### ISSUE TITLE
How to get Value from a ModalScreen without put it into redux state tree

### ISSUE THREAD

**Issue by iwater** [wix/react-native-navigation#10]
I want pick date from DatePicker using ModalScreen, the passProps only can transport serializable values, can't use a callback function, because it's a temp value, it's there any way to get value back from ModalScreen without put it into redux state tree when using react-native-navigation

**Comment by talkol** [comment]
See this related issue:
https://github.com/wix/react-native-controllers/issues/13

Please go over the solutions proposed there and participate in the discussion of how this issue should be addressed
