### ISSUE TITLE
Is it possible to pass a function to props when using navigator.push?

### ISSUE THREAD

**Issue by zocario** [wix/react-native-navigation#100]
I am playing with your great library with my iOS app and I have a weird issue.
I like the idea of passing functions through props in React components, as for InputText's onChangeText property.

```
<InputText onChangeText={ (text) => this.setState({ myText: text }) } />
```

So I tried to do the same between two views, the first is a ListView form containing a long Text (not editable). When I tap on the long text I push a new ListView using your navigator.push method to present a long InputText. I am passing in passProps a method like this:

```
this.props.navigator.push({
  ...
  passProps: {
    onChangeText: (text) => this.setState({ myLongText: text })
  }
  ...
})
```

..so I can update my state and retrieve the new entered text. But the only thing I receive in the view is an empty object. So is it possible to pass a function through passProps? If not is there an other way to retrieve the information?

<img width="905" alt="capture d ecran 2016-06-28 a 12 39 02" src="https://cloud.githubusercontent.com/assets/800617/16412595/55f21910-3d2d-11e6-8215-2308353d6a25.png">

**Comment by webzepter** [comment]
No you can't pass a function, because you can serialise it for passing through native bridge.
You can without extending:
1) Pass function code as string and `eval` it 😬
2) Pass e.g. boolean prop and new screen will run necessary function
3) Extend this library and create module with function registry (in `push` you need register props-functions and pass them in new screen during initialisation. This approach allows you have closures (like in your example with `this.setState`)

**Comment by zocario** [comment]
Thanks for the answer, it could be really nice to have this possibility in the future, as it is really a common pattern in React. For now I think I will try something like this as a temporary workaround: 
https://www.npmjs.com/package/react-native-simple-events

In my opinion options 1) and 2) would not work in this case as eval would be done in an other view, and passing a boolean doesn't allow me to have the returned value of the new screen isn't it? Am I missing something?

**Comment by webzepter** [comment]
Yes, you are right

**Comment by iosipeld** [comment]
As an alternative to @zocario solution, redux/flux action could be used to modify the state of parent component (parent component will listen to `componentWillReceiveProps` and then set a new state via `setState`).

**Comment by sshymko** [comment]
An alternative to passing a callback function is to pass an `EventEmitter` object, for example:
```js
import EventEmitter from 'EventEmitter';

let events = new EventEmitter();
events.addListener('changeText', (text) => this.setState({myText: text}));
this.props.navigator.push({
  // ...
  passProps: {
    events: events,
  }
})
```
```js
<InputText onChangeText={(text) => this.props.events.emit('changeText', text)} />
```

**Comment by grundmanise** [comment]
@sshymko - does not work. I receive "Invalid data message - all must be length: 5" error, when setting `addListener` on the `events` object.

**Comment by abhishek24bhar** [comment]
@sshymko How to receive this event on next screen

**Comment by sshymko** [comment]
@abhishek24bhar

You need to create the event emitter and pass this same instance to your screens/tabs.

I haven't worked with React Native in a while, so cannot give you an exact code example.
