### ISSUE TITLE
statusBarBlur is not working

### ISSUE THREAD

**Issue by williambout** [wix/react-native-navigation#1000]
### Issue Description

The `statusBarBlur` property is not working in the example app.

### Steps to Reproduce / Code Snippets / Screenshots

- Build the current version of the example app.
- Add the following code to a view:
```
static navigatorStyle = {
    navBarHidden: true,
    statusBarBlur: true,
  };
```
---
### Environment
* React Native Navigation version: 2.0.0-experimental.281
* React Native version:  0.41.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device, iOS 10.3, Debug and Release.

**Comment by tiempham** [comment]
I think it should work with drawer.
