### ISSUE TITLE
Glitch on pressed button in TitleBar

### ISSUE THREAD

**Issue by lndgalante** [wix/react-native-navigation#1007]
### Issue Description

I'm having some strange behavior when I keep pressed the button after a little while on the TitleBar

Is it just me ?

### Steps to Reproduce / Code Snippets / Screenshots
![glitch](https://cloud.githubusercontent.com/assets/2475912/24813288/dfea81a2-1ba3-11e7-8e59-ed9aafbf69b2.png)

---
### Environment
* React Native Navigation version: **2.0.0-experimental.285**
* React Native version: **0.43.0**
* Platform(s) (iOS, Android, or both?): **Android**
* Device info (Simulator/Device? OS version? Debug/Release?): **Galaxy S7. Android 6.0.1. Debug**

**Comment by guyca** [comment]
You need to set a `title` to each button. The grey balloon shows the button's title and pops up when user long presses on a button to explain the purpose of the button.

**Comment by Fenwil** [comment]
Ah great thanks @guyca !!

**Comment by Fenwil** [comment]
Hi @guyca. If I assign to the `title` key a empty string I have the same issue.

Reading the react-native-navigation docs it seems that there's not a key like `disableTitle`.

But on my leftButtons I'm using the default Android left button with id `sideMenu` it doesn't have this key `title` and the glitch doesn't happen. It's like it's disabled or it doesn't have one.

![menu](https://cloud.githubusercontent.com/assets/2475912/24915407/6edd316e-1ead-11e7-9b6c-224c8c19f7e6.png)

I have no problem on assigning a `title` as a workaround but it will be a nice feature for those who don't want a title in their left or right buttons.

Thanks as usual!

**Comment by guyca** [comment]
@Fenwil That's a good suggestion, I'll look into that.

**Comment by Fenwil** [comment]
Awesome!

**Comment by guyca** [comment]
We should cancel the longPress listener on the actual view if a label defined.
