### ISSUE TITLE
push to new Screen，crash！

### ISSUE THREAD

**Issue by charlesluo2014** [wix/react-native-navigation#1010]
### Issue Description

When push to a new Screen，in release mode crash！

[tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: JSON.stringify cannot serialize cyclic structures.
2017-04-08 11:56:58.312 VRCNewsApp[40780:4114994] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: JSON.stringify cannot serialize cyclic structures.', reason: 'Unhandled JS Exception: JSON.stringify cannot serialize cyclic structures., stack:
runApplication@344:1050
value@20:2722
<unknown>@20:838
<unknown>@20:106
value@20:810

### Steps to Reproduce / Code Snippets / Screenshots

push screen

---
### Environment
* React Native Navigation version: 2.0.0-experimental.0
* React Native version: 0.43.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): 10.31

**Comment by lipingruan** [comment]
object circle reference.
example: 

let a = {  };
let b= { ref: a };
a.ref = b;

a or b could not serialize.
check your code.

**Comment by charlesluo2014** [comment]
@lipingruan It is ok in debug mode，and react-native version 0.41.2 is ok too，0.42 above was crashed ！

**Comment by markymc** [comment]
I'm seeing this problem too on version 1.1.134 and RN v0.44.3. I think it's because I'm using normalizr's denormalize method. Does anyone have any workarounds? I guess I could just pass the ID and denormalize in my component.
