### ISSUE TITLE
LightBox cannot show debug panel

### ISSUE THREAD

**Issue by lipingruan** [wix/react-native-navigation#1015]
debug panel cannot show on lightbox
ios: panel below lightbox
android: cannot show panel
![img_0117-1](https://cloud.githubusercontent.com/assets/16621637/24837142/c14cf1fe-1d5f-11e7-8e7f-c415af8fd51f.png)

---
### Environment
* React Native Navigation version: 2.0.0-experimental.287
* React Native version: 0.43.2
* Platform(s) (iOS, Android, or both?): all
* Device info (Simulator/Device? OS version? Debug/Release?): all/Debug

**Comment by Ehesp** [comment]
Also the same with modals.

**Comment by ittikorns** [comment]
+1

**Comment by guyca** [comment]
Should be fixed in 1.1.128
