### ISSUE TITLE
Where to add view tracking?

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#1017]
What would be the place for sending info for example to Google Analytics that which screen the user has visited? Is there support for coming for events like this. For example `onScreenEnter` or something similar where I can send data to Google Analytics?

**Comment by guyca** [comment]
https://wix.github.io/react-native-navigation/#/screen-api?id=screen-visibility

**Comment by henrikra** [comment]
Is that global or screen specific? Because I would like to listen all screens :)

**Comment by guyca** [comment]
The event is sent to the screen that appeared/disappeared 👍

**Comment by henrikra** [comment]
Hmm okay. I think I have some make high order component or something if there isn't global listener for events like this

**Comment by gameboyVito** [comment]
@henrikra Hi, have you figured out how to listen to these events using global listener since adding onNavigatorEvent to each screen is annoying.... I have to send the trackTiming for each screen.

**Comment by sijad** [comment]
is there any other workaround? setting up `onNavigatorEvent` for each screen doesn't seems a good idea.

**Comment by guyca** [comment]
@sijad You can track screen visibility [globally](https://wix.github.io/react-native-navigation/#/screen-api?id=listen-to-visibility-events-globally). This listener was pretty much implemented to answer a specific need we had in the Wix app, maybe it will be useful to you as well.

**Comment by cosivox** [comment]
@guyca Hi there, could you please explain how or where you need to implement that code?

**Comment by aldidas** [comment]
@cosivox I found the implementation sample of this global listener [here](https://github.com/wix/react-native-navigation/blob/e8333ce1ea3bd7a54d3aa2c4fed469b266b6399d/example/src/screens/index.js#L56).

**Comment by Brunoalcau** [comment]
@cosivox When I use SharedElementTransition to call an action it does not pass through these global listenes.
Can you help me?
