### ISSUE TITLE
[Question] navigationStyle

### ISSUE THREAD

**Issue by jp928** [wix/react-native-navigation#1021]
### Cannot declare static navigationStyle inside component

(https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots
What if I declare a navigationStyle when I initiate the tab by:
``` javascript
 Navigation.startTabBasedApp({
      tabs: [
        {
          label: 'Explore',
          screen: 'mainTab.Explore',
          icon: iconsMap['compass-outline'],
          selectedIcon: iconsMap.compass,
          navigatorStyle: {
            tabBarHidden: false
          }
        }...
});
```
Then, I expect that I could override the style by a particular screen by:
```javascript
class TestComponent extends Component {
  static navigatorStyle = {
    tabBarHidden: true
  }
}
```
This doesn't work in my case, I have to use 

```javascript
this.props.navigation.push({
  screen: 'TestComponent',
  navigatorStyle: {
    tabBarHidden: true
  }
})

```
to achieve this and this is annoying.

Does anyone encounter this problem as well?

---
### Environment
* React Native Navigation version: 2.0.0-experimental.286
* React Native version: 0.43.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by cyakimov** [comment]
Happens to me as well.
