### ISSUE TITLE
Using icons in Android FAB

### ISSUE THREAD

**Issue by Ehesp** [wix/react-native-navigation#1023]
### Issue Description

Using `react-native-vector-icons` (the recommended setup way), I'd like to be able to use an icon in my FAB, rather than an image.

Currently the following works:

```js
  static navigatorButtons = {
    fab: {
      collapsedId: 'share',
      collapsedIcon: require('../../../images/cover.png'),
      backgroundColor: '#607D8B',
    },
  };
```

Setting the icon to a vector icon causes it not to render:

```
collapsedIcon: iconsMap.clear
```

Is this because it's only expecting an image?

---
### Environment
* React Native Navigation version: 290
* React Native version: 42.2
* Platform(s) (iOS, Android, or both?): Android

**Comment by Ehesp** [comment]
Note, this works when calling setButtons from componentDidMount.

**Comment by jsina** [comment]
I have same problem, `componentDidMount` workaround also didn't worked for me.

**Comment by looser** [comment]
`componentDidMount() {
this.props.navigator.setButtons({
      fab: {...}
})
}
`
does not work for me either
