### ISSUE TITLE
Tabbed Navigation. Does components remain mounted?

### ISSUE THREAD

**Issue by VictorVarghese** [wix/react-native-navigation#1024]
### Issue Description

Does this library solve the following issue?
http://stackoverflow.com/questions/38728435/possible-navigation-issue-in-react-native-redux-app

Components that are not visible remaining mounted causing screen freezes and lagging.
---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: 0.40.0* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Debug & Release

**Comment by guyca** [comment]
Screens remain mounted until they are popped. There is no lag. 👍
