### ISSUE TITLE
[ANDROID]How can i disable hairline shadow navbar?

### ISSUE THREAD

**Issue by nguyenchanhnghia** [wix/react-native-navigation#1028]
### Steps to Reproduce / Code Snippets / Screenshots
![image](https://cloud.githubusercontent.com/assets/7939078/24903925/1cfb0a98-1ed9-11e7-8ad2-c92c95a10f68.png)

---
### Environment
* React Native Navigation version: 2.0.0-experimental.281
* React Native version: 16.0.0-alpha.6
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by nguyenchanhnghia** [comment]
solution: -- topBarElevationShadowEnabled: false

**Comment by witalobenicio** [comment]
This just not work for me. I'm using SingleScreenApp. Just doesn't work :(

**Comment by ahtesham-shah** [comment]
but where to insert topBarElevationShadowEnabled: false
