### ISSUE TITLE
Tab based navigation with mix of Native and React views.

### ISSUE THREAD

**Issue by PadmaPreethi** [wix/react-native-navigation#1029]
### Issue Description

 I'm trying to integrate react-native-navigation in our current app. Our app is a hybrid of Native + React Native.However our Tab and Navigation system is fully native. I'm trying to create a tab based navigation using react-native-navigation. Out of 5 tabs, 3 tabs are React views and 2 are native view controller. How can this be handled using react-native-navigation ? Should we need to create a JS counterpart for those native view ?

### Environment
* React Native Navigation version: 2.0.0-experimental.296
* React Native version: 0.43.1
* Platform(s) (iOS, Android, or both?): iOS

**Comment by jp928** [comment]
IMPO, https://github.com/airbnb/native-navigation is better choice if you have to mix native with react native.

**Comment by PadmaPreethi** [comment]
@jp928 : So that's not possible with react-native-navigation ?

**Comment by PadmaPreethi** [comment]
@jp928 : On going through the implementation details, i can see a protocol defined for addExternalVCIfNecessary to support  3rd party native controllers. This basically adds the specified native controller as child controller.

**Comment by PadmaPreethi** [comment]
@DanielZlotin : Any help around this front would be helpful. I saw couple of other threads and found that support for integrating with current native view controllers with RNN is not possible. But there is a protocol defined in RNN called addExternalVCIfNecessary to support 3rd party VC's. Can we make use of this ?
