### ISSUE TITLE
TextInput behind navBar doesn't catch the tap

### ISSUE THREAD

**Issue by Fenwil** [wix/react-native-navigation#1031]
### Issue Description

I want that the native _navBar_ (AndroidNavigationBar) only takes the event for the back button because beside it I have a TextInput that I want to take the input when the user taps on it.

I can only take the input thanks to the _autoFocus={true}_ but after that I press outside I cannot longer be able to focus on the input again.

### Steps to Reproduce / Code Snippets / Screenshots

Some extra code is deleted just to see the important parts.

```jsx
class Search extends Component {
  static navigatorStyle = {
    navBarButtonColor: colors.white,
    navBarTextColor: colors.white,
    navBarTransparent: true,
    drawUnderbar: true,
  };

  constructor() {
    super();
    const ds = new ListView.DataSource({ rowHasChanged: (r1, r2) => r1 !== r2 });
    this.state = {
      dataSource: ds.cloneWithRows([]),
      keyboardActive: true,
    };
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.header}>
          <TextInput
            ref={ref => this.searchInput = ref}
            autoFocus={true}
            blurOnSubmit={true}
            onFocus={this.handleFocus}
            onBlur={this.handleBlur}
            onSubmitEditing={this.handleSubmitEditing}
            placeholder={'Search'}
            placeholderTextColor={colors.white}
            underlineColorAndroid="transparent"
            onChangeText={this.searchDataDebounced}
            style={styles.input}
            returnKeyType="search"
          />
        </View>
      </View>
    );
  }
}
```

First time I enter to the screen:

![screen shot 2017-04-11 at 12 11 51 pm](https://cloud.githubusercontent.com/assets/2475912/24916327/36ce7ff0-1eb0-11e7-9003-089b990c57fc.png)

When I tap outside the TextInput and I want to tap again (but the event now it's handle by the native view on top I guess)
![screen shot 2017-04-11 at 12 12 34 pm](https://cloud.githubusercontent.com/assets/2475912/24916354/488bb8e8-1eb0-11e7-8e5f-458fe67715a6.png)

---
### Environment
* React Native Navigation version: **0.43.0**
* React Native version: **v2.0.0-experimental.289**
* Platform(s) (iOS, Android, or both?): **Android**
* Device info (Simulator/Device? OS version? Debug/Release?): **Simulator / Android 7.0.0 API 24 / Debug**

**Comment by guyca** [comment]
Hey @Fenwil 
We plan on adding support for custom react views in navBar real soon. But until then, why don't you use your own custom navBar instead for this screen?

You can show this screen with `navBarHidden: true` in `navigatorStyle` and use any implementation you want. Should work just as fine for you

**Comment by Fenwil** [comment]
Thanks @guyca that is what I did trying to replicate the default navBar.

**Comment by guyca** [comment]
@Fenwil Not sure I understand the issue then. You are using your own custom navBar, and it's not clickable because something is blocking touch events?

**Comment by Fenwil** [comment]
No. What I meant is that I already did what you say and it works perfectly 😄
You can close this issue if you want.

**Comment by guyca** [comment]
gotcha. #967 will add support for custom views in navBar for iOS, Android will follow soon after, closing for now :)

**Comment by hoorsa** [comment]
is there a way to use topTabs under my own custom navBar?
