### ISSUE TITLE
[iOS] Swipe back gesture doesn't work anymore

### ISSUE THREAD

**Issue by Crash--** [wix/react-native-navigation#1033]
### Issue Description

When I push a screen, I can't go back anymore to the previous screen with a swipe gesture. It can be related to https://github.com/wix/react-native-navigation/commit/28014d657838a322a9f5e1c34bf9d9c95cc05ef0#diff-bf319e6382b680d324b4066dabe1377e or https://github.com/wix/react-native-navigation/commit/03d380f8a9d2fba5d4baf6815201fcebdcfa18c9#diff-bf319e6382b680d324b4066dabe1377e since a few weeks ago it works as expected.

### Steps to Reproduce / Code Snippets / Screenshots

just push a screen, and try to go back by swiping

---
### Environment
* React Native Navigation version: master
* React Native version: 0.42
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by Crash--** [comment]
If I revert this one https://github.com/wix/react-native-navigation/commit/03d380f8a9d2fba5d4baf6815201fcebdcfa18c9#diff-bf319e6382b680d324b4066dabe1377e it works

**Comment by dev-two** [comment]
I'm facing the same issue.

The problem is reverting this commit causes more strange bugs, breaking navbar and pushes.

**Comment by pcfutures** [comment]
I fixed this by updating to the latest version (currently 1.1.205) and rebuilding/reinstalling the app on the device. Seems to have fixed it.

**Comment by gran33** [comment]
@pcfutures Thanks for reporting.

**Comment by dev-two** [comment]
Well, unfortunately, updating to latest version not worked for me. But @Crash--'s solution still works, but not seems like best way to handle it.

**Comment by pcfutures** [comment]
@gran33 looks like this is still an issue, might want to re open it.
