### ISSUE TITLE
[Question] statusBarColor on Android Modals

### ISSUE THREAD

**Issue by tolu360** [wix/react-native-navigation#1034]
### Issue Description

Is there a way to set a `statusBarColor` when a `modal` view is displayed? Currently, the status bar is always black whenever a modal is opened, regardless of the value of `statusBarColor` set on the `navigatorStyle`.

### Steps to Reproduce / Code Snippets / Screenshots

Just launch a modal as usual:

```javascript
this.props.navigator.showModal({
	title: 'My Title',
	screen: 'myapp.Settings',
	animationType: 'slide-up',
});
```
Observe the status bar color on the modal view displayed.

---
### Environment
* React Native Navigation version: 2.0.0-experimental.296
* React Native version: 0.42.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):Emulator (API 25)

**Comment by tolu360** [comment]
Thanks for all you do @guyca - would be pulling in this release shortly.

Cheers.

**Comment by tolu360** [comment]
@guyca, after pulling in `2.0.0-experimental.299`, I can confirm I can now have the status bar in my chosen color but I observe like a flicker when the status bar color goes from black to my chosen color while the modal is appearing.

I just wanted to provide some feedback. Thanks.

**Comment by guyca** [comment]
Hey @tolu360, thanks for the feedback. I didn't notice a flicker, will check again tomorrow.

**Comment by tolu360** [comment]
@guyca, if can figure out screen-casting, would share a gif or something for you to see. Were you trying it out on the example app? I could take a look there if you did.

**Comment by guyca** [comment]
We should probably render our ui by default under the status bar, that way we can control the color animation etc

**Comment by tolu360** [comment]
Hey @guyca, kudos for revisiting this yet again!
