### ISSUE TITLE
Push new screen in lightbox

### ISSUE THREAD

**Issue by ziftinpeki** [wix/react-native-navigation#1035]
Hi folks,

i'm trying go to a new screen with this.props.navigator.push({...}) from lightbox screen but it doesn't work. Do you have any suggestion for me? 

"react": "16.0.0-alpha.6",
"react-native": "0.43.0",
"react-native-navigation": "^2.0.0-experimental.297"

thanks for advice,
m.

**Comment by guyca** [comment]
Hey there - that's not supported. :)

**Comment by kmdupr33** [comment]
Is this still not supported? I actually have this working sometimes.

**Comment by krisnailafat** [comment]
> Is this still not supported? I actually have this working sometimes.

how you do it ?
