### ISSUE TITLE
[iOS] statusBarHidden does not hide the StatusBar

### ISSUE THREAD

**Issue by cyakimov** [wix/react-native-navigation#1037]
### Issue Description

`statusBarHidden` and `statusBarHideWithNavBar` does not hide the `StatusBar`.

### Steps to Reproduce / Code Snippets / Screenshots

![img_0062](https://cloud.githubusercontent.com/assets/232124/24962161/79f67762-1f71-11e7-8bfb-c4242347ec9c.PNG)

```js
export default class MyScreen extends Component {
  static navigatorStyle = {
    navBarHidden: true,
    statusBarHidden: true,
    statusBarHideWithNavBar: true,
  };
}

export default class App extends Component {
  constructor(props) {
    super(props);
    this.startApp();
  }

  startApp() {
    Navigation.startSingleScreenApp({
      screen: {
        screen: 'MyScreen',
        navigatorStyle: {
          navBarHidden: true,
          statusBarHidden: true,
          statusBarHideWithNavBar: true,
        }
      },
    })
  }
}
```

---
### Environment
* React Native Navigation version: `v2.0.0-experimental.297`
* React Native version: `0.43.1`
* Platform(s) (iOS, Android, or both?): `iOS`
* Device info (Simulator/Device? OS version? Debug/Release?): Tested on `iPad Air 2` (Simulator) and `iPad Mini` (Real device).

**Comment by X-Tender** [comment]
Doesn't work on Android too.

**Comment by tafelito** [comment]
I'm having the same issue here. statusBarHidden seems to not be doing anything in Android or iOS.

I am able to change the statusBar color though

Any ideas?

Thanks!

**Comment by mobinni** [comment]
turn this on in your info.plist and it should work:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<true/>
</plist>
```

**Comment by wwwdata** [comment]
Nice this works, this should definitly be in the documentation :D

**Comment by qasimalbaqali** [comment]
Following @mobinni instructions, I get `RTStatusBarManager module requires that the UIViewControllerBasedStatusBarAppereance key in the Info.plist is set to NO`. Any ideas?

**Comment by L-Yeiser** [comment]
I am still seeing this issue.

**Comment by maulikdhameliya** [comment]
I tried statusBarHidden, statusBarHideWithNavBar
neither of them is working .

**Comment by adirzoari** [comment]
@christianlippa  same issue. did you find solution?
