### ISSUE TITLE
Content above navbar

### ISSUE THREAD

**Issue by chrise86** [wix/react-native-navigation#1039]
Trying to use something like https://github.com/testshallpass/react-native-dropdownalert does not work as the dropdown appears behind the navbar. Wrapping the component in a `Modal` / `RCTModalHostView` means that the modal overlays the whole screen and does not provide the required effect. Using `Modal` means it needs to be dismissed before being able to interact with anything else on screen, which is not what we want here.

Is there any way of achieving the desired effect?

**Comment by tolu360** [comment]
Hello @chrise86, I think `react-native-navigation`'s `InAppNotification` is what you want. Check out an [example usage](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/FirstTabScreen.js) in the example app in this very repo. A perfect replacement for `dropdownalert`. Might be worth your while inspecting the complete source of the example app and running it locally too.

**Comment by chrise86** [comment]
I just did, thanks very much! 👍

**Comment by chrise86** [comment]
Couldn't see anything related to it in the docs, might be worth mentioning it? Apologies if it is there and I've just missed it.

**Comment by tolu360** [comment]
You welcome @chrise86, might be a good catch - I haven't looked in the docs for it though.

**Comment by felipemartim** [comment]
I was also trying to use https://github.com/testshallpass/react-native-dropdownalert as I haven't seen anything on the docs. Fortunately, I stumbled across this github issue. Thanks @tolu360!
