### ISSUE TITLE
[android] Fail to start official example due to startTabBasedApp

### ISSUE THREAD

**Issue by alvarogtraveso** [wix/react-native-navigation#1041]
### Issue Description

I was trying the [official example](https://github.com/wix/react-native-navigation/tree/master/example), but I found that fails to start when the app is closed. This happens on Android with a real device.

### Steps to Reproduce

1. Compile everything, launch with react-native run-android
1. The app starts ok
1. Close the app
1. Unplug the device
1. Start the app again -> It won't start

I have no log to know what is happing, I think the issue could be related with `Navigation.startTabBasedApp` because I tried with `startSingleScreenApp` and there is no problem to close and start the app as many times as I want.

---
### Environment
* React Native Navigation version: next
* React Native version: 0.41.2
* Platform(s) (iOS, Android, or both?): Android only
* Device info (Simulator/Device? OS version? Debug/Release?): Device. Android 5.1.1. Debug

**Comment by oky1** [comment]
I have the same problem on the Android device 4.2.

**Comment by guyca** [comment]
Device needs to be plugged to usb when in debug mode. The crash is that it can't load images because server isn't found
