### ISSUE TITLE
Duplicate protocol definition of 'RCTBridgeModule' is ignored

### ISSUE THREAD

**Issue by jaggerwang** [wix/react-native-navigation#1045]
### Issue Description

Build error on iOS, "Duplicate protocol definition of 'RCTBridgeModule' is ignored"

### Steps to Reproduce / Code Snippets / Screenshots

Open Xcode, and click Play button.

![image](https://cloud.githubusercontent.com/assets/1255011/25041674/293ad348-2144-11e7-852d-ec57619e5b31.png)

---
### Environment
* React Native Navigation version: 2.0.0-experimental.299
* React Native version: 0.43.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 5s 10.3 simulator

**Comment by Crash--** [comment]
You should use .330 see https://github.com/wix/react-native-navigation/issues/924#issuecomment-294123568
