### ISSUE TITLE
Regarding Redux Provider, What's the point

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#1048]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by Ehesp** [comment]
So you can have Redux in each of your screens?

**Comment by DanielZlotin** [comment]
You are right, this will no longer be needed in the next major version

**Comment by smooJitter** [comment]
Daniel. What do mean by no longer needed.  I apologize I didn't submit my concerns.  I always thought it was an after thought implementation anyway.  Futhermore, the redux example is no longer maintained.  Without shipping with action creators and a RNN reducer, I don't see the value of registering redux components.  I'd like to use the ApolloProvider which is the redux store yet extended with a client={} prop. Although the recent versions support spreading options, the implementation is not so straight forward.  My question is, will the next major release support a tighter integration with redux or will you remove it all together and leave it up to us to inject redux state dependencies ( recompose would be useful here)?

**Comment by DanielZlotin** [comment]
You're right, it was an afterthought. In the next major release this will be removed altogether, as any props you provide will be passed to the screen component. Tighter integration with redux is not a good idea in my opinion as we shouldn't force any one specific data flow library.

If need arises we can provide some utility wrapper functions to help with integrations, but I don't think this will be necessary
