### ISSUE TITLE
Styling topTabs

### ISSUE THREAD

**Issue by elliotstokes** [wix/react-native-navigation#1049]
### Issue Description

Ive tried adding

```
tabSelectedTextColor: '#FFFFFF',
        tabNormalTextColor: '#FFFFFF',
        tabIndicatorColor: '#FFFFFF',
``` 
into the first navigator that gets shown and adding them into the appStyle property of the start call but I cant change the tab underline color or the tab text color. They appear as default. Is this supported at all? Ive seen examples in the deprecated stuff but nothing in the new documentation. The tabs, other than the styling are all working great (currently on 2.0.0-experimental.268)

---
### Environment
* React Native Navigation version: 2.0.0-experimental.268
* React Native version: 0.42
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator

**Comment by thevest** [comment]
Had this same issue, you can find all the options [here](https://github.com/wix/react-native-navigation/blob/3948776dac2ae6f447dc299942b650a789a27d59/android/app/src/main/java/com/reactnativenavigation/params/StyleParams.java)

```java
    public Color topTabTextColor;
    public Color topTabIconColor;
    public Color selectedTopTabTextColor;
    public Color selectedTopTabIconColor;
    public int selectedTopTabIndicatorHeight;
    public Color selectedTopTabIndicatorColor;
    public boolean topTabsScrollable;
```

**Comment by salisuabubakar** [comment]
Please how do i change topTab  text font size and font weight.  Thanks

**Comment by ahmetbadur** [comment]
@AvijitDutta95 You can change the navigator font family style by typing the following code..

`static navigatorStyle = {
  ...
  topTabTextFontFamily: 'BioRhyme-Bold'
  ...
}`
