### ISSUE TITLE
startSingleScreenApp not supporting orientation portrait on iOS.

### ISSUE THREAD

**Issue by jaggerwang** [wix/react-native-navigation#1050]
### Issue Description

Tried the following method on Android.
```
  Navigation.startSingleScreenApp({
    ...
    appStyle: {
      orientation: 'portrait',
    },
  });
```
```
  Navigation.startSingleScreenApp({
    ...
    portraitOnlyMode: true,
  });
```
The appStyle method is working for startTabBasedApp on Android. and on iOS only need to uncheck landscape in Xcode.

---
### Environment
* React Native Navigation version: 2.0.0-experimental.300
* React Native version: 0.42
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device and debug

**Comment by guyca** [comment]
@jaggerwang 
orientation portrait works for me in `singleScreenApp`. I tried the following in the example app:

```js
Navigation.startSingleScreenApp({
 screen: {
   screen: 'example.FirstTabScreen',
   title: 'Navigation'
 },
  appStyle: {
    orientation: 'auto'
  }
});
```

**Comment by zsajjad** [comment]
@guyca Not working for me!
