### ISSUE TITLE
Unhelpful error message: undefined is not an object (evaluating 'InternalComponent.navigatorStyle')

### ISSUE THREAD

**Issue by guthriec** [wix/react-native-navigation#1052]
### Issue Description

The project builds fine, but I'm getting this error immediately on app start in the iPhone 7 simulator. I'll believe it's a problem with my code, but I grepped my source folder for "navigatorStyle" and didn't find anything. I just got started on the project, and I've done my best to follow the examples to a T. I'd gotten to a point where the bottom tab bar was working perfectly, when it started breaking. I've tried re-installing the module and cleaning Xcode and all that good stuff.

It'd nice as a developer to get a more informative error message so I had some clue where to look to correct the problem.

### Steps to Reproduce / Code Snippets / Screenshots

<img width="369" alt="screen shot 2017-04-15 at 11 08 42 am" src="https://cloud.githubusercontent.com/assets/1740665/25065875/28cfa27a-21cc-11e7-8849-82791a7ad7fa.png">

---
### Environment
* React Native Navigation version: experimental.300, experimental.277
* React Native version: 0.43.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 7 simulator

**Comment by guyca** [comment]
I see the error occurs right when you try to start the app, perhaps one of your screens does not extend `Component` or exports by default something that is not a component?

**Comment by guthriec** [comment]
Turned out I was doing
import { MyComponent } from './components/my_component'
instead of
import MyComponent from './components/my_component'
