### ISSUE TITLE
ERROR: Image source size {21, 21} does not match loaded image size {16, 16}

### ISSUE THREAD

**Issue by zcgong** [wix/react-native-navigation#1057]
### Issue Description
ERROR: Image source size {21, 21} does not match loaded image size {16, 16}
### Steps to Reproduce / Code Snippets / Screenshots

on Simulator the json in 
> + (RCTImageSource *)RCTImageSource:(id)json 
is 
```
{
    "__packager_asset" = 1;
    height = 23;
    scale = 2;
    uri = "http://localhost:8081/assets/src/image/mit_them_icons/search@2x.png?platform=ios&hash=709ed6bb87e349b8e856fcfddea3758b";
    width = 21;
}
```
on Device the json is 
```
{
    "__packager_asset" = 1;
    height = 21;
    scale = 2;
    uri = "/var/containers/Bundle/Application/809D4122-FFA6-4751-91BD-D6C2BE5383A7/MobileOA.app/assets/src/image/mit_them_icons/scanner@2x.png";
    width = 21;
}
```
almost the same.

But when do this 
> image = assetName ? [UIImage imageNamed:assetName] : nil;

result is different.
on Simulator the image size  is {21, 21}, but on Device the size is {16, 16}, why?
---
### Environment
* React Native Navigation version: next
* React Native version:0.43.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device  Debug

**Comment by pqkluan** [comment]
@zcgong Could you update the info & status on this issue?
