### ISSUE TITLE
Invalid layout for (133) ... on iOS when upgrade RN to 0.43

### ISSUE THREAD

**Issue by kevinvn1709** [wix/react-native-navigation#1058]
### Issue Description
I have just upgraded RN to 0.43 and I got a tricky bug on iOS platform. I use `startTabBasedApp` with 3 screens, one of these included `react-native-scrollable-tab-view` component that placed on the third tab. When I stared app, it produced the error below. But when I placed this screen on first tab, it runs very well without any problem. So, I have no idea to fix this bug.

### Steps to Reproduce / Code Snippets / Screenshots
![image](https://cloud.githubusercontent.com/assets/1281425/25109899/6395f004-240a-11e7-8d96-f1e1f1a26f40.png)

---
### Environment
* React Native Navigation version: v2.0.0-experimental.301
* React Native version: 0.43
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by kevinvn1709** [comment]
I had dig deeper into source code, and I found that it got error at onLayout event of View. 
Maybe it comes from RN 0.43

**Comment by PadmaPreethi** [comment]
@kevinvn1709 : Isn't v2.0.0-experimental.301 has dependancy on RN-0.38 ? After upgrading my project to RN-0.43, i had compile issues with react-native-navigation as it was referencing React header files in older format. Can you please let me know how were you able to get the project running with RN-0.43 and v2.0.0-experimental.301?

**Comment by grin** [comment]
Not sure if it's related to your problem, but upgrading my iOS app to  RN 0.43 broke visual layout of some of my components. My app is also tab based and during testing I found that disabling tabs by switching the app from `startTabBasedApp` to `startSingleScreenApp` fixes the layout issues. Seems like tabs are somehow messing up layout calculations 😕 

But I'm not getting any red box errors like you are.

**Comment by grin** [comment]
@kevinvn1709 as per your issue, you may want to take a look at this thread: https://github.com/facebook/react-native/issues/11506

**Comment by atlas1119** [comment]
do you fixed your problem？@kevinvn1709

**Comment by kevinvn1709** [comment]
@atlas1119: I have upgraded RN to 0.44 and it fixed this problem

**Comment by kevinvn1709** [comment]
#1109
