### ISSUE TITLE
showModal is very slow on large screen

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#1059]
Hi all,

showModal working fire on my application. But with large screen, here i have a ListView about > 100 rows. When user click icon at leftButton header => a new screen show using showModal. It very very slow. 

I also tried change ListView to FlatList, showModal to showLightBox and same problem.

---
### Environment
* React Native Navigation version: ^2.0.0-experimental.300
* React Native version: "^0.43.3"
* Platform(s) (iOS, Android, or both?): IOS, Android is good!
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by guyca** [comment]
Hey @agumack 
If you push that screen, is the push also taking a long time?

**Comment by agumack** [comment]
yep @guyca , I have just tried push and same  problem.

**Comment by guyca** [comment]
@agumack It might be wort trying to optimize the list, maybe use [initialListSIze](https://facebook.github.io/react-native/docs/listview.html#initiallistsize), I don't think this is an issue with RNN since all we do is create a root view and render it. For the most part we're not aware of the screen contents.

**Comment by agumack** [comment]
I have use initialListSIze.
I also tried onEndReached for loadmore row. but about > 50rows then I open showModal, very slow : (
 I don't know why,

**Comment by agumack** [comment]
and problem only IOS

**Comment by guyca** [comment]
I'm not sure it's related to rnn. We have lists with hundred of items, they load pretty much instantly on iOS. Maybe the Js thread is under stress only on iOS. (is there a feature perhaps you support only on iOS?)

**Comment by agumack** [comment]
@guyca I found the cause
I have use "nativebase" ui, here is ListItem, i tried instead it with <View> normal and now perfomance good. 

Problem at ListItem component nativebase : )

Thanks @guyca

**Comment by guyca** [comment]
Glad to hear 👍

**Comment by ashokkumar88** [comment]
use recyclerlist view https://github.com/Flipkart/recyclerlistview. It is very performant
