### ISSUE TITLE
No animation on android

### ISSUE THREAD

**Issue by inetfuture** [wix/react-native-navigation#106]
I pulled the latest example, ran on my Android phone(Huawei honor 6, Android 6.0), push/pop screen works but with no animation at all, any idea what could be wrong? 

Also the lighbox and modal doesn't work, are they not supported?

Thanks.

**Comment by guyca** [comment]
Lightbox is not supported. What didn't work in Modals?

**Comment by inetfuture** [comment]
> What didn't work in Modals?

Complains that `undefined is not an object(evaluating 'Screen.navigatorButtons')`

What about animations?

**Comment by cesardeazevedo** [comment]
I take a look at the source, and it seems that the Modal component haven't been registered on the [index.android.js](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/index.android.js#L14-L19), and i just copied as the [index.ios.js](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/index.ios.js#L19) and added a `backgroundColor: 'white'` on [ModalScreen.js](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/ModalScreen.js#L24) and worked perfectly.

**Comment by cihancil** [comment]
I downloaded example project. It works great on iOS. 

Navigation animations does not work on Android at all.

**Comment by ccokme** [comment]
@cihancil Same issue, there is no push/pop animation on Android, IOS works fine. 
@guyca Can you help to add this feature to the roadmap? thanks!

**Comment by guyca** [comment]
@ccokme @cihancil 
Android will support screen transition animations in the next release (v2.0)
