### ISSUE TITLE
<React/RCTRootView.h> file not found

### ISSUE THREAD

**Issue by PadmaPreethi** [wix/react-native-navigation#1061]
### Issue Description

After upgrading RN to 0.43.3, i'm getting error in react-native-navigation for header file not found.I tried following things, but does not seem to work,

1) In Xcode, go to the project scheme (Product -> Scheme -> Manage Scheme -> double click your project).
2) Click on the 'Build' option at the left pane.
3) Uncheck 'Parallelize Build' under Build Options.
4) Then in Targets section, click '+' button then search for 'React'. Select it and click 'Add'.
5) 'React' should now appear under Targets section. Click and drag it to the top so that it will be the first item in the list (before your project).
6) Clean the project and build.

<img width="920" alt="screen shot 2017-04-18 at 4 57 24 pm" src="https://cloud.githubusercontent.com/assets/13163772/25128737/738beb32-2458-11e7-9349-3eba48cf164d.png">

### Environment
* React Native Navigation version: 
    "react-native-navigation": "git+https://github.com/wix/react-native-navigation.git#v2.0.0experimental.304"

* React Native version: 0.43.3

* Platform(s) (iOS, Android, or both?): iOS

**Comment by PadmaPreethi** [comment]
Any update on this ? Looks like RN Navigation isn't able to resolve any of the react classes !

**Comment by PadmaPreethi** [comment]
@gran33 : Just to give additional context, We add react dependancy via pod, 

  pod 'React',
  :path => 'node_modules/react-native',
  :subspecs => [
    'ART',
    'Core',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
And Cocoapods automatically sets the header search paths for the dependancies. Is this because of pods, RN Navigation is not able to resolve the React headers ?

**Comment by varungupta85** [comment]
I am assuming that you were already on react native version > `.40` i.e. you didn't have to update any other imported libraries to update the headers. I also ran into similar issues when I upgraded from react-native `.37` to `.42` and had to update all the imported libraries also. For me, some of the issues arose from just Xcode not able to link stuff correctly which were resolved by either restaring Xcode or removing and the adding the affected project back. Not much of an answer but something that you could try.

**Comment by PadmaPreethi** [comment]
@varungupta85 : Yes, i'm on 0.43.3 RN version. I tried removing and adding affected project back. Did a fresh install of this package and linked it again.And did couple of other things. But nothing worked. If i remove this lib from my project, it compiles fine. So the problem is with header search paths of this library and that's the reason it's not able to resolve the react headers.

**Comment by varungupta85** [comment]
@PadmaPreethi I followed this tweet while upgrading where I had to empty out the header search paths in order for things to work properly in Xcode.

https://twitter.com/skellock/status/818813810781908992/photo/1

**Comment by gran33** [comment]
@PadmaPreethi Have follow [this](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html) instruction before u install react-native-navigation?

**Comment by PadmaPreethi** [comment]
@varungupta85 : Yes, i already tried doing all those.

**Comment by PadmaPreethi** [comment]
@gran33 : Unable to find any of react headers in react-native-navigation lib. All other libraries compiles fine.

**Comment by joshyhargreaves** [comment]
I'm seeing this issue too.

**Comment by joshyhargreaves** [comment]
@PadmaPreethi modifying the `header search paths` of `ReactNativeNavigation.xcodeproj`in such a way would mean `<React/RCTRootView.h>` would need to be modified to be a local include: i.e. `"RCTRootView.h"`. Did you have any luck with this?

**Comment by joshyhargreaves** [comment]
I played around with adding a PodSpec to this project and I got it to compile the project and added it as a dependency to my `PodFile` like so: `pod 'react-native-navigation', :path => '../node_modules/react-native-navigation'`. Disclaimer: this is purely trial and error, I'm not exactly sure of the subtleties when creating a `podspec`. I've yet to include a header from `react-native-navigation` as XCode doesn't seem to be picking them up; I need to double check which headers are being copied with the properties of the `podspec`. 

I'd imagine adding a valid `podspec` to `react-native-navigation`, like Airbnb have done for `react-navigation` would be a useful thing to do, so if this works I'll submit a PR. 

PodSpec is here: https://gist.github.com/joshyhargreaves/f972f4985f1c8e94d427cae3b2ea7513

**Comment by PadmaPreethi** [comment]
@joshyhargreaves  : Thanks ! Let me try adding the Podspec and check.

**Comment by joshyhargreaves** [comment]
@PadmaPreethi any luck?

**Comment by PadmaPreethi** [comment]
@joshyhargreaves : Yes , it worked. Please raise a PR for the posdpec. Sorry didn't get time to work on this. Hence delayed.

**Comment by joshyhargreaves** [comment]
Podspec is in the v2 branch now!

**Comment by joshyhargreaves** [comment]
You can probably close the issue.

**Comment by PadmaPreethi** [comment]
Is v2 branch ready to use ? @joshyhargreaves

**Comment by joshyhargreaves** [comment]
Is a good question actually, one which I'm unsure of, it might be worth also adding a podspec to the v1 branch also.

**Comment by PadmaPreethi** [comment]
@joshyhargreaves : Though i got it up and running fine. I'm having issue with integrating a mix of native and react views in tab bar. I have raised an issue sometime back, but haven't got any reply - https://github.com/wix/react-native-navigation/issues/1029.

**Comment by James2516** [comment]
@josephdscs @PadmaPreethi 
I added the `.podspec` file from v2 branch and included 
```pod 'ReactNativeNavigation',
    :podspec => "../node_modules/react-native-navigation/ReactNativeNavigation.podspec"
```
to the Podfile, but still getting the same file not found error.

Can you please help to check what else I'm missing? I have been stuck at this for days... https://github.com/James2516/expo-native-nav

**Comment by angelafield** [comment]
I've been stuck on this for a couple days too...
Have tried altering header search paths, installing via Podfile, etc.
`'React/RCTEventEmitter.h' file not found`

**Comment by James2516** [comment]
@angelafield do you tick or untick "Find Implicit Dependencies"? 
Do you still create a `Libraries` folder and add the `ReactNativeNavigation.xcodeproj` under it in your main project, or is the pod install sufficient? 

I have tried various configs without luck.
Can you take a look at https://github.com/James2516/expo-native-nav or https://github.com/James2516/expo-native-nav/tree/react-native-navigation to see what's missing?

Or do you have a demo project of successful integration of react-native-navigation with expo?
Thanks.

**Comment by liamse** [comment]
I see this issue most the time when I want to run example of libraries like wix/react-native-camera-kit/example out of the box. In this situation, when I open the xcodeproj file, I see the Libraries icons color is pale. This show me I need to run `npm install` to download all require modules and libraries. 

To xcode understand the files is changed, I close and reopen it. (I clean the project, but xcode does not refresh libraries)

**Comment by EgidioCaprino** [comment]
I have the `'React/RCTRootView.h' file not found` error. How did you fix that?
