### ISSUE TITLE
How to hide title bar (and more questions about global styling?

### ISSUE THREAD

**Issue by lappalj4** [wix/react-native-navigation#1062]
Hey, I'm trying to implement the latest version of this library (2.0.0-experimental.302 at the time of writing this). I can't figure out how to use all of the styling options available.

First, I would like to get rid of the title bar that displays at the top of the App, with the name of my App in it. I could easily do that in my child screens with

```
navigatorStyle: {
  navBarHidden: true,
  ...
}
```

But the same does not work for appStyle. 

Second, I would like to set a global style for all of the screens in my app, which I could then override where needed. Currently the only way I got styling to work was setting the style separately for all of my tabs (I'm building a tab based app). Is there a way to do that?

Here's my root Navigator config for reference. NavigatorStyles.baseStyle() is the same as the default styles with the exception of ```navBarHidden: true```.

```
startApp() {
    Navigation.startTabBasedApp({
      tabs: [
        {
          label: 'Home', 
          screen: 'MyApp.Home', 
          icon: require('./assets/activity-home.png'), 
          selectedIcon: require('./assets/activity-home.png'), 
          title: 'Home', 
          navigatorStyle: NavigatorStyles.baseStyle(),
          navigatorButtons: {} 
        },
        {
          label: 'Shop', 
          screen: 'MyApp.Shop', 
          icon: require('./assets/activity-shop.png'),
          selectedIcon: require('./assets/activity-shop.png'), 
          title: 'Shop', 
          navigatorStyle: NavigatorStyles.baseStyle(),
          navigatorButtons: {}
        },
        ...
      ],
      tabsStyle: { 
        tabBarButtonColor: '#ffff00', 
        tabBarSelectedButtonColor: '#ff9900', 
        tabBarBackgroundColor: '#551A8B' 
      },
      appStyle: {
        orientation: 'portrait',
        titleBarHidden: true, //Does not work...
        navBarHidden: true //Does not work...
      },
      passProps: {},
      animationType: 'slide-down'
    });
}
```

**Comment by lappalj4** [comment]
Ok, I resolved the first issue. It was to do with the theme set for my app in styles.xml. Setting that to a theme extending a NoActionBar theme such as ```parent="Theme.AppCompat.Light.NoActionBar"``` did the trick. 

Still wondering about the second thing though, so I won't close this yet.

**Comment by guyca** [comment]
Hey @lappalj4 
If you want to define a theme for your app, you can add `appStyle` as shown [here](https://github.com/wix/react-native-navigation/blob/20ca76331c029d2e0f3a9c49bd5955eebf49d2d5/example/src/app.js#L63) but unfortunately this is only available on Android. So perhaps your best option is to define style once and use spread in each screen.
