### ISSUE TITLE
static events

### ISSUE THREAD

**Issue by DanielZlotin** [wix/react-native-navigation#1078]
add support to listen to static events (those not related to a specific container) like appLaunched (already implemented) or screen appeared or disappeared

```js
Navigation.events().registerAppLaunchedListener(() => {});
Navigation.events().registerComponentDidAppearListener((componentId, componentName) => {});
Navigation.events().registerComponentDidDisappearListener((componentId, componentName) => {});
Navigation.events().registerCommandListener((commandName: String, params: Any) => {}); // [push, pop, showModal...] (from JS, without crossing the bridge)
Navigation.events().registerCommandCompletedListener((commandId: String, completionTime: Number) => {}); // from native
Navigation.events().registerNativeEventListener((name: String, params: Any) => {});
```

- [x] registerAppLaunched
- [x] registerComponentDidAppear
- [x] registerComponentDidDisappear
- [x] Remove onNavigationButtonPressed in favor of `registerNativeEventListener`
- [x] registerNavigationCommandListener
- [x] registerNavigationCommandCompletedListener

# Native events
## NativeEvent - User Actions
```js
{
  name: 'bottomTabSelected', // back, bottomTabSelected, topTabSelected
  params: {
    selectedTabIndex: Number,
    unselectedTabIndex: Number
  }
}
```

### Android
- [x] TopBar button press
- [x] Bottom tab selected
- [x] Bottom tab reselected
- [ ] TopTab button press
- [ ] ~~Back button, software and hardware~~

### iOS
- [x] TopBar button press
- [x] Bottom tab selected
- [x] Bottom tab reselected
- [ ] TopTab button press
- [ ] ~~Back button, software and hardware~~
- [ ] ~~Back gesture (iOS)~~

## Command Completion
When a command completes, a `nativeEvent` should be emitted with the `commandId` and the `timestamp` when the command completed.
```js
{
  commandId: Number, // Each command which originates in Js is assigned an id
  completionTime: Number // timestamp taken on animation end
}
```

### Android
- [x] setRoot
- [x] push
- [x] setStackRoot
- [x] pop
- [x] popTo
- [x] popToRoot
- [x] showModal
- [x] dismissModal
- [x] dismissAllModals
- [x] showOverlay
- [x] dismissOverlay

### iOS
- [x] setRoot
- [x] push
- [x] setStackRoot
- [x] pop
- [x] popTo
- [x] popToRoot
- [x] showModal
- [x] dismissModal
- [x] dismissAllModals
- [x] showOverlay
- [x] dismissOverlay

**Comment by guyca** [comment]
@DanielZlotin Can you please add a description to this issue?

**Comment by DanielZlotin** [comment]
TODO: remove `RNN.componentLifecycle` from ios+android

**Comment by DanielZlotin** [comment]
Updated API
