### ISSUE TITLE
android fab

### ISSUE THREAD

**Issue by DanielZlotin** [wix/react-native-navigation#1081]
https://github.com/Clans/FloatingActionButton

- [x]  background color (collapsed and expended)
- [x]  Icon (collapsed and expended)
- [x] Icon color (collapsed and expended)
- [x]  Actions
- [x] Gravity
- [x]  Hide on scroll

**Comment by Cool04ek** [comment]
In progress

**Comment by Cool04ek** [comment]
#2680
