### ISSUE TITLE
Android tab bar icons do not display

### ISSUE THREAD

**Issue by lappalj4** [wix/react-native-navigation#1085]
### Issue Description
Setting icons for the tab bar in a tabBasedApp does not work. The icons are not rendered, but instead shapes that are colored per the config:

![image](https://cloud.githubusercontent.com/assets/11797156/25133777/fef3850a-244d-11e7-9ec8-6216de21aa64.png)

In the above image, the square shapes are image assets shaped as squares, and the circle shapes are round images respectively. The config for my tabs is as follows:

````
tabs: [
{
              label: 'Shop',
              screen: 'LaaxInside.Shop',
              icon: require('./assets/activity-biking.png'), 
              selectedIcon: require('./assets/activity-biking.png'), 
              title: 'Shop',
              navigatorStyle: NavigatorStyles.baseStyle(),
              navigatorButtons: {} 
},
...
],
appStyle: {
               orientation: 'portrait',
               forceTitlesDisplay: true,
               tabBarButtonColor: '#cccccc',
               tabBarSelectedButtonColor: '#63d7cc',
}
````
---
### Environment
* React Native Navigation version: 2.0.0-experimental.302
* React Native version: 0.42.3
* Platform(s) (iOS, Android, or both?): Android (6.0.1)
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator, debug.

**Comment by Crash--** [comment]
Loading an icon / image is on async task. So you need to resolve it before calling start*App()

Take a look at this issue : https://github.com/wix/react-native-navigation/issues/43

**Comment by Ehesp** [comment]
Hmm this works for me. What size are your images/icons?

**Comment by lappalj4** [comment]
square one in the example was 20x20 and circle 90x90. It seems like it is not an issue with not finding the assets either, since the shapes of the icons are what they are.

**Comment by giovanigm** [comment]
I'm having a similar problem: when running the app on my Android Device (6.0.1), without the USB cable, the icons on my tab bar are not displayed at all, not even their shapes. But when I'm debugging they are displayed nicely.

**Comment by ceciliaschiebel** [comment]
I have the same problem.
Has someone found a workaround for this?

**Comment by ceciliaschiebel** [comment]
I had the same problem, and in my case, it was just a matter of wrong assets.
The example images we were using were png, but they had a colored background. And since the tabBar overlays a color and applies a filter it didn't looked as expected.
We solved it by changing to silhouette icons with transparency.

**Comment by loksurya** [comment]
has any one able to solve it ?

**Comment by loksurya** [comment]
@Ehesp what size of icon are you using, I am using 48*48 for tabbar icons, which are visible when installed using usb, but not when installed using apk.

**Comment by lappalj4** [comment]
Whoops, did not mean to close this...

**Comment by ziyafenn** [comment]
hey @lappalj4  ! Any idea why i'm getting a white screen on android? It seems icons doesn't load so i get a white screen and my app is never starting... There is no crash or error, just doesn't load. On ios there is nothing like this.

Thanks in advance!

**Comment by ziyafenn** [comment]
hey @lappalj4, any idea how i could use it inside a `<View>`? 

`<Image source={iconsMap['ico-name']} />` doesn't work. It just doesn't render.

**Comment by blainemuri** [comment]
Any ideas on how to fix this? I'm also having the issue where it's fine when debugging, but when deployed to HockeyApp it doesn't display the `leftButtons` or `rightButtons`. They're still clickable, and it will transition one of the buttons from being the "icon" to the word `Done`, but the icon is not there

**Comment by ethanyanjiali** [comment]
it may not be RNN's problem. https://stackoverflow.com/questions/41937443/local-images-are-not-visible-in-react-native-app-release-build

**Comment by blainemuri** [comment]
For reference to anyone else having the issue. I fixed it by disabling debug mode in HockeyApp. Apparently it will still try to access the assets from localhost, only through react-native-navigation (even though react recognizes that it needs to pull from the bundled assets).

TL:DR - Be sure debugging is turned off

**Comment by BrunoVillanova** [comment]
@blainemuri How did you do this?

**Comment by pramjeet** [comment]
@BrunoVillanova Don't worry, it will be fixed once you will build the release version. Or you can change the settings in `menu` > `Build` > `Edit Build Types...` and set the `debuggable` to `false`. But it is not recommended for the `debug` version though.

**Comment by gerbyzation** [comment]
For me this was located in `android/app/src/java/com/fortuna/MainApplication.java`
```java  
@Override
public boolean isDebug() {
  return true;
}
```
Switching that to false resolved the issue.
