### ISSUE TITLE
waitForRender

### ISSUE THREAD

**Issue by lfabreges** [wix/react-native-navigation#1086]
### Question

Is there any way to wait for the react view to render before pushing it to avoid flickering effects ? I'm using the 2.0 branch.

**Comment by DanielZlotin** [comment]
What exact version of react-native-navigation are you using?

**Comment by lfabreges** [comment]
2.0.0-experimental.300

**Comment by DanielZlotin** [comment]
This needs some research. Will be handled after 2.0.0 is ready

**Comment by grundmanise** [comment]
@DanielZlotin This feature alone would greatly improve a UX. There are a lot of issues that address flickering, and *waitForRender* would solve this.

**Comment by guyca** [comment]
This has been implemented a while ago for both platforms, for `push` and `showModal`

```js
animations: {
  push: {
    waitForRender: true
  },
  showModal: {
    waitForRender: true
  }
}
```

**Comment by rh389** [comment]
@guyca is `waitForRender` available for the initial `setRoot`?

**Comment by hossamnasser938** [comment]
@rh389 yes, it exists. See [here](https://github.com/wix/react-native-navigation/blob/07c558c76f7bf3acd56a2af4e0e901c81ae0e49d/lib/src/interfaces/Options.ts#L883).

**Comment by nenjamin2405** [comment]
Hi @guyca, I cannot see the option of waitForRender when I use mergeOptions to programatically select tab:
```

**Comment by guyca** [comment]
@nenjamin2405 Please create a separate issue and provide details on your app's structure.

**Comment by sebastianistoblame** [comment]
As of now (RNN 4.8.3) I can only **warn** about using waitForRender.
It turned out it had **serious rendering side-effects**, for instance disappearing (flickering) bottomTabs when pushing a screen. Removing it solved most of our rendering issues.

**Comment by janlonden** [comment]
@nenjamin2405 I have the same problem. Did you find a solution?

**Comment by guyca** [comment]
@janlonden Can you please fork the library and push a reproduction to your fork? We'll look into it.

**Comment by Abhishek-Sankey** [comment]
> This has been implemented a while ago for both platforms, for `push` and `showModal`
> 
> ```js
> animations: {
>   push: {
>     waitForRender: true
>   },
>   showModal: {
>     waitForRender: true
>   }
> }
> ```

maybe I'm asking a silly question but where should I write this code in the project?
