### ISSUE TITLE
error ...\node_modules\detox: Command failed.

### ISSUE THREAD

**Issue by MintyOwl** [wix/react-native-navigation#1088]
### Issue Description

After running yarn install on ```example``` folder I get this error

```
error D:\RN\wix-example\node_modules\detox: Command failed.
Exit code: 1
Command: C:\Windows\system32\cmd.exe
Arguments: /d /s /c scripts/postinstall.sh
Directory: D:\RN\wix-example\node_modules\detox
Output:
'scripts' is not recognized as an internal or external command,
operable program or batch file.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
### Steps to Reproduce / Code Snippets / Screenshots
On Windows 10
    git clone https://github.com/wix/react-native-navigation

Then copy contents of example folder into fresh folder.
after ```cd``` into new folder  ```yarn install```

---
### Environment
* React Native Navigation version: ``` "react-native-navigation": "next"```
* React Native version: ```0.41.2```
* Platform(s) (iOS, Android, or both?): Not applicable
* Device info (Simulator/Device? OS version? Debug/Release?): Not applicable

**Comment by guyca** [comment]
Hey @MintyOwl 
the scripts folder is in the project root, you'll need to copy that folder as well - or just remove all references to detox scripts from package.json

**Comment by MintyOwl** [comment]
Hey thanks
