### ISSUE TITLE
Proposes drawer changes on android.

### ISSUE THREAD

**Issue by cesardeazevedo** [wix/react-native-navigation#109]
Hi, first of all, thanks for this project, that's really AWESOME, and i'm definitely moving forward with it, thank you so much.

I saw a pretty recent and awesome [pull request](https://github.com/wix/react-native-navigation/pull/82) with a drawer implementation, and i would like to propose some improvements.

1. The drawer is rendering behind the AppBar and TabBar, and that's a quite unusual, i haven't seen any drawer example like this on the [android guidelines](https://material.google.com/patterns/navigation-drawer.html), all of them shows the drawer over all the scene, i've played a little bit on the [bottom_tab_activity.xml](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/res/layout/bottom_tab_activity.xml), and i'm still trying to figure out how to structure the DrawerLayout with AppBarLayout.
![screenshot_2016-06-30-23-58-28](https://cloud.githubusercontent.com/assets/5366959/16510811/c7c54438-3f1f-11e6-8767-c94e897d1c75.png)

2. I think the drawer is a little bit small than expected, it showing [layout_width='240dp'](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/res/layout/bottom_tab_activity.xml#L38), also different from the [guidelines](https://material.google.com/patterns/navigation-drawer.html), i think we should add some props and customize our own as react-native does...

That's all i got, tell me what do you think about it.
Thank you so much.

**Comment by jskuby** [comment]
The drawer width should be a quick update.  Regarding the layout, I was also having some issues with it but didn't want to delay the feature.  Unless @guyca or someone else wants to look at this, I'll have some open time this weekend to do some work on this.

**Comment by cesardeazevedo** [comment]
That's cool, nice job.

**Comment by guyca** [comment]
Hey @cesardeazevedo I wasn't aware this isn't in the guidelines. Last time I added a drawer, showing the drawer under the Toolbar was [quite common](https://www.google.co.il/search?q=android+Sidebar+Menu&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiojaDN-tPNAhXsC8AKHVXnB_AQ_AUICCgB&biw=1440&bih=779) as you can see in these screenshots.

@jskuby I'll take it on me, if it's ok with you, since we want to make a few changes to the layouts anyways.

**Comment by jskuby** [comment]
No problem @guyca.  I had noticed a commit for a snackbar which modified the layouts, so it totally makes sense for you to take it on.

**Comment by cesardeazevedo** [comment]
I'm also notice that react-native and drawers in general has a small shadow on the borders, some docs and boilerplates projects uses this [drawer_shadow.9.png](https://developer.android.com/samples/NavigationDrawer/res/drawable-hdpi/drawer_shadow.9.html) image, and set by `mDrawerLayout.setDrawerShadow(R.drawable.drawer_shadow, GravityCompat.START);`

Actually i tried add it myself, but probably i missed something, could we add this?

**Comment by RichardLindhout** [comment]
+1 for this

**Comment by RichardLindhout** [comment]
I've tried to implement this but it won't work. I think the implementation of the CoordinatorLayout is in the wrong way.

**Comment by RichardLindhout** [comment]
Implementation should be like this 

<android.support.v4.widget.DrawerLayout>
               <android.support.design.widget.AppBarLayout>
    <android.support.design.widget.CoordinatorLayout >
          .... CONTENT LAYOUT WITH SCROLLABLE
    </android.support.design.widget.CoordinatorLayout>
    
    <android.support.design.widget.NavigationView
         android:id="@+id/navigation"
         android:layout_width="wrap_content"
         android:layout_height="match_parent"
         android:layout_gravity="start"
         app:headerLayout="@layout/nav_header"
         app:itemTextColor="#333"
         app:itemIconTint="#333"
         app:menu="@menu/navigation_drawer_items" />
         
</android.support.v4.widget.DrawerLayout>

**Comment by guyca** [comment]
Hey guys
We've made some updates to the SideMenu component in the new Android version.

1. deep links now work properly
2. SideMenu width can be set in JS
```js
  sideMenu: {
    flex: 1,
    width: 250,
    backgroundColor: '#efefef'
  }
```
3. SideMenu is placed over the rest of the app

Closing the issue, if there are any more suggestions feel free to open new issues.
