### ISSUE TITLE
Android findings/bugs

### ISSUE THREAD

**Issue by Ehesp** [wix/react-native-navigation#1097]
Hello,

I've collated a list of bugs/issues I've encountered (will continue to update) as I've been using this lib. Been chatting to @guyca on Discord about some of these - nothing huge or breaking apart from the first one, more of a snag list.

- [ ] Debugger doesn't work correctly (https://github.com/wix/react-native-navigation/issues/963).
- [ ] Right button text ripple effect is a circle over the center of the text ([gif](https://giphy.com/gifs/3og0ICVARae0zaxyWQ))
- [x] Using multiple FAB actions causes cut off ([image](https://cloud.githubusercontent.com/assets/842078/25268868/3a302274-2672-11e7-975c-ece98f81d5b6.png)) (https://github.com/wix/react-native-navigation/commit/c3c4a044a65ae807f04b212f3fc05472dfd9774a)
- [x] Calling `showSnackbar` from Screen API (this.props) shows text as `null` (#989)
- [ ] Snackbar is not documented 
- [ ] `collapsingToolBarExpendedColor`: "expended" should be "expanded" (few cases of this misspelt word)
- [ ] Calling `toggleTabs` to hide the tabs doesn't increase view height, so you're left with  un-usable screen space
- [ ] Animating bottom tabs doesn't have the option to fade screen in/out of view (possible with the [lib](https://github.com/aurelhubert/ahbottomnavigation))
- [ ] ~~Setting a FAB with icons only works when using `setButtons`, and **not** from the static `navigatorButtons`~~
- [x] Having the ability to have a component as a screen title. Currently only possible to have text/string (would like to use an image/logo)
- [ ] Immersive mode isn't available. We have the ability to style the status bar and navigation bar (Android soft keys), but the screens are unable to use this space so transparency is redundant.
- [x] Calling `showContextualMenu` greys out the statusbar color (expected), and when pressing the back action it returns to it's previous color (expected). However when calling `dismissContextualMenu` the color stays grey.
- [x] ~~It seems there's no way to remove a FAB once it's shown using `setButtons`.~~ (call `this.props.navigator.setButtons({fab: {}});`

---
### Environment
* React Native Navigation version: 300+
* React Native version: 0.43
* Platform(s) (iOS, Android, or both?): Only Android for now

**Comment by DanielZlotin** [comment]
Great work! thanks!
we will probably split some of these into individual issues

**Comment by chicojasl** [comment]
«_Calling showSnackbar from Screen API (this.props) shows text as null_». I fixed it with this PR: [#989](https://github.com/wix/react-native-navigation/pull/989)

**Comment by DavidKuennen** [comment]
Would be awesome if you could address this as well: https://github.com/wix/react-native-navigation/issues/242

**Comment by Ehesp** [comment]
@chicojasl I'm not sure the snackbar issue is fixed, I'm working on a example refactor at the moment (see PR) and it's still happening there.

**Comment by chicojasl** [comment]
Hi @Ehesp, I tested the 'example refactor' from your repo. You are using «title» instead of «text».

Example: `this.props.navigator.showSnackbar({ text: 'Woo Snacks!' });`

PS:
> Snackbar needs to be documented

**Comment by rawrmaan** [comment]
Would really love to be able to use immersive mode on Android!
