### ISSUE TITLE
"navBarTitleTextCentered: true" not working 

### ISSUE THREAD

**Issue by tierfour** [wix/react-native-navigation#1101]
### Issue Description

TopBar in Android does not center the title.

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
    startApp() { 
        Navigation.startTabBasedApp({
            tabs: [
                {
                    label: 'Feeds',
                    screen: 'app.Feeds',
                    icon: require('../img/tabbar/icon.png'),
                    selectedIcon: require('../img/tabbar/icon.png'),
                    title: 'Feeds',
                    navigatorStyle: {
                        navBarTitleTextCentered: true
                    }
                },
...
```

<img width="288" alt="screen shot 2017-04-21 at 10 45 12 am" src="https://cloud.githubusercontent.com/assets/23195140/25282855/bbe4ba48-267f-11e7-9d0a-841d4640d578.png">

---
### Environment
* React Native Navigation version: next
* React Native version: 0.41.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus_5X_API_23 DEBUG Simulator

**Comment by guyca** [comment]
Hey
I wasn't able to reproduce. Try switching to `latest` version as `next` is now deprecated.

**Comment by tierfour** [comment]
That's what I ended up doing for now. Works.
