### ISSUE TITLE
Custom left buttons with pop gesture

### ISSUE THREAD

**Issue by hamidhadi** [wix/react-native-navigation#1107]
I want to use leftButtons in screen and also I want to have pop gesture. 
When I add some buttons in leftButtons, the pop gesture not working.

**Comment by guyca** [comment]
Hey
In this case you should call `this.pops.navigator.pop()` from the `onNavigatorEvent` method.

**Comment by hamidhadi** [comment]
@guyca You didn't understand my problem. 
I know that I can use `this.props.navigator.pop()` for the custom back button but the problem is pop gesture. 
When I use custom left buttons the pop gesture doesn't work.

**Comment by guyca** [comment]
You're right, you mean the interactive pop gesture?

**Comment by hamidhadi** [comment]
@guyca Yes

**Comment by camellieeee** [comment]
@hamidhadi I have the same problem，how to save it ?

**Comment by hamidhadi** [comment]
@camellieeee I could not solve it. I have to change the position of my custom buttons.

**Comment by camellieeee** [comment]
@guyca Hello, can you solve it ？

**Comment by Calvin92** [comment]
Same issue here , any solutions for that?
