### ISSUE TITLE
iOS segmented control in navbar

### ISSUE THREAD

**Issue by chrise86** [wix/react-native-navigation#1108]
Is it possible to add a segmented control to the navbar for iOS? This is common practice in iOS and would be really useful :)

**Comment by chrise86** [comment]
Has anyone managed to do this? :(

**Comment by raunaqss** [comment]
@chrise86 It's funny how we realize these things after deciding to use a certain solution for navigation!

**Comment by chrise86** [comment]
@raunaqss well having not used this library before, I wasn't sure what it was fully capable of, and I didn't know a segmented navigation control would be require when I chose it. Seeing as it is in Apple's navigation guidelines I assumed it would be possible.
