### ISSUE TITLE
Flexbox layout broken in a tab-based app on react-native 0.43.4

### ISSUE THREAD

**Issue by grin** [wix/react-native-navigation#1109]
### Issue Description

Upgrading my iOS app to RN 0.43 broke visual layout of some of my components. My app is  tab-based and during testing I found that disabling tabs by switching the app from startTabBasedApp to startSingleScreenApp fixes the layout issues. I also noticed that components in the first tab aren't affected, only subsequent tabs are broken. Here is the screenshot of the correct layout, it's the first tab (notice, all cells have the same width):

<img width="400" alt="zrzut ekranu 2017-04-22 o 00 38 02" src="https://cloud.githubusercontent.com/assets/12468/25298309/19b2e46e-26f4-11e7-8fae-8ab2ce43888f.png">

now the second tab with the same component but broken (notice, different widths, the middle-red cell shifted to the right + plus a gap in the bottom row):

<img width="396" alt="zrzut ekranu 2017-04-22 o 00 38 29" src="https://cloud.githubusercontent.com/assets/12468/25298313/227a66bc-26f4-11e7-8ae7-6a041e8ee04e.png">

### Steps to Reproduce / Code Snippets / Screenshots

Here is the test app I used for reproducing this error: https://github.com/grin/react-native-navigation-bootstrap
Start the app with `react-native run-ios`, switch from Tab 1 to Tab 2, observe differences.

---
### Environment
* React Native Navigation version: v1.1.12
* React Native version:  0.43.1, 0.43.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by grin** [comment]
This may be related to https://github.com/wix/react-native-navigation/issues/1058 as the issue described there isn't present on the first tab too.

**Comment by mbizplus** [comment]
too related to #1112

**Comment by brycepavey** [comment]
same issue, I've resorted to setting width manually for now

**Comment by guyca** [comment]
@brycepavey Can you explain more? You're setting width manual to the root component or to specific elements?

**Comment by brycepavey** [comment]
@guyca sorry, I've just checked the code I believed I'd manually set it but was incorrect. At one point I had 3 text components in a row each with flex: 1 and had same issue as @grin. I resorted to wrapping each text component in a view that was 1/3 screen width, but did eventually manage to correct it. 
This was a few days ago but I am now unable to reproduce, I've since rolled back rn to 0.40.0 from 0.40.3 and moved to react-native-navigation 1.1.17 so it could have been somewhere in there. I'll report back if I come across it again. sorry for the false information before

**Comment by grin** [comment]
I think I found a solution. Applying these three patches to `node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c`:

https://github.com/facebook/react-native/commit/e85477552784f599ce7ec9274715affef183a2fa
https://github.com/facebook/react-native/commit/4bf2d8cb7d47d6ffa25aa697723086ffd3753083
https://github.com/facebook/react-native/commit/495fb5405845074166a4cb0e78b2339232fbbd8d

fixed the issue. 
These patches are part of react-native `v0.44.0-rc.0` so it should be fixed there too when released.

**Comment by grin** [comment]
Sorry, I spoke too soon, it doesn't work...I was testing it in another app where the error seems to be more intermittent and that gave me the impression it worked. But after a few more tests I see it doesn't fix the issue :/

**Comment by grin** [comment]
Ok, the actual fix is to upgrade react-native to `v0.44.0-rc.0`. Made some more tests this time.

**Comment by guyca** [comment]
@grin That's great to hear, Thanks for the update!
