### ISSUE TITLE
iOS TopBar dark-style blur

### ISSUE THREAD

**Issue by jjshammas** [wix/react-native-navigation#1115]
### Issue Description

Opening a Lightbox allows us to specify background blur types:

```
style: {
  backgroundBlur: "dark", // 'dark' / 'light' / 'xlight' / 'none' - the type of blur on the background
  backgroundColor: "#ff000080" // tint color for the background, you can specify alpha here (optional)
}
```

Are there plans (or an undocumented way) to supply these `backgroundBlur` string values when attempting to blur the TopBar/NavBar? Currently, we only have:

`navBarBlur: true|false`

For example, the Watch app's navigation bar uses the "dark" blur style. Mimicking that does not seem to yet be possible.

---
### Environment
* React Native Navigation version: 2.0.0-304
* React Native version: 0.43.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by gran33** [comment]
Hi @jjshammas,
Plz, add this to your screen:
```
  static navigatorStyle= {
    statusBarTextColorScheme: 'light',
    navBarTranslucent: true,
    drawUnderNavBar: true
  };```

And let me know if it helps.

**Comment by jjshammas** [comment]
@gran33 I have these settings already, but it looks nothing like the Watch app blur.
![img_0592](https://cloud.githubusercontent.com/assets/2018797/25720879/7c068714-30dc-11e7-938f-275401453590.PNG)

**Comment by jjshammas** [comment]
I think this can be solved very easily here:

https://github.com/wix/react-native-navigation/blob/8302064cecf81941426890ab0498ad63aebf1489/ios/RCCViewController.m#L386

By changing from `UIBlurEffectStyleLight` depending on the value of `navBarBlur`. I offered to make this change in the Discord but did not get any response—my primary concern is that switching `navBarBlur` to be a string would be a breaking change that would need to be communicated.
