### ISSUE TITLE
Pushed Screen Doesn't Load Until Refresh, Then Stacks Screens

### ISSUE THREAD

**Issue by LA** [wix/react-native-navigation#1117]
### Issue Description

Basically, I'm using [Twitter Digits](https://github.com/JeanLebrument/react-native-fabric-digits), and on signup completion, I want to push a new screen on top of my Single Screen Application. My issue is that when the completion happens, the new screen isn't loading (although my print statement is called and the console prints the message: ```Unbalanced calls start/end for tag 16```). Then, when I refresh the app and press the button (which has already been completed), it calls the same print statement and prints the same message, then it loads my screen, but with multiple stacks of it (although the completion is definitely only called once per button click).

### Steps to Reproduce / Code Snippets / Screenshots
Registering Screens - screens/index.js: 

```js
import { Navigation } from 'react-native-navigation';

import LoggedOutPage from '../components/LoggedOutPage';
import SignupPage from '../components/SignupPage';
import CategoriesPage from '../components/CategoriesPage';
import InsideChat from '../components/InsideChat';

// register all screens of the app (including internal ones)
export function registerScreens() {
  Navigation.registerComponent('screens.LoggedOutPage', () => LoggedOutPage);
  Navigation.registerComponent('screens.SignupPage', () => SignupPage);
  Navigation.registerComponent('screens.CategoriesPage', () => CategoriesPage);
  Navigation.registerComponent('screens.InsideChat', () => InsideChat);
}
```

Initializing App - App.js constructor:
```js
Navigation.startSingleScreenApp({
  screen: {
    screen: 'screens.LoggedOutPage',
    navigatorStyle: {navBarHidden: true},
    navigatorButtons: {},
  },
});
```

Pushing New Screen - LoggedOutPage.js render:
```js
completion={(error, response) => {
  var self = this;
  console.log("Error: " + error + "\n" + "Response: " + JSON.stringify(response))
  if (response) {
    if (JSON.stringify(response) !== '{}') {
      this.refs.digitsLoginButton.getSessionDetails(function(sessionDetails) {
        console.log("SHOULD BE LOADING SIGNUP PAGE");
        self.props.navigator.push({
          screen: 'screens.SignupPage',
          passProps: {phonenumber: sessionDetails.phoneNumber},
          navigatorStyle: {navBarHidden: true},
        });
      });
    }
  }
}}
```
---
### Environment
* React Native Navigation version: ^1.1.1
* React Native version: 0.43.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 7 Simulator - 10.2 - Debug

I can record a video, and post it, if necessary.

**Comment by Ehesp** [comment]
A video/gif would be handy yes. Do you see `SHOULD BE LOADING SIGNUP PAGE` printing in the console?

**Comment by TrickSpades** [comment]
I think possibly that the screens have stopped stacking now, but the issue is essentially the same. On load, I am receiving Application [NAME] has not been registered, but I'm assuming this is because of the way I'm initializing my app, because when I press dismiss, everything works fine.
```
import {
  AppRegistry
} from 'react-native';

import App from './components/App';
const app = new App();
//AppRegistry.registerComponent('RICO', () => App);
```
[Youtube Video of My Issue](https://www.youtube.com/watch?v=SQMkooMI1Pk&feature=youtu.be&ab_channel=AdarButel)

Also, when I'm spamming the button in the middle of the video, the callback is being called every time (SHOULD BE LOADING SIGNUP PAGE).

**Comment by guyca** [comment]
I think the issue is in your objective C code, perhaps you missed something in the iOS [setup](https://wix.github.io/react-native-navigation/#/installation-ios).

**Comment by TrickSpades** [comment]
I did forget to comment out the initial AppDelegate code. Now that I fixed that, the stacking and `Application Not Registered` has definitely stopped, but my key issue of the navigator not pushing my screen even though the callback was called is still there.

**Comment by TrickSpades** [comment]
My code just in case I missed something else

```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"
#import "RCCManager.h"
#import <Fabric/Fabric.h>
#import <DigitsKit/DigitsKit.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;
  
  #ifdef DEBUG
    //  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  #else
    jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
  #endif
  
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  self.window.backgroundColor = [UIColor whiteColor];
  [[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation];
  [Fabric with:@[[Digits class]]];
  
  /*
   RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
   moduleName:@"RICO"
   initialProperties:nil
   launchOptions:launchOptions];
   rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
   UIViewController *rootViewController = [UIViewController new];
   rootViewController.view = rootView;
   self.window.rootViewController = rootViewController;
   [self.window makeKeyAndVisible];
   */
  
  return YES;
}

@end
```

**Comment by hackable** [comment]
I have an issue where it shows `Unbalanced calls start/end for tag 16` everything is working then why the is being shown.

**Comment by kabus202** [comment]
@hackable did you manage to solve this issue/message?

> Unbalanced calls start/end for tag 16
