### ISSUE TITLE
How can i get current Screen ID/Name?

### ISSUE THREAD

**Issue by sourabhkheterpal** [wix/react-native-navigation#1118]
### ScreenID of Top screen in Stack. 
Hi @guyca ,
I want to know what is my current screen(its ID or name or routes) which is on top of stack by which i can make decision related to notification on the basis of this.(i.e.whether to show notification or not)

can you please help.

### Environment
* React Native Navigation version: 2.0.0-experimental.281
* React Native version: 0.42.0
* Platform(s) (iOS, Android, or both?): checking on Anroid
* Device info (Simulator/Device? OS version? Debug/Release?): Right now on Simulator

**Comment by varungupta85** [comment]
You can use screen visibility events to keep track of the current screen.

https://wix.github.io/react-native-navigation/#/screen-api?id=screen-visibility

**Comment by sourabhkheterpal** [comment]
@varungupta85  Thanks for reply.
I needed to access current screen Name at global level.

**Use Case:** 
For notification i have inserted notification's component at root level screen. now i am at 2-3 level deep from root screen and now i get notification for chat which will fire **onNotification** event in notification component at root level where i inserted that, there i have to make decision according to current screen.

have any suggestion for this?  may be i have to maintained global variable for this.

Thanks.

**Comment by Ehesp** [comment]
One thing you could do, if you're using Redux is wrap your screen in a decorator and handle it from there, something like:

```
class MyScreen extends React.Component {
  static screenName = 'Profile/MyScreen';
}

export default Screen(MyScreen);
```

```
const decorator = (ComposedComponent) => {
  const component = class extends Component {
    constructor(props) {
      super(props);
      props.navigator.setOnNavigatorEvent(this.onNavigatorEvent);
    }

   onNavigatorEvent = (event) => {
     switch(event.id) {
      case 'didAppear':
       if (ComposedComponent.screenName) {
         this.props.dispatch(onScreenAppear(ComposedComponent.screenName));
       }
        break;
   }

    render() {
      return <ComposedComponent  {...this.props} />;
    }
  };

  return connect()(component);
}
```

Obviously you'd need an action for `onScreenAppear` to set the screen name, but you can then grab it when needed from Redux.

**Comment by sourabhkheterpal** [comment]
@Ehesp Thanks a lot. it solves this.

**Comment by sytolk** [comment]
@Ehesp can you create complete example using decorator for this ?

**Comment by Ehesp** [comment]
What more do you want than the example? I'd look elsewhere if you're after how to integrate Redux.

**Comment by sytolk** [comment]
@Ehesp  Sorry but I think that code snippets is for stack-overflow.. maybe PR with example test project with this functionality will be better contribution for this project :)

**Comment by guyca** [comment]
@sytolk 
You can use `Navigation.getCurrentlyVisibleScreenId()`

**Comment by sytolk** [comment]
@guyca I have:
```
Promise.resolve(Navigation.getCurrentlyVisibleScreenId())
                .then(containerId => {
                    console.debug('CurrentlyVisibleScreenId:' + JSON.stringify(containerId));
                    return containerId;
                }).catch((error) => {
                    console.log('Error getCurrentlyVisibleScreenId:' + error);
                });
```
console log: `CurrentlyVisibleScreenId:{"screenId":"screenInstanceID8"}`
How can I get screen name from ID: "screenInstanceID8" ? 
my current visible screen name is: "app.MY_SCREEN" for example

**Comment by sytolk** [comment]
@Ehesp @sourabhkheterpal this is my decorator: https://gist.github.com/sytolk/9cdaa8f4b54fcba17f94f4f7ed4bc122
It works for the tab based App. But I have start TabBased and SingleScreen App multiple times according to recommendation: https://github.com/wix/react-native-navigation/issues/1852#issuecomment-329469269 
(drawback is the memory leak when I switch from TabBased to SingleScreen app https://github.com/wix/react-native-navigation/issues/1807)
@guyca maybe this is the known issue but when I start SingleScreen App NavigatorEvent is not fired? and this makes screen names decorator not usable for SingleScreen App.

**Comment by DavitVosk** [comment]
I am using `const isVisible = await this.props.navigator.screenIsCurrentlyVisible() ` to be informed when the screen is visible. You can use this logic and show the screens data only if `isVissible` is `true`

**Comment by b8ne** [comment]
If you are using redux, you can keep track of the current screen in your store using `ScreenVisibilityListener`.

ScreenVisibilityListener.js
```
import {ScreenVisibilityListener as RNNScreenVisibilityListener} from 'react-native-navigation';
import * as ACTIONS from '../actions/index';

export class ScreenVisibilityListener {
    constructor(store) {
        this.listener = new RNNScreenVisibilityListener({
            didAppear: ({screen}) => {
                store.dispatch(ACTIONS.screenChanged(screen));
            }
        });
    }
    register() {
        this.listener.register();
    }
    unregister() {
        if (this.listener) {
            this.listener.unregister();
            this.listener = null;
        }
    }
}
```

App.js
```
import { ScreenVisibilityListener } from './utils/ScreenVisibilityListener';
...
// Register screen listener
const screenListener = new ScreenVisibilityListener(store);
screenListener.register();
```

**Comment by terreb** [comment]
@b8ne approach is correct, however for RNN 2 [registerComponentDidAppearListener](https://wix.github.io/react-native-navigation/v2/#/docs/events?id=componentdidappear) should be used instead. 

```javascript
Navigation.events().registerComponentDidAppearListener(({ componentId, componentName }) => {

});
```
