### ISSUE TITLE
Allow more styling options for NavBar text

### ISSUE THREAD

**Issue by hammadj** [wix/react-native-navigation#112]
Right now we can only set the color of text that appears in the Navbar. It would be nice to be able to change the font, size, color, etc of the text as well.

**Comment by guyca** [comment]
Hey @hammadj I don't see a reason to change any property other then font color. Other properties are defined by the system and should be left as is so the user feels familiar with the navigation components

**Comment by mastermoo** [comment]
It would still be useful to have these options..

**Comment by 1800joe** [comment]
@guyca, it would definitely be useful to be able to change more styles than just the text color. Every application is going to have its own set of branding guidelines that will dictate font, size, colors. Please let me know what reservations you have about opening the API up for a few more customizations. Thanks!

**Comment by guyca** [comment]
Hey @1800joe @mastermoo 
Currently in v2.0, the following TitleBar (Yup, `TitleBar` instead of `navBar` see the new [naming convention](https://github.com/wix/react-native-navigation/issues/197) we're trying to use) are available:

* Title color
* Button colors (each button can be configured individually as well)
* Background color

If there's a demand from the community to style title font - we'll probably add that as well, though It might take a while (pull requests are welcome once api matures, that will speed things up).

**Comment by 1800joe** [comment]
Gotchya, I think it will be a much appreciated feature :-). I'll take a look at what it'll take to implement, anything I should know going into it?

**Comment by DanielZlotin** [comment]
We will be happy to add more options / will ask you to make a pull request - **after the styling API stabilized** - should be after v`2.0.0`

**Comment by guyca** [comment]
@1800joe We welcome any contribution to the project, thanks. Right now we're about to finish the rewrite of the Android version, after which we're going to invest time on the iOS side of the project and integrate `react-native-controllers` into the library. So we won't have time in the next month or two to accept pull requests.
Once things stabilize we'll have a better understanding of how the community can pitch in.

**Comment by 1800joe** [comment]
@guyca i made a quick test showing I can get font-family/font-size with extremely minimal intrusion -- could have a PR today. Interested in a pre-v2 addition?

**Comment by bbrock25** [comment]
I just found that as a stop-gap you can use `titleImage` as defined in react-native-controllers: [here](https://github.com/wix/react-native-controllers#props-1)

**Comment by DanielZlotin** [comment]
@1800joe The problem is we try to create some parity between the platforms, but go ahead and make a PR, if it's really non intrusive I'll consider making an exception and to implement it also in controllers.

**Comment by SudoPlz** [comment]
Any news on that guys?

**Comment by guyca** [comment]
Not really. I don't think Joe ever got around to submitting that PR and we didn't get to this as well.

**Comment by grin** [comment]
More font styling options would be useful. One iOS UX pattern I would like to follow in my app is to use bold font for a primary action and a regular for a secondary, like [here](https://developer.apple.com/ios/human-interface-guidelines/images/ModalView-Screen_2x.png) (as found in iOS Human Interface Guidelines).

**Comment by annelorraineuy** [comment]
@1800joe I'd love to get your addition in! I'm only developing on Android and titleImage doesn't work for me :/ I'd be okay with being able to set fontSize.
