### ISSUE TITLE
Question, Customizing Tab Bar

### ISSUE THREAD

**Issue by fuatsengul** [wix/react-native-navigation#1126]
### Question about Customization of TabBar
Hello @wixadmin thank you for this great package, I have to make an unusual TabBar styling(especially the big button in center) but I don't know even if I can with this environment. Can you guide me through please?
![tab-bar-icons-iphone-ramotion-animation-interface-design](https://cloud.githubusercontent.com/assets/7515057/25354975/c2de4380-293d-11e7-867f-b60bba34ab9f.gif)

**Comment by akjesto** [comment]
you got the solution?

**Comment by jp928** [comment]
you may need implement react native lottie with navigator, it might be only supported by airbnb react navigation.

**Comment by akjesto** [comment]
I dont need animation effect and i only want selected specific icon image.I tried like 

{
      label: 'HOME',
      screen: 'Home',
      icon:  require('../img/ic_tabbar.png'),
      selectedIcon: require('../img/ic_tabbar_on.png'),
      title: 'HOME',
    },

But it always take selected icon color is default tint.I did not get exact color.

**Comment by jp928** [comment]
@akjesto 
on IOS, you need 
```javascript
tabsStyle: {
        tabBarTextFontFamily: 'Avenir-Medium',
        tabBarSelectedButtonColor: THEME_COLOR.color,
        tabBarBackgroundColor: '#ffffff'
      },
```

**Comment by jp928** [comment]
android syntax is slightly different:
```javascript
appStyle: {
        tabBarBackgroundColor: '#fff',
        tabBarButtonColor: '#000',
        navBarTextFontSize: 34,
        forceTitlesDisplay: true,
        tabFontFamily: 'Avenir-Medium',
        tabBarSelectedButtonColor: THEME_COLOR.color,
      }
```

**Comment by jp928** [comment]
The whole thing is something like:
```javascript
Navigation.startTabBasedApp({
      ...tabs,
     tabStyle: {
        ...
    },
    appStyle: {
      ...
   }
});
```

**Comment by jp928** [comment]
Please reference the document for more details:
https://wix.github.io/react-native-navigation/#/

**Comment by akjesto** [comment]
@jp928    Please go through the following code

const createTabs = () => {

  let tabs = [
    {
      label: 'HOME',
      screen: 'Home',
      icon:  require('../img/ic_tabbar_inici.png'),
      selectedIcon: require('../img/ic_tabbar_inici_on.png'),
      title: 'HOME',
    },
    {
      label: 'LIST',
      screen: 'List',
      icon: require('../img/ic_tabbar_inici.png'),
      selectedIcon: require('../img/ic_tabbar_inici_on.png'),
      title: 'LIST',
    }
  ],
  tabsStyle: { 
        tabBarTextFontFamily: 'Avenir-Medium',
        tabBarSelectedButtonColor: '#ffffff',
        tabBarBackgroundColor: '#ffffff'
}
  return tabs;
}

But output is  like 
![screen shot 2017-04-25 at 1 03 59 pm](https://cloud.githubusercontent.com/assets/8862491/25373312/c34c7912-29b6-11e7-9571-9779e3bcf6dd.png)

I did not get exact tab icon when i loaded. I always get blue tint color on my tab icon.

**Comment by jp928** [comment]
The snippit u just attached would not return a tab object contains tabsStyle property. please double check.

**Comment by jp928** [comment]
'''javascript
const createTabs = () => {

const tabs ={ [
{
label: 'HOME',
screen: 'Home',
icon: require('../img/ic_tabbar_inici.png'),
selectedIcon: require('../img/ic_tabbar_inici_on.png'),
title: 'HOME',
},
{
label: 'LIST',
screen: 'List',
icon: require('../img/ic_tabbar_inici.png'),
selectedIcon: require('../img/ic_tabbar_inici_on.png'),
title: 'LIST',
}
],
tabsStyle: {
tabBarTextFontFamily: 'Avenir-Medium',
tabBarSelectedButtonColor: '#ffffff',
tabBarBackgroundColor: '#ffffff'
}};
return tabs;
}
'mm

**Comment by akjesto** [comment]
@jp928  Please check my above comment.Please check it.

**Comment by jp928** [comment]
your code looks alright. but this library cannot change selectedIcon on Android. u can test it on IOS

**Comment by akjesto** [comment]
@jp928 , Now i checked with it in iOS only

**Comment by jp928** [comment]
@akjesto Since your selecedIcon is very similar to the origin icon. plz advise the difference. your code should work as expected, maybe u could swipe your selectedIcon with an obvious change.

**Comment by fuatsengul** [comment]
Sorry guys I've lost context. My original question is about the big button in the middle, is it possible to create by using this package?

**Comment by Ehesp** [comment]
I don't believe it currently is. @guyca any ideas regarding this?

The Android tabs are currently based on https://github.com/aurelhubert/ahbottomnavigation

**Comment by Ehesp** [comment]
I mean, you could create a single screen app and have your own implementation of this, however you're not going to have the bar persisted across screens or the "active" state tracked etc.

**Comment by PARAGJYOTI** [comment]
There's some thing you  can change but its not what you are looking for . As @Ehesp  says , it uses a third party library https://github.com/aurelhubert/ahbottomnavigation , but you cann't make change as  it its compiled version that have .class extension instead of java . 
       But one thing you can do is clone the package from github and place in the main/src/com directory of react-native navigation and add your custom styles on it .

**Comment by heron2014** [comment]
Hi guys and @wixadmin,
Is there a way to have an option to customise active background color on selected tab (not only selected icon) ? 

To achieve following effect (yellow active background color):

<img width="294" alt="screen shot 2017-10-14 at 17 21 32" src="https://user-images.githubusercontent.com/8476884/31576854-3cb39d24-b104-11e7-9ffb-3040f32fedd5.png">

Thanks.

**Comment by PARAGJYOTI** [comment]
No , its not implemented yet as the navigation follows android Ui guidelines . Only underline color can be customized. However , of you have knowledge on java , you can tweak in in the native code.

**Comment by heron2014** [comment]
Thanks @PARAGJYOTI

**Comment by JPStrydom** [comment]
@jp928  Why is changing the selected tab icon not supported on Android when Facebook themselves do it?

**Comment by HarveyRoberts** [comment]
Any news on this ? I tried react-navigation and react-native-navigation and I think I might choose react-navigation if I can't have a custom component as a tab bar or header bar.

**Comment by amirmatin** [comment]
Has anyone got the larger middle button to work ? a solution would be much appreciated ...

**Comment by vigneshprabhu20** [comment]
@fuatsengul Have you got the solution for this?

**Comment by luxferoo** [comment]
I removed react-native-navigation and created a custom component who's absolute in the bottom.

**Comment by vigneshprabhu20** [comment]
@luxferoo Problem with this approach is when you push any component bottom bar is gone, you need to integrate this inside each component registered as screen!

**Comment by luxferoo** [comment]
@vigneshprabhu20 you can perform that creating a HOC and put the bar in one place

**Comment by Albert-Gao** [comment]
The upcoming Android design support lib v28 will have an interesting approach to the Bottom app bar where you can attach the FAB to the action bar:

![](https://cdn-images-1.medium.com/max/800/1*MxUcbBvlYMOSOJ-CZVJu-g.png)
![](https://cdn-images-1.medium.com/max/800/1*du591XX2cDBCgDFezZ14OA.png)

But now I know the underneath android support using a 3rd party lib, so it's very hard to change... Still wanna mention it just in case.

**Comment by eagle-design** [comment]
The same issue , i dont need animation effect now 
only different style for center icon.

**Comment by cshen4** [comment]
I just want to use different icons based on whether a tab is selected or not. is that possible right now? (i'm using v2)

**Comment by luxferoo** [comment]
@cshen4 yes you can with  'selectedIcon' attribute

**Comment by cshen4** [comment]
`Navigation.setRoot({
    root: {
      bottomTabs: {
        children: [
          {
            stack: {
              children: [
                {
                  component: {
                    name: 'ServiceInstance',
                    options: {
                      bottomTab: {
                        title: 'Service',
                        icon: require('../images/app_icon/Service_outline.png'),
                        selectedIcon: require('../images/app_icon/Service_full.png')
                      }
                    }
                  }
                }
              ]
            }
          },
          {
            stack: {
              children: [
                {
                  component: {
                    name: 'Contacts',
                    options: {
                      bottomTab: {
                        title: 'Contacts',
                        icon: require('../images/app_icon/Contacts_outline.png'),
                        selectedIcon: require('../images/app_icon/Contacts_full.png')
                      }
                    }
                  }
                }
              ]
            }
          },
          {
            stack: {
              children: [
                {
                  component: {
                    name: 'Me',
                    options: {
                      bottomTab: {
                        title: 'Me',
                        icon: require('../images/app_icon/Me_outline.png'),
                        selectedIcon: require('../images/app_icon/Me_full.png')
                      }
                    }
                  }
                }
              ]
            }
          }
        ],
        options: {
          backgroundColor: 'white'
          // tabColor: '#777777',
          // selectedTabColor: '#2979FF'
          // tabBarDisableSelectedIconTint: true
        }
      }
    }
  });`
@luxferoo this is my code right now, the selectedIcon doesn't seem to work... Am I putting it in the wrong place?

**Comment by luxferoo** [comment]
@cshen4 I don't think it's a wix/react-native-navigation configuration , look at mine :
```
 Navigation.startTabBasedApp({
                tabs: [
                    {
                        screen: 'pipo.UserInfo',
                        label: 'Account',
                        title: 'Account',
                        icon: sources[0], 
                        selectedIcon: sources[3],
                        navigatorStyle: {
                            navBarButtonColor: 'black',
                            //navBarTextColor: mainBlue
                        }
                    }
               ]
        })
```

**Comment by zedtux** [comment]
Best looking option so far : https://itnext.io/react-native-tab-bar-is-customizable-c3c37dcf711f.

I'm still looking for other options and will try the best one.

**Comment by zedtux** [comment]
Yeah sure ... nice job to close the issue because of "inactivity" ... not from us ... from the devs ! 🤦‍♂️
