### ISSUE TITLE
Open drawer from tab bar

### ISSUE THREAD

**Issue by augustoabreu** [wix/react-native-navigation#1127]
### Issue Description

Hi, i'm developing a Android/iOS app and i need to open the drawer from a button of tab bar. Is this possible with react-native-navigation??

I've tried to listen 'screen events' and open the drawer on 'didAppear' event, but when i close the drawer the view still the same. I need to go back one view, the problem is that drawer component do not dispatch 'screen events'.

**Comment by guyca** [comment]
[toggleDrawer](https://wix.github.io/react-native-navigation/#/screen-api?id=toggledrawerparams-) didn't work? what exactly did you try?

**Comment by augustoabreu** [comment]
@guyca toggleDrawer() works, but i think that is not capable to do what i want:

I want to open the drawer directly from the tab bar instead of a view. There is a way to a tab bar button work like a hamburguer button?

**Comment by guyca** [comment]
That's not supported. Since a lot of users have asked for unconventional BottomTabs implementations, in the future we will support custom BottomTabs implementations in Js.
