### ISSUE TITLE
[iOS] Setting the title of a tabbed screen changes the label in the tab bar

### ISSUE THREAD

**Issue by hammadj** [wix/react-native-navigation#113]
I have this tab in my tab bar: 

``` js
{
  label: 'Me',
  screen: screens.profile,
  icon: require('./img/profile.png'),
  selectedIcon: require('./img/profile_selected.png'),
  title: 'Profile',
  navigatorStyle: this.navStyle
}
```

In the component for the screen, once the user is loaded, I set the title of the nav bar like this: 

``` js
this.props.navigator.setTitle({
  title: nextProps.user.profile.name
});
```

However, this causes the label in the tab bar to also change. It should only change the title at the top of the nav bar, since the label and title are two separate props when defining the screen

**Comment by guyca** [comment]
Hey @hammadj Thanks for reporting. This happens on both platforms?

**Comment by hammadj** [comment]
I'm only using it on iOS, don't know about android

**Comment by dingbat** [comment]
Opened a PR in react-native-controllers to fix this: https://github.com/wix/react-native-controllers/pull/74

**Comment by adamski** [comment]
Getting this on iOS only

**Comment by adamski** [comment]
@guyca @DanielZlotin this issue has only just come up for me since around experimental.140.

**Comment by grin** [comment]
I pushed a fix: https://github.com/wix/react-native-navigation/pull/897
