### ISSUE TITLE
 Load image from  Images.xcasset  for tab icon 

### ISSUE THREAD

**Issue by akjesto** [wix/react-native-navigation#1131]
I am using xcode and i added image to   Images.xcasset .Then i already set my tab icon( for selected and unselected) like the following code.In my   Images.xcasset contain like  
for home - (3 images like) home.png,home@2x.png,home@3x.png.
for home_on - (3 images like) home_on.png,home_on@2x.png,home_on@3x.png
```
let tabs = [
    {
      label: 'HOME',
      screen: 'Home',
      icon:  {uri:'home'},
      selectedIcon: {uri:'home_on'},
      title: 'HOME',
    },
    {
      label: 'LIST',
      screen: 'List',
      icon:{uri:'home'},
      selectedIcon: {uri:'home_on'},
      title: 'LIST',
    }
  ]
```

From this i can see the image for tab icon but the size is not correct. It always take @2x or @3x images. How to solve this issue?

**Comment by mattmcdonald-uk** [comment]
Adding a scale property seems to be a workaround for this.

`icon:  {uri:'home', scale: Dimensions.get('window').scale}`
