### ISSUE TITLE
How to handle back event on android

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#1135]
Hi guy,

I tried but not working. How i can handle back event when user tap left back icon or on device.
```
onNavigatorEvent(event) {
        if (event.id == 'back') {
            alert('back');
        }
}
```

---
### Environment
* React Native Navigation version: "^1.1.22"
* React Native version: "^0.43.4"
* Platform(s) (iOS, Android, or both?): ANDROID
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by jtibbertsma** [comment]
You can use
```js
this.props.navigator.push({
  title: "Dope Title",
  screen: "example.SomeScreen",
  overrideBackPress: true
});
```
Doesn't work for overriding the back button on the iOS navbar though.

**Comment by agumack** [comment]
@jtibbertsma i have setting overrideBackPress but doesn't work.

**Comment by guyca** [comment]
@agumack The id is `backPress` and not `back`

**Comment by em222iv** [comment]
I'm using the 1.1.13 release and this setting overrideBackPress: true does only override the click-event but does not generate an onNavigatorEvent.
              
```
                       navigator.push({
                         screen:'ad',
                         navigatorStyle:{
                           navBarHidden:true
                         },
                         overrideBackPress: true
                       })}
```

```
  this.props.navigator.setOnNavigatorEvent((event) => {
            console.log('setOnNavigatorEvent ', event.id)
            // if (event.id === 'backPress') {
            //   console.log('backPress')
            // }
        })

```

does not log anything
Any ideas?

**Comment by jonathan68** [comment]
Not working on Android. 

overrideBackPress: true
event.id === 'backPress'

Works on iOS but not on Android

**Comment by guyca** [comment]
@jonathan68 This is a bit counter intuitive. [Here's an example](https://github.com/wix/react-native-navigation/blob/74266b05eba85bff8c7f9ac51993b3f268827e84/old-example-redux/src/screens/PushedScreen.js#L28).
Use `id: 'back'` when defining the button, and listen to `event.id === 'backPress'` in onNavigatorEvent

**Comment by jonathan68** [comment]
Yes, I used them.

id: 'back'
event.id === 'backPress'

Works on iOS but not on Android

**Comment by guyca** [comment]
Yes. `backPress` is a reserved word and works only on Android. I don't think you can prevent pop on iOS.
If you want to invoke some action when the screen is popped - you can dispatch an action from `componentWillUnmount`

**Comment by Agontuk** [comment]
@jonathan68, for IOS you have to add a navigator back button like this, and use `event.id === 'back'`

```js
navigatorButtons: {
  leftButtons: [{
    id: 'back',
    title: 'Back',
    icon: require('back-icon.png')
  }]
 }
```

@guyca, about adding navigator buttons, how can I use both title & icon? Currently, if I provide an icon & title, only icon shows up.
