### ISSUE TITLE
How To Add A Search Bar In The Header

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#114]
![components_tabs_usage_mobile2](https://cloud.githubusercontent.com/assets/19372005/16546780/d6396bcc-417f-11e6-9a00-5775a5caf37b.png)

Thank you so much!

**Comment by guyca** [comment]
@DanielZlotin ecom also asked for this.

**Comment by agumack** [comment]
@guyca i have resolve it. 
I am use 'navBarHidden: true' and style it on screen :)
