### ISSUE TITLE
dismissModal won't fire appropriate NavigatorEvents

### ISSUE THREAD

**Issue by cskaynar** [wix/react-native-navigation#1144]
### Issue Description
After calling dismissModal modal and presented view won't triggered with appropriate NavigatorEvents.

Modal should be triggered with willDisappear & didDisappear
Presented View should be triggered with willDisappear & didDisappear

This is working well on iOS.

---
### Environment
* React Native Navigation version: 1.1.x
* React Native version: 0.43.4
* Platform(s) : Android
* Device info: LG Nexus 5X, GM 5 version 7.1.1

**Comment by guyca** [comment]
Thanks for reporting

**Comment by cskaynar** [comment]
@guyca thanks for quick response. 
Now Modal is triggered with willDisappear & didDisappear.
However Presented View still not triggered with willDisappear & didDisappear.
