### ISSUE TITLE
How to implement intial Screen With Tab Based App

### ISSUE THREAD

**Issue by DavidKuennen** [wix/react-native-navigation#1146]
Hallo,

my main screen is tab based, but the intial screen should be a welcome page without any tabs for example, in case the user didn't login yet. 

How do I implement that?

**Comment by Ehesp** [comment]
I have a watcher in my setup function which watches for changes on the user auth state. If it changes, it either calls `startSingleScreenApp` or `startTabBasedApp` based on that state. What are you using for authentication?

**Comment by DavidKuennen** [comment]
I'm using firebase which works exactly like that. And that was also my first attempt, which worked. 
Then I guess that's the implementation to use, even tho the initial animation bothers me.

**Comment by Ehesp** [comment]
I use `react-native-firebase` (maintainer :D) and use:

```
return firebase.auth().onAuthStateChanged((user) => {
  // render screen based on user
});
```

One thing you could do is push a modal on the `screenWillAppear` event (or didAppear if that doesnt work), and override the back button press.

**Comment by DavidKuennen** [comment]
Haha, interesting, I'm using exactly the same lib. (https://github.com/invertase/react-native-firebase)

I guess I'm going with my first (and your) approach. Thank you.
