### ISSUE TITLE
HELP!: Support Universal application 

### ISSUE THREAD

**Issue by khatv911** [wix/react-native-navigation#1148]
### Issue Description

Not an issue actually, just want to know is it possible to build a Master-Detail app in which Master is tab based and the latter is single screen, and should it support 2 panels in case it runs on a tablet/ipad.  

[ipad.pdf](https://github.com/wix/react-native-navigation/files/959095/ipad.pdf)

If you guy out there have done it before, i'll do appreciate your help. Thanks!

**Comment by Ehesp** [comment]
Currently this isn't possible. Youd need to have custom button navigation which isn't currently supported.

**Comment by khatv911** [comment]
@Ehesp : Thank you for your response. Yet, is this one in 2.0 roadmap?

**Comment by Ehesp** [comment]
@DanielZlotin will be able to answer that one - right now probably no, since it's not in v1 but I personally think it's something quite core.

**Comment by DanielZlotin** [comment]
split views are not in v2 roadmap, but we talked about adding it in the future, and the new v2 architecture is actually ready to handle something like that. 

Regarding custom tab bar: if you mean a react component that will replace the native view: I don't know when we'll add this , as it's not trivial and the api would have to be pretty tight to be of any use for more than 1 project
