### ISSUE TITLE
the size of rightButton will be smaller after hot update of Codepush

### ISSUE THREAD

**Issue by bjwulin** [wix/react-native-navigation#1149]
### Issue Description

my rightbutton's icon is local png，and it's correct when release or debug. but it'size will be smaller after hot update through codepush.

### Steps to Reproduce / Code Snippets / Screenshots
in Android it will happen，and in ios it's no problem
---
### Environment
* React Native Navigation version: 2.0
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?):only android
* Device info (Simulator/Device? OS version? Debug/Release?): Android 6.0

**Comment by junedomingo** [comment]
@bjwulin, You can use PixelRatio https://github.com/wix/react-native-navigation/issues/43#issuecomment-267370982

**Comment by fqborges** [comment]
I am experiencing the same issue.

@junedomingo the PixelRatio thing works, but it is just an workaround.

**Comment by witalobenicio** [comment]
@fqborges how did you solve that? My icons get bigger in release mode.

**Comment by fqborges** [comment]
@witalobenicio I changed the ImageLoader to create BitmapDrawables using a constructor that actually uses the Resources reference, resulting in a drawable that has the correct dpi.

You can view the changes in this commit: https://github.com/fqborges/react-native-navigation/commit/b8256ec6fe80750a5b1f4eaac42a7bba042caa6f

As far as I know, it is already merged on master. You can open the react-native-navigation project from node_modules and check android/app/src/main/java/com/reactnativenavigation/react/ImageLoader.java
