### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by musicode** [wix/react-native-navigation#115]
1. use custom back button is slower than default back button, i want to use default back button but has no pop event
2. even though i use custom back button, i can't prevent pop screen by slide from left to right, so i dont know the current screen
3. i think the tabbar badge is so big when it is just a red point without a number, can i define the size?

**Comment by guyca** [comment]
Hey @musicode 
1. We're starting work on a new major version which will add lifecycle callbacks to your connected screens and back button events as well. We've also faced this issue in our own projects and need a solution asap.

2. If understand correctly, you would like to control the animation used when popping a screen?

3. We use the default badge on iOS, so I assume your talking about Android?

**Comment by musicode** [comment]
for 1

no. because now has no the ability to know current scene, so i use custom back button.

when user press back button, i pop the screen stack, when call navigator.push(), i push a screen to the stack. in this way, i know current screen.

but, user can pop screen by gesture(left to right), i dont know what is happening, so i miss the current screen.

for 2

no. i'm talking about iOS. if badge has a number, the size is perfect, but without a number, the badge is so big. i just want to make it small.

**Comment by guyca** [comment]
Can you post an image with the badge?

**Comment by musicode** [comment]
![image](https://cloud.githubusercontent.com/assets/2732303/16579485/7c1e12b0-42d2-11e6-9a56-a44a8ab26fce.png)

**Comment by musicode** [comment]
maybe the previous image has a mistake, it is what i want, but now is not.

**Comment by messense** [comment]
Issue 1 & 2 are quite annoying. Do you guys have an ETA on resolving them? @guyca

**Comment by guyca** [comment]
@messense We've started work on the new API this week - which will include lifecycle events for screens.
Regarding custom left button on iOS - i'm not aware of any slowness when using custom left button. If you think there's a bug or room for performance improvement, I encourage you to investigate and make a PR if needed.

**Comment by messense** [comment]
@guyca Great!

I am not facing custom left button performance issue, only the default back button has no pop event pains me.
