### ISSUE TITLE
onNavigatorEvent lost when you push an additional view

### ISSUE THREAD

**Issue by lprhodes** [wix/react-native-navigation#116]
After having used `this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this))` in the constructor we then push an additional view (upon user tapping on a row).

When the user goes back to the original view the onNavigatorEvent is no longer called.

**Comment by lprhodes** [comment]
Sorry, this was related to come code I'm working on the intercept and generate back button events

**Comment by sliuqin** [comment]
the last version 2.0.0-experimental.127 still have this bug.
