### ISSUE TITLE
Navigation push event is triggered multiple times

### ISSUE THREAD

**Issue by gameboyVito** [wix/react-native-navigation#1169]
Hi, I'm currently building a four-tab app. Every time, when I switch my app root from singleScreenApp to tabBasedApp, the pre-rendering time is too long which may take me around 2s. During this two-seconds, if I press any button within these four tabs more than once, the onPress event will be triggered multiple times after 2s.

For example, if I press a button to push a new screen multiple times within 2s, says 5 times, then the same new screen will be pushed five times after around 2s.

I found that if I press any button after `componentDidMount()` callbacks were triggered in all tabs, there are no issues at all. I guess this might be related to the processing of pre-rendering all tabs. In the case of building a complex app, rendering all tabs' component right after launching an app will take a long time, during these few seconds, all button press event will be queued and waited until all tabs are rendered. However, this behaviour is wrong, what is correct is that when each tab is rendered, the buttons inside that tab should be able to press instead of waiting and triggering multiple times.

**Comment by DavitVosk** [comment]
Any update on this?

**Comment by gunduzcihat** [comment]
Any solution?

**Comment by RishavKumar-3796** [comment]
Why closeD?

**Comment by GabrielModog** [comment]
Still with no updates?

**Comment by tereshchenkoartyom94-da** [comment]
Why did you closed it?

**Comment by Miran-Saman** [comment]
`setRoot(layout: LayoutRoot): Promise<string>;`

set is promise function you can use `.then` method,
it will render after the root set
