### ISSUE TITLE
Example Crashes on Android Simulator (API 23 & 24)

### ISSUE THREAD

**Issue by DavyDeDurpel** [wix/react-native-navigation#117]
I tried running the redux example on an Adroid Simulator but it always crashes with following stack trace:

07-06 09:48:45.298  2895  2895 D AndroidRuntime: Shutting down VM
07-06 09:48:45.298  2895  2895 E AndroidRuntime: FATAL EXCEPTION: main
07-06 09:48:45.298  2895  2895 E AndroidRuntime: Process: com.exampleredux, PID: 2895
07-06 09:48:45.298  2895  2895 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.clearColorFilter()' on a null object reference
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at com.aurelhubert.ahbottomnavigation.AHHelper.getTintDrawable(AHHelper.java:37)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createClassicItems(AHBottomNavigation.java:320)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems(AHBottomNavigation.java:213)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.addItem(AHBottomNavigation.java:750)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at com.reactnativenavigation.activities.BottomTabActivity.setTabsWithIcons(BottomTabActivity.java:304)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at com.reactnativenavigation.activities.BottomTabActivity.access$100(BottomTabActivity.java:26)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at com.reactnativenavigation.activities.BottomTabActivity$SetupTabsTask.onPostExecute(BottomTabActivity.java:281)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at com.reactnativenavigation.activities.BottomTabActivity$SetupTabsTask.onPostExecute(BottomTabActivity.java:257)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:651)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at android.os.AsyncTask.-wrap1(AsyncTask.java)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-06 09:48:45.298  2895  2895 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-06 09:48:45.299  1519  1839 W ActivityManager:   Force finishing activity com.exampleredux/com.reactnativenavigation.activities.BottomTabActivity

**Comment by DavyDeDurpel** [comment]
It's my own application that causes this error.  For one reason or anther sometimes on windows the packager sends the previous launched application instead of the current one.  I did some new tests today and both examples start correctly.  Now I just have to figure out what I'm doing wrong in my own application (must be something with tabs ;-) )

**Comment by DavyDeDurpel** [comment]
I found the cause of the crash.  I didn't set an icon nor selectedIcon on my tab and that causes the NPE.  Can this considered being a bug?

**Comment by guyca** [comment]
Hey @DavyDeDurpel 
Well, according to the [design guideline](https://material.google.com/components/bottom-navigation.html#bottom-navigation-usage) tabs must have icons.
We should add a proper error screen so developers don't waste time on this.

**Comment by DavyDeDurpel** [comment]
Than I think it's better to update the documentation as it currently states that these properties are optional.

**Comment by guyca** [comment]
Updated the docs. Also now an error is thrown if a tab is missing an icon on Android.

**Comment by DavyDeDurpel** [comment]
Wow, that was fast :-)

I really like this module.  This should be used as an example of how all modules should be written and documented:  clear and straight forward!

**Comment by guyca** [comment]
Thanks for the kind words :)

**Comment by SimchaShats** [comment]
@DavyDeDurpel thanks for this answer it helped also to me...
