### ISSUE TITLE
[Android]if more than 2 screen which  dynamic setStyle in startTabBasedApp app will stop

### ISSUE THREAD

**Issue by IamMonkey** [wix/react-native-navigation#1170]
### Issue Description

if more than 2 screen which each dynamic setStyle in startTabBasedApp app will stop.
ios is no problem

### Environment
* React Native Navigation version: 1.1.42
* React Native version: 0.43.4
* Platform(s) (iOS, Android, or both?): Android

**Comment by guyca** [comment]
Hey @IamMonkey , thanks for reporting. I'm not sure I understood the issue. If there's a crash - a crash log would be most helpful.
