### ISSUE TITLE
Open Drawer from custom navbar

### ISSUE THREAD

**Issue by yayanartha** [wix/react-native-navigation#1171]
Is it possible to open Drawer by clicking a button when navbar is hidden (e.g from custom navbar)?
Swiping from edge screen seems to work fine but not by clicking a custom hamburger button on top of custom navbar.

**Comment by anhtuank7c** [comment]
```
<Button
    title="Open Drawer"
    onPress={() => this.props.navigator.toggleDrawer({
        side: 'left',
        animated: true
    })}
/>
```

**Comment by vivi7** [comment]
What happens if I wwant tu use:
`<NavigationBar.DrawerButton onPress={this.() => {
    this.props.navigator.toggleDrawer({
      screen: 'com.vivi.DrawerMenuScreen',
      animated: true,
      side: 'left',
      backButtonHidden: false
    })} />` ??? attualmente non mi funziona, come posso fare?

**Comment by jsina** [comment]
@anhtuank7c but why when I call the 'toggleDrawer' from "setOnNavigatorEvent" there is no effect?
