### ISSUE TITLE
[boilerplate] RNN + MobX (w/ Provider)

### ISSUE THREAD

**Issue by kanzitelli** [wix/react-native-navigation#1173]
Hey guys,

I have created a small boilerplate RNN + MobX with Provider (so we can use `@inject('store_name')`) as described [here](https://github.com/wix/react-native-navigation/issues/187#issuecomment-265946012).

Also this boilerplate solves (maybe not the best solution) this issue -> [[iOS] Navigation from drawer doesn't work](https://github.com/wix/react-native-navigation/issues/1143) as described [here](https://github.com/wix/react-native-navigation/issues/1143#issuecomment-297627738) but storing `rootNavigator` in the `App` store.

Boilerplate: https://github.com/kanzitelli/react-native-navigation-mobx-boilerplate

And thanks a lot for the great library 👍 waiting for 2.0 version 👍

**Comment by guyca** [comment]
Hey @kanzitelli 
Great job! Would be nice to add this to the [docs](https://wix.github.io/react-native-navigation/#/third-party-libraries-support) 👍

**Comment by kanzitelli** [comment]
@guyca Thank you! And I have added a PR with a small changes in the doc.

**Comment by guyca** [comment]
Nice, Thanks!

**Comment by alonbardavid** [comment]
If anyone is interested, I've made a library to make using RNN and mobx easier:
https://github.com/alonbardavid/intent-router

**Comment by santanu4ver** [comment]
Is there any boilerplate available for [v2]? Using the Provider mentioned [here](https://github.com/kanzitelli/react-native-navigation-mobx-boilerplate/blob/master/src/utils/MobxRnnProvider.js) - I'm still constantly getting following error with v2:

> Error: MobX injector: Store 'someStoreFile' is not available! Make sure it is provided by some Provider

Thanks!

**Comment by santanu4ver** [comment]
Is there any boilerplate available for [v2]? Using the Provider mentioned [here](https://github.com/kanzitelli/react-native-navigation-mobx-boilerplate/blob/master/src/utils/MobxRnnProvider.js) - I'm still constantly getting following error with v2:

> Error: MobX injector: Store 'someStoreFile' is not available! Make sure it is provided by some Provider

Thanks!

**Comment by birkir** [comment]
For v2 you need to wrap every screen with the Provider.

This kit's development branch uses MST without a Provider (v2): https://github.com/ueno-llc/react-native-starter

The master branch has Provider (v1): https://github.com/ueno-llc/react-native-starter/blob/master/src/index.js

**Comment by wagng** [comment]
> Is there any boilerplate available for [v2]? Using the Provider mentioned [here](https://github.com/kanzitelli/react-native-navigation-mobx-boilerplate/blob/master/src/utils/MobxRnnProvider.js) - I'm still constantly getting following error with v2:
> 
> > Error: MobX injector: Store 'someStoreFile' is not available! Make sure it is provided by some Provider
> 
> Thanks!

Here is a starter kit using v2.
https://github.com/wagng/react-native-navigation-redux-starter-kit.git
It also includes a cool redux-saga structure.

**Comment by ialmoqren** [comment]
@santanu4ver I'm facing the same issue
`UnhandledPromiseRejectionWarning: Error: File not found: index.android.js in any of the project roots`
I'm trying to use [react-native-navigation-v1-v2-adapter](https://github.com/wix-playground/react-native-navigation-v1-v2-adapter) and this is how my MainApplication looks like, do you know if there is something missing?

```
public class MainApplication extends NavigationApplication {

  @Override
  public void onCreate() {
    super.onCreate();
    Fabric.with(this, new Crashlytics());
  }

  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  protected List<ReactPackage> getPackages() {
    // Add additional packages you require here
    // No need to add RnnPackage and MainReactPackage
    return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new SvgPackage(),
            new FabricPackage(),
            new RNFirebasePackage(),
            new LinearGradientPackage(),
            new SplashScreenReactPackage(),
            new ReactNativeContacts(),
            new VectorIconsPackage(),
            new RNFirebaseMessagingPackage(),
            new RNFirebaseNotificationsPackage()
    );
  }

  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }
}
```

Thanks a lot

**Comment by ialmoqren** [comment]
In case someone came here for the same issue, this is what worked for me:
```diff
+ import com.reactnativenavigation.react.NavigationReactNativeHost;
+ import com.reactnativenavigation.react.ReactGateway;


public class MainApplication extends NavigationApplication {

  @Override
  public void onCreate() {
    super.onCreate();
    Fabric.with(this, new Crashlytics());
  }

+  @Override
+  protected ReactGateway createReactGateway() {
+      ReactNativeHost host = new NavigationReactNativeHost(this, isDebug(), createAdditionalReactPackages()) {
+          @Override
+          protected String getJSMainModuleName() {
+              return "index";
+          }
+      };
+      return new ReactGateway(this, isDebug(), host);
+  }


  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  protected List<ReactPackage> getPackages() {
    // Add additional packages you require here
    // No need to add RnnPackage and MainReactPackage
    return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new SvgPackage(),
            new FabricPackage(),
            new RNFirebasePackage(),
            new LinearGradientPackage(),
            new SplashScreenReactPackage(),
            new ReactNativeContacts(),
            new VectorIconsPackage(),
            new RNFirebaseMessagingPackage(), // <-- Add this line
            new RNFirebaseNotificationsPackage() // <-- Add this line
    );
  }

  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }


}
```
