### ISSUE TITLE
App stuck on splash screen then crash

### ISSUE THREAD

**Issue by barjas** [wix/react-native-navigation#1175]
### Issue Description

i followed the installation litterly, but the app just crash after stucking on the splash screen

no error, no alert.

### Steps to Reproduce / Code Snippets / Screenshots

install react native new app
install react-native-navigation
run react-native run-ios --device 
----> app crash after splash

NOte: the same app works great on simulator 

---
### Environment
* React Native Navigation version: 1.1.1
* React Native version: 0.43.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): only on Real Device

**Comment by Jahans3** [comment]
Got the same problem, but mine doesn't work on the simulator either

**Comment by godlike1120** [comment]
+1

**Comment by hlouw** [comment]
Might be related to #1191? That issue doesn't mention the app crashing or working in the emulator, so might be a different issue.

**Comment by oky1** [comment]
Same problem on RN 4.4 -  Android device 4.2

**Comment by dktan** [comment]
same problem here, no idea what happening. project due next Monday...help......

**Comment by godlike1120** [comment]
try cleaning your app's cache in emulator or device

**Comment by spencewine** [comment]
same issue here. 

RN: 0.48.4
