### ISSUE TITLE
[Android] Tab bar overlap content

### ISSUE THREAD

**Issue by khatv911** [wix/react-native-navigation#1177]
### Issue Description

Tab bars overlap the content in android. Should it add padding bottom to the inner content? 

### Steps to Reproduce / Code Snippets / Screenshots
<img width="456" alt="screen shot 2017-05-01 at 10 41 09 pm" src="https://cloud.githubusercontent.com/assets/4799209/25584316/af473a16-2ebf-11e7-95ec-ce59d22db35a.png">

---
### Environment
* React Native Navigation version: 1.1.25
* React Native version: 0.43.4
* Platform(s) (iOS, Android, or both?):Android
* Device info (Simulator/Device? OS version? Debug/Release?): Xiaomi 4c 6.0 and geny motion android 5.0

**Comment by khatv911** [comment]
@Ehesp : any comment , Sir?

**Comment by guyca** [comment]
@khatv911 You probably have `drawUnderTabBae: true` in the `navigatorStyle` of that screen

**Comment by khatv911** [comment]
@guyca No, i did not. same result when I change drawUnderTabBar to false.

**Comment by khatv911** [comment]
@guyca : thanks. i found out that it was because of my scrollview.

**Comment by Krizzu** [comment]
Just run into the same problem - iOS displays `FlatList` fine. On Android, list is being drawn under the TabBar, even if `drawUnderTabBar` is set to false.

@khatv911 What was your issue with ScrollView? Maybe this is somehow related :)

Android: 7.0/6.0/5.0
RN: 0.43.3
Navigation: 1.1.134

**Comment by kyle-ssg** [comment]
@krizzu, just a guess here but maybe you need to add a flex:1 to your flatlist (:

**Comment by Krizzu** [comment]
@kyle-ssg Have tried this already, no luck unfortunately.

**Comment by khatv911** [comment]
@Krizzu : try this,
if your scrollview/flatlist is below a navbar, make its position absolute (0,0,0,0). Then, set the navbar on top of it (using z-index). add some padding top(equals to Navbar height) to the contentcontainerview of the scrollview.
