### ISSUE TITLE
navBarTextFontFamily on appStyle attribute does not work

### ISSUE THREAD

**Issue by dabit1** [wix/react-native-navigation#1180]
Hi!

I want to change the titles font family in navbar from a single point. In theory I can fill `navBarTextFontFamily` on `appStyle` and every screen should change the navbar fontfamily, but it is not occurs. However, if I put it on `static navigatorStyle` then it works.
Also I want to change the font size but there is no option to do that, is there any thoughts about it? Thanks!

This is the code:

```js
Navigation.startSingleScreenApp({
    screen: {
      screen: mainScreen,
      animationType: 'fade'
    },
    drawer: {
      left: {
        screen: 'sidemenu'
      },
      disableOpenGesture: true
    },
    appStyle: {
      navBarBackgroundColor: COLORS.first,
      navBarTextFontFamily: 'Raleway-Bold',
      navBarTextColor: 'white',
      navBarTextFontSize: 23,
      statusBarColor: COLORS.first
    }
})
``

React native navigation version: 1.1.45
React native version: 0.43.3
Platfrom: Android
Device: Simulator

**Comment by guyca** [comment]
Thanks for reporting @dabit1 👍

**Comment by enahum** [comment]
What about fontSize for the subtitle?

**Comment by ramneekhanda** [comment]
navBarTitleTextCentered doesnt work too?

**Comment by oliviachang29** [comment]
When is this going to be fixed?
