### ISSUE TITLE
[Android] setStyle navBarButtonColor and navBarLeftButtonColor  not work in a new push screen

### ISSUE THREAD

**Issue by IamMonkey** [wix/react-native-navigation#1181]
### Environment
* React Native Navigation version: 1.1.45
* React Native version: 0.43.4
* Platform(s) (iOS, Android, or both?): Android

**Comment by chboing** [comment]
same here. Same for the main screen in startSingleScreenApp.
Have to set the static navigator style in screen to make it work. setStyle works perfect for right buttons & text. 
react-native 0.42.3
navigation 1.1.45
android
