### ISSUE TITLE
Status bar color flickers from black to white on app start

### ISSUE THREAD

**Issue by grundmanise** [wix/react-native-navigation#1183]
### Issue Description

I have an issue with a flickering status bar color (black -> white)

In my `Navigation.startTabBasedApp({ })` in every tab's `navigatorStyle` I have `statusBarTextColorScheme: 'light'` and in `.plist`: `View controller-based status bar appearance: YES` and `Status bar style: UIStatusBarStyleLightContent`.
But anyway the app starts with a black status bar, and later (when `Navigation.startTabBasedApp({ })` fires) status bar color changes to white.

Does one know how can I force white status bar by default?

---
### Environment
* React Native version:  0.43
* Platform(s) (iOS, Android, or both?): iOS

**Comment by eneskaya** [comment]
Got the same issue, no fix yet.

**Comment by adamjacob** [comment]
I just started noticing this as well.  Anyone have any success fixing it?

**Comment by jpgarcia** [comment]
Facing same issue here 😞

**Comment by emailsubjekt** [comment]
Facing same issue, most likely wrongly set up styles/themes with AndroidManifest definitions for MainActivity
