### ISSUE TITLE
Close app on backPress

### ISSUE THREAD

**Issue by knapeto** [wix/react-native-navigation#1184]
Hey,

how can I close app when Im on first screen and use manual setOnNavigatorEvent for backPress?

Thanks,
Knapeto

**Comment by barretzhi** [comment]
Hey, how did you solve the problem? Can you please share?

**Comment by henrikra** [comment]
I would like to know this too! @knapeto @barretzhi @guyca When overriding backPress the app won't put the app to background when no views in the stack :(

**Comment by henrikra** [comment]
Solved! You can call `BackHandler.exitApp()` when you want the app to close app on back press https://facebook.github.io/react-native/docs/backhandler.html#exitapp :)

**Comment by steven-luu** [comment]
@henrikra I'm curious, which version of RN do you see this behavior on?  I was on 0.44.x and it was working as expected.

I've just upgraded to 0.50.4 and this functionality is no longer working for me.  I'm looking to directly subscribe/unsubscribe to BackHandler when I have the target screens visible now...

**Comment by umerbaig** [comment]
But `BackHandler.exitApp()` is closing the app only on android not on iOS
