### ISSUE TITLE
App Crashes on Start

### ISSUE THREAD

**Issue by Jahans3** [wix/react-native-navigation#1185]
### Issue Description

Every time I start my app, it crashes, without errors. As soon as the bundle has finished loading, it crashes to the simulator home screen.

I have created a new project, to be sure it wasn't anything in my old app, and every time I get the same issue.

### Steps to Reproduce / Code Snippets / Screenshots

1. `react-native init MyApp`
2. `yarn add react-native-navigation`
3. `react-native link`
4. Write the following test file:

```
import { Navigation } from 'react-native-navigation'
import React, { Component } from 'react'
import { View, Text } from 'react-native'

class ScreenOne extends Component {
  render () {
    return (
      <View>
        <Text>Screen One</Text>
      </View>
    )
  }
}

class ScreenTwo extends Component {
  render () {
    return (
      <View>
        <Text>Screen Two</Text>
      </View>
    )
  }
}

(function () {
  Navigation.registerComponent('test.ScreenOne', () => ScreenOne)
  Navigation.registerComponent('test.ScreenTwo', () => ScreenTwo)
})()

Navigation.startTabBasedApp({
  tabs: [
    {
      label: 'One',
      screen: 'test.ScreenOne',
      title: 'Screen One'
    },
    {
      label: 'Two',
      screen: 'test.ScreenTwo',
      title: 'Screen Two'
    }
  ]
})
```

5. `react-native run-ios`
6. App crashes as soon as the bundle finishes loading

Is my setup wrong? I have followed the steps in the iOS install guide to the letter and cannot get it work, I can't even get it to a stage where I'm able to debug it.

---
### Environment
* React Native Navigation version: 1.1.46
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): iOS (though not tried Android)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator (iPhone 6)

**Comment by jtibbertsma** [comment]
react-native link only changes some configuration files. You still need to add some code to AppDelegate.m

Check out this link:
https://github.com/wix/react-native-navigation/blob/master/example/ios/example/AppDelegate.m

**Comment by guyca** [comment]
Hey @Jahans3 
As @jtibbertsma noted, `react-native link` isn't supported. We're looking into adding support for it as we understand it became a standard in the RN echo system.
Please add the missing parts as explained in https://wix.github.io/react-native-navigation/#/installation-ios
