### ISSUE TITLE
Navigator buttons don't emit events to onNavigatorEvent

### ISSUE THREAD

**Issue by brianarpie** [wix/react-native-navigation#1190]
### Issue Description

 Navigator buttons when clicked do not emit events to the navigator event callback.

I tried creating the navigator buttons three different ways: 1) inside `startSingleScreenApp` 2) on the screen component via the `static navigatorButtons` method 3) on the screen component via `this.props.navigator.setButtons` inside `componentDidMount`. All of these created the button properly but none made the onPress events emit.

Is anyone able to reproduce this?

FWIW, I've used this onNavigatorEvent callback in the past with a tab based app w/ event type DeepLink which worked great. This is my first time trying to run a single page based app w/ navigator buttons. Thanks.

### Steps to Reproduce / Code Snippets / Screenshots

``` 
Navigation.startSingleScreenApp({
    screen: {
        screen: 'project.AppRoot',
        navigatorButtons: {
            rightButtons: [
                {
                    icon: require('./assets/settings.png'),
                    id: 'settings'
                }
            ]
        }
    }
});
```
```
class AppRoot extends Component {
    constructor(props) {
        super(props);
        this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
    }
    ...
    onNavigatorEvent(event) {
        // nothing happens here onPress
    }
}

```

---
### Environment
* React Native Navigation version: 1.1.51
* React Native version: 0.43.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone6 & LG Stylo

**Comment by brianarpie** [comment]
I figured it out.

Inside the render function of `AppRoot` I was passing `this.props.navigator` to a child component, which defined `this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));` inside its constructor.

**Comment by jonathan68** [comment]
I have this issue too.
@brianarpie Then I can't set navigator event in both of child and parent components?

**Comment by blairvanderhoof** [comment]
Same with @jonathan68, why can't I have 2 setOnNavigatorEvent calls (parent and child)? Can we fix this?
