### ISSUE TITLE
Getting stuck at splash screen on iOS

### ISSUE THREAD

**Issue by a1q123456** [wix/react-native-navigation#1191]
### Issue Description
Get stuck at splash screen on iOS

### Steps to Reproduce / Code Snippets / Screenshots

here is my AppDelegate.m
```objective-c
#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>

// **********************************************
// *** DON'T MISS: THE NEXT LINE IS IMPORTANT ***
// **********************************************
#import "RCCManager.h"

// IMPORTANT: if you're getting an Xcode error that RCCManager.h isn't found, you've probably ran "npm install"
// with npm ver 2. You'll need to "npm install" with npm 3 (see https://github.com/wix/react-native-navigation/issues/1)

#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;
#ifdef DEBUG
  //  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"dist/index.ios" fallbackResource:nil];
#else
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
  
  
  // **********************************************
  // *** DON'T MISS: THIS IS HOW WE BOOTSTRAP *****
  // **********************************************
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  self.window.backgroundColor = [UIColor whiteColor];
  [[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation];
  
  /*
   // original RN bootstrap - remove this part
   RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
   moduleName:@"example"
   initialProperties:nil
   launchOptions:launchOptions];
   self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
   UIViewController *rootViewController = [UIViewController new];
   rootViewController.view = rootView;
   self.window.rootViewController = rootViewController;
   [self.window makeKeyAndVisible];
   */
  
  
  return YES;
}

@end



```

Screenshot:
![screenshot](http://i.imgur.com/yhcdXN7.jpg)

---
### Environment
* React Native Navigation version: 1.1.1
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): IOS 10.3.1
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device, debug mode

**Comment by hlouw** [comment]
@a1q123456 I've just been stuck on the same issue. 

To get it working you need to replace `AppRegistry.registerComponent(...)` in `index.ios.js` with `Navigation.startSingleScreenApp(...)` or similar.

For example, if your app's main component is called "RunseApp", replace:
```
AppRegistry.registerComponent('RunseApp', () => RunseApp);
```
with
```
Navigation.registerComponent('example.HomeScreen', () => RunseApp);
Navigation.startSingleScreenApp({
  screen: {
    screen: 'example.HomeScreen',
    title: 'Welcome'
  }
});
```

**Comment by a1q123456** [comment]
@hlouw problem solved, thanks 😄

**Comment by thphuc** [comment]
I have same problem but I can not solved. I posted #1246 but it seems nobody gets this issue like me. Please give me any idea to solve if you have. Thanks.

**Comment by chuckkreuser** [comment]
Just to note, you'll need this line on `index.ios.js` for @hlouw's awesome solution:
`import { Navigation } from 'react-native-navigation';`

**Comment by voidstarfire** [comment]
Solves the problem but also creates a new bug with animations.
https://github.com/wix/react-native-navigation/issues/1861

**Comment by dadewoyin** [comment]
Something like this should be in the documentation since I needed to do this to get my app to even run. People shouldn't have to hunt through issue numbers for this.

**Comment by b8ne** [comment]
How is this supposed to work with the new RN running only `index.js` not `index.ios.js`?

**Comment by andreiger** [comment]
Good question and no answer I see. I'm stuck now with the same problem.

**Comment by levy0706** [comment]
> How is this supposed to work with the new RN running only `index.js` not `index.ios.js`?

```
import { Platform } from 'react-native'

if(Platform.OS === 'ios')
 // run code for ios
else
 // run code for android
```
