### ISSUE TITLE
Keep white screen when the first launch after installed.

### ISSUE THREAD

**Issue by ZheJiangEflying** [wix/react-native-navigation#1193]
### Issue Description

Android keep white screen when the first launch after installed. Kill app and launch again, the app return to normal. 

### Steps to Reproduce / Code Snippets / Screenshots

1. install app
2. open app
3. keep white screen
4. kill app
5. open again
6. return to normal

---
### Environment
* React Native Navigation version: 1.1.1
* React Native version: 0.41.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Android 5.1 Release

**Comment by a289459798** [comment]
i same in ios
