### ISSUE TITLE
Unable to fire setOnNavigatorEvent after performing setButtons

### ISSUE THREAD

**Issue by vyky** [wix/react-native-navigation#1196]
### Issue Description

After performing 'setButtons', I can't tap the buttons that have the same id with previous buttons

### Steps to Reproduce / Code Snippets / Screenshots

1. I have static navigatorButtons

```js
static navigatorButtons = {
	rightButtons: [{
		icon: require('../../img/Add.png'),
		id: 'Add'
	}, {
		icon: require('../../img/Edit.png'),
		id: 'Edit'
	}]
}
```

2. Tapping buttons with id `Add` and `Edit` is working as intended. `setOnNavigatorEvent` getting called

3. I tap `Edit` button which perform:

```js
this.props.navigator.setButtons({
	rightButtons: [{
		icon: require('../../img/Add.png'),
		id: 'Add'
	}, {
		icon: require('../../img/Save.png'),
		id: 'Save'
	}]
});
```

4. Now the buttons on navigation are `Save` and `Add` button. I can tap `Save` button, but I cannot tap `Add` button. `setOnNavigatorEvent` for id `Add` not getting called

5. I tap `Save` button which perform:

```js
this.props.navigator.setButtons({
	rightButtons: [{
		icon: require('../../img/Add.png'),
		id: 'Add'
	}, {
		icon: require('../../img/Edit.png'),
		id: 'Edit'
	}]
});
```

6. Now the buttons on navigation are `Edit` and `Add` button. I can't tap either `Add` or `Save` button. `setOnNavigatorEvent` for id `Edit` and `Add` not getting called

---
### Environment
* React Native Navigation version: "1.1.1"
* React Native version: "0.42.3"
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by isaachinman** [comment]
I am experiencing this same issue, except in a more broad sense. The `setOnNavigatorEvent` event is not firing _at all_ after using `setButtons`. This is the case whether or not I have a `static navigatorButtons`.

Is this a known issue? Any workarounds?
