### ISSUE TITLE
navigatorStyle lost on push action

### ISSUE THREAD

**Issue by juancaacuna** [wix/react-native-navigation#1198]
Guys is it normal that for every Push on the navigator, I need to set the navigatorStyle, otherwise it will not keep the same style defined at the beginning at "startSingleScreenApp"? If I don't set the navigatorStyle on the Push action; properties, colors, etc. are lost.

```
Navigation.startSingleScreenApp({
  screen: {
    screen: 'example.WelcomeScreen',
    title: 'Welcome',
    navigatorStyle: {
      drawUnderNavBar: true,
      navBarTranslucent: true,
      navBarBackgroundColor: 'blue'
    }
  }
});
```
and then...

```
this.props.navigator.push({
  screen: 'example.ScreenThree',
  navigatorStyle: {
    drawUnderNavBar: true,
    navBarTranslucent: true,
    navBarBackgroundColor: 'blue'
  }
});
```

Thanks!

**Comment by guyca** [comment]
Hey @juancaacuna 
Yes, thats the expected behavior.  Instead of passing the `navigatorStyle` in each command, You can define the navigatorStyle as a [static object in your screen](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/FirstTabScreen.js#L29).
