### ISSUE TITLE
Back button event

### ISSUE THREAD

**Issue by alidawud** [wix/react-native-navigation#12]
Could you please add a callback event when back to main screen? thank you.

**Comment by maxs15** [comment]
I would also need this event, maybe already implemented but not in the docs ?

**Comment by alidawud** [comment]
I did one, I can send to u if u need

**Comment by maxs15** [comment]
Thanks @alidawud, I would like indeed :)
Do you have a fork with the fix ?

**Comment by maxs15** [comment]
Or event the code here would be enough 👍  Thanks

**Comment by alidawud** [comment]
Sent to you already.

**Comment by manuquentin** [comment]
Hi @alidawud,
can you share the code that you did to get this callback ?

Thanks !

**Comment by maxs15** [comment]
@manuquentin I ended up using componentWillUnmount to detect it, works great

**Comment by drorbiran** [comment]
Please view the following issue #268

**Comment by hubertperron** [comment]
Anyone have a fix to share for this issue?

**Comment by guyca** [comment]
@hubertperron https://github.com/wix/react-native-navigation/issues/369#issuecomment-252500035 might help
