### ISSUE TITLE
TopTabs Styling

### ISSUE THREAD

**Issue by Juliaandavid** [wix/react-native-navigation#1202]
Hi there, really this doesn't an issue, is a question, in the documentation do not appear how I can styling the TopTabs, for example textColor or something. Anyone has the answer?, really sorry because this is not an issue 😃

**Comment by nulleof** [comment]
@Juliaandavid you should define this props in `appStyle` inside `startSingleScreenApp`:

```jsx
      appStyle: {
        orientation: 'portrait',
        topTabTextColor: Color.whiteTransparent,
        selectedTopTabTextColor: Color.white,
      },
```

You can see other options in https://github.com/wix/react-native-navigation/blob/master/src/deprecated/platformSpecificDeprecated.android.js

**Comment by PARAGJYOTI** [comment]
Yes . These are the props you should pass into appStyle .

  appStyle:{
   selectedTopTabIndicatorHeight: 2,
  selectedTopTabTextColor: '#333',
  selectedTopTabIndicatorColor:'#00d1c1',
  topTabsScrollable: false ,
 
}
For more , Here's the reference . https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/views/TopTabs.java

**Comment by helloncanella** [comment]
@Juliaandavid If you started you app with  `startSingleScreenApp` put the properties indicated by @PARAGJYOTI inside `navigatorStyle`.

Example: 

```javascript
Navigation.startSingleScreenApp({
  screen: {
    screen: 'example.FirstTabScreen', // unique ID registered with Navigation.registerScreen
    title: 'Welcome', // title of the screen as appears in the nav bar (optional)
    navigatorStyle: {
      navBarBackgroundColor: 'red',
      navBarTextColor: 'white',
      statusBarColor: 'red',
      navBarButtonColor: 'white',
      topTabTextColor: 'hsl(0,0%,75%)',
      selectedTopTabIndicatorHeight: 4,
      selectedTopTabTextColor: 'white',
      selectedTopTabIndicatorColor: 'white',
    },
    topTabs: [
      {
        screenId: 'example.ThirdTabScreen',
        title: "Third",
      },
      {
        screenId: 'example.SecondTabScreen',
        title: "Second",
      }
    ],
}
```
