### ISSUE TITLE
RCCManager.h not found in AppDelegate.m

### ISSUE THREAD

**Issue by DavidKuennen** [wix/react-native-navigation#1204]
I can't seem to get this to work on ios. 

I installed React via CocoaPods and did as described here: https://wix.github.io/react-native-navigation/#/installation-ios

Also I double-, triple-, quadruple-checked every step described but it's still showing this error. 

I'm using npm version 3.10.10 with react-native-navigation version 2.0.0-experimental.304

**Comment by DavidKuennen** [comment]
Hmm, it seems like CocoaPods is deprecated on React? (https://github.com/facebook/react-native/issues/6125) If it is true I should propably switch to a non-CocoaPods solution for integration and try it again with that configuration.

**Comment by DavidKuennen** [comment]
Solved this myself.

**Comment by YY030913** [comment]
@DavidKuennen how you solved it?

**Comment by davidgruebl** [comment]
please elaborate @DavidKuennen :)

**Comment by brunolemos** [comment]
For v2 this fixed for me: https://github.com/wix/react-native-navigation/issues/876#issuecomment-351489868

**Comment by lefoy** [comment]
For future reference (found this issue via Google):

I solved this issue by using `#import "../../node_modules/react-native-navigation/ios/RCCManager.h"` instead of `#import "RCCManager.h"` in `AppDelegate.m`
