### ISSUE TITLE
[Request] Should support passProps for screen pop api

### ISSUE THREAD

**Issue by dzunglht** [wix/react-native-navigation#1208]
passProps via pop api is the easiest way to handle the returned result like startActivityForResult in Android. The redux approach can do similar things but it requires more code. Please follow "keep it stupid" practice.
Tons of thanks

**Comment by dzunglht** [comment]
4 days passed guys !

**Comment by dzunglht** [comment]
Where are you guys, please follow this ticket
Many of thanks

**Comment by andy9775** [comment]
FYI as a work around you can do `push({passProps: {callback: (args) => {...}}})` then in your latest route do `this.navigator.callback('some info')` 

This isn't ideal, but workable for now.

**Comment by stokesbga** [comment]
this is the dream. would like to see this!
