### ISSUE TITLE
No back button for initial modal screen on iOS

### ISSUE THREAD

**Issue by DavidKuennen** [wix/react-native-navigation#1209]
Somehow there is no back button on my iOS Simulator if I start my screen as modal. It's working fine on android.

It's also working on iOS after a normal push. Just the modal one isn't working.

Is this intended and if yes, what's usually the way to implement the back mechanism on modal views?

**Comment by DavidKuennen** [comment]
Alright, but I already went with a normal push in case it's iOS. I guess that's the way to do in there anyways and it works perfectly fine. Thank you.

**Comment by timwangdev** [comment]
Hi there ,
Modal screen on Android do has a back button on the top left. Is this intended?
I'm working on a unified solution on both platform to handle the back changes, Is there a way to modify this button on Android?

**Comment by timwangdev** [comment]
Found a reply at https://github.com/wix/react-native-navigation/issues/621#issuecomment-274177876 and also `backButtonHidden` option.
Problem solved.
