### ISSUE TITLE
DeviceInfo native module is not installed correctly

### ISSUE THREAD

**Issue by jarvisluong** [wix/react-native-navigation#1210]
### Issue Description

DeviceInfo native module is not installed correctly when I tried to run the example app.

### Steps to Reproduce / Code Snippets / Screenshots

1. clone the repo (master tree)
2. cd to example project.
3. run "npm install"
4. open ios project
5. Run on Xcode

or:

1. clone the repo (master tree)
2. cd to example project.
3. run "npm install"
4. run "react-native run-ios"

---
### Environment
* React Native Navigation version: 1.1.0
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): only iOS
* Device info (Simulator/Device? OS version? Debug/Release?): 
 - iOS: iPhone 7 Plus - iOS 10.3 - Debug

**Comment by jarvisluong** [comment]
Update:

The example project cannot be run in Android version either.
Simulator: - Android 6.0 - Debug

**Comment by slender9168** [comment]
@jarvisluong 
did you manage to find a solution ?

Thanks.

**Comment by jarvisluong** [comment]
@slender9168 nope I haven't

**Comment by slender9168** [comment]
@jarvisluong 
The issue for me was  solved by this answer :

http://stackoverflow.com/questions/43727332/deviceinfo-native-module-is-not-installed-correctly/43735695#43735695

( xcode had the packager of another react native project running in the background )

Hope it helps

**Comment by hramos** [comment]
This usually happens when you have a packager for a different project running. It's not a react-native-navigation issue.

**Comment by jarvisluong** [comment]
Thanks! I understand why it happened now.
