### ISSUE TITLE
Tabbasedapp from after singlepage

### ISSUE THREAD

**Issue by efnan34** [wix/react-native-navigation#1211]
My question is simple but i couldnt handle. How can we go from single page to tab page i checked whole documents but i couldnt see any clue about this .There look like these two method are totally work seperately.Any documentation or example for this because i couldnt bump into yet 

Thanks a lot

**Comment by junedomingo** [comment]
Inside your **component**, you just need to import **Navigation** and use it this way
```js
import React, { Component, PropTypes } from 'react';
...
import { Navigation } from 'react-native-navigation';

class ExampleScreen extends Component {
	constructor(props) {
		super(props);

		this._switchToTabBased = this._switchToTabBased.bind(this);
	}

	_switchToTabBased() {
		Navigation.startTabBasedApp({
			tabs: [
				{
					label: 'One',
					screen: 'example.ScreenOne',
					... // icons
					title: 'Screen One',
					navigatorStyle: {
						...navigatorStyle
					}
				},
				{
					label: 'Two',
					screen: 'example.ScreenTwo',
					... // icons
					title: 'Screen Two',
					navigatorStyle: {
						...navigatorStyle
					}
				}
			]
		});                // or better to move this into a separate file
	}

	render() {
		return (
			<View>
				<TouchableOpacity onPress={this._switchToTabBased}>
					<Text>Switch to TabBased App</Text>
				</TouchableOpacity>
			</View>
		);
	}
}
```

**Comment by efnan34** [comment]
Thank you very much indeed for a quick response! I am so new at React.I have been a wake more than 8 hours for trying codes above.It gave  many errors because of mosly and especially my faults and also being my sleepless.Here is where i am stuck totally and exhausted.If you have any chance to check  the version of code.

## Here is the problem ;
Android device stops application when i touch 

> Swich to Tab Base App

 I think the view of application can be loaded once at core concepts .I mean if the app starts with singlebaseapp it runs like this, not able to load an other screenview. 

 Thanks to god no red error screen but now it breaks down. The project is still so  simple so far because i couldnt overcome navigation issue so i am not able to carry on my project.



**# This  is index.android.js**

```
import {Navigation} from "react-native-navigation"


import {app1} from "./source/app1"
import {page} from "./source/page"
import {tabbe} from "./source/tabbe"


Navigation.registerComponent('app1', () => app1);
Navigation.registerComponent('page', () => page);
Navigation.registerComponent('tabbe', () => tabbe);

Navigation.startSingleScreenApp({
  screen: {
    screen: 'app1',
    title: 'Navigation Bootstrap'
  }
});
```

**# This is app1.js**
```

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableOpacity
} from 'react-native';
import {Navigation} from 'react-native-navigation';

import {tabbe} from "./tabbe"
import {page} from "./page"

export class app1 extends Component {
	constructor(props) {
		super(props);

		this._switchToTabBased = this._switchToTabBased.bind(this);
	}

	_switchToTabBased() {

		

		Navigation.startTabBasedApp({
			tabs: [
				{
					label: 'tabbe',
					screen: 'page',
					icon:("../source/police-hatirlatici.png"),
                    title: 'Screen One'
				
				},
				{
					label: 'page',
					screen: 'page',
				 icon:("../source/police-hatirlatici.png"),
                 title: 'Screen two'
				}
			]
		});
    	          
	}

	render() {
		return (
			<View>
				<TouchableOpacity onPress={this._switchToTabBased}>
					<Text>Switch to TabBased App</Text>
				</TouchableOpacity>
			</View>
		);
	}
}

```

I didnt put the other two pages becaus they are just almost blank page says hello 
Thanks you again .

P.S : the documentation of React native navigation need to be reorganized by someone who knows the core of this plugin

**Comment by efnan34** [comment]
SOLVED

**Comment by kimgysen** [comment]
I tried this solution, which works on iOS, but it crashes on the Android emulator for me. In the debug logs nothing shows up, and in the runtime logs nothing shows up either. It just keeps crashing. Frustrating...

**Comment by gopi9703** [comment]
i am getting the following error 

undefined is not a function (evaluating '_reactNative Navigation 2.default.startTabBasedApp')
![screenshot_1527945131](https://user-images.githubusercontent.com/3668067/40874932-b669adf2-6694-11e8-9e2c-f45b8600702d.png)

Here is my code:

import React, { Component } from 'react';
import { View, Text, StyleSheet, Image, TextInput, TouchableOpacity, KeyboardAvoidingView, Button } from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import Navigation from 'react-native-navigation';
import Logo from '../../components/Logo';
import Offers from '../main/Offers';
import Brands from '../main/Brands';


class AuthScreen extends Component {


    constructor(props) {
		super(props);

		this._switchToTabBased = this._switchToTabBased.bind(this);
    }
    

    _switchToTabBased() {
		Navigation.startTabBasedApp({
			tabs: [
                {
                    screen: 'Wafi.Offers', 
                    label: 'Offers',        
                    title : 'Offers'
                },
                {
                    screen: 'Wafi.Brands', 
                    label: 'Brands',  
                    title : 'Brands'
                }
			]
		});                // or better to move this into a separate file
	}

    handlePress = () => {
        this.props.navigator.push({
            screen: 'Wafi.Register',
            navigatorStyle: {
                navBarHidden: true
            },
        });
    };

    ForgotPassword = () => {
        this.props.navigator.push({
            screen: 'Wafi.Forgotpassword',
            navigatorStyle: {
                navBarHidden: true
            },
        });
    };


    render() {
        return (
            <LinearGradient colors={['#621C6C', '#8E0076', '#B8007F']} style={styles.linearGradient}>
                <KeyboardAvoidingView style={styles.container} behavior="padding" enabled>
                    <View style={styles.container}>
                        <Logo />
                        <TouchableOpacity style={styles.buttonBlock}>
                            <Text style={styles.buttonText} onPress={this._switchToTabBased}>Login</Text>
                        </TouchableOpacity>
                       
                        </View>
                    </View>
                   
                </KeyboardAvoidingView>

            </LinearGradient>
        );
    }
}


How to solve this error, quick response would be appreciable...

**Comment by gergo123** [comment]
Your import statement should look like the following:
`import { Navigation } from 'react-native-navigation';`

(ps.: you should google named vs default exporting/importing of modules in javascript)
