### ISSUE TITLE
Ability to present modal from the tab controller directly on tab based app

### ISSUE THREAD

**Issue by scotbond** [wix/react-native-navigation#1216]
Is there any decent way to present a modal screen on top of the main tabController after starting with `Navigation.startTabBasedApp` ?
In native iOS for instance, UITabBarController is inherited from UIViewController which allows you to present a modal directly through that rather than through a child view controller in the tabController's stack.
This is needed for things like login screen, where you want the business logic stay out of the child VC, particularly the one residing on the first tab.

**Comment by scotbond** [comment]
I managed to swap between single screen app to tab based app on app launch upon login. gave up on the nice modal dismiss animation, but it works.

**Comment by mehdijjz** [comment]
this is disappointing
