### ISSUE TITLE
navBarHideOnScroll - White box shows and hides over the TabBar

### ISSUE THREAD

**Issue by juancaacuna** [wix/react-native-navigation#1218]
When I use `navBarHideOnScroll: true`, the navBar hides perfectly, but when it shows again, a white box blinks at the bottom (over the TabBar). Is this a known issue?

Thanks guys!

```
const navigatorStyle = {
  navBarHideOnScroll: true,
  navBarBackgroundColor: "black",
  navBarButtonColor: "white",
}
```

**Comment by guyca** [comment]
Hey @juancaacuna 
You need to draw your screen below the `BottomTabs` - add `drawUnderTabBar: true` to the `navigatorStyle`
