### ISSUE TITLE
Remove gradient in navBar

### ISSUE THREAD

**Issue by ariona** [wix/react-native-navigation#1219]
When using Collapsing react Header (https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=collapsing-react-header), I notice there is a subtle dark gradient on the NavBar, how do i remove it?

Below is my navigatorStyle:

```js
static navigatorStyle = {
    navBarTextColor: 'white',
    navBarTextFontFamily: 'arahamah_bold',
    navBarButtonColor: 'white',
    navBarHideOnScroll: false,
    navBarBackgroundColor: '#22B8CF',
    collapsingToolBarComponent: 'Tanzil.SurahHeader',
    navBarTranslucent: true,
    showTitleWhenExpended: false,
    collapsingToolBarCollapsedColor: 'transparent',
    collapsingToolBarExpendedColor: 'white',
    screenBackgroundColor: 'white'
}
```
### Environment
* React Native Navigation version: 1.1.51
* React Native version: 0.43.4
* Platform: Android
* Device info: Android / Device / Debug

**Comment by junedomingo** [comment]
try adding `drawUnderNavBar: true`

**Comment by ariona** [comment]
@junedomingo that's not working, it only draw the top part of Listview behind the header component

**Comment by guyca** [comment]
`navBarTranslucent: false` ?

**Comment by ariona** [comment]
Setting `navBarTranslucent` to `false` makes the navBar white. 😄  I've been playing with navBarBackgroundColor, navBarTransparent but no luck.
I am switching back to regular navbar, I think the collapsingHeader still not stable. Whenever i reload the app the app got crashed. 🙁

**Comment by guyca** [comment]
Might be the translucent effect can't be removed in collapsing headers.
"Whenever i reload the app the app got crashed." - with out a crash log there's not much I can do.

**Comment by ariona** [comment]
yeah, there is no log in the console? where should i look for the crash log?

**Comment by guyca** [comment]
logcat

**Comment by ariona** [comment]
Nope, there was no error. weird. :)

**Comment by manrashid** [comment]
> I am switching back to regular navbar, I think the collapsingHeader still not stable. 

Me too. Image header also shown correctly on emulator but disappear when install signed apk on device. Weird. No error. Spent more time with collapsingHeader than using wix navigation.

wix react-native-navigation still the best though. Thank you so much.
