### ISSUE TITLE
Navigation Lagging/Slow in Release

### ISSUE THREAD

**Issue by JPig** [wix/react-native-navigation#1221]
### Issue Description

When in Debug Mode the app navigation performs smooth and as expected, but as soon as i build the apk for release, all navigation performance dies.

- Bottom Tab Animations are jittery and laggy,
- Modal Fade in Jitters/Lags.

This has me stumped as it only happens when the app is compiled to an apk.

### Steps to Reproduce / Code Snippets / Screenshots

Tab Based App with 4 Tab Screens

---
### Environment
* React Native Navigation version: 1.1.64
* React Native version: 0.43.0
* Platform(s): Android 6.0.1
* Device info: Samsung S6 (RELEASE)

**Comment by JPig** [comment]
I swapped out the .png Tab Icons i was using for react-native-vector-icons and it no longer lags/jitters in release, not sure why using png's could cause this.

**Comment by guyca** [comment]
That's very strange. Last time I checked - `react-native-vector-icons` generates the icons once and saves them as pngs to disk, Maybe it's not related to the file format.

**Comment by JPig** [comment]
Yeah it does, thats what confused me when the lag stopped after changing to that. Well i guess the issue is "solved" for now haha.
