### ISSUE TITLE
navBarButtonColor doesn't override AppStyle. navBarButtonColor [Dynamic buttons]

### ISSUE THREAD

**Issue by dabit1** [wix/react-native-navigation#1223]
Hi!

Setting button through dynamic method never doesn't change the color. 

An example:

```js
import MaterialIcon from 'react-native-vector-icons/MaterialIcons'

export default class Activity extends Component {

  static navigatorStyle = {
    navBarLeftButtonColor: 'red',
    navBarButtonColor: 'red'
  }

  constructor(props) {
    super(props)

    MaterialIcon.getImageSource('arrow-back', 35).then(icon => {
      props.navigator.setButtons({
        leftButtons: [{
          icon,
          id: 'back',
          buttonColor: 'red'
        }]
      })
    })
  }

  //...
}
```
React native navigation version: 1.1.63
React native version: 0.43.3
Platfrom: Android
Device: Simulator

**Comment by guyca** [comment]
`navBarLeftButtonColor` and `navBarButtonColor` are not supported on Android. use `navBarButtonColor` which handles color for both left and right buttons

**Comment by dabit1** [comment]
Sorry, I'm not understand you. I put every way to set color (`navBarLeftButtonColor`, `navBarButtonColor` and `buttonColor`) to demostrate that none of them works.Therefore you say me that `navBarButtonColor` are not supported but I should use `navBarButtonColor` ? I supose you are mistaking. Please could you explain me that?

**Comment by guyca** [comment]
Sorry, I misread you comment. I'll recheck the issue 👍

**Comment by SunnyEver0** [comment]
I have the same issue,when I set the button color ,but It didn't work.

**Comment by guyca** [comment]
Hey @dabit1 
`buttonColor` is only supported on iOS. `navBarButtonColor` works for me when setting custom buttons.

**Comment by dabit1** [comment]
Hi @guyca , ok, if I use another ID different of `back` then it works. But `navBarButtonColor` still not working. However, why couldn't I use `back` to only change the icon and keep its functionallity? I think it will be better.

**Comment by dabit1** [comment]
I just found the problem. If I set `navBarButtonColor` on `appStyle` and I try to overrride it on `navigatorStyle` then don't work. The overriding is not working.
