### ISSUE TITLE
Compilation Failed after upgrade RN

### ISSUE THREAD

**Issue by bdebout** [wix/react-native-navigation#1224]
Hi,

I just upgraded react native to 0.44.0 version and I get this error:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-navigation:compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED

And Android Studio's Event log : 

> Executing tasks: [:app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources, :react-native-navigation:generateDebugSources, :react-native-navigation:generateDebugAndroidTestSources, :react-native-navigation:mockableAndroidJar, :react-native-navigation:prepareDebugUnitTestDependencies, :realm:generateDebugSources, :realm:generateDebugAndroidTestSources, :realm:mockableAndroidJar, :realm:prepareDebugUnitTestDependencies]

Need some help with that ! Thanks !

---
### Environment
* React Native Navigation version: 4.2.0
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): AVD from Android Studio (6.0 API 23) and tested with a second AVD (7.1.1 API 25) => got same build failed

**Comment by DanielZlotin** [comment]
>React Native Navigation version: 4.2.0 
❓

**Comment by bdebout** [comment]
My bad !

Here my package.json file : 

```
{
  "name": "App",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "^15.5.4",
    "react-native": "^0.44.0",
    "react-native-checkbox": "^1.1.0",
    "react-native-navigation": "^1.1.65",
    "realm": "^1.2.0",
    "redux": "^3.6.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "~15.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

I also made a stackoverflow post: 

[http://stackoverflow.com/questions/43888927/build-failed-after-upgrade-react-native-to-0-44-v?noredirect=1#comment74831854_43888927](url)

**Comment by bdebout** [comment]
I made these changes :  (see stackoverflow link below)

> I finally updated my build.gradle app to 25 compileSdkVersion from 23 and the buildToolsVersion to '25.0.2' from '23.x.x'.
> 
```
>  android {
>      compileSdkVersion 25
>      buildToolsVersion "25.0.2"
```
> 
> It compiled and I can run my app again for now.
