### ISSUE TITLE
Issue on navigation.push using startTabBasedApp

### ISSUE THREAD

**Issue by Juliaandavid** [wix/react-native-navigation#1225]
It seems that this is a old issue, but I'm not sure, so let's go. On iOS i have a startTabBasedApp like this: 
![screen shot 2017-05-09 at 7 16 42 pm](https://cloud.githubusercontent.com/assets/13870317/25877874/18b4245a-34ec-11e7-9c8e-d2cc099ba05b.png)

When I press one of the items listed, `this.props.navigator.push` is executed, then this happened:
![screen shot 2017-05-09 at 7 19 37 pm](https://cloud.githubusercontent.com/assets/13870317/25877919/7b0b9458-34ec-11e7-85b2-2bc3a5c865d2.png)

So, as you can see, the new screen does not overlap on the tabs, and stays inside. Is this an issue? Or is there a way in which the screen overlaps?

### Environment
* React Native Navigation version: 1.1.65
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): (This I've only tried on iOS, I'm not sure if it's also an issue of android.)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 6 (10.3) Debug.

**Comment by junedomingo** [comment]
Did you add `flex: 1` in your Calendar container?

**Comment by Juliaandavid** [comment]
@junedomingo Yes, but in this case what should I do? I've tried playing with styles but I can not do it, any suggestions?

**Comment by manrashid** [comment]
To save time, try use showModal instead of push.
