### ISSUE TITLE
deep link how to combine native scheme

### ISSUE THREAD

**Issue by a289459798** [wix/react-native-navigation#1226]
like  [https://reactnavigation.org/docs/guides/linking](https://reactnavigation.org/docs/guides/linking)

**Comment by junedomingo** [comment]
Can you add more details? 

You might want to checkout [Handling Deeplinks](https://wix.github.io/react-native-navigation/#/deep-links) in RNN Docs

**Comment by a289459798** [comment]
For example：
`
// register 
Navigation.registerComponent('/user/:uid', () => UserInfo);

//deep link

// open UserInfo Component
this.props.navigator.handleDeepLink({
    link: '/user/123'
})
`
like https://reactnavigation.org/docs/guides/linking or https://github.com/ReactTraining/react-router
