### ISSUE TITLE
Android multiple modals, dismiss ignores orientation

### ISSUE THREAD

**Issue by Jpoliachik** [wix/react-native-navigation#1229]
When two or more modals are pushed and the top one is popped, the orientation reverts back to the App's default orientation and disregards any modals still displaying. (Android only)

Example: 
1. Start Single screen with "portrait" orientation
```
Navigation.startSingleScreenApp({
  appStyle: {
    orientation: "portrait"
  },
  ...
});
```

2. Push a landscape modal - Modal1
```
Navigation.showModal({
  navigatorStyle: {
    orientation: "landscape"
  },
  ...
});
```

3. Push a second landscape modal - Modal2
4. Dismiss top modal `Navigation.dismissModal()` 

Modal1 will be displaying, but it reverts to portrait, even though Modal1 was specified as landscape.

Digging in, it looks like in `Modal.java` in the `onDismiss` method reverts back to the App's root orientation. This disregards the orientation of any modals still displaying. 
```
@Override
    public void onDismiss(DialogInterface dialog) {
        destroy();
        setOrientation(AppStyle.appStyle.orientation);
        onModalDismissedListener.onModalDismissed(this);
    }
```

Any Android guys know the proper solution to check for the top modal's orientation in `onDismiss`?

**Comment by guyca** [comment]
Thanks for reporting, will get to this asap
