### ISSUE TITLE
Android build fails "Configuration with name 'default' not found"

### ISSUE THREAD

**Issue by ovaris** [wix/react-native-navigation#1232]
### Issue Description

I'm trying add RNN to my project but it fails to build:
```
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.
```
I have checked million times instructions & all possible examples but no luck :(

---
### Environment
* React Native Navigation version: 2.0.1 (tried also latest stable)
* React Native version: 0.42.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):gradle:2.2.3, compileSdkVersion 23, buildToolsVersion "23.0.1"

**Comment by DanielZlotin** [comment]
You are installing the alpha channel, which is currently half-baked. Please use `latest` for general use.
This looks like incorrect settings.gradle in your project. Should be something like:

```groovy
include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/android/app/')
```
and in build.gradle:
```groovy
dependencies {
    compile project(':react-native-navigation')
}

```

**Comment by myp007** [comment]
I also reported this mistake, have you solved it?

**Comment by rknell** [comment]
I (stupidly) installed react-native-navigation in the wrong folder. So the error may mean that there are simply no source files found

**Comment by heron2014** [comment]
I have exactly the same issue on Android: 

```A problem occurred configuring project ':app'.
Could not resolve all dependencies for configuration ':app:_debugApk'.
 Configuration with name 'default' not found.
```

Can someone please explain this issue? I don't know how to resolve it. What am I doing wrong?

- *settings.gradle*

```include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/android/app/')
```

- *build.gradle*


```
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.1"
```

```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':RNPermissionsModule')
    compile project(':react-native-navigation')
}
```

- *MainApplication.java*

```java

public class MainApplication extends NavigationApplication {

  // private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
  //   @Override
  //   public boolean getUseDeveloperSupport() {
  //     return BuildConfig.DEBUG;
  //   }
  //
  //   @Override
  //   protected List<ReactPackage> getPackages() {
  //     return Arrays.<ReactPackage>asList(
  //         new MainReactPackage(),
  //           new MapsPackage(),
  //           new ImagePickerPackage(),
  //           new ReactNativeConfigPackage(),
  //           new VectorIconsPackage(),
  //           new RNPermissionsPackage()
  //     );
  //   }
  // };

  @Override
  public boolean isDebug() {
      // Make sure you are using BuildConfig from your own application
      return BuildConfig.DEBUG;
  }

  protected List<ReactPackage> getPackages() {
      // Add additional packages you require here
      // No need to add RnnPackage and MainReactPackage
      return Arrays.<ReactPackage>asList(
        new MapsPackage(),
        new ImagePickerPackage(),
        new ReactNativeConfigPackage(),
        new VectorIconsPackage(),
        new RNPermissionsPackage()
      );
  }

@Override
public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
  RNPermissionsPackage.onRequestPermissionsResult(requestCode, permissions, grantResults); // very important event callback
  super.onRequestPermissionsResult(requestCode, permissions, grantResults);
}
  // @Override
  // public ReactNativeHost getReactNativeHost() {
  //   return mReactNativeHost;
  // }
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }

  // @Override
  // public void onCreate() {
  //   super.onCreate();
  //   SoLoader.init(this, /* native exopackage */ false);
  // }
}
```

- *MainActivity.java*

```java
import com.reactnativenavigation.controllers.SplashActivity;

public class MainActivity extends SplashActivity {

}
```


My environment is:
- "react-native":  "0.48.0"
-  "react-native-navigation": "^1.1.235"

**Comment by imanshu1** [comment]
simply run  $ npm i and it will work :)

**Comment by imanshu1** [comment]
$ npm i  , it will work

**Comment by randauto** [comment]
@imanshu1 thanks! =)) It worked with me.

**Comment by obrahimi** [comment]
@imanshu1  can you please tell me what is the command to run?

**Comment by imanshu1** [comment]
@obrahimi  reinstall your npm module will work 
 $ npm i

**Comment by anaghakomawar** [comment]
Please help me to know the path for settings.gradle

Thanks in advance

**Comment by shackra** [comment]
If it is half baked, why in the world the readme says this?:

> We are currently in late stages of development of v2, which is published to npm under alpha tag.
> 
> * New to RNN? We recommend you start with v2.

**Comment by anubhav19rai** [comment]
Please run this command **react-native upgrade**. This command will ask replace existing file or not. If you    want to replace a particular file press Y and hit enter button or press N. After completing this command than run command  **react-native link**. This command will link all dependencies than you can run command **react native run-android /ios**. This issue create when you uninstall some dependencies so sometimes  it do not update build files like setting.gradle build.gradle etc.

**Comment by Miljarder** [comment]
I have the same problem and I have tried everything that you have explained.. Could I be using wrong  version of RN? I am using 0.55.4.
