### ISSUE TITLE
How get side menu width?

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#1235]
Hi guy,

How i can get side menu width.

Thanks so much!

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by junedomingo** [comment]
**Getting** *Sidemenu width*.

In your SideMenu component

```js
<View style={{ width: 200 }} onLayout={e => { console.log(e.nativeEvent.layout.width); }}>
     ... // content
</View>

// output: 200
```
