### ISSUE TITLE
handleDeepLink not working on android?

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#124]
Version: 1.0.27

**Comment by guyca** [comment]
Not support at the moment

**Comment by agumack** [comment]
@guyca thank you for reply
I am using handleDeepLink instead of "push". because push not support when called from drawer sidemenu. It working fine on IOS. 
Can you suggest a solution for android version app while wait support?

**Comment by guyca** [comment]
Hey @agumack 
I checked the deep links implementation and it should work on Android.

But there's something else that might have caused the confusion, Currently there's a difference ,between iOS and Android, in the way screens are created:

* iOS - all of your tabs are created when your app starts. (The constructor of the First screen of each tab is called)
* Android  - Tabs are created when the user first navigates to them.

The deepLink event is handled in `onNavigatorEvent` which is registered in the constructor, so you won't get deepLink events in screens you did not navigate to yet.
Could this be the issue you have?

**Comment by agumack** [comment]
@guyca  i tried example on android, when i tab link from sidemenu alway error "this.props.navigator is undefined

when i call this.props.navigator on my apps, have the problem too.

IOS working fire!!!

**Comment by guyca** [comment]
fixed in v2.0
