### ISSUE TITLE
The application works only with Internet connection.

### ISSUE THREAD

**Issue by oky1** [wix/react-native-navigation#1247]
### The application works only with an Internet connection.

Throws from the application or not loading if no internet. No errors in console.

---
### Environment
* React Native Navigation version:  latest
* React Native version: 4.4
* Platform(s) (iOS, Android, or both?):  Android
* Device info (Simulator/Device? OS version? Debug/Release?):  Android  4.2 ( device )

**Comment by guyca** [comment]
Probably not related to rnn
