### ISSUE TITLE
Disable elevation on toolbar

### ISSUE THREAD

**Issue by RichardLindhout** [wix/react-native-navigation#125]
Disable shadow on toolbar would be cool!

**Comment by guyca** [comment]
Hey @RichardLindhout I assume you're referring to the shadow underneath the Toolbar on Android?

**Comment by RichardLindhout** [comment]
Yes!

Op 14 jul. 2016 14:47 schreef "Guy Carmeli" <notifications@github.com>:

**Comment by guyca** [comment]
[Elevation](https://material.google.com/what-is-material/elevation-shadows.html) is part of google's [design guideline](https://material.google.com/layout/structure.html#). Can you please describe the use case where you'd want to disable the default elevation?

**Comment by RichardLindhout** [comment]
When you have a scrollable tab below it. Which is not yet supported here ;)

Op 14 jul. 2016 15:18 schreef "Guy Carmeli" <notifications@github.com>:

**Comment by guyca** [comment]
We're going to implement tabs in the AppBar real soon. @rotemmiz has already started work on it.

**Comment by RichardLindhout** [comment]
Thanks for the heads up! I like this library.

Some suggestions
- collapsingtoolbar and such things would be cool if we have that also in
the iPhone version Android support it already but not in this library or
react native

Op 14 jul. 2016 19:10 schreef "Guy Carmeli" <notifications@github.com>:

**Comment by guyca** [comment]
[Collapsing BottomNavigation](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B3321sZLoP_HNUFCLXIwV2FOcDQ/components_bottomnavigation_behavior_backtotop.webm) (BottomTabs as we call them) will be merged next week and collapsing ToolBar is also in the works

**Comment by RichardLindhout** [comment]
Thats really cool!

Op 15 jul. 2016 12:08 schreef "Guy Carmeli" <notifications@github.com>:

**Comment by guyca** [comment]
fwiw, it's possible to remove shaddow on Android now:

```js
static navigatorStyle = {
    topBarElevationShadowEnabled: false
  };
```

**Comment by studiobrain** [comment]
Where is this to be placed in order to render or rather not render the shadow?
