### ISSUE TITLE
TitleBar Animation Bug when pushing Screen with hidden TitleBar

### ISSUE THREAD

**Issue by zobeirhamid** [wix/react-native-navigation#1252]
### Issue Description
When pushing a new screen without TitleBar and without StatusBar, the previous Screen's Title Bar get also animated.

### Bug
![titlebar](https://cloud.githubusercontent.com/assets/20030709/26068754/7502d9d4-3953-11e7-9fe8-eebb9807517b.gif)
**Pushed Screen static navigatorStyle:**
` 
static navigatorStyle = {
        navBarHidden:true,
        statusBarHidden:true
}
`

**How the push is triggered:**
` 
 this.props.navigator.push({
            backButtonTitle: '',
            screen: 'example.AlbumScreen',
})
`

---
### Environment
* React Native Navigation version: 1.1.72
* React Native version: 0.43.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6 Simulator

**Comment by gran33** [comment]
There is a single StatusBar, and it's shared between screens. So if u decide to push a screen without statusBar u'll get this behaviour.
If u want to have a different behaviour, so try to set the statusBar in the `didAppear` lifeCycle events (https://wix.github.io/react-native-navigation/#/screen-api?id=listen-visibility-events-in-onnavigatorevent-handler)
