### ISSUE TITLE
Navbar not translucent when using background color

### ISSUE THREAD

**Issue by chrise86** [wix/react-native-navigation#1259]
I have the following `navigatorStyle`:

```
navBarBackgroundColor: 'rgba(210, 29, 53, 0.76)',
navBarTranslucent: true,
drawUnderNavBar: true
```

but the content does not seem to actually draw under and shine through the navbar. Removing the background colour fixes this, however the navbar then turns a grey colour which is not what I want. 

Is there any way of setting a navbar tint colour?

**Comment by Ehesp** [comment]
Yeah so this is something called immersive mode which is currently not supported (Android). I'm not sure what the iOS equivalent is called. ccing @guyca as I've spoke with him about this in the past.

**Comment by chrise86** [comment]
@Ehesp I think from scouting around StackOverflow that there is a hack to get this effect, which involves setting a transparent background image :-/

**Comment by ZionChang** [comment]
@chrise86 
It works on both iOS and android, when I use the following style in my screen.
```javascript
static navigatorStyle = {
    drawUnderNavBar: true,
    navBarTranslucent: true,
    navBarTransparent: true,
    navBarBackgroundColor: 'transparent'
};
```

**Comment by chrise86** [comment]
@ZionChang the issue is not with getting a transparent navbar, the issue is not having translucency when using a background colour (other than transparent, which isn't necessary)

**Comment by ZionChang** [comment]
@chrise86 I totally got it wrong about what you said, sorry.

**Comment by huhu087** [comment]
@chrise86 here is the pr: https://github.com/wix/react-native-navigation/pull/1548
