### ISSUE TITLE
iOS minimum version can not be 8?

### ISSUE THREAD

**Issue by lucasleelz** [wix/react-native-navigation#1260]

**Comment by gran33** [comment]
@lucasleelz Thanks for reporting.
Can u plz add some more info? any log? errors?

Thanks in advance.

**Comment by lucasleelz** [comment]
@gran33 hi, thank you for your reply.
When I switch to `v2` branch,  iOS project `ReactNativeNavigation` depends on iOS 9.0,`iOS Deployment Target` === 9.0.
and the version specified in `ReactNativeNavigation.podspec` is also iOS 9.0.

So I have doubts because my current project is needed to support more than iOS 8.0.
I really like this library so I want to use it, but it supports more than iOS 9.0.
