### ISSUE TITLE
RNN 1.1.72 Tabbar dynamic Image icon

### ISSUE THREAD

**Issue by Amurmurmur** [wix/react-native-navigation#1264]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]
How can I change tabbar icon to another image when the REST API response from the action comes back? Similar to what instagram has for their profile tab, when the tabicon changes to a profile picture once its loaded from the server.
### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.72
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by jp928** [comment]
@Amurmurmur
not sure if the api 
'''javascript
this.props.navigator.setTabButton
''''
will do the job or not.
