### ISSUE TITLE
Could Not Run On Simulator: ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by adlahd3** [wix/react-native-navigation#1265]
### Issue Description

Could Not Build The App to run in the simulator ( After Following the installation Guide. 

### Steps to Reproduce / Code Snippets / Screenshots

1- Done Exactly What is Written in the iOS installation Section. 
2- running react-native run-ios
 

---
### Environment
* React Native Navigation version: 1.1.74
* React Native version: 0.44.0
* Platform: iOS
* Device info: Simulator

**Comment by thevest** [comment]
Check your Info.plist file, it can become invalid for various reasons, make sure it's all valid xml and check the CFBundleIdentifier key

```
    <key>CFBundleIdentifier</key>
    <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
```

If that doesn't work/ is not the problem check your project's build settings, under packaging, and ensure the Info.plist File is pointed at the correct place.

**Comment by adlahd3** [comment]
Tried The Solutions Above, Even I Began from the Scratch Again. 
Could Not Make it work.

**Comment by jonbcampos** [comment]
@thevest same issue. updated plist, no fix. any other thoughts? @adlahd3 did you get it working?

**Comment by adlahd3** [comment]
The issue happened when I updated some images, the reloaded the app.
It might solve your problem if you shut down the simulator, the terminal, and the web debugger. then restart them again.

**Comment by arapocket** [comment]
I have the same issue. I'm losing my mind uninstalling and rm-rf ing and reinstalling everything.
