### ISSUE TITLE
Question: Windows support?

### ISSUE THREAD

**Issue by alixeb** [wix/react-native-navigation#1266]
### Question

Does this work in a windows app?
Any plan to support react-native-windows?

---
### Environment
* React Native Navigation version: any
* React Native version: 0.42
* Platform(s) (iOS, Android, or both?): Windows (react-native-windows 0.42)

**Comment by guyca** [comment]
Hey @alixeb 
Unfortunately rnn currently doesn't support windows phone and there are no plans to add add such support in the foreseeable future. If someone from the community is willing to add and maintain windows phone support - that will be most welcome.
