### ISSUE TITLE
[iOS, Android] Orientation change in LightBox

### ISSUE THREAD

**Issue by mdrbohlav** [wix/react-native-navigation#1270]
LightBox screen dimensions do not update when orientation is changed. I tried ScrollView with flex 1 as a root element. Display LightBox in portrait and rotate the device.
OnLayout is not fired and there is no way how to handle orientation change.

Am I missing something?

---
### Environment
* React Native Navigation version: 1.1.77
* React Native version: 0.40.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): iOS simulator, iPhone SE (10.3.2), OnePlus 2 (6.0.1)

**Comment by staufman** [comment]
I'm seeing the same thing. As a workaround (a bad one, I'll admit!), I am listening to the rotation event (i.e. `DeviceEventEmitter.addListener('orientationDidChange', this.onOrientationChange)`) and then in the event of a lightbox being open during an orientation change, I am dismissing the open lightbox and opening a new one. It's not elegant but it seems to be working.
