### ISSUE TITLE
Cannot use react native Linking.openurl()

### ISSUE THREAD

**Issue by alzalabany** [wix/react-native-navigation#1271]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by okarakose** [comment]
so ? you just write a title and clicked to the create new issue ? you should describe your problem as well as you can and you should share code snippets. so other people can help you
