### ISSUE TITLE
[IOS] toggleDrawer does not work on IOS

### ISSUE THREAD

**Issue by Kabangi** [wix/react-native-navigation#1279]
### Issue Description

Am using `startSingleScreenApp(params)` app on both android and IOS, I have configured everything on android the drawer works well

On IOS though  calling `this.props.navigator.toggleDrawer()`  does not display the sidemenu. but swiping on the edges makes it work.

### Environment
* React Native Navigation version: v1.1.79
* React Native version: 0.43.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device

Kindly help figure this out. Am stack on this part.

**Comment by Mubashirkhan** [comment]
this seems to be working for me

on my App.js file 
`startApp() {
		Navigation.startSingleScreenApp({
      screen: {
        screen: 'FootballApp.Landing', // unique ID registered with Navigation.registerScreen
        title: 'FootballApp', // title of the screen as appears in the nav bar (optional)
        navigatorStyle: {}, // override the navigator style for the screen, see "Styling the navigator" below (optional)
        navigatorButtons: {
					leftButtons: [
			      {
			        title: 'Menu', // for a textual button, provide the button title (label)
			        id: 'menu', // id for this button, given in onNavigatorEvent(event) to help understand which button was clicked
			        testID: 'e2e_rules', // optional, used to locate this view in end-to-end tests
			        showAsAction: 'ifRoom', // optional, Android only. Control how the button is displayed in the Toolbar. Accepted valued: 'ifRoom' (default) - Show this item as a button in an Action Bar if the system decides there is room for it. 'always' - Always show this item as a button in an Action Bar. 'withText' - When this item is in the action bar, always show it with a text label even if it also has an icon specified. 'never' - Never show this item as a button in an Action Bar.
			        buttonColor: 'blue', // Optional, iOS only. Set color for the button (can also be used in setButtons function to set different button style programatically)
			        buttonFontSize: 14, // Set font size for the button (can also be used in setButtons function to set different button style programatically)
			        buttonFontWeight: '600', // Set font weight for the button (can also be used in setButtons function to set different button style programatically)
			      }
			    ],
					rightButtons: [
			      {
			        title: 'Edit', // for a textual button, provide the button title (label)
			        id: 'edit', // id for this button, given in onNavigatorEvent(event) to help understand which button was clicked
			        testID: 'e2e_rules', // optional, used to locate this view in end-to-end tests
			        disabled: true, // optional, used to disable the button (appears faded and doesn't interact)
			        disableIconTint: true, // optional, by default the image colors are overridden and tinted to navBarButtonColor, set to true to keep the original image colors
			        showAsAction: 'ifRoom', // optional, Android only. Control how the button is displayed in the Toolbar. Accepted valued: 'ifRoom' (default) - Show this item as a button in an Action Bar if the system decides there is room for it. 'always' - Always show this item as a button in an Action Bar. 'withText' - When this item is in the action bar, always show it with a text label even if it also has an icon specified. 'never' - Never show this item as a button in an Action Bar.
			        buttonColor: 'blue', // Optional, iOS only. Set color for the button (can also be used in setButtons function to set different button style programatically)
			        buttonFontSize: 14, // Set font size for the button (can also be used in setButtons function to set different button style programatically)
			        buttonFontWeight: '600', // Set font weight for the button (can also be used in setButtons function to set different button style programatically)
			      }
			    ]

				} // override the nav buttons for the screen, see "Adding buttons to the navigator" below (optional)
      },
      drawer: {
        left: {
          screen: 'FootballApp.SideMenu',
          passProps: {},
        },
        disableOpenGesture: false
      },
      passProps: {},
      animationType: 'slide-down'
    });
	}`

on my screen file i have used this code
`constructor(props) {
		super(props);
		this.props.navigator.setOnNavigatorEvent(this._onNavigatorEvent.bind(this));
	}

	_onNavigatorEvent(event) {
		if (event.type === 'NavBarButtonPress') {
			if (event.id === 'menu') {
				this.props.navigator.toggleDrawer();
			}
		}
	}`
