### ISSUE TITLE
render fixed components above tabBar

### ISSUE THREAD

**Issue by michaelknoch** [wix/react-native-navigation#1280]
Is there a possibility to render "fixed" components above the tabBar? We have a component with persistent visibility and position independent of the current navigation state, which should be rendered above the tabBar.

It should behave like the player of the spotify app. As you can see it is a global view which will always stay on top of the navigation rendered above the tabBar.

<img width="300" src="https://cloud.githubusercontent.com/assets/5617793/26306446/b10c4816-3ef3-11e7-83e8-b9578894ac1b.PNG">

We are currently rendering our fixed view manually in every screen of the whole app, which works for now but looks strange when using navigator.push and pop with view transitions.

Is there an existing api which will work for us?
thanks a ton for your help.

@guyca

**Comment by guyca** [comment]
Hey @michaelknoch 
If you push the screen without animation and animate the screen content yourself in JS, does that still look bad?

On Android, you can try wrapping the persistant component in a [Shared Element Transition](https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=shared-element-transition). When using SET, the screens cross fades when pushing, you can disable the animation and animate the screen content your self.

**Comment by smowden** [comment]
Hey @guyca,
thanks for your response, we are currently trying to implement the animations ourselves. However we encountered a problem. It seems we can only disable animations when pushing and poping through JS code. However we make use of NavBars and when hitting the back button in the navbar the default animation is performed. Is there some way to disable animations on nav bar back button presses or globally?

**Comment by guyca** [comment]
Hey @smowden 
Yes you can definitely use `overrideBackPress` on Android. What you can do on iOS is set your own custom back button and handle it your self.

**Comment by nerdmed** [comment]
@guyca thanks for your support this still sounds like band aid and is kind of a hack. It should be straight forward to not override native animations and just rendern **above** all views, on the same level like the TabBar. Do you have any suggestions on how to add this feature or maybe achieve this goal with your current implementation?

**Comment by michaelknoch** [comment]
I'm wondering if there is an easy solution for this feature:

[platformSpecificDeprecated.ios.js](https://github.com/wix/react-native-navigation/blob/master/src/deprecated/platformSpecificDeprecated.ios.js#L68-L91)

```js
renderBody: function() {
      return (
        <TabBarControllerIOS
         //...
        </TabBarControllerIOS>
      );
}
```

is it possible to wrap these "hijacked react components" with react-native views?

```js
renderBody: function() {
    return (
    <View style={{flex: 1}}>
      <View style={{position: 'absolute', bottom: 50, left: 0, right: 0, height: 100}}> 
         // render global persistent stuff here 
     </View>
        <TabBarControllerIOS
         //...
        </TabBarControllerIOS>
    </View>
    );
}
```

Thanks for your awesome support @guyca

**Comment by guyca** [comment]
@michaelknoch That's a very interesting approach, though on Android you'll need to get your hands dirty and do some native work (on Android the layout is created entirely in native side) - did you get a chance to try this out?

**Comment by michaelknoch** [comment]
unfortunately it does not render the view and it seems to crash silently without warning or errors in the log. I'm not quite sure how to debug this behaviour @guyca

**Comment by steve228uk** [comment]
+1 to this. We're looking to achieve a similar design with the bar at the bottom in place of the tab bar. I tried the same approach but it seems the the render method needs to return a controller of sorts or the stack will break and refuse to render anything.

I may be able to achieve this natively on iOS by adding a subview to the navigation controller but ideally it would be great if there were a solution built in for both iOS and android to allow for views over the top of the navigation controller.

On iOS the likely place for these to go would be to add them directly to the `UIWindow` or `UIWindow.main().rootViewController`.

**Comment by steve228uk** [comment]
@michaelknoch @guyca I've achieved this by creating and registering a new component with the `AppRegistry` in React Native and then adding a subview onto the `RCCNavigationController` [here](https://github.com/steve228uk/react-native-navigation/blob/master/ios/RCCNavigationController.m#L66-L73).

Obviously this is a hack at this point but I think there's a possibility of adding a `TabOverlayView` and `NavigationOverlayView` to the API that will add a subview to either the Navigation Controller or Tab Bar Controller. This will then allow devs to decide on where to add the subview they need overlaid and can style directly in React Native.

I'm happy to submit a PR once I've got Android working to implement this and would appreciate any comments or suggestions on how to better implement this. I'm relatively new to React Native so I'm not sure `viewDidLoad` is the best point in the cycle to add the view.

**Comment by steve228uk** [comment]
I've submitted a PR #1392 that aims to add this ability. It's a WIP and I'm focusing on iOS currently as that's where my experience lies but any thoughts are appreciated.

**Comment by sajsanghvi** [comment]
anyone have a solution?

**Comment by guyca** [comment]
Hey guys
We've added Overlay api to v2. You can find an example [here](https://github.com/wix/react-native-navigation/blob/v2/playground/src/screens/OptionsScreen.js#L232)
I'm closing the issue for now as it is resolved in v2

**Comment by pie6k** [comment]
Wooohoooooo!
