### ISSUE TITLE
[Question] Why do navigation methods have to be called through props?

### ISSUE THREAD

**Issue by braco** [wix/react-native-navigation#1282]
Just curious why we need access methods through `this.props.navigator.push` instead of using imports directly: 

```
import { Navigation }  from 'react-native-navigation'
Navigation.push(...)
```
It makes navigation difficult and complicated out of the context of screen components. People have done some [hacky things](https://github.com/wix/react-native-navigation/issues/405) to work around this.

**Comment by guyca** [comment]
Because the navigator contains the screen id and navigation stack id the screen is associated with.
In the next version all methods will be static and you'll only need to pass the screen id from props.
`Navigation.on(this.props.screenId).push()` for example
