### ISSUE TITLE
[info][tid:main][RCTPerformanceLogger.m:80] Unbalanced calls start/end for tag 16

### ISSUE THREAD

**Issue by hackable** [wix/react-native-navigation#1285]
### Issue Description

Whenever i run the code in logged it shows  ``[info][tid:main][RCTPerformanceLogger.m:80] Unbalanced calls start/end for tag 16``

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.79
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): simulator

**Comment by ODelibalta** [comment]
I have the same thing. 

```
"dependencies": {
    "axios": "^0.16.2",
    "lodash": "^4.17.4",
    "native-base": "^2.3.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.4",
    "react-native-navigation": "^1.1.143",
    "react-native-vector-icons": "^4.2.0",
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "redux-persist": "^4.8.2",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
```

**Comment by avirefundit** [comment]
Have the same issue. I can't understand what does that mean? ios11

**Comment by Sorin-fratila** [comment]
also seeing this while testing out my app in target iOS=9; Not sure what to point it to since on Android I haven't seen this kind of issue. Some packages that I added since last time I checked iOS functionality are: socket.io-client, react-native-elements, upgraded react-native-navigation, 

Here is my package-json: 
"dependencies": {
    "@babel/runtime": "^7.1.2",
    "axios": "^0.18.0",
    "jwt-decode": "^2.2.0",
    "react": "^16.5.0",
    "react-native": "^0.57.2",
    "react-native-calendar-events": "^1.6.4",
    "react-native-document-picker": "^2.2.0",
    "react-native-elements": "^0.19.1",
    "react-native-image-picker": "^0.27.2",
    "react-native-maps": "^0.22.1",
    "react-native-navigation": "^2.2.5",
    "react-native-vector-icons": "^6.0.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.1",
    "rxjs": "^6.3.3",
    "socket.io-client": "^2.1.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.0.1",
    "babel-jest": "23.6.0",
    "eslint": "^5.7.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.0",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  }

**Comment by hahtml** [comment]
I still see this issue in RNN 2.13.1. Anyone could have a peek and see what it means?
