### ISSUE TITLE
startTabBasedApp works only with running local-cli/cli.js start.

### ISSUE THREAD

**Issue by oky1** [wix/react-native-navigation#1289]
startTabBasedApp works only with running local-cli/cli.js start.
Crashes app when Offline.

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): device android 4.2

**Comment by guyca** [comment]
@oky1 This has been reported a couple of times before. I'm wondering if this is indeed a bug. In a vanilla RN project - when installing debug apk, can you run it with out the device connected to packager?

**Comment by oky1** [comment]
But nothing has changed. The application does not work if there is no Internet.
I really need to run the application on production to make sure that the tabs are working?

**Comment by oky1** [comment]
startSingleScreenApp works - StartTabBasedApp not.  
 if (icon === null) Crash the app? 
 or what?

**Comment by guyca** [comment]
Can you please explain the issue in detail once again? Initially you state that the app crashes when device is not connected to packager (local-cli/cli.js start) - now you state your app crashes if device is not connected to the internet?

**Comment by oky1** [comment]
You closed unsolved issues.
https://github.com/wix/react-native-navigation/issues/1041

**Comment by guyca** [comment]
@oky1 Indeed I closed other issues. I'm trying to understand from you if I was wrong or not. How is the app supposed to work with out connection to the packager? Images and the bundle its self are served by the packager.  When building an app in debug mode - images are not bundled in the binary - instead they are resolved as urls served over the bridge.

**Comment by oky1** [comment]
The startTabBasedApp should not crashes if there is no connection to the server.
The application must work offline.

**Comment by oky1** [comment]
How about cached icons.Tabs without any icons. Default icon or whatever to not crash the app at all

**Comment by guyca** [comment]
@oky1 The images in the BottomTabs are not connected to fresco cache, they are simple `Drawable` and I find little value in connecting them to cache.

> startTabBaseApp crashes without any errors.
This is plain wrong. Use `adb logcat` to view exceptions.

> The application must work offline.
What happens in a vanilla RN project when you terminate the packager in the following scenarios:
1. When app is open
2. When app is in background and reopened
3. When app is closed and is reopened

**Comment by oky1** [comment]
https://www.dropbox.com/s/bsko556i3mu3f60/logcat.txt?dl=0

**Comment by oky1** [comment]
I/AEE/AED (15575): java.lang.RuntimeException: Unable to start activity ComponentInfo{
com.animatedd/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.RuntimeException: http://localhost/assets/img/one@3x.png?platform=android&hash=8b7141f7a41da1026033defb3b972b2e

NetInfo.isConnected.fetch().then(isConnected => {
  isConnected ? 'localhost' : ' where is my icons?'));
});

**Comment by oky1** [comment]
Nevermind
