### ISSUE TITLE
How to hide tab-bar on a specific tab

### ISSUE THREAD

**Issue by crisu83** [wix/react-native-navigation#129]
Hello, first I'd like to say thanks for this great library.

I'm currently working on a project where I would like to hide the tabs when a specific tab is active, much like the camera tab on the Instagram app, where you have to press cancel in order to return to the home screen. I've tried to find a solution, but so far I haven't had any success. It seems that there is no way to add custom buttons to the tab-bar with callbacks and that navigator events are not triggered when screens are activated.

Can you think of a way to achieve this? Thank you in advance.

**Comment by guyca** [comment]
Hey @crisu83 
You can define a [static `navigatorStyle` block](https://github.com/wix/react-native-navigation#styling-the-navigator) in the relevant screen, which will define the screen-specific styling options.

I think `tabBarHidden` is the property you'd want to use.

**Comment by avishayil** [comment]
```javascript
export default class YourClass extends Component {
    static navigatorStyle = {
        tabBarHidden: true
    };
}
```

**Comment by DveMac** [comment]
This doesnt work on tab 0 until you move away from tab 0 and back again. I would like to control the tabs completely programmatically but there does not seem to anyway to hide the tabbar permanently?

**Comment by grundmanise** [comment]
Hi @guyca , it's still an issue. `navigatorStyle = { tabBarHidden: true }` does not work until you move from the initial tab.  `static navigatorStyle = { tabBarHidden: true };` and other 'clean' solutions does not work either. What works (but is not so clean) is to call `toggleTabs({ to: 'hidden', animated: false })` in the `componentWillMount` in my initial (tab 0) component & set `drawUnderTabBar: true` in the main `navigatorStyle`

**Comment by guyca** [comment]
@grundmanise @DveMac On which platform are you reproducing this bug?
Setting `tabBarHidden: true` in navigatorStyle of the screen displayed in first tab seems to work fine on Android

**Comment by grundmanise** [comment]
@guyca iOS 10.2, iPhone 5s (real device)

**Comment by DveMac** [comment]
I saw the issue on iOS (all devices, real and simulator, ios8 upwards), I have not tested whether this is still an issue since my last post.

**Comment by guyca** [comment]
Thanks 👍

**Comment by mariotacke** [comment]
Running into this right now on iOS 10.3, iPhone 6 (Simulator), RN 0.44. Using the workaround @grundmanise suggested, but it flashes for a split second and you can see the tab bar. :/

**Comment by mcampsall** [comment]
I would also like this supported. I was able to use the workaround suggested by @grundmanise and it works on load, but the tabBar flashes back in place when I navigate away from tab 0 and you see it throughout the animation transition.

**Comment by yomybaby** [comment]
@mcampsall Thanks, it's only working solution that I found! :)
I can't not understand why there is no simple way to remove tabbar as a default. :(

**Comment by shuaibird** [comment]
The version I use is `1.1.281`, and the `react-native` version used is `0.49.5`.
Setting the `tabBarHidden` to `true` works perfectly for me at the `tab 0` on iOS device, but doesn't work on android. I finally work it out by both setting the `tabBarHidden` to `true` and using the `toggleTabs` to programmatically hide the tab.
```js
static navigatorStyle = {
    tabBarHidden: true,
}
componentWillMount() {
    this.props.navigator.toggleTabs({
        to: 'hidden',
        animate: true,
    })
}
```
One thing to mention here is that using only the `toggleTabs` doesn't work either. The related issue is reported here: #2075

**Comment by rendomnet** [comment]
Is issue with tab0 will be resolved?
