### ISSUE TITLE
DrawerNavigator width and transparency

### ISSUE THREAD

**Issue by mocanSergiu666** [wix/react-native-navigation#1290]
I am looking for making the drawer navigator to fill the screen and to make it transparent.
How can I achieve this?
I searched for info in [https://reactnavigation.org/docs/navigators/drawer](https://reactnavigation.org/docs/navigators/drawer), but there's no info I need :   (
 
### Environment
* React Native version: 0.44
* Platform: Android

**Comment by junedomingo** [comment]
Hi @mocanSergiu666 , check out [movieapp](https://github.com/junedomingo/movieapp). It has transparent Drawer on android.

**Comment by d3fkon** [comment]
@junedomingo I'd appreciate it if you could post the code which makes the Drawer transparent. 
@mocanSergiu666 You can use Dimensions.get('window') to deconstruct the window width and then apply it to the style

**Comment by canaan5** [comment]
add
drawerBackgroundColor: "transparent"
to drawerConfig
