### ISSUE TITLE
[Question] Adding support for functional components in registerComponent

### ISSUE THREAD

**Issue by ShaunLloyd** [wix/react-native-navigation#1292]
### Issue Description
Currently `Navigation.registerComponent` only accepts class components and I wondered why that is? The documentation says that `registerComponent` takes the given component class and wraps it in the libraries `Screen` component. If that is the case then what would be the possibility of adding support for functional components?

### Steps to Reproduce / Code Snippets / Screenshots
Pass a functional component into the `registerComponent` method

---
### Environment
* React Native Navigation version: 1.1.79
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): iOS simulator.

**Comment by Jpoliachik** [comment]
@ShaunLloyd did you gain any insight before closing this? I have the same question. Specifically, I'm trying to figure out the best way to implement my own screen wrapper.

**Comment by Jpoliachik** [comment]
I hacked together a functional wrapper hooked up to my redux state:

`Navigation.registerComponent(screens[i].key, () => Container(screens[i].component), store, Provider);`

`Container` looks like this: 
```

import { View, Text, ActivityIndicator, StyleSheet } from "react-native";
import { connect } from "react-redux";

// Generator function that builds our Container class
// using a dynamic Screen
export default function Container(ViewObject) {
  // which redux props to inject, given the state tree
  const mapStateToProps = function(state) {
    return {
    };
  };

  return connect(mapStateToProps)(
    class extends ViewObject {
      static navigatorStyle = ViewObject.navigatorStyle || {};
      static navigatorButtons = ViewObject.navigatorButtons || {};

      render() {
        return (
          <View style={styles.container}>
            {super.render()}
          </View>
        )
      }
    }
  );
}
```
