### ISSUE TITLE
[iOS] UI Bars > Toolbars

### ISSUE THREAD

**Issue by inlinecoder** [wix/react-native-navigation#1296]
Will react-native-navigation ever support NATIVE implementation of [UI Bars > Toolbars](https://developer.apple.com/ios/human-interface-guidelines/ui-bars/toolbars/)? With background blurs, of course.

This is a very important component for creating non-bullshit native iOS apps. More over, almost any app has this toolbar if it doesn't have a [UI Bars > Tab Bars](https://developer.apple.com/ios/human-interface-guidelines/ui-bars/tab-bars/)

Examples:
<img width="868" alt="screen shot 2017-05-27 at 05 08 12" src="https://cloud.githubusercontent.com/assets/4806743/26517099/9b735440-429a-11e7-8474-f0203ac5ffba.png">
<img width="393" alt="screen shot 2017-05-27 at 05 07 17" src="https://cloud.githubusercontent.com/assets/4806743/26517101/9b9d3fbc-429a-11e7-9960-c4c65c409aa9.png">
<img width="389" alt="screen shot 2017-05-27 at 05 07 12" src="https://cloud.githubusercontent.com/assets/4806743/26517100/9b9b805a-429a-11e7-8976-b838d6074a2e.png">

There's a lot of confusion in terminology on the Internet, but I'm glad, you guys keep up the good work with proving native-looking native-behaving components. No thanks to Facebook, for NOT creating a very basic set for everyone. Seemingly, they don't have money for it (*facepalm*).

**Comment by chrise86** [comment]
This would be SUPER helpful!

**Comment by witalobenicio** [comment]
This would be EXTREMELY helpful!
