### ISSUE TITLE
[Android] Tabbar is pushed up by keyboard

### ISSUE THREAD

**Issue by viper4595** [wix/react-native-navigation#1299]
My tabbar is pushed by keyboard up, just on Android. Anyone help ?
![abc](https://cloud.githubusercontent.com/assets/21328574/26522416/5fa3671c-432a-11e7-8e4f-28f2c570ab4a.png)

**Comment by guyca** [comment]
Hey @viper4595 
On Android, the keyboard pushes the entire app up, while on iOS they keyboard is displayed over the app. You'll need to hide the tabbar your self.

**Comment by GyyBest** [comment]
Please do you have a solution?

**Comment by manrashid** [comment]
@GyyBest Use showModal instead of push.

**Comment by ChrisGatzo** [comment]
I fixed it by adding the following to my app's manifest

```
<activity android:name="com.reactnativenavigation.controllers.NavigationActivity"
         android:windowSoftInputMode="stateAlwaysHidden|adjustPan|adjustResize" />
```

**Comment by viper4595** [comment]
My temp solution is toggle tabbar manually 
`this.props.navigator.toggleTabs({
  to: 'hidden', // required, 'hidden' = hide tab bar, 'shown' = show tab bar
  animated: true // does the toggle have transition animation or does it happen immediately (optional)
});`

**Comment by M-Jas** [comment]
@guyca I did exactly like @viper4595 solution of toggling(when needed), but it did not work. The tabs themselves did hide, but the tab bar still pushed up with the keyboard. I notice this happens after I switch tabs or navigate to a new screen and then route back. 

<img width="315" alt="screen shot 2017-09-24 at 1 25 07 pm" src="https://user-images.githubusercontent.com/13804811/30784917-d5d18626-a12b-11e7-9237-3c1f6defab65.png">

**Comment by M-Jas** [comment]
I found a fix @guyca. I switched the animations off with the toggle. No clue why that worked, but it is preforming as planned. Maybe it's the animation of switching tabs and keyboard mixing up the positioning. 

- Keyboard out
this.props.navigator.toggleTabs({
  to: 'hidden',
  animated: false
});

-Keyboard hidden. 
this.props.navigator.toggleTabs({
  to: 'shown',
  animated: false
});

**Comment by quy1403** [comment]
@ChrisGatzo I fixed this bug by your good solution (<activity android:name="com.reactnativenavigation.controllers.NavigationActivity"
         android:windowSoftInputMode="stateAlwaysHidden|adjustPan|adjustResize" />)
It worked successfully, but Keyboard.addListener('keyboardDidShow') does not work. Do you face the same problem? thanks

**Comment by profiVideos** [comment]
@ChrisGatzo, that worked for me as well.  Thanks.  Now the tabbar is staying put!  :-)

**Comment by ChrisGatzo** [comment]
@quy1403 sorry I don't have access to the code anymore.

**Comment by CusProjects** [comment]
@ChrisGatzo If you want to keep the automatic keyboard avoiding view you just have to set "adjustPan"

**Comment by rcorrie** [comment]
This ended up being my problem: https://github.com/facebook/react-native/issues/12980

Aparently, `StatusBar` doesn't play nicely with `KeyboardAvoidingView` on android.

**Comment by adamterlson** [comment]
@CusProjects Can you be more specific?  What is the full line you used to achieve tab hiding and keyboard avoiding functionality?

**Comment by CusProjects** [comment]
@adamterlson Sure. 
`<activity android:name="com.reactnativenavigation.controllers.NavigationActivity"
         android:windowSoftInputMode="stateAlwaysHidden|adjustPan|adjustResize" />` if you do this like so, the automatic keyboard avoiding view disappear from your app. So then if you just set the attribute "AdjustPan" like this 
`<activity android:name="com.reactnativenavigation.controllers.NavigationActivity"
          android:windowSoftInputMode="adjustPan"  />`  you are keeping the Automatic android avoiding view.

**Comment by javi10823** [comment]
Hi, i having this issue, i change in my manifiest to adjustPan but did'nt work! 

 I have this manifiest:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.app">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <application
		android:name=".MainApplication"
		android:label="@string/app_name"
		android:icon="@mipmap/ic_launcher"
		android:allowBackup="false"
		android:theme="@style/AppTheme">
		<activity
			android:name=".MainActivity"
			android:label="@string/app_name"
			android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
			android:windowSoftInputMode="adjustResize">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

**Comment by Jatapiaro** [comment]
@GibranPolonsky How we can do this with the v2?

**Comment by DavitVosk** [comment]
@Jatapiaro could you find a solution in v2?

**Comment by viper4595** [comment]
For V2, try this option: 

  ```
 bottomTabs: {
    visible: false,
      animate: false,
     drawBehind: true // for Android
 } 
```

**Comment by DavitVosk** [comment]
@viper4595 thanks for the answer. But actually I need the bottom tabs to be visible at the bottom of the screen. They just should not be pushed up with keyboard. My problem is that... I tried to pass`drawBehind: true` to bottomTabs, but it did not work

**Comment by viper4595** [comment]
@DavitVosk, you can use that option to hide the bottom tab manually whenever the input is focused.

```
hideBottomTab = () => {
      Navigation.mergeOptions(this.props.componentId, {
        bottomTabs: {
           visible: false,
           animate: false,
          drawBehind: true // for Android
        }
      })
    }
```

**Comment by DavitVosk** [comment]
It means that in new v2 version Android tabBar is pushed up by keyboard as default?

**Comment by viper4595** [comment]
I think so, As guyca said at second comment

**Comment by DavitVosk** [comment]
But I think it should be some global solution like 
`<activity android:name="com.reactnativenavigation.controllers.NavigationActivity"
         android:windowSoftInputMode="stateAlwaysHidden|adjustPan|adjustResize" />`
 in `v1`
