### ISSUE TITLE
Lifecycle event for finished opening Navigation.showModal()

### ISSUE THREAD

**Issue by ronaldheft** [wix/react-native-navigation#130]
I'm placing an expensive item to render in a modal (the camera), and if it renders during open on Android, the screen experiences jank and dropped frames.

I'd like to solve the issue by not initializing the camera until the modal has finished opening. Reading over the React Native docs, the suggested method for this is to fire code on `InteractionManager.runAfterInteractions`, but I'm seeing this event trigger before the modal is fully open. I assume react-native-navigation is not currently linked with that lifecycle event.

What is the recommended way to run code after a modal opens? Right now I'm working around the issue by setting a simple timeout, but ideally I'd like this linked to a lifecycle event. Thanks.

**Comment by guyca** [comment]
Hey @ronaldheft 
Life cycle events, including `onDisplayed`, will be added in version 2.0, which we estimate will be available by the end of next month.

**Comment by DarynHolmes** [comment]
Has this been included in v2?

Would this help my problem - http://stackoverflow.com/questions/40085583/how-to-trigger-an-event-when-a-component-is-shown-when-using-react-native-naviga/40086855#40086855

**Comment by guyca** [comment]
@DarynHolmes Not yet.
