### ISSUE TITLE
tap background to dismiss lightBox

### ISSUE THREAD

**Issue by nimamyscreen** [wix/react-native-navigation#1301]
is there any listener to dismiss lightBox through tapping background ?

**Comment by joarwilk** [comment]
You could make a wrapper TouchableX which covers the whole screen and trigger lightbox dismissals and then render your lightbox inside of that.

**Comment by nimamyscreen** [comment]
it's working but this touch contains the box too , so when I click the box it's dismissed . I want to exclude the box from background.

**Comment by guyca** [comment]
https://wix.github.io/react-native-navigation/#/top-level-api?id=showlightboxparams-

set `tapBackgroundToDismiss: true`

**Comment by Jonas-Arvidsson** [comment]
@guyca 

`tapBackgroundToDismiss` does not work

```
 Navigation.showLightBox({
      screen: "SortScreen", // unique ID registered with Navigation.registerScreen
      title: "Modal", // title of the screen as appears in the nav bar (optional)
      passProps: {event}, // simple serializable object that will pass as props to the modal (optional)
      navigatorStyle: {}, // override the navigator style for the screen, see "Styling the navigator" below (optional)
      navigatorButtons: {}, // override the nav buttons for the screen, see "Adding buttons to the navigator" below (optional)
      animationType: 'slide-up', // 'none' / 'slide-up' , appear animation for the modal (optional, default 'slide-up')
      //tapBackgroundToDismiss: true,
      style: {
        backgroundBlur: "dark", // 'dark' / 'light' / 'xlight' / 'none' - the type of blur on the background
        backgroundColor: "#00000099", // tint color for the background, you can specify alpha here (optional)
        tapBackgroundToDismiss: true // dismisses LightBox on background taps (optional)
      }
    });
```

**Comment by guyca** [comment]
@Jonas-Arvidsson On which platform?

**Comment by Jonas-Arvidsson** [comment]
@guyca 

Android!

**Comment by guyca** [comment]
@Jonas-Arvidsson Works for me. Which version are you using?

**Comment by Jonas-Arvidsson** [comment]
@guyca 

Updated and now it works. Thanks for taking the time to give me the obvious answer :+1:

**Comment by gameboyVito** [comment]
@nimamyscreen you may need to set your box style to `zIndex: 1`

**Comment by CusProjects** [comment]
@Jonas-Arvidsson Please tell us how did you solve this.

**Comment by Jonas-Arvidsson** [comment]
@CusProjects Simply updated the package `npm install react-native-navigation@latest`

And
 `style:
 {
        tapBackgroundToDismiss: true 
 }`

**Comment by nimamyscreen** [comment]
still have problem in android(have not tested yet in ios)
android version 5.1

**Comment by voidstarfire** [comment]
Someone needs to update the types for it. Typescript is saying this property doesn't exist for type LightBox haha.
