### ISSUE TITLE
How to access drawer?

### ISSUE THREAD

**Issue by dominicsavb** [wix/react-native-navigation#1302]
I want to disable drawer on some screen? how to do it?

How to change drawer from screen?

Thank you

**Comment by Fenwil** [comment]
Hi @dominicsavb you should try this on the screen you want to disable the drawer: [http://wix.github.io/react-native-navigation/#/screen-api?id=setdrawerenabledparams-android-only](http://wix.github.io/react-native-navigation/#/screen-api?id=setdrawerenabledparams-android-only)

**Comment by Fenwil** [comment]
@guyca you should close this one
