### ISSUE TITLE
Drawer selected events?

### ISSUE THREAD

**Issue by annelorraineuy** [wix/react-native-navigation#1303]
Just like with tabs https://wix.github.io/react-native-navigation/#/screen-api?id=listening-to-tab-selected-events is there a way to listen for **drawer selected items**? I'd like to set an active style to the drawer item currently on screen, and if active just close drawer instead of pushing the same screen.

---
### Environment
* React Native Navigation version: ^1.1.79
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?: Android
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by chmac** [comment]
Looks like not #1545.

**Comment by samw2k00** [comment]
Use redux and connect it to the drawer. keep state of the item selected in redux store 
check redux store for the selected item to style them differently
