### ISSUE TITLE
multiple click navigator.push show many screen at this time

### ISSUE THREAD

**Issue by diennguyentien** [wix/react-native-navigation#1304]
- I used onPress in TouchableOpacity, when I click multiple times at the same time on the list page, I get multiple show screens in detail page.

List page: http://prntscr.com/fdqv32
Detail page: http://prntscr.com/fdqwep

- My source code:

```
<TouchableOpacity onPress={this.pushScreen}>
```

```
pushScreen = () => {
        this.props.navigator.push({
            screen: 'example.Types.Push',
            title: 'New Screen',
        });
    };
```

---
### Environment
* React Native Navigation version: 1.1.80
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by jp928** [comment]
try onPress with bounce from lodash

**Comment by annelorraineuy** [comment]
@jp928 Do you mean `_debounce`? There's no bounce method from lodash. How did you do it?

**Comment by diennguyentien** [comment]
@jp928: thanks, I follow link as below:
https://github.com/wix/react-native-navigation/pull/256/commits/53fdbe6315850a9167f5f2f06f68998395292a5f
and did work

**Comment by berdof** [comment]
@diennguyentien can i provide an example how you use this in your code. As far as I understand you are using custom fork of this navigator with changed Screen.js logic.

**Comment by diennguyentien** [comment]
@berdof: I only modified Screen.js

**Comment by jp928** [comment]
@annelorraineuy 
In case anybody want to use debounce from lodash, just attached my solution:

```javascript

constructor(props) {
  super(props);
  this.onPress = this.onPress.bind(this);
}

onPress() {
  // your real logic
}

render() {
  return (
     <TouchableOpacity
      style={Styles.rightButton}
      onPress={debounce(this.onPress, 1000, {
        leading: true,
        trailing: false
      })}
    >
      {/* button inner view*/}
     </TouchableOpacity>
  );
}
 
```

Also, don't forget to add
``` javascript
import { debounce } from 'lodash';
```

in the beginning.

**Comment by diennguyentien** [comment]
@jp928 : thanks you

**Comment by ariona** [comment]
@jp928 thanks for this, I was using debounce from lodash but not properly called so there is waiting time when opening screen 😄 , Just notice the `leading` & `trail` options in your comment to fix the issue.

**Comment by sapjax** [comment]
`debounce` is not an ideal solution, cause the debounce delay time depends on the screen render 
if one screen renders very slowly,   1000ms is not enough,  and for the other screen, 1000ms is too long.

**Comment by nimamoradi** [comment]
it is a duplicate issue https://github.com/react-navigation/react-navigation/issues/271

**Comment by 1453009** [comment]
@sapjax is there any better solution?

**Comment by 1453009** [comment]
Can you give me more detail @sapjax , pseudo code would be fine

**Comment by 1453009** [comment]
@InternetExplorer8 is it the same? I see the push params are different

**Comment by nimamoradi** [comment]
still not solved in V2

**Comment by vivekshah-zymr** [comment]
> @annelorraineuy
> In case anybody want to use debounce from lodash, just attached my solution:
> 
> ```js
> constructor(props) {
>   super(props);
>   this.onPress = this.onPress.bind(this);
> }
> 
> onPress() {
>   // your real logic
> }
> 
> render() {
>   return (
>      <TouchableOpacity
>       style={Styles.rightButton}
>       onPress={debounce(this.onPress, 1000, {
>         leading: true,
>         trailing: false
>       })}
>     >
>       {/* button inner view*/}
>      </TouchableOpacity>
>   );
> }
>  
> ```
> 
> Also, don't forget to add
> 
> ```js
> import { debounce } from 'lodash';
> ```
> 
> in the beginning.

This worked for me.
