### ISSUE TITLE
Need RTL drawer support for localization

### ISSUE THREAD

**Issue by annelorraineuy** [wix/react-native-navigation#1307]
_EDIT: found the main issue so i'm renaming the title._

### Issue Description

On RTL, the drawer nav has issues. Test by switching device to a language like Arabic, Farsi, Hebrew or `I18nManager.forceRTL(true)`.

- drawer icon is correctly reversed in UI but drawer position on slide out is not. _(right-positioned drawer icon -> onClick -> slides out left drawer)_
- setting leftButtons and a right drawer crashes app on clicking drawer icon
- declaring both right drawer and rightButton on RTL, results in a left positioned icon with an unresponsive drawer icon

### Steps to Reproduce / Code Snippets / Screenshots

**SCENARIO 1**

App.js
```
import { I18nManager } from 'react-native';
I18nManager.forceRTL(true) // for testing RTL

...

drawer: {
    left: {  screen: 'drawerMenu'  }
}
```
Home.js
```
Icon.getImageSource('hamburger', 24, Colors.orange).then(drawerIcon => {
            props.navigator.setButtons({
                leftButtons: [
                    {
                        icon: drawerIcon,
                        id: 'sideMenu'
                    }]
            })
        })

```
**RESULT:**
![screenshot_ -](https://cloud.githubusercontent.com/assets/5892190/26611070/dfe63c5c-4568-11e7-8a01-334de35e2f96.png)
OnClick: brings up left drawer
OnSwipe: brings up left drawer

---
**SCENARIO 2**

App.js
```
import { I18nManager } from 'react-native';
I18nManager.forceRTL(true) // for testing RTL

...

drawer: {
    right: {  screen: 'drawerMenu'  }
}
```
Home.js
```
Icon.getImageSource('hamburger', 24, Colors.orange).then(drawerIcon => {
            props.navigator.setButtons({
                leftButtons: [
                    {
                        icon: drawerIcon,
                        id: 'sideMenu'
                    }]
            })
        })

```
**RESULT:**
OnClick: crashes app! ❌ 
OnSwipe: brings up right drawer 👍 

---
**SCENARIO 3**

App.js
```
import { I18nManager } from 'react-native';
I18nManager.forceRTL(true) // for testing RTL

...

drawer: {
    right: {  screen: 'drawerMenu'  }
}
```
Home.js
```
Icon.getImageSource('hamburger', 24, Colors.orange).then(drawerIcon => {
            props.navigator.setButtons({
                rightButtons: [
                    {
                        icon: drawerIcon,
                        id: 'sideMenu'
                    }]
            })
        })

```
**RESULT:**
![screenshot_ -](https://cloud.githubusercontent.com/assets/5892190/26611105/1bdd948a-4569-11e7-95f9-9871b97d89b2.png)
OnClick: no response / only touch feedback. no drawer, no crash
OnSwipe: brings up right drawer

---
### Environment
* React Native Navigation version: ^1.1.81
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device. Debug and Release.

**Comment by bitcrumb** [comment]
+1
