### ISSUE TITLE
IconSize of FAB Button 

### ISSUE THREAD

**Issue by kkroth** [wix/react-native-navigation#1309]
The icon size of the FAB Button is not compliant with the material design guide 

[FAB](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button)

I´m using vector icons for the FAB Button but i cant adjust the icon size the layout of the FAB scales the icon to this:

![image](https://cloud.githubusercontent.com/assets/18683097/26635905/6f281f22-461b-11e7-963f-896e59fa9b42.png)

The dimension of the FAB should be:
 Interior icon: 24 x 24dp
Floating action button circle: 56 x 56dp (this works)

---
### Environment
* React Native Navigation version: 1.1
* React Native version: 44.0
* Platform(s) (iOS, Android, or both?): Adnroid
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device , Debug and Release

**Comment by developer239** [comment]
+1

**Comment by Fuhrmann** [comment]
There it is a pull request to solve this issue.
