### ISSUE TITLE
ETA on 2.0?

### ISSUE THREAD

**Issue by jameskhamil** [wix/react-native-navigation#1310]
Hello

I've seen the [roadmap and other issues](https://github.com/wix/react-native-navigation/milestone/1), but there doesn't seem to be a clear timeline on when 2.0 will be usable. Is there any estimate?

I am trying to make some decisions, and it looks like all of the open issues say "This won't be done until 2.0", so this package is effectively crippled until then.

I converted my project to this and ran into many known limitations, so I will need to convert to another navigator for the project I'm working on. I looked in the 2.0 git branch, but it seems pretty incomplete and is without documentation as far as I can tell.

**Comment by smooJitter** [comment]
I here looking for the same, however I'm using version 1 with no problem.  I'm particularly interested in using TopTabs.  They don't seem to be a available in version 1, however,  if I switch to version 2 I loose some of the functionality of version 1. 

 It would be nice if the readme provided a simple status update for version 2. I've been with the package from the start so I'm  not looking to switch.  I am anxious to know how V2 will change my work flow.  Specifically I'm experimenting with using a HOC to compose my screens but I'm not sure if the. Screen component is exposed.

**Comment by Ehesp** [comment]
V2 is currently a working skeleton app, providing the most common routing features (push, pop, reset etc). It has features implemented such as BottomNavigation & Drawer. @DanielZlotin is best to give an ETA, but I'm not sure it's an easy answer.

@smooJitter topTabs are working in V1, check out the example app which implements them.
