### ISSUE TITLE
Nested navigators?

### ISSUE THREAD

**Issue by mareebsiddiqui** [wix/react-native-navigation#1316]
How do I use tabNavigator when im already using a singleScreen based app?

**Comment by oky1** [comment]
onPress={this.loadTabs}

loadTabs() {
    Navigation.startTabBasedApp({
      tabs: [
            {  screen: 'Screen1',    ...  }, 
            {  screen: 'Screen2', ....  } 
        ],
    });
}

**Comment by jaspal747** [comment]
@mareebsiddiqui I had a similar requirement. One of my screens needed a tabNavigation. The problem with using a new **Navigation.startTabBasedApp()** is that you will now be managing 2 navigators. The SingleScreenNavigator and the new TabBasedNavigator. The events of one navigator and separate from the other. So, when I had to switch back to the main SingleScreenNavigator from the TabBasedNavigator, I had to do a Navigation.startSingleScreenApp() again. 

This was not what I was looking for and I not an expert on how to make this happen but I ended up using https://github.com/skv-headless/react-native-scrollable-tab-view and maintaining my main SingleScreenNavigator as the only navigator.

Anyone with more experience on this, please point out if there is an ideal way to accomplish this. 

Thanks

**Comment by mareebsiddiqui** [comment]
This package looks good as far as they do not provide support for nested navigators, I think I'll use this one!

**Comment by amitbravo** [comment]
I have similar requirement, right now I am using react-native-router-flux , I suppose migrating on react-native-navigation can improve some performance 

my project is like there is one walkthrough screen if user loggedin, click on get started button from walkthrough to login page , user login , he jumps to tab view with drawer where he able to access all app areas. in react-native-router-flux i use kind of ... 

How can I use react-native-navigation maintaining similar app structure ?
Should I use v2 , does v2 having nested navigation system or without any nested system I can perform this using push ? I hope push does not compromise performance , 
should I go something like , creating a single screen app and later push tabscreen system into it ?

Below sudo code from react-native-router-flux to show app structure 

<Router>
              <Scene>
                    <Scene key="root" initial={!this.state.logged}>
                           <Scene key="walkthrough" component={Walkthrough} data={Data}   />
                          <Scene key="login" back component={OTPSignInFirebase} title="Login" />
                    </Scene>
                  <Drawer key="tabshome" contentComponent={TabView} initial={this.state.logged}>
                  <Tabs swipeEnabled={true} tabBarPosition="bottom" key="tabbar" gestureEnabled={false} showLabel={true} tabs tabBarStyle={styles.tabBarStyle} activeBackgroundColor="#ddd" >
                    <Scene key="tab1" component={DummyTab1} iconName="tags"         title="Tab #1" icon={TabIcon}   />
                    <Scene key="tab2" component={DummyTab2} iconName="newspaper-o"  title="Tab #2" icon={TabIcon}  />
                    <Scene key="tab3" component={DummyTab3} iconName="gear"         title="Tab #3" icon={TabIcon}  />
                    <Scene key="tab4" component={DummyTab4} iconName="gear"         title="Tab #4" icon={TabIcon} />
                  </Tabs>
                  </Drawer>
...
...
more scenes 



              </Scene>

           </Router>

**Comment by jaspal747** [comment]
@amitbravo 

If possible, you should look at using the v2 version (https://github.com/wix/react-native-navigation/tree/v2#react-native-navigation-v2-wip) as the current version is not actively maintained.

I am familiar with the version v1 and I will try to answer your question based on v1.
If you want to switch between a TabBasedApp(post login) and a SingleScreenApp(walkthrough etc), then you will have to do this in the main root container. 

You can refer this example and see how they start a SingleScreenApp post login.
https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js  
   case 'after-login':
