### ISSUE TITLE
Collapsing topTabs ?

### ISSUE THREAD

**Issue by rborn** [wix/react-native-navigation#1318]
### Issue Description
Hi, 
I'm trying to play with collapsing TopTabs on Android and I don't seem to make them work.

**example.Types.TopTabs** is an empty component and **example.Types.TopTabs.TabOne** contains a ScrollView of course. 

**navBarHideOnScroll** works as expected, but the topTabs don't (gif attached).

Am I doing something wrong (I tried any combinations of params in navigatorStyle)?

Thank you. 😺 

![rnct](https://cloud.githubusercontent.com/assets/406409/26721853/d2666210-478d-11e7-9c0c-9d5c0e355d71.gif)

### Steps to Reproduce / Code Snippets / Screenshots
~~~
Navigation.startSingleScreenApp({
    screen: {
        screen: 'example.Types.TopTabs',
        title: 'Top Tabs',
        navigatorStyle: {
            tabBarBackgroundColor: '#003a66',
            navBarButtonColor: '#ffffff',
            tabBarButtonColor: '#ffffff',
            navBarTextColor: '#ffffff',
            tabBarSelectedButtonColor: '#ff505c',
            navigationBarColor: '#003a66',
            navBarBackgroundColor: '#003a66',
            statusBarColor: '#002b4c',
            tabFontFamily: 'BioRhyme-Bold',
            drawUnderTabBar: true,
            topBarCollapseOnScroll: true,
            navBarHideOnScroll: true
        },
        topTabs: [
            {
                screenId: 'example.Types.TopTabs.TabOne',
                title: 'Tab One'
            },
            {
                screenId: 'example.Types.TopTabs.TabTwo',
                title: 'Tab Two'
            }
        ]
    }
});

~~~

---
### Environment
* React Native Navigation version: 1.1.85
* React Native version: 0.44.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): GenyMotion Android 7, Debug

**Comment by guyca** [comment]
Hey there
Actually, this is how they are supposed to work. when scrolling the Titlebar scrolls off screen and the TopTabs snap to the top of the screen. Is it common to hide the tabs as well?

**Comment by rborn** [comment]
No, I think you are right, it's not common I guess, but I was somehow confused by the 2 settings    `topBarCollapseOnScroll: true` and `navBarHideOnScroll: true`

What am I missing, what's the role of `topBarCollapseOnScroll`

Thank you 😊

**Comment by rborn** [comment]
Hi, I found this in the repo: https://github.com/wix/react-native-navigation/blob/3176aeb4485d5282f453f2f61066ff2730ea2407/src/deprecated/platformSpecificDeprecated.android.js#L143  should we consider `topBarCollapseOnScroll`deprecated then?

Thanks

**Comment by arikgilad** [comment]
I have a problem.
I am trying to add content into the upper part of the top tab but I fail.
I need to be able to add test, icons and button to the collpasible area above the toptabs.
Can it be done? How?
I was only able to show text using title=....

**Comment by guyca** [comment]
@arikgilad Not yet. We plan on adding support for a custom react view in the TopBar. No eta on that unfortunately

**Comment by arikgilad** [comment]
In the meanwhile, how can I set left/right button click handler?

**Comment by guyca** [comment]
@arikgilad [As usual](https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=adding-buttons-to-the-navigator) - `setOnNavigatorEvent`

**Comment by arikgilad** [comment]
Guy,

I found out a previous post of you:
https://github.com/wix/react-native-navigation/blob/2b182556c317b9f9352aa6b9044d0d6412b6a338/docs/android-specific-use-cases.md#collapsing-react-view-with-top-tabs

In that post you discussed: "Collapsing React header".

It seems to implement what I need.
I tried it out and it basically works but:
- collapsable tabs are not collpasing...
- It crashes often.

Any insight on that?

Arik

**Comment by CodeXtinction** [comment]
im trying to style topTaps
i cant change text color, or active color
i couldn't find the right properties  

this are not working

navBarTextColor: '#ffffff',
tabBarSelectedButtonColor: '#ff505c',

**Comment by Jonas-Arvidsson** [comment]
@CodeXtinction 
On the screen with the top tabs
```
 static navigatorStyle = {

   selectedTopTabIndicatorColor: "red",
   selectedTopTabTextColor: "green",
   topTabTextColor: "blue",

 };
```

**Comment by CodeXtinction** [comment]
@Jonas-Arvidsson  is not working for startSingleScreenApp :/

**Comment by AvijitDutta95** [comment]
How can i change topTab background color?

**Comment by hoorsa** [comment]
thanks @CodeXtinction .
how can i change topBar TextFontFamily or TextFontSize?

**Comment by misaku** [comment]
how can i do this in actualy version?
