### ISSUE TITLE
realm database types undefined

### ISSUE THREAD

**Issue by rubengarciam** [wix/react-native-navigation#132]
I've migrated my app from _NavigatorIOS_ to _react-native-navigation_. I was previously using [Realm as database](https://realm.io/products/react-native/). Unfortunately now all items returned from the query, like Dates or [list properties](https://realm.io/docs/react-native/latest/#list-properties) type, seem undefined.

**Example for the Realm Date type:**

Declaration:

```
const ComicSchema = {
  name: 'Comic',
  properties: {
   ...
    published: {type: 'date', optional: true},
   ...
  }
};
```
Use returning _undefined_:

> comic.published.toDateString();

Workaround that is valid: mapping it to a JS Date type:

> var published = new Date(comic.published);
published.toDateString();

Which is ok for simple types but unusable for list properties types ( which now cannot be iterated them using a simple _map_).

Has anyone faced a similar issue?

**Comment by rubengarciam** [comment]
Found the issue. All props are need to be serializable unf :(

**Comment by guyca** [comment]
@rubengarciam We plan to remove this requirement in one of the upcoming releases.
