### ISSUE TITLE
[Request] Support multiple native viewpagers

### ISSUE THREAD

**Issue by dzunglht** [wix/react-native-navigation#1322]
Dear folks
Please help support this ticket
https://github.com/wix/react-native-navigation/issues/1008
Thanks

**Comment by guyca** [comment]
Hey @dzunglht 
The next version is developed with support for these types of features in mind.

**Comment by dzunglht** [comment]
@guyca We still need the requested feature, i think that you the library author should have a detail development plan for the feature, currently UX performance for multiple view pagers is not good
Ref:
Demo: [Multiple viewpagers](https://www.youtube.com/watch?v=oyLhVvu5p6s&feature=youtu.be)

**Comment by meow0703** [comment]
Hello guys,
When will we have this feature in your next release ?
Thanks

**Comment by guyca** [comment]
Next release will support multiple `TopTabs`

```js
Navigation.push(this.props.containerId, {
      topTabs: [
        {
          topTabs: [
            {
              name: 'navigation.playground.TextScreen',
              options: {
                topBar: {
                  title: '_Tab 1'
                }
              }
            },
            {
              name: 'navigation.playground.TextScreen',
              options: {
                topBar: {
                  title: '_Tab 2'
                }
              }
            }
          ],
          options: {
            topBar: {
              title: 'Tab 1'
            }
          }
        },
        {
          name: 'navigation.playground.SomeOtherScreen',
          options: {
            topBar: {
              title: 'Tab 2'
            }
          }
        }
      ]
    });
```

This will push a screen with two top tabs, where the first top tab has two top tabs
