### ISSUE TITLE
Is v2 backward compatible?

### ISSUE THREAD

**Issue by idibidiart** [wix/react-native-navigation#1325]
Just thinking of using this library in my RN projects.

I've noticed you're working on v2. Is it going to be fully backward compatible with v1?

**Comment by charlesluo2014** [comment]
no,Navigation api,and register api,is not same as v1!

**Comment by idibidiart** [comment]
In that case, is v2 usable yet (for prototyping on brand nee projecf) so I wouldn't have to migrate later?

**Comment by Ehesp** [comment]
@idibidiart it's a basic skeleton at the moment. You can switch to the v2 branch and start the playground app to see whats implemented.
