### ISSUE TITLE
Should I pass the navigator object to child component via props?

### ISSUE THREAD

**Issue by sungjk** [wix/react-native-navigation#1329]
### Issue Description
I tried to use navigator.resetTo() in child component, I got the error: `this.props.navigator is undefined`

Should I pass the navigator object to child component via props like below codes?
Is there a way to globally access navigator object?

---

### Steps to Reproduce / Code Snippets / Screenshots

Root.js
```javascript
...
renderScrollableTabView() {
	return (
		<ScrollableTabView
			...
			>
			...
			<SpaceScreen
				tabLabel={require('../../assets/drawable-xxxhdpi/menu_02_on.png')}
				navigator={this.props.navigator}
			/>
			...
		</ScrollableTabView>
	)
}
```

SpaceScreen.js
```javascript
...
renderSpaceList() {
	return this.props.mySpaces.map((space, i) => {
		return (
			<Space
				...
				navigator={this.props.navigator}
				...
			/>
		)
	})
}
```

Space.js
```javascript
...
constructor(props) {
	super(props)
}

return (
	<TouchableOpacity onPress={event => {
		console.log(this.props.navigator)
	}}>
	...
	</TouchableOpacity>
)
```

---
### Environment
* React Native Navigation version: 1.1.79
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
You can either pass the navigator to child component or pass them a callback in which you interact with the navigator 👍
