### ISSUE TITLE
Cannot find RCCManager.h.

### ISSUE THREAD

**Issue by beebase** [wix/react-native-navigation#133]
I updated node v2 to v3.10.5 but I'm still getting this error.
Anyone else?

**Comment by explorigin** [comment]
Did you delete your node_modules and run `npm install` again?

**Comment by beast** [comment]
@beebase I think your best bet is to make sure react-native-controller is in your node_modules folder and also your iOS project > build settings > header search paths > make you sure you have an entry '$(SRCROOT)/../node_modules/react-native-controllers/ios' and its set to recursive.

**Comment by gazpachu** [comment]
I'm having a similar issue

![screen shot 2016-08-03 at 15 31 52](https://cloud.githubusercontent.com/assets/1721288/17369239/6df2a42a-598f-11e6-94e7-8a7ddd8a2fe8.png)

**Comment by guyca** [comment]
@gazpachu Screens are still registered. But you don't need to define a "main" screen anymore.
Instead, your app is created when your static JS code is executed and `Navigation.start*App` is called.

You can follow example-redux project to setup your first project.

**Comment by mithunm93** [comment]
@beebase if you're trying to run the example code, make sure you run `npm install` from within the example folder.

**Comment by juliansharifi** [comment]
Had this issue because my Debug header search path was empty and needed to be $(SRCROOT)/../node_modules/react-native-navigation/ios

**Comment by lin-hun** [comment]
I get the same issue that define the search path in xcode.
cocopods can solve the dependence,can u make it(podspec)?

**Comment by tspecht** [comment]
Has anyone been able to fix this? Running into the same issue right now ...

**Comment by AswinKV** [comment]
I had to use "$(SRCROOT)/../../node_modules/react-native-navigation/ios" as debug search path instaed of "$(SRCROOT)/../node_modules/react-native-navigation/ios"

**Comment by lefoy** [comment]
For future reference (found this issue via Google):

I solved this issue by using `#import "../../node_modules/react-native-navigation/ios/RCCManager.h"` instead of `#import "RCCManager.h"` in `AppDelegate.m`

**Comment by pqkluan** [comment]
Fixed by @lefoy
