### ISSUE TITLE
willAppear / didAppear navigation events not firing when closing modals in android

### ISSUE THREAD

**Issue by eeynard** [wix/react-native-navigation#1330]
### Issue Description

Hi !

In android, when you dismiss a modal, navigation events of previous screen/modal aren't fired.

Can you help me ?

### Steps to Reproduce / Code Snippets / Screenshots

Show a modal in your home screen and dismiss it, you won't see the **willAppear** and **didAppear** events of your home screen.

---
### Environment
* React Native Navigation version: 1.1.81
* React Native version: 0.44.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android 7.1.1

**Comment by asessa** [comment]
I have the same problem but only with soft/hard buttons. 
Probably related to #1238

**Comment by yusufyildirim** [comment]
As I tested, this problem is solved on Android side. But we have same issue on the iOS side, i'll investigate that
