### ISSUE TITLE
drawers's 'onNavigatorEvent' not called when call 'handleDeepLink' 

### ISSUE THREAD

**Issue by doandu** [wix/react-native-navigation#1335]
### Issue Description
My app have 1  main screen and 2 drawers on the left and right, when I call **this.props.navigator.handleDeepLink** on main screen, just one drawer's **onNavigatorEvent** get called, in my case is right drawer. When I tried to remove the left drawer, the right drawer's one get called.

Both left and right screen registered event handler in **construtor**:
`this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));`
* Beside note: in the 'react-native-navigation/src/Screen.js', **setOnNavigatorEvent** function, **this.navigatorEventID** got 'undefined' value in both drawers's register event call above.
### Steps to Reproduce / Code Snippets / Screenshots
Here is my code to start app:

```
Navigation.startSingleScreenApp({
     screen: {
       screen: 'MainScreen',
       title: 'Main'
     },
     drawer: {
       left: {
         screen: 'LeftScreen'
       },
       right: {
         screen: 'RightScreen'
       }
     }
  });
```

---
### Environment
* React Native Navigation version: ^1.1.80
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): iOS (not test on Android yet)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iOS 10.3 Debug

**Comment by tujoworker** [comment]
+1

**Comment by rhenann** [comment]
+1 Same problem here. Not working on android.

**Comment by peteroid** [comment]
Got the same issue without calling the `handleDeepLink`. Are you guys get the `this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));` working in the drawer itself?
