### ISSUE TITLE
How to disable showLightBox animation

### ISSUE THREAD

**Issue by dzunglht** [wix/react-native-navigation#1336]
Hi guys,
Please let us know how to disable showLightBox animation ?
Many thanks

**Comment by dzunglht** [comment]
Please support this ticket guys
Thanks

**Comment by alexwasner** [comment]
Any update on this?

**Comment by nbomberger** [comment]
I have a working PR for iOS here that turns off animation [[iOS] Added way to turn off moving lightbox animation #1](https://github.com/najabu/react-native-navigation/pull/1)   Perhaps someone could roll the one for Android or I can do when I have time.
