### ISSUE TITLE
[Question] How to disable initial animation

### ISSUE THREAD

**Issue by DavidKuennen** [wix/react-native-navigation#1338]
Hey there,

my goal is to disable the initial animation (slide in from the bottom). 

I'm currently checking for AuthState when my app launches and then start either a Tab or SingleScreen app. I tried using all these properties but none of them seem to work consistently: 

```javascript 
Navigation.startSingleScreenApp({
    screen: {
        screen: "App.WelcomeScreen",
        title: ''
    },
    animated: false,
    animationType: 'none',
    animateShow: false
});
```

Current Version: 1.1.85
OS: Android (didn't test iOS so far)

**Comment by dccarmo** [comment]
Same thing happening here, did you find a solution?

**Comment by DavidKuennen** [comment]
@dccarmo Yeah, I found a solution.
I modified my AppTheme like this: 

```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:windowAnimationStyle">@null</item>
</style>
```
