### ISSUE TITLE
Suggestion: Make it so that any screen can return a result to the one that called it after being unmounted.

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#1339]
Hey there..

Currently I'm not aware of any way for a screen to return a value once it's finished processing etc.

Because of that we have to improvise complex mechanisms to manage all that through our state, when it would have been so much more practical to have a screen being able to return a result object to the parent that initiated it, pretty much the way it works with Android Activities.

What do you think?

**Comment by guyca** [comment]
@SudoPlz Interesting topic. This is pretty much the same concept as `onActivityResult` which can be implemented by passing a callback to a screen (when the next screen is pushed) and calling it in `componentWillUnmount`.

**Comment by SudoPlz** [comment]
Good idea @guyca, I'll do that for now.
