### ISSUE TITLE
the first click is ignored

### ISSUE THREAD

**Issue by eastwood20** [wix/react-native-navigation#1340]
I found that sometimes the first click not get response, but second one is OK.

How to reproduce:
1.using ListView in r-n-navigation,  and put some rows in it
2.slide the list, and move out your finger
3.when stop moving, tap any row in the list
4.the first tap will not get any response

if not using r-n-navigation, it works well.

here is codes of listview:

```
renderRow (rowData, sectionId, rowId) {
 <TouchableWithoutFeedback onPress={() => {
  //be Clicked
})}>
  <View style={styles.root}>
    <Image style={styles.img} source={defaultAvatar} />
    <View style={styles.detail}>
      <Text allowFontScaling={false} numberOfLines={1} style={styles.name}>{nickName}</Text>
    </View>
  </View>
</TouchableWithoutFeedback>
}

render () {
return
    <ListView
      style={[{padding: 10, backgroundColor: grayBgColor, width: screenWidth}, this.props.style]}
      dataSource={this.state.ds}
      renderRow={this.renderRow.bind(this)}
      renderSectionHeader={this.renderSectionHeader}
      renderHeader={this.renderHeader}
    />
}
```

**Comment by grin** [comment]
Did you try it with `FlatList` instead of the `ListView`? (ListView is going to be deprecated in RN)
