### ISSUE TITLE
navigator.toggleDrawer causing crash on Android

### ISSUE THREAD

**Issue by raphaeltm** [wix/react-native-navigation#1343]
### Issue Description

I have a button that calls `this.props.navigator.toggleDrawer()` on press. It works perfectly on iOS, but on Android it produces the following:

```
Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
fromString
    SideMenu.java:27
toggleSideMenuVisible
    NavigationReactModule.java:146
invoke
    Method.java
invoke
    BaseJavaModule.java:368
invoke
    JavaModuleWrapper.java:138
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:208
run
    Thread.java:761
```

As far as steps, it's not very complicated. This happens in one of the screen components, and it's as simple as the following:

```
<Button onPress={e=>this.props.navigator.toggleDrawer()} title={"Toggle"} />
```

It works fine in the iOS simulator, running iOS 10.3.

On a physical LG-G5 running android 7.0, it fails.

---
### Environment
* React Native Navigation version: 1.1.86
* React Native version: 0.44.2
* Platform(s) (iOS, Android, or both?): Succeeds on iOS 10.3, fails on Android 7.0
* Device info (Simulator/Device? OS version? Debug/Release?): Succeeds on iOS 10.3 Debug. Fails on Android 7.0 on LG-G5, in debug.

**Comment by raphaeltm** [comment]
And immediately after posting, I figured out what was wrong.

On iOS calling toggleDrawer seems to work without passing any params. On Android, it seems that not passing the options object causes it to fail. It works now with:

```
<Button onPress={e=>this.props.navigator.toggleDrawer({side: "left"})} title={"Toggle"} />
```

**Comment by cinder92** [comment]
@raphaeItm this is not working with react native v 0.48.1
