### ISSUE TITLE
White background color navigation bar with gesture back

### ISSUE THREAD

**Issue by MrVisitor** [wix/react-native-navigation#1348]
Parent screen has params:
static navigatorStyle = {
    navBarHidden: true,
    navBarTransparent: true,
    drawUnderNavBar: true,
    navBarNoBorder: true,
    navBarButtonColor: '#FFC700'
};
The "navBarHidden", because used custom NabBar with tabs.

Children screen has params (next screen):
static navigatorStyle = {
    navBarNoBorder: true,
    navBarTransparent: true,
    drawUnderNavBar: true,
    navBarTranslucent: true,
    navBarTextColor: '#FFF'
};

When call back gesture, the navigation bar from children screen become white. 

![ika92t69yrm](https://user-images.githubusercontent.com/7935653/27014911-bc02725a-4f0a-11e7-8234-92d67bca3a7d.jpg)
![zd1a6kjv3ua](https://user-images.githubusercontent.com/7935653/27014912-bc2c6556-4f0a-11e7-9d5a-cd6e0c5b5345.jpg)

When a new screen is pushed to navigation, I can see how the white background becomes transparent.

### Environment
* React Native Navigation version: 1.1.93
* React Native version: 0.43.4
* Platform: iOS
* Device info: Simulator and Device ^8.0 iOS

**Comment by MrVisitor** [comment]
I found a solution, need to add a parameter to the parent screen:
"navBarTranslucent: true"

**Comment by henrikra** [comment]
@MrVisitor Actuall parent screen has to match parameters of the child screen. So for example the screen you are coming back from has params:
```js
{
  navBarTransparent: true,
  drawUnderNavBar: true,
  navBarTranslucent: true,
};
```

Then parent screen has to have those same params :)
