### ISSUE TITLE
CustomNavBar for android

### ISSUE THREAD

**Issue by diennguyentien** [wix/react-native-navigation#1349]
I used CustomNavBar for IOS it's work but for android, this is wrong, how can add it into android
This is my source code:
```
static navigatorStyle = {
    drawUnderTabBar: true,
    navBarCustomView: 'example.CustomNavBar',
    navBarCustomViewInitialProps: {name: 'Hi, guys!'}
  };
```
---
### Environment
* React Native Navigation version: 1.1.80
* React Native version: 0.44.3
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by laznrbfe** [comment]
I think you can use 'collapsingToolBarComponent' instead of 'navBarCustomView' for Android.
You can see [Collapsing React header](https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=collapsing-react-header).

**Comment by diennguyentien** [comment]
@laznrbfe: thanks you, i already try it, but how can disable collapsing?
