### ISSUE TITLE
Provide an option to set drawUnderTabBar to true when toggling tabs

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#1351]
### Issue Description
I have an iOS tab based app. When a user initiates a search on a screen, I want to hide the tab bar so that user can have more space to see the search result and he can also not navigate to some other screen while he is in the search. Currently, when I make a call to hide tabs,

```javascript
this.props.navigator.toggleTabs({
      to: 'hidden',
      animated: true
    });
```

There is no way to set the `drawUnderTabBar` to `true` such that the tab area is used for rendering stuff. I can't just set the `drawUnderTabBar` as default because then the user can't see a  part of the screen when the tab bar is visible.

### Steps to Reproduce / Code Snippets / Screenshots

1. Create a tab based app
2. Hide the tab bar as part of a user action
3. Observe that even though the tab bar is hidden, the area used by the tab bar is not used the app screen.

Actual
![screen shot 2017-06-12 at 11 29 46 am](https://user-images.githubusercontent.com/7475133/27021102-d45e32cc-4f63-11e7-9d30-ca193051c269.png)

Expected
![screen shot 2017-06-12 at 11 29 22 am](https://user-images.githubusercontent.com/7475133/27021114-e3bf8efa-4f63-11e7-948f-51024e6c55fe.png)

If I just enable the `drawUnderTabBar` property to true, then a part of the screen is just hidden behind the tab bar which is not expected.

---
### Environment
* React Native Navigation version: 1.1.79
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by kuma-guy** [comment]
+1

**Comment by Soraph** [comment]
Setting `drawUnderTabBar` to `true` and then toggling will still not free the space, it will just show as it was set to `false`.

**Comment by jneuendorf** [comment]
@Soraph I assume you meant `tabBarBackgroundColor` instead of `tabBackGroundColor`? Still your workaround doesn't work for me 😢 Did you customize `tabsStyle` or use the default (and do everything on the screen level with `static navigatorStyle`)?

**Comment by Soraph** [comment]
I'm sorry but I no longer remember nor I have access to that code to answer you :(
