### ISSUE TITLE
this.props.navigator is undefined

### ISSUE THREAD

**Issue by douglasjunior** [wix/react-native-navigation#1355]
### Issue Description

I know it may seem like a basic question, but I spent hours reading the documentation and issues, and did not find the solution to this problem.

When I open a new screen using `this.props.navigator.push`, I can not access the `this.props.navigator` on this new screen.

I have 3 screens: `Home` , `Drawer` and `Clinica`. `Home` is the main screen and `Clinica` is pushed by `Home`. In `Home` and `Drawer` the `this.props.navigator` works fine, but in `Clinica` is undefined.

![image](https://user-images.githubusercontent.com/1512341/27063973-21c75cac-4fcb-11e7-8424-f843dbb0de2e.png)

### Steps to Reproduce / Code Snippets / Screenshots

My start config:
```javascript
    Navigation.registerComponent('Home', () => Home);
    Navigation.registerComponent('Drawer', () => Drawer);
    Navigation.registerComponent('Clinica', () => Clinica);

    Navigation.startSingleScreenApp({
        screen: {
            screen: 'Home', // unique ID registered with Navigation.registerScreen
            title: Strings.appName, // title of the screen as appears in the nav bar (optional)
            navigatorStyle: {}, // override the navigator style for the screen, see "Styling the navigator" below (optional)
            navigatorButtons: {} // override the nav buttons for the screen, see "Adding buttons to the navigator" below (optional)
        },
        drawer: { // optional, add this if you want a side menu drawer in your app
            left: { // optional, define if you want a drawer from the left
                screen: 'Drawer', // unique ID registered with Navigation.registerScreen
                passProps: {}, // simple serializable object that will pass as props to all top screens (optional)
            },
            disableOpenGesture: false // optional, can the drawer be opened with a swipe instead of button
        },
        passProps: {}, // simple serializable object that will pass as props to all top screens (optional)
        animationType: 'fade' // optional, add transition animation to root change: 'none', 'slide-down', 'fade'
    });
```

My `Home` render:
```javascript
    render() {
        const { push } = this.props.navigator;

        return (
            <View>
                <Button
                    onPress={() => push({ screen: "Clinica", title: "Clínica" })}
                    title="Navegar para Clínica"
                />
            </View>
        )
    }
```

My `Clinica` render:
```javascript
    render() {
        console.log(this.props.navigator) // is undefined 
        
        return (
            <View>
                <Text>Detalhes da clínica: </Text>
                <Button
                    onPress={() => null}
                    title="Back"
                />
            </View>
        )
    }
```

---
### Environment
* React Native Navigation version: "^1.1.95"
* React Native version: "0.45.1"
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Moto X2 Android 6.0 API 23 and Emulator API 24

**Comment by Jaafar-abusair** [comment]
Hi,

Can you try passing the provider, 

  Navigation.registerComponent('Clinica', () => Clinica, store, Provider);

**Comment by Jaafar-abusair** [comment]
as workaround, you can pass it in the props for now. when you do push.

**Comment by douglasjunior** [comment]
Maybe it works, I have not tried yet. Now I'm using [react-navigation](https://github.com/react-community/react-navigation). Thank you.

**Comment by GorshkovNikita** [comment]
I ran into the same problem. To make it work you should change your render method in `Home` to:

```
render() {
        return (
            <View>
                <Button
                    onPress={() => this.props.navigator.push({ screen: "Clinica", title: "Clínica" })}
                    title="Navegar para Clínica"
                />
            </View>
        )
    }
```

**Comment by V3RT1AG0** [comment]
@GorshkovNikita  Thanks a lot. I almost spent a whole day figuring out what the issue was. Any idea why this happens though. Is it not the same thing ?

**Comment by Jaafar-abusair** [comment]
@V3RT1AG0 If your code get invoke from a called back method, so probably you will face this, you need to bind the current object by .bind(this), when you call your method
