### ISSUE TITLE
toggleTabs to 'shown' places BottomTabs at top of screen

### ISSUE THREAD

**Issue by jstheoriginal** [wix/react-native-navigation#1357]
### Issue Description

Calling 

```
this.props.navigator.toggleTabs({
    to: 'shown',
    animated: false,
});
```

after previously hiding the `BottomTabs` causes the `BottomTabs` bar to appear at the top of the screen instead of bottom.

### Steps to Reproduce / Code Snippets / Screenshots

This was not an issue using `v1.1.89`, but it is an issue using `v1.1.96`.

Steps:

1. In `componentWillMount`, add Keyboard event listeners for `keyboardDidShow` and `keyboardDidHide`.
1. When `keyboardDidShow` event occurs, `toggleTabs` to `hidden`.
1. When `keyboardDidHide` event occurs, `toggleTabs` to `shown`.

Note that the `BottomTabs` is at the top of the screen instead of where it should be on the bottom, as it was before hiding.

---
### Environment
* React Native Navigation version: v1.1.96
* React Native version: 0.45
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Google Nexus 6, 5.0.0 API 21

**Comment by guyca** [comment]
Hey,
I'm not able to reproduce this in the example app (although I didn't try with a keyboard event listener, I simply tried toggling tabs)
The example app has an `action` screen (second tab) with a `toggleTab` action - can you reproduce it there? perhaps add a text input and relevant boiler plate code and post the screen here. cheers

**Comment by jstheoriginal** [comment]
Sounds good I'll give it a go later today.

**Comment by jstheoriginal** [comment]
@guyca Just trying to run the example app in this repo to configure it like we have it to reproduce, but at launch on Android I get this:

```
E/ReactNativeJS( 2538): Something went wrong initializing the native ReactLocalization module.
E/ReactNativeJS( 2538): Please check your configuration.
E/ReactNativeJS( 2538): Did you run 'react-native link'?

E/ReactNativeJS( 2538): undefined is not an object (evaluating 'localization.language')
```

And running `react-native link` says `rnpm-install info Android module react-native-navigation is already linked`

I cloned, ran `yarn`, ran `react-native link`. Is there another step to get the example app to run?

Thanks!

**Comment by guyca** [comment]
1. clone rnn
2. cd examaple
3. yarn
4. react-native run-android (Or better yet, run from Android Studio)

no need to link, everything is already configured.

**Comment by jstheoriginal** [comment]
Ok I gave this another go today. I was doing it as outlined above, but still get that error.

I decided to try running it on iOS via Xcode and I get the same error, so something must be missing now. I can quickly see the example splash screen and then it shows this error which is the same as what I see on Android running the example:

![simulator screen shot jun 20 2017 5 17 27 pm](https://user-images.githubusercontent.com/5117473/27358498-930517ee-55dc-11e7-978e-46d96015e534.png)

**Comment by guyca** [comment]
¯\_(ツ)_/¯

**Comment by jstheoriginal** [comment]
ok I did a full clean of all of my react native stuff and it worked. 🙄 

Checkout my branch: https://github.com/jstheoriginal/react-native-navigation/tree/broken-tab-bar-example

Run it on Android with software keyboard enabled.

I replaced the first tab with the example. Tap in the text input field, then dismiss keyboard. Tab bar is at the top of the screen instead of the bottom.
