### ISSUE TITLE
[Question] Integrate with third party splash screen library

### ISSUE THREAD

**Issue by jp928** [wix/react-native-navigation#1358]
### Steps to Reproduce / Code Snippets / Screenshots
what I did to achieve a image splash screen was:
```java
  public class MainActivity extends SplashActivity {

    @Override
    public LinearLayout createSplashLayout() {
       LinearLayout view = new LinearLayout(this);
       view.setBackgroundResource(R.drawable.splash);
       view.setGravity(Gravity.CENTER);
        return view;
    }
```
However, I could not eliminate the unwilling blank screen either in the beginning of the app load and after dismiss the splash screen.
So, I found something like this: https://github.com/crazycodeboy/react-native-splash-screen
From the demo gif, it looks like smooth and can be controlled from js which means I could dismiss the splash after entire Javascript loaded.
But from the installation instruction I found this library requests to do something like:
```java
import com.cboy.rn.splashscreen.SplashScreenReactPackage;
public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        protected boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
            new SplashScreenReactPackage()  //here
            );
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }
}
```
Which obviously not compatible with RNN. 
I would appreciate if anyone could help me on this.
Thanks in advance.
---
### Environment
* React Native Navigation version: 1.1.93
* React Native version: 0.44.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by basudz365** [comment]
@jp928 

I've used this splash screen before and really like it a lot.  I have been trying to integrate it into an app that uses React Native Navigation as well.  I've been able to make it work in Android but it's not really ideal given the way RNN destroys the MainActivity and starts its own.

Rather than calling SplashScreen.show(this); in MainActivity you can setup activity lifecycle callbacks in MainApplication and call it in the onActivityCreated method.  When starting up the app you get an initial white screen (or what ever layout you set that is supposed to be the splash screen for RNN), and then the SplashScreen from this library appears and runs as expected.
Here's my MainApplication (I did not add any code to MainActivity)

```
public class MainApplication extends NavigationApplication {

  @Override
  public void onCreate() {
    super.onCreate();
    registerActivityLifecycleCallbacks(new ActivityLifecycleCallbacks() {
      @Override
      public void onActivityCreated(Activity activity, Bundle savedInstanceState) {
        if (activity instanceof NavigationActivity) {
          SplashScreen.show(activity);
        }
      }

      @Override
      public void onActivityStarted(Activity activity) {

      }

      @Override
      public void onActivityResumed(Activity activity) {

      }

      @Override
      public void onActivityPaused(Activity activity) {

      }

      @Override
      public void onActivityStopped(Activity activity) {

      }

      @Override
      public void onActivitySaveInstanceState(Activity activity, Bundle outState) {

      }

      @Override
      public void onActivityDestroyed(Activity activity) {

      }
    });
  }

  @Override
  public boolean isDebug() {
    // Make sure you are using BuildConfig from your own application
    return BuildConfig.DEBUG;
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }

  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
            new VectorIconsPackage(),
            new SplashScreenReactPackage()
    );
  }
```

Note that I check for NavigationActivity.  You could remove this check and then you will see the SplashScreen twice, one for each activity created (MainActivity & NavigationActivity).

**Comment by basudz365** [comment]
I don't know if this would work the same way in IOS as I'm not very familiar with it, but it would be nice to have RNN's native splash screen be able to last longer than just the JS context load.  In my particular app, I need to run some checks, load up some state, then validate certain conditions and determine which screen to start the user at.  

I need to be able to have a splash screen that continues displaying after the JS context has loaded and only be hidden when I'm ready to let the user into the app.

**Comment by jp928** [comment]
@basude365
 do you mind to advise a little bit more about how did u dismiss the splash? from Java world or javascript world?

**Comment by basudz365** [comment]
@jp928 
Other than what I posted above, the rest of the usage according to the docs is the same.

In my Javascript after I've loaded everything that I need to, I just call SplashScreen.hide();
Of course you need the import as well
import SplashScreen from 'react-native-splash-screen';

**Comment by raynor85** [comment]
@basudz365
I have exactly the same necessity, RRN with react-native-splash-screen. Can you please rewrite your code inclusive of all the imports? I have tried to make it work but I'm getting some errors. Can you also be more specific on why the solution is not ideal? Thank you
