### ISSUE TITLE
How to apply gradient color on nagivation bar

### ISSUE THREAD

**Issue by abser** [wix/react-native-navigation#1359]
Hi,
Is there a way to implement linear gradient color for navigation bar and screen background?
I found a related thread on this link https://github.com/wix/react-native-navigation/pull/861 .

So could we use something like below
{
  navigatorStyle: {
    navBarBackgroundColorGradient: [#startColor, #endColor]
    screenBackgroundColorGradient: [#startColor, #endColor]
  }
}

**Comment by guyca** [comment]
Hey, render your own navigation bar in jsx 👍

**Comment by abser** [comment]
@guyca ,
We can create another Bar in JSX inside the render method. My question is how it will be connected to react-native-navigation? Any quick example in your mind? Can we use react-native-linear-gradient together with react-native-navigation?
Appreciate your thought on it.

**Comment by guyca** [comment]
You can use [navBarHidden: true](https://wix.github.io/react-native-navigation/#/styling-the-navigator?id=style-object-format) and `drawUnderNavBar: true`. Then simply render your navBar in JSX.
The way we see it, the navBar provided by rnn is a convenience for your simple use cases, if you have a more complex use case (such as a gradient or a search bar) you should render your own navBar.

**Comment by ahmedraza11** [comment]
how can I render my custom navbar ?
