### ISSUE TITLE
Search Field in Navigation Bar - iOS Support, Documentation

### ISSUE THREAD

**Issue by Jpoliachik** [wix/react-native-navigation#1361]
I noticed there is Android support for a search view as a Navigation Button, expanding to a text field on selection. 
(Found via Pull #432)

It needs an iOS implementation, as well as documentation on how to implement. 

From my own experimentation, it appears the only necessary action is to set the Navigation Button id to `searchView`, and it requires an icon - title doesn't work. EG - 
```
static navigatorButtons = {
    rightButtons: [
      {
        icon: require("../../assets/searchIcon.png"),
        id: 'searchView',
      }
    ]
  }
```

And then search events are emitted as Navigator events, EG - 
```
this.props.navigator.setOnNavigatorEvent(event => {
      if (event.id === "searchQueryChange") {
        console.log("search query: " + event.query);
      }
    });
```

I'm going to work on an iOS equivalent to match

**Comment by guyca** [comment]
Hey Justin,
This commit was added a while ago in a hackathon we did here at Wix. I don't think we should implement the same functionality on iOS. Instead, I think a better approach is to use a custom view in navBar (Or implement the navBar entirely in JSX).

custom view in navBar has been implemented on iOS for some time now, but I never seem to get around to implement it on Android. We already support showing `ReactRootView` in navBar on Android, but only in `CollapsingTopBar` use cases. wdyt?

**Comment by Jpoliachik** [comment]
Gotcha.

Custom View in Nav Bar makes sense for this - sorry I wasn't fully aware it existed! 

I'll use iOS Custom Nav View alongside hackathon-built Android Search View for now, until Android Custom Nav View support arrives. 😄 

Side note - what is your strategy for maintaining documentation? It's hard to get an overview of all available features since it seems like the [documentation](https://wix.github.io/react-native-navigation) site is missing lots of features that currently exist in /master. Let me know if you would like some help adding more documentation - or are you waiting for v2 to revamp docs?

**Comment by guyca** [comment]
The documentation site is relatively new, so a few things are missing - what ever you find is missing, feel free to add!

**Comment by nitish24p** [comment]
@guyca any link to the documentation of the android implementation of the search view in the nav bar.

**Comment by guyca** [comment]
@nitish24p The search view feature is deprecated. You can add a react view to TopBar and add a search view in jsx. See the example app (actions tab) for a CustomTopBar example

**Comment by ldipasquale** [comment]
Hi @guyca! Why did you deprecate the search view feature?

**Comment by guyca** [comment]
Hey @ldipasquale 
As it was developed in a hackathon we held a while back and was never finished - it was pretty much deprecated from the get go.
You can add a react view to the TopBar with your search view, the example app has a custom topBar screen you can use to help you get started.

**Comment by ldipasquale** [comment]
Thanks you @guyca: but, the custom TopBar component is only to custom the title bar, right? How it can handle the right buttons (to implement the search feature) too?

Did you find critical errors in the native search view feature on Android?

**Comment by guyca** [comment]
As I said, it was developed over night in a hackathon. I'm not aware of any errors because after that hackathon - no one here at Wix has used it.

You can add a react view which will fit the available space in the navBar using `  navBarComponentAlignment: 'fill'` - Just add a search button in jsx and a text input (Or a more complex solution)

**Comment by sijad** [comment]
@guyca can you explain it more please?
it doesn't seems doable via `navBarCustomView`, because `navBarCustomViewInitialProps` should be `Serializable JSON` so it is not possible to communicate via passed props with `navBarCustomView` component. not sure if redux can be used here but it'll make it way more complicated.

**Comment by sijad** [comment]
wish at least DeepLink could be used here, but `this.props.navigator` is `undefined`

**Comment by srameshr** [comment]
@sijad Exactly. Did you figure this out? Any jsx code of how are you rendering a search component in the header?

**Comment by guyca** [comment]
@sijad You can broadcast deeplinks from `Navigation`, you don't need a navigator object for that.

**Comment by witalobenicio** [comment]
@guyca can you provide an example of using deeplinks to work with a custom view in the navbar? I'm trying to call a method from the customview, but it's not working

**Comment by linasmnew** [comment]
I ended up using redux since it's already part of my application, simply connected the CustomTopBar component to redux and changed `onChangeText` to `onChangeText={this.props.updateSearchQuery}`, and then also connected the SearchResults component to read the input of the search query via `mapStateToProps`.
