### ISSUE TITLE
Navbar title font size

### ISSUE THREAD

**Issue by adiki** [wix/react-native-navigation#1363]
Could you please add support for changing navbar title font size?

**Comment by guyca** [comment]
Hey @adiki 
Seems like [fontSize](https://github.com/wix/react-native-navigation/blob/cc94e023a1b501084d9f2adf08fd7c9e50f18b2d/ios/Helpers/RCTHelpers.m#L85) property is already supported on iOS

**Comment by adiki** [comment]
Awesome, thank you. I didn't notice it in the docs

**Comment by guyca** [comment]
Yes, It's missing from the docs 😢

**Comment by Frexuz** [comment]
What about font size for the subtitle?

**Comment by laiyifeng77** [comment]
how to change the subtitle font size?
