### ISSUE TITLE
How to disable the elasticity/stretch on drawer?

### ISSUE THREAD

**Issue by ashah888** [wix/react-native-navigation#1364]
When using the drawer, there's a certain level of elasticity that makes the drawer "stretch" when it's in its open state and you "touch and drag" the drawer.

Is there a way to disable this?

**Comment by wei0121** [comment]
Need the same answer from here

**Comment by henrikra** [comment]
Yeah when drawer is open and you try to drag it even wider it actually does 🤣  This should be fixed

**Comment by guyca** [comment]
`shouldStretchDrawer` added in #1817 resolves this.
