### ISSUE TITLE
Quick fix for android crash not connected to packager because of ImageLoader

### ISSUE THREAD

**Issue by JuniusAng** [wix/react-native-navigation#1365]
### Issue Description
related to [#975](https://github.com/wix/react-native-navigation/issues/975)

Hi, for people that cannot run debug apps when not connected to packager, i think i found a hacky solution for this, i will gladly accept any better solution than mine.

From what i observed if we use image in our navigation then in debug mode, the logic always presumed we connected to packager all the time, so it will try to always load not from our packaged resource but from localhost.

you can check the file in 
[ImageLoader.java](https://github.com/wix/react-native-navigation/blob/79f07f8a8a56f0f2f94790860338015479b7747a/android/app/src/main/java/com/reactnativenavigation/react/ImageLoader.java) 

![screen shot 2017-06-15 at 3 33 17 pm](https://user-images.githubusercontent.com/19972153/27172594-ff60c29a-51df-11e7-8bc7-cf33bd5fedda.png)

and the JSDevImageLoader already throw an RunTimeException, so i think we can use try catch and reroute the logic to use release mode (load from resource) as long as you bundle the js that contains the image

this is my solution:
https://gist.github.com/JuniusAng/f42e9d62ee32e049f235d76f70ef96c3

hope this help people who stumbled upon the same issue

### Steps to Reproduce / Code Snippets / Screenshots

1. Connect to packager
2. Disconnect the server, 
3. Next time we open apps it will crash, just happened in debug mode

### Environment
* React Native Navigation version: 1.1.91
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator + device, Debug

**Comment by guyca** [comment]
Hey @JuniusAng 
I thought I addressed that by not throwing a [run time exception and simply returning an empty drawable](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/react/JsDevImageLoader.java#L29).

With your proposed solution, are images displayed when running debug APK with out connected packager?

**Comment by JuniusAng** [comment]
@guyca yes, it is.

**Comment by guyca** [comment]
I'm missing something here. In development mode, images are passed as urls to files over localhost. What exactly are you loading if the packager isn't connected?

**Comment by JuniusAng** [comment]
please correct me if i am wrong. my hypothesis was, if the app can run properly in release, it means that the loader for release mode is already correct, RNN used specific isDebug flag in NavigationApplication instance which tell JSDevImageLoader to load, with assumption that we connected, so in case it fails, it will load image similar to release version, 

in our project, after we bundle the js, any new image (previously in our js src folder) will be exported to res folder (in android)

**Comment by JuniusAng** [comment]
@guyca sorry if not clear enough, for my case, i had bundled my js once, so the image is present in my res folder, it wont work if you do not bundle the js into assets.

the icon we put in js code is located at : 
src/platform/shared/base/icMoreAndroid

this is one of the debug output. and it will return drawable from res/drawable-yyy (where yyy is respective density)
Bundle[{enabled=true, id=contextualMenu, icon=src_platform_shared_base_icmoreandroid}]
