### ISSUE TITLE
leftButtons crashes the App in Android

### ISSUE THREAD

**Issue by EtgarSH** [wix/react-native-navigation#137]
`    Navigation.showModal({
      screen: 'example.someScreen',
      title: 'A Screen',
      navigatorStyle: {},
      navigatorButtons: {
        leftButtons: [{
          title: 'Cancel',
          id: 'navBarCancel'
        }]
      }
    });`

When I set leftButtons the application crashes immediately.

**Comment by guyca** [comment]
fixed in v2.0
