### ISSUE TITLE
Using an avatar in the navbar

### ISSUE THREAD

**Issue by heroic** [wix/react-native-navigation#1372]
### Issue Description

My app needs to show the user's avatar in the navbar. Clicking on this icon will take the user to the settings page. However, there seems to be no way to achieve this currently.

### Steps to Reproduce / Code Snippets / Screenshots

      rightButtons: [{
        id: 'user',
        icon: resolveAssetSource({uri: 'https://www.hello.com/img_/hello_logo_hero.png'}),//this.state.userIcon ? {uri: this.state.userIcon} : require('../images/user.png'),
        disableIconTint: true
      }]
---
### Environment
* React Native Navigation version: 1.1.99
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): iOS Simulator 10.0.0

**Comment by N1XUS** [comment]
You can try base64 image

**Comment by harveyconnor** [comment]
I am also unable to use base64 as an icon using that.
I'm trying the exact same way:

```js
icon: { uri: <base64> }
```
