### ISSUE TITLE
Push is not working on android

### ISSUE THREAD

**Issue by adiki** [wix/react-native-navigation#1377]
Push is not working for android. Event is sent nothing is performed. On iOS everything is fine
![push android-2](https://user-images.githubusercontent.com/2124589/27256232-0530b9c0-53af-11e7-9d2a-dc4f2fd05d4f.gif)

**Comment by guyca** [comment]
Hey
Did you set a white background color for the screen you are pushing? Screens on Android have a transparent background color by default, where on iOS background color is white.

**Comment by adiki** [comment]
Yep sorry
