### ISSUE TITLE
Wrong font on pushed screen on android

### ISSUE THREAD

**Issue by adiki** [wix/react-native-navigation#1378]
![screenshot_1497773822](https://user-images.githubusercontent.com/2124589/27259283-6d70ca74-540f-11e7-89c3-a46ce56025c5.png)
![screenshot_1497773828](https://user-images.githubusercontent.com/2124589/27259284-6d9de7a2-540f-11e7-9d9f-cc31a5c37eb3.png)

**Comment by guyca** [comment]
You need to specify font in `navigatorStyle` of each screen, or in `appStyle` if you want to to be applied globally for all screens.
