### ISSUE TITLE
Size of icon on iOS

### ISSUE THREAD

**Issue by adiki** [wix/react-native-navigation#1379]
What size should I set of icon for navbar items. Now it looks strange:
![simulator screen shot 18 jun 2017 10 17 25](https://user-images.githubusercontent.com/2124589/27259297-aa37243a-540f-11e7-9225-e4e86bc302db.png)

**Comment by carlosroberto555** [comment]
I use 20 in my project

**Comment by adiki** [comment]
But quality is so poor then. iOS navbar is 44pt which means 88px...

**Comment by Crash--** [comment]
You have to use the 1x, 2x, 3x pattern for the name of your icons and iOS will choose the one needed and at the right size. 

Something like 
Icon@1x.png (44px if 44 is the right size)
Icon@2x.png (88px)
Icon@3x.png
