### ISSUE TITLE
TabBar can not hide in the first page befort switch( iOS 1.1.101 )

### ISSUE THREAD

**Issue by bingfj2008** [wix/react-native-navigation#1384]
Hi !

TabBar can not hide in the first page befort switch.

※Using 「tabBarHidden: true」

In the first Page before switch to other page, TabBar can not hide. But after switch to other page, Tabber is hide well.

even switch back to the first page, tabber is hide well.

However, On the Android, TabBar is good to hide in the first page befort switch.

Please help !
----------------------------------------------------------------------------------------
React Native Navigation version: 1.1.101
React Native version: 0.45.1
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): iOS 10.3

**Comment by tayfunyugruk** [comment]
hi @bingfj2008 i need exactly this too, do you have any progress for this problem ? i also could not hide tab bar at the very first screen for iOS and it is i think very interesting.

**Comment by tayfunyugruk** [comment]
hi @guyca at the official wix app there is no tab bar at first screens how did you accomplish this? i tried `tabBarHidden` at everywhere but no success, am i missing something ? Thanks.

**Comment by emelyanova** [comment]
hey 

I've found a very strange solution, but it can be useful for you if you need a temporary or quick fix:
I set drawUnderTabBar: true in navigationStyles and added 
this.props.navigator.toggleTabs({ to: 'hidden', animated: false });  to the componentWillMount for the first component

**Comment by MrLoh** [comment]
yes, I found that solution too, but it's clearly a bug, would be nice, if someone with an understanding of the code base could look into this.

**Comment by alinz** [comment]
@bingfj2008, @MrLoh, @emelyanova and @tayfunyugruk I had the similar problem and I realized that this is not implemented on IOS so I simply added. You can checkout out in this PR https://github.com/wix/react-native-navigation/pull/1868

Hope the accept the PR but in a meantime you can add this in your code.

**Comment by guyca** [comment]
fixed in #1868

**Comment by MrLoh** [comment]
Great. Thanks @alinz

**Comment by MrLoh** [comment]
this issue reappeared for me, when I restart the app programmatically. I'm rendering a singlePageApp as the login screen and then a tabBasedApp as the main app. On logging in (switching from the single page to tabBased app) it always shows the tab bar at first, I can't even hide it with a `navigator.setStyle` call inside render.
