### ISSUE TITLE
Android: Screen temporarily inherits other screen properties

### ISSUE THREAD

**Issue by ronaldheft** [wix/react-native-navigation#139]
When displaying a modal on Android, if the app is backgrounded (either shutting off the screen or opening the app switcher), on resume the navigation stack can get messed up. Here is what I'm observing:

1. Launch tab app, with SCREEN_1 and SCREEN_2.
2. Open modal for SCREEN_3 from SCREEN_1.
3. Background app.
4. Resume app.
5. Close modal for SCREEN_3.
6. **SCREEN_1 is displayed the with navigator options for SCREEN_3 (ex. title, navigatorStyle).**
7. Switch to SCREEN_2 and back to SCREEN_1 in the tab bar.
8. **SCREEN_1 now has the correct navigator options.**

**Comment by guyca** [comment]
Thanks for reporting @ronaldheft

**Comment by ronaldheft** [comment]
Tracked this issue down. The back button usage for closing modals does not call `onDismiss`, which does not trigger an `updateStyles` call. I can submit a PR, but I'm not sure if you're taking PRs right now with 2.0 looming.
