### ISSUE TITLE
[iOS] TabBar issue.

### ISSUE THREAD

**Issue by grundmanise** [wix/react-native-navigation#1393]
### Issue Description

Consider this scenario:

1. We have a tab-based app.
2. We're on the 1st tab (but actually it does not matter on which one we are)
3. Our tab screen is a hefty one with a ScrollView/FlatList and with a dozens of components
4. We push a screen that has `static navigatorStyle = { tabBarHidden: true };` or we push it with `navigatorStyle: { tabBarHidden: true } ` - does not matter.
5. When we pop back to the tabbar screen we can see that the screen jumps 49 points up and returns to the initial position (not every time), while it jumps we can see a `screenBacgkoundColor` (in my example: 'green') (see gif)

In my app I have a `react-native-map` and a `FlatList` in the 'tabbar' screen -- it is even worse:
Screen don't just jump and return to the initial (correct) position (as on the gif below) - the whole screen moves up 49 points (and stays there) as if there is a 2nd (invisible) tabbar on top of the actual one.

### Steps to Reproduce / Code Snippets / Screenshots

I've made [this small project](https://github.com/grundmanise/react-native-navigation-tabbar-bug-demo) to reproduce this issue.
![bug](https://user-images.githubusercontent.com/19417672/27336021-ff48bae2-55d6-11e7-9345-2e0416707124.gif)
_slowed down for the demo_

#### Example layout from my actual app:
_Tabbar screen - before a screen push (the screen that will be pushed has `tabBarHidden: true`):_
![before-push-pop-bug](https://user-images.githubusercontent.com/19417672/27333810-d32c81e8-55cf-11e7-95d9-eae8855fa009.png)

_Tabbar screen - After the pop from the pushed screen:_
![after-pop-bug](https://user-images.githubusercontent.com/19417672/27333814-d4b9505e-55cf-11e7-84c4-77bc99b9db43.png)

### Temp. Solution

The only temp. & ugly solution that I've found is to:
- do not set `tabBarHidden: true`
- hide tabBar on the pushed screen using:

```
  onNavigatorEvent = (event) => {
    switch (event.id) {
      case 'willAppear':
        // BUG FIX: when 'tabBarHidden: true' is set in navigatorStyle -> bug when popping back
        // hide tabBar
        this.props.navigator.toggleTabs({
          to: 'hidden',
          animated: true,
        });
        break;
      case 'didAppear':
        break;
      case 'willDisappear':
        // BUG FIX: when 'tabBarHidden: true' is set in navigatorStyle -> bug when popping back
        // show tabbar when popping back
        this.props.navigator.toggleTabs({
          to: 'shown',
          animated: true,
        });
        break;
      case 'didDisappear':
        break;
    }
  };

```
---
### Environment
* React Native Navigation version: 1.1.104
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator: iPhone 5s, Device: iPhone  5s. Both Release & Debug.

**Comment by Javis1205** [comment]
set drawUnderTabBar: true will to fix issue

**Comment by jackmew** [comment]
set drawUnderTabBar: true doesn't fix this problem for me.
I need to set tabBarTranslucent: true

**Comment by mwildehahn** [comment]
Setting `drawUnderTabBar` worked for me within `Navigation.startTabBasedApp`:

```
Navigation.startTabBasedApp({
  tabs: [
    {
      label: "Home",
      screen: HOME,
      navigatorStyle: {
        drawUnderTabBar: true
      }
    }
  ]
});
```

During the transition there is a little bit of weirdness where the tab bar jumps up though:
![hide tab bar](https://user-images.githubusercontent.com/704593/35406521-f8fbbf16-01bd-11e8-8d59-07efa582a980.gif)

**Comment by Ukiand1** [comment]
@hmenzagh try this [https://github.com/wix/react-native-navigation/issues/2820](https://github.com/wix/react-native-navigation/issues/2820)

**Comment by hmenzagh** [comment]
@durdevic Didn't help sorry ! But thanks.
The solution I chose was to use a modal then push and pop in the modal.
It makes for a fine navigation UX and allows you to drop the entire stack with ease.

**Comment by guyca** [comment]
As mentioned in the comments, `drawUnderTabBar: true` should be used when hiding tabs in pushed screens though I agree with @hmenzagh that showing a modal is preferable as this is probably the UX your aiming for when hiding the `BottomTabs` in a pushed screen.

**Comment by harshalbid271** [comment]
@guyca can you expand a little bit on `drawUnderTabBar: true` should be used? I've tried setting this property in both, the tabbed screen and the non-tabbed screen. But there still is this issue where the tabbed screen will have an empty space, or will just flicker once.

**Comment by kevinkevw** [comment]
drawUnderTabBar: true fixed the problem. 
Is there any API to get the tab bar height? coz' will need it to add some margin on the bottom of the screens.

**Comment by howg0924** [comment]
I recommend people with tabBar flicker issue to give pribeh's method a try:

https://github.com/wix/react-native-navigation/issues/2184#issuecomment-397830334

It solved the issue for me. The main concept is to give the screen with tabs a fixed height.

**Comment by ssshen** [comment]
@grundmanise your solution does not work for me, but also cause empty area in pushed page
