### ISSUE TITLE
[iOS] tabBarButtonColor does not change the text color

### ISSUE THREAD

**Issue by madki** [wix/react-native-navigation#1399]
`tabBarButtonColor` in `tabsStyle` does not change the color of the font below the tab icon. 

The documentation says it does though 
```javascript
    tabBarButtonColor: '#ffff00', // optional, change the color of the tab icons and text (also unselected)
```

Even the example project has the same issue. The styling from example project is:
```javascript
  tabsStyle: {
    tabBarBackgroundColor: '#003a66',
    navBarButtonColor: '#ffffff',
    tabBarButtonColor: '#ffffff',
    navBarTextColor: '#ffffff',
    tabBarSelectedButtonColor: '#ff505c',
    navigationBarColor: '#003a66',
    navBarBackgroundColor: '#003a66',
    statusBarColor: '#002b4c',
  },
```
This should give white tab icons with white text when unselected. But the tab icons are white and the text is still default gray that iOS uses.

---
### Environment
* React Native Navigation version: 1.1.103
* React Native version: 2.0.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 7, iOS 10.3, Debug

**Comment by madki** [comment]
Had a look at this PR
[https://github.com/wix/react-native-navigation/pull/1276](https://github.com/wix/react-native-navigation/pull/1276).

Seems there's another property that was added for this `tabBarLabelColor`. That worked.
Please update the documentation with the added attributes.

**Comment by guyca** [comment]
Hey @madki Can you please update the [documentation](https://github.com/wix/react-native-navigation/tree/master/docs) with the added attributes?

**Comment by jneuendorf** [comment]
Thanks @madki! I want to mention the corresponding `tabBarSelectedLabelColor` property for other people looking for this problem, because setting `tabBarButtonColor` AND `tabBarLabelColor` nullifies `tabBarSelectedButtonColor` for the button label.
