### ISSUE TITLE
TabBarHidden not remembered across pushes in Android

### ISSUE THREAD

**Issue by BrendonSled** [wix/react-native-navigation#1402]
### Issue Description

According to the [docs](https://github.com/wix/react-native-navigation/blob/4c85cfde25494df09641d2d4ad58c41653a91e03/docs/styling-the-navigator.md)
`tabBarHidden: false, // make the screen content hide the tab bar (remembered across pushes)`
tabBarHidden should be remembered across pushes, this is the case for iOS but not Android

### Steps to Reproduce / Code Snippets / Screenshots

push screen with `tabBarHidden: true` and then push another screen and the tab bar will be shown again

---
### Environment
* React Native Navigation version: 0.45.1
* React Native version: 1.1.112
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Galaxy S7, 7.0.0, Debug

**Comment by guyca** [comment]
Styles are not remembered across pushes on Android. Each screen should define its own styles explicitly, this behaviour will carry on to v2.
