### ISSUE TITLE
[TabBar] Specify font size

### ISSUE THREAD

**Issue by hose314** [wix/react-native-navigation#1407]
Cannot find any mention on this property in the docs or it's not even exist?

---
### Environment
* React Native Navigation version: 1.1.91
* React Native version: 0.43.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by ziyafenn** [comment]
Any luck finding an answer to control fontSize for tabBar?

**Comment by bieooo** [comment]
If you guys didn't found yet, here is the solution

`
const Nav = TabNavigator ({
//Screens Here
}, { 
    tabBarOptions:{
        labelStyles:{
            fontSize:10
        }
}
});
`

@hose314 @ziyafenn

**Comment by DaniyarJakupov** [comment]
@bieooo you're confusing libraries, this is not react-navigation.
@hose314 @ziyafenn on iOS this works: 
```
tabsStyle: { 
    tabBarTextFontSize: 18,
}
```

Coudn't find solution for android tho

**Comment by alexey-belous** [comment]
I've added ability to specify fontSize by following properties of appStyle: tabFontSize and selectedTabFontSize.

**Comment by thisisjaiswal** [comment]
tabBarOptions: {
      **labelStyle**: { fontSize: 12 },
}

works

**Comment by buddhika-ranasinghe** [comment]
Thanks @thisisjaiswal 
**labelStyle:{ fontSize:25 }** worked for me

**Comment by weikee94** [comment]
@thisisjaiswal @buddhika-ranasinghe  may i know what version u guys referencing ? v1 or v2 thanks.

**Comment by umairkhan1997** [comment]
tabBarOptions: {
labelStyle: { fontSize: 12 },
}

this helps .

**Comment by gerardramospear** [comment]
@thisisjaiswal that worked as well as for font family, was this documented anywhere? was wondering how you knew this because I couldn't find this until i saw your post
