### ISSUE TITLE
[Question] When will version 2 be release

### ISSUE THREAD

**Issue by dzunglht** [wix/react-native-navigation#1409]
@here @all May we know when will the version 2 be release ? whats your project roadmap ?
Tons of thanks

**Comment by carlosroberto555** [comment]
Version 2 milestone: [https://github.com/wix/react-native-navigation/milestone/1](url)

**Comment by BrendonSled** [comment]
Your link is broken [https://github.com/wix/react-native-navigation/milestone/1](https://github.com/wix/react-native-navigation/milestone/1)
