### ISSUE TITLE
How to dismiss modal by press background

### ISSUE THREAD

**Issue by musicode** [wix/react-native-navigation#141]
API provide `dismissModal()` method, I think author hope developer to add a close button, once pressing it, call `dismissModal()`.

however, user is used to dimiss modal by pressing background, how can i do it?

**Comment by guyca** [comment]
Can you please add a screen shot?

Navigation isn't aware of what you render in JS. You can wrap you views in a `TouchableNoFeedback` and dismiss the modal from the `onPress` callback. Is this what you're referring to?

**Comment by musicode** [comment]
> Is this what you're referring to?

yes，thank you.

by the way, can you tell us whether 2.0 can release in September?

**Comment by guyca** [comment]
You welcome. v2 should be available before September.
