### ISSUE TITLE
How to do pop to the specify scene?

### ISSUE THREAD

**Issue by abellee** [wix/react-native-navigation#1410]
### Issue Description

when I do push more than one scenes step by step, maybe 4 or more,
in the last scene, I wanna pop to the second scene, and then I still can pop to the root scene from the second scene,
how can i do this?

---
### Environment
* React Native Navigation version: master branch
* React Native version: 0.45
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
Show the flow in a Modal as explained here https://github.com/wix/react-native-navigation/issues/286#issuecomment-272523552

**Comment by abellee** [comment]
@guyca 
so your mean is that I should use `showModal` after the second scene, and then use `dismissAllModal` to resolve this problem is the best way, right?

**Comment by guyca** [comment]
Yes exactly.
