### ISSUE TITLE
[IOS] the buttons overflows the tabBar when using a big image as an icon

### ISSUE THREAD

**Issue by MarvinSantos** [wix/react-native-navigation#1415]
### tabBar buttons size

the buttons on tabBar are getting to big when using a big image as its icon, there is a way to pass the height and width to it or i have to resize the image with an editor?

**Comment by cihancil** [comment]
Same issues. If I use low res icons then it looks bad

**Comment by ceciliaschiebel** [comment]
https://github.com/wix/react-native-navigation/issues/1379

I'm going to try with this one

**Comment by nabeelpkl** [comment]
Same issue here :(

**Comment by adamski** [comment]
Also having this issue. I'm using circular images and the top of the circle is being clipped.

**Comment by vranjesluka** [comment]
I am experiencing the same issue. Seems that the library is setting the size of the icon to the number of pixels that icon has even.

For example, for the icons
Icon@1x.png (28x28px)
Icon@2x.png (56x56px)
Icon@3x.png (84x84px)
on iPhone 8 (which uses x2 icons) it sets the size of the bottom navigation icon to 56x56 "points", and then the pixel size is 112x112px.
on iPhone Z (which uses x3 icons) it sets the size of the bottom navigation icon to 84x84 "points", and then the pixel size is 252x252px.

![simulator screen shot - iphone 8 - 2018-02-06 at 11 29 18](https://user-images.githubusercontent.com/8490079/35854617-1b07c128-0b31-11e8-9bd0-e566ac682b08.png)
![simulator screen shot - iphone x - 2018-02-06 at 11 29 17](https://user-images.githubusercontent.com/8490079/35854618-1b2c77c0-0b31-11e8-8073-2e55a1153b7a.png)

**Comment by cihancil** [comment]
Using @2x @3x pattern solves this problem.

**Comment by vranjesluka** [comment]
I think I'm using the @2x, @3x correctly.
what is the size of your @2x @3X icons? Are they really x2 and x3 size of the x1 icon.

I have added my code and example of my icons to my comment, I hope it will help.

**Comment by cihancil** [comment]
I've used 24x24px as base image and multiplied it with 2 and 3.
28x28px shouldn't be a problem. I am not sure what's wrong with your app.
Are you using latest version?

**Comment by vranjesluka** [comment]
Yes.
React Native Navigation version: 1.1.371
React Native version: 0.53

**Comment by adamski** [comment]
Reducing the size of my images to 28x28px for @x1 worked for me. For some reason Sketch exported the icons at 39px for @1x.

**Comment by vranjesluka** [comment]
Wix doesn't work with static images from [native code](https://facebook.github.io/react-native/docs/images.html#images-from-hybrid-app-s-resources) and you need to use the [@1x  @2x @3X pattern](https://facebook.github.io/react-native/docs/images.html#images-from-hybrid-app-s-resources) directly in React native code

**Comment by sturmenta** [comment]
In android the images were adjusted automatically, but to make it look good on iOS I use this:

image@1x.png (30px)
image@2x.png (60px)
image@3x.png (90px)

https://facebook.github.io/react-native/docs/images.html

and add: iconInsets: `{top: 5,bottom: -5}` in:
```js
  Navigation.startTabBasedApp({
    tabs: [
      {
        screen: 'myschool.home',
        icon: home,
        iconInsets: {top: 5,bottom: -5},
        navigatorStyle: {
          navBarHidden: true,
          screenBackgroundColor: '#0D1011',
        }
      }...
```
to center the image correctly in iOS.

<img width="382" alt="captura de pantalla 2018-04-26 a la s 04 59 30 a m" src="https://user-images.githubusercontent.com/30802967/39293235-c1cee34a-490e-11e8-8fd3-d0793a3908d8.png">
<img width="327" alt="captura de pantalla 2018-04-26 a la s 04 59 54 a m" src="https://user-images.githubusercontent.com/30802967/39293236-c204587c-490e-11e8-974b-5211d3a439ba.png">
