### ISSUE TITLE
Unit Testing with Jest

### ISSUE THREAD

**Issue by SukhKalsi** [wix/react-native-navigation#1417]
### Issue Description

As we all know, Jest comes preinstalled with React Native. Are there best practices in using Jest with this Navigation library at all, or point me to any articles which work well when using this library?

### Steps to Reproduce / Code Snippets / Screenshots

Using a vanilla React Native project, install this library (v1.1.x).
Integrate the library as Single or Tab Based app.
Run `npm run test`
Tests will fail.

---
### Environment
* React Native Navigation version: v1.1.x
* React Native version: v0.44
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): n/a

**Comment by bryfox** [comment]
Someone may have a better idea, as I've only used this for a short time, but react-native-navigation assumes the native bindings are in place, and the errors you see are when the tests run with `react-test-renderer`. No 'native' code is involved.

For unit tests, I've decided I'm better off testing underlying components directly, and keeping the native-navigation integration isolated. You could probably [mock](https://facebook.github.io/jest/docs/tutorial-react-native.html#mock-native-modules-using-jestmock) some of the interface to get the built-in `index.ios` and `index.android` tests working, but I didn't see much benefit.

If I wanted to really test the native components, I'd look at the native testing solutions that come with Xcode and Android Studio.

**Comment by ugiacoman** [comment]
For Jest Snapshot testing, you'll want to test the actual rendering of the component, without react-native-navigation. Native components cannot be tested by Jest, but can be mocked.

**Comment by SukhKalsi** [comment]
Thanks @bryfox that makes sense. I'll close this now but if anyone has any other thoughts on this would be good to discuss it (reopen if necessary) here
