### ISSUE TITLE
[Android] - Tabbar Labels

### ISSUE THREAD

**Issue by EtgarSH** [wix/react-native-navigation#142]
![screen shot 2016-07-20 at 11 49 25 am](https://cloud.githubusercontent.com/assets/4920831/16980741/252a4650-4e70-11e6-9ad2-f734b30e83d1.png)

Please make the taabbar in the Android to look like this:
![screen shot 2016-07-20 at 11 50 55 am](https://cloud.githubusercontent.com/assets/4920831/16980762/40b0a7ca-4e70-11e6-8660-bde623accdfc.png)

(A label only on the selected button)

To make it to look more like android.

Thanks! 💯

**Comment by adamski** [comment]
Do you mean 

> label only on the **selected** button

?

**Comment by guyca** [comment]
implemented in v2.0
