### ISSUE TITLE
FAB not showing up.

### ISSUE THREAD

**Issue by XDTZ** [wix/react-native-navigation#1423]
### Issue Description
Hi,
I made a minimalistic app to demonstrate my problem. It's just a blank app screen calling `setButton` in `componentDidMount()`
However github somehow won't let me upload zip file. So here's the link for my project: 
Just extract, `cd` into the project, and then `react-native run-android`
Download Link: 
https://app.box.com/s/h9mbqczf34epyqcwbe55slui2brugrhg

### Environment
* React Native Navigation version: 1.1.118
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Genymotion 7.1.0 Nexus 6P, Debug mode

**Comment by guyca** [comment]
Hey, please push the project to github so I can clone it.

**Comment by XDTZ** [comment]
Here you go, Thanks!
https://github.com/XDTZ/testing

**Comment by guyca** [comment]
@XDTZ Fab must have icons.

```js
{
      fab: {
        collapsedId: 'share',
        expendedId: 'clear',
        collapsedIcon: require('../img/icon.png'),
        expendedIcon: require('../img/icon.png'),
        backgroundColor: '#ff505c',
        actions: [
          {
            id: 'mail',
            backgroundColor: '#03A9F4',
            icon: require('../img/icon.png'),
          },
          {
            id: 'delete',
            backgroundColor: '#4CAF50',
            icon: require('../img/icon.png'),
          }
        ]
      }
    }
```

**Comment by XDTZ** [comment]
I found I misunderstanded the path reference level so I got nothing even with icon supplied. Thank you!

**Comment by jsina** [comment]
@guyca How could I fire an event with simple fab button.
this.props.navigator.setButtons({
      fab: {
        collapsedId: 'share',
        expendedId: 'clear',
        collapsedIcon: require('../../imgs/funnel.png'),
      }
    });`


 onNavigatorEvent = event => {
    console.log(event.type, ' event');
  }
`
