### ISSUE TITLE
Transition background color

### ISSUE THREAD

**Issue by bernatbombi** [wix/react-native-navigation#1425]
When transitioning from one Screen to another (either using card or modal mode), there's a white background that transitions its alpha from 0 o 1, during the screen to screen animation.

I'd like to know how to change the color, if possible.

![Screenshot](https://preview.ibb.co/eZURTQ/telegram_cloud_file_4_431807530_164558_7308204946965615270.jpg)
---
### Environment
* React Native Navigation version: 1.0.0-beta.11
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 10.3, iPhone 6

**Comment by guyca** [comment]
`1.0.0-beta.11` isn't familiar to me. Are you sure you're using RNN?
