### ISSUE TITLE
SideMenu Drawer Navigation on Android not navigating with navigator.resetTo

### ISSUE THREAD

**Issue by ramki1979** [wix/react-native-navigation#1426]
### Issue Description
I have an iOS/Android app with SideMenu Drawer Navigation.
```Javascript
Navigation.startSingleScreenApp({
      screen: {
        screen: 'HomePage',
        title: 'Home',
        navigatorStyle: navStyles.navigatorStyle,
        leftButtons: Platform.OS === 'android' ? [
          {
            id: 'sideMenu'
          }
        ] : []
      },
      drawer: {
        left: {
          screen: 'SideMenu'
        },
        style: {
          drawerShadow: 'NO'
        }
      }
    })
```

When an Item is selected on Drawer Menu, using DeepLink I am navigating to new screen using 
```Javascript
this.props.navigator.resetTo({
  screen: 'SettingsPage', 
  title: 'Settings',
  passProps: {},
  animated: true,
  navigatorStyle: navStyles.navigatorStyle,
  leftButtons: Platform.OS === 'android' ? [
    {
      id: 'sideMenu'
    }
  ] : []
});
```
on iOS above code is working as expected.

But on Android nothing happens and if I selected another Item it generated multiple DeepLink calls. This DeepLink calls works like an autoIncrement where each additional click we get 1 more additional DeepLink call with the current selected Item of the drawer. But no navigation happens.
its like 
1 click => 1 DeepLink call [Normal as expected] -> No change of Screen 
2nd click => 2 DeepLink calls [I am expecting Only 1] -> No change of Screen
3rd Click => 3 DeepLink calls [I am expecting Only 1] -> No change of Screen
Toggle the Drawer Close then again Open and
4th click => 4 DeepLink calls [I am expecting Only 1] -> No change of Screen

on iOS everything is working as Normal but on Android I am having this issue.

so I tried with using `Navigation.startSingleScreenApp` on every drawer menu selection and it works but with the navigation animation is like opening a New App rather than a smooth transition to new Screen.

So `Navigation.startSingleScreenApp` is not I wanted for this scenario. Is there any configuration that I am missing so that `this.props.navigator.resetTo` will work.

```JavaScript
this.props.navigator.resetTo // how to make this work on android.
```

---
### Environment
* React Native Navigation version: 1.1.81
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Debug

**Comment by ramki1979** [comment]
The new screen's have no content / style except an empty View. Once I added content & style it started working on Android.

**Comment by guyca** [comment]
@ramki1979 As you've already noticed, Screens are not displayed on Android until they have visible child views 👍
