### ISSUE TITLE
bottomTabSelected event not triggered when clicking on the current tab

### ISSUE THREAD

**Issue by gvillenave** [wix/react-native-navigation#1428]
### Issue Description

When tapping on an already selected tab, the bottomTabSelected event is not triggered. Is that something that we could consider adding? My use case is trying to refresh data when the tab is double-tapped (similar to the Facebook news feed).

---
### Environment
* React Native Navigation version: 1.1.108
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): both

**Comment by guyca** [comment]
Hey @gvillenave 
[bottomTabReselected](https://github.com/wix/react-native-navigation/search?utf8=%E2%9C%93&q=bottomTabReselected&type=) should be sent in that case. Sadly it's missing from the docs

**Comment by gvillenave** [comment]
Thank you!
