### ISSUE TITLE
How to style the topTabs?

### ISSUE THREAD

**Issue by rvpyrv** [wix/react-native-navigation#1429]
How to style the topTabs section?

**Comment by rvpyrv** [comment]
I want to style the topTabs, but i dont see how in documentation. 
Something like that: 

topTabs: [
      {
        screenId: 'example.First',
        title: 'TitleOne',
        tabBarButtonColor: 'cornflowerblue',
      },
      {
        screenId: 'example.Second',
        title: 'TitleTwo',
          tabBarButtonColor: 'cornflowerblue',
      }
    ]

**Comment by varungupta85** [comment]
Specify below in screen `navigatorStyle`

```javascript
 topTabBarStyle: {
    selectedTopTabIndicatorColor: colorThemes.Blue.white,
    selectedTopTabIndicatorHeight: 5,
    selectedTopTabTextColor: colorThemes.Blue.white,
    topTabTextColor: colorThemes.Blue.transluscentWhite
  }
```

**Comment by rvpyrv** [comment]
@varungupta85 and it is dont work.

**Comment by varungupta85** [comment]
Share the appropriate code where you applied the above styles. I am using this in my app. So, I suspect there is some mistake in how the above styles are applied.

**Comment by rvpyrv** [comment]
I tried to put it in multiple places, and it doesnt work.
1)Inside the startTabBasedApp
2)Inside tab declaration, navigatorStyle
3)Inside screen's static navigatorStyle
4)Inside the topTab declaration

**Comment by rvpyrv** [comment]
Where did u read this topTabBar properties?

**Comment by varungupta85** [comment]
I have it in the screen static `navigatorStyle`. Can't help further without looking at the code?

**Comment by rvpyrv** [comment]
//React
import React from 'react';
//Redux
import { Provider } from 'react-redux';
import configureStore from './store/configureStore';
const store = configureStore();
//Navigation
import { Navigation } from 'react-native-navigation';
import { registerScreens }  from './screens';
registerScreens(store, Provider);


Navigation.startTabBasedApp({
   appStyle: {
	forceTitlesDisplay: true,
	tabBarButtonColor: '#222222',
	tabBarSelectedButtonColor: 'cornflowerblue',
       topTabBarStyle: {
           selectedTopTabIndicatorColor: 'red',
           selectedTopTabIndicatorHeight: 2,
           selectedTopTabTextColor: '#ffffff',
           topTabTextColor: '#222222'
       },
   },
  tabs: [
	{
	  label: 'Home',
	  screen: 'example.Home', // this is a registered n,ame for a screen
	  icon: require('./assets/images/PNG/home3.png'),
        navigatorStyle: {
          navBarHideOnScroll: true, // false, since we collapse the TopBar and the TitleBar remains visible with the top tabs
          topBarCollapseOnScroll: true,
          navBarSubtitleColor: 'red'

	   },
	  title: 'Home',
		topTabs: [
			{
				screenId: 'example.Waits',
				title: 'Title1',
			},
			{
				screenId: 'example.Main',
				title: 'TitleTwo'
			}
		]
	},
	{
	  screen: 'example.Waits',
	  icon: require('./assets/images/PNG/watches.png'),
	  title: 'Waits',
	  label: 'Waits'
	},
	{
		screen: 'example.Waits',
		icon: require('./assets/images/PNG/plus-circle.png'),
		title: 'Create',
		label: 'Create'
	},
		{
		screen: 'example.Home',
		icon: require('./assets/images/PNG/updates.png'),
            navigatorStyle: {
                navBarHideOnScroll: true, // false, since we collapse the TopBar and the TitleBar remains visible with the top tabs
                topBarCollapseOnScroll: true,
                navBarSubtitleColor: 'red'

            },
		title: 'Updates',
		label: 'Updates',
            topTabs: [
                {
                    screenId: 'example.Home',
                    title: 'Title1',
                },
                {
                    screenId: 'example.Main',
                    title: 'TitleTwo'
                }
            ]
	},
	{
	label: 'Profile',
	screen: 'example.Profile',
	icon: require('./assets/images/PNG/user-plus2.png'),
	title: 'Profile'
	}
  ]
});

**Comment by rvpyrv** [comment]
Navigation.startTabBasedApp({
   appStyle: {
	forceTitlesDisplay: true,
	tabBarButtonColor: '#222222',
	tabBarSelectedButtonColor: 'cornflowerblue'
   },
  tabs: [
	{
	  label: 'Home',
	  screen: 'example.Home', // this is a registered n,ame for a screen
	  icon: require('./assets/images/PNG/home3.png'),
        navigatorStyle: {
          navBarHideOnScroll: true, // false, since we collapse the TopBar and the TitleBar remains visible with the top tabs
          topBarCollapseOnScroll: true,
          navBarSubtitleColor: 'red',
            topTabBarStyle: {
                selectedTopTabIndicatorColor: 'red',
                selectedTopTabIndicatorHeight: 2,
                selectedTopTabTextColor: '#ffffff',
                topTabTextColor: '#222222'
            },

	   },
	  title: 'Home',
		topTabs: [
			{
				screenId: 'example.Waits',
				title: 'Title1',
			},
			{
				screenId: 'example.Main',
				title: 'TitleTwo'
			}
		]
	},
	{
	  screen: 'example.Waits',
	  icon: require('./assets/images/PNG/watches.png'),
	  title: 'Waits',
	  label: 'Waits'
	},
	{
		screen: 'example.Waits',
		icon: require('./assets/images/PNG/plus-circle.png'),
		title: 'Create',
		label: 'Create'
	},
		{
		screen: 'example.Home',
		icon: require('./assets/images/PNG/updates.png'),
            navigatorStyle: {
                navBarHideOnScroll: true, // false, since we collapse the TopBar and the TitleBar remains visible with the top tabs
                topBarCollapseOnScroll: true,
                navBarSubtitleColor: 'red'

            },
		title: 'Updates',
		label: 'Updates',
            topTabs: [
                {
                    screenId: 'example.Home',
                    title: 'Title1',
                },
                {
                    screenId: 'example.Main',
                    title: 'TitleTwo'
                }
            ]
	},
	{
	label: 'Profile',
	screen: 'example.Profile',
	icon: require('./assets/images/PNG/user-plus2.png'),
	title: 'Profile'
	}
  ]
});

**Comment by varungupta85** [comment]
Please wrap your code in a code element so that it is readable. I see that you are using a tab based app where each tab may have top tab bar. I have a single screen app. Any way, in my case, I have applied to top tab bar styles to the static `navigatorStyle` of the screen and not where you have applied them in the above code.

**Comment by rvpyrv** [comment]
@varungupta85 I solved it.
So, inside the topTabs container
add the following: 

`static navigatorStyle = {`
    `selectedTopTabIndicatorColor: string,`
    `selectedTopTabIndicatorHeight: integer,`
    `selectedTopTabTextColor: string,`
    `topTabTextColor: string`
`}`

-------------

I encorage you to see, that there is no topTabBarStyle property. 
Closing.
