### ISSUE TITLE
cann't work well with react-native-barcodescanner

### ISSUE THREAD

**Issue by SPxiaomin** [wix/react-native-navigation#143]
following the instruction, I install the react-native-barcodescanner, and it work well without react-native-navigation. But, when it comes to react-native-navigation and I create a individual page for the react-native-barcodescanner to work, it cann't work well. When i go to the page by pressing a button on a another page, It only show a red line on the left, nothing else.

Plz help me~
thx in advance~

**Comment by guyca** [comment]
@SPxiaomin Could you provide a sample project where I can debug this issue?

**Comment by SPxiaomin** [comment]
@guyca https://github.com/SPxiaomin/Barcode there is the sample project providing for you to debug.

thx for help me. The problem occur in a project I am doing now and there is a deadline for the project. I am now very nervous.

**Comment by beast** [comment]
@SPxiaomin We are using react-native-barcodescanner as well and it's working fine with react-native-navigation 1.0.17 with react native 0.27 with some custom fix we did. I just took a look at the project, you are using react native 0.29.2. It will not work well with react-native-navigation. There are some breaking changes introduced to Android https://github.com/facebook/react-native/releases/tag/v0.29.0

@guyca I understood currently react native 0.25 is supported according to issues I opened previously. With latest 0.29 introducing some breaking changes for Android, is there any plan to update the project to support 0.29 in the near future? Thanks.

**Comment by guyca** [comment]
@beast I estimate we'll start migrating to RN 0.30 at the beginning of August.

**Comment by SimchaShats** [comment]
I think as temporary solution you can put necessary modules in the method getPackages() in BaseReactActivity.java class in react-native-navigation module (like it was in previous versions of react-native)...

**Comment by beast** [comment]
@SimchaShats I don't think that is going to work according to this commit. https://github.com/facebook/react-native/commit/49f20f41546e3ba8e7fe43c84c4c701684d0434d

I tried it out regardless and it didn't work for me. I don't see any way other than upgrading the package.
