### ISSUE TITLE
Android navBarHideOnScroll won't detect FlatList component scroll. ScrollView only.

### ISSUE THREAD

**Issue by tomislavHonig** [wix/react-native-navigation#1430]
NavBar won't hide after putting this into the navigator style object and appStyle object.

 navBarHideOnScroll: true,
expendCollapsingToolBarOnTopTabChange: false,
drawUnderTabBar: true

Only ScrollView scrolling will activate hiding of the navBar.

---
### Environment
* React Native Navigation version: 1.1.115
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): HTC 10

**Comment by juicycleff** [comment]
I use flatlist with navBarHideOnScroll and it works like correctly on android.

**Comment by tomislavHonig** [comment]
Can you please share same code?

**Comment by guyca** [comment]
@tomislavHonig The root view has to be either a ListView, ScrollView or FlatList.
If you are populating the list after the view is rendered, and before the list is populated you render some other view that is not one of the three I've mentioned - the list detection logic in native fails 😭
