### ISSUE TITLE
Navigation Button Action

### ISSUE THREAD

**Issue by thomasbaldwin** [wix/react-native-navigation#1434]
### Issue Description

I would like to make it so that a navigation button on press triggers a method on the respective component that's being displayed. The reason for this is becasue I've made a full-screen TextInput, and would like it so when they click the <b>Post</b> button in the top right corner, it will trigger the `post()` action on the component. The reason the post() action is on the component is because as they type, I'm updating the state to hold the value of what is in the TextInput. 

### Steps to Reproduce / Code Snippets / Screenshots

Here's my current navigation code:

<img width="437" alt="screen shot 2017-06-29 at 2 57 05 pm" src="https://user-images.githubusercontent.com/5099084/27705225-3feb6cba-5cdb-11e7-82ef-4b5c4ce871c4.png">

Here's what it currently looks like:

![simulator screen shot jun 29 2017 2 49 56 pm](https://user-images.githubusercontent.com/5099084/27705176-1faed946-5cdb-11e7-8feb-9e2ce1664d37.png)

---
### Environment
* React Native Navigation version: ^1.0.0-beta.7
* React Native version: ^0.42.0
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by rvpyrv** [comment]
Are you talking about React Native Navigation? 
I see that you use React Navigation

It's a different navigation's.

**Comment by thomasbaldwin** [comment]
@rvpyrv, yes I was, my bad. I've posted to the correct repository now. Thank you :)
