### ISSUE TITLE
[Question] set backButtonTitle in IOS

### ISSUE THREAD

**Issue by Shinichi52** [wix/react-native-navigation#1436]
Hi,
Can you help me set backButtonTitle in iOS? 
Thanks :)
---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: 0.44.1
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator - 10 - Debug

**Comment by Zcgong** [comment]
Just use backButtonTitle

**Comment by Shinichi52** [comment]
i want to update backButtonTitle after push screen to stack. How to update it?

**Comment by guyca** [comment]
as @Zcgong mentioned, set [backButtonTitle](https://wix.github.io/react-native-navigation/#/screen-api?id=pushparams) when pushing the screen
