### ISSUE TITLE
Where's the example code/app?

### ISSUE THREAD

**Issue by tmaly1980** [wix/react-native-navigation#1437]
The documentation specifically mentions the boilerplate app having some code to learn from/demo. However, it appears to be just a vanilla app with nothing coded beyond installing the dependencies. What's the purpose in that? 

Where is the code for the animations on this project's readme? They clearly seem to be demo apps.

**Comment by jp928** [comment]
@tmaly1980 
https://github.com/junedomingo/movieapp

**Comment by guyca** [comment]
[This](https://github.com/wix/react-native-navigation/tree/master/example) is the official example app.
