### ISSUE TITLE
How to start single page app as component?

### ISSUE THREAD

**Issue by tmaly1980** [wix/react-native-navigation#1438]
In most other navigation systems (such as react-navigation), the default navigator (a stack, etc) is exported and rendered as a component. How can I do this with Navigation.startSinglePageApp?

I'm specifically wrapping my app with native-base theming, which depends on StyleProvider wrapping over everything else, ie:

```
import getTheme from '../../native-base-theme/components'
import material from '../../native-base-theme/variables/material'
import Navigation from './Navigation'

class RootContainer extends Component {
  render () {
    return (
      <StyleProvider style={getTheme(material)}>
        <View style={styles.applicationView}>
          <Navigation />
        </View>
      </StyleProvider>
    )
  }
}
```

I need a way for  Navigation.startSingleScreenApp() to act as the component 'Navigation' above, which doesn't seem to work even if I do this in my Navigation.js:

```
export default Navigation.startSingleScreenApp({
....
})
```

**Comment by smooJitter** [comment]
In you are running a SingleScreenApp (e.g., no tabs at the bottom), and assuming you are start app in file called app.js, here's something to consider

Let's say you have a home component

```
// home.js
import getTheme from '../../native-base-theme/components'
import material from '../../native-base-theme/variables/material'
import Navigation from './Navigation'

class Home extends Component {
  render () {
    return (
      <StyleProvider style={getTheme(material)}>
        <View style={styles.applicationView}>
          //  home stuff goes here.
        </View>
      </StyleProvider>
    )
  }
}

export default Home;
```
Now you have to register this home screen 
```
// screens/ index.js
import { Navigation } from 'react-native-navigation';

import Home from './home';
import SideMenu from './sidemenu';
// import some more screeens

export default () => {
  Navigation.registerComponent('home.screen', () => Home);
  Navigation.registerComponent('sidemenu.screen', () => SideMenu);
  ... // register some more screens
}
```
Now here's where things get a bit different.  There's no root container component like react-navigation.  Essentially, Navigation.startSingleScreenApp is the root container. So in that file you would do this

```
import { Navigation } from 'react-native-navigation';

// screen related book keeping
import registerScreens from './screens';
registerScreens();

  Navigation.startSingleScreenApp({
    screen: {
      screen: 'home.screen',
      title: 'Navigation',
      navigatorStyle: {},
    },
    drawer: {
      left: {
        screen: 'SideMenu',
      },
    },
  });
```
Hope this helps.

**Comment by rvpyrv** [comment]
@tmaly1980 i found a solution.

app.js:

```javascript
export default App extends Component {
    
    constructor(){
        super();
        this.bootstrap();
    }
    
    boostrap(){
       //Your RNN configuration goes here

       Navigation.startSingleScreenApp({ /* ... */ }); 

    }
  
}
```

index.#platformName#.js:

```javascript
import App from './source/App';

const AppName = new App(); //Call the constructor

```

**Comment by guyca** [comment]
In a Js based navigator, the app is a component since the app lives inside a single native view. In RNN (or any other native navigation solution), the app isn't a component since a component represents a Screen in the UI hierarchy.
You should follow the approach recommended by @rvpyrv, in that class you can setup `AppState` listeners etc.
