### ISSUE TITLE
Tab bar bottom margin

### ISSUE THREAD

**Issue by willoughby** [wix/react-native-navigation#144]
I need to create a 50px bottom margin on my tab bar to allow ads to be displayed as they are currently sitting over the top. 

Do you have any idea how this can be achieved?

Thanks

**Comment by guyca** [comment]
Hey @willoughby You can't add the margin in your JS screens?

**Comment by willoughby** [comment]
I doesn't move the tab bar, but just everything within the active tab.

![simulator screen shot 21 jul 2016 07 51 18](https://cloud.githubusercontent.com/assets/158088/17013674/efd05d84-4f17-11e6-9b1d-0fcad5a0213c.png)

![simulator screen shot 21 jul 2016 07 41 46](https://cloud.githubusercontent.com/assets/158088/17013638/c4f74b7c-4f17-11e6-99d7-dcd6ce720fdc.png)

When my app loads i call this, and i added bottom margin to tab screens.

`Route.afterAuth = () => {
    Navigation.startTabBasedApp({
        tabs: [

            {
                label: 'Chat',
                screen: 'gc.Chat',
                title: 'Chat',
                icon: iconsMap["ios-chatboxes"],
            },
            {
                label: 'Groups',
                screen: 'gc.LFG',
                title: 'Groups',
                icon: iconsMap["ios-pin"],
                navigatorStyle: {
                    navBarBackgroundColor: DefaultStyles.NAV_BAR_BACKGROUND_COLOR,
                    navBarTextColor: DefaultStyles.NAV_BAR_TEXT_COLOR,
                    navBarButtonColor: DefaultStyles.NAV_BAR_TEXT_COLOR,
                },
                navigatorButtons: {
                    leftButtons: [
                        {
                            title: "List View",
                            icon: iconsMap['ios-list'],
                            id: "list"
                        }
                    ]
                }
            },
            {
                label: 'News',
                screen: 'gc.News',
                icon: iconsMap['ios-paper'],
                title: 'News',
                navigatorStyle: {
                    navBarBackgroundColor: DefaultStyles.NAV_BAR_BACKGROUND_COLOR,
                    navBarTextColor: DefaultStyles.NAV_BAR_TEXT_COLOR
                }
            },
            // {
            //     label: 'Notifications',
            //     screen: 'gc.Notifications',
            //     title: 'Notifications'
            // },
            {
                label: 'More',
                screen: 'gc.More',
                title: 'More',
                icon: iconsMap['ios-more'],
                navigatorStyle: {
                    navBarBackgroundColor: DefaultStyles.NAV_BAR_BACKGROUND_COLOR,
                    navBarTextColor: DefaultStyles.NAV_BAR_TEXT_COLOR
                }
            }
        ],
        tabsStyle: {
            tabBarSelectedButtonColor: DefaultStyles.NAV_BAR_BACKGROUND_COLOR
        }
    })
}`

**Comment by willoughby** [comment]
The ads are displayed using native code, so could it be that the view which contains the react-native app needs to resize somehow? When I used the react-native tabs this wasn't an issue.

**Comment by guyca** [comment]
Are the ads wrapped in a [custom UI component](https://facebook.github.io/react-native/docs/native-components-ios.html) and rendered in the `render` method?

**Comment by willoughby** [comment]
No, i wrote a bridge to obj which add it to the current root vc

` RCT_EXPORT_METHOD(displayBanner)
  {
    UIViewController *rootViewController = [UIApplication sharedApplication].delegate.window.rootViewController;
    
    dispatch_async(dispatch_get_main_queue(), ^{
      [Appodeal showAd:AppodealShowStyleBannerBottom rootViewController:rootViewController];
    });
  }`

**Comment by guyca** [comment]
adding @artald to the conversation

**Comment by artald** [comment]
@willoughby In your code you're always showing the ad on the app root view controller while the screen that you actually want to show it in is not the same. I think that this is the problem here.

In addition, since Appodeal is not open source we can't know for sure what they're doing to the view and how they're adding it.

Currently we don't have a way to access a specific ViewController. We can add this feature to V2 which is now in the works but it will take some time.

In the meantime I suggest that you try to create a custom react UI component that will hold the Apodeal ad view so you can include it inside your render function. I did a quick search and it seems they do support this kind of view with something called `AppodealNativeAdView`. I don't know if that's exactly what you need but you can find it here: https://github.com/appodeal/appodeal-ios-demo/wiki/Native-Ads-integration#show-native-ads-by-usage-default-templates
