### ISSUE TITLE
Show login screen before startTabBasedApp?

### ISSUE THREAD

**Issue by paynestrike** [wix/react-native-navigation#1442]
### Is it possible to show a login screen before startTabBasedApp?

Sure I can show login modal screen by using componentDidMount method of first tab screen, but in this case first tab will always show up first then login screen. Is there a better way to achieve this? Like show login before even call startTabBasedApp?

**Comment by carlosroberto555** [comment]
You can **startSingleScreenApp** with login screen, if is logged **startTabBasedApp**

**Comment by rvpyrv** [comment]
@carlosroberto555 can you give an example of conditionally switching between single and tabBased apps?

**Comment by omar-dev** [comment]
@rvpyrv you can find an example on the [old-example-redux](https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js)

**Comment by jurajkrivda** [comment]
You might have Login component as part of the startTabBasedApp and view this login as modal if you are not logged in.
