### ISSUE TITLE
resetTo animation direction

### ISSUE THREAD

**Issue by damathryx** [wix/react-native-navigation#1445]
### Issue Description
So i just started working with react-native-navigation and I am building a simple login logout with it. After you login you can click logout using resetTo for it but I don't know how to change resetTo direction and it should slide to left. I tried `animationType: 'slide-left` not working. I checked the docs, i couldn't find it. I apologize if I have missed it.

### Environment
* React Native Navigation version: 1.1.113
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by swimly** [comment]
You can use animationType: 'slide-horizontal'

**Comment by wellyal** [comment]
@swimly I don't think you understood the issue here. What hes trying to do is to make the slide horizontal animate to left, since is always animating to right side.

**Comment by ncnlinh** [comment]
Yes the direction is going forwards, we need an option to make it have a backwards animation

**Comment by xvonabur** [comment]
I would like to see that option too.

**Comment by andrewzey** [comment]
This is a huge problem, any idea about prioritizing this?

**Comment by guyca** [comment]
Custom animations are [in the works for v2](https://github.com/wix/react-native-navigation/issues/2435)
I'm closing the issue is we don't have the capacity to address it in v1.
