### ISSUE TITLE
[iOS] Subtitle doesn't sets in push as a param or in the constructor

### ISSUE THREAD

**Issue by terrysahaidak** [wix/react-native-navigation#1447]
### Issue Description

Just tried to use subtitle on ios and get into two issues.
1. When I trying to set subtitle via passing as a param to `push` or dynamically in the constructor it doesn't work. Nothing happens. But then I use `setTimeout` in the constructor it sets up but with an issue (point 2).
2. Doesn't matter which color I set in `navigatorStyle`'s `navBarSubtitleColor` it always black. It works only when a `setStyle`with `setTimeout`.

On android everything works as expected.

### Steps to Reproduce / Code Snippets / Screenshots

1. Push the screen with some `subtitle` param.
2. Try to set it dynamically in the constructor 
```
    this.props.navigator.setSubTitle({
      subtitle: 'Testing...'
    })
```
3. Try to use `setTimeout` in constructor
```
    setTimeout(() => this.props.navigator.setSubTitle({
      subtitle: 'Testing...'
    }), 1000)
```
4. Try to set different color from black in `navigatorStyle`'s `navBarSubtitleColor`.
5. Try to `setStyle` with `setTimeout`
```
  setTimeout(() => this.props.navigator.setStyle({
      navBarSubtitleColor: '#FFFFFF'
    }), 1000)
```
6. Make sure every step described above works on Android well.

---
### Environment
* React Native Navigation version: 1.1.125
* React Native version: 44.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, debug

**Comment by carlosroberto555** [comment]
Try to call on **componentDidMount()**

**Comment by guyca** [comment]
I'm closing this one as it seems no one else is experiencing this issue. If it's still relevant, please reopen and add more information.
