### ISSUE TITLE
[Android] - Crash apps

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#1449]
### Issue Description

Hi all,
I have this problem when run app on android.

### Steps to Reproduce / Code Snippets / Screenshots

<img width="1158" alt="screen shot 2017-07-03 at 9 44 05 am" src="https://user-images.githubusercontent.com/19372005/27776431-acc8fa7c-5fd4-11e7-8e38-ee79f42672c1.png">

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: "^1.1.131"
* React Native version: "0.45.1"
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Only test Device/Debug

**Comment by carlosroberto555** [comment]
Did you folow the Android installation steps?
[https://wix.github.io/react-native-navigation/#/installation-android](https://wix.github.io/react-native-navigation/#/installation-android)

**Comment by agumack** [comment]
@carlosroberto555 I checked all step setting. : (

**Comment by agumack** [comment]
@carlosroberto555 

I detect this error when integrate https://github.com/facebook/react-native-fbsdk

Do you know why? Thanks so much.


`E/UncaughtException(23129): java.lang.RuntimeException: Unable to resume activity {com.guapp/com.guapp.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
E/UncaughtException(23129): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2798)
E/UncaughtException(23129): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2827)
E/UncaughtException(23129): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
E/UncaughtException(23129): 	at android.app.ActivityThread.access$900(ActivityThread.java:141)
E/UncaughtException(23129): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
E/UncaughtException(23129): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/UncaughtException(23129): 	at android.os.Looper.loop(Looper.java:136)
E/UncaughtException(23129): 	at android.app.ActivityThread.main(ActivityThread.java:5072)
E/UncaughtException(23129): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/UncaughtException(23129): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/UncaughtException(23129): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/UncaughtException(23129): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
E/UncaughtException(23129): 	at dalvik.system.NativeStart.main(Native Method)
E/UncaughtException(23129): Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
E/UncaughtException(23129): 	at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:79)
E/UncaughtException(23129): 	at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:336)
E/UncaughtException(23129): 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:233)
E/UncaughtException(23129): 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84)
E/UncaughtException(23129): 	at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.createReactInstanceManager(NavigationReactGateway.java:145)
E/UncaughtException(23129): 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
E/UncaughtException(23129): 	at com.reactnativenavigation.react.NavigationReactGateway.getReactInstanceManager(NavigationReactGateway.java:59)
E/UncaughtException(23129): 	at com.reactnativenavigation.react.NavigationReactGateway.hasStartedCreatingContext(NavigationReactGateway.java:46)
E/UncaughtException(23129): 	at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:28)
E/UncaughtException(23129): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
E/UncaughtException(23129): 	at android.app.Activity.performResume(Activity.java:5328)
E/UncaughtException(23129): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2788)
E/UncaughtException(23129): 	... 12 more
E/UncaughtException(23129): Caused by: java.lang.reflect.InvocationTargetException
E/UncaughtException(23129): 	at java.lang.reflect.Constructor.constructNative(Native Method)
E/UncaughtException(23129): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/UncaughtException(23129): 	at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:72)
E/UncaughtException(23129): 	... 23 more
E/UncaughtException(23129): Caused by: java.lang.NoClassDefFoundError: okhttp3.internal.Util
E/UncaughtException(23129): 	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:118)
E/UncaughtException(23129): 	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:423)
E/UncaughtException(23129): 	at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:118)
E/UncaughtException(23129): 	at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:193)
E/UncaughtException(23129): 	... 26 more
E/AndroidRuntime(23129): FATAL EXCEPTION: main
E/AndroidRuntime(23129): Process: com.guapp, PID: 23129
E/AndroidRuntime(23129): java.lang.RuntimeException: Unable to resume activity {com.guapp/com.guapp.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
E/AndroidRuntime(23129): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2798)
E/AndroidRuntime(23129): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2827)
E/AndroidRuntime(23129): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
E/AndroidRuntime(23129): 	at android.app.ActivityThread.access$900(ActivityThread.java:141)
E/AndroidRuntime(23129): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
E/AndroidRuntime(23129): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(23129): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(23129): 	at android.app.ActivityThread.main(ActivityThread.java:5072)
E/AndroidRuntime(23129): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(23129): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(23129): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime(23129): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
E/AndroidRuntime(23129): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(23129): Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
E/AndroidRuntime(23129): 	at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:79)
E/AndroidRuntime(23129): 	at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:336)
E/AndroidRuntime(23129): 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:233)
E/AndroidRuntime(23129): 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84)
E/AndroidRuntime(23129): 	at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.createReactInstanceManager(NavigationReactGateway.java:145)
E/AndroidRuntime(23129): 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
E/AndroidRuntime(23129): 	at com.reactnativenavigation.react.NavigationReactGateway.getReactInstanceManager(NavigationReactGateway.java:59)
E/AndroidRuntime(23129): 	at com.reactnativenavigation.react.NavigationReactGateway.hasStartedCreatingContext(NavigationReactGateway.java:46)
E/AndroidRuntime(23129): 	at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:28)
E/AndroidRuntime(23129): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
E/AndroidRuntime(23129): 	at android.app.Activity.performResume(Activity.java:5328)
E/AndroidRuntime(23129): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2788)
E/AndroidRuntime(23129): 	... 12 more
E/AndroidRuntime(23129): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(23129): 	at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime(23129): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime(23129): 	at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:72)
E/AndroidRuntime(23129): 	... 23 more
E/AndroidRuntime(23129): Caused by: java.lang.NoClassDefFoundError: okhttp3.internal.Util
E/AndroidRuntime(23129): 	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:118)
E/AndroidRuntime(23129): 	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:423)
E/AndroidRuntime(23129): 	at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:118)
E/AndroidRuntime(23129): 	at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:193)
E/AndroidRuntime(23129): 	... 26 more
`

**Comment by Blue-Lan** [comment]
I have the same issue, on Android 4.x.x, it seems that this error was caused by onResume in SplashActivity.java

**Comment by teyou** [comment]
i encountered the exact issue.. any advise?

**Comment by Cholern** [comment]
I solved it by change `extends Application` to `extends MultiDexApplication` in NavigationApplication.java

**Comment by vishaljadav24** [comment]
Thanks, @Cholern . It's work like a charm.

**Comment by BrotherWY** [comment]
@Cholern  so cool
