### ISSUE TITLE
app hang 

### ISSUE THREAD

**Issue by a289459798** [wix/react-native-navigation#1451]
### Issue Description

App retreated to the background after open, open for a long time again, is easy to appear white, after debugging found performed "render" method, may be is a question of native code

---
### Environment
* React Native Navigation version: 1.1.12
* React Native version: 0.43
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by sunny635533** [comment]
+1，has someone know how solved it ?
