### ISSUE TITLE
Navigation between tabs

### ISSUE THREAD

**Issue by ivangrga** [wix/react-native-navigation#1452]
### Issue Description

Unable to turn on animations when switching between tabs (app initiated with startTabBasedApp()).
---
### Environment
* React Native Navigation version: 1.1.115
* React Native version: 0.44.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Xcode iPhone 6 Simulator

**Comment by guyca** [comment]
There is no animation when switching bottom tabs. The transition is instant

**Comment by ivangrga** [comment]
To bad, it would be nice feature, but all in all this is best react-native nav module so far.
