### ISSUE TITLE
BottomTabs move above keyboard when selecting TextInput inside ScrollView

### ISSUE THREAD

**Issue by TimoGlastra** [wix/react-native-navigation#1454]
### Issue Description

When using a tabBasedApp with BottomTabs and you have an TextInput in a ScrollView the BottomTabs will move up with the keyboard if the TextInput gets focussed. This only happens when you have switched tabs in the current loaded app.

### Steps to Reproduce / Code Snippets / Screenshots
To reproduce start a tabBasedApp with BottomTabs and in one of the tabs place an ScrollView with an TextInput inside of it. If the TextInput gets focussed the BottomTabs will move above the keyboard. But this only happens when you have switched tabs (so if you start the app and the TextInput inside the ScrollView is on the first tab it won't happen).

I have attached two pictures with what should happen(i think) and what happens with the bugged BottomTabs.

---
### Environment
* React Native Navigation version: 1.1.115 and 1.1.133 (thought upgrading might help)
* React Native version: 0.45
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device: Motorola Moto G3, Android 6.0.1, Tested with __DEV__ turned on and off

![What should happen](https://user-images.githubusercontent.com/23165168/27808782-9c99a7ac-604a-11e7-900e-8edb70bd1e0b.png)
![Picture with bugged BottomTabs](https://user-images.githubusercontent.com/23165168/27808767-810e668a-604a-11e7-8127-0be6f493621b.png)

**Comment by guyca** [comment]
Hey, You need to [toggleTabs](https://wix.github.io/react-native-navigation/#/screen-api?id=toggletabsparams-) when the TextView receives focus.

**Comment by TimoGlastra** [comment]
alright. But why does this not happen when i haven't switched tabs or the TextInput is not inside a ScrollView? That was the reason i thought it was an bug. But thanks anyway

**Comment by felipemartim** [comment]
I used toggleTabs on Keyboard listeners instead of relying on focus/blur of text inputs and it seems to be working well.
