### ISSUE TITLE
[Android] Navigator not working with react-native-camera

### ISSUE THREAD

**Issue by steve228uk** [wix/react-native-navigation#1458]
### Issue Description

I'm currently using the [`react-native-camera`]() package to scan barcodes and I'm calling the navigator to present a new screen. The navigator does get called and it works perfectly on iOS, however on Android it doesn't and stays on the current page.

I understand this may actually be an issue with `react-native-camera` and I may open an issue on their repo too.

### Screenshot

Here's a screenshot of the chrome dev tools.

<img width="942" alt="screen shot 2017-07-04 at 16 25 50" src="https://user-images.githubusercontent.com/1169297/27836196-4c03153a-60d6-11e7-81cb-ec38dcd3a92c.png">

---
### Environment
* React Native Navigation version: 1.1
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device + Simulator

**Comment by chrisdukey** [comment]
Take a look at [react-native-barcode-scanner-universal](https://www.npmjs.com/package/react-native-barcode-scanner-universal). It uses `react-native-camera` for IOS and `react-native-barcodescanner` for Android. I'm using it with RNN on Android and it's working nicely.

**Comment by guyca** [comment]
Hey @steve228uk 
Did you find a solution to the issue? I'm not entirely sure what you meant by the navigator not being called on Android.

**Comment by steve228uk** [comment]
@guyca Sorry, probably wasn't clear enough. Essentially the the `navigator.push()` method is called and shows the next screen perfectly on iOS whereas on Android it remains on the current screen. From the console I can see the the method is called correctly but the action isn't completed.

**Comment by steve228uk** [comment]
@chrisdukey I was using this previously but it's officially deprecated by the project maintainer in preference for `react-native-camera` so ideally I wouldn't want to use this in a production project.

**Comment by chrisdukey** [comment]
@steve228uk  Sorry, didn't realise that. Must have happened since I started using it. Guess I may have to switch back to `react-native-camera`
