### ISSUE TITLE
Nested scenes support?

### ISSUE THREAD

**Issue by aksonov** [wix/react-native-navigation#146]
I have one scene with own tab bar, how i could achieve that? Is it possible to nest tab navigators?

**Comment by guyca** [comment]
Hey @aksonov, Could you please clarify your question?

**Comment by aksonov** [comment]
Okey app has three tabs with scenes A, B, C. Scene B has own three tabs B1, B2 and B3.

**Comment by agumack** [comment]
@aksonov you can use https://github.com/ArnaudRinquin/react-native-radio-buttons for this case

**Comment by aksonov** [comment]
Hm... I don't need radio buttons, i need real hierarchical structure like native iOS has. Drawer represents first layer of 'tabs', that each tab could contain TabBar, for example.

**Comment by guyca** [comment]
@aksonov 
We're not going to support this use case. By definition, bottom tabs are used to navigate between top level views. For the use case you described, I suggest you either use [tabs](https://material.google.com/components/tabs.html) or a JS implementation of bottom tabs.

**Comment by aksonov** [comment]
Are you giving link to android or cross platform component? Why just don't pass hidden style to tab bar? I've submitted PR for that for RN controllers already

Pavel.

**Comment by guyca** [comment]
Hey Pavel
The iOS Controller corresponding to Android Tabs is [Segmented Controller](https://developer.apple.com/library/prerelease/content/documentation/UserExperience/Conceptual/UIKitUICatalog/UISegmentedControl.html) and we're going add support to both components (`Segmented Controller` and `TabLayout` in `AppBar`) in the upcoming releases.

`TabLayout` should be available in version 2.0 on Android. For iOS, we're using [react-native-custom-segmented-control](https://github.com/wix/react-native-custom-segmented-control) in our apps and we're going to merge this project into `react-native-navigation` so it will be easier to support both components.

I hope this helps you.
