### ISSUE TITLE
[Screen API] Behavior of resetTo() is not right

### ISSUE THREAD

**Issue by canhnht** [wix/react-native-navigation#1462]
### Issue Description

I have an app using drawer navigation. When user clicks on a menu item in Drawer, navigator will `resetTo()` that screen. I tried `this.props.navigator.resetTo()` in `Drawer` class, but it only works in Android, **not in iOS**.

### Steps to Reproduce / Code Snippets / Screenshots

So I tried again from scratch with a new React Native app. 
Here is my small example for demonstrating behavior of `resetTo()` in **iOS**.

```js
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Button
} from 'react-native';
import { Navigation} from 'react-native-navigation';

export default class doit extends Component {
  openScreen1() {
    // THIS WILL WORK
    this.props.navigator.resetTo({
      screen: 'Screen1',
      title: 'S1'
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
        <Button onPress={() => this.openScreen1()} title="Learn More" />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

class Screen1 extends Component {
  render() {
    return (
      <View>
        <Text>Screen 1</Text>
      </View>
    )
  }
}

class Drawer extends Component {
  goScreen1() {
    // THIS WILL NOT WORK!!!
    this.props.navigator.resetTo({
      screen: 'Screen1',
      title: 'S1'
    });
  }

  render() {
    return (
      <View>
        <Button title="Go Screen 1" onPress={() => this.goScreen1()} />
      </View>
    )
  }
}



// ============================
Navigation.registerComponent('doit', () => doit);
Navigation.registerComponent('Screen1', () => Screen1);
Navigation.registerComponent('Drawer', () => Drawer);

Navigation.startSingleScreenApp({
	screen: {
		screen: 'doit',
		title: 'Dooo It'
	},
  drawer: {
    left: {
      screen: 'Drawer'
    }
  }
});
```

From this example, I find that in iOS `resetTo()` will not work with `props.navigator` in `Drawer` but in root screen. Maybe that's how `resetTo()` work, but it's not documented and I think it's kinda weird.

For iOS, I prefer to use `resetTo()` even in Drawer or in root screen. Hope someone can help fix this.

For anyone stuck with current behavior of `resetTo()`, my workaround for it to work on both Android and iOS is creating a global service that notify the root screen to `resetTo()` when the drawer menu item is selected. Because we need a way to communicate between multiple screens (Drawer and rootScreen). Hope it helps.

I also want to request to demo `resetTo` in [movieapp](https://github.com/JuneDomingo/movieapp). Hope someone can help build this. Thanks

---
### Environment
* React Native Navigation version: 1.1.133
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6, Debug

**Comment by guyca** [comment]
Hey there
You shouldn't user navigation methods of the drawer's navigator. Instead, use [deeplinks](https://wix.github.io/react-native-navigation/#/deep-links) and broadcast events that represent navigation change and handle them in the appropriate screens.

The reason behind this limitation is that the developer expects that calling navigation methods (push/pop/resetTo) would perform on the current navigation stack. But RNN has no way to guarantee that your action would be executed on the navigation stack you've intended since the stack can change before the action is executed.

In v2, you'd be able to perform such action without deeplinks, by specifying the id of the screen/tab you want to action to apply on.

**Comment by tmaly1980** [comment]
@guyca I don't understand what you mean by "RNN has no way to guarantee that your action would be executed on the navigation stack you've intended since the stack can change before the action is executed." 

What I was able to observe though is that my single screen and my drawer had separate instances of the Navigator, rather than sharing the same. I see two AppContainer's in my tree, one for the single screen, one for the drawer.

**Comment by tmaly1980** [comment]
@guyca I tried copying the code here: https://github.com/junedomingo/movieapp/blob/feature/similar-movies/src/modules/_global/Drawer.js

But it doesn't work, how come?

**Comment by realtebo** [comment]
In this example: https://wix.github.io/react-native-navigation/#/deep-links?id=handling-deep-links 

```
export default class SecondTabScreen extends Component {
  constructor(props) {
    super(props);
    // if you want to listen on navigator events, set this up
    this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
  }
  onNavigatorEvent(event) {
    // handle a deep link
    if (event.type == 'DeepLink') {
      const parts = event.link.split('/'); // Link parts
      const payload = event.payload; // (optional) The payload

      if (parts[0] == 'tab2') {
        // handle the link somehow, usually run a this.props.navigator command
      }
    }
  }
```

When my Screen Intercept that a deepLink is for itself, how do I popToRoot if popToRoot do not works on IOS?
