### ISSUE TITLE
Android drawer behind status bar

### ISSUE THREAD

**Issue by mannol** [wix/react-native-navigation#1464]
The effect, better described in [this](https://stackoverflow.com/questions/26913770/make-navigation-drawer-draw-behind-status-bar) SO question, cannot be achieved using React Native Navigation. It would be nice to have a translucent status bar option, that plays nicely with the navBar. On a side note, do you have any quick workaround for this?

**Comment by Ehesp** [comment]
If you set `statusBarColor: 'rgba(0, 0, 0, 0)'` and `statusBarHidden: true`, what effect does this have?

**Comment by mannol** [comment]
Only the status bar color changes:
Before:
![Before](https://user-images.githubusercontent.com/13100554/27905166-6859ea3c-623f-11e7-9806-90e42ca91440.png)
After:
![After](https://user-images.githubusercontent.com/13100554/27905165-6857d774-623f-11e7-8edb-113e55c137f2.png)

**Comment by Ehesp** [comment]
Hmm I'm not sure this is possible sorry. There are plans for immersive mode on Android but they're yet to be implemented.

**Comment by mannol** [comment]
No [need](https://stackoverflow.com/a/26952242/5220037) for immersive mode, this can be done by setting android:windowTranslucentStatus to true. It's only the problem with layout really. Layout should be padded to status bar height except for the drawer. Then, that padded height would be filled with statusBarColor property. I'm not very familiar with RNN code but it should be fairly easy to do.

**Comment by sijad** [comment]
this can be achieve by `android:windowTranslucentStatus to true` and set padding top of `TitleBar` to `navBarHeight` (default is 70), can I send a PR?

**Comment by laiyifeng77** [comment]
have a translucent status bar option is needed.

**Comment by Aaron-Davison** [comment]
@sijad How did you manage to set the TitleBar padding? I can't seem to find where to do this anywhere. Thanks

**Comment by sijad** [comment]
@Aaron-Davison for now:

edit `node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java` and append `setPadding(0, 70, 0, 0);` to `setStyle` method.

it's not compatible with Lightbox and modal view.

**Comment by Aaron-Davison** [comment]
For anyone who is having this issue. There is now a new update which allows the padding to be set in the Navigation Style.
e.g.
`static navigatorStyle = {
        navBarTopPadding: 24
    };`

See Pull Request [2266](https://github.com/wix/react-native-navigation/pull/2266)
