### ISSUE TITLE
Pushing screen from drawer crashes the app

### ISSUE THREAD

**Issue by mannol** [wix/react-native-navigation#1465]
### Issue Description
Every time I try to push a screen from the drawer, the app crashes. The same screen is pushed correctly by using navigator of existing screen or tab.

**EDIT:**
It works with single screen apps: Navigation.startSingleScreenApp({});

**EDIT2:**
This is the java backtrace:
```
07-05 17:22:07.034  7536  7589 W ReactNativeJS: {"navigatorID":"navigatorID11_nav","screenInstanceID":"screenInstanceID12","navigatorEventID":"screenInstanceID12_events","navigatorEventHandler":null,"navigatorEventSubscription":null}
07-05 17:22:07.056  7536  7536 E AndroidRuntime: FATAL EXCEPTION: main
07-05 17:22:07.056  7536  7536 E AndroidRuntime: Process: com.project, PID: 7536
07-05 17:22:07.056  7536  7536 E AndroidRuntime: com.reactnativenavigation.layouts.BottomTabsLayout$ScreenStackNotFoundException: Stack navigatorID11_nav not found
07-05 17:22:07.056  7536  7536 E AndroidRuntime: 	at com.reactnativenavigation.layouts.BottomTabsLayout.getScreenStackIndex(BottomTabsLayout.java:459)
07-05 17:22:07.056  7536  7536 E AndroidRuntime: 	at com.reactnativenavigation.layouts.BottomTabsLayout.getScreenStack(BottomTabsLayout.java:433)
07-05 17:22:07.056  7536  7536 E AndroidRuntime: 	at com.reactnativenavigation.layouts.BottomTabsLayout.push(BottomTabsLayout.java:320)
07-05 17:22:07.056  7536  7536 E AndroidRuntime: 	at com.reactnativenavigation.controllers.NavigationActivity.push(NavigationActivity.java:210)
07-05 17:22:07.056  7536  7536 E AndroidRuntime: 	at com.reactnativenavigation.controllers.NavigationCommandsHandler$1.run(NavigationCommandsHandler.java:58)
07-05 17:22:07.056  7536  7536 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:761)
07-05 17:22:07.056  7536  7536 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-05 17:22:07.056  7536  7536 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:156)
07-05 17:22:07.056  7536  7536 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
07-05 17:22:07.056  7536  7536 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-05 17:22:07.056  7536  7536 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
07-05 17:22:07.056  7536  7536 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

### Steps to Reproduce 

Start tab-based app with a left drawer:
`Navigation.startTabBasedApp({});`

Now slide-open the drawer and try to push the screen:
```
this.props.navigator.push({
  screen: "screen.SomeScreen"
});
```

---
### Environment
* React Native Navigation version: 1.1.108
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device - Android 7.0 - Debug

**Comment by mannol** [comment]
Welp, I've found a `workaround` this issue:

- In a constructor() of some root tab call the following:
`global.navigator = this.props.navigator`
- Now use that to push screens from drawer instead of drawers navigator:
`global.navigator.push({ ... })`

**Comment by guyca** [comment]
Hey @mannol 
As you've noticed - it's not possible to push from the drawer. A lot of users expect that calling `navigator.push` from the drawer would push into the currently visible stack but the stack can change unexpectedly (some other component calls `switchToTab` while the drawer is open for example). Since the behaviour can be unexpected we recommend using deep links.
