### ISSUE TITLE
SharedElementTransition bug - screen which is source and destination of a shared element 

### ISSUE THREAD

**Issue by ramneekhanda** [wix/react-native-navigation#1467]
### Issue Description

I have a simple app - 
screen a which has shared element "atransitionb" which transitions to screen b
screen b has a sharedlelementtransion called "atransitionb" and "btransitionc" which transitions to screen c.

i get 
07-05 16:15:25.691 14039 14039 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View com.reactnativenavigation.views.sharedElementTransition.SharedElementTransition.getSharedView()' on a null object reference

**Comment by guyca** [comment]
Seems like one of the views is missing `sharedElementId` or has a wrong id defined.
