### ISSUE TITLE
Hide TabBar entirely

### ISSUE THREAD

**Issue by aksonov** [wix/react-native-navigation#147]
I don't need tab bar icons because i'm using drawer (so i need tab views), so how to hide tab bar for initial scene?

**Comment by guyca** [comment]
You can use `Navigation.startSingleScreenApp`

**Comment by aksonov** [comment]
No, i need TabBar, but hidden. Anyway I've submitted PR already.

**Comment by aksonov** [comment]
PR for react-native-controllers component.

**Comment by michaelknoch** [comment]
is it possible to start with `Navigation.startSingleScreenApp` and have a tabBar as childView somewhere? @aksonov @guyca

**Comment by guyca** [comment]
@michaelknoch You can add a js based tab bar to any screen in jsx.

**Comment by michaelknoch** [comment]
did i have to implement the js tabs by myself, or can i import and render the tabbar from wix/navigation?

**Comment by guyca** [comment]
You'll need to implement it your self and add it to each screen. We plan to make the library more pluggable and in the future we'll probably expose an interface which will allow developers to easily  provide their own BottomTabs implementations.

**Comment by michaelknoch** [comment]
this will look quite strange when animating between views, right?
I will always see a new tabbar animating onto the tabbar of the previous screen.
@guyca

**Comment by guyca** [comment]
@michaelknoch When user clicks a tab button (In your custom BottomTabs), you can call `resetTo` with out animation to reset the stack to the new screen.
You might run into issues on iOS with screen flickering so I don't recommend going this way. 😕

**Comment by michaelknoch** [comment]
We are currently investigating whether it is possible to render the Login/Register/Onboarding views as Modals on top of our "normal" tabbar based app. Doesn't look that bad so far. What are your thoughts about this approach? @guyca

**Comment by guyca** [comment]
We show login/onboarding flows in a singleScreenApp - when these flows complete we call `startTabBasedApp` and open the actual app.
Showing modal might work, how do you handle modal dismiss? If user isn't logged in and the login modal is displayed, if user dismisses modal - what is displayed?

**Comment by michaelknoch** [comment]
so it might be possible to switch between these app contexts by calling **startSingleScreenApp** --> for the login, and **startTabBasedApp** for the "main" app? Additionally its possible to call startSingleScreenApp again, when a user presses a logout button for example?
I am very grateful for your help @guyca

**Comment by guyca** [comment]
You can call `start*App` whenever you need to, The Wix app is tab based and we handle login and on boarding in a singleScreenApp - once these are done we call `startTabBasedApp` and show the actual app.
