### ISSUE TITLE
How to close the lightbox/modal by clicking on its overlay? 

### ISSUE THREAD

**Issue by rvpyrv** [wix/react-native-navigation#1470]
I have a lightbox, 100x100 px centered.
I want to close it by clicking on overlay, and not by dismissModal / Lightbox
How to achieve this?

**Comment by rvpyrv** [comment]
Sorry for wasting time to read this. I am so inattentive, while reading documentation.

tapBackgroundToDismiss.

**Comment by ppozniak** [comment]
@rvpyrv sorry to bother, but I wanted to ask the same question, and there is no property `tapBackgroundToDismiss` in the docs, nor it is working.
https://wix.github.io/react-native-navigation/#/screen-api?id=showlightboxparams-
