### ISSUE TITLE
no push method in navigator object

### ISSUE THREAD

**Issue by iwater** [wix/react-native-navigation#1471]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots
1.start app using Navigation.startSingleScreenApp
2.in screen component there is no push method in navigator object
<img width="588" alt="2017-07-07 11 07 24" src="https://user-images.githubusercontent.com/108937/27941732-b7f7e77c-6304-11e7-9591-c0c70bf1f8ca.png">

---
### Environment
* React Native Navigation version: 1.1.134
* React Native version: 0.46.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator 10.3 Debug

**Comment by birkir** [comment]
It's in the prototype (__proto__)
