### ISSUE TITLE
only showModal working

### ISSUE THREAD

**Issue by ahm-hossein** [wix/react-native-navigation#1473]
### Issue Description
I have a strange issue with navigation in my app. at the first step of app the push and resetTo methods works fine but when I reset the navigation to main page the push/resetTo methods not working anymore and only showModal works.

### Steps to Reproduce / Code Snippets / Screenshots
this is my app.js :
`
   registerScreens( store, Provider );
   const navigatorStyle = {
	navBarHidden: true
    };
    Navigation.startSingleScreenApp({
	screen: {
		screen: 'com.alopeyk.courier.SplashScreen',
		title: 'SplashScreen',
		navigatorStyle
	},
    });
`

---
### Environment
* React Native Navigation version: 1.1.134
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung android version 6

**Comment by guyca** [comment]
showModal can be called statically from `Navigation`. Most other navigation methods (such as push or pop) are invoked from `navigator` instance obtained from props.
https://wix.github.io/react-native-navigation/#/screen-api

**Comment by ahm-hossein** [comment]
thanks for your quick response. I'm using the navigator instance in the props and not able to push or resetTo. also I have a Navigator class that responsible for navigate from outside of component navigations.

**Comment by guyca** [comment]
Does the screen you push/resetTo render any views? does the root view have a background?
On Android, screens are pushed only when their root view is created.

**Comment by loopingz** [comment]
I have the same issue, but only on ios
