### ISSUE TITLE
Drawer ignoring navigatorStyle

### ISSUE THREAD

**Issue by michael-noetic** [wix/react-native-navigation#1475]
I've just added a drawer to my app, but it does not appear to acknowledge the navigatorStyle. 

Here is the top of my landing page:
![simulator screen shot 7 jul 2017 16 38 18](https://user-images.githubusercontent.com/27958844/27965938-5548d9f2-6335-11e7-862c-fd545e376ed7.png)
And the same component used as a drawer:
![simulator screen shot 7 jul 2017 16 38 29](https://user-images.githubusercontent.com/27958844/27965961-6f12b0ba-6335-11e7-8062-b2e66dd9c64c.png)

App initialisation:
```
Navigation.startSingleScreenApp({
        screen: { screen: "landing.LandingScreen" },
        drawer: {
            right: { screen: "landing.LandingScreen"}
        }
    });
```
From the class definition:
```
static navigatorStyle = {
    screenBackgroundColor: colours.primaryDark,
    statusBarTextColorScheme: "light",
    navBarHidden: true
}
```

It looks like the drawer has its own navigatorStyle, because the nav which is displayed by default doesn't appear. My main problem is keeping IOS' DeviceStatusBar light when I open the drawer. 

Nothing in the docs suggests any special drawer-style property.

* React Native Navigation version: 1.1.134
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): IOS Simulator

**Comment by michael-noetic** [comment]
So I've noticed in the code that you can pass a style prop to the drawer when starting the app, which is passed to the `DrawerControllerIOS` component (src/deprecated/platformSpecificDeprecated.ios.js, line 58).

Going a bit deeper, I've also tried calling `RCCManager.DrawerControllerIOS(id, "setStyle", params);` (src/deprecated/controllers/index.js, line 234).

Neither of these have had any effect though. 

Has anyone else had this problem? I can't see anything wrong with the JS, so I'm guess it's a problem in the native code. Could it be related to my install or the simulator?

Thanks

**Comment by Geminika** [comment]
I'm having the same problem.
I there any solution for this ?

**Comment by michael-noetic** [comment]
I never found one; I ended up abandoning this library, and replaced it with react-navigation + react-native-side-menu. 

I got stuck on this problem as well as a few other bugs. It was also a bit too inflexible.

**Comment by c0d3blooded** [comment]
Strangely, I noticed this to be an issue with startSingleScreenApp but not startTabBasedApp.

**Comment by rodrigobdz** [comment]
@c0d3blooded I'm having the issue as well with the `startSingleScreenApp` API.
Could you get around this one?
