### ISSUE TITLE
Side Menu not work sometime

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#1479]
### Issue Description

The side menu sometime get hanged and the open button do nothing, I have some errors from the monitor, I think it's related:

![capture](https://user-images.githubusercontent.com/1522682/27996336-b272d416-64e8-11e7-91c9-6fb7abc08d91.PNG)

### Steps to Reproduce / Code Snippets / Screenshots

Randomly, I noticed that after installing react-native-fbsdk

---
### Environment
* React Native Navigation version: ^1.1.134
* React Native version: ^0.46.0
* Platform(s) (iOS, Android, or both?): Tested on Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator and real device, both, OS 6

**Comment by Jaafar-abusair** [comment]
More info:

I noticed if i have code that call API in the home page, the side menu button stuck after that, if I commented that code, the side menu will work as expected

**Comment by guyca** [comment]
Hey @Jaafar-abusair 
How are you opening the SideMenu? Are you using [toggleDrawer](https://wix.github.io/react-native-navigation/#/screen-api?id=toggledrawerparams-)?

**Comment by Jaafar-abusair** [comment]
No just by clicking on the side menu button, I tried toggleDrawer too, but it didn't work

**Comment by guyca** [comment]
If you're using the default menu button (defined with `id: 'sideMenu'`) then I'm not sure what can cause a delay or flakiness with the menu since RN and JS aren't involved in displaying the menu.

**Comment by Jaafar-abusair** [comment]
Yes, this is what im using and its confusing me,  any idea how to debug it?

**Comment by guyca** [comment]
You can try debugging the button [click](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/views/LeftButton.java#L55).
How often does this issue occur?

**Comment by Jaafar-abusair** [comment]
SingleScreenLayout: onSideMenuButtonClick => called
SingleScreenLayout: onSideMenuButtonClick : sideMenu.openDrawer(Side.Left);  => called
SideMenu: openDrawer => called
SideMenu: openDrawer : openDrawer with gravity 3 (left) => called

result: nothing happened and the drawer didn't open

**Comment by Jaafar-abusair** [comment]
I put my fetch function inside a timeout 2 seconds, and the side menu worked as expected, is it related to thread intervention

**Comment by beerteam** [comment]
I have same problem when updated to RN 0.46.

**Comment by Jaafar-abusair** [comment]
@beerteam i solved it by react-native-timer for now till they fix it

**Comment by beerteam** [comment]
@Jaafar-abusair please give me some code from your fix. I have bug with toggleDrawer and with native SideMenu button.

**Comment by Jaafar-abusair** [comment]
Sorry replaying from mobile...  If you have any code fetch data from backend import react-native-timer and use setTimer after two seconds to call the fetch

**Comment by beerteam** [comment]
@Jaafar-abusair I do downgrade to 0.45.1 and not have bug again. But need more testing.

**Comment by Jaafar-abusair** [comment]
@beerteam  yes it worked for me after downgrade to 0.45.1, so it's related to react-native, @guyca  i will close the ticket
