### ISSUE TITLE
[Android] icon size too big

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#148]
Hi all,

I have problem with icon on android. I test icon image and iconvector both, seem size not apply. 
I too big. Anyone have same problem?

**Comment by guyca** [comment]
hey @agumack Are you referring to icons in Toolbar?

**Comment by agumack** [comment]
yes @guyca I follow this guide: https://gist.github.com/dropfen/4a2209d7274788027f782e8655be198f

(TabIcon Ok, only problem with Toolbar)

**Comment by guyca** [comment]
Hey @agumack are you seeing these issues in release or debug?
