### ISSUE TITLE
how to set launchOptions in android?

### ISSUE THREAD

**Issue by sunny635533** [wix/react-native-navigation#1481]
### Issue Description
we know this navigation must  extends SplashActivity,so i want to know how to set my launchOptions in android,just like that:
` @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            protected Bundle getLaunchOptions() {
                Bundle b = new Bundle();
                System.out.println("====envName="+ BuildConfig.FLAVOR);
                b.putString("envName", BuildConfig.FLAVOR);
                return b;
            }
        };
    }`

i checked the navgation codes ,then found it haven't use ReactActivityDelegate ,like that `catalystInstance.getJSModule(AppRegistry.class).runApplication(jsAppModuleName, appParams);`.
please tell how to init my launchOptions in android?
### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.134
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?):

**Comment by guyca** [comment]
Hey there
As you've noticed, RNN starts its own activity - `NavigationActivity`. If you like to use your own Activity, there's an undocumented workaround that you could use:

```java
public class MainApplication extends NavigationApplication {

    @Override
    public void startActivity(Intent intent) {
        intent.setClass(this, MyNavigationActivity.class); // <-- Set you own Activity
        super.startActivity(intent);
    }

    @Override
    public boolean isDebug() {
        return BuildConfig.DEBUG;
    }

    @Nullable
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return null;
    }
```

```java
// Don't forget to register your Activity in AndroidManifest.
public class MyNavigationActivity extends NavigationActivity {

}
```

Hope this answers your question.

**Comment by sunny635533** [comment]
@guyca Though i have own Activity, i still cann't push my launchOptions (such as android environment 'dev' or 'production') to AppRegistry. I want to get some params from AppRegistry when i register RN's component.

**Comment by guyca** [comment]
If I understand you correctly, you want to pass a value from native to your Js screens when the app launches. You can [fetch the value from native](https://facebook.github.io/react-native/docs/native-modules-android.html#promises) and pass it to the screen using [passProps](https://wix.github.io/react-native-navigation/#/top-level-api?id=starttabbasedappparams)

**Comment by sunny635533** [comment]
@guyca thank you very much！I get it！i will do it with your way.
