### ISSUE TITLE
why npm install it, it's version is "1.1.134",not  "1.1.85"?

### ISSUE THREAD

**Issue by sunny635533** [wix/react-native-navigation#1494]
### Issue Description

why npm install it, it's version is "1.1.134",not  "1.1.85"?  Actually it's latest version is "1.1.85" in gitub.With "npm install react-native-navigation@latest",it's veriosn is 1.1.134.
---
### Environment
* React Native Navigation version: 1.1.134
* React Native version:0.45.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): debug

**Comment by guyca** [comment]
if you think you're getting a wrong version when npm installing - you probably need to clear cache

**Comment by sunny635533** [comment]
@guyca  i already delete it ,but i still get it's version is 1.1.134.
