### ISSUE TITLE
Enable elevation on toolbar after disabling

### ISSUE THREAD

**Issue by dsvgit** [wix/react-native-navigation#1495]
Now it isn't enabled after disabling by set styles.
```
this.props.navigator.setStyle({
  topBarElevationShadowEnabled: false
});
this.props.navigator.setStyle({
  topBarElevationShadowEnabled: true
});
```

related to #125

**Comment by seanlau555** [comment]
I have the same problem too. 
Currently using react native 0.42.3
react-native-navigation 1.1.80

**Comment by Flavien** [comment]
I'm still having the same problem (react-native-navigation 1.1.246).

Once elevation is disabled, there is no way to enable it back.
