### ISSUE TITLE
[Question] Implementing popup menu

### ISSUE THREAD

**Issue by VERSAYANA** [wix/react-native-navigation#1498]
What's the best/recommended way of implementing popup menu in navBar?
![rsz_screenshot_20170713-184231](https://user-images.githubusercontent.com/20874813/28171044-7e5c565e-67fc-11e7-9346-001da509aecd.png)

**Comment by guyca** [comment]
Specify [showAsAction: 'never'](https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=adding-buttons-to-the-navigator). Though we currently only support simple menus - there's no support for checkboxes or secondary menus.
