### ISSUE TITLE
Wrapper around root component (Integration with react-native-material-ui)

### ISSUE THREAD

**Issue by xvonabur** [wix/react-native-navigation#1499]
### Issue Description

Hello! I'm currently in the middle of migrating from react-navigation. In my project I use react-native-material-ui to style views. It needs a wrapper named ThemeProvider around root component (e.g. App) like this:

```js
class Main extends Component {
    render() {
        return (
            <ThemeProvider uiTheme={uiTheme}>
                <App />
            </ThemeProvider>
        );
    }
}
```

In react-navigation it was easy by just using render method of App component. But I'm struggle to use it with react-native-navigation. I've tried to wrap every screen (I know, the dumbest decision) like this :

```js
Navigation.registerComponent('insteam.Main', () => <ThemeProvider context={{}}>MainScreen</ThemeProvider>, store, Provider)
```

but got the following error:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components), but got: object
```

Is it possible to use a wrapper for root component with this library?

---
### Environment
* React Native Navigation version: 1.1.134
* React Native version: 0.44.2
* Platform(s): Android
* Device info: Simulator with Android 7

**Comment by jtibbertsma** [comment]
You could use a higher order component:

```js
import hoistStatics from 'hoist-non-react-statics';

function themeProvider(WrappedComponent) {
  class ThemeProviderHOC extends Component {
    render() {
      return (
        <ThemeProvider uiTheme={uiTheme}>
          <WrappedComponent />
        </ThemeProvider>
      );
    }
  }

  return hoistStatics(ThemeProviderHOC, WrappedComponent);
}

Navigation.registerComponent('insteam.Main', () => themeProvider(MainScreen), store, Provider);
```

You could also override the Provider API:

```js
class MyProvider extends Component {
  render() {
    const { store, children } = this.props;
    return (
      <Provider store={store}>
        <ThemeProvider uiTheme={uiTheme}>
          {children}
        </ThemeProvider>
      </Provider>
    );
  }
}

Navigation.registerComponent('insteam.Main', () => MainScreen, store, MyProvider);
```

**Comment by xvonabur** [comment]
Thanks, @jtibbertsma! I'm closing the issue.

**Comment by xvonabur** [comment]
Thanks, @jtibbertsma! I'm closing the issue.

**Comment by xvonabur** [comment]
@jtibbertsma, I think you missed passing navigator to WrappedComponent like this:

```javascript
<ThemeProvider uiTheme={uiTheme}>
  <WrappedComponent navigator={this.props.navigator} />
</ThemeProvider>
```
