### ISSUE TITLE
[Resolved] AppRegistry.registerComponent... 

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#15]
I looking at the latest example app (master).  I notice a few thing that may or may not be related. 

1. There's no AppRegistry.registerComponent...  in the index.ios.js file.
2. The import App from './src/app'; in the index.ios.js file references app but inside app.js there's no default export.  
3.  Running the simulation leads me to a blank screen in the simulator.  

Again, I am not sure if the blank screen is associated with missing usual boilerplate

**Comment by Lllong** [comment]
same problem, can you tell me, how to Resolved

**Comment by theoutlander** [comment]
You should post solutions for posterity!
