### ISSUE TITLE
Addition of some sort of WillFocus, DidFocus mechanism.

### ISSUE THREAD

**Issue by lprhodes** [wix/react-native-navigation#150]
Hi,

I just saw that you were currently working on 2.0 of RCC/RNN. I'd love for WillFocus, DidFocus notifications to be included within this. 

In my case I need to perform actions when a user moves to a specific tab.

I've hacked this into the current version by sending the navigatorEventID to the RCCNavigationController and sending an app event from the viewWillAppear of RCCViewController in the same way the back buttons are handled.

`onNavigatorEvent (event) {
    if (event.type === 'DidFocus') {
      this.doSomething()
    }
  }`

Thanks!
Luke

**Comment by guyca** [comment]
Hey @lprhodes We're going to add life cycle events to the screens, this should give us indication when a screen is displayed after tab press or back button press etc.

**Comment by phuna** [comment]
@guyca will those life cycle events be available soon? I need something like viewWillAppear to update list view after adding a record to the list. Thank you.

**Comment by phuna** [comment]
@lprhodes : can you elaborate the mechanism you're using to achieve that kind of 'DidFocus' event with react-native-navigation? Thanks in advance.

**Comment by lprhodes** [comment]
Hi @phuna,

I've just forked in order to integrate this now - I imagine the implementation @guyca has in mind will be vastly different but it achieves what I need right now.

It requires amends to both RNC and RNN:

https://github.com/lprhodes/react-native-controllers/commit/b57f7b64c5ba6adb2c3ebddf01ec40b1e23b301a

https://github.com/lprhodes/react-native-navigation/commit/ca839f99c0a4adeed74ef6f0e36b0d1d141f3752

Then you can intercept with the same navigator events as you use for nav bar button actions:

```
onNavigatorEvent (event) {
  if (event.type === 'DidFocus') {
    this.doSomething()
  }
}
```

**Comment by phuna** [comment]
Hi @lprhodes : Thanks a lot for sharing

**Comment by kendrickkesley** [comment]
is this feature implemented yet?

**Comment by DanielZlotin** [comment]
Nope. soon.

**Comment by kendrickkesley** [comment]
Ok, Thanks for the info @DanielZlotin !
You guys are awesome!

**Comment by adamski** [comment]
This would be great to have on Android too!

**Comment by indivisable** [comment]
Any updates on this? What is best way to implement for now?

**Comment by musicode** [comment]
any update?

**Comment by musicode** [comment]
Any updates about this?

**Comment by DanielZlotin** [comment]
follow the progress in this [branch](https://github.com/wix/react-native-navigation/tree/v2)

**Comment by musicode** [comment]
Is 2.0.0 done  and 2.1.0 developing?

**Comment by guyca** [comment]
@musicode Yes, As Daniel said in https://github.com/wix/react-native-navigation/issues/150#issuecomment-280913247, v2 is under development.

**Comment by musicode** [comment]
that is said，screen lifecycle is supported, right?

**Comment by guyca** [comment]
Yes.

**Comment by musicode** [comment]
v2 branch is supported for RN0.40 ?

I am confused by master branch and v2 branch confuse...

**Comment by guyca** [comment]
v2 branch is under development and not production ready.
