### ISSUE TITLE
Code Push implementation Error with RNN: MainApplication cannot override getJSBundleFile()

### ISSUE THREAD

**Issue by larryranches** [wix/react-native-navigation#1501]
I'm trying to implement code push to my project using this react-native-navigation.  I need to run the code below to have code push make updates. I am receiving this error: MainApplication cannot override getJSBundleFile() in NavigationApplication. This is happening with building for Android. Is there a way to override this method as it's necessary for code push implementation? Help would be very nice.

```
// 2. Override the getJSBundleFile method in order to let
// the CodePush runtime determine where to get the JS
// bundle location from on each app start
        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
```

---
### Environment
* React Native Navigation version: 2.0.0-experimental.302
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug and release, nexus 7

**Comment by dorthwein** [comment]
+1

**Comment by pewh** [comment]
Just replace `protected` with `public`. Hope it helps.

**Comment by felipemartim** [comment]
@pewh do you have a working source code for MainApplication.java with code push enabled? I couldn't make it work by following the comment you linked.

**Comment by pewh** [comment]
```
package com.example;

import android.app.Application;
import com.facebook.react.ReactApplication;
import com.microsoft.codepush.react.CodePush;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    // from react-natice-code-push
    @Override
    protected String getJSBundleFile() {
      return CodePush.getJSBundleFile();
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new CodePush(BuildConfig.CODEPUSH_KEY, getApplicationContext(), BuildConfig.DEBUG),
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

```

**Comment by pewh** [comment]
What RN version do you use? Mine is testing with RN 0.47 & 0.48

**Comment by ericlewis** [comment]
anyone know how this would work on RNN v1?

**Comment by zhangandroid** [comment]
public class MainApplication extends NavigationApplication {
    @Override
    public String getJSBundleFile() {
        return CodePush.getJSBundleFile();
    }
    @Override
    public boolean isDebug() {
        return BuildConfig.DEBUG;
    }
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return Arrays.<ReactPackage>asList(
                 ......
                new CodePush("deploymentKey" , getApplicationContext(), BuildConfig.DEBUG)
        );
    }
    @Override
    public void onCreate() {
        super.onCreate();
 
    }
}

**Comment by esipavicius** [comment]
I found where it should be in navigation v2:

```
        @Override
        protected ReactGateway createReactGateway() {
            ReactNativeHost host = new NavigationReactNativeHost(this, isDebug(), createAdditionalReactPackages()) {
                protected String getJSBundleFile() {
                    return CodePush.getJSBundleFile();
                }
    
                @Override
                protected String getJSMainModuleName() {
                    return "index";
                }
            };
            return new ReactGateway(this, isDebug(), host);
        }
```

**Comment by seavan** [comment]
thank you, @esipavicius, works like a charm.

**Comment by kanso-michael** [comment]
@seavan Can you share your working `MainApplication.java` setup?

**Comment by seavan** [comment]
> @seavan Can you share your working `MainApplication.java` setup?

`public class MainApplication extends NavigationApplication {
    private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(new BasePackageList().getPackageList(), null);

    private final ReactNativeHost mReactNativeHost =
            new NavigationReactNativeHost(this) {
                @Override
                protected String getJSMainModuleName() {
                    return "index";
                }

                @Override
                public boolean getUseDeveloperSupport() {
                    return BuildConfig.DEBUG;
                }

                protected String getJSBundleFile() {
                    return CodePush.getJSBundleFile();
                }

                @Override
                public List<ReactPackage> getPackages() {
                    @SuppressWarnings("UnnecessaryLocalVariable")
                    List<ReactPackage> packages = new PackageList(this).getPackages();
                    // Packages that cannot be autolinked yet can be added manually here, for example:
                    // packages.add(new MyReactNativePackage());

                    // Add unimodules
                    List<ReactPackage> unimodules = Arrays.<ReactPackage>asList(
                            new ModuleRegistryAdapter(mModuleRegistryProvider)
                    );
                    packages.addAll(unimodules);

                    return packages;
                }
            };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }
}
`
