### ISSUE TITLE
How to set default navigator transition animationType to 'slide-horizontal'?

### ISSUE THREAD

**Issue by feyy** [wix/react-native-navigation#1503]
How to set default navigator transition animationType to 'slide-horizontal'? So I don't need pass {animationType: 'slide-horizontal'} when navigator change.

**Comment by guyca** [comment]
Create a class to handle all navigation action and set it once there.

```js
export function push(navigator, params) {
  navigator.push({
    ...params,
    animationType: 'slide-horizontal'
  });
}
```
