### ISSUE TITLE
Android - Linking.getInitialURL() returns null on application launch from external link

### ISSUE THREAD

**Issue by sheshavpd** [wix/react-native-navigation#1506]
Great package out there! Thanks for that.
#384 talks exactly about this. I'm opening this issue since I couldn't find any working solution in that thread.
The listener to linking(after app is created) is working, but the Linking.getInitialURL()(on app creation) is not.
Please help me out with this.

**Comment by guyca** [comment]
Hey there, I'm not aware of any issues with external links on Android. Perhaps the issue is with your external links setup. What version of RNN are you using?

**Comment by sheshavpd** [comment]
Hey @guyca I'm using the latest version of RNN(0.45.1).
I'm launching app from notification with pendingIntent which launches "appname://notification?data=xx"
```
Linking.getInitialURL().then((url) => {
            console.log(url);
            if(url)
            this.handleNotificationURL({ url });
        });
```
The above code(inside componentDidMount) logs "null" into console even if I launch the app from notification.
`Linking.addEventListener('url', this.handleNotificationURL.bind(this));`
works fine when app is running. Can you please inform me what's wrong?

**Comment by guyca** [comment]
Is this on iOS?

**Comment by sheshavpd** [comment]
@guyca , it's on Android(M). Sorry for not specifying.

**Comment by jhaytaslim** [comment]
nnooo,pls re-open. I just ran into into it

**Comment by oferRounds** [comment]
Any solution to this issue on Android + V1?

Facing this issue when app is opened from an external link, while being closed before (works well if it was just open on the background)

**Comment by draperunner** [comment]
I am having the same issue on iOS with react-native-navigation v2. When the app is open in the background, it works. But it does not work with the app cold starting. The app opens, but I get no URL.
