### ISSUE TITLE
Can't handle denormalized props? "Unhandled JS Exception: JSON.stringify cannot serialize cyclic structures."

### ISSUE THREAD

**Issue by markymc** [wix/react-native-navigation#1507]
### Issue Description

Hi guys. First of all thanks for this lib. I've been using TabBarIOS and NavigatorIOS until now, but its problems with passProps (https://github.com/facebook/react-native/issues/795) and the fact that I'd like to support Android soon have brought me to give this lib a try. It looks great so far, except..

`"Unhandled JS Exception: JSON.stringify cannot serialize cyclic structures."`

I get the above error when passing props that contain denormalized data using Normalizr's denormalize() method (https://github.com/paularmstrong/normalizr/blob/master/docs/api.md#denormalizeinput-schema-entities). 

This isn't something I was seeing with NavigatorIOS, so I'm assuming it's possible to handle somehow. Is there something I'm not doing right? Or an architectural decision that means this can't work? Or just a case that it's not been needed by anyone else and so hasn't been supported yet?

### Steps to Reproduce / Code Snippets / Screenshots

Call the following:

```
    this.props.navigator.push({
      screen: 'app.Profile',
      title: 'Profile',
      passProps: { user: user }
    });
```

Pass a `user` object with the following structure:

```
{ user:
   id,
   works: [{
     id,
     user: reference_to_root_object,
     other_properties_here
  }],
  other_properties_here
}
```

---
### Environment
* React Native Navigation version: 1.1.134
* React Native version: 0.44.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6 simulator iOS 10.3.1 release.

Thanks!

**Comment by guerjon** [comment]
@markymc  Any solution?

**Comment by markymc** [comment]
@guerjon Not a decent solution yet I'm afraid. I basically worked around it by passing a user ID to the component being pushed onto the nav stack, and denormalizing a full user with the ID in mapStateToProps. I don't like that as it's a bit slow, but it works.

A couple of options I see:

1) Just deal with it as it is for the time being. At least it works! Although it doesn't feel very "React"!
2) Look into the react-native-navigation codebase and see if I can fix it in a fork or PR.
3) Write my own navigation library (last resort!).
4) Go all the way and use the passing of IDs and denormalize in all components that act as view controllers being pushed onto the nav stack. But that feels messy and should be unnecessary.

It feels strange that no-one else is seeing this issue so far though. Makes me wonder whether many others are creating fully fledged apps (e.g. Facebook/Instagram level functionality) using RN (i.e. the kind that needs a normalized store), or if I've just not found the best architecture for this kind of deep model graph handling yet?

Are you able to share any details on your situation?

**Comment by markymc** [comment]
OK, so I've been looking into the react-native-navigation and NavigatorIOS codebases to see if I can work it out, and here are some notes I wrote as I went so you can follow my logic:

**react-native-navigation codebase dive**

**src/deprecated/platformSpecificDeprecated.ios.js** :236 calls `savePassProps(params)` (:586), where `params` includes the `passProps` received. `savePassProps` just saves props into the `PropRegistry`, which doesn’t send anything to the native layer AFAIK.

:238 it then calls `Controllers.NavigationControllerIOS(navigator.navigatorID).push(…)`, where `passProps` gets passed in (:245). I think this is probably where the props are going to get passed down to the native layer, so let’s look into `Controllers.NavigationControllerIOS`…


`src/deprecated/controllers/index.js` :132 is where `NavigationControllerIOS` is defined. :134 `push(params)` is what we’re interested in, and specifically :151 `RCCManager.NavigationControllerIOS(id, "push", params);` ?

`ios/RCCManagerModule.m` :272 is where the method gets bridged into ObjC. I imagine this is where the `passProps` are blowing up!



So the big question is, do we really need `passProps` to go all the way down to the native layer? What if we forcibly remove them from :245 in `platformSpecificDeprecated.ios.js`??? Surely once they get to the native layer they’re not needed?

Although… `NavigatorIOS` uses `passProps` too… https://facebook.github.io/react-native/docs/navigatorios.html … so perhaps they are necessary? Time to look at how `NavigatorIOS` does it!!!…


`NavigatorIOS.ios.js` doesn’t really show anything… checking `RCTNavigator` as shown in :49…, which is a native component…

Ah, back up… `NavigatorIOS.ios.js` :673 is where the push method is defined! And it takes a single param called `route`, which contains the `passProps` (see link above). 

:842 `_routeToStackItem` relevant? Yup, it looks like that’s where the component being pushed onto the stack receives its props (:862)…

So yeah, looks like there’s no real need for the `passProps` to go down to the native level?… so perhaps we can fork react-native-navigation, remove :245 (`passProps: passProps,`) in src/deprecated/platformSpecificDeprecated.ios.js and things will be ok???

It would be fantastic if anyone on the core react-native-navigation team could pop in here and comment on whether src/deprecated/platformSpecificDeprecated.ios.js:245 is actually needed or not. :)

**Comment by markymc** [comment]
OK, so I've had a quick play by commenting out `src/deprecated/platformSpecificDeprecated.ios.js:245` but unfortunately it looks like that line does contribute to a component being pushed receiving its props somehow. Am going to go back into the codebase and follow it deeper.

**Comment by guyca** [comment]
Hey @markymc 
First, thanks a lot for taking the time to look into this issue. Indeed, there's no reason for passing props to native and we should avoid doing so from performance reasons as well.
From what I understand, native expect three properties from `passProps`:
* navigatorID
* screenInstanceID
* navigatorEventID

Omitting all props except these three should be fine. For example, sending these three properties [here](https://github.com/wix/react-native-navigation/blob/master/src/deprecated/platformSpecificDeprecated.ios.js#L247) should be fine.

**Comment by markymc** [comment]
@guyca thanks for getting back to me. :)

That’s great to hear! I’ll give that a shot today and perhaps I can submit a pull request?

**Comment by guyca** [comment]
Of course, will gladly accept a PR 👍
