### ISSUE TITLE
Drawer in Android is not working like IOS drawer

### ISSUE THREAD

**Issue by satishpalli** [wix/react-native-navigation#151]
hi team

in IOS Drawer is working fine but same functionality not working in android.
getting error undefined is not an object(evaluating 'this.props.navigator.showModal')

can some one please help how to resolve this issue

**Comment by explorigin** [comment]
Yes, navigator is not passed to Drawer on Android.  We're waiting for the major Android re-write that will start next month. https://github.com/wix/react-native-navigation/issues?q=is%3Aissue+is%3Aopen+label%3Av2.0

**Comment by drorbiran** [comment]
Drawer for Android is a part of our plan for Version 2.0.0

**Comment by guyca** [comment]
fixed in v2.0
