### ISSUE TITLE
[Help Needed] How can I use side bar animations with RNN ?

### ISSUE THREAD

**Issue by rajaishwary** [wix/react-native-navigation#1512]
looking for Animation  SidebarLuvocracyAnimation.

![image](https://user-images.githubusercontent.com/7762321/28247473-d35ee8d4-6a4e-11e7-80b2-073910cc61c8.png)

**Comment by rajaishwary** [comment]
found the sol:

        drawer: {
            left: {
                screen: 'example.Types.Drawer',
            },
            type: "TheSideBar",
            animationType: "luvocracy"
        }

Need to pass the type and animationType. Missing from doc.

tested for platform: iOS

**Comment by guyca** [comment]
@rajaishwary Can you please update the docs?

**Comment by rajaishwary** [comment]
@guyca done. https://github.com/wix/react-native-navigation/pull/1619

**Comment by guyca** [comment]
Amazing! thanks!
