### ISSUE TITLE
[Android] startSingleScreenApp nav header disappear

### ISSUE THREAD

**Issue by criticalnooks** [wix/react-native-navigation#1515]
### Issue Description
startSingleScreenApp nav header disappear and i'm running on Android but I didn't test yet on iOS.
But when I have re-version to 1.1.134. It's Appear!.

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots
[FILL THIS OUT - It will be extremely helpful]
`Navigation.startSingleScreenApp({ `
`        screen: {`
`                screen: 'screen1', // unique ID registered with Navigation.registerScreen`
`                title: 'Welcome', // title of the screen as appears in the nav bar (optional)`
`        },`
`});`

title 'Welcome' on navbar disappear
---
### Environment
* React Native Navigation version:1.1.135
* React Native version: 0.46.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):  Simulator and Device

**Comment by jstheoriginal** [comment]
I'm also seeing no nav bar titles now on Android 6.0 and 7.0, but on Android 5.1.1 they show fine. 🤔

**Comment by jstheoriginal** [comment]
Actually I'm not seeing any on 5.1.1 either after a clean install of the app.

**Comment by criticalnooks** [comment]
I got answer now. From here #1493

**Comment by jstheoriginal** [comment]
I have a fix and am making a PR.
