### ISSUE TITLE
Custom navigatorButton component

### ISSUE THREAD

**Issue by jacobjuul** [wix/react-native-navigation#1517]
I haven't found any documentation on how to add a custom component as a navigatorButton. 
I have an icon/button, that I would like to add a badge (with count) to. 

Does this exsist?

**Comment by Fuhrmann** [comment]
You can add you own button as a component, here it is the docs:

https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=buttons-object-format

**Comment by brunolemos** [comment]
The docs mention `leftButtons` and `rightButtons`, but how about custom components on tabbar (bottom bar) icons?

**Comment by filipepratalima** [comment]
Im also looking for this.
