### ISSUE TITLE
Is there any way to mix singleScreenApp and tabBasedApp?

### ISSUE THREAD

**Issue by psychoplasma** [wix/react-native-navigation#1518]
I'm trying to implement an app that starts with some single screens (like login, signup screens) and after some point switches to a tabbed screen including some other screens. However, I couldn't find any way to do this with react-native-navigation. 

Is there any way to do it with react-native-navigation? Thanks.

**Comment by guyca** [comment]
You can call `startTabBasedApp` whenever you want 👍
