### ISSUE TITLE
Setting navbar title through navigatorStyle

### ISSUE THREAD

**Issue by tmaly1980** [wix/react-native-navigation#1519]
Is there a way to set the navbar title through navigatorStyle, such as:

```
class ContactsScreen extends React.Component {
  static navigatorStyle = {
    navBarTitle: 'Manage Contacts',
  }
  render() ...
}
```

Though obviously that doesn't work. For something that is very likely static for a given screen, it seems to make sense for it to be the screen's responsibility to identify itself, rather than it be the responsibility of the previous screen pushing it on the nav.

Currently the best way I know how to set it is via:

```
  componentWillMount () {
    this.props.navigator.setTitle({title: 'Manage Contacts'})
  }

```

But setting it in navigatorStyle seems more familiar (akin to the react-navigation library).

**Comment by guyca** [comment]
That's a great suggestion, I think this is already implemented in v2. cc @DanielZlotin

**Comment by tmaly1980** [comment]
@guyca and @DanielZlotin  , what's the status  of v2?

**Comment by smooJitter** [comment]
Lolololo.  I'm sure you guys are tired of hearing that.  Frankly, you could be backing yourselves into a pickle. The current version just keeps getting better and better. Sooooo many updates and enhancements. It begs to wonder if it'll worth the upgrade. I love this package as it is
