### ISSUE TITLE
Example Redux fails to load on iOS

### ISSUE THREAD

**Issue by chrisaspringer** [wix/react-native-navigation#152]
Upon build in XCode, and after running an `npm install` with node v6.3.0 and npm v3.10.3, get red error screen with the message `this._nativeModule.addListener is not a function...`

**Comment by jarredwitt** [comment]
I know when I tried to run the examples I got the same error and was able to fix it by adding -lc++ to the Other Linker Flags in the Linking section of Build Phases.

**Comment by pqkluan** [comment]
The bug above was patched a long time ago.
