### ISSUE TITLE
How open a screen within tabbased application that is not registered in tabs

### ISSUE THREAD

**Issue by silverboyir** [wix/react-native-navigation#1522]
Hi
im new in react native , i have a tab based application , i want start a new screen from one tab so i need bottom bar remain as it is and bottom bar rendered in top of my screen( my new screen is not registered in tab based app) 
how i can achieve this ?

**Comment by guyca** [comment]
Use [push](https://wix.github.io/react-native-navigation/#/screen-api?id=pushparams) or show a modal
