### ISSUE TITLE
Adding custom button on title or getting event from tap on title of navigation bar

### ISSUE THREAD

**Issue by swaroop03** [wix/react-native-navigation#1524]
### Issue Description

How can I get event on tapping title of navigation bar or could I add custom button on navigation bar?

---
### Environment
* React Native Navigation version: 1.1.134
* React Native version: 0.42.3
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?):

**Comment by alexwasner** [comment]
@swaroop03 This was back in July. Did you find a solution? I have the same question
