### ISSUE TITLE
crashed on android 4.3, but is good on above 5

### ISSUE THREAD

**Issue by mrxrinc** [wix/react-native-navigation#1525]
why this navigation doesn't work on android 4.3?

**Comment by guyca** [comment]
Hey @mrxrinc 
Officially we support API 16 and above, but since the Wix app supports API 19 and above, we've stopped testing on API 18.

How many users do you have with Android 4.3? I'm sure it's less then 2% - is that worth supporting?

**Comment by guyca** [comment]
I'll bring this up with the team in our next meeting, we should support API 19 and above.

**Comment by mrxrinc** [comment]
okey, anyway thank u for this amazing module.
