### ISSUE TITLE
[iOS] Default backButtonTitle for screen is not set to the tab title/label when pushed from a tab screen

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#1527]
### Issue Description
In iOS, when a screen is pushed, the default `backButtonTitle` is set to the title of the previous screen on which this screen is pushed. That is not the case when the screen is pushed from the first top level tab screen. The screen title is set to `Back` in such cases instead of the tab label or tab screen title. This breaks the internationalisation a little bit because the `Back` wouldn't be internationalised.

There is an easy workaround which is to set the `backButtonTitle` explicitly for such cases but just wanted to open an issue in case it is an oversight. If this is the expected behaviour, please close this issue.

### Steps to Reproduce / Code Snippets / Screenshots
1. Push a screen from a tab in a tab based app
2. Observe that the back button is titled `Back` and not the tab title/label
3. Push a screen from some other screen that is not a top level tab screen
4. Observe that the title of the back button is title of the previous screen.

---
### Environment
* React Native Navigation version: 1.1.79
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by pqkluan** [comment]
This issue seems to be solved a long time ago. Please re-open if that is not the case.
