### ISSUE TITLE
Screens/ContentViews drawing on top of each other

### ISSUE THREAD

**Issue by artushin** [wix/react-native-navigation#1528]
### Issue Description
When using `startSingleScreenApp`, navigating to a new screen (tested with `resetTo` and `push`) results in a brief period (half a secondish) where both screens are drawn on top of each other. This happens regardless of the `animated` setting. Anyone else seeing this issue?

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots
Seems to happen regardless of where the navigator is activated. Simple button presses and use of the drawer produce the same result.

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.136
* React Native version: 0.46.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel - 7.1.1 - debug

**Comment by obipawan** [comment]
@artushin I suppose this is because the new screen doesn't have a `backgroundColor` set?

**Comment by guyca** [comment]
@artushin Sorry for the late response. As @obipawan mentioned, it's probably due to screens having transparent background on Android. You can give the rendered view background color or use `screenBackgroundColor` property.

**Comment by artushin** [comment]
Yep, that worked. Thanks guys.
