### ISSUE TITLE
Navigation.dismissLightBox race condition

### ISSUE THREAD

**Issue by ramneekhanda** [wix/react-native-navigation#1530]
Fast switching lightbox have race condition.. show and dismiss of lightbox on android or ios need to be fixed.

**Comment by jslz** [comment]
I think we are seeing this, also. We have 2 lightboxes in a row, the 2nd one appears after the first one is dismissed by a user's click. But the 2nd one won't go away, the call to this.props.navigator.dismissLightBox() does not crash or anything, no errors appear, but the lightbox does not dismiss at all. (Mostly we see this on Android but it sometimes works which makes us wonder if iOS is just getting lucky so far in our testing.)

react-native-cli: 2.0.1
react-native: 0.46.4
"react-native-navigation": "^1.1.205",

**Comment by sijad** [comment]
we have same issue here, we see this issue by calling `switchToTab` then `showLightBox`.

**Comment by wwwdata** [comment]
I can also confirm the exact same behaviour jas @jslz described. Only tested on Android. I opened a LightBox that gets closed, and after that I imeediatly open another one. However, the tapping on background options is still working, which I am using now to close the lightbox...

Did you find any workarounds so far or is anybody working on a fix? Must be some race condition I guess.

**Comment by GizzmoAsus** [comment]
I'm seeing the exact same issue with the following environment:

react-native-cli: 1.0.0
react-native: 0.54.2
react-native-navigation:  "^1.1.409"
OS: android
platform: Windows
devices tested: Physical and Emulator

Entries from `adb logcat *:S ReactNative:V ReactNativeJS:V` are as follows:

`03-19 00:25:45.292 22200 22200 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
03-19 00:25:55.042 22200 22200 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
03-19 00:25:58.736 22200 22200 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
03-19 00:25:59.019 22200 22200 D ReactNative: ReactInstanceManager.detachViewFromInstance()`

Steps producing this log are as follows:
- Open the main single screen app 
- Click on an element that opens the first lightbox
- Click on the lightbox which should dismiss the first lightbox then open a fresh lightbox with a new screen
- Click on the last lightbox which clears a state value and should dismiss the final lightbox

What I'm seeing is that the reset state method is being triggered whenever the lightbox screen is tapped (developer console) but the dismissLightBox method is never triggered which means the detachViewFromInstance() is not called. Tapping outside of the lightbox works fine when `tapBackgroundToDismiss: true` is set though.

Hope this helps.

**Comment by zarvedan** [comment]
I have found a workaround for Android. 
Go to SingleScreenLayout.java and change method showLightBox like this :

 ` @Override
    public void showLightBox(LightBoxParams params) {
//        if (lightBox == null) {
            lightBox = new LightBox(getActivity(), new Runnable() {
                @Override
                public void run() {
                    //lightBox = null;
                }
            }, params);
            lightBox.show();
//        }
    }`

Tested on Android Physical device 
react-native: 0.54.0,
react-native-navigation: 1.1.411

**Comment by geastwood** [comment]
Solution provided by @zarvedan works for us. However we need to apply this change in a different file `BottomTabsLayout.java`, in case this is helpful for someone else.

**Comment by mironiasty** [comment]
We have same issue in our project. Turns out that this hotfix is slightly better workaround (@zarvedan fix was failing with backbutton dismissing):
```diff
     @Override
     public void showLightBox(LightBoxParams params) {
-        if (lightBox == null) {
+        if (lightBox == null || !lightBox.isShowing()) {
             lightBox = new LightBox(getActivity(), new Runnable() {
                 @Override
                 public void run() {
-                    lightBox = null;
+                    // lightBox = null;
                 }
             }, params);
             lightBox.show();
        }
    }
```
This should be applied to `BottomTabsLayout.java` and `SingleScreenLayout.java`. We are still testing it, but for now it looks promising.
