### ISSUE TITLE
Hiding tab bar on textinput

### ISSUE THREAD

**Issue by martinnenseth** [wix/react-native-navigation#1532]
### Issue Description

I'm using the TabBasedApp where I'm currently displaying the tab bar on every screen. However, I wish to hide the tabbar when a user fills out a textinput form. I'm aware of the keyboardAvoidingView, and have tried using it without success, as the tab bar hides the input form. 
So, are there any smart solutions to hiding the tab bar when a user fills out a form?
### Steps to Reproduce / Code Snippets / Screenshots
- Initialize tabBasedApp
- Create TextInput element wrapped in a KeyboardAvoidingView with behaviour='padding' on a screen with tab bar shown.
- Run app and try filling in the form.

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1
* React Native version: 0.45
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Emulator - Nexus 5X_API

**Comment by jp928** [comment]
what I did is add listener to keyboard and call toggleTabbar with 'hidden' when the keyboard appears

**Comment by M-Jas** [comment]
Not opening this back up, but I wanted to recommend turning animation to false for toggling tabs. I left animated true and it kept pushing the tabbar up with the keyboard. 

listener when keyboard is displayed:
this.props.navigator.toggleTabs({
  to: 'hidden',
  animated: false
});

listener when keyboard is exited:
this.props.navigator.toggleTabs({
  to: 'shown',
  animated: false
});
