### ISSUE TITLE
Event on drawer close

### ISSUE THREAD

**Issue by basvdheijden** [wix/react-native-navigation#1545]
Is there a way to 'catch' the event for when the drawer closes?
I've got it sorted out for when you manually press the drawer button on the navigation bar, but not when the drawer is closed in another way (i.e. slide or clicking on the main screen to close it).
Would love to hear!

**Comment by basvdheijden** [comment]
Any ideas?

**Comment by guyca** [comment]
@basvdheijden I think you can use [screen visibility events](https://wix.github.io/react-native-navigation/#/screen-api?id=screen-visibility) to detect drawer open/close

**Comment by basvdheijden** [comment]
Tried it, but that doesn't work. Event doesn't get triggered.

**Comment by guyca** [comment]
@basvdheijden On which platform did you try?

**Comment by basvdheijden** [comment]
iOs

**Comment by guyca** [comment]
Right, I think it was implemented only on Android.

**Comment by basvdheijden** [comment]
But there must be some (inner) event triggering right?

**Comment by peterp** [comment]
@basvdheijden did you ever figure this out?

**Comment by basvdheijden** [comment]
No, alas :(

**Comment by salilbajaj** [comment]
hey @basvdheijden .. you found the solution?

**Comment by basvdheijden** [comment]
No :(

**Comment by gustavorozolin** [comment]
Has anyone figured out a solution/workaround for this problem?

**Comment by padupuy** [comment]
@gustavorozolin you could use the [ScreenVisibilityListener](https://wix.github.io/react-native-navigation/#/screen-api?id=listen-to-visibility-events-globally)

```
import { StatusBar, Platform } from 'react-native';
import { ScreenVisibilityListener as RNNScreenVisibilityListener } from 'react-native-navigation';

import { SCREENS } from './constants';

function isIOS() {
  return Platform.OS === 'ios';
}

export default class ScreenVisibilityListener {
  constructor() {
    this.listener = new RNNScreenVisibilityListener({
      willAppear: ({ screen }) => {
        if (isIOS() && screen === SCREENS.DRAWER.id) {
          StatusBar.setBarStyle('light-content', true);
        }
      },
      willDisappear: ({ screen }) => {
        if (isIOS() && screen === SCREENS.DRAWER.id) {
          StatusBar.setBarStyle('dark-content', true);
        }
      }
    });
  }

  register() {
    this.listener.register();
  }

  unregister() {
    if (this.listener) {
      this.listener.unregister();
      this.listener = null;
    }
  }
}

const svl = new ScreenVisibilityListener();
svl.register();

```

**Comment by gustavorozolin** [comment]
@padupuy thanks for reply, 

the code works for both OS (Android and iOS)?

**Comment by padupuy** [comment]
@gustavorozolin yes

**Comment by rpmonteiro** [comment]
The listener doesn't capture the drawer opening/closing :(

**Comment by Nirodha261** [comment]
As a workaround you can add custom navigation actions to capture the DrawerClose event.

`const drawerNavigator = DrawerNavigator({..});

const defaultGetStateForAction = drawerNavigator.router.getStateForAction;

drawerNavigator.router.getStateForAction = (action, state) => {
    if(state && action.type === 'Navigation/NAVIGATE' && action.routeName === 'DrawerClose') {
        //action needed to be taken for 'DrawerClose' event
    }


    return defaultGetStateForAction(action, state);
};`
