### ISSUE TITLE
this.props.navigator is undefined in the `CustomTopBar` component.

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#1546]
Hey there @guyca 

I was just testing the `CustomTopBar` implementation, and it seems to be working fine (testing in iOS currently, but I will eventually test in Android too).

The only problem is, the [CustomTopBar](https://github.com/wix/react-native-navigation/blob/e73c8efafc6caa49c998b3a6bba173bdd365e707/example/src/screens/types/CustomTopBar.js) component doesn't include the navigator in it's props.

When I do `this.props.navigator` it's undefined.

I need that so that I can dispatch deep link events when a button is pushed etc w/ `this.props.navigator.handleDeepLink`.

**Comment by guyca** [comment]
Hey @SudoPlz 
IIRC `handleDeepLink` can be called from `Navigation` - you don't need a navigator instance.

**Comment by diennguyentien** [comment]
Hi @guyca : how to use toggleDrawer in CustomTopBar, when I used this.props.navigator.toggleDrawer it's undefined and I used navBarComponentAlignment but it's not work in android

**Comment by SudoPlz** [comment]
Also how do we push or replace a screen @guyca?

**Comment by tmaly1980** [comment]
@SudoPlz , I haven't tried it, but did you look here? 

https://github.com/wix/react-native-navigation/blob/master/example/src/screens/types/CustomTopBarScreen.js

This refers to this.props.navigator, so my guess is it gets included when you call Navigation.registerComponent . 

Compare that to this other one, that doesn't refer to this.props.navigator nor does it get registered as a navigation component:

https://github.com/wix/react-native-navigation/blob/master/example/src/screens/types/CustomTopBar.js

**Comment by SudoPlz** [comment]
@tmaly1980 the [CustomTopBarScreen](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/types/CustomTopBarScreen.js) is just a normal screen component. It's not the custom bar.

The custom bar is https://github.com/wix/react-native-navigation/blob/master/example/src/screens/types/CustomTopBar.js (your second link) and that's where we need the `navigator` prop. It's not there right now.

**Comment by tmaly1980** [comment]
@guyca , weren't there plans to make the navigator a singleton, so deep links can be registered and handled once (outside of screens) so we don't need to deal with the fuss of how to handle a deep link without several components/screens responding? 

I've read about having a singleton top-level screen, but honestly this seems like a hack rather than something sustainable.

**Comment by tmaly1980** [comment]
@SudoPlz, I see. I agree that it should be passed along.

In the meantime, can you pass this.props.navigator to navBarCustomViewInitialProps ?

**Comment by SudoPlz** [comment]
@tmaly1980 the `navigator` prop doesn't seem to be serialisable, (at least not fully).

**Comment by guyca** [comment]
navigator isn't serializable so can't be passed over the bridge. On Android we don't pass props over the bridge to reduce stress, I'm not sure if props are passed over the bridge or not. Regardless this mechanism is [opt in](https://github.com/wix/react-native-navigation/blob/master/src/PropRegistry.js)

**Comment by SudoPlz** [comment]
Yes but how do we access the `navigator` prop from within our custom top bar then @guyca ?

**Comment by guyca** [comment]
You need to pass it in `navBarCustomViewInitialProps`:
```js
constructor(props) {
    super(props);
    this.props.navigator.setStyle({
      navBarCustomView: 'example.CustomTopBar',
      navBarCustomViewInitialProps: {navigator: this.props.navigator}
    });
  }
```

**Comment by SudoPlz** [comment]
@guyca OOoooooh I thought that wasn't possible because the navigator object wasn't serialisable. But apparently it doesn't matter if you pass it on the `navBarCustomViewInitialProps` I'll try that.

Thank you so much!

**Comment by iamjon** [comment]
I can confirm it works with version 1.1.295 
Thanks @guyca
