### ISSUE TITLE
How to change badge color

### ISSUE THREAD

**Issue by huowenxuan** [wix/react-native-navigation#1547]

**Comment by jacobjuul** [comment]
+1 It's pretty important for me to be able to style the badge entirely.

**Comment by guyca** [comment]
`bottomTabBadgeTextColor` and `bottomTabBadgeBackgroundColor` are [available](https://wix.github.io/react-native-navigation/#/top-level-api) on Android.

**Comment by huowenxuan** [comment]
@guyca 哇，太好了，十分感谢

**Comment by jacobjuul** [comment]
No plans for iOS?

**Comment by huowenxuan** [comment]
对于iOS，可以在didFinishLaunchingWithOptions中设置：
`[UITabBarItem appearance].badgeColor = [UIColor colorWithRed:215 / 255.0 green:95 / 255.0 blue:73 / 255.0 alpha:1];`

对于Android，在startTabBasedApp中：
`Navigation.startTabBasedApp({
    appStyle: {
      bottomTabBadgeBackgroundColor: Colors.TINT, // badge
      bottomTabBadgeTextColor: 'white'
    }
})
`

**Comment by guyca** [comment]
@jacobjuul When we started working on this library, iOS didn't expose an official api to customize badges. This api was added only recently in iOS 10, I doubt we will implement this for iOS.

Let keep the issue open, perhaps someone would submit a pr for iOS.

**Comment by huowenxuan** [comment]
@jacobjuul you can set `[UITabBarItem appearance].badgeColor` for iOS

**Comment by jacobjuul** [comment]
Thanks for the hint on `UITabBarItem`
