### ISSUE TITLE
Support Universal Links

### ISSUE THREAD

**Issue by hammadj** [wix/react-native-navigation#155]
https://developer.apple.com/library/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html

This is one of the new ways to do "deep links" in iOS 9, should have this as a part of https://github.com/wix/react-native-navigation#deep-links

idk if this should belong here or in https://github.com/wix/react-native-notifications

**Comment by headlessme** [comment]
Is there a recommended way to handle Universal Links when using react-native-navigation?

**Comment by stevenyap** [comment]
+1
