### ISSUE TITLE
dismissAllModals breaking toggleDrawer on ios

### ISSUE THREAD

**Issue by CoderProject** [wix/react-native-navigation#1550]
### Issue Description

After I call `dismissAllModals()`, `toggleDrawer()` simply does not do anything on iOS.
Android works as expected. Is there a quickfix that may save my day?

### Steps to Reproduce / Code Snippets / Screenshots

- Open multiple modals recursively using `showModal()` (modal in modal, 2 is enough)
- Call `this.props.navigator.dismissAllModals();` from the latest modal. I also tried calling it from root screen via deep linking.
- All modals will disappear.
- Now try the following and you will see that the drawer will not toggle.
```
this.props.navigator.toggleDrawer({
	  side: 'left', // the side of the drawer since you can have two, 'left' / 'right'
	  animated: true, // does the toggle have transition animation or does it happen immediately (optional)
});
```

---
### Environment
* React Native Navigation version: 1.1.130
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both, 10.X, both

**Comment by ahm-hossein** [comment]
same problem here

**Comment by agumack** [comment]
I have same problem

**Comment by lxooxl** [comment]
use dismissModal  can solve this

**Comment by CoderProject** [comment]
not even close.. I need all open modals to be closed, not just latest one.

**Comment by kyle-ssg** [comment]
Yep, can replicate this also. Same thing happens if you use ```Navigation.dismissModal``` vs ```props.navigator.dismissModal```

**Comment by lovbrand** [comment]
+1

**Comment by henrikra** [comment]
I have replicated this too! After `dismissAllModals` is called the `this.props.navigator.toggleDrawer({ side: 'left' });` does not work anymore! Can you guys check this out @alinz @yomybaby @gran33 @guyca

**Comment by elliotstokes** [comment]
We are also seeing something similar. The drawer will stop working after dismissAllModals is called. Seems to be the same issue as https://github.com/wix/react-native-navigation/issues/1632

**Comment by MrVisitor** [comment]
Maybe someone could understand me and help. After using the Navigation.dismissAllModals() method, DrawerControllerIOS is unavailable in the componentsDic.
