### ISSUE TITLE
Add a changelog or a whats changed.

### ISSUE THREAD

**Issue by elliotstokes** [wix/react-native-navigation#1551]
### Issue Description

Thanks for setting up the project - its been a real help all round. One thing were finding though is that updates are pushed up pretty regularly (we often get 60+ builds behind) Looking in the project though I cant find any documentation (Changelog or similar) as to whats been fixed/modified/removed/added within those changes. It would be really useful to get some indication as to whats changed, even if its just the headlines.

I'm currently doing a compare https://github.com/wix/react-native-navigation/compare/v1.1.88...v1.1.142

Thanks again

**Comment by skovhus** [comment]
Would be really nice with a change log. Are you waiting for 2.x to be out before doing that?

**Comment by guyca** [comment]
closing in favor of #2162
