### ISSUE TITLE
how to use v2

### ISSUE THREAD

**Issue by abellee** [wix/react-native-navigation#1552]
I have some native react packages,
and how can I add them to the `getPackages` etc?
I tried to extends `ReactNativeHost` and `ReactGateway`
but the `getPackages` never been called.

### Environment
* React Native Navigation version: v2
* React Native version: 0.46.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):  all

**Comment by Noitidart** [comment]
You can copy and paste from here - https://github.com/wix/react-native-navigation/tree/v2/playground/src

Or you can clone that part of the repo. I prefered copy and pasting so I know what all is changing.

**Comment by DanielZlotin** [comment]
#1605
