### ISSUE TITLE
Android: Extending MainActivity with SplashActivity sometimes stops other native modules to load

### ISSUE THREAD

**Issue by ianataffinity** [wix/react-native-navigation#1554]
### Issue Description

I have installed the module "react-native-image-picker" from here https://github.com/react-community/react-native-image-picker

When I run the JS method from that module `ImagePicker.showImagePicker(null, () => {});` I get the red screen of death, showImagePicker is undefined. 

This is because the `native-modules` from React didn't pick up the native method in the package:

    const { NativeModules } = require('react-native');
    const { ImagePickerManager } = NativeModules;

ImagePickerManager will always be undefined. 

**However**, it is only undefined if SplashActivity is extending MainActivity. If I switch back to:

`public class MainActivity extends ReactActivity` 

ImagePickerManager is defined and all is well.

This is just 1 module example. However I have found that it will fail like this on others as well. Doesn't always happen, but I found those modules that interact with native code to be the biggest culprits. 

Any suggestions on how to use `SplashActivity` and have other modules work?

### Steps to Reproduce / Code Snippets / Screenshots

MainActivity.java to look like this:

    package com.project;
    import com.reactnativenavigation.controllers.SplashActivity;

    public class MainActivity extends SplashActivity {
        protected String getMainComponentName() {
            return "Project";
        }
    }

Then install and link the module `react-native-image-picker` 

---
### Environment
* React Native Navigation version: ^1.1.142
* React Native version: ^0.46.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, GenyMotion / Android Emulator, Debug

**Comment by ianataffinity** [comment]
Closing this issue as I found out what the problem was. 

In my MainAppplication.java I had 2 ` getPackages()`. This may sound like a simple thing to pick up on however some of the docs weren't clear on which one to keep. Full file here:

    package com.project;

    import android.app.Application;

    import com.imagepicker.ImagePickerPackage;
    import com.beefe.picker.PickerViewPackage;
    import com.facebook.react.ReactNativeHost;
    import com.facebook.react.ReactPackage;
    import com.facebook.react.shell.MainReactPackage;
    import com.facebook.soloader.SoLoader;
    import com.reactnativenavigation.NavigationApplication;

    import java.util.Arrays;
    import java.util.List;
    
    public class MainApplication extends NavigationApplication {

        private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
            @Override
            public boolean getUseDeveloperSupport() {
                return BuildConfig.DEBUG;
            }

            @Override
            protected List<ReactPackage> getPackages() {
                return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    new ImagePickerPackage() //<-- packages here with react-native-navigation do nothing
                );
            }
      };

    @Override
    public boolean isDebug() {
        // Make sure you are using BuildConfig from your own application
        return BuildConfig.DEBUG;
    }

    protected List<ReactPackage> getPackages() {
        // Add additional packages you require here
        // No need to add RnnPackage and MainReactPackage
        return Arrays.<ReactPackage>asList(
          new ImagePickerPackage(), //<-- had to move packages in here
        );
    }

    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return getPackages();
    }

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, /* native exopackage */ false);
    }
}

**Comment by dbelchev** [comment]
@ianataffinity Thank you so much for sharing this. As a programmer without native experience this really saved my life!!!
