### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'int android.view.View.getTop()' on a null object reference

### ISSUE THREAD

**Issue by damathryx** [wix/react-native-navigation#1555]
### Issue Description

I’m using SharedElementTransition and it crashes sometimes when I go back to previous screen.
![screen shot 2017-07-24 at 12 05 59 pm](https://user-images.githubusercontent.com/14576761/28507871-b58e0180-7068-11e7-9b06-e8f943ce1d79.png)

### Steps to Reproduce / Code Snippets / Screenshots
I am working on a forked of [movieapp](https://github.com/damathryx/movieapp)

### Environment
* React Native Navigation version: 1.1.84
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
Hey @damathryx 
I added a null check, it should be ok now. I'm wondering why the view was removed, perhaps state changed and ui changed in previous screen?

**Comment by damathryx** [comment]
@guyca  i still get the error after updating to latest.

**Comment by guyca** [comment]
@damathryx Can you create a project where this is reproducible?
Please provide information on how your are using SET. Is the "from" element in a ScrollView/ListView? Is it displayed conditionally by some value from `this.state`?

**Comment by damathryx** [comment]
@guyca 

the crash happens from [MovieList](https://github.com/damathryx/movieapp/blob/master/src/modules/movies/Movies.js) pops back to [Movies](https://github.com/wix/react-native-navigation/issues/1555#issuecomment-317681397)

> Is it displayed conditionally by some value from this.state?

No.

**Comment by ankitgroovy** [comment]
put this code in ViewVisibilityChecker.java

replace check mehod with this code

public static boolean check(@Nullable View view) {
        if (view == null) {
            return false;
        }
        try{
            final int top = getTopRelativeToContentView(view);
            final int scrollYInScreen = getScrollYInScreen(view);
            return top + view.getHeight() > scrollYInScreen;
        }catch (Exception e){
            return  false;
        }

    }
app will not crash

**Comment by zsajjad** [comment]
@guyca any update on this?

**Comment by 8of** [comment]
The issue is still here, unfortunately.
React Native *0.55.4*, *0.56.0*
Android 8
