### ISSUE TITLE
Hide showModal screen on swipe down.

### ISSUE THREAD

**Issue by srameshr** [wix/react-native-navigation#1557]
### Issue Description

Screen shown as modal, via ```showModal``` should hide on swipe down.

---
### Environment
* React Native Navigation version: 
react-native-cli: 2.0.1
react-native: 0.46.2
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator 10.2 ios

**Comment by guyca** [comment]
Detect the swipe gesture your self and dismiss the modal accordingly.

**Comment by joshuaflores** [comment]
@guyca forgive me if I'm wrong but the method you describe would dismiss the modal but wouldn't follow the gesture path.

I think this is the pattern @srameshr is referring to.

![pkx9b](https://user-images.githubusercontent.com/24797599/28938407-91c8b8a6-7853-11e7-97b4-cbed970c0594.gif)
[stackoverflow](https://stackoverflow.com/a/35205596)

If this is possible to achieve with a swipe gesture could you please share how to change the view controllers position to match the gestures y-coordinate.

**Comment by glendenning** [comment]
Has this functionality been added to wix react-native-navigation yet?

**Comment by guyca** [comment]
I don't see a reason for this to be supported in RNN. You can use any gesture tracking solution and dismiss the modal when the gesture reaches a certain threshold.
[react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) seems like a nice library for this use case.

**Comment by fokoz** [comment]
@joshuaflores  Have you found any solution ?

**Comment by fokoz** [comment]
I think right now swipe to close modal screen is very common on modern apps because the screen is high and some users have a short finger, so they will have a hard time to reach the close button on navBar. It is a bad UX now.

**Comment by joshuaflores** [comment]
@fokoz sorry I haven't used this library or rn in a while.

**Comment by fokoz** [comment]
@joshuaflores Which library are you using now ?

**Comment by joshuaflores** [comment]
@fokoz no library just decided to go native.

**Comment by SasjaVDD** [comment]
Not yet tried it myself. But using a library like [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) combined with [react-native-reanimated](https://github.com/kmagiera/react-native-reanimated) enables you to interact with the views and dismiss the screen (modal or overlay) when certain conditions are fulfilled.

Using a modal with:

`        screenBackgroundColor: 'transparent',
        modalPresentationStyle: 'overCurrentContext'`
allows you to 'see through'.

or an overlay and animate the slide in effect when it is shown.

**Comment by SuttonKyle** [comment]
I don't know if anyone's still looking for this, but I implemented a sort of hacky solution.  If you include  the prop
```
navigatorStyle: {
        modalPresentationStyle: 'overCurrentContext',
        screenBackgroundColor: 'rgba(255,255,255,0)'
},
```
in your `showModal` as suggested by @SasjaVDD above, then create a transparent `View` at the top of your modal, you can set the height of the `View` dynamically with `PanResponder` events, so that the modal content moves up and down in response to swiping and it appears that the modal is swiping up and down following your finger.  It's not the prettiest solution, but it seems to do the job.
