### ISSUE TITLE
How to dismiss modal in redux style?

### ISSUE THREAD

**Issue by messense** [wix/react-native-navigation#156]
Let's say I have a login modal, after I hit login button it dispatches a ``LOGIN_REQUEST`` action and calls a API to login. Then it dispatches a ``LOGIN_SUCCESS`` action and changes some states in the redux store.

Now I want to dismiss the login modal, how should I do that in redux style?

Surely I can pass a callback function through out the ``LOGIN_REQUEST`` and ``LOGIN_SUCCESS`` actions then invoke the callback after dispatching ``LOGIN_SUCCESS`` action, but it feels a little weird.

**Comment by guyca** [comment]
Hey @messense 
You can call `dismissModal` with out an actual instance of `Navigator`

```js
import {Navigation} from 'react-native-navigation';

...

function onLoginSuccessful() {
    Navigation.dismissModal();
}
```

**Comment by messense** [comment]
@guyca Thanks. It works.

But now I can not easily test my reducers because ``react-native-navigation`` tries to use platform specific extensions for the ``platformSpecific`` module but in my test setup Babel still try to use ``./platformSpecific`` which results in an error.

**Comment by messense** [comment]
After using the awesome [mockery](https://www.npmjs.com/package/mockery) package in my unittest setup, the error is gone.

```javascript
// Unit test module mocks
var mockery = require('mockery');
mockery.enable({
  warnOnReplace: true,
  warnOnUnregistered: false
});
mockery.registerMock('react-native-navigation', {
  Navigation: {
    dismissModal: function () {
      // do nothing
    }
  }
});
```

**Comment by guyca** [comment]
glad to hear @messense
