### ISSUE TITLE
App crash on start after cloning from github

### ISSUE THREAD

**Issue by alzalabany** [wix/react-native-navigation#1561]
### Issue Description

i setup github using `git init` command and push current app "which is working perfectly" to github.

i then cloned it from another machine. now every time the app starts it crash.

i'm not an ios developer so i cannot figure out exactly why it is crashing. the project in xcode and all files and libraries looks identical to me yet i cannot open app from any machine.

### Steps to Reproduce / Code Snippets / Screenshots

1. react-native init newApp;
2. .. follow installation guide to install react-native-navigation.
3. test app it works.
4. run git init, add, commit, and push to remote.
5. clone app from remote from another machine and run yarn install 

react-native link confirms that all lib. are linked properly.

---
### Environment
* React Native Navigation version: 1.1.7
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): IOS, didnt try android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
not related to RNN
