### ISSUE TITLE
Unable to change any style on startSingleScreenApp navbar

### ISSUE THREAD

**Issue by ramneekhanda** [wix/react-native-navigation#1563]
Unable to change any style on startSingleScreenApp navbar
```js
export var NavigatorStyle = {
  navBarTitleTextCentered: true,
  navBarBackgroundColor: '#000000',
  navBarTransparent: false,
  drawUnderNavBar: false,
  navBarTextColor: '#FFFFFF',
  navBarButtonColor: '#FFFFFF',
  navBarTextFontFamily: 'Exo2-Regular',
  topTabTextColor: '#ffffff',
  selectedTopTabTextColor: '#f4cd41',
  topTabIconColor: '#ffffff',
  selectedTopTabIconColor: '#f4cd41',
  selectedTopTabIndicatorHeight: PixelRatio.get() * 2,
  selectedTopTabIndicatorColor: '#f4cd41',
};
```
```js
Navigation.startSingleScreenApp({
    screen: {
      screen: 'myscreen.abc',
      navigatorStyle: NavigatorStyle,
    },
    passProps: {},
    animationType: 'slide-up',
  });
```
`static navigatorStyle = NavigatorStyle;
`
Not even the static navigatorStyle works.

If i start a a modal from this screen with same style then the styles correct themselves..

Please help this makes it very difficult to use this component.

See below how the fonts change after the modal is opened..

![navbarissue](https://user-images.githubusercontent.com/1538416/28578452-5f153894-718c-11e7-8085-4f9fad46bd8a.gif)

**Comment by guyca** [comment]
Please format your code

**Comment by ramneekhanda** [comment]
@guyca please help
