### ISSUE TITLE
Not able to change tab label with setTabButton.

### ISSUE THREAD

**Issue by ivangrga** [wix/react-native-navigation#1566]
### Issue Description
Not able to change tab label with setTabButton.

### Environment
* React Native Navigation version: 1.1.115
* React Native version: 0.44.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by guyca** [comment]
Unfortunately, changing tab label at runtime is not supported.
