### ISSUE TITLE
Back gesture opens drawer on iOS

### ISSUE THREAD

**Issue by aemdy** [wix/react-native-navigation#1568]
### Issue Description

Swipe from left to right opens drawer instead of navigating back on iOS.

### Steps to Reproduce / Code Snippets / Screenshots

- start single page app with drawer enabled
- push to another screen and define back button title so that back button is displayed
- open app on iOS devices, swipe from left

Result: swipe opens drawer instead of navigating back.

I want drawer to expand only when there's no screen user can go back to.

---
### Environment
* React Native Navigation version: 1.1.143
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): iOS (Android not tested)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug, iOS Release, iOS 10.3.3

**Comment by estuardoeg** [comment]
Hi @aemdy !

You have to use something like:

`this.props.navigator.setDrawerEnabled({
      side: 'left',
      enabled: false
    });`

This disables the drawer... and then enable the drawer only in main flow screens

`this.props.navigator.setDrawerEnabled({
      side: 'left',
      enabled: true
    });`

**Comment by aemdy** [comment]
Thank you, it works!

**Comment by mawansui** [comment]
Hi @aemdy, hi @estuardoeg , I tried to reproduce the trick with `this.props.navigator.setDrawerEnabled({})`, but have, unfortunately, failed in a strange manner. I have managed to **dis**able the drawer on a certain screen, however, I could not **re-** enable it again on another one (the latter being the main flow screen, while the former is being pushed to the stack later via `this.props.navigator.push({})` ).  Out of desperation I tried putting the line of code you are proposing in every method of the component lifecycle as described [in the React docs](https://facebook.github.io/react/docs/react-component.html) for both screens and still did not succeed. 

It seems to me that being a newbie in React Native development I am missing something, so could you please be so kind to tell me exactly where should I put this line in order for the drawer to work again on the main flow screen? 

Btw, my configuration is react-native 0.46.1, react-native-navigation 1.1.205, and I develop for iOS while testing the app on the Simulator. Thank you in advance!

**Comment by kholiavko-roman** [comment]
@mawansui , did you found the solution ? I have the same problem.

**Comment by gilsonmandalogo** [comment]
@mawansui @kholiavko-roman 
I had the same problem, and to fix it, I removed the disableOpenGesture, and on the first screen I placed setDrawerEnabled to disable drawer, and now you can control when your drawer are enabled or not.

```
Navigation.startSingleScreenApp({
  screen: {
    screen: 'login',
    title: 'Login',
    navigatorStyle: {
      navBarHidden: true,
    },
  },
  drawer: {
    left: {
      screen: 'drawer',
    },
    disableOpenGesture: true, //remove this line
  },  
});
```
