### ISSUE TITLE
Cannot read property 'setRootController' of undefined

### ISSUE THREAD

**Issue by andreatoso** [wix/react-native-navigation#1571]
I'm having this error when I launch the command "npm test" using Jest on both index.ios.js and index.android.js . I followed the instructions correctly and the navigation works, but the npm test gives me this error and I can't figure out why. What I am missing?

**Comment by Tomatoo** [comment]
+1

**Comment by jmknoll** [comment]
This is the same error that `react-native-navigation` throws if you haven't followed the iOS-specific setup through Xcode. [here](https://wix.github.io/react-native-navigation/#/installation-ios)

I don't have much experience with testing react-native apps, but my guess is that the test render isn't seeing the native code. Would love to hear from someone with more experience.
