### ISSUE TITLE
Cannot use toggleDrawer on iOS and Android

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [wix/react-native-navigation#1573]
### Issue Description

Cannot use toggleDrawer to open drawer. Followed exactly what the docs say.

`push` and `pop` still works though.

### Steps to Reproduce / Code Snippets / Screenshots

Calling `this.props.navigator.toggleDrawer` in any screen.

---
### Environment
* React Native Navigation version: 1.1.151
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): All / All

**Comment by Kosai106** [comment]
Works fine for me.

```js
<Button title='Open drawer' onPress={() => this.props.navigator.toggleDrawer()} />
```

**Comment by Maydar** [comment]
Same issue, but only on first load after installation =(
Very annoying =(

**Comment by Doko-Demo-Doa** [comment]
@Kosai106 Which RN version are you using? Should I downgrade my project?

**Comment by Doko-Demo-Doa** [comment]
Oh I got why. My code were originally looks like:

````
Navigation.startSingleScreenApp({
  screen: {
    screen: 'cabsule.Dashboard',
    title: 'Votre trajet',
    animationType: 'fade',
    navigatorStyle,
    leftButtons: [
      {
        id: 'sideMenu',
      },
    ],
    appStyle: {
      orientation: 'portrait',
    },
    drawer: {
      left: {
        screen: 'cabsule.SideMenu',
        passProps: {},
      },
    },
  },
});
````
The `drawer` object must be at the root object, so I modified it like so:

````
Navigation.startSingleScreenApp({
  screen: {
    screen: 'cabsule.Dashboard',
    title: 'Votre trajet',
    animationType: 'fade',
    navigatorStyle,
    leftButtons: [
      {
        id: 'sideMenu',
      },
    ],
    appStyle: {
      orientation: 'portrait',
    },
  },
  drawer: {
    left: {
      screen: 'cabsule.SideMenu',
      passProps: {},
    },
  },
});
```

Now it's working.
