### ISSUE TITLE
What is the differents of Push and show Modal?

### ISSUE THREAD

**Issue by XboxYan** [wix/react-native-navigation#1576]
### Issue Description
As title
[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by junedomingo** [comment]
Hi @XboxYan , try to play the example app [here](https://github.com/wix/react-native-navigation/tree/master/example)
also, the difference can be found [here](https://wix.github.io/react-native-navigation/#/screen-api?id=pushparams)
