### ISSUE TITLE
How to change Tab Bar Height

### ISSUE THREAD

**Issue by rad182** [wix/react-native-navigation#1582]
### Issue Description

Is this possible? I can't find anything in the `Styling the Tab Bar` documentation

---
### Environment
* React Native Navigation version: 1.1.154
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by guyca** [comment]
No possible. Probably will never be supported.

**Comment by Andrfas** [comment]
@guyca any reason why it is not supported? Many app designs have custom tab bar styles, and it would be great if wix navigation could handle that

**Comment by reyalpsirc** [comment]
@Andrfas I guess that we can still draw our own tabs with the desired height, hide the native ones and use the `switchToTab` function to make the custom tabs work

**Comment by alimek** [comment]
you can add this method to `RCCTabBarController.m` file:

```
- (void)viewWillLayoutSubviews {
  int height = 75;
  
  CGSize screenSize = [[UIScreen mainScreen] bounds].size;
  if (screenSize.height == 812) { // iPhone X
    height = 85;
  }
  
  CGRect tabFrame = self.tabBar.frame; //self.TabBar is IBOutlet of your TabBar
  tabFrame.size.height = height;
  tabFrame.origin.y = self.view.frame.size.height - height;
  self.tabBar.frame = tabFrame;
}
```

**Comment by adnanbabar** [comment]
@alimek 

How do I see my changes in react native. I changed few other properties in RCCTabBarController.m but can't see them when I reload the app

thanks

**Comment by ujwal-setlur** [comment]
@adnanbabar  You are changing native code, so you will have to recompile the whole app.

**Comment by adnanbabar** [comment]
@ujwal-setlur Thanks for your reply.

I did restart the whole app simulator and all but didn't see any changes. On a side note, I am using a fork version of react-native-navigation which is not sitting within node_modules. But I don't see that as an issue as long as I am linking the native-navigation xcode project from the correct location?

**Comment by ujwal-setlur** [comment]
Did you actually rebuild the xcode project from scratch?

**Comment by reyalpsirc** [comment]
@adnanbabar usually what I do is change the code directly on the main XCode project (through the Libraries group) and once it works, I fork the repository and put the code I changed in the fork.

After that I do `npm install git://github.com/gitusername/react-native-navigation#master --save` where **gitusername** is the username of the github account where the fork is and **master** is optional and can be the name of any branch.

**Comment by adnanbabar** [comment]
@ujwal-setlur I get an error saying #import <React/RCTRootView.h> not found in helper

@reyalpsirc Thank you for your reply I will try that. However, I have 'react-native' forked as well and all I have to do is change file in Xcode and save it and everything works. My react-native is within node_modules though.

**Comment by infaz** [comment]
You can use **tabBarOptions** to change height,width and color.
```
tabBarOptions: {
                style: {
                    width: windowsWidth,
                    height: 70,
                },
                labelStyle: {
                    fontSize: 14,
                    color: 'black',
                },
            }
```
