### ISSUE TITLE
App crash when showModal or Push screen in drawer

### ISSUE THREAD

**Issue by nimamyscreen** [wix/react-native-navigation#1584]
When I try to show a modal by clicking a button in drawer , app crash. I got this problem since I upgraded react native navigation from 1.1.136 to 1.1.158.

### Environment
* React Native Navigation version: 1.1.158
* React Native version: 0.46.4
* Platform:  (Android): 
* Device info : Samsung C5

**Comment by guyca** [comment]
Please provide stack trace.
