### ISSUE TITLE
On Drawer Close the App Crashes Immediately.

### ISSUE THREAD

**Issue by aritradgupta** [wix/react-native-navigation#1585]
### Issue Description

The first screen has 3 top tabs and a drawer. The drawer opens on sliding gesture but the app crashes immediately when I close the drawer. Any fix for this issue?

---
### Environment
* React Native Navigation version: 1.1.154
* React Native version: 0.46
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device/Android 7.0.0

**Comment by ZeratulDev** [comment]
same.
started yesterday. 

adb logcat :

> E/unknown:React( 6040): Received an ACTION_CANCEL touch event for which we have no corresponding ACTION_DOWN
E/unknown:React( 6040): Unexpected state: received touch event but didn't get starting ACTION_DOWN for this gesture before
W/unknown:React( 6040): Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["websocketFailed",{"message":"failed to connect to /10.0.2.2 (port 8097) after 10000ms","id":14}])
D/AndroidRuntime( 6040): Shutting down VM
W/dalvikvm( 6040): threadid=1: thread exiting with uncaught exception (group=0xa663f228)
E/AndroidRuntime( 6040): FATAL EXCEPTION: main
E/AndroidRuntime( 6040): java.lang.NullPointerException
E/AndroidRuntime( 6040):        at com.reactnativenavigation.bridge.EventEmitter.sendWillDisappearEvent(EventEmitter.java:28)
E/AndroidRuntime( 6040):        at com.reactnativenavigation.views.SideMenu$2.onDrawerClosed(SideMenu.java:149)
E/AndroidRuntime( 6040):        at android.support.v4.widget.DrawerLayout.dispatchOnDrawerClosed(DrawerLayout.java:848)
E/AndroidRuntime( 6040):        at android.support.v4.widget.DrawerLayout.updateDrawerState(DrawerLayout.java:818)
E/AndroidRuntime( 6040):        at android.support.v4.widget.DrawerLayout$ViewDragCallback.onViewDragStateChanged(DrawerLayout.java:2085)
E/AndroidRuntime( 6040):        at android.support.v4.widget.ViewDragHelper.setDragState(ViewDragHelper.java:881)
E/AndroidRuntime( 6040):        at android.support.v4.widget.ViewDragHelper$2.run(ViewDragHelper.java:338)
E/AndroidRuntime( 6040):        at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 6040):        at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 6040):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 6040):        at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 6040):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6040):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 6040):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 6040):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 6040):        at dalvik.system.NativeStart.main(Native Method)

>
