### ISSUE TITLE
Crash Toggle Drawer (Example project)

### ISSUE THREAD

**Issue by lovbrand** [wix/react-native-navigation#1587]
### Issue Description

When running Example project as is, app crashes without error message when toggling the drawer.

### Steps to Reproduce / Code Snippets / Screenshots

1. react-native run-android, app will NOT start
2. Fix the errors listed (cannot find edit@1x.png, delete@1x.png) by pointing towards edit.png and delete.png in the file /src/screens/Actions.js
3. react-native run-android, app WILL start
4. press Toggle Drawer, it will open
5. press outside of Drawer, it should close but the app crashes. The same applies when trying to swipe-close the drawer

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by lovbrand** [comment]
I have now tested on a Sony-device and it does work there.

It fails consistently on (Huawei) Honor 8-phone

**Comment by guyca** [comment]
@lovbrand This should have been fixed in v1.1.161

**Comment by lovbrand** [comment]
Thank you, this do indeed work from that version!
