### ISSUE TITLE
How to change topTabs style in single screen app(Android) ?

### ISSUE THREAD

**Issue by aritradgupta** [wix/react-native-navigation#1589]
### Issue Description

Is there any way to change top tabs style in single screen apps? I have tried putting styles in static navigatorStyle of each tabs.

---
### Environment
* React Native Navigation version: 1.1.142
* React Native version: 0.46
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device/Android N 7.0

**Comment by CodeXtinction** [comment]
same issue here,this is working for tabBased but not for single 

```
static navigatorStyle = {
    selectedTopTabIndicatorColor: 'red',
    selectedTopTabTextColor: 'green',
    topTabTextColor: 'blue',
}
```

**Comment by CodeXtinction** [comment]
#1049
