### ISSUE TITLE
set options and styling the drawer

### ISSUE THREAD

**Issue by shannoga** [wix/react-native-navigation#159]
Hi

Is there an option to control the drawer.
More specifically  - set the width of the open state, remove or change the shadow of the drawer when opened etc.
Thanks any way for this great component.
Shani

**Comment by andybbtt11** [comment]
+1, the ability to create full width drawers, remove shadows, etc would be great.

**Comment by marineb** [comment]
Yes, awesome component. And very interested in being able to control the shadow, make it more subtle. Thank you!

**Comment by GeorgeBorg** [comment]
+1

**Comment by megahertz** [comment]
When a new release with #578 will be published you can disable a drawer shadow using:
```
Navigation.startSingleScreenApp({
  ...,  
  drawer: {
    right: {
      screen: 'core.SideMenu'
    },
    style: {
      drawerShadow: 'NO'
    }
  }
});
```

**Comment by jasonnathan** [comment]
@shannoga okay to close this?

**Comment by aemdy** [comment]
I can confirm this works on v1.1.143

**Comment by filipef101** [comment]
what about android?
