### ISSUE TITLE
Blank Screen startTabBased iOS Release

### ISSUE THREAD

**Issue by JPig** [wix/react-native-navigation#1590]
### Issue Description

startTabBasedApp on iOS Device ( 6s Plus ) in Release mode unreliably starts up with a blank screen and only the bottom Tabs showing.

This is a weird one as it doesn't happen all the time, it only occurs every now and then.
The App Operates fine in Debug mode on Both Device and Simulator but as soon as its switched over to Release it every now and then shows up blank with only the Bottom Tab Bar showing and a Blank Screen/Component.

The Component seems to still mount as i placed alerts within and they still show, the component just doesn't seem to "render"

It also appears that when the View doesn't show, the App Continues to consume memory until the App eventually crashes.

### Steps to Reproduce / Code Snippets / Screenshots

* Large GIF Below, Perfectly Shows Bug though *

![out](https://user-images.githubusercontent.com/13819339/28705051-5785e73c-73b1-11e7-98ab-66788eedd13e.gif)

---
### Environment
* React Native Navigation version: 1.1.162
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info: iOS Device - ( 6s Plus ) - iOS 10.1.1  - Release only

**Comment by JPig** [comment]
@guyca @DanielZlotin 
i really do hate to be annoying but this is a pretty big problem for us as we are nearing launch, is there any chance someone could have a real quick look at this or even point me in a direction and i can try investigate it with more insight. any help would be greatly appreciated. Thanks.

**Comment by blairvanderhoof** [comment]
Same issue! Please help!

**Comment by blairvanderhoof** [comment]
I notice if i do an "alert('foo')" right before startTabBasedApp, it never shows blank. Some race condition?

**Comment by blairvanderhoof** [comment]
If I wrap the startTabNavigation in a setTimeout (no timer value, leave it blank), it seems to fix it.

**Comment by blairvanderhoof** [comment]
Actually, even with setTimeout, it still shows blank sometimes, especially after the app has been killed in the background and you try to access it again.

**Comment by JPig** [comment]
yeah thats when it occur's most for me too. its a very weird bug, and whats most annoying is the fact its unpredictable to reproduce.

**Comment by steven-luu** [comment]
I didn't make it clear in #1047 , but yes, I do see the same issues on startTabBasedApp.

**Comment by eliperkins** [comment]
Do you have an open source app to reproduce this? If so, I can look into it.

Without repro source code, I would advise for you to debug this using your source code.

**Comment by blairvanderhoof** [comment]
@JPig do you have a way to repro 100% in simulator?

**Comment by steven-luu** [comment]
HI @JPig I just re-read your 'Issue Description` and this struck out at me:

> It also appears that when the View doesn't show, the App Continues to consume memory until the App eventually crashes.

Are you using `screenBackgroundColor` by any chance?  Please read my updates on #1047 .  You might be hitting the same problem.

**Comment by JPig** [comment]
@steven-luu  I am actually using ```screenBackgroundColor``` and it was set to #fff so i just removed it and it seems to have fixed it i think 😀 .
due to the infrequency of the issue i will keep checking if it happens/occurs again but i am fairly certain that is the fix to the problem here.
thank you so much for managing to find that.
