### ISSUE TITLE
PopTo a particular screen.

### ISSUE THREAD

**Issue by srameshr** [wix/react-native-navigation#1591]
### Issue Description

API to popTo a particular screen in navigation stack.
```Main-Screen -> Camera-Screen -> Edit-Screen```
Now from ```Edit-Screen``` popTo the ```Main-Screen``` at once, without showing the ```Camera-Screen``` in the process.

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]
```
// In Edit-Screen
this.props.navigator. popTo({
  screen: 'MainScreen',
  animated: false,
});
```
---
### Environment
* React Native Navigation version: 1.1.139
* React Native version: 0.46.2
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Both / Release / Debug

**Comment by srameshr** [comment]
Any updates on this? Any heuristics on how to pop to a screen down the stack without popping the in-between screens?

**Comment by guyca** [comment]
Don't use push. Instead show a modal when appropriate and push into the modal. https://github.com/wix/react-native-navigation/issues/286#issuecomment-272523552

**Comment by mehdijjz** [comment]
@guyca this is not a real solution, I believe we need a `.popN` function to pop multiple pages

**Comment by fokoz** [comment]
@mehdijjz was right.
Sometimes, modal is not suit for every cases. It perhaps is a second flow but it is in the same context such as:
We are on Create post screen and then we press a category chooser button -> select main categories screen -> select child categories screen
After select child categories we should go back to create post screen directly.
Using modal on this case, it feels too much because it is just a minor flow within a main flow which is used just one place.

**Comment by guyca** [comment]
I don't agree. IMO The need for a `popN` method indicates a badly structured app. The solution should be to correct the product.

**Comment by fokoz** [comment]
@guyca
You think even if it is a minor flow, it should uses the modal right?
Or you have a better ui and ux the scenario above, don't tell me you will use modal, it is too much for just selecting category. I don't care about popN method or not but I want the best ux, easy and make sense.

**Comment by srameshr** [comment]
@fokoz I agree. Lets also be polite.

**Comment by guyca** [comment]
@fokoz The use case you've described fits perfectly for Modal.
-> Show parent categories screen modally
-> push/resetTo child category to modal
-> after child category is selected - dismiss the modal.

This is a classic modal use case.

**Comment by fokoz** [comment]
As you say.

**Comment by Tomatoo** [comment]
our use：

    Home -> push(sale.GoodInfo) -> showModal(report) -> push(some) ->  showModal(report) -> push(another) -> dismissModal()

i show two same ‘report’ modal(but the content is different) in the route stack. i want dismmissModal only pop top ‘report’ modal, but it dismiss two ‘report’ modal, any ideas？

**Comment by kevboh** [comment]
This is extremely common in apps, very much needed, and does not indicate anything other than the breadth of use cases traditional native navigation stacks have solved. Please reconsider dismissing this request.

**Comment by wellyal** [comment]
Any updates?

**Comment by srameshr** [comment]
Yeah @guyca. Any updates?

**Comment by Jlexyc** [comment]
Actually 2 features are really needed:
popTo (example: we are using flow: [register] -> [code enter] -> [loading] -> [success] screen, so if user did a mistake in code - it should return to [code enter] (pop), if user did a mistake in password/login it should go back to [register] (popTo [rigester]) in case of success go to [success] screen.

replaceStack (not with single screen, but with screen ierarchy like setViewControllers in iOS)
Example: original stack:
[dashboard] -> [add new item first screen] -> [add new item second screen] -> ... -> [success]
After success app should has state (with smooth transition to [item details] screen):
[dashboard] -> [item details] stack, where [item details] - opened screen with item that has been just created.

Modals doesn't help in here.

**Comment by shivawu** [comment]
I don't think it's fair to say `fix the product`. It's totally legit to have a UX that pops several views at once, or go to specific view and manipulate the view stack as the design wants. As a navigation framework, providing the most basic operation so that they can be composed together to create any user experience is probably the way to go.

**Comment by guyca** [comment]
`popTo` is implemented in v2

**Comment by DavitVosk** [comment]
Hi guys. Could you find a solution for this? I don't find any wording for popTo in the documentation. Is it already in use?

**Comment by guyca** [comment]
@DavitVosk https://wix.github.io/react-native-navigation/v2/#/docs/screen-api?id=poptocomponentid
