### ISSUE TITLE
Can not see back button in Android

### ISSUE THREAD

**Issue by jonathan68** [wix/react-native-navigation#1592]
### Issue Description

I am using react-native-navigation in my RN app.
Back button is shown on iPhone but not on Android.
Why is this happening? What did I wrongly?
My code is like as below.

### Steps to Reproduce / Code Snippets / Screenshots

    const navProps = {
      title: 'Edit Profile',
      backButtonTitle: '',
      navigatorStyle: {
        navBarHidden: false,
        navBarBackgroundColor: 'rgb(240,240,240)',
        navBarButtonColor: DARK_GRAY,
        navBarTextColor: DARK_GRAY,
        topBarElevationShadowEnabled: true,
        shadowOpacity: 0.2,
        shadowOffset: 2,
        shadowRadius: 2,
        statusBarTextColorScheme: 'dark',
        navBarTextFontFamily: 'ProximaNova-Regular',
        navBarNoBorder: true,
      },
      navigatorButtons: {
        leftButtons: [{
          id: 'ProfileEditBack'
        }],
        rightButtons: [{
          title: 'Save',
          id: 'ProfileEditSave',
        }],
        animated: true
      },
    };
    routeScene('ProfileEditScene', null, navProps);

---
### Environment
* React Native Navigation version: 1.1.162
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Only Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android 6.0 - Samsung Galaxy S6

**Comment by guyca** [comment]
If you would like to use the default back button, you'll need to use id `back`.
If you'd like to use your own custom button, you'll need to provide an icon as well.

**Comment by jonathan68** [comment]
Nice work! Thank you!!!

**Comment by jamesDZ** [comment]
I am facing the same issue which is mention above, and according to the given solution I change the id: back,  but still i am not able to find the solution.
