### ISSUE TITLE
TopBar title does not appear in Android

### ISSUE THREAD

**Issue by jarvisluong** [wix/react-native-navigation#1593]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

Every topbar in my application (even with top API like startTabBasedApp, navigator prop push,... does not display top bar title.

### Steps to Reproduce / Code Snippets / Screenshots

I just do exactly in the docs.

---
### Environment
* React Native Navigation version: 1.1.134
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 5X, API 23, Android 6, Debug mode

**Comment by jarvisluong** [comment]
Update: as a workaround, I can still set the title of the view by using props.navigator.setTitle().
However, using title property does not make the title visible though.

**Comment by guyca** [comment]
Hey @jarvisluong 
Can you please try upgrading to latest version? IIRC This bug was fixed one or two weeks ago.

**Comment by jarvisluong** [comment]
Hi @guyca 
Upgrading does fix the problem with the text-only title, however, when I want the nav title to be an image, it didn't show up.

**Comment by jarvisluong** [comment]
Current react-native-navigation I'm using right now is 1.1.164

**Comment by guyca** [comment]
If you're referring to `titleImage`, then that property is supported only on iOS.
