### ISSUE TITLE
showModal() not working

### ISSUE THREAD

**Issue by aritradgupta** [wix/react-native-navigation#1595]
### Issue Description

this.props.navigator.showModal() not working on navigator button event.
I have a right button called 'search' on nav bar. Inside onNavigatorEvent() when that button is pressed I am calling this.props.navigator.showModal() but nothing happens. 

---
### Environment
* React Native Navigation version: 1.1.142
* React Native version: 0.46
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device/Android N 7.0

**Comment by aritradgupta** [comment]
I have a right button called 'search' on nav bar. Inside onNavigatorEvent() when that button is pressed I am calling this.props.navigator.showModal() but nothing happens.

**Comment by emin93** [comment]
Why is this issue closed? Any info on how it got solved? I'm experiencing the same issue in version `1.1.193` where the app crashes when i call `Navigation.showModal(...)` right after `Navigation.startTabBasedApp(...)`.

**Comment by guyca** [comment]
@emin93 If you're experiencing a crash - a crash log would help.

**Comment by emin93** [comment]
Okay i found out it was another module (react-native-app-intro) on the modal screen which has caused the crash. Sorry for the inconveniences.

**Comment by DavitVosk** [comment]
I have the same problem. I use `https://github.com/wix-playground/react-native-navigation-v1-v2-adapter` to switch from v1 to v2, and also I use 0.59.2 RN version. Now when I call `this.props.navigator.showModal` the modal is not opened though in logs I see that the screen's API is already called. Please help to understand what is going wrong there
