### ISSUE TITLE
Want to open a screen like modal over tab view.

### ISSUE THREAD

**Issue by jonathan68** [wix/react-native-navigation#1597]
### Issue Description

I launched app by **startTabBasedApp** function.
In this case, if I push screen, it's nested in current active tab.
But I want to open a screen over entire tab view, not in active tab view.
How can I implement this?

### Steps to Reproduce / Code Snippets / Screenshots

I tried **startSingleScreenApp**, but it closes main tab based application.

**Comment by jonathan68** [comment]
Can I have a super view which all tab views are rendered on?
Please help me. It's urgent issue for my project.

**Comment by alzalabany** [comment]
```
navigatorStyle = {
  tabBarHidden: true,
};
```
add this to your screen styles, it will hide the tabbar

**Comment by jonathan68** [comment]
Thank you.
