### ISSUE TITLE
[IOS]switchToTab error - could not find UITabBarController

### ISSUE THREAD

**Issue by neuberoliveira** [wix/react-native-navigation#1598]
### Issue Description
My app was built this way:

	Tab1
		ProductsList
			ProductDetail
				AnotherProductInfo #change to Tab2 from here (switchToTab({ tabIndex: 1 }))
	Tab2
		ListOfChoices #choices picked from 'AnotherProductInfo'

Now i want to navigate from `AnotherProductInfo` directly to `Tab2`, for now the code bellow work only on Android

	this.props.navigator.dismissAllModals({ animationType: "slide-down" });
	this.props.navigator.switchToTab({ tabIndex: 1 });

In the IOS i can reach to the Tab1 with `dismissAllModals()`, but when the `switchToTab()` is executed i get this error:

	Possible Unhandled Promise Rejection (id: 0):
	Error: could not find UITabBarController
	Error: could not find UITabBarController
	    at createErrorFromErrorData (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:4584:15)
	    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:4542:25
	    at MessageQueue.__invokeCallback (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:4864:16)
	    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:4713:16
	    at MessageQueue.__guard (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:4800:9)
	    at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:4712:12)
	    at http://localhost:8081/debuggerWorker.js:71:58

I found an related issue #284 but its too old and not solved yet.

---
### Environment
* React Native Navigation version: 1.1.134
* React Native version: 0.45.1
* Platform(s): IOS
* Device info: Simulator iPhone 5s 10.3 Debug

**Comment by ISevenSinsI** [comment]
Hi neuberoliveira,

It seems to be the issue has to do with `dismissAllModals()`
For us it fixed to to use `dismissModal` instead.

The last post in #284 (The issue you mentioned) explains it has something to do with this function unsetting several controllers.

**Comment by neuberoliveira** [comment]
@ISevenSinsI sorry i forget to mention, i already tried with `dismissModal()` but with the same result.

**Comment by sercanov** [comment]
I am also having this problem, it's happening when trying to `toggleTabs` just after dismissing modal.

RNN v1.1.377
RN v0.51

**Comment by veb** [comment]
Same here @sercanov

**Comment by efstathiosntonas** [comment]
@sotownsend same here, with this code: 
```
dismissModal = () => {
        Navigation.dismissAllModals({
            animationType: 'none'
        });

        this.props.navigator.switchToTab({
            tabIndex: 0 // (optional) if missing, this screen's tab will become selected
        });
        console.log(this.props.navigator)
    };
```

returns:
![screen shot 2018-03-16 at 10 37 57](https://user-images.githubusercontent.com/717975/37511066-21d93002-2906-11e8-9917-7682bdc30189.png)

**Comment by otusweb** [comment]
Anyone found a work around?

**Comment by sercanov** [comment]
It is a really annoying bug and can't even catch the rejection with `toggleTabs` so I can't come up with a workaround.

Any plans to fix, at least workarounds ?

**Comment by sapjax** [comment]
I found the situation we encounter this problem is that we call `Navigation.startTabBasedApp` twice in a short time (all of them are iOS,  the most is iPhoneX).

But we already don't know why the function is invoked twice, when we use `Navigation.startSingleScreenApp`, seems the singleScreen is rendered twice on these devices .

**Comment by karlmosenbacher** [comment]
I am using RNN with redux and when user signs out, the application starts singleScreenApp. I have tried console.log it and what I can see is that SingleScreenApp is only started once with the exact same error. The strange thing is that the same error is showed twice.

**Comment by pqkluan** [comment]
Hi everyone, I know this issue is not addressed yet. But since this is related to v1, we have to drop the supports to focus on working on v2.

If this issue, still occurs in v2, please create a new ticket for it. Thank you.

**Comment by linnett** [comment]
@pqkluan so you're saying that in v1, we are not about to dismiss a modal and then switch to a tab? this isn't being fixed at all in v1? it's a huge issue and v2 is nowhere near ready
