### ISSUE TITLE
Tabbar Screens should mount only when visited

### ISSUE THREAD

**Issue by mastermoo** [wix/react-native-navigation#160]
I noticed that in each Tab I have, the `componentDidMount()` method gets called, although I didn't visit the tabs, yet. So the app makes several API calls, when I start the app.
Am I doing something wrong? Or is it going to get fixed?

Thanks!

**Comment by guyca** [comment]
Hey @mastermoo This is the intended behaviour. We will be adding screen life cycle methods soon (`onVisible`, `onHidden` etc).

**Comment by mastermoo** [comment]
Awesome! Can't wait to use it 😊


		_____________________________

**Comment by Rmannn** [comment]
Any news on those lifecycles ?

**Comment by guyca** [comment]
@Rmannn 
https://wix.github.io/react-native-navigation/#/screen-api?id=screen-visibility
