### ISSUE TITLE
NavBar||TopBar styles not being applied globally [iOS]

### ISSUE THREAD

**Issue by Kosai106** [wix/react-native-navigation#1603]
### The goal

I'm trying to set all my navigation styles globally from one file to make customization easier in the future if required. Both my `tabsStyle` `appStyle` parameters are stored in a helper file called `navStyle.js` and then imported in my root `index.js` where I initialize the application.

### The problem

It doesn't quite work on iOS.

It all works perfectly on both platforms except for the navBar parameters on iOS, which it refuses to use unless I manually add the following on each of my screens:

```js
static navigatorStyle = {
	navBarBackgroundColor: colours.darkestGrey,
	navBarButtonColor: colours.white,
	navBarTextColor: colours.white,
}
```

This isn't a good solution and surely there must be a better way that I'm missing.

Here's a code snippet of my `index.js`

```js
import React, { Component } from 'react'
import { Navigation } from 'react-native-navigation'

import { iconsMap, iconsLoaded } from './utils/icons';
import { navigatorStyle } from './utils/navStyle'
import { registerScreens } from './screens'

iconsLoaded.then(() => {
	startApp()
})
registerScreens()

function startApp() {
	Navigation.startTabBasedApp({
		drawer: {
			left: {
				screen: 'Drawer'
			}
		},
		tabs: [
			{
				label: 'Home',
				screen: 'Home',
				icon: iconsMap['home'],
				title: 'Home',
				navigatorButtons: {
					leftButtons: [{
						id: 'sideMenu',
						title: 'Menu',
						icon: iconsMap['menu'],
					}]
				}
			},
			{
				label: 'Profile',
				screen: 'Profile',
				icon: iconsMap['user'],
				title: 'Profile',
				navigatorButtons: {
					leftButtons: [{
						id: 'sideMenu',
						title: 'Menu',
						icon: iconsMap['menu'],
					}]
				}
			}
		],
		tabsStyle: {
			...navigatorStyle,
		},
		appStyle: {
			...navigatorStyle,
		},
	})
}
```

And `navStyle.js`

```js
import { colours } from './colours'

export const navigatorStyle = {
	orientation: 'portrait', // Sets a specific orientation to the entire app. Default: 'auto'. Supported values: 'auto', 'landscape', 'portrait'
	forceTitlesDisplay: true,
	navBarTitleTextCentered: true,
	
	tabBarBackgroundColor: colours.white, // optional, change the background color of the tab bar
	tabBarButtonColor: colours.grey, // optional, change the color of the tab icons and text (also unselected)
	tabBarSelectedButtonColor: colours.black, // optional, change the color of the selected tab icon and text (only selected)
	
	statusBarColor: colours.darkestGrey,
	navBarBackgroundColor: colours.darkestGrey,
	navBarButtonColor: colours.white,
	navBarTextColor: colours.white,
	
	tabBarBackgroundColor: colours.darkestGrey,
	tabBarButtonColor: colours.grey,
	tabBarSelectedButtonColor: colours.white,
	selectedTopTabIndicatorHeight: 4,
	selectedTopTabIndicatorColor: colours.white,
	selectedTopTabTextColor: colours.white,
	
	topTabTextColor: colours.grey,
}

```

---
### Environment
* React Native Navigation version: 1.1.151
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, 10.3, Debug

**Comment by guyca** [comment]
AppStyle isn't implemented on iOS, if someone would like to implement it please contact me on discord

**Comment by Kosai106** [comment]
@guyca I know, but if you look at the code I provided, I'm also passing the parameters into `tabsStyle` which should work according to the documentation.

**Comment by guyca** [comment]
tabStyle only sets styles to BottomTabs (the native iOS `TabBar`)

**Comment by Kosai106** [comment]
@guyca That's good to know, but is there any way to set global styles for the navBar like how you can do it on Android?

**Comment by Tomatoo** [comment]
same question.

how to set navbarButtons global? it is stupid to set in every component.
