### ISSUE TITLE
[Android] Unsupported Modules Detected

### ISSUE THREAD

**Issue by bdebout** [wix/react-native-navigation#1604]
### Issue Description

Android Studio showed me the following error:

> **Unsupported Modules Detected**
> Compilation is not supported for following modules: react-native-navigation. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.

And this one after the compilation failed:

> Bundling `index.android.js`  25.0% (1/2), failed.
> error: bundling failed: "Unable to resolve module `../img/navicon_add@2x.ios.png` 

### Steps to Reproduce / Code Snippets / Screenshots

![build gradle module app](https://user-images.githubusercontent.com/25125506/28769198-d342944e-75da-11e7-955e-b00741c622d2.png)

![build gradle project](https://user-images.githubusercontent.com/25125506/28769208-e064efa0-75da-11e7-8e47-a56138cf6d56.png)

---
### Environment
* React Native Navigation version: 0.46.4
* React Native version: 1.1.65
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Archos (Android 7.0)

**Comment by Coolerfall** [comment]
Just remove `@2x` from `../img/navicon_add@2x.ios.png`.

**Comment by bdebout** [comment]
It still show me the same error without the '@2x' : 

> error: bundling failed: "Unable to resolve module `../img/navicon_add.ios.png`

**Comment by Coolerfall** [comment]
Your should name your image file like `navicon_add.ios@2x.png` and then use it like `../img/navicon_add.ios.png`.

**Comment by bdebout** [comment]
Yes I tried to do that and I still have the same error:

![tabs](https://user-images.githubusercontent.com/25125506/28773726-04fea8be-75eb-11e7-82fe-19b04a122f37.png)

![img folder](https://user-images.githubusercontent.com/25125506/28773729-089fd1fa-75eb-11e7-9b86-922a4fc07bc9.png)

**Comment by Coolerfall** [comment]
![image](https://user-images.githubusercontent.com/4580284/28773799-92d14066-761d-11e7-8000-f628b7d0b723.png)The file name should be `navicon_add.ios@2x.png`, but not `navicon_add@2x.ios.png`

**Comment by bdebout** [comment]
I misread your first comment, sorry ! I see it now. Thank you :+1:
