### ISSUE TITLE
Single screen app Nav Bar Right Button event on press not working

### ISSUE THREAD

**Issue by aritradgupta** [wix/react-native-navigation#1606]
### Issue Description

I have a single screen app with 3 top tabs on the first screen. On this screen I have two buttons, one left and one right. The left button is the "sideMenu" button which works fine. But the right button is not working. The icon is displayed properly but nothing happens when it is pressed. However, inside other screens the right buttons work perfectly, only on the first screen it is not working. 

---
### Environment
* React Native Navigation version: 1.1.150
* React Native version: 0.46
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Moto G4/Android 7.0

**Comment by wsslfnstr** [comment]
How did you fix it?
