### ISSUE TITLE
Cannot capture 'back' button click event

### ISSUE THREAD

**Issue by jonathan68** [wix/react-native-navigation#1607]
### Issue Description

I have two button in nav bar. Left is back button with 'back' id.
Right is save button with 'ProfileEditSave' id and 'Save' label.
Right button is working well. But I can't capture back button click event.
Do I need extra work for standard back button?

Also, second case doesn't show 'Back' label for left button on Android as well as cannot capture click event for this button. iOS is good.

### Steps to Reproduce / Code Snippets / Screenshots

      navigatorButtons: {
        leftButtons: [{
          id: 'back'
        }],
        rightButtons: [{
          title: 'Save',
          id: 'ProfileEditSave',
        }],
        animated: true
      },

      navigatorButtons: {
        leftButtons: [{
          title: 'Back',
          id: 'ProfileEditBack'
        }],
        rightButtons: [{
          title: 'Save',
          id: 'ProfileEditSave',
        }],
        animated: true
      },
---
### Environment
* React Native Navigation version: 1.1.150
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Debug

**Comment by guyca** [comment]
You need to set a left button with id `back`, refer to https://github.com/wix/react-native-navigation/issues/1135#issuecomment-297242323 for information on how to override back press
