### ISSUE TITLE
Strange tab bar behaviour on iOS

### ISSUE THREAD

**Issue by Jonas-Arvidsson** [wix/react-native-navigation#1608]
I have no issues on Android, this issue came up when starting the app on iOS for the first time.

First, here's a screenshot to summarise the issues
![screen shot 2017-07-31 at 190259](https://user-images.githubusercontent.com/10659501/28789852-55bd0ae8-7627-11e7-9347-488d59ff74e3.jpg)

I added the grey boxes. They are not related to the issue.

What you see in the image are the tab bar icons which for some reason are of different big sizes. Pressing the tab bar works so I can change between screens and the icons do change colour depending on what screen I'm on. 

Here is part of my code

```
  Navigation.startTabBasedApp({
    tabs: [
      {
        label: 'tab1', 
        screen: 'tab1', 
        icon: tab1Icon, 
        selectedIcon: tab1Icon, 
        iconInsets: { 
          top: 0,
          left: 0,
          bottom: 0, 
          right: 0 
        },
        title: 'tab1', 
        navigatorStyle: {}, 
        navigatorButtons: {} 
      },
      {
        label: 'tab2',
        screen: 'tab2',
        icon: tab2Icon,
        selectedIcon: tab2Icon,
        title: 'tab2'
      },
       {
        label: 'tab3',
        screen: 'tab3',
        icon: tab3Icon,
        selectedIcon: tab3Icon,
        title: 'tab3'
      },
  });
],
tabsStyle: { 
      tabBarButtonColor: 'black', 
      tabBarSelectedButtonColor: 'red',
      tabBarBackgroundColor: 'white'
    },

```
Any reason for why the tab icons behave this way?
---
### Environment
* React Native Navigation version: 1.1.138
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 10.3

**Comment by guyca** [comment]
the tabBar on iOS doesn't fit icons to correct size. You should use correct icon sizes. https://developer.apple.com/ios/human-interface-guidelines/graphics/custom-icons/
