### ISSUE TITLE
Change backButton image

### ISSUE THREAD

**Issue by pbassut** [wix/react-native-navigation#1611]
### Issue Description
I can change only the title of the back button and not the image?

---
### Environment
yarn list v0.24.5
├─ react-native-navigation@1.1.139
└─ react-native@0.46.4

**Comment by henrikra** [comment]
Looks like in `push` you can define that https://wix.github.io/react-native-navigation/#/screen-api?id=pushparams

**Comment by pbassut** [comment]
I can only set the title image and not the back button image using that push method. Right?

Em 1 de ago de 2017, às 15:15, Henrik Raitasola <notifications@github.com<mailto:notifications@github.com>> escreveu:


Looks like in push you can define that https://wix.github.io/react-native-navigation/#/screen-api?id=pushparams

**Comment by guyca** [comment]
You can set buttons when pushing screen. On which platform are you having issues? please include code sample.

**Comment by pbassut** [comment]
@guyca I'm not having issues with it. I'm just looking for a proper way to change the back button of every screen without having to manually specify the back button image every time I do a push

**Comment by guyca** [comment]
A naive approach would be to define a function that receives a navigator as params, and use it to push a screen and set the same custom left button each time.

```js
export default function push(navigator, screen, navigatorButtons) {
  navigator.push({
    screen,
    navigatorButtons: {
      ...navigatorButtons,
      leftButtons: [
        {
           // your custom button here
        }
      ]
    }
});
}
```
