### ISSUE TITLE
Apply style to every screen

### ISSUE THREAD

**Issue by pbassut** [wix/react-native-navigation#1612]
### Issue Description
I need to apply a style to every screen in the app. Like a universal style that can be overriden on push. 
For example, I need to have the same titleImage and backButton image for every screen.

---
### Environment
yarn list v0.24.5
├─ react-native-navigation@1.1.139
└─ react-native@0.46.4

**Comment by guyca** [comment]
Right now, AppStyle is supported only on Android. You can define your style someplace and spread it on each screen.

**Comment by pbassut** [comment]
So this a manual work? I mean, every time I add a new screen I have to apply that global style to it?

**Comment by pbassut** [comment]
I mean, of course I can find a way to automate it. I'm just asking if the library supports it.

**Comment by pbassut** [comment]
And I'm not using v2.
