### ISSUE TITLE
Are top tabs available on iOS?

### ISSUE THREAD

**Issue by Jonas-Arvidsson** [wix/react-native-navigation#1614]
Top tabs seem to be working fine on Android, but not on iOS. Can't find anything that says it isn't supported so I thought I should ask here.

If not, is this something that will be available in the future?

**Comment by guyca** [comment]
Hey @Jonas-Arvidsson 
They are not implemented on iOS - will probably be implemented only in v2 for both platforms.
Internally at Wix we use https://github.com/wix/react-native-custom-segmented-control

**Comment by Yasir5247** [comment]
Hi, Is Top bar now available
