### ISSUE TITLE
Icons only Tab Bar with correct height(no extra spaces under the icons)

### ISSUE THREAD

**Issue by longsangstan** [wix/react-native-navigation#162]
Hi,

Is possible to show icons only on Tab Bar with correct height? I know we can supply an empty string to `label` in `startTabBasedApp`, but there would be extra spaces originally reserved for text under the icons.

Thanks.

**Comment by agumack** [comment]
+1

**Comment by son021293** [comment]
Yesterday, I got the same issues. In iOS, I edit file RCCTabBarController.m 
`
Line 79: 
 // create the tab icon and title
    NSString *title = nil;
    id titleTabBar = tabItemLayout[@"props"][@"title"];
    if(titleTabBar) {
      title = titleTabBar;
    }
Line 99: 
 viewController.tabBarItem = [[UITabBarItem alloc] initWithTitle:title image:iconImage tag:0];
    if(title) {
      continue;
    } else {
      viewController.tabBarItem.imageInsets = UIEdgeInsetsMake(6.0, 0.0, -6.0, 0.0);
    }
`
That's working on iOS. And Android I still in progress with [https://github.com/aurelhubert/ahbottomnavigation](url)

**Comment by guyca** [comment]
Implemented in the next release

**Comment by Colmea** [comment]
I still have this issue on last version (2.0.0-experimental.174) on Android.

Is there a workaround ?

**Comment by YouHan26** [comment]
IOS have the same problem, version 2.0.0-experimental

**Comment by gameboyVito** [comment]
I am using .245 and still meet the same issue. And I am also using I18n in my app, is there any way to rerender the tabbar because I can't update the label of the tabbar dynamically
