### ISSUE TITLE
[Help Needed] Can't use scrollview inside drawer with animation type 'luvocracy'

### ISSUE THREAD

**Issue by rajaishwary** [wix/react-native-navigation#1620]
### Issue Description
with drawer animations in iOS, 
Can't able to use ScrollView inside side bar view.

### Steps to Reproduce / Code Snippets
    Navigation.startTabBasedApp({
        tabs,
        tabsStyle: {
            tabBarBackgroundColor: '#459A45',
            navBarButtonColor: '#ffffff',
            tabBarButtonColor: '#ffffff',
            navBarTextColor: '#ffffff',
            tabBarTextColor: '#ffffff',
            tabBarSelectedButtonColor: '#fff',
        },
        appStyle: {
            tabBarBackgroundColor: '#003a66',
            navBarButtonColor: '#ffffff',
            tabBarButtonColor: '#ffffff',
            navBarTextColor: '#ffffff',
            tabBarSelectedButtonColor: '#fff',
            statusBarColor: '#002b4c',
        },
        drawer: {
            left: {
                screen: 'example.Drawer',
            },
            type: "TheSideBar",
            animationType: "luvocracy",
        },
        animationType: 'fade'
    });

---
### Environment
* React Native Navigation version: 1.1.136
* React Native version: 0.44.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): 
    Simulator, Device, 
    OS version 10.3,
    debug and release.

**Comment by henrikra** [comment]
The link is broken

**Comment by rajaishwary** [comment]
@henrikra sorry, I left the example link in description.
to reproduce the issue, 
drawer type should be "TheSideBar" and animationType should be "luvocracy".
It seems that the pan view is in native animation controller.

**Comment by rajaishwary** [comment]
@guyca Can you please look into this issue ?

**Comment by awojtczyk** [comment]
Same issue here. @rajaishwary have you solved this somehow?

**Comment by rajaishwary** [comment]
@awojtczyk Nope, couldn't solved for type "luvocracy". I used another type of drawer animation in which scroll works. Ended up using following config.
// type: "MMDrawer",
// animationType: "door"
