### ISSUE TITLE
error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by SiddarthG** [wix/react-native-navigation#1621]
### Issue Description

I used react-native init to create project, and i followed the react-native-navigation installation guidelines for android, when  i run this command react-native run-android i get the following error:

/Users/guestsid/Documents/repos/NewProject/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactPackage.java:23: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:react-native-navigation:compileReleaseJavaWithJavac FAILED

### Environment
* React Native Navigation version: latest
* React Native version: latest
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Lenovo k5 note , Marshmallow
, debug

**Comment by guyca** [comment]
RNN doesn't support RN 0.47. Please downgrade to RN 0.46 for now.

**Comment by patw0929** [comment]
@guyca:
Could it be fixed by this PR #1628?
Thanks!

**Comment by ducpt2** [comment]
+1 issue here with RN 0.50.3.
