### ISSUE TITLE
You attempted to set the key `navigatorEventHandler` with the value `undefined` on an object that is meant to be immutable and has been frozen.

### ISSUE THREAD

**Issue by nik910** [wix/react-native-navigation#1622]
### Issue Description

I need navigator in the custom toolbar to navigate to a particular screen on clicking it

### Steps to reproduce
When setting navbar style using customView.

this.props.navigator.setStyle({
      navBarCustomView: 'example.chatConversationToolbar',
      navBarComponentAlignment: 'fill',
      navBarCustomViewInitialProps: {
        title: "Hello World",
        navigator: this.props.navigator
      }
    });

---
### Environment
* React Native Navigation version: 1.1.162
* React Native version: 0.43.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by nimerfarahty** [comment]
same issue , looking for someone to answer

**Comment by paalex** [comment]
having exactly the same issue, removing the icon doesn't help (error occurs regardless whether there's a button or not).
Anyone managed to solve this?

RN0.49.3
React Native Navigation version: 1.1.236
Platform: iOS (simulator)

**Comment by ReggaePanda** [comment]
is someone working on this to pass functions to `navBarCustomViewInitialProps`?

**Comment by ReggaePanda** [comment]
oh, I think this is fixed. I add my initial props to the static navigatorStyle.
`this.props.navigator.setStyle` in the constructor works fine :)
https://github.com/wix/react-native-navigation/issues/1546#issuecomment-346802727
#1546
