### ISSUE TITLE
[Help needed] - Get length of the navigator screens stack

### ISSUE THREAD

**Issue by nicolasjr** [wix/react-native-navigation#1623]
### Issue Description

I'm currently unable to find a way to determine the size of the screen stack on my navigation system. 
I'm using custom buttons that should behave differently according to which screen they are. I know that I can set different bars for each screen, but I'd like to keep them all under one single HOC and just set accordingly.

Is there a way to do it? Something like `navigator.length` would be nice.

**Comment by guyca** [comment]
There isn't a way to get the stack depth. Since this isn't a common practice in native development, I'm not sure we'll ever add such functionality.

**Comment by jsina** [comment]
@guyca I need this practice because I wanna check if the stack is on top and the is no parent top of the screen, I'm showing the alert message before closing the page. In fact I wanna force users to press the back button twice if they are on the top on the navigation.

**Comment by prateekm33** [comment]
@jsina did you find a work around for this?

**Comment by guyca** [comment]
@prateekm33 Perhaps you can use `commandType` prop
https://stackoverflow.com/questions/47915572/how-to-check-if-i-can-go-back-use-pop-on-react-native-navigation/47938786#47938786

**Comment by jsina** [comment]
@prateekm33 here is my code. 
```
import {
  BackHandler,
} from 'react-native';`
...

BackHandler.addEventListener('backPress', () => {
  if (tabs.indexOf(currentScreen) !== -1) {
    setTimeout(() => {
      backPress = 0;
    }, 3000);

    backPress += 1;
    if (backPress <= 1) {
      ToastAndroid.showWithGravity(
        strings.BACK_BUTTON_ALERT,
        ToastAndroid.SHORT,
        ToastAndroid.CENTER
      );
      return true;
    }
  }
  return false;
});
```
