### ISSUE TITLE
My project is not building on android when using the newest version of react-native

### ISSUE THREAD

**Issue by nromptea42** [wix/react-native-navigation#1625]
### Issue Description

I just got this error when trying to upgrade my project to react-native 0.47.1 and build on android

`node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactPackage.java:23: error: method does not override or implement a method from a supertype
    @Override
    ^`
### Steps to Reproduce / Code Snippets / Screenshots

In NavigationReactPackage.java,
`@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }`
I removed the `@Overrride` and it worked

### Environment
* React Native Navigation version: 1.1.134
* React Native version: 0.47.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device on Android 7.1.2

**Comment by NicholasBertazzon** [comment]
I'm on the latest version of react-native-navigation (172), react native 0.47.1 and I still have this issue.

**Comment by vinhtq** [comment]
Still not working for me.

Environment

    * React Native Navigation version: 1.1.134
    * React Native version: 0.47.1
    * Platform(s) (iOS, Android, or both?): Android
    * Device info (Simulator/Device? OS version? Debug/Release?): Device on Android 6.0.0

**Comment by hmenzagh** [comment]
Same Here
