### ISSUE TITLE
Drawer action not invoked when `dismissAllModels` used.

### ISSUE THREAD

**Issue by kusalshrestha** [wix/react-native-navigation#1632]
### Issue Description

I'm currently using side menu Drawer in iOS platform. And i got a case where more than 2 modals are shown in succession, one upon the other; So, I've used `dismissAllModels` to dismiss all the presented modals at once. Problem is when i use `dismissAllModels`, side menu drawer stops working.

---
### Environment
* React Native Navigation version: 1.1.x
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both in device & in simulator. And in both configuration

**Comment by gran33** [comment]
What do u mean by "stops working"? Gestures aren't open the drawer? If u explicit open the drawer by action on button, is it working?

**Comment by kusalshrestha** [comment]
Means side menu bar doesn't open @gran33

**Comment by elliotstokes** [comment]
I think im seeing the same thing. The hamburger drawer menu stops working once you call dismissallmodals. The gesture still opens it but then any code that specifically opens/closes the drawer not through a gesture fails (appears to be ios only for me)

**Comment by elliotstokes** [comment]
Dont suppose you came up with a workaround or a fix for this at all?
