### ISSUE TITLE
i want the navbar height and tabbar height both for android and iOS

### ISSUE THREAD

**Issue by ankitgroovy** [wix/react-native-navigation#1633]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]
please help me out on 
how to get the navbar and tabbar height for android & iOS ??

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: ^1.1.131
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): for all cases

**Comment by guyca** [comment]
google

**Comment by AndrePech** [comment]
```
getNavBarHeight() {

        if (Platform.OS == 'ios') {

            let d = Dimensions.get('window');
            const { height, width } = d;
            
            if(height === 812 || width === 812)
                return 88 // iPhone X navbar height (regular title);
            else
                return 64 // iPhone navbar height;
        } else
            return 54 //android portrait navbar height;
    }
```

**Comment by vdlindenmark** [comment]
@guyca I've Googled this and just found this link. What to do now? It feels like a loop if I Google it again ;-)

On-topic: Your comment is really bad...

BTW. @AndrePech's solution issn't working that good. For example an iPhone XS Max is smaller then 812px.

**Comment by paklau** [comment]
Try this tool: react-native-status-bar-height
