### ISSUE TITLE
Drawer in only one of the tabs

### ISSUE THREAD

**Issue by AhSem** [wix/react-native-navigation#1640]
### Issue Description

I started my application using Navigation.startTabBasedApp({...}). I passed in "drawer" as an argument, but all the tabs now have the drawer. 

How to only have the drawer in one of the tabs?

Thank you.
### Environment
* React Native Navigation version: ^1.1.171
* React Native version: 0.47.1
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 10.2. Debug mode.

**Comment by guyca** [comment]
You can disable the SideMenu when navigating out of the tab
https://wix.github.io/react-native-navigation/#/screen-api?id=setdrawerenabledparams-
