### ISSUE TITLE
Plan for redux support in v2? (HOC support)

### ISSUE THREAD

**Issue by gtchance** [wix/react-native-navigation#1642]
I'm looking to switch from v1 to v2, but the first thing I noticed was that when registering containers, you can no longer pass in the store and Provider. Is this in the roadmap?

**Comment by DanielZlotin** [comment]
I don't think it's necessary to add any specific support for redux or any other data flow library, all you need to do is wrap your screens in a higher order component `<Provider store={store}/>`.

I automatically pass all props through to the inner implementation of `Container` so it should just work.

Open an issue if you see a specific problem with redux

**Comment by em222iv** [comment]
@DanielZlotin Would you please post an example of how to accomplish this with v2? I'm having a hard time implementing redux with the new v2 structure of registerContainer

**Comment by DanielZlotin** [comment]
You can look at the integration test with redux here
https://github.com/wix/react-native-navigation/tree/v2/integration/redux it
provides a example.
If you encounter a specific problem please report

**Comment by jleed** [comment]
Is there example how to register containers with redux?

I tried to do this

`
			Navigation.registerContainer(item.name, () => {
				const Screen = item.screen;
				return (props) => {
					return (
						<Provider store={store}>
							<Screen {...props}/>
						</Provider>
					)
				}
			});
`

but it fails

Cannot read property 'didDisappear' of undefined
Cannot read property 'didAppear' of undefined

**Comment by vovkasm** [comment]
This should work:
```
  Navigation.registerContainer('FitHelper.ProgramList', () => {
    return class ProgramList extends React.Component {
      render () {
        return <Provider store={store}><ProgramListScene /></Provider>
      }
    }
  })
```
Under the hood, Navigation's component registry wraps that you return from creator to another component that gets ref from original component, so you need full subclass of React.Component here or refs will not work.

**Comment by pentarex** [comment]
@vovkasm it works, but is there a nicer, cleaner solution for this. I have like 11 containers. And passing it for every looks like overkill... or I am not getting it

**Comment by vovkasm** [comment]
You always can create HOC... something like this (not tested):
```jsx
function sceneCreator (sceneComp, store) {
  return () => {
    class SceneWrapper extends React.Component {
      render () {
        return <Provider store={store}>{React.createElement(sceneComp)}</Provider>
// may be this also works: return <Provider store={store}><sceneComp/></Provider>
      }
    }
  }
}
```
And use as:
```javascript
Navigation.registerContainer('screen.Test', sceneCreator(TestScene, store))
```

Or you mean runtime overkill? You anyway should pass react context (whats Provider do) to underling component hierarchy. As I understand RNN creates totally new hierarchy for every navigation container, so it is not very different from pass store one time for whole app (without RNN). If this ever will slowdown, it will be caused by another things... not `Provider` comp.

**Comment by pentarex** [comment]
thank you a lot, I meant lines of code overkill :D but yeah you are correct I can use function like that one.

**Comment by DanielZlotin** [comment]
Vladimir is correct. The only other option is to put this exact code into
the library, so it's exactly the same. If we support redux we have to
support every other state management under the sun..

**Comment by michael-gillett** [comment]
@vovkasm I had written my own HOC for redux with RNN v2, but I found that I needed to pass props in order to get access to the container ID. Are you saying this is handled internally by registerContainer?

**Comment by vovkasm** [comment]
@michael-gillett Note, I didn't design this library interface.

Yes, there is code duplication :-)
I think, redux can't be used inside RNN because it is not the only state management library in the world (see Daniel's answer).

But on the other hand, you have a liberty to implement different logic and code structure in your HOC and make something different with RNN root props and life cycle methods, e.g. you can pass this info into redux state.
I did not do it myself, so no code samples, sorry.

**Comment by michael-gillett** [comment]
@vovkasm Fair enough! thanks for the response

My HOC method works fine for my use case, it would be nice to be able to have the library handle it internally, but I understand Daniel's point about having to support all state management systems

**Comment by stoerebink** [comment]
@michael-gillett did you get the lifecycle methods working in the components? I'm running into the same issue where the methods are only available in my wrapper.

**Comment by tbazko** [comment]
@michael-gillett can you share code of your hoc? And when do you apply it?

**Comment by michael-gillett** [comment]
@tbazko Sure! I apply it when I register my screens like @vovkasm above in this thread and here is my actual component wrapper code

```js
import React, { Component } from 'react';
import { Linking, SafeAreaView, StyleSheet } from 'react-native';
import Navigation from 'react-native-navigation';
import { Provider } from 'react-redux';

export function registerContainerWithRedux(
  containerName,
  comp,
  store,
  Provider,
) {
  const generatorWrapper = function() {
    const InternalComponent = comp;

    return class Scene extends Component {
      constructor(props) {
        super(props);
      }
      render() {
        return (
          <Provider store={store} style={styles.container}>
            <InternalComponent
              ref="child"
              {...this.props}
            />
          </Provider>
        );
      }

      didAppear(id) {
        instance = this.refs.child.getWrappedInstance();
        if (instance && instance.didAppear) {
          instance.didAppear(id);
        }
      }

      didDisappear(id) {
        instance = this.refs.child.getWrappedInstance();
        if (instance && instance.didDisappear) {
          instance.didDisappear(id);
        }
      }

      onNavigationButtonPressed(id) {
        instance = this.refs.child.getWrappedInstance();
        if (instance && instance.onNavigationButtonPressed) {
          instance.onNavigationButtonPressed(id);
        }
      }
    };
  };

  registerContainer(containerName, generatorWrapper);
}

function registerContainer(containerName, generator) {
  Navigation.registerComponent(containerName, generator);
}

export default registerContainerWithRedux;
```

**Comment by tbazko** [comment]
@michael-gillett Thanks! Figured out as much, also using refs now.

**Comment by flavordaaave** [comment]
I had to extend @vovkasm 's HOC like this in order to make it work:
```
function sceneCreator(sceneComp, store, thirdparam) {
  class SceneWrapper extends React.Component {
    static options = {
      ...sceneComp.options,
    }

    render() {
      return (
        <Provider store={store}>
          {React.createElement(sceneComp, this.props)}
        </Provider>
      )
    }
  }
  return SceneWrapper
}
```

**Comment by jeprojects** [comment]
@michael-gillett Do you have any more example code on how to use / implement redux in RNN v2?

I tested your HOC, but I must be doing something wrong as I am getting this error:

> Unhandled JS Exception: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `Scene`.

**Comment by jeprojects** [comment]
Figured it out. I got confused because you already import Provider so I wasn't using that param when calling the function.

**Comment by DanielZlotin** [comment]
[There's an example for working with redux](https://github.com/wix/react-native-navigation/tree/v2/integration/redux)

**Comment by ashleydw** [comment]
This logic works fine, but how do you manage navigation state?

e.g. Opening a root of ComponentA which pushes a screen of ComponentB; if ComponentB changes the state, the application reloads back to the root of ComponentA (whereas it should stay on ComponentB it seems a full reload is performed.

**Comment by casperstorm** [comment]
I am using the suggested function from @vovkasm, however in order to get it to work, you need to return it:

```js
  sceneCreator(sceneComp, store) {
    return () => {
      return class Wrapper extends React.Component {
        render() {
          return (
            <Provider store={store}>{React.createElement(sceneComp)}</Provider>
          )
        }
      }
    }
  }
```

Use it like this:

```js
  registerScreens(store) {
    Navigation.registerComponent(
      'screen.id',
      this.sceneCreator(SomeScreen, store)
    )
  }
```

**Comment by Miras4207** [comment]
Answers above sure helped, but I was still facing issues with implementing screen life cycle. Solution provided by @michael-gillett is helpful, but does not solve the issue either (at least in my case).

At first, methods 'didAppear' and 'didDisappear' seem wrong. They could have never been called. According to [RNNv2 Screen Lifecycle](https://wix.github.io/react-native-navigation/v2/#/docs/Usage?id=screen-lifecycle) and _ComponentWrapper.js_, **componentDidAppear** and **componentDidDisappear** are used instead.

Another hinder in my way was the following error:
`To access the wrapped instance, you need to specify { withRef: true } in the options argument of the connect() call.`

Working solution for me is this:

**screens/index.js**
```javascript
import registerContainerWithRedux from '../config/registerContainerWithRedux';
import { Provider } from "react-redux";
import store from '../config/store';

import LoginScreen from './LoginScreen';

export const registerScreens = () => {
  registerContainerWithRedux('navigation.LoginScreen', LoginScreen, store, Provider);
}
```

**registerContainerWithRedux.js**
```javascript
import React, { Component } from 'react';
import { Navigation } from 'react-native-navigation';
import { Provider } from 'react-redux';

export function registerContainerWithRedux(containerName, comp, store, Provider)
{
  const generatorWrapper = function() {
    const InternalComponent = comp;

    return class Scene extends Component {
      constructor(props) {
        super(props);
      }
      
      static options = {
        ...comp.options,
      }

      render() {
        return (
          <Provider store={store}>
            <InternalComponent
              ref="child"
              {...this.props}
            />
          </Provider>
        );
      }

      resendEvent = (eventName, params) =>
      {
        instance = this.refs.child.getWrappedInstance();
        if (instance && instance[eventName]) {
          instance[eventName](params);
        }
      }

      componentDidAppear() {
        this.resendEvent('componentDidAppear');
      }

      componentDidDisappear() {
        this.resendEvent('componentDidDisappear');
      }

      componentWillUnmount() {
        this.resendEvent('componentWillUnmount');
      }

      componentWillReceiveProps(nextProps) {
        this.resendEvent('componentWillReceiveProps', nextProps);
      }

      onNavigationButtonPressed(buttonId) {
        this.resendEvent('onNavigationButtonPressed', buttonId);
      }
    };
  };

  Navigation.registerComponent(containerName, generatorWrapper);
}

export default registerContainerWithRedux;
```

And finally, in **LoginScreen.js**, you need to call **connect()** like this:
```javascript
connect(mapStateToProps, null, null, {"withRef" : true})(LoginScreen);
```

However, I find this not to be the final solution either. For example, I am unable to get events like **componentWillMount** to work, as refs are not ready at that state. The error I am getting is:
`TypeError: Cannot read property 'getWrappedInstance' of undefined`. Maybe someone could help out?

Overall, I wish React Native Navigation team came up with more friendly solution to redux users. Doing all of this nasty stuff is pain. Out of box feature for this would be just delightful. At its current state, I wonder it is production ready.

**Comment by nSimonFR** [comment]
I would like to complete other answers with the right props bound to the registered screen in order to be able to call `this.props.componentId` (Otherwhise it defaults to `undefined`):

```javascript
const withStore = (Screen, store) => () =>
  // eslint-disable-next-line react/prefer-stateless-function
  class Wrapper extends React.Component {
    render = () => (
      <Provider store={store}>
        <Screen {...this.props} />
      </Provider>
    );
  };
```

It might be possible to write it as a stateless component, but I haven't managed to make it work...

**Comment by Hiro5409** [comment]
+1

**Comment by nSimonFR** [comment]
I have worked on a fix on a fork of my own: https://github.com/nSimonFR/react-native-navigation/commit/5322ebf84786989714d02a6c024705b493cdbb35

I can use the Api just like in V1:
```javascript
Navigation.registerComponent(containerName, generatorWrapper, store, Provider);
```

But connect needs the withRef option in every registered container:
```javascript
connect(mapStateToProps, mapDispatchToProps, null, { withRef: true })(MyContainer);
```

It fits my needs as `componentWillMount`, `componentDidAppear` and other methods seems to be working properly.

I can make a PR for this, but i'm not sure about code coverage and my TS skills...

**Comment by Tamiyadd** [comment]
why this issue is closed? someone found working solution?

**Comment by sbayd** [comment]
Hey,

We are facing the same issue. We created a workaround thanks to helpful comments.

Is there any plan for supporting redux officially in v2?

**Comment by jaumevn** [comment]
Hi,

I'm facing the same issue, used the `registerContainerWithRedux.js` and worked fine until now. Now I'm getting the following error:

![img_1937](https://user-images.githubusercontent.com/884454/40714656-8af67292-6403-11e8-82c9-e68a7ff9fcab.PNG)

Which is related to these lines of code on `registerContainerWithRedux.js`.
```js
instance = this.refs.child.getWrappedInstance();
        if (instance && instance[eventName]) {
          instance[eventName](params);
}
```

**Comment by cayasso** [comment]
@jaumevn just declare the variable adding `const` or `var` in front of it `const instance = thiis.refs...`

**Comment by rendomnet** [comment]
Why this issue closed?

**Comment by jaumevn** [comment]
thanks @cayasso this is working!

**Comment by brenwell** [comment]
Hey guys V2 looks great! I tried to get redux going through all the different suggestions above but no luck. If anyone has a working solution for this, I would be extremely grateful.

Also want to add a +1 for keeping the same register support from V1 in V2

**Comment by rendomnet** [comment]
componentDidAppear is still not working with @Miras4207 solution

**Comment by AE0011** [comment]
any final solution?

**Comment by AE0011** [comment]
@Miras4207 
If we connect our component in this way:

**Comment by yusufyildirim** [comment]
Here is my fully working version HOC.

```javascript
import React, { Component } from 'react';
import { Provider } from 'react-redux';

export default function reduxHOC(Scene, store) {
  return class extends Component {
    static options = {
      ...Scene.options,
    }

    componentDidMount() {
      this.instance = this.refs.child.getWrappedInstance();
    }

    resendEvent = (eventName, params) => {
      if (this.instance && this.instance[eventName]) {
        this.instance[eventName](params);
      }
    }

    componentDidAppear() {
      this.resendEvent('componentDidAppear');
    }

    componentDidDisappear() {
      this.resendEvent('componentDidDisappear');
    }

    onNavigationButtonPressed(buttonId) {
      this.resendEvent('onNavigationButtonPressed', buttonId);
    }

    render() {
      return (
        <Provider store={store}>
          <Scene ref="child" {...this.props} />
        </Provider>
      );
    }
  };
}
```

 As @Miras4207  said, you should connect your components like this:
```javascript 
export  default connect(mapStateToProps, null, null, {"withRef" : true})(LoginScreen);
```

**Comment by DanielZlotin** [comment]
I understand the issue better now. So we are having a problem with how react works, it's a problem with supporting any HOC. The problem is we added useful and easy to use API (`static options`, additional lifecycle methods) but that comes at the price of having to delegate those methods from the HOC, because that's the one being registered. We have no access to the underlying "screen" component.

This is not easy to fix, at least not extensibly (the example above by @yusufyildirim is a good solution but it already breaks because we added another method `onSearchBarUpdated`).

Reopening the issue until we figure out the best solution. This is not a redux issue, it's supporting any HOC issue.

**Comment by sdc395** [comment]
React Native newbie here.  Could someone familiar with this issue and react-native-paper confirm my suspicions that this issue is the reason Paper components don't render correctly?  Paper uses a provider to supply theme data to components.  I've tried variations of the workarounds above but no luck so far.

Thanks

**Comment by traxx10** [comment]
Please has this issue been solved?

**Comment by ilovett** [comment]
Using the above @yusufyildirim 's HOC and `connect` I appear to be implementing this wrong, I get `Cannot call a class as a function`

Here is how I am registering:

```
import reduxHOC from 'app/routing/reduxHOC';

export function registerScreens() {
    Navigation.registerComponent('Alarm', reduxHOC(ConnectedScreenComponent, store));
```

**Comment by yusufyildirim** [comment]
@ilovett Hey, registerComponent expects a function as a second argument (which returns a component). You should change your code to this:

```
Navigation.registerComponent('Alarm', () => reduxHOC(ConnectedScreenComponent, store));
```

**Comment by ilovett** [comment]
Ah, thank you @yusufyildirim that allowed me to get it running.

I did notice with this patch that `this.props.navigator` is not being passed down to the wrapped component.

**Comment by LewisBr** [comment]
Using the above HOC's I'm running into "undefined is not an object (evaluating 'comp.options').

Is there any special way you're configuring your screens outside of connecting them to Redux?

**Comment by lan-nguyen91** [comment]
@traxx10 I think the HOC looks correct, and also the registerComponent looks correct too. But your mapStateToProps did not have `fetchAds`. Could you please reformat the code so people can better assist.

**Comment by LewisBr** [comment]
Using both @yusufyildirim and @Miras4207 HOC's I'm getting problems with the Scene/comp options. Is there any special way that you need to instantiate the Screen component?  Anyone have a fully working example out there for me to reference from?

**Comment by nenti** [comment]
@yusufyildirim solution only works if you are connecting to a single layer hoc. But the normal use case is, that multiple hocs are piped on top of each other. That way you are loosing access to the instance calls. I don't think the entire interface is feasible for production like this. Is there a discussion on this on any channel that can be joined?

**Comment by luskin** [comment]
We are using the following and so far no problems:

```
import { Provider } from 'react-redux'

const store = configureStore()
registerScreens(store, Provider)
```

```
const sceneCreator = (sceneComp, store, Provider) => {
  return () => {
    return class Wrapper extends React.Component {
      render() {
        return <Provider store={store}>{React.createElement(sceneComp)}</Provider>
      }
    }
  }
}

export function registerScreens(Store, Provider) {
  Navigation.registerComponent(Screens.Launch, sceneCreator(Launch, Store, Provider))
}
```

**Comment by luskin** [comment]
@Miras4207 great solution for now, any advice on getting static options to work? They seem to be undefined in the wrapper

**Comment by lan-nguyen91** [comment]
@DanielZlotin, thanks for doing this, Is this mostly for second layer of redux connect like:

`Hoc1(Hoc2(connect(Login)))`

Can you point us to sample code where we have to manually register all events.

**Comment by smooJitter** [comment]
I haven’t ran into this problem but it seems like this might help

https://github.com/mridgway/hoist-non-react-statics

**Comment by rendomnet** [comment]
@DanielZlotin with new version I have error when using solution from this  thread https://github.com/wix/react-native-navigation/issues/1642#issuecomment-396899419.

![image](https://user-images.githubusercontent.com/18900210/42612069-f817904e-85ba-11e8-93d4-883c77b737dd.png)

**Comment by tiempham** [comment]
@yusufyildirim. Why should we use "resendEvent" while react lifecycle still working? Thank.

**Comment by retyui** [comment]
@DanielZlotin 
[Documentation](https://wix.github.io/react-native-navigation/v2/#/api/ComponentEventsObserver?id=componenteventsobserver) is the best in the world!

> Can you point us to sample code where we have to manually register all events.

**Comment by DavidNorena** [comment]
any luck to get wrapper static options working ?

**Comment by nikhilponnuru** [comment]
After going through Integration tests for redux in the source code, this is what I came up and works well
````
import React, {Component} from "react";
import {Provider} from "react-redux";

export default reduxStoreWrapper= (ComponentToWrap, store) => {
    return () => {
        return class StoreWrapper extends Component{
            render(){
                return (
                    <Provider store ={store}>
                        <ComponentToWrap {...this.props}/>
                    </Provider>
                );
            }
        }
    }
}
```
Here {..this.props} is necessary for having componentId in props for every navigation screen which is required while pushing or poping screens in v2.

And while registering screen
`  Navigation.registerComponent('Varsity.App', ReduxStoreWrapper(App, Store));`

**Comment by DavidNorena** [comment]
What about the performance having a provider created every time we navigate trough screens, also, every screen gets its own provider ... does it impact the performance ?

**Comment by DanielZlotin** [comment]
The people have spoken... #3675
usage:
```
Navigation.registerComponentWithRedux(componentName: string, getComponentClassFunc: ComponentProvider, ReduxProvider: any, reduxStore: any): ComponentType<any>
```
