### ISSUE TITLE
passing function in passProps crash

### ISSUE THREAD

**Issue by alzalabany** [wix/react-native-navigation#1645]
### Issue Description

app crash without any warning in many cases with error " TypeError: Converting circular structure to JSON" when you pass data to passProps

it happens when passing Immutable objects, and functions.

### Steps to Reproduce / Code Snippets / Screenshots

1. create new project and install react-native-navigation

```
import { Navigation } from 'react-native-navigation';
// inside some component
Navigation.showLightBox({
    screen: SCREEN_NAME, // unique ID registered with Navigation.registerScreen
    passProps:{ crash: console.log },
    style: {
      backgroundBlur: 'light',
    },
  });
```
once you call this app will crash with "circular dependencies in JSON.stringify"

---
### Environment
* React Native Navigation version: ^1.1.165
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): simulator

**Comment by kyle-ssg** [comment]
@alzalabany Have you tried changing ```crash:console.log``` to ```crash:(err)=>console.log(err)```
