### ISSUE TITLE
2.0-experimental is published to npm as latest

### ISSUE THREAD

**Issue by ronaldheft** [wix/react-native-navigation#165]
https://www.npmjs.com/package/react-native-navigation

**Comment by smooJitter** [comment]
It's probably a lot to ask but is there a release note for this.  I haven't updated for a while because I remember reading about you all completely restructuring the "stack" . What's changed?

**Comment by guyca** [comment]
@ronaldheft marked 1.0.30 as latest. Thanks for reporting

@smooJitter We'll write a post describing the changes, plans for the future and future milestones.
