### ISSUE TITLE
how can i remove the history screens?

### ISSUE THREAD

**Issue by abellee** [wix/react-native-navigation#1656]
Example:
there is a screen A, and then I do push the screen B, finally I do push the screen C, when I do press the back button in screen C, I wanna back to the screen A directlly.
so I wanna know is there a method can let me remove the history screens(screen B) silently?

### Environment
* React Native Navigation version: master
* React Native version: 0.46.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): 6.0

**Comment by guyca** [comment]
Instead of pushing screen C, call [resetTo](https://wix.github.io/react-native-navigation/#/screen-api?id=resettoparams)

**Comment by potasium** [comment]
This is exactly what i want. But this time, when resetTo C screen, it doesnt have back button
