### ISSUE TITLE
Android: Cannot find library or import com.reactnativenavigation.activities.RootActivity

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#166]
Not sure what I'm doing wrong here. 

```
public class MainActivity   extends  com.reactnativenavigation.activities.RootActivity
```
results in 
```
Error:(68, 71) error: package com.reactnativenavigation.activities does not exist
```

I can see the library module in Android Studio. I've checked its listed as a module dependency in my main app.

**Comment by guyca** [comment]
hmm are you using `latest` in your `package.json`? try to use v 1.0.30 specifically

**Comment by adamski** [comment]
I'm now using 1.0.30 and still getting this error... I'm actually using a branch off current master https://github.com/adamski/react-native-navigation/tree/gradle-experimental but only difference is `gradle.build` file

**Comment by guyca** [comment]
Could be a gradle cache issue

**Comment by adamski** [comment]
Maybe... However i wasn't referencing `latest` so think it might be some other gradle issue. My project is nonstandard as I'm using the experimental gradle plugin (its originally generated as a JUCE C++ app via Projucer) I had to make a couple of adjustments

**Comment by adamski** [comment]
I tried deleting the Gradle cache and still same issue... investigating further.

**Comment by adamski** [comment]
Created an SO question: http://stackoverflow.com/questions/38730675/module-app-dependency-results-in-error-package-x-does-not-exist

**Comment by adamski** [comment]
Solved this issue - I just had to delete the `productFlavours` part of RNN's `build.gradle` as its not being used here..
