### ISSUE TITLE
toggleTabs does not hide white background animate = true

### ISSUE THREAD

**Issue by emileNetter** [wix/react-native-navigation#1660]
### Issue Description

When trying to hide bottom tabs , doing   

```
this.props.navigator.toggleTabs({
  to: 'hidden', // required, 'hidden' = hide tab bar, 'shown' = show tab bar
  animated: true // does the toggle have transition animation or does it happen immediately (optional)
});
```
only hides the buttons and the labels but not the white background. Setting `animated = false` resolves this issue.

### Environment
* React Native Navigation version: 0.46.4
* React Native version: 16.0.0-alpha.12
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device: OnePlus One android version : 7.1.2, debug

**Comment by guyca** [comment]
Use `drawUnderTabBar: true` so the screen is drawn behind the tab bar

**Comment by ziyafenn** [comment]
@guyca i have my `drawUnderTabBar: true` but the white background is still visible under the tabBar. Dunno what else i can do in this situation.
