### ISSUE TITLE
Best way to create searchbar in navigation on icon click

### ISSUE THREAD

**Issue by nitish24p** [wix/react-native-navigation#1661]
Needed help on what could be the best way to create a search input on the navbar with the material animation, on clicking the search icon attached screen

<img width="291" alt="screen shot 2017-08-08 at 4 48 12 pm" src="https://user-images.githubusercontent.com/13037986/29069664-74cca488-7c59-11e7-8399-1fdf66b41b2a.png">
<img width="306" alt="screen shot 2017-08-08 at 4 48 27 pm" src="https://user-images.githubusercontent.com/13037986/29069665-74ff889e-7c59-11e7-9064-6096ecf4ff2e.png">

**Comment by dev-two** [comment]
This was mentioned in #1361, so you can take a look on it.
