### ISSUE TITLE
getCurrentlyVisibleScreenId() without await?

### ISSUE THREAD

**Issue by jslz** [wix/react-native-navigation#1665]
### Issue Description

I want to get current screen name w/out having to use await.

### Steps to Reproduce / Code Snippets / Screenshots

https://wix.github.io/react-native-navigation/#/top-level-api?id=getcurrentlyvisiblescreenid

---
### Environment
* React Native Navigation version: 1.1.182
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all of them.

**Comment by guyca** [comment]
resolve the promise

**Comment by netojose** [comment]
The promise return something like "screenInstanceID6"
And is different from defined on registerScreen.
