### ISSUE TITLE
Unable to push a route in a modal

### ISSUE THREAD

**Issue by alexwasner** [wix/react-native-navigation#1666]
### Issue Description
I am attempting to push a route from a modal and it is not working. It is a fairly common scheme to open a modal and navigate within that modal these days. I asked on the Discord channel, but I think its dead. 

### Steps to Reproduce / Code Snippets / Screenshots
1. Open a modal with `showModal({screen:'Awesome.Modal'})`
2. From AwesomeModal, do a `.push({screen:'AwesomeModalSubpage'})`
3. Notice no page has been pushed
 
### Environment
* React Native Navigation version: 1.1.188
* React Native version: 0.44
* Platform(s): iOS
* Device info: All

**Comment by guyca** [comment]
When is `AwesomeModalSubpage` pushed? from constructor? CDM? after button press?

**Comment by alexwasner** [comment]
After a button press

**Comment by alexwasner** [comment]
@guyca  i.e. you open a modal of a profile which has a button for settings. Tapping settings would push the Settings page in instead of opening a new modal

**Comment by alexwasner** [comment]
Debugging it, in `platformSpecific`, `passProps.navigatorID = navigator.navigatorID` is undefined.
It is passing the `DedicatedWorkerGlobalSpace` as `this` instead of the navigator. I'm assuming this is not intended

**Comment by alexwasner** [comment]
doing ```this.props.navigator.push.bind(this.props.navigator)``` solves the issue. I don't think this should be needed

**Comment by michael-gillett** [comment]
I am facing the same issue in v2.2074, I'll look to see if its a similar cause
