### ISSUE TITLE
some feature requests/questions...

### ISSUE THREAD

**Issue by mastermoo** [wix/react-native-navigation#167]
Hey,
I have a couple of Feature requests/questions:
1. Can we change the color of the bottom border of the NavigationBar? The current one ist way to dark. Maybe we could at least make the default color lighter..
2. Can we change the Back Button to a different icon (without having to remove the BackButton for each screen and instead set a custom LeftButton with a different Icon)? Ideally by setting a property `backButtonImage` once in the params of `Navigation.start...()`.
3. Can we change the Title of the NavBar to a Custom Component, so we can place a SearchBar or 2 lines of Text, see below.

![photo 02-08-16 23 02 27](https://cloud.githubusercontent.com/assets/7849822/17346513/51bcba40-590b-11e6-89e7-7cf211d52123.jpg)
![photo 02-08-16 23 10 11](https://cloud.githubusercontent.com/assets/7849822/17346514/51bda0b8-590b-11e6-9fdd-cf42d0509a05.jpg)

Unfortunately, I have no idea how hard these features are to implement or if they are even possible.

**Comment by agumack** [comment]
Hi, I have same proble, and react-native-navigation not support at time.

I have resolved by, config navBarHidden=true and style header on special view.

: )

**Comment by mastermoo** [comment]
Yes I have the same solution right now. 
However, you are noticing the missing NavigationBar when you are pushing a new scene -> the NavigationBars don't blend in and it looks weird.

**Comment by messense** [comment]
Would be great to have 2 & 3.

**Comment by messense** [comment]
> However, you are noticing the missing NavigationBar when you are pushing a new scene -> the NavigationBars don't blend in and it looks weird.

It's really annoying.

**Comment by alfonsogacevedo** [comment]
+1 on 2 & 3. Also having custom components for left and right buttons would be great.

**Comment by ZionChang** [comment]
+1 on 2
