### ISSUE TITLE
Change EntryPoint For Navigators

### ISSUE THREAD

**Issue by nomoreboredom** [wix/react-native-navigation#1672]
### Issue Description

I am using React Native with Typescript, and my configuration currently requires me to use on mainactivity.java and mainapplication.java:
### Steps to Reproduce / Code Snippets / Screenshots

    public class MainActivity extends ReactActivity {
       /**
        * Returns the name of the main component registered from JavaScript.
        * This is used to schedule rendering of the component.
        */
        @Override
        protected String getMainComponentName() {
            return "UsnApp";
        }
    }
    
    public class MainApplication extends Application implements ReactApplication {
      private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        protected String getJSMainModuleName() {
          return "artifacts/index.android";
        }
        .....
      }
    ....
    }; 

In order for typescript to work, I have to change getJSMainModuleName(), however when I setup the installation for RNN the bundle is not found. 

I believe RNN itself points to index.android.js on root of the project, any idea how would I achieve to use both? I read somewhere that RNN changes the entryPoint depending on navigator, if that is the case is it even possible to change it to suit my case? 

NavigationApplication imported itself wraps ReactApplication, am I right? 
 
### Environment
* React Native Navigation version: 1.1.118
* React Native version: 0.47.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by grsmvg** [comment]
Did you solve this already?

**Comment by nomoreboredom** [comment]
Nope

**Comment by grsmvg** [comment]
I decided to go for React Navigation, since this looks more promising (backed by Facebook + isomorphic).

**Comment by dmexs** [comment]
I got my TypeScript working by putting the following in index.android.js:

`
import App from './artifacts/app';
`

And here's src/app.tsx:

```
import { Navigation } from 'react-native-navigation'

import { registerScreens } from './screens'

registerScreens()

// start the app
Navigation.startSingleScreenApp({
  appStyle: {
    navBarHidden: true
  },
  screen: {
    screen: 'LoginScreen'
  }
})
```
