### ISSUE TITLE
Lightbox with navbar is impossible?

### ISSUE THREAD

**Issue by jameskhamil** [wix/react-native-navigation#1677]
Hello, is it possible to use lightbox with a navbar? Doesn't seem so, but this is a convention in iOS.

**Comment by pqkluan** [comment]
If you want to display an overlay with Navigation Bar, why don't you using [showModal](https://wix.github.io/react-native-navigation/#/screen-api?id=showmodalparams-) instead of `LightBox`?

I'll close this issue, but feel free to re-open it if needed.
