### ISSUE TITLE
Please Help, this.props.navigator.push not working at all

### ISSUE THREAD

**Issue by humbss** [wix/react-native-navigation#1679]
I have the environment fully working, tested with tab app and now with Navigation.startSingleScreenApp

**my  entrypoint is:**

`AppRegistry.registerComponent('foodproject', () => App);`

**this is my App.js:**

```
import React from 'react';

import { Navigation } from 'react-native-navigation';

import { registerScreens } from './screens';

registerScreens(); 

// start the app
Navigation.startSingleScreenApp({
  screen: {
    screen: 'food.Tabs'
  }
  ,
  tabsStyle: {
    tabBarBackgroundColor: '#003a66',
    navBarButtonColor: '#ffffff',
    tabBarButtonColor: '#ffffff',
    navBarTextColor: '#ffffff',
    tabBarSelectedButtonColor: '#ff505c',
    navigationBarColor: '#003a66',
    navBarBackgroundColor: '#003a66',
    statusBarColor: '#002b4c',
    tabFontFamily: 'BioRhyme-Bold',
  },
  appStyle: {
        tabBarBackgroundColor: '#ccc',
        tabBarButtonColor: '#000',
        navBarTextFontSize: 32,
        forceTitlesDisplay: false,
        tabFontFamily: 'Avenir-Medium',
        tabBarSelectedButtonColor: '#f40057',
      }
}

);
```

When I try to navigate in onPress I'm facing this error:

E/ReactNativeJS( 4605): undefined is not an object (evaluating 'e.props.navigator.push')

this is my navigation code:

```
                 <TouchableHighlight underlayColor={'transparent'} onPress={() => this.props.navigator.push({
                                                                                                            screen: 'food.Promotion',
                                                                                                            title: 'Promoções'
                                                                                                          })}>
                          <Text style={{fontSize: 15,fontWeight:'bold', color:'#EEE', padding: 0}}>
                                  OUTRO
                          </Text>
                        </TouchableHighlight> 

```

**also I tried to add propTypes inside my class:**

export class LocationBar extends React.Component {

      constructor(props) {
        super(props);
        this.state = {
          scrollY: new Animated.Value(0),
        };
        console.log(props);
        console.log(this.props);
      }

      static propTypes = {
        navigator: PropTypes.object
      };

---
### Environment
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-native-elements": "^0.14.0",
    "react-native-navigation": "^1.1.188",
    "react-native-vector-icons": "^4.3.0"
* Platform(s): Android
* Device info: Samsung Galaxy S6

**Comment by braco** [comment]
Are you using redux? List your props and see what shows up

**Comment by humbss** [comment]
Hi @braco I have a very simple project, no redux for any flux engine, is it necessary? or recommended in order to use react-native-navigation?

below I printed the props before call the push:

I/ReactNativeJS(16229): Running application "food.Tabs" with appParams: {"initialProps":{"screenInstanceID":"screenInstanceID2","navigatorID":"navigatorID1_nav","navigatorEventID":"screenInstanceID2_events"},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON

**I/ReactNativeJS(16229): print props: {"style":[null,null]}**

**E/ReactNativeJS(16229): undefined is not an object (evaluating 'this.props.navigator.push')**

**Comment by humbss** [comment]
I got it working in the first level of components.. this error above happens in inner components

example:

App.js with startSingleScreenApp includes a screen component that the navigation push works pretty good... but, in second level of components inside this screen component I get this this.props.navigator undefined error.

**Comment by humbss** [comment]
I found a solution to my problem, may be this helps other non experienced developers to solve the same situation, seems that this is more a gap of knowledgment on react from my side... I don't know if this is the best approach but what I did to solve is pass the props to inner components this way:

        <View>
               <LocationBar {...this.props} /> 
        </View>

then components inside LocationBar are able to pick this.props.navigator
if this is not a good approach or in case of a better one, please comment here

**Comment by braco** [comment]
Yeah, that's right. You might want to just pass the one prop down with `navigator={this.props.navigator}`.

You can close this issue

**Comment by humbss** [comment]
thank you
