### ISSUE TITLE
How well does this package work with Win Phone new support of RN

### ISSUE THREAD

**Issue by kcfgl** [wix/react-native-navigation#168]
You guys have done an awesome job with this package. I'm thinking of switching over to it.  But unfortunately, I need to support Win Phone (I know).  I know you're working on Android now so I doubt you've moved into Win Phone.  But before I strip out the old Nav logic and implement this, I was curious if anyone has had experience leveraging this package when developing with the new react-native-windows plugin?

Thanks!

**Comment by guyca** [comment]
Hey @kcfgl I doubt we'll support Windows Phone any time soon, we simply don't have the resources for that. Sorry.
