### ISSUE TITLE
navBarCustomView flickers on iOS

### ISSUE THREAD

**Issue by braco** [wix/react-native-navigation#1680]
navBarCustomView works great except that it flickers between push/view transitions on iOS. It seems that it's not passing new props to the same view, but is instead reloading it entirely. Would you like me to take a look and submit a PR or will this be fixed?

**Comment by braco** [comment]
Ping @SudoPlz, are you in charge of this?

**Comment by SudoPlz** [comment]
Hey @braco , I haven't experienced this to be honest. Feel free to dig into this if you want to.

**Comment by jameskhamil** [comment]
I have some problem

**Comment by jackmew** [comment]
+1

**Comment by jackmew** [comment]
I solved this problem by setting customView in [navigationStyle](https://github.com/wix/react-native-navigation/issues/1844), instead [setStyle](https://wix.github.io/react-native-navigation/#/styling-the-navigator?id=setting-styles-dynamically).

**Comment by ugendrang** [comment]
+1
