### ISSUE TITLE
Milestone: Version 2.0.0

### ISSUE THREAD

**Issue by drorbiran** [wix/react-native-navigation#169]
So we thought that it will be a good idea to share with you our plans for [Version 2.0.0](https://github.com/wix/react-native-navigation/milestone/1).

The main purpose of this issue is to create a discussion about the version scope and overall architecture.
We'll start to use [Version 2.0.0](https://github.com/wix/react-native-navigation/milestone/1) milestone to collect all PRs and issues that will be a part of the version.
## The general goals for this version are:
- [react-native-controllers](https://github.com/wix/react-native-controllers) will be deprecated and fully merged into [react-native-navigation](https://github.com/wix/react-native-navigation).
- iOS - Redesign and Refactor
- Android - Redesign and Refactor
- Complete feature parity between Android and iOS
## The main feature that we are planning for this version are:
- [Screens lifecycle](https://github.com/wix/react-native-navigation/labels/Screens%20Lifecycle)
- [Pass props and functions](https://github.com/wix/react-native-navigation/labels/Passprops%20%26%20Functions)
- [Dynamic styling](https://github.com/wix/react-native-navigation/labels/Dynamic%20styling)

**Comment by explorigin** [comment]
Something that might be helpful is to list features that are planned in the future...but not for this version.  Since this is a redesign (new work), will it have features of the current release version (I'm thinking of the drawer mainly)?

**Comment by DanielZlotin** [comment]
@explorigin I agree.
We're gonna think of a way to organise all features / bugs better (@drorbiran 😄 ).. maybe wiki?
As for your question, yes, we're gonna have the same features (with few additions) as we have right now. The side menu is already implemented.

**Comment by DanielZlotin** [comment]
> ### Notice
> We are currently working hard on redesigning and refactoring this project with high quality and robustness in mind. As a result, issues and pull requests will take more time to process. 

> To avoid any confusion and breaking existing projects, all continuous development is published under the npm tag `next`, with version `2.0.0-experimental.x`. Once stable, we will publish it as `2.0.0`. **This version supports react-native `0.31.0`**.

> The last stable version is `1.30.x` with npm tag `latest`. **This version supports react-native `0.25.1`**.

**Comment by antoniochen0205** [comment]
hi, i want to know when will you finish the features that you planed for this version

**Comment by antoniochen0205** [comment]
I really want to when will you finish the feature 'Dynamic styling',  could you tell me
