### ISSUE TITLE
Swipe to dismiss prevents touches on the previous screen

### ISSUE THREAD

**Issue by blairvanderhoof** [wix/react-native-navigation#1692]
* Start with a view that has a single TouchableOpacity item.
* Upon tapping it, push to a new view.
* Now swipe to dismiss the view.
* Now try tapping that TouchableOpacity item. Notice it doesn't respond to touches. Tap again, it works.
* Compare this to not swiping to dismiss, but simply hitting the back button in the nav. Tapping works immediately instead of on the second try only.

**Comment by blairvanderhoof** [comment]
It looks like it was fixed here https://github.com/wix/react-native-navigation/issues/645 and then the bug was put back here https://github.com/wix/react-native-navigation/issues/930.  my buck is fixed with the patch from https://github.com/wix/react-native-navigation/issues/645.

Can we have the best of both worlds somehow?

**Comment by guyca** [comment]
Hey @blairvanderhoof 
I assume you're experiencing this bug on iOS. I can't reproduce it in our app or the example app.

**Comment by blairvanderhoof** [comment]
Hi yes iOS. That's odd, let me debug more.

**Comment by blairvanderhoof** [comment]
@guyca I found the correct repro

- Start with a view that has a single TouchableOpacity item.
- Upon tapping it, push to a new view **that has a scroll view**
- Now swipe to dismiss the view.
- Now try tapping that TouchableOpacity item. Notice it doesn't respond to touches. Tap again, it works.
- Compare this to not swiping to dismiss, but simply hitting the back button in the nav. Tapping works immediately instead of on the second try only.

Seems the view you push to must have a scroll view for the bug to show.

**Comment by blairvanderhoof** [comment]
@guyca I narrowed it down to this traverseAndCall block, if I comment it out, I don't get the issue: https://github.com/wix/react-native-navigation/blob/33e861478c46b110ad9b8fd58c5abe856d1b5745/ios/RCCViewController.m#L280-L286

**Comment by guyca** [comment]
@blairvanderhoof Thanks for the repro.

@gran33 I also managed to repro on our app in prod, I'll show you tomorrow.

**Comment by blairvanderhoof** [comment]
Any recommendations here? Could we remove that block?

**Comment by chrise86** [comment]
@guyca what is the solution here? I think https://github.com/wix/react-native-navigation/issues/1696 is the same issue too.

**Comment by superliwei** [comment]
I have this issue too.

**Comment by blairvanderhoof** [comment]
@guyca, @gran33 any update? Thanks

**Comment by superliwei** [comment]
@blairvanderhoof i did as you said,the issue is gone.

**Comment by blairvanderhoof** [comment]
@superliwei Awesome! I could make my own fork with the fix, but I don't want to diverge off their master.  Would be awesome if they could fix the issue, i'm sure it's more than just deleting that block of code as it's solving some other issue at the moment.

**Comment by markhomoki** [comment]
Any update on this? I am experiencing the same issue with v1.1.210.

**Comment by mobitar** [comment]
Same issue with v1.1.213.

**Comment by grundmanise** [comment]
I think this is fixed now? Can we close it?

**Comment by blairvanderhoof** [comment]
You’ll need to make the code fix I mentioned in master
