### ISSUE TITLE
the splash implementation 

### ISSUE THREAD

**Issue by supei328** [wix/react-native-navigation#1693]
I think the splash implementation is less friendly for the following reasons:
1. Process logic is not clear. It is now waiting for Startreactcontextonceinbackgroundandexecutejs to execute, but the timing of this execution is uncertain.
2. If you have a custom splash, it's a hassle to implement in Java or iOS code.

**Comment by guyca** [comment]
Hey @supei328 
I'm not sure what's the purpose of having splash screen in Js. The reasons for implementing it in native is to show some ui while the bundle is parsed (`startReactContextOnceInBackgroundAndExecuteJS`) which takes more time the bigger the bundle is.
V2 has made some changes and improvements in this matter, I suggest we revisit this issue in a month or two when v2 is in beta 👍
