### ISSUE TITLE
navBarHideOnScroll touch bug...

### ISSUE THREAD

**Issue by gilra2000** [wix/react-native-navigation#1696]
navBarHideOnScroll: true, 

FlatList

There is no response when flatList scrolling and clicking..
twice touch.. success

**Comment by chrise86** [comment]
I think I'm also getting this, or a similar issue. Oddly, it only seems to happen for me when swiping to go back. If I swipe to go back, it takes 2 taps to interact with the FlatList on the previous screen. If I press the back button (a custom button using `navigator.pop()` in my case) then it works fine 🤔

**Comment by chrise86** [comment]
@guyca do you have any idea why this would happen?
