### ISSUE TITLE
[iOS][Screen push] Flicker on an image

### ISSUE THREAD

**Issue by fokoz** [wix/react-native-navigation#1698]
### Issue Description

When I push some screen with full-width local image, it always has some flicker around image. I think because it starts loading too late. In many popular apps, feel like images have been loaded before the user push the screen. Right now I fixed the issue by using fadeIn-animated images, but I truely don't like this technique : (

I don't know if it is RN issue or RNN issue, sorry if it is the RN issue.

Thank you.

### Steps to Reproduce / Code Snippets / Screenshots

1. Create a screen with a full-width local image.
2. Push this screen.
3. You will see the image is flicker because it starts loading too late(about 50% of transition time until it starts loading).

---
### Environment
* React Native Navigation version: 1.1.128
* React Native version: 0.45.1
* Platform(s) : iOS 10.2
* Device info : Both Real and Simulator

**Comment by fokoz** [comment]
I will close now because It is only on debug mode.

**Comment by gonzalezchris** [comment]
@fokoz did you ever find a solution to this issue?
