### ISSUE TITLE
Overlay objects over navigation bar

### ISSUE THREAD

**Issue by edvinasbartkus** [wix/react-native-navigation#17]
Projects like [KBLNY/react-native-message-bar](https://github.com/KBLNY/react-native-message-bar) or [brentvatne/react-native-overlay](https://github.com/brentvatne/react-native-overlay) provide functionality to show message bar on top of navigation bar. However, with react-native-navigation there is no possibility to place any objects outside navigation screen.

Maybe just as there are `modal` and `lightBox` we could have on more type which would allow to place some components as overlays?

**Comment by pqkluan** [comment]
Close this issue since [lightbox](https://wix.github.io/react-native-navigation/#/top-level-api?id=showlightboxparams-) was implemented.

**Comment by RyanWarner** [comment]
What if we don't want to use the built in lightbox?

**Comment by guyca** [comment]
We've added an overlay API to v2 which will allow you to display react components wherever you want on the screen. You'll be able to control if an Overlay handle all touch events are let some events (Touch not within bounds of the actual react view) pass through.
