### ISSUE TITLE
Transparent Tab Bar like transparent Nav Bar

### ISSUE THREAD

**Issue by longsangstan** [wix/react-native-navigation#170]
Hi,

Is it possible to set Tab Bar to transparent like Nav Bar(i.e. `navBarTransparent: true`)?

From the docs(https://github.com/wix/react-native-navigation#styling-the-tab-bar) it seems that we cannot set Tab Bar to transparent directly. 

I have tried setting the Tab Bar color to something like `rgba(0, 0, 0, 0)` or `transparent` together with `drawUnderTabBar: true`, but the background would be dark instead of transparent.

**Comment by camunity** [comment]
@longsangstan did you find any fix for this issue yet?
