### ISSUE TITLE
Drawer screens not navigating

### ISSUE THREAD

**Issue by gokulkulkarni1987** [wix/react-native-navigation#1701]
### Issue Description

When we click any of the items in the Side menu, the content in the ContentView will not get replaced.

#### Android
resetTo ==> brings up all together new screen with no Hamburger.
push ==> will bring the screen up with back button, again removing hamburger.
popToRoot ==> nothing happens.

#### iOS
nothing happens for any of those all the three.

and also in iOS there is no hamburger icon at the top left.

### Steps to Reproduce / Code Snippets / Screenshots

I am using the following code to when user clicks on the bar,
```
this.props.navigator.resetTo({
      screen: 'user.Profile'
    });
```
OR

```
this.props.navigator.push({
      screen: 'sazen.Home'
    });
```
OR
```
this.props.navigator.popToRoot({
      screen: 'sazen.Home'
    });

```

Nothing seem to give the exact behaviour of a typical navigation drawer app.

---
### Environment
* React Native Navigation version: ^1.1.198
* React Native version: 0.47.0
* Platform(s) (iOS, Android, or both?): cases mentioned in details
* Device info (Simulator/Device? OS version? Debug/Release?): Android device with marshmallow and iOS simulator

**Comment by sksahil030** [comment]
facing the same issue

**Comment by pureblood** [comment]
Having the same issue. pushing from anywhere else in the screen works but not from drawer.

**Comment by pureblood** [comment]
in iOS problem lies with the fact that pushing from sideDrawer sends the drawer id of `controllerID1_drawer` while pushing from any other screen sends the drawer id of `controllerID1_nav0` to native code. These IDs are bound with instances of different classes and hence drawer cannot push the screens. I can take a look but I think someone else can do it far quicker.

**Comment by pureblood** [comment]
Probably should use `const navigatorID = navigator.navigatorID.split('_')[0] + '_nav';` in `push, pop, popToRoot` like you are using in `toggleDrawer`

**Comment by toadums** [comment]
You need to use deep links - normal navigation doesn't work. Counter intuitive, and the example is wrong.

Here is the solution

https://github.com/wix/react-native-navigation/issues/624#issuecomment-269692336

**Comment by gokulkulkarni1987** [comment]
@toadums I had followed the same comment that you mentioned. But that navigates to new page rather than replacing, i.e there will be no navigation drawer rather there will be a back button.

**Comment by gokulkulkarni1987** [comment]
@pureblood I did not get what you want me to do :(
Sorry as I am just a beginner to React Native, and hence for React Native Navigation as well, could you please elaborate the same so that I can try it and let u know.

**Comment by toadums** [comment]
@gokulkulkarni1987 you need to have the `onNavigationEvent` handler in whatever component you want to navigate inside of (not the drawer component).

For example if you had something like

```
Navigation.startSingleScreenApp({
      screen: {
        screen: 'app.Home',
        title: 'Home',
        navigatorStyle
      },
      drawer: {
        left: {
          screen: 'app.Drawer'
        }
      }
    });
```

Inside the `app.Home` component you would want to listen for `event.type === 'DeepLink'` and then do some sort of a switch or something

```
onNavigationEvent = (event) => {
// handle a deep link
    if (event.type == 'DeepLink') {
       this.props.navigator.resetTo({
         screen: 'Home',
         animated: false
       })
    }
}
```
I made a base class that all of my root pages extend that, in the `componentWillMount` set the 
`this.props.navigator.setOnNavigatorEvent(this.onNavigationEvent)`. You can read about that here

https://wix.github.io/react-native-navigation/#/screen-api?id=listen-visibility-events-in-onnavigatorevent-handler

If you put together the following two pieces, in the right space (not your drawer), you should be able to get something that works
https://wix.github.io/react-native-navigation/#/screen-api?id=listen-visibility-events-in-onnavigatorevent-handler

and 

https://wix.github.io/react-native-navigation/#/deep-links

**Comment by gokulkulkarni1987** [comment]
@toadums this worked for me thanks a lot.

I had used the same mechanism but I as using push instead of resetTo.

After using resetTo the navbar color gets changed. :(

**Comment by eduardomoroni** [comment]
I don't think this is an issue, actually is the expected behaviour as we can see [HERE ](https://wix.github.io/react-native-navigation/#/deep-links).
![image](https://user-images.githubusercontent.com/823150/29792993-ac47ff24-8c18-11e7-8b88-ac8f285060df.png)

I didn't know about that, It was having this Issue opened anyways 😛

**Comment by matthamil** [comment]
@eduardomoroni I completely missed over that in the docs. I've been struggling with figuring out how to navigate from the side drawer, so thank you :). Maybe the docs should include a blip [here](https://wix.github.io/react-native-navigation/#/screen-api?id=toggledrawerparams-) when someone looks up the API to open a side drawer since I assume most users will want the user to be presented with options to navigate to in a side drawer.

**Comment by gaultierq** [comment]
showModal is working though
