### ISSUE TITLE
resetTo componentWillUnmount issue

### ISSUE THREAD

**Issue by maxs15** [wix/react-native-navigation#1703]
### Issue Description

I'm having a screen with a modal displayed on top of it.
When calling ``resetTo`` to a different screen, the current screen componentWillUnmount isn't called.
If there is no modal, just the screen everything is working fine.

I've done many test showing modals and pushing views it's always to root view that isn't unmounted.
Looks like a critical bug happening when opening a modal.

---
### Environment
* React Native Navigation version: 1.1.198
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): IOS 10.2 / Debug

**Comment by srameshr** [comment]
Yes, this is happening.

Here is my scenario, I receive a push notification and the handler for that is in screen ```A```. Now I  navigate to screen ```C``` and in screen ```C``` I call ```resetTo({ screen: 'A' })```. It ends up firing notification handler again, even though no data is present to do so.

**Comment by drpiou** [comment]
I have the same issue. When I call `push` and then `pop`, `componentWillUnmount` is fired. But if I call `resetTo` then `componentWillUnmount` is not fired for the View beiing replaced.

**Comment by noambonnie** [comment]
I don't get unmount on dismissAllModals() either. Hope this can be resolved.
iOS, RNN 1.1.402, iOS simulator
