### ISSUE TITLE
Compatibility with react-native-gesture-handler (Overwriting createReactActivityDelegate())

### ISSUE THREAD

**Issue by DragonRaider5** [wix/react-native-navigation#1704]
Hey,
I am currently trying to use the package react-native-gesture-handler alongside with react-native-navigation.
It requires me to overwrite the createReactActivityDelegate() function (in the main Activity, which normally is a ReactActivity implementing createReactActivityDelegate()) like the following: https://github.com/kmagiera/react-native-gesture-handler/blob/master/Example/android/app/src/main/java/com/swmansion/gesturehandler/react/example/MainActivity.java
```
public class MainActivity extends ReactActivity {
  @Override
  protected String getMainComponentName() {
    return "Example";
  }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
        return new RNGestureHandlerEnabledRootView(MainActivity.this);
      }
    };
  }
}
```

However when extending your MainActivity from react-native-navigation's SplashActivity, there's no way (known to me) to insert a custom ReactActivityDelegate. Is there any way of doing it I don't know about? If not I might be forced to use another navigation solution :(

Thanks in advance!

---
### Environment
* React Native Navigation version: latest from v1
* React Native version: 0.47.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by njho** [comment]
Any luck with finding an answer for this?

**Comment by guyca** [comment]
Seems like this is resolved in alpha 32 https://twitter.com/kzzzf/status/933990771228860416
