### ISSUE TITLE
Adding navigator to custom navbar button (and custom nav component)

### ISSUE THREAD

**Issue by tmaly1980** [wix/react-native-navigation#1705]
What would it take to implement having this.props.navigator accessible to custom navbar buttons and custom nav components (which may already work, I don't quite know)? I know it was discussed at least in #1641 .

**Comment by MeKarina** [comment]
moving from https://github.com/wix/react-native-navigation/pull/1641

@eliperkins thank You for this..

how to use screen api such as navigator.push() for custom button..?? 
i did following but nothing is working...

```js
navigator.setOnNavigatorEvent((event) => {
  let {id} = event
  if (id == 'CustomButton') {
    alert('custom button is pressed') // not showing
    navigator.push({screen:'SomeScreen'})
  }
})
```

this gave me error when onPress is called...

```js
// CustomButton.js
import {Navigation} from 'react-native-navigation';

<TouchableOpacity onPress={()=> Navigation.push({screen:'SomeScreen'})}>
</TouchableOpacity>
```

this also give me error when onPress is called..

```js
// CustomButton.js

let {navigator} = this.props
<TouchableOpacity onPress={()=> navigator.push({screen:'SomeScreen'})}>
</TouchableOpacity>
```


passing props to parent screen also gave me error when onPress props is called..

```js
navigator.setButtons({
  rightButtons: [{
    id: 'CustomButton',
    component: 'CustomButton',
    passProps: {
      onPress: () => {
        alert('custom button is pressed')
        navigator.push({screen:'SomeScreen'})
      }
    }
  }]
});
```

**Comment by mxaly** [comment]
@MeKarina 
* ``` navigator.setOnNavigatorEvent((event) => ``` 
  it won't work, native event is not triggered from custom component


* > this gave me error when onPress is called...
 
  `Navigation.` does not expose `.push` top level API, it's available only in screen level API 



* case with:
  ```// CustomButton.js
    let {navigator} = this.props
    <TouchableOpacity onPress={()=> navigator.push({screen:'SomeScreen'})}>
    </TouchableOpacity>
  ```
  {navigator} is always undefined, if you will try to pass it from one of the screens, app 
  crashes (at least for me) with: 
  ```
  ```libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: Did not get valid calls back from JS: [[38,38,0,0,7,53,53,53,53,53,53,53],[5,5,1,1,1,3,3,3,3,3,3,0],[[8,"RCTView",11,{"pointerEvents":"box-none","flex":1}],[9,"RCTView",11,{"pointerEvents":"box-none","flex":1}],["Converting circular structure to JSON",
  [...]
  ```
  cc @eliperkins

* > passing props to parent screen also gave me an error when onPress props is called.
  
  props passed with passProps that are functions are omitted so this won't work too 

I'm dealing with this by using redux actions and checking changes in components where i'm triggering navigation events. However, this is a hack and it would be nice to have possibility to at least pass navigator as prop to the custom component. @eliperkins do you think you can help with that?

**Comment by henrikra** [comment]
@guyca Why there isn't `this.props.navigator` available to custom navbar button? This would be essential when making custom buttons to navbar :O

**Comment by saudpunjwani101** [comment]
any solution?

**Comment by luco** [comment]
+1 on this. It's almost useless without navigator props.

**Comment by saudpunjwani101** [comment]
Yes it is. I guess the only workaround is using deeplinks.

**Comment by brmk** [comment]
Can we have more attention on this? I think almost every app needs to call navigator from the navbar button. It would be nice to have the workaround documented somewhere

**Comment by saudpunjwani101** [comment]
You don't need a navigator instance in the custom button. You can use Deep link.

**Comment by henrikra** [comment]
@saudpunjwani101 Can you provide example code?

**Comment by eliperkins** [comment]
A gentle reminder: Pull requests to implement this functionality would be gladly accepted. +1's and requests to collaborators to implement the functionality do nothing to move this project forward. If you are interested in this being implemented, please open a pull request to add the functionality or use the subscribe button to know when there are status changes.

From my brief look at this, it looks like we need to pass the `navigatorID` to the button components, but I'm not sure the best way to do that.

Additional workarounds, as mentioned, are using deep links or using the global `Navigator`, such as showing modals or lightboxes (i.e., `Navigator.showModal` or `Navigator.showLightBox'`).

**Comment by saudpunjwani101** [comment]
@henrikra  in my case I had a custom button like this,

        import {Navigation} from 'react-native-navigation';

        const CustomButton = (props) =>
          <TouchableOpacity
           onPress={()=>Navigation.handleDeepLink({link:"shop"})}
           style={{flexDirection:'row', justifyContent:'flex-start'}}>
          <Icon name="ios-arrow-back" style={{fontSize:36,color:"#007aff"}} />
          <Text style={{marginLeft:5,marginTop:8, fontSize:16, color:"#007aff"}}>Shops</Text>
        </TouchableOpacity>

       export default CustomButton;

instead of doing props.navigator, import Navigation from the core library and use handleDeepLinks. Now when you press the button, it be called in the other component like this,

     class Category extends React.Component {
        constructor(props) {
        super(props);
        // you need this 
        this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
       }

      onNavigatorEvent(event) {
        if (event.type == 'DeepLink') {
            //when you press the button, it will be called here
            console.log("button pressed");
         }
      }


this was my case scenario. Hope it'll help you out a bit.

**Comment by ropilz** [comment]
IMHO the sample in the docs for Custom Navigation Buttons should make use of deep links to make it clear how to use it for newcomers.

**Comment by voidstarfire** [comment]
Created nice component for iOS only, ignores Android because that works out of the box with 'id'

```
/**
 * @providesModule ios-back-button
 */

// @flow

// NPM modules
import React, { Component } from 'react';
import { View, Text, Image, Platform } from 'react-native';
import { Navigation } from 'react-native-navigation';

// Custom modules
import { AppStyles, StyleConstants, DefaultNavigatorStyle } from 'styles';
import Touchable from 'touchable'; // Cross platform touchable.
 
const placeHolderImage = require('../assets/ios_back_arrow.png');

type Props = {
    title: ?string,
    id: ?string
};

type State = {
};

/**
 * Back button for iOS, needed so we can override it.
 */
export default class iOSBackButton extends Component<any, Props, State> {

    state: State;

    constructor(props: Props) {
        super(props);
    }

    render() {
        return (
            <Touchable {...this.props} onPress={() => Navigation.handleDeepLink({ link:this.props.id })}>
                <View 
                    style={{
                        flexDirection: 'row',
                        alignItems: 'center'
                    }}>
                    <Image 
                        source={ require('../assets/ios_back_arrow.png') }
                        resizeMode={'contain'}
                        style={{
                            width: 16,
                            height: 21,
                            marginRight: StyleConstants.marginSmall,
                            marginLeft: -(StyleConstants.marginMed + 1) // Minus padding to remove hidden back button padding.
                        }}
                    />
                    <Text style={{ color: StyleConstants.white, fontSize: 17 }}>{this.props.title}</Text>
                </View>
            </Touchable>
        );
    }

    /**
     * Get the json config to override the screen navigation bar, for iOS only.
     * 
     * @param {*} title 
     * @param {*} id 
     */
    static getJsonConfig(title: ?string, id: ?string) {
        if (Platform.OS === 'ios') {
            return {
                leftButtons: [
                    {
                        id: id,
                        component: 'iosBackButton', // This line loads our component as a nav bar button item
                        passProps: {
                            title: title,
                            id: id
                        }
                    }
                ]
            }

        } else {
            return {};
        }
    }

    /**
     * Was the back button pressed from the navigation listener event.
     */
    static wasBackButtonPressed(event: any) {
        if (event.type == 'NavBarButtonPress' || event.type == 'DeepLink') {
            if (event.id == 'backPress' || event.link == 'backPress') {
                return true;
            }
        }
        return false;
    }
}
```

**Comment by Maxor4** [comment]
Hey guys,

I ran into this problem also where I needed my custom NavBar to receive Deeplinks, in order to change the navBar style dynamically. After a few hours of struggle I scanned throught the docs and I finally found a workaround, it might help you guys.

Basically I set the ScreenVisibilityListener directly in my custom component and executed my changes on a specific screen event, like so : 

`import React, { Component} from 'react';
import {
    Keyboard,
    StyleSheet,
    Text,
    TextInput,
    TouchableOpacity,
    View
} from 'react-native';

import { Navigation } from 'react-native-navigation';
import {ScreenVisibilityListener as RNNScreenVisibilityListener} from 'react-native-navigation';

export default class NavigationBar extends Component {

    constructor(props) {
        super(props);
        this.state = {
            recherche: false,
            focusInput: false,
        };

        this.setListener()
    }

    setListener() {
        this.listener = new RNNScreenVisibilityListener({
            didDisappear: ({screen, startTime, endTime, commandType}) => {
                console.log('screenDisap', `Screen ${screen} displayed in ${endTime - startTime} millis after [${commandType}]`);
                if (screen === "reappro_mobile.CameraScreen")
                this.setState({
                    focusInput: false,
                })
            },
        });
        this.listener.register();
    }

    render() {
        if (!this.state.focusInput){
            return(this._OffFocusView())
        }
        else {
            return(this._OnFocusView())
        }
    }`

As the listener doesn't use navigator, no problem on that part.

**Comment by AvijitDutta95** [comment]
Hi @saudpunjwani101  i'm following your scenario for my one project to  handle onPress on custom nav button. But problem is when i'm pressed that button its render a three times automatically and i'm not able to debug this problem because from my end everything is ok. you can check last comment of my issue #2131

**Comment by rsimbu89** [comment]
> onNavigatorEvent(event) {
>     if (event.type == 'DeepLink') {
>         //when you press the button, it will be called here
>         console.log("button pressed");
>      }
>   }

I'm getting the attached error of undefined is not an object while calling this.props.navigator.setOnNavigatorEvent
![Screen Shot 2019-03-18 at 4 18 04 PM](https://user-images.githubusercontent.com/6513047/54525209-b19a1580-4999-11e9-83b3-da18c1690483.png)
