### ISSUE TITLE
Navbar items change size and colour when navigating back

### ISSUE THREAD

**Issue by chrise86** [wix/react-native-navigation#1706]
### Issue Description

When pressing the back button or swiping back you can see the navigation bar back button and title change appearance.

Normal:
![simulator screen shot 17 aug 2017 16 45 30](https://user-images.githubusercontent.com/616956/29421190-31475752-836c-11e7-87e7-9b3e8946783b.png)

During pop:
![simulator screen shot 17 aug 2017 16 45 34](https://user-images.githubusercontent.com/616956/29421206-3f9daacc-836c-11e7-9451-d2ca39f1f22a.png)

### Steps to Reproduce / Code Snippets / Screenshots

navigatorStyle:
```
navBarTranslucent: false,
drawUnderNavBar: false,
navBarTextColor: colours.bodyFont,
navBarTextFontFamily: fonts.body,
navBarButtonColor: colours.bodyFont,
navBarBackgroundColor: '#fff',
statusBarTextColorScheme: 'dark',
drawUnderTabBar: false,
tabBarTranslucent: false,
screenBackgroundColor: '#fff',
statusBarHidden: false
```

Also have this set in `AppDelegate.m` to adjust back button font, although it happens even when this isn't set:

```
[[UIBarButtonItem appearanceWhenContainedInInstancesOfClasses:@[[RCCNavigationController class]]] setTitleTextAttributes:@{NSFontAttributeName: [UIFont fontWithName:@"MyriadPro-Semibold" size:16]} forState:UIControlStateNormal];
```

---
### Environment
* React Native Navigation version: 1.1.85
* React Native version: 0.44.0
* Platform(s): iOS
* Device info: Simulator, Debug

**Comment by chrise86** [comment]
Turns out it was due to pushing from a screen that wasn't setting the same colours as it was using `navBarHidden: true`.

**Comment by dobiedad** [comment]
Cheers ! you just saved me a lot of pain !

**Comment by Renattynha** [comment]
How can i solve this problem?
