### ISSUE TITLE
Best way to pass data back to parent screen?

### ISSUE THREAD

**Issue by MyGuySi** [wix/react-native-navigation#1708]
I'm working on adding a camera screen to capture some photos but I want to pass them back to the screen that pushed the camera (the parent) and can't seem to find the best way to do that with the current api.

I could do it with Redux but seems overkill. We can pass props then using `push()` but not back again when using `pop()`

Any suggestions?

**Comment by Rezania815** [comment]
you can pass a function as callback to camera screen and then call it.

in first screen: 
`
this.props.navigator.push({
  screen: 'app.CameraScreen',
  passProps: {
     onDone: (data) => console.log(data)
  },
})`

then call this.props.onDone(data) in Camera screen

**Comment by MyGuySi** [comment]
Now that I think about it, I think I tried that but didn't bind to the parent component so it wouldn't work properly.

Noob mistake... thanks!

**Comment by saeedvaziry** [comment]
solved my problem... thanks
