### ISSUE TITLE
A bridge instance is required to create an RCTRootView

### ISSUE THREAD

**Issue by hussam-almarzoq** [wix/react-native-navigation#171]
Hi,

I'm trying to get started with react-native-navigation but I'm getting this error when running this code.

Exception 'A bridge instance is required to create an RCTRootView' was thrown while invoking setRootController on target RCCManager with params (
        {
        children =         (
        );
        props =         {
            component = Home;
            id = "g6llc2jessg0k_nav";
            passProps =             {
                navigatorEventID = "hbset1y3m9cs8_events";
                navigatorID = "g6llc2jessg0k_nav";
                screenInstanceID = hbset1y3m9cs8;
            };
            style =             {
            };
            title = Welcome;
            titleImage = "<null>";
        };
        type = NavigationControllerIOS;
    },
    "slide-down",
        {
    }
)
And this is the code
```
Navigation.registerComponent('Home', () => Home);
Navigation.startSingleScreenApp({
  screen: {
    screen: 'Home', // unique ID registered with Navigation.registerScreen
    title: 'Welcome', // title of the screen as appears in the nav bar (optional)
  },
  animationType: 'slide-down' // optional, add transition animation to root change: 'none', 'slide-down', 'fade'
});

```

**Comment by brunolemos** [comment]
@hussam-almarzoq have you got it to work? how?

**Comment by brunolemos** [comment]
Fixed. I missed the last step from the Wiki, which is to replace your `AppDelegate.m` file with the one from the example.

**Comment by 13409795771** [comment]
@brunolemos 我也是蠢了 wiki最后一步没看 跟你一样。。 谢谢你解决了我的问题,但是我又出现了'RCTBridgeModule.h' file not found 这个问题

**Comment by dktsudgg** [comment]
@brunolemos  Thanks. you saved my ass with this
