### ISSUE TITLE
How to disable TabBar button color? Want to use the original color of the icon image.

### ISSUE THREAD

**Issue by spikeisryu** [wix/react-native-navigation#1710]
### Issue Description

Need to use images for TabBar buttons like these.
Normal
![timeline](https://user-images.githubusercontent.com/23102875/29449199-c844acc2-8434-11e7-9869-9a817f2a6271.png)
Selected
![timeline_rv](https://user-images.githubusercontent.com/23102875/29449217-d7e9d6e8-8434-11e7-9e3c-495f21ef6805.png)
and the background color of the TabBar needs to be a certain one.

Therefore, I used tabsStyle like this.

            tabsStyle: {
                tabBarBackgroundColor: '#AB013E',
            },

Then, the result shows like this.
![image](https://user-images.githubusercontent.com/23102875/29449328-34d56624-8435-11e7-8af6-2afdb4c29564.png)

It seems that the default button color is blue and it overwrite the color of the original image.

And I when I set a specific color, like 'white', then it still overwrite the color of the original image, like this.
![image](https://user-images.githubusercontent.com/23102875/29449463-d67cebd2-8435-11e7-9965-09b198c7bcfa.png)

I tried not to use tabsStyle, but it that case, I can't set the background color of the tab and the default color of the button, 'blue', still overwrites the image, like this.
![image](https://user-images.githubusercontent.com/23102875/29449560-2fd4a210-8436-11e7-84b8-ab101cab0537.png)

How can I use the original color of the button, not the tabsStyle settings?

---
### Environment
* React Native Navigation version: 1.1.130
* React Native version: 0.47.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 7, iOS 10.3

**Comment by saxahan** [comment]
This is exactly my deserving issue recently. Can anyone achieve this?

**Comment by ianataffinity** [comment]
You'll need a pull request to implement`disableIconTint` for TabBar icons.

For example in the docs:
https://github.com/wix/react-native-navigation/blob/d224bf4d3903ce16b287f5243c736aee67d30824/docs/adding-buttons-to-the-navigator.md

And implemented here in iOS (in Android too):
https://github.com/wix/react-native-navigation/blob/c62d944c2b10a841e531c05b45f88f18f902042a/ios/RCCNavigationController.m#L386

**Comment by gvillenave** [comment]
I started working on this PR and I got this done successfully for iOS and Android, with one caveat on iOS: the disableIconTint setting is not taken into account when calling setTabButton. The reason is that the tabsStyle properties are not accessible when calling setTabButton so we can't check.

I see two options to work around that:
1. Unify the behavior with Android and move those properties to appStyle, that way we can access them from the ViewController
2. Add iconColor and selectedIconColor parameters to the setTabButton function

Any ideas @ianataffinity?

**Comment by spikeisryu** [comment]
Sounds great! I think No.1 option might be better or both.

Looking forward to seeing your update!

Thanks!

**Comment by gvillenave** [comment]
I agree that option 1 sounds better, but I think that if we go down that road we should move all Tab Bar styling properties to appStyle instead of having 2 different places (https://wix.github.io/react-native-navigation/#/styling-the-tab-bar).

Any thoughts from maintainers?

**Comment by gvillenave** [comment]
Submitted PR #1943

**Comment by gvillenave** [comment]
I went too fast and missed something on Android. React Native Navigation uses https://github.com/aurelhubert/ahbottomnavigation on Android and it seems that this use case is not supported there (https://github.com/aurelhubert/ahbottomnavigation/issues/221).

This brings me back to option 2 above, where we could add an optional `color` parameter to `setTabButton` and potentially also to each tab in the call to `startTabBasedApp`.

Thoughts?

**Comment by spikeisryu** [comment]
I agree with you. Adding a color option to setTabButton and startTabBasedApp will be the right approach.

Thanks!

**Comment by gvillenave** [comment]
@guyca I'd like to get insights from the maintainers before moving forward with this PR, as it's a pretty significant change.

**Comment by gvillenave** [comment]
Submitted #1978, scoped to iOS for now.

**Comment by Crash--** [comment]
I think this PR should solve the problem : https://github.com/aurelhubert/ahbottomnavigation/pull/276 but I didn't succeed to use it in react-native-navigation (gradle is not my best friend yet)

**Comment by adtm** [comment]
Is this problem moving forward?

**Comment by bdavid68** [comment]
@Crash-- [Here](https://github.com/wix/react-native-navigation/pull/1723) is the solution for Android. But it's not merged. I don't understand why they don't merge this PR.

**Comment by Crash--** [comment]
You have cloned the entire ahbottomnavigation to the project, it's a good workaround for our user perspective but I can clearly understand why Wix don't merge this PR since every line of code added here will become Wix responsability. 

I think the only way to have it properly in RNN, is to merge your PR upstream.

**Comment by sercanov** [comment]
This is really annoying on Android if you're using colored icons. It tints the whole non-transparent pixels and there is no way to disable that tint.

Already tried to fork and play with `AHBottomNavigation` `setForceTint` but couldn't manage to make it working. 
Any workarounds ?
