### ISSUE TITLE
Map localization

### ISSUE THREAD

**Issue by AetherQuinque** [wix/react-native-navigation#1711]
I use this lib in Russia. On android and iOS device I got:
<img width="234" alt="2017-08-18 14 56 52" src="https://user-images.githubusercontent.com/20066332/29449792-5a383e96-8426-11e7-9f02-7e3c156f8c34.png">
Language of system - Russian. Can I fix that and take only Russian language for map?

**Comment by pqkluan** [comment]
I don't think your issue belong to this library but your map library.

The map library needs to provide a way to set the display data language.

**Comment by AetherQuinque** [comment]
Ooops, I'm so sorry, I just miss the tab) This issue for another library...

**Comment by henrikra** [comment]
@AetherQuinque Please close this
