### ISSUE TITLE
Push screen outside of TabBarViewController to use siwpeBackGesture

### ISSUE THREAD

**Issue by hhunaid** [wix/react-native-navigation#1712]
I have a tab-based app. I want to push a screen over the tabBarViewController. Right now it is achievable by pushing the screen from a tab and hiding the tab but the side drawer still remains there and sliding from left opens the drawer when I actually want it to transition back to previous screen.
For me the whole point of using this library was to be bale to use backSwipeGesture and other native stuff without tinkering too much.
Maybe if TabBarViewController can be put inside another NavigationController?

**Comment by pureblood** [comment]
Oh I can enable and disable drawer. nvm.

**Comment by pureblood** [comment]
One issue still remains. I am opening the screen from side drawer which means I have to use deeplinks which means I have to listen to deep links on each of the tabs. Is there a better way?
