### ISSUE TITLE
How to realize the i18n?

### ISSUE THREAD

**Issue by baijunjie** [wix/react-native-navigation#1718]
I want to dynamically switch languages, How do I render the navigation render `title` and `label`  again?

**Comment by gameboyVito** [comment]
You need to call startTabBaseApp again, it will reboot everything related to Navigation.

**Comment by baijunjie** [comment]
@gameboyVito Thank you, This is indeed a method.
But it can also cause applications to restart.
I would also like to have a method to render all the text without restarting the application.

**Comment by gameboyVito** [comment]
#925

**Comment by bdavid68** [comment]
@baijunjie i18n works based on your phone language.
If you change your phone language, all apps on your phone restart definitely.
So you can't switch languages dynamically using i18n.

**Comment by gameboyVito** [comment]
@bdavid68 no, you can use https://github.com/AlexanderZaytsev/react-native-i18n this library to achieve language switching.

**Comment by bdavid68** [comment]
@gameboyVito Yeah. I mean you can't switch language dynamically without restarting app.

**Comment by baijunjie** [comment]
@bdavid68 My app isn't just based on the language of the system, Users can also use Settings to dynamically switch languages, So I need to switch languages dynamically :)

**Comment by baijunjie** [comment]
I want to provide a way to update the tabLabel, So I don't have to restart the application.
I can only do so at present
```js
import { Navigation } from 'react-native-navigation';
import { registerScreens, registerScreenVisibilityListener } from './screens';
import Icon from 'react-native-vector-icons/Entypo';
import events from 'events';
import { getT } from 'i18n';

registerScreens();
registerScreenVisibilityListener();

let T = getT('screens');
let listIcon;
let userIcon;
let listIconProm = Icon.getImageSource('list', 30).then(source => listIcon = source);
let userIconProm = Icon.getImageSource('user', 24).then(source => userIcon = source);

Promise.all([listIconProm, userIconProm]).then(startApp);
events.Emitter.addListener(events.CHANGE_LANGUAGE, startApp);

function startApp() {
    Navigation.startTabBasedApp({
        tabs: [
            {
                label: T('IDList.name'),
                screen: 'IDList',
                icon: listIcon,
                title: T('IDList.name')
            },
            {
                label: T('UserSetting.name'),
                screen: 'UserSetting',
                icon: userIcon,
                title: T('UserSetting.name')
            }
        ],
        tabsStyle: {
            tabBarTranslucent: true
        }
    });
}
```

**Comment by NicholasBertazzon** [comment]
Already tried with redux?

**Comment by baijunjie** [comment]
@NicholasBertazzon It is not by the `state` to manage the `tabLabel`, thus `redux` didn't help on this issue.
