### ISSUE TITLE
Can I dismiss modal in the background?

### ISSUE THREAD

**Issue by kevando** [wix/react-native-navigation#172]
I have a modal that lets a user enter data. Upon successful entry, I would like the modal to dismiss and push to the screen of the newly created user data.

I cannot seem to push to the new screen without dismissing the modal, but every time I run dismissModal none of my navigator push functions work.

**Comment by guyca** [comment]
Hey @kevando,
It's possible you are trying to push to the screen stack that was bound to the modal, which you've just dismissed.

To push a screen, you require a `navigator` instance. That instance is bound to the current screen, or more specifically: to it's stack. You access that instance using `this.props.navigator`

If this is the case, you can dispatch an action to update the state with data user entered and dismiss the modal. Modals can be dismissed with out a `navigator` instance:
```js
import {Navigation} from 'react-native-navigation';
...
Navigation.dismissModal();
```

In `componentWillUpdate ` (of the screen that was displayed before you opened the modal) check if you have data and push your new screen using `this.props.navigator.push`
