### ISSUE TITLE
i want to reduce the space between navBarButtons

### ISSUE THREAD

**Issue by ankitgroovy** [wix/react-native-navigation#1725]
### Issue Description

i want to add 4 buttons at right in navBar
But the issue is it overlaps the title,
displaying title is mandatory for me,
 so how can i reduce space between buttons so that 
i can show all the contents 

### Steps to Reproduce / Code Snippets / Screenshots

add the multiple rightButtons on navBar

this.props.navigator.setButtons(
             {
                leftButtons: [
                        {
                         icon: iconsMap['menu'],
                         id: 'menu',
                         title:'Menu'
                        }
                  ],
                rightButtons: [
                        {icon:iconsMap['list'],id: 'list',title:'grid'},
                        {icon:iconsMap['euro-outer'],id:'euro',title:'euro'},
                        {icon:iconsMap['calendar'],id:'calendar',title:'date'}
                 ],
                 animated:true,
            });

![screen shot 2017-08-21 at 10 57 07 am](https://user-images.githubusercontent.com/30686066/29504755-972ee1ac-865f-11e7-8a16-4088e82f4501.png)

---
### Environment
* React Native Navigation version: 1.1.193
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): debug

**Comment by ghoshabhi** [comment]
Hello,

Was there a solution to this ?
