### ISSUE TITLE
Toggle drawer not functioning

### ISSUE THREAD

**Issue by MrVisitor** [wix/react-native-navigation#1727]
### Issue Description

Unable to open the right drawer. Opens only with a gesture. Using the method toggleDrawer call fails.

this.props.navigator.toggleDrawer({
          side: 'right',
          to: 'open'
        })

---
### Environment
* React Native Navigation version: 1.1.205
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): only Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Debug

**Comment by dima** [comment]
To add some more details to this bug report.

If you remove the ```to: 'open'``` parameter, it should open properly in debug mode. However, if you wipe data in emulator and start the app with ```--variant=release``` option set, the toggleDrawer function does nothing.

Registered ```onNavigatorEvent``` is fired correctly on menu item press and other navigator commands such as ```resetTo``` work correctly. However, nothing happens when ```toggleDrawer``` is called. What's even more weird is that if you close the app and then open it again the ```toggleDrawer``` call works properly.

**Comment by MrVisitor** [comment]
<img width="609" alt="2017-08-24 13 53 23" src="https://user-images.githubusercontent.com/7935653/29663412-a650daca-88d3-11e7-8727-7901cd7a5ca2.png">
When you remove the check on isShown, the toggleDrawer method works.

**Comment by MrVisitor** [comment]
<img width="670" alt="2017-08-24 13 56 20" src="https://user-images.githubusercontent.com/7935653/29663494-0f9feeee-88d4-11e7-8fb7-e9f5bc72ac0d.png">
I think, problem with isShown() function.
If you delete the isShown check, the toggleDrawer method its works.

**Comment by dima** [comment]
@MrVisitor If you play around with your solution in release mode (e.g. open/close app and try to toggle side menu) it doesn't work reliably. Sometimes the drawer works, sometimes it doesn't. Probably something else is involved. ```isShown()``` is implemented in the system level parent view ```android.view.View```

**Comment by cinder92** [comment]
in Android remove `to:"open"`

**Comment by MrVisitor** [comment]
@cinder92 Do you mean double brackets instead of single ?

**Comment by fmoessle** [comment]
i tried to remove `to:"open"`, but it did not work on android. iOS works fine

**Comment by em222iv** [comment]
+1
The drawer is not working reliably. It sporadically just doesn't open.
Tried removing to:"open", isShown-fix and so on.

Does anyone know if this is still an issue with v2? 

nav: 1.1.228
react-native: 48.3
Multiple devices: sony, huawei, samsung

**Comment by aksidn8** [comment]
Does your drawer's `screen` component have a fixed width? Adding a fixed width solved the problem for me.

**Comment by eeynard** [comment]
I have exactly the same behaviour @dima and any of the solutions mentioned above worked for me. Hope this would help #1997

**Comment by brainbrain34** [comment]
for me happen the same behavior sometimes work correctly and no other, without a pattern to find it out. After trying to different solutions with similar issues founded I fixed to set the width on the drawer screen by StyleSheet:
```
container: {
    flex: 1,
  },
´´´
👆 that didn't work so adding a width working with dimensions to be responsive work for me:
```
const { width } = Dimensions.get('window')
...
container: {
    flex: 1,
    width: width - 60,
  },
´´´

**Comment by yaibait** [comment]
@brainbrain34  thanks you , it work for me 👍
