### ISSUE TITLE
screenIsCurrentlyVisible() always returning false in iOS

### ISSUE THREAD

**Issue by MrPeproni** [wix/react-native-navigation#1728]
Hello,

I am using `const isVisible = await this.props.navigator.screenIsCurrentlyVisible();` in Android and it's working fine.

Now i am developing my app in iOS so this is returning false everytime
`const isVisible = await this.props.navigator.screenIsCurrentlyVisible();`

Please guide... where i am doing mistake and how can i solve this
Thanks in Advance :)

**Comment by jbolter** [comment]
Same issue here.
