### ISSUE TITLE
Navbar visible size less than it's actual size

### ISSUE THREAD

**Issue by SimchaShats** [wix/react-native-navigation#173]
On iPhone 4/4s a visible size of navbar almost twice less than it actual size, so it overlays part of the page and user can't touch stuff on the top of screen under navbar. On iPhone 5s it's actual size a little bit bigger then visible sizes but still some places on screen untouchable.

**Comment by 1800joe** [comment]
I have found this to be the case on iPhone 5 and 5s, but to a lesser degree.

**Comment by guyca** [comment]
@artald Have you ever noticed this?

**Comment by artald** [comment]
@guyca can't say I've noticed this issue.

We're using the native `UINavigationController` which actually reserves a very small extended touch area for the navigation bar buttons but it is not that noticeable, doesn't change from one device to another, and not in our control.

Not sure if I understand completely if that's the problem, or maybe that the screen content appears beneath the navigation bar and can be solved by applying`navigatorStyle` (drawUnderNavBar)?

**Comment by guyca** [comment]
Thanks @artald.

@SimchaShats @1800joe Can you confirm if this issue is related to [`drawUnderNavBar`](https://github.com/wix/react-native-navigation#style-object-format) or not? thanks.

**Comment by 1800joe** [comment]
I haven't had a chance to look for the root cause. My test involved aligning a touchableHighlight just under the navbar across width of device. it is untouchable ~10 px from the top of the touchablehighlight.

**Comment by 1800joe** [comment]
Adding a picture for reference, the pink circle is about where the press occurs and the button (top left) is activated. Have tested various combinations of navigator styles including the "drawUnderNavBar,"  same results.

![screen-shot-2016-08-18-at-8 55 08-pm](https://cloud.githubusercontent.com/assets/3111670/17795524/11d3e268-6587-11e6-912c-5e7aafbcaffe.png)

**Comment by lalogomez** [comment]
Same issue here. 

I cant focus in the searchbar without overlay the nav buttons, all navigator styles tested and no result.

![demo](https://cloud.githubusercontent.com/assets/13592480/18703448/1f99913c-7fa3-11e6-920a-2a56e73d4af3.gif)

**Comment by perrosnk** [comment]
Same as #339
