### ISSUE TITLE
Possible to have navigation actions in Redux?

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#1731]
### Issue Description

Is it possible to use `react-native-navigation` navigation actions with Redux? For example I would like to fire redux actions and the navigation stack would be inside Redux state. Now all Redux examples only show only how to access Redux state but nothing that is related in having navigation stack in Redux state for example.

---
### Environment
* React Native Navigation version: 1.1.194
* React Native version: 0.47.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by srishanbhattarai** [comment]
+1
This would also help in using [Redux Observable](https://github.com/redux-observable/redux-observable) with this library.

**Comment by Macromeda** [comment]
Just ran into that situation right now, my work around was to subscribe to the store, and fire the navigator function from inside the component itself. 
I think that's a better way to do it than to implement a whole new package to your project, @srishanbhattarai
