### ISSUE TITLE
undefined error onPress

### ISSUE THREAD

**Issue by PHClement** [wix/react-native-navigation#1738]
### Issue Description

When I create a onPress event on a child component I get this error:

![f95f91d58a72a505f56e849ddb8b07d3](https://user-images.githubusercontent.com/26087186/29639891-ac3c16d8-885c-11e7-9531-47ea966b2f54.png)

Here my code, can you help me please ?

![2b9185ac555dba1151bb8272a32b8423](https://user-images.githubusercontent.com/26087186/29639931-df3e4f10-885c-11e7-8012-fd1d92df1f43.png)

Thank you in advance ! :)

---
### Environment
* React Native Navigation 16.0.0-alpha.12
* React Native version: 0.47.1
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Debug, device (Galaxy Note 4)

**Comment by zerotalk** [comment]
I think you unregister react-native-navigation component

please reference react-native-navigation document

[iOS Installation](http://wix.github.io/react-native-navigation/#/installation-ios)
[Android Installtion](http://wix.github.io/react-native-navigation/#/installation-android)
[Usage](http://wix.github.io/react-native-navigation/#/usage)

**Comment by PHClement** [comment]
Thank you for the answer but it's registered I don't understand why I've this error 😕

**Comment by zerotalk** [comment]
@PHClement 

1. create app.js
import { Navigation } from 'react-native-navigation';
// import your component, BackButton.js and Home.js 
import BackScreen from './BackButton';
import HomeScreen from './Home';
//register screen
export function registerScreens() {
    Navigation.registerComponent('home.BackScreen', () => BackScreen);
    Navigation.registerComponent('home.HomeScreen', () => HomeScreen);
}

2. index.ios.js or index.android.js
import { Navigation } from 'react-native-navigation';
// import app.js
import { registerScreens } from './app';

// this is where you register all of your app's screens
registerScreens();

// Change your app root into an app based on a single screen 
Navigation.startSingleScreenApp({
  screen: {
    screen: 'home.BackScreen', // unique ID registered with Navigation.registerScreen
  },
})

3. your BackButton.js
onPress={this._goBack.bind(this)}

_goBack() {
    this.props.navigator.push({
        screen: 'home.HomeScreen'
    })
}

**Comment by PHClement** [comment]
Is this working on a child of a child component ?

**Comment by PHClement** [comment]
**# Fixed, you can't navigate in a child component**

**Comment by varungupta85** [comment]
@PHClement I am not sure what you meant by >you can't navigate in a child component. I think you probably forgot to pass the navigator as a prop to the `BackButton` component.

**Comment by PHClement** [comment]
Yes on the child component you must add this

`<ClasseCarroussel title="" navigator={this.props.navigator}/>`
