### ISSUE TITLE
Is there something like this package for React (web version)?

### ISSUE THREAD

**Issue by gazpachu** [wix/react-native-navigation#174]
The closest I can think of is React Bootstrap but I was wondering if there's something with the same sort of pull menus, overlays and push screens.

I'm starting a cross-platform project (web desktop, web mobile and native mobile) and I would like to have the same type of navigation animations and journeys as the ones provided in react native navigation.

Thanks!

**Comment by geminiyellow** [comment]
hmm... can i use it in react-native-web ?
