### ISSUE TITLE
Swipe left to go back to previous screen

### ISSUE THREAD

**Issue by mazing** [wix/react-native-navigation#1741]
Is it possible to allow the user to make a swipe left gesture on the entire screen to go back - just as Instagram?

**Comment by guyca** [comment]
IIRC it's enabled by default for pushed screens on iOS. You can disable it with `disabledBackGesture: true` style property.

**Comment by mazing** [comment]
But it's not using the entire screen, but only a few pixels in the left

**Comment by NikoMontana** [comment]
Does anybody know if this is better solved in the wix lib? Because like @mazing said, it is only some pixels on the left that is triggering the back function. The back function will never trigger if you place the gesture in the middle of the screen..

**Comment by mths0x5f** [comment]
The gesture Instagram implemented themselves. I think RNN goals avoid custom and derivate implementations from official guidelines and agree they do not attempt to replicate custom behavior.

**Comment by vnnoder** [comment]
> But it's not using the entire screen, but only a few pixels in the left
 
You can change this default behaviour by configuring `gestureResponseDistance.horizontal` value like this, the default is 25 pixel:
```
const VideoStack = createStackNavigator({
    VideoNews: VideoScreen,
    VideoDetails: VideoDetailsScreen,
    VideoSubcategory: VideoSubcategoryScreen
  },
  {
    initialRouteName: 'VideoNews',
    navigationOptions: {
      gestureResponseDistance: {
        horizontal: 300,
        vertical: 135,
      },
    }
  },
);
```

For more detail: https://reactnavigation.org/docs/en/stack-navigator.html
