### ISSUE TITLE
Usage with redux-saga (How to access Navigator elsewhere than component)

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#1742]
### Issue Description
I would like to know how can I access Navigator actions (push, toggleDrawer, resetTo...) elsewhere than from component. Because everyone knows you can do for example `this.props.navigator.push(...)` from inside of component. But how can I call `push` from example inside of redux-saga generator? Below is full example that will explain this:
```js
// sagas.js
export function* login({ credentials, Navigator }) { // now Navigator is here :(
  try {
    const response = yield call(authApi.login, credentials);
    yield call(Navigator.push, {
      screen: 'MAIN_VIEW',
      passProps: { user: response.data.user },
    });
  } catch (error) {
    // show some error
  }
}

// MyComponent.js
class MyComponent {
  login = ({ credentials }) => {
    this.props.dispatch({
      type: 'LOGIN',
      credentials,
      Navigator: this.props.navigator, // this has to be passed :(
    });
  };
}
```
This is very important when you want to move all business logic outside of your components. Please tell me if you need more information :)

**Comment by henrikra** [comment]
Looks like every component gets `this.props.navigator` like this: https://github.com/wix/react-native-navigation/blob/17701133211d914f0d00089f0d65cc873030e980/src/Screen.js#L185
So basically I could import `Navigator` but what do I put to `navigatorID`, `navigatorEventID` and `screenInstanceID `? Any ideas @jp928 ?

**Comment by jp928** [comment]
@henrikra 
My solution would be a hack comparing with yours but it would be simpler.

Rather than redirect within a saga, I would like to put a action with a payload to the component,
inside the component, I use

```javascript
componentWillReceiveProps(nextProps) {
  if(nextProps.redirect) {
    this.props.navigator.push({
      ...
   })
  }
}
```

**Comment by jp928** [comment]
@henrikra 
To achieve your way, you may pass the navigatorID, navigatorEventID and screenInstanceID as parameters to action

When you dispatch action from component, you could 

```javascript

 this.props.dispacthMySagaAction({
    ...this.props
 });

```

**Comment by henrikra** [comment]
@jp928 This way is fighting against sagas and takes away all the good parts like testability :( Any other ideas? I guess only change to library it self would help with this? Ping also @guyca @blairvanderhoof

**Comment by henrikra** [comment]
@jp928 Can you tell me more about your 2nd solution? How the complete example would look?

**Comment by jp928** [comment]
@henrikra 

Just tested with your solution, absolutely fine but I don't know why the first solution is not testable.
From the component I passed the navigator as a parameter as you suggested:

```javascript


```

**Comment by jp928** [comment]
Also I passed with
```javascript

new Navigator(this.props.navigatorID, this.props.navigatorEventID, this.props.screenInstanceID)

```

Also works properly.

**Comment by jp928** [comment]
@henrikra 

would you mind to share your test suite?

**Comment by jp928** [comment]
This approach requests me to pass styles into saga, which is so disgusting.

**Comment by henrikra** [comment]
Yeah this approach won't work because I still have to pass `navigator` to saga so it is the same as first approach for this problem :(

**Comment by jp928** [comment]
@henrikra 
may be we could have a separator function called routerFunc sits in between sagas and navigator.push

**Comment by henrikra** [comment]
Can you elaborate how this would work? And in this way I would not have to pass `navigator` around?

**Comment by jp928** [comment]
I am wondering may be Store.subscribe would be the best solution for this

http://redux.js.org/docs/api/Store.html

**Comment by henrikra** [comment]
I am listening :D

**Comment by jp928** [comment]
Ahh... 

I am off today :)

**Comment by henrikra** [comment]
So you mean I should do `store.subscribe` and check for my custom action. And then use `navigator` somehow there? But there lies same problem: how can I get `navigator` into to that `store.subscribe`?

**Comment by jp928** [comment]
You are right. let me make routerFuncs in between saga and navigator. I will attach a github link in this thread soon.

**Comment by henrikra** [comment]
Great 👍

**Comment by pelim** [comment]
looked the whole week for a suitable solution for this problem +1

**Comment by henrikra** [comment]
@pelim Did you find a good solution?

**Comment by jp928** [comment]
@henrikra @pelim 
The solution already exists in here:
https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js

and it uses store.subscribe as solution.

**Comment by henrikra** [comment]
@jp928 Hmm I not sure how this relates to redux-saga

**Comment by juddey** [comment]
@henrikra @jp928 Neither am I, but I'd :heart: to be able to call RNN from a saga :smile:

**Comment by chrismllr** [comment]
I also encountered this issue, using `redux-observable`... FWIW, my solution was a HOC for the view component, which listened for a saga/ observable stream to toggle a boolean, and then providing a handler for the toggling of that boolean...

Ex here:
https://gist.github.com/chrismllr/92c3a314d7d035c8877fcf672cfd555c

**Comment by chrismllr** [comment]
This solution also seems valid, although it would require a custom rebuild of the navigator actions API:
https://github.com/wix/react-native-navigation/issues/993#issuecomment-294400316

**Comment by pqkluan** [comment]
Duplicate with #993
