### ISSUE TITLE
startSingleScreenApp: undefined is not an object (evaluating 'RCCManager.setRootController')

### ISSUE THREAD

**Issue by yhan64** [wix/react-native-navigation#1744]
### Issue Description
Can not start the app using Navigation.startSingleScreenApp

### Steps to Reproduce / Code Snippets / Screenshots

![image](https://user-images.githubusercontent.com/14009820/29698978-31a76474-890e-11e7-876a-542982fc5bbc.png)

**index.ios.js**
```
import { Navigation } from 'react-native-navigation';
import Example from './src/example';

console.ignoredYellowBox = ['Remote debugger'];

Navigation.registerComponent('Example', () => Example);

Navigation.startSingleScreenApp({
  screen: {
    screen: 'Example',
    title: 'WixCal',
  },
  appStyle: {
    navBarBackgroundColor: '#00adf5',
    navBarTextColor: 'white',
    navBarButtonColor: '#ffffff',
    statusBarTextColorScheme: 'light'
  }
});
```
---
### Environment
* React Native Navigation version: 1.1.205
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): simulator

**Comment by jp928** [comment]
You need to modify your AppDelegate.m file just like the installation instruction does.

**Comment by choudharyjji** [comment]
@jp928  got the same error in the android please suggest what to do ? i counln't able to find the AppDelegate.m in the android folder i guess there is not . Please help

**Comment by jp928** [comment]
make changes in MainActivity.java and MainApplication.java as the insllation instruction.

**Comment by choudharyjji** [comment]
@jp928  Thanks for the valuable suggestion will look into it and let you know :)

**Comment by choudharyjji** [comment]
`D:\android\Hiran\android\app\src\main\java\com\hiran\MainApplication.java:17: error: cannot find symbol
    return BuildConfig.DEBUG;
           ^
  symbol:   variable BuildConfig
  location: class MainApplication
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.348 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

`

now the build failed everytime .. any suggestion about this ?

**Comment by sang-dao** [comment]
I got same error
FYI, i am testing use Expo.

**Comment by pqkluan** [comment]
@choudharyjji I'm pretty sure that you failed to follow Android setup instruction for RNN.
@sang-dao react-**native**-navigation don't work with Expo since Expo hide the native part from new starters.

**Comment by sang-dao** [comment]
Hi @pqkluan pk , Thanks for your answer.

**Comment by yhan64** [comment]
@jp928 @pqkluan Thank you for answering! I jumped to React Navigation after more consideration and comparisons. But anyway, thank you for your kindness! I feel the warmth from JS community again, lol

**Comment by spencewine** [comment]
I'm getting this error and I've literally copied the appDelegate.m file from the example.

**Comment by axed** [comment]
I'm getting this error and i don't even use XCode at all...
It might be an advantage if the documentation stated that this is incompatible with Expo, as the React-Native tutorials/getting started guides seem to use Expo to show off how easy it is to get started with all this...

RN: 0.48.4

**Comment by yhan64** [comment]
@spencewine @axed I solved this by going through the setup guide step by step here:
IOS: https://wix.github.io/react-native-navigation/#/installation-ios
Android: https://wix.github.io/react-native-navigation/#/installation-android

**Comment by mstahlmann** [comment]
This is really a troublesome package. I have been going thru this for hours with various issues. I am now stuck on this one. Is it possible that you have unstable compatibility with the react-native tools. This is literally the most frustrating process I have been thru in coding to date. I have gone thru all the steps multiple times and I cannot solve this issue.

**Comment by pqkluan** [comment]
I have [this example file](https://github.com/pqkluan/RNN-SplashScreen-Example/blob/master/Example/ios/Example/AppDelegate.m), it's a bit out-dated (v1) but it's a correct setup for reference.

And make sure that you are using ejected React Native project, RNN is not working with Expo.

**Comment by mstahlmann** [comment]
Thanks for the reply. I am hoping to tackle v2. I’m assuming it’s compatible with the latest react native. I haven’t been using expo. I have been building in react native so the third party stuff works better.

**Comment by bilalma** [comment]
I'm also facing this issue.

**Comment by bilalma** [comment]
I did the same steps like https://wix.github.io/react-native-navigation/#/docs/Installing but I gets an error "console error , error while starting app: TypeError undefined is not an object evaluating RCCManager.setRootController"

**Comment by nachiketsalvi** [comment]
> @spencewine @axed I solved this by going through the setup guide step by step here:
> IOS: https://wix.github.io/react-native-navigation/#/installation-ios
> Android: https://wix.github.io/react-native-navigation/#/installation-android
> And also, kept telling myself 'it's going to work, it's going to work, it's going to work'

Links are broken
