### ISSUE TITLE
Tapping tab button on Android does not reset tab to root

### ISSUE THREAD

**Issue by lappalj4** [wix/react-native-navigation#1745]
### Issue Description

BottomTabs behavior is different between iOS and Android: on iOS, tapping the active tab resets that tab to it's root, and on Android it does not do anything. 

Expected behavior:
- If a tab is active, both platforms should reset that tab to it's root when the respective tab button is tapped. Alternatively, this could be an option in the tabBasedApp configuration.

I have not found a way to manually listen to click events for the BottomTabs, which would allow me to bypass this issue by manually resetting the tab. Is this possible in some way?

---
### Environment
* React Native Navigation version: 1.1.193
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): Android 
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Samsung Galaxy S8 7.0.0

**Comment by guyca** [comment]
Hey there,
Native views are expected to behave according to the design guidelines for each platform. I don't think this is the native behavior for BottomTabs on Android.

You can listen to the [reselect event](https://wix.github.io/react-native-navigation/#/screen-api?id=listening-to-tab-selected-events) and reset the tab if you really wanted to.

**Comment by lappalj4** [comment]
@guyca thanks, missed that part of the docs apparently. I still think it makes little sense to have differing behaviour between platforms like this, be the native behaviour of these components what it may. The goal of RN is to be able to create cross-platform apps with a single codebase, so when I have to write Platform.OS checks in my code to have a uniform navigation flow between platforms, I think we are not going in the right direction.

**Comment by leoskyrocker** [comment]
@guyca can you provide the link to the design guideline for Android? I can't seem to find any information regarding that.
