### ISSUE TITLE
Can't pass realm objects via navigator props

### ISSUE THREAD

**Issue by hhunaid** [wix/react-native-navigation#1748]
### Issue Description

Can't pass Realm objects via navigator props. It gives "Attempted to assign to readonly property" error.
iOS works fine

### Steps to Reproduce / Code Snippets / Screenshots

Pass a realm object in `passProps` option of `navigator.push`
On the pushed screen try to access props

---
### Environment
* React Native Navigation version: 0.47.1
* React Native version: 1.1.193
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Emulator, Debug

**Comment by kkgelu** [comment]
Not sure this helps, I also had the problems with _Attempted to assign to readonly property_ when migrating from the deleted official JS navigator to this dependency.

Inspired by https://github.com/wix/react-native-navigation/issues/1708 
I pass a function which returns object. To make life easier, I wrapped the navigator:
```
class Navigator {
  push(params){
    var paramsWrapper = {
      onRequestParams: () => params
    }

    this.wixNavigator.push({
      ...
      passProps: paramsWrapper,
    });
    ...
  }
```
I made a base class for all screens that receive the params:
```
class ScreenComponent extends Component {
  get params(){
    return this.props.onRequestParams();
  }
}
```

**Comment by stonecold123** [comment]
@kkgelu 
Your suggestion works. I hope it can be fixed. I don't want to go back to react navigation just because of this bug.
