### ISSUE TITLE
Toggle Drawer in Android

### ISSUE THREAD

**Issue by nimerfarahty** [wix/react-native-navigation#1749]
### Issue Description
Dears

some times the drawer not toggled on android below logs from android studio 
```
08-26 19:35:17.388 5831-5831/com.city360 E/unknown:ReactNative: Got DOWN touch before receiving UP or CANCEL from last gesture
08-26 19:35:17.549 5831-5831/com.city360 E/unknown:ReactNative: Received an ACTION_CANCEL touch event for which we have no corresponding ACTION_DOWN
08-26 19:35:17.549 5831-5831/com.city360 E/unknown:ReactNative: Unexpected state: received touch event but didn't get starting ACTION_DOWN for this gesture before
```

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.205
* React Native version: 0.47
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device with debug

**Comment by riyazMuhammad** [comment]
+1

**Comment by riyazMuhammad** [comment]
For me open was never working only on android build. 
It worked for me after removing to: "open"
```
this.props.navigator.toggleDrawer({
        side: "left",
        animated: true,
        to: "open"
 });
```
According to [doc](https://wix.github.io/react-native-navigation/#/screen-api?id=toggledrawerparams-), to is a optional param.

**Comment by fmoessle** [comment]
this solution does not work on android

**Comment by saxahan** [comment]
E/unknown:ReactNative: Got DOWN touch before receiving UP or CANCEL

I get all click action on any screens. Any solutions?

**Comment by tafelito** [comment]
Same as @saxahan here. Lot of` E/unknown:React: Got DOWN touch before receiving UP or CANCEL` from last gesture whenever I touch anything on the screen. Any ideas where this is coming from?

Thanks

**Comment by skymax406** [comment]
Hello same issue ...
`Unexpected state: received touch event but didn't get starting ACTION_DOWN for this gesture before`

Any solution ?

**Comment by Loivado** [comment]
Hope that repro helps debugging and fixing the issue: 

The normal error trigger is easily reproducible, do open the drawer, close drawer, open drawer.. until the error triggers. 
But there is a dead end possibility when doing some click action with a Burger Menu which opens the Drawer aswell. (see below)

Currently: 
1. Error Log appears, doesn't do much harm. 
2. At some point no Click State is accepted anymore.
2.1. Any next click results in triggering the error.  

Repro Steps: 
1. Have an App which has a Burger Menu (which opens the Navigation Drawer when clicked) and a Menu Button (which can switch to another screen(s)). (Best would be you have to load data before displaying the next screen completely.)
2. Click Burger Menu.
3. Click Button to switch screen. (Move the position of the click a little bit when clicking the button.)

Do Action 2 and 3 in a loop for a longer time until click actions are locked.
