### ISSUE TITLE
Can the custom NavBar button's icon be a component?

### ISSUE THREAD

**Issue by saudpunjwani101** [wix/react-native-navigation#1751]
### Issue Description

I want the custom Navbar button icon to be a component.

for example: 

        static navigatorButtons = {
           leftButtons: [
          {
             title: 'Booking',
             buttonColor:'white',
             id: 'booking',
             // like this
             icon: <Icon name="ios-home" />
           },
        ]
      };

is it possible to do so?

**Comment by guyca** [comment]
[Using custom buttons](https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=custom-navigation-buttons)

**Comment by saudpunjwani101** [comment]
Yeah right!
