### ISSUE TITLE
Navigator does not work with react native facebook account kit

### ISSUE THREAD

**Issue by VoNam** [wix/react-native-navigation#1752]
### Issue Description
Push function does not work after successful authentication with Account Kit.
Lib: https://github.com/underscopeio/react-native-facebook-account-kit

### Steps to Reproduce / Code Snippets / Screenshots
My app starts with `Navigation.startSingleScreenApp`, then I have a button to invoke the method below, after successful authentication, the callback will be called, but it seems navigator does not work after all.
```
RNAccountKit.loginWithPhone()
  .then((token) => {
    this.props.navigator.push({
      screen: 'Screen',
    })
  })
```

---
### Environment
* React Native Navigation version: 1.1.205
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6, OS 10.3, Debug

**Comment by phattv** [comment]
is it the correct way to use `resetTo`?

**Comment by gvillenave** [comment]
I'm seeing the same exact thing. resetTo works, but not push. Ideally I would want to use push for users to be able to go back to the login page.
