### ISSUE TITLE
BackHandler problem

### ISSUE THREAD

**Issue by jsina** [wix/react-native-navigation#1765]
#### I wanna do sth on screen after the android back button fired but there is no effect effect I've done it.
```
componentWillMount() {
    this._backPress = 0;

    BackHandler.addEventListener('backPress', () => {
      console.log('back ****');
      setTimeout(() => {
        this._backPress = 0;
      }, 3000);

      this._backPress += 1;
      if (this._backPress <= 1) {
        ToastAndroid.showWithGravity(strings.BACK_BUTTON_ALERT, ToastAndroid.SHORT, ToastAndroid.CENTER);
        return true;
      }
      return false;
    });

  }
```

**Comment by MrLoh** [comment]
I'm having the same issue with `BackHandler.addEventListener('hardwareBackPress', this.myHandler);` I need some way to override this in a youtube player, which displays back buttons on android in fullscreen, but I don't want to always go back a screen, just to disable fullscreen with the button.

**Comment by Hizoul** [comment]
i have the same problem.
I also tried the overrideBackPress / overrideBackPressJs param. It works in that no backpress does anything anymore, but the "backPress" event that should be fired somehow never reaches my navCallback :/
https://github.com/wix/react-native-navigation/blob/90df99030cb7495a4f862efd538aab8b0456bce1/android/app/src/main/java/com/reactnativenavigation/screens/ScreenStack.java#L398
https://wix.github.io/react-native-navigation/#/screen-api?id=setonnavigatoreventcallback

**Comment by jsina** [comment]
@Hizoul could you send us an example code?

**Comment by Hizoul** [comment]
Whenever you call the navigator.pop or navigator.push method make sure to do it like this
```
navigator.pop({overrideBackPress: true})
navigator.push({ screen: "abc", overrideBackPress: true})
```

then on each root component of a route you call the following
```
    navigator.setOnNavigatorEvent((event) => {
      switch (event.id) {
        case `backPress`: {
console.log("received backpress on android") 
        }
      }
    })
```

but thats just what i already wrote in pseudocode

**Comment by truongthanh1303** [comment]
Hi,
I have an issue I think it also related to this issue. Do you have a look at it, please?
https://github.com/wix/react-native-navigation/issues/749#issuecomment-331627087

Regards,

**Comment by Hizoul** [comment]
Did you also pass `overrideBackPress` as a param to the `startSingleScreenApp` function?

**Comment by truongthanh1303** [comment]
Yes I did, but it didn't work on the first screen?

**Comment by jsina** [comment]
@truongthanh1303 this is how I handle BackHandler on first screen. in fact I force user to press twice on back button for exit on code below.
```  this._backPress = 0;

    BackHandler.addEventListener('backPress', () => {
      setTimeout(() => {
        this._backPress = 0;
      }, 3000);

      this._backPress += 1;
      if (this._backPress <= 1) {
        ToastAndroid.showWithGravity(strings.BACK_BUTTON_ALERT, ToastAndroid.SHORT, ToastAndroid.CENTER);
        return true;
      }
      return false;
    });

  }

**Comment by Fuhrmann** [comment]
I`m having the same problem: the BackHandler.addEventListener never gets called. Event using the overrideBackPress: true.
