### ISSUE TITLE
Linking not opening app when app in background (Android)

### ISSUE THREAD

**Issue by renrizzolo** [wix/react-native-navigation#1766]
### Issue Description

I am having some trouble getting Linking to work correctly on Android.

I can successfully launch an intent from a url when the app is closed.

However If I use the app switcher or the home button to leave my app, then open the link from elsewhere, nothing happens. (or in the case of gmail, it switches to a white screen briefly then back to gmail). If I manually switch back to the app, the `Linking` listener picks up the url and acts accordingly. Opening from gmail opens the app twice - one shows the splash screen and crashes on focus, the other is the app running normally.

as well as the above I am using [react-native-auth0](https://github.com/auth0/react-native-auth0/) which opens a chrome custom tab, and specifies a callback url which should return to the app once the login is done on the website. The behaviour is slightly different to above – from the custom tab it doesn't return to the app but if I open the custom tab url in Chrome and log in, it works correctly.

I'm using AppState  - the app is in 'background' when in the custom tab and when in chrome.

react-native-auth0 wants us to use `android:launchMode="singleTask"` which I believe RNN shouldn't use? Not sure if that's relevant.

Does a different activity need to be launched when the app is already open?

I've been trying various things for a while but not getting anywhere!

* this all worked before I switched to RNN

### Steps to Reproduce / Code Snippets / Screenshots

the Auth0 login method looks like this:
```
    @ReactMethod
    public void showUrl(String url, boolean closeOnLoad, Callback callback) {
        final Activity activity = getCurrentActivity();

        this.callback = callback;
        if (activity != null) {
            CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
            CustomTabsIntent customTabsIntent = builder.build();
            customTabsIntent.launchUrl(activity, Uri.parse(url));
        } else {
            final Intent intent = new Intent(Intent.ACTION_VIEW);
            intent.setData(Uri.parse(url));
            getReactApplicationContext().startActivity(intent);
        }
    }
```

and the JS side of it is this
 ```
 show(url, closeOnLoad = false) {
    return new Promise((resolve, reject) => {
      const urlHandler = (event) => {
        A0Auth0.hide();
        Linking.removeEventListener('url', urlHandler);
        resolve(event.url);
      };
      Linking.addEventListener('url', urlHandler);
      A0Auth0.showUrl(url, closeOnLoad, (err) => {
        Linking.removeEventListener('url', urlHandler);
        if (err) {
          reject(err);
        } else if (closeOnLoad) {
          resolve();
        }
      });
    });
  }
```

my manifest:
```
<application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme"
       >
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustPan"
       >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
                <data android:host="mydomain.auth0.com"
                      android:pathPrefix="/android/${applicationId}/callback"
                      android:scheme="${applicationId}" />

              <!-- Accepts URIs that begin with "https://*.mysite.com/post” -->
                <data android:scheme="https"
                      android:host="*.mysite.com"
                      android:pathPrefix="/post" />
        </intent-filter>
      </activity>
   ...
</application>
```

---
### Environment
* React Native Navigation version: 1.1.205
* React Native version: 0.46.1
* Platform: Android

**Comment by ywongweb** [comment]
@renrizzolo 
Did you manage to find a fix for this?

**Comment by renrizzolo** [comment]
hi @ywongweb, 
I was able to get around the main problem which was related to Custom Tabs in react-native-auth0 (when used with react-native-navigation) – discussion here https://github.com/auth0/react-native-auth0/issues/83

The other problem (launching app from external url) _seemed_ to fix itself after uninstalling,  restarting my device and reinstalling.

**Comment by SuperKirik** [comment]
I still have this issue with launching application, but in my case this happens only with gMail (exactly as wrote above -  in the case of gmail, it switches to a white screen briefly then back to gmail).
