### ISSUE TITLE
[iOS] ScreenVisibilityListener not being called on back navigation

### ISSUE THREAD

**Issue by gtRfnkN** [wix/react-native-navigation#1771]
### Issue Description

The `ScreenVisibilityListener`  is working on forward navigation (`push`, `resetTo`) but not back navigation (`pop`, native back navigation) on iOS. However, back navigation works with the `ScreenVisibilityListener` on Android.

"working" in that case means, that the callbacks (`willAppear`, `didAppear`, `willDisappear`, `didDisappear`) of the `ScreenVisibilityListener` are being called when the screen changes.

PS: the callback of `setOnNavigatorEvent` is being called, but without any screen id or information, which makes it rather useless...

### Steps to Reproduce / Code Snippets / Screenshots

* create 2 screens
* register the ScreenVisibilityListener with all 4 callbacks
* push a screen (callbacks are being called)
* pop the screen (no callbacks are being called on iOS)

---
### Environment
* React Native Navigation version: 1.1.207
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iOS 10.3

**Comment by gtRfnkN** [comment]
After some help from a colleague we found that the [line 236 in RCCViewController.m](https://github.com/wix/react-native-navigation/blob/33e861478c46b110ad9b8fd58c5abe856d1b5745/ios/RCCViewController.m#L236)prevents the native back navigation from being sent to react native. After removing that line, everything works just fine.

I'll add a PR for that.
It would be great, if you could check, if removing that line breaks anything. I didn't find anything, since `commandType` is being checked again on line 243.

**Comment by henrikra** [comment]
Great debugging!

**Comment by baijunjie** [comment]
Great debugging! 
When will the problem be fixed?

**Comment by mobitar** [comment]
Can confirm same issue. Also applies to modal dismissals. willDisappear and didDisappear not called for modals. Commenting out that line fixes the issue.

**Comment by jslz** [comment]
hi, I am encountering this -- per chance, is this going to be fixed in the core wix project? thanks.

**Comment by TonyTofugear** [comment]
Also encountering exact same issue in our project; can we confirm that this will be fixed in the core wix project as well?  Would like to refrain from implementing hack-fixes for this seemingly trivial fix.

**Comment by keyboard-toucher** [comment]
Same issue. @guyca is possible to add this fix?

**Comment by fabryx92** [comment]
Same issue for me. I hope that this will be included in the library.
Any workaround meanwhile?

**Comment by wwwdata** [comment]
@fabryx92 removing that line in `RCCViewController.m` was also working fine for me. I just hope this gets included in the repo soon. But in the meantime, you can just do that manually. What I do is run a postinstall npm script that deletes it. You can do that with a simple copy over and check in the modified file or by applying a patch.

**Comment by fabryx92** [comment]
@wwwdata thanks for the advice, I will try it. But I ever prefer to use tested and approved solutions for my projects.

**Comment by skovhus** [comment]
@guyca @DanielZlotin can you advice what needs to be done here?

**Comment by skovhus** [comment]
@guyca @DanielZlotin please advice what needs to be done here... Would love to help.

**Comment by iksent** [comment]
Any updates on this? This issue is still actual.

React Native Navigation: 1.1.351

@guyca, please take a look at this - it's important thing.

**Comment by NicolasBonduel** [comment]
Until this is fixed, could you guys tell us if there is any drawback in commenting out this line for now?
@guyca @yogevbd @DanielZlotin

**Comment by NicolasBonduel** [comment]
For those waiting for a fix, from @wwwdata's idea, I made a patch file that you can temporarly use if you don't want to fork the library.

https://gist.github.com/NicolasBonduel/138339fe1eb3d8cc986e5d8dcabb290e

You can save it as `IOS_RCCViewController_hack.patch` in your root folder and then add 
```
  "scripts": {
    [...]
    "postinstall": "patch ./node_modules/react-native-navigation/ios/RCCViewController.m IOS_RCCViewController_hack.patch"
  },
```
in your `package.json` file.
It's absolutely not ideal, but it can eventually be used as a temporary fix.

**Comment by iksent** [comment]
Why it was closed, if "commandType" in new event is empty on iOS?
You cannot understand, is didAppear invokes due to Push or Pop - so it's impossible to process it in the right way.

**Comment by NicolasBonduel** [comment]
I agree with @iksent even if I created the PR, we still don't get the `commandType` parameter.

**Comment by jslz** [comment]
(agreed with @iksent, see also https://github.com/wix/react-native-navigation/issues/2101)
