### ISSUE TITLE
iOS - Need a flag to allow simultaneous gesture recognition 

### ISSUE THREAD

**Issue by thanhzusu** [wix/react-native-navigation#1776]
### Issue Description

My app has a paging tab inside [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view) that user can swipe left/right to navigate between tabs easily. But I got an issue at the first tab that swipe gesture was conflicted with pop gesture (a cool feature of iOS that let's user can get back to previous between screen quickly). So I thought we need a flag to allow simultaneous gesture recognition.

---
### Environment
* React Native Navigation version: 1.1.85
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone, iPad

**Comment by thanhzusu** [comment]
I created a PR [1777](https://github.com/wix/react-native-navigation/pull/1777) for this issue.

**Comment by guyca** [comment]
closed by #1777
