### ISSUE TITLE
Getting warning message when Tab Screen sets state in componentDidMount

### ISSUE THREAD

**Issue by mastermoo** [wix/react-native-navigation#178]
Hey,

I'm getting a warning, that my components should not set state, when they are not mounted, see below screenshot. This happens to components which are used as Tab screens and they set the state in componentDidMount (in my case after an api request).

I also noticed, that the componentDidMount method gets called twice, which causes some side effects (code gets initialized twice).

Am I doing something wrong or is this getting fixed?

Thanks!

![screen shot 2016-08-05 at 11 25 34 pm](https://cloud.githubusercontent.com/assets/7849822/17451016/f25fe0ee-5b63-11e6-924d-deee3c6d670e.png)

**Comment by guyca** [comment]
Hey @mastermoo 
What platform are you getting this warning on?

**Comment by mastermoo** [comment]
Ob iOS 

Get Outlook for iOS




On Sat, Aug 6, 2016 at 10:04 AM +0200, "Guy Carmeli" <notifications@github.com> wrote:












Hey @mastermoo 

What platform are you getting this warning on?

**Comment by mastermoo** [comment]
ok I found the error. It was a mistake on my side. I called `Navigation.startTabBasedApp(...)` twice. 

Sry!
