### ISSUE TITLE
method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by spidergears** [wix/react-native-navigation#1781]
### Issue Description
Seeing error when building app for android.
Seems to originate at `react-native-navigation/android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactPackage.java:23`

Relevant Code:
```
@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```

Error:
`react-native-navigation/android/app/src/main/java/com/reactnativenavigation/bridge/NavigationReactPackage.java:23: error: method does not override or implement a method from a supertype`
---
### Environment
* React Native Navigation version: "^1.1.134"
* React Native version: "0.47.1"
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by spidergears** [comment]
Commenting '@Override'  annotation seems to fix it.

**Comment by spidergears** [comment]
This is already taken care of on the latest release.
Thank you Wix.

**Comment by waterdoo** [comment]
@spidergears I'm running into the same issue, would you mind sharing how you resolved it?

**Comment by pie6k** [comment]
I've managed to run it to I thought I'll share my code:

MainActivity.java

```java
package com.YOUR_APP_NAME_HERE;

import com.facebook.react.ReactActivity;

import com.reactnativenavigation.controllers.SplashActivity;

public class MainActivity extends SplashActivity {

}
```

MainApplication.java
```java
package com.YOUR_APP_NAME_HERE;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.reactnativenavigation.NavigationApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;


public class MainApplication extends NavigationApplication {

    public boolean isDebug() {
        return BuildConfig.DEBUG;
    }

    protected List<ReactPackage> getPackages() {
        // Add additional packages you require here
        // No need to add RnnPackage and MainReactPackage
        return Arrays.<ReactPackage>asList(
          new MainReactPackage()
        );
    }

    public List<ReactPackage> createAdditionalReactPackages() {
        return getPackages();
    }

    @Override
    public String getJSMainModuleName() {
      return "index";
    }

}
```

**Comment by pawarvijay** [comment]
Thanks @spidergears answer is correct
remove `@Override`
it works nicley
