### ISSUE TITLE
How to remove the stack opened by startTabBasedApp or startSingleScreenApp

### ISSUE THREAD

**Issue by wagng** [wix/react-native-navigation#1782]
### Issue Description

I have 2 functions to open
- Login part: 2 screens
- Main part: tab based screen

I opened a tab based app by calling **startTabBasedApp** function which has 3 tabs(DashboardScreen, SettingsScreen, ChatScreen).
On SettingsScreen I have logout feature.
When I click logout button, I want to open login screen. So I call **startLoginScene**.
Before call this function, I clean all data from redux store.
This makes the tab screens re-render so app crashes by empty data from redux store.
Is there any way to protect re-rendering once I open a new app?
I think there is old app alive even I open a new app by **startTabBasedApp** or **startSingleScreenApp**.
I need to kill the old app completely once I open a new app.

### Steps to Reproduce / Code Snippets / Screenshots

```
export function startApp() {
  ...
  Navigation.startTabBasedApp({
    tabs,
    appStyle: {
      orientation: 'portrait',
      tabBarBackgroundColor: WHITE,
    },
    tabsStyle: {
      tabBarButtonColor: DARK_GRAY,
      tabBarSelectedButtonColor: DARK_GRAY,
      tabBarHideShadow: true,
    }
  });
}

export function startLoginScene() {
  ...
  Navigation.startSingleScreenApp({
    screen: {
      screen: 'LoginScene',
      navigatorStyle: {
        navBarHidden: true,
        navBarButtonColor: WHITE,
        statusBarHidden: true,
      },
      overrideBackPress: true,
    },
    appStyle: {
      orientation: 'portrait'
    }
  });
}
```

---
### Environment
* React Native Navigation version: 1.1.205
* React Native version: 0.47.1
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Simulator, Debug/Release

**Comment by seanlau555** [comment]
I am facing the same problem too. Anybody has similar experience?

**Comment by sytolk** [comment]
In my app with RNN v.1 it's have memory leak when I switch from Single screen (LoginScene) to tabBasedApp:
https://github.com/Johan-dutoit/RNN-StarterKit-V2/issues/5

**Comment by i198622** [comment]
Maybe an old example can help you? https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js

**Comment by Jose4gg** [comment]
Any solutions to this?

**Comment by a6051529** [comment]
I am facing the same problem too， when I call startTabBasedApp twice，The BottomTab's Color is Red(I want to be gray)。 This is ScreenShots: 
![599a5ce9c0ed59828f7546c1e184023e](https://user-images.githubusercontent.com/7309118/31720004-efb66554-b3da-11e7-9ebf-f25f1aff4720.png)
![c5f24c00cad140f6544e92509f792407](https://user-images.githubusercontent.com/7309118/31720005-effb077c-b3da-11e7-8a23-0d3f0e93befb.png)

**Comment by GorshkovNikita** [comment]
I had the same issue. I cleared redux store in `componentDidMount` method of SingleScreenApp, assuming that TabBasedApp was already unmounted. But it turns out, that this method is called before `componentWillUnmount` methods of tabs screens. So, you need to clear store from `componentWillUnmount` method of one of your tab screens.

**Comment by beansoftapp** [comment]
My workaround is this: using a lightbox or modal to display the login screen to block the main UI.

**Comment by jonathan68** [comment]
I didn't check [this](https://github.com/wix/react-native-navigation/commit/bf001063c9410f3e1bada45b8118cc43b0e62f66) fix. Anybody can check if this fixes our issue?

**Comment by leoskyrocker** [comment]
Haven't investigated further, but at some pt I suspected it's a race condition that the old App's components are rendering before Navigation.start[...]App is able to finish starting up the app, but it may also be like what OP says that the old App never died.

**Comment by chujian** [comment]
I am facing the same problem too.
