### ISSUE TITLE
change top tabs font family 

### ISSUE THREAD

**Issue by ahmedfouad2016** [wix/react-native-navigation#1784]
change top tabs font family 
Is there any way to change top tabs font family in the topTabs or appStyle ? i used tabFontFamily but it change the font family in bottom bar
---
### Environment
* React Native Navigation version: 1.1.143
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by ahmedfouad2016** [comment]
is there any update about this issue  ? @guyca

**Comment by salisuabubakar** [comment]
Any update?

**Comment by hoorsa** [comment]
+1
