### ISSUE TITLE
How to change navbar height on iOS?

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#1786]
How is it possible to change navbar height on iOS? :)

**Comment by adamjacob** [comment]
I'm also wondering the same

**Comment by mattermoran** [comment]
Anybody figured this one out?

**Comment by adamjacob** [comment]
Unfortunately no.  I looked around the objective-c code a bit but I don't know enough about native iOS to make any progress.

**Comment by brenwell** [comment]
Hey guys, is there any movement on this? I have a custom view which working great except I am not sure how to increase the size of the navbar to fit it all.

<img width="376" alt="screen shot 2018-03-02 at 13 29 15" src="https://user-images.githubusercontent.com/802618/36899066-bf84ef42-1e1d-11e8-9aca-b436d52d4fc9.png">

**Comment by mattermoran** [comment]
@brenwell I guess you're just gonna have to make your custom navbar to fit ios navbar height. So far I couldn't find a way to increase the size

**Comment by brenwell** [comment]
I played around for a bit wih obj-c, had been a while. I would need to get to know the project better to understand why my custom CGRect won't stick. Its certainly possible and if I had the time I would love to find out how.

Anyway I solved my issue sadly by swapping to `react-navigation`

**Comment by yogevbd** [comment]
Changing topBar height in iOS is not possible. The only option is to hide the bar and implement your own in jsx

**Comment by brenwell** [comment]
Hey @yogevbd  If its not possible, then there is nothing to be done. But I am curious as to why its impossible. If you have a moment you could shed some light on this, it would be much appreciated.

I thought perhaps something like this would be possible

https://stackoverflow.com/a/31940514/1393746

Thanks

**Comment by yogevbd** [comment]
The navigation bar in iOS is implemented and handled privately by the system.. That includes transition animations when pushing screens, navigation bar title layout, buttons positioning, safe areas and more.
Trying to hack the navigation bar frame will cause an unexpected behavior.
(for example in largeTitle animation)
