### ISSUE TITLE
ViewPagerAndroid not functioning

### ISSUE THREAD

**Issue by MrVisitor** [wix/react-native-navigation#1788]
Stops functioning ViewPagerAndroid when new screen is pushedt

Create screen with ViewPagerAndroid component -> go to new screen -> go back to screen with ViewPagerAndroid component -> on scroll ViewPagerAndroid not functioning

---
### Environment
* React Native Navigation version: v1.1.210
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): only Android
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by guyca** [comment]
duplicates #1317
