### ISSUE TITLE
How to make the balloon not to show after the right title bar button have a long press

### ISSUE THREAD

**Issue by bingfj2008** [wix/react-native-navigation#1789]
Issue Description

How to make the balloon not to show after the right title bar button have a long press.
If it can not to be achieve, how to achieve it by change the code with my own self ?

Please help.

→The Same problem Like Issue:#1560
---
Environment
* React Native Navigation version: 1.1.212
* React Native version: 0.45.1
* Platform : Android

**Comment by guyca** [comment]
@bingfj2008 
If it's the same problem - no reason to open another issue, We can pick up the discussion in #1560
