### ISSUE TITLE
Errors after 0.31.0 upgrade

### ISSUE THREAD

**Issue by rmdort** [wix/react-native-navigation#179]
Getting the following errors with `objc_setAssociatedObject` in RCCNavigationController.m after 0.31.0 react-native upgrade

![image](https://cloud.githubusercontent.com/assets/118231/17454523/b27d68ee-5bcb-11e6-8e6d-7c7152c45b31.png)

**Comment by webzepter** [comment]
@rmdort https://github.com/techery/react-native-controllers/commit/7e363e8ac129ec94289f98a227d521c4055b299a

**Comment by guyca** [comment]
@rmdort We're still using RN 0.25.1 for our internal projects, so we're not supporting RN 0.31 yet. I can't guarantee, but we'll probably upgrade from RN 0.25.1 in the next 2-3 weeks.

**Comment by divyekhanna** [comment]
+1 Facing the same issue. Downgrading react-native for now

**Comment by webzepter** [comment]
@divyekhanna you can use this fix: https://github.com/techery/react-native-controllers/commit/7e363e8ac129ec94289f98a227d521c4055b299a

**Comment by messense** [comment]
Will there be a bugfix version of react-native-controllers pushed to npm soon?

**Comment by folivi** [comment]
did @webzepter fix work for you?

**Comment by robinsmedberg** [comment]
Any news on Android upgrades needed after react-native@0.29.0?

Seems some code have moved from MainActivity to MainApplication.
The error I get is a white screen.

**Comment by reimertz** [comment]
fix mentioned by @webzepter fixed these issues for me. Thanks homie!

**Comment by DanielZlotin** [comment]
iOS is upgraded to RN31 successfully, also backwards compatible. Android is next.

**Comment by DanielZlotin** [comment]
Please see #234
