### ISSUE TITLE
[android] support "react.native.RELOAD" broadcast

### ISSUE THREAD

**Issue by DanielZlotin** [wix/react-native-navigation#1790]
usage: `adb shell am broadcast -a react.native.RELOAD` should reload the js context

**Comment by henrikra** [comment]
When you are using this command?

**Comment by guyca** [comment]
During development, when developing on android device. This way you don't need to shake the device and look like a monkey each time you want to reload 😕

**Comment by henrikra** [comment]
Ahaa :D Why not use "Live reload"?

**Comment by DanielZlotin** [comment]
@guyca does this feature exist in vanila RN?

**Comment by henrikra** [comment]
Yeah. Just shake to pop the menu up. Then tap "Live reload" Then it will reload the JS bundle every time file is saved

**Comment by DanielZlotin** [comment]
@henrikra yes that's given, I was asking about this broadcast we have in v1, where did it come from? nice feature anyway. "Live Reload" isn't working in all cases

**Comment by guyca** [comment]
@DanielZlotin this broadcast isn't a feature of vanilla RN. It was added exactly for the reason you mentioned - live reload isn't working in all cases.

**Comment by DanielZlotin** [comment]
usage: `adb shell am broadcast -a com.reactnativenavigation.broadcast.RELOAD`
