### ISSUE TITLE
NavBar exists a extra white gap.

### ISSUE THREAD

**Issue by rubi** [wix/react-native-navigation#1791]
I came across the problem, you can have a look at screenshot link, there is a extra white gap above NavBarTitle, how to fix the problem , thanks in advance.

[https://github.com/rubi/demos/blob/master/8AAE12B25F392A440EF0E8CB3DB37C42.jpg](https://github.com/rubi/demos/blob/master/8AAE12B25F392A440EF0E8CB3DB37C42.jpg)

**Comment by guyca** [comment]
Hey @rubi 
Do you have any way to reproduce this issue?

**Comment by rubi** [comment]
I demo official example in my project which references react native 43 version, i don't make any changes, it displays strange layout after launching app, i thought this was rn version issue, so upgrade rn vesion to 47, it still exsits the problem, easy to reproduce.

**Comment by guyca** [comment]
On which device and Os version?

**Comment by rubi** [comment]
Android 5.1.1
