### ISSUE TITLE
App start after call "createReactContextInBackground"

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#1792]
Hi all,
I'm using GCM Push notification on android. In GcmListenerService, when the notification come up, I call ReactInstanceManager.createReactContextInBackground() to create React Native context (load some data from redux persist). However, after call, the app auto start up
This problem happens when using with react-native-navigation. I try to use the normal Application and ReactActivity, everything is OK
There's any way to prevent auto start? I searched and found some solutions on this page. The author used some flags as "state" to prevent auto start. However, the app also not START even you press the app icon 🗡 
Hope your helps soon!

**Comment by guyca** [comment]
Hey @moonjava2005 
Did you try [this](https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=compatibility-with-headlessjs)?
