### ISSUE TITLE
exclude Modal from Android BackStack

### ISSUE THREAD

**Issue by sytolk** [wix/react-native-navigation#1793]
I think that Modal screen can be excluded from Android back button history. Maybe like:
showModal({overrideBackPress: true})

On native (Java) level this can be easily done with: <xml>android:noHistory="true"</xml> or set FLAG_ACTIVITY_NO_HISTORY 
https://developer.android.com/reference/android/app/Activity.html#moveTaskToBack(boolean)

generally Android device Back button history is not synchronized with JavaScript navigation stack history. Right?

**Comment by guyca** [comment]
Hey there,
Modal is implemented as a Dialog. RNN keeps one Activity in the stack - the NavigationActivity.

**Comment by sytolk** [comment]
@guyca you mean Android Dialog or DialogFragment ? 
https://developer.android.com/guide/topics/ui/dialogs.html
If I showModal() from button in Tab based navigation (first screen) and next dismissModal() and return to the first Tab. How can I exclude this Modal Dialog from Android BackStack ? (when I press Android hardware back button now the dismissed Modal Dialog will be shown)

**Comment by guyca** [comment]
Use [overrideBackPress](https://github.com/wix/react-native-navigation/issues/250#issuecomment-254186394
)

Handle the back press event in [onNavigatorEvent](https://github.com/wix/react-native-navigation/issues/1135#issuecomment-297242323)

**Comment by sytolk** [comment]
@guyca I know for the overrideBackPress If I set it to Modal its works but I need to handle Back in my initialScreen -> the first Tab. How can I set `{overrideBackPress: true}` here:
```
Navigation.startTabBasedApp({
        tabs: [
            {
                label: I18n.t('navHome'), // tab label as appears under the icon in iOS (optional)
                screen: 'app.Home',
```

**Comment by guyca** [comment]
Oh, that's not supported.

**Comment by sytolk** [comment]
I see this: 
https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js#L151

**Comment by guyca** [comment]
Does it work? Maybe we do support it and I forgot? Could be it's just a copy paste tabs declaration.

**Comment by sytolk** [comment]
@guyca yes it works. But this not resolve my problem :)
```
onNavigatorEvent(event) {
        if (event.id === 'backPress') {
// TODO: skip Modal Dialog from history and go to the next one in the History stack
        }
    }
```
Maybe it's better to have an other option that I can set to Fragment like: skipFragmentFromBackStack: true
