### ISSUE TITLE
Push Notifications started app when it dropped from process.

### ISSUE THREAD

**Issue by Vetalyo** [wix/react-native-navigation#1799]
### Issue Description
Hello, thank you for you plugin!

I have one problem, when my app is dropped from process, and received push notification, app started and becomes to foreground. (Even if another app opened right now)

I am using plugin [react-native-fcm](https://github.com/evollu/react-native-fcm) to handle push notification.

I found the similar problem in [#566](https://github.com/wix/react-native-navigation/issues/566), but I did not fount working solution there.

Here is my code to start application:
```
startApp();

function startApp() {
  Navigation.startSingleScreenApp({
    screen: {
      screen: 'splash'
    },
    drawer: {
      left: {
        screen: 'screen1'
      },
    },
    animationType: 'fade'
  });
} 
```

On iOS I have no problems with it.

### Steps to Reproduce / Code Snippets / Screenshots
1. Run app
2. Drop app form process
3. Received PUSH notification (I don`t clicked on it)
4. App started in foreground

---
### Environment
* React Native Navigation version: 2.0.1
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device/7.1.1 / Debug (tested on Nexus X, and Xperia XA)

**Comment by kholiavko-roman** [comment]
I have same problem. 
I discovered, that when app started normally, or (app closed from process) and push received - app becomes to foreground, callback that catches push notification, fires with [this data:]
![Data from my usual notification.](http://joxi.ru/V2VnQnQsxXJVn2.jpg)

In case when push received - callback shows only which data ( data that send directly from push, does not shows)

Data from my usual notification.
![Data from my usual notification.](http://dl4.joxi.net/drive/2017/09/08/0005/3103/338975/75/9be78057e5.jpg)

**Comment by ywongweb** [comment]
Same problem here, also using react-native-fcm

**Comment by kholiavko-roman** [comment]
@ywongweb, did you found solution to solve the problem ?

**Comment by horacehylee** [comment]
+1 Having the same problem

**Comment by hovoodd** [comment]
+1 Same problem

**Comment by varungupta85** [comment]
You should invoke the app like shown below if you are not already doing so. This should fix this problem. It is also listed in the official documentation [here](https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=compatibility-with-headlessjs).

```javascript
import {Navigation, NativeEventsReceiver} from 'react-native-navigation';

Navigation.isAppLaunched()
  .then(appLaunched => {
    if (appLaunched) {
      startApp(); // App is launched -> show UI
    }
    new NativeEventsReceiver().appLaunched(startApp); // App hasn't been launched yet -> show the UI only when needed.
  });

function startApp() {
  Navigation.startTabBasedApp({ ... });
}
```

**Comment by kholiavko-roman** [comment]
@varungupta85, I already try this. It does not help. App launch when it was closed when push received.

**Comment by varungupta85** [comment]
@kholiavko-roman Okay. Could you share how you are making the `start*App` call in your app?

**Comment by kholiavko-roman** [comment]
@varungupta85 
here is my start app code
`export default class App extends Component {
  constructor(props) {
    super(props);

    PushNotification.configure(); // get device id for push notification and save it to async storage.

    Promise.resolve(Navigation.isAppLaunched())
    .then(appLaunched => {
      if (appLaunched) {
        this.startApp(); // App is launched -> show UI
      } else {
        new NativeEventsReceiver().appLaunched(this.startApp()); // App hasn't been launched yet -> show the UI only when needed.
      }
    });
  }

  startApp() {
    Navigation.startSingleScreenApp({
      screen: {
        screen: 'splash'
      },
      drawer: {
        left: {
          screen: 'drawer'
        },
        animationType: 'door'
        //optional, iOS only, for MMDrawer: 'door', 'parallax', 'slide', 'slide-and-scale'
        // for TheSideBar: 'airbnb', 'facebook', 'luvocracy','wunder-list'
      },
    });
  } //end of startApp
} //end of App
`

**Comment by filipochka97** [comment]
I also have the same problem, help me, please.

**Comment by varungupta85** [comment]
The startup code looks okay. I am not sure what is wrong.

**Comment by kholiavko-roman** [comment]
@varungupta85, try to make simple app with FCM push notification and you will see our pain 😢
Or maybe anybody have an example project and can share it ?

**Comment by reyalpsirc** [comment]
Can you try to remove the "else" you have around `new NativeEventsReceiver().appLaunched(this.startApp()); ` ?

**Comment by umerbaig** [comment]
I'm having same issue.

**Comment by jslz** [comment]
(fwiw we see the same thing :-)
