### ISSUE TITLE
Local image resources

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#18]
What challenges should I expect if I wanted to use fonts from packages like this.?

https://github.com/oblador/react-native-vector-icons.

**Comment by pvlvsk** [comment]
Hello smooJitter,

have you managed to use vector icons with this navigator?

**Comment by smooJitter** [comment]
Yes, something like this should work.

` class ColoredView extends Component {
  componentWillMount() {
    Icon.getImageSource('md-arrow-back', 30).then((source) => this.setState({ backIcon: source }));
  }
  _navigateToSubview() {
    this.props.navigator.push({
      component: ColoredView,
      title: this.props.pageText,
      **leftButtonIcon: this.state.backIcon,**
      onLeftButtonPress: () => this.props.navigator.pop(),
      passProps: this.props,
    });
  }
`

**Comment by pvlvsk** [comment]
Thank you!
