### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by rui-infotrack** [wix/react-native-navigation#180]
![image](https://cloud.githubusercontent.com/assets/12144265/17462293/b4406aac-5ceb-11e6-92ed-1e63972e1d60.png)
This is first time I use this library, so forgive my ignorance. Is there anything I missed here? I followed the instruction - Library link, build settings, etc. But the build failed. Is this some "classic" error?

Thank you very much

**Comment by webzepter** [comment]
Duplication #179
