### ISSUE TITLE
dismissModal() promise return inconsistently between platforms

### ISSUE THREAD

**Issue by neuberoliveira** [wix/react-native-navigation#1800]
### `dismissModal()` promise return inconsistently

In the IOS the method `dismissModal()` return a promise so i can wait until its dismissed and then do something.

But in the Android its `undefined`, dont know if its the expected behavior but would be nice if it was documented properly.

IOS - Cleary returning a promise.
![promise-ios-1](https://user-images.githubusercontent.com/3378304/30131099-ddee2232-9321-11e7-9e43-56362b27c92d.png)

Android - `undefined`
![promise-android-1](https://user-images.githubusercontent.com/3378304/30131106-e6506a0c-9321-11e7-87bb-8b74d559c755.png)

---
### Environment
* React Native Navigation version: 1.1.134
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by Jose4gg** [comment]
Any updates on this one?
