### ISSUE TITLE
[ios] orientation doesn't work as expected

### ISSUE THREAD

**Issue by DanielZlotin** [wix/react-native-navigation#1803]
### Issue Description

Setting orientation in iOS produces weird results when actually rotating screen.
Also, it sometimes fails the tests because the landscape orientation is lingering

---
### Environment
* React Native Navigation version: 2.0.x
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): 10.3 debug

**Comment by joonhocho** [comment]
I also noticed on playground that it rotates screen, but status bar (where time is displayed on iOS) remains portrait. It's bizarre.
