### ISSUE TITLE
How to use vector icons instead of image in tabs ?

### ISSUE THREAD

**Issue by saudpunjwani101** [wix/react-native-navigation#1804]
I have a question,

    Navigation.startTabBasedApp({
       tabs: [
        {
          label: 'Categories',
          screen: 'checkLogin',
          icon: require('./src/images/grocery.png'),
          //want to do it like this
          selectedIcon: <Icon name="md-home" />,
          title: 'Categories'
       }
     ]
   })

instead of requiring image, is it possible to use vector icons? Using images is painful

**Comment by renrizzolo** [comment]
@saudpunjwani101 have a look at this https://gist.github.com/dropfen/4a2209d7274788027f782e8655be198f

Full issue with other examples here  https://github.com/wix/react-native-navigation/issues/43

**Comment by brunolemos** [comment]
@renrizzolo the examples you mentioned use `getImageSource`, which generates an png, not a vector icon.

I see the `leftButtons` and `rightButtons` screen properties accept a `component` field, which works great to use vector icons ([code](https://github.com/wix/react-native-navigation/issues/43#issuecomment-352187447)).

But tab icons doesn't seem to support it, right?
Maybe we should reopen this issue to track this?

cc @guyca

**Comment by calcazar** [comment]
This should be reopened.. Limiting the icons on the tab bar to only be images is a bit silly...

**Comment by hugows** [comment]
> @saudpunjwani101 have a look at this https://gist.github.com/dropfen/4a2209d7274788027f782e8655be198f
> 
> Full issue with other examples here #43

This now 404s
