### ISSUE TITLE
java.lang.NoClassDefFoundError: com.reactnativenavigation.react.JsDevReloadHandler

### ISSUE THREAD

**Issue by abellee** [wix/react-native-navigation#1805]
works above android 5.0 but android 4.x

---
### Environment
* React Native Navigation version: ^1.1.188
* React Native version: 0.46.1
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?):  All

**Comment by jykun** [comment]
maybe it can help you, 
https://developer.android.com/studio/build/multidex.html
and setting like this:  http://quanke.name/2016/07/19/%E5%AE%8C%E7%BE%8E%E8%A7%A3%E5%86%B3-java-lang-NoClassDefFoundError-R-R-%E5%B7%A8%E5%9D%91/
