### ISSUE TITLE
Leakage in Android

### ISSUE THREAD

**Issue by sytolk** [wix/react-native-navigation#1807]
My LeakCanary show:
![device-2017-09-07-174957](https://user-images.githubusercontent.com/1415463/30169408-0092684c-93f5-11e7-90b8-a2b199ef7969.png)

**Comment by sytolk** [comment]
It's have leakage in Android example app. To repeat it install LeakCanary and reload app (Ctrl+R)
![device-2017-11-16-135353](https://user-images.githubusercontent.com/1415463/32890041-d6a5110c-cad5-11e7-8a8d-162f19b5c99d.png)

**Comment by guyca** [comment]
Can you reproduce in release?

**Comment by sytolk** [comment]
@guyca I have install LeakCanary in debug build only. But what will be different in release?

```
dependencies {
    // Real LeakCanary for debug builds only: notifications, analysis, etc
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.3.1'

    // No-Op version of LeakCanary for release builds: no notifications, no analysis, nothing
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.3.1'
 }
```

**Comment by guyca** [comment]
LeakCanary has a very strict means of detecting activity leaks and it has a certain amount of false positives. If this issue is occurring only in debug due to reloading, I would regard it as lower priority.
