### ISSUE TITLE
initialTabIndex unsuported in android

### ISSUE THREAD

**Issue by MrLoh** [wix/react-native-navigation#1808]
it seems like `tabsStyle: {initialTabIndex}` is not supported on android. is there any other way to properly set the initial tab?

**Comment by MrLoh** [comment]
I figured something out, doing a deep link, but it was paynfull to get it work, because I needed to figure out a way to not send the deeplink before the app screen listeners were ready.

**Comment by Frexuz** [comment]
Would be nice to see your solution :)

**Comment by MrLoh** [comment]
Just fire a deep link on app start, listen in all screens for deep links so you can manage the whole app with deep links. I can't easily share the code, it's too entrenched in how I setup my app.

**Comment by MrLoh** [comment]
See here for more ideas: https://github.com/wix/react-native-navigation/issues/993#issuecomment-327910466

**Comment by blackhair** [comment]
Android : 
```
                    appStyle: { 
                        initialTabIndex: 2, 
                    },
```
