### ISSUE TITLE
Android navBarTitleTextCentered with leftBarButton not centered

### ISSUE THREAD

**Issue by blairvanderhoof** [wix/react-native-navigation#1809]
### Issue Description
* Android Simulator
* navBarTitleTextCentered: true
* Have a left button in the nav using this.props.navigator.setButtons
* As soon as this.props.navigator.setButtons is called, the text shifts to the right.  If I call it again, it seems to re-center.

Bad:
![image](https://user-images.githubusercontent.com/833890/30171276-652c4cb8-93a6-11e7-838e-4f8b68ec06b9.png)

Good:
![image](https://user-images.githubusercontent.com/833890/30171270-597e05c8-93a6-11e7-9bcf-d2f46bc7eef8.png)

**Comment by BIWhitfield** [comment]
Did you find a solution to this? I'm having the exact same problem even with navBarTitleTextCentered: true in my styling.

**Comment by BIWhitfield** [comment]
My work-around for this is to call `navigator.setStyle({ navBarTitleTextCentered: true });` after you call setButtons. It seems that as soon as you add the menu button to the left it fails to recalculate the width based on that and recenter itself.
