### ISSUE TITLE
Multiple Left/Right Side Drawers (Options)

### ISSUE THREAD

**Issue by hans0low** [wix/react-native-navigation#1811]
Hello, I was looking for a way to do multiple options for the left side or ride side drawer.

Something along the lines of:
```
drawer: {
  left: {
    [
      {screen: 'FormOptions'},
      {screen: 'FilterOptions'}
    ]
  }
}
```

And then call by:
```
this.props.navigator.setDrawerEnabled({
      side: 'left',
      enabled: true,
      screen: 'FormOptions'
});
this.props.navigator.toggleDrawer({
      side: 'left',
      animated: true,
      to: 'open'
      screen: 'FormOptions'
});
```

Would this be possible? Documentation does not seem to allow it.

---
### Environment
* React Native Navigation version: 1.1.205
* React Native version: .47
* Platform(s) (iOS, Android, or both?): iOS

**Comment by witalobenicio** [comment]
I would appreciate that too
