### ISSUE TITLE
No lowercase capability on bar button items

### ISSUE THREAD

**Issue by jolones** [wix/react-native-navigation#1814]
### Issue Description

There is no style config to change the case of the button items

### Steps to Reproduce / Code Snippets / Screenshots

Set bar button to text

---
### Environment
* React Native Navigation version: ^1.1.205
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 5X Sim 23

Thanks!

**Comment by adnanaliarshad** [comment]
@jolones any solution fort this issue?
