### ISSUE TITLE
Can't install example app

### ISSUE THREAD

**Issue by jslok** [wix/react-native-navigation#1815]
### Issue Description

When I try to install the example app with npm install, I get the following errors:
```
> detox@5.6.1 postinstall C:\Users\jlok\Documents\reactnative\react-native-navigation-master\example\node_modules\detox
> scripts/postinstall.sh

'scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! detox@5.6.1 postinstall: `scripts/postinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the detox@5.6.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jlok\AppData\Roaming\npm-cache\_logs\2017-09-09T08_48_40_039Z-debug.log
```

### Steps to Reproduce / Code Snippets / Screenshots

Download the react-native-navigation package from github.
cd to the /example folder
npm install

---
### Environment
Windows 10 64

Any help would be appreciated. Thanks!

**Comment by nolan-m** [comment]
Looks like a Windows file path issue.

Look in package.json.  The postinstall command is specifying ` "postinstall": "node ./scripts/postinstall.js",`

on Windows it should be `.\scripts\postinstall.js`

Change this and see if it works.

**Comment by justinlok** [comment]
`"postinstall": "node .\\scripts\\postinstall.js"` gave the same error. Needed two \ to escape it.

I ended up removing many things related to the error from package.json and it built and ran on my device correctly. package.json looked like this:
```
{
  "name": "example",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "cd android && ./gradlew installDebug"
  },
  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-animatable": "^1.1.0",
    "react-native-navigation": "latest"
  }
}
```

**Comment by prgpascal** [comment]
Same issue here, editing the package.json of the example project doesn't worked for me.

Windows 7 64
react-native: 0.47.2
react-native-navigation: latest

**Comment by ibpasha1** [comment]
Experiencing this on windows 10 as well.
Trying to do npm install causes this issue. Running the example on a mac seems fine.
