### ISSUE TITLE
Milestone: Version 2.1.0

### ISSUE THREAD

**Issue by drorbiran** [wix/react-native-navigation#182]
The main purpose of this issue is to create a discussion about the version scope and overall architecture.
We'll start to use [Version 2.1.0](https://github.com/wix/react-native-navigation/milestone/2) milestone to collect all PRs, issues and features that will be a part of the version.
## The general goals for this version are:
- Android tests
- iOS tests
- Activity results

**Comment by divyekhanna** [comment]
Hi, the library does not play well with react-native-fbsdk. Is there any change that can be fixed? Specifically, the SplashActivity transits to NavigationActivity upon app start, therefore the callback from Facebook SDK is not fired. Any suggestions? or plans to resolve this?

Thanks!
