### ISSUE TITLE
popToRoot breaks interactive swipe gesture

### ISSUE THREAD

**Issue by mobitar** [wix/react-native-navigation#1823]
My controller stack looks like [root, vc1, vc2], and I pop to root via:
```
this.props.navigator.popToRoot({
  animated: true,
});
```

When I now go from root and push another vc, the iOS interactive back swipe gesture no longer works.

This has something to do with the horizontal dismiss animation as if I use `animationType: 'fade'` I don't see this issue.

iOS 10.3.1, iPhone 6 Simulator
"react": "16.0.0-alpha.12"
"react-native": "0.48.1"
"react-native-navigation": "^1.1.213"

**Comment by thanhzusu** [comment]
I think it's the same issue with #1839

**Comment by mobitar** [comment]
Ah bingo. That is indeed the fix.

RCCNavigationController.m, add after line 210:

```
if (self.viewControllers.count > 0)
{
   [self.viewControllers.lastObject viewWillDisappear:animated];
}
```

so that popToRoot looks like this:

```
// popToRoot
if ([performAction isEqualToString:@"popToRoot"])
{
  NSString *animationType = actionParams[@"animationType"];
  if ([animationType isEqualToString:@"fade"])
  {
    CATransition *transition = [CATransition animation];
    transition.duration = 0.25;
    transition.type = kCATransitionFade;

    [self.view.layer addAnimation:transition forKey:kCATransition];
    [self popToRootViewControllerAnimated:NO];
  }
  else
  {
    if (self.viewControllers.count > 0)
    {
       [self.viewControllers.lastObject viewWillDisappear:animated];
    }
    
    [self popToRootViewControllerAnimated:animated];
  }
  return;
}
```

**Comment by whyinteractive** [comment]
Any short term solution to solve this?

**Comment by sajsanghvi** [comment]
@mobitar that solution didn't work for me...any ideas? I am popping to root just by pressing the tab icon multiple times

**Comment by mobitar** [comment]
I keep a conservative fork here that I use in production with no problems: https://github.com/mobitar/react-native-navigation

Too many commits on this repo to keep up with ;)

**Comment by sajsanghvi** [comment]
I was able to solve it by returning NO in the tab bar controller, and popping to root from the javascript on tabreselect
