### ISSUE TITLE
Navigation bar icons are missing from Android app sometimes

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#1824]
### Issue Description

Sometimes, I have noticed that the navigation bar icons are missing from the top in the Android tap as shown below. The icons are png files and NOT vector icons.

![whatsapp image 2017-09-10 at 12 52 31 am](https://user-images.githubusercontent.com/7475133/30246270-e1bbd29e-9612-11e7-9d18-92c2427687ee.jpeg)

There are supposed to be three icons on the top as shown in this screenshot

![whatsapp image 2017-08-16 at 11 45 44 pm](https://user-images.githubusercontent.com/7475133/30246274-f55ab91e-9612-11e7-8716-d0b8ea9faccb.jpeg)

They start to show up if I push and pop a screen or change tab and go back to the previous tab. It feels as if the navigation bar icons are rendered before the screen is pushed due to which they don't show up.

### Steps to Reproduce / Code Snippets / Screenshots

This problem is intermittent and there are no set steps to reproduce it.

---
### Environment
* React Native Navigation version:1.1.203
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by sorter** [comment]
I am also having this issue on some Samsung devices like the Galaxy Note IV. Navigating has no effect on whether or not they appear.

Meanwhile app icons render just fine on iOS and android simulators.

**Comment by blainemuri** [comment]
I'm also having this same issue, currently looking for a solution.

Environment
-------------
* React Native: 0.47.2
* React Native Navigation: 1.1.245
* Platform: Android (iOS works fine)
* Device info: Both

The problem seems to occur mostly when I bundle the application and deploy it (to HockeyApp), but will occasionally also occur when debugging.

**Comment by eldooon** [comment]
Was there a solution to this? It seems to happen more frequently (every 3-4) tries on a deploy and occasionally on debug (every 10-15).

**Comment by samiede** [comment]
This still occurs, has there been a fix?
