### ISSUE TITLE
Change tab in TabNavigator not call componentWillUnmount

### ISSUE THREAD

**Issue by galhardi** [wix/react-native-navigation#1826]
I'm new in react-native and I'm trying use TabNavigator. In one tab I use react-native-camera with a conditional render.
I need handler componentWillUnmount to change my conditional render, but this event is never called?
What's I'm doing wrong?

**Comment by Sunil6591** [comment]
I am facing the same issue? @galhardi is it resolved how?

**Comment by galhardi** [comment]
@Sunil6591, I dint't test anymore.
