### ISSUE TITLE
Integration. Requirements for native apps are too strict. 

### ISSUE THREAD

**Issue by sneerin** [wix/react-native-navigation#1827]
### Issue Description
If you have an existing app, changing extending of the app is to strict, and could be a blocker for many people, also hiding launching options etc

---
### Environment
* React Native Navigation version: 1.1
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): any

**Comment by sneerin** [comment]
just to clarfiy if I have multidex application, I can't add custom extend and so on.

**Comment by andfk** [comment]
@sneerin did you find any solution? I need to support at least API 19 and I can´t get to work the following code:
```public class MyApplication extends SomeOtherApplication {
  @Override
  protected void attachBaseContext(Context base) {
     super.attachBaseContext(context);
     Multidex.install(this);
  }
}
```

**Comment by sytolk** [comment]
@andfk the same init code for Multidex work for me. What is the error?
