### ISSUE TITLE
Can a Tabbar item open a Modal window?

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#183]
I wanted to ask if there is a way for a tabbar item to open a modal window, and on close, to navigate to the previous tabbar scene.

**Comment by guyca** [comment]
@perrosnk You can call both, `showModal` and `dismissModal` from a static reference to `Navigation`.

```js
import {Navigation} from 'react-native-navigation';

Navigation.showModal({...});

Navigation.dismissModal();
```

**Comment by brianjd** [comment]
@guyca How would you attach Navigation.showModal({...}) to a "tab button"?

**Comment by guyca** [comment]
@brianjd I don't think that's possible atm since right now, you don't know when a screen is displayed and when a tab is pressed. I've opened #268 to address this.

**Comment by brianjd** [comment]
@guyca Thanks for the clarification.  That's what I thought, but based on your earlier response thought I may have been missing something.
