### ISSUE TITLE
What is a good approach to implementing an "onboarding" process with redux?

### ISSUE THREAD

**Issue by kevando** [wix/react-native-navigation#184]
I implemented the redux example and I would really like to include an onboarding process that is stored in redux.

For example, user does something to set the state such that it should display an onboarding message via lightbox. Any thoughts?

**Comment by guyca** [comment]
@kevando Maybe consider using [Overlay](https://github.com/brentvatne/react-native-overlay) or something similar. I'm not sure what's the common approach for onboarding overlays (I assume that's what you meant)

I'm not sure about lightbox, but on Android the Modal has transparent background, so you could show it with no animation, and do your magic in JS.

**Comment by kevando** [comment]
@guyca  Thanks for responding. I can make the overlays work with lightbox, my onboarding display is not complex, but I would like to have several pop ups throughout the entire experience.  Therefore I want a more sophisticated way of displaying the onboadring messages that is seperate from the app code.

I'm going to try adding the following code to the onStoreUpdate function in the [Redux Example](https://github.com/wix/react-native-navigation/blob/master/example-redux/src/app.js) app.js file.

``
onStoreUpdate() {
    const root = store.getState().app.get('root');
    // handle a root change
    // if your app doesn't change roots in runtime, you can remove onStoreUpdate() altogether
    if (this.currentRoot != root) {
      this.currentRoot = root;
      this.startApp(root);
    }
// ONBOARDING STUFF
    const step = store.getState().onboard.get('step');
    const currentStep = store.getState().onboard.get('currentStep');

    if (currentStep != step) {
      // immediately reconcile step so this doesnt repeat
      store.dispatch(onboardActions.incrementStep());

      onboardingStepProps = store.getState().onboard.get('steps').get(currentStep);

      Navigation.showLightBox({
        screen: "chaz.OnboardPopup",
        passProps: onboardingStepProps,
        style: {backgroundBlur: "none", backgroundColor: onboardingStepProps.backgroundColor, }
      });
    }
}
``

Not sure if this will slow down the app, or there's some glarring issue, but I think this will work.
