### ISSUE TITLE
[Android] Drawer width is only 60dp

### ISSUE THREAD

**Issue by mdrbohlav** [wix/react-native-navigation#1843]
Sometimes (first app run) the drawer width is only 60dp in Android. Its fixed after reload but I do not want to force users to reload the app. I will add screenshots later today.

![screenshot_1505226130](https://user-images.githubusercontent.com/7562302/30331080-1c4c6016-97d7-11e7-8282-da515267c87a.png)

`sideMenuView.getChildAt(0).getWidth()` at `/java/com.reactnativenavigation/views/SideMenu.java:135` returns only 60 sometimes.

---
### Environment
* React Native Navigation version: 1.1.205
* React Native version: 0.48.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): OnePlus 2, LineageOS, Android 7.1.2 and Emulator AIP 25

**Comment by guyca** [comment]
Hey @mdrbohlav 
Do you specify an exact width in the root view rendered in the drawer? That should resolve this.

**Comment by mdrbohlav** [comment]
No, I use `flex: 1`. It worked before I updated the packages (react-native, react-native-navigation) so I thought it is a bug. I set minWidth and it works like a charm, thank you

**Comment by Danny-weebo** [comment]
@guyca I'm having the same problem **but only with the right drawer** (on the left one it works as expected). as the right drawer root view is styled with `{ flex: 1, width: Dimensions.get('window').width }` but still there is something which is 'blocking' it from spreading widely, as you can see in the following screenshot. any ideas about it ?

result for `{ flex: 1, width: Dimensions.get('window').width }`
<img width="399" alt="screen shot 2017-12-06 at 13 48 02" src="https://user-images.githubusercontent.com/6795014/33660348-2cbe885a-da8c-11e7-9bb9-5d6eec53bb24.png">
result for `{ flex: 1, width: 100 }`
<img width="434" alt="rightdrawer" src="https://user-images.githubusercontent.com/6795014/33660418-54815d7c-da8c-11e7-9791-330d399211cf.png">
