### ISSUE TITLE
Example app stops working

### ISSUE THREAD

**Issue by AlexNetsov** [wix/react-native-navigation#185]
I start from blank RN 0.31. After fixing the issue with the #import <objc/runtime.h> there are other problems. Second after starting the example app I get this errors in Xcode:

`2016-08-08 02:50:18.491 [warn][tid:main][RCTEventEmitter.m:52] Sending `websocketFailed` with no listeners registered.
2016-08-08 02:50:18.554 [warn][tid:com.facebook.react.JavaScript] Set to default type=MMDrawer animationType=slide
2016-08-08 02:50:18.616 [info][tid:com.facebook.react.JavaScript] Running application "example.SecondTabScreen" with appParams: {"rootTag":1,"initialProps":{"navigatorID":"6zq3mrj3y50jk_nav1","screenInstanceID":"izf3v51njls00","navigatorEventID":"izf3v51njls00_events"}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
2016-08-08 02:50:18.671 Testo[24603:2052520] *** Assertion failure in -[RCTUIManager registerRootView:withSizeFlexibility:](), /Users/alex/Sites/react-native-app/Testo/node_modules/react-native/React/Modules/RCTUIManager.m:375
2016-08-08 02:50:18.683 Testo[24603:2052520] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Expect all root views to have unique tag. Added 1 twice'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010399fd85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000102b94deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010399fbea +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00000001027dee1e -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 169
	4   Testo                               0x0000000102391ed8 -[RCTUIManager registerRootView:withSizeFlexibility:] + 1176
	5   Testo                               0x00000001022e2364 -[RCTRootContentView initWithFrame:bridge:reactTag:sizeFlexiblity:] + 516
	6   Testo                               0x00000001022e10ae -[RCTRootView bundleFinishedLoading:] + 286
	7   Testo                               0x00000001022e0f65 -[RCTRootView javaScriptDidLoad:] + 437
	8   CoreFoundation                      0x0000000103969c8c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	9   CoreFoundation                      0x00000001039699cb _CFXRegistrationPost + 427
	10  CoreFoundation                      0x0000000103969732 ___CFXNotificationPost_block_invoke + 50
	11  CoreFoundation                      0x00000001039b21e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1986
	12  CoreFoundation                      0x0000000103861679 _CFXNotificationPost + 633
	13  Foundation                          0x0000000102720cd9 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	14  Testo                               0x000000010233dcfc __38-[RCTBatchedBridge executeSourceCode:]_block_invoke.273 + 220
	15  libdispatch.dylib                   0x0000000106e2cd9d _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x0000000106e4d3eb _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x0000000106e351ef _dispatch_main_queue_callback_4CF + 1738
	18  CoreFoundation                      0x00000001038f90f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	19  CoreFoundation                      0x00000001038bab99 __CFRunLoopRun + 2073
	20  CoreFoundation                      0x00000001038ba0f8 CFRunLoopRunSpecific + 488
	21  GraphicsServices                    0x0000000108964ad2 GSEventRunModal + 161
	22  UIKit                               0x00000001057adf09 UIApplicationMain + 171
	23  Testo                               0x00000001022c78ef main + 111
	24  libdyld.dylib                       0x0000000106e8192d start + 1
	25  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by igagen** [comment]
I just ran into this same issue

**Comment by knot123** [comment]
Same here!

**Comment by folivi** [comment]
RN 31 not supported yet. I had to downgrade to 27 to get it to work

**Comment by JustinJKlein** [comment]
Me too!  I would love to see this fixed soon!

**Comment by bbrock25** [comment]
Are there plans to support 0.31? I just found this project today and I'm so pumped on it I'm considering rolling RN back to 0.25 on my project for these features :)

**Comment by guyca** [comment]
@bbrock25 Officially we support RN 0.25.1. From what I read here in the threads, some users are using RN 0.27 with out problems.
We're going to upgrade the project to the most up to date version at the end of august/ beginning of September.

**Comment by bbrock25** [comment]
👏 thanks @guyca, that's very exciting.

**Comment by DanielZlotin** [comment]
Please see #234
