### ISSUE TITLE
Drawer is not working with nested "startSingleScreenApp" call.

### ISSUE THREAD

**Issue by kaltindas** [wix/react-native-navigation#1851]
I have a Login/Register Page and on press on Login Button i want to start a new SingleScreenApp with Drawer. Drawer (Hamburger Btn) will rendered but without function. It happens nothing on click.. Same code (startSingleScreenApp) does work if i execute it on the root of App. 

`
export default class Splash extends Component {

    onPressed(){
        Navigation.startSingleScreenApp({
            screen: {
                screen: 'Home',
                title: 'Welcome',
                navigatorButtons: {
                    leftButtons: [
                        {
                            id: 'sideMenu',
                        }
                    ]
                }
            },
            drawer: {
                left: {
                    screen: 'Drawer',
                },
            },
            animationType: 'slide-down'
        });
    }

    render() {
        return(
            <View>
                <Button
                    onPress={ () => this.onPressed() }
                    title="Login And Open App"
                    color="#841584"
                />
            </View>
        )
    }
}` 

Whats wrong here?

**Comment by chakrihacker** [comment]
Any update, I am having same problem

**Comment by RiCoTeRoX** [comment]
@kaltindas hi! did you resolve this issue ?

**Comment by isaachinman** [comment]
I am also experiencing this issue on an iOS 11 real device. Interestingly, it works fine in simulator.

Using react-native-navigation v1.1.407

@guyca Any idea what this is about?

**Comment by nemat001** [comment]
Rather than opening a drawer with navigation.navigate(‘DrawerOpen’), you can now call navigation.openDrawer()
