### ISSUE TITLE
[question] How to implement tab based app on subscreen?

### ISSUE THREAD

**Issue by pedrogarciyalopez** [wix/react-native-navigation#1852]
What is the proper way to implement navigation like on the figure?
![question](https://user-images.githubusercontent.com/14232660/30393026-67b04e00-98c7-11e7-9bb1-97177ee47876.jpg)

**Comment by sytolk** [comment]
I have use this approach: https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js

**Comment by guyca** [comment]
Just as @sytolk mentioned, you can call startSIngle/TabBasedApp multiple times, simply start to correct root according to your flow.

**Comment by gusterwoei-veltra** [comment]
startSIngle/TabBasedApp will reset the stack root, which causes the app to quit when back pressed

**Comment by witalobenicio** [comment]
I'm huge fan of this lib, but this behavior of reset the stack root when calling another type of basedApp is really bad. Maybe in v2 it's different (didn't tried yet, I'm waiting a version with more functions).
