### ISSUE TITLE
Android 5.x navBarNoBorder doesn't seem to work

### ISSUE THREAD

**Issue by jslz** [wix/react-native-navigation#1853]
### Issue Description

navigatorStyle with { navBarNoBorder: true } does what I expect on iOS but not on Android. On Android there is still a hairline style border at the bottom of the navBar itself.

### Steps to Reproduce / Code Snippets / Screenshots

<img width="413" alt="phone_android" src="https://user-images.githubusercontent.com/27701565/30403758-0012cdc4-9898-11e7-8c7e-e0900da295fa.png">

<img width="413" alt="phone_ios" src="https://user-images.githubusercontent.com/27701565/30403759-0015f030-9898-11e7-8e02-7229fc25d57d.png">

---
### Environment
* React Native Navigation version: resolved "https://registry.yarnpkg.com/react-native-navigation/-/react-native-navigation-1.1.205.tgz#eb7ff639f97e7f5bde42f38d2b11b7a6ce06a2c0"
* react-native-cli: 2.0.1
* react-native: 0.46.4
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): sim, emu, devices (it behaves the same on each platform, so it is not apparently a problem with sim or emu vs. real devices).

**Comment by dbelchev** [comment]
For Android I use:
`topBarElevationShadowEnabled: false, // default: true. Disables TopBar elevation shadow on Lolipop and above`
