### ISSUE TITLE
Fix iOS11 safeArea effects on scrollView

### ISSUE THREAD

**Issue by gran33** [wix/react-native-navigation#1858]
### Issue Description

There is a margin under the top bar that shouldn't be there.
Related to iOS11 and react-native issue:
https://github.com/facebook/react-native/issues/15681

### Steps to Reproduce / Code Snippets / Screenshots

Running any app with screen contains any scroll view, when push then pop, the back screen comes from the bottom.

---
### Environment
* React Native Navigation version: 1.1.85
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator + real device

**Comment by gran33** [comment]
fixed in #1859

**Comment by DanielZlotin** [comment]
implement in v2

**Comment by gameboyVito** [comment]
it's not working on iOS10 while building with Xcode9, though it works on iOS11. See this: https://github.com/facebook/react-native/issues/15957

**Comment by gameboyVito** [comment]
Fixed, I will send you a PR if you don't mind.

**Comment by DanielZlotin** [comment]
So the current solution is a bug. This forces the users to specify magic number in their code, instead of letting the system do it's thing.

**Comment by LeoNatan** [comment]
Fixed in v2. Will back-port to v1.
