### ISSUE TITLE
Best way to transtion from singleScreenApp to tabBasedApp?

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#186]
What is the best way to transition to a tabBasedApp after the user has signed in, without using redux?

**Comment by guyca** [comment]
With out using redux? why wouldn't you use redux for this use case?

**Comment by perrosnk** [comment]
Because I don't really need redux in any other part of the app, but anyway thanks a lot!.
By the way, do you know if it's possible to use mobx?

**Comment by guyca** [comment]
I haven't tried. Sorry.
