### ISSUE TITLE
Drawer is not working on Android

### ISSUE THREAD

**Issue by bdavid68** [wix/react-native-navigation#1863]
### Issue Description

Drawer is not shown on Android

### Steps to Reproduce / Code Snippets / Screenshots

```
this.props.navigator.toggleDrawer({
      side: 'left',
      animated: true
    });
```

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by nimerfarahty** [comment]
set width for the drawer screen , it will works

**Comment by mathieuroblin** [comment]
I tried the drawer and am also encountering some issues on android even after setting up the width of the view.

I am able to show the drawer if I swipe my finger from the left of the screen to the center but not if I use navigator.toggleDrawer.

The code is running fine on iOS though.

React Native Navigation : 1.1.233
React Native version : 0.48
Platform : Android
Device info : Simulator, Android 7.1 & 8 (Haven't tried more versions) Debug

**Comment by BIWhitfield** [comment]
Hey guys for the time being I've followed the suggestion of setting the width directly on my Sidemenu component and it seems to be working.

` render() {
    return (
      <View style={{ height: '100%', width: 280, backgroundColor: 'rgb(240,239,245)' }}>
    .......
}
`

**Comment by SquaredData** [comment]
I encounter the same issue, even with the width-advise...

**Comment by bdavid68** [comment]
Yeah, set width seems to be working.

**Comment by SquaredData** [comment]
Hey bdavid, why did you close? I still have this problem...

**Comment by fmussap** [comment]
https://github.com/SquaredData

I was having this problem when using RN 0.51.
I downgraded it to RN 0.49.5 and now it's working when you set width property on the Sidemenu component

**Comment by SquaredData** [comment]
Thanks a lot!!! RN 0.49.5 works for me as well :)

**Comment by jamesguan** [comment]
This is still an issue, even on react-native version 0.54.0

**Comment by denieler** [comment]
I have this problem in RN 0.55.3 with "react-native-navigation": "^1.1.457".

I've set width for the Drawer component itself. But randomly after application installed and opened drawer doesn't open. I use `toggleDrawer` function to open it.

```
navigator.toggleDrawer({
  side: 'left',
  animated: true
})
```

After I close the app and open again it can start working. It's in release mode.
I do app for Android only, so it's happening for me when I update app from Google Play.

Please share some tricks how to fix this flickering Drawer. Thanks!

**Comment by augustofontes** [comment]
Does anyone have a workaround to this issue? I still face this problem on Android randomly in production.

**Comment by denieler** [comment]
@augustofontes it looks like it started to work as soon I've set a `backgroundColor` for the Drawer and set a fixed width in pixels.

If you will still having the problem - ping me, I will try to review the things I did to fix it.

**Comment by augustofontes** [comment]
Thank you, @denieler . This is the styling that I'm using for the root View for Drawer Screen component. Did you set the width like I did?

```
// Trying to fix a bug that causes drawer not to be shown sometimes
let drawerWidth = Dimensions.get("window").width * 0.8;

export default StyleSheet.create({
    SideDrawer: {
        width: drawerWidth,
        height: "100%",
        paddingVertical: 22,
        backgroundColor: Colors.dark
    },
// ...
```

**Comment by denieler** [comment]
No, I did this

```
const DRAWER_WIDTH = 840

const store = configureStore()

const startApp = screen => {
  return Navigation.startSingleScreenApp({
    screen: {
      screen: screen,
      navigatorStyle: {
        navBarHidden: true
      }
    },
    appStyle: {
      orientation: 'portrait'
    },
    drawer: {
      left: {
        screen: 'workoutApp.MainDrawer',
        fixedWidth: DRAWER_WIDTH
      }
    },
    animationType: 'none'
  })
}
```

**Comment by augustofontes** [comment]
Thank you so much.
