### ISSUE TITLE
A ScrollView in one container changes contentOffSet in other containers

### ISSUE THREAD

**Issue by bogobogo** [wix/react-native-navigation#1864]
This is reproducible in the example app by pushing to the scrollView screen and popping.

**Comment by guyca** [comment]
@bogobogo Is this still relevant? If so, on which platform does the bug happen?

**Comment by bogobogo** [comment]
@guyca Yes. On iOS.

**Comment by yogevbd** [comment]
@bogobogo Caused by topBar.translucent = false in ScrollViewScreen.js
Looks like normal behavior
