### ISSUE TITLE
[iOS] showLightBox, can't handle dimensions or positions

### ISSUE THREAD

**Issue by Soraph** [wix/react-native-navigation#1866]
### Issue Description

Can't set dimensions or positions of the lightbox.

### Steps to Reproduce / Code Snippets / Screenshots

I call showLightBox() from the toplevel API, example as follow:

```
Navigation.showLightBox({
      screen: 'DateFilter',
      style: {
        backgroundBlur: 'none',
        tapBackgroundToDismiss: false,
        width: 200,
      },
```

I endup with something that has unknow width outside the screen and ignore any dimension and position settings in style.

![image](https://user-images.githubusercontent.com/1741291/30474740-f433b478-9a04-11e7-9468-507e9144d98f.png)

---
### Environment
* React Native Navigation version: 1.1.189
* React Native version: 0.47.1
* Platform: iOS 10.3
* Device info: Simulator iPhone6

**Comment by anonrig** [comment]
I'm having the same exact issue at the moment.

**Comment by rpmonteiro** [comment]
Same here
