### ISSUE TITLE
StatusBar.setBarStyle("dark-content", true) doesn't work on Android modals

### ISSUE THREAD

**Issue by mobitar** [wix/react-native-navigation#1867]
When I present a modal via  `this.props.navigator.showModal`, the Android status bar text color is always white. When I dismiss the modal, it's back to black.

This only happens on Android. On iOS, it works wonderfully.
---
### Environment
* React Native Navigation version: 1.1.216
* React Native version: 0.48.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Nexus 6 API 23:5554

**Comment by andrewzey** [comment]
I went with this library, which implements a custom modal by default, and doesn't ruin the statusbar: https://github.com/maxs15/react-native-modalbox
