### ISSUE TITLE
How to show a splash in Javascript until all loading has completed?

### ISSUE THREAD

**Issue by basudz365** [wix/react-native-navigation#1870]
I am trying to integrate this navigation library into my app and have ran into a fundamental issue that I don't understand how to handle correctly.

When my app starts up, I rehydrate the Redux store (using Redux-Persist) and once that completes I need to check a fews things and validate a token against an API on my host.  While all of this is taking place, I need my loading screen to be showing so the user cannot use the app until all of this has completed.  

Depending on the users state in Redux and on the response from the API call, I need to start the user at different screens.  How can I achieve this with this navigation library?
I am using a tab based navigation app.

Would I have to use 2 different Navigation.startApp calls, one to start a single page app for my loading and one to start the tab based app once it's all completed?  Or can I can pop a full screen modal before anything else is displayed until I've finished everything in the background, and redirect them accordingly before dismissing the modal?

I used to use a library called react-native-splash-screen which was a splash screen at the native OS layer that I could dismiss from the javascript layer at any point.  This worked well but doesn't integrate here because this library uses it's only native activity and provides it's own splash screen for only the duration of the JS bundling phase.

**Comment by basudz365** [comment]
Closing because I don't think this is possible with this library and unfortunately nobody has been able to offer any information here or on stackoverflow.

**Comment by Stmol** [comment]
@basudz365 hi there! I also investigated this issue. All I could find is this example: https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js
I could not call the modal window right after the tab based application started. Because the tab based app `Navigation.startTabBasedApp` overrides the modal window `Navigation.showModal`.

And I do not think it's a good idea to run a single application `Navigation.startSingleScreenApp` for login action because there is no API to stop it. I'm not sure, but it seems to me that there are leaks. 

In addition, it remains necessary to display the Login screen in case the user loses the session while he uses the main tab based application. What to do in this case? Start a new single screen application again?

**Comment by basudz365** [comment]
@Stmol Thank you for the response!  I've looked into that solution that you linked and is what actually got me starting to try and implement this library into my app.  I really love the native feel of the navigational transitions but currently it doesn't seem like version 1 was meant to handle session based apps. 
Hopefully version 2 will have a more configureable splash screen and be able to handle this kind of scenario.  This is a very common scenario so I'm a little surprised it can't be handled here but I assume the version 1 of this library was created with the needs of the original developers environment.

**Comment by henrikra** [comment]
I agree that there should be better example of what to do when checking if user is authenticated and then show some screen @guyca

**Comment by Stmol** [comment]
@basudz365 At a glance I did not find any popular library allowing to easily solve this issue.

**Comment by basudz365** [comment]
@Stmol react-native-splash-screen works very well for this purpose with other navigational libraries but I wasn't able to get it working right here because this library extends from its own base activities/classes at the native layer.
With that library, you call the splash screen at the native layer and then you can dismiss from the React side of things at any point. This allows you to do any loading/checking/redirecting before dismissing the splash screen.  There's also react-native-smart-splash-screen which is the same thing with a few more options to configure the animation.

**Comment by michaeltnguyen** [comment]
@basudz365 Just solved this a few days ago.  Was a little tricky.  Here's how I did it (for context, I'm primarily a native android dev):

1.  With redux-persist, we get a callback once rehydration has occurred.  Use this for launching the authentication screen or the main screen.
```
    persistStore(store, {storage: AsyncStorage}, () => {
        launchFirstScreen()
    })

    launchFirstScreen() {
        if (store.getState().authenticated) {
            Navigation.startTabBasedApp({ // main screen
        } else {
            Navigation.startSingleScreenApp({ // auth screen
        }
    }
```
2.  Prior to the first `Navigation.startApp` call, a splash screen is visible, but its configuration is platform-specific.
3.  on iOS, there is a `LaunchScreen.xib` file.  Modify this file in `xcode`, and this layout will be visible up until your first `Navigation.startApp` call.
4.  on android, this is a bit trickier.  When the OS launches your app, but before any views are inflated, android shows the app's window background.  After the app is initialized, the JS part begins loading, and the app displays the layout specified in `createSplashLayout` or `getSplashLayout` of Wix's `SplashActivity`.  So there are actually two splash screens that are shown in android.  ASCII art:

```
----
 |
 |     OS initialization.  Displays android:windowBackground
 |
----
 |
 |     JS initialization.  Displays View created by Wix's SplashActivity
 |
----
 |
 |     App launches from Navigation.startApp
```
5.  So, to get this working on android:
5a.  create your window background.  You basically just need to create a `layer-list` drawable file and set it as your `android:windowBackground` in your splash activity.  Here's a good tutorial: https://www.bignerdranch.com/blog/splash-screens-the-right-way/
5b.  Override the `createSplashLayout` method of your `SplashActivity`.  We already have a window background splash screen, so just make the activity transparent so the splash screen is visible.
```
    @Override
    public View createSplashLayout() {
        View view = new View(this);
        // show the window background, which is our native splash screen
        view.setBackgroundColor(Color.TRANSPARENT);
        return view;
    }
```

**Comment by basudz365** [comment]
@michaeltnguyen thanks for the solution, I'll give it a shot!

**Comment by iCodePup** [comment]
@michaeltnguyen

I try your solution and i have an issue.
Between the splashscreen and the first view, a background splash with the icon app appear ?
