### ISSUE TITLE
navBarCustomView not displayed

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#1871]
### I use Tab navigation and on each tab, I have the customize navigation bar
When I upgrade to this version of navigation, the customized navigation not displayed on Android (still displayed on iOS)
navigatorStyle: {
                    navBarTextColor: Colors.TextWhitePrimary,
                    navBarCustomView: 'TOP_BAR_TAB',
                    navBarComponentAlignment: 'fill',
                    drawUnderTabBar: true,
                    navigationBarColor: Colors.OlaPrimaryDark,
                    statusBarColor: Colors.OlaPrimaryDark,
                    bottomTabBadgeBackgroundColor: Colors.OlaRedColor,
                    bottomTabBadgeTextColor: 'white',
                    topBarElevationShadowEnabled: false,
                },

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.227
* React Native version: 0.48.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Asus Zenphone 4 Pro

**Comment by radiegtya** [comment]
+1

**Comment by JesseARWhite** [comment]
+1

**Comment by aminroosta** [comment]
I have the same problem, did you found a workaround? The example project works on android ... Not sure what's going on.

**Comment by aminroosta** [comment]
It's working for me ... i just had a typo `navbarCustomView` instead of `navBarCustomView` 😄 
I just followed the example project.

**Comment by freiserg** [comment]
@guyca It happened after this commit https://github.com/wix/react-native-navigation/commit/9a7d483450e625b0beabe98a602e5f7806f3fcf1

@moonjava2005 try to use navBarHeight for appStyle.

**Comment by moonjava2005** [comment]
Thanks @freiserg

**Comment by SudoPlz** [comment]
For me, setting the `navBarHeight` wasn't helpful. Even after setting it there were times when the nav bar would be totally hidden on Android.

The `navBarCustomView` is **sometimes** displayed, and at other times it's hidden, but I can't really find out when it happens.

**Comment by SudoPlz** [comment]
After inspecting with the `LayoutInspector` it looks like my top bar view, does have the right height, but it's width is zero:

<img width="532" alt="screen shot 2017-11-16 at 02 19 24" src="https://user-images.githubusercontent.com/3070948/32867247-b6f6b218-ca74-11e7-8bc4-80aea110f6e5.png">

**Comment by SudoPlz** [comment]
Ok I believe I found what's going on, the problem was obvious on [this line](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/views/TopBar.java#L147).

In my Custom Nav Bar view (JSX) I was not specifying a width value and for some reason it could not be calculated by Yoga:
```
<View
    style={[
      {
        flexGrow: 1,
        zIndex: 2,
        justifyContent: 'center',
      },
      props.style,
    ]}
  >
```

I now switched my style to:

```
<View
    style={{
        zIndex: 2,
        // backgroundColor: 'pink',
        flex: 1,
        height: props.navBarHeight,
        /**
         * ALWAYS specify a width value here,
         * otherwise the nav bar on Android might not show up at all
         * https://github.com/wix/react-native-navigation/issues/1871
         */
        width: screenWidth * 0.96,
        justifyContent: 'center',
      }}
  >
```

and I haven't seen that problem afterwards.
All that I had to add was the static width value declaration.
The reason it's value is `screenWidth * 0.96` is because there's a ~4% left padding value on the left side of the custom nav bar at all times (no idea why, but it seems like its configured that way in react-native-navigation).
