### ISSUE TITLE
[question] How to change back button title in IOS?

### ISSUE THREAD

**Issue by pedrogarciyalopez** [wix/react-native-navigation#1877]
It is possible to change back button title in IOS with JavaScript?
I'm not familiar with native.

**Comment by thanhzusu** [comment]
You can use **backButtonTitle**.

**Comment by kyle-ssg** [comment]
@pedrogarciyalopez See https://wix.github.io/react-native-navigation/#/screen-api

**Comment by hariDasu** [comment]
```
  static options(passProps) {
    return {
      topBar: {
        backButton: {
          title: ""
        }
      }
    };
  }
```

for rnnV2
