### ISSUE TITLE
HMR crashing with 

### ISSUE THREAD

**Issue by MrLoh** [wix/react-native-navigation#1878]
My react-native-navigation based app with redux crashes when I try to use hot reloading. I get the following error that refers to react-native-navigation internal methods (my app starts from initialize.js). Can this have to do with react native navigation, or does it have to do with my redux setup in some way, because RNN is proven to work with hot reloading?

<img width="370" alt="screen shot 2017-09-17 at 23 13 12" src="https://user-images.githubusercontent.com/1285032/30524979-2475c84c-9bfe-11e7-9347-679d203d3568.png">

---
### Environment
* React Native Navigation version: 1.1.228
* React Native version: 0.47.2
* iOS Simulator with Hot Reloading enabled

**Comment by ethanyanjiali** [comment]
I have the same issue. And my case is that HMR works fine with tab screen, but if the changes is on the modal pop from those tab screens, the app will crash due to max call stack size exceeded.

**Comment by MrLoh** [comment]
I think it stopped for me after eliminating all circular dependencies in the app.

**Comment by ethanyanjiali** [comment]
Thanks for the help! It indeed solved my problem as well.

To be more specific, my code was like this:

/folderA
--index.js
--componentA.js
--componentB.js
/folderB
--screenA.js

in index.js, I imports componentA and componentB and exports them together
in componentA, it imports component B
in screenA it imports componentA from index.js (module-like import)

and after I remove the import of component B in index.js, it just works fine

**Comment by MrLoh** [comment]
@ethanyanjiali I still can't get HMR to work in my app. could you share your setup? I don't get any errors, but the modules don't hot reload. I think it might have something todo with the problems with functional components, but I can't reproduce it in a minimal setup yey.

**Comment by ethanyanjiali** [comment]
Hmm there's no log either? I didn't do something specifically to enable HMR. I did got an error before but that's because I accidentally turn on global.__DEV__=true
