### ISSUE TITLE
How to passing navagator props in reducer redux?

### ISSUE THREAD

**Issue by phumaster** [wix/react-native-navigation#1879]
Hi, everyone.
I'm looking for solution bellow:
I want to map navigator props to reducer.
```javascript

const mapStateToProps => state => {
    return {
         navagator: state.navagator // <---- It's here
    }
}
export default connect(mapStateToProps)(MyComponent);
```

Then, in MyComponent I can call this.props.navigator.push (or pop, showModal.....)

### Environment
* React Native Navigation version: ^1.1.227
* React Native version: ^0.47.0
* Platform(s) (iOS, Android, or both?): Both

Thank you.

**Comment by gusilveiramp** [comment]
+1

**Comment by phumaster** [comment]
plz support on v2.
