### ISSUE TITLE
Build failed on first attempt

### ISSUE THREAD

**Issue by arieh** [wix/react-native-navigation#188]
Trying to run the project for the first time, I'm getting an xcode build error.

I've followed all of the instructions in the README, and when running `react-native run-ios` I get the following error:

```
** BUILD FAILED **


The following build commands failed:
    CompileC /www/MyProject/ios/build/Build/Intermediates/ReactNativeControllers.build/Debug-iphonesimulator/ReactNativeControllers.build/Objects-normal/x86_64/RCCNavigationController.o RCCNavigationController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Versions:
- node 6.3.0
- npm 3.10.3
- react-native 0.31
- react-native-navigation 1.0.30

After looking at other tickets - I have tried running `react-native` upgrade, but it did not help (other than overriding the config files from the installation steps, which I had to redo)

What am I missing?

**Comment by rzmz** [comment]
I'm getting that same error trying to build my project after adding react-native-navigation
