### ISSUE TITLE
How to use it with Apollo-react?

### ISSUE THREAD

**Issue by mjt19930301** [wix/react-native-navigation#1883]
Apollo needs HOC at the outermost

**Comment by smooJitter** [comment]
I'm not sure what you are asking but I'm using this with Apollo.  So far so good. Essentially, use a HOC to wrap the screen component  w/  withApollo (from react-apollo) before you register the screen.  Note, sense you have already wrapped each screen with the apollo client and redux store, there's no need to adopt the approach for registering redux components as suggested in version 1 of this package.

**Comment by larryranches** [comment]
@smooJitter Do you have an example of this?

**Comment by sqow** [comment]
@smooJitter I'd also like to see an example of the HOC for this technique, if possible.

**Comment by larryranches** [comment]
@sqow I think this is what he might be referring to http://dev.apollodata.com/react/redux.html

**Comment by sqow** [comment]
@mjt19930301 @larryranches Here's how I ended up getting this all integrated:

1. I don't use `AppRegistry` in my `index.ios.js` or `index.android.js` files at all to register the main component, instead I use `Navigation.registerComponent` and `Navigation.startSingleScreenApp` or `Navigation.startTabBasedApp` — if I used `AppRegistry` even for the main component it would never connect to my GraphQL server for some reason
2. Registering my screens/components is done via `Navigation.registerComponent(name, () => withProvider(component))` where `withProvider` is a HOC (_see below_)
3. **Importantly**, I'm not making use of `Navigation.registerComponent`'s additional arguments (Provider, store, and options/props to pass to the Provider) as I found they didn't really get me to where I needed to be

With this setup, I'm able to combine `react-apollo`, `react-redux`, `formik`, and whatever other HOCs I need to achieve my goal. My `withProvider` HOC **is** similar to the internal HOC used by `react-native-navigation`, but is more simplistic.

```js
const withProvider = (Component, store = defaultStore, client = defaultClient) => {
  return class extends React.Component {
    render () {
      return (
        <ApolloProvider store={store} client={client}>
          <Component {...this.props} />
        </ApolloProvider>
      )
    }
  }
}
```

Hope that helps someone out there who has a hard time getting it all to work together!

**Comment by smooJitter** [comment]
@sqow that's it.  I didn't notice your message.  That's exactly what I do.  I'm interested in knowing where you are pulling the store and client from.  react-apollo exposes a withApollo box which does the above so you might not have to use your withProvider.

**Comment by perrosnk** [comment]
@sqow  @smooJitter 
How do you handle client changes? For example in my case, the user establishes a websocket connection at the beginning of the app without a token, and after login, I need to update the connectionParameters to include the token or include it in the Authorization header. I have made a question here :https://stackoverflow.com/questions/46992147/updating-authorization-header-in-websocket-graphql
but I haven't received any reply.
Could you please help me? 
Thank you anyway for you help so far.

**Comment by sqow** [comment]
@smooJitter Unfortunately, I wasn't able to use the `react-apollo` `withProvider` given the nature of my store & setup, but I would definitely encourage anyone who can use it to use that instead of the simplistic recreation I posted here

**Comment by sqow** [comment]
@perrosnk http://dev.apollodata.com/react/auth.html#Header You'll probably want to add a middleware for your `networkInterface` that uses `AsyncStorage` (probably) instead of `localStorage`. You can then update whatever that key is with your `token` received via logging in.

**Comment by perrosnk** [comment]
@sqow From what I understand the middleware runs only once when using websockets, and at the beginning of the app there is no token stored. The user gets the token after he logs in, so I then need to update either the header or the `connectionParemeters` as stated here: http://dev.apollodata.com/react/subscriptions.html#authentication

**Comment by sqow** [comment]
@perrosnk Unless your GraphQL queries are going over via websocket instead of HTTP, the middleware sends the Authorization header on every request.

If you are using websocket instead of HTTP for your GraphQL queries, then you're probably better off asking over in https://github.com/apollographql/react-apollo/.

**Comment by perrosnk** [comment]
@sqow I need to run some subscriptions that's why I need to use websockets. From what I understand I need to close the previous connection and start a new one with the token included. But in that case I need to update the client and pass it down to all screens by using your example code, right?

**Comment by perrosnk** [comment]
Fortunately I think I found a solution based on this comment: https://github.com/apollographql/subscriptions-transport-ws/issues/171#issuecomment-307793837
I am basically creating a single client with the ability to close and restart the connection, so I don't need to pass a new client to the Component.
@sqow I used your solution, but I noticed that the `static methods` I use in the Components to style the navigator and add buttons are not working. Do you experience the same behavior or am I doing something else wrong? Thanks again for sharing this code, it really helped me

**Comment by sqow** [comment]
@perrosnk I don't use those methods personally, so I haven't run into that issue. You can try using http://dev.apollodata.com/react/higher-order-components.html#withApollo or https://git.io/vFm6n (the full method signature of `registerComponent`) to modify what I've put up to create something that works for your use case, however.

Best of luck.

**Comment by jakelacey2012** [comment]
This doesn't work for me I get the error `client` cannot be found in context.

**Comment by jakelacey2012** [comment]
So I fixed my issue by doing this
```javascript
export const Provider = ({ children }) => (
  <ApolloProvider client={client}>
    { children }
  </ApolloProvider>
);
```
and when registering the components doing this.
```javascript
Navigation.registerComponent('screen.thingy', () => ThingyWithData, null, Provider);
```

**Comment by jakelacey2012** [comment]
For me I had to do this to get it working correctly
` Navigation.registerComponent(name, () => component, store, ApolloProvider, { client });  `

sadly had to add redux to get it to work though.

**Comment by perrosnk** [comment]
Has anyone managed to use mobx with apollo?

**Comment by perrosnk** [comment]
If anyone wants to find a way to make Mobx, Apollo 2 and RNN work together here is the solution:
https://github.com/kanzitelli/react-native-navigation-mobx-boilerplate/issues/3

**Comment by franciscocgoncalves** [comment]
Thanks for the tip @jakelacey2012. I managed to avoid using redux by registering the component with the client's internal store tho.

```
Navigation.registerComponent(name, () => component, client.store, ApolloProvider, { client });

```

**Comment by ujwal-setlur** [comment]
There seems to be a bug in react-apollo that fails to pass down the store prop. Please see:

https://github.com/apollographql/react-apollo/issues/1360

My current workaround is:

```
import { ApolloProvider } from "react-apollo";
import { Provider } from "react-redux";


const withProvider = (Component, store, client) => {
  return class extends React.Component {
    render() {
      return (
        <ApolloProvider client={client}>
          <Provider store={store}>
            <Component {...this.props} />
          </Provider>
        </ApolloProvider>
        );
    }
  };
};

Navigation.registerComponent("login", () => withProvider(Login, store, client));
```

**Comment by pqkluan** [comment]
@ujwal-setlur You don't have to Wrap the root screen with Redux `Provider` because `registerComponent` will do that for you if you pass the second params.

And `apollo-client` v2 drop the support to Redux. So you have to use the v1, by integrating the apollo reducer with your exists reducer.

**Comment by sreuter** [comment]
Further iterating on @sqow's example, let me show you how to pass through the navigatorButtons your component might have :)

```
const withProvider = (Component, store, Provider, ApolloProvider, client) => {
  return class extends React.Component {
    static navigatorButtons = Component.navigatorButtons

    render () {
      return (
        <Provider store={store}>
          <ApolloProvider client={client}>
            <Component {...this.props} />
          </ApolloProvider>
        </Provider>
      )
    }
  }
}
```

**Comment by thielCole** [comment]
Hey guys, leaving this here because it will probably be useful for someone in the future. Following what @sreuter is saying, for v2 to pass options into the component (like header options) you will need to define them in your HOC. Example below for how I have my HOC and registerComponent setup in my index.js file.

```ts
const localClient = new ApolloClient({
  uri: <local url>
});

const withProvider = (Component, client = localClient) => {
  return class extends React.Component {
    static options = Component.options

    render () {
      return (
        <ApolloProvider client={client}>
          <Component {...this.props} />
        </ApolloProvider>
      )
    }
  }
}

Navigation.registerComponent(`com.myApp.App`, () => withProvider(App))
Navigation.registerComponent(`com.myApp.Login`, () => withProvider(LoginPage))
```

**Comment by immortalx** [comment]
@thielCole @sreuter  Thank you.
This should work on V1 as well.
I believe this should be in the docs, it's not easy to find this information for someone starting with this library.

**Comment by sandeepbalouria** [comment]
Hi @thielCole 
I was hoping if you help me with proper setup for RNN2 and ApolloProvider
Here is what I am doing 
1. Index.js 

`Navigation.events().registerAppLaunchedListener(()` => pushLoginScreen());

2. ```const withProvider = (Component) => {
    return class extends React.Component {
        static options = Component.options

        render() {
            return (
                <ApolloProvider client={client}>
                    <Rehydrated>
                        <Component {...this.props}/>
                    </Rehydrated>
                </ApolloProvider>
            );
        }
    };
};


3. Registering all screens
```
export const registerScreens =  () => {
    Navigation.registerComponent(LOGIN_SCREEN, () => withProvider(LoginScreen));
    Navigation.registerComponent(USER_PROFILE_SCREEN, () => withProvider(UserProfileScreen));
    Navigation.registerComponent(ACCOUNT_SETTINGS_SCREEN, () => withProvider(AccountSettingsScreen));
    Navigation.registerComponent(HOME_SCREEN, () => withProvider(HomeScreen));
    console.log("All Screens have been registered");
};
registerScreens();
```

3. From LoginScreen I am navigating to a tab view with 3 tabs (HOME,USER_PROFILE,ACCOUNT_SETTINGS) using 

Navigation.setRoot( <bottom tabs with three children)

I can see  contents for account settings tab but other tabs  say 

Loading...


Thanks in advance.
