### ISSUE TITLE
'statusBarHidden' not work under SideBar menu Screen

### ISSUE THREAD

**Issue by leotu** [wix/react-native-navigation#189]
I want to hide status bar for side bar screens, but it don't work.
But "&lt;StatusBar hidden={true} /&gt; " will hidden always that I just want it disappeared only under drawer's control screens.

---

export default class Menu extends Component {
  ..
  static navigatorStyle = {
    statusBarHideWithNavBar: true,
    statusBarHidden: true,
  };
  ...

---

Navigation.registerComponent('sidebar.Menu', () => Menu);

---

drawer: {
        left: {
          screen: 'sidebar.Menu',
        },
       type: 'MMDrawer',
       animationType: 'slide',
      },

**Comment by guyca** [comment]
@leotu what platform?

**Comment by leotu** [comment]
iOS

**Comment by joemckie** [comment]
@guyca is there any further info on this? I'm at a bit of a blocker with this myself - and the status bar seems to lose its original props when opening the drawer (it turns from light to dark).

**Comment by indivisable** [comment]
Anyone figure this out yet? I am trying to manually reset the StatusBar style but cannot seem to find callback events for when sidebar is open/closed.

**Comment by heysailor** [comment]
If it helps at all, if a screen that has the statusbar hidden triggers the side drawer, the statusbar appears, and will disappear on closing the drawer.

**Comment by matthiasdilger** [comment]
ran into the same issue, a fix would be greatly appreciated

**Comment by jordanbrown** [comment]
Has anyone figured out a fix for this?

**Comment by aschenkel** [comment]
In  **v1** this [temporary workaround](https://github.com/wix/react-native-navigation/issues/754#issue-206966080) does it
