### ISSUE TITLE
Android lightbox - styling inconsistencies

### ISSUE THREAD

**Issue by kyle-ssg** [wix/react-native-navigation#1890]
### Issue Description

```
    "react-native":"0.48.3",
    "react-native-navigation": "1.1.228"
```
*Let me know if you want me to put up a replication app for this*

There are several implementation differences I've found that keep catching me out when developing android lightboxes:

1 - On Android, the root element of a lightbox screen needs a background color in order to render properly

<img src="https://image.prntscr.com/image/QvcQ6xMzRd6vXn_K4MgBgQ.png" height="300"/>
<img src="https://image.prntscr.com/image/0nsMIlcoRWGkM9sSPkwFYw.png" height="300"/>

2 - On android, I have to have a full screen root element justifying/aligning content to the center in order to achieve the above (which breaks the idea of tap to dismiss), iOS however doesn't require a container. 

3 - On android, the root element doesn't adjust its size if the content changes:
<img src="https://image.prntscr.com/image/0cO6VmtNQgWp-wr4XcmoHQ.png" height="200"/>
where as on iOS we get
<img src="https://image.prntscr.com/image/n15GpmziRm2YfuN4UvjpDg.png" height="200"/>

**Comment by fokoz** [comment]
@kyle-ssg Do you have to set width and height of  `lightBox` content ?

My issue occurs about 50% of time(Only android), `lightBox ` appears correctly, sometimes it appears without content (like it was clipped or cannot read content height)

**Comment by kyle-ssg** [comment]
Yeah I do, are you rendering stuff asynchronously by any chance?

Regardless, the following is what I do, which works for me across both platforms : 

**Launching**
```
navigator.showLightBox({
    screen: "/save-reply", // unique ID registered with Navigation.registerScreen
    passProps: {reply, campaign},

    style: {
        width: DeviceWidth,
        height: DeviceHeight,
        justifyContent: 'center',
        backgroundBlur: "light", // 'dark' / 'light' / 'xlight' / 'none' - the type of blur on the background
    },
    adjustSoftInput: "resize", // android only, adjust soft input, modes: 'nothing', 'pan', 'resize', 'unspecified' (optional, default 'unspecified')
})
```

**Component**
```
	<KeyboardAvoidingView keyboardVerticalOffset={64} style={{flex: 1}} behavior="padding">
		<View style={styles.lightboxOuter}>
			<View style={styles.lightbox}>

			</View>
		</View>
	</KeyboardAvoidingView>

...
var styles = StyleSheet.create({
	lightboxOuter: {
		backgroundColor: 'transparent',
		justifyContent: 'center',
		alignItems: 'center',
		paddingBottom: 40,
		paddingTop: 40,
	},

	lightbox: {
		paddingTop: 40,
		width: DeviceWidth - 40,
		borderRadius: 5,
		backgroundColor: 'white'
	}
})
```

**Comment by fokoz** [comment]
@kyle-ssg Nope, It just static text, no async at all.

**Comment by fokoz** [comment]
@kyle-ssg Update My issue occurs only on Production mode, it is fine on Debug mode. Really weird.

**Comment by kibot914** [comment]
Facing the same issue here, can anybody fix it ?

**Comment by brunolemos** [comment]
Any way to get the lightbox blur effect on Android like it does on iOS?
