### ISSUE TITLE
Get Intent(data) from Intent.ACTION_SEND/Intent.ACTION_SEND_MULTIPLE

### ISSUE THREAD

**Issue by michaelspeed** [wix/react-native-navigation#1891]
how to get the intent data from intent.ACTION_SEND / intent.ACTION_SEND_MULTIPLE,
and then receive it as props in app.android.js? 
i am experimenting with it a lot still cannot figure it out?

is it to pass 

`@Override
    public void startActivity(Intent intent) {
        super.startActivity(intent);
    }`

or in the onCreate() with - 
`@Override
            public void onNewIntent(Intent intent) {
                super.onNewIntent(intent);
            }`

it would be a big if anyone can provide a small snippet, THANKS
### Environment
* React Native Navigation version: 1.1.113
* React Native version: 0.46.1
* Platform(s) (iOS, Android, or both?): ANDROID
* Device info (Simulator/Device? OS version? Debug/Release?): DEVICE/ > 5.0

**Comment by njho** [comment]
Did you find a solution for this?
