### ISSUE TITLE
softInputMode : adjutPAN push the navBar

### ISSUE THREAD

**Issue by Chamal0f** [wix/react-native-navigation#1892]
I changed the soft input mode to adjustPan but the navBar get pushed out of the screen. Is there a way to prevent that ? 

some screen :

![screen3](https://user-images.githubusercontent.com/24553455/30588283-6a370574-9d36-11e7-9838-5184bb5ad8b5.png)
![screen 2](https://user-images.githubusercontent.com/24553455/30588289-707ea2de-9d36-11e7-8148-23a5962324b9.png)
![screen 1](https://user-images.githubusercontent.com/24553455/30588293-72ae825e-9d36-11e7-83b6-f0303bf71e3c.png)

---
### Environment
* React Native Navigation version: 1.1.205
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):Device / Debug

**Comment by moonjava2005** [comment]
Actually, "adjustPan" means "move" your screen up on Android. There's no way to do that. Why not try "resizeMode"
