### ISSUE TITLE
some bug with custom nav bar

### ISSUE THREAD

**Issue by TranThanh96** [wix/react-native-navigation#1893]
guys, i use some code to add nav bar. but it looks like has something on the left, i dont know why. this is my code: <hi>
this code add navbar, use component TabHeader
**componentDidMount() {
    this.props.navigator.setStyle({
      navBarCustomView: 'TabHeader',
      navBarHeight: 90,
      navBarBackgroundColor: '#34223',
      navBarComponentAlignment: 'fill',
    });
  }**
and this code to create component TabHeader:
**# render() {
    return (
      <View style={{ width: '100%', height: 90, flexDirection: 'row', alignItems: 'flex-start', backgroundColor: '#fff' }} >
        <TouchableOpacity style={{ width: '15%', alignItems: 'flex-start' }} onPress={this.props.openSideMenu} >
          <Image
            style={{ width: 25, height: 25, marginTop: 32 }}
            source={require('../images/Menu.png')}
          />
        </TouchableOpacity>
        <TouchableOpacity onPress={() => this.props.changeContent('go Link')} style={{ width: this.props.showLinkButtonImage ? '35%' : '70%', height: '100%', alignItems: 'center', backgroundColor: '#ff0000' }} >
          <Image
            source={require('../images/HistoryOrder.png')}
            style={{ width: 75, height: 75, marginTop: 7 }}
          />
        </TouchableOpacity>
        {this.props.showLinkButtonImage && <TouchableOpacity onPress={() => this.props.changeContent('go Helio')} style={{ width: '35%', alignItems: 'center' }} >
          <Image
            source={require('../images/Order.png')}
            style={{ width: 75, height: 75, marginTop: 7 }}
          />
        </TouchableOpacity>}
        <View style={{ width: '15%' }} />
      </View >
    );
  }**

![image](https://user-images.githubusercontent.com/26323599/30602121-daf1b1a4-9d8d-11e7-9628-cf7797756de0.png)
 anyone can help me?

**Comment by moonjava2005** [comment]
"navBarCustomView" not replace entire Navigation Bar View. It just apply the content in Navigation Bar view, on different device, the margin is different. Try to make your Customize View background is transparent and use the background color of Navigation Bar
