### ISSUE TITLE
Android release crash

### ISSUE THREAD

**Issue by xll503721** [wix/react-native-navigation#1897]
### Issue Description

I follow https://facebook.github.io/react-native/docs/signed-apk-android.html to setp up android release, but when I tap app, crash, and the error show:

Application scallions has not been registered.
                                                              
      Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
        If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').
                                                              
                                                              This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.

this code run on android simulator well. I have no idea.

my app.js code:

 import React, { Component } from 'react';
 import {
  AppRegistry,
  StyleSheet,
  Text,
  View
 } from 'react-native';

 import { Navigation } from 'react-native-navigation'

 import My from './My/my.js'
 import CreateOrder from './Order/create-order.js'
 import OrderList from './Order/order-list.js'
 import CreateOrderDetail from './Order/create-order-detail.js'
 import MyOrderList from './My/my-order-list.js'
 import BecomeStep1 from './My/Become/become-step1.js'
 import BecomeStep2 from './My/Become/become-step2.js'
 import BecomeStep3 from './My/Become/become-step3.js'
import Wallet from './My/wallet.js'
import MyDetail from './My/my-detail.js'

import iconsPath from './Common/icons.js'

Navigation.registerComponent('My', () => My)
Navigation.registerComponent('Order', () => Order)
Navigation.registerComponent('CreateOrder', () => CreateOrder)
Navigation.registerComponent('MyOrderList', () => MyOrderList)
Navigation.registerComponent('OrderList', () => OrderList)
Navigation.registerComponent('BecomeStep1', () => BecomeStep1)
Navigation.registerComponent('BecomeStep2', () => BecomeStep2)
Navigation.registerComponent('BecomeStep3', () => BecomeStep3)
Navigation.registerComponent('Wallet', () => Wallet)
Navigation.registerComponent('CreateOrderDetail', () => CreateOrderDetail)
Navigation.registerComponent('MyDetail', () => MyDetail)

export default class App extends Component {
    constructor(props) {
        super(props)

        this.initNavigation()
    }

    async initNavigation() {
        let icons = await iconsPath()

        Navigation.startTabBasedApp({
            tabs: [
              {
                label: '1111',
                screen: 'OrderList',
                title: '1111',
                icon: icons.recent,
              },
              {
                label: '111',
                screen: 'CreateOrder',
                title: '111',
                icon: icons.recent,
              },
              {
                label: '111',
                screen: 'My', // this is a registered name for a screen
                title: '1111',
                icon: icons.keyboard
              }
            ]
          });
    }
}

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "scallions";
    }
}

public class MainApplication extends NavigationApplication {
  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  @Nullable
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new WeChatPackage(),
            new VectorIconsPackage(),
            new NavigationReactPackage()
    );
  }

}

**Comment by witalobenicio** [comment]
You may have ran your app from react-packager that was already running for another app.
Try to close all of your terminal windows (it will kills your react packager). Then run the command again.

**Comment by lxooxl** [comment]
```
public class MainActivity extends SplashActivity {
    ...
}
```
maybe you forgot this;
