### ISSUE TITLE
custom position of light box

### ISSUE THREAD

**Issue by TranThanh96** [wix/react-native-navigation#1898]
guys, how can i custom position of light box??  on android, default center on screen. How we can controll this position?? i just want to put it on bottom

**Comment by moonjava2005** [comment]
Let the lightbox transparent and control your view inside the lightbox

**Comment by xuzb** [comment]
I put the view with style {position: 'absolute', bottom: 0}, but it does not work. Can you give more details? @moonjava2005

**Comment by stokesbga** [comment]
@moonjava2005 meant to wrap the content of the lightbox in a view that takes up the full screen, and then your content will have a position: 'absolute' bottom: 0
