### ISSUE TITLE
Root view push tabbed view (Android)

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#19]
I'm looking to implement a structure where the root view consists of a list and upon selecting an item a tab based view is pushed. Will this be possible/supported in Android? I'm planning to make a PR for react-native-controllers to implement this for iOS. 

EDIT: I think I might be able to achieve this by switching root with a suitable animation.

**Comment by guyca** [comment]
You can call `Navigation.startSingleScreenApp` to display the screen with the ListVIew. When a list view item is clicked, you can use `this.props.navigator.push` to display a screen over that list (clicking back button will go back to the list screen). In the screen you've just pushed, maybe you can use a project like [https://github.com/brentvatne/react-native-scrollable-tab-view](react-native-scrollable-tab-view) to show tabs?

**Comment by adamski** [comment]
Yes - that is a route I had considered, which will work well unless I need to have a separate ViewController / ScreenStack for one or more of the tabs. I think I will do it this way for now. https://github.com/alinz/react-native-tabbar looks like a good RN tab solution.

**Comment by guyca** [comment]
Nice. Please let me know if you encounter any issues with this approach
