### ISSUE TITLE
It is possible only to change screen's title without change tab item's title automatically ?

### ISSUE THREAD

**Issue by leotu** [wix/react-native-navigation#190]
## Here is my code:

Navigation.startTabBasedApp({
  tabs: [
    {
      label: 'MyLabel',
      screen: 'my.Demo',
      title: 'MyTitle',
    },
    ...
## In 'my.Demo' screen if change the title will also change tabbar item's 'label'

 this.props.navigator.setTitle({
  title: "MyTitle2"
});   

then label will become "MyTitle2" too.

**Comment by adamski** [comment]
Is this related to https://github.com/wix/react-native-navigation/issues/113?

**Comment by guyca** [comment]
@adamski Yes. This will be fixed soon 👍
