### ISSUE TITLE
resetTo breaks pushed screens "swipe back" gesture on iOS (Not tested on Android yet) 

### ISSUE THREAD

**Issue by hmenzagh** [wix/react-native-navigation#1907]
Hi, 

I navigate with a drawer of mine using navigator.push except when I go back to the HomePage, in that case I do a navigator.resetTo
When I navigate everything goes fine, i can swipe back etc. But when I resetTo the HomePage and push my other pages again I can't swipe back.

Here's the code : 
`
if (item.route == 'HomePage') {
    this.props.navigator.resetTo({ screen: 'app.HomePage' })
}
else {
    this.props.navigator.push({ screen: 'app.' + item.route })
}`

Any idea ?

**Comment by aemdy** [comment]
Same issue here as well!

**Comment by drpiou** [comment]
same issue here...
