### ISSUE TITLE
Pop or Back breaks tabs switching animations on Android

### ISSUE THREAD

**Issue by ywongweb** [wix/react-native-navigation#1909]
### Issue Description

Example repo link below.  

In the example repo I have a `tab view component` and a `button` that push a new screen on click. The animation on switching tabs works fine on the first load. But if we push the new scene and go back to the first. None of the animation will work.  

I've tried a few different react native tabs libraries. All have the same problem. 

### Steps to Reproduce / Code Snippets / Screenshots

https://github.com/ywongweb/RnnTextiInputBug

1. Run repo on Android device or Simulator
2. Change tabs -> can see animation
3. Click on button to push new scene, then click back to go back to first scene
4. Change tabs -> no animation

---
### Environment
* React Native Navigation version: tried 1.1.190, 1.1.200, 1.1.218
* React Native version: 0.46.4 and 0.48.3
* Platform(s) (iOS, Android, or both?): Android only, **works on iOS**
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by pqkluan** [comment]
I see you are using `react-native-tab-view` tab component.

```jsx
//... other imports
import { TabViewPagerPan } from 'react-native-tab-view';

class TabDisplay extends React.Component {

    render(){
        return (
            <TabViewAnimated
                //... other props
                renderPager={this.renderPager}
            />
        );
    }

    renderPager(props) {
        return <TabViewPagerPan {...props} />;
    }
}
```

**Comment by ywongweb** [comment]
@pqkluan Thank you so much!
