### ISSUE TITLE
Example from repo does not work on Android

### ISSUE THREAD

**Issue by fasibio** [wix/react-native-navigation#1911]
### Issue Description

Hello, 
I have clone the repo change to folder example
npm install
npm run android
Got error undefined is not an object 
NativeReactModule.startApp
in startApp
platformSpecific.android.js:10:20

### Environment
* React Native Navigation version: The current react-native-navigation example Version
* React Native version: The current react-native-navigation example Version
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 6P Android 8.0.0

**Comment by anwarhamr** [comment]
I just cloned the repo and can't get either android or ios to run the example programs.  Really tough to see how to use this library with any detail without some examples.  Additionally, the examples readme only mentions how to use IOS and well it doesn't work.  I'm getting `RCTxxxView.h` not found.  Tried looking how to fix this and there is a long string of people going back and forth w/o a resolution.
Please help.
