### ISSUE TITLE
iphone x tab bar compatibility

### ISSUE THREAD

**Issue by eladgel** [wix/react-native-navigation#1912]
### Issue Description

Tab Bar Hight is very high on iPhone X what can we do to fix this?

### Steps to Reproduce / Code Snippets / Screenshots
![image](https://user-images.githubusercontent.com/412137/30733760-0c601c7c-9f81-11e7-8314-c263f504df83.png)

---
### Environment
* React Native Navigation version: 1.1.205
* React Native version:  0.46.4
* Platform(s): iOS
* Device info Simulator iOS 11 Debug

**Comment by kyledmellander** [comment]
Also worth noting: the status bar is quite different on the iPhone X. Hiding the nav bar/status bar have different effects when compared to traditional IOS design.

**Comment by claaslange** [comment]
Judging by this promo shot from Apple's [iPhone X page](https://www.apple.com/iphone-x/) it looks correct to me.
![screenshot 2017-09-26 09 45 59](https://user-images.githubusercontent.com/42106/30848478-875487da-a29f-11e7-9873-757fec83c9f8.png)

**Comment by eladgel** [comment]
@claaslange interesting

**Comment by 9SumeetMourya** [comment]
@eladgel : Just check the guidelines for iPhoneX here.  
[https://developer.apple.com/ios/update-apps-for-iphone-x/](url)

**Comment by M-Jas** [comment]
We are having some issues with the tab bar also. I know we need to setup the SafeArea, but the tabs look way off.  @eladgel did your tabs look like this at all? Any help on this would be great!

<img width="385" alt="screen shot 2017-11-17 at 10 12 07 am" src="https://user-images.githubusercontent.com/13804811/32954073-0fa6ec5a-cb80-11e7-8733-d98410c9794c.png">

**Comment by claaslange** [comment]
Looks like your app isn't optimized for the iPhone X, so you get the black bars on top and bottom but the app is respecting the safe area nevertheless.

**Comment by M-Jas** [comment]
@claaslange we do still needed to setup the SafeArea to remove the black bars, so I'll try that now. Do you think the tabs are stretched because of that? 
Side note: We do have a iPhone x image in place.

**Comment by thechefchen** [comment]
I have the same scenario with you. The tab bar has a black background below. Do you have a solution yet? I'm curious how and why the splash screen would solve this problem?

**Comment by thechefchen** [comment]
Updates, it works! I mentioned the step to make it work here:

https://github.com/wix/react-native-navigation/issues/2113
