### ISSUE TITLE
compatibility with react-native-fcm

### ISSUE THREAD

**Issue by Chamal0f** [wix/react-native-navigation#1915]
### Issue Description

I can't manage to make react-native-navigation work with react-native-fcm. I created a new react-native project, then I installed fcm and react-native-navigation, everything work fine  until I send a notification.

basically I got this error when the device receive a notification ( app in foreground ) .
it works well in background.
 
![21919469_10155578517408070_107600698_n](https://user-images.githubusercontent.com/24553455/30754888-cdcc7c64-9fc4-11e7-80f9-9b2722735a94.png)

### Steps to Reproduce / Code Snippets / Screenshots

screen.js

```

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import FCM, {FCMEvent, RemoteNotificationResult, WillPresentNotificationResult, NotificationType} from 'react-native-fcm';

export default class AwesomeProject extends Component {
  componentDidMount(){
    FCM.requestPermissions();
    FCM.getInitialNotification().then(notif => console.log(notif))
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

```

app.js

```
import { Navigation } from 'react-native-navigation';
import screen from './screen/screen';





  Navigation.registerComponent('screen', () => screen);
  Navigation.startSingleScreenApp({
  screen: {
    screen: 'screen',
    title:'screen',
    navigatorStyle: {
      drawUnderNavBar: true,
      navBarTranslucent: true,
      navBarHidden: true,

    }, // override the navigator style for the screen, see "Styling the navigator" below (optional)

  },
  appStyle: {
    orientation: 'portrait',
  },
  animationType: 'fade'
})

```

index.android.js

```

import app from './app/app';

```
---
### Environment
* React Native Navigation version: 1.1.228
* React Native version: 0.48.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device / Debug-Release

**Comment by Nitroman605** [comment]
Yeah Same problem here . Did you found a Solution ? This problem really destroying my progress .

**Comment by insidelabs** [comment]
We're seeing similar behavior as well. It seems to be isolated to android specifically.

**Comment by Nitroman605** [comment]
@insidelabs what if we used the push notification lib by wix will that solve the problem ? Maybe more compatible ? .

I also noticed that it tries to call index.js which is correct starting point of the new react native projects , but in wix navigation it still uses index.android.js as a starting point So maybe that's part of the issue .

**Comment by insidelabs** [comment]
@Nitroman605 

We're looking at using the wix notification lib as well.

wix has a write up specifically about integrating react native notifications with RNN, which I'm assuming has something to do with why FCM won't work either.

https://github.com/wix/react-native-notifications/wiki/Android:-working-with-RNN

> Why was this needed? Raw React-Native projects assume a single activity. react-native-navigation inherently allows for multiple activities, thus making the activities lifecycle process an issue of importance. It consequently provides a lifecycle management API of its own your project needs to integrate to.(url)

**Comment by Nitroman605** [comment]
@insidelabs 

Just a heads up . I tried the react-native-notification by wix and failed to make it work correctly ( notification not arriving on the phone ) . So I tried react-native-firebase and it works perfectly and much better than others since it's well documented and updated to work with the latest FCM plus having the extra features of Firebase if you want them .

Hope this will helps you .

**Comment by insidelabs** [comment]
Did it work correctly with react-native-navigation installed as well? You can receive a notification with the app open, click through and have it deep link properly? Even with react-native-firebase we are having the issue where clicking a notification relaunches the activity.

**Comment by Nitroman605** [comment]
> Did it work correctly with react-native-navigation installed as well?

Yes so far .

> You can receive a notification with the app open

You can you receive it by listening to (onMessage) handler `firebase.messageing().onMessage( (message) => {  do something }` .When you get a notification while app is open and in the page where you fired the onMessage , your handle will intercept it and then you can maybe show a local notification in case you want to show it to the user .

>  click through and have it deep link properly?

I am not using deep link for my app , so clicking on notification will start the app or brings it to the foreground which is fine by me .

**Comment by Reiji87** [comment]
Right before starting of app, we added this line in.
```
 if (NativeReactModule === undefined && Platform.OS === 'android') {
      return;
}
```

**Comment by hoorsa** [comment]
@insidelabs 
I'm using `react-native-navigation`  and `react-native-firebase` in my project.

> Did it work correctly with react-native-navigation installed as well?

YES.

> You can receive a notification with the app open?

YES.

> click through and have it deep link properly?

**NO**

**Comment by RuairiOliver** [comment]
It works apart from the initial notification used to launch the app.
FCM.getInitialNotification() returns undefined.

Has anyone managed to fix this?

**Comment by RuairiOliver** [comment]
Got initial notification working by changing this line in AppDelegate.m

from: 
[[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation];

to:

[[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions];

And then handling the initial notification before doing anything else in the application
