### ISSUE TITLE
how to hide space or override space after hidding tabbar?

### ISSUE THREAD

**Issue by TranThanh96** [wix/react-native-navigation#1917]
guys, i need helps.
before hidding tabbar: 
![before](https://user-images.githubusercontent.com/26323599/30770916-a5c62678-a066-11e7-8721-80d8f3cf29aa.jpg)

after hidding tabbar:
![after](https://user-images.githubusercontent.com/26323599/30770917-aec762f0-a066-11e7-939b-8564897e81c7.jpg)

this screen after hide tabbar has some space on positon of tabbar. how can i hide this? or override this?

**Comment by moonjava2005** [comment]
Apply "drawUnderTabBar:true" in navigatorStyle of screen
