### ISSUE TITLE
[question] How to pass more than one provider?

### ISSUE THREAD

**Issue by azgron** [wix/react-native-navigation#1920]
I'm using the react-native-material-ui library with redux.
react-native-material-ui requires it's own provider. It seems on regular router like this:

```
     <Provider store={store}>
         <ThemeProvider uiTheme={uiTheme}>
           <Router scenes={Scenes} />
        </ThemeProvider> 
      </Provider>
```
How should i pass it to  Navigation.registerComponent?
Is there any way to combine providers?

**Comment by alimek** [comment]
Hi @azgron ,

You must create your wrapper. Here you have my example for `redux`'s `Provider` and `styled-components` theme. 

My `Provider.js` file:
```js
import { Provider } from 'react-redux';
import { ThemeProvider } from 'styled-components';
import theme from './theme';

const Provider = ({ store, children }) => (
  <Provider store={store}>
    <ThemeProvider theme={theme}>
      {children}
    </ThemeProvider>
  </Provider>
);

export default Provider;
```

and then use it when register screens:

`registerScreens.js`:
```js
import { Navigation } from 'react-native-navigation';

export default (store, Provider) => {
  Navigation.registerComponent('UNIQUE_ID', () => YourComponent, store, Provider);
}
```

and how it register it in `index.js`
```js
import Provider from './provider';
import store from './store';
...
registerScreens(store, Provider);
...
```

Hope it helps ;)

**Comment by azgron** [comment]
@alimek Thank you!

**Comment by hemraj-s** [comment]
Doesn't seem to be working for me. Have used the following code.

Provider.js is as follows

`import Provider from 'react-redux';
import React from 'react'
import darkBaseTheme from 'material-ui/styles/baseThemes/darkBaseTheme';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import getMuiTheme from 'material-ui/styles/getMuiTheme';

const myProvider = ({ store, children }) => (
  <Provider store={store}>
    <MuiThemeProvider muiTheme={getMuiTheme(darkBaseTheme)}>
      {children}
    </MuiThemeProvider>
  </Provider>
);

export default myProvider;`

Code in app.android.js
`import React from 'react'; // eslint-disable-line
import myProvider from './provider';
import { Navigation } from 'react-native-navigation';

import { registerScreens } from './screens';
import configureStore from './store/store';

const store = configureStore();

registerScreens(store, myProvider);
`
I get an error as follows

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got undefined. You likely forgot to export your component from the file it is defined in.

**Comment by Balamir** [comment]
It doesn't work with react-native-navigation **1.1.382**

**Comment by trialsNow** [comment]
@alimek 

I am using react-native-elements. Would the themeprovider automatically handle colors of react-native-navigation (v2) bottom and top bars? I tried it and it didnt work.
I would like paint the whole app with a primary color that comes from my server. Can you suggest me some easy ways that would fit well with RNN V2?
