### ISSUE TITLE
Three-dot menu button not clickable on some Android phones when using large font size

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#1921]
### Issue Description

This is only for Android. I have a tab screen that has three navigation bar buttons. None of them have `showAsAction` set which should default to `ifRoom` value. On some Android phones, when using large text, the app displays 2 of the navigation bar buttons and a three-dot menu as shown below

![whatsapp image 2017-09-23 at 6 01 05 pm](https://user-images.githubusercontent.com/7475133/30778835-13b56662-a0fd-11e7-8f94-66f298e3db38.jpeg)

This is a bit weird because there is space to show three buttons and there are in fact just three buttons. When I click on the three-dot menu button, it is not clickable. If I set the font size to normal, I see below screen

![whatsapp image 2017-09-23 at 6 00 53 pm](https://user-images.githubusercontent.com/7475133/30778852-793210da-a0fd-11e7-9cff-b2a897ca6ea3.jpeg)

As you can see, there are just three button in the navigation bar. So, RNN should have just displayed the settings icon when large font is selected. Nevertheless, the three-dot menu should be clickable.

I was able to reproduce this issue on a [Samsung Galarm J2](http://www.gsmarena.com/samsung_galaxy_j2-7357.php) phone but I was not able to run the app on debug mode on this phone and I was not able to reproduce this issue on any simulator to check if there are any error logs printed by RNN on the console.

I am not sure if there is enough information to debug this issue but this is affecting my users.

### Steps to Reproduce / Code Snippets / Screenshots

Screenshots attached above. I was not able to reproduce this on all the phones. Till now, just on the Samsung Galaxy J2 phone and other users who reported this error were also using a Samsung phone. On that phone, I see the font size to largest and open the app and observe this issue.

---
### Environment
* React Native Navigation version: 1.1.203
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Release

**Comment by guyca** [comment]
Hey @varungupta85 
Does the third button (the one which is, supposedly, displayed in the menu) have a `title` property?

**Comment by varungupta85** [comment]
hi @guyca,

Yes, it does. It is set to `Search` to allow showing a helper text on long click. The `title` is not important for me and I can remove it. Does that have something to do with the issue?

**Comment by varungupta85** [comment]
I removed the `title` from the settings button and still see the same issue.

**Comment by guyca** [comment]
This is the first time I'm hearing of this issue, can you please add here the `rightButtons` object your using? I'll try to look into it (although I'm taking a ~two week vacation now so it might be after I return)

**Comment by varungupta85** [comment]
Below is the `rightButtons` object that I am using

```javascript
rightButtons = [
      {
        icon: require('../../img/ic_settings.png'),
        id: 'settings',
        title: I18n.t('settings')
      },
      {
        icon: require('../../img/ic_filter.png'),
        id: 'filterAlarms',
        title: I18n.t('filterAlarms')
      },
      {
        icon: require('../../img/ic_find.png'),
        id: 'search',
        title: I18n.t('search')
      }
    ]
```

**Comment by varungupta85** [comment]
@guyca If you give me some hints about where I can start investigating it, I can also take a look at it.

**Comment by xvonabur** [comment]
I faced this behaviour too, but for two buttons. The right one is non-clickable three-dot menu. Both of them have titles. Here is the interesting part: you see this strange three-dot menu button if the characters sum of all right buttons on the screen is more than 30 chars. For example: 

```js
rightButtons = [
      {
        icon: require('../../img/ic_settings.png'),
        id: 'settings',
        title: 'Very long title here'
      },
      {
        icon: require('../../img/ic_filter.png'),
        id: 'filterAlarms',
        title: 'Another very long title here'
      }
    ]
```
It will give you  three-dot menu.

But this one renders fine: 

```js
rightButtons = [
      {
        icon: require('../../img/ic_settings.png'),
        id: 'settings',
        title: 'Title 1'
      },
      {
        icon: require('../../img/ic_filter.png'),
        id: 'filterAlarms',
        title: 'Title 2'
      }
    ]
```

Android only, last release build of react-native-navigation (1.1.270)

**Comment by varungupta85** [comment]
@xvonabur Thanks for sharing that the three-dot menu appears when the sum of characters in title is greater than some number. That was a shrewd observation. It led me to think that probably RNN is trying to compute if it can fit the buttons in the action bar using a mixture of icons and titles and when the titles are long enough, it thinks that it won't be able to show all of them and end up showing the three-dot menu but since I am not showing titles in the action bar, the handlers are not attached properly.

@guyca I guess this is something that the RNN library should take care of but not a very urgent issue as I was able to easily get around it by removing titles for all the buttons in the action bar in my case. Previously I tried to remove the title from just the settings button and I guess the remaining titles were still longer than what can be accommodated in the action bar but after removing all the titles, it works as expected.

**Comment by mdAlvarenga** [comment]
@guyca Hi, I want to see if they could see this, because I had the same problem and we didn't find a solution. I try to use the solution they gave to limit the number of characters in the combination id + title, but it didn't work. It happens to me on any android phone that changes the source to the maximum. Thanks for your time

**Comment by xvonabur** [comment]
@guyca any news about this issue?
