### ISSUE TITLE
popTo functionality

### ISSUE THREAD

**Issue by ugendrang** [wix/react-native-navigation#1922]
Is it possible to achieve the functionality popTo(screenName)? 

For example Navigation stack will be:
A -> B -> C -> D

And I want to pop to screen B from screen D as like popTo('D')
D-> B -> A

**Comment by Jlexyc** [comment]
Need "replaceStack" also as
an also A -> B-> C -> D
And After show A -> B-> C

**Comment by kitchenSpoon** [comment]
Just wondering if anyone found a work around for this issue?

**Comment by hernancorigliano** [comment]
This actually is so usefull. There should be a way to manage the stack, all the options are you either resetTo a screen or you popToRoot. We need something in the middle to edit the stack of screens.

**Comment by guyca** [comment]
Implemented in v2
