### ISSUE TITLE
Multidex

### ISSUE THREAD

**Issue by andfk** [wix/react-native-navigation#1925]
Hi! Im having issues to add Multidex. With the following added:
```
android {
    defaultConfig {
        ...
        minSdkVersion 19 
        targetSdkVersion 22
        multiDexEnabled true
        dexOptions {
            javaMaxHeapSize "8g"
        }
    }
    ...
}

dependencies {
  compile 'com.android.support:multidex:1.0.1'
}
```
The 3 possible ways to do it fails by:
- No possible to replace `android:name="` as it needs `android:name=".MainApplication"`.
- No possible to `public class MyApplication extends MultiDexApplication` because `MainApplication` must extend `NavigationApplication`. (`public class MainApplication extends NavigationApplication`)
- Doing
```
import android.support.multidex.MultiDex;
import android.content.Context;
public class MainApplication extends NavigationApplication {
  @Override
  protected void attachBaseContext(Context base) {
     super.attachBaseContext(context);
     Multidex.install(this);
  }
}
```

Returns an error on build for `error: cannot find symbol variable Multidex`.

Did anyone implemented Multidex successfully with RN-Navigation?? im totally stuck with this.

**Comment by ywongweb** [comment]
Try
```
super.attachBaseContext(base); 
```

**Comment by andfk** [comment]
@ywongweb many thanks for the suggestion! in my code i have the same, even ‘super.attachBaseContext(base)’ too, not like the example but the issue is about Multidex symbol not available even when is imported in the top. Did you got Multidex working?

**Comment by ywongweb** [comment]
Do you have a capital D in MultiDex?

**Comment by andfk** [comment]
Omg man... I feel **** now. Yes, you are totally right!! I was copy-pasting the code from android docs that has a lowercase d and not D... what a simple mistake. 

Really lot of thanks @ywongweb.

**Comment by ShaMan123** [comment]
This should be written in the installation guide.
Absolutely agonizing installing this repo and getting it to run on android.
