### ISSUE TITLE
NavBar flickers upon modal opening

### ISSUE THREAD

**Issue by eladgel** [wix/react-native-navigation#1926]
### Issue Description

NavBar flickers upon modal opening

### Steps to Reproduce / Code Snippets / Screenshots
 run this code piece
```

Navigation.showModal({
            screen: 'some.screen',
            navigatorStyle: {
                navBarTranslucent: true, // make the nav bar semi-translucent, works best with drawUnderNavBar:true
                navBarTransparent: true, // make the nav bar transparent, works best with drawUnderNavBar:true,
                navBarNoBorder: true, // hide the navigation bar bottom border (hair line). Default false
                drawUnderNavBar: true,
            }
        }); 

```

in the render method of the screen you show write

``` 
render(){
  return <View style={{flex:1, backgroundColor:'red'}}/>
} 
```

---
### Environment
React Native Navigation version: 1.1.205
React Native version: 0.46.4
Platform(s): iOS
Device info Simulator iOS 11 Debug, iPhone also

**Comment by OverVlad** [comment]
Have some problem, any ideas how to solve this issue? For my help disable animation fro modal (animationType: 'none')
