### ISSUE TITLE
Header margins

### ISSUE THREAD

**Issue by jaredramirez** [wix/react-native-navigation#1927]
### Issue Description

When I create a header with a custom component , there is a margin on the left of the header with android, and on both sides with iOS.

### Steps to Reproduce / Code Snippets / Screenshots

Navbar.js:
```
// @flow
import React, {Component} from 'react';
import {StyleSheet, View, Image} from 'react-native';

import {logo, getWidthPercent, getHeightPercent} from '../constants';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: getHeightPercent(20),
    backgroundColor: 'red',
  },
  logo: {
    width: getWidthPercent(8),
    zIndex: 100, // arbitrarily high zindex
  },
});

export default () => (
  <View style={styles.container}>
    <Image source={logo} style={styles.logo} resizeMode="contain" />
  </View>
);
```

Routes.js
```
import {COMPONENTS} from './constants';
import Navbar from './components/Navbar';
...
export const registerScreens = () => {
  ...
  // components
  Navigation.registerComponent(COMPONENTS.NAVBAR, () => Navbar);
};
```

Screen:
```
import {COMPONENTS} from '../../../constants';

class RoutesAll extends React.Component {
  static navigatorStyle = {
    navBarNoBorder: true,
    navBarButtonColor: COLORS.blue, // sets colors for all buttons on navbar
    navBarCustomView: COMPONENTS.NAVBAR,

    // android
    topBarElevationShadowEnabled: false,
  };
  ...
}
```

### Result
android:
![screen shot 2017-09-25 at 12 07 16 pm](https://user-images.githubusercontent.com/8095741/30821185-182113d4-a1ea-11e7-96dd-cbaf48edebdd.png)
As you can see, there is a margin to the left of the header.

iOS:
![screen shot 2017-09-25 at 12 10 21 pm](https://user-images.githubusercontent.com/8095741/30821321-8fa5887c-a1ea-11e7-95f1-c9a19d10dd54.png)
As you can see, there is a margin on both sides of the header

---
### Environment
* React Native Navigation version: 1.1.228
* React Native version: 0.48.3
* Platform(s) (iOS, Android, or both?): Android/iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Genymotion/iOS, Debug

**Comment by aminroosta** [comment]
Add this to you component:

```js
  static navigatorButtons = {
    leftButtons: [ ],
    rightButtons: [ ],
  };
```

**Comment by aminroosta** [comment]
@jaredramirez Found a workaround ...
Open `views/TitleBar.java` and change the constructor to this:

```java
    public TitleBar(Context context) {
        super(context);
        super.setContentInsetStartWithNavigation(0);
        super.setContentInsetEndWithActions(0);
        super.setContentInsetsAbsolute(0,0);
    }

```

**Comment by aminroosta** [comment]
@guyca Could you please remove the `ContentInset` when there is no LeftButtons and rightButtons are present? Or when `navBarComponentAlignment` is `fill`?

**Comment by jaredramirez** [comment]
That fixed my issue on android!

**Comment by mguariero** [comment]
I'm having the same problem, both in IOS and Android. Is there a quick fix for now? For both platforms?

**Comment by Fuhrmann** [comment]
Same problem here. I`m trying to use a navBarCustomView with a custom component but there is this margin in both sides.

**Comment by karlmosenbacher** [comment]
+1

**Comment by danielang** [comment]
+1

**Comment by karlmosenbacher** [comment]
Any updates on this?

**Comment by liorchen** [comment]
+1

**Comment by Nickersoft** [comment]
Doesn't this fix the issue on iOS at least?

https://github.com/wix/react-native-navigation/pull/2306

**Comment by Hari70a** [comment]
@Nickersoft upgrading to `1.1.407` fixes the issue on iOS but still persists on Android. Workaround suggested by @aminroosta seems to work on Android, wondering if this can be / was merged in.

Thanks :)

**Comment by alandmonte** [comment]
where can I find Titlebar.java ?

**Comment by aminroosta** [comment]
@alandmonte I don't remember, do a `find . | grep Titlebar.java` in your `node_modules` folder, it's somewhere in the `node_modules/react-native-navigation` folder

**Comment by rheng001** [comment]
I'm experienced the same issue on android. Is changing the node_modules the only fix to this?

**Comment by rgazeredo** [comment]
+1

**Comment by guyca** [comment]
This issue is addressed in v2.
As the horizontal margins can't be worked around, you can declare two separate components: one for the background which stretches as expected without margins, and another for the "title" (content):

```js
topBar: {
    title: {
      component: {
        name: 'example.CustomTopBarTitle',
        alignment: 'center'
      }
    },
    background: {
      component: {
        name: 'example.CustomTopBarBackground'
      }
    }
  }
```

I'm closing the issue as v1 is not maintained anymore. You can easily migrate your codebase to v2 with a single line of code using the [adapter library](https://github.com/wix-playground/react-native-navigation-v1-v2-adapter)

**Comment by padupuy** [comment]
the @aminroosta solution works perfectly for V1.

I prefere to use a patch, here is my workaround

1. Create a file with the name "header.patch" at the root of your application or create a folder with the name "patch" with this content : 
```
--- node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/views/TitleBar.java	1970-01-01 01:00:00.000000000 +0100
+++ TitleBar2.java	2018-06-21 09:10:37.000000000 +0200
@@ -33,6 +33,9 @@

     public TitleBar(Context context) {
         super(context);
+        super.setContentInsetStartWithNavigation(0);
+        super.setContentInsetEndWithActions(0);
+        super.setContentInsetsAbsolute(0,0);
     }

     @Override

```

2.  Go to your package.json and add a **postinstall** hook to your "scripts" : 
if you put the patch file at root"postinstall": "patch -p0 < header.patch || true",
if you put the patch file inside the patch "postinstall": "patch -p0 < patch/header.patch || true"
```
    "scripts": {
        "start": "node node_modules/react-native/local-cli/cli.js start",
        "postinstall": "patch -p0 < patch/header.patch || true"
    },
```

3. Save all and open your terminal in the same path. Run "npm run postinstall" or "yarn postinstall"
Done.

The patch has been created from the commande line from [this solution](https://github.com/wix/react-native-navigation/issues/1927#issuecomment-332453071)  :
```
diff -u node_modules/apollo-client/bundle.umd.js bundle.umd.js> apollo.patch
```
