### ISSUE TITLE
rightButtons on Android attempt to set key "enabled" on an immutable/frozen object

### ISSUE THREAD

**Issue by sqow** [wix/react-native-navigation#1928]
### Issue Description

Attempting to set `rightButtons` on the `navigatorButtons` object of the `screen` object within, at least, a `startSingleScreenApp` call on Android (6.0.1+)  results in the following error:

```
You attempted to set the key `enabled` with the value `true` on an object that is meant to be immutable and has been frozen.
```

### Steps to Reproduce / Code Snippets / Screenshots

```js
const navigatorStyle = 

Navigation.startSingleScreenApp({
  screen: {
    screen: 'com.example.MyScreen',
    navigatorStyle: {
      statusBarColor: '#831d19',
      navigationBarColor: '#339999',
      navBarBackgroundColor: '#339999',
      navBarTextColor: '#ffffff',
      navBarButtonColor: '#ffffff',
      statusBarTextColorScheme: 'light',
      navBarHidden: false,
      tabBarButtonColor: 'red',
      tabBarSelectedButtonColor: 'red',
      tabBarBackgroundColor: 'red'
    },
    navigatorButtons: {
      rightButtons: [
        {
          id: 'sideMenu'
        }
      ]
    }
  },
  drawer: {
    right: {
      screen: 'com.example.Drawer'
    }
  }
})
```

This relates to [this line](https://github.com/wix/react-native-navigation/blob/master/src/deprecated/platformSpecificDeprecated.android.js#L524) being used in the array of `rightButtons` (plural), while the [left button (singular) block](https://github.com/wix/react-native-navigation/blob/master/src/deprecated/platformSpecificDeprecated.android.js#L537-L548) has no comparable setting of an `enabled` property.

---
### Environment
* React Native Navigation version: 1.1.228
* React Native version: 0.47.0
* Platform(s) (iOS, Android, or both?): Android, not tested on iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung Galaxy S6 running 6.0.1, debug

**Comment by HoogsterInc** [comment]
I have this too. Works on iOS but not android

**Comment by tschoffelen** [comment]
This seems pretty major, but doesn't seem to get much attention. I'm facing the same issue, any solutions found yet?

**Comment by cqlanus** [comment]
I'm experiencing this, as well. The error cites [this line](https://github.com/wix/react-native-navigation/blob/master/src/deprecated/platformSpecificDeprecated.android.js#L565) as an issue

**Comment by HoogsterInc** [comment]
I am also having this problem. Has anyone tried it on a production build? Mine starts with "console.error: ..." which makes me hopeful that it won't translate to production but I'm a noob and have no idea

**Comment by adrienthiery** [comment]
Same problem here.

It leads to [that line](https://github.com/wix/react-native-navigation/blob/c82f28afa4df89230ed14ae62bf57905493f4bb8/src/deprecated/platformSpecificDeprecated.android.js#L383)

**Comment by adrienthiery** [comment]
By avoiding to mutate the buttons and just clone them before returning, it fixes the issue.

I'll keep that in for now ('cause I'm a bit short on time).

Let me know if it helps!

**Comment by lchavezpozo** [comment]
don't working :(

**Comment by adrienthiery** [comment]
@gabrielvcbessa : The error was coming from the line 597 : https://github.com/wix/react-native-navigation/pull/3032/files#diff-4879ab6a334567fa35803da3231ab404L597 ` button.enabled = !button.disabled;`

On the 2nd iteration, the `button` object seems to be immutable, and we try to modify it by setting the `enabled` property. So instead of modifying it, I create a copy/clone and return that instead.

**Comment by TylerR909** [comment]
I was running into a lot of code reuse throughout my application with several components having near-identical `onNavigatorEvent`s, `navigatorButtons`, and `navigatorStyle`s. I made a base class containing those 3 things and exported a function to wrap my screens with this base class. 

```
// ComponentWrapper.js
export default function componentWrapper(componentToWrap) {
  class BaseNavigatorScreen extends Component {
    constructor(props) {
        super(props);
        this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
    }
    static propTypes = {
        navigator: PropTypes.object
    }
    
    static navigatorButtons = { ... }

    static navigatorStyle = { ... }
    
    onNavigatorEvent(event) {
        if (event.type === 'navbarButtonPress') {
            if (event.id === 'screen2') {
                this.props.navigator.push({ screen: 'Screen2', title: 'Screen2'}); // <-- This is throwing the error
            }
            if (event.id === 'mainscreen') {
                this.props.navigator.push({ screen: 'MainScreen', title: 'MainScreen'}); // <-- This is throwing the error
            }
        }
    }

    render() { return <ComponentToWrap {...this.props} {...this.state} /> }
  }
}
```
And then I have 
```
// MainScreen.js - MainScreen defined
export default componentWrapper(MainScreen);
```
and
```
// Screen2.js - Screen2 defined
export default componentWrapper(Screen2);
```

Now if I start clicking on the navigatorButtons to go back and forth between the screens, as people have already noted, the 2nd time I click a button this error gets thrown. In my code I threw a try/catch around the wrapper's `navigator.push` and that's where I'm catching the error. If you'll forgive my syntax here, my workflow is something like `MainScreen.click('Screen2') -> Screen2.click('MainScreen') -> MainScreen.click('Screen2') ERROR`. It looks like `MainScreen.click('Screen2') -> Back -> MainScreen.click('Screen2') ERROR` is also failing, so... It just really hates that second click when Composition is involved. 

This method of minimizing code reuse was very close to working. I had it hooked up on a couple screens  with the navigatorButtons, styling, and navButton Functionality working great before it started throwing errors. I'm wondering if there's something creative I can do with this-binding and the `ComponentToWrap` parameter, like assigning an `onNavigatorEvent` function to it and then messing with this-binding, but none of that has panned out successfully.

**Comment by adrienthiery** [comment]
@guyca @yogevbd are you still considering issues and PRs for v1 or aee you focusing on v2 ?

**Comment by gabrielvcbessa** [comment]
@adrienharnay In the main page there is the following warning:

> Since we're focusing our efforts on v2, we are not accepting pull requests for v1 and are not addresing issues for v1.

**Comment by adrienthiery** [comment]
Oups 😅
