### ISSUE TITLE
How to I listen to react-native-onesignal event on all views?

### ISSUE THREAD

**Issue by jarvisluong** [wix/react-native-navigation#1934]
### Issue Description

I'm using react-native-onesignal to do push notification on my app. I want to add a feature that when use tap the notification to go to the app, my app can take the payload of the notification and then push the corresponding view to the stack that the user can see it. My app is a log in based app so when the user is not logged in, Navigation.startSingleScreenApp is used and when they logged in, a tab app is used.
I can't find a way to listen to onesignal event through all the app, not just a single screen. Is there any way that I can implement it?

**Comment by unexge** [comment]
you can listen OneSignal events in your main file(the file you imported from your index.*.js). and then you can call `Navigation.handleDeepLink` to navigate proper screens.

**Comment by jarvisluong** [comment]
I have fìgured one way myself: In the function that I used to initialize the app, I add the eventListener of onesignal there, and then put the payload to a redux state and whatever view need to react to that payload, I inject the payload with `connect()`

**Comment by KManiKumarReddy** [comment]
Can you elaborate your solution an little. Putting the payload in redux is fine, but how to push the appropriate screen to the user upon current context?

**Comment by pacozaa** [comment]
@jarvisluong Would you mind sharing more about your solution? I would like to see snippet of your code.

**Comment by jarvisluong** [comment]
Hi! Unfortunately I'm not working at that project using this solution anymore so I can't access the code. However, the basic idea is that you need to listen to OneSignal's event and then pass it to redux using ```store.dispatch```. At the top component of each screen that you want to listen to the event, you need to watch the reducer's properties that keeps the OneSignal's payload, maybe using componentDidUpdate or something similar.
