### ISSUE TITLE
Allow adding a Callback on Swipe Back Event

### ISSUE THREAD

**Issue by MrLoh** [wix/react-native-navigation#1937]
It seems like there is no way to hook into the swiping back gesture on iPhone. I am handling the button presses manually, so that is easy, but I need to track the state of the app separately as well. It would be great if I could listen for swipe backs and android back presses in the `onNavigatorEvent`.

**Comment by alimek** [comment]
+1, any idea how for make it for now ?

**Comment by MrLoh** [comment]
I'm using a callback on the `screenDidAppear` event. I'm also keeping track of the stacks by hand in my redux store, so I can check, wether the appeared screen is the previous screen in the current stack. 

Code looks something like that (this should give an idea of how it works)

```js
const onScreenAppeared = (payload, state) => {
		const activeStack = selectActiveStack(state);
		if (
			activeStack.length > 1 &&
			payload !== activeStack[0].key &&
			payload === activeStack[1].key
		) {
			dispatch(goingBack);
		}
	}
```

**Comment by alimek** [comment]
@MrLoh hmm good idea with storing stack and then checking 👍 

thanks for solution
