### ISSUE TITLE
Android app stuck on splash screen after first time back from background

### ISSUE THREAD

**Issue by mobitar** [wix/react-native-navigation#1938]
I'm surprised this one hasn't been reported, as it was so easy to replicate while also a pretty bad bug. I created a blank project to replicate this (and was able to do so), but then realized I could just use your example app to the same effect.

I simply ran your example app via `react-native run-android`, waited for the app to launch successfully, put the app in background by pressing the home button, then re-opened the app via the launcher. Upon launch, the screen is white (which is the default color of the splash screen). The only two ways to get rid of this screen are to:

1. Press the hardware back button, which removes the white screen and launches the app
2. Kill the app from multitasking, then re-launch it. Afterwards, the white screen issue will not appear anymore, even after subsequent fresh launches.

This issue only appears on new installs. I thought it was a debug issue, but I distributed an app through Google Play and this issue appears on first run after the user backgrounds the app for the first time.

For the record, I also created a new non-RNN project, and this issue _does not_ occur. It's strictly an RNN issue.

#### Environment
* React Native Navigation version: 1.1.231
* React Native version: 0.45.1 
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Any device / Tested on Android 7.0

**Comment by mobitar** [comment]
It looks like the issue has something to do with RNN/SplashActivity.java creating splashScreens every time the app opens up.

Change `createSplashLayout` to set a random color for the splash screen:

```
    /**
     * @return the layout you would like to show while react's js context loads
     */
    public View createSplashLayout() {
        Random rnd = new Random();
        int color = Color.argb(255, rnd.nextInt(256), rnd.nextInt(256), rnd.nextInt(256));
        View view = new View(this);
        view.setBackgroundColor(color);
        return view;
    }
```

Then, on new app install, the initial splash screen is color A. After putting the app in the background then re-opening, a new splash screen color B appears and stays on. Put the app in background again and re-open it, a new color C appears. Press hardware back, then color B appears. Press hardware back again, color A appears, back again, then finally app appears.

**Comment by mobitar** [comment]
After deeper investigation, `NavigationActivity.currentActivity` seems to be null when launching the app from background after new install.

In `SplashActivity.java`, in the `onResume` method, `NavigationActivity.currentActivity` is null when this issue occurs.

So the only solution I could come up with was to relaunch the NavigationActivity in the `onResume` function of SplashAcitvity if the app enters this state:

```
if(NavigationActivity.currentActivity == null && NavigationCommandsHandler.didPreviouslyLaunch) {
    NavigationCommandsHandler.startApp(null);
}
```

Then in NavigationCommandsHandler, I create two new static variables:

```
private static Bundle savedParams;
public static Boolean didPreviouslyLaunch = false;
```

Then in the `startApp` function, I add to the top:

```
didPreviouslyLaunch = true;
if(params != null) {
    savedParams = params;
} else {
    params = savedParams;
}
```

This seems to remedy the issue.

Again, this only happens on new installs, or via `react-native run-android`. This issue does not happen if you build and run directly from Android Studio. Also still very surprised no one has reported this issue.

**Comment by sytolk** [comment]
This fix this issue for me:
https://github.com/wix/react-native-navigation/pull/1900

**Comment by mobitar** [comment]
Wow, that does indeed fix it. Thanks @sytolk! So glad I don't have to use my hacky fix 😅

**Comment by filipef101** [comment]
@guyca Why is this not merged in master? the #1900

**Comment by LingboTang** [comment]
I'm still having this issue.

**Comment by NextVictim** [comment]
@mobitar your hack fix work fine.

**Comment by AmirTahani** [comment]
in my case, I was navigating the app by watching rehydrate action like this :
`export function* watchRehydrate(store) {
    const state = store.getState();
    if (state && state.auth && state.auth.jwt) {
        put(setJwt(state.auth.jwt));
        NavigationService.navigate('Profile', {
            lang: state.auth.lang
        });
    } else {
        NavigationService.navigate('Auth');
    }
}`
now when the app launches it checks that if there is a logged-in user it navigates to "Profile" otherwise navigates to "Auth" 
if the app is closed with hardware back press and then relaunch it stucks on white screen page because rehydrate is not dispatched and you cant navigate in Saga watcher. so I have to move the same logic to App.js componenDidMount. it solves the relaunching issue but in new launch, componentDidMount happens before redux-persist rehydrate so `store.getState();` returns initialState and it always navigates to "Auth". 

so you need to make sure this is not the first (new) launch.
rehydrate Module: 
`const initialState = {
    isRehydrated: false
};

export default function (state = initialState, action = {}) {
    switch (action.type) {
        case REHYDRATE_SUCCESS:
            return {
                ...state,
                isRehydrated: true
            };
        default:
            return state;
    }
}

export function rehydrateSuccess() {
    return {
        type: REHYDRATE_SUCCESS
    };
}

export function* watchRehydrate(store) {
    const state = store.getState();
    if (state && state.auth && state.auth.lang) {
        yield put(changeLang(state.auth.lang));
    }
    if (state && state.auth && state.auth.jwt) {
        yield put(setJwt(state.auth.jwt));
        NavigationService.navigate('Profile', {
            lang: state.auth.lang
        });
    } else {
        NavigationService.navigate('Auth');
    }
    yield put(rehydrateSuccess());
}`

and inside App.js 
`const state = store.getState();
        if (state.rehydrate.isRehydrated) {
            if (state && state.auth && state.auth.lang) {
                store.dispatch(changeLang(state.auth.lang));
            }
            if (state && state.auth && state.auth.jwt) {
                store.dispatch(setJwt(state.auth.jwt));
                NavigationService.navigate('Profile', {
                    lang: state.auth.lang
                });
            } else {
                NavigationService.navigate('Auth');
            }
        }`

**Comment by j-schuster** [comment]
Still having this issue. Anyone found a recent workaround maybe lately?
