### ISSUE TITLE
Swipe to pop()? [QUESTION]

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#194]
Is it possible to swipe to pop a screen (go back)?

**Comment by guyca** [comment]
Hey @perrosnk 
Not sure about iOS, but when you push a screen on Android, the previous screen is removed from the hierarchy to conserve memory. So you can detect swipe in JS witch out actually animating the screen then call `navigator.pop` and it will work. But if you change the screens coordinates, then the previous screen won't be behind it and it will look weird.
Hope I answered your question.
