### ISSUE TITLE
Nav bar always appear in screen of very last tab

### ISSUE THREAD

**Issue by Reiji87** [wix/react-native-navigation#1949]
### Issue Description

I implemented a tab based app with 4 tabs. Im trying to hide the navigation bar. I used the following code for all the screens in the 4 tabs

this.props.navigator.setStyle({ navBarHidden: true }); 
and
this.props.navigator.toggleNavBar({
  to: 'hidden', // required, 'hidden' = hide navigation bar, 'shown' = show navigation bar
  animated: true // does the toggle have transition animation or does it happen immediately (optional). By default animated: true
});

But it always seems like the navbar of the very last screen in the tab will always show on Android.

---
### Environment
* React Native Navigation version: 1.1.228
* React Native version: 0.47.0
* Platform(s) (iOS, Android, or both?):Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by Reiji87** [comment]
Did a workaround to fix this issue,I put the function inside 
ComponentWillMount() function for the screen then it will work. Don't put the function inside the constructor

**Comment by Reiji87** [comment]
How my app is structured.
<img width="475" alt="screen shot 2017-10-02 at 7 45 26 am" src="https://user-images.githubusercontent.com/8175305/31060403-b543a090-a745-11e7-8acd-f9e962b0a133.png">

I added 
this.props.navigator.setStyle({ navBarHidden: true });
For all my screens for the tab

**Comment by gongmingqm10** [comment]
+1. I also encounter this problem. Could anyone update the solution?

**Comment by isaachinman** [comment]
Is this `setStyle` function still part of the API? It doesn't seem like it is - how do we achieve a hidden navbar?
