### ISSUE TITLE
[Android] How to install with react-native-gesture-handler?

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#1950]
As you can see I have to edit `MainActivity.java` https://github.com/kmagiera/react-native-gesture-handler#installation
The problem is that I don't have `getMainComponentName` function because Wix makes you edit the file like so:
```java
 import com.reactnativenavigation.controllers.SplashActivity;

 public class MainActivity extends SplashActivity {

 }
```

But we should add this to `MainActivity.java`

```java
// Don't forget imports
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

class MainActivity extends ReactActivity {

  // Add the following method to your main activity class
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
        return new RNGestureHandlerEnabledRootView(MainActivity.this);
      }
    };
  }
}
```

Do you guys have any idea?

**Comment by henrikra** [comment]
@guyca @gran33 @DanielZlotin @Cool04ek Can you guys check this out? It would make very much sense to get this library working with react-native-gesture-handler since both of them try to use native side of react native to make best apps! More info also here https://github.com/kmagiera/react-native-gesture-handler/issues/35

**Comment by ollydixon** [comment]
Also having the same issue, did you find a solution?

**Comment by henrikra** [comment]
Yeah check this https://github.com/kmagiera/react-native-gesture-handler/issues/35

**Comment by alpamys-qanybet** [comment]
@henrikra, what about RNN v1?

**Comment by kdawgwilk** [comment]
Are there any hooks in RNN v2 to allow you to attach the gesture handler to each activity that is created RNN v2?
