### ISSUE TITLE
[Android] Unable to close drawer by swiping

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#1951]
### Issue Description
When using `disableOpenGesture: true` the drawer can't be opened with gesture which works fine. But on Android you can't close is with swiping either. On iOS you can close drawer with swiping with `disableOpenGesture: true` so it works fine.

Have you guys noticed the same?

### Steps to Reproduce / Code Snippets / Screenshots
Add `disableOpenGesture: true` inside `drawer` config

### Environment
* React Native Navigation version: 1.1.231
* React Native version: 0.48.4
* Platform: Android
* Device info: Device

**Comment by riteshmalav** [comment]
I am also facing the same issue. Any resolution on this.

**Comment by henrikra** [comment]
We ended up implementing our own with this https://github.com/kmagiera/react-native-gesture-handler#drawerlayout-
