### ISSUE TITLE
space between tab buttons 

### ISSUE THREAD

**Issue by ghost** [wix/react-native-navigation#1953]
### Issue Description
when I add for example two tabs, there's no spacing between them, for a portrait screen four tabs is needed to make it look good, how can I manage the space between tabs when I have a few tabs that doesn't fit the Screen

---
### Environment
* React Native Navigation version: 1.1.229
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device , 6.0.1 , Debug

**Comment by erfanyousefifar** [comment]
something just popped in my mind, if I use a js component that represents a tab navigation but it's only a  touchable that uses switch to tab api from wix navigation, and hide the tabbar, will that give a good performance and lots of customizability??

**Comment by babara2** [comment]
I have a similar issue too! I cannot find anything in the documentation that would help with this problem. Does anyone have any insight?
