### ISSUE TITLE
Assert: Expect all root views to have unique tag. Added 1 twice

### ISSUE THREAD

**Issue by alexesDev** [wix/react-native-navigation#196]
After update react-native to 0.31 I have one assert in RCTUIManager.m
https://github.com/facebook/react-native/blob/master/React/Modules/RCTUIManager.m#L374
After comment this line -  all works fine.

That's my fault?

**Comment by guyca** [comment]
@alexesDev Navigation still doesn't support RN 0.31 officially. Internally we're still using RN 0.25.1

We'll upgrade from RN 0.25.1 later this month

**Comment by alexesDev** [comment]
@guyca I understood, thanks for the answer.

**Comment by DanielZlotin** [comment]
iOS now upgraded to RN31, Android coming soon.
