### ISSUE TITLE
startSingleScreenApp: undefined is not an object (evaluating 'RCCManager.setRootController')

### ISSUE THREAD

**Issue by spencewine** [wix/react-native-navigation#1960]
### Issue Description

Can not start the app using Navigation.startSingleScreenApp
I checked the iOS installation, and I've done everything it requested.

### Steps to Reproduce / Code Snippets / Screenshots
![screen shot 2017-10-03 at 2 18 56 pm](https://user-images.githubusercontent.com/1612742/31144261-d2c48e94-a845-11e7-82c6-023d2fd7a213.png)

index.ios.js

```
import React, { Component } from 'react';
import { Provider } from 'react-redux';
import configureStore from '~/Common/stores/store';
import RootContainer from './containers/RootContainer';
import { Navigation } from 'react-native-navigation';
import { registerScreens } from './screens';
const store = configureStore();

class App extends Component {
    constructor(props) {
        super(props);

        registerScreens(store, Provider);
        this.startApp();
    }

    startApp() {
        Navigation.startSingleScreenApp({
            screen: {
                screen        : 'native.Root',
                navigatorStyle: {
                  tabBarBackgroundColor    : '#003a66',
                  navBarButtonColor        : '#ffffff',
                  tabBarButtonColor        : '#ffffff',
                  navBarTextColor          : 'black',
                  tabBarSelectedButtonColor: '#ff505c',
                  navigationBarColor       : 'white',
                  navBarBackgroundColor    : 'white',
                  statusBarColor           : '#002b4c',
                  tabFontFamily            : 'BioRhyme-Bold',
                }
            }
        });
    }
}
export default App;
```

---
### Environment
* React Native Navigation version: 1.1.235
* React Native version: 48.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by iamameme** [comment]
Having the same issue. Here is my index.ios.js as well.

`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableHighlight,
  TouchableOpacity,
} from 'react-native'
import PropTypes from 'prop-types';
import * as Progress from 'react-native-progress';

import { Navigation } from 'react-native-navigation';

import { registerScreens } from './screens';

registerScreens();

Navigation.startTabBasedApp({
  tabs: [
    {
      label: 'One',
      screen: 'DrinkingApp.FirstTabScreen', // this is a registered name for a screen
      icon: require('./img/one.png'),
      selectedIcon: require('./img/one_selected.png'), // iOS only
      title: 'Screen One'
    },
    {
      label: 'Two',
      screen: 'DrinkingApp.SecondTabScreen',
      icon: require('./img/two.png'),
      selectedIcon: require('./img/two_selected.png'), // iOS only
      title: 'Screen Two'
    }
  ]
});
`

**Comment by pmlarocque** [comment]
You might be missing

```
// **********************************************
// *** DON'T MISS: THE NEXT LINE IS IMPORTANT ***
// **********************************************
#import "RCCManager.h"
```

In AppDelegate.m ?

Was the case for me.

**Comment by iamameme** [comment]
No dice sadly. This is my AppDelegate.m:
```
#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>

// **********************************************
// *** DON'T MISS: THE NEXT LINE IS IMPORTANT ***
// **********************************************
#import "RCCManager.h"

// IMPORTANT: if you're getting an Xcode error that RCCManager.h isn't found, you've probably ran "npm install"
// with npm ver 2. You'll need to "npm install" with npm 3 (see https://github.com/wix/react-native-navigation/issues/1)

#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;
#ifdef DEBUG
  //  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
#else
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
  
  
  // **********************************************
  // *** DON'T MISS: THIS IS HOW WE BOOTSTRAP *****
  // **********************************************
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  self.window.backgroundColor = [UIColor whiteColor];
  [[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions];
  
  /*
   // original RN bootstrap - remove this part
   RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
   moduleName:@"example"
   initialProperties:nil
   launchOptions:launchOptions];
   self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
   UIViewController *rootViewController = [UIViewController new];
   rootViewController.view = rootView;
   self.window.rootViewController = rootViewController;
   [self.window makeKeyAndVisible];
   */
  
  
  return YES;
}

@end

```

**Comment by iamameme** [comment]
Here is the rest of the setup for me as well. I've set the Header Search Path, imported the ReactNativeNavigation.xcodeproj, and linked it to my binaries.

![alt text](https://i.imgur.com/Mxo6WTq.png "Logo Title Text 1")
![alt text](https://i.imgur.com/huvUten.png "Logo Title Text 1")
![alt text](https://i.imgur.com/VaKDL3s.png "Logo Title Text 1")

**Comment by yusisi** [comment]
having the same issue

**Comment by amscher** [comment]
I'm seeing this issue when I try to run the example app as well...

**Comment by CliveTeow** [comment]
Same here.

**Comment by DiederikvandenB** [comment]
+1

**Comment by coderjonny** [comment]
might be React Native .48+ version issue [#2040](https://github.com/wix/react-native-navigation/issues/2040)

**Comment by Jordsan** [comment]
Any resolution on this?

**Comment by dulguuned** [comment]
i had same issue. But i opened ios project in xcode and cleaned build folder with cmd+shift+option+k command then it started working. I hope this helps someone.

**Comment by 1pocketaces1** [comment]
check your path in Header Search Paths, that was my issue

**Comment by bilalma** [comment]
I'm also facing this issue.Kindly share solution
