### ISSUE TITLE
TabBar navigation buttons accross tabs

### ISSUE THREAD

**Issue by werne2j** [wix/react-native-navigation#1962]
### Issue Description
Is it possible when creating a tab based application, to register a navigation button that exists across multiple tabs without having to register the same button for every tab?

### Steps to Reproduce / Code Snippets / Screenshots

```
    Navigation.startTabBasedApp({
      tabs: [
        {
          label: 'One',
          screen: 'screen.One',
          title: 'Screen One'
        },
        {
          label: 'Two',
          screen: 'screen.Two',
          title: 'Screen Two'
        },
        {
          label: 'Three',
          screen: 'screen.Three',
          title: 'Screen Three'
        },
        {
          label: 'Four',
          screen: 'screen.Four',
          title: 'Screen Four'
        },
        {
          label: 'Five',
          screen: 'screen.Five',
          title: 'Screen Five'
        }
      ]
    });
```

I am starting a TabBasedApp like so ^ and want to have a navigation button that is the same for everyone of my tabs without having to add this:
```
  static navigatorButtons = {
    rightButtons: [
      {
        title: 'Edit', // for a textual button, provide the button title (label)
        id: 'edit', // id for this button, given in onNavigatorEvent(event) to help understand which button
      },
    ]
  };
```
to each of my components

---
### Environment
* React Native Navigation version: 1.1.231
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/iPhone 6/iOS 10.3/Debug

**Comment by saxahan** [comment]
I've created a base screen component that applies: 

```
this.props.navigator.setButtons({
            leftButtons: [
                {}
            ],
            rightButtons: [
               {}
            ]
        });
```
And all my tabs screen extend it. Basically, I wrote nav bar buttons code once.

**Comment by werne2j** [comment]
@saxahan i had something similar, wasn't sure if there was a framework specific way to do it. I think i'm going to convert what i have to your suggestion. Thanks for the help!
