### ISSUE TITLE
Is having multicoloured PNG tab icons possible?

### ISSUE THREAD

**Issue by linnett** [wix/react-native-navigation#1965]
We are passing PNG icons into the `startTabBasedApp()` method. They are currently rendering with a single colour filled in though (bar transparency). 

Is there a way to prevent this happening so we can use custom icons with multiple colours or is this just the way it is? Thanks.

---
### Environment
* React Native Navigation version: 0.47.2
* React Native version: 16.0.0-alpha.12
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by gabrielbs** [comment]
@linnett Can you solve it? Same problem here

**Comment by linnett** [comment]
Unfortunately it doesn't appear to be a feature they support
