### ISSUE TITLE
Pop() from the first screen of a startSingleScreenApp

### ISSUE THREAD

**Issue by JeremDsgn** [wix/react-native-navigation#1969]
Hey!

I would like to know how to handle this flow.

I have 2 screens. When the user install the app for the first time he goes through screen A, submit a form and then I push to screen B.

At this point when the user launch the application again, he should be on screen B. Until a countdown is done or he removed it.

So at this point I have this

```js
export const startApp = (data) => {
  if (data) {
    ScreenB();
  } else {
    ScreenA();
  }
};

export const ScreenA = () =>
  Navigation.startSingleScreenApp({
    screen: {
      screen: SCREEN_A,
      navigatorStyle: { navBarHidden: true },
    },
  });

export const ScreenB = () =>
  Navigation.startSingleScreenApp({
    screen: {
      screen: SCREEN_B,
      navigatorStyle: { navBarHidden: true },
    },
  });
```

I'm checking with a store if the user should go to screen A or B. But if the user decide to cancel the counter on screen B, I would like to do a `pop()` to the screen A. But this this not possible since the screen A is not part of the stack. I tried to use a `resetTo()` or `push()` but the slide animation is in the wrong way.

How should I manage this?

---
### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.47.2

**Comment by jurajkrivda** [comment]
You should use Redux.

**Comment by JeremDsgn** [comment]
@jurajkrivda Can you be more descriptive? I'm using mobx actually.

**Comment by jurajkrivda** [comment]
Look at this example https://github.com/apparena/app-arena-native-app/blob/master/src/app.js

**Comment by JeremDsgn** [comment]
Not quite sure about this exemple. This is really the same I do on my example, just defining which screen should appear depending user preferences.

It doesn't affect the stack of screens to pop() on the previous one, even if it was only one screen at the beginning of the app, right?

![a4](https://user-images.githubusercontent.com/937328/32217877-37911d6a-be21-11e7-9a4d-759ddaf12938.png)
