### ISSUE TITLE
Draw undernav transparent header not transparent on modal at launch

### ISSUE THREAD

**Issue by alexwasner** [wix/react-native-navigation#1971]
### Issue Description
When displaying a modal with a transparent header, the header first assumes the `navBarBackgroundColor` until the transition is complete. Once it is complete, it then goes transparent which causes an ugly flicker

### Steps to Reproduce / Code Snippets / Screenshots
Here is an image with super awesome colors showing this in more detail:
![stepstoreproduceimage](https://user-images.githubusercontent.com/4612947/31199436-ecdf2190-a91c-11e7-88b5-20a716137ae9.png)

1. Set your `navigatorStyle` to include the following:
```
{
      navBarTranslucent: true,
      navBarTransparent: true,
      drawUnderNavBar:true,
      navBarBackgroundColor: 'red',
}
```
2. In iOS simulator, hit `CMD`+`T` to slow animations (to see it better)
3. Open a modal
4. Examine that the modal header is first red. When transition is complete, see that it goes transparent. showing the color of the item behind it

---
### Environment
* React Native Navigation version: "latest"
* React Native version: "^0.47.0"
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both device and simulator on iOS 11. Debug and release builds

**Comment by alexwasner** [comment]
Any thoughts on this?

**Comment by chrise86** [comment]
What I've done as a workaround is to set the navbar as hidden, then do the following:

```
componentDidMount() {
    setTimeout(() => {
      this.props.navigator.toggleNavBar({
        to: 'shown',
        animated: true
      })
    }, 500)
  }
```

Not the best, but at least you don't get that flicker.

**Comment by nimamyscreen** [comment]
any solution for this issue?

**Comment by brunolemos** [comment]
This issue is not unique to modals, it also happens if you use push:

![gif](https://user-images.githubusercontent.com/619186/34231294-a10e1090-e5c2-11e7-90e2-78194b0f6e5d.gif)

**Comment by veb** [comment]
Has anyone else come up with a better solution? This is a pretty shit bug.

**Comment by veb** [comment]
This turned out to be SUPER easy to fix: https://github.com/wix/react-native-navigation/blob/master/docs/styling-the-navigator.md#disabling-persistent-styling-properties-on-ios 

That's it. No more flickers. Nothing. Perfect.
