### ISSUE TITLE
Issue to install Wix Navigation on Android in RN ^0.49

### ISSUE THREAD

**Issue by donnes** [wix/react-native-navigation#1974]
### Issue Description

Firs of all I'd like to apologize because I don't have much experience with Java.
So I having a issue to run my app after try install Wix Navigation with the new RN release version (^0.49).

I think my problem is in the file `MainApplication.java`, because in RN 0.49 this file have a lot of changes.

### Steps to Reproduce / Code Snippets / Screenshots

![screenshot_1507209966](https://user-images.githubusercontent.com/9506146/31229889-8fe4e3f2-a9b8-11e7-86d8-7e1516f828f4.png)

`MainApplication.java`

```
package com.reactnativestarter;

import android.app.Application;
import android.support.annotation.NonNull;

import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.reactnativenavigation.NavigationApplication;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends NavigationApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }

  @Override
  public boolean isDebug() {
    // Make sure you are using BuildConfig from your own application
    return BuildConfig.DEBUG;
  }

  @NonNull
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return null;
  }
}

```

---
### Environment
* React Native Navigation version: ^1.1.235
* React Native version: 0.49.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by chanphillip** [comment]
Same issue here

**Comment by janpahkala** [comment]
You have lot of unneeded code in your MainApplication.java. Here's my NavigationApplication/setup:

    "react": "^16.0.0",
    "react-native": "0.49.1",

    (compileSdkVersion 26
    buildToolsVersion "26.0.2"
    minSdkVersion 23
    targetSdkVersion 26)

```
public class MainApplication extends NavigationApplication {

    @Override
    public boolean isDebug() {
        // Make sure you are using BuildConfig from your own application
        return BuildConfig.DEBUG;
    }

    protected List<ReactPackage> getPackages() {
        // Add additional packages you require here
        // No need to add RnnPackage and MainReactPackage
        return Arrays.<ReactPackage>asList(
                //if needed: new YourPackageHere() 
        );
    }

    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return getPackages();
    }
}
```

**Comment by safe-dog** [comment]
Just rename (copy) `index.js` to `index.android.js`

**Comment by donnes** [comment]
Thank you @safe-dog and @janpahkala yours answers fixed the issue.

**Comment by reyalpsirc** [comment]
If you want to already use a single `index.js` as it is recommended now for 0.49+, you can do it like this:

    import android.app.Application;
    import android.support.annotation.Nullable;

    import com.facebook.react.ReactApplication;
    import com.facebook.react.ReactNativeHost;
    import com.facebook.react.ReactPackage;
    import com.facebook.react.shell.MainReactPackage;
    import com.facebook.soloader.SoLoader;
    import com.reactnativenavigation.NavigationApplication;

    import java.util.Arrays;
    import java.util.List;

    public class MainApplication extends NavigationApplication {

      private final CustomRNHost mReactNativeHost = new CustomRNHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          return Arrays.<ReactPackage>asList(
              new MainReactPackage()
          );
        }

      };

      @Override
      public String getJSMainModuleName() {
        return "index";
      }
      
      @Override
      public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
      }

      @Override
      public boolean isDebug() {
        // Make sure you are using BuildConfig from your own application
        return BuildConfig.DEBUG;
      }

      @Override
      public List<ReactPackage> createAdditionalReactPackages() {
        return mReactNativeHost.getHostPackages();
      }

      @Override
      public void onCreate() {
        super.onCreate();
        SoLoader.init(this, /* native exopackage */ false);
      }

      protected abstract class CustomRNHost extends ReactNativeHost {

        protected CustomRNHost(Application application) {
          super(application);
        }

        public List<ReactPackage> getHostPackages() {
          return this.getPackages();
        }
      }
    }

**Comment by abhishek1214** [comment]
This is not working for me till now... Its not using rns server to request for files. It is looking for the bundles only.

**Comment by reyalpsirc** [comment]
@abhishek1214 did you set the `adb reverse tcp:8081 tcp:8081`?

If you run on device using wi-fi, please look on https://facebook.github.io/react-native/releases/0.21/docs/running-on-device-android.html

**Comment by Zephir77167** [comment]
Hey for people still running into this issue,, I updated the docs to explain the changes needed on ios and android: https://github.com/wix/react-native-navigation/pull/2412
