### ISSUE TITLE
How to back to single login screen from tab based app ?

### ISSUE THREAD

**Issue by xshadowlegendx** [wix/react-native-navigation#1979]
My app starting from loading a single screen app - login screen, it checks if auth is true, start tab based app, if not stay in the login screen. I want to do 2 thing, when auth is true but some error is occurred, kick back to login screen, when user logout, also kick back to login screen. I do this with triggering:

`this.props.navigator.popToRoot({ screen: 'app.Authentication' })`

and this:

`Navigation.startSingleScreenApp( SingleScreenApp )`;

It throws me an immutable error:
```
You attempted to set the key `navigatorID` with the value `"navigatorID28_nav"` on an object that is meant to be immutable and has been frozen.
```

**Comment by n1ru4l** [comment]
I am doing it like this (not related to your errors). I also noticed some weird issues with calling `Navigation.startSingleScreenApp` and `Navigation.startTabBasedApp` multiple times, like having two Tabbed screens over each other or a Tab screen over a SingleScreenApp.

The following approach seems to be the best to me:

1. Start app with `Navigation.startTabBasedApp`
2. Push login screen as modal: `Navigation.showModal`
3. Login finished? `Navigation.dismissAllModals`
3. After logout: `Navigation.showModal`
4. Goto 2

**Comment by xshadowlegendx** [comment]
@n1ru4l But I think following your approach does not seem like practical way to do it using modal ?

**Comment by n1ru4l** [comment]
@xshadowlegendx Yeah it is not the perfect way I guess, but it is the way with the minimal amount of issues for me 😅

**Comment by xshadowlegendx** [comment]
@n1ru4l hahaha I see 👍

**Comment by Soraph** [comment]
@n1ru4l How would you handle that with a tabBasedApp that has to navigate to a tab from an inAppNotification ?

The modal solution is great but I need to the navigator buttons and adding them has (ofc) no effect.

**Comment by xshadowlegendx** [comment]
Using redux subscribe to watch for user login changes and switching between single and tab based app only works in IOS but not android.
Basically login -> home -> logout -> login ( throw immutable error on Android, while working fine on IOS )
![screen shot 2017-10-22 at 11 36 20 pm](https://user-images.githubusercontent.com/21999889/31864086-f67114ac-b781-11e7-910e-61142ce19222.png)
![screen shot 2017-10-22 at 11 37 00 pm](https://user-images.githubusercontent.com/21999889/31864087-f9802444-b781-11e7-8bb5-7b5b1573b11e.png)

**Comment by xshadowlegendx** [comment]
In this condition, I was wondering if triggering app restart on android are consider best practice if i could not switch between those on Android ?

**Comment by n1ru4l** [comment]
Somehow I managed to get it working. I think that my issues were related to async code that triggered some stuff in components after they got unmounted by switching between navigation modes.

**Comment by xshadowlegendx** [comment]
@n1ru4l glad you solved your issues man. I am restarting the android app as workaround in my case.

**Comment by n1ru4l** [comment]
I only tested my app on ios

**Comment by bdrobinson** [comment]
I had this problem and found that it was due to a mistake on my part – for some reason I was passing the same object to `appStyle` and `tabsStyle`, even though they expect differently-structured objects:

```js
const TAB_STYLE = {
    tabBarSelectedButtonColor: "green",
    forceTitlesDisplay: true,
    tabBarHideShadow: true,
    tabBarBackgroundColor: "white",
    ...etc
}

Navigation.startTabBasedApp({
    ...
    appStyle: TAB_STYLE, // this is what broke it for me.
    tabsStyle: TAB_STYLE,
})
```

Strangely, if I replaced `appStyle: TAB_STYLE` with `appStyle: { ...TAB_STYLE }` the bug went away too, so I'm not entirely sure what was actually wrong – it feels like maybe the library is mutating the passed-in object or holding a reference to it for too long or something? I haven't looked into it any more than that.

**Comment by n1ru4l** [comment]
@bdrobinson thank you for that info 😊

**Comment by mattmarkham** [comment]
>The following approach seems to be the best to me:

1. Start app with Navigation.startTabBasedApp
2. Push login screen as modal: Navigation.showModal
3. Login finished? Navigation.dismissAllModals
4. Goto 2

@n1ru4l May I ask where you are calling Navigation.showModal? I'm having the problem of the modal being shown for a split second before the tab 0 is drawn, and then the modal is hidden by tab 0 afterwards.

class App extends Component {
  constructor(props) {
      super(props);

			this.startApp();
			this.showLogin();
	}

startApp() {
    Navigation.startTabBasedApp({
      tabs: [
        {
          label: 'Home',
          screen: 'app.ResellerHomeScreen',
					icon: require('../assets/images/home-icon.png'),
          title: 'Home',
					navigatorStyle2
        },
				{
          label: 'Store',
          screen: 'app.StoreScreen',
					icon: require('../assets/images/ic_shop.png'),
          title: 'Store',
					navigatorStyle2
        },
				{
          label: 'Orders',
          screen: 'app.StoreScreen',
					icon: require('../assets/images/ic_orders.png'),
          title: 'Orders',
					navigatorStyle2
        },
				{
          label: 'Lists',
          screen: 'app.StoreScreen',
					icon: require('../assets/images/list.png'),
          title: 'Lists',
					navigatorStyle2
        },
      ],
		tabsStyle: {
    tabBarBackgroundColor: 'black',
    tabBarButtonColor: 'white',
    tabBarSelectedButtonColor: 'blue',
  },
	appStyle: {
    keepStyleAcrossPush: false,
    navBarButtonColor: '#ffffff',
    navBarTextColor: '#ffffff',
    navigationBarColor: '#003a66',
    navBarBackgroundColor: 'black',
    statusBarColor: '#002b4c',
  },
});
  }
	showLogin() {
			Navigation.showModal({
				screen: 'app.LoginScreen',
				title: 'Login',
				animationType: 'slide-up'
			});
	}
}

**Comment by CliveTeow** [comment]
I have encountered an issue which the code within "class App extends Component {}" not getting called. Any idea?

**Comment by lusimail** [comment]
I got the same issue, but found the fix by chance. In short, I think you cannot pass the same object twice to the navigator.

Let's say you have this 2 variables:
```
const SingleScreenApp = { screen: 'app.HomeScreen' };
const TabApp = {
	tabs: [
		{ screen: 'app.Tab1' },
		{ screen: 'app.Tab2' },
		{ screen: 'app.Tab3' },
	]
};
```

Running this sequence of command will give you that immutable error:
```
Navigation.startSingleScreenApp( SingleScreenApp );
Navigation.startTabBasedApp( TabApp );
Navigation.startSingleScreenApp( SingleScreenApp );
```

But I found running this sequence will work:
```
Navigation.startSingleScreenApp(Object.assign({}, SingleScreenApp));
Navigation.startSingleScreenApp(Object.assign({}, TabApp));
Navigation.startSingleScreenApp(Object.assign({}, SingleScreenApp));
```

**Comment by sanjcho** [comment]
I got the same error, but all previous methods don't work for me. I done it with functions:
```
const singlePageSettings = () => ({
  screen: {
    screen: 'someStartupScreen',
    title: '',
    navigatorStyle: navigatorStyle.mainNavigatorStyle,
  },
  animationType: 'slide-down',
  // I got immutablility error if don't use here a new object
  appStyle: { ...navigatorStyle.appStyle },
});

export const startSinglePageApp = (passProps = {}) => {
  Navigation.startSingleScreenApp({
    ...singlePageSettings(),
    passProps
  });
};
```
