### ISSUE TITLE
Module RCCManagerModule requires main queue setup (implement requiresMainQueueSetup)

### ISSUE THREAD

**Issue by atkit** [wix/react-native-navigation#1982]
### Issue Description

There is a warning from ReactNative 0.49.1:
``
Module RCCManagerModule requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
``

### Steps to Reproduce / Code Snippets / Screenshots

Is shown in Crome Debugger on start.

---
### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.49.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Debug

**Comment by larryranches** [comment]
I am also this the warning on the debugger after upgrading to React Native 0.49.3. Any help on this warning?

**Comment by esses77** [comment]
I followed the instructions at [Add requiresMainQueueSetup to fix warning in RN 0.49+ #245](https://github.com/yamill/react-native-orientation/pull/245) and there is no more the warning.
