### ISSUE TITLE
Render React component on top on Navigation Bar

### ISSUE THREAD

**Issue by alimek** [wix/react-native-navigation#1984]
Hello all,

I have a use case that i would like to render `React` component on top of navigation bar.

I would like to have toast message with animation going from top of screen to like 100px and then after 5 secs hide it back.

Can't find any solution for this. Has anyone solution for this?

**Comment by i198622** [comment]
I think you should use
`
this.props.navigator.showInAppNotification({
 screen: "example.InAppNotification", // unique ID registered with Navigation.registerScreen
 passProps: {}, // simple serializable object that will pass as props to the in-app notification (optional)
 autoDismissTimerSec: 1 // auto dismiss notification in seconds
});
`
More details https://wix.github.io/react-native-navigation/#/screen-api

**Comment by alimek** [comment]
Hi @i198622 .

Thanks! I have missed this on documentation. This is exactly what I was looking for. Thanks!

**Comment by alandmonte** [comment]
Hi, I would like to show the badge on navbar notification icon. Any idea how to do that?

![image](https://user-images.githubusercontent.com/14125474/38791980-6770236c-4168-11e8-8d68-0ef4e1b47dae.png)

**Comment by alimek** [comment]
@alandardic render custom component as navbar button.

**Comment by alandmonte** [comment]
It worked thanks. I was able to render the notification component in the right buttons, but don't know why I can't render left button as custom component I want to load logo image there. If I  load the logo image in right buttons it renders but not for left buttons...

**Comment by alimek** [comment]
not sure why, try google something. I also had problem sometimes that custom component was not working on Android, but it was long time ago, maybe its fixed now ;)
