### ISSUE TITLE
Navbar left button appear nothing when using custom component

### ISSUE THREAD

**Issue by xshadowlegendx** [wix/react-native-navigation#1985]
Here is my custom component for the left button:

```
const CustomLeftButton = function () {
    return (
        <TouchableOpacity
            hitSlop={{ top: 20, bottom: 20, left: 20, right: 20 }}
            style={ styles.touchable }
            onPress={ _ => alert ( "bro" ) }
        >
            <Image
                style={ styles.avatar }
                soure={{ uri: avatar }}
            />
        </TouchableOpacity>
    );
};
```
I already registered the left button component, and here is the tab:

```
{
    screen: 'app.HomeScreen',
    title: 'Home',
    icon: home,
    navigatorStyle,
    navigatorButtons: [
        leftButtons: [
            {
                id: 'custom-button',
                component: 'app.LeftAvatarButton'
            }
        ]
    ]
}
```
**Investigation**
1. If I change it to icon, using vector icons it work as normal. I already test the avatar component, nothing is wrong but making a left button does not seeing it appear.
2. I tried to click on it, to see if it has the wave effect at where the left button should be but it did not do anything.
3. Tried putting componentDIdMount inside the custom button, the console log fired but did not see it render.
4. Tried using text instead of image also and did not see it.
5. Adding 2 icon like the code below does not work, while removing the custom component make the second one works:

```
{
    // ... same as above
    leftButtons: [
        {
            id: 'custom-button',
            component: 'app.LeftAvatarButton'
        }, {
            id: 'test-button',
            icon: home, // uri of icon
            buttonColor: 'red
        }
    ]
}
```
6. Making it to right button crashes the whole app

PS: This package is very good, using native approach to build the navigation but overall i think the document not really make that much sense or maybe I am just dumb. Try to fix this for like half way trying to make the icon up there, and there is this problem that is hard to navigate back to previous single screen app after you navigated to tab based app.

**Comment by atlas1119** [comment]
I have the same problem, can you solve it?

**Comment by yagneshmodh** [comment]
I have also same issue. No custom left button display in showmodal.

**Comment by xshadowlegendx** [comment]
I am using custom icon instead of component as replacement for custom left button for android. I could do the custom button on IOS but not android since it is not supported ( searching from the issues ). Using custom component is not recommended from my thought because it does not allow you to pass any props like navigator props or do any action.

**Comment by tmaly1980** [comment]
You have to register the component where you register the rest of your screens. Also, it doesn't look like Android has this implemented. Which I find ridiculous. And working with the navigator isn't a problem as long as you use deep link triggering/handling. You won't be using this.props.navigator though.

**Comment by die20** [comment]
Yea why would customers buttons work for iOS but not android?

**Comment by tedwong** [comment]
So, does it have a solution / workaround?
