### ISSUE TITLE
Update your AppDelegate.m to follow React Native 0.49.1!!!!!!

### ISSUE THREAD

**Issue by keri4141** [wix/react-native-navigation#1986]
### iOS splashscreen simulator hangs

It looks like the new React Native version no longer uses index.ios.js, but instead uses index.js.

<img width="855" alt="screen shot 2017-10-06 at 5 59 21 pm" src="https://user-images.githubusercontent.com/16449435/31300151-2411c4fc-aac0-11e7-9a01-6c5c57491603.png">

In your example for editing AppDelegate.m,
 https://github.com/wix/react-native-navigation/blob/master/example/ios/example/AppDelegate.m

You're using index.ios.js, not index.js. I changed it to index.js, however when I run react-native run-ios the app hangs on the splash screen.

---
### Environment
* React Native Navigation version: ^1.1.235
* React Native version: 0.49.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by zebpaypeswani** [comment]
@keri4141 I am getting same issue. Can you please tell me what's the solution.

**Comment by joelvoss** [comment]
@keri4141 I am having the same issue. It would be nice to know what modifications are necessary to get this working.

**Comment by wellyal** [comment]
any updates?

**Comment by keri4141** [comment]
I closed it because i got discouraged after someone down-voted the issue :(. But since there are a couple of people responding now, I guess I'll reopen

**Comment by keri4141** [comment]
For those that are having this issue, you can refer to this for the android development part:

https://github.com/wix/react-native-navigation/issues/2010

As for iOS, I don't know yet.

**Comment by pqkluan** [comment]
Closed because this issue duplicate to #2010
