### ISSUE TITLE
[iOS] Passing props to Sidemenu with toggleDrawer

### ISSUE THREAD

**Issue by oliviachang29** [wix/react-native-navigation#1987]
### Issue Description

How do I pass props to the sidemenu? I want the sidemenu to know which screen is the current screen. I have multiple screens (today, calendar, etc.) which can be accessed from the side menu, and the sidemenu needs to show which screen the user currently has open. 

The first screen that the app shows is Today. When the user opens the sidemenu, I want the sidemenu to display that the value of prop `currentScreen` is 'today'. 

*Side menu open on screen Today:*

<img width="242" alt="screen shot 2017-10-07 at 2 33 12 pm" src="https://user-images.githubusercontent.com/15709895/31311956-84ace13c-ab6c-11e7-9af5-1e3bf1d67696.png">

When the user changes to the screen Calendar the sidemenu should say that currentScreen is 'calendar'. Instead, it shows that currentScreen is 'today'.

*Side menu open on screen Calendar:*

<img width="245" alt="screen shot 2017-10-07 at 2 33 20 pm" src="https://user-images.githubusercontent.com/15709895/31311957-84ad6ec2-ab6c-11e7-8692-b124395f18e0.png">

### Steps to Reproduce / Code Snippets / Screenshots

*src/App.js*
```
import {Platform} from 'react-native'
import {Navigation} from 'react-native-navigation'
import registerScreens from './screens'

registerScreens()

Navigation.startSingleScreenApp({
  screen: {
    screen: 'app.Today',
    title: 'T O D A Y',
  },
  passProps: {
    currentScreen: 'today'
  },
  drawer: {
    left: {
      screen: 'app.Drawer',
    },
    style: {
      drawerShadow: false,
      contentOverlayColor: 'rgba(0,0,0,0.2)',
      leftDrawerWidth: 65,
    },
    disableOpenGesture: false,
    animationType: 'slide-and-scale',
  },
  appStyle: {
    orientation: 'portrait'
  },
  animationType: 'fade',

})
```
Opening sidemenu and handling deeplinks to go from Today to Calendar:

*src/screens/Today.js*
```
onNavigatorEvent(event) {
    if (event.type == 'NavBarButtonPress') {
      if (event.id == 'drawer') {
        this.props.navigator.toggleDrawer({ // open drawer
          side: 'left',
          passProps: {
            currentScreen: 'calendar'
          }
        });
      }
    } else if (event.type == 'DeepLink') {
      if (event.link === 'Calendar') {
        this.props.navigator.resetTo({
          screen: 'app.Calendar',
          title: 'C A L E N D A R',
          animationType: 'fade',
          passProps: {
            currentScreen: 'calendar'
          }
        });
      }
  }
```
src/screens/Drawer.js
```
class Drawer extends Component {
  constructor(props) {
    super(props)
    this.state = {
      currentScreen: this.props.currentScreen
    }
  }

  gotoToday = () => {
    this.toggleDrawer()
     this.props.navigator.handleDeepLink({
      link: 'Today'
    })
  }

  gotoCalendar = () => {
    this.toggleDrawer()
    this.props.navigator.handleDeepLink({
      link: 'Calendar'
    })
  }

  toggleDrawer = () => {
    this.props.navigator.toggleDrawer({
      side: 'left'
    });
  };

  render() {
    return (
      <View style={styles.container}>
        <Button onPress={this.gotoToday} text='today' />
        <Button onPress={this.gotoCalendar} text='calendar' />
        <Button text='map' />
        <Button text='profile' />
        <Button text='settings' />
        <Text>currentScreen: {this.state.currentScreen}</Text>

      </View>
    );
  }
}

module.exports = Drawer;
```
---
### Environment
* React Native Navigation version: 1.1.205
* React Native version: 0.46.4
* Platform: iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iOS 10.0, Debug

**Comment by umerbaig** [comment]
I'm facing same issue on Android also.

**Comment by antoxann96** [comment]
Same on Android. Works fine on iOS

**Comment by oliviachang29** [comment]
@antoxann96 can you post your code solution? I'd like to see where my code is going wrong.

**Comment by peterlau** [comment]
Support for dynamically rendered drawers is one weak area that  `react-native-navigation`  sadly shares with `react-navigation`.  Rather than looking for a workaround I suggest using `react-native-drawer` which allows you define drawers as a standard child component of your screen (thereby inheriting whatever props/customization is needed)

**Comment by antoxann96** [comment]
Thx @peterlau! Fully support your solution! Btw, we've already using it for solving our problem!

**Comment by peterlau** [comment]
Also, this became a moot point for us when we transitioned to global state management and binding using `react-redux`.

Until this gets properly addressed in `react-native-navigation`, it might be a good excuse to dive into redux for anybody encountering this limitation.
