### ISSUE TITLE
BottomTabs issue

### ISSUE THREAD

**Issue by mehdijjz** [wix/react-native-navigation#1988]
### Issue Description

in a tab based app, when I hide the tabs on a screen and push to another page with `tabBarHidden: true` navigatorStyle, and then pop back, the tabBar will get shown.

Update:
I'm currently using a hack which I hide the tabBar manually in `willAppear` of `OnNavigatorEvent` event listener and it's pretty ugly

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.48.2
* Platform(s) (iOS, Android, or both?): Both

**Comment by tayfunyugruk** [comment]
Same here. also **toggleTabs** does not work, i executed toggleTabs with a button click in problematic screen but it did not work.

**Environment :** 
React Native Navigation version: latest
React Native version: 0.47.1
Platform(s) (iOS, Android, or both?): iOS
