### ISSUE TITLE
props.navigator is undefined in a custom button component

### ISSUE THREAD

**Issue by saudpunjwani101** [wix/react-native-navigation#1989]
I have a custom button and have registered it as a screen, but navigator is undefined in there.

        const CustomButton = (props) =>
           <TouchableOpacity
           onPress={()=>console.log(props.navigator //undefined)}
           style={{flexDirection:'row', justifyContent:'flex-start',marginLeft:-8,marginTop:2}}>
          <Icon name="ios-arrow-back" style={{fontSize:36,color:"#007aff"}} />
          <Text style={{marginLeft:5,marginTop:8, fontSize:16, color:"#007aff"}}>Shops</Text>
      </TouchableOpacity>

This is the button, here's the registry

      Navigation.registerComponent('customButton', () => CustomButton)

I'm calling it in some component like this,

      class Category extends React.Component {
            static navigatorButtons = {
               leftButtons: [
                 {
                    id: 'popping',
                    component: 'customButton'
                }
            ],
         }
       ...

How can I use the navigator in this custom button?

**Comment by i198622** [comment]
You should import navigator.
`import { Navigation } from 'react-native-navigation';`
And use DeepLinking https://wix.github.io/react-native-navigation/#/top-level-api?id=handledeeplinkparams- to handle button press.

**Comment by ishrak-imam** [comment]
I didn't understood the the solution regarding DeepLink mentioned above. But here's a valid solution below.


Custom buttons aren't associated with a navigator. You'll need to set the button in the screens' constructor and pass the navigator in props.
```
constructor(props) {
    super(props);
    this.props.navigator.setButtons(this.navigatorButtons(this.props.navigator));
  }

  navigatorButtons = (navigator) => {
    return {
      leftButtons: [
        {
          id: 'custom-button',
          component: 'CustomButton',
          passProps: {
            text: 'Hi!',
            navigator
          }
        }
      ]
    };
  }
```

Thanks to this stackoverflow guy who gave the answer.
https://stackoverflow.com/questions/47486649/react-native-navigation-navigator-is-undefined-custom-button

But the real question is How someone is supposed to figure this out with this portion of the doc.
https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=custom-navigation-buttons
