### ISSUE TITLE
How to install version 2.0?

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#199]
I am new git, How to install version 2.0.

Thanks you!

**Comment by guyca** [comment]
change version of `react-native-navigation` in package.json to `next` and follow the [migration guide](https://github.com/wix/react-native-navigation/tree/v2.0#migrating-to-version-20)

note that it's still under development.

**Comment by danceyoung** [comment]
sorry,I follow this migration guide https://github.com/wix/react-native-navigation/tree/v2.0#migrating-to-version-20,
but no com.reactnativenavigation.controllers.SplashActivity 

android , 0.31RN

**Comment by guyca** [comment]
@danceyoung Did you sync project with gradle files? In any case, I doubt the v2.0 will work properly with RN 0.31 on Android. a lot has changed in react native's internal api and we got some catching up to do.
