### ISSUE TITLE
React native navigation + redux simple example

### ISSUE THREAD

**Issue by tigo0** [wix/react-native-navigation#1991]
Hey,
I am struggling with implementing v2 with redux. Followed up this issue #1642 and the v2 documentation, unfortunately did not get me to a proper solution. Is there a working simple example that I can rely to implementing react-native-navigation v2 + redux that loads a screen. Thanks
### Environment
* React Native Navigation version: 2.0.2008
* React Native version: 0.49.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): any

**Comment by xmarianox** [comment]
@tigo0 this is a great example to use `react-native-navigation` + `redux`, [handling-wix-react-native-navigation-with-redux](https://medium.com/technoetics/handling-wix-react-native-navigation-with-redux-3f593927057a)

**Comment by tigo0** [comment]
@xmarianox thank you, I have seen that example. Although my problem relates to v2 of react native navigation, and that example is based on v1. As shown in the example, v1 connects with the store by passing it to the views, like: 
`/* eslint-disable import/prefer-default-export */
import { Navigation } from 'react-native-navigation';
import Home from './modules/appscreens/Home';
export function registerScreens(store, Provider) {
    	Navigation.registerComponent('app.Home', () => Home, store, Provider);
}`
Regardless, in v2 it is a bit different to my understanding, and so far I did not manage to run it properly. Therefore, I am asking for some guidance on v2 and redux.

**Comment by michael-gillett** [comment]
@tigo0 @billsader See #1642 I just shared my component wrapper code for redux in v2 which should be enough to get you off the ground

**Comment by gaillota** [comment]
Hello,
Does anyone have a solution for this ? The v2 API has changed and is now

`registerComponent(componentName: string, getComponentClassFunc: ComponentProvider)`

How do handle the Redux store from now on ?

**Comment by danielbertini** [comment]
Does have a elegant solution for this?

**Comment by voidstarfire** [comment]
FYI, if you're using Typescript it will actually tell you the options available..
