### ISSUE TITLE
InApp Notification rendered behind LightBox on Android

### ISSUE THREAD

**Issue by mdrbohlav** [wix/react-native-navigation#1992]
I think the title says it all - the in-app notifications are rendered behind the lightbox when I display them from the light box.

Tested only on Android.

---
### Environment
* React Native Navigation version: 1.1.205
* React Native version: 0.48.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): OnePlus 2, LineageOS with Android 7.1.2, debug

**Comment by vedovato** [comment]
Any workaround found, @mdrbohlav ?

**Comment by mdrbohlav** [comment]
Unfortunately no, I did not find any workaround

**Comment by arsal-wal** [comment]
I'm facing the same problem. Please keep this open.
