### ISSUE TITLE
initialProperties in Android

### ISSUE THREAD

**Issue by mmiani** [wix/react-native-navigation#1995]
Is there a way to set the initial props in Android? 
Previously I was extending from _ReactActivity_ and overriding _getLaunchOptions_ in the delegate, but I cannot see any method related in _SplashActivity_

---
### Environment
* React Native Navigation version: 1.1.236
* React Native version: 0.47.2
* Platform(s) : Android

**Comment by njho** [comment]
Did you happen to find a solution?

**Comment by jh-code** [comment]
Is there still no way to do this?
