### ISSUE TITLE
Android Tab Bar 

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#20]
Are there plans to create an Android Tab Bar (as opposed to the Toolbar + View Pager) - i.e. icon tabs at the bottom of the screen (as per [new Android guidelines](https://www.google.com/design/spec/components/bottom-navigation.html#))?

**Comment by guyca** [comment]
Of course. This design pattern is also very common in iOS. We'll probably use https://github.com/roughike/BottomBar which I believe you posted here a few weeks ago.

**Comment by tanguyantoine** [comment]
It seems that bottombar create an IOs like tabbar but google recommande this : https://www.google.com/design/spec/components/tabs.html#tabs-usage

**Comment by adamski** [comment]
https://www.google.com/design/spec/components/bottom-navigation.html

**Comment by tanguyantoine** [comment]
it works too :) and this is semantically better

**Comment by smooJitter** [comment]
@guyca right now, the standard seems to support the material specs.  I like your example because it as just enough to spice up native standards.  I can't wait to see it.  I working on a project with at least 60 screen views. I'll get a chance to see how well the many RCTViews hold up.  By the way are there still plans to expose drawer animations?

**Comment by yedidyak** [comment]
#45 addresses this.

![screen](https://cloud.githubusercontent.com/assets/8819594/15669984/b37e44a4-272b-11e6-88fc-a01c10ebd56e.png)

**Comment by guyca** [comment]
Thanks @yedidyak. So BottomNavigation was just added in version 1.0.5. We've decided to use [ahbottomnavigation](https://github.com/aurelhubert/ahbottomnavigation/issues). The author is very responsive and it seems to have significantly less issues compared to [BottomBar](https://github.com/roughike/BottomBar).

The new BottomBar replaces the TabLayout used as navigation. We'll probably reimplement it soon, So you will be able to have a BottomNavigation bar and TabLayout.

One feature that's missing, which we'll address in future release, is circular reveal in the navigation bar.
