### ISSUE TITLE
Conflicting type for objc_getAssociatedObject

### ISSUE THREAD

**Issue by JohnWhisker** [wix/react-native-navigation#200]
I'm new to ReactNative, when I try to install the lib and build it. It's said Conflicting types for 'obj_getAssociatedObject' 

Here is the screenshot for it:

![alt text](http://i.imgur.com/CdAMC4u.png)

**Comment by webzepter** [comment]
@JohnWhisker https://github.com/wix/react-native-controllers/issues/85

**Comment by JohnWhisker** [comment]
Thanks the problem is solved thanks to @webzepter
