### ISSUE TITLE
NPE in Android SlidingOverlay (showInAppNotification)

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#2002]
### Issue Description

I am observing some crash logs in Sentry which are originating from the `SlidingOverlay` support in Android which is used in the `showInAppNotification` screen API. Although I haven't been able to reproduce it myself, I can see the crashes in Sentry nonetheless. Below is a screenshot of the crash log on Sentry.

![screen shot 2017-10-11 at 12 21 40 pm](https://user-images.githubusercontent.com/7475133/31426094-905251dc-ae7f-11e7-946c-d6b042a5413a.png)

As you can see, the crash is originating in the `SlidingOverlay` support. When I look at the code, I see the following line:

    // SlidingOverlaysQueue.java
    Integer autoDismissTimerSec = queue.peek().getAutoDismissTimerSec();

`peek` method will return the topmost element of the queue or null if the queue is empty. I am not sure if this queue is not supposed to be empty when this method is called.

Do we need to make such calls null safe to avoid crashes in the app?

### Steps to Reproduce / Code Snippets / Screenshots

Unable to reproduce locally.

---
### Environment
* React Native Navigation version: 1.1.203
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by varungupta85** [comment]
One more crash report.
![screen shot 2017-10-11 at 12 21 40 pm](https://user-images.githubusercontent.com/7475133/31437025-793bff62-aea1-11e7-91e1-7255a23dc1ee.png)

**Comment by guyca** [comment]
merged, Thanks 👍
