### ISSUE TITLE
Custom left button isn't implemented on Android

### ISSUE THREAD

**Issue by koansang** [wix/react-native-navigation#2003]
### Issue Description

No display custom button on Android.

### Steps to Reproduce / Code Snippets / Screenshots

```js
  static navigatorButtons = {
    leftButtons: [
      {
        id: 'site-button',
        component: 'SiteButton',
        passProps: {},
      },
    ],
  }
```

---
### Environment
* React Native Navigation version: 1.1.236
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): LG V20, 6.0

**Comment by oprearocks** [comment]
Not related to your use case but be careful that you don't get `NavBarButtonPress` events for custom components. If you expect to trigger the drawer using a navbar button, make sure you're using text or an icon for your button and not a custom component.

**Comment by koansang** [comment]
@oprearocks No display that only use text or icon.

**Comment by koansang** [comment]
If use icon is show but use text is no show on Android.

**Comment by atlas1119** [comment]
not support android?

**Comment by atlas1119** [comment]
I have the same problem..

**Comment by i198622** [comment]
@koansang Did you try to add height and width to the button?
Example:
`
<TouchableOpacity onPress={this._onPressButton} style={{ width: 40, height: 40, backgroundColor: 'red' }}>
      <Image
        style={styles.button}
        source={require('./myButton.png')}
      />
</TouchableOpacity>
`

**Comment by atlas1119** [comment]
I have added width and height, but not display

**Comment by oprearocks** [comment]
@koansang Could you please share your custom button component code here?

**Comment by guyca** [comment]
Hey @koansang 
Custom component isn't supported as left button on Android - I'd gladly accept a PR. We should really through an error in this case.

**Comment by ErikMikkelson** [comment]
@guyca You removed the iOS only caveat from the docs in [this commit ](https://github.com/wix/react-native-navigation/commit/d224bf4d3903ce16b287f5243c736aee67d30824#diff-f22892bd5a337225cfd521657f623a6f).  You might want to put it back then.

**Comment by dbyilmaz** [comment]
@guyca  hey, is custom component supported by the left button on Android?

**Comment by tmaly1980** [comment]
@guyca Why is this not implemented? Doesn't that kind of defeat the purpose of a cross-platform library/framework, if only one side is developed?

**Comment by guyca** [comment]
@tmaly1980 
You're right. The reason it wasn't implemented is simply because this feature isn't needed by Wix. Wix allows developers to dedicate 20% of their time to open source, but since I'm now actively working on v2, I have less time for v1... I try to focus mainly on maintenance and can't really work on new features for v1.
I'm closing this as it really isn't a bug.

**Comment by tmaly1980** [comment]
Does it work in v2?

**Comment by bjacog** [comment]
@guyca I'm keen to add this to v1, is there a wix discord?

**Comment by FinnGu** [comment]
This is still an issue in v1 and v2.
