### ISSUE TITLE
How to remove bottom tabbar border?

### ISSUE THREAD

**Issue by koansang** [wix/react-native-navigation#2005]
### Issue Description

I wish remove border in bottom tabar.
How do you do it?

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by ethluz** [comment]
我也有这个需求，i have this question too。
in topBar：noBorder: true。
but bottomTabs it is not work。

**Comment by cspicuzza** [comment]
try `bottomTabs: { hideShadow: true }`
