### ISSUE TITLE
Drawer Events?

### ISSUE THREAD

**Issue by SchwarzerSchnee** [wix/react-native-navigation#2006]
### Issue Description

My app is arranged as a drawer navigation. I have a settings screen with a save button, and I'm tracking unsaved changes in this screen's state. Now what I want to do is this: show an alert when the user tries to leave the settings screen without saving unsaved changes...and then keep them on the screen when they hit the cancel button. What am I supposed to do in order to accomplish this? I've tried the normal navigator events ('willDisappear', 'didDisappear' etc.) and they're not catching this. Is there a way?

---
### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.48.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): all currently usable iPhones

**Comment by chmac** [comment]
I read in another ticket that there are no drawer events on iOS #1545.
