### ISSUE TITLE
Touchable Component is not clickable after swiping back from a scrollview screen

### ISSUE THREAD

**Issue by xuzb** [wix/react-native-navigation#2008]
### Issue Description

Touchable Component is not clickable at first time after swiping back from a screen that contains a scrollview.

### Steps to Reproduce / Code Snippets / Screenshots

Screen A:
```
render() {
  return (
      <View>
          <TouchableOpacity 
                onPress={() => this.props.navigator.push({screen: 'ScreenB', ...}}>
              <Text>Click Me</Text>
           </TouchableOpacity>
      </View>
  );
}
```

Screen B:
```
render() {
    return (
        <ScrollView>
           <Text>Please swipe me back</Text>
        </ScrollView>
    );
}
```

---
### Environment
* React Native Navigation version: 1.1.213
* React Native version: 0.48.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device, iOS 11, DEBUG

**Comment by ywongweb** [comment]
try adding `keyboardShouldPersistTaps="always"` to your touchables

**Comment by ywongweb** [comment]
try adding `keyboardShouldPersistTaps` to your scrollview
```
<ScrollView keyboardShouldPersistTaps="always">
```

**Comment by xuzb** [comment]
Still not work

**Comment by tudorilisoi** [comment]
happens on Android 6 as well, RN 0.50.4
