### ISSUE TITLE
Still android can not retrieve the URL using Linking.getInitialURL() when new incoming intent data received.

### ISSUE THREAD

**Issue by ggizuru** [wix/react-native-navigation#2009]
### Issue Description
Hello,
I am trying to  link  to specific screens in my project by using custom external URL (testapp://myapp/booking/1234) via SMS message .

but **app launched**  {adb shell am start  -d "testapp://myapp/booking/1234"} **but it does not get the URL   (Alert >>> URL= Null)**

RN component: 

componentDidMount() {
  if (Platform.OS === 'android') {
        Linking.addEventListener('url', this.handleOpenURL);
        Linking.getInitialURL().then(url => {
          alert(url)
        });
    } 
}

AndroidMaifest.xml :
    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="23" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/appicon"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        >
          <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
          </intent-filter>
          <intent-filter android:label="filter_react_native" >
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="testapp"
                  android:host="myapp" />
          </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

---
### Environment
* React Native Navigation version: "^1.1.84"
* React Native version: "^0.48.4"
* Platform(s) Android 
* Device info: Simulator/Device OS version:Debug

**Comment by ggizuru** [comment]
@guyca can you help me ? iOS working fine.

**Comment by henrikra** [comment]
What if you app is open at background and you click the SMS link? What happens then?

**Comment by ggizuru** [comment]
app is open but below event's url is "null"
(I expected url is "testapp://myapp/1234")

 componentDidMount() {
if (Platform.OS === 'android') {
Linking.addEventListener('url', this.handleOpenURL);
Linking.getInitialURL().then(url => {
alert(url)
});
}
}

**Comment by jay1337** [comment]
@ggizuru With universal links always test the two cases: app already running in background AND app killed not running.

For Android you have to listen to app state changes to deal with the second case:

```
const handleAppStateChange = function(newAppState) {
	if (newAppState === 'active') {
		AppState.removeEventListener('change', handleAppStateChange);
		Linking.getInitialURL().then((url) => {
			handleNewUrl(url);
		});
	}
};
if (Platform.OS === 'android') {
	AppState.addEventListener('change', handleAppStateChange);
}
```

**Comment by ggizuru** [comment]
@jay1337 At Android simulator, it is working randomly, not working fine. otherwise it is alert shown as a "Null"

  componentDidMount() { 
    if (Platform.OS === 'android') {
      AppState.addEventListener('change', this.handleAppStateChange);
    } else {
      }
    }

    handleAppStateChange(newAppState) {
      if (newAppState === 'active') {
        AppState.removeEventListener('change', this.handleAppStateChange);
        Linking.getInitialURL().then((url) => {
          //handleNewUrl(url);
          **alert(url);**
        });
      }
    }

**Comment by jay1337** [comment]
@ggizuru You tried to kill the app and then to click on a link ? You must put the AppState.addEventListener directly in a file directly or indirectly required by the entry file (eg `index.js`) of your app (you don't really know when the code in `componentDidMount` will be executed).

**Comment by uqmessias** [comment]
@ggizuru, I have the same issue.
Please, try to use just `Linking.addEventListener` instead of `getInitialURL`. And, please add the `android:launchMode="singleTask"` into Andorid Manifest.

**YourComponent.js**
```
...
componentDidMount() {
  // remove the getInitialURL call
  Linking.addEventListener('url', this.handleOpenURL);
}
...

componentWillUnmount() {
  Linking.removeEventListener('url', this.handleOpenURL)
}
...
```

**AndroidMaifest.xml**

```
  <activity
    ...
    android:launchMode="singleTask"
    ...
    >
```

Note that, if you're using `` in the manifest, the `MainActivity` will receive a new intent that [dispatches the event with `url` as a key](https://github.com/facebook/react-native/blob/13d8375323c8fac2cfa94648cdde75448faaa01e/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java#L519)

**Comment by reyalpsirc** [comment]
Using `Linking.addEventListener('url', this.handleOpenURL)` and setting the code on [this stackoverflow question](https://stackoverflow.com/questions/11721619/resume-the-top-activity-instead-of-starting-the-launcher-activity/21022876#answer-38878907) (even with `launchMode="singleTop"` seems to solve the issue for me
