### ISSUE TITLE
When I change the root to a tab app on iOS, I receive an NSInternalInconsistencyException error

### ISSUE THREAD

**Issue by simonmitchell** [wix/react-native-navigation#201]
Code can be seen below:

```
switch (rootId) {

    case "splash": {
		Navigation.startSingleScreenApp({
			screen: {
				screen: SPLASH_SCREEN_ID,
			},
			passProps: passProps
		})
	}

	case "main": {
		Navigation.startTabBasedApp({
  			tabs: [
    			{
      				label: 'One',
      				screen: DISCOVER_SCREEN_ID, // this is a registered name for a screen
      				// icon: require('../img/one.png'),
      				// selectedIcon: require('../img/one_selected.png'),
      				title: 'DISCOVER'
    			},
    			{
      				label: 'Two',
      				screen: SEARCH_SCREEN_ID,
      				// icon: require('../img/two.png'),
      				// selectedIcon: require('../img/two_selected.png'),
      				title: 'SEARCH'
    			},
    			{
    				label: 'Three',
    				screen: PAY_SCREEN_ID,
    				title: 'PAY'
    			}
  			]
		});
	}
}
```

We switch the main route in after persisting state to our redux store and get this error:

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Expect all root views to have unique tag. Added 1 twice'`

I'm not an expert on how react-native-controllers works, but it looks like it's an issue where you're not unregistering the current root view before setting the new one?

**Comment by aksonov** [comment]
Looks like some breaking changes from RN0.31 Example  project doesn't work as well

**Comment by simonmitchell** [comment]
Ahh yes, you're probably right there. We've just started up a new RN project with one of our clients. I'm going to fork and see if I can figure out what's going on now as we need to get up-and-running pronto!

**Comment by simonmitchell** [comment]
Actually scrap that. It works in our project if you add in the `break;` part of the switch statement which I forgot were needed (Too much swift recently!). We're going to carry on as is.

**Comment by aksonov** [comment]
@simonmitchell what do you mean? Current Example project from this component just throws this exception.

**Comment by simonmitchell** [comment]
So the above code sample, our splash screen performs some Asynchronous setup and then calls changeRoot("main"). The problem wasn't that we were switching to a tab-based app, rather that both cases in the switch statement were being called on initial launch. I guess the problem is being caused when the root viewController is being changed in extremely quick succession?

**Comment by aksonov** [comment]
Have you tried just example project from this component. Related react-native-controllers is broken as well with RN0.31

**Comment by simonmitchell** [comment]
I'm afraid I don't have time to really now :/ We're on a very tight schedule with this project!

**Comment by aksonov** [comment]
Ok, i hope assigned people will do that. I just wanted to tell you that your error is not related to your code but to RN 0.31 :)

**Comment by simonmitchell** [comment]
Ahh I gotcha, thank you, appreciate it :)

**Comment by DanielZlotin** [comment]
Please see #234
