### ISSUE TITLE
Error Installing wix for android RN .49

### ISSUE THREAD

**Issue by kriptonhaz** [wix/react-native-navigation#2010]
### Issue Description

> Bundling `index.android.js`  [development, non-minified]  0.0% (0/1), failed.
error: bundling failed: NotFoundError: Cannot find entry file index.android.js in any of the roots: ["c:\\Users\\haz\\Desktop\\GProject"]
    at DependencyGraph._getAbsolutePath (c:\Users\haz\Desktop\GProject\node_modules\metro-bundler\src\node-haste\DependencyGraph.js:305:11)
    at DependencyGraph.getDependencies (c:\Users\haz\Desktop\GProject\node_modules\metro-bundler\src\node-haste\DependencyGraph.js:283:4236)
    at Resolver.getDependencies (c:\Users\haz\Desktop\GProject\node_modules\metro-bundler\src\Resolver\index.js:129:5)
    at c:\Users\haz\Desktop\GProject\node_modules\metro-bundler\src\Bundler\index.js:642:39
    at next (native)
    at step (c:\Users\haz\Desktop\GProject\node_modules\metro-bundler\src\Bundler\index.js:13:1336)
    at c:\Users\haz\Desktop\GProject\node_modules\metro-bundler\src\Bundler\index.js:13:1496
    at process._tickCallback (internal/process/next_tick.js:109:7)

### Steps to Reproduce / Code Snippets / Screenshots

> react-native init GProject
> npm install --save react-native-navigation
> follow installation for android in [https://wix.github.io/react-native-navigation/#/installation-android](url)
> 

### Environment
* React Native Navigation version: react-native-navigation@1.1.236
* React Native version:  0.49.3
* Platform(s) (iOS, Android, or both?): Android
* Device info : Device Android 6.0.1

**Comment by vdhieu** [comment]
Duplicate index.js and name it index.android.js

**Comment by kriptonhaz** [comment]
Based on the documentation in RN 49 there are no more index.android.js and just a single index.js

**Comment by vdhieu** [comment]
I know that, but react-native-navigation still use old RN template which needs separated index files for each platform. So for now create index.android.js will solve your problem.

**Comment by maitham1** [comment]
rather than initializing from react-native init, start app using  https://github.com/wix/react-native-navigation-bootstrap then update dependencies!

**Comment by chaitanya0bhagvan** [comment]
@kriptonhaz In your Application.java add the following method. 

```
    @Override
    public String getJSMainModuleName() {
        return "index";
    }
```

The implementation inside NavigationApplication still uses 

> index.android

**Comment by Zephir77167** [comment]
Hey for people still running into this issue,, I updated the docs to explain the changes needed on ios and android: https://github.com/wix/react-native-navigation/pull/2412
