### ISSUE TITLE
Theming with styled-components

### ISSUE THREAD

**Issue by SergeySivchenko** [wix/react-native-navigation#2013]
### Issue Description

I'm working with [styled-components](https://github.com/styled-components/styled-components) on my react-native project. We are using react-native-navigation to perform navigation within the application. So the question is how can I implement theme pattern from styled-components in such kind of application? The problem is that to perform the idea of theming in terms of styled-components I have to wrap my top level component in `<ThemeProvider />` like this:
```
<ThemeProvider theme={theme}>
    <App />
</ThemeProvider>
```
But with react-native-navigation I don't have top level component.
I tried to use `passProps`  from `startSingleScreenApp`, but this pass the theme prop to top screen component only.

---
### Environment
* React Native Navigation version: 1.1.236
* React Native version: 0.49.3
* Styled Components: 2.2.1
* Redux: 3.7.2
* Platform(s) (iOS, Android, or both?): both

**Comment by alimek** [comment]
see #1920

**Comment by SergeySivchenko** [comment]
@alimek Thank you!
