### ISSUE TITLE
Top Bar buttons don't retain styling on status changes

### ISSUE THREAD

**Issue by andrzli** [wix/react-native-navigation#2016]
### Issue Description

Navigation bar buttons don't seem to retain set styling depending on their state (selected/highlighted, disabled, etc.) and instead revert to default stylings. I would like to either set the styling for these different states, or have it inherit the styles if not set.

### Steps to Reproduce / Code Snippets / Screenshots

Code Snippet:
on pushing new scene:
```
navigatorButtons: {
          leftButtons: [{
            title: 'Cancel',
            id: 'left button',
            buttonColor: 'blue',
            buttonFontSize: 13,
            buttonFontWeight: '600',
          }],
          rightButtons: [{
            title: 'Done',
            id: 'right button',
            buttonColor: 'blue',
            buttonFontSize: 13,
            buttonFontWeight: '600',
            disabled: true,
          }],
        },
```

Screenshot:
![simulator screen shot - iphone 7 - 2017-10-12 at 11 02 07](https://user-images.githubusercontent.com/2774505/31511650-424344ba-af3d-11e7-852f-0d55ca9a0a39.png)
![simulator screen shot - iphone 7 - 2017-10-12 at 11 07 34](https://user-images.githubusercontent.com/2774505/31511816-bb4e5322-af3d-11e7-85b1-1448b932a4ff.png)

---
### Environment
* React Native Navigation version: `1.1.235`
* React Native version: `0.48.4`
* Platform(s) (iOS, Android, or both?): `iOS`
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 7 simulator. iOS 11

**Comment by grundmanise** [comment]
Same here @ iOS 11: iPhone 5s (real) + on all simulators.

React Native version: `0.50.4`
React Native Navigation version: `1.1.297`

**Comment by grundmanise** [comment]
https://github.com/wix/react-native-navigation/issues/2353
