### ISSUE TITLE
Detect the current active screen

### ISSUE THREAD

**Issue by srameshr** [wix/react-native-navigation#2018]
### Issue Description
Procedure to detect the currently active or mounted screen.
### Steps to Reproduce / Code Snippets / Screenshots

How to detect the currently active screen?
```const visibleScreenInstanceId = await Navigation.getCurrentlyVisibleScreenId()```
This returns a screenId, but how to map it to the currently active screenId?

---
### Environment
* React Native Navigation version: 1.1.231
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): iOS 9 to 11
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by edolix** [comment]
Hello there,

any updates on this? 

Thanks a lot!

**Comment by srameshr** [comment]
Did anyone figure out a solution for this?
@guyca

**Comment by netojose** [comment]
Hi, I want this answser. I just receiving some like that "screenInstanceID6"

Thanks

**Comment by RGump** [comment]
+

**Comment by die20** [comment]
+1

**Comment by JesseTheDev** [comment]
+1

**Comment by awchang56** [comment]
+1

**Comment by beginnermanish** [comment]
+1

**Comment by rickyliu93** [comment]
+1

**Comment by brunolemos** [comment]
You can get the screen instance id inside the navigator object:

```js
constructor(props) {
  super(props)
  console.log('screenInstanceID', props.navigator.screenInstanceID)
}
```

Now the mapping is up to you.
But I really wish that was not necessary.

**Comment by brunolemos** [comment]
I really wish it also returned the `screenID` that we used when registering (e.g. `org.brunolemos.HomeScreen`) instead of only `screenInstanceID2`, that would make things a lot easier.

**Comment by JorgeCeja** [comment]
Thanks @brunolemos I'll see what solution I can come up with and I'll report back.

**Comment by alexsmartens** [comment]
Any news on this?

**Comment by GokulDharumar** [comment]
i am looking for the screen name too instead of instanceId. please let us know if any update on this

**Comment by AE0011** [comment]
Any solution??

**Comment by alexsmartens** [comment]
I would love to see a good implementation of this feature, but here is my workaround:


### Solution 1, detecting current screen in its code base

`this.props.testID` holds the screen name which you assigned to your screen when registered your navigation:
* registration of your navigation
```
onGetStartTabBasedApp(callbackOnSignOut, username) {
      Navigation.startTabBasedApp({
        tabs: [{
              label: 'myScreenName1',
              screen: 'scene.myScreenName1',
              icon: myIcon1,
            }, {
              label: 'myScreenName3',
              screen: 'scene.myScreenName2',
              icon: myIcon2,
            }
          ],
      })
    }

```
* checking current screen name from it's code base
```
if (this.props.testID=='scene.myScreenName1') {
    console.log('current screen is ' + this.props.testID )
}
```


### Solution 2, detecting current screen from the outside of your screen's code base

I created a listener to navigation events. When you click to any tab a series of events pops up in the listener. These events have various information including current screen id (`event.id` property) . 
Given you have a static number of tabs, you can check which tab is open.

**Comment by AE0011** [comment]
`this.props.testID` works for me. Thanks 
I wonder why this point isn't in doc

**Comment by AE0011** [comment]
@alexsmartens 
Is there any solution for drawer items? (to prevent multiple push a screen in stack)
In drawer `this.props.testID` shows drawer register id instead of a screen which contain drawer

**Comment by netojose** [comment]
I don't know exactly what `this.props.testID` means, but looking for the `testID` word, don't sounds good for real production code 😛

**Comment by AE0011** [comment]
@netojose 
So what do you suggest? how we can handle it

**Comment by guyca** [comment]
Hey guys
Detecting the currently visible screen (active?) can be done in v2 by listening to the [didAppear event](https://wix.github.io/react-native-navigation/v2/#/docs/events?id=componentdidappear):

```js
Navigation.events().registerComponentDidAppearListener((componentId, componentName) => {

});
```
