### ISSUE TITLE
showInAppNotification is display as fullscreen in android 

### ISSUE THREAD

**Issue by yagneshmodh** [wix/react-native-navigation#2019]
### Issue Description

I am trying to display App notification at the bottom but in android notification not overlay tabbar.

while in IOS it is working fine.

Please guide me how to hide tabar while open notification at bottom

### Steps to Reproduce / Code Snippets / Screenshots

--------------------index.js------------------------

```
this.props.navigator.showInAppNotification({
      screen: 'krooqi.MapDetail',
      passProps: {},
      position: 'bottom',
      autoDismissTimerSec: 100,
    });
```

--------------------mapDetail.js------------------------

```
const { width } = Dimensions.get('window');

const MapDetail = props => (
  <View
    style={{
      flex: 1,
      height: 200,
      width,
      backgroundColor: 'red',
    }}
  >
    <View>
      <Text>Hello</Text>
    </View>
  </View>
);

MapDetail.propTypes = {};

export default MapDetail;
```

Android Screenshot

<img width="566" alt="screenshot 2017-10-14 00 48 02" src="https://user-images.githubusercontent.com/9801499/31562605-b9d252ae-b079-11e7-8c4e-1e10dc396ed0.png">

IOS Screenshot

![image](https://user-images.githubusercontent.com/9801499/31550352-b85c6a02-b04e-11e7-8382-c4510ccc4e15.png)

---
### Environment
* React Native Navigation version: 1.1.236
* React Native version: 0.49.3
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Genymotion

**Comment by guyca** [comment]
Hey

Try using: `{flex-shrink: 1, height: 70}`
You can use [toggleTabs](https://wix.github.io/react-native-navigation/#/screen-api?id=toggletabsparams-) to hide the tabs.
