### ISSUE TITLE
"navigator.setDrawerEnabled" throws "Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference" Error

### ISSUE THREAD

**Issue by Kukhapprabu** [wix/react-native-navigation#2021]
### Issue Description

With reference to https://github.com/wix/react-native-navigation/issues/922#issuecomment-302897609 by @lndgalante I have implemented model based Drawer disabling and is working perfectly. However, when I try to implement `navigator.setDrawerEnabled` as per https://github.com/wix/react-native-navigation/issues/922#issuecomment-312807828 by @kyle-ssg, I am facing the following error.

> Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
fromString
    SideMenu.java:32
setSideMenuEnabled
    NavigationReactModule.java:157
invoke
    Method.java
invoke
    Method.java:372
invoke
    JavaMethodWrapper.java:363
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:135
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:818

### Code Snippet / Screenshot
Approach 1:
`componentDidMount() {`
    `const {navigator} = this.props;`
    `InteractionManager.runAfterInteractions(() => {`
       `navigator.setDrawerEnabled({enabled: false});`
   `});`
`}`

Approach 2:
`componentDidMount() {`
    `const {navigator} = this.props;`
     `navigator.setDrawerEnabled({enabled: false});`
`}`

Both approaches throws the mentioned error.
![screenshot_1508094813](https://user-images.githubusercontent.com/17544746/31588165-cc500140-b20b-11e7-9aa9-a9f5f3645dfe.png)

However, `navigator.showModal({...})` works perfectly. (Working example below)
`componentDidMount() {`
    `const {navigator} = this.props;`
    `navigator.showModal({`
        `screen: 'Login',`
        `animationType: 'slide-up',`
        `passProps: {`
           `logIn: this.logIn`
         `}`
    `});`
`}`

**Note: Am facing same issue for `navigator.toggleDrawer({ to: 'closed' });` also.**

---
### Environment
* React Native Navigation version: ^1.1.237
* React Native version: 0.49.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): AVD Simulator(Nexus 5X API-21)

**Comment by IamDhana** [comment]
+1, I am also facing the same issue, Kindly help

**Comment by hamxabaig** [comment]
@Kukhapprabu @IamDhana You need to have `side` key too in the object that you're passing to `setDrawerEnabled`. Check out the documentation 
https://wix.github.io/react-native-navigation/#/screen-api?id=setdrawerenabledparams-
```
this.props.navigator.setDrawerEnabled({
  side: 'left', // the side of the drawer since you can have two, 'left' / 'right'
  enabled: false // should the drawer be enabled or disabled (locked closed)
});
```
If you don't pass `side` it'll get null in Java thats why the exception. Hope it helps.

**Comment by Kukhapprabu-Gladminds** [comment]
@hamxabaig, Thanks for your help. I have misunderstood optional params and considered as params will have default behaviour if left undeclared.

**Comment by Kukhapprabu** [comment]
@hamxabaig Thanks for your help, it works perfectly. I have misunderstood optional params and considered as params will have default behaviour if left undeclared.

**Comment by NitinAK** [comment]
> @Kukhapprabu @IamDhana You need to have `side` key too in the object that you're passing to `setDrawerEnabled`. Check out the documentation
> https://wix.github.io/react-native-navigation/#/screen-api?id=setdrawerenabledparams-
> 
> ```
> this.props.navigator.setDrawerEnabled({
>   side: 'left', // the side of the drawer since you can have two, 'left' / 'right'
>   enabled: false // should the drawer be enabled or disabled (locked closed)
> });
> ```
> If you don't pass `side` it'll get null in Java thats why the exception. Hope it helps.

how to declare this side in setDrawerEnabled
