### ISSUE TITLE
navBarCustomView does not change on setStyle

### ISSUE THREAD

**Issue by gokulkulkarni1987** [wix/react-native-navigation#2022]
### Issue Description

We are trying to change the navBar when a component loads. But it does not change.

### Steps to Reproduce / Code Snippets / Screenshots

We are using the following code, in the first component,
```
this.props.navigator.setStyle({
      navBarCustomView: 'app.NewTopBar',
      navBarComponentAlignment: 'center',
      navBarCustomViewInitialProps: { title: 'Hi Custom' }
    });
```
In the second component have the following code,
```
this.props.navigator.setStyle({
      navBarCustomView: 'app.NewTopBar1',
      navBarComponentAlignment: 'center',
      navBarCustomViewInitialProps: { title: 'Hi Custom' }
    });
```

---
### Environment
* React Native Navigation version: ^1.1.198
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by gokulkulkarni1987** [comment]
I have observed one more things, if I do the following thing,
```
this.props.navigator.setStyle({
      navBarCustomView: 'app.NewTopBar2',
      navBarComponentAlignment: 'center',
      navBarBackgroundColor: '#808080'
      navBarCustomViewInitialProps: { title: 'Hi Custom' }
    });
```
It does change the color, but the top bar does not change. :(

**Comment by nimerfarahty** [comment]
you have to explicitly set the component width

**Comment by gokulkulkarni1987** [comment]
@nimerfarahty no its not helping :(

**Comment by gaultierq** [comment]
Any insights on this issue ?

**Comment by gaultierq** [comment]
Related : how can I remove a navBarCustomView ? 
use case: when search field is cleared, I want to remove the search field, which is a navBarCustomView.

**Comment by brunolemos** [comment]
My experience with wix navigation has not been smooth at all, dammit :( 

Any workaround for this issue?

**Comment by GedoonS** [comment]
Running into the same issue. Like I can log that setStyle is being called with the specific style, but regardless it's being ignored when using modal view on Android. I guess I need to switch to slapping the navBarCustomViews there manually and just hide the framework navigator because it's so inconsistent.

**Comment by CoderXpert** [comment]
Running into similar kind of issue, I want to change color of nav bar and on scrolling, but this looks like 
`this.props.navigator.setStyle` is not working properly.
```
this.props.navigator.setStyle({
  navBarBackgroundColor: 'blue'
});
```

**Comment by reinvanimschoot** [comment]
Same problem, is there any workaround?

**Comment by terreb** [comment]
Any updates?

**Comment by gmisa** [comment]
any updates on this?  In my case i need to update navBarCustomViewInitialProps on the custom view.  Calling setStyle doesn't do anything.

**Comment by guruparan** [comment]
Any updates on this issue ?, i have the same problem , the color changes but the properties are not updated
