### ISSUE TITLE
[Urgent request] Support different kinds of sidebar menu

### ISSUE THREAD

**Issue by meow0703** [wix/react-native-navigation#2023]
RCCTheSideBarManagerViewController
RCCDrawerController
Hi team,
We noticed that you already supported 2 kinds of SidebarMenu for iOS native code. Would you please provide us an example RCCTheSideBarManagerViewController ?
Regards

**Comment by guyca** [comment]
Hey @meow0703 
We actually want to support a single side menu type, and eventually expose an interface which will allow users to provide their own side menu implementations.
Hope this answers your question :)
