### ISSUE TITLE
Fab button left side

### ISSUE THREAD

**Issue by gusilveiramp** [wix/react-native-navigation#2024]
Hi, is it possible to position the FAB button on the left side of the screen?
Also, I wonder if it is possible to do some kind of hover effect when clicking on it.

**Comment by guyca** [comment]
Hey there
Why would you want to have the fab on the left side of the screen? Is it for RTL support?

Not sure what hover effect you'r talking about :)

**Comment by gusilveiramp** [comment]
Hi, thanks for the quick reply. The App already uses 2 buttons on the right to execute the main actions of it. The only place I can insert the fab is on the left as it is secondary in the application, but still very important. The client requires me to insert it on the left and really makes perfect sense in this application we are developing.

The hover effect is just a white glow that will light up quickly when you click the button. I do not know if I can call this hover effect. I just like to make it turn white and then go back to its black color slowly after clicking it. It's possible?

**Comment by gusilveiramp** [comment]
Hi, thanks for the quick reply. The App already uses 2 buttons on the right to execute the main actions of it. The only place I can insert the fab is on the left as it is secondary in the application, but still very important. The client requires me to insert it on the left and really makes perfect sense in this application we are developing.

About the hover effect, I expressed myself poorly. The name is Ripple effect.
Can you help me?

**Comment by guyca** [comment]
I think you're referring to the [ripple effect](http://4.bp.blogspot.com/-7OPWAPg50gI/VlHY4aYu4ZI/AAAAAAAABi4/foHpDOukI_8/s1600/Android_Ripple_effect_button_edt.png). At any case, we probably won't support this as it's against material design guidelines.

**Comment by sijad** [comment]
@guyca can I send a PR for this? it seems an easy task, we need this feature because our application is RTL.

**Comment by guyca** [comment]
@sijad Sure, ping me when you do 👍
