### ISSUE TITLE
How to know when screen transition is finished?

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#2025]
### Issue Description
Is there way to know when for example `push` or `pop` animation has finished? So I could run code after the transition has finished?

---
### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by guyca** [comment]
It just occurred to me the [documentation](https://wix.github.io/react-native-navigation/#/screen-api?id=listen-visibility-events-in-onnavigatorevent-handler) doesn't mention this.
On Android, `didAppear` and `didDisappear` are called after the `push` or `pop` animations end. I'm fairly certain the same applies to iOS.

**Comment by henrikra** [comment]
Yeah but what if I want to fire some action after successful api request AND when the screen will disappear? Because I dont want to fire action always when the screen has disappeared. Only when both conditions are met :)

**Comment by guyca** [comment]
Seems like this isn't the screen's concern. If you have actions which depend on screen state, you can update the store in `didAppear` and `didDisappear` and take it from there.
hope this helps.
