### ISSUE TITLE
Error in doc for tabFontFamily parameter

### ISSUE THREAD

**Issue by jay1337** [wix/react-native-navigation#2026]
This doc contains an error : http://wix.github.io/react-native-navigation/#/styling-the-tab-bar?id=style-object-format

The `tabFontFamily` for Android in `appStyle` object must not include the file extension (`ttf ` or `otf`) since it is automatically added by RNN here: https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/utils/TypefaceLoader.java#L43-L49

**Comment by guyca** [comment]
Nice catch. Can you please submit a PR for the [docs](https://github.com/wix/react-native-navigation/tree/master/docs)?

**Comment by jay1337** [comment]
@guyca Done !
