### ISSUE TITLE
Not locked to orientation "portrait" on Android

### ISSUE THREAD

**Issue by koansang** [wix/react-native-navigation#2027]
### Issue Description
 - Not locked to orientation "portrait" on Android

### Steps to Reproduce / Code Snippets / Screenshots

- I'm write this:
 ```xml
//android/app/src/main/AndroidMainfest.xml
  <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>
```

---
### Environment
* React Native Navigation version: 1.1.236
* React Native version: 0.49.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Galaxy s7, V20

**Comment by guyca** [comment]
Hey there
Use `orientation: 'portrait'` in `appStyle`
https://wix.github.io/react-native-navigation/#/top-level-api

**Comment by zsajjad** [comment]
@guyca this one also not working ...

**Comment by linuxgg** [comment]
> https://wix.github.io/react-native-navigation/#/top-level-api

doc is 404

**Comment by linuxgg** [comment]
refer here:
https://wix.github.io/react-native-navigation/#/docs/options-migration?id=orientation
