### ISSUE TITLE
How to disable back swipe on iOS?

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#2028]
If I want to disable back swipe gesture on iOS what I have to config?

**Comment by henrikra** [comment]
Damn I already found it. It is `disabledBackGesture` which can be found here https://github.com/wix/react-native-navigation/blob/9cb53a7175ca8364d19ba02090ed9d671f6d7724/docs/styling-the-navigator.md

**Comment by rh389** [comment]
Just in case this has anyone else banging their head against a macbook - note that (weirdly IMO) it's disable*d* (with a d) not disable.

**Comment by DavitVosk** [comment]
@henrikra Thanks for your answer. And what about for app's all screens? As I understand `disabledBackGesture` is for single screen. Thanks in advance
