### ISSUE TITLE
Attempt to invoke virtual method 'void com.reactnativenavigation.animation.VisibilityAnimator.setVisible(boolean, boolean)' on a null object reference

### ISSUE THREAD

**Issue by nikhilag** [wix/react-native-navigation#2029]
This bug only shows up in the release version of the Android app.

Attempt to invoke virtual method 'void com.reactnativenavigation.animation.VisibilityAnimator.setVisible(boolean, boolean)' on a null object reference

Here's the full stack trace:-
com.reactnativenavigation.views.TopBar.setVisible (TopBar.java:264)
com.reactnativenavigation.screens.Screen.setTopBarVisible (Screen.java:227)
com.reactnativenavigation.screens.ScreenStack$8.run (ScreenStack.java:286)
com.reactnativenavigation.screens.ScreenStack$8.run (ScreenStack.java:283)
com.reactnativenavigation.screens.ScreenStack.performOnScreen (ScreenStack.java:410)
com.reactnativenavigation.screens.ScreenStack.setScreenTopBarVisible (ScreenStack.java:283)
com.reactnativenavigation.layouts.SingleScreenLayout.setTopBarVisible (SingleScreenLayout.java:175)
com.reactnativenavigation.controllers.NavigationActivity.setTopBarVisible (NavigationActivity.java:265)
com.reactnativenavigation.controllers.NavigationCommandsHandler$5.run (NavigationCommandsHandler.java:119)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5417)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)

Could this have something to do with proguard? In my developer version, this error never shows up.

I think similar to BottomTabs.setVisibility(), the fix in TopBar.setVisible() should be:-

```
public void setVisible(boolean visible, boolean animate) {
  if (visibilityAnimator != null) {
    visibilityAnimator.setVisible(visible, animate);
  } else {
    titleBar.setVisibility(!visible);
  }
}
```

**Comment by nikhilag** [comment]
Could this have something to do with proguard? In my developer version, this error never shows up.

**Comment by gongmingqm10** [comment]
I encountered this crash issues too. It only shows up the first time I run the App.

The version I used:

```
"react-native-navigation": "^1.1.367",
"react-native": "0.50.4",
```

Tested in Android 7.1.1

**Comment by gongmingqm10** [comment]
@nikhilag  After some investigation. I found the root cause for my case is that I used the following code:

```
class EulaScreen extends React.Component {
   constructor(props) {
      super(props)
      this.props.navigator.toggleNavBar({
        to: 'hidden',
      })
  }
}
```

After  I change the usage of `toggleNavBar` to `setStyle`, everything works.

```
  constructor(props) {
    super(props)
    this.props.navigator.setStyle({
      navBarHidden: true,
    })
  }
```

I think either put the `toggleNavBar` inside the componentWillMount method or use the `setStyle` to toggle off the navBar.

**Comment by nikhilag** [comment]
Thanks @gongmingqm10 ! But in my case, I used `toggleNavBar` always inside `componentWillMount()`.
