### ISSUE TITLE
Push notification data on cold launch not passed to activity

### ISSUE THREAD

**Issue by MattDavies** [wix/react-native-navigation#203]
Hi guys,

Most push notification libraries for React Native appear to work by sending the data payload of the notification to the intent against the main application activity when the app is cold launched.

When using react-native-navigation, it appears as though the only information present in the bundle for the current activity is parameters for react-native-navigation (it's missing the data parameter I'd expect to see - not sure if it's overridden or just never passed).

Are you guys using push notifications at wix (on Android) - if so I was just curious as to whether or not you found a way to solve this.

Thanks!

**Comment by guyca** [comment]
@amitdwix You have the most with push notifications. Can you publish a gist maybe?

**Comment by MattDavies** [comment]
(This is 2.0 branch based, but applicable to 1.x's architecture too):

If I move the launch intent-filter matching the push notification to react-native-navigation's AndroidManifest.xml rather than my own, I can see the correct bundle extras in NavigationActivity,java in onCreate(). The problem is NavigationActivtity starts the react context (at which point the intent's extras are lost) and I cant see a way to pass any parameters into the react context. JS then starts up an activity for the app itself, which has just react-native-navigation params.

The nice solution would be figuring out how to pass through the intent extras params to the react context so it can pass them back through when JS starts an activity. I'm not really sure how else to prevent them being lost.

**Comment by MattDavies** [comment]
Found a way to pass the intent through (ugly, but workable for the moment). Closing this :)

**Comment by explorigin** [comment]
@MattDavies Can you share for the rest of us please?

**Comment by MattDavies** [comment]
Hey @explorigin, the diff for what I did was here:

https://github.com/MattDavies/react-native-navigation/commit/ac693a3e4d447510f870ce033f9a6b01ef038539

It's *really* nasty, but maybe someone can use it to come up with a cleaner solution. I had two goals:

1) Using hybrid push notifications (with notification and data payloads) because we liked the user experience on our particular application.
2) Support cold launches (app killed) and background launches when the push notification is touched in the tray, and support immediate updates if the app was already open.

**Comment by explorigin** [comment]
Thanks, I'm trying to expand my horizons into Android and I foresee running into the same issue. Every little bit helps.  Thanks
