### ISSUE TITLE
reload debug crash

### ISSUE THREAD

**Issue by mingkang1993** [wix/react-native-navigation#2030]
1 java.util.Stack.peek(Stack.java:57)
java.util.EmptyStackException

--
2 com.reactnativenavigation.screens.ScreenStack.peek(ScreenStack.java:233)
3 com.reactnativenavigation.layouts.BottomTabsLayout.sendTabReselectedEventToJs(BottomTabsLayout.java:393)
4 com.reactnativenavigation.layouts.BottomTabsLayout.onTabSelected(BottomTabsLayout.java:363)
5 com.aurelhubert.ahbottomnavigation.AHBottomNavigation.updateSmallItems(AHBottomNavigation.java:722)
6 com.aurelhubert.ahbottomnavigation.AHBottomNavigation.access$100(AHBottomNavigation.java:52)
7 com.aurelhubert.ahbottomnavigation.AHBottomNavigation$3.onClick(AHBottomNavigation.java:561)

**Comment by brunolemos** [comment]
This fixes it: #1836

**Comment by mobitar** [comment]
The fix above is only for iOS. This crash in particular is an Android/Java crash.

**Comment by brunolemos** [comment]
True.
