### ISSUE TITLE
Android statusbar transparent not working

### ISSUE THREAD

**Issue by viper4595** [wix/react-native-navigation#2034]
### Issue Description

Hi, i'm trying to set statusbar to transparent on Android. 
It's ok when starting SingleScreenApp or TabBaseApp, but when i'm changing from SingleScreen to TabBase, the status bar not transparent anymore.

### Steps to Reproduce / Code Snippets / Screenshots

![Imge](https://media.giphy.com/media/26Ffj0P6Btp0nwH4I/giphy.gif)

* My code

```
// SingleScreen
Navigation.startSingleScreenApp({
	screen: {
		screen: 'LoginScreen',
		navigatorStyle: { navBarHidden: true},
	}
});
```

```
// TabBaseApp
Navigation.startTabBasedApp({
    tabs: 
        [{
		label: 'Home',
		// ...
		navigatorStyle: {
			navBarHidden: true,
			drawUnderNavBar: true,
			navBarTranslucent: true
			navBarTransparent: true,
			statusBarColor: 'transparent',	
		},// ...],
               //...
```
```
// Login Screen
<MyScreen>
    <StatusBar 
          barStyle='dark-content'
          translucent={true}   
          backgroundColor={'transparent'} />
</MyScreen>
```
### Environment
* React Native Navigation version: ^1.1.219
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): ANDROID
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator-6.0-Debug-

**Comment by linnett** [comment]
Also doesn't work for me
