### ISSUE TITLE
SVG icons in tabBar navigation ?

### ISSUE THREAD

**Issue by setelemed** [wix/react-native-navigation#2035]
### Issue Description

Hi!

Has anyone had luck using SVG icons in tabBar navigation  ?

I added react-native-svg but cant seem to get the SVG icons to play. I get red screen, with errormessage like: 

`Image source icon.svg size {32, 32} does not match loaded image size {0, 0}`

I checked the SVG file and dimensions are set:

```
<svg 
enable-background="new 0 0 50 50" 
width="50px" 
height="50px" 
version="1.1" 
viewBox="0 0 50 50" 
xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.x
* React Native version: 0.49.2
* Platform(s) (iOS, Android, or both?): iOS + Android
* Device info (Simulator/Device? OS version? Debug/Release?): Development on Mac, iOS 11.0 simulator

**Comment by ziyafenn** [comment]
I just came here for this quiestion. @setelemed  you can use `react-native-svg-uri` for easire use of svg files in RN. But i also would like to know how could use it together with react-native-svg-uri

**Comment by nolan-m** [comment]
See https://github.com/wix/react-native-navigation/issues/43

Plenty of examples there using react-native-vector-icons.

**Comment by pqkluan** [comment]
The current Tab Bar API only take image assets as icons. That means you have to convert the icon resource into a bitmap image before call `startTabBasedApp`. 

In `react-native-vector-icons` case, there is [Icon.getImageSource](https://github.com/oblador/react-native-vector-icons#usage-as-png-imagesource-object) function ([read more](https://wix.github.io/react-native-navigation/#/third-party-libraries-support?id=react-native-vector-icons)).

If you are using others SVG library, all you need is to find a similar function to convert SVG to the bitmap image, and I think such feature is out of this library scope so I'll close this issue for now. Feel free to re-open this if needed :)
