### ISSUE TITLE
When I call startTabBasedApp method twice，The BottomTab's Color is Red

### ISSUE THREAD

**Issue by a6051529** [wix/react-native-navigation#2037]
### Issue Description

When I call startTabBasedApp method, The BottomTab's Color is Red(I want to be gray)。 How to resolve this problem? 

### Steps to Reproduce / Code Snippets / Screenshots

1. When App is start, I call startSingleScreenApp method go to Login Screen
2. When User is Login, I call startTabBasedApp method go to Tabbar Screen。
3. When  User press logout button, I call startSingleScreenApp method go to Login Screen。
4. When User is Login again,  I call startTabBasedApp method again, Now the BottomTab's Color is Red                     

This is ScreenShots:
![599a5ce9c0ed59828f7546c1e184023e](https://user-images.githubusercontent.com/7309118/31721679-a6c51aca-b3df-11e7-8b36-751578205f0a.png)
![c5f24c00cad140f6544e92509f792407](https://user-images.githubusercontent.com/7309118/31721681-a708c13a-b3df-11e7-8357-76a40c5e322b.png)

---
### Environment
* React Native Navigation version: 1.1.205
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):  Device: LG G4, OS version: Android 5.1, Release.

**Comment by viper4595** [comment]
Do you  set tabBarSelectedButtonColor to your app style?

```
Navigation.startTabBaseApp({
    tabs: [//...],
    appStyle: { tabBarSelectedButtonColor: 'gray' }
})
```

**Comment by a6051529** [comment]
@viper4595  Yes, This is my code:

### A file:
```
export const tabbarConfigs = {  
    tabs: [   
        {....}, 
        {....}, 
        {....}, 
        {....}
    ],appStyle: {
        forceTitlesDisplay: true,
        tabBarSelectedButtonColor: '#505c68',
        tabBarButtonColor: '#ccd1d4'
    },
    tabsStyle: {
        tabBarSelectedButtonColor: '#486370',
        navBarBackgroundColor: '#486370',
        forceTitlesDisplay: true,
        collapsingToolBarCollapsedColor: '#486370'
    }
}
```

### B file:
```
import { tabbarConfigs } from './A'

Navigation.startTabBasedApp(tabbarConfigs);
```

When I first call startTabBasedApp method , The bottomTab's color is right.       
When I call startTabBasedApp method again, The bottomTab's color is weird.

**Comment by sytolk** [comment]
I can't repeat this issue. @a6051529  can you publish in GitHub example project with this issue ?

**Comment by a6051529** [comment]
@sytolk  I see, It is my problem,  when I use "import" the tabbarConfigs, The tabbarConfigs variable is Immutable。When I call startTabBasedApp method again， The bottomTab's color is weird. 
Thanks! @sytolk @viper4595
