### ISSUE TITLE
Does V2.0 support android by now?

### ISSUE THREAD

**Issue by winglight** [wix/react-native-navigation#204]
I tried to run android after building ios successfully and on the real device app was always throwing errors even with the  example app. Errors as followed:
`didn't find class com.facebook.jni.iteratorhelper`
After google it, I found the most errors mentioned RN's bug but that's solved since v0.30.0. So is it a bug or any other hacks?

**Comment by MattDavies** [comment]
@winglight If you're running the latest RN, you still need to apply this change manually for now:

https://github.com/wix/react-native-navigation/pull/145/files

It's worth keeping in mind that this project isn't officially supporting higher than 0.25.1 yet. There's more detail on that pull request thread.

**Comment by winglight** [comment]
Many thanks for your reply! But I can't find the java file you mentioned(android/app/src/main/java/com/reactnativenavigation/core/RctManager.java), and there isn't the "core" folder and RctManager.java either.
My dependency of navigation is 2.0.0-experimental.61.

**Comment by MattDavies** [comment]
It moved in the 2.0 branch:

https://github.com/MattDavies/react-native-navigation/commit/d505550c6d3bfd947af8c8b53de6d0500a113de9

**Comment by guyca** [comment]
Thanks @MattDavies
