### ISSUE TITLE
How to detect when drawer open/close event?

### ISSUE THREAD

**Issue by cosivox** [wix/react-native-navigation#2046]
I would like to know how to detect if the drawer has been opened or closed even if it was by gesture (swiping). I've already tried with visibility events without any luck. I also took a look at global visibility events in documentation but I don't know exactly how and where I need to put that code, also don't know if it is going to work for this case.

* React Native Navigation version: 1.1.236
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): BOTH

**Comment by chmac** [comment]
Looks like these don’t exist #1545
