### ISSUE TITLE
Android has white Screen before app render

### ISSUE THREAD

**Issue by sunny635533** [wix/react-native-navigation#2047]
Android has white Screen before app render.I tried override createSplashLayout(),it still here.

---
### Environment
* React Native Navigation version: 1.1.242
* React Native version: 0.49.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by reyalpsirc** [comment]
Same thing here also with react native 0.49.3

**Comment by sunny635533** [comment]
@reyalpsirc yes,i found it with rn-0.49.3

**Comment by reyalpsirc** [comment]
@sunny635533 Please check if my solution at [https://github.com/wix/react-native-navigation/issues/14#issuecomment-344564151](https://github.com/wix/react-native-navigation/issues/14#issuecomment-344564151) works for you

**Comment by sunny635533** [comment]
@reyalpsirc  I tried your solution  in Android.Though i couldn't see the blank screen,it has a bit weird in user behavior

**Comment by reyalpsirc** [comment]
@sunny635533 What kind of issue? Something like an Image scaling during the calls to `startSingleScreenApp` ?

**Comment by ofirdagan** [comment]
The same happened for me. The problem was an error was thrown inside the `Navigation.startTabBasedApp` or `Navigation.startSingleScrrenApp` and it was swollen so I didn't know it ever happened. 
I fixed it in this PR:

https://github.com/wix/react-native-navigation/pull/2556

**Comment by guyca** [comment]
Thanks @ofirdagan 👍
