### ISSUE TITLE
v2.0 Navigation.registerScreen

### ISSUE THREAD

**Issue by explorigin** [wix/react-native-navigation#205]
In < 2.0, I was using `Navigation.registerScreen` because `registerComponent` is not flexible enough for me.  I see that it's no longer exposed in 2.0.  Can we re-expose it?

My use-case is that I'm adding both a redux store and a translation object to the React context.  In case you're curious, it looks like this:

```
function registerWrappedComponent(screenID, generator) {
    const generatorWrapper = () => {
        const InternalComponent = generator();
        return class extends Screen {
            static navigatorStyle = InternalComponent.navigatorStyle || {};
            static navigatorButtons = InternalComponent.navigatorButtons || {};
            render() {
                return (
                    <SuperProvider store={store} i18n={i18n}>
                        <InternalComponent navigator={this.navigator} {...this.props} />
                    </SuperProvider>
                );
            }
        };
    };
    Navigation.registerScreen(screenID, generatorWrapper);
    return generatorWrapper;
}
```

**Comment by explorigin** [comment]
I'm working through this.  Merely exposing it is not good enough.  Currently getting a message:

> Super expression must either be null or a function, not undefined.

**Comment by explorigin** [comment]
Got it sorted.  If you want this to be part of the final API, I did it like this: https://github.com/wix/react-native-navigation/compare/v2.0...twistle:v2.0

My register wrapper function ends up looking like: 

```
function registerWrappedComponent(screenID, generator) {
    const generatorWrapper = () => {
        const InternalComponent = generator();
        return class extends Screen {
            static navigatorStyle = InternalComponent.navigatorStyle || {};
            static navigatorButtons = InternalComponent.navigatorButtons || {};
            constructor(props) {
                super(props);

                this.allProps = {
                    ...props,
                    ...PropRegistry.load(props.screenInstanceID),
                };
            }

            render() {
                return (
                    <SuperProvider store={store} i18n={i18n}>
                        <InternalComponent navigator={this.navigator} {...this.allProps} />
                    </SuperProvider>
                );
            }
        };
    };
    Navigation.registerScreen(screenID, generatorWrapper);
    return generatorWrapper;
}
```

**Comment by smooJitter** [comment]
I'm anticipating the same problem.  In addition to the language api, I'm going with.
<ApolloProvider client={client}  store={store}/>.

I've always thought tucking away redux provider was constraining.  

I plan to use your solution. Thanks. 

Neverless, perhaps there should be a way to configure the redux provider without tampering with package files.  I'm not sure how that will work

**Comment by DanielZlotin** [comment]
I agree @smooJitter . I think changing the API to require a factory method instead of a screenID would be better, and MUCH more flexible (instead me creating the Screen, you create it for me - the way you want).
