### ISSUE TITLE
dismissLightBox  is not working

### ISSUE THREAD

**Issue by yagneshmodh** [wix/react-native-navigation#2055]
### Issue Description

getting following error while dismiss the Lightbox

<img width="566" alt="screenshot 2017-10-22 13 08 15" src="https://user-images.githubusercontent.com/9801499/31859496-8b0709d0-b72a-11e7-91b6-060d504d805f.png">

I have attached the code for same below.

### Steps to Reproduce / Code Snippets / Screenshots

```
  sortProperties() {
    this.props.navigator.showLightBox({
      screen: 'krooqi.Search.SortModal',
      passProps: {
        selectedValue: this.state.selectedValue,
        onSelect: this.selectSortData,
        sortData,
      },
      style: {
        backgroundBlur: 'dark',
        tapBackgroundToDismiss: true,
      },
    });
  }

  selectSortData(data) {
    this.props.navigator.dismissLightBox();
    this.setState({ selectedValue: data });
  }
```

---
### Environment
* React Native Navigation version: 1.1.236
* React Native version: 0.49.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Genymotion

**Comment by TimoGlastra** [comment]
This is a bug in RNN at the moment. To make it work you have to manually change a line. See the fix [here](https://github.com/wix/react-native-navigation/issues/1502#issuecomment-325946177). It is not a nice fix, but it works

**Comment by pqkluan** [comment]
Close this issue due to duplicate with #1502
