### ISSUE TITLE
How can I let my users select colors

### ISSUE THREAD

**Issue by ODelibalta** [wix/react-native-navigation#2058]
Hello all, 

As it stands, I have an appStyle.js file that contains objects like navBarStyle with all the navbar properties. That file gets imported to my screens. navBarStyle is nothing but a plain JS object. Style.js is pretty much a collection of objects that gets exported. 

I want to be able to let my users select things like navbar color etc. So far, I have set up the page with color pickers etc and I've wired the actions through redux and whatever they select gets put into a store property. 

Am I looking at this all wrong? I have this suspicion that this is not the way to approach it at all given that so far it is not working. Anybody has or seen a repo with theme color picker functionality so I can look through the code? I'd love to see an example. It has to be there I can not be the only one who needed this :) 

I am not sure how to label this topic. I realize it is not an issue exactly but I've already asked this in the discord channel and got nothing. Thank you !

**Comment by guyca** [comment]
If you're using appStyle to theme your app (which you should) - then I suggest you restart the app after changes since appStyle is parsed once when the app is loaded.
