### ISSUE TITLE
Not work with "react-native-facebook-account-kit"

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#2059]
Dear all,
I'm using "react-native-facebook-account-kit" for verifying phone number. However, "react-native-navigation" cannot work with "react-native-facebook-account-kit" because of
- I found that "react-native-facebook-account-kit" use 
"UIViewController *rootViewController = [UIApplication sharedApplication].delegate.window.rootViewController;
[rootViewController presentViewController:viewController animated:YES completion:NULL];"
 to present the view controller
However, 'react-native-navigation' controlled their route stack inside
Any idea to work around it?

**Comment by tranhuuthinhit** [comment]
The same problem. But I'm using `react-native-facebook-login`

**Comment by amorino** [comment]
Any solution on this?
