### ISSUE TITLE
android hardware back button and tabbar

### ISSUE THREAD

**Issue by jrryhrtn** [wix/react-native-navigation#2061]
### Issue Description

After switching between several tabs in the tabbar, androids hardware back button exists application vs going back to previous selected tabs.

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

After creating a simple application using "StartTabbarApplication", then running in a Android emulator.  The hardware back button exists the application vs going back to a previously selected tab.  I test only after selecting several tabs from the tabbar.

[FILL THIS OUT - It will be extremely helpful]
![screen shot 2017-10-23 at 9 14 21 am](https://user-images.githubusercontent.com/5680239/31893964-9a82a7ea-b7d2-11e7-9e1c-6283466fd390.png)

After selecting each tab, one at a time (see screen shot), then selecting the hardware back button the application exits to the home screen.  I believe the default native behavior is to go back to the previously selected tab.

---
### Environment
* React Native Navigation version: 1.1.250
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Nexus-5X-API-26

**Comment by MSSPL-PiyaleeMaiti** [comment]
Here also same problem occur, can anyone give us solution for this problem.
hardwareBackHandler is not working in tabbar-navigation.

**Comment by kyryloz** [comment]
You can override back button press.
For your tab screens set:

```javascript
 tabs: [
    {
      screen: 'com.yourscreen',
      title: 'Title',
      label: 'Label',
      icon: <icon>,
      overrideBackPress: true, // <--- here is what you need
    },
... other screens go here
```
Than in your tab's screen component:

```javascript
navigator.setOnNavigatorEvent(event => {
    if (event.id === 'backPress') {
      const tabIndex = 0 // tab index you want return to
      navigator.switchToTab({ tabIndex })
    }
  })
```
So, you can customize your tab behavior on tabs. For instance, in my app I just go to `tabIndex: 0` for all other tabs expect 1st. If you want 'history' experience than you should retain stack of tab changes, I think, you can achieve this by subscribing to tab changing event. Unfortunately, can't give an example of this.

**Comment by alandmonte** [comment]
I'm not able to get the onPress event for left nav back button on the main tabs. Any idea how to get it?
