### ISSUE TITLE
Global navigatorStyle doesn't work

### ISSUE THREAD

**Issue by ziyafenn** [wix/react-native-navigation#2063]
### Issue Description

So, i have set a separate file **nav.js** where i run my` Navigation.startTabBasedApp` and it's corresponding styles. Everything works perfectly with tabs and their styles.

There in **nav.js** i also added  `const navigatorStyle = { ... };`  and tried also as a styles, `navigatorStyle: { ... }` and absolutely nothing happens.

I also have tried to add `const navigatorStyle = { ... };` to app.js, nothing happens either.

Though, using `this.props.navigator.setStyle`on a separate screen works perfectly.

Any ideas why it could be? 

I've attached an example of **nav.js**
![screenshot 2017-10-23 20 08 18](https://user-images.githubusercontent.com/314302/31905304-feb7850e-b82d-11e7-9147-5773e59d18c1.png)

Thanks.
---
### Environment
* React Native Navigation version: 1.1.243
* React Native version: 0.47.0 
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
Hey there,
The property you're looking for is called `appStyle` https://wix.github.io/react-native-navigation/#/top-level-api?id=starttabbasedappparams
Also note that `tabStyle` is deprecated on Android, just add all tab properties to `appStyle`
