### ISSUE TITLE
Custom navbar left component button not rendering on iOS

### ISSUE THREAD

**Issue by aidenwallis** [wix/react-native-navigation#2064]
### Issue Description

I have tried to implement a custom `navigatorButtons.leftButtons` component to allow me to render out the users' avatar from the backend CDN that we have. And upon doing so I wasn't able to get it to display, or by the looks of it even render, as leaving a small console log in the component doesn't seem to work either.

This is a tab based app, and through looking at the various issues raised with similar topics on here, it looks as if this doesn't seem to be an issue for `singleScreenApp`'s.

As a few bugging steps I've tried:-

Is it *actually* registered? Yes. You can see it here
![image](https://user-images.githubusercontent.com/12055114/31906914-3cc0b306-b82a-11e7-9ee7-68fa9b06b01f.png)
(As `app.userHeaderButton`).

The component was literally copied/pasted off of the docs to ensure I 100% just hadn't done something stupid myself, you can see the component here:-
![image](https://user-images.githubusercontent.com/12055114/31906985-74897df4-b82a-11e7-853b-cc1e08bd9d69.png)

I tried mounting this directly on the component here - 
![image](https://user-images.githubusercontent.com/12055114/31907081-adbede98-b82a-11e7-8a1e-2544d6dc4dc7.png)

### Steps to Reproduce / Code Snippets / Screenshots

Hopefully the above explains this - if you want the exact part of the docs I referenced, you can see it [here](https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=custom-navigation-buttons).

Thanks! 

---
### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.46.4
* React version: 16.0.0-alpha.12
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 7 Sim on xcode, iOS 11.0

**Comment by eliperkins** [comment]
Ensure that you don't set a `title` property as part of your object in `leftButtons`. [`title` will take precedence over `component`](https://github.com/wix/react-native-navigation/blob/c62d944c2b10a841e531c05b45f88f18f902042a/ios/RCCNavigationController.m#L357)

**Comment by SebastianDaehnrich** [comment]
same problem here. the button is not rendered
react": "16.0.0-alpha.6
react-native": "0.44.0
react-native-navigation": "1.1.84
Platform(s) (iOS, Android, or both?): iOS

**Comment by eliperkins** [comment]
@SebastianDaehnrich Can you post some example code to illustrate your issue? From my diagnosis, the original issue should be resolved by removing the `title` attribute, as noted here: https://github.com/wix/react-native-navigation/issues/2064#issuecomment-339131984

Without seeing your code, it's not possible to diagnose this issue further.

**Comment by adnanaliarshad** [comment]
@SebastianDaehnrich did you find any solution? I am facing same issue and removing title attribute ain't helping either.

**Comment by eliperkins** [comment]
@adnanaliarshad Do you have some example code to illustrate your issue? It would help us a bunch if you could share an example project, or even just a gist, that reproduces this for us.
