### ISSUE TITLE
V1 is it possible to switch root tab navigators 

### ISSUE THREAD

**Issue by maitham1** [wix/react-native-navigation#2066]
### Issue Description

Hey guys, awesome work with the native navigation. I just wanted ask is it possible in v1 to switch the root tab navigator, i.e very similar to the way airbnb have split their app into hosting and travelling.  So the user clicks a button in the initial tab root, he is then shown a loading screen, behind the scenes the tab root is then reset and the user shown a new tab root. Is something like this possible? 

### Environment
* React Native Navigation version: V1 latest
* React Native version: 0.49.3
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Simulator Debug/Release?): Debug
1

**Comment by maitham1** [comment]
I had to navigat

**Comment by guyca** [comment]
I think [resetTo](https://wix.github.io/react-native-navigation/#/screen-api?id=resettoparams) is what your looking for. It resets a stack to a specific screen

**Comment by tedwong** [comment]
@guyca but can `resetTo` the tabbar?

**Comment by tedwong** [comment]
@maitham1  can u show me some sample code, I got the issue on `mount to another tab based app` ?
