### ISSUE TITLE
Bulk screen registration

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#207]
I have more than 100 screens spread across 5-7 modules. I Loki g for a more efficient way to load them all.  Perhaps looping over screen imports and then defining screenIds by combining the module name and import name.  Something along the line of,

import Screen1....
import Screen2...

ScreenImports.forEach( ( screen ) => {

   const screenId = ${moduleName}.list.${screen};

   Navigation.registerComponent( screenId, ( ) => screenImport );
});

In addition to making it easier to register many screens, such an approach can allow me to create structure of immutable screen definitions,

const screens = {
    screenId: { 
         screenId: ' ',
         compontent: { },
         children: [ {screen}...]
    ...
},
Now we can add this structure to redux and compose middleware thus supporting better redux integration.

**Comment by guyca** [comment]
You can always wrap `Navigation.registerComponent` and loop over your imported screens.
