### ISSUE TITLE
KeyboardAvoidingView broken (Major issue)

### ISSUE THREAD

**Issue by voidstarfire** [wix/react-native-navigation#2074]
Created basic example application
https://github.com/voidstarfire/KeyboardAvoidingView-React-native-navigation-bug

### Issue Description
When going from a screen that contains a ListView or ScrollView the the KeyboardAvoidingView is completely broken.
Provided two buttons to two different screens.

### Steps to Reproduce / Code Snippets / Screenshots
1. Go to scrollview screen
2. Go back and tap on the textinput field.
3. Broken padding

You can see that going to the textview screen instead of scrollview screen it works fine.

---
### Environment
* React Native Navigation version: ^1.1.253
* React Native version: 48.4
* Platform(s) (iOS, Android, or both?): Android, (Not tested iOS)
* Device info (Simulator/Device? OS version? Debug/Release?): Multiple devices and multiple simulators.

### Normal working screen from start & text screen
<img width="455" alt="screen shot 2017-10-25 at 10 25 38 am" src="https://user-images.githubusercontent.com/6940726/31988661-25cf9ac6-b970-11e7-9160-b8d573ec97cf.png">

### Broken screen when going from ScrollView screen.
<img width="454" alt="screen shot 2017-10-25 at 10 25 49 am" src="https://user-images.githubusercontent.com/6940726/31988662-25f45f96-b970-11e7-9752-af532e62636f.png">

**Comment by voidstarfire** [comment]
The library is unusable for me while this bug exists. :-/

**Comment by markedby** [comment]
I'm also facing this issue. Steps to reproduce are the same as @voidstarfire mentioned above: after navigating from some screen that contains FlatList of ScrollView KeyboardAvoidingView works in unexpected way.

React Native Navigation version: ^1.1.299
React Native version: 49.3
Platform(s): Android, (Not tested iOS)

**Comment by voidstarfire** [comment]
It seems like no issues are being looked at in this library. Shame cause it's the best navigation library by far!

**Comment by gvillenave** [comment]
Seeing the same issue, any ideas for a workaround?

**Comment by rcorrie** [comment]
I am experiencing this too. I added the following to my app's AndroidManifest.xml

```
<activity android:name="com.reactnativenavigation.controllers.NavigationActivity" android:windowSoftInputMode="adjustResize" />
```

Here is the weird part.... It doesn't work on a fresh install, only when I close the app and then relaunch it.

It definitely has something to do something with the NavigationActivity.

**Comment by chrmod** [comment]
@rcorrie thick with adding `NavigationActivity` worked fine in my project. Thanks for sharing.

**Comment by dsimushkin** [comment]
https://github.com/react-navigation/react-navigation/issues/721#issuecomment-383417050

**Comment by dsimushkin** [comment]
https://github.com/react-navigation/react-navigation/issues/721#issuecomment-383417050
