### ISSUE TITLE
[Bug - iOS] toggleTabs on screen hiding tabs throughout the app

### ISSUE THREAD

**Issue by ziyafenn** [wix/react-native-navigation#2075]
### Issue Description

I needed to hide the tabBar on a specific screen **(i.e. hiddenTabs.js)**, thanks to `toggleTabs`, it is pretty easy to do.
Although, except using only `toggleTabs` i need to also set `drawUnderTabBar` **and** `tabBarTranslucent` to _true_, otherwise i will get a white background in place of hidden tabs.

**Bug 1:**

The problem though, each time when i visit **hiddenTabs.js** and then go back to the previous screen, tabs will be hidden there as well as throughout the whole app. 

In android there is no such a problem, going back bring the tabs back to the screen.

**Bug 2:**

In the case of `tabBarTranslucent`, i believe it is a bug as well, as i don't need `tabBarTranslucent` being globally _true_, because it hides some of my content behind the tabs. 

I'm okay though having `tabBarTranslucent` set to _true_ on **hiddenTabs.js**, but neither `tabBarTranslucent` nor `drawUnderTabBar` doesn't work when you set them inside `this.props.navigator.setStyle` on that specific screen. Works only globally.

### Steps to Reproduce / Code Snippets / Screenshots

**hiddenTabs.js**
```
  this.props.navigator.toggleNavBar({
      to:'hidden',
      animated: false,
    });
```
**app.js**

```
appStyle: {
        drawUnderTabBar: true,
},
tabsStyle: {
        drawUnderTabBar: true,
}
```
---
### Environment
* React Native Navigation version: 1.1.243
* React Native version: 0.47.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 6

**Comment by shuaibird** [comment]
Have you already figured out how to fix it? I encounter the same issue.

**Comment by ziyafenn** [comment]
@shuaibird yeah i found a workaround.

Add this to the originating page (i.e. app.js):

```
constructor(props) {
    super(props);
    // if you want to listen on navigator events, set this up
    this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
}
```

```
 onNavigatorEvent(event) { // this is the onPress handler for the two buttons together
     if (event.type == 'ScreenChangedEvent') {
       if(event.id == 'willAppear') {
         this.props.navigator.toggleTabs({
           to: 'shown'
           animated: false // (optional)
         });
       }
     }
}
```

And on target screen you add this to `render()`:
```

this.props.navigator.toggleTabs({
    to: 'hidden', 
    animated: false
  });
```

That should hopefully help.
