### ISSUE TITLE
iOS push animation blinks obviously

### ISSUE THREAD

**Issue by Kerence** [wix/react-native-navigation#2078]
### Issue Description
iOS push animation blinks obviously if the major color of the foreground view is not white

1.open   ./src/screens/types/Push.js  and change styles.container.backgroundColor to '#f0fa'
2.run the iOS sample app 
see the video in the following link
[video](https://github.com/Kerence/videomaterial/blob/master/react-native-navigation-ios-push-blink.mp4)
if you are unable to download the video,download the zip directly
[zip archive](https://github.com/Kerence/videomaterial/archive/master.zip)
---
### Environment
* React Native Navigation version: 1.1.253
* React Native version: 0.45.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 7 Debug

**Comment by brunolemos** [comment]
Duplicated of #358

**Comment by hellomaya** [comment]
I observed it, and fix it by changing the code this way

https://github.com/tsfosnz/react-native-navigation-fix/tree/master

**Comment by faogustavo** [comment]
@hellomaya how do I use it? Put the codes into React module?

**Comment by hellomaya** [comment]
@faogustavo

- I am using react-native-navigation, "react-native-navigation": "^1.1.256"
- I changed the two files in react-native-navigation, by open your project in Xcode, you can see these files in Library folder
- To replace them wasn't recommended, by comparing difference and then merge the code I added would be better
- All code I have added with comment start with /// @@@Tom, you can search and see them
- Those RCTRootContentView+RCTRootContentViewExtension two files, should drag and copy to Library/React/Base folder.

Hope this helps.
