### ISSUE TITLE
How do I hide back button from modal window?

### ISSUE THREAD

**Issue by aemdy** [wix/react-native-navigation#2079]
### Issue Description

How can I hide a back button from modal window navbar and also prevent back button press from closing the modal?

---
### Environment
* React Native Navigation version: 1.1.253
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator Android 6.0 DEBUG)

**Comment by rnaffer** [comment]
This work for me.

<pre>
this.props.navigator.showModal({
    title: '',
    screen: 'sigapp.ServiceModal',
    animated: true,
    animationType: 'fade',
    passProps: {data: data},
    navigatorButtons: {
      leftButtons: [
        {}
      ]
    }
});
</pre>
