### ISSUE TITLE
Keep native (iOS) `< Back` chevron after adding an id to leftButtons

### ISSUE THREAD

**Issue by kotay** [wix/react-native-navigation#2083]
### Issue Description

I'm trying to add an `Alert` when a user taps `Back` (leftButton) because it is a destructive action. Currently I'm doing this by adding an`id` to the `leftButton` and hooking into the `event.id` in `onNavigatorEvent`.

When adding an `id` to the `leftButtons` it seems I have to _also_ require the title be not null (just setting the `id` doesn't add change the `event.id`):

```
leftButtons: [
  {
    title: "Back",
    id: "back"
  }
]
```

Unfortunately setting the title explicitly means losing the native iOS Back arrow/chevron. How can I both add an `id` to the button whilst keeping the native `< Back` with a chevron?

### Environment
* React Native Navigation version: `1.1.236`
* React Native version: `0.49.0`
* Platform(s) (iOS, Android, or both?): `iOS`
* Device info (Simulator/Device? OS version? Debug/Release?): `All`

**Comment by odesey** [comment]
Have you tried setting `title: ''`?

**Comment by kotay** [comment]
Yes, that results in a completely empty nav title with no icon/chevron _or_ text

**Comment by odesey** [comment]
Then try adding an icon:

``` javascript
  {
    title: "Back",
    id: "back", //remove me
    icon: require('path/to/chevron.png'),
  }
```

**Comment by kotay** [comment]
@odesey Works a treat although now. the text `Back` is lost and only the icon is shown.

**Comment by lBroth** [comment]
+1

**Comment by odesey** [comment]
Try setting the `backButtonTitle: 'Back'`

**Comment by Diego-Franco** [comment]
did you find any way to do this? looks like for iOS is not way to handle the back action and keep the button as other screens, and the icon sometimes is small than the others

**Comment by thame** [comment]
In V2 you can add: 
```
backButton: {
   title: 'Back',
},
```
