### ISSUE TITLE
migrate android e2e to detox

### ISSUE THREAD

**Issue by DanielZlotin** [wix/react-native-navigation#2086]

**Comment by yogevbd** [comment]
Currently blocked by issue #979 
We also need better treatment for pushing screens on android (Currently invisible screens in stack are not getting detached which causes detox multiple elements error)

**Comment by guyca** [comment]
Screens are detached when the push animation ends. Perhaps you need to wait for the animation to complete.

**Comment by yogevbd** [comment]
So it might be bug in detox.. @rotemmiz
