### ISSUE TITLE
Back button style changes on press

### ISSUE THREAD

**Issue by luco** [wix/react-native-navigation#2087]
### Issue Description

Whenever I touch the back button, it changes the current style to the default.
![c4nqocwdra](https://user-images.githubusercontent.com/246373/32085092-efa4f1ac-baab-11e7-90c9-9956cda9a8e6.gif)

### Steps to Reproduce / Code Snippets / Screenshots

Install react-native-navigation and apply a custom font style to back button.

---
### Environment
* React Native Navigation version: 1.1.236
* React Native version: 0.49.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS Simulator

**Comment by odesey** [comment]
Have you tried to `disableIconTint`?

https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=adding-buttons-to-the-navigator

**Comment by luco** [comment]
@odesey Yes, had no luck. I kinda fixed it using` backButtonTitle: ''`. It's not a fix. The back label doesn't appear.

**Comment by luco** [comment]
Updates on this?
I'm also having this on right buttons:

![3pon1tvzol](https://user-images.githubusercontent.com/246373/34327242-4709b5c2-e8a6-11e7-8571-828be4a13b2a.gif)
