### ISSUE TITLE
[V2] - Support drawing custom elements outside navigation stack

### ISSUE THREAD

**Issue by alexwasner** [wix/react-native-navigation#2089]
### Issue Description
I mentioned this in Discord, but didn't get a thumbs up or down from the Wix team, so I figured I'd solidify it with an issue on here. Some devs at my company are considering becoming a core contributor to V2, but we have some common client requests that don't really work 100% with the current navigation paradigm. 

The issue - We want to draw custom components outside of the navigation stack such as a custom menu overlay or other other external components. Many JS based implementations support drawing elements outside of the navigation stack to solve for this. 

### Steps to Reproduce / Code Snippets / Screenshots
A solution (with the current V1 syntax) could look something like this:
```
export default class App extends Component {
	constructor(props) {
		super(props);
		// ...
		_registerComponents().then(()=>{
	    Navigation.startSingleScreenApp({
	      screen: {
	        screen: 'Home',
	        title:  'Home',
	        navigatorStyle: stores.appState.navigatorStyle
	      },
	    }, this.refs.root)
		})
	}
	render() {
		return (<View>
			<CustomComponent/>
			<View ref='root'/>
    </View>)
	}
}

function _registerComponents(){
	return Promise.all([
		Navigation.registerComponent('Home', () => Home, stores, Provider),
		Navigation.registerComponent('ScreenTwo', () => ScreenTwo, stores, Provider)
	])
}
```
Or perhaps you register this component as `rootComponent` and if that exists, you render the navigators as a child of this component

### Environment
* React Native Navigation version: V1 Enhancement or V2 Feature
* Platform(s) (iOS, Android, or both?): Both

**Comment by reyalpsirc** [comment]
I’ve been trying to work with this and ignite boilerplate from Infinite Red and something like that would allow me to use Reactotron overlay feature when using different navigations for login/register and home screens

**Comment by egorkhmelev** [comment]
I believe I needed more or less the same feature (a view outside navigation stack) and done some work for v1 here https://github.com/wix/react-native-navigation/pull/1682 which I successfully use in one of the project both for iOS and Android

**Comment by joepake** [comment]
You should use react-navigation to replace this lib. This is a weak point of react-native-navigation. Use react-navigation you able to control better
