### ISSUE TITLE
screen animate 2 times

### ISSUE THREAD

**Issue by danceyoung** [wix/react-native-navigation#209]
The first screen's navBar is hidden.
navigate to second screen from first screen,
but first screen is animated with type 'slide-down or up' 2 times when pop second screen

android, RN0.31,RNN1.0.30

**Comment by guyca** [comment]
Thanks for reporting @danceyoung. I assume this is fixed in v2.0 so we didn't encounter this issue.
version 1.0.30 is pretty much not supported at this time since we're focusing on version 2.0.
