### ISSUE TITLE
Does react-native-navigation supports MobX

### ISSUE THREAD

**Issue by ugendrang** [wix/react-native-navigation#2092]
Iam aware that react-native-navigation support redux.

Can you please let us know, does it supports mobx?
import { Provider } from "mobx-react";
const store = configureStore();
registerScreens(store, Provider);

**Comment by 3210jr** [comment]
Hey,

Take a look at this repo: [react-native-navigation-mobx-boilerplate](https://github.com/kanzitelli/react-native-navigation-mobx-boilerplate)

Hope it helps!

**Comment by perrosnk** [comment]
Dublicate: https://github.com/wix/react-native-navigation/issues/187

**Comment by stonecold123** [comment]
My experience: 
I'm not able to pass mobx observable props to other screen in V2. I also have the same problem with realm in V1. Similar bugs: https://github.com/wix/react-native-navigation/issues/1748

**Comment by pqkluan** [comment]
I'll close this issue since the initial question has been answered.
