### ISSUE TITLE
[Question] Adding a filter icon next to Title on AppBar

### ISSUE THREAD

**Issue by ziyafenn** [wix/react-native-navigation#2094]
### Issue Description

I'm trying to add a **filter icon** as it shown on material guidelines next to my title. Once clicked, it will show a floating menu.
![image](https://user-images.githubusercontent.com/314302/32142904-787462d2-bca1-11e7-8c58-5fdb0f70261f.png)

I'd like to have to both working on iOS and Android. Is there any way to make it work?

Thanks.

**Comment by pqkluan** [comment]
You could use `navBarCustomView` field in [Navigation Style](https://wix.github.io/react-native-navigation/#/styling-the-navigator?id=style-object-format) for this issue.

It's not an out-of-a-box solution, but it's doable.
