### ISSUE TITLE
Transparent Nav Bar

### ISSUE THREAD

**Issue by chrissm79** [wix/react-native-navigation#21]
I'm having an issue trying to create a completely transparent navigation bar ([something like this](https://dribbble.com/shots/2178004-Purchase-Classes/attachments/401177)). I attempted the styles below, but the background comes out looking almost black. Is there something wrong with my styles?

``` javascript
export default class Profile extends React.Component {
  static navigatorStyle = {
    navBarTextColor: '#FFFFFF',
    navBarBackgroundColor: 'transparent', // Color is almost black
    navBarButtonColor: '#007aff',
    navBarHidden: false,
    navBarHideOnScroll: false,
    navBarTranslucent: true,
    drawUnderNavBar: true,
    drawUnderTabBar: true,
    statusBarBlur: true,
    navBarBlur: false, // If I set this to true, it properly blurs the background
    tabBarHidden: false,
    statusBarHideWithNavBar: false,
    statusBarHidden: false,
    statusBarTextColorScheme: 'light' // This doesn't seem to work either
  };

  constructor(props) {
    super(props);
  }

  render() {
    return (
      <FullBackground>  {/* Full screen image background */}
        <View style={styles.container}>
          {/* children */}
        </View>
      </FullBackground>
    );
  }
}

```

**Comment by guyca** [comment]
@chrissm79 Sorry for the late reply, Is this issue still relevant?

**Comment by chrissm79** [comment]
No worries, I'm sure you guys are busy! I actually just checked this out this morning with the app in the example folder. Looks like it's still an issue. I used the following navigatorStyle options on the [StyledScreen](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/StyledScreen.js):

```js
static navigatorStyle = {
    navBarBackgroundColor: 'transparent', // the background is black
    drawUnderNavBar: true,
    drawUnderTabBar: true,
    navBarTranslucent: true
};
``` 

```js
static navigatorStyle = {
    navBarBlur: false, // The background is still blurred
    drawUnderNavBar: true,
    drawUnderTabBar: true,
    navBarTranslucent: true
};
```

**Comment by gran33** [comment]
Hi @chrissm79,
I added ```navBarTransparent: true/false(default)``` option.
Best way yo use it:
```
navBarBlur: true,
drawUnderNavBar: true,
navBarTransparent: true
```

>Note If u want to make the navigation bar transparent and blur back and forth make sure u r explicitly set `navBarTransparent: false` `navBarTransparent: true`

Please, update to latest version and enjoy :)

**Comment by egdelwonk** [comment]
Is there a 2.0.1 release on npm? I can't seem to find one.

**Comment by brunolemos** [comment]
I think this issue should be reopened, because currently the navbar is becoming solid black instead of transparent. cc @gran33

**Comment by gran33** [comment]
@brunolemos Thanks for update. Can u plz share your `static navigatorStyle = {...}` and if u push the screen to share the `
this.props.navigator.push({... 
  navigatorStyle: {}, 
...
});` by the `push`.

**Comment by brunolemos** [comment]
@gran33 

```
navigator.showModal({ // tried with push too
  screen: 'easycarros.ServiceDetails',
  title: 'Serviço',
  navigatorStyle: {
    drawUnderNavBar: true,
    navBarTransparent: true,
  },
  title: name,
  passProps: {
    service: [{x: 1}], // ...
  },
});
```

- Tried with the static style property as well. 
- It's not black anymore, don't know why, but also not transparent netheir drawing under the nav.
- The `navBarTranslucent` works perfectly.

**Comment by brunolemos** [comment]
@gran33 lol, just got it working, but that's weird: It only works if I pass **both**  `navBarTransparent` and `navBarTranslucent` as `true`, then it will be transparent. That's probably an unexpected behaviour.

**Comment by sexykodo** [comment]
i'm having a similar issue, both passing style as prop or declaring as static in screen 
drawUnderNavBar: true,
navBarTransparent: true,
navBarTranslucent: true

on IOS works fine,
on android navbar keeps default color (white) and it's not drawn under

RN: 0.35
RNN: 2.0.0-experimental.105

**Comment by guyca** [comment]
@sexykodo Can you try updating to a newer version?

**Comment by sexykodo** [comment]
@guyca update to 2.0.0-experimental.136, still no transparency nor drawUnderNavBar.

**Comment by guyca** [comment]
@sexykodo Yes, I see that `navBarTransparent` is indeed not wired properly on Android. I'll fix it tomorrow.

**Comment by OzgurAkin** [comment]
@guyca  navBarTransparent is still not working on Android:
drawUnderNavBar: true,
navBarTransparent: true,
navBarTranslucent: true

**Comment by hdchan** [comment]
This doesn't seem to be working still on iOS. I'm using 1.1.108

**Comment by benwtnb** [comment]
@hdchan it's not working for me either… I tried using this setup:
```
    static navigatorStyle = {
    navBarTransluscent: true,
    navBarTransparent: true,
    drawUnderNavBar: true,
  };
```

**Comment by mahendra13** [comment]
Still not working in android, showing grey background instead of transparent and draw under navbar also not working.
`  drawUnderNavBar: true,
            navBarTransparent: true,
            navBarTranslucent :true`

**Comment by mahendra13** [comment]
@hdchan you need to give the navigatorStyle when you push the screen, it will not work in case of static style.
` this.props.navigator.push({
            screen: 'Example',
            title:"Example",
            animated: true,
            navigatorStyle: {
            drawUnderNavBar: true,
            navBarTransparent: true,
            navBarTranslucent :true
            },
            passProps: {
				id
	   },    
        })`

**Comment by Andrfas** [comment]
Facing this issue in iOS (simulator) on version 1.1.255 :(

**Comment by Andrfas** [comment]
For anyone who will face the issue - following combination worked for me:
```
    drawUnderNavBar: true,
    navBarTranslucent: true,
    navBarTransparent: true,
    navBarBackgroundColor: 'transparent'
```

**Comment by 1pocketaces1** [comment]
still having issue. works when applying what @Andrfas said, but same does not work for bottom tabs

**Comment by 1pocketaces1** [comment]
Yes it works for the navBar but not the tabsBar
