### ISSUE TITLE
Separate events on setOnNavigatorEvent?

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#2101]
### Issue Description
How can I know when my screen is appearing on push or on pop? Because I would like to do different stuff when my screen is being pushed to stack vs when it is being popped to top of stack.

Any ideas? I am using `setOnNavigatorEvent` at the moment. And it is firing `event.id === 'willAppear'` on push and pop which is not ideal :P

**Comment by jslz** [comment]
hi, Just wanted to chime in +1, this would be a great extra flag to know!
