### ISSUE TITLE
not work with amap integration

### ISSUE THREAD

**Issue by laiyifeng77** [wix/react-native-navigation#2102]
### Issue Description

use react-native-navigation with amap or any other map sdk ,the map will stop drawing when push another page . for example, show Apage with a single map, then push BPage, and then go back to APage, the map is showing a  white screen. i guess that it is the lifecycle of the map handling, but it is well with other navigation such as react-navigation . 

so i hope you can handle the problem for us .

the core question is how to handle the react-native-navigation lifecycle with the map lifecycle!!

best wishes.

https://github.com/wix/react-native-navigation/issues/2102

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: ^1.1.178
* React Native version: 0.47.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All The environments will happened

**Comment by haoxinlei1994** [comment]
hi!  do  you  solve  this  problems  now??   I  meet  the  same problem with you
