### ISSUE TITLE
Styling Tab Bar

### ISSUE THREAD

**Issue by xanderberkein** [wix/react-native-navigation#2106]
Hi, 
I was wondering if it's possible to style a tab bar like this, where the selected screen has a different tabbarcolor than the others.
![image](https://user-images.githubusercontent.com/10937632/32235869-eb799eda-be60-11e7-8119-23e51e01012e.png)

I looked through [the docs](https://wix.github.io/react-native-navigation/#/styling-the-tab-bar), but couldn't find anything. I'm on React Native Navigation version 1.1.255

**Comment by brunolemos** [comment]
Related: #466

**Comment by pqkluan** [comment]
Close this issue due to duplicate.
