### ISSUE TITLE
Add iPhone X prefersHomeIndicatorAutoHidden Option

### ISSUE THREAD

**Issue by michaelmerrill** [wix/react-native-navigation#2107]
### Issue Description

Currently there is no way to hide the home indicator on iPhone 10. Maybe we could set a property when creating a controller like: 'setAutoHideHomeIndicator' and have that set the prefersHomeIndicatorAutoHidden on the viewController to provide a better user experience.

> Per
> 
>  Apple:
> 
> Dear Developer,
> 
> iPhone X will start shipping to customers on Friday, November 3rd. As I’m sure you’ve seen, the iPhone X does not have a home button. To exit an app or access multitasking, users will swipe up from the bottom of the screen. A visual indicator at the bottom of the screen provides a hint about this interaction.
> 
> In order to assure a great video watching experience on iPhone X, it’s important to hide this indicator during video playback. You can do this by overriding the new UIViewController instance method https://developer.apple.com/documentation/uikit/uiviewcontroller/2887510-prefershomeindicatorautohidden in your video playback view controller, and returning true.
> 
> You can see a preview of the auto-hide behavior in the video https://developer.apple.com/videos/play/fall2017/801/. Implementing this new behavior should be very straight forward and quick.
> 
> Also, it’s important to verify that controls and information aren't touching or covered by the home indicator. For more information about avoiding layout issues on iPhone X, please check out the page https://developer.apple.com/ios/update-apps-for-iphone-x/.
> 
> We hope you’ll be able to update your app with this change prior to November 3rd. Please let me know if you have any questions.

**Comment by Jazznight** [comment]
I found a package implemented the auto-hide behavior into react native but it should replace the UIViewController so that I have no idea how can I use integrate this package to react native navigation..

https://github.com/flowkey/react-native-home-indicator

**Comment by stefanc96** [comment]
I found a solution , but this is not best one: 
1. Add to RNNRootViewController.h this line @property(nonatomic, readonly) BOOL prefersHomeIndicatorAutoHidden;
2.Add to RNNRootViewController.m this: 
- (BOOL)prefersHomeIndicatorAutoHidden {
	return true;
}
