### ISSUE TITLE
How would I communicate with my custom component?

### ISSUE THREAD

**Issue by deeperthanyou** [wix/react-native-navigation#2110]
I have a custom view component in the navigation bar how would I communicate with the parent component?

I'm trying to pass parameters but the problem is the custom view is a SearchBar so I want to be able to get the textview's input.

` navigationOptions = {
        navBarTransparent: true,
        navBarCustomView: 'CustomSearchBar', // registered component name
        navBarCustomViewInitialProps: this.props,
        navBarComponentAlignment: 'center',
        drawUnderNavBar: true,
    };
`

**Comment by hnvcam** [comment]
I'll suggest you to use redux to communicate between those views.

**Comment by deeperthanyou** [comment]
Could you help me learn about redux some more or point me to some useful resources

**Comment by pqkluan** [comment]
[Here](https://redux.js.org/) is Redux official website.
[Here](http://www.react.express/redux) is my recommended website for learning Redux and React Native.

I'll close this issue since the original problem is solved. Feel free to re-open if needed.
