### ISSUE TITLE
Top and bottom portion of screen left empty on iPhone X

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#2113]
### Issue Description
When I run the app on iPhone X simulator, the top and bottom portion of screen is left empty and is shown as black as shown below.

![screen shot 2017-11-04 at 9 09 27 am](https://user-images.githubusercontent.com/7475133/32402043-c1645a66-c141-11e7-9758-4ff796e9a5de.png)

The app screen should cover the entire screen of the phone.

### Steps to Reproduce / Code Snippets / Screenshots

Run the app on iPhone X simulator.

---
### Environment
* React Native Navigation version: 1.1.253
* React Native version: 0.49.3
* Platform(s) (iOS, Android, or both?): iOS (iPhone X)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by varungupta85** [comment]
@guyca @DanielZlotin Please share if you have any information regarding this issue.

**Comment by SukhKalsi** [comment]
Not sure if this is related, but will post here in case it is. We having some strange issue where when running the app on the iPhone X simulator, the app scales perfectly full screen. However on a release build to device, the app runs in the iPhone 6 esque view. We're using the following:

React Native Navigation version: 1.1.250
React Native version: 0.47.2
Platform(s) (iOS, Android, or both?): iOS (iPhone X)
Device info (Simulator/Device? OS version? Debug/Release?): Simulator (Debug/Release) & Device (Release)

**Comment by varungupta85** [comment]
hi @gran33 , would you have any information about this issue? Thanks!

**Comment by huyhai** [comment]
+1

**Comment by jbolter** [comment]
You guys need to "enable" iPhone X by adding the appropriate screen size.  This will allow the RNN to fill the screen but you may run into other layout issues.

**Comment by varungupta85** [comment]
@jbolter I figured what did you mean by adding the appropriate screen size to enable iPhone X. You meant the launch screen image. iPhone X requires a launch image of size 1125x2436 without which it will not use the complete screen.

**Comment by nromptea42** [comment]
When you say "launch image", do you mean a splash screen ? Did it work for you ?

**Comment by varungupta85** [comment]
Yes. The black area on the top and bottom is gone after I added the right sized splash screen for iPhone X but you will also need to fix some screens in your app depending on the safe area for iPhone X. React Native 50 has a new component called `SafeAreaView` that can be used or react-community also has a package that can be used if you don't want to update the react-native version just yet.

**Comment by thechefchen** [comment]
Verified that changing the splashscreen would fix the tabBasedNavigation on iphoneX.

This post mentioned what size to use and how to change it. 

https://stackoverflow.com/questions/46191522/how-to-add-iphonex-launch-image

**Comment by saurabhsahu13** [comment]
@SukhKalsi I am facing same issue as yours. I have used the right sized Launch image for iPhone X  and it shows perfectly on the simulator but in the release version it doesn't take up the full view. Did you find any solution to this issue?

**Comment by aemdy** [comment]
Could you please explain how to add an iphone X splash screen? If I open xcode, go to Images > LaunchImage I don't see a slot for iPhone X screen (all the existing screens are already full).

**Comment by Suresh-R-S** [comment]
@aemdy make sure you have 'iOS 8.0 and later' portrait check box as marked.

![screen shot 2017-12-19 at 4 17 25 pm](https://user-images.githubusercontent.com/13781322/34153477-358c093e-e4d8-11e7-8d96-009c719ad455.png)

**Comment by joshuapinter** [comment]
Yup, amazingly, updating the Launch Images fixed this issue. You can see my full answer here: 

https://stackoverflow.com/a/54965204/293280

My guess is because Apple assumes that if you don't have the proper LaunchImage for the taller iPhone X(s) screens, then your app isn't optimized for the new screen and instead of breaking your app layout, it just uses the limited screen size for compatibility.
