### ISSUE TITLE
navBarCustomView alignment not correctly

### ISSUE THREAD

**Issue by jarvisluong** [wix/react-native-navigation#2114]
### Issue Description

I use navBarCustomView on navBarStyle and use navBarComponentAlignment to 'center'. However, the custom view does not center as expected.

I tried to fix it with alignSelf: 'center' in the navBarCustomView component, but it will only be truly center in the view if both left and right button are the same kind (text or icons), or there are no left and right buttons. (It means if I set left button to be an icon, rightbuttons to be text button, it will be aligned center between the distance of these buttons)
---
### Environment
* React Native Navigation version: 1.1.257
* React Native version: 0.49.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 11.0, normal navbar, iphone 8

**Comment by rh389** [comment]
Same issue here. Hacking around at it, I've had some success with changing `layoutSubViews` in `RCCCustomTitleView.m` to:

```objectivec
-(void)layoutSubviews {
    [super layoutSubviews];
    
    if ([self.subViewAlign isEqualToString:@"fill"]) {
        self.subView.frame = self.bounds;
    }
    else {
        
        CGFloat superViewWidth = self.superview.frame.size.width;
        CGFloat navBarWidth = self.superview.superview.frame.size.width;
        CGFloat leftButtonWidth = self.superview.frame.origin.x;
        CGFloat rightButtonWidth = navBarWidth - superViewWidth - leftButtonWidth;
        CGFloat padLeft = 0;
        CGFloat padRight = 0;
        if (leftButtonWidth > rightButtonWidth) {
            padRight = rightButtonWidth - leftButtonWidth;
        } else {
            padLeft = rightButtonWidth - leftButtonWidth;
        }

        CGRect reactViewFrame = self.subView.bounds;

        reactViewFrame.size.width = self.frame.size.width - padLeft - padRight;
        reactViewFrame.origin.x = padLeft;
        self.subView.frame = reactViewFrame;
    }
}
```
**AND** using `alignSelf: 'center'` in the style of my custom component.

The problem with this is that the title's container takes up the maximum available width between the two buttons, which means the default iOS `< Back` button shows as `<` even if the custom title component isn't wide. If your left and right buttons don't change depending on the space available to them, that shouldn't be a problem.

**Comment by wilson100** [comment]
@rh389 Any ideas about how to fix it on Android? If we use modal navigation, then there is no back arrow on iOS, but there is one on Android. So the custom view's alignment is also incorrect in that case.

**Comment by wilson100** [comment]
Made a small workaround:
In class/function where you define navBarCustomView add marginRight to the style of view. Set the margin value in order to compensate shift caused by navigation bar button.

**Comment by rh389** [comment]
Unfortunately that workaround only works where your buttons and title have a fixed, known size.

I discovered my hack above only works for iOS 11.0 and 11.1, but not <=10.3 or >=11.2 (basically because there are a different number of superviews between the `RCCCustomTitleView` and the nav bar). This approach is obviously too fragile, and in any case it's a fudge (making the container big and nudging its content towards the centre, which means left/right buttons are compressed) so I've tried to strip it back and find the "correct" solution.

I've got as far as this: https://stackoverflow.com/questions/47779643/centering-a-dynamically-sized-titleview-in-navigation-bar-without-autolayout , which is great for iOS 11+ but slightly glitchy for iOS 10. Would love to hear how to do this right.

**Comment by chrismllr** [comment]
Anyone have any updates here? Currently, I have a `SpacerButton` component, which I use like:
```
static navigatorButtons = {
    rightButtons: [
      {
        id: 'close-modal',
        component: CUSTOM_CLOSE,
        passProps: {
          buttonId: 'close-modal'
        }
      }
    ],
    leftButtons: [
      {
        id: 'spacer',
        component: SPACER_BUTTON
      }
    ]
  };
```

This works fine and all, but when pushing a screen onto the stack, if both screens use this same button/spacer combo for top buttons, there is a jitter in the header animation as they are removed and put back.

**Comment by rh389** [comment]
I'm currently using this - it gives good results for me, but it's an awful piece of hackery especially for iOS<=10: https://github.com/rh389/react-native-navigation/commit/39ad457b839ad980582c550685e7605f904248c0

It also requires wrapping any custom title (centre) component in this:

```js
export default function NavBarTitle({ style, children }) {
  if (Platform.OS === 'ios' && Platform.Version && parseInt(Platform.Version.split('.')[0]) <= 10) {
    return <View style={{
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 5, // YMMV
      flexDirection: 'row',
    }}>
      { children }
    </View>
  }

  return <View style={{
      flexDirection: 'row',
      alignItems: 'center'
    }}>{ children }</View>;
}
```

**Comment by davidliu** [comment]
Having trouble with this myself. Additionally, the nav bar jumps when swiping from the left to pop a screen.

I guess a question that should be asked is: is the navBarCustomView intended to be using alongside the navigatorButtons, or should the navBarCustomView be thought as a full replacement for the nav bar, including navigator buttons?

**Comment by chrismllr** [comment]
After upgrading (currently on `1.1.407`) I am no longer seeing this issue! I've built to iPhone X as well as iPhone 7 on iOS 10.3.2.

Other relevant versions:
```
react-native: 0.54.0
react: 16.3.0.alpha-1
```

**Comment by jarvisluong** [comment]
Upgrading indeed solved the problem, I'm going to close this issue for now!

**Comment by Hari70a** [comment]
@chrismllr Was this fixed on Android? Still seeing even after upgrade to `1.1.407`
