### ISSUE TITLE
iOS Installation Instructions Are Out of Date as of React Native v0.49.0

### ISSUE THREAD

**Issue by kylecorbelli** [wix/react-native-navigation#2118]
As of React Native v0.49.0, iOS and Android share a common `index.js` file in the root directory of the project.

The installation documentation for `react-native-navigation` currently expects the old paradigm of separate `index.ios.js` and `index.android.js` files and consequently includes `jsBundleURLForBundleRoot:@"index.ios"` when it should now be `jsBundleURLForBundleRoot:@"index"`.

https://user-images.githubusercontent.com/165856/31623607-cc69304a-b254-11e7-8fd3-cb81c897ca41.png

## Fix:
This PR updates the iOS installation instructions in the documentation: https://github.com/wix/react-native-navigation/pull/2117

**Comment by Zephir77167** [comment]
Hello, sorry didn't see your PR and fixed it: https://github.com/wix/react-native-navigation/pull/2412
