### ISSUE TITLE
incompatible between ios and android to send object by props  

### ISSUE THREAD

**Issue by winglight** [wix/react-native-navigation#212]
I found that the same json object sent by props like this:

```js
this.props.navigator.push({
          screen: ...,
          title: ...,
          passProps: {
            book: this.state.book //it's a parse model object
          }
      });
```
On iOS, it's sent to the next screen with all of fields but functions.
But on android,  it's just with parts of functions but fields.
Here's code of the next screen:
```js
var chapters = this.props.book.chapters; //this works fine on iOS but android
chapters = this.props.book.get('chapters'); //this works fine on android but iOS
```

**Comment by DanielZlotin** [comment]
Please include your react-native version, react-native-navigation version.

Also, I didn't quite understand the issue. Can you please provide more code example? what is `book`?

**Comment by winglight** [comment]
`"react": "15.2.1",
    "react-native": "0.30.0",
    "react-native-navigation": "^2.0.0-experimental.51"`
Here's book type:
`
 var Parse = require('parse/react-native');

class BookModel extends Parse.Object {
    constructor() {
        // Pass the ClassName to the Parse.Object constructor
        super('BookModel');
        this.name = "unknown";
        this.url = "";
        this.cover = "";
        this.newest = "";
} 
`
My problem is how to get the value of fields, if by field, like book.name it's undefined on android and if by the function "book.get('name')" it reports "no function" error on ios.

**Comment by DanielZlotin** [comment]
I'm not familiar with this "parse" library, care to make an example app for me to play with? because when I pass functions or objects using the new passProps it has that same function/object in the props.. Seems to me like it's not related at all to navigation

**Comment by winglight** [comment]
Here‘s parse: https://parse.com/
Though it'll be closed by facebook, I like it for simplest API.
That's possible parse caused this problem but I'll take a couple of weeks to replace it if no other options.

**Comment by DanielZlotin** [comment]
I know the parse service, I have no idea about it's react-native implementation. 

Here is a suggestion: prove that it's NOT a parse/react-native issue: create a book/parse object and without passing it as prop, just print out the result of the method call in place.

**Comment by winglight** [comment]
uh, if on the current screen I got a parse object, every field and function is ok because no problem found at the beginning until I made the second screen.

**Comment by 1800joe** [comment]
I haven't tried v2. But I have run into this issue: passProps to a modal does not allow functions through in v1.0.30 on iOS -- there's nothing special about the Parse library, you're just passing functions.

**Comment by winglight** [comment]
@1800joe My problem has a little difference with yours. It's a little weird, the same code results different behaviors between ios and android.

**Comment by 1800joe** [comment]
@winglight can you confirm the issue persists with v2? If so create a test case showing the exact props that work on android and fail on iOS. It would be extra helpful to eliminate any third party code from Parse, etc. so we can know what specifically about the props is failing.

**Comment by winglight** [comment]
Yes, I use a new object wrapper to solve this problem. I guess there's a implicit conflict in parse object. So I close this issue now.
