### ISSUE TITLE
Example create Custom Tab Bar Component?

### ISSUE THREAD

**Issue by RagamAnekaGlobal** [wix/react-native-navigation#2126]
### Issue Description
Hello guys, i am new in react native. Currently i need to create this custom component (Big Plus in center, when clicking show the floating menu) in tab bar. How to create this custom component inside the tab bar? I know there is tabBarComponent options but i don't know example to create the component for tabBarComponent. Thank you.
### Steps to Reproduce / Code Snippets / Screenshots
<img width="400" alt="screen shot 2017-11-06 at 8 09 41 pm" src="https://user-images.githubusercontent.com/32739276/32442591-8e8bc392-c32e-11e7-83c8-5a1c57d86ef3.png">

---
### Environment
* React Native Navigation version: 0.49.1
* React Native version: 1.0.0-beta.13
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug

**Comment by alimek** [comment]
hmm i am challenging with something similar, @RagamAnekaGlobal did you find any solution for this?

**Comment by brzez** [comment]
@alimek 
oh snap, sorry, I'm working on 2 projects where one uses react-native-navigation and the second one uses reactnavigation. I was looking how to do this in reactnavigation when I got to this issue.

Yeah, the best solution would be to achieve it via native. 
There might also be a bit easier but messier solution - just write your own bottom tab component.

You could drop react-native-navigation for bottom tabs, use custom component for the bottom tab views.
If you would need some control over which tab should open - you could probably do this via navigator events / deep links.

The rest of the app would still be using react-native-navigation without any changes.

**Comment by sagark1510** [comment]
@brzez how can I add my custom tabbar which will be shared to all the tabs at the bottom? Any example?

**Comment by flaviotobi** [comment]
@alimek   Can you show some code, about your solution?
And this is in V2 or V1?

**Comment by alimek** [comment]
@flaviotobi it's in V1.

What I did:

- register a ReactComponent 
- pass overlay parameters like position and size to native side
- render on native side a overlay `UIView` with ReactComponent side with a specified with, height and position

You can check my forked repo [here](https://github.com/alimek/react-native-navigation) and you can compare my for with wix's master to see my commits

for iOS "core" change: see my first commit [here](https://github.com/alimek/react-native-navigation/blob/d46a61bb27ba991cd23c1856952feff487bc2793/ios/RCCTabBarController.m#L235)

**Comment by flaviotobi** [comment]
@alimek  Thanks for the fast response. :)

**Comment by aaahrens** [comment]
I know I'm late to the party, but can't you just use the navBarCustomView property?

**Comment by bbuchanan** [comment]
@aaahrens navbar is at the top, tab bar is at the bottom. I think OP wants to control the bottom.

**Comment by amirmatin** [comment]
@alimek  can you please expand on your solution ? I have been trying to do this for days now but cant find any solution ! a snipped code would be great .. 
any help is much appreciated

**Comment by amirmatin** [comment]
I was also thinking of having a button and overlaying it at the middle of the navigator but the button always lies behind the navigator..

**Comment by pribeh** [comment]
@alimek Does your fork address Android or just iOS?

**Comment by alimek** [comment]
@pribeh both, but on Android there is problem if you would like to position over the bottom navigation.

**Comment by pribeh** [comment]
@alimek Thanks for responding! It looks like it might be easier to get this going with v2 of the library.

**Comment by Agoujil2saad** [comment]
@alimek how to toggle the Visibility of  the overlay for a specific tabs ?

**Comment by jupassamani** [comment]
@RagamAnekaGlobal did you find any solution for this?

**Comment by rickycpadilla** [comment]
@jupassamani  I've spent hours trying to figure out the best solution for adding a larger button to the tab bar (including toying around with v2's "showOverlay"), and I think @alimek 's solution is the best way to go. Use his fork of the react-native-navigation library, and implement like this:
`
 Navigation.startTabBasedApp({
    tabs: [...],
    tabsStyle: {...},
    overlay: {
        screen: 'CustomTab',// Where 'CustomTab' is the name of my registered tab button
        height: 62,
        width: 62,
        position: {
          top: screen.height - 62,
          left: (screen.width / 2) - 31
        }
    }
})
`
I used this implementation to place a larger 62x62 button in the center of my tab bar.

**Comment by alimek** [comment]
@rickycpadilla did you maybe tried to achieve a middle button on `Android` over the bottom tabs?

**Comment by rickycpadilla** [comment]
@alimek It does not appear to work out of the box for Android, at least in the way I implemented it. Is there something else I need to do?

**Comment by alimek** [comment]
@rickycpadilla I had problem on `Android` to implement overlay on top of bottom navigation working with my `Android` development knowleage. I have finished with button on right side just above the bottom nav (just position it on different position for each platform).

I thought, that you have played on `Android` native side with my repo to render something on top of bottom nav :-)

**Comment by FRizzonelli** [comment]
@alimek @rickycpadilla I'm not able to use the fork, while tryin' to launch the app, i'm getting error "screen is not defined" on both iOS and Android. Tried even with screens that are correctly working in the app but it doesn't work (I'm showing the tabbarbasedapp after a singlebased one used for login)

**Comment by FRizzonelli** [comment]
@alimek I've the same problem of @amirmatin, the custom view is always behind the navigation bar. I can see it only when the tabbar is hidden (which I think is wrong, I'd like to hide the button when tabbar is hidden). My iOS skills are really bad, do you any idea? 
I'm an Android dev, so I can try to fix it for Android but I need some help for Objective-C side 😅

**Comment by FRizzonelli** [comment]
@alimek Ok I've found that if you toggle the visibility of the tabbar, the component goes behind the tabbar (after the transition completes). I'm trying to investigate it!

**Comment by BrightonWeBill** [comment]
@RagamAnekaGlobal did you end up finding a solution of how to implement that design, i have the same issue too.

**Comment by FRizzonelli** [comment]
@BrightonWeBill You'd try my fork, you need to add the overlay params to the starttabbasedapp. I've also added the feature to have "disabled tab" so you can add an invisible/not clickable tab under the button to have everything properly spaced

**Comment by FRizzonelli** [comment]
@BrightonWeBill Sure, you need to put this in your startTabBased
```
Navigation.startTabBasedApp({
          tabs: [
          {
              label: '',
              icon: require('../src/img/fake.png'),
              screen: ScreenKeys.emptyScreen,
              isIntercept: true
          }],
          overlay: {
              screen: ScreenKeys.middleButton,
              position: {
                    top: screen.height - Platform.select({ ios: 76, android: 84 }),
                    left: screen.width / 2 - 28,
                    height: 56,
                    width: 56
              }
          },
          animationType: 'fade'
        });
```

ScreenKeys is just an enum with name of the components. For tabs, I've pasted only the code for adding the middle one (which should be the third in order). The icon of that tab is just a 1x1 transparent pixel, pointing to an Empty view component.

Let me know if you have any other problem!

**Comment by BrightonWeBill** [comment]
I did mine a bit different, it works for ios but for android it giving me problems

<img width="810" alt="screen shot 2018-06-30 at 09 39 43" src="https://user-images.githubusercontent.com/33026951/42122916-975562a6-7c49-11e8-9499-776c92c36726.png">

**Comment by pribeh** [comment]
@BrightonWeBill That's an overflow issue. Android doesn't deal with overflow very well. I'm not sure you will be able to resolve the issue easily. Can you add the color to the bottom object?

**Comment by Albert0405** [comment]
@BrightonWeBill  im having the same issue.

**Comment by FRizzonelli** [comment]
@BrightonWeBill @Albert0405 I'm using setElevation in the code (which works on 21+). Btw I think the problem is in your RN component 'cause I imagine that the white background is inside the registered RN component right? In that case as mentioned from @pribeh you should work on the overlay and try to figure it out.

**Comment by pribeh** [comment]
@FRizzonelli I tried the recent fork here https://github.com/FRizzonelli/react-native-navigation and the code below but I can't seem to get the icon to show up on Android. Any tips?

In App.js:

```
tabs: [
		{
			screen: "myapp.HomeScreen",
			icon: require('./img/tabs/home.png'),
			selectedIcon: require('./img/tabs/homepress.png'),
			iconInsets: { // add this to change icon position (optional, iOS only).
				top: 6, // optional, default is 0.
				left: 0, // optional, default is 0.
				bottom: -6, // optional, default is 0.
				right: 0 // optional, default is 0.
				},
		},
		{
			screen: "myapp.ChatScreen",
			title: "Chat",
			icon: require('./img/tabs/chat.png'), //placeholder
			selectedIcon: require('./img/tabs/chatpress.png'),
			iconInsets: { // add this to change icon position (optional, iOS only).
				top: 6, // optional, default is 0.
				left: 0, // optional, default is 0.
				bottom: -6, // optional, default is 0.
				right: 0 // optional, default is 0.
				},
		},
		{
			screen: "myapp.EmptyScreen",
			title: "",
			icon: require('./img/tabs/dumbybutton.png'),
			selectedIcon: require('./img/tabs/dumbybutton.png'),
			isIntercept: true
		},
		{
			screen: "myapp.NotificationScreen",
			title: "Notifications",
			icon: require('./img/tabs/notifications.png'),
			selectedIcon: require('./img/tabs/notificationspress.png'),
			iconInsets: { // add this to change icon position (optional, iOS only).
				top: 6, // optional, default is 0.
				left: 0, // optional, default is 0.
				bottom: -6, // optional, default is 0.
				right: 0 // optional, default is 0.
				},
		},
		{
			screen: "myapp.ProfileScreen",
			title: "Profile",
			icon: require('./img/tabs/profile.png'),
			selectedIcon: require('./img/tabs/profilepress.png'),
			iconInsets: { // add this to change icon position (optional, iOS only).
				top: 6, // optional, default is 0.
				left: 0, // optional, default is 0.
				bottom: -6, // optional, default is 0.
				right: 0 // optional, default is 0.
				},
			navigatorButtons: {
				rightButtons: [
					{
						icon: require('./img/navbar/settings.png'),
						id: 'settings',
						showAsAction: 'always',
						buttonColor: '#262626',
						disableIconTint: true,
					},
				]
			}
		}
	],		
	tabsStyle: {
		initialTabIndex: 0, //the default selected bottom tab. On Android, add this to appStyle
		tabBarSelectedButtonColor: '#262626',
		tabBarButtonColor: '#262626',
		tabBarHideShadow: true,
		tabBarTranslucent: false,
		tabBarBackgroundColor: '#f5f5f5',
	},
	appStyle: {
		initialTabIndex: 0,
		orientation: 'portrait',
		tabBarSelectedButtonColor: '#262626',
		backButtonImage: require('./img/navbar/back.png'), // iOS only
		hideBackButtonTitle: true // iOS only
	},
	overlay: {
		screen: 'myapp.OverlayButton',
		position: {
				top: screen.height - Platform.select({ ios: 37, android: 55 }),
				left: screen.width / 2 - 28,
				height: 56,
				width: 56
		}
	},
	animationType: 'fade'
});
```

In OverlayButton.js:

```
import React, { Component } from "react";
import {
	StyleSheet,
    View,
    Image,
    TouchableOpacity
} from "react-native";

class OverlayButton extends React.Component {

    render() {	
        return (
            <TouchableOpacity style={styles.container}>
                <Image style={styles.logo} source={require('../img/navbar/add.png')} />
            </TouchableOpacity>
        )
    }
}

const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default OverlayButton;
```

**Comment by pribeh** [comment]
Just a margin/positioning issue

**Comment by pribeh** [comment]
Anybody have a good idea on how to handle transitions between screens (left/right ones) and the overlay? When transitioning from left or right the overlay remains in the same position which makes the transition a little jarring.

**Comment by FRizzonelli** [comment]
@pribeh unfortunatly, overlay component doesn't receive the navigator parameter properly (and I've not enough knowledge on RNN to find the fix). I resolved it by dispatching an action with redux and handling the "button behaviour" from the main tab screen. For generating the button I've taken the fork from @alimek, maybe he can fix the problem on the navigator not injected inside the overlay :(

**Comment by alimek** [comment]
hmm i am doing navigation from overlay component in little different way. I am storing navigation object from each tab in object


```js
class NavigationActionService {
  [FIRST_STACK] = null;
  [SECOND_STACK] = null;
  [THIRD_STACK] = null;
  [FOURTH_STACK] = null;
  [MODAL_STACK] = null;

  setNavigator = (type, navigator) => {
    this[type] = navigator;
  };

  push = (type, params) => {
    if (this[type]) {
      this[type].push(params);
    }
  };
}
```

When registering component in RNN, I added HOC:
```js
Navigation.registerComponent(LOGIN_PAGE, () => withNavigationWrapper(Login, FIRST_STACK), store, Provider);
```

and generally `withNavigationWrapper` is HOC with lifecycle methods:

```js
constructor(props) {
      super(props);
      NavigationActions.setNavigator(navigationStackName, this.props.navigator);
    }

componentWillReceiveProps(nextProps) {
      .... check if navigation id changed...
      NavigationActions.setNavigator(navigationStackName, nextProps.navigator);
    }
```
and I am using redux's actions to change a screen in specified tab. eg push:

```js
NavigationActions.push(FIRST_STACK, {
   screen: 'newScreen',
});
```

Use case for my fork is, that you can put an button in the middle which is on top of bottom navigation and after click its showing a modal, which is rendered in totally different component, which is always render once in app like `RootComponent`.

**Comment by pribeh** [comment]
@FRizzonelli @alimek thanks to both of you for sharing what you're doing! We're using mobx but might give what @alimek has laid out above with a twist.

**Comment by pribeh** [comment]
@FRizzonelli As for animation, we're using animatable for a lot of stuff – just use useNativeDriver for native animations. I would trigger a slideInLeft but still figuring out how to pass the prop properly from the one screen to the other. 

See: https://github.com/oblador/react-native-animatable

**Comment by pribeh** [comment]
@FRizzonelli are you experiencing crashes or any other issues updating (refreshing) lists with your fork? I'm going to investigate what the differences are with the main branch here and see if I can merge it with the latest RNNv1 release.

**Comment by FRizzonelli** [comment]
@pribeh I think lists are not related to RNN, I'm using many FlatLists in my app without problems. I'm on latest RN release btw (0.55.4, need to update to 0.56 in next days).

**Comment by cchiama** [comment]
@FRizzonelli work only on v1? The central custom tab indeed. (il tab centrale lo utilizzi solo sulla versione 1 o hai provato anche nella v2 :))

**Comment by FRizzonelli** [comment]
@cchiama Only on v1 :( (dato che sto usando quella nei vari progetti, ho sempre lavorato con il fork della v1, nella v2 credo sia totalmente da cambiare l'implementazione)

**Comment by cchiama** [comment]
@FRizzonelli ok. Immaginavo. Grazie.

**Comment by abhijeetmane** [comment]
@FRizzonelli I tried @alimek solution and I am getting below error.
```
Possible Unhandled Promise Rejection (id: 0):
ReferenceError: screen is not defined
ReferenceError: screen is not defined
```
<img width="416" alt="screen shot 2018-09-07 at 22 41 11" src="https://user-images.githubusercontent.com/18515777/45242116-260b4200-b2ef-11e8-8d61-9041f35b3a8b.png">

**Comment by alimek** [comment]
@abhijeetmane did you registered screen before load app?

**Comment by abhijeetmane** [comment]
@alimek Yes.  Like this
Navigation.registerComponent(
  "eventxapp.logoTab",
  () => LogoTab,
  store,
  Provider
);

and then passing overlay like this

Navigation.startTabBasedApp({
    tabs: [...],
    tabsStyle: {...},
   overlay: {
                screen: "eventxapp.logoTab",
                height: 62,
                width: 62,
                position: {
                 top: screen.height - 62,
                  left: (screen.width / 2) - 31
                }
        },
})

**Comment by alimek** [comment]
@abhijeetmane and are you sure that app works without the `overlay` property ?

**Comment by abhijeetmane** [comment]
@alimek 
I am using overlay just to add one logo button in tab menu.
Without Overlay it looks like this ( without yellow warning)

<img width="423" alt="screen shot 2018-09-07 at 23 00 45" src="https://user-images.githubusercontent.com/18515777/45242863-ed209c80-b2f1-11e8-869c-07fa30cdb8cf.png">

and With Overlay I am not able to navigate from previous page to my tab based page. (yellow warning)
<img width="408" alt="screen shot 2018-09-07 at 23 01 05" src="https://user-images.githubusercontent.com/18515777/45242886-0590b700-b2f2-11e8-9f28-acda13fddbd5.png">
<img width="416" alt="screen shot 2018-09-07 at 22 41 11" src="https://user-images.githubusercontent.com/18515777/45242890-07f31100-b2f2-11e8-8a09-88bb1ab20f8d.png">

**Comment by abhijeetmane** [comment]
@alimek @FRizzonelli Any help would be appreciated

**Comment by ialmoqren** [comment]
Just for the record, [an example of a custom tab bar component in RNN v2](https://github.com/wix/react-native-navigation/issues/498#issuecomment-456218215)

**Comment by scaralfred** [comment]
@FRizzonelli Hey man. Did you manage to use a central overlay button also with v2 (android) ?
Ci sei riuscito con la v2?
Thanks in advance...
