### ISSUE TITLE
calling pop() after a switchToTab()

### ISSUE THREAD

**Issue by jonching** [wix/react-native-navigation#2127]
### Issue Description

It doesn't seem like there's a way to call pop() or popToRoot() after doing a switchToTab().

This seems like a pretty normal use-case. For example, I have a tab where users can upload images. After uploading, I'd like to switch back to the home tab and ensure that it's at the root by calling popToRoot(), but I can't do this from the same function that I called switchToTab(). I don't see a viable way of doing this.

**Comment by Seeker93** [comment]
Look at Deep links in the docs. I amd doing something similar with toptabs using Deeplinks. Don'r really have the time to put example code, but If you still need help later I'll see if I can find the time.

**Comment by ErikMikkelson** [comment]
I'd like to see this too, as I must be missing the proper way to do it in the documentation.

**Comment by leoskyrocker** [comment]
@Seeker93 can you elaborate from a high level how you achieved it with deeplinks?
