### ISSUE TITLE
How to extend com.reactnativenavigation.activities.RootActivity to MainActivity.java?

### ISSUE THREAD

**Issue by prashen** [wix/react-native-navigation#213]
I am not getting how to add/config this third step. Please help to config :>

This is the third step for installing for android :>

"Have your MainActivity.java extend com.reactnativenavigation.activities.RootActivity. RootActivity is used as a proxy activity to start your actuall app.
The only method you might need to override is getPackages(), make sure you add RnnPackage as well."

Here I am not clear how to extend and how to override RnnPackage. :( (non-java user)

This is my MainActivity.java file :>
![mainactivity](https://cloud.githubusercontent.com/assets/5449548/17765678/f97ad0ec-6544-11e6-846b-0c66b7d78309.jpg)

I have replaced "import com.facebook.react.ReactActivity;" with this "import com.reactnativenavigation.activities.RootActivity;"

Confused here. Any steps example will be helpful. Thanks!

**Comment by guyca** [comment]
Hey @prashen 
First off, I think you'd find it easier to work on Java files from Android Studio. You need to override `getPackages()` only if you've added native dependencies to your project. If you did, then simply add:
```java
@Override
    public List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
                new RnnPackage()
                // Add here the rest of the packages you require
        );
    }
```

**Comment by nos-joel** [comment]
Hi guyca.
 I am facing the same problem, but I am not understanding your answer. First, my MainActivity.java path is "myProjectName\android\app\src\main\java\com\myProjectName\MainActivity.java". It is initially like this: 
`package com.myProjectName;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "myProjectName";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage()
        );
    }}`

Regarding the native dependencies, I have not added anything. I am just following the Wix example for react-native-navigator. Really, I am not clear what needs to be added and/or modified.

**Comment by guyca** [comment]
Hey @nos-joel 
You're `MainActivity` is completely wrong. If you're using version 1.3.x - it's not supported.
You can upgrade to the experimental v2 version, instructions [here](https://github.com/wix/react-native-navigation/wiki/Installation---Android), which will be soon officially released.

**Comment by nos-joel** [comment]
Will try the experimental version, thanks!
