### ISSUE TITLE
Custom Nav Button problem with positioning 

### ISSUE THREAD

**Issue by AvijitDutta95** [wix/react-native-navigation#2131]
### Issue Description

I am designing  my own custom nav button which design is like this:

![capture](https://user-images.githubusercontent.com/26165120/32492055-f3ab6808-c3de-11e7-9e48-9505c0ec0831.PNG)

But when i'm trying to implement it it looks like: 
![capture2](https://user-images.githubusercontent.com/26165120/32492089-12d36e2e-c3df-11e7-97be-7d499d826e22.PNG)

Code for custom button 

```
import React from 'react';
import {View, Text, TouchableOpacity, StyleSheet } from 'react-native';

export default class CustomNavButton extends React.Component {
    render(){
        return(
            <View style={{marginTop: 12, right: 5}}>
                <TouchableOpacity style={styles.buttonContainer} activeOpacity={0.8}>
                    <Text style={styles.buttonText}>{this.props.text}</Text>
                </TouchableOpacity>
            </View>
        )
    }
}

const styles = StyleSheet.create({
    buttonContainer: {
        width: 45,
        height: 30,
        borderRadius: 25,
        borderColor: '#ffffff',
        borderWidth: 1.5,
        justifyContent: 'center',
        alignItems: 'center'
    },
    buttonText: {
        fontSize: 30,
        textAlign: 'center',
        fontFamily: 'VarelaRound-Regular',
        color: '#ffffff'
    }
})
```
If i don't use `right: 5` in view styling then its shows perfectly but i need that gap on that right side.

This need help for this problem.

---
### Environment
* React Native Navigation version: latest
* React Native version: 49.03
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both, Debug

**Comment by Seeker93** [comment]
What I suspect is happening is that you are setting your buttonContainer's width to 45, and then forcing it right by 5, which causes that 5 pixels to get cut off on the left.

I can think of 2 solutions:

1) Set the width of your buttonContainer to 50.

OR (preffered)

2)  Use paddingRight: 5 instead of right: 5. This adds and extra padding to the right of your view and should achieve what you want it to achieve.

Let me know how it goes.

**Comment by AvijitDutta95** [comment]
@Seeker93 , none of solutions are worked for me, with your first solution there is no changes and with that second one it's looks like: 
![capture3](https://user-images.githubusercontent.com/26165120/32496847-a12fdea8-c3f0-11e7-98dc-22401a2664d7.PNG)


No gap on right side after using paddingRight: 5

**Comment by Seeker93** [comment]
HI I edited my answer relatively quickly because I made a mistake. I meant to say `marginRight` instead of `paddingRight`

**Comment by Seeker93** [comment]
Hi, sorry, I edited my initial answer quickly since I made a mistake.  You need `marginRight` instead of `paddingRight`

**Comment by AvijitDutta95** [comment]
@Seeker93, No change with `marginRight` also. :-(

**Comment by khsily** [comment]
add {borderWidth: 0}  👍

**Comment by AvijitDutta95** [comment]
Sorry @khsily , you comment is not clear to me. I need that border for that button. Can you explain what are you trying to say! Thanks....

**Comment by khsily** [comment]
@AvijitDutta95 
Sorry, here's more detail.

you should use TouchableOpacity for the top wrapper View with {borderWidth: 0}

ex)
`<TouchableOpacity style={{
                height: '100%',
                justifyContent: 'center',
                borderWidth: 0,
                paddingRight: 132.5,
            }}>
                <View style={{
                    width: 45,
                    height: 30,
                    borderRadius: 25,
                    borderColor: '#ffffff',
                    borderWidth: 1.5,
                    justifyContent: 'center',
                    alignItems: 'center'
                }}>
                    <Text style={{
                        fontSize: 20,
                        color: '#ffffff'
                    }}>+</Text>
                </View>
            </TouchableOpacity>`

**Comment by AvijitDutta95** [comment]
Thank you so much for your help @khsily , Its work perfectly as i need 👍 Thanks once again... :-)

**Comment by AvijitDutta95** [comment]
Hi @khsily , can you tell me one more thing that how can i handle onPress from custom nav button. for now i'm trying to you deep-linking like that way: 

```
<TouchableOpacity style={styles.container} onPress={() => Navigation.handleDeepLink({ link: 'showNewPage' })}>
                <View style={styles.buttonContainer}> 
                    <Text style={styles.buttonText}>{this.props.text}</Text> 
                </View> 
            </TouchableOpacity> 
```
this is my custom nav button component:

and i'm handling it on component like this way: 

```
onNavigatorEvent(event) {
    if (event.type === 'DeepLink') {
      if (event.link === 'addListing') {
        this.onAddListing();
      }
    }
  }

  componentWillMount() {
    this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
  }
```

**Comment by anonrig** [comment]
@AvijitDutta95 any luck on solving this issue?

**Comment by witalobenicio** [comment]
@AvijitDutta95 @anonrig maybe you should create a method that uses `Navigation.handleDeepLink()` and bind this method in the onPress like this: `this.myMethod.bind(this)`
