### ISSUE TITLE
throwOnImmutableMutation - you attempted to set the key 'enabled'.... on showModal with buttons

### ISSUE THREAD

**Issue by dbelchev** [wix/react-native-navigation#2139]
### Issue Description

When you once open a modal with navigatorButtons: {leftButtons, right buttons}, close it and open it again the following red screen appears:
Message: You attempted to set the key "enabled" with the value 'true' on an object that is meant to be immutable and has been frozen.
https://drive.google.com/open?id=1MFvlYEIGHxyMy6ZjiuGbuxxejM7pWuzL

PLEASE NOTE, that a working fix for this issue has been approved by @guyca and provided here by @pedro, but for some reason has never been merged : https://github.com/wix/react-native-navigation/issues/394#issuecomment-312652537

---
### Environment
* React Native Navigation version: 1.1.256
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device: Android Nougat, Emulator: Android Oreo

**Comment by tschoffelen** [comment]
Related to #1928.
