### ISSUE TITLE
Is 2.0 compatible with react-native above 0.25.1?

### ISSUE THREAD

**Issue by musicode** [wix/react-native-navigation#214]
My react-native version is 0.30.0, so I can't use 2.0?

if yes, how long to wait for it?

**Comment by DanielZlotin** [comment]
We have reports of bugs with RN versions other than 0.25.1. An upgrade to RN is scheduled for v2.0.0 milestone. I can't guarantee a timeline, but we think of trying to upgrade in 2 weeks (production takes priority)

**Comment by explorigin** [comment]
@musicode I'm currently running RN 0.31 with RNN 2.0.  It was a painful process to get here though.  Now that it's merged into mainline, I'll be posting some bugs related to my experience.

**Comment by AdamBrodzinski** [comment]
@musicode were you able to install on 0.30 without any forks? I'm trying to here: #223 and am running into issues.

**Comment by musicode** [comment]
@AdamBrodzinski  my rnn version is 1.x, and rn version is 0.30.0, without any forks.

**Comment by AdamBrodzinski** [comment]
@musicode ah great to hear! Thanks!! If you have a spare moment would you mind looking here to see if anything jumps out at you? Between the readme and example differences I couldn't get it working:
https://github.com/wix/react-native-navigation/issues/223

**Comment by DanielZlotin** [comment]
please see https://github.com/wix/react-native-navigation/issues/234
