### ISSUE TITLE
Tab bar renders on first component and then hides in tab based app

### ISSUE THREAD

**Issue by tokict** [wix/react-native-navigation#2143]
### Issue Description
Although I have set tabBarHidden : true the tab bar shows on first rendered tab when opening app and then quickly hides on android. On IOS it doesnt show but my page has a hole where tab should be. 

How can I get rid of this damn tab so it doesnt flash or make an empty space on first component?

### Steps to Reproduce / Code Snippets / Screenshots

Have tabs. Try to hide the tab bar on first rendered view both on ISO and Android

---
### Environment
* React Native Navigation version:1.1.264
* React Native version:0.50.3
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Debug and release. Everywhere

**Comment by tokict** [comment]
Seriously? Not even a reason for closing or telling me what I am doing wrong

**Comment by tokict** [comment]
@guyca 
![image](https://user-images.githubusercontent.com/3405336/32614117-33a03c1c-c575-11e7-9969-24cb6882d143.png)

Im still seeing this on IOS on first load. Toggling tabs gets rid of it

**Comment by guyca** [comment]
Did you specify `drawUnderTabBar: true`?

**Comment by tokict** [comment]
Ah, it goes away with that. Thanks mate!

**Comment by tokict** [comment]
@guyca  Should I be seeing this. I just noticed it. Is it because of my styles or something on my side?
![image](https://user-images.githubusercontent.com/3405336/32660305-fb2b42b2-c62a-11e7-9d16-50428c0ee408.png)
