### ISSUE TITLE
Android FlatList bug with NavBar

### ISSUE THREAD

**Issue by masterpetit** [wix/react-native-navigation#2144]
### Issue Description

With a full screen `{flex: 1}` FlatList, if the NavBar is visible, the FlatList cannot scroll to the end. The bug only occurs in Android, iOS works fine and there is no problem if the NavBar is hidden.

### Steps to Reproduce / Code Snippets / Screenshots

```
import React, { Component } from 'react';
import { StyleSheet, Text, View, FlatList, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default class Test extends Component {
  static navigatorStyle = {
    tabBarHidden: true
  };

  render() {
    return (
      <View style={styles.container}>
        <FlatList
          data={[
            { key: 'a' },
            { key: 'b' },
            { key: 'c' },
            { key: 'd' },
            { key: 'e' },
            { key: 'f' },
            { key: 'g' },
            { key: 'h' },
            { key: 'i' },
            { key: 'j' },
            { key: 'k' }
          ]}
          renderItem={this._renderItem}
        />
      </View>
    );
  }

  _renderItem = ({ item }) => {
    return (
      <View style={styles.row}>
        <Text>{item.key}</Text>
      </View>
    );
  };
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white'
  },
  row: {
    backgroundColor: 'red',
    height: 80,
    width,
    borderWidth: 1,
    borderColor: 'blue'
  }
});
```

---
### Environment
* React Native Navigation version: 1.1.268
* React Native version: 0.50.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Multiple Devices both Release and Debug.

**Comment by irwing-reza** [comment]
might be related with this one [1112](https://github.com/wix/react-native-navigation/issues/1112)

**Comment by irwing-reza** [comment]
I just did a test and found that on:
React Native Navigation version: 1.1.245
React Native version: 0.48.4 
The issue doesn't happen.

**Comment by masterpetit** [comment]
I am not sure if this is related to [1112](https://github.com/wix/react-native-navigation/issues/1112). The provided fix does not solve this bug.

In this case the FlatList can actually scroll but a weird offset is added that prevents it from scrolling to the bottom of the list.

Downgrading to React Native 0.48.4 is not an option for me because 0.50 contains bug fixes that I need.

**Comment by danilobuerger** [comment]
+1

**Comment by masterpetit** [comment]
I currently use the following workaround.

Add the following to the navigatorStyle of your screen.
`{ drawUnderNavBar: Platform.OS !== 'ios' }`

Add the following to your FlatList/ScrollView/(container)View:
`{marginTop: 56}`

The same problem occurs with the TabBar on Android. 
This workaround can also be used to fix that (use drawUnderTabBar and maringBottom).

**Comment by celso-henrique** [comment]
+1

**Comment by celso-henrique** [comment]
Its happening with ScrollView and View elements too, if you centralize any element inside the ScrollView or View it starts to bounce (probably because the height calc problem).

**Comment by pureblood** [comment]
Would love some attention to this. Is the bug inside RNN or RN?
How do I downgrade if i created a new app with RN > 0.50?

**Comment by celso-henrique** [comment]
I think its related to #2138

**Comment by pureblood** [comment]
Yes I am watching that too. @guyca said they plan on upgrading v1 to RN 0.50 in couple weeks. I can wait till then.

**Comment by thechefchen** [comment]
+1

I'm experiencing a lot of dropped frames. I tried to above trick above about setting `drawUnderNavBar` but no luck. 

I'm using 0.50.3. After downgrading back to 0.49.3, the drop frame issue is gone.

**Comment by hhunaid** [comment]
I was okay with downgrading to 0.49.x until I ran into [react-native/16518](https://github.com/facebook/react-native/issues/16518) which is fixed in 0.50. I am really desperate for a fix

**Comment by cedricode** [comment]
+1 same issue here, in #2138 , this issue is well explained, hope there will be a fix soon..

**Comment by Momazo7u7** [comment]
Welp, here using version 2.0 and still this bug is present.

**Comment by adybuciuman** [comment]
I tried <ScrollView style={{height: 0}} /> and it worked. Is a fixed suggested for ScrollView but maybe is working for FlatList as well. Is a solution I saw suggested on bug #1112
