### ISSUE TITLE
setSoftInputMode encounters Java error -- "is not abstract..."

### ISSUE THREAD

**Issue by johngoren** [wix/react-native-navigation#2145]
### Issue Description
To set the Android soft input mode, I went into MainApplication and pasted the @override method for onCreate() that was suggested in the docs. But I received a build error: "is not abstract and does not override abstract method onActivityDestroyed(Activity) in ActivityLifecycleCallbacks."

I then tried to implement the missing (?) methods but it didn't seem to make the compiler happier.

### Steps to Reproduce / Code Snippets / Screenshots

Added the Java code recommended under Android-specific Use Cases for setting softInput mode. Also tried importing any Android modules that seemed to be missing (android.app.activity, android.os.Bundle are supposed to be imports, I think.)

---
### Environment
* React Native Navigation version: 1.1.268
* React Native version: 0.49
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulated, debug.

<img width="750" alt="screen shot 2017-11-09 at 17 26 05" src="https://user-images.githubusercontent.com/748214/32619578-1a03d2a2-c573-11e7-9932-985485e8ac6d.png">

<img width="637" alt="screen shot 2017-11-09 at 17 24 52" src="https://user-images.githubusercontent.com/748214/32619524-f249297e-c572-11e7-84f8-ee24ecf31c95.png">

**Comment by N3TC4T** [comment]
Hi @johngoren 

you need to do something like this 

```
  @Override
  public void onCreate() {
      super.onCreate();
      registerActivityLifecycleCallbacks(new ActivityLifecycleCallbacks() {
          @Override
          public void onActivityCreated(Activity activity, Bundle savedInstanceState) {
              activity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
          }

          @Override
          public void onActivityStarted(Activity activity) {

          }

          @Override
          public void onActivityResumed(Activity activity) {

          }

          @Override
          public void onActivityPaused(Activity activity) {

          }

          @Override
          public void onActivityStopped(Activity activity) {

          }

          @Override
          public void onActivityDestroyed(Activity activity) {

          }

          @Override
          public void onActivitySaveInstanceState(Activity activity, Bundle outState){

          }

      });
}
```

**Comment by hmenzagh** [comment]
Thanks a lot that was really unclear ! So why is that ?
