### ISSUE TITLE
Android - Can't set TopTabs font family

### ISSUE THREAD

**Issue by fmorato** [wix/react-native-navigation#2146]
### Issue Description

Can't set TopTabs font family.

### Steps to Reproduce / Code Snippets / Screenshots

There is no implementation for the feature.

How can I set the TopTabs font family? I tried to follow the code structure and copy other font definitions and created the method bellow in TopTabs.java. It is then called in TopBar.java's `setTopTabsStyle`

 ```
   void setTopTabsFontFamily(StyleParams style) {
        if (style.topTabFontFamily != null && style.topTabFontFamily.hasFont()) {
            ViewGroup vg = (ViewGroup) this.getChildAt(0);
            int tabsCount = this.getTabCount();
            for (int j = 0; j < tabsCount; j++) {
                ViewGroup vgTab = (ViewGroup) vg.getChildAt(j);
                int tabChildsCount = vgTab.getChildCount();
                for (int i = 0; i < tabChildsCount; i++) {
                    View tabViewChild = vgTab.getChildAt(i);
                    if (tabViewChild instanceof TextView) {
                        ((TextView) tabViewChild).setTypeface(style.topTabFontFamily.get());
                    }
                }
            }
        }
    }
```
The whole code executes, including `setTypeface` but nothing happens. What am I missing?

---
### Environment
* React Native Navigation version: 1.1.262
* React Native version: 0.50.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device v 6.0.1

**Comment by hoorsa** [comment]
+1
