### ISSUE TITLE
How to passProps to screen in startSingleScreenApp?

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#2147]
### Issue Description
I would like to give props to the screen I init the app in `startSingleScreenApp`. But according to the documentation: https://wix.github.io/react-native-navigation/#/top-level-api?id=startsinglescreenappparams you can only use `passProps` to pass props to *ALL* top level screen. How can I pass props to only the initial screen?

---
### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.48.4
* Platforms: both
* Device info: All

**Comment by buffaly** [comment]
try this
```
Navigation.startSingleScreenApp({
        // add this line
        passProps: { ...propsData },
        screen: {
          screen: 'screen-name',
          title: 'title',
        },
      });
```

**Comment by pqkluan** [comment]
It's been a while since there is a response, I'll assume the problem is solved. Feel free to re-open if needed.
