### ISSUE TITLE
How to check for authentication status on every screen change?

### ISSUE THREAD

**Issue by skumarcm** [wix/react-native-navigation#2149]
My app includes screens that are protected by authentication and others that are public. Additionally, the server will send push notifications to log the user out in certain exception conditions.
I am looking for a solution that will help me to check the authentication status on each screen change and I do not want to duplicate the code in each screen as the check is the same.

1. Is there a common place where I can put this logic under react-native-navigation?
2. Alternatively, is there an event that indicate a screen change in react-native-navigation that I can capture and check for authentication status?

Your help will be highly helpful.
Thank you very much for your wonderful product!!!

**Comment by noambonnie** [comment]
I'm dealing with a similar situation. What I did was listen on app state (using redux store) for the LOGOUT state. When the state changes to logged-out, I use Navigation.showModal(). 

My problem currently is during app start-up - I can't find a way to know when Navigation.startSingleScreenApp() finished initialization. I need that so I can show the Login screen when the app first launches. Do you know how to know when the app launched?

**Comment by pqkluan** [comment]
@skumarcm I don't think issue belong to RNN but the way you handle the app business. Personally, I'll use `redux-sagas` to handle global event cases like receive push-notification message. If you need to monitor navigation relates status, a screen HOC is what you want.

@noambonnie You might want to check user **authentication** before start the app.

**Comment by noambonnie** [comment]
@pqkluan But if I want to display the login screen after app started - how do I do that? How do I know that the app started and I can now navigate to a modal?

**Comment by skumarcm** [comment]
I have been using ionic prior to switching to React-Native. in Ionic, there is an event called "StateChangeEvent" that can be captured at each state transition and any check can be performed before the transition is completed. I was looking for a similar solution here as well.

What I am planning to do currently is to use Axios along with an interceptor that will check for authentication on every http request sent from the app to the server. If there is an authentication error, then the user will be redirected to a login page after popping all the navigation stack. Even though this is not exactly what I want, this will suffice for now until a solution is reached.

The primary reason why I need to check for authentication on every screen transition is due to a security measure that I implemented in my app which will allow the user to login from only one device at any given time. If the user logs in from a different device while he is logged in another device, then the user will be logged out of the first device with a warning about the second login. This is effected through websocket connection. Hence the logout can happen any time.

**Comment by pqkluan** [comment]
@noambonnie If you only want to check the authentication **after** the app started, trigger that code at the `componentDidMount` function of the first screen.

@skumarcm That could be easy implement if you are using `redux-sagas` by creating a utility function to handle network request. The reason why `redux-sagas` is needed because sagas function could access the app's state on their own, so you don't have to gather the data before calling them every time.
