### ISSUE TITLE
tab bar border color and shadow?

### ISSUE THREAD

**Issue by ericyip** [wix/react-native-navigation#2151]
How can I style the tab bar border and shadow?
I've tried `tabBarHideShadow`, but nothing's changed

**Comment by pqkluan** [comment]
Hi @ericyip 

The current API doesn't support change tab bar color, and `tabBarHideShadow` is for iOS only, that means you should put it inside of `tabsStyle` (not `appStyle`) props when calling `startTabBasedApp`.

I'll close this issue for now. But feel free to re-open it if needed.
