### ISSUE TITLE
this.props.navigator.pop not calling constructor() & ComponentDidMount()

### ISSUE THREAD

**Issue by chixpc123** [wix/react-native-navigation#2152]
### When i call this.props.navigator.pop(), it's not calling popped screen's constructor() & componentDidMount()

My usage is something like..

* Profile Screen showing : No. of token for example 5 tokens.

* there is a button to buy tokens on tap that button, it's calling this.props.navigator.push('MY_PAYMENT_SCRREN')
* After payment on MY_PAYMENT_SCREEN i'm storing total updated token in AsyncStorage and pop screen (Means it will redirect me to my profile screen)

* in my profile screen, i'm calling a function from constructor() that setState for totalUpdated token, but it's not calling after redirected from MT_PAYMENT_SCREEN. I did also tried to call that function in componentDidMount but componentDidMount() also not calling...

---
### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by markhu** [comment]
Did you typo the call
`this.props.navigator.push('MY_PAYMENT_SCRREN')` ? --the "SCRREN" should be
`this.props.navigator.push('MY_PAYMENT_SCREEN')`

**Comment by guyca** [comment]
Screens stay mounted when another screen is pushed into the stack. So when you pop back to a screen, it's already created and mounted.

**Comment by KthProg** [comment]
That kind of kills logic like fetching data in the constructor though. Can't you at least provide us the option to remount the screen?

**Comment by Gujie-Novade** [comment]
I have a similar use case where the screens in the stack need to be updated. How can it be done?

**Comment by Batistleman** [comment]
@Gujie-Novade check out https://wix.github.io/react-native-navigation/#/docs/Usage?id=screen-lifecycle perhaps those can help.

**Comment by Gujie-Novade** [comment]
@Batistleman `componentDIdAppear()` worked.
Thanks!
