### ISSUE TITLE
Carousel Problems (Maybe Major)

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#2153]
### Issue Description
I can not get any carousel our swipable library to work in RNN:  I've tried the following

- https://github.com/yjy5264/react-native-card-carousel
- https://github.com/phil-r/react-native-looped-carousel
- https://github.com/nick/react-native-carousel
- https://github.com/juangl/react-native-infinite-carousel
- https://github.com/davidsamacoits/react-native-swipeable-parallax-carousel
- https://github.com/alexbrillant/react-native-deck-swiper

I've also tried the following with is based on wix/react-native-interactable 

- https://github.com/ptmt/react-native-swipable-deck/blob/master/DeckViaInteractable.js
- https://github.com/machadogj/react-native-carousel-control

The only packages I was able to get to work were
- https://github.com/archriss/react-native-snap-carousel

### Steps to Reproduce / Code Snippets / Screenshots
- In each case, I would load the example into and react-native-navigation screen.
- In each case, the swipe or the carousel view would not move or would only barely nudge.  Perhaps this is similar to the issues with android ViewPager.  I've tried the suggested solution but to no avail. 

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.270
* React Native version: 0.49.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device

**Comment by smooJitter** [comment]
Interestingly enough... all of the above work perfectly fine inside a modal view.  What gives.

**Comment by efstathiosntonas** [comment]
Yeah, i've mentioned here the same, i've included a gif to demonstrate the issue

https://github.com/wix/react-native-navigation/issues/2153?_pjax=%23js-repo-pjax-container

**Comment by mustafadroid** [comment]
I also encountered the same issue. I use react-native-swiper and react-native-scrollable-tab-view which is working fine when I first enter the view. However, if I visit another view using navigator.push() then I pop the view and after that this issue always occurs. I cannot swipe through like usual. 

After the issue happening what i can do to work around this problem is either using navigator.resetTo() method or restart the apps. I wonder why.

**Comment by smooJitter** [comment]
Sigh...  all just want support for ViewPager behavior.   I thought this would be handled in V2 but it isn’t.   Frankly, without support for view page and carousel behavior,  I don’t see much reason to go with V2.  Carousels are indeed popular. I don’t understand how anyone can doubt the prevalence of swipable carousels.  Of the many packages, some with more than 1,000 stars, only snap-carousel works with RNN!
