### ISSUE TITLE
[V2.0] Toggle Drawer not working on android

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#216]
"react-native": "0.31.0",
"react-native-navigation": "next", 
 (2.0.0-experimental.70)

Toggle drawer called from View:

`<View style={styles.row}>
                    <TouchableOpacity onPress={this._onPressButton.bind(this) }>
                        <View style={{ paddingLeft: 10 }}>
                            <FontAwesome name="bars" size={20} color="white"/>
                        </View>
                    </TouchableOpacity>
</View>`

`_onPressButton() {
        alert('menu');
        this.props.navigator.toggleDrawer({
            side: 'left',
            animated: true
        });
    }`

IOS: Good
Android: not working. (swiper from left screen is good)

**Comment by guyca** [comment]
FIxed. Thanks for reporting 👍
