### ISSUE TITLE
add automatic changelog

### ISSUE THREAD

**Issue by DanielZlotin** [wix/react-native-navigation#2162]
https://github.com/skywinder/github-changelog-generator

**Comment by DanielZlotin** [comment]
This require us to clean up all open issues and PRs like we did in https://github.com/wix/detox/labels.
All issues and PRs should have correct labels

**Comment by DanielZlotin** [comment]
auto changelog should exclude all issues without label

**Comment by skovhus** [comment]
Related to https://github.com/wix/react-native-navigation/issues/1551

**Comment by yogevbd** [comment]
Done
