### ISSUE TITLE
NavBarBackgroundColor not working in latest version

### ISSUE THREAD

**Issue by Seeker93** [wix/react-native-navigation#2166]
### Issue Description

Since I have upgraded to react-native-navigation 1.1.275 (was on 1.1.272 and it works there), my navigatorStyle property 'navBarBackgroundColor' is not being honored. It simply assumed the color defined in 'ScreenBackgroundColor' (even if this prop is not set)

### Steps to Reproduce / Code Snippets / Screenshots
Add this style object:

        navigatorStyle: {
          navBarTextColor: 'white',
          navBarButtonColor: 'white',
          navBarBackgroundColor:  'blue',
          navBarHideOnScroll: false,
          screenBackgroundColor: 'white',
          statusBarTextColorScheme: 'light',
          statusBarColor: 'blue',
          topTabTextColor: 'white',
          topTabIconColor: 'white',
          topBarElevationShadowEnabled: true,
          tabBarHidden: true,
          topTabsHeight: 48,
          drawUnderTabBar: true,
          topBarBorderColor: 'blue',
          topBarBorderWidth: 0.5
        },
### Environment
* React Native Navigation version: 1.1.275
* React Native version: 0.50.3
* Platform(s) (iOS, Android, or both?): Android

**Comment by guyca** [comment]
I tried with the following:

```js
class Actions extends React.Component {
  static navigatorStyle = {
    navBarSubtitleFontFamily: 'sans-serif-condensed',
    navBarBackgroundColor: 'green',
    screenBackgroundColor: 'yellow',
    topBarBorderWidth: 0.5,
    topBarBorderColor: 'purple',
    drawUnderTabBar: true
  }
...
}
```

Works as expected. Can you reproduce this in the example app?

**Comment by Seeker93** [comment]
Hi guyca.

Unfortunately, I cannot reproduce in the example app. However, I realised that if I remove    topBarBorderWidth and topBarBorderColor in my navigatorStyle, then everything works as intended. Everything worked fine in  1.1.272. 

I realise that not being able to reproduce it in the example app makes it very hard to debug, but do you know of any interactions between topBarBorderColor and navBarBackgroundColor?
