### ISSUE TITLE
Header image size change in released apk

### ISSUE THREAD

**Issue by ShahidAli786** [wix/react-native-navigation#2167]
`   leftButtons:[ {
        icon: require("../assets/Images/menu.png"),
      }],`

![screenshot_20171115-175817](https://user-images.githubusercontent.com/24582758/32836945-944b0932-ca31-11e7-9923-d7ba0cb3e47a.png)

-----debug screen shot of header

![screenshot_20171115-180304](https://user-images.githubusercontent.com/24582758/32836952-9c4fb2b8-ca31-11e7-83b8-5d18a7d239f6.png)

--released screen shot of header

# Header Icon Size is change in released apk
 
Environment:
"react": "16.0.0",
"react-native": "0.50.2",
"react-native-navigation": "^1.1.262",

**Comment by sqow** [comment]
@ShahidAli786 Having the same issue. Did you ever find a resolution?
