### ISSUE TITLE
Storyboard fades away before React is done loading

### ISSUE THREAD

**Issue by ds8k** [wix/react-native-navigation#2168]
### Issue Description

When using a Launch Storyboard versus static launch images, the storyboard displays, then quickly fades away to a black screen. From here React finishes loading everything. Previously, the static images would stay up until the app was done loading.

### Steps to Reproduce / Code Snippets / Screenshots

Implement a Launch Storyboard and set it to be used as the launch screen. Launch application on simulator/device running iOS 11. Storyboard will display, then fade away.

---
### Environment
* React Native Navigation version: 1.1.275
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X Simulator, iPhone 6+ Device. Both on 11.1

**Comment by rolfb** [comment]
Seeing the same thing.

**Comment by rolfb** [comment]
I wonder if the storyboard logic in RCCManager may have some implicit dependencies of the storyboard structure which is unknown.

A quick fix would be to load a view in AppDelegate.m in didFinishLaunchingWithOptions just before the initiation of RCCManager. If your storyboard is called LaunchScreen and the UIViewController is first responder, and has an identity of "LaunchScreen" you can do the following just before. Your mileage may vary on this.

```
UIViewController *launchScreen = [[UIStoryboard storyboardWithName:@"LaunchScreen"
                                                             bundle:NULL] instantiateViewControllerWithIdentifier:@"LaunchScreen"];;
  self.window.rootViewController = launchScreen;
  
  [self.window makeKeyAndVisible];
```
