### ISSUE TITLE
showModal causes push unavailable?

### ISSUE THREAD

**Issue by winglight** [wix/react-native-navigation#217]
My RN version is 0.30.0, RNN is 2.0 latest.
If I push a modal screen A by showModal function and then close it by dismissAllModals function from screen C, I can't push the other screen by push function still from C any more, like a common screen B. Is there any clue?

**Comment by guyca** [comment]
I'm not sure I understood the scenario you're trying to describe.

In `example-redux` project, I the following worked for me:
1. show modal
2. dismiss all modals
3. push screen

**Comment by winglight** [comment]
Your rn & rnn version same as mine? And it's fine on iOS?  On simulator or real device?

? 2016?8?19??21:54?Guy Carmeli <notifications@github.com<mailto:notifications@github.com>> ???


I'm not sure I understood the scenario you're trying to describe.

In example-redux project, I the following worked for me:
1. show modal
2. dismiss all modals
3. push screen

-

**Comment by guyca** [comment]
I'm using RN 0.25.1 and RNN 2.0

**Comment by guyca** [comment]
@winglight I'm closing this. If you still have any issues please reopen.

**Comment by alidawud** [comment]
I'm facing the same issue. @winglight How did you solve it?

**Comment by winglight** [comment]
@alidawud As I know, the only way to solve it is down your RN to 0.25.1. Though, I choose a inner component instead of a modal screen.
