### ISSUE TITLE
(Android) tapBackgroundToDismiss: "View with tag XX is not registered as a root view"

### ISSUE THREAD

**Issue by chrismllr** [wix/react-native-navigation#2170]
### Issue Description
Closing lightbox by tapping background crashes app

### Steps to Reproduce / Code Snippets / Screenshots
1. Show Lightbox
```
this.props.navigator.showLightBox({
  screen: EDIT_CONFERENCE_INFO,
  style: {
    backgroundBlur: 'dark',
    backgroundColor: '#00000080',
    tapBackgroundToDismiss: true
  }
});
```
2. Tap outside lightbox to close
3. Crashes
<img width="613" alt="screen shot 2017-11-15 at 4 54 35 pm" src="https://user-images.githubusercontent.com/9942917/32864682-b9174692-ca25-11e7-887a-b07cfac10fad.png">

---
### Environment
* React Native Navigation version: `"react-native-navigation": "^1.1.246"`
* React Native version: `"react-native": "0.49.3"`
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel API_23 emulator

**Comment by fliPmitKlammern** [comment]
Probably related to this issue: https://github.com/wix/react-native-navigation/issues/1502

**Comment by pqkluan** [comment]
Close this issue due to duplicate with #1502
