### ISSUE TITLE
navBarCustomView cannot show ImageBackground

### ISSUE THREAD

**Issue by phuongluu98** [wix/react-native-navigation#2171]
### Issue Description
Hi, I'm using navBarCustomView and I have an ImageBackground on the View. But i cannot fill my ImageBackground full the header navbar

// myHeader.js
```
return (
            <ImageBackground style={styles.bg} source={require('./../../assets/images/header.jpg')}>
                    <IconMoon name='logo' color={'#fff'} size={20}/>
            </ImageBackground>
        )
```

//  my tabbar config 
```
{	
screen: 'lizks.feed',
title: 'Feed',
    navigatorStyle: {
        navBarBackgroundColor: 'transparent',
        navBarButtonColor: 'transparent',
        navBarHideOnScroll: false,
        statusBarHideWithNavBar: false,
        statusBarBlur: false,
        statusBarHidden: true,
        navBarTransparent: true,
        navBarCustomView : 'lizks.header',
    }
},
```

// And this is my view
<img width="378" alt="screen shot 2017-11-16 at 12 29 47 pm" src="https://user-images.githubusercontent.com/18485553/32875312-df061f78-cac9-11e7-93b0-72b079c716f0.png">

---
### Environment
* React Native Navigation version: ^1.1.257
* React Native version: 0.49.5
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 7 plus

**Comment by guyca** [comment]
The padding are added by the system and I believe we weren't able to easily remove them (pr is welcome) I think you'll need to set the background image in native:

```obj
[[UINavigationBar appearance] setBackgroundImage:[[UIImage imageNamed:@"navbarimg.png"] resizableImageWithCapInsets:UIEdgeInsetsMake(0, 0, 0, 0)] forBarMetrics:UIBarMetricsDefault];
```

**Comment by phuongluu98** [comment]
I put your code into AppDelegate.m, but it's not work.
