### ISSUE TITLE
Android navigation bottom bar disappears when screen is redrawn

### ISSUE THREAD

**Issue by edvinasbartkus** [wix/react-native-navigation#218]
I guess it's being worked on android 2.0 heavily, but maybe my report will help improving android navigation.

It does not happen on emulator but on real devices navigation android bottom bar disappears once the screen is redrawn. I will try to illustrator with screens:

# 1 Step. Navigation bar is initialized
![1](https://cloud.githubusercontent.com/assets/202988/17806567/02c31aa0-660e-11e6-9b5a-6ac04842141f.png)

# 2 Step. I draw loading screen to get data. Navigation bottom bar is present
![2](https://cloud.githubusercontent.com/assets/202988/17806587/1ab18ff2-660e-11e6-994a-e7e0c5a7ad7d.png)

# 3 Step. Once I redraw scene with my view the navigation bottom bar disappears
![3](https://cloud.githubusercontent.com/assets/202988/17806637/58208f8c-660e-11e6-935c-52985813c9f4.png)

# 4 Step. I push another screen and then I go back and navigation bar reappears
![3](https://cloud.githubusercontent.com/assets/202988/17806598/2b92feb4-660e-11e6-869e-48385a4096bf.png)

Same happens when I navigate through tabs.

**Comment by guyca** [comment]
Hey @edvinasbartkus Can you please check how the `drawUnderTabBar` property on `navigatorStyle` is configures in your screens?

**Comment by edvinasbartkus** [comment]
it's `drawUnderTabBar: true`. I will test out with `false`.

**Comment by guyca** [comment]
And also `tabBarHidden`. thanks 👍

**Comment by edvinasbartkus** [comment]
Changing to `drawUnderTabBar: false` fixed an issue. I will solve the issue by specifying Platform specific value as there is no need to draw under on Android (navbar is not translucent). 

`tabBarHidden` was undeclared.

**Comment by agumack** [comment]
Hi @edvinasbartkus 
your screenshot =>i see tab label not show. This is error or your style?

I am have problem too, only first tab show label. 

![tab](https://cloud.githubusercontent.com/assets/202988/17806598/2b92feb4-660e-11e6-869e-48385a4096bf.png)

**Comment by edvinasbartkus** [comment]
@agumack 
It's shows the label once the tab is active. I think I was looking at android implementation and there is an option for that.

https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java#L46

You should be able to pass as an option for it ;)

**Comment by agumack** [comment]
@guyca 
this error seem come bank after i upgrade to 2.0.0-experimental.126

**Comment by guyca** [comment]
Hey @agumack 
I don't think there ever was an error in this case. The issue is that on Android, screens are transparent unlike on iOS where they have a default white color. So when you push a screen and show a loader for instance, the previous screen is visible until loading is done and a view with flex 1 and some background color is rendered.

We will add a default white color for screens soon and add the ability to change the default screen color to avoid issues like this.

**Comment by nguyenminh797** [comment]
I using configs:
`forceTitlesDisplay: true`
It working ....
