### ISSUE TITLE
Blank screen on android before multitasking

### ISSUE THREAD

**Issue by alexmbp** [wix/react-native-navigation#2180]
### Issue Description
I've followed the guide for android. My App is possible to build and navigation is working.
With one issue - on Android I see an app only after I go to multitasking and back.

Here is an video:
http://take.ms/8ODDUw

---
### Environment
* React Native Navigation version: 0.50.2
* React Native version: 1.1.273
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug, Android 7

**Comment by Noitidart** [comment]
Yes!! This is what was getting me. My gosh took days to figure this out!!! Everytime I set it up and got this blank screen then gave up on RNN v1. Then I come back weeks later try again same. This third time I really struggled with it. And this is what it was.

I didn't know what "multitasking" meant, but I fond this solution like this:
When you see the blank screen on startup in android:

1) hit the "square" button to show all open apps
2) Then press on your app
3) voila it renders

Here is screenshots of steps:

![](https://i.imgur.com/MuNJ81n.png)

**Comment by alexmbp** [comment]
@Noitidart Yes! That's it! Honestly - I moved off from react-native-navigation for now and using react-navigation.
And yes - that was my issue and I was fixing it the same way. I just worry that it can be reproduced in production.

**Comment by ppozniak** [comment]
Oh, didn't know this gets "fixed" by entering open applications mode. I also get white screen if I exit and then relaunch application. Do you guys know if this happens only on emulator?
