### ISSUE TITLE
3D Touch preview and pop iOS

### ISSUE THREAD

**Issue by birkir** [wix/react-native-navigation#2181]
### Issue Description

How hard would it be to implement Peek and Pop with 3D touch like Apple uses all over their apps?

The view controller would have to implement the `UIViewControllerPreviewingDelegate` and a native component would have to register the 3d touch to push a screen.

```js
<Preview target={{ screen: 'screenId', passProps: '123' }}>
  <Text>Click me</Text>
</Preview>
```
### Video

![iOS](https://media.giphy.com/media/26u44g4QEjbks9Htm/giphy.gif)

http://gph.is/2zQayJJ

**Comment by birkir** [comment]
Hello @birkir 
Is this what you are looking for? #2186 
> Yes. Thanks.

**Comment by brunolemos** [comment]
I think you can close? 😄
