### ISSUE TITLE
Immutable error when passing appStyle [iOS]

### ISSUE THREAD

**Issue by lglomer** [wix/react-native-navigation#2182]
### Issue Description

Error: You attempted to set the key 'statusBarColor' with the value 486520604 on an object that is meant to be immutable and has been frozen.

<img width="449" alt="screen shot 2017-11-18 at 11 02 28" src="https://user-images.githubusercontent.com/15572194/32978697-14d7b486-cc50-11e7-8887-7c774653addf.png">

### Steps to Reproduce / Code Snippets / Screenshots

- When the app starts a welcome screen is launched by calling `Navigation.startSingleScreenApp`.
- Then after the user has authenticated I called `Navigation.startTabBasedApp` and passed an appStyle object to it.

App.js:
```
import { Navigation } from 'react-native-navigation';
import { Provider } from 'react-redux';
import configureStore from './src/redux/configureStore';
import { registerScreens } from './src/screens';
import * as appActions from './src/modules/_global/reducer';

const highlightsIcon = require('./src/img/ic_bookmark_border.png');

const store = configureStore();
registerScreens(store, Provider); // register app's screens

const appStyle = {
  statusBarColor: '#B71C1C'
};

const navigatorStyle = {
};

const tabsStyle = {
  tabBarSelectedButtonColor: '#D32F2F'
};

class App {
  constructor() {
    // execute onStoreUpdate when the app's state changes
    store.subscribe(this.onStoreUpdate.bind(this));
    store.dispatch(appActions.appInitialized());
  }

  startApp({ loginState }) {
    switch (loginState) {
      case null:
        break;
      case 'welcome':
        this.startWelcomeApp();
        break;
      case 'app':
        this.startFullApp();
        break;

      default:
        console.error('Unknown app root');
    }
  }

  startFullApp() {
    Navigation.startTabBasedApp({
      tabs: [
        {
          label: 'Groups',
          title: 'Groups',
          screen: 'Groups.Groups',
          icon: highlightsIcon,
          navigatorStyle
        }
      ],
      tabsStyle,
      appStyle,
    });
  }

  startWelcomeApp() {
    Navigation.startSingleScreenApp({
      screen: {
        screen: 'Groups.Welcome',
        title: 'Welcome',
      }
    });
  }

  onStoreUpdate() {
    const { root } = store.getState();
    // handle a root change
    if (this.currentRoot !== root) {
      // handle a login change
      const appFirstOpens = !this.currentRoot;
      const loginStateChanged = this.currentRoot && this.currentRoot.loginState !== root.loginState;

      if (appFirstOpens || loginStateChanged) {
        this.startApp(root);
      }

      this.currentRoot = root;
    }
  }

  render() {
    return (
      null
   );
  }
}

export default App;

```
---
### Environment
* React Native Navigation version: ^1.1.268
* React Native version: 0.50.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 11.1 with iPhone 8 and iPhone X simulator

**Comment by kastopia** [comment]
I started getting a similar error with `tabBarButtonColor`, I think the issue is connected.
It used to work well with version `1.1.208`, so try using that version for now.
This bug was introduced in version `1.1.209`.

**Comment by RyanWarner** [comment]
I was able to get around this error by explicitly declaring my app style in line (instead of defining the variables above):

Navigation.startTabBasedApp({
      tabs: [
        {
          label: 'Groups',
          title: 'Groups',
          screen: 'Groups.Groups',
          icon: highlightsIcon,
          navigatorStyle
        }
      ],
      appStyle: {
        statusBarColor: '#B71C1C'
      }
    });
```

I have no idea why this works, but I'm curious if it works for you too.

**Comment by brunolemos** [comment]
I have the same problem with same situation: using `appStyle` and changing between `startSingleScreenApp` and `startTabBasedApp`. Seems to happen with all color properties (`navBarBackgroundColor`, ...)

> I was able to get around this error by explicitly declaring my app style in line

Using `navigatorStyle` on the start methods instead of `appStyle` works, but unfortunately this brings other bugs to my application, e.g. colors getting wrong for no apparent reason:

![bug](https://user-images.githubusercontent.com/619186/34229739-7e6b43b0-e5bc-11e7-97f1-8c3fa853615a.gif)


So what works for me is add a `static navigatorStyle = { ...defaultNavigatorStyle, otherStylesHere }` at ALL screen components.

**Comment by chrise86** [comment]
I used a slightly modified version of @RyanWarner 's solution:

```
Navigation.startTabBasedApp({
    tabs: [
      {
        label: 'Groups',
        title: 'Groups',
        screen: 'Groups.Groups',
        icon: highlightsIcon,
        navigatorStyle
      }
    ],
    appStyle: { ...appStyle  }
  });
```
