### ISSUE TITLE
[v2] test-unit-ios failed

### ISSUE THREAD

**Issue by vovkasm** [wix/react-native-navigation#2183]
### Issue Description

Seems like I found a bug non-related to this issue, but when I try to dig into it, I discover that ios tests fails on my system.
Specifically it is `RNNCommandsHandlerTest/testAssertReadyForEachMethodThrowsExceptoins` that failed. I'am can't understand what is intent of this test, so this issue is more question to developers. This test try call all methods of `RNNCommandsHandler` class, but without needed arguments... is this possible in Objective C at all? And what it try to check after all?

### Steps to Reproduce / Code Snippets / Screenshots

As in https://github.com/wix/react-native-navigation/blob/v2/docs/docs/CONTRIBUTING.md
1. `brew tap wix/brew`
2. `brew install --HEAD applesimutils`
3. `npm install`
4. `npm run test-js`
5. `npm run test-unit-ios`

Expected that tests pass, but instead this output:
```
2017-11-18 16:33:58.231 xcodebuild[48492:1624107] [MT] IDETestOperationsObserverDebug: (071EFBDB-4403-4669-912B-6C0CCDDFA608) Beginning test session ReactNativeNavigationTests-071EFBDB-4403-4669-912B-6C0CCDDFA608 at 2017-11-18 16:33:58.231 with Xcode 9B55 on target <DVTiPhoneSimulator: 0x7fa7eeb0ede0> {
		SimDevice: iPhone 7 (7E09DA93-0546-4163-9F2F-94A78EEE432B, iOS 11.1, Booted)
} (11.1 (15B87))

Restarting after unexpected exit or crash in RNNCommandsHandlerTest/testAssertReadyForEachMethodThrowsExceptoins; summary will include totals from previous launches.

Test Suite 'Selected tests' started at 2017-11-18 16:34:00.463
Test Suite 'ReactNativeNavigationTests.xctest' started at 2017-11-18 16:34:00.464
Test Suite 'RNNCommandsHandlerTest' started at 2017-11-18 16:34:00.464
Test Case '-[RNNCommandsHandlerTest testDynamicStylesMergeWithStaticStyles]' started.
Test Case '-[RNNCommandsHandlerTest testDynamicStylesMergeWithStaticStyles]' passed (0.031 seconds).
Test Suite 'RNNCommandsHandlerTest' failed at 2017-11-18 16:34:00.496.
	 Executed 2 tests, with 1 failure (0 unexpected) in 0.031 (0.032) seconds
... etc...
Test Suite 'RNNStoreTest' passed at 2017-11-18 16:34:00.730.
	 Executed 6 tests, with 0 failures (0 unexpected) in 0.003 (0.008) seconds
Test Suite 'ReactNativeNavigationTests.xctest' failed at 2017-11-18 16:34:00.731.
	 Executed 67 tests, with 1 failure (0 unexpected) in 0.218 (0.267) seconds
Test Suite 'Selected tests' failed at 2017-11-18 16:34:00.731.
	 Executed 67 tests, with 1 failure (0 unexpected) in 0.218 (0.268) seconds
** TEST EXECUTE FAILED **

child_process.js:644
    throw err;
    ^

Error: Command failed: cd ./playground/ios && RCT_NO_LAUNCH_PACKAGER=true xcodebuild test-without-building -scheme "ReactNativeNavigation" -project playground.xcodeproj -sdk iphonesimulator -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 7' -derivedDataPath ./DerivedData/playground ONLY_ACTIVE_ARCH=YES
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.execSync (/Users/vovkasm/work/react-native-navigation/node_modules/shell-utils/src/exec.js:8:6)
    at execWithXcprettyIfPossible (/Users/vovkasm/work/react-native-navigation/scripts/test.unit.ios.js:35:10)
    at run (/Users/vovkasm/work/react-native-navigation/scripts/test.unit.ios.js:19:3)
    at Object.<anonymous> (/Users/vovkasm/work/react-native-navigation/scripts/test.unit.ios.js:39:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

---
### Environment
* React Native Navigation version: `2.0.2016` (19c247b7d1cebff32dc3e32d571e15d7f91c2a7d)
* React Native version: `0.44.0` (as required in package.json)
* `Xcode 9.1 (9B55)` on `macOS High Sierra 10.13.1 (17B48)`
* Platform(s) (iOS, Android, or both?): iOS simulator

I did try to run this test from Xcode (in context of playgraound app) with and without debug... same things. But without debug (as in scheme) no variables can be seen in interactive debugger.

**Comment by DanielZlotin** [comment]
I knew this test will bite me some day :)
so the point here was to make sure that all commands call `assertBridgeReady`
instead of specifying each method individually, I do a reflective call to all public methods (except the alloc init and other system methods) and assert that each of them throw a specific NSException

if it fails, this means maybe you added a new command that does not assertBridgeReady, or maybe you added a property (properties export new public methods under the hood) or maybe there's something wrong with the test itself.

I would want to remove this test but I don't have a better solution for that and this exception is a good one as it catches a lot of weird state bugs related to the RCTBridge initialization process.

**Comment by vovkasm** [comment]
Thank you for answer!

But did not add any methods, I simple run current v2 branch as already noted git hash is 19c247b7d1cebff32dc3e32d571e15d7f91c2a7d
Currently I think that test crashed because it calls every method without pass arguments to them.

**Comment by vovkasm** [comment]
I can make this test to work as expected by using NSInvocation api.
This works for me:
```ObjectiveC
- (void)testAssertReadyForEachMethodThrowsExceptoins {
	NSArray* methods = [self getPublicMethodNamesForObject:self.uut];

	for (NSString* methodName in methods) {
		SEL s = NSSelectorFromString(methodName);
		NSMethodSignature* signature = [self.uut methodSignatureForSelector:s];
		NSInvocation* invocation = [NSInvocation invocationWithMethodSignature:signature];
		invocation.selector = s;
		XCTAssertThrowsSpecificNamed([invocation invokeWithTarget:self.uut], NSException, @"BridgeNotLoadedError");
	}
}
```

Is this enough or should I create pull request?

**Comment by DanielZlotin** [comment]
That's great! thanks!
If you can make a pr that would be even greater :)

**Comment by vovkasm** [comment]
I can... will do it tomorrow... Before this I will try to found why CI pass the tests...

**Comment by vovkasm** [comment]
Now after #2210 merged, lets close it.
