### ISSUE TITLE
(iOS) Navigation bar shadow

### ISSUE THREAD

**Issue by DrunkardLiu** [wix/react-native-navigation#2185]
It's able to hide navigation bar shadow using
topBarElevationShadowEnabled: false
in Android

But I don't know how to hide navigation bar shadow in iOS
Already view issue #1491 
and seems topBarShadowOpacity, topBarShadowOffset and topBarShadowRadius are not work

![img_3177](https://user-images.githubusercontent.com/21217210/32988072-dec2e36a-cd36-11e7-8bc6-4e2039374fb1.PNG)

**Comment by khsily** [comment]
try this
{navBarNoBorder: true}  :)

**Comment by GetSource1234** [comment]
It seems {navBarNoBorder: true} doesn't work within 1.1.335. I tried navBarNoBorder and still can see shadow/line under the bar.

**Comment by MounirDhahri** [comment]
Try 
`topBarElevationShadowEnabled: false`

**Comment by ProkhoDim** [comment]
Adding `background: {clipToBounds: true}` to the topBar options works in my case. The `noBorder` option does not work.
