### ISSUE TITLE
[iOS] Race condition in map initalization

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#2193]
### Issue Description

I noticed this bug with https://github.com/mapbox/react-native-mapbox-gl. That when I have just a `View` with  `flex: 1` and Mapbox map with `flex: 1` sometimes the map gets double size of the screen. Here is picture of what I mean
![image](https://user-images.githubusercontent.com/12229968/33007628-47191b9a-cdd8-11e7-9eb4-798cb1de8f3d.png)

My guess is that this navigation library is somehow getting the double screen size for small amount of time and then it changes it back to the size of the actual phone. Between those steps the map has been initialized and has wrong size.

To be able to reproduce this you can use my test repo where I can reproduce this bug: https://github.com/henrikra/mapbox-shifted-map-bug 
Here is also video on how you can get the bug situation with the above repo: https://drive.google.com/file/d/1uAPjtq_hzRWUWL60oRoYxhywLlxULKlQ/view?usp=sharing
You can see the bug in the last 20 secs of the video. It may take many tries before you can get the race condition situation as you can see it from the video it took me 2 minutes of retries to get. So I have set the center coordinate to Kamppi but in the end it is shifted to "Meilahti"

More info on this here: https://github.com/mapbox/react-native-mapbox-gl/issues/777

### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.49.0
* Platform: iOS
* Device info: Device

**Comment by pqkluan** [comment]
You might want to delay the initial render of the map component by creating a boolean flag in the constructor and set it to true in `componentDidMount` method. For additional, using `setInterval` to increase the delay duration to 0.5s will make it safer.

**Comment by henrikra** [comment]
Those kind of hacks are not ideal :/ Would be cool to know how this library initialises it's views. So we could at least pass that information to mapbox :) @guyca

**Comment by nitaliano** [comment]
Hi, I'm the one that maintains the Mapbox repo that @henrikra mentioned. What are the chances of a PR being merged in if I was to pick this up? @guyca

**Comment by rickycpadilla** [comment]
@henrikra  I ran into the same issue. Instead of `{ flex: 1 }` I used ` { height: screenHeight, width: screenWidth }` and this seemed to solve the problem. But I agree that being able to set a flex value would be much more convenient.

**Comment by henrikra** [comment]
Here you can see my observations too https://github.com/mapbox/react-native-mapbox-gl/issues/777#issuecomment-345631572
