### ISSUE TITLE
Performance problems like in react-navigation?

### ISSUE THREAD

**Issue by inv2004** [wix/react-native-navigation#2195]
Hello,

It is question:
I just started my project in RN with react-navigation, but found that react-navigation is the worst part of the  RN. The problems I found, after travel between screens and back react-navigation will have a lot of attached components (even duplicated components) and redux change fires render of inactive and duplicate pages also.

After a while react-navigator has so many pages it decreases application performance significantly: https://github.com/react-community/react-navigation/issues/608

How does this navigator work with all nested pages?

Regards,

**Comment by vovkasm** [comment]
(I'am not contributor to this lib)
At work we still use old NavigationExperimental copy from old versions of RN for the same reason.

Theoretically this library should be very fast... but I'am at last weekend tried to test v2... I port small application to this lib and iOS works well (and fast), but Android part has many unimplemented features (most important one - buttons in topBar). May be v1 in better state, I did not tried...

**Comment by buffaly** [comment]
I already use V1 in production from 4 months,
In my opinion, Performance is well more than react-navigation.
BUT!!!
react-native-navigation have many things to handle with~
Notification, app lifecycle, memory use, bra bra bra~
.
It works very well on IOS, but hard work to make android.
because android has a lot of unknown crash.
Hope this comment can help you guy~

**Comment by pqkluan** [comment]
Copy my [old comment](https://github.com/wix/react-native-navigation/issues/1699#issuecomment-323287915):
```
React-Navigation is a Javascript-based navigation, that means all the navigate happen inside of single Activity (on Android and iOS counterpart).

The good part about Javascript based navigation is they will work on most platforms. But they usually suffer from performance issues due to stacks everything in the same activity.

React-Native-Navigation on another hand is an actual native navigation. Every screen has their own native container that handles native system. Better optimize better performance at the cost of deep integrate for each platform.
```

**Comment by pqkluan** [comment]
I'll close this issue since it's been a week since the last active comment and I think the original question has been answered. Feel free to re-open if needed.
