### ISSUE TITLE
NavBar visibility toggling

### ISSUE THREAD

**Issue by sniib** [wix/react-native-navigation#2198]
I have a screen component which has video player component inside it. When I toggle the video player to fullscreen, the navbar still stays on the screen.

![nayttokuva 2017-11-20 kello 19 34 19](https://user-images.githubusercontent.com/33811558/33032449-ed901464-ce29-11e7-9b2d-8459c0ad18fd.png)

I know I can hide the navbar by doing this in screen component:

`
    static navigationOptions = {
        header : null
    }
`

But how can I hide it and get it back with condition isFullscreen, which is property in video player.
Im not sure how to access the 'isFullscreen' property in screen component either.
(Im very new to react native)

**Comment by datvp09** [comment]
from Documentation:

```
this.props.navigator.toggleNavBar({
  to: 'hidden', // required, 'hidden' = hide navigation bar, 'shown' = show navigation bar
  animated: true // does the toggle have transition animation or does it happen immediately (optional). By default animated: true
});
```
