### ISSUE TITLE
setButtons should only set buttons on the calling screen

### ISSUE THREAD

**Issue by aarongreenwald** [wix/react-native-navigation#22]
If I call `setButtons` from a screen and then the screen is immediately popped, or call `setButtons` before the screen is finished pushing, the buttons are set on the top-most screen in the navigator, not the calling screen.

**Comment by guyca** [comment]
Fixed in v2.
If you're using v1.x, you can [check if the screen is visible](https://wix.github.io/react-native-navigation/#/screen-api?id=screen-visibility) and set the buttons only if it's visible.
