### ISSUE TITLE
Sticky NavBar - is it possible?

### ISSUE THREAD

**Issue by hadynz** [wix/react-native-navigation#220]
Just wondering how could one go about creating a "sticky navbar" that is overlaid on top of any navigation transition. It is a popular paradigm that many apps like Facebook use.

![facebook navbar always on top](https://cloud.githubusercontent.com/assets/315585/17830683/e59f32a0-6726-11e6-942f-937f3dc14280.gif)

**Comment by guyca** [comment]
Currently this isn't supported by the api. You could create a screen with a TopBar, and handle the drill in your self in JS.

**Comment by hadynz** [comment]
> You could create a screen with a TopBar, and handle the drill in your self in JS.

Didn't quite follow what you meant there. The "drill in" usually happens by using the navigator to push/pop a route. Which in this case would ignore the `TopBar` that is loaded on the current scene.

**Comment by guyca** [comment]
What I meant is, that since the current api doesn't support this behaviour, don't use navigator to handle drill in for this specific use case. Instead, have a single screen which actually can display two different screens and animate the second screen (the drill in) in the render function instead of calling `navigator.push`.

**Comment by hadynz** [comment]
> Instead, have a single screen which actually can display two different screens and animate the second screen (the drill in) in the render function instead of calling `navigator.push`

I would end up creating my own "navigator" in going down such a route, which will always be subpar in comparison to the navigator components out there.

I think `react-native-navigation` is not currently fit for my current need, and I am better off looking at the other mainstream navigators that support being nested.
