### ISSUE TITLE
Screens registered with Navigation, displaying on complete screen

### ISSUE THREAD

**Issue by priyanka931** [wix/react-native-navigation#2203]
How can i make single screen navigator a child of {flex: 1} view

// This class itself is a screen displayed by startSingleScreenApp
<View style={{flex: 1}}>
<View style={{height: 200}} />
{Navigation.startSingleScreenApp({})} // SubNavigator
</View>

I want the SubNavigator to be the child of the above class. Is this achievable?

**Comment by hhunaid** [comment]
How about adding a root level view with {flex:1} to every screen?

**Comment by pqkluan** [comment]
Short answer: No.

When you start the app with `startSingleScreenApp` the registered screen that passed with being wrapped by many layers of HOC which will eventually end at the `root`.

The most you could do is wrap the registered component with your HOC. This solution might be what you want since there will be *many* instances of that HOC.

**Comment by priyanka931** [comment]
Thanks for the replies, but i want to know that is there any way by which i can use the single screen navigator and tab navigator as a react component as we do in "react-navigation", so that i can meet the following scenario.
```
<View style={{flex: 1}}>
      <View style={{flex: 1}} />
      <View style={{flex: 2}} >
            <SingleScreen Navigator/ Tab Navigator /> // So that this Navigator takes the 2/3 part of the 
               complete parent View.
      </View>
</View>
```

**Comment by pqkluan** [comment]
@priyanka931 Sorry, but I'm afraid it's not possible with RNN. But doable with other Javascript-based navigation.

**Comment by priyanka931** [comment]
@pqkluan Thank you so much for your fast & generous response

**Comment by pqkluan** [comment]
I'll close this issue for now. Feel free to re-open it if needed.
