### ISSUE TITLE
Push or popToRoot not working on Drawer. 

### ISSUE THREAD

**Issue by muresanandrei** [wix/react-native-navigation#2206]
From what i saw on other posts using handleDeepLink is the way.

But I have for example Menu.js which is the drawer and inside that component a view with multiple text which represents the menu links. Each of them have onPress event.On press I tried with push and popToRoot, resetTo but is not working.

Can i use handleDeepLink like this on push where link is?

this.props.navigator.handleDeepLink({
    link: 'app.ProfileSettings'
  });

**Comment by guyca** [comment]
duplicates #1701
