### ISSUE TITLE
[V2.0] SetButtons left error on Android

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#221]
```
this.props.navigator.setButtons({
                leftButtons: [
                    {
                        id: "closeShopingCart",
                        icon: closeIcon
                    }
                ]
            });
```

on android, set leftButtons not working => it always display is drawer icon
set rightButtons: OK

**Comment by guyca** [comment]
@agumack Use `leftButton` instead of `leftButtons`. [Like in  the example project](https://github.com/wix/react-native-navigation/blob/master/example-redux/src/screens/PushedScreen.js#L239).
