### ISSUE TITLE
navBarTextColor not working in android

### ISSUE THREAD

**Issue by nimamyscreen** [wix/react-native-navigation#2219]
### 
I upgrade from 1.1.236 to 1.1.295 and after that navBarTextColor is not working in android.

### Steps to Reproduce / Code Snippets / Screenshots ###

this.props.navigator.showModal({
            screen: 'com.example',
            navigatorStyle: {
                navBarHidden: false,
                navBarButtonColor: 'white',
                statusBarHideWithNavBar: true,
                statusBarTextColorScheme: 'light',
                statusBarHidden: false,
                navBarTransparent: true,
                navBarTranslucent: true,
                drawUnderNavBar: true,
                navBarBackgroundColor: 'white',
                screenBackgroundColor: 'transparent',
                modalPresentationStyle: 'overFullScreen',
                orientation: 'portrait'
            },
            navigatorButtons: {
                rightButtons: [
                    {
                        title: 'New'
                        buttonColor: 'white',
                        id: 'save' 
                    },
                ],
            },
        });

---
### Environment
* React Native Navigation version: 1.1.295
* React Native version: 0.49.5
* Platform (Android): 7

**Comment by pqkluan** [comment]
I don't see `navBarTextColor` prop inside of `navigatorStyle` object. Could you double check the code?

**Comment by pqkluan** [comment]
I'll close this issue for now due to the lack of information. If the problem still exists with the latest version, feel free to re-open.
