### ISSUE TITLE
[V2.0] switchToTab doesn't work on Android

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#222]
Hi,

I have test handleDeepLink on android. I working when called inside drawer but not working on any screen (ex: called handleDeepLink in FirstTabScreen). IOS is good.

`this.props.navigator.handleDeepLink({
            link: "section/" + item.id
        });`

**Comment by guyca** [comment]
Hey @agumack I'm not sure I understand the issue. You're calling `handleDeepLink` from a screen you display in the SideMenu, and it's not received by the screens?

**Comment by agumack** [comment]
sorry @guyca.

I finally found the reason why: handleDeepLink received.
But switchToTab not working (Only android)

> this.props.navigator.switchToTab({
>                     tabIndex: 1
>                 });

**Comment by guyca** [comment]
Hey @agumack I actually [started implementing it](https://github.com/wix/react-native-navigation/tree/switchToTab), but had to context switch to something else. Hope to get to it by Thursday

**Comment by agumack** [comment]
@guyca 
It seems now Tab doesn't work on Android too. 
I tried run example code. (my project having problem too)

Logs when i tap tab: Got DOWN touch before receiving UP or CANCEL from last gesture

**Comment by guyca** [comment]
@agumack what exactly doesn't work? We use `TopTabs` in our app and we haven't noticed any problems with it.

**Comment by agumack** [comment]
@guyca I am using:

> Navigation.startTabBasedApp({
>   tabs: [
>     {
>       label: 'One',
>       screen: 'example.FirstTabScreen', // this is a registered name for a screen
>       icon: require('../img/one.png'),
>       selectedIcon: require('../img/one_selected.png'),
>       title: 'Screen One'
>     },
>     {
>       label: 'Two',
>       screen: 'example.SecondTabScreen',
>       icon: require('../img/two.png'),
>       selectedIcon: require('../img/two_selected.png'),
>       title: 'Screen Two'
>     }
>   ]
> });

Nothing happens when you click  Tab Two.

> "react-native-navigation": "2.0.0-experimental.71"
> "react-native": "0.31.0", (same problem 0.25.1)

**Comment by guyca** [comment]
@agumack implemented `switchToTab` in `v2.0.0-experimental.72`.

Bottom tabs work fine for us, I don't think there's an issue there. But if there is, please open another issue. Thanks.

**Comment by agumack** [comment]
Thanks @guyca switchToTab worked worked worked 👍 

Changing to drawUnderTabBar: false fixed issue "Nothing happens when you click Tab Two"

**Comment by guyca** [comment]
@agumack Glad to hear. Thanks for reporting issues.
