### ISSUE TITLE
Change Screen on Redux Action

### ISSUE THREAD

**Issue by gusilveiramp** [wix/react-native-navigation#2220]
### Issue Description

How to use this.props.navigator inside a Redux Action?
I'm following this implementation: https://github.com/JuneDomingo/movieapp/tree/feature/similar-movies

---
### Environment
* React Native Navigation version: ^1.1.275
* React Native version: 0.50.3
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung Galaxy S7 - Android 6.0

**Comment by Fuhrmann** [comment]
I`m using this and works very well for my use cases: https://gist.github.com/chrismllr/92c3a314d7d035c8877fcf672cfd555c

**Comment by nazrdogan** [comment]
@gusilveiramp  I had same problem with you. I make little hack for navigation. I don't know very well react-native-navigation but its works well. you can dispatch action everywhere.

https://github.com/nazrdogan/react-native-navigation-redux

**Comment by oakis** [comment]
I am currently trying out https://github.com/nazrdogan/react-native-navigation-redux/blob/master/app/navigatior.js as my solution.
So far it is working as I want.

In my first screen (splashscreen) I load in the navigator like so:
```js
componentDidMount() {
    setNav(this.props.navigator);
}
```

Then when I need to change screen I use the loaded navigator like so:
```js
getNav().push({
    screen: 'app.Dashboard',
    title: 'Pushed Screen'
});
```
