### ISSUE TITLE
Many requests on app startup

### ISSUE THREAD

**Issue by gaultierq** [wix/react-native-navigation#2221]
When I start my app with **startTabBasedApp**, every tab & drawer screen are fetching  the data they need when mounting (I request when **componentDidMount**)
This is causing a lot of (unnecessary) requests on startup.

Before trying to do anything about it, and as I haven't found any lazy loading capability within RNN, I was wondering how other people were dealing with this issue.
Thx !

**Comment by guyca** [comment]
You can move your logic to `didAppear` instead of didMount https://wix.github.io/react-native-navigation/#/screen-api?id=screen-visibility

**Comment by gaultierq** [comment]
thanks
