### ISSUE TITLE
Extreme frame dropping when using this library

### ISSUE THREAD

**Issue by MostafaNasiri** [wix/react-native-navigation#2222]
### Issue Description

I have a simple app with three tabs (it's a tab based app). When I run it the ui frame rate keeps dropping to 40 (about 3000 frames dropped in one minute without doing anything!)
JS frame rate is almost always between 40 to 50.
I didn't have this problem when I was using react navigation and this happened when I started to use wix navigation.

---
### Environment
* React Native Navigation version: 1.1.294
* React Native version: 0.50.1
* Platform(s): Android
* Device info: Xiaomi mi a1 | Android 7.1.2

**Comment by chaitanya0bhagvan** [comment]
RNN is still not compatible with rn 0.50,  use rn 0.49.

**Comment by tutts** [comment]
yikes! thats why I'm having some issues perhaps, would be good to update the docs on first page.

>  It supports react-native 0.43 and above.

**Comment by pqkluan** [comment]
Hi @tutts , the team will upgrade the repo to RN 0.50 in the near feature. You could use v1/v2 on RN 0.49 in the meantime.

**Comment by MostafaNasiri** [comment]
I solved my problem with downgrading to 0.49
When will 0.50 be supported?

**Comment by pqkluan** [comment]
Sorry, but the exact time frame depends on the team. That's also an unknown to me.

I'll close this issue since there is an answer to the problem. Feel free to re-open this if needed.
