### ISSUE TITLE
Snackbar ios equivalent

### ISSUE THREAD

**Issue by gaultierq** [wix/react-native-navigation#2225]
I need to display a short message after an action is completed. 
Snackbar is provided within RNN, but I need to display messages for iOS users as well. 
What are my options ?

**Comment by guyca** [comment]
You can show a transparent modal without animation and animate a snackbar like view as you like.

To make the modal transparent and over the current screen, use these settings in the modal component.
```js
static navigatorStyle = {
  screenBackgroundColor: 'transparent',
  modalPresentationStyle: 'overCurrentContext',
};
```

**Comment by gaultierq** [comment]
thanks for the tip @guyca .
no better options ? iOS doesn't have a standart way of displaying contextual messages ?

**Comment by brunolemos** [comment]
This solution seems to block the tap on the rest of the app. Weird because I see `pointerEvents="box-none"` in the react tree. Any way to fix that? cc @guyca

**Comment by guyca** [comment]
@brunolemos No way around that. You can easily implement a Snackbar equivalent on iOS in v2 using an [Overlay](https://wix.github.io/react-native-navigation/v2/#/docs/top-level-api?id=showoverlaylayout-)

**Comment by brunolemos** [comment]
Thanks. Waiting for v2 ios-android parity before using it.

**Comment by guyca** [comment]
@brunolemos What feature are you waiting for?

**Comment by brunolemos** [comment]
@guyca hm... probably none specifically, just that looking at the comparison table gives the feeling that android has been lagging behind so it will very likely have more bugs

IMO you should eventually release v2 already without beta flag, with more people using it you will also get more contributors for it. cc #1298
