### ISSUE TITLE
TopBar transparent not working in android with custom view

### ISSUE THREAD

**Issue by iamjon** [wix/react-native-navigation#2237]
Following the directions in #21 I was able to get the top bar to be transparent in ios. However in android it shows up as a weird gradient. (Both in emulator -pixel android 7 and real device android 6)

` this.props.navigator.setStyle({
            navBarCustomView: 'TopBar',
            navBarCustomViewInitialProps: {title: 'Hi Custom', navigator: this.props.navigator},
            drawUnderNavBar: true,
            navBarTranslucent: true,
            navBarTransparent: true,
            navBarBackgroundColor: 'transparent'

        });`

![iphone_6_-_ios_11_1_transparent](https://user-images.githubusercontent.com/617757/33319602-fb9f2dfa-d447-11e7-94c4-019113595459.png)
![pixel_api_25_5554_no_transparent](https://user-images.githubusercontent.com/617757/33319615-03ccaab6-d448-11e7-9a2c-c61388fd0f8e.png)

---
### Environment
* React Native Navigation version: 1.1.295
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): Android 6 + 7
* Device info (Simulator/Device? OS version? Debug/Release?): Android 7 Pixel Simulator, Android 6 Oneplusone

**Comment by eduplus** [comment]
The same,

navBarTransparent: true,

doesn't seem to work on Android. Using the 1.x version here as well. This would be really nice to have working, works nicely on iOS.

**Comment by pqkluan** [comment]
Set `navBarTranslucent` to false might do the trick

**Comment by iamjon** [comment]
Setting navBarTranslucent false makes the weird gradient go in android, and makes the background black in ios. Does nothing for transparent.

` this.props.navigator.setStyle({
            navBarCustomView: 'TopBar',
            navBarCustomViewInitialProps: {title: 'Hi Custom', navigator: this.props.navigator},
            drawUnderNavBar: true,
            navBarTranslucent: false,
            navBarTransparent: true,
            navBarBackgroundColor: 'transparent',
         });`

![translucent-false](https://user-images.githubusercontent.com/617757/33363195-fdf501c4-d4e7-11e7-9455-238df711d4d9.png)

**Comment by pqkluan** [comment]
Could you guy update the info on this issue? Does you guy found the solution or this problem persist in the latest version?

**Comment by pqkluan** [comment]
It's been two weeks, and there are no updates. I'll assume the issue is resolved.
