### ISSUE TITLE
Navigator API for setting buttons should be the same for iOS and Android

### ISSUE THREAD

**Issue by artald** [wix/react-native-navigation#224]
Currently in V2, if you want to set buttons using the navigator, you need to call different functions for every platform - `setButtons` for iOS and `setButton` for Android.

I understand that this decision was made since Android can only have one button on the left side. However, this need to be consistent; we don’t want to make different calls when we have the same code handling both platform.

**Comment by agumack** [comment]
@guyca i tried but have a error: "**Unsupported button type barcodescanner**"
> this.props.navigator.setButtons({
>                     leftButtons: [
>                         {
>                             title: "Scan",
>                             id: "barcodescanner",
>                             icon: cameraIcon
>                         }
>                     ],
>                     rightButtons: [
>                         {
>                             title: "Logout",
>                             id: "priview_logout",
>                             icon: logoutIcon
>                         }
>                     ]
>                 });

**Comment by guyca** [comment]
@agumack Android apps don't have left buttons besides the back and hamburger buttons, still we figured thats a bit too strict so we support four types of left buttons:
1. back
2. hamburger
3. cancel
4. accept

I really don't think you should set any other button as a left button on Android. Android  users don't expect to have left buttons besides the four I mentioned above.

**Comment by DanielZlotin** [comment]
While I agree with @guyca , it's a feature we can add in the future. If you want, open a feature request and we'll assign it to TBD, that way you can track it.
