### ISSUE TITLE
Stuttering ripple effect with Android BottomTabs

### ISSUE THREAD

**Issue by simonedavico** [wix/react-native-navigation#2248]
### Issue Description

Issue: I set up a simple tab based navigation in Android (following the movieapp app example), and the ripple effect on tab icon tap stutters A LOT, both on emulator and testing device. The weird thing is that I downloaded the Wix Android app, and navigation is buttery smooth on that one. My views are basic, I still don't have any business logic running, so this leaves me very concerned. I based my code on the movieapp example, so it is basically the same. 

### Steps to Reproduce / Code Snippets / Screenshots

I am not sure about which code will be meaningful to post here, but if anybody has an hint on what the problem may be I will attach it here. The stuttering is especially noticeable when the ripple effect is finishing, or when repeatedly tapping on the same icon.

[Video recording of the stuttering from the emulator.](https://www.dropbox.com/s/w9zac661j4ghi84/tabbar.mp4?dl=0) Dropbox may lower the quality while reproducing, but it is fine if you download it.

---
### Environment
* React Native Navigation version: 0.50.4
* React Native version: 1.1.295
* Platform(s) (iOS, Android, or both?): Android 
* Device info (Simulator/Device? OS version? Debug/Release?): Android, both emulator (Pixel 2 with Oreo 8.0 (API 26)) and device OnePlus 3, OxygenOS 5.0 (Oreo 8.0). Debug version of the app.

**Comment by simonedavico** [comment]
Maybe this is related? https://github.com/wix/react-native-navigation/issues/2138

**Comment by simonedavico** [comment]
*Update: * after going through the issues I downgraded to react-native 0.49.3, and the stuttering is gone. I have extensive Java experience but unfortunately I played very little with Android, so I'm not sure where to start from to help. Any hint to get this working properly with RN 0.50.x is appreciated :)

**Comment by guyca** [comment]
Hey @simonedavico 
As you've probably already understood form the issues, since the Wix app is using RN 0.44.2 we're not officially supporting RN 0.50. We're planning to upgrade pretty soon - I hope by the end of December.

**Comment by Fuhrmann** [comment]
Yeah, I'm seeing the same stuttering in ripple effects on Android, because I'm using RN 0.50.3.
