### ISSUE TITLE
Override navBarCustomView for all new screens

### ISSUE THREAD

**Issue by tsdevelopment** [wix/react-native-navigation#2249]
### Override navBarCustomView for all new screens

I use a singleScreenApp as follows:

`Navigation.startSingleScreenApp({
    screen: {
        screen: 'screens.example',
        title: 'Example',
        navigatorStyle: {
            navBarCustomView: 'navigation.TopBar',
        }
    },
});`

You can see that I use a custom navBar component. That works very well. But if I link to a new screen via

`this.props.navigator.push({
            screen,
            title: item.title,
            passProps: {
                item,
            },
        });`

the navbar resets to the default one. Is it possible to set my custom navbar globally and prevent setting the `navigatorStyle` setting on each new push statement?

---
### Environment
* React Native Navigation version: 1.1.280
* React Native version: 0.50.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Samsung Galaxy S8

**Comment by Fuhrmann** [comment]
You can do what you want (and that's what I do it too) using a HOC. Here it is an example: https://github.com/wix/react-native-navigation/issues/1500#issuecomment-315189983

**Comment by tsdevelopment** [comment]
Thanks for that! Please mark as resolved!
