### ISSUE TITLE
Deep Linking on iOS

### ISSUE THREAD

**Issue by bbrock25** [wix/react-native-navigation#225]
I'm not able to register to incoming deep links from outside the app.

my dev dependencies: 

```
    "react": "^0.14.5",
    "react-native": "0.25.1",
    "react-native-navigation": "^1.0.30",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-thunk": "^2.1.0"
```

``` javascript
class OrderList extends Component {

  constructor(props) {
    super(props);
    ...
    this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
  }

  onNavigatorEvent(event) {
    console.log(event);
    if (event.id === 'drawer') {
      this.props.navigator.toggleDrawer({
        side: 'left',
        animated: true,
      });
    }
  }
}
```

I can log the event when creating a deep link action from within the app, but it never fires when linking to the app from an external source, such as a push notification or safari in the simulator. 

Thank you by the way for the great work on this project. It is a much needed utility for React Native!

**Comment by guyca** [comment]
We use `DeviceEventEmitter` to send event from native to JS when a push message is received, then handle deep link deep link logic in JS. 
When the event is received, you can update your state, or register listener on your screens to handle the external deeplink.

**Comment by bbrock25** [comment]
OK, thanks. I'll give that a whirl. Just curious, the deep linking from the documentation, is that only relevant when using deep links while the app is already running in the foreground? The example suggests using deep links to navigate from the drawer.

**Comment by guyca** [comment]
@bbrock25 Exactly, `navigator.handleDeepLink` is for in app links, links that originate rom JS and are handled in JS.

**Comment by edvinasbartkus** [comment]
There is an issue with `wix/react-native-controllers` that it forgets about `launchOptions` parameter. I have a fix for it: https://github.com/edvinasbartkus/react-native-controllers/commit/9472a8b56154a8dad32d178ed0721cdd990a64d4 (https://github.com/wix/react-native-controllers/pull/58)

AFAIK `launchOptions` keeps the information about `Linking.getInitialURL()` and `PushNotificationIOS.getInitialNotification()`.

AppDelegate.m should be changed to:
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions

<...>
  [[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation
                                         launchOptions:launchOptions];
<...>
```

**Comment by jay1337** [comment]
The AppDelegate.m example https://github.com/wix/react-native-navigation/blob/master/example/ios/example/AppDelegate.m quoted at the end of the page http://wix.github.io/react-native-navigation/#/installation-ios must be updated with launchOptions:launchOptions

**Comment by shafy** [comment]
@jay1337 you're a life saver. I spend half a day and not understanding why I can't get the URL when launching the app.

**Comment by srameshr** [comment]
@shafy
Can you share your Appdelegate.m file?
I dont understand this. Im trying to launch via deeplinks and i handle those via ```Linking``` as mentioned in the docs. I listen to the 'url' in ```componentDidMount``` method in ```myScreen``` then I call ```this.props.navigator.push({ screen: 'myscreen' })```. But it throws an error saying ```MyScreen is used but not yet registered```

Logs:
```
TypeError: Cannot read property 'navigatorStyle' of undefined
    at Object.navigatorPush [as push] (index.ios.bundle?platform=ios&dev=true&minify=false:55027)
    at Navigator.push (index.ios.bundle?platform=ios&dev=true&minify=false:62703)
    at HomeScreen.handleOpenURL (index.ios.bundle?platform=ios&dev=true&minify=false:110251)
    at 
```

**Comment by shafy** [comment]
@srameshr that sounds like you didn't register 'myscreen' with the react native navigator? Have you registered it like described here: https://wix.github.io/react-native-navigation/#/top-level-api

Here is my `AppDelegate.m`:


```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

@import Firebase;

#import "AppDelegate.h"

#import <RCTBundleURLProvider.h>

#import <RCCManager.h> // needed for react-native-navigtor
#import <RCTRootView.h> // needed for react-native-navigtor

#import "ReactNativeConfig.h"
//#import <Firebase/Firebase.h>
#import <React/RCTLinkingManager.h>


@implementation AppDelegate
@synthesize oneSignal = _oneSignal;

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;
  
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  
  // needed for react-native-navigator
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  self.window.backgroundColor = [UIColor whiteColor];
  [[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions];

  // this is for onesignal
  self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
                     appId:[ReactNativeConfig envFor:@"ONE_SIGNAL_APP_ID"]
                     settings:@{kOSSettingsKeyAutoPrompt: @false}
                     ];

  // this is added for firebase
  [FIRApp configure];
  
  // original routing part, without react-native-navigator
  /*
   RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
   moduleName:@"BattereApp"
   initialProperties:nil
   launchOptions:launchOptions];
   rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
   
   self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
   UIViewController *rootViewController = [UIViewController new];
   rootViewController.view = rootView;
   self.window.rootViewController = rootViewController;
   [self.window makeKeyAndVisible];
   */
  
  return YES;
}
// Required for the notification event.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification {
    [RCTOneSignal didReceiveRemoteNotification:notification];
}

// Required for Universal Links (deep linking)
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}

@end
```

**Comment by srameshr** [comment]
Yeah, I have registered all my screens.

**Comment by isaachinman** [comment]
> Just curious, the deep linking from the documentation, is that only relevant when using deep links while the app is already running in the foreground?

Is there any documentation and/or a supported way to handle incoming links that launch the app itself? Or is this left up to users via `Linking.getInitialUrl`?

**Comment by isaachinman** [comment]
Deep linking is only useful if it handles both cases (app foregrounded and app launching). This lib needs to support both in a documented way.

**Comment by draperunner** [comment]
Did you find a solution to this @isaachinman? I need deep linking to work on iOS when the app is not already opened in the background. I've tried different things, but `Linking.getInitialURL` never returns a URL when the app has to be launched first. If it on the other hand is already in the background, it works fine...

There are various issues related to deep linking in some way, but they're all either closed or have no solution for this case. https://github.com/wix/react-native-navigation/issues/4539 https://github.com/wix/react-native-navigation/issues/4118 https://github.com/wix/react-native-navigation/issues/2017  and more...

Any status update on this @guyca or known workarounds?

**Comment by isaachinman** [comment]
@draperunner Yes I did, but it's been awhile. I've had to step away from the RN world for awhile, but I do believe the community has moved towards [`react-navigation`](https://reactnavigation.org/).

**Comment by draperunner** [comment]
Ok, thanks. Replacing react-native-navigation with react-navigation isn't an option, though. I hope there's a way to get this to work.

**Comment by isaachinman** [comment]
And you're still working on v2?

**Comment by draperunner** [comment]
I am using v2.13.2 of react-native-navigation, yes. I'll upgrade to v2.18.5 (the latest) tomorrow and check if that works, but the changelog doesn't look too promising.

**Comment by draperunner** [comment]
Seems like this is the issue I'm encountering! https://github.com/facebook/react-native/issues/24429
