### ISSUE TITLE
react native navigation cpu usage issue with react native 50.0

### ISSUE THREAD

**Issue by mrxrinc** [wix/react-native-navigation#2257]
Hi everyone. I got a problem newly with rn50 when using r-n-navigation. it uses alot of cpu from computer (while on emulator) and a fix 15% cpu on 8 core physical devices. also I've googled everywhere on earth still no answer! I've already tested r-n-navigation on react native 0.47 and it worked perfectly but it face this problem on react native 0.50. any kind of help will be appreciated!

---
### Environment
* React Native Navigation version: 1.1.296
* React Native version: 0.50.3
* Platform(s) (iOS, Android, or both?): Android 6, 7, 8
* Device info (Simulator/Device? OS version? Debug/Release?): Android emulator and physical devices

**Comment by enahum** [comment]
might be related to #2138

**Comment by mrxrinc** [comment]
yes, that was the exact problem. already downgraded to 0.49.

**Comment by enahum** [comment]
Care to close this issue and follow that other one?

**Comment by mrxrinc** [comment]
ok
