### ISSUE TITLE
How to achieve a global style similar to Tabbar？

### ISSUE THREAD

**Issue by luojinghui** [wix/react-native-navigation#2258]
### Issue Description

Now to create a music player software, encountered a problem.
How to achieve a global style similar to tabbar, this is for each page I added to play the audio page entry is useful. 
Because I can not add an audio portal component to every page because of serious performance issues, I wanted to make a public component like tabs similar to the one below, so that I could listen to the play status in real time instead of Send a message to each page's entry file.

This plug-in can help me achieve it? Help me, thank you

**Comment by alexwasner** [comment]
I created https://github.com/alexwasner/react-native-navigation-extra-view to achieve this sort of thing on iOS. I couldn't get it to work well with Android as Java is not my strong suit. Feel free to use it for inspiration on how to solve your problem and PR up something for Android if you find a solution
