### ISSUE TITLE
GPU rendering issue

### ISSUE THREAD

**Issue by ghiteze** [wix/react-native-navigation#2259]
### Issue Description
Hello, 
I create a simple app with 5 tabs but i've a problem with GPU, you can see my video in the link, it's not stop, is that normal?

https://streamable.com/018rw

### Steps to Reproduce / Code Snippets / Screenshots
* Open developer options
* Profile GPU rendering: On screen as bars
* Show GPU view updates: turn on

### Environment
* React Native Navigation version: 1.1.295
* React Native version: 0.50.4
* Platform(s) (iOS, Android, or both?): Android 6.0
* Device info (Simulator/Device? OS version? Debug/Release?): Moto G (2nd gen)

**Comment by hhunaid** [comment]
Related to #2144 and #2138 probably.

**Comment by ghiteze** [comment]
Yes, thanks a lot. downgrading from 0.50+ to 0.49.3 and its works well but this is just a temporary solution
