### ISSUE TITLE
Android resetTo - infinite newStack loop

### ISSUE THREAD

**Issue by anhuin69** [wix/react-native-navigation#226]
Using navigation.resetTo({...}) on Android creates an infinite loop of Navigation newStack calls.
Apparently, the call to createStack in SingleScreenLayout is made using the current screenParams instead of the targeted screen screenParams.

Using the following patch does make the resetTo call work again.
ps: I didn't test the side effects

    // Current code
    private void createStack(RelativeLayout parent) {
        if (stack != null) {
            stack.destroy();
        }
        stack = new ScreenStack(activity, parent, screenParams.getNavigatorId(), this);
        LayoutParams lp = new LayoutParams(MATCH_PARENT, MATCH_PARENT);
        stack.pushInitialScreen(screenParams, lp);
        stack.show();
    }

    // createStack version which replaces the screenParams
    private void createStack(RelativeLayout parent, ScreenParams params) {
        if (stack != null) {
            stack.destroy();
        }
        stack = new ScreenStack(activity, parent, params.getNavigatorId(), this);
        LayoutParams lp = new LayoutParams(MATCH_PARENT, MATCH_PARENT);
        stack.pushInitialScreen(params, lp);
        stack.show();
    }

The following sample reproduces the original issue.

    class Screen1 extends Component {
        componentWillMount() {
            // Load some stuff

            this.props.navigator.resetTo({
                screen: 'test.screen2',
                title: 'Screen 2',
            });
        }

        render() {
            return (
                <View>
                    <Text>Screen 1</Text>
                </View>
            );
        }
    }

    class Screen2 extends Component {
        componentWillMount() {
        }

        render() {
            return (
                <View>
                    <Text>Screen 2</Text>
                </View>
            );
        }
    }

    Navigation.registerComponent('test.screen1', () => Screen1);
    Navigation.registerComponent('test.screen2', () => Screen2);

    Navigation.startSingleScreenApp({
        screen: {
            screen: 'test.screen1',
            title: 'Screen 1',
            navigatorButtons: { rightButtons: [] }
        },
    });

**Comment by michelantonides** [comment]
I have the same problem. I can't find the current code that you provide 

`// Current code
private void createStack(RelativeLayout parent) {
    if (stack != null) {
        stack.destroy();
    }
    stack = new ScreenStack(activity, parent, screenParams.getNavigatorId(), this);
    LayoutParams lp = new LayoutParams(MATCH_PARENT, MATCH_PARENT);
    stack.pushInitialScreen(screenParams, lp);
    stack.show();
}
`

I found this code in SingleScreenActivity.java but its different.

`private void createStack(RelativeLayout parent) {
        if (stack != null) {
            stack.destroy();
        }
        stack = new ScreenStack(activity, parent, screenParams.getNavigatorId(), this);
        LayoutParams lp = new LayoutParams(MATCH_PARENT, MATCH_PARENT);
        pushInitialScreen(lp);
}`

**Comment by guyca** [comment]
@michelantonides Yes, the code changed quite a lot since the issue was opened. I'll get to this issue today/tomorrow.

**Comment by michelantonides** [comment]
Any updates about this bug?

**Comment by guyca** [comment]
Hey @michelantonides Sorry about the delay

So I looked at the example project and `resetTo` seems to work fine in v2. Can you pull and check? Are you using v1.30 or v2.0 experimental?

**Comment by michelantonides** [comment]
I use:
react-native: 0.32.1
react-native-navigation: 2.0.0-experimental.117

On iOS resetTo works perfect. On android he keeps navigate me to the first page of my app.

```
this.props.navigator.resetTo({
  title: "",
  screen: "screen.HomeScreen",
});
```

**Comment by guyca** [comment]
Can you please provide more information? What is "first page" ? first tab?
please add steps that you take so I can reproduce the bug

**Comment by michelantonides** [comment]
I follow these navigation steps:

On iOS
1. Intro page (push to login page)
2. login page (resetTo Homepage)
3. Home page (Nice homepage with no back button)

On Android 
1. Intro page (push to login page)
2. login page (resetTo Homepage)
3. Intro page (Reset take me back to the intro page)

**Comment by guyca** [comment]
Thanks @michelantonides. Can you reproduce this bug in the example project?

**Comment by michelantonides** [comment]
The problem is also in the example project.

in the PushedScreen.js the function onResetToPress doesn't open the ThirdTabScreen.

```
onResetToPress() {
    this.props.navigator.resetTo({
      title: "New Root",
      screen: "example.ThirdTabScreen"
    });
  }
```

**Comment by michelantonides** [comment]
resetTo works in the example project. Something to do with react native version?

Example project: 0.31.0
My project: 0.32.1

**Comment by guyca** [comment]
I don't think so, but we should check anyways to eliminate the possibility.

**Comment by michelantonides** [comment]
I found something. 

When i use

```
Navigation.startTabBasedApp
```

The resetTo function work.

When i use

```
Navigation.startSingleScreenApp
```

The resetTo function doesn't work

**Comment by guyca** [comment]
In the example project?

**Comment by michelantonides** [comment]
My own project. I check example project

**Comment by michelantonides** [comment]
The example project has the bug also.

if you change the App.js code in startSingleScreenApp

```js
import {Navigation} from 'react-native-navigation';

// screen related book keeping
import {registerScreens} from './screens';
registerScreens();

// this will start our app
/*Navigation.startTabBasedApp({
  tabs: [
    {
      label: 'One',
      screen: 'example.FirstTabScreen',
      icon: require('../img/one.png'),
      selectedIcon: require('../img/one_selected.png'),
      title: 'Screen One'
    },
    {
      label: 'Two',
      screen: 'example.SecondTabScreen',
      icon: require('../img/two.png'),
      selectedIcon: require('../img/two_selected.png'),
      title: 'Screen Two',
      navigatorStyle: {
        tabBarBackgroundColor: '#4dbce9',
      }
    }
  ],
  drawer: {
    left: {
      screen: 'example.SideMenu'
    }
  }
});*/
Navigation.startSingleScreenApp({
  screen: {
    screen: 'example.FirstTabScreen',
    title: 'Navigation',
    navigatorStyle: {
      navBarBackgroundColor: '#4dbce9',
      navBarTextColor: '#ffff00',
      navBarSubtitleTextColor: '#ff0000',
      navBarButtonColor: '#ffffff',
      statusBarTextColorScheme: 'light'
    }
  },
  drawer: {
    left: {
      screen: 'example.SideMenu'
    }
  }
});
```

**Comment by michelantonides** [comment]
@guyca Tnx. working.

**Comment by guyca** [comment]
Sure. Thanks for reporting 👍
