### ISSUE TITLE
New compatibility issue with react-native-fbsdk on Android

### ISSUE THREAD

**Issue by amscher** [wix/react-native-navigation#2262]
### Issue Description
I'm using Firebase Facebook login in my app, and before using react-native-navigation, it worked perfectly. It still works on iOS, but on Android it seems that the callback functions are no longer called. I've seen multiple issues about this topic in other threads, #410 #373 #240 being the most helpful, however I have had no luck getting it to work after following the suggestions. 

These issues were also all opened about a year ago, so I'm wondering if maybe there's a different, new problem that I'm facing... Also these issues it seems are using V2 and I'm using V1. I attempted using V2, however still couldn't get it to work. The relevant code is below, I would really appreciate your help!

### Steps to Reproduce / Code Snippets / Screenshots

**MainApplication.java**
```javascript
import android.app.Application;
import android.content.Intent;

import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.appevents.AppEventsLogger;
import com.facebook.react.ReactApplication;
import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.analytics.RNFirebaseAnalyticsPackage;
import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import io.invertase.firebase.database.RNFirebaseDatabasePackage;
import io.invertase.firebase.storage.RNFirebaseStoragePackage;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.lwansbrough.RCTCamera.RCTCameraPackage;
import com.reactnativenavigation.NavigationApplication;
import com.reactnativenavigation.controllers.ActivityCallbacks;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends NavigationApplication {
  // Added for firebase / fblogin
  private static CallbackManager mCallbackManager = CallbackManager.Factory.create();

  protected static CallbackManager getCallbackManager() {
    return mCallbackManager;
  }

  // Added for react-native-navigation
  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  // Added for react-native-navigation
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
       new RNFirebasePackage(),
       new RNFirebaseAnalyticsPackage(),
       new RNFirebaseDatabasePackage(),
       new RNFirebaseAuthPackage(),
       new FBSDKPackage(mCallbackManager),
       new RNFirebaseStoragePackage(),
       new RCTCameraPackage()
    );
  }

  // Added for react-native-navigation
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }

  @Override
  public void onCreate() {
    super.onCreate();
    // To get FBSDK to work
    setActivityCallbacks(new ActivityCallbacks() {
      @Override
      public void onActivityResult(int requestCode, int resultCode, Intent data) {
        mCallbackManager.onActivityResult(requestCode, resultCode, data);
      }
    });
    FacebookSdk.sdkInitialize(getApplicationContext());
    AppEventsLogger.activateApp(this);
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

**MainActivity.java**
```Javascript
import com.facebook.react.ReactActivity;
import com.reactnativenavigation.controllers.SplashActivity;
import android.content.Intent;

public class MainActivity extends SplashActivity {
     @Override
     public void onActivityResult(int requestCode, int resultCode, Intent data) {
         super.onActivityResult(requestCode, resultCode, data);
         MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
     }
}
```

**LoginForm**
```Javascript
LoginManager
	.logInWithReadPermissions(['public_profile', 'email'])
	.then(
             function(result) {console.log("trying to login")},
             function(error) {console.log(error)}
         )
```
Neither the success or error callbacks are getting called....

---
### Environment
* React Native Navigation version: 1.1.298
* React Native version: 0.49.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device,  Moto G (5) Plus - 7.0, Debug

**Comment by chaitanya0bhagvan** [comment]
Can remove onActivityResult from MainActivity.java and try?

**Comment by perrosnk** [comment]
@amscher have you found a solution to that?

**Comment by TONYHOKAN** [comment]
Maybe you have inputed incorrect android Key Hashes to facebook app?

I encountered the same behaviour event if i have followed the solution provided. 
Finally i found that it was my mistake and not related to RNN.

I run `adb logcat` in console to monitor if something wrong when clicking LoginButton in my android app, then below exception thrown:
```
1634  8688 W fb4a.BlueServiceQueue: Exception during service
1634  8688 W fb4a.BlueServiceQueue: X.3Q7: [code] 404 [message]: Key hash {longstring} does not match any stored key hashes. (404) [extra]: null
```
I copied the Key hash to my facebook app, clicked LoginButton again and it worked!

I just wondered why the exception was not returned to error object...

**Comment by juanlet** [comment]
I also have this same problem....

**Comment by kevinkevw** [comment]
After removing onActivityResult inside MainActivity.java I can get the callback.
Hope it helps.

**Comment by xe4me** [comment]
In my case, after adding the onActivityResult like above , it still didn't work, did some debugging and turned out that the SDK was trhowing.

I removed bellow like of code from my React code

`LoginManager.setLoginBehavior('native');`

**Comment by manojkmishra** [comment]
I tried many things but nothing is working out. I am working on windows with  "react-native": "0.55.4",
    "react-native-fbsdk": "^0.7.0", "react-native-navigation": "^1.1.461".

Popup is coming after pressing the button, it takes facebook login/pass verifies it, but after submit, nothing is returned. 

I tried removing onActivityResult also-- so MainActivity.java looks like this (not sure if this is correct) but still nothing is returned
---------------------------------------------------------
package com.instagramclone;
import com.reactnativenavigation.controllers.SplashActivity;
import android.content.Intent;

public class MainActivity extends SplashActivity {

  //  @Override
 //   public void onActivityResult(int requestCode, int resultCode, Intent data) {
  //      super.onActivityResult(requestCode, resultCode, data);
  //      MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
 //   }
}
------------------------------------------------------------

**Comment by manojkmishra** [comment]
Issue got resolved(LoginManager.logInWithReadPermissions promise getting resolved) after modifying onCreate()  in MainApplication.java. So to use react-native-navigation with react-native-fbsdk, it seems we need to import com.reactnativenavigation.controllers.ActivityCallbacks and use it in MainApplication.java.

MainActivity.java:

package com.instagram_mobile;
import com.reactnativenavigation.controllers.SplashActivity;
import android.content.Intent;
public class MainActivity extends SplashActivity {
 @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
    }
  }

===============================================
MainApplication.java:

package com.instagram_mobile;
import com.facebook.react.ReactPackage;


import com.reactnativenavigation.NavigationApplication;
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
import com.BV.LinearGradient.LinearGradientPackage;
import com.facebook.CallbackManager;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import com.facebook.appevents.AppEventsLogger;
import com.facebook.FacebookSdk;

import java.util.Arrays;
import java.util.List;
import com.oblador.vectoricons.VectorIconsPackage;
import com.reactnativenavigation.controllers.ActivityCallbacks;
import android.content.Intent;

public class MainApplication extends NavigationApplication 
{   private static CallbackManager mCallbackManager = CallbackManager.Factory.create();
    protected static CallbackManager getCallbackManager() {   return mCallbackManager; }
    
    @Override
    public boolean isDebug() 
    {  // Make sure you are using BuildConfig from your own application
        return BuildConfig.DEBUG;
    }

    protected List<ReactPackage> getPackages() 
    {   // Add additional packages you require here
        // No need to add RnnPackage and MainReactPackage
        return Arrays.<ReactPackage>asList(
             new VectorIconsPackage(),
             new RNGestureHandlerPackage(),
             new LinearGradientPackage(),
             new FBSDKPackage(mCallbackManager)
        );
    }

    @Override
    public List<ReactPackage> createAdditionalReactPackages() {   return getPackages();  }

    @Override
    public String getJSMainModuleName() { return "index";  }

    public void onCreate() 
    {    super.onCreate();
        setActivityCallbacks(new ActivityCallbacks() 
                {   @Override
                    public void onActivityResult(int requestCode, int resultCode, Intent data) 
                    {  mCallbackManager.onActivityResult(requestCode, resultCode, data);
                    }
                });
        FacebookSdk.sdkInitialize(getApplicationContext());
        // If you want to use AppEventsLogger to log events.
        AppEventsLogger.activateApp(this);
      }
}
