### ISSUE TITLE
 tabbar icon disappear when generating APK app.

### ISSUE THREAD

**Issue by criticalnooks** [wix/react-native-navigation#2265]
### Issue Description

when I run as react-native run-android. Everything is work.

![2](https://user-images.githubusercontent.com/29303670/33530368-f820da1c-d8b0-11e7-8e7a-8c0d25e7abff.png)

But when I generating APK app. And install it on real device.Only just tabbar text appear.

![1](https://user-images.githubusercontent.com/29303670/33530369-fb3fd1da-d8b0-11e7-8156-5d381b0b3b5e.png)

---
### Environment
* React Native Navigation version: 1.1.295
* react-native: 0.46.3
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): device Android 5.1.1

**Comment by outPlanetDev** [comment]
I am with this problem now, don't know what to do

**Comment by criticalnooks** [comment]
At first my problem occur when I generate APK with these 2 steps
1. `react-native bundle --dev false --platform android --entry-file index.android.js --bundle-output ./android/app/build/intermediates/assets/debug/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/debug`
2. `./gradlew assembleDebug`

And I have solved with following by [this link](https://facebook.github.io/react-native/docs/signed-apk-android.html). At first you should generate a signing key after that just run `cd android && ./gradlew assembleRelease` (have to do with assembleRelease not assembleDebug).
