### ISSUE TITLE
Support floating screen

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#2277]
Dear all,
First of all, I so sorry because I can not be able to post in "Pull request"
I would like to create a floating view like Youtube player. It means, the video can play while we changing to other tabs
I ask for supporting floating view or any existing solutions?

**Comment by hjh5696** [comment]
Anybody who has a workaround about this?

**Comment by guyca** [comment]
This is possible in v2 using an [Overlay](https://wix.github.io/react-native-navigation/v2/#/docs/top-level-api?id=showoverlaylayout-)
