### ISSUE TITLE
navBarCustomView component is mounted twice

### ISSUE THREAD

**Issue by althamash-chaipoint** [wix/react-native-navigation#2278]
### Issue Description
I have a custom component registered and assigned to navBarCustomView in a startTabBasedApp.
The header will show the current address based on the device's location. I am calling a function that does the geocoding for me, which accepts a callback. In the callback I am setting the state of the header component.

I get a warning 

> Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

I noticed that the header component is getting mounted twice resulting in the above error.

### app.js
```
import {Platform} from 'react-native';
import {Navigation} from 'react-native-navigation';
import {registerScreens} from './screens';

import Stores from './stores';
import Provider from './utils/MobxRnnProvider';

registerScreens(Stores, Provider);

const tabs = [{
  screen: 'app.OrderScreen',
  icon: require('../img/three.png'),
  selectedIcon: require('../img/three_selected.png')
},{
  screen: 'app.OtherScreen',
  icon: require('../img/reports-icon.png'),
  selectedIcon: require('../img/reports-active-icon.png')
}];

Navigation.startTabBasedApp({
  tabs,  
  animationType: Platform.OS === 'ios' ? 'slide-down' : 'fade',
  appStyle: {
    navBarCustomView: 'app.GeoHeader', //Registered custom header component
    navBarBackgroundColor: 'rgba(255,255,255,0.5)',
    navBarTranslucent: true,
    navBarNoBorder: true,
    drawUnderNavBar: true,
    navBarTextColor: '#333333',
  }
});
```
### geoHeader.js
```
import React from 'react';
import {StyleSheet, View, Text} from 'react-native';
import {getCurrentAddress} from '../utils/utils';

class GeoHeader extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            currentAddress : 'Locating ...'
        }
    }
    componentDidMount(){
        console.log("DID_MOUNT_HEADER");        
        let that = this;
        getCurrentAddress(obj => {
            that.setState({currentAddress: obj.formattedAddress});
        });
    }
    render() {
        return (
            <View style={styles.header}>
                <Text>Location : {this.state.currentAddress}</Text>
            </View>
        );
    }
}

export default GeoHeader;
```
### Screenshot of debug console
<img width="773" alt="screen shot" src="https://user-images.githubusercontent.com/26251165/33599574-8fc19af2-d9cc-11e7-9401-face502ed826.png">

---
### Environment
* React Native Navigation version: 1.1.275
* React Native version: 0.50.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 6 - iOS 11.1

**Comment by davidliu** [comment]
I'm getting the same error, except my navBarHeaderView doesn't even have a state (functional component).

**Comment by zhaiyjgithub** [comment]
same issue.

**Comment by manjeetwadi** [comment]
+1
