### ISSUE TITLE
selectedIcon doesn't work on Android

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#228]
"react-native-navigation": "2.0.0-experimental.72"

**Comment by guyca** [comment]
`selectedIcon` property isn't supported on Android. On Android, when a tab is selected the icon is tinted in a different color. Use `tabBarSelectedButtonColor` for that.

**Comment by agumack** [comment]
OK @guyca

**Comment by bdavid68** [comment]
Solved and made PR.

[https://github.com/wix/react-native-navigation/pull/1721](url) : iOS
[https://github.com/wix/react-native-navigation/pull/1723](url) : Android

Waiting for review and merge.
