### ISSUE TITLE
How to use setTabBadge on android

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#229]
Hi @guyca 

setTabBadge feature ready on android? 
I am using this code but it doesn't work. thank you so much!
> this.props.navigator.setTabBadge({
>  tabIndex: 2,
>  badge: 4
> });

**Comment by guyca** [comment]
not yet @agumack.

**Comment by agumack** [comment]
OK. thank you for the quick response @guyca

**Comment by guyca** [comment]
@agumack fixed in v2.0.0-experimental.73
