### ISSUE TITLE
[V2] Title not showing in iOS

### ISSUE THREAD

**Issue by pnewell** [wix/react-native-navigation#2291]
### Issue Description

I am working to switch to V2 and cannot get the title not showing at the top when the app first loads.

### Steps to Reproduce / Code Snippets / Screenshots

This is what I am trying right now with no luck, is this doucmented somewhere?
<img width="385" alt="screen shot 2017-12-05 at 11 07 56 pm" src="https://user-images.githubusercontent.com/6485697/33644169-2f072d18-da11-11e7-97a0-cfe287a15cc3.png">
:

```js
  Navigation.events().onAppLaunched(() => {
    Navigation.setRoot({
      container: {
        name: 'navigation.MovieTickets.Movies',
        title: 'Movies' // title of the screen as appears in the nav bar (optional)
      },
      topBar: {
        title: 'Movies',
        textColor: 'black',
        textFontSize: 16,
        textFontFamily: 'HelveticaNeue-Italic'
      }
    });
  });
}
```

---
### Environment
* React Native Navigation version: 2.0.2027
* React Native version: 0.50.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by yogevbd** [comment]
The right way to use topBar options is to pass it inside navigationOptions under container. 
for example:

```
Navigation.setRoot({
        container: {
          name: 'navigation.MovieTickets.Movies',
          navigationOptions: {
            topBar: {
              title: 'Movies',
              textColor: 'black',
              textFontSize: 16,
              textFontFamily: 'HelveticaNeue-Italic'
            }
          }
        }
      });
```
