### ISSUE TITLE
iOS Bad Exec

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#2292]
Dear all,
I found crash with BAD_EXEC on iOS in this case
I have a Tab app with 5 tabs: A, B, C, D, E
When we in tab C, we push screen on tab C as: C -> C1 -> C2
Then, you tab on the tab "C" icon at bottom, navigation automatically pop all to root of tab C
Then, we push another screen from tab C to C3. It crash at RCCViewController.m line 634
`id <UIGestureRecognizerDelegate> interactivePopGestureRecognizer = self.navigationController.interactivePopGestureRecognizer.delegate;`

Can reproduce 100% on iOS 8.1 with simulator or device
---
* React Native Navigation version: 1.1.300
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 8.1

**Comment by eldereal** [comment]
Also crashes on version 1.1.297, iOS 8.4.1
