### ISSUE TITLE
tabs icon placement is not centered on android

### ISSUE THREAD

**Issue by chenbekor** [wix/react-native-navigation#2295]
### Issue Description

in android - when using tabs (startTabBasedApp) with 2 tabs, the button are not centered correctly:

<img width="233" alt="screen shot 2017-12-06 at 13 01 13" src="https://user-images.githubusercontent.com/1867481/33658791-9128540c-da86-11e7-9224-a18c2d921375.png">

on iOS it renders just fine:

<img width="269" alt="screen shot 2017-12-06 at 13 14 01" src="https://user-images.githubusercontent.com/1867481/33659018-5e52ff90-da87-11e7-8f75-6d2192a719e7.png">

### Environment
* React Native Navigation version:1.1.299
* React Native version:0.45.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by simonedavico** [comment]
This is not a bug, it's just that by default on Android you see only the label of the selected tab. Use 

```
appStyle: {
    forceTitlesDisplay: true
}
```

To get persistent labels on Android, as it is on iOS.
