### ISSUE TITLE
Questions regarding data loading and state management.

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#23]
I absolutely adore working with this navigation system. In the beginning, I was most excited about react-native-navigation, particularly the possibility for different drawer variations.  Seeing how react-native-controllers now supports this feature, I look forward to it becoming  available via react-native-navigation.  Nevertheless, the more I fiddle arround with this system, the more I appreciate how easy it feels.  I ran in to a few things that have me wondering. 

Do you have a recommendation regarding file structure (e.g modules) and state management?  
I notice other navigators are moving quickly to support redux, and that's no exception here. However, I'm curious about the decision to encapsulate parts of the Redux setup. Essentially,  the way you have the redux model setup, passing around my application "context" is sort of tricky. I'd like to pass them as props; perhaps via  registerComponentRedux( ). I'm not sure, should I gain access via the generator or by passing a { optional }.  Inside the Navigator, the props are spread, so it seems I could pass an optional  prop. When things are simple, it may work. I'm curious about how this would hold much can be done here,
`
  function _registerComponentRedux(screenID, generator, store, Provider) {
      const generatorWrapper = function() {
      const InternalComponent = generator();
      return class extends Screen { .. 
      render() {
        return (

```
      <Provider store={store}>
        <InternalComponent navigator={this.navigator} {...this.props} />
      </Provider>

    );
  }
};
```

  };
`
This lead to questions about file structure. Here's a popular setup

src
  config
  modules
       moduleOne
            actions
            components
            containers (or screens)
            resolvers
            screens
            index.js
            routes.js

```
   moduleTwo
        ...
   app.js 
```

My thoughts are to align each "tab" to a module then call  registerCompontents at the module level instead of at the top. Indeed since each tab and each single root encapsulates a stack of screens,where  each may call on its own state and context management regimes,  I'm using meteor and DDP to interact with my data.  It appears all the data my app demands is called in from the start. For a data intensive system, what do you think is the best way to use react-native-navigation to support use cases similar what's described here?

**Comment by pvlvsk** [comment]
Thats my question too, I'm switching to this project from NavigatorIOS and that was a bit strange to see all my components load at start at the same time. Is there a workaround to prevent this?

**Comment by pqkluan** [comment]
Close this issue since the current [register API ](https://wix.github.io/react-native-navigation/#/top-level-api?id=registercomponentscreenid-generator-store-undefined-provider-undefined) has support redux.
