### ISSUE TITLE
Callback for onTabSelected

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#230]
Are there plans to be able add callbacks to the `onTabSelected` method for bottom tabs?
I guess this would come under the screen lifecycle callbacks... 
This would be very handy so I know which screen is visible on a `tabBasedLayout`.

**Comment by guyca** [comment]
Hey @adamski This feature is in the roadmap. We also need it for our production apps.
closing this issue, let keep discussion in #16
