### ISSUE TITLE
[Android] tabBarSelectedButtonColor bug in released apk

### ISSUE THREAD

**Issue by criticalnooks** [wix/react-native-navigation#2300]
### Issue Description

When I run as react-native run-android. Everything is works.

After generating APK app using assembleRelease. When I selected or unselected the tab. Icon color and Label color not the same color.

![11](https://user-images.githubusercontent.com/29303670/33686433-7cb78976-db07-11e7-9e53-3a85ee01b14d.png)
![22](https://user-images.githubusercontent.com/29303670/33686434-7cf31ea0-db07-11e7-8939-df2741b8f4a1.png)
![33](https://user-images.githubusercontent.com/29303670/33686436-7d551966-db07-11e7-9cda-d0720d56e757.png)

---
### Environment
* React Native Navigation version: 1.1.295
* React Native version: 0.46.3
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Android 5.1.1

**Comment by criticalnooks** [comment]
solved :)

**Comment by ShinHyunJong** [comment]
@criticalnooks  Can I ask how you solved it pls? I am having same error...

**Comment by criticalnooks** [comment]
@ShinHyunJong I found that my problem occur when a many icon use the same image (look at screen1 and screen2 tabbar).I solved by duplicate the image and assign to that two icons.

**Comment by ShinHyunJong** [comment]
@criticalnooks Thank you so much! you save my life 💃
