### ISSUE TITLE
Drawer not works as expected

### ISSUE THREAD

**Issue by thundernet8** [wix/react-native-navigation#2302]
### Issue Description

startTabBasedApp, add left menu screen as drawer, gesture or toggleDrawer API never call the left menu successfully.

I tried any hacks from those issues. e.g. remove `to: "open"`, set fixed width of drawer screen, but always failed

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.startTabBasedApp({
        tabs: [
            {
                label: "Feeds",
                screen: Screen.HOMEFeedsTab,
                icon: icons[0],
                title: "Feeds",
                navigatorButtons: {
                    leftButtons: [
                        {
                            id: "sideMenu"
                        }
                    ]
                }
            },
            {
                label: "Issues",
                screen: Screen.HOMEIssuesTab,
                icon: icons[1],
                title: "Issues",
                navigatorButtons: {
                    leftButtons: [
                        {
                            id: "sideMenu"
                        }
                    ]
                }
            }
        ],
        drawer: {
            left: {
                screen: Screen.LeftMenu,
                passProps: {}
            },
            disableOpenGesture: false
        }
    });
```

screen which has the menu button:
```
constructor(props) {
        super(props);
        this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent);
    }

    onNavigatorEvent = event => {
        console.log(event);
        if (event.type === "NavBarButtonPress") {
            if (event.id === "sideMenu") {
                this.props.navigator.toggleDrawer({
                    side: "left" // the side of the drawer since you can have two, 'left' / 'right'
                    // animated: true,
                    // to: "open" 
                });
            }
        }
    };
```

---
### Environment
* React Native Navigation version: 1.1.298
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus_5X_API_27_x86(AVD) - 8.1.0 and SM-N9500 - 7.1.1

**Comment by thundernet8** [comment]
I downgrade my react-native version to `0.50.4`, it's works now. Maybe some changes between `0.50` and `0.51` has broken our package functionality.

**Comment by johngoren** [comment]
Downgrading to 0.50.4 worked for me too.

**Comment by johngoren** [comment]
Still getting this issue in version 1.1.323 if I go up to RN 0.51.

**Comment by johngoren** [comment]
Anyone know of a good breakpoint for testing drawer behavior in Android?

**Comment by SquaredData** [comment]
I have the same issue, with version 0.50.4 and 0.51

**Comment by dre4success** [comment]
Having this issue with version 0.50.3, width is set in the drawer component. 99% of the time, the drawer doesn't work

**Comment by SquaredData** [comment]
I had the same issue with the latest RN version! Try RN 0.49.5, this one works for me!

**Comment by dre4success** [comment]
Thanks @SquaredData. Just tried it now and it worked.
