### ISSUE TITLE
navigator.push from tab behaviour

### ISSUE THREAD

**Issue by jurajkrivda** [wix/react-native-navigation#2309]
Hi I have a problem.
I have five tabs. T1 - T5. I also have other single screens like About etc. I am on T1, click on About button and I am in About Page. Then, I click to T2 tab. I see content in T2 tab. It is ok. But then I clicked to T1 tab and I see About page, not original content from T1 tab. Everytime I click on tab I want to see content from this tab. Please help me. Thank you.

**Comment by igez** [comment]
+1

have similar issue, need to make the tabs always show its root screen, is this something doable with current API?

**Comment by Dielz98** [comment]
That’s expected and should be like that

**Comment by AbdoelKaheal** [comment]
my first guess would be to try to pop when the tab unmounts or something like that.

**Comment by guyca** [comment]
This is the expected behaviour, tabs don't pop stacks when you switch between them.
