### ISSUE TITLE
Multiple Route Pop Issue

### ISSUE THREAD

**Issue by dogbutcat** [wix/react-native-navigation#2317]
### Issue Description

The situation is I need to pop to target screen, eg. A->B->C, I need to pop back to screen A. Currently, the pop method seems only support one screen pop, from C back to B, and popToRoot is truly pop to root which is not root, so is there any good way to satisfy the situation? Thanks!

---
### Environment
* React Native Navigation version: 1.1.300
* React Native version: 0.50
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by nhohb07** [comment]
Same issue, and any idea for back from this tab to another tab?

This mean: 

Tab1:
  Screen 1
  Screen 2

Tab2:
  Screen 3
  Screen 4

Navigate Screen 1 -> Screen 2 -> Screen 4
I want to back from Screen 4 to Screen 1

Many thanks

**Comment by heiheiLqq** [comment]
Same issue ！ How to resolve

**Comment by dogbutcat** [comment]
@heiheiLqq Method we use at that time(till now) is forking the [react-navigation](https://reactnavigation.org) and add extra action with rewrite the navigate and back transition animation for gesture support to meet such requirement.

**Comment by guyca** [comment]
`popTo(componentId)` is implemented in v2. You'll be able to define `componentId` to easily support this use case. For example:

```js
Navigation.setRoot({
    stack: {
      children: [
        {
          id: 'ROOT',
          name: 'com.app.rootScreen'
        }
      ]
    }
  });
```

Then, after pushing some screens into the stack, call `Navigation.popTo('ROOT')` to pop to the initial screen.
