### ISSUE TITLE
how to make switchToTab rerender

### ISSUE THREAD

**Issue by moeinrahimi** [wix/react-native-navigation#2325]
I need to re render one of my tabs when i switch to it.
my scenario : there is a post tab which users creates posts, I want to switch to posts list tab when user created post so he can see the post, like what instagram have. also I read in one of issues that if you use redux rerendering tabs will automatically work, why this is not working without redux ? 

update : I'm achieve this by using onNavigatorEvent and listening to didAppear but it's not good since every time tab gets selected this events will called, also before swithing tab i Need to pop to the root of that tab to it's default layout .
right now i'm using it like this =
in postTab after post created : 
``` javascript
   this.props.navigator.popToRoot({
          animated: true,
          animationType: 'fade', 
        });
            this.props.navigator.switchToTab({
          tabIndex: 3 
        });
```

and in postList tab 
``` javascript
  onNavigatorEvent(event) {
    switch(event.id) {
      case 'didAppear':
      let userId =this.state.userId
      let token =  getStorage('token')    
      this.getUserData(userId,token)
              break;
    }
  }
```
I think there might be a better way to achieve this, I wonder why no one had asked this before it's such a normal functionality in apps

**Comment by guyca** [comment]
In RNN, we took an imperative approach to navigation. But your internal logic and data flow should still be declarative and use flux.
Before after `navigator.switchToTab()`, dispatch an action that will trigger data refresh and consecutively a render. 
Hope that answers your question.

**Comment by moeinrahimi** [comment]
so basically i have to use one of these state managment libraries to achieve this ? can i use redux too ?

**Comment by rashidul0405** [comment]
@guyca After tried the `React context API` option, switches to `Redux`. However, the whole stack (all screens) on a tab gets the updated state but other tabs are not re-rendering on redux state change.
