### ISSUE TITLE
this.props.navigator gives undifined

### ISSUE THREAD

**Issue by nandi-krisanu** [wix/react-native-navigation#2326]
### Issue Description

While pushing

        this.props.navigator.push({
            screen: 'LoginLayout',
            title: 'Screen 3'
          });

gives  this.props.navigator undefined. 

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.305
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android N, Debug

**Comment by varungupta85** [comment]
This is not enough information to debug the problem. You need to provide steps to reproduce, code snippets etc. as mentioned in the issue template.

**Comment by nandi-krisanu** [comment]
It is now solved, may be happen due to limited knowledge about react.
I was writing as:
```
            <Button
                title="Registration"
                onPress={this._handleClickNextButton}
                />
```
Then convert to 
```
            <Button
                title="Registration"
                onPress={this._handleClickNextButton.bind(this)}
                />
```
Now it is working.
