### ISSUE TITLE
React context not initialized on first load and app doesn't pass splash screen

### ISSUE THREAD

**Issue by italonascimento** [wix/react-native-navigation#2340]
### Issue Description

I'm running on Android device, and when I start the app it won't pass the splash screen. If I switch to another app and come back, it runs correctly.

By putting some logs in the SplashActivity `onResume`, I found out it doesn't pass this condition on startup:

```java
if (NavigationApplication.instance.isReactContextInitialized()) {
    NavigationApplication.instance.getEventEmitter().sendAppLaunchedEvent();
    return;
}
```

### Steps to Reproduce / Code Snippets / Screenshots

Here's my `MainActivity`:

```java
public class MainActivity extends SplashActivity {

    @Override
    public View createSplashLayout() {
        View view = new View(this);
        view.setBackgroundColor(Color.CYAN);
        return view;
    }
}
```

And my `MainApplication`:

```java
public class MainApplication extends NavigationApplication {

  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
      new VectorIconsPackage(),
      new RCTCameraPackage(),
      new ReactNativeDialogsPackage()
    );
  }

  @Override
  public String getJSMainModuleName() {
    return "artifacts/index";
  }

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }
}
```
---
### Environment
* React Native Navigation version: **1.1.284**
* React Native version: **0.50.3**
* Platform(s) (iOS, Android, or both?): **Android**
* Device info (Simulator/Device? OS version? Debug/Release?): **Device / 6.0.1 / Debug**

**Comment by italonascimento** [comment]
Just found out it's the same as #963. The bug only occurs with remote js debug enabled and hot reload turned off.

**Comment by MiLeung** [comment]
I'm getting this bug regardless of dev settings

**Comment by RicardoBer** [comment]
Same here, exact the same issue

prop-types@15.6.0
react@16.0.0-alpha.6
react-native@0.44.2
react-native-navigation@1.1.235

Easy to reproduce.

Donload https://github.com/wix/react-native-navigation-bootstrap
npm install

But it works when execute from cmd with "react-native run-android"

and fails when use visual studio code and react native tool. This don't happend without react native navigation. So it seems to be related to a vs code and react native navigation conflict.

**Comment by qasimalbaqali** [comment]
Same issue having here

```
"react": "^16.3.0-alpha.1",
"react-native": "0.54.0",
"react-native-navigation": "^1.1.398"
```
