### ISSUE TITLE
[iOS]"tabBarBackgroundColor: transparent" not worked

### ISSUE THREAD

**Issue by koansang** [wix/react-native-navigation#2343]
### Issue Description

If set tabBarBackgroundColor to `transparent`, background color is black in iOS.

My options : 
```js
 Navigation.startTabBasedApp({
    tabs: routes,
    tabsStyle: {
      tabBarButtonColor: '#4a4a4a',
      tabBarSelectedButtonColor: '#05a1ff',
      tabBarBackgroundColor: 'transparent',
      tabBarTranslucent: true,
      tabBarHideShadow: true,
      initialTabIndex,
    },
    appStyle: {
      tabBarButtonColor: '#4a4a4a',
      tabBarSelectedButtonColor: '#05a1ff',
      tabBarBackgroundColor: '#ffffff',
      tabBarTranslucent: true,
      orientation: 'portrait',
      hideBackButtonTitle: true,
    },
  });
```

### Steps to Reproduce / Code Snippets / Screenshots
![image](https://user-images.githubusercontent.com/12390185/33989272-3ca34c22-e10a-11e7-92f2-d737aa0f9219.png)

---
### Environment
* React Native Navigation version: 1.1.309
* React Native version: 0.50.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): simulator iPhone 6

**Comment by NichAga** [comment]
I think you should put "drawUnderTabBar" also.

**Comment by koansang** [comment]
@NichAga OK~
I'm set `drawUnderTabBar` is **true**.
But same problem.

**Comment by koansang** [comment]
not worked `drawUnderTabBar` in iOS.

**Comment by brunolemos** [comment]
I can confirm `tabBarBackgroundColor: 'transparent'` does not work, neither does `drawUnderTabBar: true` or `tabBarTranslucent: true`.

**Comment by 1pocketaces1** [comment]
still not working any solutions?
