### ISSUE TITLE
Can't set navigation bar text font weight

### ISSUE THREAD

**Issue by jasonmerino** [wix/react-native-navigation#2350]
### Issue Description

I am trying to add a bold weight to the TopBar > TitleBar > title and cannot find a way to do this on Android. I am using a custom font family for the `navBarTextFontFamily` property when starting the app, and on iOS it pulls the font weight from that font family, but on Android it doesn't seem to respect the font weight that is applied to that font family.

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by jasonmerino** [comment]
Never mind this issue. I just found the prop to force it over to being bold [here in the documentation](https://wix.github.io/react-native-navigation/#/styling-the-navigator?id=style-object-format). The property I was looking for was the (Android only) `navBarTextFontBold`.

**Comment by mths0x5f** [comment]
Is it possible to use this in v2?
