### ISSUE TITLE
setOnNavigatorEvent doesn't pick up all events

### ISSUE THREAD

**Issue by abeaclark** [wix/react-native-navigation#2355]
### Issue Description

When using the setOnNavigatorEvent API, I only get events with the following ids:
* willAppear
* didAppear
* willDisappear
* didDisappear

From the documentation, I expect to get an event with an id of "back" when the navigator back button is pressed. I never receive this event.

If I override the back button with an id, it still doesn't come through. Only if I override the back button with an id & icon, or id and title does the id come through setOnNavigatorEvent.

I want to be able to use the standard navigator (with the standard back button) and be notified when the back button is pressed.

### Steps to Reproduce / Code Snippets / Screenshots

```
constructor(props) {
     ...
      this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this))
      ...
    }

    onNavigatorEvent(event) {
      console.log(event)
      // only shows the above-metioned events
    }
```
If I add the following, I still don't get an event with id === 'back':
```
static navigatorButtons = {
    leftButtons: [
      {
        id: 'back',
      },
    ],
  }
```
only if I add the following do I start seeing the event appear. BUT, it means that the navigator displays the text "Back" and the built-in functionality is broken (does not go back when clicked, does not disappear when the nav stack is length is 0.
```
static navigatorButtons = {
    leftButtons: [
      {
        id: 'back',
        title: 'Back'
      },
    ],
  }
```
---
### Environment
* React Native Navigation version: 1.1.198
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by ShaunSpringer** [comment]
I have the same issue. It's making this library virtually unusable because it's impossible to keep track of state. 

Every navigation event needs to be propagated (back, appear, disappear, drawer open, drawer close).
