### ISSUE TITLE
navigatorBar & topTabs different background color

### ISSUE THREAD

**Issue by sfratini** [wix/react-native-navigation#2357]
### Issue Description

Is there a way to have a different color for the navigatorBar and another for the TopTabs? Can't find a way to do it looking at the docs nor code. Thanks

### Environment
* React Native Navigation version: 1.1.210
* React Native version: 0.48.1
* Platform(s) (iOS, Android, or both?): Android (iOS in the future)

**Comment by szemeii** [comment]
Is there any solution?
