### ISSUE TITLE
tabBarTranslucent not working

### ISSUE THREAD

**Issue by brunolemos** [wix/react-native-navigation#2359]
### Issue Description

Setting `tabBarTranslucent: true` on the `tabsStyle` has not effect.

### Steps to Reproduce / Code Snippets / Screenshots

<img width="368" alt="image" src="https://user-images.githubusercontent.com/619186/34073486-f7911352-e281-11e7-9c14-87d58cd3b92c.png">

```js
Navigation.startTabBasedApp({
    tabs: [
      {
        icon: icons.feed,
        label: 'Feed',
        screen: 'screen id here',
        title: '',
      },
    ],
    tabsStyle: { // ios tab tar
      // tabBarBackgroundColor: '#000000',
      tabBarTranslucent: true,
    },
  })
```

---
### Environment
* React Native Navigation version: ^1.1.311
* React Native version: ^0.51.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info: iPhone X Emulator (iOS 11.2) Debug mode

**Comment by manuhook** [comment]
You have to use drawUnderTabBar true to make it work

**Comment by brunolemos** [comment]
Thanks
