### ISSUE TITLE
Android app crashes due to RuntimeException on changing font size of the phone and opening the app again

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#2364]
### Issue Description

My android app crashes with below exception when I change the font-size of the phone and open the app again.

![screen shot 2017-12-17 at 3 53 59 pm](https://user-images.githubusercontent.com/7475133/34078585-eabfac62-e342-11e7-9e11-a2a90dab932d.png)

The crash is reproducible and I am able to reproduce the crash in the Wix Android app also. Just start the app. Go to phone settings and change the font size of the phone and then go back to the app and observe the crash.

The crash doesn't seem to be related to RNN but it started to happen after I updated from `1.1.206`. There is an open issue on `react-native` report also https://github.com/facebook/react-native/issues/16959 and there also all the reporters figured that they have all have RNN in common.

I have observed the same crash happened at other times also for e.g. when I am on a different app and I start my app. But that is intermittent. By changing the font size and going back to the app, I can see the issue repeatedly.

### Steps to Reproduce / Code Snippets / Screenshots

1. Start the app
2. Go to phone settings and change the font size of the phone
3. Go back to the app

---
### Environment
* React Native Navigation version: 1.1.305
* React Native version: 0.49.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by linnett** [comment]
We also have this issue but it happens for a different reason. After a long period of using other apps on the phone and then later going back to the app, it crashes on start. 
Would be great to get an answer as to why this happens.

React Native Navigation version: 1.1.227
React Native version: 0.47.1
Platform(s) (iOS, Android, or both?): Android

**Comment by varungupta85** [comment]
@linnett My app users have also observed this crash as you have described that is after using other apps for a long period of time and then going back to the app. But I was able to consistently reproduce the same crash by changing the font size. So that is how I reported the issue.

@guyca Please share if you have any comments on this issue.

**Comment by linnett** [comment]
@varungupta85 Yes I can confirm I am also getting the error on fontSize change, every time. That's not the end of the world for me. The biggest issue is the period of inactivity.

It's worth pointing out that on Android 8.1, the app just freezes on the launch screen and doesn't do anything. On <= 8.0, the SimpleSettableFuture error occurs. 
Would really welcome a solution to this - we can't be the only ones getting the issue.

**Comment by varungupta85** [comment]
@linnett I agree, for me also the main issue is the period of inactivity. I don't really care about people changing the font size of the phone because that is not a common/repeating operation.

**Comment by enahum** [comment]
yup same here, after a long inactive period switching to the app it hangs for a long time on the splashScreen and then it crashes, even with:

```js
Promise.resolve(Navigation.isAppLaunched()).then((appLaunched) => {
                    if (notification) {
                        if (appLaunched) {
                            this.launchApp(); // App is launched -> show UI
                        } else {
                            new NativeEventsReceiver().appLaunched(this.launchApp); // App hasn't been launched yet -> show the UI only when needed.
                        }
                    } else {
                        this.launchApp();
                    }
                });
```

**Comment by linnett** [comment]
Any news on this?

**Comment by neuberoliveira** [comment]
for me it happens sundelly, i justopen the app and leave it for a while, and then it crash, not sure if its related but the error i got is this:

	I/DEBUG(302): pid: 6919, tid: 6974, name: mqt_native_modu  >>> COM.MY.APP.BUNDLE.ID <<<
	W/BroadcastQueue(520): Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{229e99c0 6919:COM.MY.APP.BUNDLE.ID/u0a553} (pid=6919, uid=10553) requires android.permission.READ_LOGS due to sender android (uid 1000)
	I/WindowState(520): WIN DEATH: Window{354d2a58 u0 COM.MY.APP.BUNDLE.ID/com.reactnativenavigation.controllers.NavigationActivity}
	I/ActivityManager(520): Process COM.MY.APP.BUNDLE.ID (pid 6919) has died
	W/ActivityManager(520): App Op not allow to restart app COM.MY.APP.BUNDLE.ID/10553
	W/ActivityManager(520): Force removing ActivityRecord{17cda728 u0 COM.MY.APP.BUNDLE.ID/com.reactnativenavigation.controllers.NavigationActivity t4109}: app died, no saved state


And i already add the `android.permission.READ_LOGS`

**Comment by nimabk82** [comment]
any update for this issue

**Comment by Alexyzyz** [comment]
any update for this issue

**Comment by guyca** [comment]
Hey @Alexyzyz 👋 
As this is a closed issue from 4 years ago, I suggest you [open a new issue](https://github.com/wix/react-native-navigation/issues/new/choose), with an up-to-date description of the problem you're facing. Be sure to add a stack trace and a repository with a reproduction.
