### ISSUE TITLE
Dropdown menu inside navbar

### ISSUE THREAD

**Issue by sergeylaptev** [wix/react-native-navigation#2366]
### Issue Description

Hello! How can I implement dropdown menu inside navbar with this library?:)

![image](https://user-images.githubusercontent.com/5740795/34079626-58a92524-e342-11e7-816d-58f1d67ae846.png)

---
### Environment
* React Native Navigation version: 1.1.311
* React Native version: 0.50
* Platform(s) (iOS, Android, or both?): Both

**Comment by pqkluan** [comment]
Check out the [Android context document](https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=contextual-topbar-menu-android-only).

If that doesn't suit you, then there is no available out-of-the-box solution for your issue. You have to create your very own context component using react-native Modal component.

**Comment by pqkluan** [comment]
I'll close this issue for now assuming the original problem resolved.
