### ISSUE TITLE
Back button inside custom navbar component

### ISSUE THREAD

**Issue by sergeylaptev** [wix/react-native-navigation#2367]
### Issue Description

Is there way to implement fully functional navbar component based on current stack (to show back button), and be able to toggle drawer. Show screen's title based on props etc. 

There is no info about stack, screen title etc. Which is pretty strange in common, what's the purpose of custom navbar in this case?

Custom navbar props:
![image](https://user-images.githubusercontent.com/5740795/34080368-92f8bd9c-e34d-11e7-9f1c-a385695cdb9e.png)

Screen component props:
![image](https://user-images.githubusercontent.com/5740795/34080217-9e30f712-e34b-11e7-96aa-c1009a438c98.png)

---
### Environment
* React Native Navigation version: 1.1.311
* React Native version: 0.50
* Platform(s) (iOS, Android, or both?): Doesn't matter
* Device info (Simulator/Device? OS version? Debug/Release?): Doesn't matter

**Comment by pqkluan** [comment]
You have to set the custom navbar and its props after the Screen Component is created.

```jsx
this.props.navigator.setStyle({
  navBarCustomView: 'example.CustomTopBar',
  navBarCustomViewInitialProps: { navigator = this.props.navigator }
});
```
