### ISSUE TITLE
Android styling text color of navigation buttons

### ISSUE THREAD

**Issue by adurandet** [wix/react-native-navigation#2368]
### Issue Description

I am trying to customise the color of the text of one of my navigation button (right one).

It was working fine lately using: `navBarButtonColor: colors.primary,`

but it seems that now the text is black and there is no way to change it.

The strangest thing is it is working on a emulator but not on real device.
(It is working well on iOS too).

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.295
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): real device ( nexus5, nexus 5x, samsung s8, etc...)

**Comment by nprz** [comment]
I am also having this issue. Android is completely unresponsive to the `buttonColor` prop. I am not sure how I am supposed to change the color of a text button.

**Comment by vgeorge** [comment]
Are you using the latest version of RNN? I had the same problem and after I upgraded to v1.1.398 the color setting worked again.
