### ISSUE TITLE
YellowBox being added to all registered components

### ISSUE THREAD

**Issue by brunolemos** [wix/react-native-navigation#2371]
### Issue Description

The react native warning box is expected to be added only in the root view, but seems to be added on all components registered with `registerComponent`.

### Steps to Reproduce / Code Snippets / Screenshots

- Use `registerComponent` for screens and navbar buttons
- `startTabBasedApp`
- `leftButtons: [{ component: 'mycomponentidhere' }]`

<img alt="Screenshot" height="500" src="https://user-images.githubusercontent.com/619186/34112418-a5137250-e3f3-11e7-9e8f-b873a2b52fb2.png" />

---
### Environment
* React Native Navigation version: ^1.1.311
* React Native version: ^0.51.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X Simulator (iOS 11.2)

**Comment by campierce88** [comment]
This is happening for me as well... any Idea how to prevent this?

**Comment by brunolemos** [comment]
Similar thing with Inspect tool:

<img width="416" alt="screenshot" src="https://user-images.githubusercontent.com/619186/36614294-e6ef34e2-18ba-11e8-9f05-c64f6f7ee11d.png">

**Comment by guyca** [comment]
Not sure this is an issue... it's just how RN is implemented.
RN assumes an app as a single ReactRootView, so the yellow boxes are added to each root view. 🤷‍♂️
