### ISSUE TITLE
[Android] tab icon bouncing

### ISSUE THREAD

**Issue by barbarossusuz** [wix/react-native-navigation#2372]
### Issue Description

I added label on tab icons but when i click tab icons they are bouncing (without label they do not). Is there any way to prevent this, i searched it but i could not find

### Steps to Reproduce / Code Snippets / Screenshots
![untitled](https://user-images.githubusercontent.com/21311371/34112585-15d43f86-e41e-11e7-903b-9d07e28f9096.gif)

---
### Environment
* React Native Navigation version: ^1.1.309
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Genymotion galaxy s7

**Comment by guyca** [comment]
This is a feature of AHBottomNavigation which we can't control.
