### ISSUE TITLE
ReactRootView height should not be affected when animating TopBar

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#2378]
When toggling TopBar, don't change content view height. Instead, the user should take care of positioning himself so that blank spaces won't be visible when animating TopBar.

**Comment by Cool04ek** [comment]
RootView height is not animated now in #2413 PR. No we have `drawUnder` property for TopBar. So if user wants a smooth behavior he draws content under the TopBar and then it can be hidden or collapsed smoothly.
