### ISSUE TITLE
[Feature request for iOS] Porting the iOS navigation into Swift

### ISSUE THREAD

**Issue by dzunglht** [wix/react-native-navigation#2392]
Dear team,
Although that Swift is not a stable language at the moment but the community has been increasing in recent years, we need more resource to maintain this great library and also reinforce your contributions to open source communities.
Best regards,

**Comment by smusa** [comment]
Second the Swift porting because of need to build react-native app using Swift for iOS and Kotlin for Android.

**Comment by birkir** [comment]
Until the React Core has been rewritten in Swift this is not a viable option. See what happened with airbnb's native navigation.

**Comment by smusa** [comment]
Thanks for clarifying. When I went on to check state of affairs with native navigation i realized the same.
