### ISSUE TITLE
v2 fails to run with debug js mode on

### ISSUE THREAD

**Issue by anonrig** [wix/react-native-navigation#2393]
Hello,

I'm using react-native 0.51.0 with react-native-navigation@alpha. When debug js mode is enabled, I'm seeing this error and the app doesn't work at all.

```
Sending `RNN.appLaunched` with no listeners registered.
```

**Comment by guyca** [comment]
Hey @anonrig 
Thanks for reporting, on which platform?

**Comment by anonrig** [comment]
@guyca it's occurring on iOS platform

**Comment by yogevbd** [comment]
@anonrig Can you please try to reproduce on latest version? It is working good for me.
