### ISSUE TITLE
Android: Navigation bar interferes with TextInput focus when soft keyboard shows up

### ISSUE THREAD

**Issue by Agontuk** [wix/react-native-navigation#2402]
### Issue Description

I have a TextInput at the bottom of a ScrollView. When I focus the input, keyboard shows up and resize the layout, but fails to push the input right above the keyboard. When I set `navBarHidden: true`, this doesn't happen, so it seems keyboard is not considering the TitleBar height when it pushes the layout up.  I'm using `softInputMode adjustResize`.

### Demo
![focus_bug](https://user-images.githubusercontent.com/5656440/34320543-be8334fa-e826-11e7-8cf0-d915bc98c59f.gif)

---
### Environment
* React Native Navigation version: 1.1.311
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): 5.1 (emulator) / 7.1 (Xiaomi Redmi Note 3)

**Comment by Agontuk** [comment]
@guyca

**Comment by Agontuk** [comment]
As a workaround, I set the `drawUnderNavBar: true` on android, and then applied a `marginTop` equal to the navbar height on android. It works, but it would be better to have a fix for this.

**Comment by solodream** [comment]
+1
it took me hours to find the problem. @Agontuk 's fix works for me.
