### ISSUE TITLE
TopTabs options

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#2405]
**Android**
- [x] font family
- [x] font color
- [ ] font size (requires custom tab view)
- [ ] badge (requires custom tab view)
- [ ] font weight ?
- [ ] selected tab indicator color
- [ ] selected tab indicator size
- [ ] scrollable
- [ ] Tabs only with icons

**Comment by muhammedyasirmt** [comment]
topTabs titile is not displayed
