### ISSUE TITLE
Codepush installation

### ISSUE THREAD

**Issue by SimchaShats** [wix/react-native-navigation#241]
Hi, is there any way to use Microsoft Codepush plugin with navigation on android after react-native version 0.29: https://github.com/Microsoft/react-native-code-push

**Comment by SimchaShats** [comment]
Ah sorry, found solution need to add next lines to `NavigationReactGateway.java` to the function `createReactInstanceManager()`

`for (ReactPackage reactPackage : createReactPackages()) {
            builder.addPackage(reactPackage);
        }

        String jsBundleFile = CodePush.getJSBundleFile();
        if (jsBundleFile != null) {
            builder.setJSBundleFile(jsBundleFile);
        } else {
            builder.setBundleAssetName(Assertions.assertNotNull(NavigationApplication.instance.getBundleAssetName()));
        }`

**Comment by DanielZlotin** [comment]
This is implemented in the upgrade to RN 0.31

**Comment by monder** [comment]
@DanielZlotin  Could you please point me to the place where I can customize bundle location without modifying 'react-native-navigation' subproject.

**Comment by DanielZlotin** [comment]
@monder working on exposing it. Will be ready today.

**Comment by DanielZlotin** [comment]
Done, published in 2.0.0-experimental.106.
Please see https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java#L65 and tell me if that's enough

**Comment by monder** [comment]
Awesome. Thanks.

**Comment by agumack** [comment]
@DanielZlotin 
I have a error after upgrade .106

```
node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java:75: error: method onActivityResult in class ReactInstanceManager cannot be applied to given types;
        getReactInstanceManager().onActivityResult(requestCode, resultCode, data);
                                 ^
  required: Activity,int,int,Intent
  found: int,int,Intent
  reason: actual and formal argument lists differ in length
```

please help!

**Comment by monder** [comment]
I think its not related to `react-native-navigator`, but to a `react-native` itself.
The signature was changed in [v0.33.0](https://github.com/facebook/react-native/commit/fbd2e139103e3d520f6dfc009d6200f8b8168e35), and as I understand `react-native-navigator` is not compatible with anything v0.31.+.

**Comment by agumack** [comment]
yep @monder 
I downgrade react-native .031 that error resolved (y)
But have one other error: 

`java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.phonewindow$decorview not attached to window manager`

**Comment by monder** [comment]
Isn't that the error that happens when Android Studio tries to patch the application without killing it? Could you please try to uninstall/kill the previous app version on the device/emulator. Or maybe remove the app data.

**Comment by agumack** [comment]
on device i tried: 
Setting => Installed apps =>"MyApp" => Clear data, Clear cache => Uninstall

But don't understand after run react-native run-android => the previous app version installed 😢 
I reload js again and appear this error . :s :s
