### ISSUE TITLE
Specify the default selected TopTabs

### ISSUE THREAD

**Issue by ahmedfouad2016** [wix/react-native-navigation#2421]
### Issue Description
Is there a way to Specify the default selected TopTabs ?
i use this.props.navigator.switchToTopTab but i want by default the screen opening on specific top tab 

---
### Environment
* React Native Navigation version: 1.1.314
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device & Simulator Debug

**Comment by syedabuthahirm** [comment]
Did you find a solution for this issue?
