### ISSUE TITLE
Homogenous layouts api

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#2426]
In order to support truly homogenous layouts, a few changes need to be made to the layout api

- [x] Redesign layout API
- [x] Rename `container` to `component` - a leaf in the hierarchy
- [x] Declare `stack` node explicitly
- [x] implement StackLayout on Android #2425
- [x] A `stack` can be initialized with more then one screen [example](https://gist.github.com/guyca/c3046e9602176244c6aafb6761b93a88#file-newlayouts-js-L7)
- [x] Rename `navigationOptions` to `options`

cc @yogevbd @Cool04ek @bogobogo

**Comment by DanielZlotin** [comment]
js side - done. 
please make sure android e2e all green and implement StackLayout, Stack initialized with multiple screens

**Comment by guyca** [comment]
@yogevbd Please add e2e to iOS as well 👍
