### ISSUE TITLE
[iOS]Screen API should only affect current screen

### ISSUE THREAD

**Issue by littlesome** [wix/react-native-navigation#243]
hi, I find a bug,
On iOS, setTitle and setButtons called from screen A may affects screen B

setTitle and setButtons may be triggered by some events asynchronously, and user may just pop screen using  gesture, there's no way to detect this currently (componentWillUnmount is too late) 

```
//On iOS setTitle is a navigator level API
function navigatorSetTitle(navigator, params) {
  Controllers.NavigationControllerIOS(navigator.navigatorID).setTitle({
    title: params.title
  });
}


//On Android, setTitle is screen level API
function navigatorSetTitle(navigator, params) {
  newPlatformSpecific.setScreenTitleBarTitle(navigator.screenInstanceID, params.title);
}
```

**Comment by himanshusoni** [comment]
If you look at the below snippet in `RCCNavigationController.m`, we need to verify that the request updates the screenID with requested the title update. i.e. only if screenID for topViewController and the requesting screen are same. 
`line 185`
```objective-c
  // setTitle
  if ([performAction isEqualToString:@"setTitle"] || [performAction isEqualToString:@"setTitleImage"])
  {
    NSDictionary *navigatorStyle = actionParams[@"style"];
    [self processTitleView:self.topViewController
                     props:actionParams
                     style:navigatorStyle];
    return;
  }
```

**Comment by alexcurtis** [comment]
It would be great if this was on the todo list.
I currently need to async update the title when its off-screen (in the stack), but if I call navigator.setTitle within that view, it updates the view that is currently visible (on the top of the stack).

**Comment by guyca** [comment]
@alexcurtis On what platform are you seeing this issue?

**Comment by alexcurtis** [comment]
@guyca iOS 10. Latest react-native-navigation

**Comment by guyca** [comment]
Yes, we fixed that on Android already and it will be fixed on iOS as well pretty soon. Can't guarantee exactly when since It's the jewish holidays now, and we're based in Israel... most of the team is on vacation :)

**Comment by alexcurtis** [comment]
@guyca awesome, thank you! :)

**Comment by noradaiko** [comment]
any progress?

**Comment by dcgoss** [comment]
Is there:
A) Any progress on this issue?
B) If not A, any suggestions on where we can start fixing this ourselves to make a PR?

**Comment by DanielZlotin** [comment]
You can follow the v2.0.0 progress in this [branch](
https://github.com/wix/react-native-navigation/tree/v2?files=1), we'll
solve this bug after the release

**Comment by dcgoss** [comment]
@DanielZlotin I'm struggling to find the setButtons and setTitle methods in the v2 branch - are they there?

**Comment by DanielZlotin** [comment]
Not yet

**Comment by guyca** [comment]
@dcgoss Is a temp workaround, you can detect when a [screen is visible or not](https://github.com/wix/react-native-navigation/wiki/Screen-API#screen-visibility) and call `setTitle` only when the screen is visible

**Comment by noradaiko** [comment]
@guyca cool!

**Comment by doertli** [comment]
this is an annoying bug -- any chance it'll be solved in Wix Nav v1, given v2 isn't happening anytime soon?
