### ISSUE TITLE
Toggle drawer is not working with tab based app in release apk.

### ISSUE THREAD

**Issue by kishanj918** [wix/react-native-navigation#2430]
### Issue Description
 I am trying to toggle drawer on button press in tab based app. It's working when i run app via react-native run-android but it's not working in release apk.

---
### Environment
* React Native Navigation version: 1.1.316
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Device? Android? Release?)

**Comment by Yuri-Tiofilo** [comment]
The same problem is happening to me.

React Native Navigation version: 4.0.3
react Native version: 0.61.4

**Comment by parmarravi** [comment]
any solution?
