### ISSUE TITLE
White screen without icon

### ISSUE THREAD

**Issue by juanamd** [wix/react-native-navigation#2442]
This is just a heads up for anyone experiencing the same as I did:

If you can't get this lib to work correctly because it only shows a white screen with no errors or messages (can't even reload the environment without recompiling) then you are just probably missing the tabs icon.
Yes, if you don't actually include an image to the "icon" property of the tab, then it will just simply display a white screen with no information whatsoever that it is in any way related to that.

**Comment by mehdijjz** [comment]
Wow!

**Comment by MatheoJaouen** [comment]
Wow! Got trapped too! @juanamd thanks!

**Comment by sbaden** [comment]
I'm a bit new at this. Could you please explain how to add the icon that you're referring to?
