### ISSUE TITLE
iOS (1.1.323) three dots in navbar title

### ISSUE THREAD

**Issue by jurajkrivda** [wix/react-native-navigation#2444]
Hi. I have Tabbar app with 5 tabs. In some tabs I see title with three dots in the end of the title. For example. Is this bug?

**Comment by aspidvip** [comment]
![ex1](https://user-images.githubusercontent.com/22605655/34454021-4708c2b4-edad-11e7-80f7-be94457d1985.jpeg)
me to

**Comment by guyca** [comment]
Might be related to #2443

**Comment by khsily** [comment]
adding empty space will solve the problem.
title: 'HOME' --> title: ' HOME '

**Comment by jurajkrivda** [comment]
@khsily I tried this but it does not work in the latest version of the navigation

**Comment by gargsms** [comment]
@guyca I can confirm that #2443 indeed fixes the issue.

**Comment by yogevbd** [comment]
#2443 indeed fixes the issue and pushed to master.
