### ISSUE TITLE
'React/RCTRootView.h' file not found after detaching from Expo

### ISSUE THREAD

**Issue by James2516** [wix/react-native-navigation#2448]
### Issue Description

I created a new project with [expo](https://github.com/expo/expo) and detached it.

When I try to run the iOS project in XCode, it gives an error
>'React/RCTRootView.h' file not found

If I create a new project with `react-native init` instead, I'm able to build with `react-native-navigation` successfully. Why does it fail with expo?

### Steps to Reproduce / Code Snippets / Screenshots

https://github.com/James2516/expo-native-nav
Run `npm install` and try building the iOS project in Xcode.

Or start a new project:
1. `exp init`
2. `exp detach`
3. `yarn add react-native-navigation`
4. `react-native-link`
5. `cd ios && pod install`

I have tried adding React to build target ![](https://i.imgur.com/OCQ30Tj.png)

---
### Environment
* React Native Navigation version: ^1.1.323
* React Native version: expo sdk 24 / 0.51
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Failed at XCode build

**Comment by quy1403** [comment]
you can not use wix rnn on expo. please react-native init!

**Comment by James2516** [comment]
@quy1403 I need to use some expo libraries. You can use native libraries with Expo after detaching. See https://docs.expo.io/versions/latest/guides/detach.html

**Comment by James2516** [comment]
still not resolved...

**Comment by EgidioCaprino** [comment]
Hi @James2516 

Did you eventually fixed this? If yes, how?

**Comment by James2516** [comment]
Didn't manage to fix it, so ended up not using this library.
