### ISSUE TITLE
Integration with redux

### ISSUE THREAD

**Issue by James2516** [wix/react-native-navigation#2450]
### Issue Description
There's no documentation on how to integrate the API with redux.

Use case:
I want the last visited scene to be restored when the user restarts the app. 

It seems like this is not possible since the entire stack of routes before the current route and their respective component's states have to be stored?

**Comment by christopherread** [comment]
There's a link under /examples, but it returns a 404

You may find this blog post useful
https://medium.com/react-native-training/explanation-of-react-native-navigation-wix-with-redux-deabcee8edfc

**Comment by guyca** [comment]
Thanks for sharing this post @christopherread, I'll add it to the docs

**Comment by James2516** [comment]
In other words, we have to manually dispatch updates to the redux store whenever `this.props.navigator.push` to keep track of the current route? This would still only work if we are directing the user to a root stack route.

**Comment by nazrdogan** [comment]
@James2516  I  had  same problem with you.  I make little hack for navigation. I don't know very well react-native-navigation but its works well. you can dispatch action everywhere.

https://github.com/nazrdogan/react-native-navigation-redux
