### ISSUE TITLE
[HOC] How can I pass navigator props to HOC?

### ISSUE THREAD

**Issue by dbyilmaz** [wix/react-native-navigation#2457]
I want to pass parameters to hoc. I saw that react-navigation method `withNavigation`.  Is there available like this method on react-native-navigation? Or how can I do this method?

**Comment by guyca** [comment]
Please continue discussion in [SO](https://stackoverflow.com/questions/48057938/how-can-i-pass-navigator-props-to-hoc)

**Comment by JulesPatry** [comment]
I would love to have this. Please implement this!
