### ISSUE TITLE
registerComponent why generator instead of function?

### ISSUE THREAD

**Issue by James2516** [wix/react-native-navigation#2458]
`Navigation.registerComponent('example.FirstTabScreen', () => FirstTabScreen);`
Why does the generator parameter takes in a higher order function (a function that returns a function)? 

`Navigation.registerComponent('example.FirstTabScreen', FirstTabScreen);`
Wouldn't this method signature simplify things a bit?

**Comment by guyca** [comment]
Generator pattern allows for more flexibility, and provides more power to the user (you). For example, with a generator you can defer calls to require.
`Navigation.registerComponent('example.FirstTabScreen', () => require('FirstTabScreen'));`
