### ISSUE TITLE
Will the root component be accessible in v2?

### ISSUE THREAD

**Issue by JesseTheDev** [wix/react-native-navigation#2459]
So there are a lot of reasons to really like this package, namely that it feels very native and that it's easy to use once it's all set up.

The main thing I have against this package is that I can't access the root component for implementing things like `react-native-branch` and other globalized packages that require 1) a function to be run every time the app opens and 2) access to the navigator object in said function.

I'm curious if, in v2, we'll be able to access the the root component to implement `componentWillMount()` and such or if we'll still be stuck with the very basic version of the root component shown in the docs (and below) where only the constructor is available.

````
import React from 'react';
import run from 'app/app';

class Root extends React.Component {
    constructor(props) {
        super(props);
        run(); // calls Navigation.startTabBasedApp()
    }

    componentWillMount() {
        // doesn't run
    }
}

export default Root;
````

**Comment by guyca** [comment]
Hey there, RNN doesn't have a root component.
Each screen is a component which is managed by the native navigation stack.
Perhaps what you're looking for a [AppState](https://facebook.github.io/react-native/docs/appstate.html) or wrapping your screens in a HOC?

**Comment by lanetteammonika** [comment]
@guyca , I want to wrap all screen in single HOC, as I need to access AppState in my App.

**Comment by jslz** [comment]
€0.02 I think I agree with OP, there can sometimes be UI widgets that are cross-cutting in the whole app, that are effectively globals. It would be nice to be able to wrap the top level / root view of the app once vs. having every screen wrapped. The former is easier to deal with when the widget has to be the same across the app e.g. dismiss on one screen and then it is therefore gone from all other screens.

**Comment by fmoessle** [comment]
Yes, [native-base](https://docs.nativebase.io/) requires something like that for Toasts etc.
