### ISSUE TITLE
LightBox fade-in animation not working

### ISSUE THREAD

**Issue by drorbiran** [wix/react-native-navigation#246]
> This issue was originally opened in [react-native-controllers](https://github.com/wix/react-native-controllers/issues/61)

I see there is intention in the code to animate the alpha for the lightbox so that it fades in. However on calling the lightbox, if I have e.g.

``` js
      style: {
        backgroundBlur: "none",
        backgroundColor: "#888888DD"
      }
```

then the background instantly turns grey with transparency, and on dismiss it fades back nicely.

It would be great to have the background fade in also.

**Comment by guyca** [comment]
Not relevant anymore
