### ISSUE TITLE
How to use in a native project using RN for part of features?

### ISSUE THREAD

**Issue by LiuYibin** [wix/react-native-navigation#2463]
### Issue Description

Your docs and demos are all about using your navigation in an all-RN project. Do you have any docs which represent the steps about how to use it in a project which use RN for  a part features? For example, when a native viewController pushing an RN viewController, how should I use and config your navigation in my code?

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.328
* React Native version: 0.44.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
Hey @LiuYibin 
RNN only support green field apps. If you're interested in integrating RN with an existing native app, You don't need this library as RNN aims to provide a complete navigation solution, while you only need to bootstrap Js and show a few React Native screens (Views)
