### ISSUE TITLE
dismissAllModals dont dismiss all modals

### ISSUE THREAD

**Issue by tkulpa** [wix/react-native-navigation#2465]
### Steps to Reproduce / Code Snippets / Screenshots
Use dismissAllModals, only one modal will be dismissed (The newest one)

---
### Environment
* React Native Navigation version: 1.1.188
* React Native version: 0.49.5
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): One Plus 5

**Comment by guyca** [comment]
I believe this bug was fixed in a recent version.. try updating RNN latest version

**Comment by tkulpa** [comment]
I did and now on version 1.1.329 it still happens

**Comment by karlmosenbacher** [comment]
I have similar issue when trying to dismissAllModals. I am using version 1.1.390.
