### ISSUE TITLE
"  Application has not been resisted  "

### ISSUE THREAD

**Issue by farooq029** [wix/react-native-navigation#2468]
![n2](https://user-images.githubusercontent.com/34084867/34535604-4adf73c0-f077-11e7-9e2e-f1ec648002d1.JPG)
i am facing this issue 
screenshot attached of project structure 
i have write this code for  index.android.js

import React, { Component } from 'react';
import {
  AppRegistry,
![nnnn](https://user-images.githubusercontent.com/34084867/34535463-b73f73a4-f076-11e7-9178-314a73c7025a.JPG)

  StyleSheet,
  Text,
  View
} from 'react-native';

export default class UIExplorer extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('UIExplorer', () => UIExplorer);

**Comment by dbyilmaz** [comment]
Has a different application been installed on the emulator before? Also, you must write other parts of the code.

**Comment by guyca** [comment]
Hey, Please follow the getting started guides in the docs.
In RNN, you don't register components using AppRegistry directly... I'm wondering what else you've missed when setting up your project.

**Comment by dbyilmaz** [comment]
@guyca how to listen back button(left buttons) on the navbar?

**Comment by farooq029** [comment]
@dbyilmaz only one APP is running on emulator ..Other parts means ?
