### ISSUE TITLE
Navigation.showModal and showLightBox crash on release when the screen has scrollView or flatlist in it. 

### ISSUE THREAD

**Issue by erfanyousefifar** [wix/react-native-navigation#2469]
### Issue Description

Navigation.showModal and showLightBox crash on release when the screen have scrollView or flatlist in
it. 
### Steps to Reproduce / Code Snippets / Screenshots
i use mobx and mobx-react to manage states, i don't think it's related. 
when I try to showModal this screen from a pushed screen, if I use scrollView, the app crash.
it works fine in debug but crash in release, i found this error on logcat
Calling JS function after bridge has been destroyed
`@observer export default class PlaceSearch extends React.Component {
    render() {
        return (
            <View style={{flex : 1, backgroundColor : 'white'}}>
                //<ScrollView style={{flex : 1}}> if you put this screen will crash
                <Text>this is a Text</Text>
                <Text>this is a Text</Text>
                <Text>this is a Text</Text>
                <Text>this is a Text</Text>
                <Text>this is a Text</Text>
                <Text>this is a Text</Text>
                <Text>this is a Text</Text> 
               // </ScrollView>
            </View>
        )
    }
}`
---
### Environment
* React Native Navigation version: 1.1.331
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device 7.1.2 Release

**Comment by guyca** [comment]
Please investigate further, if you can confirm this crash is related to RNN please reopen with more information.

**Comment by erfanyousefifar** [comment]
I just downgraded react native to 0.49.5 and everything works as expected!!!!!
