### ISSUE TITLE
Modal.showController shows component multiple times

### ISSUE THREAD

**Issue by drorbiran** [wix/react-native-navigation#247]
> This issue was originally opened in [react-native-controllers](https://github.com/wix/react-native-controllers/issues/64)

react-native-controllers v2.0.2

In one of my components, I have the following code

```js
_stateChange (val) {
  if (val === 'inactive') {
    Modal.showController('myapp.Controller.Locked', 'slide-up');
  }
}

componentDidMount () {
  AppState.addEventListener('change', this._stateChange);
}
```

Everytime the AppSate is `inactive`, the modal gets shown even if the `myapp.Controller.Locked` is already showing on screen.

Maybe the `Controllers` could keep track of the shown component and not show it again?

```js
// var _currentModal;

showController: function(appKey, animationType = 'slide-up', passProps = {}) {
  var controller = _controllerRegistry[appKey];
  if (controller === undefined) return;

  if (_currentModal === appKey) return;
  _currentModal = appKey;

  var layout = controller.render();
  _validateDrawerProps(layout);
  RCCManager.showController(layout, animationType, passProps);
}
```

**Comment by DanielZlotin** [comment]
This looks like a simple local state you need to keep in your app, ie a boolean flag or a registry. I don't see how it's Navigation's responsibility. I don't mind providing an api for something like `isScreenShowning()`, you can open a feature request issue if you want.
