### ISSUE TITLE
Applying margin to all screens in startSingleScreenApp

### ISSUE THREAD

**Issue by James2516** [wix/react-native-navigation#2470]
RE https://github.com/wix/react-native-navigation/issues/2461

`appStyle` is not a property of https://wix.github.io/react-native-navigation/#/top-level-api?id=startsinglescreenappparams
When i set 
```
appStyle: {
   marginTop: 100,
   marginBottom: 100,
}
```
It doesn't seem to have any effect.

**Comment by guyca** [comment]
marginTop and marginBottom are not supported style properties of appStyle. Generally, appStyle supports navigatorStyle properties which are not related to react style properties.

**Comment by James2516** [comment]
So is there a way to apply common margins to all screens?
