### ISSUE TITLE
navigatorStyle not passed from startSingleScreenApp

### ISSUE THREAD

**Issue by James2516** [wix/react-native-navigation#2471]
### Issue Description

My `startSingleScreenApp` contains `navigatorStyle` property, but when I do a `props.navigator.showModal` from the screen in `startSingleScreenApp`, the modal screen's navigator does not have the same style unless i duplicate the `navigatorStyle` property.
### Steps to Reproduce / Code Snippets / Screenshots
See above

### Environment
* React Native Navigation version: 1.1.315
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug iOS 11.1

**Comment by guyca** [comment]
`navigatorStyle` isn't a property of `startSingleScreenApp`
