### ISSUE TITLE
[Android ] Collapsing Header doesn't work well

### ISSUE THREAD

**Issue by elyonsaber** [wix/react-native-navigation#2477]
I tried the demo on Android phone, and found that the collapsing header seems to have a problem.

![screenshot_20180105-110927](https://user-images.githubusercontent.com/15250710/34594308-28634aa2-f20b-11e7-9fa3-f8dcd75ea498.png)

Just as the screenshot shown,  the scrollview doesn't always fill the viewport, because it also goes up when I try to hide the header.

**Comment by guyca** [comment]
@elyonsaber This api is unmaintained as we're focusing on v2. There are a few performant alternatives to creating collapsing headers on RN which you can try, here's on for example https://medium.com/appandflow/react-native-collapsible-navbar-e51a049b560a

**Comment by elyonsaber** [comment]
Great thanks!
