### ISSUE TITLE
Could not find method testImplementation()

### ISSUE THREAD

**Issue by anilgurindapalli** [wix/react-native-navigation#2478]
**FAILURE: Build failed with an exception.**

I'm using V2.. Build is getting failed.. Could be please provide the solution for the issue. I have followed all the installation steps given in the documentation. But facing the issue.

Check out #2354 but still didn't solved.

**ScreenShot**

![error](https://user-images.githubusercontent.com/30103626/34597030-2fbd7288-f20a-11e7-8d87-613484d082a6.jpg)

---
### Environment
* React Native Navigation version: ^2.0.2072
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device / 6.0 / Debug

**Comment by redwind** [comment]
i face same problem,anyone has update for this issue ?

**Comment by oakis** [comment]
I have the same issue...

**Comment by ebouJ** [comment]
+1

**Comment by guyca** [comment]
testImplementation was introduced in gradle 3.x - as @redwind mentioned you need to upgrade your projects gradle version.

**Comment by vitto-moz** [comment]
I've decided to move to react-native-navigation v2 but several packages still need gradle 2.
Any solution here - can I use RNN v2 with gradle 2?
