### ISSUE TITLE
Styling Tab Bar - tint overrides background color

### ISSUE THREAD

**Issue by drorbiran** [wix/react-native-navigation#248]
> This issue was originally opened in [react-native-controllers](https://github.com/wix/react-native-controllers/issues/76)

Have I missed something, or is the iOS tint effect overriding the value entered for "tabBarBackgroundColor"?
# cc0000 is rendered as #bf1212
# ffffff is rendered as #ebebeb

Trying to set the background to absolute white, but always rendering grey.

**Comment by savelichalex** [comment]
Hm, I think this is happened by apply UIVisualEffect under tab bar. I'm disable it in my app 😄

**Comment by yourcontainer** [comment]
@savelichalex how you disabled? using xcode?

**Comment by hackable** [comment]
How did you solve this issue

**Comment by mobinni** [comment]
@hackable what exactly is the fix? A bit more context would be appreciated

**Comment by vladislavoff1** [comment]
@mobinni try to add `tabBarTranslucent: false` to `tabsStyle` like this
```
  Navigation.startTabBasedApp({
    tabs,
    tabsStyle: {
      tabBarBackgroundColor: '#000',
      tabBarTranslucent: false,
    },
  })
```
