### ISSUE TITLE
Navigation Tabs FlatList incorrect display onRefresh

### ISSUE THREAD

**Issue by aspidvip** [wix/react-native-navigation#2484]
Hello
* React Native Navigation version: 1.1.334
* React Native version: 0.49.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device ?): Simulator/Device 
Debug/Release

`<FlatList`
        data = {this.state.data}
        renderItem={this._renerRowList.bind(this)}
        keyExtractor={this._keyExtractor}
        onRefresh={this.handleRefresh}
        refreshing={this.state.refreshing}
       />
`

![ex](https://user-images.githubusercontent.com/22605655/34646704-aa01d53c-f3ba-11e7-8024-ff3f2a4fb017.gif)

**Comment by pqkluan** [comment]
The issue description is vague and this is more related to your Flatlist implement that RNN.

If you think the issue truly cause by RNN, feel free to re-open.
