### ISSUE TITLE
toggleDrawer is not working 

### ISSUE THREAD

**Issue by ishraqe** [wix/react-native-navigation#2485]
It was working fine. I haven't changed the code but suddenly it stopped working. 

Clicking on the navbar button the drawer is not opening. Here is code i have used for button press

```
if (event.type === 'NavBarButtonPress') {
        if (event.id === 'sideDrawerToggle') {
            this.props.navigator.toggleDrawer({
                side: 'left',
                animated: true,
            });
        }
    }

```
Here is the drawer set up

```
Navigation.startTabBasedApp({
        tabs: [
            {
                label: 'Find Place',
                screen: 'places.FindPlace',
                title: 'Find Place', 
                icon: source[0],
                navigatorButtons: {
                    leftButtons: [
                        {
                            icon : source[2],
                            title : 'Menu',
                            id: 'sideDrawerToggle'
                        }
                    ]
                }
            },
            {
                label: 'Share Place', 
                screen: 'places.SharePlace', 
                title: 'Share Place', 
                icon: source[1],
                navigatorButtons: {
                    leftButtons: [
                        {
                            icon: source[2],
                            title: 'Menu',
                            id: 'sideDrawerToggle'
                        }
                    ]
                }
            }
        ],
        drawer: {
            left: { 
                screen: 'places.SideDrawer'
            }
        }
    });
```

And this is what my drawer looks like
```
 import React, {Component} from 'react';
import {View, Text, Dimensions} from 'react-native';


class SideDrawer extends Component {
    render() {
        return(
            <View style={[
                styles.container,
                {width: Dimensions.get('window').width * 0.8}
            ]}>
                <Text>Drawer</Text>
            </View>
        );
    }
}

const styles = {
    container: {
        backgroundColor : 'white',
        paddingTop: 22,
        flex: 1
    }
};


export default SideDrawer;
```

By searching a lot i found that giving a fixed width to drawer solves the problem. But its not solving in my case. I don't know what is wrong with the code, It was working fine.

---
### Environment
* React Native Navigation version: ^1.1.328
* React Native version:0.51.0
* Platform(s): Android

**Comment by aspidvip** [comment]
me to

**Comment by dre4success** [comment]
same problem here. Please, if you do find a solution, kindly let us know

**Comment by dre4success** [comment]
Just downgraded React Native to version: 0.49.5 and it worked

**Comment by aspidvip** [comment]
React Native 0.49.5 problem toggleDrawer is not working

**Comment by DazChong** [comment]
Have the same experience either, as it turned out I found that using `this.props.navigator` is not available outside of `constructor(props)` or `render()`, and cannot be bind to class variable either.

So instead of calling `this.props.navigator.toggleDrawer()` in functions. You need to either use it within component or passing the `this.props.navigator` into function.

Example 1 (Not working): 
```js
export default class HomeScreen extends Component<{}> {

  function showLeftMenu() {
    // this.props.navigator undefined
    this.props.navigator.toggleDrawer({
      side: 'left'
    })
  }
}
```

Example 2 (Working):
```js
<TouchableOpacity
  onPress={() => {
    this.props.navigator.toggleDrawer({
      side: 'left'
    })
  }}
>
  Button
</TouchableOpacity>
```

Example 3 (Working, passing navigator into function):
```js

showLeftMenu(navigator) {
  navigator.toggleDrawer({
    side: 'left'
  })
}

render() {
  return(
    <TouchableOpacity
      onPress={() => this. showLeftMenu(this.props.navigator)}
    >
      Button
    </TouchableOpacity>
  )
}
```

**Comment by cpilson** [comment]
`"react-native": "0.51.0"` here, running under `"react-native-navigation": "1.1.330"`.

With the following setup
```js
import { Navigation } from "react-native-navigation";
// some lines later...
Navigation.startSingleScreenApp({
        screen: {
          screen: "app.ProfileScreen",
          title: "-------",
          navigatorStyle: navigatorStyle,
          leftButtons: [{ id: "sideMenu" }]
        },
        drawer: {
          left: {
            screen: "app.UserDrawer"
          }
        }
      });
```

and all screens and drawers registered via `Navigation.registerComponent()`, I have a slightly more nuanced and troubling issue: **the side menu _occasionally_ won't respond to a click of the hamburger-menu button.** When it gets like this, there's nothing in the (redux) logger, nothing in logs, nothing I can really do outside of halt the app and re-launch. And occasionally I'll have to do so five or six times before the hamburger menu button decides to work.

While in this mode of operation, toggling the Android debugging inspector and showing touchables gives a red-screen error. I think it's saying that the hamburger menu can't be clicked.

When I physically click the menu button, however, it makes the "click" sound accordingly, so the touch is being registered at some level.

Has anyone else had this issue? It is exceedingly nerve-wracking when trying to demo Shiny New App and never know if you'll have to go through multiple rounds of "wait, let me just close this ... erm ..." and "ah, that didn't work, hold on a moment..."

Platform: Android Nougat.

**Comment by aspidvip** [comment]
![error](https://user-images.githubusercontent.com/22605655/34819891-c181e47e-f70a-11e7-98f4-58dd412cb1c5.gif)

**Comment by guyca** [comment]
@aspidvip Can you please try version 1.1.336 ?
I pushed changes which I hope will resolve these issues

**Comment by aspidvip** [comment]
problem still exists

**Comment by skipsuva** [comment]
I bumped my version to 1.1.336 and its working again for android (although some styles got messed up).  Thanks @guyca !

**Comment by guyca** [comment]
@skipsuva What styles got messed up?

**Comment by skipsuva** [comment]
@guyca The drawer became full width of the device. I just set an explicit width and it looks fine now.

**Comment by aspidvip** [comment]
"react-native-navigation": "^1.1.340",
works without errors! Let's see how it behaves in the future

**Comment by jackmew** [comment]
"react-native-navigation": "^1.1.334" -> "1.1340".
Fixed the problem~

**Comment by guyca** [comment]
@skipsuva If you have `flex: 1` in the side menu root layout, then it will take the full screen width. Setting and explicit width is definitely the right thing to do 👍

**Comment by malloboany** [comment]
this worked for me. ``static navigationOptions = ({ navigation, screenProps }) => ({
      drawerLabel: "Home",
      title: "Home",
      headerLeft: (
        <View style={{ paddingHorizontal: 10 }}>
          <TouchableOpacity
          onPress={() => {
             navigation.toggleDrawer({
               side: 'left'
             })
           }}
           >
            <Icon name="menu" size={30} color="blue" />
          </TouchableOpacity>
        </View>
      )
    });``
