### ISSUE TITLE
Hidden tab bar

### ISSUE THREAD

**Issue by drorbiran** [wix/react-native-navigation#249]
> This issue was originally opened in [react-native-controllers](https://github.com/wix/react-native-controllers/pull/81)

My app uses drawer that is actually tabbar without visible tabs - so user may switch between these tabs using drawer, not tabbar. How to achieve that? I've tried to put TabBar inside NavBar with tabBarHidden style, but looks like NavBar allows only 'component', not inner TabBar (that is pity).

**Comment by eikebartels** [comment]
I have the same question
