### ISSUE TITLE
Provide default props to navBarCustomView while registering?

### ISSUE THREAD

**Issue by gargsms** [wix/react-native-navigation#2492]
### Issue Description

I have a `navBarCustomView` component which relies on some props to be passed to it for it to render accordingly.
Since it is just a dumb component, I do not want it to connect to the redux store to watch for updates.
I supply it with callbacks which give it the current store state. The issue occurs at the time of registration of the component. Since none of those callbacks are available, the component throws errors.
I am unsure about the registration part. I added a few log statements, and they are called multiple times - during component registration and once the app is running. So maybe there are other times where the component is getting mounted/initialized without those callbacks.

### Steps to Reproduce / Code Snippets / Screenshots
Consider for example a `navBarCustomView` component
```
import React from 'react';
import {Image} from 'react-native';

export default function customNavBar (props) {
  return (
    <Image source={props.loadAltImage() ? require('alt-image.png') : require('original-image.png')} />
  );
}
```

This component will fail at the time of registration because `props.loadAltImage` is `undefined`.

**Is there a way to pass default props to the component?
Is there also a way to change the props passed to the `navBarCustomView` at a later stage than `navBarCustomViewInitialProps`?**

---
### Environment
* React Native Navigation version: 1.1.329
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator - iPhone 6 iOS 11.2

**Comment by pqkluan** [comment]
To set the default props:
```jsx
export default function customNavBar (props = { loadAltImage: () => true }) {
```
Or just set the `navBarCustomView` together with `navBarCustomViewInitialProps`.
