### ISSUE TITLE
navBarCustomView not working in Android

### ISSUE THREAD

**Issue by jjimenezlopez** [wix/react-native-navigation#2495]
### Issue Description

I'm trying to use a custom nav bar in my app, I'm setting it in appStyle as in the documentation and it works fine in iOS, but the custom view is not showing in Android at all.

### Steps to Reproduce / Code Snippets / Screenshots
Here is my code:

**Registering the screens**
```javascript
export default function registerScreens(store, Provider) {
  Navigation.registerComponent('myapp.core.InitialScreen', () => InitialScreen, store, Provider);
  Navigation.registerComponent('myapp.core.CustomNavBar', () => CustomNavBar, store, Provider);
}
```

**Starting application**
```javascript
Navigation.startSingleScreenApp({
      screen: {
        screen: 'myapp.core.InitialScreen',
        title: 'my app',
      },
      appStyle: {
        statusBarTextColorScheme: 'light',
        statusBarColor: 'rgb(33, 33, 33)',
        navBarBackgroundColor: 'rgb(33, 33, 33)',
        navBarHeight: 60, // android only
        navBarCustomView: 'myapp.core.CustomNavBar',
      },
    });
```

**Custom nav bar component**
```javascript
import React from 'react';
import { View, Text } from 'react-native';
import { common } from '../../styles';

const CustomNavBar = () => (
  <View style={common.navbar}>
    <Text style={common.navbarText}>
      my app
    </Text>
  </View>
);

export default CustomNavBar;
```

And finally, a couple of screenshot, the iOS one is perfect, the Android one is showing the default navbar.

![captura de pantalla 2018-01-09 a las 0 57 52](https://user-images.githubusercontent.com/1641139/34698386-2eaf7384-f4d8-11e7-824b-bb9a1282b1e8.png)
![captura de pantalla 2018-01-09 a las 0 57 43](https://user-images.githubusercontent.com/1641139/34698389-2eee2796-f4d8-11e7-903d-e2536b304e54.png)

Note that if I use this in my *InitialScreen*:

```javascript
  componentDidMount() {
    this.props.navigator.setStyle({
      navBarCustomView: 'tellscope.core.CustomNavBar',
    });
  }
```

It works in Android, but I'm traying to set a generig nav bar for the entire application, so this is not a solution.

---
### Environment
* React Native Navigation version: 1.1.334
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, API 26

**Comment by jjimenezlopez** [comment]
It's working now moving `navBarCustomView` from `appStyle` to `screen`. I think I missunderstood the location of this config, so I'm closing this bug now.

**Comment by ctt123** [comment]
Did your custom nav bar component didn't show in android some times?

**Comment by josebadger** [comment]
Hi @ctt123, no, it didn't show never until I fixed it.

**Comment by akhan118** [comment]
Note, the android screenshot does show 'my app' , it's in black and to the left .
