### ISSUE TITLE
While screen transition, black screen is opening.

### ISSUE THREAD

**Issue by dbyilmaz** [wix/react-native-navigation#2496]
### Issue Description
When my app first initializing, firstly splash screen, secondly black screen, thirdly white screen are opening then Authenticated or Anonymous screen is opening. These are happening when only first initializing. I want to remove black screen. 

### Steps to Reproduce / Code Snippets / Screenshots
//AppNavigationScreen

```
componentWillMount() {
if(isAuthorized) {
Navigation.startSingleScreenApp(RouteConfig('AuthenticatedScreen'));
} else {
Navigation.startSingleScreenApp(RouteConfig('AnonymousScreen'));
}
}
```

---
### Environment
* React Native Navigation version: 1.1.323
* React Native version: 0.49.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator and General Mobile Android One

  
![ezgif-5-33a543f577](https://user-images.githubusercontent.com/21238272/34709983-973bdac6-f52a-11e7-9297-6e45d0ee46bd.gif)

**Comment by pqkluan** [comment]
This issue seems to happen due to the way you implement the starting code.

Try to follow the [example project](https://github.com/wix/react-native-navigation/tree/master/example).

**Comment by pqkluan** [comment]
Hey, I just wrote a detail [article](https://medium.com/@pqkluan/how-to-implement-splash-screen-in-react-native-navigation-ee2184a1a96) about implementing Splash Screen with RNN.

You could check the gif results to see if the solution is suitable for you.
