### ISSUE TITLE
Redux example doesn't work

### ISSUE THREAD

**Issue by pvlvsk** [wix/react-native-navigation#25]
Hello, 

i cloned the example Folder, run npm install, and run this in Xcode, the result ist only a black screen in the simulator...

**Comment by pvlvsk** [comment]
I checked the regular example without redux and it's also not working for me. I get only a black screen in the simulater after the app initializes. I'm using npm 3.6.0

**Comment by smooJitter** [comment]
That's odd. It works fine for me.
