### ISSUE TITLE
Ability to intercept the back button

### ISSUE THREAD

**Issue by drorbiran** [wix/react-native-navigation#250]
> This issue was originally opened in [react-native-controllers](https://github.com/wix/react-native-controllers/issues/84)

This would allow the back button to be intercepted in case you wish to perform some kind of action (e.g. a save) before leaving the view.

I've implemented in RNC and RNN, I would create a pull request but from the sounds of it you're refactoring a lot of that kind of code - it's here if anyone needs it though.

https://github.com/lprhodes/react-native-controllers/commit/d071f83901dd9cadb8da26bfa19217a72c7ef5b1
https://github.com/lprhodes/react-native-navigation/commit/d65b679c0b4183b80e532d80985ce0ce6685ff35

**Comment by guyca** [comment]
This is actually already implemented on Android

**Comment by Mark2xv** [comment]
This does not seem to work when you're active in a modal.
RN 0.34.1 with react-native-navigation@2.0.0-experimental.133.

**Comment by guyca** [comment]
@Mark2xv I tested this in the example project, Seems to work fine (Android only) for both hardware back button and TopBar back button.

```js
    this.props.navigator.showModal({
      title: "Modal",
      screen: "example.ModalScreen",
      overrideBackPress: true
    });
```

I'm using RN 0.31 but don't think it matters in this case.

**Comment by Mark2xv** [comment]
You're correct - setting `overrideBackPress` fixes my situation. 
However, that property seems to be undocumented as far as I could find?

**Comment by guyca** [comment]
It's undocumented since it's not available on iOS yet and I'm pretty sure that once we implement it on iOS, the api will change a bit. I think the `overrideBackPress` declaration will move out of the `showModal` call and into the screen itself.

**Comment by kevinnguy** [comment]
@guyca @Mark2xv could you give an example of how to use `overrideBackPress`? What is the event type that I should be listening to?

**Comment by kanzitdinov** [comment]
@kevinnguy I had the same problem. I'll provide code that helped me.

GoTo.js (or put this code wherever you fell more comfortable):
```
...
function openWelcomeScreen(props) {
  Navigation.showModal({
    screen: 'auth.Welcome',
    passProps: props,
    animationType: 'slide-up',
    overrideBackPress: true,
  });
}
...
```

WelcomeScreen.js:
```
...
// MARK: APP CYCLE

componentWillUnmount() {
  BackAndroid.removeEventListener('hardwareBackPress', function() {});
}

componentDidMount() {
  BackAndroid.addEventListener('hardwareBackPress', function() {
    // Put some if-statements here if needed
    return false;
  });
}
...
```

**Comment by kevinnguy** [comment]
@kanzitdinov thanks for providing your code as an example! What I want to do is to disable the ability to exit the app by pressing the back button. I've implemented your example in my code but I still get the same result. Is it even possible to disable the back button from exiting the app?

**Comment by kevinnguy** [comment]
I am using `overrideBackPress` on `Navigation.startSingleScreenApp()` though so I may be misusing this feature.

**Comment by kanzitdinov** [comment]
@kevinnguy oh, that is the problem. I also tried to use it the way you've described. You can use it only like this  ```Navigation.showModal({ ..., overrideBackPress: true, });```

**Comment by kevinnguy** [comment]
@kanzitdinov ahh got it. Thanks for your help!

**Comment by SudoPlz** [comment]
What about iOS ...
Is there anything we can do to intercept the back button in iOS ?

**Comment by SudoPlz** [comment]
Any news on that? I really miss that feature.. :'/

**Comment by voidstarfire** [comment]
I might have to stop using this library because this feature isn't implemented 👎

**Comment by fabryx92** [comment]
There still is not a way to intercept a back press on iOS?

**Comment by tirrorex** [comment]
@fabryx92 there is no back button on ios, why would you need to intercept an event fired by your own button ?

On the other hand this feature would be great on android.

**Comment by SudoPlz** [comment]
@tirrorex That feature already exists on Android.

And for iOS the back button is not his own button. It belongs to a `react-native-navigation` native iOS view which we have no control over at the moment. We can't intercept it, so that's what he's talking about.

**Comment by tirrorex** [comment]
@SudoPlz i assume what you are talking about is a UINavigationController which seems to be implemented in react-native by https://facebook.github.io/react-native/docs/navigatorios.html

I don't understand why you would have no control over a button that you should be implementing yourself :/

**Comment by SudoPlz** [comment]
Well the issue that we're currently commenting on, refers to the `UINavigationController` implementation of `react-native-navigation`'s Top bar.

Yes if we implemented that ourselves we'd have control over that button, but apparently that's not the case here.

**Comment by fabryx92** [comment]
@tirrorex what i mean is the default back button in the left position of the navbar. If you are only talking about the android physical button, I am sorry, I misunderstood.

**Comment by Gongreg** [comment]
One workaround that supports both platforms:

1. Push the screen with `overrideBackPress: true`.
2. Override left button with custom one (for instance button with id `backWithCheck`)
3. Handle event in onNavigatorEvent:
```
onNavigatorEvent(event) {
	if (event.id === 'backWithCheck' || event.id === 'backPress') {
		//Do your thing
	}
}
```
