### ISSUE TITLE
Overlay implementation

### ISSUE THREAD

**Issue by yogevbd** [wix/react-native-navigation#2500]
Top level API
- [x] showOverlay(componentId, options) - return promise on completion
- [x] dismissOverlay() - return promise on completion
- [ ] dismissAllOverlay() - do we need this?

Overlay Options
- [ ] interceptTouchOutside
- [ ] queueable (nice to have)

cc @guyca @DanielZlotin

**Comment by guyca** [comment]
@yogevbd Are you resolving a promise when overlay is presented?

```js
  showOverlay(layout) {
    return this.nativeCommandsModule.showOverlay(layout);
  }
```

`showOverlay` isn't `async`...

**Comment by yogevbd** [comment]
@guyca It's taking care of on iOS. Will push fix for the js side

**Comment by guyca** [comment]
Also, the api should be as follows:

```js
Navigation.showOverlay({
      component: {
        name: 'navigation.playground.CustomDialog',
        options: {
          overlay: {
            interceptTouchOutside
          }
        }
      }
    });
```
