### ISSUE TITLE
How to implement onpress action for title/subtitle in Topbar

### ISSUE THREAD

**Issue by ugendrang** [wix/react-native-navigation#2501]
ScreenA:
    this.props.navigator.push({
      screen: 'ScreenB',
      title: 'Screen B',
      subtitle: 'subtitle'
    });

ScreenB:
When I press title/subtitle, it need to navigate to new screen. How to implement onpress action for title/subtitle in Topbar

**Comment by ugendrang** [comment]
Achieved it via navBarCustomView.

      navigatorStyle: {
        navBarCustomView: 'CustomTopbar'
      },

CustomTopbar:
      <View style={styles.container}>
        <TouchableOpacity stye={styles.button} onPress={ () => Alert.alert(this.props.title, 'Welcome') }>
          <Text style={styles.title}>Title</Text>
          <Text style={styles.subTitle}>SubTitle</Text>
        </TouchableOpacity>
      </View>

**Comment by ugendrang** [comment]
@guyca ,

I have tried to implement the described usecase, but facing below issues,
Issue1: Custom Navbar component not referring navigator property. ie this.props.navigator is null

Issue2: callback function is not supported (Error reported on pressing Navbar, 'undefined is not a function _this2.props.onNavbarPressCB()')

`  navigatorStyle: {
    navBarCustomView: 'CustomTopbar',
	navBarCustomViewInitialProps: {this.onNavbarPressCB.bind(this)}
  }
  
  onNavbarPressCB(){
	this.props.navigator.push({screen: 'SCREEN_B'});
  }`

`export default class CustomNavBar extends Component {

   constructor(props) {
    super(props);
    this.state = {};
	console.log(this.props.navigator); //ISSUE_1
  }

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity stye={styles.button} onPress={ () => this.props.onNavbarPressCB()}> //ISSUE_2
          <Text style={styles.title}>{this.props.title}</Text>
          <Text style={styles.subTitle}>{this.props.subTitle}</Text>
        </TouchableOpacity>
      </View>
    );
  }
}`

**Comment by ugendrang** [comment]
@guyca,

I have tried to implement the described usecase, but facing below issues,
Issue1: Custom Navbar component not referring navigator property. ie this.props.navigator is null

Issue2: callback function is not supported (Error reported on pressing Navbar, 'undefined is not a function _this2.props.onNavbarPressCB()')

  navigatorStyle: {
    navBarCustomView: 'CustomTopbar',
	navBarCustomViewInitialProps: {this.onNavbarPressCB.bind(this)}
  }
  
  onNavbarPressCB(){
	this.props.navigator.push({screen: 'SCREEN_B'});
  }


export default class CustomNavBar extends Component {

   constructor(props) {
    super(props);
    this.state = {};
	console.log(this.props.navigator); //ISSUE_1
  }

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity stye={styles.button} onPress={ () => this.props.onNavbarPressCB()}> //ISSUE_2
          <Text style={styles.title}>{this.props.title}</Text>
          <Text style={styles.subTitle}>{this.props.subTitle}</Text>
        </TouchableOpacity>
      </View>
    );
  }
}`

**Comment by flavordaaave** [comment]
@ugendrang Your atempt hinted me to a solution/hack that actually works using the deeplinks logic ;-)

```
static navigatorStyle = {
  navBarCustomView: 'CustomTopbar',
  navBarCustomViewInitialProps: {
    onNavbarPressCB: () =>
        Navigation.handleDeeplink({
          link: 'CUSTOM_TOPBAR_CB',
      }),
  },
}

onNavigatorEvent = event => {
  const { navigator } = this.props

  if (event.type == 'DeepLink') {
    if (event.link == 'CUSTOM_TOPBAR_CB') {
      navigator.push({
        screen: 'SCREEN_B',
      })
    }
  }
}
```
