### ISSUE TITLE
IOS run is fail (Application X has not been registered)

### ISSUE THREAD

**Issue by kungfu321** [wix/react-native-navigation#2509]
Hi. I'm run on IOS is error, but i'm run on android is well
<img width="294" alt="screen shot 2018-01-11 at 11 23 01 am" src="https://user-images.githubusercontent.com/10558363/34812116-dbedbe5c-f6d6-11e7-8de4-4c25e70a851d.png">

![screen shot 2018-01-11 at 1 54 40 pm](https://user-images.githubusercontent.com/10558363/34812143-03a7c0b4-f6d7-11e7-820d-6f63132d8bb6.png)

I'm did clear cache and reinstall node_modules, bui it is not running.

`watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf yarn.lock && rm -rf ./node_modules && yarn install && yarn start -- --reset-cache`

I don't find what wrong. Please help me.
---
### Environment
* React Native Navigation version: 1.1.236
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by danielang** [comment]
I have the same issue, when I push a specific screen.

![image](https://user-images.githubusercontent.com/6752808/34853080-3425c744-f732-11e7-8d0b-6b6342d02279.png)

#### registerScreens()
```javascript
import ArticlesScreen from './articles';
import CategoriesScreen from './categories';

export function registerScreens(store, Provider) {
    // screens
    Navigation.registerComponent('app.Articles', () => ArticlesScreen, store, Provider);
    Navigation.registerComponent('app.Categories', () => CategoriesScreen, store, Provider);
    Navigation.registerComponent('app.categories.List', () => ArticlesScreen, store, Provider);

}
```

#### Code which causes the error (on CategoriesScreen)
```javascript
onCardPressed = (category) => {
    const { navigator, t, theme } = this.props;
    const style = ThemeManager.getStyleSheetForComponent('screens', theme);
        
    navigator.push({
        screen: 'app.categories.List',
        title: t(category),  // returns localized string
        navigatorStyle: {
            ...style, // basic screen styles
            navBarCustomView: null,
        },
        passProps: {
            category
        },
    });
};
```

### Environment

* React Native Navigation version: current master branch
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator; Debug & Release

Android works fine.

**Comment by tiempham** [comment]
You must link lib to ios and android first.

**Comment by kungfu321** [comment]
@tiempham I did linking, I run `react-native link` link all lib into project.

**Comment by tiempham** [comment]
@kungfu321 How about your index.js? it's look like 
`import App from './src/App'

const app = new App()
`

**Comment by danielang** [comment]
My app works well. Only if I push this screen the error occurs.
I've 6 other registered screens and two custom navbars. Everything works well (in iOS too) till I push the `app.categories.List` screen.

**Comment by kungfu321** [comment]
@tiempham yes here is my file

`import App from './src/app';
const app = new App();
`

**Comment by salilbajaj** [comment]
Getting the same error. Tried all the solutions

**Comment by rpolonsky** [comment]
Are there any updates? Getting this error right from the beginning

**Comment by narek11** [comment]
update?

**Comment by msrivas** [comment]
I have facing a similar issue with. I posted on stackoverflow as well - https://stackoverflow.com/questions/49306366/application-not-registered-error-when-using-react-native-navigation-with-redux

Any guidance would be of great help! Thanks!

**Comment by pribeh** [comment]
Experiencing the same. No solution in sight.

**Comment by nezaidu** [comment]
+1

**Comment by ahmad2smile** [comment]
Same error in V2

**Comment by jneuendorf** [comment]
@neil-hyd Thanks, this is the 1st thing that has worked for me.

**Comment by Crysp** [comment]
@neil-hyd thx! your save my day)

**Comment by hannehanen** [comment]
Not working.
And the link to the "sullotion" is not working.

**Comment by jneuendorf** [comment]
@hannehanen this is the working link https://github.com/wix/react-native-navigation/blob/v1/example/ios/example/AppDelegate.m

**Comment by davidleee** [comment]
So what's the key of the AppDelegate solution? 

My AppDelegate is almost the same as the example's, but mine is still not working.
