### ISSUE TITLE
[V2] [ANDROID] ContentView Flickering

### ISSUE THREAD

**Issue by FlaviooLima** [wix/react-native-navigation#2511]
Hi,
I was testing the v2 of react-native-navigation and when I try to create a BottomTabs based application, Android started to give me this weird flickering and huge frames dropped(Use Perf Monitor  4~ Frames drop per 3~ seconds).
It seems almost a page refresh or resize, and it only happen on ContentView. (As far my human eye allow me to see)
None of this happens when I create a SingleScreen application.
This problem is Android only.

  
![example](https://user-images.githubusercontent.com/13239857/34826464-88cb20aa-f6ce-11e7-878a-cab050665be7.gif)

Works
```
    Navigation.setRoot({
      stack: {
        children: [
          {
            component: {
              name: 'navigation.WelcomeScreen'
            }
          }
        ]
      }
    });
```
Doesn't Work

  ```
  Navigation.setRoot({
      bottomTabs: {
        children: [
          {
            stack: {
              children: [
                {
                  component: {
                    name: 'navigation.TextScreen',
                    passProps: {
                      text: 'This is tab 1',
                      myFunction: () => 'Hello from a function!'
                    },
                    options: {
                      bottomTab: {
                        title: 'Tab 1',
                      }
                    }
                  }
                }
              ]
            }
          },
          {
            stack: {
              children: [
                {
                  component: {
                    name: 'navigation.WelcomeScreen',
                    passProps: {
                      text: 'This is tab 2'
                    },
                    options: {
                      bottomTab: {
                        title: 'Tab 2',
                      }
                    }
                  }
                }
              ]
            }
          }
        ]
      }
    });
```

### Environment
* React Native Navigation version: 2.0.2078 until 2.0.2083
* React Native version: 0.51.0
* Platform: Android Only
* Device info: (Debug) (Real Device) Samsung S4/S5 Mini

**Comment by flaviotobi** [comment]
@anonrig  Hi, thanks for the response.
To be honest I don't even know how to apply these settings. :(
I'm new to this library and they made a few changes three releases ago.
I tried what you said in a couple of places and solutions but the bug persists.
it is possible that I'm putting the code in the wrong place.
Can anyone clarify this?

**Comment by guyca** [comment]
Seems to be resolved

**Comment by blairvanderhoof** [comment]
I can repro this as well on 1.1.306.
