### ISSUE TITLE
Swipe element not worked with drawer

### ISSUE THREAD

**Issue by abaddonGIT** [wix/react-native-navigation#2515]
### Issue Description

Swipe element not worked together Drawer. If a disabled drawer in page:

    this.props.navigator.setDrawerEnabled({
      side: 'left',
      enabled: false
    });
drawer disable but swipe not worked :( Swipe work only if i set disableOpenGesture, but it does not suit me. I try to use for swipe two components: 
[Native-Base SwipeRow](https://docs.nativebase.io/Components.html#swipeable-multi-def-headref)
[react-native-swipeout](https://github.com/dancormier/react-native-swipeout)
### Steps to Reproduce / Code Snippets / Screenshots

Drawer init:

    left: {
      screen: 'type.NativeDrawer'
    }
---
### Environment
* React Native Navigation version: 1.1.310
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): only IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device

**Comment by AE0011** [comment]
same problem
