### ISSUE TITLE
ShowLightbox not render properly

### ISSUE THREAD

**Issue by perfmlin** [wix/react-native-navigation#2516]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots
Press Show Lightbox 
Screen not render

![qq 20180112114847](https://user-images.githubusercontent.com/10769151/34859014-a62af40c-f78e-11e7-9e9d-06935cfad1f4.png)

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.336 
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator  API 21 Debug

**Comment by kibot914** [comment]
Facing the same issue here, can anybody fix it ?

**Comment by pqkluan** [comment]
Can you provide the LightBox content and the code block that open the LightBox?

**Comment by danielang** [comment]
This issue is also in your example app. So you have your code and content already.
The result you see in the attached screenshot above.

There are already a discussion in issue #2288
