### ISSUE TITLE
[v2]rebuild documents + wrong bottomTab's title

### ISSUE THREAD

**Issue by redwind** [wix/react-native-navigation#2517]
### Issue Description

- Please rebuild document site for v2.
- It's seem bottomTab's title in android force set to tab index in this code:
`String title = String.valueOf(i);` in **BottomTabsController**

### Steps to Reproduce / Code Snippets / Screenshots

 
---
### Environment
* React Native Navigation version: 2.x.x
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android device

**Comment by guyca** [comment]
We're converting the project to TypeScript, once we're done we'll reimplement the auto generating scripts.
