### ISSUE TITLE
How to prevent click to tab?

### ISSUE THREAD

**Issue by xuananpham93** [wix/react-native-navigation#2518]
I want to turn off 2 in 4 tabs of my app. When user click tab disabled then nothing to show => Keep current screen. How can I do it?

**Comment by beansoftapp** [comment]
We implements this feature by modify the native code with our own fork, no way to do it through JS only.

See:
ios patch:
https://github.com/pilipa-cn/react-native-navigation/commit/d8086e2d7f1fe2e031e34c76c09c47f247bcb70c

android patch:
https://github.com/pilipa-cn/react-native-navigation/commit/6517af17662662ae116bb0275c48f1f95278d2d9

JS side:
const tabsMain = [
    {
        label: 'ServicePage,
        screen: 'ServicePage',
        icon: require('./img/service_normal.png'),
        selectedIcon: require('./img/service_selected.png'),
        title: 'ServicePage',
        navigatorStyle
    },
    {
        label: 'MessagePage',
        screen: 'MessagePage',
        icon: require('./img/message_normal.png'),
        selectedIcon: require('./img/message_selected.png'),
        title: 'MessagePage',
        isIntercept:true,
        navigatorStyle
    },
    {
        label: 'MinePage',
        screen: 'MinePage',
        icon: require('./img/mine_normal.png'),
        selectedIcon: require('./img/mine_selected.png'),
        title: 'MinePage',
        isIntercept:true,// Newly added function, click this will bring up navigation event 'bottomTabSelected', but no tab page screen changes
        navigatorStyle,
    }
];

You can use our fork for a test: 
 "dependencies": {
"react-native-navigation": "github:pilipa-cn/react-native-navigation"
}

**Comment by shubham2385** [comment]
there is way to prevent render tab and open drawer and light box.
