### ISSUE TITLE
leftButtons  does not work on android

### ISSUE THREAD

**Issue by winglight** [wix/react-native-navigation#252]
I have a main screen with the same code on ios and android which have a left button. That's very weird that the left button can't be shown on android but shown on ios.
And after jumping the second screen, the back button could be shown on android and ios as normal.

**Comment by guyca** [comment]
@winglight it does work, but the api is a [bit different](https://github.com/wix/react-native-navigation/blob/master/example-redux/src/screens/PushedScreen.js#L239).
#224 describes the problem so I'm closing this issue.
