### ISSUE TITLE
How to avoid opening multiple views (navigator.push)

### ISSUE THREAD

**Issue by mtzluisalfredo** [wix/react-native-navigation#2521]

**Comment by bozaigao** [comment]
@mtzluisalfredo export function callOnceInInterval(functionTobeCalled, interval = 600) {
    if (!isCalled) {
        isCalled = true;
        clearTimeout(timer);
        timer = setTimeout(() => {
            isCalled = false;
        }, interval);
        functionTobeCalled();
    }
}

**Comment by bozaigao** [comment]
then callOnceInInterval(()=> {
                                        this.props.navigator.push({
                                            screen: 'wenlu.VideoDetail',
                                            passProps: {title: this.state.majorInfo.subjects[this.state.index].subject_name}
                                        })
                                    })

**Comment by pqkluan** [comment]
In this case, you have to implement a de-bounce function like @bozaigao has posted. 
Create a HOC to add the custom navigate methods with the de-bounce applied will be the best way to handle this.

I'll close the issue as the answers were provided. Feel free to re-open if needed.
