### ISSUE TITLE
Android - Unable to push a screen before UI resumes

### ISSUE THREAD

**Issue by liorchen** [wix/react-native-navigation#2523]
### Issue Description

Hi
Let's say I have two screens: Login and Home.
I want to show the login screen every time my app resumes, but using react native navigation - every time my app resumes - the previous screen (the home screen) is shown for a very short time until my new navigation command (I tried - ```Navigation.startSingleScreenApp```, ```navigator.push```, ```Navigation.showModal```) applies during the ```AppState``` listener.
In order for this to (partially) work, I had to add ActivityCallback as following:
```
    @Override
    public void onActivityResumed(Activity activity) {

            //set content view
            NavigationActivity navAct = (NavigationActivity)activity;
           
            ActivityParams params = new ActivityParams();
            .... // init activity params
            Layout layout = LayoutFactory.create(navAct, params);
            if (AppStyle.appStyle.screenBackgroundColor != null &&
                    AppStyle.appStyle.screenBackgroundColor.hasColor()) {
                layout.asView().setBackgroundColor(AppStyle.appStyle.screenBackgroundColor.getColor());
            }
            navAct.setContentView(layout.asView());
            _lastIntent = null;
        super.onActivityResumed(activity);
    }
``` 
this is working but there are two problems:
1. when calling ```this.props.navigator.resetTo(..)``` from the component loaded this way - nothing is happening.
2. it's a bit slow

I'm kinda stuck because of this whole thing.. I'm starting to consider using a native android activity. 

Is there any good way to solve this? 
will appreciate your help!

---
### Environment
* React Native Navigation version: ^1.1.332
* React Native version: ^0.51.0
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): simulator - debug

**Comment by guyca** [comment]
I think replacing `resetTo` with `startSingleScreenApp` is what you need.

Wouldn't you prefer to validate session in [AppState](https://facebook.github.io/react-native/docs/appstate.html) listener and call `startSingleScreenApp` with your login root if needed?

**Comment by liorchen** [comment]
@guyca 
well my use case requires to pop up a "login" screen before the home ALWAYS (trust me, I know all about session management already.. it's not the issue)
startSingleScreenApp doesn't do the job.. I think it actually requires intervention in the native code (onResume..) 

I cannot say it's a bug. I would call it a feature request (very important one if you ask me..).

Thanks anyway
Lior.
