### ISSUE TITLE
Android FAB not always showing

### ISSUE THREAD

**Issue by jakewtaylor** [wix/react-native-navigation#2525]
### Issue Description

When adding a FAB to a pushed screen, it doesn't always show. I can't work out why.

It only happens on pushed screens as far as I can tell, I have no problems with FAB showing on my root view.

---
### Environment
* React Native Navigation version: 1.1.335
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 5X Simulator, Android 7.1.1

My code (simplified as much as possible):

#### FAB HOC
```JavaScript
const fab = (Component, fab) => class extends PureComponent {
    componentDidMount () {
        const { navigator } = this.props;
        loadIcons.then(() => {
            const fab = this.getFabObj();
            navigator.setButtons({ fab });
        });
    }

    getFabObj = () => {
        const newFabObj = { ...fabObj };

        if (has(newFabObj)('collapsedId')) {
            newFabObj.collapsedId = `fab_${newFabObj.collapsedId}`;
        }

        if (has(newFabObj)('collapsedIcon')) {
            newFabObj.collapsedIcon = iconsMap[newFabObj.collapsedIcon];
        }

        if (has(newFabObj)('expendedId')) {
            newFabObj.expendedId = `fab_${newFabObj.expendedId}`;
        }

        if (has(newFabObj)('expendedIcon')) {
            newFabObj.expendedIcon = iconsMap[newFabObj.expendedIcon];
        }

        if (has(newFabObj)('actions') && Array.isArray(newFabObj.actions)) {
            newFabObj.actions = newFabObj.actions.map(action => ({
                ...action,
                icon: iconsMap[action.icon],
                id: `fab_${action.id}`,
            }));
        }

        return newFabObj;
    }

    render () {
        return (
            <Component {...this.props} />
        );
    }
}
```

Component being used by FAB is a regular component, but quite large so won't put it here.

I'm using the HOC like:
```JavaScript
Navigation.registerComponent('telltrail.Main.Post', () => fab(Post, {
    backgroundColor: colors.PRIMARY,
    collapsedId: 'comment',
    collapsedIcon: 'comment',
    collapsedIconColor: colors.WHITE,
}));
```

Thanks for any help.

**Comment by guyca** [comment]
Hey there, fab isn't a custom component.. it doesn't need to be registered. It's a native Android fab from the support library.
I hope this section from the docs will help clarify the [usage](https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=floating-action-button-fab-android-only)

**Comment by jakewtaylor** [comment]
There's some confusion here. I'm not using the FAB as a component, I've made a higher-order components to apply FABs to certain screens. The code I've shown is my HOC that gets given an object (the fab properties), which is then applied using `navigator.setButtons({ fab })`. This issue isn't resolved. 😄

**Comment by jakewtaylor** [comment]
Thanks for reopening. Do you have any ideas @guyca?

**Comment by guyca** [comment]
Not really, perhaps its a race with the screens' show animation. Try calling `setButtons` from [didAppear](https://wix.github.io/react-native-navigation/#/screen-api?id=listen-visibility-events-in-onnavigatorevent-handler)

**Comment by jakewtaylor** [comment]
That fixed it! Thanks a lot.

**Comment by philipp-serfling** [comment]
@guyca this should be noted in the docs somewhere. 
It did the trick for me aswell - thank you very much - but it took me 7hours to get this work

**Comment by Pushplaybang** [comment]
@guyca  your linkl above returns a 404, and can't seem to find any documentation about working with a FAB,

**Comment by jakewtaylor** [comment]
Which link @Pushplaybang? Both are working for me

**Comment by Pushplaybang** [comment]
@jakewtaylor link from the 15th of Jan pointing to a 404

<img width="882" alt="screenshot 2019-03-07 at 18 01 34" src="https://user-images.githubusercontent.com/1330359/53970309-14babb00-4103-11e9-9de9-f0c3af1a5dbd.png">
<img width="1660" alt="screenshot 2019-03-07 at 18 00 36" src="https://user-images.githubusercontent.com/1330359/53970310-14babb00-4103-11e9-81ce-a0de50eaf385.png">

**Comment by jakewtaylor** [comment]
That is strange, the link still works fine for me. The link was just to the web version of [this](https://github.com/wix/react-native-navigation/blob/v1/docs/adding-buttons-to-the-navigator.md#floating-action-button-fab---android-only) docs page. That link is directly to the markdown so should work forever!
