### ISSUE TITLE
java.lang.NullPointerException if appStyle not exists

### ISSUE THREAD

**Issue by alexesDev** [wix/react-native-navigation#253]
react-native-navigation@2.0.0-experimental.76
In https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java#L85

**Comment by alexesDev** [comment]
Currect fix...
```java
if (AppStyle.appStyle == null ||
    AppStyle.appStyle.bottomTabBadgeBackgroundColor == null ||
    AppStyle.appStyle.bottomTabBadgeTextColor == null) {
  return;
}
```

**Comment by alexesDev** [comment]
Sorry, I did not create pullrequest, because do not know much java and this project... but only `AppStyle.appStyle == null` check not work.

**Comment by guyca** [comment]
sorry about that. Should be good now.
