### ISSUE TITLE
Navigation startTabBasedApp order of tab creation is reversed on iOS vs. Android

### ISSUE THREAD

**Issue by jslz** [wix/react-native-navigation#2533]
### Issue Description

When I call Navigation.startTabBasedApp() I want the tab screens that are then created to be created in the same order on all platforms. Empirically is appears on iOS they are created in order, whereas on Android they are created in reverse order.

### Environment
* React Native Navigation version: 1.1.331
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): both 
* Device info (Simulator/Device? OS version? Debug/Release?): everything, as far as i know

**Comment by pqkluan** [comment]
Just curious, how are the screens mounting order troubling you?
