### ISSUE TITLE
Pushing new screen in Android doesn't preserve navBar style.

### ISSUE THREAD

**Issue by witalobenicio** [wix/react-native-navigation#2534]
When I call:

```
this.props.navigator.push({
      screen: 'fastseller.Cart',
      title: Strings.Cart,
    });
```

The navBar goes WHITE and text and buttons are BLACK.

There's a way to preserve the style in Android?

**Comment by guyca** [comment]
You can declare your them in [appStyle](https://wix.github.io/react-native-navigation/#/top-level-api).

**Comment by witalobenicio** [comment]
@guyca I'm already declaring them on appstyle... But when I call "push screen" it loses the style only in Android.

**Comment by beginnermanish** [comment]
I am also getting the same issue here.

**Comment by guyca** [comment]
I can't reproduce this issue in the example app, which declares styles in appStyle

**Comment by witalobenicio** [comment]
@guyca There is way to update appStyles after the tab based was launched? 
For example...I get a color based on an image, and then, update for all screens.

**Comment by maximerenou** [comment]
Just to be clear, I faced this issue on a single screen app...

**Comment by drpiou** [comment]
Same here... I'm no longer surprised anymore for all the many bugs I found in this plugin.
