### ISSUE TITLE
Problem with toggleDrawer on IOS

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#254]
Hi all,

I discovered a bug toggleDrawer on ios.
My apps have 3 tab
- Home, search and person tab

First run ok, 
On PersonTab i have check if user isLogin = false will hide button Login.
A modal Login will show when login button clicked, then login success steps continue:
- Call handeDeepLink:

> this.props.navigator.handleDeepLink({
>  link: "accountprofile/login/" + customerId
> })
- check deeplink event "accountprofile/login/" on PersonTab
  1. Get account profile: 

> this.getAccountProfile(parts[2]);
1. Switch to tab Person (itself) (because Login Modal called many other screen, action)

> this.props.navigator.switchToTab({
>   tabIndex: 2
> });

Any things working, but now toggleDrawer (at all tab) not working. only IOS (android ok)

thank you so much!

**Comment by elliotstokes** [comment]
I'm seeing this issue too. I can close the drawer from the component that opened it but if I try calling it in another View then it does not close. On android the drawer closes as expected.

**Comment by Flavien** [comment]
I have the same problem. Did you find a solution?
