### ISSUE TITLE
How can create this?

### ISSUE THREAD

**Issue by nyaratakumi** [wix/react-native-navigation#2543]
### Issue Description
How can create this with `startTabBasedApp(params)`?

### Screenshots
![2018-01-16 23 49 03](https://user-images.githubusercontent.com/13572056/34994792-f90beb22-fb17-11e7-9128-1b52a908c7e8.png)

It is underlined in the bottom right that I want to pay attention, I also want to implement it

### Environment
* React Native Navigation version: 1.1.334
* React Native version: 0.50.3
* Platform(s) (iOS, Android, or both?): iOS

**Comment by mkuczera** [comment]
We implemented the underlined tabbar inside our project, but patched the AHBottomNavigation React-Native-Navigation is using for Android and RCCTabBarController.m / RCCTabBarController.h . If it´s wanted, i can create a pull request at least for the indicator after a little bit of code cleanup
