### ISSUE TITLE
initialTabIndex doesn't work (iOS)

### ISSUE THREAD

**Issue by camellieeee** [wix/react-native-navigation#2546]
#### But setSelectedIndex not work 
---
### Environment
* React Native Navigation version: 1.1.340
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Device Debug and Release

**Comment by guyca** [comment]
@camellieeee Try upgrading? Seems to work on latest version. One of the last commits messed up some style attributes but was quickly reverted.
