### ISSUE TITLE
Build Failed for Android

### ISSUE THREAD

**Issue by igor9levi** [wix/react-native-navigation#2551]
When I init brand new react native app and ONLY install react-native-navigation and follow intructions in docs to install it in android files when run: react-native run-android -> BUILD FAILD ?

Without temporing with android folder files app starta normally in its default welcome screen.

**Comment by guyca** [comment]
RNN doesn't support RN 0.52 yet, try downgrading to RN 0.51

**Comment by cxrod** [comment]
Im facing the same issue with 0.55 , what is the las version of React Native does React Navigation Navigation support? 

From Docs : 

> Make sure you are using react-native version >= 0.51. We also recommend using npm version >= 3

**Comment by uinz** [comment]
![image](https://user-images.githubusercontent.com/12208108/40776992-02e77ef8-64ff-11e8-9071-d7ecce40a474.png)

which version should I choose?
