### ISSUE TITLE
Unhandled Promise Rejection Error startTabBasedApp timestamp immutable frozen

### ISSUE THREAD

**Issue by jslz** [wix/react-native-navigation#2553]
### Issue Description

https://github.com/wix/react-native-navigation/blob/fd4e7091c056dfe9554efbc38cf1a5762b32d3fe/src/deprecated/platformSpecificDeprecated.ios.js#L119

You attempted to set the key `timestamp` with the value `xxx` on an object that is meant to be immutable and has been frozen.

![simulator screen shot - iphone 6 - 2018-01-17 at 11 33 18](https://user-images.githubusercontent.com/27701565/35062924-6e37aa8c-fb7a-11e7-8792-dad9c1688cc6.png)

### Steps to Reproduce / Code Snippets / Screenshots

I haven't seen this before today and I don't think we've really changed much so maybe it is some kind of race condition. We're just calling startTabBasedApp with a config. I did a console.log(Object.isFrozen(config)) and it said false.

---
### Environment
* React Native Navigation version: 1.1.331
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): saw it on iOS simulator, haven't repro'd it much yet.
* Device info (Simulator/Device? OS version? Debug/Release?): RN Debug build, iOS simulator, iphone 6, iOS 11.2

**Comment by jslz** [comment]
Update: seeing it pretty often today. Printing out the stuff from that line 119, params.passProp === undefined, and Object.isFrozen(params.passProp) === true, although Object.isFrozen(params) === false.

**Comment by jslz** [comment]
So far, I think I've only seen it on the iOS simulator. The iPhone 6 / iOS 10.3.2 i test on hasn't failed with that yet.

**Comment by jslz** [comment]
fwiw If I manually patch the code from

```
    _.set(params, 'passProps.timestamp', Date.now());
```

to

```
    if (params.passProps === undefined) { params.passProps = {}; }
    params.passProps.timestamp = Date.now();
```

then it doesn't fail.

(I did some testing in a repl of _.set() and could not repro the issue that way.)

**Comment by jslz** [comment]
I fixed it in our own code, it appears to be something about how module-level variables are somewhere frozen by something. So I moved the config to be inside the same function that calls startTabBasedApp and it was all ok.

**Comment by tmaly1980** [comment]
@jslz For the sake of others, can you clarify what exactly you did to fix this (with code samples)? I'm running into this same exact issue.

**Comment by jslz** [comment]
@tmaly1980 dunno exactly other than making everything as "function local" instead of anything being "module local" helped fix it, empirically speaking.

**Comment by tmaly1980** [comment]
Sorry, can you please clarify what you mean by an example? I don't know what 'function local' and 'module local' means.

**Comment by tmaly1980** [comment]
@jslz I think I figured it out. I don't exactly know why, but because I call startTabBasedApp multiple times (once post-login, and another after rehydrating), passProps gets set as immutable (probably somewhere deep inside react-native-navigation)... and won't be able to be called multiple times if state changes. The easiest solution I could come up with is doing a deep copy using JSON:

`Navigation.startTabBasedApp(JSON.parse(JSON.stringify(tabNavigationConfig)));`

This solved my immutability problems with starting the app.

**Comment by gordysc** [comment]
Just in case someone else hits this down the road, you can also have your config be returned via function to fix this:
```
const config = () => { 
 return {
  tabs: [ ... ]
  }
};

Navigation.startTabBasedApp(config());
```

**Comment by hiradarshadi** [comment]
I had the same problem. You @tmaly1980, just Saved My Life 💯
