### ISSUE TITLE
InAppNotification swipe direction doesn't change when setting position to 'bottom'

### ISSUE THREAD

**Issue by jmhuret** [wix/react-native-navigation#2554]
### Issue Description

I'm using the inAppNotification quite a lot in my app (and really like the implementation). It appears that when I set `position: 'bottom'` I still have to swipe up to get the notification to go away, not swipe down like I would expect.

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.showInAppNotification({
          screen: 'myapp.screen',
          passProps: {...props},
          position: 'bottom'
        });
```

---
### Environment
* React Native Navigation version: 1.1.262
* React Native version: 0.49
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?):simulator and device, n - 2 release, debug and release

**Comment by mkuczera** [comment]
Added PR to handle the iOS swipe to dismiss [#2567](https://github.com/wix/react-native-navigation/pull/2567)
