### ISSUE TITLE
Build succeeds, but app crashes after downloading JS bundle

### ISSUE THREAD

**Issue by MiLeung** [wix/react-native-navigation#2558]
### Steps to Reproduce / Code Snippets / Screenshots

I basically just try to make the most bare bones project with react-native-navigation

```
react-native init Test --version="0.51.0"
yarn add react-native-navigation@latest
react-native link
```

index.js
```js
import App from './src/app';
```

app.js
```js
import { Navigation } from 'react-native-navigation';
import { registerScreens } from './screens';

registerScreens();

Navigation.startSingleScreenApp({
  screen: {
    screen: 'progress._'
  }
});
```

screens.js
```js
import { Navigation } from 'react-native-navigation';
import _ from './components/_';

export function registerScreens() {
  Navigation.registerComponent('progress._', () => _);
}
```

_.js
```js
import React from 'react';
import { View, Text } from 'react-native';

export default props => {
  return (
    <View}>
      <Text>test</Text>
    </View>
  );
}
```
---
### Environment
* React Native Navigation version: 1.1.346
* React Native version: 0.51.0
* Platform: iOS (haven't test Android)
* Device info: Simulator and physical iPhone 6

**Comment by guyca** [comment]
I'm not sure `react-native link` works with RNN.
Seems like this isn't a bug but likely a misconfigured project, please post your issue in [SO](https://stackoverflow.com/questions/tagged/react-native-navigation?mixed=1) and include a stack trace.

**Comment by MiLeung** [comment]
I tried linking manually previously, but it appeared that react-native link did everything that the docs said to do.
