### ISSUE TITLE
ScrollView not acting well when using "drawUnderStatusBar: true"

### ISSUE THREAD

**Issue by zarnifoulette** [wix/react-native-navigation#2560]
### Issue Description

I tweak my status bar so I set to true the `drawUnderStatusBar: true` when I push a new Screen. 
And I put a component in header like that 
`<View>
	<LinearGradient colors={Assets.gradientColors} style={styles.header}/>
</View>

header: {
	height: (Platform.OS === 'ios' ? 20 : StatusBar.currentHeight),
}
`

My problem is when I create a ScrollView within input, the view not resize at all. But if I suppress the  `drawUnderStatusBar: true` option the ScrollView act well. But I need to keep my status bar with the current LinearGradient. 

Do you have an idea to correct this bug ?
![screenshot_20180118-164425](https://user-images.githubusercontent.com/16413502/35106696-2f160236-fc6f-11e7-8091-0e5ad5e6d03c.png)
Here I can scroll but my view is wrap in a scrollView.

![screenshot_20180118-164451](https://user-images.githubusercontent.com/16413502/35106716-3eecf0e8-fc6f-11e7-9bc8-ba710b46d9af.png)
Here I can scroll but I have a statusBar problem.

---
### Environment
* React Native Navigation version: 1.1.334
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by arsal-wal** [comment]
Having the same problem. Did you find a workaround?
