### ISSUE TITLE
Set background image to avoid White Screen Flash before first page

### ISSUE THREAD

**Issue by RuairiOliver** [wix/react-native-navigation#2561]
Hi,

I'm currently getting a white screen in between the splash screen and the first screen of my application.

Without this library I could do the following:

UIImageView *launchView = [[UIImageView alloc] initWithImage: image];
      launchView.contentMode = UIViewContentModeBottom;
      launchView.image = image;
      rootView.loadingView = launchView;

Any ideas?

Thanks

**Comment by fbartho** [comment]
I've been planning to make a NativeModule that replicates our LaunchImage, and then waits for Javascript to dismiss it. -- This is really a problem with react-native; not so much with react-native-navigation. :(

**Comment by pqkluan** [comment]
Hey, I just wrote a detail [article](https://medium.com/@pqkluan/how-to-implement-splash-screen-in-react-native-navigation-ee2184a1a96) about implementing Splash Screen with RNN.

You could check the gif results in the article, there is no white screen in between. Hope this help :)

**Comment by pqkluan** [comment]
I'll close this issue, assuming the problem was solved. Feel free to re-open if needed.

**Comment by RuairiOliver** [comment]
Thanks pqkluan. I actually have the same setup as you but I get a white screen while the loading progress displays which you don't seem to. My app is probably much larger though. 

So my app start up is like this:
1. Splash screen image displays
2. White Screen (when in debug shows loading percentage)
3. Initial page displays from startSingleScreenApp

**Comment by pqkluan** [comment]
@RuairiOliver Do your app has to fetch/load data before `startSingleScreenApp` get called? The white screen in between maybe creates by that process.
