### ISSUE TITLE
[Android] disableOpenGesture: true is not working

### ISSUE THREAD

**Issue by DaniyarJakupov** [wix/react-native-navigation#2564]
On Android drawer param `disableOpenGesture: true` is not working. I'm still able to open it with swipe gesture. Tho I want to toggle it only with navbar icon. I manage to disable it via screen api, like this
```
this.props.navigator.setDrawerEnabled({
      side: 'left', // the side of the drawer since you can have two, 'left' / 'right'
      enabled: false, // should the drawer be enabled or disabled (locked closed)
    });
```

Swipe gesture is disabled and navbar icon toggles the drawer. But now on iOS drawer does not open at all. Of course, I can fix it with Platform.OS, but it's a lot of unnecessary work that could be avoided if only `disableOpenGesture: true` param was working as intended.

---
### Environment
* React Native Navigation version: 1.1.335
* React Native version: 0.50.4 
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Emulator, OS 6.0

**Comment by kevinmeyvaert** [comment]
Experiencing the same issue.

**Comment by kevinmeyvaert** [comment]
@DaniyarJakupov Have you found a solution to your issue yet. I've been looking into it yesterday and still didn't get it to work.

**Comment by Th3Ov3r** [comment]
I have the same problem, "disableOpenGesture: true"  it does not work, 
but this does it. this.props.navigator.setDrawerEnabled({ side: 'left', enabled: true });

**Comment by alaboudi** [comment]
Same problem here. disableOpenGesture when initializing a single screen app

**Comment by qmegas** [comment]
Any progress on that issue?

**Comment by prateek3255** [comment]
I'm facing the same issue.

**Comment by Th3Ov3r** [comment]
here a momentary solution
https://github.com/wix/react-native-navigation/issues/922#issuecomment-302897609
