### ISSUE TITLE
[iOS]  navBarTextFontSize is not working

### ISSUE THREAD

**Issue by DaniyarJakupov** [wix/react-native-navigation#2565]
On iOS I cannot control the size of a title in the nav bar via `navBarTextFontSize` param . Tho on Android it does work. 

---
### Environment
* React Native Navigation version: 1.1.335
* React Native version: 0.50.4 
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS Simulator v.10

**Comment by ReggaePanda** [comment]
same issue
```
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0


React Native Navigation version: wix/react-native-navigation#2545/head
```

**Comment by danielang** [comment]
related to #2542

**Comment by tevatahiti** [comment]
I followed @danielang advice and tried: navBarTitleFontSize instead of navBarTextFontSize.... it works fine lol, thanks @danielang for spoting it!

**Comment by tevatahiti** [comment]
It is actually the same problem with navBarTextFontFamily --> we must use **navBarTitleFontFamily**

**Comment by tevatahiti** [comment]
Ok I have updated to "react-native-navigation": "^1.1.458" and now the navBarTextFontSize and navBarTextFontFamily works fine now. They must have discovered the bug lol. Can someone close that issue? @DaniyarJakupov? @danielang ?

**Comment by DaniyarJakupov** [comment]
@tevatahiti good to hear!
