### ISSUE TITLE
[Proposal] Tabs Parameter in startSingleScreenApp

### ISSUE THREAD

**Issue by c0d3blooded** [wix/react-native-navigation#2575]
Hi all,

This is my first issue here so first I'd like to thank the authors of this library and the contributors who've been a part of making it grow. It's been a very helpful library thus far.

This library makes navigation with RN simple. Unfortunately, the tab based navigation is sort of weird. From what I've seen, it's more of the norm to have tabs on a single screen and additional pushes continue separately, either without tabs or it's their own set of tabs. However, the current implementation is clearly supported officially.

In my own app, it makes sense to have a single screen with tabs and multiple single screens during navigation (e.g. Settings, About page, object editing, etc.). The current 2 options make it difficult to implement such a structure. What I'd propose (possibly for v2) is the [startSingleScreenApp] function a "tabs" parameter (similar to the [startTabBasedApp] parameter). Having tabs attached to a single view rather than integrated into the entire navigation of the app would make things much easier.

The implementation would be similar to TopTabs which is being worked on in v2 (and in the answer here https://github.com/wix/react-native-navigation/issues/1322).

This would:
- make it clear when to use showModal vs push (ok on Android, awkward in iOS)
- avoid managing messy tabBarHidden tags for every single screen in startTabBasedApp
- avoid multi-tab navigation management
- simplifying multiple screens which contain tabs

It would also solve many similar concerns/issues:
https://github.com/wix/react-native-navigation/issues/2482
https://github.com/wix/react-native-navigation/issues/2309 (possibly)
https://github.com/wix/react-native-navigation/issues/1988
https://github.com/wix/react-native-navigation/issues/1979
https://github.com/wix/react-native-navigation/issues/1712
https://github.com/wix/react-native-navigation/issues/1225
https://github.com/wix/react-native-navigation/issues/690
https://github.com/wix/react-native-navigation/issues/2289
https://github.com/wix/react-native-navigation/issues/2187
https://github.com/wix/react-native-navigation/issues/1905

Below is also a visualization of how such navigation would work as well in comparison with current solutions.
![startsingle](https://user-images.githubusercontent.com/8219641/35200650-3ceca3b0-fee0-11e7-9326-a34fc5fede2b.png)
![starttabs](https://user-images.githubusercontent.com/8219641/35200651-3cf80372-fee0-11e7-9282-1e7734d945a3.png)
![startsingletabs](https://user-images.githubusercontent.com/8219641/35200652-3d023f36-fee0-11e7-8c0b-da1b8b5efa7b.png)

**Comment by guyca** [comment]
Hey @c0d3blooded 
Thanks for the kind words and for taking the time to write your suggestion in such detail. The current api RNN uses was basically tailored for Wix use cases, we never thought this library would pick off, so we didn't bother creating a generic api which will address more use cases.

As you've mentioned, this feedback cames up a lot so we've made the v2 api much more flexible. You'll be able to construct layout as you see fit, without much (any 🙏 ) limitation.

You can check out the v2 api by opening the playground app in the `v2` branch. There's still work being done on it and we have a few ideas on how to simplify it, while still keeping flexibility

**Comment by c0d3blooded** [comment]
Ok. Thanks for the response. I'll take a closer look at what's been done in v2 to get a better idea of how it's progressing and contribute if I can.
