### ISSUE TITLE
[v2] Pressing HW back button on root view causes app to be blank on repopen

### ISSUE THREAD

**Issue by michael-gillett** [wix/react-native-navigation#2579]
### Issue Description
From the root view of your app, if you click the hardware back button on Android it closes the app to the home screen as expected. **However when you reopen the app it is a completely blank gray screen.**

Using the home button to close the app and then reopen behaves as expected and the app is resumed.

I dug around in `StackController.java` and `canPop()` is functioning correctly and returning false when only the root view exists.

### Steps to Reproduce / Code Snippets / Screenshots
1. Setup a root view
```
Navigation.setRoot({
  stack: {
    children: [
      {
        component: {
          name: 'SomeScreen',
        },
      },
    ],
  },
});
```
2. Press the hardware back button on your android device
3. Reopen the app, the screen will be completely blank

![screen shot 2018-01-22 at 12 39 12 pm](https://user-images.githubusercontent.com/9299495/35236557-c0579b48-ff75-11e7-81e3-0c0d5a3875b7.png)

---
### Environment
* React Native Navigation version: **2.0.2083**
* React Native version: **0.51.0**
* Platform(s) (iOS, Android, or both?): **Android**
* Device info (Simulator/Device? OS version? Debug/Release?):
**Emulator Nexus 5X (Android 8.0.0, API 26)**
****

**Comment by perrosnk** [comment]
Could this be related to https://github.com/wix/react-native-navigation/issues/963? Have you tried switching on and off debug and hot reload?

**Comment by michael-gillett** [comment]
@perrosnk Looks like a similar problem, but a different underlying cause. I am experiencing this even in debug and release builds with and without the debugger enabled

**Comment by guyca** [comment]
@michael-gillett I can't reproduce in the playground app, possible latest commit fixed the issue. Can you please confirm.

**Comment by michael-gillett** [comment]
@guyca Thanks for the help and my apologies! It was actually an issue on my end with a race condition related to the `Navigation.events().onAppLaunched` event. I have a bit of logic that waits for my redux store to be populated before loading the root which didn't wait for that event. This worked fine in all cases except for this specific issue

The solution was to wrap my redux logic with the event listener and just make sure that the redux logic is called at least once in case it populates before the event is fired. I'll make sure to test in the playground next time before making an issue :)
