### ISSUE TITLE
can not define modal height？

### ISSUE THREAD

**Issue by AndrewJikun** [wix/react-native-navigation#2581]
### Issue Description
I checked the doc and did not see how to define the modal height or can we have a drawer shown from the bottom?

---
### Environment
* React Native Navigation version:latest（V1）
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): IOS * Device info (Simulator/Device? OS version? Debug/Release?):  Iphone 8 plus

**Comment by guyca** [comment]
Modal matches the device dimensions. 
I don't think RNN v1 provides an easy api for custom drawers. We've addressed this issue in v2 with the overlay api.
