### ISSUE TITLE
topBarElevation stopped working on iOS

### ISSUE THREAD

**Issue by iksent** [wix/react-native-navigation#2586]
### Issue Description

I am using such code in "render" of component (similar if in constructor or componentDidMount):

`        this.props.navigator.setStyle({
            topBarElevationShadowEnabled: false,
            topBarShadowOffset: 0,
            navBarTextColor: 'blue',
        });`

navBarTextColor was changed fine, but shadow was not disabled.

Also if I have a screen with {topBarElevationShadowEnabled: true} and I push from it new screen with {topBarElevationShadowEnabled: false}, I get new screen with shadow. (I know about keepStyleAcrossPush and enabled it)

### Steps to Reproduce

I just upgraded "react-native-navigation" from "1.1.235" to "1.1.351"

And i check versions:

"1.1.250", "1.1.290", "1.1.310", "1.1.330" - Same behavior

---
### Environment
* React Native Navigation version: 1.1.351
* React Native version: 0.49.3
* Platform(s): iOS (at least)
* Device info: iOS 11.2, Iphone 7, Debug

**Comment by hotsen** [comment]
I am having the same issue, even with static navigationStyle ... (RN 0.51.0 / RNN 1.1.354) ... Can't get rid of the iOS elevator ...
