### ISSUE TITLE
White Blank screen when app opened from notification center

### ISSUE THREAD

**Issue by Mubashirkhan** [wix/react-native-navigation#2590]
### Issue Description

On android platform if the app is in background and opened from the notification center app gets stuck on a white blank screen 

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.isAppLaunched()
  .then(appLaunched => {
    if (appLaunched) {
      startApp();
    }
    new NativeEventsReceiver().appLaunched(startApp);
  });
```

---
### Environment
* React Native Navigation version: 1.1.222
* React Native version: 0.48.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both simulator & Device and Debug & Release modes

**Comment by filipef101** [comment]
Try placing this in main activity:

`    @Override
    public View createSplashLayout() {
        View view = new View(this);
        view.setBackgroundColor(Color.TRANSPARENT);
        return view;
    }
`

**Comment by Mubashirkhan** [comment]
the issue is that app gets stuck there or crash when opened from Notification Center. I'm using react-native-push-notification for the push notifications

**Comment by MounirDhahri** [comment]
+1

**Comment by filipef101** [comment]
@MounirDhahri why do you breath?

**Comment by chrise86** [comment]
@Mubashirkhan did you manage to resolve your issue?

**Comment by rodolfoviolac** [comment]
+1
