### ISSUE TITLE
navBarHidden

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#26]
navBarHidden doesn't seem to work, at least not withe @latest.

**Comment by smooJitter** [comment]
Actually it works fine we passed via the navigationStyle object, it doesn't work as a screen prop.

**Comment by talkol** [comment]
The 3 supported ways to pass styles to screens are:

* static navigatorStyle object when the Component is defined
```js
export default class StyledScreen extends Component {
  static navigatorStyle = {
    drawUnderNavBar: true,
    navBarTranslucent: true
  };
```

* when pushing a screen, as the navigatorStyle param dureing the push()
```js
this.props.navigator.push({
  screen: 'example.ScreenThree',
  navigatorStyle: {},
});
```

* as the navigatorStyle parameter when calling startSingleScreenApp
```js
Navigation.startSingleScreenApp({
  screen: {
    screen: 'example.WelcomeScreen',
    navigatorStyle: {},
  },
```

When you say it doesn't work as a screen prop, what do you mean? which option isn't working?

**Comment by smooJitter** [comment]
I misread the API

**Comment by talkol** [comment]
oh, cool :)
