### ISSUE TITLE
error starting up after update to v2.0

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#260]
I'm getting a runtime error after updating to v2.0:
`undefined is not an object (evaluating 'E.RctActivity.startTabBasedApp')`

**Comment by guyca** [comment]
RctActivity doesn't exist in v2. You probably need to clean your gradle cache or sync your project files with gradle

**Comment by DanielZlotin** [comment]
also can help: `watchman watch-del-all && node node_modules/react-native/local-cli/cli start --reset-cache`

**Comment by guyca** [comment]
@DanielZlotin got an alias for that?

**Comment by DanielZlotin** [comment]
@guyca lol. nah.. it's just the `npm run start` script command I use on every project...
The full one is:
`watchman watch-del-all && adb reverse tcp:8081 tcp:8081 && node node_modules/react-native/local-cli/cli.js start --reset-cache`

**Comment by guyca** [comment]
`alias nrs='npm run start` :trollface:

**Comment by DanielZlotin** [comment]
u h4ck3r

**Comment by adamski** [comment]
Sorry guys yes it was an obvious issue... I am sending the js bundle and forget to redo this after the upgrade.
