### ISSUE TITLE
v1.1.354, Android works great, but iOS Build Fails in RNNSwizzles.m

### ISSUE THREAD

**Issue by yangningBU** [wix/react-native-navigation#2602]
### Issue Description

I've transitioned from React Navigation to React Native Navigation and coupled with the [react-native-modal-datetime-picker](https://github.com/mmazzarolo/react-native-modal-datetime-picker) feature, I was able to avoid [an issue](https://github.com/react-navigation/react-navigation/issues/2387) I was experiencing with my DatePicker using React Navigation. The Android build works beautifully and I much prefer the native routing with React Native Ravigation but I can't get the iOS build to pass at all. There are two build errors popping up in Xcode:
```
No visible interface for 'UIScrollView' declares the selector 'setContentInsetAdjustmentBehavior:'
```
and
```
Unexpected '@' in program.
```
<img width="1397" alt="screenshot 2018-01-28 01 36 04" src="https://user-images.githubusercontent.com/4258357/35480340-c9b0c724-03d9-11e8-99ff-cd8d1294933c.png">

I've run Clean in Xcode and tried both `run-ios` and manual building in XCode (my normal way) and I keep getting the same errors. I don't know much about Objective-C but as I understand the second error message could very will be because of an import of a bad file but I don't know where to start looking.

Is this an environment issue (i.e. my fault) or a code issue?

---
### Environment
* React Native Navigation version: 1.1.354
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Mac OSX / Debug

**Comment by marshome** [comment]
me too

**Comment by IsaacWIvins** [comment]
same boat

**Comment by IsaacWIvins** [comment]
What build setting, simulator version, and XCode version are you using? 

For now I'm using IOS 10.2 for the XCode build settings compared to "Latest IOS 10.2", and an IOS 10.2 for the simulator.

I ended up commenting out the "if (@available(iOS 11.0, *))" conditionals which got it working. But I'm going to update XCode and the Simulator later on to see if thats the problem.

**Comment by yangningBU** [comment]
@IsaacWIvins I'm using Xcode 8.2.1, build setting Base SDK is "Latest iOS (iOS 10.2)", and simulator is iPhone 7 running 10.2. Changing the build setting to just 10.2 and not Latest didn't seem to help. I don't like the idea of removing v11 support either but I didn't even see the conditionals to try, what file(s) are they in (grepping gave me nothing)? In any event, I'm sure it's a simple dependency mismatch but I just don't know enough about Xcode or Objective-C / Swift to properly identify it. I'll try upgrading Xcode and simulator and see if that helps.

**Comment by dviluk** [comment]
same problem for me.
I'm using El capitan 10.11.5, xcode 10.2.1, ios 10.2
``
"react-native-navigation": "^1.1.228",
"react-native": "0.48.3",
``

**Comment by yogevbd** [comment]
This will happen in xcode < 9.
Make sure your'e using the latest xcode version

**Comment by yangningBU** [comment]
@yogevbd upgrading to Xcode 9 resolved this issue so thank you for pointing that out! But I do have to say that it's kind of frustrating that I had to upgrade to High Sierra to do so since Xcode 9 is not compatible with El Capitain out of the box.
