### ISSUE TITLE
Subtitle text center alignment for Android

### ISSUE THREAD

**Issue by markedby** [wix/react-native-navigation#2608]
### Issue Description
There is navBarTitleTextCentered property for Android which works great. But the same alignment property for subtitle is currently missing.
I'm desperately need to be able to center navbar's subtitle on Android. Is there any possibility to implement this?

---
### Environment
* React Native Navigation version: 1.1.361
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Android 5.0.2, Debug/Release.

**Comment by Andrei-Vakulski** [comment]
I am also facing this problem. It would be cool to have something like "navBarSubTitleTextCentered" navbar's prop on Android.

**Comment by mkuczera** [comment]
Hi @Andrei-Vakulski , i actually created the pull request for this prop a week ago. Hope this get´s merged soon.
