### ISSUE TITLE
RCTBridge.h file not found when upgrade to v2.0

### ISSUE THREAD

**Issue by musicode** [wix/react-native-navigation#261]
iOS RN30

when I upgrade to v2.0, the error is as below.

![image](https://cloud.githubusercontent.com/assets/2732303/18043264/515da188-6df9-11e6-8992-9521d8647113.png)

I has linked the Library. how to fix it?

**Comment by DanielZlotin** [comment]
Looks like missing `header search path`

**Comment by musicode** [comment]
`header search path` includes
`$(SRCROOT)/../node_modules/react-native-navigation/node_modules/react-native-controllers/ios` and it is `recursive`.

**Comment by DanielZlotin** [comment]
@musicode also make sure you `npm installed` using npm version >= 3.0.0

**Comment by musicode** [comment]
react-native-controllers has merged into this project, so the `react-native-controllers` is under the `react-native-navigation/node_modules`, is it right?

**Comment by DanielZlotin** [comment]
1. it's going to be merged, still not merged.
2. once merged, the header search path should specify: `$(SRCROOT)/../node_modules/react-native-navigation/ios`

**Comment by musicode** [comment]
my npm version is 3.3.12, i install this project by `npm install react-native-navigation@2.0.0-experimental.85 --save`. after installed, the directory is like below:

```
node_modules/
  - react-native-navigation/
      - node_modules
          - react-native-controllers/
```

**Comment by DanielZlotin** [comment]
This is bad. This means you probably have 2 copies of `react-native-controllers`. Delete node_modules and do a fresh `npm install`

**Comment by musicode** [comment]
Thanks.
