### ISSUE TITLE
passProps array of object return [Getter/Setter]

### ISSUE THREAD

**Issue by iCodePup** [wix/react-native-navigation#2612]
### Issue Description

Push new screen with array of Object inside passProps  : 

     let test = [
            {
                foo: "test"
            },{
                foo: "test"
            }
        ]
     this.props.navigator.push({
                screen: 'OtherScreen',     
                passProps: {
                  test: test
                }
            })

**OtherScreen** : 

    console.log(this.props)

**Result** 

    test: [ [Getter/Setter], [Getter/Setter] ],

Why i get [ [Getter/Setter] instead of my object ?

---
### Environment
* React Native Navigation version: ^1.1.354
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): ANDROID
* Device info (Simulator/Device? OS version? Debug/Release?): DEBUG

**Comment by pqkluan** [comment]
This issue is not related to RNN. [It just how Javascript work](https://stackoverflow.com/questions/28072671/how-can-i-get-console-log-to-output-the-getter-result-instead-of-the-string-ge).
