### ISSUE TITLE
Examples For new versions.

### ISSUE THREAD

**Issue by lilitGrigoryan** [wix/react-native-navigation#2614]
### Issue Description
We haven't any example for creating new pages. for example we need push screen, but we didn't know what we must send as a  containerId. Can you send us  any example of container?
 Now we get error " unknown LayoutType name, props"? What must be name and Props.

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]
<img width="284" alt="screen shot 2018-01-31 at 2 53 15 pm" src="https://user-images.githubusercontent.com/17703327/35662402-6446ae98-0731-11e8-9208-6cd6f9c90683.png">

---
### Environment
* React Native Navigation version: V2
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?): IOS, Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by yogevbd** [comment]
We are still working on a new documentation.
This is the simplest layout example:
```js
Navigation.setRoot({
  stack: {
    children: [{
      component: {
        name: 'navigation.playground.TextScreen',
        passProps: {
          text: 'This is screen 1'
        }
      }
    }],
    options: {
      topBar: {
        title: 'Top bar Title'
      }
    }
  }
}

You can also take a look at the example project main file: https://github.com/wix/react-native-navigation/blob/v2/playground/src/screens/WelcomeScreen.js
It contains different layout usages.
