### ISSUE TITLE
Using largeTitle produces two titles

### ISSUE THREAD

**Issue by djschilling** [wix/react-native-navigation#2616]
### Issue Description

I am using the newly introduced (#2593) option `largeTitle` to get the Large Title Bar.
Now i get two titles in the title bar the big one (correct) the old small one (not correct).

### Steps to Reproduce / Code Snippets / Screenshots

This is how i use the new option.
```
const appStyle = {
    largeTitle: true
  };


// this will start our app
Navigation.startTabBasedApp({
  tabs: tabs,
  appStyle: appStyle
});

```

Here a screenshot of how it looks in my app:

<img width="405" alt="bildschirmfoto 2018-01-31 um 21 06 36" src="https://user-images.githubusercontent.com/3503166/35645647-c1bf80b4-06cc-11e8-8533-9b5866881193.png">

---
### Environment
* React Native Navigation version: 1.1.362
* React Native version: 0.52.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iOS11 Debug

**Comment by pqkluan** [comment]
@hammadj @eliperkins 
Could you guys take a look at this issue?

**Comment by frangeris** [comment]
Same here, what's going on?

```javascript
@inject('events')
@observer
export default class Recents extends Component {
  static navigatorStyle = {
    navBarHideOnScroll: true,
    largeTitle: true
  }
...
```
![image](https://user-images.githubusercontent.com/811381/35773641-c2a9414c-0936-11e8-83dc-5e7d3a8a6633.png)

**Comment by hammadj** [comment]
The issue is with this commit: https://github.com/wix/react-native-navigation/commit/3f7f6c26120dea34b298d6940a987b07dbdf9aea#diff-bf319e6382b680d324b4066dabe1377e

Reverting this commit fixes the issue for me. I didn't notice this when I made my PR since I had an older version of react-native-navigation at the time.
