### ISSUE TITLE
overrideBackPress make BackHandler.exitApp() not work

### ISSUE THREAD

**Issue by sapjax** [wix/react-native-navigation#2619]
### Issue Description

I run my app with `startTabBaseApp`,  and set one tab `overrideBackPress`,   then there is no way to exit app from this tab screen.

```javascript
 Navigation.startTabBasedApp({
    tabs: [
      {
        label: 'browse',
        screen: 'Discovery',
        icon: icon.tabDiscover,
        overrideBackPress: true,
      },
      ...
    ]
})
```

---
### Environment
* React Native Navigation version: 1.1.365,
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by pqkluan** [comment]
This is an upstream issue that conflict with the RNN.
Since the RN team rely on Android Back Button event to exit the app and RNN is overriding that event handler from native code.
The solution is to create a native function that actually exits the app.
You use [this](https://github.com/noitq/react-native-exit-app) lib for that job.

**Comment by raynor85** [comment]
I had a similar problem with the modal, and to solve it I needed to write the following code inside the component INSIDE the modal:

`  constructor(props: Props) {
    super(props);
    this.destroyNavigatorEvent = this.props.navigator.addOnNavigatorEvent(this.onNavigatorEvent);
  }
  
  componentWillUnmount() {
    this.destroyNavigatorEvent();
  }
  
  onNavigatorEvent = (event: NavigatorEvent) => {
    if (event.id === 'backPress') {
      BackHandler.exitApp();
    }
  }`

Maybe you can try to use this boilerplate inside the 'Discovery' screen? I haven't tried it with a navigator component, but it is definitely working for a modal opened with overrideBackPress: true

**Comment by feliperregomt** [comment]
Eu tentei agora usar esse `overrideBackPress` mas não resolveu o meu problema.
