### ISSUE TITLE
How to push new Screen?

### ISSUE THREAD

**Issue by lilitGrigoryan** [wix/react-native-navigation#2623]
### Issue Description
I was try this, but isn't push the screen.
 Navigation.push(this.props.componentId, {
	    component: {
	       name: 'navigation.playground.management',
		  options: {
			animated: false
		 }
	});

---
### Environment
* React Native Navigation version: 2.0
* React Native version: 0.52
* Platform(s) (iOS, Android, or both?): Ios ,Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by jeroenbourgois** [comment]
See the [documentation](https://wix.github.io/react-native-navigation/#/screen-api?id=pushparams), this is not correct.

**Comment by pqkluan** [comment]
Check the [example project](https://github.com/wix/react-native-navigation/tree/master/example) and the document.

**Comment by dviluk** [comment]
it says "React Native Navigation version: 2.0"

**Comment by lilitGrigoryan** [comment]
Yes thanks it work :)
