### ISSUE TITLE
White flashing in top-right corner when pushing between two navBarHidden screens

### ISSUE THREAD

**Issue by JuoCode** [wix/react-native-navigation#264]

**Comment by bbrock25** [comment]
I noticed this as well when launching a modal with nav bar hidden.

**Comment by guyca** [comment]
Thanks for reporting. On which platform did you notice this?

**Comment by MattDavies** [comment]
Interesting - I've had this for a while on iOS, needed https://github.com/MattDavies/react-native-controllers/commit/fb5dec7d4e53026cd11617ac86b093e4397c0df0 to resolve it. Haven't seen flickering on Android (I have navBarHidden on all screens).

**Comment by bbrock25** [comment]
@guyca iOS.

**Comment by JuoCode** [comment]
@guyca On iOS, It is easy to reproduce when set a dazzling background color

**Comment by JuoCode** [comment]
@MattDavies Awesome! It can resolve this. But I still have a little doubt, why not `Create a new ReactView with user defined styles direct`.


0. Navigator takes the registered component
1. Create a new ReactView **with user defined styles**, <del>which has by default backgroundColor white!</del>
2. Applies the navigation<Here we see the flickering>
3. <del>React styles will get applied</del>

**Comment by grundmanise** [comment]
Still an issue on iOS with dark backgrounds

**Comment by Soraph** [comment]
Any news about?
