### ISSUE TITLE
Detox failed to await device.setOrientation

### ISSUE THREAD

**Issue by yogevbd** [wix/react-native-navigation#2646]
This is blocking the migration of detox in android

**Comment by guyca** [comment]
Orientation was implemented on Android, but now one test fails on iOS. Can you pick this up in https://github.com/wix/react-native-navigation/tree/detoxAndroid branch? Thanks.

**Comment by Cool04ek** [comment]
Sure. I’ll check it tomorrow.

Best regards,
Roman Kozlov

**Comment by guyca** [comment]
Not a bug, detox `await`s fine. The true issue is that it doesn't rotate device and instead changes orientation of the activity directly which breaks our api. Communicated this to detox team and will continue in #2792
