### ISSUE TITLE
Get current Activity in SimpleViewManager (Android)

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#265]
I seem to be in a conundrum with my codebase, I have updated to v2.0 (which fixed a few Android issues, thanks!) but the new system has broken my reference to the current Activity (which was `MainActivity`, passed into the `SimpleViewManager` constructor). RN 0.31 introduced, with [issues](https://github.com/facebook/react-native/issues/9310) that seem to have been fixed in 0.33 the ability call `getCurrentActivity` from `ThemedReactContext` - however it looks like we need to wait for RNN to update to the latest RN versions. 

Is there another way I can get the current Activity context or pass it into a `SimpleViewManager` class with RNN v2.0? 
I'm currently on RN 0.28.

**Comment by adamski** [comment]
Think I found a solution: wrap my native component in a`ReactContextBaseJavaModule` where I can get the current Activity and use that in the `SimpleViewManager` class.

**Comment by adamski** [comment]
Yes you're right, although there are some cases where the current `Activity` needs to be passed to the object creating the view, in my case the underlying object should know what the current Activity is, as there are certain JNI methods that could be called that depend on the activity, e.g. to show dialog boxes, set requested orientation. 

It seems however that for creating a `View` instance, `ThemedReactContext reactContext` is enough to pass into the `View`s constructor. And this should be enough for my needs atm. 

I think my issue lies elsewhere, I need to pull apart the dependency on the initial `Activity` in the class that interacts with the JNI layer in my app, with regard to creating the native view.

**Comment by DanielZlotin** [comment]
@adamski exactly, try to decouple the dependencies. If you still find yourself needing the activity I'm sure we'll find some solution.
