### ISSUE TITLE
TabBarHidden: true do not work after opening Modal 

### ISSUE THREAD

**Issue by araienko** [wix/react-native-navigation#2653]
### Steps to Reproduce
1. Launch tabBasedApp (for all tabs tabBarHidden : true - works correctly from the start)
2. Open modal . 
3. Dismiss modal.
4. there is black line at the bottom of the screen

Problem appears only with Modal screens (LightBox works fine) and only for the latest iOS versions.
On 10.x iOS works fine (same device)

What I've tried :
```
navigator.showModal({
  screen: 'Home',
  navigatorStyle: {
    tabBarHidden: true,
  }
})
```

for the Modal screen : 
```
componentWillUnmount() {
  this.props.navigator.toggleTabs({to: 'hidden'});
}
```

what helped :
```
this.props.navigator.setOnNavigatorEvent(() => this.props.navigator.toggleTabs({to: 'hidden'}))
```

but anyway seems like a bug
---
### Environment
* React Native Navigation version:  "1.1.365"
* React Native version: "0.50.4"
* Platform(s) (iOS, Android, or both?): "iOS"
* Device info (Simulator/Device? OS version? Debug/Release?): Device, OS 11.2.5 ,Debug and Release

**Comment by L-Yeiser** [comment]
This is still an issue can it be re-opened?

**Comment by keremcubuk** [comment]
I have same problem but in different status.

1 - Open modal and tabbarhiden: true
2- Open lightbox in modal and tabbarhidden: true not works.

When I follow these steps. Tabbar is showing with lightbox but I want to hide it.

**Comment by djkdeveloper** [comment]
@araienko do you solve your problem？ i have then same problem

**Comment by keremcubuk** [comment]
> @araienko do you solve your problem？ i have then same problem

No, the problem still continues. Updates and others solutions not working.
