### ISSUE TITLE
Prevent navigating twice when clicking a button quickly

### ISSUE THREAD

**Issue by Fernando-Parise** [wix/react-native-navigation#2655]
Good Morning!
I have a problem with my Android / IOS application. clicking the buttons or listview several times
the same screen is opened several times.
Does anyone know how to solve this situation?

This is my source code:
[código fonte.txt](https://github.com/wix/react-native-navigation/files/1698963/codigo.fonte.txt)

**Comment by tokict** [comment]
Is it a problem on real device?

**Comment by Fernando-Parise** [comment]
Yes. it a problem on real device

**Comment by tokict** [comment]
Lodash _debounce function can be used to ignore double taps for x milliseconds

**Comment by wd** [comment]
Just write a method could done this:

1. Add a global var `screens = []`
2. Add `push` `pop` methods in your screen like
```
push = (screenName) => {
   if(screenName == screens[screens.length -1])
      return

   screens.push(screenName)
   this.props.navigator.push({})
}

pop = () => {
   screens.pop()
   this.props.navigator.pop()
}
```
3. When you need to do navigating, use `this.pop()` and `this.push()`.

Wish this will help you out.

**Comment by Fernando-Parise** [comment]
Thank you, it worked.

**Comment by DavitVosk** [comment]
@wd thanks for your answer. But what if the user swipes the screen manually, I mean without using `pop` method. Then how can we handle the solution?

**Comment by DucAnhPhi** [comment]
The most simple solution would be to wrap the button in a custom component which debounces the onPress event. Here is an article which exactly describes how: https://medium.com/@devmrin/debouncing-touch-events-in-react-native-prevent-navigating-twice-or-more-times-when-button-is-90687e4a8113

**Comment by ahtesham-shah** [comment]
> Just post a way could done this:
> 
> 1. Add a global var `screens = []`
> 2. Add `push` `pop` methods in your screen like
> 
> ```
> push = (screenName) => {
>    if(screenName == screens[screens.length -1])
>       return
> 
>    screens.push(screenName)
>    this.props.navigator.push({})
> }
> 
> pop = () => {
>    screens.pop()
>    this.props.navigator.pop()
> }
> ```
> 
> 1. When you need to do navigating, use `this.pop()` and `this.push()`.
> 
> Wish this will help you out.

Thanks, its working for push when I am clicking back button it automatically pops the last screen then where to write pop's code.

**Comment by LozytskyiA** [comment]
Will this be implemented(fixed) by wix/react-native-navigation team?
