### ISSUE TITLE
FR: Set default lightbox styling for whole app

### ISSUE THREAD

**Issue by brunolemos** [wix/react-native-navigation#2659]
Feature request:

- Allow setting global default style to all lightbox (similar to `appStyle`, `navigatorStyle`, `tabsStyle`).
- Also a static property on screen, e.g. `static lightBoxStyle = {}` (similar to `navigatorStyle`)

Currently I'm setting `style` every time I call `showLightBox`, not sure if there's other way.

**Comment by guyca** [comment]
Hey @brunolemos 
We realised the lightbox api can't be generic enough to satisfy everyone's needs, so we removed it from v2.
Instead, we provide an `Overlay` api which will allow you to place react views anywhere on the screen, consume all touch events or let touch events pass through to underlying views. An Overlay can even be persistent on the screen (Push won't dismiss it)
As we are not supporting Lightbox anymore, I'm closing the issue. Sorry for the inconvenience.

**Comment by brunolemos** [comment]
I love v1 lightboxes (the blur, the animation, the tap outside, etc), I migrated all popups to it.
Didn't check v2 Overlay yet, hopefully it's great too :)

**Comment by guyca** [comment]
@brunolemos 
It will require a little bit more work on the users side, but it's worth it. For example, You'll need to require `react-native-blur` and apply the blur effect yourself - Obvious upside is it will allow you to fully customise it.
