### ISSUE TITLE
Prevent Android push notifications from relaunching app when closed

### ISSUE THREAD

**Issue by tmaly1980** [wix/react-native-navigation#2663]
I'm working with a project that utilizes react-native-push-notification, and noticing an issue with Android, where the app will launch if it's closed when a notification gets received. 

There had been some discussion here about switching over to react-native-notifications, https://github.com/wix/react-native-navigation/issues/566, but also a semi-discussed solution to work around the issue. We're already very much invested in this library so we don't want to switch over to the wix version.

Effectively, this is what I have come up with, but there's a missing piece to determine whether or not the code was called from a push notification. 

index.android.js:

```
import { Navigation, NativeEventsReceiver } from 'react-native-navigation';
import { registerScreens } from './app/screens/registerScreens';
import logInNavigationConfig from './app/screens/logInNavigationConfig';

registerScreens();


function appOpenedFromPushNotification() {
    return false // ??? What goes here ???
}

Navigation.isAppLaunched()
  .then(appLaunched => {
    if (appLaunched || appOpenedFromPushNotification()) {
        startApp();
    } else {
        new NativeEventsReceiver().appLaunched(startApp());
    }

  });

function startApp() { // Start the app
    Navigation.startSingleScreenApp(logInNavigationConfig);
```

https://github.com/wix/react-native-navigation/issues/566#issuecomment-327404439 refers to appOpenedFromPushNotification(), but that was never actually discussed anywhere.

What am I missing?

**Comment by oscar-omana** [comment]
why would you close an issue for which there has not been an answer or a way to fix it?
