### ISSUE TITLE
Elements still clickable under Drawer

### ISSUE THREAD

**Issue by joecaraccio** [wix/react-native-navigation#2665]
I have noticed elements remain clickable under the Drawer. For instance, if I have a drawer open, and am only clicking on the area enclosed by the drawer, I can still trigger touchable events underneath the drawer. Elements such as TouchableOpacity, despite being underneath the drawer view will still be triggered, if that makes sense.

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots
Simple Tab bar Drawer, set to be full width
---
### Environment
* React Native Navigation version: 1.1.366
* React Native version: 0.49.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Google Pixel 2 (AVD) Simulator

**Comment by tokict** [comment]
I am using the same versions and when drawer is activated, nothing can be tapped. Maybe your zIndexes are strangely set up
