### ISSUE TITLE
Custom viewController

### ISSUE THREAD

**Issue by yogevbd** [wix/react-native-navigation#2667]
```js
Navigation.push(this.props.componentId, {
  externalComponent: {
    name: 'LoginScreen', // A unique name used by `ExternalComponentCreator` to create the native screen
    passProps: { age: 20 }
  }
})
```

**Comment by guyca** [comment]
@DanielZlotin @yogevbd Is this api correct? A Controller/Fragment isn't a component.
a `component` is a leaf - a React view, therefore it must contain a `name`.

I thought the api would look something like this:
```js
externalComponent: {
  className: '', // Fully qualified class name
  passProps: {}
}
```

**Comment by yogevbd** [comment]
👍  Updated

**Comment by guyca** [comment]
Seems like the v1 implementation requires a "controller creator name" which is actually a more correct approach.
Lets rename `className` to `classCreator` which will be a fully qualified method name, invoked using reflection which returns a `Fragment` on Android and a `Controller` on iOS.

@yogevbd @DanielZlotin Please ack and of course feel free to suggest a more suitable name.

**Comment by DanielZlotin** [comment]
I have another suggestion:
Register (in native) the creator (which will implement a protocol) then
just use the registration key in js.

**Comment by guyca** [comment]
Sounds good 👍

**Comment by guyca** [comment]
@yogevbd, I've created a PR for android https://github.com/wix/react-native-navigation/pull/2846
e2e is broken on iOS as I've changed `className` to `name`.
Basically, there's no need to create the component with reflection - as @DanielZlotin suggested we can register a creator function which will create the component corresponding to the given `name`.
