### ISSUE TITLE
Clean up example projects (there should only be one)

### ISSUE THREAD

**Issue by DanielZlotin** [wix/react-native-navigation#267]
There should be a single example project, which will be updated regularly, both on iOS and Android, and all (main) features are implemented in it. It should also be well documented.

On top of that, any special integration with the library should be done outside this example project. Maybe a bunch of showcase apps (one with redux, one with mobx, etc)

**Comment by derdav3** [comment]
Also: in readme-gif there's a search function in the header - would be great to see how that's implemented.
