### ISSUE TITLE
Prevent drawer close gesture from stealing events

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#2671]
### Issue Description

I have a modal screen with swipe-to-reveal sections. I'd like to move it to a drawer, but the drawer close action steals all the gestures. Is there a way to prevent this?

A crude way might be to have `disableCloseGesture`. Ideally, it would only respond to touches starting at the opposite edge to the side of the drawer.

### Steps to Reproduce / Code Snippets / Screenshots

Add left side drawer with a screen containing e.g. `SwipeListView` components ([react-native-swipe-list-view](https://github.com/jemise111/react-native-swipe-list-view))

---
### Environment
* React Native Navigation version: 1.1.365
* React Native version: 0.46.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iOS 11, Debug

---
Also posted on SO: https://stackoverflow.com/questions/48625147/how-to-prevent-drawer-close-gesture-from-stealing-events

**Comment by zarvedan** [comment]
@adamski Did you find an alternative / workaround ? I'm experiencing the same issue on IOS...

**Comment by adamski** [comment]
No, I didn't, I am using a modal at the moment instead of a drawer. I'm hoping to be able to move to a drawer soon once there is a workaround.

**Comment by jdegger** [comment]
Any workaround available for V1? Is this solved in V2? We have not upgraded yet.
