### ISSUE TITLE
Intercept navigation events like back button press and tab press

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#268]
This will allow us to respond to these events and optionally consume them.

**Comment by grundmanise** [comment]
Any progress on this guys?

**Comment by wremacle** [comment]
Interested too. Thanks.

**Comment by rgoren** [comment]
Interested too. Thanks.

**Comment by fabryx92** [comment]
Interested too. Thanks.

**Comment by nicoara** [comment]
interested

**Comment by brenwell** [comment]
Me too. Thanks!

**Comment by guyca** [comment]
Handling back button press can be done using [BackHandler](https://facebook.github.io/react-native/docs/backhandler.html), handling BottomTabs press will be addressed in #2766
