### ISSUE TITLE
Can't center subtitle in nav bar on Android

### ISSUE THREAD

**Issue by davidliu** [wix/react-native-navigation#2681]
### Issue Description

Can't center subtitle in nav bar on Android. There exists a navBarTitleTextCentered, but it does not center the subtitle, and there doesn't exist a corresponding navBarSubtitleTextCentered.

### Steps to Reproduce / Code Snippets / Screenshots

    static navigatorStyle = {
      navBarTitleTextCentered: true, // works
      navBarSubtitleTextCentered: true, // doesn't work
    }
---
### Environment
* React Native Navigation version: ^1.1.371
* React Native version: 0.52.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel 1, version 8.1.0

**Comment by mkuczera** [comment]
@davidliu : Resolved in 1.1.378 
Can be closed @guyca
