### ISSUE TITLE
Android app restarts when opening push notification

### ISSUE THREAD

**Issue by miguelespinoza** [wix/react-native-navigation#2682]
I'm working on a project that uses `react-native-notification` on Android.  When I open a push notification it opens the app but I notice that the SplashActivity displays for a couple of seconds.  Effectively, it restarts the app instead of resuming the app.

Here's how to reproduce:
1. Open app from launcher or appDrawer
2. Go home
3. Send notification and open
4. It creates a new `SplashActivity` and destroys the old `NavigationActivity`
5. Causing an unnecessary app restart

One thing to note, if the app is started from a push notification the app works fine for any subsequent notifications (resumes every time instead of restart)
It's only when you start app from launcher or appDrawer.

I found a solution that short-circuits the app restart:
```
public class MainActivity extends SplashActivity {
@Override
  protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    if (!isTaskRoot()) {
      finish();
      return;
    }
  }
}
```

here's the link for reference: https://stackoverflow.com/questions/7944338/resume-last-activity-when-launcher-icon-is-clicked

What are your thoughts on that? This feels like a hacky solution, and can't tell if it's `react-native-navigation` or `react-native-notificaton`

**Comment by noambonnie** [comment]
@miguelespinoza This is extremely helpful. My case is slightly different than yours. The splash activity appears forever (or until I press the back button). But your workaround seems to work. 

The problem appears to be with react native navigation - I'm using a different library for notifications and I have the same problem. I'm not an android developer and therefore have no idea what are the consequences of it. Have you tested it thoroughly enough?

**Comment by miguelespinoza** [comment]
Hi @noambonnie, no consequences with this change.  Simply if the Activity is not TaskRoot that means an Activity exists already that is TaskRoot.  It's a safe solution, for a bug that's been existing since Android 1.0.

It definitely has been tested, it's been out in the wild with no side-effects reported from the fix 😄

**Comment by ronilitman** [comment]
Adding android:launchMode="singleTask" to AndroidManifest.xml under MainActivity solved the issue for me.

**Comment by ldh1428a** [comment]
In my case `android:launchMode="singleInstance"` add to `AndroidManifest.xml` 

It work for me !  😆😆😆😆😆

**Comment by ldh1428a** [comment]
In my case android:launchMode="singleInstance" add to AndroidManifest.xml

It work for me ! 😆😆😆😆😆

**Comment by coolprinze** [comment]
> In my case android:launchMode="singleInstance" add to AndroidManifest.xml
> 
> It work for me ! 😆😆😆😆😆

This work for me

**Comment by vineethvijayan314** [comment]
Issue is still happening I have tried singleInstance and singleTask both didn't work

**Comment by TwistedMinda** [comment]
"singleInstance" works for normal notifications, but Rich Push Notifications will force a restart of the app.
Any workaround?

**Comment by nervouscat** [comment]
I'm trying to make it work as well. though **singleInstance** and **singleTask** aren't working. I'm currently using it with 
**react-native-bootsplash** and **react-navigation**. are they the cause?

I couldn't find a workable solution so far

**Comment by ilight** [comment]
Sharing in case anyone is still facing issues where App relaunches on clicking an Android notification

My issue was - I post a local notification when Android received a remote push and app is on foreground. Clicking on it restarts the App entirely.

https://gist.github.com/ilight/be7141f45f15e39b6fccfe46ca6e3829
