### ISSUE TITLE
Is it possible to use react-native-vector-icons at Tabbar? [QUESTION]

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#269]
I would like to ask if it's possible to use this package (https://github.com/oblador/react-native-vector-icons) for icons in the Tabbar, and if yes, how can I do it?

Another question, is if it's possible to reduce the tabbar height and use only an icon and no label, just like facebook and airbnb's new app.

**Comment by tkporter** [comment]
It's actually shown in the main [README.md](https://github.com/wix/react-native-navigation#react-native-vector-icons)

As far as icon and no label, I'm not entirely sure

**Comment by guyca** [comment]
By default, on Android only the label of the selected BottomTab is displayed. If you want all labels to be visible pass `forceTitlesDisplay: true` to `appStyle`
regarding iOS, tab labels are always visible but you'll be able to control that in future version.
