### ISSUE TITLE
Icons in release apk are too Big in ANDROID

### ISSUE THREAD

**Issue by witalobenicio** [wix/react-native-navigation#2698]
When I'm testing on my device (via localhost) icons are just fine, but when I assemble my release apk, icons in Navbar are just enormous.

**Comment by guyca** [comment]
Perhaps this https://github.com/wix/react-native-navigation/issues/43#issuecomment-267370982 will help

**Comment by witalobenicio** [comment]
@guyca I'm not using vector icons. Just sizes for @1x and @2x (36px and 72px for android).
