### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by ZoharLiran** [wix/react-native-navigation#27]
Hi guys,
First of all thank you for developing what seems to be an awesome tool. 
I am having trouble starting it up since once I follow the instructions on your site the simulator won't start the app and just shows a black screen. 
you can see it in the following repo:
https://github.com/ZoharLiran/ReactTodo/commits/master

the last commit is the one with the changes in the instructions. if you checkout the prior commit the app works.

The only thing I see in the debugger is:
`RCTLog.js:38 Unbalanced calls start/end for tag 0`
my `Pause on Caught Exceptions` is turned on but there are no exceptions.

If that helps, I am running your `exmple-redux` successfully.

I am using npm v3.9.1
Thank you

**Comment by madvas** [comment]
I also get an error `RCTLog.js:38 Unbalanced calls start/end for tag 13`

**Comment by guyca** [comment]
Are you still getting this error? We've updated the library to use react-native v0.25.1. Can you check again using v1.0.1?
Thanks

**Comment by carbon-via** [comment]
Same problem, with all latest versions =(

**Comment by guyca** [comment]
@CarbonC Which example project did you try to run? iOS or Android?

**Comment by CarbonC** [comment]
@guyca It is IOS.... But in the example i read too fast, and forgot to delete the specified part...
