### ISSUE TITLE
[v2] passProps for topBar buttons not working

### ISSUE THREAD

**Issue by jeprojects** [wix/react-native-navigation#2706]
### Issue Description

I am trying to add a component for one of the `leftButtons` in the `topBar` but it won't pass the props needed for the component. I only get this:

componentId
rootTag

### Steps to Reproduce / Code Snippets / Screenshots

```
topBar: {
  title: 'Main',
  textColor: 'white',
  textFontSize: 16,
  backgroundColor: 'black',
  leftButtons: [{
    component: 'navigation.Icon',
    passProps: {
      name: 'menu',
      size: 24,
      color: 'white'
    },
    title: 'action',
    id: 'bebeb'
  }]
}
```

---
### Environment
* React Native Navigation version: 2.0.2124
* React Native version: 0.53.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by yogevbd** [comment]
Fixed in #2878
