### ISSUE TITLE
Clearing Redux with starting new singleScreenApp

### ISSUE THREAD

**Issue by iksent** [wix/react-native-navigation#2707]
### Issue Description

I have a Redux with its store (and data in it) and screens in TabBasedApp.

Then I want to reset stack to single screen app (make logout to Login page), so I call "Navigation.startSingleScreenApp", and in "then" of it I make dispatch to reset store data. And I get a lot of errors, because screens in TabBasedApp are in render too for some strange reason (I guess that because of asynchronous functions).

So how can I achieve redux clearing with starting new singleScreenApp and getting no errors?

### Environment
* React Native Navigation version: "1.1.351"
* React Native version: "0.49.3"
* Redux version: "3.7.2"
* Platform(s): Android at least
* Device info: Real Device, Android 7.0.1, Debug and Release

**Comment by guyca** [comment]
You can `await Navigation.startSingleScreenApp`
When startSingleScreenApp resolves, previous screens are already unmounted and destroyed.

**Comment by iksent** [comment]
Hello, @guyca.

As I mentioned before - I made Redux clearing in `then` block of `Navigation.startSingleScreenApp`.
Like: 
`Navigation.startSingleScreenApp({ /* options */ }).then(() => { /* Redux dispatch for clearing */ })`

Is this not equivalent of `await`?

**Comment by karlmosenbacher** [comment]
@iksent are you running your application on simulator or device? If device, are you running on Ios simulator? And how does your index.ios.js look like?

Mine looks like this:

import App from './App';
const app = new App();

but it does not work, and my App.js is a class which extends React.Component.
Currently working with react-native 0.51

**Comment by iksent** [comment]
@karlmosenbacher, how are your questions related to this problem?

**Comment by iksent** [comment]
@guyca, can you reply on my last question, please?

**Comment by guyca** [comment]
Hey @iksent , sorry for not responding.

these are definitely the same. In the Wix app, before major change we broadcast an event async, modules in the app can handle the event as they see fit (clear state if they want) and actual app proceeds to calling `start*App()` without waiting.
In some cases, mostly when we need to fetch data from server, we show a loader/empty state screen until requests complete.
That's mostly it... no real magic here.

**Comment by yershalom** [comment]
Hi @iksent ,
Is @guyca answered your question?
Can I close this issue?

**Comment by danilobuerger** [comment]
@yershalom @guyca I don't think this is answered as even with `await Navigation.startSingleScreenApp` the previous screens are actually not destroyed and errors are still happening

**Comment by masterpetit** [comment]
Awaiting the startSingleScreenApp() does not solve the problem.

**Comment by danilobuerger** [comment]
Our solution, for now, is to just use a new store each time. So every time we want to reset everything (user logs out) we create a new store, and re-register the components with the new store, then start.
