### ISSUE TITLE
Preventing "double tap" transitions?

### ISSUE THREAD

**Issue by willks** [wix/react-native-navigation#271]
Not sure this is an issue, or just something I've encountered. I'm using Redux fully (for all state management) - and I've found and issue in my app that's usually a symptom during the "debug" stage of my app. It's a photo heavy app, and sometimes during background processing, the UI becomes "frozen". However, all controller "transition" taps are remembered, which results in a new screen being "pushed" multiple times. I've implemented the redux "debounce" mechanism, but this seems to have no effect when buttons are pressed multiple times during one of these application pauses.

Is there a recommended approach to prevent the "double tap" transitions?

Thanks

**Comment by DanielZlotin** [comment]
Yes we know this problem all too well. This is not a `react-native-navigation` problem, and not event a `react-native` problem. This is a multithreading problem. 

`tl;dr`: clicks are fired on the main (ui) thread that dispatch some async action that takes time to complete - in another thread. By the time the action completes, more clicks come-in. This an age old issue. There are a couple of ways to deal with it, and we need to think of the best way for us. I'll try to implement some clever mechanism in 2.0.0 here: (a work in progress) #255 .

The way I see it, we have 2 options.
1. as soon as an action comes in, we disable the button for clicks, until someone reenables it
2. we try to be more clever than that, and try to detect push/showModal events which are "duplicate". this is what #255 tries to do.

The issue here is by the time the JS receives the command to push and sends the push to native, it's already too late to block the button, as there can be multiple touches already on their way through the bridge to JS.  
The only safe option is to block the commands in native (before they reach JS). But this is a problem, because only the JS knows what button does what. This is a pickle.

At first I tried to just specify `_.throttle()` in JS on all `push` and `showModal` commands. This didn't work well, to say the least, as there are places where you WANT to do multiple pushes. (for example, a push notification comes in and you want to delve deep into a stack of views).

So we thought about making this mechanism more clever: remember the parameters for the push, and only ignore those that are exactly the same, and also allow this mechanism to be *optional*, and *configurable*. We still need to research it and decide if this is good enough.

**Comment by willks** [comment]
Thanks for the very descriptive explanation of the problem. As part of my original post, I exposed my own ignorance of the redux debounce and it's purpose! I've managed to work around things by having my own rudimentary debounce for buttons, but it's not really working well as I can't determine the time longer requests make. Lucky for me, it seems there are no issues on the actual device but I do appreciate your in-depth response. I use a lot of WIX frameworks (Scala and React Native) - I appreciate yours and your company's efforts.

**Comment by willks** [comment]
Small response to your last sentence, yes I dispatch all heavy processing in ObjC and Swift using GCD - the issue is that some users may select 100+ photos, so I have to pre-warm the cache for displaying in main view - this is for generating thumbnail images, which drains the device CPU. This results in sluggy performance only in the simulator - but I've been lucky that the 6/6s flies through the operations and doesn't actually cause a block to happen. There's numerous background activity too - like generating JPEG images of the photo library and uploading (using background sessions) to cloud provider . My issue just seems due to debugging issues. But like I said, appreciate your efforts as the double tap scenario can definitely occur if the user fast enough. I've only had it happen once on the device, and it was during debugging mode. 

Thanks - feel free to close this issue as it's already in consideration and being worked on.

**Comment by DanielZlotin** [comment]
Another side note, check out the differences between debounce and throttle: http://drupalmotion.com/article/debounce-and-throttle-visual-explanation

We'll close as soon as it's resolved :) - that way you can keep track of the issue.

**Comment by willks** [comment]
I've been reading that this is also an issue on iOS in general, and the way to overcome it is to check whether the latest controller in the stack as the same as the one being pushed. I can't find a reference to that one, but I did stumble on another solution that prevents any transitions while other transitions are in progress: http://stackoverflow.com/questions/27111960/ios-is-there-currently-a-way-to-prevent-two-view-controllers-being-pushed-or-po

Either way, I haven't had time to experiment with the sources to check wether any of these are viable solutions but thought I'd check in. However, I've seen your solution about preventing transition if the props are the same, which could be a much quicker fix (without delving into native controller territory)

**Comment by littlesome** [comment]
What about add a 'single instance' mode? Screen marked as single instance should be only opened once, if it was already opened in stack, steal it and move to top.  It's a common use case in my app, will this be offically supported?

**Comment by SudoPlz** [comment]
I'm just using a throttle function to throttle all my taps. I don't want code running 2 times anyway.

```javascript
    export function throttle(func, wait, ctx, immediate = true) {
      let timeoutRefId;
      let args;
      let context;
      let timestamp;
      let result;

      const later = () => {
        const last = timestampNow() - timestamp;

        if (last < wait && last >= 0) {
          timeoutRefId = setTimeout(later, wait - last);
        } else {
          timeoutRefId = null;
          if (!immediate) {
            result = func.apply(context, args);
            if (!timeoutRefId) context = args = null;
          }
        }
      };

      return () => {
        context = ctx || this;
        // eslint-disable-next-line prefer-rest-params
        args = arguments;
        timestamp = timestampNow();
        const callNow = immediate && !timeoutRefId;
        if (!timeoutRefId) timeoutRefId = setTimeout(later, wait);
        if (callNow) {
          result = func.apply(context, args);
          context = args = null;
        }

        return result;
      };
    }
```

**Comment by royendgel** [comment]
@SudoPlz Great ! with timestampNow() you mean this ? 
function timestampNow() {
        return + Date();
    }

**Comment by SudoPlz** [comment]
Woops I forgot to mention that. In using a library called performance now https://www.npmjs.com/package/performance-now

So 
`import timestampNow from 'performance-now'`

**Comment by sintylapse** [comment]
You can just use a higher order component for that purpose

```
function preventNavStackDuplicate(Component){
    return class PreventNavStackDuplicate extends React.Component {

        componentDidMount(){
             this.props.navigator.setOnNavigatorEvent(event => {
                 if (event.id === 'didDisappear') {
                    this._navigated = null
                 }
             })
        }

        _navigated = null

        navigateTo = screenOptions => {
            if (!this._navigated) {
                this.props.navigator.push(screenOptions)
            }

            this._navigated = true
        }

        render(){
            return <Component {...this.props} navigateTo = {this.navigateTo} />
        }

    }
}
```
- wrap your screen with it `export default preventNavStackDuplicate(MyBeautifulScreen)`
- then, in your screen component, just use `this.props.navigateTo({screen: 'SomeScreenId'})`, and it will automatically prevent unnecessarily navigation pushes.

**Comment by filipef101** [comment]
@DanielZlotin can you also make your PR do the same for show modal, and show lightbox?

**Comment by ReggaePanda** [comment]
https://github.com/wix/react-native-navigation/issues/271#issuecomment-345432064
this only works for android, iOS doesn't work #2676

**Comment by LuckyCrab** [comment]
I modified my reducer and this works for me (in addition I use nested navigation):

    export default (state = initialNavState, action) => {
      let nextState,
          nextStateDefault = RootNavigator.router.getStateForAction(action, state),
  
      switch (action.type) {
          case 'Navigation/NAVIGATE':
              nextState = nextStateDefault;
              // <prevent "double tap" navigation>
              if(state.isTransitioning) {
                  nextState = state;
              }
              nextState.isTransitioning = true;
              // </prevent "double tap" navigation>
              break;
          ...
          ...
          ...
          default:
              nextState = nextStateDefault;
              break;
      }
      return nextState || state;
    }

**Comment by LuckyCrab** [comment]
I have changed my previous solution to:

    const doubleTapTimeoutMs = 500;
    ...
        switch (action.type) {
            case 'Navigation/NAVIGATE':
                nextState = nextStateDefault;
                // <prevent "double tap" navigation>
                state.timestamp && (Date.now() - state.timestamp <= doubleTapTimeoutMs) && (nextState = state);
                nextState.timestamp = Date.now();
                // </prevent "double tap" navigation>
                break;

**Comment by ReggaePanda** [comment]
is it possible to fix the events for iOS?

**Comment by filipef101** [comment]
ios its not an issue. android only. if you want a solution set a timeout of 200ms on your navigation buttons/events

**Comment by ReggaePanda** [comment]
@filipef101 i have the same issue on iOS and the wix works for android.
on iOS `didDisappear` is not fired and so the workaround doesn't work :/

**Comment by filipef101** [comment]
@DavitVosk Its not a problem, and is very weird that you get that on iOS, is it on release? what you can do is set a timeout like said before

**Comment by filipef101** [comment]
@willks close this issue no?

**Comment by DavitVosk** [comment]
You don't get that problem @filipef101 on IOS?

**Comment by filipef101** [comment]
On release I do not, also V1 btw

**Comment by DavitVosk** [comment]
Can you please show which code has fixed that problem here?

**Comment by DavitVosk** [comment]
I mean in package...
