### ISSUE TITLE
[v2] topBar onNavigationButtonPressed not called when using component

### ISSUE THREAD

**Issue by jeprojects** [wix/react-native-navigation#2710]
### Issue Description

I have configured the leftButtons[] to get a component (svg button), instead of the standard 'icon/title'.

When doing this, it doesn't fire onNavigationButtonPressed. Shouldn't it still do this for a component based topBar button? It works for a 'icon/text' based button in the topBar.

### Steps to Reproduce / Code Snippets / Screenshots

The first button (id: sideMenu) will not fire onNavigationButtonPressed, but the second button (id: BUTTON_ONE) fires the callback fine.

```
leftButtons: [
  {
    id: 'sideMenu',
    testId: 'sideMenu',
    component: 'navigation.icon.sideMenu',
    passProps: {
      name: 'menu',
      size: 24,
      color: 'white'
    }
  },
  {
      id: 'BUTTON_ONE',
      testID: 'BUTTON_ONE',
      title: 'One',
      buttonFontSize: 28,
      buttonColor: 'red'
   }
]
```

---
### Environment
* React Native Navigation version: 2.0.2124
* React Native version: 0.53.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, 20.3.1, debug

**Comment by guyca** [comment]
Hey @jeprojects,
I've looked into this issue today and it's not as straightforward as it might seem. Adding any `Touchable` component in jsx prevents native click handlers from being fired, preventing us from sending the button press event to js.
Seems to me that custom buttons should handle click events themselves as setting onClick handlers in native for custom views is very problematic.
