### ISSUE TITLE
bottomTabSelected event dipatched before  didAppear event?

### ISSUE THREAD

**Issue by AndrewJikun** [wix/react-native-navigation#2711]
### Issue Description

In my app, I need to listen bottomTabSelected and didAppear event on a pop or a push. What I expect is that bottomTabSelected needs to be catched before didAppear and this works perfertly in IOS, While in Android it performs the opposite. Can we have them work the same?

### Environment
* React Native Navigation version: V1 latest
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?):BOth
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by AndrewJikun** [comment]
@guyca I upgraded RNN to lastest Version and I don't think you fixed the issue.  
Here is my use case(My app has four tabs), here is what the user would do:
1. open the app, the first tab would be selected in default.
2. the user press the fourth tabs, I need to listen the bottomSelceted first and didappear events in this  fourth component but now I only catch  will appear and did appear.
3. the user press the third tabs, I notice bottomSelceted being catched. 

This is not correct, what i need is the same as IOS: when the user press the fourth tab,bottomSelceted willappear,didappear would be catched one by one .

**Comment by guyca** [comment]
Hey @AndrewJikun, should be fine now.

**Comment by AndrewJikun** [comment]
@guyca Thanks so much, I will try out later. I have another issue, that is  when poping back to a sreen (Like Screen A) using Didappear event to update the in the data  Sreen  A where there is Image which needs to downloaded from the web server, I find UI frame would be dropped dramatically in Sreen A. I find two solutions to the issue.
1. apply a setTimeout Timer to have image downloaded with 500ms delay
2. smaller the image size (from 1MB to 300B)

But still there is slightly frame dropping and this is not in good user experence. Do you have better solution?

**Comment by guyca** [comment]
If you're fetching images in `didAppear`, obviously there will be some artifacts.
Even though `ScreenA` is not visible, it's still mounted and connected, I suggest you handle these ui changes via state management.
