### ISSUE TITLE
Large title is not taking the navBarTextColor color value

### ISSUE THREAD

**Issue by frangeris** [wix/react-native-navigation#2713]
### Issue Description

Large title is not taking the `navBarTextColor` color value

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
export default class MyScreen extends Component {
  static navigatorStyle = {
    largeTitle: true,
    navBarTextColor: 'red'
  }
}
```
![image](https://user-images.githubusercontent.com/811381/36112403-4e7bc398-1008-11e8-9b4f-c5916b075d25.png)

When scroll take the color

![image](https://user-images.githubusercontent.com/811381/36112413-56901840-1008-11e8-9b2a-5f0698ed73dc.png)

---
### Environment
* React Native Navigation version: ^1.1.375
* React Native version: ^0.52.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/iPhone 11.2 Debug

**Comment by karlmosenbacher** [comment]
@frangeris have you solved it?

**Comment by DazChong** [comment]
@frangeris @karlmosenbacher 

Here with my fix:

- Edit `./node_modules/react-native-navigation/ios/RCCViewController.m`

- Search for `self.navigationController.navigationBar.prefersLargeTitles = YES;`

- Add the following lines just below it:
```
id navBarTextColor = self.navigatorStyle[@"navBarTextColor"];
if (navBarTextColor)
{
    UIColor *color = navBarTextColor != (id)[NSNull null] ? [RCTConvert UIColor:navBarTextColor] : nil;
    self.navigationController.navigationBar.largeTitleTextAttributes = @{NSForegroundColorAttributeName: color};
}
```

**Comment by KimAM** [comment]
Seems like this is still a problem on 1.1.483. Is there any plan to fix this on version 1?

**Comment by frangeris** [comment]
> @frangeris @karlmosenbacher
> 
> Here with my fix:
> 
> * Edit `./node_modules/react-native-navigation/ios/RCCViewController.m`
> * Search for `self.navigationController.navigationBar.prefersLargeTitles = YES;`
> * Add the following lines just below it:
> 
> ```
> id navBarTextColor = self.navigatorStyle[@"navBarTextColor"];
> if (navBarTextColor)
> {
>     UIColor *color = navBarTextColor != (id)[NSNull null] ? [RCTConvert UIColor:navBarTextColor] : nil;
>     self.navigationController.navigationBar.largeTitleTextAttributes = @{NSForegroundColorAttributeName: color};
> }
> ```

Nice!, could send a PR or this?
