### ISSUE TITLE
v2 vs v1

### ISSUE THREAD

**Issue by gaultierq** [wix/react-native-navigation#2716]
I am considering migrating from RNN to RNN v2.
Is v2 production ready ? Which version offer the best experience, as of today ?

**Comment by guyca** [comment]
Hey @gaultierq 
I'm not 100% comfortable saying v2 is production ready, although there are already companies using it in production and future products. We're aiming for almost complete parity by late march/april.
We're keeping track of available features [here](https://github.com/wix/react-native-navigation/tree/v2), although this needs to be updated actually.
Hope this answers your question.

**Comment by gaultierq** [comment]
many thanks ! think i'll give it a try :)

**Comment by karlmosenbacher** [comment]
Is there anything to keep in mind when migrating from v1 to v2?

**Comment by guyca** [comment]
Mostly that v2 is still in alpha and in early stages of development on Android.

**Comment by ujwal-setlur** [comment]
so, is the android support lagging behind ios? Is it less stable?

**Comment by guyca** [comment]
@ujwal-setlur v2 should be stable on both platforms. Android is a bit lagging behind iOS since we're implementing the navigation stack from scratch as we can't use Activities (and trying to avoid Fragments)

**Comment by ujwal-setlur** [comment]
@guyca, thank you. I am starting a new project that will not be production ready for a few months, so I am wondering if I can start with v2 if you guys are fairly close? Any thoughts?

**Comment by guyca** [comment]
We're starting to migrate one of our internal apps to v2 by early April, I'd say we're fairly close to beta release and the api is pretty much stable now.

**Comment by ujwal-setlur** [comment]
Great, then I will start with v2 then!

**Comment by ujwal-setlur** [comment]
@guyca, is the API for v2 documented somewhere? Thanks.

**Comment by ujwal-setlur** [comment]
The playground example app does not seem to work well under android. side panels don't show. Maybe I will stick to v1 for now.
