### ISSUE TITLE
How can i show the tab menu in side a modal ? 

### ISSUE THREAD

**Issue by khanh19934** [wix/react-native-navigation#2717]
### Issue Description
I want to know is any way to show a tab base when modal open ?

### Environment
* React Native Navigation version: 1.1.375
* React Native version: "0.53.0",
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator 11.2

**Comment by guyca** [comment]
No, a modal is a full screen component independent of the navigation stack.
