### ISSUE TITLE
[v2] Building on Android fails

### ISSUE THREAD

**Issue by jeprojects** [wix/react-native-navigation#2724]
### Issue Description

Following the instructions here: https://wix.github.io/react-native-navigation/v2/#/docs/installation-android

I am getting this error:

### ANDROID
FAILURE: Build failed with an exception.

* Where:
Script '/Users/xxx/Documents/ReactNative/xxx/xxx/node_modules/react-native-navigation/lib/android/prepare-robolectric.gradle' line: 6

* What went wrong:
A problem occurred evaluating script.
> Could not find method testImplementation() for arguments [org.khronos:opengl-api:gl1.1-android-2.1_r1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
---
### Environment
* React Native Navigation version: 2.0.2125
* React Native version: 0.53.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
What project are you trying to run? the playground app?

**Comment by jeprojects** [comment]
@guyca My own project. iOS runs fine, and downgrading to RNN v1 compiles fine too.

**Comment by jeprojects** [comment]
@guyca Any feedback on this one?

**Comment by guyca** [comment]
afaik the library compiles fine on android. Try `./gradlew clean` perhaps

**Comment by FlaviooLima** [comment]
Hi, this problem is resolved if you update a few things on Android.

You have two options : 
1- Open the project with android studio and just accept every update we ask for;
2- Just follow @fvicente comment in   #2354  issue.

**Comment by jeprojects** [comment]
@FlaviooLima Worked perfectly.. Thanks! I followed Option 2, and updated Gradle from 2 -> 3

**Comment by vitto-moz** [comment]
Very disappoint for me. I've tried to move to react-native-navigation v2 but several packages in a project use gradle 2.
Any solution here? Can I use RNN v2 with gradle 2?

**Comment by FlaviooLima** [comment]
@vitto-moz Gradlew 2 is pretty old.
I recommend using another gradlew version.
That being said,  I'm not 100% sure but you can update those packages gradlew versions in worse case scenario with the help of Android Studio. 
Right now I can't give more info. sorry :/
