### ISSUE TITLE
[Android] Setting a Title when a navBarCustomView is active

### ISSUE THREAD

**Issue by kevinmeyvaert** [wix/react-native-navigation#2726]
### Issue Description

In our application, we have 2 navbar states on the main screen. The 'normal' state is a navBarCustomView showing our logo. When you activate 'Demo Mode' the logo should disappear and a regular native title 'Demo Mode' should appear in the navbar.

We wrote a simple function that takes props as an argument (newProps in willReceiveProps), the function is called in the componentWillMount & componentWillReceiveProps.

```javascript
    // when demo mode is active, set 'Demo Mode' title
    if (props.demoMode) {
      props.navigator.setTitle({
        title: I18n.t('demo_mode.title'),
      });
    }
    // when demo mode is not active, set the company logo component
    if (!props.demoMode) {
      props.navigator.setStyle({
        navBarCustomView: SCREEN_IDS.TOPBAR,
      });
    }
```

On *iOS, this works perfectly*. On Android, this logic also works up until a navBarCustomView is set. Once a custom component is active, doing `navigator.setTitle()` will have no visible result.

### Steps to Reproduce / Code Snippets / Screenshots

* Set a static title.
* Use `navigator.setStyle()` to set a custom component.
* Then use `navigator.setTitle()` to set a title.

Expected result: The custom component disappears and the new title is shown. (This works on iOS!)
Actual result: The custom component stays visible and the new title doesn't appear on screen (All Android devices)

---
### Environment
* React Native Navigation version: 1.1.323
* React Native version: 0.50.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All android devices / simulators

**Comment by oferRounds** [comment]
+1

**Comment by oferRounds** [comment]
@kevinmeyvaert did you find any workaround for that issue?

**Comment by thibmaek** [comment]
@oferRounds we ended up ditching the `navBarCustomView` unfortunately.

**Comment by oferRounds** [comment]
Thanks @thibmaek! My workaround was to hook my custom view to `Redux`
