### ISSUE TITLE
Minimize the app instead of killing it as default back behavior

### ISSUE THREAD

**Issue by willlaserlike** [wix/react-native-navigation#2728]
Hello everyone, 

I'd like get some input on the idea of default Android back button behavior for navigation when it's the last activity on a stack. 

The current implementation is to kill the activity and causes a much longer time to start the app next time. I'm proposing to only minimizing the app as an alternative.

### Issue Description
I got inspired by this comment. 
https://github.com/wix/react-native-navigation/issues/1022#issuecomment-302473779

### Steps to Reproduce / Code Snippets / Screenshots

- Install the example app on an Android device 
- Open the App, press Home button, open the app again. Notice the app resumes instantly.
- Open the app, press Back button to leave the app, open the app again. Notice the app go through a cold starting thus more slower than the previous way
---
### Environment

* Platform(s) (iOS, Android, or both?): Android only

**Comment by guyca** [comment]
Hey there

Back button should kill the activity if there's nothing to pop. The issue which you've linked to proposes a solution to the problem, as it will greatly speed up launch time. We use it in the Wix app with great success, and that's the default behaviour in v2.
Alternatively, you can override the back button in your root screen by setting `overrideBackPress: true` in tab declaration .

```js
Navigation.startTabBasedApp({
  tabs: [
    {
      label: 'Navigation',
      screen: 'example.Types',
      icon: require('../img/list.png'),
      title: 'Navigation Types',
      overrideBackPress: true
    }, {
      label: 'Actions',
      screen: 'example.Actions',
      icon: require('../img/swap.png'),
      title: 'Navigation Actions',
      overrideBackPress: true
    }
  ]
})
```

Then, listen to `backPress` navigation event in the root screens and programatically send the app to the background (you'll need to do some native work here I think, starting the launcher intent is one way of achieving this)

regardless, overriding back handling isn't something RNN should be responsible so I'm opting to close the issue.
Best of luck

**Comment by dr-johnsmith** [comment]
@guyca  If a set `overrideBackPress: true`, how do i make a back to previous screen.
