### ISSUE TITLE
Can the default Tab be something other than the first one? [QUESTION]

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#273]
Is there a way to define a default tab to be selected on initial load of the app, that is other that the first one?

**Comment by guyca** [comment]
No. Can you please describe your use case?

**Comment by perrosnk** [comment]
I have a tabbar that consists of 3 tabs. The center one is the main screen of the app. I don't want to  move it to the left and be the first on because I want it to be in the center.
For example https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md provides a way to define the initial screen by writing: <Scene initial={true} />

**Comment by DanielZlotin** [comment]
Sounds like a nice feature. We'll add it.

**Comment by dacsang97** [comment]
You can use this guide. 
In the constructor of tab 1. Add :
this.props.navigator.switchToTab({
   tabIndex: 1 //index of tab you want to show first. 
})

**Comment by perrosnk** [comment]
@dacsang97  This doesn't really solve the problem, because it seems like the first tab is loaded and then moved to the other one, which is basically what is really done. But thanks anyway, it's a good solution till this feature is added.

**Comment by PARAGJYOTI** [comment]
If someone looking  for switching topTabs here's the api , which is not in documentation . 
   this.props.navigator.switchToTopTab({
   tabIndex: 1 //index of tab you want to show first.
   })

**Comment by PARAGJYOTI** [comment]
This is a really important feature that every navigation or routing api must have . Please add this soon . I tried but  I have no idea about Java .

**Comment by guyca** [comment]
[initialTabIndex](https://wix.github.io/react-native-navigation/#/top-level-api) was added in v1.1.198

**Comment by nebsi04** [comment]
Is there a solution like this for the top tabs?

**Comment by faizr** [comment]
When creating tab bar using createBottomTabNavigator() , use following:
initialRouteName: 'Route Name Here',
