### ISSUE TITLE
Blank white screen with TopBar in android  RNN v2

### ISSUE THREAD

**Issue by DVLNarayana** [wix/react-native-navigation#2732]
### Issue Description

After included the RNN v2 in my project IOS variant working fine but when i am trying android variant build and installed successfully but showing only TopBar. Please see the screen shoots

not able to fine what went wrong.

### Steps to Reproduce / Code Snippets / Screenshots

IOS Screenshort
![image](https://user-images.githubusercontent.com/3823779/36257841-8a02bf34-127e-11e8-8da3-f87598b73ac3.png)

Android Screenshort
![image](https://user-images.githubusercontent.com/3823779/36257851-91ca9a48-127e-11e8-80d1-10d752e5be23.png)

---
### Environment
* React Native Navigation version: 2.0.2128
* React Native version: 53
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): any

**Comment by guyca** [comment]
Hey there,
How do you expect me to debug this supposed issue? What am I supposed to understand from the two screenshots you've posted?
Before opening an issue, please investigate it locally and post any findings. Screenshots with some white screen are not acceptable.

**Comment by DVLNarayana** [comment]
I created a simple react-native app using "react-native init sampleRNNv2" then i integrated the react-native-navigation v2 package and followed instructions given the documentation then i facing this issue. here i am attaching the same sample project.

[sampleRNNV2.zip](https://github.com/wix/react-native-navigation/files/1731285/sampleRNNV2.zip)

**Comment by DVLNarayana** [comment]
@guyca : even i am facing this issue with playground example also i am sure something wrong in react-native-navigation for android variant.
