### ISSUE TITLE
iOS drawUnderNavBar/drawUnderTabBar overlaps view

### ISSUE THREAD

**Issue by lukakerr** [wix/react-native-navigation#2736]
### Issue Description

Content that was previously showing, gets hidden under both the nav and tab bar on IOS when using `drawUnderNavBar: true` or `drawUnderTabBar: true`.

### Steps to Reproduce / Code Snippets / Screenshots

When applying the following navigation styles, content that was previously in view, now gets overlapped by the nav and tab bars. The content is a FlatList, but this occurs even with a simple view and text as shown below:

```jsx
<View style={{flex: 1}}>
  <Text>Content goes here</Text>
</View>
```

```javascript
const navigatorStyle = {
  drawUnderTabBar: true,
  drawUnderNavBar: true,
  navBarTranslucent: true,
};
```

BEFORE adding navigator styles: 

![screen shot 2018-02-16 at 5 28 42 pm](https://user-images.githubusercontent.com/20056300/36295975-e21af8d8-133e-11e8-9181-84b482ccc055.png)

AFTER adding navigator styles (you can even see that the warning that says the debugger is in the background, is also hidden):

![screen shot 2018-02-16 at 5 28 50 pm](https://user-images.githubusercontent.com/20056300/36295979-e60fc266-133e-11e8-965c-d1cfe958f74a.png)

Adding a paddingTop seems to fix that nav bar issue, but adding paddingBottom or marginBottom doesnt fix the tab bar overlap. This doesn't seem like the right fix anyway. Is there a way to show the content in the viewport, but still have the navbar translucent?

---
### Environment
* React Native Navigation version: 1.1.378
* React Native version: 0.53.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X/11.2/Debug

**Comment by manuhook** [comment]
Did you try to apply the marginbottom to the contentContainerStyle on a scrollview ?
