### ISSUE TITLE
The Header back button(ios(<) and android(<--))  click not responding as fast a native

### ISSUE THREAD

**Issue by Bharatchavan20** [wix/react-native-navigation#2738]
### Issue Description

I have used StackNevigator with few screens.It's working perfectly but I have got an issue.
When I try to click Header back button(ios(<) and Android(<--)), it does not respond immediately. Either you have to **click it twice** or **wait for few seconds** after screen loading.   

### Environment
* React Native Navigation version: ^1.0.0-beta.21
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?):Release

**Comment by Bharatchavan20** [comment]
@guyca Is this issue resolved?

**Comment by guyca** [comment]
You're posting about `react-navigation` in `wix/react-native-navigation`.
