### ISSUE TITLE
leftButton event not happening on Android

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#274]
I'm trying to get the leftButton event to respond on Android and not having much luck. 
I get events from the right button fine. 

I am trying to pop up a modal on left button press. This has been working on iOS (with v1.x, I'm now on v2.0 and focusing on Android)

In my Component:

```js
  static navigatorButtons = {
    leftButtons: [
      {
        icon: require('../../../images/navicon_menu.png'),
        id: 'sideMenu'
      }
    ],
    rightButtons: [
      {
        icon: require('../../../images/navicon_edit.png'),
        id: 'settings'
      }
    ]
  }

  constructor(props) {
    super(props)
    this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this))
  }

  onNavigatorEvent(event) {
    console.log ("navigator event: "+event.id);
    if (event.id == 'settings') {
      Alert.alert('NavBar', 'settings');
    }
    if (event.id == 'sideMenu') {
      console.log('sideMenu button');
      this.props.navigator.showModal({
        screen: "myApp.IndexScreen", // unique ID registered with Navigation.registerScreen
        title: "List", // title of the screen as appears in the nav bar (optional)
        passProps: {}, // simple serializable object that will pass as props to the modal (optional)
        navigatorStyle: navigatorStyle, // override the navigator style for the screen, see "Styling the navigator" below (optional)
        animationType: 'slide-up' // 'none' / 'slide-up' , appear animation for the modal (optional, default 'slide-up')
      }); 
    }
  }

```

**Comment by guyca** [comment]
Hey @adamski 
I see that on Android we send left button events to JS in two cases:
1. The LeftButton is a back button, and `overrideBackPress` is true
2. The LeftButton is either a `cancel` or `accept` button

What exactly is your use case? When hamburger button is clicked, You show a menu screen in a modal?

**Comment by adamski** [comment]
For now, I think the standard drawer will do. However, I would like that LeftButton to bring up a full width modal with options like search, favourites etc. 

The architecture of my app is a few tabs that are different views on the same data. The LeftButton view allows the user to select a new set of data, which then alters the tabbed views with the new data.

**Comment by guyca** [comment]
I see, so you're setting a `sideMenu` left button but you don't define a `drawer` object when you call `start*App`. right?

**Comment by adamski** [comment]
Yes that's correct.

**Comment by guyca** [comment]
Ok I'll fix that next week. Thanks for reporting @adamski

**Comment by adamski** [comment]
Thanks
