### ISSUE TITLE
leftButton for Navigator.setButtons doesn't work on Android

### ISSUE THREAD

**Issue by davidliu** [wix/react-native-navigation#2740]
### Issue Description

leftButton for Navigator.setButtons doesn't work on Android. If used, it reverts any existing leftButton back to the default back arrow.

Notably, the static navigatorButtons = {leftButtons:[etc]} works, while setButtons will not.

### Steps to Reproduce / Code Snippets / Screenshots

```js
export const backButton = {
  icon: require('mobile/img/back-icon.png'),
  id: 'back',
  testID: 'back',
  showAsAction: 'always',
  disableIconTint: true,
}
```

At any point during a component's lifecycle:

```js
this.props.navigator.setButtons({leftButtons:[backButton])
```

---
### Environment
* React Native Navigation version: 0.52.1
* React Native version: ^1.1.378
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel 2, Android 8.1.0

**Comment by guyca** [comment]
`back` is a reserved key on Android, use a different `id`
https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=android-left-button
