### ISSUE TITLE
[v2] Stack topbar hidden is not working embedded in bottomTabs.  

### ISSUE THREAD

**Issue by JohnSmith0602** [wix/react-native-navigation#2743]
### Issue Description

My app needs to use stacks inside bottom tabs. If I use stacks alone, topbar options work as expected, including hidden. If I use stacks inside bottom tabs, I tried different places for options in Navigation.setRoot, yet none worked. I can customize some properties of topbar options by using Navigation.setOptions inside the component, yet, hidden option is still not working.

### Steps to Reproduce / Code Snippets / Screenshots

``` javascript
Navigation.setRoot({
    bottomTabs: {
      children: [
        {
          stack: {
            children: [
              {
                component: {
                  name: 'Discover',
                  options: {
                     topBar: {
                       hidden: true       // this doesn't work
                     }
                  }
                }
              }
            ],
            options: {
              topBar: {
                hidden: true       // this doesn't work
              },
              bottomTab: {
                title: 'Discover'  // this works
              }
            }
          }
        }
      ],
      options: {
        bottomTabs: {
          fontSize: 14    // this works
        }
      }
    }
})
```

---
### Environment
* React Native Navigation version: 2.0.2133
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by JohnSmith0602** [comment]
@yogevbd Thanks for your commit, I have checked the new version works! Just one thing to confirm: I remembered that I used topBar hidden in stack to get it work before, now I can only use topBar visible according to the example in your commit. I wanna confirm if is visible the new attribute instead of hidden?

**Comment by JohnSmith0602** [comment]
Well, sorry for one more question: just checked that drawUnder seems not working while visible does, meaning the content renders beneath the topBar when I set visible to be true.

```javascript
Navigation.push(this.props.componentId, {
      component: {
        name: 'Link',
        passProps: { links, index },
        options: {
          topBar: {
            visible: true,
            drawUnder: false
          }
        }
      }
    })
```

**Comment by yogevbd** [comment]
@JohnSmith0602 `hidden` changed to `visible` and `drawUnder` change to `drawBehind` 😄

**Comment by JohnSmith0602** [comment]
Cool, thx!

**Comment by L-Yeiser** [comment]
I am still seeing this on android. Any help?
