### ISSUE TITLE
Support RTL languages

### ISSUE THREAD

**Issue by dorshay6** [wix/react-native-navigation#275]
Hey,

As far as i understand there no support for RTL navigation right now, am I right?
If so there is any planing for it?

**Comment by DanielZlotin** [comment]
I guess it will happen sometime in the future, and it's not a simple task. We ourselves are sitting in Israel so I guess it depends on how soon our product people will want it.. My guess is not any time soon. I'll assign it to TBD.

**Comment by nidongara** [comment]
Any update on the support?

**Comment by mrxrinc** [comment]
buddies pls make it rtl too :(

**Comment by mrxrinc** [comment]
@jadidian bro man ke bikhiyale rtl shodam! avazesh khodam tab bar o navigation bar neveshtam ke shabihe aslishe! vali ino dar nazar dashte bash ke rnn ta react native version e 0.51 ro support mikone! avazesh airbnb dare roo ye navigation e jadid kar mikone ke oonam native hast vali hanooz too beta st! montazere oonam man. (hala hame ta'ajob mikonan ke ma darim be che zabooni harf mizanim :))))

**Comment by jadidian** [comment]
@mrxrinc dude the Airbnb navigation seems to be a dead project https://github.com/airbnb/native-navigation/issues/145 and not actively being developed / maintained anymore...

**Comment by mrxrinc** [comment]
@jadidian oh! I didn't know this! so the navigation future seem dark then :(

**Comment by nidongara** [comment]
I made it work with these 2 commits. My app supports full RTL. 
https://github.com/nidongara/react-native-navigation/commit/420d2322c9e98ae23ab4ffac014c81ab7c4e90e8
https://github.com/nidongara/react-native-navigation/commit/cfd1eccf5d83349e6ab4319fd7de87e80ce7c164

**Comment by jadidian** [comment]
@nidongara I think your commits are just patches for opening the drawer from left / right while full RTL support also means:
- Correct positioning of start / end (or left / right) buttons on navigation bar
- Correct drawer position
- Correct order of tab bar buttons
- Correct direction of slide animations and back buttons for stack navigations (in RTL, pushing a view should slide it in from left side and back button should appear on right side of the navigation bar)

**Comment by nidongara** [comment]
![image](https://user-images.githubusercontent.com/16006011/36107113-b91302cc-0fde-11e8-897d-135b8ecf074c.png)
![image](https://user-images.githubusercontent.com/16006011/36107130-beca7452-0fde-11e8-81b9-ea5ba29dd61f.png)
![image](https://user-images.githubusercontent.com/16006011/36107171-df61dea8-0fde-11e8-8485-18d89bdf2d77.png)
@jadidian I agree it is a patch but I was able to achieve the screens mentioned above. In my case, I only turn RTL if the Android locale is selected to an RTL language. If you mention your use case then I might be able to help you with some patch.

**Comment by jadidian** [comment]
@nidongara I guess its already possible to customize left / right buttons on navigation bars and handle tabs order or other stuff using `I18nManager.isRTL ? ... : ...`, but the most important thing in my case is having push animations slide in from correct direction which hasn't been implemented in RNN

**Comment by jadidian** [comment]
This is how it should look like, notice the slide directions in LTR / RTL... I used `react-navigation` to achieve this but I would be awesome to make the same thing using `react-native-navigation`
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/650099/36108569-612e8578-1032-11e8-86d5-f20047e0f1ae.gif)

**Comment by bitcrumb** [comment]
I added support for flipping the back button via this PR: #3154

**Comment by manjeetwadi** [comment]
any progress on this??

**Comment by anuraginwadi** [comment]
@manjeetwadi this is already supported, if device locale is RTL, buttons are flipped
