### ISSUE TITLE
Integrating native libraries with Android

### ISSUE THREAD

**Issue by jtibbertsma** [wix/react-native-navigation#2753]
### Issue Description

I'm trying to integrate this library into my android app that uses RNN.
https://docs.branch.io/pages/apps/react-native/

To integrate, I need to add the following into `MainActivity`:

```java
      @Override
      protected void onStart() {
          super.onStart();
          RNBranchModule.initSession(getIntent().getData(), this);
      }

      @Override
      public void onNewIntent(Intent intent) {
          setIntent(intent);
      }
```

According to the RNN docs, code that is meant to go in `MainActivity` should go into the `setActivityCallbacks` block in `MainApplication.onCreate`. So I put these methods into the callbacks block, but I get a compile fail which says that the symbol `onStart` does not exist. Indeed, neither `onStart` nor `onNewIntent` are listed in the RNN docs as available callbacks.

So, is there anything I can do here (other than switch react-navigation)? Or am I shit out of luck?

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely painful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
The list of available callbacks can be found [here](https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=activity-lifecycle-and-onactivityresult) notice the names are slightly different.

**Comment by jtibbertsma** [comment]
Slightly different than what?

**Comment by guyca** [comment]
The names are different. `onStart` -> `onActivityStarted`

**Comment by jtibbertsma** [comment]
Oh. Maybe you guys should put that in the docs. It isn't exactly obvious.

If I wanted to override `onNewIntent`, what should I do?

**Comment by guyca** [comment]
@jtibbertsma 
If you dig a little in the code, you'll find the native java [file](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/controllers/ActivityCallbacks.java) where all available callbacks are listed.
The docs are a bit outdated as some callbacks were added later on

**Comment by jinshin1013** [comment]
@guyca Is this still valid for V2? I couldn't locate ActivityCallbacks file on V2

**Comment by guyca** [comment]
No need to use activity callback in v2, you can simply override the Activity lifecycle methods in MainActivity

**Comment by jinshin1013** [comment]
Doing something like this, [Branch.io Android Setup](https://github.com/BranchMetrics/react-native-branch-deep-linking#android-setup), would crash the app on start.

**Comment by badaz** [comment]
Hi, I'm facing the same issue, have you found a solution?
