### ISSUE TITLE
Moving elements between scenes causes stretching

### ISSUE THREAD

**Issue by nixterrimus** [wix/react-native-navigation#2758]
### Issue Description

When I move elements between scenes I've been seeing stretching and squishing as the element moves:

<img width="638" alt="screen shot 2018-02-19 at 1 54 00 pm" src="https://user-images.githubusercontent.com/18454/36398526-6072aeda-157c-11e8-82d2-832277ae33d6.png">

### Steps to Reproduce / Code Snippets / Screenshots

- [Video of transition](https://i.imgur.com/IyXQecE.mp4)
- [Source for source and destination scenes](https://gist.github.com/nixterrimus/1643c8d290c3610deca4ff9da43a1e78)

---
### Environment
* React Native Navigation version: 2.0.2140
* React Native version: 0.53.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by nixterrimus** [comment]
cc: @bogobogo I think you've been working on transitions for v2 (❤️)

- During text rasterization is retina / non retina an issue?
- Is something going wrong with calculating frames?  It seems like there's enough room for both source destination but do I need to do something to hint at frame sizes?

**Comment by nixterrimus** [comment]
I'm seeing this effect with images too.  It looks like it's the same distortion but it's much more noticeable.

Here's during animation:
<img width="542" alt="screen shot 2018-02-20 at 8 58 12 am" src="https://user-images.githubusercontent.com/18454/36437648-6bb7b966-161c-11e8-9be3-70fcf5b8227a.png">

And here's the first frame of the next scene:
<img width="542" alt="screen shot 2018-02-20 at 8 58 30 am" src="https://user-images.githubusercontent.com/18454/36437663-74f4fbf6-161c-11e8-948c-292dbf5a6f04.png">

**Comment by nixterrimus** [comment]
Here's a video with the stretching: https://imgur.com/a/TBNm0
Here's the code for the version with the image stretching: https://gist.github.com/nixterrimus/03cdf8a3909e17e444234fe3c64da1e8

**Comment by nixterrimus** [comment]
@guyca Do you know anything about this?  Maybe I can help out if you give me a nudge in the right direction

**Comment by guyca** [comment]
Hey guys
I'm not familiar with the iOS implementation of this feature, will try to ping @bogobogo as well.
As this feature isn't used by the WIx app, it's a bit low on our priorities at the moment.
Once we reach parity with features the Wix app uses (late March/April 🙏 ) we will get to moread features such as this.

**Comment by bogobogo** [comment]
Hey @nixterrimus ,
Shared Element currently does not work with a changing font size or font color.
Regarding the image:
1)  Try to wrap your image with a Navigation.Element directly instead of wrapping a View that wraps the image(in the destination source code).
2) This might change in the future, but currently you need to specify the resizeMode to the Navigation.Element view that wraps the image as well the image. See[ this line code of code](https://github.com/wix/react-native-navigation/blob/v2/playground/src/screens/CustomTransitionOrigin.js#L29) from the playground app as reference. 

Let me know if the image stretching problem is resloved or if you need any more help.

**Comment by tastyqbit** [comment]
There is a pretty big issue with the sharedElements for images. Their resizing does not work as expected and rerenders when the destination component is mounted. I think this is a really big feature that many people are looking for and would love some support or at least a pointer to where we can try to fix it

**Comment by geroale** [comment]
Same issue here
