### ISSUE TITLE
Error on Release on android

### ISSUE THREAD

**Issue by SimchaShats** [wix/react-native-navigation#276]
Hi When I'm running on debug mode, it works great, but when I'm generating release apk I'm getting next error:
`Process: com.simcha.measures, PID: 19543
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.clearColorFilter()' on a null object reference
                                                                         at com.aurelhubert.ahbottomnavigation.AHHelper.getTintDrawable(AHHelper.java:37)
                                                                         at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createSmallItems(AHBottomNavigation.java:447)
                                                                         at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.createItems(AHBottomNavigation.java:236)
                                                                         at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.onSizeChanged(AHBottomNavigation.java:132)
                                                                         at android.view.View.sizeChange(View.java:16748)`

What I'm doing wrong?

**Comment by guyca** [comment]
What Android version? Are you using vector icons in your BottomTabs?

**Comment by SimchaShats** [comment]
I'm using emulator Google Nexus 5x 6.0.0 (API 23), yes I'm using vector icons according instructions installation instractions (on readme page)... and it works perfect on Debug but with release it failed... thanks

**Comment by guyca** [comment]
You're not the first user that encounters this issue. We're not using vector icons in our app so we didn't face this issue. I'll try to look into it next week, If you create a sample project where this bug is reproducible it will greatly speed things up.

**Comment by SimchaShats** [comment]
Thanks you van take my project: [](https://drive.google.com/open?id=0B_kzM6Vbx-hzcm90OGsyMDdmblU) you need just to do npm install and setUsingOldBridge(true) on Naviation-router...

**Comment by guyca** [comment]
@SimchaShats what is `Naviation-router`?
Can you upload the project to GitHub so I can just clone it, npm install, run -> crash?

**Comment by SimchaShats** [comment]
This is branch: [Git](https://github.com/SimchaShats/test-navigation/)
Naviation-router: I wanted to say this file: NavigationReactGateway:

` ReactInstanceManager.Builder builder = ReactInstanceManager.builder()
                .setApplication(NavigationApplication.instance)
                .setJSMainModuleName(NavigationApplication.instance.getJsEntryFileName())
                .setBundleAssetName(NavigationApplication.instance.getBundleAssetName())
                .setUseDeveloperSupport(NavigationApplication.instance.isDebug())
                .setInitialLifecycleState(LifecycleState.BEFORE_RESUME).setUseOldBridge(true);`

**Comment by SimchaShats** [comment]
yes you was right, if I will use simple images instead of vector icons it works (and need to add also selectedIcon property, to router configuration it also the issue for this exception (thanks for [#117](https://github.com/wix/react-native-navigation/issues/117)))... and I think also on release there are no vector icons in all application not only tabbar

**Comment by guyca** [comment]
This seems to be the same issue as #176. @adamski did you ever figure out what caused this issue for you?

**Comment by adamski** [comment]
No I didn't, this seems like a slightly different cause but definitely the same error message. There was something preventing the loading of image files. I don't have the issue anymore.

**Comment by guyca** [comment]
Thanks Adam.
