### ISSUE TITLE
FR: Allow disable some tabs

### ISSUE THREAD

**Issue by brunolemos** [wix/react-native-navigation#2766]
My use case is that when the user haven't completed 100% of the signup (or his profile has been rejected/changes requested), he has access to 2 tabs and the other 2 should be grayed out and disabled (no press handler). We don't want to hide the tabs, only disable some, because we want them to transition to not-gray after he completes the signup.

I don't see any way to disable some specific tabs on react-native-navigation.
I see it's possible to change their icon, but not disable the press handler.

**Comment by guyca** [comment]
@DanielZlotin What do you think about adding ability to handle BottomTab click in Js?

```js
options: {
  bottomTab: {
    title: 'Tab 2',
    icon: require('../images/two.png'),
    onClick: (index) => console.log(`tab ${index} clicked`)
  }
}
```

**Comment by brunolemos** [comment]
Do you see any other use case for a custom press handler?
Personally I think a `disabled: true` would be enough.

**Comment by DanielZlotin** [comment]
That was part of the initial roadmap but we postponed it.. 
Then if the onClick is provided we do nothing in native?
If we gonna add this now, we should probably add the onClick on any buttons (topbar, toptabs etc) as a function as well. (while still supporting the other methods)

**Comment by guyca** [comment]
Right, if `onClick` is provided we don't handle the click in native. But in this case, should we rename it to `clickHandler`? To better reflect that this method handles the click and is not just a regular listener/callback.

**Comment by DanielZlotin** [comment]
How about `onClickHandler`

**Comment by guyca** [comment]
Sounds good

**Comment by brunolemos** [comment]
I would personally vote for:

- Add a `disabled` prop
- Add `disabledIcon` and other props to provide styling for disabled tabs
- [optional] Add a `callback` (or `onPress`, ...) prop 
  - Native will change tab no matter if you pass this prop or not
  - Native will not change tab only if you pass `disabled: true`

**Comment by guyca** [comment]
I'm a bit hesitant to support `enabled` property for bottom tabs as this is pretty much a UX anti pattern. For a reason known only to you (and your product manager), a bottom tab is disabled. The user clicks on it without getting any feedback (it's disabled dah..) and this kind of sucks.

I couldn't find anything about this in the [design guidelines on Android](https://material.io/guidelines/components/bottom-navigation.html#).

Honestly, I think if a user should be logged in and a tab that required login is visible - show an empty state encouraging the user to login.

**Comment by brunolemos** [comment]
Oks the other solution should be enough

**Comment by brunolemos** [comment]
@stale no

**Comment by Dallas62** [comment]
+1 for `onClick` feature
It will also allow us to implement some library such as `react-native-intercom` with a press on the Tab.

**Comment by Burnsy** [comment]
Any progress on this for v2? Thank you!

**Comment by herarya** [comment]
+1 for onClick

**Comment by jayeshanandani** [comment]
Any update? This seems like a great add on :)

**Comment by immortalx** [comment]
Does it cover the case in the issue #2756 ?
My use case is to define a bottomTab that opens a modal on the current active tab.

**Comment by Maksym5248** [comment]
Are there any updates ?

**Comment by pacozaa** [comment]
I am looking forward to this improvement as well.

**Comment by guvenakcbn** [comment]
+1 I need this improvement.

**Comment by eightyfive** [comment]
This feels like an anti UX pattern to me.

What I did in your case:
> ... when the user haven't completed 100% of the signup ...

Is to show/mount a blocking "Onboard" `stack` app if user profile is not yet ready. I only show the "Main" `bottomTabs` app when the user profile is completed.

Hope this helps!

**Comment by eightyfive** [comment]
Hi @guyca 

You seem to point back to this issue to track progress about a custom click handler for tabs:
https://github.com/wix/react-native-navigation/issues/3204#issuecomment-388881806

Can we have a timeline please? A guess?

Opening a Modal from the central tab is a very common UX pattern (Instagram), while not critical that would be a nice feature to have!

Thanks for the lib and your time as usual.

**Comment by AbanoubNassem** [comment]
any updates on this issue?

**Comment by immortalx** [comment]
@guyca is this something planned for the near future or really low priority? I had to replace react-native-navigation with react-navigation because of this feature but would love to come back to RNN.

**Comment by akhan118** [comment]
Any work around for this ?

**Comment by eightyfive** [comment]
https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/

> **Don’t remove or disable a tab when its function is unavailable.** If tabs are available in some cases but not in others, your app’s interface becomes unstable and unpredictable. Ensure that all tabs are always enabled, and explain why a tab’s content is unavailable. For example, if there are no songs on an iOS device, the My Music tab in the Music app explains how to download songs.

**Comment by guyca** [comment]
Fixed by https://github.com/wix/react-native-navigation/issues/5545
