### ISSUE TITLE
iOS backButtonTitle default value is inconsistent

### ISSUE THREAD

**Issue by nbolender** [wix/react-native-navigation#2767]
### Issue Description

The default back button title is inconsistent between iOS versions. Specifically, in iOS 8.4, the default is always "Back" while in iOS 11.2, the default is the title of the pushing screen.

### Steps to Reproduce / Code Snippets / Screenshots

1. Start on a screen with a navbar title "First Title"
2. Push a screen using this.props.navigator.push(), and do not specify backButtonTitle
3. On iOS 8: back button reads "Back"; on iOS 11: back button reads "First Title"

---
### Environment
* React Native Navigation version: 1.1.384
* React Native version: 0.52.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / 8.4 & 11.2 / Debug

**Comment by guyca** [comment]
@yogevbd Is this a bug? Relevant to v2 as well?

**Comment by yogevbd** [comment]
Not a bug.. This change is in iOS navBar implementation 😄

**Comment by isaachinman** [comment]
@yogevbd Is there anyway to change this? Eg to force the back button text to _always_ be "Back" instead of the previous screen's title?
