### ISSUE TITLE
iOS <11: custom rightButton position wrong during push animation

### ISSUE THREAD

**Issue by nbolender** [wix/react-native-navigation#2768]
### Issue Description

On iOS 8, when using a custom rightButton, the button initially appears on the left when pushing the screen. That is, it appears on the left until the push animation is complete, then it resets to the correct position.

This issue does not occur when popping the view or on iOS 11.

## iOS 8.4
![iOS 8.4](https://imgur.com/BoGau5u.gif)

## iOS 11.2
![iOS 11.2](https://imgur.com/cce4Sy7.gif)

### Steps to Reproduce / Code Snippets / Screenshots

```js
export default class SignUpScreen extends BaseScreen {
	loginButtonPressed = () => {
		this.props.navigator.push({
			screen: 'LoginScreen',
			title: "Log In",
			backButtonTitle: "Back"
		});
	}
}

export default class LoginScreen extends BaseScreen {
	static navigatorButtons = {
		rightButtons: [
			{
				component: 'Button',
				passProps: {
					text: "Cancel2"
				},
			}
		]
	}
}
```

---
### Environment
* React Native Navigation version: 1.1.384
* React Native version: 0.52.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / iOS 8.4 / Debug

**Comment by KarolAltamirano** [comment]
For me, the issue is also present in iOS 9.3 and iOS 10.3.1 simulators.

**Comment by thibmaek** [comment]
We're also seeing this issue in latest iOS 10 (10.3.3) on both Simulator and device.
Works fine on iOS 11 & Android using: `"react-native-navigation": "^1.1.323"`

**Comment by nbolender** [comment]
I did a small amount of digging into the Objective-C code around managing the toolbar buttons, but couldn't figure out an obvious fix. I think it may have something to do with the native component not settings its initial bounds correctly. If anyone knows a bit more and wants to point me in the right direction I'd be happy to try to fix it.
