### ISSUE TITLE
Component mount in Tab based navigation

### ISSUE THREAD

**Issue by RajeshUppara** [wix/react-native-navigation#2769]
### Issue Description

In Tab based navigation app when ever I start so all the components under each tab bar starts mounting.
For example: when Tab based app is started let say, I have tab1, tab2, tab3 and I am on tab1 so tab1 component will get mounted on to the screen, what is happening behind the scenes is tab2 and tab3 components are also running behind the scenes.

How to handle this untill unless I click on any tab that component shouldn't load.

(https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

This is generic scenario and with all versions.

**Comment by guyca** [comment]
True, this is by design.
