### ISSUE TITLE
ScrollView in stack causes odd behavior when keyboard opens

### ISSUE THREAD

**Issue by kingkian** [wix/react-native-navigation#2773]
With a textinput in a view and no keyboard handling whatsoever, the keyboard will cover the screen and bottom tabs as expected. 

For some reason, if I have a scrollview anywhere in the stack of screens and the keyboard opens, the tabs will be placed on top of the keyboard and the screen is resized causing all of the flexboxes to change. This issue exists only on Android.

Any ideas?

**Comment by guyca** [comment]
What RNN version are you using?
