### ISSUE TITLE
Hamburger menu doesnt get displayed

### ISSUE THREAD

**Issue by hemraj-s** [wix/react-native-navigation#2776]
### Issue Description

I have created an application with 4 pages and have registered them along with the drawer. The screens get rendered correctly; however am unable to see the drawer menu. Kindly note that the render method is called (have checked it with console.log)

### Steps to Reproduce / Code Snippets / Screenshots

Flow is as follows:
Index.js in the root

`import {Provider} from 'react-redux'
import configureStore from './store/store'
import myProvider from './provider';

import Application from './screens/index'
import initState from './reducers/initialState'
const store = configureStore(initState);
export const rootNavigator = new Application(store, myProvider)

rootNavigator.run()`

index.js in the screens folder
`import {Navigation} from react-native-navigation

export default class Application {
  constructor(store, Provider) {
    this._store = store
    this._provider = Provider
    this._iconsLoaded = false
    this._topTabs = [];

    this._configureScreens(store, Provider)
  }

  _configureScreens(store, Provider) {

    const screens = [
      {
          screenId: 'kmit.HomePage',
          title: 'Home',
          screen : HomePage
      },
      {
          screenId: 'kmit.MathPage',
          title: 'Math',
          screen : MathPage
      },
      {
          screenId: 'kmit.UserPage',
          title: 'User',
          screen : UserPage,
          navigatorButtons: {
            leftButtons: [
                {
                    title: 'Menu',
                    id: 'sideDrawerToggle'
                }
            ]
        }          
      },
      {
          screenId: 'kmit.MyKIT',
          title: 'My KIT',
          screen : MyKIT
      },
      {
        screenId: 'kmit.Drawer',
        title: '',
        screen : Drawer,
        isDrawer : true
    }

  ];
  
    screens.map( item =>{
      if(item.isDrawer == undefined || !item.isDrawer)
      {
        Navigation.registerComponent(item.screenId, () => item.screen, store, Provider);
        this._topTabs.push({screenId: item.screenId, title: item.title});
      }
      else
      {
        Navigation.registerComponent(item.screenId, () => item.screen);        
      }
    })
  }

  run() {
    this._store.dispatch(init())
  }

  startAppWithScreen(opts) 
  {
      this._iconsLoaded = true;
    if (this._iconsLoaded) {
      this.startApp(opts);
    } 
  
  }

  startApp({screen, passProps, showDrawer = true}) {
    const navigatorStyle = {

      navBarBackgroundColor: 'teal', // tab bar background
      navBarTextColor: 'white', // text color on the nav bar
    
      topTabTextColor:'white', // top tab text color
      selectedTopTabTextColor:'yellow', // top tab selected text color
    
      statusBarColor: 'black',
      statusBarTextColorScheme: 'light',
    
      navigationBarColor: 'black',
    
      navBarButtonColor: 'red',
    
      tabBarLabelColor : 'blue',
      tabBarSelectedLabelColor : 'yellow',
      tabBarButtonColor: 'yellow',
      tabBarSelectedButtonColor: 'red',
      tabBarBackgroundColor: 'yellow',
    
    
    };
        
    const app = {
        screen: {
            screen: 'kmit.HomePage',
            title: 'Not Current',
            navigatorStyle : navigatorStyle,
            topTabs : this._topTabs
        },
    }
    var screenObj = Object.assign(
      app, showDrawer ? {drawer: {left: {screen: 'kmit.Drawer'}}} : {}
    )

    Navigation.startSingleScreenApp(screenObj);
  }
}
`
init function export from app.js
`export function init() {
  return async (dispatch, getState) => {

     rootNavigator.startAppWithScreen({screen: 'kmit.Home', showDrawer: true})

  }
}
`

render functions from drawer
`
    render() {
        return(
            <View style={[
                styles.container,
                {width: Dimensions.get('window').width * 0.8}
            ]}>
                <Text>Drawer</Text>
            </View>
        );
    }
	render1() {
		console.log ('drawer render called');
		const iconSearch = (<Icon name="md-search" size={26} color="#9F9F9F" style={[styles.drawerListIcon, { paddingLeft: 2 }]} />);
		const iconMovies = (<Icon name="md-film" size={26} color="#9F9F9F" style={[styles.drawerListIcon, { paddingLeft: 3 }]} />);
		const iconTV = (<Icon name="ios-desktop" size={26} color="#9F9F9F" style={styles.drawerListIcon} />);
		return (
			<LinearGradient colors={['rgba(0, 0, 0, 0.7)', 'rgba(0,0,0, 0.9)', 'rgba(0,0,0, 1)']} style={styles.linearGradient}>
				<View style={styles.container}>
					<View style={styles.drawerList}>
						<TouchableOpacity onPress={this._openSearch}>
							<View style={styles.drawerListItem}>
								{iconSearch}
								<Text style={styles.drawerListItemText}>
									Search
								</Text>
							</View>
						</TouchableOpacity>
						<TouchableOpacity onPress={this._goToMovies}>
							<View style={styles.drawerListItem}>
								{iconMovies}
								<Text style={styles.drawerListItemText}>
									KMIT with
								</Text>
							</View>
						</TouchableOpacity>
						<View style={styles.drawerListItem}>
							{iconTV}
							<Text style={styles.drawerListItemText} onPress={() => ToastAndroid.show('Coming Soon!', ToastAndroid.SHORT)}>
								TV Shows
							</Text>
						</View>
					</View>
					<Text style={styles._version}>
						{/* 'v1.0.0' */}
					</Text>
				</View>
			</LinearGradient>
		);
	}
}

Drawer.propTypes = {
	navigator: PropTypes.object
};

export default Drawer;`
---
### Environment
* React Native Navigation version: 1.1.386
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug / API 27

**Comment by guyca** [comment]
Please format the code snippets and tidy up the issue report. Can't understand much from this wall of text.
