### ISSUE TITLE
Custom Navigation Bar is not centralized 

### ISSUE THREAD

**Issue by barjas** [wix/react-native-navigation#2777]
### Issue Description

Custom nav bar is not centralised when there is a right navigation icon. The whole custom navigation is pushed left 

### Steps to Reproduce / Code Snippets / Screenshots

- add a custom Nav Bar
- add an navigation right icon

the whole custom navigation area is pushed to the left 

ANY HELP?

---
### Environment
* React Native Navigation version: 1.1.79
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by barjas** [comment]
but this is not solved yet!

**Comment by yogevbd** [comment]
@barjas the build was broken. can you please try again with the latest version?

**Comment by barjas** [comment]
still same issue on android with the latest version
