### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by lilitGrigoryan** [wix/react-native-navigation#2789]
How can i set Width and hight for modal in V2.

### Issue Description

i need modal in canter of screen but width and height must be customize.

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: v2
* React Native version:0.51
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?):All

**Comment by guyca** [comment]
Modal is full screen by design, that can't be changed.
You can show an Overlay instead. It can even contain a stack or any kind of layout you want

```js
    Navigation.showOverlay({
      stack: {
        children: [
          {
            component: {
              name: 'navigation.playground.TextScreen',
              passProps: {
                text: 'This Overlay screen 1'
              }
            }
          },
          {
            component: {
              name: 'navigation.playground.TextScreen',
              passProps: {
                text: 'This Overlay screen 2'
              }
            }
          }
        ]
      }
    })
```

**Comment by srameshr** [comment]
@guyca Where is this method mentioned in the docs?
