### ISSUE TITLE
Remove Icon Animation on Tab bar

### ISSUE THREAD

**Issue by joecaraccio** [wix/react-native-navigation#2796]
Is there anyway to remove the Icon Animation (where the icon enlargens when pressed) on the Tab Bar? I was trying to recreate the instagram style tab bar

Also, is there a size specific for each platform?

**Comment by guyca** [comment]
Hey, RNN uses [AHBottomNavigation](https://github.com/aurelhubert/ahbottomnavigation) and afaik this isn't supported by that library.
