### ISSUE TITLE
navBarHideOnScroll and statusBarHideWithNavBar

### ISSUE THREAD

**Issue by pvlvsk** [wix/react-native-navigation#28]
Hello,

when i use both properties together there's no animation on hiding the both components, when using in a ListView, they just disappear. When I scroll back, the navBar and and the StatusBar are returning with an animation correctly. Is this a bug or have i made a mistake?

> ```
>   case 'after-login':
>     Navigation.startTabBasedApp({
>       tabs: [
>         {
>           label: 'My Feed',
>           screen: 'tattoo.FeaturedScreen',
>           title: 'My Feed',
>           icon: require('../assets/tabBar/myfeed.png'),
>           navigatorStyle: {
>             navBarTextColor: '#FFFFFF',
>             navBarBackgroundColor: '#485995',
>             statusBarTextColorScheme: 'light',
>             navBarHideOnScroll: true,
>             statusBarHideWithNavBar: true,
>             navBarButtonColor: '#FFFFFF'
>           }
>         },
>        ...
> ```

I'm using the GiftedListView package and I also set "View controller-based status bar appearance" to YES in info.plist to customize the StatusBar Color Scheme

**Comment by pqkluan** [comment]
Fixed in the newest version.
