### ISSUE TITLE
[V1] dismissAllModals do not dismiss all modals

### ISSUE THREAD

**Issue by karlmosenbacher** [wix/react-native-navigation#2802]
### Issue Description
This is basically a continuation on issue [#2465](https://github.com/wix/react-native-navigation/issues/2465) but started this issue instead since the linked one is closed.

I have also discovered (in addition to above) that when dismissing a modal at a time instead of dismissAllModals, each components componentWillunmount function is invoked. But when using dismissAllModals the componentWillUnmount is not invoked at all. 

Any suggestions on what to do?

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots
start single app navigation, push screen, open two modals after each other and then dismissAllModals.

[FILL THIS OUT - It will be extremely helpful]
---
### Environment
* React Native Navigation version: 1.1.390
* React Native version: 0.53.3
* Platform(s) (iOS, Android, or both?): IOS, not tested on Android yet.
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator (Iphone 6 OS version: 11.2) and device Iphone 8 OS version: 11.2.5

**Comment by canyara** [comment]
I get this problem too. I write a modal manager to avoid use dissmissAllModal.

**Comment by karlmosenbacher** [comment]
@canyara do you mind sharing your code of that modal manager? Sounds interesting :)
