### ISSUE TITLE
navBarTextColor is not applied after screen pop

### ISSUE THREAD

**Issue by Nodonisko** [wix/react-native-navigation#2805]
### Issue Description

On iOS if I have screen with `navBarTextColor: 'black'`, then i push screen with `navBarTextColor: 'white'`, then go back to first screen, `navBarTextColor` remains white.  Tried also with/without `    keepStyleAcrossPush: false` but it has no effect.

**EDIT:** If I pop screen via `props.navigator.pop()` everything works correctly, issue will occur only if I use back button.

### Steps to Reproduce / Code Snippets / Screenshots

![in](https://user-images.githubusercontent.com/5837757/36893377-1a0c8c1a-1e08-11e8-858d-296f672153a3.gif)

---
### Environment
* React Native Navigation version: 1.1.386
* React Native version: 0.52.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iP 7 / Debug

**Comment by YYH123123** [comment]
Did you solve this problem? I am suffering from this problem now.
