### ISSUE TITLE
tab bar visibility query api?

### ISSUE THREAD

**Issue by jslz** [wix/react-native-navigation#2808]
### Issue Description

Need an API to query if the tab bar is visible. It could be hidden due to various things:
1. could be the screen is modal
1. could be 
```
navigatorStyle: { tabBarHidden: true }
```

---
### Environment
* React Native Navigation version: 1.1.331
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by guyca** [comment]
Hey @jslz 
I'll bring this up for discussion in our upcoming meeting. Regardless, whatever solution won't be part of v1.

**Comment by guyca** [comment]
@jslz Can you please describe the use case for which you need such an api?
