### ISSUE TITLE
White flash during the first component's render

### ISSUE THREAD

**Issue by alexeyvakarchuk** [wix/react-native-navigation#2812]
### Issue Description
I'm writing a small crypto app with charts(I'm using react-native-highcharts) and when I'm pushing a new screen I see a white flash when chart renders for the first time.
Does anyone know how to fix that?

<img src="https://user-images.githubusercontent.com/19474687/36947235-e58eab3c-1fd1-11e8-9bd5-2dd68c566df7.gif" width="320"/>
### Steps to Reproduce / Code Snippets / Screenshots

You can check it and run from my repo with app. Here is the full code:
https://github.com/alexeyvakarchuk/cryptofolio-mobile/tree/developpment-2

---
### Environment
* React Native Navigation version: 1.1.354
* React Native version: 0.53.3
* Platform(s) (iOS, Android, or both?): iOS(didn't tried on Android)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and device, iOS 11, Debug

**Comment by TolgaCagin** [comment]
Hi Alex , Sorry i am noob also, It is just my idea, did you try set  screenBackgroundColor: '#yourcolorhexcode', on top level api?

**Comment by alexeyvakarchuk** [comment]
@TolgaCagin Hi! Yes, I've already set it here: https://github.com/alexeyvakarchuk/cryptofolio-mobile/blob/developpment-2/src/App.js
Line 49

**Comment by onlaps** [comment]
@alexeyvakarchuk Did you solve this problem? Still have same issue
