### ISSUE TITLE
[Android] tabbar doesn't rerender after drawUnderStatusBar is set from true to false

### ISSUE THREAD

**Issue by vranjesluka** [wix/react-native-navigation#2813]
### Issue Description

Tabbar doesn't rerender after drawUnderStatusBar is set from true to false.
The tabbar is lower by status bar height until you touch a screen and the tabbar rerenders.

#### My navigator code for details:
```
    static navigatorStyle = {
        navBarButtonColor: '#fd8042',
        navBarNoBorder: true,
        drawUnderNavBar: true,
        statusBarTextColorScheme: Platform.OS === 'ios' ? 'dark' : "light",
        navBarTranslucent: Platform.OS === 'ios',
        navBarTransparent: true,
        navBarBackgroundColor: 'transparent',
        topBarElevationShadowEnabled: false,
        // iOS only
        // Android only
        drawUnderStatusBar: true,
        statusBarColor: '#00000033',
        navBarTopPadding: StatusBar.currentHeight
    };
```

![screen shot 2018-03-05 at 13 06 04 2](https://user-images.githubusercontent.com/8490079/36975242-c38bc828-2079-11e8-9565-ee6d0d4839f8.png)

![screen shot 2018-03-05 at 13 06 11 2](https://user-images.githubusercontent.com/8490079/36975241-c3690554-2079-11e8-8108-8a9943859210.png)

![screen shot 2018-03-05 at 13 06 15 2](https://user-images.githubusercontent.com/8490079/36975243-c3b0860e-2079-11e8-8c64-75038a8fdc24.png)

---
### Environment
* React Native Navigation version: 1.1.398
* React Native version: 0.54
* Platform: Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Samsung Galaxy S8, API 25, debug

**Comment by datvp09** [comment]
I've opened this issue before #3241 and the fact is `navBarTopPadding` not a workaround @guyca
