### ISSUE TITLE
iOS Navigation push not work! With standard Modal component for display wait loading!

### ISSUE THREAD

**Issue by legion-zver** [wix/react-native-navigation#2815]
### Issue Description

After the call to push a new window does not open, but in the debugger shows the creation of a new AppContainer. After that, any operations with navigacie no longer work, but AppContainer are created.

### Steps to Reproduce / Code Snippets / Screenshots

Send request to API (use axios) and in then call `this.props.navigator.push`
`this.setState({loading: true})` activating Modal component for display wait loading

```
    _onPressNext = () => {
        if(this.state.valid) {
            Keyboard.dismiss();
            this.setState({loading: true}, ()=>{
                API.auth.getConfirmCode(this.state.phone).then(() => {
                    this.props.navigator.push({
                        screen: 'app.ConfirmCode',
                        title: i18n.t('confirm_code_title'),
                        passProps: {phone: this.state.phone},
                        backButtonHidden: true,
                        animated: true
                    });
                }).catch((err)=>{
                    console.warn(err);
                }).then(()=>{
                    this.setState({loading: false});
                });
            });
        }
    };
```

---
### Environment
* React Native Navigation version:  1.1.393
* React Native version: 0.53.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6s latest OS version

**Comment by legion-zver** [comment]
If run in setTimeout 1sec - works, but it's not good for me

**Comment by legion-zver** [comment]
I seem to have found the problem, but not quite understand ... I use Modal to display a progress indicator by request server (SleekLoadingIndicator on the screen with shading) and while playing animation opening query time to return a result, respectively push not works

**Comment by Compulsor** [comment]
Why is this issue closed? I'm experiencing the same problem on the iOS build of my React-Native app. 
When I set a timeout as suggest by @legion-zver above, the screen indeed loads successfully.

This issue should be open, please someone help!

**Comment by pmichalowski** [comment]
I'm experiencing the same issue.

I'm having a tab based app. While being on one of the tabs I'm pushing some screens to the stack and later on I do an API call in on of those screens after which I try push the confirmation screen and here my problem starts. The debugger shows "Running application "XXXX" with appParams: ..." which suggests that the view was somehow initialized but it doesn't appear. If I'll do the push in a 1s timeout after the api call then it will work.
This timeout is a hack to make it working but it'd great if it'd be fixed.

**Comment by isaachinman** [comment]
I am also experiencing this issue. It's due to a modal overlay as well. I believe this is a general RN bug though, as there are weird issues with modals in general.

**Comment by isaachinman** [comment]
@guyca Any idea about a potential fix for this? Do you perhaps need more information? If 1.x is the stable release, I would expect bug fixes to still be a priority, no?

**Comment by isaachinman** [comment]
**Update:** for anyone else experiencing this problem, here's how I got around it temporarily.

Like others, I was using a `Modal` component (directly from RN) as a loader overlay - I specifically wanted to disable all user interaction in some "hard loading" cases.

The reason a `setTimeout` of a second works in the above mentioned cases has something to do with the Modal's animation period. Basically, we should not attempt _any_ `react-native-navigation` events, whether that be pushing, popping, showModal, dismissModal, etc, until the RN Modal is completely out of view / unmounted.

If you are willing to set `animationType='none'` on your RN Modal, this "blocking period" becomes much shorter. You should be able to get away with a `setTimeout` of 10ms, or maybe even a `setImmediate`. It's still a disgusting hack-solution, but it's a lot more acceptable than a full second delay.

**Comment by betopompolo** [comment]
@isaachinman do you know if this issue is fixed? I'm having the same problem here. Using react-native-navigation v3.2.0

**Comment by levynir** [comment]
On react-native-navigation 7.24.0 we have found that we need to wait at least 500ms between closing one modal and opening another. Seems related to this issue but I can't confirm.
