### ISSUE TITLE
java.lang.IllegalStateException: aidl is missing

### ISSUE THREAD

**Issue by Proxy08** [wix/react-native-navigation#2816]
failed to executed react-native run-android 
I got this error followed the instruction

Execution failed for task ':react-native-navigation:compileReleaseAidl'.
> java.lang.IllegalStateException: aidl is missing

my MainApplication.java

`package com.swiftalertsmobile;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.oblador.vectoricons.VectorIconsPackage;
import com.reactnativenavigation.NavigationApplication;

import java.util.Arrays;
import java.util.List;

//public class MainApplication extends Application implements ReactApplication {
//
//  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
//    @Override
//    public boolean getUseDeveloperSupport() {
//      return BuildConfig.DEBUG;
//    }
//
//    @Override
//    protected List<ReactPackage> getPackages() {
//      return Arrays.<ReactPackage>asList(
//          new MainReactPackage(),
//          new VectorIconsPackage()
//      );
//    }
//
//    @Override
//    protected String getJSMainModuleName() {
//      return "index";
//    }
//  };
//
//  @Override
//  public ReactNativeHost getReactNativeHost() {
//    return mReactNativeHost;
//  }
//
//  @Override
//  public void onCreate() {
//    super.onCreate();
//    SoLoader.init(this, /* native exopackage */ false);
//  }
//}
public class MainApplication extends NavigationApplication {

  @Override
  public boolean isDebug() {
    // Make sure you are using BuildConfig from your own application
    return BuildConfig.DEBUG;
  }

  protected List<ReactPackage> getPackages() {
    // Add additional packages you require here
    // No need to add RnnPackage and MainReactPackage
    return Arrays.<ReactPackage>asList(
            // eg. new VectorIconsPackage()
            new VectorIconsPackage()
    );
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }
}
`

**Comment by rlam3** [comment]
were you able to figure this out @Proxy08 ?

**Comment by Proxy08** [comment]
yes @rlam3, I did solve it, the problem was coming from one of Android platform which was not correctly installed ( android sdk 26.0.2), check your Android sdk using Android studio, when you will find the faulty one uninstalled and reinstall it . let me know if it works.

**Comment by rlam3** [comment]
@Proxy08 

Is this what you're talking about? I tried installing and reinstalling them and it doesn't seem to be working. 

<img width="772" alt="screen shot 2018-04-07 at 7 47 44 am" src="https://user-images.githubusercontent.com/1154044/38455058-ff578dc4-3a37-11e8-8219-c57a0ed206bb.png">

**Comment by Proxy08** [comment]
click on show package details, and if you can post the error as well I might able to figure out which packages is faulty
