### ISSUE TITLE
[iOS] navBarTextColor doesn't change when setting it dynamically

### ISSUE THREAD

**Issue by vranjesluka** [wix/react-native-navigation#2818]
### Issue Description

navBarTextColor doesn't change when setting it dynamically on iOS.
It worked in previous versions but in latest versions, it does not.
Also, it works on Android.

### Steps to Reproduce / Code Snippets / Screenshots
Inside the component class:
```
static navigatorStyle = {
    navBarTextColor: '#000000',
};
```

Dynamically changing: 
```
this.props.navigator.setStyle({
	navBarTextColor: '#FFFFFF'
});
```
Tried to put it in `constructor`, `componentWillReceiveProps` and `render` it doesn't work anywhere.
I need it in `componentWillReceiveProps`. (also tried with `nextProps`)

---
### Environment
* React Native Navigation version: 1.1.398
* React Native version: 0.54
* Platform: iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iPhone X, 11.2, debug

**Comment by zhaiyjgithub** [comment]
+ 1 same issue.

**Comment by dhamdani666** [comment]
Are you using navigation v1 on ios ?
Is it running ?

**Comment by vranjesluka** [comment]
@dhamdani666 
Yes, I'm using v1 of the library, specifically, we are using version 1.1.398
Sorry, I don't understand the question if it is running?

**Comment by JeJan** [comment]
same Issue here

**Comment by leograde** [comment]
Same problem here.

**Comment by nerdchandise** [comment]
Workaround working for me with v1.1.412:

```
this.props.navigator.setTitle({
  title: 'New Title'
});

this.props.navigator.setStyle({
  navBarTextColor: '#f0f'
});
```

Its important to call setTitle **before** setStyle.
