### ISSUE TITLE
HIDING SOFT NAVBAR ANDROID

### ISSUE THREAD

**Issue by olejka91** [wix/react-native-navigation#2819]
### Issue Description
I have written a native module for react-native for hiding/showing soft navigation bar on Android (Java). It works well on static pages with the navigator. It hides soft bar and shows it when I need on static pages, but when I open a modal window and try to call method hide of my module it does not work as it should be. It works only when I go back to the static pages.

Expected behavior: Module must hide the soft navigation bar anytime when its called.

Actual: Module works only on static pages and does not work when open modal windows with react-native-navigation

### Steps to Reproduce / Code Snippets / Screenshots
1.  Create react-native-app using react-native-init testProj, etc. 
2. Add a folder in android -> app -> src -> main -> java -> com -> testpoj  and name it ToggleSoftKeys
3. Add ToggleSoftKeysModule.java file into ToggleSoftKeys folder with following code 
`
package com.testproj.ToggleSoftKeys;

        import com.facebook.react.bridge.ReactContextBaseJavaModule;
        import com.facebook.react.bridge.ReactApplicationContext;
        import com.facebook.react.bridge.ReactMethod;

        import java.lang.Runnable;
        import android.app.Activity;
        import android.view.View;

        public class ToggleSoftKeysModule extends ReactContextBaseJavaModule {
            public ToggleSoftKeysModule(ReactApplicationContext reactContext) {
                super(reactContext);
       }

         @Override
         public String getName() {
               return "ToggleSoftKeys";
          }

             @ReactMethod
               private void hide() {
                 final Activity reactActivity = getCurrentActivity();
                  final int flags = View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                        | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                        | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                        | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                        | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;

        if (reactActivity != null) {
            reactActivity.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    reactActivity.getWindow()
                            .getDecorView()
                            .setSystemUiVisibility(flags);
                }
            });

        }

              }

              @ReactMethod
               private void show() {
                  final Activity reactActivity = getCurrentActivity();
                   final int flag = View.SYSTEM_UI_FLAG_VISIBLE;

                  if (reactActivity != null) {
                     reactActivity.runOnUiThread(new Runnable() {
                      @Override
                      public void run() {
                         reactActivity.getWindow()
                            .getDecorView()
                            .setSystemUiVisibility(flag);
                   }
                 });
                }
              }
         }
`

4. Add ToggleSoftKeysPackage.java file into ToggleSoftKeys folder with following code
`
  package com.testproj.ToggleSoftKeys;

        import com.facebook.react.ReactPackage;
        import com.facebook.react.bridge.JavaScriptModule;
        import com.facebook.react.bridge.NativeModule;
        import com.facebook.react.bridge.ReactApplicationContext;
        import com.facebook.react.uimanager.ViewManager;

        import java.util.ArrayList;
        import java.util.Collections;
        import java.util.List;

        public class ToggleSoftKeysPackage implements ReactPackage {
            @Override
            public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
                 List<NativeModule> modules = new ArrayList<>();
                modules.add(new ToggleSoftKeysModule(reactContext));
                  return modules;
          }

             public List<Class<? extends JavaScriptModule>> createJSModules() {
                  return Collections.emptyList();
             }          

           @Override
            public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
                 return Collections.emptyList();
         }
       }
`
5. Import module to MainApplication.java file with 
`
    import com.testproj.ToggleSoftKeys.ToggleSoftKeysPackage;
    ...
    protected List<ReactPackage> getPackages() {
           return Arrays.<ReactPackage>asList(
              ... ,
              new ToggleSoftKeysPackage()
            );
      }
`
6.  Start the react-native server with npm start command
7. Build for android with react-native run-android
8. Add module with  import { NativeModules } from 'react-native'
NativeModules.ToggleSoftKeys  (hide/show) methods
9. Hide soft navbar keys when open modal window with react-native-navigation
---
### Environment
* React Native Navigation version: 1.1.369
* React Native version: 0.50.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Emulator Pixel_2_API_25

**Comment by guyca** [comment]
Hey, a modal is implemented using a Dialog - which has a different window then the Activity.
We're planning to switch from Dialog to a simple view in v2, but that might be in2-3 months from now.
I'm closing as I'm not sure I can assist you further.
