### ISSUE TITLE
leftButton not appear.

### ISSUE THREAD

**Issue by igor-nm** [wix/react-native-navigation#2821]
### Issue Description
Hello guys, everything good ?
I'm having a problem with the leftButton, they work normally while I'm debugging and with the usb cable plugged, but when I removed the cable, and opened the application again, the leftButton does not appear.
Does anyone know why this occurs? And how can I solve it?

### Steps to Reproduce / Code Snippets / Screenshots
![screenshot from 2018-03-06 12-08-16](https://user-images.githubusercontent.com/20232832/37039809-1bb26d64-2137-11e8-9376-53fa5f71e389.png)

---
### Environment
* React Native Navigation version: v1
* React Native version: 0.54
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device and emulator (both OS: 7.1.1)

**Comment by karlmosenbacher** [comment]
Is navigatorButtons correct? Have you tried setButtons?

**Comment by igor-nm** [comment]
Yes, navigatorButtons is correct, I tried to use setButtons and I had the same result.
I will try to use api v2.
Thank's @karlmosenbacher.

**Comment by karlmosenbacher** [comment]
Well, if you are using RNN version 1 you should stick to that API instead. Thought you had written V2 in your environment description?. 
But I have seen quite many issues regarding navigatorButtons on Android lately so you are definitely not the only one. Do we know if version 1 still gets updated?

**Comment by igor-nm** [comment]
I wrong description of the problem, but I straightened. (I so sorry)
I tried using v2, but still there is not much implementation there, and for my needs I still use v1.
Now, by answering your question, I do not know if v1 still gets updates, but I hope so.

**Comment by sytolk** [comment]
@igor-nm leftButton id have limited values (its not like right Button) id can be only sideMenu, back..
try this:
```
leftButtons: [{
            id: 'sideMenu'
        },{
            id: 'back',
            title: 'Back',
        }
]
```

**Comment by igor-nm** [comment]
Hi @sytolk, i tried change of id's, but do continue to happen the problem. I'll show you an example of how it was: 
![screenshot from 2018-03-08 18-48-03](https://user-images.githubusercontent.com/20232832/37178449-4964d7da-2301-11e8-9851-ff274262addc.png)

Any solution is welcome.

**Comment by igor-nm** [comment]
@sytolk The application uses the singleApplication concept, so when I browse between screens, which is currently logged in and talk, I use navigation.resetTo ('MyScreen').
My OS is android, but I testing in apple OS too.

**Comment by adrienthiery** [comment]
@igor-nm : In dev, Images are served by the packager, so if you unplug the device and restart the application, it might not be able to load the image (because the connection to the packager goes through the cable).

This is not a react-native-navigation bug.

**Comment by sytolk** [comment]
@adrienthiery I see that you are far away from this issue :) but can you try to repeat this (unplug the device and so on..) with Android emulator ;)

**Comment by adrienthiery** [comment]
@sytolk, not sure what you mean by `unplug the device with the Android emulator` ?

**Comment by sytolk** [comment]
@adrienthiery I mean that the tales with packager and USB cable is not for this issue.. you can try to use emulator instead ;)

**Comment by sytolk** [comment]
Ah, good reason @adrienthiery :+1:  but I fall into this issue from the title only and this part miss me in my reading by diagonal..

**Comment by igor-nm** [comment]
This problem happen when are debug mode, but when started as release not happen none problem and that's why that I'm closing this problem.
