### ISSUE TITLE
[V1] Android doesn't show number on badge

### ISSUE THREAD

**Issue by brunolemos** [wix/react-native-navigation#2823]
<div>
<img width="340" alt="ios_screenshot" src="https://user-images.githubusercontent.com/619186/37062035-0c2f485c-2174-11e8-9d54-54159e4f23ff.png" />

<img width="300" alt="android_screenshot" src="https://user-images.githubusercontent.com/619186/37061868-958ea4ea-2173-11e8-9848-8c6a59630fbf.png" />

</div>

---
### Environment
* React Native Navigation version: 1.1.365
* React Native version: 0.52.2
* Platform(s) (iOS, Android, or both?): Android
* Device info: Android Simulator API 27

**Comment by guyca** [comment]
Are you passing the number as test? did you set `bottomTabBadgeTextColor`?

**Comment by brunolemos** [comment]
@guyca ops, `bottomTabBadgeTextColor` was set to the main app color which is red-ish, let's pretend this issue never happened
