### ISSUE TITLE
[v2] topBar hideOnScroll, animateHide issue on iOS

### ISSUE THREAD

**Issue by jeprojects** [wix/react-native-navigation#2829]
### Issue Description

Before this was working fine on iOS but in the latest version (RNN 2.0.2160) there is no animation when hiding the topBar with hideOnScroll: true and once the topBar is hidden, you can not see it again

### Steps to Reproduce / Code Snippets / Screenshots

hideOnScroll: true
animateHide: true

Main container view is SafeAreaView

Scroll down and the topBar will hide and not animate like before. Scroll up and the topBar will not show again. 

---
### Environment
* React Native Navigation version: 2.0.2160
* React Native version: 0.54.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iOS 10.3 (iPhone 6) & iOS 11 (iPhone X)

**Comment by yogevbd** [comment]
@jeprojects we changed properties `animateHide` to `animate` and `hidden` to `visible`
