### ISSUE TITLE
[v2] BottomTabs are hidden in the release build of Android app

### ISSUE THREAD

**Issue by kingstenbanh** [wix/react-native-navigation#2831]
### Issue Description
The bottom tabs navigation is hidden when building the release version of the Android app. I thought our app does something funky that making the tabs hidden. However, when building the Playground app from `react-native-navigation`, the bottom tab is also hidden

### Steps to Reproduce / Code Snippets / Screenshots
1. Clone the `react-native-navigation` library
2. `yarn install`
3. `cd playground/android`
4. './gradlew installRelease`
5. Open the Playground app and click on `SWITCH TO TAB BASED APP`
6. The bottom tabs are hidden

![screenshot_20180307-152659](https://user-images.githubusercontent.com/7540669/37122077-60862aee-221c-11e8-9a72-4fe326d2d296.png)

---
### Environment
* React Native Navigation version: 2.0.2159
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung S8

**Comment by kingstenbanh** [comment]
@guyca: Would you please take a look at this? When I built v2 in the release build of Android, the bottom tab disappear, but not in debug mode

**Comment by michael-gillett** [comment]
I was curious if this had to do with the `minifyEnabled` setting in `app/build.gradle` which can sometimes cause different behavior on release builds, but setting it to false in my app gives the same behavior
