### ISSUE TITLE
Android ANR

### ISSUE THREAD

**Issue by zsajjad** [wix/react-native-navigation#2833]
### Issue Description

We are having ANRs report on our play console:

* Input dispatching timed out (Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it. Outbound queue length: 0. Wait queue length: 1.)
com.reactnativenavigation.controllers.NavigationActivity

* Input dispatching timed out (Waiting because no window has focus but there is a focused application that may eventually add a window when it finishes starting up.)
com.app.MainActivity

* Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 11. Wait queue head age: 20702.9ms.)
com.reactnativenavigation.controllers.NavigationActivity

### Steps to Reproduce / Code Snippets / Screenshots

Production app

---
### Environment
* React Native Navigation version: 1.1.374
* React Native version: 0.53.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Release [Android 7.1,  Android 5.1, Android 6.0]

**Comment by ashokkumar88** [comment]
@zsajjad did you find any work around to fix this issue?
