### ISSUE TITLE
[v2] BackHandler works only in certain cases

### ISSUE THREAD

**Issue by RubenSandwich** [wix/react-native-navigation#2840]
### BackHandler works only in certain cases

Currently, BackHandler only works in certain cases. This case is currently:
1. Single View
2. Root View of Stack

BackHandler will never call:
1. Any view besides the root view of the stack
2. On a modal

This is due to the way the BackHandler is used in React Native Navigation. Basically when the hardware back button is press on Android the handleBack method on the current View Controller gets calls and will propagate back through the View Controllers, Stack Controller -> ViewController -> Navigator -> etc,  as long as the last method returned false this continues until it hits a view that returns true or it hits the app().getReactGateway().onBackPressed() which it then sends the back press to React Native.

However, because handleBack is always false on Controller:
https://github.com/wix/react-native-navigation/blob/v2/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ViewController.java#L66
If the controller is in a Modal or Stack then the BackHandler will never be called, because that Controller will be dismissed by the propagated handleBack function in the Stack Controller or Modal:

https://github.com/wix/react-native-navigation/blob/v2/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/StackController.java#L192

https://github.com/wix/react-native-navigation/blob/v2/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/modal/Modal.java#L55

This is a bit difficult to solve. I believe it was solved in react-native-navigation v1 through the `overrideBackPress` property. However, I believe a better solution is possible:

A `handleHardwareBack()` function on the React Native side could be added to the View Controller that if implemented presents calls the handleHardwareBack() implementation on the View Controller otherwise propagates false as normal.

I believe this is a better choice then overrideBackPress for a few reasons:
1. It reduces dependency on BackHandler
2. The handleHardwareBack function will work without registering or removing callbacks in another place
3. The handleHardwareBack now has to be located in the View in question

BackHandler can still be used in this case, but the use case for it is greatly reduced.

---
### Environment
* React Native Navigation version: 2.0.2159
* React Native version: 0.52.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device, All OS versions, Debug & Release

**Comment by guyca** [comment]
Hey @RubenSandwich
Thanks for the detailed bug report. I'm addressing the issue with Modals now but I'm not sure I understand other use cases you've described. Can you please give an example of a problematic layout?

**Comment by guyca** [comment]
@RubenSandwich I'm closing the issue, if you encounter more unsupported use cases, please PR a failing e2e detox test so we can easily reproduce and ensure we don't have regressions. Thanks.
