### ISSUE TITLE
onActivityCreated not applied to modals

### ISSUE THREAD

**Issue by brunolemos** [wix/react-native-navigation#2841]
### Issue Description

I was experimenting with this to fix some keyboard overlapping issues:

```java
@Override
public void onActivityCreated(Activity activity, Bundle savedInstanceState) {
    activity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN);
}
```

(`PAN` because for some reason `SOFT_INPUT_ADJUST_RESIZE` was not auto scrolling for me)

It works fine if I open the screen using `push`, but seems to have no effect when opening with `showModal`.

### Steps to Reproduce / Code Snippets / Screenshots

- Put the code above on android `MainApplication.java` `onCreate` method
- AndroidManifest: `android:windowSoftInputMode="adjustPan|adjustResize">`
- Create a big vertical screen with some textinputs
- Open this screen with push, autoscroll on input focus works
- Open this screen with showModal, autoscroll on input focus scrolls to wrong position

---
### Environment
* React Native Navigation version: 1.1.365
* React Native version: 0.54.0
* Platform(s) (iOS, Android, or both?): Android only
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator API 27, Debug

**Comment by guyca** [comment]
A Modal isn't an activity, it's implemented using Dialog. Therefore this method is irrelevant.
[This](https://github.com/wix/react-native-navigation/pull/1957/files) PR adds ability to adjust soft input mode for modals but never got merged for two reasons.

1. Styles should be applied inside the [Modal's](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java) constructor

2. soft input mode is [passed as an integer](https://github.com/wix/react-native-navigation/pull/1957/files#diff-9e199b8b9ab8f875d615bf21626ad8bfR25) which is really confusing. It should be passed as a string and parsed in native.

You're welcome to submit a PR based on this, ping me on discord if you need help 👍
