### ISSUE TITLE
how to scroll tab bar on the top!scroll doesn't mean swipe!attention

### ISSUE THREAD

**Issue by TheIdhem** [wix/react-native-navigation#2844]
I'm beginners in using react-native-navigation and I want to know if I have too many tabs and I want to scroll the tabs what should I do!?

![1](https://user-images.githubusercontent.com/31737620/37244027-026ab622-2498-11e8-8591-a58295a2178b.jpg)

**Comment by guyca** [comment]
@TheIdhem You can set `topTabsScrollable: true` in `navigatorStyle

**Comment by Shubham-Sinha** [comment]
@Theldhem How did you implement top tabbar ?
