### ISSUE TITLE
android build failed - cannot find symbol NavigationApplication

### ISSUE THREAD

**Issue by sagic** [wix/react-native-navigation#285]
i created a clean react-native project, followed the instruction for android and i'm stuck with this:

```
... error: cannot find symbol 
import com.reactnativenavigation.NavigationApplication
```

i tried: `/android $ ./gradlew clean`

my settings.gradle file contains:
```
...
include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/android/app/')

```
any help will be appreciated,
thanks

**Comment by kevinnguy** [comment]
This might help you: https://github.com/wix/react-native-navigation/issues/223

**Comment by kevinnguy** [comment]
I'm having issues running a clean project on Android as well. I hope the docs get updated soon...

**Comment by guyca** [comment]
Make sure you've updated the gralde file in you application's root directory  (not the one under `app` folder)
You need to pull RN from `node_modules`, something like this:

```groovy
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$projectDir/../../node_modules/react-native/android"
        }
    }
}
```

**Comment by DanielZlotin** [comment]
What version of RN and navigation do you use?

**Comment by kevinnguy** [comment]
```
"dependencies": {
    "react": "15.3.1",
    "react-native": "0.32.0",
    "react-native-navigation": "^1.0.30",
    "redux": "^3.6.0"
  }
```

**Comment by kevinnguy** [comment]
I ran `npm install react-native-navigation --save` from the iOS installation instructions. Should I be pulling from master instead?

**Comment by guyca** [comment]
@kevinnguy v1.0.30 isn't maintained. We're in the middle of transitioning to v2.0, you can use it by setting `next` tag in `package.json` (instead of `^1.0.30`).
We're using v2.0 in production, feel free to give it a try.

**Comment by sagic** [comment]
sorry for the delay @guyca . i have the same dependencies as @kevinnguy.
trying to upgrade to v2.0 ...
thanks

**Comment by kevinnguy** [comment]
Thanks for the help @guyca ! I'm now experiencing crashes on Android with my clean project app. Hope this can get ironed out!

**Comment by sagic** [comment]
yep, thanks for the help @guyca!
i can confirm that the build is passing.
now i got the crashes like @kevinnguy

**Comment by guyca** [comment]
@kevinnguy @sagic Can you please provide logs?

**Comment by guyca** [comment]
@kevinnguy @sagic Did you follow the [Installation guide](https://github.com/wix/react-native-navigation/wiki/Installation---Android) and the [migration guide to v2](https://github.com/wix/react-native-navigation/wiki/Migrating-to-version-2.0) ?

**Comment by sagic** [comment]
yes, i followed the guides and i think it's all good.
here is the log:

09-07 16:34:16.769 I/ActivityManager(  580): Start proc com.fooapp for activity com.fooapp/.MainActivity: pid=1622 uid=10061 gids={50061, 3003, 1028, 1015}
09-07 16:34:16.785 I/dalvikvm( 1622): Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method android.support.v7.view.WindowCallbackWrapper.onProvideKeyboardShortcuts
09-07 16:34:16.785 W/dalvikvm( 1622): VFY: unable to resolve interface method 20203: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
09-07 16:34:16.785 D/dalvikvm( 1622): VFY: replacing opcode 0x72 at 0x0002
09-07 16:34:16.793 W/dalvikvm( 1622): VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
09-07 16:34:16.793 I/dalvikvm( 1622): Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
09-07 16:34:16.793 W/dalvikvm( 1622): VFY: unable to resolve interface method 20205: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
09-07 16:34:16.793 D/dalvikvm( 1622): VFY: replacing opcode 0x72 at 0x0002
09-07 16:34:16.793 I/dalvikvm( 1622): Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
09-07 16:34:16.793 W/dalvikvm( 1622): VFY: unable to resolve interface method 20209: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
09-07 16:34:16.793 D/dalvikvm( 1622): VFY: replacing opcode 0x72 at 0x0002
09-07 16:34:16.793 I/dalvikvm( 1622): Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
09-07 16:34:16.793 W/dalvikvm( 1622): VFY: unable to resolve virtual method 557: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
09-07 16:34:16.793 D/dalvikvm( 1622): VFY: replacing opcode 0x6e at 0x0002
09-07 16:34:16.793 I/dalvikvm( 1622): Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
09-07 16:34:16.793 W/dalvikvm( 1622): VFY: unable to resolve virtual method 579: Landroid/content/res/TypedArray;.getType (I)I
09-07 16:34:16.793 D/dalvikvm( 1622): VFY: replacing opcode 0x6e at 0x0008
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): Exception while inflating <vector>
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:708)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:348)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at com.reactnativenavigation.controllers.SplashActivity.onCreate(SplashActivity.java:16)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.app.Activity.performCreate(Activity.java:5231)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.os.Looper.loop(Looper.java:136)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at java.lang.reflect.Method.invoke(Method.java:515)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
09-07 16:34:16.797 E/VdcInflateDelegate( 1622): 	at dalvik.system.NativeStart.main(Native Method)
09-07 16:34:16.797 D/AndroidRuntime( 1622): Shutting down VM
09-07 16:34:16.797 W/dalvikvm( 1622): threadid=1: thread exiting with uncaught exception (group=0xa4d51b20)
09-07 16:34:16.797 E/AndroidRuntime( 1622): FATAL EXCEPTION: main
09-07 16:34:16.797 E/AndroidRuntime( 1622): Process: com.fooapp, PID: 1622
09-07 16:34:16.797 E/AndroidRuntime( 1622): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fooapp/com.fooapp.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.os.Looper.loop(Looper.java:136)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at java.lang.reflect.Method.invokeNative(Native Method)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at java.lang.reflect.Method.invoke(Method.java:515)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at dalvik.system.NativeStart.main(Native Method)
09-07 16:34:16.797 E/AndroidRuntime( 1622): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020013
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.content.res.Resources.loadDrawable(Resources.java:2096)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.content.res.Resources.getDrawable(Resources.java:700)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:354)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at com.reactnativenavigation.controllers.SplashActivity.onCreate(SplashActivity.java:16)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.app.Activity.performCreate(Activity.java:5231)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	... 11 more
09-07 16:34:16.797 E/AndroidRuntime( 1622): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	at android.content.res.Resources.loadDrawable(Resources.java:2092)
09-07 16:34:16.797 E/AndroidRuntime( 1622): 	... 30 more
09-07 16:34:16.801 W/ActivityManager(  580):   Force finishing activity com.fooapp/.MainActivity
09-07 16:34:16.913 D/        (  580): HostConnection::get() New Host Connection established 0xb7ca0bd0, tid 786
09-07 16:34:17.101 D/dalvikvm(  580): GC_FOR_ALLOC freed 1737K, 30% free 11014K/15664K, paused 8ms, total 8ms
09-07 16:34:17.157 D/MobileDataStateTracker(  580): default: setPolicyDataEnable(enabled=true)
09-07 16:34:17.609 W/ActivityManager(  580): Activity pause timeout for ActivityRecord{529a76e8 u0 com.fooapp/.MainActivity t3 f}
09-07 16:34:17.665 W/EGL_genymotion(  754): eglSurfaceAttrib not implemented
09-07 16:34:17.741 D/MobileDataStateTracker(  580): default: setPolicyDataEnable(enabled=true)
09-07 16:34:17.773 D/MobileDataStateTracker(  580): default: setPolicyDataEnable(enabled=true)

**Comment by guyca** [comment]
@sagic I googled `Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml` and found [this](http://stackoverflow.com/questions/35739743/file-res-drawable-abc-ic-ab-back-material-xml-from-drawable-resource-id-0x7f020) thread on SO

**Comment by sagic** [comment]
updating support dependencies to 23.4 and gradle to 2.1 did the trick.
thanks :)

/android/app/build.gradle
```
compile 'com.android.support:appcompat-v7:23.4.0'
compile 'com.android.support:support-v4:23.4.0'
```

/android/build.gradle
```
classpath 'com.android.tools.build:gradle:2.1.0'
```

**Comment by DanielZlotin** [comment]
@sagic so can I close this?
