### ISSUE TITLE
background flash when show/hide keyboard in android dialog

### ISSUE THREAD

**Issue by redrose218** [wix/react-native-navigation#2852]
### Issue Description

the issue occurred in android dialog
used Navigation.showModal() method

### Steps to Reproduce / Code Snippets / Screenshots

video feedback:
https://drive.google.com/open?id=1dTZwwfQD0VSVqWmvvDpToO0m1QpBANj-

---
### Environment
* React Native Navigation version: 1.1.396
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device. 7.0, Both

**Comment by redrose218** [comment]
I fixed it by using SOFT_INPUT_ADJUST_PAN instead of SOFT_INPUT_ADJUST_RESIZE in the following file.
android/app/src/main/java/com/reactnativenavigation/controllers/Modal.java Line 163
window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
I am open to better solutions in wix team :)

**Comment by TomAtterton** [comment]
https://github.com/wix/react-native-navigation/pull/1957 

This PR would also solve your problem, but no one seems to be picking it up.

**Comment by binbinla** [comment]
same issue here. Is there any solution?

**Comment by L-Yeiser** [comment]
@binbinla we used a bit of a JS hack to get around this issue. Basically we animate a white underlay up on the screen as the modal is pushed up.

**Comment by rendomnet** [comment]
Same here
