### ISSUE TITLE
[Android] tabBar jumps up and down for a second on pop

### ISSUE THREAD

**Issue by ahoseinian** [wix/react-native-navigation#2854]
### Issue Description

tabbar goes hidden, shown for a second, and then hidden again when poping the screens that have toggleTabs on android.

### Steps to Reproduce / Code Snippets / Screenshots
On Android:
push couple of screens 
`this.props.navigator.toggleTabs` to `hidden` on `willAppear` and `willDisappear`

`this.props.navigator.toggleTabs` to `shown` after some interaction on the screen

pop the screen observe that the tabbar first hides, then shows for a second, and then hides again...

On `IOS` it is working as expected

---
### Environment
* React Native Navigation version: 1.1.385
* React Native version: 0.52
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All android devices and simulator

**Comment by ahoseinian** [comment]
@guyca @DanielZlotin can you help me out here a bit please? :)

**Comment by barjas** [comment]
same issue , on android. tabBar jumps up and down for a second pushscreen between 2 screens when its hidden
