### ISSUE TITLE
App crashes on Android when react-native-camera is installed

### ISSUE THREAD

**Issue by arapocket** [wix/react-native-navigation#2856]
### Steps to reproduce
1. Create empty project and manually install react-native-camera and verify you can install it correctly
2. Create empty project and manually install react-native-navigation and verify you can install it correctly
3. Try to add react-native-navigation to the react-native-camera project

### Expected behaviour
App should run with no problems

### Actual behaviour
App builds successfully but crashes before opening on Android. Everything works fine on iOS.

### Environment
- **Node.js version**: v8.9.4
- **React Native version**: 0.54.0
- **React Native platform + platform version**: Android simulator (most recent version?)

### react-native-camera
**Version**: npm version
**____________________________________________________________________________________________________**
**Relevant Code**
**____________________________________________________________________________________________________**

**MainApplication.java**

```
package com.androidtest;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;
import org.reactnative.camera.RNCameraPackage;
import com.reactnativenavigation.NavigationApplication;

public class MainApplication extends NavigationApplication {


	@Override
	public boolean isDebug() {
		// Make sure you are using BuildConfig from your own application
		return BuildConfig.DEBUG;
	}

    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNCameraPackage()
      );
    }

    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
      return getPackages();
    }

    @Override
public String getJSMainModuleName() {
	return "index";
}

}

```

**MainActivity.java**

```
import com.reactnativenavigation.controllers.SplashActivity;

public class MainActivity extends SplashActivity {

}
```

**Comment by arapocket** [comment]
Well it miraculously started working so closing for now but if anyone has similar issues please chime in.

**Comment by balazs31** [comment]
@ajaykumar97  Any update? Did you solve it? I encountered the same problem just now.

**Comment by ajaykumar97** [comment]
try the following configuration in build.gradle file:
```
compile (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
        compile ('com.android.support:exifinterface:28.0.0')
        compile ('com.google.android.gms:play-services-vision:16.2.0') {
            force = true
        }
    }
```

That is probably the google play services or exifinterface version issue.

**Comment by balazs31** [comment]
@ajaykumar97 Nope, still crashing.
