### ISSUE TITLE
Unsure how to do a replace?

### ISSUE THREAD

**Issue by cymen** [wix/react-native-navigation#286]
I'm reading https://github.com/wix/react-native-navigation/wiki/Screen-API and it isn't clear to me how to do the equivalent of `replace` (present in [React Native Navigator](https://facebook.github.io/react-native/docs/navigator.html#replace)). Am I missing something obvious or is this difficult to do?

If it's just the need to do the PR to implement it in react-native-controllers (well, that code after it is merged to this repo), I'd be happy to do it. It appears to be possible on the iOS side:

``` obj-c
NSArray * viewControllers = [self.navigationController viewControllers];
NSArray * newViewControllers = [NSArray arrayWithObjects:[viewControllers objectAtIndex:0], [viewControllers objectAtIndex:1], thirdController,nil];
[self.navigationController setViewControllers:newViewControllers];
```

**Comment by huyphan** [comment]
@drorbiran: I see the issue was assigned to you but it was 2 months ago. Do you have any plan to work on this feature? I'd love to contribute a PR for this but want to make sure there's no duplication of work.

**Comment by guyca** [comment]
@huyphan I think we're missing a few methods in our navigator object, replace is one of them. I'll push to implement them asap but we're already behind schedule on v2.0, so it might take some time (we originally aimed for a late November release).

**Comment by huyphan** [comment]
Cool, I already have `replace` implemented here as I really need it for my project. If you haven't started working on that yet, I'd be happy to send a PR.

**Comment by guyca** [comment]
@huyphan Can you please describe the use case for which you need `replace`? We had a little discussion about a few methods some of the users were missing (replace, replaceAtIndex, replacePrevious, replacePreviousAndPop) and the consensus was that this set of functions indicates misused design patters, and there for we shouldn't implement them.

When a user navigates back in the stack, he expects to see the previous screen he came from. If you want to "branch" out of the current stack state, a modal should be used.

**Comment by tdzl2003** [comment]
I have this scene:

User opened app, there's home page.

User want to buy something, so we push screen 'sale.GoodInfo'.

On sale page, user want to login, so we push screen 'auth.Login'. Now the stack is: 

Home -> sale.GoodInfo -> auth.Login

Then user found he needs to register first, so we should jump to register page, but after register, user should back to sale.GoodInfo page instead of auth.Login page, so we want the next state to be:

Home -> sale.GoodInfo -> auth.Register

Here's one case that we need replace.

Run `this.props.navigator.pop(`) twice doesn't work.

**Comment by guyca** [comment]
@tdzl2003 I think you're misusing `push` in this case.

consider modifying your code as follows:
Home -> push(sale.GoodInfo) -> showModal(auth.Login) -> push(register) -> _user finished registeration_ -> dismissModal()

I was in favor of adding `replace` (and we might still add it) but all of the use cases for replace I've seen so far can, and should, be solved by using modals when appropriate.
Modal should be used when ever you need to branch out of your main flow into a secondary flow. When the secondary flow, which is displayed in a modal, ends - dismiss the modal and you're back to the screen you branched out of.

**Comment by Kureev** [comment]
Hi there,

Can you please update me with the status of this issue? Seems like the initial topic has been addressed, so we can probably close this one and exclude it from the 2.0 roadmap?

**Comment by DanielZlotin** [comment]
As @guyca said, as it stands right now, we won't be adding a `replace` screen feature as it's a misuse of the stack API (and will probably cause weird UI bugs anyway).
If need arises and enough people want it, we can rethink, but currently this will not be added to the roadmap.

**Comment by hose314** [comment]
https://github.com/react-community/react-navigation/issues/774

Seems like such function is very common. And also for me. When app back from background how to redirect to certain screen immediately  for example `[home screen, product screen, product checkout screen]`?

**Comment by guyca** [comment]
What do you mean redirect? If you want to push a screen - call push, if you want to show a modal - show a modal - if you want to reset reset the current stack - call resetTo.

**Comment by hose314** [comment]
@guyca Thanks for answer. 

Imagine that app starts by tab based app then user push to OrderCard screen than push OrderFull Info screen and then user close app. My question is how to start tab based (user see OrderFull Info screen and can pop to OrderCard screen) app with given stack from cold start?

**Comment by guyca** [comment]
Hey @hose314 
If the user closed the app with the back button - the app's navigation state is cleared. If you want to restore a previous state - it's your responsibility to cache and restore it.

Native apps don't persist navigation state (Activity stack state) when the app is closed.
I assume you already persist checkout flow data, when the app is opened and there was incomplete checkout flow - I suggest you show a modal and continue checkout flow in the modal. Instead of pop, call resetTo in order to go to previous screens in the flow etc.

**Comment by hose314** [comment]
@guyca Thanks! Agree with your suggestion

**Comment by ddeath** [comment]
@guyca thanks for example. Just wanted to add that for proper function you have to add also

```
onNavigatorEvent(event) {
    switch(event.id) {
      case 'willDisappear':
        this.props.navigator.dismissModal();
        break;
    }
  }
```

without this code it will not work if user press back button.

**Comment by jeffreznik** [comment]
I'm using the modal approach to branch off to a secondary flow, and need the ability to push navigate automatically to another screen after the modal is dismissed.  This seems to be a common use case where an unauthenticated user tries to access a protected resource, you show a modal to log them in, then when you dismiss the modal you send the user to the protected resource. What is the preferred way to do this with RNN?

**Comment by guyca** [comment]
@jeffreznik Instead of dismissing a modal and calling push/resetTo to navigate to another screen, I would call `startSingleScreenApp`/`startTabBasedApp` and show the "protected" screen in a new app instance

**Comment by Gujie-Novade** [comment]
I had a pretty similar scenario as @jeffreznik when I tried building a wizard.
I posted an answer on SO: https://stackoverflow.com/a/55448286/3466729
I hope this may help someone.
