### ISSUE TITLE
Navigator Screen Replace Problem

### ISSUE THREAD

**Issue by andrei0807** [wix/react-native-navigation#2860]
### Issue Description

I am going to replace now screen to other screen.
and I want to preserve now call stack.
But i could not found replace function in react native navigator.
How do it?. Please help me!!!

**Comment by seahorsepip** [comment]
First pop the current screen and then push the replacement screen has the same effect.

**Comment by andrei0807** [comment]
Thanks for your response, But i don't want to show screen change effect

**Comment by seahorsepip** [comment]
In that case you can change the current screen navigatorStyle and change the render content to the content of the new screen.

This might not the best solution but I don't know any other way.

**Comment by andrei0807** [comment]
Ok. Can you send me code?

**Comment by Noitidart** [comment]
@seahorsepip - this doesn't work if we are on the first screen. Doing a `pop` does nothing. Is there any other way? My first screen is a login screen.

**Comment by Noitidart** [comment]
Also @seahorsepip doing a `pop` then `push` makes us see the previous screen during transition. Is it possible to `push` and then `pop` so we dont see the previous? I tried this but it doesnt work.

**Comment by sebringj** [comment]
I went here hoping there was some method to do this... the realized there is. Use setRoot and set it to where you want to be in the stack and it will just replace without animation.

***example jump from Login to Signup***
```
    Navigation.setRoot({
      root: {
        stack: {
          children: [
            { component: { name: 'Splash' } },
            { component: { name: 'SignUp' } },
          ]
        }
      }
    })
```

**Comment by seahorsepip** [comment]
@sebringj
This results in a white screen sometimes on Android last time I tried it. It wasn't a problem on my own device (pixel 2) but one someone else's one plus  the screen wasn't replaced but showed a white screen or crashed instead.
