### ISSUE TITLE
Debug overdraw on pushing and popping a screen on Android

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#2861]
### Issue Description

I am debugging some performance issues in my app. I ran systrace on the app and found a few frames show up as yellow. On viewing more details about the frame drop issue, I see the alert at `Long View#draw()` which means that I am overdrawing. I started debugging the overdraw by enabling the GPU overdraw and found that we always overdraw a lot during the navigator transitions. Please see the attached screen recording. Observe that whenever I push a new screen or pop a screen, the screen become red occasionally which means that the view was overdrawn more than 4 times.

[pixel_overdraw_capture.mp4.zip](https://github.com/wix/react-native-navigation/files/1807660/pixel_overdraw_capture.mp4.zip)

I am not sure if this is something that needs to be looked into or how can I debug this problem.

### Steps to Reproduce / Code Snippets / Screenshots

Run the app with `Debug GPU Overdraw` enabled in the `Developer Options` settings.

---
### Environment
* React Native Navigation version: 1.1.387
* React Native version: 0.52.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by varungupta85** [comment]
@guyca I would love to get some feedback from you on this issue. I think it is related to the way screen transition animations are done. I disabled the animation to validate that theory and the overdraw problem definitely reduced. Instead of seeing the red flash, I now see a green flash.

**Comment by guyca** [comment]
Naturally there's overdraw when pushing screens as the previous screen is removed from the hierarchy after the push animation ends.

**Comment by varungupta85** [comment]
I was comparing the overdraw with other apps on Android such as Whatsapp, Gmail etc. and I don't see such flashes in those apps during screen transitions. I understand it may be a case of premature optimisation. Thanks for looking into it.
