### ISSUE TITLE
Two buttons in android Navbar.

### ISSUE THREAD

**Issue by lilitGrigoryan** [wix/react-native-navigation#2865]
Issue Description

i need two buttons on left navbar but on android shown only one button , how i can fix this?

---
### Environment
* React Native Navigation version:V1
* React Native version: 0.52
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): debug

**Comment by guyca** [comment]
That's currently not supported and also not planned. You can use a custom react view in TopBar or simply render the TopBar (toolbar/navBar) in jsx as part of your screen
