### ISSUE TITLE
Push View in topTabs.

### ISSUE THREAD

**Issue by lilitGrigoryan** [wix/react-native-navigation#2866]
Hi ,
i have a topTabs, when i trying push screen, my screen pushed but not us tab view, it pushed instend of tabs. 
How i can push view into tab?

### Environment
* React Native Navigation version: v1
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?):both
* Device info (Simulator/Device? OS version? Debug/Release?): debug

**Comment by guyca** [comment]
This feature is already implemented in v2. In v1 `TopTabs` only contains screens while in v2 each `TopTabs` child can be any layout type, including a `Screen Stack`.

**Comment by salisuabubakar** [comment]
Please can  you give example on how to create a toptabs in V2. Thanks
