### ISSUE TITLE
navBarButtonColor goes back to blue when pressed

### ISSUE THREAD

**Issue by JFE84** [wix/react-native-navigation#2868]
I'm using navBarButtonColor to change the back blue button color of iOS to black. It works fine until I press it, that's when it goes back to blue just before it fades away.

**Comment by karlmosenbacher** [comment]
I am also using navBarButtonColor on IOS, but I dont recognize the behaviour that you describes. Which version of RNN are you using?

**Comment by JFE84** [comment]
react-native-navigation@1.1.409

**Comment by krystofcelba** [comment]
@JFE84 Do you have the same `navBarButtonColor` set also on the screen above this one? 
Eg. If you are initializing your app using `Navigation.startSingleScreenApp` you have to call it like
```
Navigation.startSingleScreenApp({
  screen: {
    screen: 'example.WelcomeScreen',
    title: 'Welcome', 
    navigatorStyle: {
       navBarButtonColor: 'black'
    },
  },
});
```
even if there aren't any navigation bar buttons. 

It should work like expected if you push new screen from this one 🙂.

**Comment by JFE84** [comment]
yes I have that and still doing it

this is what is happening with the button
idle --- onpress --- release
![backbutton](https://user-images.githubusercontent.com/24555828/37742850-75b4bc78-2dbb-11e8-8320-f83e33e88c5b.png)

**Comment by karlmosenbacher** [comment]
hmm just a thought now, what animationType do you have to the screen when going back?

**Comment by JFE84** [comment]
```
this.props.navigator.push({
            screen: EditBasicInfoFormView.displayName,
            animationType: 'slide-horizontal',
            navigatorStyle: {
                navBarTitleTextCentered: true,
                navBarHidden: false,
                tabBarHidden: true,
                navBarButtonColor: backButton
            },
            title: 'Personal Details',
            backButtonTitle: ''
        });
```

**Comment by karlmosenbacher** [comment]
@JFE84 what animationType do you have when you "pop" back to the screen that calls "push" ?

**Comment by JFE84** [comment]
nothing, it goes back on its own using that same slide thing but I didn't do that
there is no code, it goes back without me doing anything
sometimes I add this.props.navigation.pop() if I want to go back after certain criteria without pressing the button but that's it
