### ISSUE TITLE
Top tabs bar, It's possible hide him ?

### ISSUE THREAD

**Issue by igor-nm** [wix/react-native-navigation#2871]
### Issue Description
I need use tabs bar, but I don't want leave visible the bar of the tab, and yes keep the action of slide of screen change. (I already tried use styles with hide)
Anybody help me?

### Environment
* React Native Navigation version: v1
* React Native version:v0.53
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Devices and emulator (Android 7.1.1, Iphone 7 ans X)

**Comment by guyca** [comment]
This feature is planned for v2
