### ISSUE TITLE
Error building Android, Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :react-native-navigation.

### ISSUE THREAD

**Issue by juanlet** [wix/react-native-navigation#2884]
Hello,

I'm following the steps on android but in android studio the build fails with the message. Gradle 4.1( I don't know if this is related)

Could not resolve project :react-native-navigation.
Required by:
    project :app
 > Unable to find a matching configuration of project :react-native-navigation: None of the consumable configurations have attributes.

> >  Error:Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :react-native-navigation.
> > <a href="openFile:/home/home/AndroidStudioProjects/MyApplication/app/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:app@debug/compileClasspath&#39;: Could not resolve project :react-native-navigation.">Show Details</a>
> > 
> 
> Error:Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :react-native-navigation.
> <a href="openFile:/home/home/AndroidStudioProjects/MyApplication/app/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:app@debugAndroidTest/compileClasspath&#39;: Could not resolve project :react-native-navigation.">Show Details</a>
> 
> Error:Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :react-native-navigation.
> <a href="openFile:/home/home/AndroidStudioProjects/MyApplication/app/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:app@debugUnitTest/compileClasspath&#39;: Could not resolve project :react-native-navigation.">Show Details</a>
> 
> Error:Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve project :react-native-navigation.
> <a href="openFile:/home/home/AndroidStudioProjects/MyApplication/app/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:app@release/compileClasspath&#39;: Could not resolve project :react-native-navigation.">Show Details</a>
> 
> Error:Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve project :react-native-navigation.
> <a href="openFile:/home/home/AndroidStudioProjects/MyApplication/app/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:app@releaseUnitTest/compileClasspath&#39;: Could not resolve project :react-native-navigation.">Show Details</a>
> 

I leave the details below(my user is called home, is not a typo): 

### Issue Description

local.properties file

`sdk.dir=/home/home/Android/Sdk`

settings.gradle

```
include ':app'
include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/android/app/')
```

App gradle file
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    defaultConfig {
        applicationId "com.example.home.myapplication"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "com.android.support:appcompat-v7:25.0.1"
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
   //tried implementation as well here instead of compile but didn't work either 
   compile project(':react-native-navigation')

}


### Environment
* React Native Navigation version: "1.1.370"
* React Native version: "0.52.0"
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Studio

**Comment by FakhruddinAbdi** [comment]
How did you fix it @guyca

**Comment by Abhishekgarg727** [comment]
??? any solution yet

**Comment by EricYuen** [comment]
I'm also having the same problem and could use some help.

**Comment by herarya** [comment]
How did you fix it ? @guyca @juanlet

**Comment by felgarte** [comment]
I need to know how fix this problem ASAP!

**Comment by lironsher** [comment]
Did someone was able to solve this?

**Comment by Ajaykumar02** [comment]
Target the React Native version required by your project by specifying the RNN build flavor in android/app/build.gradle

android {
    ...
    defaultConfig {
        applicationId "com.yourproject"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
+        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative56"
        versionCode 1
        versionName "1.0"
        ...
    }
    ...
}

RNN only support react-native 0.51 ("reactNative51"), 0.55 ("reactNative55"), and 0.56 ("reactNative56")

**Comment by PurnimaNaik** [comment]
Any updates here?

**Comment by Kolezhniuk** [comment]
The same problem, please help

**Comment by minhloi** [comment]
Okay, I finally found what causes the errors after 2 hours searching.

This line in settings.gradle is not correct:
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/android/app/')

It should be: (**Note there is lib folder**)
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/lib/android/app/')

I think most of us have this problem because react-native link put this line in for us incorrectly.

**Comment by SudoPlz** [comment]
You sir are amazing @minhloi

**Comment by LRNZ09** [comment]
The problem mentioned by @juanlet is happening even with a newly bootstrapped RN project, and the docs are also updated to @minhloi 's solution.

I've resolved setting explicitly a `configuration` param within `implementation` as this:
```groovy
implementation project(path: ':react-native-navigation', configuration: 'default')
```

@guyca can you confirm?

**Comment by mohsenhaghighatkhah** [comment]
I'm also having the same problem and could use some help. 
I try and test your answer and doesn't solve! 
any update here?

**Comment by mayuroks** [comment]
I already have lib in my path still I am getting this error
```
rootProject.name = 'RNNavProj'
include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, 
'../node_modules/react-native-navigation/lib/android/app/')
include ':app'
```

OS: Windows 10
react-native: 0.57.8
react-native-navigation": "^2.10.0"

**Comment by enavermate** [comment]
In the file ` android/app/build.gradle` 

android {
    ...
    defaultConfig {
        applicationId "com.yourproject"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        _**missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57"**_ 
        versionCode 1
        versionName "1.0"
    }
}

Write value according on RN version:

reactNative55 - RN 0.55.x
reactNative56 - RN 0.56.x
reactNative57 - RN 0.57.0 - 0.57.4
reactNative57_5 - RN 0.57.5 and above

**Comment by ch3cke** [comment]
the path is error, are you sure the path can find the project？

**Comment by snairsumith** [comment]
Any Updates?

**Comment by edritech93** [comment]
same for me

**Comment by gokuney** [comment]
I found a solution that worked for me, hope it does for others too.
Firstly follow @enavermate's comment above to set correct RN version, then: 
1. Update android studio to latest version
2. Import the "android" folder (in app's root folder) into the Android Studio | Some error might occur if 
2. Goto Build -> Clean Project 
3. Once the gradle sync is successful, go back to the RN project folder and hit react-native run-android. 

One of two things will happen, either the app will compile or new errors will appear 😂 , but this particular one will be resolved.

**Comment by keshav00001** [comment]
![image](https://user-images.githubusercontent.com/34762556/58366552-ab706a00-7ef1-11e9-9d4c-123e27d90db4.png)

**Comment by zcmgyu** [comment]
@keshav00001 Same here :(

**Comment by jivanpp** [comment]
It just your internet is slow & not downloading related files. So please do sync gradle when high speed .

**Comment by megacriativa** [comment]
"react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-notifications": "^3.2.2"

In settings.gradle...

project(':reactnativenotifications').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-notifications/**lib**/android/app')

**Comment by HadiNamazi** [comment]
you should just clean your project
