### ISSUE TITLE
Is there a way to get badge number from TabBar?

### ISSUE THREAD

**Issue by efstathiosntonas** [wix/react-native-navigation#2889]
### Issue Description

Is there a way to get the TabBar badge number without using redux or async storage.

I m adding items to a shopping basket, when i navigate to different products and add to basket again it resets to 0. 

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
Hey there,
That's not possible, you should keep track of this data yourself and not query RNN internals 👍

**Comment by efstathiosntonas** [comment]
@guyca thanks, i'll implement it on my own.
