### ISSUE TITLE
Is it possible to draw online image on tab bar item?

### ISSUE THREAD

**Issue by bdavid68** [wix/react-native-navigation#2897]
https://stackoverflow.com/questions/49384471/is-it-possible-to-draw-online-image-on-tab-bar-item

### Issue Description

I want to put online image on tab bar item. Is this possible?

<img width="531" alt="2018-03-20_2238" src="https://user-images.githubusercontent.com/15665426/37663133-4ecdd4f4-2ca4-11e8-8f69-022b787cb126.png">

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
I'm not sure this is currently possible, though we are planning on supporting custom react views as buttons, so you'll be able to implement this custom button in JSX
