### ISSUE TITLE
Pushing screen within secondary modal

### ISSUE THREAD

**Issue by kyle-lam** [wix/react-native-navigation#2899]
### Issue Description
Having issues pushing screens into a secondary (child) modal. The odd scenario is that the presence of a breakpoint in the child screen seems to make it work. The absence of a breakpoint causes the screen to not show

### Steps to Reproduce / Code Snippets / Screenshots

[fail case]
- open a modal
- push a few screens
- open a second (child) modal
- push a screen // screen does not render however the code is hit

[success case]
- open a modal
- push a few screens
- open a second (child) modal
- set a breakpoint anywhere in the screen which is about to be pushed
- push a screen // screen does not render however the code is hit
- see breakpoint and move past
- the screen is properly rendered

---
### Environment
* React Native Navigation version: 1.1.273
* React Native version: react-native: 0.51.0
* Platform(s) (iOS, Android, or both?): tested on ios
* Device info (Simulator/Device? OS version? Debug/Release?): simulator, debug

**Comment by guyca** [comment]
Hey @kyle-lam 
You can `await` `showModal` and interact with the modal after it's shown.

**Comment by LucianHij** [comment]
I am trying to push a screen from a `showModal` screen. I see here that you said this is possible. I call `Navigation.push(componentId, {some options})` from within a `showModal` but it seems it doesn't show any screen. Can you give a working example? Thanks!

**Comment by pk1m** [comment]
@LucianHij did you ever figure if this is possible?  I can't get it to work.
