### ISSUE TITLE
Is there a way to make the TabBar solid?

### ISSUE THREAD

**Issue by pvlvsk** [wix/react-native-navigation#29]
In TabBarIOS I had the choice to set the TabBar **translucent:false**. Is there a way with react-native-navigation to accomplish this?

Thank you!

**Comment by guyca** [comment]
In your screen component, define a static `navigatorStyle` object like this:

```js
class MyScreen extends Component {
  static navigatorStyle = {
    drawUnderNavBar:true
    navBarTranslucent: false
  };
}
```

For more examples, refer to the [docs](https://github.com/wix/react-native-navigation#style-object-format)
