### ISSUE TITLE
Missing styles for parity with v1

### ISSUE THREAD

**Issue by yogevbd** [wix/react-native-navigation#2902]
## iOS
- [x] disabledButtonColor -> disabledColor
- [x] backButtonImage
- [x] backButtonTitle
- [x] backButtonHidden
- [x] hideBackButtonTitle
- [x] topBarSubtitle
- [x] ~~selectedIcon (bottomTab)~~ #3031
- [x] ~~iconInsets (bottomTab)~~ #3031

## Android
- [x] ~~overrideBackPress~~ Use react-natives' BackHandler
- [x] navBarButtonFontFamily (Android only)
- [x] subtitle
- [x] disabledColor
- [x] statusBarHidden
- [x] statusBarTextColorScheme
- [x] statusBarColor
- [x] drawUnderStatusBar
- [x] navBarHeight
- [x] navBarTopPadding
- [x] topBarBorderColor
- [x] topBarBorderWidth
- [x] backButtonImage
- [x] topTabsHeight
- [x] forceTitlesDisplay

**Comment by windydang26** [comment]
disabledButtonColor not working

**Comment by yogevbd** [comment]
@windydang26 use `disabledColor`

**Comment by guyca** [comment]
@yogevbd `iconInsets` is pretty much a workaround to `TabBar` items not being centered when when tab items have no `title`. If we can center the icon in this case, then there's no need to bother with `iconInsets`

**Comment by yogevbd** [comment]
@guyca Added `overrideBackPress`

**Comment by guyca** [comment]
Instead of `overrideBackPress` users should use [BackHandler](https://facebook.github.io/react-native/docs/backhandler.html)

**Comment by guyca** [comment]
@seahorsepip This is indeed undocumented 😢 

```js
layout: {
  topMargin: Navigation.constants().statusBarHeight
}

**Comment by seahorsepip** [comment]
@guyca
The content that is to be supposed below the statusbar(everything besides topbar) is also pushed down with that code.

**Comment by guyca** [comment]
@seahorsepip Please open separate issues and I'll get to them asap. We're a bit overwhelmed with issues ATM as we just migrated the Wix app to v2, so it might take me a while to address these. Thanks for the understanding.

**Comment by seahorsepip** [comment]
@guyca 
I'll open another issue and try to make a fix myself.
