### ISSUE TITLE
hide the tab bar

### ISSUE THREAD

**Issue by AlanSaracho** [wix/react-native-navigation#2909]
Hi! i try to use the tab based app with a drawer, and hidden tabs, because i will navigate with the drawer in my app.
In the documentation, i see the tabBarHidden option, but doesn't work.

DOCUMENTATION:
`{
  tabBarHidden: false, // make the tab bar hidden
  tabBarButtonColor: '#ffff00', // change the color of the tab icons and text (also unselected)
  tabBarSelectedButtonColor: '#ff9900', // change the color of the selected tab icon and text (only selected)
  tabBarBackgroundColor: '#551A8B', // change the background color of the tab bar
  tabBarTranslucent: false, // change the translucent of the tab bar to false
  tabBarTextFontFamily: 'Avenir-Medium', //change the tab font family
  tabBarLabelColor: '#ffb700', // iOS only. change the color of tab text
  tabBarSelectedLabelColor: 'red', // iOS only. change the color of the selected tab text
  forceTitlesDisplay: true, // Android only. If true - Show all bottom tab labels. If false - only the selected tab's label is visible.
  tabBarHideShadow: true // iOS only. Remove default tab bar top shadow (hairline)
}
`

Code in v1.1.46

`    tabsStyle?: {
        tabBarButtonColor?: string;
        tabBarSelectedButtonColor?: string;
        tabBarBackgroundColor?: string;
        initialTabIndex?: number;
    };`

Regards!

### Environment
* React Native Navigation version: v1.1.46

**Comment by guyca** [comment]
Hey,
You can add `tabBarHidden: true` to appStyle which will apply this style properties on all screens.
https://wix.github.io/react-native-navigation/#/top-level-api?id=starttabbasedappparams

**Comment by FRizzonelli** [comment]
How can I set "tabBarHidden" only on some screens? Navigator.toggleNavBar hides the bottom bar, but the space is still occupied by the hidden tabbar.
If I use "tabBarHidden" in appStyle tab is correctly hidden by all screens, but I can't toggle it. 

I've tried with

` navigator.setStyle({
tabBarHidden: true
})`

in the screen I want to hide the bar, but it does nothing :(
