### ISSUE TITLE
TitleBar - Title now shown in iOS 

### ISSUE THREAD

**Issue by pascalporedda** [wix/react-native-navigation#2911]
### Issue Description

I started a new project and added react-native-navigation, followed along the installation instructions, added the basic code from the example in the documentation and it seems to be working fine, except for the fact that the title bar is not showing the current screen title, it is simply empty.

When downgrading to an older version of RNN (specifically version 1.1.409) it is working fine though!

### Steps to Reproduce / Code Snippets / Screenshots

1. Create new app via react-native init
2. Follow the installation instructions of the documentation for ios
3. Goto index.js and remove all content there except for the app import
4. Add the following code to the App.js file

```
import { Navigation } from 'react-native-navigation'
import HomeScreen from './src/screens/HomeScreen' // Contains a simple component with hello world text
Navigation.registerComponent('example.HomeScreen', () => HomeScreen);

Navigation.startSingleScreenApp({
  screen: {
    screen: 'example.HomeScreen', // unique ID registered with Navigation.registerScreen
    title: 'Welcome', // title of the screen as appears in the nav bar (optional)
    navigatorStyle: {}, // override the navigator style for the screen, see "Styling the navigator" below (optional)
    navigatorButtons: {} // override the nav buttons for the screen, see "Adding buttons to the navigator" below (optional)
  }
});
```

5. Run the app in iOS Simulator

-> No title in the titlebar is shown

---
### Environment
* React Native Navigation version: 1.1.422
* React Native version: 0.54.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/iPhone 6. iOS 11. Debug

**Comment by yogevbd** [comment]
Fixed in v1.1.424
