### ISSUE TITLE
Where can I find all the navigator methods?? When I press a drawer option I want a new page and not a pushed screen

### ISSUE THREAD

**Issue by juanlet** [wix/react-native-navigation#2912]
Hello. I have a side drawer and I need to press one of the options and create a new scene. How do I do that with the navigator object? I tried to console.log the object but I don't see the methods and couldn't find them in the docs. Thanks

**Comment by guyca** [comment]
You'll probably need to dispatch a deeplink and handle it in the relevant screen. You checkout the example app for examples.

**Comment by juanlet** [comment]
guyca...I did exactly that and the deep link works, but that was not my question. I jus wanna know where I can find the full doc of the navigator object. The docs only talk about this.props.navigator.push but dont mention other navigator methods like resetToRoot () or other methods. I just need to know where to find that full list since the docs are really incomplete.

**Comment by juanlet** [comment]
Found it...sorry!! https://github.com/wix/react-native-navigation/blob/master/docs/screen-api.md
