### ISSUE TITLE
use of undefined identifier RCTBridgeWillReloadNotification in RCCManager.m

### ISSUE THREAD

**Issue by bjacog** [wix/react-native-navigation#2913]
### Issue Description

Fails to build:

```
~/react_apps/core/node_modules/react-native-navigation/ios/RCCManager.m:39:100: Use of undeclared identifier 'RCTBridgeWillReloadNotification'
```

Can get around this by defining the string in RCCManager.m:

```
NSString *const RCTBridgeWillReloadNotification = @"RCTBridgeWillReloadNotification";
```

### Steps to Reproduce / Code Snippets / Screenshots

Build using current master, I do get the problem going back to 1409

---
### Environment
* React Native Navigation version: `1.1.409` and up
* React Native version: `0.47.1`
* Platform(s) (iOS, Android, or both?): `iOS`
* Device info (Simulator/Device? OS version? Debug/Release?): `Simulator and device 11.2`

**Comment by guyca** [comment]
@bjacog Sounds great!

**Comment by normal1ze** [comment]
Will this be merged into a release soon? I'm getting the same issue.

**Comment by witalobenicio** [comment]
I'm getting this error on React Native 0.48.3 too
