### ISSUE TITLE
Collapsible header bug after upgrading react native version

### ISSUE THREAD

**Issue by nitish24p** [wix/react-native-navigation#2920]
I recently updated my react native version to 0.51.0, The collapsible header component seems to have stopped working. This is my code below. I have a `<View>` Component and inside that i have a ScrollViewComponent and an Absolute positioned bottom button. Attached the Gif below 

This was working fine untill my react native version was <=0.50

```jsx
  render() {
    return (
      <View style={{ flex: 1, backgroundColor: '#fff' }}>
        <ScrollView style={{ marginBottom: 50, flex: 1 }}>
          {this.renderGroupDetailsContent()}
        </ScrollView>
        {this.renderButtons()}
      </View>
    );
  }
```

My navigation push code.
```javascript
{
      screen: screenRoute,
      title: title,
      navigatorStyle: {
        drawUnderTabBar: true,
        navBarButtonColor: Themes.userTheme.white,
        navBarTextColor: Themes.userTheme.white,
        navBarTranslucent: true,
        collapsingToolBarComponent: 'CollapsingHeader',
        collapsingToolBarCollapsedColor: Themes.userTheme.primaryColor
      }
    };
```
![screen](https://user-images.githubusercontent.com/13037986/37910320-dcad5346-312a-11e8-9790-514d19da0de2.gif)

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.422
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 5 emulator

**Comment by prgpascal** [comment]
Probable duplicate of [#2477](https://github.com/wix/react-native-navigation/issues/2477).

**Comment by nitish24p** [comment]
Closing
