### ISSUE TITLE
Root component lifecycle issues when NOT debugging remotely

### ISSUE THREAD

**Issue by habovh** [wix/react-native-navigation#2928]
### Issue Description

This issue may be quite similar to #2286, root components mounted using `startTabBasedApp` or `startSingleScreenApp` are having a lifecycle issue, when not using RN's "Debug JS Remotely" feature.

Root components seem to be mounted, unmounted, then mounted again. This leads to timing-related issue, and while the root component eventually stays mounted at last, it happens that `componentWillUnmount` can be fired after the second `componentWillMount`.
Notice that sometimes, the `componentWillUnmount` is not even triggered.

### Investigation

From what I experienced, this behavior does not seem to happen in simulator, but happens **only when remote-debugging is turned off**. This means the issue happen also when installing app from a production-ready archive.

During my investigation, I've modified my current app to eliminate as much variables as I could, and here's the general app lifecycle:

- `index.ios.js` instantiates `App` which consist of a class (not a component, a real class) responsible of calling its `startApp()` function only if and when the store gets rehydrated by redux.
- `startApp()` in turns calls `Navigation.startSingleScreenApp`, only providing `screen` and `title` params.

> The screen displayed is `TestScreen`, which is registered before instantiating `App`.

During each lifecycle function of my `TestScreen` root component, and in some other places like inside `App` class, I'm pushing strings inside `window.logtrace`, which then gets rendered on the screen.

### Results

Here are the results. Notice that in each case, `startApp()` gets called only **once**, after the second `onStoreUpdate`, which is correct behavior (in first `onStoreUpdate`, the state is not rehydrated yet).

With `startApp()` being called only once, I can safely state that `startSingleScreenApp` is effectively called only once.

#### On device

| With remote debugging | Without remote debugging |
| -------- | --------- |
|![img_7364](https://user-images.githubusercontent.com/4186230/37979800-cacd6b6a-31e9-11e8-80a2-4af00abb24ce.png) | ![device-local js](https://user-images.githubusercontent.com/4186230/37979844-ecfbdd02-31e9-11e8-824e-d77bf3dac09d.png) |

#### On simulator

| With remote debugging | Without remote debugging |
| ----------------------- | --------------------------- |
| ![screenshot1](https://user-images.githubusercontent.com/4186230/37979909-16d2b538-31ea-11e8-8391-651fd62946e9.png) | ![screenshot2](https://user-images.githubusercontent.com/4186230/37979954-31b2f214-31ea-11e8-8134-2017bfaf437c.png) |

### Now what?

Now I've got to the point where I cannot debug any further without digging into the lib, and I'd like to see if this behavior reproduces for others.

---
### Environment
* React Native Navigation version: `1.1.411`
* React Native version: `0.53.3`
* Platform(s) (iOS, Android, or both?): **iOS**
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator + Device iPhone 7, iOS 11.2.6, Debug + Release

**Comment by manjeetwadi** [comment]
similar thing happening to our app. Any success resolving this or #1212

**Comment by alvaromb** [comment]
@brunolemos I don't think `componentWillUnmount` is being deprecated: https://reactjs.org/docs/react-component.html#componentwillunmount

**Comment by brunolemos** [comment]
@alvaromb yes you are right, I just meant that was one of the reasons Dan Abramov mentioned about deprecating the other `willX` methods, I don't know if it's normal to have `componentWillUnmount` called more than once but the other `willX` yes
