### ISSUE TITLE
[iOS] Tabs have a cutoff when in-call status bar is present in screen with tabs hidden

### ISSUE THREAD

**Issue by tyricec** [wix/react-native-navigation#2930]
### Issue Description

Hi. I found an issue in iOS. When the tab bar is hidden and the in-call status bar appears, this causes the tabs titles to have a cutoff. The tabs have a cutoff because the bar is positioned downwards from the status bar. However, this doesn't occur if the user only navigates to screens with the tabs present. The only way the tabs are fixed is when the call indicator is removed, and the user navigates to another screen with the tabs hidden.

#### Steps

1. In simulator, toggle in-call status bar (Cmd+Y)
2. Navigate to screen that uses toggleTabs with **to** set to **hidden**
3. Navigate to screen that uses toggleTabs with **to** set to **shown**

#### Expected

<img width="375" alt="screen shot 2018-03-27 at 12 00 41 pm" src="https://user-images.githubusercontent.com/3968741/37988746-89678148-31b6-11e8-8ffd-da638bce2990.png">

#### Actual

<img width="389" alt="screen shot 2018-03-27 at 12 00 52 pm" src="https://user-images.githubusercontent.com/3968741/37988762-8fc5c3ba-31b6-11e8-8e04-059698d6dcd3.png">

---
### Environment
* React Native Navigation version: 1.1.332
* React Native version: 0.49.5
* Platform(s): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/iPhone 6 iOS 11.2 Debug/Release

**Comment by 1453009** [comment]
+1
same issue but on Android 5., 6. and 7.
I have never seen on iphone

**Comment by AmeerTgh** [comment]
+1

**Comment by taschik** [comment]
did anyone find a proper fix for this?

**Comment by sb8244** [comment]
I'm doing something like this @taschik: 

```
import React, { Component } from 'react'
import { Animated, Easing, NativeModules } from 'react-native'
// @ts-ignore: No typings
import StatusBarSizeIOS from 'react-native-status-bar-size'
import Reactotron from '../../ReactotronConfig'

const { StatusBarManager } = NativeModules

interface IState {
  marginBottom: Animated.Value
}

export default function StatusBarAwareView(WrappedComponent: any) {
  return class extends Component<any, IState> {
    public state = {
      marginBottom: new Animated.Value(0),
    }

    public componentDidMount() {
      this.handleStatusBarSizeDidChange()
      StatusBarSizeIOS.addEventListener('willChange', this.handleStatusBarSizeDidChange)
    }

    public componentWillUnmount() {
      StatusBarSizeIOS.removeEventListener('willChange', this.handleStatusBarSizeDidChange)
    }

    public render() {
      return (
        <Animated.View
          style={{display: 'flex', flex: 1, marginBottom: this.state.marginBottom}}
        >
          <WrappedComponent {...this.props} />
        </Animated.View>
      )
    }

    private handleStatusBarSizeDidChange = () => {
      this.getHeight().then((currentStatusBarHeight: number) => {
        Reactotron.log('handleStatusBarSizeDidChange', 'currentHeight=', currentStatusBarHeight, 'toValue=', currentStatusBarHeight - 20)
        // This animation is wonky but I cannot figure out how to get it to work properly
        Animated.timing(this.state.marginBottom, {
          toValue: currentStatusBarHeight - 20,
          duration: 250,
          easing: Easing.inOut(Easing.linear),
        }).start()
      })
    }

    private getHeight = () => new Promise<number>((resolve) => {
      StatusBarManager.getHeight((statusBarFrameData: { height: number }) => {
        resolve(statusBarFrameData.height)
      })
    })
  }
}
``` 

```
StatusBarAwareView(MainTabNavigation)
```

I already do some stuff to make sure that the router is properly setup, as this will most likely give you the incorrect reference for your navigation.
