### ISSUE TITLE
Subtitle

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#2937]
### API
```js
{
  topBar: {
    title: {
      text: 'Static Title',
      color: 'black',
      fontSize: 16,
      fontFamily: 'HelveticaNeue-Italic',
      largeTitle: false
    }
  }
}
```

### Android
- [x] text
- [x] color
- [x] font family
- [x] font size
- [x] alignment

### iOS
- [x] text
- [x] color
- [x] font family
- [x] font size

**Comment by quy1403** [comment]
@guyca in V2, how can I set backButtonTitle, please help, thanks u!

**Comment by guyca** [comment]
@quy1403 Please refer to the [docs](https://wix.github.io/react-native-navigation/v2/#/docs/styling)
