### ISSUE TITLE
How to show introduction page  before Navigation.startTabBasedApp launch ?

### ISSUE THREAD

**Issue by leotu** [wix/react-native-navigation#294]
Hi, I want to integrate "https://github.com/FuYaoDe/react-native-app-intro",
But don't know how to run introduction page before Navigation.startTabBasedApp.

-----------------
What version of `react-native` you are using: 0.29.0
What version of `react-native-navigation` you are using:  1.0.30

**Comment by guyca** [comment]
call `startSingleScreenApp` then at the end of the intro, start your app as usual with `startTabBasedApp`

**Comment by leotu** [comment]
It works, thanks!
