### ISSUE TITLE
Navigation bar cannot be transparent.（导航栏不能透明）

### ISSUE THREAD

**Issue by CoddingTan** [wix/react-native-navigation#2941]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by CoddingTan** [comment]
The navigation bar can be colored but not transparent.

**Comment by dbyilmaz** [comment]
@CoddingTan  You must add your navigatorStyle code.

**Comment by CoddingTan** [comment]
@dbyilmaz  My code:

`{
        tabBarComponent:TabBarBottom,
        
        indicatorStyle:{
          backgroundColor:'rgba(0,0,0,0)'
        },
        tabBarPosition:'bottom',
        swipeEnabled:false,  //是否支持滑动切换tab
        animationEnabled:false,//是否触发滑动切换样式
        lazy:true,  
        initialRouteName: 'Two',//默认显示
        tabBarOptions:{  
          
          activeTintColor:'#06c1ae',  
          inactiveTintColor:'#979797',  
          style:{backgroundColor:'rgba(0,0,0,0.3)'},
          labelStyle: {  
                fontSize: 15, // 文字大小 
            },
        }  
          
      }`
The style is opaque and the color can be changed, but it can't be transparent, like a white control below.
