### ISSUE TITLE
How to rewrite swipe left gesture to go back event in ios 

### ISSUE THREAD

**Issue by mingshangege** [wix/react-native-navigation#2945]
On IOS, there is a swipe left gesture to go back function, how to call my method when triggering this function

### Environment
* React Native Navigation version: 1.1.310
* React Native version: 0.44.3
* Platform(s) (iOS, Android, or both?): ios

**Comment by namnh240795** [comment]
Why closing this, this is still happen. How to listen to gesture back event?
