### ISSUE TITLE
[tid:com.facebook.React.JavaScript][RCTConvert.m:53] JSON value '7' of type NSNumber cannot be converted to NSArray

### ISSUE THREAD

**Issue by zhump** [wix/react-native-navigation#295]
![image](https://cloud.githubusercontent.com/assets/7962067/18352449/09905484-7611-11e6-964f-7ce6635e23c3.png)

**Comment by guyca** [comment]
This seems like an error that's usually thrown when RN version you're expected to use doesn't match the one that actually gets bundled.
Try closing the server, then run `watchman watch-del-all` before restarting the server
