### ISSUE TITLE
Please completely update the v2 docs

### ISSUE THREAD

**Issue by Dexwell** [wix/react-native-navigation#2950]
I understand that it would be a very time consuming job, but at some point it will have to be done anyway. 

Not all APIs are shown off in the Playground. Keeping the docs updated as soon as API changes are made will give us all a lot of time back spent experimenting and debugging; it would lead to far less confusion/questions and more quality Issues/bug reports :)

Please allow me to slip in a question to provide an example. I've spent hours trying to figure out how to set a screen's status bar style (light or dark) without using the StatusBar component. There's no example in the Playground; Issues on here suggest placing the following two pieces of code in the component, but neither work. (using RNN 2.0.2204)

```js
static navigatorStyle = {
  statusBarTextColorScheme: 'light'
}
```

```js
static get options() {
  return {
    statusBarTextColorScheme: 'light'
  };
}
```

**Comment by Dexwell** [comment]
cc @guyca

**Comment by yogevbd** [comment]
Updated the docs but there's still work to be done..
For your question:

```js
static get options() {
  return {
    statusBarStyle: 'light'
  };
}
```

**Comment by Dexwell** [comment]
Thanks so much!
