### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by keyeMyria** [wix/react-native-navigation#2951]
### blank screen on ios while android is ok

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

1.create-react-native-app
2.yarn eject
3. add RNN as document
4. run

Android is ok.

---
### Environment
* React Native Navigation version: 1.1.428
* React Native version: 0.54.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator yet

**Comment by guyca** [comment]
You've probably missed a step in the [installation guide](https://wix.github.io/react-native-navigation/#/installation-ios)
