### ISSUE TITLE
Crash on showModal when presenting it more than one time

### ISSUE THREAD

**Issue by swapnil001** [wix/react-native-navigation#2952]
### Issue Description

Showing a component modally more than one time causes a crash on Android

### Steps to Reproduce / Code Snippets / Screenshots

1. Show a component as modal
2. Dismiss it
3. Show the same modal again
4. The app crashes

---
### Environment
* React Native Navigation version:  1.1.428
* React Native version: 0.54.1
* Platform(s) (iOS, Android, or both?): Android

**Comment by swapnil001** [comment]
Update - Only those modal inside which I am making API Calls to get data are forcing the crash on Android. Those with no API Calls and static data display are working fine.

**Comment by guyca** [comment]
Sounds like it's a Js error on your side, I'm not able to reproduce.
