### ISSUE TITLE
Android Cold Startup issues

### ISSUE THREAD

**Issue by miguelespinoza** [wix/react-native-navigation#2958]
### Issue Description
Long cold startups are a notorious issue on Android.  I've recently started digging into why that's the case for our app and I have little insights but I have some reason to believe React Native Navigation places a certain role.

I'm currently in the phase of measuring to see why we have startup times of ~7 seconds.
I've started with the Android methodTracing tool to get an idea where the time is getting spent.
Here's a glimpse, from `onReactInitialized` to start of `JS Code`.
Notice how big of a gap certain calls have in the `mqt_js` thread.

## App 1 (with react-native-navigation)
<img width="1611" alt="screen shot 2018-03-30 at 4 18 00 pm" src="https://user-images.githubusercontent.com/6182543/38198526-30e382d4-365b-11e8-9d3e-a9a79ab6abd3.png">

I measured a pure RN app without RNN and noticed that the threads run nicely with very little hiccup.

## App 2 (without react-native-navigation)
<img width="1620" alt="screen shot 2018-03-30 at 4 18 21 pm" src="https://user-images.githubusercontent.com/6182543/38198564-5bda87ee-365b-11e8-9745-ec4331a8ffb6.png">

Some facts about App 1 and App 2.

App 1
* 20 native modules

App 2
* 12 native modules

Also, I did an experiment of "migrating" from RNN to pure RN app (same configuration as react-native init).
This experiment trimmed 2 seconds off of cold start time.  This gave me reason to believe that there's an issue with the React Initialization with RNN.

Any thoughts as to how I can address this issue.  Maybe areas in my app, RNN library, or React I should look at.  Any solutions that are available to us that could help with this?
It seems like the overhead comes from after the ReactContext has been initialized. I'm not sure yet what follows after this process.  I'll be investigating this next.

Note: I've installed the Wix app and the startup time floats around 6 seconds.  So I know this is an issue that many users will have eventually.  We all inherit this issue.

---
### Environment
* React Native Navigation version: 1.1.412
* React Native version: 0.52.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Android7.0 Debug and Release

**Comment by miguelespinoza** [comment]
I did some more profiling after some changes, notably disabling multiDex.  This cleaned up the threads significantly. Yet I'm seeing these gaps. This happens after reactContextInitialized. Any idea what could cause these gaps?

<img width="1629" alt="screen shot 2018-04-05 at 2 28 38 pm" src="https://user-images.githubusercontent.com/6182543/38384625-aa3b4098-38dd-11e8-92fd-b76079688cb0.png">

**Comment by dblachut-adb** [comment]
@miguelespinoza did you came up with anything that would be worth sharing here?

**Comment by RZulfikri** [comment]
any update on this??

**Comment by AlexHooperDev** [comment]
bump

**Comment by nichthinkof30** [comment]
Bump any updates on this issue ? Anyone found any solution?

**Comment by svbutko** [comment]
This issue was with next versions of RN and RNN

React Native Navigation version: 1.1.412
React Native version: 0.52.0

It it the same thing with

React Native Navigation version: 7.21.0
React Native version: 0.65.1

?
