### ISSUE TITLE
RCCManager.h not found in example xcode project

### ISSUE THREAD

**Issue by gowtam04** [wix/react-native-navigation#296]
<img width="1136" alt="screen shot 2016-09-08 at 8 28 53 pm" src="https://cloud.githubusercontent.com/assets/3285565/18354377/fbbe65e8-7602-11e6-8ba6-30431ea96474.png">

**Comment by bbrock25** [comment]
have you followed the installation instructions [here](https://github.com/wix/react-native-navigation/wiki/Installation---iOS#installation---ios)?

**Comment by zeffon** [comment]
@bbrock25 is right.
Try to add "./node_modules/react-native-controllers/ios/ReactNativeControllers.xcodeproj" to your iOS project maybe resolve your problem.

**Comment by xiongjiabin** [comment]
rm node_modules, and rebuild it by "npm install" fixed the problem for me

**Comment by cacheflow** [comment]
What worked for me was changing the path that it says to add to your header search paths in XCode. 

`$(SRCROOT)/../node_modules/react-native-controllers/ios`

It was going up to a parent dir where the node_modules folder did not exist. I just changed it to `./node_modules` and it worked fine.

**Comment by lakhman** [comment]
I got this error as I had not modified my AppDelegate correctly.:

```
  #import "RCCManager.h"

  // I forgot this - RCCManager.h not found
  self.window.backgroundColor = [UIColor whiteColor];
  [[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation];
```

**Comment by juliansharifi** [comment]
Make sure when you add the header path you add it to debug as well.

**Comment by jpoutrin** [comment]
The wix team changed the project structure. documentation is not up-to-date...

1. the app delegate has changed. 
RCCManager.h is no longer there apparently.
#import <ReactNativeNavigation/ReactNativeNavigation.h>
2. the ios project has moved to $(SRCROOT)/../node_modules/react-native-navigation/lib/ios

**Comment by dozel** [comment]
@jpoutrin did you have to do anything else in addition to replacing RCCManager import and changing the header search path? My project still sees RCCManager as undeclared.

**Comment by madhu314** [comment]
Change the import as per @jpoutrin and replace 
```[[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions];```
with
```[ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];```

**Comment by Ignigena** [comment]
Hit the same issue and was solved thanks to the suggestions of @jpoutrin and @madhu314. In my case, however, since I was upgrading from an earlier build of this module I had to re-link the native module in order for the new header to get picked up (otherwise Xcode was complaining that `ReactNativeNavigation.h` was not found)

* `react-native unlink react-native-navigation`
* `react-native link react-native-navigation`

**Comment by Pyrolistical** [comment]
lol, my problem was i installed `react-native-navigator`

**Comment by lefoy** [comment]
For future reference (found this issue via Google):

I solved this issue by using `#import "../../node_modules/react-native-navigation/ios/RCCManager.h"` instead of `#import "RCCManager.h"` in `AppDelegate.m`

**Comment by balwinder4264** [comment]
Make Header Search Path non-recursive

**Comment by shreyashpatodia** [comment]
I ran into the same issue and [this](https://gist.github.com/shreyashpatodia/e7b18454f8b5f202c80444607e7cb42e) is the AppDelegate file I ended up using to get everything resolved.

I hope that helps!
