### ISSUE TITLE
V2 showOverlay does not redraw on iOS rotation

### ISSUE THREAD

**Issue by alexwasner** [wix/react-native-navigation#2962]
### Issue Description
While testing on the V2, `Navigation.showOverlay` does not change bounds when orientation changes. Haven't tested on Android.

### Steps to Reproduce / Code Snippets / Screenshots
1. Toggle multiple orientations in XCode.
2. Register view positioned absolutely `{top:0,bottom:0,left:0,width:'50%'}` and display it
```
    Navigation.showOverlay({
      component: {
        name: 'TestView',
        options: {
          overlay: {
            interceptTouchOutside: false
          }
        }
      }
    });
```
3. Rotate iOS device
4. Examine bounds have not changed.

---
### Environment
* React Native Navigation version: `^2.0.2202`
* React Native version: `^0.51.0`
* Platform(s) (iOS, Android, or both?): iOS (haven't tested android)
* Device info (Simulator/Device? OS version? Debug/Release?): Both iOS 11.2/11.3

**Comment by yogevbd** [comment]
@guyca This doesn't reproduce on android.. can we close?
