### ISSUE TITLE
[Android] dismissModal() crashes when no modal is on-screen

### ISSUE THREAD

**Issue by MyGuySi** [wix/react-native-navigation#2966]
# UPDATE: I've changed the issue title as it wasn't related to the real issue. See additional comments below...

### Issue Description

I've had this issue lurking around for a while but I haven't been able to recreate it consistently until now. When the app is open, if it is closed from the app switcher the next time you launch it will cause it to crash on launch and this keeps happening until you remove the app and reinstall.

Here's the output I captured from logcat when the crash occured:

```
04-04 10:26:11.037 14497 14497 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-04 10:26:11.052  1489  1489 W Binder_A: type=1400 audit(0.0:467): avc: denied { ioctl } for path="socket:[90981]" dev="sockfs" ino=90981 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
04-04 10:26:11.052  1489  1489 W Binder_A: type=1400 audit(0.0:468): avc: denied { ioctl } for path="socket:[90981]" dev="sockfs" ino=90981 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
04-04 10:26:11.060 14497 14537 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
04-04 10:26:11.060 14497 14537 E AndroidRuntime: Process: com.sorbet.contractor.rc, PID: 14497
04-04 10:26:11.060 14497 14537 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.reactnativenavigation.params.StyleParams.screenAnimationType' on a null object reference
04-04 10:26:11.060 14497 14537 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.ScreenParamsParser.parse(ScreenParamsParser.java:62)
04-04 10:26:11.060 14497 14537 E AndroidRuntime: 	at com.reactnativenavigation.bridge.NavigationReactModule.dismissTopModal(NavigationReactModule.java:223)
04-04 10:26:11.060 14497 14537 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-04 10:26:11.060 14497 14537 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
04-04 10:26:11.060 14497 14537 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
04-04 10:26:11.060 14497 14537 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
04-04 10:26:11.060 14497 14537 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
04-04 10:26:11.060 14497 14537 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-04 10:26:11.060 14497 14537 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
04-04 10:26:11.060 14497 14537 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-04 10:26:11.060 14497 14537 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
04-04 10:26:11.060 14497 14537 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
```

### Steps to Reproduce / Code Snippets / Screenshots

1. Launch app
2. Open App Switcher
3. Dismiss app (force close)
4. Relaunch app
5. Crash before launch

---
### Environment
* React Native Navigation version: v1.1.410
* React Native version: v0.50.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Various devices running different versions of Android. Release build. I can provide more details if needed..

**Comment by MyGuySi** [comment]
I thought it might be related to [this issue](https://github.com/wix/react-native-navigation/issues/2479) but that didn't fix it :(

**Comment by MyGuySi** [comment]
The error that was logged points to this line in the `ScreenParamsParser`: https://github.com/wix/react-native-navigation/blob/e0a6ff2dad25c26eaa8ae1eacd3d2f185c5aebd5/android/app/src/main/java/com/reactnativenavigation/params/parsers/ScreenParamsParser.java#L62

**Comment by MyGuySi** [comment]
I'm starting to this this isn't an issue with `react-native-navigation` because it only happens on Release builds and after I've logged into my app. It doesn't happen before I login. I haven't pinpointed the issue just yet though so I'll update if I find out more.

**Comment by MyGuySi** [comment]
Starting to narrow this down a bit, I've got this code that fires on startup and when auth state changes:

```javascript
  handleLoginStateChange(isUserLoggedIn: boolean) {
    if (this.isInitializing) {
      return;
    }
    if (isUserLoggedIn !== this.isUserLoggedIn) {
      if (isUserLoggedIn) {
        Navigation.dismissModal({ <--- Removing this stop the crash
          animationType: "slide-down"
        });
        this.handleUserLoggedIn();
      } else {
        Navigation.showModal({
          screen: "MyApp.Login",
          navigatorStyle: { navBarHidden: true }
        });
      }
    }
    this.isUserLoggedIn = isUserLoggedIn;
  }
```

If I remove the call to `Navigation.dismissModal({...})` that stops the crash.

What's happening is that I'm already logged in, so it's trying to dismiss a modal that was never presented. This has never caused any issues on iOS and I'd expect it to just fail gracefully rather than crash the entire app.

I can add some logic to determine whether the screen has been presented previously or not but I don't like the way that it's being handled by `react-native-navigation` at the moment.

**Comment by MyGuySi** [comment]
This is probably where the change needs to be made:

https://github.com/wix/react-native-navigation/blob/d050ce2fda8d6f1c4f8a1f2242511e4319cf619c/android/app/src/main/java/com/reactnativenavigation/controllers/ModalController.java#L45:L49

You can see `dismissAllModals()` iterates a stack which is how it handles an empty stack. `dismissModal()` doesn't have any check. I'm not familiar with Java or native Android so I wouldn't like to butcher a solution. It would be great if someone else could submit a PR 👍

**Comment by MyGuySi** [comment]
@guyca I'm not entirely sure that the change you made is fixing the right problem. Shouldn't `dismissModal()` check if there is an active modal before attempting to dismiss it?

**Comment by guyca** [comment]
No worries 👍
