### ISSUE TITLE
[iOS] [v1] Disabled Drawer cancels move gesture event on screen

### ISSUE THREAD

**Issue by DanielBoening** [wix/react-native-navigation#2968]
### Issue Description
I have an Side Drawer in the App. On one screen I want to draw on a sketch view. During drawing the gesture is cancelled after a very short moment. So only short lines can be drawn. On Android it fixes this issue by disabling the drawer on the page. On iOS it only helps if I completely remove the drawer from the app.

---
**Steps to Reproduce / Code Snippets / Screenshots**
Used for Drawing:  "(at)terrylinla/react-native-sketch-canvas": "^0.3.1"
On the specific page in the constructor:
this.props.navigator.setDrawerEnabled({
			side: 'left',
			enabled: false,
		});

---
### Environment
* React Native Navigation version: 1.1.410
* React Native version: 0.54.2
* Platform(s) (iOS, Android, or both?): only iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator 11.0.1

**Comment by Vietvantue** [comment]
I still got this problem when using with terrylinla/react-native-sketch-canvas
