### ISSUE TITLE
toggleDrawer not working on Android

### ISSUE THREAD

**Issue by tapdancemobile** [wix/react-native-navigation#297]
I am using RN31 and react-native-navigation - 2.0.0-experimental.105
I can't get this.props.navigator.toggleDrawer to work from the drawer button or a custom button in my view. Works in iOS but not Android.

I am getting an opaque overlay on the whole screen upon the toggleDrawer action and 'Got DOWN touch before receiving UP or CANCEL from last gesture' when I touch the screen sunsequently

**Comment by guyca** [comment]
@tapdancemobile You don't need to call `toggleDrawer` when hamburger button is clicked, that's handled for you.

**Comment by tapdancemobile** [comment]
oh ok, gotcha - thanks! I still get the described error when calling toggleDrawer manually within a custom view...

**Comment by guyca** [comment]
@tapdancemobile `toggleDrawer` works fine on my test device. On what device are you testing? what Android version?

**Comment by tapdancemobile** [comment]
This was my error - the view wasn't rendering due to an error with the props. Thanks! Works for me now...

**Comment by JuneDomingo** [comment]
@guyca It's not really working this time. I'm using 2.0.0-experimental.127
Work perfectly fine on IOS.

RN 0.32

**Comment by guyca** [comment]
@JuneDomingo It works fine in the example project. Maybe something with your setup.

**Comment by JuneDomingo** [comment]
Yes, It will work when you press the hamburger button, but when you toggle it programmatically using ``this.props.navigator.toggleDrawer`` it doesn't.

**Comment by JuneDomingo** [comment]
I removed the ``to: open`` and it worked (for left drawer and this solved my problem).  Thanks
One thing I noticed is that when I change ``side:`` to ``right`` the right drawer is not showing up.

**Comment by guyca** [comment]
Yes. Right drawer isn't implemented on Android yet. I didn't think it people use it that much on Android so we delayed implementing it. I can push for it to be implemented soon if you need it.

**Comment by JuneDomingo** [comment]
I see. I don't need it for now (well at least for me).

**Comment by brianjd** [comment]
@guyca I actually require the right drawer (Android).  Are you able to queue it up?

**Comment by megahertz** [comment]
+1 for right drawer on Android

**Comment by guyca** [comment]
@megahertz Right drawer was added to android in experimental.153

**Comment by megahertz** [comment]
@guyca Thank you, I've seen #547. But it doesn't work for me (with experimental.154). I've already try to recompile in Android Studio and checked that RNN subproject has the latest files. When I change a drawer side to left it works fine.

**Comment by megahertz** [comment]
Here is an example where the right drawer doesn't work: https://github.com/megahertz/react-native-test/blob/master/index.android.js
Tried with RN 0.37.0, 0.38.1, 0.39.2

**Comment by guyca** [comment]
@megahertz 
Seems to work in my [test branch](https://github.com/wix/react-native-navigation/tree/rightSideMenuInExample)

**Comment by megahertz** [comment]
@guyca Thank you for the example, it helps me to find a problem :)

**Comment by guyca** [comment]
@megahertz Thanks for the PR 😁

**Comment by chhourbro** [comment]
Hi guys,

Has this been fixed yet? I'm still having trouble with toggleDrawer on Android.
