### ISSUE TITLE
enable/disable animations

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#2970]
* Remove `animated` property from options
* Support enabling/disabled each animation separately in `animations` option:
  ```js
  options: {
    animations: {
      push: {
        enable: false
      }
  }
  ```

**Comment by terreb** [comment]
Is this implemented? I get `This animation is not supported` on Android when using something like:

```
        animations: {
            push: { disabled: true },
            pop: { disabled: true },
            showModal: { disabled: true },
            dismissModal: { disabled: true }
        }
```

...in Navigation.setDefaultOptions
