### ISSUE TITLE
What is the right way for load data before start single view app

### ISSUE THREAD

**Issue by JuoCode** [wix/react-native-navigation#298]
react-native: 0.32.0
react-native-navigation: 1.0.30

I want load data from `AsyncStorage` to determine which screen should pass to `startSingleViewApp`, but   load data operations are asynchronous.

I have tried in the following way with `react-native@0.31.0`, it's work well:
```
export default (async () => {
  const user = await AsyncStorage.getItem()

  let initialScreen
  if (user) {
    initialScreen = { screen: { screen: 'Dashboard' } }
  } else {
    initialScreen = { screen: { screen: 'SignIn' } }
  }

  Navigation.startSingleViewApp(initialScreen)
})()
```

When i upgrade `react-native` to `0.32.0`, first time is ok, but when i refresh the simulator it will go wrong  as follows:
```
React-Native: Module AppRegistry is not a registered callable module
```
Is this approach not recommend?
I think this demand should be common, and what is best practices should be like?

Thanks to the open source and community

**Comment by agumack** [comment]
I don't know why but you can try this:

- Step1: Navigation.startSingleViewApp('checkLoginScreeen') ;
- Step 2: on checkLogin Screen display a loader view and you can check AsyncStorage.getItem("user") 
- Step 3: Navigation.startSingleViewApp SignIn or Dashboard

**Comment by guyca** [comment]
Hey @JuoCode 
The approach you took is definitely solid. We don't officially support RN 0.32, the issue doesn't reproduce in RN 0.31?

**Comment by JuoCode** [comment]
@agumack I think your solution will break down the hot-reload mechanism.

@guyca Rarely happend in RN 0.31 and every time in RN 0.32, the source code is definitely same.

Thanks for replying. 😄

**Comment by littlesome** [comment]
It's a bug of RN, you need to require AppRegistry at the very beginning even if you do not use it there.

**Comment by littlesome** [comment]
Maybe you need to require RCTLog as well if you got some error about 'RCTLog'

**Comment by JuoCode** [comment]
@littlesome No effect 😢

**Comment by Andarius** [comment]
Following this issue, what is the recommended way to access AsyncStorage at startup ? 
I tried @JuoCode solution, but so far no luck I keep getting a blank white screen.
