### ISSUE TITLE
[Android] - Custom Navbar disappears

### ISSUE THREAD

**Issue by PeteOyable** [wix/react-native-navigation#2980]
### Issue Description
I use a customview for my navbar on an application, and on Android only, sometimes the navbar is not correctly displayed. The elements are missing.
On iOS everything works properly.

### Steps to Reproduce / Code Snippets / Screenshots
**This is a correct navbar**
<img width="482" alt="capture d ecran 2018-04-05 a 11 40 06" src="https://user-images.githubusercontent.com/3481956/38359296-36a5b6be-38c8-11e8-8714-0bb190da5825.png">

**And this is the navbar with the elements missing**
<img width="482" alt="capture d ecran 2018-04-05 a 11 39 46" src="https://user-images.githubusercontent.com/3481956/38359252-1948967c-38c8-11e8-9208-7560a273744f.png">

I use the static method to display the custom navbar : 
```javascript
static navigatorStyle = {
    navBarCustomView: SCREENS.NAVBAR.id
  };
```

I really don't understand why this does not work, does anyone has the same issue or know how to fix it ?
---
### Environment
* React Native Navigation version: 1.1.378
* React Native version: 0.53.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Any Android devices on both Debug and Release

**Comment by karlmosenbacher** [comment]
Do you have the same behavior on a real device?

**Comment by PeteOyable** [comment]
Hi @karlmosenbacher,
Yes I do have the same behavior on a real device.

**Comment by karlmosenbacher** [comment]
This is strange because I also have a tabbased app with a custom navbar and it works on both android and Ios.

**Comment by pawel-n** [comment]
have the same as @bilmiyore. Tabbased app, 3 tabs, on last tab, in 'release' mode, navBarCustomView disappears. In debug mode (react-native run-android) it's going to be visible after refreshing JS. I've tested on real device only.
On iOS there's no problem like this :(.

**Comment by ilovett** [comment]
Samesies.

react 16.2.0
react-native 0.53.0
react-native-navigation 1.1.471

Using `navBarCustomView` and only on my android release builds... I have using a tab based app.

Also on a real device

**Comment by ilovett** [comment]
Upgrading to react 16.3 and react-native 0.55.4 did not resolve the issue...

**Comment by rubeus90** [comment]
I have the same issue @PeteOyable 

I'm on:
"react": "16.3.1",
"react-native": "0.54.2",
"react-native-navigation": "1.1.412"

There's no problem on iOS but on the last tab of the tabbar, the custom view disappears

Is there any fix on this yet ?

**Comment by ivan133** [comment]
https://github.com/wix/react-native-navigation/issues/2807
