### ISSUE TITLE
[Android] dynamically changing drawUnderNavBar does not work

### ISSUE THREAD

**Issue by AndrePech** [wix/react-native-navigation#2985]
### Issue Description

I am trying to change the drawUnderNavBar att. in my screen constructor. iOS works fine, but Android seems to ignore the change.

### Steps to Reproduce / Code Snippets / Screenshots

Calling the code below in a pushed screen 's constructor having the app started with drawUnderNavNar set to true.

`this.props.navigator.setStyle({
            drawUnderNavBar: false
        });`

I could find a workaround if I knew the navBarHeight, by setting drawUnderNavBar to always true and setting a paddingTop:navBarHeight  on my screens which I dont want to draw under.

I have tried with some values found online, but did not work across Android <> iPhones <> iPhone X.

Thanks in advance.

---
### Environment
* React Native Navigation version: 1.1.426
* React Native version: 0.54.3
* Platform(s) (iOS, Android, or both?): ANDROID ONLY
* Device info (Simulator/Device? OS version? Debug/Release?): GALAXY S8 ANDROID 8.0

**Comment by AndrePech** [comment]
For anyone with the same issue, I have got a temporary workaround.
```

getNavBarHeight() {

        if (Platform.OS == 'ios') {

            let d = Dimensions.get('window');
            const { height, width } = d;
            
            if(height === 812 || width === 812)
                return 88 // iPhone X navbar height (regular title);
            else
                return 64 // iPhone navbar height;
        } else
            return 54 //android portrait navbar height;
    }
```

**Comment by guyca** [comment]
Did you try setting `drawUnderNavBar: false` in static style?
```js
static navigatorStyle = {
    drawUnderNavBar: false
  };
```

regardless, I'm closing as this issue won't be addressed in v1 since we're transitioning to v2
