### ISSUE TITLE
Pushing screen not working [v2]

### ISSUE THREAD

**Issue by EliSadaka** [wix/react-native-navigation#2986]
### Issue Description

Pushing a screen doesn't seem to work for me. I'm able to show a screen as a modal but when I try to push one to the stack I get an error. It's a tab-based app if that makes any difference. Here is my code:

```
Navigation.push(this.props.componentId, {
   component: {
	name: "example.ChatroomScreen",
   }
})
```

But when the code runs I get this error:

`Error: Could not push component: Component10. Stack with id null was not found.`

---
### Environment
* React Native Navigation version: 2.0.2229
* React Native version: 0.53.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device / Android 8.1.0 / Debug

**Comment by guyca** [comment]
Pushing a screen to a stack in a BottomTabs screen seems to work in the playground app.
If you PR a failing e2e test I could look into this further.

**Comment by pribeh** [comment]
@guyca would you be open to reviewing a github repo using RNN? 

Is there anything the error outputted above could indicate?

**Comment by guyca** [comment]
@pribeh Yes of course, If you could upload a project where this reproduces I'll gladly look into it.
Another option is to PR a failing Detox e2e test, if you need any assistance with that, ping me on Discord.

**Comment by bogobogo** [comment]
@guyca I have reproduced this issue locally. reopening.

**Comment by pribeh** [comment]
@yogevbd Is there a reason you closed the issue? We still haven't got past this hurdle.

**Comment by bogobogo** [comment]
Hey @pribeh, make sure that your tab is inside a stack and is not just a component. Note that in this [example](https://wix.github.io/react-native-navigation/v2/#/docs/top-level-api?id=setrootlayout) the second tab is a component without a stack, so push won't work.  We should probably change this example to something more clear...

**Comment by EliSadaka** [comment]
This is what our Navigation.setRoot function looks like. Unless I've done something wrong our tabs are all inside a stack, but we're still having this issue.

```
Navigation.setRoot({
   bottomTabs: {
	children: [
	   {
		stack: {
		   children: [
			{
			   component: {
				id: "HomeScreen",
			   	name: "HomeScreen"
			   }
			}
		   ],
		   options: {
			bottomTab: {
			   title: "Home",
				icon: require("./img/circle/circle.png") //placeholder
			   }
			}
		   }
		},
		{
		   stack: {
			children: [
			   {
				component: {
				   id: "ChatScreen",
				   name: "ChatScreen"
				}
			   }
			],
			options: {
			   bottomTab: {
				title: "Chat",
				icon: require("./img/circle/circle.png") //placeholder
			   }
			}
		   }
		},
		{
		   stack: {
			children: [
			   {
				component: {
				   id: "ChallengeScreen",
				   name: "ChallengeScreen"
				}
			   }
			],
			options: {
			   bottomTab: {
				title: "Challenges",
				icon: require("./img/circle/circle.png") //placeholder
			   }
			}
		   }
		},
		{
		   stack: {
			children: [
			   {
				component: {
				   id: "NotificationScreen",
				   name: "NotificationScreen"
				}
			   }
			],
			options: {
			   bottomTab: {
				title: "Notifications",
				icon: require("./img/circle/circle.png") //placeholder
			   }
			}
		}
	   }
	],
   }
});
```

**Comment by KA5558** [comment]
I think you missing add registerAppLaunchedListener before your setRoot.

**Comment by KA5558** [comment]
Is there any solution? In my case page is rendering but not opening

**Comment by KA5558** [comment]
I think I found!
Firstly you should give id stacks then put the screen in children

` stack: {
                        id:"myId"        //You will call this stack by id
			children: [
			   {
				component: {               //It is your other screen. This page will not  appear
				   id: "myPage",
				   name: "MyPage"
				}
			   },
                           {
				component: {             //It is your first screen
				   id: "NotificationScreen",                         
				   name: "NotificationScreen"
				}
			   }
			],`


then call this page like this


`Navigation.push("myId", {           //Use your stack id instead of this.porps.componentId
        component: { 
          name: 'MyPage'            
        }      
      })`

**Comment by KA5558** [comment]
I think I found!
Firstly you should give id stacks then put the screen in children


stack: {
                        id:"myId"                           //Your stack Id
			children: [
			   {
				component: {      //This page will not appear in first time
				   id: "myPage",
				   name: "MyPage"
				}
			   },
                           {
				component: {             //It is your first screen
				   id: "NotificationScreen",                         
				   name: "NotificationScreen"
				}
			   }
			],



then call this page like this


Navigation.push("myId", {          //Use your stack Id instead of this.pros.componentId
        component: { 
          name: 'MyPage'            //any children in your stack
        }      
      })

**Comment by cool94amit** [comment]
I had to change build.gradle inside node_modules/react-native-google-signin/android to below settings to get this working

`def safeExtGet(prop, fallback) {
rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

buildscript {
repositories {
google()
jcenter()
maven {
url "https://maven.google.com"
}
}
dependencies {
classpath 'com.android.tools.build:gradle:+'
}
}

allprojects {
repositories {
google()
jcenter()
maven { url "$projectDir/../node_modules/react-native/android" }
}
}

apply plugin: 'com.android.library'

android {
compileSdkVersion safeExtGet('compileSdkVersion', 26)
buildToolsVersion = '28.0.2'

defaultConfig {
minSdkVersion safeExtGet('minSdkVersion', 16)
targetSdkVersion safeExtGet('targetSdkVersion', 26)
versionCode 1
versionName "1.0"
ndk {
abiFilters "armeabi-v7a", "x86"
}
}

lintOptions {
    abortOnError false
}
}

dependencies {
implementation fileTree(include: ['*.jar'], dir: 'libs')
implementation "com.android.support:appcompat-v7:${safeExtGet('supportLibVersion', '26.1.0')}"
implementation "com.google.android.gms:play-services-auth:${safeExtGet('googlePlayServicesAuthVersion', '16.0.1')}"
implementation "com.facebook.react:react-native:+"
}`

**Comment by hto** [comment]
@EliSadaka great!!!

**Comment by vivek6923** [comment]
This seems to work perfectly fine in my case , RN version - 0.57.7 , "react-native-navigation": "^2.5.1"

Navigation.setRoot({
            root: {  // Don't forget to set it as root
              bottomTabs: {

                children: [
                  {
                    stack: { . // Each tabs must be in a stack.
                      children: [
                        {
                          component: {
                            id: "Home",
                            name: 'app.taper.CustomerHomePage'
                          }
                        }
                      ],
                      options: {
                        bottomTab: {
                          title: "Home",
                          icon: require('../images/Home.png')
                        }
                      }
                    }
                  },
                  {
                    stack: {
                      children: [
                        {
                          component: {
                            id: "Search",
                            name: 'app.taper.CustomerSearch'
                          }
                        }
                      ],
                      options: {
                        bottomTab: {
                          title: 'Search',
                          icon: require('../images/Search.png')
                        }
                      }
                    }
                  },
                  {
                    stack: {
                      children: [
                        {
                          component: {
                            id: "Appointment",
                            name: 'app.taper.UsersAppointments'
                          }
                        }
                      ],
                      options: {
                        bottomTab: {
                          title: "Appointment",
                          icon: require('../images/Appointment.png')
                        }
                      }
                    }
                  }
                ]
              }
            }
          });

**Comment by LRNZ09** [comment]
I'm also having this issue on `2.9.0`
@KA5558 you are right but on iOS it works without any workaround.
@yogevbd this issue should not be closed.

**Comment by bcicube** [comment]
I too having same issue. Any workaround ?

**Comment by djnsu** [comment]
Same here.

**Comment by FahdJamy** [comment]
Still having the push issue.

**Comment by HugoLiconV** [comment]
I'm getting this error when pushing a screen:
`undefined is not an object (evaluating 'api.name.toString'`

**Comment by Rubenvdveen** [comment]
This happened to me while using the new hot reload of React-native. After properly reloading the app, the issue disappeared.

**Comment by Luktm** [comment]
![image](https://user-images.githubusercontent.com/24861458/71613898-befc5580-2be3-11ea-8da2-5672af3e1e46.png)


I solved my problem using this solution from this medium page 
```
Navigation.setRoot({
        root: {
            stack: {
                children: [{
                    component: {
                        name: 'Login',
                        options: {
                            topBar: {
                                title: {
                                    text: 'Login'
                                }
                            }
                        }
                    }
                }]
            }
        }
    });
```
