### ISSUE TITLE
Requiring "react-native-navigation" module from node  leads to an error (Cannot find module './deprecated/indexDeprecated')

### ISSUE THREAD

**Issue by vyshkant** [wix/react-native-navigation#2987]
### Issue Description

Requiring "react-native-navigation" module from node  leads to an error:
```
Error: Cannot find module './deprecated/indexDeprecated'
```

You can say that `react-native-navigation` should not work in node environment, BUT I'm not trying to use it (to use means to invoke any function). I'm not invoking anything, I'm only requiring, which, IMO, should not lead to an error.

### Steps to Reproduce / Code Snippets / Screenshots

1. Create file `foo.js`:

```javascript
require("react-native-navigation");
```

2. Run it with `node`:
```bash
$ node foo.js 
module.js:549
    throw err;
    ^

Error: Cannot find module './deprecated/indexDeprecated'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/my/project/node_modules/react-native-navigation/src/index.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
---
### Environment
* React Native Navigation version: `1.1.412`
* React Native version: `0.54.2`
* Platform(s) (iOS, Android, or both?): `node`
* Device info (Simulator/Device? OS version? Debug/Release?): Node version `v8.11.1`

---

### The cause
Obviously, the cause is that `src/index.js` file contains next line:
https://github.com/wix/react-native-navigation/blob/a520aca0d4288cebae0bfd441d776e724910c3eb/src/index.js#L1

while the `deprecated` folder contains files named `index.android.js` and `index.ios.js` but not `index.js`.

**Comment by vyshkant** [comment]
If you agree with my arguments and have any idea how to fix it, I will gladly write a PR.

**Comment by Aman40** [comment]
If you figure it out please don't forget to share. Thanks :)

**Comment by anil11** [comment]
error: bundling failed: Error: Unable to resolve module `./../Navigation` from `/Users/anil/Desktop/Reactnative/sellit/node_modules/react-native-navigation/src/deprecated/indexDeprecated.ios.js`: The module `./../Navigation` could not be found from `/Users/anil/Desktop/Reactnative/sellit/node_modules/react-native-navigation/src/deprecated/indexDeprecated.ios.js`. Indeed, none of these files exist:

**Comment by danangan** [comment]
I have the same problem. Do anyone have any idea?

**Comment by danangan** [comment]
@vyshkant do you have any solution yet? I got stuck in this problem for hours now.
