### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by fmoessle** [wix/react-native-navigation#2988]
### Issue Description

I started a fresh project with the react-native-cli and tried to add v2 of your project.

I added the project to LIBRARIES, added the header search paths (tried $(SRCROOT)/../node_modules/react-native-navigation/ios and $(SRCROOT)/../node_modules/react-native-navigation/lib/ios) and linked the library with lib.ReactNativeNavigation.a

When I want to start the project, my simulator says: Native module cannot be null

and Xcode tells me: [this function is not a prototype](https://ibb.co/gx0RNH)

Thanks in advance

---
### Environment
* React Native Navigation version: 055.1
* React Native version: 2.0.2229
* Platform(s) (iOS, Android, or both?): iOS 11.3
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
We should revisit the installation guide and see if there are missing steps when creating a project from scratch using `react-native-cli`

**Comment by jeprojects** [comment]
@guyca This seems to be the same issue I am having after updating from React Native 0.54.* to 0.55.2.

#3019

**Comment by guyca** [comment]
Thanks @jeprojects, closing in favor of #3019

**Comment by noumanDev** [comment]
@fmoessle did you fix the issue? i am having same issue 
react-native : 0.54.4
