### ISSUE TITLE
Custom Left Button not showing on Android

### ISSUE THREAD

**Issue by andrei0807** [wix/react-native-navigation#2993]
### Custom Navigation Button
import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity, } from 'react-native';
import { Navigation, } from 'react-native-navigation';

class WishlistIcon extends React.Component {
  render() {
    return (
      <TouchableOpacity
        style={[styles.container, { backgroundColor: 'tomato', },]}
        onPress={() => alert('pressed!')}
      >
        <View style={styles.container}>
          <Text style={{ color: 'white', }}>{'Hi'}</Text>
        </View>
      </TouchableOpacity>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    overflow: 'hidden',
    width: 34,
    height: 34,
    borderRadius: 34 / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

Navigation.registerComponent('WishlistIcon', () => WishlistIcon);

export default WishlistIcon;

### Add button to screen.

class ProductsScreen extends React.Component {
  static navigatorButtons = {
    leftButtons: [
      {
        id: 'WishlistIcon',
        component: 'WishlistIcon', 
        passProps: {}
      },
    ],
  };
}

but i can not show left button, Please help me!!!

**Comment by guyca** [comment]
Hey there, react components are only supported for right buttons on Android.

**Comment by andrei0807** [comment]
No, i added icon to left button position, but i can not add custom button on android

**Comment by ujwal-setlur** [comment]
@guyca why are react components supported only for right buttons, and not left?

**Comment by guyca** [comment]
@ujwal-setlur Because the native api supports only icons on Android. It's possible to workaround this limitation by simply adding a view before the title's `TextView`, we're open for PR's and might add this functionality later on ourselves.
