### ISSUE TITLE
Black BG after LaunchScreen

### ISSUE THREAD

**Issue by pvlvsk** [wix/react-native-navigation#30]
Hello,

on your examples the LaunchScreen fades to black before the app initializes. How one would accomplish a white BG so there is no transition to black and back to white app interface?

Thank you

**Comment by talkol** [comment]
This is an issue with the dependency `react-native-controllers`
It was solved there 2 days ago with this [commit](https://github.com/wix/react-native-controllers/commit/eadf2978784d630eff2a0c868eb913558c88a90e)
Long story short, delete node_modules, reinstall and this should be fixed
