### ISSUE TITLE
Modal connected to Redux makes navigator events not firing anymore after first dismiss 

### ISSUE THREAD

**Issue by 39otrebla** [wix/react-native-navigation#3004]
### Issue Description

We have a modal component registered with
```javascript
Navigation.registerComponent(SID_CARTS_CONTAINER, () => CartsContainer, store, Provider)
```
that should be opened tapping on a navbar right button.
```javascript
onNavigatorEvent(event) {
    if (event.type === 'NavBarButtonPress') {
      if (event.id === 'cart') {
        Navigation.showModal({
          screen: SID_CARTS_CONTAINER,
          title: 'Cart',
          animationType: 'fade',
          passProps: {
            viewCart: 0,
          }
        })
      }
    }
  }
```

Component is exported as usual with
```javascript
export default connect(mapStateToProps, mapDispatchToProps)(CartsContainer)
```

The first tap on the navbar right button works as expected: press event is fired and modal is opened. But dismissing the modal (either via hardware back button press or via `Navigation.dismissModal()`) has a **very strange behavior**: all rendered views (it is a `Tabbar-based` app) **stop receiving events**, i.e. it is no more possibile to re-open the modal because no navigator event is fired from now on, in every tab! Neither button press events, nor screen visibility changes events. Really, **no more navigator events are fired**.
The other "funny" thing is that if you push a new screen from one of the 5 tabs, it happens the same thing: the first tap on the navbar right button works as expected, the event is fired and modal opens.. and if you dismiss it, it stops again receiving events (at this navigation stack level). And it keeps doing the same for every push.
**Disconnecting the outer Component (CartsContainer) from Redux fixes the issue.** Also, bear in mind that opening/closing the modal from a ReactNative touchable works just fine, because the issue is at navigator events level.

### Steps to Reproduce / Code Snippets / Screenshots

1. Create a component and connect it to Redux. Register the screen with ReactNative Navigation API `registerComponent`, passing `store` and `Provider` as usual.
2. Create a tabbar-based app and add a navbar right button to every tab
3. Set `onNavigatorEvent` for opening the modal on navbar right button press

Now try to open the modal from whichever tab and dismiss it (either via hardware back button press or via `Navigation.dismissModal()`. Then try to open it again tapping on navbar right button.

---
### Environment
* React Native Navigation version: 1.1.436
* React Native version: 0.54.3
* Platform(s) (iOS, Android, or both?): Android (iOS not tested but might happen there as well)
* Device info (Simulator/Device? OS version? Debug/Release?): Real Device, Android Lollipop and above, Debug and Release builds

**NOTE:** this is issue was **NOT** happening for sure on react-native@0.48.3 and react-native-navigation@1.1.205. Indeed, we have this app in production with those versions and is working just fine.

**Comment by leolusoli** [comment]
+1.

Using Redux <Provider /> component (instead of passing it through registerComponent func) didn't solve the problem.

**Comment by rezasazesh** [comment]
This should not be closed

**Comment by 39otrebla** [comment]
@rezasazesh it should, we realized (much) later on that we were unsubscribing from all Navigation events (I do not remember the exact code, but conceptually we were doing `detachAll` instead of `detach`). Fixing our code solved the issue, and it never came back in all our apps.
