### ISSUE TITLE
multiple push..

### ISSUE THREAD

**Issue by MeKarina** [wix/react-native-navigation#301]
# environment..
suppose i have `FirstTabScreen` and `SideMenu` with the title `Menu`...

`FirstTabScreen` and `SideMenu` contain menu list... let's say..

1. menu1
1. menu2
1. menu3

# scenario..

1. on `FirstTabScreen` i push menu2 => `menu2Screen` opened => pop to `FirstTabScreen`
2. on `FirstTabScreen` i push again menu2 => `menu2Screen` opened => pop to `FirstTabScreen`
3. on `FirstTabScreen` i push again menu2 => `menu2Screen` opened

on `menu2Screen`,, i swipe to open `SideMenu`...

on `SideMenu`,, suppose i have `menu1`..

i push `menu1Screen`,, this will push `menu1Screen` **3 times**... why 3 times..?? maybe because previously i pushed `menu2Screen` 3 times... so all opened `menu2Screen` (in this case 3 `menu2Screen`) will be pushed to `menu1Screen`...

would be great if this library have nice api to deal with this kind of scenario...

# note..
What version of `react-native` you are using: 0.31.0
What version of `react-native-navigation` you are using: 2.0.0-experimental.105

**Comment by DanielZlotin** [comment]
Hmm.. interesting
Does it happen on both platforms?

**Comment by MeKarina** [comment]
Tested on ios...

When i said pop to,, it simply i click back button... Not sure back button == popTo...

**Comment by MeKarina** [comment]
use `resetTo` instead... dont `push`...
