### ISSUE TITLE
white screen in ios after returning from a pushed view wich is not registered

### ISSUE THREAD

**Issue by ogostus** [wix/react-native-navigation#3010]
### Issue Description

when implementing a react native modal or a third module who pushes a view like "react native imagepicker", the current screen disappear and app display white screen after pressing the back button in ios

### Steps to Reproduce / Code Snippets / Screenshots

-implement react native modal
-show modal
-dismiss modal

---
### Environment
* React Native Navigation version: 1.1.409
* React Native version: 0.54.1
* Platform(s): IOS
* Device info: ALL

**Comment by guyca** [comment]
Hey @ogostus 
V1 is not supported anymore as we're transitioning to v2. If this issue exists in v2 as well, I suggest you PR a failing detox e2e test and we'll take it from there.
I'm closing as we can't afford to address issues in v1.
