### ISSUE TITLE
TopBar flashes briefly when showing a screen with TopBar hidden

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#3016]
Noticeable in `WelcomeScreen.js`

**Comment by DavitVosk** [comment]
@guyca I have the same problem here on IOS. Could you find a solution for this?

**Comment by guyca** [comment]
Hey @DavitVosk, I'll look into this issue this week, we have a few other tasks prioritised for iOS for this week.. I'll see what I can do.

**Comment by nSimonFR** [comment]
I found that playing with the property `topBar` `animate` in the options getter and `setDefaultOptions` was able to prevent the weird animation flash and seems to be more stable, if it helps anyone
