### ISSUE TITLE
React Native v0.55.2 Build Issue [v2]

### ISSUE THREAD

**Issue by jeprojects** [wix/react-native-navigation#3019]
### Issue Description

After updating to React Native v0.55.2 it has a build issue with React Native Navigation:

/MyApp/node_modules/react-native/React/Views/RCTFont.h:21:37: This function declaration is not a prototype

/MyApp/node_modules/react-native-navigation/lib/ios/RCTHelpers.m:4:9: In file included from /MyApp/node_modules/react-native-navigation/lib/ios/RCTHelpers.m:4:

Is this a problem with the update or is RNN not compatible with React Native 0.55.2 yet?

### Steps to Reproduce / Code Snippets / Screenshots

Update to React Native v0.55.2 using `react-native-git-upgrade`

---
### Environment
* React Native Navigation version: 2.0.2237
* React Native version: 0.55.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Debug Simulator

**Comment by jeprojects** [comment]
Just an update, I created a fresh react native 0.55.2 project and only installed React Native Navigation. The same error message occurs.

**Comment by stefanedberg** [comment]
I'm having the same problem on a fresh project created with react-native init.
react-native-cli: 2.0.1
react-native: 0.55.2
react-native-navigation: 2.0.2237

If I change
`RCT_EXTERN BOOL RCTHasFontHandlerSet();`
to this, it runs
`RCT_EXTERN BOOL RCTHasFontHandlerSet(void);`

**Comment by larryranches** [comment]
@stefanedberg As @jeprojects stated, downgrade your react-native version to 0.55.4 till this issue is fixed. I can confirm that its working with this version.

**Comment by Alu1911** [comment]
@stefanedberg your solution solved my problem. Thanks!

**Comment by congnguyen91** [comment]
- This has been closed on react-native now :) waiting for new release :D

**Comment by yogevbd** [comment]
Fixed in react-native: https://github.com/facebook/react-native/commit/37c820f16e33746241af05e188d69502f518f80d
