### ISSUE TITLE
navigator.push() returns a Promise for Android, nothing on iOS

### ISSUE THREAD

**Issue by sqow** [wix/react-native-navigation#3021]
### Issue Description

`this.props.navigator.push()` on Android returns a Promise (both for [deprecated](https://github.com/wix/react-native-navigation/blob/master/src/deprecated/platformSpecificDeprecated.android.js#L84-L105) as well as for [current](https://github.com/wix/react-native-navigation/blob/master/src/platformSpecific.android.js#L13-L16) implementations), however for iOS [nothing is returned](https://github.com/wix/react-native-navigation/blob/master/src/deprecated/platformSpecificDeprecated.ios.js#L322-L379) (the current implementation is [empty](https://github.com/wix/react-native-navigation/blob/master/src/platformSpecific.ios.js)).

**Expectation**: `push` should either consistently return a Promise or return nothing at all. Preferably, a Promise would be returned uniformly as it allows for more flexibility.

### Steps to Reproduce / Code Snippets / Screenshots

```js
const pushOpts = {
  screen: 'YourScreenName'
}
this.navigator.push(pushOpts)
  .then(() => {
    console.log('This works on Android, but fails on iOS')
  })
```

---
### Environment
* React Native Navigation version: 1.1.436
* React Native version: 0.49.5
* Platform(s) (iOS, Android, or both?): iOS/Both
* Device info (Simulator/Device? OS version? Debug/Release?): Device, iOS 10.3.3, Debug or Release

**Comment by guyca** [comment]
Hey @sqow 
All commands return promises in v2, v1 isn't supported anymore as we're transitioning to v2. I'm closing as this won't be implemented in v1.
