### ISSUE TITLE
Support for initialization of external modules with bridge

### ISSUE THREAD

**Issue by silyevsk** [wix/react-native-navigation#3024]
### Issue Description

Sometimes there are RN modules that require initialization with parameters, such modules should be initialized via the `extraModulesForBridge` method from the `RCTBridgeDelegate` protocol.
However, RNN initializes the bridge by itself and sets itself as the bridge delegate, thus modules with custom initialization can't be used with RNN.
It would be great if support for external modules with custom initialization could be added to the RNN API.

**Comment by guyca** [comment]
I believe we're already exposing `getBridge` method on both v1 and v2, is that not enough?

**Comment by silyevsk** [comment]
The bridge is not enough - it's about dependency injection to modules. For example, there's some native class whose instance should be passed to one or several modules. In order to pass the instance, instead of letting react native initialize the modules with `[[module alloc] init]` (with no params), the module should be initialized in the bridge delegate's `extraModulesForBridge` method.

**Comment by silyevsk** [comment]
Looks like it wasn't implemented yet

**Comment by yogevbd** [comment]
Added the option to delegate the bridgeManager in order to inject extraModules.

`[ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions bridgeManagerDelegate:delegate]`

**Comment by benpeke** [comment]
This functionality was [removed in V5]( https://github.com/wix/react-native-navigation/commit/373f20b5800b354a774a0acb47f595ad0aa4f01e#diff-c801f57930bf73d8b1873f21dfc7750d). Is there a replacement ?
