### ISSUE TITLE
"End" old navigators

### ISSUE THREAD

**Issue by joecaraccio** [wix/react-native-navigation#3025]
Hi everyone,

Is there a way people use "startTabBased()" And startSingleScreenapp (might not be the exact name but you get the idea) in the same app? In particular we have a login type flow but have noticied that after we start out tab bar, after starting single screen.. some of the behavior can be weird. 

Should we be removing the old nav stacks somehow.. or just using a native nav?

**Comment by joecaraccio** [comment]
*typo on the end but it won't let me edit it for some reason


Should we be removing the old nav stacks somehow.. or only using one app type.. tab..single screen..

**Comment by guyca** [comment]
You can call `start*App` multiple times, I'm not sure what you mean by "old navigators" as the navigator is a Js object attached to React components, once a component is unmounted you shouldn't use it's navigator.
