### ISSUE TITLE
setOptions should update an existing components props

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#3030]
Currently, in order to update a components props (TopBar title component for example) we need to connect it or hack some some other solution).
Ideally we'd be able to call `mergeOptions` to update props:

```js
Navigation.mergeOptions('my unique id', {
  topBar: {
    title: {
      component: {
        componentId: 'MY_COMP',
        passProps: {
          counter: 1
        }
      }
    }
  }
});
```

**Comment by guyca** [comment]
I'm wondering if this can be solved by using [Context API](https://reactjs.org/docs/context.html)

**Comment by diegolmello** [comment]
This feature would be awesome!

**Comment by ChristianPraiss** [comment]
This has not been resolved yet and shouldn't have been closed!

**Comment by donovanhiland** [comment]
Something I can do to help move this along? @guyca

**Comment by LRNZ09** [comment]
This would be really helpful!

**Comment by akupczak** [comment]
We really need this...

**Comment by sophister** [comment]
same problem. 
How to update custom title Component through `Navigation.mergeOptions` ?

**Comment by NdauwaRafael** [comment]
Any progress on this? @guyca ??

**Comment by jfojtl** [comment]
I think anyone using custom component in header will hit this problem. Passing refs as recommended in https://stackoverflow.com/questions/53072562/how-can-i-update-a-custom-top-bar-title-component-in-react-native-navigation-v2?rq=1 seems too cumbersome (not the only example of cumbersome with this lib..).

**Comment by JunoVW** [comment]
Has this been resolved?

**Comment by ribbedcrown** [comment]
@JunoVW  Take a look at #5623.

**Comment by guyca** [comment]
Closing as this is fixed by `Navigation.updateProps()` which was added in [3.4.0](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#340)
