### ISSUE TITLE
Fix tabBar margins

### ISSUE THREAD

**Issue by sreuter** [wix/react-native-navigation#3037]
### Issue Description

The tabBar margins look odd on all iPhones apart from iPhone X. At least the bottom margin could use a few more pts/pixels :)

### Steps to Reproduce / Code Snippets / Screenshots

See screenshot.

---
### Environment
* React Native Navigation version: 1.1.436
* React Native version: 0.52.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 7 Plus Simulator+
![screen shot 2018-04-14 at 2 04 40 am](https://user-images.githubusercontent.com/550246/38745797-fc178582-3f88-11e8-9532-efb1bfe1601b.png)
Device

**Comment by yogevbd** [comment]
This is the iOS native behaviour..
