### ISSUE TITLE
Android blank white screen after launch

### ISSUE THREAD

**Issue by varqasim** [wix/react-native-navigation#3044]
### Issue Description

When using react-native-navigation, the Android app launches but it only shows a white blank screen. It doesn't get connected to the debugger no matter what. Even when enabling or disabling the debugger, which I think isn't the problem. When checking Logcat in android studio this error stands out. `E/unknown:ReactNative: Unable to display loading message because react activity isn't available` It only happened after setting up my project with react-native-navigation that this happens.

This is only in Android, iOS works perfectly.

### Steps to Reproduce / Code Snippets / Screenshots

Followed the set up for Android for the documentation and the end result of my `MainApplication` is

```
import com.airbnb.android.react.maps.MapsPackage;
import com.babisoft.ReactNativeLocalization.ReactNativeLocalizationPackage;
import com.brentvatne.react.ReactVideoPackage;
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.learnium.RNDeviceInfo.RNDeviceInfo;
import com.oblador.vectoricons.VectorIconsPackage;
import com.reactnativenavigation.NavigationApplication;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends NavigationApplication {

  @Override
  public boolean isDebug() {
    // Make sure you are using BuildConfig from your own application
    return BuildConfig.DEBUG;
  }

  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new ReactNativePushNotificationPackage(),
            new MapsPackage(),
            new ReactVideoPackage(),
            new VectorIconsPackage(),
            new ReactNativeLocalizationPackage(),
            new RNDeviceInfo()
    );
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }

  @Override
  public String getJSMainModuleName() {
    return "index";
  }


}
```

As for `MainActivity` 

```
import com.reactnativenavigation.controllers.SplashActivity;

public class MainActivity extends SplashActivity {

}
```

---
### Environment
* React Native Navigation version: ^1.1.440
* React Native version: ^0.53.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device and Simulator, Debug

**Comment by hamidhadi** [comment]
@guyca I get this error too. How can we fix this?

**Comment by kermopajula** [comment]
+1

**Comment by jctf** [comment]
try following steps: 

- `rm -rf node_modules`
- `rm -rf ~/.rncache`
- `yarn cache clean`
- `rm -rf android/build` 

make sure that the Metro Bundler isn't running, if so kill it.

- `yarn install` or `npm install` then start your react native android development.

**Comment by JayStackKrisz** [comment]
I have the same issue :-(

**Comment by qasimalbaqali** [comment]
@jctf Thank you for your suggestion, tried but the same problem persists.

**Comment by fcochim** [comment]
+ 1, Running in emulator and works fine, run on Device white Screen. Only Android, iOS works fine

**Comment by jcsena** [comment]
+1 the same error

**Comment by pzw224** [comment]
+1 the same error
error message:
05-05 06:45:02.317 3511-3511/com.ngm E/unknown:ReactNative: Unable to launch redbox because react activity is not available, here is the error that redbox would've displayed: console.error: "Error while starting app: TypeError: undefined is not an object (evaluating 'PropRegistry_1.default.save')"

**Comment by matzewagner** [comment]
+ 1 for same error

**Comment by maitham1** [comment]
Same Error any solutions?

**Comment by escote** [comment]
same error

**Comment by ATShiTou** [comment]
It works well sometimes , and blank sometimes.

**Comment by qasimalbaqali** [comment]
I had to downgrade react-native for this to work. Here are my package versions:

```
"react-native": "^0.52.0",
"react": "^16.2.0",
"react-native-navigation": "^1.1.440",
```

And for my gradle settings for Android as I saw that it actually makes a difference in my case when using react-native-navigation:

`compileSdkVersion 25
    buildToolsVersion '27.0.1'`

`minSdkVersion 18
        targetSdkVersion 22` 

`implementation "com.android.support:appcompat-v7:25.0.0"`

Hope this comes into use for someone out there. Have struggled with this error for months now, and this was the only solution that I could find for me to continue working.

**Comment by williamtran1988** [comment]
Yes, the problem exactly is missing icons define.

**Comment by Geli25** [comment]
I am having the exact same issue, downgrading didn't seem to work either

**Comment by brightsider** [comment]
react-native 0.55.4 same error

**Comment by hani647** [comment]
I also faced same issue when upgraded RNN from version 1.x.x to 1.1.x. Now again I've rolled back to RNN v 1.x.x by running command
`yarn add react-native-navigation@1.x.x`
Hope work for you as well !!

**Comment by ayankhan2415** [comment]
Any Loin here to solve this error, i think there is no because react native has one drawback which is there are many Run time error, when we want to run our application, React js is better than React_native
why errors are coming

**Comment by AlphaJuliettOmega** [comment]
Installed RNN using the guide, now my 'Hello World' application is just a white screen with 0 errors, 0 debugging output.

Not happy that this thread is closed without anything being fixed.

**Comment by muhnur29** [comment]
> 
> ### Issue Description
> 
> When using react-native-navigation, the Android app launches but it only shows a white blank screen. It doesn't get connected to the debugger no matter what. Even when enabling or disabling the debugger, which I think isn't the problem. When checking Logcat in android studio this error stands out. `E/unknown:ReactNative: Unable to display loading message because react activity isn't available` It only happened after setting up my project with react-native-navigation that this happens.
> 
> This is only in Android, iOS works perfectly.
> ### Steps to Reproduce / Code Snippets / Screenshots
> 
> Followed the set up for Android for the documentation and the end result of my `MainApplication` is
> 
> ```
> import com.airbnb.android.react.maps.MapsPackage;
> import com.babisoft.ReactNativeLocalization.ReactNativeLocalizationPackage;
> import com.brentvatne.react.ReactVideoPackage;
> import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
> import com.facebook.react.ReactPackage;
> import com.facebook.react.shell.MainReactPackage;
> import com.learnium.RNDeviceInfo.RNDeviceInfo;
> import com.oblador.vectoricons.VectorIconsPackage;
> import com.reactnativenavigation.NavigationApplication;
> 
> import java.util.Arrays;
> import java.util.List;
> 
> public class MainApplication extends NavigationApplication {
> 
>   @Override
>   public boolean isDebug() {
>     // Make sure you are using BuildConfig from your own application
>     return BuildConfig.DEBUG;
>   }
> 
>   public List<ReactPackage> getPackages() {
>     return Arrays.<ReactPackage>asList(
>             new MainReactPackage(),
>             new ReactNativePushNotificationPackage(),
>             new MapsPackage(),
>             new ReactVideoPackage(),
>             new VectorIconsPackage(),
>             new ReactNativeLocalizationPackage(),
>             new RNDeviceInfo()
>     );
>   }
> 
>   @Override
>   public List<ReactPackage> createAdditionalReactPackages() {
>     return getPackages();
>   }
> 
>   @Override
>   public String getJSMainModuleName() {
>     return "index";
>   }
> 
> 
> }
> ```
> 
> As for `MainActivity`
> 
> ```
> import com.reactnativenavigation.controllers.SplashActivity;
> 
> public class MainActivity extends SplashActivity {
> 
> }
> ```
> 
> ### Environment
> 
>     * React Native Navigation version: ^1.1.440
> 
>     * React Native version: ^0.53.0
> 
>     * Platform(s) (iOS, Android, or both?): Android
> 
>     * Device info (Simulator/Device? OS version? Debug/Release?): Device and Simulator, Debug

hei i have problem my project can't showing after run on my device 
i build list view using array adapter 
but nothing happen in my project just white screen and tittle project
can you help me answer please
