### ISSUE TITLE
how to get a splash screen first and then go the main home screen

### ISSUE THREAD

**Issue by wilbyang** [wix/react-native-navigation#305]
I am using react-native 0.32.0 and  "react-native-navigation": "^1.0.30", And I want to get a splash screen first and then go to the main home screen, where I begin to use react-native-navigation. I  googled a lot and did a lot re research but still do not know how to make this. I try to get the simplest config passed to Navigation.startSingleScreenApp, but I still get the navbar in iOS. is it possible to get a raw splash screen first and then use react-native-navigation for navigation?

**Comment by artald** [comment]
you can set the `navigatorStyle` of your screen to not show the bar:
```javascript
class MyScreen extends Component {
  static navigatorStyle = {
    navBarHidden: true
  };
 ...
}
```

See the [docs](https://github.com/wix/react-native-navigation/wiki/Styling-the-navigator) for more details and styling options

**Comment by leotu** [comment]
I have the same problem but by using "rn-splash-screen" project.
(https://github.com/mehcode/rn-splash-screen
https://github.com/mehcode/rn-splash-screen/blob/master/docs/ios.md)

The Question is "react-native-navigation" has to remove rootView
```OC
RCTRootView *rootView = ...
````

but "rn-splash-screen" need to use use rootView
(https://github.com/wix/react-native-navigation/blob/master/example/ios/example/AppDelegate.m)

```OC
RCTRootView *rootView = // [...]

  // Show splash screen (rn-splash-screen)
  [RCTSplashScreen show:rootView];
```

So, how to solve it ?

**Comment by chrise86** [comment]
I'm facing a similar situation where I'd like to display a login / register screen(/'s) initially, and then start a tab bar. My assumption would be to:

1. Check current login state
2. `Navigation.startTabBasedApp` if logged in
3. `Navigation.startSingleScreenApp` if not logged in

Would this be correct? How would I handle logging in / out, and re-initialising the app? As this would be outside of a react component I also have no way of maintaining and reacting to state.

**Comment by guyca** [comment]
That's the correct way to do it indeed. To implement logout, simply call `Navigation.startSingleScreenApp` and show your login screen. You can react to state as you normally would after the call to `startApp` and the screen is created. If it's a logout and login use case you don't even need to worry about persisting your current state.

**Comment by chrise86** [comment]
Ah of course, I'd simply call Navigator.start again on logout. Thanks very much!

**Comment by vdesdoigts** [comment]
@leotu Have you find a solution ?

**Comment by Jaafar-abusair** [comment]
What you mean, you are getting the splash screen by default, until you call Navigation.startSingleScreenApp or Navigation.startTabBasedApp. what i see a problem now is that you can't customized the splash screen, what I did to change the color in the Main activity 
@Override
    public View createSplashLayout() {
        View view = new View(this);
        view.setBackgroundColor(Color.parseColor("#11505f"));
        return view;
    }

**Comment by DanielZlotin** [comment]
@Jaafar-abusair You can actually return any `View` you want from this method and we will display it for you in the `splash` screen (while the js bundle loads). I don't know if we can make it more customisable than that...

**Comment by Jaafar-abusair** [comment]
I know that, I'm explaining this to the issue owner, making it more customization by letting the user from the react native set the view content, but i have no idea if that possible since I think the creation of this view before loading the RN.

**Comment by DanielZlotin** [comment]
@Jaafar-abusair oh I see. Yeah before the react context is created you essentially have no javascript, so we have to use native views. That's OK because most of the time the splash should be quick and static. Maybe we will add some templates in the future for those that don't know any Java/ObjectiveC...

**Comment by guyca** [comment]
@DanielZlotin Make it a plugin to RNN

**Comment by jasonhealy** [comment]
Do you have an example of this for AppDelegate.m / ObjectiveC? I have a Launch Screen.storyboard but there's still a flash between that and my first screen while RN is loading.

**Comment by SudoPlz** [comment]
@DanielZlotin I think when you said we can actually return any `View` you were referring to Android.
Is there any way to customise the splash screen on iOS?
I'm trying all sorts of madness to do that https://github.com/wix/react-native-navigation/issues/916#issuecomment-288604574 but I still have problems.

**Comment by SudoPlz** [comment]
Also this thread is so weird.. An initial question comes along the way, then someone else asks a totally irrelevant question, and then the initial question remains unanswered.

Did you guys manage to find the solution for iOS @leotu or @Jaafar-abusair ?

Am I missing something obvious here?

Thanks.

**Comment by terrysahaidak** [comment]
Just created custom splashScreen in my app using version 2.0.0.experimental.302.
Here is the code:

```
package com.gittermobile;

import android.widget.LinearLayout;
import android.graphics.Color;
import android.widget.TextView;
import android.view.Gravity;
import android.util.TypedValue;
import com.reactnativenavigation.controllers.SplashActivity;

public class MainActivity extends SplashActivity {

    @Override
    public LinearLayout createSplashLayout() {
        LinearLayout view = new LinearLayout(this);
        TextView textView = new TextView(this);

        view.setBackgroundColor(Color.parseColor("#E20354"));
        view.setGravity(Gravity.CENTER);

        textView.setTextColor(Color.parseColor("#FFFFFF"));
        textView.setText("GitterMobile");
        textView.setGravity(Gravity.CENTER);
        textView.setTextSize(TypedValue.COMPLEX_UNIT_DIP, 40);

        view.addView(textView);
        return view;
    }
}
```

Here is the result:
<details>
![image](https://cloud.githubusercontent.com/assets/7809008/25202171/b8976920-2554-11e7-8ed3-724c1446350e.png)
</details>

**Comment by Ehesp** [comment]
Thanks @terrysahaidak I've added this as an example to the docs 👍

**Comment by peteroid** [comment]
I modified the above one to have logo in the splash screen. See if anyone is looking for this.

```java
// you should add the logo file to the drawable folder first
@Override
    public LinearLayout createSplashLayout() {
        LinearLayout view = new LinearLayout(this);
        ImageView imageView = new ImageView(this);

        view.setBackgroundColor(Color.parseColor("#FF723F"));
        view.setGravity(Gravity.CENTER);

        // hard code the width and the height of the logo
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(400, 167);
        layoutParams.gravity = Gravity.CENTER;
        imageView.setLayoutParams(layoutParams);
        imageView.setImageDrawable(ContextCompat.getDrawable(this.getApplicationContext(), R.drawable.logo_file));

        view.addView(imageView);
        return view;
    }
```

**Comment by guyca** [comment]
Thanks guys. Seems like op's question is answered so I'm closing the issue. If anyone experiences issues with third party splash libraries, please open a separate issue.

**Comment by MrLoh** [comment]
I restore the first screen of my app from async storage, that means that I need to sometimes fire a few pushes before the app is in the state where it was last left from again. Unfortunately this looks a bit weird. The normal splash screen disappears and then the root view of a tab first shows and in the next blink the view is pushed on top of it (without animation). I would be nice to show the splash screen until the child view is mounted, but I don't know how I would do this, I'd basically need a splash screen view that's ontop of all the other navigation screens.

**Comment by eagle-design** [comment]
How to define R.drawable.logo_file ?

**Comment by peteroid** [comment]
@eagle-design that s your logo file you have added in the android project (usually locates in `android/app/main/res/drawable`)

**Comment by eagle-design** [comment]
@peteroid  i dont know xml . What do you prefer ?
