### ISSUE TITLE
When will i get the v2 ? I need popTo functionality badly ...

### ISSUE THREAD

**Issue by vengal** [wix/react-native-navigation#3050]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
[popTo](https://wix.github.io/react-native-navigation/v2/#/docs/screen-api?id=poptocomponentid) is already available in v2
