### ISSUE TITLE
cannot able to remove header 

### ISSUE THREAD

**Issue by praveenkumar66** [wix/react-native-navigation#3056]
### Issue Description
How to remove header from navigation for single screen app
[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by ManigandanRaamanathan** [comment]
How to remove the header?

**Comment by vahidreza** [comment]
how?
