### ISSUE TITLE
Cannot work with 0.33.0

### ISSUE THREAD

**Issue by magicismight** [wix/react-native-navigation#306]
### Issue Description

1.x and 2.x cannot work with react-native@0.33.0 on Android due to [this commit](https://github.com/facebook/react-native/commit/fbd2e139103e3d520f6dfc009d6200f8b8168e35)
### Additional Information
- React Native Navigation version: 1.0.30
- React Native version: 0.33.0
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by chaitanya0bhagvan** [comment]
This seems to be a breaking change for RNN due to change in signature of `onActivityResult`  in [ReactInstanceManager.java](https://github.com/facebook/react-native/commit/fbd2e139103e3d520f6dfc009d6200f8b8168e35#diff-dc0f3a09c238b372cb1c27aa5f7dcbce).

**Comment by monder** [comment]
Are there any other impediments except #298 for us to upgrade and require react `v0.33+` for `2.0`?

**Comment by DanielZlotin** [comment]
I tried playing with RN33 a bit using controllers and navigation, there are a couple of weird bugs with the timing of appearance of views, so I postponed it for now. I think we will upgrade in 2.1.0

**Comment by gwendall** [comment]
+1

**Comment by monder** [comment]
Would be great to upgrade to 0.33+ sooner as there are many UI related fixes for Android (With alerts for example) and new stuff like [PermissionsAndroid](https://facebook.github.io/react-native/docs/permissionsandroid.html), where with the current architecture I have to monkeypatch `NavigationActivity`.
Plus many libraries already updated, and require 0.33+, and I can't use them because `react-native-navigation` is not compatible. Its a blocker.
I've patched the `onActivityResult`s and I didn`t notice any difference in appearance. Since the version is experimental anyway, maybe lets update and file issues for these.

**Comment by ColCh** [comment]
this project works with iOS, using version next. 

but Android version not build because if this change (first post) 

I checked on react native version 0.33

**Comment by beast** [comment]
Hi guys. Could we have some priority on this one? Even know I could patch this in order for it to compile my project. But it's stoping onActivityResult to be called for other react native libraries. And as @monder mentioned, many had upgraded to require using 0.33. Thanks a lot and appreciate all the efforts for making this package great.

**Comment by beast** [comment]
@DanielZlotin 
A pull request made to fix this issue https://github.com/wix/react-native-navigation/pull/357. I was able to use RN33 and other modules that use startActivityForResult and successfully get onActivityResult called. Hopefully this can be merged soon. Are there any other issues with RN0.33 and above? I didn't really notice anything weird.

**Comment by DanielZlotin** [comment]
Thanks for the PR, but this is a breaking change, I'll merge it as soon as we update. There are other issues with RN33 so it'll have to wait.

**Comment by beast** [comment]
@DanielZlotin No problem. Understood it's breaking change. Is there a RN33 issue list or could you label all RN33 issues so I could help out? We use this package heavily and trying to keep up RN version as much as we could. Thanks.

**Comment by ColCh** [comment]
What about to merge 0.33 fix and publish it with very special tag on npm ?

or, @beast would you mind to publish it in your npm scope?

**Comment by beast** [comment]
@ColCh I think the special tag is a better idea than publishing on my own scope. But if you have a team that needs to work on RN33 or above. Feel free to do whatever you need :)

**Comment by DanielZlotin** [comment]
works in `^2.0.0-experimental.141`
