### ISSUE TITLE
Content is hidden behind status bar

### ISSUE THREAD

**Issue by djschilling** [wix/react-native-navigation#3065]
### Issue Description

I am using the `navigatorStyle` property `navBarHidden` to hide the navbar. That is working. But now the content of my screen is partially hidden behind the `DeviceStatusBar`.

Is this intended behaviour? I would expect the content to start below the status bar.

### Steps to Reproduce / Code Snippets / Screenshots

Here is how i use the screen:
```
Navigation.startSingleScreenApp({
                    screen: {
                        screen: 'churchtoolsmobile.LoginAlreadyLoggedIn',
                        navigatorStyle: {
                            navBarHidden: true
                        }
                    }
                });
```

This is how it looks rendered in the app:

![bildschirmfoto 2018-04-17 um 12 19 31](https://user-images.githubusercontent.com/3503166/38864174-27d4a9ee-423a-11e8-9c9d-72fedc9109ec.png)

---
### Environment
* React Native Navigation version: 1.1.443
* React Native version: 0.54.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS Simulator iPhone 6 iOS 11.3

**Comment by yogevbd** [comment]
You should use [SafeAreaView](https://facebook.github.io/react-native/docs/safeareaview.html).

**Comment by djschilling** [comment]
Thx, that helped.

**Comment by heyannu** [comment]
SafeAreaView doesn't help either. what else could be wrong?

**Comment by lata2694** [comment]
@heyannu Try this [react-native-safe-area-view](https://github.com/react-native-community/react-native-safe-area-view). github.com/WrathChaos/react-native-header-search-bar HeaderClassicSearchBar uses it. You may have a look.

**Comment by MoldyLunchBox** [comment]
had the same issue and SafeAreaView from 'react-native-safe-area-context' helped.  i just used it to wrap all of the routes or stacks

`    <AuthProvider>
      <SafeAreaView style={styles.container}>
        <StatusBar backgroundColor="#00C4FF" hidden={false} />
        <Routes loaded={loaded} setLoaded={setLoaded} />
      </SafeAreaView>
    </AuthProvider>
    `
