### ISSUE TITLE
Android Error while staring app:TypeError:undefined is not an object(evaluating 'NativeReactModule.startApp')"

### ISSUE THREAD

**Issue by liangshangyu** [wix/react-native-navigation#3069]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.1.443
* React Native version: 0.55
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by boomix** [comment]
Would be really nice if you would write down how you fixed the problem

**Comment by Araton95** [comment]
+

**Comment by emaddoma** [comment]
+1
