### ISSUE TITLE
ScreenVisibilityListener is not available in V2

### ISSUE THREAD

**Issue by hamidhadi** [wix/react-native-navigation#3070]
It seems RNNScreenVisibilityListener is not available and it returns null but according to the V2 doc, it should be available. 

 React Native Navigation version: 2.0.2241

```javascript
import {ScreenVisibilityListener as RNNScreenVisibilityListener} from 'react-native-navigation'

class ScreenVisibilityListener {
  constructor () {
    this.listener = new RNNScreenVisibilityListener({
      didAppear: (params) => {
         ......
      }
    })
  }
}
```

<img width="412" alt="screen shot 1397-01-29 at 12 13 13" src="https://user-images.githubusercontent.com/6258297/38918082-e591c814-4301-11e8-948e-89ad499520b4.png">

**Comment by guyca** [comment]
Hey @hamidhadi ,
That's a mistake in the docs, Where is this mentioned?

You can observe global events using `Navigation.events()`
https://github.com/wix/react-native-navigation/blob/v2/playground/src/screens/StaticLifecycleOverlay.js#L13

**Comment by guyca** [comment]
@hamidhadi The docs are slowly taking shape, you can also [contribute by pr](https://github.com/wix/react-native-navigation/tree/v2/docs/docs). We appreciate any help we can get 👍
