### ISSUE TITLE
Support for TheSideBar feedly animation?

### ISSUE THREAD

**Issue by philvasseur** [wix/react-native-navigation#3078]
### Issue Description

I noticed the drawer type and animation are iOS only. I'm trying to have the same animation on both android and iOS. I also truthfully like the android animation better where the drawer is coming out and covering the main screen. On iOS all of the animations seem to move the main view. I assumed there would be an option to have it bring the drawer over the screen, as it does in android, I realized the animation that does this is TheSideBar Feedly animation. However, for some reason it is disabled and not supported.

### Steps to Reproduce / Code Snippets / Screenshots

Put a drawer in and try opening it on iOS (with the different animation types) and android.

---
### Environment
* React Native Navigation version: 0.54.0
* React Native version: 1.1.411
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Debug

**Comment by guyca** [comment]
Hey there,
We're not supporting the SideMenu component in v1. I'm hoping that with the layout system in v2, this would be supported/possible at some point.

**Comment by chrise86** [comment]
@guyca how would you achieve this effect in v2?
