### ISSUE TITLE
[V2] Release componentId after overlay dismissed

### ISSUE THREAD

**Issue by DevArenaCN** [wix/react-native-navigation#3081]
### Issue Description
After calling `dismissOverlay`, it still holds onto the componentId. I'm not sure if it's intended or not, I would much appreciated if someone could shed some light on this.

### Steps to Reproduce / Code Snippets / Screenshots 
First call` Navigation.dismissOverlay('componentId1')`, then if you try calling 
`Navigation.showOverlay({
      component: {
        id: 'componentId1',
        name: 'overlayComponent',
        options: {
          overlay: {
            interceptTouchOutside: false
          }
        }
      }
    })`
The app will crash, and you will get an error from XCode saying `Exception 'Component id already exists minimizedPlayer' was thrown while invoking showOverlay on target RNNBridgeModule with params `

---
### Environment
* React Native Navigation version: 2.0.2241
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): iOS, haven't tested on Android yet
* Device info (Simulator/Device? OS version? Debug/Release?): emulator

**Comment by animatereactnative** [comment]
Just reproduce this issue 
"react-native": "0.72.5",
"react-native-navigation": "7.37.0",
Platform(s) (iOS, Android, or both?): Android
