### ISSUE TITLE
[iOS][v1] Disable popping-to-root behavior when clicking on tab bar by default

### ISSUE THREAD

**Issue by shivawu** [wix/react-native-navigation#3083]
### Issue Description

Clicking on the selected tab icon on iOS would trigger a pop to root behavior, which is inconsistent with Android, and often undesired.

Disabling this behavior seems as easy as adding a `return NO` after this line: https://github.com/wix/react-native-navigation/blob/master/ios/RCCTabBarController.m#L50

But I'm not sure if adding an option for it is the best way to go. If we're OK with disabling this behavior all together, I'd be happy to create the one-liner PR. I think it makes sense, since we have event issued inside wix-navigation `bottomTabReselected`, which allows custom things to be done.

### Environment
* React Native Navigation version: 1.1.431
* React Native version: 0.55.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
Hey @shivawu 
I suggest you fork and make the adjustments in your own fork for now, as we don't have much time to process v1 PR's since it's slowly being deprecated in favor of v2.

IIRC, what you suggested is actually the implementation in v2, So I rather leave it at that :)
