### ISSUE TITLE
Android tabbar icon is not center while the label is blank string.

### ISSUE THREAD

**Issue by zhaiyjgithub** [wix/react-native-navigation#3092]
Hi, I use RNN 1.1.444. I want to set the middle tabbar icon center. It works on iOS while I use **iconInsets**.
But it does not work while I set the label with blank string on Android.
Thanks a lot.

`
{
					label: '', // tab label as appears under the icon in iOS (optional)
					screen: 'CameraViewController', // unique ID registered with Navigation.registerScreen
					icon: require('../resources/images/TabBar/icon相机.png'), // local image asset for the tab icon unselected state (optional on iOS)
					selectedIcon: require('../resources/images/TabBar/icon相机hover.png'), // local image asset for the tab icon selected state (optional, iOS only. On Android, Use `tabBarSelectedButtonColor` instead)
					title: '', // title of the screen as appears in the nav bar (optional)
					navigatorStyle: {
						drawUnderNavBar: true,
						drawUnderTabBar: true,
					},
					iconInsets: { // add this to change icon position (optional, iOS only).
						top: 0, // optional, default is 0.
						left: 0, // optional, default is 0.
						bottom: -12, // optional, default is 0.
						right: 0 // optional, default is 0.
					},
				},

`

**Comment by zhaiyjgithub** [comment]
I found that in the file **AHBottomNavigation.java** android navigation only can set the global title label state. Not for the specify tabbar icon.

**Comment by guyca** [comment]
I believe that if you don't set any labels - the icons will be centered.

**Comment by zhaiyjgithub** [comment]
Thanks @guyca yes, i tried the way you told me but it did not works. I annotated the label in each tab. I need try it again and more detail.

**Comment by oferRounds** [comment]
Seeing the same issue, and on Android – the `iconInsets` is not available. Any way around this issue?
![image](https://user-images.githubusercontent.com/1477963/90106944-c6c2d180-dd50-11ea-925f-6c40021032f1.png)
