### ISSUE TITLE
[V2] Overlay displaying over modal

### ISSUE THREAD

**Issue by DevArenaCN** [wix/react-native-navigation#3097]
### Issue Description

When dispatching a show modal action, the overlay would block the modal. Not sure if this is by design or not, I think the modal should be on top of everything include the overlay.

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions]
Overlay persist over modal.

### Steps to Reproduce / Code Snippets / Screenshots
Call `Navigation.showOverlay({ component: { id: 'componentId1', name: 'overlayComponent', options: { overlay: { interceptTouchOutside: false } } } })` to init the overlay, then call `Navigation.showModal({
  stack: {
    children: [{
      component: {
        name: 'example.ModalScreen',
        passProps: {
          text: 'stack with one child'
        },
      }
    }]
  }
});`

the overlay is still on top of the modal.
---
### Environment
* React Native Navigation version: 2.0.2241
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): iOS and Android
* Device info (Simulator/Device? OS version? Debug/Release?): emulator

**Comment by guyca** [comment]
Hey, Overlay is displayed over modals by design.
Overlay can be used to show persistent UI elements, Alerts etc and there for has to be on top of other elements.

If you wish to hide an Overlay when modals are displayed, you can listen to modal displayed events and hide the overlay accordingly:

```js
Navigation.events().onNavigationCommand((name, params) => {
  if (name === 'showModal') {
    // hide overlay
  }
});
```

**Comment by pie6k** [comment]
Overlay also displays over system dialogs like alerts:

![image](https://user-images.githubusercontent.com/7311462/43096979-f63fd41c-8eba-11e8-9b1e-227d94513e8d.png)

Is it possible to change it somehow?

**Comment by guyca** [comment]
I think https://github.com/wix/react-native-navigation/pull/4241 will address this.
@yogevbd lets prioritise this issue

**Comment by VicFrolov** [comment]
Can't wait for this to be merged :) +1

**Comment by calendee** [comment]
FYI: The suggestion above by @guyca is no longer valid in RNN v2.  The correct way is :

```
const commandListener = Navigation.events().registerCommandListener((name, params) => {
...
});
```

as documented : https://wix.github.io/react-native-navigation/#/docs/events?id=registercommandlistener
