### ISSUE TITLE
screenBackgroundImageName Android Support on V1

### ISSUE THREAD

**Issue by kayzenkayzen** [wix/react-native-navigation#3099]
ios support both screenBackgroundImageName and rootBackgroundImageName
android only support rootBackgroundImageName.

It is planned to give support in Android to screenBackgroundImageName ?

**Comment by filipef101** [comment]
if it isn't supported there are PR for both cases

**Comment by kayzenkayzen** [comment]
@filipef101 i cant find the PR for this property on android.

**Comment by filipef101** [comment]
hmm, I know I use it :) maybe check my repo, I dont have time

**Comment by L-Yeiser** [comment]
This is still not working for me. I am on the latest version of of `react-native-navigation` V1 (1.1.476). I am setting the both `screenBackgroundImageName` and `rootBackgroundImageName` in the top level screen component. I have tried setting the navigator styles as a static property, in the constructor, in `componentDidMount`, and when I push the screen onto the stack. The image is accessible in my `drawable` folder.
