### ISSUE TITLE
Android example does not build?

### ISSUE THREAD

**Issue by liuzhen2008** [wix/react-native-navigation#310]
1.  Pull repo
2. cd into ./example
3. react-native run-android
4. Observe error
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-navigation : Configuration with name 'libraryDebug' not found.

---

OS: Windows

**Comment by DanielZlotin** [comment]
@liuzhen2008 I got it working (partially)... v2.0.0-experimental.115
@guyca is assigned to make it work 100%

**Comment by DanielZlotin** [comment]
A big part of the problems is the fact we had 2 example projects to manage. I decided to delete one of them (example-redux) - I keep it still as a documentation guide, but in the future we will have a nice clean example project. #267

**Comment by DanielZlotin** [comment]
fixed in 	
2.0.0-experimental.116
