### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.bridge.NavigationReactEventEmitter.sendNavigatorEvent(java.lang.String, java.lang.String, com.facebook.react.bridge.WritableMap)' on a null object reference 

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#3100]
Hey there,

here's the stacktrace of the issue:

### Stacktrace

    java.lang.RuntimeException Unable to start activity ComponentInfo{com.acuityscheduling.app.android/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.bridge.NavigationReactEventEmitter.sendNavigatorEvent(java.lang.String, java.lang.String, com.facebook.react.bridge.WritableMap)' on a null object reference 
        ActivityThread.java:2583 android.app.ActivityThread.performLaunchActivity
        ActivityThread.java:2665 android.app.ActivityThread.handleLaunchActivity
        ActivityThread.java:-1 android.app.ActivityThread.-wrap11
        ActivityThread.java:1499 android.app.ActivityThread$H.handleMessage
        Handler.java:111 android.os.Handler.dispatchMessage
        Looper.java:207 android.os.Looper.loop
        ActivityThread.java:5765 android.app.ActivityThread.main
        Method.java:-2 java.lang.reflect.Method.invoke
        ZygoteInit.java:789 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
        ZygoteInit.java:679 com.android.internal.os.ZygoteInit.main

    Caused by: java.lang.NullPointerException Attempt to invoke virtual method 'void com.reactnativenavigation.bridge.NavigationReactEventEmitter.sendNavigatorEvent(java.lang.String, java.lang.String, com.facebook.react.bridge.WritableMap)' on a null object reference 
        EventEmitter.java:67 com.reactnativenavigation.bridge.EventEmitter.sendNavigatorEvent
        EventEmitter.java:44 com.reactnativenavigation.bridge.EventEmitter.sendScreenChangedEventToJsScreen
        EventEmitter.java:18 com.reactnativenavigation.bridge.EventEmitter.sendWillAppearEvent
        ScreenStack.java:459 com.reactnativenavigation.screens.ScreenStack.sendScreenAppearEvent
        ScreenStack.java:444 com.reactnativenavigation.screens.ScreenStack.sendScreenAppearEvent
        ScreenStack.java:437 com.reactnativenavigation.screens.ScreenStack.show
        SingleScreenLayout.java:99 com.reactnativenavigation.layouts.SingleScreenLayout.pushAdditionalScreens
        SingleScreenLayout.java:88 com.reactnativenavigation.layouts.SingleScreenLayout.createStack
        SingleScreenLayout.java:64 com.reactnativenavigation.layouts.SingleScreenLayout.createLayout
        SingleScreenLayout.java:56 com.reactnativenavigation.layouts.SingleScreenLayout.<init>
        LayoutFactory.java:20 com.reactnativenavigation.layouts.LayoutFactory.createSingleScreenLayout
        LayoutFactory.java:15 com.reactnativenavigation.layouts.LayoutFactory.create
        NavigationActivity.java:100 com.reactnativenavigation.controllers.NavigationActivity.createLayout
        NavigationActivity.java:81 com.reactnativenavigation.controllers.NavigationActivity.onCreate
        Activity.java:6309 android.app.Activity.performCreate
        Instrumentation.java:1113 android.app.Instrumentation.callActivityOnCreate
        ActivityThread.java:2530 android.app.ActivityThread.performLaunchActivity
        ActivityThread.java:2665 android.app.ActivityThread.handleLaunchActivity
        ActivityThread.java:-1 android.app.ActivityThread.-wrap11
        ActivityThread.java:1499 android.app.ActivityThread$H.handleMessage
        Handler.java:111 android.os.Handler.dispatchMessage
        Looper.java:207 android.os.Looper.loop
        ActivityThread.java:5765 android.app.ActivityThread.main
        Method.java:-2 java.lang.reflect.Method.invoke
        ZygoteInit.java:789 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
        ZygoteInit.java:679 com.android.internal.os.ZygoteInit.main

---

### Environment
* React Native Navigation version: "1.1.406"
* React Native version: "0.53.3"
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, 6.0 API 23, Lenovo K10a40, Release

**Comment by marcmo** [comment]
observing the exact same thing

**Comment by marcmo** [comment]
so good...you close it just because you don't have time to care for it 👎

**Comment by BenBach** [comment]
@marcmo @SudoPlz Did you find a solution for this? Would really appreciate. Thank you

**Comment by SudoPlz** [comment]
Nope, nada..

**Comment by marcmo** [comment]
@BenBach sort of...for a while I maintained my own fork with [this fix](https://github.com/esrlabs/react-native-navigation/commit/3b3258653935ac12e999bfff2e8d44c46990b84e)
but I just finished migrating to v2. I still got null-pointer problems there but ...at least my hopes are up that my fork [for this](https://github.com/esrlabs/react-native-navigation/tree/v2) is not needed for long...the devs seem to really care for the quality here!
