### ISSUE TITLE
NullPointerException in shared element transition if the screen containing the shared element is scrolled down and then popped

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#3105]
### Issue Description

There is a NullPointerException in shared element transition will the below stack trace:

```java
NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.views.sharedElementTransition.SharedElementTransition.show()' on a null object reference
    at com.reactnativenavigation.views.sharedElementTransition.SharedElements.removeHiddenElements(SharedElements.java:139)
    at com.reactnativenavigation.screens.Screen.removeHiddenSharedElements(Screen.java:330)
    at com.reactnativenavigation.screens.Screen.animateHide(Screen.java:313)
    at com.reactnativenavigation.screens.ScreenStack.hideScreen(ScreenStack.java:238)
    at com.reactnativenavigation.screens.ScreenStack.swapScreens(ScreenStack.java:221)
...
(16 additional frame(s) were not displayed)
```

This happens when the screen containing the initial shared element is scrollable i.e. it contains a FlatList or SectionList or a ScrollView. Scroll the screen down such that the shared element is no longer visible on the screen and then press the back button to go back to the previous screen and observe an abort. I have attached a gif also that shows the abort. In one case the screen is scroll down before popping and the abort is seen and in the other, the screen is not scrolled down before popping and the abort is not seen.

![sharedelementtransitionbug](https://user-images.githubusercontent.com/7475133/39240639-09357c98-48a2-11e8-97a9-a3a5bed4cadc.gif)

I ran the code in the debugger and found that when the below method is called in `SharedElements.java`, the `fromElements` size is 0. For now, I have changed the `if` condition to check for the presence of the `fromElement` also before calling `show` on it.

```java
public void removeHiddenElements() {
        Iterator<String> iterator = toElements.keySet().iterator();
        while (iterator.hasNext()) {
            String key = iterator.next();
            if (!ViewVisibilityChecker.check(toElements.get(key))) {
                iterator.remove();
                fromElements.get(key).show();
            }
        }
    }
```

### Steps to Reproduce / Code Snippets / Screenshots

Described above

---
### Environment
* React Native Navigation version: 1.1.409
* React Native version: 0.52.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by guyca** [comment]
Hey @varungupta85 
V1 isn't maintained anymore as we're transitioning to v2. I'm closing as this won't be addressed by anyone, sorry for the inconvenience.
Perhaps you should reconsider using SET as it's still not implemented in v2 on Android, and it will probably take a few months until we get to it.

**Comment by varungupta85** [comment]
Okay @guyca. Thanks for the info.

**Comment by ashokkumar88** [comment]
@varungupta85 Can u please put the code here how you have modified the `removeHiddenElements()`?
