### ISSUE TITLE
[v2] setStackRoot() doesn't appear to work on iOS

### ISSUE THREAD

**Issue by jeprojects** [wix/react-native-navigation#3107]
### Issue Description

When my app initially loads it will load a single authentication component/screen. Once logged in I am calling setStackRoot to load the main app (with sidebar) in order to create a new stack with the main application.

For some reason it is just loading a blank white screen. I can see in the logs that it is loading the main application though.

```js
Running application navigation.SideMenuScreen ({
    initialProps =     {
        componentId = Component4;
    };
    rootTag = 91;
})

Running application navigation.App ({
    initialProps =     {
        componentId = Component7;
    };
    rootTag = 101;
})
```

### Steps to Reproduce / Code Snippets / Screenshots

Code:

```js
    Navigation.setStackRoot(this.props.componentId, {
      sideMenu: {
        left: {
          component: {
            name: 'navigation.SideMenuScreen'
          }
        },
        center: {
          stack: {
            children: [
              {
                component: {
                  name: 'navigation.App'
                }
              }
            ]
          }
        }
      }
    })

```
---
### Environment
* React Native Navigation version: 2.0.2256
* React Native version: 0.54.4
* Platform(s) (iOS, Android, or both?): iOS (not tested in Android)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
@yogevbd Seems like we don't have e2e for `setStackRoot` - let's cover it with e2e and see if this issue reproduces or not.

**Comment by yogevbd** [comment]
@jeprojects setStackRoot assumes that you already have a stack in your layout. 
If you didn't initialized your root (using `setRoot`) with stack object, it will not work.

**Comment by jeprojects** [comment]
@yogevbd 

I already have setRoot, which initializes the authentication screen, once logged in I use setStackRoot to change the root stack to the main application.

**Comment by yogevbd** [comment]
When calling setRoot on the first time, do you use a stack?

      Navigation.setRoot({
        stack: {
          children: [
            {
              component: {
                name: 'your.auth.screen'
              }
            }
          ]
        }
      });
    });

**Comment by jeprojects** [comment]
@yogevbd I guess that might be it? I am calling this:

```
Navigation.setRoot({
        component: {
          name: 'navigation.Authentication'
        }
      })
```

Is it better to put this single screen into a stack and use setStackRoot, or do the authentication screen as a single component with setRoot, then once authorized use setRoot with a stack for the app?

**Comment by jeprojects** [comment]
@yogevbd Thanks for the info.
