### ISSUE TITLE
v.1 Android App cannot start and its have error for SplashScreen

### ISSUE THREAD

**Issue by sytolk** [wix/react-native-navigation#3113]
How to repeat:
1. close app (multitasking button close RN app)
2. start App and faster press on Android Home button
3. click on App icon again
4. Splash Screen appears for a while and close. I cannot start App again (It's needs to kill it and start again) 

This is only in App log:
`04-26 19:11:19.459 569-2356/? E/SurfaceFlinger: Failed to find layer (Splash Screen de.drivelog.triplog#0) in layer parent (no-parent).`

**Comment by sytolk** [comment]
This is from usage with redux  onStoreUpdate()

**Comment by mckn** [comment]
@sytolk did you find any way to resolve this issue?

**Comment by sytolk** [comment]
No I have updated to RNN v.2

**Comment by jneuendorf** [comment]
> This is from usage with redux onStoreUpdate()

@sytolk How do you know it is caused by redux (from just the native log)?

**Comment by sytolk** [comment]
@jneuendorf I cannot reproduce this issue now (upgrade to RNN v.2 fix it) but maybe if I comment onStoreUpdate() function (from redux integration) I cannot repeat this issue with RNN v.1 too :)
