### ISSUE TITLE
(ANDROID) ReactNative: Unable to display loading message because react activity isn't available

### ISSUE THREAD

**Issue by mckn** [wix/react-native-navigation#3116]
### Issue Description
When loading the react native app in debug I get the following error during boot. And no "green" bar about the bundle being loaded is displayed.

"ReactNative: Unable to display loading message because react activity isn't available"

### Steps to Reproduce / Code Snippets / Screenshots
Install latest version of RN and RNN. Run the application in debug mode.
---
### Environment
* React Native Navigation version: 1.1.450
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by mckn** [comment]
Also, when I'm trying to enable the debugger it tries to open 10.0.2.2 instead of localhost.

**Comment by adrienthiery** [comment]
Is this not a duplicate of https://github.com/wix/react-native-navigation/issues/3044 ?

**Comment by mckn** [comment]
Ah, cool! But we dont use the tab based application mode.

**Comment by haggholm** [comment]
Encountering this, too; and it’s not about tab icons—I’m (also) trying to create a single-page app, not a tab-based one; and there are no earlier error messages in `adb logcat`, about icons or anything else.

**Comment by adrienthiery** [comment]
@mckn or @haggholm, could you create a sample project on github?
I never got that error again but I'm using latest versions of RN and RNN in 2 new projects these days
