### ISSUE TITLE
Setting width on drawer view breaks drawer on fresh install in Android 8.0

### ISSUE THREAD

**Issue by collinglass** [wix/react-native-navigation#3118]
### Issue Description

I am trying to set a specific width on my drawer component. It works in most android devices however, I have 2 Nexus devices running android 8.0 that it does not on fresh install only.

When I run the app after a fresh install on these devices, my drawer component does not slide out, this includes gesture and programmatically after pressing a button.

### Steps to Reproduce / Code Snippets / Screenshots

Delete the app.
Set width property on outer view of Drawer component.
Run app in release mode.
Drawer should not work, If you run the app again without deleting, it works.

```
  // app start
  startApp() {
    const drawer = Platform.OS === 'ios' ? null : {
      left: {
        screen: Sidebar,
        passProps: {},
        disableOpenGesture: false
      }
    }

    Navigation.startSingleScreenApp({
      appStyle: {
        navBarHidden: true,
        keepStyleAcrossPush: false,
        orientation: 'portrait',
        statusBarTextColorScheme: 'light',
        screenBackgroundColor: 'transparent'
      },

      screen: {
        screen: AppHandler,
        overrideBackPress: true,
        navigatorStyle: {
          navBarHidden: true
        },
        navigatorButtons: {}
      },

      drawer,

      passProps: {},

      animationType: 'none'
    });
  }
```

The width is set on the outer view inside Drawer component. As mentioned by @guyca in this comment: https://github.com/wix/react-native-navigation/issues/366#issuecomment-265460319
```
// render method inside Drawer.ts
render() {
  return (
      <View style={[styles.container, { width: 250 }]}>
         // ...
      </View>
   )
}
```

---
### Environment
* React Native Navigation version: 1.1.409
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Nexus 6p, Android 8.0, Release

**Comment by CookieKenku** [comment]
Did you try setting "fixedWidth" prop under the left or right drawer prop instead of style?

**Comment by denieler** [comment]
happens for me on the same devices
