### ISSUE TITLE
Entire screen rendering in top left corner when switching to Tab for first time

### ISSUE THREAD

**Issue by chrismllr** [wix/react-native-navigation#3119]
### Issue Description
When opening new tab for the first time, entire screen renders in top left before expanding to fill the space.

### Steps to Reproduce / Code Snippets / Screenshots
`startTabApp` -> navigate to a different tab
<img width="568" alt="screen shot 2018-04-27 at 2 06 49 pm" src="https://user-images.githubusercontent.com/9942917/39380581-b5732da6-4a24-11e8-957f-75216585048b.png">
<img width="568" alt="screen shot 2018-04-27 at 2 06 54 pm" src="https://user-images.githubusercontent.com/9942917/39380589-b9888a76-4a24-11e8-8b9b-c48823e7f099.png">

### Environment
* React Native Navigation version: `"react-native-navigation": "^1.1.451"`
* React Native version: `"react-native": "0.54.0"`
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): 
Both Debug and Release. Screenshot is Debug.
Simulator and Device (Happens on all i've tested, screenshots are Simulator iPhone X)

**Comment by perrosnk** [comment]
+1 It still happens
