### ISSUE TITLE
passProps not working for bottom tabs on Android

### ISSUE THREAD

**Issue by artald** [wix/react-native-navigation#312]
### Issue Description

When creating `Screens` for the `BottomTabs` which includes `passProps` -  the props are not received in the screen after using `startTabBasedApp`.
Note that this is `passProps` for a specific tab screen and not a single `passProps` object which is passed to all top screens.

### Example code

```javascript
const myTab = {
  label: 'My Screen',
  screen: 'core.MyScreen',
  icon: require('img/tab_icon.png'),
  selectedIcon: require('img/tab_selected_icon.png'),
  title: 'My Screen',
  passProps: {additionalData: [value1: 1, value2: 2]}
};

Navigation.startTabBasedApp(tabs: [myTab]);
```

The expected result is that the screen which registered in the example as `core.MyScreen` would receive the prop `additionalData` along with its content.

In iOS it works, but it required some fixes that we applied recently in `platformSpecificDepracated.ios.js`.

**Comment by artald** [comment]
thanks @guyca!
unfortunately, this doesn't solve the issue.

When we talked I mentioned `TopTabs` (I was probably confused), but what I actually meant is bottom tabs - as mentioned in this issue.

The thing is that there is a global `passProps` for bottom tabs which is then passed to each tab when `passProps` is saved. Now I have a use-case where I want specific `passProps` just for a specific Screen on a tab (see the example in the issue). It's wrong to pass it to all tabs.

You can see what I mean [here](https://github.com/wix/react-native-navigation/blob/master/src/platformSpecific.android.js#L83) and [here](https://github.com/wix/react-native-navigation/blob/master/src/deprecated/platformSpecificDeprecated.android.js#L186).

In iOS we solved it by not replacing the `passProps` of a tab if it already has them.  Something like this:
```javascript
if (!tab.passProps) {
  tab.passProps = params.passProps;
}
```

Now when thinking about it, maybe a better solution would be to merge between the tab-specific props and the "global" tab props? this way if you have both, you won't lose either of them. @DanielZlotin - what do you think?
**Note**: if you think this is a better solution then this needs to be done also on iOS.

**Comment by guyca** [comment]
Props are directly related to a screen. I think it's kingd of wrong that all `BottomTabs` share the same props. 
Anyways, Lets stick to consolidating iOS Android api.. I'll add that check to Android as well

**Comment by DanielZlotin** [comment]
I agree with guy, furthermore the entire concept of "global" pass props
seem weird and wrong to me. I don't quite understand it's use case and even
if it's useful for something I'm sure it can be solved in a different,
easier to reason-about way.

Go ahead and make it work for now, but if we're going to leave that feature
in, it must be well defined, consistent, and make more sense.

Needless to say, way to go on the quick resolution :)

**Comment by artald** [comment]
Thanks @guyca, but fixing it just in `platformSpecificDeprecated.android.js` is not enough. Also need to fix [here](https://github.com/wix/react-native-navigation/blob/master/src/platformSpecific.android.js#L83) where passProps is being saved. I can do it if you want me to.

And as I said @DanielZlotin - I also think it is wrong. I don't know or remember why it was decided this way. However it is not "global" to the whole app, maybe "common" is a better word, common for all the tab root screens. I don't think it would hurt to have both and merge if a tab-screen has specific `passProps`.
