### ISSUE TITLE
[v2] showOverlay does not transition statusBarStyle 

### ISSUE THREAD

**Issue by Dexwell** [wix/react-native-navigation#3122]
### Issue Description

When using `Navigation.showOverlay`, the `statusBarStyle` of the overlay component is not transitioned to.

### Steps to Reproduce / Code Snippets / Screenshots

Call `Navigation.showOverlay`, set the `statusBarStyle` option in the overlay component:

```js
static get options() {
  return {
    statusBarStyle: 'dark'
  };
}
```

Does also not work if `statusBarStyle` is set in the `options` object of `Navigation.showOverlay`.

---
### Environment
* React Native Navigation version: 2.0.2269
* React Native version: 0.55.2
* Platform(s): iOS, Android unknown
* Device info: Simulator, iPhone X, iOS 11

**Comment by yogevbd** [comment]
Actually when presenting overlays there is no transition at all. That component is added as a subview above all. Why don't you use showModal? 

You can try to use `mergeOptions()` with your styles on presented component behind the Overlay.

**Comment by Dexwell** [comment]
I'm not using a modal because the overlay allows me to create a really cool shared element transition. The following does not work:

```js
// On a screen with statusBarStyle light 

Navigation.mergeOptions(this.props.componentId, {
  statusBarStyle: 'dark'
});

Navigation.showOverlay(...);
```

**Comment by yogevbd** [comment]
Pushed fix. This code should work now:

```
Navigation.mergeOptions(this.props.componentId, {
  statusBarStyle: 'dark'
});
```

**Comment by Dexwell** [comment]
Thanks, however is there any way I can tell the statusbar to animate this change?
