### ISSUE TITLE
[v2] dismissModal is not animated

### ISSUE THREAD

**Issue by Dexwell** [wix/react-native-navigation#3123]
### Issue Description

When I open a modal it is animated, but dismissing it is instant without an animation.

### Steps to Reproduce / Code Snippets / Screenshots

Call `Navigation.dismissModal` after `Navigation.showModal`.

---
### Environment
* React Native Navigation version: 2.0.2269
* React Native version: 0.55.2
* Platform(s): iOS, Android unknown
* Device info: Simulator, iPhone X, iOS 11

**Comment by yogevbd** [comment]
@Dexwell Does not reproduce for me. Have you implemented animation options?

**Comment by Dexwell** [comment]
Not as far as I know. This is basically my code:

```js
// App screen
Navigation.setRoot({
  stack: {
    children: [
      {
        component: {
          name: 'screen.Main'
        }
      }
    ]
  }
});

// On Main screen button press
Navigation.showModal({
  component: {
    name: 'screen.Settings'
  }
});

// Settings screen
static get options() {
  return {
    statusBarStyle: 'light'
  };
}

// On Settings screen button press
Navigation.dismissModal(this.props.componentId);

```

**Comment by yogevbd** [comment]
Fixed. thanks!
