### ISSUE TITLE
drawer not always working in android

### ISSUE THREAD

**Issue by nimamoradi** [wix/react-native-navigation#3124]
### Environment
* React Native Navigation version: 5.6.0
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?): android , maybe ios too 
* Device info (Simulator/Device? OS version? Debug/Release?):Release lg g5 and samsung s8 

### Issue Description
i start drawer which work most of the time right but sometimes it make screen black screen but no drawer 

### Steps to Reproduce / Code Snippets / Screenshots

first i make screen like this 
<pre>
export function login() {
    let startAppdata = {
        screen: {
            screen: 'example.Types.loginScreen', // unique ID registered with Navigation.registerScreen
            navigatorStyle: {
                navBarHidden: true,
            }
        },
        appStyle: {
            orientation: 'portrait',
        },
        drawer: { // optional, add this if you want a side menu drawer in your app
            right: { // optional, define if you want a drawer from the right
                screen: 'example.Types.Drawer', // unique ID registered with Navigation.registerScreen
                passProps: {}, // simple serializable object that will pass as props to all top screens (optional)
                percentOfScreenWidth: 0.75,
            },

            style: { // ( iOS only )
                drawerShadow: true, // optional, add this if you want a side menu drawer shadow
                contentOverlayColor: 'rgba(0,0,0,0.25)', // optional, add this if you want a overlay color when drawer is open
            },
            type: 'TheSideBar', // optional, iOS only, types: 'TheSideBar', 'MMDrawer' default: 'MMDrawer'
            animationType: 'parallax', //optional, iOS only, for MMDrawer: 'door', 'parallax', 'slide', 'slide-and-scale'
            // for TheSideBar: 'airbnb', 'facebook', 'luvocracy','wunder-list'
            disableOpenGesture: false // optional, can the drawer be opened with a swipe instead of button
        },
        portraitOnlyMode: true,

    };
    return (startAppdata);
}</pre>
then i start it 
`Navigation.startSingleScreenApp(login());`

drawer render method  is like 
<pre>
 render() {
        return (
            <View style={styles.container}>
.
.
.
   container: {
        width: 75 * vw,
        height: 100 * vh,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff',
        flexDirection: 'column'
    },
</pre>
when ran to issue i got a screenshot https://imgur.com/a8foB9a

**Comment by hugows** [comment]
My drawer also seems to fail sometimes, and seems to be related with "using the menu too soon", before things are properly mounted?

**Comment by nimamoradi** [comment]
probably duplicate as this issue https://github.com/wix/react-native-navigation/issues/1583

**Comment by windydang26** [comment]
same me, sometimes menu on android is not available. i can press on menu but drawer not open, nothing action!

**Comment by augustofontes** [comment]
Same here. When the problem happens, if I click the menu button, I get no feedback. When I try to swipe from left border, I get a black screen for some milliseconds. Ex:

<img src="https://user-images.githubusercontent.com/8450569/44959844-eb0ea600-aecb-11e8-8c1f-f2172a7b7add.gif" width="220" height="391" />
