### ISSUE TITLE
[v2] Modal element isn't clickable on Android

### ISSUE THREAD

**Issue by gabrielvcbessa** [wix/react-native-navigation#3127]
When you open a modal using showModal without any styling, the modal and all it's children can't be clicked on Android. If you add the following style to modal's wrapper view, this issue is fixed.
 
```
{
   flexGrow: 1, 
   backgroundColor: 'white' 
}
```

This should't be the behavior, the modal wrapper should have the needed styles in order to work on both Android and iOS.

### Environment
* React Native Navigation version: 2.0.2269
* React Native version: 0.55.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Debug and Release

**Comment by andresesfm** [comment]
`backgroundColor` is all I needed to make it work in my case

**Comment by guyca** [comment]
[Modal](https://github.com/wix/react-native-navigation/blob/v2/playground/src/screens/ModalScreen.js#L139) works as expected when removing both flex and backgroundColor properties
