### ISSUE TITLE
Update navigator button based on the state of the app (redux or mobx) [QUESTION]

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#313]
Is it possible to dynamically change the navigator button based on the application state held by mobx?

I would also like to toggle its value whenever the user clicks, to show two different values from the mobx (or redux) state.

**Comment by guyca** [comment]
Hey @perrosnk 
You can set button dynamically using `this.props.navigator.setButtons`. The way we see it, `TopBar` buttons are linked to screens. So when your state changed, you can update buttons in `  `componentWillReceiveProps(nextProps)`

I didn't quit understand your second question. If you want the button to reflect that it was clicked, you can change the button's icon in `onNavigatorEvent(event)` where you handle button click. Is this what you meant?
