### ISSUE TITLE
Refresh indicator of FlatList is hidden below NavBar when using largeTitle

### ISSUE THREAD

**Issue by sreuter** [wix/react-native-navigation#3137]
### Issue Description

When using `largeTitle` the refresh indicator of a FlatList shows below the large title. Quite literally, as it's hidden below it.

Looking at Apple Mail it seems like the expected behaviour is that the refresh indicator shows above the large title. Am I missing anything?

### Steps to Reproduce

Use `largeTitle` in a View that hosts a FlatList.

**Comment by tyrong** [comment]
+1

**Comment by e-Luksch** [comment]
are there any news for this Problem?

**Comment by bdrobinson** [comment]
This is also an issue for us. It looks like V2 has better support for the largeTitle in general, but it doesn't look like it lets you control the refresh state.

**Comment by tyrong** [comment]
Could this be a problem with the react native library list api rather than wix navigation? Hopefully upcoming releases of react native will have an option to offset the refresh icon above large titles

**Comment by ptmt** [comment]
See #3538. The only current ready-to-use solution is using react-native-tableview.

**Comment by chrise86** [comment]
Not stale.

**Comment by sallar** [comment]
This is still an issue and not stale as you can see in this screenshot:

<img width="509" alt="Screenshot 2019-12-13 at 0 37 44" src="https://user-images.githubusercontent.com/768052/70754981-4cfdc280-1d41-11ea-864a-e6b4f658dfce.png">
