### ISSUE TITLE
[V2][Android]Creating BottomTabs one at the time is not efficient

### ISSUE THREAD

**Issue by andresesfm** [wix/react-native-navigation#3140]
### Issue Description
As described here: https://github.com/wix/react-native-navigation/issues/3131: 
The root problem is comes from AHBottomNavigation implementation of `adItem` calling `createItems`: https://github.com/aurelhubert/ahbottomnavigation/blob/master/ahbottomnavigation/src/main/java/com/aurelhubert/ahbottomnavigation/AHBottomNavigation.java#L975 discarding the LinearLayout and builds it from scratch again: https://github.com/aurelhubert/ahbottomnavigation/blob/master/ahbottomnavigation/src/main/java/com/aurelhubert/ahbottomnavigation/AHBottomNavigation.java#L274

### Proposed Fix

TBD
---
### Environment
* React Native Navigation version: V2
* React Native version:  0.53.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator / Debug

**Comment by andresesfm** [comment]
@guyca In order to use `addItems` we'd need to combine all the results from `imageLoader.loadIcon(...)` https://github.com/wix/react-native-navigation/blob/v2/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java#L118 Are you open to using a framework like RxJava or Kotlin Corutines ? I just want to open the discussion, I'd be happy to help with the implementation.

**Comment by andresesfm** [comment]
Hello @guyca. This is my proposed implementation: https://github.com/wix/react-native-navigation/pull/3152 Notice that I used Lists instead of varargs. But open to hear your feedback

**Comment by guyca** [comment]
Merged, thanks @andresesfm 👍
