### ISSUE TITLE
Is it possible to create an Android-style tabbed UI using this library?

### ISSUE THREAD

**Issue by jamesqo** [wix/react-native-navigation#3141]
[React-Native-ViewPager](https://github.com/zbtang/React-Native-ViewPager) supports creating a kind of carousel Android-style UI, with icon-less tabs on the top, like this:

![image](https://github.com/zbtang/React-Native-ViewPager/raw/master/imgs/titleIndicator.gif)

Is it easy to create an Android-style tab layout like the above with this library (including little details, like the rectangle that appears below the tab for the current page)? Thanks. (I'm already using this library for iOS-style tabs on the very bottom; I'd prefer not to use 2 different navigation libraries in my app.)

**Comment by guyca** [comment]
Hey there, v2 supports TopTabs on both platforms (though not all style options are implemented as of yet on Android)
I wouldn't call React-Native-ViewPager a navigation library, it's a cross platform view. Don't see a reason not to use it if it suits your needs 👍

**Comment by mths0x5f** [comment]
Is there any updated doc to get this working on latest build of RNN v2?
