### ISSUE TITLE
Documentation additions?

### ISSUE THREAD

**Issue by thewaywest** [wix/react-native-navigation#3142]
### Issue Description

**Installation - Android** document could use some clarification/completion to ease adoption for new(er) users. Like me. I won't make these changes as I have yet to get a Hello React page to come up with react-native-nav :/.

**In MainApplication.java, add the following** I believe should be split:
* ADD THE FOLLOWING should apply to the _include_ line.
* REPLACE THE FOLLOWING should apply to the existing class declaration, implementing instead your class extension of NavigationApplication: _public class MainApplication extends Application implements ReactApplication {_

**Also, add the following** could be inserted into your class declaration as a comment for greater clarity: 
```
// If you are using index.js as your entry point instead of index.ios.js and index.android.js
// (this is the default since React Native 0.49), include the following:
/*
@Override  
public String getJSMainModuleName() {  
    return "index";  
}
*/
```
**Make sure that isDebug and createAdditionalReactPackages methods are implemented.**

Argh. I would like to jump further into react-native than beginner's tutorials. I clearly want the power of this package, but have to research where and how to implement these methods. I imagine inclusion and one- or few-liners are all that is required. Maybe could add them here?

### Steps to Reproduce / Code Snippets / Screenshots

No further detail needed.

---
### Environment
* React Native Navigation version: ^1.1.453
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?): trying to get Android running first (Linux user)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator for now

**Comment by guyca** [comment]
Hey there
I agree the documentation could use more attention and clarification. We're transitioning to v2 so I don't think there much sense in updating the v1 docs now.
