### ISSUE TITLE
[V2][Android] ReactGateway constructor was made private

### ISSUE THREAD

**Issue by andresesfm** [wix/react-native-navigation#3145]
ReatGateway constructor that takes the Host was made private:
https://github.com/wix/react-native-navigation/blob/v2/lib/android/app/src/main/java/com/reactnativenavigation/react/ReactGateway.java#L22

We need that to be accessible so we can create a link with Codepush: https://github.com/Microsoft/react-native-code-push/pull/1239/files#diff-cf1aaec78d431bcee1c397a5faef736dR352

### Proposed Fix
https://github.com/wix/react-native-navigation/pull/3146

**Comment by viotti** [comment]
This also breaks the `index.js` workaround proposed on https://github.com/wix/react-native-navigation/issues/3040#issuecomment-383086179.

**Comment by guyca** [comment]
I'll add a test to ensure this contract doesn't break in the future.

**Comment by andresesfm** [comment]
@guyca I have added the test in this PR: Let me know what you think: https://github.com/wix/react-native-navigation/pull/3153

**Comment by guyca** [comment]
Thanks @andresesfm 👍
