### ISSUE TITLE
[v2]StatusBar color

### ISSUE THREAD

**Issue by heroic** [wix/react-native-navigation#3147]
### Issue Description

I am setting my navbar's background, which works without a problem, however the background color change doesn't affect the statusbar background. Here's my default settings:

  ```
Navigation.setDefaultOptions({
    topBar: {
      background: {
        color: '#0079f3'
      }
    },
    statusBarStyle: 'light'
  })
```

Here's what this generates: [https://imgur.com/a/OHwLbD7](https://imgur.com/a/OHwLbD7)

---
### Environment
* React Native Navigation version: 2.0.2274
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Debug

**Comment by qiepeipei** [comment]
ios statusBar color

**Comment by qiepeipei** [comment]
ios statusBar color  Can not be changed .  react native provided <statusBar> Components  Black and white style .  Other customizations can

**Comment by qiepeipei** [comment]
ios statusBar color Can not be changed . react native provided <statusBar/>  Components Black and white style . Other customizations can

**Comment by qiepeipei** [comment]
@heroic  ios statusBar No background color .  view style default Screen top .  You can customize tabbar settings Background color

**Comment by ahmad2smile** [comment]
I'm getting the same problem. I'm trying to switch from React Navigation and It was setting my statusBar on iOS the same color as my topBar was.

Now I'm setting the color to the topBar but it does not reflect on the statusBar.

**Comment by ahmad2smile** [comment]
What it should be:


![](https://cloud.githubusercontent.com/assets/7475133/21718398/2c55a1ec-d43d-11e6-8932-53c816f52d0d.png)

Here's what it is:

<img width="424" alt="screen shot 2018-05-03 at 3 57 11 pm" src="https://user-images.githubusercontent.com/6108922/39572969-b990ceb4-4eea-11e8-95eb-a3b2e62908d0.png">

**Comment by gabrielvcbessa** [comment]
Same as #3136

**Comment by gabrielvcbessa** [comment]
@guyca Is this a missing feature or are we doing something wrong?

**Comment by guyca** [comment]
@gabrielvcbessa Will need to look into it, could be a missing feature. We're a bit busy migrating the Wix app to v2, so it might be a week (more or less) until we get to this.

**Comment by guyca** [comment]
@ahmad2smile We're working on this project full time and tracking progress in the [board](https://github.com/wix/react-native-navigation/projects/3?fullscreen=true).
This issue has been prioritised, nothing more I can do. You're welcome to look into this and submit a PR

**Comment by gabrielvcbessa** [comment]
It is fixed on v2.0.2275

**Comment by ahmad2smile** [comment]
Works like a charm.

**Comment by ahmad2smile** [comment]
1 thing I had to update. Event [onAppLaunched](https://wix.github.io/react-native-navigation/v2/#/docs/Usage?id=onapplaunchedcallback) isn't available on latest alpha Its switched with `registerAppLaunchedListener`. The Documentation doesn't reflect this I checked the source and It worked.

afaik, Docs are auto generated, If not I can submit a pr for this. @guyca ;)

**Comment by guyca** [comment]
Hey @ahmad2smile 
Only a [small section of the docs](https://wix.github.io/react-native-navigation/v2/#/api/README) is auto generated. You're more then welcome to PR the docs 👍

**Comment by guyca** [comment]
`statusBarBackgroundColor` is implemented for Android in 2.0.2286
Will address `statusBarStyle` soon

**Comment by reddeguzman** [comment]
Hi. Is this resolved? I still can't change `statusBar` color on Android.

**Comment by voidstarfire** [comment]
So how do we change the text color on Android there's no documentation?

**Comment by guyca** [comment]
```js
style: 'dark' | 'light'
```

Same as in iOS

**Comment by voidstarfire** [comment]
Ah so there's no way to set the hex value on Android for custom system menu colors I see.

**Comment by stevenkampen** [comment]
@heroic @guyca This ticket was closed but it's not clear at all what should be working now. Can you please outline what was fixed, and what should now work? People are wasting considerable time with this package because we have NO idea what the state of it is. I have 4 separate issues that are in that same bucket.

**Comment by AugustoAleGon** [comment]
is it possible now to do the opposite? Because once I do this: 

```
Navigation.setDefaultOptions({
  topBar: {
    background: {
      color: '#0079f3'
    }
  },
  statusBarStyle: 'light'
})
```

I want to just change the color of the status bar.

**Comment by lukebrandonfarrell** [comment]
Any update on this?

**Comment by Rendfold** [comment]
So in iOS you can't change statusBar background color?
