### ISSUE TITLE
Blank Tab bar navigation 

### ISSUE THREAD

**Issue by davekedar** [wix/react-native-navigation#3148]
I am getting the blank Tab Navigation bar, I have used the single screen navigation in the same application which is working perfectly. 
![screenshot at may 03 15-42-03](https://user-images.githubusercontent.com/11268363/39571266-90af445a-4ee8-11e8-907b-e5013dd0cfe6.png)

`import { Navigation } from 'react-native-navigation';

const startTabs = () => {
    
        Navigation.startTabBasedApp({
            tabs: [
                {
                    screen: "awesome-places.FindPlaceScreen",
                    label: "Find Place",
                    title: "Find Place",
                    
                },
                {
                    screen: "awesome-places.SharePlaceScreen",
                    label: "Share Place",
                    title: "Share Place",
                    
                }
            ]
        });
};

export default startTabs;`
---
### Environment
React Native Navigation version: 2.0.2274
React Native version: 0.52.2
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iOS 11.3, Both

**Comment by davekedar** [comment]
screen registration file coding 
`import { Navigation } from "react-native-navigation";
import {Provider} from 'react-redux';

import AuthScreen from "./src/screens/Auth/Auth";
import SharePlaceScreen from "./src/screens/SharePlace/SharePlace";
import FindPlaceScreen from "./src/screens/FindPlace/FindPlace";
import configureStore from './src/store/configureStore';

const store = configureStore();

// Register Screens
Navigation.registerComponent("awesome-places.AuthScreen", () => AuthScreen, store, Provider);
Navigation.registerComponent("awesome-places.SharePlaceScreen", () => SharePlaceScreen,store, Provider);
Navigation.registerComponent("awesome-places.FindPlaceScreen", () => FindPlaceScreen,store, Provider);

// Start a App
Navigation.startSingleScreenApp({
  screen: {
    screen: "awesome-places.AuthScreen",
    title: "Login"
  }
});`

**Comment by guyca** [comment]
Seems like you're using v1 api but have v2 installed
https://wix.github.io/react-native-navigation/v2/
