### ISSUE TITLE
react-native-navigation documentation missing

### ISSUE THREAD

**Issue by navneetsharma1988** [wix/react-native-navigation#3149]
### Issue Description

Please check the documentation link on the repository page, it's not working

**Comment by viotti** [comment]
Just checked. It works.

https://wix.github.io/react-native-navigation/#/

**Comment by soundestmammal** [comment]
The documentation link posted above does not work.

**Comment by guyca** [comment]
Seems to be working

**Comment by jr07449** [comment]
This issue is not fixed. Shows "Please Wait" on MacOS and continuously reroutes on Windows machines. 

Thanks for your help.
