### ISSUE TITLE
Application not registered error when running on Android device

### ISSUE THREAD

**Issue by folivi** [wix/react-native-navigation#315]
### Issue Description

 My app runs great on ios on both simulator and device, but when I run react-native-run-android, I get the error saying the app has not been registered.....

### inside index.android.js: 

import App from './src/app';
const app = new App();

### app.js

```js
import { Navigation } from 'react-native-navigation';
import { registerScreens } from '../screens';
import { iconsMap, iconsLoaded } from '../helpers/icons-loader';
import I18n from 'react-native-i18n';

registerScreens(); 
import { Navigation } from 'react-native-navigation';
import { registerScreens } from '../screens';
import { iconsMap, iconsLoaded } from '../helpers/icons-loader';
import I18n from 'react-native-i18n';

registerScreens(); 

export default class App {

  constructor(){

    this.startApp();
    });

  }

  startApp() {
   Navigation.startTabBasedApp({
     app code
  })
}

```

What I'm I missing?

---
### Environment
- [ ] React Native Navigation version: [2.0.0-experimental.113]
- [ ] React Native version: [0.31.0]
- [ ] Platform(s) (iOS, Android, or both?): [Android]
- [ ] Device info (Simulator/Device? OS version? Debug/Release?): [ Debug on device]

**Comment by DanielZlotin** [comment]
This sounds like you didn't call `Navigation.registerComponent`.  I need more info - show me what's inside `registerScreens` function

**Comment by folivi** [comment]
Hi Daniel.
Here it goes:

```

export function registerScreens() {  
  Navigation.registerComponent('up4danz.DealsScreen', () => Deals);
  Navigation.registerComponent('up4danz.EventScreen', () => Events);
  Navigation.registerComponent('up4danz.SideMenu', () => SideMenu);
  Navigation.registerComponent('up4danz.SettingScreen', () => Settings);
  Navigation.registerComponent('up4danz.SearchScreen', () => Search);
  Navigation.registerComponent('up4danz.EventSearchModal', () => EventSearchModal);
}

```

**Comment by DanielZlotin** [comment]
Can you paste the exact error? line? stacktrace?

**Comment by folivi** [comment]
RunApplication
AppRegistry.js:93

__callfunction
MessageQueue.js:204

<unknown>
MessageQueue.js:95

guard
MessageQueue.js:41

**Comment by DanielZlotin** [comment]
Did you manage to run the example project in navigation?

**Comment by folivi** [comment]
Nope.
I get this error

Starting the app (/Users/ffolivi/Library/Android/sdk/platform-tools/adb shell am start -n com.example/.MainActivity...
Starting: Intent { cmp=com.example/.MainActivity }
Error type 3
Error: Activity class {com.example/com.example.MainActivity} does not exist.

Strange thing is this error only shows with the example project.
At least my app launches on my device then fails.

**Comment by guyca** [comment]
@folivi I just did some work on the example project. Can you please pull and try again?

**Comment by folivi** [comment]
I still get 

Error: Activity class {com.example/com.example.MainActivity} does not exist and 

But I could start the app manually on my device after allowing screen overlay for the example app.

The app shows deprecation of leftbutton.

**Comment by guyca** [comment]
@folivi You can safely ignore the left button deprecation warning. It was introduced a while ago for the developers in our team and is probably insignificant to the community. I'll remove the warning soon.

I pushed a fix the should make `react-native run-android` work. Issue was that this command assumes your launch activity is called `MainActivity` and ours was not.

**Comment by folivi** [comment]
Great.
Now the example runs perfectly on my android device.
Now I'm trying to figure out why app doesn't

**Comment by folivi** [comment]
I finally decided to start a project from scratch to have something clean to work with.
Everything works fine on ios but on my Android device I see no error but I get a blank white screen.
The new project can be found git@github.com:folivi/navSample.git

Hope you can help
Cheers

**Comment by guyca** [comment]
@folivi in your sample project, `index.android.js` is not configured properly.
Also don't forgot that on Android BottomTabs require icons

**Comment by folivi** [comment]
Guys, thank you so much for your time
I've just pushed some changes to my sample making it a pretty complete blank app.
It now contains localization for the tab labels and async loading of rn-vector-icons.

Please feel free to review and I'll make it even better and share with the community
Cheers

**Comment by guyca** [comment]
@folivi That's a great initiative! Thanks! actually, @yedidyak published a [bootstrap](https://github.com/wix/react-native-navigation-bootstrap) repo for Navigation yesterday.

I like the idea of adding `react-native-vector-icons` to the bootstrap project. If you're interested, I think you should open an issue in [react-native-navigation-bootstrap](https://github.com/wix/react-native-navigation-bootstrap) and continue this discussion with @DanielZlotin  and @yedidyak over there since I'm not sure what their plans are for the bootstrap project.
