### ISSUE TITLE
[V2] Build errors after installing V2 on fresh react-native project

### ISSUE THREAD

**Issue by jamesguan** [wix/react-native-navigation#3151]
After installing V2 on fresh react-native project, build errors occur.

### Steps to Reproduce
1. Use react-native init to make a native project.

2. Follow the directions to install react-native-navigation V2 laid out here: https://wix.github.io/react-native-navigation/v2/#/docs/Installing.

3. Run `react-native run-ios`

4. See build error.

`In file included from /Users/******/Projects/testrnnv2/node_modules/react-native-navigation/lib/ios/RCTHelpers.m:4:
/Users/******/Projects/testrnnv2/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTFont.h:21:37: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
RCT_EXTERN BOOL RCTHasFontHandlerSet();
                                    ^
                                     void
1 error generated.

** BUILD FAILED **

The following commands produced analyzer issues:
	Analyze Base/RCTModuleMethod.mm normal x86_64

(1 command with analyzer issues)

The following build commands failed:
	CompileC /Users/******/Projects/testrnnv2/ios/build/Build/Intermediates.noindex/ReactNativeNavigation.build/Debug-iphonesimulator/ReactNativeNavigation.build/Objects-normal/x86_64/RCTHelpers.o RCTHelpers.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/testrnnv2.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/testrnnv2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist`

### Environment
* React Native Navigation version: 2.0.2274
* React Native version: 0.55.3
* Platform(s): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Debug
Xcode Version 9.3 (9E145)

**Comment by aspidvip** [comment]
me to

**Comment by yogevbd** [comment]
This is react-native issue. Take a look at https://github.com/wix/react-native-navigation/issues/3019

**Comment by cassioseffrin** [comment]
I created a fresh react native 0.55.4 project and only installed React Native Navigation. The same error message occurs. Then I changed the file in my root folder: 
React/Views/RCTFont.h : line 21
-RCT_EXTERN BOOL RCTHasFontHandlerSet(); //original
+RCT_EXTERN BOOL RCTHasFontHandlerSet(void); //changed

After that, the build have succeed. 
Cassio
