### ISSUE TITLE
[v2] Contributing link is broken

### ISSUE THREAD

**Issue by Naoto-Ida** [wix/react-native-navigation#3155]
I'd like to contribute to V2, but the docs for contributing are broken [here](https://github.com/wix/react-native-navigation/blob/v2/docs/WorkingLocally.md).

**Comment by guyca** [comment]
Hey @Naoto-Ida , Here's the correct link https://wix.github.io/react-native-navigation/v2/#/docs/WorkingLocally 👍

**Comment by Naoto-Ida** [comment]
@guyca Awesome thanks!
