### ISSUE TITLE
[v2] Android doesn't show back button

### ISSUE THREAD

**Issue by gabrielvcbessa** [wix/react-native-navigation#3157]
### Issue Description

Android doesn't show back button when a screen is pushed, but it does happen on iOS. 

### Environment
* React Native Navigation version: 2.0.2274
* React Native version: 0.55.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device and Simulator

**Comment by quy1403** [comment]
+1

**Comment by guyca** [comment]
Resolved in 2.0.2294

**Comment by ArfaouiHamouda** [comment]
still have the same Issue, not solved !
