### ISSUE TITLE
React Native Navigation iOS white navbar

### ISSUE THREAD

**Issue by Luckiest-Developer** [wix/react-native-navigation#3160]
https://stackoverflow.com/questions/50189452/react-native-navigation-ios-white-navbar

### Issue Description

When I start minimal react-native app with react-native-navigation I got this result. Where android navbar got default style and ios got ugly white style with no border at the bottom of the navbar.

### Steps to Reproduce / Code Snippets / Screenshots
```
"dependencies": {
"react": "16.3.1",
"react-native": "~0.55.2",
"react-native-navigation": "^1.1.457"}
```

Nav Bar Picture for android and ios

[https://i.stack.imgur.com/8TjnP.png](https://i.stack.imgur.com/8TjnP.png)

What I want to achive is this default style I saw it in an only course where the trainer did the same is what I did.

[https://i.stack.imgur.com/WWDRa.png](https://i.stack.imgur.com/WWDRa.png)

Start App Code

```
import { Navigation } from 'react-native-navigation'
import AuthScreen from './src/screens/Auth';

// Register Screens
Navigation.registerComponent('rncourse.AuthScreen', () => AuthScreen);

// Start an App
Navigation.startSingleScreenApp({
  screen: {
    screen: 'rncourse.AuthScreen',
    title: 'Login'
  }
});
```

---
### Environment
* React Native Navigation version: ^1.1.457
* React Native version: ~0.55.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iOS 11.3

**Comment by guyca** [comment]
You can style the navBar using [navigatorStyle](https://wix.github.io/react-native-navigation/#/styling-the-navigator)
