### ISSUE TITLE
Make content of labels at BottomTabs change dynamically

### ISSUE THREAD

**Issue by datvtwakumo** [wix/react-native-navigation#3161]
In order to change the content of labels at BottomTabs when locale language is changed (I store the locale in redux), there is only one way I can do is to restart the app, which appears very slow on Android.
Please add a feature that helps to update label at BottomTabs dynamically. For example, navigator.setLabel(I18n.t('myLabel'))
Thank you very much!

* React Native Navigation version: 2.0.2274
* React Native version: 0.54
* Platform(s) iOS, Android

**Comment by guyca** [comment]
duplicate #466
