### ISSUE TITLE
blank white screen, when i build signed apk!

### ISSUE THREAD

**Issue by vijaya06** [wix/react-native-navigation#3163]
Issue Description

i get blank white screen, when i build signed apk. i is not giving any error, successfully build. but when i install apk then it gives blank white screen. i made signed apk through this link https://facebook.github.io/react-native/docs/signed-apk-android.html#generating-a-signing-key.
please help me.

[https://facebook.github.io/react-native/docs/signed-apk-android.html#generating-a-signing-key]

kindly help!
Thanks
---
### Environment
* React Native Navigation version: 0.55.2
* React Native version: 16.3.0
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): device

**Comment by guyca** [comment]
Not sure how we can help here

**Comment by vijaya06** [comment]
anybody have any idea. i tried this long time. please help!

**Comment by a289459798** [comment]
+1
