### ISSUE TITLE
Do icons have to be actual image resources?

### ISSUE THREAD

**Issue by liuzhen2008** [wix/react-native-navigation#317]
I see that in the code, it eventually goes to react-native/Libraries/Image/resolveAssetSource 

But is it still possible to use a module such as react-native-vector-icon or native-base to provide an icon?

It is really inconvenient to generate a new image each time I want to try out a different icon.

The ability to provide an icon like `icon: <icon name="search"/> `would be super cool...

**Comment by guyca** [comment]
Hey @liuzhen2008 It's possible to use `react-native-vector-icon`, there's more info in the [wiki](https://github.com/wix/react-native-navigation/wiki/Third-party-libraries-support#react-native-vector-icons)

**Comment by liuzhen2008** [comment]
Oh thanks a lot!!

**Comment by guyca** [comment]
Yes exactly, In the future we're going improve vector icons support.
