### ISSUE TITLE
[v2] setStackRoot inside modal doesn't animate correctly

### ISSUE THREAD

**Issue by gabrielvcbessa** [wix/react-native-navigation#3178]
When using setStackRoot inside a modal, the screen flashes and the transition breaks, regardless of the option "animated" being true or false. Is this behaving correctly? @guyca 

---
### Environment
* React Native Navigation version: 2.0.2275
* React Native version: 0.55.1
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Devices

**Comment by guyca** [comment]
Hey @gabrielvcbessa 
If the animation is jerky - then obviously something isn't behaving as expected. Could you please PR a failing unit test?
Are you positive `setStackRoot` does not animate correctly on both platforms?

**Comment by gabrielvcbessa** [comment]
@guyca Currently I'm having a lot of issues when trying to run our app on android, we are fixing it and as soon as possible i'll upload the video showing the problem on this platform. 

But I manage to record it on iOS, I call it on the "Avisar Aplicação" button:
![https://gfycat.com/ViciousLittleArmyworm]

**Comment by gabrielvcbessa** [comment]
@guyca I was testing here and seems that it breaks only on 11.3.1
