### ISSUE TITLE
[v2] font Family for back button title in ios 

### ISSUE THREAD

**Issue by omar-dev** [wix/react-native-navigation#3179]
### Issue Description

Hello, thanks for the good work.
Back button font family not implemented yet  
### Steps to Reproduce / Code Snippets / Screenshots

Not implemented yet

---
### Environment
* React Native Navigation version: 2.0.2279
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device

**Comment by steventnorris** [comment]
Was this every actually resolved in v2 or v3 or just marked stale and forgotten?
