### ISSUE TITLE
TestID doesn

### ISSUE THREAD

**Issue by abdulkhaliquem9** [wix/react-native-navigation#3181]
###Passing testID through props to the navigatorButtons doesn't work on android emulator, I haven't tested it on IOS simluator.

`componentDidMount() {
    this.props.navigator.setButtons({
      leftButtons: [{ id: 'close', icon: iconsMap['close'], testID:'closeButton' }],
      rightButtons: [{ id: 'save', icon: iconsMap['save'], testID:''saveButton'}],
    });
  }`

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version:"react-native-navigation": "latest",
* React Native version: "0.51.1",
* Platform(s) ( Android): Nexus_5X_API_27
*Operating System: Linux mint.

**Comment by guyca** [comment]
@abdulkhaliquem9 testId is not implemented for buttons in v1. I'm closing as this is implemented in v2
