### ISSUE TITLE
Pushed screen does not display until you navigate to and then back from a different BottomTab

### ISSUE THREAD

**Issue by EliSadaka** [wix/react-native-navigation#3186]
### Issue Description

In my app I use a native SDK to open up a camera view to take a photo, save it, and return the image path to the React Native app where it is then passed to another screen to be processed. However, on iOS once the native module passes the image path back to the React Native app the next screen does not display automatically, it simply returns to the screen that the native module was called from. The only way to get it to display the next screen after returning from the native module is to navigate to a different BottomTab and then navigate back to the BottomTab that the native module is called from, after which the next screen displays immediately with the image path in its props. This issue does not happen on Android and it only happens on iOS in this specific usage. Does anyone know why this might be happening?

### Steps to Reproduce / Code Snippets / Screenshots

Here is the relevant code section:

```
takePhoto() {
	PESDK.showCamera() //a native module that returns an image path
	.then(imagePath => {
		this.props.navigator.push({
			screen: "NewPostScreen",
			title: "New Post",
			passProps: { imagePath: imagePath },
			overrideBackPress: true
		});
	})
	.catch(error => console.log(error.message));
}
```

Once the `PESDK.showCamera()` module returns, the following is printed in the debug console showing that the screen was pushed even though it doesn't appear until you switch to and then back from a different BottomTab:

```
Running application NewPostScreen ({
    initialProps =     {
        commandType = Push;
        imagePath = "/var/mobile/Containers/Data/Application/1C272FA6-8E17-4A75-A078-A20D559ABCD4/Documents/taken_photo.jpg";
        isPreview = 0;
        navigatorEventID = "screenInstanceID9_events";
        navigatorID = "controllerID3_nav0";
        screenInstanceID = screenInstanceID9;
        timestamp = 1525886211773;
    };
    rootTag = 551;
})
infoLog.js:17 Running application "NewPostScreen" with appParams: {"rootTag":551,"initialProps":{"navigatorID":"controllerID3_nav0","commandType":"Push","screenInstanceID":"screenInstanceID9","imagePath":"/var/mobile/Containers/Data/Application/1C272FA6-8E17-4A75-A078-A20D559ABCD4/Documents/taken_photo.jpg","isPreview":false,"navigatorEventID":"screenInstanceID9_events","timestamp":1525886211773}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
```

---
### Environment
* React Native Navigation version: 1.1.457
* React Native version: 0.53.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS Simulator and iPhone SE device / iOS 11.2.6 / Debug

**Comment by pribeh** [comment]
Anybody? We can't seem to get past this.

**Comment by guyca** [comment]
Have you tried adding a delay before pushing `NewPostScreen` screen?

**Comment by pribeh** [comment]
@guyca thanks! We haven't tried that yet. We'll give that a shot and report back.

**Comment by guyca** [comment]
I'm closing as this appears to be synchronisation issue between controllers in v1 which is deprecated.

**Comment by guyca** [comment]
@pribeh This issue shouldn't exist in v2. I'd like to add e2e tests for this use case as well at some point as well.

**Comment by danielgindi** [comment]
@guyca That's a great idea, given that this issue happens in every platform at some point. In native iOS you can get warnings from the system about mismatching push/pop when timing is incorrect, and you can have other sync issues.
So regardless of v2 design - this is a crucial use case to test for :-)
