### ISSUE TITLE
how can i go back tab screen.

### ISSUE THREAD

**Issue by SlZeroth** [wix/react-native-navigation#3187]
my nav stack is like this 
tab nav -> screen2 -> screen3

and i want to go back to "tab nav" when back button is clicked in screen2 or screen3
but I know back button event not support in IOS 

give me the solution

---
Environment
React Native Navigation version: the latest version
React Native version: the latest version
Platform(s) (iOS, Android, or both?): Android
Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
You can either call `popToRoot` or `dismissAllModals` depending on how your hierarchy is constructed.
