### ISSUE TITLE
snackbar doesnt show on modal screen..

### ISSUE THREAD

**Issue by MeKarina** [wix/react-native-navigation#3188]
snackbar doesnt show on modal screen... 
it seems it doesnt support, though..
https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/layouts/ModalScreenLayout.java

it only support on pushable screen or single screen layout..
https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java

would be great if it also supported on modal screen as snack bar is very neat to show alert on android…

**Comment by guyca** [comment]
Hey there, This is a limitation of v1 which can't be addressed.
