### ISSUE TITLE
The callback setStackRoot() exist in module RNNBridgeModule, can only register one callback

### ISSUE THREAD

**Issue by ahmad2smile** [wix/react-native-navigation#3189]
### Issue Description

I'm trying to navigate to a screen by using `setStackRoot`. I've also tried using `popToRoot` but I get the following error in both cases:

```
The callback setStackRoot() exists in module RNNBridgeModule, but only one callback may be registered to a function in a native module.
```
or in case of `popToRoot`
```
The callback popToRoot() exists in module RNNBridgeModule, but only one callback may be registered to a function in a native module.
```

I'm guessing this error is related to some problem in Native code as mentioned here, [RN Docs](http://facebook.github.io/react-native/docs/native-modules-android.html#callbacks)

#### My Setup:

I register components with this wrapper https://github.com/wix/react-native-navigation/issues/1642#issuecomment-361006675

My `setRoot` looks like this.

```
Navigation.setRoot({
  stack: {
	children: [
		{
			component: {
				name: "DashboardScreen"
			}
		},
		{
			component: {
				name: "LoginScreen"
			}
		}
	],
	options: {
		topBar: {
			visible: false
		}
	}
}
})
```

#### Screenshot:

<img src="https://user-images.githubusercontent.com/6108922/39867621-2fb7cff0-546f-11e8-8171-07233e53275b.png" width="200px" height="350px">

### Steps to Reproduce / Code Snippets / Screenshots

Just run alpha `v2.0.2283`

---
### Environment
* React Native Navigation version: 2.0.2283
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator 6 OS 11.3 Debug

**Comment by pmachowski** [comment]
You probably did not set the `componentId` as first argument for the call.

**Comment by ahmad2smile** [comment]
I did pass the component ID and It does move to the next screen but then exception happens.

**Comment by maestrolsj** [comment]
same issue with me
