### ISSUE TITLE
Multiple SharedElementTransition issue

### ISSUE THREAD

**Issue by riteshmalav** [wix/react-native-navigation#3191]
I was testing SharedElementTransition on android and in my use case there are three pages where first page contains <FlatList/> from which shared element is a list icon that becomes the header of the second page, second page also contains <FlatList/> from which shared element is a list icon that become the header of the third page, and third page container just textual elements. now the page navigation looks fine when i navigate from first page to second and second page to third. but when i navigation back from third page to second it works fine but while navigating from second page to first it replaces the shared element of first page with the shared element of second page. so the animation on navigation back from second page to first page looks a little different.

**Comment by guyca** [comment]
Hey there, SharedElementTransition was an experimental feature in v1 and is still not implemented in v2. We're not maintaining this feature for v1, it will probably be added at some point to v2.
