### ISSUE TITLE
custom right button problems with positioning on Android.

### ISSUE THREAD

**Issue by YYH123123** [wix/react-native-navigation#3194]
### Issue Description

I am designing my own custom right button which design is like this(What I want to do):
![default](https://user-images.githubusercontent.com/33000614/39935158-129767e0-5583-11e8-8458-95e345940570.png)

But this is what the result is when I am trying to implement it:
![default](https://user-images.githubusercontent.com/33000614/39935243-507ec710-5583-11e8-82b2-27ce6539120f.png)

I already follow [this](https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=adding-buttons-to-the-navigator) and refered to other issues here.
I succeed in making gap between the button and the right side on IOS but I can't make it on Android.
I wanna make a padding between the button and right side... Please help me and I really appreciate it.

This is code I made:
`Navigation.startTabBasedApp({
    tabs: [
      {
        title: 'Screen One',
        screen: 'connecting.VoiceTab', // unique ID registered with Navigation.registerScreen
        icon: require('../assets/bottom_tab_menu1.png'), // local image asset for the tab icon unselected state (optional on iOS)
        selectedIcon: require('../assets/bottom_tab_menu1_on.png'), // local image asset for the tab icon selected state (optional, iOS only. On Android, Use `tabBarSelectedButtonColor` instead)
        iconInsets: defineIconInsets,
        title: 'Connecting',
        navigatorStyle: defaultNavStyle,
        navigatorButtons: {
          rightButtons: [
            {
              id: 'custom-button',
              component: 'connecting.PaymentButton',
              passProps: {
                text: 'Hi!',
              },
            }
          ]
        }
      },`

`Import React, { Component } from 'react';

import {
  Image,
  TouchableOpacity,
  StyleSheet,
  View,
  Text
} from 'react-native';

const styles = StyleSheet.create({
  button: {
    width: 30,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default PaymentButton = ({ text }) =>
<TouchableOpacity
      style={[styles.button]}
      onPress={() => console.log('pressed me!')}>
      <Image style={styles.button} source={require('../../assets/big_crown.png')} />
    </TouchableOpacity>`

Please help me solve the problem...:(

---
### Environment
* React Native Navigation version: latest
* React Native version: latest
* Platform(s) (iOS, Android, or both?): Android

**Comment by windydang26** [comment]
same me. why close?

**Comment by windydang26** [comment]
width for custom right button too small cause error

**Comment by LeVadim** [comment]
same issue here

**Comment by kanso-michael** [comment]
Got fix for this, ensure that you set a width on the container of the component you are passing in. I bumped it from 30-50 and all is fine.
