### ISSUE TITLE
[v2] isScreenVisible feature

### ISSUE THREAD

**Issue by yusufyildirim** [wix/react-native-navigation#3199]
### Issue Description
Hi, I just started to use v2 version and I wanna thank you guys, I saw great improvements here. We were discussed these core improvements a couple months ago there: https://github.com/wix/react-native-navigation/issues/1376 and as I saw, we can pass containerId by ourselves and this was what I want.

Now, I have a case which I wanna share with you. Imagine we have LoadingModal (or Overlay), here is how I show this overlay: 

```js
Navigation.showOverlay({
      component: {
        id: 'LoadingOverlay',
        name: 'LoadingOverlay',
      },
});
```

This piece of code triggers every time I sent an api request but **the problem is, id must be unique.** This is cool, but I don't want to use id uniqueIdProvider, I just wanna know there is any shown (currently in the stack, don't have to current screen or on top of the screen) screen which it's id equals 'LoadingOverlay'. So, If I know there is a screen in stack with 'LoadingOverlay' id, I can stop another showOverlay actions with same id and prevent errors.

Actually, I read your typescript code and found Store class and I created this `isScreenVisible` function in my way. Here is my code:

```js
Navigation.isScreenVisible = componentId => Navigation.store.getRefForId(componentId) != undefined;
```

If there is any ref with this id, it means this screen currently in the stack. This is cool, working good but I wanna know is this a good approach? I don't know the whole lifecycle and how events are triggering etc. So I hope you guys can help me about this situation. This is a common scenario btw, I hope we can figure it out together 💯 

@DanielZlotin @guyca 

---
### Environment
* React Native Navigation version: v2@alpha
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by guyca** [comment]
Hey @yusufyildirim 
Detecting when a screen appears and disappears is possible using `Navigation.events()` api.

Register for component appear event:
```js
Navigation.events().registerComponentDidAppearListener((componentId, componentName) => {
  console.log(`${componentName} appeared`);      
})
```

Register for component disappear event:
```js
Navigation.events().registerComponentDidDisappearListener((componentId, componentName) => {
  console.log(`${componentName} disappeared`);
})
```
