### ISSUE TITLE
Re-render on default back button press

### ISSUE THREAD

**Issue by madvas** [wix/react-native-navigation#32]
When default back button is pressed, no re-render of screen I returned to, or `setOnNavigatorEvent` is fired. How can I get some callback/re-render after pressing this?

![snap 2016-05-17 at 17 43 13 285x500](https://cloud.githubusercontent.com/assets/3857155/15328964/485f80cc-1c57-11e6-9619-6b8da40b005e.png)

**Comment by dg92** [comment]
@madvas  any success ?

**Comment by madvas** [comment]
nope, no response

**Comment by pqkluan** [comment]
This problem could be solved by either sync the data using Redux/MobX or listen to [visibility events](https://wix.github.io/react-native-navigation/#/screen-api?id=listen-visibility-events-in-onnavigatorevent-handler)
