### ISSUE TITLE
SelectedIcon configuration for tabs does not work on android

### ISSUE THREAD

**Issue by liuzhen2008** [wix/react-native-navigation#320]
SelectedIcon configuration for tabs does not work on android

1. build example
2. Observe the selected tab icon - two different icons were provided. one.png and one_selected.png. But it doesn't really change.

    "react-native": "0.31.0",
    "react": "15.2.1",
    "react-native-navigation": "2.0.0-experimental.116"

**Comment by guyca** [comment]
SelectedIcon is not supported on Android. You can use `tabBarSelectedButtonColor` in `navigatorStyle`

**Comment by liuzhen2008** [comment]
@guyca Is there no plan to support it in the future?

**Comment by guyca** [comment]
@liuzhen2008 I don't think so. It doesn't follow Android's design guidelines.
We can reopen the issue to keep it visible, and if there's demand from the community I assume we can add this feature in one of the upcoming releases.

**Comment by liuzhen2008** [comment]
@guyca  Ahh, I see.

I have another question for tab bars.

Is there a way to keep the tab label on the tab bar regardless whether it is selected or not? I didn't see any configuration doc on it. But it is shown like that in the demo readme.md but not in ./example for android.

**Comment by guyca** [comment]
Yes, You need to define it with `forceTitlesDisplay` property in `appStyle` as follows:

```js
Navigation.startTabBasedApp({
  tabs: [
    ...
  ],
  appStyle: {
    forceTitlesDisplay: true
  }
});
```

Just note, that this api is not final and might change soon (That's why we didn't add it to the docs).
