### ISSUE TITLE
[v2][regression] StackNavigator missing an option for tabBarVisible 

### ISSUE THREAD

**Issue by Perelan** [wix/react-native-navigation#3200]
### Issue Description
Missing an option to hide the tabBar for a StackNavigator.

**Comment by Perelan** [comment]
Hey @guyca! On iOS, there used to be a field for tabBarVisible in navigationOptions for StackNavigator to actually hide the BottomTabs for a specific screen. I, however, cannot find the field in the new version of the navigator - is it slip up, or are you supposed to do it in another way?

**Comment by guyca** [comment]
Available options can be found [here](https://wix.github.io/react-native-navigation/v2/#/docs/styling?id=options-object-format)

I think you're looking for `bottomTabs: {visible: false}`
