### ISSUE TITLE
Is it possible to customise action of bottom tab bar item?

### ISSUE THREAD

**Issue by bdavid68** [wix/react-native-navigation#3204]
### Issue Description

For now, we attach screens to each tab bar items so clicking on tab bar item just switches screens.
But I want to open a modal dialog(not switching to a screen) by tapping tab bar icon.
Is this possible?

---
### Environment
* React Native Navigation version: 1.1.458
* React Native version: 0.53.3
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device, Debug/Release

**Comment by guyca** [comment]
This will be implemented in v2, tracking in #2766
