### ISSUE TITLE
Push new screen not work if i not have warnings

### ISSUE THREAD

**Issue by AlanSaracho** [wix/react-native-navigation#3205]
### Push new screen not work if i not have warnings

Hi! I try to push a new screen from tabs app, and works fine. But, if i remove all react warnings the navigator.push() broke the app. Basically, the new screen is not pushed, and the current screen is overlaped by other tabs. 

EDIT: i try compile a release app. But the error keep going  

---
### Environment
* React Native Navigation version: 1.1.458
* React Native version: 0.51.0 / 0.54.2 (try to update)
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug/release Android 8.0 simulator && Debug/release Android 6.0 Device

i track the error, and the com.reactnativenavigation.screens.StackScreen.pushScreenToVisibleStack() not work property. The onDisplay function is never called.
`    private void pushScreenToVisibleStack(LayoutParams layoutParams,
                                          final Screen nextScreen,
                                          final Screen previousScreen,
                                          @Nullable final Promise onPushComplete,
                                          @Nullable final Screen.OnDisplayListener onDisplay) {
        nextScreen.setVisibility(View.INVISIBLE);
        addScreen(nextScreen, layoutParams);
        NavigationApplication.instance.getEventEmitter().sendWillDisappearEvent(previousScreen.getScreenParams(), NavigationType.Push);
        nextScreen.setOnDisplayListener(new Screen.OnDisplayListener() {
            @Override
            public void onDisplay() {
                nextScreen.show(nextScreen.screenParams.animateScreenTransitions, new Runnable() {
                    @Override
                    public void run() {
                        if (onDisplay != null) onDisplay.onDisplay();
                        if (onPushComplete != null) onPushComplete.resolve(null);
                        NavigationApplication.instance.getEventEmitter().sendDidDisappearEvent(previousScreen.getScreenParams(), NavigationType.Push);
                        parent.removeView(previousScreen);
                    }
                }, NavigationType.Push);
            }
        });
    }
`

I have a tab bassed app and a warning alert.
![a](https://user-images.githubusercontent.com/8611194/40011986-bd39fb1a-577f-11e8-9c62-b895d7a6579e.png)

Click works fine.
![b](https://user-images.githubusercontent.com/8611194/40012020-d69c2f1a-577f-11e8-9311-249e6bcdc3bd.png)

Remove Warnings and clicks
![c](https://user-images.githubusercontent.com/8611194/40012034-e0ea22b0-577f-11e8-8e02-ddaae7b9f2fd.png)

**Comment by guyca** [comment]
Hey @AlanSaracho, I'm closing the issue as v1 is maintained anymore. v2 will be merged in the upcoming weeks to master.
