### ISSUE TITLE
React Native Navigation Blank Screen After Install

### ISSUE THREAD

**Issue by byteskw** [wix/react-native-navigation#3207]
### Issue Description
so after i'm install new react native version in react-native init test
and i'm install react native navigation with npm install --save react-native-navigation@latest or via yarn 
and then i'm runing the application
and my application show blank screen
for example my problem : https://imgur.com/a/ED0R6ad
i'm use Navigation.startSingleScreenApp

and why my previous application, like my new application its blank screen to

so can help my problem? 

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by Shubham-Sinha** [comment]
I was able to implement this. I'm sharing a [repo](https://github.com/Shubham-Sinha/rn-api27-native-navigation) for the same

**Comment by byteskw** [comment]
cant run with your repo,
i dont know why 

still blank screen

can u help me?

**Comment by Shubham-Sinha** [comment]
Open android studio and see if there's any error in gradle build. You can also open logcat to check if there's any error causing white screen. It's working fine for me

**Comment by Igum92** [comment]
Reproduced with RN 0.48.4 and fixed with updating to 0.49.5
