### ISSUE TITLE
[v2] bottomTabs visible false is not working

### ISSUE THREAD

**Issue by swingywc** [wix/react-native-navigation#3209]
## Steps to Reproduce / Code Snippets / Screenshots
I have set `bottomTabs: { visible: false }` before `setRoot` and `registerScreens` as following:

```js
    Navigation.events().registerAppLaunchedListener(async () => {

      await Navigation.setDefaultOptions({
        popGesture: false,
        bottomTabs: {
          visible: false,
          drawBehind: false,
          translucent: false,
          hideShadow: true,
          backgroundColor: '#0f0'
        }
      });

      await registerScreens();

      Navigation.setRoot({
        bottomTabs: {
          children: [
            {
              component: {
                name: 'screens.Home',
                passProps: {
                  text: 'This is tab 1'
                }
              }
            },
            {
              component: {
                name: 'screens.Album',
                passProps: {
                  text: 'This is tab 2'
                }
              }
            }
          ]
        }
      });
    });
```

My HomeScreen component didn't put any extra config as following:

    import React, { Component } from 'react';
    import { View } from 'react-native';

    export default class HomeScreen extends Component {
      constructor(props) {
        super(props);
      }

      render() {
        return (
          <View style={{flex: 1, backgroundColor: '#f00'}}>
          </View>
        );
      }
    }

The result is like below screenshots:
![2018-05-15 7 00 08](https://user-images.githubusercontent.com/9659080/40052990-3aa55886-5872-11e8-9ec2-77dedeb0f4cf.png)

The tabBar didn't hide completely, with some space left at the bottom (green area).

**NOTE: This should be a BUG, I have tried all solution provided inside RNN v2 guide.** 

Someone please help!
## Environment
React Native Navigation version: 2.0.2286
React Native version: 0.52.0
Platform(s) (iOS, Android, or both?): IOS
Device info (Simulator/Device? OS version? Debug/Release?): iPhone X simulator, iPhone 6, in Debug mode

**Comment by yusufyildirim** [comment]
Nope it's  not a bug you must set translucent true too @swingywc

**Comment by swingywc** [comment]
hi @yusufyildirim , thanks for your response. However, setting translucent to true didn't make any changes. The initial page still still show the green area but it will disappear when I go to another tab.

**Comment by swingywc** [comment]
@yusufyildirim @yershalom 
What I want to achieve is the following: 
1. Make the middle tab icons bigger. (like the design in this issue: https://github.com/wix/react-native-navigation/issues/2126)
2. Allow this middle tab button call a custom function to check user login status, if user is not login yet, will pop-up a login modal. Otherwise, navigate to the tab component.

My current solution is to hide the bottomTabs and show a customize bottomTabs component in every page. 

Do you have any solution to achieve the above target? Appreciate for your kindly help.

**Comment by yusufyildirim** [comment]
@swingywc Yea I need something like that too but library is not flexible about the bottomTabs but as I understand, they have plans about that. Are you guys gonna create a flexible api like topBar @guyca?

**Comment by maestrolsj** [comment]
I want to hide the bottomTabs completely but impossible

**Comment by yogevbd** [comment]
Try this:
```
await Navigation.setDefaultOptions({
        bottomTabs: {
          visible: false,
          drawBehind: true
        }
      });
```

**Comment by terreb** [comment]
@yogevbd, `Navigation.mergeOptions( 'bottomTabs', { bottomTabs: { visible: false, translucent: true, drawBehind: true } } )` doesn't work

**Comment by terreb** [comment]
@yogevbd, doing so like you suggested in `Navigation.setDefaultOptions` doesn't work neither

**Comment by mtzfactory** [comment]
Yeah, I have the same problem...
