### ISSUE TITLE
how to make an 'android toast' like overlay ?

### ISSUE THREAD

**Issue by midgit** [wix/react-native-navigation#321]
How can i show an overlay like 'android toast', with full screen transparent background, and a custom foreground layer ? 
or like full screen loading ?

**Comment by guyca** [comment]
@midgit On iOS you can show LightBox as described in the [wiki](https://github.com/wix/react-native-navigation/wiki/Screen-API). LightBox isn't supported on Android though, @DanielZlotin should we support it?

But I would just save a flag in the state indicating if data is loading or not, and when the flag is `true` I would just return a full screen `ActivityIndicator` in `render()`. When loading is done, render your screen as usual.

**Comment by midgit** [comment]
@guyca It's ugly when many screens all need TOAST, but unfortunately it is the only one way as you  referred... thank you

**Comment by guyca** [comment]
@midgit If you have an idea for improvement let us know. You can create a unified loading view and use it across all relevant screen. Usually you won't have a lot of screen where you fetch data each time you open the screen - that's bad UX.

**Comment by midgit** [comment]
@guyca I have implemented a overlay(now only ios), much like LightBox, but without animation(do it in JS). I could put loading on it, or more complicated ui. 
But now, i encounter an issue, which also in LightBox. If 'TouchOpacity' or 'Text' with onPress() in the LightBox screen, it cannot invoke the touch callbacks.
Wish for your help. Thank you

**Comment by midgit** [comment]
@guyca I am sorry to disturb you. I find that touch callbacks can be invoked in Example. I will dive in my issue myself...

**Comment by guyca** [comment]
@midgit All is good, you're not disturbing 👍
