### ISSUE TITLE
[Android]: Tab Bar color not working

### ISSUE THREAD

**Issue by luskin** [wix/react-native-navigation#3212]
### Issue Description

Styling the tab bar does not work on Android even though the docs state these should work cross platform, which leads me to believe there is something missing in my code.

### Steps to Reproduce / Code Snippets / Screenshots

```
export const Colors = {
  Yellow: '#f7ca02',
  ButtonGrey: '#cdcdcd',
  White: '#ffffff',
  Black: '#000000',
  Blue: '#3755b0'
}
```

```
  Navigation.startTabBasedApp({
    animationType: 'fade',
    tabs: [
      {
        screen: Screens.Dispatches,
        icon: Icons.TabBar.Dispatches,
        label: 'Dispatches',
        title: 'Dispatches'
      },
      {
        screen: Screens.History,
        icon: Icons.TabBar.History,
        label: 'History',
        title: 'History'
      },
      {
        screen: Screens.Account,
        icon: Icons.TabBar.Account,
        label: 'Account',
        title: 'Account'
      }
    ],
    tabsStyle: {
      tabBarLabelColor: Colors.White,
      tabBarButtonColor: Colors.White,
      tabBarSelectedLabelColor: Colors.Yellow,
      tabBarSelectedButtonColor: Colors.Yellow,
      tabBarBackgroundColor: Colors.Black
    }
  })
```
iOS:
![img_1337](https://user-images.githubusercontent.com/5702322/40081513-1566ac52-5843-11e8-87a0-618ce49188a2.PNG)

Android:
![screenshot_20180515-131948](https://user-images.githubusercontent.com/5702322/40081527-1d2f812a-5843-11e8-9b16-8d94ad2b6b7e.jpg)

---
### Environment
* React Native Navigation version: 1.1.458
* React Native version: 0.55
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X vs Samsung Galaxy S7 Edge (both real devices)

**Comment by guyca** [comment]
Due to historical reasons, `BottomTabs` style on Android should be declared in `appStyle`
https://wix.github.io/react-native-navigation/#/styling-the-tab-bar

**Comment by chengguo0719** [comment]
> Due to historical reasons, `BottomTabs` style on Android should be declared in `appStyle`
> https://wix.github.io/react-native-navigation/#/styling-the-tab-bar

Thank you very much. it is working in android correctly
