### ISSUE TITLE
[v2] bottomTab icons are freaked out

### ISSUE THREAD

**Issue by yusufyildirim** [wix/react-native-navigation#3213]
### Issue Description

I was just testing the bottomTabs and when I set iconInsets option to bottomTab, it happened. It's working fine without iconInsets btw.

![2018-05-15 23 08 24](https://user-images.githubusercontent.com/22980987/40083008-84a2b680-589b-11e8-90b3-518f44be0f67.gif)

### Steps to Reproduce / Code Snippets / Screenshots
Just set iconInsets option.
For Example: 
```
bottomTab: {
  iconInsets: { top: 6, left: 0, bottom: 6, right: 0 },
}
```
---
### Environment
* React Native Navigation version: v2@alpha
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS (Didn't test android)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / iOS 11.3 / Debug

**Comment by yusufkinatas** [comment]
Using `iconInsets: { top: 5, bottom: -5,  },` instead of `iconInsets: { top: 10, bottom: 0,  },` fixed the problem for me.
