### ISSUE TITLE
Error: Drawer side menu is overlaid by main menu..

### ISSUE THREAD

**Issue by kevinchensd** [wix/react-native-navigation#3214]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]
The side menu (drawer) is overlaid by main page, but I wanted is side menu should be on top of the main page. please help.

![image](https://user-images.githubusercontent.com/26289472/40099951-cce4da26-5914-11e8-8b86-97db3d231d12.png)

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): simulator iphone 6 plus

**Comment by guyca** [comment]
This is the behaviour of the SideMenu. I believe you can tweak it a bit using
`type` and `animationType`
https://wix.github.io/react-native-navigation/#/top-level-api?id=startsinglescreenappparams

**Comment by karlmosenbacher** [comment]
@guyca can you style the sidemenu the same in version 2?

**Comment by maestrolsj** [comment]
I can't use   fixedWidth  in version2

**Comment by anonrig** [comment]
Does the type of sidemenu applies to V2 also @guyca ?

**Comment by acollazomayer** [comment]
Any news with this?

**Comment by rishabhSmartdata** [comment]
![Screenshot 2019-04-15 at 11 45 45 AM](https://user-images.githubusercontent.com/46954033/56112173-dde48a00-5f77-11e9-888a-2008bdc906ab.png)
![Screenshot 2019-04-15 at 11 45 16 AM](https://user-images.githubusercontent.com/46954033/56112174-de7d2080-5f77-11e9-9b00-efae192bc58d.png)
@guyca I am facing this issue on ios with React-native-navigation[V2]
What should i do

"navigation.js"
Navigation.setRoot({
    
  root: {
    sideMenu: {
      left: {
       
        component: {
          id: "sideDrawer",
          name: "SideMenu",
        
        },
      
      },
      center: {
        stack: {
          options: {},
          children: [{
            component: {
              name:"NewCard",
              options: {
                topBar: {
                  hideOnScroll: true,
                  title: {
                    text: "Homescreen",
                    color: "white"
                  },
                  leftButtons: [
                    {
                      id: "buttonOne",
                      icon: require("../assets/img/menu.png")
                    }
                  ],
                  background: {
                    color: "#05B8CC"
                  },
                  drawBehind: false,
                  visible: true,
                  animate: true
                },
              }
            }
          }]
        }
      },
      
    }
  }
  });

**Comment by Motojo** [comment]
Same issue here on V2.
Any way to style it on iOS to be in front of the content ?

**Comment by uday007** [comment]
@rishabhSmartdata Have you find any solution for this?

I am also facing the same issue.

**Comment by igor-nm** [comment]
Same issue here on V2.
Any news about this topic on V2 version ?

**Comment by Desintegrator** [comment]
same trouble
