### ISSUE TITLE
[v2] iOS Modal unmount bug

### ISSUE THREAD

**Issue by yusufyildirim** [wix/react-native-navigation#3216]
### Issue Description
Hi,

Everything is working fine about show and dismiss a modal but the problem is whenever we dismiss a modal, it's react component is doesn't unmount until another modal shown.

### Steps to Reproduce / Code Snippets / Screenshots

Click Show Modal
Click Test Modal Lifecycle
Click Dismiss
didDisappear alert appears
componentWillUnmount alert should appear too but event doesn't firing
Click Test Modal Lifecycle again
Previous modal's componentWillUnmount event triggers

![2018-05-16 11 16 43](https://user-images.githubusercontent.com/22980987/40109579-5679055a-5906-11e8-9438-4011394d79d9.gif)

---
### Environment
* React Native Navigation version:  v2@alpha
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS (Android works fine)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / iOS 11.3

**Comment by yusufyildirim** [comment]
Here is the pr for e2e test of this situation https://github.com/wix/react-native-navigation/pull/3215

**Comment by TylerNRobertson** [comment]
It seems this might be an issue again in V3.

**Comment by TylerNRobertson** [comment]
This seems to be present again in V3. Works fine on android but doesnt trigger "componentWillUnmount" on any components inside the modal on IOS.

**Comment by wsliaw** [comment]
Getting this on V6 iOS, modal dismissed but missing `componentWillUnmount`

**Comment by TylerNRobertson** [comment]
This is still happening in version 7
