### ISSUE TITLE
[v2] dismissModal stops calling componentDidDisappear after the first dismissal

### ISSUE THREAD

**Issue by mahyarr** [wix/react-native-navigation#3223]
### Issue Description

When I dismiss a modal for the first time for a given layout, the componentDidDisappear callback is called the first time but stops getting called on subsequent dismissModal calls for the same layout.

### Steps to Reproduce / Code Snippets / Screenshots

1- Show a modal with a component layout
2- dismiss the modal and notice `componentDidDisappear` does get called.
3- Now show the same component layout as modal again
4- Dismiss the modal. 

Notice `componentDidDisappear` is no longer invoked.

---
### Environment
* React Native Navigation version: 2.0.2291
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 7p

**Comment by guyca** [comment]
Related to #3216

**Comment by yogevbd** [comment]
Solved here https://github.com/wix/react-native-navigation/commit/3a282ea24b88513b96d1edce787051a24cdefef4
