### ISSUE TITLE
Passing array of functions in passProps causes Malformed calls from JS: field sizes are different

### ISSUE THREAD

**Issue by henricazottes** [wix/react-native-navigation#3226]
### Issue Description

When passing an array of functions in the ``passProps`` prop of ``navigator.push`` I get the following error:

    Malformed call from JS: field sizes are different. 

### Steps to Reproduce / Code Snippets / Screenshots

    navigator.push({ screen: 'anyScreen', passProps: { anyKey: [() => {}] } });

![Screenshot](https://i.stack.imgur.com/qceDL.png)

---
### Environment
* React Native Navigation version: react-native-navigation@^1.1.352
* React Native version: react-native@^0.55.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 6P / Android 8.1.0

**Comment by guyca** [comment]
duplicate #2814
