### ISSUE TITLE
Android Backbutton rendering issue

### ISSUE THREAD

**Issue by vanlooverenkoen** [wix/react-native-navigation#3227]
https://stackoverflow.com/questions/50424780/android-back-button-is

### Issue Description
The android back arrow has a strange rendering issue. It has an extra bump at the left of the arrow.

![image](https://user-images.githubusercontent.com/21172855/40268124-4a072b8a-5b68-11e8-931e-406e99f71355.png)

### Steps to Reproduce / Code Snippets / Screenshots

Just create a single page application and push a new screen. The back arrow will be shown but it will have a rendering issue.

---
### Environment
* React Native Navigation version: 1.1.406
* React Native version: 0.52.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, device, any OS, any buildType.

**Comment by guyca** [comment]
hmm interesting, I've never noticed this. Regardless, I'm closing as v1 is deprecated and we've switched to the default back button vector icon in v2.
Thanks for reporting though 👍

**Comment by vanlooverenkoen** [comment]
When will v2 be available. Or is there a stable enough version we can use?
