### ISSUE TITLE
using code-push with this library

### ISSUE THREAD

**Issue by iamsoorena** [wix/react-native-navigation#3228]
Is it possible to use code-push with react native navigation?
if yes, HOW?!

**Comment by iamsoorena** [comment]
I asked this question in stackoverflow
If anyone knows the answer please help [here](https://stackoverflow.com/questions/50424554/registering-react-native-code-push-with-react-native-navigation-by-wix).

**Comment by j-schuster** [comment]
Has anyone maybe used these two libs recently? I feel like I am close to getting it to work, but I need to know how RNN V2 loads the bundle, or where I could find the implementation of it.
