### ISSUE TITLE
Example not working on IOS

### ISSUE THREAD

**Issue by yansenarmandau** [wix/react-native-navigation#323]
### Issue Description

i just clone this repo and follow example instructions. but when i want to run example i got this message:

Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

---
### Environment
* React Native Navigation version: ^2.0.0-experimental.118
* React Native version: 0.31.0
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Iphone 6, OS 10

**Comment by DanielZlotin** [comment]
Some stupid but important questions:
* Did you `npm install` inside `example` folder?
* Did you clean the xcode project? (command+alt+shift+K)?
* What version of xcode do you use?
* Did you change the name of any file?

**Comment by yansenarmandau** [comment]
Hi Daniel

1. Did you npm install inside example folder? **i did**
2. Did you clean the xcode project? (command+alt+shift+K)? **i did**
3. What version of xcode do you use? **Version 8.0 (8A218a)**
4. Did you change the name of any file? **No**

/react-native-navigation/example/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:494:3: Ignoring return value of function declared with warn_unused_result attribute

thats i got error from Xcode

Thanks

**Comment by artald** [comment]
@yansenarmandau there is an issue with Xcode 8 and React Native (it was fixed in RN 33, but we only support RN-31 at the moment)

To fix it you need to go to `RCTWebSocket.xcodeproj`under Libraries in the Xcode project navigator -> Build Settings -> Other Warning Flags -> edit it and delete the `-Werror` flag

**Comment by brunolemos** [comment]
It works now that #379 has been merged. It can be closed.

**Comment by gran33** [comment]
@brunolemos did u try to run the app from command line, like this:
`react-native run-ios`? or through `xcode`?

**Comment by brunolemos** [comment]
@gran33 I usually run `npm start -- --reset-cache` in the terminal, then open xcode, clean the project and run from there.

**Comment by brunolemos** [comment]
About the `Ignoring return value of function declared with warn_unused_result attribute` error, that's still requiring a manual fix:

Just add `(void)` in the beginning of the line that is causing this error. 

That's a very commom error in RN so I just forgot that in my last comment, sorry. The merge makes it works after this manual fix. It didn't work before even with this fix.
