### ISSUE TITLE
goback does not work in react navigation v2

### ISSUE THREAD

**Issue by mahshadalishahi** [wix/react-native-navigation#3230]
hello
I'm using react navigation on the site
http://docs.nativebase.io/docs/examples/navigation/StackNavigationExample.html
I answered the projects I used navigation v1
but in navigation v2
goback() does not work in second page
and when hardware back button the application close

**Comment by swingywc** [comment]
hi @mahshadalishahi , I think you are on the wrong repository. Here is `react-native-navigation` but what you are using is `react-navigation`. To get answered for your question, I think you should go to this repository: https://github.com/react-navigation/react-navigation/issues
