### ISSUE TITLE
[V2][Android] Bottom tab name is hidden

### ISSUE THREAD

**Issue by congnguyen91** [wix/react-native-navigation#3231]
### Issue Description

[Set navigation bottom tab. follow the v2 docs - Only active tab shows its name.

### Steps to Reproduce / Code Snippets / Screenshots
![screenshot_20180520-222233_familytree](https://user-images.githubusercontent.com/18322684/40280422-314cbf4a-5c7d-11e8-90b6-1dd55f66f2f9.jpg)
---
### Environment
* React Native Navigation version: v2
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Device? 8.0? Debug):

**Comment by ntcong91** [comment]
hi @swingywc  I mean that it still happen

```
options: {
              bottomTab: {
                title: "Home",
                icon: Images.logo,
                iconInsets: {
                  top: 6,
                  left: 0,
                  bottom: 6,
                  right: 0
                },
                forceTitlesDisplay: true
              },
              topBar: {
                visible: false
              },
              forceTitlesDisplay: true
            }
```

**Comment by ntcong91** [comment]
Also try:
```
    appStyle: {
      forceTitlesDisplay: true
    },
```

**Comment by aurelienshz** [comment]
How about the answer on #3463 ?

**Comment by congnguyen91** [comment]
Thanks for react-native-navigation team. It's ok right now :) 
```
                bottomTab: {
                  text: "Home",
                },
                bottomTabs: {
                  titleDisplayMode: 'alwaysShow'
                },
```
