### ISSUE TITLE
Debounce navigation methods.

### ISSUE THREAD

**Issue by sorodrigo** [wix/react-native-navigation#3235]
### Issue Description

On v1, when using navigation methods such as `push`, `pop`, or `resetTo` the UI isn't blocked until the navigation has been performed. This call isn't debounced either, so if a user clicks fast enough (easier to replicate on slow mobiles) the app could push, pop a screen twice.

### Steps to Reproduce / Code Snippets / Screenshots
In an app with at least 2 screens, add an click handler that calls `this.props.navigator.push()` from one screen to navigate to the other. Double click the navigation button. 

---
### Environment
* React Native Navigation version: 1.1.434
* React Native version: 0.55.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): iOS simulator

I'm happy to submit a PR if you think debouncing/throttling the calls to NavigationSpecific is good solution. If there's a better idea, I'm happy to help with some guidance.

**Comment by jinshin1013** [comment]
Just use lodash.debouce? I think it should not debounce on the library side.

**Comment by sorodrigo** [comment]
I guess that for most navigation method calls I can debounce it myself. My main issue is with the navigator buttons, if I want to disable it. Because they’re defined statically, I have to call `setButtons`, find the correct button, and change the disabled prop to true. And then repeat the same code on each screen.

And I understand that this problem can be solved in userland, but don’t really see a use case for stacking the same view more than once because the method was called twice before navigation.

Anyway I really have to say thanks for the work you guys are doing. 🙂

**Comment by guyca** [comment]
This will be addressed in #3110
