### ISSUE TITLE
[v2] Modal animations can't be disabled

### ISSUE THREAD

**Issue by Dexwell** [wix/react-native-navigation#3236]
### Issue Description

My modals keep opening with animations despite setting `options.animated` to `false`.

### Steps to Reproduce / Code Snippets / Screenshots

The following doesn't disable the animation:

```js
Navigation.showModal({
  component: {
    name: 'app.Main',
    options: {
      animated: false
    }
  }
});
```

---
### Environment
* React Native Navigation version: 2.0.2292
* React Native version: 0.55.3
* Platform(s): iOS, Android unknown
* Device info: Simulator, iPhone X, iOS 11

**Comment by yogevbd** [comment]
Try this:
```js
Navigation.showModal({
  component: {
    name: 'app.Main',
    options: {
      animations: {
        showModal: {
          enable: false
        }
      }
    }
  }
});
```

**Comment by Dexwell** [comment]
Thanks, couldn't find this documented.
