### ISSUE TITLE
[ANDROID] AppState change is dispatched when calling startXXXApp

### ISSUE THREAD

**Issue by brunolemos** [wix/react-native-navigation#3239]
### Steps to Reproduce / Code Snippets / Screenshots

```js
AppState.addEventListener(appState => {
    console.log(appState)
})

Navigation.startSingleScreenApp(...
...
Navigation.startTabBasedApp(...

// iOS: no events (unless I really minimize the app, which is correct)
// Android: background / active / background / active
```

PS: My MainActivity launchMode is set to singleTop. Tried singleTask as well.

---
### Environment
* React Native Navigation version: 0.55.4
* React Native version: 1.1.446 (been always like this)
* Platform(s) (iOS, Android, or both?): Android only
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by guyca** [comment]
This is a known behaviour of V1 and is resolved in v2. Basically this happens since `start*App` starts a new Activity, which triggers `AppState` events.
You can work around this issue by `await`ing the `start*App` call abd ignoring events until the promise is resolved.

**Comment by guyca** [comment]
I don't think so, Basically `AppState` changes in `onPause` and `onResume` of `NavigationActivity` - displaying a permission dialog will trigger appStateChange events as the dialog is actually an activity. This behaviour exists in v2 as well.
