### ISSUE TITLE
Central place to handle deeplinks.

### ISSUE THREAD

**Issue by Antonides** [wix/react-native-navigation#324]
Does anybody has an example how to handle deeplinks on a central place? now i need to handle the event in every page to listen for deeplinks.

**Comment by bbrock25** [comment]
I am also interested in seeing a good implementation of deep links. Is there a way to leave a component mounted to sit and listen for all available links?

**Comment by brainstretch** [comment]
@bbrock25 Now i have a route component and handle al the deeplinks in this component. 
```js
<Route parent={this} />
```
  In my route i can call:
```js
this.props.parent.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));

this.props.parent.props.navigator.resetTo
```

**Comment by SudoPlz** [comment]
I need a way to do that as well..!

**Comment by Colmea** [comment]
@Antonides I'm also interested. Could you explain us how you keep this Route component mounted ? Where do you put it ?

**Comment by Jpoliachik** [comment]
You can do this without having access to a `navigator` instance. 
This isn't strictly documented though - so beware of breaking in future updates. 
```
Navigation.setEventHandler('myUniqueIdHere', (event) => {
    	console.log("all navigation events logged here");
    })
```

Just remember to call `Navigation.clearEventHandler('myUniqueIdHere');` if you want to unsubscribe.

**Comment by peterp** [comment]
@Jpoliachik I'm trying to figure out what you do with the event? You cannot push or reset the stack from the static `Navigation` object?

**Comment by Jpoliachik** [comment]
@peterp For actions that modify a stack, you'll need to register for the event somewhere which has contextual access to that navigation instance. This was purposely done because an App may have more than one navigation stack at once.

**Comment by peterp** [comment]
@Jpoliachik Thanks! I figured it out with your rootNavigator example above. It's a super awkward API :)
