### ISSUE TITLE
[V2][Android] TopBar Custom Title Component Passprops

### ISSUE THREAD

**Issue by jinshin1013** [wix/react-native-navigation#3240]
### Issue Description

Custom TopBar Title component does not pass any props defined in passProps: { }
Only happening in Android.

### Steps to Reproduce / Code Snippets / Screenshots

![screen shot 2018-05-22 at 1 13 57 pm 2](https://user-images.githubusercontent.com/17612922/40340411-2fef5f18-5dc2-11e8-9b1a-9140fc065db9.png)

I have a screen with a custom title component which is a progress bar which takes in two props, `currentStep` and `totalSteps` which is passed in passProps as you can read from the image. 
In IOS, it successfully passes the props to `ROUTES.PROGRESS_INDICATOR`, however in Android, it does not. I know V2 is not yet stable, however I am not 100% sure if the fault is on my end or not.

### Environment
* React Native Navigation version: 2.0.2292
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Android 7.0, Debug

**Comment by kfroemming** [comment]
I am currently having the same issue on iOS but in a slightly different way. On initial render of the component, the props are passed.  I can reproduce this by transitioning to a new screen, transitioning back to the same screen, and then waiting for my component to render. Once it renders, the props are no longer being passed to the component.
