### ISSUE TITLE
[Android] drawUnderStatusBar causing tab bar bottom cut off

### ISSUE THREAD

**Issue by 1453009** [wix/react-native-navigation#3241]
### Issue Description

I set `drawUnderStatusBar: true` to set status bar transparent, this causing tab bar bottom cut off a half
if set it to false, tab bar would show fine.

![screenshot_20180522-150649](https://user-images.githubusercontent.com/25218577/40350006-8e283a0e-5dd2-11e8-9d26-98ae0ad4b063.png)

### Steps to Reproduce / Code Snippets / Screenshots

push a screen with `drawUnderStatusBar: true` and pop (to main screen with tab bar).

---
### Environment
* React Native Navigation version: 1.1.334
* React Native version: 0.55
* Platform: Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 6, Android 7.1.1, debug

**Comment by guyca** [comment]
Hey there,
This is resolved in v2. Meanwhile you can workaround this by setting the following style options in your main screen:

```js
drawUnderStatusBar: true,
navBarTopPadding: 24
```
