### ISSUE TITLE
Error type 3 Error: Activity class {com.reactnativenavigation/com.reactnativenavigation.MainActivity} does not exist.

### ISSUE THREAD

**Issue by VanishingOne** [wix/react-native-navigation#3242]
It says build successful but after that I am getting this error while building Android app:

Running C:\Users\Dell\AppData\Local\Android\Sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
Starting the app on emulator-5554 (C:\Users\Dell\AppData\Local\Android\Sdk/platform-tools/adb -s emulator-5554 shell am start -n com.reactnativenavigation/.MainActivity)...
Starting: Intent { cmp=com.reactnativenavigation/.MainActivity }
Error type 3
Error: Activity class {com.reactnativenavigation/com.reactnativenavigation.MainActivity} does not exist.

**Comment by VRuzhentsov** [comment]
@VanishingOne if you use emulator, try `Cold boot`
