### ISSUE TITLE
(v2) Different topBar animation comparing to V1

### ISSUE THREAD

**Issue by stefan9625** [wix/react-native-navigation#3246]
in react-native-navigation v2, animation of *TitleBar* (TopBar) is not same as in react-native-navigation v1, or i can not make it work as it used to, so what i'm talking about is that topBar is not moving with screen , but it's separated from it, how this can be fixed?, Did anyone experienced this issue before?

* React Native Navigation version: V2
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Device and Simulator, IOS, Debug and Release

**Comment by jinshin1013** [comment]
I got the same. On IOS, when swiping (pop gesture) to pop to previous page, if the previous does not have a top bar, as you are slowing swiping, the screen will just cut off the top bar and only animate the screen.
