### ISSUE TITLE
Possible to pass intent data to the react native part  from push notifications ??

### ISSUE THREAD

**Issue by sja1n** [wix/react-native-navigation#3248]
Hello, I am using react-native-navigation for a long time in all my react-native apps. I wanted to know if its possible to read the intent data from push notifications as I need to open a page according to the data present in intent. 
As even from linking only thing i can read is url with which the app was opened. and for any other type.

So, Is there any way by which I can pass the intent data to the react-native bridge ?

### Environment
* React Native Navigation version: 1.1.451
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?): Android

**Comment by pytlakow** [comment]
I am facing the same. Did you find solution @sja1n?

**Comment by sja1n** [comment]
Still havent found any solutions 😞 , neither can find in v2
