### ISSUE TITLE
[v1] Change Back Button Title Globally

### ISSUE THREAD

**Issue by swingywc** [wix/react-native-navigation#3249]
### Issue Description

Currently this project provide a method to override the back button title from previous page `pushScreen` function.   

What I want is to have no back button title in a single page, no matter from which previous page. 

Therefore I would like to ask is there any option in `static navigatorStyle` to change the back button title totally, without passing an empty string `' '` in every `pushScreen` function? Appreciate for any kindly help.

---
### Environment
* React Native Navigation version: 1.1.458
* React Native version: 0.52.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both Simulator and Device

**Comment by guyca** [comment]
Hey @swingywc 
You should create a wrapper over `Navigation` where you can add default options. The wrapper should expose the entire `Navigation` api, and will enforce whatever behaviour you require.
For example, when pushing a screen - it will remove the back button by default from all pushed screens.
Hope this answers your question.
