### ISSUE TITLE
How to use TabLayout

### ISSUE THREAD

**Issue by sathyakumarseshachalam** [wix/react-native-navigation#325]
Are there any examples on how to use `TabLayout`. I saw a mention in #146 , but unable to find an example. 

I am interested in having a bottom tab bar to switch between top level view. But each top level view of mine also has a sectioned views on top. (Similar to Product, Orders thats shown in the animated example in Readme)

If available, is there any chance at at all to use it in 1.3.x ?

**Comment by guyca** [comment]
V1.3 is not supported. 
This feature will be supported in v2. On Android you can use it like [this](https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js#L103). RNN doesn't support this feature yet on iOS. Instead, we use [react-native-custom-segmented-controller](https://github.com/wix/react-native-custom-segmented-control).
We're going to consolidate the API as part of the work on v2, once that's done the Android API will probably change a bit.
