### ISSUE TITLE
[v1] Is it possible to render an element outside of the drawer (on top of the normal content)

### ISSUE THREAD

**Issue by EdwardDrapkin** [wix/react-native-navigation#3256]
Title really says it all.

We have a mockup for a slide out drawer (from the right) that pushes icons on top of the regular content, on top of the overlay.  

Is this possible with the built in drawer?

Thanks!

**Comment by guyca** [comment]
I'm not sure I understand the design you've described, but v1 drawer is very limiting in regards to what you can achieve with it.

"that pushes icons on top of the regular content, on top of the overlay." - on top of what overlay?

**Comment by EdwardDrapkin** [comment]
So there's a screen `[screen]` that becomes `[...een][drawer]` once the drawer is open, and there's an opt-in overlay to paint on top of `[screen]`.  Is there any way content from the drawer can get painted on top of the original `[screen]`?  

If my weird brackets are unclear, I can take screenshots tomorrow at work.

**Comment by guyca** [comment]
Well, in v1 you can use different types of side menus and animations that might suite your requirements. See the [docs](https://wix.github.io/react-native-navigation/#/top-level-api) and look for `drawer` node.
Note that these options are available only on iOS.

In v2 you have more flexibility as you have more control over the layout and hierarchy and you can show Overlays as well.
I suggest you play around a bit with the playground app in v2 branch. 👍
