### ISSUE TITLE
`react-native-navigation` is breaking `react-native/PermissionsAndroid`

### ISSUE THREAD

**Issue by rcidt** [wix/react-native-navigation#3257]
### Issue Description

`react-native-navigation` is preventing the `onRequestPermissionsResult` method in the application's `MainActivity` from being called.

This is causing https://github.com/facebook/react-native/issues/17985

### Steps to Reproduce / Code Snippets / Screenshots
(copied from https://github.com/facebook/react-native/issues/17)
We have a Camera component and it should check for the Camera permission before mounting.

In my app's AndroidManifest.xml I have the line, along with many other permissions:

`<uses-permission android:name="android.permission.CAMERA"/>`
In our component's componentDidMount() we call a function that should return true if we have permission and false if we do not have, here is the relevant snippet of the function:

```
if (Platform.OS === 'android') {
const isGranted = await PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.CAMERA);
      if (isGranted) {
        return true;
      }
      try {
        console.log('before request');
        const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.CAMERA,
          {
            title: 'Dialog Title',
            message: 'Dialog Message',
          }
        );
        console.log('after request');
        return granted === PermissionsAndroid.RESULTS.GRANTED;
      } catch (err) {
        console.log('error');
        console.log(err);
      }
}
```
#### Expected Behavior

A dialog with my title and message should appear, if the user clicks on "Allow", the promise should resolve and my component should render as expected.

---
### Environment
* React Native Navigation version: 1.1.408
* React Native version: 0.49.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): API > 23

**Comment by rcidt** [comment]
I see this is already addressed here https://github.com/wix/react-native-navigation/pull/470

**Comment by vanlooverenkoen** [comment]
What did you do to fix this issue?

**Comment by rcidt** [comment]
@vanlooverenkoen I updated to the latest version of `react-native`
