### ISSUE TITLE
override volume onKeyDown, android

### ISSUE THREAD

**Issue by Evgen74** [wix/react-native-navigation#3258]
### Issue Description

I create an application, and one of the main screens is the camera. I want to take a picture by clicking on the volume button, but this code does not work for me. Tell me how it can be implemented?

MainActivity.java
```
import android.util.Log;
import android.view.KeyEvent;

import com.reactnativenavigation.controllers.SplashActivity;

public class MainActivity extends SplashActivity {

  @Override
  public boolean onKeyDown(int keyCode, KeyEvent event) {
      Log.v("MainActivity", Integer.toString(keyCode));
      return true;
  }

}
```
---
### Environment
* React Native Navigation version: 1.1.462
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, both, both

**Comment by guyca** [comment]
Hey @Evgen74 
v1 uses an unorthodox Activity setup, the actual Activity running your code isn't MainActivity.

You can respond to key events by setting a listener in your `MainApplication`

```java
public class MainApplication extends NavigationApplication {

    @Override
    public void onCreate() {
        super.onCreate();
        setActivityCallbacks(new ActivityCallbacks() {
            @Override
            public void onKeyUp(int keyCode, KeyEvent event) {
                
            }
        });
    }
}
```
