### ISSUE TITLE
[v2] 3D Touch Peek/Pop Support

### ISSUE THREAD

**Issue by Dexwell** [wix/react-native-navigation#3259]
Is this planned for v2 as well?

**Comment by birkir** [comment]
Not planned, but I may create a PR with that functionality.

How about having an property in component options to allow this.

I thought about having a component we can wrap a view with to use as the Preview View.
```js
<Navigation.Element elementId="Preview1">
  <View>...</View>
</Navigation.Element>
```

Then we can reference it with `elementId`.
```js
Navigation.push(this.props.componentId, {
  component: {
    name: 'example.PushedScreen',
  },
  options: {
    preview: {
      elementId: 'Preview1',
      actions: [/* ... */],
      height: 250,
      commit: true,
    },
  },
});
```

**Comment by Dexwell** [comment]
Sounds fantastic!

**Comment by Dexwell** [comment]
@birkir Congrats on the merge. Could you describe the APIs you ended up implementing? Will a Peek `preview` also work with `Navigation.showModal` and `Navigation.showOverlay`?

**Comment by guyca** [comment]
@birkir ❤️
