### ISSUE TITLE
How disable drawer on current window?

### ISSUE THREAD

**Issue by alexsbobylev** [wix/react-native-navigation#326]
### Issue Description

How disable drawer on current window?

---
### Environment
- React Native Navigation version: 2.0.0-experimental.120
- React Native version: 0.32.0
- Platform(s) (iOS, Android, or both?): both

**Comment by guyca** [comment]
@alexsbobylev Currently that's not possible. You can disable the drawer open gesture for the entire app with `disableOpenGesture` attribute.

```js
  drawer: {
    left: {
      screen: 'example.SideMenu'
    },
    disableOpenGesture: true
  }
```

But I think we definitely should add an option to disable the `SideMenu` per screen.
cc @DanielZlotin

**Comment by MeKarina** [comment]
@guyca 
instead of passing disable option,, passing props would create higher impact i guess..

with props,,`SideMenu` would be dynamic depend on current screen... one prop is an option to disable `SideMenu` of course...

similar like manipulating current `navigatorStyle`...

```js
static navigatorStyle = {}
```

**Comment by guyca** [comment]
I like your suggestion @MeKarina, I'll take this up with @DanielZlotin

**Comment by tolu360** [comment]
Hello @guyca, please do you know if this was ever implemented? Ability to disable open gesture for the drawer at the screen level, that is, not just app-wide. Thanks

**Comment by Fenwil** [comment]
Guys take a look at this hacky solution maybe will help you:
[https://github.com/Fenwil/rnn-disable-drawer](https://github.com/Fenwil/rnn-disable-drawer)

**Comment by netojose** [comment]
I found a beautiful solution.

To disable drawer on a specific screen, just do:

```
    constructor(props) {
        super(props);
        this.props.navigator.setOnNavigatorEvent(
            this.onNavigatorEvent.bind(this)
        );
    }

    // If this screen was the first screen app (like a slash or login page), you will need do this
    // componentWillMount() {
    //     this.props.navigator.setDrawerEnabled({
    //          side: "left",
    //          enabled: false
    //      });
    // }

    onNavigatorEvent(event) {
        switch (event.id) {
            case "willAppear":
                // On enter on this screen, enable the drawer
                this.props.navigator.setDrawerEnabled({
                    side: "left",
                    enabled: false
                });
                break;
            case "didDisappear":
                // On leave from this screen, enable the drawer
                this.props.navigator.setDrawerEnabled({
                    side: "left",
                    enabled: true
                });
                break;
        }
    }
```
