### ISSUE TITLE
event propagation

### ISSUE THREAD

**Issue by gaultierq** [wix/react-native-navigation#3260]
Is there a way to know if broadcasted event have been consumed by other listeners ? It would be handy, especially when using deeplinking

**Comment by guyca** [comment]
Which events are you referring to?

**Comment by gaultierq** [comment]
those available in `addOnNavigatorEvent`

**Comment by guyca** [comment]
No, events are simply emitted to registered listeners. You can probably implement this behaviour by extending and events system and managing events in some centralised manager.
Keep in mind the deeplinks feature was removed from v2 as it's unrelated to navigation from this exact reason, it's a naive pub sub implementation which is really not suited for any serious project.

**Comment by gaultierq** [comment]
agreed, but yet, when clicking on a deeplink / universal link, in some cases, I need to access the current navigator (the static `Navigation#doSomething` is not good enough). What are my options ?
Many thanks for the good work btw

**Comment by guyca** [comment]
The current api is definitely limiting when dealing with such use cases. I'm afraid I don't have any solutions to offer you as we've stopped supporting v1.

In v2, you can assign predefined identifiers to screens which lets you perform actions on these screens statically. There's no navigator object and no need to pass or keep track of navigators.
We've added a more robust [events](https://wix.github.io/react-native-navigation/v2/#/docs/events) api which allows you to listen to any Navigation command and screen visibility.
I think these features support your requirements.

**Comment by gaultierq** [comment]
sounds exciting, v2 look quite ready for production now 🥇
