### ISSUE TITLE
Handle notification open the detail screen

### ISSUE THREAD

**Issue by tranhuuthinhit** [wix/react-native-navigation#3261]
### Issue Description

I have a case regarding notification. When I tap on a notification, I want a push to the detail screen on another tab.

Steps:
1. I have an app with 2 tabs (Home & Product). The first I will start this app and active Home tab.
2. I received a notification and then I tap on this notification. The app will active Product tab and then push to the Product detail. 

But I don't find any APIs for support this case.

---
### Environment
* React Native Navigation version: 1.1.352
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Real devices

**Comment by guyca** [comment]
Hey there,

You can start your app with one of the tabs initialised with multiple screens pushed into the stack.

```js
Navigation.startTabBasedApp({
  tabs: [
    {
      label: 'Home',
      screen: 'HomeScreen',
      icon: require('../img/home.png'),
      title: 'Home'
    },
    {
      label: 'Products',
      screen: 'ProductsScreen',
      icon: require('../img/products.png'),
      title: 'Products',
      components: [
        {
          screen: 'NotificationScreen',
          title: 'Push notification 1'
        },
        {
          screen: 'NotificationScreen',
          title: 'Push notification 2'
        }
      ]
    }
  ]
});
```

**Comment by sebringj** [comment]
A way I can think of (so far) is to keep track of the current component id being viewed using the **Navigation.events().registerComponentDidAppearListener**.

create a navigation wrapper to use globally
```
class NavigationWrapper {
  static setComponentId(componentId) {
    this._componentId = componentId
  }
  static push(routeName) {
    Navigation.push(this._componentId, { component: { name: routeName } })
  }
}
```
Then setup global event listener
```
Navigation.events()
  .registerComponentDidAppearListener(({ componentId, componentName }) => {
   NavigationWrapper.setComponentId(componentId)
})
```
Then when navigating globally...
```
  NavigationWrapper.push('someRoute')
```
