### ISSUE TITLE
tab icons are tinted!

### ISSUE THREAD

**Issue by barjas** [wix/react-native-navigation#3263]
### Issue Description
the tab icons are tinted , there is not option to disable tab icons from being tinted by any color

### Steps to Reproduce / Code Snippets / Screenshots

- create a tabbed app
- add PNG icons
- the icons are tinted with the tab color

---
### Environment
* React Native Navigation version: 1.1.72
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by guyca** [comment]
Hey @barjas, This is resolved in v2.
