### ISSUE TITLE
landscape mode not working

### ISSUE THREAD

**Issue by Proxy08** [wix/react-native-navigation#3264]
Hey  I've tried to setup my app in landscape mode   by setting android:screenOrientation="landscape" and orientation: 'landscape' on startSingleScreenApp   but it always comes back in portrait mode. why ???
### Issue Description

![image](https://user-images.githubusercontent.com/18226981/40578730-d8fd6524-6136-11e8-938f-e2010990bb85.png)
![image](https://user-images.githubusercontent.com/18226981/40578742-11b28426-6137-11e8-80b2-61a4de948f0f.png)

---
### Environment
* React Native Navigation version: 1.1.462
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device

**Comment by guyca** [comment]
https://github.com/wix/react-native-navigation/issues/349#issuecomment-323005136
