### ISSUE TITLE
[v2] Animate statusBar style change using mergeOptions

### ISSUE THREAD

**Issue by Dexwell** [wix/react-native-navigation#3266]
Feature request, see title. I think this is an important option to have. Perhaps something like:

```js
Navigation.mergeOptions(this.props.componentId, {
  statusBar: {
    style: 'light',
    animate: true || false
  }
});
```

**Comment by guyca** [comment]
Is this supported on iOS? I don't think it is on Android

**Comment by Dexwell** [comment]
It is on iOS, see `StatusBar.setBarStyle()` https://facebook.github.io/react-native/docs/statusbar.html#setbarstyle

**Comment by guyca** [comment]
I've added it to the backlog, if you'd like to take a stab at implementing it, go ahead 👍

**Comment by mrousavy** [comment]
The `animate` flag is not available in the types, was this feature removed?

**Comment by guyca** [comment]
@mrousavy Seems like it was left out unintentionally but the feature works as expected.
