### ISSUE TITLE
Ability to overwrite default tab navigation stack behavior

### ISSUE THREAD

**Issue by JPStrydom** [wix/react-native-navigation#3269]
### Issue Description

With regards to navigation on `BottomTabs` generated from `Navigation.startTabBasedApp`: It's my understanding that each tab keeps track of it's own navigation stack - meaning that if I navigate as follows:

`tab1 -> screen1 -> screen2 -> tab3 -> tab1`

that I will still be on `screen2`. Is there a way to overwrite this behavior so that when I press on a tab's icon, it navigates to that tab's initial screen regardless of how many screens it has on its stack?

### Environment
* React Native Navigation version: 1.1.457
* React Native version: 0.55.3
* Platform(s): both
* Device info: Nexus 5 Emulator with Android 8.0.0

**Comment by guyca** [comment]
You can listen to [bottomTabReselected](https://github.com/wix/react-native-navigation/issues/1719#issuecomment-323679041) event in the root screen.
