### ISSUE TITLE
setStackRoot() not working from the sidemenu in react-native-navigation V2

### ISSUE THREAD

**Issue by Vinu-MysteriousTechVision** [wix/react-native-navigation#3271]
### Issue Description

When I try to change the root page from home page it will work perfectly, but it not worked from the side menu.
The below code is used in both page(Side menupage and Home page)

  ```js
  Navigation.setStackRoot(this.props.componentId, {
      component: {
        name: 'navigation.SampleRNNavigationV2.SecondPage',
        options: {
          topBar: {
            title: {
              text: 'Pushed 1'
            }
          }
        }
      }
    });
```

using `setRoot` from the side menu the page is reset, but it haven't any animation.

---
### Environment
* React Native Navigation version: 2.0.2305
* React Native version: 0.54.4
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by oscar-omana** [comment]
I faced the same issue and realized you have to use Deep Links instead.
The reason why it doesn't work is that each screen has it's own stack, so you can't change the stack of your main page from the side menu/page.

So, on your side menu you would trigger
` this.props.navigator.handleDeepLink({ link: "SecondPage" });`

Then you have to listen to the event on your main page:
`    onNavigatorEvent = event => {
        if (event.type === 'DeepLink') {
            const parts = event.link;
            if (parts === 'SecondPage') {
               //your setStackRoot code 
                 }
            }
            

    };`

**Comment by oscar-omana** [comment]
You can't change the stack of a screen from another screen.
You have to use Deep Links.
[https://wix.github.io/react-native-navigation/#/deep-links](url)

**Comment by Vinu-MysteriousTechVision** [comment]
@oscar-omana Thanks for your suggestion.

Deep links working in v1 react-native-navigation. But in V2 haven't mentioned about the Deep link.
Can you Please share sample code of using Deep Links in V2 react-native-navigation.
Shared link getting 404Error

**Comment by Vinu-MysteriousTechVision** [comment]
@guyca I am try to reset the root from the side menu. Used your suggetion to reset the stack but getting the error.
![simulator screen shot - iphone 6 - 2018-05-30 at 14 34 07](https://user-images.githubusercontent.com/19585857/40710541-8b273c3e-6416-11e8-8f39-feee0c579957.png)

**Comment by guyca** [comment]
Can you reproduce this in the playground app? On which platform?

**Comment by Vinu-MysteriousTechVision** [comment]
While checking the playground app, `setStackRoot` is not used in the sidemenu component.

Please note that, `setStackRoot` action working in the center component, but not from the sidemenu component(**From the Drawer**).

**Comment by guyca** [comment]
@Vinu-MysteriousTechVision 
If you believe this is a bug, please PR a failing detox e2e test. Thanks 👍

**Comment by Vinu-MysteriousTechVision** [comment]
@guyca Thanks your kind attention to the issue that I am facing using the 'setStackRoot' action

https://github.com/Vinu-MysteriousTechVision/TestProjectRNNavigationV2/tree/master/Sample3RNNavigationV2

This is a sample project for testing the reset scenario(reset the page from the side menu using `setStackRoot`).
Can you please verify the given sample project.

**Error reproducing stpe:**
1. Tap on side menu(**`Menu 1`** in Drawer) in second time(**Reset action using `setStackRoot`** ) getting error.

**Comment by pmachowski** [comment]
@guyca  I can reproduce it on iOS platform. (not tested on Android)

As a workaround I'm caching the currently visible screen's `componentId` like this:
```
Navigation.events().registerComponentDidAppearListener((componentId, componentName) => {
  // cache the currently visible screen componentId for making transitions from a drawer menu
  if (componentName !== 'MainMenuScreen') {
    AppScreens.currentComponentId = componentId
  }
})
```
and later using it with `Navigation.setStackRoot(AppScreens.currentComponentId, {...})` for making screen transitions on the main stack.

**Comment by Vinu-MysteriousTechVision** [comment]
I have fixed the issue.

For managing navigation controller, we have created a **singleton class** which has an _id field_ used to store the currently active root component id.

Consider in side-menu have two menu options **Home and Settings**.
When navigating to the root page(Home or Setting), set the component id in a variable in the singleton navigation controller class. This component is used in side-menu to reset the page using the method setStackRoot()

Please find the updated sample project code: https://github.com/Vinu-MysteriousTechVision/TestProjectRNNavigationV2/tree/master/Sample3RNNavigationV2

> @guyca The animation is not working correctlty as expected. When resetting to the new page, the previous page is slightly visible.
> 
> Documentation already mentioned that setStackRoot() work as similar as push(). But I would like to animate the page without visible on the previous page. **So how can create custom animation**?

**Comment by diegolmello** [comment]
@Vinu-MysteriousTechVision Great job!
That said, I hope you guys are working on a better solution.
This is not an odd behaviour: it's an usual sidebar navigation.

**Comment by doublex** [comment]
Same issue
setStackRoot() does not work when using on the Drawer.

**Comment by Vinu-MysteriousTechVision** [comment]
@doublex  Did you try this logic? https://github.com/wix/react-native-navigation/issues/3271#issuecomment-394679775 


The project is in the version "react-native-navigation": "^2.0.2314".
The same logic also worked in the latest version.

**Comment by doublex** [comment]
@Vinu-MysteriousTechVision 
Yes, but it's a bad hack.

**Comment by tanys123** [comment]
You can set componentId to the stack and then use that in setStackRoot. No need to cache currentComponentId.

**Comment by Vinu-MysteriousTechVision** [comment]
@tanys123 Thanks for your valuable comment.
**It's now working using the latest version "react-native-navigation": "^2.0.2556".**

When i have integrated the older version of the react-native-navigation-v2("react-native-navigation": "^2.0.2314"),`set componentId to the stack and then use that in setStackRoot` this approach not worked and I have got the error 

> ExceptionsManager.js:73 Unhandled JS Exception: The callback setStackRoot() exists in module RNNBridgeModule, but only one callback may be registered to a function in a native module.

In an older version("react-native-navigation": "^2.0.2314"), I have used this [#3271 (comment)](https://github.com/wix/react-native-navigation/issues/3271#issuecomment-394679775) for managing the side menu(I haven't know its a good approach or not but i have to solve those issue).

**Comment by NweThazin** [comment]
Hi,

Center of sideMenu layout is BottomTabs.
So, How can I navigate to one new component screen which is not under bottom tabs from side Menu page..?? thank you

    Navigation.events().registerAppLaunchedListener(() => {
      Navigation.setRoot({
          root: {
              sideMenu: {
                center: {
                    bottomTabs: [Stack1,Stack2,Stack3]
                    },
                right: {
                    component: {
                        name: 'SideMenu'
                        }
                    },
                }
            }
        });
    });

**Comment by denieler** [comment]
as soon as I can open sideMenu from different screens approach with setting componentId as a constant when initialization of the layout doesn't work for me.
