### ISSUE TITLE
iOS and Android back button api

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#3276]
# Configuring the back button

```js
topBar: {
  backButton: {
    icon: require('icon.png'),
    visible: false,
    text: 'Back', // iOS only
    textVisible: true // iOS only
  }
}
```

**Comment by lan-nguyen91** [comment]
@guyca  v2

![image](https://user-images.githubusercontent.com/14827876/42488302-ca5622b8-83b9-11e8-8b4e-7cc529127a77.png)

![image](https://user-images.githubusercontent.com/14827876/42488325-ddb2dcb6-83b9-11e8-8f9d-13cc9b8b5c29.png)

setting title doesn't work like the example.

**Comment by lan-nguyen91** [comment]
@guyca nvm, it is working.

For those who might run into this error, if you have a stack within the tab, you might need to set title and titleVisible on the outer most parent level.
