### ISSUE TITLE
Usage with Relay

### ISSUE THREAD

**Issue by chrise86** [wix/react-native-navigation#328]
What is the best way of using this library with Relay? The complication comes with having to use a Relay RootContainer.

Is this at all possible? If so, does anyone have an example please?

**Comment by perrosnk** [comment]
+1

**Comment by danielfeelfine** [comment]
👍

**Comment by nosykretts** [comment]
+1

**Comment by eljago** [comment]
was anyone able to make it work with Relay?

**Comment by Brunoalcau** [comment]
+1
