### ISSUE TITLE
[v2] Cannot read property 'backButton' of undefined after setup new project

### ISSUE THREAD

**Issue by Albert-Gao** [wix/react-native-navigation#3284]
### Issue Description

The following screen shots are for iOS, 

for Android, it is more weird, development server returns 404, Can't find entry file index.android.js in any of the roots

<img width="376" alt="error1" src="https://user-images.githubusercontent.com/18282328/40837685-5b05ec46-65ef-11e8-88ef-11f65f5658ad.png">
<img width="281" alt="error2" src="https://user-images.githubusercontent.com/18282328/40837687-5b354e0a-65ef-11e8-98ab-e2f0fb648adb.png">

### Steps to Reproduce / Code Snippets / Screenshots

app.ts
```typescript
export default function start() {
  Navigation.registerComponent(
    'Main',
    () => TestComponent,
  )

  Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setRoot({
      root: {
        center: {
          component: {
            name: 'Main',
          },
        },
      },
    })
  })
}
```

index.js
```javascript
import start from './src/App'
start()
```
---
### Environment
* React Native Navigation version: 2.0.2314
* React Native version: 0.55.4
* Platform(s) (iOS): 11.0.1
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
You layout appears to be incorrect

```js
Navigation.setRoot({
      root: {
        center: {
          component: {
            name: 'Main',
          },
        },
      },
    })
```

`center` node is part of [sideMenu layout](https://wix.github.io/react-native-navigation/v2/#/docs/layout-types?id=sidemenu).
This doesn' reproduce in any of our apps so I'm closing as it seems like this isn't an RNN issue.
