### ISSUE TITLE
How to finish the screen which is in stack.

### ISSUE THREAD

**Issue by shrivastavaanurag** [wix/react-native-navigation#3285]
Hello wix, thanx for this beautiful library for react native.
I am new in react. **I want to finish the splash screen,** I search but didn't find a solution. please help.
What I use in react native instead of `CLEAR_TOP, SINGLE_TOP, or finish();
`

**Comment by jinshin1013** [comment]
I'm using [react-native-splash-screen](https://github.com/crazycodeboy/react-native-splash-screen). Works great. You can finish the splash screen by just calling SplashScreen.hide().

**Comment by shrivastavaanurag** [comment]
but I am using **wix/react-native-navigation.**
what is the process in this? and how to handle `backPress();`

**Comment by jinshin1013** [comment]
I'm also using RNN v2 and the process is much the same. I think your questions suit more in stackoverflow.
