### ISSUE TITLE
Android build fail - 2.0.0-experimental.122

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#329]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

android/app/src/main/AndroidManifest.xml:21:7-33 Error:
        Attribute application@allowBackup value=(true) from AndroidManifest.xml:21:7-33
        is also present at [myreactapp:react-native-navigation:unspecified] AndroidManifest.xml:12:9-36 value=(false).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:19:5-40:19 to override.

android/app/src/main/AndroidManifest.xml:24:7-38 Error:
        Attribute application@theme value=(@style/AppTheme) from AndroidManifest.xml:24:7-38
        is also present at [myreactapp:react-native-navigation:unspecified] AndroidManifest.xml:13:9-65 value=(@style/Theme.AppCompat.Light.NoActionBar).
        Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:19:5-40:19 to override.

---
### Environment
* React Native Navigation version: 2.0.0-experimental.122
* React Native version: 0.31
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by guyca** [comment]
Should be fixed in .123

**Comment by agumack** [comment]
thank @guyca

**Comment by agumack** [comment]
@guyca 
Attribute application@allowBackup: OK
Attribute application@theme value=(@style/AppTheme): miss?

I tried and error with log: Attribute application@theme value=(@style/AppTheme)

Thanks!

**Comment by guyca** [comment]
@agumack Remove the `theme` attribute from the `aplication` element in your `AndroidManifest.xml`
