### ISSUE TITLE
Request setRightButtonsBadge function

### ISSUE THREAD

**Issue by anhtuank7c** [wix/react-native-navigation#3293]
### Issue Description

* rightButtons: request function setBadge for rightButtons

```
navigator.setRightButtonsBadge({
    buttonIndex: 0,
    badge: 2 || null,
    badgeColor: 'red'
})
```

### Steps to Reproduce / Code Snippets / Screenshots
![img_2062 1](https://user-images.githubusercontent.com/3163410/40913549-265a4316-681f-11e8-9069-decab74cdcb7.PNG)

---
### Environment
* React Native Navigation version:^1.1.426
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Any

**Comment by guyca** [comment]
Use a custom button
https://wix.github.io/react-native-navigation/#/adding-buttons-to-the-navigator?id=custom-navigation-buttons
Add the badge in jsx 👍

**Comment by p77u4n** [comment]
Em chào anh Tuấn
