### ISSUE TITLE
issues with react-native-navigation scripts during compiling process.

### ISSUE THREAD

**Issue by jerodgers1** [wix/react-native-navigation#3294]
### Issue Description

when i run 'npm run android' during the compiling process i get the following errors from react native navigation files
[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\collapsingToolbar\CollapsingTextView.java:
11: error: cannot find symbol
import android.support.v7.widget.TintTypedArray;
^
symbol: class TintTypedArray
location: package android.support.v7.widget

[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\SideMenu.java:
47: error: cannot find symbol
removeDrawerListener(sideMenuListener);
^
symbol: method removeDrawerListener(SimpleDrawerListener)
location: class SideMenu

[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\SideMenu.java:
56: error: cannot find symbol
removeDrawerListener(sideMenuListener);
^
symbol: method removeDrawerListener(SimpleDrawerListener)
location: class SideMenu

[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\SideMenu.java:
84: error: incompatible types: int cannot be converted to boolean
openDrawer(side.gravity, animated);
^
[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\SideMenu.java:
96: error: incompatible type
s: int cannot be converted to boolean
closeDrawer(side.gravity, animated);
^
[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\SideMenu.java:
173: error: cannot find symbol
addDrawerListener(sideMenuListener);
^
symbol: method addDrawerListener(SimpleDrawerListener)
location: class SideMenu

[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\FloatingActionButtonCoordinator.java:
181: error: SIZE_MINI has private access in FloatingActionButton
action.setSize(FloatingActionButton.SIZE_MINI);
^
[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\FloatingActionButtonCoordinator.java:
181: error: cannot find symbol
action.setSize(FloatingActionButton.SIZE_MINI);
^
symbol: method setSize(int)
location: variable action of type FloatingActionButton

[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\FloatingActionButtonCoordinator.java:
183: error: cannot find symbol
action.setCompatElevation(0);
^
symbol: method setCompatElevation(int)
location: variable action of type FloatingActionButton
[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\collapsingToolbar\CollapsingTextView.java:
58: error: cannot find symbol
final TintTypedArray a = TintTypedArray.obtainStyledAttributes(getContext(), null,
^
symbol: class TintTypedArray
location: class CollapsingTextView

[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\collapsingToolbar\CollapsingTextView.java:
58: error: cannot find symbol
final TintTypedArray a = TintTypedArray.obtainStyledAttributes(getContext(), null,
^
symbol: variable TintTypedArray
location: class CollapsingTextView

[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\collapsingToolbar\CollapsingTextView.java:
67: error: cannot find symbol
TextViewCompat.setTextAppearance(dummy, titleTextAppearance);
^
symbol: method setTextAppearance(TextView,int)
location: class TextViewCompat

[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\utils\ColorUtils.java:
6: error: cannot find symbol
android.support.v4.graphics.ColorUtils.colorToLAB(color, result);
^
symbol: method colorToLAB(int,double[])
location: class ColorUtils

[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\utils\ColorUtils.java:
11: error: cannot find symbol
return android.support.v4.graphics.ColorUtils.LABToColor(lab[0], lab[1], lab[2]);
^
symbol: method LABToColor(double,double,double)
location: class ColorUtils

[Project path]\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\views\utils\LabColorEvaluator.java:
11: error: cannot find symbol
ColorUtils.blendLAB(from, to, ratio, color);
^
symbol: method blendLAB(double[],double[],float,double[])
location: class **ColorUtils**

### Steps to Reproduce / Code Snippets / Screenshots

npm run android

---
### Environment
* React Native Navigation version: 1.1.466
* React Native version: 0.55.2
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator nexus 5x api 26

**Comment by Hari70a** [comment]
Facing the same issue here
@jerodgers1 Could you please tell me how did you fix this?

**Comment by jerodgers1** [comment]
I don't remember exactly what I did for this one issue because I tried a few issue but I do remember I did this to solve a couple issues I was having so give this a shot. 
```
cd \yourProject\node_modules\react-native-navigation
npm install
```
- then open yourProject\node_modules\react-native-navigation\android folder in android studio and  built it 
- then go back to yourProject folder in android studio and build it.
- then try npm run anndroid
