### ISSUE TITLE
[iOS] Add more detail to iOS installation guide

### ISSUE THREAD

**Issue by rodrigobdz** [wix/react-native-navigation#3304]
On the [installation guide](https://github.com/wix/react-native-navigation/blob/4c76331757590851e2a7719913371f83df491e4e/docs/installation-ios.md) it is advised to replace the current AppDelegate.m with [another file](https://github.com/wix/react-native-navigation/blob/4c76331757590851e2a7719913371f83df491e4e/example/ios/example/AppDelegate.m). 
What are exactly the needed changes in [AppDelegate.m](https://github.com/wix/react-native-navigation/blob/4c76331757590851e2a7719913371f83df491e4e/example/ios/example/AppDelegate.m)?
The current approach is too radical.

**Comment by guyca** [comment]
Perhaps comparing the example's [AppDelegate](https://github.com/wix/react-native-navigation/blob/master/example/ios/example/AppDelegate.m) to yours will help.

**Comment by rodrigobdz** [comment]
@guyca That was *very* helpful.
