### ISSUE TITLE
[v2] Recommended way of customizing launch image?

### ISSUE THREAD

**Issue by Dexwell** [wix/react-native-navigation#3305]
As of v2, what's the recommended way of customizing the splash/launch screen? Specifically talking about iOS for the time being. Currently the screen is white until the first screen is faded in. 

How can we change the launch image and optionally disable the fade?

**Comment by Dexwell** [comment]
@yogevbd What's your recommendation here? Most online solutions require replacing `(UIApplication *)application didFinishLaunchingWithOptions:`

**Comment by Dexwell** [comment]
@yogevbd Would love to implement a launch image ASAP as I'm nearing launch. How do I set one?

**Comment by yogevbd** [comment]
@Dexwell [Answer here](https://stackoverflow.com/a/35718781/3562020)

**Comment by Dexwell** [comment]
@yogevbd I know we can use the Asset Catalog, there's two problems however:

1) For iPhone X the launch image remains solid white (not sure if RNN-related)
2) There's a brief white flash (black on iPhone X) between the Asset catalog launch image and the first screen (the statusbar also goes dark even though I set it to light using `UIStatusBarStyle` in Info.plist). I assume this is caused by RN(N) loading.    

    Is there any way you guys on the native side could make it so that the launch image and UIStatusBarStyle are not changed until the first RNN screen has loaded? This is some critical functionality impacting the UX of every app using RNN. 

    Like I wrote before, online solutions require messing around with `rootView` (keep it visible until React Native has loaded), but when using RNN this is impossible since we have to replace everything related to `rootView` with:

```objc
NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
     [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];
```

**Comment by eightyfive** [comment]
I can confirm point 2. of @Dexwell, I also see a brief white screen on iPhone X simulator between [XCode native splash screen](https://medium.com/handlebar-labs/how-to-add-a-splash-screen-to-a-react-native-app-ios-and-android-30a3cec835ae) and first RNN app screen.
