### ISSUE TITLE
Different color of selected Tab item in Android

### ISSUE THREAD

**Issue by kirtishjain** [wix/react-native-navigation#3308]
### Issue Description

Hi, 
I want to display active Tab Item in different color while user taps on it.
For e.g. If I have 2 Tabs 
1.) Men
2.) Women

Then If 'Men' tab selected then it needs to be in Blue color while 'Women' is in gray color by default
and if 'Women' tab selected then it needs to be in Pink color  while 'Men' is in gray color by default.

I've made a hack for this in iOS in RCCTabBarController.m class.
How could I achieve it same behavior in ANDROID? Is there any hack for this?

It's really urgent. Please help me out.

Thanks in advance.

---
### Environment
* React Native Navigation version: 1.1.457
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by guyca** [comment]
@kirtishjain RNN uses [AHBottomNavigation](https://github.com/aurelhubert/ahbottomnavigation) and as far as I know, is doesn't support this use case.

**Comment by kirtishjain** [comment]
@guyca Is there any hacking solution in Android as i did manage in iOS by setting hard-code colors in **RCCTabBarController.m**?

**Comment by kirtishjain** [comment]
@guyca I did manage to hack it in Android as well by modifying setStyleFromScreen() function of BottomTabs.java file.

And the hacking solution is as following:

`if (params.selectedBottomTabsButtonColor.hasColor()) {
//             if (getAccentColor() != params.selectedBottomTabsButtonColor.getColor()) {
//                 setAccentColor(params.selectedBottomTabsButtonColor.getColor());
                 if (this.getCurrentItem() == 0) {
                     setAccentColor(Color.rgb(1, 39, 108));
                 }
                 else {
                     setAccentColor(Color.rgb(221, 0, 108));
                 }
//             }
         }`

Please make sure you set `this.setCurrentItemWithoutInvokingTabSelectedListener(1);` in addTabs() function of BottomTabs.java file after for loop.
