### ISSUE TITLE
Screens lifecycle current/nextScreen

### ISSUE THREAD

**Issue by Crash--** [wix/react-native-navigation#331]
I know that by design when we push a new screen, you keep alive the previous screen in order to make the navigation more reactive. 

But I've two screens connected to the same redux container and I would like to be able to put a condition in my screen to do nothing when it is not the current one. As the componentWillUnmount is not called, we can't use it. 

Something like : 
```javascript 
componentWillReceiveProps(nextProps){
if(this.props.navigator.currentScreen === nextProps.navigator.currentScreen){
props.navigator.push({myNewScreen});
}
```

Actually I'm dispatching an action to deal with, don't know if it's the right choice but it's working.

**Comment by guyca** [comment]
@Crash-- Sadly we're also dispatching actions to notify screens they are not visible. Lifecycle events for screens is a feature we plan for the upcoming [v2 release](https://github.com/wix/react-native-navigation/issues/120).
Now that `react-native-controllers` has been merged into this project, This feature is our top priority. 

If it's ok with you I'm closing this issue, let's keep the discussion in #120.

**Comment by Crash--** [comment]
Thank you for your answer @guyca. 

#120 Sounds good, but it's not only for Android ;).
