### ISSUE TITLE
Is it possible to override/change back "swipe" behavior on iOS?

### ISSUE THREAD

**Issue by EdwardDrapkin** [wix/react-native-navigation#3314]
hey there,

I'm still on v1, and I'm also wondering whether it's possible to disable the back swipe behavior or, ideally override it with custom functionality.  I'm talking about when you swipe in from the left and it pops off the navigator stack, I'd like to override that.

Thanks!

**Comment by EdwardDrapkin** [comment]
I found this issue: https://github.com/wix/react-native-navigation/issues/2197 for handling Android but nothing has come up for iOS.

**Comment by rampazzo1989** [comment]
I'm facing the same situation, any solution?
