### ISSUE TITLE
Tried to use permissions API while not attached to an Activity.

### ISSUE THREAD

**Issue by vanlooverenkoen** [wix/react-native-navigation#3316]
### Issue Description

Tried to use permissions API while not attached to an Activity.
I am using react-native-navigation to start a Tab Navigation. In one of the tabs I request permission to read Contacts. with this code:

```
  getContacts = async () => {
    const resp = await PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.READ_CONTACTS);
    console.warn("Permission => " + resp);
    if (resp) {
      console.warn("GET ALL CONTACTS");
    } else {
      try {
        const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_CONTACTS);
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
          console.warn("GET ALL CONTACTS");
        } else {
          console.warn("PERMISSION DENIED");
        }
      } catch (err) {
        console.warn(err);
      }
    }
  }

```
The permissions dialog is shown. But when I press allow or deny. The app crashes with this error
`Tried to use permissions API while not attached to an Activity.`

How can I handle this issue?

### Steps to Reproduce / Code Snippets / Screenshots

Create a tab navigation and in the first tab request permission in the componentDidMount.

---
### Environment
React Native Navigation version: 1.1.406
React Native version: 0.52.2
Platform(s) (iOS, Android, or both?): Android
Device info (Simulator/Device? OS version? Debug/Release?): Simulator, device, any OS, any buildType.

**Comment by vanlooverenkoen** [comment]
I currently use a timeout of 500 ms. and everything works fine. But the crash happens from an Activity but yet it is not attached to an activity. makes no sense
![image](https://user-images.githubusercontent.com/21172855/41097498-75b2c326-6a58-11e8-86df-7e8f80e6d9f5.png)

**Comment by garrottkai** [comment]
This is happening for me when requesting location permissions

**Comment by hugows** [comment]
I had to go into "App info" (Android emulator) and then concede Location permissions manually - but the app never asked for them. Now the app works... (in debug/dev still).

**Comment by heron2014** [comment]
I am having the same issue with location permission. I am using react-native-navigation version 1, would that mean the issue is resolved in version 2?

Did you resolve it @garrottkai?

**Comment by amin3mej** [comment]
Any update???

**Comment by umerbaig** [comment]
facing same issue

**Comment by thekundankamal** [comment]
Hi,
Still, this issue is happening I notice that If I am putting the permission code on the componentDidMount() method then this is happenig. But it works with setTimeout() but I don't think it is the correct way. Looking for help.

>   componentDidMount() {
>       this.requestLocationPermission();
>   }

**Comment by tkyr-hh** [comment]
I am using react-native-location library and this issue is happening to me because I am trying to request for location permission outside of the App.js (entry point of the App). I think, if you place permission requests in the useEffect or useLayoutEffect hooks  the error will go away.
