### ISSUE TITLE
Error when start startTabBasedApp ?

### ISSUE THREAD

**Issue by viper4595** [wix/react-native-navigation#3329]
### Issue Description

When i call startTabBasedApp on iOS, the error show **JSON value '<null>' of type NSNull cannot be converted to an image. Did you forget to call resolveAssetSource() on the JS side?**.

The error only happens on ios.

### Steps to Reproduce / Code Snippets / Screenshots

Just call startTabBasedApp() in app root, it works fine with startSingleScreenApp() with the same 'screen'.

![image](https://user-images.githubusercontent.com/21328574/41190407-07d138d6-6c08-11e8-98b4-81af96eb85a4.png)

---
### Environment
* React Native Navigation version: 1.1.464
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator-OS: 11.2-Debug

**Comment by viper4595** [comment]
Solved: My faults, i set the wrong icon's name for selectedIcon.

**Comment by witalobenicio** [comment]
I'm facing the same problem from the latest version of v1

**Comment by RCTnativeapp** [comment]
I am also getting similar error. Any clue please
