### ISSUE TITLE
[android] BUILED FAILED while executing run-andoid

### ISSUE THREAD

**Issue by kanzitdinov** [wix/react-native-navigation#333]
### Issue Description

I have a problem when I try to compile the project for Android. For iOS everything is good.

### Steps to Reproduce / Code Snippets / Screenshots

1. react-native run-android
2. I get this message in the console
```
:react-native-navigation:compileReleaseJavaWithJavac
/Users/***/app/ExampleApp/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java:77: error: method onActivityResult in class ReactInstanceManager cannot be applied to given types;
        getReactInstanceManager().onActivityResult(requestCode, resultCode, data);
                                 ^
  required: Activity,int,int,Intent
  found: int,int,Intent
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-navigation:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

---
### Environment
* React Native Navigation version: ^2.0.0-experimental.126
* React Native version: 0.33.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device (6.0.1) and the same for Simulator

**Comment by liuzhen2008** [comment]
you can downgrade your react native version to 0.32.1 and it will work.

see #306

**Comment by kanzitdinov** [comment]
Thank you so much! Didn't see that issue :)
