### ISSUE TITLE
Weird problem with WebView in react native navigation V1 

### ISSUE THREAD

**Issue by AE0011** [wix/react-native-navigation#3334]
### Issue Description
I have a screen which contain a WebView component it's works fine but if I pop screen then the problem shows itself... the background color of all modals and light boxes would be transparent also background in some buttons and tabs...

### Steps to Reproduce / Code Snippets / Screenshots
My webView: 
 ```
<View style={{flex: 1}}>
      <WebView
             source={{uri: this.props.url}}
             />
</View>
```
---
### Environment
* React Native Navigation version:     "react-native-navigation": "^1.1.463",
* React Native version:     "react-native": "^0.51.0",
* Platform(s) (iOS, Android, or both?): Android ( Ios unknown )
* Device info (Simulator/Device? OS version? Debug/Release?): Android device OS 5

**Comment by Tyouzi** [comment]
this.props.navigator.push({
*********
animated: false
});

if you want to  push some screen with webview , just add animated:false

**Comment by Tyouzi** [comment]
this.props.navigator.push({
*********
animated: false
});

if you want to  push some screen with webview , just add animated:false
