### ISSUE TITLE
Android build problem where system language uses both of the "I" and "İ" letters 

### ISSUE THREAD

**Issue by yusufkinatas** [wix/react-native-navigation#3335]
### Issue Description
  
I am trying to build a project on android simulator. The part below is a problem for OS's which system language uses both of the "I" and "İ" letters 
 `testLogging {
    events "passed", "skipped", "failed", "standardOut", "standardError"
}`

I can solve this problem temporarily by changing
 `events "passed", "skipped", "failed", "standardOut", "standardError"`
 to 
`events "passed", "SKIPPED", "FAILED", "standardOut", "standardError"`

![resim](https://user-images.githubusercontent.com/39553853/41203367-79f26224-6cde-11e8-8bdb-e175af20f0b9.png)

react-native-navigation\android\app\build.gradle:

![resim](https://user-images.githubusercontent.com/39553853/41203454-b56a1bfc-6cdf-11e8-9167-a6ae5a2624d5.png)

### Steps to Reproduce / Code Snippets / Screenshots

* Set system language to Turkish
* Initialize a project with react-native-navigation
* Try `react-native run-android` 

---
### Environment
* React Native Navigation version: 0.55.4
* React Native version: 1.1.471
* Platform: Android
* Device info : Simulator/ Build Tools Version '26.0.2'/ Compile Sdk Version 26/ Debug

**Comment by DanielZlotin** [comment]
Interesting. Apparently [this is a bug in gradle](https://github.com/gradle/gradle/issues/2661).
I pushed your suggested fix to v2.
