### ISSUE TITLE
Sort BottomTabs options 

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#3341]
# iOS
- [x] remove tabColor from bottomTabs
- [x] remove unselectedTabColor from bottomTabs
- [x] move font options from bottomTabs to bottomTab
- [x] remove disableIconTint from bottomTab
- [x] remove disableSelectedIconTint from bottomTab
- [x] Set selected  iconColor in bottomTab
- [x] Set selected  textColor in bottomTab
- [x] Set iconColor in bottomTab
- [x] Set textColor in bottomTab
- [x] Don't set system colors on icons

# Android
- [x] remove tabColor from bottomTabs
- [x] remove unselectedTabColor from bottomTabs
- [x] move font options from bottomTabs to bottomTab
- [x] Set selected  iconColor in bottomTab
- [x] Set selected  textColor in bottomTab
- [x] Set iconColor in bottomTab
- [x] Set textColor in bottomTab

```js
bottomTab: {
  icon: require('icon.png'), // Unselected
  selectedIcon: require(), // Optional, iOS only
  iconColor: 'red', // unselected color
  selectedIconColor: 'green',
  text: 'Tab 1',
  textColor: 'red', // Unselected color
  selectedTextColor: 'green',
  fontFamily: 'Helvetica',
  fontSize: 13
}
```
- [x] Update documentation

**Comment by yogevbd** [comment]
https://github.com/wix/react-native-navigation/issues/3341

**Comment by sJJdGG** [comment]
>  move font options from bottomTabs to bottomTab

@guyca  Are you sure about this?
As far as i know at this moment these options are not implemented for android yet. (RNN V2.0.2348)

bottomTabs Options:
![bottomTabs Options](https://i.imgur.com/i6ygSoz.png)

And they'r not implemented in bottomTab options either.
bottomTab Options:
![bottomTab Options](https://i.imgur.com/SCZJTbd.png)

An edit for original comment and Docs to indicate they're IOS only for now would be nice.
As you can see i found it myself the hard way.
