### ISSUE TITLE
[V2] component layouts as bottomTabs children are not visible

### ISSUE THREAD

**Issue by sJJdGG** [wix/react-native-navigation#3345]
### Issue Description

adding components to bottomTabs children make them not be visible although stack children work as expected.

### Steps to Reproduce / Code Snippets / Screenshots

In playground app root folder replace existing code in index.js with the following. (It's the same example as mentioned in the docs for bottomTabs).
```js
import React, { Component } from 'react';
import { View, Text } from 'react-native';
import { Navigation } from 'react-native-navigation';

class Test extends Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Test Screen</Text>
      </View>
    );
  }
}

Navigation.registerComponent('Test', () => Test);

Navigation.setRoot({
  root: {
    bottomTabs: {
      children: [
        {
          stack: {
            children: [
              {
                component: {
                  name: 'Test'
                }
              }
            ],
            options: {
              bottomTab: {
                title: 'Tab 1',
                icon: require('./images/one.png'),
              },
            },
          },
        },
        {
          component: {
            name: 'Test',
            options: {
              bottomTab: {
                title: 'Tab 2',
                icon: require('./images/two.png'),
              },
            },
          },
        },
      ],
    },
  },
});

```
In addition to playground app i tried it on a clean init project (Edited as instructed in the docs) and got the same results.

![Screen Cap](https://media.giphy.com/media/1Xamrt2Dwd2u8UC3BD/giphy.gif)
---
### Environment
* React Native Navigation version: 2.0.2344
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): 
Google Pixel 1 Android 8.1 Debug
Genymotion Android Emulator Custom Phone 6.0 Debug

**Comment by jonathanRinciari** [comment]
Yah same issue it seems to be messing with the styling. If you put a hard width/height on the container, and add like a background color it is visable but still doesnt take up the full width/height. I have also had a screen that is half of the width but shows children components

**Comment by FaBeyyy** [comment]
Have the same Issue... currently just using a bunch of stacks with children that have bottomTabs.
