### ISSUE TITLE
Dynamic Tabs

### ISSUE THREAD

**Issue by calcazar** [wix/react-native-navigation#3346]
Is it possible to have dynamic tabs using this library?

The use case is that an regular user gets a different tab bar than an admin level user. This has to happen dynamically as the admin user can toggle back and forth between regular user and admin. 

I've tried calling startTabBasedApp on toggle but it looks like it creates a new instance of the tab instead of just toggling the new tab.

**Comment by devpascoe** [comment]
Would also like to know if dynamic tabs can be rendered eg show list of tabs based on user info.

**Comment by devpascoe** [comment]
I got a solution working using the other React Navigation library but perhaps its technique can be used with this library...

I ended up writing something like this to only load the component once the tab configuration was fetched from an api and saved into a global variable and used state to only show the component once ready.
```
  fetchTabs = async () => {
    const fetchUrl = `urltoapi/menu`
    const response = await fetch(fetchUrl)
    global.tabs = await response.json()
    AppScreen = require('./screens/AppScreen').default
    this.setState({ loadedTabs: true })
  }
```
...and in AppScreen its default returns the createBottomTabNavigator with the tabs object being the result of the following tabs() function
```
const tabs = () => {
  const tabItems = {}
  global.tabs.forEach(tab => {
    if (tab.screen == 'Feed') {
      tabItems['Feed'] = FeedStack
    } else if (tab.screen == 'Chat') {
      tabItems['Chat'] = ChatStack
    } else if (tab.screen == 'Profile') {
      tabItems['Profile'] = MyProfileStack
    } else if (tab.screen == 'Contact') {
      tabItems['Contact'] = ContactScreen
    }
  })
  return tabItems
}
```
So i'm basically doing whatever i can to delay loading and then showing the createBottomTabNavigator until i have prepared the tabs object for it to use since it needs that result returned synchronously.

**Comment by FinnGu** [comment]
> I got a solution working using the other React Navigation library but perhaps its technique can be used with this library...
> 
> I ended up writing something like this to only load the component once the tab configuration was fetched from an api and saved into a global variable and used state to only show the component once ready.
> 
> ```
>   fetchTabs = async () => {
>     const fetchUrl = `urltoapi/menu`
>     const response = await fetch(fetchUrl)
>     global.tabs = await response.json()
>     AppScreen = require('./screens/AppScreen').default
>     this.setState({ loadedTabs: true })
>   }
> ```
> 
> ...and in AppScreen its default returns the createBottomTabNavigator with the tabs object being the result of the following tabs() function
> 
> ```
> const tabs = () => {
>   const tabItems = {}
>   global.tabs.forEach(tab => {
>     if (tab.screen == 'Feed') {
>       tabItems['Feed'] = FeedStack
>     } else if (tab.screen == 'Chat') {
>       tabItems['Chat'] = ChatStack
>     } else if (tab.screen == 'Profile') {
>       tabItems['Profile'] = MyProfileStack
>     } else if (tab.screen == 'Contact') {
>       tabItems['Contact'] = ContactScreen
>     }
>   })
>   return tabItems
> }
> ```
> 
> So i'm basically doing whatever i can to delay loading and then showing the createBottomTabNavigator until i have prepared the tabs object for it to use since it needs that result returned synchronously.

Did your solution hold up to production usage? I am asking because a client wants to dynamically change their tabs (order, description, count, ...) and I am unsure whether this is something I should talk them out of, because it could lead to many problems.
