### ISSUE TITLE
Swipe screen to dissmiss on Android

### ISSUE THREAD

**Issue by trieulh-gotitapp** [wix/react-native-navigation#3349]
It's not an issue but I just want to request a swipe to dismiss feature on Android. Or apologize if this feature is already somewhere but I missed. 
Thanks you guys for awesome lib.
---
### Environment
* React Native Navigation version: 1.1.443
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by guyca** [comment]
You can implement this your self in JS 👍
