### ISSUE TITLE
Expose launchArgs to JS

### ISSUE THREAD

**Issue by rotemmiz** [wix/react-native-navigation#3353]
We want to be able to pass launchArgs to better control the test environment when running Detox. 
We already had that in v1, I guess [this](https://github.com/wix/react-native-navigation/commit/a0d9518117c5397dcdd72e4437918f94151c8ea8) is the original implementation.

Re iOS, this is exactly what we need. on Android I'm not yet sure what would be the best approach, either instrumentation params, intent params, or something else, we should continue the Android discussion.

**Comment by d4vidi** [comment]
@doronpr we'll be able to pass in the device ID via detox

**Comment by rotemmiz** [comment]
@d4vidi , please report back if this solves your issue.

**Comment by drorbiran** [comment]
@yogevbd @rotemmiz It doesn't seem to work.
In my test I'm doing something like
```
    await global.device.launchApp({launchArgs: {arg1: 1, arg2: '2'}});
```
In my project 
```
  const launchArgs = await Navigation.getLaunchArgs();
```
And I'm getting some default props that are not related to what I have passed

**Comment by rotemmiz** [comment]
Can you please paste the part in detox test log showing the `xcrun simctl launch` execution?
Use `--loglevel verbose` to print it

**Comment by rotemmiz** [comment]
The first time is probably detox.init. the he second is your device.launch
It looks ok from Detox perspective, but try to detox.init({launch app: false}) to avoid excessive app launches.

**Comment by drorbiran** [comment]
Didn't work. Do we have any working example of using `Navigation.getLaunchArgs()` that I can take a look at?
