### ISSUE TITLE
using popToRoot() on iOS 8 and  finding a EXC_BAD_ACCESS KERN_INVALID_ADDRESS crash

### ISSUE THREAD

**Issue by 21gSoul** [wix/react-native-navigation#3359]
when i call popToRoot() on iOS 8， i find a EXC_BAD_ACCESS KERN_INVALID_ADDRESS crash,Here is crashlytics report:
![image](https://user-images.githubusercontent.com/20986922/41389688-b7f6b74e-6fc4-11e8-9e15-6885f71247c9.png)
for example, when  page A push to page B , and page B push to C ,then call popToRoot() on page C and it will cash, like this:
![image](https://user-images.githubusercontent.com/20986922/41393775-e2fb0a2a-6fd9-11e8-926a-390d7519bf6f.png)

---
### Environment
* React Native Navigation version: 1.1.462
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 8

**Comment by tayfunyugruk** [comment]
hi @21gSoul if issue is from your test app i think it will be good to test with iOS 9 starting with RN 0.56 will start supporting iOS 9 and will drop support for iOS 8. 

link : https://github.com/facebook/react-native/commit/f50df4f5eca4b4324ff18a49dcf8be3694482b51
