### ISSUE TITLE
[V2] onNavigationButtonPressed is not callback

### ISSUE THREAD

**Issue by a289459798** [wix/react-native-navigation#3364]
### onNavigationButtonPressed is not callback

```
Navigation.push(this.props.componentId,
            {
                component: {
                    name: component,
                    passProps: {
                    },
                    options: {
                        topBar: {
                            leftButtons: [
                                {
                                    id: 'back',
                                    icon: require('../../resource/images/nav_back.png')
                                }
                            ],
                        },
                
                    }
                }
            });

export default class BaseView extends Component<Props> {

    onNavigationButtonPressed(buttonId) {
        console.log(buttonId)
    }
}
```

### Environment
* React Native Navigation version: v2.0.2350
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by maestrolsj** [comment]
same symptom

**Comment by nickofthyme** [comment]
@a289459798 how are you registering your screens? If you are using a HOC for wrapping you screen with a redux `Provider` this may be related to #3322.

**Comment by maestrolsj** [comment]
I am not using Redux and this is my navigation conf.

Navigation.setRoot({
			root: {
				sideMenu: {
					left: {
						component: {
							name: Screens.JHDrawerMenu.name,
							id: Screens.JHDrawerMenu.name,
							passProps: {
								items: tabs,
							},
						},
					},
					center: {
						bottomTabs: {
							children: [
								{
									stack: {
										children: [
											{
												component: {
													name: tabs[0].screen,
													id:   tabs[0].screen
												},
											}
										],
										options: {
											topBar: {
												title: {
													text: tabs[0].title,
												},
											},
										}
									}, 
......
....
