### ISSUE TITLE
[v2] bottomTab(s) fontSize does not work

### ISSUE THREAD

**Issue by FaBeyyy** [wix/react-native-navigation#3369]
### Issue Description
bottomTabs fontSize does not work on Android.

### Steps to Reproduce / Code Snippets / Screenshots
```js
Navigation.setDefaultOptions({
    bottomTabs: {
        fontSize: 14,
    },
});
```
### Environment
* React Native Navigation version: latest
* React Native version: latest
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug/Android 8.1 Device

**Comment by guyca** [comment]
Resolved in `2.0.2402`
```js
options: {
  bottomTabs: {
    fontSize: 13, // font size in sp
    selectedFontSize: 16 // font size in sp
  }
}
```
