### ISSUE TITLE
iOS 10 Title Header Bug

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#337]
### Issue Description

I am using a Tab based app, and I am trying to set one page title to the word "Wallet", but instead I am getting the word "Wall...". It seems like there is not enough space to be show, but this is not correct, because I tried using words with more that 6 letters and they appear correctly.

This happened after I updated Xcode to 8, react-native to 0.31, and iOS simulator to 10. I think I also updated navigation to 2.0.0-experimental.126, but I am not sure 
I was previously using Xcode 7, react-native 0.3, and iOS simulator 9 and didn't have this problem. I am not sure which navigation version I was previously using but I believe I wasn't using 2.0.0-experimental.126.
### Environment
- React Native Navigation version: 2.0.0-experimental.126
- React Native version: 0.31
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): simulator iPhone 6s, iOS 10, Xcode 8

**Comment by quoctuams** [comment]
I'm having the same problem, is there anyway to fix this? Only 1 of my 5 tabs has this issue.

**Comment by perrosnk** [comment]
This problem has disappeared after upgrading to react-native 0.38, navigation 2.0.0-experimental.191.
