### ISSUE TITLE
[v2] topBar customComponent does not work on Android

### ISSUE THREAD

**Issue by FaBeyyy** [wix/react-native-navigation#3370]
### Issue Description

topBar customComponent does not work on Android.
Component is never mounted (render function is never called).

NOTE: topBars title custom component works.
### Steps to Reproduce / Code Snippets / Screenshots
```
Navigation.setDefaultOptions({
    topBar: {
         component: {
                name: 'test.TopBar',
            }
});
```
### Environment
* React Native Navigation version: latest
* React Native version: latest
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Android 8.1 Debug

**Comment by reganperkins** [comment]
Im having the same issue, is anyone else? adding a custom topbar is working in ios but on android it just shows a blank topbar or a back button

**Comment by samcampisi** [comment]
Yes I'm having the same problem. It straight up shows nothing on Android (ios working fine)

**Comment by guyca** [comment]
@reganperkins @samcampisi Can you please add logs to `componentDidMount` and `render` to check if the component is being added and created?
From my experience, this usually happens due to flex/yoga issues

**Comment by samcampisi** [comment]
I added the logs and the component and indeed the component is not being added. Nothing gets printed on componentDidMount.

**Comment by guyca** [comment]
Can you add code snippets? How are you adding the component?

**Comment by samcampisi** [comment]
Just like @FaBeyyy 

`
Navigation.setDefaultOptions({
    topBar: {
         component: {
                name: 'test.TopBar',
            }
});
`

The only way I get this to work is putting the component in the title, but it's not what I'm looking for:

`
Navigation.setDefaultOptions({
    topBar: {
         title: {
             component: {
                name: 'test.TopBar',
            }
         }
});
`

Also I get a strange behaviour on Android while doing this, there's an unwanted padding, impossible to delete (tried giving flex: 1 to the custom title component and yet it's not covering the space)

**Comment by guyca** [comment]
The following api is not supported, it was supposed to be removed from iOS.
```js
Navigation.setDefaultOptions({
  topBar: {
    component: {
      name: 'test.TopBar'
    }
  }
});
```
___
We support adding two types of components to the TopBar:
1. Title component:
```js

Navigation.setDefaultOptions({
  topBar: {
    title: {
      component: {
        name: 'example.CustomTopBarTitle',
        alignment: 'center'
      }
  }
});
```

2. Background component (probably what you need)
```js

Navigation.setDefaultOptions({
  topBar: {
    background: {
      component: {
        name: 'example.CustomTopBarBackground'
      }
    }
  }
});
```

**Comment by spiraltrip** [comment]
How do you remove the background component? I don't want to set the topBar visibility to false, but instead want the default topBar.
