### ISSUE TITLE
Screen component can't be functional

### ISSUE THREAD

**Issue by andy-zy** [wix/react-native-navigation#3371]
### Issue Description

App.js
```
import { Navigation } from 'react-native-navigation';

import { Welcome } from './src/screens';

Navigation.registerComponent('navigation.WelcomeScreen', () => Welcome);

...
````

Weclome.js
```
import React from 'react';
import {
	StyleSheet,
	Text,
	View
} from 'react-native';

const Welcome = () => {
	return (
		<View style={styles.container}>
			<Text>
				Welcome Screen
			</Text>
		</View>
	);
};

const styles = StyleSheet.create({
	container: {
		flex: 1,
	},
});

export default Welcome;
```

![screenshot_1529248546](https://user-images.githubusercontent.com/6594975/41509318-9042b570-725a-11e8-8847-0d39c1274133.png)

---
### Environment
* React Native Navigation version: alpha
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator,

**Comment by ujwal-setlur** [comment]
Umm, what else is in your App.js? Where is your ```setRoot()```, ```Navigation.events().registerAppLaunchedListener```, etc?
