### ISSUE TITLE
pass props between bottom tabs

### ISSUE THREAD

**Issue by rheng001** [wix/react-native-navigation#3372]
### Issue Description

How can I pass props from one tab to another ? I've tried passProps used in the normal navigation but it doesn't work.

### Steps to Reproduce

> this.props.navigator.switchToTab({
  tabIndex: 2,
  // // Pass data on click
  // passProps: {
  //   desc: data
  // }
});

---
### Environment
* React Native Navigation version: 1.1.463
* React Native version: 0.55.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Android 7.0

**Comment by AniketMalik** [comment]
Any one on passing the props between tabs?

**Comment by kirtishjain9** [comment]
Hi All,

I would need the same kind of functionality of passing data from one tab to another.

Does anyone find the solution for this?

**Comment by DavitVosk** [comment]
Any update here?

**Comment by dfattlar** [comment]
+1   Also interested in passing props as part of mergeOptions tab change. 
My scenario is:
- User presses button in component on tab 1, calling mergeOptions tab change
- User is navigated to tab 2, component in tab 2 triggers componentDidAppear
Currently in this scenario, passProps are empty.

**Comment by manjeets12** [comment]
We can simple use 
`Navigation.updateProps(this.props.componentId, YOUR_PROPS_OBJECT)`
this is not documented at the moment, but work perfectly for me.

**Comment by MakhouT** [comment]
@manjeets12 `Navigation.updateProps` Worked perfectly for me! Thanks for the suggestion!
