### ISSUE TITLE
When no title, I hope to icon vertical center

### ISSUE THREAD

**Issue by hengkx** [wix/react-native-navigation#3374]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]
![image](https://user-images.githubusercontent.com/8358236/41543596-b0a4b918-7349-11e8-9b6a-149d18d0ca85.png)

---
### Environment
* React Native Navigation version: 1.1.471
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator MAC

**Comment by guyca** [comment]
Hey @hengkx 
You can use the `iconInsets` option to adjust the icon position.

```js
bottomTab: {
    iconInsets: { top: 0, left: 0, bottom: 0, right: 0 },
}
```
