### ISSUE TITLE
v2: Using React Component for leftButtons crashes on Android

### ISSUE THREAD

**Issue by ujwal-setlur** [wix/react-native-navigation#3375]
### Issue Description

When using a React component for the leftButtons on Android, the app crashes. When I use the same component for the right button, it works.

### Steps to Reproduce / Code Snippets / Screenshots

```js
    Navigation.setDefaultOptions({
      topBar: {
        title: {
          color: "rgba(60, 109, 240, 0.87)",
          fontFamily: "Nunito-Bold",
          fontSize: 18
        },
        rightButtons: [ // this crashes the app on Android
          {
            id: "sideMenuButton",
            component: {
              name: "IconButton",
              passProps: {
                name: "menu",
                size: 30,
                color: "blue"
              }
            }
          }
        ]
      }
    });
```

---
### Environment
* React Native Navigation version: v2
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug

**Comment by guyca** [comment]
Hey @ujwal-setlur 
Please add crash logs when opening an issue regarding a crash 👍 
React components are not supported for left buttons on Android at the moment.
