### ISSUE TITLE
v2: missing PermissionAwareActivity implementation

### ISSUE THREAD

**Issue by serjek** [wix/react-native-navigation#3376]
### Issue Description

`NavigationActivity` is missing `PermissionAwareActivity` interface, this makes other libraries that require permissions (e.g camera or image library) impossible to use, as they crash at runtime.

### Steps to Reproduce / Code Snippets / Screenshots

* Install https://github.com/ivpusic/react-native-image-crop-picker/ along with RNN and try to open camera.
---
### Environment
* React Native Navigation version: v2
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by serjek** [comment]
This is easy to fix at runtime, let me know if you require a PR

**Comment by sapjax** [comment]
@serjek 
https://github.com/wix/react-native-navigation/issues/3283
They need a PR.

**Comment by serjek** [comment]
since it's merged to v2 I'm closing the issue.
