### ISSUE TITLE
Android APP Crash When Using version  2.0.0-experimental.126

### ISSUE THREAD

**Issue by wengcan** [wix/react-native-navigation#338]
I had tested the example android app, if using version 2.0.0-experimental.126, i would cause crash in both emulator and real device. version 2.0.0-experimental.125 is fine.
Here is  the log

> I/ActivityManager( 2880): Start proc 8956:com.example/u0a16 for activity com.example/.MainActivity
I/art     ( 8956): Late-enabling -Xcheck:jni
W/art     ( 8956): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
E/VdcInflateDelegate( 8956): Exception while inflating <vector>
E/VdcInflateDelegate( 8956): java.lang.RuntimeException: Failed to resolve attribute at index 1
E/VdcInflateDelegate( 8956): 	at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
E/VdcInflateDelegate( 8956): 	at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:518)
E/VdcInflateDelegate( 8956): 	at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
E/VdcInflateDelegate( 8956): 	at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
E/VdcInflateDelegate( 8956): 	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:708)
E/VdcInflateDelegate( 8956): 	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:348)
E/VdcInflateDelegate( 8956): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
E/VdcInflateDelegate( 8956): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:181)
E/VdcInflateDelegate( 8956): 	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:689)
E/VdcInflateDelegate( 8956): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
E/VdcInflateDelegate( 8956): 	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
E/VdcInflateDelegate( 8956): 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:83)
E/VdcInflateDelegate( 8956): 	at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
E/VdcInflateDelegate( 8956): 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
E/VdcInflateDelegate( 8956): 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
E/VdcInflateDelegate( 8956): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:193)
E/VdcInflateDelegate( 8956): 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:173)
E/VdcInflateDelegate( 8956): 	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:511)
E/VdcInflateDelegate( 8956): 	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
E/VdcInflateDelegate( 8956): 	at com.reactnativenavigation.controllers.SplashActivity.onCreate(SplashActivity.java:17)
E/VdcInflateDelegate( 8956): 	at android.app.Activity.performCreate(Activity.java:6063)
E/VdcInflateDelegate( 8956): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
E/VdcInflateDelegate( 8956): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437)
E/VdcInflateDelegate( 8956): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2546)
E/VdcInflateDelegate( 8956): 	at android.app.ActivityThread.access$800(ActivityThread.java:154)
E/VdcInflateDelegate( 8956): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
E/VdcInflateDelegate( 8956): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/VdcInflateDelegate( 8956): 	at android.os.Looper.loop(Looper.java:135)
E/VdcInflateDelegate( 8956): 	at android.app.ActivityThread.main(ActivityThread.java:5453)
E/VdcInflateDelegate( 8956): 	at java.lang.reflect.Method.invoke(Native Method)
E/VdcInflateDelegate( 8956): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/VdcInflateDelegate( 8956): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952)
E/VdcInflateDelegate( 8956): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
E/AndroidRuntime( 8956): FATAL EXCEPTION: main
E/AndroidRuntime( 8956): Process: com.example, PID: 8956
E/AndroidRuntime( 8956): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.example.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime( 8956): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2484)
E/AndroidRuntime( 8956): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2546)
E/AndroidRuntime( 8956): 	at android.app.ActivityThread.access$800(ActivityThread.java:154)
E/AndroidRuntime( 8956): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
E/AndroidRuntime( 8956): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 8956): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 8956): 	at android.app.ActivityThread.main(ActivityThread.java:5453)
E/AndroidRuntime( 8956): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8956): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 8956): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952)
E/AndroidRuntime( 8956): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
E/AndroidRuntime( 8956): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime( 8956): 	at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:343)
E/AndroidRuntime( 8956): 	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
E/AndroidRuntime( 8956): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:268)
E/AndroidRuntime( 8956): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:145)
E/AndroidRuntime( 8956): 	at com.reactnativenavigation.controllers.SplashActivity.setSplashLayout(SplashActivity.java:48)
E/AndroidRuntime( 8956): 	at com.reactnativenavigation.controllers.SplashActivity.onCreate(SplashActivity.java:18)
E/AndroidRuntime( 8956): 	at android.app.Activity.performCreate(Activity.java:6063)
E/AndroidRuntime( 8956): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
E/AndroidRuntime( 8956): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437)
E/AndroidRuntime( 8956): 	... 10 more
W/ActivityManager( 2880):   Force finishing activity 1 com.example/.MainActivity

**Comment by guyca** [comment]
Fixed in v2.0.0-experimental.127.
Thanks for reporting @wengcan
