### ISSUE TITLE
[V2] [Android] statusBar drawBehind: true make topBar draw behind statusBar

### ISSUE THREAD

**Issue by sapjax** [wix/react-native-navigation#3380]
### Issue Description

set options:
```
statusBar: {
   drawBehind: true,
}
```

it will make topBar drawn behind statusBar, I think this does not make sense.
The expected effect is : 
If topBar is visible, topBar should not be drawn behind statusBar.
If topBar is not visible, the screen should be drawn behind statusBar.

---
### Environment
* React Native Navigation version: "2.0.2334"
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device

**Comment by sapjax** [comment]
Or there is another solution:  set the topBar height more than title height, but I don't know how to set paddingTop for topBar?

**Comment by guyca** [comment]
Hey @sapjax 
StatusBar.drawBehind will make the layout draw behind the statusBar, therefor it's mostly used for modals.
If you'd like to draw a screen pushed to a stack behind the status bar, you might want to set `topMargin` to some of your screens.

```js
layout: {
  topMargin: Navigation.constants().statusBarHeight // Or any other number
}
```

**Comment by sapjax** [comment]
@guyca Thanks, I will try it.

**Comment by sapjax** [comment]
@guyca  
The `topMargin` does not work as expected.
The `topBar` is still drawn under the `statusBar`.
I think this does not make the scene.

**Comment by sapjax** [comment]
The behavior is not keeping the same as v1 and iOS.

**Comment by legion-zver** [comment]
@guyca Can you read? The problem is in Topbar, it should get bigger in size and have padding on top (with StatusBar.drawBehind = true)!!! What a indifferent!

**Comment by makirby** [comment]
Any update on this? The `topMargin: ` property on layout does not seem to do anything in this situation.

Cheers

**Comment by djschilling** [comment]
I have the same problem.

Tried all the suggestions but the top Bar still draws behind the status bar.

**Comment by sapjax** [comment]
@djschilling   I migrated to React-Navigation one month ago, everything works fine.

**Comment by mayconmesquita** [comment]
I fixed that using: 

`Navigation.setDefaultOptions({ topBar: {
  topMargin: 25,
} });`

**Comment by dreamhb** [comment]
@mayconmesquita 
But screen will be covered by the TopBar, how do you fix that ?

**Comment by mayconmesquita** [comment]
@dreamhb I created a HOC and putted a view with a padding (paddingTop: 25). Or, you can add padding over all screens (will require more effort)
