### ISSUE TITLE
v2: passProps need to be passed in different places for custom buttons on Android and iOS

### ISSUE THREAD

**Issue by ujwal-setlur** [wix/react-native-navigation#3382]
### Issue Description

When creating a custom topBar right button with a React component, it seems passing props is different between iOS and on android. For iOS, I have to pass it outside the component structure, while for android, I have to pass it within the component structure.

### Steps to Reproduce / Code Snippets / Screenshots

```js
        rightButtons: [
          {
            id: "righButton",
            component: {
              name: "IconButton",
              passProps: { // android needs it here
                name: "menu",
                size: 30,
                color: "rgba(60, 109, 240, 0.87)",
                onPress: () => {
                  console.log("button pressed!");
                }
              }
            },
            passProps: { // iOS needs it here
              name: "menu",
              size: 30,
              color: "rgba(60, 109, 240, 0.87)",
              onPress: () => {
                console.log("button pressed!");
              }
            }
          }
        ]
```

---
### Environment
* React Native Navigation version: 0.55.4
* React Native version: latest v2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): simulator

**Comment by yogevbd** [comment]
This is how it will work now in both platforms:
```
{
  id: "righButton",
  component: {
    name: "IconButton",
    passProps: {
      name: "menu"
    }
  }
}
```

 thanks!
