### ISSUE TITLE
[V2] [Android] RN 0.56 Issue

### ISSUE THREAD

**Issue by stephenheron** [wix/react-native-navigation#3387]
Hi,

I am starting a new project so I thought I would use React Native 0.56 RC2 as a starting point. I am having difficulty in getting React Native Navigation setup on Android. I followed the instructions but when I am running a gradle build I am getting a error. 

```
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.4.0) from [com.android.support:design:25.4.0] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:appcompat-v7:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.
```
I am unsure if this is related to 0.56 but what makes me think it might be is the fact that as part of 0.56 this commit was included (https://github.com/facebook/react-native/commit/065c5b6590de18281a8c592a04240751c655c03c) which upgrades some of the support libraries to 26. 

---
### Environment
* React Native Navigation version: 2.0.2359
* React Native version: 0.56.0-rc.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): N/A

**Comment by sytolk** [comment]
I have the same issue:
```
Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.4.0) from [com.android.support:design:25.4.0] AndroidManifest.xml:28:13-35
	is also present at [com.android.support:appcompat-v7:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at manifestMerger8863698996077032328.xml:26:9-28:38 to override.

```
ext {
    compileSdkVersion = 27
    buildToolsVersion = '27.0.3'
    support_version = '27.0.2'
}
resolutionStrategy {
        force "com.android.support:support-annotations:$support_version"
        force "com.android.support:support-v4:$support_version"
        force "com.android.support:support-v13:$support_version"
        force "com.android.support:appcompat-v7:$support_version"
        force "com.android.support:recyclerview-v7:$support_version"
        force "com.android.support:design:$support_version"
        force 'com.squareup.okhttp3:okhttp:3.10.0'
    }

**Comment by sapjax** [comment]
Your other package has the `com.android.support:*` with version 25.4.0.
I found the all 25.4.0 and replace it with 26.1.0.
then it works.
