### ISSUE TITLE
[V2][Android] componentDidAppear didn't trigger when switch tab

### ISSUE THREAD

**Issue by sapjax** [wix/react-native-navigation#3394]
### Issue Description

When I switch tab, I found the `componentDidAppear` lifecycle I defined in the screen component is not triggered,  same as the `componentDidDisappear` event.

---
### Environment
* React Native Navigation version: 2.0.2361
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device

**Comment by guyca** [comment]
Hey @sapjax 
Seems to work fine in the example app. If you still think this is a bug, please PR a failing Detox are unit test 👍

**Comment by sapjax** [comment]
@guyca
This issue does not occur every time. sometimes work, sometimes not.
But there is no problem on iOS.

**Comment by guyca** [comment]
Hey @sapjax, Not sure I can help if we don't have a solid reproduction.

**Comment by svenlombaert** [comment]
I have the same problem when pushing a screen. Sometimes it triggers, sometimes it doesn't. Very hard to reproduce ofcourse.
