### ISSUE TITLE
[V2] Global event Listener and SideMenu disable bug

### ISSUE THREAD

**Issue by maestrolsj** [wix/react-native-navigation#3397]
### Issue Description

It's about  Global event Listener and SideMenu disable bug.
 
### Steps to Reproduce / Code Snippets / Screenshots

1. **Global** events()  are not called (only Android)   in  index.js
    
```javascript
import { Navigation } from 'react-native-navigation';
import registerScreens, { Screens } from './app/lib/RegisterScreens';
import NavigationHelper from './app/lib/navigationHelper';
import { 
	Keyboard,
} from 'react-native';

registerScreens();
Navigation.events().registerAppLaunchedListener(() => {
	NavigationHelper.startSingleScreenApp(Screens.WaitSplashScreen.name);
});

Navigation.events().registerComponentDidAppearListener((componentId, componentName) => {
	switch (componentId) {
	case Screens.VoteList.name : case Screens.ApplicationList.name : case Screens.ChatList.name : case Screens.SettingsView.name :
		Navigation.mergeOptions(Screens.JHDrawerMenu.name, {
			sideMenu: {
				left: {
					visible: false,
					enabled: true
			  }
			},
	  });
	  break;
	}
});

// for Keboard Dissmiss whenever sideMenu is opened.
Navigation.events().registerCommandListener((name, params) => {
	if (name == 'mergeOptions') {
		if (params.options.sideMenu != undefined && params.options.sideMenu.left.visible)	{
			Keyboard.dismiss();
		}
	}
});
```

2. **SideMenu** Disable doesn't work (Android)

```javascript
Navigation.mergeOptions(componentID, {
			sideMenu: {
				left: {
					visible: false,
					enabled: true
			  }
			},
	  });
```
 
3. SideMenu is not fully opened  (IOS)
    * The contents inside SideMenu is situated in center now

![screen shot 2018-06-20 at 15 44 47](https://user-images.githubusercontent.com/16445243/41662314-1d4d55fe-74a1-11e8-9c11-6325c11192e0.png)

### Environment
* React Native Navigation version:  2.0.23yar61
* React Native version: "0.53.0",
* Platform(s) (iOS, Android, or both?): Android , IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulater , Debug

**Comment by ujwal-setlur** [comment]
Please show appropriate code snippets. Something like this works just fine for me on android and iOS:

```js
  Navigation.events().registerNativeEventListener((event, params) => {
    // check we pressed our drawer button
    if (event === "buttonPressed" && params && params.buttonId === "drawer") {
      Navigation.mergeOptions("drawer", {
        sideMenu: {
          left: {
            visible: true
          }
        }
      });
    }
  });
```

**Comment by maestrolsj** [comment]
It is triggered inside component but It is not triggered in index.js globaly . (only Android doesn't work)

**Comment by ujwal-setlur** [comment]
Can you please show a snippet of where you are declaring the listener? It seems to be pretty sensitive to where some of these are declared. I have noticed that causes discrepancies between iOS and Android

**Comment by maestrolsj** [comment]
I declared that code in the index.js file  since I want to use it as  a Global listener. 
IOS works well.. only Android has that issues.  most of all SideMenu disable doesn't work

**Comment by billel-boudchicha** [comment]
@maestrolsj did you managed to solve the issue ?
thank you
