### ISSUE TITLE
React Native Navigation V2 undefined is not a function

### ISSUE THREAD

**Issue by joecaraccio** [wix/react-native-navigation#3398]
Hi Everyone,
I can't figure out this issue out, everytime..regardless of the function I try to use RNN I get the error:

undefined is not a function (evaluating '_reactNativeNavigation.Navigation.events')

Pretty positive everything all dependencies are linked and properly installed. Has anyone else had this issue?

**Comment by dorthwein** [comment]
I'm running into this as well with the react-native-navigation-v1-v2-adapter

**Comment by taxidermic** [comment]
same on rnn v2 with react-native 0.55.0, 0.55.3
@joecaraccio any success?

**Comment by arapocket** [comment]
Same issue.
