### ISSUE TITLE
Swipe-back gesture triggers Touchablehighlight

### ISSUE THREAD

**Issue by alidawud** [wix/react-native-navigation#340]
### Issue Description

Swipe-back gesture triggers Touchablehighlight on iOS.
*I don't have this issue with RN-Navigation 1.x.x.
### Screenshots

[https://youtu.be/sD8GesuPpN8](https://youtu.be/sD8GesuPpN8)

---
### Environment
- React Native Navigation version: 2.0.0-experimental.127
- React Native version: 0.33
- Platform: iOS
- Device info: Device / iOS 10 / Debug

**Comment by wlei-fx** [comment]
did you solve this problem?
