### ISSUE TITLE
[V2][iOS] area above bottomTabs flicker issue

### ISSUE THREAD

**Issue by jjbeach** [wix/react-native-navigation#3407]
### Issue Description

Using Navigation.push with options

```
bottomTabs: {
   visible: false
}

```
from a root bottomTabs child page with ScrollView or FlatList, when I call Navigation.pop from the stacked page, the area just above the bottomTabs flickers when returning to the root child page.

### Steps to Reproduce / Code Snippets / Screenshots

Related issues seem to be: 
#2849
#3250 
---
### Environment
* React Native Navigation version: 2.0.2369
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?):iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone Simulator Devices SE to X; iPhone X real device

**Comment by steverob** [comment]
This needs fixing please.

**Comment by steverob** [comment]
@jjbeach  did you manage to get this fixed?

**Comment by jjbeach** [comment]
Hey @steverob sorry for the delay, I was on vacation last week. I haven't been able to get it solved in v2 yet. I'm just going to wait until a stable version is released before I fully move over to v2.

**Comment by kfroemming** [comment]
Any idea what could be the root cause of this? We are experiencing this across all devices when using a scroll view. 
Exmaple Code: 
```
<ScrollView>
  {getContactDetailsSections(this.props.contact)
.map(
    this.renderSection,
   )}
</ScrollView>
```

**Comment by Neilgebbie** [comment]
Try the solution I posted here: https://github.com/wix/react-native-navigation/issues/3545

**Comment by Neilgebbie** [comment]
@jjbeach if this works can we close this issue?

**Comment by rickyliu93** [comment]
+1 reopen plz
