### ISSUE TITLE
[V2] bottomTabs broken / inconsistent breaks across Android & iOS

### ISSUE THREAD

**Issue by linnett** [wix/react-native-navigation#3409]
### Issue Description

Following the documentation for setting up bottomTabs, I was unable to make it work consistently across Android (7.0) and iOS (11.4). 

I copied and pasted this exact code, with the exception of changing the icon paths and screen ID's: https://wix.github.io/react-native-navigation/v2/#/docs/top-level-api?id=setrootlayout.
The results were as follows with screenshots below: 

Android - Tab 1 screen loaded correctly. The tab bar was visible and the Home icon and "Tab 1" text was and active red colour. I could also see the other icon, but I could not see the "Tab 2" text. When I press the Tab 2 icon, the "Tab 2" text appears. The red active state changes correctly. However, the Tab 2 screen does not load at all.

iOS - Tab 1 screen loaded correctly. The tab bar was visible and the Home icon and "Tab 1" text was and active blue colour. However, this time I could not see the other icon or text for Tab 2. When I press where the icon would be, it successfully shows the Tab 2 screen (unlike on Android) and the Tab 1 Home icon and text goes to an inactive state. 

Furthermore, documentation is also missing quite a lot of details e.g. fine but important details such as on/off states of icons and higher level critical installation instructions. 

### Steps to Reproduce / Code Snippets / Screenshots

Android
![screenshot_20180621-143831](https://user-images.githubusercontent.com/2244545/41723266-87c999f8-7562-11e8-96fb-412eea05b6a1.png)
![screenshot_20180621-143858](https://user-images.githubusercontent.com/2244545/41723271-89db1b36-7562-11e8-98ae-ad21e26dd2e4.png)

iOS
<img width="410" alt="screen shot 2018-06-21 at 14 37 48" src="https://user-images.githubusercontent.com/2244545/41723232-6e86aee0-7562-11e8-8873-b68271fd3eaa.png">
<img width="411" alt="screen shot 2018-06-21 at 14 37 40" src="https://user-images.githubusercontent.com/2244545/41723241-71b8b086-7562-11e8-9ea7-d9ee357cf734.png">

---
### Environment
* React Native Navigation version: 2.0.2362
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): 11.4 iOS / Android 7.0
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device - debug

**Comment by TylerNRobertson** [comment]
I had this same problem for a tiny bit but then realize it had to do with how I was calling my setRoot on a tab based application. Look very closely at the [layout](https://wix.github.io/react-native-navigation/v2/#/docs/layout-types?id=bottomtabs) in the docs. I realized that each tab has its own stack property but it doesn't show it across the full example. Try to see if formatting your setRoot with this format will work: 
<img width="365" alt="screen shot 2018-06-21 at 12 57 56 pm" src="https://user-images.githubusercontent.com/23481122/41730671-be88104c-7552-11e8-90cd-eabe1852661a.png">

I didn't include actual components in this little boilerplate but Im assuming you have seen the children and stack object/arrays before.

**Comment by linnett** [comment]
Thanks for the reply @TylerNRobertson. I couldn't quite get it working. I think the documentation needs a real revamp. Version 2 is nowhere near ready as far as I can see. 

Wix - please do not close until docs have been updated with how to implement a bottomTabs application correctly without bugs as highlighted. Thanks.
