### ISSUE TITLE
When resetTo new screen, app no response after swipe-back gesture

### ISSUE THREAD

**Issue by JuoCode** [wix/react-native-navigation#341]
As titles say, can be simple repetition
- For example screen1 and screen2, call `resetTo` to go to the screen2
- In screen2, make a swipe-right gesture on the left edge of the screen
- Now click any one component in screen2 will no response

---
### Environment
- React Native Navigation version: 1.0.30
- React Native version: 0.31.0
- Platform(s) : iOS
- Device info: iPhone 6, iOS 9.3.4 (Release)

**Comment by brainstretch** [comment]
I had the same problem. I think the problem appeared when you try to swipe back but there is no back page in the navigation stack. My solution was to disable swipe back in the native code.

**Comment by JuoCode** [comment]
Are you disable it in the whole app? Or just when there is no back page?

**Comment by brainstretch** [comment]
For now i disabled it in the whole app.

**Comment by brainstretch** [comment]
Maybe there is a problem with this code? when you hardcode it to NO it doesn't work.

RCTNavigator.m Line 373
```
- (BOOL)gestureRecognizerShouldBegin:(__unused UIGestureRecognizer *)gestureRecognizer
{
  return _navigationController.viewControllers.count > 1;
}
```

**Comment by JuoCode** [comment]
I found the later interactions like `view-push` `pop` are going well however you can't see it, but the app will show the correct result when you coming back from home screen.

**Comment by JuoCode** [comment]
@brainstretch Is [react-native-controllers#25](https://github.com/wix/react-native-controllers/issues/25) related with current issue?

**Comment by JuoCode** [comment]
@brainstretch Can you teach me how to disable it ?

**Comment by brainstretch** [comment]
Add this code to the viewWillAppear on line 174

RCCViewController.m
```objectivec
if ([self.navigationController respondsToSelector:@selector(interactivePopGestureRecognizer)]) {
      self.navigationController.interactivePopGestureRecognizer.enabled = NO;
    }
```

**Comment by JuoCode** [comment]
@brainstretch Thank you.

**Comment by alexcurtis** [comment]
+1 I'm also seeing this.
