### ISSUE TITLE
[v2] [iOS] iPhone X splash screen problem

### ISSUE THREAD

**Issue by pibo** [wix/react-native-navigation#3410]
I'm trying to configure the splash screen for my app via Xcode, but there is a problem when I open the app on the iPhone X.

I configured the LaunchImage on Xcode as follows:

<img width="585" alt="captura de tela 2018-06-21 as 12 10 28" src="https://user-images.githubusercontent.com/2624768/41728106-5b4b8c58-754c-11e8-918b-ea017327cead.png">

When I launch the app on the iPhone X, the solid orange image appears for a while, but suddenly changes to the logo before showing the single screen app. I tested different image combinations and found out that it uses the iPhone X image first, then it changes to the iPhone Portrait 2x iOS 7+ and fallbacks to iPhone Portrait 1x if the latter doesn't exist. As the image is smaller, it appears stretched.

![bug](https://user-images.githubusercontent.com/2624768/41728908-5654e6ac-754e-11e8-8516-925a6ae09b28.gif)

---
### Environment
* React Native Navigation version: 2.0.2275
* React Native version: 0.55.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X

**Comment by yogevbd** [comment]
Fixed. thanks!
