### ISSUE TITLE
modalPresentationStyle is always fullscreen and screenBackgroundColor is never transparent. [v2]

### ISSUE THREAD

**Issue by spencewine** [wix/react-native-navigation#3413]
### Issue Description

[ENTER DESCRIPTION HERE -]
Modal is always fullscreen and the background is not transparent even when changing `screenBackgroundColor` to transparent and `modalPresentationStyle` to anything other than `fullScreen`.

### Steps to Reproduce / Code Snippets / Screenshots

My content view for prior to displaying the modal is such:
```
<ScrollView>
  <CartSummaryContainer/>
  <AddressFormContainer/>
</ScrollView>
```

In my `AddressFormContainer` I have a method for displaying the modal:
```
    togglePicker(picker){
        const { navbarIcon } = this.state;
        const { countryValue, regionValue } = this.props;
        const showCountry = picker === 'showCountry';
        const name = showCountry ? 'native.CountryPicker' : 'native.RegionPicker';
        Navigation.showModal({
            stack: {
                children: [{
                    component: {
                        name,
                        passProps: {
                            picker,
                            onChange: showCountry ? this.countryChange : this.regionChange,
                            value: showCountry ? countryValue : regionValue,
                            showDefaultOption: !!showCountry,
                            defaultOptionLabel: showCountry ? 'United States' || countryValue : null,

                        },

                    },
                }],
                options: {
                    topBar: {
                        buttonColor: 'black',
                        leftButtons: [
                            {
                                id: 'close',
                                icon: navbarIcon,
                            },
                        ],

                    },
                    layout: {
                        backgroundColor: 'transparent',
                    },
                    screenBackgroundColor: 'transparent',
                    modalPresentationStyle: 'formSheet',
                },

            },

        });
    }
```
The result, regardless of what I change the modalPresentationStyle to, is a full screen modal. The screenBackgroundColor changes color, but if I make the value `transparent` it will have a white background. Here is gif of the event, the red background color in the inital CheckoutContainer is just to help visualize the elements:

![modalissue2](https://user-images.githubusercontent.com/1612742/41747767-c7ba3a4c-7574-11e8-8c46-4abe26cb3670.gif)

---
### Environment
* React Native Navigation version: 2.0.2305
* React Native version: 0.54.4
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/ 11.2/Debug

**Comment by dorthwein** [comment]
Running into this as well

**Comment by dorthwein** [comment]
Is there a thread tracking background colors not working etc...

**Comment by rostyys** [comment]
Same issue here.

**Comment by nanndoj** [comment]
I can confirm this problem still happening  on `^2.0.2581` couldn't make it work either. It starts transparent but then it becomes white.

**Comment by pribeh** [comment]
Can someone please reopen this issue? Or would you like us to post a new issue? As of 2.0.2584 the issue remains. 

iOS 12, xcode 10, iphone 6, 8 & X, RN 0.55.4.
