### ISSUE TITLE
IOS v127 error when reload app

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#342]
### Issue Description

this is error when reload js

![img_3852](https://cloud.githubusercontent.com/assets/19372005/18847634/2ed8c044-8455-11e6-9f44-cf6ca4517ab2.PNG)

---
### Environment
- React Native Navigation version: .127
- React Native version: 0.32.0
- Platform(s) (iOS, Android, or both?): IOS
- Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by agumack** [comment]
seem this is error with version react native 0.32, i revert 0.31 : )

**Comment by Crash--** [comment]
With iOS you can work on RN 0.33. I don't have any particular issue with that.

**Comment by agumack** [comment]
thank @Crash-- 
i will try now

**Comment by alexcurtis** [comment]
I'm also getting this every now and again. I reload and its back to normal.
@guyca Do you guys have a rough eta on 0.35+ support for iOS + android? It seems like a react-native version jump would solve quite a few issues floating around.

**Comment by guyca** [comment]
@alexcurtis no concrete eta but we will probably upgrade by mid November. give or take one week. Some guys from the team are also pushing for an upgrade.
