### ISSUE TITLE
Implementing HeadlessJS Task in react-native-navigation not working as expected

### ISSUE THREAD

**Issue by Ketn** [wix/react-native-navigation#3422]
### Issue Description

I'm using [react-native-firebase](https://github.com/invertase/react-native-firebase) to receive FCM messages via a HeadlessJS task.

However, the problem I'm having is that the headlessJS performs the task **when the app is in the background**, but it **doesn't work when the app is closed**.

I suspect this is because I need to implement headlessJS task differently in `react-native-navigation`. What is the correct way of registering a headless task?

### Steps to Reproduce / Code Snippets / Screenshots

This is how my headless task (**bgMessaging.js**):
```
import firebase from 'react-native-firebase';
import type { RemoteMessage } from 'react-native-firebase';

export default async (message: RemoteMessage) => {
    console.log("RemoteMessage", message);

    const newNotification = new firebase.notifications.Notification()
        .android.setSmallIcon(message.data.icon)
        .android.setChannelId(message.data.channel_id)
        .setNotificationId(message.messageId)
        .setTitle(message.data.title)
        .setBody(message.data.body)
        .setData({
            key1: 'value1',
            key2: 'value2',
        });
    firebase.notifications().displayNotification(newNotification);

    return Promise.resolve();
}
```

and this is how I've registered it in my **index.js**:
```
import { AppRegistry } from 'react-native';
import App from './app';
import bgMessaging from './bgMessaging';

const app = new App();

AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessaging);
```

---
### Environment
* React Native Navigation version: 1.1.464
* React Native version: 0.53.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): ONEPLUS A5010 - 8.1.0 (Debug)

**Comment by codebymani** [comment]
@Ketn if you are still having this issue, just wrap you root navigation as shown.

`import {Navigation, NativeEventsReceiver} from 'react-native-navigation';

Promise.resolve(Navigation.isAppLaunched())
  .then(appLaunched => {
    if (appLaunched) {
      startApp(); 
    } else {
      new NativeEventsReceiver().appLaunched(startApp);
    }
  });

function startApp() {
  Navigation.startTabBasedApp({ ... });
}`
