### ISSUE TITLE
[V2] Keyboard does not avoids ScrollView

### ISSUE THREAD

**Issue by diegolmello** [wix/react-native-navigation#3424]
### Issue Description

Hey, guys.
I need to implement a form and the keyboard not seems aware of `ScrollView` on Android.
It works properly on react-navigation.
I tried `KeyboardAvoidingView` and `KeyboardAwareScrollView`.

Since all libs of KeyboardAvoid*** do workarounds for iOS and return a normal ScrollView for Android, 
it seems the bug is in this lib.

### Steps to Reproduce / Code Snippets / Screenshots

GIF:
![jun-22-2018 18-29-19](https://user-images.githubusercontent.com/804994/41800097-670afaf2-764a-11e8-951d-8c0259406866.gif)

Code:
```jsx
render() {
    return (
        <KeyboardAwareScrollView enableOnAndroid>
            <View style={{ padding: 20 }}>
                <TextInput placeholder='textinput here' style={{ padding: 16 }} />
                <TextInput placeholder='textinput here' style={{ padding: 16 }} />
                <TextInput placeholder='textinput here' style={{ padding: 16 }} />
                <TextInput placeholder='textinput here' style={{ padding: 16 }} />
                <TextInput placeholder='textinput here' style={{ padding: 16 }} />
                <TextInput placeholder='textinput here' style={{ padding: 16 }} />
                <TextInput placeholder='textinput here' style={{ padding: 16 }} />
                <TextInput placeholder='textinput here' style={{ padding: 16 }} />
                <TextInput placeholder='textinput here' style={{ padding: 16 }} />
            </View>
        </KeyboardAwareScrollView>
    );
}
```

---
### Environment
* React Native Navigation version: 2.0.2373
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Samsung Galaxy S8 on debug

**Comment by blairvanderhoof** [comment]
I can repro this too on 1.1.474.  This happened after upgrading to the latest RN version.

**Comment by blairvanderhoof** [comment]
I confirmed its this library, something broke with scroll view avoiding the keyboard on focused inputs in android. I backed out to version 1.1.213 and I can no longer repro this issue. Would love a fix.  BTW if you want to use the newest react native version but use an older react native navigation version, grab the latest `JsDevReloadListenerReplacer` from react native navigation and replace it with the version in 1.1.213.

**Comment by blairvanderhoof** [comment]
It's also nothing to do with KeyboardAwareScrollView. @diegolmello example above will repro with a normal ScrollView.

**Comment by blairvanderhoof** [comment]
I did a bisect and it looks like it broke in 1.1.307.

**Comment by blairvanderhoof** [comment]
@guyca

**Comment by blairvanderhoof** [comment]
bump

**Comment by birkir** [comment]
You can build this yourself, actually, if you want (and its more stable than KeyboardAware...)

This example adds padding to the bottom of the scrollview:

```jsx
class Screen {

  state = {
    height: 0,
  };

  componentDidMount() {
    this.handler = Keyboard.addListener('keyboardWillChangeFrame', this.onKeyboardWillChangeFrame);
  }

  componentWillUnmount() {
    this.handler.remove();
  }

  onKeyboardWillChangeFrame = e => {
    const { startCoordinates, endCoordinates } = e;
    const height = startCoordinates.screenY - endCoordinates.screenY;
    LayoutAnimation.configureNext();
    this.setState({ height });
  }

  render() {
    const { height } = this.state;
    return (
      <ScrollView>
        // Stuff here
        <View style={{ height }} />
      </ScrollView>
    );
  }
}
