### ISSUE TITLE
[ios][v2] searchBarHiddenWhenScrolling doesn't work when searchBar is present on root screen

### ISSUE THREAD

**Issue by benhiller** [wix/react-native-navigation#3429]
### Issue Description

The searchBarHiddenWhenScrolling style property should make the search bar hide under the top bar when the user scrolls down in the content view. This works when the search bar is present on a child screen of the navigation stack, but when the search bar is present on the root screen of the navigation stack, it doesn't scroll away.

I looked into why this is happening, and it seems like it is due to the UIViewController lifecycle methods being called before the searchController property of the navigationItem is set. That is why this works properly for pushed screens, because in that case the UIViewController lifecycle methods are called after the view controller subviews have been set, thanks to the onReactViewReady call in -[RNNCommandsHandler push:layout:completion:rejection:]. That means one fix for this would be to ensure that the lifecycle methods are called for the root VC only after the react view is ready in setRoot, like we do in push. 

I tried making a change that fixes this issue with an approach similar to how showModal handles this, but I was not totally confident this fix is the right approach. The patch is here: https://gist.github.com/benhiller/5e6fdc8535f63a32680c1c46628d93b4. Let me know if this does seem like a reasonable approach to fix this issue and I can send out a pull request with this change.

### Steps to Reproduce / Code Snippets / Screenshots

1. Apply this patch to the v2 branch: https://gist.github.com/benhiller/dab2beacfb03eb35bd6aa5364e5767cf
2. Tap 'Push SearchBar' on the welcome screen
3. Scroll down, see that the search bar doesn't hide under the TopBar.

GIF demonstrating the issue: https://gfycat.com/FatherlyCarelessDolphin

---
### Environment
* React Native Navigation version: v2 at commit fbf8ea13874983b97c381bc3bac1cfcba9cd5b1c
* React Native version: 0.51.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6 Simulator, iOS 11.4, Debug

**Comment by sejr** [comment]
I am experiencing this issue as well.

**Comment by ptmt** [comment]
@benhiller, after updating to the `2.0.2397` I got the same regression. Your patch is working fine with default `stack` layout but seems to not working with other layouts, such as `bottomTabs`. Anyway, I'm curious if your explanation is right and if it's possible to write a test. Would love to help, but @yogevbd might have best understanding of this.

**Comment by DazChong** [comment]
Facing same issue. 
The `RNNRootViewController` > `viewDidAppear` method, where the `searchBarHiddenWhenScrolling` option apply. Never get called.

**Comment by ericlewis** [comment]
This is still occurring.

**Comment by ranjitpandit** [comment]
This is still broken.

**Comment by Crisis2010** [comment]
Still broken

**Comment by jfrolich** [comment]
Is this planned to be fixed?

**Comment by maitrungduc1410** [comment]
This is still broken

**Comment by sejr** [comment]
@jfrolich @maitrungduc1410 I wouldn't hold your breath for this to be fixed. In the amount of time that has passed since it was first reported, you could just learn to build your app without React Native. That was the approach I ended up taking.

**Comment by jfrolich** [comment]
> @jfrolich @maitrungduc1410 I wouldn't hold your breath for this to be fixed. In the amount of time that has passed since it was first reported, you could just learn to build your app without React Native. That was the approach I ended up taking.

Yeah I'd probably pull-request it. I didn't ship with autohide because it wasn't a priority atm. Actually we have good experience with react-native, just you have to be prepared to add some native code to get the best experience.
