### ISSUE TITLE
add more obvious links to `v2` documentation

### ISSUE THREAD

**Issue by ilovett** [wix/react-native-navigation#3430]
Just started a project a couple of days ago.  I knew there must be v2 documentation somewhere since I saw npm installed v2, but the README points to v1 documentation.  Since it didn't match up and I couldn't be bothered to look past the README and v1 docs site for a link to v2 docs, I just gave up and rolled back to v1 since I was familiar with it.

I'd recommend having a link right at the top of README to v2 underneath v1,

As well an obvious link in the v1 docs, maybe a dropdown in the left hand menu

**Comment by ilovett** [comment]
Updating github project description would help a lot

**Comment by yogevbd** [comment]
Done. thanks!
