### ISSUE TITLE
iOS navbar height

### ISSUE THREAD

**Issue by vanlooverenkoen** [wix/react-native-navigation#3433]
Issue Description
I need to get the navbar height for ios. How can I get that?

Steps to Reproduce / Code Snippets / Screenshots
/

Environment
React Native Navigation version: 1.1.406
React Native version: 0.52.2
Platform(s) (iOS, Android, or both?): Android
Device info (Simulator/Device? OS version? Debug/Release?): Simulator, device, any OS, any buildType.

**Comment by guyca** [comment]
Will be resolved in v2 by #3434
