### ISSUE TITLE
Constants support

### ISSUE THREAD

**Issue by yogevbd** [wix/react-native-navigation#3434]
**iOS**
- [x] statusBarHeight
- [x] topBarHeight
- [x] bottomTabsHeight

**Android**
- [x] statusBarHeight
- [x] topBarHeight
- [x] bottomTabsHeight
- [x] backButtonId

- [x] document

**Comment by yogevbd** [comment]
https://github.com/wix/react-native-navigation/tree/v2-Constants

**Comment by nenti** [comment]
Constants returns a promise but is documented as synchronous function. Also the returned value is wrong on my phone LG G4 returns 96 224.5 which apparently is way too high values for status and topbar.

```js
Navigation.constants().then(({ statusBarHeight, topBarHeight }) => {
      console.log(statusBarHeight, topBarHeight)
    })
```

**Comment by thame** [comment]
I'm getting '0' for my topBarHeight and bottomTabsHeight. statusBarHeight appears to be reported correctly ('44').

### Environment
* React Native Navigation version: 2.0.2418
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): iOS (only tested in iOS)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iPhone X, 11.4

**Comment by birkir** [comment]
drawUnder by any chance?

**Comment by masarusanjp** [comment]
@thame 

The code of below works fine.

```
Navigation.events().registerAppLaunchedListener(async () => {
  await Navigation.setRoot({
    root: {
      stack: {
      children: [
        {
          component: {
            name: "screen"
          }
        }
      ],
    });
  const c = await Navigation.constants();
  console.log(c.topBarHeight);
});

```

https://github.com/wix/react-native-navigation/blob/v2/lib/ios/Constants.m#L10

Maybe this behavior is a bug.
Looking at the current implementation, it returns the height of the navigationBar of navigationController of rootViewController. So, in the current implementation, it seems that the height can be taken only after displaying the screen with stack layout.

**Comment by aleppos** [comment]
I am getting wrong value
Constants {statusBarHeight: 63, topBarHeight: 147.5, backButtonId: "RNN.back", bottomTabsHeight: undefined}

**Comment by bneigher** [comment]
In researching why the `registerNavigationButtonPressedListener` doesn't report events on iOS, I'm seeing that `backButtonId` is undefined on iOS.  Is this intentional?  I'm starting to think that is the reason why it's not working.  Can we set this anywhere?
