### ISSUE TITLE
Document shared element transition

### ISSUE THREAD

**Issue by yogevbd** [wix/react-native-navigation#3435]

**Comment by birkir** [comment]
Are we planning shared element transition for android?

Should be able to re-use most of the SharedElementTransition from v1: https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=shared-element-transition

**Comment by guyca** [comment]
@birkir We are. As it's a pretty big task, we'll get to it in ~2 months after we fix the issues raised by the community during the alpha period.
