### ISSUE TITLE
Can't run example - RCTBridge.h file not found

### ISSUE THREAD

**Issue by songyen** [wix/react-native-navigation#344]
### Issue Description
Followed steps on example, can't run example.

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

1. Clone repo
2. run npm install in react-native-navigation/example
3. open example/ios/example.xcodeproj
4. Get error

RCTBridge.h not found in RCCNavigationController.h
(..downloaded directory)/react-native-navigation/ios/RCCNavigationController.m:1:9: In file included from (..downloaded directory)/react-native-navigation/ios/RCCNavigationController.m:1:

Package.json:

{
  "name": "example",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "watchman watch-del-all && (adb reverse tcp:8081 tcp:8081 || true) && node node_modules/react-native/local-cli/cli.js start",
    "xcode": "open ios/example.xcodeproj",
    "android": "cd android && ./gradlew installDebug"
  },
  "dependencies": {
    "react-native": "0.31.0",
    "react": "15.2.1",
    "react-native-navigation": "file:../"
  }
}
Error
![screen shot 2016-09-28 at 12 45 20 pm](https://cloud.githubusercontent.com/assets/5099425/18925483/c4f9fdac-8579-11e6-8e7f-eeb87d7f4d91.png)
Header search paths
![screen shot 2016-09-28 at 12 47 00 pm](https://cloud.githubusercontent.com/assets/5099425/18925489/c72b7d44-8579-11e6-848e-295c79f818d0.png)

---
### Environment
* React Native Navigation version: v.2.0.0.127
* React Native version: 0.31.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iOS 10.0, Debug

**Comment by YuriyUlantsev** [comment]
@songyen need added correct path "$(SRCROOT)/../example/node_modules/react-native/React"

**Comment by songyen** [comment]
That did not fix it, still getting the same error.

**Comment by songyen** [comment]
Nevermind I got it. I had to fix the header path in the ReactNativeNavigatoin.xcodeproj.
