### ISSUE TITLE
Custom NavBar does not render [after merging #3405]

### ISSUE THREAD

**Issue by steverob** [wix/react-native-navigation#3440]
### Issue Description

There was a PR #3405 merged in to fix the iOS Flicker Issue (#2849, #3250) by @yogevbd . After that merge, the custom top NavBar components have stopped rendering

###  Screenshots

Here is a screenshot from the sample app at 92b3037f14882dd2b577f6d8b86d712dc201aa29 (before merge):

![f580773a-77a8-4416-a55a-aaa5674e2fe3](https://user-images.githubusercontent.com/1220480/41901906-c4f06258-794f-11e8-863f-ad38f1644acf.jpeg)

Here is how it looks at 9d4eea835ad83170c39c336c108ef2610c078f19 (after the merge / master)

![8a894b0f-48fa-4b93-b0e3-cf440b9b12de](https://user-images.githubusercontent.com/1220480/41901936-d6c2df6a-794f-11e8-9a27-f2a2df1b049c.jpeg)

Can this be addressed please? @simonmitchell @yogevbd 

---
### Environment
* React Native Navigation version: `master`
* React Native version: `0.55.4`
* Platform(s): `iOS`
* Device info: all iOS Devices. (debug & release modes)

**Comment by yogevbd** [comment]
Reverted #3441

**Comment by steverob** [comment]
@yogevbd any thoughts on how this can be fixed?

**Comment by steverob** [comment]
@yogevbd  @guyca Can you confirm that this will not be looked at in the near future?

**Comment by simonmitchell** [comment]
@steverob @guyca it looks like it's possible my PR was merged insanely quickly, and that I made some changes to fix additional issues (like this one) after it was merged. I will test in the example project pointing at our branch and then would it be possible to get the merge looked at again?
