### ISSUE TITLE
Problem with building React-Native-Navigation

### ISSUE THREAD

**Issue by TylerNRobertson** [wix/react-native-navigation#3444]
### Issue Description
I am trying to build my project in Microsoft App Center but when it tries to build and install the packages, React-Native-Navigation produces this error. 

**RCTFont.h:21:37: error: this function declaration is not a prototype**

I know it is React-Native-Navigation because I have gone in and had to turn that function into a prototype myself locally. But since this is not local I cannot make the changes myself and it would be nice if you guys could update the code.

### Steps to Reproduce / Code Snippets / Screenshots

Only thing you need to reproduce this error is just simply install this library and try to build your project.

---
### Environment
* React Native Navigation version: 2.0.2367
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): N/A

**Comment by medelman17** [comment]
Just ran into the same issue.

**Comment by TylerNRobertson** [comment]
@medelman17 If you need to fix it locally just follow the reference produced by the error in xcode and then clean your product and rebuild. Once the "void" is placed within the brackets it fixed the error.

**Comment by KylePalko** [comment]
Same issue 😕

**Comment by KylePalko** [comment]
It looks like this issue will go away with the React Native 0.56.0 release candidate. The RN team added `void` to the `RCTHasFontHandlerSet` [method invocation](https://github.com/facebook/react-native/blob/37c820f16e33746241af05e188d69502f518f80d/React/Views/RCTFont.h).

**Comment by danmurrelljr** [comment]
@guyca 
Waiting for a ReactNative release isn't really a fix. The current situation won't work with continuous integration systems.

What if instead we turn off the strict-prototypes build setting in ReactNativeNavigation.xcodeproj, since that's what's actually failing these builds, and something RNN team can control.
