### ISSUE TITLE
screenBackgroundColor not working[iOS]

### ISSUE THREAD

**Issue by whhotw** [wix/react-native-navigation#3447]
as title, on iOS cannot change screenBackgroundColor even set, but Android was fine 
anyone has same problem?

```
    appStyle: {
      navBarButtonColor: '#fff',
      navBarTextColor: '#fff',
      navigationBarColor: '#fff',
      navBarBackgroundColor: '#000',
      statusBarColor: '#000',
      navBarSubtitleColor: '#fff',
      statusBarTextColorScheme: 'light',
      navBarTitleTextCentered: true,
      hideBackButtonTitle: true,
      navBarHidden: false,
      autoAdjustScrollViewInsets: true,
      screenBackgroundColor: '#eee',
    }
```

**Comment by vitalyrotari** [comment]
Same problem,

- `navigatorStyle` is not working anymore
- When opening a modal screen, it opens several on top of each other
- `setOnNavigatorEvent` not fire `didAppear`, etc. 

version v1.1.473

**Comment by whhotw** [comment]
downgrade to v1.1.471 is well, i checkout latest(v1.1.473) changes found about reason
