### ISSUE TITLE
navBarCustomView not working on iOS

### ISSUE THREAD

**Issue by mhidou** [wix/react-native-navigation#3449]
### Issue Description

When I run the example app on iOS the `CustomTopBarScreen` example doesn't work.

### Steps to Reproduce / Code Snippets / Screenshots

```
git clone https://github.com/wix/react-native-navigation.git
cd react-native-navigation/example
npm install
```
 - Open `./ios/example.xcodeproj`.
 - Run on iOS device or simulator.
 - Press `Custom TopBar`.
 - The `navBarCustomView` is not displayed.

---
### Environment
* React Native Navigation version: latest
* React Native version: all
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): all iOS devices

---

After some debugging I've spotted that in `RCCViewController.m:615` we have currently

```objective-c
if ([self.view isKindOfClass:[RCTRootView class]]) {
  RCTBridge *bridge = ((RCTRootView*)self.view).bridge;
```

Changing `self.view` to `self.rootView` fixes this issue.

```objective-c
if ([self.rootView isKindOfClass:[RCTRootView class]]) {
  RCTBridge *bridge = ((RCTRootView*)self.rootView).bridge;
```

**Comment by herarya** [comment]
same +1, after update npm

**Comment by pribeh** [comment]
Resolved the issue for me. Thanks!
