### ISSUE TITLE
[v2] topBar missing if searchBar has focus and new route is pushed

### ISSUE THREAD

**Issue by tobiaslins** [wix/react-native-navigation#3450]
### Issue Description

I have following active route: 
```js
topBar: {
  title: {
    text: 'Explorer'
  },
  largeTitle: {
     visible: true
  },
  searchBar: true,
}
```
When I click on the `searchBar` and afterwards click onto a item (invokes a push) the `TopBar` is missing until I swipe back.

### Steps to Reproduce / Code Snippets / Screenshots

Simple Route with `largeTitle` and `searchBar`. On this route a button with a push action to another route with `topBar` title.

<img src="https://i.imgur.com/BclLQJe.gif" height="400"/>

---
### Environment
* React Native Navigation version: 2.0.2377
* React Native version: 0.55.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Testflight Release tested

**Comment by ptmt** [comment]
Looks like a regression. I'm currently using `2.0.2354` and don't have such problem, but surely will need to update soon. Investigating now what causes this behaviour. Will try to fix.

**Comment by ptmt** [comment]
Fixed https://github.com/wix/react-native-navigation/pull/3501
