### ISSUE TITLE
[v2] `transparent: true` vs. `background: { color: 'transparent' }`

### ISSUE THREAD

**Issue by ilovett** [wix/react-native-navigation#3455]
If default has `background.color: 'red'` and component has `transparent: true` the red background will still be displayed.

```
    static get options() {
        return {
            topBar: {
                drawBehind: true,
                transparent: true,
                background: {
                    color: 'transparent'
                }
            }
        };
    }
```

Perhaps move `transparent` to `background.transparent = true`

**Comment by ilovett** [comment]
Also there appears to be a border left over even if `topBar.noBorder = true`

![image](https://user-images.githubusercontent.com/1776100/41996737-af8619b0-7a0a-11e8-9f95-885756ee7b04.png)

**Comment by sapjax** [comment]
https://github.com/wix/react-native-navigation/issues/3400
Did you using `showModal` with this options.

**Comment by salisuabubakar** [comment]
I had the same issue. Any solution please. Thanks

**Comment by wilsontr** [comment]
Seeing the same thing here. 

```
topBar: {
  noBorder: true,
  visible: true,
  drawBehind: true,
  transparent: true,
  title: {
    text: 'Foobar',
    color: 'white',
  },
  background: {
    color: 'transparent',
  },              
},
```

The top bar background shows up as black, in this case.

**Comment by guyca** [comment]
Hey guys, we're deprecating the `transparent` property as it really does duplicate `topBar.background.color` property.

**Comment by guyca** [comment]
`transparent` property was removed in v2.0.2570. The `blur` and `translucent` properties changed as well and are now part of the `background` node:

```js
options: {
  topBar: {
    background: {
      color: 'transparent',
      translucent: true,
      blur: false
    }
  }
}
```
