### ISSUE TITLE
App crashes on start only on android

### ISSUE THREAD

**Issue by rbth7e5** [wix/react-native-navigation#3458]
### Issue Description
Build successful. However, crashes on startup only on android. I followed all the getting started installation instructions. It was working until I tried to integrate react-native-firebase.

### Logs
Starting the logger (/Users/chencaijie/Library/Android/sdk/platform-tools/adb logcat *:S ReactNative:V ReactNativeJS:V)...
--------- beginning of system
--------- beginning of main
--------- beginning of crash
06-28 17:18:44.916 23396 23396 D ReactNative: ReactInstanceManager.createReactContextInBackground()
06-28 17:18:44.916 23396 23396 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
06-28 17:20:34.943 23518 23518 D ReactNative: ReactInstanceManager.ctor()
06-28 17:20:35.005 23518 23518 D ReactNative: ReactInstanceManager.createReactContextInBackground()
06-28 17:20:35.005 23518 23518 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
06-28 17:21:08.751 23615 23615 D ReactNative: ReactInstanceManager.ctor()
06-28 17:21:08.808 23615 23615 D ReactNative: ReactInstanceManager.createReactContextInBackground()
06-28 17:21:08.808 23615 23615 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
06-28 17:24:45.178 23735 23735 D ReactNative: ReactInstanceManager.ctor()
06-28 17:24:45.228 23735 23735 D ReactNative: ReactInstanceManager.createReactContextInBackground()
06-28 17:24:45.229 23735 23735 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
06-28 17:25:10.382 23851 23851 D ReactNative: ReactInstanceManager.ctor()
06-28 17:25:10.427 23851 23851 D ReactNative: ReactInstanceManager.createReactContextInBackground()
06-28 17:25:10.427 23851 23851 D ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
06-28 17:25:12.351 23851 23851 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
06-28 17:25:12.351 23851 23851 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
06-28 17:25:12.352 23851 23851 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
06-28 17:25:12.360 23851 23879 D ReactNative: ReactInstanceManager.createReactContext()
06-28 17:25:12.392 23851 23879 D ReactNative: Initializing React Xplat Bridge.
06-28 17:25:12.394 23851 23879 D ReactNative: Initializing React Xplat Bridge before initializeBridge
06-28 17:25:12.397 23851 23879 D ReactNative: Initializing React Xplat Bridge after initializeBridge
06-28 17:25:12.397 23851 23879 D ReactNative: CatalystInstanceImpl.runJSBundle()
06-28 17:25:12.397 23851 23883 D ReactNative: ReactInstanceManager.setupReactContext()
06-28 17:25:12.397 23851 23883 D ReactNative: CatalystInstanceImpl.initialize()
---
### Environment
* React Native Navigation version: 1.1.473
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel 2 Simulator. Android version 6.0. Debug

**Comment by umerbaig** [comment]
I'm having exactly same issue.

**Comment by MSSPL-PiyaleeMaiti** [comment]
I am getting the same issue, can anyone suggest any solution?

**Comment by marudy** [comment]
Same here, that issue should be reopened

**Comment by umerbaig** [comment]
are you using react native maps?

**Comment by rbth7e5** [comment]
nope i am not

**Comment by GioLogist** [comment]
Same issue on my end

**Comment by hindsricardo** [comment]
same issue here

**Comment by mrishan1993** [comment]
same
