### ISSUE TITLE
[Android] Cannot get Android version working

### ISSUE THREAD

**Issue by tylerclark** [wix/react-native-navigation#346]
### Issue Description
Trying to follow the confusing [Android Installation directions](https://github.com/wix/react-native-navigation/wiki/Installation---Android) I can't get passed a few errors:
`undefined is not an object (evaluating 'NativeReactModule.startApp')` - I get that in the simulator. I get this error when I run: `react-native run-android`:
```
/Users/<username>/<project>/android/app/src/main/java/com/<project>/MainApplication.java:17: error: MainApplication is not abstract and does not override abstract method createAdditionalReactPackages() in NavigationApplication
public class MainApplication extends NavigationApplication {
       ^
1 error
:app:compileDebugJavaWithJavac FAILED
```

### Steps to Reproduce / Code Snippets / Screenshots

1. Ran: `rninit init test5 --source react-native@0.31.0` to install RN 0.31.0
2. Tested that the default RN installation would run on iOS and Android. Both worked fine.
3. Ran: `npm install react-native-navigation@next --save` (this instruction only exists on the iOS installation page)
4. Moved over some files from the `examples` folder: `index.ios.js`, `index.android.js`, `app.js`, and a sample screen file.
5. Followed the [iOS instructions](https://github.com/wix/react-native-navigation/wiki/Installation---iOS). Ran project in Xcode and it worked showing the sample screen.
6. Followed the [Android instructions](https://github.com/wix/react-native-navigation/wiki/Installation---Android). Ran project via command line `react-native run-android` and it fails.

I had to guess at a lot of the steps so I'm sure I got something wrong.

Step 3 for example says "MainActivity". I assume they mean `/android/app/src/main/java/com/<project>/MainActivity.java`? An example of this file would be super helpful. I did copy exactly from examples folder.

Step 4 says "MainApplication". I assume they mean `/android/app/src/main/java/com/<project>/MainApplication.java`? Step 4 really mentions two files it seems. Confusing.

Step 5 doesn't say which file to modify? I've also seen in the examples folder references to `MyApplication` and `MainApplication`.

Just so lost. Any help would be nice.

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.31.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

---
### AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.test6"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
      android:name=".MyApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

---
### MainActivity.java
```
package com.test6;

import com.reactnativenavigation.controllers.SplashActivity;

public class MainActivity extends SplashActivity {

}
```

---
### MyApplication.java
```
package com.test6;

import android.support.annotation.Nullable;

import com.facebook.react.ReactPackage;
import com.reactnativenavigation.NavigationApplication;

import java.util.List;

public class MyApplication extends NavigationApplication {
    @Override
    public boolean isDebug() {
        return BuildConfig.DEBUG;
    }

    @Nullable
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return null;
    }
}
```

---
### MainApplication.java
```
package com.test6;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

import com.reactnativenavigation.NavigationApplication;

public class MainApplication extends NavigationApplication {

}
```

**Comment by guyca** [comment]
@tylerclark I'm sorry about the confusion. The docs are still incomplete, we definitely  need to improve them. If you delete `MainApplication.java` your code should run, since you declared `MyApplication` in your `AndroidManifest.xml` file:
```xml
<application
      android:name=".MyApplication"
      ...
</application>
```

An Android app has only one class that extends the Application class, in your case `MyApplication` is used since it's the one declared in the manifest. You had two classes that extended `NavigationApplication` which is an abstract class, meaning it can't be used by itself, it has to be extended in order to be used because it defines methods that must be implemented (Using `@Override` annotation).
`MyApplication` was defined just fine, it contained the two methods that had to be implemented (`isDebug` and `createAdditionalReactPackages`) but `MainApplication` was missing both. That's the compilation error you got.

**Comment by tylerclark** [comment]
I made the proper adjustments (by removing `MainApplication.java`). Unfortunately I'm getting this error now:

```
/Users/username/test6/android/app/src/main/java/com/test6/MyApplication.java:18: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class MyApplication
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

```

---
### MyApplication.java
```
package com.test6;

import android.support.annotation.Nullable;

import com.facebook.react.ReactPackage;
import com.reactnativenavigation.NavigationApplication;

import java.util.List;

public class MyApplication extends NavigationApplication {

    @Override
    public boolean isDebug() {
        // Make sure you are using BuildConfig from your own application
        return BuildConfig.DEBUG;
    }

    @NonNull
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        // Add the packages you require here.
        // No need to add RnnPackage and MainReactPackage
        return null;
    }
}
```

**Comment by tylerclark** [comment]
I removed `@NonNull` and launched a simulator (another confusing thing) and it worked. That'll work!
