### ISSUE TITLE
Always Show Bottom Tabs Label

### ISSUE THREAD

**Issue by caktoy** [wix/react-native-navigation#3463]
### Issue Description
How do I keep labels on the bottom tabs always showing up?
![image](https://user-images.githubusercontent.com/6917446/42073499-5e4a8238-7b91-11e8-92e5-b2c05c6ccc9f.png)

### Steps to Reproduce / Code Snippets / Screenshots
Just create an Navigation

### Environment
* React Native Navigation version: 2.0.2381
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Android 8

**Comment by guyca** [comment]
Use [titleDisplayMode](https://wix.github.io/react-native-navigation/v2/#/docs/styling?id=android-specific-options) 👍

**Comment by Dalamar** [comment]
What about V1?

**Comment by rodrigofbm** [comment]
how I do that in the current version?

**Comment by rodrigofbm** [comment]
I'm reading this [doc](https://wix.github.io/react-native-navigation/next/api/options-bottomTabs/#titledisplaymode) but I don't know where I put in the titleDisplayMode . Can some on help me?
