### ISSUE TITLE
[v2] documentation link dead

### ISSUE THREAD

**Issue by GuillotJessica** [wix/react-native-navigation#3465]
https://wix.github.io/react-native-navigation/v2/#/android-specific-use-cases?id=splash-screen
was searching for splash screen in the search input when : 
![image](https://user-images.githubusercontent.com/21151517/42098238-9aa07278-7bba-11e8-893f-9c7fab589182.png)
in fact no link of the results got me anywhere

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
Not sure why this happens, perhaps this is a caching issue which will be resolved when we merge v2 to master. (v2 docs are pulled from the `v2` branch.
