### ISSUE TITLE
When will this awesome library will hit a beta release? 

### ISSUE THREAD

**Issue by rautram** [wix/react-native-navigation#3467]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
We're in late alpha, the api is pretty much stable and we've already migrated the Wix app to v2. I think you can give it a spin and try v2 for your self :)
