### ISSUE TITLE
Integrate firebase with redux

### ISSUE THREAD

**Issue by avishayil** [wix/react-native-navigation#347]
Hi,
I'm currently trying to integrate this library with firebase & redux.

My intension is to anonymously log in the user using firebase using `firebaseRef.auth().onAuthStateChanged`listener and , and save the reference on the app state, so i'll be able to use it later within the app.

What would be the best way to do that in a tab based app?

I tried to do that using a root component and put the listener on the constructor, but since I can't connect the root component to redux (it's not a react component but a pure JS class - `const app = new App();`), nor to pass the reference to `passProps` parameter of `startTabBasedApp` i'm kinda out of ideas.

Do you have any suggestion to address this?

**Comment by guyca** [comment]
The way I think you should implement this, is dispatch an action in your `App` constructor indicating the app is loaded. in your action check if you have a valid session of a logged in user, then dispatch another action from which call `startApp` with the appropriate screen; `LoginScreen` or `MainScreen`.

```js
const store = createStoreWithMiddleware(reducer);

...
export default class App {
  constructor() {
    store.subscribe(this.onStoreUpdate.bind(this));
    store.dispatch(actions.appInitialized());
  }

  onStoreUpdate() {
    // Start appropriate root, either login or main screen
  }
}

**Comment by avishayil** [comment]
Great way, just don't forget to unsubscribe, otherwise it would cause your app an infinite loop :>
```javascript
const store = createStoreWithMiddleware(reducer);

...
export default class App {
  constructor() {
    this.unsubscribe = store.subscribe(this.onStoreUpdate.bind(this));
    store.dispatch(actions.appInitialized());
  }

  onStoreUpdate() {
    // Start appropriate root, either login or main screen
    this.unsubscribe();
  }
}
```

**Comment by brunovalenga** [comment]
Thanks @avishayil, its great for me.
