### ISSUE TITLE
Override hardware back button

### ISSUE THREAD

**Issue by caktoy** [wix/react-native-navigation#3471]
### Issue Description
I want to exit my application when I pressed hardware back button, I was implemented BackHandler from react-native module, and I implement that in a modal. The event handler is worked only close active modal. How I can set to exit application when the event tirgerred?

### Steps to Reproduce / Code Snippets / Screenshots
componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.handleBackPress);
}

componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.handleBackPress);
}

handleBackPress() {
    Alert.alert('Exit', 'Are you sure?', [
            {
                text: 'No',
                style: 'cancel'
            },
            {
                text: 'Yes',
                onPress: () => BackHandler.exitApp()
            }
        ], {
            cancelable: false
        });
        return true;
}

### Environment
* React Native Navigation version: ^2.0.2381
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Android 8

**Comment by HRCJ7** [comment]
Hi,
Have you solved this ?

**Comment by caktoy** [comment]
Not yet @HRCJ7

**Comment by kevinNejad** [comment]
hsving the same issue with LightBox

**Comment by muhammadsr** [comment]
Any updates on how to override the back handling in a component?

**Comment by cinder92** [comment]
any update on this?

**Comment by ashu090990** [comment]
any update ?
