### ISSUE TITLE
Navbar from transparent to background color.

### ISSUE THREAD

**Issue by acollazomayer** [wix/react-native-navigation#3473]
Hi i want to make the navbar from with the properties transparent and drawunder to a navbar with background color on scroll. However when toggle the properties navBarTranslucent, navBarTransparent from true to false, the draw under property stop working and the transition between the transparent navbar to the background color is not smooth. I discover that if i disable only the navBarTransparent property the transition is smooth. However as the navBarTranslucent property is still on the background is not really the background I want. 

Does anyone knows how i can achieve this.

Thank you

**Comment by thame** [comment]
I'm having a similar issue regarding topBar animation. If a topBar has a backgroundColor, pushing the next screen animates the backgroundColor appropriately, but it just jumps back to the prior color when popping.

App.js
```
  Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setDefaultOptions({
      topBar: {
        animate: true,
        background: {
          color: 'green'
        },
      },
    });
    Navigation.setRoot({
      root: {
        bottomTabs: {
          children: [
            {
              stack: {
                id: 'TabOne',
                children: [{
                  component: {name: 'navigation.TabOne'}
                }],
                options: {
                  bottomTab: {
                    title: 'TabOne',
                  },
                }
              }
            },
          ],
        }
      }
    });
  });
```

And in TabTwo's `componentDidMount`
```
    Navigation.mergeOptions(this.props.componentId, {
      topBar: {
        background: {
          color: 'blue'
        }
      }
    })

```
![topbaranimation](https://user-images.githubusercontent.com/14227/42142328-9187f602-7d63-11e8-98ce-4940818ac91c.gif)

**Comment by herarya** [comment]
i found the same issue , only on android
