### ISSUE TITLE
White background when push screen

### ISSUE THREAD

**Issue by acollazomayer** [wix/react-native-navigation#3474]
### Issue Description
I have a dark theme app and when pushing a new screen there is a white background during the transition. This is ugly is there a way to solve this.

I already try with screenBackgroundColor, but it does not work
Here is how it looks:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9849229/42145052-3295a5d6-7d95-11e8-9d4a-5b33894bf5be.gif)

### Environment
* React Native Navigation version: 1.1.446
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device/Debug

**Comment by mhidou** [comment]
I got the same issue, downgrading to `1.1.471` fixes this issue

**Comment by acollazomayer** [comment]
@mhidou It works! It seems that the version 1.1.446 has a bug! Thank you!!

**Comment by Kyonru** [comment]
Maybe you should close the issue.

**Comment by legion-zver** [comment]
@mhidou I have the same problem, but only in the release build on iOS

**Comment by damathryx** [comment]
this is also happening on v2 only on iOS

**Comment by legion-zver** [comment]
In version 2 of this QC, you can close the issue

**Comment by Rana-Muhammad-Amir** [comment]
Facing same issue on latest version....
Environment
"react": "16.6.1",
"react-native": "0.57.5",
"react-native-navigation": "^2.1.3",
Platform(s) (iOS, Android, or both?): Android
Device info (Simulator/Device? OS version? Debug/Release?): Device/Debug

Any help...?

**Comment by romanglom** [comment]
@Rana-Muhammad-Amir Check this out https://github.com/wix/react-native-navigation/issues/358#issuecomment-451974062
It worked for me.
