### ISSUE TITLE
[v2] Is there a way to 'replace' the sideMenu component

### ISSUE THREAD

**Issue by bobmulder** [wix/react-native-navigation#3477]
Hi there,

Because of the lack of documentation I can't find out if it's possible to use another sideMenu component for specific screens on Android.

I tried the following:

```js
      this.Navigation.push(this.props.componentId, {
        component: {
          name: routes.Camera,
          options: {
            sideMenu: {
              left: {
                component: {
                  name: routes.DrawMenu,
                  visible: true
                }
              }
            }
          }
        }
      })
```

```js
  static get options () {
    return {
      rightButtons: [
        {
          icon: icons.close,
          id: 'close'
        }
      ],
      sideMenu: {
        left: {
          component: {
            name: routes.DrawMenu,
            visible: true
          }
        }
      }
    }
  }
```

**Comment by guyca** [comment]
Hey Bob, Instead of using a component in `SideMenu.left` - use a `stack` instead and reset that stack to a different component.

```js
Navigation.setRoot({
  root: {
      sideMenu: {
        left: {
          stack: {
            id: 'SIDE_MENU_LEFT_STACK',
            children: [
              {
                component: {
                  name: 'navigation.playground.SideMenuScreen',
                  passProps: {
                    side: 'left'
                  }
                }
              }
            ]
          }
        },
        center: {
          ...
        }
      }
    }
  }
});
```

Then, call [setStackRoot](https://wix.github.io/react-native-navigation/v2/#/docs/screen-api?id=setstackrootcomponentid-params) with `SIDE_MENU_LEFT_STACK` as id.

**Comment by bobmulder** [comment]
Thank you! I left my migration from v1 to v2 in order to to fix some other stuff on my app but this will definitely help me @guyca! Thanks!

**Comment by reganperkins** [comment]
@guyca using the stack method you suggested is there anyway to completely remove the side menu for certain pages? i.e i want to have it where a side menu is only on two pages and the content depends on which of the two pages I am on. 

Also in the following I can replace the content but I cant seem to open the drawer, only gestures are working.

```
Navigation.setRoot({
		root: {
			sideMenu: {
				center: {
					stack: {
						options: {
							popGesture: false,
						},
						children: [
							{
								component: {
									name: 'WaitForAuth',
								},
							},
						],
					},
				},
				left: {
					enabled:
						_.get(session.selector(store.getState()), 'status') ===
						session.SessionStatus.LOGGED_IN,
					visible: false,
					component: {
						id: 'drawer',
						name: 'drawer',
					},
				},
				right: {
					stack: {
						id: 'SIDE_MENU_RIGHT',
					}
				},
			},
		},
	});

```

```
Navigation.setStackRoot('SIDE_MENU_RIGHT', {
		component: { name: 'RightPanel', passProps: props, options: {visible: true, enabled: true} },
		options: {visible: true, enabled: true},
		visible: true,
		enabled: true,
	}) 
```

**Comment by React-Vishnu** [comment]
@guyca  i tried like you mentioned, but after reset the side drawer it will not be visible, i understand that the  old side drawer not unmounting . but in the case of HomeScreen it works.
Navigation.setStackRoot('DrawerStack', {
        component: {
            name: "MyApp.LeftDrawer",
            passProps: {
              ...
            }
        }
    }); 
Navigation.setStackRoot('Root', {
        component: {
            name: 'MyApp.HomeScreen',
            passProps: {
                ...
            },
            options: {
               ...
            }
        }   
    });
