### ISSUE TITLE
RefreshControl icon, appears at the upper right side, in TabBased app

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#348]
### Issue Description

I have a tab based app with the navigator at the top. In the middle there is a component with a ListView.
When the app first loads, almost half of the loading icon (RefreshControl icon) appears at the upper right corner. When I swipe to refresh, the problem gets solved. The icon moves in the middle and appears and disappears at the correct place and time from then on.
This happens always when the app is loaded.

### Steps to Reproduce / Code Snippets / Screenshots

![drawing](https://cloud.githubusercontent.com/assets/10828675/18993202/c05853f4-872a-11e6-9609-8b25552b15ba.png)

---
### Environment
* React Native Navigation version: 2.0.0-experimental.126
* React Native version: 0.31.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iOS 9 -10

**Comment by guyca** [comment]
cc @artald

**Comment by andybbtt11** [comment]
I have fixed this by adding style={{backgroundColor: 'transparent'}} on the scroll/list view.

**Comment by artald** [comment]
@guyca this is a bug in RN. Fixed in RN-34.1 via [this commit](https://github.com/facebook/react-native/commit/dcdf16a0fbe8ded9af6ed75ad0c3ec627e56b75a)
