### ISSUE TITLE
[iOS] react-native-navigation error

### ISSUE THREAD

**Issue by RCTnativeapp** [wix/react-native-navigation#3483]
<img width="448" alt="screen shot" src="https://user-images.githubusercontent.com/36904072/42190890-9b199584-7e14-11e8-846d-a407189c5159.png">

Any clue please

**Comment by viper4595** [comment]
Check your images/icons you assigned to icon and selectedIcon prop in tabs at startTabBasedApp

**Comment by RCTnativeapp** [comment]
Icon.getImageSource('ios-menu', 30, '#fff').then((menuIcon) => {
      this.props.navigator.setButtons({
        leftButtons: [
          {
            icon: menuIcon,
            disableIconTint: 'true',
            buttonColor: '#fff',
            id: 'menu'
          }
        ]
      });
    });

**Comment by RCTnativeapp** [comment]
Tried replacing the icon with another icon.Still the same error

**Comment by viper4595** [comment]
Did you try to paste "require('icon') directly to your static button icon prop (without setButtons)? Is it work correctly ?
