### ISSUE TITLE
[V2] RTL Layout Support

### ISSUE THREAD

**Issue by hadimostafapour** [wix/react-native-navigation#3485]
### Issue Description

In many cases our applications need to support __RTL__ languages, __React__ allows to _RTL_ via `I18nManager` API, but __RNN__ does not support any options to deal with layout directions ( Only loves _LTR_ 😢 ).

~~Android Platform:~~
~~In RNN v1 when system language was a RTL  language (like: Persian or Arabic) or simply call `I18nManager.forceRTL(true)`, Everything goes fine, back button shown in right.~~
~~But in RNN v2 Nothing, always left and always LTR, no way to done it.~~

### Steps to Reproduce / Code Snippets / Screenshots

1. Change system language to > `Persian/فارسی` `Arabic`
2. Restart _RNN_ App
3. Push a component to navigator  and __look at navigation__

  > _If works, back button should displayed at right either title._

#### UPDATE: I described workarounds for both _Android_ and _iOS_ platforms in comments.
---
### Environment
* React Native Navigation version: 2.0.2394
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by hadimostafapour** [comment]
Workaround for android

Edit NavigationModule.java

Add:
```java
@NonNull
	private LayoutFactory newLayoutFactory(String direction) {
		Activity appActivity = activity();
		appActivity.getWindow().getDecorView().setLayoutDirection(direction.equals("rtl") ? View.LAYOUT_DIRECTION_RTL : View.LAYOUT_DIRECTION_LTR);

		I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
		if(direction.equals("rtl")) {
			sharedI18nUtilInstance.allowRTL(getReactApplicationContext(), true);
			sharedI18nUtilInstance.forceRTL(getReactApplicationContext(), true);
		} else {
			sharedI18nUtilInstance.allowRTL(getReactApplicationContext(), false);
			sharedI18nUtilInstance.forceRTL(getReactApplicationContext(), false);
		}

		return new LayoutFactory(appActivity,
                navigator().getChildRegistry(),
                reactInstanceManager,
                eventEmitter,
                externalComponentCreator(),
                navigator().getDefaultOptions()
        );
	}
```

Edit setRoot
```java
@ReactMethod
	public void setRoot(String commandId, ReadableMap rawLayoutTree, Promise promise) {
		final LayoutNode layoutTree = LayoutNodeParser.parse(JSONParser.parse(rawLayoutTree).optJSONObject("root"));
		handle(() -> {
            final ViewController viewController = newLayoutFactory(rawLayoutTree.getString("direction")).create(layoutTree);
            navigator().setRoot(viewController, new NativeCommandListener(commandId, promise, eventEmitter, now));
        });
	}
```

Also edit RNN Commands.js setRoot method:
```javascript
const direction = simpleApi.direction ? simpleApi.direction : 'ltr';
        const commandId = this.uniqueIdProvider.generate('setRoot');
        const result = this.nativeCommandsSender.setRoot(commandId, { direction, root, modals, overlays });
        this.commandsObserver.notify('setRoot', { commandId, layout: { direction, root, modals, overlays } });
```


Application:
```javascript
Navigation.setRoot({
+   direction: 'rtl',
      root: {
        ...
      }
    },
  });
```

**Comment by hadimostafapour** [comment]
# Workaround for iOS

#### 1. Edit `RNNCommandsHelper.m`: 

```objective-c
-(void) setRoot:(NSDictionary*)layout completion:(RNNTransitionCompletionBlock)completion {
	
	if (@available(iOS 9, *)) {
		if ([layout[@"direction"] isEqualToString:@"rtl"]) {
			[[RCTI18nUtil sharedInstance] allowRTL:YES];
			[[RCTI18nUtil sharedInstance] forceRTL:YES];
			[[UIView appearance] setSemanticContentAttribute:UISemanticContentAttributeForceRightToLeft];
			[[UINavigationBar appearance] setSemanticContentAttribute:UISemanticContentAttributeForceRightToLeft];
		} else {
			[[RCTI18nUtil sharedInstance] allowRTL:NO];
			[[RCTI18nUtil sharedInstance] forceRTL:NO];
			[[UIView appearance] setSemanticContentAttribute:UISemanticContentAttributeForceLeftToRight];
			[[UINavigationBar appearance] setSemanticContentAttribute:UISemanticContentAttributeForceLeftToRight];
		}
	}
	
	[self assertReady];
```

#### 2. Open __RNN__ `Commands.js` file and modify setRoot method: _(Same as android workaround)_
> pass direction param down to native module
```javascript
const direction = simpleApi.direction ? simpleApi.direction : 'ltr';
        const commandId = this.uniqueIdProvider.generate('setRoot');
        const result = this.nativeCommandsSender.setRoot(commandId, { direction, root, modals, overlays });
        this.commandsObserver.notify('setRoot', { commandId, layout: { direction, root, modals, overlays } });
```

Now you can choose layout direction by passing _direction_ param as following :
```javascript
Navigation.setRoot({
+   direction: 'rtl',
      root: {
        ...
      }
    },
  });
```

**Comment by aaalsubaie** [comment]
great tricks 💯 
looking forward for the official support.

**Comment by ghahremanifarali** [comment]
in ios:
#import <React/RCTI18nUtil.h>

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;
  [[RCTI18nUtil sharedInstance] allowRTL:YES];
  [[RCTI18nUtil sharedInstance] forceRTL:YES];

**Comment by bahmannejati** [comment]
Thanks, but i'm facing back gesture issue again (in IOS), stack layout direction is fine but swipe action is reverse.
Dragging should start from left side, but the stack start pushing out from right side (wrong swipe direction)
