### ISSUE TITLE
[v2] [iOS] When you `pop` to a view with `largeTitle` visible, it 'jumps' to the regular title size.

### ISSUE THREAD

**Issue by sejr** [wix/react-native-navigation#3490]
This is a minor animation issue, also seems to be present when selecting from a `bottomTab` component.

---
### Environment
* React Native Navigation version: Latest@alpha
* React Native version: Latest
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X Device

**Comment by sejr** [comment]
There is a similar jump effect that seems to be caused by topBar search controllers.

**Comment by ajharahmed** [comment]
Hi I’m not receiving any notification from Facebook

**Comment by ptmt** [comment]
Partially might be related to https://github.com/wix/react-native-navigation/pull/3501 (at least with searchbar). Can you provide a gif or code sample?
