### ISSUE TITLE
[V2] Removing topBar buttons when pushing screen doesn't work

### ISSUE THREAD

**Issue by jarrx** [wix/react-native-navigation#3496]
### Issue Description
When pushing a screen that got topBar buttons set by `static get options() {...},` it doesn't work removing those buttons as you push.

### Steps to Reproduce / Code Snippets / Screenshots
Code in screen thats get pushed:
```
  static get options() {
    return {
      topBar: {
        rightButtons: [{
          title: 'Edit',
          id: 'edit'
        }]
      }
    };
  }
```

When pushing
```
Navigation.push(this.props.componentId, {
        component: {
          name: 'myScreen',
          options: {
            topBar: {
              title: { text: 'Screen Title' },
              rightButtons: [],
            }
          }
        }
      });
````

---
### Environment
* React Native Navigation version: ^2.0.2394
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by ujwal-setlur** [comment]
I have this problem as well. It seems like the with every release, I have to change where I specify the topBar buttons. Quite frustrating...

**Comment by TylerNRobertson** [comment]
Just don't include top bar buttons on the component your pushing (like completely remove "rightButtons: []" and that works for me.

**Comment by jarrx** [comment]
Sure that works but you should be able to remove the buttons when you push anyway. Lets say you can navigate to the same screen from three paces, where from two of the places you are suppose to see the same buttons, but from the other you shouldn't. Then you have to define the same buttons twice.

**Comment by ruscoder** [comment]
This is still an issue.

**Comment by TylerNRobertson** [comment]
Utilizing the "mergeOptions" inside of the constructor of the screen you'r "pushing"  could solve your issue. I have never used "mergeOptions" with an await directly after a screens "push" call I've always set them (if i needed to) on the component level constructor if I can't set them on the push event. Let me know if this made any sense/helped.
