### ISSUE TITLE
[V2] setRoot Fade Animation?

### ISSUE THREAD

**Issue by luskin** [wix/react-native-navigation#3499]
### Issue Description

In V1 we could specify a nice fade animation when replacing the root screen, I can't seem to find any documentation anywhere allowing us to do the same with V2. Can anyone advise how to gracefully fade on `setRoot`?

---
### Environment
* React Native Navigation version: 2.0.2394
* React Native version: 0.55
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?):Device - Samsung S7

**Comment by TylerNRobertson** [comment]
Would really like to know how this is done. I remember how easy it was to implement in V1. You could just assign a prop and it just worked. The documentation on how animations work now in V2 is very obscure and not well written for people to actually use the libraries animation API effectively. As of now I personally haven't found/figured out how to implement the same effect in V2. Hopefully, this will be explained soon by the contributors to this project and properly outlined in the documentation.

**Comment by zirtuedeveloper** [comment]
@guyca please tell us example code for v2 fade in and fade out

**Comment by damathryx** [comment]
same here, is this feature ready?

**Comment by guyca** [comment]
Hey guys, modifying the `setRoot` animations is now supported. You can set it in default options before calling `setRoot` or declare the desired animations in the root options.
Note that this is implemented only on Android.

```js
Navigation.setDefaultOptions({
  animations: {
    setRoot: {
      alpha: {
        from: 0,
        to: 1,
        duration: 500
      }
    }
});
```

**Comment by rishabhpoddar** [comment]
Is there still no way to do this for iOS yet?

**Comment by guyca** [comment]
@yogevbd Is setting root animation not possible with the current animations api?

**Comment by yogevbd** [comment]
@guyca It is possible to implement it with the current api. I will implement it soon

**Comment by dmkmedina** [comment]
A simple crossdisolve on setRoot fulfilled our needs here. It doesn't cover all supported animations though.

**Comment by AbanoubNassem** [comment]
any news about this?

**Comment by TylerNRobertson** [comment]
This is still not working. You are unable to add setRoot animations on IOS.

**Comment by harveyconnor** [comment]
Any news on this working in iOS? @guyca

**Comment by abury** [comment]
We're after this as well. Doesn't seem to be any solution to this at the moment, which is really surprising.

**Comment by aijazbinqasim** [comment]
@guyca yes it is working fine On android.

**Comment by luskin** [comment]
nearly 1 1/2 years later since I originally posted this, any update?

**Comment by TylerNRobertson** [comment]
@luskin I agree it would be nice to get an update.

**Comment by cspicuzza** [comment]
Will setRoot fade animations be supported by iOS in RNN 5.0?

**Comment by ninjz** [comment]
I was able to get a fade-in animation when calling setRoot by modifying the setRoot function inside of RNNCommandsHandler.m doing this:

```objective-c
- (void)setRoot:(NSDictionary*)layout commandId:(NSString*)commandId completion:(RNNTransitionCompletionBlock)completion {
	[self assertReady];
    RNNAssertMainQueue();
	
	if (@available(iOS 9, *)) {
		if(_controllerFactory.defaultOptions.layout.direction.hasValue) {
			if ([_controllerFactory.defaultOptions.layout.direction.get isEqualToString:@"rtl"]) {
				[[RCTI18nUtil sharedInstance] allowRTL:YES];
				[[RCTI18nUtil sharedInstance] forceRTL:YES];
				[[UIView appearance] setSemanticContentAttribute:UISemanticContentAttributeForceRightToLeft];
				[[UINavigationBar appearance] setSemanticContentAttribute:UISemanticContentAttributeForceRightToLeft];
			} else {
				[[RCTI18nUtil sharedInstance] allowRTL:NO];
				[[RCTI18nUtil sharedInstance] forceRTL:NO];
				[[UIView appearance] setSemanticContentAttribute:UISemanticContentAttributeForceLeftToRight];
				[[UINavigationBar appearance] setSemanticContentAttribute:UISemanticContentAttributeForceLeftToRight];
			}
		}
	}
	
	[_modalManager dismissAllModalsAnimated:NO completion:nil];
	
	UIViewController *vc = [_controllerFactory createLayout:layout[@"root"]];
    vc.waitForRender = [vc.resolveOptionsWithDefault.animations.setRoot.waitForRender getWithDefaultValue:NO];
    
    /** START: Code Change */
    [vc setReactViewReadyCallback:^{
        _mainWindow.rootViewController = vc;
        [vc.view setNeedsDisplay];
        [UIView transitionWithView:_mainWindow
                          duration:0.5
                           options:UIViewAnimationOptionTransitionCrossDissolve
                        animations:^{
                            [vc.view.layer displayIfNeeded];
                        }
                        completion:nil];
        [_eventEmitter sendOnNavigationCommandCompletion:setRoot commandId:commandId params:@{@"layout": layout}];
        completion();
    }];
    /** END: Code Change */
    
	[vc render];
}

```

But extending this library to support this would be nice to have.

**Comment by nenjamin2405** [comment]
Many thanks for your code snippet @ninjz. It feels so good when it has fade animation for setRoot. Any plan to integrate @ninjz 's snippet to core react-native-navigation @guyca?
