### ISSUE TITLE
How does example-redux get away with not calling AppRegistry.registerComponent?

### ISSUE THREAD

**Issue by kenfehling** [wix/react-native-navigation#35]
I've tried integrating the steps to set up navigation using Redux, but I get this error:

`AwesomeProject has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.`

However example-redux runs fine so I'm missing something obviously, but I can't seem to see what. The only way I can get mine running is if I give one of my screens the ID `AwesomeProject` so it gets registered but this doesn't seem right.

**Comment by smooJitter** [comment]
Lol.  Can you post more of the code?

**Comment by kenfehling** [comment]
Sure, I've created a project which gets this error. It's based off the original Redux example. https://github.com/kenfehling/ReactNativeNavigationTest

**Comment by kenfehling** [comment]
Ohh nevermind, I had to run

> `rnpm install react-native-controllers`

and make the changes to AppDelegate.m
