### ISSUE TITLE
Sidemenu Deeplink not working 

### ISSUE THREAD

**Issue by ant-camp** [wix/react-native-navigation#350]
I have a sidebar and im clicking on the side menu link to go to the HomeView screen and the sidemenu closes but it doesn't redirect to the next screen.

Upgraded from 1.0 to 2.0 and its still not working.

```
<TouchableOpacity style={styles.drawerButtonStyle}
                      onPress={this.onReplaceTabHome }>
<View style={styles.menuLinks}>
<Icon
    name='fontawesome|home'
    size={17}
    color={"white"}
>
</Icon>

      <View style={styles.btnTxtSpacing}></View>
        <Text style={[styles.drawerButtonStyleText]}>
            Home
        </Text>
  </View>
    </TouchableOpacity>
       onReplaceTabHome() {
       this.props.navigator.toggleDrawer({
       to: 'closed',
      side: 'left',
      animated: true
   });

this.props.navigator.handleDeepLink({
  link: "App.HomeView"
});
},
```
---
### Environment
* React Native Navigation version: 2.0.0-experimental.127
* React Native version: 0.31.0
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
Hey @ant-camp 
Where is the deeplink [handled](https://github.com/wix/react-native-navigation/wiki/Deep-links#handling-deep-links)?

**Comment by ant-camp** [comment]
On the sidemenu screen.

now I'm getting 2 errors

maximum call stack size exceeded
property 'type' of undefined error


```
getInitialState: function () {
    this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent);
},

onNavigatorEvent(event) {
    // handle a deep link
    if (event.type == 'DeepLink') {
      const parts = event.link.split('/');
      console.log(parts[0]);
      if (parts[0] == 'App.FormView') {

        // handle the link somehow, usually run a this.props.navigator command
        
        this.props.navigator.handleDeepLink({
          link: "App.FormView"
        });

      }
    }
  },


  onReplaceTabTransaction() {
    this.props.navigator.toggleDrawer({
      to: 'closed',
      side: 'left',
      animated: true
    });

    this.props.navigator.handleDeepLink({
          link: "App.FormView"
        });
 
  },

**Comment by guyca** [comment]
I'm not sure I understand the code you've posted. Deeplink is simply an event you broadcast to your registered screens. You can see the [implementation in the example project](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/SideMenu.js).

1. [Broadcasting the deeplink from SideMenu](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/SideMenu.js#L35)
2. [Handling the deeplink in the desired screen](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/SecondTabScreen.js#L107)

Hope this helps you

**Comment by ant-camp** [comment]
@guyca reviewed the example projects

i setup my onNavigatorEvent func as following but its still just closing the drawer and not rendering new screen. 


```
onNavigatorEvent(event) {
    // handle a deep link
    console.log(event.type);
    if (event.type == 'DeepLink') {
      var parts = event.link.split('/');
      console.log(parts[0]);
      if (parts[0] == 'App.FormView') {

        // handle the link somehow, usually run a this.props.navigator command
        this.props.navigator.resetTo({
            title: "Replaced Root",
            screen: "App.FormView",
            animated: true
          });

      }
    }
  },
```

**Comment by guyca** [comment]
In which class is this function implemented? In your side menu or in the currently displayed screen?

**Comment by ant-camp** [comment]
@guyca the sidemenu

**Comment by ant-camp** [comment]
got it working. had to put it in current display screen instead of sidemenu
