### ISSUE TITLE
[v2] Global Animation Settings from SetDefaultOptions

### ISSUE THREAD

**Issue by thame** [wix/react-native-navigation#3500]
### Issue Description

Setting global animation settings do not work, settings are only animated from "Push" or "Pop" events.

### Steps to Reproduce / Code Snippets / Screenshots

Defining animation settings in SetDefaultOptions doesn't work, using the same code in a "Push" event does.

```
      animations: {
        push: {
          content: {
            y: {
              from: 1000, to: 0,
            }
          }
        }
      },
```

---
### Environment
* React Native Navigation version: 2.0.2397
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Only tested on iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 8 Device, iOS 11.4

**Comment by Lube** [comment]
Same happening for me on Android!

**Comment by guyca** [comment]
@Lube which RNN version do you have?

**Comment by skyflyer55** [comment]
animating the topBar seems to be broken as well for any functionality

**Comment by mths0x5f** [comment]
Indeeed, I couldn't **set default** animations at all for iOS. And I can confirm **setting default** animations for Android is only working for "push".

As already reported, settings animations in a screen-basis is working.

I'm using 2.0.2422 version, @guyca / @yogevbd

**Comment by clytras** [comment]
I can confirm @mths0x5f  fix https://github.com/wix/react-native-navigation/issues/3500#issuecomment-408696714 is working.

Any chance to have a PR? Is this on some king of a schedule?

**Comment by stefanc96** [comment]
Why on ios transition animations between screens doesn't work? On android works perfectly
