### ISSUE TITLE
portraitOnlyMode not working, device rotation restarts the app.

### ISSUE THREAD

**Issue by bogobogo** [wix/react-native-navigation#351]
### Issue Description

1) Can't disable landscape mode in my app, both android and iOS 
2) Every time I change the device rotation, my android app restarts 

### Steps to Reproduce / Code Snippets / Screenshots

My app was built using react-native-navigation-bootstrap in the Wix react-native hackathon. 

I have added `portraitOnlyMode: true`  to my startSingleScreenApp function 
and  `android:screenOrientation="portrait"
  android:configChanges="keyboard|keyboardHidden|orientation|screenSize"` to my AndroidManifest file and that did not solve the problem. 

Here is my startSingleScreenApp function: 

`Navigation.startSingleScreenApp({
      screen: {
             screen: 'Home',
             title: 'Home'
           },
      portraitOnlyMode: true
    });`

---
### Environment
* React Native Navigation version: 2.0.0-experimental.116
* React Native version: 0.31.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus X5, Android 6.0

**Comment by guyca** [comment]
Hey @bogobogo nice to see you again.
As you can see from the [commit history](https://github.com/wix/react-native-navigation/commits/master), `portraitOnlyMode` was added in .121 👍

**Comment by bogobogo** [comment]
Awesome, updating the RNN version worked. 
It's not relevant to me but just to let you know, the android app still restarts on device rotation if `portraitOnlyMode` is not set to true. 
I will check commit history next time before asking.
Thanks again @guyca

**Comment by dg92** [comment]
@bogobogo  i tried to update RNN for the same issue ..but got error 
`Cannot evaluate module react-native-navigation : Configuration with name 'libraryDebug' not found.`

was on RNN 2.0.0-experimental.105 
can you tell me how did you update ?

**Comment by guyca** [comment]
@dg92 Some Android boilerplate code has changed, check out the updated [Android installation guide](https://github.com/wix/react-native-navigation/wiki/Installation---Android)
