### ISSUE TITLE
[V2] Push a component with options, changes default options

### ISSUE THREAD

**Issue by hadimostafapour** [wix/react-native-navigation#3515]
### Issue Description
Pushing a component with options, cause update other components styles and options.
> Example. 
> I have elevation for my topBar by default, when I push a new component with no topBar elevation in my stack, all other components elevation gone.

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
Navigation.push(this.props.componentId, {
    component: {
        name: 'example.Tabs',
        options: {
            topBar: {
                background: {
                    color: '#00ff00',
                },
                borderColor: 'red',
                elevation: 0,
                title: {
                    text: 'Tabs',
                }
            }
        }
    }
});
```

Default:
![01](https://user-images.githubusercontent.com/33980142/42413726-9c5c9b78-823b-11e8-8ebc-fa81cb2799ed.png)

Push:
![02](https://user-images.githubusercontent.com/33980142/42413729-a4a9b900-823b-11e8-8d6d-ded8c3c313eb.png)

Back (Pop):
![03](https://user-images.githubusercontent.com/33980142/42413730-aa8c8c26-823b-11e8-904d-5462a1b8a678.png)

---
### Environment
* React Native Navigation version: 2.0.2397
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by onlaps** [comment]
TopBar options doesnt apply on pop()

**Comment by hadimostafapour** [comment]
@guyca could you please take a look into this issue?
Also if I set back button color to "white" as default options, When push a new screen back button color is "black" in first second then it turns to white color, actually blinks.
