### ISSUE TITLE
this.props.navigator.showLightBox not working

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#352]
### Issue Description

Hi, 
I tried to use showLightBox but i got the following error

undefined is not a function (evaluating '_platformSpecificDeprecated2.default.showListBox(params)')

when i replaced it with showModel, it worked as expected

 _onPressDescription(description){
         this.props.navigator.showLightBox({
      screen: 'example.DisplayDescription',
      style: {
        backgroundBlur: "dark", // 'dark' / 'light' / 'xlight' / 'none' - the type of blur on the background
        backgroundColor: "#ff000080" // tint color for the background, you can specify alpha here (optional)
        },
      passProps: { 
          DisplayText: description
      }
    });
    }

---
### Environment
- React Native Navigation version: 2
- React Native version: 0.25
- Platform(s) (iOS, Android, or both?): tested on Android only
- Device info (Simulator/Device? OS version? Debug/Release?): LG G3 Debug, OS version 5.0

**Comment by guyca** [comment]
Hey @Jaafar-abusair, lightbox is not implemented on Android.
I'm not entirely sure what out plans are for lightbox on Android, @DanielZlotin can probably shed some light on this matter.

**Comment by beast** [comment]
I actually did some research on this for Android. Android has a heads up notification which I personally dislike the user experience (for example, whatsapp). If you perform a google search for this, you will see all relevant results are about people asking how to disable it. I think it would be good to make iOS/Android consistent but the user experience of such should be noted. The main problem on Android is that the heads up notification could block the top of the app unless you do a swipe action and if you have a whatsapp group that is in conversation. It's almost impossible to get to the top of your app...

**Comment by Jaafar-abusair** [comment]
I'm sorry @beast but how that related to the light box?

**Comment by beast** [comment]
@Jaafar-abusair Ouch, sorry about that. We were implementing something on Android that mimic the heads up notification thinking about using lightbox. You could just ignore my previous comment.

**Comment by adamski** [comment]
I am using a modal with transparent overlay on Android. Only difference is it comes with its own nav bar. Would be nice to have a native lightbox on Android but its not a big deal for me.

**Comment by Jaafar-abusair** [comment]
@adamski well you can hide the navigation bar from the navigation style, you just need to set
 navigatorStyle: {
                navBarHidden: true
              }

**Comment by varungupta85** [comment]
@adamski @Jaafar-abusair Could you please share how you configured modal with transparent overlay. I am trying to show a modal with transparent/transluscent background but I am not able to get it to work. I tried setting the background color for the modal screen to transparent but that didn't work. Here is my modal screen component

```js
import React, {Component} from 'react';
import {
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  Dimensions
} from 'react-native';
import navigatorStyles from '../styles/navigationStyles'

export default class MessageModalScreen extends Component {
  static navigatorStyle = {
    navBarHidden: true
  }

  constructor(props) {
    super(props);
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.message}>
          {this.props.message}
        </Text>
        <TouchableOpacity onPress={ this.onDismissPress.bind(this) }>
          <Text style={styles.button}>Dismiss</Text>
        </TouchableOpacity>
      </View>
    );
  }

  onDismissPress() {
    this.props.navigator.dismissModal();
  }
}

var styles = StyleSheet.create({
  container: {
    flex: 1,
    width: Dimensions.get('window').width,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)' // Tried 'transparent' also
  },
  message: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
    paddingTop: 20
  },
  button: {
    textAlign: 'center',
    fontSize: 18,
    marginBottom: 10,
    marginTop:10,
    color: '#4692ad'
  }
});
```

It would be of great help if you could let me know how can I make the background of the modals transparent such that the user can still the app in the background.

**Comment by varungupta85** [comment]
Okay, it looks like adding transparency to the background color works on Android but not on iOS. Any pointers on how to make the modals background transparent for iOS as well.

**Comment by adamski** [comment]
@varungupta85 I'm using a lightbox on iOS, which takes its own style parameters e.g:
```
      this.props.navigator.showLightBox({
        screen: "myApp.showModal",
        title: "My Modal",
        style: {
          backgroundBlur: "none",
          backgroundColor: "#888888DD",
        },
        navigatorStyle: { ... }
    })

```

**Comment by varungupta85** [comment]
@adamski Thanks for the response 👍 . I didn't realize that the solution was right in front of me. :)

**Comment by guyca** [comment]
Lightbox is available on Android now.

**Comment by danielbertini** [comment]
@guyca but this.props.navigator.dismissLightBox(); not work on Android.
