### ISSUE TITLE
[V2] Android Navigator Style Color Change

### ISSUE THREAD

**Issue by luskin** [wix/react-native-navigation#3526]
### Issue Description

V2 documentation is missing information on how to set the navigator style on Android, has anybody come across the solution in V2?

You can set a color in your `styles.xml` like so: `<item name="android:statusBarColor">@color/black</item>` but this does not allow you to change it

![navigatorsytlemissing](https://user-images.githubusercontent.com/5702322/42476092-9a939f7a-8381-11e8-9cd2-c17a87a13c2e.png)

---
### Environment
* React Native Navigation version: 2.0.2394
* React Native version: 0.55
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung S7

**Comment by SudoPlz** [comment]
Any news on that? How do we change it's color?

**Comment by SudoPlz** [comment]
We can do that via this prop: https://wix.github.io/react-native-navigation/api/options-navigationBar/#backgroundcolor

I think we can close this now
