### ISSUE TITLE
[V2] Screen remains on reload

### ISSUE THREAD

**Issue by luskin** [wix/react-native-navigation#3528]
### Issue Description

On V2 if you have a screen visible and reload via debugger RNN keeps those screens open and remounts them before the app has a chance to reload properly:

```
Running application "Driver.Account" with appParams: {"initialProps":{"componentId":"Component13"},"rootTag":151}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
infoLog.js:15 Running application "Driver.History" with appParams: {"initialProps":{"componentId":"Component12"},"rootTag":161}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
infoLog.js:15 Running application "Driver.Dispatches" with appParams: {"initialProps":{"componentId":"Component11"},"rootTag":171}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
console.js:35 Running application "Driver.Launch" with appParams: {"initialProps":{"componentId":"Component1"},"rootTag":181}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
console.js:35 ---- START APP ----
```

In the above example from my app, all of those views (except the launch view) should not be visible until after the `START APP` log, and after the start app log there should be a series of services to startup before the views are visible. On a fresh install from android studio everything works fine as shown in the following logs:

```
Running application "Driver.Launch" with appParams: {"initialProps":{"componentId":"Component1"},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
console.js:35 ---- START APP ----
console.js:35 [CODEPUSH]: Started
console.js:35 [PERMISSION]: Checking
console.js:35 [APPSTATE]: Started service
console.js:35 [PERMISSION]: Location  authorized
console.js:35 [PERMISSION]: Notification authenticated (default android)
console.js:35 [AUTHENTICATION]: Authenticated as ***************************
console.js:35 [CODEPUSH]: Up To Date
console.js:35 [USER]: Started services
console.js:35 [ONBOARDING]: Started services
console.js:35 [DISPATCH]: Started
console.js:35 [ORGANIZATION]: Started services
console.js:35 [LOCATION]: Permission is authorized, begin tracking
console.js:35 [NOTIFICATION]: Permission granted setting up listener
console.js:35 [NOTIFICATION]: Started services
console.js:35 Running application "Driver.Account" with appParams: {"initialProps":{"componentId":"Component6"},"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
console.js:35 Running application "Driver.History" with appParams: {"initialProps":{"componentId":"Component5"},"rootTag":21}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
console.js:35 Running application "Driver.Dispatches" with appParams: {"initialProps":{"componentId":"Component4"},"rootTag":31}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
```

---
### Environment
* React Native Navigation version: 0.55
* React Native version: 2.0.2399
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug Samsung S7

**Comment by guyca** [comment]
Hey @luskin 
How is your layout constructed? Are you using TopTabs? BottomTabs? SideMenu?

**Comment by GuillotJessica** [comment]
you are on debug, this is a problem with RN 0.55

**Comment by luskin** [comment]
@guyca the Launch screen is a single page view set as root and when all services have loaded I reset the root with a bottom tab bar view.

@GuillotJessica I was using RN0.55 before with `react-native-navigation` v1 and this problem did not exist.

**Comment by GuillotJessica** [comment]
@luskin I'm on "react-native": "0.55.2",
 and the problem was there before using rnn at all

**Comment by guyca** [comment]
Guess we can close this one 😕
I'll reopen if we can confirm RNN has something to do with this

**Comment by luskin** [comment]
Looks like it was a 0.55 issue, very very strange we did not see it before implementing RNN, see here: https://github.com/facebook/react-native/commit/e5aa5b7c508c5e0e51f7abfcee350e27bef24ba2

**Comment by rendomnet** [comment]
@luskin I have this in rn 0.56

**Comment by luskin** [comment]
@rendomnet I think this may be a side effect of hot reloading or live reload, try turning those debug features off and see if this is still the case.

**Comment by rendomnet** [comment]
@luskin just tested without hotreloading. and bug remains the **same**.
setRoots that was active during app reaload is started first... before all.

**Comment by luskin** [comment]
Android, iOS or Both?

**Comment by rendomnet** [comment]
@luskin only Android

**Comment by luskin** [comment]
Yeah we've ran into this before as well, I believe this is due to Android's app caching for faster app launching in debug mode, I do not believe this occurs when building in release.

**Comment by rendomnet** [comment]
@luskin anyway this is a **bug** and not documented one.

**Comment by tylerjbainbridge** [comment]
I'm having this issue as well, not sure what to do.
