### ISSUE TITLE
Change between tabs on swap startTabBasedApp

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#353]
### Issue Description

How to switch between the tabs on figure gesture, when some one swap right or left on the screen

---
### Environment
* React Native Navigation version:  2.0 experimental 
* React Native version: 0.25
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): LG G3, OS 5.0

**Comment by guyca** [comment]
After you detected the gesture, call [switchToTab](https://github.com/wix/react-native-navigation/wiki/Screen-API#switchtotabparams--).
But I highly discourage you to do so, at least on Android. According to google [design guidelines](https://material.google.com/components/bottom-navigation.html#bottom-navigation-behavior), "Using swipe gestures on the content area does not navigate between views".
