### ISSUE TITLE
Customize Center Tab Bar

### ISSUE THREAD

**Issue by edys00** [wix/react-native-navigation#3531]
### Issue Description

Unable to create custom BottomTab where the center button is enlarged than the others like in this sample image. Should have been able to use a custom Component for the tab bar button like in react navigation. It would be more awesome seems some people did find these issue but no a proper solution for this.
![test](https://user-images.githubusercontent.com/40975424/42496963-df5209fa-8451-11e8-8d05-e08ff8045d89.png)

### Steps to Reproduce / Code Snippets / Screenshots

Create TabBasedApp Navigation but need the option to render custom component for tab bar preferably in the center tab bar.

---
### Environment
* React Native Navigation version: 1.1.462
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by TPMinan** [comment]
the problem continues. How to work ?

**Comment by arryanggaputra** [comment]
@TPMinan  I think that you already implement this

**Comment by TPMinan** [comment]
Yes I solved it with "showOverlay" method

**Comment by arryanggaputra** [comment]
@TPMinan  do you have email? I need your help man
