### ISSUE TITLE
[v2] Large title animation flicks with pull-to-refresh

### ISSUE THREAD

**Issue by gabrielvcbessa** [wix/react-native-navigation#3538]
Large title doesn't behavior as expected when you have pull to refresh on the screen. I don't know if this is an iOS or react-native-navigation bug.

With small title:

![small title](https://thumbs.gfycat.com/GlaringSilentBlackwidowspider-size_restricted.gif)

With large title:

![large title bug](https://thumbs.gfycat.com/PossibleApprehensiveGuineapig-size_restricted.gif)

---
### Environment
* React Native Navigation version: 2.0.2377
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS

**Comment by pibo** [comment]
+1

**Comment by dkpalmer** [comment]
> There are some workarounds but we could maybe add support for refresh control in header until then.

@birkir We just had this request come from our designer (refresh control in header). Is that possible today, or on the roadmap?

**Comment by dkpalmer** [comment]
Bump. Still hoping for some direction on this one. We've internally hacked some support in by hooking into the page scroll position and displaying some custom views in the header, but it's been less than ideal. We'd be happy to look at putting this in RNN directly.

**Comment by cesargdm** [comment]
Still happening

**Comment by sam3d** [comment]
This is not stale.

**Comment by sam3d** [comment]
Anyone have any updates on this?

**Comment by gabrielvcbessa** [comment]
@yogevbd @guyca

**Comment by hueyenclave** [comment]
Same issue. Do we have any update on this?

**Comment by juangamnik** [comment]
Still there... won‘t fix?

**Comment by gabrielvcbessa** [comment]
They closed this issue don't know why and just ignore it now. I am going to create a new one

**Comment by juangamnik** [comment]
@gabrielvcbessa thank you very much

**Comment by kneza23** [comment]
any hack maybe to fix this?
