### ISSUE TITLE
bottomTabSelected not responding in ^1.1.474

### ISSUE THREAD

**Issue by pribeh** [wix/react-native-navigation#3539]
After updating to 1.1.474, bottomTabSelected no longer responds. I'm not sure if it's related but navBarCustomView also stopped working for us with the update. @mhidou's fix resolves that issue but not this one – see https://github.com/wix/react-native-navigation/issues/3449.

### Steps to Reproduce / Code Snippets / Screenshots

Update to 1.1.474
Use anything like the following:

```
async onNavigatorEvent(event) {
  if (event.id === 'bottomTabSelected') {
    Alert.alert("WHAT!", "OMG!", [
	{ text: "Okay!", style: "cancel" },
    ]);
  }
}
```

---
### Environment
* React Native Navigation version: 1.1.474
* React Native version: ^0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator X, iPhone 6 and 5s

**Comment by guyca** [comment]
Hey @pribeh, I reverted the problematic commit in v1.1.475
