### ISSUE TITLE
Latest version v1.1.475 is not compiling due to incorrect commit reversion

### ISSUE THREAD

**Issue by guidolodetti** [wix/react-native-navigation#3541]
### Issue Description

Latest commit in master produces a compile error due to revert of [this commit
](9d4eea835ad83170c39c336c108ef2610c078f19) and [a commit](241349625f5a88a5e2d54f92157d75d7ec97850d) between the reversion and the previous change

**Comment by NaoyaKurahashi** [comment]
Hello guidolodetti, I have same problem so I created pull request. 
I checked build and work correctly reatct-native-navigation with project member.
https://github.com/wix/react-native-navigation/pull/3542

Thanks for creating issue.

**Comment by guyca** [comment]
Merged, Thanks @NaoyaKurahashi
