### ISSUE TITLE
[v2] iOS Top Bar Icon Tint Color [Missing Documentation]

### ISSUE THREAD

**Issue by luskin** [wix/react-native-navigation#3546]
RNN V2 doesn't seem to support setting the icon tint color on iOS for the navigation bar. We are using our own icons (with our specific colors) but iOS is force tinting them to their default blue. As far as documentation goes we don't see anything to set the tint color to our desired color or disable icon tinting. Our options code is as follows:

```
  static get options() {
    return {
      statusBar: {
        style: 'light'
      },
      topBar: {
        visible: true,
        title: { text: 'Loading', color: Colors.White },
        leftButtons: [{ id: 'close', icon: Icons.Navigation.CloseXWhite }],
        rightButtons: [{ id: 'support', icon: Icons.NavBar.ChatSupportWhite }],
        background: { color: Colors.Black },
      },
      layout: { orientation: ['portrait'] }
    }
  }
```

---
### Environment
* React Native Navigation version: 2.0.2399
* React Native version: 0.55
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Debug iOS iPhone X (Real Device)

**Comment by birkir** [comment]
```js
{
  topBar: {
    buttonColor: 'red',
  },
}
```

No support for individual button colors yet.

**Comment by ouabing** [comment]
After upgrading to 2.0.2452, all the buttons becomes blue, and I can't find a way to set the default back button color. The buttonColor option seems to be broken?

**Comment by LeVadim** [comment]
Correct, same here, all buttons are blue now.

**Comment by wolfgio** [comment]
Any update on this?

**Comment by mths0x5f** [comment]
This really an issue after 2.0.2452 upgrade. @guyca

**Comment by robobakery** [comment]
+1

when i don't set any color to icon, it forces tint with blue color on ios.

**Comment by waveChand** [comment]
I'm also getting this issue on ios, do anyone have a fix for this?

**Comment by exentrich** [comment]
This is dealbreaker for me. All topBar buttons are black in Android and iOS regardless 'topBar.buttonColor' value

**Comment by LeVadim** [comment]
Hello!
`        Navigation.setDefaultOptions({
            statusBar: {
                visible: true,
                style: 'light',
                backgroundColor: '#FFFFFF'
            },
            topBar: {
                background: {
                    color: '#000000'
                },
                title: {
                    color: '#FFFFFF'
                },
                subtitle: {
                    color: '#FFFFFF'
                },
                backButton: {
                    color: '#FFFFFF'
                },
                buttonColor: '#FFFFFF'
            },
            layout: {
                backgroundColor: '#FFFFFF'
            }
        });`

Please see if this code helps you, tintColor is working. Thank you!

**Comment by exentrich** [comment]
No this code is not works.
This is what I found, check source https://github.com/wix/react-native-navigation/blob/master/lib/ios/RNNTopBarOptions.m
As you can see there two separate options **leftButtonColor**, **rightButtonColor**
If you apply both, tint color will work. Seems to be documentation is outdated

**Comment by bitcrumb** [comment]
@eightyfive Wow. Thanks for clarifying this. Totally not clear from the documentation.

**Comment by rosskhanas** [comment]
> > Also backButton color is ignored in iOS when using any attributes
> 
> That must have been fixed. `topBar.backButton.color` works for me _BUT_ is not documented.
> 
> Bottom line:
> 
> ```js
> {
>   topBar: {
>     leftButtonColor: 'red',
>     rightButtonColor: 'red',
> 
>     backButton: {
>       color: 'red'
>     }
>   }
> }
> ```
> 
> Notes:
> 
> 1. `leftButtonColor` does _not_ apply to back button, use `backButton.color` instead
> 2. `(left|right)ButtonColor` only apply to [TopBar buttons](https://wix.github.io/react-native-navigation/#/docs/topBar-buttons)

It helps to change the color, thank you. However, in my case, the button is pressed it has some black background instead of being half transparent. 😢 

![image](https://user-images.githubusercontent.com/10609041/63657084-f73de400-c76a-11e9-8ed0-3adf1864d15e.png)
![image](https://user-images.githubusercontent.com/10609041/63657082-ef7e3f80-c76a-11e9-9d64-48c97d121250.png)

Anyone knows how to fix it?
