### ISSUE TITLE
Crash iOS - v127

### ISSUE THREAD

**Issue by olefritsch** [wix/react-native-navigation#355]
When I try to run my app I get the following error: "undefined is not an object (evaluating 'RCCManager.setRootController'). 

Everything is linked and imported correctly (as far as I can tell). I have tried this with in numerous ways with different versions of react-native and react-native-navigation.

Any help or clues are appreciated seems as thought I'm the only one to have encountered this issue.

-----------------------------CODE-----------------------------

screens.js:

import { Navigation } from 'react-native-navigation';
import GameOverview from './scenes/gameOverview/gameOverview';

export function registerScreens() {
    Navigation.registerComponent('qb.GameOverview', () => GameOverview);
}

index.ios.js

import { Navigation } from 'react-native-navigation';
import { registerScreens } from './screens';
registerScreens();

Navigation.startSingleScreenApp({
  screen: {
    screen: 'qb.GameOverview',
    title: 'Game Overview'
  }
});

Other imports are left out for clarity. 

----------EDIT----------
After uninstalling/reinstalling/setup etc I am not getting this error anymore, however my app simply crashes. 

---
### Environment
* React Native Navigation version: 2.0.0-Experimental.127 // Tested with 1.30.x as well
* React Native version: 0.31 // Tested with 0.34 as well
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 6 on Xcode 8

**Comment by iRoachie** [comment]
Encountering same problem

**Comment by beast** [comment]
This should work. The only thing I could think of is that the project is not still not linked properly somehow. The error you see is a clue that iOS module is not visible from javascript. Do you have your boiler project uploaded on github? I am using 2.0.0-Experimental.127 with RN33 without any issues. 

Another possibility is that your header search paths somehow resolves to a different place than the stock installation instruction. Not very likely but it happened once to myself before when I was playing with my project structure.

**Comment by olefritsch** [comment]
I'm working on a company app so I can't share the project for legal reason. 

I redid everything, uninstalled, reinstalled, etc. I am no longer getting this error, but my app crashes before I get the the start screen. Any other ideas?  I have tried this with both rnpm link as well as manually. I copied the AppDelegate.m file from the example project. I have no idea what else to try at this point.

**Comment by beast** [comment]
@olefritsch I am not suggesting you to provide the actual project you are working on. Did you try with just a boilerplate project? That is usually my starting point to find out whether it's a RN-Navigation package problem or setup problem.

**Comment by olefritsch** [comment]
Created a new project now to try and recreate the problem. No error and no crash this time, however my app is just showing a white screen. It should display "Hello World!" and a purple border so something is still wrong. I have uploaded that project in case you want to take a look, I am not sure however if that will apply to the problem I originally described.

https://github.com/olefritsch/example

**Comment by guyca** [comment]
@olefritsch Your `index.android.js` is not configured with RNN

**Comment by olefritsch** [comment]
I haven't configured Android, the problem I am encountering is on iOS

**Comment by olefritsch** [comment]
I must've missed something because I'm now getting a white screen in both projects.

**Comment by olefritsch** [comment]
I have somehow solved the issue. Re-configuring AppDelegate.m to look like the example project (full on copy-pasting this time!) seemed to solve the issue. 

@iRoachie Hope this helps you!

**Comment by beast** [comment]
Glad that you had it working but after I downloaded your project. I got the same undefined problem even though I checked all the linking as well. I am not sure if this problem magically goes away is a good thing. Did you create the project using react-native init or did you copy some boiler project? All my other 2 projects using RN Navigation never encounter this problem.

**Comment by vtsatskin** [comment]
I've been having a similar issue where if I am trying to integrate react-native-navigation into an existing React Native project on iOS, I get the same error as the original issue.

## Installation on fresh react native project
Following all of the [installation steps outlined](https://github.com/wix/react-native-navigation/wiki/Installation---iOS#installation---ios) on a fresh React Native project yields a working installation. 

```
react-native init testnav
yarn add react-native-navigation@next
react-native link 
```

Then editing the following files:

* AppDelegate.m to [exact copy outlined in instructions](https://github.com/wix/react-native-navigation/blob/master/example/ios/example/AppDelegate.m).
* index.ios.js:
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import { View } from 'react-native';
import { Provider } from 'react-redux'
import { Navigation } from 'react-native-navigation';

Navigation.registerComponent('example.FirstTabScreen', () => View);
Navigation.registerComponent('example.SecondTabScreen', () => View);

Navigation.startTabBasedApp({
  tabs: [
    {
      label: 'One',
      screen: 'example.FirstTabScreen', // this is a registered name for a screen
      // icon: require('../img/one.png'),
      // selectedIcon: require('../img/one_selected.png'), // iOS only
      title: 'Screen One'
    },
    {
      label: 'Two',
      screen: 'example.SecondTabScreen',
      // icon: require('../img/two.png'),
      // selectedIcon: require('../img/two_selected.png'), // iOS only
      title: 'Screen Two'
    }
  ]
});
```

Then compiling and running the packager:
```
react-native run-ios
```

This runs without any errors.

## Installation on an existing project

When doing the same steps outlined above on an existing react native project, the same error as the op occurs after running:
```
undefined is not an object (evaluating 'RCCManager.setRootController')
```

Interestingly enough, running the packager from the existing app's react native directory and then running the fresh react native app works fine.

## Environment
* react-native-navigation@2.0.0-experimental.142  
* react-native@0.37.0
* macOS 10.12.1 
* Xcode Version 8.1 (8B62)

**Comment by vtsatskin** [comment]
I've solved how to get react-native-navigation working in my existing project. I've updated my post above with how to fix it. See section "Copying working iOS Xcode project into Existing Project". However, there is not a clear diagnosis as to why this occurred in the first place.
