### ISSUE TITLE
[V1 - V2] LargeTitle bug (iOS)

### ISSUE THREAD

**Issue by jelleM** [wix/react-native-navigation#3551]
### Issue Description

When using `largeTitle: true` on iOS the transition between the large title and the small title seems to cause weird behaviour on View components that use `bottom: 16` and` position: 'absolute'`

### Steps to Reproduce / Code Snippets / Screenshots

The FAB on the bottom sometimes jumps when scrolling through the flatlist. 

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/10854309/42695249-0f8aac48-86b5-11e8-8054-fd07be11179e.gif)

---
### Environment
* React Native Navigation version: 1.1.476
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator- iPhone 8 - 11.3

Happens in V1 and V2

**Comment by abury** [comment]
I've noticed this as well. It looks like it's trying to adjust the position on the fly

**Comment by hahtml** [comment]
Bump. This still happens to v2.
