### ISSUE TITLE
[v2] [ios] tabBar visible but set to false

### ISSUE THREAD

**Issue by GuillotJessica** [wix/react-native-navigation#3553]
having a similar problem on android i set Navigation.setDefaultOptions to 
```
topBar: {
        // todo follow this issue for topBar still displays with visible to false
        // https://github.com/wix/react-native-navigation/issues/3416
        visible: false,
        drawBehind: true,
    },
```
android is fine then but topBar remains on IOS

    "react-native": "0.55.2",
    "react-native-navigation": "2.0.2367",

I really need a solution asap...

**Comment by skyflyer55** [comment]
Are you setting the visibility to true in your defaultOptions?
