### ISSUE TITLE
navBarHideOnScroll not working on Android 

### ISSUE THREAD

**Issue by junedomingo** [wix/react-native-navigation#356]
### Environment
- React Native Navigation version: 2.0.0-experimental.127
- React Native version: 0.32.0
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Android  5.0 +

**Comment by guyca** [comment]
We had to scrap the previous implementation for `navBarHideOnScroll` on Android because of bug in RN, which was recently fixed, when flinging the ListView.
