### ISSUE TITLE
[V2]Navigation.events().bindComponent(this) do not work ? react-native-navigation: "2.0.2381"

### ISSUE THREAD

**Issue by LuuLinhSon** [wix/react-native-navigation#3562]
![simulator screen shot - iphone x - 2018-07-16 at 11 37 33](https://user-images.githubusercontent.com/28147783/42743431-f1aa108e-88ed-11e8-949a-36d1efde0da5.png)

    import { Navigation } from "react-native-navigation";    
    constructor(props) { 
          super(props);
          Navigation.events().bindComponent(this); 
    }

**Comment by geirr** [comment]
It was added in 2.0.2406

**Comment by LuuLinhSon** [comment]
@geirr thank you. It's working

**Comment by GitHubGreg** [comment]
Thanks.

**Comment by HemrajLodha** [comment]
getting same issue in 2.1.2

**Comment by mehulnahar** [comment]
Is there anyway to refresh bottom tabs in "react-native-navigation": "^1.1.316"?
