### ISSUE TITLE
[v2] showModal with custom animation type

### ISSUE THREAD

**Issue by hiradarshadi** [wix/react-native-navigation#3563]
### Issue Description

I used to use wix navigation v1 for my projects, and I was able to set animationType within my showModal function :
```
this.props.navigator.showModal(
  screen: 'example.ModalScreen',
  animationType: 'none'
)
```
but in wix v2, there is no way to do so. default animation type for me is slide-up, and I don't want that. I tried setDefaultOptions with the following opitons: 
```
        animations: {
            showModal: {
                alpha: {
                    from: 0,
                    to: 1,
                    duration: 5,
                    startDelay: 0,
                },
                y: {
                    from: 0,
                    to: 0,
                    duration: 5,
                    startDelay: 0,
                }
            }
        }
```

**Comment by guyca** [comment]
Hey there, on which platform are you experiencing this issue and which RNN version are you using?

**Comment by hiradarshadi** [comment]
@guyca I'm using RNN 2.0.2381
I'm also using React Native 0.51.0, React 16.0

**Comment by voidstarfire** [comment]
Did anyone figure this out? I can't find any documentation on how to animate modals or overlays?

**Comment by wangwailok** [comment]
> Did anyone figure this out? I can't find any documentation on how to animate modals or overlays?

There was nearly no example code and instructions on the doc....its just a list of API

**Comment by Abramovick** [comment]
Any updates on this?

**Comment by brandtnewww** [comment]
I'm also having this problem.

**Comment by pribeh** [comment]
It would appear as if custom animations for modals and overlays are not supported.

**Comment by pedrobertao** [comment]
Was this fixed ?

**Comment by ollydixon** [comment]
What it feels like to develop on React Native now.
Just loads of unsupported libraries.
