### ISSUE TITLE
Using v1 with the RN v0.56?

### ISSUE THREAD

**Issue by ziyafenn** [wix/react-native-navigation#3564]
Hey guys. Did someone already try to upgrade RN to [v0.56](https://github.com/facebook/react-native/releases) using navigation v1 ?

As RN introduced quite a lot of environmental upgrades, i was failing to make it work with rn-nav v1.

Would be happy to hear thoughts.

**Comment by nanndoj** [comment]
I upgraded successfully RN to `v0.56`. It is working fine for on iOS but it broke the build in Android:

````
Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
````
file: `node_modules/react-native-navigation/android/app/build/intermediates/res/merged/debug/values-v26/values-v26.xml`

**Comment by ziyafenn** [comment]
@nanndoj yep, that's exactly my case.

**Comment by linnett** [comment]
It appears that v2 is way off production ready. Which is worrying for people invested in v1 as we cannot upgrade React Native...

**Comment by Surbhiairan** [comment]
Build failing in android after upgrading rn to 0.56.0.
What is the solution?

**Comment by MirGhojam** [comment]
@Surbhiairan After I upgraded gradle as Android Studio said, the error is gone and project built successfully

**Comment by Surbhiairan** [comment]
@MirGhojam Can you share a link for upgrading gradle?

**Comment by nextdots** [comment]
@ziyafenn  @nanndoj  @linnett  @Surbhiairan  @MirGhojam  anyone?

**Comment by mdelclaro** [comment]
...anyone?

**Comment by nextdots** [comment]
@mdelclaro  I have to Downgrade to 0.55.4 to make it work...

**Comment by jamestsang** [comment]
@mdelclaro I tried this [solution](https://github.com/wix/react-native-navigation/issues/2209#issuecomment-405843895). It work for me
