### ISSUE TITLE
Shared Element Transition issues

### ISSUE THREAD

**Issue by yedidyak** [wix/react-native-navigation#3565]
Using shared element transition to animate a number of elements text and images between two screens A and B.

Screen A has no navBar, screen B does.

* When wrapping elements in <Navigation.Element> Image elements are pushed down in screen A by about the size of the nav bar or safe area. Text elements are not though. 

* When animating, the items animate up farther than they are eventually drawn in screenB.

* When they are drawn in their final positions in screen B, they are drawn behind the navBar despite screenB having topBar options of drawBehind: false or undefined. Without the animation screenB is shown as it should be.

Environment:

* React Native Navigation version: 2.0.2412
* React Native version: 51
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone X

**Comment by birkir** [comment]
Have you tried to use the `drawUnder` property, you can use ScrollView to make sure content will not render under the navBar

**Comment by skumarcm** [comment]
Is this issue resolved?
I am facing the following issue:
In iOS, while transitioning from screen A to screen B (both with navbar), the shared element goes too far initially to hide under the navbar and then redraws at the current position.

**Comment by ThoMiDev** [comment]
Is this issue resolved?

**Comment by nomoreboredom** [comment]
I am also experiencing this
