### ISSUE TITLE
[V2] Bottom Tabs Touch Handler Delayed

### ISSUE THREAD

**Issue by luskin** [wix/react-native-navigation#3567]
### Issue Description

We have been working with V2 for a while now and noticing that the bottom tab buttons are often delayed after touch, sometimes as bad as a second or two after tapping them. Is this already a known issue? Unfortunately there's not much I can do in the way of providing logs for this bug. Additionally sometimes when tapping the last bottomTab it will actually select the first one instead. These two issues combined makes me thing there is some bad logic in the touch handler for the bottom bar.

### Steps to Reproduce / Code Snippets / Screenshots

```
export const start = () => {
  Navigation.events().registerAppLaunchedListener(() => {
    setDefaultNavigationStyleOptions()
    startComponentDidAppearListener()
    Navigation.setRoot({
      root: {
        component: {
          name: Screens.Launch
        }
      }
    })
  })
}

export const setDefaultNavigationStyleOptions = () => {
  Navigation.setDefaultOptions({
    layout: { orientation: ['portrait'] },
    topBar: {
      buttonColor: Colors.Blue
    },
    bottomTabs: {
      titleDisplayMode: 'alwaysShow',
      backgroundColor: Colors.Black
    }
  })
}

export const launchMainApp = () => {
  Navigation.setRoot({
    root: {
      bottomTabs: {
        children: [
          MainAppTab(Screens.Dispatches, 'Dispatches', Icons.TabBar.Dispatches),
          MainAppTab(Screens.History, 'History', Icons.TabBar.History),
          MainAppTab(Screens.Account, 'Account', Icons.TabBar.Account)
        ],
        options: {

        }
      }
    }
  })
}

const MainAppTab = (screen, title, icon) => ({
  stack: {
    id: screen,
    children: [
      {
        component: {
          name: screen
        }
      }
    ],
    options: {
      bottomTabs: {
        visible: true,
        animate: false,
        currentTabIndex: 0,
        drawBehind: false,
        backgroundColor: Colors.Black
      },
      bottomTab: {
        text: title,
        icon: icon,
        selectedIcon: icon,
        textColor: Colors.White,
        selectedTextColor: Colors.Yellow,
        selectedIconColor: Colors.Yellow,
        iconColor: Colors.White,
        fontSize: 10
      }
    }
  }
})

export const startComponentDidAppearListener = () => {
  Navigation.events().registerComponentDidAppearListener(({ componentId, componentName }) => {
    Analytics.Screen.viewed(componentName)
  })
}
```

---
### Environment
* React Native Navigation version: 2.0.2415
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both Physical iPhone X and Simulator

**Comment by davrosull** [comment]
@luskin I had the same issue the other day. Cause of the problem is setting `currentTabIndex` on the `bottomTabs` properties. From what I can gather, every time you press a tab, it merges those options in and sets the currentTab to the first tab.

**Comment by luskin** [comment]
Thanks @davrosull but unfortunately this does not solve the problem. On bottom tab selection on both simulator and iPhone X device the touch handler is significantly delayed still.
