### ISSUE TITLE
[v2] bottomTabs root configuration not respecting bottomTab text for stacks

### ISSUE THREAD

**Issue by zachrnolan** [wix/react-native-navigation#3568]
### Issue Description

When using a stack within bottomTabs, the bottomTab text field is not respected. Here is my root configuration:

```js
import { Navigation } from 'react-native-navigation'
import { registerScreens } from './src/screens'

registerScreens()

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      bottomTabs: {
        children: [
          {
            stack: {
              children: [
                {
                  component: {
                    name: 'Home'
                  }
                }
              ],
              options: {
                topBar: {
                  title: {
                    text: 'Home'
                  }
                },
                bottomTab: {
                  text: 'Tab 1'
                }
              }
            }
          },
          {
            component: {
              name: 'Profile',
              options: {
                bottomTab: {
                  text: 'Tab 2'
                }
              }
            }
          }
        ],
        options: {}
      }
    }
  })
})
```

If I change this to only components, it works fine:

```js
import { Navigation } from 'react-native-navigation'
import { registerScreens } from './src/screens'

registerScreens()

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      bottomTabs: {
        children: [
          {
            component: {
              name: 'Home',
              options: {
                bottomTab: {
                  text: 'Tab 1'
                }
              }
            }
          },
          {
            component: {
              name: 'Profile',
              options: {
                bottomTab: {
                  text: 'Tab 2'
                }
              }
            }
          }
        ],
        options: {}
      }
    }
  })
})
```

### Steps to Reproduce / Code Snippets / Screenshots

Screenshot with stack:
![iphone_6_-_11_4](https://user-images.githubusercontent.com/66614/42795266-3866e7e6-8938-11e8-8b28-03692e0733f0.jpg)

Screenshot with only components:
![iphone_6_-_11_4](https://user-images.githubusercontent.com/66614/42795280-42c2c728-8938-11e8-82c2-4ac531247a2b.jpg)

---
### Environment
* React Native Navigation version: 2.0.2411
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS (haven't tested this on Android yet)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug

**Comment by TimurAsayonok** [comment]
Yes, I have same with 2.0.2453.

And main problem, than when we use `stack: ` we can see `topBar` and do what we want with tap bar. But when we don't use  `stack: ` we can't work with `topBar`

**Comment by lindesvard** [comment]
Having exact same problem, bottomTab text not displaying while inside a stack.

**Comment by JoelFieldCode** [comment]
@lindesvard do you have a logo set for the bottomTab? I was having this issue until I put a logo in. Silly fix I know but it has seemed to work for me.

**Comment by TimurAsayonok** [comment]
@JoelFieldCode Why sis you say 'Silly fix..' ?) How many applications do you know without Icons on the  bottomTabs?)

**Comment by lindesvard** [comment]
@JoelFieldCode no, just played around a bit to see if it was ready or not. Everything worked fine except this issue. Maybe should try add icon also...
