### ISSUE TITLE
[v2] cannot use a swipeable element on iOS when using side drawer

### ISSUE THREAD

**Issue by ujwal-setlur** [wix/react-native-navigation#3575]
### Issue Description

I am using a swipable list view (from native-base) in a tab view layout that has a **left** side drawer. I want to swipe left from the **right**, but it does not work on iOS. it works on android. on iOS, I can drag it only for about 10 pixels.

### Steps to Reproduce / Code Snippets / Screenshots

<img width="302" alt="screen shot 2018-07-17 at 4 05 08 pm" src="https://user-images.githubusercontent.com/5835869/42850153-3b9f821c-89db-11e8-9923-23d386f41510.png">
<img width="282" alt="screen shot 2018-07-17 at 4 06 56 pm" src="https://user-images.githubusercontent.com/5835869/42850232-772e858a-89db-11e8-9131-6af57c423e60.png">

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 2.0.2.412
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by ujwal-setlur** [comment]
If I don't use a side drawer, it works. But I do need the side drawer :-)

**Comment by ujwal-setlur** [comment]
I can work around this by returning ```MMOpenDrawerGestureModeNone``` in 

```
-(MMOpenDrawerGestureMode)possibleOpenGestureModesForGestureRecognizer
```

It essentially disables opening the side menu with a gesture...

I will play around with this a bit to see if I can find a happy middle ground.

**Comment by ujwal-setlur** [comment]
I see an interesting callback in ```MMDrawerController.h``` and ```MMDrawerController.m```:

```setGestureShouldRecognizeTouchBlock```

from the documentation in the ```MMDrawerController.h```:

```
/**
 Sets a callback to be called to determine if a UIGestureRecognizer should recieve the given UITouch.
 
 This block provides a way to allow a gesture to be recognized with custom logic. For example, you may have a certain part of your view that should accept a pan gesture recognizer to open the drawer, but not another a part. If you return YES, the gesture is recognized and the appropriate action is taken. This provides similar support to how Facebook allows you to pan on the background view of the main table view, but not the content itself. You can inspect the `openSide` property of the `drawerController` to determine the current state of the drawer, and apply the appropriate logic within your block.
 
 Note that either `openDrawerGestureModeMask` must contain `MMOpenDrawerGestureModeCustom`, or `closeDrawerGestureModeMask` must contain `MMCloseDrawerGestureModeCustom` for this block to be consulted.
 
 @param gestureShouldRecognizeTouchBlock A block object to be called to determine if the given `touch` should be recognized by the given gesture.
 */
-(void)setGestureShouldRecognizeTouchBlock:(BOOL(^)(MMDrawerController * drawerController, UIGestureRecognizer * gesture, UITouch * touch))gestureShouldRecognizeTouchBlock;
```

But I do not see any hooks into the JavaScript world. How do I use this from JavaScript?

**Comment by ujwal-setlur** [comment]
for now, this patch works for me:

```objective-c
--- a/node_modules/react-native-navigation/lib/ios/RNNSideMenu/MMDrawerController/MMDrawerController.m
+++ b/node_modules/react-native-navigation/lib/ios/RNNSideMenu/MMDrawerController/MMDrawerController.m
@@ -1446,9 +1446,6 @@ -(MMCloseDrawerGestureMode)possibleCloseGestureModesForGestureRecognizer:(UIGest
         if([self isPointContainedWithinNavigationRect:point]){
             possibleCloseGestureModes |= MMCloseDrawerGestureModePanningNavigationBar;
         }
-        if([self isPointContainedWithinCenterViewContentRect:point]){
-            possibleCloseGestureModes |= MMCloseDrawerGestureModePanningCenterView;
-        }
         if([self isPointContainedWithinRightBezelRect:point] &&
            self.openSide == MMDrawerSideLeft){
             possibleCloseGestureModes |= MMCloseDrawerGestureModeBezelPanningCenterView;
```

**Comment by mths0x5f** [comment]
And with that, you still use the gesture to open the drawer?

**Comment by ujwal-setlur** [comment]
@mths0x5f, yes that still works.

**Comment by ujwal-setlur** [comment]
This issue got absolutely no comments from the development team

**Comment by ujwal-setlur** [comment]
Anyway, I am now using react-native-gesture-handler and its swipeable component, and it seems to work with RNN. But very unfortunate that this issue got closed without actual resolution.

**Comment by mtzfactory** [comment]
Hi @ujwal-setlur ,

Do you have a minnimal demo? Can you share it?

Thanks.

**Comment by ujwal-setlur** [comment]
Hi @mtzfactory, I have moved away from react-native-navigation to react-navigation, so I don't have a ready demo. But from what I recall, I had a tabView with one of the tabs showing a list view, and the list item was to swipe-able with react-native-swipeable row. That did not work.

**Comment by vshkl** [comment]
Hello, @mtzfactory. This issue still persists, so I've made a demo. Here it is: https://github.com/vshkl/RNNDemo

Some clarification: at the first screen you should see two items: the first one is for enabling/disabling side menu, 'cuz the issue occurs only when side menu enabled, and the second one is the swipable item itself. You will be able to swipe the item only when the side menu is disabled. That's the issue.
`react-native-swipeable-row` is used it this demo, however, I've checked some other similar solutions and they lead to the same result.

Demo made with:
```json
"react-native": "0.57.5",
"react-native-navigation": "2.1.3",
```

Note: there is a "Reset Root" button in the side menu. Don't pay attention to it. It's for another issue 🙂

**Comment by ItsNoHax** [comment]
@guyca Could you please re-open this issue

**Comment by yogevbd** [comment]
5f16bb3 let you set `openGestureMode` option:
```
sideMenu: {
  openGestureMode: 'bezel'
}
```
