### ISSUE TITLE
I have new simple redux example application

### ISSUE THREAD

**Issue by developer239** [wix/react-native-navigation#3577]
Hey, guys, 🙂
I remember that when I was starting out with your navigation about a year ago it took me some time to find a simple example that would show me how to use up-to-date integration with redux.

I updated my example repository couple of days ago and a friend of mine told me that I could share it in your official repository.

What I have is basically a minimal example that is supposed to show people

- how basic project setup looks like
- how to do simple screen transitions
- how to call simple redux action creators

The application is very simple but I also decided to write unit tests.

Maybe I can create a pull request and replace the old-example-redux repository? 

https://github.com/developer239/react-native-redux-wix-navigation

![preview](https://user-images.githubusercontent.com/14946081/42891497-cc9f2554-8aaf-11e8-869c-4c914f2386f7.gif)

**Comment by birkir** [comment]
mobx-state-tree man!

**Comment by developer239** [comment]
@birkir I was thought about getting rid of redux and replace it with GraphQL. However, somehow I feel like the current setup is easier for beginners. 😄

**Comment by rfdc** [comment]
It would be great if you used V2 instead. :)

**Comment by guyca** [comment]
Hey @developer239, Thanks a lot for sharing your setup 🙇 
Feel free to PR it to the documentation, or even better migrate it to v2 as v2 will be merged pretty soon to master 👍

**Comment by developer239** [comment]
I will migrate it to version 2 this weekend. I wasn't sure how long it will take you to finish it. That sounds pretty exciting. 🙂
