### ISSUE TITLE
[v2][android] Linking event listener not firing on Android

### ISSUE THREAD

**Issue by davrosull** [wix/react-native-navigation#3581]
### Issue Description

On Android using RNN v2, the Linking 'url' event listener does not fire.

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
const { Navigation } = require('react-native-navigation');
const { registerScreens } = require('./screens');
const { Platform } = require('react-native');

function start() {
  registerScreens();
  Navigation.events().registerAppLaunchedListener(() => {
     Linking.addEventListener("url", event => {
        console.log("url", { event });
     });
     // Other code to launch app
  }) 
}
```

Then calling`yourapp://this-is-a-url` to launch your app never triggers the event listener.

Using `Linking.getInitialURL` will show the URL if the app is being launched.
```javascript
 Linking.getInitialURL().then(url => {
          if (url) {
          console.log("Initial url is: " + url);
        }
});
```

I've tested this with both ` android:launchMode="singleTask"` enabled and disabled in the `AndroidManifest.xml` and the result is the same each time.

---
### Environment
* React Native Navigation version: 2.0.2415
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):Simulator and Device. Android 8.1.0

**Comment by davrosull** [comment]
Follow up: `Linking` is working as expected using React Native 0.55.4 and RNNv1.  Could it be released to the bump in Android build tools for RNNv2?

**Comment by Darkilen** [comment]
Hello,
I'm not able to get the Linking 'url' event too.

### Environment
- React Native Navigation version: 2.0.2438
- React Native version: 0.56.0
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?):Device - Android 8.1.0

**Comment by Darkilen** [comment]
Hello,
I'm not able to get the Linking 'url' event too.

### Environment
- React Native Navigation version: 2.0.2438
- React Native version: 0.56.0
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?):Device - Android 8.1.0

**Comment by HerrR** [comment]
I'm having the same issue ☝️
