### ISSUE TITLE
Support for android: compileSdkVersion 27

### ISSUE THREAD

**Issue by sarthak-sehgal** [wix/react-native-navigation#3583]
### Issue Description
Is react native navigation supported for SDK version 27?

### Steps to Reproduce / Code Snippets / Screenshots
1. Setup react native navigation for android
2. In android/app/build.gradle, change "compileSdkVersion" to 27 and "buildToolsVersion" to 27.0.3

The app builds successfully but a white screen is displayed on startup.
---
### Environment
* React Native Navigation version: 1.1.476
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
Should work, don't think compile sdk version relates to white screens.

**Comment by sarthak-sehgal** [comment]
@guyca 
The app is working fine on SDK version 25 (as mentioned in the docs) but it is not working on SDK version 27 (white screen appearing)
