### ISSUE TITLE
StatusBar disappear after a push command 

### ISSUE THREAD

**Issue by Jose4gg** [wix/react-native-navigation#3584]
### Issue Description

If I push a scene the statusBar becomes hidden and if I open a modal with the modal presentation fullScreen, the statusBar shows up again.

### Steps to Reproduce / Code Snippets / Screenshots

- Push a scene
- show a Modal

---
### Environment
* React Native Navigation version: 2.0.2410
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): IOS 11.x

**Comment by Peeeep** [comment]
No idea why, but adding a statusBar style option seems to fix it for now:

```javascript
Navigation.push(this.props.componentId, {
  component: {
    name: 'PushItRealGoodComponent',
    options: {
      statusBar: {
        style: 'light', // or 'dark'
      },
    },
  },
})

**Comment by Jose4gg** [comment]
Thanks!, now, I'm just curious why it needs that to work everytime
