### ISSUE TITLE
[v2] Shared element not working  

### ISSUE THREAD

**Issue by odorukeyboard** [wix/react-native-navigation#3588]
### Issue Description

Playground not working

'NSInvalidArgumentException', reason: 'elementId title2 does not exist'

---
### Environment
* React Native Navigation version: 2.0.2418
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/iPhone8

**Comment by rendomnet** [comment]
same thing. Not working? Any comments from dev? Is it suppose to work?
