### ISSUE TITLE
[v2] Replace stack initialized with bottomTabs

### ISSUE THREAD

**Issue by habovh** [wix/react-native-navigation#3592]
### Issue Description

Hi,
I'm initializing my app with `bottomTabs`, and I'm trying to figure out how can I update one of the tab's stack using `setStackRoot`.
I'm not sure this is the way to go, but the behavior I'm trying to reproduce is to actually replace the topmost screen in the current stack without animation as following:

> → means the screen on the right is on top of the screen on the left

Using `push` I can achieve this:
1. TabRoot
2. TabRoot → Form
3. TabRoot → Form → FormResults

But I'd like the final stack not to include the form, like so:
1. TabRoot
2. TabRoot → Form
3. TabRoot → FormResults

Hence, replacing the topmost Form component with FormResults.

### Code Snippets

How I initialize my app:

```js
Navigation.setRoot({
    root: {
        bottomTabs: {
             children: [
                 {
                     stack: {
                         id: 'TAB1_STACK',
                         children: [{
                             component: {
                                 name: 'TabRoot',
                             }
                         }],
                         options: {
                             bottomTab: {
                                 text: 'Tab 1',
                             }
                         }
                     }
                 },
                 [... other tabs here]
             ]
        }
    }
})
```

How I try to replace the topmost component, when the Form is sent:

```js
Navigation.setStackRoot('TAB1_STACK', {
    stack: {
        children: [
            {
                component: {
                    name: 'TabRoot'
                }
            },
            {
                component: {
                    name: 'FormResults',
                    passProps: { formId: 1 }
                }
            },
        ],
    }
})
```

When I call this, I get the following error:

> UINavigationControllers are not allowed in a navigation controller!
> was thrown while invoking setStackRoot on target RNNBridgeModule with params...

![simulator screen shot - iphone x - 2018-07-20 at 18 05 08](https://user-images.githubusercontent.com/4186230/43012816-731de062-8c47-11e8-823b-7e74c5b724f2.png)

So I'm obviously doing something wrong but I can't figure out what it is. Or maybe my approach to the problem is just flawed and I should use another technique to achieve what I want. Since the docs are a little bit sparse `setStackRoot` seemed the best way to solve this.

I took inspiration from this issue as well: #3477, but I'm not sure the author got something to work, or maybe it's different while I'm initializing the root using bottomTabs.

Any help or insight on this appreciated!

---
### Environment
* React Native Navigation version: `2.0.2418`
* React Native version: `0.53.3`
* Platform(s) (iOS, Android, or both?): iOS
* Device info: Simulator, iOS 11, Debug

**Comment by habovh** [comment]
Little update on this.

As it turns out, `setStackRoot` is the actual proper way of doing this.
I was able to get something to work using the same initial setup, and the following `setStackRoot` call:

```js
Navigation.setStackRoot('TAB1_STACK', {
  bottomTabs: {
    children: [
      {
        stack: {
          children: [
            { component: { name: 'TabRoot' } },
            { component: { name: 'FormResults', passProps: { formId: 1 } } },
          ]
        }
      }
    ]
  }
})
```

Basically, I had to call `setStackRoot` using the same ROOT layout initialized using `setRoot`. It may seem obvious now, but I thought using `bottomTabs` here would require me to redefine every tab of the app. Turns out it's not the case.

**BUT** (yes, there is one issue with this), initializing `bottomTabs` with a `stack` children that has more than one `component` leads to an empty `bottomTab`. Both the name and icon disappears. I've even tried initializing my app (using `setRoot`) with bottomTabs that has one stacked child or two stacked children, and in the latter case, it seems that the stack's options are ignored. And since these options hold the `bottomTab` data, the corresponding tab gets its icon and name wiped, or never initialized. I'm closing this issue, and opening another issue for the multi-children stack bottomTab options.

**Comment by henrikra** [comment]
@habovh Can you check my PR? It looks like it will fix your issue as well https://github.com/wix/react-native-navigation/pull/4434

**Comment by habovh** [comment]
@henrikra thanks for pointing out your PR, however my particular case was detailed in issue #3624 as mentioned above. Maybe the detail you’ll find there might help you out, in any case, this issue is closed because I did not encounter the issue anymore.
