### ISSUE TITLE
Back button font family

### ISSUE THREAD

**Issue by chrise86** [wix/react-native-navigation#3596]
Is there any way to set the font family of the back button in the top bar?

---
### Environment
* React Native Navigation version:  `2.0.2415`
* React Native version: `0.56.0`
* Platform(s): `iOS`
* Device info: Simulator, debug

**Comment by chrise86** [comment]
Well not solely for the back button, just none of the options seem to affect the font family of the back button.

**Comment by pie6k** [comment]
Is it resolved?
