### ISSUE TITLE
setOnNavigatorEvent callback not fired when switching tabs

### ISSUE THREAD

**Issue by jneuendorf** [wix/react-native-navigation#3599]
### Issue Description

I have originally posted [my question](https://stackoverflow.com/q/51225730/6928824) on stackoverflow but had no success so far. Thus I want to try to get some more help here or some people to read my question on stackoverflow.

Basically I want to `popToTRoot` when the user switches tabs but it doesn't work:

```javascript
class NavScreen extends React.PureComponent {
    constructor(props) {
        super(props)
        this.props.navigator.setOnNavigatorEvent(this.toRootOnTabSelect.bind(this))
    }

    toRootOnTabSelect(event) {
        const {id} = event
        if (["bottomTabSelected", "bottomTabReselected"].includes(id)) {
            this.props.navigator.popToRoot({
                animated: true,
                animationType: "fade",
            })
        }
    }

    render() {
        return <Text>Whatever...</Text>
    }
}
```

### Steps to Reproduce / _Code Snippets_ / Screenshots

For more details see [my stackoverflow post](https://stackoverflow.com/q/51225730/6928824).

---
### Environment
* React Native Navigation version: 1.1.474
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator (iPhone 6), iOS 11.4, Debug

**Comment by nacidai** [comment]
This is due to the same root cause as #3443.  The fix would be in RCCViewController (rootView is not public) and RCCTabControllers:

+(void)sendTabEvent:(NSString *)event controller:(UIViewController*)viewController body:(NSDictionary*)body{
  UIView *theView = viewController.view;
  if ([viewController isKindOfClass:[RCCViewController class]]){
    RCCViewController *rccvc = (RCCViewController *)viewController;
    if (rccvc.rootView != nil) {
      theView = rccvc.rootView;
    }
  }
  
  if ([theView isKindOfClass:[RCTRootView class]]){
    RCTRootView *rootView = (RCTRootView *)theView;
    
    if (rootView.appProperties && rootView.appProperties[@"navigatorEventID"]) {
      NSString *navigatorID = rootView.appProperties[@"navigatorID"];
      NSString *screenInstanceID = rootView.appProperties[@"screenInstanceID"];
      
      
      NSMutableDictionary *screenDict = [NSMutableDictionary dictionaryWithDictionary:@
                                         {
                                           @"id": event,
                                           @"navigatorID": navigatorID,
                                           @"screenInstanceID": screenInstanceID
                                         }];
      
      
      if (body) {
        [screenDict addEntriesFromDictionary:body];
      }
      
      [[[RCCManager sharedInstance] getBridge].eventDispatcher sendAppEventWithName:rootView.appProperties[@"navigatorEventID"] body:screenDict];
    }
  }

**Comment by jneuendorf** [comment]
@nacidai Thanks for your reply. Unfortunately, I am very unfamiliar with native App coding (i.e. objective-C/swift).

So could you please clarify exactly what change has to be done in which file?

- I am guessing the `sendTabEvent` method has to be added to `Libraries/ReactNativeNavigation.xcodeproj/RCCTabBarController .m` but I'm not really sure...
- What exactly has to be done to fix `rootView is not public`?

**Update**

I just saw there is a [PR]() that has already been merged. What version includes this fix?

**Comment by davidliu** [comment]
@jneuendorf that PR doesn't address this one. It's a separate but closely related.

**Comment by davidliu** [comment]
I've filed a PR #3808 based on @nacidai's proposal.

It exposes a public readonly property for rootView on RCCViewController to deal with the issue of it being internal.
