### ISSUE TITLE
ios splash screen..

### ISSUE THREAD

**Issue by gilra2000** [wix/react-native-navigation#36]
How to apply splash screen?

**Comment by artald** [comment]
@gilra2000 what kind of splash screen are you talking about?

Currently we support showing the launch image as a splash until the first root controller is set. This happens automatically if you have either a Default image, a xcassets launch image or a launch storyboard screen.

**Comment by musicode** [comment]
@artald Do you means put a default.png under the project root directory?

**Comment by artald** [comment]
@musicode yes, the method of using a default.png is supported.

Currently you can use either:

1. default.png
2. launch xib (defined in info.plist using `UILaunchStoryboardName`).
3. xcassets LaunchImage

Personally I prefer the xcassets option.

Also note that currently storyboard files are not supported as splash.

**Comment by musicode** [comment]
@artald @guyca  

Do you have a plan to write a image pinch and drag effect for ios and android by native code?

I think the feature is very common, but I can't find a good library in github.

**Comment by artald** [comment]
@musicode 

That's a nice idea, thanks! 

Unfortunately, we don't have plans for creating such components for the time being. We usually work on new components when we need them in our own projects and there's not enough time and resources to handle new stuff otherwise..

**Comment by grundmanise** [comment]
@artald Hey, I've made [a little tutorial](https://gist.github.com/grundmanise/a712b6c57472d0f70af1d766ba0201f2) on how to setup launch images when using RNN. Maybe you can add a link to it somewhere in the readme to share with others?

**Comment by artald** [comment]
@grundmanise thanks!

A new documentation page is now in the works. We can add it there when it's up.
cc: @guyca

**Comment by chuyik** [comment]
@grundmanise Dude you rocks!

**Comment by kamwysoc** [comment]
@grundmanise your answer fix the problem, thanks!
