### ISSUE TITLE
Is there a way to add badge in navigator icon for android?

### ISSUE THREAD

**Issue by junedomingo** [wix/react-native-navigation#360]
Something like this
![screen shot 2016-10-06 at 11 09 23 am](https://cloud.githubusercontent.com/assets/5106887/19139241/6cba15c2-8bb5-11e6-88aa-73527ff89eb2.png)

**Comment by guyca** [comment]
Not at the moment.
cc @DanielZlotin

**Comment by JuneDomingo** [comment]
Hopefully you can implement it soon. This is one big thing that is missing I think.

**Comment by agumack** [comment]
+ 1

**Comment by agumack** [comment]
@JuneDomingo you can use navBarHidden: true
and css it on view : )
