### ISSUE TITLE
[V2] merge options should not wait for animations to end

### ISSUE THREAD

**Issue by Niryo** [wix/react-native-navigation#3603]
### Issue Description
When pushing a screen and setting the topBar title dynamically, it takes a noticeable time until the topBar title is being set. If "push screen" animation is being disabled, the title is being set immediately. 
I think we should consider not waiting for animations to end when merging navigation options.

### Environment
IOS

**Comment by mths0x5f** [comment]
iOS or Android? hahaha

merging by the options property or the mergeOptions method? I have a similar "issue" on Android which I workarround calling mergeOptions inside componentDidMount

**Comment by yogevbd** [comment]
Reproducing in v1 as well.. It is not possible to manipulate topBar during transition, you must provide all the options before the transition starting.
