### ISSUE TITLE
[V2] White Image Flicker

### ISSUE THREAD

**Issue by TylerNRobertson** [wix/react-native-navigation#3609]
### Issue Description

When changing screens background Images flicker white for a second and then render properly. This is on both debug and Release builds. (Seems to only happen sometimes but its still in issue)

### Steps to Reproduce / Code Snippets / Screenshots

- Create an ImageBackground with the react native API.
- Navigate between the screen with an image and back and you will see the flicker.

![buggiph](https://user-images.githubusercontent.com/23481122/43080523-44d8f3ec-8e66-11e8-9956-6949e85098d0.gif)

---
### Environment
* React Native Navigation version: 2.0.2415
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): IOS (Haven't tried on android)
* Device info (Simulator/Device? OS version? Debug/Release?): All of the above

**Comment by kriptonhaz** [comment]
got the same problem but only facing on the android, the ios is smooth like what I want

**Comment by SudoPlz** [comment]
We face the same issue, but we're not using an `ImageBackground` anywhere, so that may be unrelated.

**Comment by sharifMedici** [comment]
Did anyone get solution for it,. i am getting same flash in ios after pop screen vertifically

**Comment by TylerNRobertson** [comment]
Closing issue due to being inactive and unused. Also references an out of date version of this library.
