### ISSUE TITLE
Customize TabBar border top

### ISSUE THREAD

**Issue by hiradarshadi** [wix/react-native-navigation#3617]
I haven't found any option for customizing tabbar top border (color).

<img width="444" alt="screen shot 2018-07-24 at 9 42 48 pm" src="https://user-images.githubusercontent.com/29271309/43154802-df3fcc56-8f8a-11e8-906c-ee8000da1526.png">

I want to change that black color (#000) to something a bit lighter (like #b4b4b4)
But there is no option for that.

---
### Environment
* React Native Navigation version: 1.1.477
* React Native version: 0.51.0
* Platform(s): Both

**Comment by hiradarshadi** [comment]
Suppose I'm going to make it red, green, etc.

**Comment by bzaman** [comment]
bottomTabs: { hideShadow: true,  backgroundColor: '#F5F6F7', } This will works I hope
