### ISSUE TITLE
[V2] options.animation.showModal not working

### ISSUE THREAD

**Issue by alexichristakis** [wix/react-native-navigation#3618]
### Issue Description
When I show a modal without any animation enabled the opening transition persists. The dismiss modal animation is properly disabled.

Here's my function:
```
Navigation.showModal({
    component: {
      name: componentName,
      passProps: props,
      options: {
        modalPresentationStyle: "overCurrentContext",
        animations: {
          showModal: {
            enable: false
          },
          dismissModal: {
            enable: false
          }
        },
      }
    }
  });
```
I've isolated the breaking RNN version to be 2.0.2401. My function works in versions up to 2.0.2401 but nothing after.
---
### Environment
* React Native Navigation version: ^2.0.2401
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device Debug/Release

**Comment by phuongwd** [comment]
@alexichristakis #3523

**Comment by flikQ** [comment]
This still seems to be broken on iOS.

**Comment by rendomnet** [comment]
still broken

**Comment by phuongwd** [comment]
@rendomnet 

did you try ?
```
Navigation.dismissAllModals({
  animations: {
    dismissModal: {
      enable: false
    }
  }
});
```
 https://github.com/wix/react-native-navigation/issues/3523#issuecomment-420909791

**Comment by rendomnet** [comment]
@phuongwd The correct method is 
**enabled: false NOT enable: false!!!!!**
with this it is working
