### ISSUE TITLE
example animations are super slow by default

### ISSUE THREAD

**Issue by tzookb** [wix/react-native-navigation#363]
### Issue Description

I just implemented the example on my app, and the animations are super super slow,
I tried to find a config for animations speed but found nothing.

Is there something I'm missing?

here is a video that shows the animations speed

https://www.youtube.com/watch?v=O8gtqeSresw

### Steps to Reproduce / Code Snippets / Screenshots

Just took the code in the example.

---
### Environment
* React Native Navigation version: ^2.0.0-experimental.127
* React Native version: 0.31.0
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): ios simulator

**Comment by edvinasbartkus** [comment]
I thin, it's nothing to do with React Native nor RNNavigation. 
I think you have enabled Slow Animations in your emulator: Debug > Slow Animations.
Or Cmd + T.

**Comment by tzookb** [comment]
damn... I'm shaming myself from github :/

thanks @edvinasbartkus

**Comment by smooJitter** [comment]
@tzookb, don't feel bad.  I've been combing code all morning trying to figure this one out. smh
