### ISSUE TITLE
[V2] 'passProps' to 'sideMenu'

### ISSUE THREAD

**Issue by doublex** [wix/react-native-navigation#3635]
Passing props to 'sideMenu' during open-drawer does not honor 'passProps', e.g.:

````
Navigation.mergeOptions( componentId, {
  sideMenu: {
    left: {
      visible: true,
      component: {
        name: 'SideMenu',
        passProps: {
          name: value,
        }
      }
    }
  }
});
````

---

* React Native Navigation version: 2.0.2428
* React Native version: 0.56.0
* Platform: both
* Device info: Simulator

**Comment by angelos3lex** [comment]
Is there any way to pass props from another component into sideMenu component?

**Comment by spikeisryu** [comment]
Same request. I need a way to pass props to sideMenu component.
There are multi tabs and when the side menu is shown, I want to pass the component ID of the tab screen, so that I can tell which tab screen called the side menu.

Or is there a way to figure out the current selected tab's componentId from SideMenu?

**Comment by reganperkins** [comment]
also in need of this

**Comment by doublex** [comment]
@guyca
Are there any plans to dynamically pass props to the sideMenu?

**Comment by doublex** [comment]
Should be possible to pass props

**Comment by MEsteves22** [comment]
I'm having the same problem.  I need to pass props to my side menu component in order to know the componentId of the tab screen that is opened. When I try to access my props I always get "undefinied"...

**Comment by MNAcaisoft** [comment]
Any ideas how to pass props to side menu?

**Comment by doublex** [comment]
still relevant

**Comment by React-Vishnu** [comment]
Same need. how do we pass props to sideMenu component.

**Comment by doublex** [comment]
still useful

**Comment by akupczak** [comment]
So from what I see there is still no possibility to pass Prop by merging. I need it in the sideMenu in order to decide what item should be disabled. The only way I would fix it right now is by storing center componentID inside of redux store and pulling it in the side menu, and I really don't want to do that. 
How did you handle this?

**Comment by EskelCz** [comment]
@guyca this is still needed and the stale bot is not helping one bit :(

**Comment by hossamnasser938** [comment]
Still a relevant issue

**Comment by GrinchakAndrew** [comment]
you can easily pass props to `sideMenu` like so: 

```continueBtnOnPress={() => {
                  RouterManager.mergeOptions('BottomTabsId', {
                    sideMenu: {
                      right: {
                        enabled: true,
                        visible: true,
                        component: {
                          name: 'redirectFromSideMenu',
                          passProps: {
                            redirectFromSideMenu: componentId,
                            redirectToScreen: screenNames.BROADBAND_COMPLETE,
                          },
                        },
                      },
                    },
                  });
                }}```

then, providing you have got ` this.navigator.events().registerCommandListener(async (name, params)`
listener to the merger options event in navigation, you have to listen to the mergeOptions event 
```name === 'mergeOptions'```
and go to the navigation state : ```this.navigator.store.propsById```, where you will be able to get the passed property and the `componentId`, the most coveted piece of data in my case, as I wanted to redirect user to another screen programmatically from the sideMenu. That's it. No redux needed.

**Comment by varunarora1687** [comment]
I used this library to overcome the limitations of sidemenu
http://www.lib4dev.in/info/lukebrandonfarrell/react-native-navigation-drawer-extension/171316468

**Comment by doublex** [comment]
@GrinchakAndrew 
After `registerCommandListener()`, how did you pass the props to the SideMenu?
