### ISSUE TITLE
[V2] Overlay displaying over SafariView

### ISSUE THREAD

**Issue by phuongwd** [wix/react-native-navigation#3636]
### Issue Description

The overlay display overlap on SafariView and does not display website content.
I using the [Safari View Controller](https://github.com/naoufal/react-native-safari-view#install) "react-native-safari-view": "^2.1.0".

### Steps to Reproduce / Code Snippets / Screenshots
`
SafariView.default.show({
 url: 'https://wix.github.io/react-native-navigation/#/'
});
`

Case 1:  work well 👍 
- Start app
- Welcome screen
- Push options screen
- Show SafariView

Case 2:
- Start app
- Welcome screen
- Push options screen
- Show touch through overlay
- Show SafariView

**Actually**: 
- show white screen
- overlay display overlap on SafariView
<img src="https://user-images.githubusercontent.com/2460806/43301227-0928c806-918e-11e8-96bc-ae3657721cd9.png" width="320">

**Expect**: 
- show content
- overlay hidden

Please see video:
[![RNN V2 - Overlay issues](http://img.youtube.com/vi/nS6afrlKziA/0.jpg)](https://www.youtube.com/watch?v=nS6afrlKziA "RNN V2 - Overlay issues")

---
### Environment
* React Native Navigation version: the latest code from git 
 "temp fix for ios unit tests" commit: ac86b499ad888487c54497d7aa4ad5d4743bf3d7 [ac86b499]
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator - iPhone X 11.3 - Debug

---
### The issues refer:
- https://github.com/wix/react-native-navigation/issues/3097#issuecomment-383837765 Overlay displaying over modal (Closed)
- https://github.com/wix/react-native-navigation/issues/3614 Overlay is showing above system dialogs like alerts (Closed https://github.com/wix/react-native-navigation/commit/89cf84f1ab62e64785213552b10eb7a4811c6680)

**Comment by birkir** [comment]
You won't be able to do this, because that SafariView is completely isolated from RNN. You could, however, create your own custom view controller with SafariView and maybe display modal on top of it using the RNN showModal api.

```objc
// AppDelegate.m
[ReactNativeNavigation registerExternalComponent:@"RNNSafariViewController" callback:^UIViewController *(NSDictionary *props, RCTBridge *bridge) {
  return [[RNNSafariViewController alloc] initWithProps:props];
}];

// RNNSafariViewController.m
#import "RNNSafariViewController.h"

@import SafariServices;

@implementation RNNSafariViewController {
  NSURL* _url;
  boolean* _readerMode;
}

- (instancetype)initWithProps:(NSDictionary *)props {
  self = [super init];
  _url = [[NSURL alloc] initWithString:props[@"url"]];
  _readerMode = [props[@"readerMode"] boolValue];
  return self;
}

- (void)viewDidAppear:(BOOL)animated {
  [super viewDidAppear:animated];
  SFSafariViewController *safariViewController = [[SFSafariViewController alloc] initWithURL:_url entersReaderIfAvailable:_readerMode];
  safariViewController.delegate = self;
  [self presentViewController:safariViewController animated:animated completion:nil];
}

@end

// RNNSafariViewController.h
#import <UIKit/UIKit.h>

@interface RNNSafariViewController : UIViewController<SFSafariViewControllerDelegate>

- (instancetype)initWithProps:(NSDictionary*)props;

@end
```

**Comment by phuongwd** [comment]
@birkir thank you
