### ISSUE TITLE
[v2] custom top bar background does not fill entire height on iPhone X

### ISSUE THREAD

**Issue by erickreutz** [wix/react-native-navigation#3646]
![image](https://user-images.githubusercontent.com/59875/43361981-0d765778-9294-11e8-9a98-4848fa83926f.png)

### Steps to reproduce: 

Run playground on iPhone X simulator

---
### Environment
* React Native Navigation version: wix/navigation@master
* React Native version: wix/navigation@master
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X

**Comment by thame** [comment]
Add `drawBehind: true`

**Comment by erickreutz** [comment]
Won’t that just draw the screen view underneath the top bar?

**Comment by chrise86** [comment]
Also facing this issue. Adding `drawBehind: true` does not solve the problem. Neither the background component nor the actual screen component is visible under the top most part of the topbar. It's like there is a white object on top of everything else.

**Comment by Dalamar** [comment]
Also facing this issue.
Neither drawBehind: true, nor <SafeAreaView> within wrapper helps.

**Comment by Dalamar** [comment]
` translucent: true,`  solved this issue for me:

```
Navigation.setDefaultOptions({
      statusBar: {
        visible: true,
        style: 'light',
        hideWithTopBar: false,
      },
      layout: {
        backgroundColor: '#f2a99a',
        orientation: ['portrait'],
      },
      topBar: {
        visible: true,
        translucent: true,
        background: {
          color: 'rgba(217, 73, 114, 0.5)',
          component: {
            name: 'TopBarBackground',
          },
        },
      },
...
})
```

![screen shot 2018-08-15 at 12 34 59](https://user-images.githubusercontent.com/321632/44142061-af920150-a087-11e8-82dc-04c6ffed2415.png)

**Comment by FRizzonelli** [comment]
This isn't fixed, and doesn't work on any device, the problem is also present with any iOS device.

`statusBar: {
                      hideWithTopBar: true,
                    }`

works perfectly if you have a background color, but doesn't work when you have a custom top bar c
