### ISSUE TITLE
[v2][Android] - unmaintained dependencies

### ISSUE THREAD

**Issue by mths0x5f** [wix/react-native-navigation#3659]
### Issue Description

https://github.com/wix/react-native-navigation/blob/7e24aafd67398b329c57aeaedda1c8213c6742c7/lib/android/app/build.gradle#L78-L80

I have saw that you forked ahbottomnavigation to tweak it a little and I hope eventually correct bugs. That's great because it seems that the [original library is unmaintained](https://github.com/aurelhubert/ahbottomnavigation). 

But what will be done in respect of Clans' FAB? The [library is explicitly discontinued](https://github.com/Clans/FloatingActionButton) (since 2 years!) and there's no support anymore, but the floating action buttons are one of the strongest UI patterns in Material Design. Perhaps you can fork it also?

**Comment by mths0x5f** [comment]
no one?

**Comment by ZeroCool00** [comment]
wix/react-native-navigation#3479
