### ISSUE TITLE
How to set Drawer width

### ISSUE THREAD

**Issue by makasimenator** [wix/react-native-navigation#366]
### How to set Drawer width

I want to set Drawer width and can't find how to do it. I found that it's possible in react-native-controllers library `drawerController.setStyle({  rightDrawerWidth: '70' })`.
### Environment
- React Native Navigation version: 2.0.0-experimental.127
- React Native version: 0.33.0
- Platform(s) (iOS, Android, or both?): ios
- Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by guyca** [comment]
hmm
on Android you can set the width of your drawer component in JSX, not too sure about iOS. @gran33 ?

Why would you want to change the side menu width? If I'm not mistaken it's supposed to be fixed width, At least on [Android](https://material.google.com/patterns/navigation-drawer.html#navigation-drawer-specs)

**Comment by makasimenator** [comment]
The drawer takes ~80% of width on iPhone 5 and ~30% on iPad air 2 now. It looks not fine... I can't style the menu for different resolutions(((

**Comment by guyca** [comment]
I see. How does it behave on Android?

**Comment by makasimenator** [comment]
I didn't build the app for Android yet...

**Comment by andybbtt11** [comment]
+1, my ux team has designed a full width drawer (not something i'd wanna do) but, I'm gonna have to support it sooner than later.

**Comment by raonicaselli** [comment]
I also want to know! In Android the width is the same for mobile and tablets. When I set the width inside the drawer component to let's say 320, the section where the user taps to close the drawer is not adjusted accordingly, so in tablets if I set the maxWidth to 320, the user can only close the drawer by tapping in the far right corner, as if the drawer was still with width 80%.

**Comment by glesage** [comment]
Any updates or estimates? I'd love to get an idea on when you guys plan on implementing this or if we can help

**Comment by guyca** [comment]
@glesage I played around with this on Android. Setting the screen width in RN works fine, but the drawer measurement is not correct and it blocks touch events in about 80% percent of the screen.
I'll do my best to try and prioritise this but because we don't use a drawer in our app, this will take some time.

**Comment by glesage** [comment]
Yea exactly, I believe the only issue is that the touch handling isn't shifted according the the drawer width...

Ok, yea I was surprised to find that you guys even had a drawer in the framework since it seems the wix app doesn't have it hehe

**Comment by guyca** [comment]
#544 fixes SideMenu measurement bug on Android. This leaves us with supporting full screen SideMenu on iOS, and supporting right SideMenu on Android.

**Comment by guyca** [comment]
full width drawer is also supported on Android @andybbtt11

**Comment by mrphu3074** [comment]
```jsx
  drawer: {
    left: {
      screen: 'App.Screen.SideMenu',
    },
    style: {
      leftDrawerWidth: 40,
    }
  }
```

It's works for me

**Comment by andybbtt11** [comment]
Just noticed this. Thank you guys! Works great.
