### ISSUE TITLE
PermissionsAndroid crashes if request permission when using react native navigation

### ISSUE THREAD

**Issue by halaharr** [wix/react-native-navigation#3660]
### Issue Description
I am trying to use PermissionsAndroid to grant or request permissions. The app crashes if you deny or grant permissions. It works fine of project where there is no react-native-navigation. 

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots
const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA);

[FILL THIS OUT - It will be extremely helpful]
I am not sure since Mainapplication.java is changed with react-native-navigation this causes a issue. Please let me know if there is a workaround.

---
### Environment
* React Native Navigation version: FILL THIS OUT
1.1.398
* React Native version: FILL THIS OUT
0.54.0
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
Android
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT
Samsung Galaxy S7 Edge

**Comment by kriptonhaz** [comment]
I'm facing this problem request for location access, is there anyway to solve this?
