### ISSUE TITLE
[V2] [iOS] Quick white screen (flash) after LaunchImage

### ISSUE THREAD

**Issue by Dexwell** [wix/react-native-navigation#3661]
### Issue Description

Between the LaunchImage and display of the first RNN screen, there is a small window where the screen is white. In Debug mode it takes longer; this is where you see the green "Downloading JavaScript bundle" bar up top. The statusbar also goes dark here even though I set it to light using `UIStatusBarStyle` in Info.plist.

Existing solutions exist that require editing `AppDelegate.m` code related to the `rootView`. However when using RNN this is impossible, since we have to replace everything with a custom bootstrap method:

```objc
[ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];
```

Is there any way you guys on the native side could make it so that the launch image and UIStatusBarStyle are not changed until the first RNN screen has loaded? This is some critical functionality impacting the UX of every app using RNN.

### Steps to Reproduce / Code Snippets / Screenshots

n/a

---
### Environment
* React Native Navigation version: 2.0.2435
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by tiempham** [comment]
I used 
`    
layout: {
      backgroundColor: 'transparent',
      orientation: ['portrait', 'landscape']
    }
` it's working.

**Comment by Dexwell** [comment]
@tiempham Not for me, which makes sense because the white screen means RN is loading the JavaScript. I think you misunderstand my issue.

@guyca @yogevbd Could you assign/look at this? We already have 4 +1s :)

**Comment by flosdor** [comment]
v1 also have a same issue :(

**Comment by danielgindi** [comment]
Happens to me too. While it is loading the JS/React - it shows a white screen.
If `react-native-navigation` would supply an intermediate splash screen that takes the Default image on iOS and then fades into the real screen when it's rendered - that will solve the issue.

**Comment by Dexwell** [comment]
Is this just not going to be looked at @yogevbd @guyca? Again, pretty big UX deal.

**Comment by Dexwell** [comment]
Those following this issue, perhaps duplicate this issue and refer it to get the devs' attention. I'd hate for this issue to block me from launching my app. @guyca @yogevbd

**Comment by rduhard** [comment]
The solution to this problem is to set the `loadingView` property of the `RCTRootView`. If you have a Launch image in your app, you'd want to pass in the launch screen view to be set as the `RCTRootView.loadingView` property so that RN will use that screen while it loads the JS. This removes the flash and looks like a seamless transition. The RNN library needs to support the ability to pass in a loadingView that can be set to the `RCTRootView.loadingView` when it's created and from there it is handled entirely by RN.

**Comment by Dexwell** [comment]
@rduhard So if I understand correctly this can't be solved until the RNN library adds support for a loadingView, correct?

**Comment by rduhard** [comment]
@Dexwell yes I believe so. We have a fork of V1 that we implemented this in currently but it would be ideal if they could add this necessary functionality into V2. They need to add a way for users of RNN to pass in a loadingView that would RNN would then subsequently set on the `RCTRootView.loadingView` property when it is created. In addition, they would need to set the frame of the loadingView to match that of the RCTRootView prior to setting it. This is how we implemented it in our fork.

**Comment by Dexwell** [comment]
It's pretty bizarre how the RNN devs seem unwilling to even acknowledge this issue. I'm afraid we'll have to hope someone experienced with native code comes in clutch and creates a PR that fixes this.

**Comment by LRNZ09** [comment]
If you don't use an image, you can try [this](https://github.com/wix/react-native-navigation/issues/358#issuecomment-415918650).

**Comment by VicFrolov** [comment]
+1

**Comment by nikolas7892** [comment]
+1

**Comment by ENT108** [comment]
+1

**Comment by VicFrolov** [comment]
Hopefully this issue gains some traction as the +1's are growing.

**Comment by ENT108** [comment]
I fixed it with react-native-splash-screen.

**Comment by Dexwell** [comment]
Acknowledged! Thanks devs 🙌🏼

**Comment by Dexwell** [comment]
Still relevant...

**Comment by Garmega** [comment]
+1. this issue is driving me insane

**Comment by evaldsurtans** [comment]
+1

**Comment by brianramirez** [comment]
+1 This is a large UX issue and should be implemented to RNN.

**Comment by henrikra** [comment]
Does anyone have some idea where the code is that needs to be changed? I can look into that because I am facing the same problem. I would just want to be shown to right direction :)

**Comment by danielgindi** [comment]
Okay so I've analyzed the problem and it's problematic specifically on iOS.
On Android, the `Activity` is controlled by the App, and it is only first displayed when RNN knows that it's ready.
On iOS the system shows the `UIWindow` immediately after the splash (and loading in App's delegate code). You can only delay this with synchronous code, but RN/RNN loading is asynchronous, and it must have the main thread free to prepare `UIKit` stuff, so we can't block it.

So I started to write a solution for this - which is basically a view controller that parses the app's plist and fetches the correct launch screen storyboard/xib/image.
After I'm almost done with that, I find out that there's a file named `RNNSplashImage.m` file in RNN's code, which does exactly that.

Now I'm investigating why the blanks still how if we have a splash screen automatically set up.

**Comment by danielgindi** [comment]
An update:
It does use the splash-mock, and shows it up nicely. In fact most of the (fraction of a) time that we see the splash - it's actually that `RNNSplashImage`.

BUT when the app calls `setRoot(...` it goes straight to `setRoot` in native code, which replaces the `UIWindow`'s root view controller with the new root view controller, immediately. It does not wait for its first render.
Now we just have to dive into RN's internals and find out how to get notified on first render.

If anyone has experience in that area I could use a hand there.

**Comment by danielgindi** [comment]
Solved it! Will create a PR and let you know. Let's just hope it gets merged.

**Comment by danielgindi** [comment]
In the meantime, you could point your npm at the branch, like this:
```
{
  "dependencies": {
    "react-native-navigation": "git+https://github.com/danielgindi/react-native-navigation.git#bugfix/ios_white_launch_screen"
  }
}
```

**Comment by Dexwell** [comment]
Thanks so much for working on this!

When I point my npm at your branch, my app launches with this error though:

> However, this package itself specifies a `main` module field that could not be resolved (`/Users/(...)/node_modules/react-native-navigation/lib/dist/index.js`. 
 
The dist folder doesn't exist?

**Comment by danielgindi** [comment]
Yes because there is a build stage before publishing to npm.
I point my npm now to the official 2.4.0, and modify the podspec to point to thr branch in a postinstall script.
The changes are only in the native code anyway.

**Comment by Dexwell** [comment]
@danielgindi Can you point me in the right direction as to how to set up the Podspec file?

**Comment by danielgindi** [comment]
Take the current Podspec, in the `git` url replace `”wix”` with `”danielgindi”`, and replace `tag = ...` with `branch = “bugfix/ios_white_launch_screen”`

**Comment by danielgindi** [comment]
In my project I have a `postinstall` script that is doing such modifications in the code/specs of several react packages. I think anyone with a project big enough ends up with such a mechanism, so this is just another “fix” you can do until it is merged.

**Comment by Dexwell** [comment]
That didn't work for me, but I ended up pulling in your code by setting up my Podfile like this

`pod 'ReactNativeNavigation', git: 'https://github.com/danielgindi/react-native-navigation.git', branch: 'bugfix/ios_white_launch_screen'`

The white flash persists because I setRoot after loading the initial root, looks like I have to change my approach there 😬

However, the status bar still looks buggy; it's light during launch, then changes to dark where the screen used to flash white, then becomes light again. Is it possible to update your PR so that it honors the chosen status bar style all the way through?

**Comment by danielgindi** [comment]
@Dexwell when compiling as an "adhoc" or "testflight" for the device - does the white screen still persist?
I'm asking because I allowed it in the code to immediately replace the root for subsequent `setRoot` calls - assuming that everything's loaded. It's possible that I'll have to enable the "delay until render" for those too - but in order to be sure I need to know if it happens in releases too, not in React debug mode.

As for the status bar - I think I'll have to update `RNNSplashImage` to fetch the initial status bar color from the app's plist and return that in the `ViewController`'s methods.
Again - not sure about this, as I don't know where the colors are taken from in your app.

Let's try to clarify it! The stages are:
1. Real launch image, loaded by iOS
2. Fake launch image screen, loaded by RNN
3. Still fake launch image screen, react is loading (In debug mode you see the green bar at the top)
4. Still fake launch image screen, react has attached its view into RNN's generated view controller (green bar may say 100%)
5. RNN receives a slot on RN's UI thread and attached the new root instead of `RNNSplashImage`.

Now can you say what the status bar's color is at each stage? And what the source of it is (to your best guess)?

**Comment by Dexwell** [comment]
@danielgindi Haven't set up TestFlight for it yet, but when launching on my device using the Release scheme it still flashes.

Let's see:

1. White. I have no Launch Screen File, so source is UIStatusBarStyleLightContent in Info.plist
2. Animates to black here I think. 
3. Green bar overlaps status bar, so hard to say. Best guess still black.
4. Same as 3?
5. White, source probably:
```js
static get options() {
    return {
      statusBar: {
        style: 'light'
      }
    };
  }
``` 

Re Android; it's an iOS only project for now.

**Comment by Dexwell** [comment]
@danielgindi Latest commits fixed all issues; looks so smooth now. You're a legend! 🙌🏼🎉

**Comment by danielgindi** [comment]
@Dexwell The only blocker now for merging it is the tests. The e2e tests are failing due to using a library called `detox` which is supposed to wait for react to be ready before it expects UI elements to be on the screen, but it resolves that before react actually performs the layout stage, and then the tests fail. 
We need someone who has experience with `detox` to fix the tests...

**Comment by danielgindi** [comment]
@guyca Unless you are going to wait for the layout cycle - it's not going to solve it. Because the current implementation of "wait for render" on iOS - means waiting for React's DidAppear notification, which happens when the React Native view was added to the parent view.
As the layout cycle is async and not happening immediately, you will still get a flicker for a fraction of a second.

I've debugged this a lot, and I don't really see a way around it.
I have an implementation that's ready and tested in both debug & dist environments. There's just some weird incompatibility with `detox.
It could be used together with @yogevbd's work, but it must be there in order to get rid of the white screen.

The e2e tests are currently passing 100% "on my machine" - but not on your CI machine. It's like it's ignoring the `waitFor` request.

תנו לזה קצת תשומת לב אה? שרפתי על זה כבר כמה שעות טובות.

**Comment by danielgindi** [comment]
@guyca The implementation you were referring to is both irrelevant, and Android only (while the current issue is with iOS. In Android it actually worked...)
How can we make this get more attention?

**Comment by guyca** [comment]
@danielgindi This issue has already been prioritised internally and work has already started on it - unfortunately something came up and @yogevbd had to context switch to other tasks. I'm sure he'll get to this by next week.
We also need this feature for the Wix app so you can be sure we'll get to this.

**Comment by danielgindi** [comment]
@guyca Great to hear that, thank you.
I thought about a way to resolve the testing issue, or more of a workaround.
Since `detox` does not know how to wait for real "ready" mode,
We can (and should, anyway) make the new waiting mechanism depend on `waitForRender` flag of `setRoot`. It's not implemented in iOS anyway.
And the current tests will stay as is - with `waitForRender` turned off.
A separate test for `waitForRender` on `setRoot` will have to be created, to make sure that the UI is not attached before being really ready - actually expecting the errors that come up now.

The only gap is implementing the `waitForRender` configuration on the iOS side, and toggling the waiting mechanism according to that.

**Comment by guyca** [comment]
We intent `waitForRender` to be opt-in - in this case why should there be issues with detox?

**Comment by danielgindi** [comment]
@guyca That's what I'm saying

**Comment by danielgindi** [comment]
Note that the branch is now rebased on 2.6.0, and that it is now an opt-in feature, by adding `waitForRender: true` in the options for you root component.

An example:
```js
Navigation.setRoot({
  root: { 
    stack: {
      children: [
        {
          component: {
            name: 'MyRootComponent'
            options:
              animations: {
                setRoot: {
                  waitForRender: true
                }
              }
            }
          }
        }
      ]
    }
  }
});
```

@Dexwell @LRNZ09 @henrikra

**Comment by danielgindi** [comment]
Okay so a lot of work was done on `master` branch already, and we have one leftover which is the bugs with the splash screen itself.
A PR is here: https://github.com/wix/react-native-navigation/pull/4698

You could do the same as before - work with the latest version and compile the iOS part from `danielgindi:bugfix/ios_splash_status_bar` branch.
```
pod 'ReactNativeNavigation', git: 'https://github.com/danielgindi/react-native-navigation.git', branch: 'bugfix/ios_splash_status_bar'
```

**Comment by guyca** [comment]
We'll merge #4698 today and publish a new version. Thanks for all the work you're doing @danielgindi, this feature is happening thanks to your efforts 🙇

**Comment by danielgindi** [comment]
@guyca I'm just grateful for the work you guys have done and for Wix open sourcing some of their projects. I believe in open source.

**Comment by danielgindi** [comment]
Now with 2.10.0 I think this issue can finally be closed! @Dexwell

**Comment by Dexwell** [comment]
@danielgindi Unfortunately, I don't think so 😓 I moved from your branch to the latest official release, and upon launch, the screen either still flashes white, or all components resize and bounce in as if a LayoutAnimation is happening. Quickly going back to your branch...

**Comment by guyca** [comment]
@Dexwell Have you setup `waitForRender` as shown in https://github.com/wix/react-native-navigation/issues/4369#issuecomment-461071990?

**Comment by Dexwell** [comment]
@guyca Yep.

**Comment by danielgindi** [comment]
For me it actually works on `master`.
Setting `waitForRender` on the root component.
Note that setting it in the defaults did not work for me, but on the actual `setRoot` call.

**Comment by Dexwell** [comment]
I set the `waitForRender` on both `setRoot` calls.

**Comment by danielgindi** [comment]
@Dexwell Is this in a release build or in debug?
Because there's one difference from my original implementation, which is on the bridge's "reload" event, we didn't try to attach a not-so-ready view controller, so the splash screen persisted until the bridge finished reloading.
In the new implementation, this does not happen - so bridge reloads cause a white screen, but in release builds there's no bridge reload event.

**Comment by danielgindi** [comment]
@Dexwell Basically the same configuration that worked with my branch should work on `master`, this is what works for me in release builds now.

**Comment by Dexwell** [comment]
@danielgindi Release, exact same code as with your branch triggers a flash/bounce.

**Comment by Dexwell** [comment]
Can you guys not reproduce the issue with LayoutAnimations?

**Comment by Dexwell** [comment]
I have another issue, which is `showModal` does nothing when called quickly in/after `componentDidMount` when using the `Release` scheme. Only works when calling `showModal` after 300 ms or so using `setTimeout` 😬 

Did some testing, and the issue is there in both @danielgindi's 2.4.0 branch and the official 2.10.0, using the `Release` scheme. Not an issue when using the `Debug` scheme. In the official 2.4.0 there's no issue using either scheme.

Hope this is an easy fix 'cause I want to launch soon 😄

**Comment by danielgindi** [comment]
@Dexwell Please try with `pod 'ReactNativeNavigation', git: 'https://github.com/danielgindi/react-native-navigation.git', branch: 'bugfix/ios_white_launch_screen_2'`, over 2.11.0.
It's a new branch I made, that takes the work that was already merge to `master`, and adds that old trick of waiting for first UI event to be considered as rendered.

I haven't even tried to compile it with React Native yet, so you may have to fix some syntax errors or 
something like that. But the good news is that if it works for you, it's a very small gap to be merged to `master`.


About the `showModal`, please look for any warnings from iOS in the console. Something about presenting a view when ready or similar.

**Comment by Dexwell** [comment]
@danielgindi Thanks for your effort. It didn't help. To be clear, I'm using this code, then in that Root component the same to set to another screen.

```js
Navigation.setRoot({
    root: {
      stack: {
        children: [
          {
            component: {
              name: 'cardbox.Root',
              options: {
                topBar: {
                  title: {
                    component: {
                      waitForRender: true
                    }
                  }
                },
                animations: {
                  setRoot: {
                    waitForRender: true
                  }
                }
              }
            }
          }
        ]
      }
    }
  });
```

Regarding showModal, I can't view console logs because it only happens in the Release scheme. Even then, how would I know when RNN is ready to show a modal? It worked in the old versions. Perhaps useful: in this latest branch I did see the modal for like a split-second and then the original component again. The modal seems to be opened, but hidden/overlapped/interrupted.

**Comment by danielgindi** [comment]
@guyca Is it possible that it's "done waiting" when another request comes in?
https://github.com/wix/react-native-navigation/blob/master/lib/ios/RNNCommandsHandler.m#L80

**Comment by danielgindi** [comment]
@Dexwell If my suspicions are correct, it might be showing the modal over the first view controller, and then removed when showing the second view controller.

I could try to write a fix that will take care of the synchronization for the first issue, which may also take care of the second one. But it's just a guess. I'll try to look at it later.

**Comment by guyca** [comment]
cc @yogevbd

**Comment by Dexwell** [comment]
Not to put you under any pressure @danielgindi 😄But do you have a rough idea of when you could take a look at this?

**Comment by danielgindi** [comment]
@Dexwell Sorry I got a lot of pressure in the last few days, I'll try to give it a go today

**Comment by Dexwell** [comment]
@danielgindi Take your time, I'm grateful for your help. Just seeing what the ETA is, otherwise I'll have to hack together a different solution to launch :)

**Comment by guyca** [comment]
@Dexwell If you could PR a screen to the playground app where this issue reproduces - we'll be able to take a look as well.

**Comment by danielgindi** [comment]
@Dexwell I looked at the code again, and didn't find a codepath where the situation I described could happen, unless React Native is doing something really bad under the hood.
I mean it looks like the DidAppear notification (added as a subview) is filtered out if it's for a different view.
There could still be a bug there.

Anyway, could you compile with the branch I mentioned and see that it actually compiles? Because I haven't tested it and it could just be failing.
Also it should be relatively easy to debug in Xcode connected to your device, you'll see the ReactNativeNavigation code under the Pods project. Look for `RNNReactView.m`, specifically the function `- (void)contentDidAppear:(NSNotification *)notification {`. That's what I modified in the branch for you, and you could also test on `master` and on my branch.

**Comment by Dexwell** [comment]
@danielgindi It did compile after I changed

```objc
if (![appearedView.appProperties[@"componentId"] isEqual:_self.appProperties[@"componentId"]])
```
to
```objc
if (![appearedView.appProperties[@"componentId"] isEqual:self.appProperties[@"componentId"]])
```
and that's what I tested it with.

**Comment by Dexwell** [comment]
@guyca I can't seem to reproduce the issue in a simple lightweight sample project 😬

**Comment by Dexwell** [comment]
I at least made a test case where the root component appears over the modal. Basically when calling `showModal` in `componentDidMount`: https://github.com/Dexwell/react-native-navigation/tree/rnn-modal-bug

The Xcode console does say:
>  Presenting view controllers on detached view controllers is discouraged <RNNRootViewController: 0x7fe24bd3a100>  

But it worked fine in 2.4.0. If we could just figure out what has changed from 2.4.0 to 2.10.0 that (only in `Release`!) makes the root component appear over the modal. 

If you uncomment the `setTimeOut` in `initial.js` it works fine, but I want as few of those in my code as possible. (Also it still animates in even though the animation options tell it not to?)

**Comment by Dexwell** [comment]
@guyca @danielgindi I'll be submitting my app for review in a matter of days. Did you manage to take a look at the example project? I'd prefer to not ship on 2.4.0 with a flash, but that's less bad than modals not opening 😰

**Comment by guyca** [comment]
Hey @Dexwell, we've been a bit busy last two weeks. If the issue reproduces in that library we'll look into it soon, Thursday or Sunday next week.

**Comment by danielgindi** [comment]
@Dexwell did not get a chance, but if you want I can re-push the branch that worked for you, if you tell me what was the latest version that worked for uou with my branch (2.4.0?)

**Comment by Dexwell** [comment]
Some hopefully helpful info to narrow down the issue. On the latest 2.13.1: 
- If I set `waitForRender: false` on the second `setRoot`, modals show correctly, but there is a flash (you can test this in my example project)
- If I change my app so that there is no second `setRoot`, there is no flash, but modals are hidden by the root

What exactly does `waitForRender: true` do? Am I supposed to only call it once?

@danielgindi Thank you, but no need. I believe your 2.4.0 also had the modal bug, and 2.13.1 works, albeit with a flash.

**Comment by Dexwell** [comment]
In some cases I still had modal issues on 2.13.1, so I reverted to 2.4.0 and am using https://github.com/crazycodeboy/react-native-splash-screen to fix the flash. Still hope we find the cause of these issues so I won't be stuck at 2.4.0.

**Comment by Dexwell** [comment]
Still not completely fixed, bot.

**Comment by acollazomayer** [comment]
> I fixed it with react-native-splash-screen.

How is your AppDelegate with react-native-splash-screen and react-native-navigation

**Comment by Dexwell** [comment]
@acollazomayer Call show after RNN code

```objc
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  #ifdef DEBUG
    NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  #else
    NSURL *jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
  #endif

  [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];
  
  [RNSplashScreen show];
  
  return YES;

}
```

**Comment by LRNZ09** [comment]
@danielgindi I have set `waitForRender: true` in default options and it does work, thanks!

**Comment by haideralishah** [comment]
Open The Script Build Phases in Xcode > Bundle React native Code and images 
see this export NODE_BINARY=/usr/local/bin/node     <--
../node_modules/react-native/scripts/react-native-xcode.sh
1) open your teminal type `which node` to get node version path 
2) replace `node` with your node version path
reference : https://stackoverflow.com/questions/48639491/app-ios-stuck-on-blank-white-screen-when-build-release-react-native

**Comment by Nargle30** [comment]
@haideralishah Hi! Do you know what to do if after running 'which node' I get only '/usr/local/bin/'?

**Comment by Nargle30** [comment]
I found! 
"npm config list" command gives the correct path

And it didn't solve the issue in my case :(

**Comment by Vivek-maven** [comment]
Change js loading screen color from AppDelegate.m file by modifying the below line rgb color
rootView.backgroundColor = [[UIColor alloc] initWithRed:0.0f green:0.0f blue:0.0f alpha:1];

**Comment by JimTeva** [comment]
For anyone still having this. The best thing to do right now is to add library react-native-splash-screen and only add this code in your first screen:
```
import SplashScreen from 'react-native-splash-screen';

...
componentDidMount() {
  ...
  SplashScreen.hide();
}
```
