### ISSUE TITLE
[v2][iOS] accessibilityLabel for TopBar Buttons

### ISSUE THREAD

**Issue by karlsander** [wix/react-native-navigation#3662]
### Issue Description

TopBar buttons should either have their `title` or `text` set as an [accessibilityLabel](https://developer.apple.com/documentation/objectivec/nsobject/1615181-accessibilitylabel) or provide an additional option for that label.

Sadly, I lack the Objective C skills to create the pull request myself. The button with icon is created [here](https://github.com/wix/react-native-navigation/blob/c0481040cb2fbfec0f1cde2205ea0787c5d3f27d/ios/RCCNavigationController.m#L423), I think another special case, like [the disabled one here](https://github.com/wix/react-native-navigation/blob/c0481040cb2fbfec0f1cde2205ea0787c5d3f27d/ios/RCCNavigationController.m#L449) would be the right place to set the [accessibilityLabel](https://developer.apple.com/documentation/objectivec/nsobject/1615181-accessibilitylabel) if either title, text or label is provided.

Improperly tabled buttons are probably the number 1 annoyance for VoiceOver users, so it would be great if RNN made it easy for developers to do right.

### Steps to Reproduce / Code Snippets / Screenshots

1. Create a TopBar button with a button that has an icon, e.g.

```javascript
Navigation.mergeOptions(this.props.componentId, {
  topBar: {
    rightButtons: [
      {
        title: "Einstellungen",
        icon: settingsIcon,
        id: "settings"
      }
    ]
  }
});
```

2. Install the application on a real device

3. Enable VoiceOver and navigate to the TopBar button.

4. "Button" and nothing else will be read out

---
### Environment
* React Native Navigation version: 2.0.2428
* React Native version: 0.56
* Platform(s): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6s, iOS 12, Release

**Comment by Ingibjorg** [comment]
@karlsander did you ever find a fix for this?

**Comment by ngvazquezbdsol** [comment]
@karlsander Hi, did you ever find a fix for this?

**Comment by karlsander** [comment]
No, my app is no longer using topbar buttons. Is this still a problem im the current version?

**Comment by gran33** [comment]
You can add `accessibilityLabel` to the top bar buttons.
