### ISSUE TITLE
[V2] FAB icon color

### ISSUE THREAD

**Issue by aarnoldaas** [wix/react-native-navigation#3664]
As in v1 we had possibility to change FAB icon color, we should have possibility to do it v2 too.

example: 
fab: {
  id: ID,
  icon: ICON,
  iconColor: 'red'
}

icon color should be red.

**Comment by guyca** [comment]
cc @ethanshar

**Comment by Pushplaybang** [comment]
should we not simply be using the `Navigator.showOverlay` for elements such as FAB buttons?
