### ISSUE TITLE
[V2] [AndroidOnly] Navigator.dismissModal closes multiple modals if Navigation.setRoot is called from modal

### ISSUE THREAD

**Issue by DVSoftware** [wix/react-native-navigation#3666]
### Issue Description

We have an app where we use Navigation.setRoot() from a modal screen, and later in the application we have an issue when we open multiple modals, and then need to close one by one, but on Navigation.dismissModal(), all modals are getting closed, leaving the application in the inconsistent state.

This issue only happens on Android

### Steps to Reproduce / Code Snippets / Screenshots

- Use Navigation.showModal() to display a modal
- Use Navigation.setRoot() from the modal
- Open a modal from the new root, and then open a modal from that modal
- Dismiss the last modal
- Both modals are dismissed.
---
### Environment
* React Native Navigation version: 2.0.2425
* React Native version: 0.55.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All devices and Emulator

**Comment by cdanielraducu** [comment]
any update to this issue?
