### ISSUE TITLE
[v2] How to add animation show overlay like showInAppNotification

### ISSUE THREAD

**Issue by herarya** [wix/react-native-navigation#3667]
### Issue Description

hi, i need show alert like showInAppNotification using overlay, how to custom animation

(https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

> Navigation.showOverlay({
      component: {
        name: 'navigation.playground.CustomDialog',
        options: {
          overlay: {
            interceptTouchOutside : false,
            animations: {
              y : {
                ...
              }
            },
          },
        }
      }

---
### Environment
* React Native Navigation version: `^2.0.2437`
* React Native version: `^0.55.3`
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): iphone x

**Comment by herarya** [comment]
[SOLVED], im using react-native-animatable 💃

**Comment by pribeh** [comment]
@herarya would you be able to share how you used animatable to establish the animation?

**Comment by gabrielamarques** [comment]
@pribeh I've managed to animate the entrance, by placing a <Animatable.View> outside the notification component. (It animates on mount)
The thing is, it doesn't animate the exit :/

**Comment by pribeh** [comment]
@gabrielamarques I just did the same. I'll see if I can get it to do it on exit.

**Comment by pribeh** [comment]
Anybody figure out how to set a timer to dismiss the overlay?

**Comment by herarya** [comment]
@pribeh sorry late replay, this my code
```javascript
state = {
    keyFrames : {
        from: { translateY: -100 },
        to: { translateY: 0 },
      }
 }

 componentDidMount(){
    setTimeout(()=>{
        this._dismiss()
      },2000)
 }
 _dismiss() {
    this.setState({
      keyFrames : {
        from: { translateY: 0 },
        to: { translateY: -100 },
      }
    });
    setTimeout(()=>{
        Navigation.dismissOverlay(this.props.componentId);
    },2000)
   
   
```

```javascript
<Animatable.View useNativeDriver duration={800}
        animation={this.state.keyFrames} 
        style={[styles.container,{backgroundColor:backgroundColor}]}>
            <View style={styles.content}>
            
            </View>
          </View>
</Animatable.View>
```

**Comment by pribeh** [comment]
@herarya that's exactly it – I just learnt how to use keyframes to do the same thing. I added a timer for the entire overlay as well. Make sure to clearTimeout if you do this as you will crash the app if a user dismisses the overlay before that particular timeout.

```
	state = {
		keyFrames : {
			from: { translateY: -100 },
			to: { translateY: 0 },
		}
	}

/* Dismisses overlay on press or whatever you want */
	dismissOverlay() {
		this.setState({
			keyFrames : {
			  from: { translateY: 0 },
			  to: { translateY: -100 },
			}
		});

		setTimeout(() => {
			Navigation.dismissOverlay(this.props.componentId);
		}, 1000);

/* Very important to set, otherwise this.timeout will try to run after dismissOverlay has run */
		if (this.timeout) {
			clearTimeout(this.timeout)
		}
	}

/* Dismisses overlay after 5 seconds */
	componentWillMount () {
		this.timeout = setTimeout(() => {
			this.setState({
				keyFrames : {
				  from: { translateY: 0 },
				  to: { translateY: -100 },
				}
			  });

			setTimeout(() => {
				Navigation.dismissOverlay(this.props.componentId);
			}, 1000);
		}, 5000);
	}

	render() {
		return (
			<Animatable.View
				duration={350}
				useNativeDriver={true}
				animation={this.state.keyFrames}
			>
					<TouchableOpacity
						style={styles.backButton}
						onPress={this.dismissOverlay}
					>
					</TouchableOpacity>
			</Animatable.View>
		);
	}
}
```
