### ISSUE TITLE
you should be able to check the stack

### ISSUE THREAD

**Issue by reganperkins** [wix/react-native-navigation#3669]
### Issue Description
There is currently no documented way to check what elements are in the stack or to check the stack length.

### Steps to Reproduce / Code Snippets / Screenshots
In the app I am creating there are multiple ways a user can navigate to different pages. The different ways a user might navigate to the page effects if I should use pop, pushTo or setStackRoot. For example lets say in the drawer I have a list of teams and workspaces, when changing to a team or workspace from the drawer I would use setStackRoot to make sure all the previous stack is cleared. When going through the main page I would be using pushTo when entering a team and like wise pushTo when entering a workspace. However when using the main page navigation to move back from the workspace to the team I would use pop. 

The issue comes in when you mix using navigation from the drawer and the main page. In the case of having used the drawer to get to the workspace and then using the main page navigation to go back to the team, the team is not in the nav stack and pop workspace fails. being able to check that the component is in the stack or that the stack is of a certain length would really help. 

If there is a method I can use that I did not find please let me know

---
### Environment
* React Native Navigation version: Current
* React Native version: .56
* Platform(s) (iOS, Android, or both?): All
* Device info Any

**Comment by ItsNoHax** [comment]
Same goes for checking the current visibility of a drawer
