### ISSUE TITLE
Redux example folder returns 404

### ISSUE THREAD

**Issue by folivi** [wix/react-native-navigation#367]
Hi guys,

looks like the redux example no longer exists.

Any plans to bring it back?

**Comment by folivi** [comment]
my bad,
I just read you're no more maintaining the redux example.

**Comment by guyca** [comment]
Yes it's not maintained anymore, but it's stilll [up](https://github.com/wix/react-native-navigation/tree/master/old-example-redux)

**Comment by folivi** [comment]
hi,
So is it normal that it doesn't run at all?

**Comment by guyca** [comment]
It's not maintained, I assume it will work on an older version of navigation (instead of using `next` tag in package.json)
