### ISSUE TITLE
[V2] Creating a seamless lock screen

### ISSUE THREAD

**Issue by Seeker93** [wix/react-native-navigation#3670]
### Issue Description

Hi everyone

I have created a lock screen which requires a pin-code every time a user wants to enter the app. The problem is that currently, I am setting a new root after the pincode is entered, and this incurs a delay every time a user enters their code. 

I want it to be seamless, where the lock screen simply dismisses after the pin is entered, or at least have the appearance of just dismissing.

### Steps to Reproduce / Code Snippets / Screenshots
Currently I set the root with a method like this: 
```

function initializePinLock() {
    Navigation.setRoot({
      root: {
        component: {
          name: 'Screen.PinScreen',
        },
      },
    })
  } 
}
```

And when the user enters their pin, from the pin screen I call a second function that sets another root ie:

```
function startApp() {
    Navigation.setRoot({
      root: {
        component: {
          name: 'Screen.HomeScreen',
        },
      },
    })
  } 
}
```

This approach works fine, but as I said, it incurs a noticeable delay, and I was wondering if there is an official way of handling this situation, or if anybody has a better solution.

---
### Environment
* React Native Navigation version: 2.0.2432
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 5 emulator, Iphone 8, targeting Android 5 and above.

**Comment by DVSoftware** [comment]
Perhaps use the overlay?

**Comment by DVSoftware** [comment]
We use overlay for the exact same purpose without issues

**Comment by ItsNoHax** [comment]
@DVSoftware Do you call the overlay at the same time you call Root?
