### ISSUE TITLE
[V2] Feature request: Style modal as alert

### ISSUE THREAD

**Issue by doublex** [wix/react-native-navigation#3676]
Add a 'modal'-option to style the modal like this:

![modal](https://user-images.githubusercontent.com/274624/43581694-2765f674-965a-11e8-957a-be17d1c3f877.gif)

**Comment by guyca** [comment]
This can be achieved by showing a modal or an overlay, I think we should try and keep the API simple and not add functionality which tailored to such specific use cases. 👍

**Comment by joecaraccio** [comment]
@guyca  I can't find in the documentation.. how did you style the background color of the modal?

**Comment by doublex** [comment]
@joecaraccio 
I agree. Styling the background-color of the modal would help a lot.

**Comment by joecaraccio** [comment]
@doublex think you can style it, I'm jus tnot sure how to pass in the argument.
I bet @guyca knows, since he says you can right above lol
