### ISSUE TITLE
Add this sample app to v2 docs

### ISSUE THREAD

**Issue by birkir** [wix/react-native-navigation#3677]
I don't know if this is something you'd like to include in the readme but I built this app with v2 with many features it has over v1 like SplitView etc.

https://github.com/birkir/hekla

**Comment by guyca** [comment]
Hey @birkir, Would love to showcase the app in the documentation! Would you like to add a Showcase page to the documentation which we could link to from the README?

**Comment by birkir** [comment]
Will do, thanks Guy.
