### ISSUE TITLE
How to implement drawer Navigation in android

### ISSUE THREAD

**Issue by chaitanya0bhagvan** [wix/react-native-navigation#368]
### Issue Description

I have an app that has a SideMenu with a list of 8 screen to navigate to. I start this screen using           `Navigation.startTabBasedApp` and I handle navigation using `this.props.navigator.handleDeepLink` in the SideMenu screen and handle the `onNavigatorEvent` in each of the the screens. This works fine on IOS but on android I am only able to navigate to the first 5 screens. This is because of the limit put in `createBottomTabsScreenLayout(AppCompatActivity activity, ActivityParams params)`.

So my question is how do I handle drawer navigation in android that has more than 5 screens. 

### Environment
* React Native Navigation version: 2.0.0-experimental.127
* React Native version: 0.31
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/6.0.1/Debug

**Comment by guyca** [comment]
Hey @chaitanya0bhagvan 
The limitation on the number of BottomTabs is defined in [Android's design guidelines](https://material.google.com/components/bottom-navigation.html#bottom-navigation-usage), We simply try to follow it as close as possible.
Read under the _"When to use"_ section: "Three to five top-level destinations of similar importance". I doubt your app has 8 major top level destinations.

What might work for you is using the drawer with `startSingleScreenApp` as described [here](https://material.google.com/patterns/navigation-drawer.html#).
When the user clicks on a button in the drawer, simply push a screen to the stack and close the drawer.

**Comment by chaitanya0bhagvan** [comment]
Thank you @guyca . I am using drawer navigation but starting the screen as a tab based screen and hiding the tabbar. Your suggestion of using a single screen app and pushing other screens makes sense.
