### ISSUE TITLE
[V2] Large title in modal doesn't show until scroll

### ISSUE THREAD

**Issue by jarrx** [wix/react-native-navigation#3680]
### Issue Description

Large title in modal doesn't show until scroll.

### Steps to Reproduce / Code Snippets / Screenshots

```
  static get options() {
    return {
      topBar: {
        title: { text: 'More' },
        largeTitle: { visible: true },
        rightButtons: [
          {
            title: 'Done',
            id: 'done'
          }
        ]
      }
    };
  }
````

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31743687/43635660-0724b54c-9710-11e8-8504-a1d703afc0d4.gif)

---
### Environment
* React Native Navigation version: ^2.0.2394
* React Native version: ^0.55.4
* Platform(s) (iOS, Android, or both?): iOS 
* Device info (Simulator/Device? OS version? Debug/Release?): simulator/device debug

**Comment by jarrx** [comment]
Also strange animation when you go back from a screen without large title to a screen with large title.
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/31743687/43649829-8048cfc0-973e-11e8-80da-0fa3185edc5c.gif)

**Comment by nicolaslopezj** [comment]
Related https://github.com/wix/react-native-navigation/pull/3610

**Comment by srogers202** [comment]
I've tested the change in #3610, but I don't think it resolves this issue. 

Any ideas on why the large title is not showing initially? I've been working on a solution, but I haven't found the root cause.

**Comment by zcmgyu** [comment]
Same issue.

**Comment by ericlewis** [comment]
Also having this issue, will try to investigate. Seems related to scrollViews

**Comment by mikeletscher** [comment]
I am currently experiencing this issue as well. Will see if I can figure out a short term solution.

**Comment by chrise86** [comment]
I'm still having this issue on single component screens, not even inside modals.

**Comment by kheraprabhat** [comment]
For me, #3610 worked.

**Comment by chrise86** [comment]
Doesn’t do anything for me

**Comment by matpaul** [comment]
Found fix,  

1) drawBehind should be true,

2) in screen 
```tsx
const {height} = Dimensions.get('window')
...
render() {
  return (<View style={{height}}><ScrollView>....</ScrollView></View>);
}
```

**Comment by chrise86** [comment]
@matpaul that also doesn't work for me. It resolves the scrolling up issue, however when the view loads the topBar is extra large and pops back up (to small) when the `FlatList` content loads (from a network request).
