### ISSUE TITLE
Android Navigator button title is always capital.

### ISSUE THREAD

**Issue by bhatti-waqas** [wix/react-native-navigation#3683]
### Issue Description

I am using navigatorButtons but for android the title is always capital. 
How can I make it in proper case. 
Here is the code given for navigatiorButtons

`static navigatorButtons = {
        leftButtons: [{
            icon: images.close,
            buttonColor: '#333333',
            disableIconTint: true,
            id: 'back'
        }],
        rightButtons: [{
            title: 'Sign out',
            buttonColor: '#F47F28',
            //disableIconTint: true,
            id: 'signout'
        }]
    }`

Please see screenshot.

![screen shot 2018-08-03 at 4 41 01 pm](https://user-images.githubusercontent.com/9653275/43641165-0c12f8c6-973c-11e8-8cb1-3091f9812963.png)

Any help would be much appreciated thanks.

**Comment by makirby** [comment]
I use a workaround in the app theme config for doing this.
In `styles.xml`:

```
<style name="MenuItemTextAppearance" parent="@style/TextAppearance.AppCompat.Widget.ActionBar.Menu">
        <item name="textAllCaps">false</item>
    </style>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="actionMenuTextAppearance">@style/MenuItemTextAppearance</item>
    </style>
```

Bear in mind this will force no caps on all activities. Which was the desired effect for me.
