### ISSUE TITLE
[V2] [Android] Back button does not work as expected on screen with side menus

### ISSUE THREAD

**Issue by sJJdGG** [wix/react-native-navigation#3689]
### Back button does not work as expected on screen with side menus

if a screen gets pushed in an app with side menu, pressing back button does not pop the last screen from stack. It exits from the app completely. Does not depend on how many screens are pushed.
### Steps to Reproduce / Code Snippets / Screenshots
Run the playground app.
press "SWITCH TO APP WITH SIDE MENUS".
Press "Push".
Press back button.
It exits the app.

![the screen cap](https://media.giphy.com/media/vMaXHLJ5uy884TdDMh/giphy.gif)

---
### Environment
* React Native Navigation version: 2.0.2453
* React Native version: 0.51.x
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Google Pixel 1/ 8.1 / Debug

**Comment by hadimostafapour** [comment]
@guyca @yogevbd Does any WIP on this?
RNN Version: 2.0.2478

**Comment by makirby** [comment]
You could listen to navigation events on that screen for back button presses and call the pop method.

**Comment by guyca** [comment]
Resolved in 2.0.2553
Now hardware back button will close open side menus or let the center view handle the back press.

**Comment by caiolv** [comment]
> Resolved in 2.0.2553
> Now hardware back button will close open side menus or let the center view handle the back press.

I can't say thank you enough.
