### ISSUE TITLE
Focus TextInput on pop screen [QUESTION]

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#369]
How can I programmatically focus on a TextInput after popping a screen?
It seems that the autoFocus prop on the TextInput, is not working in that case.

**Comment by guyca** [comment]
Hey @perrosnk 
Until we implement Screen Lifecycle events (#120), you can implement a hacky temporary solution.

Android:
when pushing the screen you will be returning from, specify `overrideBackPress: true`
```js
navigator.push({
    screen: 'core.nextScreen',
    overrideBackPress: true,
    ...
});
```

In that screen, listen to the native back button press event:
```js
onNavigatorEvent(event) {
  if (event.id === 'backPress') {
    // Dispatch action here that will trigger focus on your TextInput
  }
}
```

on iOS
set a custom back button and do the same logic.

Unless this is urgent for production, I suggest you wait for lifecycle events to be implemented.

**Comment by perrosnk** [comment]
Ok great! Thanks!
