### ISSUE TITLE
[V2] Add support for navigate back event

### ISSUE THREAD

**Issue by noamco** [wix/react-native-navigation#3691]
### Issue Description

Add support for navigate back event triggered by user pressing the back/up button, physical back button or swiping left.

**Comment by wbercx** [comment]
+1. Would be great to be able to intercept back button presses in v2, for showing confirmation modals etc. This is the only loss in functionality I've run into so far when moving from v1 to v2.

**Comment by angelos3lex** [comment]
Is this planned to be implemented sometime?

**Comment by jarrx** [comment]
Would really need this funktion as well.
