### ISSUE TITLE
[V2] push new screen crash the app on android

### ISSUE THREAD

**Issue by billel-boudchicha** [wix/react-native-navigation#3692]
### Issue Description

this morning after updating to RNN to 2.0.2454 and 2.0.2456 can't push new screen 
Navigation.push crash the app , but showModal works fine
the app close maybe crashs in android only ,iOS works fine

### Steps to Reproduce / Code Snippets / Screenshots

A simple `react-native init newProject` with RNN `v2.0.2456` as dependency 

index.js
````
import { AppRegistry } from "react-native";
import App from "./App";
import Test from "./Test";
import { name as appName } from "./app.json";
import { Navigation } from "react-native-navigation";

Navigation.registerComponent(`navigation.AppScreen`, () => App);
Navigation.registerComponent(`navigation.TestScreen`, () => Test);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      stack: {
        id: "appStack",
        options: {
          // topBar: {
          //   visible: false
          // }
        },
        children: [
          {
            component: {
              id: "App",
              name: "navigation.AppScreen",
              passProps: {
                text: "This is Test"
              }
            }
          }
        ]
      }
    }
  });
});

````

App.js
````
...
import { Navigation } from "react-native-navigation";

export default class App extends Component {
  onPressLearnMore = async () => {
    await Navigation.push("appStack", {
      component: {
        name: "navigation.TestScreen",
        passProps: {
          text: "Pushed screen"
        },
        options: {
          topBar: {
            title: {
              text: "Pushed screen title"
            }
          }
        }
      }
    });
  };
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Button
          onPress={this.onPressLearnMore}
          title="Learn More"
          color="#841584"
          accessibilityLabel="Learn more about this purple button"
        />
      </View>
    );
  }
}

````
Test.js
```
export default class Test extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Page 2</Text>
      </View>
    );
  }
}
```
---
### Environment
* React Native Navigation version: 2.0.2456
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device / 6.0 / Debug

**Comment by billel-boudchicha** [comment]
Testing on v`2.0.2452`  works fine on android
Doesn't work starting from 53 ==> 56

**Comment by birkir** [comment]
Rated to SharedElement transition maybe, @guyca ?

**Comment by Lokendra-rawat** [comment]
yup its working on v `2.0.2459` thanks

**Comment by billel-boudchicha** [comment]
Still not working on v `2.0.2460`. Navigation.push crashing the app

**Comment by haggholm** [comment]
The only recent change that seems relevant is (as @birkir presumably alluded to) https://github.com/wix/react-native-navigation/commit/bd4e42fadd4faa9829cacb7eae4b18861af7c2ad from @guyca

**Comment by billel-boudchicha** [comment]
Yes I can confirm that the Problem is with android 6.0

**Comment by manattersa** [comment]
Hi, same problem with Android Emulator API 19 (4.4).
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-navigation": "^2.0.2459",
Trace:
java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet
        at android.animation.AnimatorSet.sortNodes(AnimatorSet.java:881)
        at android.animation.AnimatorSet.start(AnimatorSet.java:517)
        at com.reactnativenavigation.anim.NavigationAnimator.push(NavigationAnimator.java:51)
        at com.reactnativenavigation.anim.NavigationAnimator.push(NavigationAnimator.java:33)
        at com.reactnativenavigation.viewcontrollers.stack.StackController.push(StackController.java:144)
...
