### ISSUE TITLE
[V2] [iOS] Peek and Pop on iOS using Navigation.TouchablePreview crashes the app

### ISSUE THREAD

**Issue by yuannypants** [wix/react-native-navigation#3693]
### Issue Description

Implementing the recently refactored peek and pop function for iOS (#3620) crashes the app.

### Steps to Reproduce / Code Snippets / Screenshots

To reproduce the crash, you can implement either the demo from #3620 or the example from https://wix.github.io/react-native-navigation/v2/#/docs/animations.

![img_6b88919734e4-1](https://user-images.githubusercontent.com/8996417/43691444-47ab67dc-994f-11e8-988b-ef3ba6115b11.jpeg)

You may refer to the error message/callstack below. I don't know how to format the error message properly but I do hope it helps!

Exception '-[__NSDictionaryM floatValue]: unrecognized selector sent to instance 0x1c0032060' was thrown while invoking push on target RNNBridgeModule with params (
    push12,
    Component8,
        {
        children =         (
        );
        data =         {
            name = "flicc.ActivityScreen";
            options =             {
                preview =                 {
                    reactTag =                     {
                        reactTag = 1409;
                    };
                };
            };
        };
        id = Component11;
        type = Component;
    },
    2396,
    2397
)
callstack: (
 0   CoreFoundation                      0x000000018519ada4 <redacted> + 252
 1   libobjc.A.dylib                     0x00000001843545ec objc_exception_throw + 56
 2   CoreFoundation                      0x00000001851a8098 <redacted> + 0
 3   CoreFoundation                      0x00000001851a05c8 <redacted> + 1380
 4   CoreFoundation                      0x000000018508641c _CF_forwarding_prep_0 + 92
 5   Flicc                               0x00000001014ea97c -[RNNCommandsHandler push:layout:completion:rejection:] + 420
 6   Flicc                               0x00000001014bbe54 -[RNNBridgeModule push:componentId:layout:resolver:rejecter:] + 360
 7   CoreFoundation                      0x00000001851a2580 <redacted> + 144
 8   CoreFoundation                      0x0000000185081748 <redacted> + 284
 9   CoreFoundation                      0x000000018508656c <redacted> + 60
 10  Flicc                               0x0000000100eb3200 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2064
 11  Flicc                               0x0000000100f5de58 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 664
 12  Flicc                               0x0000000100f5d9e8 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 132
 13  Flicc                               0x0000000100f5d958 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
 14  libdispatch.dylib                   0x0000000184a8caa0 <redacted> + 24
 15  libdispatch.dylib                   0x0000000184a8ca60 <redacted> + 16
 16  libdispatch.dylib                   0x0000000184acdd80 <redacted> + 964
 17  CoreFoundation                      0x0000000185143070 <redacted> + 12
 18  CoreFoundation                      0x0000000185140bc8 <redacted> + 2272
 19  CoreFoundation                      0x0000000185060da8 CFRunLoopRunSpecific + 552
 20  GraphicsServices                    0x0000000187046020 GSEventRunModal + 100
 21  UIKit                               0x000000018f080758 UIApplicationMain + 236
 22  Flicc                               0x0000000100dc4a44 main + 124
 23  libdyld.dylib                       0x0000000184af1fc0 <redacted> + 4
)

RCTFatal
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
<redacted>
<redacted>
<redacted>
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
<redacted>

---
### Environment
* React Native Navigation version: 2.0.2454
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 8+ / iOS 11.4.1 / Debug

**Comment by TheEhsanSarshar** [comment]
This issue still exists
