### ISSUE TITLE
[Help] Find a solution build for multiple application

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#370]
### Issue Description

Hey all,

This is not a issue react-native-navigation. 
Currently, i am develop for a lot of customer and all application same source code (only different by appId). I am finding a solution for:
- build application auto 
- update version for all apps 

Can anyone suggest? Currently i am build, update,...for each app so take a lot of time :(

Thank so much much much!!!

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by DanielZlotin** [comment]
Maybe create some scripts? some suggestions: shell, js, gradle (groovy), make. Also checkout https://fastlane.tools/
