### ISSUE TITLE
[V1] App resumes to the foreground after back button pressed but works fine when home button is pressed, how can I emulate the home button functionality

### ISSUE THREAD

**Issue by Alanz2223** [wix/react-native-navigation#3700]
### Issue Description

I am having issues with my app returning to the foreground every time the user presses the back button. I believe this may be because there is a conflict between this navigation module and a sound playing module (react-native-track-player) that restarts the activity although this is just my hypothesis. However whenever I press the home (middle) button the app is sent to the background and everything works accordingly. I would like to emulate this functionality by capturing the back press event and handle it in a similar manner to the home button. I've read through issue #3471  While navigating the source, i've found the following handler in

android/reactnativenavigation/layouts/SingleScreenLayout.java

    @Override
    public boolean onBackPressed() {
        if (handleBackInJs()) {
            return true;
        }

    if (stack.canPop()) {
        stack.pop(true, System.currentTimeMillis());
        EventBus.instance.post(new ScreenChangedEvent(stack.peek().getScreenParams()));
        return true;
    } else {
        return false;
    }
    }

I can understand at a glance what is being done however I am not very familiar with Java and don't want to introduce any bugs involving the native side of the app, could anyone kindly point out what I would need to modify?

### Steps to Reproduce / Code Snippets / Screenshots

I have not been able to track which module is making my app resume to the foreground, whether its react-native-navigation or react-native-track-player but I strongly suspect there may be a conflict, so reproducing the issue would be laborious. 

---
### Environment
* React Native Navigation version: ^1.1.334
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All , 6.0.1, Both

**Comment by BenBach** [comment]
@Alanz2223 Hi did you find a solution? I have the same problem. Appreciate your help. Thank you

**Comment by Alanz2223** [comment]
@BenBach 
https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java#L207

I changed that line to `this.moveTaskToBack(true);`
