### ISSUE TITLE
[V1] How to call onNewIntent in MainApplication

### ISSUE THREAD

**Issue by prabakarviji** [wix/react-native-navigation#3702]
I'm trying to override newIntent in MainApplication.java. But it is not calling
`@Override
  public void onCreate() {
    super.onCreate();
    setActivityCallbacks(new ActivityCallbacks() {
      @Override
      public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        this.setIntent(intent);
      }
    });
    SoLoader.init(this, /* native exopackage */ false);
  }`

**Comment by hackrx** [comment]
hey @prabakarviji  did you found the solution to override onNewIntent(), actually, I want to receive a new image path when shared from gallery to rn app (app was in the background then it comes in the foreground but it is receiving the same prop).
https://stackoverflow.com/questions/62661326/how-to-return-a-new-bundle-in-react-native-when-app-resumes
Here is the question which I have asked
