### ISSUE TITLE
[V2] [iOS] RNN.componentDidAppear is not a supported event type for RNNEventEmitter

### ISSUE THREAD

**Issue by jsmankoo** [wix/react-native-navigation#3703]
### Issue Description

App fails to start.
<img width="335" alt="screen shot 2018-08-06 at 4 23 20 pm" src="https://user-images.githubusercontent.com/6406020/43739155-0ed2ab96-9995-11e8-9a76-74de51ac9b35.png">

`RNN.componentDidAppear` is not a supported event type for RNNEventEmitter.
Supported events are: `RNN.AppLaunched`, `RNN.CommandCompleted`, `RNN.BottomTabSelected`, `RNN.ComponentDidAppear`, `RNN.ComponentDidDisappear`, `RNN.NavigationButtonPressed`, `RNN.SearchBarUpdated`, `RNN.SearchBarCancelPressed`, `RNN.PreviewCompleted`.

### Steps to Reproduce / Code Snippets / Screenshots
1. install v2.0.2459 (current latest)
2. link libraries
3. run app

currently I'm only able to use version v2.0.2404

---
### Environment
* React Native Navigation version: 2.0.2459
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhoneX iOS 11.4 Debug

**Comment by zeucxb** [comment]
Same

**Comment by jsmankoo** [comment]
Can we get an update on this?

**Comment by WeiLiangTan** [comment]
Try [this solution](https://github.com/wix/react-native-navigation/issues/3608#issuecomment-407496435)

**Comment by ue** [comment]
Did you use `yarn` @jsmankoo

**Comment by jsmankoo** [comment]
yes @ue , we use yarn.

**Comment by ue** [comment]
@jsmankoo Can you try `npm install` instead of `yarn`. I hope it will fix it.

**Comment by jsmankoo** [comment]
@ue I can confirm that removing `node_modules` and re-installing via `npm install` does fixes this. However I'm not sure whether that constitutes as the issue be "fixed".
