### ISSUE TITLE
topBar in the root layout doesn't appear

### ISSUE THREAD

**Issue by KhaledSayed** [wix/react-native-navigation#3707]
### Issue Description

topBar in the root layout doesn't appear 

### Steps to Reproduce / Code Snippets / Screenshots

in index.js 
```js
Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setRoot({
      root: {
        stack: {
          children: [
            {
              component: {
                name: 'App'
              }
            }
          ],
          options: {
            topBar: {
              title: {
                text: 'Title asdadasdas asdasdasdas',
                fontSize: 14,
                color: 'red',
                fontFamily: 'Helvetica',
          
              }
            }
          }
        }
      }
    });
  });

```    

[Screenshot](https://i.imgur.com/GuSCLTP.png
)---
### Environment
* React Native Navigation version: 2.0.2459
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Android 
* Device info (Simulator/Device? OS version? Debug/Release?): Android Api27

**Comment by yuannypants** [comment]
if I'm not wrong, you can't simply append your topBar as an option to a stack.. try appending it to the component itself instead?

**Comment by Luisvl13** [comment]
In your component add:

```
class Screen1 extends Component {
    static get options () {
        return {topBar: {title: {text: 'Screen1'}}};
    }
...
}
```

**Comment by guyca** [comment]
@Luisvl13 Is correct. Currently container options are applied on parent container, On Android at least, we need to consolidate the behaviour between the two platforms asap.

The reason for this, is that layouts can be nested. If the user has a stack within a stack, the inner stack's options are applied to the outer stack.
This isn't intuitive enough (at all?), We should apply the options in such cases on the stack, and perhaps add ability to apply options on all applicable layout nodes when calling mergeOptions.

**Comment by ecomaven** [comment]
Battled with this issue for a couple of days until I just stumbled upon this now. Thanks for the clarification, would be nice to have it somewhere in the "Getting Started" part of the documentation

**Comment by spiraltrip** [comment]
Yes, this would be a good **NOTE** to put in the Docs - Layout Section. I spent so much time figuring why the default approach didn't work according to the docs.
