### ISSUE TITLE
[V2][iOS] Merge options not working correctly

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#3720]
### Issue Description

Trying to close a sidemenu or change bottom tab with MergeOptions is not working on iOS at all.
Works perfectly on Android.

### Steps to Reproduce / Code Snippets / Screenshots

Easiest way to reproduce is create a layout with sidemenu, add a button to close the sideMenu using MergeOptions and it will not work. For example if you add the button to the sidemenu component itself so that it uses it's own componentId.

```
    Navigation.mergeOptions(this.props.componentId, {
      sideMenu: {
        left: {
          visible: false,
        },
      },
    });
```

---
### Environment
* React Native Navigation version: 2.0.2461
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator + Device / iOS 11.4.1 / Debug (Haven't tested Release)

**Comment by kasperkronborg** [comment]
Too add to this case, I'm experiencing a similar issue (only on iOS), when I follow the example given in the documentation here: https://wix.github.io/react-native-navigation/v2/#/docs/layout-types?id=bottomtabs.

I provide my bottomTabs with an id, like this:

```js
Navigation.setRoot({
  root: {
    bottomTabs: {
      id: 'BottomTabsId',
      children,
      options: {
        bottomTabs: {
          visible: false,
        },
      },
    },
  },
})
```

Then when I want to `mergeOptions` on it, it doesn't work.

```js
Navigation.mergeOptions('BottomTabsId', {
  bottomTabs: {
    visible: true,
    animate: true,
  }
})
```

But as the documentation also states, we can use one of the child component ids and when doing that, everything works. I just wished the other method would work, since it makes for a more clear code to read and helps create a better understanding of what's going on.

**Comment by guyca** [comment]
Hey @ItsNoHax, Could you please PR a failing detox test?
We have two related e2e tests that pass
https://github.com/wix/react-native-navigation/blob/v2/e2e/ScreenStyle.test.js#L75
https://github.com/wix/react-native-navigation/blob/v2/e2e/ScreenStyle.test.js#L83

@kasperkronborg We're aware of this issue. Hoping to address it by the end of the month (I'm currently on vacation)

**Comment by kasperkronborg** [comment]
Sounds awesome @guyca. Let me know if there is anything else you need regarding the issue I posted.

**Comment by ItsNoHax** [comment]
@guyca Okay, so I was looking into those two tests.

First thing I noticed is that the test is broken, the CENTERED_TEXT_HEADER is always visible. So I sent a PR to fix it: https://github.com/wix/react-native-navigation/pull/3779

And it turns out my problem is not merge options but that a sidemenu layout INSIDE a bottom tab layout doesn't work. (which is a huge problem for us because we want to support different sidemenus per bottom tab) Related issue: https://github.com/wix/react-native-navigation/issues/3697

**Comment by EskelCz** [comment]
In my case opening works only after app reload
