### ISSUE TITLE
[V2][Android] ComponentDidAppear/ComponentDidDisappear callbacks are never triggered whenever drawer has just been opened or closed

### ISSUE THREAD

**Issue by mica16** [wix/react-native-navigation#3724]
### Issue Description

As the [documentation](https://wix.github.io/react-native-navigation/v2/#/docs/events?id=componentdidappear) explains, a corresponding callback is supposed to be triggered as soon as an appearance/disappearance event is spawn.
They aren't triggered with an Android device (emulator and real device). 

### Step to reproduce

So I configured a basic drawer like this:  

```
Navigation.setRoot({
        root: {
            sideMenu: {
                left: {
                    component: {
                        id: 'drawer',
                        name: 'Drawer'
                    },
                },
                //.............
``` 

```
export class Drawer extends PureComponent {
   
     constructor(props) {
        super(props);
        Navigation.events().bindComponent(this);
    }

     componentDidAppear() {
        alert("triggered");
     }

     componentDidDisappear() {
        alert("triggered");
     }

}
```

Try opening or closing the drawer, and you will notice that callbacks are not triggered.  

Tried also with the global listening: 

```
Navigation.events().registerComponentDidAppearListener(({ componentId, componentName }) => {
  // never triggered
});
```

On the other hand, note that **they are on an iOS device (Iphone X) with the EXACT same code**.

May you check whether those callbacks are supported in the targeted-Android code part? 

### Context

* React Native Navigation version: 2.0.2461
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): Android only
* Device info (Simulator/Device? OS version? Debug/Release?): Debug And Release are impacted

**Comment by angelos3lex** [comment]
I also confirm that on Android 6.0.0 sideMenu registered component's componentDidAppear() is fired only when someone navigates through sidebar to another view, and not when it is opened/appeared on screen. In fact componentDidAppear() is called after componentDidAppear() of the selected navigated View.

**Comment by mica16** [comment]
any news about this bug ?

**Comment by rgoldiez** [comment]
@guyca - This is still an issue on Android.  The RNN V2 lifecycle methods (DidAppear / DidDisappear) do not get fired on a sideMenu showing or hiding.  Works great on iOS.

**Comment by cesarm16** [comment]
any update?

**Comment by soutot** [comment]
This worked for me
```
componentDidMount() {
  Navigation.events().registerComponentDidAppearListener(({ componentId, componentName }) => {
     console.log('is visible') 
  });

  Navigation.events().registerComponentDidDisappearListener(({ componentId, componentName }) => {
     console.log('is hidden')
  });
 }
```

I'm using RNN 2.0.2585

**Comment by ssshen** [comment]
this issue is still exist in 0.56.0 version

**Comment by aderaaij** [comment]
Is this something that will be worked on? I was just breaking my head about why these methods didn't fire on Android but I guess it's a common problem. In the meanwhile, are there any other ways to get a reliable sidebar toggle on Android?

**Comment by kiroukou** [comment]
Anyone was able to help on this one?

How did you guys manage to handle these cases ?

**Comment by lefoy** [comment]
I'm still having this issue on iOS
