### ISSUE TITLE
Third party (FBSDK) loading

### ISSUE THREAD

**Issue by heysailor** [wix/react-native-navigation#373]
When using the third party [FBSDK](https://github.com/facebook/react-native-fbsdk), the android build does not load the FBSDK correctly. **Is this because of the modified sequence required by [RNN](https://github.com/wix/react-native-navigation)?**

I appreciate this is a third party issue, but the FBSDK is a common part of many apps. It would help many others if a way of getting it to work on Android with RNN could be nutted out.

As a test case, I've installed the [FBSDK as per its installation instructions](https://github.com/facebook/react-native-fbsdk)  **_- with modifications as below -_** into the [RNN bootstrap project](https://github.com/wix/react-native-navigation-bootstrap).

Linking appears to be successful:

    react_native_navigation_bootstrap@0.0.1 /Users/heysailor/dev/RNN-FBSDK
    └── react-native-fbsdk@0.3.0

    npm WARN react-redux@4.4.5 requires a peer of redux@^2.0.0 || ^3.0.0 but none was installed.
    rnpm-link info Linking react-native-fbsdk android dependency
    rnpm-link info Android module react-native-fbsdk has been successfully linked
    rnpm-link info Linking react-native-fbsdk ios dependency
    rnpm-link info iOS module react-native-fbsdk has been successfully linked
    rnpm-install info Module react-native-fbsdk has been successfully installed & linked```

As RNN modifies the MainActivity.java and MainApplication.java files with SplashActivity and navigationApplication, I've put the FBSDK code snippets into them.

ie., instead placing the FBSDK code for MainApplication.java into 

`public class MainApplication extends Application implements ReactApplication { }` 

I've put it into 

`public class MainApplication extends NavigationApplication { }`

And for MainActivity.java, instead of in 

`public class MainActivity extends ReactActivity { }`

I've put it into 

`public class MainActivity extends SplashActivity { }`

_Gists:_ 
[MainApplication.java](https://gist.github.com/heysailor/a6fedcc5b6bf133670ba6aa63b8ba64c)
[MainActivity.java](https://gist.github.com/heysailor/1fed39782f312d1723b66742b8bddef6)

The other FBSDK installation steps are straightforward. The app builds correctly on iOS and Android. The following code is used to call the FB login flow: 

    import FBSDK from 'react-native-fbsdk';
    const {LoginManager, AccessToken} = FBSDK;
    LoginManager.logInWithReadPermissions(['public_profile', 'email']);

This triggers the FB login flow fine on iOS, but causes an error on Android:

`TypeError: undefined is not an object (evaluating 'LoginManager.logInWithReadPermissions')`

Console logging LoginManager reveals it has this function as a property.

Environment:

react": "15.2.1",
react-native": "0.31.0",
react-native-fbsdk": "^0.3.0",
react-native-navigation": "2.0.0-experimental.116"

Emulating on Nexus 5 API 24 with Android 7.0 via Android Studio.

**Comment by beast** [comment]
Your mainapplicaiton.java. I think it should be:

  public List<ReactPackage> createAdditionalReactPackages() {

    // Add the packages you require here.
    return Arrays.<ReactPackage>asList(
         new FBSDKPackage(mCallbackManager)
    );
  }

You are returning null in your code. Whenever you see undefine is not an object error in React Native, usually means your javascript code is unable to call native code because of linking or package issues.

**Comment by guyca** [comment]
Nice catch @beast
The `onActivityResult` mechanism is also tricky since the Activity that's actually running is `NavigationActivity`. #182 will resolve that

**Comment by heysailor** [comment]
Cheers! That did the trick...such a simple error :P

For anyone else having problems, my working [MainApplication.java is here.](https://gist.github.com/heysailor/87f51798a50852eb9fccaf91a1055a5c)

**Comment by divyekhanna** [comment]
@heysailor Is it working for you on Android? For me, the callback is never fired. I'm guessing that the app transits from SplashActivity to NavigationActivity upon app launch whereas the callback is defined in SplashActivity (MainActivity).

Any thoughts or suggestions?

Thanks

**Comment by heysailor** [comment]
Are you working off a fresh test install? It worked fine on android for me.






On Fri, Oct 28, 2016 at 6:30 PM +1100, "Divye" <notifications@github.com> wrote:












@heysailor Is it working for you on Android? For me, the callback is never fired. I'm guessing that the app transits from SplashActivity to NavigationActivity upon app launch whereas the callback is defined in SplashActivity (MainActivity).



Any thoughts or suggestions?



Thanks

**Comment by divyekhanna** [comment]
@heysailor I have the exact same setup as you with same library versions as well as MainActivity.java and MainApplication.java files. I wonder why it does not work for me. Notably, I receive this in logcat running on emulator at the time when callback is supposed to happen:

`cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 4765`

**Comment by divyekhanna** [comment]
@heysailor So I tried working off a fresh install with exact same `MainActivity.java` and `MainApplication.java` as you, but it is still not working for me on Android! (Pulling my hair now)

More info:
```
react": "15.2.1",
react-native": "0.31.0",
react-native-fbsdk": "^0.3.0",
react-native-navigation": "2.0.0-experimental.134"

Emulating on API 24.
```

Is there anything else I need to change in my project? (Apart from setting App ID in resources and Android Manifest?)

Thanks again!

**Comment by perrosnk** [comment]
can anybody help me with this? #520

**Comment by arshavinho** [comment]
@divyekhanna Did you find a fix ? for me the callback is never fired also

**Comment by geordasche** [comment]
@arshavinho 
Setting the onActivityResult listener might help as described here: 

https://github.com/wix/react-native-navigation/issues/410#issuecomment-258109114

**Comment by anhtuank7c** [comment]
@geordasche You saved my day. Thank you!

**Comment by xe4me** [comment]
In my case, after adding the `onActivityResult` like above , it still didn't work, did some debugging and turned out that the SDK was trhowing.

I removed  bellow like of code from my `React` code

`LoginManager.setLoginBehavior('native');`
