### ISSUE TITLE
[V2] App stucks when pushing to the stack some ID twice

### ISSUE THREAD

**Issue by trofima** [wix/react-native-navigation#3732]
### Issue Description

When pushing a screen to the stack with the same ID for the second time, the app stucks and than crashes without throwing any error to the debugger or ui.

### Steps to Reproduce / Code Snippets / Screenshots

Push a screen to the same stack with the same ID twice
---
### Environment
* React Native Navigation version: 2
* React Native version: 
* Platform(s) (iOS, Android, or both?): checked on IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by dozoisch** [comment]
I doubt this is stale!

**Comment by dozoisch** [comment]
this is not stale! and shouldn't be closed

**Comment by dozoisch** [comment]
@guyca I'm not sure if stale-bot can reopen issues, so pinging you here given it's an accepted bug

**Comment by stokesbga** [comment]
Can reproduce. mergeOptions does nothing

**Comment by stokesbga** [comment]
@guyca this is a big issue, needs to be reopened
