### ISSUE TITLE
[V2] dismissModal doesn't await

### ISSUE THREAD

**Issue by trofima** [wix/react-native-navigation#3733]
### Issue Description

It seems that `await dismissModal(componentId)` doesn't work. The modal should be shown right after dismissing is also getting closed.
 
### Steps to Reproduce / Code Snippets / Screenshots

```
await Navigation.dismissModal('one');
Navigation.showModal('two');
```
Expected modal 'one' to be dismissed and the 'two' to be shown.
Actually the 'two' doesn't show.

---
### Environment
* React Native Navigation version: 2
* React Native version: 
* Platform(s) (iOS, Android, or both?): checked on iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by jolic** [comment]
This is still a bug!

version: 2.18.5,
iOS,
Simulator & Device

**Comment by samiede** [comment]
Also not working in v3!
