### ISSUE TITLE
[V2][Android] Bottom tabs placehodler doesn't hide

### ISSUE THREAD

**Issue by trofima** [wix/react-native-navigation#3738]
### Issue Description

When hiding bottom tab bar, the space where it was leaves occupied by white space. Looks like the buttons are hidden but the bar itself - no.

### Steps to Reproduce / Code Snippets / Screenshots

Checked setting options statically to the screen

---
### Environment
* React Native Navigation version: 2
* React Native version: 
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by hrayrpapikyan** [comment]
use {drawBehind: true}

**Comment by trofima** [comment]
```
bottomTabs: {
    visible: false,
    drawBehind: true
  }
},```

This doesn't work on Android

**Comment by trofima** [comment]
Thanks @hrayrpapikyan 
So in conclusion on iOS it's enough setting bottom tabs `visible: false`, on Android you have to add `drawBehind: true` in order bottom tabs fully disappear.
```
bottomTabs: {
  visible: false,
  drawBehind: true,
}
```
