### ISSUE TITLE
[V2][Android] statusBar backgroundColor setDefaultOptions doesn't works

### ISSUE THREAD

**Issue by guillaumevincent** [wix/react-native-navigation#3739]
I configured the backgroundColor of the statusBar with `Navigation.setDefaultOptions`.
Before react native StatusBar is launched in `App.js`, the statusBar is black.

index.js

```javascript
import { Navigation } from "react-native-navigation";
import App from "./src/App";


Navigation.registerComponent(`navigation.playground.WelcomeScreen`, () => App);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setDefaultOptions({
    statusBar: {
      backgroundColor: "#cc00cc",
      style: 'dark',
    }
  });

  Navigation.setRoot({
    root: {
      component: {
        name: "navigation.playground.WelcomeScreen"
      }
    }
  });
});

```

App.js

```javascript
import React, { Component } from "react";
import { Text, View, StatusBar } from "react-native";

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Welcome to LessPass!</Text>
      </View>
    );
  }
}
```
MainActivity.java

```java
package com.lesspass;

import android.os.Bundle;
import android.view.View;
import android.graphics.Color;
import android.support.annotation.Nullable;
import com.reactnativenavigation.NavigationActivity;

public class MainActivity extends NavigationActivity {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        View splash = new View(this);
        splash.setBackgroundColor(Color.parseColor("#474957"));
        setContentView(splash);
    }
}
```

### Steps to Reproduce / Code Snippets / Screenshots

![statusbar glitch](https://user-images.githubusercontent.com/943762/43968293-fc2a2c46-9cc6-11e8-8c72-04b7685628a4.gif)

is it related to RNN?
Do I forgot something?

reproductible repo: https://github.com/guillaumevincent/StatusBarBug

---
### Environment
* React Native Navigation version: 2.0.2461
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulated Nexus5X API26 x86_64

**Comment by tolu360** [comment]
You should call `Navigation.setDefaultOptions()` before `Navigation.setRoot()`.

**Comment by guillaumevincent** [comment]
No particular reason. Let me try your solution. Thanks
I will reopen the issue if it doesn't work

**Comment by guillaumevincent** [comment]
I update my first post, still not working
I created a repo with the bug
I will try on a real device to see if the flash on StatusBar is only on an emulated device

**Comment by guillaumevincent** [comment]
Close again,
bug only on my emulated device
Sorry for the flood

**Comment by zirtuedeveloper** [comment]
i face same bug on real device
