### ISSUE TITLE
[V2][Android] topBar title text is not displayed

### ISSUE THREAD

**Issue by hqdai** [wix/react-native-navigation#3740]
### Issue Description

topBar Text was displayed in version: 2.0.2452
But after going to version: 2.0.2466
Title of topbar is not displayed

### Steps to Reproduce / Code Snippets / Screenshots

I'm using 
`Navigaton.push(componentId, componentName, {
        passProps,
        options: {
          topBar: {
            title: {
              text: title
            },
            height: Metrics.navBarHeight
          }
        }
      });`

---
### Environment
* React Native Navigation version: 2.0.2466
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android 7 Emulator

**Comment by Luisvl13** [comment]
This can help you https://github.com/wix/react-native-navigation/issues/3707

**Comment by hqdai** [comment]
Thanks Luisvl13, I tried but it doesn't not success.
This is my detail situation.
I defined a root Tab with topBar options is as below
`root: {
      bottomTabs: {
        children: [
          {
            stack: {
              children: [
                {
                  component: {
                    name   : ContainerIdConstant.NAVIGATION_HOME,
                    options: {
                      topBar: {
                        visible   : false,
                        height    : 0,
                        drawBehind: true
.
.
.`

in this scene, I Push to a another scene 

`
Navigaton.push(componentId, componentName, { passProps, options: { topBar: { title: { text: title }, height: Metrics.navBarHeight } } });
` 
I tried to use mergeOptions to re-assign value in componentDidUpdate() function, I seems to be working but it takes some times, I look so bad.

Any suggestion for this case?

Thank you!
