### ISSUE TITLE
[v2][Android] mergeOptions backgroundColor not working

### ISSUE THREAD

**Issue by brandons** [wix/react-native-navigation#3741]
### Issue Description

Using `mergeOptions` to change the background color does not work on Android. 

```js
  Navigation.mergeOptions(this.props.componentId, {
      layout: {
        backgroundColor: 'blue'
      }
    });
```

The above code works fine on iOS, but does not have any effect on Android.

---
### Environment
* React Native Navigation version: 2.0.2466
* React Native version: 0.54.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel 2 API 27

**Comment by guyca** [comment]
Not able to reproduce, perhaps your root layout has `backgroundColor` defined in jsx?

**Comment by brandons** [comment]
@guyca No default backgroundColor on the root layout. It appears to be working fine on normal screens however is not working on screens presented as an overlay. 

```
    Navigation.showOverlay({
      component: {
        name: 'drawerComponent'
        }
      }
    });
```

```
class DrawerComponent extends React.Component<Props, State> {
  static get options() {
    return {
      layout: {
        backgroundColor: 'black',
      }
    };
  }

  componentDidMount() {
    Navigation.mergeOptions(this.props.componentId, {
      layout: {
        backgroundColor: 'blue'
      }
    });
  }
}
```
