### ISSUE TITLE
Unable to align lightbox content at the bottom of the screen instead of the middle

### ISSUE THREAD

**Issue by Alanz2223** [wix/react-native-navigation#3745]
### Issue Description
I've spent the past couple of hours trying to align the lightbox's content at the bottom of the screen while still maintaining a portion of the background without content so the use can click to dismiss. I've tried passing styling as an option to the

`
 navigation.showLightbox({

                style: {
                 backgroundBlur: "light", // 'dark' / 'light' / 'xlight' / 'none' - the type of blur on the background
              backgroundColor: "rgba(255,255,255,.4)",
              tapBackgroundToDismiss: true, // dismisses LightBox on background taps (optional)
              justifyContent : 'flex-end',
              position : 'relative'
              alignItems: 'flex-end',
              alignContent: 'flex-end',
              flexWrap: 'wrap',
              alignSelf : 'flex-end'
            }
})
`

and i've also tried various variations using flex box or absolute positioning on the container styling to get it to align at the bottom, but the lightbox always shows up that the center.

`  {
  position : 'absolute',
        bottom : 0,
        right : 0,
        left : 0,
   }`

`{
        alignItems: 'flex-end',
        alignContent: 'flex-end',
        alignSelf : 'flex-end'
}`

Is the alignment of the light boxe's content hard coded to be at the center? if so how may I achieve a similar effect?

###Steps to Reproduce / Code Snippets / Screenshots
Call Navigation.showLightBox()

###Environment
React Native Navigation version: ^1.1.334
React Native version: 0.51.0
Platform(s) (iOS, Android, or both?): Android
Device info (Simulator/Device? OS version? Debug/Release?): All , 6.0.1, Both

**Comment by ZloyRob** [comment]
any news?

**Comment by Alanz2223** [comment]
@ZloyRob Unfortunately, I was unable to resolve this cleanly. I went with the "hack" method and placed a transparent touchableview inside the container to force the view to align at the bottom. I capture the touch and dismiss the view explicitly.
