### ISSUE TITLE
[V2] Hide bottom tab bar when push to a new screen

### ISSUE THREAD

**Issue by webdevsyd** [wix/react-native-navigation#3749]
### Issue Description

I have TabBar base application, in one of my tab I need to push it to another screen but the tab bar should not display in the pushed screen. But the bottom bar is still existing in the pushed screen.
What I want to achieved is not totally hide the bottom tab bar but to put the pushed screen on top of the tab bar.

### Steps to Reproduce / Code Snippets / Screenshots

Here's my code to display the tab bar application:

```
bottomTabs: {
      id: 'BottomTabsId',
      children: [
        {
          stack: {
            children: [
              {
                component: {
                  name: 'Home',
                  options: {
                    topBar: {
                      backButton: {
                        title: 'Back',
                      },
                      title: {
                        text: 'Home'
                      }
                    },
                    bottomTab: {
                      fontSize: 12,
                      text: 'Home',
                      icon: require('./src/assets/home.png'),
                      selectedIcon: require('./src/assets/home_active.png')
                    },
                  },
                },
              }
            ]
          }
        },
        {
          stack: {
            children: [
              {
                component: {
                  name: 'Booking',
                  options: {
                    topBar: {
                      title: {
                        text: 'Booking'
                      }
                    },
                    bottomTab: {
                      text: 'Booking',
                      fontSize: 12,
                      icon: require('./src/assets/booking.png'),
                      selectedIcon: require('./src/assets/booking_active.png')
                    }
                  }
                },
              }
            ],
          },
        },
      ],
    },
```

<img width="337" alt="screen shot 2018-08-11 at 9 39 00 pm" src="https://user-images.githubusercontent.com/15810023/43992273-849f09dc-9daf-11e8-957b-ff495e925cfe.png">

**The Tab bar is still existing :(**
<img width="343" alt="screen shot 2018-08-11 at 9 43 31 pm" src="https://user-images.githubusercontent.com/15810023/43992279-9ceec144-9daf-11e8-9f2f-2973e29206a5.png">

**What I want to achieve is this**
![image from ios](https://user-images.githubusercontent.com/15810023/43998861-998364f0-9e32-11e8-971d-a33ccb515565.png)

---
### Environment
* React Native Navigation version: 2.0.2454
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator IOS 11

**Comment by herarya** [comment]
@webdevsyd try this 

` Navigation.push(this.props.componentId, {
      component: {
        name: 'NEXT_PAGE,
        options: {
          bottomTabs: {
            visible: false,
            drawBehind: true,
            animate: true
          }
        }
      },
    });`

**Comment by pakyo-pan** [comment]
`Navigation.mergeOptions(componentId, {
            bottomTabs: {visible: false, animate: false}
});`,  mergeOptions does not work too !

**Comment by webdevsyd** [comment]
@herarya YOUR SOLUTION IS FUCKING REALLY WORKS!. Thank you very much!

**Comment by VicFrolov** [comment]
While this works, the transitions aren't smooth, the tabBar disappears during the segue, and when you pop back, it re-appears over the container being hidden. This is a great temporary solution to have the app function though.

**Comment by benkraus** [comment]
UIKit supports `hidesBottomBarWhenPushed` on a `UIViewController`, at at first glance it appeared that this isn't supported yet. I agree that that would be a very useful thing to add and would resolve the quirky animations.

**Comment by mtzfactory** [comment]
Hi,

This code only works when you change the active tab and then you returns to the previous tab, at this time the bottom tab is not visible.

Any solution?

`Navigation.mergeOptions(componentId, { bottomTabs: {visible: false, animate: false} });`

**Comment by TienNguyenanh** [comment]
> @webdevsyd try this
> 
> ` Navigation.push(this.props.componentId, { component: { name: 'NEXT_PAGE', options: { bottomTabs: { visible: false, drawBehind: true, animate: true } } }, });`

This work for me. Thanks

**Comment by algorithmhash** [comment]
If anyone else needs this, this helped, for on app launch:
```
Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setDefaultOptions({
      /**
       * Add default options right here
       * This also, on app launch, sets bottomTab to invisible,
       * in case you are doing custom navigations with buttons and so on
       * and do not need the bottom tab bar and other things.
       */
      bottomTabs: {visible: false, drawBehind: true, animate: true}
    });
  });
```
