### ISSUE TITLE
How to view doesn't re-render when update state?

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#375]
### Issue Description

Hi all,

I have a problem when setState on screen.
On this screen i have many <View> and display by state property
When i tried setState, screen will re-render. How to only child view updated?

Thanks so much! 

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
Hey @agumack This question is more fitting to StackOverflow since it's not related to RNN. 👍
