### ISSUE TITLE
When are events for clicking tab items going to be done?

### ISSUE THREAD

**Issue by tylerclark** [wix/react-native-navigation#376]
I am really not able to use react-native-navigation because when I click on the different icons at the bottom I can't fire an event or events. Really need this ability. ETA on this?

**Comment by guyca** [comment]
It's actually been implemented on Android for quit some time, and wasn't implemented on iOS due to time constraints.

```js
class FirstTabScreen extends Component {
  ...

  onNavigatorEvent(event) {
    if (event.id === 'tabSelected') {
      // Handle tab selected
    }
    }
  }
}
```

**Comment by jingzhaoou** [comment]
I am working on iOS and would really like the feature to be available on iOS as well. Thanks a lot!

**Comment by simonmitchell** [comment]
We implemented this on iOS (kind of) using about 10 lines of code, see branch here: https://github.com/3sidedcube/react-native-navigation/tree/feature/view_lifecycle

**Comment by xiongjiabin** [comment]
@simonmitchell Will it accept as official release?

**Comment by gran33** [comment]
Thanks a lot guys! 
Please place a pull request. It will helps us to review your changes.

**Comment by xiongjiabin** [comment]
Have any plan for adding this feature? Great Thanks ! @guyca

**Comment by gran33** [comment]
Done, N-Joy!

**Comment by jingzhaoou** [comment]
Awesome!
