### ISSUE TITLE
[V2] bottom tab -> changing the text of the current tab is not working with mergeOptions()

### ISSUE THREAD

**Issue by hisothreed** [wix/react-native-navigation#3764]
### Issue Description
While trying to update the bottom tab text for a tab, it's updating everything but leaving the text as it is
### Steps to Reproduce / Code Snippets / Screenshots
```js
this.props.navigation.mergeOptions(this.props.componentId, {
    bottomTab: {
        text: "my reward"
    }
})

```
---
### Environment
* React Native Navigation version: 2.0.2472
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device, Debug and Release

**Comment by InternetExplorer8** [comment]
It seems that mergeOptions only works for the same stack level on which the screen is built. 
Similar case: https://github.com/wix/react-native-navigation/issues/3598

**Comment by hisothreed** [comment]
@InternetExplorer8 it's updating the badge count and showing it, but it's not updating the text so it's ignoring the text

**Comment by dozoisch** [comment]
I doubt this is stale.

**Comment by mralj** [comment]
I have the same issue 😕

**Comment by tsiory** [comment]
Same here when trying to update the bottomTab text ... it's not working, it works only if a re render the whole bottomTabs with Navigation.setRoot(); ... Can anyone help me to figure out how to change bottomTab text when language updated in store? (I use Redux if it can help)
