### ISSUE TITLE
[V2]Does v2 support deep link?

### ISSUE THREAD

**Issue by pakyo-pan** [wix/react-native-navigation#3768]
### Issue Description

Does v2 support deep link?  Thank you very much.

---
### Environment
* React Native Navigation version: 2.0.2468
* React Native version: 0.53.3

**Comment by lukebrandonfarrell** [comment]
Looks like it still needs to be done:
https://wix.github.io/react-native-navigation/v2/#/?id=screen-api-1

Not sure how far along the team are on working on this.

**Comment by pakyo-pan** [comment]
@lukebrandonfarrell Thank you!
