### ISSUE TITLE
[v2] topTabs inside bottomTabs

### ISSUE THREAD

**Issue by TimotheeMato** [wix/react-native-navigation#3769]
### Issue Description

I can't seem to have nested topTabs inside bottomTabs.
Here's the error I have : 
`Exception '-[RNNTopTabsViewController applyTabBarItem]: unrecognized selector sent to instance 0x7fa066f1e860' was thrown while invoking setRoot on target RNNBridgeModule with params`

Is it possible to have those nested layouts ?

### Steps to Reproduce / Code Snippets / Screenshots

Here's my current layout :
```
Navigation.setRoot({
      root: {
        bottomTabs: {
          children: [
            {
              topTabs: {
                children: [
                  {
                    component: {
                      name: 'FIRST_TOP_TAB',
                    },
                  },
                ],
              },
            },
          ],
        },
      },
    });
  });
```

---
### Environment
* React Native Navigation version: 2.0.2465
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by arpan-chaudhury** [comment]
I'm having this same issue. It seems like any sort of nested tabs creates this (bottom in bottom, top in bottom)

**Comment by hariDasu** [comment]
+1 for iOS top tabs
