### ISSUE TITLE
RNN in a container view

### ISSUE THREAD

**Issue by dmathewwws** [wix/react-native-navigation#3770]
Looking to build a navigation workflow where there is a persistent component below a bottom tabbar.  

The images below shows a screenshot of that, where a bottom tabbar does not take up the full height of the screen and there is a component (a persistent player) always at the bottom. Once you tap on a button of the bottom component it grows and pushes the tabbar up and shows a large representation of the bottom component (second image).

<img src="https://user-images.githubusercontent.com/2018931/44119017-c4a93704-9fcc-11e8-98d0-7d10e6dfe8ec.png" width="280" height="500">

<img src="https://user-images.githubusercontent.com/2018931/44119016-c49086fa-9fcc-11e8-9e56-3827b9714ec9.png" width="280" height="500">

Was thinking of implementing RNN for the Tab bar controller part of the app, which is the bulk of the app, and doing the bottom player natively. So, I'm wondering how to initialize RNN in a container and not the full window of the app.

I had a couple questions:
1) I do not believe I can use an overlay as it will hide the tabbar bottom options. Or is this something you would suggest.
2) Found externalComponent in the code, seems like it allows you add a uiviewcontroller to RNN's layout. What's a use case for this? wondering if that is a path I should explore more to solve this.
3) Starting with iOS, I was thinking of contributing (or forking if you dont want to include it) and adding a layout option of 'containerView' and using iOS's container view controller (which allows you to add a childViewController like another RNN layout like a TabBarContoller in this case. (A similar thing could possibly be done with fragments for Android, but I haven't looked at RNN's Android code yet to see if you are using Fragments vs Activities.)

Thanks for your help.
---
### Environment
RNN: version 2
* React Native Navigation version: v2
* React Native version: 0.55
* Platform(s) (iOS, Android, or both?):both

**Comment by dmathewwws** [comment]
Playing with the Wix app and realized you built something similar. Did you use showOverlay to accomplish this?

![img_7bd48444418f-1](https://user-images.githubusercontent.com/2018931/44172657-b65cbb00-a092-11e8-9b1a-60bcefe9acdb.jpeg)

**Comment by DVSoftware** [comment]
It is quite easy to implement your own tabbed screen in RN, which we do in our app, so you can create whatever you want at the bottom of the screen :)

**Comment by phuongwd** [comment]
@dmathewwws Did you have any solutions? I using the overlay to do that.

**Comment by dmathewwws** [comment]
@phuongwd have you check out the Wix iOS app? They have an example of an overlay for their "visitors on your page" inbox screen. I believe they use an overlay and would be a great UX for a player as well.

https://streamable.com/q87s8

**Comment by phuongwd** [comment]
@dmathewwws I think they use an modal or custom modal.

so, the UX look like:
- pressed on icon message
- show inbox screen and merge options:
` topBar: {
   visible: false,
  animate: true
},
bottomTabs: {
    visible: false,
    animate: true,
}`

**Comment by ouabing** [comment]
Same question here, our player modal has a long initialization time, rendering new modal for every pushed screen is not so ideal. Hope there will be some better solution!
