### ISSUE TITLE
[v2] BottomTabs hidden by default is not working

### ISSUE THREAD

**Issue by tiempham** [wix/react-native-navigation#3778]
Hi All!
I have facing problem with bottom tab options.
here is my code
`
    Navigation.setDefaultOptions({
      bottomTabs: {
        visible: false,
        drawBehind: true
      },
      layout: {
        backgroundColor: '#fff'
      }
    })
    Navigation.setRoot({
      root: {
        bottomTabs: bottomTabs()
      }
    })
    
`
### Environment
* React Native Navigation version: 2.0.2478
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): IOS, ( android not checked)
* Device info (Simulator/Device? OS version? Debug/Release?): both simulate and device.

**Comment by rendomnet** [comment]
Same updated from 2.0.2474 > 2.0.2509 and now my bottomTabs are visible despite 
```
options: {
          bottomTabs: {
            visible: false,
            animate: false,
            drawBehind: true
          }
        },
```
