### ISSUE TITLE
[v2] pushing screen with topbar visible from screen with invisible topbar

### ISSUE THREAD

**Issue by danielgindi** [wix/react-native-navigation#3788]
### Issue Description

I have a stack root with topBar set as `visible: false`, and a sidemenu.
Clicking on a sidemenu option - the menu is hidden and a new screen is pushed.
The problem is - that the topBar in the new screen is randomly visible or invisible (while it should be visible)

---
### Environment
* React Native Navigation version: 2.0.2478
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Api 28, Debug

**Comment by starzle** [comment]
Same here. Pushing a screen with visible topBar from a screen without a topBar will trigger this issue in Android.

A temporary workaround is to set animate: false in the parent screen. But a real fix would be much better.

**Comment by webdevsyd** [comment]
What I did for hackish fix is to set the topBar transparent:true and set the background color of topBar same with the content.

**Comment by danielgindi** [comment]
@webdevsyd yes but that won't work if you need to occupy that space with your own elements

**Comment by webdevsyd** [comment]
@danielgindi Did you solve this problem?

**Comment by danielgindi** [comment]
Shouldn't be marked as stale. Should be a priority for the author.

**Comment by danielgindi** [comment]
Shouldn't be marked as stale. Should be a priority for the author.

**Comment by danielgindi** [comment]
Shouldn't be marked as stale. Should be a priority for the author.

**Comment by danielgindi** [comment]
Again? Stupid bot.
