### ISSUE TITLE
Render Flash

### ISSUE THREAD

**Issue by joecaraccio** [wix/react-native-navigation#3789]
Hi Everyone,
RNN V1
I have seen this issue been posted about before. Basically on iOS the screen isn't done rendering before it is opened. Heres an example of it i found. Its realllllllly close though and maybe with a 10 ms delay would be fine. I noticed comparing my app to Twitter, that my app opens the next view almost quicker than Twitter does. The example I linked isn't my specific use case so setting a solid color won't work as the page has multi colored sections
Example:
http://g.recordit.co/IYWeaVyJnZ.gif

So I have a few questions:
- Is there a way to add a delay to avoid this? I'm talking something like:
Push Called -> Component Mounts and begins to render -> ~10 MS Delay -> Animation -> Enjoy
if so where in the native code would I place that so that it dosen't halt the rendering

- Is this not an issue in RNN V2? I'm on V1, if this has been ironed out in V2 I can just look to switching

Any thoughts?

**Comment by damathryx** [comment]
I am also experiencing this in v2 only on iOS. A simple console.log will trigger this ugly flicker on the screen.

**Comment by guyca** [comment]
You can configure push and show modal animation to wait for initial render.

```js
Navigation.setDefaultOptions({
  animations: {
    push: {
      waitForRender: true
    },
    showModal: {
      waitForRender: true
    }
  }
});
```
