### ISSUE TITLE
[v2] how to custorm animation like animationType: 'fade' in v1

### ISSUE THREAD

**Issue by tiennguyen9988** [wix/react-native-navigation#3790]
I was custom animation base on this code in V2, but it not working like property animationType: 'fade' in v1.
<img width="733" alt="screen shot 2018-08-19 at 9 02 47 am" src="https://user-images.githubusercontent.com/3782474/44304744-b7416580-a38e-11e8-8983-5f359839d676.png">
Please help me, Thanks!

**Comment by jun1st** [comment]
same issue here, 

Can someone improve the animation part on Doc V2?  needs more explanation and examples.

**Comment by akhenda** [comment]
Need help with this
