### ISSUE TITLE
[v2] [Android] this.props.navigator is not accessible and returns undefined in all components

### ISSUE THREAD

**Issue by spiraltrip** [wix/react-native-navigation#3795]
**DESCRIPTION**

I am unable to access `this.props.navigator` in all components. `console.log(this.props.navigator)` will return **`undefined`**

`this.props.componentId` is accessible so I can still use `Navigation.push(this.props.componentId, {...`

**STEPS TO REPRODUCE**

_**App.js**_
![image](https://user-images.githubusercontent.com/3600315/44325583-c35f1d00-a48b-11e8-90a5-cb6a6135a275.png)

_**screen.js**_
![image](https://user-images.githubusercontent.com/3600315/44325676-091be580-a48c-11e8-9e0a-6b5c1fb57904.png)

_**LoginForm.js**_
![image](https://user-images.githubusercontent.com/3600315/44325856-834c6a00-a48c-11e8-9abe-528218744c57.png)

**ENVIRONMENT**
* React version: 16.4.1
* React Native Navigation version: 2.0.2483
* React Native version: 0.55.4
* Platform(s): Android
* Device info: Android Emulator (Android 8.1) API 27

**ANDROID BUILD** 

* buildToolsVersion = "27.0.3"
* minSdkVersion = 19
* compileSdkVersion = 26
* targetSdkVersion = 26
* supportLibVersion = "26.1.0"

**Comment by DVSoftware** [comment]
this.props.navigator is not used anymore in 2.x.
You need to use Navigation

**Comment by spiraltrip** [comment]
@DVSoftware I just realised it too ><
