### ISSUE TITLE
[v2][iOS] topBar.backButton.icon : Image source back@3x.png size {27.5, 30} does not match loaded image size {27, 30}

### ISSUE THREAD

**Issue by retyui** [wix/react-native-navigation#3796]
### Issue Description
On IPhoneX emulator, will be next error appears (see screnshot)
How I can create 27.5 * 3 = `82.5px` back icon ?

### Steps to Reproduce / Code Snippets / Screenshots

When you run this code, the following error occurred!
```js
Navigation.setStackRoot(this.props.componentId, {
  component: {
        name: 'test.MyRootScreen',
        passProps: {
          text: 'My screen'
        },
        options: {
          backButton: {
            icon: require('./back.png'),
            visible: true
          },
        }
      }
});
```

![Image source back@3x.png size {27.5, 30} does not match loaded image size {27, 30}](https://pp.userapi.com/c845418/v845418044/cc18d/B7z2wcXGtTs.jpg)

---
### Environment
* React Native Navigation version: 2.0.2465
* Platform(s) : iOS
* Device info: Simulator , Debug mode, iOS 11.4
```sh
# react-native info
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 30.95 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.0.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.2 => 16.4.2
      react-native: ^0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

**Comment by herarya** [comment]
@retyui  try this 24X24 x1, 48x48 x2, 72x72 x x3

**Comment by retyui** [comment]
@herarya This helped solve the problem :+1:

**Comment by swapanil** [comment]
> @retyui try this 24X24 x1, 48x48 x2, 72x72 x x3

what is the third parameter?
height* width * ?

**Comment by gwmccull** [comment]
@swapanil you probably already figured it out but that's a file name parameter that can be used to help the OS pick the correct resolution for the icon

for example,
- `icon@1x.png` would be the 24x24 res
- `icon@2x.png` would be the 48x48 res
- `icon@3x.png` would be the 72x72 res

then the OS can choose to use the `icon@3x.png` if you have a retina-display phone
