### ISSUE TITLE
Rerendering on tab change

### ISSUE THREAD

**Issue by ninjz** [wix/react-native-navigation#38]
It seems to me that every time i switch tabs, every element in my component gets re-rendered. I notice this because i can see the images loading sequentially after switching to a tab, and instead of it being instant.

Is this the expected behaviour? I am using redux so that could be possibly a reason this may be happening - though I just migrated from react-native-flux-router and did not experience this on a tab change because I guess all the views are never being deallocated. 

EDIT:  It looks as if it is only Images which are the ones being re-rendered on each tab change

**Comment by guyca** [comment]
Did you notice this behaviour in Android or iOS?

**Comment by ninjz** [comment]
@guyca on IOS i have not tested this on android yet

**Comment by webzepter** [comment]
@guyca I notice this issue on iOS. After switching tabs using `switchTo` the React Native view re-renders. JavaScript component does not re-render, but native view does.

**Comment by alexeypodolian** [comment]
@guyca I also noticed this issue on iOS. On Android it works well.

**Comment by grundmanise** [comment]
@guyca same here on iOS

**Comment by larsvinter** [comment]
@guyca same here on iOS. White flickering when updating native view

**Comment by guyca** [comment]
@gran33 As @webzepter [mentioned](https://github.com/wix/react-native-navigation/issues/38#issuecomment-222498811) this is reproducible when using `switchToTab`

**Comment by fokoz** [comment]
@guyca Any update on this ? I am facing this issue just only when app becomes active from background then switch tab with a lot of images. Images re-render, they cause tab to freeze and switch after 1-2 second, this is very bad UX.

**Comment by gupta-ji6** [comment]
Try switching `lazy` to `false` in TabNavigatorConfig. See below for example. It rerenders all the tabs at once even if they are active or not.
```
swipeEnabled: true,
    lazy: false,
    navigationOptions: ({navigation}) => ({
    }),
    tabBarOptions: {
      style: {
        backgroundColor: "#222325"
      },
      activeTintColor: "white",
      indicatorStyle: {
        backgroundColor: "white"
      }
    },
    tabBarPosition: "top",
```
[Refer this link](https://v1.reactnavigation.org/docs/tab-navigator.html#tabnavigatorconfig)
