### ISSUE TITLE
Navbar title image on Android

### ISSUE THREAD

**Issue by glesage** [wix/react-native-navigation#380]
Hi there, any recommendations for implementing a navbar image instead of/next to the title on Android?

This works great on iOS but no luck for Android. Any thoughts on adding this as a feature?

Thanks!

Related: https://github.com/wix/react-native-navigation/issues/378 https://github.com/wix/react-native-navigation/issues/198 https://github.com/wix/react-native-navigation/issues/40 https://github.com/wix/react-native-navigation/issues/103 https://github.com/wix/react-native-navigation/pull/283

**Comment by guyca** [comment]
@glesage Can you please add a screenshot of how you'd expect this would look on Android?

I don't want to place the image in the centre of the TopBar, that would take away precious real estate from the RightButtons and just doesn't feel like a native Android app.
We could add support for multiple LeftButtons, but that also isn't native Android behaviour.

**Comment by glesage** [comment]
Hmm.. I was wondering about the Android guidelines on that, but couldn't find anything against it on the Google Material design guide https://material.google.com/layout/structure.html

Here is how we do it on iOS and were planing on doing it on Android

https://dl.dropboxusercontent.com/u/30415492/design/1.jpg
https://dl.dropboxusercontent.com/u/30415492/design/2.jpg

**Comment by glesage** [comment]
Nevermind, you are correct... material design standards recommend this way: https://dl.dropboxusercontent.com/u/30415492/design/navbar.png
