### ISSUE TITLE
[V2] TopBar custom components lose Props from passProps after navigating off screen and back 

### ISSUE THREAD

**Issue by leonid-shevtsov** [wix/react-native-navigation#3803]
### Issue Description

[In iOS,] If you have a custom topbar button component, and you `passProps` to it, the component receives props fine.

But when you navigate from the screen and then back, the custom component is now rendered without the passed props.

### Steps to Reproduce / Code Snippets / Screenshots

```js
// button declaration:
const TestButton = ({text}) => <Text>{text || "no text"}</Text>;
Navigation.registerComponent("topBar.Button", () => TestButton);

// screen options:
const options = {
  topBar: {
    title: {
      text: "Test"
    },
    leftButtons: [
      {
        id: "test",
        component: {
          name: "topBar.Button",
          passProps: { text: "some text"  }
        }
      }
    ]
}
```

1. Go to screen with button
2. Observe button with correct text
3. Navigate to any other screen - both `push` and `showModal` reproduce this.
4. Navigate back by `pop` or `dismissModal`.
5. Observe button with no text

---
### Environment
* React Native Navigation version: 2.0.2478
* React Native version: 0.56.0
* Platform: only tested on iOS
* Device info: iPhone 6 simulator, debug build

**Comment by vshkl** [comment]
@leonid-shevtsov if the problem is still valid, try `"react-native-navigation": "2.0.2506"`. It fixed the issue for me.

**Comment by naiduasn** [comment]
Any updates on this? its very crucial when we have navigate screens especially Pop screens out but still props has to be retained in the older screen.

**Comment by vshkl** [comment]
I'm currently using `v2.0.2509` and I don't have such a problem either on iOS or Android.
RNN V2 is still under development and a couple releases emerge every day, so in case of any problem, I'd try to bump a version first.

**Comment by eyes2design** [comment]
Seeing the same issue in IOS as well with our custom topbar. First rendering works and sets the text than when I navigate to the next page and come back the text shows for a moment and then disappears.

"react-native": "0.59.2",
"react-native-navigation": "2.15.0",
IOS Iphone X  12.2 emulation.
