### ISSUE TITLE
[V2][iOS] Adding native module via PodSpec failing

### ISSUE THREAD

**Issue by rizwankce** [wix/react-native-navigation#3810]
### Issue Description

If we follow the straightforward way (as mentioned in [documentation](https://wix.github.io/react-native-navigation/v2/#/docs/Installing)) of adding the native module `ReactNativeNavigation` from 
`node_modules/react-native-navigation/lib/ios/ReactNativeNavigation.xcodeproj`, linking would work fine without any issues.

But for those developers who add `ReactNativeNavigation` module as a `Pod`(Adding react native to existing native app). For now, it's failing. It is working fine for the v1 though. 

After some investigation figured out that `ReactNativeNavigation.podspec` is trying to get the source files from its GitHub repo tag name.

```ruby
  s.source       = { :git => "https://github.com/wix/react-native-navigation.git", :tag => "v#{s.version}" }
```

Above tag name is looks like `v2.0.2486` but actual tag name in our repo is just `2.0.2486`. So its failing for all v2 tags. 

### Steps to Reproduce / Code Snippets / Screenshots

* Add native module via `Podfile`
   ```ruby
   # React Native Navigation, where react_native_navigation_path is node_modules/react-native-     navigation/ReactNativeNavigation.podspec
     pod 'ReactNativeNavigation', podspec:react_native_navigation_path
   ```
* Run `pod install`
* Get an error like below
   ```sh
   [!] Error installing ReactNativeNavigation
   [!] /usr/bin/git clone https://github.com/wix/react-native-navigation.git /var/folders/_f/4w45wnmd2ql9z0kvdzht98dc0000gn/T/d20180821-4142-zdca0y --template= --single-branch  --depth 1 --branch v2.0.2485

   Cloning into '/var/folders/_f/4w45wnmd2ql9z0kvdzht98dc0000gn/T/d20180821-4142-zdca0y'...
   warning: Could not find remote branch v2.0.2485 to clone.
   fatal: Remote branch v2.0.2485 not found in upstream origin
   ```
### Possible Fix/ Workaround

We could either change the tag name from `2.0.XXXX` to `v2.0.XXXX` (or) If tag naming is something we can not change, we could simply edit the `Podspec` file like below.

```ruby
  s.source       = { :git => "https://github.com/wix/react-native-navigation.git", :tag => s.version }
```

---
### Environment
* React Native Navigation version: all V2 I have tried on (v2.0.2485)
* React Native version: Latest 
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by saleksandras** [comment]
Works for me using:
`pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'`

**Comment by rizwankce** [comment]
Fixed with https://github.com/wix/react-native-navigation/pull/3650 👍 so closing the issue
