### ISSUE TITLE
[V2][iOS] topBar `searchBar: true` doesn't work in statically for modal

### ISSUE THREAD

**Issue by chrise86** [wix/react-native-navigation#3814]
When using the following options inside a screen component:

```
static get options() {
  return {
    topBar: {
      searchBar: true,
      searchBarHiddenWhenScrolling: true,
      searchBarPlaceholder: 'Search questions...'
    },
  }
}
```

and opening a modal via:

```
Navigation.showModal({
  stack: {
    children: [{
      component: {
        name: 'Search',
        passProps: {
          userId: this.props.userId
        }
      }
    }]
  }
})
```

...the topBar is displayed but the search bar is not.

If you use the following:

```
Navigation.showModal({
  stack: {
    children: [{
      component: {
        name: 'Search',
        passProps: {
          userId: this.props.userId
        },
        options: {
          topBar: {
            searchBar: true,
            searchBarHiddenWhenScrolling: true,
            searchBarPlaceholder: 'Search questions...'
          }
        }
      }
    }]
  }
})
```
... then it works fine.

---
### Environment
* React Native Navigation version: `2.0.2468`
* React Native version: `0.56`
* Platform(s) (iOS, Android, or both?): `iOS`
* Device info (Simulator/Device? OS version? Debug/Release?): `Debug, Device`

**Comment by naveenkonduru** [comment]
Either way seachBar is not showing in showModal for me.

**Comment by WeiLiangTan** [comment]
Same for me, not showing at all no matter where i declare `searchBar: true`

RN version: 0.55.4,
RNN version: 2.0.2556

**Comment by TNicholson11** [comment]
Also looking to use the searchBar in modals... any traction on this issue? Workarounds?

RNN v2.0.2588

**Comment by matpaul** [comment]
+1 not showing at all
RNN v2.1.2

**Comment by matpaul** [comment]
Hi @ptmt, can you help us with your search feature?)

**Comment by gsdatta** [comment]
Same issue. If I add `searchBar: true` to every single tabs when I instantiate tabs layout, it'll show up on the first tab and only that tab. Move the option to one of the tabs, and it no longer works.

Doesn't work with `static get option` or `mergeOptions`.

**Comment by gsdatta** [comment]
Hah, figured out seconds after posting. I had `drawBehind` set to `true`. It needs to be `false` in the `topBar` for the search bar to show.

**Comment by mikitasavanovich** [comment]
The same problem for me.
RN: 0.54.5
RNN: 2.0.2510

**Comment by mikitasavanovich** [comment]
> Either way seachBar is not showing in showModal for me, is there any working example where I can refer.

The same problem for me.
RN v0.54.4
RNN v2.0.2510

**Comment by emielvanliere** [comment]
I still have this issue, the searchBar doesn't show in a modal.

The only way I can get it to show is:

1. Show modal, with a stack inside (searchBar not shown)
2. Push screen
3. Navigate back
4. Now the searchBar is shown

iOS: 12.1
RN: 0.56
RNN: 2.5.0

**Comment by chrise86** [comment]
I can't get the `searchBar` to show at all any more when used in a tab setup. I've tried defining in default options, the options passed when setting root and statically using `static options`.

**Comment by chrise86** [comment]
So it turns out, as @emielvanliere pointed out above, it only shows after navigating...
