### ISSUE TITLE
Can't set left buttons on Android

### ISSUE THREAD

**Issue by trofima** [wix/react-native-navigation#3818]
On Android it's impossible to set `leftButtons`. Tried `mergeOptions` and style object in `push`.
Works on iOS.
Update: reproduces for text buttons (with the `text` property). Works, when setting `icon`.

**Comment by guyca** [comment]
Only left buttons with icons are supported on Android.

**Comment by L-Yeiser** [comment]
There is a real underlying issue here. One setting the left button works when defined as a static option but not using `mergeOptions`.

**Comment by L-Yeiser** [comment]
There is an underlying issue here on Android. When calling `mergeOptions` to set the `leftButtons` if that style object also contains `backButton: { color: any Color }` the leftButtons do not merge. Passing the backButton color does not break the styles when setting the `leftButtons` via `static options`

**Comment by kiroukou** [comment]
> Only left buttons with icons are supported on Android.

Oh... that note, if present in a more visible way (or visible at all) in the documentation would have saved me many wasted hours... :(

**Comment by hariDasu** [comment]
this renders overriding the back button behavior impossible on android then?

**Comment by hariDasu** [comment]
https://facebook.github.io/react-native/docs/0.57/backhandler#docsNav

will still work with andriod, however my <CustomBackButton/> does not render on android. the disparity of feature implementations on iOS vs android make the logic in cross platform components rather hairy, but it is still less work than writing a swift and kotlin code base so, here we go...

¯\_(ツ)_/¯
