### ISSUE TITLE
Bottom tabs disappear on pop operation in some scenarios 

### ISSUE THREAD

**Issue by trofima** [wix/react-native-navigation#3819]
When screen is hiding bottomTabs, in this case bottomTabs also disappear on previous screen

``` 
Navigation.push('screenWithBottomTabs') 
...
Navigation.push('screenHidingBottomTabs') 
...
Navigation.showModal('modalUponTheScreen')
...
await Navigation.pop('screenHidingBottomTabs');
Navigation.dismissModal('modalUponTheScreen');
```
So in this case bottom tabs unexpectedly disappear from the 'screenWithBottomTabs'.
This reproduces only on iOS and only in if you are poping the screen before the modal.

**Comment by guyca** [comment]
@silyevsk @yogevbd Any chance this is related to the bottom insets issue?
