### ISSUE TITLE
[V2] [Android] BottomTabs component does not apply testID

### ISSUE THREAD

**Issue by danielocampo2** [wix/react-native-navigation#3820]
### Issue Description

`BottomTabs` component doesn't apply defined testID in Android. iOS is working as expected.

### Steps to Reproduce / Code Snippets / Screenshots

Define your BottomTabs stack using testID, like this:
```
const createBottomTabStack = ({ name, text, icon }) => ({
  stack: {
    children: [
      {
        component: {
          name,
          options: {
            bottomTab: {
              text,
              icon,
              testID: `navigation-tab-${name}`
            }
          }
        }
      }
    ]
  }
})
```

Expected: testID is set in each tab so the tab can be found by id / accessbilityLabel when doing automation.

Actual: testID is not present so the tab cannot be found.

---
### Environment
* React Native Navigation version: 2.0.2475
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Any - tested mostly in simulator

**Comment by robertofrontado** [comment]
Hey @danielocampo2!

Did you find a way to solve this?
