### ISSUE TITLE
[v2] ScrollView content always offsets from top by  statusbarheight in iOS

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#3821]
### Issue Description

If I will make ScrollView take whole screen, then it content will always offsets from the top by the amount of statusbar height.

```
<ScrollView
        style={[
          {
            flex: 1,
            padding: 0,
            margin: 0,
            borderColor: "red",
            borderWidth: 1
          }
        ]}
      >
        <View
          style={{
            height: 300,
            borderColor: "green",
            borderWidth: 1
          }}
        />
</ScrollView>
```

[image](https://user-images.githubusercontent.com/18900210/44459920-17edce00-a62d-11e8-898b-46caf2f8aedf.png)
red border - is ScrollView
green border - is children View inside ScrollView

### Steps to Reproduce / Code Snippets / Screenshots

Make ScrollBar fill entire view and put children inside of it.

---
### Environment
* React Native Navigation version:2.0.2474
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): sim

**Comment by Skyien** [comment]
+1 Same problem

**Comment by VicFrolov** [comment]
+1 same issue

**Comment by TomAtterton** [comment]
Adding the  the prop ` contentInsetAdjustmentBehavior="never" ` to scrollview should solve the issue for devices using iOS 11+ . 
But the issue still persists with versions earlier than iOS 11 adding ` automaticallyAdjustContentInsets={false}` doesn't seem to solve the issue, but a quick cheap fix is to just update the contentInsets `     contentInset={{ top: -20, left: 0, bottom: 0, right: 0 }}`.
