### ISSUE TITLE
android: setTitle breaks navbar left button (shows <- instaed of X)

### ISSUE THREAD

**Issue by ronywix** [wix/react-native-navigation#3825]
When setting navbar title in a modal srceen, left button displays <- instead of X and the clicking on it performs nothing

```
this.props.navigator.setButtons({
      rightButtons: [{id: 'share', icon: require('../../img/promote/share-Icon.png')}]
});

```
followed by 

`this.props.navigator.setTitle({title: i18n('COMPOSER_TITLE_PRESETS')});`

Also happens here:
https://github.com/wix-private/promote/blob/master/wix-promote-app-module/src/screens/Home.js

and here:
https://github.com/wix-private/promote/blob/master/wix-mobile-facebook-module/src/screens/Pages.js

**Comment by ethanshar** [comment]
what happens here is by default when opening a modal wrapped with `asWixScreen` the modal comes with our X left button (and its functionality)
during the runtime of the screen there's a code the execute `this.props.navigator.setTitle(...)` and it overrides the left button to its default icon (the arrow icon) and remove the functionality.
