### ISSUE TITLE
Can't hide back button and border for modal

### ISSUE THREAD

**Issue by andy-zy** [wix/react-native-navigation#3826]
### Issue Description

Can't hide back button and border for modal on Android. Tried all known ways:

1. On modal call

```
Navigation.showModal({
        stack: {
          children: [{
            component: {
              name: SCREENS.BOOKING_SUCCESS,
              passProps: {
                callback: isScreen ? () => {
                  Navigation.popTo(returnScreenComponentId);
                } : null
              },
              options: {
                topBar: {
                  noBorder: true,
                  backButton: {visible: false},
                  leftButtons: [],
                },
                popGesture: false,
              }
            }
          }]
        }
      });
```

2. Statically

```
static get options() {
    return {
      topBar: {
        noBorder: true,
        leftButtons: [],
      },
    };
  }
```

3. On mount

 ```
componentWillMount() {
    Navigation.mergeOptions(this.props.componentId, {
      topBar: {
        noBorder: true,
        leftButtons: [],
      },
    });
  }
```

No results, only on componentWillUpdate it works but it is a hack and reduces performance.  

### Repo steps

email: andriiz@wix.com
password: 1q2w3e4r

1. Go to Bookingpremium place
2. Open Services tab
3. Tab on any class
4. Tab Book Now button

You should end up on Booking Success screen

![image](https://user-images.githubusercontent.com/6594975/44647581-1898b280-a9e7-11e8-836b-db039cc4c91f.png)

---
### Environment
* React Native Navigation version: 2.0.2490
* React Native version: 0.51.2400
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
`noBorder` is an iOS options, use `elevation: 0` to remove the TopBar elevation Or better yet: 
```js
topBar: {
  visible: false
}
```
