### ISSUE TITLE
App crash while running from visual studio code

### ISSUE THREAD

**Issue by joker2210** [wix/react-native-navigation#3827]
Hello,
I am new to React native. I am facing issue while deploying app to my android device running on oreo-8.
It crashes every time i deploy saying "App has stopped" even it builds successfully. Its just hello world program. 
Configuration 
react-native : 0.44.1.
OS : Windows 7

As i am not running code from Android studio i dont have logs. I am using Visual studio code to build and run on device.

Following are the files:
Package.json : 
{
  "name": "RNHelloWorld1",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.4.1",
    "react-native": "0.44.1"
  },
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-preset-react-native": "5.0.2",
    "jest": "23.5.0",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

index.json:

//import {AppRegistry} from 'react-native';
//import App from './App';
//import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);

I commented import to fix "Module does not exist in the module map".

App.js : 
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

//import React, {Component} from 'react';
//import {Platform, StyleSheet, Text, View} from 'react-native';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
 
![image](https://user-images.githubusercontent.com/42615136/44476839-96129a80-a656-11e8-9db0-d2215c168387.png)

Kindly help me here to point out the issue. And please let me know if you need more information from me to debug this.

**Comment by ItsNoHax** [comment]
Please close this issue. You are not even using the library. Post your RN issues in the official react-native repository: https://github.com/facebook/react-native/issues
