### ISSUE TITLE
[v2] Custom top bar component issue Android

### ISSUE THREAD

**Issue by kentdev92** [wix/react-native-navigation#3838]
### Issue Description

I am using a custom component for the topBar on my tab stack.
It work fine on iOS but got issue like picture below here

### Steps to Reproduce / Code Snippets / Screenshots

Here is my options inside first tab screen
`  
static get options() {
    return {
      topBar: {
        visible: true,
        translucent: true,
        background: {
          color: "rgba(217, 73, 114, 0.5)",
          component: {
            name: "app.customtopbar"
          }
        }
      }
    };
  }`

<img width="688" alt="screen shot 2018-08-23 at 5 50 50 pm" src="https://user-images.githubusercontent.com/17426288/44521941-23112e80-a6ff-11e8-8dac-0bcb41cf2ca2.png">

---
### Environment
* React Native Navigation version: "react-native-navigation": "^2.0.2489",
* React Native version: "react-native": "^0.55.4",
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Nexus 5X Android 8.1 Debug

**Comment by hungcv92** [comment]
At lastest version. This issue is still relevant. Please check this and help me.
Now the only way i found  to replace this are using custom component of button topBar.
But this solution only can do with one button, when i try to add more two button. Still got error in layout.

**Comment by peterh32** [comment]
Try wrapping your header component in a container with a minHeight, minWidth, and backgroundColor:

```
<View style={{minWidth: 400, minHeight: 40, backgroundColor: 'transparent'}} >
    <...your component...>
</View>
```
I was attempting to implement a topbar component with a TouchableOpacity and an Image and was getting extremely bizarre rendering behaviors, only on Android. This fixed it.
