### ISSUE TITLE
Reset bottomTab.badge when passing an empty string

### ISSUE THREAD

**Issue by yogevbd** [wix/react-native-navigation#3839]

**Comment by manosim** [comment]
Here's my work-around:

To remove the badge, I have to pass an empty string on android & `null` on iOS.

```
const isIos = Platform.OS === 'ios';

Navigation.mergeOptions(componentId, {
  bottomTab: {
    badge: isIos ? null : '',
  },
});
```

**Comment by guyca** [comment]
@manosim What version of RNN are you using? I'm pretty sure this is already resolved, i.e passing empty string clears the badge.

**Comment by Embraser01** [comment]
it seems that on RNN 2.18.4, passing `null` does not work anymore but passing an empty string do
