### ISSUE TITLE
[V2] BackButton color on iOS 10

### ISSUE THREAD

**Issue by thame** [wix/react-native-navigation#3840]
### Issue Description

BackButton color is not applied on iOS 10. 

### Steps to Reproduce / Code Snippets / Screenshots

Setting backButton color using setDefaultOptions:

```
backButton: {
     title: 'Back',
     color: '#333333',
}
```
In iOS 11 and Android, the correct backButton color is applied. In iOS 10, the color remains blue.

---
### Environment
* React Native Navigation version: 2.0.2478
* React Native version: 0.51.0
* Platform(s) (iOS, Android, or both?): iOS, 10.2
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iPhone 6, iPhone 7, iPhone SE

**Comment by makirby** [comment]
@thame there is already a ticket for this https://github.com/wix/react-native-navigation/issues/3731
