### ISSUE TITLE
[V2] PassProps is broken

### ISSUE THREAD

**Issue by eleretic** [wix/react-native-navigation#3842]
### Issue Description

PassProps doesn't work. Passing props like it is done in the playground app results in undefined props in components. Also, componentId, which I've come to understand that is supposed to be passed to every screen behind the scenes, is undefined

~~There is no example in the playground app. All passProps references are in the deprecated or old-example-redux folder.~~

### Steps to Reproduce / Code Snippets / Screenshots
```
Navigation.push('Kimoby.Stacks.Customers', {
      component: {
        name: 'Kimoby.Customer',
        passProps: {
          customerId: customer.id,
          customer: customer
        }
      }
    })
```
```
Navigation.push('Kimoby.Stacks.Customers', {
      component: {
        name: 'Kimoby.Customer',
        options: {
          passProps: {
             customerId: customer.id,
             customer: customer
          }
        }
      }
    })
```
```
CustomerComponent: this.props.customerId === undefined
```
```
CustomerComponent: this.props.componentId === undefined
```
---
### Environment
* React Native Navigation version: 2.0.2478
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info : Simulator and Device,  Android 8, Debug and Release

**Comment by wbeuil** [comment]
Did you find a way to make it work? I have the same problem on Android ...

**Comment by eleretic** [comment]
Nope, sorry. Still awaiting answer from repo managers.

**Comment by guyca** [comment]
Hey there, I'm not aware of any issues passing props. The first snippet is correct, the second isn't.
[Here's an example from the playground app for passing props](https://github.com/wix/react-native-navigation/blob/v2/playground/src/screens/ModalScreen.js#L75), we have e2e on pass props so I don't think it's broken.
If you can reproduce this issue in the playground app, pelese PR a failing e2e test

**Comment by getDanArias** [comment]
I was having problems with anything defined within `passProps` not being available within the component. I felt maybe this had to do something with the app bundling process.

I stopped the Metro Bundler running on port 8081 and run `react-native run-android` again and it worked 🙌

**Comment by KovalevAnton** [comment]
Why the issue was closed? Any solutions?

**Comment by NirpE** [comment]
I am seeing props being undefined with `showOverlay` and `showModal`. Using `push` they seem to be working.

**Comment by cuongtora1996** [comment]
I faced this issue too. Any solutions guys?

**Comment by stevenkampen** [comment]
I also see this on version 2.11.0. Haven't done a lot of testing, but nothing passed in with `passProps` in `showModal` is ending up in the component.

**Comment by guyca** [comment]
@cuongtora1996 @stevenkampen Can you guys please try latest snapshot? `2.11.0-snapshot.200`

**Comment by cuongtora1996** [comment]
@guyca Still don't work with `push`

**Comment by krookten14** [comment]
PassProps doesn't work when I use it with redux, or is there something wrong with how I get the passprops and the props from my reducers

**Comment by max77p** [comment]
I am having this issue as well. How do you actually get the props when passing props? 
+1 bump

**Comment by askmakdag** [comment]
any solutions ? please ...

**Comment by guyca** [comment]
Hey guys
If you believe there's an issue with passProps, then please pr a failing e2e or unit test.
e2e tests for passProps can be found [here](https://github.com/wix/react-native-navigation/blob/master/playground/src/screens/PushedScreen.js#L66)
Unit tests can be found [here](https://github.com/wix/react-native-navigation/blob/master/lib/src/commands/OptionsProcessor.test.ts)
