### ISSUE TITLE
Hide Topbar on Android

### ISSUE THREAD

**Issue by joecaraccio** [wix/react-native-navigation#3843]
Unlike iOS, when you set the top bar to not be visible on android, the gap still exists.

If you then set to draw underneath the top bar, it does, but still initially loads that area white and fills it in. Is there a solution to this?

**Comment by kdawgwilk** [comment]
We just upgraded using the v1-v2 adapter and are also seeing this

**Comment by ahmedfouad2016** [comment]
you can set topBar height = 0 . till this issue solved 

`options:{
               topBar: {
                            visible: false,
                            height: 0,
                           }
 }`

**Comment by alexkbsoft** [comment]
Fix this quickly!!

**Comment by alexkbsoft** [comment]
height: 0 is not working!

**Comment by alexkbsoft** [comment]
Navigation.setRoot({
        root: {
            bottomTabs: {
                animate: false,
                children: [
                    {
                        stack: {
                            children: [{
                                component: {
                                    id: DASHBOARD_TAB_ID,
                                    name: 'DashboardScreen'
                                }
                            }],
                            options: {
                                bottomTab: {
                                    text: 'Поиск',
                                    icon: searchAsset
                                },
                                topBar: {
                                    visible: false,
                                    height: 0
                                }
                            }
                        }
                    }

**Comment by alexkbsoft** [comment]
Ok, its working if inside componet:
stack: {
                            children: [{
                                component: {
                                    id: DASHBOARD_TAB_ID,
                                    name: 'DashboardScreen',
                                    options: {
                                        topBar: {
                                            visible: false
                                        }
                                    }
                                }
                            }],
                            options: {
                                bottomTab: {
                                    text: 'Search',
                                    icon: searchAsset
                                }
                            }
                        }

**Comment by sudarakas** [comment]
Try this
```
HomeScreen.options = {
    topBar: {
        visible: false
    }
}
```
