### ISSUE TITLE
[v2] TopBar and DeviceStatusBar measurement problem in Android.

### ISSUE THREAD

**Issue by manattersa** [wix/react-native-navigation#3844]
### Issue Description

Trying to get measurements for the TopBar and DeviceStatusBar using Navigation.constants() promise returns higher sizes than the expected.

### Steps to Reproduce / Code Snippets / Screenshots

  Navigation.constants().then(({ statusBarHeight, topBarHeight }) => {
	// logs 147.5 # 63 on Android, 44 # 20 on iOS
	console.log(`${topBarHeight} # ${statusBarHeight}`);
  })

In NavigationModule.java, the method getConstants(Promise promise) calculates two times the TOP_BAR_HEIGHT_KEY Constants, each one of them with a pixel size value. Could be this a problem?

---
### Environment
* React Native Navigation version: 2.0.2488
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, API 24, Debug

**Comment by jinshin1013** [comment]
It's either the [doc](http://wix.github.io/react-native-navigation/v2/#/docs/constants) is wrong or something doesn't seem right here. According to the doc, it should not be a promise. But until things get clarified, you might as well use other library to obtain statusBarheight like react-native-iphone-x-helper.

**Comment by manattersa** [comment]
You're right @jinshin1013, the docs doesn't say anything about a promise, but that's the way it works. Right now i'm using the PixelRatio class if the Platform is Android to solve this. Something like:
`Navigation.constants().then(({statusBarHeight, topBarHeight }) => {
      const ratio = Platform.OS == 'ios'? 1 : PixelRatio.get();
      const tph = topBarHeight / ratio;
      const sbh = statusBarHeight / ratio;
      ...
  });`

**Comment by dozoisch** [comment]
Probably shouldn't be stale

**Comment by dozoisch** [comment]
Not stale
