### ISSUE TITLE
[v2] Weird topbar animation when swiping right in stack layout

### ISSUE THREAD

**Issue by ouabing** [wix/react-native-navigation#3846]
### Issue Description

Swiping screen right in stack layout from screen A(with topbar visible: true) to screen B (with topbar visible: false) will trigger weird topbar animation. But if I set topbar animate to false, the topbar hide immediately when I just start the swipe gesture.

This happened after upgrading from 2.0.2461 to 2.0.2497. I can confirm it works fine in 2.0.2461.

### Steps to Reproduce / Code Snippets / Screenshots

Swiping from A to B with animate setting to false (GIF):

![issue-gif1](https://user-images.githubusercontent.com/1430376/44566538-b77f9d80-a7a0-11e8-8470-ab933edd4283.gif)

Swiping from A to B with animate setting to true (GIF):

![issue-gif2](https://user-images.githubusercontent.com/1430376/44566632-1fce7f00-a7a1-11e8-812d-f202275ebc6b.gif)

---
### Environment
* React Native Navigation version: 2.0.2497
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device, latest iOS version, both in debug and release mode

**Comment by guyca** [comment]
@yogevbd We should document best practices in this regard.

**Comment by ouabing** [comment]
Is there any quick way I can fix this?

**Comment by quy1403** [comment]
@guyca  please fix this, thanks u!

**Comment by steffenmllr** [comment]
@guyca can you elaborate what the best practice is here ? I can make a PR to the Docs if I know what to do :)

**Comment by ouabing** [comment]
Still exist in 2.0.2580.

**Comment by ouabing** [comment]
Seem like it's fixed in 2.1.0, thanks guys!
