### ISSUE TITLE
Can not seem to use mergeOptions to overwrite topBar button colors

### ISSUE THREAD

**Issue by reganperkins** [wix/react-native-navigation#3848]
### Issue Description
I can use mergeOptions to change the background color (ie in example from red to blue) but i can not change the leftButton color (amongst others), however if i dont have left buttons set i can add it from mergeOptions.

### Steps to Reproduce 

```js
Navigation.setStackRoot(this.props.componentId, {
  component: {
    name: 'teams',
    passProps: { teams: true },
    options: {
      topBar : {
        leftButtons: {
          id: 'drawer-btn',
          icon:require('../img/icon_menu.png'),
          disabledColor: 'trasnparent',
          color: getDrawerIconColor()
        },
        background: {
          color: background,
        },
      }
    }
  },
});

Navigation.mergeOptions(this.props.componentId, {
  topBar: {
    background: {
      color: 'red'
    },
    leftButtons: {
      color: 'blue'
    }
  }
});
```
---
### Environment
* React Native Navigation version: 2.0.2497
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): ios have not yet checked android

**Comment by guyca** [comment]
Hey @reganperkins 
Updating button properties isn't supported. in order to update the left button, you'll need to set it again with the updated color (or other properties)

```js
Navigation.mergeOptions(this.props.componentId, {
  topBar: {
    leftButtons: {
        leftButtons: {
          id: 'drawer-btn',
          icon:require('../img/icon_menu.png'),
          disabledColor: 'trasnparent',
          color: 'red'
        }
        // right buttons won't be affected by this call.
    }
  }
});
```

**Comment by stokesbga** [comment]
Wait, wasnt this supported a few versions ago? Or am I thinking of V1

**Comment by freudibili** [comment]
Same problem here. Please can you update it ?
