### ISSUE TITLE
V2 Documentation out of date

### ISSUE THREAD

**Issue by AbdoelKaheal** [wix/react-native-navigation#3858]
### Issue Description

I'm having a really hard time understanding the docs for V2. I took a look at the playground to see if it will be any more helpful and there seems to be a lot of things un documented with V2 that are seen in the playground. I understand that V2 was just released and is still in alpha but can someone please take the time to make a PR and update the docs? 

Thank You!

**Comment by guyca** [comment]
Hey @AbdoelKaheal 
The documentation is a slow work in progress. Hopefully we'll have more time to invest in improving it in the near future.
What do you think it's currently lacking?
