### ISSUE TITLE
modalPrsentationStyle not working iOS?

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#3859]
### Issue Description

I can not get the modalPresentationStyle to work.  The modal always shows over the fullScreen.  I'm not sure if there is a problem with the version or that I'm not implementing this right.  

### Steps to Reproduce / Code Snippets / Screenshots

I've tried the following, first onPress showModal
```
    Navigation.showModal({
      component: {
        name: 'demoModalScreen',
        passProps: {
          modalPosition: this.getModalPosition() + 1,
          previousModalIds: _.concat(
            [],
            this.props.previousModalIds || [],
            this.props.componentId
          ),
          callback: event => {
            Navigation.dismissModal().then(() => {
              if (callback) {
                callback(event);
              }
            });
          },
        },
        options: {
          modalPresentationStyle: 'formSheet',
          animated: false,
        },
      },
    });
```
then by setting options of the screen which opens the modal.
```
  static get options() {
    return {
      modalPresentationStyle: 'formSheet',
    };
  }
```
In either case, the modal opens the same way.

---
### Environment
* React Native Navigation version: 2.0.2487
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by yogevbd** [comment]
Working good in RNN playground.. Maybe your component define `backgroundColor` style?
Also try: `modalPresentationStyle: 'overCurrentContext'`
