### ISSUE TITLE
Drawer & Modals not working correctly

### ISSUE THREAD

**Issue by mshaaban0** [wix/react-native-navigation#386]
### Issue Description

I have an issue with Modals, when ever i use dismissModal the app navigates to the drawer as a full screen, and freezes without any errors or warnings.

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.startTabBasedApp({
  tabsStyle: {
    tabBarButtonColor: '#A2A1A1',
    tabBarBackgroundColor: '#F7F7F7',
    tabBarSelectedButtonColor: '#EA5A5B'
  },
  portraitOnlyMode: true,
  tabs: [
    {
      label: 'Home',
      screen: 'Kharabeesh.homePage',
      icon: require('./assets/home@2x.png'),
      selectedIcon: require('./assets/home-selected@2x.png'),
      title: 'Kharabeesh',
      titleImage: require('./assets/icon-logo@2x.png')
    },
    {
      label: 'Favorites',
      screen: 'Kharabeesh.appFavs',
      icon: require('./assets/favorite@2x.png'),
      selectedIcon: require('./assets/favorite-selected@2x.png'),
      title: 'Favorites',
      titleImage: require('./assets/icon-logo@2x.png')
    },
    {
      label: 'Categories',
      screen: 'Kharabeesh.appCategories',
      icon: require('./assets/categories@2x.png'),
      selectedIcon: require('./assets/categories-selected@2x.png'),
      title: 'Categories',
      titleImage: require('./assets/icon-logo@2x.png')
    },
    {
      label: 'Featured',
      screen: 'Kharabeesh.appFeat',
      icon: require('./assets/featured@2x.png'),
      selectedIcon: require('./assets/featured-selected@2x.png'),
      title: 'Featured',
      titleImage: require('./assets/icon-logo@2x.png')
    }
  ],
  drawer: {
    left: {
      screen: 'Kharabeesh.SideMenu'
    },
    disableOpenGesture: true,
    type: "TheSideBar",
    animationType: "luvocracy"
  }
});
```

![menubug-optimized](https://cloud.githubusercontent.com/assets/6163988/19479227/670d88f0-954e-11e6-8686-e3962b7cf5cc.gif)

---
### Environment
* React Native Navigation version: 2.0.0-experimental.133
* React Native version: 0.33.0
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device IOS 10

Thanks

**Comment by gran33** [comment]
@mshaaban0 Thanks for using `react-native-navigation`.
Just to make clear, R u try to dismiss FB login screen with `dismissModal` of `react-native-navigation`?

**Comment by mshaaban0** [comment]
Hi @gran33 
Thanks for the reply. i am not using dismissModal on facebook login.
Actually this happens also when i use `dismissModal`, at this example i am using `react-native-facebook-login` which opens also a modal. so i think it's a modal related thing, not only on dismissModal.

**Comment by gran33** [comment]
@mshaaban0 Can u plz add some more code and information on how and when do u use `dismissModal`? How do u use the FB login?

What's feel to me is that r using `dismissModal` and the modal is the main screen (the one in the center).

U can take a brief look in the native `iOS`code and see figure out how the `dismissModal` is implemented:
https://github.com/wix/react-native-navigation/blob/8b034b2ebb95f482b594a467bd98942f0bce16ce/ios/RCCManagerModule.m#L54
U can see there that it uses the `rootViewController` which means in your case the central screen.

I need to have some more info in order to solve this issue and help.

**Comment by mbizplus** [comment]
Hi, I have same problem. 
When I using showModal form any screen and when i use dismissModal the app alway to the drawer as a full screen.
