### ISSUE TITLE
[V2] How to use with react-native-notifications

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#3872]
### Issue Description

I posted the same issue in the react-native-notifications repository but it seems that development efforts on that repository are dead.

How can we use this with react-native-notifications?

### Environment
* React Native Navigation version: Latest alpha
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): Android

**Comment by ItsNoHax** [comment]
Basically figured it out myself, since RNN V2 extends the normal activity, you can just ignore the GIST about integration with RNN.

**Comment by lukebrandonfarrell** [comment]
@ItsNoHax would you be able to share your implementation?
