### ISSUE TITLE
Navigation is undefined during unit tests

### ISSUE THREAD

**Issue by abury** [wix/react-native-navigation#3873]
### Issue Description

Hey RNN team 👋

I'm getting RNN setup for a new project with high test coverage requirements, and I'm finding that Navigation is undefined when running jest.

If you have any ideas on what might be wrong, It would be amazing. The test I'm trying to write is really really simple (make sure push is called once with certain parameters) and I've been banging my head against a wall for the last few hours trying to get it working.

Thanks!

### Steps to Reproduce / Code Snippets / Screenshots
helpers.test.js
```javascript
import { Navigation } from 'react-native-navigation';

 Navigation.push('component2', {
   component: {
     name: 'Hello'
   }
 })
```
The test always fails with `TypeError: Cannot read property 'push' of undefined`

This error shows up no matter where we call Navigation.push. What's even more perplexing is if we `console.log(Navigation.push)` we get `[Function: push]`

---
### Environment
* React Native Navigation version: 2.0.2497
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Unit Testing (Jest)
* Device info (Simulator/Device? OS version? Debug/Release?): N/A

**Comment by abury** [comment]
As is usually the case, posting a Github question has helped me resolve it myself 😂

I ended up just using Sinon to stub it out and it worked like a charm. Still not sure why the above error is showing up, during unit tests but adding a Sinon stub lets me work around it. 👍

**Comment by wbeuil** [comment]
@abury How did you manage to stub the function ? I can't find a way to make it work ...

**Comment by abury** [comment]
@wbeuil 
```javascript
import { Navigation } from 'react-native-navigation';
import sinon from 'sinon';

const pushStub = sinon.stub(Navigation, 'push').callsFake(() => true);

describe('Navigation is called', () => {
  test('push is called', () => {
    Navigation.push('Component1', {
      component: {
        name: 'ScreenName'
      }
    })
    expect(pushStub.called).toBeTruthy();
  });
});
```
