### ISSUE TITLE
[v2] Set background color for StatusBar when topBar is hidden

### ISSUE THREAD

**Issue by nicgutierrez** [wix/react-native-navigation#3876]
I can see in the documentation that there's a way to set a background color for the status bar, however, such option doesn't exist for iOS.

When using `hideOnScroll: true` and  statusBar `style: 'light'`, the topBar disappears just fine, but the statusBar becomes almost invisible. 

Is there any way or workaround to set a background color (or a background view?) to the status bar?

**Comment by sejr** [comment]
I am trying to handle this issue as well. Ideally I would use a blur view (which iOS has already) but I'd settle for a color. @nicgutierrez  did you have any luck with this?
