### ISSUE TITLE
feature request: navigator.showLightBox

### ISSUE THREAD

**Issue by mbardauskas** [wix/react-native-navigation#388]
Please implement the ability to subscribe to LightBox background/backdrop touch events.
If not possible, please add flag param to showLightBox method which would dismiss the lightBox by clicking the background/backdrop

**Comment by guyca** [comment]
[tapBackgroundToDismiss](https://wix.github.io/react-native-navigation/#/top-level-api?id=showlightboxparams-) is now available 👍
