### ISSUE TITLE
[v2] [iOS] bottomTabs visible:false not working after updating 2.0.2474 > 2.0.2509

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#3883]
### Issue Description

iOS: Updated from 2.0.2474 > 2.0.2509 and now my bottomTabs are visible despite 
```
options: {
          bottomTabs: {
            visible: false,
            animate: false,
            drawBehind: true
          }
        },
```

---
### Environment
* React Native Navigation version:  2.0.2509
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): emu

**Comment by ouabing** [comment]
same issue

**Comment by dao-wkm** [comment]
On iOS, BottomTab visibility can be changed only when pushing screens.
https://wix.github.io/react-native-navigation/v2/#/docs/options-migration?id=tabbarhidden

Try this hack: #3951

**Comment by alpamys-qanybet** [comment]
not stale, same issue.
