### ISSUE TITLE
High crash rate on Android -  ModalPresenter.showModal

### ISSUE THREAD

**Issue by bruchim** [wix/react-native-navigation#3884]
### Issue Description

reactnativenavigation.viewcontrollers.modal.ModalPresenter.showModal

See the crash log:
https://rpm.newrelic.com/accounts/23428/mobile/174395388/crash_analysis/5536b50f4e5ea4ce2291f1f8e47dce54-23428-174395388/details?filters%5B0%5D=crashLocation%3A%3AModalPresenter.java%20line%2037%20in%20com.reactnativenavigation.viewcontrollers.modal.ModalPresenter.showModal
---

### Environment
* React Native Navigation version: 2.0.2505
* Platform(s) (iOS, Android, or both?): Android

**Comment by guyca** [comment]
Resolved in 2.0.2511

We should support showing modals regardless if root was set or not, this will be handled in #3885
