### ISSUE TITLE
New Crash Android - BottomTabsOptionsPresenter.applyDrawBehind()

### ISSUE THREAD

**Issue by bruchim** [wix/react-native-navigation#3887]
BottomTabsOptionsPresenter.java line 103 in com.reactnativenavigation.presentation.BottomTabsOptionsPresenter.applyDrawBehind() - 11 Occurrences/11 Users - 
https://rpm.newrelic.com/accounts/23428/mobile/25622085/crash_analysis/63b161e13a33732b3d65743a0eeea5ab-23428-174395388/details?tw%5Bstart%5D=1535353161&tw%5Bend%5D=1535612361&timeType=ending-now

**Comment by guyca** [comment]
Resolved in 2.0.2512
