### ISSUE TITLE
New crash Android - BottomTabs.setTabTestId()

### ISSUE THREAD

**Issue by bruchim** [wix/react-native-navigation#3888]
BottomTabs.java line 25 in com.reactnativenavigation.views.BottomTabs.setTabTestId() - 14 Occurrences/14 Users
https://rpm.newrelic.com/accounts/23428/mobile/25622085/crash_analysis/108dbc80a8a72ed5012ab0e0b802e6f7-23428-174395388/details?tw%5Bstart%5D=1535353161&tw%5Bend%5D=1535612361&timeType=ending-now

**Comment by guyca** [comment]
Resolved in 2.0.2511
