### ISSUE TITLE
Native Vector Icons broken in iOS 10

### ISSUE THREAD

**Issue by pzhine** [wix/react-native-navigation#389]
### Issue Description

React Native Vector Icons no longer work in navigator components using getImageSource in iOS 10.

I followed #43 to load my icons. Everything worked great until I upgraded to XCode 8, which I had to do because I upgraded my device to iOS 10. The icons no longer show in either the simulator or device in the navigator components, BUT they show up fine using the <Icon /> jsx tag.

---
### Environment
* React Native Navigation version: 1.0.7
* React Native Vector Icons version: 2.0.3
* React Native version: 0.34.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 10

**Comment by mikehuebner** [comment]
Can you show some code? Might be able to help with this one, I just fought with this for an hour.

**Comment by pzhine** [comment]
Turns out iOS 10 is not the problem. I just hadn't tested the app in the device or simulator without the remote JS debugger attached. The icons work fine in the navigator components when the remote JS debugger is attached, but when I detach the debugger (Cmd-D, Stop Remote Debugging) I get a red screen with the error "JSON value '<null>' of type NSNull cannot be converted to an image. Did you forget to call resolveAssetSource() on the JS side." When I reload, the app runs but the icons are missing in the navigator components.

So my guess is that it's a race condition with loading converting the vector icons to PNGs. With the debugger attached, the loading is slowed enough that the images have time to generate.

Here's my code for loading the icons, in the redux action creator:
```javascript
async function loadIcons(iconMap) {
  const sources = await Promise.all(
    Object.keys(iconMap).map(async iconName =>
      await Ionicons.getImageSource(
        iconName.replace('--active', ''),
        iconMap[iconName][0],
        iconMap[iconName][1]
      ))
  );

  return Object.keys(iconMap).reduce((icons, iconName, idx) =>
    icons.set(iconName, sources[idx]),
    new Map()
  ).toJS();
}
export function initializeApp({ icons }) {
  return async () => {
    const iconSources = await loadIcons(icons);
    const settings = await AsyncStorage.getItem('ttapp:settings');

    return {
      type: APP_READY,
      payload: {
        icons: iconSources,
        root: 'login',
        settings: settings ? fromJS(JSON.parse(settings)) : new Map()
      }
    };
  };
}
```

And here's the code that starts my app:
```javascript
constructor() {
    // since react-redux only works on components, we need to subscribe this class manually
    store.subscribe(this.onStoreUpdate.bind(this));
    store.dispatch(appActions.initializeApp({ icons }));
  }

  onStoreUpdate() {
    const { root, ready } = store.getState().app;
    if (this.currentRoot !== root) {
      this.currentRoot = root;
      if (ready) {
        this.startApp();
      }
    }
  }

  startApp() {
    const appState = store.getState().app;
    // this will start our app
    Navigation.startTabBasedApp({
      tabs: [
        {
          label: 'Outgoing',
          screen: 'ttapp.OutgoingList',
          title: 'Outgoing',
          icon: appState.icons.get('ios-sync')
        },
        {
          label: 'Messages',
          screen: 'ttapp.MessageGroupList',
          title: 'Messages',
          icon: appState.icons.get('ios-mail-outline')
        },
        {
          label: 'Settings',
          screen: 'ttapp.SettingsPage',
          title: 'Settings',
          icon: appState.icons.get('ios-settings-outline')
        },
      ]
    });
  }
```

**Comment by pzhine** [comment]
Ok, got it working. I was mixing Immutable Maps with plain JS objects.
I changed:
```javascript
return Object.keys(iconMap).reduce((icons, iconName, idx) =>
  icons.set(iconName, sources[idx]),
  new Map()
).toJS();
```
To this:
```javascript
return Object.keys(iconMap).reduce((icons, iconName, idx) =>
  icons.set(iconName, sources[idx]),
  new Map()
)
```
This doesn't explain why it worked with the debugger attached, but it works.

**Comment by smooJitter** [comment]
I know this is closed, but @pzhine  brings up an issue I'm encountering however instead of loading the images in the redux state im following the recommendation of the AppIcon iconMaps I large load solution.  My images are loading before he app begins but I'm still getting cannot convert to an image error.
