### ISSUE TITLE
[V2] Custom Status Bar Color is not allowed when background.component is set

### ISSUE THREAD

**Issue by srogers202** [wix/react-native-navigation#3890]
### Issue Description

When a background->component is given, the status bar reverts to white on iOS. If I remove the component from the background, the statusBar colors goes back to the background->color we set in default options.

### Steps to Reproduce / Code Snippets / Screenshots

1. Add a component to background in the options.

```
static get options() {
...
background: {
  color: backgroundColor,
  component: {
    name: 'SOME_COMPONENT',
  },
},
...
}
```
2. The status bar color goes back to white, instead of our backgroundColor.

---
### Environment
* React Native Navigation version: 2.0.2478
* React Native version: 0.55.4
* Platform(s): iOS
* Device info: Sim, Device, Debug

**Comment by srogers202** [comment]
Looks like this still happening. It works fine on sims, but on devices the status bar is still reverting to white (instead of our custom header background color).

**Comment by TPMinan** [comment]
+1 what is the solution

**Comment by TPMinan** [comment]
Not Working. Status bar color has not changed

```
topBar: {
    background: {
        color: Colors.Primary,

        component: {
            name: 'car.TopBar',
            clipToBounds: true
        }
    }
}
