### ISSUE TITLE
[V2] Overlay closes and opens keyboard on iOS

### ISSUE THREAD

**Issue by pribeh** [wix/react-native-navigation#3892]
On iOS, calling an overlay while the keyboard is open closes the keyboard. After dismissing the overlay, the keyboard opens again. Is there a reason why this is? Or can this be considered a bug?

## STEPS ##

- Navigation.push screen with textinput
- Focus textinput to load keyboard
- Navigation.showOverlay component (in our case a notification type component with smallish size)

## RESULT ##

As soon as the overlay loads, the keyboard and textinput collapse. When the overlay is dismissed, the keyboard and textinput expand again. 

We're using overlays for in-app notifications so this is quite bothersome for the end user in this instance. 

---
### Environment
* React Native Navigation version: ^2.0.2513
* React Native version: 0.55
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 10/11

**Comment by pribeh** [comment]
Is anybody else experiencing this?

**Comment by nikolas7892** [comment]
+1

**Comment by trqson** [comment]
+1

**Comment by tomhicks** [comment]
@pribeh or anyone else can you confirm this is fixed? I'm still getting this issue on iOS, version 2.12.0.

**Comment by FRizzonelli** [comment]
@tomhicks @guyca I think the fix is in this line of the commit

`- [overlayWindow makeKeyAndVisible];`
`+ [overlayWindow setHidden:NO];`

The problem is that isn't included in master or in 2.12.0. Maybe something went wrong with merge/other commits?

**Comment by pribeh** [comment]
@tomhicks yeah, it doesn't seem to be fixed and @FRizzonelli is correct that the fix looks to be missing.

**Comment by FRizzonelli** [comment]
#4778 PR from @tomhicks, @guyca can you approve and merge it?

**Comment by pribeh** [comment]
Looks like [overlayWindow makeKeyAndVisible] was added to make sure OS dialogs appear overtop overlays. The side effect is that keyboards or keyboard related textinputs are hidden when overlays are displayed. Anybody have any ideas on a way around this?

**Comment by marf** [comment]
Same problem here

**Comment by geroale** [comment]
Same :(

**Comment by pribeh** [comment]
This issue is now resolved as of https://github.com/wix/react-native-navigation/commit/e9ca247a524e474daf3ccf56989289ce679fc063 by @yogevbd

The solution now is described [here](https://github.com/wix/react-native-navigation/issues/4860#issuecomment-484505392) by @yogevbd 

```
options: {
  overlay: {
    handleKeyboardEvents: true
  }
}
```

**Comment by pribeh** [comment]
The solution @yogevbd came up with works fine with:

- Textinput and keyboard
- KeyboardAccessoryView with textinput inside (wix)

Oddly though, it doesn't work with:

- InputAccessoryView with text input inside (RN)

If you put your text input inside InputAccessoryView it just doesn't show up at all – not even behind the overlay. I'll run some more tests to confirm there isn't anything particular about the setup I'm running.
