### ISSUE TITLE
Start white screen

### ISSUE THREAD

**Issue by knowledges** [wix/react-native-navigation#3896]
Code Startup success，but android （Commd + M）  invalid；
I think it's a `MainApplication.java` problem, but I don't know where it is.
```
package com.selfrnapp;

import android.support.annotation.Nullable;

import com.facebook.react.ReactPackage;
import com.reactnativenavigation.NavigationApplication;

import java.util.List;

public class MainApplication extends NavigationApplication {
    @Override
    public boolean isDebug() {
        return BuildConfig.DEBUG;
    }

    @Nullable
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return null;
    }

    @Nullable
    @Override
    public String getJSMainModuleName() {
        return "index";
    }
}
```
`package.json`
```
{
  "name": "SelfRNApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.2.0",
    "react-native": "0.52.3",
    "react-native-navigation": "^1.1.484"
  },
  "devDependencies": {
    "babel-jest": "23.4.2",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.5.0",
    "react-test-renderer": "16.2.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

<img width="961" alt="wx20180831-232736 2x" src="https://user-images.githubusercontent.com/8423645/44921626-b1417200-ad08-11e8-9e9b-79cee193cced.png">

**Comment by perrosnk** [comment]
Could be related to [this](https://github.com/wix/react-native-navigation/issues/2180)

Try the steps mentioned there, and probably switch off Remote debug and Hot reload

**Comment by spiraltrip** [comment]
Make sure you do not use `AppRegistry.registercomponent('appName', () => App);`

Just `import App from './src/App'; ` and then in App.js, register the components and then use 
```
Navigation.events().registerAppLaunchedListener(() => {
		Navigation.setRoot(yourStackTree);
});
```

**Comment by spiraltrip** [comment]
@perrosnk It applies to RNN2 because of **registerAppLaunchedListener()**. It needs to handle the native app launch event which must precede before React-Native's AppRegister.registerComponent() method. Well at least that's the experience and assumption I have.

**Comment by knowledges** [comment]
There is no solution yet.

**Comment by knowledges** [comment]
我已经降级到0.47.1 办吧了
I have been downgraded to 0.47.1. 
run success

**Comment by knowledges** [comment]
I'm trying to try.
