### ISSUE TITLE
Custom Navbar

### ISSUE THREAD

**Issue by InYourDreamz** [wix/react-native-navigation#390]
### Issue Description

Is there a way to implement the NavBars like this? 

![customnavbar](https://cloud.githubusercontent.com/assets/11990210/19592431/4ed3a88e-97ae-11e6-9667-b422b178aa68.png)

We're currently hiding the NavBar and implementing it in React Native but it causes white flash during screen push.

**Comment by mastermoo** [comment]
no, that's not possible unfortunately :(

**Comment by agumack** [comment]
navBarHidden: true and style view : )

**Comment by savelichalex** [comment]
But main question is: How I can know height of native nav bar?

**Comment by agumack** [comment]
64px @savelichalex

**Comment by savelichalex** [comment]
Hm, are you sure that they always be 64*pt*?

**Comment by guyca** [comment]
@savelichalex The navBar height is be consistent across devices, even on Android. According to the material [design guide lines](https://material.google.com/layout/metrics-keylines.html#metrics-keylines-keylines-spacing) it's 56 dp. I think  the size changes on Tablets, not sure.
On iOS it also seems to be pretty consistent, found [this partial list](http://ivomynttinen.com/blog/the-ios-7-design-cheat-sheet) on [google](https://www.google.co.il/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=ios%20navigation%20bar%20height) but I'm not too familiar with native iOS so can't say for sure. cc @gran33 @artald

I would like to add support for custom react views in the TopBar. After v2.0 will finally be behind us we'll have more time to experiment with that.

**Comment by artald** [comment]
What @guyca said regarding the height of the nav-bar on iOS is correct, the height is consistent.
The bar itself is 44px. When shown bellow the status bar (the most common use-case), the vertical offset for your screen start is 64px (the status bar height is 20px).

Again, as @guyca said, we hope to add the ability to have custom views in the top bar when v2.0 is done; so hard-coded values and other hacks won't be necessary.

**Comment by guyca** [comment]
Thanks @artald

**Comment by savelichalex** [comment]
Ok, waiting 2.0! Thanks guys @guyca @artald

**Comment by InYourDreamz** [comment]
Oh good to know that this is in plan, in the meantime I think we'll dabble a little with the native code to enable this.

**Comment by SudoPlz** [comment]
For people coming here wondering why the nav bar height is weird on landscape, keep in mind that the nav bar in Landscape is 32 points on iOS (instead of 44 points that it is in portrait).
With the status bar +20 points that would be 52 points in landscape, and 64 in portrait.

**Comment by braco** [comment]
@InYourDreamz how did you end up implementing this? I'm looking at dropping a NavBar into every component, but that's a little nutty

**Comment by braco** [comment]
@artald is this coming to 2.0?

**Comment by SudoPlz** [comment]
@braco I have implemented a Custom Nav bar in 1.* by using the `navBarCustomView` (Check the [docs](https://wix.github.io/react-native-navigation/#/styling-the-navigator?id=style-object-format))

**Comment by braco** [comment]
@SudoPlz thank you! Will check this out.

[Looks like this is just recently being added for Android?](https://github.com/wix/react-native-navigation/commit/e581b2dec6eee9d7e5bdc4eab165e6e13b259496)

**Comment by sowdri** [comment]
@SudoPlz I was assuming that the customNavBar attribute will only replace the title element of the navBar as opposed to the complete navBar. Did you manage to replace the entire nav bar with your custom react-native component?

Thanks,

**Comment by SudoPlz** [comment]
Yes I replace the whole nav bar.
