### ISSUE TITLE
[v2] [Android] AppLayout defaults to white on launch

### ISSUE THREAD

**Issue by birkir** [wix/react-native-navigation#3905]
### Issue Description

![androidlaunchbug](https://user-images.githubusercontent.com/180773/44968644-08b52d00-af17-11e8-9781-dff85e747def.gif)

RAW Video: https://streamable.com/jina7

The video explains the bug very well. On Android, when launching the app, I show my splash screen with `setContentView` in the Activity. Then when `Navigation.setRoot`is executed, the launch screen is replaced with an white screen and gray NavBar (defaults?). 

Few moments later, the expected screen options were applied and the app rendered.

I tried different configurations:
 - Very bad effect when using `sidemenu` or pure `root.component`.
 - It appears for shortest amount of time when using `bottomTabs`.
 - It appears for shorter amount of time on better device.
 - Settings default options did not work.

### Steps to Reproduce / Code Snippets / Screenshots

Repro on current master: https://github.com/birkir/kvikmyndr-app

```js
Navigation.setRoot({
  component: {
    name: WEEK,
  },
});
```

---
### Environment
* React Native Navigation version: 2.0.2515
* React Native version: 0.56.rc-3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by LRNZ09** [comment]
The issue is caused by `addDefaultSplashLayout` on `NavigationActivity` setting by default a white view.

"Resolved" by overriding `onCreate` like this:
```java
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        View view = new View(this);
        view.setBackgroundColor(Color.TRANSPARENT);
        setContentView(view);
    }
```

The `addDefaultSplashLayout` should be overridable.

**Comment by esipavicius** [comment]
> @Override protected void onCreate(@Nullable Bundle savedInstanceState) { super.onCreate(savedInstanceState); View view = new View(this); view.setBackgroundColor(Color.TRANSPARENT); setContentView(view); }

OR: view.setBackgroundResource(R.drawable.splash_screen);

**Comment by nezaidu** [comment]
@edvinasbartkus <3 <3 <3
