### ISSUE TITLE
[V2] issues with custom top bar button (Left or Right)

### ISSUE THREAD

**Issue by hisothreed** [wix/react-native-navigation#3907]
### Issue Description

when using a component in the left or right buttons in topBar it is not taking the required width ( when putting text and image only the image is visible) and when pressing on it, it is not triggering the onPress of the touchableOpacity in it nor onNavigationButtonPressed()

**having this issue with the newer versions of the navigation (2.0.2500++)**

### Steps to Reproduce / Code Snippets / Screenshots

<img width="175" alt="screen shot 2018-09-03 at 12 39 27 pm" src="https://user-images.githubusercontent.com/9201625/44976498-6b89e100-af76-11e8-8c0f-2b88470c867f.png">
<img width="145" alt="screen shot 2018-09-03 at 12 39 18 pm" src="https://user-images.githubusercontent.com/9201625/44976499-6b89e100-af76-11e8-972f-cc05f919d060.png">

```
class ChatHelpButton extends React.Component<Props, State> {
  state = {
    tintColor: this.props.color
  }
  render() {
    return (
      <TouchableOpacity
        style={{
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "center"
        }}
        onPress={this.props.onPress}
      >
        <View style={{ flexDirection: "row", flex: 1 }}>
          <Image
            style={{
              maxWidth: 23,
              maxHeight: 23,
              marginRight: 5,
              tintColor: this.state.tintColor,
              resizeMode: "contain"
            }}
            source={this.props.image}
          />
          <Text
            style={{
              fontWeight: "700",
              color: this.state.tintColor,
              fontSize: scale(12)
            }}
          >
            {this.props.text}
          </Text>
        </View>
      </TouchableOpacity>
    )
  }
}
```
---
### Environment
* React Native Navigation version: 2.0.2500+
* React Native version: 54.6
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by hisothreed** [comment]
Downgrading to v2.0.2500 will make it work

**Comment by iksent** [comment]
I confirm that problems.

And also if set `rightButtons` to `null`, all screens will be frozen (I have a stack with bottomTabs).
Checked it only on iOS.
I think that array of left/right-Buttons should be validated.

```
bottomTabs: {
	children: navigationSettings.bottomTabs.map(t => ({
		stack: {
			children: [
				{
					component: {
						name: t.name,
						options: {
							// ...
							topBar: {
								visible: true,
								title: {
									text: t.title,
								},
								rightButtons: null,
							},
						}
					}
				}
			],
		}
	})),
}
```
