### ISSUE TITLE
[V2][iOS] iOS builds fail with xcodebuild

### ISSUE THREAD

**Issue by Jazqa** [wix/react-native-navigation#3908]
### Issue Description

#3774 breaks clean iOS builds with xcodebuild

### Steps to Reproduce / Code Snippets / Screenshots

1. Clean the build output (e.g. ~/Library/Developer/Xcode/DerivedData)
2. Build the project with xcodebuild

---
### Environment
* React Native Navigation version: 2.0.2507
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Xcode 9.4.1

**Comment by guyca** [comment]
Hey @Jazqa 
#3774 was reverted, thanks for reporting 👍
