### ISSUE TITLE
Use with onesignal pushnotification

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#391]
### Issue Description

Hi, I am using onesignal push. and have one problem when call API Screen

``` js
import { Navigation } from 'react-native-navigation';
import OneSignal from 'react-native-onesignal';

export function notificationConfig() {
    OneSignal.configure({
        onIdsAvailable: function (device) {
            console.log('UserId = ', device.userId);
            console.log('PushToken = ', device.pushToken);
        },
        onNotificationOpened: function (message, data, isActive) {
            var notification = { message: message, data: data, isActive: isActive };
            if (isActive) {
                Navigation.showInAppNotification({
                    screen: "app.NotificationInAppScreen",
                    passProps: { notification: notification }
                });
            } else {
                Navigation.handleDeepLink({
                    link: "refeshnotifications/"
                })
            }
        }
    });
}
```

Navigation.showInAppNotification: working fine!
Error when Navigation.handleDeepLink (push too) called:

> 2016-10-21 17:08:34.080 [error][tid:com.facebook.react.JavaScript] undefined is not a function (evaluating '_reactNativeNavigation.Navigation.handleDeepLink({
> link:"refeshnotifications/"})')
> 2016-10-21 17:08:34.101 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: undefined is not a function (evaluating '_reactNativeNavigation.Navigation.handleDeepLink({
> link:"refeshnotifications/"})')

How call it? thanks so much!
### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
- React Native Navigation version: FILL THIS OUT
- React Native version: FILL THIS OUT
- Platform(s) (iOS, Android, or both?): FILL THIS OUT
- Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
@agumack `handleDeepLink` is a function in `Navigator`, the one your get from props (`this.props.navigator`). To overcome this, you can dispatch an action which will be handled by your main screen and send the deep link from there. This is a shortcoming of the current api which I hope we'll address soon.

**Comment by vyky** [comment]
@agumack mind sharing your code for RNN and OneSignal integration?
