### ISSUE TITLE
[V2] Problems with push+dismissModal and showModal+pop

### ISSUE THREAD

**Issue by iksent** [wix/react-native-navigation#3914]
### Issue Description

If you do a `pop` for a modal screen or `dismissModal` for a pushed-screen, then problems start.

### Steps to Reproduce / Code Snippets / Screenshots

1. `push` new screen. Then call `dismissModal`. Result:

My screens|Crash|Crash (Drawer opened)
:-------------------------:|:-------------------------:|:-------------------------:
![img_0017](https://user-images.githubusercontent.com/32956521/45018515-bcb3d680-b043-11e8-95b2-cb98a3532063.PNG) | ![img_0018](https://user-images.githubusercontent.com/32956521/45018292-2c759180-b043-11e8-933b-da4bd70b97ac.PNG)  |  ![img_0019](https://user-images.githubusercontent.com/32956521/45018298-313a4580-b043-11e8-9b0b-384b34faf4c9.PNG)

2. `showModal` new screen. Then call `pop`.  Then call `dismissModal`. Result: nothing happens!

---
### Environment
* Checked with 3 versions of RNNv2: `2.0.2459`, `2.0.2500`, `2.0.2519`
* React Native version: `0.55.4`
* Platform(s) (iOS, Android, or both?): `iOS` only
* Device info (Simulator/Device? OS version? Debug/Release?): `Debug`

---
### My stack

```
Navigation.setRoot({
        root: {
            sideMenu: {
                left: {
                    component: {
                        id: SCREENS_NAMES.leftDrawer,
                        name: SCREENS_NAMES.leftDrawer
                    }
                },
                center: {
                    bottomTabs: {
                        children: navigationSettings.bottomTabs.map(t => ({
                            stack: {
                                children: [
                                    {
                                        component: {
                                            name: t.name,
                                            passProps: {
                                                ...(t.passProps || {})
                                            },
                                            options: {
                                                bottomTab: {
                                                    icon: getIconSource(t.icon),
                                                },
                                                topBar: {
                                                    visible: true,
                                                    title: {
                                                        text: t.title,
                                                    },
                                                },
                                            }
                                        }
                                    }
                                ],
                            }
                        })),
                    }
                }
            }

        }
    }).then(() => console.warn("App launched with RNN v2 =))"));
```

Where `navigationSettings.bottomTabs` is:

```
[
            {
                name: SCREENS_NAMES.testHome,
                title: 'Главная',
                icon: INITIALIZED_ICONS_NAMES.home,
                // ...
            },
            {
                name: SCREENS_NAMES.test,
                title: 'Test',
                icon: INITIALIZED_ICONS_NAMES.test,
                // ...
            },
        ]
```

**Comment by guyca** [comment]
Hey @iksent 
Thanks for the detailed report. I'm wondering if `await`ing the initial command resolves these issues.

**Comment by guyca** [comment]
Wait for the push command to complete
```js
await Navigation.push(...);
Navigation.dismissModal();
```

**Comment by guyca** [comment]
@iksent 
What exactly do you mean by "pop for a modal screen or dismissModal for a pushed-screen"?
Modals can't be popped, they can be dismissed and pushed screens are popped.

**Comment by guyca** [comment]
@yogevbd Lets talk about this issue, we should add e2e for these use cases as well.

**Comment by RajenderDandyal** [comment]
setting ...rightButtons: [{color: "#D84315", fontSize: 25}], inside setDefault-->topBar was crashing my app 
... everything back to normal after removing this property and adding color from static option
