### ISSUE TITLE
Right button misaligned and not pressable on iOS

### ISSUE THREAD

**Issue by yedidyak** [wix/react-native-navigation#3915]
Right buttons that are components are not centered on iOS, and tapping them does not work.

This bug started between versions 2.0.2507 and 2.0.2513.

**Comment by guyca** [comment]
Can you check if disabling yellow box in Js resolved this?

**Comment by robobakery** [comment]
Same issue here. it renders like this.

![screen shot 2018-09-04 at 6 09 01 pm](https://user-images.githubusercontent.com/9474523/45021871-acb0ec80-b06d-11e8-8a4b-fbd15f2894bd.png)

**Comment by yogevbd** [comment]
Pushing a fix asap

**Comment by yogevbd** [comment]
Fixed #3918
