### ISSUE TITLE
[v2]SideMenu Bug Report(width option problem)

### ISSUE THREAD

**Issue by spikeisryu** [wix/react-native-navigation#3924]
### Issue Description

I think there is a bug related to sidemenu width property.
If there is a width configuration at sidemenu option, then it does not hide the sidemenu properly.

### Steps to Reproduce / Code Snippets / Screenshots
When I set a specific width at sidemenu option like this,

    sideMenu: {
        left: {
            width: 200,
            visible: false,
        },
    },

and try to hide the side menu like this,

        Navigation.mergeOptions(this.props.componentId, {
            sideMenu: {
                left: {
                    visible: false
                }
            }
        });

The screen shows like this.
![simulator screen shot - iphone x - 2018-09-05 at 16 42 23](https://user-images.githubusercontent.com/23102875/45078314-b0567900-b12a-11e8-83c5-63e2e08d1309.png)

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 2.0.2526
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/iPhoneX Debug mode

**Comment by cvongrim** [comment]
I am running into the exact same issue.

- React Native Navigation version: 2.0.2538
- React Native version: 0.56.0
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator/iPhone 6 11.4

**Comment by shaliko** [comment]
I have the same issue:

React Native Navigation version: 2.0.2538
React Native version: 0.56.0
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): Simulator/iPhone 6 11.4

**Comment by cesarm16** [comment]
there is a solution for this?

**Comment by SudoPlz** [comment]
I'm experiencing the same issue, setting a width does not affect anything.

**Comment by chelovekdrakon** [comment]
@spikeisryu @cvongrim @shaliko @SudoPlz @cesarm16

Hi guys!
Just stuck with the same issue.
Anybody found what a trigger for this? :)

P.S. What is interesting... I got it after update from v2.8.0 -> to v2.14.0.
It worked fine before...

**Comment by byonghun** [comment]
@chelovekdrakon I am running into the same issue with v.2.14.0-snapshot.246 but only when I push a component after toggling the drawer. If I just toggle without pushing a component after, it works fine.

Has anyone found a solution to this problem?

**Comment by chelovekdrakon** [comment]
@byonghun I still didn't find a solution. Just rolled back to v2.8.0
If you will find one, please let us know :)

**Comment by SudoPlz** [comment]
@guyca any ideas?

**Comment by byonghun** [comment]
@chelovekdrakon will do. If I can't figure it out, I'll probably use `v2.8.0` as well. Hopefully, @guyca can help us out!

**Comment by flikQ** [comment]
Anyone found a solution to this? I find it mind boggling that they haven't fixed this 9 months after the OP. Has V2 been discontinued?

**Comment by acollazomayer** [comment]
Is this fixed? why does this happen

**Comment by flikQ** [comment]
@guyca is this error going to remain? it's only been 9+ months.

**Comment by AKACC** [comment]
@spikeisryu @cvongrim @shaliko @SudoPlz @cesarm16 @chelovekdrakon

I might solve the problem in my case:
instead of using `mergeoptions`, write options in  `Navigation.push()` method. This is my example:
```
 Navigation.push('AppStack', {
        component: {
          name: 'Login',
          passProps: {
            text: 'Pushed screen'
          },
          options: {
            sideMenu: {
                left: {
                    visible: false
                  }
            }
          }
        },
   });
```

it works fine to me, helps it helps.

**Comment by chelovekdrakon** [comment]
@AKACC But what if I don't need to push. Just to show/hide sideMenu)

**Comment by yogevbd** [comment]
Can someone reproduce this in the playground app and push it to a branch? I can't reproduce

**Comment by AKACC** [comment]
@chelovekdrakon the problem just happened to me when i tried to push to other screen. showing/hiding sidemenu work perfect with mergeoptions alone.

**Comment by dorthwein** [comment]
Removing the width resolved this in my particular case where I only set the menu on the root tab.  Merge options then worked fine on latest version of RRN

**Comment by chelovekdrakon** [comment]
Issue is still not solved. 
I keep v2.8.0, because if I upgrade to the latest one --> my sideBar is black.
I can not use it
