### ISSUE TITLE
[V2] Android app crash after showOverlay

### ISSUE THREAD

**Issue by iksent** [wix/react-native-navigation#3928]
### Issue Description

Attempt to call `showOverlay` makes crash of the application

### Steps to Reproduce / Code Snippets / Screenshots

![photo_2018-09-05_16-04-06](https://user-images.githubusercontent.com/32956521/45089353-543d2600-b125-11e8-8b6b-ff68a472f144.jpg)

Overlay component TextInAppNotification render:

```
    render() {
        return (
            <View style={{flex: 1, height: 30, width: 100, backgroundColor: '#fff'}}>
                <AppText>{123}</AppText>
            </View>
        );
    }
```

```
    Navigation.showOverlay({
        component: {
            name: 'TextInAppNotification',
            options: {
                layout: {
                    backgroundColor: 'transparent',
                },
                overlay: {
                    interceptTouchOutside: true
                }
            }
        }
    });
```
---
### Environment
* React Native Navigation version: 2.0.2500
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by animatereactnative** [comment]
still reproduce
