### ISSUE TITLE
iOS & Android navigator.push from side menu behaviour differs

### ISSUE THREAD

**Issue by glesage** [wix/react-native-navigation#393]
### Issue Description

Having troubles pushing screens using `navigator.push({})` when tapping on an item from a slide menu on iOS (similar to the example menu: https://github.com/wix/react-native-navigation/blob/master/example/src/screens/SideMenu.js

When tapping, no screen is pushed. However, doing `navigator.push` from the main page pushes/shows the screens perfectly. Android works perfectly, but not iOS.

### Steps to Reproduce - Using Example app

![Alt Text](https://dl.dropboxusercontent.com/u/30415492/push_issue.gif)

---
### Environment
https://github.com/wix/react-native-navigation/blob/master/example/package.json
* React Native Navigation version: v2.0.0-experimental.100
* React Native version: 0.31.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 10 iPhone 6 simulator

**Comment by guyca** [comment]
@glesage If you call `navigator.push` from your `SideMenu` screen, the app will try to push into the Drawer component but that's not possible. You'll need to use [deep-links](https://github.com/wix/react-native-navigation/wiki/Deep-links) and handle the deep link in the screen you want to push from (Your main page)

1. [post deep link](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/SideMenu.js#L35)
2. [handle deep link](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/SecondTabScreen.js#L107)

**Comment by glesage** [comment]
it's too bad it works differently than Android yea...

Thanks!

**Comment by guyca** [comment]
What do you mean? If there's no parity between iOS and Android then we should definitely reopen and fix that.

**Comment by glesage** [comment]
Let me double check

**Comment by glesage** [comment]
Unfortunately yes it actually seems to work differently on Android. This works on Android when called from the side menu:
```
this.props.navigator.push({
            screen: route
        });
```
But it does not on iOS

**Comment by guyca** [comment]
So calling `navigator.push` from SideMenu will push a screen into the current bottom tab?

**Comment by glesage** [comment]
Yes it seems that way. How might I check that the bottom tab is the one that is getting the new screen? (other than the fact that it is showing)

**Comment by guyca** [comment]
@glesage I tried to push a screen from SideMenu as you did in the video you added (Thanks for that!) and I got a `ScreenStackNotFoundException`, as expected. On iOS nothing happened.
On both platforms you can't push to tabs using the SideMenu's navigator, that's the intended behaviour.
We have to improve the error reporting and exceptions we through to prevent confusion.

I see you're using a pretty old version, I think `ScreenStackNotFoundException` was added in a later version.

**Comment by glesage** [comment]
Ok that seems to be the case indeed, thanks for all the info!
