### ISSUE TITLE
[V1] Issue with Side Drawer

### ISSUE THREAD

**Issue by mdelclaro** [wix/react-native-navigation#3937]
### Issue Description

I am trying to click a button on the side drawer to Signout on my app and go back to the Login screen. I'm using Deep Link to handle this. I'm able to go to the Login screen, but after this I got this error message:
```
Invariant Violation: eventType argument is required

     This error is located at:
            in SharePlaceScreen (created by Connect(SharePlaceScreen))
            in Connect(SharePlaceScreen) (at Navigation.js:83)
            in Provider (at Navigation.js:82)
            in _class2 (at renderApplication.js:33)
            in RCTView (at View.js:60)
            in View (at AppContainer.js:102)
            in RCTView (at View.js:60)
            in View (at AppContainer.js:122)
            in AppContainer (at renderApplication.js:32) 
```
I have tried to search this error but I can't find anything...
---
### Environment
* React Native Navigation version: ^1.1.277
* React Native version: 0.55
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Physical Device. LG K4 5.1

**Comment by makeco** [comment]
I am currently experiencing the same issue.

**Comment by minhphung210** [comment]
same issue
