### ISSUE TITLE
You attempted to set the key `onPress` with the value...

### ISSUE THREAD

**Issue by WhatAKitty** [wix/react-native-navigation#394]
### Steps to Reproduce / Code Snippets / Screenshots
1. Before the component will mount, I set rightButtons;
2. Then I setOnNavigatorEvent to listen button event;
3. When I click the button what I add. The first time, it worked, but when I turned back and clicked it again. It broken.

![image](https://cloud.githubusercontent.com/assets/4178729/19624707/c3262a4e-9935-11e6-9673-76ee64c8dac2.png)
---
### Environment
- React Native Navigation version: 2.0.0-experimental.133
- React Native version: 0.35.0
- Platform(s) (iOS, Android, or both?): IOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator IOS 10.0 Debug

**Comment by WhatAKitty** [comment]
I run your example code right now. And I found the same issue.
![10 -23-2016 16-17-51](https://cloud.githubusercontent.com/assets/4178729/19624923/523e64c0-993c-11e6-9595-01c819fa8a28.gif)

**Comment by sexykodo** [comment]
Same problem here, after updating to RN 0.35

**Comment by JuneDomingo** [comment]
@sexykodo @WhatAKitty RN 0.35 is not yet fully supported, but this might help you #357

**Comment by WhatAKitty** [comment]
@JuneDomingo It seems worked on Android. How about IOS?

**Comment by beast** [comment]
@WhatAKitty I am the author for https://github.com/wix/react-native-navigation/pull/357. It only affects Android. It's not related here. However, I believe somewhere along the way React Native fixed the way they handle listview datasource (Making it immutable). I suggest you have a look at the accepted answer on http://stackoverflow.com/questions/38270445/you-attempted-to-set-the-key-on-an-object-that-is-meant-to-be-immutable-and-has

**Comment by beast** [comment]
@guyca I am reviewing the source code for this, to be honest I am a backend developer that just got into frontend and mobile world. So bear with me if I got it wrong. Error is thrown at 199 [platformSpecificDeprecated.ios.js](https://github.com/wix/react-native-navigation/blob/master/src/deprecated/platformSpecificDeprecated.ios.js)

```javascript
 const navigatorButtons = Object.assign({}, screenClass.navigatorButtons);

  if (navigatorButtons.rightButtons) {
    for (let i = 0; i < navigatorButtons.rightButtons.length; i++) {
      navigatorButtons.rightButtons[i].onPress = navigatorEventID;
    }
  }
```

I believe the navigatorButtons should be declared with "let" identifier instead of "const"? Thanks.

**Comment by WhatAKitty** [comment]
@beast thx, I'll try.

**Comment by sexykodo** [comment]
@beast ye, having a rightbutton as immutable, the second time the same screen is pushed it breaks. But declaring navigatorButtons or even screenClass as let doesn't seem to work.

**Comment by beast** [comment]
@sexykodo Do you get a new error when you try? Sorry I haven't been able to actually test this out myself. The error I saw earlier indicate it was an problem with immutable that is why I went with the guess.

**Comment by sexykodo** [comment]
@beast ye, i get the same problem. Debugging i found that on first push the navigatorButtons.rightButtons[0] object seems like a plain object
<img width="243" alt="screen shot 2016-10-24 at 10 31 19" src="https://cloud.githubusercontent.com/assets/7148528/19638657/331752d4-99d5-11e6-9eed-ebb837b9d2a4.png">

but on second push it looks like an immutable
<img width="236" alt="screen shot 2016-10-24 at 10 31 35" src="https://cloud.githubusercontent.com/assets/7148528/19638670/3d6cb6c0-99d5-11e6-9ef4-a73684ae0349.png">

**Comment by beast** [comment]
@sexykodo I just want to confirm with you that you did change your node_modules from const to let. Could it be because of the following? Maybe the screenClass also should be a let?

`const screenClass = Navigation.getRegisteredScreen(screenID);`

**Comment by sexykodo** [comment]
@beast i changed both screenClass and navigatorButtons declaration to let but i had the same error

**Comment by beast** [comment]
@sexykodo I am not a javascript expert but after reading about object.assign on MDN https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign.

Could it be that we actually need a deep clone instead of a reference? https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Deep_Clone

**Comment by WhatAKitty** [comment]
@sexykodo

```
let navigatorEventID = screenInstanceID + '_events';
  let navigatorButtons = { ...screenClass.navigatorButtons };
  if (params.navigatorButtons) {
    navigatorButtons = { ...params.navigatorButtons };
  }
```

Same error before.

**Comment by WhatAKitty** [comment]
@beast @sexykodo  The problem is solved.
as @beast said, use deep clone:
```
let navigatorEventID = screenInstanceID + '_events';
  let navigatorButtons = JSON.parse(JSON.stringify(screenClass.navigatorButtons));
  if (params.navigatorButtons) {
    navigatorButtons = JSON.parse(JSON.stringify(params.navigatorButtons));
  }
```

**Comment by beast** [comment]
@WhatAKitty Great work! However, is this related to RN0.35 at all? Sorry, I am the type of person that likes to get to the bottom of things :)

**Comment by guyca** [comment]
@beast git blame 😄

**Comment by chaitanya0bhagvan** [comment]
If I remember correctly this is happening only on rn 0.35. Try downgrading
0.34.1.

**Comment by indivisable** [comment]
@WhatAKitty fixed for me, I am still using RN 0.31 so not specific to 0.35

**Comment by WhatAKitty** [comment]
@beast not specific to 0.35

**Comment by beast** [comment]
@guyca @WhatAKitty  Thanks for the confirmation. I did check git blame that is why I didn't think it was related to version problem. It was probably there all along just no one ever notice :)

**Comment by lkj01010** [comment]
I update RN from 0.31 to 0.35, then this error appears.

**Comment by kanzitdinov** [comment]
@guyca @beast @WhatAKitty Hey guys. The same is happening to me on Android. I've fixed this issue on iOS as described before. I tried to fix it but unsuccessfully.
![screenshot_20161029-182450](https://cloud.githubusercontent.com/assets/4402166/19833138/98d44530-9e05-11e6-97e8-2dbbc9dd9672.png)
![github_question](https://cloud.githubusercontent.com/assets/4402166/19833140/a208f826-9e05-11e6-858b-ea0bf2d57e8f.png)

**Comment by guyca** [comment]
@kanzitdinov What's the use case that leads to the error?

**Comment by beast** [comment]
How did you declare your right buttons? Thanks.

**Comment by kanzitdinov** [comment]
@guyca @beast yes, I'm trying to declare one right nav button but I need to change them Edit <-> Done.

I use this code to set right button at the begining ```this.props.navigator.setButtons(NavigatorButtons.Profile.Edit);```

This is how I change right buttons:
```
_onNavigatorEvent(event) {
    if (event.type == 'NavBarButtonPress') {
      if (event.id == 'editButtonId') {
        this.setState({editing: true});
        this.props.navigator.setButtons(NavigatorButtons.Profile.Done);
      }
      if (event.id == 'doneButtonId') {
        this.setState({editing: false});
        this.props.navigator.setButtons(NavigatorButtons.Profile.Edit);
      }
    }
}
```

And this is how they are declared: 
```
Profile: {
    Edit: {
      rightButtons: [{
        title: 'Edit',
        id: 'editButtonId',
        fontSize: Sizes.Font[14],
        fontFamily: Fonts.Avenir_Medium,
      }],
      animated: true,
    },
    Done: {
      rightButtons: [{
        title: 'Done',
        id: 'doneButtonId',
        fontSize: Sizes.Font[14],
        fontFamily: Fonts.Avenir_Medium,
      }],
      animated: true,
    }
  }
```

Everything works fine on iOS because I changed code as described before but on Android I get an error.

**Comment by beast** [comment]
I can't really see any problem by a glance. You might want to read how ES6 object literal works. In the iOS case, the parent object need to be deep cloned instead of simply assigning new properties. The error is quite clear that some sort of immutable is happening on the rightbuttons object that it didn't like.

**Comment by guyca** [comment]
@kanzitdinov Any chance you could fork RNN and modify the example project to repro the bug?

**Comment by kanzitdinov** [comment]
@guyca @beast Thank you for the help. I've fixed this problem. I just changed some code in ```platformSpecificDeprecated.android.js```.
```
function navigatorSetButtons(navigator, navigatorEventID, params) {

  const rightButtons = JSON.parse(JSON.stringify(params.rightButtons));
  if (rightButtons) {
    rightButtons.forEach(function(button) {
      button.enabled = !button.disabled;
      if (button.icon) {
        const icon = resolveAssetSource(button.icon);
        if (icon) {
          button.icon = icon.uri;
        }
      }
    });
  }

  ...

  newPlatformSpecific.setScreenTitleBarButtons(navigator.screenInstanceID, navigatorEventID, rightButtons, leftButton);
}
```

**Comment by beast** [comment]
Well done. I think you should send a pull request for this :)

**Comment by sexykodo** [comment]
@guyca @beast I encountered a similar problem in addNavigatorButtons wich i solved with

```
function addNavigatorButtons(screen, sideMenuParams) {
  const Screen = Navigation.getRegisteredScreen(screen.screen);
  Object.assign(screen, Screen.navigatorButtons);

  // Get image uri from image id
  let rightButtons = getRightButtons(screen)

  if (rightButtons) {
    rightButtons = JSON.parse(JSON.stringify(getRightButtons(screen)));
    rightButtons.forEach(function(button) {
      button.enabled = !button.disabled;
      if (button.icon) {
        const icon = resolveAssetSource(button.icon);
        if (icon) {
          button.icon = icon.uri;
        }
      }
    });
  }
```

Adding the deepclone or rightbuttons if defined.

**Comment by DanielZlotin** [comment]
So this was a tough one to crack..
Apparently react-native somewhere down the line decided it will be smart to deep freeze and throw on mutation **all** properties (and inherited properties) of react Components. recursively. 

You can find the function that actually does this [here](https://github.com/facebook/react-native/blob/master/Libraries/Utilities/deepFreezeAndThrowOnMutationInDev.js#L32).

And the fact all components get this wonderful behaviour [here](https://github.com/facebook/react-native/blob/3683beb88ab3233038ac32b9c33112d537478088/Libraries/Renderer/src/renderers/native/ReactNativeBaseComponent.js#L190).

Once objects are frozen in JS, there is no way to unfreeze them. So the only solution will be to deep clone and assign them to the screen instance. This was an unreasonable decision for them to make, but we have no choice but to play along. I prefer not to use `Object.assign` anyway..

In any case this will change as part of the redesign of the API, but it's good we caught this early on, before the actual rewrite, as it will impact some of the decisions.

The fix, along with an upgrade to RN0.36.1 will be published tomorrow.

**Comment by pedro** [comment]
@DanielZlotin can you share any details about the fix/where it eventually landed?

I'm running into this on `1.1.125`; tried deep cloning my params before sending to `navigator.push` but still nothing, so I believe they're being frozen and then changed inside rn navigator itself 🤔

**Comment by pedro** [comment]
Sweet, the patch from @maurovisitin above fixed 1.1x for me.

Tried updating briefly but got stuck trying to find the equivalent of `ActivityCallbacks` there. It seems like there was a wiki page on updating to 2 but couldn't find it so will give it another try later!

Thanks,

**Comment by guyca** [comment]
@pedro Could you please submit a PR with the fix?

**Comment by dbelchev** [comment]
@guyca @pedro This issue is still reproducible. I can confirm that @pedro's PR fixes the problem.

**Comment by stonecold123** [comment]
Got the same issue with passing mobx data or realm object to passProps in navigation:
https://github.com/wix/react-native-navigation/issues/1748
