### ISSUE TITLE
[V2] Can't set default options for topBar anymore

### ISSUE THREAD

**Issue by InternetExplorer8** [wix/react-native-navigation#3940]
### Issue Description

Since the last update, no default options can be passed for the TopBar. The default is always taken from the operating system. However, if the options are set individually for each TopBar, it works.

### Steps to Reproduce / Code Snippets / Screenshots

Does nothing since last update:

```javascript
Navigation.setDefaultOptions({
  topBar: {
    backButton: {
      showTitle: false
    },
    hideBackButtonTitle: true,
    buttonColor: "red"
  }
});
```

---
### Environment
* React Native Navigation version: "react-native-navigation": "^2.0.2538",
* React Native version: "react-native": "0.56.0",
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by yogevbd** [comment]
Pushed fix for `backButton.showTitle` .
You should use it like that:

```javascript
Navigation.setDefaultOptions({
  topBar: {
    backButton: {
      showTitle: false
    },
    rightButtonStyle: {
      color: 'red'
    },
    leftButtonStyle: {
      color: 'red'
    }
  }
});
```
