### ISSUE TITLE
[V2] Events: No way to listen to screen pop when performed via gesture or hitting back button

### ISSUE THREAD

**Issue by jordanfloyd** [wix/react-native-navigation#3941]
### Issue Description

When registering a command listener, the only events subscribed to are the ones explicitly called on Navigation class from my code. The implicit commands (gesture swipe back, system back button) don't get picked up by this listener so there is effectively no way to detect that they happened.

The componentDidAppear/didDisappear listeners could be used if there was context with the event (command that resulted in the screen being mounted/unmounted).

Ultimately what I'm trying to do is trigger some side effect on screen pop. I can override the back button with my own button and manually call the pop command, but that doesn't solve the gesture back case and it seems like this is a departure from the way that v1 handled this, which was to provide a handler for all events and then let the implementer filter out as needed.

### Steps to Reproduce / Code Snippets / Screenshots

    Navigation.events().registerCommandListener((name, params) => {
      // do something here
    }

---
### Environment
* React Native Navigation version: 2.0.2514
* React Native version: 0.55.1
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Emulator, iOS 11.4, Android 8.0, Debug

**Comment by ShaMan123** [comment]
+1

**Comment by vlkosinov** [comment]
Very important for me too

**Comment by TuTejsy** [comment]
I have the same problem. @guyca  Did you work on this?

**Comment by guyca** [comment]
Hey guys, we'll add the following event to support this use case:

```js
Navigation.events().registerScreenPoppedListener({ componentId } = {
});
```

The event will be emitted each time a screen is popped, regardless of whether it was popped by `Navigation.pop()` command or gesture.

**Comment by msqar** [comment]
@guyca hey guy, is telling me that registerScreenPoppedListener is not a function. In what version of RNN was this added? I'm using 3.7.0. Thanks!

**Comment by guyca** [comment]
Hey @msqar On which platform are you not getting the event?

**Comment by msqar** [comment]
@guyca on iOS 13, didn't test on Android though. I ended up using a different library that would handle event listeners to solve it :( since i couldn't make this one work, don't know why, even by updating to latest.

**Comment by habovh** [comment]
@guyca can confirm the `registerScreenPoppedListener` event is never fired on iOS 13.

**Comment by eightyfive** [comment]
I'm using `react-native-navigation@^4` and I can confirm the event is not fired both in iOS 12 & 13 (Simulators).

**Comment by guyca** [comment]
@eightyfive screenPopped event works as expected on latest RNN, please upgrade and open a new issue with a reproduction if you think there's still an issue 👍
