### ISSUE TITLE
[V2] [iOS] SearchBar search button press

### ISSUE THREAD

**Issue by wbeuil** [wix/react-native-navigation#3944]
How can we know when the user presses the search button on the search bar using RNN in iOS 11+?

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
Navigation.setRoot({
  root: {
    bottomTabs: {
      children: [
        {
          stack: {
            children: [{
              component: {
                name: 'Test',
              },
            }],
            options: {
              topBar: {
                searchBar: true,
              },
            },
          },
        },
     },
  },
});
```

---
### Environment
* React Native Navigation version: "react-native-navigation": "^2.0.2538"
* React Native version: "react-native": "0.56.0"
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by jun1st** [comment]
check [Handling button press events ](https://wix.github.io/react-native-navigation/v2/#/docs/topBar-buttons?id=handling-button-press-events) out.

**Comment by samcampisi** [comment]
@wbeuil did you manage to find out? I also want to know when the user presses the search button in the keyboard
