### ISSUE TITLE
unexpected white space at top of the screen in android

### ISSUE THREAD

**Issue by dileepkumarjuloori** [wix/react-native-navigation#3945]
![1fb03061-d892-4811-a625-ae0f526f79f0](https://user-images.githubusercontent.com/32605811/45340678-13805980-b5ca-11e8-8840-42733aab2495.jpeg)

After adding navigation getting unexpected white at top of the screen in android. I hidden topbar  even though getting topspace
Please help to solve this issue

Thanks in advance

**Comment by hisothreed** [comment]
Use drawBehind: true in the top bar options

**Comment by kubilaytural** [comment]
Thanks @hisothreed !

Example:

  Navigation.setDefaultOptions({
    topBar: {
      visible: true,
      **drawBehind: true,**
      title: {
          ...props
      },
   ....
  });
