### ISSUE TITLE
 On the android, when the application stratum is simply a white screen

### ISSUE THREAD

**Issue by sinevitch** [wix/react-native-navigation#3948]
I do everything as indicated in the repasitory
JuneDomingo/movieapp

index.android.js

![image](https://user-images.githubusercontent.com/35930695/45350892-918a3380-b5bd-11e8-9807-28d348e9fe91.png)

app.android.js
![image](https://user-images.githubusercontent.com/35930695/45350941-a5ce3080-b5bd-11e8-9aa9-6b81e5f63046.png)

screen.js

![image](https://user-images.githubusercontent.com/35930695/45350968-b2eb1f80-b5bd-11e8-80b4-4ff89512420f.png)

Movie.js
![image](https://user-images.githubusercontent.com/35930695/45350990-c0080e80-b5bd-11e8-883a-8e6457f3b026.png)

Drawer.js
![image](https://user-images.githubusercontent.com/35930695/45351003-cb5b3a00-b5bd-11e8-8ce8-6d2431c59616.png)

![image](https://user-images.githubusercontent.com/35930695/45351598-3f4a1200-b5bf-11e8-9b46-0ec1ffb7eed7.png)

Help me what I'm doing wrong?

### Environment
* React Native Navigation version: "^1.1.485"
* React Native version: 0.56.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by holparb** [comment]
Try launching the app via Android Studio and check the error logs in LogCat for the launched application instance. 
I had a similar issue and checking the error log revealed that the issue was in fact came from some external library.

**Comment by sinevitch** [comment]
I think the problem is due to "overlay permissions need to be granted react native"
Please tell me there is a way to solve it?

**Comment by holparb** [comment]
You need to grant the permission to the app in the phone's settings, for example like this:
https://www.howtogeek.com/271519/how-to-fix-the-screen-overlay-detected-error-on-android/

**Comment by LRNZ09** [comment]
The overlay permission is just for the green bar of the bundle loading, it has nothing to do with the white screen.
Please see https://github.com/wix/react-native-navigation/issues/3905#issuecomment-423230553
