### ISSUE TITLE
How to add 3rd analytics ?

### ISSUE THREAD

**Issue by alexlipe** [wix/react-native-navigation#395]
### Issue Description

I want add some analytics into my project , and analytics must use onCreate(),onResume(),onPause(). Where can I insert it?   in  MainApplication.java or MainActivity.java?

* React Native Navigation version: 2.0.0-experimental.133
* React Native version: 0.31
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by beast** [comment]
Which analytics package are you using? You should be able to just add your code in MainApplication.java like the examples from FB analytics:

https://github.com/facebook/react-native-fbsdk

**Comment by alexlipe** [comment]
I'm use Umeng analytics, is a China package.   Can you help me ? @beast 
https://github.com/esseak/rn-umeng

**Comment by beast** [comment]
Just follow ru-umeng instructions and the WIX Navigation instruction here https://github.com/wix/react-native-navigation/wiki/Installation---Android

Below goes to MainApplication.java

```
@Override
protected void onResume() {
    super.onResume();
    MobclickAgent.onResume(this);
}

@Override
protected void onPause() {
    super.onPause();
    MobclickAgent.onPause(this);
}

  @NonNull
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {

    // Add the packages you require here.
    return Arrays.<ReactPackage>asList(
        new UmengPackage()
    );
  }
```

**Comment by alexlipe** [comment]
no....

**Comment by alexlipe** [comment]
can't run.
say can't find symbol. @beast 

Users/alex/workflow/guanjiaapp/android/app/src/main/java/com/guanjiaapp/MainApplication.java:42: 错误: 找不到符号
        super.onResume();
             ^
  符号: 方法 onResume()
/Users/alex/workflow/guanjiaapp/android/app/src/main/java/com/guanjiaapp/MainApplication.java:40: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
/Users/alex/workflow/guanjiaapp/android/app/src/main/java/com/guanjiaapp/MainApplication.java:48: 错误: 找不到符号
        super.onPause();
             ^
  符号: 方法 onPause()
/Users/alex/workflow/guanjiaapp/android/app/src/main/java/com/guanjiaapp/MainApplication.java:46: 错误: 方法不会覆盖或实现超类型的方法
    @Override

**Comment by alexlipe** [comment]
I use this at RN0.28, it is work well .

**Comment by beast** [comment]
Try this. 

MainActivity.java
```
@Override
protected void onResume() {
    super.onResume();
    MobclickAgent.onResume(this);
}

@Override
protected void onPause() {
    super.onPause();
    MobclickAgent.onPause(this);
}
```

MainApplication.java
```
@NonNull
@Override
public List<ReactPackage> createAdditionalReactPackages() {

    // Add the packages you require here.
    return Arrays.<ReactPackage>asList(
        new UmengPackage()
    );
}
```

There was some Android breaking change at RN0.29. That is why it works for RN0.28. https://github.com/facebook/react-native/releases/tag/v0.29.0

**Comment by beast** [comment]
@alexlipe What is your wechat ID? I think it might be more involved than the above because how WIX Android navigation activity works.

**Comment by alexlipe** [comment]
my wechat is 2292390.  thank you very much @beast

**Comment by alexlipe** [comment]
thanks @beast .   It is not issues , is my fault
