### ISSUE TITLE
[v2][solved]Problem bottomsTab visible iOs

### ISSUE THREAD

**Issue by jesussantos** [wix/react-native-navigation#3951]
Hello

After two days looking for a solution to hide the bottom bar in the end I found it.
The only thing I have done is to replace the following line:

**react-native-navigation/lib/ios/RNNBottomTabOptions.m**
if (self.visible) {
	[viewController.tabBarController setSelectedIndex:[viewController.tabBarController.viewControllers indexOfObject:viewController]];
}

The new line is:

[viewController.tabBarController.tabBar setHidden:![self.visible boolValue]];

For me, it was the solution

**Comment by pakyo-pan** [comment]
Thanks for your help! I have spent so much time and this solution works for me.

**Comment by dao-wkm** [comment]
On iOS, BottomTab visibility can be changed only when pushing screens.
https://wix.github.io/react-native-navigation/v2/#/docs/options-migration?id=tabbarhidden

**Comment by rendomnet** [comment]
Not working for me on 2.0.2570
