### ISSUE TITLE
"latest" tag now points to v2

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#3953]
I just reinstalled my node modules, using the "latest" tag I got some build errors (still on v1) and looks like it was due to being on v2. 
`node_modules/react-native-navigation/package.json` shows:
```
{
  "_from": "react-native-navigation@latest",
  "_id": "react-native-navigation@2.0.2534-patch.1",
...
```

What is/how do we get the latest v1 stable version?

**Comment by adamski** [comment]
Found it via https://www.npmjs.com/package/react-native-navigation
Currently the latest version 1 is "1.1.485"

**Comment by guyca** [comment]
`latest` shouldn't be used, changing the dependency to `react-native-navigation: '1.x.x'` should work.

**Comment by adamski** [comment]
Please update the docs to reflect this: https://wix.github.io/react-native-navigation/#/installation-android
