### ISSUE TITLE
Can we get navigator object in redux  so that we can dispatch push pop  in thunk action creator ? 

### ISSUE THREAD

**Issue by ParshantArora** [wix/react-native-navigation#3957]
How we can get navigator object in redux so that we can dispatch push pop in thunk action creator?
Description : 
Hi the react-native-navigation is very good in terms of performance . I am new to react-native-navigation earlier i was working on react-navigation in which we can get navigator object in redux for handing  push pop but in this navigation how we can get that or please mention the steps to do the same task
Thanks

**Comment by hisothreed** [comment]
```
import { Navigation } from "react-native-navigation"

// inside your redux-thunk action 

export const doSomeActionWithThunk = () => async (dispatch, getState) => { 
  ..
  dispatch({ ...
  ..
  Navigation.push..
  Navigation.pop..
}
```

**Comment by ItsNoHax** [comment]
Don't forget you can await a Navigation.push/pop so it fits perfectly inside thunks as is.

**Comment by ParshantArora** [comment]
Thanks @ItsNoHax  and  @hisothreed

**Comment by gethabit** [comment]
how are we able to do Navigation.push without a this.props.componentId

**Comment by yeomann** [comment]
just pass `this.props.componentId` in your redux action. @gethabit
