### ISSUE TITLE
[V2] getting error when calling dismissModal

### ISSUE THREAD

**Issue by hisothreed** [wix/react-native-navigation#3964]
### Issue Description

getting this error when calling 
```
Navigation.dismissModal( this.props.componentId )
```
and nothing happens then

### Steps to Reproduce / Code Snippets / Screenshots

<img width="306" alt="screen shot 2018-09-13 at 6 28 59 pm" src="https://user-images.githubusercontent.com/9201625/45498696-4de12680-b783-11e8-8ad6-62e2f581c847.png">

---
### Environment
* React Native Navigation version: 2.0.2544
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): emulator

**Comment by guyca** [comment]
`dismissModal` method prototype has changed - Recompile the native code.
