### ISSUE TITLE
[v2] How do we set drawerLockMode on both platforms?

### ISSUE THREAD

**Issue by jpls93** [wix/react-native-navigation#3968]
We can set sideMenu layouts per the docs
![image](https://user-images.githubusercontent.com/17956698/45541666-4896e100-b842-11e8-8c46-79c3977883f9.png)

Is there a way to define a property so we could lock them for both platforms as in https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#drawerlockmode?

**Comment by rgoldiez** [comment]
@jpls93 - Have you tried the code below?  

```
Navigation.mergeOptions(this.props.componentId, { sideMenu: { left: { enabled: false } } });
```

**Comment by jpls93** [comment]
@rgoldiez - Thank you. I will try as soon as I can and keep you posted.

Although, may I ask where you got these properties from? I couldn't seem to find them in the docs.

**Comment by rgoldiez** [comment]
@jpls93 - The docs definitely leave a little room for improvement!  If you go here to the [styling section of the docs](https://wix.github.io/react-native-navigation/v2/#/docs/styling) you will see the options for the `sideMenu`, one of which is `enabled`.  You can toggle that dynamically using `mergeOptions` anytime you need to change it.

**Comment by jpls93** [comment]
Thanks @rgoldiez !

**Comment by rgoldiez** [comment]
@jpls93 - Glad to help!
