### ISSUE TITLE
[V2] TopBar Issue only when i have scrollview on the page & after updated to RNN 2547

### ISSUE THREAD

**Issue by naiduasn** [wix/react-native-navigation#3970]
### Issue Description

TopBar
Yesterday i upgraded RNN from version V2- 2431 to V2 - 2547.
The reason for the upgrade is this issue #3803.
This happens only for the screens where i have scrollview

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
static get options() {
        return {
            topBar: {
                title: {
                    text: 'Horecacart',
                    color: 'white',
                    fontSize: 30,
                    alignment: 'left',
                    fontFamily: 'Cocon-Regular'
                },
                background: {
                    color: '#3880ff'
                },
                ...Platform.select({
                    android: { drawBehind: true },
                    ios: { drawBehind: false, }
                }),
                leftButtons: [
                    {
                        id: 'buttonMenu',
                        icon: iconsMap['bars'],
                        color: 'white',
                    }
                ],
                rightButtons: [],
            },
            statusBar: {
                backgroundColor: '#3880ff'
            }
        };
    }
```
The render method contains 
```javascript
<ScrollView
                        style={styles.scrollview}
                        scrollEventThrottle={200}
                        directionalLockEnabled={true}
                    >
                        {homePageGrid}
                        {homePageSlide}
                    </ScrollView>
```
<img width="311" alt="screen shot 2018-09-15 at 11 56 03 pm" src="https://user-images.githubusercontent.com/6754367/45593235-44cca100-b99f-11e8-8442-bee643748c88.png">

---
### Environment
* React Native Navigation version: 2.0.2547
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator / Android 7 / Relase & Debug

**Comment by adamterlson** [comment]
@naiduasn You can try and set `contentInsetAdjustmentBehavior` on your scroll view:

`<ScrollView contentInsetAdjustmentBehavior="never">...</ScrollView>`
