### ISSUE TITLE
[v2] [android] [failing build] Task :react-native-navigation:compileReactNative56DebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by developer239** [wix/react-native-navigation#3974]
### Android build is failing

```
> Task :react-native-navigation:compileReactNative56DebugJavaWithJavac FAILED
/Users/michaljarnot/IdeaProjects/react-native-redux-wix-navigation/node_modules/react-native-navigation/lib/android/app/src/reactNative56/java/com/reactnativenavigation/react/SyncUiImplementation.java:10: error: cannot find symbol
import com.facebook.react.uimanager.UIImplementationProvider;
                                   ^
  symbol:   class UIImplementationProvider
  location: package com.facebook.react.uimanager
/Users/michaljarnot/IdeaProjects/react-native-redux-wix-navigation/node_modules/react-native-navigation/lib/android/app/src/reactNative56/java/com/reactnativenavigation/react/SyncUiImplementation.java:23: error: cannot find symbol
    public static class Provider extends UIImplementationProvider {
                                         ^
  symbol:   class UIImplementationProvider
  location: class SyncUiImplementation
/Users/michaljarnot/IdeaProjects/react-native-redux-wix-navigation/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactNativeHost.java:86: error: cannot find symbol
                .setUIImplementationProvider(getUIImplementationProvider())
                                             ^
  symbol:   method getUIImplementationProvider()
  location: class NavigationReactNativeHost
/Users/michaljarnot/IdeaProjects/react-native-redux-wix-navigation/node_modules/react-native-navigation/lib/android/app/src/reactNative56/java/com/reactnativenavigation/react/SyncUiImplementation.java:24: error: method does not override or implement a method from a supertype
        @Override
        ^
/Users/michaljarnot/IdeaProjects/react-native-redux-wix-navigation/node_modules/react-native-navigation/lib/android/app/src/reactNative56/java/com/reactnativenavigation/react/SyncUiImplementation.java:29: error: method does not override or implement a method from a supertype
        @Override
        ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
```

### Steps to Reproduce / Code Snippets / Screenshots

This is minimal example. Fresh `react-native init` project.

https://github.com/developer239/react-native-redux-wix-navigation/pull/3

---
### Environment
* React Native Navigation version: 2.0.2553
* React Native version: 0.57.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by developer239** [comment]
@guyca Hey could you please look at the issue? This is definitely not a general issue. I followed your installation process step by step and I created a minimal example.

**Comment by KhaledSayed** [comment]
i have the same problem

**Comment by guyca** [comment]
Hey guys, I think [this section](https://wix.github.io/react-native-navigation/v2/#/docs/Installing?id=_8-rnn-and-react-native-version) from the installation guide is related

**Comment by developer239** [comment]
@guyca 
```
RNN only support react-native 0.51 ("reactNative51"), 0.55 ("reactNative55"), and 0.56 ("reactNative56"),
``` 🙈 

Is it possible to downgrade to react-native 56 somehow? 😂

**Comment by developer239** [comment]
@guyca @KhaledSayed 
`RNN only support react-native 0.51 ("reactNative51"), 0.55 ("reactNative55"), and 0.56 ("reactNative56"),`🙈 

After downgrading to `react-native@0.56.0` I have a new error:
`java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex`

I will come back to this later. If I had to guess this has probably something to do with this section: https://wix.github.io/react-native-navigation/v2/#/docs/Installing?id=_82-ignore-other-rnn-flavors

Or maybe I have different static `android` and `ios` files because originally I created application with `react-native@0.57.0`.

**Comment by developer239** [comment]
Bump. 🙂

**Comment by kenma9123** [comment]
afaik the v2 of react-native-navigation does not fully support react-native v57 yet. 
So shift to v1 or lower your react native version to v56

**Comment by developer239** [comment]
bump

**Comment by barjas** [comment]
same issue, does not work on android for RN 0.57

**Comment by developer239** [comment]
@barjas
React native 57 is not supported.

I am not sure but I think I made a mistake in the 4th step. Also, do you have MacOs Mojave? I want to make this work tonight.

This is the most minimal implementation that I found (note that this is react-native 55):
https://github.com/drorbiran/react-native-init

**Comment by developer239** [comment]
@KhaledSayed @barjas @kenma9123 @guyca Can you please reopen this issue? On and off I am trying to figure this out for more than a month now.

This is my updated android implementation: https://github.com/developer239/react-native-redux-wix-navigation/pull/4


0. step: Downgrade react-native to 0.56.0 https://github.com/developer239/react-native-redux-wix-navigation/pull/4/commits/885da087131ad93b0c22365012e735a6132fdd68 (install a new dependency, `rm -rf android` and eject new android folder)
1. step: https://github.com/developer239/react-native-redux-wix-navigation/pull/4/commits/03a98443939efd17d37d352369fd7323ceb7b47e
2. step: https://github.com/developer239/react-native-redux-wix-navigation/pull/4/commits/4681c2658e66f061a1cb6062dc3264eea8667103
3. step: https://github.com/developer239/react-native-redux-wix-navigation/pull/4/commits/171314e25a77db0ff0ccbaecc86bce2d84bc3598
4. step: https://github.com/developer239/react-native-redux-wix-navigation/pull/4/commits/934da188a43ab8438a7782e6d7399aa6ad95bdbf
5. step: https://github.com/developer239/react-native-redux-wix-navigation/pull/4/commits/301fcc97355e180c198ed545003365bc520c6c12
6. step: https://github.com/developer239/react-native-redux-wix-navigation/pull/4/commits/733b7595b2e10a2a96a384354fc5cd330d9f6fad
7. step: https://github.com/developer239/react-native-redux-wix-navigation/pull/4/commits/be1452c6564dde2e2aed46851a57c8aa7ba35fd5
8. step: https://github.com/developer239/react-native-redux-wix-navigation/pull/4/commits/5cda9f1df7c88c02e8c934b5ee6e5724c6262484
8.2 step: https://github.com/developer239/react-native-redux-wix-navigation/pull/4/commits/1d2f8c15ed07e49a4342e8599fdb81dd4e3fb107
9. Fix babel configuration: https://github.com/developer239/react-native-redux-wix-navigation/pull/4/commits/31f436031de26768d2c9f42ac3543ead7d4f9a42

Android build: **works**
Npm build: **works**

My appliaction? Does not work. 🤯

![image](https://user-images.githubusercontent.com/14946081/47135422-027bd580-d265-11e8-8e2f-df0464cd280a.png)

I will be more than happy to create PR and update documentation when we make this repo work. I mean I have literally the simplest setup there can be.

**Comment by barjas** [comment]
@developer239, im starting new app, so what i ended starting fresh again using RN 0.56.
then will upgrade later on when RNN2 fully supports latest RN version

**Comment by developer239** [comment]
@barjas Withc RNN1? 😢 That does not really solve the problem.

**Comment by barjas** [comment]
@developer239 , RN 0.56 + RNN2.
i followed the documentation and it just worked as it should

**Comment by developer239** [comment]
@barjas can you please share your repository? Just the minimal `RN 0.56 + RNN2` without any other dependencies.

**Comment by PurnimaNaik** [comment]
### Same issue:-

I am trying to set up a new project from scratch.

```
    "react-native": "^0.57.3",
    "react-native-navigation": "^2.0.2608"
```

### Tried/Integrated the following:-

1. `missingDimensionStrategy "RNN.reactNativeVersion", "reactNative56"`

 2. 
```
subprojects { subproject ->
  afterEvaluate {
     if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
        android {
          variantFilter { variant ->
             def names = variant.flavors*.name
                if (names.contains("reactNative51") || names.contains("reactNative55")) {
                  setIgnore(true)
                  }}}}}}
```

3. 
```
configurations.all {
  resolutionStrategy {
    eachDependency { DependencyResolveDetails details ->
       if (details.requested.group == 'com.facebook.react' && details.requested.name == 'react-native') {
         details.useVersion "0.57.3" // Your real React Native version here
       }}}}
```
4. `chmod 755 android/gradlew`
5. `react-native run-android --variant debug`

### Everything boils down to these 2 errors on Android:-

1. `npm run android` - **Task :react-native-navigation:compileReactNative56DebugJavaWithJavac FAILED**

2.  `react-native run-android` - **Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment**

If I directly run the emulator from Android studio, everything works well.

### Downgrading to react-native 0.56.0 throws this error on iOS:-
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(/Users/"system-name"/"project-name"/index.js: .overrides is not allowed in preset options (null))

I would prefer a solution that won't require downgrading from react-native 0.57.3. 

Any ideas?

**Comment by zoecarver** [comment]
Works on `0.56`
