### ISSUE TITLE
[V2] [Android] Weird behavior with mergeOptions for the topBar

### ISSUE THREAD

**Issue by samcampisi** [wix/react-native-navigation#3976]
### Issue Description

I'm trying to create a searchBar for Android that mimics the following behavior:

![ezgif com-optimize](https://user-images.githubusercontent.com/42766924/45614498-fe904400-ba69-11e8-86d4-599c72912c7c.gif)

To do this, I thought I could use mergeOptions to render either the search icon as a right button or the cancel left button with a custom title component including the textInput to type the search query, like this:

```javascript
 navigationButtonPressed({ buttonId }) {
    switch (buttonId) {
      case 'searchButton':
        Navigation.mergeOptions(this.props.componentId, {
          topBar: {
            leftButtons: [
              {
                id: 'closeButton',
                icon: require('assets/cancel.png'),
                color: theme.TEXT_PRIMARY_COLOR,
              },
            ],
            rightButtons: [],
            title: {
              component: {
                name: 'wallet.searchText',
                alignment: 'center',
              },
            },
          },
        });
        break;
      case 'closeButton':
        Navigation.mergeOptions(this.props.componentId, {
          topBar: {
            rightButtons: [
              {
                id: 'searchButton',
                icon: require('assets/search-icon.png'),
                color: theme.TEXT_PRIMARY_COLOR,
              },
            ],
            leftButtons: [],
            title: {
              text: 'My Original Title'
            },
          },
        });
        this.searchBarCancelPressed();
        break;
      default:
        break;
    }
  }
```

This works when you're within the same view. However, when you navigate to another screen and come back to this screen, it displays a mixture of both options. I can see both the custom title component and the right button:

![ezgif com-optimize 1](https://user-images.githubusercontent.com/42766924/45615319-72cbe700-ba6c-11e8-8203-1262ea0cf765.gif)

You can see that as long as I'm on "my screen" it works as expected but as soon as I navigate the options get messed up.

Why would this be happening? Is there something I'm missing on mergeOptions?

---
### Environment
* React Native Navigation version: 2.0.2553
* React Native version: 0.55
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Pixel 2 API 28 Android 9

**Comment by samcampisi** [comment]
As a workaround, adding a custom component to display "My Original Title" does the trick, but it's not really what I wanted.

**Comment by mdelclaro** [comment]
Hey, would you mind sharing the searchText component, please?
