### ISSUE TITLE
Make dismissModal return a promise

### ISSUE THREAD

**Issue by ofirdagan** [wix/react-native-navigation#398]
### Make dismissModal return a promise

A lot of the times when u open a modal you want to do something with the result. For example if you edit a contact you want to return the new edited contact to the screen that opened you.

I suggest

`navigator.dismissModal()` will return a promise with whatever params this modal wants to return.

---
### Environment
- React Native Navigation version: latest
- React Native version: 31
- Platform(s) (iOS, Android, or both?): both

**Comment by trung1008** [comment]
i want to same :(

**Comment by kyle-ssg** [comment]
I don't think you'd really want to couple form submission with a modals dismissing. Two viable options here would be : 
 
1 - If using a flux / redux have the form trigger actions and save contacts to a store
2 - Pass an onSubmit callback via passProps and call this.props.onSubmit when you deem necessary.
