### ISSUE TITLE
[V2] Topbar button won't show

### ISSUE THREAD

**Issue by mdelclaro** [wix/react-native-navigation#3982]
### Issue Description

Topbar buttons won't show. I can see the allocated space for it, but it is not there. Am I missing something?

### Steps to Reproduce / Code Snippets / Screenshots
My navigation.js
```
(...)
const startApp = () => {
  Navigation.setRoot({
    root: {
      sideMenu: {
        id: 'sideMenu',
        left: {
          component: {
            id: 'leftDrawer',
            name: 'motoapp.Screen2'
          }
        },
        center: {
          stack: {
            id: 'navStack',
            children: [
              {
                component: {
                  id: 'Home',
                  name: 'motoapp.Home'
                },
              },
            ],
            options: {
              topBar: {
                title: {
                  text: 'Moto App'
                }
              }
            }
          }
        }
      }
    }
  });
};
```
My Home.js
```
(...)
static get options() {
    return {
      topBar: {
        title: {
          text: 'Moto App',
          animate: true,
          drawBehind: true,
          buttonColor: 'black',
          testID: 'topBar',
        },
        leftButtons: [
          {
            id: 'menuButton',
            text: 'Menu',
            component: {
              name: 'motoapp.Screen2'
            },
          }
        ]
      }
    };
  }
(...)
```

---
### Environment
* React Native Navigation version: 0.56
* React Native version: 2.0.2555
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device 5.1.1

**Comment by guyca** [comment]
React components are not supported as left buttons

**Comment by mdelclaro** [comment]
Sorry, that "component" is there just because I was trying different things, but even without it, I see no buttons. Shouldn't just an "id" and "text" show the button? Thanks.

Em 18 de set de 2018, às 03:19, Guy Carmeli <notifications@github.com<mailto:notifications@github.com>> escreveu:


React components are not supported as left buttons

**Comment by guyca** [comment]
Textual left button is also not supported on Android. Only icon buttons are supported as left buttons on Android.

**Comment by socceroos** [comment]
Is this a limitation of RNN 2 or is it a limitation imposed by the Android platform?

Is there any way around this? Perhaps there is some other topBar I can use to achieve the design we require? I've been searching for a while but have been unable to find a solution to this.

**Comment by zubko** [comment]
I think it's possible to make a custom component covering the whole top bar, which will render a custom button on the left. Maybe it's not for all cases, but for some cases this should work.
