### ISSUE TITLE
[V2] Bad accessibility on Android

### ISSUE THREAD

**Issue by JK0N** [wix/react-native-navigation#3984]
### Issue Description

On android, views are defining static content description by calling setContentDescription in class constructors, for example in StackLayout.java it calls setContentDescription("StackLayout") which is completely useless information for accessibility purposes. This makes accessibility services like TalkBack to focus and read out loud "StackLayout", "ComponentLayout", ... when navigating between focusable components.

If all the setContentDescription calls are removed/commented out, it works the same as on iOS.

### Steps to Reproduce / Code Snippets / Screenshots

Enable TalkBack: Settings --> Accessibility --> TalkBack. Open react-native app that uses react-native-navigation and switch between focusable components on screen. Every second tap on focusable component, it will actually focus on ComponentLayout and not the component user tapped.

---
### Environment
* React Native Navigation version: 2.0.2542
* React Native version: 0.56.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Emulator & Device

**Comment by draperunner** [comment]
Could this be re-opened? We just started using react-native-navigation, and a fix for this would be much appreciated.
