### ISSUE TITLE
[V2] [iOS] onSubmitEditing event for searchBar 

### ISSUE THREAD

**Issue by samcampisi** [wix/react-native-navigation#3985]
### Issue Description

I'm using searchBar in iOS and it works as expected (native behavior).

I was wondering if there's a way of knowing when the user presses on 'Search' (Intro) from the keyboard? Sort of like onSubmitEditing for TextInput.

### Steps to Reproduce / Code Snippets / Screenshots

<img width="620" alt="screen shot 2018-09-18 at 14 28 50" src="https://user-images.githubusercontent.com/42766924/45687811-00ccce00-bb50-11e8-9b4f-4a5e5b01560e.png">

I looked into searchBarUpdated but it doesn't really tell me when the user presses the intro key.

---
### Environment
* React Native Navigation version: 2.0.2553
* React Native version: 0.55
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X iOS 12

**Comment by samcampisi** [comment]
As a workaround I ended up using the Keyboard event listeners... that way when keyboardWillHide and the searchbar is not focused (which you know on search bar update) you know it's the moment to perform the "on search" code.

**Comment by kgaspar** [comment]
Yeah, was thinking of doing the same, shame there isn't a cleaner way to implement this. Thank you!
