### ISSUE TITLE
[V2][iOS] XCode 10 Build errors

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#3986]
### Issue Description

XCode 10 uses a new build system and complains about multiple commands producing file ReactNativeNavigation.h and RNNBridgeManagerDelegate.h

### Steps to Reproduce / Code Snippets / Screenshots

Temporary fix:
XCode -> File -> Project Settings -> Use legacy build system.

Error produced:
```

Showing All Errors Only
:-1: Multiple commands produce '/Users/development/Library/Developer/Xcode/DerivedData/basenetapp-emeszkvkwnjnxwerbwbsmzqgsgsx/Build/Products/Debug-iphonesimulator/include/ReactNativeNavigation/ReactNativeNavigation.h':
1) Target 'ReactNativeNavigation' (project 'ReactNativeNavigation') has copy command from '/Users/development/Desktop/Projects/app-react-native-2/node_modules/react-native-navigation/lib/ios/ReactNativeNavigation.h' to '/Users/development/Library/Developer/Xcode/DerivedData/basenetapp-emeszkvkwnjnxwerbwbsmzqgsgsx/Build/Products/Debug-iphonesimulator/include/ReactNativeNavigation/ReactNativeNavigation.h'
2) Target 'ReactNativeNavigation' (project 'ReactNativeNavigation') has copy command from '/Users/development/Desktop/Projects/app-react-native-2/node_modules/react-native-navigation/lib/ios/ReactNativeNavigation.h' to '/Users/development/Library/Developer/Xcode/DerivedData/basenetapp-emeszkvkwnjnxwerbwbsmzqgsgsx/Build/Products/Debug-iphonesimulator/include/ReactNativeNavigation/ReactNativeNavigation.h'
```

---
### Environment
* React Native Navigation version: 2.0.2555
* React Native version: 0.56.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Debug

**Comment by samcampisi** [comment]
Here are some options you can try:
https://github.com/wix/react-native-navigation/issues/3608

**Comment by ItsNoHax** [comment]
Oh I see this is a duplicate then, gonna go ahead and close the issue. Thanks @samcampisi
