### ISSUE TITLE
Working with react-native-gifted-chat (Resetting Views)

### ISSUE THREAD

**Issue by indivisable** [wix/react-native-navigation#399]
#### Issue Description

Hello trying to use Gifted Chat inside a Tabs or Modal and it seems to get reset each time. What is best way to integrate into external libraries like Gifted Chat? I think it has to do with it being unmounted but should not have problem re-initializing. 

#### Steps to Reproduce / Code Snippets

1) Download and run the react-native-navigation example (https://github.com/wix/react-native-navigation)
2) Install react-native-gifted-chat into the project (https://github.com/FaridSafi/react-native-gifted-chat)
3) Use the example code for gifted-chat and try to put inside a Tab or Modal
4) Try to test with Tabs (does not work at all) or a Modal (works once then not after)

Anyone have some tips on how to make work? It worked fine with ExNavigation library, does this have to do with the way the root view is handled?

**Comment by guyca** [comment]
Hey @indivisable
Can you please clarify what  "it seems to get reset each time" means?

**Comment by edvinasbartkus** [comment]
My two cents, I am using both react-native-navigation with gifted-chat. All works perfectly, did not have to do any workarounds or hack anything to make it work. Everything works out of the box on Android and iOS.

**Comment by guyca** [comment]
Thanks @edvinasbartkus

**Comment by indivisable** [comment]
Thanks to @kfiroo I found fix: https://github.com/FaridSafi/react-native-gifted-chat/issues/244

@shivekkhurana

```
import Dimensions from 'Dimensions';
Update 1 - October 9, 2016

It wasn't react-native-navigation or flex:1, what fixed the issue for me was wrapping GiftedChat in

 <View style={{height: Dimensions.get('window').height - 65}}></View>
```
