### ISSUE TITLE
[v2] Shared element transition stretches element in a weird way

### ISSUE THREAD

**Issue by israelidanny** [wix/react-native-navigation#3990]
I'm trying to test out shared element transitions in `v2` and right now the transition looks like it simply resizes a bitmap version of the element wrapped in `Navigation.Element`. 

Since I have an image I want to scale, it loses aspect ratio and makes it look quite ugly. Is it intended behaviour? Is there any way to tweak it?

I tried to set `resizeMode` to `cover` (both on `Navigation.Element` and `Image`) but it doesn't seem to help.

**Comment by israelidanny** [comment]
It seems that an older issue reported similar quirks, but was closed:
https://github.com/wix/react-native-navigation/issues/2758

I'm also experiencing weird stretching with text even if I don't change the style / color, just the position.

**Comment by jinshin1013** [comment]
Is this being worked on at the moment? I know SharedElement Transition is quite a low priority in Wix, but would love to have this feature working properly.

**Comment by laurentrivard** [comment]
Anyone working on SharedTransitionElements for Android?

**Comment by tastyqbit** [comment]
This is a new issue for me. I was using ReactNative 0.59.10 with react-native-navigation version 2.21.1 and this was working.

I created a new project with react 0.6 with the same version of rnn and the resizeMode and image stretching is not working at all.

Help please, I need to launch!

**Comment by ThoMiDev** [comment]
@tastyqbit me too

**Comment by geroale** [comment]
Same here

**Comment by guyca** [comment]
Shared element transition has been reimplemented in [v5](https://github.com/wix/react-native-navigation/issues/5904) and this issue has been addressed.
