### ISSUE TITLE
[v2] Timeline for DeepLinks in v2?

### ISSUE THREAD

**Issue by rsokz** [wix/react-native-navigation#3991]
### Issue Description

Is there an estimated timeline to get deep links working in v2?

**Comment by birkir** [comment]
The deep link system in v1 actually is just a simple event library that you can build yourself if you desperately need it.

```jsx
import EventEmitter from 'EventEmitter';
export const events = new EventEmitter();
```

```jsx
import { events } from './events';

class Screen1 extends React.Component {

  componentDidMount() {
    events.addEventListener('DeepLink', this.handleDeepLink);
  }

  handleDeepLink(event) {
    const parts = event.link.split('/'); // Link parts
    const payload = event.payload; // (optional) The payload
    if (parts[0] == 'chats') {
      // handle the link somehow, usually run a this.props.navigator command
    }
  }
}

class Screen2 extends React.Component {

  onContactSelected(contactID) {
    events.emit('DeepLink', {
      link: 'chats/' + contactID,
      payload: '' // (optional) Extra payload with deep link
    });
  }
}

```

**Comment by webdevsyd** [comment]
> The deep link system in v1 actually is just a simple event library that you can build yourself if you desperately need it.
> 
> ```js-jsx
> // events.js
> import EventEmitter from 'EventEmitter';
> export const events = new EventEmitter();
> ```
> 
> ```js-jsx
> import { events } from './events';
> 
> class Screen1 extends React.Component {
> 
>   componentDidMount() {
>     events.addEventListener('DeepLink', this.handleDeepLink);
>   }
> 
>   handleDeepLink(event) {
>     const parts = event.link.split('/'); // Link parts
>     const payload = event.payload; // (optional) The payload
>     if (parts[0] == 'chats') {
>       // handle the link somehow, usually run a this.props.navigator command
>     }
>   }
> }
> 
> class Screen2 extends React.Component {
> 
>   onContactSelected(contactID) {
>     events.emit('DeepLink', {
>       link: 'chats/' + contactID,
>       payload: '' // (optional) Extra payload with deep link
>     });
>   }
> }
> ```

Will this work when I open the link for example in my email (GMAIL)?.

**Comment by ionush** [comment]
i believe this isn't feasible because react native doesn't import node standard library anymore

**Comment by guyca** [comment]
Hey guys, as @birkir noted - v1's deeplink system was a very basic pub-sub implementation. As handling events isn't a navigation library's concern we opted to remove it from v2.
I'm closing the issue as it won't be added to RNN in the future.

**Comment by RichardLindhout** [comment]
It's really easy with the Linking library from React Native ;)
https://facebook.github.io/react-native/docs/linking.html
