### ISSUE TITLE
Styling Tabs

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#4]
How do you suggest we style the tabs?

**Comment by talkol** [comment]
This feature isn't supported yet. There's a related PR on react-native-controllers. As soon as it's merged we'll add this functionality here. Should be in a couple of days.

**Comment by smooJitter** [comment]
Thank you, I look forward to it.

**Comment by talkol** [comment]
Added.

https://github.com/wix/react-native-navigation#styling-the-tab-bar

**Comment by smooJitter** [comment]
AWESOME
