### ISSUE TITLE
Topbar image

### ISSUE THREAD

**Issue by maxs15** [wix/react-native-navigation#40]
Is there any way of rendering an image instead of a title in the topbar ? (To display the app icon)

Thanks

**Comment by artald** [comment]
when pushing a screen, you can specify a `titleImage`:

```javascript
this.props.navigator.push({
  title: "Styled",
  titleImage: require('../../img/my_image.png'),
  screen: "example.StyledScreen"
});
```

**Comment by maxs15** [comment]
Awesome ! Didn't find this prop in the docs

**Comment by artald** [comment]
added to the docs, thanks!

**Comment by markantonyz** [comment]
@artald i love you
