### ISSUE TITLE
[V2] showAsAction not documented

### ISSUE THREAD

**Issue by CoolCyberBrain** [wix/react-native-navigation#4001]
### Issue Description

```
topBar: {
    rightButtons: [
        {
            showAsAction: "ifRoom|always|never"
        }
    ]
}
```

is not documented in V2 docs

**Comment by kheraprabhat** [comment]
@CoolCyberBrain - is showAsAction working for you? I am using the latest version (2.16.0) and it is not working for me.

**Comment by danilobuerger** [comment]
Also missing from the TS Definition

**Comment by ItsNoHax** [comment]
Hey guys, don't forget this project is open source and ANY contributions are welcome.

I went ahead and created the PR to add showAsAction to the TS definition.

https://github.com/wix/react-native-navigation/pull/5199
