### ISSUE TITLE
[V2] buttonColor does apply to menu button

### ISSUE THREAD

**Issue by CoolCyberBrain** [wix/react-native-navigation#4002]
### Issue Description
```
topBar: {
        buttonColor: 'red'
}
```
does not apply to the 3-dot menu button in the top bar when using the following
```
topBar: {
    rightButtons: [
        {
            id: "test",
            text: "test",
            showAsAction: "never"
        }
    ]
}
```

---
### Environment
* React Native Navigation version: 2.0.2556
* React Native version: 0.56
* Platform(s): Android
* Device info: Device

**Comment by guyca** [comment]
This should be resolved by now
