### ISSUE TITLE
[v2] Android drawer functionality is broken

### ISSUE THREAD

**Issue by baldarian** [wix/react-native-navigation#4003]
### Issue Description

Is there someone who has implemented drawer with a toggle button on android ? since there's no way to listen to the drawer's appear/disappear events.

**Comment by rgoldiez** [comment]
@baldarian - Yes, I have.  For both iOS and Android, I have this in my `constructor` for my sideMenu/drawer:

```
    Navigation.events().registerNavigationButtonPressedListener(({buttonId}) => {
      if(buttonId === 'toggleDrawer') Navigation.mergeOptions('leftDrawer', { sideMenu: { left: { visible: this._isClosed } } });
    });
```

and `this._isClosed` is set in the componentDidAppear/Disappear methods of the drawer:
```
  componentDidAppear() {
    this._isClosed = false;
  }
  componentDidDisappear() {
    this._isClosed = true;
  }
```

**Comment by nic-thomson** [comment]
this works great on iOS, unfortunately the android version of RNN v2  has this issue.
https://github.com/wix/react-native-navigation/issues/3724

**Comment by alexsmartens** [comment]
This works on Android, here is my snippet:
```
// Button press listener
Navigation.events().registerNavigationButtonPressedListener((event) => {

    // launching menu
    if (event.buttonId == "menuButton"){
        Navigation.mergeOptions("MenuScreen", {
            sideMenu: {
                left: {
                    visible: true, //false
                },
            }
        });    
    }

})
```
where `menuButton` is a drawer button and `MenuScreen` is a drawer screen

**Comment by ItsNoHax** [comment]
Closing as there is already another issue for this open and it's been acknowledged by devs.

**Comment by ssshen** [comment]
Is this issue resolved? And this issue is still in my project.
