### ISSUE TITLE
[v2] Incorrect drawBehind behaviour while merging bottom tabs options

### ISSUE THREAD

**Issue by devey** [wix/react-native-navigation#4005]
### Issue Description

I would like to hide the `bottomTabs` when keyboard shows on Android ([cause otherwise they appear on top of the keyboard](https://github.com/react-navigation/react-navigation-tabs/issues/16)) and show them again when keyboard hides. The solutions seems to be toggling `bottomTabs.visible` but it seems like the tabs disappear but a white container stays there. Setting `bottomTabs.drawBehind: true` with `setDefaultOptions` fixes it but I'd like to toggle `drawBehind` like in the code below and this doesn't work. Looks like `drawBehind` is not taken into account in `mergeOptions`.

### Steps to Reproduce / Code Snippets / Screenshots

```
  Navigation.setDefaultOptions({
    bottomTabs: {
      visible: true,
      animate: false,
      drawBehind: false,
    },
  });
```
```
    Keyboard.addListener(
      'keyboardDidShow',
      () =>
        Platform.OS === 'android' &&
        Navigation.mergeOptions('BottomTabsId', {
          bottomTabs: {
            visible: false,
            drawBehind: true,
          },
        })
    );
    Keyboard.addListener(
      'keyboardDidHide',
      () =>
        Platform.OS === 'android' &&
        Navigation.mergeOptions('BottomTabsId', {
          bottomTabs: {
            visible: true,
            drawBehind: false,
          },
        })
    );

```

<img width="398" alt="screen shot 2018-09-20 at 15 42 44" src="https://user-images.githubusercontent.com/5102099/45822485-df084e00-bceb-11e8-941f-49be61a9546b.png">

---
#

## Environment
* React Native Navigation version: 2.0.2544
* React Native version: 0.55.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6s 11.4.1 debug mode

**Comment by iamolegga** [comment]
Same problem

**Comment by margaridaDinis** [comment]
Same issue on:
React Native Navigation version: 2.1.3
React Native version: 0.57.0
Platform(s) (iOS, Android, or both?): Android 8.0.0
Device info (Simulator/Device? OS version? Debug/Release?): Device Galaxy S8

**Comment by narodejesus** [comment]
I can confirm that this is still an issue.. 

drawBehind is not working when used using mergeOptions

**Comment by RobertFOConnor** [comment]
I managed to get the keyboard displaying over (in-front of) the bottom tabs by setting this in the manifest.
`android:windowSoftInputMode="stateAlwaysHidden|adjustPan|adjustResize"`

**Important**: Add this to your .MainActivity in the AndroidManifest.xml.

**Comment by RobertFOConnor** [comment]
@margaridaDinis Even better!

**Comment by lukebrandonfarrell** [comment]
This still exists when using mergeOptions to hide bottom tabs in Android. Even when using drawBehind the tab placeholder is still present.

**Comment by pie6k** [comment]
I'm still having this issue

**Comment by guyca** [comment]
The white space you're observing is background color of the stack the component was pushed into. 
@pie6k Are you observing a problem on v3? In v3, togelling tabs when keyboard is visible isn't necessary since BottomTabs are drawn behind the keyboard.
