### ISSUE TITLE
Question - what is the documentation generated with?

### ISSUE THREAD

**Issue by MariusMeiners** [wix/react-native-navigation#4006]
the documentation for this project looks very appealing and i wondered how it was created ? 
Are there any resources i can check out ? I hope it's alright that im opening an issue for this purpose but i did not know another way to get in touch.

Thank you very much
Marius

**Comment by iksent** [comment]
Do you really think openning an issue at github is the best way to ask such questions?

Here is what you are looking for:
https://docsify.js.org/#/?id=docsify
