### ISSUE TITLE
Background notification tap action is resetting navigation

### ISSUE THREAD

**Issue by bhushansethi** [wix/react-native-navigation#4007]
I am trying to use react-native-notifications with react-native-navigation on Android device
When app is foreground, everything works fine
When app is in background, navigation is getting reset. 
For example, if I am on 2nd tab of navigation, clicking notification when app is in background, launches app but reset navigation to 1st tab again.

**Comment by Natkarock** [comment]
> I am trying to use react-native-notifications with react-native-navigation on Android device
> When app is foreground, everything works fine
> When app is in background, navigation is getting reset.
> For example, if I am on 2nd tab of navigation, clicking notification when app is in background, launches app but reset navigation to 1st tab again.

Hello! Did you found an answer on your question?

**Comment by gusoskar** [comment]
This is the answer to the problem https://github.com/wix/react-native-navigation/issues/4007#issuecomment-447289559. Guys, remember to post your solutions before closing the issue. Thank you @Natkarock!

**Comment by vineethvijayan314** [comment]
We tried the same with Android 11 emulator and it's not working. is there anything else we need to do around it?
