### ISSUE TITLE
Back Button - Navigator White Background Flicker

### ISSUE THREAD

**Issue by indivisable** [wix/react-native-navigation#401]
### Issue Description

I have two screens each with their own navigatorStyles, the original has a blue background and I push in a screen which updates the navigatorStyle to make the background white or transparent (tested with both) and I hide the StatusBar. Note this is inside a Tab Application

Once I hit the back button the transition starts but instead of reseting the style before start of transition it seems to do it after which causes a white flicker. This is same even if I disable animated feature. If you use the swipe right gesture to go back the animation seems to be properly applied.

Also I tried to use the `this.props.navigator.toggleNavBar` to show/hide the Navbar but since we do not have fully working WillFocus/DidFocus (https://github.com/wix/react-native-navigation/issues/150) which is another issue itself as how can you reshow a hidden navbar?

Maybe related to this: https://github.com/wix/react-native-navigation/issues/14

![oct-27-2016 18-11-09](https://cloud.githubusercontent.com/assets/22860891/19788872/c724d80a-9c70-11e6-9596-c27db3a435e9.gif)
### Steps to Reproduce / Code Snippets / Screenshots

Screen One navigatorStyle: 

```
{
  navBarTextColor: '#FFFFFF', 
  navBarSubtitleTextColor: '#FFFFFF',
  //screenBackgroundColor: 'red', // Tried this #63 but seems only to effect global
  navBarBackgroundColor: '#3FA2F7',
  navBarButtonColor: '#FFFFFF',
  navBarHidden: false, 
  navBarHideOnScroll: false, 
  navBarTranslucent: false, 
  navBarTransparent: false, 
  navBarNoBorder: false, 
  drawUnderNavBar: false,
  drawUnderTabBar: true, 
  statusBarBlur: false, 
  navBarBlur: false, 
  tabBarHidden: false, 
  statusBarHideWithNavBar: false, 
  statusBarHidden: false, 
  statusBarTextColorScheme: 'light' 
}
```

Screen Two navigatorStyle: 

```
{
 navBarTextColor: '#3FA2F7', 
 navBarSubtitleTextColor: '#3FA2F7',
 navBarBackgroundColor: '#FFF', 
 navBarButtonColor: '#3FA2F7', 
 navBarHidden: false, 
navBarHideOnScroll: false, 
navBarTranslucent: false,
navBarTransparent: false, 
navBarNoBorder: true, 
 drawUnderNavBar: true, 
 drawUnderTabBar: true, 
 statusBarBlur: false, 
 navBarBlur: false, 
 tabBarHidden: true, 
 statusBarHideWithNavBar: false,
 statusBarHidden: true, 
 statusBarTextColorScheme: 'light' 
}

```

Push Call (initializes the Push)

```
this.props.navigator.push({
  screen: item.target,
  title: item.title,
  //titleImage: require('../../img/my_image.png'), 
  passProps: item.props, 
  animated: false, 
  backButtonTitle: item.backTitle,
  backButtonHidden: false, 
  navigatorStyle: item.navigatorStyle, 
  //navigatorButtons: item.navigatorStyle 
});
```

---
### Environment

"react": "15.3.2",
"react-native": "0.36.0",
"react-native-navigation": "^2.0.0-experimental.134", (using Tab Example)
iOS 10
iPhone 6

**Comment by camellieeee** [comment]
+1

**Comment by shafy** [comment]
+1

**Comment by Amurmurmur** [comment]
Same issue here

**Comment by Calvin92** [comment]
Hi, all:
Same issue here,
So any solutions to fix this bug?

**Comment by simonhintersonnleitner** [comment]
Same issue here.

**Comment by Calvin92** [comment]
By now , any solutions to fix this bug ?

**Comment by thechefchen** [comment]
Also came across this issue. Is there any solution for this?

**Comment by mazing** [comment]
How can this not be fixed in a package with so many users

**Comment by tereartur** [comment]
+1

**Comment by Moreno97** [comment]
Did you try the following option based on the documentation?
```The easiest way to style your screen is by adding static navigatorStyle = {}; to your screen React component definition.```

**Comment by karlmosenbacher** [comment]
+1

**Comment by yusufkinatas** [comment]
+1
