### ISSUE TITLE
[v2][Android] setting leftbutton makes title align more to the right

### ISSUE THREAD

**Issue by damathryx** [wix/react-native-navigation#4010]
### Issue Description
lefbutton causes title to align to the right only happens in android and it is fixed when the screen gets active again. only happens to the first screen when the app launch.
### Steps to Reproduce / Code Snippets / Screenshots

```  
componentWillMount () {
    Navigation.events().bindComponent(this);
    FontAwesome.getImageSource('bars', 25, 'black').then(icon =>
      Navigation.mergeOptions(this.props.componentId, {
        topBar: {
          leftButtons: [
            {
              id: 'MENU',
              icon,
              color: 'black'
            },
          ]
        }
      })
    )
  }
```
<img width="316" alt="screen shot 2018-09-21 at 11 54 30 am" src="https://user-images.githubusercontent.com/14576761/45861996-53052d80-bda2-11e8-8f5a-9ccb865b9f20.png">

---
### Environment
* React Native Navigation version: 2.0.2474
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Debug

**Comment by rgoldiez** [comment]
I see the same thing.  It seems inconsistent in our app though.  Some screens the title is where it should be, other times it's towards the right (like your screenshot).  I haven't spent enough time w/ V2 Android (yet) to determine why/when it's happening.
