### ISSUE TITLE
[V2] Warning: navigationButtonPressed for button '' was not handled

### ISSUE THREAD

**Issue by CoolCyberBrain** [wix/react-native-navigation#4017]
### Issue Description

`Warning: navigationButtonPressed for button '' was not handled`
pops up when a navigation button is pressed if `Navigation.events().registerNavigationButtonPressedListener();` is used instead of `Navigation.events().bindComponent(this);` and `navigationButtonPressed({ buttonId }){}`

---
### Environment
* React Native Navigation version: 2.0.2556
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by saleksandras** [comment]
+1

**Comment by ItsNoHax** [comment]
I only get this on subsequent reloads when the UI sort of falls out of sync. Cold booting the app makes it work again.

**Comment by GuillermoGuevara** [comment]
i have the same issue , i think is not good idea use V2 for the moment, in this version toggleDrawer also has an issue.
