### ISSUE TITLE
How I can set background color for statusbar? 

### ISSUE THREAD

**Issue by dacsang97** [wix/react-native-navigation#402]
I'm using react-native-navigation for my ios app. I opposite with a problems. I set navbar hidden on scroll,  but I don't want status bar is transparent, so I want to set background color for statusbar and content render under statusbar, same Instagram app. Anyone can help me? 
Thanks for your attention.

**Comment by Jose4gg** [comment]
Any update?

**Comment by FlaviooLima** [comment]
A cheat  to accomplish this is by using this:
`static navigatorStyle = { screenBackgroundColor: "red", navBarHidden: true, }`
or you can use position absolute.
I'm still hoping to find a better solution.  :/

**Comment by AugustoAleGon** [comment]
This issue should be re opened.
