### ISSUE TITLE
[V2] topBar title bold in iOS 12

### ISSUE THREAD

**Issue by inf2381** [wix/react-native-navigation#4022]
### Issue Description

After upgrading to iOS 12 and Xcode 10, the topBar title on iOS is bold by default and could only be changed by using a custom component. When using Xcode 9 and iOS 11.4, the fontWeight is normal by default (desired behavior). What changed? Would it be possible to add fontWeight as a styling option to the title?

### Steps to Reproduce / Code Snippets / Screenshots
```javascript
Navigation.setRoot({
  root: {
    stack: {
      children: [{
        component: {
          name: 'app.Dashboard',
          options: {
            topBar: {
              title: {
                text: 'DASHBOARD'
              }
            }
          }
        },
      }],
    }
  }
});
```

UPDATE:
We installed a custom font and provide a _normal and a _bold version of it in our assets. By default, the bold version is selected.  

---
### Environment
* React Native Navigation version: 2.0.2556
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator + Device; iOS 12; Debug + Release

**Comment by LRNZ09** [comment]
Having `fontWeight` would be really great!

**Comment by LRNZ09** [comment]
Temporary fixed setting `fontFamily: ".SFUIDisplay-Heavy"` within `topBar.title`
