### ISSUE TITLE
App on Android keep splash Screen when App from inactive to active

### ISSUE THREAD

**Issue by bjwulin** [wix/react-native-navigation#403]
### Issue Description

in android, my app will change it's appstate to inactivate when i push HOME key，and then I click the app icon to restart it，then A white screen will be keeped。and the white screen is the splash Screen,I can remove it by push back key。
### Steps to Reproduce / Code Snippets / Screenshots

1、push Home key to deactivate the app。
2、click the app icon to restart it
3、a white screen(splash screen) to show
4、to remove it by pushing the back key。
### Environment
- React Native Navigation version: 2.0.133
- React Native version: 0.31
- Platform(s) (iOS, Android, or both?):Android
- Device info (Simulator/Device? OS version? Debug/Release?): Android 5.0 Release and Debug

**Comment by JuoCode** [comment]
Meet the same problem in android

**Comment by guyca** [comment]
@JuoCode @bjwulin Is this consistent?
I wasn't able to repro on emulator.

**Comment by JuoCode** [comment]
It's only happen when the first launch after installed. If it's happened, just kill it and you will never repro it again.

**Comment by bjwulin** [comment]
@guyca ,it happened as @JuoCode ，only the first launch after installed。

**Comment by guyca** [comment]
Thanks @bjwulin @JuoCode 
I'll look into it asap

**Comment by guyca** [comment]
fixed in c5ebbfba75b18444f14a7f1a38fd9fbcabc14f18
