### ISSUE TITLE
navBarCustomViewInitialProps not working on Android

### ISSUE THREAD

**Issue by djschilling** [wix/react-native-navigation#4032]
### Issue Description

I built my own react component to be used at the tobBar.
When i try to pass properties to it with `navBarCustomViewInitialProps` they get passed on iOS but not on Android.

### Steps to Reproduce / Code Snippets / Screenshots

The tob Bar Component:

```
import React, { Component } from 'react';
import { View, Text } from 'react-native';

export default class SearchTobBar extends Component {
    render() {
        return (
            <View>
                <Text>Title: {this.props.title}</Text>
            </View>
        );
    }
}
```

How i use it in another component:

```
    componentDidMount() {
        this.props.navigator.setStyle({
            navBarCustomView: 'SearchTobBar',
            navBarCustomViewInitialProps: {
                title: 'Test'
            }
        });
    }
```

This results in Android to a text of `Title:` in the tobBar and in `Title: Test` on iOS.

---
### Environment
* React Native Navigation version: 2.0.2406
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Nexus 5 X

**Comment by ctt123** [comment]
Did you solve this problem?I met it too.

**Comment by kirtishjain9** [comment]
Hi,

Did you manage to get value of search text in it's parent view from where the search bar is being displayed if user types in any text in navBar SearchBar?

@guyca please suggest on this how to achieve?

Thanks in advance.
