### ISSUE TITLE
Why is there no reference about topTabs in documents?

### ISSUE THREAD

**Issue by heeroduo** [wix/react-native-navigation#4036]
Actually I thought that there is no function about top tabs in RNN.
But after I moved to RNN v2 from v1, I got to know that there is topTabs.
But why is there no any reference about it in document of v2.
I can't find any reference. Some people ask about it in here so I got to know.
So if I can use it, please tell me the page I can refer. Or if there is no way to 
add tobTabs by RNN, maybe I should use some other libraries right? hmmm

---
### Environment
* React Native Navigation version: 2.0.2538
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?):

**Comment by praveenapoojary** [comment]
@putuyoga but there is no doc about how to change color or highlighter
