### ISSUE TITLE
Bottom tabs are broken at 2.0.2563 version

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#4039]
### Issue Description

On version `2.0.2562` my bottom bar looks like this:
![image](https://user-images.githubusercontent.com/12229968/46144762-978f3e00-c266-11e8-81e9-7ec13f385e57.png)

After updating to `2.0.2563` or later the bottom bar looks like this:
![image](https://user-images.githubusercontent.com/12229968/46144757-92ca8a00-c266-11e8-80e5-c825ac2714c4.png)

Also what I noticed that if I click the tab they are invisible and after the click they appear again
![image](https://user-images.githubusercontent.com/12229968/46144794-af66c200-c266-11e8-8518-a8f6b10604e4.png)

So what happened on version 2.0.2563 so that some bottom tabs are invisible? 🤔 
Here is the comparison between those tags https://github.com/wix/react-native-navigation/compare/2.0.2562...2.0.2563

---
### Environment
* React Native Navigation version: 2.0.2563
* React Native version: 0.54.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by henrikra** [comment]
@yogevbd Hmm I guess something that you refactored in [this commit](https://github.com/wix/react-native-navigation/commit/51c71ecafb5d0236ce63ca836fa1e3bd59648f92) made this broke 🤔 

Because between those tags @guyca didn't touch any iOS files :D

**Comment by yogevbd** [comment]
It should be fix in the latest version.. can you please check?

**Comment by henrikra** [comment]
Just tried with version `2.0.2567` and it has the same problem :(

**Comment by yogevbd** [comment]
Can you post here your root layout structure? thanks

**Comment by henrikra** [comment]
Very simple. It looks like this

```
Navigation.setRoot({
  root: {
    bottomTabs: {
      children: [
        {
          component: {
            name: Screen.Home,
            options: {
              bottomTab: {
                text: 'something',
                icon: require('./images/icon.png'),
                testID: 'something',
                selectedIconColor: someColor,
                selectedTextColor: someColor,
              },
            },
          },
        },
        {
          component: {
            name: Screen.Profile,
            options: {
              bottomTab: {
                text: 'something',
                icon: require('./images/icon.png'),
                testID: 'something',
                selectedIconColor: someColor,
                selectedTextColor: someColor,
              },
            },
          },
        },
        {
          component: {
            name: Screen.Store,
            options: {
              bottomTab: {
                text: 'something',
                icon: require('./images/icon.png'),
                testID: 'something',
                selectedIconColor: someColor,
                selectedTextColor: someColor,
              },
            },
          },
        },
        {
          stack: {
            children: [
              {
                component: {
                  name: Screen.Messages,
                  options: {
                    bottomTab: {
                      text: 'something',
                      icon: require('./images/icon.png'),
                      testID: 'something',
                      selectedIconColor: someColor,
                      selectedTextColor: someColor,
                    },
                  },
                },
              },
            ],
          },
        },
      ],
    },
  },
});
```

**Comment by yogevbd** [comment]
Will be fixed in the next release! thanks

**Comment by henrikra** [comment]
I can try the new version tomorrow. Would be nice to keep issues open until they are tested :D

**Comment by henrikra** [comment]
I have now tried version `2.0.2568` and the bug is gone! Good job 👍
