### ISSUE TITLE
TitleBar renders titleImage too early

### ISSUE THREAD

**Issue by duranje** [wix/react-native-navigation#404]
### TitleBar Renders titleImage Too Early

The destination view of the push() function contains a titleImage. This image appears too early in the  transition between views and does not slide to the center of the title bar until the transition has completed (see accompanying gif). 

I am invoking the titleImage with the following code, in the destination view's constructor: 

```
        this.props.navigator.setTitle(
        {
            titleImage: require('../../assets/images/logo.png'),
        });
```

I have tried putting this code in various React component lifecycle methods, including componentWillMount and componentDidMount, none of which changed the behavior!

### Steps to Reproduce / Code Snippets / Screenshots

Gif:
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/17210728/19824349/342cd2d6-9d34-11e6-8d19-59171da5da3c.gif)

---
### Environment
* React Native Navigation version: 2.0.0-experimental.x
* React Native version: 0.35.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6 / iOS 10 / Debug

**Comment by guyca** [comment]
Try defining the image in your call to `navigator.push`

```js
this.props.navigator.push({
      title: "MyScreen",
      screen: "app.MyScreen"
      titleImage: require('../../../img/logo.png'),
    });
```

**Comment by duranje** [comment]
Thanks! That took care of it.
