### ISSUE TITLE
[V2] [Android] BottomTab initial render flickers

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#4045]
### Issue Description

When using a bottomTab layout, the first time you click on a tab, it will flicker before rendering normally. It seems to be more noticeable when you don't have a left icon.

### Steps to Reproduce / Code Snippets / Screenshots

Create a bottomTabs layout, cold boot the app and then switch tabs.

![peek 2018-09-28 09-54](https://user-images.githubusercontent.com/4223434/46195416-96ace980-c304-11e8-9f41-f26a6f9797f4.gif)

---
### Environment
* React Native Navigation version: 2..2566
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator + Device

**Comment by guyca** [comment]
Closing this as the BottomTabs flicker is resolved. If there are any more issues lets open new issues for them 👍
