### ISSUE TITLE
Bottom Tab Bar Icons - react-native-navigation v2

### ISSUE THREAD

**Issue by ShraddhaWankar** [wix/react-native-navigation#4047]
### Issue Description

Bottom Tab bar icons are equidistant for iOS, but not for Android after hiding the title
(https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

For Android

bottomTab:{
titleDisplayMode : 'alwaysHide'
}

For iOS

bottomTabs:{
iconInsets : {top : 5, left : 0, bottom : -5, right : 0}
}

---
### Environment
* React Native Navigation version: v2
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Both Android and iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device (Android O, iPhone 4s), Debug Build

iOS ScreenShot
![img_ios](https://user-images.githubusercontent.com/18212067/46212111-d3073680-c352-11e8-8293-ad503a0ae4aa.png)

Android ScreenShot
![img_android_footer](https://user-images.githubusercontent.com/18212067/46212127-dbf80800-c352-11e8-8b79-6f940b440d34.png)

**Comment by crushy26** [comment]
@ShraddhaWankar is the issue solved? please let me know.

**Comment by umkhan65** [comment]
I really hate this package as there is no support and has limitless limitations and bugs. I'm never using this package ever again in my life
