### ISSUE TITLE
[v2] unsetting back button title does not work

### ISSUE THREAD

**Issue by srameshr** [wix/react-native-navigation#4059]
### Issue Description

Setting the back button title or hiding the back button title does not work
### Steps to Reproduce / Code Snippets / Screenshots

```
  static options(props) {
    return {
      topBar: {
        visible: true,
        backButton: {
          title: '',
        },
      },
    };
  }
```
---
### Environment
* React Native Navigation version: 2.0.2569
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 5s simulator

**Comment by srameshr** [comment]
@guyca Could you please look into this?

**Comment by srameshr** [comment]
Can somebody from the team look at this?

**Comment by michaelcurtis** [comment]
react-native-navigation@2.0.2641
react-native@0.56.0
Platform: iOS
Device: Both iPhone X simulator and physical iPhone X

Dynamically updating the backButton title doesn't seem to work for me.
```
Navigation.mergeOptions(this.props.componentId, {
  topBar: {
    backButton: {
      title: 'some dynamic title'
    }
  }
});
```

However, updating it statically does work fine in my case.
```
static options(passProps) {
  return {
    topBar: {
      backButton: {
        title: 'some static title'
      }
    }
  };
}
```

**Comment by thinklinux** [comment]
Same on version 2.0.2637. It seems that it is an old issue.
