### ISSUE TITLE
Getting ref from generated views

### ISSUE THREAD

**Issue by witalobenicio** [wix/react-native-navigation#4062]
### Issue Description

How to get ref from generated views (e.g: toolbar, tabbars)?
Is it possible?

I would like to use `https://github.com/prscX/react-native-app-tour` but it uses refs to show the targetview.
How could I use it with RNN?

**Comment by ganlub** [comment]
Sorry to necrobump this, but did you managed to do that?

**Comment by witalobenicio** [comment]
@ganlub I wasn't able. But I recommend you to use position (x,y) to draw your tutorial view.
