### ISSUE TITLE
[V2] Hide bottomTabs on Android breaks with ScrollView

### ISSUE THREAD

**Issue by tigo0** [wix/react-native-navigation#4065]
### Issue Description

I've got a bottomTabs navigation and I navigate to a screen with `ScrollView` where I want to hide those. Based on the documentation, I am hiding them when pushing the new screen as such:
```
         Navigation.push(this.props.componentId, {
            component: {
              name: 'example.Example2',
              options: {
                topBar: {
                  title: {
                    text: 'Example screen'
                  }
                },
                bottomTabs: {
                  visible: false,
                }
              }
            }
          });
```
The bottomTabs seem to hide, but the content sizes are not re-calculated to fit the dimensions (?!) so it leaves nasty empty space the size of the bottomTabs after it.

### Steps to Reproduce / Code Snippets / Screenshots
Apply bottomTabs navigation and try to navigate to a screen where you hide those tabs on Android.

![bottomtabs android](https://user-images.githubusercontent.com/6010279/46335687-ef47f380-c630-11e8-9e97-dd1fdbecc400.gif)

---
### Environment
* React Native Navigation version: 2.0.2569 (Using `https://github.com/abdullah-sr/react-native-navigation#build` based on https://github.com/wix/react-native-navigation/pull/3851)
* React Native version: 0.57.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by ItsNoHax** [comment]
Try this:
```         Navigation.push(this.props.componentId, {
            component: {
              name: 'example.Example2',
              options: {
                topBar: {
                  title: {
                    text: 'Example screen'
                  }
                },
                bottomTabs: {
                  visible: false,
                  drawBehind:true,
                }
              }
            }
          });```

You forgot the option: drawBehind must be set to true on the screen you pushed to.
If it works, please close the issue.

**Comment by tigo0** [comment]
That worked. Don't know how I missed it. Tnx. Closing.
