### ISSUE TITLE
Better communication and help among community

### ISSUE THREAD

**Issue by beast** [wix/react-native-navigation#407]
@guyca 
I am suggesting we open a gitter or discord channel for the community to help each other.  Or possibly an official channel to provide real-time feedback for changes and such. I know this might mean more time committed but I am more than happy to contribute my time to help this great package to go further. Thanks.

**Comment by guyca** [comment]
@beast That's a great idea! Everybody is welcome to [Join us on Discord](https://discord.gg/DhkZjq2) 👍 
I'm kind of new to Discord, hung around for a while at reactiflux but couldn't keep track of all the groups and conversations so I left, but we're a smaller community so it might work for us.
I appreciate your willingness to assist! 👍

**Comment by beast** [comment]
Great! If you could put this on the github readme in the contribution section that would be great, I suggest limit the use for community discussions instead of another place for "issues".

**Comment by guyca** [comment]
Closing this since we now have a discord bade in the readme. curtesy of @brianjd 👍
