### ISSUE TITLE
[Android] Bottom tabs appearing unexpectedly on the next screen in the stack

### ISSUE THREAD

**Issue by trofima** [wix/react-native-navigation#4071]
### Issue Description

After hiding bottom tabs they are appearing on the next screen pushed to stack. This reproduces only on Android. Works fine on ios.

### Steps to Reproduce / Code Snippets / Screenshots

Hide bottom tabs on any screen using `{bottomTabs:  {visible: false, drawBehind: true}}`. Push a screen to the same stack. On ios bottomTabs will stay hidden. On android they will appear. This is inconsistent.

---
### Environment
* React Native Navigation version: 2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Android 6

**Comment by guyca** [comment]
This is the expected behavior. Options should not persist between screens in the stack.
@yogevbd please add e2e for this use case when you get to it

**Comment by trofima** [comment]
So it unexpectedly *NOT* appear on ios. In any case the current behavior is not consistent between platforms.

**Comment by yogevbd** [comment]
Fixed in 2.0.2597
