### ISSUE TITLE
[v2][Android] Hiding TopBar leaves a gap

### ISSUE THREAD

**Issue by Mikunj** [wix/react-native-navigation#4074]
### Issue Description

When you set top bar visibility to `false` it still leaves a gap instead of completely hiding like it does on iOS.

### Steps to Reproduce / Code Snippets / Screenshots

```
topBar: {
    visible: false,
}
```

You can get around it by doing the following:
```
topBar: {
    visible: true,
    height: 0,
}
```
However that is really inconvenient if you have a mix of screens with no top bar and screens with top bars. There is also a slight flicker when you do this.

---
### Environment
* React Native Navigation version: 2.0.2571
* React Native version: 0.53
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device

**Comment by Mikunj** [comment]
@guyca This isn't a question, it's a bug. On version `2.0.2555` setting the visibility of the top bar to `false` completely hides it (no gap is left), however on `2.0.2571` it hides the bar but there's still a gap left at the top.

**Comment by Aleksion** [comment]
@Mikunj You're absolutely right it's a bug! And thank you for providing a solution.
@guyca why did you close thise?

**Comment by Kyonru** [comment]
This is happening on version ^2.1.3-patch.2

**Comment by unfrgivn** [comment]
Still happening on 2.18.5 both with adding `height: 0` on my `Navigation.setRoot()` element component and also inside my individual screens, setting the options at the top:

```
static get options() {
    return {
        topBar: {
            visible: false,
            height: 0,
        }
    }
}
```

**Comment by unfrgivn** [comment]
There must be something stale, bc it happens on my emmulators even when running gradle clean and deleting/reinstalling the app, but it's not happening on my device with an alpha release installed

**Comment by EskelCz** [comment]
can confirm, still happening on android

**Comment by vemarav** [comment]
This works on android
https://github.com/wix/react-native-navigation/issues/5206#issuecomment-502053359
