### ISSUE TITLE
[v2] [iOS] Bottom tabs visible when using layout bottomTabs visible: false

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#4076]
### Issue Description

Can't hide bottomTabs using layout bottomTabs
It is visible on first tab and when I switch tab only then it will disappear.

```
  Navigation.setRoot({
    root: {
      bottomTabs: {
        children: [
...          
        ],
        options: {
          bottomTabs: {
            visible: false,
            animate: false,
            drawBehind: true
          }
        }

      }
    }
  });
```

### Steps to Reproduce / Code Snippets / Screenshots

Use  
```
options: {
          bottomTabs: {
            visible: false,
            animate: false,
            drawBehind: true
          }
        }
```
inside bottomTabs layout

---
### Environment
* React Native Navigation version: 2.0.2570
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by rendomnet** [comment]
Any updates on this issue?

**Comment by michellmorso** [comment]
im experiencing this as well
