### ISSUE TITLE
[V2][iOS] Going back in stack does not set the title color properly

### ISSUE THREAD

**Issue by Jazqa** [wix/react-native-navigation#4079]
### Issue Description

Going back in stack does not set the title color properly on iOS (broken after the fix for styling the iOS backbutton)

### Steps to Reproduce / Code Snippets / Screenshots

1. Have a stack navigator where the first screen has `static get options()` and `topBar.title.color: blue`
2. Push a screen with `static get options()` and `topBar.title.color: red`
3. Pop the screen with red title and the previous screen will have a red title too

---
### Environment
* React Native Navigation version: 2.0.2571
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, 11.4, Debug

**Comment by SparkleFaerieCoder** [comment]
Same here for v1

**Comment by SparkleFaerieCoder** [comment]
@yogevbd Will this be addressed for v1 as well?

**Comment by Jazqa** [comment]
Related to the V2 issue. If you navigate back in stack (to the root of the stack) by pressing the bottomTab icon, this works fine.

**Comment by Jazqa** [comment]
Going back with the popGesture (swipe) also works fine. The issue is only present when using the backButton on the topBar.

**Comment by yogevbd** [comment]
Fixed in `2.0.2585`.
@SparkleFaerieCoder We currently do not address issues for v1 so we can focus on v2

**Comment by hellotoby** [comment]
@SparkleFaerieCoder - This usually occurs in v1 when the previous screen doesn't have a navigatorStyle applied to it (in our case the navBar was hidden so we hadn't applied any navigatorStyles to it). You can fix in v1 by applying the same navigator style as the current screen to the screen that you are swiping back to.
