### ISSUE TITLE
It's not working on Android 4.4 (KitKat) and below

### ISSUE THREAD

**Issue by JuneDomingo** [wix/react-native-navigation#408]
I don't know if i'm missing something with the documentation, I tried to run it with lower version of Android and the app didn't work.

**Comment by guyca** [comment]
@JuneDomingo I'm not aware of any issues running on API <= 19.

**Comment by Alireza1619** [comment]
I have same problem.
I tested [movie app](https://github.com/JuneDomingo/movieapp) which uses RNN and it worked on 4.4.4.

**Comment by JuneDomingo** [comment]
Hi @Alireza1619 , it should work as I already [fix](https://github.com/JuneDomingo/movieapp/commit/c51fc3ac9e9fb116882ae7f4f2d46f5b910b58f5) this.
What particular error  message do you encounter?
