### ISSUE TITLE
[V2][iOS] drawBehind not working after merging options

### ISSUE THREAD

**Issue by Jazqa** [wix/react-native-navigation#4080]
### Issue Description

transparent and/or translucent topBar with `drawBehind: true` does not allow drawing behind it after merging options (for example topBar title color or disabling a topBar button). Broken after 2.0.2570.

### Steps to Reproduce / Code Snippets / Screenshots

1. Have a topBar with `{ drawBehind: true, background: { color: "transparent", translucent: true } }`
2. Try to merge options (for example, disable left button or change text color)
3. View moves down by the height of the topBar, because drawing under topBar is not possible

---
### Environment
* React Native Navigation version: 2.0.2571
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, 11.4, Debug

**Comment by stokesbga** [comment]
I was able to reproduce this with an animated flatlist, noticing that the containerLayout was pushed down, but the actual top level flexbox had no issue and took up the full screen.

**Comment by yogevbd** [comment]
Do you use sideMenu in your layout? I'm trying to understand if this bug related to this fix: b840dd4181cb8d5512185123a4e0be466071be05

**Comment by Jazqa** [comment]
@yogevbd, no I don't. We don't use sideMenu at all.

**Comment by Jazqa** [comment]
@yogevbd, this has been working again after 2.0.2576.
