### ISSUE TITLE
[IOS] bottomTabs drawBehind: true bug

### ISSUE THREAD

**Issue by trofima** [wix/react-native-navigation#4082]
### Issue Description

Setting `bottomTabs: {visible: false, drawBehind: true}` resulting the view 'jump' behind the topBar

### Steps to Reproduce / Code Snippets / Screenshots

render usual <View> (not flex: 1) with some content and set statically 
`bottomTabs: {visible: false, drawBehind: true}`

---
### Environment
* React Native Navigation version: 2
* React Native version:
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): simulator iphone X

**Comment by yogevbd** [comment]
Fixed here: 6426d74ed8d60f70e4a3b8ef9d88a6eb2cf1faf9
Can you please approve? thanks
