### ISSUE TITLE
[V2][Android] setDefaultOptions not effective in initial setRoot

### ISSUE THREAD

**Issue by jinshin1013** [wix/react-native-navigation#4085]
### Issue Description
The initial, the very first screen does not get affected by the style set in `Navigation.setDefaultOptions`. 

### Steps to Reproduce / Code Snippets / Screenshots
My `app.ts`
```
Navigation.events().registerAppLaunchedLIstener(() => {
  // mobx-persist hydrate
  hydrateStores()
    .then((store) => {
      // use store to decide the root to render
     const root = store.root.....
      
     Navigation.setDefaultOptions({
       topBar: { elevation: 0 }
     })
     
     registerScreens() // register all screens

     Navigation.setRoot({
        root: {
          stack: {
            children: [{
              component: { name: root }
            }]  
          }
        }
      })
    })
})
```

The very first root screen still renders with topBar elevation however as soon as React Native reloads or pushed to the next screen, the style suddenly comes in effect.

---
### Environment
* React Native Navigation version: 2.0.2571
* React Native version: 0.56.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Android 7, Debug/?Release

**Comment by yusufyildirim** [comment]
Kinda related to #4034
