### ISSUE TITLE
Wierd transition on screen push

### ISSUE THREAD

**Issue by sexykodo** [wix/react-native-navigation#409]
Hi there, 
i'm working on Android navigation and i'm having a trouble pushing a screen from a tabbed screen to non tab screen.

It seems to me that happens in 2 steps:
1- tabBar toggle
2- screen push

Problem is that during the tabBar toggle (quite slow), I see the app background (white).
Is there a way to cut this toggle animation during the push?
is there at least a way to change the nativeview background color?

<img width="407" alt="screen shot 2016-11-02 at 13 31 58" src="https://cloud.githubusercontent.com/assets/7148528/19928867/cb32d08e-a100-11e6-8f07-1f06ef577da6.png">

<img width="408" alt="screen shot 2016-11-02 at 13 32 08" src="https://cloud.githubusercontent.com/assets/7148528/19928873/cd85673e-a100-11e6-9e5a-4c95411565e2.png">

Additional question: is it default behaviour on android to have unselected tabs with hidden label? is there a way to change it?

* React Native Navigation version:0.35
* React Native version: 2.0.0-experimental.136 (same on previous versions)
* Platform: ANDROID
* Device info (Device - Debug)

**Comment by guyca** [comment]
@sexykodo To show BottomTabs titles, add `appStyle` element when you start your app.

```js
  Navigation.startTabBasedApp({
    ...
    appStyle: {
      forceTitlesDisplay: true
    }
  });
```

Regarding the push animation issue. I suggest you define `drawUnderNavBar: true` in the first screen. This way, when you push the second screen you won't see the white background during the BottomTabs hide animation.

**Comment by sexykodo** [comment]
@guyca 
forceTitlesDisplay: true
 works great!

starting screen already has property  "drawUnderNavBar: true" but doesn't seem to work 
(pretty much like drawUnderNavBar: true )

**Comment by guyca** [comment]
Ok I'll look into it. Thanks for reporting

**Comment by guyca** [comment]
@sexykodo I meant `drawUnderTabBar`

**Comment by sexykodo** [comment]
@guyca  yes i misstypes, both drawUnderTabBar and drawUnderNavBar don't work

**Comment by sexykodo** [comment]
@guyca i pulled last version and checked for

```
if (params.bottomTabsColor.hasColor()) {
            setBackgroundColor(params.bottomTabsColor);
        }
```

root screen has  "tabBarBackgroundColor: '#181818' " set but transition is still the same

**Comment by guyca** [comment]
@sexykodo
Where is `drawUnderTabBar` defined?
Do you have both `static navigatorStyle` and `navigatorStyle` defined in the that tab declaration? (I hope I'm clear 😞)

**Comment by sexykodo** [comment]
@guyca you're quite clear :)  and thanks for the support!
drawUnderTabBar is defined as static on my pushed screen and works fine.
The root screen (tabbed) doesn't drawunder as espected. The problem is during the transition itself, tabs disapper with animation before the push make visible the empty portion of the view

**Comment by guyca** [comment]
No problem.
I noticed there's a problematic behaviour when defining `navigatorStyle` both statically and in tab declaration. The static `navigatorStyle` gets overridden and not merged.

You should set `drawUnderTabBar` on the root screen. make sure you have a single `navigatorStyle` just to be on the safe side.
