### ISSUE TITLE
[V2][iOS] SearchBar missing tint color options + can't change Cancel text color

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#4093]
### Issue Description

- Using the native SearchBar I can not change the color of the Search... background. In my app it has become Dark Blue and I don't know where to change it. Same goes for the Cancel text next to it.

### Steps to Reproduce / Code Snippets / Screenshots

![file](https://user-images.githubusercontent.com/4223434/46475709-8dc98580-c7e6-11e8-9762-a27d0d68a4fb.jpg)

---
### Environment
* React Native Navigation version: 2572
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device + Simulator

**Comment by ericlewis** [comment]
https://github.com/wix/react-native-navigation/pull/4055

**Comment by chrise86** [comment]
@ericlewis I may be wrong but it looks like your PR sets [tintColor](https://developer.apple.com/documentation/uikit/uisearchbar/1624286-tintcolor), not [barTintColor](https://developer.apple.com/documentation/uikit/uisearchbar/1624295-bartintcolor) which would change the background.

**Comment by brenwell** [comment]
Can this be reopened that would be awesome!! Thanks

**Comment by kgaspar** [comment]
Have the same problem, has anyone found a solution for this?

**Comment by jjbeach** [comment]
@kgaspar i had to get under the ol' hood and tweak it myself:
Just after line 49 in the _UiViewController+RNNOptions.m_  file (located in ReactNativeNavigation.xcodeproj), I added
`search.searchBar.tintColor = [UIColor colorWithRed:0.59 green:0.59 blue:0.59 alpha:1.0];` 
and was able to successfully alter the color of the cancel button

**Comment by prathammehta** [comment]
If you don't want to mess with the code of RNN you could just add this line of code to your `AppDelegate.m` file in the `didFinishLaunchingWithOptions` method:

```
[[UISearchBar appearanceWhenContainedInInstancesOfClasses:@[[UIViewController class]]] setTintColor:[UIColor
                                                                                                       colorWithRed:245.0/255.0
                                                                                                       green:166.0/255.0
                                                                                                       blue:34.0/255.0
                                                                                                       alpha:1.0]];
```
Add any `UIColor` you like. :)

**Comment by kgaspar** [comment]
@jjbeach Thanks for the help, I implemented the tintColor and the button looks good now. Have you managed to change the barTintColor? To change the color of the Search Bar Background. R

**Comment by kgaspar** [comment]
Hi I managed to make the Search Bar background white with this code, added under @jjbeach solution

`search.searchBar.barTintColor = UIColor.whiteColor;
			
			UITextField *txfSearchField = [search.searchBar valueForKey:@"_searchField"];
			txfSearchField.tintColor=[UIColor colorWithRed:21/255.0 green:157/255.0 blue:130/255.0 alpha:1];
			txfSearchField.textColor=[UIColor colorWithRed:1 green:1 blue:1 alpha:1];
			txfSearchField.backgroundColor=[UIColor whiteColor];
			UIView *backgroundview= [[txfSearchField subviews]firstObject ];
			backgroundview.backgroundColor=[UIColor whiteColor];
			
			backgroundview.layer.cornerRadius = 8;
			backgroundview.clipsToBounds = true;`

**Comment by witalobenicio** [comment]
Not stale

**Comment by guyca** [comment]
@yogevbd Seeing that #4055 was abandoned, lets add `searchBarBackgroundColor: true|false` and `searchBarKeyboardStyle: 'dark'|'light'`

**Comment by Alw3ys** [comment]
@guyca Will this include the cancel button color?

**Comment by Eldavid** [comment]
Are you planning to implement this feature in the future?

**Comment by arashkevich25** [comment]
Any updates ?

**Comment by 3luyka** [comment]
@guyca hey, any updates on that?

**Comment by mrousavy** [comment]
Does https://github.com/wix/react-native-navigation/commit/d50e4bf62990c12318f369e077eb8414cc3e52d4 solve this issue?

**Comment by guyca** [comment]
@mrousavy Seems like the commit you've linked and @mateioprea's PR will resolve this issue.
