### ISSUE TITLE
Could not find a declaration file for module 'react-native-navigation'

### ISSUE THREAD

**Issue by awaqo** [wix/react-native-navigation#4097]
### Issue Description

[ts]
Could not find a declaration file for module 'react-native-navigation'. '(directory)f:/SEKOLAH/XIRPL3/KK4/react/hello8/node_modules/react-native-navigation/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-navigation` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-navigation';(https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

![image](https://user-images.githubusercontent.com/37984552/46569912-85a84c00-c986-11e8-9def-7eb4c9d2fce3.png)
![image](https://user-images.githubusercontent.com/37984552/46569926-b7b9ae00-c986-11e8-87b2-4cdd259cab9c.png)

---
### Environment
* React Native Navigation version: ^1.1.487
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Redmi 4a 7.1.2

**Comment by nitish8750** [comment]
Same here

**Comment by torigeorge** [comment]
I am having the same issue. Did anyone get the fix?

**Comment by HemanthNGovindan** [comment]
Issue still exist

**Comment by yogeshmishrikotkar** [comment]
Issue still exist

**Comment by IgorMing** [comment]
Issue still exist for me as well

**Comment by asmi77** [comment]
Same here.

**Comment by christiandave090697** [comment]
solution anyone?

**Comment by mazzulli** [comment]
I have the same problem.

**Comment by knastordin** [comment]
Still have this problem

**Comment by zerkshaban** [comment]
I am facing the same issue.

**Comment by shravyaramesh** [comment]
I have the same issue for a different package though

**Comment by tim92109** [comment]
Same issue.  Doesn't seem to 'break' anything in the navigation so maybe it can be ignored?  Not using TS.

**Comment by Linuhusainnk** [comment]
Same issue in case of using SearchableDropdown 
any solution

**Comment by akhzarna** [comment]
Same issue in case of 'react-native-animated-loader'.

**Comment by PR4V33N-droid** [comment]
It's year 2022, still facing the same issue in case of using SearchableDropdown.
