### ISSUE TITLE
showModal showing transparent screen. How to disable it from showing transparent background ?

### ISSUE THREAD

**Issue by manojkumawat003** [wix/react-native-navigation#4098]
I am using showModal and it is working fine but this is showing transparent screen.
I tried backgroundColor:'#ffffff' but, it still showing transparent.

How to disable transparancy?

---
### Environment
* React Native Navigation version: 1.1.486
* React Native version: 0.55.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): simulator,8.0

**Comment by AdamLee321** [comment]
Did you find a solution because I have the same problem.
