### ISSUE TITLE
Overrride default back functionality in v2

### ISSUE THREAD

**Issue by crushy26** [wix/react-native-navigation#4102]
### Issue Description

Please provide an option to override default back functionality for a component. In my case I want to handle the back button to take current tab to home.

---
### Environment
* React Native Navigation version: v2
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): Android

**Comment by ogostus** [comment]
use the BackHandler of RN to handle backPress, and a navigation leftButton for the back button

**Comment by Jazqa** [comment]
@ogostus solution is not enough, since we can not stop the default behavior of Android's hardware back button.

**Comment by rendomnet** [comment]
Any updates on this?

**Comment by Jazqa** [comment]
Found a workaround. If you user React Native's BackHandler and wrap the functionality in a `await setTimeout(/* YOUR BACK FUNCTIONALITY */, 1)`, React Native Navigation's back functionality seems to be overwritten.

**Comment by spacesuitdiver** [comment]
To clarify @Jazqa's answer. Just be sure you register an event that returns "true". Below would work fine in a root level screen.

```
    componentDidMount() {
        BackHandler.addEventListener('hardwareBackPress', this.handleHardwareBackPress);
    }

    componentWillUnmount() {
        BackHandler.removeEventListener('hardwareBackPress', this.handleHardwareBackPress);
    }

    handleHardwareBackPress = () => {
        return true;
    };
```
