### ISSUE TITLE
[V2] React Native Sentry not send errors on registered component - Android

### ISSUE THREAD

**Issue by mammad2c** [wix/react-native-navigation#4108]
Hi
### Issue Description
React Native Sentry not reporting errors on registered components. for example if I call a function and it is not exist, throw undefined is not a function but no logs in sentry server. but outside of component (a function logic or in index.js root) if throw error, sentry show it on server.

### Steps to Reproduce / Code Snippets / Screenshots
```
class Hello extends React.Component {
render(){
     return <View onPress={this.hello}><Text>Hello</Text></View>
}
}
```

if I press on the 'Hello', React Native throw error because undefined is not a function. But no error logs in sentry :)

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android 5.1, Android 6.0, on device and emulator.

**Comment by dozoisch** [comment]
@mammad2c are you sure react-native throws an error? Normally if an onPress has an undefined, it doesn't call it at all. Try with `() => this.hello()`
