### ISSUE TITLE
registerBottomTabSelectedListener does not fire callback on tab change

### ISSUE THREAD

**Issue by rishabhpoddar** [wix/react-native-navigation#4109]
### Issue Description

Navigation.events().registerBottomTabSelectedListener(someFunc) does not fire someFunc when tabs are changed. My code is below (I am using Typescript. But that should have no effect on this discussion):

```js

    constructor(props: any) {
        super(props);
        this.eventSubscription = Navigation.events().registerBottomTabSelectedListener(this.tabChanged);
    }

    tabChanged = (info: { selectedTabIndex: number, unselectedTabIndex: number }) => {
        this.props.onBottomTabChanged(info.selectedTabIndex);
    }

    componentWillUnmount() {
        this.eventSubscription.remove();
        super.componentWillUnmount();
    }
```

---
### Environment
* React Native Navigation version: 2.0.2577
* React Native version: 0.53.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device, 12.0.0, Debug

**Comment by rishabhpoddar** [comment]
I think I may have solved the issue. But i am not sure:
Added "self.delegate = self;" in function initWithLayoutInfo in RNNTabBarController.m

**Comment by jcsena** [comment]
@rishabhpoddar  this is correct.
