### ISSUE TITLE
[v2] Missing getCurrentlyVisibleScreenId()

### ISSUE THREAD

**Issue by replecta** [wix/react-native-navigation#4111]
I'm using quick action shortcut module and i need to know what screen is currently being shown otherwise i wouldn't know if the modal that i'm trying to show from quick action is already being shown on the screen.

---
### Environment
* React Native Navigation version: 2.0.2556
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by guyca** [comment]
You'll need to track screen visibility yourself using a [componentDidAppear listener](https://wix.github.io/react-native-navigation/v2/#/docs/events?id=componentdidappear)

```js
Navigation.events().registerComponentDidAppearListener(({ componentId, componentName }) => {

});
```

**Comment by zFadil995** [comment]
@guyca could you please update your link to the listener (just remove the v2) so people who run into this in the future don't run into a 404?

**Comment by guyca** [comment]
Of course 👍
