### ISSUE TITLE
Can't see app on iPhoneX, XS, XSMAX

### ISSUE THREAD

**Issue by eladgel** [wix/react-native-navigation#4119]
### Issue Description

AppLayout on iPhone x family not working, upgraded from V1 to V2, can see my app on iPhone 8 plus, iPhone 8, iPhone 7...
I See a black screen on iPhone X, XS, XSMAX, XR

### Steps to Reproduce / Code Snippets / Screenshots

I've followed the steps on the v1-v2 bridge page.

**index.ios.js**
``` 
/**
 * @flow
 */
'use strict';
console.log('APP ENTRANCE');
import React from 'react';
let App = require('./App/App');
const app = new App();`
```
**App.js**
```
/**
 * @flow
 */
'use strict';
import registerScreens from "./Screens/index";
import React, {Component} from "react";
import {Platform} from "react-native";
import AppController from "./Controllers/App/AppController";
import {
    Navigation,
    ScreenVisibilityListener
} from "react-native-navigation-v1-v2-adapter";
let Globals = require('./Utils/Globals');

registerScreens();
let {
    HBPreferences,
} = require('NativeModules');

class App extends Component {
    constructor(props) {
        super(props);

        Globals.IS_SIMULATOR = Platform.OS === 'ios' ? HBPreferences.isSimulator : false;
        Globals.IS_DEBUG = Platform.OS === 'ios' ? HBPreferences.isDebug : false;
        Globals.IS_PROD_ENV = Platform.OS === 'ios' ? HBPreferences.isProdEnv : false;
        this._appController = AppController.instance;

        console.log("**** STARTING A NEW APP SESSION ****");
        this._appController.startApp();

    }
}

module.exports = App;
```

---
### Environment
* React Native Navigation version: 2.0.2577
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by barees63** [comment]
try 2.0.2555  - the latest release is broken for me on iPhone X, just a black screen.. going back to the older version fixed it (I haven't tried any other versions).

**Comment by ItsNoHax** [comment]
Closing issue as this is no longer a problem.

**Comment by dobrynia** [comment]
@ItsNoHax `2.0.2555` is the latest version I was able to run the app on the iPad. With newer versions I see only a black screen and nothing else. I think this is a bug, because at the same time on the iPhone 6s it's all right.
