### ISSUE TITLE
Does this module work with RN 0.36

### ISSUE THREAD

**Issue by jrmcdona** [wix/react-native-navigation#412]
Just wanted to check.  I was having some issues with my project so I upgraded to .36 and getting an error now that I was not before.    Loaded a screenshot of what I am seeing. 
Just wanted to check with you all!

<img width="264" alt="screen shot 2016-11-03 at 8 24 51 pm" src="https://cloud.githubusercontent.com/assets/4327773/19991498/c18a4144-a203-11e6-8446-0a04214782e7.png">

**Comment by beast** [comment]
Check your app delegate. RN upgrade modifies quite a bit of your project structure, you really should check your linking again after every upgrade

**Comment by DanielZlotin** [comment]
works in `^2.0.0-experimental.141`
