### ISSUE TITLE
[v2] Value 'xxxxx' doesn't fit into a 32 bit signed int

### ISSUE THREAD

**Issue by CedricZhang** [wix/react-native-navigation#4120]
### Issue Description
When try to parse a JSON with a large integer (say, a millisecond timestamp) on Android, the app will crash with error "Value xxxxx doesn't fit into a 32 bit signed int"

### Steps to Reproduce / Code Snippets / Screenshots

---
Not 100% sure, but I think it has something to do with [THIS](https://github.com/wix/react-native-navigation/commit/0519602f3f5dae285bf8c6fcdd0f82d1bf6439c6) commit.
#3960 

The code of `parseNumber()` should be something like 
``` java
try {
        //getInt()
} catch (Exception e) {
        return map.getDouble(key);
}

```
but now its

``` java
try {
       //getInt()
} catch (Exception e) {
      return map.getInt(key);
 }
```
---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
Which option are you passing a large number to?
