### ISSUE TITLE
 [v2] Headless JS and react-native-navigation

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#4121]
### Issue Description
Can we use  Headless JS with react-native-navigation [v2]?

Android allows you to act on data-only messages when your application is closed or running in the background. This is particularly useful if you'd like to be able to show heads-up notifications to your user. To allow this to work, we make use of React Native's built-in Headless JS functionality.

bgMessaging.js
```
// @flow
import firebase from 'react-native-firebase';
// Optional flow type
import type { RemoteMessage } from 'react-native-firebase';

export default async (message: RemoteMessage) => {
    // handle your message

    return Promise.resolve();
}
```
index.js
`AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessaging);`

### Steps to Reproduce / Code Snippets / Screenshots

https://rnfirebase.io/docs/v5.x.x/messaging/receiving-messages#4)-(Optional)(Android-only)-Listen-for-FCM-messages-in-the-background

---
### Environment
* React Native Navigation version:  2.0.2578
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by Dimasik911** [comment]
@rendomnet, how you managed to make it work?

**Comment by saadqbal** [comment]
Hey @rendomnet , did you find any solution for this?

**Comment by shivangp** [comment]
@rendomnet @saadqbal Can we reopen this issue if there isn't a solution?

**Comment by WASHSWATDAVID** [comment]
Is there any solutions?

**Comment by WASHSWATDAVID** [comment]
I got the solution myself. this codes works for me.


```
import { AppRegistry,Platform :{OS} } from 'react-native';
import { Navigation } from 'react-native-navigation';
if(OS === 'android'){
  AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessaging);
}
Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setDefaultOptions({
    // popGesture: false,
    topBar: {
      visible: false,
      _height: 0,
      drawBehind: true
    }
  });
  Navigation.setRoot({
    root: {
      id: 'App',
      stack: {
        children: [
          {
            component: { name: 'Splash' }
          }
        ]
      }
    }
  });
});

```

**Comment by diolegend** [comment]
doesn't works for me, how can i fix?

**Comment by johanschram** [comment]
Any updates on this ?

**Comment by vstukanov** [comment]
I had the same issue and root cause was that message wasn't high priority.
