### ISSUE TITLE
iPhone XR XS,navigationbar height issue

### ISSUE THREAD

**Issue by jeffzing** [wix/react-native-navigation#4124]
### Issue Description
(iPhone X)
![2018-10-11 3 52 32](https://user-images.githubusercontent.com/12021460/46788950-eb714b00-cd6d-11e8-981e-3e43cae29c39.png)
(iPhone XR XS)
![2018-10-11 3 52 24](https://user-images.githubusercontent.com/12021460/46788959-f035ff00-cd6d-11e8-8275-af17c1f74136.png)

---
### Environment
 "react-navigation": "^2.11.2"
 "react": "16.4.1",
"react-native": "^0.56.0",
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): XR XS XS MAX

**Comment by jeffzing** [comment]
any new version?

**Comment by jeffzing** [comment]
now I see the problem located at react-native/React/Modules/RCTDeviceInfo.m,

**Comment by jeffzing** [comment]
just make sure your code looks like the code below:
static BOOL RCTIsIPhoneX() {
   static BOOL isIPhoneX = NO;
   static dispatch_once_t onceToken;

   dispatch_once(&onceToken, ^{
     RCTAssertMainQueue();

     CGSize screenSize = [UIScreen mainScreen].nativeBounds.size;
     CGSize iPhoneXScreenSize = CGSizeMake(1125, 2436);
     CGSize iPhoneXMaxScreenSize = CGSizeMake(1242, 2688);
     CGSize iPhoneXRScreenSize = CGSizeMake(828, 1792);

     isIPhoneX =
       CGSizeEqualToSize(screenSize, iPhoneXScreenSize) ||
       CGSizeEqualToSize(screenSize, iPhoneXMaxScreenSize) ||
       CGSizeEqualToSize(screenSize, iPhoneXRScreenSize);
   });

   return isIPhoneX;
}

**Comment by GitHubGreg** [comment]
Thanks very much Jeff. After making the change, do you happen to know if I need to do something else to have the change take effect (I am using Expo). Thanks again.
