### ISSUE TITLE
Is it stable enough to use in production?

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#413]
Hey guys, 
I plan to use this library on a production project, is it stable enough to do so? 
I don't need anything special, for starters just a regular navigation bar with left and right buttons working both on Android and iOS would do.

I'm a bit worried because I've used lot's of open-source projects in the past, and I've found myself trapped in the endless pit hole of unresolved issues whenever things went bad.

I guess all I need is some reassurance, are there any other people using this in production.

**Comment by DanielZlotin** [comment]
While the API is not stable in terms of changes (until the official release of v 2.0.0), in terms of runtime stability it is very stable.
A good indicator to this is that the Wix.com app (both Android and iOS) is built around `react-native-navigation` with 100's of thousands of downloads worldwide and an almost zero crash rate.
