### ISSUE TITLE
[v2] different behavior between iOS 10 & 11 when using drawBehind

### ISSUE THREAD

**Issue by omar-dev** [wix/react-native-navigation#4132]
### Issue Description

Different behavior between iOS 10 & 11 when using drawBehind

iOS 10
<img width="296" alt="iOS 10" src="https://user-images.githubusercontent.com/6189654/46905614-0f17cb00-ceff-11e8-8408-aaf021a7ad82.png">

iOS 11.4
<img width="300" alt="iOS 11.4" src="https://user-images.githubusercontent.com/6189654/46905635-4c7c5880-ceff-11e8-9d52-fb89522a8cc3.png">

### Steps to Reproduce / Code Snippets / Screenshots

```js 
Navigation.push(componentId, {
    component: {
      name: "Screen",
      options: {
        layout: {
          backgroundColor: "#ffffff",
          orientation: ["portrait"]
        },
        bottomTabs: {
          visible: false,
          drawBehind: true,
          animate: true
        },
        topBar: {
          background: {
            color: "transparent",
            translucent: true,
           
          },
          borderColor: "transparent",
          elevation: 0,
          borderHeight: 0,

          drawBehind: true,
          backButton: {
            title: ""
          },
          rightButtons: [
            {
              id: "SHARE",
              icon: require("../../images/share.png")
            },
            {
              id: "Fav",
              component: {
                name: "FavButtonScreen",
                passProps: {
                  product_id: product.product_id
                }
              }
            }
          ],
          buttonColor: 'black'
        }
      }
    }
  });
```
---
### Environment
* React Native Navigation version: 2.0.2581
* React Native version: 0.56 & 0.57
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device

**Comment by omar-dev** [comment]
This is still an issue.

**Comment by thielCole** [comment]
@omar-dev I am also seeing this issue, will provide a screenshot when I can.

**Comment by omar-dev** [comment]
This is still an issue.

**Comment by omar-dev** [comment]
This is still an issue.

**Comment by SudoPlz** [comment]
I'm experiencing the same issue..
