### ISSUE TITLE
Custom icon component for icons on bottom tabs

### ISSUE THREAD

**Issue by KostyaGr** [wix/react-native-navigation#4133]
Hi everyone! I want to use custom icon components for bottom tab icons.

`...
options: {
                bottomTab: {
                  text: 'Tab#1',
                  icon: <CustomComponent/>
                }
              }
...
`
This doesn`t work. Help

---
### Environment
* React Native Navigation version: 2.0.2581
* React Native version: 0.57.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by maulikdhameliya** [comment]
![image](https://user-images.githubusercontent.com/12501230/48470264-f741a880-e816-11e8-9c54-f0fa51c07025.png)
is there any possibility to add image in bottom tab bar?

**Comment by maulikdhameliya** [comment]
@guyca 
Hi, I have my profile tab in the bottom bar and I want to add currently login user's photo in the bottom bar. is it supported to have images in bottom bar.

![image](https://user-images.githubusercontent.com/12501230/48470388-4d165080-e817-11e8-83a7-b31f45cd40bc.png)

**Comment by nickrobinson352** [comment]
I have gotten this to work using react-native-action-button. I just had to implement an empty space in the bottom tab and permanently float this button there.

**Comment by anuraginwadi** [comment]
any update on this?

**Comment by valery-kuzmenko** [comment]
@guyca Could you please suggest a way or direction how to use custom components for bottom tabs menu ?
