### ISSUE TITLE
[V2 ] modalPresentationStyle prop is not working on showModal

### ISSUE THREAD

**Issue by hisothreed** [wix/react-native-navigation#4134]
### Issue Description

Presenting modal with transparent background with custom using modalPresentationStyle is not working properly, it was working two weeks ago

### Steps to Reproduce / Code Snippets / Screenshots
```
this.props.navigation.showModal({
      component: {
        name: Screens.SortFiltersScreen,
        passProps: {
          source: "Home",
          onResultRequest: this._presentBusinessesList
        },
        options: {
          modalPresentationStyle:
            "overFullScreen" // try any other style, all the same result 
        }
      }
    })
```
---
### Environment
* React Native Navigation version: 0.55.4
* React Native version: 2.0.2581
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by pribeh** [comment]
Yes, others are experiencing the same using:

```
layout: {
          backgroundColor: 'transparent',
      },
      screenBackgroundColor: 'transparent',
      modalPresentationStyle: 'overCurrentContext',
```

See: https://github.com/wix/react-native-navigation/issues/3413#issuecomment-429538465

**Comment by pribeh** [comment]
Amazing

**Comment by smooJitter** [comment]
@pribeh can you post a sample of your code?  I'm still having problems with this.

**Comment by guyca** [comment]
@ywongweb Can you please PR a layout where this breaks to the playground app? Possible to `modal.js`

**Comment by ywongweb** [comment]
@guyca 
My bad. It is working on iOS 2.0.2623

Sample code:
```
    Navigation.showModal({
      component: {
        name: 'modal121',
        id: 'myModal',
        options: {
          layout: {
            backgroundColor: 'rgba(0,0,0,0.9)',
          },
          modalPresentationStyle: 'overCurrentContext',
        },
      },
    })
```

**Comment by pribeh** [comment]
@ywongweb have you tried the following?
```
static options() {
  return {
    layout: {
      backgroundColor: 'transparent',
  },
  screenBackgroundColor: 'transparent',
  modalPresentationStyle: 'overCurrentContext',
  };
}
```

**Comment by tobias-leinss** [comment]
I am on rnn 2.1.2 (if that is really the latest) and 

layout: {
                backgroundColor: 'transparent' or the appropriate color
}
does it for me. Thanks @pribeh

**Comment by adybuciuman** [comment]
If I set 
```
 Navigation.showModal({
    component: {
      name: SCREENS.Feedback,
      id: SCREENS.Feedback,
      passProps: { isModalScreen: true },
      options: {
        layout: { backgroundColor: 'transparent' },
        screenBackgroundColor: 'transparent',
        modalPresentationStyle: 'overCurrentContext',
      }
    }
  });
```
this crash happens

![image](https://user-images.githubusercontent.com/12176091/62280883-69195b00-b455-11e9-8b4d-b6afbe9676f2.png)

**Comment by emilioheinz** [comment]
@adybuciuman You can use `overFullScreen` instead of `overCurrentContext`.

**Comment by TimonSotiropoulos** [comment]
@emilioheinz thanks for solving this, just a note that the docs on the website on Modals actually still say to use 'overCurrentContext' ->

https://wix.github.io/react-native-navigation/docs/modal

Probably why people (like me) are still running into this issue =D

**Comment by emilioheinz** [comment]
> @emilioheinz thanks for solving this, just a note that the docs on the website on Modals actually still say to use 'overCurrentContext' ->
> 
> https://wix.github.io/react-native-navigation/docs/modal
> 
> Probably why people (like me) are still running into this issue =D

Sorry but I'm not able to access the link provided in your comment.
