### ISSUE TITLE
V2 installing documentation 

### ISSUE THREAD

**Issue by barjas** [wix/react-native-navigation#4136]
### Issue Description

installing documentation is not clear at all. how to start tab app .. not clear at all.

please add some steps by step on how to install and use 

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by jinshin1013** [comment]
[Start by setroot](http://wix.github.io/react-native-navigation/v2/#/docs/top-level-api?id=setrootlayout)

[Different Layouts](http://wix.github.io/react-native-navigation/v2/#/docs/layout-types)

I give you that documentation doesn't have a specific page to tell you an instruction to go from installing to start tab app, but if you invest a little time on the documentation, you will find most of info you need to get started.
