### ISSUE TITLE
Top Bar gets drawn behind status bar (v2)

### ISSUE THREAD

**Issue by djschilling** [wix/react-native-navigation#4139]
### Issue Description

I want to have a status bar and a top bar.
But when i use both the top bar gets drawn behind the status bar and half the text is not visible.
I tried to set `drawBehind` in `statusBar` and `topBar` to `false`. But this had no effect.

### Steps to Reproduce / Code Snippets / Screenshots

![bildschirmfoto 2018-10-15 um 11 31 10](https://user-images.githubusercontent.com/3503166/46942687-27f2be80-d06e-11e8-87fb-454a1d890feb.png)

---
### Environment
* React Native Navigation version: 2.0.2582
* React Native version: 0.57.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Simulator

**Comment by starzle** [comment]
Also see the same issue. It works normally before 2.0.2578.

**Comment by guyca** [comment]
Does this reproduce in the playground app?

**Comment by LRNZ09** [comment]
I can confirm this is also happening in version 2.0.2620, I've just upgraded and it never happened before.

**Comment by davidwico** [comment]
Any solution for this?

**Comment by LRNZ09** [comment]
Still happening for me with 2.1.3, I think the problem is caused by bottomTabs layout.

**Comment by Rana-Muhammad-Amir** [comment]
Just set the "drawBehind:false" in statusBar it should be fix...like below
i think you set drawBehind:true due to why this is  happening.... @davidwico 

 options: {
        statusBar: {
        visible: true,
       drawBehind: false,
         },
     topBar: {
     visible: true,
     drawBehind: false,
     animate: true,
      }
    }

**Comment by icekev** [comment]
After trying to rollback to earlier versions, trying around each parameters of Drawing behind or not, adding top margins to the layout and STILL it drew behind, I realized I had this part in my view

` <StatusBar translucent={true} backgroundColor={this.props.color} />`
Please note that if you have this option, this basically removes whatever RNN is trying to do as it will make that bar draw behind... So all I had to do to get this working : 

` <StatusBar translucent={false} backgroundColor={this.props.color} />`

**Comment by LRNZ09** [comment]
Related issue with bug replicated in a repo https://github.com/wix/react-native-navigation/issues/4605
