### ISSUE TITLE
bottomTabs backgroundColor not working

### ISSUE THREAD

**Issue by jp928** [wix/react-native-navigation#4148]
Reproduce:

use style as below:

```js
bottomTabs: {
        visible: true,
        animate: false,
        // currentTabIndex: 0,
        // currentTabId: 'currentTabId',
        testID: 'bottomTabsTestID',
        drawBehind: false,
        backgroundColor: 'white',
        fontSize: 10,
        titleDisplayMode: 'alwaysShow'
}
```

### Environment
* React Native Navigation version: 2.0.2585
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): simulator
![screen shot 2018-10-17 at 5 36 42 pm](https://user-images.githubusercontent.com/659612/47066899-47871400-d233-11e8-84be-f4d8ac4018d4.png)

**Comment by guyca** [comment]
Are you sure it doesn't work on bot platforms?

**Comment by jp928** [comment]
@guyca I am terrible sorry. I had update my issue report.
