### ISSUE TITLE
[V2] topBar's BackButton color property not working

### ISSUE THREAD

**Issue by zzorba** [wix/react-native-navigation#4151]
### Issue Description
It seems like the color of the backButton cannot be changed at the moment.

### Steps to Reproduce / Code Snippets / Screenshots

1) Push a screen onto the stack with the following options:
```
topBar: {
       backgroundColor: {
         color: 'red',
       },
        backButton: {
          title: 'Cancel),
          color: 'white',
        },
```
2) Observe that the color of the button remains unchanged (on both platforms).
![image](https://user-images.githubusercontent.com/1091291/47090797-990eaf00-d1f1-11e8-881c-e83c18bd37ad.png)
![image](https://user-images.githubusercontent.com/1091291/47090806-9e6bf980-d1f1-11e8-9c9b-43731ab6e2ef.png)

---
### Environment
* React Native Navigation version: 2.0.2585
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): both IOS and Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulators running iOS 11,

**Comment by guyca** [comment]
duplicate #4150
