### ISSUE TITLE
[v2][iOS] Tab bar disappears when switching between tabs

### ISSUE THREAD

**Issue by maleriepace** [wix/react-native-navigation#4156]
### Issue Description

Tab bar disappears when switching between tabs after switching tabs from outside of the tabs.

### Steps to Reproduce / Code Snippets / Screenshots

From the playground app

1. Tap Switch to tab based app
2. Tap Switch to Tab 2 from the list
3. Tap Tab 1 from the tab bar

---
### Environment
* React Native Navigation version: latest, 2.0.2593
* React Native version: 
react-native-cli: 2.0.1
react-native: 0.51.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone XR 12.0

**Comment by guyca** [comment]
Hey @maleriepace 
Can you please elaborate? What do you mean by "after switching tabs from outside of the tabs"?

**Comment by maleriepace** [comment]
@guyca After following the steps to reproduce from the playground app, the tab bar disappears. This only happens after you click on "Switch to Tab 2" which is in the list of options in the _screen content_. 

After pulling down the latest changes from the v2 branch, the tab bar doesn't disappear until you tap a second tab now. Steps are the following:

1. Tap Switch to tab based app
2. Tap Switch to Tab 2 from the list
3. Tap Tab 1 from the tab bar
4. Tap Tab 2 from the tab bar

**Comment by yogevbd** [comment]
the tab bar disappears in this case because we also pass there:
```
bottomTabs: {
  visible: false
}
```

**Comment by guyca** [comment]
@maleriepace I'm closing the issue. If you still think there's an issue, please PR a failing detox test. Thanks 👍
