### ISSUE TITLE
Is react-native-navigation compatible with new versions of react-native? Trouble with rn 0.37 on Android.

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#416]
Hello,

I know facebook releases new versions very often so I wonder will I be able to use them, or will `react-native-navigation` force me to stay in older versions for a long time.

For example, I've been trying to use react-native 0.37 and I get this error in Android:

    Error:(77, 34) error: method onActivityResult in class ReactInstanceManager cannot be applied to given types;
        required: Activity,int,int,Intent
        found: int,int,Intent
        reason: actual and formal argument lists differ in length

on this line:

    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        getReactInstanceManager().onActivityResult(requestCode, resultCode, data);
    }

within `react-native-navigation/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java`

so I assume this might be because I'm using react-native 0.37?

---
### Environment
* React Native Navigation version: `next`
* React Native version: `0.37.0`
* Platform(s) (iOS, Android, or both?): `Android`
* Device info (Simulator/Device? OS version? Debug/Release?): `Device, Api 24, Debug`

**Comment by guyca** [comment]
Hey @SudoPlz 
This particular error is not specific to RN 0.37 and was fixed in this PR:
https://github.com/wix/react-native-navigation/pull/357

We will release a new version (`next` npm tag) hopefully tomorrow with official support to RN 0.36.1
I think it will also be compatible with RN 0.37, I'm not aware of any breaking changes yet

**Comment by SudoPlz** [comment]
Ahh sounds good, so nice to hear that. But right now I'm using the `next` npm tag.
Should I perhaps directly link `react-native-navigation` to your repo instead of using the `next` tag to fix that today for me?
