### ISSUE TITLE
not compability with react native voice

### ISSUE THREAD

**Issue by bytesk** [wix/react-native-navigation#4160]
hei dude, i'm get some error which is i'm use react native navigation
because setting react native navigation change MainActivity.java and MainApplication.java for extends

react native voice need extends ReactActivity, in react native navigation no need this and extends other,
![photo_2018-10-18_15-24-53](https://user-images.githubusercontent.com/36951004/47196431-ac08b700-d38a-11e8-829e-e726444d3874.jpg)

this i attach img for example error, after i klik start button react native voice i got this error.

i hope u reply my post, thanks

**Comment by guyca** [comment]
This issue should be opened in react-native-voice. Libraries shouldn't assume the activity is ReactActivity as RN can be embedded in meny applications, not necessarily in a vanilla RN project.

**Comment by bytesk** [comment]
@guyca thank you man for reply me, oh i know maybe this problem must give to react native voice.
