### ISSUE TITLE
[V2][iOS] topBar.backButton.color broken again in 2.0.2596

### ISSUE THREAD

**Issue by Jazqa** [wix/react-native-navigation#4164]
### Issue Description

2.0.2596 reintroduced #4150 

---
### Environment
* React Native Navigation version: 2.0.2596
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS

**Comment by yogevbd** [comment]
Fixed in 2.0.2600.
Can you please verify? thanks

**Comment by Jazqa** [comment]
Yes. It works again. :+1:
