### ISSUE TITLE
Should we do something specific to receive Navigation events in redux?

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#417]
Hi,

I installed your beautiful library, and I pass the redux store and Provider to my screens like so:
```javascript
    export function registerScreens(store, Provider) {
        Navigation.registerComponent(ScheneKeys.MAIN, () => Main, store, Provider);
    }
```
but for some reason I don't get any events dispatched whenever I perform any action, like open the drawer etc.

I should be getting such actions, shouldn't I? If not what's the point of integrating with redux?

I want to keep track of the current visible screen, or modal in my own state, so I wonder how to do that if not through redux actions dispatched by your library.

Thank you!

**Comment by guyca** [comment]
Hey
Did you call [navigator.setOnNavigatorEvent](https://github.com/wix/react-native-navigation/wiki/Screen-API#setonnavigatoreventcallback) in you the screen where you want to handle navigator event?
[example](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/FirstTabScreen.js#L43)

**Comment by SudoPlz** [comment]
Ah yeah I forgot to mention that. 
I want to handle those events globally instead of having to use `this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));`

It would be so cool if I could do this:

    import { Navigator } from 'react-native-navigation'
    Navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));

or if I did not do any of that at all, and just get events out of the box.



So I guess the question is, can I get those redux events dispatched without having to add `.setOnNavigatorEvent` on each and every screen of my project?

From what I understand, `react-native-navigation` does not offer a parent component to just add this code once.

Any ideas @guyca ?

**Comment by guyca** [comment]
You could create a base screen for your app and register for navigator events in the base screen constructor then dispatch actions accordingly. Have each of your screens extend that base class.

In the current implementation on RNN, each screen has its own `navigator` object. I'm pretty sure that will change in the near future.

You can pass the navigator object around when you dispatch actions.

**Comment by MattDavies** [comment]
Other thing worth mentioning is that your initial screen can be a good place for global type registrations. Say your first screen is "Home" and you navigate to subsequent screens from there, Home will actually always stay loaded, so you can register for navigation events etc there.

**Comment by SudoPlz** [comment]
That sounds like a great suggestion @MattDavies , but I really can't think of a way to create 1 initial screen.
Can you give me a quick example?

Where would I pass that screen:
Assume the following:

**init.js**
```
Navigation.startSingleScreenApp({
  screen: {
    screen: ScheneKeys.PARENT,
    title: 'Parent Component',
  }
});
```

**screens.js**
```
export function registerScreens(store, Provider) {
  Navigation.registerComponent(ScheneKeys.PARENT, () => ParentScreen, store, Provider);
  Navigation.registerComponent(ScheneKeys.CHILD_SCREEN, () => ChildScreen, store, Provider);
}
```

**Comment by guyca** [comment]
PARENT_SCREEN is your initial screen - when you call `startSingleScreenApp` you pass that screen as parameter.
That screen is not unmounted when you push CHILD_SCREEN or show it as a modal.

**Comment by SudoPlz** [comment]
Oh I see, but what about the solution you suggested @guyca, I think that one might serve me a bit better.
I created a parent screen factory function called `createScreen` and I plan to extend every other screen by whatever the factory created. It needs to be a factory so I can have different redux actions bound to each parent:

**ParentScreenFactory.js**

    export default function createScreen(stateActions = [], stateProps = null) {
      class ParentScreen extends React.Component {

        constructor(props) {
          super(props);
          // if you want to listen on navigator events, set this up
          this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
        }

        onNavigatorEvent() {
        }

      }

      ParentScreen.propTypes = {
        navigator: React.PropTypes.object,
      };

      function mapStateToProps(state) {
        if (stateProps) {
          return {
            ...state,
            ...stateProps,
          };
        }
        return {
          ...state,
        };
      }

      function mapDispatchToProps(dispatch) {
        const creators = Map()
                .merge(...stateActions)
                .filter(value => typeof value === 'function')
                .toObject();

        return {
          actions: bindActionCreators(creators, dispatch),
          dispatch,
        };
      }

      return connect(mapStateToProps, mapDispatchToProps)(ParentScreen);
    }

**Child.js**

    const ParentScreen = createScreen([
      routingActions,
      authActions,
    ]);

    class Child extends ParentScreen {

      constructor(props) {   // <-- error on this line
        super(props);
      }
     
      render() {
        return (
          <View/>
        );
      }
    }
    export default Child;

for some reason though, I get `undefined is not an object (evaluating 'context.store')`.
Stacktrace:

    Connect(ParentScreen)
    connect.js:129

which is this line of code `_this.store = props.store || context.store;`.
Any obvious mistakes you see here?

Thank you.

**Comment by SudoPlz** [comment]
Thank you for that..!

**Comment by SudoPlz** [comment]
For some reason though, I don't

**Comment by guyca** [comment]
@SudoPlz what events are you expecting to get?

**Comment by SudoPlz** [comment]
I want to get a PUSH event when I push to an new screen, so that I can keep track of all the routing that takes place within my redux state.

**Comment by guyca** [comment]
No event is fired when a screen was pushed. Since you already push your screens from your actions, I suggest you keep track of that from your actions.
the `onNavigatorEvent` is [used mainly](https://github.com/wix/react-native-navigation/wiki/Adding-buttons-to-the-navigator) for button clicks and a few other events (top tabs switch on Android, fab click, contextual menu events etc.)

We're going to add screen lifecycle events (screenDidAppear, screenDidDisappear etc) in the near future - it's included in the v2.0 milestone.

**Comment by SudoPlz** [comment]
Ah that would be amazing, can't wait enough for 2.0 :)

Thanks!

**Comment by SudoPlz** [comment]
@guyca Even though what you suggested about managing my own events when pushing or popping works, there's no way for me to currently know when a back button is pressed from the navigation bar itself and thus dispatch an event then.

Any ideas?

**Comment by guyca** [comment]
@SudoPlz 
This issue pains a lot of RNN users, including us.

As a temporary **hack**, you can do the following:
Android:
set `overrideBackPress: true` when pushing screens or showing a modal. This will send a `backPress` event which you can handle in the screen's `onNavigatorEvent`
```js
this.props.navigator.showModal({
      screen: 'core.MyScreen',
      title: 'Screen :)',
      overrideBackPress: true
    });
```

on iOS:
You can set a custom left button:

```
const navigatorButtons = {
  leftButtons: [
    {
        id: 'back'
        title: 'Back'
    }
  ]
}
```
And handle that as you would handle any other button.

Sorry for the inconvenience 😭

**Comment by SudoPlz** [comment]
Ah ok, thank you man, I appreciate it!

**Comment by kyle-ssg** [comment]
Had to also get around this issue, adding a custom back button is an acceptable hack for the meantime however you might get an issue when swiping back through navigation - this does not fire an event (much like the native back button). In my case i disabled gesture based navigation : 
```
//RCCNavigationController init
 if ([self respondsToSelector:@selector(interactivePopGestureRecognizer)]) {
      self.interactivePopGestureRecognizer.enabled = NO;
    }

```

**Comment by tmaly1980** [comment]
So I had been struggling with how to display a modal login screen from a saga trigger (ie screen content is available for anonymous browsing, but user clicks on a button that requires authentication). 

I used @guyca 's suggestion of having a parent screen that loads my app. I tried making a HOC for each screen but then componentWillReceiveProps was triggered multiple times potentially. So a root component (that just wraps my actual initial screen) worked.

I ended up coming up with this:

**App/Containers/ParentScreen.js:**

```
import React, { Component } from 'react'
import { View, StatusBar } from 'react-native'
import { connect } from 'react-redux'
import HomeScreen from './HomeScreen'

class ParentScreen extends Component {
  static navigatorStyle = {
    navBarHidden: true
  }
  componentWillReceiveProps (newProps) {
    if (newProps.modal && !this.props.modal) { // open modal
      this.props.navigator.showModal({ screen: newProps.modal })
    } else if (!newProps.modal && this.props.modal) { // close modal
      this.props.navigator.dismissModal()
    }
  }
  render () {
    return (
      <View style={{flex: 1}}>
        <StatusBar hidden />
        <HomeScreen {...this.props} />
      </View>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    modal: state.navigator.modal // set in redux/saga, ie login required
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(ParentScreen)

```

In an arbitrary saga, I have this:

```
export function * saveListing (api, params) {
  const { model } = params

  const user = yield select(getUser)
  if (!user) { // login first then come back
    return yield put(LoginActions.showLogin('Please sign in to continue', call(saveListing, api, params)))
  }

  const response = yield call(api.saveListing, model, params)
  if (response.ok) {
    yield put(ListingDetailsScreenActions.saveListingSuccess(model, response.data))
  } else {
    yield put(ListingDetailsScreenActions.saveListingFailure(model))
  }
}
```
My Login saga (the reducer sets the parameters along too):

```
export function * showLogin () { // push login screen
  yield put(NavigatorActions.openModal('LoginScreen'))
}
```

And in my Navigator reducer (I'm using ignite's boilerplate with reduxsauce):

```
import { createActions, createReducer } from 'reduxsauce'
import Immutable from 'seamless-immutable'

const { Types, Creators } = createActions({
  navPush: ['route', 'params'],
  openModal: ['screen'],
  closeModal: null
})

export const NavTypes = Types
export default Creators

export const INITIAL_STATE = Immutable({
  root: '',
  modal: null
})

export const navPush = (state, { screen }) =>
  state.merge({ root: screen })

export const openModal = (state, { screen }) => {
  return state.merge({ modal: screen }) // This here is what ParentScreen listens to
}

export const closeModal = (state) =>
  state.merge({ modal: null })

export const reducer = createReducer(INITIAL_STATE, {
  [Types.NAV_PUSH]: navPush,
  [Types.OPEN_MODAL]: openModal,
  [Types.CLOSE_MODAL]: closeModal
})

```
