### ISSUE TITLE
[v2] call dismissOverlay  registerComponentDidAppearListener  Not working

### ISSUE THREAD

**Issue by qiepeipei** [wix/react-native-navigation#4174]
```
Navigation.dismissOverlay(this.props.componentId);

Navigation.events().registerComponentDidAppearListener(({componentId, componentName}) => {
   //Here Not working
});

---
### Environment
* React Native Navigation version: 2.0.2597
* React Native version: 0.57
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by guyca** [comment]
I'm not sure I understand the issue. Can you please PR a failing detox e2e test?

**Comment by marcorm** [comment]
Any updates on this?!?! We've got the same problem.... :(

**Comment by pontusab** [comment]
```
Navigation.events().registerCommandListener((name, { componentId }) => {
  console.log(name, componentId)
})
```
returns 
Also `showOverlay`, `undefined`

**Comment by pontusab** [comment]
You can hardcode the id of the overlay:

```
  Navigation.showOverlay({
    component: {
      name: 'test',
      id: 'test',
      options: {
        layout: {
          backgroundColor: 'transparent',
        },
        overlay: {
          interceptTouchOutside: false,
        },
      },
    },
  })
```

Then you know the id beforehand and can close it by `Navigation.dismissOverlay('test)`

**Comment by Eldavid** [comment]
This is still an issue in 4.5.3!

**Comment by guyca** [comment]
@Eldavid If I understand the issue correctly, you're expecting `componentDidAppear` event to be emitted after an Overlay is dismissed.
`componentDidAppear`  isn't emitted after Overlay is dismissed since when an Overlay is displayed, no screen disappears. Overlay is displayed in a different hierarchy level and doesn't cause screens in the app root or modals to disappear.

**Comment by Eldavid** [comment]
Really, you are right! This is the expected behaviour.
