### ISSUE TITLE
[v2] Typescript - Export layout interfaces from "react-native-navigation"

### ISSUE THREAD

**Issue by localnet** [wix/react-native-navigation#4177]
### Issue Description

Export layout interfaces, and possibly others, from "react-native-navigation".

### Steps to Reproduce / Code Snippets / Screenshots

Current:
```typescript
import { Navigation } from "react-native-navigation";
import { LayoutRoot } from "react-native-navigation/lib/dist/interfaces/Layout";
```

Expected
```typescript
import { LayoutRoot, Navigation } from "react-native-navigation";
```

---
### Environment
* React Native Navigation version: 2.0.2581
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
Hey @localnet 
We've been wanting to get to this task for quite some time now, seems like there are always more important issues. Would be nice if someone made a PR for this feature
