### ISSUE TITLE
switchToTab stops working after calling dismissAllModals

### ISSUE THREAD

**Issue by indivisable** [wix/react-native-navigation#418]
### Description
The tab switching seems to stop working after you use the dismissAllModals method, I was using this to assure all modals were cleared but it works when I only use dismissModal.

Rel: https://github.com/wix/react-native-navigation/issues/284

### Steps 

1) Use the example code from latest 2.0 branch (Tabbed Application)
2) Create a button that triggers the switchToTab Method
3) Create a Modal and a button to toggle it
4) Dismiss the Modal with dismissAllModals
5) Test the switchTab button 

---
### Environment
react: 15.3.2
react-native: 0.36.0
IOS 10
iPhone 6 - On device.

**Comment by norman-kapschefsky** [comment]
I do have a related issue. After calling `dismissAllModals` I cant push a new screen on the stack that was under that dismissed modal. When using `dismissModal` its fine. **Note** that this happens on **iOS only**.

**Comment by fuatsengul** [comment]
I have the same issue, Is there any workaround at the moment?

**Comment by ScrimpyCat** [comment]
Came across the same issue with dismissAllModals preventing any new screens from being pushed onto the stack underneath. Anyone figured out why dismissAllModals isn't working?

@fuatsengul Only workaround I'm aware of is to call dismissModal the required amount of times (avoid animation on all subsequent dismissals to avoid any weird UI animations being shown to the user). This however is a bit of a hack.

**Comment by asimolmez** [comment]
👍
