### ISSUE TITLE
[V2] Dismiss overlay and reopening it causes crash, id already exist

### ISSUE THREAD

**Issue by hisothreed** [wix/react-native-navigation#4184]
### Issue Description

```

Exception 'Component id already exists BalanceTutorialScreen' was thrown while invoking showOverlay on target RNNBridgeModule with params 

```

### Steps to Reproduce / Code Snippets / Screenshots
```
Navigation.showOverlay({
        component: {
          name: item.id,
          id: item.id,
       } 
 })
```
---
### Environment
* React Native Navigation version: 0.55.4
* React Native version: 2.0.2607
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by kiroukou** [comment]
Is that issue solved?
I encounter the same problem here.
