### ISSUE TITLE
[V2][iOS] stack.options.layout.backgroundColor not working

### ISSUE THREAD

**Issue by Jazqa** [wix/react-native-navigation#4187]
### Issue Description

I'm trying to set a backgroundColor for a stack in an app with bottomTabs, but `stack.options.layout.backgroundColor` is not working on iOS. Works fine on Android though.

### Steps to Reproduce / Code Snippets / Screenshots

Setup a project with `stacks` as children for `bottomTabs` and try to give the stack `options.layout.backgroundColor`

---
### Environment
* React Native Navigation version: 2.0.2608
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS

**Comment by thobiasn** [comment]
Having this exact issue, is there a solution?

**Comment by thobiasn** [comment]
Seems to work with `componentBackgroundColor` instead of `backgroundColor`.

```
Navigation.setDefaultOptions({
        layout: {
            componentBackgroundColor: '#000'
        }
    });
```
