### ISSUE TITLE
[v2] conflict with windowSoftInputMode adjustResize and statusBar drawBehind true

### ISSUE THREAD

**Issue by banli17** [wix/react-native-navigation#4194]
### Issue Description

you know react-native default AndroidManifest.xml has below code, when textInput onFocus, it will auto scroll to fit position:

```
<activity
                android:name=".MainActivity"
                android:label="@string/app_name"
                android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
                android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
```

1. i init a new react-native, it's ok
2. i add react-native-navigation@alpha, it's ok

follow gif show this:

![img_0009](https://user-images.githubusercontent.com/12556069/47337756-e4303280-d6c7-11e8-9b25-bad88c9be30b.gif)

3. then  is setDefaultOptions like this

```
Navigation.setDefaultOptions({
    statusBar: {
        backgroundColor: THEME.m_color_primary,
        drawBehind: true,
        visible: false
    }
})
```
![img_0011](https://user-images.githubusercontent.com/12556069/47337743-d7abda00-d6c7-11e8-8637-300d95d00f6f.gif)

the textInput not scroll to fit position.

4. i remove drawBehind option

```
Navigation.setDefaultOptions({
    statusBar: {
        backgroundColor: THEME.m_color_primary,
        // drawBehind: true,  // remove this line
        visible: false
    }
})
```

it's ok , the textInput scroll to fit position.

![img_0010_1_](https://user-images.githubusercontent.com/12556069/47337725-be0a9280-d6c7-11e8-96ef-31cc1b4a4a61.gif)

but i want statusBar drawBehind. 

### react-native info

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 460.81 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.2 => 0.57.2
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
"react-native-navigation": "^2.0.2608",

**Comment by RichardLindhout** [comment]
https://stackoverflow.com/questions/21092888/windowsoftinputmode-adjustresize-not-working-with-translucent-action-navbar

I have the same problem
