### ISSUE TITLE
Tabbar iOS: center icon if no title/label

### ISSUE THREAD

**Issue by Crash--** [wix/react-native-navigation#420]
ATM, if we set a title & label to null, icons are not centered in the tabbar on iOS. 

I've made the change on my project, is it something you can be interested in? If yes, I can submit a PR 

before: 
![capture d ecran 2016-11-09 a 10 06 52](https://cloud.githubusercontent.com/assets/1107936/20132660/46f51098-a664-11e6-9f56-3961cd6d5a49.png)

after
![capture d ecran 2016-11-09 a 10 04 43](https://cloud.githubusercontent.com/assets/1107936/20132663/4a27a4b0-a664-11e6-929c-4ebc20fbdf03.png)

**Comment by DesignMonkey** [comment]
👍  for PR

But shouldn't it just be label that affect the tabbar. Title is used as the topheader in the navigation and not in the tabbar

**Comment by guyca** [comment]
@Crash-- Thanks a lot! Please submit a PR 👍

**Comment by perrosnk** [comment]
related to this #311
