### ISSUE TITLE
Add elvation or shadow to the background of lightbox

### ISSUE THREAD

**Issue by CoderHuzaifa** [wix/react-native-navigation#4201]
### Issue Description
Cannot add elevation and shadow to lightbox background. I want to raise the light box above the view

### Steps to Reproduce / Code Snippets / Screenshots
I have added elevation to the root view but it does nothing. Is there any work around like if we could any styling attribute to :

`Navigation.showLightBox({
                    screen: "MyApp.MyScreen", 
                        passProps: {
                            image:image
                        }, 
                        style: {
                            backgroundBlur: background
                            backgroundColor: "transparent", 
                            tapBackgroundToDismiss: true
//Any Attribute to add elevation or shadow property to light box
                        },
                        adjustSoftInput: "resize"
                    });

                }}`

Here is my code to the root view of the light box:
`bubble: {
        backgroundColor: '#ffffff',
        // borderRadius: 25,
        borderColor: '#3B5998',
         borderWidth: 0.5,
        alignSelf:'center',
        width:Dimensions.get('window').width*0.6,
        height:Dimensions.get('window').height*0.35,
        shadowColor: '#000000', //This does nothing
        shadowOffset: {width: 0, height: 2}, //This does nothing
        shadowOpacity: 0.8, //This does nothing
        shadowRadius: 2, //This does nothing
        elevation: 4 //This does nothing
      }`

![screenshot_20181023-193427](https://user-images.githubusercontent.com/9552894/47368831-d1cfec00-d6fb-11e8-8a41-20c6a67b086e.png)

### Environment
* React Native Navigation version: ^1.1.480
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device,7.0,Debug

**Comment by CoderHuzaifa** [comment]
@guyca Can you please look into this ?

**Comment by guyca** [comment]
Hey there, v1 is not maintained anymore.
