### ISSUE TITLE
[V2] registerBottomTabSelectedListener not working

### ISSUE THREAD

**Issue by TPMinan** [wix/react-native-navigation#4205]
### Issue Description

Navigation.events().registerBottomTabSelectedListener not working. Does anyone have this problem?

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.events().registerAppLaunchedListener(() => {
.....


Navigation.events().registerBottomTabSelectedListener(
   ({ selectedTabIndex, unselectedTabIndex }) => {
     console.log('select',selectedTabIndex, unselectedTabIndex)
   }
  )
})
```

---
### Environment
* React Native Navigation version: ^2.0.2581
* React Native version: 0.57.3
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by yogevbd** [comment]
Fixed here: https://github.com/wix/react-native-navigation/commit/fee53a1a914bceb2980a5f682d57ed267257c480 and available in latest version
