### ISSUE TITLE
[V2][Android] Cannot assemble release 

### ISSUE THREAD

**Issue by jp928** [wix/react-native-navigation#4209]
### Issue Description

Works fine with
```
react-native run-android
```
followed all the installation instruction.
but cannot assemble release

### Steps to Reproduce / Code Snippets / Screenshots
execute
```
./gradlew assembleRelease
```
will have output
```
node_modules/react-native-navigation/lib/android/app/src/reactNative57WixFork/java/com/reactnativenavigation/react/SyncUiImplementation.java:10: error: cannot find symbol
import com.facebook.react.uimanager.UIImplementationProvider;
                                   ^
  symbol:   class UIImplementationProvider
  location: package com.facebook.react.uimanager
```
---
### Environment
* React Native Navigation version: 2.0.2612
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): Android

**Comment by jp928** [comment]
I guess I need to add ignore config as mentioned 
https://github.com/wix/react-native-navigation/issues/3388#issuecomment-399071604

with
‘’’
name.contain(‘reactNativeWixFork57’)
‘’’

**Comment by guyca** [comment]
@jp928 That's one solution. Internally at Wix, we don't use the `run android` command and instead build directly with gradle - `./graldew app:assembleDebug`. The `app:` prefix is important as it tells gradle to use the configurations declared in the `app` module in `app/build.gradle`

**Comment by StephenTANM** [comment]
> @jp928 That's one solution. Internally at Wix, we don't use the `run android` command and instead build directly with gradle - `./graldew app:assembleDebug`. The `app:` prefix is important as it tells gradle to use the configurations declared in the `app` module in `app/build.gradle`

You saved my life

**Comment by RomuloDevelop** [comment]
@guyca can you tell me in what page, docs or wherever you find that information? I ussually use gradlew assembleRelease for cretate the APK but that command threws me an error today and when i used the 'app:' prefix everything was fine. I know my cuestion is not related with this use but i can't find official's docs
