### ISSUE TITLE
[v2] [iOS] bottomTabs visible: false visible again on version 2.0.2614 after it was fixed in 2.0.2597

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#4210]
### Issue Description

After it was fixed in https://github.com/wix/react-native-navigation/issues/4161
Issue is back but now bottomTabs become visible when I change current Tab. 
On the first tab it is not visible.

```
Navigation.mergeOptions(componentId, {
      bottomTabs: {
        visible: false,
        animate: false,
        drawBehind: true,
        currentTabIndex: NEWINDEX
      }
    });
```

Also I have set 
```
Navigation.setDefaultOptions({
    bottomTabs: {
      visible: false,
      drawBehind: true,
      animate: false
    }....
```

And also`visible: false` in my setRoot  bottomTabs

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.setDefaultOptions({
    bottomTabs: {
      visible: false,
      drawBehind: true,
      animate: false
    }
})
```

and use to change tab.
```
Navigation.mergeOptions(componentId, {
      bottomTabs: {
        visible: false,
        animate: false,
        drawBehind: true,
        currentTabIndex: NEWINDEX
      }
    });
```

bottom tab becomes visible.

---
### Environment
* React Native Navigation version: 2.0.2614
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by rendomnet** [comment]
![image](https://user-images.githubusercontent.com/18900210/47425525-67c34f80-d7ac-11e8-8bde-82a37b79211f.png)
**Clarification:** Maybe it is not bottomTabs but some white area will appear in the place of bottomTabs.

**Comment by a396901990** [comment]
same issue

**Comment by maleriepace** [comment]
Same issue here too

**Comment by yogevbd** [comment]
Doesn't seem to reproduce in version 2.0.2620. Can you please check with this version?
4f3cbf0ab3b5270eb358a974bb17d28e0ea22dc8 should solve all latest issues related to `defaultOptions`

**Comment by rendomnet** [comment]
@yogevbd seems like fixed. No issues on iOS and android
