### ISSUE TITLE
[V2] [iOS] topBar background color will flash to default color when clicking back button

### ISSUE THREAD

**Issue by winsontam** [wix/react-native-navigation#4214]
If the topBar background color set, it will flash to default background color first when clicking back button.

**Comment by henrikra** [comment]
Yeah I noticed the same thing with when I upgraded from `2.0.2568` to `2.0.2617`. But I have no idea in which version broke. @winsontam Can you provide small video of the problem to maintainers understand the problem better? @guyca @yogevbd

**Comment by handywinson** [comment]
![ezgif-1-83b5930e2591](https://user-images.githubusercontent.com/13143594/47472669-1f567100-d842-11e8-9ec1-7c37a94035c2.gif)

**Comment by winsontam** [comment]
![ezgif-1-83b5930e2591](https://user-images.githubusercontent.com/7421326/47472722-4a40c500-d842-11e8-85ff-d97ebe27c1c6.gif)

**Comment by henrikra** [comment]
The place where I have set the background color is right away when the app starts

```
Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setDefaultOptions({
    topBar: {
      background: { color: 'red' },
      title: { color: '#ffffff' },
      backButton: { color: '#ffffff' },
    },
  });
  // other stuff here
});
```

How about you @winsontam ?

**Comment by dhl1402** [comment]
Still facing this issue when set topBar background color in options static getter method. It only works if I set topBar background color in defaultOptions
