### ISSUE TITLE
[V2] Override back button to return to home tab

### ISSUE THREAD

**Issue by Brianwebb22** [wix/react-native-navigation#4217]
### Issue Description

The documentation is lacking when it comes to overriding the hardware back button on Android. I'm looking to pop back to the Home tab when back is pressed from the root of other tabs (see the Youtube app for example). 

### Steps to Reproduce / Code Snippets / Screenshots

1. Press hardware back button form root of any tab
2. App is closed

---
### Environment
* React Native Navigation version: 0.55.4
* React Native version: 2.0.2585
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device (debug)

**Comment by Brianwebb22** [comment]
Ended up solving this using this method
```
   componentDidMount() {
      BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
    }

    componentWillUnmount() {
      BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
    }

    onBackPress = () => {
      const { screen, navigator } = this.props;
      if (screen === 'MobilePro.HomeScreen' && navigator.isVisible) {
         Alert.alert(
           'Exit App',
           'Do you want to exit?',
           [
             { text: 'No', onPress: () => console.log('Cancel Pressed'), style: 'cancel' },
             { text: 'Yes', onPress: () => BackHandler.exitApp() },
           ],
           { cancelable: false },
        );
      } else if (!navigator.isVisible) {
        navigator.switchToTab({
          tabIndex: 0,
        });
        action(selectTab(0));
      } else {
        navigator.pop();
      }
      return true;
    }
```

**Comment by Asleepace** [comment]
Hi I'm facing this same issue, and I tried implementing the `BackHandler` solution you stated, it works however it doesn't override the automatic nature of RNNs back button press. Any ideas?
