### ISSUE TITLE
[v2] TopBar noBorder not working properly in iOS

### ISSUE THREAD

**Issue by CoolCyberBrain** [wix/react-native-navigation#4218]
### Issue Description

TopBar "noBorder" option does not work properly in an app with bottomtabs when mixed with translucent and blur.
TopBar border appear and disappear randomly when switching tabs in iOS.

### Steps to Reproduce / Code Snippets / Screenshots

TopBar border appear and disappear randomly when switching tabs in iOS.

```
Navigation.setDefaultOptions({
  topBar: {
    noBorder: true,
    background: {
        color: "red",
        translucent: false,
        blur: true,
    }
  },
});
Navigation.setRoot({
  root: {
    bottomTabs: {
      children: [
        {
          stack: {
            children: [
              {
                component: {
                  id: "test1",
                  name: "test1",
                },
              },
            ],
          },
        },
        {
          stack: {
            children: [
              {
                component: {
                  id: "test2",
                  name: "test2",
                },
              },
            ],
          },
        },
      ],
    },
  },
});
```

---
### Environment
* React Native Navigation version: 2.0.2618
* React Native version: 0.57.3
* Platform(s) (iOS, Android, or both?): iOS only
* Device info (Simulator/Device? OS version? Debug/Release?): simulator

**Comment by guyca** [comment]
Hey there, what exactly doesn't work properly?

**Comment by CoolCyberBrain** [comment]
> Hey there, what exactly doesn't work properly?

"TopBar border appear and disappear randomly when switching tabs in iOS."

**Comment by CoolCyberBrain** [comment]
> > Hey there, what exactly doesn't work properly?
> 
> Sometimes it doesn't work when mixing with properties like top bar background color, blur and translucent.

You're right, it worked after removing translucent, and blur. Revise the issue to reflect that since it's still a problem

**Comment by pakyo-pan** [comment]
I think it should be reopen.

**Comment by LRNZ09** [comment]
This is still a problem

**Comment by mayconmesquita** [comment]
this problem exists

**Comment by kevinkevw** [comment]
RN 0.59.10
RNN 2.26.5

on iOS
`noBorder: true` works on mobile but no effects on iPad ( Simulator, iOS 12+ ), tried all the options I can think of, with / without background, using default options / set per screen / set per push. 

Is that the team already working on V3? I still found many problems on V2...

**Comment by kevinkevw** [comment]
> RN 0.59.10
> RNN 2.26.5
> 
> on iOS
> `noBorder: true` works on mobile but no effects on iPad ( Simulator, iOS 12+ ), tried all the options I can think of, with / without background, using default options / set per screen / set per push.
> 
> Is that the team already working on V3? I still found many problems on V2...

In case you're experiencing the same issue, 
the border is now hidden after I changed  `barStyle: 'black'`  under the topBar style object.

**Comment by daveyjones** [comment]
I can confirm that there is currently no way to remove the top bar border from iPad.
