### ISSUE TITLE
BUG：When pop to the last page, the bottom of the current page will flash.

### ISSUE THREAD

**Issue by camellieeee** [wix/react-native-navigation#422]
When I jump from the a page to the last page, the bottom of the current page will flash some time.
I found this bug is easier happen to the dark background app.

**Comment by arshavinho** [comment]
Same for me:
"react": "15.3.2",
"react-native": "0.35.0",
"react-native-navigation": "^2.0.0-experimental.136"

**Comment by guyca** [comment]
Which platform? iOS or Android..

**Comment by camellieeee** [comment]
@guyca IOS
