### ISSUE TITLE
[v2][iOS] TopBar drawBehind not working after update to react-native 0.57.3

### ISSUE THREAD

**Issue by Fabian-Fynn** [wix/react-native-navigation#4221]
### Issue Description
The parameter drawBehind for the TopBar doesn't have any effect on iOS after updating react native to 0.57.3.

Expected Behaviour:
![image](https://user-images.githubusercontent.com/6934994/47493664-1d93aa00-d850-11e8-8eb2-8d895fc29627.png)

Actual Behaviour:
![image](https://user-images.githubusercontent.com/6934994/47493514-c2fa4e00-d84f-11e8-843c-bbf013da345a.png)

### Steps to Reproduce / Code Snippets / Screenshots

Our TopBar options are set with:
`Navigation.setDefaultOptions(globalStyles.navigation);`
which contains these options:
```javascript
topBar: {
    drawBehind: true,
    elevation: 0,
    background: {
      color: 'transparent',
      translucent: true,
      blur: false,
    },
    width: '100%',
    backButton: {
      color: 'white',
      showTitle: false,
    },
  },
```
---
### Current Workaround
In file `lib/ios/RNNViewControllerPresenter.m` locate `applyOptionsOnInit`-function change:
```objectiveC
[viewController rnn_setDrawBehindTopBar:[options.topBar.drawBehind getWithDefaultValue:NO]];
```
to:
```objectiveC
[viewController rnn_setDrawBehindTopBar:[options.topBar.drawBehind getWithDefaultValue:YES]];
```

---
### Environment
* React Native Navigation version: 2.0.2618
* React Native version: 0.57.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Tested on: 
  * Simulator: iPhone 6, 6s, X (iOS 9.3 + 12 each)
  * iPhone 5s (Device)(iOS 12)
  * DEBUG and RELEASE

**Comment by Fabian-Fynn** [comment]
This is still an issue 😭

**Comment by Fabian-Fynn** [comment]
For some reason this problem disappeared.
Without updating or reinstalling react-native or react-native-navigation.

**Comment by gethabit** [comment]
were you able to figure out how it disappeared?

**Comment by Fabian-Fynn** [comment]
No idea unfortunately
