### ISSUE TITLE
[V2][iOS] Going back in stack does not set the title color properly

### ISSUE THREAD

**Issue by Jazqa** [wix/react-native-navigation#4224]
Consider this a reopened #4079

### Issue Description

Going back in stack does not set the title color properly on iOS

### Steps to Reproduce / Code Snippets / Screenshots

1. Have a stack navigator where the first screen has `static get options()` and `topBar.title.color: blue`
2. Push a screen with `static get options()` and `topBar.title.color: red`
3. Pop the screen with red title and the previous screen will have a red title too

---
### Environment
* React Native Navigation version: 2.0.2618
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, 11.4, Debug

**Comment by yogevbd** [comment]
Can you test it in latest version 2.0.2620?

**Comment by Jazqa** [comment]
@yogevbd, 2.0.2620 has the issue as well.
