### ISSUE TITLE
[V2] Presenting a modal over an overlay?

### ISSUE THREAD

**Issue by VicFrolov** [wix/react-native-navigation#4228]
### Issue Description
I'm not sure if this is expected behavior, but we use overlays to present detailed product views, and it takes up the full screen. We're using it as a lightbox, since lightbox is not in V2. When we want to show a user an alert modal or an action sheet, it is not visible, and when the user closes the overlay, the alert modal / action sheet is then visible.

Show an overlay
```
      Navigation.showOverlay({
        component: {
          name: Routes.SomeOverlay,
          passProps: {
            previousComponentId: this.props.componentId,
          },
          options: {
            overlay: {
              interceptTouchOutside: true,
            },
          },
        },
      });
```

Now present an `ActionSheet`

```
    const options = {
      options: ['Hello World'],
      cancelButtonIndex: 1,
    };

    ActionSheetIOS.showActionSheetWithOptions(options, result => {
      switch (result) {
        case 0:
          break;
        default:
          break;
      }
    });
```

The alert popup is not visible, once user closes overlay, the alert modal is then visible.

If this is intended, is there a way to show said alert modal?
---
### Environment
* React Native Navigation version: "^2.0.2618"
* React Native version: "^0.57.3"
* Platform(s): iOS
* Device info: iPhone X, iOS 12, Debug

**Comment by geroale** [comment]
I really need this feature too.
