### ISSUE TITLE
[V2] Can't get event 'navigationButtonPressed' when click Back button

### ISSUE THREAD

**Issue by minhchienwikipedia** [wix/react-native-navigation#4231]
How can I instead of the onPress function of the Back button? 
I can't get the event with `Navigation.events().bindComponent(this)` 
When I click the Back button this function doesn't fire.
---
### Environment
* React Native Navigation version: 2.0.2575
* React Native version: 0.56.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Debug

**Comment by ShaMan123** [comment]
#4227

**Comment by guyca** [comment]
Hey there, currently the best (and only) solution is to set the back button yourself.

**Comment by Xesme** [comment]
Is this something that we can request as a feature?
