### ISSUE TITLE
[v2] how to navigate to new component screen from sideMenu ??

### ISSUE THREAD

**Issue by NweThazin** [wix/react-native-navigation#4236]
### Issue Description

Navigation.registerComponent("menu.screenScreen", () => SecondScreen);

sideMenu: {
        center: bottomtabs:{....}
        right: {
            component: {
                id: "componentId",
                name: "menu.firstScreen",
            }
        }
    }

how to navigate to SecondScreen Component from firstScreen of Sidemenu??

(https://github.com/wix/react-native-navigation/issues/197)]
---
### Environment
React Native Navigation version:"^2.0.2556"
React Native version: "0.55.4"
Platform(s) (iOS, Android, or both?): both
Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by alexsmartens** [comment]
@NweThazin, did you figure this out?

**Comment by stevesuyao** [comment]
@alexsmartens @NweThazin , please use `stack` in `center`, and use `bottomtabs` as a child of this `stack`.
```
Navigation.registerComponent("menu.screenScreen", () => SecondScreen);

sideMenu: {
 center: {
   stack:{
    id: 'CENTER_STACK',
    children: [
     { 
      bottomTabs:{....}
     },
    ],
  },
 },
 right: {
   component: {
    id: "componentId",
    name: "menu.firstScreen",
   },
 },
}
```
then you can `pushScreen('CENTER_STACK', 'menu.secondScreen')` in sidemenu. 
`CENTER_STACK` is the component id of the stack where bottomtabs live.
