### ISSUE TITLE
[v2] setting top bar background color with mergeOption does not work

### ISSUE THREAD

**Issue by omar-dev** [wix/react-native-navigation#4240]
### Issue Description
setting top bar background color with mergeOption does not work

### Steps to Reproduce / Code Snippets / Screenshots
push screen with top bar background color transparent
mergeOption for top bar background color with any color 

---
### Environment
* React Native Navigation version: 2.0.2621
* React Native version: 0.57.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by yogevbd** [comment]
Try this:
```
Navigation.mergeOptions(componentId, {
  topBar: {
    background: {
      color: '#00ff00',
      translucent: false
    }
  }
});
```

When `topBar.background.color` receive transparent color it also set `translucent: true`.
We might consider removing it

**Comment by omar-dev** [comment]
@yogevbd it worked. thanks
