### ISSUE TITLE
v2 - TopBar with background color and translucency rendering completely transparent (no colour at all)

### ISSUE THREAD

**Issue by tomhicks** [wix/react-native-navigation#4244]
### Issue Description

TopBar on iOS unexpectedly rendering completely transparent when background color and translucent are both set. This used to work somewhere around v2.0.2500.

### Steps to Reproduce / Code Snippets / Screenshots

```
  Navigation.setDefaultOptions({
    layout: {
      backgroundColor: theme.colors.darkest,
    },
    topBar: {
      background: {
        color: isAndroid ? theme.colors.dark : theme.colors.darkest,
        translucent: true,
      },
    },
  })
```

This used to render my dark theme colour with a subtle translucency (not as obvious as the standard "dark" or "default" iOS blur), but now it renders completely transparent and the content is unreadable.
---

### Environment
* React Native Navigation version: 2.0.2620 (although it was also present earlier - I haven't done a bisect to find the exact breaking version)
* React Native version: 0.57.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device iOS 12.1

**Comment by FRizzonelli** [comment]
It's also happening to me out of nowhere. It was working perfectly, now all of a sudden it stopped :( No style applied at all :(
