### ISSUE TITLE
Android Crash: If icon is not an image (a string for example) - App Crashes "App .. has stopped"

### ISSUE THREAD

**Issue by lakhman** [wix/react-native-navigation#425]
### Issue Description

Just came across this, I thought I could use system defined icons as a string (home, favorites), but instead, on android it just crashes, nothing in adb logs and difficult to debug. - It doesn't work for iOS - but you get an error instead of a "silent crash".

I know this is unlikely but for testing I thought I could use system defined icons (so no need to include any extra images). - Could possibly trip up other noobs to RNN.

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.startTabBasedApp({
    tabs: [{
        label: 'One',
        screen: 'example.FirstTabScreen',

        icon: 'home', // THIS WILL CRASH AN ANDROID APP - We cannot use system icons

        title: 'Screen One'
    }],
});
```

Could it fail more gracefully?

On iOS you get the following error.

> JSON value '<null>' of type NSNull cannot be converted to an image. Did you forget to call resolveAssetSource() on the JS side?

On android it crashes the app. "Unfortunately, ProjectName has stopped."

---
### Environment
* React Native Navigation version: 62847a7d57ee12efa7138e883c7e40a5bc08eaed
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device

**Comment by guyca** [comment]
hey @lakhman Thanks for the detailed description, but I'm not sure what system icons are. 
I agree we must improve on error reporting and validations. I'll add that to one of the next milestones. Thanks for the suggestion 👍

**Comment by lakhman** [comment]
on iOS we have some default system icons we can use if wanted:

https://developer.apple.com/ios/human-interface-guidelines/graphics/system-icons/

Not sure about android system icons, we don't need the icons, but some error reporting enhancement would be great.
