### ISSUE TITLE
[v2] Adding SafeAreaView makes the screens flicker

### ISSUE THREAD

**Issue by thinklinux** [wix/react-native-navigation#4250]
### Issue Description

When I wrap my component with SafeAreaView and I navigate around it flickers. As it's rendering the SafeAreaView after the screen is rendered.

Here is a video:

[IMG_8277.TRIM.mov.zip](https://github.com/wix/react-native-navigation/files/2524902/IMG_8277.TRIM.mov.zip)

### Steps to Reproduce / Code Snippets / Screenshots

```js
import React, { Component } from "react";
import { Text, View, Button, SafeAreaView } from "react-native";
import { goSignUp } from "../../navigation";

export default class SignIn extends Component {
  render() {
    return (
      <SafeAreaView style={{ flex: 1, backgroundColor: "#fff" }}>
        <View style={{ flex: 1 }}>
          <Text>Sign in</Text>
          <Button
            onPress={() => {
              goSignUp();
            }}
            title="Sign up"
          />
        </View>
      </SafeAreaView>
    );
  }
}
```

My goSignUp function

```js
export const goSignUp = () =>
  Navigation.setRoot({
    root: {
      component: {
        name: "SignUp"
      }
    }
  });
```
---
### Environment
* React Native Navigation version: ^2.0.2568
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone SE, iPhone X simulator

**Comment by andreypaul** [comment]
Same problem...

**Comment by rendomnet** [comment]
any updates?

**Comment by azrul** [comment]
use this one, https://github.com/react-native-community/react-native-safe-area-view

**Comment by Gra55h0pper** [comment]
Same problem. Have not tried the proposed workaround suggested by @azrul yet.

**Comment by Robiullah2244** [comment]
I have also faced this issue. In my case, it's flickered when I imported SafeAreaView from 'react-native'. Then when I imported from 'react-navigation', it works fine

import { SafeAreaView } from "react-native"; --->>>import { SafeAreaView } from "react-navigation"; 

You can try it

**Comment by antonputra** [comment]
> import { SafeAreaView } from "react-native"; --->>>import { SafeAreaView } from "react-navigation";

thanks, fixed my issue!

**Comment by nenjamin2405** [comment]
I'm facing the same problem, but I'm using `import {SafeAreaProvider} from 'react-native-safe-area-context'`. If I have the SafeAreaProvider outside of the registered screen so the code snippet below will not work. Hi @azrul , do you have the same problem as mine when using the Provider of that library
```js
options: {
          animations: {
            push: {
              waitForRender: true,
            },
          },
 },
```

**Comment by nthtrung09it** [comment]
@nenjamin2405 Hi, did you find a way to resolve the issue?

**Comment by nenjamin2405** [comment]
Hi @nthtrung09it, the reason why I use `react-native-safe-area-context` is that I wanna use `const insets = useSafeAreaInsets();`. But this library has a problem as I mentioned above, so I stop using it, remove the outer SafeAreaProvider and use `https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets` instead.

**Comment by guyca** [comment]
Hey guys, I might be missing something here but what is the purpose of using `react-native-safe-area-context`?
If the root element is a scrollable component  (ScrollView, FlatList etc.) or [SafeAreaView](https://reactnative.dev/docs/safeareaview) then insets are handled for you out of the box by RNN.

**Comment by nenjamin2405** [comment]
Hi @guyca, because sometimes it's useful to know what the insets are for the top, right, bottom, and left of the screen to do some UI customization, that's why I use `react-native-safe-area-context`

**Comment by honcon** [comment]
Hi folks, after a lot of research I came up with the solution.
1. Install `react-native-static-safe-area-insets` as @nenjamin2405 Indicates
_Don't worry that is somehow aged it is very simple, nothing is changed from then._
2. Use the following Component as the one and only SafeAreaView you will ever need

Works great and always, respond after orientation change
No Providers
No Flickering
No Jumping
No Bullshit

**SafeAreaView.js**
```javascript
import React, { useState, useEffect } from 'react';
import { View, Dimensions } from 'react-native';
import StaticSafeAreaInsets from 'react-native-static-safe-area-insets';

export default function SafeAreaView(props) {

    const [insets, setInsets] = useState({
        bottom: StaticSafeAreaInsets.safeAreaInsetsBottom,
        right: StaticSafeAreaInsets.safeAreaInsetsRight,
        top: StaticSafeAreaInsets.safeAreaInsetsTop,
        left: StaticSafeAreaInsets.safeAreaInsetsLeft
    });

    useEffect(() => {
        const subscription = Dimensions.addEventListener('change', () => {
            StaticSafeAreaInsets.getSafeAreaInsets(values => {
                setInsets({
                    bottom: values.safeAreaInsetsBottom,
                    right: values.safeAreaInsetsRight,
                    top: values.safeAreaInsetsTop,
                    left: values.safeAreaInsetsLeft
                });
            });
        });

        return () => subscription.remove();
    });

    return (
        <View {...props} style={{
            ...props.style,
            marginTop: insets.top,
            marginBottom: insets.bottom,
            marginLeft: insets.left,
            marginRight: insets.right
        }}>{props.children}</View>
    );
}
```

**Comment by thepirateboy** [comment]
This is really annoying and still happening until now. 
The **simplest way** to fix it actually just use `View` instead. 
And don't forget to setup the `paddingVertical` mate :)

**Comment by hblab-luunv** [comment]
same issue

**Comment by adamSplendex** [comment]
same experience with NavigatorStack and DrawerNavigator :( have to wrap screens with Animated.View in order to fix it, but it is not really fixing it.
