### ISSUE TITLE
[V2] Cannot interact behind overlay on iOS

### ISSUE THREAD

**Issue by steve228uk** [wix/react-native-navigation#4251]
### Issue Description

It seems that when an overlay is presented on iOS that it's not possible to interact with the screen that's below it.

I have attempted with `interceptTouchOutside` as both `true` and `false`

This is not the case on Android.

### Steps to Reproduce / Code Snippets / Screenshots

1. Present an overlay
2. Attempt to interact with the view below

```js
Navigation.showOverlay({
    component: {
        name: componentName,
        passProps: passProps,
        options: options
    }
});
```

---
### Environment
* React Native Navigation version: 2.0.2594
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / iOS 12 / Debug

**Comment by yogevbd** [comment]
Can you check if this reproducing in 2.0.2635?

**Comment by barjas** [comment]
same issue, interceptTouchOutside has no effect

**Comment by yogevbd** [comment]
This issue should be fixed in latest version, if not please let us know

**Comment by michellmorso** [comment]
I’m still experiencing this issue as well

**Comment by yung93** [comment]
same happening on version 2.14.0
