### ISSUE TITLE
[v2] Clicking on notif create new react instance on top of previous one

### ISSUE THREAD

**Issue by ogostus** [wix/react-native-navigation#4252]
### Issue Description
when user clicks on a notification, a new react instance is added on top of the previous one, if the app is playing a song, the song is played as many time as there are react instances, and the backpress remove instance by instance

### Steps to Reproduce / Code Snippets / Screenshots
a project to clone to reproduce the bug:
git@github.com:ogostus/RNNIssueReproduction.git

---
### Environment
* React Native Navigation version: ^2.0.2631
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?): Android

**Comment by quarryman** [comment]
Can you try adding this to your android/app/src/main/AndroidManifest.xml to ensure its not configuration problem?
```
<activity
        android:name=".MainActivity"
        ...
        android:launchMode="singleTop"
```

**Comment by ogostus** [comment]
> Can you try adding this to your android/app/src/main/AndroidManifest.xml to ensure its not configuration problem?
> 
> ```
> <activity
>         android:name=".MainActivity"
>         ...
>         android:launchMode="singleTop"
> ```

it worked ! thank you @quarryman
