### ISSUE TITLE
[v2] Cannot resolve module 'tslib'

### ISSUE THREAD

**Issue by thinklinux** [wix/react-native-navigation#4253]
### Issue Description

Building the app results in `Cannot resolve module 'tslib'`

### Steps to Reproduce / Code Snippets / Screenshots

I just updated to the last version of react-native-navigation and I cleaned the cache and nodejs folder after I first got the error but that didn't help.

My solution was to manually install tslib by doing `run npm install --save tslib`

### Environment
* React Native Navigation version: ^2.0.2630
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone SE

**Comment by guyca** [comment]
Fixed in .2631

**Comment by thinklinux** [comment]
You are awesome!!! Thanks! <3
