### ISSUE TITLE
[V2] [Android]  Getting UNAUTHORIZED_OVERLAY error while we use react-native-youtube.

### ISSUE THREAD

**Issue by JaydeepJikadra** [wix/react-native-navigation#4256]
### Issue Description

I have used react-native-navigation V2 along with react-native-youtube. when I play the video then it will pause automatically with error

10-30 10:59:35.613 18102-18102/com.xyz W/YouTubeAndroidPlayerAPI: **YouTube video playback stopped due to unauthorized overlay on top of player.** The YouTubePlayerView is obscured by android.widget.FrameLayout{91b1c4c V.E...... ........ 0,0-1080,1857}. **YouTubePlayerView is completely covered,** with the distance in px between each edge of the obscuring view and the YouTubePlayerView being: left: 54, top: 734, right: 53, bottom: 514..

This error is happening bcoz in V2 there is something new support adding for overlay manager before root is setting #3899, while in v1 everything works perfectly.

### Steps to Reproduce / Code Snippets / Screenshots
Snippets for how I open home page after splash loaded.
 Navigation.setRoot({
          root: {
            stack: {
              children: [
                {
                  component: {
                    id: constants.Home_CMP_ID,
                    name: constants.Home,
                    passProps: {
                      stateData: store,
                      notificationData: this.notificationData
                    }
                  }
                }
              ],
              options: {}
            }
          }
        });
---
### Environment
* React Native Navigation version: 2.0.2621
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator And Device, 8.0, Debug And Release.

**Comment by JaydeepJikadra** [comment]
Hello @guyca 
plz, guide me, how to solve this issues bcoz my app is totally dependant on this navigation lib
and I can not move back to V1, due to some major changes.

I think with  "react-native-navigation": "^2.0.2500"  was working properly but if I used this version then getting the problem with react-native-pushnotification [https://github.com/wix/react-native-navigation/issues/472](url)

**Comment by praveenapoojary** [comment]
I found that if you push component as a overlay it will work but it is still a hack.

**Comment by GoaGit** [comment]
@guyca could you please share a sketch/description of the view layering in react-native-navigation V2. Apparently there is at least one item stacked (either transparent of invisible) on top of every screen type (except for the overlay component) that is being detected by the Youtube component. I can confirm that @praveenapoojary's suggestion works, yet it is not the preferred solution.

To be able to create a PR for this issue, some guidance regarding the view layer composition would be awesome.

**Comment by GoaGit** [comment]
A first solution would be to modify the ```setContentLayout``` method in ```node_modules\react-native-navigation\lib\android\app\src\main\java\com\reactnativenavigation\viewcontrollers\navigator\Navigator.java```

In case you would like to keep the possibility to use modals, this solution works:

**Comment by AyushAppin** [comment]
Any solutions for this issue?

**Comment by IbrahimCanKALYA** [comment]
@AyushAppin did u find any solution for this issue if u want cloud u share it?
thanks in advence

**Comment by yjose** [comment]
by creating my own youtube package https://github.com/barmej/react-native-youtube-player
