### ISSUE TITLE
Stuck on (Task :react-native-navigation:compileReactNative56DebugJavaWithJavac FAILED)

### ISSUE THREAD

**Issue by waleedbk** [wix/react-native-navigation#4257]
### Issue Description
I've just started react-native-navigation for the upcoming project as react-navigation is going to deprecate the redux support. But i'm still not able to build my very first example project using react-native-navigaiton v2. I've spent a lot of hours by apply everything i got on gihub issues that are similar to mine. But none of them worked for me. Please help to get rid off from this. thanks
**Error**
`
Task :react-native-navigation:compileReactNative56DebugJavaWithJavac FAILED
D:\projects\react-native\quizup - Copy\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\SyncUiImplementation.java:10: error: cannot find symbol
import com.facebook.react.uimanager.UIImplementationProvider;
                                   ^
  symbol:   class UIImplementationProvider
  location: package com.facebook.react.uimanager
D:\projects\react-native\quizup - Copy\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\SyncUiImplementation.java:23: error: cannot find symbol
    public static class Provider extends UIImplementationProvider {
                                         ^
  symbol:   class UIImplementationProvider
  location: class SyncUiImplementation
D:\projects\react-native\quizup - Copy\node_modules\react-native-navigation\lib\android\app\src\main\java\com\reactnativenavigation\react\NavigationReactNativeHost.java:86: error: cannot find symbol
                .setUIImplementationProvider(getUIImplementationProvider())
                                             ^
  symbol:   method getUIImplementationProvider()
  location: class NavigationReactNativeHost
D:\projects\react-native\quizup - Copy\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\SyncUiImplementation.java:24: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\projects\react-native\quizup - Copy\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\SyncUiImplementation.java:29: error: method does not override or implement a method from a supertype
        @Override
        ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative56DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
`
### Environment
* React Native Navigation version: 2.0.2427 also tried ^2.0.2631
* React Native version: 0.57.0 (also tried 0.56.x and 0.55.x but they cause more bugs)
* Platform(s) : Android phone and Emulator

**Comment by narodejesus** [comment]
currently they it seems that RNN doesn't support 0.57. it happens to me too that's why I downgraded to RN 0.56. now it is working

**Comment by waleedbk** [comment]
It's a bug because i followed the documentation and it didn't work.

**Comment by davidwico** [comment]
I got same issue, anyone find solution ?
