### ISSUE TITLE
[v2] [Android] Navigating from screen without topbar to topbar screen and then back causes persistent white space

### ISSUE THREAD

**Issue by pribeh** [wix/react-native-navigation#4260]
### Issue Description

On Android, when pushing from a screen without a topbar to one with a topbar and then back a white space where the topbar was in the second screen shows on the original.

### Steps to Reproduce / Code Snippets / Screenshots

- load base screen without topbar (bottom of the stack)
- push a screen with a topbar
- navigate back to the the base screen
- white space appears where the topbar was in the pushed screen (see attachment)

![screenshot_20181023-094439_yuser](https://user-images.githubusercontent.com/690883/47736082-43e88980-dc44-11e8-996b-df996bd1e92b.jpg)

---
### Environment
* React Native Navigation version: 2.0.2621
* React Native version: 55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung Galaxy S8+, Android 8

**Comment by guyca** [comment]
Hey @pribeh 
I wasn't able to reproduce this in the playground app - can you please try to reproduce it in the playground app?
