### ISSUE TITLE
In app message notification / sliding overlay is shown behind the bottom tab bar in Android

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#4263]
### Issue Description
For a bottom tab based app on Android, the in app message notification/sliding overlay is shown behind the tab bar due to which it is not visible or partially visible to users. I can add a margin at bottom such that it appears above the tab bar but in my mobile app, some screens have a bottom tab bar and some other screens don't have a bottom tab bar. So, adding a bottom margin makes the in app notification look weird on the screens without the bottom tab bar.

Is there a way to show the in app notification above the tab bar or somehow figure out the tab bar is hidden such that the bottom margin can be applied programatically?

### Steps to Reproduce / Code Snippets / Screenshots

Create a tab based app.
Show an in app message notification at bottom position.
Observe that the in app message notification is invisible or partially visible.
---
### Environment
* React Native Navigation version: 1.1.471
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by guyca** [comment]
Hey @varungupta85, I'm sorry but we've stopped supporting v1. If you're maintaining a fork of RNN, I think your best option is to fix it in your fork.
