### ISSUE TITLE
Drawer always appears in the example project even after I remove the drawer section

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#427]
### Issue Description

The hamburger menu icon which opens up the drawer is always shown on the screen even after I remove the drawer section from the example application. So, I have this in the `app.js` after I removed the drawer piece from it

```
Navigation.startTabBasedApp({
  tabs: createTabs(),
  appStyle: {
    tabBarBackgroundColor: '#0f2362',
    tabBarButtonColor: '#ffffff',
    tabBarSelectedButtonColor: '#63d7cc'
  }
});
```

But I still the see the hamburger menu icon on the top left side. It doesn't show the drawer when I click on it but the icon still appears. I expected the icon to go away.

### Steps to Reproduce / Code Snippets / Screenshots

Create a react-native application
Copy over the example app
Remove the drawer piece as described above from the app.js file
Run the app and observe the issue

---
### Environment
* React Native Navigation version: react-native-navigation@2.0.0-experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
Hey @varungupta85 
`FirstTabScreen` also declares a menu button explicitly. Did you remove that as well?

**Comment by varungupta85** [comment]
Thanks @guyca for the quick response as always. I didn't realize that we need to specify the left menu button per scene which would be hooked to the drawer defined in the top application. If I understand this correct, the `drawer` configuration in the top level defined which drawer to show when toggled from right or left. The menu button in the scene defines the icon to show for the drawer and the action that will be sent when the icon is pressed and when you handle the action in the scene, you specify which drawer you want to toggle and it will show the screen as defined in the top level application.

If you want, I can add this info to the README and send a PR.

**Comment by guyca** [comment]
That's correct for iOS. On Android things are a bit different. Because on Android we only support four types of left buttons, there's no need to define a menu button explicitly. The menu button is set for you if no other button is defined and it's id is `sideMenu`.

Can you send a PR to the wiki page? If so that would be great!

**Comment by varungupta85** [comment]
Hi @guyca, sorry for the delayed response, I have been travelling. Could you please throw some light on what your meant by **four types of left buttons** in Android? If you can point me to a source file which would explain this, that would be fine as well. I was trying to create a PR for the wiki and realized that github doesn't support PRs for the wiki pages according to [stackoverflow](http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github). There are some workarounds that are suggested. So, just wanted to check if you guys follow some strategy for sending PRs for the wiki pages.

**Comment by guyca** [comment]
@varungupta85 [source](https://github.com/wix/react-native-navigation/blob/8b034b2ebb95f482b594a467bd98942f0bce16ce/android/app/src/main/java/com/reactnativenavigation/params/parsers/TitleBarLeftButtonParamsParser.java#L16)

Thanks for taking the time to make a PR, that's really appreciated. We don't use any of the workarounds. When things stabilise we'll figure something out.
