### ISSUE TITLE
[V2] TopBar Background Component

### ISSUE THREAD

**Issue by TPMinan** [wix/react-native-navigation#4271]
### Issue Description

I want to add a logo to the header. but in doing so I could not center the logo. Is there a method for this?

### Steps to Reproduce / Code Snippets / Screenshots

I want to add a logo to the header. but in doing so I could not center the logo. Is there a method for this? the size at the time it is loaded remains constant

#### TopBar Option
```
topBar: {
    background: {
        color: Colors.Primary,
        component: {
             name: 'car.TopBar',
             aligment: 'center'
        }
   },
```

#### TopBar Screen
```
export default class TopBar extends Component {
    state = { orientation: 'P' };

    render() {
        return <View style={styles.container}>
            <SvgUri width={120} height={40} source={require('./logo.svg')} />
        </View>
    }
}


const styles = {
    container: {
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'stretch',
        backgroundColor: Colors.Primary
    }
};
```

<img width="392" alt="screen shot 2018-11-01 at 15 18 42" src="https://user-images.githubusercontent.com/25525515/47851360-7b446b00-dde9-11e8-8c81-d4def2db72e0.png">
<img width="811" alt="screen shot 2018-11-01 at 15 18 50" src="https://user-images.githubusercontent.com/25525515/47851361-7b446b00-dde9-11e8-90dd-5ac911842a7e.png">

---
### Environment
* React Native Navigation version: ^2.0.2636
* React Native version: 0.57.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): any

**Comment by AlexBueckig** [comment]
Not sure if it's just a copy&paste error, but in your topbar options the word alignment is misspelled... ;)

**Comment by TPMinan** [comment]
Thank you for your answer. The 'alignment' works. But the main problem is that the Bar gives the width according to its orientation. And this value remains constant when the phone is rotating. For this, I use the orientation property, but I don't look very healthy. I'm looking for a healthier solution.

**Comment by AlexBueckig** [comment]
I see, I see... Not sure how SvgUri works internally regarding setting the width... But regarding to the RN Docs: 

> For stretch to have an effect, children must not have a fixed dimension along the secondary axis.

Source: https://facebook.github.io/react-native/docs/flexbox#align-items

Maybe that's the reason the stretch/centering doesn't work for you. Is the width property really necessary for the svg to show up properly? Might be worth a try to remove it and see how it works out. ;)

**Comment by TPMinan** [comment]
I'm using it as a workaround. but I am changing the currentTabIndex value with mergeOptions when starting the application. When I do this, the logo on the first tab page appears to be left-justified. and `bottomTabs: {currentTabIndex: 1}` does not work in the setOptions property

This method does not work
```
Navigation.setDefaultOptions({
    topBar: {
        title: {
            component: {
                name: 'car.TopBar',
                alignment: 'center'
            }
        }
    }
})
```

When I use this method, it just looks like this in the first screen
```
Navigation.mergeOptions(this.props.componentId, {
    bottomTabs: {
        currentTabIndex: 1
    },
})
```
<img width="469" alt="screen shot 2018-11-06 at 09 05 50" src="https://user-images.githubusercontent.com/25525515/48045939-7560d800-e1a3-11e8-9aa8-eb29363efd54.png">

**Comment by arryanggaputra** [comment]
@TPMinan  hi there, how you make the bottomTab with custom icon?

**Comment by TPMinan** [comment]
I'm using 'react-native-vector-icons' and Icomoon configuration. You can resolve the links I've added
https://github.com/oblador/react-native-vector-icons#custom-fonts
http://wix.github.io/react-native-navigation/#/docs/layout-types?id=bottomtabs

**Comment by arryanggaputra** [comment]
![screen shot 2019-01-15 at 22 33 10](https://user-images.githubusercontent.com/4743772/51190792-96694600-1915-11e9-9ea5-9d0b6d64747f.jpg)
@TPMinan  I mean, how you create the center button, it's bigger than the other. Can you give me code sample? Really appreciate

**Comment by TPMinan** [comment]
@arryanggaputra The code I'm writing right now is an example. I wrote a sample code because it is quite complicated in the picture.

The method I use is not very effective. Because you may need to assign different values to a few actions. Such as giving more to the 'bottom' value for iphoneX
To do this, you need to create a screen first
```
// register component TabBarIcon
Navigation.registerComponent('car.TabBarIcon', () => TabBarIcon);
```
```
// TabBarIcon Component
export default class TabBarIcon extends Component{
    render() {
        return <View style={{
            width: 55,
            height: 55,
            position: 'absolute',
            bottom: 10,
            borderRadius: 55,
            justifyContent: 'center',
            alignItems: 'center',
            alignSelf: 'center',
            zIndex: 2,
            backgroundColor: 'red'
        }}>
            {/* Custom icon here */}
        </View>
    }
}
```

```
Navigation.events().registerAppLaunchedListener(() => {
    /* Other Options */


    // TabBar center button
    Navigation.showOverlay({
        component: {
            id: 'car.TabBarIcon',
            name: 'car.TabBarIcon',
            options: {
                overlay: {
                    interceptTouchOutside: false
                },
            }
        }
    })
})
```
After that you can do as you like svg shape for the background of the button.
If not, examine the documents. I can help you if you encounter a problem.

**Comment by arryanggaputra** [comment]
@TPMinan woah cool... let me try your code man... Btw, is this work on android?

**Comment by arryanggaputra** [comment]
![photo_2019-01-16 05 54 13](https://user-images.githubusercontent.com/4743772/51215338-2bd6fb00-1953-11e9-9fd9-6015c9abf160.jpeg)
@TPMinan  Okay, I tried your code, thank a lot. There's a component on the bottom of the page, but why it's not transparent, do you have any idea with this?

**Comment by TPMinan** [comment]
@arryanggaputra The components you add using "ShowOverlay" can cover the entire screen. So the icon you use should be just its size. Probably the element on the icon component will take up the entire screen.

**Comment by arryanggaputra** [comment]
@TPMinan  Okay cool, i just set `componentBackgroundColor : transparent`, and it's work. Thanks a lot  😊😊😊😊😊😊
