### ISSUE TITLE
[v2] Option to set TopBar tint color

### ISSUE THREAD

**Issue by jsslai** [wix/react-native-navigation#4273]
### Issue Description

Now it is impossible to set tint color for whole `TopBar` and instead you have to define color for different components (back button, left and right buttons and title) separately. I think it is quite common case to apply tint color for whole `TopBar`.

At least on iOS this would mean adding method which sets `UINavigationBar.tintColor` property. I'm not sure how this is done on Android but I think this should be possible. You could still set different colors per component by explicitly defining those properties in `Options`.  

```javascript
{
  topBar: {
    tintColor: "blue", // Or itemColor etc.
    title: {
      color: "white"
    }
  }
}
```

---
### Environment
* React Native Navigation version: 2.0.2636
* React Native version: 0.57.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Any iOS 12 simulator, debug and release builds

**Comment by chrise86** [comment]
@guyca is tint colour possible on v6?
