### ISSUE TITLE
Regression: [V2] [iOS] [Android] Dismiss modal got 4 arguments, expected 5

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#4285]
### Issue Description

Open modal then dismiss it.

![peek 2018-11-05 11-57](https://user-images.githubusercontent.com/4223434/47994236-05464980-e0f2-11e8-809a-018fac609647.gif)

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.dismissModal(this.props.componentId);
```

---
### Environment
* React Native Navigation version: 2.1.1
* React Native version: 0.56.4
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device and only tested on Debug

**Comment by AnimaWolf** [comment]
Same problem but with popToRoot

**Comment by guyca** [comment]
Checking, seems like `alpha` is working as expected. You can use it until we figure this out

**Comment by guyca** [comment]
This should be fixed in 2.1.1-snapshot.23, will publish 2.1.2 soon.

**Comment by ItsNoHax** [comment]
Confirmed fixed in 2.1.2, thanks a lot @guyca

**Comment by HemrajLodha** [comment]
again getting same issue in version 2.1.3

**Comment by YourBoB** [comment]
Hi @guyca , do you have any suggestions about this issue? I meet the same issue when I using 2.1.1-snapshot.23, 2.1.0, and  2.2.2 (my react-native version is 0.57.4) thanks

**Comment by guyca** [comment]
Perhaps you didn't rebuild the native code after npm install?
