### ISSUE TITLE
start single screen app is undefined.

### ISSUE THREAD

**Issue by mstahlmann** [wix/react-native-navigation#4289]
### Issue Description

I cannot get a simple example app to start. I have followed the instructions exactly. I have a very simple app and it is failing right at the beginning.

### Steps to Reproduce / Code Snippets / Screenshots

import {Navigation} from 'react-native-navigation';

import AuthScreen from './src/screens/Auth/Auth';

// Register Screens
Navigation.registerComponent("awesome-places.AuthScreen", () => AuthScreen);

// Start a App
Navigation.startSingleScreenApp({
  screen: {
    screen: "awesome-places.AuthScreen",
    title: "Login"
  }
});
---
### Environment

"dependencies": {
    "react": "16.4.1",
    "react-native": "0.56",
    "react-native-navigation": "^2.0.2641",
    "react-native-vector-icons": "^6.0.2",
    "react-redux": "^5.1.0",
    "redux": "^4.0.1"
  },
* React Native Navigation version: 2.0.2641
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): IOS simulator, IOS 12

**Comment by guyca** [comment]
Hey there, `startSingleScreenApp` is a v1 api and it seems like you have v2 installed 👍

**Comment by mstahlmann** [comment]
what is the V2 corresponding command?

**Comment by mstahlmann** [comment]
figured it out thanks
