### ISSUE TITLE
Deep link handler fires for every screen, visible or not

### ISSUE THREAD

**Issue by falquaddoomi** [wix/react-native-navigation#429]
### Issue Description

I'm attempting to follow the advice from the docs of using deep links in my navigation drawer to trigger a push on the main active app screen (which is a sibling of the drawer). Unfortunately, every screen in the current stack (visible or not) receives the deep link event and then pushes the new screen, resulting in as many pushed screens as there were previously screens in the navigation stack.

Here's a little video illustrating the problem:
![Multiple Screen Chaos Demo](https://d17oy1vhnax1f7.cloudfront.net/items/0h0j2x0l2T0O2D0i1v1O/msnavbug_final.gif)

### Steps to Reproduce / Code Snippets / Screenshots

Here's the base class from which my iOS and Android-specific drawer components inherit. The navigateTo() method fires the deep link event from within the drawer.

```jsx
export default class BaseSideMenu extends Component {
  constructor(props) {
    super(props);
  }

  navigateTo(title, screen, reset) {
    this._toggleDrawer();

    const t = {
      title: title,
      screen: screen,
      doReset: reset
    };

    this.props.navigator.handleDeepLink({
      link: 'main/' + JSON.stringify(t)
    });
  }

  _toggleDrawer() {
    this.props.navigator.toggleDrawer({
      to: 'closed',
      side: 'left',
      animated: true
    });
  }
}
```

Below is the base class for my main screens which handles the deep link event.

```jsx
export default class LinkableMenuScreen extends Component {
  constructor(props) {
    super(props);
    // if you want to listen on navigator events, set this up
    this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
  }

  onNavigatorEvent(event) {
    if (event.id === 'menu') {
      // centrally handle menu visibility button for the child screens
      this.props.navigator.toggleDrawer({
        side: 'left',
        animated: true
      });
    }
    else if (event.type == 'DeepLink') {
      // recall that deeplink events are broadcast to every screen
      //  we want to handle this event only if it's about us (the main screen)
      const parts = event.link.split('/');
      if (parts[0] == 'main') {
        const params = JSON.parse(parts[1]);

        // handle the link somehow, usually run a this.props.navigator command
        if (params.doReset === true) {
          console.log("Deep reset to " + params.title + " from ", this.props.navigator.screenInstanceID);

          this.props.navigator.resetTo({
            title: params.title,
            screen: params.screen
          })
        }
        else {
          console.log("Deep push to " + params.title + " from ", this.props.navigator.screenInstanceID);

          this.props.navigator.push({
            title: params.title,
            screen: params.screen
          })
        }
      }
    }
    else if (this.childNavigatorEvent !== null && typeof this.childNavigatorEvent == 'function') {
      // propogate navigation event to inheriting classes, if they're interested
      this.childNavigatorEvent(event);
    }
  }
}
```

I suppose it makes sense that they're all receiving it, but I don't know how to distinguish in each screen whether it's the currently visible one or not.

---
### Environment
* React Native Navigation version: 2.0.0-experimental.141
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 10.1 Simulator

**Comment by falquaddoomi** [comment]
Thanks to psyz on the Discord channel, I realized that my drawer should be resetting the navigation stack, not pushing onto it. This circumvents the problem by only having "root" screens with deep link handlers at the bottom of the navigation stack. I could imagine a situation in which you want to push a typically "root" screen, but in that case you could pass it a prop to instruct it to ignore deep link navigation events.

I still think it would be convenient for a screen to be able to somehow tell if it's on the top of the navigation stack, but it's not nearly as necessary for me as before.

**Comment by guyca** [comment]
@falquaddoomi 
We'll add screen lifecycle callbacks real soon 👍
