### ISSUE TITLE
[v2] searchBar set focus

### ISSUE THREAD

**Issue by mtzfactory** [wix/react-native-navigation#4290]
Hi,

Is there a way to set focus on the topBar's searchBar?

I want control when it appears and set immediately the focus...

Thank you.

**Comment by knight-hub** [comment]
I also need this feature. As nothing seems to have happened in this issue for over a year, I'd be interested if this is being worked on and wether  / when we could expect this feature to be released.

**Comment by janpawellek** [comment]
We also need this feature.
