### ISSUE TITLE
React hooks 

### ISSUE THREAD

**Issue by tyrong** [wix/react-native-navigation#4291]
With the release of React Hooks, it would be good to test them out with RNN, has anyone managed to get this going? particularly with binding the component to listen for topBar button presses ?

**Comment by lukebrandonfarrell** [comment]
@tyrong 

You can listen to react-native-navigation events globally. Freeing your components from methods such as `componentDidAppear ` or `navigationButtonPressed({ buttonId })`, allowing you to use functional components and hooks :)

```
Navigation.events().registerNavigationButtonPressedListener(({ buttonId }) => {

});

Navigation.events().registerNavigationButtonPressedListener(({ buttonId }) => {

});
```

https://wix.github.io/react-native-navigation/v2/#/docs/events

**Comment by smooJitter** [comment]
@lukebrandonfarrell can you share an example of how you've used registerNavigationButtonPressListners globally?

**Comment by tyrong** [comment]
@lukebrandonfarrell is there any way to pass a componentId to the global listener?

**Comment by lukebrandonfarrell** [comment]
@smooJitter still working on using registerNavigationButtonPressListeners globally to make my components functional for the app we are building.

@tyrong Not that I know about :( Although I'm currently setting my app to register `componentId` in Redux when app screen state changes. Meaning the app can be controlled outside of the screens e.g. registerNavigationButtonPressListeners or remote notifications that change navigation state.

I'll share my solution once I'm done.

**Comment by tyrong** [comment]
@lukebrandonfarrell the global listener returns componentId to the call back so you can access it that way via `({ buttonId, componentId })`

**Comment by lukebrandonfarrell** [comment]
@tyrong Great to know! Going to make my job a lot easier today :)

**Comment by lukebrandonfarrell** [comment]
@loudwinston Yes I did. I have a root index.js file which contains the navigation listeners:

```
Navigation.events().registerComponentDidAppearListener(
  ({ componentId, componentName }) => {

           if (_includes(["Screen1", "Screen2"], componentName)) {
                // Update Top Left icons for Screen1 & Screen2
           }
   }
});
```

I'm also listening for button events globally:
```
Navigation.events().registerNavigationButtonPressedListener(
  ({ buttonId, componentId }) => {

  // Listen for button events
});
```

Is there anything in particular that you are having trouble with?

**Comment by loudwinston** [comment]
@lukebrandonfarrell Thanks for the example!  I am new to React Native and to `react-native-navigation`, so it is really helpful to see how you're approaching the problem.

**Comment by lukebrandonfarrell** [comment]
To customise your options through the component instead of globally (which can be quite messy in my experience) you can access the static properties directly and keep your components functional:

```
const MyFunctionalComponentScreen = ({...props}) => {
    return <View />
}

MyFunctionalComponentScreen.options = {
   bottomTab: {
    text: "My Screen",
    icon: Images.icons.home
  },
  topBar: {
    title: {
      text: "My Screen"
    }
  },
  bottomTabs: {
    drawBehind: false
  }
}

export default MyFunctionalComponentScreen;
```

@loudwinston @tyrong

**Comment by lukebrandonfarrell** [comment]
@smooJitter 

Either syntax will work.

```
MyFunctionalComponentScreen.options = {
   bottomTab: {
    text: "My Screen",
    icon: Images.icons.home
  },
  topBar: {
    title: {
      text: "My Screen"
    }
  },
  bottomTabs: {
    drawBehind: false
  }
}
```

or
```
MyFunctionalComponentScreen.options = () => {
  return {
       bottomTab: {
          text: "My Screen",
          icon: Images.icons.home
       },
       topBar: {
          title: {
             text: "My Screen"
          }
       },
       bottomTabs: {
           drawBehind: false
       }
   }
}
```

**Comment by yomybaby** [comment]
Today I try to use `useEffect` hook for RNN `NavigationButtonPressedEvent`. 
I got a hint from https://github.com/react-navigation/react-navigation-hooks
I wrote some snippet for RNN. please check this out.

```
function useNavigationEvents(handler: (event: NavigationButtonPressedEvent) => void, inputs: [any]) {
  useEffect(
    () => {
      const subsNBP = Navigation.events().registerNavigationButtonPressedListener(
        handler
      );
      return () => {
        subsNBP.remove();
      };
    },
    inputs
  );
}


function Login(props: Props) {
  useNavigationEvents(
    ({ buttonId, componentId }) => {
      if (componentId && componentId === props.componentId) {
        switch (buttonId) {
          case 'back':
            props.onPressBack!();
            break;
        }
      }
    },
    [props.componentId]
  );

 return <View/>
}

```

**Comment by dcvz** [comment]
@yomybaby here's perhaps a better version:

```tsx
export function useNavigationButtonPressed(
  handler: (event: NavigationButtonPressedEvent) => void,
  componentId: string,
) {
  useEffect(() => {
    const sub = Navigation.events().registerNavigationButtonPressedListener((event: NavigationButtonPressedEvent) => {
      if (event.componentId === componentId) {
        handler(event)
      }
    })
    return () => {
      sub.remove()
    }
  }, [componentId])
}
```

In this manner, you can make one for all types of events: `registerSearchBarUpdatedListener`, `registerNavigationButtonPressedListener`, etc.

**Comment by smooJitter** [comment]
@dcvz nice!

Could you elaborate on usage.  Maybe a few examples, please?

**Comment by immortalx** [comment]
@dcvz Nice example, it worked great. 

@smooJitter 
This works for me

```javascript
const ExploreScreen = React.memo(props => {
  useNavigationButtonPressed(e => {
    if (e.buttonId === "buttonOptions") {
      Navigation.push(props.componentId, {
        component: {
          name: "OptionsScreen"
        }
      })
    }
  }, props.componentId)

  return (
    <View style={styles.container}>
      <Text>Explore</Text>
    </View>
  )
})

ExploreScreen.options = props => {
  return {
    topBar: {
      rightButtons: [
        {
          id: "buttonOptions",
          icon: iconsMap["dots-horizontal"],
          color: colors.black
        }
      ]
    }
  }
}
export default ExploreScreen
```

**Comment by smooJitter** [comment]
@immortalx and @dcvz like a charm.

**Comment by jpgarcia** [comment]
Thank you very much for all the suggestions!

In case you find it useful we published a new `react-native-navigation-hooks` npm package to handle all the events exposed by RNN based on the snippets found here ([Github Repo](https://github.com/underscopeio/react-native-navigation-hooks)).

Feedback and contributions are welcome! 😄

**Comment by unfrgivn** [comment]
I recently refactored my app to use hook and now I am unable to set top bar options for my functional components. I tried posting on Discord as well but I can't get anywhere. To be clear my app using the static options() method + RNN2 works great, but I am unable to achieve the same thing with functional components. 

*Works (hides the top bar)*
```
class LoginScreen {

    static get options() {
        return {
            topBar: {
                visible: false,
                height: 0,
            }
        };
    }

    render() {
        return <Text>Test</Text>;
    }
};
```

*Not working (top bar visible)*
```
const loginScreen = (props) => {
    return <Text>Test</Text>;
};

loginScreen.options = {
    topBar: {
        visible: false,
        height: 0,
    }
};
```

Tried options as a function as well, but it didn't make any difference
```
loginScreen.options = () => {
    return {
        topBar: {
            visible: false,
            height: 0,
        }
    }
}
```

And in addition to working as a static method inside a class, it also still works if sending those options when calling `Navigation.push()` or if using `Navigation.mergeOptions()` inside of a `useEffect` hook but this is not ideal. 

Any help is appreciated. I'm completely baffled why this isn't working the way it is for others when I know my setup is working every way except with functional components.

react-native@0.59.10
react-native-navigation@2.27.2

**Comment by jpgarcia** [comment]
Hi @unfrgivn are you using `memo`? If so make sure you're using it before setting your options

**Will work**

```jsx
import React, { memo } from 'react'
import { Text } from 'react-native'

const Sample = memo(() => <Text>Sample</Text>)

Sample.options = () => ({
  topBar: {
    title: {
      text: 'Sample',
      color: 'red',
    },
  },
})

export default Sample
```

**Won't work**
```jsx
import React, { memo } from 'react'
import { Text } from 'react-native'

const Sample = () => <Text>Sample</Text>

Sample.options = () => ({
  topBar: {
    title: {
      text: 'Sample',
      color: 'red',
    },
  },
})

export default memo(Sample)
```

Hope it helps!

**Comment by yomybaby** [comment]
@ialmoqren It's a good point. 
@unfrgivn Can you share the `Navigation.registerComponent` code for `loginScreen` and `export default` of loginScreen?
The component registered via `Navigation.registerComponent` should have an own static option.

**Comment by unfrgivn** [comment]
@jpgarcia I am not memoizing anything, so that's not it

@yomybaby see below

The only "odd" thing I'm doing is using Mobx with its Observer HOC to re-render with specific Store property updates, but this was working fine with the same RNN when this screen component was a class. I was just using a decorator above the class for @observer in that iteration.

**Register Screens**
```
import React from 'react';
import { Navigation } from 'react-native-navigation';
import { GlobalContext } from '../contexts';

import {
  LoginScreen,
  ...
} from '../screens';

export const registerScreens = async (Stores) => {

  // Wrap all screens in my global context provider 
  const addStore = (Component, ...props) => {
      return ((props) => (
          <GlobalContext.Provider value={Stores}>  
               <Component {...props} />
          </GlobalContext.Provider> 
      ));
  };

  // Register RNN screens
  Navigation.registerComponent('navigation.myapp.LoginScreen', () => addStore(LoginScreen));
  ...
}
```

**Screen component**
```
import React, { Fragment, useEffect, useState } from 'react';
import { observer } from 'mobx-react';

import LoginForm from "../../components/LoginForm/LoginForm";
import { useStores } from '../../hooks';

import {
	KeyboardAvoidingView, 
	Platform,
	StyleSheet,
	SafeAreaView,
	View
} from 'react-native';

import { pushAuthenticatedApp } from '../../navigation';

const loginScreen = observer((props) => {

	const { App, Auth } = useStores();
	const { user: { isRegistered = false }, error, isSubmitting } = Auth || {};

	useEffect(() => {
		// If authentication runs on the login screen due to an automatic sign in then send to authenticated app
		if (isRegistered) {
			pushAuthenticatedApp();
		}
	}, [isRegistered]);

	const loginError = error ? (
		<View style={styles.errorBar}>
			<Text style={styles.errorMessage}>{(error.message || 'An error occurred').toUpperCase()}</Text>
		</View>
	) :	null;

	let loginFormContents = <LoginForm ...props />;

	if (App.loginLoading) {
		loginFormContents = <Text>Logging you in</Text>;
	}

	return (
			<SafeAreaView style={styles.safeContainer}>
				<KeyboardAvoidingView style={styles.container} behavior={Platform.OS === "ios" ? "padding" : undefined}>
					<View>	
						{loginError}								
						{loginFormContents}
					</View>
				</KeyboardAvoidingView>
			</SafeAreaView>
	);
});

// DOES NOT WORK (but did inside this component as a class as `static get options()`)
// Currently setting these options inside the `Navigation.push()` that shows this screen instead
loginScreen.options = {
	topBar: {
		visible: false,
		height: 0,
	}
};

const styles = StyleSheet.create({
	safeContainer: {
		flex: 1,
	},
	container: {
		flex: 1,
		justifyContent: 'space-evenly',
		alignItems: 'center',
	}
});

export default loginScreen;
```

**Comment by pacozaa** [comment]
@yomybaby @dcvz I try to use you guys function but got this error at `NavigationButtonPressedEvent`

`Cannot find name 'NavigationButtonPressedEvent'`

Any idea?

**Comment by vishalenrique** [comment]
@jpgarcia  It'll be really helpful if there's a mention about `react-native-navigation-hooks` in the RNN's documentation.

**Comment by jpgarcia** [comment]
@guyca what do you think? ☝️

**Comment by guyca** [comment]
@jpgarcia Yes absolutely! We're almost finished rewriting the documentation and we should definitely have a section on hooks. I personally don't have much experience with hooks, if anyone would like to contribute this - please reach out to us at the `#docs` channel on our [Discord](https://discord.gg/DhkZjq2).

**Comment by LeeJunhui** [comment]
So after five months, did you figure out the issue that static options doesn't work on functional component ? @unfrgivn

**Comment by guyca** [comment]
@LeeJunhui [Here's how to declare static options on functional components](https://wix.github.io/react-native-navigation/docs/functionalComponents#declaring-static-options).

**Comment by LeeJunhui** [comment]
@guyca I've solved the probleam, thanks 😁.
