### ISSUE TITLE
[v2][IOS] ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by williamnvk** [wix/react-native-navigation#4293]
### Issue Description

Happens when i try `react-native run-ios`.

> Installing build/Build/Products/Debug-iphonesimulator/SmallShops.app
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
> Failed to install the requested application
> The bundle identifier of the application could not be determined.
> Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
> Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/SmallShops.app/Info.plist
> Print: Entry, ":CFBundleIdentifier", Does Not Exist
> 
> Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/SmallShops.app/Info.plist
> Print: Entry, ":CFBundleIdentifier", Does Not Exist

Me `AppDelegate.m` copy from _playground_.

```
#import <React/RCTBundleURLProvider.h>
#import <ReactNativeNavigation/ReactNativeNavigation.h>
#import <React/RCTRootView.h>

#import "AppDelegate.h"
#import "RNNCustomViewController.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
	NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
	[ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];

	[ReactNativeNavigation registerExternalComponent:@"RNNCustomComponent" callback:^UIViewController *(NSDictionary *props, RCTBridge *bridge) {
		return [[RNNCustomViewController alloc] initWithProps:props];
	}];

	return YES;
}

@end

```

---
### Environment
* React Native Navigation version: 0.57
* React Native version: https://github.com/leonardoballand/react-native-navigation-rn57.git
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator
* Xcode 10.1
* OSX Mojave

**Comment by TPMinan** [comment]
Difficult to understand the problem with this output. Try to run on Xcode. The solution to the problem may be related to the scheme.

**Comment by tayfunyugruk** [comment]
@williamnvk `":CFBundleIdentifier", Does Not Exist` is a generic error that xcode throws if you go back at the terminal logs you will see the actual issue. if you can find that that will be helpful to find out the problem.

**Comment by deepakaggarwal7** [comment]
Setting File > Project Settings > Build System to Legacy Build System, resolved for me. Also, I had 8081 used by some other service so I had to change the code to make it work on 8083 (this might not be a common issue)

**Comment by ItsNoHax** [comment]
Closing as this is more of a React-Native related problem with XCode 10.
