### ISSUE TITLE
Android: Retain tab state on orientation change

### ISSUE THREAD

**Issue by lakhman** [wix/react-native-navigation#430]
Running the example on `@next - experimental`, on android, when the orientation changes, we have this fancy animation and the tab layout resets (back to the home tab). On iOS it retains the position (and no fancy animation), How can we make the android example app do the same thing (save the state of the tab bar, and remove the fancy animation).

![Imgur](http://i.imgur.com/Yccq77V.gif)

---
### Environment
* React Native Navigation version: experimental
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device

**Comment by guyca** [comment]
Thanks for reporting. Fully supporting orientation changes will be supported in v2.0, I'm closing this issue in favor of the original issue #258.
