### ISSUE TITLE
V2: backButton testID

### ISSUE THREAD

**Issue by kyledmellander** [wix/react-native-navigation#4304]
Is it possible to add a testID to the back button, or some other accessibility ID? It seems like other buttons / navbar title work, but the back button can't be accessed.

React-Native: v0.51.0
React-Native-Navigation: 2.0.2620

**Comment by Ingibjorg** [comment]
@kyledmellander did find a solution to this issue?

**Comment by jarnove** [comment]
Somebody?

**Comment by thomas-coinjar** [comment]
Detox provides a solution for that already
```
if (device.getPlatform() === 'ios') {
  await element(by.type('_UIBackButtonContainerView')).tap();
} else {
  await device.pressBack();
}
```

**Comment by jarnove** [comment]
@thomas-coinjar https://github.com/wix/react-native-navigation/blob/master/lib/src/interfaces/Options.ts#L278 :)
