### ISSUE TITLE
topBar noBorder with largeTitle makes navigationBar's backgroundColor black.

### ISSUE THREAD

**Issue by mohammadalijf** [wix/react-native-navigation#4307]
### Issue Description

when i set noBorder to true and set largeTitle, navigationBar background color changes to black.

### Steps to Reproduce / Code Snippets / Screenshots

![simulator screen shot - iphone xs max - 2018-11-11 at 00 41 19](https://user-images.githubusercontent.com/7884637/48306133-bc582000-e54b-11e8-85a6-1aeb2dd7ec32.png)

```typescript
static options(_: any): Options {
        return {
            topBar: {
                title: {
                    text: 'Some Title',
                    color: 'white',
                },
                largeTitle: {
                    visible: true,
                    color: 'white',
                },
                background: {
                    color: 'blue',
                },
                noBorder: true,
            }
        }
    }
```

---
### Environment
* React Native Navigation version: 2.1.2
* React Native version: 0.57.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator 12.1 Debug

**Comment by mlm249** [comment]
For me noBorder set to true also messes with the color of my stack navigation. I get a grey color that flashes back to white when the screen comes in

**Comment by mohammadalijf** [comment]
@mlm249 hey Mat,
i ended up creating a fork and fix issue by myself. I've created a pull request to resolve issue but main contributes did not respond. for now i am using my fork repository till they resolve this issue.

**Comment by pkyeck** [comment]
not stale ...

**Comment by masarusanjp** [comment]
Same issue

**Comment by pkyeck** [comment]
@mohammadalijf still turns black when popping the screen or pushing a new one. ever ran into this?

**Comment by mohammadalijf** [comment]
@pkyeck the forked version or the master?
no i didnt ran to that on forked version. if the fork version turns to black on pop or push please give me detail on how you pop and push screens so i can fix it

**Comment by pkyeck** [comment]
@mohammadalijf the forked version - but I realized that it only happens when you push a screen with a normal title. It's not the same problem ... but related!?

![large-title-black](https://user-images.githubusercontent.com/870980/51316332-a6d40a80-1a54-11e9-8648-529d5de4a10f.gif)

**Comment by mohammadalijf** [comment]
@pkyeck oh i see. it's not the same issue...
when you set a color to a UINavigationBar it will change the navigation bar to an opaque bar and by default iOS do not extend edges under a opaque bar... to solve this problem in native application you can use a check-mark to indicate you want to extend your ViewController's view under opaque bars...

<img width="345" alt="screen shot 2019-01-18 at 2 27 22 pm" src="https://user-images.githubusercontent.com/7884637/51382918-45cc3580-1b2d-11e9-884f-2529e89c86bf.png">

in react-native-navigation i did not find any option to change ViewController's Layout like "Adjust Scroll View Insets" which automatically adds inset to scrollview (which sometimes cause unwanted behaviors) or layout "Edge Extend".

this problem also happens when you have a pushed viewcontroller with large title and you scroll down and navigation bar gets shrink. then when you pop the view controller you will see a black area under navigation bar

**Comment by pkyeck** [comment]
@mohammadalijf thanks for explaining. where can I find the menu on the screenshot?

**Comment by mohammadalijf** [comment]
@pkyeck you're welcome. 
on xcode if you select a viewcontroller in storyboard, you can find the menu in attributes inspector 

<img width="1280" alt="screen shot 2019-01-18 at 5 26 26 pm" src="https://user-images.githubusercontent.com/7884637/51391028-39a0a200-1b46-11e9-9050-2466480154e7.png">
