### ISSUE TITLE
v2 documentation is down

### ISSUE THREAD

**Issue by nikolas7892** [wix/react-native-navigation#4313]
v2 documentation is down. All i get is a 404.
https://wix.github.io/react-native-navigation/v2/

**Comment by 8BallBomBom** [comment]
It was moved due to v2 becoming the default version now.
https://wix.github.io/react-native-navigation/

**Comment by tuannkop** [comment]
i still using v1 but now i cant find v1 document . @8BallBomBom do u know where is it ?

**Comment by 8BallBomBom** [comment]
The old docs for v1 are housed here -> https://github.com/wix/react-native-navigation/tree/v1/docs
You could download that docs folder and run the index.html file in your browser.
Not really sure if theres a github page for the v1 docs anymore.

**Comment by Brianwebb22** [comment]
Is there reason for removing all references to V1? I understand that V2 is the default now, but as someone who used react-native-navigation-v1-v2-adapter to migrate, having quick access to the adapter and V1 docs was helpful.

**Comment by 8BallBomBom** [comment]
Not really sure about that myself.
Would make sure to link the old docs somewhere.

**Comment by ItsNoHax** [comment]
As @8BallBomBom said: V2 has been officially merged into master.

V2 documentation: https://wix.github.io/react-native-navigation/#/

V1 documentation: https://github.com/wix/react-native-navigation/tree/v1/docs

**Comment by pisgithub** [comment]
[ReactNativeNavigation-WixV1Docs.pdf](https://github.com/wix/react-native-navigation/files/2715166/ReactNativeNavigation-WixV1Docs.pdf)

I've grabbed the docs from archives.org and saved in a pdf, might be helpful for others :)
