### ISSUE TITLE
Better documentation for supported versions of RN

### ISSUE THREAD

**Issue by leonardoanalista** [wix/react-native-navigation#4314]
### Issue Description

This is one of the last steps in the docs:

```
RNN only support react-native 0.51 ("reactNative51"), 0.55 ("reactNative55"), and 0.56 ("reactNative56"),```

Could we have this documented in the first step or in a separate header before "installing"?

**Comment by henrikra** [comment]
Agreed! It should be stated in first page of README which RN versions are supported. Wanna do PR for this?

**Comment by leonardoanalista** [comment]
Ok cool, it seems like we all agree here. I’ll do a pr tomorrow ok?

**Comment by henrikra** [comment]
Ok for me 👌

**Comment by leonardoanalista** [comment]
Here is the PR: https://github.com/wix/react-native-navigation/pull/4320
