### ISSUE TITLE
'React/RCTConvert.h' file not found

### ISSUE THREAD

**Issue by EgidioCaprino** [wix/react-native-navigation#4318]
### Issue Description
Can't build the project in XCode. We get the following error: `'React/RCTConvert.h' file not found`

![image](https://user-images.githubusercontent.com/5156120/48408710-48c83580-e73a-11e8-98e5-aec23cc6182a.png)

### Steps to Reproduce / Code Snippets / Screenshots

Install the dependencies listed below and follow `react-native-navigation` instructions for iOS. Then
```
npm install
react-native link
pushd ios
pod install
popd
```
Open XCode and build the application.

---
### Environment
* React Native Navigation version: 2.1.2
* React Native version: expo/react-native 30.0.0
* Platform(s) (iOS, Android, or both?): iOS (for now)
* Device info (Simulator/Device? OS version? Debug/Release?): n/a

**Comment by minhloi** [comment]
This happened to me when my project has different build configurations from ReactNativeNavigation. If you did add more build configurations to your project, use react-native-schemes-manager from npm. It will make sure all projects have the same build configurations.

**Comment by cassidylaidlaw** [comment]
I'm having the same issue trying to run the playground project.

**Comment by platonish** [comment]
this SO solution worked for me: https://stackoverflow.com/a/41488258/7414945

**Comment by ItsNoHax** [comment]
Closing as this is not a RNN related error but a general React Native issue.

**Comment by sam3d** [comment]
@ItsNoHax I believe this is a react-native-navigation error that needs addressing. The linked SO solution states:

> Note: You might still have similar header issue with other libraries (e.g. react-native-fbsdk) that are referring to those react native .h files.

Which is the case as far I can tell from the build failure output:

> ~/Desktop/expo-tests/expoTest/node_modules/react-native-navigation/lib/ios/RNNOptions.h:2:9: fatal error: 'React/RCTConvert.h' file not found
#import <React/RCTConvert.h>
        ^~~~~~~~~~~~~~~~~~~~

**Comment by saaransh** [comment]
Try excluding Header path(Option) provided by Wix. In my case it resolved the issue.

**Comment by davidmarinangeli** [comment]
@EgidioCaprino have you figured it out? I have the same problem in react-native-navigation

**Comment by enesbildiren95** [comment]
Any solution?
