### ISSUE TITLE
[v2] topBar Right Button Text is capital letter

### ISSUE THREAD

**Issue by NweThazin** [wix/react-native-navigation#4322]
### Issue Description
    static options(passProps) {
        return {
            topBar: {
                title: {
                    text: "Title",
                    alignment: "center"
                },
                rightButtons: [{
                    id: 'btn_click',
                    text: "click",
                }],
            }
        };
    }

Even though I write right button text with small letter, it becomes all capital letters when run the app.
Is there any solution for it?
thanks

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: "^2.0.2556"
* React Native version: "0.55.4"
* Platform(s) (iOS, Android, or both?): Tested on android. haven't tried on iOS
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by MEsteves22** [comment]
I'm having the same problem... Has someone found the solution?

**Comment by NweThazin** [comment]
@MEsteves22 

react native navigation folder -> res -> values -> styles.xml
put "<item name="textAllCaps">false</item>" in TopBar style tag
thanks

**Comment by MEsteves22** [comment]
@NweThazin thank you, it works!

**Comment by JimmyDLA** [comment]
Ummmm... what? 
I think i found the folder and file but not sure.
Can you be a little more specific what to add and where?

**Comment by JimmyDLA** [comment]
AWESOME! 
To be more specific, navigate to:
`android/app/src/main/styles.xml`
Then just add: `<item name="textAllCaps"> false </item>`
