### ISSUE TITLE
[V2] Dynamically setting back button title doesn't work

### ISSUE THREAD

**Issue by michaelcurtis** [wix/react-native-navigation#4324]
### Issue Description

Attempting to dynamically set the backButton title doesn't work. I am able to set other attributes of the topBar dynamically (like title), but backButton title doesn't update. 

Here is how I reproduce: 

```
export class Test extends React.Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {
    Navigation.mergeOptions(this.props.componentId, {
      topBar: {
        title: {text: 'foo'},
        backButton: {
          title: 'bar'
        }
      }
    });
  }

  render() {
    return <View/>;
  }
}
```

Expected behavior: title updates to 'foo', backButton title updates to 'bar'. 

Actual behavior: title updates to 'foo', backButton title doesn't update.

---
### Environment
* React Native Navigation version: react-native-navigation@2.1.3
* React Native version: react-native@0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X simulator and physical device running 12.1 (16B92)

**Comment by yusufyildirim** [comment]
Have you tried it with static options() like this https://wix.github.io/react-native-navigation/#/docs/styling?id=styling-options

**Comment by michaelcurtis** [comment]
I have yes. It works correctly with static options. 

```
static options(passProps) {
  return {
    topBar: {
      backButton: {
        title: 'foo'
      }
    }
  };
}
```

It also works correctly if I pass the backButton title when pushing the screen. Unfortunately I need to  update it dynamically while on the screen, which doesn't work. Thanks in advance!

**Comment by michaelcurtis** [comment]
Confirmed this is still an issue with react-native-navigation@2.4.0.

**Comment by michaelcurtis** [comment]
Confirmed this commit fixes it: https://github.com/wix/react-native-navigation/commit/84349384958ee9f0d03d24c6ef087cc5b7661d4b

Thanks!

**Comment by samcampisi** [comment]
I'm having this problem with version 2.8.0... 

Navigation.mergeOptions(this.props.componentId, {
      topBar: {
        title: {text: 'foo'},
        backButton: {
          title: 'bar'
        }
      }
});

this does not update the back button title to "bar". I've tried setting showTitle to true but still see no change in the back button title. Other options like icon do work but I need the title to change.

**Comment by Slessi** [comment]
I am also having this issue in `2.8.0` - backButton title does not override the topBar title

**Comment by LoganArnett** [comment]
This still appears to be an issue, currently using 2.18.2
