### ISSUE TITLE
[V2] ScrollView/FlatList after changing route/pushing/showing modal while there is a momentum scroll

### ISSUE THREAD

**Issue by minhloi** [wix/react-native-navigation#4325]
### Issue Description
This is the similar bug that happened in V1 and it got fixed but now it comes back in V2.
[#1446](https://github.com/wix/react-native-navigation/issues/1446)

### Steps to Reproduce / Code Snippets / Screenshots
1. Scroll few items.
2. While there is a momentum scrolling => switch to the 2nd tabbar screen
3. Return to the 1st screen and try to click a FlatList cell => cells are not responsive.

---
### Environment
* React Native Navigation version: 2.1.2
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device, IOS 1.2.1, Debug/Release

**Comment by exentrich** [comment]
Issue is still exist on latest RNN

**Comment by flikQ** [comment]
@guyca how come there are so many bugs and issues being closes and moved to 'done' when they are not fixed?

I am curious on the reasoning of the team/contributors that are leaving bugs unfixed but marking them as fixed.

Specifying them as closed won't make the issues go away.

**Comment by minhloi** [comment]
It is because they are refactoring the architecture so some bugs reappear.

**Comment by wellcode** [comment]
Have the same problem, is there a plan to fix it?

**Comment by Crisis2010** [comment]
Still exist, need fix

**Comment by manuhook** [comment]
Any update on this problem ?
Thanks 🙏

**Comment by minhloi** [comment]
Sorry. I was able to fix this issue for by stopping the momentum scroll before pushing screen or showing modal. 

I'm busy fixing my other issues so I haven't submitted a pull request yet. I will do it once I have time.

You can see my forked version for the fix.

https://github.com/minhloi/react-native-navigation/commit/108e9b3b2d489916c92d3e9a6b0d461759915ea1#diff-54fb69abd59c84c3119510a4ae58d80a

**Comment by exentrich** [comment]
@minhloi thank you very much! Would be great if you find a time to make pull request!

**Comment by manuhook** [comment]
@minhloi thanks a lot ! I will be also very grateful if you can make a pull request as the problem is still present on RNN V3.
Thanks again !

**Comment by manuhook** [comment]
Hi @yogevbd 

Please can you add those changes on master ? 
This issue is still present on V4 and and our iOS users regularly complain about it since a long time.
https://github.com/minhloi/react-native-navigation/commit/108e9b3b2d489916c92d3e9a6b0d461759915ea1#diff-54fb69abd59c84c3119510a4ae58d80a

Thanks you !

**Comment by nenjamin2405** [comment]
Hi, I'm facing the same issue, it's quite annoying, is there any plan to add the changes from @minhloi to the master :(

**Comment by nenjamin2405** [comment]
Hi @guyca, I'm still facing this issue in the `"react-native-navigation": "^6.9.0"` on iOS. It's quite annoying, is there any plan to add the changes from @minhloi to the master :( . Thank you

**Comment by manuhook** [comment]
Hi @yogevbd, unfortunatly I'm still having the issue with "**react-native-navigation 6.12.0**".
I'm not seeing any chance with your patch. I'm simply doing what's it's described on the issue : 
On the first Tab Scroll few items.
While there is a momentum scrolling => switch to the 2nd tabbar screen
Return to the 1st screen and try to click a FlatList cell => cells are not responsive.

**Comment by manuhook** [comment]
It's working when you add this 2 lines on **RNNBottomTabsController.m** :

line 3 : 
#import "UIView+Utils.h"

line 161 : 
[self.view stopMomentumScrollViews];
