### ISSUE TITLE
Replicate iOS viewWillAppear callback.

### ISSUE THREAD

**Issue by LukeDefeo** [wix/react-native-navigation#4329]
How do I replicate iOS viewWillAppear callback. This is extremely use-full to refresh when someone navigates back or switches tab. But you want to kick something off before the screen is shown

### Environment
* React Native Navigation version: V2
* Platform(s) (iOS, Android, or both?): iOS

**Comment by yusufyildirim** [comment]
https://wix.github.io/react-native-navigation/#/docs/events

**Comment by LukeDefeo** [comment]
I've read that but there is only the did appear callback no will appear
