### ISSUE TITLE
[v2] Can't get TopBar to show on Modal

### ISSUE THREAD

**Issue by deecewan** [wix/react-native-navigation#4336]
### Issue Description

May be related to #3982 

I have tried every way I know how of setting things so that a top bar will appear on the modal.  First, `static options` on the Modal screen component. Second, `Navigation.mergeOptions` in the constructor of the Modal screen component.
Third, Options passed to the `Navigation.showModal` - all result in no top bar being visible.

#### static options

```js

class ModalComponent extends Component {
  // ...
  static options() {
    return {
      statusBar: {
        backgroundColor: color.NAV_BAR_BACKGROUND_DARKEN,
      },
      topBar: {
        title: {
          text: 'TESTING',
        },
        visible: true,
        drawBehind: false,
        background: {
          color: color.NAV_BAR_BACKGROUND,
        },
        leftButtons: [{
          title: 'Close',
          id: 'closeModal',
          icon: require('../../../images/navIcons/close.png'),
          disableIconTint: true,
        }],
      },
    };
  }
}
```

#### constructor
```js
  constructor() {
    Navigation.mergeOptions(this.props.componentId, {
      statusBar: {
        backgroundColor: color.NAV_BAR_BACKGROUND_DARKEN,
      },
      topBar: {
        title: {
          text: 'TESTING',
        },
        visible: true,
        drawBehind: false,
        background: {
          color: color.NAV_BAR_BACKGROUND,
        },
        leftButtons: [{
          title: 'Close',
          id: 'closeModal',
          icon: require('../../../images/navIcons/close.png'),
          disableIconTint: true,
        }],
      },
    })
  }
```

---
### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.57.3
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iOS 12. Emulator Android 7

**Comment by willfulbard** [comment]
Is your modal a stack, or component?  I'm pretty sure only stacks can have that top nav bar.

**Comment by deecewan** [comment]
interesting! i didn't even consider passing a whole new stack layout to the modal. that should work 👍

**Comment by ItsNoHax** [comment]
@willfulbard is correct. Only stack's contain a top bar.

**Comment by Reidweb1** [comment]
I'm seeing this issue when using a stack as well. This is the Modal I'm showing and the topbar is completely blank.

```
Navigation.showModal({
      stack: {
        children: [{
          component: {
            name: NavigationKeys.Club,
            passProps: props
          }
        }],
        options: {
          topBar: {
            drawBehind: false,
            visible: true,
            backButton: {
              visible: true,
              title: 'CANCEL',
              showTitle: true
            },
            title: {
              text: 'MODAL'
            }
          }
        }
      }
    })
```

Versions:
"react-native-navigation": "^2.10.0"
"react-native": "0.58.4"

Any idea on why that wouldn't show?

**Comment by hossamnasser938** [comment]
the same here on IOS. Works well on Android. Is there an issue with showing top bar with modal on IOS?

**Comment by hossamnasser938** [comment]
For me on IOS it worked only when I merged options in constructor. Both passing options to showModal and setting static options did not work on IOS
