### ISSUE TITLE
[V2] [Android] BottomTabs component does not apply testID

### ISSUE THREAD

**Issue by robertofrontado** [wix/react-native-navigation#4338]
### Issue Description
BottomTabs component doesn't apply defined testID in Android. iOS is working as expected.

### Steps to Reproduce / Code Snippets / Screenshots
Define your BottomTabs stack using testID, like this:
```
const createBottomTabStack = ({ name, text, icon }) => ({
  stack: {
    children: [
      {
        component: {
          name,
          options: {
            bottomTab: {
              text,
              icon,
              testID: `tab-${name}`
            }
          }
        }
      }
    ]
  }
})
```
Expected: testID is set in each tab so the tab can be found by id / accessbilityLabel when doing automation. (Using [Detox](https://github.com/wix/Detox))

Actual: testID is not present so the tab cannot be found.

View Hierarchy:
```
+--------->FrameLayout{id=2131755186, res-name=bottom_navigation_container, visibility=VISIBLE, width=252, height=147, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@3d6bbee, tag=null, root-is-layout-requested=false, has-input-connection=false, x=288.0, y=0.0, child-count=3} 
|
+---------->AppCompatImageView{id=2131755187, res-name=bottom_navigation_item_icon, visibility=VISIBLE, width=63, height=63, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@7c4b88f, tag=null, root-is-layout-requested=false, has-input-connection=false, x=94.0, y=21.0} 
|
+---------->AHTextView{id=2131755188, res-name=bottom_navigation_item_title, visibility=VISIBLE, width=252, height=28, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@c98571c, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=101.0, text=REWARDS, input-type=0, ime-target=false, has-links=false} 
```
As you can see the `tag` of the FrameLayout is `null`

### Environment
* React Native Navigation version: 2.0.2620
* React Native version: 0.54.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Any - tested mostly in simulator

**Comment by minhloi** [comment]
I have this issue too and I found what's causing this. On android, ReactNativeNavigation uses AHBottomNavigation internally. AHBottomNavigation recreates the views whenever you change something to the bottom tabs (like setTtitleTextSize) thus the tags become null.

https://github.com/aurelhubert/ahbottomnavigation/blob/c4114c23213f0e86216f75b2770964dbc02eebb0/ahbottomnavigation/src/main/java/com/aurelhubert/ahbottomnavigation/AHBottomNavigation.java#L1134-L1136
