### ISSUE TITLE
page listens when it is live again

### ISSUE THREAD

**Issue by tzookb** [wix/react-native-navigation#434]
### Issue Description

I have a page that inside itself it decides to push another page.

now when the pushed page, performs pop to go back,
I'm suppose to go back to the first page.

Up to here all is good...

But now I want that the first page will know, he is visible again...

any ideas how?

something like: componentIsVisible()

**Comment by guyca** [comment]
Hey @tzookb 
Screen lifecycle events will be added in v2.0. I don't have an eta to give you. This question has been asked a couple of times and I've described workarounds in those issues that you might be able to use in the mean time.
Thanks for the patience. 👍

**Comment by tzookb** [comment]
Thanks @guyca 

surely wait, for now do a quick hack

thanks
