### ISSUE TITLE
[v2] Centering of TopBar text doesn't update until tabs are switched

### ISSUE THREAD

**Issue by deecewan** [wix/react-native-navigation#4340]
### Issue Description

I'm trying to center the top bar text of one (out of three) of my tabs. I can do this with the following:

```js
Navigation.mergeOptions(this.props.componentId, {
  topBar: {
    title: {
      alignment: 'center',
      text: <varies in length per render>,
    },
    subtitle: {
      alignment: 'center',
      text: 'Subtitle',
    },
  },
});
```

But, there are two problems with this:

Firstly, on the initial boot, the text is still left-aligned.

![image](https://user-images.githubusercontent.com/4755785/48811176-4d16d300-ed78-11e8-9437-e36b2347dcbe.png)

Changing tabs, then coming back, recenters the text:

![2018-11-21 10 29 20](https://user-images.githubusercontent.com/4755785/48811191-6cadfb80-ed78-11e8-8bd6-42bc072bf866.gif)

Secondly, when the title changes, it sometimes becomes offset from the actual center, and only fixes when tabs are changed:

![2018-11-21 10 30 38](https://user-images.githubusercontent.com/4755785/48811233-92d39b80-ed78-11e8-92d4-d217242b0b62.gif)

Before switching tabs:
![image](https://user-images.githubusercontent.com/4755785/48811258-ada61000-ed78-11e8-8a2b-34a701908aec.png)

After:

![image](https://user-images.githubusercontent.com/4755785/48811272-b39bf100-ed78-11e8-9a2c-9de5631c2d16.png)

Is there any way to have the text centered from the start (I am calling `Navigation.mergeOptions` in `componentDidMount`), and also have it recenter itself if the length changes?
This worked in v1, so I'm surprised it's so difficult in v2.

### Steps to Reproduce / Code Snippets / Screenshots

See above

---
### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.57.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator Android 7

**Comment by minhloi** [comment]
Have you tried to put the code in static options() instead of Navigation.mergeOptions()?

**Comment by deecewan** [comment]
I have tried there, too. Exact same problem.

Let me confirm that that is the case, tho.

**Comment by minhloi** [comment]
I'm using setDefaultOptions and it works fine. Every screen has a title in the center.
```
Navigation.setDefaultOptions({
    topBar: {
      title: {
        alignment: "center"
      }
    }
})

```

**Comment by samiede** [comment]
This is still an issue!

**Comment by guyca** [comment]
@samiede Which version of RNN are you observing this on?
