### ISSUE TITLE
I can not find Document WIX navigator version 1

### ISSUE THREAD

**Issue by SittisukChartrasee** [wix/react-native-navigation#4342]
### Issue Description

I can not find Document WIX navigator version 1

### Environment
* React Native Navigation version: "^1.1.480"
* React Native version: "0.53.2"
* Platform(s) (iOS, Android, or both?): IOS, Android

**Comment by heron2014** [comment]
Related issue - https://github.com/wix/react-native-navigation/issues/4294

**Comment by ItsNoHax** [comment]
Duplicate issue

Link is at: https://github.com/wix/react-native-navigation/tree/v1/docs

**Comment by jdegger** [comment]
We published it through gh-pages https://x-guard.github.io/react-native-navigation
