### ISSUE TITLE
[v2][Android] registerComponentDidAppearListener doesn't work on sideMenu

### ISSUE THREAD

**Issue by diegolmello** [wix/react-native-navigation#4345]
### Issue Description
Hey, guys.
Since RNN doesn't have toggleSideMenu implemented yet, we need to do some hack like below.
The problem I noticed is that `Navigation.events().registerComponentDidAppearListener` works perfectly on iOS for sideMenu, but it doesn't on Android.

### Steps to Reproduce / Code Snippets / Screenshots

```jsx
import { Navigation } from 'react-native-navigation';

const DRAWER_ID = 'Sidebar';

class Drawer {
  constructor() {
    this.visible = false;

    Navigation.events().registerComponentDidAppearListener(({ componentId }) => {
      if (componentId === DRAWER_ID) {
        this.visible = true;
      }
    });

    Navigation.events().registerComponentDidDisappearListener(({ componentId }) => {
      if (componentId === DRAWER_ID) {
        this.visible = false;
      }
    });
  }

  toggle() {
    try {
      const visibility = !this.visible;
      Navigation.mergeOptions(DRAWER_ID, {
        sideMenu: {
          left: {
            visible: visibility
          }
        }
      });
      this.visible = visibility;
    } catch (error) {
      console.warn(error);
    }
  }
}

export default new Drawer();
```

---
### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.57.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Moto G5 Plus. Android 8.1.

**Comment by MariaTolstov** [comment]
Hey,
Is there anything new on this?

**Comment by augustl** [comment]
Not sure if this is related, but I just noticed that every now and then, the side menu component I've specified has its "render" method called, but the actual side menu GUI doesn't update.

**Comment by diegolmello** [comment]
Sorry, bot.
Up this one :)

**Comment by manelsanz** [comment]
The only way I achieved that a button close the sideMenu and that it could get invoked by a gesture after (without that hides automatically) is with that snippet:

```
  toggleOffSideMenu = () => {
    Navigation.mergeOptions(this.props.componentId, {
      sideMenu: {
        left: {
          enabled: false
        }
      }
    });
     Navigation.mergeOptions(this.props.componentId, {
       sideMenu: {
         left: {
           enabled: true
         }
       }
     });
  };

```

**Comment by marudy** [comment]
Hey @diegolmello did you manage to trigger `Navigation.events().registerComponentDidAppearListener` on Android? I face the same issue.

* React Native Navigation version: 2.2.1
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Real device: Samsung A5 2017

**Comment by JulianoMajally** [comment]
Am still facing this issue of the sideMenu on android, how can i close/open the sidemenu using a button
