### ISSUE TITLE
[Feature Request] DismissAllOverlays function

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#4346]
### Feature Request

In our application there are times when we need to force logout the user. To achieve this currently we need to dismissAllModals and then dismiss each overlay by name. Ideally we would be able to dissmissAllOverlays too.

**Comment by oferRounds** [comment]
How easy will this be to add to v6? Is this also a "good first task"?

**Comment by guyca** [comment]
Should be fairly easy, yes this is also a good first task (as the label indicates)

**Comment by oferRounds** [comment]
Yes, saw the label – but wasn’t sure if it’s still applicable for the current version, as this was 2 years ago
