### ISSUE TITLE
[V2] Top bar title is not showing

### ISSUE THREAD

**Issue by bdavid68** [wix/react-native-navigation#4347]
### Issue Description

Top bar title is not showing on iOS as expected to see `Dashboard`.
I see only bottom border of top bar.

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
Navigation.setRoot({
    root: {
      stack: {
        children: [{
          component: {
            name: 'DashboardScene',
          }
        }],
        options: {
          topBar: {
            title: {
              text: 'Dashboard'
            }
          }
        }
      }
    }
  });
```

---
### Environment
* React Native Navigation version: 2.0.2641
* React Native version: 0.57.0
* Platform(s) (iOS, Android, or both?): iOS(Not sure for android yet)
* Device info (Simulator/Device? OS version? Debug/Release?): Device/Debug

**Comment by vshkl** [comment]
@bdavid68 try to move that `options` to the `component`. LIke so:
```es6

  component: {
    ...
    options: {
      topBar: {
        ...
        title: {
          text: 'Title',
        },
      },
    },
  },
}
```

**Comment by bdavid68** [comment]
Thanks, @vshkl. It works!

**Comment by elbrodelche** [comment]
Thanks!. This should be updated on the oficial docs.
