### ISSUE TITLE
'titleImage' not working

### ISSUE THREAD

**Issue by PaulRBerg** [wix/react-native-navigation#435]
I try to set an image on the navigation bar, but it simply doesn't work. I've seen #378 and implemented this:

```
constructor(props) {
    super(props);
    props.navigator.setTitle({
      title: "Home",
      titleImage: require('../../images/home.png'),
    })
  }
```

But when I run the application only the text 'Home' is on the navigation bar. Also, I tried without the 'title' key, but the results were disappointing again (now I was left with an empty navigation bar).

Any solutions?

* React Native Navigation version: 2.0.0-experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by lakhman** [comment]
Seems to work for me, are you sure your image path can be resolved?

I used react-native-vector-icons to generate an image and then set it as the `titleImage` - also in the constructor.

```
Icon.getImageSource('home', 22, '#FFF').then((source) => {
    props.navigator.setTitle({
        title: "NONE",
        titleImage: source,
    });
});
```

![screen shot 2016-11-19 at 21 39 37](https://cloud.githubusercontent.com/assets/1582690/20458648/77383cda-aea2-11e6-8187-2669fd2c839f.png)


I'm using:

- React Native Navigation version: 2.0.0-experimental.141  
- react-native-cli: 1.2.0
- react-native: 0.37.0
