### ISSUE TITLE
initialTabIndex not working in ios

### ISSUE THREAD

**Issue by arbabi2010** [wix/react-native-navigation#4352]
### Issue Description

Hello , initialTabIndex in Navigation.startTabBasedApp not working in IOS and show me first tab . i set 
initialTabIndex = 3 but first is selected. 
### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 1.1.493
* React Native version: 0.51.1
* Platform (iOS)
* Device info (Simulator/Device? OS version? Debug/Release?): iphone SE , debug

**Comment by henrikra** [comment]
Can you share code that you used to do this? Because I would like to compare it to mine because I noticed the same bug :/

**Comment by arbabi2010** [comment]
@henrikra I use document code. This problem exist in 1.1.493 version for me. Downgrade to 1.1.491 and work now properly

**Comment by henrikra** [comment]
Ah I am using version 2.1.3
