### ISSUE TITLE
handleDeepLink documentation missing

### ISSUE THREAD

**Issue by nicoara** [wix/react-native-navigation#4356]
### Issue Description
Where is the online documentation for "handleDeepLink"?? Can you provide a link? It seems I suddenly cannot find elements in the documentation any more. 
Thanks

**Comment by guyca** [comment]
RNN Deeplinks are not implemented in v2 as this isn't a navigation concern.

**Comment by RichardLindhout** [comment]
It's really easy with the Linking library from React Native ;)
https://facebook.github.io/react-native/docs/linking.html
