### ISSUE TITLE
Not able to integrate youtube player

### ISSUE THREAD

**Issue by praveenapoojary** [wix/react-native-navigation#4358]
### Issue Description

I am trying to integrate youtube android player and it is always throwing an [overlay error](https://stackoverflow.com/questions/16067783/android-youtubeplayer-with-unauthorized-overlay-on-top-of-player) but I tried shwoing my componet which has native youtube player as overlay using showOverlay api and it works perfeclty fine. 

### Steps to Reproduce / Code Snippets / Screenshots
Use this [library](https://github.com/inProgress-team/react-native-youtube) to reproduce the error.
---
### Environment
* React Native Navigation version: ^2.0.2641
* React Native version: 0.57.4
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): All android phones

**Comment by praveenapoojary** [comment]
@guyca  There is some kind of overlay in RNN component which is stopping Youtube. This is definitely not `stackoverflow` question.

**Comment by Praveena0989** [comment]
@guyca I am getting this error `The YouTubePlayerView is obscured by android.widget.FrameLayout`
Do you guys create overlay `framelayout` in every component?
