### ISSUE TITLE
How to use with Apollo client and other-like libraries

### ISSUE THREAD

**Issue by gutenye** [wix/react-native-navigation#436]
Apollo client and other-like libraries needs wrap root component:

```
<ApolloProvider client={client}>
    <MyRootComponent />
  </ApolloProvider>
```

Is there a working example?

**Comment by brianjd** [comment]
@gutenye This was discussed in #69.

**Comment by jnsone11** [comment]
In case anyone comes across this:

```
import {ApolloProvider} from "react-apollo";

export const registerScreens = (results) => {
    const {store, apollo_client} = results[1];
    return new Promise((resolve) => {
        Navigation.registerComponent('user.TopTabsScreen', () => TopTabsScreen, store, ApolloProvider, {client: apollo_client});
        Navigation.registerComponent('user.FeedScreen', () => FeedScreen, store, ApolloProvider, ApolloProvider, {client: apollo_client});
        resolve();
    });
};
```

**Comment by nicedexter** [comment]
@jnsone11 What do you call the store in this sample?

**Comment by jnsone11** [comment]
@nicedexter Not sure if I understand correctly. store is the redux store.
I created a redux store and injected it into apollo client.

**Comment by nicedexter** [comment]
That make sense,  I didn't see what was the store in the Apollo context, I use it without redux. 
Thanks for the hint

**Comment by perrosnk** [comment]
@jensneuse How do you access client within the Component? I don't see the client within this.props when using your code
Thank you!
