### ISSUE TITLE
 title alignment center move when push component

### ISSUE THREAD

**Issue by JackGZY** [wix/react-native-navigation#4360]
### Issue Description

title alignment center move when push component

### Steps to Reproduce / Code Snippets / Screenshots

![ezgif-4-3a27bab2db53](https://user-images.githubusercontent.com/19221577/49003079-2a335700-f19c-11e8-8b78-4beb7bc17af5.gif)

---
### Environment
* React Native Navigation version: 2.1.3
* React Native version:0.55.0
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by ItsNoHax** [comment]
This is just the default animation in Android. You can look in the documentation about how to change them.
