### ISSUE TITLE
Disable Drawer for specific screens 

### ISSUE THREAD

**Issue by Rogger98** [wix/react-native-navigation#4361]
- ###

i wan to disable drawer's swipe gesture for specific screens 

### Steps to Reproduce / Code Snippets / Screenshots

const HomeCntrl = createStackNavigator({
    Home:{screen:HomeController},
    SelectPhotos:{screen:SelectImageController,navigationOptions:{
        gesturesEnabled:false,
        drawerLockMode: 'locked-closed'
    }},
    Facility:{screen:FacilitiesRulesController},
    PrintPreview:{screen:PrintPreviewController},
    AddMsg:{screen:AddMessageController},
    payment:{screen:PaymentOptionsController},
    cardPayment:{screen:CardPaymentController}
})
const OrderHistry = createStackNavigator({
    OrderHistory:{screen:OrderHistoryController}
})
const Contacts = createStackNavigator({
    Contacts:{screen:ContactsController}
})
const Pelipointscntrl = createStackNavigator({
    Pelipoints:{screen:PelipointsController},
    Earn:{screen:EarnPointsController,navigationOptions:{
        gesturesEnabled:false
    }},
    Redeem:{screen:RedeemPointsController,navigationOptions:{
        gesturesEnabled:false
    }}
})
const Pricingcntrl = createStackNavigator({
    Price:{screen:PricingController}
})
const returncntrl = createStackNavigator({
    Return:{screen:ReturnPolicyController}
})
const myacntcntrl = createStackNavigator({
    MyAccount:{screen:MyAccountController}
})
const Primary = createDrawerNavigator({
    Home:{screen:HomeCntrl},
    'Order History':{screen:OrderHistry},
    Contacts:{screen:Contacts},
    Pelipoints:{screen:Pelipointscntrl},
    Pricing:{screen:Pricingcntrl},
    'Return Policy':{screen:returncntrl},
    'My Account':{screen:myacntcntrl}
})
const AppStack = createStackNavigator({
    Login:{screen:LoginController},
    Home:{screen:Primary,navigationOptions:{header:null, gesturesEnabled: false,drawerLockMode:'locked-closed'}}
})

---
### Environment
* React Native Navigation version: 2.18.2
* React Native version: 0.44.2

**Comment by ItsNoHax** [comment]
This looks like code for React-Navigation. You are posting this in the wrong github repository.
