### ISSUE TITLE
title in TopBar does not appear

### ISSUE THREAD

**Issue by morelearn1990** [wix/react-native-navigation#4363]
### Issue Description

when i put a buttomTabs in a stack title option in TopBar does not appear

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.setRoot({
  root: {
    stack: {
      children: [
        {
          bottomTabs: {
            children: [
              {
                component: {
                  name: 'screens.fixedloss.AGRO.Working'
                }
              },
              {
                component: {
                  name: 'screens.fixedloss.AGRO.Worked'
                }
              },
              {
                component: {
                  name: 'screens.fixedloss.AGRO.Completed'
                }
              }
            ]
          }
        }
      ]
    }
  }
});
```

options in screen:
```
{
    topBar: {
      visible: true,
      animate: true,
      buttonColor: '#fff',
      background: {
        color: ‘#666’
      },
      backButton: {
        visible: false,
        icon: require('../../../assets/backburger.png')
      },
      title: {
        color: '#fff',
        fontSize: 18,
        text: '列表'
      },
      leftButtons: [
        {
          color: '#fff',
          id: 'nav-btn-back',
          text: '返回'
        }
      ],
      rightButtons: [
        {
          color: '#fff',
          id: 'nav-btn-filter',
          text: '筛选'
        }
      ]
    },
    bottomTab: {
      text: config.bottomTabtext,
      icon: icons[config.iconName],
      iconColor: config.color,
      selectedIconColor: config.selectColor,
      textColor: config.color,
      selectedTextColor: config.selectColor
    }
  }
```

bottomTab and topBar background is ok

![image](https://user-images.githubusercontent.com/18624210/49069291-e2780280-f263-11e8-8477-ba64cf793bb6.png)

---
### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.57.5
* Platform(s) (iOS, Android, or both?): IOS(android dont know)
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6  IOS 12.1

**Comment by DarianNwankwo** [comment]
@morelearn1990 I believe I had a similar issue when reading the documentation. The code provided [here](https://wix.github.io/react-native-navigation/#/docs/top-level-api-migration?id=showmodalparams-showmodallayout-) has the options outside of the children's array component, but I changed it to look like this and I was able to get the title on my application.

Before
`Navigation.setRoot({
  root: {
    stack: {
      children: [{
        component: {
          name: 'example.WelcomeScreen',
          passProps: {
            text: 'stack with one child'
          }
        }
      }],
      options: {
        topBar: {
          title: {
            text: 'Welcome screen'
          }
        }
      }
    }
  }
});`

After
`Navigation.setRoot({
  root: {
    stack: {
      children: [{
        component: {
          name: 'example.WelcomeScreen',
          options: {
            topBar: {
              title: {
                text: 'Welcome screen'
              }
            }
          },
          passProps: {
            text: 'stack with one child'
          }
        }
      }],
    }
  }
});`

I hope this helps.

**Comment by LRNZ09** [comment]
I'm having the same issue on `2.7.1`

**Comment by nvthuong** [comment]
@morelearn1990 
Add title in the bottomTabs pls add the static method on your component 

like this:

static options(passProds){
        return {
            topBar: {
                title: {
                    text: "Name title"
                }
            }
        };
    }
