### ISSUE TITLE
iOS Stuck on Splash Screen

### ISSUE THREAD

**Issue by schvetsov** [wix/react-native-navigation#4365]
### Issue Description

I have followed the installation instructions exactly for RN Navigation on a fresh instance of RN. I am at a loss of what to do, but the error starts when I edit the appdelegate.m file in xcode per the instructions. Is anyone else having this problem? Is there anything else I can try?

EDIT: I attempted changing the index.js file to this:

```
import {Navigation } from 'react-native-navigation';
import App from './App';

Navigation.registerComponent('example.HomeScreen', () => App);
Navigation.startSingleScreenApp({
    screen: {
        screen: 'example.HomeScreen',
        title: 'Welcome'
    }
});
```

And it gives me the following error: "_reactNativeNavigation.navigation.startSingleScreenApp is not a function ... "

FIXED:
If you scroll down all the way to the bottom (past the Android instructions) there is an additional step where it tells you to add code to the index.js file. I made my index.js file look like this and the app is now working: 

```
import { Navigation } from "react-native-navigation";
import App from "./App";

Navigation.registerComponent(`navigation.playground.WelcomeScreen`, () => App);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      component: {
        name: "navigation.playground.WelcomeScreen"
      }
    }
  });
});
```

Additionally, on another project I had to upgrade my RN version to the latest version (0.57.7) and it also started working.

### Steps to Reproduce / Code Snippets / Screenshots

Just follow the iOS RNN installation instructions

---
### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by ItsNoHax** [comment]
Glad you managed to fix your problem.
