### ISSUE TITLE
Android navBarCustomView does not work in last tab

### ISSUE THREAD

**Issue by UtkucanBykl** [wix/react-native-navigation#4367]
### Issue Description
navBarCustomView does not work on android.
It works very well in the first 4 tabs. But in the last tab, navBarCustomView does not work. Even if I change the number of tabs, the last tab still doesn't work.

### Steps to Reproduce / Code Snippets / Screenshots

`
export const navigatorStyle = {
  ...Platform.select({
    android: {
      navBarCustomView: 'CustomNavBar',
      drawUnderTabBar: true,
    },
  }),
  navBarTextColor: '#5A6866',
  navBarBackgroundColor: 'rgb(243, 243, 243)',
  navBarTitleTextCentered: true,
  topBarElevationShadowEnabled: false,
  navBarNoBorder: true,
};
`

---
### Environment
* React Native Navigation version: 1.1.328
* React Native version: 0.53.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
Interesting, can you please PR a failing detox test?
