### ISSUE TITLE
com.github.wix-playground:reflow-animator:1.0.4 can't found

### ISSUE THREAD

**Issue by nuaahuang** [wix/react-native-navigation#4368]
### Issue Description
com.github.wix-playground:reflow-animator:1.0.4 can't found

i try my best to find com.github.wix-playground:reflow-animator:1.0.4. but  i can't . Can do me a favour , thanks
### Steps to Reproduce / Code Snippets / Screenshots
![image](https://user-images.githubusercontent.com/4338137/49149140-45d96180-f344-11e8-8376-8e77e5c34f00.png)

---
### Environment
* React Native Navigation version: ^2.1.3
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by JanPeter** [comment]
How did you fix it?

**Comment by witalobenicio** [comment]
@nuaahuang how did you solve this?

**Comment by chrisparton1991** [comment]
@witalobenicio I had this same issue as well (react-native v0.60.14, react-native-navigation 3.2.0).

My problem was that I forgot to add `maven { url 'https://jitpack.io' }` to my `android\build.gradle` file. Adding that got me past this issue.
