### ISSUE TITLE
Render title components before the screen

### ISSUE THREAD

**Issue by yedidyak** [wix/react-native-navigation#4369]
Since rendering of screens is generally more computationally expensive than header components, sometimes there can be a noticeable lag between the render of the screen and render of components in the title or top buttons. 

To solve this we could try and swap the order, so that the lighter components do not have to wait for the heavier ones.

* React Native Navigation version: 2.1.3
* React Native version: 51
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by denieler** [comment]
Yeah, I've noticed this lag as well in my application after moving from v1 to v2.

**Comment by novakben** [comment]
Hi! Any updates here?
Thanks

**Comment by guyca** [comment]
As iOS implementation got delayed a bit, I think I'll move on and merge Android implementation next week.

**Comment by guyca** [comment]
You can now use the `waitForRender` option on both platforms to show the ui after both title component and root content have been rendered.

```js
options: {
  animations: {
    setRoot: {
      waitForRender: true
    }
  }
}
```

Make sure to add `waitForRender: true` in the `title.component` as well.

```js
topBar: {
  title: {
    component: {
      name: 'myComponent',
      waitForRender: true
    }
  }
}
```
