### ISSUE TITLE
Can't handle back button press globally

### ISSUE THREAD

**Issue by D0vydas** [wix/react-native-navigation#4370]
### Issue Description

When clicking back button neither of `registerCommandListener` or `registerNavigationButtonPressedListener` callbacks are fired.

### Environment
* React Native Navigation version: 2
* React Native version:
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by denieler** [comment]
I use

```
BackHandler.addEventListener('hardwareBackPress', this.handleBackPress)
```

in `componentDidMount` of the screen component. And do some magic inside `handleBackPress` handler.

**Comment by renrizzolo** [comment]
@denieler can you expand on that magic? 
In v1 I was able to `return` from the `this.handleBackPress` function in order to not automatically pop. But in v2 it seems to pop regardless. Any idea how to override it?

For context I have a section that slides up, so one back press should close that, then the next back press should pop the screen.

**Comment by denieler** [comment]
@renrizzolo I think you can find more information here - https://facebook.github.io/react-native/docs/backhandler about how this handler works. It looks like it can be used to implement what you need.

**Comment by jinshin1013** [comment]
BackHandler api is only applicable to Android. Also there isn't an official way to listen to backButton event but you can create your own back button and manually set the event if you really need that feature. I believe in Wix, they do that. Or if you are looking to do something when the screen is popped, you can always use componentDidDisappear or componentDidAppear.

**Comment by renrizzolo** [comment]
Ah, turns out I was returning true / false in the wrong order.

> The event subscriptions are called in reverse order (i.e. last registered subscription first), and if one subscription returns true then subscriptions registered earlier will not be called.
