### ISSUE TITLE
setTimeout handler is not called

### ISSUE THREAD

**Issue by haggholm** [wix/react-native-navigation#4372]
### Issue Description

A piece of our network logic involves a delay to collect WS messages for batch sends. The relevant code looks like this:

```javascript
if (!currentBatchPromise) {
	logger.debug('Enqueueing new batch promise');
	currentBatchPromise = new Promise((resolve, reject) =>
		setTimeout(() => sendCurrentBatch(resolve, reject), 10)
	);
}
```

Most of the time, this works fine. However, sometimes *the timeout handler (`sendCurrentBatch`) is never invoked*. Typically, this happens when transitioning between different screens; I’m not sure which project this bug should be filed under: RN or RNN? I have a vague suspicion that it might be something like https://github.com/facebook/react-native/issues/22089 (“Timers do not run if specified before App mounts”), compounded by the fact that (if I understand correctly) RNN, on some level, creates more than one “app”. I do not know the details.

But it seems very…wrong…that a function like `setTimeout` can somehow *stop working* in the middle of a running application.

---
### Environment
* React Native Navigation version: 2.1.3, 2.1.3-snapshot.49
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): Android, yes; iOS, unknown
* Device info (Simulator/Device? OS version? Debug/Release?): Multiple devices, multiple emulators with different images

**Comment by rohit9625** [comment]
Not stale, I'm facing the exact same issue. The `setTimeout` doesn't get called when navigating back from a screen. However, it get called after navigating one more time or because of some UI interaction. So, I think the execution get stuck and it only happens on iOS for me.
