### ISSUE TITLE
[V1] KeyboardAvoidingView works not properly

### ISSUE THREAD

**Issue by Gitldx** [wix/react-native-navigation#4375]
first,I want to thank for your great job on this library.It's really good!
second,I'm sorry for my poor English.Wish you could understand what I say here.
My application has a chat view where the TextInput is positioned at the bottom of the screen.
My issue is when the TextInput is focused and the keyboard pop up, the TextInput is still behind the keyboard.
On Android,the textInput is popped up too high
Below is a demo code:
export default class Keyboardavoidlayout extends Component {

    render() {
        return (
            <KeyboardAvoidingView style={{ flex: 1, flexDirection: 'column' }} behavior="padding" enabled>
                <View style={{ flex: 1, justifyContent: 'center', backgroundColor: 'lightgreen' }}>
                    <Text>this is a chat list</Text>
                </View>
                <View style={{borderWidth: 1, borderColor: 'red', height: 40 ,justifyContent:'center'}}>
                    <TextInput style={{fontSize:18}} placeholder={'this is at the bottom'} />
                </View>

            </KeyboardAvoidingView>
        )

    }
}

**Comment by jinshin1013** [comment]
How is this an RNN problem?? I think you should try to ask the question on Stackoverflow rather.

**Comment by ItsNoHax** [comment]
Closed as this is not a RNN problem. Please use stackoverflow next time.

**Comment by Gitldx** [comment]
> How is this an RNN problem?? I think you should try to ask the question on Stackoverflow rather.

You may have misunderstood me. The component above is embedded in TabBasedApp.Sorry for my bad demo
