### ISSUE TITLE
[V2] How to check stack is empty before pop

### ISSUE THREAD

**Issue by naiduasn** [wix/react-native-navigation#4379]
### Issue Description

I want to know is there any way we can check if the stack is empty before I try to POP?

### Steps to Reproduce / Code Snippets / Screenshots

Once a user reaches home screen of my app (which i will make it using setRoot), if the user press back button, the app will go to the background but comes as a crash in Crashlytics.

`
com.reactnativenavigation.viewcontrollers.stack.StackController.pop (StackController.java:204)
com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$pop$2$Navigator (Navigator.java:155)
com.reactnativenavigation.viewcontrollers.navigator.Navigator$$Lambda$2.run (Unknown Source:6)
com.reactnativenavigation.viewcontrollers.navigator.Navigator.lambda$applyOnStack$5$Navigator (Navigator.java:208)
com.reactnativenavigation.viewcontrollers.navigator.Navigator$$Lambda$5.run (Unknown Source:2)
com.reactnativenavigation.viewcontrollers.ViewController.performOnParentStack (ViewController.java:144)
com.reactnativenavigation.viewcontrollers.navigator.Navigator.applyOnStack (Navigator.java:208)
com.reactnativenavigation.viewcontrollers.navigator.Navigator.pop (Navigator.java:155)
com.reactnativenavigation.react.NavigationModule.lambda$pop$6$NavigationModule (NavigationModule.java:102)
com.reactnativenavigation.react.NavigationModule$$Lambda$6.run (Unknown Source:10)
android.os.Handler.handleCallback (Handler.java:789)
`

Want to know if i can handle this gracefully.
---
### Environment
* React Native Navigation version: 2.0.2546
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All Android Production Devices

**Comment by jinshin1013** [comment]
Use BackHandler API from React native and set the hardware back button eventlistener on your root component and prevent it from popping.
