### ISSUE TITLE
[V2] [IOS] [SideMenu] StatusBar visible: false doesn't hide status bar

### ISSUE THREAD

**Issue by olehmisuna** [wix/react-native-navigation#4381]
### Issue Description

Setting `{statusBar: {visible: false}}` doesn't hide status bar for side menu, but works for other screens.

Also I've set `UIViewControllerBasedStatusBarAppearance` to `true` inside my `Info.plist`
### Steps to Reproduce / Code Snippets / Screenshots

Try to set sideMenu as root and `StatusBar visible` option to `false`

```
Navigation.setRoot({
        root: {
            sideMenu: {
                left: {
                    component: {
                        id: "someId",
                        name: "app.LeftSideMenu"
                    },
                },
                center: {
                    stack: {
                        children: [{
                            component: {
                                name: "app.SomeScreen"
                            },
                        }]
                    },
                }
            }
        }
    }
})
```

#### Inside "app.LeftSideMenu" component
```
 static options() {
        return {
            statusBar: {
                visible: false
            },
        }
    }
```

---
### Environment
* React Native Navigation version: 2.0.2641
* React Native version: 0.57.4
* Platform(s) (iOS, Android, or both?): IOS
* Device info: Tried with different devices and simulators

**Comment by olehmisuna** [comment]
Has anyone have fix/hack for this?

**Comment by chelovekdrakon** [comment]
> I have found the solution. Its no more related to react-native-navigation.
> You have to import {StatusBar } from 'react-native' and in render() add
> `<StatusBar hidden></StatusBar>` or in
> 
> ```
> componentDidMount() {
>        StatusBar.setHidden(true);
>     }
> ```

Using this module, I got...
<img height="500" src="https://user-images.githubusercontent.com/25362437/51969127-adb34200-2484-11e9-9203-6d29dea9bb02.png" />
No matter what I set to "UIViewControllerBasedStatusBarAppearance" true or false, or even delete it -> I have the same error. 

@pushpanjalip Did you have it?

**Comment by pushpanjalip** [comment]
@chelovekdrakon  No I didn't have this error but  when you set the <key>UIViewControllerBasedStatusBarAppearance</key>
	<true/>
in info.plist of Xcode try Product->clean build and then try npm run ios again.
