### ISSUE TITLE
[V2] Unable to hide backButton

### ISSUE THREAD

**Issue by andresfcamacho** [wix/react-native-navigation#4384]
### Issue Description

I'm unable to hide the `backButton` on the `topBar`. I don't want to make the entire `topBar` `visible:false` as suggested here: https://github.com/wix/react-native-navigation/issues/3826 as I want some `rightButtons`. 

### Steps to Reproduce / Code Snippets / Screenshots
I tried this:

```
options: {
        topBar: {
          backButton: { }
        }
      }
```

But the button was still visible and worked. As a hack/workaround I can do this as my top bar is white:

```
      options: {
        topBar: {
          backButton: { color: '#ffffff' }
        }
      }
```
But its not ideal since the buttons is still there just not visible. I would have expected `backButton: {}` to clear it out.

---
### Environment
* React Native Navigation version: 2.0.2641
* React Native version: 0.57.0
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by jinshin1013** [comment]
If you look at the documentation, there is a style option for backButton. [Link](http://wix.github.io/react-native-navigation/#/docs/styling?id=common-options).
You can do:
```
topBar: {
    backButton: {
        visible: false
    }
}
```

**Comment by stokesbga** [comment]
Doesnt look like this works in 2.3.0 on iOS

**Comment by thinklinux** [comment]
A workaround

```
        leftButtons: [
          {
            id: 'something',
            text: '',
          },
        ],
```

**Comment by L-Yeiser** [comment]
This is still an issue.

**Comment by kiroukou** [comment]
I second this request, this is quite a big issue. Current state: it does work on IOS but not on Android.

**Comment by L-Yeiser** [comment]
@kiroukou as a work around I added `backgroundColor: ' transparent'`.

**Comment by L-Yeiser** [comment]
still an issue

**Comment by L-Yeiser** [comment]
still an issue

**Comment by X-Tender** [comment]
Damn, I thought to find a solution on this issue here :/
The workaround with the empty leftButton is no solution because it leave the gap on the left side.

**Comment by ajmalsalim** [comment]
As @thinklinux mentioned, this workaround is working fine:

` leftButtons: [
          {
            id: 'something',
            text: '',
          },
        ],`

The thing is you need to use this when you are pushing the screen and not in mergeOptions

**Comment by bitcrumb** [comment]
This is still an issue.

**Comment by Findiglay** [comment]
Can confirm the follow does not work on Android.

```
backButton: {
   visible: false,
},
```

**Comment by SudoPlz** [comment]
Still an issue, I don't know what's going on with wix but this is SOOO sooo bad man.
Feels like this library has ben left to rot, all the issues get closed after months of existence without anyone ever taking a look at them, and this just hurts the wix brand I think.

I think the way to go is start looking for maintainers for this repo..

**Comment by keremcubuk** [comment]
I'm using RNN 6.6.2 issue still not fixed. Any updates about this problem? @guyca

**Comment by zabojad** [comment]
Still not fixed on Android and RNN v6.10.1. Still having this issue since v2...

Please reopen!

**Comment by guyca** [comment]
Hey @zabojad 
I've tried hiding the back button in the Playground app both in static and merge options. Both seem to work as expected on Android.

### Hiding the back button with mergeOptions
```js
<Button
          label="Hide back button"
          onPress={() => {
            Navigation.mergeOptions(this, {
              topBar: {
                backButton: {
                  visible: false,
                },
              },
            });
          }}
        />
```

### Hiding the back button with static options
```js
  static options(): Options {
    return {
      topBar: {
        backButton: {
          visible: false,
        },
      },
    };
  }
```

If this is still an issue - please open another issue and provide a reproduction. Thanks and sorry for the inconvenience.

**Comment by freudibili** [comment]
Still an issue for me

**Comment by a8nova** [comment]
Hello, still an issue on RN 0.64.2
