### ISSUE TITLE
[V2] bottomTabs animate: true broken

### ISSUE THREAD

**Issue by dkimm96** [wix/react-native-navigation#4385]
### Issue Description

Configuring bottomTabs to { visible: false, animate: true } via Navigation.mergeOptions changes the visibility but does not animate. TopBar is working fine, its just the bottomTabs that seems to be broken.

### Steps to Reproduce / Code Snippets / Screenshots

Navigation.mergeOptions(componentId, {
        topBar: {
          visible: true,
          animate: true,
        },
        bottomTabs: {
          visible: true,
          animate: true,
          drawBehind: true
        }
})

---
### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.57.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator (iPhone X) and Device (iPhone X) both. iOS 12.1, Debug scheme

**Comment by michaelfreund** [comment]
I noticed a change in the behavior of the tab animation, which probably changed here: https://github.com/wix/react-native-navigation/compare/2.0.2595...2.0.2596

In version 2.0.2595, if you called the push command in a view with bottom tabs, the tab bar was pushed out of the screen together with the parent view. Starting with version 2.0.2596 it is only "hidden" and seems not to be connected with the parent view.

**Comment by ADCrouch** [comment]
I'm also having the same issue, did you find a solution?
