### ISSUE TITLE
[Urgent request] Support windows phone for community growth & community identity

### ISSUE THREAD

**Issue by kelvin-dev** [wix/react-native-navigation#4387]
@guyca @DanielZlotin @yogevbd @gran33 @yershalom @yedidyak @bogobogo @Cool04ek @all @here
We highly appreciate your work, plz help consider supporting windows phone natively based upon RN-XP from Microsoft. Do we really need to upgrade to latest Fb react-native meanwhile Microsoft already had another the well-tested version built the top of Fb RN ? we can make use of their team effort, cant we ? As a cross-platform mobile producer, we expected that by RN-XP integration, your react-navigation would be the first-class implementation, the best universal react-navigation support all mobile platforms. Millions of developers from Windows phone marketve been waiting this feature in your release roadmap and this library soon gets funded from giant tech investors ✓ As current status quo in tech marketshare, only Wix has this great advantage ! 
Refs:
1. https://microsoft.github.io/reactxp/ 
2. https://github.com/Microsoft/reactxp.git
3. https://github.com/GPegel/NavigationExample
4. https://github.com/EgorBo/MvvmNavigationToolkit
Happy coding & tons of thanks

**Comment by ItsNoHax** [comment]
Please be professional when submitting issues. You tagged the whole team, triple liked your own issue and then added some clickbait jargon.

While Microsoft phone support is a valid argument, this is not the way you bring it up for discussion.
