### ISSUE TITLE
iOS popGesture on stack root freezes the app

### ISSUE THREAD

**Issue by Jazqa** [wix/react-native-navigation#4388]
### Issue Description

Attempting iOS popGesture on stack root may freeze the app

### Steps to Reproduce / Code Snippets / Screenshots

1. (May not be necessary. This is just what I have) Have a tab-based app with each tab being a stack
2. Push a screen to one of the stacks
3. Go back
4. Try to do popGesture on stack root
5. Try to push a screen on the stack again
6. App freezes

---
### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.57.5
* Platform(s) (iOS, Android, or both?): iOS

**Comment by ItsNoHax** [comment]
Hey @Jazqa 

I actually have been talking to @guyca recently about this bug and I sent him a reproducible case.
Will keep you updated.

**Comment by ouabing** [comment]
I can confirm from 2.2.0, pop gesture not work on iOS when there is a react-native-tab-view pager in the screen. Is this fix related to the new issue?

**Comment by cinder92** [comment]
is there any update on this? im having same issue with : `2.14.0-snapshot.246`

**Comment by fliPmitKlammern** [comment]
I have a similar problem in v2.17.0:
1. tab-based app with each tab being a stack
2. Push a screen to one of the stacks
3. Try to do popGesture on the pushed screen
4. App freezes

**Comment by guyca** [comment]
Should be fixed in `2.18.0-snapshot.292` 👍

**Comment by idanlo** [comment]
@guyca still not fixed
