### ISSUE TITLE
Separate actions for each tab of the top tab bar in a screen

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#439]
### Issue Description

I am using a tab based app for iOS and a single screen app with top tabs for Android. In case of android, I want to show separate action buttons under the overflow icon for each tab. But currently, it looks like each of the top tabs gets the action buttons that are defined as part of the `screen` for the single screen app. Typically, it is possible that each of the tab may have its own set of actions. Is it possible to achieve it currently.

### Steps to Reproduce / Code Snippets / Screenshots

This is the app configuration.

    Navigation.startSingleScreenApp({
        screen: {
          screen: 'Screen1',
          title: 'Nooz',
          navigatorStyle: {},
          topTabs: [
            {
              screenId: 'Screen1',
              title: 'Screen 1'
            },
            {
              screenId: 'Screen2',
              title: 'Screen 2'
            },
            {
              screenId: 'Screen3',
              title: 'Screen 3'
            }
          ]
        },
        drawer: { // optional, add this if you want a side menu drawer in your app
          left: { // optional, define if you want a drawer from the left
            screen: 'Settings' // unique ID registered with Navigation.registerScreen
          },
          disableOpenGesture: false // optional, can the drawer be opened with a swipe instead of button
        },
        passProps: {},
        animationType: 'none'
      });

Screen1 has five action buttons out of which four appear behind the overflow icon and one in the action bar. Screen2 and Screen3 has just button that appears in the action bar. But currently, I see the five buttons configured in the Screen1 in all the three tabs.

### Environment
* React Native Navigation version: 2.0.0.experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug

**Comment by guyca** [comment]
Hey @varungupta85 I'm sorry but I didn't understand your issue.
If you want to configure buttons per `TopTab`, just define a static `navigatorButtons` in each `TopTab` screen.

**Comment by varungupta85** [comment]
hi @guyca, this is what I have done but I am not able to see the correct buttons in the navigation bar as configured per `TopTab` screen. Below is how I have configured the app.

**App.js**

    Navigation.startSingleScreenApp({
        screen: {
          screen: 'AlarmListScreen',
          title: 'App',
          navigatorStyle: {},
          topTabs: [
            {
              screenId: 'AlarmListScreen',
              title: 'Alarms'
            },
            {
              screenId: 'GroupListScreen',
              title: 'Groups'
            },
            {
              screenId: 'ContactListScreen',
              title: 'Contacts'
            }
          ]
        },
        drawer: { // optional, add this if you want a side menu drawer in your app
          left: { // optional, define if you want a drawer from the left
            screen: 'Settings' // unique ID registered with Navigation.registerScreen
          },
          disableOpenGesture: false // optional, can the drawer be opened with a swipe instead of button
        },
        passProps: {},
        animationType: 'none'
      });

**AlarmListScreen.js**

```
const getLeftButtonsForAlarmList = () => {
  let leftButtons = []
  if(Platform.OS === 'android') {
    leftButtons = [{
      icon: require('../../img/navicon_menu.png'),
      id: 'settingsMenu'
    }]
  }
  return leftButtons
}

const getRightButtonsForAlarmList = () => {
  let rightButtons = []
  if(Platform.OS === 'ios') {
    rightButtons = [
      {
        title: 'Add',
        icon: require('../../img/navicon_add.png'),
        id: 'add'
      }
    ]
  } else {
    rightButtons = [
      {
        title: 'Add',
        icon: require('../../img/navicon_add.png'),
        id: 'add',
        showAsAction: 'always'
      },
      {
        title: 'All',
        id: 'all',
        showAsAction: 'never'
      },
      {
        title: 'Upcoming',
        id: 'upcoming',
        showAsAction: 'never'
      },
      {
        title: 'My',
        id: 'my',
        showAsAction: 'never'
      },
      {
        title: 'Participant',
        id: 'participant',
        showAsAction: 'never'
      },
    ]
  }
  return rightButtons
}

export default class AlarmListScreen extends Component {
  static navigatorButtons = {
    leftButtons: getLeftButtonsForAlarmList(),
    rightButtons: getRightButtonsForAlarmList()
  }
  // Other methods needed to render the screen
}
```

**GroupListScreen.js**

```
const getLeftButtonsForGroupList = () => {
  let leftButtons = []
  if(Platform.OS === 'android') {
    leftButtons = [{
      icon: require('../../img/navicon_menu.png'),
      id: 'settingsMenu'
    }]
  }
  return leftButtons
}

const getRightButtonsForGroupList = () => {
  let rightButtons = [
    {
      title: 'Add',
      icon: require('../../img/navicon_add.png'),
      id: 'add',
      showAsAction: 'never'
    }
  ]
  return rightButtons
}

export default class GroupListScreen extends Component {
  static navigatorButtons = {
    leftButtons: getLeftButtonsForGroupList(),
    rightButtons: getRightButtonsForGroupList()
  }
  // Other methods
}
```

**ContactListScreen.js**

```
const getLeftButtonsForContactList = () => {
  let leftButtons = []
  if(Platform.OS === 'android') {
    leftButtons = [{
      icon: require('../../img/navicon_menu.png'),
      id: 'settingsMenu'
    }]
  }
  return leftButtons
}

const getRightButtonsForContactList = () => {
  let rightButtons = [
    {
      title: 'Remove',
      icon: require('../../img/navicon_menu.png'),
      id: 'remove',
      showAsAction: 'never'
    }
  ]
  return rightButtons
}

export default class ContactListScreen extends Component {
  static navigatorButtons = {
    leftButtons: getLeftButtonsForContactList(),
    rightButtons: getRightButtonsForContactList()
  }
  // Other methods
}
```

**Screenshot from Alarms tab**

This is expected. I am seeing all the button as configured

![screen shot 2016-11-14 at 9 35 56 pm](https://cloud.githubusercontent.com/assets/7475133/20272243/5b3380dc-aab3-11e6-89b6-82f2173acab2.png)

**Screenshot from Groups tab**

This is not expected. I didn't expect to see any of All, Upcoming, My and Participant buttons.

![screen shot 2016-11-14 at 9 36 14 pm](https://cloud.githubusercontent.com/assets/7475133/20272321/82a50dfc-aab3-11e6-960a-5ed668119bc5.png)

**Screenshot from the Contacts tab**

Again, since I have configured only one button which is set to always show up in the action bar, I didn't expect to see an overflow icon at all. But the overflow icon is present and when clicked, it also shows the All, Upcoming, My and Participant actions.

![screen shot 2016-11-14 at 9 36 24 pm](https://cloud.githubusercontent.com/assets/7475133/20272402/c3960384-aab3-11e6-9f36-7ae34eb1bf31.png)

I also made the `GroupListScreen` as the default screen in the `startSingleScreenApp` and then I started to see the buttons configured in `GroupListScreen` under all the three tabs.

**Comment by guyca** [comment]
So items are not removed from overflow menu when switching tabs?

**Comment by varungupta85** [comment]
Yes, the items remain constant while switching tabs. If there are any new items in the navigation bar in some tab, they are not added. If some items are not present in some other tab, they are not removed.

**Comment by guyca** [comment]
@varungupta85 Thanks for reporting the issue 👍 Just a friendly tip, when you use triple ticks to add a code block - you can set syntax highlighting by adding `js` after the ticks

```js
const iAmHighlighted = 'now it\'s easy to read code';
```

**Comment by varungupta85** [comment]
Thanks for the tip 👍  I didn't know about it. I have updated the code with the syntax highlighting.

**Comment by guyca** [comment]
@varungupta85 I just remembered that buttons don't change when changing TopTab screens. You need to listen to `tabSelected` event, and call `setButtons` manually. I really think this behaviour should be taken care of for you.

For now, here's a reasonable workaround that we also use:

```js
onNavigatorEvent(event) {
  switch (event.id) {
    case 'tabSelected':
      this.onTabActive();
      return;
  }
}

onTabActive() {
  this.props.navigator.setButtons(MYSCREEN.navigatorButtons);
}
```

**Comment by guyca** [comment]
I was confused at first because we recently added `FloatingActionButton` and that **IS** taken care for you automatically.

**Comment by varungupta85** [comment]
@guyca Thanks for the workaround. Works as expected.

**Comment by DanielZlotin** [comment]
What you are really after, if I understand you correctly, is to make your `topTabs` your main navigation tabs. This is currently not supported by `react-native-navigation`.

There are multiple reasons for this, but the main one being this is not a part of our current scope. It can be added to a major version in the future, as it will make us treat all tabs as generic sections in the app, and it is a pretty big change.

Other than that, we are soon adding lifecycle events for screens, this can also help you.

**Comment by varungupta85** [comment]
@DanielZlotin Yes, kind of like Whatsapp in Android. There would be 3-4 top tabs where users can browse different things and perform different kinds of actions depending on the tab they are currently in. Workaround suggested by @guyca works pretty well for now.

**Comment by Arafath-misree** [comment]
hey how can i set buttons to the top tabbar selected screen.

**Comment by arryanggaputra** [comment]
cool issue :)
