### ISSUE TITLE
stack loading all the children components at once

### ISSUE THREAD

**Issue by Bharatchavan20** [wix/react-native-navigation#4392]
### Issue Description

My app screens structure/flow  is 

**Events List (Entry point)** ---_OnList item click_---> **Event Registration screen** ---_onButton click_-> **Confirmation scren**

The issue is: It loading all the screen at once. 
The expectation is,  It should show only entry point first then on click on a list item, I will push new component by using 

` Navigation.push(this.props.componentId, {
      component: {
        name: 'screen id'
      }
    });
  };
`

### Steps to Reproduce / Code Snippets / Screenshots

`Navigation.setRoot({
  root: {
    stack: {
      children: [
        {
          component: {
            name: "com.events.list",
            passProps: {},
            options: {
              topBar: {
                title: {
                  text: "Events list"
                }
              }
            }
          }
        },
        {
          component: {
            name: "com.events.registration",
            passProps: {},
            options: {
              topBar: {
                title: {
                  text: "Registration"
                }
              }
            }
          }
        },
        {
          component: {
            name: "com.events.confirmation",
            passProps: {},
            options: {
              topBar: {
                title: {
                  text: "confirmation"
                }
              }
            }
          }
        }
      ]
    }
  }
});
`

---
### Environment
* React Native Navigation version: ^2.1.3
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):  Android - Moto E/7.11/ debug

**Comment by Bharatchavan20** [comment]
Need help for this issue

**Comment by ddcech** [comment]
@Bharatchavan20, I have the same issue. How did you solve this? My Navigation.setRoot looks similar to yours.
Any help would be great, thanks

**Comment by ddcech** [comment]
So the issue comes when you have more than one screen in the stack array. So the solution is that you should only have one screen in the stack, and then just use:
```
Navigation.push(this.props.componentId, {
    component: {
      name: 'COMPONENT_NAME'
    }
})
```
