### ISSUE TITLE
Peek and pop not working

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#4396]
### Issue Description

When trying the example code of peek and pop in the documentation https://wix.github.io/react-native-navigation/#/docs/animations?id=peek-and-pop-ios-114 it correctly does the animation when I press harder and harder. It will also show correctly the previous screen so peeking works. But when I press harder so that it should actually go to that screen it won't. It just stays in the current screen anyways.

### Steps to Reproduce / Code Snippets / Screenshots

Try the example code in the documentation I have linked

---
### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.55.4
* Platform: iOS
* Device info: Real device iPhone 6s

**Comment by madhubalan** [comment]
@henrikra I am facing same issue. Did you find any solution?
