### ISSUE TITLE
Show the "startSingleScreenApp" inside a specific page

### ISSUE THREAD

**Issue by AlaaAttya** [wix/react-native-navigation#44]
Hi guys,

I need to show up the navigation drawer only in a single specific page inside the app. I've a splash screen then a signup page then the home page. I've initialised the "startSingleScreenApp" object inside the HomeComponent only but it's showing in all the screens. How could i do that?

**Comment by guyca** [comment]
tl;dr: You need to call `startSingleScreenApp` twice - and define the drawer component only the second time.

The idea is, you call `startSingleScreenApp` the first time and show your splash screen and signup page. After a user has signed up - call `startSingleScreenApp` again and show your "HomeComponent"

**Comment by AlaaAttya** [comment]
@guyca i did so but the gesture is working for all the pages. meaning that, when the user swipes from left to right in any page it shows the left menu. how can i stop it?

**Comment by guyca** [comment]
adding @gran33
