### ISSUE TITLE
Application settings has not been registered error on Android

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#440]
### Issue Description

When I start the app on Android simulator, I see a red box with the following error

```
Application Settings has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.
runApplication
    AppRegistry.js:99
__callFunction
    MessageQueue.js:236
<unknown>
    MessageQueue.js:108
guard
    MessageQueue.js:46
callFunctionReturnFlushedQueue
    MessageQueue.js:107
```

If I dismiss the red box, I see the app on the screen. It works find on iOS. This is the start app call.

    Navigation.startSingleScreenApp({
        screen: {
          screen: 'Screen1',
          title: 'App',
          navigatorStyle: {},
          topTabs: [
            {
              screenId: 'Screen1',
              title: 'Screen 1'
            },
            {
              screenId: 'Screen2',
              title: 'Screen 2'
            },
            {
              screenId: 'Screen3',
              title: 'Screen 3'
            }
          ]
        },
        drawer: { // optional, add this if you want a side menu drawer in your app
          left: { // optional, define if you want a drawer from the left
            screen: 'Settings' // unique ID registered with Navigation.registerScreen
          },
          disableOpenGesture: false // optional, can the drawer be opened with a swipe instead of button
        },
        passProps: {},
        animationType: 'none'
      });

I am not sure what may be wrong as I was able to run the example without observing this error. I have made sure that the `MainActivity.java` and `MainApplication.java` class are updated as instructed in the wiki

Here is the MainActivity.java class

```
package com.xyz;

import com.reactnativenavigation.controllers.SplashActivity;

public class MainActivity extends SplashActivity {

}
```

Here is the MainApplication.java class

```
package com.xyz;

import android.support.annotation.NonNull;

import com.facebook.react.ReactPackage;
import com.reactnativenavigation.NavigationApplication;

import java.util.Arrays;
import java.util.List;

import com.joshblour.reactnativepermissions.ReactNativePermissionsPackage;
import com.evollu.react.fa.FIRAnalyticsPackage;
import com.reactnative.ivpusic.imagepicker.PickerPackage;
import com.learnium.RNDeviceInfo.RNDeviceInfo;
import com.oblador.vectoricons.VectorIconsPackage;
import com.zmxv.RNSound.RNSoundPackage;
import com.rt2zz.reactnativecontacts.ReactNativeContacts;
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
import com.aakashns.reactnativedialogs.ReactNativeDialogsPackage;
import com.acintyo.reactnativeandroidperiodicfetch.ReactNativeAndroidPeriodicFetchPackage;
import com.i18n.reactnativei18n.ReactNativeI18n;

public class MainApplication extends NavigationApplication {

    @Override
    public boolean isDebug() {
        // Make sure you are using BuildConfig from your own application
        return BuildConfig.DEBUG;
    }

    @NonNull
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return Arrays.<ReactPackage>asList(
                new ReactNativePermissionsPackage(),
                new FIRAnalyticsPackage(),
                new PickerPackage(),
                new RNDeviceInfo(),
                new RNSoundPackage(),
                new ReactNativeContacts(),
                new ReactNativePushNotificationPackage(),
                new ReactNativeDialogsPackage(),
                new ReactNativeAndroidPeriodicFetchPackage(),
                new ReactNativeI18n(),
                new VectorIconsPackage()
        );
    }
}
```

### Environment
* React Native Navigation version: 2.0.0.experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug

**Comment by varungupta85** [comment]
According to [this](http://stackoverflow.com/questions/35449248/failure-to-call-appregistry-registercomponent), it may happen if there is a mismatch between the app name between the JS and the native side (although the post is concerned with iOS). There used to be a overridden method `getMainComponentName` which use to return the app name and I think the same name is used while calling `AppRegistry.registerComponent` but both of these are gone after moving to react-native-navigation. So, not sure if this is the reason behind the error.

cc @guyca

**Comment by guyca** [comment]
You have a sideMenu defined with id `Settings` - did you register that screen?

**Comment by varungupta85** [comment]
@guyca Thanks a lot. I didn't realize that such errors may be thrown when some screen is not registered. Registering the screen fixed the problem.
