### ISSUE TITLE
[v2] Set default topBar button color

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#4400]
Is it possible to set the default color of topBar button?

**Comment by perrosnk** [comment]
Yes it is:

```javascript
    Navigation.setDefaultOptions({
      topBar: {
        rightButtons: {
          color: 'color',
        },
        leftButtons: {
          color: 'color',
        },
      },
    });
```

**Comment by perrosnk** [comment]
It's still an issue

**Comment by confiks** [comment]
@perrosnk It's undocumented, but you can use:

    Navigation.setDefaultOptions({
        topBar: {
            leftButtonColor: nbVariables.topBarContentColor,
            rightButtonColor: nbVariables.topBarContentColor,
        }
    });
