### ISSUE TITLE
Right icon just show blue circle in iOS

### ISSUE THREAD

**Issue by waveChand** [wix/react-native-navigation#4402]
I'm using new V2 of react-native-navigation, when I'm use back icons and right top bar button icons, I't works fine on android devices, but with IOS I'm not getting the image, only the blue circle.

enter image description here

These are the codes use generate top bar icons

//right button

`static options(passProps) {
    return {
      topBar: {
        leftButtons: [

        ],
        rightButtons: [
          {
            id: 'settings',
            icon: require('../assets/images/symbols/settings.png'),
            disableIconTint: true
          }
        ],
      }
    };
  }`

//Image showing issue
[bug image](https://i.stack.imgur.com/F2D3d.png)
---
### Environment
* React Native Navigation version: v2
* React Native version: 0.57
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by ItsNoHax** [comment]
Add property: color: 'white'

**Comment by waveChand** [comment]
> Add property: color: 'white'

I tried with this. but then I'm getting white circle. cannot get the real image (png)

**Comment by omarchacinortega13** [comment]
I am facing this issue on iOS as well - Any solution?

**Comment by waveChand** [comment]
> I am facing this issue on iOS as well - Any solution?

did you able to solve this?

**Comment by spbond** [comment]
I am experiencing this issue with the back button in iOS.  It renders the shape of the png, but fills it with a solid color (blue by default).
