### ISSUE TITLE
[V2][iOS]how do i change side menu shadow' position to the right

### ISSUE THREAD

**Issue by ssshen** [wix/react-native-navigation#4403]
### Issue Description

how do i change side menu shadow' position to the right
![simulator screen shot - iphone xs max - 2018-12-06 at 11 35 27](https://user-images.githubusercontent.com/28528399/49559897-5ba1e480-f94b-11e8-88b5-33a2d29cda43.png)

---
### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS

**Comment by hadnet** [comment]
@ssshen did you find a solution?

**Comment by kirhim** [comment]
@ssshen I have same question!

**Comment by ssshen** [comment]
@hadnet @kirhim I rewrite `lib/ios/RNNSideMenu/MMDrawerController/MMDrawerController.m` to solve this problem, you can view latest commit in my fork `https://github.com/ssshen/react-native-navigation`.May it can help you.
