### ISSUE TITLE
Animations (Preview API) Shared element

### ISSUE THREAD

**Issue by I-ad** [wix/react-native-navigation#4404]
the document clearly says the share element for cross platforms IOS / Android.

When I tried it out, its work perfectly on IOS, but on Android not Working at all.
it just sliding from bottom to top with all screen content.

my Question: is that ok or I miss something, I used the same example on Animations API document.

thank you

**Comment by FRizzonelli** [comment]
Having the same issue. @I-ad @dopey2 @alexandregiordanelli any working solution?

**Comment by FinnGu** [comment]
Same issue. I am using RN v0.59.8, RNN v2.21.0 went back to not using the Shared element transition at all.

**Comment by ashokkumar88** [comment]
@FinnGu @I-ad Did you find and work around to work the Shared Element in android?

**Comment by FinnGu** [comment]
> @FinnGu @I-ad Did you find and work around to work the Shared Element in android?

No, I did not have any more time to look for a solution.

**Comment by rendomnet** [comment]
same here

**Comment by FinnGu** [comment]
Apparently RNN v5.0.0 includes a completely new implementation of Shared Element Transitions. Right now push and pop is possible on iOS and push is working on Android. Pop animations on Android are supposed to come very soon.

Just in case, some of you have not seen the update :)
