### ISSUE TITLE
Some RNN1 drawer style attributes missing in RNN2's sideMenu?

### ISSUE THREAD

**Issue by SchwarzerSchnee** [wix/react-native-navigation#4408]
### Steps to Reproduce / Code Snippets / Screenshots

Migrating to RNN2 right now, I had this on my drawer in RNN1:

```
style: { // ( iOS only )
    drawerShadow: false, // optional, add this if you want a side menu drawer shadow
    contentOverlayColor: 'rgba(0,0,0,0.25)', // optional, add this if you want a overlay color when drawer is open
},
```

How do I achieve the same effects on what is now the sideMenu?

---
### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): device, iOS 9-12

**Comment by onlaps** [comment]
+1

**Comment by ialmoqren** [comment]
I hope there is an equivalent, but if not, I think it should be added to the [Unsupported options](https://wix.github.io/react-native-navigation/#/docs/options-migration?id=unsupported-options)

**Comment by Desintegrator** [comment]
+1
