### ISSUE TITLE
Implementing deprecated method

### ISSUE THREAD

**Issue by stevensacks** [wix/react-native-navigation#4409]
### Issue Description
```
The following commands produced analyzer issues:
	Analyze /Users/steven/Development/project/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64
(1 command with analyzer issues)

The following build commands failed:
	CompileC /Users/steven/Development/project/ios/build/Build/Intermediates.noindex/ReactNativeNavigation.build/Debug-iphonesimulator/ReactNativeNavigation.build/Objects-normal/x86_64/TheSidebarController.o /Users/steven/Development/project/node_modules/react-native-navigation/lib/ios/RNNSideMenu/TheSidebarController/TheSidebarController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

### Steps to Reproduce / Code Snippets / Screenshots
Set up everything as per the docs. Brand new clean install of Mojave, XCode 10.1, etc.

`react-native run-ios`

`Libraries/ReactNativeNavigation.xcodeproj/RNNSideMenu/TheSidebarController/TheSideBarController.m/M-willRotateToInterfaceOrientation:duration:`
![screen shot 2018-12-07 at 02 39 12](https://user-images.githubusercontent.com/162252/49601505-52eff380-f9c9-11e8-8f42-1abf00f03795.png)

---
### Environment
* React Native Navigation version: 2.2.0
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone XS iOS 12.1

**Comment by stevensacks** [comment]
Duplicate of #4391, but perhaps more info here.

**Comment by Kenneth-Brisco** [comment]
I am having the same issue after Xcode update.
