### ISSUE TITLE
Make left-to-right swipe behaviour depend on stack size: SideMenu or go back

### ISSUE THREAD

**Issue by kompot** [wix/react-native-navigation#441]
Currently it's only possible to enable/disable SideMenu globally.

Also there are some proposals 
https://github.com/wix/react-native-navigation/issues/326
to make it customizable per screen.

While I think that should be possible, default behaviour for left SideMenu should be different.

— if the screen can be popped then swiping from left-to-right must just pop the screen
— if we are at top of the stack — SideMenu should be shown

Reason for that: on iOS it's nearly impossible to go back by swiping with SideMenu enabled which is widely used as far as I can see (e. g. facebook app, instagram app).

What do you think guys?

Thanks for your hard work on this project, seems like the only sane way to do navigation in react-native.

**Comment by valeriik** [comment]
So guys, there is possibility to add API to make drawer customizable per screen?
If not may be you have some idea to "hack" to get around this?
Thanks.

**Comment by DanielZlotin** [comment]
Maybe what you're looking for is modal?

**Comment by valeriik** [comment]
>Maybe what you're looking for is modal?

Thanks for quick reply, I will try to figure out...

But, for now, unfortunately I could not run this navigator (v2) on 

Android 4.1 / API16:
BUILD SUCCEEDED but App crashed in virtual device with error - "Unfortunately, [app name] has stopped." 

and 

Android 7.1.1 / API25:
** BUILD SUCCEEDED **, but I see just white screen on virtual device and there are no any observable errors.

...and I do not know it is my mistake or component issue :)

With iOS looks like everything ok.

**Comment by DanielZlotin** [comment]
Please open a separate issue and specify the exact version

**Comment by valeriik** [comment]
Ok, #777 is created.

**Comment by valeriik** [comment]
@DanielZlotin is it possible to run navigator with opened modal screen without navigation bar itself?

In case I use "showModal" method in "FirstTabScreen.js" constructor (this screen shows at start) like this:
```
this.props.navigator.showModal({
      title: "Modal",
      screen: "ModalScreen",
      animationType: 'none'
});
```
and in "ModalScreen.js" constructor I use "toggleNavBar":
```
this.props.navigator.toggleNavBar({
      to: 'hidden',
      animated: false
});
```
modal screen shows at start but I see some blink at start, like during ~0.01 sec NavBar shows and then it hides (I have not physical iOS device so I did not check this on it, may be this "bug" is on simulator only).

The main goal is to create "Login" screen (with Login/Pass fields to type) and obviously drawer should not be applicable in this screen, and after user input the login/pass, application should shows drawer etc.

Thanks.
