### ISSUE TITLE
[V2][Android] Crashing on setRoot with bottom tabs. Currently present in 2.1.3. Original post linked.

### ISSUE THREAD

**Issue by TylerNRobertson** [wix/react-native-navigation#4415]
- Currently still an issue with:
RNN - 2.1.3
RN - 0.57.7
React - 16.6.1

Original Issue Post:
https://github.com/wix/react-native-navigation/issues/4130

** This was moved to stale by the bot and then taken back out about 9 says ago. Seems like this issue needs some light shed on it because it's an on going problem

**Comment by ItsNoHax** [comment]
Closing this because it is a duplicate. Setting root with bottomTabs does work
