### ISSUE TITLE
Quick feedback: Why I haven't chosen this library.

### ISSUE THREAD

**Issue by atrauzzi** [wix/react-native-navigation#4417]
Hey there!  I've been assessing some of the wix react native contributions as we go through the process of tech selection on my team.

I want to say first that it's great to see what you've done, although I want to offer up some feedback, particularly as it pertains to the android project setup.

There are very few situations where I'll take on a concern-specific base class to get a new feature in my projects.  Even in the most restrictive languages/environments, composition is always preferred over inheritance and I think that's generally good design.
When I saw the places in the instructions where this library requires that I extend your base classes in my android project, it was sadly forced out of the running.  I've had scenarios in the past where one library will insist on being my root type, but then another library comes along that wants to make the same assumption...

It's worth noting that in almost every other respect, the wix public libraries showed strong in our matrix and I was really saddened when it came down to this and the more commonly mentioned issues of documentation quality with the public wix react native projects.

Anyway.  Maybe this issue will help you guys advocate internally for more resources to dedicate towards your published projects.  There might even be benefits internally from getting the time to spend polishing things up.

I look forward to a day when I'll be able to take a second look at this project for navigation!

---

##### cc.
 - https://github.com/wix/react-native-ui-lib/issues/8

**Comment by guyca** [comment]
hmm that's an interesting point, however that specific aspect of the design was pretty much dictated by react-native's [ReactActivity](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java) - we figured it would be easier for users to migrate their project by simply extending a different class, and I think we were pretty much correct with that assumption as it's a pattern users are already familiar with.

**Comment by atrauzzi** [comment]
Hm, I think there's an assumption out of convenience floating in that rationale.  People don't explicitly take an action to extend `ReactActivity`.  They have it scaffolded as part of a default project structure.
(React native is in essence the platform, so it has more latitude to define a new base type than a library.  There's no reasonable expectation for it to have an alternative.)

Hearing _"we figured"_, that seems like a good reason to go actively seeking input vs. making assumptions.  Everyone knows about inheritance, but I think we all know the temperature on how well loved it is! 😉 

Full apologies, not trying to be contrarian here.
