### ISSUE TITLE
Blurry NavBar Broken After iOS 10 Upgrade

### ISSUE THREAD

**Issue by ghost** [wix/react-native-navigation#442]
### Issue Description

After iOS 10 upgrade, all my blurry navBar broken. Title and button won't showing up.

![screen shot 2016-11-15 at 1 32 19 am](https://cloud.githubusercontent.com/assets/23297109/20277691/33175788-aad4-11e6-91f2-a145e189eceb.jpg)

```js
static navigatorStyle = {
    drawUnderNavBar: true,
    navBarBlur: true,
    navBarTextColor: 'rgb(46,171,146)',
    navBarSubtitleTextColor: 'rgb(46,171,146)',
    navBarButtonColor: 'rgb(46,171,146)'
 };
```

This is not the case for non-blurry navBar

![screen shot 2016-11-15 at 1 33 02 am](https://cloud.githubusercontent.com/assets/23297109/20277730/61bc3874-aad4-11e6-9ab6-f47c0372b3b3.jpg)

```js
static navigatorStyle = {
    navBarBackgroundColor: 'rgb(46,171,146)',
    navBarTextColor: '#ffffff',
    navBarSubtitleTextColor: '#ffffff',
    navBarButtonColor: '#ffffff',
    navBarNoBorder: true,
    drawUnderTabBar: true
 };
```

Seems to be related with https://github.com/wix/react-native-navigation/issues/337

---
### Environment
* React Native Navigation version: 2.0.0-experimental.141
* React Native version: 0.31.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by yxprama** [comment]
This project worth mentioning https://github.com/react-native-community/react-native-blur as using the same implementation for blur effect (UIVisualEffectView)

**Comment by perrosnk** [comment]
@yxprama have you tried upgrading react-native to 0.38, and RNN to 2.0.0-experimental.191? 
My issue #337 was solved after the upgrade.

**Comment by jasonmerino** [comment]
I am seeing something similar to this issue with...

`react-native-navigation@1.1.237`
`react-native@0.49.3`

Although, what I'm seeing is that when you add just the `navBarBlur: true` property and value the nav bar does indeed blur, but it shows no buttons or titles at all. Not even a back button. 

Is this something that is likely to get fixed for v1? Or is this mostly a v2 concern?
