### ISSUE TITLE
[V2] showModal animation customisation is not working

### ISSUE THREAD

**Issue by NirpE** [wix/react-native-navigation#4421]
### Issue Description

Customizing modal animation gives error `This animation is not supported: content`. Based on documentation `showModal` and `dismissModal` could have custom animations.

### Steps to Reproduce / Code Snippets / Screenshots

    await Navigation.showModal({
      component: {
        name: screen,
        passProps: props,
        options: {
          layout: {
            backgroundColor: Colors.black80,
            orientation: 'portrait',
          },
          overlay: {
            interceptTouchOutside: true,
          },
          modalPresentationStyle: 'overCurrentContext',
          animations: {
            showModal: {
              content: {
                alpha: {
                  from: 0,
                  to: 1,
                  duration: 200,
                  interpolation: 'accelerate',
                },
              },
            },
            dismissModal: {
              content: {
                alpha: {
                  from: 1,
                  to: 0,
                  duration: 200,
                  interpolation: 'accelerate',
                },
              },
            },
          },
        },
      },
    });

---
### Environment
* React Native Navigation version: 2.2.0
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug, LGE Nexus 5X, OS 8.1.0

**Comment by alexcoady** [comment]
In the documentation [here](https://wix.github.io/react-native-navigation/#/docs/styling?id=customizing-stack-command-animation) it says
> When pushing and popping screens to and from a stack, you can control the TopBar, BottomTabs and actual content animations as separately.

So I'm guessing this cannot be achieved when animating modals/

**Comment by NirpE** [comment]
[Here](https://wix.github.io/react-native-navigation/#/docs/styling?id=customizing-navigation-commands-animation) it is said that `showModal` etc. should support animations at least for the content.

TopBar, BottomTabs and actual content can be animated separately when pushing and popping screens.

**Comment by kiroukou** [comment]
More information concerning theses questions ?

**Comment by ialmoqren** [comment]
Sorry guys I think this shouldn't be closed, by looking at the interfaces I see that the documentation isn't correct, it should receive something like
```js
showModal: {
    alpha: {
        from: 0,
        to: 1,
        duration: 200,
        interpolation: 'accelerate',
    },
},
```

i.e. without `content`

**But that doesn't work either**, please @guyca is it possible for someone to have a look at this, thanks for your effort

**Comment by dimasdanz** [comment]
Experiencing the same issue on build `2.13.1`, `dismissModal` animation works, but not `showModal`

**Comment by AlexKLWS** [comment]
Having the same issue. Also `setRoot` doesn't seem to work either. What's the status on this?

**Comment by Miyaguisan** [comment]
> Sorry guys I think this shouldn't be closed, by looking at the interfaces I see that the documentation isn't correct, it should receive something like
> 
> ```js
> showModal: {
>     alpha: {
>         from: 0,
>         to: 1,
>         duration: 200,
>         interpolation: 'accelerate',
>     },
> },
> ```
> 
> i.e. without `content`
> 
> **But that doesn't work either**, please @guyca is it possible for someone to have a look at this, thanks for your effort
> 
> **_NOTE:_** I'm testing in iOS

On Android this code works nice, but on iOS it won't. It doesn't work if we add the **content** key either. Is there a workaround?

**Comment by ialmoqren** [comment]
@Miyaguisan for me it wasn’t that necessary so I gave up after wasting a lot of time trying to find a workaround. It seemed to me like there isn’t one (other than using another library for the modal).
BTW I just wanted to say that we are considering switching to [react-navigation](https://github.com/react-navigation/react-navigation) mainly for these kind of issues, also I genuinely think that is where the community is heading.

**Comment by flikQ** [comment]
Hey @guyca is it possible for someone to take a look at this issue? Animations seem ok on Android but for me still plays the default bottom to top on iOS. 

Maybe the documentation is wrong?
