### ISSUE TITLE
registerCommandListener callback only passes name of event

### ISSUE THREAD

**Issue by stokesbga** [wix/react-native-navigation#4425]
### Issue Description

on both iOS and Android, im getting registerCommandListener only passing the name of the event as a string, and not a full object like in the documentation.

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.events().registerCommandListener(event => {
  console.log("NAVIGATION EVENT", event);       // Will print push, showModal, etc
});
```

---
### Environment
* React Native Navigation version: 2.2.0
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Device & Simulator/Debug

**Comment by vshkl** [comment]
@stokesbga huh, as I recall there is a typo in docs: https://wix.github.io/react-native-navigation/#/docs/events?id=registercommandlistener

Should be not
```es6
Navigation.events().registerCommandListener(({ name, params }) => {

});
```

but

```es6
Navigation.events().registerCommandListener((name, params) => {

});
```

**Comment by stokesbga** [comment]
Jesus christ.. thank you @vshkl
