### ISSUE TITLE
How to set initial selected tab index for bottom tabs?

### ISSUE THREAD

**Issue by liorbraginsky92** [wix/react-native-navigation#4426]
### Issue Description

I want to select specific tab for initial selection. How to approach this in V2?

---
### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by Abramovick** [comment]
I too have the same question.
Based on my current research, the way to do it is by using `currentTabIndex`. Something like this:

```
Navigation.setRoot({
  root: {
    bottomTabs: {
      children: [
        {
          component: {
            name: 'navigation.playground.TextScreen'
          }
        },
        {
          component: {
            name: 'navigation.playground.TextScreen'
          }
        }
      ],
      options: {
        bottomTabs: {
          currentTabIndex: 1
        }
      }
    }
  }
});
```

BUT, doing this doesn't work on iOS, but it works when done using `mergeOptions`. Something like this:

```
Navigation.mergeOptions(this.props.componentId, {
  bottomTabs: {
    currentTabIndex: 2,
  }
});
```

Which is a bit weird...

**Comment by LRNZ09** [comment]
The same issue mentioned by @Abramovick happens to me on latest version.

**Comment by henrikra** [comment]
I made fix PR here: https://github.com/wix/react-native-navigation/pull/4456

Can you test that branch and validate it works for you too :)

**Comment by Abramovick** [comment]
I just pulled the latest release v2.2.5 and I can confirm this is fixed and work on both iOS and Android.
Thanks @henrikra
