### ISSUE TITLE
Specify the default selected tab

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#443]
### Issue Description

I am using a tab based application for iOS and a single screen application with top tab bar for Android. I didn't find any documentation on how to specify the default selected tab when the application is started. Right now, it is the first tab for both bottom tab bar and top tab bar.

1. Is it possible to specify the default selected tab when the application starts. In other tab packages, I have seen that there is a condition `selected` that is specified per tab and whichever condition evaluated to `true` is the selected tab. Is there such an option available for the bottom tab bar and the top tab bar?

2. There is a way to programmatically switch to a different tab by using 

```js
this.props.navigator.switchToTab
```

The above API only works for the bottom tab. Is there such an API for the top tab bar as well where we can switch tabs programmatically.

### Environment
* React Native Navigation version: 2.0.0.experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug

**Comment by guyca** [comment]
@varungupta85 This features was requested before and we will add it.

**Comment by varungupta85** [comment]
hi @guyca, thanks for responding.

**Comment by LaPoPvLe** [comment]
hi @guyca, is it finished? how can i use it?

**Comment by salisuabubakar** [comment]
Is the feature implemented now? Thanks

**Comment by guyca** [comment]
Yes, look for `initialTabIndex` in the [docs](https://wix.github.io/react-native-navigation/#/top-level-api?id=starttabbasedappparams)

**Comment by salisuabubakar** [comment]
This is for bottom tabs. I want it for topTabs.

Thanks

**Comment by LuuLinhSon** [comment]
@guyca : How is initialTabIndex used in v2?

**Comment by burntzen** [comment]
Well I dont know if the `initialTabIndex` prop still exists in v2. I implemented it as follows to select another tab than the first on startup. Maybe it helps someone.

```
const bottomTabs = {
 	children: [
    	{
      		component: {
        		id: 'firstTab',
        		name: 'firstTab',
        		passProps: {
          			text: 'This is tab 1'
        		},
        		options: {
          			bottomTab: {
            			text: 'Tab 1',
            			icon: require('./assets/images/myIcon1.png'),
            			testID: 'FIRST_TAB_BAR_BUTTON'
          			}
        		}
      		}
		},
		{
      		component: {
        		id: 'secondTab',
        		name: 'secondTab',
        		passProps: {
          			text: 'This is tab 2'
        		},
        		options: {
          			bottomTab: {
            			text: 'Tab 2',
            			icon: require('./assets/images/myIcon2.png'),
            			testID: 'SECOND_TAB_BAR_BUTTON'
          			}
        		}
      		}
		},
		{
      		component: {
        		id: 'thirdTab',
        		name: 'thirdTab',
        		passProps: {
          			text: 'This is tab 3'
        		},
        		options: {
          			bottomTab: {
            			text: 'Tab 3',
            			icon: require('./assets/images/myIcon3.png'),
            			testID: 'THIRD_TAB_BAR_BUTTON'
          			}
        		}
      		}
		}
	]
}

Navigation.setRoot({
	root: {
		bottomTabs: bottomTabs
	}
});

Navigation.mergeOptions('secondTab', {
	bottomTabs: {
		currentTabIndex: 1
	}
});
```
