### ISSUE TITLE
[V2][iOS] currentTabIndex in common options has no effect

### ISSUE THREAD

**Issue by Dalamar** [wix/react-native-navigation#4433]
### Issue Description

After upgrade to 2.2.1 from ^2.0.2470 currentTabIndex has no effect in iOS app anymore.

in Android it works as expected but in iOS RNN alway starts tab based with first tab active instead of 3rd (index 2)

### Steps to Reproduce / Code Snippets / Screenshots

Set currentTabIndex option in common options like in the doc: 
https://wix.github.io/react-native-navigation/v2/#/docs/styling?id=common-options
``` ...},
  bottomTabs: {
   ...
    currentTabIndex: 2
   ...
```

**Tab based app with 4 tabs**
#### Expect behavior:
After app launch/reload have 3rd tab active.
#### Actual behavior:
After app launch/reload have 1st tab active.

---
### Environment
* React Native Navigation version: 2.2.1
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 6 OS 12.1.

**Comment by henrikra** [comment]
I made fix PR here: https://github.com/wix/react-native-navigation/pull/4456

Can you test that branch and validate it works for you too :)
