### ISSUE TITLE
[V2] `static options` broken when using a top bar button with a custom component platform: iOS v2

### ISSUE THREAD

**Issue by kfroemming** [wix/react-native-navigation#4436]
### Issue Description

When trying to set a custom component via `static options()` method inside a component, RNN throws an error in the top bar.
### Steps to Reproduce / Code Snippets / Screenshots
Steps to reproduce: 
Attempt to add a custom component tot the top bar without using `Navigation.mergeOptions`

Code Example: 
```   
static options() {
    return {
      topBar: {
        rightButtons: [
          {
            id: 'ADD',
            testID: 'addItem',
            component: {
              name: CUSTOM_NAV_BUTTON,
              passProps: {},
            },
          },
        ],
        testID: 'TEST',
      },
    };
  }
```
SCREENSHOT:
<a href="https://cl.ly/468b7aa6221f" target="_blank"><img src="https://d1wuojemv4s7aw.cloudfront.net/items/2S1l473O1O451015080o/Image%202018-12-11%20at%202.45.29%20PM.png" style="display: block;height: auto;width: 100%;"/></a>`

---
### Environment
* React Native Navigation version: 2.0.256
* React Native version: v0.57
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6s

**Comment by Pungsnigel** [comment]
Getting the same error. Any updates on this?
