### ISSUE TITLE
TopBar title loses bold when being set with mergeOptions()

### ISSUE THREAD

**Issue by tringuyen1121** [wix/react-native-navigation#4438]
### Issue Description

The title in topBar loses its bold style after being set with mergeOptions()
![](https://i.imgur.com/YNcehkV.gif)

### Steps to Reproduce / Code Snippets / Screenshots
```
constructor(props) {
    super(props);
    Navigation.events().bindComponent(this);
    Navigation.events().registerCommandListener((name, params) => {
      if (name === "push") {
        Navigation.mergeOptions(this.props.componentId, {
          topBar: {
            title: {
              text: ""
            }
          }
        });
      }
    });
  }

componentDidAppear() {
    Navigation.mergeOptions(this.props.componentId, {
      topBar: {
        title: {
          text: "Announcement post details"
        }
      }
    });
  }
```
---
### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): iOS 
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6

**Comment by utkusubakan** [comment]
Same issue here.

**Comment by markymc** [comment]
Same here.

**Comment by markymc** [comment]
I think this is still a problem, unless it's been fixed in a subsequent release?

**Comment by Collin3** [comment]
Definitely still a problem for me on version 2.7.1. I'll try upgrading to the latest, but I haven't seen anything that would have fixed this.

**Comment by Collin3** [comment]
@guyca is there anyway we can reopen this one? Correct me if I'm wrong, but as far as I can tell this hasn't been fixed yet.
