### ISSUE TITLE
navigatorButtons not applied

### ISSUE THREAD

**Issue by chaitanya0bhagvan** [wix/react-native-navigation#444]
### Issue Description
If you have navigatorButtons object in the params to navigator.push or navigator.resetTo, buttons are not rendered. I am using react-native-vector-icons.

>     {
>       label: 'Test',
>       screen: 'TestScreen',
>       navigatorButtons: {
>         leftButtons: [{
>           id: 'toggle_menu',
>           icon: iconsMap['ios-menu']
>         }]
>       },
>       navigatorStyle: {
>       },
>       animated: false
>     }
> 

### Steps to Reproduce / Code Snippets / Screenshots
push or resetTo with navigatorButtons in the params object. In android those buttons are not displayed.

---
### Environment
* React Native Navigation version: 2.0.0-experimental.141
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug

**Comment by Crash--** [comment]
Loading an icon is an async task. So you need to resolve the icon before pushing anything. 

See #43 ;)

**Comment by guyca** [comment]
@chaitanya0bhagvan I'm closing the issue since passing navigatorButtons as params to navigator commands (push for example) will soon be deprecated.

**Comment by chaitanya0bhagvan** [comment]
@Crash-- my icons are already resolved, I am doing that before any calls to startApp

**Comment by chaitanya0bhagvan** [comment]
@guyca What is the correct way to specify left and right navigator buttons.

**Comment by guyca** [comment]
@chaitanya0bhagvan [specify a static navigatorButtons object in your screen](https://github.com/wix/react-native-navigation/wiki/Adding-buttons-to-the-navigator).

**Comment by Jaafar-abusair** [comment]
Just use setButtons in the pushed screen, this.props.navigator.setButtons({})
