### ISSUE TITLE
Support setting multiple children in setStackRoot

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#4441]
Currently setStackRoot method allows us to reset a stacks root to a single child. We need to support setting multiple children, similar to the stack declaration api which accepts a `children` array.
This feature should be backwards compatible.

## API
```jsx
Navigation.setStackRoot(this.props.componentId, {
  children: [
    {},
    {}
  ]
});

**Comment by henrikra** [comment]
Okay sounds good! We need to asap too! :D Tell me if I can help and also I can review <3
