### ISSUE TITLE
Bottom tab badge position

### ISSUE THREAD

**Issue by ammoradi** [wix/react-native-navigation#4442]
### Issue Description

it seems there is not an option to change the position of the badge to right, center or the other positions.

---
### Environment
* React Native Navigation version: 2.1.3-patch.2
* React Native version: 0.56.0

**Comment by haiderali101** [comment]
@ammoradi did you find any solution to this?

**Comment by ammoradi** [comment]
@haiderali101 not yet.
I didn't test RNN v4 for react native 0.6x
