### ISSUE TITLE
[v2] searchBar: false render a searchBar on iOS 11+

### ISSUE THREAD

**Issue by dozoisch** [wix/react-native-navigation#4443]
### Issue Description

`searchBar: false` renders a search bar on iOS 11+.

### Steps to Reproduce / Code Snippets / Screenshots

Create a component with the following definition.

```
{
  component: {
  id: "a.component",
  name: "a.component",
  options: {
    topBar: {
      searchBar: false,
      title: {
        text: "Search Bar is Visible,
      },
    },
  },
}
```

Without `searchBar: false` there is no search bar, with `searchBar: any`, a wild search bar appears.

This is due to https://github.com/wix/react-native-navigation/blob/b0c8113243de2043b98442dd485c04b0422aa213/lib/ios/RNNViewControllerPresenter.m#L31 just checking if there is a value instead of making sure the value is truthy.

I wanted to do a PR, but it's also present here https://github.com/wix/react-native-navigation/blob/b0c8113243de2043b98442dd485c04b0422aa213/lib/ios/RNNViewControllerPresenter.m#L67 and I wasn't sure how to handle removing the search bar.

---
### Environment
* React Native Navigation version: 2.1.3-snapshot.50
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 11+

**Comment by mathieumg** [comment]
Not stale.

**Comment by dozoisch** [comment]
Not stale :)

**Comment by mathieumg** [comment]
Not stale

**Comment by alexey-chernikov** [comment]
Not stale

**Comment by mathieumg** [comment]
Not stale.

**Comment by mathieumg** [comment]
Not stale.

**Comment by dozoisch** [comment]
Not stale!

**Comment by dozoisch** [comment]
No stale/

**Comment by mathieumg** [comment]
Not stale.

**Comment by mathieumg** [comment]
Not stale.

**Comment by dozoisch** [comment]
💃 not stale

**Comment by mathieumg** [comment]
Not stale.

**Comment by simonasdev** [comment]
I could submit a PR if anyone would point me in the right direction - I wonder whether setting `UIViewController`'s `navigationItem.searchController` to `nil` would suffice

**Comment by dozoisch** [comment]
Not stale

**Comment by captaincole** [comment]
Still not stale...

**Comment by dozoisch** [comment]
not stale

**Comment by dozoisch** [comment]
not stale

**Comment by dozoisch** [comment]
not stale

**Comment by dozoisch** [comment]
not stale
