### ISSUE TITLE
calling setRoot keeps all previous components in memory?

### ISSUE THREAD

**Issue by mcampsall** [wix/react-native-navigation#4444]
Because [hiding the tabbar for one tab is no longer supported by RNN](url
https://github.com/wix/react-native-navigation/issues/4439#issuecomment-446712801), I have had to use `setRoot` to switch between a stack layout and bottomTabs layout to get the same functionality. However, all of the previous components are still around and each time I call `setRoot`, it just adds more:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/15930818/49898149-0cf1c000-fe0d-11e8-831a-d7b483414a82.png">

Is there a way to call this to either re-use the components already there, or to clear the old ones out?

Or, alternatively, is there another solution out there to accomplish this?

**Comment by mcampsall** [comment]
I think it is caused by `Navigation.events().registerBottomTabSelectedListener`.

[reference](url
https://github.com/wix/react-native-navigation/issues/3164#issuecomment-416519585)

**Comment by guyca** [comment]
Hey @mcampsall 
Components are unmounted when root is set - if you think there's a leak, can you please PR a failing detox test?
I'm closing the issue as I'm not aware of any leaks around setRoot, will reopen if we can confirm the issue.

**Comment by mcampsall** [comment]
@guyca,  I have not used detox and am unable to put that together quickly (it is on my learning agenda).

The issue was having `Navigation.events().registerBottomTabSelectedListener` on a component. Calling setRoot did indeed keep that component around. I was able to solve the issue by removing the listener as shown below:

```
   constructor(props) {
    super(props);
    listener = Navigation.events().registerBottomTabSelectedListener(({ selectedTabIndex, unselectedTabIndex }) => {this.bottomTabSelected(selectedTabIndex, unselectedTabIndex)});
  }

  componentWillUnmount() {
    listener.remove();
  }
```
