### ISSUE TITLE
[V2] [Android] default options override merge options

### ISSUE THREAD

**Issue by Collin3** [wix/react-native-navigation#4445]
### Issue Description

Android `mergeOptions` is using the default options instead of what is passed via `mergeOptions` for `leftButtons` and `rightButtons`. This seems to only be an issue on Android and it is only a problem when the default settings for the buttons are set to components. If I set icons as the topbar buttons, then merge options works as expected when I override them with another icon through `mergeOptions`. It also works as expected if I set the default buttons to components and then override them with a different component through `mergeOptions`.

### Steps to Reproduce

On Android, if you define `rightButtons` via `setDefaultOptions` providing a custom component, but try to override them on a screen with `mergeOptions` providing an icon instead of a component, on `componentDidMount`, the right buttons from the default options will be used instead of what was passed through merge options. 

Please let me know if you need more details. Thanks!

---
### Environment
* React Native Navigation version: 2.2.0
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android only
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Pixel 2 API 28 using Android 8.1, as well as on an actual device of Samsung Galaxy S6 Android version 7.0

**Comment by Collin3** [comment]
I believe this is still a problem. Will try to reproduce on the latest version to confirm.

**Comment by Collin3** [comment]
Still a problem on React Native Navigation version: 2.7.1 and React Native version: 0.57.8

**Comment by Collin3** [comment]
Still an issue..

**Comment by Collin3** [comment]
Still an issue

**Comment by rheutz** [comment]
I'm also facing this issue. Is there any solution for this?

**Comment by Collin3** [comment]
Sadly the only way I've been able to avoid this is to not use default options for left/right buttons on the topbar...

**Comment by Collin3** [comment]
Still an issue on 2.16.0

**Comment by igortupini** [comment]
Still an issue on 2.18.5
