### ISSUE TITLE
Show a view above the navigator

### ISSUE THREAD

**Issue by wbeuil** [wix/react-native-navigation#4446]
### Issue Description

I'd like to know if, with RNN v2, it is possible to display a view above the navigation bar. My purpose is to show an in-app notification view. But it seems that I can only show below the navigation bar since I can't wrap the navigator.

Any suggestions?

**Comment by vshkl** [comment]
@wbeuil I feel like it should be some lib implemented natively as per platform rather then purely JS solution. But I can't remember any such lib right now. However, it's not that hard to call native code from you RN app's realm, especially if you don't need some heavy customization of those alerts (I mean if you don't need to expose all the lib's API to the JS realm).

**Comment by wbeuil** [comment]
@vshkl thank you, I will take a look at those libs.

**Comment by guyca** [comment]
@wbeuil You can show an [Overlay](https://wix.github.io/react-native-navigation/#/docs/top-level-api?id=showoverlaylayout-) which is positioned over the root and all modals.

**Comment by marcelglaeser** [comment]
@guyca can you give me a quick sample for that? What is structure of Navigation.setRoot(); ?

**Comment by guyca** [comment]
@marcelglaeser I suggested showing an overlay. Overlays aren't part of the root declaration. Instead, they are displayed with the `Navigation.showOverlay` command.

**Comment by chrise86** [comment]
@guyca is this still the case? I can see Typescript suggests `LayoutRoot.overlays` but it simply has a type of `any`. Does this API exist currently?
