### ISSUE TITLE
Navigation bar buttons are not shown for the default tab while using top tab bar

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#445]
### Issue Description

I am using a single screen app with a top tab bar. While configuring the application, I have provided a dummy screen as the `screen` for the single screen app and provided the tabs in the `topTabs` sections like so

```js
    Navigation.startSingleScreenApp({
        screen: {
          screen: 'TopTabsScreen',
          title: 'App',
          navigatorStyle: {},
          topTabs: [
            {
              screenId: 'AlarmListScreen',
              title: 'Alarms'
            },
            {
              screenId: 'GroupListScreen',
              title: 'Groups'
            },
            {
              screenId: 'ContactListScreen',
              title: 'Contacts'
            }
          ]
        },
        passProps: {},
        animationType: 'slide-down'
      });
```

`TopTabsScreen` is a dummy screen which is defined like this. I got this from the `old-example-redux` project

```js
export default class TopTabsScreen extends Component {
  static navigatorStyle = {
    navBarBackgroundColor: '#4dbce9',
    navBarTextColor: '#ffff00',
    navBarSubtitleTextColor: '#ff0000',
    navBarButtonColor: '#ffffff',
    statusBarTextColorScheme: 'light',
    tabBarBackgroundColor: '#4dbce9',
    tabBarButtonColor: '#ffffff',
    tabBarSelectedButtonColor: '#ffff00'
  }

  render() {
    return null;
  }
}
```

By default, the first tab `AlarmListScreen` appears on the screen. `AlarmListScreen` contains a bunch of right buttons but none of them appear. As soon as I change the tab, then the buttons start to appear as expected which I think is because I am catching the `tabSelected` event and updating the navigation buttons for each tab as a result of the event. This has to be done this way because currently, the buttons don't change when changing top tabs #439 . This is how the `AlarmListScreen` is configured

```js
export default class AlarmListScreen extends Component {
  static navigatorButtons = {
    rightButtons: getRightButtonsForAlarmList() // Show buttons All, My, Participant, Upcoming on the right
  }
  // other methods
}
```

This is how it appears when the app is loaded the first time. Observe that there are no right buttons

![screen shot 2016-11-15 at 4 46 11 pm](https://cloud.githubusercontent.com/assets/7475133/20303789/19f394f4-ab53-11e6-95ba-1118be4b3b9f.png)

This is how the app appears once I change the top tab to `Groups` and then back to `Alarms`. Notice that the right buttons are shown as expected

![screen shot 2016-11-15 at 4 46 29 pm](https://cloud.githubusercontent.com/assets/7475133/20303813/347bef24-ab53-11e6-8f39-b5811611391a.png)

I guess the missing piece is that `tabSelected` event is only fired when the tab is changed. If there is any event that is fired when the first tab is shown, I can catch that event and update the navigator buttons.

I tried to just add these buttons in the `TopTabsScreen` and that shows the buttons as expected but the problem remains that the navigator events won't be hooked up such that the `AlarmListScreen` receives the event. I also tried to specify `AlarmListScreen` as the `screen` for the single screen app but that also creates some problems with the navigator button events and none of the events are fired.
 
### Environment
* React Native Navigation version: 2.0.0.experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug

**Comment by DanielZlotin** [comment]
You are probably looking for the screen lifecycle events feature. Coming soon. see #120

**Comment by varungupta85** [comment]
@DanielZlotin I think lifecycle events feature could be used to handle it but I think this should be would be working even without the lifecycle event feature and I really think that I may be missing something. So, is this the expected behavior right now that in case a single screen app with top tabs, the user won't see any of the buttons configured for the first tab unless they change to a different tab and come back.

**Comment by guyca** [comment]
I agree with @varungupta85, This is something RNN should take of for you, it'll be part of v2.0 release. Thanks for your patience 👍

**Comment by DanielZlotin** [comment]
@guyca Go ahead and add it

**Comment by varungupta85** [comment]
I was able to get around this problem for now by adding the navigator buttons in the `componentWillMount` method of the screen component of the first tab as well.

**Comment by andrzey** [comment]
@guyca absolutely love RNN. is there an estimate as to when v2 will be released?
