### ISSUE TITLE
[V2] How to get height between top bar and bottom tabs?

### ISSUE THREAD

**Issue by jasnoponjatno** [wix/react-native-navigation#4453]
### Issue Description

Is there a way to get height between top bar bottom line and bottom tabs top line, or somehow calculate it?

![screenshot 2018-12-15 at 02 11 52](https://user-images.githubusercontent.com/15952585/50036194-a12b7500-000f-11e9-99a6-0700565d0a45.png)

**Comment by ItsNoHax** [comment]
Use React-Native’s Dimensions?
