### ISSUE TITLE
[V2] TopBar - Title Font Weight?

### ISSUE THREAD

**Issue by rsokz** [wix/react-native-navigation#4454]
### Issue Description

Is there a way to set `fontWeight` for the `TopBar` title?

in v1, `navigatorStyle` could take `navBarTextFontWeight`

### Steps to Reproduce / Code Snippets / Screenshots

Currently can't adjust the `fontWeight`.

---
### Environment
* React Native Navigation version: 2.2.1
* React Native version: 0.52
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator - iOS 12.1 - Debug

**Comment by rsokz** [comment]
Found a solution. The only way to do it is do set the `fontFamily` for the `title` to the name of your font. 

Example: If using `SF Pro Display` font, and you want a fontWeight of 300:
```
title: {
    fontFamily: 'SFProDisplay-Light',
}
```

**Comment by KieranWitt** [comment]
Hey @rsokz, for someone who is new to react native do you have an example how you set up your font i.e. `SFProDisplay-Light` for the `fontFamily` prop assuming `SF Pro Display` is the basic font and the `-Light` part is your fontWeight that you've defined elsewhere.
