### ISSUE TITLE
[V2] iOS app stuck on launch screen

### ISSUE THREAD

**Issue by dobrynia** [wix/react-native-navigation#4459]
### Issue Description
First of all, thank you for your hard work on the plugin.

The application is stuck on launch screen if there is no image with a specific name for the launch screen.

### Steps to Reproduce / Code Snippets / Screenshots

It is enough to run the application without the required image of the launch screen.

https://github.com/wix/react-native-navigation/blob/62f6dbaa366855832b1b343acf1ff8ba1e135bfa/lib/ios/RNNSplashScreen.m#L69

If the image file is not found, the `viewController` is not initialized and not passed condition above in the `RNNSplashScreen.m` file. I thought the problem might be because of this, and when I added the code below before condition, everything worked as it should.

```
if (viewController == nil) {
		viewController = [[RNNSplashScreen alloc] init];
}
```
---
### Environment
* React Native Navigation version: 2.2.5
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both simulator and device, iOS 12.1, Debug and Release

**Comment by stokesbga** [comment]
I moved splashscreen.hide() to inside appDidLaunch, instead of waiting for setRoot, and that seemed to help. It's only like this in debug for me. Once splash goes away, i turn on remote debugging and the slowness/stuck issue goes away

**Comment by dobrynia** [comment]
I already use the `react-native-splash-screen` plugin if you are talking about it. It does not help. I think that it is necessary to find a more correct solution related to the `react-native-navigation` plugin.

**Comment by amed** [comment]
This happens on a fresh version. 

react-native: `0.58.6`
react-native-navigation: `^2.13.1`

1 - Create a new app 
2 - Install on ios as described [here](https://wix.github.io/react-native-navigation/#/docs/Installing) 
3 - Start Successfully
4 - Refresh the app 
5 - App Stuck on default loading splash

**Comment by kriptonhaz** [comment]
just happened with fresh version

react-native: 0.59.1
react-native-navigation: ^2.14.0
xcode: 9.1

whenever start on the simulator if the app is fresh installed it's always got stuck on the first screen (I set a loading screen as the first screen), but if the app already in there and run again from xcode or just reload directly in the simulator it's work again.

**Comment by alpamys-qanybet** [comment]
@kriptonhaz, you have also another problem, if you try to archive Xcode 9 it will get error, you can fix it only with Xcode10.

**Comment by kriptonhaz** [comment]
@alpamys-qanybet  so if I use Xcode10 it will solve this whole issue?

**Comment by iksent** [comment]
I am using Xcode 10.1 and have the same problem.

**Comment by amed** [comment]
It seems that `AppDelegate.m`  launchOptions order has something to do with it. 😕

**Comment by alpamys-qanybet** [comment]
@kriptonhaz, @iksent, @amed, I just overall come with this stack: RN0.59.1, RNN0.1.x(needs some extra coding) in detail:
   ```ios: RN0.59.1 compatibility```
   [issue] (https://github.com/wix/react-native-navigation/issues/4864)
   [solution](https://github.com/wix/react-native-navigation/commit/57caacddfc5422c00f41b32e031a732ab503b7dc)

**Comment by alpamys-qanybet** [comment]
@kriptonhaz, @iksent, @amed, also there are some workarounds on android for http load and etc, but facing specific problem you can luckily get the answer.

**Comment by ranaharoni** [comment]
@kriptonhaz @amed @dobrynia @iksent I'm stuck with this issue too, I tried downgrading to RN@0.58.6 and I encounter the same issue.

Did you manage to get it working?
