### ISSUE TITLE
When will RNN compatible with RN 0.37 and be available on NPM?

### ISSUE THREAD

**Issue by lglomer** [wix/react-native-navigation#446]
### Issue Description

I want to start a new project and integrate RNN to it. I want to use the latest RN (0.37) but RNN is not compatible with it.

When will it be available?
Can I set it up before it's out?

---
### Environment
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator - debug

**Comment by guyca** [comment]
Latest experimental version (.141) supports RN 0.37
