### ISSUE TITLE
[Android] Calling mergeOptions doesn't update bottomTabs

### ISSUE THREAD

**Issue by Jazqa** [wix/react-native-navigation#4462]
### Issue Description

Calling mergeOptions doesn't update tabs

### Steps to Reproduce / Code Snippets / Screenshots

1. Dynamically give a badge to a bottomTab
2. Doesn't update
3. Open a modal
4. Dismiss the modal
5. BottomTab updated with the badge

---
### Environment
* React Native Navigation version: 2.2.5
* Platform(s) (iOS, Android, or both?): Android

**Comment by Stacyadam** [comment]
Having this same issue when trying to mergeOptions and set a badge on the bottomTabs. Works as expected for iOS. Were you able to find a solution for this?

**Comment by matpaul** [comment]
Same issue on android (last version)

**Comment by matpaul** [comment]
@Jazqa @Stacyadam found fix just set id in stack.children.component
```
{
 stack: {
 children: [
     {
      component: {
          id: 'ACCOUNT', <--- here 
          name: SCREENS.account.menu,
    },
   },
  ],
 options: {
   bottomTab: {
    iconInsets,
    selectedIconColor: colors.secondary,
    icon: profileIcon,
 },
},
 }
```
