### ISSUE TITLE
[V2][iOS] SplitView - EXC_BAD_ACCESS when split screen is enabled

### ISSUE THREAD

**Issue by gcox** [wix/react-native-navigation#4463]
### Issue Description

When using the SplitView layout, and split *screen* is enabled, a crash occurs when you size the app down to either either the 50/50 or 20/80 split (other app taking up 80%).

### Steps to Reproduce / Code Snippets / Screenshots

This is reproducible in the Playground app

1. Enable split screen by adding this to the Playground app's info.plist:
```
  <key>UISupportedInterfaceOrientations~ipad</key>
  <array>
    <string>UIInterfaceOrientationLandscapeLeft</string>
    <string>UIInterfaceOrientationLandscapeRight</string>
    <string>UIInterfaceOrientationPortraitUpsideDown</string>
    <string>UIInterfaceOrientationPortrait</string>
  </array>
```
2. Run the playground app
3. Rotate to landscape
4. Tap `Switch to split view based app`
5. Drag another app like Safari to the far right of the screen to enable splitting the screen with it. Should start at 80/20 (Playground taking up 80%).
6. Drag the splitter to either the 50/50 or 20/80 split location and release. A crash will follow.

![screenshot 2018-12-17 10 31 15](https://user-images.githubusercontent.com/251512/50097048-02597100-01e7-11e9-96c3-e6334f5f2150.png)

---
### Environment
* React Native Navigation version: 01bcfbab
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPad Pro (9.7 Inch) simulator (iOS 12.1). Have not tried on a device.

**Comment by exentrich** [comment]
Please reopen issue! On iPad resize leads to crash.

**Comment by exentrich** [comment]
@gcox do you find any solution?

**Comment by gcox** [comment]
@exentrich Unfortunately no.
