### ISSUE TITLE
How to Style SideMenu to be on top of screen

### ISSUE THREAD

**Issue by ebrahimhassan121** [wix/react-native-navigation#4468]
### Issue Description

[ENTER DESCRIPTION HERE]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by ItsNoHax** [comment]
Closing issue because Issue template is not filled in.
