### ISSUE TITLE
BUILD FAILED on run-android (with react-native-navigation@2.0.0-experimental.141)

### ISSUE THREAD

**Issue by lglomer** [wix/react-native-navigation#447]
### Issue Description

**Similar issues: #359 , #333 ..**

I integrated the current version of RNN into a new project. I followed the instructions in the Wiki but keep getting an error after `react-native run-android`.

The error is `:react-native-navigation:compileReleaseJavaWithJavac FAILED`. I don't understand why it persists as I am using the latest version of RNN (.141) as suggested in similar issues.

### Steps to Reproduce / Code Snippets / Screenshots

Console output after `react-native run-android`:

```
:react-native-navigation:compileReleaseJavaWithJavac
C:\Users\Omer\Desktop\Apps\PetSpot\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\react\NavigationReactGateway.java:78: error: method onActivityResult in class ReactInstanceManager cannot be applied to given types;
        getReactInstanceManager().onActivityResult(currentActivity, requestCode, resultCode, data);
                                 ^
  required: int,int,Intent
  found: Activity,int,int,Intent
  reason: actual and formal argument lists differ in length
Note: C:\Users\Omer\Desktop\Apps\PetSpot\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\react\ResourceDrawableIdHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-navigation:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

#### /android/app/build.gradle

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.petspot"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':react-native-navigation') // Wix nav
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

```

#### /android/settings.gradle

```
rootProject.name = 'PetSpot'

include ':app'
include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/android/app/')
```

#### /android/app/src/main/java/com/petspot/MainActivitiy.java

```
package com.petspot;

import com.facebook.react.ReactActivity;
import com.reactnativenavigation.controllers.SplashActivity;

public class MainActivity extends SplashActivity { // extended ReactActivity
}
```

#### /android/app/src/main/java/com/petspot/MainApplication.java

```
package com.petspot;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;


import android.support.annotation.Nullable;

import com.facebook.react.ReactPackage;
import com.reactnativenavigation.NavigationApplication;

import java.util.List;

public class MainApplication extends NavigationApplication {
  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }
  
  @Nullable
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return null;
  }
}
```

---
### Environment
* React Native Navigation version: react-native-navigation@2.0.0-experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android

**Comment by varungupta85** [comment]
Looks like gradle is trying to link to an older version of `react-native`. Can you try running `./gradlew clean` in the `/Project/android` directory and try running the command again? The other two issues you mentioned were actually trying to use a higher version of `react-native` with this package which was not supported but `.141` supports RN 0.37.

**Comment by lglomer** [comment]
@varungupta85 it doesn't recognize the command gradlew. I removed the `./` from your suggestion, it seems like a typo.

**Comment by guyca** [comment]
I think @varungupta85 is right. Make sure you're using RN from node modules and not some older version cached by gradle.

make sure you have this code block in `build.gradle` (the one in your projects root directory)
```groovy
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

**Comment by lglomer** [comment]
Thanks, I just now noticed that my react-native version is not 0.37 as I thought.
Totally my bad, thanks for the help guys.

**Comment by fufag** [comment]
hi, I am trying to install RNN packages by following all the steps described in its official website . After followed each and every step carefully I run it using react-native run-android command in the terminal and facing an issue again and again. It halted my progress and very annoying also

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Terminal is indicating this message. Please give me some solution to remove this error

Here is my app/gradle code below

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by NagarajRaju** [comment]
> Looks like gradle is trying to link to an older version of `react-native`. Can you try running `./gradlew clean` in the `/Project/android` directory and try running the command again? The other two issues you mentioned were actually trying to use a higher version of `react-native` with this package which was not supported but `.141` supports RN 0.37.



> Looks like gradle is trying to link to an older version of `react-native`. Can you try running `./gradlew clean` in the `/Project/android` directory and try running the command again? The other two issues you mentioned were actually trying to use a higher version of `react-native` with this package which was not supported but `.141` supports RN 0.37.

getting same bug for react-native-navigation 2 and it points older version of 0.51. i am using 0.56.
