### ISSUE TITLE
App doesn't load and stuck on white screen when restored from minimized/background state

### ISSUE THREAD

**Issue by Rana-Muhammad-Amir** [wix/react-native-navigation#4471]
I tried solutions #3011 and search some others but no luck....
@guyca please guide for the solution version of dependencies are mentioned..... 
platform Android...
"dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.5",
  "react-native-navigation": "^2.1.3",
    "react-native-share": "^1.1.3",
  },

**Comment by rawrmaan** [comment]
Are you using `Navigation.events().registerAppLaunchedListener()` to initialize your app? I noticed that if you press the back button from the root view controller, it kills everything and "re-launches" the app. Not sure why it's like that...seems far from ideal.

**Comment by Rana-Muhammad-Amir** [comment]
@rawrmaan if i use Navigation.events().registerAppLaunchedListener() to initialize app like below  is my index.js.....
i got error screenshot attached...
i am new to react-native please mention if i am doing any mistake ....
![screenshot-2018-12-19_10 32 53 266](https://user-images.githubusercontent.com/37925492/50200883-a8d57b80-0379-11e9-8f84-9c559da7fbaa.png)

import { Navigation } from "react-native-navigation";
import {AppRegistry} from 'react-native';
import App from './App';
import  SplashScreen  from "./Script/SplashScreen";
import  HomeScreen  from './Script/HomeScreen';
import  SideMenu  from "./Script/SideMenu";
import {name as appName} from './app.json';


//Navigation.registerComponent(appName, () => App);
Navigation.registerComponent('App', () => App); 
Navigation.registerComponent('SplashScreen', () => SplashScreen);
Navigation.registerComponent('HomeScreen', () => HomeScreen);n);
Navigation.registerComponent('SideMenu', () => SideMenu);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      component: {
        name: "App"
      }
    }
  });
});

**Comment by Rana-Muhammad-Amir** [comment]
@rawrmaan  thanks it works after some change .....
thanks again for your help!
