### ISSUE TITLE
[V2] TopBar with LargeTitle + ScrollView

### ISSUE THREAD

**Issue by Purii** [wix/react-native-navigation#4475]
### Issue Description

Large Title is not shown when opening the screen.
After scrolling up the title becomes visible.

|                           Screen opened                           |                                         Scrolled up                                          |
| :-----------------------------------------------------------------------------------: | :-----------------------------------------------------------------------------------------: |
| ![initially](https://user-images.githubusercontent.com/7056989/50183488-80fefd00-0312-11e9-9bb3-0fe922f6de9e.png) | ![afterscrolling](https://user-images.githubusercontent.com/7056989/50183486-80666680-0312-11e9-9f11-4c4bca03d8b1.png) |

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, { Component } from "react";
import {
  Dimensions,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  View
} from "react-native";

const instructions = Platform.select({
  ios: "Press Cmd+R to reload,\n" + "Cmd+D or shake for dev menu",
  android:
    "Double tap R on your keyboard to reload,\n" +
    "Shake or press menu button for dev menu"
});

type Props = {};
export default class Screen2 extends Component<Props> {
  static options(passProps) {
    return {
      bottomTab: {
        text: "Screen 2"
      },
      topBar: {
        title: {
          text: "Screen 2"
        },
        visible: true,
        animate: true,
        largeTitle: {
          visible: true
        }
      }
    };
  }

  render() {
    return (
      <ScrollView contentContainerStyle={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF",
    minHeight: Dimensions.get("window").height * 2
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10
  },
  instructions: {
    textAlign: "center",
    color: "#333333",
    marginBottom: 5
  }
});

```

---
### Environment
* React Native Navigation version: `2.2.5`
* React Native version: `0.57.8`
* Platform(s) (iOS, Android, or both?): `iOS`
* Device info (Simulator/Device? OS version? Debug/Release?): `Simulator > Debug`

**Comment by Purii** [comment]
Needed second screen to demonstrate because of https://github.com/wix/react-native-navigation/issues/3429.

**Comment by Purii** [comment]
This issue still occurs

**Comment by jinshin1013** [comment]
This issue it still relevant.

**Comment by ericschaal** [comment]
+1

**Comment by julianklumpers** [comment]
Here is a quick workaround.

<ScrollView ref={ref => ref.scrollTo({x: 0, y: -10})>

or

`<ScrollView ref={ref => (this.view = ref)}>`
and then in componentDidMount:
`  componentDidMount() {
    this.view.scrollTo({ x: 0, y: -10})
  }`

**Comment by hahtml** [comment]
bump

**Comment by cesarm16** [comment]
This issue still occurs.

**Comment by hammadj** [comment]
Still happens

**Comment by Findiglay** [comment]
+1
