### ISSUE TITLE
Android bottom bar icon is looking small

### ISSUE THREAD

**Issue by Deepaknathtiwari** [wix/react-native-navigation#4476]
### Issue Description

Bottom tab bar icon look small in android in comparison of ios Bottom tab bar icon

 

### Steps to Reproduce / Code Snippets / Screenshots

Ios: 

![screen shot 2018-12-19 at 5 38 18 pm](https://user-images.githubusercontent.com/12734438/50219364-f8856880-03b4-11e9-8195-03ac7718cb98.png)

Android: 

![screen shot 2018-12-19 at 5 38 03 pm](https://user-images.githubusercontent.com/12734438/50219366-f91dff00-03b4-11e9-8155-00c16faf7cc7.png)

---
### Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 2.25 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.2, 27.0.3, 28.0.0
        System Images: android-23 | Google APIs Intel x86 Atom, android-26 | Google APIsIntel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
      react-native: ^0.57.4 => 0.57.7
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

**Comment by flikQ** [comment]
Still an issue in [V6]
