### ISSUE TITLE
[v2] Sidemenu is remounted on each setRoot

### ISSUE THREAD

**Issue by sja1n** [wix/react-native-navigation#4477]
### Issue Description

I have 4 screens to navigate through them I use drawer, so now whenever I use `Navigation.setRoot(...)` it remounts my drawer component as well, is there are way to only change the center view and not the sidemenu view

as in drawer I have to maintain persistent connection to server, so most of the core logic is in drawer as per v1 architecture it was never remounted on resetting root view. 

---
### Environment
* React Native Navigation version: 2.2.5
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Real device

**Comment by guyca** [comment]
Set the center view to a stack and use `setStackRoot`

**Comment by sja1n** [comment]
Hi, thanks for the clarification, but while using it I am getting
 `Error: Failed to execute stack command. Stack PAGE2 not found.`, while using setStackRoot from the sidemenu
