### ISSUE TITLE
Mistake in the docs about onAppLaunched

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#4483]
### Issue Description

When looking the search results https://github.com/wix/react-native-navigation/search?q=onapplaunched&unscoped_q=onapplaunched it looks like `onAppLaunched` doesn't exist anymore. 🤷‍♂️

**Comment by guyca** [comment]
<img width="1339" alt="screen shot 2018-12-20 at 10 55 37" src="https://user-images.githubusercontent.com/12352397/50274382-cf60e880-0445-11e9-8aa7-237d36280a98.png">

**Comment by henrikra** [comment]
What do you mean by this picture? :D Because it clearly shows that the function name is `registerAppLaunchedListener` and not `onAppLaunched`

Also error is wrong
![image](https://user-images.githubusercontent.com/12229968/50274511-21a20980-0446-11e9-8228-33cfa6613fbc.png)
