### ISSUE TITLE
Docs need to be more detailed ?

### ISSUE THREAD

**Issue by trinadhkoya** [wix/react-native-navigation#4484]
Can you just clarify these below stuff ,
The Provided docs are belongs to v1 or v2?
What is stable v2 Version to use  for upcoming apps.
Where can i see docs for both v1 and v2

**Comment by henrikra** [comment]
I have been using v2 around three months now and it is pretty good 👍 Use that

**Comment by guyca** [comment]
Hey there,
The docs can definitely use some TLC, you're welcome to take a stab at it.
