### ISSUE TITLE
[V2] Toptabs are not showing up, regression in newest version of RNN

### ISSUE THREAD

**Issue by the-friyia** [wix/react-native-navigation#4485]
### Issue Description

There has been a regression in Top Tabs Navigation for React-Native-Navigation. After version  2.0.2459 topTabs will no longer appear. 

I am currently using the code below with version 2.2.5, however, that code allows me to swipe right and left and the app will transition screens BUT tabs themselves will not appear. 

If I downgrade to 2.0.2459 again, the top tabs once again appear.

### Steps to Reproduce / Code Snippets / Screenshots

```
        stack: {
          id: 'mainStack',
          children: [
            {
              topTabs: {
                children: [
                  {
                    component: {
                      name: 'Screen1',
                      options: {
                        topTab: {
                          title: 'Tab 1',
                        },
                      },
                    },
                  },
                  {
                    component: {
                      name: 'Screen2',
                      options: {
                        topTab: {
                          title: 'Tab 2',
                        },
                      },
                    },
                  },
                ],
              },
            },

```  

### Environment
* React Native Navigation version: 2.2.5
* React Native version: 0.55.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by Ibrahim-GHub** [comment]
I am also facing this issue with "react-native-navigation": "^2.3.0"

`Navigation.push('insp-req', {
    stack: {
        id: 'insp-req-info-stack',
        children: [{
            topTabs: {
                currentTabIndex: 0,
                currentTabId: 'insp-req-info',
                children: [{
                    component: {
                        id: 'insp-req-info',
                        name: 'InspectionRequestDocumentInfo',
                        options: {
                            topTab: {
                                title: 'Info'
                            },
                            topBar: {
                                title: {
                                    text: 'Details'
                                }
                            }
                        },
                        passProps: {
                            id: id,
                            projectId: projectId
                        }
                    }
                }, {
                    component: {
                        id: 'insp-req-workflow',
                        name: 'InspectionRequestDocumentWorkflow',
                        options: {
                            topTab: {
                                title: 'Workflow'
                            },
                            topBar: {
                                title: {
                                    text: 'Details'
                                }
                            }
                        },
                        passProps: {
                            id: id,
                            projectId: projectId
                        }
                    }
                }, {
                    component: {
                        id: 'insp-req-attachments',
                        name: 'InspectionRequestDocumentAttachments',
                        options: {
                            topTab: {
                                title: 'Attachments'
                            },
                            topBar: {
                                title: {
                                    text: 'Details'
                                }
                            },
                            fab: {
                                id: "attach",
                                backgroundColor: "#9F854F",
                                hideOnScroll: true,
                                icon: images.add
                            }
                        },
                        passProps: {
                            id: id,
                            projectId: projectId
                        }
                    }
                }],
                options: {
                    topTabs: {
                        unselectedTabColor: '#FFF',
                        selectedTabColor: '#333',
                        fontSize: 6
                    }
                }
            }
        }]
    }
});`

**Comment by Ibrahim-GHub** [comment]
@guyca Any suggestions would be great i am migrating from v1 to v2 and this is crucial for me mate

**Comment by Ibrahim-GHub** [comment]
Hi i appreciate you guys being really busy and taking out of your time to respond but i have a project that's already on play store and there is a critical update that i need to push and this issue is a real road block for me. I would just appreciate if you just point me to what might be causing the issue and i will try to patch it my self until you make a proper fix in your next update.

**Comment by guyca** [comment]
Hey there, I'll look into this issue asap.

**Comment by ReggaePanda** [comment]
https://medium.com/@dooboolab/types-of-navigation-in-react-navigation-v2-bce6d24d94ec#9c33
https://github.com/react-navigation/react-navigation/blob/334be6021a45547c29220ab559807354218fbfd5/examples/NavigationPlayground/js/StacksOverTopTabs.js#L91

i found this. i think there is now an other way to make top tabs

**Comment by ReggaePanda** [comment]
is there also a plan to add topTabs for iOS? @guyca

**Comment by shub-singh-mail** [comment]
I can't get topTabs to work in Android or IOS !! 
In Android, I can't see the tabs but they scroll and in IOS, app crashes after few minutes!

**Comment by jmcartlamy** [comment]
I tried to downgrade to react-native-navigation@2.0.2459 as @the-friyia, and the top tabs still does not appear. Maybe it's because of my react-native version.

However, if you see https://github.com/wix/react-native-navigation/issues/4357, there is a workaround to get topTabs working on Android: 
```
-        topBar.setHeight(options.height.get(UiUtils.getTopBarHeightDp(activity)));
+        topBar.setHeight(options.height.get(LayoutParams.WRAP_CONTENT));
```
line 169 in the file `lib/android/app/src/main/java/com/reactnativenavigation/presentation/StackPresenter.java`

**Comment by hufkens** [comment]
I just started a new project and I also can't see the topTabs on Android and on iOS it crashes. Any idea how to solve this? I can't downgrade, and we really need the topBar and bottomBar for Android/iOS.

**Comment by berkedel** [comment]
@jmcartlamy I tried your solution and it worked. The remaining problem is when I invoke `Navigation.push(..)` to go to another screen, the app do nothing. Any solution on this?

**Comment by codoffer** [comment]
It is buggy and not working anymore. There is no proper documentation for this. I am getting same result and crashing on click. I want to use topTab with sideMenu.

react : 16.6.3
react-native : 0.58.5
react-native-navigation : ^2.12.0

**Comment by 8BallBomBom** [comment]
Seems even with the latest versions the top tabs don't show.
You can set a height of like 100 on the top bar though which then makes the tabs show.
But then you have another issue which is not being able to style the top tabs or at least i haven't been able to find a way to style them as of yet.

**Comment by animeshchat** [comment]
Is this issue resolved? If yes, is there any documentation that I can follow to setup top tabs within bottom tab navigation?

**Comment by animeshchat** [comment]
I got topTabs working within one of the screens of bottomTabs. Note that the topBar needs to be given a height of 100. Configuration below.

Still trying to figure out how to -
1) style it 
2) dynamically add tabs

![Screenshot from 2019-04-27 12-06-36](https://user-images.githubusercontent.com/22907273/56845846-03ad4f80-68e5-11e9-8b33-1e72b98cafc3.png)


root: {
    bottomTabs: {
      id: 'BottomTabsId',
      children: [
        {
          stack: { // Each `tab` must be in a separate stack
            children: [
              {
                topTabs: {
                  children: [
                    {
                      component: {
                        id: 'Home',
                        name: 'app.HomeScreen',
                        options: {
                          topTab: {
                            title: 'Tab 1',
                          },
                        },
                      },
                    },
                    {
                      component: {
                        id: 'Home2',
                        name: 'app.SettingsScreen',
                        options: {
                          topTab: {
                            title: 'Tab 2',
                          },
                        },
                      },
                    },
                  ],
                },
              },
            ],
            options: {
              topBar: {
                title: {
                  text: 'Home',
                },
                height: 100,
              },
              bottomTab: {
                text: 'Home',
                fontSize: 12,
                icon: homeIcon 
              }
            }
          }
        },
        {
          stack: {
            children: [
              {
                component: {
                  id: 'Profile',
                  name: 'app.ProfileScreen',
                  options: {
                    topBar: {
                      title: {
                        text: 'Profile'
                      },
                      rightButtons: [
                        {
                          id: 'Settings',
                          icon: settingsIcon,
                          color: 'black'
                        }
                      ]
                    }
                  }
                }
              }
            ],
            options: {
              bottomTab: {
                text: 'Profile',
                fontSize: 12,
                icon: profileIcon
              }
            }
          }
        }
      ]  
    }
  }

**Comment by syedabuthahirm** [comment]
If you want stack topTabs try this one

```js

  Navigation.setRoot({
    root: {
      stack: {
        options: {
          topBar: {
            title: {
              text: "Message",
              fontSize: 22
            },
            height: 100,
            backgroundColor: 'green'
          },
          topTabs: {
            selectedTabColor: "#12766b",
            unselectedTabColor: "red",
            fontSize: 6,
          }
        },
        children: [
          {
            topTabs: {
              children: [
                {
                  component: {
                    name: "SCREENS.CHATS",
                    options: {
                      topTab: {
                        title: "CHATS"
                      }
                    }
                  }
                },
                {
                  component: {
                    name: "SCREENS.STATUS",
                    options: {
                      topTab: {
                        title: "STATUS"
                      }
                    }
                  }
                },
                {
                  component: {
                    name: "SCREENS.CALLS",
                    options: {
                      topTab: {
                        title: "CALLS"
                      }
                    }
                  }
                }
              ]
            }
          }
        ]
      }
    }
  });

```

**Comment by muhammadsr** [comment]
This is still not working for me

**Comment by syedabuthahirm** [comment]
Did you checked with current version of RNN 2.19.0 and RN 0.59.8?

**Comment by Findiglay** [comment]
Can anyone tell me what is the current status of topTabs in this project? Following the examples provided here haven't been able to get them to work and there is little mention of the feature in the documentation. The comment referenced above from the v3 MR suggests the topTabs should still be working, beyond some deprecated features.

**Comment by hariDasu** [comment]
+1 badly need documentation for this. @syedabuthahirm code works, but I do not want to setRoot in my app, I want to create tabs dynamically for a particular screen within a navigation stack embedded in one tab of the parent tab bar controller

**Comment by hariDasu** [comment]
```
Navigation.push(componentId, {
      topTabs: {
        children: [
          {
            component: {
              name: "Buildings",
              options: {
                topTab: {
                  title: "Buildings"
                }
              }
            }
          },
          {
            component: {
              name: "Documents",
              options: {
                topTab: {
                  title: "DOCS"
                }
              }
            }
          },
          {
            component: {
              name: "Items",
              options: {
                topTab: {
                  title: "ITEMS"
                }
              }
            }
          }
        ]
      }
```

if you want to push a nested TopTab set of components (screens) within a bottom tab view

**Comment by hariDasu** [comment]
any way to disable horizontal scrolling between tabs?

**Comment by clamiax** [comment]
Just want to point out that issue is still there with RNN 4.3.0 (RN 0.61.5). None of the suggested workaround works and in the best case I can swipe screen sideways but the tab names never appears.

For instance this is what I do:
```
const tabs  = [
        {id:"t1",name:"Tab 1",com:"Screen1",icon:require("./my-icon.png")},
        {id:"t2",name:"Tab 2",com:"Screen2",icon:require("./my-icon.png")},
];

Navigation.setRoot({root:{
        topTabs: {
                children: tabs.map(t => {
                        return {
                                stack: {
                                        children: [{
                                                component: {
                                                        id: t.id,
                                                        name: t.com,
                                                        options: {
                                                                topTab: {
                                                                        text: t.name,
                                                                        icon: t.icon
                                                                }
                                                        }
                                                }
                                        }]
                                }
                        }
                })
        },
}});
```

I only checked on Android, not sure about iOS.

**Comment by mrarlloyd** [comment]
+1

**Comment by rat-moonshine** [comment]
RNN can you please land with some fix on this? Toptabs is all broken! Or if it is not, please suggest how to use it on stack.

R: 16.11.0
RN: 0.62.2
RNN: 6.4.0

Thanks!

**Comment by ifier** [comment]
Can we have Tabs? Can't apply them for iOS :( Do we have some instructions?
