### ISSUE TITLE
V1 Docs?

### ISSUE THREAD

**Issue by basudz** [wix/react-native-navigation#4488]
Where are the v1 docs? I can't seem to get to them and am working on an existing project with v1. Am new to the library so the docs would be very helpful.

**Comment by ItsNoHax** [comment]
You should check the docs folder inside the V1 branch.

**Comment by basudz** [comment]
Thanks, I'll take a look.

**Comment by jdegger** [comment]
We published it through gh-pages https://x-guard.github.io/react-native-navigation
