### ISSUE TITLE
[v1] Tabs text space issue

### ISSUE THREAD

**Issue by ivan133** [wix/react-native-navigation#4489]
### Issue Description

I have an issue 
https://gyazo.com/d7153b37e9f2c9e4c2a97d7b6017d9ef

When I move to a component that has:

```
  static navigatorStyle = {
    tabBarHidden: true,
    navBarHidden: false
  }
```

Here is the tabs before 

![simulator screen shot - iphone 6 plus - 2018-12-23 at 13 37 35](https://user-images.githubusercontent.com/4018236/50382833-186ca300-06b9-11e9-95e8-77fcdb19764f.png)

Here is after I click "Push Screen" and go back

![simulator screen shot - iphone 6 plus - 2018-12-23 at 13 37 39](https://user-images.githubusercontent.com/4018236/50382841-3508db00-06b9-11e9-8b2a-b979bd6d3de9.png)

When I return back I see tabs visually jumping + text size becomes significantly smaller 

### Steps to Reproduce / Code Snippets / Screenshots

You can run this test app:
https://github.com/ivan133/react-native-navigation-tab-issue 

It's simple app created based on react-native-navigation example 

---
### Environment
* React Native Navigation version: 1.1.493
* React Native version: 0.53.0"
* Platform(s) (iOS, Android, or both?): iOS only on adroid it works smooth
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by ivan133** [comment]
I don't agree, looks like a bug for me 
But ok I'll create SO question

**Comment by ivan133** [comment]
https://stackoverflow.com/questions/53904234/wix-react-native-navigation-v1-tabs-text-space-issue

**Comment by danielgreane** [comment]
Am able to reproduce the bug this end, it seems to be limited to older iOS versions and devices. 
Initial 

@ivan133 did you have any luck solving this?
