### ISSUE TITLE
Set tab badge not working for me

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#449]
### Issue Description

Tab badge not working for me, I have called 

        this.props.navigator.setTabBadge({
          tabIndex: 2, 
          badge: 17 
        });
and nothing changed on tab number 3

(https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 2.0exp
* React Native version: 0.35
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): simulator, Platform 6, API 23

**Comment by Jaafar-abusair** [comment]
Is there any specific place to invoke this?

**Comment by Jaafar-abusair** [comment]
Any update?

**Comment by Jaafar-abusair** [comment]
Well it worked, but i have to set the number inside the page, after the navigator loaded, can't set it in the same page that construct the startTabBasedApp, you can close the ticket

**Comment by guyca** [comment]
Glad to hear you sorted it out. Will be fixed in the next version.
