### ISSUE TITLE
Task :react-native-navigation:compileReactNative57_5DebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by pakyo-pan** [wix/react-native-navigation#4494]
cd ./android && ./gradlew app:assembleDebug && ./gradlew installDebug

![image](https://user-images.githubusercontent.com/13342613/50389082-ec582d00-075f-11e9-91f1-2d1e145bf56a.png)

---
### Environment
* React Native Navigation version: 2.3.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by pakyo-pan** [comment]
https://github.com/wix/react-native-navigation/issues/4498#issue-393908013

**Comment by codoffer** [comment]
Facing same issue with
react: 16.8.3
react-native: 0.59.0
react-native-navigation: ^2.13.1

I have tried to google and find stack, but there is nothing regard new version.

**Comment by krookten14** [comment]
Is this resolved?? I have the same issue and I don't want to downgrade my react-native

**Comment by stevesuyao** [comment]
my solution: https://github.com/wix/react-native-navigation/issues/4498#issuecomment-478746383
