### ISSUE TITLE
V2 - 2.3.0 bottomTabs bug 

### ISSUE THREAD

**Issue by Amenocy** [wix/react-native-navigation#4498]
there is bug in new commit in 2.3.0 bottomTabs
```
initmobile\node_modules\react-native-navigation\lib\android\app\src\main\java\com\reactnativenavigation\views\BottomTabs.java:33: error: method does not override or implement a method from a supertype
    @Override
    ^
\initmobile\node_modules\react-native-navigation\lib\android\app\src\main\java\com\reactnativenavigation\views\BottomTabs.java:48: error: createItems() has private access in AHBottomNavigation
        super.createItems();
             ^
\initmobile\node_modules\react-native-navigation\lib\android\app\src\main\java\com\reactnativenavigation\viewcontrollers\bottomtabs\BottomTabsController.java:150: error: no suitable constructor found for AHBottomNavigationItem(String,Drawable,String)
            return new AHBottomNavigationItem(
                   ^
    constructor AHBottomNavigationItem.AHBottomNavigationItem(String,int,int) is not applicable
      (argument mismatch; Drawable cannot be converted to int)
    constructor AHBottomNavigationItem.AHBottomNavigationItem(int,int,int) is not applicable
      (argument mismatch; String cannot be converted to int)
    constructor AHBottomNavigationItem.AHBottomNavigationItem(String,Drawable,int) is not applicable
      (argument mismatch; String cannot be converted to int)
Note: C:\Users\Amin\Desktop\gittick\initmobile\node_modules\react-native-navigation\lib\android\app\src\reactNative57_5\java\com\reactnativenavigation\react\SyncUiImplementation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 errors
```

i should mention that, it works by returning to 2.2.5

**Comment by guyca** [comment]
Hey, you probably didn't recompile after npm installing.

**Comment by GuillermoGuevara** [comment]
same issue!!!:

> Task :react-native-navigation:compileReactNative57DebugJavaWithJavac FAILED
/Users/guillermo/Documents/projects/react_native/njoyv3/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativen
avigation/views/BottomTabs.java:33: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/guillermo/Documents/projects/react_native/njoyv3/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/views/BottomTabs.java:48: error: createItems() has private access in AHBottomNavigation
        super.createItems();
             ^
/Users/guillermo/Documents/projects/react_native/njoyv3/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java:150: error: no suitable constructor found for AHBottomNavigationItem(String,Drawable,String)
            return new AHBottomNavigationItem(
                   ^
    constructor AHBottomNavigationItem.AHBottomNavigationItem(String,int,int) is not applicable
      (argument mismatch; Drawable cannot be converted to int)
    constructor AHBottomNavigationItem.AHBottomNavigationItem(int,int,int) is not applicable
      (argument mismatch; String cannot be converted to int)
    constructor AHBottomNavigationItem.AHBottomNavigationItem(String,Drawable,int) is not applicable
      (argument mismatch; String cannot be converted to int)
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 errors





"react-native": "^0.57.8",
"react-native-navigation": "^2.5.0",

**Comment by wsliaw** [comment]
Hi @guyca , what does recompile mean? I tried to do a clean build but still failed, thanks

**Comment by bensont1** [comment]
This is also happening to me on latest `2.6.0` version. I've cleaned and rebuilt my Android project multiple times, no luck.

**Comment by janroures** [comment]
any luck on this? same issue on version 2.7. iOS works well.

**Comment by eddysapata** [comment]
Nope..
Sadly Moved to react navigation

**Comment by wsliaw** [comment]
check whether ```com.github.wix-playground:ahbottomnavigation```'s version under  ```node_modules/react-native-navigation/lib/android/app/build.gradle``` is ```2.4.6```?

**Comment by janroures** [comment]
it is 2.4.8. should that matter?

**Comment by wsliaw** [comment]
should be okay

**Comment by janroures** [comment]
have you faced the issue before?

**Comment by janroures** [comment]
oh okay. I'm facing the issue with 2.4.8 :/

**Comment by amol-c** [comment]
Facing the same issue here.

**Comment by janroures** [comment]
which version of com.github.wix-playground:ahbottomnavigation's under node_modules/react-native-navigation/lib/android/app/build.gradle are you using?

**Comment by amol-c** [comment]
Yea. i updated to the latest release `2.7.1-snapshot.159` and it worked.

👍

**Comment by obshksw** [comment]
Same problem here on 2.7.1 and also on 2.7.1-snapshot.160. Works fine on 2.5.1!

react-native version is 0.57.8

**Comment by amol-c** [comment]
There are few cache's going on here. You may have to clean your gradle cache too.

`rm -rf ~/.gradle/cache `

**Comment by sja1n** [comment]
still facing the same issue with `2.4.9` version and I just created a fresh app from cli
React native: 0.58.6
react native navigation: 2.13.1

any updates on this ?

**Comment by alexxsanchezm** [comment]
I found i missed to add jitpack repository. Add this tho your project level build.gradle and hit sync again.
```
allprojects {
    repositories {
        // <other repos>
        maven {
            url 'https://jitpack.io'
        }
    }
}
```

**Comment by stevesuyao** [comment]
upgrade Android Gradle plugin to 3.3.2 works for me: https://developer.android.com/studio/releases/gradle-plugin

in `anroid/build.gradle`, 
~~~
dependencies {
   classpath 'com.android.tools.build:gradle: 3.3.2'
}
~~~

RN: 0.59.3
react-native-navigation: 2.16.0
