### ISSUE TITLE
[boilerplate] React-Native-Navigation V2 with Redux & Saga

### ISSUE THREAD

**Issue by wagng** [wix/react-native-navigation#4499]
Hey guys,

I have integrated RNN v2.0 into my react-native boilerplate.
It also includes a cool redux-saga structure.
I will add more and more components and new modules in my free time.

Boilerplate: https://github.com/wagng/react-native-navigation-redux-starter-kit.git

Enjoy it and feel free to open any issues for advanced features!
Also thanks a lot for the great library 👍

**Comment by minhx3** [comment]
Love you

**Comment by guyca** [comment]
Great job! Added it to the [starter kits](https://wix.github.io/react-native-navigation/#/docs/showcases) section in the docs 👍

**Comment by wagng** [comment]
Thanks, @guyca !
