### ISSUE TITLE
Set tabs to top instead of bottom in Android in Navigation.startTabBasedApp

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#450]
### Issue Description

How to set tabs to top instead of bottom in Android in Navigation.startTabBasedApp
(https://github.com/wix/react-native-navigation/issues/197)]

IT's a question

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
Hey @Jaafar-abusair 
For now, You can refer to the [old-example-redux](https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js#L106) for implementation example. That api is available only on Android, but will soon make it into iOS.

**Comment by Jaafar-abusair** [comment]
Are you saying I have to use Navigation.startSingleScreenApp, with TopTabs property?

**Comment by guyca** [comment]
Yes, because top tabs is a property of screen.
