### ISSUE TITLE
How to disable android hardware back button with stack?

### ISSUE THREAD

**Issue by dopey2** [wix/react-native-navigation#4503]
### Issue Description

Hello, I'm using a stack in my app and whenever I press the back hardware button on android the app pop to the previous screen. 

My issue is that i cannot override this behaviour, I have a BackHandler and a listener which is called whenever i press the hardware back button, but even if i have my own implementation the pop is still happening!

Is there a way to disable the hardware back button ? 

---
### Environment
* React Native Navigation version: 2.2.5
* React Native version: 57.2
* Android

**Comment by ItsNoHax** [comment]
Try the following:

```
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
  }

  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
  }

  onBackPress = () => {
    return true; <---- make sure you return true.
  }
```

**Comment by dopey2** [comment]
@ItsNoHax, I forgot to mention it, but thats what I do and it still doesn't work

**Comment by dopey2** [comment]
@ItsNoHax, i just solve this, the problem was not the return statement from onBackPress. The problem was that my listeners was never removed. Indeed i had multiple listeners for each of my screens and i was removing them componentWillUnmount lifecycle method. But since I was using a stack the previous screens were never unmount so I had to remove my listener inside componentDidDisappear.

**Comment by manojalwisnz** [comment]
@ItsNoHax , this is awesome.

**Comment by Hassan709** [comment]
n

**Comment by Hassan709** [comment]
componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
  }

  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
  }

  onBackPress = () => {
    return true; <---- make sure you return true.
  }

**Comment by HappyCodingLover** [comment]
I want to disable device back button popping, in only one screen
Any idea?

**Comment by mateioprea** [comment]
@HappyCodingLover https://wix.github.io/react-native-navigation/api/options-backButton

**Comment by yushanwebdev** [comment]
@HappyCodingLover https://wix.github.io/react-native-navigation/docs/customBackNavigation/#handling-the-hardware-back-button
