### ISSUE TITLE
[V2][iOS] title and subtitle and styles from sideMenu

### ISSUE THREAD

**Issue by igor-nm** [wix/react-native-navigation#4509]
### Problems with sideMenu

When I use the sideMenu the title and subtitle putted don't appear in iOS, also the styles and effects not work as for exemple animationType, openGesture, shouldStretchDrawer at least this don't had effect.

### Steps to Reproduce / Code Snippets / Screenshots
Style in default options
```js
sideMenu:
{
	left:
	{
		width: 230,
		animationType: 'parallax',
		shouldStretchDrawer: false
	},
	openGestureMode: 'bezel'
}
```

SideMenu
```js
Navigation.setStackRoot(componentId, 
{
	sideMenu:
	{
		left:
		{
			component:
			{
				name: 'app.Drawer'
			},
		},
		center:
		{
			stack:
			{
				id: 'MAIN',
				children:
				[{
					component:
					{
						name: 'app.Main',
						options:
						{
							topBar:
							{
								title: { text: 'Title' },
								subtitle: { text: 'subtilte' }
							}
						}
					}
				}],
			}
		}
	}
});
```
iOS print's
![img_0054](https://user-images.githubusercontent.com/20232832/50481637-cdf56a00-09c9-11e9-9b80-f055efa0e68d.PNG) 
![img_0055](https://user-images.githubusercontent.com/20232832/50481638-cdf56a00-09c9-11e9-879f-e27bd91fd8ca.PNG)
Android print's
![screenshot_20181227-111033](https://user-images.githubusercontent.com/20232832/50481639-cdf56a00-09c9-11e9-909b-ad908a076d7f.png)
![screenshot_20181227-111304](https://user-images.githubusercontent.com/20232832/50481641-cdf56a00-09c9-11e9-94b7-03ab02433dab.png)

---
### Environment
* React Native Navigation version: v2.2
* React Native version: v57.7
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): device | iOS version 12.1.1 | Debug

**Comment by cjroth** [comment]
Try this:

```
        Navigation.setStackRoot('MAIN', {
            component:
            {
                name: 'app.Main',
            }
        })
        Navigation.mergeOptions(this.props.componentId, {
            sideMenu: {
                left: {
                    visible: false,
                },
            },
        })
```

**Comment by igor-nm** [comment]
Hello @cjroth unfortunately this it is don't work.

**Comment by hadnet** [comment]
@igor-nm did you resolve this problem? I'm using RNN 2.12.0 and it seems that animationType, openGestureMode doesn't work or make any effect on iOS.
