### ISSUE TITLE
Modal stays on after calling dismissModal

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#451]
### Issue Description

I am showing a modal dialog box in my app to show the progress of an action which I dismiss once the action is complete but the modal screen stays on. I see that the modal screen is slid down hinting that an effort was made to dismiss the modal but the modal screen continues to appear after the slide-down animation completes. I have attached a zip file containing a small video showing the symptom. The problem occurs on both iOS and Android for me.

I am using following calls to show and dismiss the modal. I have tried both `dismissModal` and `dismissAllModals` with the same result.

```js
    this.props.navigator.showModal({
      screen: "MessageModalScreen",
      title: "Authenticating",
      passProps: {message: 'Authenticating with server'}
    })

    this.props.navigator.dismissModal()
```

[Modal_Bug.zip](https://github.com/wix/react-native-navigation/files/597091/Modal_Bug.zip)

If you have an idea what may be causing it or any workaround, please let me know.

### Environment
* React Native Navigation version: 2.0.0.experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug

**Comment by guyca** [comment]
Hey @varungupta85 Is this reproducible in the example project?

**Comment by varungupta85** [comment]
Hi @guyca , I will check if I can reproduce it in the example project and get back to you.

**Comment by guyca** [comment]
Because you're experiencing this issue on both platforms, and we didn't encounter this issue, I have a feeling it's caused by you logic and not related to RNN.

**Comment by varungupta85** [comment]
Closing this for now. Will reopen if I am able to reproduce it in the example project.
