### ISSUE TITLE
Navigation.constants() get the same value

### ISSUE THREAD

**Issue by morelearn1990** [wix/react-native-navigation#4514]
### Issue Description

When i first ran Navigation.constants() in a page without tabBar and bottomTab, i get 
```
{
bottomTabsHeight:0, 
topBarHeight,:0
}
```
then  i ran Navigation.constants() the second time  in a page with tabBar and bottomTab,i also get 
```
{
bottomTabsHeight:0, 
topBarHeight,:0
}
```
After many tests，i find this function get same value as the first time.
notice: i just test on iphone6 and IOS12,other Environment is unknown.

### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.57.5
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): iphone6,debug

**Comment by henrikra** [comment]
It is called `constants` so it means their values never change 🤷‍♂️

**Comment by morelearn1990** [comment]
Why topBarHeight and bottomTabsHeight is zero .QAQ

**Comment by morelearn1990** [comment]
#4190
