### ISSUE TITLE
Get current screen from navigator

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#452]
### Issue Description

Is it possible to get the current screen from navigator such that I can perform different kinds of actions depending on the screen user is currently on. For e.g., for user profile screen, an avatar is shown along with the user name. If there is an image for a user, the image is shown and if there is no image, a default avatar is shown. When a user clicks on the avatar, if there is an image, the image is shown on the full screen from where he can change the image. If there is no image, he is directly asked if he wants to change the image. On selecting the image, I want to pop out one screen if there was previously an image for the user so that the user ends up on the profile screen after the image is uploaded. If there was no image to begin with, then I don't want to pop because the user would already be on the profile screen. If I was able to get the current screen from the navigator, then I can check the title of the current screen and then pop based on which screen the user is currently on. I have similar needs at a couple of more places where I need to perform different kinds of action based on the current screen.

I checked the navigator API and there is doesn't seem to be a method that returns this information. In the `react-native` navigator API, there is an API to get the current routes from which I can get the topmost route to know the current route which I have been using till now.

### Environment
* React Native Navigation version: 2.0.0.experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug

**Comment by guyca** [comment]
Hey @varungupta85 
Thanks for the detailed description. Screen lifecycle (screenDidAppear, ScreenDidDissappear) callbacks are in the works and will be added soon.

Also, I think we should add few methods to our navigator that will also might help
* replacePreviousAndPop
* replacePrevious
* replaceAtIndex
etc.

**Comment by varungupta85** [comment]
@guyca, thanks for the response. I have a quick question regarding the scope of the lifecycle callbacks and will open a new issue if you think it would be useful to have the discussion in a separate issue. Currently, I am migrating my app from using the `ex-navigator` navigation package which internally uses the `react-native` `Navigator` for navigation. I used to have a top level `App` component which would be root component mounted in the `index.ios.js`. In the `componentWillUpdate` and other creation lifecycle methods of the `App`, I set up all the event handlers for notifications, app state change, connectivity change etc. I remove all these event handlers in the `componentWillUnmount` method. Now with `react-native-navigation` package, there is no such root component. I guess with single screen app, there is still the root level `screen` where I can perform all such operations but with tab based app, I am not sure where to hook and unhook these event handlers etc. I can perform these operations in one of the tabs but I am not sure if that would be the right way of doing it.

Is there any recommended way of doing these things with tab based application?

Thanks a lot for your quick and useful responses.

**Comment by guyca** [comment]
@varungupta85 We wired that logic to the main screen of our app.
We dispatch an action when that screen is mounted and do most initialisations form there.

**Comment by varungupta85** [comment]
@guyca thanks. Just to confirm that I understood it clearly, if there a tab based application with more than one tab, you suggest to perform the initializations when the first tab which is also the default tab for the app is mounted and you perform the clean up when the first tab is unmounted. I guess I was a little confused about where to perform the cleanup. For e.g., if the app is in the background for a while, the OS will stop the app at which point, I want to perform the cleanup and when the app is foregrounded again, the app will be restarted at which point I want to perform the initializations again. I was thinking that if the user was on tab 2 when the app is sent to the background and when the user foregrounds the app again after some time, will the `componentWillMount` and other lifecycle methods for the first screen be called again since the user is on tab 2. But from the logs, I have realized that all the tabs for the tab based application are mounted and unmounted when the app start and stops.

**Comment by guyca** [comment]
@varungupta85 Yes thats correct, all tabs are mounted at startup and unmounted when going to background.
You might also rely on [AppState](https://facebook.github.io/react-native/docs/appstate.html) for cleanup operations.
