### ISSUE TITLE
[V2] Push native horizontal animation and back iOS

### ISSUE THREAD

**Issue by voidstarfire** [wix/react-native-navigation#4522]
I'm trying to understand the point of V2.
I decided to use this library over 2 years ago and I've used V1 in around 11 RN projects since.

I chose this library because it gave me a native 'look and feel' with iOS back and the native animation timings over the JS based libraries at the time. It was super simple to implement and was a lot better than the garbage facebook official 'react-navigation' that still to this day doesn't support reset animations...

Now I don't use any of the toolbars, tabs or titles because it's better to implement them yourself I've found.

So my issue..

Simple push animations to work horizontally with swipe back on iOS. The following code comes up from the bottom. For the life of me I cannot get this to work, the solutions requires using some custom transitions (very bad) which lose the native feel and iOS slide back doesn't work. Before this was as simple as putting the option 'slide-horizontal' in. What now? There's nothing in the docs apart from the custom confusion.

```
Navigation.push(currentComponentId, {
        component: {
            name: ComponentNames.ScreenCreateUsername,
        },
});
```

The solutions with custom transitions work very poorly with jumps and no native feel what-so-ever. Am I true in saying that you guys have destroyed react-native-navigation with V2? Also, where is the version 1 docs they've been taken down... since I will go back to use that if there's no simple solution for this.

**Comment by angelos3lex** [comment]
@voidstarfire have you managed to push-pull with horizontal transition? If yes, for both platforms?

**Comment by voidstarfire** [comment]
Cannot get it too work natively so I gave up. Going back to V1 it has more features that make RN look more native.
