### ISSUE TITLE
RNN should propose a NavigationButton component?

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#4523]
### Issue Description

We all know about the double tap issues we can have with buttons triggering a nav command (push/pop/whetever...).

https://github.com/wix/react-native-navigation/issues/271
https://github.com/wix/react-native-navigation/issues/2655
https://github.com/wix/react-native-navigation/pull/255
etc...

It seems to me that we have in the RNN (v2) API what is needed to make a wrapper component around buttons which would automatically disable the button the first time it's tapped and would re-enable it once the right [command completed listener](https://wix.github.io/react-native-navigation/#/docs/events?id=registercommandcompletedlistener) is raised...

This seems to me generic enough to include it within the RNN lib, don't you think?

I could send a PR for that but I'm sure many already have dealt with this problem and probably have some nice solution they could share...

What API do you think would be best? A HOC or a component?

### Steps to Reproduce / Code Snippets / Screenshots

n/a

---
### Environment
* React Native Navigation version: any
* React Native version: any
* Platform(s) (iOS, Android, or both?): any
* Device info (Simulator/Device? OS version? Debug/Release?): any

**Comment by zabojad** [comment]
I'm trying to make my own `NavigationButton` that would behave as described in my original post.

One problem i'm facing is that we cannot get the command id when calling the nav command:

`Navigation.push(/* ... */).then((v)->console.log(v))` => will output the component Id (useless here?)

While listening for command completion, I receive the command id:
`Navigation.events().registerCommandCompletedListener(console.log);` <= will output something like `'navCompleted', { completionTime: 1546274244072, commandId: 'push18' }`

It would be preferable that commands promise would resolve with the command id so that we can actually know the command attached to the button completed...

**Comment by zabojad** [comment]
Ended up using `lodash.debounce`...

**Comment by stokesbga** [comment]
No doubt, throttle needs to be PR'd. I'm guessing wix does not want to add lodash to their repo though.

**Comment by stokesbga** [comment]
@zabojad why debounce over throttle?

**Comment by stokesbga** [comment]
So I tried debounce and throttle, but didn't like the results. Nothing was 100% foolproof. I ended up changing the main export to be the Navigation class rather than the instance, and then added this wrapper class: 
```
import { Navigation } from "@outfix/react-native-navigation";
const THROTTLED_EVENTS = [
  "showModal",
  "dismissModal",
  "dismissAllModals",
  "push",
  "pop",
  "popTo",
  "popToRoot",
  "setStackRoot",
  "showOverlay",
  "dismissOverlay"
];
let eventQueue = [];

class NavigationWrapper extends Navigation {
  constructor() {
    super();
  }

  _throttleEvent = (event, ...params) => {
    if (eventQueue.indexOf(event) === -1) {
      eventQueue.unshift(event);
      super[event](...params);
    }
  };

  push = (...params) => {
    this._throttleEvent("push", ...params);
  };
  pop = (...params) => {
    this._throttleEvent("pop", ...params);
  };
  popTo = (...params) => {
    this._throttleEvent("popTo", ...params);
  };
  popToRoot = (...params) => {
    this._throttleEvent("popToRoot", ...params);
  };
  showModal = (...params) => {
    this._throttleEvent("showModal", ...params);
  };
  dismissModal = (...params) => {
    this._throttleEvent("dismissModal", ...params);
  };
  dismissAllModals = (...params) => {
    this._throttleEvent("dismissAllModals", ...params);
  };
  setStackRoot = (...params) => {
    this._throttleEvent("setStackRoot", ...params);
  };
  showOverlay = (...params) => {
    this._throttleEvent("showOverlay", ...params);
  };
  dismissOverlay = (...params) => {
    this._throttleEvent("dismissOverlay", ...params);
  };
}

const NavigationObj = new NavigationWrapper();
NavigationObj.events().registerCommandCompletedListener(({ commandId }) => {
  if (THROTTLED_EVENTS.indexOf(commandId) > -1) {
    eventQueue = eventQueue.filter(e => e !== commandId);
    console.log("Navigation queue (completed) is: ", commandId, eventQueue);
  }
});

export default NavigationObj;

```

**Comment by markhomoki** [comment]
@stokesbga Are you still using the code above in production or is there a better way doing it? Thanks.
