### ISSUE TITLE
Sidemenu width counter-intuitive

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#4527]
### Issue Description

Related issues:
#3977 

Currently the way the Sidemenu width works is very counter intuitive. It always uses the full width of your device for the Sidemenu component regardless of the width set.

### Steps to Reproduce / Code Snippets / Screenshots

For example: If I set the SideMenu's width as following:

```
sideMenu: {
  left: {
   width: 200,
  }
 }
```

and my SideMenu screen is a empty screen with Text centered in the middle:
```
const styles = {
  root: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5fcff'
  }
};
```
```
      <View style={styles.root}>
        <Text>
            I am centered.
        </Text>
        <Text>
            Width: {width}
        </Text>
      </View>
```

The following happens:
![simulator screen shot - iphone xr - 2019-01-02 at 10 52 17](https://user-images.githubusercontent.com/4223434/50587356-e22fe000-0e7d-11e9-8b9a-72342f0f6df4.png)

---
### Environment
* React Native Navigation version: Latest
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by ItsNoHax** [comment]
Hey @yogevbd, I can confirm your changes work when setting the width. 
But when you use the default width, the previous behaviour is still happening.

**Comment by doneitas** [comment]
I am still facing it on 6.4.0 😕
