### ISSUE TITLE
statusBarTextColorScheme light not working?

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#453]
Hey there, 
this is how i set `react-native-navigation`:

```javascript
const navigatorStyle = {
  statusBarColor: 'white',
  statusBarTextColorScheme: 'light',
  navBarBackgroundColor: Colors.darkColor,
  navBarTextColor: 'white',
  navBarButtonColor: 'white',
};

registerScreens(store, Provider);
Navigation.startSingleScreenApp({
  screen: {
    screen: ScheneKeys.MAIN,
    title: 'Test',
    navigatorStyle,
  }
  },
});
```

Even though the `statusBarTextColorScheme` is `light` the status bar text is still black.
I had to use 

```javascript
<StatusBar
    barStyle="light-content"
/>
```
to make the status bar text white again. Am I doing something wrong?

Thank you.

---
### Environment
* React Native Navigation version: `next`
* React Native version: `0.37.0`
* Platform(s) (iOS, Android, or both?): `iOS`
* Device info (Simulator/Device? OS version? Debug/Release?): `Simulator v10.0 iPhone 7 iOS 10.1`

**Comment by messense** [comment]
Ran into the same bug sometimes.

**Comment by TylerLH** [comment]
I've been running into this issue on iOS as well, haven't tried Android yet. The initial navigatorStyle I use when starting the app works, but doesn't persist when I push a new screen onto the stack. Even when I add `static navigatorStyle = {...}` to a Screen, the pushed screen doesn't change the statusBarTextColorScheme. 

Oddly enough, if I re-save the file and wait for hot-reloading, the statusBarTextColorScheme does change to light.

**Comment by razvan-paul** [comment]
+1

**Comment by qimingfang** [comment]
+1

**Comment by florianbepunkt** [comment]
+1 same here

**Comment by florianbepunkt** [comment]
statusBarHidden property also takes no effect

**Comment by jaggerwang** [comment]
For me, it's worked on iOS, but not Android.

**Comment by IharKrasnik** [comment]
+1

**Comment by markhaasjes** [comment]
+1

**Comment by markhaasjes** [comment]
Check out the documentation, this works for me:
https://github.com/wix/react-native-navigation/wiki/Styling-the-navigator

**Comment by TylerLH** [comment]
I'm fairly certain everyone in this thread has seen and relied on that
documentation. The problem exists either way. For what it's worth, I didn't
have time to fork and try to fix the issue, so I moved on to another
routing solution that has worked very well for my use case.

**Comment by IharKrasnik** [comment]
Light color scheme still not working for me too

**Comment by grundmanise** [comment]
The only solution that works for me is to set:

```
  static navigatorStyle = {
     statusBarTextColorScheme: 'light',
  };
```
in every `Component`.

**Comment by grin** [comment]
You must first set the UIViewControllerBasedStatusBarAppearance to YES in the .plist file, only then the `statusBarTextColorScheme` prop will be picked...

**Comment by yungobiwan** [comment]
@grin 

I'm getting RCTStatusBarManager manager module requires that the UIViewControllerBarStatusAppeareance key in the info.plist is set to NO

Do you know why i'm getting this error?

**Comment by mbardauskas** [comment]
+1

**Comment by yungobiwan** [comment]
I went ahead and commented the nslogs in RCTStatusBarManager but I'm not sure what the implications might be. Will really like to know what's going on under the hood

**Comment by jnsone11** [comment]
If you want one style across the application add these 2 lines to your AppDelegate.m (Xcode)  to 'didFinishLaunchingWithOptions' method.

`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  [[UIApplication sharedApplication] setStatusBarStyle:
   UIStatusBarStyleLightContent];`

**Comment by jpoutrin** [comment]
@grin solution works for me. thanks man!

**Comment by SudoPlz** [comment]
I confirm that after changing `UIViewControllerBasedStatusBarAppearance` to `<false>` 
`statusBarTextColorScheme` is now working.

@yungobiwan The reason you get that error is because you're still using the StatusBar component from react-native.
In order to use statusBarTextColorScheme or statusBarTextColorSchemeSingleScreen in your app you have to totally remove any <StatusBar> components from your code.

Closing that issue, as it's now resolved.

**Comment by leoskyrocker** [comment]
For those getting the error @yungobiwan mentioned:
> RCTStatusBarManager manager module requires that the UIViewControllerBarStatusAppeareance key in the info.plist is set to NO

It is possible to set the key to YES without that error.
Make sure your app is not using StatusBar at all, explicitly or **implicitly** by another libraries' component.
In my case, I installed NativeBase and used its `<Header>` component, which under the hood uses react-native's `<StatusBar>`.

**Comment by otusweb** [comment]
@leoskyrocker DId you find a way to keep using native base and not get this warning? This is getting annoying everytime I run the app it comes up...

**Comment by leoskyrocker** [comment]
@otusweb Yep, should be good if you don't import the `<Header>` component and render it anywhere in your app.

**Comment by ashokkumar88** [comment]
@TylerLH Can u please let me know which routing solution you are using

**Comment by PriyankaAshu** [comment]
@leoskyrocker, Yes, withoue header it's working, But I have to use <Header> then is there are any solution. I am using react-native-base for UI elements/components.

**Comment by PriyankaAshu** [comment]
I got it fixed, I was doing a mistake -> was writing statusbar outside of Header. 
It's working inside the header or content :) yay
