### ISSUE TITLE
[V2] [Android] bottomTabs misaligns after dismissing modal or popping stack.

### ISSUE THREAD

**Issue by PetteriHaro** [wix/react-native-navigation#4530]
### Issue Description

The bottomTabs bar goes half out of screen when dismissing a modal or popping a stack. The problem has something to do with the statusBar, I would assume. 

In Homescreen drawBehind statusBar is set to false and in the modal the drawBehind statusBar and topBar is true.

When dismissing the modal, the bottomTabs gets pushed the statusBars' height below the screen.

This happens only on android! iOS work perfectly fine

![react native navigation bug](https://user-images.githubusercontent.com/33297046/50602281-9e5dca80-0ebf-11e9-87ac-125afe782726.gif)

### Steps to Reproduce / Code Snippets / Screenshots
In App.js:

```js
Navigation.setDefaultOptions({
  bottomTabs: {
    titleDisplayMode: "alwaysHide",
  },
  statusBar: {
    backgroundColor: "white",
    style:"dark"
  }
})

Navigation.setRoot({
  root: {
    bottomTabs: {
      children: [{
	stack: {
          children: [{
	    component: {
	      name: "myapp.HomeScreen"
	    }
	  }],
	  options: {
	    bottomTab: {
	      icon: icons[0],
	    },
	  }
	}
      },
      {
        stack: {
	  children: [{
	    component: {
		name: "myapp.SecondScreen"
	    }
	  }],
	  options: {
	    bottomTab: {
		icon: icons[1],
	    }
	  }
	}
      },
    }
  }
})
```

HomeScreen.js
```js
 static options(passProps) {
    return {
      topBar: {
        title: {
          text: 'Home'
        },
        visible: true,
        drawBehind: "false"
      }
    };
  }
```

ModalScreen.js
```js
 static options(passProps) {
    return {
      topBar: {
        drawBehind: true,
        visible: false,
        animate: false,
      },
      statusBar: {
          drawBehind: true
      }
    };
  }
```

---
### Environment
* React Native Navigation version: 2.2.5
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device

**Comment by LRNZ09** [comment]
This is still an issue and should be reopened.
