### ISSUE TITLE
my android app was crashed  when using the bottomtab  in react native navigation

### ISSUE THREAD

**Issue by harikrishnadvk1991** [wix/react-native-navigation#4533]
i have con figure below like this

    Navigation.setRoot({
        root:{
    sideMenu: {
        id:"RootStack",
        left: {
            component: {
                id: 'SideMenu',
                name: 'reminder.sideMenu',
            }
        },
        center: {
            bottomTabs: {
                id:'bottomTab',
            options: {
                    bottomTabs: {
                            titleDisplayMode: 'alwaysShow',
                            //testID: testIDs.BOTTOM_TABS_ELEMENT,
                            backgroundColor: 'white',
                            currentTabIndex: 0,
                            },
                    },
        children: [
            {
                stack: {
                id: 'BOTTOM_TAB_SCREENS',
                options: {
                            bottomTab:{
                            selectedIconColor: 'green',
                            }
                        },

                children: [{
                component: {
                    name: 'reminder.ContactList',
                    passProps: {
                                text: 'This is tab 1',
                                // myFunction: () => 'Hello from a function!',
                                },
                    options: {
                            bottomTab: {
                                icon:require('../../Images/home1.png'),
                                text:'Home',
                                },
                                // topBar:{
                                //  // visible:true
                                // }
                        },
                    }
                },
                ]
            }
            },

            {
                component: {
                    name: 'reminder.ContactList',
                    options: {
                        bottomTab: {
                            icon: require('../../Images/contact.png'),
                            text:'Contact',
                            selectedIconColor: 'green',
                        }
                    }
                },
            },
            {
                component: {
                    name: 'reminder.FeedBack',
                    options: {
                        bottomTab: {
                            icon: require('../../Images/chatbot.png'),
                            text:'Chatbot',
                            selectedIconColor: 'green',
                        }
                    }
                },
            },
            {
                component: {
                    name: 'reminder.FeedBack',
                    options: {
                        bottomTab: {
                            icon: require('../../Images/feedback.png'),
                            text:'Feedback',
                            selectedIconColor: 'green',

                        }
                    }
                },
            },
        ],
    },
    }
},
}
})
}

this is console

::ffff:127.0.0.1 - - [03/Jan/2019:18:05:40 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 200 - "-" "okhttp/3.11.0"
::ffff:127.0.0.1 - - [03/Jan/2019:18:05:45 +0000] "GET /assets/src/Images/home1.png?platform=android&hash=2582c1a4447e38aba0c211ec4b95ec32 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 8.1.0; vivo 1716 Build/OPM1.171019.011)"
::ffff:127.0.0.1 - - [03/Jan/2019:18:05:45 +0000] "GET /assets/src/Images/contact.png?platform=android&hash=3b443760d8c609dbb14d44a65abfce76 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 8.1.0; vivo 1716 Build/OPM1.171019.011)"
::ffff:127.0.0.1 - - [03/Jan/2019:18:05:45 +0000] "GET /assets/src/Images/chatbot.png?platform=android&hash=6509e08879b2c1684b79f1fa2910ddda HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 8.1.0; vivo 1716 Build/OPM1.171019.011)"
::ffff:127.0.0.1 - - [03/Jan/2019:18:05:45 +0000] "GET /assets/src/Images/feedback.png?platform=android&hash=4cab4efda5ad2dec9601910f9976bc34 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 8.1.0; vivo 1716 Build/OPM1.171019.011)"
::ffff:127.0.0.1 - - [03/Jan/2019:18:05:47 +0000] "GET /assets/src/Images/Rightarrow.png?platform=android&hash=bd3d7534131099f9a9534a3a3b04401a HTTP/1.1" 200 - "-" "okhttp/3.11.0"
::ffff:127.0.0.1 - - [03/Jan/2019:18:05:47 +0000] "GET /assets/src/Images/ImageLogo.png?platform=android&hash=5cc76230d904b460834b27c93e230af4 HTTP/1.1" 200 - "-" "okhttp/3.11.0"
::ffff:127.0.0.1 - - [03/Jan/2019:18:06:04 +0000] "GET /assets/src/screens/Feed/assets/worried.png?platform=android&hash=f0c0ae2dfb4282b07caa2a03883655c8 HTTP/1.1" 200 - "-" "okhttp/3.11.0"
::ffff:127.0.0.1 - - [03/Jan/2019:18:06:04 +0000] "GET /assets/src/screens/Feed/assets/sad.png?platform=android&hash=eb7f2f9a2882b084e8626c91f57cb5ee HTTP/1.1" 200 - "-" "okhttp/3.11.0"
::ffff:127.0.0.1 - - [03/Jan/2019:18:06:04 +0000] "GET /assets/src/screens/Feed/assets/surprised.png?platform=android&hash=f1a2a009d30911b5ed3f7511ebc4e3ea HTTP/1.1" 200 - "-" "okhttp/3.11.0"
::ffff:127.0.0.1 - - [03/Jan/2019:18:06:04 +0000] "GET /assets/src/screens/Feed/assets/ambitious.png?platform=android&hash=c930c040879f07cdd8a60a50344e3891 HTTP/1.1" 200 - "-" "okhttp/3.11.0"
::ffff:127.0.0.1 - - [03/Jan/2019:18:06:04 +0000] "GET /assets/src/screens/Feed/assets/worried_big.png?platform=android&hash=833feeb590cd1fc7104d8fc55e1a6f68 HTTP/1.1" 200 - "-" "okhttp/3.11.0"
::ffff:127.0.0.1 - - [03/Jan/2019:18:06:04 +0000] "GET /assets/src/screens/Feed/assets/smile.png?platform=android&hash=2061f778fc1d2da88e276707dd7d97a3 HTTP/1.1" 200 - "-" "okhttp/3.11.0"
::ffff:127.0.0.1 - - [03/Jan/2019:18:06:04 +0000] "GET /assets/src/screens/Feed/assets/sad_big.png?platform=android&hash=7810c8fb239022b64e91ee4b7e9710fc HTTP/1.1" 200 - "-" "okhttp/3.11.0"
::ffff:127.0.0.1 - - [03/Jan/2019:18:06:04 +0000] "GET /assets/src/screens/Feed/assets/smile_big.png?platform=android&hash=6b115d92cb3200d8a156777036d3c24c HTTP/1.1" 200 - "-" "okhttp/3.11.0"
::ffff:127.0.0.1 - - [03/Jan/2019:18:06:04 +0000] "GET /assets/src/screens/Feed/assets/surprised_big.png?platform=android&hash=d843aea7d0823bf75cf8eb5f62d51d98 HTTP/1.1" 200 - "-" "okhttp/3.11.0"
::ffff:127.0.0.1 - - [03/Jan/2019:18:06:04 +0000] "GET /assets/src/screens/Feed/assets/ambitious_big.png?platform=android&hash=78013f4de99912da45789aca77102676 HTTP/1.1" 200 - "-" "okhttp/3.11.0"

**Comment by ItsNoHax** [comment]
duplicate issue, closing.

**Comment by harikrishnadvk1991** [comment]
where and how  to close duplicate issue
