### ISSUE TITLE
_reactNative.Navigation.startSingleScreenApp

### ISSUE THREAD

**Issue by khenry10** [wix/react-native-navigation#4538]
### Issue Description

Xcode settings got wiped and some iOS files possibly lost through a git issue.  Now the app won't start up (errors below).  I re-done the whole library linking process and re-traced the steps but the app won't start.

Errors: 
 - red error simulator screen that says: _reactNative.Navigation.startSingleScreenApp is not a function
 - the terminal window I ran "run-ios" fails and has this error: 
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNNCustomViewController", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

https://wix.github.io/react-native-navigation/#/docs/Installing?id=requirements say to edit .h and .m, is there a specific example of what AppDelegate.h should look like?

### Steps to Reproduce / Code Snippets / Screenshots

- npm run start
- run-ios --simulator="iPhoneX"

App.js:
import { Navigation } from 'react-native-navigation';

import AuthScreen from './src/screens/Auth/Auth';
import SequencesList from './src/screens/SequencesList/SequencesList';

Navigation.registerComponent("my-app.AuthScreen", () => AuthScreen);
Navigation.registerComponent("my-app.App", () => App);
Navigation.registerComponent("my-app.SequencesList", () => SequencesList);

Navigation.startSingleScreenApp({
    screen: {
        screen: "my-app.SequencesList",
        title: "Sequences"
    }
});

![screen shot 2019-01-04 at 6 45 33 am](https://user-images.githubusercontent.com/11139044/50686705-715b0600-0fec-11e9-91da-86c66902668b.png)

<img width="800" alt="screen shot 2019-01-04 at 6 46 51 am" src="https://user-images.githubusercontent.com/11139044/50686736-8b94e400-0fec-11e9-9f31-ba4953eaab1b.png">

![screen shot 2019-01-04 at 6 47 53 am](https://user-images.githubusercontent.com/11139044/50686776-b5e6a180-0fec-11e9-959d-6401b0be9905.png)

---
### Environment
* React Native Navigation version: ^2.2.5
* React Native version:  0.55.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
Hey there, `startSingleScreenApp` is v1 api and you have v2 installed.
You can refer to the [migration guide](https://wix.github.io/react-native-navigation/#/docs/top-level-api-migration?id=starttabbasedappparams-gt-setrootbottomtabs) for more info.
