### ISSUE TITLE
[V2][android] Linking "url" event never fire.

### ISSUE THREAD

**Issue by Darkilen** [wix/react-native-navigation#4539]
### Issue Description

On Android using RNN v2, the Linking 'url' event listener does not fire.

Re-open of #3581 since it was closed unresolved.

### Steps to Reproduce / Code Snippets / Screenshots

```jsx
const { Navigation } = require('react-native-navigation');
const { registerScreens } = require('./screens');
const { Platform } = require('react-native');

function start() {
  registerScreens();
  Navigation.events().registerAppLaunchedListener(() => {
     Linking.addEventListener("url", event => {
        console.log("url", { event });
     });
     // Other code to launch app
  }) 
}
```

---
### Environment
* React Native Navigation version: 2.0.2438
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device - Android 8.1.0 - both

**Comment by RobertFOConnor** [comment]
Can confirm this is an issue on **Android**. Using the following workaround for now:

```
 Navigation.events().registerAppLaunchedListener(async () => {
    setNavigationRoot();
  });
  isAndroid && setNavigationRoot();
```

**Comment by Darkilen** [comment]
This issue is still relevant.

**Comment by Darkilen** [comment]
This issue is still relevant.

**Comment by Darkilen** [comment]
This issue is still relevant.

**Comment by draperunner** [comment]
I am also trying to get the URL from deep linking, but there's never a URL.

```
Navigation.events().registerAppLaunchedListener(async () => {
  Linking.getInitialURL().then((url) => {
          console.log('Did we come from a URL?')
          if (url) {
              console.log(`Initial url is: ${url}`)
          }
      }).catch(err => console.error('app: An error occurred', err)
```

**Comment by Darkilen** [comment]
This issue is still relevant.

**Comment by piuholo** [comment]
`Linking.getInitialURL()` works for me but I cannot get the listener `Linking.addEventListener('url', handler)` to fire with RNN.

**Comment by mtzfactory** [comment]
Hi, I have the same Issue as @draperunner ...

**Comment by piuholo** [comment]
Still an issue

**Comment by oxy88** [comment]
Still

**Comment by randomBrainstormer** [comment]
Still present in `version 3.2.0`

**Comment by randomBrainstormer** [comment]
I was able to get the `Linking.addEventListener('url', handler)` event to fire by adding the check described [here](https://github.com/react-navigation/react-navigation/issues/798#issuecomment-290363058) like this: 

```objective-c
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{

  if ([RCTLinkingManager application:application openURL:url sourceApplication:nil annotation:nil]) {
    return YES;
  }

 // default to normal snippet handling
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

**Comment by zarvedan** [comment]
@Darkilen I had the same issue (Only Android with RNN V2) when clicking on a Facebook post that redirects to my app. The intent ACTION was "com.facebook.blabla" and was not catched on RN side.
By forcing the intent action to ACTION_VIEW, the Linking "url" event is fired correctly.

2 lines to add on MainActivity's onCreate method:

```
Intent intent = getIntent(); // <- add this line
intent.setAction(Intent.ACTION_VIEW); // <- add this line
```

1 line to add on NavigationActivity:

```  
@Override
    public void onNewIntent(Intent intent) {
        intent.setAction(Intent.ACTION_VIEW); // <- add this line
        if (!getReactGateway().onNewIntent(intent)) {
            super.onNewIntent(intent);
        }
    }
```

I hope it can resolves your issue.

**Comment by bmbmjmdm** [comment]
This is still an issue. Please stop trying to close this, bot -.-

**Comment by zarvedan** [comment]
> @Darkilen I had the same issue (Only Android with RNN V2) when clicking on a Facebook post that redirects to my app. The intent ACTION was "com.facebook.blabla" and was not catched on RN side.
> By forcing the intent action to ACTION_VIEW, the Linking "url" event is fired correctly.
> 
> 2 lines to add on MainActivity's onCreate method:
> 
> ```
> Intent intent = getIntent(); // <- add this line
> intent.setAction(Intent.ACTION_VIEW); // <- add this line
> ```
> 
> 1 line to add on NavigationActivity:
> 
> ```
> @Override
>     public void onNewIntent(Intent intent) {
>         intent.setAction(Intent.ACTION_VIEW); // <- add this line
>         if (!getReactGateway().onNewIntent(intent)) {
>             super.onNewIntent(intent);
>         }
>     }
> ```
> 
> I hope it can resolves your issue.

Helping myself 2 years later with same issue on RNN V7 ! :)
