### ISSUE TITLE
[V2] StatusBar resetting its style when backing out of the app with the back button

### ISSUE THREAD

**Issue by denisloch** [wix/react-native-navigation#4541]
### Issue Description

I currently have one Screen and a sideMenu in my App:
```
Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setRoot({
        root: {
            sideMenu: {
                id: "sideDrawer",
                left: {
                    component: {
                        name: "global.Drawer",
                    },
                },
                options: {
                    sideMenu: {
                        left: {
                            width: 290
                        }
                    }
                },
                center: {
                    stack: {
                        id: "centerStack",
                        children: [{
                            component: {
                                name: "component1.Main"
                            }
                        }],
                        options: `{`
                            topBar: {
                                visible: false,
                                animate: false,
                                drawBehind: true
                            }
                        }
                    },
                }
            },
        }
    });
});
```      
I set the StatusBar color like that:
```
Navigation.setDefaultOptions({
    statusBar: {
        backgroundColor: "rgba(0, 0, 0, .2)",
        drawBehind: true,
        visible: true,
    }
})
```
Now, if I back out of my app using the back button of my phone and then open up the app again, the statusBar resets itself to the standard style (black color and drawBehind set to false).

I have no idea on how to resolve this issue, I tried pasting the second posted code snippet into both the "global.Drawer" and "component1.Main" components, but nothing seems to work and I highly assume that this is not intended.

---
### Environment
* React Native Navigation version: 2.4.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Device: OnePlus 3, Android: 8.0.0, OxygenOS: 5.0.8, Debug & Release (both)

**Comment by asolas** [comment]
same as home button, a new screen created with no navigation options each time.
![test](https://user-images.githubusercontent.com/16093867/50749877-c90fa080-127c-11e9-8d73-f815d727aaa4.gif)

**Comment by denisloch** [comment]
@asolas 

Wow, thanks for bringing up this solution, using
```
@Override 
public void invokeDefaultOnBackPressed() {
    moveTaskToBack(true); 
}
```
worked like charm. I guess React Native is remounting everything, which leads to the Navigator not working as intended.

I'm not so sure if that is enough to close the issue and if it even can be fixed from the react-native-navigation side or if it is a bug by react-native alone triggering a remount where there shouldn't be one.

**Comment by Zaporozhec7** [comment]
I was have same problems. Thanks to @asolas for pointing to solution. But solution above require adding `hardwareBackPress` hadler on each screen, other case back button not pop screens from stack and always put app to background.  Adding handler on each screen is quite hard when there dozens of screens and complex layout. So I look into `com.reactnativenavigation.NavigationActivity` class, and seen there also `invokeDefaultOnBackPressed` method override:

 ```
   @Override
    public void invokeDefaultOnBackPressed() {
        if (!navigator.handleBack(new CommandListenerAdapter())) {
            super.onBackPressed();
        }
    }
```

So combining code above from react-native-navigation and:
```
@Override 
public void invokeDefaultOnBackPressed() {
    moveTaskToBack(true); 
}
```

I have added to `MainActivity.java` next code:

  ```
  @Override
    public void invokeDefaultOnBackPressed() {
        if (!navigator.handleBack(new CommandListenerAdapter())) {
            moveTaskToBack(true);
        }
    }
```

Which work great for me. Hope this will help to someone.
