### ISSUE TITLE
[Feature Request] Track ComponentID Internally

### ISSUE THREAD

**Issue by kevinvangelder** [wix/react-native-navigation#4546]
### Issue Description

The developer shouldn't have to track `this.props.componentId` manually as it requires setting up a global navigation tracking system in order to navigate outside of normal screens. For example, if one wanted to reset their stack to the login screen any time the API returns a 401 unauthorized, they would need to implement a system to track what the current `componentId` is to pass in to `Navigation.setStackRoot`. I am happy to provide additional examples or information if it would be helpful.

### Steps to Reproduce / Code Snippets / Screenshots
N/A

---
### Environment
N/A

**Comment by kevinvangelder** [comment]
If this is already possible and I'm missing how, please let me know.

**Comment by guyca** [comment]
Hey there,
layouts accept an optional `id?: string` parameter which can be used to give a layout a predefined `componentId`.

For example, you can assign your root stack an id, and use that predefined id to reset the stack to an arbitrary screen.

```js
Navigation.setRoot({
  stack: {
    id: 'ROOT_STACK',
    children: []
  }
});

// 401 - reset stack to login screen
Navigation.setStackRoot('ROOT_SCREEN', {
  component: {
    name: 'LOGIN_SCREEN'
  }
});
```

**Comment by kevinvangelder** [comment]
@guyca Thanks! The documentation isn't clear what `this.props.componentId` is, so I had to dig out from other examples that I needed to do `Navigation.events().bindComponent(this);`, but it's even less clear that it has multiple possible uses, such as the example above.

**Comment by guyca** [comment]
You're right, the docs could definitely use more clarifications and improvements.
