### ISSUE TITLE
Screen title is truncated when back button title and screen title are too long (back button title should be truncated instead)

### ISSUE THREAD

**Issue by mcampsall** [wix/react-native-navigation#4549]
Why is the back button title taking precedence over the screen title?

<img width="414" alt="image" src="https://user-images.githubusercontent.com/15930818/50857100-7350fc00-1341-11e9-8a36-3c49df923c38.png">

Is there a way to make the back button title get truncated (or removed) if there is not enough space?

### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.55.3
* Platform(s) (iOS, Android, or both?):iOS

**Comment by LRNZ09** [comment]
This would be really appreciated

**Comment by kfroemming** [comment]
Any ideas?

**Comment by LRNZ09** [comment]
This is still relevant

**Comment by LRNZ09** [comment]
This is still relevant

**Comment by LRNZ09** [comment]
This is still relevant

**Comment by LRNZ09** [comment]
Still an issue.
