### ISSUE TITLE
Android Bug,When I use the 4 tab, the display is not full.

### ISSUE THREAD

**Issue by zhong6739168** [wix/react-native-navigation#455]
### Screenshot：
![device-2016-11-18-154018](https://cloud.githubusercontent.com/assets/9208390/20422453/7688d4f0-ada5-11e6-8cbc-c16c9ed35fe9.png)
![device-2016-11-18-154057](https://cloud.githubusercontent.com/assets/9208390/20422455/786a49d4-ada5-11e6-9b34-44a4eae4f85f.png)

### code:
const createTabs = () => {
    let tabs = [
        {
            label: '首页',
            screen: 'MainView',
            icon: require('../img/Index/tab_item_index.png'),
            selectedIcon: require('../img/Index/tab_item_index_select.png'),
            title: 'e行淮安',
            titleImage: require('../img/Index/index_title.png'),
            navigatorStyle: styles.navigatorStyle,
        },
        {
            label: '资讯',
            screen: 'InfoView',
            icon: require('../img/Index/tab_item_info.png'),
            selectedIcon: require('../img/Index/tab_item_info_select.png'),
            title: '交通资讯',
            navigatorStyle: styles.navigatorStyle,
        },
        {
            label: '服务',
            screen: 'ServiceView',
            icon: require('../img/Index/tab_item_service.png'),
            selectedIcon: require('../img/Index/tab_item_service_select.png'),
            title: '服务',
            navigatorStyle: styles.navigatorStyle,
        },
        {
            label: '设置',
            screen: 'SettingView',
            icon: require('../img/Index/tab_item_setting.png'),
            selectedIcon: require('../img/Index/tab_item_setting_select.png'),
            title: '设置',
            navigatorStyle: styles.navigatorStyle,
        }
    ];
    return tabs;
};

**Comment by guyca** [comment]
Hey @zhong6739168 
Could you please provide more information? What do you mean by "the display is not complete"?

**Comment by zhong6739168** [comment]
@guyca My tab title will be displayed when my tab is selected. but when my tab is not selected,it's gone.

**Comment by guyca** [comment]
When calling add `appStyle` object to `startTabBasedApp`:

```js
appStyle: {
  forceTitlesDisplay: true
}
```

**Comment by zhong6739168** [comment]
@guyca it's working,thank you very musch.I have another question, can I set a APP LOGO on the left side of the navbar's title

**Comment by guyca** [comment]
Not possible at the moment.

**Comment by zhong6739168** [comment]
@guyca understood
