### ISSUE TITLE
[V2] Differentiate between push and showModal

### ISSUE THREAD

**Issue by danilobuerger** [wix/react-native-navigation#4551]
### Issue Description

In V1 we had a prop `commandType` that was set on each screen telling us wether the screen was pushed or shown as a modal. 

Can this be done with V2 or do we have to track it ourself?

**Comment by danilobuerger** [comment]
Not Stale, awaiting answer.

**Comment by danilobuerger** [comment]
Not Stale, awaiting answer.

**Comment by danilobuerger** [comment]
Not Stale, awaiting answer.

**Comment by danilobuerger** [comment]
Not Stale, awaiting answer.

**Comment by danilobuerger** [comment]
Not Stale, awaiting answer.

**Comment by danilobuerger** [comment]
Not Stale, awaiting answer.

**Comment by muhammadarsal** [comment]
Not Stale, awaiting answer.
