### ISSUE TITLE
Attempted to invoke method on UIManager with an invalid bridge

### ISSUE THREAD

**Issue by L-Yeiser** [wix/react-native-navigation#4558]
### Issue Description
When running the playground app on a real iOs device you get the yellow box warning `Attempted to invoke [number] (method ID) on UIManager (NativeModule name) with an invalid bridge.`  This issue [may be related to](https://github.com/facebook/react-native/issues/20926). But the yellow box warning disappear when you revert to the default app entry point.

### Steps to Reproduce / Code Snippets / Screenshots
Init the playground app. Run on a real device. Reload the app a few times. The yellow box errors will appear. [This app](https://github.com/L-Yeiser/reactNativeNavigationV2Test) shows that reverting to the default entry point and removing RN-navigation gets rid of the yellow box warnings.

---
### Environment
* React Native Navigation version:  2.5.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOs
* Device info (Simulator/Device? OS version? Debug/Release?): iphone X
![img_2372a21d575c-1](https://user-images.githubusercontent.com/6750498/50922045-575f6000-13fe-11e9-9e74-4f1622fa10fa.jpeg)

**Comment by mpcen** [comment]
Anything on this? This is causing entire app to act funky

**Comment by OnurVar** [comment]
I'm no expert but probably react-native-navigation's RCTBridge initializers are getting mixed up somewhere.

**Comment by hadnet** [comment]
Same thing here using react-native-navigation@2.11.0, react-native 0.59.0-rc.1 and react@16.8.2

**Comment by remigijusbalc** [comment]
Same issue with react-native "0.58.4" and react-native-navigation "^2.11.0"

**Comment by acollazomayer** [comment]
same here with same configuration of @remigijusbalc

**Comment by acollazomayer** [comment]
I found out that this happens whenever I refresh more than one time fast

**Comment by EskelCz** [comment]
Same with RN 0.58.5 and RNN 2.0.2483 :(

**Comment by EskelCz** [comment]
Updated to RNN 2.12.0 and the issue went away.

**Comment by hadnet** [comment]
Still these yellow box warnings in RN 0.59.0-RC.3 and RNN 2.12.0

**Comment by acollazomayer** [comment]
@hadnet I submitted a PR to react native that was approved loggin this warnings in console instead of showing them as warnings. This happens because upon javascript refreshing. The asynchronous bridge of react native stops and becomes invalidated.

**Comment by henrikra** [comment]
@acollazomayer You mean this one? https://github.com/facebook/react-native/pull/23557 Do you know in which version it is released?

**Comment by acollazomayer** [comment]
@henrikra sorry I dont know. maybe its in the last 0.59.2 version

**Comment by henrikra** [comment]
Okay but at least it is merged so it should come at some point :D I would close this issue since it is fixed now in React Native and now we just wait for the release

**Comment by acollazomayer** [comment]
@henrikra yes this could be close, at some point this should be fixed correctly I think, However is not a react-native-navigation issue.

**Comment by muganwas** [comment]
I'm having this same exact issue. RN 0.59.5

**Comment by mths0x5f** [comment]
Oh gosh, these are really annoying

**Comment by wanxsb** [comment]
I also have this exact issues. RN 0.59.8
![image](https://user-images.githubusercontent.com/1924449/59498821-b7d05d00-8ec8-11e9-987c-53876b1f7dc7.png)

**Comment by the-duck** [comment]
same here

**Comment by unutoiul** [comment]
I got the same issue 
<img width="429" alt="Screenshot 2019-06-20 at 18 43 49" src="https://user-images.githubusercontent.com/317535/59834573-8f92a380-938b-11e9-8ee9-c1f99dec0fb4.png">


any fixes?

**Comment by AugustoAleGon** [comment]
Same issue

**Comment by liaodiv** [comment]
https://github.com/wix/react-native-navigation/issues/4558 
it is the issue for react-native 0.57.0 ^ maybe just on ios simulator

**Comment by FrankGoortani** [comment]
@liaodiv  `console.warn` is suppressed on production release of the react-native apps. That is why you only see them in simulator. This needs to be resolved. I have the same issue in R 0.59

**Comment by BingXiong1995** [comment]
I was facing this issue, I cannot believe after I restart my Mac, this warning disappear!

**Comment by ConnectedReasoning** [comment]
same issue here
    "react": "16.8.3",
    "react-native": "^0.59.2", but it only happens when I run simulator devices iphone 6 and iPhone 6s seems to be ok on iPhone X

**Comment by kg-currenxie** [comment]
Same with 0.59.9. Starting the iOS simulator with debugger and hot reloading ON

**Comment by BracketMan** [comment]
Also experiencing the same issue. Whenever I close the app and open it again, i get the same timing issue.

**Comment by its-wufu** [comment]
Can also confirm this to be happening on ios simulator with RN 0.59.9

**Comment by iamisathya** [comment]
> Can also confirm this to be happening on ios simulator with RN 0.59.9

Yes, it's happening on RN 0.59.9

**Comment by mcaubrey** [comment]
Also have this happening on RN 0.59.9

**Comment by Bautista-Baiocchi-lora** [comment]
Same problem on RN 0.62.0

**Comment by guyca** [comment]
@Bautista-Baiocchi-lora Which RNN version are you using?

**Comment by Bautista-Baiocchi-lora** [comment]
> @Bautista-Baiocchi-lora Which RNN version are you using?

I have removed my comment, I was causing the error myself. The debug message just wasn't descriptive.

**Comment by avzz-19** [comment]
Same issue when i try to click the login link recd on email and app tries to open. Any fixes? (RN 0.64)
Attempted to invoke `1` (method ID) on `Timing` (NativeModule name) without a method queue.
Multiple errors and app crashes on ios.
