### ISSUE TITLE
Integration into existing app

### ISSUE THREAD

**Issue by emielvanliere** [wix/react-native-navigation#456]
Hey, first of all awesome library! Native navigation is really one of the missing pieces in React Native at the moment.

I tried integrating this library into my existing native iOS app (ie. the app is native, but some parts of the app are in ReactNative) but I quickly discovered that react-native-navigation assumes that it will cover all of the app's navigation.

For instance in `RCCManager.m ` and `RCCManagerModule.m` there are many references to the AppDelegate's window rootViewController. But if instead we pass `rootViewController` into the constructor of`RCCManager` (and exposing it to other classes in this lib), this would open the possibility to use this library in an existing app that already has its root navigation set up.

Have you considered this? Is it on the roadmap? If not, would you take a PR for this?

(I have not looked into Android btw but I would assume it works the same way)

Thanks!

**Comment by DanielZlotin** [comment]
Thanks for you input,
react-native-navigation's purpose is to bridge the gap (heh) between react-native and the native side. 

Specifically, it allows you to send navigation requests to the native side (created and managed by this framework) and listen on certain events. Basically, allows you to write truly native apps with almost no native knowledge.

If your app is already built with native navigation, you basically gain little from using this framework (I assume you yourself call `startReactApplication`).
What are your motivations for using react-native-navigation?

**Comment by atlas1119** [comment]
I want to Integrate into existing app, how to do?

**Comment by alinz** [comment]
@DanielZlotin one of the valid usage case that I'm struggle with is adding react-native-navigator to share extension. As you know share extension and any other extension do not access to UIApplication and as a result there is no appDelegate. I'm also Author of react-native-share-extension and I'm planning to use this library as my navigation in the app. It would be nice if we can expose some classes which for advance user they can extend and change the behaviour how react-native-navigation attaches itself to UIView. I haven't jumped into Android yet but I assumed it would be the same problem. 

It would be nice to hear back from core dev of react-native-navigation on this matter.
