### ISSUE TITLE
[V2][iOS] BottomTabs drawBehind weird behaviour

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#4563]
### Issue Description

I have a bottomTabs layout where my Email tab (see screenshot below) contains a sideMenu layout.
I'm seeing weird behaviour with drawBehind when I hide the bottomTabs.

It seems the center component of the SideMenu layout does not re-render till the app is minimized and opened again.

Code used to hide bottomTabs:
```
  componentDidAppear() {
    Navigation.mergeOptions(this.props.componentId, {
      bottomTabs: {
        visible: false,
        animate: true,
        drawBehind: true,
      },
    });
  }

  componentDidDisappear() {
    Navigation.mergeOptions(this.props.componentId, {
      bottomTabs: {
        visible: true,
        animate: true,
        drawBehind: false,
      },
    });
  }
```

### Steps to Reproduce / Code Snippets / Screenshots

![2019-01-10 15 43 46](https://user-images.githubusercontent.com/4223434/50975909-ee0b4a00-14ee-11e9-943d-ddc1c8b5cab1.gif)

---
### Environment
* React Native Navigation version: 2.5.0
* React Native version: 56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by narodejesus** [comment]
also bottomTabs drawBehind true does not work when set by mergeOptions

**Comment by benpeke** [comment]
I am trying to remove bottom tabs using mergeOptions and it is not working, there is a white bar where the tabs should have been. @narodejesus did you ever find a solution for that?

**Comment by guyca** [comment]
@benpeke Which version are you using?

**Comment by benpeke** [comment]
> @benpeke Which version are you using?

Using RN59 and RNN 2.27.7. I just noticed this issue when I updated from RN56.
