### ISSUE TITLE
Custom Transition not working with showModal() and really jumpy with push() on iOS

### ISSUE THREAD

**Issue by jayjac** [wix/react-native-navigation#4566]
I just downloaded the 2.6.0 version of RNN.
As the title reads:
when I use customTransition as explained on the page https://wix.github.io/react-native-navigation/#/docs/animations
the customTransition doesn't work AT ALL with Navigation.showModal() and it is pretty jumpy with Navigation.push()
In the second example, the view that is in common transitions to a new position that is somehow miscalculated and at the end of the transition it drops down instantaneously to its expected position (the length of the drop seems to be equal to the height of the topbar).

### Steps to Reproduce / Code Snippets / Screenshots

```js   

// FirstScreen.js ..                                                 
_showOtherScreenWithAnimation = () => {
    Navigation.push(this.props.componentId, {
      component: {
        name: "viewInCommonScreen",
        options: {
          customTransition: {
            animations: [
              {
                type: "sharedElement",
                fromId: "viewInCommon1",
                toId: "viewInCommon2",
                startDelay: 0,
                springVelocity: 0.2,
                duration: 0.8
              }
            ],
            duration: 0.8
          }
        }
      }
    });
  };

  render() {
    return (
      <View style={styles.container}>
        <Button
          title="Show modal with view in common"
          onPress={this._showOtherScreenWithAnimation}
        />
        <Navigation.Element elementId="viewInCommon1">
          <View style={styles.viewInCommon1} />
        </Navigation.Element>
      </View>
    );
  }

// In the other screen's file:
  render() {
    return (
      <View style={styles.container}>
        <Navigation.Element elementId="viewInCommon2">
          <View style={styles.viewInCommon2} />
        </Navigation.Element>
      </View>
    );
  }
``` 

---
### Environment
* React Native Navigation version: 2.6.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X simulator 12.1

**Comment by danieljvdm** [comment]
I'm experiencing the same issues.

**Comment by Jyrno42** [comment]
Does not work with modals at all for me. With `push` only seems to work in version `2.9.0` and below.

**Comment by jayjac** [comment]
Nothing works on the current version. When showing a modal, the transition is simply ignored. When pushing in a stack, the final placement of the view in common at the end of the transition does not match its  actual placement in the new screen. So there is a weird “jump” when the transition finishes.
Have you guys thought of using the Hero transition SDK for the iOS ?

**Comment by kdawgwilk** [comment]
[Video of Issue when pushing](https://drive.google.com/open?id=1pjgYG-kJ-1ygdQrlDY8wlu-ToCNV6LDz)

**Comment by kdawgwilk** [comment]
Seems like the the jump the views make after the transition completes is about the same height as the topBar which makes me suspect that the height of the topBar is not being accounted for in the transition.  This also applies to when the topBar is not `visible` with `drawBehind` set to true.

**Comment by madandrija** [comment]
It goes to the top and then jumps down by the topBar+statusBar height

**Comment by pedrobertao** [comment]
Custom transitions works fine on Android but not for iOS when using 

`{
 showModal: {
    alpha: {
      from: 0,
      to: 1,
      duration: 300
    }
},
dismissModal:{
    alpha: {
      from: 1,
      to: 0,
      duration: 300
    }
}
}`

**Comment by madandrija** [comment]
> Custom transitions works fine on Android but not for iOS when using
> 
> `{ showModal: { alpha: { from: 0, to: 1, duration: 300 } }, dismissModal:{ alpha: { from: 1, to: 0, duration: 300 } } }`

What? How does this relate to the OP?

**Comment by pedrobertao** [comment]
> > Custom transitions works fine on Android but not for iOS when using
> > `{ showModal: { alpha: { from: 0, to: 1, duration: 300 } }, dismissModal:{ alpha: { from: 1, to: 0, duration: 300 } } }`
> 
> What? How does this relate to the OP?

What do you mean ? This is the code from the showModal transition that isn't working with ios

**Comment by jinshin1013** [comment]
@pedrobertao  have a look at this #5078. There is some inconsistency between the platform at the moment.

**Comment by carobeta** [comment]
@

> Seems like the the jump the views make after the transition completes is about the same height as the topBar which makes me suspect that the height of the topBar is not being accounted for in the transition. This also applies to when the topBar is not `visible` with `drawBehind` set to true.

Do you find any solution?
