### ISSUE TITLE
[v2][Android] Top bar Title Flickering

### ISSUE THREAD

**Issue by hadimostafapour** [wix/react-native-navigation#4571]
### Issue Description

While push/pop pages the topBar title blinks. 

![demo](https://user-images.githubusercontent.com/33980142/51035394-182c3d00-15bf-11e9-8030-36a2cdea27ff.gif)
_GIF is 5x slower_

Basically same as: #3864

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 2.6.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by hadimostafapour** [comment]
Hey bot, Issue still exists!

**Comment by htkibar** [comment]
Is this happening to you only on Android or also with iOS as well?

**Comment by hadimostafapour** [comment]
@htkibar only `Android`

**Comment by rickyliu93** [comment]
+1

**Comment by MoonlightAniki** [comment]
+1

**Comment by gusoskar** [comment]
+1

**Comment by LoganArnett** [comment]
Still seeing this on 2.18.2, every screen change cause my title icon to flicker even though it is static

**Comment by ferrydarma** [comment]
This workaround works like magic. Give it a try guys:
https://medium.com/@linasmnew/react-native-navigation-wix-fix-top-left-corner-flickering-bcf5f9aa57cd
