### ISSUE TITLE
Navigating between Stacks

### ISSUE THREAD

**Issue by lukebrandonfarrell** [wix/react-native-navigation#4572]
### Issue Description
Hi Everyone,

I've been trying to achieve a certain navigational flow in RNN for a while now, but have not had any success. Here is the flow I am trying to achieve:

![rnn-issue](https://user-images.githubusercontent.com/18139277/51042696-d5656780-15b4-11e9-8a42-0de22af0f68e.png)

Let's say you start from the products screen. You are able to explore a product and purchase one, these screens are added to the stack with `push`. Once the checkout has been completed I want the stack to reset to the orders bottom tab stack with the specific order page on top of the stack.

One solution would be to push the specific orders page onto the stack using an ID e.g. `ORDERS_STACK`, but then how would I reset the current stack (products), and navigate to the orders tab?

I've tried using `setStackRoot` but could not achieve what I wanted, it may be due to me using it incorrectly, but I could not find a description on how `setStackRoot` works anywhere on the repository.

### Environment
* React Native Navigation version: 2.6.0
* React Native version: 0.57.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (iOS/Android, Debug/Release): Both

**Comment by guyca** [comment]
Hey @lukebrandonfarrell 
Instead of pushing the screens, you should initiate this flow in a modal - meaning show `Details Screen` in a modal and push screens into that modal.

When dismissing the modal, select orders tab programatically using `mergeOptions`
