### ISSUE TITLE
React-native-navigation [V2] - Android - modal's topBar visible before modal opens

### ISSUE THREAD

**Issue by jojomillenium** [wix/react-native-navigation#4579]
### Issue Description

I am using react-native-navigation v2. I've put in place a fairly basic navigation to open a modal.

The issue I am having is that on Android the topBar of my modal appears before the modal has appeared, giving on top of it a flickering effect (see gif below, compares between iOS and Android). I've played around with many config options... but could not get to a smooth page transition (it kind of is the same issue when I push on a stack, the transition on Android is not smooth).

![androidflickermodal](https://user-images.githubusercontent.com/6372094/51088777-3d0de500-1764-11e9-97d6-80804e29ff33.gif)

### Steps to Reproduce / Code Snippets / Screenshots
in my index.js
```js
import { Navigation } from "react-native-navigation";
import { Home, AddIdeaScreen } from './src/screens';
// ...
// Store Config
import { Provider } from 'react-redux';
import configureStore from './src/store/configureStore';

const store = configureStore();

Navigation.events().registerAppLaunchedListener(() => {
   Navigation.registerComponentWithRedux(`Home`, () => Home, Provider, store);
   Navigation.registerComponentWithRedux(`AddIdeaScreen`, () => AddIdeaScreen, Provider, store);

  Navigation.setDefaultOptions({
    layout: {
      orientation: ['portrait']
    },
    topBar: {
      visible: true,
      drawBehind: false
    },
    animations: {
      push: {
        waitForRender: true,
      },
      showModal: {
        waitForRender: true
      }
    }
  });
  Promise.all([
    Icon.getImageSource("magnify", 30),
    Icon.getImageSource("account", 30),
  ]).then(source => {
    Navigation.setRoot({
      root: {
        stack: {
          children: [{
            component: {
              name: "Home",
              options: {
                topBar: {
                  testID: "Home.TopBar",
                  background: {
                    color: themeVars.brandPrimary
                  },
                  title: {
                    text: i18n.t('Home.title'),
                    color: "white"
                  },
                  rightButtons: [{
                      id: 'viewProfile',
                      icon: source[1],
                      color: "white",
                      testID: "Home.profileButton"
                  }, {
                      id: 'searchFriends',
                      icon: source[0],
                      color: "white",
                      testID: "Home.friendsButton"
                  }],
                }
              }
            }
          }
          ]
        }
      }
    })
  })
});
```
Then in my App.js (my home page), my Fab has an onPress event: onPress = {this.FabClickedHandler}
```js
import React, { Component } from 'react';
// ...
class Home extends Component {
constructor(props) {
        super(props);
    }
FabClickedHandler = () => {
    Promise.all([
      MaterialIcon.getImageSource("close", 30)
    ])
    .catch(err => {
      alert(err);
    })
    .then(source => {
      Navigation.showModal({
        stack: {
          children: [{
            component: {
              name: 'AddIdeaScreen',
              options: {
                topBar: {
                  testID : 'AddIdeaScreen.title',
                  background: {
                    color: themeVars.brandPrimary
                  },
                  leftButtons: [{
                    id: 'cancelButton',
                    testID: 'AddIdeaScreen.cancelButton',
                    ...Platform.select({
                      ios: { text: i18n.t('AddIdeaScreen.cancelButton'), },
                      android: { icon: source[0], }
                    }),
                    color: "white"
                  }],
                  rightButtons: [{
                    id: 'saveButton',
                    testID : 'AddIdeaScreen.saveButton',
                    text: i18n.t('AddIdeaScreen.saveButton'),
                    enabled: false,
                    color: "white"
                  }],
                  title: {
                    text: i18n.t('AddIdeaScreen.title'),
                    color: "white"
                  }
                }
              }
            }
          }]
        }
      })
    })
  }
  // ...
  render() {
  return (
  // ...
                   <Fab
                        active={true}
                        position='bottomRight'
                        testID='Home.FabButton'
                        onPress={this.fabClickedHandler}
                        style={{ backgroundColor: themeVars.brandPrimary }}
                    >
                        <Icon name="plus" type='MaterialCommunityIcons'></Icon>
                    </Fab>
// ...
)}
}
```

---
### Environment
* "native-base": "^2.10.0"
* "react": "16.6.3"
* "react-native": "0.57.8"
* "react-native-navigation": "^2.6.0"
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator API 27, 28 and real device

**Comment by L-Yeiser** [comment]
A work around until this gets fixed - When you call showModal pass `visible: false`, and in the `componentDidMount` update the visibility.

```
Navigation.showModal({
  stack: {
    children: [{
      component: {
        name: 'Login',
        options: {
          topBar: {
            visible: false,
          },
        },
      },
    }],
  },
});
```
Then in the Login component
```
componentDidMount() {
  Navigation.mergeOptions(
    this.props.componentId,
    {
      topBar: {
        visible: true,
        animate: false,
      },
    },
  );
}
```

**Comment by jojomillenium** [comment]
@L-Yeiser , Thank you for suggesting this approach.

Unfortunately it does not solve it fully, as we still see it appear very quick, and it creates a flickering on the screen, see below.

![2019-01-17_07-35-07](https://user-images.githubusercontent.com/6372094/51300016-b76f8b00-1a2a-11e9-9a35-4acdc0f94617.gif)

I played around, trying setting the ```visible:false``` at setDefaultOptions, but without any success.

**Comment by tidianeb5** [comment]
> ### Issue Description
> I am using react-native-navigation v2. I've put in place a fairly basic navigation to open a modal.
> 
> The issue I am having is that on Android the topBar of my modal appears before the modal has appeared, giving on top of it a flickering effect (see gif below, compares between iOS and Android). I've played around with many config options... but could not get to a smooth page transition (it kind of is the same issue when I push on a stack, the transition on Android is not smooth).
> 
> ![androidflickermodal](https://user-images.githubusercontent.com/6372094/51088777-3d0de500-1764-11e9-97d6-80804e29ff33.gif)
> 
> ### Steps to Reproduce / Code Snippets / Screenshots
> in my index.js
> 
> ```js
> Navigation.events().registerAppLaunchedListener(() => {
>   Navigation.setDefaultOptions({
>     layout: {
>       orientation: ['portrait']
>     },
>     topBar: {
>       visible: true,
>       drawBehind: false
>     },
>     animations: {
>       push: {
>         waitForRender: true,
>       },
>       showModal: {
>         waitForRender: true
>       }
>     }
>   });
>   Promise.all([
>     Icon.getImageSource("magnify", 30),
>     Icon.getImageSource("account", 30),
>   ]).then(source => {
>     Navigation.setRoot({
>       root: {
>         stack: {
>           children: [{
>             component: {
>               name: "IdeasScreen",
>               options: {
>                 topBar: {
>                   testID: "Home.TopBar",
>                   background: {
>                     color: themeVars.brandPrimary
>                   },
>                   title: {
>                     text: i18n.t('Home.title'),
>                     color: "white"
>                   },
>                   rightButtons: [{
>                       id: 'viewProfile',
>                       icon: source[1],
>                       color: "white",
>                       testID: "Home.profileButton"
>                   }, {
>                       id: 'searchFriends',
>                       icon: source[0],
>                       color: "white",
>                       testID: "Home.friendsButton"
>                   }],
>                 }
>               }
>             }
>           }
>           ]
>         }
>       }
>     })
>   })
> });
> ```
> 
> Then in my App.js (my home page), my Fab has an onPress event: onPress = {this.FabClickedHandler}
> 
> ```js
> FabClickedHandler = () => {
>     Promise.all([
>       MaterialIcon.getImageSource("close", 30)
>     ])
>     .catch(err => {
>       alert(err);
>     })
>     .then(source => {
>       Navigation.showModal({
>         stack: {
>           children: [{
>             component: {
>               name: 'AddIdeaScreen',
>               options: {
>                 topBar: {
>                   testID : 'AddIdeaScreen.title',
>                   background: {
>                     color: themeVars.brandPrimary
>                   },
>                   leftButtons: [{
>                     id: 'cancelButton',
>                     testID: 'AddIdeaScreen.cancelButton',
>                     ...Platform.select({
>                       ios: { text: i18n.t('AddIdeaScreen.cancelButton'), },
>                       android: { icon: source[0], }
>                     }),
>                     color: "white"
>                   }],
>                   rightButtons: [{
>                     id: 'saveButton',
>                     testID : 'AddIdeaScreen.saveButton',
>                     text: i18n.t('AddIdeaScreen.saveButton'),
>                     enabled: false,
>                     color: "white"
>                   }],
>                   title: {
>                     text: i18n.t('AddIdeaScreen.title'),
>                     color: "white"
>                   }
>                 }
>               }
>             }
>           }]
>         }
>       })
>     })
>   }
> ```
> 
> ### Environment
> * "native-base": "^2.10.0"
> * "react": "16.6.3"
> * "react-native": "0.57.8"
> * "react-native-navigation": "^2.6.0"
> * Platform(s) (iOS, Android, or both?): Android
> * Device info (Simulator/Device? OS version? Debug/Release?): Simulator API 27, 28 and real device

please can i have your code-source

**Comment by jojomillenium** [comment]
> > ### Issue Description
> > I am using react-native-navigation v2. I've put in place a fairly basic navigation to open a modal.
> > The issue I am having is that on Android the topBar of my modal appears before the modal has appeared, giving on top of it a flickering effect (see gif below, compares between iOS and Android). I've played around with many config options... but could not get to a smooth page transition (it kind of is the same issue when I push on a stack, the transition on Android is not smooth).
> > ![androidflickermodal](https://user-images.githubusercontent.com/6372094/51088777-3d0de500-1764-11e9-97d6-80804e29ff33.gif)
> > ### Steps to Reproduce / Code Snippets / Screenshots
> > in my index.js
> > ```js
> > Navigation.events().registerAppLaunchedListener(() => {
> >   Navigation.setDefaultOptions({
> >     layout: {
> >       orientation: ['portrait']
> >     },
> >     topBar: {
> >       visible: true,
> >       drawBehind: false
> >     },
> >     animations: {
> >       push: {
> >         waitForRender: true,
> >       },
> >       showModal: {
> >         waitForRender: true
> >       }
> >     }
> >   });
> >   Promise.all([
> >     Icon.getImageSource("magnify", 30),
> >     Icon.getImageSource("account", 30),
> >   ]).then(source => {
> >     Navigation.setRoot({
> >       root: {
> >         stack: {
> >           children: [{
> >             component: {
> >               name: "IdeasScreen",
> >               options: {
> >                 topBar: {
> >                   testID: "Home.TopBar",
> >                   background: {
> >                     color: themeVars.brandPrimary
> >                   },
> >                   title: {
> >                     text: i18n.t('Home.title'),
> >                     color: "white"
> >                   },
> >                   rightButtons: [{
> >                       id: 'viewProfile',
> >                       icon: source[1],
> >                       color: "white",
> >                       testID: "Home.profileButton"
> >                   }, {
> >                       id: 'searchFriends',
> >                       icon: source[0],
> >                       color: "white",
> >                       testID: "Home.friendsButton"
> >                   }],
> >                 }
> >               }
> >             }
> >           }
> >           ]
> >         }
> >       }
> >     })
> >   })
> > });
> > ```
> > 
> > 
> > Then in my App.js (my home page), my Fab has an onPress event: onPress = {this.FabClickedHandler}
> > ```js
> > FabClickedHandler = () => {
> >     Promise.all([
> >       MaterialIcon.getImageSource("close", 30)
> >     ])
> >     .catch(err => {
> >       alert(err);
> >     })
> >     .then(source => {
> >       Navigation.showModal({
> >         stack: {
> >           children: [{
> >             component: {
> >               name: 'AddIdeaScreen',
> >               options: {
> >                 topBar: {
> >                   testID : 'AddIdeaScreen.title',
> >                   background: {
> >                     color: themeVars.brandPrimary
> >                   },
> >                   leftButtons: [{
> >                     id: 'cancelButton',
> >                     testID: 'AddIdeaScreen.cancelButton',
> >                     ...Platform.select({
> >                       ios: { text: i18n.t('AddIdeaScreen.cancelButton'), },
> >                       android: { icon: source[0], }
> >                     }),
> >                     color: "white"
> >                   }],
> >                   rightButtons: [{
> >                     id: 'saveButton',
> >                     testID : 'AddIdeaScreen.saveButton',
> >                     text: i18n.t('AddIdeaScreen.saveButton'),
> >                     enabled: false,
> >                     color: "white"
> >                   }],
> >                   title: {
> >                     text: i18n.t('AddIdeaScreen.title'),
> >                     color: "white"
> >                   }
> >                 }
> >               }
> >             }
> >           }]
> >         }
> >       })
> >     })
> >   }
> > ```
> > 
> > 
> > ### Environment
> > 
> > * "native-base": "^2.10.0"
> > * "react": "16.6.3"
> > * "react-native": "0.57.8"
> > * "react-native-navigation": "^2.6.0"
> > * Platform(s) (iOS, Android, or both?): Android
> > * Device info (Simulator/Device? OS version? Debug/Release?): Simulator API 27, 28 and real device
> 
> please can i have your code-source

What other code would help investigate? Other parts of my code is not related to Navigation so irrelevant to this question.
I've updated a bit the initial post to had a few imports I use. The rest is pure layout.

**Comment by FransTwisk** [comment]
I'm experiencing the same issue.

**Comment by jojomillenium** [comment]
I decided to move away from RNN for the modal part only and use the 'Modal' from react-native.

**Comment by L-Yeiser** [comment]
This is still an issue.

**Comment by fliPmitKlammern** [comment]
Same problem for me when pushing screens or showing Modals on Android with `waitForRender: true`. The flickering of the TopBar does not occur when setting waitForRender to false. However that does of course display a blank screen for some time, only trading one kind of flickering for another.

**Comment by mtzfactory** [comment]
I'm suffering the same issue...

**Comment by ericschaal** [comment]
Still an issue.

**Comment by FransTwisk** [comment]
This is still an issue and I don't understand why this isn't looked into?

**Comment by mayconmesquita** [comment]
Im having the same issue

**Comment by L-Yeiser** [comment]
Still an issue
