### ISSUE TITLE
instructions for launching playground app are out of date

### ISSUE THREAD

**Issue by Pushplaybang** [wix/react-native-navigation#4582]
### Issue Description

Following the documentation instructions for running the playground app do not work.  This seems largely due to the clone command shown, referencing the old v2 branch, which now seems out of date with master, where there have been a number of fixes, such as the issues with xcode 10.x #4321 #3608 etc

### Steps to Reproduce / Code Snippets / Screenshots

follow the playground setup documentation **exactly**.
https://wix.github.io/react-native-navigation/#/docs/showcases

#### Solution:
the first line should be changed from:

```
git clone -b v2 git@github.com:wix/react-native-navigation.git
```
to:
```
git clone -b master git@github.com:wix/react-native-navigation.git
```
---
### Environment
* React Native Navigation version: PLAYGROUND INSTRUCTIONS PULL THE WRONG ONE
* React Native version: 0.51 >=
* Platform(s) (iOS, Android, or both?): iOS / xcode / OSX
* Device info (Simulator/Device? OS version? Debug/Release?): IOS - ALL under xcode 10.x

**Comment by Pushplaybang** [comment]
update needed.

**Comment by Pushplaybang** [comment]
there seems to be some work around playground happening, are docs being updated as well

#4767  ?

**Comment by guyca** [comment]
Hey @Pushplaybang, seems like someone already PR'd a fix to that line. Sorry about the confusion.
Indeed we've reorganised the playground app abit. I think it's friendlier now and more accommodating to  PR's and additional e2e tests.

**Comment by Pushplaybang** [comment]
@guyca awesome, will check it out.
