### ISSUE TITLE
[v2][Android] Navigation.mergeOptions doesn't update/toggle sideMenu

### ISSUE THREAD

**Issue by el-lsan** [wix/react-native-navigation#4584]
### Issue Description

I'm using topBar's leftButtons to toggle sidemenu drawer and everything works as expected on IOS but on android it fails without throwing any error/warning.

### Steps to Reproduce / Code Snippets / Screenshots

```
static options() {
  return {
    topBar: {
      leftButtons: [
        {
          id: 'menu',
          icon: MYICON,
          color: 'white',
        },
      ],
    },
  };
}

constructor(props) {
  super(props);
  Navigation.events().bindComponent(this);
  this.isSideDrawerVisible = false;
}

navigationButtonPressed({ buttonId }) {
  if (buttonId === 'menu') {
    this.isSideDrawerVisible = !this.isSideDrawerVisible;
    Navigation.mergeOptions('root', {
      sideMenu: {
        left: {
          visible: this.isSideDrawerVisible,
        },
      },
    });
  }
}
```

---
### Environment
* React Native Navigation version: `^2.5.1`
* React Native version: `0.57.8`
* Platform(s) (iOS, Android, or both?): `Android`
* Device info (Simulator/Device? OS version? Debug/Release?): `Simulator` `8.1.0` (`Debug and Release`)

**Comment by wzhou40555** [comment]
I am having the same problem. I am on React Native Navigation version: ^2.5.0.

**Comment by StasDoskalenko** [comment]
You could take a try my modifications https://github.com/StasDoskalenko/react-native-navigation/blob/060c70e964cf9c95d195a0ced6ceca2acbb7e410/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/sidemenu/SideMenuController.java

**Comment by ashleydw** [comment]
Did you make a PR for your changes @StasDoskalenko?

**Comment by StasDoskalenko** [comment]
@ashleydw no cuz I've removed event emitting class from the side menu. Probably some users will be affected because of this.

**Comment by phathuynh5519** [comment]
> ### Issue Description
> I'm using topBar's leftButtons to toggle sidemenu drawer and everything works as expected on IOS but on android it fails without throwing any error/warning.
> 
> ### Steps to Reproduce / Code Snippets / Screenshots
> ```
> static options() {
>   return {
>     topBar: {
>       leftButtons: [
>         {
>           id: 'menu',
>           icon: MYICON,
>           color: 'white',
>         },
>       ],
>     },
>   };
> }
> 
> constructor(props) {
>   super(props);
>   Navigation.events().bindComponent(this);
>   this.isSideDrawerVisible = false;
> }
> 
> navigationButtonPressed({ buttonId }) {
>   if (buttonId === 'menu') {
>     this.isSideDrawerVisible = !this.isSideDrawerVisible;
>     Navigation.mergeOptions('root', {
>       sideMenu: {
>         left: {
>           visible: this.isSideDrawerVisible,
>         },
>       },
>     });
>   }
> }
> ```
> 
> ### Environment
> * React Native Navigation version: `^2.5.1`
> * React Native version: `0.57.8`
> * Platform(s) (iOS, Android, or both?): `Android`
> * Device info (Simulator/Device? OS version? Debug/Release?): `Simulator` `8.1.0` (`Debug and Release`)

This issue still happens on Android
```
react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    Memory: 3.32 GB / 15.83 GB
  Binaries:
    Node: 16.13.2 - D:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.4 - D:\Roaming\npm\yarn.CMD
    npm: 6.14.5 - D:\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      Android NDK: 18.1.5063045
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.8.30907.101 (Visual Studio Professional 2019)
  Languages:
    Java: 14.0.1 - /cygdrive/c/Program Files/OpenJDK/jdk-14.0.1/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2
    react-native: 0.67.2 => 0.67.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
