### ISSUE TITLE
showOverlay breaks react-native Animated animations

### ISSUE THREAD

**Issue by kiroukou** [wix/react-native-navigation#4590]
### Issue Description

I'm using an animated component to wrap some of my screens.
The animated component starts the animation on componentDidMount callback.

It's a pretty straightforward use of Animation, vertical Y sliding.

The code is working correctly if my screens is displayed using showModal, but NOT if I'm opening it with showOverlay (which is more what I would like to achieve).

### Environment
* React Native Navigation version: 2.4.0
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): iOS Simulator
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator ios 6s 11.3

**Comment by guyca** [comment]
Have you tried switching the animation start to `componentDidAppear`?

**Comment by kiroukou** [comment]
Hey @guyca ,
thanks for the input.  
So it is a bit better now, but not perfect, let me explain.

I can get a transform animation to work, but only if I'm using the  "useNativeDriver" set to true.  Sounds good me though.

But I can't manage to get the same animation code working on an opacity value..
I had to force the component update on animationChange, but not very sure this can be react-native-navigation related..

**Comment by kiroukou** [comment]
Ok now I'm sure the opacty thing had nothing to do with the lib.

Using componentDidAppear to start the animation did the trick to solve the issue for me.
Thanks !
