### ISSUE TITLE
Component [name] does not have a componentId

### ISSUE THREAD

**Issue by IL4Miy** [wix/react-native-navigation#4593]
### Issue Description

I followed all steps on https://wix.github.io/react-native-navigation/#/docs/Installing?id=ios and created the _index.js_ file like the tutorial describes.
Now `Navigation.registerComponent("Name", () => Main);` causes the error: 

> Component [Name] does not have a componentId

`Main` is a simple React component.

### Environment
* React Native Navigation version: 2.7.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone7 with iOS 12.1.2

**Comment by IL4Miy** [comment]
@JoseFMP I also tried to do it with cocoapods but it did not work.
Ended up not using this library. Instead I now use [FluidTransitions](https://github.com/fram-x/FluidTransitions) with React Navigation.

**Comment by JoseFMP** [comment]
Such a pity... I really want to use react-native-navigation because as opposed to React Navigation, it uses native APIs. But this issue is just blocking.

**Comment by CyberMew** [comment]
Encountered the same issue here while following the official documentation 🤣 . That workaround did not work for me. Looks like I will have to stick with `React-Navigation` for now.

**Comment by santaclauze** [comment]
Anything new regarding this. I have a new project, initialized with the react-native tutorial and I am trying to get `react-native-navigation` to work but it still fails.

```javascript
import { Navigation } from "react-native-navigation";
import App from './App';


Navigation.registerComponent(`FamilyMealOrganizer`, () => App);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      component: {
        name: "FamilyMealOrganizer"
      }
    }
  });
});

```
I get exactly the same error.

**Comment by asaharan** [comment]
I faced the same issue because I missed steps 3 and 3b from [Native Installation](https://wix.github.io/react-native-navigation/#/docs/Installing?id=native-installation) section.

**Comment by Desintegrator** [comment]
faced same issue (((

**Comment by danilobuerger** [comment]
If anybody is experiencing this issue with rnn v7 please open a new issue and provide a reproducible demo.

**Comment by juanjlunar** [comment]
> If anybody is experiencing this issue with rnn v7 please open a new issue and provide a reproducible demo.

Well I have an issue like this [#7440 ](https://github.com/wix/react-native-navigation/issues/7440).
