### ISSUE TITLE
Unable to resolve dependency for '...': Could not resolve project :react-native-navigation

### ISSUE THREAD

**Issue by jsphkm** [wix/react-native-navigation#4595]
### Issue Description

After carefully following the instructions in [https://wix.github.io/react-native-navigation/#/docs/Installing](url), I am getting these errors after completing step 4 for Android:

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :react-native-navigation.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :react-native-navigation.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :react-native-navigation.
Show Details
Affected Modules: app

WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: app

### Steps to Reproduce / Code Snippets / Screenshots

1. Add the following in `android/settings.gradle`
```
include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/lib/android/app/')
```
2. Make sure you're using the new gradle plugin, edit `android/gradle/wrapper/gradle-wrapper.properties`
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
```
3. Update `android/build.gradle`
```
buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 19
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url 'https://jitpack.io' }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```

4. Update project dependencies in `android/app/build.gradle`
```
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {...}
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    ...
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-navigation')
}
```

Sync project as necessary confirming that after step 4 the errors are produced

---
### Environment
* React Native Navigation version: 2.7.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):
* Android Studio 3.3
* Gradle 4.10.1
* Android Gradle plugin 3.3.0
* Android SDK Build Tools 28.0.3
* macOS Mojave 10.14.2

**Comment by jsphkm** [comment]
I have updated my first comment to reflect the question asked on [stackoverflow](https://stackoverflow.com/questions/54231555/unable-to-resolve-dependency-for-could-not-resolve-project-react-native).  I would appreciate it if you can reconsider supporting this issue, and perhaps be able to edit the installation guide, if needed.

**Comment by tiagoalexbastos** [comment]
I'm having the same problem.....

**Comment by jsphkm** [comment]
@tiagoalexbastos try ignoring the error and proceed to set up as instructed on the docs.  I was able to get rid of the error at step 7, but after having completed all the steps, the app builds successfully but does not launch in the emulator.  The emulator stays at the home screen.

**Comment by quangit1102** [comment]
> I'm having the same problem.....<

**Comment by mrquanghuy** [comment]
I have same in RN 0.6.4 and RNN v3

**Comment by ollydixon** [comment]
I'm using verison 1 still.

But I noticed if you include the project settings like this:

```
include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/lib/android')
include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/lib/android/app/')
```

It works.

I'm getting tired of constantly maintaining these RN projects though, the configuration is a nightmare.. just endless bugs.

**Comment by inf3rnus** [comment]
> I have same in RN 0.6.4 and RNN v3

Did you ever get this fixed? I'm trying to upgrade from RN 59 to RN 0.60.2 right now and it is *incredibly* frustrating.

**Comment by ollydixon** [comment]
@inf3rnus I created a new RN project in 0.60.2 and copied the PodFile stucture then adding my own. That seemed to work.

**Comment by CryceTruly** [comment]
> missingDimensionStrategy

Yes @ciawalsh, but the same problem here.

**Comment by maitrungduc1410** [comment]
> @inf3rnus @mrquanghuy - Have you guys added `missingDimensionStrategy "RNN.reactNativeVersion", "reactNative60"` to the `defaultConfig` in `app/build.gradle`?

Confirm it works by adding `missingDimensionStrategy`, my react native version `0.61.5`

Thanks
