### ISSUE TITLE
[V2][Android] Unable to come back from background

### ISSUE THREAD

**Issue by bensont1** [wix/react-native-navigation#4598]
### Issue Description

On Android, app is stuck on splash screen when app comes from background. This happens when a notification is pressed when outside the app but was previously launched successfully. ALSO happens when app is exited by `BackHandler.exitApp()` function of RN.

Killing the app and restarting would fix the stuck on splash screen issue. But shouldn't be stuck in the first place.

I'm using RNN V2 with no 3rd party splash screen packages.

Does anyone have a fix for this? I'm thinking its related to Android's onResume function within the RNN-V2 wrapper.

### Steps to Reproduce / Code Snippets / Screenshots
Open App
Press Android Back Button to send App to background (Code using `BackHandler.exitApp()`)
Press App icon to get back into App. App seems to reload then get stuck on Splash screen.

---
### Environment
* React Native Navigation version: 2.5.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Device, Debug & Release

**Comment by spacesuitdiver** [comment]
LOL troubleshooting this issue just now, will keep you posted if I find anything.

**Comment by bensont1** [comment]
@spacesuitdiver Thanks, I've tried to do some troubleshooting within the RNN code, looking at onResume function, but I'm not very familiar with Android development, so I was really just poking around blindly. 

I'm surprised no one else has reported this issue, kind of a big deal with deeplinks.

**Comment by spacesuitdiver** [comment]
@bensont1 commenting out this line of code at least allows for the <AppContainers> to remain for my application (in debugger). 

https://github.com/wix/react-native-navigation/blob/b0c8113243de2043b98442dd485c04b0422aa213/lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java#L69

Not sure where to go from here.

**Comment by spacesuitdiver** [comment]
probably can just trigger a `setRoot()` on app resume.

**Comment by bensont1** [comment]
Is the navigator getting destroyed when the app goes into the background?

**Comment by zheldRnaskan** [comment]
I'm having the same issue with the Author.

**Comment by j-schuster** [comment]
@zheldRnaskan did you ever find a fix for this?

**Comment by andrewsadowski** [comment]
I'm encountering this as well, but only on Android devices that are Android 8 and lower.  Anyone else have any luck?
