### ISSUE TITLE
[v2] How to custom animation for push

### ISSUE THREAD

**Issue by tiennguyen9988** [wix/react-native-navigation#4599]
### Issue Description

[v2] How to custom animation for Navigation.push method replace for slide left to right effect only ?

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: react-native-navigation
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by rubeus90** [comment]
Same here, push animation customisation doesn't seem to work on iOS.

I've defined custom animations for push, pop, showModal and dismissModal in `Navigation.setDefaultOptions()` as indicated in the documentations : 

```javascript
Navigation.setDefaultOptions({
    animations: {
        push: {
            content: {
                alpha: {
                    from: 0,
                    to: 1,
                }
            }
        },
        pop: {
            content: {
                alpha: {...}
            }
        },
        showModal: {
            alpha: {...}
        },
        dismissModal: {
            alpha: {...}
        }
    }
})
```

This worked perfectly on Android, but on iOS it doesn't seem to have any effect, all animations remain system defaults.

Someone knows if I've done something wrong ?

PS : I've tried to move the animation options from `Navigation.setDefaultOptions()` to `Navigation.push()`, but it produces the same results

**Comment by PatrickVanOverdijk2** [comment]
This is still an issue on RN v0.58.5 and RNN 2.12.0

**Comment by Pushplaybang** [comment]
this still seems to be an issue.

**Comment by el-lsan** [comment]
The current [documentation](https://wix.github.io/react-native-navigation/#/docs/styling?id=customizing-screen-animations) is a bit confusing. 

`Supported only on Android` is just mentioned for one of the examples which is for `setRoot`'s animation however none of the commands animation is working for IOS.

Maybe it's better to put this note under the main title (`Animation properties`).

**Comment by renrizzolo** [comment]
I'm finding that defining custom animations as above will break pushing screens on **iOS 10**.
In my case the screen goes black. Changing device orientation will get the pushed screen to render again.
