### ISSUE TITLE
[v2] react-native-share-extension support

### ISSUE THREAD

**Issue by prabakarviji** [wix/react-native-navigation#4600]
### Issue Description

When trying to integrate sharing extension(https://github.com/alinz/react-native-share-extension)  with react-native-navigation, we are getting this issue

`com.example.extension.ExampleExtensionActivity cannot be cast to com.reactnativenavigation.NavigationActivity`

Can anyone please help us?

### Steps to Reproduce / Code Snippets / Screenshots

`com.example.extension.ExampleExtensionActivity cannot be cast to com.reactnativenavigation.NavigationActivity`

---
### Environment
* React Native Navigation version: 2.6.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Android 8.0 Debug

**Comment by hackdie** [comment]
you wont be able to use the navigation on ios since the app extension will run in some kind of sand box in the app you want to share de file. On android you need to create a custom activity and set it up with the intent to receive the kind of files you want
