### ISSUE TITLE
Running Detox build command shows following ERROR Using rnn

### ISSUE THREAD

**Issue by Lokendra-rawat** [wix/react-native-navigation#4601]
### Issue Description

we are trying to add detox to our project which uses rnnv2 and running the command <code> detox build --configuration android.emu.debug </code> throws following error
Issue recreated on this project  [https://github.com/Lokendra-rawat/rnn-detox/tree/master](https://github.com/Lokendra-rawat/rnn-detox/tree/master)
example application showing the error 

<pre>
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':detox:minReactNative44DebugCompileClasspath'.
> Could not resolve com.squareup.okhttp3:okhttp:3.4.1.
  Required by:
      project :detox
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp:3.11.0'
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp-ws:3.4.1' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.11.0' --> 'com.squareup.okhttp3:okhttp:3.11.0'

> Could not resolve com.squareup.okio:okio:1.9.0.
  Required by:
      project :detox
   > Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints: 
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okio:okio:1.14.0'
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.11.0' --> 'com.squareup.okio:okio:1.14.0'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp:3.11.0' --> 'com.squareup.okio:okio:1.14.0'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okio:okio' strictly '1.9.0' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 1.9.0
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okio:okio' strictly '1.9.0' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 1.9.0

> Could not resolve com.squareup.okhttp3:okhttp:3.4.1.
  Required by:
      project :detox
      project :detox > com.squareup.okhttp3:okhttp-ws:3.4.1
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp:3.11.0'
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp-ws:3.4.1' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.11.0' --> 'com.squareup.okhttp3:okhttp:3.11.0'

> Could not resolve com.squareup.okhttp3:okhttp:3.11.0.
  Required by:
      project :detox > com.facebook.react:react-native:0.57.8
      project :detox > com.facebook.react:react-native:0.57.8 > com.squareup.okhttp3:okhttp-urlconnection:3.11.0
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp:3.11.0'
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp-ws:3.4.1' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.11.0' --> 'com.squareup.okhttp3:okhttp:3.11.0'

> Could not resolve com.squareup.okio:okio:1.14.0.
  Required by:
      project :detox > com.facebook.react:react-native:0.57.8
      project :detox > com.squareup.okhttp3:okhttp:3.11.0
   > Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints: 
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okio:okio:1.14.0'
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.11.0' --> 'com.squareup.okio:okio:1.14.0'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp:3.11.0' --> 'com.squareup.okio:okio:1.14.0'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okio:okio' strictly '1.9.0' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 1.9.0
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okio:okio' strictly '1.9.0' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 1.9.0

> Could not resolve com.squareup.okhttp3:okhttp:3.10.0.
  Required by:
      project :detox > com.facebook.react:react-native:0.57.8 > com.facebook.fresco:imagepipeline-okhttp3:1.10.0
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp:3.11.0'
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp-ws:3.4.1' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.11.0' --> 'com.squareup.okhttp3:okhttp:3.11.0'
</pre>

### Steps to Reproduce / Code Snippets / Screenshots
Run <code> detox build --configuration android.emu.debug </code>

---
### Environment
* React Native Navigation version: 2.7.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): debug

**Comment by legrandelf** [comment]
I can confirm I've got the same error during android release build attempt.
It doesn't matter if minReactNative is set to 44 or 46, on that particular step the build fails.
The only way to make the build successful was to remove these:

```
minReactNative44Implementation 'com.squareup.okhttp3:okhttp:3.4.1'
minReactNative44Implementation 'com.squareup.okhttp3:okhttp-ws:3.4.1'

minReactNative46Implementation 'com.squareup.okhttp3:okhttp:3.6.0'
minReactNative46Implementation 'com.squareup.okio:okio:1.13.0'
```
from 'node_modules/detox/android/detox/build.gradle

But as you can guess - that's not a solution at all...

Also all the setup/configuration steps are there, nothing missed. It seems it's an issue with latest react-native version.

The same detox 10.0.2 works fine with older RN version (like 54 or 55).

**Comment by yogeshthanvi** [comment]
I am facing the same issue

**Comment by SparkleFaerieCoder** [comment]
Running into the same issue, only way to resolve the conflicts was to comment out

```
minReactNative44Implementation 'com.squareup.okhttp3:okhttp:3.4.1'
minReactNative44Implementation 'com.squareup.okhttp3:okhttp-ws:3.4.1'

minReactNative46Implementation 'com.squareup.okhttp3:okhttp:3.6.0'
minReactNative46Implementation 'com.squareup.okio:okio:1.13.0'
```

from 'node_modules/detox/android/detox/build.gradle

**Comment by taylorcoffelt** [comment]
I was getting the same issue with the `assembleAndroidTest` build on detox `12.1.1`. \
The solution for me was to upgrade detox to `12.1.4`
