### ISSUE TITLE
Bottom Tabs Ripple color

### ISSUE THREAD

**Issue by JohnnyDevX** [wix/react-native-navigation#4602]
So I'm using a bottom tabs with very dark color, close to dark - #0F0F21 and the ripple color when I click on a tab is nearly not visible.

When tabs are white, you can clearly see a gray, smooth and nice ripple effect.

Same with white back buttons on topBars. Ripple is hardly visible.

Is there a way to set ripple color?

**Comment by oxyii** [comment]
@JohnnyDevX did you solve this issue? I also need to configure ripple background color
