### ISSUE TITLE
modalPrestationStyle support

### ISSUE THREAD

**Issue by kiroukou** [wix/react-native-navigation#4603]
### Issue Description

I'm getting the following error while trying to use overCurrentContext modalPresentationStyle on iOS simulator.

From the documentation of react-native-navigation and Apple https://developer.apple.com/documentation/uikit/uimodalpresentationstyle 
this should be correct.

### Steps to Reproduce / Code Snippets / Screenshots
![capture d ecran 2019-01-18 a 18 17 09](https://user-images.githubusercontent.com/2912939/51402332-7754f900-1b4d-11e9-818c-3b3e56d393b0.png)
---
### Environment
* React Native Navigation version: 2.4.0
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): iOS Simulator
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator ios 6s 11.3

Any Idea please?

**Comment by cjroth** [comment]
Running into this as well.

**Comment by cjroth** [comment]
It looks like React Native itself doesn't support any more than these 4 presentation styles: https://github.com/facebook/react-native/blob/0.47-stable/React/Views/RCTModalHostViewManager.m#L20.

I don't understand how `overCurrentContext` was working previously.

**Comment by cjroth** [comment]
I was able to temporarily solve this by forcing React Native to support `overCurrentContext`. It'd be worth understanding why this isn't already supported before relying on it.

https://github.com/cjroth/react-native/commit/cd1e1c960b3fe02091a9ed0330f627ece537831d

**Comment by loris42** [comment]
Any updates on this ?
I am facing the same issue and it was working previously ...
Thanks !

**Comment by buskerone** [comment]
you can still use `overFullScreen` for having a semi transparent modal for example:
`layout: {
          backgroundColor: 'transparent',
        },
        modalPresentationStyle: 'overFullScreen',
        screenBackgroundColor: 'transparent',`

**Comment by yogevbd** [comment]
Can't reproduce in latest version.. Does this still happening for you in 2.17.0?

**Comment by smooJitter** [comment]
@yogevbd... how did you resolve this.   It's weird, because like the others have mentioned, it just happened out of the blue.   Suddenly, 'overCurrentContext' gives me an error, while the other options have no effect
