### ISSUE TITLE
Android Run Error

### ISSUE THREAD

**Issue by sachidanandam** [wix/react-native-navigation#4606]
Hi,
 I have added react native package but iam facing below errors. can any one help to fix these errors.

dependencies": {
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-elements": "^0.19.1",
    "react-native-gesture-handler": "^1.0.12",
    "react-native-navigation": "^2.7.1",
    "react-native-vector-icons": "^6.1.0",
    "react-navigation": "^3.0.9"
  },

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-navigation.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-navigation: None of the consumable configurations have attributes.

**Comment by Jonjoe** [comment]
Same here, bump!

**Comment by chriseteka** [comment]
Having same problem here.

**Comment by jinshin1013** [comment]
Make sure you have followed the guide in installing on Android. Seems like you have missed a step somewhere and did not include react-native-navigation in your gradle files.

**Comment by Adar-Li** [comment]
Having same problem here.

**Comment by jan-happy** [comment]
In my case a little '/' at the end made the difference:
<img width="1008" alt="slash" src="https://user-images.githubusercontent.com/695826/51611643-041dff00-1f20-11e9-9f0e-6cf21a5d32c9.png">

**Comment by songahlee** [comment]
Same problem here!!! 
I'm sure I have followed the guide in installing on Android in several times.
Please, help me....

**Comment by jinshin1013** [comment]
If you could provide a little more info, I could help out.

**Comment by songahlee** [comment]
I can't build in android studio.

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :react-native-navigation. |  
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :react-native-navigation. |  
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :react-native-navigation. |  
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve project :react-native-navigation. |  
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve project :react-native-navigation. |  



- package.json in my project
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.5",
    "react-native-navigation": "^2.12.0"
  },

- android studio gradleVersion : 4.7
(distributionUrl=https\://services.gradle.org/distributions/gradle-4.7-all.zip)

- android build.gradle
buildscript {
    ext {
        buildToolsVersion = "28.0.2"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

**Comment by jinshin1013** [comment]
Can you create a new react-native init project and try integrate RNN in there and share the project?

**Comment by songahlee** [comment]
I just created new react-native init project and installed until guide 4.
(https://wix.github.io/react-native-navigation/#/docs/Installing)

I can't build after '4 Update project dependencies in android/app/build.gradle.'

It's my source.
https://github.com/songahlee/RNN_test.git

**Comment by jinshin1013** [comment]
I've checked out your source code, but you haven't finished the whole process from step 5 - 8 which are the essential part of the installation process.

**Comment by songahlee** [comment]
Please check again.
I finished installation process except optional part. 
but the error is same.

**Comment by jinshin1013** [comment]
From the brief view, you are missing step 7 and 8. Please refer to the doc.

**Comment by songahlee** [comment]
Oh.... I'm sorry. It's work.

**Comment by guyca** [comment]
Closing, Thanks a lot @jinshin1013 🙇
