### ISSUE TITLE
Screen push/pop transition animation looks weird on Android

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#461]
### Issue Description

I saw that there were already quite a few issues reported against animations on Android and in general but wasn't sure if the behavior that I am experiencing is same as what other people have reported, probably because of my very limited knowledge with respect to animations. So, I just want to share what I am observing. When I push or pop a screen on Android, it appears as if the push screen appears with a transparent background, then the screen on which the new screen is pushed disappears leaving a white background and finally the pushed screen appears as expected. I have attached a small recording demonstrating this behavior. If I change tabs, then the transition happens from left-to-right or right-to-left. Below is how I start the app and push/pop a screen

```js
    Navigation.startSingleScreenApp({
        screen: {
          screen: 'TopTabsScreen',
          title: 'App',
          navigatorStyle: navigationStyles.navigatorStyle,
          topTabs: [
            {
              screenId: 'AlarmListScreen',
              title: 'Alarms'
            },
            {
              screenId: 'GroupListScreen',
              title: 'Groups'
            },
            {
              screenId: 'ContactListScreen',
              title: 'Contacts'
            }
          ]
        },
        appStyle: {
          selectedTopTabIndicatorColor: 'yellow',
          selectedTopTabIndicatorHeight: 5,
          selectedTopTabTextColor: 'yellow'
        },
        passProps: {},
        animationType: 'slide-down' // Tried 'fade' and 'none' with same effects
      });

     this.props.navigator.push({
        screen: 'NewAlarmScreen',
        title: 'New Alarm',
        animated: true
      })

    this.props.navigator.pop({animated: true})
```

Is it possible to not have this transparent effect when a screen is pushed/popped? It would be great to have the left-to-right and right-to-left affect like in top tabs but I read in some issues' comments that it is not possible with Android at the moment. If I can just get rid of the transparent effect for now, it would be great.

![android_screen_animation 1](https://cloud.githubusercontent.com/assets/7475133/20460305/cb7029cc-af04-11e6-98bd-538605ef246b.gif)

### Environment
* React Native Navigation version: 2.0.0.experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug

**Comment by guyca** [comment]
Hey @varungupta85 
Screens on Android have transparent backgrounds by default while on iOS we set the default background to be white if it's not specified.
You should set the background of your view in JS, and we will add an option to set default background in future version.

**Comment by varungupta85** [comment]
@guyca Thanks for the response. Setting the `backgroundColor` on the view fixes the problem. I have tried using `screenBackgroundColor` property suggested in one of the issues but I guess that only applies to iOS.

**Comment by guyca** [comment]
`screenBackgroundColor` was added in a PR which is not merged yet

**Comment by smhatre59** [comment]
Please merge the PR since this will greatly improve the app screen transition animations

**Comment by guyca** [comment]
@smhatre59 `screenBackgroundColor` is available on Android.
