### ISSUE TITLE
mergeOptions does not work for topBar when component is used on ios

### ISSUE THREAD

**Issue by ssorint** [wix/react-native-navigation#4613]
### 

I am trying to render top bar with 3 buttons and when one button is pressed, a textbox should appear in the top bar. This works but when I try to go back to the 3 buttons view, the top bar does not render the title correctly, the component I specified in the last step is still visible.

### Steps to Reproduce / Code Snippets / Screenshots

// Initial top bar
var initialListTopBar = {
    rightButtons: [
        {
            id: 'topbuttons.search',
            icon: Platform.OS == 'ios' ? require('../src/assets/ios/Search_White.png') : require('../src/assets/android/Search_White.png'),
            color: 'white'
        },
        {
            id: 'topbuttons.add',
            icon: Platform.OS == 'ios' ? require('../src/assets/ios/Add_White.png') : require('../src/assets/android/Add_White.png'),
            color: 'white'
        }
    ],
    leftButtons: [
        {
            id: 'topbuttons.menu',
            icon: Platform.OS == 'ios' ? require('../src/assets/ios/Menu_White.png') : require('../src/assets/android/Menu_White.png'),
            color: 'white'
        }
    ],
    background: {
        component: { name: 'navigation.HeaderTopBarBackground' }
    },
    elevation: 0,
    noBorder: true
};

// When I push the search button:
Navigation.mergeOptions('navigation.MainList', {
                topBar:
                {
                    title: {
                        component: {
                            name: 'navigation.TopBarSearch',
                            id: 'gigi'
                        },
                    },
                    rightButtons: [
                        {
                            id: 'topbuttons.cancelsearch',
                            text: 'Cancel',
                            color: 'white'
                        }
                    ],
                    leftButtons: []
                }
            });

// When I push the Cancel button
Navigation.mergeOptions('navigation.MainList', {
                topBar:
                {
                    title: {
                        text: '' // This works on Andoid but not iOS
                    },
                    rightButtons: [
                        {
                            id: 'topbuttons.search',
                            icon: Platform.OS == 'ios' ? require('../src/assets/ios/Search_White.png') : require('../src/assets/android/Search_White.png'),
                            color: 'white'
                        },
                        {
                            id: 'topbuttons.add',
                            icon: Platform.OS == 'ios' ? require('../src/assets/ios/Add_White.png') : require('../src/assets/android/Add_White.png'),
                            color: 'white'
                        }
                    ],
                    leftButtons: [
                        {
                            id: 'topbuttons.menu',
                            icon: Platform.OS == 'ios' ? require('../src/assets/ios/Menu_White.png') : require('../src/assets/android/Menu_White.png'),
                            color: 'white'
                        }
                    ]
                }
            });

---
### Environment
* React Native Navigation version: 2.5.2
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X 12.1 - Simulator

**Comment by retyui** [comment]
https://github.com/wix/react-native-navigation/issues/4625

**Comment by fantasywind** [comment]
#4502

**Comment by dcalhoun** [comment]
I experienced this issue this week. It is still relevant.

**Environment:**
- `react-native@0.57.4`
- `react-native-navigation@2.5.0`
- iOS 12.1

**Comment by enisinanaj** [comment]
Issue still persists

Environment:

react-native@0.59.3
react-native-navigation@2.16.0
iOS 12.1

**Comment by rener172846** [comment]
I have same issue, any solution?

**Comment by enisinanaj** [comment]
What I've noticed is that is sending for some reason empty params even though you set the passProps property.

I'll try to use the global state in redux to change these information instead of passing them with passProps

**Comment by enisinanaj** [comment]
My solution for this was to set an ID to the screens that had the issue and then register a `registerComponentDidAppearListener` event where i'm calling the merge options.

**Comment by FRizzonelli** [comment]
@enisinanaj I can confirm that calling mergeOptions on didAppear works. Still this is not a suitable solution. I don't want to add a listener in my code to call this on first appear (the components are first screens in a stack for each bottomTab)
Also this #4625 is already accepted but it's a big bug :( Any ETA on the possible fix? @yogevbd

**Comment by dcalhoun** [comment]
I believe this is still an active, relevant issue.

**Comment by FRizzonelli** [comment]
This shouldn't be closed :( also again linked to #4625 which is open from around 8 months. Any ETA guys? Or at least where we'd check to find a workaround!

**Comment by enisinanaj** [comment]
This seems to be pretty much fixed in the newer releases. I'm not experiencing the issue anymore since upgrading. try that.
