### ISSUE TITLE
side menue animation ended event available?

### ISSUE THREAD

**Issue by patricktresp** [wix/react-native-navigation#4614]
### Issue Description
I created a topBarButton which toggles the visibility of the sideMenu

```
static options(passProps) {
    return {
      topBar: {
        title: {
          text: "Home"
        },
        leftButtons: {
          id: "menuButton",
          icon: require("./../signin.png")
        }
      }
    };
  }
```

Now when i click on the the leftButton

```
navigationButtonPressed({ buttonId }) {
    switch (buttonId) {
      case "menuButton":
        this.toggleSideMenu();
        break;
      default:
    }
  }


  toggleSideMenu() {
    this.isSideDrawerVisible = !this.isSideDrawerVisible;

    Navigation.mergeOptions(this.props.componentId, {
      sideMenu: {
        left: {
          visible: this.isSideDrawerVisible
        }
      }
    });
  }
```
the sideMenue appears and disappears as desired.

Now i have the issue, that the area of the screen that holds the leftbutton is clickable and closes the sidemenu on click without changing the value 'isSideDrawerVisible' to false.

I was thinking to listen to the event like "animationEnded" to set the value again to false.
Is this even possible?

Which approach would be the best? I do need that leftButton to show users where to tap to get to the menu and of course i do need it to behave correctly. I somehow did not search for correct terms to find an example?
![ezgif com-optimize](https://user-images.githubusercontent.com/1619156/51497977-349d5600-1dc5-11e9-8797-390f17921a06.gif)

---
### Environment
* React Native Navigation version: 2.5.1
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator - Debug version

**Comment by retyui** [comment]
Reproduced  in the 2.12 ver.
