### ISSUE TITLE
TopBar alignment 

### ISSUE THREAD

**Issue by mauricioscotton** [wix/react-native-navigation#4619]
### Issue Description
TopBar default properties does not change text alignment.
I've pushed into stack a screen with a title, and by default the title is centralized, which is a behaviour that I'm not expecting.
![image](https://user-images.githubusercontent.com/34411735/51538341-eaf64f00-1e48-11e9-9133-44f7e02f0ca1.png)

I've tried to set one of the default properties as described here:
https://wix.github.io/react-native-navigation/#/docs/styling?id=common-options
It has accepted color:'red', but alignment:(center/left/right) it hasn't...
![image](https://user-images.githubusercontent.com/34411735/51538555-7ff94800-1e49-11e9-8b78-d2f165ec0af7.png)

After this, I've tried to add a subtitle to check how are things over there...
![image](https://user-images.githubusercontent.com/34411735/51539061-eb8fe500-1e4a-11e9-96b3-818eb5112881.png)
This was the surprise:
![image](https://user-images.githubusercontent.com/34411735/51539079-f9de0100-1e4a-11e9-9a5e-fa21830f1f8a.png)
It does works for subtitle!

Am I missing something? 

### Steps to Reproduce / Code Snippets / Screenshots
```js
export default class ForgotPasswordScreen extends React.Component {
    static get options() {
        return {
            topBar: {
                title: {
                    text: I18n.t('screens.forgotPassword'),
                    alignment: 'right',
                    color: 'red',
                },
            },
        };
    }
........
```

---
### Environment
* React Native Navigation version:  2.5.2
* React Native version:  0.57.8
* Platform(s) (iOS, Android, or both?):  Android by now.
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator(8.1)+Real Device(7.0) - Debug

**Comment by retyui** [comment]
I this prop support only 2 value `center` and `fill` on Android

https://github.com/wix/react-native-navigation/blob/b0c8113243de2043b98442dd485c04b0422aa213/lib/android/app/src/main/java/com/reactnativenavigation/parse/Alignment.java#L6-L15

**Comment by mauricioscotton** [comment]
Well, neither Fill or removing the property had make it go to left.
Any suggestion?

**Comment by pushpanjalip** [comment]
I thick there is no default option to align Navbar Title left or right. It is by default centered. But I have used
 `options: {
                        topBar: {
                            title: {
                               component:{
                                  name: 'NavHeader'
                                }
                              },
}`
I have created NavHeader.js component and also registered it as 
`Navigation.registerComponent('NavHeader', () => NavHeader);`

NavHeader.js
```
import React from 'react';
import {  View, Text } from 'react-native';

export default navHeader = props => {
    return(
        <View style={styles.container}><Text>Institiute</Text></View>      
    );
}
```
You can customize header title as you want by using title component option.


<img width="374" alt="screenshot 2019-01-29 at 23 52 01" src="https://user-images.githubusercontent.com/21329772/51946215-31d3de00-2421-11e9-86bf-1119ce76f7ee.png">

**Comment by mauricioscotton** [comment]
> I thick there is no default option to align Navbar Title left or right. It is by default centered. But I have used
> `options: { topBar: { title: { component:{ name: 'NavHeader' } }, }`
> I have created NavHeader.js component and also registered it as
> `Navigation.registerComponent('NavHeader', () => NavHeader);`
> 
> NavHeader.js
> 
> ```
> import React from 'react';
> import {  View, Text } from 'react-native';
> 
> export default navHeader = props => {
>     return(
>         <View style={styles.container}><Text>Institiute</Text></View>      
>     );
> }
> ```
> You can customize header title as you want by using title component option.
> 
> <img alt="screenshot 2019-01-29 at 23 52 01" width="374" src="https://user-images.githubusercontent.com/21329772/51946215-31d3de00-2421-11e9-86bf-1119ce76f7ee.png">

Thanks for replying mate!
I was thinking about it, but I want to avoid this type of customizations as I would like to keep it as a standard and focus on developing the other parts which are more important... =D 
Although, There is a funny thing...
Is just that screen that have this problem..
The others are okay!

Have a look:
![image](https://user-images.githubusercontent.com/34411735/52048865-48268a80-2544-11e9-899e-79fa93b540eb.png)
![image](https://user-images.githubusercontent.com/34411735/52048877-4f4d9880-2544-11e9-9535-7a22e8712598.png)

What do you think!

**Comment by mauricioscotton** [comment]
No one?

**Comment by JamieBort** [comment]
This is still an issue. Any solution yet? Any docs you can share with me before I reinvent the wheel by hunting the internet? Much thanks if so!

**Comment by guibas741** [comment]
I am facing the same problem with iOS

**Comment by dylanjongbloed** [comment]
same

**Comment by AudereSemper** [comment]
I'm in the same position too.

**Comment by rodrigodiasf1984** [comment]
Inside the Stack.Screen options use ` headerTitleAlign: 'center',`! 

OBS: I've used the react-navigation 5

Ex: 

`import React from 'react';
 import { NavigationContainer } from '@react-navigation/native';
 import { createStackNavigator } from '@react-navigation/stack';
 import Home from './pages/Home/index';

 const Stack = createStackNavigator();

 function Routes() {
   return (
     <NavigationContainer>
       <Stack.Navigator>
         <Stack.Screen
           name="Home"
           component={Home}
           options={{
            title: 'Loja',
            headerStyle: {
              backgroundColor: '#7159c1',
            },
            headerTitleAlign: 'center',
            headerTintColor: '#fff',
            headerBackTitleVisible: false,
          }}
        />
      </Stack.Navigator>
    </NavigationContainer>
   );
 }

export default Routes;`

Before: 
[https://drive.google.com/open?id=1s7FW9eo1aGbGyXYk34_IDbSrYKToKeab](url)

after:
[https://drive.google.com/open?id=1QY6pNfpD69BcSOHSjEETvMVdkSga3R8B](url)

I hope this might be helpful!
