### ISSUE TITLE
Unable to show two light boxes in quick succession in iOS

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#462]
### Issue Description

I am using a light box in iOS to show progress dialogs boxes in the app. If an operation is under way, I show a light box with a spinner and a message. If the operation succeeds, the light box is dismissed. If the operation fails, I want to show an error message to the user for which I dismiss the current light box and show a different light box with the error message right away but the second light box doesn't appear. I was able to reproduce it in the example app as well. This is how I show the light box in the example app `FirstTabScreen.js` file to reproduce the problem

```js
// Show a light box, the dismiss the light box after three seconds and show a new one right away.
  onLightBoxPress() {
    this.props.navigator.showLightBox({
      screen: "example.LightBoxScreen",
      style: {
        backgroundBlur: "dark"
      },
      passProps: {
        greeting: 'hey there'
      },
    });

    setTimeout(() => {
      this.props.navigator.dismissLightBox()
      this.props.navigator.showLightBox({
        screen: "example.LightBoxScreen",
        style: {
          backgroundBlur: "dark"
        },
        passProps: {
          greeting: 'how do you do'
        },
      });
    }, 3000)
  }
```

With the above call, the first light box disappears after three seconds but the second light box doesn't appear. I tried wrapping the second call to `showLightBox` in a `setImmediate` method without any help. Wrapping the second call to another `setTimeout` with a delay of at least 500 ms solves the problem. If the I set the timeout to say 100 ms, then also I don't see the second light box. The below set of calls work with an extra timeout

```js
// Show the second light box after some delay after dismissing the first light box
  onLightBoxPress() {
    this.props.navigator.showLightBox({
      screen: "example.LightBoxScreen",
      style: {
        backgroundBlur: "dark"
      },
      passProps: {
        greeting: 'hey there'
      },
    });

    setTimeout(() => {
      this.props.navigator.dismissLightBox()
      setTimeout(() => {
        this.props.navigator.showLightBox({
          screen: "example.LightBoxScreen",
          style: {
            backgroundBlur: "dark"
          },
          passProps: {
            greeting: 'how do you do'
          },
        });
      }, 500)
    }, 3000)
  }
```

I am not sure if this is a limitation of the OS or if this is something that can be fixed within the library. For Android, I am using modals to show the progress/error dialog boxes and with modals, it works fine.

### Environment
* React Native Navigation version: 2.0.0.experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug

**Comment by varungupta85** [comment]
hi @DanielZlotin , can you suggest any workarounds/alternate solution that I can use for the time being for my use case which is to show a progress dialog box during some operation and then an error message when the operation fails? Thanks!

**Comment by guyca** [comment]
You can display a single `LightBox` and control what it displays renders with your state.
render a progress bar by default, and if an error occurs set `error: true` in your state and in your `render` function change what you render accordingly.

**Comment by Renattynha** [comment]
Hi @guyca, this problem can be solved in a near future? Or we have to use a workaround?
