### ISSUE TITLE
interceptTouchOutside doesn't work on iOS

### ISSUE THREAD

**Issue by paubins** [wix/react-native-navigation#4622]
### Issue Description

Setting interceptTouchOutside to true/false doesn't make a difference for iOS; the UIWindow overlay always intercepts the touch and never passes it through to the underlying main React window.

### Steps to Reproduce / Code Snippets / Screenshots

```js
    Navigation.showOverlay({
      component: {
        name: 'Player',
        passProps: {
          songs: [this.props]
        },
        options: {
          overlay: {
            interceptTouchOutside : false/true // doesn't matter it will always intercept
          }
        }
      }
    });
```

---
### Environment
* React Native Navigation version: 2.7.1
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug

**Comment by kfroemming** [comment]
Same issue

**Comment by rsokz** [comment]
+1

**Comment by abdullah-sr** [comment]
works for me. make sure there's nothing wrapping your overlay that would block touches. Pass  `pointerEvent="none"` as a prop to your `View` if you do.

**Comment by yfuks** [comment]
Had the same issue.
In my case i also use [react-native-popup-dialog](https://github.com/jacklam718/react-native-popup-dialog) in my project.

I don't know why/how but downgrading [react-native-popup-dialog](https://github.com/jacklam718/react-native-popup-dialog) to `0.11.46` fixed the issue in my case.

Hope it help.

## Environment
- React Native Navigation version: `2.13.0`
- React Native version: `0.57.8`
- Platform : `iOS`

**Comment by fadak0828** [comment]
> Had the same issue.
> In my case i also use [react-native-popup-dialog](https://github.com/jacklam718/react-native-popup-dialog) in my project.
> 
> I don't know why/how but downgrading [react-native-popup-dialog](https://github.com/jacklam718/react-native-popup-dialog) to `0.11.46` fixed the issue in my case.
> 
> Hope it help.
> 
> EDIT: It was probably caused by [react-native-root-siblings](https://github.com/magicismight/react-native-root-siblings) (a new dependencies in `react-native-popup-dialog`) but i'm not sure.
> Feels like there is some kind of conflict between `RNN` and this lib.
> 
> ## Environment
> * React Native Navigation version: `2.13.0`
> * React Native version: `0.57.8`
> * Platform : `iOS`

I had same issue,
In my case, i used react-native-root-toast.
And it also include react-native-root-siblings.

So i remove toast library, and it works!

Thanks!

**Comment by danielgindi** [comment]
Fixed in https://github.com/magicismight/react-native-root-siblings/pull/47

**Comment by elsurudo** [comment]
> works for me. make sure there's nothing wrapping your overlay that would block touches. Pass `pointerEvent="box-none"` as a prop to your `View` if you do.

Worth adding to the docs IMO.
