### ISSUE TITLE
[iOS] LargeTitle noBorder gets overridden 

### ISSUE THREAD

**Issue by jinshin1013** [wix/react-native-navigation#4624]
### Issue Description
I've got two screens with `largeTitle: { visible: true }` but first with border and second with noBorder. Both screens have scrollview to see both LargeTitle and normal Title. On the initial setRoot of Screen1, the border is shown on both LargeTitle and normal Title. Once Screen2 is pushed, the border disappears which is expected. However as Screen2 is popped, Screen1 does not show border on LargeTitle but the normal Title shows border. Both code and a gif are attached for reference. While recording I also realised that the normalTitle become non-bold after popping from Screen2.

The doc mentions that
> `options` object can be passed when the screen is originally created; can be defined `per-screen` by setting static options(passProps) on the screen component

so on popping to previous screen, the previous options should be reapplied. 

### Steps to Reproduce / Code Snippets / Screenshots

```js
//Screen 1
export class Screen1 extends React.Component<Props> {
  static options(): Options {
    return {
      title: { text: 'Screen 1' },
      largeTitle: { visible: true },
    }
  }
  ...
}

//Screen 2
export class Screen2 extends React.Component<Props> {
  static options(): Options {
    return {
      noBorder: true,
      title: { text: 'Screen 1' },
      largeTitle: { visible: true },
    }
  }
  ...
}
```

![largetitle](https://user-images.githubusercontent.com/17612922/51575500-125b2380-1efe-11e9-99c6-5e49e450ec84.gif)

---
### Environment
* React Native Navigation version: 2.7.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both simulator and device

**Comment by ganlub** [comment]
I believe I am experiencing something like this as well, what happens if you explicitly specify `noBorder: false` on Screen1? Or if you set it on `Navigation.setDefaultOptions`?

**Comment by jinshin1013** [comment]
Tried bunch, every other style seem to be working just fine but only the border on LargeTitle gets overridden.

**Comment by jinshin1013** [comment]
Not stale. noBorder issue have been resolve, however the font of the title become *not bold*.
