### ISSUE TITLE
[IOS][2.7.1] Bug mergeOptions when megre topBar.title.component and then merge topBar.title.text

### ISSUE THREAD

**Issue by retyui** [wix/react-native-navigation#4625]
### Issue Description
When you apply custom topBar component
```js
Navigation.mergeOptions(state.componentId, {
    topBar: {
      visible: true,
      title: { component: { name: 'MAIN_SCREEN_CUSTOM_TOP_BAR' } },
    },
  });
```
And then apply text topBar:

```js
  Navigation.mergeOptions(state.componentId, {
    topBar: {
      visible: true,
      title: { text: 'Test text top Bar' },
    },
  });
```

Nothing will happen on IOS

### Code Snippets
Run this code: [LIVE EXAMPLE GIST](https://gist.github.com/retyui/1c4dbda8a8e741d1e7edc3f2d3f73fcd)
First press: "set Text topBar"
Then press: "set Custom topBar"
And you will see the topBar didn't change! (on Android this case works) 

---
### Environment
React Native Navigation version: v2.7.1
React Native version: 0.56.0
Platform(s) (iOS, Android, or both?): IOS only
Device info: Simulator\Debug

**Comment by retyui** [comment]
Still, reproduce in `RNN 2.13.1`
Any ideas to fix this bag @guyca?

**Comment by retyui** [comment]
Also reproduce in `RNN 2.14.0`

**Comment by retyui** [comment]
@yogevbd Hi 
Could you view this problem?

**Comment by retyui** [comment]
Up

**Comment by retyui** [comment]
up

**Comment by JB-CHAUVIN** [comment]
Same problem goes for me...

**Comment by guyca** [comment]
@FRizzonelli Isn't this the issue you're looking into?

**Comment by FRizzonelli** [comment]
@guyca Exactly! I've the fix I think, gonna send a PR this afternoon!

**Comment by FRizzonelli** [comment]
@retyui @guyca I've submitted PR #5398 , it's working on my build (I'm on v2 currently, but I think problem is the same for v3 also).
