### ISSUE TITLE
[v2] [Android/iOS] topBar content is not visible with bottomTabs layout

### ISSUE THREAD

**Issue by LRNZ09** [wix/react-native-navigation#4627]
### Description

`topBar` content (text, etc) is not visible using a `bottomTabs` layout within a `stack`.
Related issue: https://github.com/wix/react-native-navigation/issues/4050

### Snippet

```jsx
import React, { Component } from 'react'
import {
    Dimensions,
    Platform,
    ScrollView,
    StyleSheet,
    Text,
} from 'react-native'
import { Navigation } from 'react-native-navigation'

const instructions = Platform.select({
    ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
    android:
        'Double tap R on your keyboard to reload,\n' +
        'Shake or press menu button for dev menu',
})

class Screen extends Component {
    static options() {
        return {
            bottomTab: {
                text: 'Screen',
            },
            topBar: {
                background: {
                    color: 'darkgrey',
                },
                title: {
                    text: 'Screen',
                },
                largeTitle: {
                    visible: true,
                },
            },
        }
    }
    render() {
        return (
            <ScrollView contentContainerStyle={styles.container}>
                <Text style={styles.welcome}>Welcome to React Native!</Text>
                <Text style={styles.instructions}>
                    To get started, edit App.js
                </Text>
                <Text style={styles.instructions}>{instructions}</Text>
            </ScrollView>
        )
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'lightgrey',
        minHeight: Dimensions.get('window').height * 2,
    },
    welcome: {
        fontSize: 20,
        textAlign: 'center',
    },
    instructions: {
        textAlign: 'center',
        color: 'slategrey',
    },
})

Navigation.registerComponent('Screen', () => Screen)

Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setRoot({
        root: {
            stack: {
                children: [
                    {
                        bottomTabs: {
                            children: [
                                {
                                    component: {
                                        name: 'Screen',
                                    },
                                },
                            ],
                        },
                    },
                ],
            },
        },
    })
})
```

### Environment

* React Native Navigation version: 2.7.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by jfrolich** [comment]
I have the same issue. It seems like if you put bottomTabs inside of a stack, it does not show a title for the bottom tabs (other options do work like setting the background color), however when changing stack to another screen the title works again (for that screen).

**Comment by vascome** [comment]
Has anyone found workaround to solve it?

**Comment by jfrolich** [comment]
I wrote a custom bottomtabs component (also for other reasons)

**Comment by LRNZ09** [comment]
Another related issue https://github.com/wix/react-native-navigation/issues/4363

**Comment by JohnBRTS** [comment]
Any tips or suggestions on working around this? Not being able to put a back button/title/anything in the topBar for bottomTabs layouts is kind of frustrating

**Comment by Pungsnigel** [comment]
Still having this issue on latest version of RNN. Has anyone found a solution? Seems to work fine on iOS.

**Comment by tyuwan** [comment]
Also, have the same issue. Did anyone get any workaround?

**Comment by bitlab-code** [comment]
Same issue here.
Fixed follow this on [stackoverflow](https://stackoverflow.com/a/54917819)
This issue should not be closed, if it's not a bug it's needs to be documented in a better way

**Comment by paulbargaoanu** [comment]
> Fixed from this hint on [stackoverflow](https://stackoverflow.com/a/54917819)

This fixed it for me. Thanks, @bitlab-code!
Basically what you need to do for a tab layout is set each tab component within its own stack. This means that the `children` array of the of the `bottomTabs` will be filled with stack items instead of components directly.
