### ISSUE TITLE
[FEAT] Statically switching tabs

### ISSUE THREAD

**Issue by MaxMaes** [wix/react-native-navigation#4628]
### Issue Description

I have a screen with 4 tabs, but upon selecting the last tab I need to hide the tabbar so the screen kind of appears as an overlay. When I close that screen, I need to navigate back to the previously selected tab.

In my current setup, I store the previously selected screen and want to switch the tab using mergeOptions. But when I use mergeOptions, the tabbar is still hidden on the other screen. So, ok,  can make it visible for that screen again when I also set it to visible in the mergeOptions, which works. But when I go back to my 'overlay tab', the tabbar doesn't hide.

I have a specific static options setup for each of my tab screens, so it is very tedious to be working with mergeOptions for switching tabs.

Would it be possible to add a top level API for selecting a tab, eg Navigation.selectTabIndex and/or Navigation.selectTabId where the statically declared options of the screen are applied upon opening said screen?

### Environment
* React Native Navigation version: 2.7.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by MaxMaes** [comment]
This has been added by @RemyLivewall, not stale?

**Comment by guyca** [comment]
Closing, see https://github.com/wix/react-native-navigation/pull/4739#issuecomment-468293356
