### ISSUE TITLE
passProps with number cause exception

### ISSUE THREAD

**Issue by monzy613** [wix/react-native-navigation#463]
### Issue Description

use passProps with number cause exception
(https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

```objc
passProps: {
  index: 10,
}
```
![image](https://cloud.githubusercontent.com/assets/12622268/20471574/f571bb8e-afed-11e6-9df2-cf83eabd0861.png)

---
### Environment
* React Native Navigation version: @next
* React Native version: 0.35
* Platform(s) (iOS, Android, or both?):iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS Simulator 10.1

**Comment by monzy613** [comment]
I tried {}, bool, all cause exception... I can only pass in string with passProps?

**Comment by guyca** [comment]
@monzy613 afaik All types are supported. You didn't fill out the details regarding your issue. It will help us if you do that.

   > React Native Navigation version: FILL THIS OUT
React Native version: FILL THIS OUT
Platform(s) (iOS, Android, or both?): FILL THIS OUT
Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by monzy613** [comment]
@guyca thank u, I'v edited the issue above
