### ISSUE TITLE
[V2] Android back button always closes app with bottomTabs

### ISSUE THREAD

**Issue by ErikMelton** [wix/react-native-navigation#4630]
### Issue Description

When using a bottomTabs nested inside of a stack when you set your root, the hardware back button on Android will always close the when you push components to the stack, and then attempt to back out. The topBar back button works perfectly however.

I believe this is an issue in [this function](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java#L74) of NavigationActivity, as when I override it in my own MainActivity and leave the overridden function empty, the expected behavior of navigating back to the bottomTabs (the first item in the stack) occurs.

### Steps to Reproduce / Code Snippets / Screenshots
[Afflicted function](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java#L74)

```js
  Navigation.setRoot({
    root: {
      stack: {
        id: 'home-stack',
        children: [
          {
            bottomTabs: {
              id: 'home-tabs',
              children: [
                {
                  stack: {
                    children: [
                      {
                        component: {
                          ...
```

---
### Environment
* React Native Navigation version: 2.7.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel 3, Debug + Release, Android 9

**Comment by Stacyadam** [comment]
I don't think its an issue with NavigationActivity. This is just how the back button works natively on an Android device.

If you want to customize the behavior though React Native gives you access to a BackHandler object where you could add an event listener and navigate them according to your apps needs.
https://facebook.github.io/react-native/docs/backhandler

**Comment by ErikMelton** [comment]
I don't think you're right; if I override the BackHandler, (like I do for Modals), it will still close the app, but when I re-open the app it will have ran whatever I put in the BackHandler.

**Comment by Stacyadam** [comment]
Gotcha. I misunderstood the issue. I can't see your entire root object but it looks like you have it wrapped in a single stack. Have you tried configuring it closer to the bottomTabs example in the docs? Without wrapping the bottomTabs object in a single stack.
https://wix.github.io/react-native-navigation/#/docs/layout-types?id=tab-based-app-with-passprops-example

**Comment by ErikMelton** [comment]
Haha, no worries :)

Yeah, I've tried that as well, the same issue arises. I didn't put my entire root object in because it's quite lengthy, (4 tabs w/a lot of configuration), but I'm able to reproduce it with only one or two tabs.

**Comment by guyca** [comment]
Hey @ErikMelton, can you please PR a failing detox e2e test?

**Comment by phantom1299** [comment]
Have the same issue, having bottomTabs as root, I have overcome it for now by adding a backhandler to every page, but thats just ugly

**Comment by phantom1299** [comment]
Never mind, my problem was this line in MainActivity.java:

`@Override public void invokeDefaultOnBackPressed() { moveTaskToBack(true); }`

which I had added while trying to solve another issue.
Removing that solved this
