### ISSUE TITLE
[v2] setStackRoot Animations not working

### ISSUE THREAD

**Issue by Stacyadam** [wix/react-native-navigation#4631]
### Issue Description

Trying to customize the setStackRoot animation to transition the screen from right to left instead of bottom to top. None of the documented screen animations appear to be working on setStackRoot though.

### Steps to Reproduce / Code Snippets / Screenshots

![2019-01-23_14-49-22](https://user-images.githubusercontent.com/33630849/51637389-45fb7500-1f21-11e9-9521-06062e9cb37f.gif)

```js
Navigation.setDefaultOptions({
	animations: {
		setStackRoot: {
			x: {
				from: 1000,
				to: 0,
				duration: 300
			}
		}
	}
});
```

---
### Environment
* React Native Navigation version: 2.7.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by aaronisme** [comment]
facing the same issue, whether this function supported?

**Comment by cvarley100** [comment]
Also experiencing the same issue

**Comment by cvarley100** [comment]
@Stacyadam See https://github.com/wix/react-native-navigation/issues/3495#issuecomment-402437006

**Comment by Stacyadam** [comment]
@cvarley100 thanks for linking that comment. I tried directly setting both `push` and `setStackRoot` from `.setStackRoot`s options as suggested but am still getting a bottom to top animation.

**Comment by cvarley100** [comment]
@Stacyadam This is all I need to do to prevent the screen animating in.

```navigator.setStackRoot('languageSetup', {
            animations: {
                push: {
                    enable: false,
                },
            },```

**Comment by exentrich** [comment]
The issue is still actual in latest RNN. I can only disable animation, but customization is not working.

**Comment by exentrich** [comment]
Reopen this issue please!
Probably this [pull request](https://github.com/wix/react-native-navigation/pull/4865) will fix this issue

**Comment by adeca** [comment]
As far as I could tell, the iOS code is using `animations.setStackRoot` to determine if the animation is enabled, but it is using `animations.push` to customize the animation. 

The PR referenced above does not fix this, it only updates the Typescript interfaces, but does not change the native code.

In my opinion this  inconsistency should be fixed by either using `setStackRoot` or `push` for **both** determining if it's enabled **and** customizing.

**Comment by exentrich** [comment]
I tried to customize `push` animations, and they are ignored for `setStackRoot`

**Comment by adeca** [comment]
Is this the format you used?
```
animations: {
  push: {
    content: { ... }
  }
}
```

**Comment by exentrich** [comment]
Yes of course

**Comment by huuthinh245** [comment]
i have the same issue setStackRoot animations isn't working on ios

**Comment by Dawqss** [comment]
why it's closed if it's not working?

**Comment by exentrich** [comment]
In RNN 3 setStackRoot for iOS is working, but only if you specify `animations` when you call `setStackRoot`. 

If you specify `animations` in `setDefaultOptions` they ignored
