### ISSUE TITLE
How can I customize bottomTab looks like this.

### ISSUE THREAD

**Issue by suupham2506** [wix/react-native-navigation#4638]
### Issue Description

I would like to customize bottomTab in RNN, but I dont know how to do it. Anyone helps me????

### Steps to Reproduce / Code Snippets / Screenshots
![image](https://user-images.githubusercontent.com/28852565/51740264-1f2a7380-20c6-11e9-8ff6-50462bdbeef1.png)

**Comment by m0dawood** [comment]
i have a problem also in my project as i need to make the bottom tabs  background as gradient 
so what i do  is creating a component  called footer and set it in my pages and hide the default tabs
in my component i used this to switch tabs

>  goToPage(index) {
        Navigation.mergeOptions(this.props.componentId, {
            bottomTabs: {
                currentTabIndex: index
            }
        })
    }

**Comment by m0dawood** [comment]
you can also manually set your pages ids while initializing the tabs so that you can detect which tab you are in like that

>  bottomTabs: {
      children: [
        {
          stack: {
            id: "servicesTab",
            children: [{ component: { id: "tab0", name: "ServicesTab" } }],
            options: {
              bottomTab: { text: "الخدمات", icon: require('./src/assets/services.png') }
            }
          }
        },
