### ISSUE TITLE
[Android] handle screenBackgroundColor (temp fix)

### ISSUE THREAD

**Issue by DanielZlotin** [wix/react-native-navigation#464]
See #437

**Comment by Antonides** [comment]
For me its not working on Android. I tested it on 3 different devices. When i try iOS its working perfect. did i do something wrong?

**Comment by guyca** [comment]
@Antonides Please provide more information. Hard to know if you're doing something wrong if I don't know what you're doing.

**Comment by Antonides** [comment]
I have a SingleScreenApp. 
React-native: 0.37.0. 
React-native-navigation: 2.0.0-experimental.142

I use the following code:

```js
this.props.navigator.resetTo({
  title: 'Title',
  navigatorStyle: {
    navBarBackgroundColor: '#ff00ff',
    screenBackgroundColor: '#ff00ff',
  },
  screen: Screen,
  animated: false,
});
```

in iOS it works on Android i get white flashing page.

**Comment by guyca** [comment]
@Antonides I'll look into it.
