### ISSUE TITLE
RNN v2 latest version ios gesture(swipe) problem

### ISSUE THREAD

**Issue by Haqverdi** [wix/react-native-navigation#4642]
![cant open swipe element](https://user-images.githubusercontent.com/24776121/51786465-139a8380-217e-11e9-87e3-54f75690cb37.gif)

### if use side menu layout in rnn v2 cant open swipe element on screen

cant open swiper element when using side menu layout rnn v2 gesture capturing at all screen thats why it blocking other gesture touches i think, but on android its working well

### Steps to Reproduce / Code Snippets / Screenshots

 ```js
export const goToScreen = screen => {
  Navigation.setRoot({
    root: {
      sideMenu: {
        left: {
          component: {
            name: 'SideBar',
            passProps: {
              activeScreen: screen,
            },
          },
        },
        center: {
          stack: {
            children: [
              {
                component: {
                  name: screen,
                  options: {
                    animations: {
                      push: {
                        waitForRender: true,
                      },
                    },
                  },
                },
              },
            ],
          },
        },
      },
    },
  });
};
```

```js
// merge options here
Navigation.mergeOptions(componentId, {
    sideMenu: {
      left: {
        visible: true,
      },
      right: {
        visible: false,
        enabled: false,
      },
    },
  });
```

---
### Environment
* React Native Navigation version: 2.8.0
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both

## thank all in advance

**Comment by Squall410** [comment]
the fix:
#4649

**Comment by Haqverdi** [comment]
> the fix:
> #4649

Thanks)) i am already converted project from rnn to react-navigation))
