### ISSUE TITLE
Error on Android device with RN 0.58.1

### ISSUE THREAD

**Issue by Alekseyideas** [wix/react-native-navigation#4646]
### Issue Description

**When I run -  npm run android --stacktrace has an error:**

> Task :react-native-navigation:compileReactNative57_5DebugJavaWithJavac FAILED
/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/utils/NoOpPromise.java:7: error: NoOpPromise is not abstract and does not override abstract method reject(String,String,Throwable,WritableMap) in Promise
public class NoOpPromise implements Promise {

/node_modules/react-native-navigation/lib/android/app/src/reactNative57_5/java/com/reactnativenavigation/react/SyncUiImplementation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

---
### Environment
* React Native Navigation version: 2.8.0
* React Native version: 0.58.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by Tahirou-DIABATE** [comment]
I'm also getting the same error.

**Comment by Alekseyideas** [comment]
I returned to RN 0.57.8. And all work

**Comment by Tahirou-DIABATE** [comment]
Yes it's what i dit too; thanks

**Comment by Angry-Potato** [comment]
seeing the same issue

**Comment by retyui** [comment]
You can find tmp decision here: https://github.com/wix/react-native-navigation/issues/4639#issuecomment-457600144

**Comment by arpansharma7474** [comment]
Hello Everyone, I managed to solve this error using following steps :
1. First navigate to /node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/utils/ and open NoOpPromise.java.
2. As is clear from the error this file doesn't override required methods from Promise class.
Replace this file with the following file or manually write the required methods.

```
package com.reactnativenavigation.utils;

import com.facebook.react.bridge.*;

import javax.annotation.Nullable;

public class NoOpPromise implements Promise {
    @Override
    public void resolve(@Nullable Object value) {

    }

    @Override
    public void reject(String code, String message) {

    }

    @Override
    public void reject(String code, Throwable e) {

    }

    @Override
    public void reject(String code, String message, Throwable e) {

    }

    @Deprecated
    @Override
    public void reject(String message) {

    }

    @Override
    public void reject(Throwable reason) {

    }

    /*Extra Methods*/

    @Override
    public void reject(String code, String message, Throwable e, WritableMap a) {

    }

   @Override
    public void reject(Throwable e, WritableMap a) {

    }

   @Override
    public void reject(String code, String message, WritableMap a) {

    }

   @Override
    public void reject(String code, Throwable e, WritableMap a) {

    }

   @Override
    public void reject(String code, WritableMap a) {

    }
}
```
3. Now run `npm run android` and these issues will disappear.

Enjoy Coding 👍

**Comment by Alekseyideas** [comment]
Hi! Great work))) 
But I think it`s a bad solution, because after updating dependencies this error will return ((((
It must be a PR to RNN and then we can updated))) 
But, now I will work with stable version RN 0.57.8

**Comment by Tahirou-DIABATE** [comment]
@Alekseyideas   right.

**Comment by nugoo1** [comment]
@arpansharma7474

Thank you, ur a life saver!!!!

**Comment by deecewan** [comment]
@Alekseyideas you can use something like [`patch-package`](https://github.com/ds300/patch-package)

**Comment by atoami** [comment]
@guyca I also have this issue with version react-native 0.58.3 and react-native-navigation 2.8.0.0
Can we resolve this issue asap?

**Comment by cinder92** [comment]
is this error fixed on 2.11.0?

**Comment by guyca** [comment]
Yes

**Comment by krookten14** [comment]
> 
> 
> Hello Everyone, I managed to solve this error using following steps :
> 
>     1. First navigate to /node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/utils/ and open NoOpPromise.java.
> 
>     2. As is clear from the error this file doesn't override required methods from Promise class.
>        Replace this file with the following file or manually write the required methods.
> 
> 
> ```
> package com.reactnativenavigation.utils;
> 
> import com.facebook.react.bridge.*;
> 
> import javax.annotation.Nullable;
> 
> public class NoOpPromise implements Promise {
>     @Override
>     public void resolve(@Nullable Object value) {
> 
>     }
> 
>     @Override
>     public void reject(String code, String message) {
> 
>     }
> 
>     @Override
>     public void reject(String code, Throwable e) {
> 
>     }
> 
>     @Override
>     public void reject(String code, String message, Throwable e) {
> 
>     }
> 
>     @Deprecated
>     @Override
>     public void reject(String message) {
> 
>     }
> 
>     @Override
>     public void reject(Throwable reason) {
> 
>     }
> 
>     /*Extra Methods*/
> 
>     @Override
>     public void reject(String code, String message, Throwable e, WritableMap a) {
> 
>     }
> 
>    @Override
>     public void reject(Throwable e, WritableMap a) {
> 
>     }
> 
>    @Override
>     public void reject(String code, String message, WritableMap a) {
> 
>     }
> 
>    @Override
>     public void reject(String code, Throwable e, WritableMap a) {
> 
>     }
> 
>    @Override
>     public void reject(String code, WritableMap a) {
> 
>     }
> }
> ```
> 
>     1. Now run `npm run android` and these issues will disappear.
> 
> 
> Enjoy Coding 👍

Still got nothing tho, I still got the same error

**Comment by Tahirou-DIABATE** [comment]
Bonjour,
Je viens de signer la pétition "HBO: Let's not be ungrateful, GOT was great
and it's ended period." et je souhaitais savoir si vous voudriez nous aider
en ajoutant votre signature.

Notre objectif est d'atteindre 100 signatures et nous avons besoin de plus
de soutiens. Pour en savoir plus et pour signer, c'est ici:

http://chng.it/4Hbz8PZMKf

Merci!
Tahirou
