### ISSUE TITLE
[V2][iOS] Modal backButton 

### ISSUE THREAD

**Issue by yfuks** [wix/react-native-navigation#4656]
### Issue Description

Hello,

first of all thanks for this library !

Just a quick question, is there a way on **iOS** to have a native back Button on a Modal ?
Tell me if i'm wrong but for the moment we can only provide a custom component to have a back button like **Android**.

It would be really usefull to have a native back button.

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.showModal({
    stack: {
        children: [{
            component: {
                name: component,
                options: {
                    topBar: {
                        visible: true,
                        backButton: {
                              visible: true,
                        },
                    },
                },
            },
        }],
    },
});
```
| Android                                                                                                                   | iOS                                                                                                                       |
| --------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------- |
| <img title="iOS" src="https://i.imgur.com/u7Q21Qr.png"> | <img title="Android" src="https://i.imgur.com/XthO3to.png"> |

Ps: Right now in my configuration pressing the back button on **android** do nothing.

---
### Environment
* React Native Navigation version: 2.7.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Iphone XR, Debug

**Comment by jinshin1013** [comment]
The root component in the stack cannot have back button natively I believe unless you use a custom back button?

**Comment by yfuks** [comment]
You are right i discuss with an iOS native developer and he tell me that's there are no back button on your first view of the stack with [UINavigationController](https://developer.apple.com/documentation/uikit/uinavigationcontroller) (I think ?).

Seems like a somewhat *logic* behavior !
