### ISSUE TITLE
alignment title topbar work not well on android

### ISSUE THREAD

**Issue by suupham2506** [wix/react-native-navigation#4659]
### Issue Description

I tried to set topbar title to be centered but it's unexpected. the position of topbar title is randomly located after go back.

### Steps to Reproduce / Code Snippets / Screenshots
![screenshot_1548837857](https://user-images.githubusercontent.com/28852565/51969032-f3cccd80-24a5-11e9-8aaf-fb9f60c6c7b1.png)
![screenshot_1548837519](https://user-images.githubusercontent.com/28852565/51969036-f4fdfa80-24a5-11e9-81ab-28a50020331d.png)

---
### Environment
* React Native Navigation version: 2.7.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by StasDoskalenko** [comment]
The fix: https://github.com/wix/react-native-navigation/pull/4674

**Comment by RemyLivewall** [comment]
I am using topbar -> title -> alignment: 'center' inside my default options, but the title still doesn't look centered. When there is a back button it is more to the center, but without buttons it is pinned to the left.

**Comment by adybuciuman** [comment]
@RemyLivewall I have the same problem did you manage to fix it?

**Comment by RemyLivewall** [comment]
> @RemyLivewall I have the same problem did you manage to fix it?

The fix worked for me. Before that I used a custom title component to work around the alignment issue.

**Comment by adybuciuman** [comment]
> > @RemyLivewall I have the same problem did you manage to fix it?
> 
> The fix worked for me. Before that I used a custom title component to work around the alignment issue.

ok. Unfortunatetly I have to use component. I set the component in background and with some modification I can make it work. But this work around requires more code for pushed modal

**Comment by JamieBort** [comment]
I am not able to use a custom component. Is there an alternative solution?

**Comment by cpbange** [comment]
JamieBort could learn how to code.
