### ISSUE TITLE
undefined is not an object (evaluating '_reactNativeNavigation.default.push')

### ISSUE THREAD

**Issue by EspacesTempsStudio** [wix/react-native-navigation#4662]
### Issue Description

Hi,

I just updated RNN to version 2 and I'm stuck with my first push

I get an error :

`undefined is not an object (evaluating '_reactNativeNavigation.default.push') `

I guess my issue is related to `this.props.componentId` but I couldn't find any help in the official doc since i think my setting is correct.

or perhaps it's coming from a wrong call to the stack since I never use the id property set in App.js

I'm also wondering if I have to provide an id manually for each screen or, as it is said in the doc it will be done automatically by RNN

if someone can guide me, I'm a bit lost -_-

### Code Snippets

**App.js**
```js
import { Navigation } from 'react-native-navigation';
import { Provider } from 'react-redux';

import LandingScreen from './src/screens/Landing/Landing';
import AuthScreen from './src/screens/Auth/Auth';

import configureStore from './src/store/configureStore';

import strings from './src/global/strings';

const store = configureStore();

// Landing
Navigation.registerComponentWithRedux(strings.screens.screenLanding, () => LandingScreen, Provider, store);

// Auth
Navigation.registerComponentWithRedux(strings.screens.screenAuth, () => AuthScreen, Provider, store);


// Start App

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      stack:{
        id:"appStack",
        children: [
          {
            component: {
              name: strings.screens.screenLanding,
              options: {
                topBar:{
                  title:{
                    text:"Welcome"
                  }
                }
              }
            }
          }
        ]
      },

    }
  });
});
```

**Landing.js**
```js
import React, { Component } from 'react';
import { View, Button } from 'react-native';

import Navigation from 'react-native-navigation';

import strings from '../../global/strings';

class Landing extends Component {

    goToScreen = (screenName) => {
        Navigation.push(this.props.componentId, {
            component: {
                name: screenName
            }
        })
    }

    render() {
        return (
            <View>
                <Button
                    title="Connexion"
                    onPress={() => this.goToScreen(strings.screens.screenAuth.toString())}
                />
            </View>
        )
    }
}

export default Landing;
```

---
### Environment
* React Native Navigation version: ^2.0.0
* React Native version: react-native: 0.57.8
* Platform(s) : Android
* Device info : Android Simulator

**Comment by jinshin1013** [comment]
In `Landing.js`, you should be importing Navigation like this,
`import { Navigation } from 'react-native-navigation`

**Comment by EspacesTempsStudio** [comment]
ew... such a mess for some forgotten braces ^^
thank you very much @jinshin1013

**Comment by rawrmaan** [comment]
@EspacesTempsStudio Don't forget to close the issue if your problem is resolved 😄
