### ISSUE TITLE
'com.android.support:recyclerview-v7' has different version for the compile (23.0.1) and runtime (26.1.0) classpath. You should manually set the same version via DependencyResolution

### ISSUE THREAD

**Issue by mirette922** [wix/react-native-navigation#4663]
What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:recyclerview-v7' has different version for the compile (23.0.1) and runtime (26.1.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
3 actionable tasks: 1 executed, 2 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: gradlew.bat installDebug

Error: Command failed: gradlew.bat installDebug
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at runOnAllDevices (E:\xampp\htdocs\ContrackFM\node_modules\react-native\local-cli\runAndroid\runAndroid.js:299:19)
    at buildAndRun (E:\xampp\htdocs\ContrackFM\node_modules\react-native\local-cli\runAndroid\runAndroid.js:135:12)
    at isPackagerRunning.then.result (E:\xampp\htdocs\ContrackFM\node_modules\react-native\local-cli\runAndroid\runAndroid.js:65:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ContrackFM@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ContrackFM@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2019-01-30T12_37_05_483Z-debug.log

**Comment by nickkuijpers** [comment]
Same here
