### ISSUE TITLE
'Bool' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by danieljvdm** [wix/react-native-navigation#4665]
I get this error if I try to use v2 with Swift. The issue is that the RNN iOS SDK defines its own (in ObjC) `Bool` as well as `Dictionary` which cause ambiguous type lookups in Swift while trying to use the native `Bool`. This is immediately evident in your AppDelegate where all the functions export `-> Bool` and you have to rename them all to `-> Swift.Bool`.

This screams bad design and, to me, it seems like this was written in Objective C with disregard to what the types were named in Swift. 

A proposed solution is to prefix the custom types with `RNN`. I'm happy to open a PR for this if this is acceptable and I'm not missing something here.

**Comment by danieljvdm** [comment]
Here's a SO link to a similar issue with a HelloSign SDK: https://stackoverflow.com/questions/51952394/date-is-ambiguous-for-type-lookup-in-this-context

**Comment by andrejcesen** [comment]
A bit of naming refactoring is needed to this lib work in Swift, hence forking, and that's pretty tedious. Could you update us on the reasoning behind naming, or is it up to a PR to align it with Swift nomenclature?
