### ISSUE TITLE
registerCommandListener does not detect pop event

### ISSUE THREAD

**Issue by samcampisi** [wix/react-native-navigation#4666]
### Issue Description

I'm trying to execute some actions when the Navigation.pop event occurs. For this, I wanted to use:

```
Navigation.events().registerCommandListener((name, params) => {
      console.warn('name', name, 'params', params);
});
```

But I noticed two problems. The first one is that events like "push" and "mergeOptions" don't appear until I enter the screen in which I want to track the events for the second time.

The second problem (and the most important to me) is that the "pop" event is not being tracked at all, unlike "push" or "mergeOptions".

I attach an illustration of the problems here:

![ezgif-3-545893c50ce0](https://user-images.githubusercontent.com/42766924/52051992-795b8680-2555-11e9-8818-064d60e00739.gif)

We can see that the first time I go to "Next Screen" nothing gets printed, even though I added the registerCommandListener as mentioned above in this component (specifically in componentDidMount).

We can also see that whenever this component is popped, nothing gets printed. Furthermore, the listener prints more times than expected from the second time "Next Screen" is opened and so on.

Am I missing something to track the pop event (and other events in general)?

---
### Environment
* React Native Navigation version: 2.8.0
* React Native version: 0.57
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X, Xiaomi Mi A1

**Comment by samcampisi** [comment]
In the meantime, as a workaround, I'm using a custom left button made out of a custom component to override the default back button.
I pretty much followed this issue #3699 to create said button.

**Comment by codazzo** [comment]
I can reproduce the issue exactly as described.

**Comment by pribeh** [comment]
Running into the same issue here https://github.com/wix/react-native-navigation/issues/4900

**Comment by pribeh** [comment]
In release mode, running 2.17.0 or higher, neither pop or dismissModal seem to be detected by registerCommandListener.

**Comment by ahwatts** [comment]
I'm also seeing this on iOS, with RNN 2.11.0 (I haven't updated in a while, will try that when the RN 0.59 support is released). The pop events seem only to be emitted if triggered programmatically; if you poke the automatically-added back button, the pop event is not emitted. I am seeing dismissModal events, but I'm also triggering them programmatically.

**Comment by pribeh** [comment]
@ahwatts is this working in release mode for you?

**Comment by pribeh** [comment]
Can any of the maintainers look into this? I've tried to figure it out but in release mode registerCommandListener doesn't appear to work for us at all.

**Comment by pribeh** [comment]
Here's our simple code which determines when an overlay (dashboard) displays which we employ in our mainstore.js. In debug mode it works some of the time for pop and dismissmodal but in release mode it never seems to fire. 

```
		// fires when a navigation command is run
		Navigation.events().registerCommandListener(action((name, params) => {
			// hide dashboard when a screen or modal is pushed
			if (name === "push" || name === "showModal") {
				DashboardStore.dashboardIsVisible = false

			/*	// set timeout if command fails to complete within 1 second
				clearTimeout(this.commandListenerTimeout)
				this.commandListenerId = params.commandId
				this.commandListenerTimeout = setTimeout(() => {
					runInAction(() => {
						DashboardStore.dashboardIsVisible = true
					})
				}, (2000));*/
			} else if ((name === "pop" || name === "dismissModal") && !params.componentId.startsWith("noDash")) {
				DashboardStore.dashboardIsVisible = true
			}
		}));

		// fires when a navigation command is completed
		Navigation.events().registerCommandCompletedListener(action(({ commandId, completionTime, params }) => {
			if (commandId === this.commandListenerId) {
				// if command with set timeout completed, clear timeout
				clearTimeout(this.commandListenerTimeout)
				DashboardStore.dashboardIsVisible = false
			}
		}));
```

**Comment by pribeh** [comment]
I believe this may be resolved in both dev and release mode with the latest update.
