### ISSUE TITLE
[boilerplate] RNN V2 + MobX + Firebase starter kit

### ISSUE THREAD

**Issue by alexwasner** [wix/react-native-navigation#4669]
I made a starter kit for V2 for anyone that wants to use Firebase and/or MobX instead of Redux. Others opened tickets for this, so I'm not sure the normal process. Maybe @guyca can add it to the readme if people find it useful https://github.com/alexwasner/react-native-mobx-firebase-starter

**Comment by retyui** [comment]
The best logo :+1: 
![sorry](https://raw.githubusercontent.com/alexwasner/react-native-mobx-firebase-starter/master/src/assets/images/logo.png)

**Comment by ItsNoHax** [comment]
@alexwasner Looks good, I suggest you create a PR to include this in the docs' showcases/starter kits.

Going to close this issue as I'm trying to clean up issues. Please don't forget to create a PR!
