### ISSUE TITLE
How to restart the app?

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#467]
When user do logout, how to restart the app?
Im using redux, so I will change the state of the app, but I need to invoke a method from the navigator to tell him to go the app class, how that possible? 

### Environment
* React Native Navigation version: 2.0 exp
* React Native version: 0.35
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): OS 5.0

**Comment by guyca** [comment]
@Jaafar-abusair Just call `startApp` with your new root (LoginScreen ?)

**Comment by Jaafar-abusair** [comment]
Where i can find a documentation for this? is it this.props.navigator.startApp();?

**Comment by guyca** [comment]
I mean `startSingleScreenApp` or `startTabBasedApp` as described [here](https://github.com/wix/react-native-navigation/wiki/Usage#step-1---change-the-way-your-app-starts)

**Comment by bsonntag** [comment]
@guyca I believe your link was moved [here](https://wix.github.io/react-native-navigation/#/usage).
