### ISSUE TITLE
SideMenu redux problem

### ISSUE THREAD

**Issue by andrei0807** [wix/react-native-navigation#4670]
### Issue Description

[ENTER DESCRIPTION HERE]

### Steps to Reproduce / Code Snippets / Screenshots

When I change reducer's value, don't render function in side menu component,
I used "this.props.user.price", 
<img width="840" alt="screen shot 2019-02-01 at 10 29 07 am" src="https://user-images.githubusercontent.com/32348752/52099028-5d66ec00-260c-11e9-9383-e39dd6cbf4fc.png">
<img width="844" alt="screen shot 2019-02-01 at 10 29 19 am" src="https://user-images.githubusercontent.com/32348752/52099029-5dff8280-260c-11e9-8895-7cb7b6003856.png">

---
### Environment
* React Native Navigation version: 2.2.5
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?):  ios
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by retyui** [comment]
Do provide store for any

**Comment by retyui** [comment]
And I also know the problem with `react-redux@6 and react-native@0.56` 
You should use previous version `yarn add react-redux@5`
