### ISSUE TITLE
[v2] app relaunch problem

### ISSUE THREAD

**Issue by adoniscoder** [wix/react-native-navigation#4672]
### Issue Description

On Android when I press on hardware back and app goes to background and when I bring it to foreground again it will be relaunched and not continues on the page which I have been on it.

### Steps to Reproduce / Code Snippets / Screenshots
<img width="967" alt="screen shot 2019-02-01 at 2 15 00 
pm" src="https://user-images.githubusercontent.com/13381026/52118568-e4778c80-262b-11e9-9770-4490f630caaf.png">

---

### Environment
* React Native Navigation version: 2.8.0
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung j7, android 8, seen on both release and debug

**Comment by JohnnyDevX** [comment]
Related: https://github.com/wix/react-native-navigation/issues/4644

**Comment by ItsNoHax** [comment]
Hey @adoniscoder 

Please refer to this: https://github.com/wix/react-native-navigation/issues/4255#issuecomment-441207411

Basically your registerAppLaunchedEventListener must always be available.

**Comment by Andre-JierongLuo** [comment]
@ItsNoHax 

I am still having this issue. Could you please show us an example (index.js && app.js) of how to make registerAppLaunchedEventListener always be available? Thanks!

**Comment by ItsNoHax** [comment]
Uhm in this issue’s case this is standard Android behaviour, pressing back
button on the root screen exits your app

**Comment by Andre-JierongLuo** [comment]
@ItsNoHax 

OMG!!!! My bad... I don't use Android a lot... 

Thanks!
