### ISSUE TITLE
[Android] Top bar absolutely positioned on first Navigation.push 

### ISSUE THREAD

**Issue by devey** [wix/react-native-navigation#4673]
### Issue Description

When the app is first opened and navigation is triggered:
```
    Navigation.push(this.props.componentId, {
      component: {
        name: screenName,
        passProps,
      },
    });
```
the first time a screen is pushed the `RNN` top bar appears to be absolutely positioned and so the content of the screen is hidden under it. Doesn't happen all upcoming navigation triggers. 

### Steps to Reproduce / Code Snippets / Screenshots

On `Android`, push a screen with a header and some mock text content in the page. On first open header should be absolute and hide content.

---
### Environment
* React Native Navigation version: `2.0.2544`
* React Native version: `0.55.3`
* Platform(s) (iOS, Android, or both?): `Android`
* Device info (Simulator/Device? OS version? Debug/Release?): ` Google Nexus 5 6.0.0 API 23 debug mode`

**Comment by ItsNoHax** [comment]
Please attach a gif reproducing the problem.

**Comment by 1fabiopereira** [comment]
I have the same problem.
