### ISSUE TITLE
[v2] ShowModal silently failing iOS. `[self topPresentedVC]` returning nil.

### ISSUE THREAD

**Issue by Reidweb1** [wix/react-native-navigation#4676]
### Issue Description

Version 2.8.0 showModal silently failing.

###

I'm trying to perform a very simple `showModal` call and the animation/ navigation simply doesn't execute.

Using break points I've found that on line 34 of `RNNModalManager.m` the value for `topVC` is `nil` meaning the `presentViewController` call will silently fail. Is there some piece of configuration I might be missing. Or could this be a bug with RNN failing to set/get the `rootViewController`?

I can perform pushes no problem - it's just an issue with `showModal`

Hopefully I'm overlooking something simple here.

Here is the component I'm using as the root (that is working properly):

```                                       
// I Registered the components
Navigation.registerComponent('Test', () => TestView)
Navigation.registerComponent('TestTwo', () => TestViewTwo)

// I set the root (and it appears as expected)
Navigation.setRoot({
    root: {
      stack: {
        children: [{
          component: {
            name: 'Test'
          }
        }]
      }
    }
  })


// Here is the Component I'm trying to call `showModal` from
export default class TestView extends React.Component<any, any> {

  constructor(props) {
    super(props)
    Navigation.events().bindComponent(this)
  }

  public componentDidMount() {
    console.log('***MOUNT***')
  }

  public render() {
    return (
      <TouchableOpacity style={ { flex: 1 } } onPress={ this.navigate }>
        <View style={{ flex: 1, backgroundColor: '#c3c3c3' }} />
      </TouchableOpacity>
    )
  }

  private navigate = () => {
  Navigation.showModal({
      component: {
        name: 'TestTwo'
      }
    })
  }

}  

// Here is the component I'm trying to show as a modal
export default class TestViewTwo extends React.Component<any, any> {

  constructor(props) {
    super(props)
    Navigation.events().bindComponent(this)
  }

  public componentDidMount() {
    console.log('***MOUNT TWO***')
  }

  public render() {
    return (
      <TouchableOpacity style={ { flex: 1 } } onPress={ this.navigate }>
        <View style={{ flex: 1, backgroundColor: '#9706e5' }} />
      </TouchableOpacity>
    )
  }

}
```

---
### Environment
* React Native Navigation version: 2.8.0
* React Native version: 0.55.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 8 simulator (iOS 12.1)

**Comment by Reidweb1** [comment]
Figured out what was going on. I still had the following lines in my AppDelegate.m left over from the old implementation.
```
self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
self.window.backgroundColor = [UIColor whiteColor];
```
Removing these fixed the issue.

**Comment by StasDoskalenko** [comment]
Yes. I believe this should be noted in the installation documentation.
