### ISSUE TITLE
Large title jumps to normal size whilst using pop gesture

### ISSUE THREAD

**Issue by kyle-ssg** [wix/react-native-navigation#4678]
### Issue Description

<img src="http://g.recordit.co/Qcd3n3ih6d.gif"/>

### Steps to Reproduce / Code Snippets / Screenshots

```
 component: {
            name: '/login',
            options: {
                topBar: {
                    title: {
                        text: 'Login',
                    },
                    largeTitle: {
                        visible: true,
                        fontSize: 30,
                        fontFamily: 'Helvetica',
                    },
                },
            },
```

---
### Environment
* React Native Navigation version: 2.8.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS

**Comment by olexh** [comment]
Write large title options in default options function and it will be work correctly, like this:

`Navigation.setDefaultOptions({
    topBar: {
      background: {
        color: 'black'
      },
      title: {
        color: 'white',
      },
      largeTitle: {
        visible: true,
        fontSize: 30,
        color: 'white',
        fontFamily: 'HelveticaBold',
      },
    },
  });`
