### ISSUE TITLE
[FR] iOS hideOnScroll - reveal whilst scrolling back up

### ISSUE THREAD

**Issue by kyle-ssg** [wix/react-native-navigation#4679]
### Issue Description

The hideOnScroll works well when scrolling down but doesn't when scrolling back up which makes it pretty unusable.

- You have to scroll up quite aggressively to actually get the navbar to appear again
- The navbar doesn't reveal whilst scrolling back up

<img src="http://g.recordit.co/idhRKMB1mC.gif"/>

---
### Environment
* React Native Navigation version: 2.8.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by manuhook** [comment]
Same issue but only when using **SafeAreaView**

**Comment by iShankarG** [comment]
facing the same issue, it there any quick fix. I'm using V3 alpha release.
