### ISSUE TITLE
RNN2  with Apollo client  setup

### ISSUE THREAD

**Issue by sandeepbalouria** [wix/react-native-navigation#4685]
I was hoping if anyone could help me with proper setup for RNN2 and ApolloProvider
Here is what I am doing 

1. Index.js 

`Navigation.events().registerAppLaunchedListener(()` => pushLoginScreen());

2. const withProvider = (Component) => {
    return class extends React.Component {
        static options = Component.options

        render() {
            return (
                <ApolloProvider client={client}>
                    <Rehydrated>
                        <Component {...this.props}/>
                    </Rehydrated>
                </ApolloProvider>
            );
        }
    };
};

3. Registering all screens
```
 const registerScreens =  () => {
    Navigation.registerComponent(LOGIN_SCREEN, () => withProvider(LoginScreen));
    Navigation.registerComponent(USER_PROFILE_SCREEN, () => withProvider(UserProfileScreen));
    Navigation.registerComponent(ACCOUNT_SETTINGS_SCREEN, () => withProvider(AccountSettingsScreen));
    Navigation.registerComponent(HOME_SCREEN, () => withProvider(HomeScreen));
    console.log("All Screens have been registered");
};
registerScreens();
```

3. From LoginScreen I am navigating to a tab view with 3 tabs (HOME,USER_PROFILE,ACCOUNT_SETTINGS) using 

Navigation.setRoot( <bottom tabs with three children)

I can see  contents for account settings tab but other tabs  say 

Loading...

Thanks in advance.

_Originally posted by @sandeepbalouria in https://github.com/wix/react-native-navigation/issues/1883#issuecomment-460148879_

**Comment by retyui** [comment]
https://wix.github.io/react-native-navigation/#/docs/third-party

**Comment by sandeepbalouria** [comment]
Thanks
