### ISSUE TITLE
[Android] Resets bottom tab badge value on modal dismiss

### ISSUE THREAD

**Issue by Zycon42** [wix/react-native-navigation#4689]
### Issue Description

We have bottom tabs, these tabs contain stacks. We set bottom badge on one of them using
```js
const badge = ...;
Navigation.mergeOptions(this.props.componentId, {
  bottomTab: {
    badge,
  },
});
```

but when we showModal and then dismiss modal, the badge is lost. Happens only on android.

I have found that this is because in BottomTabPresenter.java the method applyOptions is called when modal dismisses and it incorrectly clears the badge because the badge value is in fact in tabs grandchild where mergeOptions put it, but is empty in child (StackController). So mergeOptions should update parent options until it hits direct BottomTabController child or BottomTabPresenter should traverse whole child tree to find correct badge value.

#### Workaround

put id to your stack in setRoot like this:
```js
Navigation.setRoot({
  root: {
    bottomTabs: {
       children: [
         { /* ...first tab */ },
         {
            stack: {
              id: 'STACK_ID',  // Use custom id to refer to this controller later
              children: [ /* ...actual screen */ ],
              options: {
                bottomTab: {
                   /* ...text, icon etc. */
                }
              }
            }
         }
       ]
    }
  }
});
```

and then when seting badge programatically you have to set badge on BOTH the current screen and stack id.

```js
const badge = ...;
Navigation.mergeOptions(this.props.componentId, {
  bottomTab: {
    badge,
  },
});
Navigation.mergeOptions('STACK_ID', {
  bottomTab: {
    badge,
  },
});
```

### Steps to Reproduce / Code Snippets / Screenshots

* Have a root with bottom tabs that contain stacks
* Programatically set badge using `Navigation.mergeOptions` with stack child componentId. This correctly shows badge on correct bottom tab
* Push new screen on stack
* Show new modal using `Navigation.showModal`
* Dismiss opened modal using `Navigation.dismissModal(this.props.componentId)`
* Observe that bottom tab badge has disappeared

---
### Environment
* React Native Navigation version: 2.9.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung S8, Android 8, both

**Comment by Jazqa** [comment]
Similarly, if you only use the id of the stack the badge becomes visible only after you dismiss a modal

**Comment by msqar** [comment]
There's absolutely no way to reset the badge on android by using mergeOptions or what? please help?

**Comment by emilioheinz** [comment]
Stills a bug with that, we need to set the badge on the screen and the component in Android devices, in iOS it works fine.
