### ISSUE TITLE
NavigationActivity must implement PermissionAwareActivity

### ISSUE THREAD

**Issue by chaitanya0bhagvan** [wix/react-native-navigation#469]
### Issue Description

To target android API 23 and above, an activity must perform permission handling. React native already provides PermissionAwareActivity interface. NavigationActivity must implement PermissionAwareActivity to handle permissions. I can submit a PR to this effect.

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 2.0.0-experimental.142
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device

**Comment by shafy** [comment]
Would be awesome if we could have that 👍

**Comment by guyca** [comment]
merged. Thanks for the pr @chaitanya0bhagvan
