### ISSUE TITLE
iOS linker error: library not found for -ljschelpers

### ISSUE THREAD

**Issue by HolySamosa** [wix/react-native-navigation#4691]
### Issue Description

After upgrading React Native from 0.57.8 -> 0.5.8.3 and also upgrading Xcode to 10.1 (unfortunately, at the same time as the RN upgrade due to unrelated problems w/ the upgrade), I now receive the following error when my iOS project builds RNN:

```
ld: library not found for -ljschelpers
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Here's the linker invocation:
```
Ld /Users/jeremy/Library/Developer/Xcode/DerivedData/MyPath-bwhssvdsbkvifjenbwvdkpzlqahk/Build/Products/Debug-iphonesimulator/ReactNativeNavigationTests.xctest/ReactNativeNavigationTests normal x86_64 (in target: ReactNativeNavigationTests)
    cd /Users/jeremy/Developer/source/MyPath-React/node_modules/react-native-navigation/lib/ios
    export IPHONEOS_DEPLOYMENT_TARGET=10.3
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk -L/Users/jeremy/Library/Developer/Xcode/DerivedData/MyPath-bwhssvdsbkvifjenbwvdkpzlqahk/Build/Products/Debug-iphonesimulator -L/Users/jeremy/Developer/source/MyPath-React/node_modules/react-native-navigation/lib/ios -F/Users/jeremy/Library/Developer/Xcode/DerivedData/MyPath-bwhssvdsbkvifjenbwvdkpzlqahk/Build/Products/Debug-iphonesimulator -F/Users/jeremy/Developer/source/MyPath-React/node_modules/react-native-navigation/lib/ios -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -filelist /Users/jeremy/Library/Developer/Xcode/DerivedData/MyPath-bwhssvdsbkvifjenbwvdkpzlqahk/Build/Intermediates.noindex/ReactNativeNavigation.build/Debug-iphonesimulator/ReactNativeNavigationTests.build/Objects-normal/x86_64/ReactNativeNavigationTests.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mios-simulator-version-min=10.3 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/jeremy/Library/Developer/Xcode/DerivedData/MyPath-bwhssvdsbkvifjenbwvdkpzlqahk/Build/Intermediates.noindex/ReactNativeNavigation.build/Debug-iphonesimulator/ReactNativeNavigationTests.build/Objects-normal/x86_64/ReactNativeNavigationTests_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -lc++ -ObjC -framework XCTest -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/jeremy/Library/Developer/Xcode/DerivedData/MyPath-bwhssvdsbkvifjenbwvdkpzlqahk/Build/Intermediates.noindex/ReactNativeNavigation.build/Debug-iphonesimulator/ReactNativeNavigationTests.build/ReactNativeNavigationTests.xctest-Simulated.xcent -lcxxreact -ljschelpers -lRCTActionSheet -lRCTAnimation -lRCTGeolocation -lRCTImage -lRCTLinking -lRCTNetwork -lRCTSettings -lRCTText -lRCTVibration -lRCTWebSocket -lReact -lOCMock -lyoga -lReactNativeNavigation -Xlinker -dependency_info -Xlinker /Users/jeremy/Library/Developer/Xcode/DerivedData/MyPath-bwhssvdsbkvifjenbwvdkpzlqahk/Build/Intermediates.noindex/ReactNativeNavigation.build/Debug-iphonesimulator/ReactNativeNavigationTests.build/Objects-normal/x86_64/ReactNativeNavigationTests_dependency_info.dat -o /Users/jeremy/Library/Developer/Xcode/DerivedData/MyPath-bwhssvdsbkvifjenbwvdkpzlqahk/Build/Products/Debug-iphonesimulator/ReactNativeNavigationTests.xctest/ReactNativeNavigationTests
```

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 2.8.0 (and 2.5.1)
* React Native version: 0.58.3 
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Debug build linker error

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 87.03 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      npm: 6.7.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 20, 23, 24, 25, 26, 27
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.0, 27.0.1, 27.0.2, 27.0.3
        System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.3 => 16.6.3 
      react-native: ^0.58.3 => 0.58.3 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7

**Comment by HolySamosa** [comment]
Forgot to mention, I'm presently working around this by removing the **ReactNativeNavigationTests** target.

**Comment by kostya9116** [comment]
hi @HolySamosa, how did you remove ReactNativeNavigationTests, and does it help?

**Comment by HolySamosa** [comment]
This is kind of weird- I received the following notification of a comment posted to this issue, however the comment doesn't appear here:

> hi @HolySamosa, how did you remove ReactNativeNavigationTests, and does it help?

I simply edited the ReactNativeNavigation project (ReactNativeNavigation.xcodeproj in node_modules) which my iOS project imports under "Libraries" to remove the ReactNativeNavigationTests build target.  With this removed, the project builds without error.

**Comment by cinder92** [comment]
@HolySamosa  remove the ReactNativeNavigationTest from ReactNativeNavigation.xcodeproj did the trick for me!

**Comment by HolySamosa** [comment]
Thanks, @cinder92, that's exactly what I did as a work around.

**Comment by aniiskywalker** [comment]
I have a question, it works of course, but ... Does it have a negative impact when you deploy your app?

**Comment by HolySamosa** [comment]
@aniiskywalker Yes, it does have an impact on deployment as I can't use build automation as the `ReactNativeNavigation.xcodeproj` file must be manually edited in order for the build to succeed.  So ultimately, the issue needs to be addressed upstream within the RNN project.

**Comment by aniiskywalker** [comment]
@HolySamosa Thank you

**Comment by RoiDayan1** [comment]
i also have this problem, can anyone can give me a step by step how to overcome this problem?

**Comment by alpamys-qanybet** [comment]
me too, please help!

**Comment by RoiDayan1** [comment]
here:
<img width="679" alt="Screen Shot 2019-03-24 at 7 26 35" src="https://user-images.githubusercontent.com/29122098/54875363-61daa480-4e06-11e9-8a60-fe5bd85c82e7.png">
press delete.
remember, this is a workaround and you will need to do it on new installation on a new computer etc.

**Comment by alpamys-qanybet** [comment]
@RoiDayan1, I also found out that there is '-' button in panel below.

**Comment by vdimitrovv** [comment]
> @aniiskywalker Yes, it does have an impact on deployment. I can't use build automation as the `ReactNativeNavigation.xcodeproj` file must be manually edited in order for the build to succeed. So ultimately, the issue needs to be addressed upstream within the RNN project.

Fork the RNN repository, remove the tests on there and use your fork until the tests are fixed.

It's already been 2 months, so maybe we can have it fixed by Christmas 😬

**Comment by yogevbd** [comment]
Fixed in this PR: https://github.com/wix/react-native-navigation/pull/5050
