### ISSUE TITLE
[V2][Android] options layout topMargin not working on push

### ISSUE THREAD

**Issue by yfuks** [wix/react-native-navigation#4695]
### Issue Description

The options
```js
layout {
  topMargin: value,
},
```
not working on `push()`
I was able to use it with `showModal()` and `setRoot()` does it only work on root components ?
### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.push(componentId, {
  component: {
    name: component,
    options: {
      layout: {
          topMargin: 40,
       },
    },
  },
});
```

---
### Environment
* React Native Navigation version: 2.8.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Debug

**Comment by AlexBueckig** [comment]
Are the other options working for you? I just noticed that all my options (buttons, topbar title, ...) defined in my components
```
public static options() {
   return {
      topBar: {
        title: { text: 'MyTitle' }
      }
    };
}
```
method stopped working after pushing a component to a stack. The initial root of the stack defined in `Navigation.setRoot()` works fine though aswell.


### Environment
* React Native Navigation version: 2.10.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Debug

**Comment by yfuks** [comment]
Yes. Others options seems to work as expected in my case.

**Comment by ahmedam55** [comment]
Not solved
