### ISSUE TITLE
Layout LargeTitle with right buttons

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#4697]
### Issue Description
Is it possible to add rightButtons or leftButtons  adjacent to LargeTitle

![9b960f20-4d77-4640-946f-f948b66f3789](https://user-images.githubusercontent.com/13536334/52358191-9258b180-2a05-11e9-8186-7226af61baed.jpeg)

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by jinshin1013** [comment]
From my understanding, it isn't a natural/provided feature on iOS and require additional implementation. But this feature would be great to have thought.
