### ISSUE TITLE
Navbar title click event

### ISSUE THREAD

**Issue by maxs15** [wix/react-native-navigation#47]
Hi,

Is there any configuration available to catch a click on the title (using titleImage) ? 
I didn't find anything in the docs related to this event :)

Thanks

**Comment by gran33** [comment]
@maxs15, Work in progress

**Comment by maxs15** [comment]
Awesome @gran33 :)

**Comment by maxs15** [comment]
Any update on this ? Can't wait to implement my new feature hehe :D

**Comment by headlessme** [comment]
Is this feature available yet? Sorry if I've missed it in the documentation

**Comment by nidongara** [comment]
Any update on this?

**Comment by raunaqss** [comment]
Any update on this yet?

**Comment by enahum** [comment]
will this be available on version 1 or just in version 2?

**Comment by kristm** [comment]
+1

**Comment by kristm** [comment]
there's a relevant PR for this https://github.com/wix/react-native-navigation/pull/967
