### ISSUE TITLE
[V2] Hide android navigation bar

### ISSUE THREAD

**Issue by iShankarG** [wix/react-native-navigation#4701]
I could find any option to hide android navigation bar. Is this feature available and not exposed in documentation. If not any plan of adding it or alternative ways to do that.

![navigation bar](https://developer.android.com/images/training/navigation-bar.png)

---
### Environment
* React Native Navigation version: 0.57.7
* React Native version: 2.9.0 
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by kyle-ssg** [comment]
Hey @iShankarG, I could be wrong but is this what you're looking for? 
https://github.com/Anthonyzou/react-native-full-screen

You could use this within screen lifecycle events

**Comment by iShankarG** [comment]
@kyle-ssg I have tried it and it's not working for me. But If we have that as option in react-native-navigation, we will have more control over the layout and don't want to rely on other package.

Since I'm new to React Native, I don't have much exposure to RN Modules. If you guide me, I'm happy to contribute.
