### ISSUE TITLE
[V2][IOS] Change all BottomTabs textColor, iconColor,  selectedTextColor, selectedIconColor, 

### ISSUE THREAD

**Issue by rsispal** [wix/react-native-navigation#4703]
### Issue Description

I've been trying to figure out how to change the `bottomTabs` text colour, selected text colour, icon colour and selected icon colour across all tabs by the root ID.

In response to my previous issue (#4418) showing some unimplemented style properties in `mergeOptions()`, I've been able to implement the change of the above colour properties directly to a bottomTab. Still not the entire bar though and having to keep track of hardcoded bottomTab ID's to run `mergeOptions()` on is a problem waiting to happen as my development continues, especially as different navigators are produced for different user levels.

How can I go about implementing these colour changes to `setDefaultOptions()` and `mergeOptions()`? 

Currently implementing a light and dark mode to my app. This is why I need an easy way to blanket set the colours.

### Steps to Reproduce / Code Snippets / Screenshots
N/A

---
### Environment
* React Native Navigation version: 2.9.0
* React Native version: 0.58.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPad Pro 11" (actual and simulator)

**Comment by matmac** [comment]
+1

Also I would love to know how to change styles for each one of the tabs my app has, for example, "blue" background on the first tab and "white" background on the rest of the tabs, I'm currently getting the style change but only when I tap on the next tab... meaning tap on 2nd tab, no style change, tap on any next tab, styles change for the previous styles passed... strange behaviour.

**Comment by MahmoudShaeer** [comment]
+1
