### ISSUE TITLE
SideMenu disableOpenGesture not working

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#471]
Hi, 

disableOpenGesture not working for me, it's always disabledOpenGesture, It worked only when I went the module java file (SideMenu.java) and i commented this line

setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);

### Steps to Reproduce / Code Snippets / Screenshots

drawer: { // optional, add this if you want a side menu drawer in your app
            left: { // optional, define if you want a drawer from the left
              screen: 'seco.SideMenu', // unique ID registered with Navigation.registerScreen
            },
            disableOpenGesture: false, // optional, can the drawer be opened with a swipe instead of button
          },

---
### Environment
* React Native Navigation version: ^2.0.0-experimental.142
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): OS 5.0

**Comment by Jaafar-abusair** [comment]
any updates?

**Comment by guyca** [comment]
No, sorry. Didn't have time to look into this yet.

**Comment by wwwdata** [comment]
Can confirm this. Seems to work fine on iOS, but in Android this is never locked.
