### ISSUE TITLE
[Android] BottomTabs misaligned if app started in landscape mode

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#4710]
### Issue Description

On Android when an app is started in Landscape mode and then switched back to portrait. The bottomTabs will be misaligned. Gif below

### Steps to Reproduce / Code Snippets / Screenshots

![bottomtabs](https://user-images.githubusercontent.com/4223434/52469010-9bbf5680-2b8a-11e9-99e7-80a547a3285a.gif)

---
### Environment
* React Native Navigation version: 2.8.0
* React Native version: 0.56
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by ghsantos** [comment]
any update for that?
