### ISSUE TITLE
How do I run playground code?

### ISSUE THREAD

**Issue by kirhim** [wix/react-native-navigation#4717]
There is no installation guide for this.
I tried in my terminal:
`cd playground`
`npm install`

then 'react-native run-ios'
but this won't work. 

I think I might be doing something wrong. Does anyone know the installation guide to run the playground code?

**Comment by andertun** [comment]
Did you follow the [Playground](https://wix.github.io/react-native-navigation/#/docs/showcases?id=playground) instructions? 

If you did, try to start over and clone the master branch instead.

`git clone -b master git@github.com:wix/react-native-navigation.git`

And then follow the rest of the instructions.

**Comment by kirhim** [comment]
@andertun I followed the Playground instructions and that worked for me thank you very much. However, it only shows how to run using xcode. What about android?

**Comment by RominHalltari** [comment]
I'm running `npm start` after `npm install` but it fails with this error: 
`Command failed: lsof -t -i :8081 \| xargs kill \|\| true`. 
Anyone knows how to run it on Android?
