### ISSUE TITLE
Horizontal scrolling doesn't work in Android side menu

### ISSUE THREAD

**Issue by atoami** [wix/react-native-navigation#4718]
### Issue Description

[ENTER DESCRIPTION HERE]

### Steps to Reproduce / Code Snippets / Screenshots

I put [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view) inside the side menu component but horizontal scrolling doesn't work.

---
### Environment
* React Native Navigation version: 2.8.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device, Debug/Release

**Comment by guyca** [comment]
You'll probably need to use Android's NestedScrollView
