### ISSUE TITLE
[iOS] waitForRender on setRoot breaks KeyboardAvoidingView capability 

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#4719]
### Issue Description

The new waitForRender animation breaks KeyboardAvoidingView's capability.

First without waitForRender:
![2019-02-11 11 48 49](https://user-images.githubusercontent.com/4223434/52558810-d841bb00-2df3-11e9-81cf-99724da13f38.gif)

Then with waitForRender:
![2019-02-11 11 50 06](https://user-images.githubusercontent.com/4223434/52558820-e1cb2300-2df3-11e9-84be-6ecd641f5320.gif)

### Steps to Reproduce / Code Snippets / Screenshots

I setRoot with the following layout:
```js
    root: {
      stack: {
        children: [
          {
            component: {
              id: 'baseNet.LoginScreen',
              name: SCREENS.LOGINSCREEN,
            },
          },
        ],
        options: {
          animations: {
            setRoot: {
              waitForRender: true,
            },
          },
        },
      },
    },
```

---
### Environment
* React Native Navigation version: 2.11.0
* React Native version: 56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by guyca** [comment]
When are you giving focus to the text input? Have you tried focusing it in `componentDidAppear`?
