### ISSUE TITLE
Integration with local/push notification libraries on Android

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#472]
### Issue Description

I have been successfully using [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) library to show local/push notifications in my app. After I moved to this package, I realized that the local/push notifications are no longer working on Android. After some debugging, I realized that my application never receives the notification intent due to which none of the code around the local/push notification is invoked. I think the reason for that is as stated in the `Android specific use cases` wiki page

> MainActivity extends SplashActiviy which is used to start the react context. Once react is up and running MainActivity is stopped and another activity takes over to run our app: NavigationActivity. Due to this design, there's usually no point in overriding lifecycle callbacks in MainActivity.

In the push notification package, I can see that the notification intent is delivered to the `MainActivity` class which is stopped by this package. This code is from the push notification package to figure out the `MainActivity` class

```java
        String packageName = mContext.getPackageName();
        Intent launchIntent = mContext.getPackageManager().getLaunchIntentForPackage(packageName);
        String className = launchIntent.getComponent().getClassName();
        try {
            return Class.forName(className);
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            return null;
        }
```

It is pretty common for apps to have local/push notifications, so I am pretty sure that people using this package have already figured out how to fix this problem. I searched for issues related to push notification and I did find some issues but still don't understand how to fix this problem. Could you please let me know how can I integrate with the local/push notification libraries. Ideally, I think we should be able to integrate the local/push notifications third party libraries without making any changes to the third party library but I am open to making changes to the third party library as well for the time being since this has completely stopped the local/push notifications in my Android app and my app relies on it heavily.

### Environment
* React Native Navigation version: 2.0.0.experimental.141
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device Nexus 5 / Debug

**Comment by Crash--** [comment]
I'm using both projects on iOS & Android and I didn't notice something wrong with it. I can display push notification etc. 

Can you share your `MainApplication.java` ?

**Comment by MattDavies** [comment]
Try 2.0.0.experimental.142 which includes https://github.com/wix/react-native-navigation/pull/433 (makes sure all the push notification data gets passed through properly).

**Comment by varungupta85** [comment]
@Crash-- Below is my `MainApplication.java` file. The notifications will display fine but the event handler for the notification won't be called when the notifications are clicked. The `onNotification` event handler for the local/push notifications is no longer invoked when the notifications are clicked. Can you confirm that you are able to invoke the `onNotification` event handler as well. Thanks!

```java
package com.galarmapp;

import android.support.annotation.NonNull;

import com.facebook.react.ReactPackage;
import com.reactnativenavigation.NavigationApplication;

import java.util.Arrays;
import java.util.List;

import com.joshblour.reactnativepermissions.ReactNativePermissionsPackage;
import com.evollu.react.fa.FIRAnalyticsPackage;
import com.reactnative.ivpusic.imagepicker.PickerPackage;
import com.learnium.RNDeviceInfo.RNDeviceInfo;
import com.oblador.vectoricons.VectorIconsPackage;
import com.zmxv.RNSound.RNSoundPackage;
import com.rt2zz.reactnativecontacts.ReactNativeContacts;
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
import com.aakashns.reactnativedialogs.ReactNativeDialogsPackage;
import com.acintyo.reactnativeandroidperiodicfetch.ReactNativeAndroidPeriodicFetchPackage;
import com.i18n.reactnativei18n.ReactNativeI18n;

public class MainApplication extends NavigationApplication {

    @Override
    public boolean isDebug() {
        // Make sure you are using BuildConfig from your own application
        return BuildConfig.DEBUG;
    }

    @NonNull
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return Arrays.<ReactPackage>asList(
                new ReactNativePermissionsPackage(),
                new FIRAnalyticsPackage(),
                new PickerPackage(),
                new RNDeviceInfo(),
                new RNSoundPackage(),
                new ReactNativeContacts(),
                new ReactNativePushNotificationPackage(),
                new ReactNativeDialogsPackage(),
                new ReactNativeAndroidPeriodicFetchPackage(),
                new ReactNativeI18n(),
                new VectorIconsPackage()
        );
    }
}
```

**Comment by varungupta85** [comment]
@MattDavies I will update to `.142` and report back.

**Comment by varungupta85** [comment]
@MattDavies I updated to `.142` but I still see the same problem. 

In the `Android specific use cases` wiki page, what does it mean by `Once react is up and running MainActivity is stopped and another activity takes over to run our app: NavigationActivity`. Does it mean that the `MainActivity` is no longer running? If that is the case, that may cause a problem with the notification intent. In the notification intent, the main activity class is specified as `com.xyz.MainActivity` and if it is no longer running, then intent may not be intercepted. I don't have a lot of knowledge with native Android code as such and I may be completely off in my understanding. Thanks!

cc @guyca

**Comment by varungupta85** [comment]
I did some more digging around in the `react-native` code and I think I have a better handle on why it is not working and I think the problem is more widespread. I am posting some code snippets from `react-native` code to explain the problem.

Traditionally, `MainActivity` class extends `ReactActivity` and `MainApplication` class extends `ReactApplication` classes. `ReactActivity` extends `Activity` and overrides the method `onNewIntent` which is defined as:

```java
// ReactActivity.java
 @Override
  public void onNewIntent(Intent intent) {
    if (!mDelegate.onNewIntent(intent)) {
      super.onNewIntent(intent);
    }
  }
```

The `onNewIntent` for the `mDelegate` is defined as:

```java
// ReactActivityDelegate.java
public boolean onNewIntent(Intent intent) {
    if (getReactNativeHost().hasInstance()) {
      getReactNativeHost().getReactInstanceManager().onNewIntent(intent);
      return true;
    }
    return false;
  }
```

The `onNewIntent` in `ReactInstanceManager` which is an object of `XReactInstanceManagerImpl` is defined as:

```java
// XReactInstanceManagerImpl.java
@Override
  public void onNewIntent(Intent intent) {
    if (mCurrentReactContext == null) {
      FLog.w(ReactConstants.TAG, "Instance detached from instance manager");
    } else {
      String action = intent.getAction();
      Uri uri = intent.getData();

      if (Intent.ACTION_VIEW.equals(action) && uri != null) {
        DeviceEventManagerModule deviceEventManagerModule =
                Assertions.assertNotNull(mCurrentReactContext).getNativeModule(DeviceEventManagerModule.class);
        deviceEventManagerModule.emitNewIntentReceived(uri);
      }

      mCurrentReactContext.onNewIntent(mCurrentActivity, intent);
    }
  }
```

The `onNewIntent` in `mCurrentReactContext` which of type `ReactContext` is defined as:

```java
// ReactContext.java
public void onNewIntent(@Nullable Activity activity, Intent intent) {
    UiThreadUtil.assertOnUiThread();
    mCurrentActivity = new WeakReference(activity);
    for (ActivityEventListener listener : mActivityEventListeners) {
      listener.onNewIntent(intent);
    }
  }
```

An instance of `ReactContext` is provided to the native modules when they are constructed. `ReactContext` also have a method `addActivityEventListener` which can be used by native modules to add activity listeners which are invoked when a new intent arrives at the application.

The `react-native-push-notification` module calls the `addActivityListener` method when it is created. It also defines a `onNewIntent` method where the notification event is emitted to the JS code.

The notification intent is delivered to the `MainActivity` which will then follow the above route to end up on the `onNewIntent` of the module and emit an event to the JS side. Now since as part of setup for this package, we don't extend `MainActivity` from `ReactActivity` but `SplashActivity`, all the above plumbing doesn't happen. I think the problem may apply to many other native modules as well which relies on receiving a new intent or activity result.

**Comment by guyca** [comment]
Hey @varungupta85 
`onNewIntent` isn't even called in our case since `NavigationActivity` isn't started with the `SINGLE_TOP` flag. instead, we pass data differently.

First, let's understand what happens when a notification is created and clicked. When creating a notification, a `PendingIntent` is created with a corresponding `Intent` which will be started when the notification is clicked. In your case, the application's launch intent is used, which is perfectly fine in our case.
When the notification is clicked, `MainActivity` is opened, meaning it's `onCreate` and `onResume` methods are called.

`MainActivity` extends `SplashActivity`, let's take a look what happens in `SplashActivity`.
`onCreate` - we [save](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/controllers/SplashActivity.java#L19) the data sent from the push notification.
`onResume` - if react context is being created are has already been created - we call `finish()` and return to `NavigationActivity`.

`NavigationActivity.onResume()` is called. This is where we [save](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java#L95) the data you got from the push notification.

I don't have time to dig in their code today, but if we need to change something to support `react-native-push-notification` I'd appreciate if you let me know.

I don't want your activities to use singleTop or any other flags. The whole activity flags mechanism on Android is screwed up in my opinion and leads to unexpected behaviours. it's complete magic and I think we should avoid it.

**Comment by varungupta85** [comment]
@guyca Thanks for the detailed response.

> If for some reason you've added singleTop flag, remove it.

I haven't added any such flag myself anywhere but I can see that when the intent for the notification is created, this flag is added. Below is how the notification intent is created in the `react-native-push-notification` package.

```java
Intent intent = new Intent(mContext, intentClass);
intent.addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP);
```

I don't know if that is a cause for concern.

I was able to verify the above sequence of events you mentioned when a notification is clicked and like you said, since the `onNewIntent` is never called, the new intent kind of goes unattended. I think the package takes care of activity results that are returned by activities started by the native modules but ignores the new intents sent to the application.

I added the below line of code in the `onResume` method of [NavigationActivity](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/controllers/NavigationActivity.java#L96) such that it looks like below

```java
    @Override
    protected void onResume() {
        super.onResume();

        Log.d("NavigationActivity", "onCreate");

        if (isFinishing() || !NavigationApplication.instance.isReactContextInitialized()) {
            return;
        }

        currentActivity = this;
        setDeepLinkData();
        NavigationApplication.instance.getReactGateway().onResumeActivity(this, this);
        NavigationApplication.instance.getReactGateway().getReactContext().onNewIntent(this, getIntent()); // NEW LINE ADDED
        NavigationApplication.instance.getActivityCallbacks().onActivityResumed(this);
        EventBus.instance.register(this);
    }
```

After adding the new line, the push notifications started to work as expected. Essentially, the `onNewIntent` method in the `react-native-push-notification` package was called when the notification is clicked which emits the notification event to the JS side.

I am not sure if the above change is correct but the I think the basic problem is that the activity event listeners are not notified of the new intent due to which some native modules may not function properly. If you can direct me towards how to properly fix the problem, I would be more than happy to write out the code and send a PR.

**Comment by varungupta85** [comment]
@guyca I guess if I can figure out that the `NavigationActivity` is resumed because of a new intent, then I can conditionally call the `onNewIntent` method in that case. I guess the activity can be resumed due to following reasons - on arrival of a new intent, on activity result and when the app is foregrounded. Is that correct?

**Comment by varungupta85** [comment]
After discussing with @guyca , we have finally arrived at a workaround for the problem which solves the issue for now. The workaround is to set the `ActivityCallbacks` in the `NavigationApplication` and override the `onActivityResumed` method and make the call to `onNewIntent` on the `ReactContext` there such that the custom logic is limited to the app itself. Also check if the new intent has an `notification` extra before calling the method to avoid calling it unnecessarily. Below is the code for it

```java
// NavigationApplication.java
    @Override
    public void onCreate() {
        super.onCreate();
        setActivityCallbacks(new ActivityCallbacks() {
            @Override
            public void onActivityResumed(Activity activity) {
                if(activity.getIntent().hasExtra("notification")) {
                    NavigationApplication.instance.getReactGateway().getReactContext().onNewIntent(activity, activity.getIntent());
                }
            }
        });
    }
```

Thanks a lot for the help @guyca. You are the best 👍

**Comment by guyca** [comment]
Don't forget to check if the intent is not null.
I'm wondering what will happen if you get a notification and handle it like this, and then your app gets paused (user got a phone call for instance) and then resumed. In this case it's possible you'll call `onNewIntent` twice unnecessarily. You might need to dedup the notifications somehow.

**Comment by varungupta85** [comment]
There was an issue with the above workaround where the notification intent was delivered to the application repeatedly if the app is paused and resumed after receiving a notification. I have updated the above workaround to fix that problem. Basically, we want to remove the `notification` extra from the intent after it has been handled to reflect the same so that we don't handle it again.

`activity.getIntent().removeExtra("notification");`

**Comment by Jaafar-abusair** [comment]
but how to receive the notification intent in react-native, after clicking on the notification, and why I'm not getting notification if the app is open!?

**Comment by varungupta85** [comment]
@Jaafar-abusair The code that we added in the `onActivityResumed` activity callback is supposed to deliver the notification intent to the `react-native-push-notification` package. Please note that that  the `if condition` present in the activity callback is specific to the `react-native-push-notification` package and it may need to be different if you are using a different package. I am not sure why are you not seeing the notification when the app is open in Android because I think I still see them. They wouldn't appear in iOS of course if the app is open due to design.

**Comment by Crash--** [comment]
Is it planned to add notification support in the 2.0.0. release? Or add a wiki page to show how to do so? I tried to understand this thread, but... :(
