### ISSUE TITLE
[Android] Bug: waitForRender on bottomTabs setRoot never completes

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#4721]
### Issue Description

It seems setting root with a bottomTabs layout with setRoot: { waitForRender: true } animation never completes. 

### Steps to Reproduce / Code Snippets / Screenshots

setRoot layout looks like:
```js
    root: {
      bottomTabs: {
        id: 'baseNet.bottomTabs',
        children,
        options: {
          animations: {
            setRoot: {
              waitForRender: true,
            },
          },
        },
      },
    },
```

With waitForRender:
![waitforrendertrue](https://user-images.githubusercontent.com/4223434/52561871-ee07ae00-2dfc-11e9-8a60-ab1036675079.gif)

Without waitForRender:
![waitforrenderfalse](https://user-images.githubusercontent.com/4223434/52561934-227b6a00-2dfd-11e9-9092-68c16001a290.gif)

---
### Environment
* React Native Navigation version: 2.11.0
* React Native version: 56.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by guyca** [comment]
Does this reproduce in the playground app as well?

**Comment by ItsNoHax** [comment]
@guyca It does not reproduce :/ I will look into it further.

**Comment by ItsNoHax** [comment]
Going to close this for now since I can't reproduce this on the playground app.
