### ISSUE TITLE
[V2] Using Context to pass around ComponentID

### ISSUE THREAD

**Issue by deecewan** [wix/react-native-navigation#4727]
### Issue Description

Hey. I've set up a context store that keeps track of the `componentId`. The provider is rendered in every screen, and the consumer can then be used in components that need to perform navigation functions.  This allows us to stop passing `componentId` down through the whole tree if we want a button to navigate to a new screen, or if we want to set a title or similar.

Just wondering if there were any foot-guns to this approach? I imagine there is a reason that this functionality isn't implemented in the library itself.

**Comment by guyca** [comment]
Hey @deecewan 
Context is a very recent addition to React, while RNN has been in development since 2016 - that's the reason why it's not promoted more by us.

**Comment by deecewan** [comment]
@guyca sure. but are there any downsides to using context to pass the componentId to children using Context?

**Comment by guyca** [comment]
None that I'm aware of :)
