### ISSUE TITLE
BUG：When pop to the last page, the bottom of the current page will flash.

### ISSUE THREAD

**Issue by camellieeee** [wix/react-native-navigation#473]
![3](https://cloud.githubusercontent.com/assets/18331008/20514950/f00cf096-b0c9-11e6-97a8-e00cc6538ab4.gif)
You can see this gif or the two images.
react-native@0.37  (But this bug was found in react-native@0.29 too)
react-native-navigation@latest
![1](https://cloud.githubusercontent.com/assets/18331008/20515089/da5a53dc-b0ca-11e6-92ef-f7d36932b1ba.jpg)   ====>
![2](https://cloud.githubusercontent.com/assets/18331008/20515090/dbaf3dec-b0ca-11e6-999a-367b2acaa320.jpg)

**Comment by guangmingzizai** [comment]
I met with the same problem, after 2 days debug, I came up with a temp fix:
Change RCTRootView like so:
```objective-c
- (void)layoutSubviews
{
    [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(_performLayout) object:nil];
    [self performSelector:@selector(_performLayout) withObject:nil afterDelay:0.008];
}

- (void)_performLayout {
    [super layoutSubviews];
    
    _contentView.frame = self.bounds;
    _loadingView.center = (CGPoint){
        CGRectGetMidX(self.bounds),
        CGRectGetMidY(self.bounds)
    };
}
```

---
If you log in the `RCCTabBarController` like so:
```objective-c
- (void)viewWillLayoutSubviews {
  [super viewWillLayoutSubviews];
  
  NSLog(@"-----viewWillLayoutSubviews: %@", NSStringFromCGRect(self.selectedViewController.view.frame));
}

- (void)viewDidLayoutSubviews {
  [super viewDidLayoutSubviews];
  
  NSLog(@"-----viewDidLayoutSubviews: %@", NSStringFromCGRect(self.selectedViewController.view.frame));
}
```

When pop, you will get like so:
```
2017-02-05 01:22:55.296 YourAppName[15793:274659] -----viewWillLayoutSubviews: {{0, 0}, {375, 667}}
2017-02-05 01:22:55.296 YourAppName[15793:274659] -----viewDidLayoutSubviews: {{0, 0}, {375, 667}}
2017-02-05 01:22:56.003 YourAppName[15793:274659] -----viewWillLayoutSubviews: {{0, 0}, {375, 618}}
2017-02-05 01:22:56.003 YourAppName[15793:274659] -----viewDidLayoutSubviews: {{0, 0}, {375, 667}}
```
Pay attention to **618**, there is a disturbance. It doesn't cause problems if the viewController.view is a normal view, however RCTRootView is an exception. If you add a breakpoint at the layoutSubviews method of RCTRootView, you will find the stack trace is different from normal view. 
I think this is a bug of react-native, but I haven't found the underlying cause sadly. Looking forward to better solution.

**Comment by camellieeee** [comment]
@guangmingzizai Cool！thanks！
