### ISSUE TITLE
[v2] react-native-navigation waits until whole screen loads before navigate?

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#4731]
### Issue Description

I hear somewhere here that when we navigate to screen RNN will wait until every element loads and only then visually navigates to this screen? And because of this we have this pause between our touch and navigation animation?
And solution was to hide screen elements conditionally and show them in timeout so RNN will show screen faster?

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 0.57.8
* React Native version: 2.11
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?):Device/Simulator

**Comment by hadimostafapour** [comment]
@rendomnet There is a property that enables you to ignore this behavior, look for `waitForRender` in documentation.

**Comment by rendomnet** [comment]
@hadimostafapour I did not found it in official documentation.
So by default it is not waits?

**Comment by ItsNoHax** [comment]
By default it does not wait. You can use the waitForRender option if you do want to wait for it to render.
