### ISSUE TITLE
App stucks when push to new screen whereas it shows in console log that it pushed already.

### ISSUE THREAD

**Issue by suupham2506** [wix/react-native-navigation#4733]
### Issue Description

I tried to push to avatarIntro screen.
It already pushed to avatarIntro screen in console log but actually it's not. The app kept running at the current screen.

### Steps to Reproduce / Code Snippets / Screenshots
![screen shot 2019-02-14 at 11 37 16 am](https://user-images.githubusercontent.com/28852565/52763808-d4aa7000-304f-11e9-9a83-1f6db4ccc3d7.png)

---
### Environment
* React Native Navigation version: 2.11.0
* React Native version: 0.56.1
* Platform(s) (iOS, Android, or both?): only IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by retyui** [comment]
Please use [Screen Lifecycle methods](https://wix.github.io/react-native-navigation/#/docs/Usage?id=screen-lifecycle) like `componentDidAppear` to know screen already shows!

**Comment by byonghun** [comment]
@suupham2506 I've been getting this issue as well. For me, it only happens when I open/close drawers then try pushing a component. When does this occur for you?

@retyui I have a global appear listener but I still encounter this issue. In your app, do you use drawers?
