### ISSUE TITLE
[iOS] Peek and Pop no longer working as expected

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#4734]
### Issue Description

It seems somewhere between release 2.8.0 and 2.11.0 that peek and pop have stopped working. While the peek window still appears, it previews the screen you are going to push as a white blank screen and when you press hard enough that it pushes to the screen. You end up in a blank white screen.

### Steps to Reproduce / Code Snippets / Screenshots

Go to the playground app , click on the Peek and Preview menu option and the result is a blank screen
---
### Environment
* React Native Navigation version: 2.11.0
* React Native version: Any
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?):Device (as I don't have a compatible Mac to test with simulator)

**Comment by guyca** [comment]
@yogevbd could this be related to waitForRender effort?
