### ISSUE TITLE
Android: right drawer not working correctly

### ISSUE THREAD

**Issue by adawi9** [wix/react-native-navigation#4736]
### Issue Description

I used react navigation to show drawer, I want to show the drawer from the right so I set 
drawerPosition: 'right'

but it is not working correctly, it is opened whenI swipe from any point in the screen not only from the edge

this vide show my issue

[VIdeo](https://drive.google.com/file/d/1u-IcEYxpp_sHx3li4iv26cNlBaIMTbOx/view?fbclid=IwAR3i9Glpk5KPZCigdleMKSqKUXHxwI3a08TgkPMyw7c8Dw2vfTKNYJ006Iw)

---
### Environment
* React Native Navigation version: 3.1.5
* React Native version: 0.58.4
* Platform(s) (iOS, Android, or both?): only Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device

**Comment by hadimostafapour** [comment]
set `openGestureMode` to `bezel`.

check docs here: https://wix.github.io/react-native-navigation/#/docs/styling
```javascript
sideMenu: {
    left: {
      shouldStretchDrawer: false, // defaults to true, when false sideMenu contents not stretched when opened past the width
      animationVelocity: 2500 // defaults to 840, high number is a faster sideMenu open/close animation
    },
    right: {
      shouldStretchDrawer: false, // defaults to true, when false sideMenu contents not stretched when opened past the width
      animationVelocity: 2500 // defaults to 840, high number is a faster sideMenu open/close animation
    },
    animationType: 'parallax', // defaults to none if not provided, options are 'parallax', 'door', 'slide', or 'slide-and-scale'    
    openGestureMode: 'entireScreen' | 'bezel'
  }
```

**Comment by adawi9** [comment]
As the document on the link yiu sent the openGestureMode is specified for iOS not android... My issue under android not iOS

**Comment by adawi9** [comment]
Same issue [here](https://github.com/kmagiera/react-native-gesture-handler/issues/464) ... so I'll close this issue
