### ISSUE TITLE
[RNNSplashScreen tabBar]: unrecognized selector sent to instance 0x7fe55ec00c60

### ISSUE THREAD

**Issue by diruuu** [wix/react-native-navigation#4737]
### Issue Description

I got this error after upgrading to v2.11.0. I'm using react-native-splash-screen package. Everything works fine on Android, but on iOs it throws error **[RNNSplashScreen tabBar]: unrecognized selector sent to instance 0x7fe55ec00c60** after splash screen disappear. It only happens if I disable the remote JS debugger. 

---
### Environment
* React Native Navigation version: 2.11.0
* React Native version: 0.58.1
* Platform(s) (iOS, Android, or both?): iOs
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug

**Comment by lumenlunae** [comment]
I had a similar error--mine was that I was calling `Navigation.constants()` in a file before the splash screen was being dismissed. Hopefully that can help!

**Comment by xido00** [comment]
@lumenlunae Thanks. I had the same problem!

**Comment by mralj** [comment]
We are having some issue :/

**Comment by nenti** [comment]
We experience a similar issue. Fixed it by moving `Navigation.constants()` to after setRoot of a Tabbar. Since we need the constant in the tabbar though we have rare occurances of crashed based one timing. Is there any other workaround that allows calling constants() without fear of fatal crash?

**Comment by yfuks** [comment]
Reproductible in **2.12.0**

**Comment by yfuks** [comment]
Removing `react-native-splash-screen` don't change anything

**Comment by nenti** [comment]
Not stale. Reopen please.
