### ISSUE TITLE
页面之间如何传递参数

### ISSUE THREAD

**Issue by puyangdev** [wix/react-native-navigation#4738]
How to pass parameters between pages

**Comment by retyui** [comment]
```js
Navigation.push(this.props.componentId, {
  component: {
    name: 'example.PushedScreen',
    passProps: {
      text: 'Pushed screen' // < -- your's props
    },
  }
});
```

See more about [react native navigation  Screen API](https://wix.github.io/react-native-navigation/#/docs/screen-api?id=screen-api)

**Comment by retyui** [comment]
And usually, use https://stackoverflow.com/ for similar questions!
