### ISSUE TITLE
Ability to change elevation of navbar on android

### ISSUE THREAD

**Issue by anuragalla** [wix/react-native-navigation#474]
### Issue Description

How do i  remove/change navbar elevation in android

### Environment
* React Native Navigation version: 0.37
* React Native version: 2.00-experimental.142
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): any

![screen shot 2016-11-22 at 2 03 26 pm](https://cloud.githubusercontent.com/assets/9738350/20518279/9d1ec166-b0c4-11e6-990c-6027cf8b8473.png)

In this scenario the elevation of navbar and swipable tabs should be the same

**Comment by guyca** [comment]
Hey @anuragalla 
I strongly suggest you use the `TopTabs` component provided by RNN. You can refer to [this example](https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js#L106).
The TopTabs will be part of the `TopBar` - so the shadow will be cast appropriately. You will also be able to specify `titleBarHideOnScroll` and when scrolling ListView or ScrollView - the Title will be hidden to provide more screen space for your actual screens.

**Comment by tolu360** [comment]
Hello @guyca, thank you for the great work your team has put into this navigation library. This is the first mention of the `TopTabs` component I would be coming across. Is there any reason it is not mentioned on the wiki or did I totally miss where it is?

Cheers!

**Comment by guyca** [comment]
Hey @tolu360 Thanks for the kind words. `TopTabs` is not mentioned in the docs because it's only available on Android and it's api might change when we'll add it to iOS.
You can refer to the deprecated [example-redux](https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js#L107) app for `TopTabs` implementation.

**Comment by tolu360** [comment]
You are welcome @guyca. I see your point but the `TopTaps` is such a popular UI pattern in Android that it should make it to the docs even while we wait for the unified api across the two platforms. I would refer to the old example to see how to put it together.

Thank you.
