### ISSUE TITLE
[V2] Need ability to use default system animations when navigating screens on Android

### ISSUE THREAD

**Issue by Flavien** [wix/react-native-navigation#4741]
### Issue Description

The V2 of the library doesn't seem to have a way to use the Android default slide animation when navigating being two screens.

In V1, it was the default behavior.

In V2, the default animation is now a bottom-up type animation.

V2 has an API for customising the transition animations, however:

1. It is inconvenient to have to mimic the default system animations.
2. The default slide animation animates both the "from" screen and the "to" screen, which isn't supported with this API.

### Steps to Reproduce

Use `Navigation.push` to navigate to a new screen.

### Environment
* React Native Navigation version: 2.11.0
* React Native version: 0.58.3
* Platform: Android
* Device info: Actual device (Oreo)

**Comment by Pushplaybang** [comment]
yeah this seems to be really odd behaviour, expected the system animation, but left a little cold here.

**Comment by Pushplaybang** [comment]
@Flavien @guyca  - you have got an ideas on where to start?  Keen to see this become a reality as well.

**Comment by Flavien** [comment]
I don't know much about the internals of `react-native-navigation` so a few pointers would certainly help.

**Comment by Pushplaybang** [comment]
@guyca any pointers on where we could start?

**Comment by kamleshh-bms** [comment]
Any update for default system animations support?

**Comment by pribeh** [comment]
I found this odd as well. I'll see if I can come up with a sensible set of values using and share them here: 

https://wix.github.io/react-native-navigation/#/docs/styling?id=customizing-screen-animations

**Comment by Pushplaybang** [comment]
@pribeh  that would be awesome.

**Comment by 8BallBomBom** [comment]
This would be a nice addition, something i've also been working about.

**Comment by ritesh-malav** [comment]
When will we see this ?

**Comment by guyca** [comment]
Closing in favor of #6060, this is planned for Q2 2020.
