### ISSUE TITLE
No ability to create a modal that covers part of the screen

### ISSUE THREAD

**Issue by steve228uk** [wix/react-native-navigation#4743]
### Issue Description

Currently, there's no way to create a modal that only covers part of the screen. This is a common UI pattern, especially since iOS 11 (for example, the Maps app drawer or Apple Music now playing). 

While this could possibly be replicated using an "overlay", this causes additional issues as when using a stack the navigation bar remains at the top of the screen. Ideally, this would be included as part of the presented "card".

### Proposal

I propose that an improvement to the API is made to allow for custom sizing and positioning when using `showModal`. 

The ability to customise `push` and `pop` animations is [already in place](https://wix.github.io/react-native-navigation/#/docs/styling?id=customizing-stack-command-animation). I don't believe the separation needs to be split into `topBar`, `content` and `bottomBar` and instead should follow the below structure:

```js
animations: {
    showModal: {
        x: {
            from: 0,
            to: 1,
            duration: 400,
            startDelay: 100,
            interpolation: 'accelerate'
        },
        y: {
            ...
        },
        width: {
            ...
        },
        height: {
            ...
        }
    }
}
``` 

Should `width` or `height` values not be provided then the modal should stretch to fill the entire screen as it does currently. Should `x` or `y` then the modal should pop up from the bottom as it does currently (on iOS).

This API should be extended to both iOS and Android.

**Comment by eladgel** [comment]
@steve228uk please use **[overlay](https://wix.github.io/react-native-navigation/#/docs/top-level-api?id=showoverlaylayout-)**

**Comment by steve228uk** [comment]
@eladgel As mentioned in my post, overlay does not play well with stacks currently as it leaves the top bar at the top of the screen.

**Comment by rawrmaan** [comment]
What you're describing isn't a modal. Neither the Now Playing in Apple Music or the overlay in Maps are modals. They are carefully controlled UI elements with custom touch handling.

Furthermore, it IS possible to create a modal as you describe in RNN v2. Simply make a component whose top level view has the width and height of the entire screen, and then layout your subviews however you see fit. This can include snapping to the bottom or whatever else you want.
