### ISSUE TITLE
Link not working in iOS install documentation

### ISSUE THREAD

**Issue by ycai2** [wix/react-native-navigation#4744]
### Issue Description

There is a (code snippet) link not working in iOS installation guide

### Steps to Reproduce / Code Snippets / Screenshots
Go to the installation guide for iOS on react-native-navigation: https://wix.github.io/react-native-navigation/#/installation-ios
On step 5, it says: 
In Xcode, you will need to edit this file: AppDelegate.m. Replace all of its code with this [reference](https://github.com/wix/react-native-navigation/blob/master/example/ios/example/AppDelegate.m).

The link address of the reference is this:
https://github.com/wix/react-native-navigation/blob/master/example/ios/example/AppDelegate.m

I got a 404 and I have no idea where to find the original file

---
### Environment
* React Native Navigation version: ^2.11.0
* React Native version: 0.58
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): N/A

**Comment by sam3d** [comment]
I believe it's in [playground/ios/playground/AppDelegate.m](https://github.com/wix/react-native-navigation/blob/master/playground/ios/playground/AppDelegate.m).
