### ISSUE TITLE
replace current screen in stack

### ISSUE THREAD

**Issue by dumbre-prasad** [wix/react-native-navigation#4747]
### Issue Description

hello everyone I am newbie in react native , i am using RNN for navigation I have caught up with an situation where I wanted to replace my current screen with different screen (replace current screen in stack), i haven't found any solution please anybody will help me out here 
Thankyou

---
### Environment
* React Native Navigation version: 2.9.0
* React Native version: 0.57.5
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): Moto c+

**Comment by guyca** [comment]
Hey there, this isn't possible. You can replace all children using `setStackRoot`, but it's not possible to replace a specific child.
