### ISSUE TITLE
FlatList ignores StatusBar drawbehind

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#4748]
### Issue Description

If we make fullscreen FlatList. It will make margin from the top as if drawBehind is false.
On first render it will respect drawBehind={true} but if we scroll FlatList then it will ignored it.

### Steps to Reproduce / Code Snippets / Screenshots

```
class Flat extends Component {

  static options(passProps) {
    return {
      statusBar: {
        visible: true,
        drawBehind: true,
        backgroundColor: "rgba(0,0,0,0)"
      }
    };
  }

 render() {
    return (
     <FlatList .../>
    )
 }
}

```
---
### Environment
* React Native Navigation 2.12.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by RichardLindhout** [comment]
There is an option in FlatList to disable the safe spacing for iOS
