### ISSUE TITLE
[V2][Android 19] Bottomtabs not visible at all if drawBehind=true

### ISSUE THREAD

**Issue by manuhook** [wix/react-native-navigation#4749]
### Issue Description

On Android API 19 (Kitkat 4.4) Bottomtabs are not visible at all if **drawBehind** is set to **true**.
No problem on iOS and Android API 20 to 28.

### Steps to Reproduce / Code Snippets / Screenshots

On Navigation.setDefaultOptions :

```
bottomTabs: {
 visible: true,
 animate: true,
 drawBehind: true
}
```

### Environment
* React Native Navigation version: V2
* React Native version: 57.8
* Platform(s) (iOS, Android, or both?): Android API 19
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device / Debug and Release/

**Comment by jinshin1013** [comment]
You've set `visible: false` ??

**Comment by manuhook** [comment]
Oups my bad, wrong snippet, of course 'visible' must be 'true' like 'drawbehind' to reproduce the problem.

**Comment by manuhook** [comment]
The problem still exist on the last version, you can easily reproduce on the playground app.

**Comment by manuhook** [comment]
Not fixed

**Comment by manuhook** [comment]
Still exist on last version

**Comment by guyca** [comment]
Hey @manuhook 
We don't actively support Android 4.x as that versions's circulation is miniscule - you're welcome to submit a PR

**Comment by sm2017** [comment]
@guyca In android KitKat Bottomtabs is not visible but working 
I am using react-native-navigation@6.4.0
