### ISSUE TITLE
Text does not align properly vertically with a large font size in the topBar (iOS)

### ISSUE THREAD

**Issue by jfrolich** [wix/react-native-navigation#4753]
The text is not vertically aligned / centered when the fontSize is large. I resolved it with a custom component, but it would be great to have this working correctly.

**Comment by rawrmaan** [comment]
You didn't follow the issue template. Please at least provide a screenshot.

**Comment by jinshin1013** [comment]
I believe it's not a natural behaviour on iOS platform to be able to align largeTitle in centre. RNN is trying to provide the fastest platform default behaviour so it makes sense that the library would not support this kind of customisation. BUT it's only my opinion so, if you are happy to make a PR :)
