### ISSUE TITLE
Could not get unknown property 'mergeResourcesProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

### ISSUE THREAD

**Issue by hadnet** [wix/react-native-navigation#4757]
### Issue Description
Got this error just when I try to build for Android (on iOS is working fine):

FAILURE: Build failed with an exception.

* Where:
Script '/Users/jon/RN/RNNv2Firebase/node_modules/react-native/react.gradle' line: 95

* What went wrong:
A problem occurred configuring project ':app'.
> Could not get unknown property 'mergeResourcesProvider' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.

### Steps to Reproduce

1) react-native init Project
2) yarn add react-native-navigation

---
### Environment
* React Native Navigation version: 2.12.0
* React Native version: 0.59.0-rc.2
* Platform: Android
* Device info: Nexus5X API28 x86

**Comment by ralexand56** [comment]
I'm getting the same error.

**Comment by tibbus** [comment]
same here, happens when I try to upgrade my app to React Native version: 0.59.0-rc.2 , cannot reproduce with a new/clean project.

**Comment by kimbui87** [comment]
I'm using 0.59.0-rc.3

and solved by these steps:

- In gradle-wrapper.properties
change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
- and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
- Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
- Remove node_modules, yarn install, and run-android again.
(And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

**Comment by hadnet** [comment]
Yep, React Native 0.59.0-rc.3 solved this issue. Now it's working fine.

**Comment by tibbus** [comment]
for me rc3 didn't solved the issue, but @kimbui87 solution did !

**Comment by linmiss** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

i had solved  it in Android, thanks

**Comment by vikaskbh** [comment]
@kimbui87 solution worked on RN-0.59.1

**Comment by ctrljs** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

where do i paste the metro.config.js file ?? in which folder?

**Comment by marcelloJr** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

Worked on react-native-cli: 2.0.1 and react-native: 0.59.1. Thanks bro

I didn't need to modify the file metro.config.js'

**Comment by theilgazcode** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

Tried on react-native-cli: 2.0.1 and react-native: 0.59.1. 
Gradle version: 4.10.1

It didn't work.


Task :react-native-maps:compileDebugRenderscript FAILED
Could not resolve all files for configuration ':react-native-maps:debugCompileClasspath'.
Could not resolve com.android.support:support-compat:25.2.0.
Could not resolve com.android.support:support-annotations:25.2.0.
Could not resolve com.android.support:support-core-utils:25.2.0.
Could not resolve com.android.support:support-fragment:25.2.0.
Could not resolve com.android.support:support-annotations:28.0.0.
Could not resolve com.android.support:support-compat:28.0.0.
Could not resolve com.android.support:support-core-utils:28.0.0.
Could not resolve com.android.support:support-fragment:28.0.0.
Could not resolve com.android.support:support-core-ui:28.0.0.
Could not resolve com.android.support:support-compat:25.2.0.
Could not resolve com.android.support:support-core-utils:25.2.0.
Could not resolve com.android.support:support-core-ui:25.2.0.
Could not resolve com.android.support:support-fragment:25.2.0.
Could not resolve com.android.support:support-annotations:26.1.0.
Could not resolve com.android.support:support-annotations:25.2.0.

BUILD FAILED in 1s
8 actionable tasks: 3 executed, 5 up-to-date
error Command failed: gradlew.bat app:installDebug

**Comment by jeronnex2** [comment]
having the same error now ....rn 0.59.1

**Comment by kunal886496** [comment]
Same Problem.

**Comment by kunal886496** [comment]
THIS  HAPPENS :

Loading dependency graph, done.
Error: Unable to resolve module `./index` from `/Users/c-kunal.chugh/Desktop/bizmanager-react/node_modules/react-native/.`: The module `./index` could not be found from `/Users/c-kunal.chugh/Desktop/bizmanager-react/node_modules/react-native/.`. Indeed, none of these files exist:
  * `/Users/c-kunal.chugh/Desktop/bizmanager-react/node_modules/react-native/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/Users/c-kunal.chugh/Desktop/bizmanager-react/node_modules/react-native/index/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/c-kunal.chugh/Desktop/bizmanager-react/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/c-kunal.chugh/Desktop/bizmanager-react/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/c-kunal.chugh/Desktop/bizmanager-react/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at /Users/c-kunal.chugh/Desktop/bizmanager-react/node_modules/metro/src/lib/transformHelpers.js:261:42
    at Server.<anonymous> (/Users/c-kunal.chugh/Desktop/bizmanager-react/node_modules/metro/src/Server.js:1038:41)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/c-kunal.chugh/Desktop/bizmanager-react/node_modules/metro/src/Server.js:99:24)
    at _next (/Users/c-kunal.chugh/Desktop/bizmanager-react/node_modules/metro/src/Server.js:119:9)
::ffff:127.0.0.1 - - [22/Mar/2019:11:02:23 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"

**Comment by ras-marques** [comment]
Same error as @kunal886496

**Comment by hoscahmet** [comment]
don't use **run `npm audit fix` to fix them, or `npm audit` for details**  in your project

**Comment by 859988748** [comment]
I have the same issue. Updating gradle to 3.3.0 did address this issue. But gradle 3.3.0 has a bug. It can not resolve R file in my project. all of my layout file can not be resolved. I have to downgrade gradle to 3.2.1. But, this issue will happen again. How to fix this?

**Comment by kimbui87** [comment]
> > I'm using 0.59.0-rc.3
> > and solved by these steps:
> > 
> > * In gradle-wrapper.properties
> >   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> > * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> > * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> > * Remove node_modules, yarn install, and run-android again.
> >   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)
> 
> where do i paste the metro.config.js file ?? in which folder?

You should put it in root - same level with App.js. But now RN 0.59 official version was release, it seems no need config metro anymore.

**Comment by iKronyck** [comment]
Thanks @kimbui87  working for me

**Comment by CliffWMiller** [comment]
I have the same issue as @859988748. I'm using react-native-navigation and facing a similar build issue where the apparent working solution is to downgrade gradle to 3.2.1.

**Comment by 859988748** [comment]
@CliffWMiller I solved it. You need to upgrade AS to 3.2.2 also. using the latest AS will work good with gradle 3.3.0. It cost me one day.

**Comment by nuclearWinters** [comment]
> @CliffWMiller I solved it. You need to upgrade AS to 3.2.2 also. using the latest AS will work good with gradle 3.3.0. It cost me one day.

@859988748 Can you tell me what "AS" stands for? Thank you

**Comment by swcisel** [comment]
> > @CliffWMiller I solved it. You need to upgrade AS to 3.2.2 also. using the latest AS will work good with gradle 3.3.0. It cost me one day.
> 
> @859988748 Can you tell me what "AS" stands for? Thank you

Android Studio

**Comment by MarcoLLeite** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

This not only helped me with using the latest version, but t also helped getting the vscode-react debugger back hitting breakpoints

**Comment by dmackinn** [comment]
@kimbui87 Thank you, your solution fixed this issue for me when upgrading from 0.57.4 to 0.59.3

**Comment by ManuelAlanis** [comment]
> > I'm using 0.59.0-rc.3
> > and solved by these steps:
> > 
> > * In gradle-wrapper.properties
> >   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> > * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> > * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> > * Remove node_modules, yarn install, and run-android again.
> >   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)
> 
> where do i paste the metro.config.js file ?? in which folder?

Thanks @kimbui87 it's works for me

**Comment by vigneshsankar07** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

Thanks, @kimbui87 It's Works fine for me.

**Comment by hariputranto** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

what does it mean by removing node?

**Comment by kimbui87** [comment]
> > I'm using 0.59.0-rc.3
> > and solved by these steps:
> > 
> > * In gradle-wrapper.properties
> >   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> > * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> > * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> > * Remove node_modules, yarn install, and run-android again.
> >   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)
> 
> what does it mean by removing node?

delete old node_modules, yarn install again to make sure new config above is applied

**Comment by fbadaud** [comment]
HI
 I am following guidelines from @kimbui87  but  using 0.59.3 and "metro-react-native-babel-preset": "0.53.0" 

I have following issue in cli.js :
metro.config.js:7
<!DOCTYPE html>
^

SyntaxError: Unexpected token <
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vapro@0.4.5 create-bundle-android: `node node_modules/react-native/local-cli/cli.js bundle
 
Can you help a bit on how to fix this?

thanks in advance
Francois

**Comment by Minter27** [comment]
I did what @kimbui87 suggested, not the build is successful but the app keeps stopping (crashing), does anybody know the solution to this? Thanks in anticipation

**Comment by wibav** [comment]
> I did what @kimbui87 suggested, not the build is successful but the app keeps stopping (crashing), I'm using version 0.59.4. Does anybody know the solution to this? Thanks in anticipation

i solved my problem using this npm install — save “react-native-maps@jerolimov/react-native-maps#fix-rn59rc-compile-issues”

from: github.com/react-native-community/...

the problem is with React native 0.59+ that compile with compileSdkVersion 28 and maps use 26

**Comment by akem3g** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

This solved the issue. Thank you so much!

**Comment by LukePenkava** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

Hi, i tried this fix, but when i do that, i get this error:

```
Cannot find a version of 'com.android.support:support-compat' that satisfies the version constraints: 
   Dependency path 'MyProject-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.4' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-compat:28.0.0'
 Dependency path 'MyProject-native-maps:unspecified' --> 'com.facebook.react:react-native:0.59.4' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-core-utils:28.0.0' --> 'com.android.support:support-compat:28.0.0'
....
```

Any help appreciated.

**Comment by HarshaKoshila** [comment]
**Magic answer**
compileSdkVersion  and  buildToolsVersion **must be same** inside  in root build.gradle file and in react-native-admob build.gradle.

Example:  compileSdkVersion 28
                buildToolsVersion "28.0.3"

**Comment by jorrharris** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

Tried this and I get this message:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  C:\Users\jorrh\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\af8030e268737a93bc8a43fec0f8b818\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

  C:\Users\jorrh\Desktop\Projects\FitBoard\fitboard\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

  C:\Users\jorrh\.gradle\caches\transforms-1\files-1.1\design-26.1.0.aar\a6db251e9fbe69fc08fb3996b591f32d\res\values\values.xml:159:5-202: AAPT: error: resource android:attr/fontVariationSettings not found.

  C:\Users\jorrh\.gradle\caches\transforms-1\files-1.1\design-26.1.0.aar\a6db251e9fbe69fc08fb3996b591f32d\res\values\values.xml:159:5-202: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.

**Comment by androsein** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

THIS WORKS FOR ME

**Comment by hugomejia** [comment]
I encountered this issue while upgrading a project from react-native:0.58.6 to 0.59.8, and thanks to @kimbui87, the solution was : `In gradle-wrapper.properties
change distributionUrl to distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
and in root build.gradle file change gradle classpath to this: classpath 'com.android.tools.build:gradle:3.3.0'` , so thanks a lot !!!!

**Comment by lazymesh** [comment]
I had to change the buildscript object in build.gradle to match with the emulator sdk version as 

> buildscript {
>     ext {
>         buildToolsVersion = "28.0.3"
>         minSdkVersion = 16
>         compileSdkVersion = 28
>         targetSdkVersion = 28
>         supportLibVersion = "28.0.0"
>     }
>     repositories {
>         jcenter()
>         google()
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.3.1'
> 
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }

**Comment by vipinsharma22** [comment]
Try this.

In gradle-wrapper.properties
change distributionUrl to distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip
and in root build.gradle file change gradle classpath to this: classpath 'com.android.tools.build:gradle:3.3.0'
Copy file 'metro.config.js' in 0.59-stable/template to your project.
Remove node_modules, yarn install, and run-android again.
(And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

**Comment by zhou7102** [comment]
> > I'm using 0.59.0-rc.3
> > and solved by these steps:
> > 
> > * In gradle-wrapper.properties
> >   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> > * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> > * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> > * Remove node_modules, yarn install, and run-android again.
> >   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)
> 
> Running RN 0.59.8
> Tried this and I get this message:
> Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
> C:\Users\jorrh.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\af8030e268737a93bc8a43fec0f8b818\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
> 
> C:\Users\jorrh\Desktop\Projects\FitBoard\fitboard\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.
> 
> C:\Users\jorrh.gradle\caches\transforms-1\files-1.1\design-26.1.0.aar\a6db251e9fbe69fc08fb3996b591f32d\res\values\values.xml:159:5-202: AAPT: error: resource android:attr/fontVariationSettings not found.
> 
> C:\Users\jorrh.gradle\caches\transforms-1\files-1.1\design-26.1.0.aar\a6db251e9fbe69fc08fb3996b591f32d\res\values\values.xml:159:5-202: AAPT: error: resource android:attr/ttcIndex not found.
> 
> error: failed linking references.

Sorry, I am facing the same problem now. Have you figured it out?

**Comment by cinan** [comment]
@zhou7102 compare your `android/*` files with https://github.com/facebook/react-native/tree/0.59-stable/template/android. I upgraded gradle to 5.4.1 and to get rid of the problem above.

**Comment by nicoara** [comment]
Hi,

I have the same problem, can someone please help me?

in package-json:
"react-native-navigation": "^1.1.440" (my understanding is that if I upgrade this it will take a full week)

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
      Memory: 33.24 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 21, 23, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 25.0.1, 25.0.3, 26.0.2, 27.0.3, 28.0.3, 29.0.2
        System Images: android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.2.0 => 16.2.0 
      react-native: 0.59.0 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2

kimbui87's solution does not change the error for me. 

Does this error appear on "react-native-navigation": "^1.1.440" ?

Thank you!!!

**Comment by Gasty-WebDev113** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)


I USE THIS WITH "react-native": "0.61.5" AND WORKS !!!!

**Comment by jayasme** [comment]
> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

I want to say a thank you to my life saver!

**Comment by jhonzdev** [comment]
I'm Using 0.59.10

I Implement this solution, but New error Show up

> I'm using 0.59.0-rc.3
> 
> and solved by these steps:
> 
> * In gradle-wrapper.properties
>   change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
> * and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
> * Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
> * Remove node_modules, yarn install, and run-android again.
>   (And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

this is error
![2nd error](https://user-images.githubusercontent.com/70487329/146784293-804824f8-b928-460f-ba0f-1d3a3150c64a.png)
