### ISSUE TITLE
Navbar bottomBorder Flickers when using with navBarNoBorder:true, navBarHideOnScroll:true

### ISSUE THREAD

**Issue by anuragalla** [wix/react-native-navigation#476]
### Issue Description
Im using navigation startSingleScreen app, where the initial view renders  scrollable tabs(https://github.com/react-native-community/react-native-tab-view).

I have set the navigatorStyle to 

```javascript
{
  navBarHideOnScroll: true, 
  navBarNoBorder: true,
}
```
When the navbar animates to hide/show on scroll the bottomBorder flickers in white color.

---
### Environment
* React Native Navigation version: 2.00-experimental.142
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): any

**Comment by PARAGJYOTI** [comment]
Haven't tried yet but try setting drawUnderNavBar: true in appStyle .

**Comment by fdnhkj** [comment]
@PARAGJYOTI I just tried your suggestion and it doesn't help. The bottom of the view still flickers.
