### ISSUE TITLE
Blank topBar when navigating to a screen that hides topBar on Android

### ISSUE THREAD

**Issue by MaZchao** [wix/react-native-navigation#4764]
### Issue Description

Navigating from a  screen that has a topBar to a screen that hides topBar, there's a blank during animation on the last screen. Only appears on Android.

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
// first screen's topBar
topBar: {
  background: {
    color: '#00ff00',
  },
  title: {
    text: 'My Screen'
  },
  animate: false
}

// second screen's topBar
topBar: {
  visible: false,
  drawBehind: true,
  animate: false,
}
```

![issue](https://user-images.githubusercontent.com/16012513/53078691-bb159680-352f-11e9-9b2f-c9160a922a5a.gif)

---
### Environment
* React Native Navigation version: 2.12.0
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Both

Thank you.

**Comment by SudoPlz** [comment]
This shouldn't be closed, I believe it's a bug.

Setting `visible: false` should hide the topBar completely, but now it doesn't.

I got it working by also setting `drawBehind: true`...

This should be reopened.

**Comment by rener172846** [comment]
I have the same issue. Any solution to fix this issue?

**Comment by zabojad** [comment]
Still happening with RNN v 2.20.2

**Comment by tyuwan** [comment]
Also, still happen on 2.21.0

**Comment by DaveLomber** [comment]
Same issue here, 
looks weird 

any solutions on how to make it prettier ?
