### ISSUE TITLE
[v2] hideWithTopBar/visible on statusBar doesn't work if you have a custom topbar component

### ISSUE THREAD

**Issue by FRizzonelli** [wix/react-native-navigation#4768]
### Issue Description

As stated in the description, if you set hideWithTopBar it works great when you simply style the topbar, however if you add a custom background component the statusbar will appear and you can't remove it. 

This is really frustrating because I'm so happy that in v2 you implemented the custom background (which is great, especially if you want to set a gradient as background). In v1 I'm currently adding the component to the top of every container, which isn't very elegant.

### Steps to Reproduce / Code Snippets / Screenshots

Tried to put visible/hideWithTopBar in default options, in setRoot, in screen push and also in didMount with mergeOptions.

---
### Environment
* React Native Navigation version: 2.12.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, all versions

**Comment by zabojad** [comment]
@FRizzonelli I might be experiencing a similar issue (see https://github.com/wix/react-native-navigation/issues/4976). Did you find any solution?

**Comment by FRizzonelli** [comment]
@zabojad Let me have a check at your issue

**Comment by zabojad** [comment]
@FRizzonelli forget it, my issue #4976 was actually from my code...
