### ISSUE TITLE
[V2][iOS] topBar is not displaying Title Text

### ISSUE THREAD

**Issue by frederickalcantara** [wix/react-native-navigation#4770]
### Issue Description

IOS topbar is not rendering text at all while Android's topbar title is. The phone on the right is the Iphone 8 SImulator while the phone on the left is the Google Pixel 2. 

<img width="799" alt="screen shot 2019-02-20 at 11 31 02 pm" src="https://user-images.githubusercontent.com/23001248/53143821-b10f8a00-3567-11e9-8a5b-2cb55af3595b.png">

### Steps to Reproduce / Code Snippets / Screenshots

```
import { Navigation } from "react-native-navigation";
import AuthScreen from './src/screens/Auth';
Navigation.registerComponent('AuthScreen', () => AuthScreen);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      stack: {
        children: [{
          component: {
            name: 'AuthScreen',
          }
        }],
        options: {
          topBar: {
            title: {
              text: 'Login'
            }
          }
        }
      }
    }
  });
});
``` 
---
### Environment
"react-native": "0.58.5",
* React Native Navigation version: ^2.12.0
* React Native version: 0.58.5
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Iphone 8 Simulator

**Comment by RoTTex** [comment]
Hello. Please try to replace topBar options from `stack` to `component`. I thinks it should be something like this:
```
Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      stack: {
        children: [{
          component: {
            name: 'AuthScreen',
            options: {
              topBar: {
                title: {
                  text: 'Login'
                }
              }
            }
          }
        }]
      }
    }
  });
});
```

**Comment by frederickalcantara** [comment]
This solved my problem, this should be noted in the docs if it hasn't already.
