### ISSUE TITLE
left Buttons not work when direction is rtl

### ISSUE THREAD

**Issue by mo-ah-dawood** [wix/react-native-navigation#4771]
### Issue Description

When setting left buttons as component and the layout is rtl
the component not showing 

- if i used  local icon it works fine
- if i set the same code for rightButtons it works fine
![screenshot_1550751301](https://user-images.githubusercontent.com/31937782/53168390-308e6f00-35e3-11e9-85fc-205fb10114ad.png)
![screenshot_1550751322](https://user-images.githubusercontent.com/31937782/53168398-34ba8c80-35e3-11e9-8c31-900ac4e02d8d.png)

### Steps to Reproduce / Code Snippets / Screenshots
```
static options() {
    return {
      topBar: {
        title: {
          text: ""
        },
        leftButtons: [{
          id: "UserAvatar",
          component: {
            id:"UserAvatar",
            name: "UserAvatar"
          }
        }]
      }
    };
  }

---
### Environment
* React Native Navigation version: 2.12.0
* React Native version: 0.58.4
* Platform(s) (iOS, Android, or both?):Tested only in android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by m0dawood** [comment]
I have changed the layout to ltr and it worked fine but the right buttons not work 
so u guess the issue happen when setting the button that replaces the back button
