### ISSUE TITLE
[V2] Impossible to change width of sideMenu with mergeOptions() method

### ISSUE THREAD

**Issue by manelsanz** [wix/react-native-navigation#4773]
### Issue Description
When I try to dinamically change width of `sideMenu`, nothings happens.

### Steps to Reproduce
This is what I'm trying inside my `sideMenu `component. I tried to do that on `componentDidMount()` and on button handler with no luck.

```
  changeSideMenuWidthHandler = () => {
    Navigation.mergeOptions(this.props.componentId, {
      sideMenu: {
        left: {
          width: 100
        }
      }
    });
  };
```

Thanks.

---
### Environment
* React Native Navigation version: 2.7.1
* React Native version: 0.57.8
* Platform(s): Android tested
* Device info: Xiaomi Mi 8 Lite (Android 8.1) / Huawei MediaPad T5 (Android 8.0)

**Comment by cvongrim** [comment]
Ever find a solution? I am running into the same thing.

**Comment by jerodb** [comment]
Try this out:

```
changeSideMenuWidthHandler = () => {
    Navigation.mergeOptions(this.props.componentId, {
      sideMenu: {
        options: {
          sideMenu: {
            left: {
              width: 100,
            },
          },
        },
      }
    });
};
```

I'm setting the sideMenu width like this in  Navigation.setRoot
```
Navigation.setRoot({
    root: {
      sideMenu: {
        center: {
          ...
        },
        left: {
          component: {
            name: 'SideMenu'
          }
        },
        options: {
          sideMenu: {
            left: {
              width: 100,
            },
          },
        },
      }
    }
})
```
