### ISSUE TITLE
How to override back button action [V2]

### ISSUE THREAD

**Issue by andrei0807** [wix/react-native-navigation#4776]
### Issue Description

[ENTER DESCRIPTION HERE]
I am going to override back button's action.
I used BackHandler.
But I can not control back button's action, and backhandler was not called.
How to solve this problem?
Please help me.
Thanks.
![image](https://user-images.githubusercontent.com/32348752/53241138-b7bf0e00-36db-11e9-9781-20610e381d26.png)

---
### Environment
* React Native Navigation version: 2.2.5
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by jinshin1013** [comment]
You will have to use a custom BackButton, RNN does not give you a way to listen or modify the stock BackButton.

**Comment by cinder92** [comment]
same issue here, how can i override BackHandler action in Android?

**Comment by marudy** [comment]
@andrei0807 @cinder92 you may find [this article about android back button handling](https://medium.com/building-with-react-native/android-back-button-handling-in-react-native-apps-1x08-e3acb0990011) useful.

**Comment by cinder92** [comment]
@marudy  this is not working with RNN V2

**Comment by Gujie-Novade** [comment]
I solved it by using a custom back button:
1. When pushing a new screen where I want to override the button, use the options
```js
import Icon from 'react-native-vector-icons/MaterialIcons';
/* ... */
const backIcon = await Icon.getImageSource('arrow-back', 24, '#000');
const component = {
  id: screenID,
  name: screenID,
  passProps,
  options: {
    topBar: {
      leftButtons: [
        {
          id: 'backButton',
          icon: backIcon,
        },
      ],
    },
  }
};
return Navigation.push(componentId, { component });
```

2. Create a HOC to implement you custom back action
```js
import React, { Component } from 'react';
import { Navigation } from 'react-native-navigation';

const getDisplayName = WrappedComponent => WrappedComponent.displayName || WrappedComponent.name || 'Component';

export default function withCustomBackButton(WrappedComponent) {
  class WithCustomBackButton extends Component {
    componentDidMount() {
      this.navigationEventListener = Navigation.events().bindComponent(this);
    }

    componentWillUnmount() {
      if (this.navigationEventListener) this.navigationEventListener.remove();
    }

    navigationButtonPressed() {
      // Your custom action
      const { componentId } = this.props;
      Navigation.pop(componentId);
    }

    render() {
      return <WrappedComponent {...this.props} />;
    }
  }

  WithCustomBackButton.displayName = `WithCustomBackButton(${getDisplayName(WrappedComponent)})`;

  return WithCustomBackButton;
}
```

3. When registering the screen with the custom back button, wrap it in your HOC
```js
import withCustomBackButton from '../components/hoc/WithCustomBackButton';
/* ... */
Navigation.registerComponent('selectLocation', () => withCustomBackButton(SelectLocation));
```

**Comment by bneigher** [comment]
@Gujie-Novade I tried your solution but neither the default nor the custom back button is triggering the `navigationButtonPressed` for me.  Do you know if this works with v3?
