### ISSUE TITLE
Invariant Violation: Objects are not valid as Reach child (found: objects with keys....

### ISSUE THREAD

**Issue by efec89** [wix/react-native-navigation#4784]
### Issue Description
I'm trying to create bottom tab bars. But I got an error. When i press Dismiss button, everythings working. But why this error shows? 

`import { Navigation } from "react-native-navigation";
import HomeScreen from "./screens/HomeScreen";
import GarajimScreen from "./screens/GarajimScreen";
import { App } from './App'

Navigation.registerComponent("example.HomeScreen", ()=> HomeScreen);
Navigation.registerComponent("example.GarajimScreen", ()=> GarajimScreen);

export default () => Navigation.setRoot({
  root: {
    bottomTabs: {
      children: [
        {
          component: {
            name: 'example.HomeScreen',
            options: {
              bottomTab: {
                text: 'Tab 1',
                icon: require('./assets/images/activeHome.png')
              }
            },
          },
        },
        {
          component: {
            name: 'example.GarajimScreen',
            options: {
              bottomTab: {
                text: 'Tab 2',
                icon: require('./assets/images/activeHome.png')
              }
            },
          },
        },
      ],
    },
  }
});
`

### Steps to Reproduce / Code Snippets / Screenshots

![screenshot_1551104802](https://user-images.githubusercontent.com/6522288/53344177-1a561b00-3923-11e9-8640-73df9bf1f0b6.png)

---
### Environment
* React Native Navigation version: ^2.12.0
* React Native version: 0.58.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Similator, Android 8.1.0, Debug

**Comment by Estebank94** [comment]
I am having the same issue. How did you fix it?
