### ISSUE TITLE
WARNING: Module 'react-native-navigation' has variant 'reactNative56Debug' selected, but the module ''app'' depends on variant 'reactNative57_5Debug'

### ISSUE THREAD

**Issue by harleenarora** [wix/react-native-navigation#4787]
Hi,
I am using latest version of react-native-navigation, but I got one warning on my android studio 

WARNING: Module 'react-native-navigation' has variant 'reactNative56Debug' selected, but the module ''app'' depends on variant 'reactNative57_5Debug'
Select 'react-native-navigation' in "Build Variants" window
Fix problem

**Comment by jinshin1013** [comment]
Have you followed the doc [here?](http://wix.github.io/react-native-navigation/#/docs/Installing?id=_72-ignore-other-rnn-flavors)

**Comment by cvongrim** [comment]
This seems to start happening to me when I upgraded Android Studio to 3.3.1

**Comment by kirhim** [comment]
I have same issue how did you fix it?
