### ISSUE TITLE
Top bar not showing correctly

### ISSUE THREAD

**Issue by Sadhr** [wix/react-native-navigation#4789]
### Issue Description

When I'm pushing a new screen I got only half from the top bar but my other screens work as expected 

### Steps to Reproduce / Code Snippets / Screenshots

 ```                                                       
Navigation.push(this.props.componentId, {
      component: {
        name: "futsal-schedule.MapDetail",
        options: {
          sideMenu: {
            left: {
              visible: false,
              enabled: false
            }
          },
          topBar: {
            title: {
              text: "Map"
            },
            leftButtons: [
              {
                
                //icon: ,
                color: "white"
              }
            ],
            visible: true,
            drawBehind: true,
            background: { color: "#25B02C" },
            backButton: { visible: false }
          },
          bottomTabs: { visible: false, drawBehind: true, animate: true }
        }
      }
    });
```                                                  

![screenshot_1551182255](https://user-images.githubusercontent.com/9772227/53411833-e08b2000-39c7-11e9-897b-c5dadade493c.png)

---
### Environment
* React Native Navigation version: 2.5.1
* React Native version: 0.58.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device

**Comment by Sadhr** [comment]
I just need to put componentDidDisappear and componentDidAppear

**Comment by bneigher** [comment]
@Sadhr what did you do to solve this?  also I live like 2 blocks from you hahah
