### ISSUE TITLE
Why Android App showing blank screen when coming out of an App with back button React Native Navigation?

### ISSUE THREAD

**Issue by archana-iron** [wix/react-native-navigation#4790]
**Issue Description**

I am working on React Native Application and integrated react-native-navigation package for navigation inside app.
Android App got stuck and show blank screen. This happens if I am closing app using back button in case of Android app. At the end I have a listing page, after reopen the application it shows blank screen because it's not calling `Navigation.registerComponent` again.
This is a code inside my index.js::

```
import { Navigation } from "react-native-navigation";
import App from './src/app';

Navigation.registerComponent("appName", () => App); 
```

Killing the app and restarting would fix the stuck on splash screen issue. But shouldn't be stuck in the first place. Just an issue when closing through back button.

Please suggest me how can I handle and call my index.js code once again after closing app using Android back button.

**Environment**
* React Native Navigation version: 2.12.0
* React Native version: 0.58
* Platform(s) : Android only

**Comment by iksent** [comment]
I am having the same problem in Production.
