### ISSUE TITLE
[V2] Lack of componentWillAppear/componentWillDisappear

### ISSUE THREAD

**Issue by aafarian** [wix/react-native-navigation#4793]
### Issue Description

We don't have access to a componentWillAppear/componentWillDisappear in V2.

Currently, when trying to migrate onNavigatorEvent events, we can migrate "didAppear", "didDisappear", "bottomTabReselected" (although for that one we have to manually compare the current/target tab to see if they're the same). 

"didAppear" --> componentDidAppear
"didDisappear" --> componentDidDisappear
"willAppear" --> ?
"willDisappear" --> ?

I'm aware that we have componentDidMount/componentDidUnmount, but those will not fire when a modal is opened/closed that was on top of your screen, whereas "didAppear" used to fire on a root page when you closed a modal on top of it and "didDisappear" will fire off when you open a modal on top of a root page.

---
### Environment
* React Native Navigation version: 2.12.0
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by donovanhiland** [comment]
Have you by chance subscribed to navigation events in this component via something like:

```
  componentDidMount() {
    this.navigationEventListener = Navigation.events().bindComponent(this);
  }
```

**Comment by aafarian** [comment]
@donovanhiland yes, I've subscribed - which gives me access to `componentDidAppear` and `componentDidDisappear`, but not `componentWillAppear` (or an equivalent) or `componentWillDisappear` (or an equivalent). In fact, if you search through the whole repo, you won't find those anywhere.

**Comment by guyca** [comment]
Hey @aafarian 
Indeed, v2 doesn't expose will appear simply because they aren't reliable. In v1, both `willAppear` and `willDisappear` were emitted from native. This makes them irrelevant since if the bridge or Js thread are busy, they will be handled by you after the component has already appeared. In other words, they are meaningless due to the async nature of RN.
