### ISSUE TITLE
[v2] Trying to put a badge on a bottomTab with mergeOptions throws and error and freezes my app

### ISSUE THREAD

**Issue by thinklinux** [wix/react-native-navigation#4796]
### Issue Description

Trying to put a badge on a bottomTab with mergeOptions throws and error and freezes my app

### Steps to Reproduce

```js
  useEffect(() => {
    Navigation.mergeOptions(componentId, {
      bottomTab: {
        badge: 2,
        badgeColor: 'red',
      },
    });
  }, []);
```

### Error

![screenshot 2019-02-27 at 13 31 00](https://user-images.githubusercontent.com/326949/53487405-30371d80-3a94-11e9-9025-d8af525fcf56.png)

---
### Environment
* React Native Navigation version: 2.12.0
* React Native version: 0.59.0-rc.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by ItsNoHax** [comment]
Can you try passing the value as a string? `${value}`

**Comment by thinklinux** [comment]
Oh my god I need to read more carefully... Thanks @ItsNoHax :)) Closing this one.
