### ISSUE TITLE
Mobx observable objects are no longer observable when passed with a pushed screen

### ISSUE THREAD

**Issue by EliSadaka** [wix/react-native-navigation#4798]
### Issue Description

Our app is using Mobx for state management. When I attempt to pass an observable object with a pushed screen, the prop is no longer observable in the new screen. Is this a bug or intended behaviour, and is there a workaround?

### Steps to Reproduce / Code Snippets / Screenshots
The observable object is first defined:

```js
@observable user = {} // user object is populated with data later
```

Then later, a new screen is pushed with the user object passed as a prop:
```js
console.log(isObservable(this.user)) // this will output 'true'
Navigation.push(this.props.componentId, {
	component: {
		name: 'ProfileScreen',
		passProps: {
			user: this.user
		},
	}
})
```

However, testing the observability in the pushed screen shows that it is no longer an observable:
```js
constructor(props) {
	super(props);
	console.log(isObservable(this.props.user)) // this will output 'false'
}
```
---
### Environment
* React Native Navigation version: 2.11.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel 2, iPhone SE in Debug

**Comment by guyca** [comment]
Hey @EliSadaka 
We clone props to avoid mutation issues - I'm assuming that breaks the observable contract. You can handle these situations yourself 👍

**Comment by lukescott** [comment]
@guyca I am migrating from NavigationIOS. I am running into the issue of props being cloned. Is there any way to work around this? I am passing a class and it appears that my class is being cloned.

**Comment by EliSadaka** [comment]
@lukescott I worked around this issue by passing a function and retrieving the desired object that way.

```
Navigation.showModal({
   stack: {
      children: [{
         component: {
            name: "VideoScreen",
            passProps: {
               activity: (() => { return this.props.activity }),
            },
         }
      }]
   }
});
```
```
constructor(props) {
    super(props);

    if (typeof this.props.activity === 'function') {
      this.activity = this.props.activity()
    }
}
```
