### ISSUE TITLE
NavigationExperimental ?

### ISSUE THREAD

**Issue by Vani-gurnani** [wix/react-native-navigation#48]
Any plans to use this library with React-Native's NavigationExperimental so Android and IOS both can work?

**Comment by MattDavies** [comment]
See https://github.com/wix/react-native-navigation/issues/5#issuecomment-217704276, there is work in progress to support Android natively.

**Comment by guyca** [comment]
As @MattDavies mentioned, we already support Android. You can refer to the link in Matt's comment for installation instructions. We will update the docs soon since the Android version has reached feature parity with the iOS version.
