### ISSUE TITLE
[Android][Stuck] when a screen was closed

### ISSUE THREAD

**Issue by congnguyen91** [wix/react-native-navigation#4801]
### Issue Description

[Can not interact with any button/component when user close a screen]

### Steps to Reproduce / Code Snippets / Screenshots
1) Screen A includes a map.
2) Push a screen from SCREEN_A => call it as SCREEN_B
3) Touch an Input => Keyboard show
4) Click back button on the TopBar / not backButton of the device=> Keyboard close & Screen Close at the same time
5) Cann't move the map in SCREEN_A

NOTE: It was normal when the Keyboard closed then the screen closed

---
### Environment
* React Native Navigation version: 2.12.0
* React Native version: 0.58.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Debug & Release

**Comment by luoyushouchai** [comment]
@congnguyen91 Have you fixed this?
