### ISSUE TITLE
Playground project should have seperate package.json

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#4805]
### Issue Description

When updating to RNN 2.13.0 I'm seeing dependencies being added to my own project:
- react-native-ui-lib (has 7-8 dependencies)
- Possibly others related to the playground project

These could be easily avoided by moving the package.json of the playground project into /playground/ directory.

### Steps to Reproduce / Code Snippets / Screenshots

```
yarn add react-native-navigation@latest
```

Observe yarn.lock/package.lock changes

**Comment by guyca** [comment]
Will be fixed in 2.13.1. Thanks @ItsNoHax 💪
