### ISSUE TITLE
[V2] Navigation.constants() produces error.

### ISSUE THREAD

**Issue by vnshgrg** [wix/react-native-navigation#4807]
### Issue Description

I am trying to get the statusBarHeight and topBarHeight but when used `Navigation.constants()` anywhere in my code throws Fatal error:
`Exception '-[RNNSideMenuController tabBar]: unrecognized selector sent to instance 0x7f81a7070a00' was thrown while invoking getConstants on target RNNBridgeModule with params (
    216,
    217
)`

###  Code Snippets

```js
const NavConstants = await Navigation.constants();
const statusBarHeight = NavConstants.statusBarHeight;
const topBarHeight = NavConstants.topBarHeight;
console.log(statusBarheight, topBarHeight);
```

### Screenshot of error

![simulator screen shot - iphone x - 2019-03-03 at 12 57 05](https://user-images.githubusercontent.com/3870529/53692246-81a51c80-3db4-11e9-9c1d-a2738139b576.png)

---
### Environment
* React Native Navigation version: ^2.12.0
* React Native version: 0.58.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both Simulator & Device

**Comment by barbarossusuz** [comment]
Same here

**Comment by guyca** [comment]
Have you tried getting `Navigation.constants` after root is displayed?

You can use the https://wix.github.io/react-native-navigation/#/docs/events?id=registercommandcompletedlistener listener for that

**Comment by preko96** [comment]
For me it's produced error on a root without a visible topbar and bottom tab.

**Comment by barbarossusuz** [comment]
> Have you tried getting `Navigation.constants` after root is displayed?
> 
> You can use the https://wix.github.io/react-native-navigation/#/docs/events?id=registercommandcompletedlistener listener for that

Yes , actually im calling it after everything :) .
Thank you i will try with listener

**Comment by vnshgrg** [comment]
> Have you tried getting `Navigation.constants` after root is displayed?
> 
> You can use the https://wix.github.io/react-native-navigation/#/docs/events?id=registercommandcompletedlistener listener for that

Yes, also tried getting `constants` with listeners but same error.

However I am not sure if I used the listeners properly. Here's the code I used:

```
const commandCompletedListener = Navigation.events().registerCommandCompletedListener(
    ({ commandId, completionTime, params }) => {
        console.log(commandId, params);
        if (
            commandId === "setRoot" &&
            params.layout.root.id === "MainSideMenu" // ID of my root sideMenu Stack
        ) {
            Navigation.constants().then(result => {
                console.log(result);
            });
        }
    }
);
```

**Comment by RiCoTeRoX** [comment]
Same here.

I added in the Navigation.events().registerAppLaunchedListener() but same error. :'(

**Comment by kriptonhaz** [comment]
just barely got the same problem, with or without listener produce the same error.

**Comment by matpaul** [comment]
As i undertan this issue reproduce if contants() fired when no tabBars

here patch to Fix (just try catch on bottomTabsHeight)

```
patch-package
--- a/node_modules/react-native-navigation/lib/ios/Constants.m
+++ b/node_modules/react-native-navigation/lib/ios/Constants.m
@@ -15,7 +15,11 @@ + (CGFloat)statusBarHeight {
 }
 
 + (CGFloat)bottomTabsHeight {
-	return CGRectGetHeight(((UITabBarController *)((UIWindow *)(UIApplication.sharedApplication.windows[0])).rootViewController).tabBar.frame);
+	@try {
+		return CGRectGetHeight(((UITabBarController *)((UIWindow *)(UIApplication.sharedApplication.windows[0])).rootViewController).tabBar.frame);
+	} @catch (NSException *exception) {
+		return 0;
+	}
 }
 
 @end
```

**Comment by Axxxx0n** [comment]
@matpaul fix is working, is there PR for this?

**Comment by matpaul** [comment]
@Axxxx0n no, my patch is crutch fix ))

**Comment by mo-ah-dawood** [comment]
same here

**Comment by zabojad** [comment]
This is still happening with v 2.17.0 :(...

**Comment by ssg-luke** [comment]
Fixing this in my app was much simpler than I expected. I was grabbing constants during async componentDidMount(). I moved the code into async componentDidAppear() and have not seen the error since.

**Comment by vaskolnikov** [comment]
Works with great
"react-native": "0.59.2",
 "react-native-navigation": "^2.17.0",
 "react-native-splash-screen": "^3.2.0",

**Comment by renrizzolo** [comment]
```
Navigation.setRoot({...})
```

**Comment by zabojad** [comment]
Still happening with RNN v 2.20.2

**Comment by mayconmesquita** [comment]
Still happening. This is a critical bug.

**Comment by daveyjones** [comment]
I was having the same issue when using  `Navigation.constants()` on a project with no tab bar. Adding a try/catch as suggested by @matpaul resolved the issue for me, and seems like a perfectly valid permanent fix, so I submitted a PR: https://github.com/wix/react-native-navigation/pull/5201
