### ISSUE TITLE
[V2] Black screen on iPad

### ISSUE THREAD

**Issue by dungnguyen10989** [wix/react-native-navigation#4811]
Everything is working on iPhone with rnn@2.13.1, but it only show black screen on iPad with set devices=iPad or devices=universal. If I downgrade to rnn@2.0.2070, I will be wright, but other issus has happen( black screen when hide drawer ... ).
Any solution to fix it?

**Comment by rangav** [comment]
Duplicate issue see [4580](https://github.com/wix/react-native-navigation/issues/4580)
