### ISSUE TITLE
[v2][iOS] Back gesture doesn't work when topBar.leftButtons have some custom icons

### ISSUE THREAD

**Issue by retyui** [wix/react-native-navigation#4813]
### Issue Description
When a pushed scene  has custom `options.topBar.leftButtons` icons a back gesture doesn't work (you can only open leftMenu)!

But when  a pushed scene  hasn't  a custom `options.topBar.leftButtons` 
You can:
* open a left menu 
* and back to perv. screen using a back gesture

### Steps to Reproduce / Code Snippets / Screenshots
Reproduce demo code: https://gist.github.com/retyui/a8ced587eed30c382e84c465e76c5d96

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Real device \ Debug

**Comment by retyui** [comment]
https://github.com/wix/react-native-navigation/issues/4455

**Comment by retyui** [comment]
Up

**Comment by retyui** [comment]
up

**Comment by retyui** [comment]
Up

**Comment by guyca** [comment]
Hey @retyui 
Could you please fork the repo and push a branch with a reproduction?

**Comment by retyui** [comment]
I do not understand the whole thing I need to do

**Comment by guyca** [comment]
Sorry for not being clear enough. Fork the repository, and push a branch to your fork with a reproduction in the playground app.

**Comment by retyui** [comment]
But I provided  the reproduce demo gist with an example of a problem

**Comment by yogevbd** [comment]
Does not reproduce in the latest version. If it still reproduce for you please let us know and we will reopen. thanks
