### ISSUE TITLE
[v2][Android] Side Menu closes automatically

### ISSUE THREAD

**Issue by retyui** [wix/react-native-navigation#4815]
### Issue Description
You can see two cases in my code snippet:
<details>
  <summary><code>Navigation.push(id, { /*... scene + close left menu ...*/ })</code></summary>
<img src="https://user-images.githubusercontent.com/4661784/53741790-32401880-3ea8-11e9-8b45-9a51dd0ea333.gif"/>
</details>

---

<details>
  <summary>
<code>
Navigation.mergeOptions(id, { /*... close left menu ...*/ })

Navigation.push(id, { /*... scene ...*/ })
</code>
</summary>
<img src="https://user-images.githubusercontent.com/4661784/53741873-61ef2080-3ea8-11e9-8a51-cf31767b6314.gif"/>
</details>

---

Something strange happening on Android when passing:
```js
sideMenu: {
    left: {
      visible: false,
    },
  },
```
And then try to open menu

### Steps to Reproduce / Code Snippets / Screenshots

It is code for reproduce this bag: https://gist.github.com/retyui/2d2417970f28f7a0cc5c7c8c140d367b

---

### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device \ Debug

**Comment by retyui** [comment]
https://github.com/wix/react-native-navigation/issues/4696

**Comment by enisinanaj** [comment]
call mergeOptions with the same id:

```
export const ProtectedViewNavigation = {
  sideMenu: {
    id: 'SideMenuContainer',
    left: {
      component: {
        id: "Drawer",
        name: "navigation.Drawer"
      }
    },
    center: {
      stack: {
        id: 'CenterStack',
        children: [
          {
            component: {
              id: 'HomeComponent',
              name: 'Home'
            }
          }
        ]
      }
    }
  }
}
```

and the function to close it

```
closeDrawer() {
        Navigation.mergeOptions('SideMenuContainer', {
            sideMenu: {
                left: {
                    visible: false
                }
            }
        })
    }
```

**Comment by retyui** [comment]
@enisinanaj 
What difference between call `.mergeOptions()` with a scene ID or a side menu ID?

**Comment by retyui** [comment]
<details>
  <summary>Click to open working example (thanks @enisinanaj)</summary>
<pre>
import React from 'react';
import { Button, View, Text } from 'react-native';
import { Navigation } from 'react-native-navigation';

const MENU_SCENE_ID = 'MENU_SCENE_ID';
const MENU_SCENE = 'MENU_SCENE';
const MAIN_SCREEN = 'MAIN_SCREEN';
const PROFILE_SCENE = 'PROFILE_SCENE';

const closeLeftMenu = {
  sideMenu: {
    left: {
      visible: false,
    },
  },
};

const state = Object.seal({ componentId: null });

export const closeAndPushToProfile = async () => {
  await Navigation.push(state.componentId, {
    component: {
      name: PROFILE_SCENE,
      passProps: {
        text: PROFILE_SCENE,
      },
    },
  });

  await Navigation.mergeOptions(MENU_SCENE_ID, closeLeftMenu);
};

const App = () => (
  <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
    <Text style={{ fontSize: 20 }}>MAIN_SCREEN</Text>
    <Text style={{ fontSize: 20 }}>Open left menu</Text>
  </View>
);

const Menu = () => (
  <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
    <Button
      onPress={closeAndPushToProfile}
      title="push(Profile) => closeMenu()"
    />
  </View>
);

const Profile = ({ text }) => (
  <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
    <Text style={{ fontSize: 20 }}>{text}</Text>
  </View>
);
Navigation.registerComponent(MAIN_SCREEN, () => App);
Navigation.registerComponent(MENU_SCENE, () => Menu);
Navigation.registerComponent(PROFILE_SCENE, () => Profile);

Navigation.events().registerComponentDidAppearListener(
  ({ componentId, componentName }) => {
    console.log(' --- componentId, componentName', componentId, componentName);
    if (componentName !== MENU_SCENE) {
      state.componentId = componentId;
    }
  },
);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      sideMenu: {
        id: MENU_SCENE_ID,
        left: {
          component: {
            name: MENU_SCENE,
          },
        },
        center: {
          stack: {
            children: [
              {
                component: {
                  name: MAIN_SCREEN,
                  options: {
                    topBar: {
                      title: {
                        text: MAIN_SCREEN,
                      },
                    },
                  },
                },
              },
            ],
          },
        },
      },
    },
  });
});
</pre>
</details>
