### ISSUE TITLE
[Regression] [iOS] TextInput focusing in componentDidMount broken in Overlays

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#4824]
### Issue Description

Regarding MR: https://github.com/wix/react-native-navigation/pull/4778

It seems like that MR has caused some regression regarding TextInput focusing.
TextInputs with autoFocus prop or focusing in componentDidMount no longer work.

### Steps to Reproduce / Code Snippets / Screenshots

Overlay with following code:

```js
componentDidMount() {
  this.textInput.focus();
}

render() {
return (
 <TextInput
   ref={(ref) => { this.textInput = ref; }}
   ...otherProps
 />
)
```

or

```js

render() {
return (
 <TextInput
   autoFocus
   ...otherProps
 />
)
```

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by yogevbd** [comment]
@ItsNoHax You can now make your overlay respond keyboard events by passing `overlay.handleKeyboardEvents: true` option

**Comment by samahndev** [comment]
Hi @yogevbd - The issue where `autoFocus` on `TextInput` in Overlays which doesn't launch soft keyboard still seems to be an issue even on v4.0.3.

I did add `overlay.handleKeyboardEvents: true` option.

**Comment by cspicuzza** [comment]
RN: 0.61.5
RNN: 4.8.4

I'm having the same issue with `<TextInput autoFocus>` being ignored on showModal()

**Comment by zabojad** [comment]
Same here :( 
RNN 6.10.1
RN 0.63.3

**Comment by JasonXiang2014** [comment]
Same here :(
RNN 7.8.4
RN 0.63.4
