### ISSUE TITLE
[Android] font awesome icon size too small in release build

### ISSUE THREAD

**Issue by matthiasdilger** [wix/react-native-navigation#483]
### Issue Description

Loading Font Awesome icons with a Promise and setting them as rightButtons. Works perfectly on iOS and Android debug, but the icons are tiny in Android release build.

### Steps to Reproduce / Code Snippets / Screenshots

Tiny icons in Release build
<img width="406" alt="screen shot 2016-11-22 at 21 21 08" src="https://cloud.githubusercontent.com/assets/5625718/20525319/bb53c8b8-b0f9-11e6-85d9-a1a17f7a31d3.png">

Correct icons in debug build
<img width="406" alt="screen shot 2016-11-22 at 21 21 37" src="https://cloud.githubusercontent.com/assets/5625718/20525339/df0be2f4-b0f9-11e6-9598-eb45aa700c12.png">

---
### Environment
* React Native Navigation version: 2.0.0-experimental.142
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android RELEASE only
* Device info (Simulator/Device? OS version? Debug/Release?): Android 6.0, Release

**Comment by guyca** [comment]
I'm not familiar with font awesome, is that a vector icons library? Can you upload your release apk file?

**Comment by matthiasdilger** [comment]
Yes, font awesome is part of react-native-vector-icons. I can try to build a release without login, but it will take some time.

**Comment by guyca** [comment]
Do you use BottomTabs in your app? Does the problem appear there as well?

**Comment by matthiasdilger** [comment]
I use bottom tabs but there the same icons work fine

**Comment by guyca** [comment]
Can you upload a release apk? I don't want to install the app, just inspect the apk.

**Comment by matthiasdilger** [comment]
Ok, here you go
[app-release.zip](https://github.com/wix/react-native-navigation/files/606561/app-release.zip)

**Comment by guyca** [comment]
Does this happen on all Android OS version?

**Comment by guyca** [comment]
Did you follow the gist posted [here](https://github.com/wix/react-native-navigation/issues/43#issuecomment-223907515)?

I think a lot of people here are using rn-vector-icons with RNN and this is the first time someone reports an issue like this..

**Comment by matthiasdilger** [comment]
Yes, I copied [this version](https://gist.github.com/dropfen/4a2209d7274788027f782e8655be198f)
I only have Android 6.0 available right now, no simulator installed, sorry

**Comment by guyca** [comment]
I'll try to look into this on Thursday, I suggest you ask in #43 as well.

**Comment by guyca** [comment]
@matthiasdilger Any updates?

**Comment by matthiasdilger** [comment]
Nope, still same problem. For now I use PNGs on Android (downloaded from http://fa2png.io)

**Comment by kristiansorens** [comment]
I'm having the same issue. I'm using the IonIcons though.

**Comment by matthiasdilger** [comment]
Please see https://github.com/wix/react-native-navigation/issues/43#issuecomment-267370982

Closing this bug. Thanks @guyca
