### ISSUE TITLE
Best design pattern for uppermost wrapped component(migrating from react-navigation)

### ISSUE THREAD

**Issue by hahtml** [wix/react-native-navigation#4830]
### Issue Description

I am currently migrating my codebase from react-navigation to RNN. For the previous implementation, I have two more wrapped components under the Provider component. The architecture shows below
```text
<Provider>
  <WebsocketManager>
     <ConnectionManager>
        <App> (render react-navigation navigator inside)
     </ConnectionManager>
  </WebsocketManager>
</Provider>
```

But right now if I understand and implement correctly, the new architecture of RNN should be this way 
```text
<Provider>
  <Screen 1 />
</Provider>

<Provider>
  <Screen 2 />
</Provider>
```
These screens share the same redux store. But what is the best way to embed my two more upper components here? Notice that I need those screen to use the same instance like singleton way. If I use HOC to wrap the Screen 1 and Screen 2..., each screen will be wrapped by new instances of managers. Some logics like open ws might run multiple times if there is no global flag to control. I am wondering if there is a RNN way to handle this condition and what the best design pattern is.

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Not related

**Comment by jinshin1013** [comment]
I'm not sure how your `managers` are being instantiated but you could instantiate those in the files where you register all your screens and pass it as a prop so that your `provider` files get the same instance. Very naive example:

```jsx
// Provider.js
export const createProvider = (WrappedComponent, store, managers) => {
  class HOC extends React.Component {
    render() {
      return (
        <Provider store={store}>
          <WebSocketManager manager={managers.websocket}>
            <ConnectionManager manager={managers.connection}>
              <WrappedComponent {...this.props} />
            </ConnectionManager>
          </WebSocketManager>
        </Provider>
      )
    }
  }
  return HOC
}

// App.js
import { createProvider } from './Provider'
import screens from './screens'

Navigation.events().registerAppLaunchedListener(() => {
  const store = new store()
  const websocket = new WebsocketManager()
  const connection = new ConnectionManager()

  screens.forEach((screen) => {
    Navigation.registerComponent(screen.route, () => 
      createProvider(screen.component, store, { websocket, connection })
    )
  })

  ....
})

```

**Comment by hahtml** [comment]
@jinshin1013 Thx for ur reply. But the issue is that my WebSocketManager and ConnectionManager component need to be singleton for all screens so that some state can be shared (for example, there is a ws opened or not).

Both manager component render function return chidren
```javascript
render() {
   return this.props.children;
  }
```

**Comment by jinshin1013** [comment]
I made an assumption that these websockets and connection managers can simply be a class instance and not a component where you can use like websocketManager.isOpened or something like this. That way you can just simply pass these instances to all the screens. Surely they don't have to be a component, or would you mind sharing your WebsocketManager and ConnectionManager components?

**Comment by hahtml** [comment]
Both managers include tons of functions, states and props. We use component to implement them so that some props and states are subscribed and some functions like reconnect can be self-triggered in lifecycle functions (reuse consideration).

**Comment by jinshin1013** [comment]
Yes, states and props can still be there and it can still function the same as long as you pass them with the same instance of websocket or whatever you are using. Assuming yo are using a regular WebSocket:

```jsx
// Provider.js
export const createProvider = (WrappedComponent, store, managers) => {
  class HOC extends React.Component {
    render() {
      return (
        <Provider store={store}>
          <WebSocketManager manager={managers.websocket}>
            <ConnectionManager manager={managers.connection}>
              <WrappedComponent {...this.props} />
            </ConnectionManager>
          </WebSocketManager>
        </Provider>
      )
    }
  }
  return HOC
}

// App.js
import { createProvider } from './Provider'
import screens from './screens'

Navigation.events().registerAppLaunchedListener(() => {
  const store = new store()
  const websocket = new WebSocket('ws:127.0.0.1:3000')
  // const connection = new ConnectionManager()

  screens.forEach((screen) => {
    Navigation.registerComponent(screen.route, () => 
      createProvider(screen.component, store, { websocket, connection })
    )
  })

  ....
})
```
