### ISSUE TITLE
anrdroid bottomTabs click  How to close water ripple and animation

### ISSUE THREAD

**Issue by rc558620** [wix/react-native-navigation#4833]
bottomTabs: {
            titleDisplayMode: "alwaysShow", 
            backgroundColor: '#FFFF00',
            // barStyle: 'black',
            // translucent: false,
            // hideShadow: true
        },

**Comment by danghung24031992** [comment]
### Disable tabbar animation  on android , add to file dimen in react-native-navigation project
<dimen name="bottom_navigation_text_size_active">11sp</dimen>
<dimen name="bottom_navigation_text_size_inactive">11sp</dimen>
<dimen name="bottom_navigation_text_size_forced_active">11sp</dimen>
<dimen name="bottom_navigation_text_size_forced_inactive">11sp</dimen>
<dimen name="bottom_navigation_margin_top_active">6dp</dimen>
<dimen name="bottom_navigation_margin_top_inactive">6dp</dimen>
