### ISSUE TITLE
Android:show white space when hidden bottom bar 

### ISSUE THREAD

**Issue by danghung24031992** [wix/react-native-navigation#4834]
### When I want to hide bottom bar on android device then show white space.On iOS device not show.My code hide bottom bar when click on Button
Navigation.mergeOptions(this.props.componentId, {
      bottomTabs: {
        visible: hideBottom?false:true,
        drawBehind: true
      }
   });

<img width="459" alt="screen shot 2019-03-08 at 12 11 47 pm" src="https://user-images.githubusercontent.com/9923258/54009102-171d2380-419c-11e9-8e12-f0369a177c08.png">

**Comment by C-ollins** [comment]
I'm experiencing  same issue with the top bar

```
Navigation.setRoot({
    root: {
        stack: {
            children: [{
                component: {
                    name: "Login",
                    options: {
                        topBar: {
                            visible: false,
                        }
                    }
                }
            }]
        }
    }
});
```

![screenshot_1552025138](https://user-images.githubusercontent.com/19960200/54010848-b88e8000-4170-11e9-9add-05d09c85731d.png)

**Comment by danghung24031992** [comment]
> I'm experiencing same issue with the top bar
> 
> ```
> Navigation.setRoot({
>     root: {
>         stack: {
>             children: [{
>                 component: {
>                     name: "Login",
>                     options: {
>                         topBar: {
>                             visible: false,
>                         }
>                     }
>                 }
>             }]
>         }
>     }
> });
> ```
> ![screenshot_1552025138](https://user-images.githubusercontent.com/19960200/54010848-b88e8000-4170-11e9-9add-05d09c85731d.png)

You can add drawBehind:true like this

Navigation.setRoot({
    root: {
        stack: {
            children: [{
                component: {
                    name: "Login",
                    options: {
                        topBar: {
                            visible: false,
                            drawBehind:true
                        }
                    }
                }
            }]
        }
    }
});

**Comment by danghung24031992** [comment]
I fixed my issue.
I add tab.requestLayout(); to class BottomTabsPresenter > function name mergeDrawBehind > line 131.

**Comment by C-ollins** [comment]
Thanks for the solution.

**Comment by sinxwal** [comment]
@danghung24031992   this is wired solution

**Comment by msqar** [comment]
Happens the same for me in iOS, any solution?
