### ISSUE TITLE
[V2] Custom tab bar button/programmatically change active tab

### ISSUE THREAD

**Issue by szemannp** [wix/react-native-navigation#4837]
### Issue Description

I have 3 tab bar buttons with 2 proper stacks on the left and right, however, the middle tab bar button should be a custom element which if clicked brings up an overlay with >1 opacity over the active screen (from either proper stacks). Closing this modal should result in remaining on the screen where the overlay button was clicked (one of the side stacks). Is there any way this concept could be implemented in the current state of RNN V2?

So far the worst case scenario idea is to clone the last active screen and place it under the overlay, but still there's no solution to programmatically navigate back to the previously active tab/stack. 

---
### Environment
* React Native Navigation version: 2.12.0
* React Native version: 0.58.4
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all devices

**Comment by jayeshanandani** [comment]
any solution for same?

**Comment by donnes** [comment]
I'm interested about this too!

**Comment by eurobob** [comment]
Hey wix team!

You can't just sit there and pat yourselves on the back for reduced workload if the stalebot just closes issues that you couldn't be bothered to reply to!
