### ISSUE TITLE
How to disable addDefaultSplashLayout in NavigationActivity on android ?

### ISSUE THREAD

**Issue by RoiDayan1** [wix/react-native-navigation#4840]
### When app starts its shows white screen between splash screen and first navigation route.

I've been researched it and came to it that this is because of addDefaultSplashLayout in the NavigationActivity fired from  onCreate.
when i delete this call, the native splash is hanging and the first navigation route never appears.

i want to show the first navigation route immediately when app starts or immediately after native splash screen.

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): Android

**Comment by billyohgren** [comment]
Hi @RoiDayan1 ,

I had the same issue and I _think_ I solved it by adding this in my MainActivity.java:

```
@Override
    protected void addDefaultSplashLayout() {
        View view = new View(this);
        view.setBackgroundColor(Color.parseColor("#1C299F"));
        setContentView(view);
    }

```

Where #1C299F is the background color you would the to use instead of white. 

Hope it helps!

**Comment by RoiDayan1** [comment]
this exactly what I did.. thank you.
