### ISSUE TITLE
BottomTabs with Stack; Icon disappears after updating tab text

### ISSUE THREAD

**Issue by smeevil** [wix/react-native-navigation#4841]
### Issue Description

When I update the text of a bottom bar tab which is a stack, it loses its icon.
This does work properly on a 'plain' child without a stack.

### Steps to Reproduce / Code Snippets / Screenshots

```js
  Navigation.events().registerAppLaunchedListener(() => {
      Navigation.setRoot({
          root: {
            bottomTabs: {
              id: "BottomTabsId",
              children: [                
                {
                  stack: {
                    id: "MyScreenStackId",
                    children: [
                      {
                        component: {
                          id: "MyScreenId",
                          name: "Foo",
                          options: {
                            bottomTab: {
                              text: "Foo",
                              icon: icons.archive,
                              iconColor
                            },
                            topBar: {
                              visible: false,
                            }
                          }
                        }
                      }
                    ],
                  }
                },                
              ],
            }
          }
        }
      ).then();
    }
  );
```
Then call : 

```js
Navigation.mergeOptions("MyScreenId", {bottomTab: {text: "Bar"}});
```

The text is updated on the tab, but the icon disappears.
The current workaround I apply is :

```js
Icon.getImageSource("ios-archive", 30).then((icon: number) => {
  Navigation.mergeOptions("MyScreenId", {
    bottomTab: {
      text: "Bar",
      icon,
      iconColor: "#6177cc"
    }
  });
});
```
---
### Environment
* React Native Navigation version: ^2.13.1
* React Native version: 0.59.0-rc.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Real Device (iPhone XR)

**Comment by julianklumpers** [comment]
Same problem here

**Comment by msqar** [comment]
Same problem here as well!!! any ideas? what is going on? i just change currentTabIndex and sometimes my bottomTabs will disappear. (iOS)

**Comment by herarya** [comment]
same issue, any solution?

**Comment by MrAlekhin** [comment]
the same issue

**Comment by parth-koshta** [comment]
Anyone find any solution? I'm also having same issue

**Comment by lprhodes** [comment]
I'm still seeing this, did anyone find a fix?

**Comment by parth-koshta** [comment]
Hey @lprhodes 
I fixed it by passing all the options to mergeOptions() for that bottomTab again, instead of passing just the updated ones.

**Comment by lprhodes** [comment]
Thanks @parth-koshta 

My issue was different. It turns out that if you set a badge on a tab while the tab bar is hidden (i.e. a new screen has been pushed) then it will sometimes mess up with the tab bar layout
