### ISSUE TITLE
[V2] componentDidAppear seems too slow to trigger

### ISSUE THREAD

**Issue by zhaiduo** [wix/react-native-navigation#4846]
### Issue Description

Hi guys, 

I'm new to V2, so excited.
But it seems componentDidAppear triggered 2 more seconds later after componentDidMount.
Is there any ways to improve this?

Thanks very much~

> 03-11 15:01:30.766 26148-26179/com.app I/ReactNativeJS: '[99]===>: ', 'startScreen componentDidMount'
> 03-11 15:01:33.442 26148-26179/com.app I/ReactNativeJS: '[2676]===>: ', 'startScreen DidAppear'

```javascript
class StartScreen extends React.PureComponent {
  private navigationEventListener: any;
  public componentDidMount() {
    this.navigationEventListener = Navigation.events().bindComponent(this);
    echo("startScreen componentDidMount");
  }
  public componentDidAppear() {
    echo("startScreen DidAppear");
  }
```

### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device 24API

**Comment by guyca** [comment]
Hey there, and welcome to RNN 👋 
The reason for the delay is that `componentDidMount` is triggered from JS, while `componentDidAppear` is emitted from native.
To minimise the gap, reduce the work you're doing in Js when a screen is displayed to a minimum.

At Wix, we don't do any logic in constructors and `CDM`.
Good luck 👍

**Comment by zhaiduo** [comment]
Thanks for the advices~ @guyca
