### ISSUE TITLE
Cannot read property 'navigatorStyle' of undefined

### ISSUE THREAD

**Issue by florianbepunkt** [wix/react-native-navigation#485]
I tried to incorporate the library into my project, got the error in the title when running in simulator. my app initialization is this:

```js
import { Navigation } from 'react-native-navigation';

import { StartPage } from './app/startPage.js';
import { FirebaseTestPage } from './app/firebaseTest.js';

function registerScreens() {
  Navigation.registerComponent('roomary.StartPage', () => StartPage);
  Navigation.registerComponent('roomary.FirebaseTestPage', () => FirebaseTestPage);
}

registerScreens();

// start the app
Navigation.startTabBasedApp({
  tabs: [
    {
      label: 'One',
      screen: 'roomary.StartPage', // this is a registered name for a screen
      icon: require('./assets/img/one.png'),
      selectedIcon: require('./assets/img/one_selected.png'), // iOS only
      title: 'Screen One'
    },
    {
      label: 'Two',
      screen: 'roomary.FirebaseTestPage',
      icon: require('./assets/img/two.png'),
      selectedIcon: require('./assets/img/two_selected.png'), // iOS only
      title: 'Screen Two'
    }
  ]
});
```

---
### Environment
* React Native Navigation version: react-native-navigation@2.0.0-experimental.142 
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 6 iOS10.1

**Comment by guyca** [comment]
Hey @florianbepunkt Did you manage to make progress? `navigatorStyle` is supposed to be optional.

**Comment by florianbepunkt** [comment]
I was using this library in conjunction with firestack library… I guess somewhere in the installation process something got mixed up, but can't say for sure. If I install this library first and other libraries after this, it works fine. But not the other way around.

**Comment by wpapper** [comment]
I'm running into the same issue after following the examples in the documentation. I tried overriding the navigatorStyle with custom styling, but it didn't fix the problem.

Is there a known solution?

**Comment by wimgoeman** [comment]
I had the same issue. It took me some digging around in the code of this lib, but the reason is you are incorrectly registering the component. The function you use at regsitration time probably returns undefined. I am making a pull request to properly show this as an error.

**Comment by guyca** [comment]
Thanks a lot @wimgoeman

**Comment by bjacog** [comment]
@wimgoeman Thanks for pointing out that it is related to the registered component, you saved me a lot of time. Is there any reason why the same warning was not implemented for `_registerComponentRedux`?

**Comment by realtebo** [comment]
I've the same problem. I'm asking if how to understand  the reason of bad registration.

InternalComponent.navigatorStyleI'm getting this
```
 D ReactNative: CatalystInstanceImpl.initialize()
02-16 16:56:42.392 20994 21025 E ReactNativeJS: Navigation: FirstTabScreen registration result is 'undefined'
02-16 16:56:42.407 20994 21025 E ReactNativeJS: Error while starting app: TypeError: undefined is not an object (evaluating 'InternalComponent.navigatorStyle')
```
Of course I've no idea of whath/where is `InternalComponent.navigatorStyle`
