### ISSUE TITLE
How to animate topBar on every push in android. Currently is static on every screen push.

### ISSUE THREAD

**Issue by kamleshh-bms** [wix/react-native-navigation#4851]
I am not able to set transaction for the sticky header for android. The animation only works when show and hide topBar.

```
animations: {
            setRoot: {
                waitForRender: true,
                alpha: {
                    from: 0,
                    to: 1,
                    duration: 300
                }
            },
            push: {
                topBar: {
                    x: {
                        from: 500,
                        to: 0,
                        duration: 350
                    }
                },
            }
        }
```

### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.58.6
* Platform: Android

**Comment by david-laurentino** [comment]
I think It is not possible. I'm facing the same problem here. It seems that topbar acts as global thing, like a single instance being shared over all screens and cannot be animated between screen transitions in push commands.

**Comment by SteffenC** [comment]
I'm experiencing the same issue. TopBar is not animating.

**Comment by david-laurentino** [comment]
The solution was to replace react-native-navigation with react-navigation v4. This allows much greater customization options and provides animations smooth as butter. The documentation is great.

**Comment by vovka-s** [comment]
Not stale!
It is very usefull fiature for consistent transitions between the screens with different topBars
Do you have any desicions of thes problem?
