### ISSUE TITLE
Native Stack Animation

### ISSUE THREAD

**Issue by kamleshh-bms** [wix/react-native-navigation#4852]
### Issue Description

How to have device native animation for stack navigation as the native applications like WhatsApp.
---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.58.6
* Platform Android

**Comment by guyca** [comment]
You're referring to activity animations. RNN doesn't use activities, instead we simply add views to hierarchy, you can customise the animations as explained in the docs.
Just for reference, RNN behaves very similar to Android's new navigation component...
