### ISSUE TITLE
[iOS][v2] Support react-native 0.59.x

### ISSUE THREAD

**Issue by retyui** [wix/react-native-navigation#4853]
### Issue Description
How to apply the changes made to AppDelegate.m in react-native 0.59.0?
[diff ios/RnDiffApp/AppDelegate.m](https://github.com/react-native-community/rn-diff-purge/compare/version/0.58.6...version/0.59.0#diff-ad42fe05482c788c487f5b3a971ce4cb)

### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.59.0
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by aathapa** [comment]
Add following to your `android/app/build.gradle`
 ```diff
dependencies {
 + implementation "com.android.support:design:27.1.0"
 }
 ```

**Comment by retyui** [comment]
[Install guide](https://wix.github.io/react-native-navigation/#/docs/Installing?id=_4-update-project-dependencies-in-androidappbuildgradle) haven't this dependency

**Comment by bobber205** [comment]
Does something need to be done for 59 and iOS?

**Comment by aathapa** [comment]
Nope just follow docs..

**Comment by arnojernej** [comment]
does not work on a new project. in .59
App hangs on launchscreen with old AppDelegate.m
AppDelegate.m has changed a lot:

```cpp
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"Test"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

**Comment by djschilling** [comment]
I have the same problem.
I don't know how to apply the changes made to `AppDelegate.m` in react-native 0.59.0.

Here is a link to the changes that were made: https://github.com/react-native-community/rn-diff-purge/compare/version/0.58.6...version/0.59.0#diff-ad42fe05482c788c487f5b3a971ce4cb

**Comment by kneza23** [comment]
i got to run it without any changes to the AppDelegate.m (not sure this is right approach), but it seems the SearchBar in TopBar is crashing when you click on it.

**Comment by frederickalcantara** [comment]
Go here to solve any issues with upgrading to RN 0.59.0. 
Click here to find out any differences between your version vs the most current. That's how I got my app up running with ease. Make sure to include any RNN navigation installation on the edits as well. https://github.com/react-native-community/rn-diff-purge. Anything with versions is ok to replace, just the main install code logic you need to be wary of.

**Comment by kneza23** [comment]
@frederickalcantara what about error with search bar i have posted above?

**Comment by ceyhuno** [comment]
This worked for me:

```obj-c
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <ReactNativeNavigation/ReactNativeNavigation.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];

  [ReactNativeNavigation bootstrap:[self sourceURLForBridge: bridge] launchOptions:launchOptions];

  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

**Comment by JB-CHAUVIN** [comment]
Hello,

I have the same problem.

Anything new ? How to use react native navigation with RN 0.59 ?

Thanks

**Comment by scarlac** [comment]
Documentation should really be updated to reflect the changes since React Native 0.60.0.
