### ISSUE TITLE
[V2][iOS] Bridge associated with custom title component in navigation header is never removed.

### ISSUE THREAD

**Issue by magnusnorberg** [wix/react-native-navigation#4854]
### Issue Description

The root element (bridge) associated with a custom title component is not removed when a screen is popped from navigation stack.

See below for details. What am I supposed to do to get rid of the custom title component? Or is this a bug?

### Steps to Reproduce / Code Snippets / Screenshots

The root contains a stack:

```js
  root: {
    stack: {
      children: [{
        component: {
          name: NAV_VIEW_NAMES.Main,
          passProps: params,
        },
      }],
    },
  },
```

The Screens added to the stack are configured (via static property options) to have a custom component as the title:

```js
  topBar: {
    title: {
      component: {
        name: NAV_VIEW_NAMES._NavHeader,
        passProps: {
          someValue: 'some value',
        },
        alignment: 'fill',
      },
    },
  },
```

Running React Native Debugger and inspecting the Elements, after navigating to Main there are two root Elements:

```js
<AppContainer rootTag={401}></AppContainer>
<AppContainer rootTag={411}></AppContainer>
```

The first one corresponding to the Main screen, the second corresponding to the custom header title Component.

When I push another Screen with the same options configuration with custom component as title, there are 4 root Elements.

```js
<AppContainer rootTag={401}></AppContainer>
<AppContainer rootTag={411}></AppContainer>
<AppContainer rootTag={421}></AppContainer>
<AppContainer rootTag={431}></AppContainer>
```

Going back (either by tapping back button in header or swiping right) there are 3 root elements:

```js
<AppContainer rootTag={401}></AppContainer>
<AppContainer rootTag={411}></AppContainer>
<AppContainer rootTag={431}></AppContainer>
```

The Root element corresponding to the custom title header of the details view is not removed.

Each time I navigate to details screen and back to main, I get another live root element:

```js
<AppContainer rootTag={401}></AppContainer>
<AppContainer rootTag={411}></AppContainer>
<AppContainer rootTag={431}></AppContainer>
<AppContainer rootTag={451}></AppContainer>
<AppContainer rootTag={471}></AppContainer>
<AppContainer rootTag={491}></AppContainer>
...
```

The custom header title component is very simple:

```js
export default class SimpleNavHeader extends Component {
  render() {
    return (
      <View>
        <Text>Simple Header</Text>
      </View>
    )
  }
}
```

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.58.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iOS 12.1

**Comment by magnusnorberg** [comment]
Could someone please give me directions on this one. Am I missing something obvious? Thank you.

**Comment by cjoshi85** [comment]
@magnusnorberg I am also facing the same issue. Did you get any solution for this?
