### ISSUE TITLE
Using  StackActions.reset() makes it so navigation.state.index never changes

### ISSUE THREAD

**Issue by bobber205** [wix/react-native-navigation#4855]
### Issue Description

I followed a pretty good tutorial on how to do a temp auth loading screen where I check Async storage and redirect to the Signin in screen or to another screen as appropriate.

To prevent the user from accessing the sign in screen accidentally when using the back button (only a real concern on Android) I do the following in the below code snippet.

### Steps to Reproduce / Code Snippets / Screenshots

```js
       let destination = no_user_found ? 'SignInScreen' : 'AccountScreen';
        // let params;
        if (!no_user_found) {
            store.dispatch(setCurrentUser(JSON.parse(userToken)));
        }
        const resetAction = StackActions.reset({
            index: 0,
            actions: [NavigationActions.navigate({ routeName: destination, params: {user_id: this.props.current_user && this.props.current_user.id} })],
        });
        this.props.navigation.dispatch(resetAction);
```

This all works fine.
However when I tried to use the navigation options function for this stack like so

```js
AccountStack.navigationOptions = ({ navigation }) => {
    let tabBarVisible = true;
    console.log('Navigation State', navigation.state);
    if (navigation.state.index == 0) {
        tabBarVisible = false;
    }
    return {
        tabBarVisible
    };
```

navigation.state.index is ALWAYS 0. If I simply do

```js
this.props.navigation.navigate(destination, {user_id: this.props.current_user.id});
```

instead of dispatch there's no problem.

What am I doing wrong or how can I work around this?

---
### Environment
* React Native Navigation version: 3.1.1
* React Native version: 0.58
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): All simulators 8+

**Comment by bobber205** [comment]
I've managed to work around this issue on my project but this is still a bug it seems

**Comment by bobber205** [comment]
By workaround I mean just don't use stack actions and reset anymore.

**Comment by ItsNoHax** [comment]
Closing issue as it's not related to this library. I believe you are talking about react-navigation?
