### ISSUE TITLE
[v2][iOS] Overlay displaying over alert

### ISSUE THREAD

**Issue by phuongwd** [wix/react-native-navigation#4860]
Hi @yogevbd
### Issue Description

This issue still happening on latest code

### Steps to Reproduce / Code Snippets / Screenshots

![image](https://user-images.githubusercontent.com/2460806/54327332-4cae8a80-463c-11e9-9e6a-0095a32fb1ab.png)

### Related to
**Presenting alerts on top most window presented #4241**

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by pribeh** [comment]
Experiencing the same with 2.12.0.

**Comment by florinvasilevilsan** [comment]
Same issue here with the latest version.

**Comment by marf** [comment]
Same problem here

**Comment by ptfly** [comment]
Same here :(

**Comment by RuairiOliver** [comment]
Also having the same issue on latest version

**Comment by hisothreed** [comment]
@yogevbd adding 

```
20| [overlayWindow makeKeyAndVisible];
```
inside RNNOverlayManager.m solved it for me

**Comment by pribeh** [comment]
@yogevbd I've tried that, but if you add that line then the following issue arises

https://github.com/wix/react-native-navigation/issues/3892

**Comment by marf** [comment]
Same problem here as @pribeh reported, do someone know a way to fix it, but also be able to use Text Inputs?

**Comment by RuairiOliver** [comment]
I’ve switched to using modals with a transparent background. Works well for me.

**Comment by yogevbd** [comment]
https://github.com/wix/react-native-navigation/commit/e9ca247a524e474daf3ccf56989289ce679fc063 Adds an option which will make your overlay becomes the key window, I'm still not sure about the correct naming for this option but adding it to your overlay options will solve this issue:
```
options: {
  overlay: {
    handleKeyboardEvents: true
  }
}
```

**Comment by pribeh** [comment]
@yogevbd Thanks!
