### ISSUE TITLE
Execution failed for task ':react-native-navigation:verifyReactNative56ReleaseResources'.

### ISSUE THREAD

**Issue by archana-iron** [wix/react-native-navigation#4863]
**Issue Description**

I am getting this error while creating a release build.
Error::

```
Task :react-native-navigation:verifyReactNative56ReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:verifyReactNative56ReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  /home/iron/Desktop/LatestBookingKoala/provider-mobile-app/bkproviderapplatest/node_modules/react-native-navigation/lib/android/app/build/intermediates/res/merged/reactNative56/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
```

**React Native Environment Info:**
    Binaries:
      Node: 10.15.0 - /usr/local/opt/node@10/bin/node
      npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.4 
      react-native:  0.58.6 
      react-native-navigation: 2.12.0

Please suggest a solution for this.

**Comment by codoffer** [comment]
Facing same issue with 
react: 16.8.3
react-native: 0.59.0
react-native-navigation: ^2.13.1

**Comment by sebastialonso** [comment]
Same issue with ReactNative 0.59.1!

**Comment by nikolas7892** [comment]
+1

**Comment by guvenakcbn** [comment]
same here with RN 0.59.2

**Comment by HolySamosa** [comment]
+1

**Comment by HolySamosa** [comment]
This workaround did the trick for me:
https://github.com/wix/react-native-navigation/issues/4671#issuecomment-468546146

**Comment by wandrzejczak** [comment]
+1 same here
