### ISSUE TITLE
[V1][iOS] How to implement AppDelegate.m for React Native 0.59

### ISSUE THREAD

**Issue by IanOnFire** [wix/react-native-navigation#4864]
### Issue Description

Hi there!
We're still using react-native-navigation on v1 and are wondering how to implement the AppDelegate.m with the new structure for RN 0.59.

### Steps to Reproduce / Code Snippets / Screenshots
You could use a fresh project.
```bash
react-native-init
yarn add react-native-navigation@1.1.493
```
---
### Environment
* React Native Navigation version: 1.1.493
* React Native version: 0.59.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by nethergrim** [comment]
Yes we need some way to use `RCCManager.h` with react-native 0.59, currently it fails to launch the app

**Comment by nethergrim** [comment]
@IanOnFire  please see: https://github.com/wix/react-native-navigation/commit/57caacddfc5422c00f41b32e031a732ab503b7dc

It helped me to use V1 with RN059

**Comment by alpamys-qanybet** [comment]
@nethergrim, @IanOnFire, so how ```AppDelegate.m``` looks like?

**Comment by alpamys-qanybet** [comment]
@IanOnFire, hey guys, I do not understand, my project is even cannot build with v1 on rn59, so how you not only resolved issues but get it build?

**Comment by alpamys-qanybet** [comment]
ok guys, I do not exactly what was my problem, I tried to re-create project and problem gone, and I just left ```AppDelegate.m``` as it was in old RNNv1 documented. Don't know if it is correct or not.

**Comment by IanOnFire** [comment]
@alpamys-qanybet your `AppDelegate.m` should look like how it is described in the documentation of V1.
The commit referenced above ensures that it can understand the existing implementation of `AppDelegate.m`, so you should only update your navigation to include mentioned commit.

I can recommend updating your package.json to reference rnn like following:
`"react-native-navigation": "wix/react-native-navigation#57caacddfc5422c00f41b32e031a732ab503b7dc"`

**Comment by acollazomayer** [comment]
How does the app delegate looks like then? is too difficult to post?

**Comment by genglei01** [comment]
I got an error when update code to this commit #4775
Dimensions.get("window").width returns zero in iOS when launch,#5248
