### ISSUE TITLE
resetTo causes "Attempt to update component Text..."

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [wix/react-native-navigation#487]
### Issue Description

Bug when using *resetTo* when the stack has screens on the stack (they were added with *push*)

### Steps to Reproduce / Code Snippets / Screenshots
The user navigates throught some screens, always with *push*
Then, at some time, he reaches a screen where he ends the process and I want to navigate him to a new stack, to I'm using *resetTo*
Then I have this error:
![bugwix](https://cloud.githubusercontent.com/assets/12840136/20542039/f6604714-b0e6-11e6-803e-7a1e91b49470.png)

The code I'm using is this:
```js
() => navigator.resetTo({
          screen: SCREEN_VOUCHERS,
          animated: true,
          title: 'Vouchers',
        })
```

Where navigator came from props

If I do :
```js
() => navigator.push({
          screen: SCREEN_VOUCHERS,
          animated: true,
          title: 'Vouchers',
        })
```

Then it works just fine. So the problem is with resetTo

---
### Environment
* React Native Navigation version: next
* React Native version: 0.35
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Genymotion / Android 21 / Debug

**Comment by guyca** [comment]
@rafaelcorreiapoli Is this bug reproducible  in the example project?

**Comment by vyky** [comment]
I'm having the same problem tested on iOS with RNN 2.0.0-experimental.162

Say current screen is screen A. I resetTo to screen B. In screen B, RNN running screen A code which already unmounted causing error 'setState on unmounted component' (in my case)

**Comment by vyky** [comment]
Oh no. Actually my mistake. I was doing asynchronous call with setState as callback. Before the call is finished, I was resetTo to screen B which cause screen A is unmounted. When the call is finished, it was doing setState in an unmounted component.
