### ISSUE TITLE
[V2] Back icon and topBar button icon weird jumping

### ISSUE THREAD

**Issue by davidbilik** [wix/react-native-navigation#4870]
### Issue Description
I've migrated to v2 version of the lib and the topBar icons behave weird on Android. Up/back icon appears later than title of the screen which makes title jump to the right. TopBar buttons are animating from the top which is not a nice animation and also on less performant device this animation is laggy which make it really unpleasant. I've tried to disable all animations that I thought can affect this but nothing helped.

I dont think that I can release it this way to my users :( but I dont want to ditch X hours of work that I've put into migrating. Any idea whats going on and how to fix? Thanks!
 
### Steps to Reproduce / Code Snippets / Screenshots
I have app with bottomTabs and some simple styling applied which I don't think matters. On the attached [video](https://drive.google.com/file/d/1ZRPfLHrmd8nndr3wO4Q4OPgWxbbBhIBh/view?usp=sharing) is what i am talking about. I am clicking on the right top button and then clicking on back button from the next screen. When top button is clicked, it performs Navigation.pop() to the second screen. Back icon has default behavior. 

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.59.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Any device, any Android version

**Comment by harveyconnor** [comment]
#4875 Similar issue

**Comment by davidbilik** [comment]
Maybe but I dont use custom components

**Comment by pribeh** [comment]
Experiencing the same on 0.59 and 2.16.0

**Comment by sorin-f-wiredelta** [comment]
### Environment
* React Native Navigation version: 2.16.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): PIXEL 2 Emulator , Android 8 SDK

Can confirm, experiencing the same problems with topBar icons and not with custom components. Here is a [GIF](https://giphy.com/gifs/rnnv2-g4G2uPvDeIFlP3nGWe) I made to highlight the problem. 

I noticed the problem after I made the upgrade from RNN 2.12.0 to 2.16.0.

**Comment by pribeh** [comment]
It almost looks like it was an added animation that doesn't really render properly and is too short to work effectively in that space. That's just a guess. I can't figure out what the cause of it is.

**Comment by aminosman** [comment]
Still seeing this in v `2.18.3`, any update?

**Comment by davidbilik** [comment]
I've discovered whats causing buttons to jump weirdly, its this commit https://github.com/wix/react-native-navigation/commit/54ff1cd049b7a418f7fd2658f569d06853bcea6c Probably ActionMenuView has two phase positioning of its items and this "overflow" or clipChildren = false will display it's flaw. I will probably make my own fork of this lib and remove this line because I don't need badges or other views in my top bar buttons, but its not universal solution. It would be great to have some official support from the guy that made that commit @guyca to discuss it.

**Comment by kyryloz** [comment]
> I've discovered whats causing buttons to jump weirdly, its this commit [54ff1cd](https://github.com/wix/react-native-navigation/commit/54ff1cd049b7a418f7fd2658f569d06853bcea6c) Probably ActionMenuView has two phase positioning of its items and this "overflow" or clipChildren = false will display it's flaw. I will probably make my own fork of this lib and remove this line because I don't need badges or other views in my top bar buttons, but its not universal solution. It would be great to have some official support from the guy that made that commit @guyca to discuss it. Unfortunately, Back/Up icon still makes title to jump, dont know whats causing that yet

After removing `enableOverflowForReactButtonViews(child);` it definitely fixes the weird jumping. For future readers, instead of making your own fork to fix minor issues consider using `patch-package` package. It may be the quickest way to make a change to a third-party library.
