### ISSUE TITLE
cannot read property setRoot of undefined

### ISSUE THREAD

**Issue by sunny-mittal** [wix/react-native-navigation#4871]
### Issue Description

I'm getting an error that setRoot cannot be read on undefined, however, when I console.log just `Navigation.setRoot`, I see that it _is_ a defined function (see below)

### Steps to Reproduce / Code Snippets / Screenshots

I don't have any "repro" steps, as I've used react-native-navigation before with no issues, but I'm thoroughly confused as to what's going on. Here's the relevant code from my `navigation.ts` file:
```
import 'react-native'
import { Navigation } from 'react-native-navigation'

import { registerScreens } from './screens'

registerScreens()

Navigation.setRoot({...})
```
which throws the error: "Cannot read property 'setRoot' of undefined."

But then if I comment out the `setRoot` call and add `console.log(Navigation.setRoot)`, I get this:

```
ƒ setRoot(layout) {
        return this.commands.setRoot(layout);
      }
```
Clearly setRoot exists but when I attempt to call it, something goes awry. I've added a breakpoint before the call to setRoot and in the debugger, I _don't_ see setRoot on the Navigation object...so I'm very confused. Any help would be greatly appreciated.

### Environment
* React Native Navigation version: ^2.13.1
* React Native version: 0.59.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iOS 12.1, iPhone X

**Comment by sunny-mittal** [comment]
Here's an additional oddity:
![image](https://user-images.githubusercontent.com/8553227/54481985-d9ef0c00-4801-11e9-852e-e7a85b4791e4.png)

I can mouse over the setRoot method and see it's defined, but if I unpause the debugger, it again throws the error that setRoot cannot be read on undefined. I've been going mad all day.

**Comment by jinshin1013** [comment]
You need to wrap your initial setRoot in `Navigation.events().registerAppLaunchedListener`.

**Comment by sunny-mittal** [comment]
@jinshin1013, I tried that as well but the method doesn't fire...I don't know if it's a timing thing, but I put the event registration in index.js and my breakpoint never hits. Here's my index.js code:
```
/**
 * @format
 */

import { AppRegistry } from 'react-native'
import App from './src/components/App'
import { name as appName } from './app.json'
import { Navigation } from 'react-native-navigation'

import { registerScreens } from './src/screens'
registerScreens()

Navigation.events().registerAppLaunchedListener(() => {
  debugger // never hits
  Navigation.setRoot({
    root: {
      component: {
        name: 'nav.Home'
      }
    }
  })
})

AppRegistry.registerComponent(appName, () => App)
```
I bet there's something very obvious I'm missing regarding timing but I've tried moving the listener and it never fires.

**Comment by jinshin1013** [comment]
Remove AppRegistry.registerComponent function. Have you been referring to the doc?

**Comment by sunny-mittal** [comment]
@jinshin1013 I have...and I've been confused by the demos I've seen because all end up throwing an error about the app not being registered. Creating a new RN app with the CLI tool creates an index file with the registerComponent code but, without it, the app won't run. Do you have a very simple demo app I can clone and build to use as reference?

**Comment by jinshin1013** [comment]
I made a boilerplate while back which can be found [here](https://github.com/jinshin1013/rnn-boilerplate). It's little different, but you should be able to pick up where you've possibly done wrong. Also make sure you have followed the all steps in the documentation to "link" react-native-navigation.

**Comment by sunny-mittal** [comment]
Trying now...thank you so much for your quick responses!

**Comment by sunny-mittal** [comment]
This works swimmingly...I shall study it. Thank you! I'll close this as a non-issue unless something crops up. Thanks again.

**Comment by subinkrishna** [comment]
I still face the same issue. Even though the boilerplate works, I am struggling to run the sample code from the docs. This is all the code I have:

```
import { Navigation } from 'react-native-navigation';
import App from './src/component/App';

Navigation.registerComponent('navigation.playground.WelcomeScreen', () => App);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      component: {
        name: 'navigation.playground.WelcomeScreen'
      }
    }
  });
});
```

Dependencies:
```
"dependencies": {
  "react": "16.8.6",
  "react-native": "0.59.8",
  "react-native-navigation": "2.18.5"
}
```

Any suggestions?
