### ISSUE TITLE
Error when doing npm run android in React Native v0.59

### ISSUE THREAD

**Issue by vivevio** [wix/react-native-navigation#4874]
### Issue Description

I already followed the installation instructions. But when I do command line `npm run android` or `react-native run-android` I got errors like this

`Task :react-native-navigation:compileReactNative57_5DebugJavaWithJavac /Users/vive/Documents/Projects/RNPlayground/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/ views/element/Element.java:17: error: ReactViewBackgroundDrawable is not public in com.facebook.react.views.view; cannot be accessed from out side package import com.facebook.react.views.view.ReactViewBackgroundDrawable;`

Already searching on Issues tab whether on an open or closed tag, and on StackOverflow as well, but not found the solution yet. 

---
### Environment
* React Native Navigation version: ^2.13.1
* React Native version: 0.59.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Version 9.0(Android Pie),  Debug

**Comment by harveyconnor** [comment]
`rm -rf node_modules && npm install` then re-run

**Comment by vivevio** [comment]
I just tried but the error still persists tho. I use **Nativebase.io** library, is there any possibility caused by that library?
