### ISSUE TITLE
[v2] [Android] Adding marginLeft or marginRight to rightButtons causes title to collapse

### ISSUE THREAD

**Issue by harveyconnor** [wix/react-native-navigation#4875]
### Issue Description

When adding custom components as buttons on topBar->rightButtons, it causes the topBar to glitch and collapse the title.

### Steps to Reproduce / Code Snippets / Screenshots

Both topBar and rightButtons were custom components. It did not appear to collapse when using a standard text component as the title.

topBar-->rightButtons (components)
topBar-->title (component)

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.59.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Poco F1 - LineageOS 16 (Debug)

**Comment by harveyconnor** [comment]
@retyui 
Nah that's not it.

Here's what you should try, attempt to create a custom component for your right button, and a custom component for your title.

```js
options: {
  topBar: {
      title: { 
        component: {} // Insert a custom title component here, obviously register it first and use the appropriate component name e.g. <View><Text>Title</Text></View>
      },
      rightButtons: [
        {
           id: '1',
           component: {} // Apply a marginRight to the component's root <View>
        },
      ],
   }
}
```

**Comment by retyui** [comment]
I update the example https://gist.github.com/retyui/16a275c8cb3c322dab4dd858515d457f
And here is the result:
<a href="https://giphy.com/gifs/1VVL1aiVzwzjx98C00/html5">
![](https://media.giphy.com/media/1VVL1aiVzwzjx98C00/giphy.gif)
</a>

**Comment by juddey** [comment]
I get the same behavior. RNN `2.8.0`, RN 57.4.

**Comment by harveyconnor** [comment]
@retyui yep, that's exactly what happens. iOS is completely fine. My solution was just to add
```js
paddingRight: 10
```
instead of marginRight

**Comment by juddey** [comment]
@harveyconnor Did paddingRight exhibit strange behaviour for you? 
I distinctly remember adding this attribute and what happened was that the element I had slid left and bumped up against the title...
kind of like a skater going across the ice, a nice effect but not what I was _really_ after. :wink:

**Comment by harveyconnor** [comment]
@juddey This is what I have:
```js
container: {
    ...Platform.select({
      android: {
        paddingRight: 16,
        marginLeft  : 8,
      },
    }),
  },
```
On iOS the marginRight is in there natively

**Comment by juddey** [comment]
Hmmm.
Variation on your problem then: 

![ezgif-4-8c4d30088394](https://user-images.githubusercontent.com/7445602/54729995-3e87dd80-4beb-11e9-9653-3cc9da9ad720.gif)

**Comment by harveyconnor** [comment]
yeah that was the original issue I had

**Comment by juddey** [comment]
This is still an issue (2.17)

**Comment by juddey** [comment]
No no no no no stalebot, this is still a problem. :robot:

**Comment by xxRockOnxx** [comment]
Still existing on `3.0.0`
