### ISSUE TITLE
How to use .svg files like icons on topBar or bottomTab

### ISSUE THREAD

**Issue by manelsanz** [wix/react-native-navigation#4879]
Hi, I have some .svg files that are icons from a client and I need to use inside navigation. I researched some options but I don't want to create a custom font type, just want to use it as Image or Icons on the Navigation options like topBar Buttons or botomTab options.

Thank you.

**Comment by sja1n** [comment]
you can try to convert them to .png or .jpg files and then use it

**Comment by manelsanz** [comment]
@sja1n I'm gonna do that way, converting to .png. 
After losing all day trying to get working SVG on React Native, I only achieved to work with this way; 
- Pasting svg file here https://www.smooth-code.com/open-source/svgr/playground/ 
- with React Native and SVGO checked with options
```
{ "plugins": [{ "removeTitle": false },
{ "inlineStyles": { "onlyMatchedOnce": false } }] }
```

But this way I can not use them with react-native-navigation, because I cannot paste a Component on topBar or bottomTab config. Or if I can, it's not much practical for me.

Thank you.
