### ISSUE TITLE
Example App:

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#488]
### Issue Description
My default Example is not the same as the one shown in your ReadMe

---
### Environment
* React Native Navigation version: next
* React Native version: .37
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
That gif is of the Wix app.
@JuneDomingo posted a nice open [source app](https://www.facebook.com/photo.php?fbid=803821889758089) which uses RNN
