### ISSUE TITLE
Display overlay on top of default modal from react-native

### ISSUE THREAD

**Issue by sja1n** [wix/react-native-navigation#4881]
### Issue Description

I am using default react native Modal to show a screen and depending from some user interaction i am trying to show overlay, but its getting displayed under the modal, which i verified by dismissing the modal immediately and overlay was visible.

Is it even possible to show overlay on top of Modal ?

### Steps to Reproduce / Code Snippets / Screenshots

`import React, { Component } from 'react'
import {
  View,
  Text,
  Modal,
} from 'react-native'
import { Navigation } from 'react-native-navigation'

class App extends Component {
  constructor(props) {
    super(props)
  }

  showSnackbar = (msg, type = 'info') => {
    Navigation.showOverlay({
      component: {
        name: 'streak.toast',
        passProps: {
          msg, type,
        },
        options: {
          overlay: {
            interceptTouchOutside: false,
          },
        },
      },
    })
  }

  render() {
    const { isVisible } = this.state
    return (
      <View style={styles.container}>
        <Modal
          animationType="slide"
          transparent={false}
          visible={isVisible}
          onRequestClose={() => this.togglePopup('isVisible')}
        >
          <Add
            showSnackbar={(msg, type) => this.showSnackbar(msg, type)}
          />
        </Modal>
      </View>
    )
  }
}

class Add extends Component {
  componentDidMount = () => {
    this.props.showSnackbar('Hello from snackbar', 'success')
    this.showSnackbar('Hello from snackbar', 'success')
  }

  showSnackbar = (msg, type = 'info') => {
    Navigation.showOverlay({
      component: {
        name: 'streak.toast',
        passProps: {
          msg, type,
        },
        options: {
          overlay: {
            interceptTouchOutside: false,
          },
        },
      },
    })
  }

  render() {
    return (
      <View><Text>Hello</Text></View>
    )
  }
}`

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.59.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Device, both

**Comment by tarunraj95** [comment]
I am facing this similar issue!
@sja1n did you find any solution for this ? :|

**Comment by rf1804** [comment]
Same Issue @guyca
