### ISSUE TITLE
componentDidAppear doesn't fire again after dismissing modal

### ISSUE THREAD

**Issue by EliSadaka** [wix/react-native-navigation#4882]
### Issue Description

When showing a modal on a screen that has a `componentDidAppear()` function, once the modal is dismissed `componentDidAppear()` is not fired on the original screen again.

### Steps to Reproduce / Code Snippets / Screenshots

In the screen:
```
componentDidAppear() {
   console.log('screen appeared')
}

...

Navigation.showModal({
   stack: {
	children: [{
	   component: {
		name: "TestModal",
	   }
	}]
   }
});
```
Then at some point in the modal:
`Navigation.dismissModal(this.props.componentId);`

When the screen first appears `screen appeared` is printed to the console, and even when pushing and popping other screens it works as it should, but when showing and dismissing a modal it fails to fire. Using `dismissAllModals()` instead does not change this behaviour.

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel 2, iPhone SE

**Comment by idanlo** [comment]
Can you reopen please? I am also experiencing this. We have tried to use multiple events instead of `componentDidAppear`, such as `setRoot` or `push` but none of them are as consistent as `componentDidAppear` was.
