### ISSUE TITLE
Scrolling on bottomTab index change prevents tap

### ISSUE THREAD

**Issue by markhomoki** [wix/react-native-navigation#4884]
### Issue Description
On changing bottomTab while scrolling inside the tab content then going back to the previous tab index, the tap is prevented. To enable tap again, need to scroll the content again. This issue exists in the WiX mobile app as well. This issue only exists in v2.

### Steps to Reproduce / Code Snippets / Screenshots
1. Select Tab Index 1
2. Scroll down and while it's scrolling switch to Tab Index 2
3. Switch back to Tab Index 1 and try to press any action button (it will be prevented)
4. Scroll the content on Tab Index 1 then try to press the same action button (it will work)

---
### Environment
* React Native Navigation version: v2.13.2
* React Native version: v0.59.1
* Platform(s) (iOS, Android, or both?): iOS (not tested on Android)
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 8 iOS 12.1.4 Release

**Comment by manuhook** [comment]
I can repro the same problem on my app.
It's only affecting iOS, on Android when you switch back to Tab index 1, the scroll is still in movement.

**Comment by flikQ** [comment]
I am also experiencing this.

**Comment by wellcode** [comment]
Have the same problem, is there a plan to fix it?

**Comment by markhomoki** [comment]
Unfortunately, this has not been fixed and this error still happens in the latest version of the WiX iOS app.
