### ISSUE TITLE
ios showModal with custom animation not work

### ISSUE THREAD

**Issue by yanjie311** [wix/react-native-navigation#4886]
Navigation.showModal({
          stack: {
            children: [{
              component: {
                id: componentId ,
                name: componentName,
                options: {
                  topBar: {
                    noBorder: true,
                    visible: false,
                    drawBehind: true,
                    animated: false
                  },
                  bottomTabs: {
                    visible: true,
                    drawBehind: false,
                    animated: false
                  },
                  animations: {
                    enable: true,
                    waitForRender: true,
                    showModal: {
                      alpha: {
                        from: 0,
                        to: 1,
                        duration: 200,
                        interpolation: 'accelerate'
                      }
                    },
                    dismissModal: {
                      alpha: {
                        from: 1,
                        to: 0,
                        duration: 200,
                        interpolation: 'accelerate'
                      }
                    }
                  }
                }
              }
            }]
          }
        });

**Comment by pribeh** [comment]
Do overlays not support custom animations? I'm trying myself but without luck.

**Comment by fliPmitKlammern** [comment]
Same problem for me: I defined animations for showModal and they are working just fine on Android - however on iOS the default animation is shown.
This is how I nested the animations:
```javascript
Navigation.showModal({ stack: { children: [{ component: {
  name: screen,
  options: {
    animations: {
      showModal: { alpha: { from: 0, to: 1, duration: 400, startDelay: 0, interpolation: 'accelerate' }},
      dismissModal: { alpha: { from: 1, to: 0, duration: 400, startDelay: 0, interpolation: 'accelerate' }}
    }
  }
}}]}});```

**Comment by pedrobertao** [comment]
I'm having the same problem with iOS. Android works fine. iOS doesn't.

**Comment by jinshin1013** [comment]
Same problem here as well.

**Comment by igortupini** [comment]
Same problem. Android works smoothly and iOS default slide up animation is showing.
Very frustrating.

**Comment by jinshin1013** [comment]
@igortupini have a look at #5078, there is an inconsistency between iOS and Android.

**Comment by igortupini** [comment]
> @igortupini have a look at #5078, there is an inconsistency between iOS and Android.

I tried your code and worked. Alpha animation is working on showModal, but not on dismissModal.
The transition starts but when is about to finish, the screen turns white and get stuck there.

My presentation style is 'overFullScreen', when I switch to any other presentation style your method works. But only in 'overFullScreen' I cant get a transparent background.

**Comment by smooJitter** [comment]
@igortupini  what was your “overCurrentContext” work around?  I’m getting the same error.

**Comment by igortupini** [comment]
@smooJitter This error is a problem with React Native itself. RN is missing 'overCurrentContext' for iOS. I fixed it adding manually to RN. Although this made 'overCurrentContext' work, didn't solve my modal problem.

I suggest you to user 'overFullScreen' with `layout: { backgroundColor: 'transparent' }`
This method requires no changes in RN and should work the same as overCurrentContext

**Comment by smooJitter** [comment]
@igortupini thanks...  I still don’t quit understand how it happened all of a sudden.

**Comment by badaz** [comment]
I found out that dismissAllModals triggers the default animation on IOS, not the one passed in the showModal options. However, if you call dissmissModal with the correct componentId, the animation passed in the animations.dissmissModal option of the modal component will work (I'm on RNN 6, RN 0.63.2). I also found out that it works best if you pass a stack instead of just the component option.
