### ISSUE TITLE
Draw the side menu over the center.

### ISSUE THREAD

**Issue by acollazomayer** [wix/react-native-navigation#4890]
How do I make the side menu on top of the center. Not display the center sideways.

Thanks

**Comment by zabojad** [comment]
You have a `width` parameter that works for iOS only (although the doc doesn't mention it, I haven't been able to use this param on Android). If you give it the same value as your screen width, it should do what you want...

**Comment by acollazomayer** [comment]
@zabojad thanks but is not what I meant. I want the sidebar to draw over the center not to have the width of the center

**Comment by ItsNoHax** [comment]
@acollazomayer That sort of sidemenu drawer is not supported at the current moment in RNN. As far as I know, Wix apps don't use that sort of sidemenu themselves thus the devs have been prioritizing other issues. But this is a open source and they are very willing to accept a community contributed PR for it.
