### ISSUE TITLE
custom top bar button shows react native warning

### ISSUE THREAD

**Issue by acollazomayer** [wix/react-native-navigation#4891]
Custom button shows react native warning.

<img width="358" alt="Screen Shot 2019-03-20 at 2 59 28 PM" src="https://user-images.githubusercontent.com/9849229/54707930-fef4bf00-4b20-11e9-9f90-70c4a3b6fa6d.png">

---
### Environment
* React Native Navigation version: 2.13.2
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by jinshin1013** [comment]
I mean this is kinda expected but could be tedious.

**Comment by acollazomayer** [comment]
@jinshin1013 Give me a little bit of explanation here. How adding a custom header component should show the react native warning. Or at least add this to the documentation. "While adding a custom title component or background to the header you will see the warnings beacuse of ...."

**Comment by jinshin1013** [comment]
Warnings are shown not by RNN but RN. They show the warning on the natively registered RNView. Since RNN registers every screen, RN goes oh there are two registered screen, show the warning on both.

**Comment by acollazomayer** [comment]
@jinshin1013 Thanks. Its really annoying.
