### ISSUE TITLE
 Navigation.registerComponent does not register component with a componentId

### ISSUE THREAD

**Issue by curtismenmuir** [wix/react-native-navigation#4894]
### Issue Description

Navigation.registerComponent() does not register the JS component with a componentId. Issue found when attempting to displaying a react-native view inside of a native Android module (using ReactRootView). 

### Steps to Reproduce / Code Snippets / Screenshots

Issue found with component registration:
```js                                                        
Navigation.registerComponent(
    "OtherView",
    () => require("./OtherView").default
  );

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      component: {
        name: "init"
      }
    }
  });
});

```                 
Then call in Android (java) to display component using ReactRootView: 
```js
mReactRootView.startReactApplication(mReactInstanceManager, "OtherView", getLaunchOptions());
```

Screenshot:

![Screenshot_20190321-165353](https://user-images.githubusercontent.com/9335768/54771040-616ebd80-4bfc-11e9-83f9-03adbddc1649.jpg)

The issue is resolved by registering component with AppRegistry (before calling setRoot):
```js                                                        
Navigation.registerComponent(
    "OtherView",
    () => require("./OtherView").default
  );

AppRegistry.registerComponent("OtherView", () => OtherView);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      component: {
        name: "init"
      }
    }
  });
});

```                                                          
---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Seen on both simulator and actual device. Issue seen with various Android versions. Issue was seen in debug buils.

**Comment by Angry-Potato** [comment]
seeing the same issue here
