### ISSUE TITLE
Huge performance decrease

### ISSUE THREAD

**Issue by geroale** [wix/react-native-navigation#4903]
I moved from react-navigation to this react-native-navigation, keeping the same navigation structure. The problem I am having is that before the app used about 140mb of memory and now it's using min 200mb. It is weird, I guess, considering also that this package is fully native.
To make sure I don't have any memory leaks in my screens, I am using, for all of them, a simple component that only returns one text.

This is my navigation structure

First root: 1 component
Second root: 1 component
Third root: bottomTabs with 4 stacks with each 12 screens

Am I doing anything wrong? There may be a specific reason, considering that this navigation still seems more fluid than the previous one?

* React Native Navigation version: 2.0.0
* React Native version: 0.58.6
* Platform(s): iOS
* Device info: iPhone 8 Simulator, iOS 12.1

**Comment by flikQ** [comment]
I am having a similar issue, I was however on RNN V1 and at boot was about 140mb usage too. After migrating to V2 I am booting at 550mb. It's pretty insane the differences, makes me think there is an issue how we've configured the app during the boot process.
