### ISSUE TITLE
sideMenu bugs?

### ISSUE THREAD

**Issue by DeevD** [wix/react-native-navigation#4904]
sideMenu is not close in andriod when setStackRoot center of sideMenu like below code.  
`Navigation.setStackRoot("Tabs", {
          component: {
            name: "Categories",
            options: {
              topBar: {
                visible : false,
                drawBehind : true,
              },
            }
          }
        })`

not working code 
`sideMenu:{
    left : {
  visible : false
}
}`

**Comment by RekarBotany** [comment]
I have the same issue doing this:
`  closeSideMenu() {
    Navigation.mergeOptions("mainSideMenu", {
      sideMenu: {
        left: {
          visible: false,
          enabled: false,
        },
      },
    });
  }

  gotToScreen(screen) {
    this.closeSideMenu();
    Navigation.push("mainStack", {
      component: {
        name: screen,
        passProps: {},

        options: {
          topBar: {
            visible: false
          }
        }
      }
    });
  }`

**Comment by ItsNoHax** [comment]
Closing as it's a duplicate issue of: #4696

There is a PR open that fixes this, just need @guyca 's help with fixing the android tests. #4937
