### ISSUE TITLE
Remote JS debugging breaks app - White screen

### ISSUE THREAD

**Issue by gotters** [wix/react-native-navigation#491]
As per an earlier post....my app becomes completely unusable once I switch to Remote debugging.

I did the following:
- I took the example project
- added a few screens of my own
- app was working fine
- added some console logs
- switched to Remote debugging
- now app loads up with a white screen and nothing is happening
- I cant even switch out of Remote JS debugging mode (the app doesnt respond once it loads - any other way to do it)

Please let me know how I can better investigate this!

**Comment by guyca** [comment]
Hey @gotters 
If you upload your project to github I can take a look. We didn't encounter any issues debugging in RN 0.37.

**Comment by gotters** [comment]
It may have to do with an out of date Android SDK...testing and will get back to you.
Thanks

**Comment by gotters** [comment]
Confirmed. Upgraded SDK and its working as expected.
Not sure why this was only affected my app that was using react-native-navigation though.
Thanks

**Comment by lglomer** [comment]
This happens to me. I upgraded to the latest SDK as suggested (7.1.1 API 25). Any advice?

**Comment by gotters** [comment]
Can you run the example project?
Also I know I was also getting message to upgrade gradle...which i did through Android studio separate to SDK upgrade

**Comment by lglomer** [comment]
@gotters I ran the example project. It required my to install Android SDK Build-tools (Rev. 25.0.1) so I did. I tried running the app and it worked but remote debugging still crashed my app. Now I get a white screen, exactly the symptoms you described.

**Comment by gotters** [comment]
yes i was having the same frustration. Happy to see you are able to find some kind of workaround...something flaky under the hood is causing this inconsistent behaviour. For now its behaving for me. 
Did you try restart Android Studio...i think that worked for me at one point also.

If I have any more ideas will let you know.

**Comment by lglomer** [comment]
@gotters I don't have Android Studio. I downloaded the SDK and AVD managers separately from the Android website. Perhaps that's the issue?
Thanks.

**Comment by florianbepunkt** [comment]
@gotters @lglomer I experience the same issue… white screen. app was working fine. now I can't open the debug menu with cmd + m. I just get a white screen on android. did you find a way to get this back to normal or do I have to setup my app from scratch.

**Comment by guyca** [comment]
@florianbepunkt I know this sounds weird, did you try uninstalling the app from emulator?

**Comment by florianbepunkt** [comment]
@guyca Yes, I did… also setup a fresh AVD, but to no avail.

**Comment by guyca** [comment]
@florianbepunkt Can you ping me on our [Discord](https://discord.gg/DhkZjq2) channel?

**Comment by lglomer** [comment]
@florianbepunkt Pressing "Start" in AVD Manager will open up a new window. Have "Wipe user data" checked.

**Comment by arapocket** [comment]
I'm having this same issue on iOS.
