### ISSUE TITLE
Completely disable bottom tabs

### ISSUE THREAD

**Issue by vahidd** [wix/react-native-navigation#4911]
### Issue Description

Since I want to implement custom tabs and be able to customize it I disabled native bottom tabs and rendered a custom bottom tab component with react native components. I use "setDefaultOptions" as first thing on "registerAppLaunchedListener" event, something like this:
```javascript
Navigation.events().registerAppLaunchedListener(() => {
            Navigation.setDefaultOptions({
                bottomTabs: {
                    visible: false,
                    height: 0,
                }
            });
            Navigation.setRoot({
                root: {
                    component: {
                        name: LANDING,
                    },
                },
            });
}
```
The problem is on app startup native bottom tabs view will be displayed and immediately hides.
How can I completly disable native bottom tabs view?

###  Screenshots

![Alt Text](https://media.giphy.com/media/lwqwRoHs4Ux78kcVlb/giphy.gif)

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.59.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by EliSadaka** [comment]
Try adding `animate: false` to your bottomTabs options:
```
Navigation.setDefaultOptions({
   bottomTabs: {
      animate: false,
      visible: false,
      height: 0,
   }
});
```
