### ISSUE TITLE
Android push animation skips animating for heavy pages

### ISSUE THREAD

**Issue by smarki** [wix/react-native-navigation#4914]
### Issue Description

Push animation on android skips animating for heavy pages. While on iOS it works fine. 
Looking at the android implementation for animations I see that wait for render for the child view is only true if explicitly set so.

I would assume for parity that the flag would default to true or explicitly check for negation. 
While it probably would make pushing times inconsistent; it at least would behave consistently on both platforms. 

### Steps to Reproduce / Code Snippets / Screenshots
For internal testing we use pages that are showcasing various animating or heavy components. Such as a page with progress bars, animating via js. While switching to those pages the push animation usually skips.

To fix it explicitly setting `waitForRender` works:

            animations: {
                push: {
                    waitForRender: true
                }
            }
---
### Environment
* React Native Navigation version: 2.15.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): x86 emulator API 28

**Comment by ItsNoHax** [comment]
I think we should leave waitForRender opt in as in most cases you want the push animation to feel instant, component heavy screens are less common in most apps.
