### ISSUE TITLE
Attempted to invoke `3` (method ID) on `UIManager` (NativeModule name) with an invalid bridge

### ISSUE THREAD

**Issue by nihp** [wix/react-native-navigation#4915]
**🐛 Bug Report**

I am facing lot of warnings which not allowing me to make any event in the app.
Attempted to invoke 3 (method ID) on UIManager (NativeModule name) with an invalid bridge. Refer the attached image

**To Reproduce**

I am facing this issue in latest version of "react-navigation": "^3.2.3" (v3)

**Expected Behavior**

Need to remove all the warnings (Attempted to invoke 3 (method ID) on UIManager (NativeModule name) with an invalid bridge.)

**Environment**

**npmPackages:**
react: 16.8.1 => 16.8.1
react-native: ^0.58.4 => 0.58.6
**npmGlobalPackages:**
react-native-cli: 2.0.1

![Screenshot 2019-03-26 at 2 23 42 PM](https://user-images.githubusercontent.com/36992338/54984952-efb8ba00-4fd5-11e9-955c-e7c86a24e010.png)

**Comment by retyui** [comment]
Are you use `react-navigation` and `react-native-navigation` simultaneously?

**Comment by nihp** [comment]
I am using react-navigation.

**Comment by retyui** [comment]
@nihp maybe you want to create an issue here: https://github.com/react-navigation/react-navigation?
