### ISSUE TITLE
[V2] Show modal with modalPresentationStyle='overCurrentContext' not change rotation

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#4916]
I used Modal as LightBox on iOS. I call show modal with modalPresentationStyle='overCurrentContext'
The background is transparent OK. But when I rotate my device, the screen didn't rotate (my device is in auto rotate mode). But if I didn't use modalPresentationStyle='overCurrentContext', the background was solid and the screen auto rotate as device rotate
### Environment
* React Native Navigation version: 2.16.0
* React Native version: 0.59.2
* Platform(s) (iOS, Android, or both?): iOS

**Comment by phuongwd** [comment]
its not stale

this issue is still happing on version `3.2.0`
