### ISSUE TITLE
(iOS) hideOnScroll=true, hidden topBar not showing

### ISSUE THREAD

**Issue by WeiLiangTan** [wix/react-native-navigation#4917]
### Issue Description

On iOS iphone XS Simulator, after hiding topBar with hideOnScroll: true, scroll down won't get the topBar to show again.

my screen is wrapped in SafeAreaView from react native.

It seems 
`import { SafeAreaView } from "react-native"`,
after hidden, then cannot show the topbar again.

if 
`import SafeAreaView from "react-native-safe-area-view"`, 
it works correctly, however the scrolling content will block the status bar.

### Steps to Reproduce / Code Snippets / Screenshots

```
topBar: {
  visible: true,
  drawBehind: false
  animate: true,
  hideOnScroll: true,
  title: {
    component: {
      name: 'MyCustomTopBar'
    }
  }
}
```

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.58.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone XS Simulator (iOS 12.1)

**Comment by mtzfactory** [comment]
I do have the same problem... once is scrolled, the topBar never shows again...

**Comment by WeiLiangTan** [comment]
To be fair, I don't think there is anything the team can do.
This behaviour lies on Apple's api.

navigationController. hidesBarsOnSwipe only do the hiding.

Since hideOnScroll only works for scrollable content,

adding onScroll in the Scrollview, FlatList or SectionList, etc should help to solve the issue, although it is not perfect.

```
onScroll={({
  nativeEvent: {
    contentOffset: { x, y }
  }
}) => {
  if (this.y > y && y <= 44) {
    Navigation.mergeOptions(this.props.componentId, {
      topBar: {
        visible: true,
      }
    });
  }
  this.y = y;
}}
```
