### ISSUE TITLE
screen static options lost on pop ?

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#4919]
### Issue Description

I have a screen component which exposes as a static var some navigation options:
```
	static options = {
		topBar: {
			title: {
				component: {
					passProps: { hideBackButton: true }
				}
			}
		}
	}
```

When it shows up the first time, those passProps options are passed correctly to the topbar title component. If I push a screen on the same stack and then pop it, the topbar title component does not receive those passProps.

---
### Environment
* React Native Navigation version: 2.16.0
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device iPhone SE iOS 12.0.1

**Comment by zabojad** [comment]
@yogevbd @guyca this seems to be a rather basic issue, do you think we could find a fix for one of the next releases?

**Comment by jinshin1013** [comment]
That's because `static options` only get processed on component mount so it makes sense that the props are not received because it doesn't get called.

**Comment by zabojad** [comment]
I see. Maybe I'm biased but to me, it would make more sense that `static options` get processed on component appearing rather than mounting...
