### ISSUE TITLE
KeyboardAvoidingView interferes with this navigation on Android, bug or feature?

### ISSUE THREAD

**Issue by arthurvi** [wix/react-native-navigation#492]
### Issue Description
We used a JS navigation component before and implemented the [KeyboardAvoidingView](https://facebook.github.io/react-native/docs/keyboardavoidingview.html) with behaviour `padding` for screens that contained forms.
> KeyboardAvoidingView: It is a component to solve the common problem of views that need to move out of the way of the virtual keyboard

After switching on iOS everything still works as expected. However, on Android, the view is "pushed up" two times. When removing the `KeyboardAvoidingView` on Android, everything works fine. 

I believe the default setting of React Native for Android is `<activity android:windowSoftInputMode="stateUnspecified|adjustPan" . . . >` See [here](https://developer.android.com/guide/topics/manifest/activity-element.html#wsoft) for more the Android docs about this. Our app is using this setting.
>"adjustPan"	The activity's main window is not resized to make room for the soft keyboard. Rather, the contents of the window are automatically panned so that the current focus is never obscured by the keyboard and users can always see what they are typing. This is generally less desirable than resizing, because the user may need to close the soft keyboard to get at and interact with obscured parts of the window.

But somehow it looks like the mode is changed to `adjustResize` without changing/specifying this in our Android code.
> "adjustResize"	The activity's main window is always resized to make room for the soft keyboard on screen.

Is this a bug or a feature of this library?

---
### Environment
* React Native Navigation version: 2.0.0-experimental.142
* React Native version: 0.37.0, 0.38.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator&Device, most OS, Debug&Release

---
### Initial Screen
<img width="479" alt="screen shot 2016-11-24 at 13 54 47" src="https://cloud.githubusercontent.com/assets/3864426/20599338/e0ef955c-b24d-11e6-833b-eda79e3d72ab.png">

### Correct behaviour without KeyboardAvoidingView
<img width="479" alt="screen shot 2016-11-24 at 13 55 31" src="https://cloud.githubusercontent.com/assets/3864426/20599344/e4b61706-b24d-11e6-8ae3-b263843dc2b5.png">

### Wrong behaviour with KeyboardAvoidingView
<img width="482" alt="screen shot 2016-11-24 at 13 54 39" src="https://cloud.githubusercontent.com/assets/3864426/20599341/e29eb734-b24d-11e6-960a-ae265e93b277.png">

**Comment by guyca** [comment]
Hey @arthurvi 
We don't use `KeyboardAvoidingView` in our apps and I have no idea what it does on Android. Truthfully, I'm not entirely sure why it's needed on Android. 

In our app, we set SOFT_INPUT_ADJUST_RESIZE flag on our activities and use `ScrollView` as the root view in screens with input fields.

```java
public class MainApplication extends NavigationApplication {
    ...
    @Override
    public void onCreate() {
        super.onCreate();
        registerActivityLifecycleCallbacks(new LifecycleCallbacks() {
            @Override
            public void onActivityCreated(Activity activity, Bundle savedInstanceState) {
                activity.getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);
            }
        });
    }
    ...
}
```

**Comment by arthurvi** [comment]
Thanks @guyca!
Then it is not necessary on Android anymore! 

How do you guys handle the iOS keyboard? So now on Android the screen is pushed up. On iOS however, the keyboard is placed on top of the view. The official docs suggest that you set a listener for when the keyboard is shown and use scrollTo to scroll down, like shown here:

![keyboard_adjust_2x](https://cloud.githubusercontent.com/assets/3864426/20618074/57f3f46e-b2ed-11e6-818c-78c3ff08be33.png)

Is this what you guys are doing as well? Or do you have another way of handling the keyboard show/hide events on iOS?

**Comment by guyca** [comment]
We're using [wix/react-native-keyboard-aware-scrollview](https://github.com/wix/react-native-keyboard-aware-scrollview/). It's a component @artald wrote before KeyboardAvoidingView was available. It can take care of automatically scrolling to the focused `TextInput` component for you.
On Android it just returns the regular `ScrollView` 😃
