### ISSUE TITLE
Error: popping component failed with stack custom id

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#4920]
### Issue Description

I have a stack with a custom id:
```
Navigation.setRoot({
	root: {
		sideMenu: {
			left: {
				component: {
					id: IDs.DRAWER,
					name: MySideMenu,
				}
			},
			center: {
				stack: {
					id: IDs.MY_STACK,
					children: [{
						component: {
							name: HomePage,
						},  
					}],
				}
			},
		},
	}
});
```

1 - I push a screen to the stack => OK, push works
2 - Then I pop with `Navigation.pop(IDs.MY_STACK).catch(console.log)` => OK, pop works, nav comes back to HomePage screen
3 - I push again a screen to the stack => OK, push works
4 - I pop again with `Navigation.pop(IDs.MY_STACK).catch(console.log)` => NOK, pop doesn't work and XCode logs shows `Error: popping component failed`.

Why? That use case should work, right?

---
### Environment
* React Native Navigation version: 2.16.0
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device - iPhone SE, iOS 12.0.1, Debug

**Comment by zabojad** [comment]
@guyca am I wrongly using the custom ids here?

**Comment by rphlmr** [comment]
I try this myself and it doesn't work.
So in pop() I use the componentId given in prop.

**Comment by zabojad** [comment]
@rphlmr yep but here, I'm doing poping a screen from another component that doesn't have access to the componentId of the screen I want to pop. That basically why I'm using a custom id on the stack...

**Comment by rphlmr** [comment]
I understand the documentation like this : pop take in param the current component id to pop from the stack. Maybe I misunderstand :) 

Did you try popTo or popToRoot ?

**Comment by gigby** [comment]
Still reproduced. Method pop() doesn't work with layout id on iOS and Android. It tested on react-native-navigation v6.5.0 (RN 0.62). Method popToRoot() works as expected.

**Comment by yasir2hats** [comment]
@guyca @yogevbd 
Is still an issue in ios with RNN 6.7.1 and RN 0.62.2
working fine on older projects with RNN 4.8.3 and RN 0.61.5,

**Comment by alex-phillips** [comment]
I think I have a similar issue. We just upgraded from 4.8.3 to 6.7.1. We were registering a `registerBottomTabSelectedListener` that did a `popToRoot` on the "previous" tab, the idea being to reset that tab's stack so going back to that tab later didn't have a stack. This is working on android but not on iOS.

**Comment by alex-phillips** [comment]
So it looks like in the "registerBottomTabSelectedListener", the arguments "selectedTabIndex" and "unselectedTabIndex" is always 0 in my case.

**Comment by alex-phillips** [comment]
Confirming that on android they are correct and different. on iOS, they are both always 0.
