### ISSUE TITLE
[Android][V2] Dismissing a modal over a pushed screen causes crash

### ISSUE THREAD

**Issue by mdermksian** [wix/react-native-navigation#4921]
### [ANDROID] Dismissing a modal over a pushed screen causes crash

My app is a tab-based app with various pushed screens and modals. Currently (and only on android), we have several areas of the app where a screen is pushed, and a modal is shown over the pushed screen. In all areas where this is the case, calling `dismissAllModals()` results in an app crash.

### Steps to Reproduce / Code Snippets / Screenshots
1. Launch android app
2. Push a screen
3. Display a modal over that pushed screen
4. Dismiss the modal.

##### Stack trace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
        at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.setTitleInactiveTextSizeInSp(AHBottomNavigation.java:1184)
        at com.reactnativenavigation.presentation.BottomTabPresenter.applyOptions(BottomTabPresenter.java:55)
        at com.reactnativenavigation.viewcontrollers.bottomtabs.BottomTabsController.applyOptions(BottomTabsController.java:90)
        at com.reactnativenavigation.viewcontrollers.ViewController.onViewAppeared(ViewController.java:206)
        at com.reactnativenavigation.viewcontrollers.ChildController.onViewAppeared(ChildController.java:34)
        at com.reactnativenavigation.viewcontrollers.ViewController.onGlobalLayout(ViewController.java:259)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:945)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2250)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

##### Function definition for pushed screen:
```js
export const goToContestInfo = (rootId, contestId) => {
    Navigation.push( rootId, {
        component: {
            name: 'contestInfo',
            passProps: {
                contestId,
            },
            options: {
                bottomTabs: { visible: false , drawBehind: true, animate:true},
                topBar: {
                    title: {
                        text: 'INFO',
                        color: 'white'
                    },
                    visible: true,
                    buttonColor: "white",

                    backButton: {
                        visible: true,
                        color:"white",
                        icon: getBackArrow(),
                    },
                    background:{

                        color: COLORS.dark

                    },
                }
            },
        }
    })
};
```

##### Function definition for showing modal:
```js
export const goToGenericWebView = ( source ) => {
    Navigation.showModal({
        stack: {
            children: [
                {
                    component: {
                        name: "genericWebView",
                        passProps:{
                            source
                        },
                        options:{
                            overlayPresentationStyle: "overCurrentContext",

                            topBar: {
                                title: {
                                    component:{
                                        name:'logoHeader',
                                        alignment: 'center',
                                    }
                                },
                                visible:true,

                                background: {
                                    color: COLORS.dark
                                },
                                rightButtons:[
                                    {
                                        id:"closeWebViewModal",
                                        component: {
                                            name: 'iconButton',
                                            passProps:{
                                                onPress: () => {
                                                    Navigation.dismissAllModals()
                                                },
                                                source:closeButton,
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                    }
                }
            ]
        }
    })
}
```

---
### Environment
* React Native Navigation version: 2.15.0
* React Native version: 0.59.2
* Platform(s) (iOS, Android, or both?): Android only
* Device info (Simulator/Device? OS version? Debug/Release?): Android simulator, OS version 8/9 (both tested), Debug

**Comment by mdermksian** [comment]
Has anyone been able to reproduce this? I've spent a lot of time trying to troubleshoot this from the JS end and had no luck. As a temporary fix, I went into `BottomTabPresenter.java` and commented out line 55: `bottomTabs.setTitleInactiveTextSizeInSp(i, tab.fontSize.hasValue() ? Float.valueOf(tab.fontSize.get()) : null);` and the program runs as expected. We don't use an inactive text size on the tabs, but I imagine this won't work for people who do.

**Comment by mdermksian** [comment]
Also, I looked at https://github.com/aurelhubert/ahbottomnavigation/blob/master/ahbottomnavigation/src/main/java/com/aurelhubert/ahbottomnavigation/AHBottomNavigation.java and it looks like in the most recent version they've changed the class slightly with regard to these functions.

in the version you're using, `getInactiveTextSize` and `getActiveTextSize` are slightly different. The inactive text size function doesn't have the `.floatValue()` casting function. It seems like this could be the problem?

**Comment by moneymc** [comment]
Same problem.
mdermksian's solution works for me.

**Comment by Siddharth-Stark** [comment]
I have found a simple solution for this problem. Just add tab style (i.e fontSize and other styles ) to the pushed screen even if the tab is hidden. This could solve the app crash problem without touching the native java code

**Comment by loga4** [comment]
+1

**Comment by Jatapiaro** [comment]
@Siddharth-Stark could you please put an example of what are you doing?

**Comment by mdermksian** [comment]
Not stale! I believe this is being worked on and should not yet be closed

**Comment by Siddharth-Stark** [comment]
> @Siddharth-Stark could you please put an example of what are you doing?

You can add static navigation options like in the pushed screen

`  static options(passProps) {
    return {
      bottomTabs: {
        visible: false,
        animate: false, // Controls whether BottomTabs visibility changes should be animated
        drawBehind: true,
      },
      bottomTab: {
        fontSize: 11,
      },
    }
  }`

Even if tabs are hidden you should just add tab font size in the options.. this prevents crash and you dont have to touch any native android code too.

**Comment by amin3mej** [comment]
The problem not solved yet. 
Do you need any more informations?

**Comment by alexsoul95** [comment]
Same here

**Environment**

- React Native Navigation version: 2.26
- React Native version: 0.59.10
- Platform(s) (iOS, Android, or both?): Android only

**Comment by alexsoul95** [comment]
The problem is solved by adding 
`options: {
            bottomTab: {
              fontSize: 12,
            }
          },`
to the pushed screen where you adding then dismissing modals.

**Comment by alexsoul95** [comment]
> options: {
            bottomTab: {
              fontSize: 12,
            }
          }, 
helps

**Comment by alexsoul95** [comment]
Basically, when you push screen (without specifying fontSize of bottomTab) -> add modal -> dismiss modal, will crash with logcat error at : `at com.aurelhubert.ahbottomnavigation.AHBottomNavigation.setTitleInactiveTextSizeInSp(AHBottomNavigation.java:1184)`

**Comment by Jatapiaro** [comment]
I'm still stuck with this problem:

```
            Navigation.showModal({
                stack: {
                    children: [{
                        component: {
                            name: 'containers-app.ContainersConfigureDeviceScreen',
                            passProps: {
                                claimCode: claimCode
                            },
                            options: {
                                topBar: {
                                    title: {
                                        text: 'Configurar Dispositivo'
                                    },
                                    leftButtons: [
                                        {
                                            id: 'cancelDeviceConfiguration',
                                            icon: res
                                        }
                                    ],
                                },
                                bottomTabs: { 
                                    visible: false, 
                                    animate: false, 
                                    drawBehind: true, 
                                }, 
                                bottomTab: {
                                    fontSize: 11, 
                                }, 
                            }
                        }
                    }]
                }
            });
```
That is the code i'm using in order to prevent the crash on android but it is not working

**Comment by alexsoul95** [comment]
@Jatapiaro you don't have to add bottomTab prop to Navigation.showModal. You have to add it to the pushed screen (inside Navigation.push) where you adding then dismissing modals.

**Comment by syedazeemahmed** [comment]
This issue should not be closed because its not yet fixed
