### ISSUE TITLE
Adding swipe to close on modal

### ISSUE THREAD

**Issue by sajsanghvi** [wix/react-native-navigation#4922]
### Issue Description

Adding swipe to close on modal

### Environment
* React Native Navigation version: 2.16.0
* React Native version: 0.59.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): both

I'm wondering where to put the Pan Gesture Recognizer. I tried putting it in UIViewController+RNNOptions but it doesn't seem to work. Anyone successfully done this?

**Comment by jinshin1013** [comment]
You could have a transparent view on modal and add swipe gesture to move the view down and at certain y axis you could dismiss the modal to kinda mimic swipe to close modal.

**Comment by kyle-ssg** [comment]
I don't think you could, that would involve also moving the native modal navbar.

**Comment by pribeh** [comment]
You can do something like this easily:

https://github.com/wix/react-native-navigation/issues/3667#issuecomment-416987134

If you want to do something with more control I recommend using the following with gesture handler and reanimated (gesture handler is required by RNN):

https://github.com/kmagiera/react-native-reanimated/blob/master/Example/Interactable.js

**Comment by pribeh** [comment]
@kyle-ssg you are correct, you'd have to add your own navbar.
