### ISSUE TITLE
Is there a way to have the side menu displayed over any modal?

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#4923]
### Issue Description

Currently, if I open a modal both on iOS and Android, the side menu is behind the modal and cannot open over it.

Is there a way to display/open it over any modal?---
### Environment
* React Native Navigation version: 2.16.0
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Any

**Comment by zabojad** [comment]
@guyca @ItsNoHax @yogevbd guys, sorry to ping you like that but that issue could be easily closed just with an answer. Maybe you would have this answer?

**Comment by mayconmesquita** [comment]
i want to know this too
