### ISSUE TITLE
Android - Cannot pass props to topBar title component

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#4924]
### Issue Description

Passing props to topBar title component works on iOS but not on Android.

Here is what I'm doing:
```
Navigation.showModal({
    stack: {
        id: "test-stack",
        children: [{
            component: {
                name: MyScreen,
            }
        }]
    }
})
```

I tried static options on MyScreen:
```
static var options = {
    topBar: {
        title: {
            component: {
                passProps: {
                    hideMenuButton: true,
                }
            }
        }
    }
}
```
as well as a call to `mergeOptions` when component is showing up:
```
class MyScreen {

// ...

    function componentDidAppear() {
	 Navigation.mergeOptions(props.componentId, options);
    }

// ...
```

as well as passing those option in the `Navigation.showModal` call:
```
Navigation.showModal({
    stack: {
        id: "test-stack",
        children: [{
            component: {
                name: MyScreen,
                options: options
            }
        }]
    }
})
```

None of them work on Android :(

---
### Environment
* React Native Navigation version: 2.16.0
* React Native version: 0.57.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Android 8

**Comment by chyrta** [comment]
Having the same issue

**Comment by zabojad** [comment]
This issue is still happening on v 2.18.4 :(...

**Comment by micheleb** [comment]
still having this issue on v 2.21.0

**Comment by zabojad** [comment]
Same issue on v 2.26.5...
