### ISSUE TITLE
Could not find com.android.support:appcompatv7:28.0.0 error

### ISSUE THREAD

**Issue by onurcagilci** [wix/react-native-navigation#4927]
### Issue Description
I am adding react-native-navigation lib and doing all installation step. but I am still taking sync failed error.

Here is what I am doing:

![2019-03-25_11-10-35-6511360a42aa4626b98ad5cf0e6cefec](https://user-images.githubusercontent.com/37251596/55233974-204d5d80-523b-11e9-92b6-101e4b3257d8.PNG)
![2019-03-25_11-10-35-9977471550267e6985e44133ab062d0e](https://user-images.githubusercontent.com/37251596/55234014-31966a00-523b-11e9-95af-88d37b5428ba.PNG)
![2019-03-25_11-10-35-a30e5eeb039f566ec2fb38f2e5790670](https://user-images.githubusercontent.com/37251596/55234040-3d822c00-523b-11e9-8643-a71da162bd62.PNG)
![2019-03-25_11-10-35-aa757b33101e0846fcc2728b414172d8](https://user-images.githubusercontent.com/37251596/55234061-470b9400-523b-11e9-90d7-3d1d4c987bdf.PNG)
![2019-03-25_11-05-04-8634e7e15d4a7ccd1d7aa19d7589ae40](https://user-images.githubusercontent.com/37251596/55234078-525ebf80-523b-11e9-95a7-614f7dfb1891.PNG)

How can I fix this?

---
### Environment
* React Native Navigation version: "^2.16.0"
* React Native version:"0.59.1"
* Platform(s) (iOS, Android, or both?):Android(3.3.0)
* Device info (Simulator/Device? OS version? Debug/Release?): Device,Windows10

**Comment by N3TC4T** [comment]
You have typo problem 

it should be 

`implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"`

not 

`implementation "com.android.support:appcompatv7:${rootProject.ext.supportLibVersion}`
