### ISSUE TITLE
java.lang.NullPointerException after updating to 143

### ISSUE THREAD

**Issue by Antonides** [wix/react-native-navigation#493]
After updating to 143 the android version crashed with the following error.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.testApp/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.reactnativenavigation.params.StyleParams$Color.hasColor()' on a null object reference
```

**Comment by guyca** [comment]
published .144 with the fix. Thanks for reporting

**Comment by kis25791** [comment]
@guyca I got this NullPointerException when run in Android. Could you please check for me?
<img width="1040" alt="screen shot 2017-03-17 at 5 21 14 pm" src="https://cloud.githubusercontent.com/assets/9639683/24039017/4ea98aee-0b36-11e7-87ec-4b07550c8b42.png">

**Comment by kis25791** [comment]
@guyca I found the problem, in Android, your ButtonFactory was required a specified ID
