### ISSUE TITLE
[V2][ANDROID] Tab bar label not centered with icon

### ISSUE THREAD

**Issue by marf** [wix/react-native-navigation#4931]
### Issue Description

Hello,
Tab bar label is not aligned with its icon, for example in library tab at the bottom icon is not centered with label.
This problem only happens on Android, while in iOS everything is aligned.

### Steps to Reproduce / Code Snippets / Screenshots

![tabbar](https://user-images.githubusercontent.com/485566/55278454-c4eba000-530c-11e9-8661-2275b766a7be.png)
---
### Environment
* React Native Navigation version: 2.15.0
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both simulator/device and debug/release

Best Regards,
Marco

**Comment by retyui** [comment]
I created example https://gist.github.com/retyui/cb30ff8d96c9f0f5dce66a52ea199e39
And don't see a problem with alignment
<a href="https://user-images.githubusercontent.com/4661784/55320055-f2f0f180-547e-11e9-821e-e16085e4bede.png">
<img src="https://user-images.githubusercontent.com/4661784/55320055-f2f0f180-547e-11e9-821e-e16085e4bede.png" width="300" />
</a>

Maybe your icons have a transparent indent?

**Comment by marf** [comment]
Hello, thank you!
This is very strange because in iOS it works, while in Android not.
If there is a transparent indent it shouldn't work neither for iOS.

**Comment by geroale** [comment]
Same issue here. In my case, I am not using the require but the package react-native-vector-icons, using its method createIconSet and passing the component in the tabIcon. On iOS it’s perfectly cantered but not on Android.

**Comment by marf** [comment]
I am using react-native-vector-icons too, and this problems happens only on Android and not iOS

**Comment by LRNZ09** [comment]
I am having the same issue.

**Comment by mbizplus** [comment]
same issue...

**Comment by dgellisco** [comment]
Same issue

**Comment by ItsNoHax** [comment]
Hi @marf , @LRNZ09, @mbizplus , @dgellisco, @geroale 

I'm running into the same problem inside my app and I've been messing around with RNN's bottomtab library: https://github.com/wix-playground/ahbottomnavigation/

But I have come to the conclusion that the problem is in react-native-vector-icon's Android loadIconFromSource (I assume that is what you all are using?)

It seems to happen to SVG's that have a larger width than height, they seem to get cropped incorrectly to 24x24 (in my case)

**Comment by LRNZ09** [comment]
I can confirm, I have made a patch for now inside `android/src/main/java/com/oblador/vectoricons/VectorIconsModule.java`, which seems to solve the issue.
```java
i̶n̶t̶ ̶o̶f̶f̶s̶e̶t̶X̶ ̶=̶ ̶0̶;̶
int offsetX = (size / 2) - ((int) paint.measureText(glyph) / 2);
```

**Comment by ItsNoHax** [comment]
@LRNZ09 I tried your fix but it's not working correctly with: https://fontawesome.com/icons/inbox?style=regular

**Comment by LRNZ09** [comment]
@ItsNoHax I'm using Ionicons, haven't tested with other icon packs

**Comment by ItsNoHax** [comment]
I went ahead and created an issue in react-native-vector-icons: https://github.com/oblador/react-native-vector-icons/issues/1054

If you could go ahead and post your findings there we can possibly get this resolved asap.
