### ISSUE TITLE
[V2][RN-0.59][Android] - Works in DEBUG but crashes in Release Mode

### ISSUE THREAD

**Issue by nickrobinson352** [wix/react-native-navigation#4933]
I upgraded my project to RN 0.59 to take advantage of the performance gain, however the app crashes in the Release mode with the following Exception

```
03-31 21:57:56.206 30342 30384 E AndroidRuntime: FATAL EXCEPTION: mqt_js
03-31 21:57:56.206 30342 30384 E AndroidRuntime: Process: com.threesixtymemos.MonarchToday, PID: 30342
03-31 21:57:56.206 30342 30384 E AndroidRuntime: com.facebook.jni.UnknownCppException: Unknown
03-31 21:57:56.206 30342 30384 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-31 21:57:56.206 30342 30384 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:746)
03-31 21:57:56.206 30342 30384 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
```

I have got the iOS to work in both Release and Debug. In Android, Debug works fine but Release crashes immediately.

---
### Environment
* React Native Navigation version: 2.16.0
* React Native version: 0.59
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Works in Debug, crashes in Release

**Comment by guyca** [comment]
Hey @nickrobinson352 
That stack trace doesn't indicate the crash is related to RNN

**Comment by pritasam** [comment]
Hey any updates on this crash I am also getting the same issue

**Comment by greulist137** [comment]
I am having the same issue

**Comment by nickrobinson352** [comment]
I am no longer having this issue. I upgraded to 59.8, enabled AndroidX etc and its now working
