### ISSUE TITLE
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :react-native-camera.

### ISSUE THREAD

**Issue by ankitgauravapporio** [wix/react-native-navigation#4934]
### Issue Description

[ENTER DESCRIPTION HERE]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by retyui** [comment]
Are you thinking you get this error because of use `react-native-navigation`?

**Comment by ankitgauravapporio** [comment]
@retyui  no , i am getting this while implementing react native camera

**Comment by retyui** [comment]
@ankitgauravapporio and how does your problem relate to react-native-navigation?

**Comment by rphlmr** [comment]
It's due to "missingDimensionStrategy" recommendation on react-native-camera documentation. 
It says to add `"react-native-camera", "general"`and it breaks an already working react-native-navigation setup ;)

**Comment by rphlmr** [comment]
I find a solution.

In app build.gradle, add a second line of `missingDimensionStrategy` : 

```
missingDimensionStrategy "react-native-camera", "general"
missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57_5"
```

It works for me :)
