### ISSUE TITLE
Extracting ComponentId from Stateless/Function Component

### ISSUE THREAD

**Issue by vedovato** [wix/react-native-navigation#4938]
### Issue Description

Is there a way to get/extract ComponentId from stateless/function components?

I know that's possible to pass it as prop when registering the screen and easily get it from Class Components or with mapStateToProps from Redux's connect() but in this case, i'd like a way to avoid using classes or connect() just for this sole purpose as the screen doesn't accomplish much beyond rendering information and linking to another screen.

If i register a stateless component as screen, i do have to carry on that prop from the Component to the function that pushes another screen. Ideas? :)

---
### Environment
* React Native Navigation version: 0.59.2
* React Native version: ^2.16.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): any

**Comment by jinshin1013** [comment]
Are you suggesting a way to register functional component? It's little hard to understand the actual problem you are suggesting.

**Comment by vedovato** [comment]
Ops, my bad. I'm actually asking for a way to push a new screen to the stack from a functional component instead of a stateful/class one.

Question is based in the fact i have to call pushScreen and pass the current ComponentId which doesn't exist by default in stateless/functional component.

**Comment by jinshin1013** [comment]
Stateless/functional component doesn't have the current componentId because it is not the screen that has been registered, and you want a way to somehow have these functional components to have the context of the current componentId? Sorry if I misunderstood your problem :(

**Comment by vedovato** [comment]
Yeah, that's right :)

**Comment by jinshin1013** [comment]
I see, I always wanted some magic like this as well having to pass around componentId could be tedious work. I've found some workarounds that could ease off that pain but it doesn't involve any magic unfortunately. Reference below:

```tsx
/* 
 * createProvider.tsx
 * This is a HOC component used when you register the screen
 */
...
class HOC extends React.Component {
  push = (route: string) => Navigation.push(this.props.componentId, {/* layout */})
  pop = () => Navigation.pop(this.props.componentId)

  render() {
    return (
      <Provider store={rootStore}>
        <WrappedComponent push={this.push} pop={this.pop} {...this.props} />
      </Provider>
    )
  }
}
...
```

It doesn't exactly solve your problem but could ease off the pain to pass around componentId. Another solution is to use React context and useContext to receive componentId in any functional component.

**Comment by vedovato** [comment]
Hey @jinshin1013, thank you! I see what you did.
Will give it a try later and give you some feedback :)

I was exporting a push function and passing around ComponentId from caller screen and despite of having Redux setup in this app i didn't think about appending the function to a parent HOC would "solve" it for now.

**Comment by guyca** [comment]
I think https://github.com/mridgway/hoist-non-react-statics is what you're looking for
