### ISSUE TITLE
Ram Bundles and Inline require

### ISSUE THREAD

**Issue by jinshin1013** [wix/react-native-navigation#4940]
### Issue Description
As part of new release of react-native, they released a performance boost feature where you can essentially "lazy-load" components and screens, more [info here](https://facebook.github.io/react-native/docs/performance#ram-bundles-inline-requires). Surprisingly, turning on these features worked out of the box. And when it comes to using react-native-navigation, I was wondering if there is a recommended way to use `registerComponent` to register your screens later. So in my case, I've got essentially 2 different types of screen collection, public and private. Public screens are those before the user logs in and Private screens are those after user logs in. So at the moment, I am using `SplashScreen` to register all these screens. Reference below:

```
// Splashscreen.tsx
..... 
componentDidMount() {
  // hydrate mobx store
  for (const [route, component] of publicScreens) {
    Navigation.registerComponent(route, () => createPublicProvider(component, rootStore))
  }

  for (const [route, component] of privateScreens) {
    Navigation.registerComponent(route, () => createPrivateProvider(component, rootStore))
  }
}
.....
```

Upon checking all the loaded modules, it did require and load every screens and the components used to build the screens. And if I do something like below:

```
// Splashscreen.tsx
..... 
componentDidMount() {
  // hydrate mobx store
  if (userLoggedIn) {
    for (const [route, component] of privateScreens) {
      Navigation.registerComponent(route, () => createPrivateProvider(component, rootStore))
    }
    return
  }

  for (const [route, component] of publicScreens) {
    Navigation.registerComponent(route, () => createPublicProvider(component, rootStore))
  }
}
.....
```

Either type of the screens are later registered when user logs in or logs out but only if necessary. It does reduce the number of modules loaded to the app which result in boost in start up time; don't have the exact stat :(

Do you see this as a viable choice now that lazy load is possible in react-native? And whether this could be somehow built in to the library? Or is it just waste of time? Love to hear you guys thought on this.

### Environment
* React Native Navigation version: 2.12.0
* React Native version: 0.59.3
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by retyui** [comment]
We have implemented this improvement a long time ago everything works well

```js
Navigation.registerComponent(AUTH_SCENE_ID, () => wrapProvider(require('./AuthScren').default , store));
```

**Comment by jinshin1013** [comment]
Do you see any noticeable start up time improvement or any performance increase with Ram bundle and inline require enabled?

**Comment by retyui** [comment]
We didn't measure the result before and after

**Comment by guyca** [comment]
@jinshin1013 I think **inline requires is pretty much a must** - we've switched to inline requiring screens last year and immediately noticed a 2 seconds improvement in startup time.

Recently we made a dedicated effort and switched everything we could to inline requires, not only screens, and shaved a few more seconds from our startup time. We also moved any logic from screen constructors to componentdidAppear. 
The idea is to be able to control when logic is executed - usually you'd want to avoid having stuff running when an object is created as that introduces delays when creating screens - whether through push or setRoot. That means that **we've stopped using ES6 import and switched to inline requires**.
There's a nice bable transformer that transforms import statements to inline requires.. can't find it atm.

**Comment by pontusab** [comment]
@guyca Is it in metro.config.js you thinking about:

```

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
}
```

**Comment by hammadj** [comment]
> @jinshin1013 I think **inline requires is pretty much a must** - we've switched to inline requiring screens last year and immediately noticed a 2 seconds improvement in startup time.
> 
> Recently we made a dedicated effort and switched everything we could to inline requires, not only screens, and shaved a few more seconds from our startup time. We also moved any logic from screen constructors to componentdidAppear.
> The idea is to be able to control when logic is executed - usually you'd want to avoid having stuff running when an object is created as that introduces delays when creating screens - whether through push or setRoot. That means that **we've stopped using ES6 import and switched to inline requires**.
> There's a nice bable transformer that transforms import statements to inline requires.. can't find it atm.

@guyca Are you doing inline requires manually? Or are you using a babel transformer? If so, which one?

**Comment by guyca** [comment]
@hammadj Right now we're manually requiring modules. We've recently upgraded our app to RN 0.59 and plan to use the `inlineRequire` flag in `metro.config`

**Comment by karlmarxlopez** [comment]
@guyca Hi. Can you provide us an example or a gist on how you did it? Thank you so much!

**Comment by JulianKingman** [comment]
In the docs it says:
> Note: If you are using Hermes JS Engine, you should not have RAM bundles feature enabled. In Hermes, when loading the bytecode, mmap ensures that the entire file is not loaded. Using Hermes with RAM bundles might lead to issues, because those mechanisms are not compatible with each other.

There's no indication of which one is better, or how to choose, or what criteria to consider... does anyone have an answer to that?
