### ISSUE TITLE
showAsAction not working on iOS

### ISSUE THREAD

**Issue by kheraprabhat** [wix/react-native-navigation#4941]
### Issue Description

showAsAction not working

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.mergeOptions(this.props.componentId, {
      topBar: {
        title: {
          text: "Title",
        },
        rightButtons: [
          {
            id: 'add_property1',
            text: "add",
            color: colors.link,
            showAsAction: 'always'
          },
          {
            id: 'add_property',
            text: "add",
            color: colors.link,
            showAsAction: 'ifRoom'
          },
        ],
      }
    });
```

---
### Environment
* React Native Navigation version: 2.16.0
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by retyui** [comment]
This props implemented only for Android: https://github.com/wix/react-native-navigation/search?q=showAsAction&unscoped_q=showAsAction

**Comment by ItsNoHax** [comment]
As @retyui said, this is a Android only feature as it's supported by the native top bar. https://developer.android.com/training/appbar/actions#add-actions
