### ISSUE TITLE
[v1] What is the latest react-native version supported?

### ISSUE THREAD

**Issue by mromarreyes** [wix/react-native-navigation#4946]
What is the latest version of react-native that I can use to run version 1 of react-native-navigation?

I'm currently running react-native version: 0.59.3 with react-native-navigation version: 1.1.489 without issues on iOS. On Android I get a white screen on the emulator after running react-native run-android but if I generate a signed APK in Android Studio and load it on my phone it works without issues.

It sounds like I need to spend some time upgrading to version 2.

**Comment by DanielBoening** [comment]
Hi,
i'm currently running into the same problem. Did you find a solution for v1? As I would really appreciate not updating.

**Comment by trippypro** [comment]
> Hi,
> i'm currently running into the same problem. Did you find a solution for v1? As I would really appreciate not updating.
> 
> Edit:
> I guess this bug is related to this issue #4962
> So it seams the problem is not related to v1.

+1
I'm getting this error:

ReactNativeJS: Error while starting app: Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.
ReactNativeJS: [[28,21],[36,0],[[17,2000,1564033414525,false]],9]
