### ISSUE TITLE
[V2] Is there a possibility to change android navigation bar and soft buttons color

### ISSUE THREAD

**Issue by SergeyBazhanov** [wix/react-native-navigation#4949]
### Issue Description

Hi. Thank you for this awesome package. In V1 there is a possibility to change at least navigation bar color. Could you hint me if there is similar functionality in V2? Didn't find anything in the docs. 

I can use separate packages for that purpose, but i don't want to add unnecessary third party dependencies. 

Maybe someone can also hint me how to change android soft buttons color (navigation bar style)? It would be great. Because if i make navigation bar white - soft buttons becomes almost invisible, so need to change somehow their color also

Thanks in advance

![Screenshot 2019-04-05 at 10 42 03](https://user-images.githubusercontent.com/16165550/55611868-7f592800-578f-11e9-9255-6b45773c01c4.png)

---
### Environment
* React Native Navigation version: 2.16.0-snapshot.265
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Any android device with soft buttons

**Comment by a7urag** [comment]
Use statusBar option to change the color of the Android status bar.

**Comment by SergeyBazhanov** [comment]
Yes, i can change color of statusBar, but i'm asking about navigation bar i showed on screenshot above. Thank you

**Comment by a7urag** [comment]
You can directly change it without react-native-navigation. Try https://stackoverflow.com/a/47341768/9821453

**Comment by SergeyBazhanov** [comment]
I managed to do what i need using the following package: https://github.com/thebylito/react-native-navigation-bar-color
Thanks for your reply. This issue-question can be closed now

**Comment by D4nt4lion** [comment]
I got the same problem. I need to change the soft button color dynamically. It was easily possible in v1 but I can't find anything about v2...

Using a third party library is not really a solution for me.

**Comment by Pragati20** [comment]
I too have same issue, react-native-navigation-bar-color is not working for me.Can this question be reopened?

**Comment by debold-tech** [comment]
any updates?
