### ISSUE TITLE
How to detect when app is ready?

### ISSUE THREAD

**Issue by florianbepunkt** [wix/react-native-navigation#495]
I'm using firestack library (firebase) to implement an authentication listener on app root component. based on auth status I start a single page app or tab based app.

this auth state listener works when using normal navigator, but with react-native-navigation I only see the splashscreen when starting the app and nothing else. So the auth state listener is either never triggered at all or too early (before app is ready). However when I reload (Cmd + R), the my auth listener works and the correct screen is displayed.

Is there some sort of event that tells me navigation is ready to start single page app or tab based app?

My root component looks like this

```js
import React, { Component } from 'react';
import { Navigation } from 'react-native-navigation';
import { registerScreens } from './screens.js';
import firestack from './components/firebase';

registerScreens();

/**
 * handle authentication
 */
firestack.auth().onAuthStateChanged((user) => {
  if (user) { 
    // user is signed in
    authenticatedRoutes();
  }
  else {
    // use is not signed in
    unauthenticatedRoutes(); 
  }
});

function authenticatedRoutes() {
  Navigation.startTabBasedApp({
    tabs: [
      {
        label: 'Search',
        screen: 'roomary.SearchPage', // this is a registered name for a screen
        icon: require('./assets/images/one.png'),
        selectedIcon: require('./assets/images/one_selected.png'), // iOS only
        title: 'Search'
      },
      // left out for brevity
    ]
  });
}

function unauthenticatedRoutes() {
  Navigation.startSingleScreenApp({
    screen: {
      screen: 'roomary.LoginPage',
      title: 'Anmelden'
    }
  });
}
```

**Comment by guyca** [comment]
I don't see anything wrong with your approach - it should work.
When you app is "ready" - it loads react context and static Js code is executed. Can you add some logs, and see which parts are executed and which aren't?

**Comment by florianbepunkt** [comment]
@guyca thank you. Not 100 percent sure yet, but there seems to be some bugs (not related to this repo), but to RN's reote debug function. if I disable remote debug it works… but turning off debuging was not really the first thing that came to my mind when trying to debug a problem :D

anyway, thank you for this great repo. I'm closing this now.
