### ISSUE TITLE
BottomTabs icons cropped

### ISSUE THREAD

**Issue by 3luyka** [wix/react-native-navigation#4951]
For some reason icons (react-native-vector-icons) in bottomTabs appears cropped on Android.

![image](https://user-images.githubusercontent.com/40960820/55627214-454f4c80-57b6-11e9-8b6a-5ae6490e61a8.png)

**Comment by RominHalltari** [comment]
Did you find a solution for this?

**Comment by Estebank94** [comment]
I'm also having this issue. Did anyone solve it?

**Comment by OrLavy** [comment]
Same problem here, using 'Fontaswsome 5 pro'.
On real Android device the icons are awfully cropped, on IOS simulator the very same icons are displayed perfectly.

**Comment by Estebank94** [comment]
Still having the same issue. Did anyone solve this?

**Comment by ItsNoHax** [comment]
@Estebank94 @OrLavy @RominHalltari The issue lies in react-native-vector-icons, you can follow the issue I created there: https://github.com/oblador/react-native-vector-icons/issues/1054
