### ISSUE TITLE
package com.reactnativenavigation.NavigationActivity does not exists

### ISSUE THREAD

**Issue by dcabib** [wix/react-native-navigation#4952]
### Issue Description

During the project build in Android Studio (after configuring my react native with navigation project), Android Studio informs that com.reactnativenavigation.NavigationActivity does not exists.

I was following this instructions: https://wix.github.io/react-native-navigation/#/docs/Installing

I've included the following lines on settings.grandle:

include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/lib/android/app/')

The project was OK until I modify MainActivity.java and MainApplication.java including react-native-navigation classes.
 
### Steps to Reproduce / Code Snippets / Screenshots

![image](https://user-images.githubusercontent.com/28359711/55634141-33f54880-5794-11e9-8b5e-ccd72fbf0539.png)

![image](https://user-images.githubusercontent.com/28359711/55634337-ad8d3680-5794-11e9-91b5-8538d06a7849.png)

![image](https://user-images.githubusercontent.com/28359711/55634743-753a2800-5795-11e9-816c-2fca7f16eb5f.png)

![image](https://user-images.githubusercontent.com/28359711/55634895-ce09c080-5795-11e9-9306-9ff062b562e5.png)

![image](https://user-images.githubusercontent.com/28359711/55635202-87689600-5796-11e9-9a0d-12032c1a7f67.png)

---
### Environment
* React Native Navigation version: "2.16.0"
* React Native version: 0.59.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All simulators

**Comment by baj9032** [comment]
Found solution of this question?

I have asked similar question on stackoverflow [https://stackoverflow.com/questions/55849097/package-com-reactnativenavigation-does-not-exist](https://stackoverflow.com/questions/55849097/package-com-reactnativenavigation-does-not-exist).

**Comment by kubilaytural** [comment]
I have the same. I checked the linking. I couldn't find the problem. Does anyone solve the problem?

**Comment by RumenKoynov** [comment]
I had exactly the same problem. I tried everything with no result. My version of react native was 0.60.0 and I downgraded it to 0.57.0, repeat the steps in https://wix.github.io/react-native-navigation/#/docs/Installing?id=android and everything was allright.

**Comment by lqrz** [comment]
I have the same issue on RNN 0.60.2 No solution to this? Just closed?

**Comment by sanjay-salunkhe** [comment]
I am also facing same issue

**Comment by rezasazesh** [comment]
Can we get a fix for this please?

**Comment by rezasazesh** [comment]
This should not be closed!

**Comment by rezasazesh** [comment]
if you still have this issue I solved it using [This Comment](https://stackoverflow.com/questions/55849097/package-com-reactnativenavigation-does-not-exist/59812652#59812652)

**Comment by rendomnet** [comment]
same problem with rnn 7.1.0 and rn 0.63.3
