### ISSUE TITLE
[v2] [Android] interceptTouchOutside false does not work

### ISSUE THREAD

**Issue by ssg-luke** [wix/react-native-navigation#4953]
### Issue Description

On Android only, setting option interceptTouchOutside to false does not allow touch events to occur on elements underneath the overlay. On iOS it works perfectly.

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.showOverlay({
          component: {
              id: 'dashboard-action-button',
              name: '/dashboard-action-button',
              options: {
                  overlay: {
                      interceptTouchOutside: false,
                  },
              },
          },
      });
```

---
### Environment
* React Native Navigation version: 2.16.0
* React Native version: 0.59.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device (Samsung Galaxy S8), Android 9.0,

**Comment by ssg-luke** [comment]
I have started looking into this myself and so far I have found that in OverlayTouchDelegate.java in getTouchLocation(MotionEvent ev) this always returns TouchLocation.Inside. Logging I added around it:

```
04-05 16:32:41.886 13702 13702 D RNN     : GEtting action masked
04-05 16:32:41.886 13702 13702 D RNN     : Calling handleDown
04-05 16:32:41.886 13702 13702 D RNN     : hitRect0 0 1440 2672
04-05 16:32:41.887 13702 13702 D RNN     : event raw x: 309.375 y: 1696.7969
```

Hit rect is always the entire screen for the overlay I'm rendering (a single react-native-action-button)

**Comment by ssg-luke** [comment]
I ended up solving this by wrapping the action button in an absolute view with fixed width and height that becomes full size on opening the action button. Seems as though overlays on Android do not care about the value of `pointerEvents` on View components as the action button is internally wrapped by default by an absolute full screen View with `pointerEvents=box-none`

**Comment by rendomnet** [comment]
Did you found solution?

**Comment by LRNZ09** [comment]
Still happens on `2.20.2`

**Comment by fjmorant** [comment]
Hi,

I am having the same issue, I add one more detail if your screen component is like:

```
<TouchableOpacity onPress={() => alert('Touch parent')}>
    <RowView>
        <TouchableOpacity onPress={() => alert('Touch child')}>
            <Icon name={'favourites'} />
        </TouchableOpacity>

        <Icon name={'notifications'} />
        <Icon name={'settings'} />
    </RowView>
</TouchableOpacity>
```

Favourites icon doesn't work it always show touch parent alert, and this works on iOS and without overlay screen.

Does anybody have a clue of what is going on?

Thanks

**Comment by eightyfive** [comment]
Hello @guyca 

I tried to get some logs via:
```
$  adb logcat *:V | grep reactnativenavigation
```

But nothing fails, "touches outside" seem to be completely ignored (Android) and/or not passed through.

Could you point how could we help resolve/debug this issue further?

Thanks in advance.

**Comment by guyca** [comment]
Hey @eightyfive 
There's an e2e test which covers `interceptTouchOutside` flag. You can find it [here](https://github.com/wix/react-native-navigation/blob/master/playground/src/screens/OverlayScreen.js#L39).

What would help is PRing a failing e2e test so we can understand the problem and debug it.

**Comment by fjmorant** [comment]
Hi @guyca ,

Created a PR with a new option in playground for overlay https://github.com/wix/react-native-navigation/pull/5182

![Screenshot_1559678038](https://user-images.githubusercontent.com/6560136/58910106-a2ab3f80-870c-11e9-8c2e-bf418245deff.png)

![Screenshot_1559678568](https://user-images.githubusercontent.com/6560136/58910120-a939b700-870c-11e9-8d0e-ce4f3a75ed2e.png)


I know design is shit but I just wanted to prove that nested touchables in overlay don't work, you can only touch the parent but children somehow cannot respond.

Thanks for your help.

**Comment by guyca** [comment]
@fjmorant Thanks for looking into this. I'll get to it asap

**Comment by fjmorant** [comment]
@guyca Thanks

**Comment by eightyfive** [comment]
@guyca @fjmorant I'll keep an eye on this issue but after installing the playground locally on the same Android device I use, I cannot reproduce my problem.

Meaning I am doing something wrong in my RN app, playground (`showOverlay`) works as expected.

**Comment by fjmorant** [comment]
Hi @eightyfive ,

Have you checked out this https://github.com/wix/react-native-navigation/pull/5182 ? 

If you touch in one of the children what alert message do you get?

I can try to send a video to make things clearer.

Thanks

**Comment by eightyfive** [comment]
I haven't tried you PR because I am battling with the simplest case: Getting touches to go through the overlay.

**Comment by guyca** [comment]
@eightyfive If you can PR/push a branch to your fork with a View where the issue reproduces I can take a look

**Comment by fjmorant** [comment]
Hi @guyca @eightyfive ,

I think we are talking about something different, so I will create another ticket because the issue is different for me nested touchables (no matter which form) in overlays don't work.

Thanks

**Comment by eightyfive** [comment]
Thanks @guyca but I wrote a non-trivial lib/wrapper over RNN and even though it is not _that_ complex, it would be a waste of time for you to go through my custom code in order to help me.

_Good news_: I setup a simple project with this small utility and `interceptTouchOutside` works as expected.

_Bad news (for me)_: In my more complex / real-life project, touches don't go though my overlay.

If (ever) I find out why, I'll post an update here.

**Comment by eightyfive** [comment]
My problem came from using [`react-native-paper`](https://github.com/callstack/react-native-paper).

When using their `<PaperProvider />`, the library adds some `<Portal />` component that intercepts all touches.

They seem to be aware of the unwanted side effects:
https://github.com/callstack/react-native-paper/issues/420

**Comment by rendomnet** [comment]
any updates?

**Comment by samiede** [comment]
Is there any progress on this? I'm trying to implement an upload progress overlay for our app, but the user can't use the app during the overlay, which defeats the purpose

**Comment by eightyfive** [comment]
@samiede With a simple case/setup the problem does not occur. I would say it is likely your problem is caused by another third party library in your project. In my case it was react-native-paper <Provider />.

Hope this helps.

**Comment by piuholo** [comment]
@samiede In my case the `interceptTouchOutside` option failed to work on Android if I used overlay with component that was sometimes `null` or had the width & height of 0.

Could there be such case in your app?

**Comment by samiede** [comment]
Thanks for your replies, I did not get to try it today, but will report back on Monday!

**Comment by atlkuk** [comment]
Re-open the issue because is not fixed yet!

**Comment by mayconmesquita** [comment]
same problem here

**Comment by Pczek** [comment]
This sucks :(

**Comment by rezasazesh** [comment]
Issue still exists

**Comment by samiede** [comment]
We solved it for us. We Use react-native-gesture-handler to be able to use the react-native-tab-view. My colleague noticed that the whole transparent area was registered as one of the wrapped components, so when you're usually using `gestureHandlerRootHOC` to register your screens, just register your overlay without that and it will work!

**Comment by baotoan1905** [comment]
I got same issue if I wrap my overlay component inside redux like bellow 
![image](https://user-images.githubusercontent.com/7258479/82405874-48c39700-9a8f-11ea-8dde-680021ae7c4c.png)
It works if I don't wrap it inside redux provider. I think I have to workaround by not using redux inside this overlay component.
If you guys have any better solutions if share with me.
Many thanks.

**Comment by JB-CHAUVIN** [comment]
I still can't click on my touchables on Android (these touchables are in overlays).

**Comment by baotoan1905** [comment]
I got same issue, and it was because of I wrap my overlay component inside a wrapper. After remove wrapper, it works fine.

**Comment by SasjaVDD** [comment]
> I still can't click on my touchables on Android (these touchables are in overlays).
@baotoan1905 I had the same problem with my touchables in an overlay. After adding zIndex to the outermost parent that contain the touchables the problem was fixed.

**Comment by fancydevpro** [comment]
In our case, `SafeAreaProvider` was causing this issue as well as `gestureHandlerRootHOC`.
We were wrapping all screens with `SafeAreaProvider`.
Hope this helps.

**Comment by arashkevich25** [comment]
still can't click through on my android app

**Comment by erennyuksell** [comment]
gestureHandlerRootHOC it's causing problem still

**Comment by fc-io** [comment]
yeah, this was very annoying. In my case it was "caused" by returning null from the overlay component. 

What I hade done was creating a notifications-toast that returned `null` instead of the `<View>...</View>` when there was no notification message to show. I did not want to use `Navigation.dismissOverlay` cause that caused som flashing/blinking effects when a new notification/overlay was rendered when there already was a message showing. The fix that worked in this case was to, instead of returning `null`, show and hide the notification component with `display: "none" and "flex"`.

**Comment by animatereactnative** [comment]
Still reproducing
