### ISSUE TITLE
setStackRoot not working on iOS (same code works on Android)

### ISSUE THREAD

**Issue by m00gl3** [wix/react-native-navigation#4958]
### Issue Description

The same setStackRoot code that works on Android does not work on iOS simulator.
I'm getting a crash with 

![Screen Shot 2019-04-08 at 10 22 56](https://user-images.githubusercontent.com/1267581/55706056-e3c2f400-59e8-11e9-8cca-e1238bd6b27c.png)

I pasted my App.js root code and the navigation code

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.setRoot({
	  root: {
			sideMenu: {
        left: {
          stack: {
            id: 'SIDE_MENU_LEFT_STACK',
            children: [
              {
                component: {
					name: 'torim.SideMenu',
                  passProps: {
                    side: 'left',
		},
		options: {
			topBar: {
				drawBehind: true,
				visible: false // like navBarHidden:true
				}
			}									
                }
              }
            ]
          }
	},
	center: {
		stack: {
			children: [{
				component: {
					name: "torim.Splash",
					options: {
						topBar: {
								drawBehind: true,
								visible: false 
							},
						layout: {
								orientation: ['portrait'] 
						}				  
					},
					passProps: {
						text: 'This text will be available in your component.props'
					}
				}
			}]
		}
        }
      },
 }
});

navigator.setStackRoot(componentId, {
      component: {
            name: 'torim.MerchantLogin',
            options: {
              animations: {
                setStackRoot: {
                  enable: true
                }
              },
              layout: {
                orientation: ['portrait'] 
              },
              topBar: {
                  drawBehind: true,
                  visible: false,
                }                
            }           
          }
    });
```

---
### Environment
* React Native Navigation version: 2.7.1 and 2.16.0
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6s simulator

**Comment by Pushplaybang** [comment]
Shouldn't you just be using `Navigation.setRoot` ?

**Comment by m00gl3** [comment]
> Shouldn't you just be using `Navigation.setRoot` ?

Using setRoot I get:

![Screen Shot 2019-04-11 at 10 58 27](https://user-images.githubusercontent.com/1267581/55940432-cd1ad800-5c48-11e9-8695-b0a03c73b0a4.png)
