### ISSUE TITLE
[iOS] "Malformed calls from JS: field sizes are different."

### ISSUE THREAD

**Issue by shuzootani** [wix/react-native-navigation#4962]
### Issue Description
The following error pops up just after launching app.
<img width="369" alt="Screen Shot 2019-04-09 at 23 02 42" src="https://user-images.githubusercontent.com/19385183/55807214-c727d880-5b1c-11e9-9c37-64bdb44e0725.png">

I assume that I'm doing something wrong with integration of React context API.
So I'd appreciate if someone could point out what I'm doing wrong with using context API and react-native-navigation.

### Steps to Reproduce / Code Snippets / Screenshots
I'm wrapping a root screen with React Context API based on [this](https://github.com/wix/react-native-navigation/pull/4427)
It doesn't give the error on iPhoneX(12.1) simulator but on some other older versions such as iPhone6(12.1), 6s(12.1).

my index.js looks like below

``` js
function registerComponents() {
  Navigation.registerComponent('Detail', () => Detail)
  Navigation.registerComponent('Preview', () => Preview)
  Navigation.registerComponent('Filter', () => Filter)
  Navigation.registerComponent(
    'Search',
    () => props => (
      <SearchContextProvider>
        <Search {...props} />
      </SearchContextProvider>
    ),
    () => Search
  )
}

registerComponents()

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      stack: {
        children: [
          {
            component: {
              name: 'Search',
              options: {
                topBar: {
                  visible: false
                }
              }
            }
          }
        ]
      }
    }
  })
})

```

---
### Environment
* React Native Navigation version: 2.17.0
* React Native version: 0.59.2
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Debug on simulators, iPhone6(12.1), 6s(12.1). it only works on iPhoneX simulator somehow.

**Comment by AugustoAleGon** [comment]
Same problem

**Comment by dangkhoa2708** [comment]
Same problem after upgrade to RN 0.59.*

**Comment by reyalpsirc** [comment]
Same issue on 0.59.8

**Comment by juliettegodyere** [comment]
I am also getting this same issue

 "react-native": "0.59.8",

**Comment by boythan** [comment]
Same problem with react-native": "0.59.8",

**Comment by DanielBoening** [comment]
I have the same problem but only on Android. On iOs it works fine.

**Comment by martinvol** [comment]
Have the same issue on react-native `0.59.10`

**Comment by misterpoloy** [comment]
Same for me

**Comment by AngelVenchev** [comment]
I am having the same issue on Android.

**Comment by hellochirag** [comment]
Malformed calls from JS: field sizes are different.

[[84,33],[20,0],[[260,2000,1585903674435,false]],3338]

RCTFatal
-[RCTCxxBridge handleError:]
__34-[RCTCxxBridge _initializeBridge:]_block_invoke
facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&)
facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1::operator()() const
decltype(std::__1::forward<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&>(fp)()) std::__1::__invoke<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&>(facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&)
void std::__1::__invoke_void_return_wrapper<void>::__call<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&>(facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&)
std::__1::__function::__alloc_func<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1, std::__1::allocator<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1>, void ()>::operator()()
std::__1::__function::__func<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1, std::__1::allocator<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1>, void ()>::operator()()
std::__1::__function::__value_func<void ()>::operator()() const
std::__1::function<void ()>::operator()() const
invocation function for block in facebook::react::RCTMessageThread::runAsync(std::__1::function<void ()>)
__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
__CFRunLoopDoBlocks
__CFRunLoopRun
CFRunLoopRunSpecific
+[RCTCxxBridge runRunLoop]
__NSThread__start__
_pthread_start
thread_start


 "react": "16.9.0",
 "react-native-navigation": "^6.3.1",
"react-native": "0.61.5",

Don't know why close this issue , if everybuddy facing issue still the day?

**Comment by Jarzka** [comment]
Same issue here on Android when I call `navigator.push`.

It seems that this only happens once during the lifetime of my app. If I dismiss the error message, I can continue normally. When I restart my app and do `navigator.push`, it happens again once and then goes away. However, not all `navigator.push` calls cause this.

**Comment by Jarzka** [comment]
I upgraded to 0.62 and haven't faced this since then.
