### ISSUE TITLE
Tab bar button goes out of bound on navigating back to tab screen

### ISSUE THREAD

**Issue by nak1b** [wix/react-native-navigation#4963]
### Issue Description
Pushing to new screen with **tabbarHidden** set to **true** and poping back to the screen, tabbar is animated from the left and it looks sloppy. Is it a bug or there is prop i can pass to prevent it from animating.

#### Expected Behaviour
Tab bar icon should not animate from left

### Steps to Reproduce / Code Snippets / Screenshots
![bug](https://user-images.githubusercontent.com/2307104/55824139-42639d00-5ad1-11e9-82b9-c377bef3aecf.gif)

---
### Environment
* React Native Navigation version: v1.1.493
* React Native version: ^0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 8, iPhone 6

**Comment by markhomoki** [comment]
This is an iOS issue, not react-native-navigation. Other native apps had the same issue since iOS 12. However, upgrading to v2 fixes this.

**Comment by nak1b** [comment]
> avigation. Other native apps had the same issue since iOS 12. However, upgrading to v2 fixes this.

So there is no way to fix this without upgrading to v2?

**Comment by markhomoki** [comment]
Personally, with v1 I couldn't find any fix, although this doesn't mean there is no fix. I just simply found it easier to upgrade to a newer version/codebase.

**Comment by nak1b** [comment]
@markhomoki I was able to fix this by adding style to tabsstyle
` tabBarTranslucent: false`

Thanks for the help.
