### ISSUE TITLE
[v2][Android] Translucent option doesn't work

### ISSUE THREAD

**Issue by djnsu** [wix/react-native-navigation#4966]
### Issue Description

Greetings. Translucent options doesn't work in v2, but it works fine in v1. I've tried hard to experiment with different combination of options, but with no luck.

### Steps to Reproduce / Code Snippets / Screenshots

V2
```javascript
static options() {
    return {
      topBar: {
        elevation: 3, // 0 doesn't work either  
        drawBehind: true,
        background: {
          translucent: true,
          color: 'transparent',
        },
        backButton: {
          color: 'white',
        },
      },
    };
  }
```
White buttons are merging with white background of image and become completely invisible.

![image](https://user-images.githubusercontent.com/11135349/55874896-60e29a80-5b9c-11e9-97f1-66175b63a5bb.png)

exact same thing v1
```javascript
  static navigatorStyle = {
    drawUnderNavBar:   true,
    navBarTransparent: true,
    navBarTranslucent: true,
    navBarButtonColor: '#fff',
  };
```

It works perfect here

![image](https://user-images.githubusercontent.com/11135349/55874628-96d34f00-5b9b-11e9-9743-50c7c3f68fcc.png)

---
### Environment
* React Native Navigation version: 2.11.0
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): Android 
* Device info (Simulator/Device? OS version? Debug/Release?): Nougat 7.1.2 and Pie 9.0.1

**Comment by pribeh** [comment]
This is not supported for Android in V2, as per the documentation:

https://wix.github.io/react-native-navigation/#/docs/styling?id=android-specific-options

**Comment by djnsu** [comment]
I've taken it from here. Also translucent options could be founded in playground application.
https://wix.github.io/react-native-navigation/#/docs/options-migration?id=navbartranslucent

**Comment by djnsu** [comment]
The issue is still relevant.
