### ISSUE TITLE
[V2][iOS] popGesture blocking UI on setRoot

### ISSUE THREAD

**Issue by cinder92** [wix/react-native-navigation#4971]
### Issue Description

I have an app that only works with tabs, but first screen is a login screen, then i push to Home Screen.

### Steps to Reproduce / Code Snippets / Screenshots
```
Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      stack: {
        id: 'Egiving',
        children: [
          {
            component: {
              name: 'MainScreen',
              options: {
                topBar: {
                  visible: false,
                  animate: false,
                  drawBehind: true,
                },
                statusBar: {
                  style: 'light',
                  backgroundColor: colors.orange,
                },
                layout: {
                  orientation: ['portrait'],
                },
                popGesture: false
              },
            },
          },
        ],
      },
    },
  });
});
```

i can't put design because of privacy contract

---
### Environment
* React Native Navigation version: 2.1.3-patch.2-snapshot.62
* React Native version: 0.59.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Debug, Simulator, Real, both

**Comment by ItsNoHax** [comment]
This is fixed in 2.18.2
