### ISSUE TITLE
[V2][Android] Splash screen pops up twice

### ISSUE THREAD

**Issue by el-lsan** [wix/react-native-navigation#4974]
### Issue Description

I'm trying to show a loading screen (`app.loadingScreen` in code snippet) while my redux store is being rehydrated, then navigate to my main screen (`app.homeScreen` in code snippet)
But for some reason the splash screen is showing up between my loading component and main component.

### Code Snippets and Screenshots
```
Navigation.events().registerAppLaunchedListener(() => {
  bootstrap();
});

async function bootstrap() {
  // this function is registering all of my screens using Navigation.registerComponentWithRedux
  registerScreens(store, provider);

  // Navigate to loading screen as the first screen of the app
  Navigation.setRoot({
    root: {
      stack: {
        id: 'splash',
        children: [{
          component: {
            name: 'app.loadingScreen',
            options: {
              topBar: {
                drawBehind: true,
                visible: false,
                animate: false,
              },
            },
          },
        }],
      },
    },
  });

  // Loads resources and persist and rehydrate my redux store using redux-persist
  await Promise.all([loadIcons(), persistStore(store)]).then(() => {
   // Navigate to home screen once the store is rehydrated
    Navigation.setRoot({
      root: {
        stack: {
          id: 'root',
          children: [{
            component: {
              name: 'app.homeScreen',
            },
          }],
        },
      },
    });
  });  
}
```

On Android the splash screen is flashing before the second Navigation.setRoot

![RNN ANDROID](https://user-images.githubusercontent.com/1249548/55953998-d19dbb80-5c5d-11e9-9a41-ecba4f57061d.gif)

However on IOS everything is as expected:

![RNN IOS](https://user-images.githubusercontent.com/1249548/55954017-dcf0e700-5c5d-11e9-853a-b233df9e04c7.gif)
`

---
### Environment
* React Native Navigation version: `^2.16.0`
* React Native version: `^0.59.4`
* Platform(s) (iOS, Android, or both?): `Android`
* Device info (Simulator/Device? OS version? Debug/Release?): `All`

**Comment by el-lsan** [comment]
@ItsNoHax I believe this is more like a bug than a question!

**Comment by dvill03** [comment]
In android, this happens because a modal is opened before the SplashScreen.hide() condition is met.
Basically it shows SplashScreen -> Modal -> SplashScreen -> condition for closing modal -> HomeScreen
