### ISSUE TITLE
installation instructions for ios presumes AppDelegate code. mine is different

### ISSUE THREAD

**Issue by aaa-manuelhe** [wix/react-native-navigation#4977]
### Issue Description

I am attempting to install react-native-navigation and am following the instructions from https://wix.github.io/react-native-navigation/#/docs/Installing at the section for editing ios files. The instructions tell me to edit the AppDelegate.m. The instructions tell me to add this code and the end result should look like this.

> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions { ... }

and the end result should look like this

 

> #import "AppDelegate.h"
>  #import <React/RCTBundleURLProvider.h>
>  #import <React/RCTRootView.h>
>  #import <ReactNativeNavigation/ReactNativeNavigation.h>
> 
>  @implementation AppDelegate
> 
>  - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
>  {
>      NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
>      [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];
> 
>      return YES;
>  }
> 
>  @ end 

but my AppDelegate.m looks nothing like this? instead it looks like this...

> /**
>  * Copyright (c) Facebook, Inc. and its affiliates.
>  *
>  * This source code is licensed under the MIT license found in the
>  * LICENSE file in the root directory of this source tree.
>  */
> 
> 
> 
> #import "AppDelegate.h"
> 
> #import <React/RCTBridge.h>
> #import <React/RCTBundleURLProvider.h>
> #import <React/RCTRootView.h>
> 
> @implementation AppDelegate
> 
> - (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
>   sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
> {
>   return [RCTLinkingManager application:application openURL:url
>                       sourceApplication:sourceApplication annotation:annotation];
> }
> 
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>   RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
>   RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
>                                                    moduleName:@"planzu"
>                                             initialProperties:nil];
> 
>   rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
> 
>   self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
>   UIViewController *rootViewController = [UIViewController new];
>   rootViewController.view = rootView;
>   self.window.rootViewController = rootViewController;
>   [self.window makeKeyAndVisible];
>   return YES;
> }
> 
> - (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
> {
> #if DEBUG
>   return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
> #else
>   return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
> #endif
> }
> 
> `@end`

how should I proceed? Am I supposed to eliminate the top and bottom methods? or just replace the event call 'didFinishLaunchingWithOptions'?

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 2.17.0
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): IOS only
* Device info (Simulator/Device? OS version? Debug/Release?):iphone6 but the problem is with idE

**Comment by ronaldozanoni** [comment]
Hi @aaa-manuelhe 
Try to put the code below in your `didFinishLaunchingWithOptions` method:

`[ReactNativeNavigation bootstrap:[self sourceURLForBridge: bridge] launchOptions:launchOptions];`

So, the final code should be:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  
  [ReactNativeNavigation bootstrap:[self sourceURLForBridge: bridge] launchOptions:launchOptions];
  
  return YES;
}
```

See https://github.com/wix/react-native-navigation/issues/4853#issuecomment-472353418 for more info
