### ISSUE TITLE
Crash app when push screen on android

### ISSUE THREAD

**Issue by huuthinh245** [wix/react-native-navigation#4978]
### Issue Description

[ENTER DESCRIPTION HERE]
Sometimes I push screen 10 times more and my app crash. Test on android. 
I check logcat and see error  
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 4159 (mqt_js), pid 3852
### Steps to Reproduce / Code Snippets / Screenshots

function push screen
Navigation.push({
      screen: 'Detail_Sceen', options: {
        bottomTabs: {
          visible: false,
          animate: true,
          drawBehind: true,
        },
        layout: {
          backgroundColor: 'white'
        }
      }
})

My function pop in detail screen
Navigation.pop({ componentId: this.props.componentId });

[FILL THIS OUT]
When i click button to push to detail screen then i pop back. I do like this 10 times more. Suddenly I press push screen again my app stop working.
I open logcat throw error like 
<img width="1216" alt="Screen Shot 2019-04-12 at 9 41 56 AM" src="https://user-images.githubusercontent.com/27191029/56015725-37547b00-5d24-11e9-8362-fac193ddf5ee.png">

---
### Environment
* React Native Navigation version: 2.17.0
* React Native version: 0.59.3
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): debug android simulator

**Comment by jinshin1013** [comment]
You might need to update the issue with more detail than a line of error. How did you determine that this is react-native-navigation problem? Does it crash on specific screen? Is it reproducible? You need to put a little more detail than this man.

**Comment by huuthinh245** [comment]
problem like #4651. I change jsc-android and It seem no crash app

**Comment by SergeyBazhanov** [comment]
Same for me. RN 0.59.4. Android 6.0.1. App crashes with the same error after several push/pop operations

**Comment by nghiant96** [comment]
Same for me. RN 0.59.8. Android 9, Device xiaomi mi 9

**Comment by 8BallBomBom** [comment]
Experiencing the same issue on Android 8 and 9 with some Samsung devices.

**Comment by piuholo** [comment]
You might have better luck with "react-native": "0.59.10" as it contains the updated JSC version `245459.0.0`.

Updating RN fixed similar SIGSEGV crashes for my app.
