### ISSUE TITLE
mergeOptions with StackId not working in android

### ISSUE THREAD

**Issue by vemarav** [wix/react-native-navigation#4979]
Following snippet not working on android

Using RNN v2, RN v0.55.4

```js
Navigation.mergeOptions('StackID', { 
  bottomTab: { badge: '1'}
})
```

**Comment by vemarav** [comment]
Working

**Comment by aminosman** [comment]
@vemarav can you elaborate on what your mistake was? I am having trouble getting `mergeOptions` to work with tabs on android (setting badge and changing tabs)
