### ISSUE TITLE
Transparent tabBar

### ISSUE THREAD

**Issue by marineb** [wix/react-native-navigation#498]
### Issue Description

Hi, I'm trying to set the tabBar to transparent. I've followed the same convention as with the navBar, but it doesn't seem to work. The result is a black navigation. 

Specifically, I'd like to:
* Make the background of tabBar completely transparent (or being able to control its color: when I set a solid color, it gives me a lighter tone of that color)
* Remove the line above the tabs

### Steps to Reproduce / Code Snippets / Screenshots

* Setting the tabs' background to transparent doesn't work (result is black)
* Setting the tabs' background to a solid color doesn't work (result is a lighter shade of that color 
* Can't figure out how to remove the line above the tabs

```
tabsStyle: { 
    tabBarBackgroundColor: 'transparent',
    tabBarButtonColor: 'white',
    tabBarSelectedButtonColor: 'white',
    drawUnderTabBar: false,
    tabBarTransparent: true,
    tabBarTranslucent: true
}
```

<img width="375" alt="screen shot 2016-11-25 at 2 10 12 pm" src="https://cloud.githubusercontent.com/assets/234208/20634182/d6302ab8-b31b-11e6-91a1-38f513c93452.png">

---
### Environment
* React Native Navigation version: 2.0.0-experimental.142
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): iOS (didn't test Android)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and iPhone 6.

**Comment by grundmanise** [comment]
@guyca may you check this issue please.

**Comment by guyca** [comment]
@grundmanise Can you try adding your tab style parameters to `appStyle` (Only for android)
as mentioned in the docs https://github.com/wix/react-native-navigation/wiki/Styling-the-tab-bar#style-object-format

**Comment by grundmanise** [comment]
@guyca there is no option for a transparent tabbar on iOS?

**Comment by guyca** [comment]
`tabBarBackgroundColor: 'transparent'` didn't work on iOS?

**Comment by grundmanise** [comment]
No, it is not working.. Same default (white) tabbar.

**Comment by marineb** [comment]
Yes, it doesn't work. That's explained in the issue above ^^ @guyca. Thanks for looking into it!!

**Comment by jpoutrin** [comment]
Same issue. when using transparent color I get back background...

**Comment by HermantoTang** [comment]
Same issue on android, transparent color get white background

**Comment by kidequinox** [comment]
Having same issue on Android when using `tabBarComponent` option.

Some thoughts:

Is the tabbar in it's own fixed segment and Content beneath or above it is in it's own scrollable view and therefore does not pass into the tabbar space ? 

Can we control how tabBar floats so that it can overlap other screens?

Transparency works when calling a tabBar routes component from another component 
```
<View>
   <FeedTabs screenProps={this.props}/>
</View>
```

& with FeedTabs.js having:
```
tabBarOptions: {
  style: { backgroundColor: 'transparent' }
}
```
but since not overlapping content, it does not produce the desired effect.

**Comment by thechefchen** [comment]
This still repros. No matter if I put ```tabBarBackgroundColor: 'transparent'``` on `appStyle` or `tabsStyle`, it's still black for the background.

Is there a way to work around this?

**Comment by 1pocketaces1** [comment]
same issue here, I need the page background to extend down behind the tabBar so that the transparent tabBar shows through to the background of the page

**Comment by ialmoqren** [comment]
Is this still not possible?

**Comment by pribeh** [comment]
Sorry for asking, but is this possible now?

**Comment by ialmoqren** [comment]
@pribeh , I'm not a pro, but I loved having the ability to make any bottom bar I want, while still using the native library, so what I ended up doing is:
1. Hiding the bottomTabs: [v2 docs](https://wix.github.io/react-native-navigation/#/docs/options-migration?id=navbarhidden)
```js
bottomTabs: {
    visible: false,
    drawBehind: true,
},
bottomTab: {
    icon: require(<ANY ICON>) // even though they won't be shown, having no icons crashed my app on android
}
```

2. Creating my own tab bar component, something like this:
```js
import * as React from 'react';
import { Text, View, StyleSheet, Platform, Dimensions, TouchableOpacity, Image } from 'react-native';
import { Navigation } from 'react-native-navigation';

export default class App extends React.Component {

    changeToTab = (newIndex) => { 
       Navigation.mergeOptions('HomeTabs', {
          bottomTabs: {
              currentTabIndex: newIndex
          }
      });
    }

  render() {
    return (
            <View style={styles.tabBar}>

                <TouchableOpacity
                    activeOpacity={1}
                    onPress={()=>this.changeToTab(0)}
                    style={styles.iconView}>
                    <Image
                        source={require("./assets/snack-icon.png")}
                       style={[styles.image, { tintColor: this.props.visibleTab == 0 ? "black" : "#b1b2b3" }]}
                     />
                     <Text style={[styles.iconsText, { color: this.props.visibleTab == 0 ? "black" : "#b1b2b3" }]}>
                         Home
                      </Text>
                </TouchableOpacity>

                <TouchableOpacity
                    activeOpacity={1}
                    onPress={()=>this.changeToTab(1)}
                    style={styles.iconView}>
                    <Image
                        source={require("./assets/snack-icon.png")}
                       style={[styles.image, { tintColor: this.props.visibleTab == 1 ? "black" : "#b1b2b3" }]}
                     />
                     <Text style={[styles.iconsText, { color: this.props.visibleTab == 1 ? "black" : "#b1b2b3" }]}>
                         Explore
                      </Text>
                </TouchableOpacity>

                <TouchableOpacity
                    activeOpacity={1}
                    onPress={()=>this.changeToTab(2)}
                    style={styles.iconView}>
                    <Image
                        source={require("./assets/snack-icon.png")}
                       style={[styles.image, { tintColor: this.props.visibleTab == 2 ? "black" : "#b1b2b3" }]}
                     />
                     <Text style={[styles.iconsText, { color: this.props.visibleTab == 2 ? "black" : "#b1b2b3" }]}>
                         My Orders
                      </Text>
                </TouchableOpacity>

                <TouchableOpacity
                    activeOpacity={1}
                    onPress={()=>this.changeToTab(3)}
                    style={styles.iconView}>
                    <Image
                        source={require("./assets/snack-icon.png")}
                       style={[styles.image, { tintColor: this.props.visibleTab == 3 ? "black" : "#b1b2b3" }]}
                     />
                     <Text style={[styles.iconsText, { color: this.props.visibleTab == 3 ? "black" : "#b1b2b3" }]}>
                         My Account
                      </Text>
                </TouchableOpacity>

            </View>
    );
  }
}


const isTallIPhone = Platform.OS == "ios" && Dimensions.get('window').height >= 812

const styles = StyleSheet.create({
    tabBar: {
        position: 'absolute',
        bottom: 0,
        width: "100%",
        height: isTallIPhone ? 83 : 49, // The Height of the iOS tab
        backgroundColor: "#f9fafb",
        flexDirection: 'row',
        justifyContent: 'space-around',
        borderTopWidth: 0.3,
        borderTopColor: "#b1b2b3"
    },
        iconView: {
        width: "25%",
        height: "100%",
        alignItems: "center",
    },
    iconsText: {
        position: "absolute",
        bottom: isTallIPhone ? 32 : 3,
        fontSize: 10,
    },
    image: {
        position: "absolute",
        bottom: isTallIPhone ? 50 : 21,
        width:20,
        height:20
    }
});
```

And I need to pass visibleTab as a prop (0 for first tab, 1, for the second...)
```js
import * as React from 'react';
import { View } from 'react-native';
import BottomBar from "./BottomBar"

export default class App extends React.Component {

  render() {
    return (
          <View style={{ flex:1 }}>    
                //  ANYTHING CAN BE HERE

              <BottomBar visibleTab={0}/>
          </View>
    );
  }
}
```

I don't think this will affect the performance (a lot?) because after all I'm using the same native library,
Best of luck

**Comment by ialmoqren** [comment]
Unfortunately I haven't needed it, what I'm thinking about is adding a normal component inside each tab (might use absolute positioning) then improving its style until it looks like the native badge, and of course hide it if it's empty.
And I might need to manage their values from redux.

But after all, I'm not sure what issues you might face doing such logic, wish you all the best guys

**Comment by alimek** [comment]
> @pribeh , I'm not a pro, but I loved having the ability to make any bottom bar I want, while still using the native library, so what I ended up doing is:
> 
> 1. Hiding the bottomTabs: [v2 docs](https://wix.github.io/react-native-navigation/#/docs/options-migration?id=navbarhidden)
> 
> ```js
> bottomTabs: {
>     visible: false,
>     drawBehind: true,
> },
> bottomTab: {
>     icon: require(<ANY ICON>) // even though they won't be shown, having no icons crashed my app on android
> }
> ```
> 
> 1. Creating my own tab bar component, something like this:
> 
> ```js
> import * as React from 'react';
> import { Text, View, StyleSheet, Platform, Dimensions, TouchableOpacity, Image } from 'react-native';
> import { Navigation } from 'react-native-navigation';
> 
> export default class App extends React.Component {
> 
>     changeToTab = (newIndex) => { 
>        Navigation.mergeOptions('HomeTabs', {
>           bottomTabs: {
>               currentTabIndex: newIndex
>           }
>       });
>     }
> 
>   render() {
>     return (
>             <View style={styles.tabBar}>
> 
>                 <TouchableOpacity
>                     activeOpacity={1}
>                     onPress={()=>this.changeToTab(0)}
>                     style={styles.iconView}>
>                     <Image
>                         source={require("./assets/snack-icon.png")}
>                        style={[styles.image, { tintColor: this.props.visibleTab == 0 ? "black" : "#b1b2b3" }]}
>                      />
>                      <Text style={[styles.iconsText, { color: this.props.visibleTab == 0 ? "black" : "#b1b2b3" }]}>
>                          Home
>                       </Text>
>                 </TouchableOpacity>
> 
>                 <TouchableOpacity
>                     activeOpacity={1}
>                     onPress={()=>this.changeToTab(1)}
>                     style={styles.iconView}>
>                     <Image
>                         source={require("./assets/snack-icon.png")}
>                        style={[styles.image, { tintColor: this.props.visibleTab == 1 ? "black" : "#b1b2b3" }]}
>                      />
>                      <Text style={[styles.iconsText, { color: this.props.visibleTab == 1 ? "black" : "#b1b2b3" }]}>
>                          Explore
>                       </Text>
>                 </TouchableOpacity>
> 
>                 <TouchableOpacity
>                     activeOpacity={1}
>                     onPress={()=>this.changeToTab(2)}
>                     style={styles.iconView}>
>                     <Image
>                         source={require("./assets/snack-icon.png")}
>                        style={[styles.image, { tintColor: this.props.visibleTab == 2 ? "black" : "#b1b2b3" }]}
>                      />
>                      <Text style={[styles.iconsText, { color: this.props.visibleTab == 2 ? "black" : "#b1b2b3" }]}>
>                          My Orders
>                       </Text>
>                 </TouchableOpacity>
> 
>                 <TouchableOpacity
>                     activeOpacity={1}
>                     onPress={()=>this.changeToTab(3)}
>                     style={styles.iconView}>
>                     <Image
>                         source={require("./assets/snack-icon.png")}
>                        style={[styles.image, { tintColor: this.props.visibleTab == 3 ? "black" : "#b1b2b3" }]}
>                      />
>                      <Text style={[styles.iconsText, { color: this.props.visibleTab == 3 ? "black" : "#b1b2b3" }]}>
>                          My Account
>                       </Text>
>                 </TouchableOpacity>
> 
>             </View>
>     );
>   }
> }
> 
> 
> const isTallIPhone = Platform.OS == "ios" && Dimensions.get('window').height >= 812
> 
> const styles = StyleSheet.create({
>     tabBar: {
>         position: 'absolute',
>         bottom: 0,
>         width: "100%",
>         height: isTallIPhone ? 83 : 49, // The Height of the iOS tab
>         backgroundColor: "#f9fafb",
>         flexDirection: 'row',
>         justifyContent: 'space-around',
>         borderTopWidth: 0.3,
>         borderTopColor: "#b1b2b3"
>     },
>         iconView: {
>         width: "25%",
>         height: "100%",
>         alignItems: "center",
>     },
>     iconsText: {
>         position: "absolute",
>         bottom: isTallIPhone ? 32 : 3,
>         fontSize: 10,
>     },
>     image: {
>         position: "absolute",
>         bottom: isTallIPhone ? 50 : 21,
>         width:20,
>         height:20
>     }
> });
> ```
> 
> And I need to pass visibleTab as a prop (0 for first tab, 1, for the second...)
> 
> ```js
> import * as React from 'react';
> import { View } from 'react-native';
> import BottomBar from "./BottomBar"
> 
> export default class App extends React.Component {
> 
>   render() {
>     return (
>           <View style={{ flex:1 }}>    
>                 //  ANYTHING CAN BE HERE
> 
>               <BottomBar visibleTab={0}/>
>           </View>
>     );
>   }
> }
> ```
> 
> I don't think this will affect the performance (a lot?) because after all I'm using the same native library,
> Best of luck

so it means you have to wrap every screen in your `App` component  and it renders again everytime when you navigating between screens?

**Comment by ialmoqren** [comment]
@alimek oh no, sorry that was misleading,
Instead of `App` it should be `FirstTab`

So, in my [setRoot](https://wix.github.io/react-native-navigation/#/docs/top-level-api?id=setrootlayout) I put four screens in the [bottomTabs](https://wix.github.io/react-native-navigation/#/docs/layout-types?id=bottomtabs), then I included the `BottomBar` component in each one of them.

I will change my previous comment to be `FirstTab`

**Comment by pribeh** [comment]
@ialmoqren thanks for your suggestion again. We decided to use an overlay for our tabbabr. There are many caveats to doing this but ultimately was the most performant for what we are doing. If you decide to do an overlay you have to come up with businesses logic to hide and show the tabbar on each screen considering that an overlay shows on top of every screen. I don't recommend it unless you have to ensure that your tabbar doesn't re-render on each screen.

**Comment by donnes** [comment]
@ialmoqren thanks for your help!
Just one more question about your solution.

Where is the component id `HomeTabs` that you declared at:

``` jsx
Navigation.mergeOptions('HomeTabs', {
  bottomTabs: {
    currentTabIndex: newIndex
  }
});
```

**Comment by ialmoqren** [comment]
@donnes it's here, sorry that I haven't included it

```js
Navigation.setRoot({
    root: {
        center: {
            bottomTabs: {
                id: "HomeTabs",  // <---- HERE
                children: [
                     // this is an array of my bottom tabs tabs
                ]
            }
        },
    }
});
```

**Comment by rezasazesh** [comment]
@ialmoqren thanks for this, how do you keep the buttom tab stationary when you push a new screen in one of the bottom tab stacks?

**Comment by alisherakb** [comment]
@ialmoqren Hi Ibrahim, your solution works like charm. Thank you.
I'm trying to animate buttons using Animated from `react-native` and experiencing very strange behaviour. Animated gets incorrect values. 

<img width="532" alt="Screenshot 2019-08-26 at 13 57 43" src="https://user-images.githubusercontent.com/26904008/63686534-cdd49500-c80a-11e9-9e9e-f894d78259ac.png">
I
