### ISSUE TITLE
[v2][Android] Can't apply text to leftButtons

### ISSUE THREAD

**Issue by el-lsan** [wix/react-native-navigation#4980]
### Issue Description

I'm trying to customise the left button on top bar using a text but for some reason it doesn't work on Android. However if I replace `text: 'Test',` to an icon like `icon: loadedIcons.menu,` it works just fine.

### Steps to Reproduce / Code Snippets / Screenshots

```
static options() {
    return {
      topBar: {
        leftButtons: [
          {
            id: 'test',
            text: 'Test', // works with an icon but fails with text
            color: 'white',
          },
        ],
      },
    };
  }
```

---
### Environment
* React Native Navigation version: `^2.16.0`
* React Native version: `^0.59.4`
* Platform(s) (iOS, Android, or both?): `Android`
* Device info (Simulator/Device? OS version? Debug/Release?): `All`

**Comment by drunkel** [comment]
This appears to be their desired behaviour :( https://github.com/wix/react-native-navigation/issues/3982#issuecomment-422455420

It's frustrating to go through the migration from v1 to find out silly inconsistencies like this, and even more to have them be undocumented. I don't get it.
