### ISSUE TITLE
[v2][Android] Back button does not appear or work by default in modals

### ISSUE THREAD

**Issue by Alanz2223** [wix/react-native-navigation#4981]
### Issue Description

Using V2.13.1 on Android Pie. I am registering the modal screen with 

`Navigation.registerComponentWithRedux('Myapp.ModalCard', () => ProductCard,Provider, store);`

then from a button press I call 

`Navigation.showModal({
      stack: {
        children: [{
          component: {
            name: 'Myapp.ModalCard',
            passProps: {
              content: type
            },
            options: {
              topBar: {
                drawBehind: true,
                backButton: {
                  visible: true,
                  enabled : true
                },
                background : {
                  color: 'transparent',
                }
              }
            }
          }
        }]
      }
    });`

At first I assumed you wouldn't even need to pass the backButton object within the options but it seems you do since not doing so doesn't show the back button. Anyways, after I passed them the back button is showing but not working at all (modal not dismissed). So I placed a listener on both the modal and the calling screen but `navigationButtonPressed` is never called.

### Steps to Reproduce / Code Snippets / Screenshots

Have a single screen invoke a modal, the screen doesnt show the back button until options are passed and then it doesnt work.

---
### Environment
* React Native Navigation version: 2.13.1 
* React Native version: 0.59.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Pie, Debug

**Comment by jinshin1013** [comment]
I don't think this is a bug necessarily, Modals are supposed to function flexibly. In some Modal, you might want to use left button to dismiss whereas in other Modal you might want to swipe down to dismiss, automatically dismiss and etc. If you'd prefer your Modal to have a default back button, you can create a template Modal to call.

**Comment by Alanz2223** [comment]
@jinshin1013 I see, however just going off the docs there is no mention of creating a template modal.. and I do its an issue that even though the backbutton on the top bar has been made visible, it is still not functional

**Comment by jinshin1013** [comment]
You need to manually call, `Navigation.dismissModal(ModalComponentId)`

**Comment by Alanz2223** [comment]
@jinshin1013 I appreciate the help but I think you're not really understanding where I am coming from. I get that having a back button on a modal should be optional since it is a highly customizable component. What I am saying is that when the back button IS enabled by passing the options, the button appears but does not work. There is no way to know whether the button was pressed since `navigationButtonPressed ` is not fired, therefore you can't call `Navigation.dismissModal` without implementing YOUR own back button. Which defeats the purpose of the default button.

**Comment by jinshin1013** [comment]
The functionality of the backbutton is popping the current screen from the current stack. When you open a modal, it is not part of the stack you opened a modal from, thus backbutton does not dismiss the modal. And besides, as an UX designer I recommend you use different icon for dismissing the modal as the default backbutton does not imply dismissing the "modal", I hope this helps

**Comment by Alanz2223** [comment]
Thanks for explaining that.
