### ISSUE TITLE
SideMenu styling issue on IOS with react-native-navigation[V2]

### ISSUE THREAD

**Issue by rishabhSmartdata** [wix/react-native-navigation#4984]
IOS side menu styling issue, its working fine on android but its not behave good in IOS ,Please help me asap

 "react-native": "0.57.3",
"react-native-navigation": "^2.1.3",

![Screenshot 2019-04-15 at 11 45 45 AM](https://user-images.githubusercontent.com/46954033/56111187-bc35d380-5f74-11e9-9fff-3ba79085485d.png)
![Screenshot 2019-04-15 at 11 45 16 AM](https://user-images.githubusercontent.com/46954033/56111188-bc35d380-5f74-11e9-93a9-8fd624e3c7f8.png)

Navigation.js
 Navigation.setRoot({
    
  root: {
    sideMenu: {
      left: {
        component: {
          id: "sideDrawer",
          name: "SideMenu"
        }
      },
      center: {
        stack: {
          options: {},
          children: [{
            component: {
              name:"NewCard",
              options: {
                topBar: {
                  hideOnScroll: true,
                  title: {
                    text: "Homescreen",
                    color: "white"
                  },
                  leftButtons: [
                    {
                      id: "buttonOne",
                      icon: require("../assets/img/menu.png")
                    }
                  ],
                  background: {
                    color: "#05B8CC"
                  },
                  drawBehind: false,
                  visible: true,
                  animate: true
                },
              }
            }
          }]
        }
      }
    }
  }
  });
                                                     

---
### Environment
 "react-native": "0.57.3",
"react-native-navigation": "^2.1.3",

**Comment by ItsNoHax** [comment]
What's the problem? @rishabhSmartdata

**Comment by rishabhSmartdata** [comment]
Problem is like @ItsNoHax that i want sideMenu like android in ios, In ios the sidebar hide under the component(its not drawer like android, its slide the menu component) , I attached the images of both so please reviewed it then you got my point.I given the width for sidebar but it's also not working in ios.
Thanks

**Comment by fabware** [comment]
It is the shadows on the right, very annoying problem. We have hacked the native code to get rid of it, but it isn't working with the latest upgrade of react-native-navigation yesterday.

Is it possible to disable the shadow on the right of the iOS component?

**Comment by jeffy7** [comment]
> It is the shadows on the right, very annoying problem. We have hacked the native code to get rid of it, but it isn't working with the latest upgrade of react-native-navigation yesterday.
> 
> Is it possible to disable the shadow on the right of the iOS component?

same +1 ，Can you solve it?

**Comment by rishabhSmartdata** [comment]
![Screenshot 2019-05-02 at 9 59 37 AM](https://user-images.githubusercontent.com/46954033/57056606-2367bd80-6cc1-11e9-8ea3-4cb459cc98eb.png)
When i am giving the custom width to side menu then sideMenu screen is going to black

**Comment by fabware** [comment]
> > It is the shadows on the right, very annoying problem. We have hacked the native code to get rid of it, but it isn't working with the latest upgrade of react-native-navigation yesterday.
> > Is it possible to disable the shadow on the right of the iOS component?
> 
> same +1 ，Can you solve it?

Yes, with an updated hack on native code. 

It's unbelievable to see people constantly brought it up and getting ignored.

**Comment by uday007** [comment]
> When i am giving the custom width to side menu then sideMenu screen is going to black

@rishabhSmartdata Have you find any solution ?

**Comment by rishabhSmartdata** [comment]
@uday007 I was removed the custom width for the iphone device , I was handling this issue to increased the width of sidebar component and remove the width properties from navigation.js.

**Comment by uday007** [comment]
> @uday007 I was removed the custom width for the iphone device , I was handling this issue to increased the width of sidebar component and remove the width properties from navigation.js.

Can you demonstrate it with code snippet ??

**Comment by rishabhSmartdata** [comment]
Yeah sure @uday007 ,

here i was removed the width for iphone only left for Ipad
export const goHome = () =>{
  
  Navigation.setRoot({  
    root: {
      sideMenu: {
        left: {
         visible:true,
          component: {
            id: "sideDrawer",
            name: "SideMenu",
        
          },
        },
        center: {
          stack: {
            id:'CENTER_STACK',
            children: [{
              component: {
                name:"NewCard",
              },
            
            }]
          },
         
        },
        options: Platform.isPad? { 
          sideMenu: {
            left: {
              width: 500,           
            },
          }
        }:{}
       
        
      }
    }
    });
}

and i am defining the sidebar component width like
 width: Platform.OS == 'ios'? width*0.65:width*0.75,

**Comment by uday007** [comment]
> Yeah sure @uday007 ,
> 
> here i was removed the width for iphone only left for Ipad
> export const goHome = () =>{
> 
> Navigation.setRoot({
> root: {
> sideMenu: {
> left: {
> visible:true,
> component: {
> id: "sideDrawer",
> name: "SideMenu",
> 
> ```
>       },
>     },
>     center: {
>       stack: {
>         id:'CENTER_STACK',
>         children: [{
>           component: {
>             name:"NewCard",
>           },
>         
>         }]
>       },
>      
>     },
>     options: Platform.isPad? { 
>       sideMenu: {
>         left: {
>           width: 500,           
>         },
>       }
>     }:{}
>    
>     
>   }
> }
> });
> ```
> 
> }
> 
> and i am defining the sidebar component width like
> width: Platform.OS == 'ios'? width_0.65:width_0.75,

Thanks, I will try this in my project

**Comment by uday007** [comment]
> Yeah sure @uday007 ,
> 
> here i was removed the width for iphone only left for Ipad
> export const goHome = () =>{
> 
> Navigation.setRoot({
> root: {
> sideMenu: {
> left: {
> visible:true,
> component: {
> id: "sideDrawer",
> name: "SideMenu",
> 
> ```
>       },
>     },
>     center: {
>       stack: {
>         id:'CENTER_STACK',
>         children: [{
>           component: {
>             name:"NewCard",
>           },
>         
>         }]
>       },
>      
>     },
>     options: Platform.isPad? { 
>       sideMenu: {
>         left: {
>           width: 500,           
>         },
>       }
>     }:{}
>    
>     
>   }
> }
> });
> ```
> 
> }
> 
> and i am defining the sidebar component width like
> width: Platform.OS == 'ios'? width_0.65:width_0.75,

Hi @rishabhSmartdata ,

I have tried your code. But that is not work for my iPhone application. As custom width comes with black screen issue and custom width for side menu component need different width according to various device.

_getSideMenuWidth = () => {
    if (Platform.OS === 'ios') {
        if (Dimensions.get('window').height == 568) { // iPhone SE
            return Dimensions.get("window").width * 0.90
        } else if (Dimensions.get('window').height == 667) { // iPhone 6, iPhone 7, iPhone 8
            return Dimensions.get("window").width * 0.75
        } else if (Dimensions.get('window').height == 736) { // iPhone 6+, iPhone 7+, iPhone 8+
            return Dimensions.get("window").width * 0.70
        } else if (Dimensions.get('window').height == 812) { // iPhone Xs, iPhone X
            return Dimensions.get("window").width * 0.75
        } else if (Dimensions.get('window').height == 896) { // iPhone Xʀ, iPhone Xs Max
            return Dimensions.get("window").width * 0.70
        } else {
            return Dimensions.get("window").width
        }
    } else {
        return Dimensions.get("window").width
    }
};

**Comment by Kirill-Cherkalov** [comment]
still not fixes

**Comment by solshuffle** [comment]
this is still an issue

**Comment by maxto024** [comment]
I have this issue as well if i set the width

**Comment by snairsumith** [comment]
Still not fixed .Any updates?

**Comment by lo0oleta** [comment]
Still not fixed .Any updates?

**Comment by Findiglay** [comment]
Has anybody found a solution to this? We would like to use a sidemenu in the app, but the dark shadow does not really complement our design.

**Comment by TacticCoder** [comment]
??

**Comment by Desintegrator** [comment]
not fixed
