### ISSUE TITLE
Unable to build RNN with RN 0.59.4 on android

### ISSUE THREAD

**Issue by crushy26** [wix/react-native-navigation#4985]
### Issue Description

Getting the following error on react-native run-android

> Could not determine the dependencies of task ':app:preDebugBuild'.
> > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
>    > Could not resolve project :react-native-navigation.
>      Required by:
>          project :app
>       > Unable to find a matching variant of project :react-native-navigation:
>           - Variant 'reactNative57WixForkDebugApiElements':
>               - Required RNN.reactNativeVersion 'reactNative57_5' and found incompatible value 'reactNative57WixFork'.
>               - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
>               - Found com.android.build.api.attributes.VariantAttr 'reactNative57WixForkDebug' but wasn't required.
>               - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
>               - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
>           - Variant 'reactNative57WixForkDebugRuntimeElements':
>               - Required RNN.reactNativeVersion 'reactNative57_5' and found incompatible value 'reactNative57WixFork'.
>               - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
>               - Found com.android.build.api.attributes.VariantAttr 'reactNative57WixForkDebug' but wasn't required.
>               - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
>               - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
>           - Variant 'reactNative57WixForkReleaseApiElements':
>               - Required RNN.reactNativeVersion 'reactNative57_5' and found incompatible value 'reactNative57WixFork'.
>               - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
>               - Found com.android.build.api.attributes.VariantAttr 'reactNative57WixForkRelease' but wasn't required.
>               - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
>               - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
>           - Variant 'reactNative57WixForkReleaseRuntimeElements':
>               - Required RNN.reactNativeVersion 'reactNative57_5' and found incompatible value 'reactNative57WixFork'.
>               - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
>               - Found com.android.build.api.attributes.VariantAttr 'reactNative57WixForkRelease' but wasn't required.
>               - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
>               - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.

**android/build.gradle**

`subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                variantFilter { variant ->
                    def names = variant.flavors*.name
                    if (names.contains("reactNative51") || 
                        names.contains("reactNative55") || 
                        names.contains("reactNative56") || 
                        names.contains("reactNative57")) {
                        setIgnore(true)
                    }
                }
            }
        }
    }
}`

**android/app/build.gradle**

`defaultConfig {
        applicationId "com.highongames"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57_5"
        versionCode 1
        versionName "1.0"
    }`

### Environment
* React Native Navigation version: ^2.0.2641
* React Native version: 0.59.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device/8.0/Debug

**Comment by YourBoB** [comment]
Hey @crushy26 , is there a solution to fix this issue? I meet the same problem. Thanks

**Comment by crushy26** [comment]
Hi @yourBoB I actually didn't follow the instructions properly. Might have missed some steps. Install properly and it will work.
