### ISSUE TITLE
TopBar custom component button problem with transparent

### ISSUE THREAD

**Issue by rener172846** [wix/react-native-navigation#4996]
### Issue Description

I'm making an app which has avatar button on topbar. That avatar has circle style with `borderRadius: '50%'` and user's profile image will be loaded dynamically.
I have made that with custom component into leftButtons
```
      topBar: {
        title: {
          text: 'Notifications'
        },
        leftButtons: [
          {
            id: 'menu',
            component: {
              name: `CUSTOM_BUTTON_NAME`,
            }
          }
        ]
      }
```
However the navigation renders full rect image from the custom component, not rounded image.

![image](https://user-images.githubusercontent.com/18702659/56314972-27f08a00-6189-11e9-91e7-aaf8b734a473.png)

If borderRadius isn't correct solution for topBar buttons, please tell me the exact solution for round avatar effect on topBar

---
### Environment
* React Native Navigation version: 2.17.0
* React Native version: 0.59.4
* Platform(s) (iOS, Android, or both?): iOS (haven't tested on Android yet)
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone XR Simulator

**Comment by trialsNow** [comment]
@rener172846 
Can you help me with how you came up with the component for this? I have a similar requirement and trying to use react-native-elements Avatar component up on right button.. It errors out saying "Malformed Calls from JS: Field Sizes are different". Can you help me?

```
const avatarIcon = <Avatar rounded title="MD" />;
Navigation.setDefaultOptions({
      popGesture: true,
      statusBar: {
        backgroundColor: theme.colors.secondary,
        visible: false
      },
      layout: {
        backgroundColor: color.white,
        // topMargin: Navigation.constants().statusBarHeight,
        orientation: ['portrait', 'landscape']
      },
      topBar: {
        title: {
          color: color.white,
          fontFamily: 'System'
        },
        rightButtons: [
          {
            id: 'change',
            component: {
              name: avatarIcon
            }
          }
        ],
