### ISSUE TITLE
LeftButtons more margin than backButton

### ISSUE THREAD

**Issue by jfrolich** [wix/react-native-navigation#4999]
The left-margin on leftButton is more than the backButton when using a react component. So in the scenario of a slightly modified back button it's impossible to put it in the same location.

The use case is a component as back button label.

**Comment by jfrolich** [comment]
This issue is still present

**Comment by keremcubuk** [comment]
I have the same problem. Did you find any solution? @jfrolich 
And @guyca could you help us?
