### ISSUE TITLE
PassProps for ToggleDrawer

### ISSUE THREAD

**Issue by bfine9618** [wix/react-native-navigation#500]
### Issue Description

Is there a way to pass information to the toggled drawer?  

--
### Environment
* React Native Navigation version: 2.0
* React Native version: 0.36
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by Jaafar-abusair** [comment]
Just use this event

  _toggleSideMenu() {
        this
            .props
            .navigator
            .toggleDrawer({
                side: 'left', // the side of the drawer since you can have two, 'left' / 'right'
                animated: true, // does the toggle have transition animation or does it happen immediately (optional)
            });
  }

**Comment by bfine9618** [comment]
I am using the drawer as a menu for a given user. Therefore, i only want it accessible after a log in screen. i am having trouble completing this goal. Here is the log-in screen with the menu. You can see that i want to pass the users name to the menu. is there an easy way to do this? I tried your method above but am still receiving an error. 
<img width="1280" alt="screen shot 2016-11-27 at 12 55 34 pm" src="https://cloud.githubusercontent.com/assets/16210553/20650626/d2c46d0e-b4a0-11e6-8c4c-c190b5020776.png">

**Comment by Jaafar-abusair** [comment]
can you paste your side menu code.

**Comment by bfine9618** [comment]
import React, { Component, PropTypes } from 'react';
import {
  Text, Image, AsyncStorage,
  View, TouchableHighlight,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  AlertIOS
} from 'react-native';

export default class SideMenu extends Component {
  /*static propTypes = {
    user: PropTypes.object.isRequired,
    type: PropTypes.string.isRequired
  }*/

  constructor(props) {
    super(props);
  }

  /*componentDidMount() {
       AsyncStorage.getItem("user").then((value) => {
           this.setState({"user": value});
       }).done();
       AsyncStorage.getItem("type").then((value) => {
           this.setState({"type": value});
       }).done();
   }*/

  //TODO: make image user profile picture
  render() {
    return (
      <Image source={require('../images/menuBG.png')} style={[styles.container, {width: 290}]}>
      <View>
      <TouchableOpacity
        style={{alignItems: 'center'}}
        onPress={this.toProfile.bind(this)}
        underlayColor="#3498DB">
        <View style={{alignItems: 'center'}}>
        <Image source={require('../images/jeff.png')} style={styles.menuImg}/>
        <Text style={[styles.name, {fontSize:10}]}>this.state.user.fname} this.state.user.lname}</Text>
        <Text style={styles.h2}>Student @ UPenn</Text>
        </View>
      </TouchableOpacity>
      </View>
        <View style={{width: 287, marginTop:16}}>
          <TouchableOpacity style={styles.pressedButton} onPress={ this.onReplaceTab2Press.bind(this) }>
            <Text style={styles.pressedText}>&#xf023;    Home</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.button} onPress={ this.history.bind(this) }>
            <Text style={styles.text}>&#xf1da;    History</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.button} onPress={ this.settings.bind(this) }>
            <Text style={styles.text}>&#xf085;    Settings</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.button} onPress={ this.logout.bind(this) }>
            <Text style={styles.text}>&#xf235;    Log Out</Text>
          </TouchableOpacity>
        </View>
      </Image>
    );
  }
  onReplaceTab2Press() {
    this._toggleDrawer();
    // push/pop navigator actions affect the navigation stack of the current screen only.
    // since side menu actions are normally directed at sibling tabs, push/pop will
    // not help us. the recommended alternative is to use deep links for this purpose
    this.props.navigator.handleDeepLink({
      link: "tab2/example.PushedScreen"
    });
  }

  history() {
    this._toggleDrawer();
    this.props.navigator.showModal({
      title: "History",
      screen: "example.HistoryModal",
      navigatorStyle: {
        navBarBackgroundColor: '#3498db',
        navBarTextColor: '#ffffff',
        navBarSubtitleTextColor: '#ffffff',
        navBarButtonColor: '#ffffff',
        statusBarTextColorScheme: 'light',
      }
    });
  }

  toProfile() {
    this._toggleDrawer();
    this.props.navigator.showModal({
      title: "Profile",
      screen: "example.profile",
      navigatorStyle: {
        navBarBackgroundColor: '#3498db',
        navBarTextColor: '#ffffff',
        navBarSubtitleTextColor: '#ffffff',
        navBarButtonColor: '#ffffff',
        statusBarTextColorScheme: 'light',
      },
      passProps: {
        user: this.props.user,
        type: this.props.type,
      }
    });
    }

  settings() {
    this._toggleDrawer();
    this.props.navigator.showModal({
      title: "Settings",
      screen: "example.settings",
      navigatorStyle: {
        navBarBackgroundColor: '#3498db',
        navBarTextColor: '#ffffff',
        navBarSubtitleTextColor: '#ffffff',
        navBarButtonColor: '#ffffff',
        statusBarTextColorScheme: 'light',
      }
    });
  }

  onModalPress() {
    this._toggleDrawer();
    this.props.navigator.showModal({
      title: "Modal",
      screen: "example.ModalScreen"
    });
  }

  _toggleDrawer() {
    this.props.navigator.toggleDrawer({
      to: 'closed',
      side: 'left',
      animated: true
    });
  }

  logout() {
    this.props.navigator.handleDeepLink({
      link: "tab2/example.welcome"
    });
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    width: 267,
    right: 10,
  },
  title: {
    textAlign: 'center',
    fontSize: 18,
    marginBottom: 10,
    marginTop:10,
    fontWeight: '500'
  },
  pressedButton: {
    borderLeftWidth: 12,
    borderLeftColor: 'white',
    height: 60,
    paddingLeft: 21,
    backgroundColor: '#157ABD',
    justifyContent: 'center'
  },
  pressedText: {
    fontFamily: 'FontAwesome',
    fontSize: 18,
    color: 'white'
  },
  button: {
    height: 60,
    paddingLeft: 33,
    backgroundColor: 'transparent',
    justifyContent: 'center'
  },
  text: {
    fontFamily: 'FontAwesome',
    fontSize: 18,
    color: '#90CAF9'
  },
  menuImg: {
    width: 94,
    height: 94,
    borderRadius: 47,
    marginTop: 53,
    alignSelf: 'center'
  },
  name: {
    fontFamily: 'Montserrat-Regular',
    fontSize: 18,
    color: "#ffffff",
    marginTop: 13,
    backgroundColor: 'transparent'
  },
  h2: {
    fontFamily: 'Montserrat-Light',
    fontSize: 16,
    color: "#90caf9",
    marginTop: 8,
    backgroundColor: 'transparent'
  }
});

**Comment by bfine9618** [comment]
I have tried using AsyncStorage and passprops, but neither work

**Comment by Jaafar-abusair** [comment]
you need to initialize the state in the constructor which you don't

**Comment by bfine9618** [comment]
THANK YOU
