### ISSUE TITLE
Increasing Tappable Area of Top Bar Buttons

### ISSUE THREAD

**Issue by calendee** [wix/react-native-navigation#5000]
### Issue Description

When using custom icons for left/right buttons, the tappable area is significantly reduced as compared to native iOS icons.

Is there any way to improve the tappable area of custom buttons to extend to the edge of the screen and more vertically?

### Steps to Reproduce / Code Snippets / Screenshots

Example of the tappable area of native iOS icons created using :

```
rightButtons: [
  {
    id: "cart",
    systemItem: "add"
    color: "gray"
  }
]
```

![rnn-system-icon](https://user-images.githubusercontent.com/57374/56357007-051da000-61a0-11e9-9a52-848af1ae6c35.png)

Versus the tappable area of custom icons created using:

```
rightButtons: [
  {
    id: "cart",
    icon: images.shopping_cart,
    color: "gray"
  }
]
```

![rnn-png-icon](https://user-images.githubusercontent.com/57374/56357018-09e25400-61a0-11e9-8644-fea694f3abd6.png)

### Environment
* React Native Navigation version: 2.17.0
* React Native version: 0.59.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X 12.2 simulator in Xcode 10.1

**Comment by calendee** [comment]
When using text for the buttons, they also have the full tappable area that native options do:

```
leftButtons: [
  {
    id: CLOSE_ID,
    enabled: true,
    color: "black",
    text: "Cart",
  },
],
```

![rnn-text](https://user-images.githubusercontent.com/57374/56357828-6e9eae00-61a2-11e9-9bb6-de394526e126.png)

**Comment by calendee** [comment]
I'm finding that if I make this change in ``, I get a more tappable area.  However, I'm still not able to get the button to be tappable to the edge of the device.

```
-(instancetype)init:(NSString*)buttonId withIcon:(UIImage*)iconImage {
	UIButton* button = [[UIButton alloc] init];
	[button addTarget:self action:@selector(onButtonPressed) forControlEvents:UIControlEventTouchUpInside];
	[button setImage:iconImage forState:UIControlStateNormal];
// Increase the rectangle to increase tappable area
	[button setFrame:CGRectMake(0, 0, iconImage.size.width + 40, iconImage.size.height + 20)];
	self = [super initWithCustomView:button];
	self.buttonId = buttonId;
// Force the icon to align to the left of the rectangle
	button.contentHorizontalAlignment = UIControlContentHorizontalAlignmentLeft;
	return self;
}
```

**Comment by ItsNoHax** [comment]
I went ahead and assigned @yogevbd because this is something we are also running into.

**Comment by thinklinux** [comment]
Yeap I'm running into this one too. If you have guys have some suggestions where I can start from I can take a look.

**Comment by GioLogist** [comment]
+1 for this!

**Comment by minhloi** [comment]
This issue can be resolved by using the built-in ```initWithImage``` instead of ```initWithCustomView``` . If you use ```initWithImage```, you will have the tappable area like the built-in system icons so it covers the edge area.

Any reason for using initWithCustomView to set button icon?

Here is the fix: 
In ```RNNUIBarButtonItem.m```
```
-(instancetype)init:(NSString*)buttonId withIcon:(UIImage*)iconImage {

        // ORGINAL:
        //UIButton* button = [[UIButton alloc] init];
	//[button addTarget:self action:@selector(onButtonPressed) forControlEvents:UIControlEventTouchUpInside];
	//[button setImage:iconImage forState:UIControlStateNormal];
	//[button setFrame:CGRectMake(0, 0, iconImage.size.width, iconImage.size.height)];
	//self = [super initWithCustomView:button];
	//self.buttonId = buttonId;

         // FIX:
  	self = [super initWithImage:iconImage style:UIBarButtonItemStylePlain target:self action:@selector(onButtonPressed)];
  	self.buttonId = buttonId;

	return self;
}
```

**Comment by AlexDM0** [comment]
The same goes for custom components, not just icons. I hope this can be addressed :) Keep up the good work guys!

**Comment by prgpascal** [comment]
Same issue here :/
I hope this will be resolved soon.

**Comment by bneigher** [comment]
backButton has a good hitSlop, would be cool to be able to set negative insets or something for left/right buttons

**Comment by bneigher** [comment]
@minhloi your suggestion is really good.  Should be changed in the source for sure

**Comment by brsaylor2** [comment]
The solution from @minhloi worked for me as well.

**Comment by danilobuerger** [comment]
PR at #6482
