### ISSUE TITLE
Custom top bar layout is broken on iOS on latest release 2.17.0

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#5003]
### Issue Description

I am using a custom top bar for my app. I have been using `v2.13.1` and the layout of the top bar was fine as shown below:

![Screenshot 2019-04-18 at 6 03 43 PM](https://user-images.githubusercontent.com/7475133/56361306-a76f6f00-6204-11e9-9804-e1c044e01ba7.png)

I updated the version to `v2.17.0` and without any other changes, the top bar looks like this. I tried many different things in styling to make it look right but I couldn't get it to the same as `v2.13.1`

![Screenshot 2019-04-18 at 6 03 30 PM](https://user-images.githubusercontent.com/7475133/56361218-66775a80-6204-11e9-85c3-e5dec344cea8.png)

Below is the code for my top bar component.

```javascript
      <View
        style={{
          flexDirection: 'row',
          justifyContent: 'space-between',
          alignItems: 'center',
          backgroundColor: 'transparent'
        }}>
        <Icon
          name="notifications"
          type="material"
          color={colorThemes.Default.primary}
          onPress={this.onViewNotifications}
          size={24}
          containerStyle={styles.iconContainerStyle}
        />
        <TouchableOpacity
          style={{
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
            marginVertical: 10
          }}
          onPress={this.onViewProfile}>
          <ContactAvatar
            size={'medium'}
            imageUri={this.props.profileImageThumbnailPath}
            name={name}
          />
        </TouchableOpacity>
        <Icon
          name="add"
          type="material"
          color={colorThemes.Default.primary}
          onPress={this.onNew}
          size={24}
          containerStyle={styles.iconContainerStyle}
        />
      </View>
```

It is just a simple view with three views laid out in a single row.

### Steps to Reproduce / Code Snippets / Screenshots

Use custom top bar component with three views in a single row.

---
### Environment
* React Native Navigation version: 2.17.0
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by Collin3** [comment]
I think I'm having a related issue. I upgraded from version `v2.16.0` to `v2.17.0` and now my top bar buttons are not showing up. I have a right button component defined and set with `setDefaultOptions`, but that doesn't seem to be working anymore. Now I have to define static options or do a `mergeOptions` to redefine that icon in my top bar.

@guyca any thoughts?

**Comment by Collin3** [comment]
I just went through all of the snapshots and found that it was introduced in `v2.16.0-snapshot.270`

**Comment by aminosman** [comment]
For us text no longer shows in the custom nav component and our `TouchableOpacity` is no longer triggered. I tried just having the nav bar component render text and it just loads blank

**Comment by guyca** [comment]
@aminosman Can you please push a branch with a reproduction?

**Comment by guyca** [comment]
@Collin3 Thanks for taking the time to track down the faulty commit
