### ISSUE TITLE
alignment 'fill' doesn't give the whole top bar area to the custom component on Android

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#5004]
### Issue Description

I am using custom top bar for my app. I am using `alignment: fill` to give the complete top bar area to the component. It appears fine on iOS as shown below:

![Screenshot 2019-04-18 at 6 03 43 PM](https://user-images.githubusercontent.com/7475133/56364400-12707400-620c-11e9-9878-826f7cd64f63.png)

But on Android, it doesn't get the complete top bar area and only appears on the left side of the top bar as shown below.

![Screenshot 2019-04-18 at 6 32 07 PM](https://user-images.githubusercontent.com/7475133/56364410-18665500-620c-11e9-8124-f69fc523333b.png)

Below is the code for the custom top bar

```js
        <View
        style={{
          flexDirection: 'row',
          justifyContent: 'space-between',
          alignItems: 'center',
          backgroundColor: 'transparent'
        }}>
        <Icon
          name="notifications"
          type="material"
          color={colorThemes.Default.primary}
          onPress={this.onViewNotifications}
          size={24}
          containerStyle={styles.iconContainerStyle}
        />
        <TouchableOpacity
          style={{
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
            padding: 10
          }}
          onPress={this.onViewProfile}>
          <ContactAvatar
            size={'medium'}
            imageUri={this.props.profileImageThumbnailPath}
            name={name}
          />
        </TouchableOpacity>
        <Icon
          name="add"
          type="material"
          color={colorThemes.Default.primary}
          onPress={this.onNewFuturegram}
          size={24}
          containerStyle={styles.iconContainerStyle}
        />
      </View>
```

If I add a padding of `115` to the `TouchableOpacity`, I am able to provide more area to the top bar and have it take up the whole of top bar as shown below:

![Screenshot 2019-04-18 at 6 33 12 PM](https://user-images.githubusercontent.com/7475133/56364439-29af6180-620c-11e9-9c65-cec272bbf8cc.png)

### Steps to Reproduce / Code Snippets / Screenshots

Use a custom top bar as described above on Android. The custom top bar component is a simple view with three views placed in one row.

---
### Environment
* React Native Navigation version: 2.13.1
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by exentrich** [comment]
Confirm that `alignment: fill` is not works correctly on Android. The problem is root view with `flex: 1` do not automatically occupy all available space, so I need to manually hardcode width for this view.

But on iOS prior to 2.17.0:
- `alignment: fill` and `flex: 1` works good
- but on device orientation change size of view is not updated

Today I'm upgraded to RNN: 2.17.0 (+React Native version is 0.59.5) and on iOS behaviour of custom title component now same as on Android (no automatic fill space).

Please fix this problem!

**Comment by dozoisch** [comment]
Seems like https://github.com/wix/react-native-navigation/commit/9f439dabd8fabc151bb96fbb04fa34bfe2b469d8 (2.18.4) fixed it on iOS.

**Comment by dozoisch** [comment]
Not stale on android

**Comment by dozoisch** [comment]
Not stale

**Comment by dozoisch** [comment]
💃 stale dance

**Comment by dozoisch** [comment]
Not stale

**Comment by dozoisch** [comment]
Not state as far as I know

**Comment by dozoisch** [comment]
not stale

**Comment by dozoisch** [comment]
not stale

**Comment by dozoisch** [comment]
not stale
