### ISSUE TITLE
File 'RNNModalAnimation.m' not found

### ISSUE THREAD

**Issue by Oz-on** [wix/react-native-navigation#5005]
### Issue Description
After upgrading a react-native-navigation module, ios app crashes because of error:
**Build input file cannot be found: '[project_path]/node_modules/react-native-navigation/lib/ios/RNNModalAnimation.m'**

After downgrading module to, for example version 2.12.0 everything is working correctly. I searched for that file in node_module in both cases and I could only find this file in the older version of module.

### Steps to Reproduce / Code Snippets / Screenshots
1. Upgrade react-native-navigation to version  2.17.0
2. Build an application using Xcode

---
### Environment
* React Native Navigation version: **2.17.0**
* React Native version: **0.58.6**
* Platform(s) (iOS, Android, or both?): **iOS**
* Device info (Simulator/Device? OS version? Debug/Release?): **iPhone 8  iOSv12.2**

**Comment by sorin-f-wiredelta** [comment]
Environment
React Native Navigation version: 2.16.0
React Native version: 0.57.8
Platforms: iOS;
Device info: iPhoneX simulator

I am experiencing the same problem now. 
I would like to mention that this happens when building with the new build system in Xcode. I just stumbled upon this issue when I wanted to try the new build system, because it works with the legacy system.

**Comment by sorin-f-wiredelta** [comment]
I just tried to copy the missing files from an older version of RNN (2.12.0) into 2.16.0, but of course there are other errors that pop up so it's a no go.

**Comment by yogevbd** [comment]
I think cleaning the build cache folder will help in this case.. delete both `ios/build` and `ios/DerivedData`

**Comment by guyca** [comment]
Closing, to my understanding this isn't a bug

**Comment by sorin-f-wiredelta** [comment]
no it's not, as @yogevbd said, I just cleaned the build folder and manually deleted the derived data directory.
