### ISSUE TITLE
.pop() custom animation ends with full view of screen being removed

### ISSUE THREAD

**Issue by MossP** [wix/react-native-navigation#5007]
### Issue Description

When applying a custom animation Up/Down for Push/Pop the push animation works well but the pop animation runs then, when the screen should get removed from the stack, it momentarily becomes visible again, full opacity in the previous location. i.e. it shows again when it shouldn't.

### Steps to Reproduce / Code Snippets / Screenshots
Push any screen with the following options then pop back out of it. The popped screen will slide down then appear back at the top before disappearing again.
```js
options: {
  animations: {
    push: {
      content: {
        y: {
          from: 2000,
          to: 0,
          duration: 400,
          interpolation: 'decelerate',
          startDelay: 100,
        },
      },
    },
    pop: {
      content: {
        y: {
          from: 0,
          to: 2000,
          duration: 400,
          interpolation: 'accelerate',
          startDelay: 0,
        },
      },
    },
  },
}
```

---
### Environment
* React Native Navigation version: ~2.8.0~ *2.17.0* *correction*
* React Native version: 57.8 (haven't tested others)
* Platform(s) (iOS, Android, or both?): ~only tested on iOS~ *iOS only*
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone6 and iPhone XS 12.1.4

**Comment by guyca** [comment]
Hey @MossP, I see you're using a very old RNN version, please upgrade to latest version and report if the issue still exists.

**Comment by MossP** [comment]
@guyca Apologies. A correction, I am using v2.17.0 (Incorrect version number given above).

**Comment by bear-junior** [comment]
+1 I have the same issue

**Comment by bear-junior** [comment]
@guyca only iOS issue, still visible in the newest version of RNN

**Comment by exentrich** [comment]
Also have the same issue

**Comment by MossP** [comment]
@guyca I've updated the initial Bug Report now based on other's feedback. Is there anything that you need me to supply.

**Comment by markhomoki** [comment]
I'm having the same issue only on iOS. Did anyone find a solution for this?

**Comment by MossP** [comment]
@markhomoki I haven't tried again as I was only trying out the plugin to get to know it.

**Comment by cyberraven** [comment]
I am experiencing a similar issue, but in my case I am using a modal. When I try to use custom animation for dismissModal, app gets stuck on an empty white screen after the animation finishes. Animation itself runs as it should and the whole problem goes away if I use a default animation.
On the other hand, I haven't had any issues with showModal animation.

**Comment by zzzkasper-1995** [comment]
"react": "^16.6.3",
    "react-native": "^0.58.6",
    "react-native-navigation": "^2.21.0"

Problem still exists

**Comment by YasminBeatriz** [comment]
```
"react": "16.9.0",
"react-native": "0.61.2",
"react-navigation": "^3.11.0"
```
Facing the same issue
