### ISSUE TITLE
Is there any way to use lifecycle method in functional component?

### ISSUE THREAD

**Issue by oxy88** [wix/react-native-navigation#5018]
### Issue Description

Looking for ways to use lifecycle method in funtional component

### Steps to Reproduce / Code Snippets / Screenshots

```
function SomeComponent() {
   componentDidAppear() {
  }
}
```
Obviously this doesn't work

So I'm using event listener with useEffect but this listens all event
```
function SomeComponent() {
  useEffect(() => {
    const someListener = Navigation.events().listener()
  
    return () {
      someListener.remove()
    }
  })
}
```

---
### Environment
* React Native Navigation version: 2.13.2
* React Native version: 0.59.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all devices

**Comment by jinshin1013** [comment]
You can find the related doc [here](http://wix.github.io/react-native-navigation/#/docs/events?id=componentdidappear)

**Comment by retyui** [comment]
You can simulate `this` instance:

```
const Test = ({ componentId }) => {
  useEffect(() => {
    return Navigation.events().bindComponent({
      props: { componentId },
      componentDidAppear() {
        console.log(' --- componentDidAppear');
      },
    });
  }, [componentId]);
};
```


https://github.com/wix/react-native-navigation/blob/0e888fb65a70343949386f0d6f9f59b03e7b93b7/lib/src/events/ComponentEventsObserver.ts#L43-L56

**Comment by jinshin1013** [comment]
@retyui I believe you won't have to dispose `bindComponent` function as it gets automatically unregistered on unmount. As much as I like your way, I think it's little more explicit to use the following:

```
useEffect(() => {
  const componentAppearListener = Navigation.events(). registerComponentDidAppearListener(({ componentId: compId }) => {
    if (componentId === compId) {
      console.log('did appear')
    }
  })

  return () => componentAppearListener.remove()
}, [])
```

**Comment by retyui** [comment]
@jinshin1013 
That's a good point!
I forgot about clearing the event listener on unmount
