### ISSUE TITLE
Question: keeping a reference to a popped screen, and re-pushing it back later on?

### ISSUE THREAD

**Issue by oferRounds** [wix/react-native-navigation#5020]
### Issue Description

Question: is it possible with RNN to keep a reference to a popped screen, and later on re-push the same instance using the reference? 

### Environment
* React Native Navigation version: v1 or v2 
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by guyca** [comment]
Hey, not possible.
A very hacky way of keeping a component mounted, but not visible, is to use an Overlay.
You could show a screen with an Overlay, animate it outside of screen bounds while keeping the Overlay mounted. Later on you can animate it back into place.

**Comment by oferRounds** [comment]
Thank you!
The hacky way, if I understand right, is not a good option for my case, as I want to use the default native push/pop behavior

**Comment by guyca** [comment]
May I ask, what's your use case?

**Comment by oferRounds** [comment]
We have a part on our app where we use a WebView which is pushed when tapping an item on the list, and we don’t want to re-load, if it had already been shown once.

On the non-react-native world it possible (while release it if needed, when getting a memory warning), so was looking for the same behaviour

**Comment by guyca** [comment]
gotcha. I think your best option is to create and manage the WebView natively and expose it with a `ViewGroupManager`. This way you'll be able to create once, keep a reference to it and reuse the existing WebView when needed.

**Comment by oferRounds** [comment]
Thanks again! Can I ask what is `ViewGroupManager`? find only some references to it, but can’t find it on the RN documentation

**Comment by guyca** [comment]
I meant that you can create a custom view where you could create and handle the WebView
https://facebook.github.io/react-native/docs/native-components-ios
https://facebook.github.io/react-native/docs/native-components-android

**Comment by oferRounds** [comment]
But I will still need to push a new RN component instance each time I push right?

i.e., I will be pushing a new instance every-time using RNN, **but** my RN component will hold a reference to the same webview member (which for example, will be referenced somewhere else in the app)? That’s the idea?

**Comment by guyca** [comment]
Exactly.

**Comment by oferRounds** [comment]
Great, thank you very much for the replies here! 
LOVE React-Native-Navigation BTW!
