### ISSUE TITLE
V1 - Execution failed for task ':react-native-navigation:verifyReleaseResources'

### ISSUE THREAD

**Issue by gagan144** [wix/react-native-navigation#5025]
### Issue Description
I am using wix/react-native-navigation - V1 and while compiling android app for release following error is encountered
> Task :react-native-navigation:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':react-native-navigation:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  ..\path\to\project\node_modules\react-native-navigation\android\app\build\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  ..\path\to\project\node_modules\react-native-navigation\android\app\build\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  ..\path\to\project\node_modules\react-native-navigation\android\app\build\intermediates\res\merged\release\values\values.xml:3083: error: resource android:attr/fontVariationSettings not found.
  ..\path\to\project\node_modules\react-native-navigation\android\app\build\intermediates\res\merged\release\values\values.xml:3084: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

Content of /android/app/build.gradle:

dependencies {
    implementation project(':rn-fetch-blob')
    implementation project(':react-native-apk')
    implementation project(':react-native-device-info')
    implementation project(':@react-native-community_async-storage')
    implementation project(':react-native-webview')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-vector-icons')
    implementation 'com.android.support:design:27.1.0'
    implementation project(':react-native-navigation')  // From node_modules
}

Any idea how to resolve this error?
Thanks!

### Environment
* React Native Navigation version: 1.1.493 (v1)
* React Native version: 0.59.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by maulikdhameliya** [comment]
I am also facing this issue

**Comment by jneuendorf** [comment]
Any updates from anyone on how to solve this? Or maybe some stackoverflow question?

**Comment by jneuendorf** [comment]
FYI: I solved the issue by basically doing this: https://stackoverflow.com/a/52613927/6928824 (this question is directly related to RNN: https://stackoverflow.com/a/56468756/6928824 but I am no `gradle` expert so I had to hard-code the values).

This is my `android/build.grald`:

```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    // See https://github.com/zo0r/react-native-push-notification#android-manual-installation
    // and https://github.com/zo0r/react-native-push-notification/issues/794#issuecomment-407695414
    // and https://github.com/zo0r/react-native-push-notification/issues/796#issuecomment-410801969
    ext {
        googlePlayServicesVersion = "16.1.0" // default: "+"
        firebaseVersion = "18.0.0" // default: "+", must be < 19 because >= 19 uses androidX, to find versions see https://firebase.google.com/support/release-notes/android

        // Other settings
        compileSdkVersion = 28 // default: 28
        buildToolsVersion = "28.0.3" // default: "28.0.3"
        targetSdkVersion = 26 // default: 28
        minSdkVersion = 26 // default 16
        supportLibVersion = "28.0.0" // default: 28.0.0
    }
    repositories {
        google() // Must be before jcenter. See https://rnfirebase.io/docs/v5.x.x/installation/android#Update-Gradle
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1' // default 3.4.0

        // https://rnfirebase.io/docs/v5.x.x/installation/android#2.-Setup-google-services.json
        classpath 'com.google.gms:google-services:4.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            // Local Maven repo containing AARs with JSC library built for Android
            url "$rootDir/../node_modules/jsc-android/dist"
        }
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion "28.0.3"
            }
        }
    }
}
```
