### ISSUE TITLE
Android hardware back button is causing problems

### ISSUE THREAD

**Issue by Frekansapp** [wix/react-native-navigation#5027]
### Issue Description

If I switch between the tabs on my bottomtabs page and press the hardware back button, the application closes instead of opening the previous tab and restarts when I open it.
If I show overlay on the bottom of the tab page, the hardware back button will exit the application  instead of closing the overlay
### Code Sample
[Example](https://github.com/Frekansapp/RNNBack-button-issue)
### Screenshots

<img src="https://media.giphy.com/media/UTRw3YB6SNFHfdYdzZ/giphy.gif" width="240">

---
### Environment
* React Native Navigation version:2.18.1
* React Native version: 0.59.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): LG G4 5.0 Debug

**Comment by retyui** [comment]
Plesse read [docs/app-launch](https://wix.github.io/react-native-navigation/#/docs/app-launch ) first

**Comment by Frekansapp** [comment]
> 
> 
> Please read [docs/app-launch](https://wix.github.io/react-native-navigation/#/docs/app-launch) first

I read it but could not solve this problem. I downloaded the [hekla ](https://github.com/birkir/hekla) application and it has the same behavior. The logic in [this line](https://github.com/wix/react-native-navigation/blob/40a01599bf785238bce4616472f2b9dcbbfb2c66/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/navigator/Navigator.java#L99) needs to change but I failed.

**Comment by retyui** [comment]
You need only restore a previous scene 

When you reopen  your app again will be called `registerAppLaunchedListener`

**Comment by Frekansapp** [comment]
I guess I couldn't tell the problem exactly. When I switch between tabs, I need to open the previous tab when I press android hardware back button. Like YouTube or Instagram etc. but it takes the application to the background.  If I'm doing something wrong, is a hekla or this [repo](https://github.com/atoami/react-native-navigation-redux-starter-kit) faulty example beacuse i'am using exactly same code block what they use. This examples provide by this repo.

**Comment by Frekansapp** [comment]
Here is a [example ](https://github.com/Frekansapp/RNNBack-button-issue) code to reproduce

**Comment by varungupta85** [comment]
The bottom tabs are separate navigation stacks in RNN. So, when you press the back button and you are at the root of the tab, it will close the app. If you push a screen one a tab and then press the back button, it will pop the screen and not close the app. If you want the behavior you are looking for, you will probably need to define your own bottom tab bar.

**Comment by Frekansapp** [comment]
> 
> 
> The bottom tabs are separate navigation stacks in RNN. So, when you press the back button and you are at the root of the tab, it will close the app. If you push a screen one a tab and then press the back button, it will pop the screen and not close the app. If you want the behavior you are looking for, you will probably need to define your own bottom tab bar.

I understood this, but the behavior I want is native behavior of Android. It seems strange to me that it does not display native android behavior in a library that has native navigation even in its name. I can count on dozens of applications that show the behavior I'm talking about. I would appreciate if you consider this in future updates.

**Comment by ItsNoHax** [comment]
I'm closing this issue because what you are seeing IS native behaviour. Don't forget you can use ReactNative's BackHandler to customise the logic yourself.

**Comment by vietnguyen402** [comment]
I have the same problem, can you tell me how to fix it? @ItsNoHax
