### ISSUE TITLE
Log Out from sideMenu

### ISSUE THREAD

**Issue by bfine9618** [wix/react-native-navigation#503]
### Issue Description

I am having trouble resetting to my login screen from the sign in menu. In addition, when i do it from a modal screen, the navigation buttons no longer work after a second login. Any suggestions?

### Steps to Reproduce / Code Snippets / Screenshots
I have tried:
`logout() {
    this.props.navigator.handleDeepLink({
      link: "example.welcome"
    });
  }`
AND 
this.props.navigator.resetTo

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): iOS (ideally both though)
* Device info (Simulator/Device? OS version? Debug/Release?): sim iOS 10.1

**Comment by Jaafar-abusair** [comment]
have you tried this.props.navigator.startSingleScreenApp()?

**Comment by bfine9618** [comment]
Works perfectly! thank you
