### ISSUE TITLE
Unable to run e2e android test

### ISSUE THREAD

**Issue by kelvin-dev** [wix/react-native-navigation#5031]
npm run test-e2e-android doesn't work, please help investigate !

Our fork get stuck on the latest source code in master branch ...

![image](https://user-images.githubusercontent.com/19224355/56762355-e20b7580-67c9-11e9-8347-30a34a2bb39d.png)

**Comment by Kirill-Cherkalov** [comment]
try runing this command in another terminal (Bash for example)

**Comment by guyca** [comment]
I'm pretty sure our scripts are broken on Windows. You're welcome to PR a fix 👍
