### ISSUE TITLE
[v2][Android] BackButton is too small

### ISSUE THREAD

**Issue by congnguyen91** [wix/react-native-navigation#5033]
### Issue Description

When I override icon backButton for Android. It's too small with transparent touch.
```
backButton: {
  icon: require(../back.png')
}
```
I also try to supply 1x, 2x, 3x (24x24, 48x48, 72x72) png files but It still has the bug.

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: 2.18.2
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device/Android 9/Rease& Debug
![Screenshot_20190426-143030_KuuHo Admin](https://user-images.githubusercontent.com/18322684/56791414-37c73880-6831-11e9-956a-15e5944b6d42.png)
<img width="180" alt="Screen Shot 2019-04-26 at 2 40 59 PM" src="https://user-images.githubusercontent.com/18322684/56791482-5c231500-6831-11e9-902d-6eaf97a7c0a8.png">

**Comment by congnguyen91** [comment]
+1 new?

**Comment by congnguyen91** [comment]
Hello @guyca  Should I add any information for this to be accepted like a bug? 
Thanks :) I don't want to customized back button component.

**Comment by thinklinux** [comment]
You either have to use svg or supply every android size like in a native app. 1x, 2x and 3x does not work for some reason and I don't know if it is a react-native or react-native-navigation problem.

**Comment by congnguyen91** [comment]
So should I use svg or png image for back button on topBar?
@thinklinux :) Have you met the same issue like me :)
