### ISSUE TITLE
[V2] showModal animation broken

### ISSUE THREAD

**Issue by Dexwell** [wix/react-native-navigation#5036]
### Issue Description

On the latest version, modals on iOS instantly show, while the dismiss animation _does_ work. 

### Steps to Reproduce / Code Snippets / Screenshots

```js                                                      
Navigation.showModal({
  component: {
    name: 'example.Screen'
  }
});
```        

---
### Environment
* React Native Navigation version: 2.18.1
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): iOS confirmed

**Comment by guyca** [comment]
Hey @Dexwell , were you able to reproduce this in the playground app?

**Comment by Dexwell** [comment]
I can't get the Playground app to build—is there a guide to this?

**Comment by 3luyka** [comment]
same here :/

**Comment by guyca** [comment]
I found one way to reproduce it:

1. Show modal
2. Show another modal
Second modal isn't animated 🤷‍♂

**Comment by cjroth** [comment]
I'm having the same issue.

**Comment by 3luyka** [comment]
I've replaced 
```
Navigation.showModal({
  component: {
    name: 'example.Screen'
  }
});
```
with 
```
Navigation.showModal({
  stack: {
    children: [
      {
        component: {
          name: 'example.Screen',
        },
      },
    ],
  },
});
```
and animation works as expected. (might be helpful)

**Comment by Dexwell** [comment]
Can confirm @3luyka's solution works; would be great if both ways worked and not every `showModal` call will have to be updated though.
