### ISSUE TITLE
[V2][IOS] Is it possible to remove stretch effect of SideMenu in IOS?

### ISSUE THREAD

**Issue by SergeyBazhanov** [wix/react-native-navigation#5037]
### Issue Description

Hello. Thank you for this awesome package.
I want to ask if it's possible to disable the stretch effect in IOS for SideMenu.
I'm talking about effect when SideMenu is stretched horizontally a bit: when it's already opened and you try to move it over the maximum width

Thanks in advance
---
### Environment
* React Native Navigation version: 2.16.0-snapshot.265
* React Native version: 0.59.4
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Any IOS Device

**Comment by ItsNoHax** [comment]
Yes, it's written in the documentation: https://wix.github.io/react-native-navigation/#/docs/styling?id=ios-specific-options

```
shouldStretchDrawer: false
```
