### ISSUE TITLE
Topbar rightButtons / leftButton flipping sides when popping back

### ISSUE THREAD

**Issue by m00gl3** [wix/react-native-navigation#5042]
### Issue Description

With the latest React Native version (0.59.5) and RNN 2.18.2 **ONLY** on iOS - the topBar buttons are reversed when running this scenario:

* using RTL with:

`if (Constants.Localization.localize === "he-IL")
	I18nManager.forceRTL(true);`

1) Topbar icons look good.
2) Pushing another view with Navigation.push(...)
3) Going back from THAT screen to my main screen with Navigation.pop, the topbar icons are REVERSED.

This happens only once when I return from the 2nd view. 
Repeating the process (opening a new view and popping back) doesn't change the icons once again (they stay reversed).

                topBar: {
                    leftButtons: [
                        {
                          id: 'sideMenu',
                          icon: iconsMap['ios-menu'],
                          color: Constants.Color.ToolbarIcon,
                        }
                      ],
                      rightButtons: [
                          {
                              id: 'refreshAgendaScreen',
                              icon: iconsMap['ios-refresh'],
                              color: Constants.Color.ToolbarIcon,
                          }                          
                        ], 
                }

![Screen Shot 2019-04-29 at 11 58 34](https://user-images.githubusercontent.com/1267581/56885854-376baf00-6a76-11e9-9270-b7784d9847b4.png)
First run. Looks good.

![Screen Shot 2019-04-29 at 11 56 56](https://user-images.githubusercontent.com/1267581/56885865-42264400-6a76-11e9-950a-4c828c6e14be.png)
Popping back from 2nd view, icons are reversed.

---
### Environment
* React Native Navigation version: 2.18.2
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): iOS only
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 6s, Debug

**Comment by snairsumith** [comment]
@m00gl3 did you find any solution regarding this? 
I have same issue .
