### ISSUE TITLE
[V2] dismissAllModals doesn't await

### ISSUE THREAD

**Issue by veraldo** [wix/react-native-navigation#5045]
### Issue Description

Similarly to #3733, it's not possible to await dismissAllModals() then trying to use showModal() after it

### Steps to Reproduce / Code Snippets / Screenshots

```
await Navigation.dismissAllModals(); 
Navigation.showModal('modal');
```

---
### Environment
* React Native Navigation version: 2.8
* React Native version: 0.57
* Platform(s) (iOS, Android, or both?): tested on iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 11.4 (Simulator)

**Comment by danilobuerger** [comment]
Fixed by #6671
