### ISSUE TITLE
[V2][Android] StatusBar `drawBehind` can not be set to false after being set to true

### ISSUE THREAD

**Issue by aminosman** [wix/react-native-navigation#5047]
### Issue Description

When you have a tab based app with different `statusBar` with different `drawBehind` settings each tab does not respect its setting. In my setup we have `statusBar` (and `topBar`) hidden with `drawBehind` set to false and the next tab. On the next tab over both are visible and `drawBehind` is false however the `topBar` is being drawn under the status bar. It seems like the issue is once you set `drawBehind: true` on the status bar, setting it to false does not take. 

This seems to be the same issue seen in these issues
https://github.com/wix/react-native-navigation/issues/3729
https://github.com/wix/react-native-navigation/issues/4857

### Environment
* React Native Navigation version: 2.18.3
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by adeelraza** [comment]
+1

**Comment by aminosman** [comment]
Created a PR with a fix 
https://github.com/wix/react-native-navigation/pull/5052

**Comment by cesarm16** [comment]
+1

**Comment by LRNZ09** [comment]
I am having the same issue.

**Comment by LRNZ09** [comment]
Still an issue.
