### ISSUE TITLE
[Android] BottomTabs animate: false is not working

### ISSUE THREAD

**Issue by NweThazin** [wix/react-native-navigation#5049]
### Issue Description

BottomTabs animate is not working.

I try to disable animation on android bottom tabs so added

  Navigation.setDefaultOptions({
    bottomTabs: {
      backgroundColor: SRXColor.DarkBlue,
      animate: false
    }
});

which is not working. still showing animation. Can someone help me to disable animation on android bottom tabs? thanks 

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version:"^2.13.1",
* React Native version:"^0.58.4"
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by ADCrouch** [comment]
I'm also having the same issue, did you find a solution?

**Comment by karlmarxlopez** [comment]
I'm also having this issue.

**Comment by oferRounds** [comment]
Hi @guyca, is there any way to disable the animation when switching tabs on Android? Also, the elevation the tab icon gets when selected

**Comment by oferRounds** [comment]
Oh, found a way from this answer:
https://github.com/wix/react-native-navigation/issues/4481#issuecomment-450583294
