### ISSUE TITLE
[v2][iOS] Unable to push ViewController from Native code

### ISSUE THREAD

**Issue by bensont1** [wix/react-native-navigation#5057]
### Issue Description

I'm trying to integrate Frechchat SDK to React Native. Its simply a chat UI SDK. It pushes a UIViewController from native code over the React Native app. Since the last RNN update, I have gotten the following error when trying to invoke a method to display the UI.

Any ideas?

### Steps to Reproduce / Code Snippets / Screenshots

```
2019-05-01 23:59:56.240855-0700 MyApp[76069:2329763] -[ConversationOptions mergeInOptions:]: unrecognized selector sent to instance 0x600002902200
2019-05-01 23:59:56.276 [fatal][tid:main] Exception '-[ConversationOptions mergeInOptions:]: unrecognized selector sent to instance 0x600002902200' was thrown while invoking showConversations on target RNFreshchatSdk with params (
)
callstack: (
	0   CoreFoundation                      0x000000011376d6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001124ebac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011378bab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000113772443 ___forwarding___ + 1443
	4   CoreFoundation                      0x0000000113774238 _CF_forwarding_prep_0 + 120
	5   MyApp                               0x000000010d8ac8b5 -[UIViewController(LayoutProtocol) resolveOptions] + 149
	6   MyApp                               0x000000010d8ad43e -[UIViewController(LayoutProtocol) willMoveToParentViewController:] + 110
	7   UIKitCore                           0x000000011efdeda6 -[UIViewController _addChildViewController:performHierarchyCheck:notifyWillMove:] + 614
	8   UIKitCore                           0x000000011ef421ba -[UINavigationController pushViewController:transition:forceImmediate:] + 1136
	9   UIKitCore                           0x000000011ef41bac -[UINavigationController pushViewController:animated:] + 681
	10  UIKitCore                           0x000000011ef2261d -[UINavigationController initWithRootViewController:] + 123
	11  MyApp                               0x000000010d7123bb +[FCControllerUtils presentOn:option:] + 141
	12  MyApp                               0x000000010d794cd2 -[Freshchat showConversations:withOptions:] + 227
	13  MyApp                               0x000000010d794a85 -[Freshchat showConversations:] + 133
	14  MyApp                               0x000000010dee43f4 -[RNFreshchatSdk showConversations] + 196
	15  CoreFoundation                      0x00000001137744cc __invoking___ + 140
	16  CoreFoundation                      0x0000000113771a45 -[NSInvocation invoke] + 325
	17  CoreFoundation                      0x0000000113771e96 -[NSInvocation invokeWithTarget:] + 54
	18  MyApp                               0x000000010d9eb96a -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2810
	19  MyApp                               0x000000010da88776 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 790
	20  MyApp                               0x000000010da88283 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 131
	21  MyApp                               0x000000010da881f9 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
	22  libdispatch.dylib                   0x00000001182c5d7f _dispatch_call_block_and_release + 12
	23  libdispatch.dylib                   0x00000001182c6db5 _dispatch_client_callout + 8
	24  libdispatch.dylib                   0x00000001182d4080 _dispatch_main_queue_callback_4CF + 1540
	25  CoreFoundation                      0x00000001136d48a9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	26  CoreFoundation                      0x00000001136cef56 __CFRunLoopRun + 2310
	27  CoreFoundation                      0x00000001136ce302 CFRunLoopRunSpecific + 626
	28  GraphicsServices                    0x0000000117ecc2fe GSEventRunModal + 65
	29  UIKitCore                           0x000000011f5dcba2 UIApplicationMain + 140
	30  MyApp                               0x000000010d6f5d60 main + 112
	31  libdyld.dylib                       0x000000011833b541 start + 1
)
2019-05-01 23:59:56.276610-0700 MyApp[76069:2329763] Exception '-[ConversationOptions mergeInOptions:]: unrecognized selector sent to instance 0x600002902200' was thrown while invoking showConversations on target RNFreshchatSdk with params (
)
callstack: (
	0   CoreFoundation                      0x000000011376d6fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001124ebac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011378bab4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000113772443 ___forwarding___ + 1443
	4   CoreFoundation                      0x0000000113774238 _CF_forwarding_prep_0 + 120
	5   MyApp                               0x000000010d8ac8b5 -[UIViewController(LayoutProtocol) resolveOptions] + 149
	6   MyApp                               0x000000010d8ad43e -[UIViewController(LayoutProtocol) willMoveToParentViewController:] + 110
	7   UIKitCore                           0x000000011efdeda6 -[UIViewController _addChildViewController:performHierarchyCheck:notifyWillMove:] + 614
	8   UIKitCore                           0x000000011ef421ba -[UINavigationController pushViewController:transition:forceImmediate:] + 1136
	9   UIKitCore                           0x000000011ef41bac -[UINavigationController pushViewController:animated:] + 681
	10  UIKitCore                           0x000000011ef2261d -[UINavigationController initWithRootViewController:] + 123
	11  MyApp                               0x000000010d7123bb +[FCControllerUtils presentOn:option:] + 141
	12  MyApp                               0x000000010d794cd2 -[Freshchat showConversations:withOptions:] + 227
	13  MyApp                               0x000000010d794a85 -[Freshchat showConversations:] + 133
	14  MyApp                               0x000000010dee43f4 -[RNFreshchatSdk showConversations] + 196
	15  CoreFoundation                      0x00000001137744cc __invoking___ + 140
	16  CoreFoundation                      0x0000000113771a45 -[NSInvocation invoke] + 325
	17  CoreFoundation                      0x0000000113771e96 -[NSInvocation invokeWithTarget:] + 54
	18  MyApp                               0x000000010d9eb96a -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2810
	19  MyApp                               0x000000010da88776 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 790
	20  MyApp                               0x000000010da88283 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 131
	21  MyApp                               0x000000010da881f9 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
	22  libdispatch.dylib                   0x00000001182c5d7f _dispatch_call_block_and_release + 12
	23  libdispatch.dylib                   0x00000001182c6db5 _dispatch_client_callout + 8
	24  libdispatch.dylib                   0x00000001182d4080 _dispatch_main_queue_callback_4CF + 1540
	25  CoreFoundation                      0x00000001136d48a9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	26  CoreFoundation                      0x00000001136cef56 __CFRunLoopRun + 2310
	27  CoreFoundation                      0x00000001136ce302 CFRunLoopRunSpecific + 626
	28  GraphicsServices                    0x0000000117ecc2fe GSEventRunModal + 65
	29  UIKitCore                           0x000000011f5dcba2 UIApplicationMain + 140
	30  MyApp                               0x000000010d6f5d60 main + 112
	31  libdyld.dylib                       0x000000011833b541 start + 1
)

```
---
### Environment
* React Native Navigation version: 2.18.4
* React Native version: 0.59.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both, all.

**Comment by bensont1** [comment]
I can confirm it works on `RNN 2.16.0`, but broken after...

**Comment by edritech93** [comment]
same for me

**Comment by eldooon** [comment]
How were you able to push it previously from a react screen to native? I don't see any documentation for this. Can I see your code snippet to get an idea?

**Comment by username199327** [comment]
`2019-05-10 11:26:10.850405+0700 Project[326:25128] -[ConversationOptions mergeInOptions:]: unrecognized selector sent to instance 0x282141e00
2019-05-10 11:26:10.851029+0700 Project[326:25128] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ConversationOptions mergeInOptions:]: unrecognized selector sent to instance 0x282141e00'`

Hi i also got the same issue as @bensont1 does anyone here knows at least how to temporarily fix this issue, other than downgrading the RNN version if possible?

**Comment by nialexsan** [comment]
I have the same issue with [instabug](https://github.com/Instabug/Instabug-React-Native) on `feature request`

`RNN 2.16.0` works fine though

**Comment by margaridaDinis** [comment]
This issue is still happening in **2.18.5**. Are there any workarounds or plans to fix it anytime soon?

**Comment by nialexsan** [comment]
this is still an issue in **3.1.1**

**Comment by bensont1** [comment]
Yep issue still exists in 3.1.X, with RN 0.60.5.
Have not found a workaround for this.

I have tried the following but still get the same `unrecognized selector` error.

1. Get the presented view controller using:
```
RCTPresentedViewController();
```

2. Get the ViewController using RNN, where "appMain" is the componentId in JS code:
```
UIViewController *visibleVC = [ReactNativeNavigation findViewController:@"appMain"];
```

**Comment by markmoomoo** [comment]
@bensont1 May I ask where did you find the documentation for the class level method of
`findViewController`
how did you switched from react native layer to Native Layer with it?
Appreciated

**Comment by markmoomoo** [comment]
> Yep issue still exists in 3.1.X, with RN 0.60.5.
> Have not found a workaround for this.
> 
> I have tried the following but still get the same `unrecognized selector` error.
> 
> 1. Get the presented view controller using:
> 
> ```
> RCTPresentedViewController();
> ```
> 
> 1. Get the ViewController using RNN, where "appMain" is the componentId in JS code:
> 
> ```
> UIViewController *visibleVC = [ReactNativeNavigation findViewController:@"appMain"];
> ```

@bensont1 , did you got it work again?
I am at RNN version 4.8.1
"Settings" is the componentId in my JS code
UIViewController *visibleVC = [ReactNativeNavigation findViewController:@"Settings"];
when I debug it, visibleVC is nil in xcode.

**Comment by markmoomoo** [comment]
Yep issue still exists in 4.8.1 with RN 0.60.6
`Exception 'threading violation: expected the main thread' was thrown while invoking openNative on target Utils with params (
    "totalbrain.Profile"
)
callstack: (
 0   CoreFoundation                      0x000000019a536a5c 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 1227356
 1   libobjc.A.dylib                     0x000000019a25dfa4 objc_exception_throw + 56
 2   CoreFoundation                      0x000000019a438e88 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 188040
 3   Foundation                          0x000000019a86e654 7B1733B1-74C9-3A33-8A58-853B0A029826 + 554580
 4   FrontBoardServices                  0x000000019f6b2a4c BA369656-AFEF-391A-A426-EED114A72432 + 350796
 5   FrontBoardServices                  0x000000019f667ec8 BA369656-AFEF-391A-A426-EED114A72432 + 44744
 6   FrontBoardServices                  0x000000019f668130 BA369656-AFEF-391A-A426-EED114A72432 + 45360
 7   FrontBoardServices                  0x000000019f668038 BA369656-AFEF-391A-A426-EED114A72432 + 45112
 8   UIKitCore                           0x000000019e14f31c D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 5858076
 9   UIKitCore                           0x000000019e5b1108 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 10453256
 10  MyBrainSolutions                    0x00000001025811d0 -[ViewController startCameraCapture] + 1496
 11  MyBrainSolutions                    0x0000000102580be8 -[ViewController viewDidLoad] + 1756
 12  UIKitCore                           0x000000019df9d448 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 4080712
 13  UIKitCore                           0x000000019dfa1f58 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 4099928
 14  UIKitCore                           0x000000019dfa2360 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 4100960
 15  UIKitCore                           0x000000019dfb7a98 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 4188824
 16  UIKitCore                           0x000000019dfb08a4 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 4159652
 17  UIKitCore                           0x000000019dfb22b8 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 4166328
 18  UIKitCore                           0x000000019dfb4794 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 4175764
 19  UIKitCore                           0x000000019dfb4c90 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 4177040
 20  UIKitCore                           0x000000019dfb46e4 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 4175588
 21  UIKitCore                           0x000000019dfb494c D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 4176204
 22  MyBrainSolutions                    0x0000000102583d74 -[Utils openNative:] + 284
 23  CoreFoundation                      0x000000019a53cc20 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 1252384
 24  CoreFoundation                      0x000000019a40cd30 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 7472
 25  CoreFoundation                      0x000000019a40d908 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 10504
 26  MyBrainSolutions                    0x00000001027633a4 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1896
 27  MyBrainSolutions                    0x0000000102766da0 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 660
 28  MyBrainSolutions                    0x0000000102766914 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 144
 29  MyBrainSolutions                    0x0000000102766878 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
 30  libdispatch.dylib                   0x0000000103d3d7fc _dispatch_call_block_and_release + 24
 31  libdispatch.dylib                   0x0000000103d3ebd8 _dispatch_client_callout + 16
 32  libdispatch.dylib                   0x0000000103d45b48 _dispatch_lane_serial_drain + 744
 33  libdispatch.dylib                   0x0000000103d466e4 _dispatch_lane_invoke + 448
 34  libdispatch.dylib                   0x0000000103d51adc _dispatch_workloop_worker_thread + 1324
 35  libsystem_pthread.dylib             0x000000019a252b88 _pthread_wqthread + 276
 36  libsystem_pthread.dylib             0x000000019a255760 start_wqthread + 8
)

RCTFatal
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread`

Get the ViewController using RNN, where "totalbrain.profile" is the componentId in JS code:
UIViewController *visibleVC = [ReactNativeNavigation findViewController:@"totalbrain.profile"];
