### ISSUE TITLE
[v2] interceptTouchOutside false not working on Android

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#5058]
### Issue Description

interceptTouchOutside false not working on Android. I can't press though overlay on Android.

### Steps to Reproduce / Code Snippets / Screenshots

```js                                                      
Navigation.showOverlay({
    component: {
      name: "overlay",
      options: {
        layout: {
          backgroundColor: "transparent"
        },
        overlay: {
          interceptTouchOutside: false
        }
      }
    }
  });
 ```
---
### Environment
* React Native Navigation version: 2.18.4
* React Native version: 0.59.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): BOTH

**Comment by LRNZ09** [comment]
Still happens on `2.20.2`

**Comment by fjmorant** [comment]
Still happens on `2.21.0` explained here https://github.com/wix/react-native-navigation/issues/4953#issuecomment-498163338

**Comment by eightyfive** [comment]
This should be closed as duplicate in favor of https://github.com/wix/react-native-navigation/issues/4953

**Comment by kolosov507** [comment]
I got the same error after upgrading React Native to 0.59.3.
At 0.57.8 everything works fine.
