### ISSUE TITLE
[V2] Android tablet bottom tabs are tiny and centered

### ISSUE THREAD

**Issue by LoganArnett** [wix/react-native-navigation#5059]
### Issue Description
Trying to use bottom tabs in an application that uses both phones and tablets and the bottom tabs show at the overall width of a phone on a tablet. They do not take up the entire width of the device. The bar itself does but the icons are all small and centered

### Steps to Reproduce / Code Snippets / Screenshots
Use a basic bottom tab setup and launch on a tablet sized device instead of a phone.

This is the result:
![image](https://user-images.githubusercontent.com/8780547/57080649-f1eef200-6cc0-11e9-92c1-e7a74a53bcb6.png)

---
### Environment
* React Native Navigation version: 2.18.4
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android, havent tested iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel tablet emulator and hardware

**Comment by oxyii** [comment]
@LoganArnett This is not a bug I think. See [Material Design docs](https://material.io/design/components/bottom-navigation.html#placement) (Landscape view)

**Comment by LoganArnett** [comment]
That looks awful on large devices, that is odd. I have seen on the component that is being used here that they are supposedly trying to add in better support for Tablets or the option to extend so I have also opened an issue there, I will close this for now

**Comment by Manikanta-GEP** [comment]
Any ideas on how to make them occupy full width.
