### ISSUE TITLE
[IOS] popToRoot mergeOptions is not working

### ISSUE THREAD

**Issue by shuuha** [wix/react-native-navigation#5062]
### Issue Description

When I am using popToRoot with some mergeOptions it is not working on IOS, though everything is ok on Android.

### Steps to Reproduce / Code Snippets / Screenshots

Just use popToRoot from any stack and pass mergeOptions, I am using it like:

```Navigation.popToRoot(this.props.componentid, { bottomTabs: { currentTabIndex: 2 }})```
---
### Environment
* React Native Navigation version: @latest
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device, iphone 6

**Comment by shuuha** [comment]
anybody else having same issues on IOS?

**Comment by shuuha** [comment]
Still not working.

**Comment by svenlombaert** [comment]
Navigation.mergeOptions is working to change the active tab, but indeed as stated above, the popToRoot doesn't take this into account

**Comment by bneigher** [comment]
This is still a bug with v3 (alpha-11)
