### ISSUE TITLE
[iOS] Navigation push to Native View?

### ISSUE THREAD

**Issue by eldooon** [wix/react-native-navigation#5069]
### Issue Description

I have RNN setup already. I'm currently incorporating a storyboard file from a pod. I can present the storyboard from native iOS code using:

`self.window?.rootViewController?.present(podVC!, animated: true, completion: nil)`

but I'm unable to use:

`self.window?.rootViewController?.navigationController?.pushViewController(chatbotVC!, animated: true)`

NavigationController is coming back as nil. The screen I am using the NativeModule from currently has a Navigation header.

---
### Environment
* React Native Navigation version: 2.5.2
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): iOS 10
* Device info (Simulator/Device? OS version? Debug/Release?): iOS Simulator

**Comment by edritech93** [comment]
same problem for me

**Comment by eldooon** [comment]
I was able to work around this issue by using this: 
https://pspdfkit.com/blog/2017/native-view-controllers-and-react-native/

I basically embed my native View Controller into a UIView, and exported that to use as a component in a new screen.
