### ISSUE TITLE
Track tab change

### ISSUE THREAD

**Issue by brunocramos** [wix/react-native-navigation#507]
Is there any way to know the current displaying tab or/and a sort of tab change vent?
My case: I need to track all the screens the user navigates to, but all tab screens are rendered the moment the navigation component is mounted. Is there a sort of "onTabSwitch" event or any other way I can approach this?

Thanks
---
### Environment
* React Native Navigation version: Last
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Both

**Comment by guyca** [comment]
Hey @brunocramos It's being worked on now, will be available when v2.0 is released sometime in December
