### ISSUE TITLE
Not restoring state on Android when backgrounding and foregrounding and Activity is destroyed.

### ISSUE THREAD

**Issue by joshuapinter** [wix/react-native-navigation#5071]
### Current Behavior

On Android, an Activity can be destroyed by the operating system in the background to recover memory, etc. Android handles this by saving and restoring the state. Works great, actually. However, with React Native Navigation, the entire stack is wiped out when this happens.

![May-05-2019 09-44-43](https://user-images.githubusercontent.com/180819/57196610-b734c600-6f1b-11e9-9d0d-2e159a539e8f.gif)

### Expected Behavior

It should restore the state, similar to what happens when you have "Don't keep activities" set to false. (See above GIF for comparison.)

### How to reproduce

To easily test this: 

1. Ensure "Don't keep activities" is set to true in Developer Settings. 

2. Navigate a couple screens deep. 

3. Background app.

4. Foreground app. 

5. You're back at the root screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.4
| react-native     | 0.59.5
| node             | v10.15.3
| npm or yarn      | 6.4.1

**Comment by guyca** [comment]
Hey there,
Android actually doesn't handle Activity restore and it's left for the developers to restore the activity, usually with the [onSaveInstanceState api](https://developer.android.com/guide/components/activities/activity-lifecycle#saras).

When the Activity is destroyed, the Application usually isn't. As long as the Application isn't destroyed, the js context is also not destroyed and you can restore state your self.

**Comment by joshuapinter** [comment]
Thanks for the reply, @guyca! I've handled the `onSaveInstanceState` and `onRestoreInstanceState` in the past but do you have any sample implementations or pointers to how to save and restore the JS state as well? Particularly with the use of `react-native-navigation`. 

I don't mind digging but I can't be the only person that is using `react-native-navigation` that is dealing with this so a little help would be fantastic. 

Thanks!

**Comment by guyca** [comment]
Hey @joshuapinter 
Your js state shouldn't be lost when the Activity is destroyed since Js context isn't destroyed when the activity is destroyed.

You listening to [onAppLaunched](https://wix.github.io/react-native-navigation/#/docs/events?id=onapplaunched) event to show your ui when the application is first launched. Use that same event to restore your ui after the Activity is restarted.

```js
const appLaunchedListener = Navigation.events().registerAppLaunchedListener(() => {
  if (store.items) {
    // Items have already been loaded, our Activity has been recreated
    restoreUi();
  } else {
    loadItems();
    showUi();
  }
});
```

Hope this helps.

**Comment by joshuapinter** [comment]
Thanks, @guyca. I'm using your sample application to test this. So is this not done properly in the sample app? Should it be?

And to clarify, are `restoreUi()`, `loadItems()` and `showUi` actual methods or is that pseudo-code that we're supposed to build out?

Thanks.

**Comment by guyca** [comment]
This functionality isn't built into the playground app. This behaviour is unique to each app, therefore we don't force anything upon the developer.
Indeed these function are pseudo code
