### ISSUE TITLE
[iOS] showModal custom animation Platform inconsistency

### ISSUE THREAD

**Issue by jinshin1013** [wix/react-native-navigation#5078]
### Issue Description
showModal animations options differ on iOS and Android.

Related issue: #4886 and maybe this? #5036 

### Steps to Reproduce / Code Snippets / Screenshots
```tsx
Navigation.showModal({
  stack: {
    children: [
      {
        component: {
          name: 'COMPONENT_NAMAE',
          options: {
            animations: {
              showModal: {
                // Works on Android but not on iOS
                alpha: {
                  from: 0,
                  to: 1,
                  duration: 250,
                },

                // Only works on iOS
                content: {
                  alpha: {
                    from: 0,
                    to: 1,
                    duration: 250
                  }
                }
              },
            },
          },
        },
      },
    ],
  },
})

```

The same config is applicable in `dismissModal` animations option as well as single component showModal.

---
### Environment
* React Native Navigation version: 2.18.4
* React Native version: 0.59.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by igortupini** [comment]
This still an issue

**Comment by jinshin1013** [comment]
Still an issue.

**Comment by jinshin1013** [comment]
Not stale :(

**Comment by huuthinh245** [comment]
Still an issue. on v3

**Comment by pdziak** [comment]
And v2 of course.

**Comment by jinshin1013** [comment]
Still an issue :(

**Comment by jinshin1013** [comment]
pleasse it's still an issue

**Comment by jinshin1013** [comment]
Not resolved.

**Comment by cinder92** [comment]
still and issue, and animation fade didn't work on android 6-7

**Comment by guyca** [comment]
Fixed in [v5](https://github.com/wix/react-native-navigation/issues/5904) :)
