### ISSUE TITLE
Discussion: Supporting Fabric & TurboModules

### ISSUE THREAD

**Issue by ericlewis** [wix/react-native-navigation#5080]
### Issue Description

Fabric and TurboModules are both new architectural changes to react-native that will be landing at some point in 2019, currently, there is code for both in the master repo. I have been experimenting with both and there is a number of architectural changes that will need to happen to this library in order to support them. I am opening this issue to gauge interest, and see if the maintainers are open to API changes in order to support these endeavors. Some of the most obvious changes are:

- Will need to expose the delegates used by CxxBridge in order to install TMs (maybe temp measure) but definitely needed to expose the lookup delegates, this is quite similar to how extraModules works today.

- Will need to move from RCTRootView. Fabric uses RCTSurface's for most things, there is a view proxy for RCTRootView in Fabric that works quite nicely. I am currently experimenting with this on a private branch of RNN.

**Comment by guyca** [comment]
Hey @ericlewis 
We're totally open to api changes, we can keep all fabric efforts in a dedicated branch and once we're ready publish a new major version.
Do you plan on working on Android support as well?

**Comment by ericlewis** [comment]
@guyca indeed I do. This is on my list of todos. That is a good idea, we could also consider creating a subspec in the cocoapods for RNN that makes it very easy to use, that way those of us already on fabric will have it fairly easy.

**Comment by mrousavy** [comment]
Closed with https://github.com/wix/react-native-navigation/pull/6399 and https://github.com/wix/react-native-navigation/pull/5086
