### ISSUE TITLE
Using unstated with RNN and auth

### ISSUE THREAD

**Issue by djMax** [wix/react-native-navigation#5081]
### Issue Description

I am using [unstated](https://github.com/jamiebuilds/unstated) for state management which requires that I surround the "root" component with a _Provider_ component (unstated's Provider, not RNN). Before RNN, I just put this around the App component. But the auth examples I've found for RNN talk about launching an auth flow and THEN navigating to the App component. That wouldn't work in this case because it would cause a new Provider to be spun up which has all sorts of bad side effects.

I can imagine a setRoot with a stack that had the auth on it that just moved from the Welcome/Splash screen directly to the tab-based navigation of the main app, but I'm not sure why the auth examples wouldn't have done that instead if it was that easy.

How does one integrate React-context based state into RNN without a JS-side root component that's always in the hierarchy?

### Environment
* React Native Navigation version: 2.18.4
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): both

**Comment by jinshin1013** [comment]
Isn't it sufficient to just wrap your screen with Unstated Provider when you register them? Like below:

```
Navigation.registerComponent(() => <UnStatedProvider><YourComp /></UnStatedProvider>)
```

Each screen you register is treated as `root` component (I apologise if I'm wrong here :p) so you do need to wrap each screen with the Provider, I'm not entirely sure about what side effect it can cause?

**Comment by djMax** [comment]
I tried that, but it didn't work at all. I got `undefined is not an object (evaluating _react.React.createElement)`. Strangely, the top of the stack was DatePickerAndroid.android.js, and this is a blank app with a view with just a text component on it. But if I take the Provider out, it works. The side effect I'm worried about is constructing multiple React contexts (via the unstated provider) which you're not supposed to do. Basically various libraries require a stable root component, and RNN seems to forbid this. Am I misunderstanding that?

**Comment by djMax** [comment]
That was my own silly bug, fixed now (mental note, `import { React } from 'react'` in one out of 50 components is 1 too many). BUT, it does do what I was afraid of, which is create independent state for every screen, which is obviously bad. I don't fully grok React Context yet, but I think it presents some challenges with RNN.

**Comment by christianlippa** [comment]
I would definitely look into redux. There are many examples of it working with React Native Navigation and it provides you with global state management like you want.

**Comment by jinshin1013** [comment]
Not sure why Unstated Provider has that behaviour. I use react-apollo, react-apollo-hooks and mobx which all provide their own Provider and I wrapped these for all screens that are being registered with RNN and never had any side effect as they keep them the same instance. Would you care to share a demo repo with RNN and Unstated setup? I'm keen to have a look.

**Comment by djMax** [comment]
The problem is here:

https://github.com/jamiebuilds/unstated/blob/master/src/unstated.js#L163

Since all the RNN Provider instances end up siblings, they don't share state. I fixed it by basically copying this library (it's small) and making them all use "parentMap" and passing in a Map to the initial createContext function.

**Comment by jinshin1013** [comment]
I had a quick play around with `Unstated` with `RNN` and wrapping Unstated `Provider` for each screen when registering worked with using Unstated `Subscribe` in a component. But it only works if your Unstated `Container` is exported as an instance so like below:

```tsx
// RNN Provider to register each screen
import { Provider } from 'unstated'

class RNNHocProvider extends React.Component<Props> {
  return (
    <Provider>
      <WrappedComponent />
    </Provider>
  )
}

// Unstated Counter Container
import { Container } from 'unstated'

class CounterContainer extends Container {
  // snip
}
export const counterContainer = new CounterContainer()

// Your screen component 1
import { Subscribe } from 'unstated'
import { counterContainer } from 'path-to-your-counter-container'

const ScreenComp1 = () => (
  <Subscribe to={[counterContainer]}>
    {counter => <View />}
  </Subscribe>
)

// Your screen component 2
import { Subscribe } from 'unstated'
import { counterContainer } from 'path-to-your-counter-container'

const ScreenComp2 = () => (
  <Subscribe to={[counterContainer]}>
    {counter => <View />}
  </Subscribe>
)

``` 

Upon updating counter state in `ScreenComp1` will be reflected in `ScreenComp1`.

**Comment by smooJitter** [comment]
@jinshin1013 

Maybe this will help

https://github.com/wix/react-native-navigation/issues/4517

**Comment by djMax** [comment]
(I would suggest it's a feature request, because I think the idea that there may need to be "a thing" at the top of the render hierarchy is not limited to unstated. Perhaps it's simply not possible with RNN, but if it is, then I'd argue it should be exposed)

**Comment by jinshin1013** [comment]
It's more of how you architecture your app, you can pass the same instance of the provider when you are registering your screen to avoid having multiple instances of Provider. Kinda like the `registerComponentWithRedux`.

**Comment by smooJitter** [comment]
@jinshin1013 have you tried Unstated-next?

**Comment by jinshin1013** [comment]
I had a brief play around, I had a success by passing the same instance of the Unstated Container to `Subscribe` worked without even needing to pass the same instance of Unstated `Provider` when registering RNN components. But in my work project, I recently refactored how it registers all the component by passing the same instance of mobx and apollo Providers.

**Comment by iamyellow** [comment]
hey folks, maybe someone will find interesting my approach, so i'm here.

i've managed to mix `unstated-next` with `Proxy` (where available). actually, i've rewritten `unstated-next` for this. 

some background: we're making a `tvos` app, so we have RNN screens and we're handling menu button touches with RN `BackHandler`. 

first, our `createContainer` (renamed to `createGlobalContainer`):

```typescript
import React from "react";

interface ContainerProviderProps {
  children: React.ReactNode;
}

interface Container<Value, State = void> {
  Provider: React.ComponentType<ContainerProviderProps>;
  useContainer: () => Value;
  getState: () => State | undefined;
}

export default function createGlobalContainer<State, Value>(
  useHook: (
    getter: () => State | undefined,
    setter: (nextState: State | undefined) => void
  ) => Value,
  initialState?: State
): Container<Value, State> {
  const Context = React.createContext<
    [{ value: State | undefined }, Value] | null
  >(null);

  const listeners: { [key: string]: (s: State | undefined) => void } = {};
  const state = { value: initialState };

  function Provider(props: ContainerProviderProps) {
    const proxy = new Proxy(state, {
      set(obj, prop, value) {
        if (typeof prop !== "string" || prop !== "value") {
          return Reflect.set(obj, prop, value);
        }

        obj.value = value;
        Object.values(listeners).forEach(listener => {
          listener(value);
        });

        return true;
      }
    });

    const getter = () => state.value;
    const setter = (nextState: State | undefined) => (state.value = nextState);
    const value = useHook(getter, setter);

    return (
      <Context.Provider value={[proxy, value]}>
        {props.children}
      </Context.Provider>
    );
  }

  function useContainer(): Value {
    let contextValue = React.useContext(Context);
    if (contextValue === null) {
      throw new Error("Component must be wrapped with <Container.Provider>");
    }

    const [proxy, rest] = contextValue;

    const [, setInternalStateValue] = React.useState<State | undefined>(
      proxy.value
    );

    React.useEffect(() => {
      // https://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript
      const uniqueId =
        Math.random()
          .toString(36)
          .substring(2) + new Date().getTime().toString(36);

      listeners[uniqueId] = (v: State | undefined) => {
        setInternalStateValue(v);
      };

      return () => {
        delete listeners[uniqueId];
      };
    }, []);

    return rest;
  }

  return { Provider, useContainer, getState: () => state.value };
}
```

how we write our custom `useWhatever` (e.g.: handle navigation)?

```typescript
import createGlobalContainer from "@internal/providers/createGlobalContainer";

type NavigationState = [string, boolean?] | undefined;

function useNavigation(
  getCurrentComponent: () => NavigationState,
  setCurrentComponent: (nextState: NavigationState) => void
) {
  return { getCurrentComponent, setCurrentComponent };
}

const NavigationContainer = createGlobalContainer(useNavigation);
export default NavigationContainer;
```

now, a `HomeScreen`:
```typescript
const HomeScreen: ScreenComponent = props => {
  const { setCurrentComponent } = NavigationContainer.useContainer();

  useEffect(() => {
    setCurrentComponent([props.componentId, true]);
  }, []);

  // ...
}
```

an "extra" bonus is we can get the state from outside screens:

```typescript
BackHandler.addEventListener("hardwareBackPress", function() {
  const currentComponent = NavigationContainer.getState();

  if (currentComponent) {
    const [id, isRoot] = currentComponent;
    if (!isRoot) {
      Navigation.pop(id);
    }
  }
});
```

you can use this as you'd use `unstated-next`, though there a couple of differences:

* the second `createGlobalContainer` argument is the first state (can be `undefined`)
* your hook alway has two arguments, the `getter` and `setter` of the state

again, hope this helps, happy to contribute and obviously poke me if you find some bug or better approach!

**Comment by artemkloko** [comment]
> you can pass the same instance of the provider when you are registering your screen to avoid having multiple instances of Provider.
> But in my work project, I recently refactored how it registers all the component by passing the same instance of mobx and apollo Providers.

@jiangxunyue Can you please show an example of how you did that?
