### ISSUE TITLE
Inconsistent TextInput direction is in RTL languages

### ISSUE THREAD

**Issue by Amir-M7** [wix/react-native-navigation#5083]
### Issue Description

TextInput text direction has an inconsistent behavior when it comes to the RTL languages. I think the pictures below are describing the issue well:

### Steps to Reproduce / Code Snippets / Screenshots
Android:
![1](https://user-images.githubusercontent.com/17439071/57373002-7dc6b980-71ac-11e9-814b-650a4514e226.jpg)

iOS:
<img width="374" alt="2" src="https://user-images.githubusercontent.com/17439071/57373009-81f2d700-71ac-11e9-9867-b4ada3a2b27b.png">

As you can see, iOS behaves as it's expected, but it seems like that Android changes the direction in an unexpected way.
---
### Environment
* React Native Navigation version: 2.18.2
* React Native version: 0.59.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, OS version is 9,Debug mode

**Comment by MakhouT** [comment]
As this is related to TextInput, I don't think it's related to RNN?

**Comment by Amir-M7** [comment]
this is related to react-native, I've upgraded the react-native version to the latest version

**Comment by Amir-M7** [comment]
this was related to react-native ,I've upgraded react-native (0.59.8) and the problem seems to be solved.
