### ISSUE TITLE
Can't block Android Back Button behavior in Modal

### ISSUE THREAD

**Issue by Dantalion** [wix/react-native-navigation#5084]
### Issue Description

I can catch and alter the behavior of the Android hardware back button in every screen, but not in modals.
No matter what I do, the Android back button always dismisses the modal.

### Steps to Reproduce / Code Snippets / Screenshots

```js                

handleBackPress() {
        ToastAndroid.showWithGravity(
            "Please fill out the form",
            ToastAndroid.SHORT,
            ToastAndroid.CENTER
        );
        return true;
  }
                                         
componentDidDisappear () {
        BackHandler.removeEventListener("hardwareBackPress", this.handleBackPress);
    }

    componentDidAppear() {
        BackHandler.addEventListener("hardwareBackPress", this.handleBackPress);
    }
 ```                                                           
The code seems to work everywhere except in modals.

---
### Environment
* React Native Navigation version: 2.18.2
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator, Debug and Release

**Comment by hossamnasser938** [comment]
I have the same issue. The callback registered with "hardwareBackPress" is never called.

**Comment by hossamnasser938** [comment]
I solved it by setting `overrideBackPress `when showing the modal.
```
this.props.navigator.showModal( {
    screen: "your_screen",        
    overrideBackPress: true
} );
```
and then in the modal component you can listen on ` backPress ` event.
```
props.navigator.setOnNavigatorEvent( event => { 
            if ( event.id === "backPress" ) {
                console.log( "pop twice" );
                props.navigator.dismissModal();
                console.log( "popToRoot" );
                props.navigator.popToRoot();
                return true;
            } 
} );
```
