### ISSUE TITLE
I'm using 0.59.0-rc.3

### ISSUE THREAD

**Issue by priyankurs** [wix/react-native-navigation#5088]
I'm using 0.59.0-rc.3

and solved by these steps:

- In gradle-wrapper.properties
change `distributionUrl` to `distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip`
- and in root `build.gradle` file change gradle classpath to this: `classpath 'com.android.tools.build:gradle:3.3.0'`
- Copy file 'metro.config.js' in [0.59-stable/template](https://github.com/facebook/react-native/tree/0.59-stable/template) to your project.
- Remove node_modules, yarn install, and run-android again.
(And make sure version of metro in package.json "metro-react-native-babel-preset": "0.51.0" is the same with current metro's version)

_Originally posted by @kimbui87 in https://github.com/wix/react-native-navigation/issues/4757#issuecomment-468133753_

**Comment by priyankurs** [comment]
what does "remove node_modules, yarn install means?

**Comment by jinshin1013** [comment]
This question is more suitable for stackoverflow, but it's literally deleting your `node_modules` folder in your project and do `npm install` or `yarn install` to reinstall your dependencies. Deleting `node_modules` folder 100% ensures that all the packages installed in your project are the ones you specified in your `package.json`.
