### ISSUE TITLE
[v2][ios] topBar drawBehind not working when pushing a screen with animation options

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#5090]
### Issue Description

Hi Wix,

we've been trying to migrate to v2 of your library, and we noticed than if we use a custom animation like so: 

```
animations: {
  push: { // It works! Push with animation from right to left
    enabled: 'true', // Optional, used to enable/disable the animation
    topBar: {
      alpha: {
        from: 0,
        to: 1,
        duration: 400,
      },
    },
    content: {
      x: {
        from: 1000,
        to: 0,
        duration: 300,
      },
      alpha: {
        from: 0.5,
        to: 1,
        duration: 300,
      },
    },
  },
}
```

the pushed screen content is hidden behind the top Bar  (as if `drawBehind` was set to true - even if it's explicitly set to false).
Commenting out that, makes the content visible.

We tested many versions of react-native-navigation, and it looks like the commit that broke things is this: https://github.com/wix/react-native-navigation/commit/a98f18704cc49094cd91859e75089328b4fd7cbc

- 2.14.0-snapshot.245 **Works**
- 2.14.0-snapshot.246 **Doesn't work**

### Steps to Reproduce / Code Snippets / Screenshots

Just push any screen with the above animation options ^ and you'll experience the content getting hidden behind the nav bar.

---
### Environment
* React Native Navigation version: **2.18.5**
* React Native version: **0.56.0**
* Platform(s) (iOS, Android, or both?): **iOS only**
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator for sure, but most probably everywhere

**Comment by cosivox** [comment]
+1

Any workaround?

**Comment by yogevbd** [comment]
I'm trying to reproduce this in the playground app with no luck.. Can you please try to reproduce it in the playground app and push it to a new branch?
