### ISSUE TITLE
Drawer style (width) and question about deprecation.

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#510]
- I can see the native part of the code accepts a:
`style` [prop](https://github.com/wix/react-native-navigation/blob/master/ios/RCCDrawerController/RCCTheSideBarManagerViewController.m#L70) with a `leftDrawerWidth` [prop](https://github.com/wix/react-native-navigation/blob/master/ios/RCCDrawerController/RCCTheSideBarManagerViewController.m#L99) within it, so that we can specify the width of a drawer, but without forking your repo, I see no way to pass a style on the native drawer.
How do I pass styles to that?

- Also I'm using both your Drawer, and your Notifications, but I can see those are deprecated. Should I keep using them or do you plan to remove them in the future?
I really love those features and would hate to see them removed.

Thank you.

**Comment by guyca** [comment]
Drawer isn't going to be deprecated. We're going to improve it since it's a very requested feature.

Regarding drawer width, it would be ideal if you'd be able to simply set your drawer width in Jsx and the native part would simply wrap it. I started implementing that on Android some time ago but didn't get around to finish it..

**Comment by guyca** [comment]
@SudoPlz Full width SideMenu, right and left SideMenu are available on Android. You can also set custom width SideMenu in jsx. There was a bug where the SideMenu was not measured correctly on Android, so the SideMenu blocked touch in ~80% of the screen - that's fixed now.

**Comment by SudoPlz** [comment]
aaaah, so cool, that sounds amazing. What property do I use to set the width of the side menu?

So after that let's close the issue..!

**Comment by guyca** [comment]
Simply set a specific `width` to the root view you display in the SideMenu.

**Comment by SudoPlz** [comment]
amazing... Thanks. Closing the issue.
