### ISSUE TITLE
Use Functional Component to register screens

### ISSUE THREAD

**Issue by jinshin1013** [wix/react-native-navigation#5100]
### Issue Description
The official documentation, [here](http://wix.github.io/react-native-navigation/#/docs/Usage?id=registercomponentscreenid-generator) mentions that:

> The component itself is a traditional React component extending `React.Component` or `React.PureComponent`.

With the introduction to React Hooks, more people are embracing Functional Components in favour of Class Components. I personally have been creating any new API within the project to use Hooks and I've came to a point where I needed to use Functional Component when registering the screen with RNN `registerComponent`. And surprisingly enough, it just worked. Now all my screens are registered as a Functional Component. Should we be updating the doc? Or is it supposed to not work with Functional Components?  

### Steps to Reproduce / Code Snippets / Screenshots
```tsx
// Screen 1
const Screen1: React.FC<Props> = () => <View />

// Registering
Navigation.registerComponent("routeName", () => Screen1)
```
---
### Environment
* React Native Navigation version: 2.18.4
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): BOTH
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by MakhouT** [comment]
Nowhere in the docs is stated that you cannot use functional components. Nor is stated that you need to use class based components.
I think this ticket can be closed.

**Comment by jinshin1013** [comment]
I've referenced the quote above. Please click the link I've provided in the issue.

**Comment by jono-allen** [comment]
@jinshin1013 I would be in favour of updating the docs to make this clear. I wasn't sure until searching the issues.

**Comment by jinshin1013** [comment]
I could create a PR for this once I get time!

**Comment by MakhouT** [comment]
My bad, you are correct.

**Comment by guyca** [comment]
@jinshin1013 We should definitely update the docs 👍 
Functional components are suported as well

**Comment by MakhouT** [comment]
I don't think they are fully supported yet?
I currently only have functional components in a pretty empty RN app.
I cannot push on the stack, when converting the component to a class component, it works.

**Comment by jinshin1013** [comment]
Do you have a reproducible repo? It seems to work fine on my project.

**Comment by MakhouT** [comment]
Can't sure the full repo, but here is a snippet relevant to the discussion:

` Navigation.setRoot({
    root: {
      bottomTabs: {
        children: [
          {
            stack: {
              children: [
                {
                  component: {
                    name: 'FirstScreen',
                    options: {
                      topBar: {
                        title: {
                          text: i18n.t('tabs.home'),
                        },
                      },
                    },
                  },
                },
              ],
              options: {
                bottomTab: {
                  icon: ICONS_MAP.HOME,
                  text: i18n.t('tabs.home'),
                },
              },
            },
          },
          {
            stack: {
              children: [
                {
                  component: {
                    name: 'SecondScreen',
                    options: {
                      topBar: {
                        title: {
                          text: i18n.t('tabs.info'),
                        },
                      },
                    },
                  },
                },
              ],
              options: {
                bottomTab: {
                  icon: ICONS_MAP.INFO,
                  text: i18n.t('tabs.info'),
                },
              },
            },
          },
        ],
      },
    },
  });`


`
const buttonOnPress = props => {
  Navigation.push(props.componentId, {
    component: {
      name: 'FirstScreen',
      passProps: {
        text: 'Pushed screen',
      },
      options: {
        bottomTabs: {
          visible: false,
          animate: true,
        },
        topBar: {
          title: {
            text: i18n.t('fakeTitle'),
          },
        },
      },
    },
  });
};

export const SecondScreen = props => {
  return (
    <View style={styles.container}>
      <Button text={i18n.t('buttonText')} onPress={buttonOnPress} />
    </View>
  );
};
`

**Comment by igortupini** [comment]
I can endorse that functional components are fully supported. I have a big project using only React Hooks and no class components whatsoever. My biggest issue was when I tried to use static methods, but I was able use a workaround.

Would be nice if functional components were present in the documentation.

**Comment by MakhouT** [comment]
@igortupini Please share your workaround for static methods.

**Comment by igortupini** [comment]
@MakhouT Basically I was trying to declare topBar buttons statically (like is shown on the [docs declaring buttons statically](https://wix.github.io/react-native-navigation/#/docs/topBar-buttons?id=declaring-buttons-statically))

The solution I found is quite simple. I assign a option key for the component.
Like this:
```js
import React from 'react'
import { View, Text } from 'react-native'

const MyComponent = () => {
  return (
    <View>
      <Text>Hooks are awesome!</Text>
    </View>
  )
}

MyComponent.options = {
  topBar: {
    visible: true,
    background: {
      color: '#ff1c61'
    }
  }
}

export default MyComponent
```

**Comment by MakhouT** [comment]
Beautiful! Thanks for sharing!

**Comment by smooJitter** [comment]
@igortupini 

Do wrap your components with a custom screen registration function?  I’d bee interested to see your navigation services api

**Comment by smooJitter** [comment]
Consider this:    

https://github.com/marblecodes/react-native-boilerplate/blob/49a1b91d480898432a9c1df6ec4d6c8941518044/src/lib/registerContainerWithProviders.js


I’m trying to turn this into a functional component because i can’t attach refs to functional components

**Comment by smooJitter** [comment]
`
 export function registerContainerWithProviders(containerName, comp, store, client) {
  const generatorWrapper = function() {
    const InternalComponent = comp;

    return class Scene extends Component {
      static options = {
        ...comp.options,
      }

      render() {
        return (
          <Provider store={store}>
            <ApolloProvider client={client}>
              <ThemeProvider theme={theme}>
                <InternalComponent
                  ref="child"
                  {...this.props}
                />
              </ThemeProvider>
            </ApolloProvider>
          </Provider>
        );
      }

      resendEvent(eventName, params) {
        const instance = this.refs.child.getWrappedInstance
          ? this.refs.child.getWrappedInstance()
          : this.refs.child;

        if (instance && instance[eventName]) {
          instance[eventName](params);
        }
      }

      componentDidAppear() {
        this.resendEvent('componentDidAppear');
      }

      componentDidDisappear() {
        this.resendEvent('componentDidDisappear');
      }

      componentWillUnmount() {
        this.resendEvent('componentWillUnmount');
      }

      componentWillReceiveProps(nextProps) {
        this.resendEvent('componentWillReceiveProps', nextProps);
      }

      onNavigationButtonPressed(buttonId) {
        this.resendEvent('onNavigationButtonPressed', buttonId);
      }
    };
  };

  Navigation.registerComponent(containerName, generatorWrapper);
}
`

**Comment by ItsNoHax** [comment]
I think this issue can be closed. Functional components have been supported since the start. Don't forget we use the issue tracker for bugs and/or feature requests.

**Comment by karlmarxlopez** [comment]
I wrote a tiny util function, [react-native-navigation-register-screens](https://www.npmjs.com/package/react-native-navigation-register-screens) (I know that's mouthful, but I want to be explicit) that allows to register an array of screens, provide an optional prefix, and a callback function when you want to wrap a screen with provider (e.g redux provider). You can use the 3 types provided:
1. `ScreenFunctionComponent` - wraps `React.FC`
1. `ScreenComponent` - wraps `React.Component`
1. `ScreenPureComponent` - wraps `React.PureComponent`

All of these appends `componentId` props to passed prop type via generics
