### ISSUE TITLE
Close side drawer on click does not working mergeOptions

### ISSUE THREAD

**Issue by fatihmert** [wix/react-native-navigation#5108]
### Issue Description

I'm working redux and redux-thunk. I made toggle drawer with redux. But, when I tried close button act to close drawer with mergeOption (visible:false), return to error _Cannot read property 'componentId' of undefined_

### Steps to Reproduce / Code Snippets / Screenshots

One image is enough;
![alt text](https://i.ibb.co/dMTmhFm/indir.png "rnn2 merge option does not work on drawer")

---
### Environment
* React Native Navigation version: 2.18.3
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Official Android Studio Simulator (HAXM) / Android 5.0.2 / [sdk_google_phone_x86-eng 5.0.w LSY66K]

**Comment by ItsNoHax** [comment]
Your onCloseSideDrawer method does not have access to 'this'. 

Change it to:
```
onCloseSideDrawer = () => {
  // ur code here
}
```
