### ISSUE TITLE
[V2] Is it possible to set popGesture value for each screen

### ISSUE THREAD

**Issue by SergeyBazhanov** [wix/react-native-navigation#5109]
### Issue Description

Hi. Thank you for this awesome package. Could you please point me is it possible to set popGesture value for each screen separately? 

I tried to set it via static options like this:
`static options() {
        return {
            popGesture: false,
        };
    }`

But the functionality looks broken. 
Reproducing steps:
1. Set popGesture: false for screen A
2. Set popGesture: true for screen B
3. Go to screen A
4. Push screen B
5. Try to make swipe to go back to screen A

Expected behaviour: screen B is popped
Actual behaviour: screen B is not popped, topBar back button stops to work

The same if i use Navigation.mergeOptions function for that

Thanks in advance

---
### Environment
* React Native Navigation version: 2.18.5-snapshot.332
* React Native version: 0.59.4
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Any IOS device

**Comment by SergeyBazhanov** [comment]
Hi guys. Any update about this topic? Changing popGesture parameter on fly leads to hiding topBar and screen becomes untouchable at all. This is important issue for me

Thanks

**Comment by amehrdad88** [comment]
Trying this behaviour (e.g. setting the popGesture to false for one screen (through Navigation.push(...) ) leads to other screens freezing if I try a pop gesture. I think it's a bug in the current version of RNN
