### ISSUE TITLE
iOS TopBar title font weight changes on push/pop

### ISSUE THREAD

**Issue by Nickforall** [wix/react-native-navigation#5113]
### Issue Description

![2019-05-15 20 30 45](https://user-images.githubusercontent.com/4987698/57799921-72493480-7750-11e9-88b7-64792f82d9da.gif)

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.setRoot({
    root: {
      stack: {
        children: [
          {
            component: {
              name: 'navigation.app',
              options: {
                topBar: {
                  visible: true,
                  title: {
                    text: 'Your Recipes',
                  },
                  searchBar: true,
                  searchBarPlaceholder: "Search for Recipes",
                  rightButtons: [
                    {
                      id: "add-recipe",
                      systemItem: "add"
                    }
                  ]
                },
              }
            }

          }
        ]
      }
    }
  })
```

After using Navigation.push() and Navigation.pop() the title font weight changes and stays like this.

---
### Environment
* React Native Navigation version: Tested on latest master branch
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both Simulator + physical device. Both debug and release builds.

**Comment by jinshin1013** [comment]
Yeah, this has been around for some time now. I think this occurs on both platform.

**Comment by mpiannucci** [comment]
I have the same problem, huge bummer

**Comment by Crisis2010** [comment]
Same here

**Comment by MakhouT** [comment]
I can reproduce this on 
`  "react-native": "0.59.8",
    "react-native-navigation": "2.18.5"`

**Comment by Nickforall** [comment]
For everyone experiencing this:
Hotfixed it for myself by editing this line:

https://github.com/wix/react-native-navigation/blob/b0c8113243de2043b98442dd485c04b0422aa213/lib/ios/RNNFontAttributesCreator.m#L18

```objective-c
- titleTextAttributes[NSFontAttributeName] = [UIFont systemFontOfSize:[fontSize floatValue]];
+ titleTextAttributes[NSFontAttributeName] = [UIFont boldSystemFontOfSize:[fontSize floatValue]];
```

**Comment by MakhouT** [comment]
Create a PR for it, everyone can benefit from it :)

**Comment by Nickforall** [comment]
I don't think it's exactly expected behavior to always be bold, and this also only works if you don't use a custom font. If it is I'd be happy to create a PR :)

**Comment by jinshin1013** [comment]
I think it should inherit from the user set in options, however if user doesn't specify, it should be default to bold? The fact that it's bold initially suggest to me that it should default to bold.

**Comment by Nickforall** [comment]
There is no configurable option as of now.

**Comment by piuholo** [comment]
Still an issue on `react-native-navigation` version 2.21.0

**Comment by michaelfreund** [comment]
> For everyone experiencing this:
> Hotfixed it for myself by editing this line:
> 
> https://github.com/wix/react-native-navigation/blob/b0c8113243de2043b98442dd485c04b0422aa213/lib/ios/RNNFontAttributesCreator.m#L18
> 
> ```diff
> - titleTextAttributes[NSFontAttributeName] = [UIFont systemFontOfSize:[fontSize floatValue]];
> + titleTextAttributes[NSFontAttributeName] = [UIFont boldSystemFontOfSize:[fontSize floatValue]];
> ```

Used https://www.npmjs.com/package/patch-package along with this one

```diff
- titleTextAttributes[NSFontAttributeName] = [UIFont systemFontOfSize:[fontSize floatValue]];
+ titleTextAttributes[NSFontAttributeName] = [UIFont systemFontOfSize:[fontSize floatValue] weight:UIFontWeightBold];
```

**Comment by jinshin1013** [comment]
NOt stale :(

**Comment by jinshin1013** [comment]
not stale :(
