### ISSUE TITLE
[V2][Android] Icon image in BottomTabs too small than iOS

### ISSUE THREAD

**Issue by dayaki** [wix/react-native-navigation#5115]
### Issue Description

The image used for bottomTabs appears smaller on Android than on iOS, iOS is displaying the ideal size of the image but on Android, it is way too small. How do I make the Android version look like the iOS version? see images below.

### iOS
![image](https://user-images.githubusercontent.com/815619/57816508-79356e80-7773-11e9-82ad-133f7128a5ae.png)

### Android
![image](https://user-images.githubusercontent.com/815619/57816522-85b9c700-7773-11e9-9acc-e34103d8e363.png)

### Steps to Reproduce / Code Snippets / Screenshots
```js
{
            stack: {
              children: [{ component: { name: "Friends" } }],
              options: {
                bottomTab: {
                  icon: require("./assets/img/friends-tab-icon.png"),
                  iconColor: "#878787",
                  selectedIconColor: "#00C040"
                }
              }
            }
          },
          { // The problematic icon
            stack: {
              children: [{ component: { name: "Map" } }],
              options: {
                bottomTab: {
                  icon: require("./assets/img/lens-tab-icon.png"),
                }
              }
            }
          },
          {
            stack: {
              children: [{ component: { name: "Notifications" } }],
              options: {
                bottomTab: {
                  icon: require("./assets/img/notification-tab-icon.png"),
                  iconColor: "#878787",
                  selectedIconColor: "#00C040"
                }
              }
            }
          }
```

---
### Environment
* React Native Navigation version: **2.18.5**
* React Native version: **0.59.8**
* Platform(s) (iOS, Android, or both?): **Both**
* Device info (Simulator/Device? OS version? Debug/Release?): **Simulator and Device**

**Comment by peresbri** [comment]
We are having the same problem. Icon size in iOS is fine but Android always small. Even tried following the documentation and adding the icons natively, but didn't work.
Did you find a workaround @dayaki ?

**Comment by dayaki** [comment]
@peresbri no workaround so far, just using it like that for now. You?

**Comment by ParshantAroras** [comment]
Why it is closed ? Have any one find any solution? . It would be appreciated

**Comment by ParshantAroras** [comment]
Why it is closed ?. Any on find any solution ? It would be appreciated .

**Comment by umkhan65** [comment]
@ParshantArora I tried doing that but still having same issue

**Comment by ParshantArora** [comment]
Just hide the tabs view( not remove)  and create your custom tabbar component and use that .

**Comment by umkhan65** [comment]
@ParshantArora 
`icon: {
     uri: 'home_icon_bottom',
     scale: 0.1 // I have tried 1 and 3 too but still getting same size
},`

Still getting this 
![Screen Shot 2019-09-26 at 7 58 58 PM](https://user-images.githubusercontent.com/25492618/65699870-2b713100-e098-11e9-93d8-b24adc5c9fa3.png)

**Comment by ParshantAroras** [comment]
@umkhan65 scale: 0.1 is for ios only . Either use  Custom tabs or use the following code

This piece controls opening my custom circle button component 
Navigation.showOverlay({
    component: {
      name: 'common.AddIcon',
      passProps: {},
      options: {
        statusBar: {},
        overlay: {
          interceptTouchOutside: false,
        },
      },
    },
  });

And the circle component:
...
const StyledAddButtonContainer = styled(View)`
  position: absolute;
  justify-content: center;
  align-items: center;
  left: ${screenWidth / 2 - 35};

  bottom: ${getBottomSpace() ? 30 : 0};
  width: 70;
  height: 70;
  margin: auto;
`;
const AddIconContainer = styled(Animated.View)`
  background-color: 'purple';
  border-radius: 50;
  height: 70;
  width: 70;
  border-color: 'black';
  border-width: 6;
  justify-content: center;
  align-items: center;
`;
...
render () {
   return (
    <StyledAddButtonContainer>
        <TouchableWithoutFeedback
          onPress={() => {
           console.log('my thing')
          }}>
          <AddIconContainer
            style={{
              transform: [{ rotate }],
            }}>
            <FontAwesome5
              solid
              size={32}
              name="plus"
              color={GRAY_SCALE.WHITE}
            />
          </AddIconContainer>
        </TouchableWithoutFeedback>
      </StyledAddButtonContainer>
   )
}

**Comment by barbarossusuz** [comment]
@dayaki i am facing exactly same problem, did find any workaround ? Or anyone? 
React Native Navigation version: 4.0.4
React Native version: 0.61.5

**Comment by umkhan65** [comment]
@barbarossusuz my issue was really stupid. I cropped the empty space in my png to the exact size of icon. It solved my issue

**Comment by flikQ** [comment]
Did this ever get fixed as it's still occurring now. @guyca has this been reported before?
