### ISSUE TITLE
[V2][iOS] topBar buttons missing from a stack below modal

### ISSUE THREAD

**Issue by Jazqa** [wix/react-native-navigation#5116]
### Issue Description

I have a stack with a topBar.rightButtons and I open a modal on top of the stack with the same topBar.rightButtons. When I dismiss the modal, the stack below is missing the topBar.rightButtons.

### Steps to Reproduce / Code Snippets / Screenshots

1. Have a stack with topBar.rightButtons
2. Open a modal on top of the stack with the same topBar.rightButtons
3. Dismiss the modal
4. Buttons are gone on the stack below

---
### Environment
* React Native Navigation version: 0.59.8
* React Native version: 2.18, 2.19 (works on 2.16)
* Platform(s) (iOS, Android, or both?): iOS only

**Comment by Jazqa** [comment]
Still having the issue, but the cause described here is not correct and might be misleading. I'll investigate this more before re-opening.

**Comment by DanielBoening** [comment]
Have you found a solution? I am currently facing a similar problem of missing top bar buttons on some ios devices.
