### ISSUE TITLE
Icon issue on navBar

### ISSUE THREAD

**Issue by Romandeep** [wix/react-native-navigation#5118]
I was tried this for show search icon on navBar but not shown on navBar in android. My code is:

### Code Snippets:

Navigation.startSingleScreenApp({
screen: {
screen: 'movieapp.Movies',
title: 'Movies',
navigatorStyle,
rightButtons: [
{
id: 'search'
}
],
leftButtons: [
{
id: 'sideMenu'
}
]
},
drawer: {
left: {
screen: 'movieapp.Drawer'
}
}
});

My solution  code is:

static navigatorButtons = {
rightButtons: [
{
id: 'search',
icon: require('../../constants/images/search.png'),
}
]
};

using this above solution search icon shown on navBar but i want to follow first approach to shown search icon. My environment is this:

### Environment
* React Native Navigation version: "1.1.84",
* React Native version: "0.44.0",
* Platform(s) (iOS, Android, or both?):Android

**Comment by syedabuthahirm** [comment]
For Android you have to provide text or icon property for your nav buttons. but in iOS there are already lot of [glyphs icons](https://wix.github.io/react-native-navigation/#/docs/topBar-buttons?id=ios-system-items) available to use.

**Comment by Romandeep** [comment]
I have  already tried  this, text  shown  on navBar with title property but  icon dosn't shown with icon property.

**Comment by syedabuthahirm** [comment]
Your are using RNN 1.*. Please refer the this documentation 
https://x-guard.github.io/react-native-navigation/#/top-level-api?id=startsinglescreenappparams

Compare your code to the docs you have to place your buttons under navigatorButtons property. But, your placing directly under the component tree.

**Comment by Romandeep** [comment]
@syedabuthahirm  i tried this but it is not working.

# Code Snippets:

Navigation.startSingleScreenApp({
	screen: {
		screen: 'movieapp.Movies',
		title: 'Movies',
		navigatorStyle,
		navigatorButtons: {
			left: {
				id: 'sideMenu'
			},
			right: {
				id: 'search'
			}
		}
	},
	drawer: {
		left: {
			screen: 'movieapp.Drawer'
		}
	}
});

**Comment by syedabuthahirm** [comment]
Again you missed the naming convention you have to mention as `leftButtons` and `rightButtons` not ~`left`~ and ~`right`~

```js

navigatorButtons = {
    rightButtons: [
      {
        title: 'Edit', // for a textual button, provide the button title (label)
        id: 'edit', // id for this button, given in onNavigatorEvent(event) to help understand which button was clicked
        testID: 'e2e_rules', // optional, used to locate this view in end-to-end tests
        disabled: true, // optional, used to disable the button (appears faded and doesn't interact)
        disableIconTint: true, // optional, by default the image colors are overridden and tinted to navBarButtonColor, set to true to keep the original image colors
        showAsAction: 'ifRoom', // optional, Android only. Control how the button is displayed in the Toolbar. Accepted valued: 'ifRoom' (default) - Show this item as a button in an Action Bar if the system decides there is room for it. 'always' - Always show this item as a button in an Action Bar. 'withText' - When this item is in the action bar, always show it with a text label even if it also has an icon specified. 'never' - Never show this item as a button in an Action Bar.
        buttonColor: 'blue', // Optional, iOS only. Set color for the button (can also be used in setButtons function to set different button style programatically)
        buttonFontSize: 14, // Set font size for the button (can also be used in setButtons function to set different button style programatically)
        buttonFontWeight: '600', // Set font weight for the button (can also be used in setButtons function to set different button style programatically)
      },
      {
        icon: require('../../img/navicon_add.png'), // for icon button, provide the local image asset name
        id: 'add' // id for this button, given in onNavigatorEvent(event) to help understand which button was clicked
      }
    ]
  }

```
