### ISSUE TITLE
Show/hide component based on redux state

### ISSUE THREAD

**Issue by esbenvb** [wix/react-native-navigation#5119]
### Issue Description

I have an app where I want to show a spinner overlay, when data is being loaded. I use the redux state to determine when loads are in progress.

My initial solution was to create an overlay view, based on a component that was connected to redux and showed a spinner according to the redux state, and make that overlay always shown. While working greate on iOS, Android has known problems with the `interceptTouchOutside` option. https://github.com/wix/react-native-navigation/issues/3863 https://github.com/wix/react-native-navigation/issues/4953 - and it's also disturbing the RN inspector.

So I thought it could be smarter to show or hide the overlay using the RNN api, whenever data is loading or not.

### Steps to Reproduce / Code Snippets / Screenshots

```ts
function showLoadingOverlay() {
  Navigation.showOverlay({
    component: {
      name: ScreenNames.LoadingIndicator,
      id: ScreenNames.LoadingIndicator,
      options: {
        overlay: {
          interceptTouchOutside: false,
        },
      },
    },
  })
}

function hideLoadingOverlay() {
  Navigation.dismissOverlay(ScreenNames.LoadingIndicator)
}

export function updateLoadingStatus(action: Action, getState: () => ReduxState) {
  const state = getState()
  if (isLoading(state)) {
    showLoadingOverlay()
  } else {
  }
}

```

However, that case trouble right from the start, since i'm asking to open an overlay that might already have been shown when the previous operation started loading.

I thought of 2 approaches
* Programmatically merging the visibility true/false of the overlay on state changes. That does not seem to be an option, as I cannot control the visibility of mounted screens using the RNN API.
* Checking whether the component is currently shown/hidden and then hide/show it if neccesary. However, that does not seem to be a part of the RNN API either.

What options do I have left?

---
### Environment
* React Native Navigation version: 2.13.2
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 5, API25, iOS 12 iPhone X

**Comment by eightyfive** [comment]
Like you've stated:
> ...since i'm asking to open an overlay that might already have been shown when the previous operation started loading.

You need some kind of `boolean` in your redux side-effect in order to prevent to open multiple Overlays on top of each others.

You should basically know when you Loading Overlay is showing or not.

My 2 cents.

**Comment by esbenvb** [comment]
@ItsNoHax I don't see this a support-question, but more like a feature request.

 As written in the bottom of my post, the fact is, that i cannot reliably control the visibility of an RNN component, without keeping my own state, which might not be reliable.

The source of truth, whether a component is visible or not, is RNN.

I can't ask whether a component is already shown.
And i can't set a declarative visibility status of the component. 

I already tried something like the suggestion from @eightyfive but it did not work reliably.

I'll probably end up adding an overlay in each of my screen components, and connect its visiblity to a redux prop.
