### ISSUE TITLE
Integrating into swift application fails

### ISSUE THREAD

**Issue by szalaybalazs** [wix/react-native-navigation#5120]
### Issue Description

I just implemented the package to my existing react-native application using swift AppDelegate by default and it can not found the ReactNativeNavigation module.

The error is: `No such module 'ReactNativeNavigation'`

### Steps to Reproduce / Code Snippets / Screenshots

Integrate the package following the install guides to a swift AppDelegate file.

```swift
import ReactNativeNavigation

...

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    let jsCodeLocation = RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index", fallbackResource: nil)
    ReactNativeNavigation.bootstrap(jsCodeLocation, launchOptions: launchOptions)

    return true
  }
```

---
### Environment
* React Native Navigation version: ^2.19.0
* React Native version: 0.59.4
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Can't even build the app

**Comment by pdruart** [comment]
Hey szalaybalazs, 
you have to add the line '#import <ReactNativeNavigation / ReactNativeNavigation.h>' in your bridge header and remove your 'import ReactNativeNavigation' in the AppDelegate  :) ! 

have a nice day
