### ISSUE TITLE
react-native-vector-icons as icon in options

### ISSUE THREAD

**Issue by nwaughachukwuma** [wix/react-native-navigation#5121]
Hey guys,

I just started using this library and I think it's awesome really. But I have a point of stress, which is using react-native-vector-icons for option icon item. Why do I have to use a promise and all of that fugly stuff just to use vector icons?

I think something as simple as 
```
options: {
   bottomTab: {
     ...other options,
    icon: <Icon name="iconName" ... />
  }
}
```
should be cleaner and easier. What do you think?

**Comment by guyca** [comment]
BottomTab items don't support react views. The idea is to rely on React only to display your actual content (screens) since up until recently synchronous rendering wasn't supported by the framework. Supposedly this will change with Fabric.
