### ISSUE TITLE
How handle click on title of top bar?

### ISSUE THREAD

**Issue by juanm4** [wix/react-native-navigation#5123]
### Handle event click topBar title if possible

Is there a way to know when the title of top bar is clicked? I'm trying to find out in events but there is not a method to capture this event. 

---
### Environment
* React Native Navigation version: ^2.18.1
* React Native version: 0.59.4
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by guyca** [comment]
Hey there,
You'll need to create a custom react view for that. See the following for reference:

1. https://github.com/wix/react-native-navigation/blob/master/playground/src/screens/CustomTopBar.js#L13
2. https://github.com/wix/react-native-navigation/blob/master/playground/src/screens/OptionsScreen.js#L108

**Comment by hoangduy0610** [comment]
You'll need to create a custom react view for that.

https://github.com/wix/react-native-navigation/blob/master/playground/src/screens/CustomTopBar.tsx#L13
https://github.com/wix/react-native-navigation/blob/master/playground/src/screens/OptionsScreen.tsx#L180
