### ISSUE TITLE
[Regression] Topbar's button custom components weird behaviour

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#5124]
### Issue Description

It seems between version 2.17 and 2.19 there has been a change in how custom topbar button components display. Notice how between screenshots the badge of the right button no longer works.

RNN version 2.17:
![Selection_058](https://user-images.githubusercontent.com/4223434/58019214-4ab5eb80-7b05-11e9-816c-d2094015b97c.png)

RNN version 2.19:
![Selection_059](https://user-images.githubusercontent.com/4223434/58019259-60c3ac00-7b05-11e9-8989-d6f179b9031f.png)

### Steps to Reproduce / Code Snippets / Screenshots

The badge is an absolute positioned view.
![Selection_061](https://user-images.githubusercontent.com/4223434/58019402-bac47180-7b05-11e9-918f-0d9487689c5f.png)

---
### Environment
* React Native Navigation version: 2.19.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by NweThazin** [comment]
Hi

How to move "Task" title to left beside back button?
