### ISSUE TITLE
Outdated Installation guide

### ISSUE THREAD

**Issue by hugocarreiracosta** [wix/react-native-navigation#5134]
### Issue Description

Please, update de Installation Guide for react-native: "0.59.8" 
The Guide is unclear about versions, some of the files that the guide shows is in another format as well... A user that need to use the lib will have a hard time to figure out the right installation steps with newer versions of react-native, like me. I init my project with the Guide on React Native DOCS (without expo). Thanks

---
### Environment
* React Native Navigation version: 2.20.0
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by N3TC4T** [comment]
This is a open source project, you can always contribute and change the docs/code and improve it if you ever feel it's outdated or it can be better.
