### ISSUE TITLE
Listen to native / default topBar back button navigation event

### ISSUE THREAD

**Issue by eightyfive** [wix/react-native-navigation#5136]
I wonder if this is possible to be notified when the native / default back button in topBar has been pressed?

I tried:

1. `registerNavigationButtonPressedListener`
2. `registerCommandListener`

But with no luck.

I see [this issue](https://github.com/wix/react-native-navigation/issues/4873) is closed, but with no info.

### Steps to Reproduce / Code Snippets / Screenshots

- Setup a simple `Stack` layout
- `push` a screen in stack
- Press back button in topBar
- No event is triggered in `registerNavigationButtonPressedListener`
- No event is triggered in `registerCommandListener`

---
### Environment
* React Native Navigation version: ^2.4.0
* React Native version: 0.59.8
* Platform(s): Android
* Device info: Device (Debug)

**Comment by margaridaDinis** [comment]
You need to give an id to the back button on the component's options, and then it should be registered by `registerNavigationButtonPressedListener`. That worked for me, at least.

This is my component definition: 
```
component: {
  id: screenName,
  name: screenName,
  options: {
    topBar: {
      backButton: {
        id: 'BACK', <----
        showTitle: false,
        icon: backButtonImage
      }
    }
  }
}
```
So now, I get it on `registerNavigationButtonPressedListener`
```
Navigation.events().registerNavigationButtonPressedListener(({ buttonId }) => {
  console.warn(buttonId); // BACK
});
```

**Comment by eightyfive** [comment]
Hey @margaridaDinis thanks for your help, but my question is about the "default topBar back button".

I don't want to add a custom button just for that. I'd like to catch the default back button event.

**Comment by eightyfive** [comment]
Up.

No way to be notified of that react native navigation native event?

**Comment by eightyfive** [comment]
Hi @guyca 

Ok confirmed, RNN does not send the "button pressed" event when using the default topBar back button:
https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java#L347

Is there a reason for that? IMHO it should notify the same way as any other navigation button pressed event, whether it is the default one or a custom one.

What are your thoughts on that?

PS: I always tag you because I don't know another active maintainer of the library, feel free to redirect me to whoever is more appropriate.

**Comment by witalobenicio** [comment]
I can't believe v2 doesn't send the 'back button pressed' event.
In v1 we were able to get that event. 
Really long time since v2 was officially the recommended version, but for me, v1 still looks much better in terms of available functions/actions.

**Comment by eightyfive** [comment]
@guyca Would that be enough? PR https://github.com/wix/react-native-navigation/pull/5342

**Comment by eightyfive** [comment]
Closing.

I found multiple duplicates:
https://github.com/wix/react-native-navigation/issues/4231
https://github.com/wix/react-native-navigation/issues/4776
https://github.com/wix/react-native-navigation/issues/5203

And most importantly:
https://github.com/wix/react-native-navigation/pull/4226#issuecomment-433683885 by @guyca himself

> This change (would) break parity with iOS ⚠️

**Comment by adybuciuman** [comment]
none of the solutions is working for me to get the backButton event
I'm using     

```
"react-native-navigation": "^2.27.1",
"react-native": "^0.59.9",
```
