### ISSUE TITLE
[v2][iOS] Custom Topbar Background not working properly

### ISSUE THREAD

**Issue by FRizzonelli** [wix/react-native-navigation#5138]
### Issue Description

So basically there is an issue with custom component in background of the topbar. Issue is introduced from build **2.17.0**, with previous releases it works! I'm using a bottomTabs layout with a stack in each children. I've already tried to also remove the stack and set only a component for each tab but the bug remains. 
Basically what is happening is in the first tab I'm seeing the custom component, but it's covering title and buttons (probably related to this https://github.com/wix/react-native-navigation/issues/5026). In second and third tab the custom background isn't even rendered.

My setup use one setRoot for the login, and after the login is successful, I set another root with the bottomTabs layout (I've already tried to skip the first setRoot and use only bottomTabs, bug remains).

Sharing my layout and a video of the working build (2.16.0) vs the bugged one (2.17.0). I've digged into the commits, seems related to changes made [here](https://github.com/wix/react-native-navigation/commit/ac60d2fe6ad036528c31954a2997109b06f0c947) or [here](https://github.com/wix/react-native-navigation/commit/28300597ede5de1f08d7b32ba4a9313ffdf4aac1)

I've tried all releases after 2.17.0, and it keeps to be bugged.

Maybe @yogevbd could help us to understand why is this happening?

### Steps to Reproduce / Code Snippets / Screenshots

This is my setRoot
```ts
Navigation.setRoot({
    root: {
        bottomTabs: {
            children: [
                {
                    stack: {
                        children: [
                            {
                                component: {
                                    name: ScreenKeys.dashboardScreen,
                                    options: navigatorStandardOptions({ title: 'Dashboard' })
                                }
                            }
                        ],
                        options: bottomTabStandardOptions({
                            title: 'Dashboard',
                            icon: 'dashboard-outline',
                            selectedIcon: 'dashboard'
                        })
                    }
                },
                {
                    stack: {
                        children: [
                            {
                                component: {
                                    name: ScreenKeys.timesheetScreen,
                                    options: navigatorStandardOptions({ title: 'Presenze' })
                                }
                            }
                        ],
                        options: bottomTabStandardOptions({
                            title: 'Presenze',
                            icon: 'watch-outline',
                            selectedIcon: 'watch'
                        })
                    }
                },
                {
                    stack: {
                        children: [
                            {
                                component: {
                                    name: ScreenKeys.expenseSectionScreen,
                                    options: navigatorStandardOptions({ title: 'Spese' }, undefined, rightButtonAdd())
                                }
                            }
                        ],
                        options: bottomTabStandardOptions({
                            title: 'Spese',
                            icon: 'expense-outline',
                            selectedIcon: 'expense'
                        })
                    }
                }
            ]
        }
    }
});
```

Utility method
```ts
export const navigatorStandardOptions = (opt: DicOptions, leftButtons?: OptionsTopBarButton[], rightButtons?: OptionsTopBarButton[]): Options => {
    return {
        statusBar: {
            style: 'light',
            drawBehind: true
        },
        topBar: {
            height: Platform.select({ android: NAVBAR_HEIGHT }), // Only on Android,
            noBorder: true,
            title: {
                height: Platform.select({ android: NAVBAR_HEIGHT }), // Only on Android
                text: opt.title,
                color: Colors.WHITE
            },
            backButton: {
                color: Colors.WHITE
            },
            background: {
                component: {
                    name: NavigationKeys.topBarBackground
                }
            },
            leftButtons,
            rightButtons
        }
    };
};
```

This is the working situation on 2.16.0
![working](https://user-images.githubusercontent.com/12106217/58236324-f39d5a00-7d42-11e9-8e51-32545b395792.gif)

This is the same code on 2.17.0
![2 17 0](https://user-images.githubusercontent.com/12106217/58236626-96ee6f00-7d43-11e9-900a-7acf5c8b7c0c.gif)

I spent all yesterday to understand the problem, these are all my findings. Any help is really appreciated!

---
### Environment
* React Native Navigation version: From 2.17.0
* React Native version: 0.57.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device and Simulator

**Comment by FRizzonelli** [comment]
@yogevbd Thank you so much for the effort and the almost istant fix! 
It works like a charm, only one small thing. First render of first tab is still missing title (seems to be rendered behind the custom component), if I switch tabs, then it appears.

![title](https://user-images.githubusercontent.com/12106217/58256978-43464a80-7d70-11e9-8e4e-967a6a3d22f2.gif)

**Comment by FernandoTN** [comment]
I'm having the same problem in V6.0.1 and iOS 13.4

With a topBar custom background component the title renders behind it and is un-clickable.

**Comment by snairsumith** [comment]
I have also. Same issue.

**Comment by guyca** [comment]
@FernandoTN @snairsumith We've been doing lots of fixes regarding TopBar layouting and styles in recent version. Please update to 6.4.0 and let us know if your still have issues.
