### ISSUE TITLE
Toggle side menu cause the application to crash with system right to left 

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#514]
### Issue Description

Toggle side menu cause the application to crash with system language right to left on Android (not tested vs IOS),

### Steps to Reproduce / Code Snippets / Screenshots

change the android system language to Arabic or Hebrew (any language with RTL)
call 
 this
            .props
            .navigator
            .toggleDrawer({
                side: 'left', 
                animated: true,
            });

The application will crash.

---
### Environment
* React Native Navigation version: "^2.0.0-experimental.142"
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator and Real device, OS 5/6

**Comment by guyca** [comment]
Hey @Jaafar-abusair 
I wasn't able to reproduce the crash on my device. Can you upload a stack trace perhaps?

also, do you mind using back ticks to format code blocks? [like this](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by Jaafar-abusair** [comment]
Sure, I will past the trace tomorrow, anyway the problem is when you change the language to RTL language, the toggle side menu, side property = 'left' the exception saying the right menu not defined, if i changed the drawer to right the exception will disapear but the menu will not be opened or it will be but hidden because it start from right:0 and it open to the right, so its outside the screen
