### ISSUE TITLE
Trying to install and run with local fork

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#5143]
### Issue Description

I've forked and cloned locally the rnn repo in order to try to solve by myself some of the issues I'm facing with the library.

However, when I install rnn with a local path to the locally cloned repo, the metro bundler crashes with:
```
Loading dependency graph...(node:81833) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-animated
  Paths: /Users/userme/wksp_myproj/myproj-apps-rn59/bin/node_modules/react-native-navigation/node_modules/react-native/Libraries/Animated/release/package.json collides with /Users/userme/wksp_myproj/myproj-apps-rn59/bin/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/userme/wksp_myproj/myproj-apps-rn59/bin/node_modules/metro/node_modules/jest-haste-map/build/index.js:569:17)
    at workerReply (/Users/userme/wksp_myproj/myproj-apps-rn59/bin/node_modules/metro/node_modules/jest-haste-map/build/index.js:641:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:81833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:81833) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:81833) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-animated
  Paths: /Users/userme/wksp_myproj/myproj-apps-rn59/bin/node_modules/react-native-navigation/node_modules/react-native/Libraries/Animated/release/package.json collides with /Users/userme/wksp_myproj/myproj-apps-rn59/bin/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/Users/userme/wksp_myproj/myproj-apps-rn59/bin/node_modules/metro/node_modules/jest-haste-map/build/index.js:569:17)
    at workerReply (/Users/userme/wksp_myproj/myproj-apps-rn59/bin/node_modules/metro/node_modules/jest-haste-map/build/index.js:641:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:81833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

Can anyone help me out so that I could start contributing?

**Comment by zabojad** [comment]
It's a pity the doc mentions only about running the playground locally: https://wix.github.io/react-native-navigation/#/docs/WorkingLocally

**Comment by FRizzonelli** [comment]
@zabojad How are you installing the repo locally? Cloned my fork without issues.

> when I install rnn with a local path to the locally cloned repo

What are you trying to achieve here?

**Comment by zabojad** [comment]
@FRizzonelli 
> @zabojad How are you installing the repo locally? Cloned my fork without issues.
simple executing `yarn add ../../path-to-my-cloned-rnn-repo`

> What are you trying to achieve here?
just using a local version of rnn instead of the latest release I get when installing with `yarn add react-native-navigation`

**Comment by zabojad** [comment]
Let me edit/correct this:

> when I install rnn with a local path to the locally cloned repo

to this:

> after I've installed RNN from a local cloned rnn repo, launching the metro bundler for my app crashes with: (see original post for error msg....)

**Comment by FRizzonelli** [comment]
Ah I see, ye I've same problem, I'm working in node_modules and after that making only the commits on the fork :(

**Comment by zabojad** [comment]
But why do we have this problem ? I've compared what goes into `/node_modules` when installing a release and when installing from local clone and I do not see any visible difference...

**Comment by minhloi** [comment]
When you install a package from a local folder, you basically create a symlink to that folder. Your local react-native-navigation ```node_modules``` includes some dependencies that already exist in your react-native ```node_modules```. The metro bundler does not allow duplicate modules (as of now). This is why you see the error ```Duplicate module name: react-animated```.

When you install from npm directly, it will deduplicate dependencies. If you want to install it locally, here is the only way.
1. Use ```npm pack```  to create a tarball file for your local react-native-navigation
2. In the react-native project, use ```npm install <tarball file>```

**Comment by zabojad** [comment]
Thanks a lot @minhloi, I'll try that. 

I very regularly install packages from a local folder and RNN is the only one I'm having an issue with. I think it's because the rnn repo holds both the library and the playground react app that requires its own node_modules...

IMHO, that should be explained in the "working locally" [part of the docs](https://wix.github.io/react-native-navigation/#/docs/WorkingLocally).
