### ISSUE TITLE
 Infinite loop When TextInput

### ISSUE THREAD

**Issue by ljh740** [wix/react-native-navigation#5146]
Using IQKeyboardManager causes an infinite loop

when click TextInput 
RNNNavigationController causes IQKeyboardManager to cause an infinite loop

code:
```

In  IQKeyboardManager

@implementation UIView (IQ_UIView_Hierarchy)
...
-(UIViewController *)parentContainerViewController
{
...
        while (navController.navigationController) {
            navController = navController.navigationController;
        }
...
}
...
@end

In react-native-navigation
@implementation RNNNavigationController
...

- (UINavigationController *)navigationController {
	return self;
}

...
@end


```
---
### Environment
* React Native Navigation version:0.5.59
* React Native version: V2.0.1937
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by danilobuerger** [comment]
It doesn't make sense to keep this open anymore. 

1) *IQKeyboardManager* has been converted to swift, so things changed
2) We no longer have *RNNNavigationController* or the shown method
3) Nobody was interested to fix this issue for 1,5 years.

If this issue still exists with the current versions of IQKeyboardManager and RNN, feel free to reopen.

**Comment by mateioprea** [comment]
I'm using IQKeyboardManager with RNN and it doesn't cause any infinite loops
