### ISSUE TITLE
[iOS] Instructions on how to initialize the bridge in the AppDelegate

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#515]
### Issue Description

`bridge` which is an instance of `RCTBridge` is needed to send events to the JS side from the native side. Currently, when we update the `AppDelegate` file, we don't initialize the bridge variable due to which the `bridge` is set to nil and hence when we try to send events to the JS side, the app crashes.

I tried using the below lines from the previous code to initialize the bridge

```swift
let rootView = RCTRootView(bundleURL:jsCodeLocation, moduleName: "GalarmApp", initialProperties: nil, launchOptions:launchOptions)
self.bridge = rootView.bridge
```

This prevented the crash but the events were not delivered to the app. Then I realize after some debugging that I need to use the same bridge that RCCManager created in order to be able to receive events on the JS side. When I checked the code for `RCCManager`, I found that there is a method `getBridge` which can be used to get the bridge instance. So, now I have added this to the `AppDelegate` along with other lines of code

```swift
self.bridge = RCCManager.sharedIntance().getBridge()
```

After this, the events were delivered to the JS side. I wanted to confirm if this is the right way of initializing the bridge. One other thing that I found in the `RCCManager` was that there were two methods `sharedInstance` and `sharedIntance` and `sharedIntance` is just calling the `sharedInstance` method. So, not sure if I am supposed to use one over the other.

Could you please review if above is correct and possible add it to the iOS installation wiki for others benefits. I would have sent a PR but I realize that I can't send PRs for wiki.

---
### Environment
* React Native Navigation version: 2.0.0.experimental.142
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
cc @DanielZlotin
