### ISSUE TITLE
set tab bar icon color

### ISSUE THREAD

**Issue by nicoara** [wix/react-native-navigation#5150]
### Issue Description

Is there any way to dynamically set a new tab bar icon AND color?
In my app, I want the icon for the CHAT tab to be changed to red when a new message arrives. 

### Steps to Reproduce / Code Snippets / Screenshots

```
		this.props.navigator.setTabButton(
			{
					tabIndex: 2,
					screen: 'parkour.ChatListScreen',
					title: 'Chat',
					icon: iconsMap[2],
					style: { color: 'red' }
			},
```
the style property does not work at all, the resulting color is yellow. 

---
### Environment
* React Native Navigation version: ^1.1.440
* React Native version: 0.54.4
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): iphone 6.0

**Comment by nicoara** [comment]
what the hell? this is a feature request.

**Comment by nicoara** [comment]
I posted the question, no answer for two weeks now. Please help; https://stackoverflow.com/questions/56390298/set-tabbar-icon-color-in-react-native-navigation

**Comment by guyca** [comment]
Hey there, unfortunately this possible in v1 so I posted an answer for v2

**Comment by nicoara** [comment]
so this is not possible in v1.
I am scared of upgrading to v2. I have a full live app with dozens of screens. 
Can you give me an estimate of how long migrating to v2 could take? 
Thanks

**Comment by guyca** [comment]
@nicoara For a medium size app, migrating could take you between 2-5 days. Then I'd say you might spend another 1-3 days ironing out small issues.

We've migrated the Wix app using [this tool](https://github.com/wix-playground/react-native-navigation-v1-v2-adapter) which lets you use v2 with v1 api. It's not maintained anymore, but should work just fine for the most part. Ping me on discord if you have any questions (I don't work Fridays though)

**Comment by nicoara** [comment]
@guyca 
so changing the icon dynamically works in v1, but not the style ( color).
is there really no other way to solve this style change apart from migrating to v2?
I don't have 3-8 full days to code, I am not paid for this app and have other priorities. 
do you have a UI suggestion to avoid this? 
Thanks a lot.
