### ISSUE TITLE
[v2] Large title animation flicks with pull-to-refresh 

### ISSUE THREAD

**Issue by gabrielvcbessa** [wix/react-native-navigation#5152]
Related to https://github.com/wix/react-native-navigation/issues/3538 posted in Jul 11, 2018 that is being ignored.

Large title doesn't behavior as expected when you have pull to refresh on the screen. I don't know if this is an iOS or react-native-navigation bug.

With small title:

![small title](https://thumbs.gfycat.com/GlaringSilentBlackwidowspider-size_restricted.gif)

With large title:

![large title bug](https://thumbs.gfycat.com/PossibleApprehensiveGuineapig-size_restricted.gif)

---
### Environment
* React Native Navigation version: 2.18.4
* React Native version: 0.59
* Platform(s) (iOS, Android, or both?): iOS

**Comment by juangamnik** [comment]
Does still occur on react native 0.59 and react navigation 2.18.4

**Comment by matpaul** [comment]
I think issue not in RNN, but in RCTScrollView,
There is a method setCustomRefreshControll in RCTScrollView
after change

[self addSubview:_customRefreshControl];
to 
self.refreshControl = customRefreshControl; 

flicks is gone, but pull to refresh show only once(( other offset etc logic failed after change

**Comment by chrise86** [comment]
Not stale.

**Comment by chrise86** [comment]
Still not stale.

**Comment by kneza23** [comment]
Still not stale :(, really sad as we can't use large title with pull down refresh (90% of the lists have that)

**Comment by juangamnik** [comment]
Still not stale

**Comment by Rybachello** [comment]
not stale

**Comment by guyca** [comment]
As part of an effort by @yogevbd to address all large title issues, he opened a [PR with a fix to react-native](https://github.com/facebook/react-native/pull/28236/files). Hopefully it will be merged soon 🙏

**Comment by bdrobinson** [comment]
Looks like it's been merged now right? Nice one! https://github.com/facebook/react-native/pull/28236 Thanks for all the efforts to get it fixed, what else needs to happen for this to work in RNN?

**Comment by guyca** [comment]
This has been fixed by @yogevbd 's PR to react native, closing as there's nothing else to do in RNN.
