### ISSUE TITLE
Blank white screen on back handler 

### ISSUE THREAD

**Issue by harryharihar** [wix/react-native-navigation#5156]
### Issue Description

whenever i clicked on back button it shows blank  white previous screen . I am doing hide and show bottom bar also

MainScreen for hide bottom bar:
const homeStackNavigator = createStackNavigator(
  {
    Home: {
      screen: HomeScreen,
    },
    HomeWeb:{
      screen:HomeWebScreen,
    },
    Category: {
      screen: CategoriesScreen,
    }, CommonWebview: {
      screen: CommonWebviewScreen,
    }, Search: {
      screen: SearchScreen,
    }

  },
  {
    headerMode: 'none',

  }
);

 homeStackNavigator.navigationOptions=({navigation}) =>{
    let tabBarVisible = true;
    if (navigation.state.index > 0) {
      tabBarVisible = false;
    }
  
    return {
      tabBarVisible,
    };
  }

//HomeWebScreen 
 componentDidMount() {

    if (Platform.OS == "android") {
      didFocusSubscription = this.props.navigation.addListener(
        'didFocus',
        payload => {
          handleAndroidBackButton(this.goBack);
        }
      );
      didBlurSubscription = this.props.navigation.addListener(
        'didBlur',
        payload => {
          removeAndroidBackButtonHandler();
        }
      );
    }
  }

  componentWillUnmount() {
    if (Platform.OS == "android") {
      didFocusSubscription.remove();
      didBlurSubscription.remove();
    }
  }
onNavigationStateChange = (navState) => {

    this.setState({
      canGoBack: navState.canGoBack,
      canGoForward: navState.canGoForward,

    })
  }
  goBack = () => {

    if (this.state.canGoBack) {
      this.refWeb.goBack();
      console.log("Going Back...");
      return true;
    } else {
      this.props.navigation.goBack();

    }
  }

<WebView
          ref={webView => { this.refWeb = webView; }}
          source={
            {
              uri: url,
             
            }
          }

          javaScriptEnabled={true}
          //For the Cache
          domStorageEnabled={true}
          //View to show while loading the webpage
          renderLoading={() => this.DotIndicatorLoadingView()}
          //Want to show the view or notinjectedJavaScript={injectScript}
          onMessage={this.onMessage}
          automaticallyAdjustContentInsets={true}
          startInLoadingState={true}
          onNavigationStateChange={this.onNavigationStateChange}
        />

### Environment
* react-navigation: "^3.2.3",
* react-native-cli: 2.0.1
*react-native: 0.57.8
* Device info : Android
Platform : Windows

**Comment by harryharihar** [comment]
It takes double click on back button  to load previous screen

**Comment by 3luyka** [comment]
wrong repo.
