### ISSUE TITLE
[IOS] tabBarHidden: true, not working with IOS

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#516]
### Issue Description

tabBarHidden: true, not working with IOS

### Steps to Reproduce / Code Snippets / Screenshots

- set tabBarHidden : true in Navigation.startTabBasedApp({ appStyle : {}})
for Android is working as expected but not for IOS
---
### Environment
* React Native Navigation version: 2.exp.142
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
`appStyle` is not available on iOS yet.

**Comment by Jaafar-abusair** [comment]
Please tell me there is another way to hide the navigation bar

**Comment by guyca** [comment]
You can specify `tabBarHidden` in `navigatorStyle`.
Or call

```js
this.props.navigator.toggleTabs({
      to:  'hidden'
    });
```
