### ISSUE TITLE
mergeOptions doesn't work on leftButtonColor or rightButtonColor

### ISSUE THREAD

**Issue by falsesheep** [wix/react-native-navigation#5161]
### Issue Description

mergeOptions doesn't work on leftButtonColor or rightButtonColor

### Steps to Reproduce / Code Snippets / Screenshots

1. Set leftButtonColor and rightButtonColor in options
```
static options(passProps) {
    return {
       topBar: {
        leftButtonColor: "white",
        rightButtonColor: "white",
        title: {
          text: 'Home',
          color: 'white'
        },
        leftButtons: [
          {
            id: 'btnMsgL',
            icon: require('resources/icon_message.png')
          }
        ],
        rightButtons: [
          {
            id: 'btnMsgR',
            icon: require('resources/icon_message.png')
          }
        ],
      }
    }
}
```

2. Then change the leftButtonColor and rightButtonColor when triggered. 
```
Navigation.mergeOptions(this.props.componentId,{
      topBar: {
        leftButtonColor: 'black',
        rightButtonColor: 'black',
        title: {
          color: 'black'
        },
      }
    });
```

3. The left button and the right button color remains white, while they should be black.
The title color changed. Which means this code is executed.

Before trigger:
<img width="333" alt="屏幕快照 2019-05-28 下午4 38 28" src="https://user-images.githubusercontent.com/4600822/58463806-1d051e00-8167-11e9-966a-9d33f6e8f687.png">

After trigger:
<img width="333" alt="屏幕快照 2019-05-28 下午4 38 36" src="https://user-images.githubusercontent.com/4600822/58463825-242c2c00-8167-11e9-89fd-dd2c11ef0122.png">

---
### Environment
* React Native Navigation version: 2.20.0
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X 11.4 Simulator

**Comment by bneigher** [comment]
still seems to be an issue

**Comment by JimTeva** [comment]
Still an issue in 3.2.0-snapshot.524
