### ISSUE TITLE
mergeOptions changes the color of bottomBar on Android

### ISSUE THREAD

**Issue by steve228uk** [wix/react-native-navigation#5168]
### Issue Description

On Android, when using `Navigation.mergeOptions` to change the tab bar icon, the bottom bar colour is changed to white.

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.mergeOptions(this.props.componentId, {
    bottomTab: {
        icon
    }
});
```

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Debug + Release

**Comment by steve228uk** [comment]
![Screenshot_1559228523](https://user-images.githubusercontent.com/1169297/58642030-56b75f80-82f4-11e9-9fa5-7afeaed31635.png)
![Screenshot_1559228519](https://user-images.githubusercontent.com/1169297/58642031-56b75f80-82f4-11e9-84e2-f1022527292c.png)

**Comment by ItsNoHax** [comment]
Hi @steve228uk,

Before I accept this as a bug, would you be able to create a fork of this project where you create a branch reproducing this problem in the playground app?

**Comment by nuschris** [comment]
I having this issue, please reopen it.

**Comment by nuschris** [comment]
I found the way to fix it! Just add this line right after line 81 in file BottomTabsPresenter.java.

bottomTabs.setDefaultBackgroundColor(Color.parseColor("#E8E3E4")); //parse the color u want

![Screen Shot 2019-11-01 at 1 50 13 PM](https://user-images.githubusercontent.com/49548608/68007563-8eb13d00-fcae-11e9-9b90-9f41f2f23793.png)

**Comment by manuhook** [comment]
Can we reopen this issue @guyca ? it's still happening on v3.

Doing a simple 
```
    Navigation.mergeOptions(componentId, {
      bottomTab: {
        text: "blabla",
      },
});
```
will reset bottomTabs backgroundColor to white.

Thank you !
