### ISSUE TITLE
getLaunchArgs is not a function

### ISSUE THREAD

**Issue by harleenarora** [wix/react-native-navigation#5169]
**Issue Description**

Calling the following:

`Navigation.getLaunchArgs()`

Error::
`ExceptionsManager.js:74 TypeError: this.nativeCommandsModule.getLaunchArgs is not a function`

I have try to get the all stack values using this, but I have got a error.

**Environment**
React Native Navigation version:2.21.0
React Native version: 0.59.8

**Comment by L-Yeiser** [comment]
This is still an issue
