### ISSUE TITLE
Navbar – using drawUnderNavbar and navBarTransparent only work when navBarBlur is set to true

### ISSUE THREAD

**Issue by florianbepunkt** [wix/react-native-navigation#517]
navBarTransparent & drawUnderNavbar property only takes effect when I set navBarBlur to true as well.

So basically I have these options

```
static navigatorStyle = {
	drawUnderNavBar: true,
	navBarTransparent: true,
	navBarBlur: true,
};
```

this renders the navbar transparent, blurred and the content is drawn underneath the navbar.

when I change it to this

```
static navigatorStyle = {
	drawUnderNavBar: true,
	navBarTransparent: true,
};
```

the content is not drawn underneath the navbar. I just have a white navbar and the content below.

**Comment by guyca** [comment]
Thanks for reporting. Can you please add screenshots so I can better understand the issue?

**Comment by florianbepunkt** [comment]
Okay, just for clarification. I updated RNN to 1.5.1 (via npm not github). This happens on ios.
```
static navigatorStyle = {
	drawUnderNavBar: true,
	navBarTransparent: true,
	navBarBlur: true,
};
```

looks like this 
![simulator screen shot 30 11 2016 22 46 45](https://cloud.githubusercontent.com/assets/8314202/20772782/1b1da4b6-b74f-11e6-901e-e140c270ccac.png)

while

```
static navigatorStyle = {
	drawUnderNavBar: true,
	navBarTransparent: true,
};
```

looks like this

![simulator screen shot 30 11 2016 22 47 03](https://cloud.githubusercontent.com/assets/8314202/20772794/2c090586-b74f-11e6-9a14-3c2a855569de.png)

exspected behaviour would be, that the second set of arguments would still cause the view to be drawn underneath the navbar.

the full code of my component is here: http://pastebin.com/djFjaaPm

**Comment by guyca** [comment]
I think you need to add [navBarTranslucent: true](https://github.com/wix/react-native-navigation/wiki/Styling-the-navigator#style-object-format)

cc @gran33

**Comment by florianbepunkt** [comment]
@guyca thank you, this works. although the syntax here is a bit confusing imo ;)

**Comment by guyca** [comment]
@florianbepunkt I agree
cc @DanielZlotin It seems like some properties are mandatory for other style properties to work properly. Apparently on iOS one needs to set `navBarTranslucent: true` in order for `drawUnderNavBar: true, navBarTransparent: true` to work as intended.
Maybe set `navBarTranslucent: true` programmatically in `platformSpecific.ios.js`?

**Comment by DanielZlotin** [comment]
I don't mind this quick fix for now, but maybe we need to define better
styling for the TopBar, such that it will not be derived from a collection
of boolean flags? Any input on this is welcome in #468

**Comment by guyca** [comment]
Sounds great. Thanks @DanielZlotin
