### ISSUE TITLE
[V2][Android] Build error with react native v0.60.0 RC 0

### ISSUE THREAD

**Issue by Frekansapp** [wix/react-native-navigation#5171]
### Issue Description

I update react native version to v0.60.0-rc0 and i run react-native run-android command i am getting this build errors. I think they change some files location with new version of react native.

### Steps to Reproduce / Code Snippets / Screenshots

> Task :react-native-navigation:compileReactNative57DebugJavaWithJavac FAILED
99 actionable tasks: 1 executed, 98 up-to-date
/home/rn/Desktop/Denetmen/denetmenapp/node_modules/react-native-navigation/lib/android/app/src/reactNative57/java/com/reactnativenavigation/react/SyncUiImplementation.java:12:
 error: cannot find symbol
import com.facebook.react.uimanager.common.MeasureSpecProvider;
                                          ^
  symbol:   class MeasureSpecProvider
  location: package com.facebook.react.uimanager.common
/home/rn/Desktop/Denetmen/denetmenapp/node_modules/react-native-navigation/lib/android/app/src/reactNative57/java/com/reactnativenavigation/react/SyncUiImplementation.java:13: error: cannot find symbol
import com.facebook.react.uimanager.common.SizeMonitoringFrameLayout;
                                          ^
  symbol:   class SizeMonitoringFrameLayout
  location: package com.facebook.react.uimanager.common
/home/rn/Desktop/Denetmen/denetmenapp/node_modules/react-native-navigation/lib/android/app/src/reactNative57/java/com/reactnativenavigation/react/SyncUiImplementation.java:65: error: cannot find symbol
    public <T extends SizeMonitoringFrameLayout & MeasureSpecProvider> void registerRootView(T rootView, int tag, ThemedReactContext context) {
                      ^
  symbol:   class SizeMonitoringFrameLayout
  location: class SyncUiImplementation
/home/rn/Desktop/Denetmen/denetmenapp/node_modules/react-native-navigation/lib/android/app/src/reactNative57/java/com/reactnativenavigation/react/SyncUiImplementation.java:65: error: cannot find symbol
    public <T extends SizeMonitoringFrameLayout & MeasureSpecProvider> void registerRootView(T rootView, int tag, ThemedReactContext context) {
                                                  ^
  symbol:   class MeasureSpecProvider
  location: class SyncUiImplementation
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative57DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version:  v0.60.0-rc0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device 5.0 Debug

**Comment by cassioseffrin** [comment]
I am experiencing the same issue

**Comment by Frekansapp** [comment]
Hi @cassioseffrin, did you solve this problem?

**Comment by cassioseffrin** [comment]
@Frekansapp, I ended up coming back to react-native@0.59.4. It seems that RNN2 is not yet ready for the RN60

**Comment by ryzhak** [comment]
The same issue in my environment:
React Native Navigation version: 2.22.3
React Native version: v0.60.3
Platform(s) (iOS, Android, or both?): Android
Device info (Simulator/Device? OS version? Debug/Release?): Device 8.1 Debug

**Comment by Jom-J** [comment]
I too have tha same...  any solutions??

**Comment by nethergrim** [comment]
I'm having the same issue

**Comment by cassioseffrin** [comment]
@Frekansapp @ryzhak  @nethergrim  @Jom-J 

I have succeeded with this version: #npm i react-native-navigation@3.0.0-alpha.6

for iOS I have used pod install inside ios folder instead traditional link libraries.
for android I followed the oficial docs, plus the follows configs:

app/build.grade
android {
  ...
    defaultConfig {
               ...
               missingDimensionStrategy "RNN.reactNativeVersion", "reactNative60"
     }
}


build.grade
...
subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                variantFilter { variant ->
                    def names = variant.flavors*.name
                    if (names.contains("reactNative51") || names.contains("reactNative55")||names.contains("reactNative56")||names.contains("reactNative57")||names.contains("reactNative57_5")||names.contains("reactNative57WixFork")||names.contains("ReactNative57Wix")) {
                        setIgnore(true)
                    }
                }
            }
        }

    }
}

**Comment by losheredos** [comment]
Same issue.. I'm trying your suggestion @cassioseffrin but still cant do it..

**Comment by gblue1223** [comment]
Same here
