### ISSUE TITLE
passProps passes nothing

### ISSUE THREAD

**Issue by Venipa** [wix/react-native-navigation#5177]
### Issue Description

passProps is null on component side.

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.push('AppRoot', {
              component: {
                id: 'show-wallpaper',
                name: 'show-wallpaper',
                passProps: {
                  wallpaper: x
                }
              }
            });```

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): OnePlus 7 Pro, Android P, Debug

**Comment by guyca** [comment]
Hey there, both unit and e2e related to passProps pass. Are you able to reproduce in the playground app?

**Comment by Venipa** [comment]
Solved this issue by using redux but the props didn't passed because of the react native paper libs paper provider

**Comment by guyca** [comment]
Interesting... how did you integrate with paper? Something like this should work

```js
import { Provider as PaperProvider } from 'react-native-paper';

Navigation.registerComponent('show-wallpaper', () => (props) => (
  <PaperProvider>
    <WallpaperScreen {...props} />
  </PaperProvider>
), () => WallpaperScreen);

```

**Comment by Venipa** [comment]
Thanks I'll try that

**Comment by marcorm** [comment]
Hi @guyca can you help understand how i can integrate PaperProvider with `registerComponentWithRedux`? I can't find a way.. thanks a lot!

**Comment by guyca** [comment]
@marcorm `registerComponentWithRedux` is obsolete - you should use `registerComponent` as described in the [docs](https://wix.github.io/react-native-navigation/api/component#registering-a-component-wrapped-with-providers) 👍
