### ISSUE TITLE
[iOS] set topBar leftButton with custom component via mergeOptions crashes

### ISSUE THREAD

**Issue by MarianPalkus** [wix/react-native-navigation#5180]
Hi, 
thanks for publishing/maintaining this library and your work!

### Issue Description

I try to set a custom component to `topBar.leftButtons` via `mergeOptions` (maybe this issue is related to side menus):

```js
const CustomTopBarButton = ( )=> {
  return <Text>TEST BUTTON</Text>
}

Navigation.registerComponent('CUSTOM_TOP_BAR_BUTTON', () => CustomTopBarButton);

Navigation.mergeOptions(this, {
      topBar: {
        leftButtons: [
          {
            id: 'CUSTOM_BUTTON_ID',
            component: {
              name: 'CUSTOM_TOP_BAR_BUTTON',
            }
          }
        ],
      }
    })
```

```
Exception 'NSLayoutConstraint for (null): Constraint must contain a first layout item' was thrown while invoking mergeOptions on target RNNBridgeModule with params (
    SideMenuCenter,
        {
        topBar =         {
            leftButtons =             (
                                {
                    component =                     {
                        componentId = CustomComponent19;
                        name = "CUSTOM_TOP_BAR_BUTTON";
                    };
                    id = "CUSTOM_BUTTON_ID";
                }
            );
        };
    },
    694,
    695
)
callstack: (
	0   CoreFoundation                      0x000000010427f1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000102964735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010427f015 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010258bfbd ResolveConstraintArguments + 464
	4   Foundation                          0x000000010258c2cb +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:] + 80
	5   playground                          0x000000010058f2bd -[RNNUIBarButtonItem init:withCustomView:] + 397
	6   playground                          0x00000001005d06ee -[RNNNavigationButtons buildButton:defaultStyle:insets:] + 2478
	7   playground                          0x00000001005cf67f -[RNNNavigationButtons setButtons:side:animated:defaultStyle:insets:] + 639
	8   playground                          0x00000001005cf27c -[RNNNavigationButtons applyLeftButtons:rightButtons:defaultLeftButtonStyle:defaultRightButtonStyle:] + 492
	9   playground                          0x00000001005939b8 -[RNNViewControllerPresenter mergeOptions:currentOptions:defaultOptions:] + 6360
	10  playground                          0x000000010053aba8 -[UIViewController(LayoutProtocol) mergeOptions:] + 200
	11  playground                          0x000000010053ac06 -[UIViewController(LayoutProtocol) mergeOptions:] + 294
	12  playground                          0x0000000100545d0c -[RNNRootViewController mergeOptions:] + 268
	13  playground                          0x00000001005bb98d -[RNNCommandsHandler mergeOptions:options:completion:] + 461
	14  playground                          0x000000010057b24a -[RNNBridgeModule mergeOptions:options:resolver:rejecter:] + 362
```

### Steps to Reproduce / Code Snippets / Screenshots
The issue is reproducible in playgrounds app on `playground/src/screens/SideMenuCenterScreen.js` (branch with reproducable issue can be found here https://github.com/MarianPalkus/react-native-navigation/tree/issue/ios-merge-options-top-bar-left-buttons-custom-components)

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): e.g. Simulator iPhone X iOS 12.1

### Possbile Solution
When investigating this issue, it seems that there is no `componentRegistry`passed to `RNNNavigationButtons`.

We could fix this issue by the following changes:

```diff
- RNNSideMenuChildVC *sideMenuChild = [[RNNSideMenuChildVC alloc] initWithLayoutInfo:layoutInfo creator:_creator options:options defaultOptions:_defaultOptions presenter:[[RNNViewControllerPresenter alloc] init] eventEmitter:_eventEmitter childViewController:childVc type:type];
+ RNNSideMenuChildVC *sideMenuChild = [[RNNSideMenuChildVC alloc] initWithLayoutInfo:layoutInfo creator:_creator options:options defaultOptions:_defaultOptions presenter:[[RNNViewControllerPresenter alloc] initWithComponentRegistry:_componentRegistry] eventEmitter:_eventEmitter childViewController:childVc type:type];

```

If this changes are reasonable, we will happily create a pull request.

**Comment by odeyatwi** [comment]
happend to me too, cannot use side menu right now because of it

**Comment by Batistleman** [comment]
Yes, please create a pull request for this, fixes the problem for me! 🎉

**Comment by MarianPalkus** [comment]
Pull request is created: #5189

**Comment by odeyatwi** [comment]
it's look like the main change is not in #5189 
i tried to update the version to 2.21.1, but still didn't work.

manually change it:
**from**: RNNSideMenuChildVC *sideMenuChild = [[RNNSideMenuChildVC alloc] initWithLayoutInfo:layoutInfo creator:_creator options:options defaultOptions:_defaultOptions presenter:[[RNNViewControllerPresenter alloc] init] eventEmitter:_eventEmitter childViewController:childVc type:type];
**to**: RNNSideMenuChildVC *sideMenuChild = [[RNNSideMenuChildVC alloc] initWithLayoutInfo:layoutInfo creator:_creator options:options defaultOptions:_defaultOptions presenter:[[RNNViewControllerPresenter alloc] initWithComponentRegistry:_componentRegistry] eventEmitter:_eventEmitter childViewController:childVc type:type];

and its works.. can you add this particular change to master?

**Comment by MarianPalkus** [comment]
Do you mean this line on master:
https://github.com/wix/react-native-navigation/blob/35a19b5f687b89dc414e65184995ebc69f847704/lib/ios/RNNControllerFactory.m#L191

To me it looks like the line is changed as expected, but it seems not to be included in version 2.21.1.

But there are two other instantiations of `RNNViewControllerPresenter`:
- https://github.com/wix/react-native-navigation/blob/35a19b5f687b89dc414e65184995ebc69f847704/lib/ios/RNNControllerFactory.m#L126
- https://github.com/wix/react-native-navigation/blob/35a19b5f687b89dc414e65184995ebc69f847704/lib/ios/RNNControllerFactory.m#L164

which should be checked, since the issue might occur here as well. But this seems to be out of scope of this issue.

From my side this issue is resolved now.

@odeyatwi if there are still issues, please comment and we can reopen this issue.

**Comment by odeyatwi** [comment]
yes, i mean this line.

i don't know about the other two lines, but the first one did solve my problem, so it will be great if it will be in the new version.

so can you reopen the issue and put this change in the release library version?

**Comment by MarianPalkus** [comment]
I think it will be included in the next release version.

As a workaround/hack for now, you could use a `postinstall` script, maybe something like this:

`find . -name 'RNNControllerFactory.m' -exec sed -i -e 's/presenter\:\[\[RNNViewControllerPresenter alloc\] init\]/presenter\:\[\[RNNViewControllerPresenter alloc\] initWithComponentRegistry\:\_componentRegistry\]/g' '{}' \;`
