### ISSUE TITLE
PassProps does not listen to changes

### ISSUE THREAD

**Issue by igortupini** [wix/react-native-navigation#5181]
### Issue Description

Passed props on `passProps: {}` dont change when the parent value changes. The passed value seems to be static. 

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Both / Both

**Comment by ItsNoHax** [comment]
This is correct, the passProps are cloned to ensure immutability.

In most cases you pass the unique identifier of a entity and have that screen listen to your state management (redux/mobx/react context).
