### ISSUE TITLE
[Android] Nested TouchableOpacity in overlay screen don't work

### ISSUE THREAD

**Issue by fjmorant** [wix/react-native-navigation#5184]
### Issue Description

On Android only, setting option interceptTouchOutside to false makes onPress of TouchableOpacity components to not work in child components. On iOS it works perfectly.

### Steps to Reproduce / Code Snippets / Screenshots

```
<View style={styles.root}>
        <Text style={styles.title} testID={OVERLAY_ALERT_HEADER}>Test view nested touchables</Text>
        <Button title='Dismiss' testID={DISMISS_BTN} onPress={this.dismiss} />

        <TouchableOpacity style={{ backgroundColor: 'red' }} onPress={() => alert('Touch parent')}>
          <View style={{ height: 300, width: 300, alignItems: 'center', justifyContent: 'center' }}>
            <TouchableOpacity style={{ margin: 5, height: 90, width: 90, backgroundColor: 'orange', alignItems: 'center', justifyContent: 'center' }} onPress={() => alert('Touch child')}>
              <Text>favourites</Text>
            </TouchableOpacity>

            <TouchableOpacity style={{ margin: 5, height: 90, width: 90, backgroundColor: 'orange', alignItems: 'center', justifyContent: 'center' }} onPress={() => alert('Touch child')}>
              <Text>notifications</Text>
            </TouchableOpacity>

            <TouchableOpacity style={{ margin: 5, height: 90, width: 90, backgroundColor: 'orange', alignItems: 'center', justifyContent: 'center' }} onPress={() => alert('Touch child')}>
              <Text>settings</Text>
            </TouchableOpacity>

          </View>
        </TouchableOpacity>
      </View>
```

Example https://github.com/wix/react-native-navigation/pull/5182

![58910106-a2ab3f80-870c-11e9-8c2e-bf418245deff](https://user-images.githubusercontent.com/6560136/58943338-6c56da00-8777-11e9-9f1e-8a3794e53cdc.png)

![58910120-a939b700-870c-11e9-8d0e-ce4f3a75ed2e](https://user-images.githubusercontent.com/6560136/58943347-711b8e00-8777-11e9-8d15-ed4a9c544baa.png)

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung S9 Android 8/9 Debug/Release

**Comment by fjmorant** [comment]
Hi @guyca,

This is a full description of the problem I am having with TouchableOpacity, only the parent receives touches.

Thanks

**Comment by fjmorant** [comment]
Hi @guyca ,

In ` OverlayTouchDelegate`,

if in this method: 

```
    @VisibleForTesting
    public boolean handleDown(MotionEvent event) {
        TouchLocation location = getTouchLocation(event);
        if (location == TouchLocation.Inside) {
            reactView.dispatchTouchEventToJs(event);
            return true;
        }
        return interceptTouchOutside.isFalseOrUndefined();
    }
```

when the touch is inside instead of return false as before I return true, it works fine, I am not sure the consequences of this, I have checked this docs https://developer.android.com/training/gestures/viewgroup

And returning true means that the touch event will not pass to its children but in regards, the RN view we are doing this `reactView.dispatchTouchEventToJs(event);` so it should be ok

**Comment by fjmorant** [comment]
Hi @guyca,

Any chance of having a look at this issue?

Thx

**Comment by fjmorant** [comment]
Hi @guyca ,

Any luck with this issue?

Thanks

**Comment by nezaidu** [comment]
https://stackoverflow.com/questions/31866671/how-to-stop-touch-event-propagation-in-react-native
second answer, wrap your touchables in a touchable without a handler with opacity set to 1

**Comment by fjmorant** [comment]
Thx @nezaidu I will try it

**Comment by schumannd** [comment]
It seems like this should still be fixed so that Android and iOS have the same behavior.

**Comment by marf** [comment]
The problem hasn't be fixed yet, Android and iOS have different behaviors.
Any chance of a fix?
