### ISSUE TITLE
App Crash when trying to push to a new screen while using bottomTabs 

### ISSUE THREAD

**Issue by fedu44** [wix/react-native-navigation#5185]
### Issue Description

[ENTER DESCRIPTION HERE]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by markhomoki** [comment]
Without any code or information, less likely anyone will be able to help you out.
