### ISSUE TITLE
Style the Navigation Bar Based on Data?

### ISSUE THREAD

**Issue by joncursi** [wix/react-native-navigation#519]
All style parameters are done in `static`, which makes it impossible to style the NavigationBar based on data that comes back from an API request because static methods are unaware of `this`.

How would you suggest styling the nav bar within a component when the style is dependent on an API response, which can be different every time (i.e. theming the navbar color based on a user's profile)?

**Comment by guyca** [comment]
cc @DanielZlotin

**Comment by dillonykyang** [comment]
is there a way to style the nav bar at runtime? instead of declaring static.

**Comment by guyca** [comment]
You can pass navigatorStyle when you call push/showModal

**Comment by DanielZlotin** [comment]
yeah we should add support for both static style and dynamically calling Navigation.on(screenId).setStyle({...}). it's in the roadmap
