### ISSUE TITLE
Black Screen Issue when navigating screens back and forth

### ISSUE THREAD

**Issue by rjx444** [wix/react-native-navigation#5191]
### Issue Description

Navigating back and forth to every page causes the app to hang and just show a black screen without having an error

### Steps to Reproduce / Code Snippets / Screenshots

The issue can be produced by navigating the screens using pop and push. Also when going back to the main page using popToRoot. I've been stuck with issue already and can't seem to find the solution. 

---
### Environment
* React Native Navigation version: ^2.21.0
* React Native version: 0.57.7
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Any Version but currently testing with Android 6.0, Release

**Comment by archana-iron** [comment]
I am having the same issue using react native navigation version::: 2.21.1

**Comment by archana-iron** [comment]
Do you have any solution?? Please help!

**Comment by atrofimenko** [comment]
Hello! I still have this issue with current version of package on android < 9.
There is a problem with onLayout in pushed component, it is not called after Navigation.push
