### ISSUE TITLE
TopBar custom title component not rendering in android

### ISSUE THREAD

**Issue by RatebSeirawan** [wix/react-native-navigation#5195]
### Issue Description

TopBar custom title component not rendering in android but working fine in IOS, the component seems to flash and disappear in a split second when I refresh the application in the emulator

### Steps to Reproduce / Code Snippets / Screenshots

```
  componentDidMount() {
    if(Platform.OS !== 'android') {
      Navigation.mergeOptions(this.props.componentId, {
        topBar: {
          visible: true,
          animate: true,
          hideOnScroll: true,
          drawBehind: false,
          title: {
            component: {
              name: SCREENS.HomeTopBar,
              passProps: {
                stackId: this.props.componentId
              },
              alignment: 'fill'
            }
          },
        },
      });
    }
    else {
      Navigation.mergeOptions(this.props.componentId, {
        topBar: {
          visible: true,
          animate: true,
          hideOnScroll: false,
          drawBehind: false,
          leftButtons: {
            id: CID.searchIcon,
            icon: this.props.icons[1],
          },
          title: {
            component: {
              name: SCREENS.HomeTopBar,
              passProps: {
                handleSearchClick: () => this.handleSearchClick
              }
            }
          }
        }
      });
    }
  }
```

---
### Environment

* React Native Navigation version: ^2.12.0
* React Native version: ^0.58.6
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device and Emulator/ Android/ Debugging

**Comment by RatebSeirawan** [comment]
I've seen many issues related to mine, and the solutions suggest using the background attribute to render the component, but I have clickable buttons in the component and the background component comes as a pure inactive background so!

**Comment by emilioheinz** [comment]
I've the same issue, that still relevant.
