### ISSUE TITLE
[V2][Android] Initial BottomTabs background color is always white 

### ISSUE THREAD

**Issue by danielang** [wix/react-native-navigation#5198]
### Issue Description

The initial BottomTabs background color is always white.

### Steps to Reproduce / Code Snippets / Screenshots

`Navigation.setRoot` with a bottom tabs layout with an different background color than white:
```js
bottomTabs: {
    backgroundColor: '#333333',
}
```

### Solution/Fix
Due to the fact that AHBottomNavigation sets the `defaultBackgroundColor` (white) on item creation. RNN should set the `defaultBackgroundColor` in the `BottomTabsPresenter` with the corresponding setter `setDefaultBackgroundColor` in lines [80](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsPresenter.java#L80) and [141](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/presentation/BottomTabsPresenter.java#L141).

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): In every configuration

**Comment by danielang** [comment]
This issue is not resolved!

**Comment by guyca** [comment]
Should be fixed in 57eb0db7da6d69c784a9b0cd5672a563901738a9
