### ISSUE TITLE
[V2] support for horizontally scrollable top tab bar

### ISSUE THREAD

**Issue by ritz078** [wix/react-native-navigation#5202]
### Issue Description

It becomes really hard when there are multiple tabs. It will be great if we can scroll horizontally.

<img width="468" alt="Screenshot 2019-06-12 at 6 55 49 PM" src="https://user-images.githubusercontent.com/5389035/59354921-b7f32000-8d43-11e9-8072-34455c346fd1.png">

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by nirvo** [comment]
I have the same problem. 
With react-navigation, I did it using  scrollEnabled: true, it works perfectly. With react-navigation I don't know how. there is no documentation !

**Comment by syedabuthahirm** [comment]
In v2 there is no option to configure topTabs like v1. 
Related to  #5072

**Comment by syedabuthahirm** [comment]
In [v1 scroll mode option native code](https://github.com/wix/react-native-navigation/blob/57caacddfc5422c00f41b32e031a732ab503b7dc/android/app/src/main/java/com/reactnativenavigation/views/TopTabs.java#L64) but in v2 there is no configuration available at this time 😞.

**Comment by nirvo** [comment]
> In [v1 scroll mode option native code](https://github.com/wix/react-native-navigation/blob/57caacddfc5422c00f41b32e031a732ab503b7dc/android/app/src/main/java/com/reactnativenavigation/views/TopTabs.java#L64) but in v2 there is no configuration available at this time 😞.

Crazy 😞
What is the difference between RNN1 and RNN2 ? 
Can I use "react-navigation": "^3.9.1" and React Native Navigation 2 in the same time ?

**Comment by ritz078** [comment]
> > In [v1 scroll mode option native code](https://github.com/wix/react-native-navigation/blob/57caacddfc5422c00f41b32e031a732ab503b7dc/android/app/src/main/java/com/reactnativenavigation/views/TopTabs.java#L64) but in v2 there is no configuration available at this time 😞.
> 
> Crazy 😞
> What is the difference between RNN1 and RNN2 ?
> Can I use "react-navigation": "^3.9.1" and React Native Navigation 2 in the same time ?

I think mixing navigators will only make things harder. I am using [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view) (that is used by react-navigation internally) for the top tabs and the bottom tabs are from react-native-navigation.

**Comment by t1amat9409** [comment]
@ritz078 I can relate... I'm also using react-navigation inside my screens... the performance is not that great

**Comment by ritz078** [comment]
relevant

**Comment by etienneMobileSpot** [comment]
Can we have any intel about a roadmap on this feature ? 
Or is topTabs not maintained anymore ?

**Comment by hb12DevTn** [comment]
horrizontal scroll works with react-native-navigation, you have just to manually render TabBar and and set scrollEnabled to true.
A basic example:
`<TabView
        navigationState={this.state}
        renderTabBar={props => {
          return <TabBar {...props} scrollEnabled />;
        }}
        renderScene={SceneMap({
           first: FirstRoute,
           second: SecondRoute,
           ...
        })}
        onIndexChange={index => this.setState({ index })}
        initialLayout={{ width: Dimensions.get('window').width }}
        swipeEnabled
      />
`

**Comment by etienneMobileSpot** [comment]
> horrizontal scroll works with react-native-navigation, you have just to manually render TabBar and and set scrollEnabled to true.
> A basic example:
> `<TabView navigationState={this.state} renderTabBar={props => { return <TabBar {...props} scrollEnabled />; }} renderScene={SceneMap({ first: FirstRoute, second: SecondRoute, ... })} onIndexChange={index => this.setState({ index })} initialLayout={{ width: Dimensions.get('window').width }} />`

You are talking of react-native-tab-view here... We are talking of react-native-navigation topTabs.
