### ISSUE TITLE
setRoot transition white background

### ISSUE THREAD

**Issue by fatihmert** [wix/react-native-navigation#5211]
### Issue Description

Is there a solution to the white background in setRoot transitions ? It's pretty uncomfortable for me. I thought it was due to the speed of the phone and tested it on different devices. I'm right but relatively. When I increased the RAM (4096mb), it showed a slight improvement. 

Watch it: https://streamable.com/atkjp

I can avoid some of the default settings with animations. It's not a professional solution for me. Because this white background looks up to 1 second then the loading bar appears in the application. 

The summary I want to do is as follows;
1. When setRoot is changed, the loading bar appears.
2. When all content is loaded _(including my fetch, it already happens in didMount)_, my page will be opened with the content completely loaded (fetching).

Can we add a loading bar (activity indicator) to setRoot transitions?

_I keep the setRoot changes in the function like _atoami/react-native-navigation-redux-starter-kit_ repo._

---
### Environment
* React Native Navigation version: 2.18.3
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Venus GO (I'm also speaking general for all devices, I've tried a lot of my friends' phones too)

**Comment by igortupini** [comment]
I have this problem as well. A seamless transition would be really nice

**Comment by igortupini** [comment]
I have this problem as well. A seamless transition would be really nice

**Comment by igortupini** [comment]
Not stale, still a problem

**Comment by igortupini** [comment]
Any news on this?

**Comment by abury** [comment]
We're having this problem as well, it looked like v1 had a solution to this, but nothing in v2? Seems quite strange
