### ISSUE TITLE
[Android][IOS][V2]The navigation button does not work after I used the setRoot

### ISSUE THREAD

**Issue by Kirill-Cherkalov** [wix/react-native-navigation#5212]
### Issue Description

The navigation button does not work after I used the setRoot command and moved to the screen back(-1) which I pushed into the stack via the children key. But if I go back to the screen(-2), and then push screen (-1), the button will work.
Also, if I subscribe to pressing the navigation keys I will use the `` registerNavigationButtonPressedListener `` method instead of the `` Navigation.events().bindComponent(this) `` , then everything will work correctly. Those I can assume that the problem is in `` Navigation.events().bindComponent(this) ``

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Device - android v5 and newer, ios - emulator

**Comment by ItsNoHax** [comment]
Hi @Kirill-Cherkalov ,

I find it a bit hard to understand your issue. Could you create a fork of this project and create a branch where you reproduce this in the playground app?
