### ISSUE TITLE
RNN V2 - horizontally scrollable toptabs

### ISSUE THREAD

**Issue by nirvo** [wix/react-native-navigation#5213]
How scroll in react-native-navigation
I have many tabs.
the option scrollEnabled: true doesn't work. 

`
export const goTabsScreen = () => Navigation.setRoot({
  root: {
    stack: {
      id: 'tabsStack',
      options: {
        topBar: {
                  tabBarOptions: {
                         scrollEnabled: true,
                  },
       },
   },
  children: [
  {
    topTabs:  
    {
           ...
    }
  }
  ]
}
`

**Comment by t1amat9409** [comment]
Do toptabs even work?
