### ISSUE TITLE
Pushing without the bottom navigation bar not working after Keyboard.dismiss()

### ISSUE THREAD

**Issue by samiede** [wix/react-native-navigation#5221]
### Issue Description

I'm pushing a screen from the results of a user input, which means that the keyboard may be open. Apparently, the options for pushing the new screen are a overwritten by the Keyboard.dismiss() side effect of setting the bottom tabs visibility to true, which means that the new screen is pushed with the bottom navigation bar.
I trigger the visibility of the tabs in the onEndEditing callback of the textInput, so that I can also get them back when the user cancels the text input. 
Apparently, the callback is evoked when the component is dismounted as well, such that first the push of the screen happens and then the visibility of the tabs is triggered to visible.

### Steps to Reproduce / Code Snippets / Screenshots
```js
  clickSearchItem(item) {
  Keyboard.dismiss()

    Navigation.push(this.currentComponentId, {
      component: {
        name: screen,
        passProps: props,
        options: {
           bottomTabs: {
              visible: false,
              drawBehind: true
              }
         }
       })
    }
  }
```

it does work when wrapping the whole push logic in a setTimeout of 1 ms, but unfortunately not with the InteractionsManager as suggested here:

Maybe this workaround can be helpful. Instead of using timeouts you can use `InteractionManager`.
```javascript
Keybaord.dismiss();
InteractionManager.runAfterInteractions(() => {
  // screen push logic
})
```

_Originally posted by @raphaelhovsepyan in https://github.com/wix/react-native-navigation/issues/2318#issuecomment-444392477_

### Environment
* React Native Navigation version: 2.20.0
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by JerakRus** [comment]
There is the same problem, and honestly I would like it to work out of the box, without additional hacks, as it was before.
