### ISSUE TITLE
dismissModal fails with overCurrentContext and alpha animation

### ISSUE THREAD

**Issue by vitaliykastsiuk** [wix/react-native-navigation#5222]
### Issue Description

`dismissModal` results to white background instead of just closing modal on iOS if used with `modalPresentationStyle: 'overCurrentContext'` and fade animation. It works as expected on Android.

### Steps to Reproduce / Code Snippets / Screenshots
No any errors in console
Works as expected on Android and on iOS without fade animation or without specifying `modalPresentationStyle` 

![Screen Shot 2019-06-20 at 03 51 58](https://user-images.githubusercontent.com/2403995/59810619-d2626600-930e-11e9-804a-b9dfe47fee01.png)

```js   
const defaultScreenProps = {
  navigate: (componentId, screenName, props = {}) => {
    Navigation.push(componentId, {
      component: getScreenComponent(screenName, props),
    });
  },
  showModal: (screenName, showTransparent = true) => {
    const component = getScreenComponent(screenName);
    component.options = {
      ...component.options,
      modalPresentationStyle: 'overCurrentContext',
      layout: {
        backgroundColor: showTransparent ? Colors.transparent : 'transparent',
      },
    };

    Navigation.showModal({
      stack: {
        children: [{
          component,
        }]
      },
    });
  },
  dismissModal: (componentId) => {
    Navigation.dismissModal(componentId);
  },
  goBack: (componentId) => {
    Navigation.pop(componentId);
  },
};

const fadeAnimationOpenModal = {
  alpha: {
    from: 0,
    to: 1,
    duration: 200,
    interpolation: 'accelerate',
  },
};

const fadeAnimationCloseModal = {
  alpha: {
    from: 1,
    to: 0,
    duration: 200,
    interpolation: 'accelerate',
  },
};

const defaultScreenOptions = {
  topBar: {
    visible: false,
    height: 0,
    drawBehind: true,
    animate: false,
  },
  animations: {
    push: {
      enable: false,
    },
    pop: {
      enable: false,
    },
    showModal: Platform.select({
      ios: { content: fadeAnimationOpenModal },
      android: fadeAnimationOpenModal
    }),
    dismissModal: Platform.select({
      ios: { content: fadeAnimationCloseModal },
      android: fadeAnimationCloseModal
    }),
  },
};                                        
```                                    

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator 12.1 Debug

**Comment by huuthinh245** [comment]
still an issue on v3 react-native-navigation@3.0.0-alpha.3

**Comment by huuthinh245** [comment]
i change showModal with default alpha animation hope this help
- (void)showModal:(NSDictionary*)layout commandId:(NSString *)commandId completion:(RNNTransitionWithComponentIdCompletionBlock)completion {
    [self assertReady];
    
    UIViewController *newVc = [_controllerFactory createLayout:layout];
    [newVc setModalTransitionStyle:UIModalTransitionStyleCrossDissolve];
    [newVc renderTreeAndWait:[newVc.resolveOptions.animations.showModal.waitForRender getWithDefaultValue:YES] perform:^{
        [_modalManager showModal:newVc animated:YES  completion:^(NSString *componentId) {
            [_eventEmitter sendOnNavigationCommandCompletion:showModal commandId:commandId params:@{@"layout": layout}];
            completion(newVc.layoutInfo.componentId);
        }];
    }];
}

**Comment by bneigher** [comment]
yep I am getting this too - seems like a bug

**Comment by bneigher** [comment]
@huuthinh245 where did you put this code?

**Comment by vitaliykastsiuk** [comment]
@huuthinh245 Thaks! That works for me.
@bneigher lib/ios/RNNCommandsHandler.m - showModal method

**Comment by bneigher** [comment]
Any way we can get this updated in the source?  I've been relying on a patch on install for this

**Comment by vitaliykastsiuk** [comment]
still an issue on 4.4.0

**Comment by bneigher** [comment]
seems that something has changed with the original method.  now the code must be:
```
- (void)showModal:(NSDictionary*)layout commandId:(NSString *)commandId completion:(RNNTransitionWithComponentIdCompletionBlock)completion {
    [self assertReady];

    UIViewController *newVc = [_controllerFactory createLayout:layout];
    [newVc setModalTransitionStyle:UIModalTransitionStyleCrossDissolve];
    newVc.waitForRender = [newVc.resolveOptionsWithDefault.animations.showModal.waitForRender getWithDefaultValue:NO];
    [newVc setReactViewReadyCallback:^{
        [_modalManager showModal:newVc animated:[newVc.resolveOptionsWithDefault.animations.showModal.enable getWithDefaultValue:YES] hasCustomAnimation:newVc.resolveOptionsWithDefault.animations.showModal.hasCustomAnimation completion:^(NSString *componentId) {
            [self->_eventEmitter sendOnNavigationCommandCompletion:showModal commandId:commandId params:@{@"layout": layout}];
            completion(newVc.layoutInfo.componentId);
        }];
    }];
    [newVc render];
}

```

but this still isn't exactly right

**Comment by skyliwq** [comment]
+1
