### ISSUE TITLE
[V1][Android] Build suddenly fails

### ISSUE THREAD

**Issue by Estebank94** [wix/react-native-navigation#5225]
### Issue Description

My app isn't building anymore, it was working a few days ago and I didn't change the dependencies configuration.

When I try to build the app I get
`Task :react-native-navigation:compileDebugJavaWithJavac FAILED
/Users/estebankramer1/Documents/Provi/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/screens/FragmentScreen.java:87: error: incompatible types: androidx.fragment.app.FragmentManager cannot be converted to android.support.v4.app.FragmentManager
        android.support.v4.app.FragmentManager fm = activity.getSupportFragmentManager();
                                                                                      ^
/Users/estebankramer1/Documents/Provi/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/screens/ViewPagerScreen.java:97: error: incompatible types: android.support.v4.view.ViewPager cannot be converted to androidx.viewpager.widget.ViewPager
        tabLayout.setupWithViewPager(viewPager);
                                     ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

I think it's because it uses an androidx dependency but I cannot migrate to androidx as I have other packages such as react native maps that do not support androidx yet.

This are my dependencies in android/app/build.gradle:
`compile project(':react-native-navigation')
    compile project(':react-native-maps')
    compile project(':react-native-haptic-feedback')
    compile project(':appcenter-crashes')
    compile project(':react-native-code-push')
    compile project(':appcenter-analytics')
    compile project(':appcenter')
    compile project(':react-native-device-info')
    implementation project(':react-native-haptic-feedback')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation "com.google.android.gms:play-services-base:+"
    implementation 'com.google.android.gms:play-services-maps:+'
    implementation project(':react-native-navigation')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-push-notification')
    implementation project(':react-native-device-info')
    implementation project(':react-native-maps')
    implementation project(':react-native-haptic-feedback')
    implementation 'androidx.constraintlayout:constraintlayout:1.1.0'
    implementation 'androidx.appcompat:appcompat:1.0.0-alpha1'
    implementation("com.android.support:support-media-compat:28.0.0")
    implementation("com.android.support:support-v4:28.0.0")`

and configuration in android/build.gradle
`buildToolsVersion = "28.0.3"
    minSdkVersion = 16
    compileSdkVersion = 28
    targetSdkVersion = 27
    supportLibVersion = "28.0.0"
    googlePlayServicesVersion="16.1.0"
    firebaseVersion="18.0.0"`

How can I fix this issue?

### Steps to Reproduce / Code Snippets / Screenshots

Try to build android app by running `react-native run-android`

---
### Environment
* React Native Navigation version: 1.1.381
* React Native version: 0.55.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by Estebank94** [comment]
Fixed it by using [https://github.com/mikehardy/jetifier](url)

**Comment by vinnyA3** [comment]
@Estebank94 ... just curious, why would you need to use jetifier if you're running RNNv1 + `RN < .60`?
