### ISSUE TITLE
App crash if a  screen is pushed twice and then pop 

### ISSUE THREAD

**Issue by eyousefifar** [wix/react-native-navigation#5229]
### Issue Description

in some cases, if a user presses a button with push ( or showModal ) action fast, like twice, two instances of the same screen are pushed, and on the second one poping crashes the app.
### Steps to Reproduce / Code Snippets / Screenshots

here is my push function 

```javascript
export default function push(args: pushArgs) {
  const { componentId, passProps, screenId, screenName } = args;
  Navigation.push(componentId, {
    component: {
      passProps,
      id: screenId,
      name: screenName,

      options: {
        animations: {
          push: {
            enabled: true,
            content: {
              x: {
                from: -widthPercentageToDP('100%'),
                to: 0,
                duration: 460,
                interpolation: 'decelerate'
              },
              alpha: {
                from: 0,
                to: 1
              }
            },
            waitForRender: false
          }
        }
      }
    }
  });
}

```

here is my pop function

```javascript
export default function pop(componentId: string) {
  Navigation.pop(componentId, {
    animations: {
      pop: {
        content: {
          y: {
            from: 0,
            to: heightPercentageToDP('100%')
          },
          alpha: {
            from: 1,
            to: 0
          }
        }
      }
    }
  });
}

```

![index](https://user-images.githubusercontent.com/38952501/59976842-20ad8880-95df-11e9-8916-1837f9ea1e24.jpeg)

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Redmi 6 Pro,  8.1, debug and release

**Comment by markhomoki** [comment]
I think you need to handle it on your own. I wrote a little helper function which works perfectly. The code I'm sharing is a simplified version, but it shows the idea. Hope this helps.

```
let lastPressedTime = 0;
const canNavigate = () => {
  const now = Date.now();
  if (!lastPressedTime || (lastPressedTime + 750) < now) {
    lastPressedTime = now;
    return true;
  }

  return false;
};

export const throttledPush = (args) => {
  if (canNavigate()) {
    Navigation.push(args);
  }
};
```

**Comment by eyousefifar** [comment]
@markhomoki Thanks for your response. I actually did that. I used a state class to keep history and manage all events, it's useful for logging and things like that. but the main problem still exists. on v1 you can push many and pop them, in some native android app I saw this behavior too. I switched to v1 due to some weird memory issue.  adapted state class for v1 and it works perfectly. it's a workaround though

**Comment by markhomoki** [comment]
Good one.

I think the only reason it doesn't work is the animation. For my app, pushing and popping without animation or shared element navigation, without that piece of code you can push multiple times and pop as well. With shared element it breaks, because cannot find the right reference.

Anyway, pushing the same screen multiple times is not ideal, if it's not managed by the library we can add our piece of code to it :) I think, this is still the best library by far among the RN navigation libs.

**Comment by eyousefifar** [comment]
@markhomoki I agree. integration with react native gesture handler and reanimated would be cool
