### ISSUE TITLE
appStyle not regarded on iOS

### ISSUE THREAD

**Issue by lyubo** [wix/react-native-navigation#523]
### Issue Description
iOS will not regard appStyle settings in startSingleScreenApp.

### Steps to Reproduce / Code Snippets / Screenshots
```
const settings = {
  screen: {
    screen: 'Welcome',
    navigatorStyle: {
      // Regarded for all screens on iOS (?), Android will set red only on Welcome screen.
      navBarBackgroundColor: 'red', 
    }
  },
  appStyle: {
   // Android will set blue on all screens, except on Welcome (as expected), iOS ignores it on all screens.
   navBarBackgroundColor: 'blue',
 }
}
Navigation.startSingleScreenApp(settings)
```
---
### Environment
* React Native Navigation version: 2.0.0-experimental.148
* React Native version: 0.37.0
* Platform(s): iOS
* Device info: Simulator, iOS 10.1, Debug

**Comment by ricechen** [comment]
the same, any solution?

**Comment by guyca** [comment]
Hey guys, `appStyle` probably won't be supported in v1, it's already implemented in v2.
