### ISSUE TITLE
Typescript SideMenuSide missing width / height attributes

### ISSUE THREAD

**Issue by ball-hayden** [wix/react-native-navigation#5231]
### Issue Description

The [documentation](https://wix.github.io/react-native-navigation/#/docs/styling?id=common-options) allows for `width` and `height` options to be set for side menus.
The current TypeScript definition of `SideMenuSide` does not.

### Steps to Reproduce / Code Snippets / Screenshots

```ts
Navigation.setRoot({
  root: {
    sideMenu: {
      // ...
      options: {
        sideMenu: {
          left: {
            width: 250,
            // --> Object literal may only specify known properties, and 'width' does not exist in type 'SideMenuSide'
          },
        },
      },
    },
  },
});
```

---
### Environment
* React Native Navigation version: `2.21.0`
* React Native version: `0.59.9`
* Platform(s) (iOS, Android, or both?): N/A
* Device info (Simulator/Device? OS version? Debug/Release?): TypeScript `3.4.5`

**Comment by ItsNoHax** [comment]
Why don't you go ahead and create a PR for this? It should be about 3-4 lines of code.

**Comment by ball-hayden** [comment]
Will do - just wanted to check I wasn't missing anything first 🙂
