### ISSUE TITLE
Accessibility TopBar, Content, Tab Icons

### ISSUE THREAD

**Issue by JakubKana** [wix/react-native-navigation#5232]
### [V2] Accessibility TopBar, Content, Tab Icons

Accessibility problem with native buttons and title bar. I do not have any way to modify or configure accesibility labels of topbar, tab icons and content

Even some weird wrapper around main content is used and TalkBack says "stacklayout" this is some internal accessibility label within android code.

So I have 4 accessibility problems:
1) Default top bar does not provide way to modify accessibility labels
2) With custom top bar it says "titlebar" so problem prevails.
3) Content is wrapped with some "stacklayout" accessibility label
4) Configuring Tab buttons accessibility labels

Suggested solution:
Make layouts configurable with accessible parameters so I can pass accesiblity labels within.

Positives:
On IOS platform we do not notice these problems.

### Steps to Reproduce / Code Snippets / Screenshots
![Accessibility](https://user-images.githubusercontent.com/6625593/60026902-c1ae4900-969c-11e9-8391-8f13ed1f7349.png)
                                                    
---
### Environment
* React Native Navigation version: 2.16.0
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung / Android 9.0 / Release and Debug

**Comment by JakubKana** [comment]
Any update?

**Comment by RubenSandwich** [comment]
Because wix/react-native-navigation is the only completely native navigation solution in React Native it has a unique opportunity to deal with accessibility issues in a way other navigation libraries simply cannot. I really hope that this is a priority as I think this is a huge selling point of this library.

**Comment by gaguirre** [comment]
We're having the same issue (and many others related to accessibility).
We've already identified what's need to be done and have plans to send a PR.

Our idea is to take the `accessibilityLabel` property and set it natively. 
@guyca what do you think about it?

**Comment by jpgarcia** [comment]
@guyca any update about @gaguirre question? it would be awesome to have this issue solved!

**Comment by JakubKana** [comment]
Any update?

**Comment by kyle-ssg** [comment]
I think this is quite an important issue to address, is there a chance to get an update on this?

**Comment by kyle-ssg** [comment]
An update on this.. It looks like in iOS there's an attempt to assign accessibility labels to the corresponding test IDs 

https://github.com/wix/react-native-navigation/blob/6ab2345ad6e9ddd26ac1275537ec2791fa50c7c2/lib/ios/RNNNavigationButtons.m#L151.

This actually matches my long winded attempt to refactor Java to do a similar thing. I searched for instances of setTag and also included an accessibility labels by adding view.setContentDescription. I haven't tested this yet as I also want to refactor the iOS side too as it does this in plenty of places.

```
                    view.setTag(testId.get());
                    // wherever we set the test id we should also set an accessibility label
                    view.setContentDescription(testId.get());
```

**Comment by gaguirre** [comment]
You're right @kyle-ssg 
However, we're looking for a solution for both platforms.
We've a list of things that need to be done, but still waiting for @guyca's response about wether or not this feature like this would be merged.

**Comment by RubenSandwich** [comment]
@guyca I think the automation bot closed this one on accident. It went from **Selected for Development** to **Done** without any commits associated with it.

See the message above.

**Comment by JakubKana** [comment]
Why still not fixed this?

**Comment by xchmelmilos** [comment]
Hi, is there any progress on this? 

As  @RubenSandwich said, could You please re-open it, because `stalebot` marked it as stale and closed it automatically.

**Comment by beshur** [comment]
Any update here?
