### ISSUE TITLE
Android Back default button issue

### ISSUE THREAD

**Issue by NweThazin** [wix/react-native-navigation#5233]
### Issue Description

want to remove BackHandler listener when push from first to second screen.

registered backhandler in componentDidMount and remove backhandler in componentWillUnmount method in first screen

but when push to second screen, the event listener is still listening even in second screen

is there any way to solve that issue? can some one help me ? thanks

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version:"2.21.0",
* React Native version: "^0.59.9"
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by ItsNoHax** [comment]
Hi @NweThazin , the solution is to move your backhandler code to componentDidAppear and ComponentDidDissapear. https://wix.github.io/react-native-navigation/#/docs/events?id=componentdidappear

Don't forget to call: Navigation.events().bindComponent(this); in your componentDidMount
