### ISSUE TITLE
[iOS] Back button not working on <iOS11 with topBar.background.component

### ISSUE THREAD

**Issue by johnnyborg** [wix/react-native-navigation#5234]
### Issue Description
Pressing the back button in the topBar on iOS 10.3.1 (iPhone 5/7) with an custom background component is not working. When removing the `topBar.background.component.name` it is working again. I've played with elevation/z-index but it does not seem to work. 

### Steps to Reproduce / Code Snippets / Screenshots
We're using the following options: 
```js
Navigation.setDefaultOptions({
    topBar: {
        visible: false,
        noBorder: true,
        drawBehind: true,
        elevation: 0,
        background: {
            color: 'transparent',
            component: {
                name: 'topBar.Background',
            },
        },
        backButton: {
            color: lightTheme.topBarButtonColor,
            showTitle: false,
        },
    },
});
```

Our custom topbar looks like; 
```js
const TopBarBackground = () => (
    <Wrapper>
        <Mask />
    </Wrapper>
);

const Wrapper = styled.View`
    position: absolute;
    top: -100px;
    left: 0;
    right: 0;
`;

const Mask = styled.View`
    flex: 1;
    border-bottom-left-radius: ${props => props.theme.largeBorderRadius};
    border-bottom-right-radius: ${props => props.theme.largeBorderRadius};
    background-color: ${props => props.theme.topBarBackgroundColor};
`;
```

---
### Environment
* React Native Navigation version: 2.21.1
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): < iOS 11
* Device info (Simulator/Device? OS version? Debug/Release?): 
  - iPhone 5 10.3.1 (debug)
  - iPhone 7 10.3.1 (debug)

**Comment by amitkumarsingh1991** [comment]
Hello folk, facing same issue

**Comment by deCodeIt** [comment]
Facing similar issue where it doesn't work with iOS but it works on android.

**Comment by snairsumith** [comment]
Same .Any Updates ?

**Comment by deCodeIt** [comment]
@guyca Can you look at this or point us to where we can look. I've got no experience of swift otherwise would have looked at this myself had it been on android.

**Comment by EliecerC** [comment]
Hey, @johnnyborg did you guys find any solution to this? still happening to us. 
RNN version: 7.3.0.
RN version: 0.63.4. 
iOS: 14.2. 
Device: iPhone 11 simulator and also real devices.

**Comment by johnnyborg** [comment]
Hey @EliecerC , 
I believe we've changed the design a bit as a workaround. Maby @loudy or @rtuin can peek into the code to see if they're still using it.
