### ISSUE TITLE
TopBar title centered after 2.21.1 upgrade

### ISSUE THREAD

**Issue by adamgrossman** [wix/react-native-navigation#5236]
### Issue Description

We're using a custom component in our topBar. After we upgraded to 2.21.1 from 2.17, the title moved from being left aligned to centered. I reverted the upgrade and the title went back over to the left. I tried setting `alignment` as well, but that had no effect.

### Steps to Reproduce / Code Snippets / Screenshots
```
topBar: {
  title: {
    component: {
      name: Resources
    },
  },
...
```
**Version 2.17**
![Screen Shot 2019-06-25 at 1 50 31 PM](https://user-images.githubusercontent.com/8585262/60134620-c33b4800-9754-11e9-9b2a-72c9b2492d22.png)
**Version 2.21.1**
![Screen Shot 2019-06-25 at 1 34 50 PM](https://user-images.githubusercontent.com/8585262/60134624-c59da200-9754-11e9-9200-21d2d81c90c0.png)

---
### Environment
* React Native Navigation version: 2.21.1 (also tried 2.22)
* React Native version: 0.57.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & device, debug & release

**Comment by andresfcamacho** [comment]
This is also happening on IOS 13 now.
