### ISSUE TITLE
Shows black screen while navigating from one screen to another on iPad Device with RNN: 2.22.0

### ISSUE THREAD

**Issue by archana-iron** [wix/react-native-navigation#5238]
### Issue Description
I have updated RNN version: 2.12.0 to the latest one (2.22.0), it's working on all devices except iPad. It's showing a black screen when navigating and after some time it stops an app without any error. I have searched for RNN issue but didn't find any problem like this.  
I didn't have any issue with the older version, I am getting this issue after the latest version update.

### Screenshot
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2019-06-27 at 10 34 36](https://user-images.githubusercontent.com/41895602/60236068-9eb3ad00-98c7-11e9-919a-0e7d915810d9.png)

### Environment
* React Native Navigation version: 2.22.0
* React Native version: 0.59.9
* Platform(s) : Only iOS iPad devices
* Device info: Problem on both debug and release mode(on both simulator and iPad device)

**Comment by ItsNoHax** [comment]
Hi @archana-iron, could you please create a fork of this project and push a branch where you reproduce this behavior in the playground app? That way we can help you further.

**Comment by hotdream1990** [comment]
I had same issue when moving from 2.12.0 to 2.22.3. And also had issue when force close drawer while moving to another screen.
Temporary solution is back to 2.12 version.
Impact on iPhone and another.
