### ISSUE TITLE
[V2] Android topBar shadow

### ISSUE THREAD

**Issue by ramiong** [wix/react-native-navigation#5239]
### Issue Description

Is it possible to remove topBar border/shadow like on iOS?
![Zrzut ekranu 2019-06-27 o 09 12 31](https://user-images.githubusercontent.com/20752537/60244952-d583c600-98bb-11e9-8358-254972b72fad.png)

---
### Environment
* React Native Navigation version: 2.21.1
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by MikePodgorniy** [comment]
Try `topBar: { elevation: 0 }`

**Comment by ramiong** [comment]
@MikePodgorniy thank you so much, that was so simple but I missed out this option in docs.
