### ISSUE TITLE
How to have text next to an icon on the nav bar.

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#524]
Hey there.

I'm trying to have some text on the nav bar (as part of one of the icons) like so:
<img width="441" alt="screen shot 2016-12-01 at 18 00 35" src="https://cloud.githubusercontent.com/assets/3070948/20801007/1fd3753e-b7f0-11e6-9bcd-433c8ae7c76d.png">

This would totally be possible if I was able to use an icon font on the nav bar, but to my knowledge that's not possible.

Please tell me there's a way to do this.

Thank you.

**Comment by Jaafar-abusair** [comment]
You can use a button with title only with out icon property, in this case you will have text button and set the disabled property to true, so user will not be able to press on it

**Comment by SudoPlz** [comment]
That's a nice hack @Jaafar-abusair , thanks. 
The only problem is, I can't really control it's position.

Also @guyca suggested to use a transparent Navigation Bar, and render a regular `<Text>` beneath it, but I would like to avoid that solution as well.

I might do what you suggest until we're able to render custom elements on the nav bar.

**Comment by perrosnk** [comment]
I am also interested in this! I would like to have an icon next to some text.

**Comment by Jaafar-abusair** [comment]
For me I hid the bar and i built my own custom top menu

**Comment by guyca** [comment]
@Jaafar-abusair solution is definitely preferable. You can also try adding the `showAsAction: 'withText'` property to that button but that will work only on Android.

**Comment by SudoPlz** [comment]
I have implemented a Custom Nav bar in 1.* by using the `navBarCustomView` (Check the [docs](https://wix.github.io/react-native-navigation/#/styling-the-navigator?id=style-object-format))
