### ISSUE TITLE
Discussion:[V2][Hooks] How to use bindComponent() of EventListener with a React Functional Component (convert from Class Component)

### ISSUE THREAD

**Issue by tuanduongdn1504** [wix/react-native-navigation#5241]
### Issue Discussion
Hi, just providing some feedback based on my experience:

I am tried convert `React Class Component` to `React Functional Component` with `Hooks`. My project have used RNN V2 alongside [lottie-react-native](https://github.com/react-native-community/lottie-react-native), which requires the `componentDidAppear` and `componentDidDisappear` events to handle animations each time the component appears/disappears on screen. And before I used `Navigation.events().bindComponent(this)` in React Class Component to subscribe to a component's events.

For Class-base, the solution was to use the `bindComponent(this)` method as explained in the [V2 docs](https://wix.github.io/react-native-navigation/#/docs/events?id=componentdidappear).

With Functional, however the `bindComponent(this)` does not work as expected. And I can't find anything which offers the same functionality in the [V2 docs](https://wix.github.io/react-native-navigation/#/docs/events?id=componentdidappear). Fortunately, I found something related in the [#4295 comment](https://github.com/wix/react-native-navigation/issues/4295#issue-377874173).

Then, I made `Cmd+click (Ctrl+click on Windows)` perform a "Go To Definition" on the identifier under the cursor for `bindComponent()` function. In deep of `node_modules/react-native-navigation`, This function has been declared with 2 parameters as: 

> bindComponent(component: React.Component<any>, componentId?: string): EventSubscription;

Finally, using this function with 2 parameters as declared solved the problem for `React Functional Component with Hooks`.
 
#### Workaround for React Class Component
```js                                                         
...
  componentDidMount() {
      // that are called on the component when it appears and disappears
      // (after it was bounded using Navigation.events().bindComponent(this)).
      this.navigationEventListener = Navigation.events().bindComponent(this);
    }
  }
  componentWillUnmount() {
      // Because a component is actually mounted as soon as it's part of a layout
      // -- but it is not always visible (for example, when another screen is pushed on top of it).
      // => Remove Listener after component is removed from DOM => component haven't been rendered
      this.navigationEventListener.remove();
    }
  }

  componentDidAppear() {
    // Re-play animation after paused by auto-disappearing component
    if (this.lottieAnimation) {
      this.lottieAnimation.play();
    }
  }

  componentDidDisappear() {
    // Stopping animation after disappearing
    if (this.lottieAnimation) {
      this.lottieAnimation.reset();
    }
  }
...
```                                                           
## **_Workaround for [React Functional Component with Hooks](https://reactjs.org/docs/hooks-overview.html)_**
```js                                                         
...
    useEffect(() => {
        // that are called on the component when it appears and disappears
        // ***(after it was bounded using bindComponent() with 2 parameters)***
        const navigationEventListener = Navigation.events().bindComponent(this, componentId);
        return () => {
          // Because a component is actually mounted as soon as it's part of a layout
          // but it is not always visible (for example, when another screen is pushed on top of it).
          // => Remove Listener after component is removed from DOM => component haven't been rendered
          if (navigationEventListener) {
            navigationEventListener.remove();
          }
        };
      }
    });
   
    componentDidAppear = () => {
      // Re-play animation after paused by auto-disappearing component
      if (lottieAnimation) {
        lottieAnimation.play();
      }
    };
   
    componentDidDisappear = () => {
      // Stopping animation after disappearing
      if (lottieAnimation) {
        lottieAnimation.reset();
      }
    };
...
```     
---
### Environment
* React Native Navigation version: 2.12.0
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by tuanduongdn1504** [comment]
I just want to show again my workaround but its untested:
It is only for who concern about converting `React Class Component` to `React Functional Component with Hooks`, which have used alongside RNN V2
Replace:
```
this.navigationEventListener = Navigation.events().bindComponent(this);
```

With: 
```
const navigationEventListener = Navigation.events().bindComponent(this, componentId);
```

**Comment by robertying** [comment]
Use `registerNavigationButtonPressedListener`

e.g.

```ts
  useEffect(() => {
    const listener = Navigation.events().registerNavigationButtonPressedListener(
      () => {
        // do things
      }
    );
    return () => listener.remove();
  }, []);
```

**Comment by jpgarcia** [comment]
FYI I've just [reported an issue](https://github.com/wix/react-native-navigation/issues/5244) on **Android** related with functional components using hooks.

The issue came up while using https://github.com/underscopeio/react-native-navigation-hooks

**Comment by zenVentzi** [comment]
`const navigationEventListener = Navigation.events().bindComponent(this, componentId);`

@tuanduongdn1504 what does `this` refer to in this line of code? Aren't we using functional components? I find that confusing.

----

@robertying is the code snippet you posted:
```

  useEffect(() => {
    const listener = Navigation.events().registerNavigationButtonPressedListener(
      () => {
        // do things
      }
    );
    return () => listener.remove();
  }, []);
```

 the equivalent of `Navigation.events().bindComponent(this);` in a class component? I.e. after we can use `componentDidAppear` and `componentDidDisappear` the same way we would in a class component?

**Comment by Andarius** [comment]
> ```ts
> registerNavigationButtonPressedListener
> ```

This does not trigger (in v3 at least)
