### ISSUE TITLE
[Android] registerComponentDidAppearListener not triggering (sometimes) on functional components (release mode)

### ISSUE THREAD

**Issue by jpgarcia** [wix/react-native-navigation#5244]
### Issue Description

If you use a functional (with hooks) component for a screen and you use `registerComponentDidAppearListener` you could end up with the events not being triggered **(only on Android and in release mode)**

### Steps to Reproduce / Code Snippets / Screenshots

I have created a [simple react-native project](https://github.com/jpgarcia/rnn-events-issue) on a public repo to reproduce it. The example reproduce the **DidAppear** not working on Android release mode only

The project includes a screen implemented as a  **Functional Component** (with hooks) and also a **PureComponent** with the same behavior. 

### On Android (Debug Mode) 
`react-native run-android`
The sample works perfect on both **Functional** and **PureComponent**

### On Android (Release Mode) 
`react-native run-android --variant=release`
The sample works perfect on the **PureComponent** implementation but the **Functional** doesn't work

![ezgif-2-c6b40be6fbf1](https://user-images.githubusercontent.com/95109/60398770-a1660a80-9b32-11e9-8626-4a1b782aaa22.gif)
*Video of the example app running in release mode*

---
### Environment
* React Native Navigation version: **2.22.1**
* React Native version: **0.59.9**
* Platform(s) (iOS, Android, or both?): **Android**
* Device info (Simulator/Device? OS version? Debug/Release?): **Simulator and Device (Only Release Mode)**

**Comment by rendomnet** [comment]
@guyca  Any updates on this issue?

**Comment by samithaf** [comment]
Also seems like life cycle hook is pretty slow on Android and I am testing the App on Samsung S10 so can't be the device is slow. Furthermore on iOS seems everything smooth.

**Comment by samithaf** [comment]
Looks like life cycle hook is not guarantee to get fire on Debug build too. It's still happening:(

**Comment by cfranchella** [comment]
Hey @guyca do you have any updates on this issue? Thanks!

**Comment by jpgarcia** [comment]
@sintylapse mentioned here https://github.com/underscopeio/react-native-navigation-hooks/issues/7 the cause of the events not being triggered.

Basically you must use **useLayoutEffect** instead of **useEffect** 🚀 

BTW I just published a new version of [react-native-navigation-hooks](https://github.com/underscopeio/react-native-navigation-hooks) which includes this fix
