### ISSUE TITLE
[v2] [Android] White screen if you press physical back during modal

### ISSUE THREAD

**Issue by FRizzonelli** [wix/react-native-navigation#5245]
### Issue Description

I think this is a bit awkward, if you call Navigation.showModal and during transition you press the physical back button, you get a white screen like your activity was removed from stack.

In the attached gif you can see it, on button press I'm calling showModal, if I press back on device, the result is I'm getting a white screen.

### Steps to Reproduce / Code Snippets / Screenshots

![20190701_104329](https://user-images.githubusercontent.com/12106217/60423056-991ed580-9bed-11e9-9748-a5e460464e37.gif)

---
### Environment
* React Native Navigation version: 2.22
* React Native version: 0.57.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, all build types

**Comment by FRizzonelli** [comment]
@guyca Any news on this? Can we help somehow through investigation?

**Comment by MakhouT** [comment]
I'm having the same issue!

**Comment by alejandrorangel** [comment]
I'm on 4.0.4 and this error is still happening

**Comment by gaguirre** [comment]
It's still happening with version 6.10.1

**Comment by guyca** [comment]
Hey @gaguirre I've prioritised this internally.

**Comment by gaguirre** [comment]
Great! Thank you @guyca and all the team!
