### ISSUE TITLE
[V1] Dimensions.get("window").width is zero when app launch in react-native 0.59 for iOS

### ISSUE THREAD

**Issue by genglei01** [wix/react-native-navigation#5248]
### Issue Description

Dimensions.get("window").width returns zero in iOS.

### Steps to Reproduce / Code Snippets / Screenshots
Demo url :https://github.com/genglei01/rn_playground.git

---
### Environment
* React Native Navigation version:    "wix/react-native-navigation#57caacddfc5422c00f41b32e031a732ab503b7dc"

* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by guyca** [comment]
Hey there, v1 isn't supported anymore.
