### ISSUE TITLE
bottomTab bag

### ISSUE THREAD

**Issue by maystrenkoYurii** [wix/react-native-navigation#5251]
If you do not use a picture for a tab, the app will crash into the android. In our application is your custom bottomTab.
Because of this, we need to do not crash the application to write
`options: {
                  bottomTab: {
                    icon: DeviceIcon,
                  },
                },` 

But in us he is generally hidden

**Comment by ItsNoHax** [comment]
Going to close this as it's not a properly formatted issue.
