### ISSUE TITLE
[V1] Error running assembleAndroidTest

### ISSUE THREAD

**Issue by linnett** [wix/react-native-navigation#5253]
### Issue Description

Trying to implement tests for the app. When we try and run the following command, we get an error:

`$ cd android && ./gradlew assembleDebug assembleAndroidTest`

Error:

```
> Task :react-native-navigation:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest FAILED
D8: Program type already present: android.support.design.widget.CoordinatorLayout$Behavior

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:transformDexArchiveWithExternalLibsDexMergerForDebugAndroidTest'.
```

Anyone else having this issue or know how to solve it?

---
### Environment
* React Native Navigation version: 1.1.486
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): ./gradlew assembleDebug assembleAndroidTest

**Comment by guyca** [comment]
Strange... perhaps try following [this step](https://wix.github.io/react-native-navigation/#/docs/Installing?id=_8-force-the-same-support-library-version-across-all-dependencies-optional) then explicitly run your tests for the `app` module - `cd android && ./gradlew app:assembleDebug app:assembleAndroidTest`

**Comment by daihieptn97** [comment]
> Strange... perhaps try following [this step](https://wix.github.io/react-native-navigation/#/docs/Installing?id=_8-force-the-same-support-library-version-across-all-dependencies-optional) then explicitly run your tests for the `app` module - `cd android && ./gradlew app:assembleDebug app:assembleAndroidTest`
> 
> Regardless, v1 isn't supported and this is probably not an RNN issue so I'm closing.

Thanks you. Work for me
