### ISSUE TITLE
[V2] [iOS] - bottomTabs setRoot animation doesn't work

### ISSUE THREAD

**Issue by Melzar** [wix/react-native-navigation#5259]
### Issue Description

setRoot Animation Doesn't work for iOS

### Steps to Reproduce / Code Snippets / Screenshots

Steps to reproduce: 
* Just set Navigation.setRoot() root with BottomTabs ( example config below )

Animation for setting root component with bottomTabs doesn't work for iOS is it a known issue?

```js
 Navigation.setRoot(authenticatedNavigationConfig)
```

Config definition here

```js                      
  root: {
    bottomTabs: {
      children: [
        {
          stack: {
            children: [
              {
                component: {
                  name: 'ScreenName,
                  options: {
                    topBar: {
                      visible: true,
                      title: {
                        component: {
                          name: 'componentName',
                          passProps: {
                            children: 'MyTitle',
                            style: <styles here>,
                          },
                        },
                      },
                      backButton: {
                        visible: false,
                      },
                      rightButtons: [{
...my button
}],
                    },
                    bottomTabs: {
                      visible: true,
                    },
                    bottomTab: {
                      icon: myIcon,
                      selectedIcon: myIconSelected,
                    },
                  },
                },
              },
            ],
          },
        },
     ]
   }
}                          
```      

What I've noticed animations works fine for push/pop operations and setting stack root on ios. When we are setting root with bottom tabs - there is no animation at all.

---
### Environment
* React Native Navigation version: 2.22.3
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): simulator, iPhone 6, iOS 12.2, Debug

**Comment by felix-lambert** [comment]
I also have this problem. Is it possible to investigate?
