### ISSUE TITLE
What is the suggested Approach when trying to wrap multiple HOCs to your <App>?

### ISSUE THREAD

**Issue by VicFrolov** [wix/react-native-navigation#5260]
### Issue Description

Let's say I want to wrap my App with `<Apollo>`, `<SafeAreaView`, `<Auth>`, etc. Since there is no single `<App>` entry, does that mean that every registered component needs to be wrapped, e.g.:

```
export const registerScreens = () => {
  Navigation.registerComponent(
    routes.SOME_SCREEN,
    () => props => withHocs(SomeScreen, props),
    () => SomeScreen
  );
  // more calls to registerComponent, each wrapped with withHocs
};
```

and

```
const withHocs = (Component, props) => {
  return (
    <ApolloProvider client={client}>
      <SafeAreaView>
        <Auth>
          <Component {...props} />
        </Auth>
      </SafeAreaView>
    </ApolloProvider>
  );
};
```
 and so forth?

---
### Environment
* React Native Navigation version: 2.22.3
* React Native version: 0.60.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by trantus** [comment]
@VicFrolov did you found solution?
