### ISSUE TITLE
[V2] Navigation push not working

### ISSUE THREAD

**Issue by dhamdani666** [wix/react-native-navigation#5261]
### Issue Description
Hi guys , how to fix function Navigation.push not work for me ? 
this my code : 
`this.setState({
            isLoading: true
        });
        setTimeout(() => {
            this.setState({isLoading: false});

            Navigation.push(this.props.componentId, {
                component: {
                    name: 'Home',
                }
            });

        }, 1000);`

this my video 👍 [https://streamable.com/2wif2](url)

---
### Environment
* React Native Navigation version: 2.11.0
* React Native version: 0.58.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device / Android 8.0 / Debug

**Comment by dhamdani666** [comment]
<img width="510" alt="Screen Shot 2019-07-07 at 18 30 57" src="https://user-images.githubusercontent.com/13973698/60767693-72790700-a0e5-11e9-8193-668d8d620463.png">
<img width="438" alt="Screen Shot 2019-07-07 at 18 31 13" src="https://user-images.githubusercontent.com/13973698/60767694-72790700-a0e5-11e9-9523-ea798c27c2f8.png">

GIF : 
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/13973698/60767739-f3d09980-a0e5-11e9-8765-1edff17d03c4.gif)

**Comment by dhamdani666** [comment]
SOLVED

**Comment by rizwankce** [comment]
@dhamdani666 can you please let us know - how this problem got solved?

**Comment by harveyconnor** [comment]
Even though it's solved I would suggest doing the following:
```js
this.setState({ isLoading: true }, () => {
  setTimeout(() => {
    this.setState({ isLoading: false }, () => {
      // Before pushing make sure that you are pushing with a stack, see below
      Navigation.push(this.props.componentId, {
        component: {
          id: 'Home2',
          name: 'Home2',
        }
    });
  }, 1000);
});
```

```js
stack: {
  id: 'Stack.Home',
  children: [
    {
      component: {
         id: 'Home',
         name: 'Home',
     },
   },
  ],
}
```

@rizwankce have a look and see if it fixes anything.

**Comment by rizwankce** [comment]
@harveyconnor thanks for your detailed answer. In my case there was component and stack id collision happening. After deleting all the manual `id` it works as expected. React Native Navigation handles automatic id generation and avoid collisions. 

For future readers, make sure
- set stack before pushing
- make sure there is no duplicate id's on your component or stack

**Comment by HemantRMali** [comment]
> Even though it's solved I would suggest doing the following:
> 
> ```js
> this.setState({ isLoading: true }, () => {
>   setTimeout(() => {
>     this.setState({ isLoading: false }, () => {
>       // Before pushing make sure that you are pushing with a stack, see below
>       Navigation.push(this.props.componentId, {
>         component: {
>           id: 'Home2',
>           name: 'Home2',
>         }
>     });
>   }, 1000);
> });
> ```
> 
> ```js
> stack: {
>   id: 'Stack.Home',
>   children: [
>     {
>       component: {
>          id: 'Home',
>          name: 'Home',
>      },
>    },
>   ],
> }
> ```
> 
> @rizwankce have a look and see if it fixes anything.

Works well, just wanted to show how i did using your reference.

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      stack: {
        children: [{
          component: {
            name: "Login"
          }
        }]
      }
    }
  });
})

**Comment by Shekhar7860** [comment]
Hello plz help me....The latest push method (given on documentation) of react native navigation do not works...the app (android or IOS) gets crashed....

**Comment by RichardLindhout** [comment]
Sometimes it's because your stack children is not an array but an object
