### ISSUE TITLE
[V2] ShowModal does not work on iOS

### ISSUE THREAD

**Issue by genglei01** [wix/react-native-navigation#5262]
### Issue Description

I use RNN as the following:

```
Navigation.setDefaultOptions({
      modalPresentationStyle: "pageSheet",
      layout: {
        componentBackgroundColor: "#e8e8e8",
        orientation: ["landscape"]
      },
      topBar: {
        visible: false,
        height: 0
      },
      animations: {
        setRoot: {
          alpha: {
            from: 0,
            to: 1,
            duration: 500
          }
        }
      }
    });

Navigation.setRoot({
      root: {
        stack: {
          children: [
            {
              component: {
                name: screenName,
                passProps
              }
            }
          ]
        }
      }
    });
```

And `push`/`pop`/`showOverlay` all work well, but `showModal` works well on android and not work on iOS.
Nothing happens when execute the following code:
 ```
Navigation.showModal({
      component: {
        name: screenName,
        passProps
      }
    });
```

I debug the native code, and find the topVC is nil.
![image](https://user-images.githubusercontent.com/3293583/60770507-e4654680-a10d-11e9-8f05-98fd59852ce7.png)

When I add `[ UIApplication.sharedApplication.delegate setWindow:_mainWindow];`
But i am not sure it is right.
![image](https://user-images.githubusercontent.com/3293583/60770517-0bbc1380-a10e-11e9-937c-6f10d7c3a0a4.png)

Could anyone give me a better solution?

---
### Environment
* React Native Navigation version:2.22.2
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by gillesBzk** [comment]
I confirm that 's the bug still exist !

**Comment by ACOSW** [comment]
showModal doesn't work on 3.1.1

**Comment by davidmarinangeli** [comment]
In my project there were two lines of code that we added in order to display a background in the topBar with the V1. I removed them and now `showModal` works everywhere. 

In `AppDelegate.m` remove these, if present:

```
self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
self.window.backgroundColor = [UIColor whiteColor];
```

In general: if you added something in `AppDelegate` with the V1 then try to remove it.

**Comment by bahtiyarerden** [comment]
@FRizzonelli, You saved my all day!!!

**Comment by FRizzonelli** [comment]
> @FRizzonelli, You saved my all day!!!

It was a pleasure to be useful :)
