### ISSUE TITLE
BottomTabs invisible in ShowModal() -> IOS

### ISSUE THREAD

**Issue by Ammarlio** [wix/react-native-navigation#5265]
### Issue Description

When trying showModal() the bottomTabs are invisible, but when trying push() bottomTabs are visible, and for the options -> visible: true (in all areas).

### Environment
* React Native Navigation version: ^2.18.1
* React Native version: ^0.57.8
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by jinshin1013** [comment]
I'm not 100% sure but isn't this an unexpected behaviour? Modal isn't on the same stack as the screen with the bottomTabs. If you want a modal-like screen transition but still want the bottomTabs, try using custom animation on when pushing a screen.

**Comment by ItsNoHax** [comment]
Going to go ahead and close this issue. What you are experiencing is default behavior, modals are used in UX to grab a users attention.
