### ISSUE TITLE
statusBar will auto show after switch to other APP

### ISSUE THREAD

**Issue by tomnotcat** [wix/react-native-navigation#5266]
### Issue Description

Start app with statusBar hidden, when switch to other app and switch back,
statusBar will auto show.

### Steps to Reproduce / Code Snippets / Screenshots

1. Set statusBar hidden on app start.
Navigation.setDefaultOptions({
       statusBar: {
           visible: false
       }
});

2. Set layout
Navigation.setRoot({xxx});

3. App show without statusBar, As expected.
4. Press the android ’home button’, then switch back to our App.
5. Now App will show statusBar, Which is not desired.

### Environment
* React Native Navigation version: 2.22.3
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Android 7.0 Debug

**Comment by Gutyn** [comment]
Did you figure this out, @tomnotcat ?

**Comment by tomnotcat** [comment]
@Gutyn No, I have not find the solution, Since I'm not good at Android Native Coding.

**Comment by tomnotcat** [comment]
I think react-native-navigation does not handle Activity lifecycle properly when statusBar is hidden.
