### ISSUE TITLE
Android fails to build after upgrading to RN v59.10

### ISSUE THREAD

**Issue by Xesme** [wix/react-native-navigation#5267]
### Issue Description
I'm working on an existing RN (v55.4) project that is using RNN. We upgraded to RNN v2.22.3 last week and then upgraded our RN version to v59.10. I have been banging my head against a wall trying to resolve the Android build errors for 3 days. 

Any help is much appreciated. I have looked up some of these issues, but they seem to be related to assembling a release. This is just for building. 

### Steps to Reproduce / Code Snippets / Screenshots

<img width="666" alt="Screen Shot 2019-07-08 at 10 24 14 AM" src="https://user-images.githubusercontent.com/24839005/60829902-e1e50a00-a16a-11e9-8376-2888bb6e561e.png">

Lmk if you need to see any other files. I'm at a loss of what to do next. 

### Environment
* React Native Navigation version: 2.22.3
* React Native version: 59.10
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Studio, Android devices, Development

**Comment by amdrade** [comment]
I have the same problem.

**Environment**

- React Native Navigation version: 2.22.3
- React Native version: 60.0
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Android Studio, Android devices, Development

**Comment by Xesme** [comment]
I fixed these errors by updating the RN missingDimensionStrategy from 55 to 57_5

app/build.gradle 
`        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57_5"
`

**Comment by amdrade** [comment]
> I fixed these errors by updating the RN missingDimensionStrategy from 55 to 57_5
> 
> app/build.gradle
> ` missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57_5"`

Not work for me :( 

`FAILURE: Build failed with an exception.
 What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
 Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
    Could not resolve project :react-native-navigation.
     Required by:
         project :app
       Unable to find a matching variant of project :react-native-navigation:
          - Variant 'reactNative56DebugApiElements':
              - Required RNN.reactNativeVersion 'reactNative57_5' and found incompatible value 'reactNative56'.
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'`

**Comment by Xesme** [comment]
What does your java compiler look like?

**Comment by amdrade** [comment]
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

**Comment by Xesme** [comment]
Sorry, I mean within the Android Studio window. You should be able to open the compiler to see the issues associated with each library. Like my screenshot in the original issue. 

You may need to downgrade to RN v59.10 btw v60 may not be supported yet.

**Comment by amdrade** [comment]
I downgrade to RN v59.9 but not work

> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed

**Comment by losheredos** [comment]
Same issue here .. :/
