### ISSUE TITLE
Push screen not working from side menu

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#527]
### Issue Description
Push screen not working from side menu

### Steps to Reproduce / Code Snippets / Screenshots

user this.props.navigator.push({}); case expception

---
### Environment
* React Native Navigation version: 2 exp 142
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by guyca** [comment]
You can't push from sideMenu. Instead, send a `deepLink` and push from the relevant screen. It's described in the wiki. A couple of issues were previously opened regarding this matter.
