### ISSUE TITLE
Cannot change topBar component 

### ISSUE THREAD

**Issue by ywongweb** [wix/react-native-navigation#5272]
### Issue Description

Changing topbar component when navigating between screens is not working. Here is what I observed so far.

**Doesn't work:**
Setting the new topbar component in `options` of the `.push('id', options)` call
Setting the new topbar component in `static options()` in the to-be-pushed screen

**Partially working:**
Setting the new topbar component in a `mergeOption` call in the to-be-pushed has no immediate effect, but if you navigate back to the first screen. You can see the header updates to the new one.

### Steps to Reproduce / Code Snippets / Screenshots

Sample project. 
https://github.com/ywongweb/rnnPlayground

Just un comment the code in Home.js or ScreenOne.js to see the observations above.

---
### Environment
* React Native Navigation version: 2.22.3
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): ios (not tested on Android)
* Device info (Simulator/Device? OS version? Debug/Release?): Sim

**Comment by guyca** [comment]
Fixed in v4
