### ISSUE TITLE
[Android] - Cannot set app orientation to portrait after installing RNN

### ISSUE THREAD

**Issue by Xesme** [wix/react-native-navigation#5276]
### Issue Description
After upgrading to RNN v2.22.3 I can no longer force my (Android) app to stay in portrait mode. I have set everything within the iOS and Android files according to the RN docs, and this issue only appeared after installing the newest version of this library. Any help is appreciated.

### Steps to Reproduce / Code Snippets / Screenshots

1. Install the newest version of this library and lock orientation for iOS and Android. 
2. Observe the ability to switch the app into landscape mode. 

Steps to lock in Android: 

1. Add to `android:screenOrientation="portrait"` to your <application> tag within AndroidManifest.xml:

Ex: 
```
<application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:screenOrientation="portrait"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:fullBackupContent="false"
      android:theme="@style/AppTheme">
```
2. Rebuild! 

Steps for iOS: 
1. Set device orientation within Xcode: 
![image](https://user-images.githubusercontent.com/24839005/61088627-a3ab4d00-a3ed-11e9-9bc8-7cd7378dd305.png)
2. Rebuild!

---
### Environment
* React Native Navigation version: 2.22.3
* React Native version: 59.10
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, all OS

**Comment by andrewsadowski** [comment]
I've been having a similar issue.  Unable to force orientation to portrait, even though I've added all the orientation configurations for each platform in their respective files.  I've also added RNN specific orientation configuration, which still hasn't managed to force the application to stay in portrait mode.

**Comment by esbenvb** [comment]
The only way I've made it work, was to add `layout: { orientation: ['portrait'] }` to the `options` on every single screen I use in the app. 

First I tried putting the layout option in the `options` of the `stack` or `bottomTabs` of my `root`, but, that did not help.

IMHO, it's really an anti-pattern that RNN does not obey the restrictions you set in the `AndroidManifest`. Especially the equivalent setting on iOS is actually working as expected with RNN, I think it should be the same on Android.

Example:

```tsx
export class MyScreen extends Component<Props, State> {
  static options = (): Options => ({
    topBar: {
      visible: false,
      drawBehind: true,
    },
    statusBar: {
      style: 'light',
    },
    layout: {
      orientation: ['portrait'],
    },
  })
```

**Comment by Xesme** [comment]
Thanks! This worked for me. I wish it didn't have to be defined in each screen, since there is a way to set orientation natively. Seems like a bug, but this work around works for the time being.

**Comment by esbenvb** [comment]
@Xesme actually you can fix it once and for all...

Run this right before setting your root view

```js
        Navigation.setDefaultOptions({
          layout: { orientation: ['portrait'] },
        })
```

**Comment by esbenvb** [comment]
Please close if the above solved your problem :)

**Comment by joshperry131** [comment]
@esbenvb Your suggestion unfortunately does not work for me.

I have set the screen orientation option in the AndroidManifest.xml and in Navigation.setDefaultOptions called within a registerAppLaunchedListener but **cannot lock the orientation of my device on android**.

I have tested on simulator and multiple physical android devices, I have built and rebuilt the app, cleared every cache under the sun but nothing has any effect :'(

I don't think this issue is stale unless someone can enlighten me.

**Comment by atifaziz1** [comment]
> Run this right before setting your root view

This doesn't work for me.
