### ISSUE TITLE
disable the navBar "Back" button label.

### ISSUE THREAD

**Issue by creative-git** [wix/react-native-navigation#5281]
How to disable the navBar "Back" button label.?
when i push a screen, there will be the title of the previous screen next to the back button. i want to remove that. any tip please ?

### Environment
* React Native Navigation version: 2.22.3
* React Native version: .59.10
* Platform(s) (iOS, Android, or both?): BOTH
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by Jazqa** [comment]
It's missing from [the documentation](https://wix.github.io/react-native-navigation/#/docs/styling?id=options-object-format), but changing the boolean `topBar.backButton.showTitle` should work.

```
topBar: {
  backButton: {
    showTitle: false
  }
}
```
