### ISSUE TITLE
Navigate to component out of bottomTabs

### ISSUE THREAD

**Issue by Stormsher** [wix/react-native-navigation#5284]
Hi, I need to make something like invisible bottomTab, and push there a component.
I want to navigate screen not pushing it in one of the currently defined bottomTabs (and make all of bottomTabs non-active) - are there any way to do it with react-native-navigation?And  I don't want to hide bottomTabs on that screen!

**Comment by sergei-zelinsky** [comment]
Hey @Stormsher,
I'd like to know too. I have the same use-case 🙂

As an alternative solution, I tried to set different roots (simple stack and bottom tabs), but it was too slow switching between these roots, in my case. So, I refused it.

Thanks!

**Comment by Stormsher** [comment]
Actual! Please help..

**Comment by ashokkumar88** [comment]
@Stormsher did you find any solution?
