### ISSUE TITLE
[v3] setDefaultOptions topBar drawBehind not respected

### ISSUE THREAD

**Issue by danilobuerger** [wix/react-native-navigation#5286]
### Issue Description

When setting `topBar: { drawBehind: true }` as default option, it is not respected on Android. Only when setting it via `static options ()` it is being applied.

### Steps to Reproduce / Code Snippets / Screenshots

To reproduce, use v3 playground app with following diff:

```
diff --git a/playground/src/commons/Options.js b/playground/src/commons/Options.js
index 5a7c2ebe..01b8a26a 100644
--- a/playground/src/commons/Options.js
+++ b/playground/src/commons/Options.js
@@ -7,6 +7,9 @@ const { useSlowOpenScreenAnimations } = require('../flags');
 const SHOW_DURATION = 230 * 8;
 
 const setDefaultOptions = () => Navigation.setDefaultOptions({
+  topBar: {
+    drawBehind: true,
+  },
   layout: {
     backgroundColor: Colors.background,
     orientation: ['portrait']
```

---
### Environment
* React Native Navigation version: v3 alpha 2
* React Native version: 0.60
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator API 28

**Comment by danilobuerger** [comment]
Not Stale

**Comment by lucasbeef** [comment]
I can confirm, it happens to me on 3.1.2
The statusBar also behaves the same way.

The following doesn't work (I try to achieve a full screen app) : 
```  
Navigation.setDefaultOptions({
    layout: {
      visible: false,
      drawBehind: true,
    },
    statusBar: {
      visible: false,
      drawBehind: true,
    },
  });
```
 However when specified in the options of the component it works fine.

**Comment by manuhook** [comment]
@guyca I can confirm also this behavior.
It's not working on 3.2.0

**Comment by manuhook** [comment]
Not Stale

**Comment by manuhook** [comment]
Still present on 3.7.0

**Comment by manuhook** [comment]
Fixed on 4.0.7 🎉

**Comment by manuhook** [comment]
Hi @guyca !
It's fixed for **topBar and drawBehind**,
but not for **statusBar and drawBehind** as mentionned in this issue, 
would you like me to open a new issue ?
Thank you 🙏

**Comment by guyca** [comment]
@manuhook Yes, please open an issue and mention me. Thanks 👍

**Comment by mayconmesquita** [comment]
@guyca @manuhook I opened the issue.

#5971
