### ISSUE TITLE
Using RNN with apollo client,

### ISSUE THREAD

**Issue by yassinebridi** [wix/react-native-navigation#5287]
### Issue Description

How can i use RNN with Apollo client, especially that i'm gonna use Apollo for local state managments too, negating the need for redux,
so should i initialize the apollo provider in the "registerComponent" or in the app component.
### Environment
* React Native Navigation version: 2.22.3
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Genymotion, os: Android 5.1.0

**Comment by danilobuerger** [comment]
```
export function registerComponent<P, TCache>(
  name: string,
  Comp: React.ComponentType<P>,
  client: ApolloClient<TCache>,
) {
  Navigation.registerComponent(
    name,
    () => (props) => (
      <ApolloProvider client={client}>
        <Comp {...props} />
      </ApolloProvider>
    ),
    () => Comp,
  );
}
```

**Comment by yassinebridi** [comment]
thanks @danilobuerger,
