### ISSUE TITLE
[v3] topBar is draggable

### ISSUE THREAD

**Issue by sijad** [wix/react-native-navigation#5290]
### Issue Description

topBar is draggable

![rec](https://user-images.githubusercontent.com/7693001/61351706-b1931f00-a880-11e9-9a66-7d46bd5a9c5e.gif)

### Steps to Reproduce / Code Snippets / Screenshots

compile and install current v3 playground and drag topBar

---
### Environment
* React Native Navigation version: v3 alpha2
* React Native version: v0.60.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung s5 Android 6.0.1

**Comment by guyca** [comment]
Should be fixed in .alpha3
Thanks for reporting @sijad 👍
