### ISSUE TITLE
[v3] [iOS] installation using ReactNativeNavigation.podspec causes the error

### ISSUE THREAD

**Issue by nastyakitsune** [wix/react-native-navigation#5293]
### Issue Description

It's impossible to install react-native-navigation using the pod spec file. 

### Steps to Reproduce / Code Snippets / Screenshots

[!] Error installing ReactNativeNavigation
[!] /usr/bin/git clone https://github.com/wix/react-native-navigation.git /var/folders/zj/zyyysqjj02g3zbjyr_gdzdgr0000gp/T/d20190718-19103-1oshibw --template= --single-branch --depth 1 --branch 3.0.0-alpha.3

Cloning into '/var/folders/zj/zyyysqjj02g3zbjyr_gdzdgr0000gp/T/d20190718-19103-1oshibw'...
warning: Could not find remote branch 3.0.0-alpha.3 to clone.
fatal: Remote branch 3.0.0-alpha.3 not found in upstream origin

### Environment
* React Native Navigation version: 3.0.0-alpha.3
* React Native version: 0.60.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by TiagoCoelhoB** [comment]
i temporary solved by updated field "version" on react native navigation package.json
:=> node_modules/react-native-navigation/package.json

"version": "3.0.0-alpha.3" to "version": "3.0.0-alpha.3-snapshot.404"

**Comment by nastyakitsune** [comment]
@TiagoCoelhoB I know how to fix it locally, but it's not a solution at all.

**Comment by TiagoCoelhoB** [comment]
yap, they will fix in the next version
