### ISSUE TITLE
[v2] Custom topBar button not triggering events

### ISSUE THREAD

**Issue by agreyfield91** [wix/react-native-navigation#5294]
### Issue Description

I have a topbar in my home screen with a custom navigation button. When this button is clicked, I want `myFunction()` to run. But the custom button doesn't seem to trigger `navigationButtonPressed()` :

```js
static options(passProps) {
	return {
		topBar: {
			rightButtons: [
				{
					component: {
                                               // My custom button
						name: 'Button'
					},
				},
			],
		},
	};
}

navigationButtonPressed({ buttonId }) {
	this.myFunction();
}

myFunction = () => {
	// Code I want to run when nav button is clicked, but doesn't
};
```

I tried the solution at #3648, doing the following:

```js
static options(passProps) {
	return {
		topBar: {
			rightButtons: [
				{
					component: {
                                               // My custom button
						name: 'MenuButton',
                                                passProps: {
							onClick: () => this.myFunction(),
						},
					},
				},
			],
		},
	};
}
```

But it didn't work - My linter tells me `Property myFunction does not exist on typeof Home`, where Home is my component. What am I doing wrong?

### Environment
* React Native Navigation version: 2.18.3
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android emulator, 8.0

**Comment by umkhan65** [comment]
Any luck?
I'm having same issue
React Native Navigation version: 2.26.5
React Native version: 0.59.10

**Comment by chawchaw** [comment]
Have you tried with 'id' ?

```
component: {
  id: 'menu',
  name: 'MenuButton',
}
```

**Comment by umkhan65** [comment]
This worked for me


constructor(props){
super();
Navigation.events().registerNavigationButtonPressedListener(this.navigationButtonPressed);
}

navigationButtonPressed({ buttonId }) {
        console.log(buttonId);
        if (buttonId === "signOut") {
            //your action
        }
    }

topBar: {
  title: {
   text: 'NewsFeed',        
   color: '#fccb00',
   alignment: "center",
   hideOnScroll: true,
  },
  background: {
   color: '#063567'
 },
 rightButtons: [
  {
   title: 'Sign Out',
   id: 'signOut',
   icon: require('../assets/SignOut.png'),
   text: 'Sign Out',
  }
 ]
}

**Comment by ryanpag3** [comment]
This is still an issue for me as well. Why can't we listen to button evens while using a component?
