### ISSUE TITLE
How to setup react native navigation android react native 0.60.3

### ISSUE THREAD

**Issue by suupham2506** [wix/react-native-navigation#5296]
### Issue Description

[ENTER DESCRIPTION HERE]

### Steps to Reproduce / Code Snippets / Screenshots

[I tried to set up react native navigation v2 on react native 0.60.3 but I don't know how to refactor code in MainApplication.java properly because PackageList autolinking.
Is there someone set it up successfully? 
]

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.60.3
* Platform(s) (iOS, Android, or both?): Android

**Comment by TolgaCagin** [comment]
Hi @suupham2506 check react native navigation discord page, @sijad shared example project codes, you can use it

**Comment by MIREX** [comment]
@TolgaCagin, Could you share it for us here?

**Comment by sijad** [comment]
Here: [zip.zip](https://github.com/wix/react-native-navigation/files/3410992/zip.zip)

Also [v3 playground](https://github.com/wix/react-native-navigation/tree/v3/playground) is a very good example.

**Comment by suupham2506** [comment]
@sijad @TolgaCagin I do as your example but I got the same error.
It's not working around.

**Comment by JerakRus** [comment]
It doesn't work for me either, did you find any solution?

**Comment by andrey-zelenin** [comment]
use v3 alpha (https://github.com/wix/react-native-navigation/releases/tag/3.0.0-alpha.4-snapshot.407)

**Comment by awnigharbia** [comment]
I have the same issue here. Do you find a solution yet?
