### ISSUE TITLE
AsyncStorage not working in app.js

### ISSUE THREAD

**Issue by bfine9618** [wix/react-native-navigation#530]
### Issue Description

Asyncstorage is not accessing stored information after the app is closed. I am trying to circumnavigate the login screen if a user has already logged in. Any suggestions or new ways to access the stored info?
(https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

import {
  Platform, AsyncStorage,
} from 'react-native';
import {Navigation} from 'react-native-navigation';

// screen related book keeping
import {registerScreens} from './screens';
registerScreens();
var user;
var type;

try{
  AsyncStorage.setItem('type', 'Student');
  AsyncStorage.getItem('user', (result) => {
  user = result;
  type = AsyncStorage.getItem('type');});
  console.log(AsyncStorage.getItem('type'));
} catch(error){
  console.log(error);
}

if(user == null){
  Navigation.startSingleScreenApp({
    screen: {
      screen: 'example.welcome',
      title: 'Navigation',
      navigatorStyle: {
      navBarBackgroundColor: '#3498db',
      navBarTextColor: '#ffffff',
      navBarSubtitleTextColor: '#ffffff',
      navBarButtonColor: '#ffffff',
      statusBarTextColorScheme: 'light',
      navBarHidden: true, // make the nav bar hidden
      }
    },
    drawer: {
     left: {
             screen: 'example.SideMenu',
             passProps: {
               user: {
                 fname: "Jorge",
                 lname: "Valdez",
                 },
               type: 'Student',
             },
      },
      disableOpenGesture: true,
    }
  });
} else {
  Navigation.startSingleScreenApp({
    screen: {
      screen: "example.stuInitial",
      title: '',
      backButtonTitle: "",
      passProps: {
        user: user._bodyInit,
        type: type,
      },
      navigatorStyle: {
        navBarBackgroundColor: '#3498db',
        navBarTextColor: '#ffffff',
        navBarSubtitleTextColor: '#ffffff',
        navBarButtonColor: '#ffffff',
        statusBarTextColorScheme: 'light'
      },
      animated: true,
    },
    drawer: {
      left: {
              screen: 'example.SideMenu',
              passProps: {
                user: user._bodyInit,
                type: type,
              },
       },
    },
    disableOpenGesture: false,
  });
}

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.39
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): simulator

**Comment by guyca** [comment]
Hey @bfine9618 
Thanks for the detailed issue, but if you paste code, can you please use a code block and shown [here](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Regarding AsyncStorage. Afaik your app can't run any code on iOS after it is closed by the user although there are some exceptions to that  like music players etc. You shouldn't wait for the last moment to store data because you can't predict your app will close properly. It can get shut down unexpectedly by the system due to memory concerns or the battery can run out.

I'm closing since this isn't related to RNN.

**Comment by witalobenicio** [comment]
@guyca I'm trying to use Asyncstorage in App.js before I start an App (Navigation.startSingleScreenApp) and it always return null;
