### ISSUE TITLE
[V2][Android] setRoot white screen before rendering

### ISSUE THREAD

**Issue by rverbytskyi** [wix/react-native-navigation#5308]
### Issue Description

On app launch, I set root with a splash screen and after loading data, I set root with bottomTabs. I set call `Navigation.setDefaultOptions` with `waitForRender` flag set to true. On iOS, screens are rendered one after another while on Android after calling `Navigation.setRoot({ ... })`  there's a white screen splash for a moment before bottomTabs are rendered.

### Steps to Reproduce / Code Snippets / Screenshots

Screenshots:
![20190722_191903](https://user-images.githubusercontent.com/33003758/61648139-857c0180-acb7-11e9-8c52-51a237fabed8.gif)

Navigation setup:
```js
Navigation.events().registerAppLaunchedListener(() => {
  registerScreens()
  Navigation.setRoot({
    root: {
      component: {
        name: 'splashScreen',
      },
    },
  })
})

function registerScreens() {
  Navigation.setDefaultOptions({
    layout: {
      backgroundColor: 'transparent',
    },
    animations: {
      setRoot: {
        waitForRender: true,
      },
      put: {
        waitForRender: true,
      },
      push: {
        waitForRender: true,
      },
    },
    statusBar: {
      backgroundColor: 'rgba(0, 0, 0, .2)',
      drawBehind: true,
      visible: true,
      style: 'light',
    },
  })

export function goToApp() {
  Navigation.setRoot({
    root: {
      bottomTabs: {
        children,
      },
    },
  })
}
```

---
### Environment
* React Native Navigation version: 2.22.3
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung Galaxy S8, Android 9

**Comment by guyca** [comment]
When setRoot is called, the previous root is destroyed and removed from hierarchy.
Setting splash screen from Js is problematic since it will be visible only after your bundle is parsed.

You should set your splash screen in native like we do in the [playground app](https://github.com/wix/react-native-navigation/blob/master/playground/android/app/src/main/java/com/reactnativenavigation/playground/MainActivity.java#L17).

**Comment by rverbytskyi** [comment]
@guyca The problem is not with a splash screen. The problem is that on Android after setRoot was set the second time with the option `waitForRender: true` previous root has been deleted without waiting for rendering the second root. That's why there's a white screen between the first screen and the second one.

Please, take a look at the unit test I created in PR #5309. More precisely, at [this commit](https://github.com/wix/react-native-navigation/pull/5309/commits/f097397955b199431463acd81138f893f52455d1)
