### ISSUE TITLE
[v3] hidden Topbar conflicts with Sidemenu and Translucent

### ISSUE THREAD

**Issue by sijad** [wix/react-native-navigation#5311]
### Issue Description

when TopBar visibility is false in default options, showing side menu programmatically only side menu background shows up. swipe opening still works.

### Steps to Reproduce / Code Snippets / Screenshots

1. open playground app
2. in options tab press **Hide TopBar in DefaultOptions**
3. press **Statusbar** button
4. press **BottomTabs** button
5. in **Statusbar** screen try open left or right side menu by pressing **OpenLeft** or **OpenRight** button

![rec](https://user-images.githubusercontent.com/7693001/61704056-27ebc180-ad58-11e9-9592-2dbec37ed610.gif)

---
### Environment
* React Native Navigation version: v3 alpha4
* React Native version: v0.60.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung s5 Android 6.0.1

**Comment by sijad** [comment]
also as you can see in above gif when topbar is hidden background of left sidemenu does not rendered.

**Comment by guyca** [comment]
Hey @sijad 
This isn't really a bug - `setDefaultOptions` overrides previous default options. The initial default options contain `layout.backgroundColor` which sets the default background color for components.

When we call `setDefaultOptions` for the second time, it overrides those options 🤷‍♂ 
I guess we can improve the playground app so this doesn't happen

**Comment by sijad** [comment]
the problem is not the background, when you try to open the sidemenu via `mergeOptions`, only sidemenu dark background shows up. in above gif it's clear that after pressing on `openRight` button, only dark background of right side menu shows up, and its contents (e.g. close button) does not...

**Comment by guyca** [comment]
gotcha, I'll check again 👍

**Comment by tunegov** [comment]
Found temp solution 

>   topBar: {
    visible: true,
    height: 0
  },

**Comment by guyca** [comment]
Fixed in `alpha.11`. Thanks for reporting @sijad 👍
