### ISSUE TITLE
weird top bar on android react native navigation v3 alpha

### ISSUE THREAD

**Issue by suupham2506** [wix/react-native-navigation#5316]
### Issue Description

Bug display topbar on android

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: ^3.0.0-alpha.3
* React Native version: 0.60.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android devices
![Screenshot_1564040865](https://user-images.githubusercontent.com/28852565/61856876-37504380-aeed-11e9-81b1-7c92948c7724.png)

**Comment by guyca** [comment]
Hey there, this bug should be fixed already. Please try the latest alpha - `3.0.0-alpha.6`
