### ISSUE TITLE
Get ref or native node handle of button in navigator bar

### ISSUE THREAD

**Issue by florianbepunkt** [wix/react-native-navigation#532]
Is there a way to specify a ref for a button in navigation bar or to get the button element?

I want to use a floating contextual menu in android (the button with the three little dots that show additional action). The way you have it in wix-navigation is a bit different since it does not alway render the actions as a contextual menu. But React native has a component for this in UIManager so it should be easy to setup – if it's possible to get a reference to the button pressed.

```js
UIManager.showPopupMenu(
      findNodeHandle(this.refs.refOfButton),
      ['action1', 'action2', 'action3'],
      this.handleError,
      this.handleOnPress,
    );
```

But in order to use this I need a ref to the element that is triggering the contextual menu.

To clarify: findNodeHandle() returns the native id of an element… so basically it would already do the trick if the onNavigatorEvent(event) would contain the id of the button / tab label / etc, that triggered the event.

**Comment by guyca** [comment]
Hey @florianbepunkt 
Add `showAsAction: 'never'` to each button you would like to show in the contextual menu. Additional options are shown in the [docs](https://github.com/wix/react-native-navigation/wiki/Adding-buttons-to-the-navigator)

**Comment by florianbepunkt** [comment]
@guyca Setting showAsAction: 'never' doesn't solve the problem… I probably should have describe dthe issue better.

this is the code:

```
this.props.navigator.showContextualMenu(
  {
    rightButtons: [
      {
        title: 'Add',
        id: 'add',
        showAsAction: 'never',
        icon: iconsLoaded['ios-more']
      },
      {
        title: 'Delete',
        id: 'delete',
        showAsAction: 'never',
        icon: iconsLoaded['ios-more']
      }
    ],
    onButtonPressed: (index) => console.log(`Button ${index} tapped`)
  }
);
```

what I want is NOT to have the icons in the navbar, but the little three dots that open a contextual menu with the action (add and delete in this case). for reference:

![android-action-bar-action-items](https://cloud.githubusercontent.com/assets/8314202/20866195/2ff61596-ba27-11e6-8ef5-0e481cac43a5.png)

I notice several issues

(1) If I don't specify an icon I get an error on android: `Unhandled Promise Rejection (id: 0): null is not an object (evaluating 'resolveAssetSource(button.icon(.uri')`
(2) the specified buttons show up in the navigator instead as a contextual menu (see screenshot) below. when I add more actions (liek 5 or 6), then two buttons are shown in the navbar, and the contextual menu shows with the other actions. so I guess, that the showAsAction: 'never' paramter is simply ignored…
(3) the title of my navbar is gone… I just see the buttons. when I click one of the buttons, the buttons are gone and the title appears again.

![screenshot_1480855004](https://cloud.githubusercontent.com/assets/8314202/20866213/e1657af6-ba27-11e6-8ca9-a22d7d434d5d.png)
