### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'com.reactnativenavigation.parse.TopBarOptions com.reactnativenavigation.parse.Options.topBar' on a null object reference

### ISSUE THREAD

**Issue by ZeitounCorp** [wix/react-native-navigation#5320]
### Issue Description

Fresh installation crashes on Android only with the error:
```
java.lang.NullPointerException: Attempt to read from field 'com.reactnativenavigation.parse.TopBarOptions com.reactnativenavigation.parse.Options.topBar' on a null object reference . 
```
---
### Environment
*React Native Navigation version: 2.26.0
*React Native version: 0.59.10
*Platform(s) (iOS, Android, or both?): Android
*Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by ZeitounCorp** [comment]
I'm getting the same error as in #5319 using React-native 0.59.10 && react-native-navigation ^2.26.0
If someone could help me, it would be great
Thanks

**Comment by guyca** [comment]
Hey @ZeitounCorp, sorry for the trouble - fixed in 2.26.1

**Comment by esbenvb** [comment]
@guyca I the the error in 2.26.1 as well

**Comment by guyca** [comment]
Sorry for the confusion, publishing 2.26.2 now

**Comment by ZeitounCorp** [comment]
Thanks a lot It works great with react-native-navigation@2.26.2 🎉

**Comment by mwq27** [comment]
Fiiiiinnallly, was driving me nuts getting this error. Thanks for the update 💯
