### ISSUE TITLE
[V3] Cannot switch to different tab on android

### ISSUE THREAD

**Issue by Estebank94** [wix/react-native-navigation#5323]
### Issue Description

(I am sorry for how the code is displayed here but I don't know how to fix it)

I upgraded from V1 to V3 successfully .
In iOS it works perfectly, however in Android I am having some issues.
First and most important: When I press on a bottom tab icon to switch tab, it animates the icon I selected for a second and then the first icon is quickly selected again and the new tab is never switched.
Secondly: The styles are not equally applied. For example, the topbar doesn't hide in Android like it does correctly in iOS. (Screenshots below)

Pushing new screens works correctly.

Also, I would like to point out that I am using [Jetifier](https://github.com/mikehardy/jetifier) 
and I have to run the app using `npx react-native run-android `
I don't know if that could be related to the issue.

###  Code Snippets

This is how I define the screens:

I am sorry for how the code is displayed here but I don't know how to fix it.

`Navigation.setDefaultOptions({
      topBar: {
        visible: true,
        title: {
          fontSize: navBarTextFontSize,
          color: '#343A3F',
          fontFamily: navBarTextFontFamily,
        },
        backButton: {
          icon: icons[icons.length - 1],
          color: '#343A3F',
          visible: true
        },
        background: {
          color: '#FFF'
        }
      },
      bottomTabs: {
        visible: true,
        currentTabIndex: 0,
        currentTabId: 'currentTabId',
        backgroundColor: 'white'
      },
      bottomTab: {
        iconColor: '#9AACB6',
        selectedIconColor: '#54C76B',
        textColor: '#9AACB6',
        selectedTextColor: '#54C76B',
        fontFamily: navBarTextFontFamily,
        fontSize: 10
      }
    });
    Navigation.setRoot({
      root: {
        bottomTabs: {
          children: [{
            stack: {
              children: [{
                component: {
                  id: 'Home',
                  name: 'provi.Home',
                  options: {
                    topBar: {
                      title: {
                        text: 'Inicio'
                      },
                      visible: false
                    },
                    bottomTab: {
                      text: 'Inicio',
                      icon: icons[0],
                    }
                  }
                }
              }],
            }
          },
          {
            stack: {
              children: [{
                component: {
                  id: 'Categories',
                  name: 'provi.Categories',
                  options: {
                    topBar: {
                      title: {
                        text: 'Explorá'
                      },
                      visible: true
                    },
                    bottomTab: {
                      text: 'Explorá',
                      icon: icons[1],
                    }
                  }
                }
              }]
            }
          },
          {
            stack: {
              children: [{
                component: {
                  id: 'Cart',
                  name: 'provi.Cart',
                  options: {
                    topBar: {
                      title: {
                        text: 'Carrito'
                      },
                      visible: true
                    },
                    bottomTab: {
                      text: 'Carrito',
                      icon: icons[2],
                    }
                  }
                }
              }],
            }
          },
          {
            stack: {
              children: [{
                component: {
                  id: 'Orders',
                  name: 'provi.Orders',
                  options: {
                    topBar: {
                      title: {
                        text: 'Pedidos'
                      },
                      visible: true
                    },
                    bottomTab: {
                      text: 'Pedidos',
                      icon: icons[3],
                    }
                  }
                }
              }]
            }
          },
          {
            stack: {
              children: [{
                component: {
                  id: 'Account',
                  name: 'provi.Account',
                  options: {
                    topBar: {
                      title: {
                        text: 'Mi Cuenta'
                      },
                      visible: true
                    },
                    bottomTab: {
                      text: 'Mi Cuenta',
                      icon: icons[4],
                    }
                  }
                }
              }],
            }
          }]
        }
      }
    });`

Topbar is not hidden
![Screenshot_1564341321](https://user-images.githubusercontent.com/5116089/62011792-71bb1a00-b153-11e9-9991-3c291b3b0e47.png)

Topbar is hidden
![IMG_5646](https://user-images.githubusercontent.com/5116089/62011795-7bdd1880-b153-11e9-9e11-cb205601e290.PNG)

---
### Environment
* React Native Navigation version: 3.0.0-alpha.6
* React Native version: 0.55.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Nexus 5 API 26

**Comment by solonifer** [comment]
This issue appears if you use currentTabIndex on android.
If you remove this, then you can switch.

In my case, I tried to set currentTabIndex: 2 for central tab but removed it until they fix it.

**Comment by Estebank94** [comment]
Thanks! That solved it

**Comment by GioLogist** [comment]
@guyca I think you had the right call re-opening this. I just confirmed this is still an issue.

### Environment
React Native Navigation version: 3.7.0
React Native version: 0.61.4
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug
