### ISSUE TITLE
Navigation.Push(stackName,screenName) is creating Multiple Screen

### ISSUE THREAD

**Issue by vikassahutech** [wix/react-native-navigation#5327]
### Issue Description

Whenever I am clicking on deeplink and if app is already opened its creating multiple instance of a single screen at a time.

Please help to find out the possible reason behind this?

### Steps to Reproduce / Code Snippets / Screenshots

1. Navigate to screen 1 and then screen-2, 
2. Request for change password from screen-2
3. Minimise app and go to gmail which has deep link, after clicking over there it redirects to app with a new screen (screen-3) with multiple instance of the same.
4. If I click back it opens same screen-3 (till all instances closes) then it goes to screen-2 and screen-1 further.

**Calling first screen using below code**
```
 Navigation.setRoot({
        layout:{
            orientation:['portrait']
        },
        root: {
            stack: {
                id: baseStackId,
                children: [
                    {
                        component: {
                            name: ScreenId.Screen-1,  
                        },
                    },
                ],  
                options: {
                    topBar: {
                        drawBehind: true,
                        visible: false,
                        animate: false,
                    },
                    statusBar: {
                        visible: true,
                        drawBehind: false,
                        style: "light" 
                    },
                }
            }
        }
    })
```

**Calling screens using below code**
```
 Navigation.push(baseStackId, {
                    component: {
                      name: ScreenId.Screen3,
                      options: {
                        statusBar: {
                          visible: true,
                          backgroundColor: 'green',
                          drawBehind: false,

                        },
                      }
                    }
                  })
```

*** Dependencies ***
"dependencies": {
    "firebase": "^5.0.3",
    "lodash": "^4.17.11",
    "prop-types": "^15.6.2",
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-elements": "^0.19.1",
    "react-native-firebase": "^5.3.1",
    "react-native-iphone-x-helper": "^1.2.0",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-modal-datetime-picker": "^7.4.0",
    "react-native-navigation": "^2.3.0",
    "react-native-secure-key-store": "^2.0.2",
    "react-native-segmented-control-tab": "^3.3.1",
    "react-native-size-matters": "^0.2.1",
    "react-native-svg": "6.5.3",
    "react-native-svg-charts": "^5.2.0",
    "react-native-tabbar-bottom": "^1.0.4",
    "react-native-vector-icons": "^6.1.0",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1"
  },

---
### Environment
* React Native Navigation version: ^2.3.0
* React Native version:0.56.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all device/all version with both release and debug build

**Comment by monilyf** [comment]
Have you found the solution for this?, I'm facing same issue.
