### ISSUE TITLE
Navigation events delayed until animation, fetching or scrolling completes

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#5328]
### Issue Description

Cant navigate out of screen when active animation, data fetching or scrolling

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 2.26.2
* React Native version: 0.60.4
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by guyca** [comment]
Well that probably means something is hogging the Js thread, try profiling it for more information.
