### ISSUE TITLE
BottomTabs backHandler best practice. componentDidAppear not reliable

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#5329]
### Issue Description

I used componentDidAppear with BackHandler to return null.
But result is unstable.
componentDidMount not working with tabs.
What is best practice to forbid Back button quit app when in root of bottom tabs?

### Steps to Reproduce / Code Snippets / Screenshots
```
  componentDidAppear() {
    BackHandler.addEventListener("hardwareBackPress", () => {
      return true;
    });
  }

  componentDidDisappear() {
    BackHandler.removeEventListener()
  }
```

---
### Environment
* React Native Navigation version: 2.26.2
* React Native version: 0.60.4
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by Brianwebb22** [comment]
I cannot speak to best practices, but I was also having this issue and found moving addEventListener to the constructor was more reliable.
