### ISSUE TITLE
[V3-alpha.8][Android] TopBar Title custom component spacing

### ISSUE THREAD

**Issue by jinshin1013** [wix/react-native-navigation#5332]
### Issue Description
When using custom Title component on Android, the component takes up the right button space which makes the component "not centred". Started to see this problem when we updated RNN to v3. 

### Steps to Reproduce / Code Snippets / Screenshots
You can see that the Custom ProgressBar component takes up the rest of the TopBar apart from left button (not custom).

![Screen Shot 2019-07-30 at 11 20 11 am](https://user-images.githubusercontent.com/17612922/62093270-06408c00-b2bc-11e9-937a-560eaf23ac24.png)

Code snippet:
```tsx
Component.options = {
  topBar: {
    title: {
      name: privateRoutes.PROGRESSBAR,
      passProps: {
        currentStep: step,
        totalSteps: numOfProfileSteps,
      },
    },
  },
}
```

### Workaround
So at the moment the workaround is to use `background` option for Android. The caveat is that the background component doesn't seem to work so we have to use `background` option for Android and `title` option for iOS.

```tsx
Component.options = {
  topBar: {
    // FOR ANDROID ONLY
    background: {
      name: privateRoutes.PROGRESSBAR,
      passProps: {
        currentStep: step,
        totalSteps: numOfProfileSteps,
      },
    },
  },
}
```
---
### Environment
* React Native Navigation version: 3.0.0-alpha.8
* React Native version: 0.60.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by guyca** [comment]
Hey @jinshin1013 
Could you please upload a project with a reproduction? You can fork RNN and modify the playground app in your fork.
Thanks 👍

**Comment by jinshin1013** [comment]
Hey @guyca, sorry I was gonna create a reproduction after I made this issue but it just totally slipped. You can clone [the fork](https://github.com/jinshin1013/react-native-navigation) and I've added the changes on `v3` branch. It's under `Custom Title` bottom tab. Let me know if anything is unclear!
