### ISSUE TITLE
[v3-alpha.8][Android] Background custom component not reset

### ISSUE THREAD

**Issue by jinshin1013** [wix/react-native-navigation#5333]
### Issue Description
When using the `background` custom component, the component does not get reset/removed on the next screen on the same stack using.

### Steps to Reproduce / Code Snippets / Screenshots
```tsx
// Navigating from Screen A to B.
NavigationHelpers.pushTo(ScreenA.componentId, { name: ROUTE.ScreenB })

// Screen A navigation option
ScreenA.options = {
  topBar: {
    background: {
      component: { name: COMP_NAME }
    }
  }
}

// Screen B navigation option
ScreenB.options = {
  topBar: {
    background: {
      color: 'black'
    }
  }
}
```

---
### Environment
* React Native Navigation version: v3.0.0-alpha.8
* React Native version: 0.60.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by guyca** [comment]
Hey @jinshin1013 
I wasn't able to reproduce in the playground app. Could you please push a reproduction?

**Comment by jinshin1013** [comment]
Hey there, you are right I wasn't able to reproduce in the Playground app. I'll do some investigation on my project and follow up on you! Closed until then.
