### ISSUE TITLE
selectedIcon functionality still no support on Android?

### ISSUE THREAD

**Issue by msqar** [wix/react-native-navigation#5339]
### Issue Description

I'm trying to implement the selectedIcon functionality on Android as well and found out is not yet supported? Even on RRN latest ?

I'm adding it like this based on stack structure:

### Steps to Reproduce / Code Snippets / Screenshots

```js
options: {
        bottomTab: {
            text: i18n.t('messages'),
            icon: iconsMap['message-light'],
            selectedIcon: iconsMap['message-solid'],
            badgeColor: 'red',
            ...navigatorStyle
        }
}
```

If this is not supported, any idea on how can I achieve the same result?

Thanks

---
### Environment
* React Native Navigation version: 3.0.0-alpha.6
* React Native version: 0.60.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): 28 - Android 9 Pie

**Comment by svenlombaert** [comment]
Also looking for this one. Any way we can help?
