### ISSUE TITLE
Temporary solution for a custom functionality in BottomTabs

### ISSUE THREAD

**Issue by adnanbrq** [wix/react-native-navigation#534]
### Issue Description

Right now it is not possible to add a BottomTab which is acting as a Button.
If you don't know what I mean: Some apps out there have circle add Button in the middle which when pressed does not switch to a View but instead opens up a menu (overlayed maybe).

The way I thought of achieving this is a bit "hacky" but it should work.
Simple JS (no native at all) based Router / Navigation in combination with RN-Navigation (this).

The JS based Router will be used in combination with a custom created BottomTabBar to mimic the native behavior. When need to push Views then RN-Navigation comes in.

What do you think about it?

**Comment by guyca** [comment]
Hey @adnanbrq Thanks for the suggestion. I think we can achieve this by allowing Js to respond, and override if needed, clicks on BottomTabs. I suggest you add it to #468
