### ISSUE TITLE
How to track screens with Analytics using tab bar?

### ISSUE THREAD

**Issue by igortupini** [wix/react-native-navigation#5341]
### Issue Description

All tab bars are rendered into the screen simultaneously. This behaviour results in wrong Firebase Analytics reports. I'm used to track the current active screen when the component is mounted, but this doesn't seem to be a good option as all the tabs screen components are mounted at the same time.

So even if the user never opens a certain tab will be reported as if he did. How can I overcome this? Should I try send the current screen to analytics in other way than the component did mount?

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Both / Both

**Comment by jinshin1013** [comment]
Have you tried using `componentDidAppear`?

**Comment by igortupini** [comment]
> Have you tried using `componentDidAppear`? [Doc here](http://wix.github.io/react-native-navigation/#/docs/events?id=componentdidappear)

How do I get to use this method with functional components?
I'm using Hooks for my entire app

**Comment by jinshin1013** [comment]
You can put this in your functional component:

```tsx
React.useEffect(() => {
  const navigationEventListener = 
    Navigation.events().registerComponentDidAppearListener(({ componentId: id }) => {
      // Check whether the event is fired in this screen.
      if (componentId !== id) return
      // put your code here...
    })

  return () => {
    navigationEventListener.remove()
  }
}, [])
```
