### ISSUE TITLE
[V2] Resuming application from background failed

### ISSUE THREAD

**Issue by solonifer** [wix/react-native-navigation#5344]
### Issue Description

When coming from the background, the app restarts and initialized again.
Android destroys activities and RNN seems do not manage this.
How can this issue be solved?

Do you have a playground example of how to solve this? How can I restore the application? Not to initialize it?

When using a third-party library for picking an image, NavigationActivity seems to be destroyed and there is no return to this activity after selecting image and app restarts.

### Steps to Reproduce / Code Snippets / Screenshots

Set "Do not keep activities" and try to resume application to the same state it was before.

---
### Environment
* React Native Navigation version: 2.26.2
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): Happen on simulator and device, if i use "Do not keep activities" - it happen 100% of a time

**Comment by zabojad** [comment]
I'm seeing the same thing. It happens only when exiting the app with the device back button. If you use the device home button and then come back to the application from background, the problem does not appear. @solonifer do you confirm the exact same behavior on your end?

**Comment by solonifer** [comment]
Hi @zabojad - Activate "Do not keep activities" in your android settings and you will see that app is not coming from background, but restarting.

With "Do not keep activities"  - it doesn't matter if you press back or any other usage, it happen 100% of the time.
