### ISSUE TITLE
Shared Element Transition not working in android

### ISSUE THREAD

**Issue by ashokkumar88** [wix/react-native-navigation#5349]
### Issue Description
The Shared Element transition for android not working. 

---
### Environment
* React Native Navigation version: Latest
* React Native version: 0.59
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device/Release

**Comment by rendomnet** [comment]
@ashokkumar88 why closed? I have this issue too. On android crashes

**Comment by ashokkumar88** [comment]
@rendomnet For me it is not crashing. But in V2 the Shared Element Transition for android is not fully working as in V1. It is still under development.

**Comment by ashokkumar88** [comment]
@rendomnet see this thread. The Phase 3 is still need to completed. 
https://github.com/wix/react-native-navigation/issues/3602
