### ISSUE TITLE
Add isModalInPresentation property for modals

### ISSUE THREAD

**Issue by jfrolich** [wix/react-native-navigation#5352]
The new iOS default presentation style for modals is `pageSheet`. Pagesheets can be dismissed by swiping them down. However in some cases you'd like to prevent this. The new property `isModalInPresentation` allows for this.

It would be great to be able to set this property on the ViewController using a react-native-navigation API. Any thoughts? I don't have much experience with ObjC/UIKit, but willing to have a shot at this.

**Comment by jfrolich** [comment]
Not stale.

**Comment by Rybachello** [comment]
Not stale.

**Comment by jfrolich** [comment]
Related PR: #5534

**Comment by jfrolich** [comment]
Not inactive
