### ISSUE TITLE
[v3] screen mounted twice

### ISSUE THREAD

**Issue by danielgindi** [wix/react-native-navigation#5359]
### Issue Description

After calling:
```js

    Navigation.setStackRoot(this.props.componentId, {
      component: {
        name: 'screenName',
        options: {
        },
      },
    });
```

It's animating to the screen correctly, but after 0.5 seconds another instance of the same component is created, the old one disposed (componentWillUnmount), and the new one mounted instead.

I don't know if this is intentional, but this cases a lot of componentDidMount code to be run twice.

This didn't happen with RNN v2 (RN 0.59.10)

---
### Environment
* React Native Navigation version: 3.0.0-alpha.7-snapshot.434
* React Native version: 0.60.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone X 11.4

**Comment by guyca** [comment]
Hey @danielgindi, thanks for reporting. Can you please verify if this happens in the playground app as well?

**Comment by Jazqa** [comment]
#5358 seems to fix this

**Comment by ItsNoHax** [comment]
Closing this as it should be fixed in master! Similar to: https://github.com/wix/react-native-navigation/issues/5355

Fixed by #5358

**Comment by danielgindi** [comment]
@ItsNoHax Is the fix coming to v3 as well?

**Comment by ItsNoHax** [comment]
Did you try 3.0.0-alpha.11-snapshot.447 @danielgindi

**Comment by danielgindi** [comment]
@ItsNoHax Just did, working :-)
Thank you!

**Comment by danielgindi** [comment]
Although it is completely broken on Android, not compiling due to missing classes.
