### ISSUE TITLE
redux navigation

### ISSUE THREAD

**Issue by Johan-dutoit** [wix/react-native-navigation#536]
I'd like to do navigation via the redux workflow instead of having to pass the navigator into every component via props.

Is there a way to navigate outside of a component?
ie.  using an action.

**Comment by guyca** [comment]
Will be supported soon. Each screen/component won't have a navigator injected to its props. Instead, you'd be able to call static methods from `Navigation`.

**Comment by SudoPlz** [comment]
I'm waiting for this one SO badly...!!!

**Comment by Johan-dutoit** [comment]
This would be amazing!  Do you guys need any help in building this I am happy to contribute.

**Comment by guyca** [comment]
@Johan-dutoit Thanks a lot for the offer!
The project is in an interesting state right now. We're focusing on solidifying the projects infra, mainly e2e and the core native logic that drives the project - this is done in the **v2** branch which isn't open for contributions yet.

As a result of the shift in focus to v2, the development of master branch has slowed down a bit. We try not to release new features, and mostly fix bugs. If there's a bug you'd like to fix or contribute a small feature, you're welcome to ping me at [discord](https://discord.gg/DhkZjq2)!
