### ISSUE TITLE
bottom tab cannot be hidden in a stack layout that is within a bottom tab layout

### ISSUE THREAD

**Issue by idanlo** [wix/react-native-navigation#5364]
### Issue Description
I have my main layout as a bottom tab layout and one of the tabs is a stack layout, I have my own custom tab bar (because of things that react-native-navigation does not support that I need) so what I do in the bottom tab options is hide the bottom tab with `visible: false` and `drawBehind: true`, all the tabs work fine but when navigating to the tab that is also a stack layout there is a big white blank space where the react-native-navigation bottom bar should be, meaning that the bottom tab is hidden correctly but I cannot draw behind it.
*note* - this is only happening on IOS

### Steps to Reproduce / Code Snippets / Screenshots
create a layout like this -
```js
Navigation.setRoot({
    root: {
      bottomTabs: {
        id: 'Main',
        options: {
          bottomTabs: {
            visible: false,
            drawBehind: true,
            currentTabIndex: 4
          }
        },
        children: [
          {
            component: {
              name: 'Screen1',
              options: {
                bottomTabs: {
                  currentTabIndex: 0
                },
                bottomTab: {
                  text: 'A',
                  icon: require('./src/assets/images/blank.png')
                }
              }
            }
          },
          {
            stack: {
              options: {
                bottomTabs: {
                  currentTabIndex: 1
                },
                bottomTab: {
                  text: 'A',
                  icon: require('./src/assets/images/blank.png')
                },
                topBar: {
                  visible: false,
                  height: 0
                }
              },
              children: [
                {
                  component: {
                    name: 'Screen2'
                  }
                }
              ]
            }
          }
        ]
      }
    }
  });
```
create a custom bottom bar component that will be displayed in each tab screen, run the app, see that the `Screen1` screen works fine and then navigate to `Screen2` and see that there is a big white blank space below the custom bottom bar component.

this is how it looks on a regular screen with no special layout -
![image](https://user-images.githubusercontent.com/28350511/62622506-2ceb6c00-b927-11e9-8e3a-ca82a3415682.png)

this is how it looks on the stack layout screen tab -
![image](https://user-images.githubusercontent.com/28350511/62622551-4ab8d100-b927-11e9-990f-a18cf0f7e775.png)

---
### Environment
* React Native Navigation version: 3.0.0-alpha.11
* React Native version: 0.60.4
* Platform(s) (iOS, Android, or both?): problem occurs in IOS,Android works fine.
* Device info (Simulator/Device? OS version? Debug/Release?): Both simulator and device with IOS.

**Comment by MANTENN** [comment]
It's going to be an error within your code. Check for marginBottom, perhaps a library you are using to accommodate spacing on bottom for the gesture based iPhones.

**Comment by idanlo** [comment]
@MANTENN this is not related to my code, as you can see in the image I have multiple tabs and all of them work well except the Home tab, which happens to be the one which is also a stack layout, all of the screens use the same wrapping View with the same style properties, if I put in my stack screen this component - 
```jsx
<View style={{
  position: 'absolute',
  bottom: 0,
  width: '100%',
  height: 80,
  backgroundColor: 'green'
}} />
```
this is what I get -
![image](https://user-images.githubusercontent.com/28350511/62778482-2c82da80-bab9-11e9-9b40-db4dbaa04f5b.png)
but if I put that exact View component with the same style properties on a different screen which has no layout and is just a component (within the bottom tab layout), this is what I get - 
![image](https://user-images.githubusercontent.com/28350511/62778539-50462080-bab9-11e9-9797-1d2272d6d91a.png)

**Comment by MANTENN** [comment]
What options did you set for the Navigation's layout?
Try: 
```javascript
Navigation.setRoot({
    root: {
      bottomTabs: {
        id: "authenticatedBottomTabBar",
        options: {
          bottomTabs: {
            visible: false,
            drawBehind: true
          },
        },
        // Components...
     }
   }
});

```

I used this solution: https://github.com/wix/react-native-navigation/issues/498#issuecomment-456218215

**Comment by MANTENN** [comment]
I had the same issue. I set the ```javascript
bottomTabs: {
  visible: false
}
```
to false inside the stack.

Certainly its unexpected behavior.

**Comment by MANTENN** [comment]
Try this:
```javascript
Navigation.setRoot({
    root: {
      bottomTabs: {
        id: 'Main',
        options: {
          bottomTabs: {
            visible: false,
            drawBehind: true,
            currentTabIndex: 4
          }
        },
        children: [
          {
            component: {
              name: 'Screen1',
              options: {
                bottomTabs: {
                  currentTabIndex: 0
                },
                bottomTab: {
                  text: 'A',
                  icon: require('./src/assets/images/blank.png')
                }
              }
            }
          },
          {
            stack: {
              options: {
                bottomTabs: {
                  currentTabIndex: 1
                },
                bottomTab: {
                  text: 'A',
                  icon: require('./src/assets/images/blank.png')
                },
                topBar: {
                  visible: false,
                  height: 0
                }
              },
              children: [
                {
                  component: {
                    name: 'Screen2',
                    options: {
                      bottomTabs: {
                        visible: false,
                      }
                    }
                  }
                }
              ]
            }
          }
        ]
      }
    }
  });
```

**Comment by MANTENN** [comment]
It seems like the options only apply to the screen they are configured on. In other words, children do not inherit those options, or they override them.

**Comment by idanlo** [comment]
@MANTENN this works, unfortunately it is very uncomfortable that I have to set this setting every time I am pushing to the stack instead of setting it globally once.

**Comment by MANTENN** [comment]
> @MANTENN this works, unfortunately it is very uncomfortable that I have to set this setting every time I am pushing to the stack instead of setting it globally once.

I agree, I also get a slide up animation. I tried to disable it, but couldn't figure it out.

**Comment by idanlo** [comment]
Not stale

**Comment by scaralfred** [comment]
@idanlo Have you tried to use the default options method? This solved everything on my app.

This is the method:

Navigation.setDefaultOptions({
    bottomTabs: {
      visible: false,
      drawBehind: true
    }
})

I placed it inside the app launch method, as below.
Navigation.events().registerAppLaunchedListener(() => { "here"})
