### ISSUE TITLE
[iOS/Android] setRoot promise resolves before React components are unmounted

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#5366]
### Issue Description

When using setRoot one would assume that when setRoot's promise resolves, the previous layout would be fully unmounted. This seems to not be the case. I'm seeing a delay of about 50-200ms between the promise resolving and the react components unmounting. This messes with my log out logic as I reset our redux store directly after changing root which then triggers several of the still mounted components to do a fetch.

### Steps to Reproduce / Code Snippets / Screenshots

This can be easily seen in a Redux app that logs the actions.

```js
export const setNotAuthenticatedRootLayout = () => async(dispatch) => {
  dispatch(setNotAuthenticatedRootLayoutStarted());
  try {
    Navigation.setDefaultOptions(DEFAULT_NOT_AUTHENTICATED_STYLING_OPTIONS);
    await Navigation.setRoot(NOT_AUTHENTICATED_LAYOUT);
    dispatch(setNotAuthenticatedRootLayoutSuccess());
  } catch (error) {
    dispatch(setNotAuthenticatedRootLayoutFailed(error));
  }
};

export const requestLogOut = () => async(dispatch) => {
  dispatch(requestLogOutStarted());
  try {
    // Other log out logic like resetting HTTP auth headers etc
    await dispatch(setNotAuthenticatedRootLayout());
    dispatch(requestLogOutSuccess()); <--- This action also resets my redux stores
  } catch (error) {
    dispatch(requestLogOutFailed(error));
  }
```

and in one of the mounted components:
```js
  componentWillUnmount() {
    console.log('We are unmounting!');
  }
```

Result:
We can see the console.log happening ~80ms after the promise resolved.

![before_guyca_fix](https://user-images.githubusercontent.com/4223434/62688972-2feb6880-b9ca-11e9-9c21-e6fb3d44aab4.png)

---
### Environment
* React Native Navigation version: 2.26.5
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator + Device, Debug + Release

**Comment by ItsNoHax** [comment]
@guyca has already mentioned how to fix this on Android:
![Selection_021](https://user-images.githubusercontent.com/4223434/62689265-c28c0780-b9ca-11e9-84ee-1861ab1f9821.png)

Which effectively fixes the problem:
![after_guyca_fix](https://user-images.githubusercontent.com/4223434/62689294-d20b5080-b9ca-11e9-9bf7-d62a4caec8e2.png)

**Comment by chuyeoh** [comment]
Facing this issue as well. 
Fortunately (If anyone is looking for a workaround) the Navigation.events are executing correctly. 
You can listen to the `componentDidDisappear` and execute your clean up there. 
unfortunately, you would have a lingering listener.

https://wix.github.io/react-native-navigation/#/docs/events

**Comment by dmexs** [comment]
Has this issue been fixed? I'm on 3.3.0 and wondering if it'll be fixed by upgrading.

If not I guess I'll use a short timer after setRoot before I modify my redux state.

**Comment by dmexs** [comment]
Upgraded to 6.4.0 and still noticing this issue.

I'm using the workaround as @chuyeoh to change redux state on componentWIllUnmount(). Using a timer was a bad idea that didn't work reliably. See below:

    componentWillUnmount () {
      if (this.props.user.logoutRequested) {
        this.props.dispatch({type: userConstants.LOGOUT})
      }
    }

**Comment by janroures** [comment]
this still happens to me on version 7.22.3 and RN v0.64.2

found any workarounds?
