### ISSUE TITLE
Dynamic interactions between overlay and tabbar

### ISSUE THREAD

**Issue by geroale** [wix/react-native-navigation#5369]
### Issue Description

Hi, I'm trying to get the following effect (I attach a gif) using the react native navigation v2.

I have a series of tabs and the "player", that is the part above that moves with the drag, is inserted in an overlay. (I have to use an overlay, as this component must be global throughout the app).

The solution I adopted for now was to use the overlay normally and create all the animation using javascript in the components, but, being too complex, I can't use the native driver, which I would absolutely like to keep (https: // facebook .github.io / react-native / blog / 2017/02/14 / using-native-driver-for-animated).

I would definitely prefer to use only one component for this player (I wouldn't want to point out a detachment when it is minimized or open, during the animation) and have a simple animation, so as to be able to use the native driver.

How could it be possible to obtain exactly this effect, which I report in the gif below?

### Steps to Reproduce / Code Snippets / Screenshots

![ezgif-2-7c95cef1a63b](https://user-images.githubusercontent.com/31098569/62724427-3e11a700-ba13-11e9-9a19-efd1b9b0f914.gif)

### Environment
* React Native Navigation version: 2.17.0
* React Native version: 0.59.10
* Platform(s): Both platforms, all emulators of course

**Comment by marf** [comment]
I want to create a similar effect in my app but I do not figure out how to do it, maybe it is a limitation of react-native-navigation?

**Comment by geroale** [comment]
Guys, no one can help me? @wix

**Comment by geroale** [comment]
@guyca

**Comment by farad4y** [comment]
This is possible with using gesture handler and overlay. We did these effect on our app.
