### ISSUE TITLE
react-native-codepush with react-native-navigation

### ISSUE THREAD

**Issue by Amurmurmur** [wix/react-native-navigation#537]
### Issue Description

When using react-native-codepush with react-native-navigation app just shows a blank screen. 

### Steps to Reproduce / Code Snippets / Screenshots

When using the following:
`App = codePush({ checkFrequency: codePush.CheckFrequency.ON_APP_RESUME, installMode: codePush.InstallMode.ON_NEXT_RESUME })(App);
export default App;`

If `App = codePush({ checkFrequency: codePush.CheckFrequency.ON_APP_RESUME, installMode: codePush.InstallMode.ON_NEXT_RESUME })(App);` removed, than its all fine :/

Is there any tutorial to use codepush with react-native-navigation

---
### Environment
* React Native Navigation version: 2.0.0-experimental.151
* React Native version: 0.38.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 10.1, Android 6.0.0

**Comment by beast** [comment]
Did you take a look at this? https://github.com/wix/react-native-navigation/issues/387 
Make sure your iOS appdelegate was setup correctly to load the bundle from codepush. Including your iOS code would help too.

**Comment by Amurmurmur** [comment]
Decided to give it another try, and problem hasnt been fixed :/ 
It is blank, when using code-push with RNN :/

Here is index.ios.js:
```
import App from './src'

const app = new App();
```
Here is 'src/index.js'
```
const store = configureStore();
registerScreens(store, Provider);

const navigatorStyle = {
	navBarTranslucent: true,
	drawUnderNavBar: true,
	navBarTextColor: 'white',
	navBarButtonColor: 'white',
	statusBarTextColorScheme: 'light',
	drawUnderTabBar: true
};

class app extends Component {

  constructor(props){
    super(props)
   
    store.dispatch(setStore(store))

    iconsLoaded.then(() => {
			this.startApp();
		});
    
  }

  componentDidMount(){
   if(!__DEV__)
     codePush.sync({
            updateDialog: true,
            installMode: codePush.InstallMode.ON_NEXT_RESUME
        });
  }

  startApp() {
		Navigation.startTabBasedApp({
			tabs: [
				{
					label: 'FirstTab',
					screen: 'app.FirstTab',
					icon: iconsMap['ios-search'],
					selectedIcon: iconsMap['ios-desktop'],
					title: 'FirstTab',
					navigatorStyle,
					
				},
				{
					label: 'SecondTab',
					screen: 'app.SecondTab',
				  icon: iconsMap['ios-search'],
					selectedIcon: iconsMap['ios-desktop'],
					title: 'SecondTab',
					navigatorStyle
				}
			],
			tabsStyle: {
				tabBarButtonColor: 'white',
				tabBarSelectedButtonColor: 'white',
				tabBarBackgroundColor: 'black'
			}
		});
	}
}


app = codePush({ checkFrequency: codePush.CheckFrequency.MANUAL })(app);

export default app;
```

**Comment by Amurmurmur** [comment]
Any ideas @guyca ?

**Comment by knot123** [comment]
@Amurmurmur I am using code-push with this library and I don't have any issues, this is the structure of my project maybe help you. first of all I am not calling the code push sync within a component, maybe the lifecycle of the component cause the problem you have.
1. I am importing App from my app.js
2. my app.js contains:
```javascript
...
import {registerScreens} from './Screens';
registerScreens();
iconsLoaded.then(() => {
    codePush.sync();
    startApp();
});
function startApp() {
    Navigation.startTabBasedApp({...});
}
```
 3. for adding stores to screens, I am doing it in Screens.js file which contains:
```javascript
import AppState from './stores/AppState'

export function registerScreens() {
    const store = new AppState();
    Navigation.registerComponent('app.Drawer', () => Drawer, store, Provider);
    Navigation.registerComponent('app.Page1', () => Page1, store, Provider);
    Navigation.registerComponent('app.Page2', () => Page2, store, Provider);
    Navigation.registerComponent('app.Page3', () => Page3, store, Provider);
}
```

I hope this fix your problem. (I also recommend you to upgrade the react-native and react-native-navigation to the latest version)

**Comment by Amurmurmur** [comment]
@knot123 
Thank you very much for your reply.
So you dont wrap you main App.js with code-push? 
How does it update than ?
I beleive you have to replace your App.js with the one from code-push if the update is available

**Comment by knot123** [comment]
@Amurmurmur You are welcome. 
My solution work exactly as expected. It is updating the entire app based on the update mode you specified. Let me explain, when you are pushing a new update to codepush server, bundle.js file with all other assets will be uploaded to cloud server, it doesnt change anything in your app bundle. When you are calling the codepush.sync() method anywhere, codepush native module will start to work in background, first it will compare the current version with the latest version on the server, if it finds any new update it will download the update and replaces the bundle.js and other assets. So it is independent from the lifecycle of your app. So dont worry, try my solution and you won't see any issues. I have a movie streaming app on appstore with many native plugins and third party libraries, but without any ploblem i am calling codepush.sync with immediate mode and codepush works as expected, it downloads the update and refreshes the app immidiately.

**Comment by laobaigan** [comment]
your code is generate a wrapper class, so you can resolve it by my code:

<pre><code>CodePushDemoApp = CodePush({ checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME, installMode: CodePush.InstallMode.ON_NEXT_RESUME })(CodePushDemoApp)
CodePushDemoApp.navigationOptions = 
    ({ navigation }) => ({
      title: 'Home',
      headerVisiable: Platform.OS === 'ios',
      tabBarKey: navigation.state,
      tabBarlabel: 'Dashboard',
      tabBarIcon: ({ tintColor, focused }) => (
         <Image
          // source={require('./welcome/welcome-icon.png')}
          style={[styles.icon, {tintColor: tintColor}]} />
      ),
      visible: !navigation.state.params ? true : navigation.state.params.visible,
   });
export default CodePushDemoApp;
</code></pre>

**Comment by knot123** [comment]
@laobaigan Hi, I think you are talking about react-nativation not react-native-navigation!! Am I right?

**Comment by laobaigan** [comment]
@knot123 Yes, I made a mistake, I'm sorry

**Comment by mhdnp** [comment]
@knot123  Thank you. you made my evening 👍
