### ISSUE TITLE
iOS13 pageSheet modal: no cleanup after dismissing by gesture

### ISSUE THREAD

**Issue by jfrolich** [wix/react-native-navigation#5370]
In iOS13 pageSheet modals can be dismissed using a swipe. When this is happening currently there is no cleanup (`componentWillUnmount` is not called), causing several edge cases.

**Comment by exentrich** [comment]
Screen with `pageSheet` never call `componentWillUnmount` including `dismissModal` and swipe down. This happen on iOS 13 and build with Xcode 11 beta 3.
I'm sure that this bug happen in release versions.
This is critical issue i think? @guyca

**Comment by Dexwell** [comment]
Pretty critical @yogevbd

**Comment by Dexwell** [comment]
Not stale...
