### ISSUE TITLE
Bottom bar is not hidden when Android keyboard is visible and adjustResize mode

### ISSUE THREAD

**Issue by peresbri** [wix/react-native-navigation#5371]
### Issue Description

Bottom bar is not hidden when Android keyboard is visible and adjustResize mode

### Steps to Reproduce / Code Snippets / Screenshots

`android:windowSoftInputMode="stateHidden|adjustResize"`

---
### Environment
* React Native Navigation version: 2.17.0
* React Native version: 0.58.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and any android device

**Comment by Agungkes** [comment]
Hey any update on this?

**Comment by DavitVosk** [comment]
We were having discussion for this on https://github.com/wix/react-native-navigation/issues/1299#issuecomment-525999477, but it is deleted now -_-

**Comment by DavitVosk** [comment]
We were discussing that the navBar can be hidden manually with the help of mergeOptions, like this: 

`Navigation.mergeOptions(this.props.componentId, {
      bottomTabs: {
        visible: true
      }
    });`.

I tried this solution listening to Keyboard appearing with `Keyboard.addListener("keyboardDidShow", this.keyboardDidShow)` and `Keyboard.addListener("keyboardDidHide", this.keyboardDidHide)`.

Yes, that solution works. But it works for all screens (even for the screens where the tab bars are hidden). And that way for the screen without tab bar, then when the keyboard is closed bottomTab (tab bar) becomes visible, which is not a feature which I want.

**Comment by DavitVosk** [comment]
Anybody did find a global solution to not move bottom tabs up when a keyboard is opened?

**Comment by guyca** [comment]
@DavitVosk This issue is resolved in v3. Prior to v3, hiding the keyboard with mergeOptions is the only solution.

**Comment by DavitVosk** [comment]
@guyca thanks for answer. But it seems that `drawBehind` can't be changed in `mergeOptions`? I need it to change from false to true and vice versa when hiding my bottom tabs

**Comment by oferRounds** [comment]
hey @guyca, is there a way to solve it in v1?
(i.e., not showing the bottom navigation bar above keyboard)

**Comment by guyca** [comment]
@oferRounds https://github.com/wix/react-native-navigation/issues/5371#issuecomment-528866411

**Comment by oferRounds** [comment]
Toda Guy – yes, saw it, but was not sure what are is the "mergeOptions" and if it’s available on V1

**Comment by guyca** [comment]
It's the equivalent of `setStyle()` of v1

**Comment by oferRounds** [comment]
Got you. But with param? Can’t find anything which looks like this

**Comment by oferRounds** [comment]
I’m looking [here](https://x-guard.github.io/react-native-navigation/#/styling-the-tab-bar)

**Comment by guyca** [comment]
Sorry @oferRounds , It's been so long I really don't remember. Why don't do you migrate to v6 already? 🙈

**Comment by oferRounds** [comment]
Ok, it’s on the plans :\ Next time I’ll write here it will be related to v6 :)

**Comment by guyca** [comment]
בעזרת השם
