### ISSUE TITLE
Passing a prop when we pop a screen

### ISSUE THREAD

**Issue by Jatapiaro** [wix/react-native-navigation#5373]
### Issue Description

Hi, I have an update view. When that update view pops I need to pass to the previous screen a prop with the new value of the item.
Is there a way to pass props when we pop a screen?

### Environment
* React Native Navigation version: ^2.18.4
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by jinshin1013** [comment]
I don't think you can add `passProps` to `pop` method but you can use state management library or React Context API.

**Comment by ItsNoHax** [comment]
You could use state + componentDidAppear.

```js
  constructor(props) {
    super(props);
    this.state = { hasPushed: false };
    Navigation.events().bindComponent(this);
  }

   navigateToOtherScreen() {
    const { componentId } = this.props;
    await Navigation.push(componentId, {
      component: {
        name: 'imago.SingleImageViewScreen',
        passProps: {
          item,
        },
      },
    });
    this.setState({ hasPushed: true });
   }

   componentDidAppear() {
    const { hasPushed } = this.state;
    if (hasPushed) {
      alert('We have popped');
      this.setState({ hasPushed: false });
    }
  }
```

Which achieves the following:
![Peek 2019-08-14 00-28](https://user-images.githubusercontent.com/4223434/62981834-9f2de600-be2a-11e9-83c0-d6cdf397bb06.gif)

**Comment by switch13** [comment]
Is there a way to remove props that were passed to a screen after it's popped?
