### ISSUE TITLE
Will RNN suport Android Fragment?

### ISSUE THREAD

**Issue by dreamhb** [wix/react-native-navigation#5378]
### Issue Description

Hi,

My app has four bottom tabs, and there is only one  using react-native, the other three are all native android fragments.

With react navigation it works fine, but how can I use RNN with that fragment?
Thanks!

### Steps to Reproduce / Code Snippets / Screenshots

none

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): android phone or emulator

**Comment by wfs3006** [comment]
I have the same problem. How can I solve it?

**Comment by guyca** [comment]
@wfs3006 The playground app includes an example of how to use a [fragment as an external screen](https://github.com/wix/react-native-navigation/blob/master/playground/android/app/src/main/java/com/reactnativenavigation/playground/FragmentScreen.java) in RNN
