### ISSUE TITLE
[v3] error: resource style/Widget.AppCompat.TextView (aka com.myapp:style/Widget.AppCompat.TextView) not found

### ISSUE THREAD

**Issue by solonifer** [wix/react-native-navigation#5379]
### Issue Description

After updating to rnn 3.0.0

```
What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  error: resource style/Widget.AppCompat.TextView (aka com.myapp:style/Widget.AppCompat.TextView) not found.
  error: resource style/Widget.AppCompat.TextView (aka com.myapp:style/Widget.AppCompat.TextView) not found.
  error: resource style/Widget.AppCompat.TextView (aka com.myapp:style/Widget.AppCompat.TextView) not found.
  error: resource style/Widget.AppCompat.TextView (aka com.myapp:style/Widget.AppCompat.TextView) not found.
  error: failed linking references.
```

---
### Environment
* React Native Navigation version: 3.0.0
* React Native version: 0.59.10 and 0.60.5
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): issue while building application

**Comment by keremcubuk** [comment]
I have same problem while trying upgrade v3. Did you find the solution? @solonifer

**Comment by nikolas7892** [comment]
Also experiencing the same issue during assembleRelease

**Comment by LA** [comment]
@solonifer Any way you could make a demo project, so that we can try to re-open the issue and get them to work on it? This is basically stopping adoption for RNN 3.x 😿

**Comment by Khuongnb** [comment]
v3.2.1 released yesterday and still got the same error on RN0.60.5. 
Please re-open and look into this.

**Comment by nikolas7892** [comment]
If it helps, it has to do with ```implementation 'androidx.appcompat:appcompat:1.0.2``` in app/build.gradle of the react native project. It seemed to transition from ```implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"```

**Comment by LA** [comment]
I'm sure it has to do with this. https://stackoverflow.com/questions/57478346/is-appcompat-possible-to-ignore-on-api-23/57480872#57480872. 

The new android X version should contain androidx.appcompat.widget.AppCompatTextView and not android.widget.TextView.

**Comment by nikolas7892** [comment]
TEMPORARY FIX: 

Add 
```    
<style name="Widget.AppCompat.TextView" parent="android:Widget">
        @null
</style>
```

to node_modules/react-native-navigation/lib/android/app/src/main/res/values/styles.xml

I know it's just a null value, but i saw this on production
```
    <style name="Widget.Support.CoordinatorLayout" parent="android:Widget">
        @null
    </style>
```
so maybe my fix is good?  🤔

**Comment by LA** [comment]
Wow @nikolas7892 that fixes everything. Thank you.

@guyca can we make a PR for this?

**Comment by nikolas7892** [comment]
Yes I can make a pr

**Comment by DerrickC** [comment]
v3.4.0 has this error still.
