### ISSUE TITLE
[V3 alpha.11] - React native navigation - HOC problem with Remx

### ISSUE THREAD

**Issue by isaacp0310** [wix/react-native-navigation#5383]
### Issue Description

I'm trying remx in one of my projects and have a problem with it. Whenever I wrap my component with connect() function, remx is works fine but react native navigation spesific events or functions like onNavigationButtonPressed(), componentDidAppear(), static get options() stops triggering. 

I really like remx a thousand times better than redux because it is so easy to implement, but i think that is a problem between the connection of rnn and remx.

### Steps to Reproduce / Code Snippets / Screenshots

- Implement react native navigation v3 aplha 11 to your project
-Implement REMX ^2.0.58
-Wrap your screen component with connect() function AND pass mapStateToProps as an argument 
-When connected to remx the static options() just stops working when navigating and getting back to the same screen
---
### Environment
* React Native Navigation version: 3.0.0-alpha.11
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android simulator api 27

**Comment by guyca** [comment]
Hey @isaacp0310 
Any chance you're not hoisting non react static to your concrete component? https://github.com/mridgway/hoist-non-react-statics

**Comment by isaacp0310** [comment]
Well i think that i am not using it  **look at my code** this is how i connect remx with my class

```
import React, {PureComponent, Fragment} from 'react';
import {View, Text, SafeAreaView, ScrollView, TouchableOpacity, StyleSheet, Dimensions, Linking} from 'react-native
import {connect} from 'remx';
import {userStore} from 'store.js';
import * as userAction from 'account.action.js';';
```
``

```
class User extends PureComponent{

}

```
```
function mapStateToProps() {
  return {
    account: userStore.getUser()
  };
}
```

`export default connect(mapStateToProps)(User);`

**Comment by guyca** [comment]
Well, to my understanding you'll need to hoist from the HOC to receive callbacks in the actual component.

**Comment by isaacp0310** [comment]
Wow thanks!, but with that code how can i accomplish it?
because i have not much experience with hoisting from the HOC.

> Well, to my understanding you'll need to hoist from the HOC to receive callbacks in the actual component.
