### ISSUE TITLE
V3 Documentation

### ISSUE THREAD

**Issue by fjmorant** [wix/react-native-navigation#5384]
### Issue Description

It would be better for the users of this library to know what has changed in V3, release notes or migration documents will be appreciated, if exists can you redirect me to the right location?

Thanks

**Comment by guyca** [comment]
Sorry about that - v3 changelog can be found [here](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#300).

**Comment by fjmorant** [comment]
Thank you very much @guyca
