### ISSUE TITLE
[V3] Topbar: Custom title component will not show if background style not set

### ISSUE THREAD

**Issue by xxRockOnxx** [wix/react-native-navigation#5385]
### Issue Description

I would like to have a TopBar with avatar so I created my own custom component.

```jsx
  <View
    style={{
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "transparent"
    }}
  >
    <Avatar source={image} rounded={true} />
    <Text style={{ marginLeft: 12, color: "#fff" }}>
      {name}
    </Text>
  </View>
```

if `backgroundColor` is removed from the `View` only the `Avatar` shows.

Tried checking with `Show Layout Boundaries` on Android to confirm. Only the size of `Avatar` is shown. Tried `flex: 1, width: "100%"` but it wouldn't expand so it's not a `width` issue and why would `backgroundColor` affect `width`?

### Steps to Reproduce / Code Snippets / Screenshots

- Create a screen with the following `static options()`:
```js
static options(props) {
  return {
    topBar: {
      visible: true,
      animate: false,
      title: {
        component: {
          name: "custom.ComponentName",
          passProps: props
        }
      }
    }
  }
}
```

- Use the custom component described on **Issue Description**

---
### Environment
* React Native Navigation version: `3.0.0`
* React Native version: 0.60.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): S7 Edge/8.0.0/Debug

Related: #4875

**Comment by xxRockOnxx** [comment]
Tried simplifying the component even more by removing `View` wrapper and `Avatar` and just left `Text`.

![demo](https://user-images.githubusercontent.com/11251134/63259933-4b038580-c2b2-11e9-806f-31853a0a388f.gif)

The `width` updates infinitely!

**Comment by guyca** [comment]
@xxRockOnxx Can you please try adding [collapsible: true](https://facebook.github.io/react-native/docs/view#collapsable) to the root layout and check if it helps?

**Comment by xxRockOnxx** [comment]
@guyca that fixes the problem! Both the text only and text with avatar.

Is this meant to happen? Or a bug? Probably on RN?

**Comment by guyca** [comment]
Well, I think it's safe to say this is an RN bug. The root view should probably kept as is, and not collapsed.
