### ISSUE TITLE
[Android] Passing a testID to a TopBar Button or a BottomTab has no effect

### ISSUE THREAD

**Issue by Jazqa** [wix/react-native-navigation#5386]
### Issue Description

Giving a testID to a TopBar Button or a BottomTab has no effect on Android. BottomTabs and TopBar Buttons without text are inaccessible (e.g. Appium).

### Steps to Reproduce / Code Snippets / Screenshots

1. Open a UI inspector (e.g. Appium)
2. Inspect a TopBar Button or a BottomTab with `options.testID`
3. `options.testID` is not present

---
### Environment
* React Native Navigation version: 2.X.X and 3.X.X
* React Native version: Any
* Platform(s) (iOS, Android, or both?): Android

**Comment by guyca** [comment]
Hey @Jazqa 
Are you sure it doesn't work? We use `testID` property with topbar buttons and tabs for our Detox e2e tests and it works.
