### ISSUE TITLE
How can I show other pages before enter into tabs?

### ISSUE THREAD

**Issue by jaggerwang** [wix/react-native-navigation#539]
### Issue Description

The pages in  tabs require login first, so I can't startTabBasedApp at first. I must make sure user already logined, then show tabs. How can I achieve this?

### Environment
* React Native Navigation version: 2.0 newest
* React Native version: 0.38.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug

**Comment by Crash--** [comment]
Simply do that in your app.js : 
```jsx

export default (async () => {
  const user = await getCurrentUser();
  if (user) {
    iconsLoaded.then(() => {
      startTabApp(iconsMap)
    });
  } else {
    startSingleApp()
  }
})()
```

Where startAppTab is somethign like: 
```jsx
export const startTabApp = (icons) => {
  return (
    Navigation.startTabBasedApp({
...
```

And startSingleApp is: 
```jsx
export const startSingleApp = () => {
  initialScreen = {
    screen: {
      screen: 'InTeach.HomeSliderScreen',
      navigatorStyle: {
        statusBarTextColorScheme: 'light'
      }
    }
  }
  return Navigation.startSingleScreenApp(initialScreen)
}
```

**Comment by PoloGarcia** [comment]
Hi @Crash--  any idea of how I could manage the change of state? 
I mean to send the user from the singleScreenApp to my tabbed app once login (via API) is done. 

I'm using redux. Any help will be appreciated :)

**Comment by guyca** [comment]
@PoloGarcia Dispatch an action
```js
const store = createStore(reducer);
...
store.dispatch({
  type: 'loginSuccess',
  user: {...}
});
```
