### ISSUE TITLE
React native navigation - HOC problem with Remx  ¡Making static options() work!

### ISSUE THREAD

**Issue by isaacp0310** [wix/react-native-navigation#5391]
### Issue Description
hi i uploaded a issue before related to this:
https://github.com/wix/react-native-navigation/issues/5383

 but @guyca  told me a solution which is:

>Well, to my understanding  you'll need to hoist from the HOC to receive callbacks in the actual component.

well the thing that is happening is that how can i accomplish that, because i have searched so many ways to learn how to hoist from the HOC **while also using remx with rnn** but it seems pretty dificult to find documents related to that,.

i am going to show my code to see who can help me with that.

**If you did not read the issue before.**

The problem is that when i am currently on a screen, everything works fine but after i push a new screen and then get back to the screen i was before. 
the following function:

static options(){
    return{
      topBar:{
        visible:false,
        drawBehind:true
      }
    };
  }
stops working!

### Steps to Reproduce / Code Snippets / Screenshots

```
import React, {PureComponent, Fragment} from 'react';
import {View, Text, SafeAreaView, ScrollView, TouchableOpacity, StyleSheet, Dimensions, Linking} from 'react-native
import {connect} from 'remx';
import {Navigation} from 'react-native-navigation';
import {userStore} from './store.js';
import * as userAction from './account.action.js';';

class User extends PureComponent{

  static options(){
    return{
      topBar:{
        visible:false,
        drawBehind:true
      }
    };
  }

render(){
  return(
//My code 
);
}

}

function mapStateToProps() {
  return {
    account: userStore.getUser()
  };
}
export default connect(mapStateToProps)(User);
```

As you can see in the following picture the static options(){} do his job.

![working](https://user-images.githubusercontent.com/35440957/63317275-30480580-c2e0-11e9-9140-f533d9e58a2c.png)

But after the actions that i have said before **It only happens when pushing a new screen**
the static options(){} is buggy.

![not working](https://user-images.githubusercontent.com/35440957/63317334-6c7b6600-c2e0-11e9-99c4-faca232783f6.png)

---
### Environment
* React Native Navigation version: 3.0.0-alpha.11
* React Native version:0.60.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): ANDROID API 27

**Comment by geroale** [comment]
Same issue here
