### ISSUE TITLE
android.support.v7.widget.AppCompatTextView not found

### ISSUE THREAD

**Issue by Lakeyour** [wix/react-native-navigation#5392]
### Description

Hello, I could not find anything related to this issue except some chinese forum so I will try my luck here.

I have done a bit of troubleshooting and it is likely related to the AndroidX merge or a missing import somewhere.

I realise it this not alot to go on, however I feel this has a very simple solution.

### Code Snippets / Screenshots

![rnn1](https://user-images.githubusercontent.com/25793711/63327395-6613db00-c32e-11e9-9433-6a5dedc19014.PNG)

>The top error is rather strange, when I looked at it, it didn't really show me any obvious errors, so that makes it likely related to the bottom ones

>Just for references the top error looks like this
![rnn3](https://user-images.githubusercontent.com/25793711/63327756-1eda1a00-c32f-11e9-8f64-a6b06e05c7b7.PNG)

>Here is an example of the three bottom errors

```
package com.reactnativenavigation.views.element.animators;

import android.animation.Animator;
import android.graphics.Point;
import android.widget.TextView;

import com.facebook.react.views.text.ReactTextView;
import com.reactnativenavigation.utils.ViewUtils;
import com.reactnativenavigation.views.element.Element;
import com.shazam.android.widget.text.reflow.ReflowTextAnimatorHelper;

import static com.reactnativenavigation.utils.TextViewUtils.getTextSize;

public class TextChangeAnimator extends PropertyAnimatorCreator<ReactTextView> {

    public TextChangeAnimator(Element from, Element to) {
        super(from, to);
    }

    @Override
    protected boolean shouldAnimateProperty(ReactTextView fromChild, ReactTextView toChild) {
        Point fromXy = ViewUtils.getLocationOnScreen(from.getChild());
        Point toXy = ViewUtils.getLocationOnScreen(to.getChild());
        return getTextSize(fromChild) != getTextSize(toChild) ||
               !fromXy.equals(toXy.x, toXy.y);
    }

    @Override
    public Animator create() {
        return new ReflowTextAnimatorHelper
                .Builder((TextView) from.getChild(), (TextView) to.getChild())
                .calculateDuration(false)
                .buildAnimator();
    }
}
```

>This specific line of code occurs on all of the bottom three

```
return getTextSize(fromChild) != getTextSize(toChild)
```

>Also it shows this, which I assume means that it uses the wrong import, I suppose it should be using the AndroidX version if it supports it

![rnn2](https://user-images.githubusercontent.com/25793711/63326730-239dce80-c32d-11e9-977d-cf2ee38cd481.PNG)

---
### Environment
* React Native Navigation version: ^3.0.0
* React Native version: 0.59.4
* Platform(s): Android
* Device info: Android Studio Emulator / Nexus 6P API 28 - Android 9.0

**Comment by Lakeyour** [comment]
Potentially found the problem.

>It seems like getChildCount has been removed, could be wrong, but it does not seem to work in this case
```
@Override
    public boolean shouldAnimateProperty(TextView fromChild, TextView toChild) {
        return fromChild.getChildCount() == 0 && toChild.getChildCount() == 0;
    }
```

>I thought I would try something like this
It removes the error, but does not solve the issue
```
@Override
    public boolean shouldAnimateProperty(TextView fromChild, TextView toChild) {
        return fromChild.getLineCount() == 0 && toChild.getLineCount() == 0;
    }
```

**Comment by Lakeyour** [comment]
Temporary fix: **Revert to RNN 2.2.65**

**Comment by guyca** [comment]
v3 only supports RN 0.60 and AndroidX - Use v2 if you're on RN < 0.60 👍

**Comment by Lakeyour** [comment]
Hey again, I found some more trouble!

>I am now running **RN 0.59.4** along with **RNN 2.26.5** otherwise the environment info remains the same, very strange.

![rnn5](https://user-images.githubusercontent.com/25793711/63511209-dc583f00-c4e0-11e9-8436-e5278b7110b6.PNG)

>Very similar to the previous errors.

>I believe the problem is related to AndroidX, find the depends below, that'd be the only thing I could imagine is incorrect in this scenario.

```
dependencies {
    implementation project(':react-native-nested-scroll-view')
    //implementation project(':react-native-sweet-alert')
    //implementation project(':react-native-reanimated')
    implementation project(':react-native-svg')
    implementation project(':@react-native-community_async-storage')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    //implementation 'com.google.android.material:material:1.0.0'
    implementation "com.facebook.react:react-native:+"
    implementation 'com.facebook.fresco:fresco:1.10.0'
    implementation 'com.facebook.fresco:animated-gif:1.10.0'
    implementation project(':react-native-navigation')

    implementation (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
    }

    implementation ("com.google.android.gms:play-services-vision:10.2.0") {
        force = true;
    }
}
```

>I am currently poking around to isolate the problem, would very much appreciate some help

**Comment by guyca** [comment]
Have you tried invalidating cache and restarting?

**Comment by Lakeyour** [comment]
> 
> 
> Have you tried invalidating cache and restarting?

Yes, unfortunately same problem still.
