### ISSUE TITLE
Android X support

### ISSUE THREAD

**Issue by marudy** [wix/react-native-navigation#5394]
### Issue Description

Android X support is needed to upgrade properly to v0.60

### Steps to Reproduce / Code Snippets / Screenshots

Not Applicable
---
### Environment
* React Native Navigation version: 0.60.5
* React Native version: 2.13.x
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): any, any

**Comment by EJohnF** [comment]
1) you mixed RNN and RNN versions
2) pls check RNN version 3.1.0

**Comment by guyca** [comment]
https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#300
