### ISSUE TITLE
Is it compatible with RN 0.27-rc?

### ISSUE THREAD

**Issue by MichaelSavin** [wix/react-native-navigation#54]
Some breaking changes are coming: https://github.com/facebook/react-native/releases/tag/v0.27.0-rc

**Comment by MattDavies** [comment]
Hey @MichaelSavin,

I'm running against the 0.27-rc without any obvious issues. The breaking changes there are around `NavigationExperimental` which this library completely replaces anyway.

**Comment by guyca** [comment]
Internally at Wix, We're working with RN 0.25.1 - so we haven't tested the library with RN 0.27 yet.
