### ISSUE TITLE
Is it possible to have API for setting disableOpenGesture for each view

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#540]
### Issue Description

Is it possible to have API for setting disableOpenGesture for each view
for example, for one view I want to set the value is false since I have many Gesture events, for the others I would like to keep it true

---
### Environment
* React Native Navigation version: 2.exp.151
* React Native version: 0.38.1
* Platform(s) (iOS, Android, or both?): Both, iOS at least
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by guyca** [comment]
Hey @Jaafar-abusair 
What do you mean by "many gesture events"? If, for instance, you have a feed screen with cards that you can swipe to delete, swiping the card will delete the card. But if you start the swipe gesture from the edge of the screen the drawer is opened. Is this not the behavior you're getting?

**Comment by annelorraineuy** [comment]
@guyca I have a screen wherein I need to disable the gesture to open the drawer. It's a game screen that has its own game menu when swiped from the left. This is a use case wherein it would be useful to be able to disable drawer gesture on specific screen.

**Comment by Jaafar-abusair** [comment]
Hi @annelorraineuy ,

For the last version ^1.1.63, side menu is set on each screen by the following code
`static navigatorButtons = {
    leftButtons: [
      {
        id: 'sideMenu'
      }
    ]
  };`

So just don't insert it on the disabled screen

**Comment by annelorraineuy** [comment]
Hi @Jaafar-abusair I did not set any buttons on the disabled screen. I set the drawer left button on the home screen. Also, I totally hid the navbar on the disabled screen.

**Comment by Jaafar-abusair** [comment]
Which version do you use?

**Comment by annelorraineuy** [comment]
@Jaafar-abusair I am using version 1.1.79.

On the disabled screen, I only put this:
```
static navigatorStyle = {
        navBarHidden: true
    };
```

My side menu button is declared in home screen (disabled screen is a child of home):
```
RooIcon.getImageSource('hamburger', 24, Colors.orange).then(drawerIcon => {
            props.navigator.setButtons({
                leftButtons: [{
                    icon: drawerIcon,
                    id: 'sideMenu'
                }]
            })
        })
```

Is there anything else I should do?

**Comment by Jaafar-abusair** [comment]
what you mean disabled screen is a child of home? do you mean they are components? how do you display them? are you use posh/showModal?

**Comment by annelorraineuy** [comment]
@Jaafar-abusair ah, sorry. i mean my disabled screen is in the stack where home should be the first screen (after root navigator). 

So Root -> (if authorized) -> Home w/ drawer -> disabled screen.

I push the disabled screen. For the drawer, declared this in App.js:
```
Navigation.startSingleScreenApp({
    screen: {
        screen: 'Root'
    },
    drawer: {
        left: {
            screen: 'DrawerMenu'
        }
    },
    animationType: 'fade'
})
```

**Comment by Jaafar-abusair** [comment]
So if you use push and there is no sidemenu button added in the disabled screen so you shouldn't get the drawer at that screen

**Comment by annelorraineuy** [comment]
@Jaafar-abusair I am able to swipe it open though.. I'll try to make a fresh project example of what I mean when I have time. For now I have disabled gestures for the entire app.

**Comment by yaswanthsvist** [comment]
It would be nice to have a disableDrawer passing true or false for a particular screen. I had to compromise on gestures for drawer for all the screens because I had to disable it in my login screen.

**Comment by yaswanthsvist** [comment]
I found some work arounds here for avoiding drawer in my login screen case.
#922

**Comment by guyca** [comment]
[setDrawerEnabled](https://wix.github.io/react-native-navigation/#/screen-api?id=setdrawerenabledparams-)
