### ISSUE TITLE
The latest version on npm is 2.x.x

### ISSUE THREAD

**Issue by retyui** [wix/react-native-navigation#5405]
When I run next command
```sh
yarn add react-native-navigation
```

As a result a get `2.x.x` version 
```
 info All dependencies
└─ react-native-navigation@2.27.1
```

I spend a lot of time to understand what wrong because all my project configurated for 3.x.x

![image](https://user-images.githubusercontent.com/4661784/63510978-a8811780-c4e8-11e9-9b1a-09661c3b156c.png)

https://github.com/wix/react-native-navigation/issues/5374

**Comment by guyca** [comment]
Hey @retyui 
npm's `latest` tag points to the last version published - you can't count on it to be incremental.

**Comment by guyca** [comment]
From now on I'll publish v2 under `prev` tag to avoid confusion 👍
