### ISSUE TITLE
pod install not working

### ISSUE THREAD

**Issue by vinjegaard** [wix/react-native-navigation#5406]
### Issue Description

pod install fails:
```
[!] Error installing ReactNativeNavigation
[!] /usr/bin/git clone https://github.com/wix/react-native-navigation.git /var/folders/kc/9t_973s96cs9z_nrny2124h00000gn/T/d20190822-5379-1uwkij --template= --single-branch --depth 1 --branch 2.27.1

Cloning into '/var/folders/kc/9t_973s96cs9z_nrny2124h00000gn/T/d20190822-5379-1uwkij'...
warning: Could not find remote branch 2.27.1 to clone.
fatal: Remote branch 2.27.1 not found in upstream origin
```

### Steps to Reproduce / Code Snippets / Screenshots

Just fresh installation of react native with expo init bare installation and `npm install react-native-navigation --save`

---
### Environment
* React Native Navigation version: ^2.27.1
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): N/A

**Comment by amehrdad88** [comment]
Same issue for me, just upgraded to RN 0.6.x

**Comment by holdenchristiansen** [comment]
Same issue here as well, RN 0.60.4

**Comment by amehrdad88** [comment]
Quick and dirty fix but not sure it's the official one: 
- locate the podspec fils (in node_modules > react-native-navigation
find the line with s.source : 

`  s.source       = { :git => "https://github.com/wix/react-native-navigation.git", :tag => "#{s.version}" }`

replace with 

`  s.source       = { :git => "https://github.com/wix/react-native-navigation.git" }`

if you npm install or yarn install again, then this will revert to original with a version number and not work again

**Comment by dobrynia** [comment]
I think there is an mistake in the project config, because v3 is already in the master branch. In this case you can specify RNN version to install via npm. 
`npm i react-native-navigation@3.1.1`
That should work.

**Comment by imamabdulazis** [comment]
> s.source = { :git => "https://github.com/wix/react-native-navigation.git" }

any solution here?
