### ISSUE TITLE
Merging Title, TopBar buttons and status bar options is broken on 3.1.1

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#5411]
Merging TopBar title, buttons and status bar options is broken on iOS with 3.1.x.
Parent options aren't resolved properly and default options aren't regarded when they should be.

---
### Environment
* React Native Navigation version: 3.1.0, 3.1.1
* React Native version: 0.60
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): any

**Comment by Andarius** [comment]
Also got a problem on Android, while trying to merge `leftButtons`. The buttons does not appear but the back button becomes visible event if set not to. However `rightButtons` works just fine.

**Comment by guyca** [comment]
Should have a fix for this later today.
@Andarius Could you please open a new issue for what you're observing? Thanks! 👍

**Comment by guyca** [comment]
This should be fixed in 3.1.2.
Sorry for the inconvenience 🙇
