### ISSUE TITLE
[V3] Merging leftbuttons does not work on Android

### ISSUE THREAD

**Issue by Andarius** [wix/react-native-navigation#5414]
### Issue Description

Merging `leftButtons` does not work. Right buttons are displayed but the left one are not. However the title moves to the right like if the button was visible.

### Steps to Reproduce / Code Snippets / Screenshots

```js
  const config = {
	topBar: {
	    leftButtons: [
	        {
	            id: 'close',
	            component: {
	                name: 'btn.Close',
	                passProps: {
	                    onPress: onPress
	                }
	            }
	        }
	 	],
	 	rightButtons: [
	        {
	            id: 'close2',
	            component: {
	                name: 'btn.Close',
	                passProps: {
	                    onPress: onPress
	                }
	            }
	        }

	 	]
    }
}
  Navigation.mergeOptions(componentId, config)
```

### Environment
* React Native Navigation version: 3.1.1
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by guyca** [comment]
Hey @Andarius 
Android doesn't support react component in left buttons at the moment

**Comment by AugustoAleGon** [comment]
@guyca so what is the current implementation in Android for the buttons? 😢

**Comment by AugustoAleGon** [comment]
Problem Solved. I just used the deprecated method `componentWillMount` in order to have the right icons ready!

**Comment by elifaahmet** [comment]
@AugustoAleGon can you share, please?

**Comment by AugustoAleGon** [comment]
@elifaahmet Sure.
`componentWillMount () {
  Navigation.mergeOptions(
    'MyView', {
      topBar: {
        rightButtons: [...]
      }
    }
  )
}`
