### ISSUE TITLE
[v3] mergeOptions with sideMenu only takes effect after side menu is opened

### ISSUE THREAD

**Issue by samiede** [wix/react-native-navigation#5415]
### Issue Description

I have a screen where I have a sideMenu, which is used to show details of what's on the screen.
I load some data and then have to set the title of the topBar, but using mergeOptions with the current component id only takes effect when I open the sideDrawer for the first time.

Additionally, the sideDrawer seems to trigger some topBar flickering, as if a new topBar is pushed on the screen

### Steps to Reproduce / Code Snippets / Screenshots

![TopBar](https://user-images.githubusercontent.com/6050746/63760845-611bd200-c8c0-11e9-9e43-3b9c2102e8ed.gif)

---
### Environment
* React Native Navigation version: 3.1.1
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel 3, OnePlus 5, Emulator, Android 9

**Comment by terreb** [comment]
Same on iOS
React Native Navigation version: 3.1.0
React Native version: 0.60.4
