### ISSUE TITLE
White Screen while using setRoot and push methods

### ISSUE THREAD

**Issue by saisaran96** [wix/react-native-navigation#5419]
### Issue Description

I get a white rendering screen while using setRoot and push method in android . I tried setting waitForRender  to true but it didn't help .
help me solve this issue
### Steps to Reproduce / Code Snippets / Screenshots

I tried this but it didn't work
 Navigation.setDefaultOptions({
    animations: {
      setRoot: {
        waitForRender: true
      },
      push: {
        waitForRender: true
      }
    }
  });

---
### Environment
* React Native Navigation version: 0.24.1
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by arahmanali** [comment]
Hey @saisaran96 you found a solution yet?

**Comment by saisaran96** [comment]
> Hey @saisaran96 you found a solution yet?

no not yet

**Comment by chrise86** [comment]
@saisaran96 did you resolve this? Just ran into this issue when run in release mode.

**Comment by Rotemy** [comment]
I also experiencing this, very annoying. Any solution?
