### ISSUE TITLE
Tab style tabBarSelectedButtonColor is not working on icon image from react-native-vector-icons?

### ISSUE THREAD

**Issue by jaggerwang** [wix/react-native-navigation#542]
### Issue Description

![image](https://cloud.githubusercontent.com/assets/1255011/20957222/6793f932-bc89-11e6-84d2-bbf08d022552.png)
The tabBarSelectedButtonColor only valid for tab label. As you can see, the label color of current tab is changed, but not the icon. The tab icon image is generated by FontAwesome.getImageSource, and it must supply to color param to this function.

### Code

**generate icon images**
```javascript
/**
 * 在球场
 * zaiqiuchang.com
 */

import FontAwesome from 'react-native-vector-icons/FontAwesome';

import {COLOR} from './config';

const icons = {
  'tabbar-nearby': ['map-marker', 24, COLOR.textEmpha, FontAwesome],
  'tabbar-atcourt': ['plus-square', 24, COLOR.textEmpha, FontAwesome],
  'tabbar-me': ['user', 24, COLOR.textEmpha, FontAwesome],
}

let iconImages = {};

export function loadIconImages() {
  return new Promise((resolve, reject) => {
    const iconNames = Object.keys(icons);
    Promise.all(
      iconNames.map(iconName => {
        let [name, size, color, vendor] = icons[iconName];
        return vendor.getImageSource(name, size, color);
      })
    ).then(sources => {
      iconNames.forEach((iconName, index) => iconImages[iconName] = sources[index]);
      resolve(iconImages);
    });
  });
}

export default iconImages;
```

**define tabs**
```javascript
export function navToTab() {
  Navigation.startTabBasedApp({
    tabs: [
      {
        label: '附近',
        screen: 'zqc.Nearby',
        icon: iconImages['tabbar-nearby'],
        navigatorStyle: DEFAULT_NAV_BAR_STYLE,
        title: '附近',
      },
      {
        label: '在球场',
        screen: 'zqc.AtCourt',
        icon: iconImages['tabbar-atcourt'],
        navigatorStyle: DEFAULT_NAV_BAR_STYLE,
        title: '在球场',
      },
      {
        label: '我',
        screen: 'zqc.Me',
        icon: iconImages['tabbar-me'],
        navigatorStyle: DEFAULT_NAV_BAR_STYLE,
        title: '我',
      },
    ],
    tabsStyle: {
      tabBarButtonColor: COLOR.textEmpha,
      tabBarSelectedButtonColor: COLOR.theme,
      tabBarBackgroundColor: COLOR.backgroundDarker,
    },
    animationType: 'fade',
  });
}
```

### Environment
* React Native Navigation version: 2.0 newest
* React Native version: 0.38.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?):Simulator Debug

**Comment by guyca** [comment]
Hey @jaggerwang 
I don't think there's an issue with vector icons color in bottom tabs. A lot of users use that package and didn't report any issues. Unfortunately I have not experience with it so I'm don't think I can assist you.

**Comment by messense** [comment]
Ran into the same issue.

**Comment by guyca** [comment]
@messense IIRC you need to set BottomTabs icon color in `AppStyle`.
```js
Navigation.startTabBasedApp({
  tabs: createTabs(),
  appStyle: {
    tabBarBackgroundColor: '#0f2362',
    tabBarButtonColor: '#ffffff',
    tabBarSelectedButtonColor: '#63d7cc',
    screenBackgroundColor: '#42A5F5'
  },
...
}
```

**Comment by messense** [comment]
@guyca Thanks, it works.

Please update the documentation, it still tell us to use `tabsStyle`.

**Comment by guyca** [comment]
@messense Good suggestion 👍

**Comment by wqi** [comment]
I can confirm that I was able to reproduce @jaggerwang's issue with the exact same environment. 

When applying both a custom tabBarButtonColor along with a custom tabBarSelectedButtonColor, only the text and not the icon is applied with the selected button color. However, if each of those styles is applied individually, everything seems to be fully functional.

**Comment by dillonykyang** [comment]
I have the same issue with @jaggerwang and @wqi

**Comment by benkraus** [comment]
Same issue here. `tabBarButtonColor` always overwrites the `tabBarSelectedButtonColor`.

**Comment by benkraus** [comment]
Sifting through the code, I found the issue. I'll submit a PR with the fix. A workaround though for any interested is to set the `selectedIcon` attribute, in our case, the same as `icon`.
