### ISSUE TITLE
[Android] Absolute views in overlay don't block touches

### ISSUE THREAD

**Issue by fjmorant** [wix/react-native-navigation#5424]
### Issue Description

When showing an overlay with views with absolute positions and interceptTouch = false, touches pass-through without capturing the touch event, this works fine on iOS. Also this is reproducible in 3 and 2 versions of the library

### Steps to Reproduce / Code Snippets / Screenshots

iOS

![ios_overlay](https://user-images.githubusercontent.com/6560136/63942307-6e25f600-ca65-11e9-8cf3-e4237157301e.gif)

Android

![android_overlay](https://user-images.githubusercontent.com/6560136/63942319-73834080-ca65-11e9-8e66-ed80951af0a2.gif)

Github template project so that you can see the issue easier https://github.com/fjmorant/example_issue_rnn

---
### Environment
* React Native Navigation version: 3.1.0 ( and 3 and latest 2)
* React Native version: 0.60.5 (Also this happens on 0.59)
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator Android 9 Pixel 3 XL

**Comment by marf** [comment]
I have the exact same problem here!

**Comment by garrettm** [comment]
I also have this problem -- @marf / @fjmorant have either of you found a solution?

**Comment by cenaHara** [comment]
same issue @garrettm @marf , @fjmorant  have either of you found a solution?

**Comment by garrettm** [comment]
@cenaHara sorry I don't remember off the top of my head what I did to workaround this
