### ISSUE TITLE
Only 3 buttons in 'rightButtons' are clickable, 4th is not clickable  

### ISSUE THREAD

**Issue by DaveLomber** [wix/react-native-navigation#5426]
### Issue Description

I have one button defined in 'leftButtons' and 4 buttons  defined in 'rightButtons'.
From UI perspective, all looks good.
But the 4th button from 'rightButtons' is not clickable - there is no any feedback when click on it 

### Steps to Reproduce / Code Snippets / Screenshots

Just install the lib, put the above amount of buttons and test 

---
### Environment
* React Native Navigation version: 2.24.0
* React Native version: 0.59.5
* Platform(s) (iOS, Android, or both?): Android, not sure about iOS
* Device info (Simulator/Device? OS version? Debug/Release?): any

**Comment by Damar95** [comment]
Just tested it with RNN 3.1.0 and RN 60.5 and i get a Icon for the UIManager.showPopupMenu, which contains the not visable buttons.
![grafik](https://user-images.githubusercontent.com/24271650/64040857-3ea6e480-cb5e-11e9-879f-c1f9983fd3f8.png)
![grafik](https://user-images.githubusercontent.com/24271650/64040879-46ff1f80-cb5e-11e9-92b8-b70db6f0772b.png)

The first two buttons get placed inside the menu

**Comment by DaveLomber** [comment]
thanks, seems a mistake at our end
we re-tested it again and now it works 
thank you for your help 👍
