### ISSUE TITLE
[V3] Application has not registered.

### ISSUE THREAD

**Issue by AdamCyffka** [wix/react-native-navigation#5427]
### Issue Description

Can not run react-native-navigation on Android, even with manual installation it does not work.

### Steps to Reproduce / Code Snippets / Screenshots

[Pic](https://image.noelshack.com/fichiers/2019/35/5/1567158146-capture-d-ecran-2019-08-30-a-11-41-33.png)

---
### Environment
* React Native Navigation version: 3.1.2
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 6 API 28

**Comment by RadagastCH** [comment]
Have the same problem on iOS with RN 0.60.5

**Comment by RadagastCH** [comment]
Ok, now I fix that for my self, first obviously follow the installation [guide](https://wix.github.io/react-native-navigation/#/docs/Installing) make sure you did everything correct. Than change this `Navigation.registerComponent('navigation.playground.WelcomeScreen', () => App);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      component: {
        name: 'navigation.playground.WelcomeScreen',
      },
    },
  });
});` 
to this 
`Navigation.events().registerAppLaunchedListener(() => {
  Navigation.registerComponent(
    'navigation.playground.WelcomeScreen',
    () => App,
  );
  Navigation.setRoot({
    root: {
      component: {
        name: 'navigation.playground.WelcomeScreen',
      },
    },
  });
});
`
That's work for me, and might work for you.

**Comment by club9822** [comment]
just install and link proper version of this package
