### ISSUE TITLE
[V3] Top bar style and animation

### ISSUE THREAD

**Issue by blueberry6401** [wix/react-native-navigation#5431]
### Issue Description
These examples are taken in playground app.

**1. Topbar wrong animation**

| Native (what should be)  | RNN v3 |
| ------------- | ------------- |
| ![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/7337535/64061883-83885500-cc0a-11e9-974e-0c1e1887cb74.gif)  | ![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/7337535/64061884-85eaaf00-cc0a-11e9-8042-2a6c76d3e067.gif)|

**2. Back button and title are not aligned**
![Screen Shot 2019-08-31 at 16 02 00](https://user-images.githubusercontent.com/7337535/64061715-afa2d680-cc08-11e9-993d-c752e53193f0.png)

---
### Environment
* React Native Navigation version: 3.1.2
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device iPhone X, iOS 12.2

**Comment by hossamnasser938** [comment]
The issue is not documented well. Please, add more info: code snippet, etc

**Comment by blueberry6401** [comment]
> The issue is not documented well. Please, add more info: code snippet, etc

Sorry I forgot to say, the example I run is directly the playground app. 
I didn't face this issue in V2.

**Comment by blueberry6401** [comment]
Not stale.

**Comment by ivan3177** [comment]
+1

**Comment by blueberry6401** [comment]
Lol still waiting for the fix, actually it's months since I posted. And the issue is right in the eye though.

**Comment by blueberry6401** [comment]
@guyca should I expect this issue will be fixed? With reac-native-navigation, the whole application looks like it's native, but the top bar diminish the native feeling.

**Comment by stereodenis** [comment]
was it fixed?
