### ISSUE TITLE
[V3] White flash between iOS Launch Screen and RN screen

### ISSUE THREAD

**Issue by markhomoki** [wix/react-native-navigation#5432]
### Issue Description
There is a white flash between iOS Launch Screen and the first loaded javascript screen. Setting `waitForRender: true` in RNN 3.1.2 has no effect.

### Steps to Reproduce / Code Snippets
With version `3.0.0` and below the following code was working.
```
Navigation.setDefaultOptions({
  animations: {
    setRoot: {
      waitForRender: true,
    },
  },
});
```

Upgrading to version `3.1.2` this seems like being ignored by RNN.

### Video
_Ignore the gradient difference between iOS Launch Screen and JS screen._

| *3.0.0*  | *3.1.2*  |
|---|---|
| ![case02](https://user-images.githubusercontent.com/8550329/64062721-385a4c00-cbe2-11e9-826f-b87ff5b4ae8f.gif) | ![case01](https://user-images.githubusercontent.com/8550329/64062722-3a240f80-cbe2-11e9-8b47-3da23b28f2ec.gif) |

---
### Environment
* React Native Navigation version: 3.1.2
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): It affects all devices and simulators and all iOS versions in release env.

**Comment by ltoussaint** [comment]
The same on android, also with version 3.1.2

**Comment by markhomoki** [comment]
Anyone found a solution? I'm using 3.3.0 now, but the issue still exist.

**Comment by gusilveiramp** [comment]
Same here. How to solve this?

**Comment by vishgoel007** [comment]
Any clue about this issue yet ?
