### ISSUE TITLE
[v3]: app crashes when setting bottomTabs via setRoot

### ISSUE THREAD

**Issue by abdullah-sr** [wix/react-native-navigation#5435]
### Issue Description

```js             
registerScreens();
  Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setRoot({
      root: {
        bottomTabs: {
          children: [
            {
              component: {
                name: HomeScreen.navID,
              },
            },
          ],
        },
      },
    });
  });
```
when setting bottomTabs, app crashes on lanuch.
Tested on Android. version 3.1.2

---
### Environment
* React Native Navigation version: 3.1.2
* React Native version: RN60
* Platform(s) (iOS, Android, or both?) Android, not sure about iOS
* Device info (Simulator/Device? OS version? Debug/Release?): physical device

**Comment by abdullah-sr** [comment]
nvm. didn't set up the project properly because docs are out of date.

**Comment by Andarius** [comment]
@abdullah-sr where did you find the correct way ? Can you share a working example ?

**Comment by davidmarinangeli** [comment]
@abdullah-sr your solution could be useful to some other people!

**Comment by Andarius** [comment]
@davidmarinangeli  this worked for me:

`    Navigation.setRoot({
      root: {
        bottomTabs: {
          options: {
            bottomTabs: {
              titleDisplayMode: 'alwaysShow'
            },
          },
          id: 'RootTabs',
          children: [
            {
              stack: {
                id: 'Stack1',
                children: [
                  {
                    component: {
                      name: Screens.SCREEN_1,
                      options: SCREEN_OPTIONS[Screens.SCREEN_1]
                    }
                  }
                ],
                options: {
                  bottomTab: {
                    text: 'Screen 1',
                    icon: require("../icons/icon1.png")
                  }
                }
              }
            },
            {
              stack: {
                id: 'Stack2',
                children: [
                  {
                    component: {
                      name: Screens.SCREEN_2,
                      options: SCREEN_OPTIONS[Screens.SCREEN_2]
                    }
                  }
                ],
                options: {
                  bottomTab: {
                    text: 'Screen 2',  
                    icon: require("../icons/icon2.png"),
                  }
                }
              }
            }
          ]
        }
      }
    });
`
