### ISSUE TITLE
[V3] StatusBar text color is not inverted correctly with dark-mode active

### ISSUE THREAD

**Issue by Xetoxyc** [wix/react-native-navigation#5446]
### Issue Description

Style for StatusBar is not applied correctly in Dark-Mode as we want a black TextColor in both modes.
We got following behaviour.

Dark-Mode = OFF
light => TextColor = White
dark => TextColor = Dark

Dark-Mode = ON
light => TextColor = White
dark => TextColor = White

Expected behaviour with Dark-Mode = ON would be
light => TextColor = White
dark => TextColor = Black

or

light => TextColor = Black
dark => TextColor = White

### Steps to Reproduce / Code Snippets / Screenshots
```js
statusBar: {
    visible: true,
    style: "light",
},
```

---
### Environment
* React Native Navigation version: 3.1.2-snapshot.486
* React Native version: 0.60.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device / 13.0 Beta 7 / Debug

**Comment by piuholo** [comment]
Now that iOS 13 with Dark Mode is properly released, this issue is quite urgent as it can break the user experience, for example in search bars.
For those that want to force their app to always use light mode and disregard the iOS user setting, you can set key `UIUserInterfaceStyle` to `Light` in the Info.plist file.

**Comment by djschilling** [comment]
The issue is not resolved.

**Comment by tothvoj-gl** [comment]
Any update on this? I see it as a quite high priority and urgent issue.

**Comment by forkandfix** [comment]
another workaround is to disable dark mode completely by adding the following to Info.plist
```
<key>UIUserInterfaceStyle</key>
<string>Light</string>
```

**Comment by GioLogist** [comment]
Might be somewhat related:
https://github.com/wix/react-native-navigation/issues/5701

**Comment by vstukanov** [comment]
In my case I was also required to change `View controller-based status bar appearance` value to `YES` in `Info.plist` to make status bar text black.

**Comment by Xetoxyc** [comment]
Still not resolved and i think all people above wish to have a fix to use darkmode within their apps

**Comment by Hemistone** [comment]
Any Updates? 
I also changed `View controller-based status bar appearance` as `true`, but I think this setting can make react-native's `StatusBar` component not workable. 
I'm not using any `StatusBar` component for now so it does not make any issues, but I'm curious about does react-native's `StatusBar` Component still works with `View controller-based status bar appearance` as `true`.

**Comment by Saliheen** [comment]
Below code works for me
```
import {useEffect} from 'react';
import {StatusBar} from 'react-native';

const TranslucentStatusBar = ({isDarkSelected = false}) => {

  useEffect(() => {
    StatusBar.setBarStyle(isDarkSelected ? 'dark-content' : 'light-content');
  }, [isDarkSelected]);

  return (
    <>
      <StatusBar
        translucent={true}
        backgroundColor="transparent"
        animated={true}
      />
    </>
  );
};

export default TranslucentStatusBar;
```
