### ISSUE TITLE
Transparent topBar with drawBehind set to true shows anyway on iOS

### ISSUE THREAD

**Issue by samcampisi** [wix/react-native-navigation#5449]
### Issue Description

This might be related to #4221

I'm trying to render a transparent topBar with drawBehind true. On Android it works kind of fine (still see a little bit of white space on top of it) but on iOS it just ignores that the topBar is supposed to be transparent. However, when I scroll, it does show the content behind the topbar:

![ezgif-1-dfb25c45918b](https://user-images.githubusercontent.com/42766924/64231720-a9ef0e80-cef0-11e9-8cd2-7304e62716db.gif)

### Steps to Reproduce / Code Snippets / Screenshots

These are the options I'm using 

```
topBar: {
        title: {
          text: 'My Title',
        },
        background: {
          color: 'transparent',
        },
       drawBehind: true,
},
```

Is there something else I should be applying to make the content visible behind the topbar?

---
### Environment
* React Native Navigation version: 3.1.2
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone XR iOS 12.4 Debug

**Comment by samcampisi** [comment]
Update: after clearing the cache and rebuilding (without changing anything) it showed it exactly as I expected from the start on both platforms. I think it's safe to close!

**Comment by lucazoffoli** [comment]
I have same problem on android...

**Comment by GioLogist** [comment]
`contentInsetAdjustmentBehavior` is a huge one. This should be documented.
