### ISSUE TITLE
Properties pass to child through passProp don't update when parent's state update

### ISSUE THREAD

**Issue by benjaminb10** [wix/react-native-navigation#545]
### Issue Description

Properties pass to child through passProp don't update when parent's state update.

I attend to see the counter increase every second. But that's not the case.
Whereas the natural react native behavior is that child component update when parent's state update and are passed through props.

Is there a way to update the child here?

### Steps to Reproduce / Code Snippets / Screenshots

Navigations:
```
Navigation.registerComponent('Parent', () => Parent);
Navigation.startSingleScreenApp({
  screen: {
    screen: 'Parent',
    title: 'Parent',
  }
})

```

Parent component: 

```
class Parent extends Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      count:0
    }
  }

  _onForward () {
    this.props.navigator.push({
      screen: 'Child',
      title: 'Child',
      passProps: {
        count: this.state.count,
      },
    })
  }

  return (
      <Text onPress={() => this._onForward()}>Click here</Text>
  )

```

Child component:

```
class Child extends Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      count: this.props.count
    }
  }

  return (
      <Text>{this.state.count}</Text>
  )
}
```

**Comment by shahen94** [comment]
See the last comment solution.
https://github.com/wix/react-native-navigation/issues/100 .

Next screen is not a child. Hierarchy is a different here

**Comment by guyca** [comment]
I'm closing as this isn't a bug in RNN 👍

**Comment by benjaminb10** [comment]
Thanks, but:

1. The documentation should be explicit on that, when introducing the `passProps` attribute.
I've lost a long time before understanding that next screen is not a child.

2. Since it's the natural way of working of React props, the attribute name `passProps` is confusing.
Maybe a name like `staticProps` or `staticData` can be less misleading.
