### ISSUE TITLE
CommandsHandler should only delegate to ViewControllers

### ISSUE THREAD

**Issue by guyca** [wix/react-native-navigation#5452]
`RNNCommandsHandler.mergeOptions` calls overrideOptions before actually calling mergeOptions. This is very confusing as it's unexpected and not part of the CommandsHandlers responsibilities and it creates method coupling.

The call to overrideOptions has been moved into ViewController.mergeOptions in a previous commit and can be removed from CommandsHandler.

**Comment by kartik-budhiraja** [comment]
@guyca I would love to work on this issue if it's available. :)
