### ISSUE TITLE
Can you please stop deleting old issues

### ISSUE THREAD

**Issue by tombasche** [wix/react-native-navigation#5453]
I am currently in the process of upgrading an app to RN 59 and the latest react-native-navigation, and have been trying to debug by reading old github issues that match my issue - only to find they've been deleted. Google seems to still index them as results!

I think it would greatly benefit developers if you could just close issues, rather than delete them.

**Comment by ItsNoHax** [comment]
Hi @tombasche , sorry about that, that's my fault completely. I've been trying to clean up as many issues as possible and have deleted some important old issues. My apologies.

**Comment by ItsNoHax** [comment]
I have created an issue where you can post the issue numbers that you would like resolved.
https://github.com/wix/react-native-navigation/issues/5461
Sorry again!

**Comment by tombasche** [comment]
Thanks so much for the response. I totally get it, and I guess it's a side effect of "googling the error"!

**Comment by ItsNoHax** [comment]
@tombasche Don't forget to comment which issues you ran into! Going to be emailing Github support start of next week.

**Comment by tombasche** [comment]
In diving back into the upgrade I've managed to get around the missing issues; but in my journey I have learnt a lot. I'll probably raise a PR that will address some issues I've encountered during the upgrade, and add some more documentation (if it's ok with you!)

**Comment by guyca** [comment]
It's more than ok! We're working on improving the docs - If you'd like you can PR directly to the [new docs](https://github.com/wix/react-native-navigation/tree/docs)
