### ISSUE TITLE
Issue deleted? Post issue number here to get it restored.

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#5461]
Hi all,

I've been doing some maintenance in the repository since there is a high degree of closed issues that bring no value. Unfortunately in the process I've deleted several issues which are important for people who are still using V1 of the library and are looking to update. 

While these issues can still be found from Google's web archive it's not a valid solution so I will be contacting Github support to get the important issues restored.

Please let me know in the comments below which issues I should restore.

I'm really sorry for the inconvenience and I will be extra careful in the future.

**Comment by sijad** [comment]
Please restore this one too:

https://github.com/wix/react-native-navigation/issues/498

**Comment by blueberry6401** [comment]
It's nice to have you taking serious to this. But it's very hard to say which issues we want to restore. 
Like I've searched about passing props when using Navigation.pop, but all the issues related is deleted, like #1208, #2073. I used google cache to view those page, actually there're no solution, but I found what I want: there are no official solution, just workarounds.
I don't know what problems you guys are facing with managing issues, but I think you should delete issues if only it's completely garbage, or else, just close it.

**Comment by guyca** [comment]
You're absolutely right, that was also our intention. But a few beneficial issues were also deleted by mistake. I apologize for that.

**Comment by msqar** [comment]
Please restore this one:
https://github.com/wix/react-native-navigation/issues/760

**Comment by tombasche** [comment]
Could you please restore this issue?
https://github.com/wix/react-native-navigation/issues/1954

**Comment by ItsNoHax** [comment]
Guys, I have contacted Github support and it seems they do not restore deleted issues.
I would like to apologize again for deleting some beneficial issues. The intention was to delete the garbage issues which we have a LOT of.

For now please use web archive/ google cache.
