### ISSUE TITLE
[V3][IOS] Unable to set bottomTab index via mergeOptions after calling setRoot

### ISSUE THREAD

**Issue by andresfcamacho** [wix/react-native-navigation#5462]
### Issue Description

When calling `setRoot` with `bottomTabs` you can't specify an index. This also happened in in V2. The workaround was to immediately call mergeOptions after calling set root. Something like this:

```
bottomTabs: {
    id: BOTTOM_TABS_ID,
    children: [
      {
        stack: { ... }
     },
    {
       stack: { ... }
    },
    {
       stack: { ... }
    }
}


Navigation.setRoot({ root: { bottomTabs }) // the first child or index 0 will be shown
```

```
// This call sets the stack to the middle one
Navigation.mergeOptions(BOTTOM_TABS_ID, {
  bottomTabs: {
    currentTabIndex: 1, // Sets it to the middle one
    titleDisplayMode: 'alwaysHide',
    drawBehind: isAndroid(),
   },
 })
```

### Steps to Reproduce / Code Snippets / Screenshots

But now in V3 that does not work. I also tried setting the `currrentTabIndex` in the root call but that didn't work either.

Note that Android works fine. This is IOS only.
---
### Environment
* React Native Navigation version: 3.1.2
* React Native version: 60.5
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by andresfcamacho** [comment]
I have noticed that if I wrap the `Navigation.mergeOptions` in a `setTimeout` of like 200ms that it changes the index. Obviously this is not workable as the 0 index stack displays then flashes away. Not sure if that helps in fixing the underlying issue.

**Comment by herarya** [comment]
same issue on IOS

**Comment by wongp** [comment]
Still see this in version 3.7.0
