### ISSUE TITLE
Navigating twice then crash when clicking "push" quickly

### ISSUE THREAD

**Issue by ThoMiDev** [wix/react-native-navigation#5463]
### Issue Description

When clicking a button twice quickly, the app navigating twice, then the app crashed.

Here is my logcat

    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.viewcontrollers.ViewController.onViewWillAppear()' on a null object reference
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at com.reactnativenavigation.viewcontrollers.stack.StackController.pop(StackController.java:237)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at com.reactnativenavigation.viewcontrollers.stack.StackController.onNavigationButtonPressed(StackController.java:346)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at com.reactnativenavigation.viewcontrollers.stack.StackController.lambda$E_USFTD4wrvfcO_zXND4bwucwwE(Unknown Source:0)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at com.reactnativenavigation.viewcontrollers.stack.-$$Lambda$StackController$E_USFTD4wrvfcO_zXND4bwucwwE.onPress(Unknown Source:2)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at com.reactnativenavigation.viewcontrollers.TitleBarButtonController.lambda$null$0$TitleBarButtonController(TitleBarButtonController.java:108)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at com.reactnativenavigation.viewcontrollers.-$$Lambda$TitleBarButtonController$_QWYPM6-64Ztw2vdeRiTPb9kqYQ.onClick(Unknown Source:2)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at android.view.View.performClick(View.java:6597)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6574)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25885)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6680)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    09-07 17:17:36.861  5887  5887 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

---
### Environment
* React Native Navigation version: 3.0.0
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): Android Crashed, iOS navigate twice
* Device info (Simulator/Device? OS version? Debug/Release?): All device

**Comment by lnanhkhoa** [comment]
same me. can anyone help?
