### ISSUE TITLE
[V3] registerBottomTabSelectedListener not being triggered when changing tab using mergeOptions

### ISSUE THREAD

**Issue by msqar** [wix/react-native-navigation#5464]
### Issue Description
I have a registerBottomTabSelectedListener and whenever I call mergeOptions to change currentTabIndex, is never called. Is only triggered only when I tap on the bottom buttons myself.

### Steps to Reproduce / Code Snippets / Screenshots
```
this.bottomTabEventListener = Navigation.events().registerBottomTabSelectedListener(this._tabChanged);
```

And then I simply call the changeTab like this:

```
        this.setState({itemSelectionModalVisible: false}, () => {
            Navigation.mergeOptions(this.props.componentId, {
                bottomTabs: {
                    currentTabIndex: 2 //3rd tab
                }
            });
        });
```

---
### Environment
* React Native Navigation version: 3.1.2
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone XS real device debug.

**Comment by msqar** [comment]
Another bug related to mergeOptions. Whenever i change currentTabIndex, it changes, but my whole bottomTabs disappear. I only see a white space now, any ideas!?

**Comment by jackytwh** [comment]
Any updates?
