### ISSUE TITLE
BottomTabs - Buttons do not realign after orientation change

### ISSUE THREAD

**Issue by Damar95** [wix/react-native-navigation#5465]
### Issue Description
The Buttons of BottomTabs do not realign after orientation change.

### Steps to Reproduce / Code Snippets / Screenshots

1. Open BottomTab app in any orientation
2. Change orientation
Landscape:
![Screenshot_20190908-174914_cookapp](https://user-images.githubusercontent.com/24271650/64490868-e066b980-d261-11e9-83b2-f70ee38142ca.jpg)
...not Lanscape:
![Screenshot_20190908-174934_cookapp](https://user-images.githubusercontent.com/24271650/64490869-e361aa00-d261-11e9-852b-a976ccd82a41.jpg)

---
### Environment
* React Native Navigation version: 3.1.0
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by williamtran1988** [comment]
I have the same problem on:
"react-native-navigation": "3.2.0",
 "react-native": "0.60.5",
Platform: Android

**Comment by sapjunior** [comment]
I also encounter this situation as well. Any way to fix this problem?

**Comment by sapjunior** [comment]
Is there any workaround for this problem?

**Comment by BoyanaKarzhilova** [comment]
I encounter the same situation. Any workarounds?

**Comment by guyca** [comment]
Fixed in [6.5.0](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#android-3)
