### ISSUE TITLE
Load index.js twice and all compoenents are created two instance on iOS

### ISSUE THREAD

**Issue by genglei01** [wix/react-native-navigation#5470]
### Issue Description

RNN Load index.js twice and all components create two instances on iOS.

### Steps to Reproduce / Code Snippets / Screenshots
Create a new react-native and integrate with RNN.
```

import {AppRegistry} from 'react-native';
import { Navigation } from "react-native-navigation";

import App from './App';
import {name as appName} from './app.json';
console.log("===========index");

Navigation.registerComponent(`navigation.playground.WelcomeScreen`, () => App);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      component: {
        name: "navigation.playground.WelcomeScreen"
      }
    }
  });
});
```
I do not know why it load index.js twice.

```

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];
  
  return YES;
}

@end

```
---
### Environment
 "react": "16.8.3",
"react-native": "0.59.8",
"react-native-navigation": "^2.26.5"
* Platform(s) (iOS, Android, or both?): 
* Device info (Simulator/Device? OS version? Debug/Release?): (Simulator&Device, Debug

**Comment by eightyfive** [comment]
I kinda think the same is happening to me, although this is a pretty broad bug surface.

In my case:

- iOS 12.4
- Running on device (iPhone 6)
- RELEASE/Ad-Hoc build
- RNN `2.29.0`
- RN `0.59.9`

Steps to reproduce:

1. Install app (Ad-Hoc build) on device
2. Launch app for the first time
3. App runs normally
4. Close/kill app
5. Open app again
6. App seems to launch twice...

By "seem to launch twice" I mean:

1. I see the native/RNN splash screen
2. I briefly see the state of my app when I first closed/killed it !
3. I see the native splash screen again...
4. App launched, supposedly for the second time...

Notes:

- The app works fine the very first time it is launched !
- Only happens with my Ad-Hoc build! Works fine in DEBUG mode
- On the "second launch", the app is completely out of sync (`setDefaultOptions` not called on 2nd instance,`navigationButtonPressed` not called on 2nd instance...)
