### ISSUE TITLE
Strange overlay on top of top bar

### ISSUE THREAD

**Issue by robertying** [wix/react-native-navigation#5472]
### Issue Description

I've seen this overlay on top of top bar when the large title enabled.

It seems to appear with or without dark mode turned on.

I checked from the view hierarchy and found out it was a `UIImageView` in `_UIBarBackground`. But setting:

```js
  topBar: {
    background: {
      color: 'black'
    }
  }
```

does not help at all.

The white overlay has opacity 1 when the large title is fully shown and disappear gradually when scrolling up.

Is there any way to get rid of this?

### Steps to Reproduce / Code Snippets / Screenshots

![image](https://user-images.githubusercontent.com/22592111/64717068-276cdd00-d4f6-11e9-9d44-b20fd64091e4.png)

![image](https://user-images.githubusercontent.com/22592111/64717082-305dae80-d4f6-11e9-8e13-7f31ce59dbf9.png)

![ezgif com-resize (1)](https://user-images.githubusercontent.com/22592111/64719092-1e7e0a80-d4fa-11e9-89ba-a893f04e767c.gif)

---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.60.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and real device (iPad). iOS 13. Debug and Release.

**Comment by cesargdm** [comment]
Also having problems with dark mode on large titles 
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-13 at 15 39 47](https://user-images.githubusercontent.com/10179494/66722162-d50e2d00-edcf-11e9-88b1-05459bbefedc.png)
![Simulator Screen Shot - iPhone 11 Pro - 2019-10-13 at 15 39 41](https://user-images.githubusercontent.com/10179494/66722163-d50e2d00-edcf-11e9-896c-2c85aba52565.png)
