### ISSUE TITLE
Modals onDismiss called twice

### ISSUE THREAD

**Issue by Xesme** [wix/react-native-navigation#5478]
### Issue Description

When dismissing a modal the callback function onDismiss is called twice. This causes the app to re-render twice if you are setting states within the callback. This can cause big problems with timers, etc. The navigation library should not be dismissing twice. 

### Steps to Reproduce / Code Snippets / Screenshots

1. Create an application. 
2. Create a modal. 
3. Console.log how many time the onDismiss callback is being called. 
---
### Environment
* React Native Navigation version: RNN v2.22.3 
* React Native version: RN v59.10 
* Platform(s) (iOS, Android, or both?): Both 
* Device info (Simulator/Device? OS version? Debug/Release?): All Android and iOS devices.

**Comment by tengkuhafidz** [comment]
Faced the same issue

**Comment by ItsNoHax** [comment]
Hi @Xesme ,

First of all you will need to provide a reproducible example since there is no onDismiss callback on RNN modals thus it might potentially not be a RNN issue.

Also it seems you are not using the latest version of RNN, please upgrade to the latest V2 version and try again.
