### ISSUE TITLE
Install and configuration for react-native 0.60+

### ISSUE THREAD

**Issue by lucazoffoli** [wix/react-native-navigation#5479]
How install and configure package for react-native 0.60+?

I've a problem to configure react-native-navigation for my project with react-native 0.60+.
My class MainApplication already extended MultiDexApplication, how add ReactNavigation?

The class don't import library:
![image](https://user-images.githubusercontent.com/49115596/64843220-cda70880-d604-11e9-9d7e-7ab61866b046.png)

I read this guide to install:
https://wix.github.io/react-native-navigation/#/docs/Installing

Before change MainApplication it's that:
![image](https://user-images.githubusercontent.com/49115596/64843445-705f8700-d605-11e9-97fd-90a6dff4b245.png)

---
### Environment
* React Native Navigation version: ^3.2.0
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): -

**Comment by randomBrainstormer** [comment]
For Android I simply followed the guide in the documentation then added this change indicated by luskin [here](https://github.com/wix/react-native-navigation/pull/5318#issuecomment-531302801) to include autolinking:

```java
protected List<ReactPackage> getPackages() {
    @SuppressWarnings("UnnecessaryLocalVariable")
    List<ReactPackage> packages = new PackageList(this).getPackages();  // <-- this
    // Packages that cannot be autolinked yet can be added manually here, for example:
    // packages.add(new MyReactNativePackage());
    return packages;
  }
```

For iOS I just added the dependency to the Pods file it using Pods, and followed the documentation to modify the `AppDalegate.m` file.

I'm using version: `3.0.0-alpha.1"` with react-native: `0.61.0`

**Comment by Peeeep** [comment]
There are three alternative ways of using Multidex (https://developer.android.com/studio/build/multidex#mdex-gradle), and for React-Native-Navigation, the third one works like charm. S

```java
package your.amazing.application;

import android.content.Context;
import androidx.multidex.MultiDex;
import com.facebook.react.PackageList;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.reactnativenavigation.NavigationApplication;
import com.reactnativenavigation.react.NavigationReactNativeHost;
import com.reactnativenavigation.react.ReactGateway;

import java.util.List;

public class MainApplication extends NavigationApplication {
  @Override
  protected void attachBaseContext(Context base) {
      super.attachBaseContext(base);
      MultiDex.install(this);
  }

  @Override
  protected ReactGateway createReactGateway() {
      ReactNativeHost host = new NavigationReactNativeHost(this, isDebug(), createAdditionalReactPackages()) {
          @Override
          protected String getJSMainModuleName() {
              return "index";
          }
      };
      return new ReactGateway(this, isDebug(), host);
  }

  @Override
  public boolean isDebug() {
      return BuildConfig.DEBUG;
  }

  protected List<ReactPackage> getPackages() {
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      return packages;
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
      return getPackages();
  }
}

```
