### ISSUE TITLE
[V3] Is there a way to set topBar title dynamically based on redux props?

### ISSUE THREAD

**Issue by fel-ri** [wix/react-native-navigation#5481]
### Issue Description

I need to set the title bar based on some params on redux, is there any way to do this? Props inside options return null

### Steps to Reproduce / Code Snippets / Screenshots
```
  static options(props) {
    let day = props.selectedDay || new Date()
    return Stack.getTitleObj(day.getDay())
  }
```

### Environment
* React Native Navigation version: 3.0.0
* React Native version: 0.60
* Platform(s) (iOS, Android, or both?): noth

**Comment by bneigher** [comment]
You can use 
`mergeOptions(this.props.componentId, { topBar: { title: { text: "New Title" }}})`
 (call it on `getDerivedStateFromProps`) when the prop you're interested in changes.
