### ISSUE TITLE
[V3] Title doesn't look like a UINavigationController title on iOS

### ISSUE THREAD

**Issue by drewhamlett** [wix/react-native-navigation#5484]
### Issue Description

Title is not bold and the vertical center doesn't seem right.  If I look at other apps on my phone the title is more vertically centered to line up with left and right buttons.

I had an issue in my project so I decided to just pull down master and run the playground locally.  XCode 10, with iOS 12

<img width="476" alt="Screen Shot 2019-09-14 at 11 34 11 AM" src="https://user-images.githubusercontent.com/1056587/64910933-ba219d80-d6e9-11e9-8ce6-9d0bfe210623.png">

From https://developer.apple.com/documentation/uikit/uinavigationcontroller

![navigation_interface_2x_8f059f7f-2e2f-4c86-8468-7402b7b3cfe0](https://user-images.githubusercontent.com/1056587/64910945-e1786a80-d6e9-11e9-9ad1-f4e5f2c74672.png)

### Steps to Reproduce / Code Snippets / Screenshots

Clone react-native-navigation and run playground.

---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.60.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, ios 12, xcode 10

Thanks!

**Comment by blueberry6401** [comment]
I reported this and didn't receive response.
https://github.com/wix/react-native-navigation/issues/5431#issue-487750126

**Comment by drewhamlett** [comment]
Ahh I see now.  My search skills aren't that good.  I was thinking when I reported, I couldn't be the only one seeing this.

**Comment by ivan3177** [comment]
Still not fixed. Any updates on this?
