### ISSUE TITLE
Can you have a background video for entire app that continues playing through screen changes

### ISSUE THREAD

**Issue by JunoVW** [wix/react-native-navigation#5488]
### Issue Description

I am designing an app that has a video playing in the background (some nice soothing animation). The problem I am facing is that I set the background video on a certain screen, and thus if I navigate to another screen the video restarts because it is loaded/mounted again. I am navigating using `setStackRoot`.

I have tried to create a stack which consist of `[ background video screen, app screen ]` so that the background would not need to be re-mounted (and then navigating using `popToRoot` and `push` for changing screens). However then I run into the problem that the second screen in the stack needs to be transparent and as far as I know this is not possible.

So my question is: Is it at all possible to have a background video persist playing through multiple screens?
### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 2.27.5
* React Native version: 0.56.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): --

**Comment by samiede** [comment]
You can try playing the video in an overlay and give all screens a top offset so that they begin below the video. 
https://wix.github.io/react-native-navigation/#/docs/top-level-api?id=showoverlaylayout-

**Comment by JunoVW** [comment]
> You can try playing the video in an overlay and give all screens a top offset so that they begin below the video.
> https://wix.github.io/react-native-navigation/#/docs/top-level-api?id=showoverlaylayout-

What do you mean with top offset?

**Comment by samiede** [comment]
I mean that the screens take up the whole space on the screen, but since the overlay blocks the upper part of the screen, you need to push the contents you want to show down, which can be achieved with a paddingTop :)

Von meinem iPhone gesendet
