### ISSUE TITLE
[V3] Question: Is there an event dispatched when visibility of the bottomTabs is toggled?

### ISSUE THREAD

**Issue by ptfly** [wix/react-native-navigation#5496]
I'd like to have a custom `bottomTabs` component and it seems to be achievable with an overlay over the native bar, except when I want to hide it on certain components pushed in the stack. If I do it with `mergeOptions` and toggle it's visibility, it doesn't feel native because I'm hiding it when my other component is mounted, also have problems with `drawBehind` when toggling visibility. Instead I'm using `static options = {}` to hide it in certain screens. So here is my main issue, there is no event I can subscribe to and to hide/show my custom overlay. At least I can't find anything about it in the docs and in the source code.

**Comment by bneigher** [comment]
I'm also interested in this (I've done the same thing here
![image](https://user-images.githubusercontent.com/4627728/65538404-15a71480-debc-11e9-88de-4325e7229fdb.png)

What I've done is added a redux event for SCENE (and I've whitelisted scenes which should have the overlay) - This solution works but there is a 500ms delay or so

Another option was to give and Id to the overlay so I can toggle it directly with the Navigation.show/dismiss overlay piece - Still a delay and hard to have coverage.

It would be awesome to have an event that fires when a screen begins to get pushed/popped, or when a scene begins to change in any way.  That way we can do tricky things like add the bigger bottomTab icon (I've seen other people ask how to do this on here)

**Comment by bneigher** [comment]
Hey guys, is there any update to this?  Today we need to write our own scene logic to determine if the overlay should be visible.  Having a fast native event that we can respond to would really help those who want to have custom bottomTabs
