### ISSUE TITLE
[V3] Android topBar rightButtons component not centered

### ISSUE THREAD

**Issue by MakhouT** [wix/react-native-navigation#5497]
### Issue Description
I have a rightButton component in my topbar. On iOS it's works and looks as expected. The issue is on android, that it is not centering

iOS
![image](https://user-images.githubusercontent.com/3041165/65232128-eb76e080-dad0-11e9-8c6b-0b58ae785b90.png)

Android
![image](https://user-images.githubusercontent.com/3041165/65232144-f3368500-dad0-11e9-8419-6c8d72538056.png)

Some snippets of code:
The bottomTab Option to create the rightButton in the topBar
```js
              topBar: {
                title: {
                  text: tab.title,
                },
                rightButtons: rightButtonAvatar(tab.name),
              },
```

```js
const rightButtonAvatar = tabId => [
  {
    id: CONSTANTS.AVATAR_COMPONENT,
    component: {
      name: CONSTANTS.AVATAR_COMPONENT,
      passProps: {
        tabId,
      },
    },
  },
];
```

And the actual component
```js
const styles = StyleSheet.create({
  wrapper: {
    alignItems: 'flex-end',
    zIndex: 999,
    position: 'relative',
  },
  avatarContainer: {
    width: 35,
    height: 35,
    borderRadius: 100,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    position: 'relative',
  },
  avatarContainerOk: {
    backgroundColor: S.COLOR.OK,
  },
  networkStatus: {
    width: 25,
    height: 25,
    borderRadius: 100,
    position: 'absolute',
    right: -10,
    bottom: -5,
    justifyContent: 'center',
    alignContent: 'center',
    flex: 1,
  },
  initials: {
    fontWeight: '600',
  },
  statusIcon: {
    height: 15,
    width: undefined,
  },
});

export const Avatar: React.FC<IAvatarProps> = props => {
  return (
    <View style={styles.wrapper}>
      <TouchableOpacity
        style={[styles.avatarContainer]}
      >
        <Text style={styles.initials}>
         NM
        </Text>
        <View
          style={[
            styles.networkStatus,
            styles.avatarContainerOk
          ]}
        >
          <Image
            source={ICONS_MAP.PAUSE}
            style={styles.statusIcon}
            resizeMode="contain"
          />
        </View>
      </TouchableOpacity>
    </View>
  );
};

```
---
### Environment
* React Native Navigation version: **3.2.0**
* React Native version: **0.60.5**
* Platform(s) (iOS, Android, or both?): **Only Android**
* Device info (Simulator/Device? OS version? Debug/Release?): **Simulator Android Pixel C tablet**

**Comment by MakhouT** [comment]
Update: When pressing the avatar in the top right hand side, I display an overlay.
When pressing on the few pixels of the avatar I have on android, the overlay shows. When I close the overlay, the avatar is shown fully in the top right hand side corner (still not centered though, but you can see it fully)

**Comment by MakhouT** [comment]
Is someone able to reproduce this? Still having this issue...

**Comment by NISUSIN** [comment]
Same here, but only when I use mergeOptions, if I update the color of rightButton, it's going upside and can't push any component. I tried lot of workaround, but no one works

**Comment by MakhouT** [comment]
I am not using any mergeOptions. @guyca is back, so hopefully he knows what's going on.

**Comment by MakhouT** [comment]
Bump - still not stale.

**Comment by MakhouT** [comment]
Not stale.

**Comment by MakhouT** [comment]
Still not stale.

**Comment by MakhouT** [comment]
This is still an issue...
