### ISSUE TITLE
startSingleScreenApp (or show Modal) on TabBar Icon Press

### ISSUE THREAD

**Issue by pvlvsk** [wix/react-native-navigation#55]
Hello,

how i would manage to push a single Screen, when i tap an Icon in a TabBarBasedApp? For example in the Instagram app you tap on the camera in the tab bar and the whole view slides down to reveal the photo library, a custom screen without tabbar.. I would like to mimic this behavior...

Thank you!

**Comment by guyca** [comment]
You can check out  `example-redux` sample project. In [FirstTabScreen](https://github.com/wix/react-native-navigation/blob/master/example-redux/src/screens/FirstTabScreen.js) we first defines `navigatorButtons`, Where each button has an id. Then in `onNavigatorEvent` we handled the button clicks.

To Push a screen, refer to (onPushPress)[https://github.com/wix/react-native-navigation/blob/master/example-redux/src/screens/FirstTabScreen.js#L94] method.

Hope this helps you

**Comment by pvlvsk** [comment]
This would be a push within the navigator with navigator buttons... How that would be working for a tab bar press?

**Comment by tendolukwago** [comment]
@pvlvsk Did you ever get an answer on how to do this?

**Comment by saxahan** [comment]
I have written hacky code, but not a good solution unfortunately.

` if (event.id === 'bottomTabSelected') {
            if (event.selectedTabIndex === 2) { // your screen tab index to dispatch to push an action
                navigator.showModal({
                    screen: SCREENS.POST.id,
                    title: SCREENS.POST.title,
                    overrideTabPress: true
                });

                let tabIndexToSelect = !event.unselectedTabIndex || event.unselectedTabIndex === 2 ? 0 : event.unselectedTabIndex;
                navigator.switchToTab(tabIndexToSelect);
            }
        }`

As you guess, before you see opening your desired screen with press action, select index for ios has been trigger and causes flickers :/

**Comment by n1ru4l** [comment]
@guyca Can you please reopen this issue? There is currently no clean solution for this. I also know this behaviour from the instagram app.

**Comment by moeinrahimi** [comment]
any one how to achieve this ?

**Comment by gaultierq** [comment]
please re-open

**Comment by yunus-alkan** [comment]
I made it work guys. You can see my codes above.

**Comment by jarrx** [comment]
But it flickers you said? Even though it might work it would be great with a solution that is not a hack and that does not flicker.
