### ISSUE TITLE
[V3] iOS 13 pageSheet Modal: can't disable popGesture

### ISSUE THREAD

**Issue by Dexwell** [wix/react-native-navigation#5500]
### Issue Description

The new iOS 13 pageSheet modal can be dismissed by dragging it away by default. This can't currently be disabled by setting `popGesture` to `false`.

---
### Environment
* React Native Navigation version: 3.1.0
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 13.0

**Comment by Dexwell** [comment]
Still very relevant... @guyca

**Comment by eladgel** [comment]
@yogevbd are you guys going to enable this? I think we could come with  a couple of nice ux's and use this. when blocking the dismiss gesture

**Comment by guyca** [comment]
Swipe to dismiss modal gesture can be disabled in options:

```js
options: {
  modal: {
    swipeToDismiss: false
  }
}
```
