### ISSUE TITLE
Execution failed for task ':react-native-navigation:compileReactNative57_5DebugJavaWithJavac'. > Compilation failed; see the compiler error output for details.

### ISSUE THREAD

**Issue by nahidmbstu** [wix/react-native-navigation#5501]
Execution failed for task ':react-native-navigation:compileReactNative57_5DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

    "react-native-navigation": "^2.12.0",

### Environment
React Native Environment Info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
      Memory: 274.66 MB / 11.64 GB
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 8.10.0 - /usr/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 3.5.2 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.5 => 0.58.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by cinder92** [comment]
same issue here with RN 0.61.2

**Comment by bonellicious** [comment]
+1
