### ISSUE TITLE
popGesture: false causes bugs for using the pop gesture on children screens

### ISSUE THREAD

**Issue by idanlo** [wix/react-native-navigation#5502]
### Issue Description
on iOS when using the `popGesture: false` option on a screen it works as intended but then after pushing a new screen with popGesture enabled it doesn't work and then the screen doesn't respond to anything - scrollviews and touchables don't respond, after reopening the app (without removing it from recents) it will go back.

### Steps to Reproduce / Code Snippets / Screenshots
Create a stack layout, push a screen with the option `popGesture: false`, then push another screen without options and see that you cannot use the pop gesture - the app will be stuck.

### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 11 Simulator

**Comment by idanlo** [comment]
this issue is urgent. this basically makes `popGesture: false` useless because it will disable that gesture for the entire application after the screen that has that option

**Comment by rvera** [comment]
I can confirm this happens.

**Comment by idanlo** [comment]
Nor stale
