### ISSUE TITLE
Modal in iOS doesn't recenter upon showing keyboard

### ISSUE THREAD

**Issue by henry132109** [wix/react-native-navigation#5504]
### Issue Description

I'm creating a little form within a modal with Text Input boxes.
When I focus on it, the keyboard appears.
On android, the modal is recentered and the keyboard doesn't cover modal content.
![android](https://user-images.githubusercontent.com/26480299/65410290-8860b300-de1c-11e9-8443-9bea70b9a2a4.jpg)
On iOS, the modal is not recentered and the keyboard covers the submit buttons.
![iOS](https://user-images.githubusercontent.com/26480299/65410291-88f94980-de1c-11e9-9b77-731cbe61a86b.jpg)
(despite the different input methods, they are indeed the same modal)

### Steps to Reproduce / Code Snippets / Screenshots
```js
Navigation.showModal({
  component: {
    id,
    name: id,
    passProps,
    options: {
      modalPresentationStyle: 'overCurrentContext',
      blurOnUnmount: true,
      animations: {
        showModal: {
          enable: false
        },
        dismissModal: {
          enable: false
        }
      }
    }
  }
});
```
---
### Environment
* React Native Navigation version: 2.26.4
* React Native version: 0.58.5
* Platform: iOS
* Device info: Device, 11.2.5 & 13.0.0, Release

**Comment by caicheng** [comment]
same here
