### ISSUE TITLE
[V2-V3] [iOS 13] Topbar custom background not working

### ISSUE THREAD

**Issue by FRizzonelli** [wix/react-native-navigation#5505]
### Issue Description

Probably related to #5468
Bug is present only when building for iOS 13 (think it's probably related to the release of dark mode from Apple).
After some investigation, problem is inside _RNNNavigationControllerPresenter.m_ in this method:

```
- (void)presentBackgroundComponent {
	RNNNavigationController* navigationController = self.bindedViewController;
	if (_customTopBarBackground) {
		[_customTopBarBackground removeFromSuperview];
	}
	RNNCustomTitleView* customTopBarBackground = [[RNNCustomTitleView alloc] initWithFrame:navigationController.navigationBar.bounds subView:_customTopBarBackgroundReactView alignment:@"fill"];
	_customTopBarBackground = customTopBarBackground;
	
	[navigationController.navigationBar insertSubview:_customTopBarBackground atIndex:1];
}
```

Using insertSubView cover all content of navigationItem (including title, buttons, etc.). I've tried some other methods with different index, movesubviews below and stuffs, but I wasn't able to make it work :(
Does someone have any idea on how to fix this?

### Steps to Reproduce / Code Snippets / Screenshots

```js
stack: {
      children: [
        {
          component: {
            name: ScreenKeys.dashboardScreen,
            options: {
              topBar: {
                title: {
                  text: 'Dashboard',
                  color: Colors.WHITE
                },
                rightButtonColor: Colors.WHITE,
                backButton: {
                  color: Colors.WHITE
                },
                background: {
                  component: {
                    name: NavigationKeys.topBarBackground
                  }
                }
              },
            }
          }
        }
      ],
    },
```

Build on iOS 13:
![broken](https://user-images.githubusercontent.com/12106217/65413225-4706de00-ddf1-11e9-9167-dc5f3797574e.gif)

Same build on iOS 12:
![working](https://user-images.githubusercontent.com/12106217/65413653-31de7f00-ddf2-11e9-9cf5-2f5dc21ee120.gif)

---
### Environment
* React Native Navigation version: Latest v2, latest v3
* React Native version: 0.59.10 for v2, latest for v3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device, iOS 13, Debug and Release

**Comment by ivan3177** [comment]
Any updates on this?

**Comment by wongp** [comment]
Bump.

**Comment by JB-CHAUVIN** [comment]
Same issue goes for me... on iOS 13 with a custom top bar component, the title + the buttons are not visible.

**Comment by JB-CHAUVIN** [comment]
Bump... can we re-open it ?

**Comment by FernandoTN** [comment]
Same issue for me, only on iOS. Android seems to work fine.

**Comment by snairsumith** [comment]
Yes me too same issue any updates?
