### ISSUE TITLE
selectedTextColor Issue

### ISSUE THREAD

**Issue by eladgel** [wix/react-native-navigation#5510]
### Issue Description

selectedTextColor for bottomTab defaults to blue after modal opened

### Steps to Reproduce / Code Snippets / Screenshots

I have a scenario that makes the selectedTextColor in a bottomTab element malfunction:
You can use the Playground app for the test
1. Open the app with tabs have all the tabs selectedTextColor to 'red' and textColor to 'green'
2. Open any modal
3. Close the modal
4. Switch tabs, you will see that almost all the tabs except for the one that was chosen when the Modal was opened, the selectedTextColor changes to BLUE when you tap on it

---
### Environment
* React Native Navigation version: 3.0.0-alpha.8
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator+Device Debug+Release

**Comment by vjtc0n** [comment]
I'm facing the same issue, any idea how to solve it ?
Or currently, we have to change the native code :|
Thanks

**Comment by TuTejsy** [comment]
I have the same issue, how to fix it?

**Comment by SukhKalsi** [comment]
Any update on this? Seems to affect both v2 and v3.

**Comment by guyca** [comment]
fixed in v4

**Comment by mtebele** [comment]
Already happening in v4..

**Comment by emilioheinz** [comment]
Any workaround on this?

**Comment by mtebele** [comment]
> Any workaround on this?

I've _fixed_ it using this setting:

```
Navigation.setDefaultOptions({
    ...
    bottomTab: {
      textColor: '#ffffff',
      selectedTextColor: '#ffffff',
      selectedIconColor: '#ffffff',
    },
    ...
```

**Comment by emilioheinz** [comment]
@mtebele I'm already using this config and it doesn't work.
