### ISSUE TITLE
How to handle the topbar back button onpress

### ISSUE THREAD

**Issue by nidhinkumar06** [wix/react-native-navigation#5511]
### Issue Description

I am using react native navigation in which the top bar shows the back button by default. I would like to create an on press event for the button. I would like to know whether it is possible or not.

### Steps to Reproduce / Code Snippets / Screenshots

I have tried using a custom back button with id and using 
```
const buttonClickListener = Navigation.events().registerNavigationButtonPressedListener(
      ({ buttonId }) => {
        if (buttonId === 'BACK') {
          isFormFilled();
        }
      },
    );
```
But I would like to know whether it is possible to do it in default
---
### Environment
* React Native Navigation version: 2.21.1
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by Jeffrey-Dozva** [comment]
Check example below

`
export default class Home extends Component {
  constructor(props) {
    super(props);
    Navigation.events().bindComponent(this);
  }
  static options(passProps) {
    return {
      topBar: {
        title: {text: 'Home'},
        leftButtons: [
          {
            id: 'menu',
            icon: icons.menu,
          },
        ],
        rightButtons: []
      },
    };
  }
  navigationButtonPressed = ({buttonId}) => {
    if (buttonId === 'menu') {
      Navigation.mergeOptions(this.props.componentId, {
        sideMenu: {
          left: {
            visible: true
          }
        }
      });
    }
  };
}
`

**Comment by jaygould** [comment]
You're able to do this in v7.37.0:

```
options: {
  topBar: {
    backButton: {
      popStackOnPress: false; // add this
    }
  }
}
```

This disables default behaviour and allows the back button event to appear in `registerNavigationButtonPressedListener`.
