### ISSUE TITLE
[V3] largeTitle breaks title transitions and render title twice

### ISSUE THREAD

**Issue by ivan3177** [wix/react-native-navigation#5515]
### Issue Description

If largeTitle is enabled on version 3.2.0 then:
1. Title is rendered twice
2. Title on next screen in stack is positioned wrong if it's not largeTitle
3. When going back to screen with largeTitle second(not right rendered) title is repositioned unexpectedly 

On version 2.21.0(before update to latest v3 release) everything was OK

### Steps to Reproduce / Code Snippets / Screenshots

```js
static options() {
  return {
    topBar: {
      title: {
        text: 'Test',
      },
      largeTitle: {
        visible: true,
      },
    }
}
```

Now:
![Simulator Screen Shot - iPhone X 11 4 - 2019-09-25 at 00 50 39](https://user-images.githubusercontent.com/16151675/65553405-7a4f8700-df2f-11e9-9682-6276f03a874a.png)
![Simulator Screen Shot - iPhone X 11 4 - 2019-09-25 at 00 50 45](https://user-images.githubusercontent.com/16151675/65553406-7a4f8700-df2f-11e9-90c5-c2524f7cde21.png)
![Simulator Screen Shot - iPhone X 11 4 - 2019-09-25 at 00 50 47](https://user-images.githubusercontent.com/16151675/65553407-7a4f8700-df2f-11e9-86a1-fadb1173a8b2.png)

Expected: 
![Simulator Screen Shot - iPhone X 11 4 - 2019-09-25 at 00 42 20](https://user-images.githubusercontent.com/16151675/65553387-702d8880-df2f-11e9-82ae-bf9096a25a28.png)
![Simulator Screen Shot - iPhone X 11 4 - 2019-09-25 at 00 46 18](https://user-images.githubusercontent.com/16151675/65553388-70c61f00-df2f-11e9-9b9e-3a5f713a20fc.png)

---
### Environment
* React Native Navigation version: 2.21.0 -> 3.2.0
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): iOS 12.2
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by marf** [comment]
Same problem here!

**Comment by davrosull** [comment]
I'm seeing the same problem too. 

Also seeing the title not being set unless I call `mergeOptions` in the constructor.

```    
 Navigation.mergeOptions(this.props.componentId, {
       topBar: {
         title: { text: 'Header Title' },
         largeTitle: { visible: true, color: 'white' },
       },
     });
```

---
### Environment
* React Native Navigation version: 2.21.0 -> 3.2.0
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): iOS 12.4
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by nbolender** [comment]
+1

**Comment by ivan3177** [comment]
Any updates on this?

**Comment by ayouidaniel** [comment]
+1

**Comment by yogevbd** [comment]
Fixed in https://github.com/wix/react-native-navigation/commit/65118b1ed28dd5a4636dabd5952c515d18a0b802
