### ISSUE TITLE
[V3][iOS][iOS13] everything with stack crash my app

### ISSUE THREAD

**Issue by cesarm16** [wix/react-native-navigation#5516]
### Steps to Reproduce / Code Snippets / Screenshots

if i use this code my app crash 

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      stack: {
        children: [{
          component: {
            name: "screen_welcome"
          }
        }]
      }
    }
  });
});

if i remove the stack and children lines it works.
---
### Environment
* React Native Navigation version: 3.1.1
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): iOS Xcode 11
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 13 Device and Simulator 

Xcode output:

2019-09-24 17:42:51.852 [info][tid:main][RCTRootView.m:293] Running application screen_welcome ({
    initialProps =     {
        componentId = Component2;
    };
    rootTag = 1;
})
2019-09-24 17:42:51.863879-0500 myApp[17041:228396] Running application screen_welcome ({
    initialProps =     {
        componentId = Component2;
    };
    rootTag = 1;
})
2019-09-24 17:42:51.863837-0500 myApp[17041:229341] [reports] Main Thread Checker: UI API called on a background thread: -[UINavigationController topViewController]
PID: 17041, TID: 229341, Thread name: (none), Queue name: com.apple.root.user-initiated-qos, QoS: 25
Backtrace:
4   myApp                            0x0000000105422d2c -[RNNNavigationController getCurrentChild] + 44
5   myApp                            0x0000000105454205 -[UIViewController(LayoutProtocol) resolveOptions] + 69
6   myApp                            0x00000001054548d5 __62-[UIViewController(LayoutProtocol) renderTreeAndWait:perform:]_block_invoke + 869
7   libdispatch.dylib                   0x00000001078c7df0 _dispatch_call_block_and_release + 12
8   libdispatch.dylib                   0x00000001078c8d64 _dispatch_client_callout + 8
9   libdispatch.dylib                   0x00000001078da46e _dispatch_root_queue_drain + 819
10  libdispatch.dylib                   0x00000001078daba4 _dispatch_worker_thread2 + 132
11  libsystem_pthread.dylib             0x00007fff5141c6b3 _pthread_wqthread + 583
12  libsystem_pthread.dylib             0x00007fff5141c3fd start_wqthread + 13
2019-09-24 17:42:52.060140-0500 myApp[17041:228396] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'This UIImage instance unexpectedly has nil content. Did calling code create an image with [UIImage alloc] without also sending -init? That's unsupported. 0x60000219e880'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23b98a1c +[NSException raise:format:] + 188
	3   UIKitCore                           0x00007fff46d8655e -[UIImage size] + 95
	4   UIKitCore                           0x00007fff467e1417 -[UINavigationBar setShadowImage:] + 141
	5   CoreFoundation                      0x00007fff23b9f95c __invoking___ + 140
	6   CoreFoundation                      0x00007fff23b9cf22 -[NSInvocation invokeUsingIMP:] + 194
	7   UIKitCore                           0x00007fff46d4e549 __workaround10030904InvokeWithTarget_block_invoke + 84
	8   UIKitCore                           0x00007fff4760140d +[UIView _performSystemAppearanceModifications:] + 56
	9   UIKitCore                           0x00007fff46d48bff applyInvocationsToTarget + 1410
	10  UIKitCore                           0x00007fff46d47e90 +[_UIAppearance _applyInvocationsTo:window:matchingSelector:onlySystemInvocations:] + 1789
	11  UIKitCore                           0x00007fff4762de6b __88-[UIView(Internal) _performUpdatesForPossibleChangesOfIdiom:orScreen:traverseHierarchy:]_block_invoke + 62
	12  UIKitCore                           0x00007fff4762ddf5 -[UIView(Internal) _performUpdatesForPossibleChangesOfIdiom:orScreen:traverseHierarchy:] + 184
	13  UIKitCore                           0x00007fff467ea833 -[UINavigationBar _didChangeFromIdiom:onScreen:traverseHierarchy:] + 51
	14  UIKitCore                           0x00007fff4762dd14 -[UIView(Internal) _didChangeFromIdiomOnScreen:traverseHierarchy:] + 174
	15  UIKitCore                           0x00007fff4762d0fa -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1519
	16  UIKitCore                           0x00007fff467e7dd2 -[UINavigationBar _didMoveFromWindow:toWindow:] + 53
	17  UIKitCore                           0x00007fff4762cdd3 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 712
	18  UIKitCore                           0x00007fff4762cdd3 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 712
	19  UIKitCore                           0x00007fff47620483 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 151
	20  UIKitCore                           0x00007fff47620373 -[UIView(Hierarchy) _postMovedFromSuperview:] + 753
	21  UIKitCore                           0x00007fff4762fb45 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1718
	22  UIKitCore                           0x00007fff46b24566 -[UIViewControllerBuiltinTransitionViewAnimator animateTransition:] + 3698
	23  UIKitCore                           0x00007fff46b2c49e ___UIViewControllerTransitioningRunCustomTransition_block_invoke_2 + 54
	24  UIKitCore                           0x00007fff46c41ece +[UIInputResponderController _pinInputViewsForInputResponderController:onBehalfOfResponder:duringBlock:] + 99
	25  UIKitCore                           0x00007fff46b2c432 ___UIViewControllerTransitioningRunCustomTransition_block_invoke.645 + 180
	26  UIKitCore                           0x00007fff47628751 +[UIView(Animation) _setAlongsideAnimations:toRunByEndOfBlock:] + 175
	27  UIKitCore                           0x00007fff46b2c2b8 _UIViewControllerTransitioningRunCustomTransition + 553
	28  UIKitCore                           0x00007fff46a0fccb __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.452 + 2632
	29  UIKitCore                           0x00007fff46a1548f +[UIPresentationController _scheduleTransition:] + 79
	30  UIKitCore                           0x00007fff46a0f01b -[UIPresentationController runTransitionForCurrentState] + 1692
	31  UIKitCore                           0x00007fff46a0c64e -[UIPresentationController _presentWithAnimationController:interactionController:target:didEndSelector:] + 1060
	32  UIKitCore                           0x00007fff47199c46 -[UIWindow addRootViewControllerViewIfPossible] + 391
	33  UIKitCore                           0x00007fff4719ae22 -[UIWindow setRootViewController:] + 631
	34  myApp                            0x000000010540b601 __51-[RNNCommandsHandler setRoot:commandId:completion:]_block_invoke + 65
	35  myApp                            0x0000000105454bdd __62-[UIViewController(LayoutProtocol) renderTreeAndWait:perform:]_block_invoke_2.52 + 29
	36  libdispatch.dylib                   0x00000001078c7df0 _dispatch_call_block_and_release + 12
	37  libdispatch.dylib                   0x00000001078c8d64 _dispatch_client_callout + 8
	38  libdispatch.dylib                   0x00000001078d6e1c _dispatch_main_queue_callback_4CF + 1500
	39  CoreFoundation                      0x00007fff23afb699 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	40  CoreFoundation                      0x00007fff23af62f9 __CFRunLoopRun + 2329
	41  CoreFoundation                      0x00007fff23af56b6 CFRunLoopRunSpecific + 438
	42  GraphicsServices                    0x00007fff3815cbb0 GSEventRunModal + 65
	43  UIKitCore                           0x00007fff47162a67 UIApplicationMain + 1621
	44  myApp                            0x0000000104e0b9b0 main + 112
	45  libdyld.dylib                       0x00007fff5123bcf5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by cesarm16** [comment]
closing this. 

i was something with another native component.

**Comment by dcalhoun** [comment]
@cesarm16 would you be able to elaborate on what issue you identified? I'm experiencing similar errors. Any help, even if it is unrelated to RNN, would be appreciated. Thanks!

**Comment by cesarm16** [comment]
was an error with Zendesk SDK (chat) and iOS 13

**Comment by zabojad** [comment]
@dcalhoun did you find the cause of those errors at your end? I'm also having similar errors (UI API called on a background thread) since updating many librairies on my project (RN, RNN, Firebase, etc...).

**Comment by dcalhoun** [comment]
@zabojad similar to the OP, I discovered our issue originated from a different third-party library. Our app was not crashing, but was reporting "Main Thread Checker: UI API called on a background thread" warnings. It turned out to be a bug within [JWPlayer's SDK](https://developer.jwplayer.com/jwplayer/docs). Once JWPlayer published a patch, we upgraded and the warnings went away.

So, it's likely that one of the third-party packages you rely on includes a bug producing these warnings.

**Comment by zabojad** [comment]
@dcalhoun  How did you find out that JWPlayer SDK was the cause from the stack trace you had? I do not see any relation to third party libs in my stack trace (by the way, here is my stacktrace: https://github.com/wix/react-native-navigation/issues/5648)

**Comment by dcalhoun** [comment]
@zabojad I believe it was identified because we had an additional, non-React Native project using the JWPlayer SDK that began experiencing the same warnings.

So, my recommendation would be to upgraded each third-party library one at a time and hopefully you are able to identify the upgrade that triggers the warning. Alternatively, you could one-by-one remove third-party packages until the warnings stop.
