### ISSUE TITLE
[V3] Android hide bottom tabs

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#5521]
Blank space at bottom when hide bottom tabs
use with options: bottomTabs: {
        visible: false,
        animate: false,
        translucent: true,
        drawBehind: true
    }
The bottom tab is hidden but there's a blank space (equal to tab bar height) at the bottom
---
### Environment
* React Native Navigation version: 3.2.0-snapshot.512
* React Native version: 0.61.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Devices

**Comment by ParshantArora** [comment]
Same here can anyone find any solution Please let me know

**Comment by ParshantArora** [comment]
Working perfectly by using the below code 
 options: {
              bottomTabs: {
                animate: false,
                elevation: 8,
                currentTabIndex: 2,
                titleDisplayMode: "alwaysShow",
                backgroundColor: "#537591",
                visible: false,
                animate: false,
                drawBehind: true
              },
              topBar: {
                visible: false
              }
            }


in   "react-native-navigation": "3.2.0",

**Comment by AhmedRedaDev** [comment]
@ParshantArora 
this solution not working with me
Environment
    React Native Navigation version:(  3.2.0 , 3.2.0-snapshot.512 ,  3.2.0-snapshot.524 )
    React Native version: 0.61.1

**Comment by Quadriphobs1** [comment]
@AhmedRedaDev 

You can use setDefaultOptoin to not show the tab initially
```
Navigation.setDefaultOptions({
    topBar: {
      drawBehind: true,
    },
    bottomTabs: {
      visible: false,
      drawBehind: true,
    },
  });
```

**Comment by ParshantArora** [comment]
Yes use the above code and create your own custom tabs

**Comment by eduardopelitti** [comment]
I'm having the same issue.

I temporarily solved it by setting the default option of BottomTabs to `visible: false`, and then setting the `drawBehind` and `visible` property to `true` on the screens where I actually need the tabs to be displayed. 

Note, apparently components where you don't want the bottomTabs should have `drawBehind: true` to acknowledge it, as well.

Working example:

```
Navigation.setDefaultOptions({
    bottomTabs: {
      visible: false,
    },
```

And on each Screen where I DONT want the whitespace:
```
MyScreen.options = {
  bottomTabs: {
    drawBehind: true,
  },
}

```
_note: function component_

And where I DO want it:
```
MyOtherScreen.options = {
  bottomTabs: {
    visible: true,
    drawBehind: true,
  },
}
```

This seems rather hacky though...I'd expect that individual screen settings would override default options, and that drawBehind shouldn't be necessary to avoid the white space.

**Comment by ivan3177** [comment]
Same here. Setting visible to false and playing with other options for bottom tabs didn't help and still blank space

**Comment by nenjamin2405** [comment]
Anyone have a solution for this, I want to create my own custom tabs by display it absolute in every screen, but the bottom: 0 not make it at the bottom of the screen because of the Wix bottom tabs is still there.
