### ISSUE TITLE
Back swipe bottom tabs incorrect behavior

### ISSUE THREAD

**Issue by voroncv** [wix/react-native-navigation#5522]
### Issue Description

When going to the screen with options:
```
options: {
  bottomTabs: {
    visible: false,
  }
},
```
My screen looks like:
![bug](https://user-images.githubusercontent.com/20584352/65683482-fcda6280-e065-11e9-9e5a-2e6f49fab712.gif)

How can I make the transition to the screen without bottomTabs so it looks like this?
![IMAGE 2019-09-26 14:06:06](https://user-images.githubusercontent.com/20584352/65683770-cd782580-e066-11e9-9f5b-e3ba3c12260d.jpg)

---
### Environment
* React Native Navigation version: 2.27.7
* React Native version: 0.61.0
* Platform(s) (iOS, Android, or both?): both

**Comment by weiningtry7** [comment]
the same problem
