### ISSUE TITLE
[V3] Android Custom TopBar Right Buttons Not Working Consistently

### ISSUE THREAD

**Issue by gpsugy** [wix/react-native-navigation#5524]
### Issue Description

This is my first github issue post, so please excuse any poor quality aspects of it (feedback to improve is welcome).

I am not sure what is exactly causing this problem, but on Android, when using a custom component for the `rightButtons` field for a `topBar` (whether in a stack for `bottomTabs` or a `Navigation.push` screen), the button image renders, but is **sometimes not clickable**. The problem seems to occur non-deterministically, and trying various attempts to find patterns has been unsuccessful so far.

My project only started experiencing this issue upon upgrading from RN v59 to RN v60 and RNN v2 to RNN v3. This issue does not seem to apply with regular `rightButtons` with the `navigationButtonPressed` listener.

**At the very least, is anyone experiencing similar issues?** Any workaround solutions are welcome.

### Steps to Reproduce / Code Snippets / Screenshots

```js
// navigation.ts

rightButtons: [
  {
    id: 'customRightBtnId',
    component: {
      name: 'CustomTopBarBtn',
      passProps: {
        iconSrc: require('../assets/icons/custom-btn.png'),
      },
    },
  },
],
```

```js
// CustomTopBarBtn.tsx

const CustomTopBarBtn: React.SFC<Props> = (props) => {
  const { iconSrc } = props;

  return (
    <TouchableOpacity onPress={() => console.log('pressed btn')}>
      <View style={styles.container}>
        <Image source={iconSrc} resizeMode="contain" />
      </View>
    </TouchableOpacity>
  );
};

const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    flexDirection: 'column'
    height: '100%',
    width: '100%',
    marginRight: 5,
    marginLeft: 5,
  },
});
```

---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All Android Devices

**Comment by gpsugy** [comment]
Add whitespaces to JS code snippet

**Comment by gpsugy** [comment]
Discovered some helpful information that may narrow down the cause.

Here is the style for the original post's code:

```js
const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    flexDirection: 'column', // problematic
    height: '100%',
    width: '100%',
    marginRight: 5, // problematic
    marginLeft: 5, // problematic
  },
});
```

For some reason, **when removing `flexDirection` and margins from the `<View>` container, the buttons become pressable.** The margins can be switched out with `paddingRight` and `paddingLeft`, but only if set to a value of `<5` for some reason. This causes the buttons to be pressable in the bottomTabs stack, but not when pushing a screen using `Navigation.push`, though. Which again, seems inconsistent.

**Comment by gpsugy** [comment]
I have discovered that the cause of this issue is two-fold, and both pertain to a custom `title` component:

1. Using a custom title component with `flex: 1` results in the title overlapping _on top_ of the right buttons in the top bar. This is most evident when more than one right button is present, and typically results in the left-most right buttons becoming unpressable since the title component renders transparently on-top of them. I would think that `flex: 1` would take up only space up until the right buttons, but it does not.

2. Although setting a width of the custom title component so that it does not overlap the right buttons, the issue still occurs non-deterministically. Replacing the custom component with the regular static properties for the `title` options, however, removes all of these issues. This leads me to believe that further implementation needs to be done on the custom title component working well with the right buttons of the top bar.

**Comment by ianwelsh** [comment]
I'm seeing this as well. It happens using regular icon buttons as well as custom components for me. I have been unable to find a workaround but removing `flex: 1` seemed to help, like you said. You can see the issue in Android Studio's Layout Inspector.

This is when the search button is pressable, notice the TitleBarReactView (blue border) sits beside the search button view:
<img width="1895" alt="working" src="https://user-images.githubusercontent.com/8646670/66052659-f8e39000-e4fe-11e9-86fb-bd6a79af01e8.png">

This is when the search button is not pressable, notice the TitleBarReactView (blue border) sits overtop of the search button view:
<img width="2211" alt="broken" src="https://user-images.githubusercontent.com/8646670/66052736-14e73180-e4ff-11e9-88c9-bde8fa835df5.png">

**Comment by ianwelsh** [comment]
So far I'm only seeing this in debug builds, production builds don't seem to have the issue.

**Comment by MakhouT** [comment]
Maybe related to the issue I've opened?
https://github.com/wix/react-native-navigation/issues/5497

**Comment by MakhouT** [comment]
I would love to take a look at this, but my android skills are practically non-existent. Best to leave this to someone who knows what they are doing :D

**Comment by ianwelsh** [comment]
Here is Layout Inspector after the fix, you can see that the TitleBarReactView is now only as wide as the image. 

<img width="2558" alt="Screen Shot 2019-10-17 at 10 26 34 AM" src="https://user-images.githubusercontent.com/8646670/67018250-f53c3580-f0c8-11e9-8dc3-79ef94a3d7a7.png">

**Comment by ianwelsh** [comment]
@MakhouT No worries, I have basically no Android skills either. If you do want to give the fix a try, you can simply change line 19 of `<YOUR_RN_PROJECT_ROOT>/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/views/titlebar/TitleBarReactView.java` to:
```
                (getChildCount() > 0 && getChildAt(0).getWidth() > 0) ? MeasureSpec.makeMeasureSpec(getChildAt(0).getWidth(), MeasureSpec.UNSPECIFIED) : widthMeasureSpec,
```
It's a one word change.

**Comment by MakhouT** [comment]
Just tried it out, and it is still not working with the suggested changes.

**Comment by ianwelsh** [comment]
Can this be re-opened? This is still an issue.

**Comment by netshedzo** [comment]
i removed the **flex: 1** at it worked for me , i had this issue also using custom component on topbar

**Comment by arashkevich25** [comment]
any updates? I had remove flex but its doesnt help me.

**Comment by alex-phillips** [comment]
Can this be reopened? This PR (although closed due to 'stale') fixes the issue: https://github.com/wix/react-native-navigation/pull/5594

**Comment by alex-phillips** [comment]
@guyca Please see above, this was an issue in v4 and is still an issue in v6.

**Comment by samparmenter** [comment]
Still not fixed...
