### ISSUE TITLE
Dismiss keyboard on default Navigation Pop

### ISSUE THREAD

**Issue by nidhinkumar06** [wix/react-native-navigation#5525]
### Issue Description

How to dismiss the keyboard in default navigation pop.I am using the default pop not using any custom id for top bar back button. I would like to know how to close the keyboard in default pop

### Environment
* React Native Navigation version: 2.21.1
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by cesarm16** [comment]
call Keyboard.dismiss() on componentWillUnmount or componentDidDissapear (https://wix.github.io/react-native-navigation/#/docs/events?id=componentdiddisappear)

**Comment by nidhinkumar06** [comment]
@cesarm16 tried but still the same issue

**Comment by MakhouT** [comment]
@nidhinkumar06 Were you able to fix it?

**Comment by hwatanabe9393** [comment]
soembody fixed it?

**Comment by arryanggaputra** [comment]
Any help?

**Comment by Rishabh02** [comment]
The issue still exists, I am navigating from My search view to details screen and Keyboard is not dismissing

**Comment by VivekkChudasama** [comment]
Any help?

**Comment by jinshin1013** [comment]
Have you guys tried on the latest version? I cannot reproduce the issue on the Playground app.

**Comment by VivekkChudasama** [comment]
Yes, I'm using the latest version.
Please check the below screenshots.


![image](https://user-images.githubusercontent.com/24473813/100576402-17603980-3304-11eb-9989-bb3eb6ea6622.png)

**Comment by jinshin1013** [comment]
@VivekkChudasama You are on a wrong repo 🤓 This is `react-native-navigation`.
