### ISSUE TITLE
[Showcase] - Building Facebook messenger app UI using React Native and Wix

### ISSUE THREAD

**Issue by flutterforsale** [wix/react-native-navigation#5529]
### Issue Description

Building Facebook messenger app UI using React Native and Wix in 30 Mins 

Demo + source:
https://github.com/flutterforsale/rn-messenger-ui

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by ItsNoHax** [comment]
Hi @flutterforsale ,

If you want your app to be showcased in the showcase section, please provide a valid pull request.
Issues are used for bugs and problems.

Thanks,
Alberto
