### ISSUE TITLE
Custom top bar title alignment: center broken on android

### ISSUE THREAD

**Issue by bdrobinson** [wix/react-native-navigation#5531]
### Issue Description

According to <https://wix.github.io/react-native-navigation/#/docs/layout-types?id=custom-topbar-title> I should be able to set `topBar.title.component.alignment` to `center` and my custom title component will be centred. I'm finding that it works as expected on iOS, but on Android it always acts as if I'd set it to `fill`.

It always used to work for us, but stopped working when I upgraded from v2.13.1 to v3.2.0 (running RN 0.61.1). I also found this similar-looking issue – could they be related? https://github.com/wix/react-native-navigation/issues/5236

### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.61.1
* Platform(s) (iOS, Android, or both?): Both (iOS works as expected, Android has the bug)
* Device info (Simulator/Device? OS version? Debug/Release?): Both the android emulator and real devices exhibit the issue.

Thanks!

**Comment by loga4** [comment]
plus one

**Comment by vovka-s** [comment]
for me too

**Comment by bdrobinson** [comment]
Feel like this must still be broken if there's not been any activity on this issue.

**Comment by guibas741** [comment]
still facing this problem

**Comment by robert-adryan** [comment]
I faced this issue as well on Android where I can't press the right button because of the 'fill' alignment, and as a small workaround I added a width to the custom topBar component

<View style={{width: Dimensions.get("window").width - 120}}>
{/* title */}
</View>

**Comment by samparmenter** [comment]
Yeah, this is causing me all sorts of problems with the title not being centred when theres either a right or left button. Works fine with a text title but not a custom component.

**Comment by mwahlig** [comment]
I was able to workaround this by using `alignSelf` styling when configuring my custom topBar title component:
```javascript
passProps: {
  style: {
    alignSelf: 'center',
  },
},
```

**Comment by alexandrughinea** [comment]
Still facing this issue.

**Comment by kabus202** [comment]
@guyca can we reopen this? still exist in in 7.16.0
