### ISSUE TITLE
Reuse screen with different props consecutively

### ISSUE THREAD

**Issue by SreevatsaAcharya** [wix/react-native-navigation#5532]
### Issue Description

I want to edit and save nested forms which have the same UI screen.

eg: I open a form aka FormScreen from a home screen, now I want to open another form screen with different data points/props to edit its data. Now if i do Navigation.pop(this.props.componentID) the app crashes. Also if I press back button it crashes without an error log.

Does the library support opening the same screen(same id) consecutively with different props?

objective example: the way Reddit app uses the same screen for consecutive r/page_name but is able to navigate back. 
---
### Environment
* React Native Navigation version: 2.18.2
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): ios simulator

**Comment by blueberry6401** [comment]
If I understand your question right, the answer is using passProps
https://wix.github.io/react-native-navigation/#/docs/screen-api

**Comment by SreevatsaAcharya** [comment]
@blueberry6401 I want to use the same screen with different content in succession.
The back functionality crashes the app when i do this. I feel it cannot pop to a screen that has already been called?

**Comment by dopey2** [comment]
@SreevatsaAcharya you can use the same screen with differents content as long as they have different ID 

eg:

` const layout1 =   {
  component: {
    name: 'MY_SCREEN',
    id: "MY_SCREEN_1"
  }}
  Navigation.push(this.props.componentId, layout1);
`

`const layout2 =   {
  component: {
    name: 'MY_SCREEN',
    id: "MY_SCREEN_2"
  }}
  Navigation.push(this.props.componentId, layout2);
`
