### ISSUE TITLE
[v3][Android] When using mergeOptions on bottomTabs, it loses it's background color

### ISSUE THREAD

**Issue by svenlombaert** [wix/react-native-navigation#5533]
### Issue Description

I have an app which uses bottom tabs and a sidemenu. Form the sideMenu I call:
```
Navigation.mergeOptions('bottom-tabs', bottomTabs: {
      currentTabIndex: 1, // another index than the one that's active
      visible: true,
      drawBehind: false,
    }})
```

The active tab changes, but the bottom tabs loses it's background color which was set with default options, the tab has a different selected color, ...

### Steps to Reproduce / Code Snippets / Screenshots

I wanted to create a reproducable example but am unable to run the example from this repository (this used to work before, not anymore..). I could not compile because of the jsc version, I then switched it, but then the app crashes on start-up without any error.

---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.60
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Real Device, Samsung Galaxy S7, Pixel 1

**Comment by ryzhak** [comment]
@svenlombaert did you manage to solve it somehow? I'm getting the same behavior:
```
Navigation.mergeOptions('BottomNav', {bottomTabs: {backgroundColor: 'blue'}});
```
renders bottom tabs with white background

```
React Native Navigation version: 3.1.2
React Native version: 0.60.5
Platform(s) (iOS, Android, or both?): Android
Device info (Simulator/Device? OS version? Debug/Release?): Real Device
```

**Comment by svenlombaert** [comment]
@ryzhak Well, in my usecase, it only happened when the new index was the same one as the current one. So I've just put an if around that block so it only executes when the new index is different from the current one. It's still a bug, just worked around it.

**Comment by pasihu** [comment]
I'm having the same problem. Trying to implement dark mode and after changing to dark theme the bottom tab background color goes back to white. The correct background color gets rendered after changing tabs.

**Comment by svenlombaert** [comment]
@pasihu have you tried the latest version, 3.7.0? For me, this seems to work on iOS. I use mergeOptions twice though, once with componentId 'bottom-tabs' (so for all screens), and once with the componentId of the current screen. On Android, the issue still persists.

**Comment by manuhook** [comment]
Same issue here on V3.
The problem is also on V2
https://github.com/wix/react-native-navigation/issues/5168

**Comment by pasihu** [comment]
@svenlombaert i just got around to testing 3.7.0 and the problem still persists. I was using 3.2.0 before. Android only. iOS works fine.
