### ISSUE TITLE
Bottomtabs tab line indicator

### ISSUE THREAD

**Issue by hawky93** [wix/react-native-navigation#5535]
### Issue Description

I am a bit new to this library and was wondering if there is a configuration for bottomTabs or bottomTab property to generate an output like so:

![Screen Shot 2019-10-01 at 3 18 57 PM](https://user-images.githubusercontent.com/9379960/65952237-34c71880-e45f-11e9-8915-b0df6473ba83.png)

without having to use a combination of icon and selectedIcon.

Thanks in advance

**Comment by Andarius** [comment]
Any update on this ?

**Comment by emilioheinz** [comment]
@guyca Something like the example bellow would be really helpful:

```js
options: {
      bottomTab: {
        activeTabIndicator: {
          visible: true || false, // Means that when that bottom tab is active the indicator will or not appear
          style: 'line' || 'dot' || 'somethingElse', // some default styles
          customStyle: { // Possibility to create a custom style to the indicator
            backgroundColor: 'red'
          },
          animated: true || false // Animated or not
        }
      }
    }
```

I don't know why this isn't implemented until now, as it is a default behavior in android.

**Comment by emilioheinz** [comment]
That is not stale

**Comment by Andarius** [comment]
up

**Comment by Andarius** [comment]
up

**Comment by Gutyn** [comment]
@Andarius I'm with you here, why on earth would a tab bar have no indicator? I think they had one some years ago, what happened to it?

**Comment by ahmedam55** [comment]
@Gutyn @Andarius,

I'm with you too :(
