### ISSUE TITLE
[iOS] defaultOptions not used for animations

### ISSUE THREAD

**Issue by Jazqa** [wix/react-native-navigation#5536]
### Issue Description

waitForRender works for .push, .showModal, .setStackRoot and .setRoot but not via default options

### Steps to Reproduce / Code Snippets / Screenshots

Have a screen that renders slowly (e.g a large ImageBackground)

Set waitForRender in default options
-> Navigation action happens instantly and screen is not rendered

Set waitForRender when calling the navigation action
-> Navigation action happens after the screen has been rendered

**Comment by pribeh** [comment]
Experiencing the same here on React Native Navigation 2.27.9 and RN 059. I've tried almost any combination possible, searched through this entire issue queue for some glimmer of hope. :) I'm going to dig a bit more still.

**Comment by mathieumg** [comment]
Not stale.

**Comment by dozoisch** [comment]
Not stale

**Comment by dozoisch** [comment]
Not stale

**Comment by dozoisch** [comment]
not stale

**Comment by guyca** [comment]
@dozoisch Which version of RNN are you using?

**Comment by guyca** [comment]
@yogevbd Wasn't this fixed in v5?

**Comment by bvelasquez** [comment]
This is not working for me. React native 0.61.5 and react-native-navigation 6.3.0. Here are my default options, maybe I have it wrong.

```
Navigation.setDefaultOptions({
    animations: {
      setRoot: {
        waitForRender: true,
        enabled: true,
        alpha: {
          from: 0,
          to: 1,
          duration: 400,
          startDelay: 100,
          interpolation: 'accelerate',
        },
      },
      push: {
        waitForRender: true,
        enabled: true,
        alpha: {
          from: 0,
          to: 1,
          duration: 2000,
          startDelay: 100,
          interpolation: 'accelerate',
        },
      },
    },
    layout: {
      orientation: ['portrait'],
    },
    topBar: {
      backButton: {
        // android
        color: colors.titleTextColor,
      },
      buttonColor: colors.titleTextColor, // iOS
      background: {
        color: colors.titleBarColor,
      },
      rightButtonColor: colors.titleTextColor,
      leftButtonColor: colors.titleTextColor,
      title: {
        color: colors.titleTextColor,
        fontFamily: fontFamily(),
        fontSize: 18,
      },
    },
    bottomTab: {
      iconColor: colors.tabIconColor,
      textColor: colors.tabIconColor,
      selectedIconColor: colors.bottomTabIconColor,
      selectedTextColor: colors.bottomTabIconColor,
      backgroundColor: 'white',
      fontFamily: fontFamily(),
      fontSize: 10,
    },
  });
```

**Comment by danilobuerger** [comment]
This has been fixed. Please upgrade your rnn version.
