### ISSUE TITLE
Icons are cut off on Android

### ISSUE THREAD

**Issue by knight-hub** [wix/react-native-navigation#5539]
### Issue Description

After updating React Native Navigation to version 3.2.0 and React Native to version 0.61.1 the icons in the BottomTabs are slightly cut off at the top. Also changing an icons size does not change the size it is displayed on screen.

### Steps to Reproduce / Code Snippets / Screenshots

![Screenshot_20191002_15520](https://user-images.githubusercontent.com/55200923/66063235-42ee6500-e543-11e9-8914-fbe406a66500.jpg)

Code:

```js
const createNavigationChildren = (componentName, options) => {
    return {
        stack: {
            children: [
                {
                    component: {
                        name: componentName,
                        options: options
                    }
                }
            ]
        }
    };
};


export function startLoggedInNavigation() {
    Icon.getImageSource('clipboard-list', 25, ctColor.neutral.darker, FA5Style.solid).then(source => {
        eventsIcon = source;
        const children = [
            createNavigationChildren('churchtoolsmobile.Services', {
                bottomTab: {
                    text: t('service.tabbarName'),
                    icon: eventsIcon
                },
                topBar: {
                    title: {
                        text: t('service.tabbarName')
                    }
                }
            })
        ];
        Navigation.setRoot({
            root: {
                bottomTabs: {
                    children: children
                }
            }
        });
    });
}
```
---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.61.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device and simulator

**Comment by ItsNoHax** [comment]
Hi @knight-hub ,

This is actually a problem in react-native-vector-icons.
You can see the issue I made here: https://github.com/oblador/react-native-vector-icons/issues/1054
