### ISSUE TITLE
[V2] bottomTabReselected

### ISSUE THREAD

**Issue by ADCrouch** [wix/react-native-navigation#5541]
### bottomTabReselected is missing on v2 

Hi, I just migrated from v1 to v2 and I noticed that there is no mention in the doc regarding bottomTabReselected.
Am I expected to use registerBottomTabSelectedListener inside componentDidAppear?
I guess it will indicate that the tab was reselected but then I'll also have to unsubscribe so it will work for other components.
this sounds to me like a workaround, is there a proper way to get it?

### I've read the doc and couldn't find any reference 

---
### Environment
* React Native Navigation version: 3.1.2
* React Native version: 0.59.1
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by vovka-s** [comment]
+1
