### ISSUE TITLE
[V3] Support onTabPress

### ISSUE THREAD

**Issue by pontusab** [wix/react-native-navigation#5545]
I can see the request has been up before to support a custom `onPress` https://github.com/wix/react-native-navigation/issues/5193 to a tab to trigger something like a modal (i.e Instagram add post behavior).

Is this something that will be supported or planed?

**Comment by guyca** [comment]
Let's make this feature happen!

#### Spec
We'll introduce `bottomTab.selectTabOnPress` options which is true by default. If it's set to false, pressing a tab won't select the tab, instead it will emit a `bottomTabPressedEvent` (`BottomTabSelectedEvent` won't be emitted).

#### Options
```js
bottomTab: {
  selectTabOnPress?: boolean
}
```

#### Implementation
Listen to the press event globally
```js
Navigation.events().registerBottomTabPressedListener(({ tabIndex, componentId }) => {

});
```

**Comment by pontusab** [comment]
@guyca Awesome! Let me know if you need any help!

**Comment by pontusab** [comment]
Why not just use the current `registerBottomTabSelectedListener` event and disable the navigation when `selectTabOnPress` is true?

**Comment by olafurr** [comment]
Any word on this?

**Comment by N3TC4T** [comment]
@guyca 

I'm implemented this while ago, here is the patch file , works both in IOS and Android

https://gist.github.com/N3TC4T/9c06bc789529731bd54be689f210f20a

this patch is for v4.0.6 and this [pull request](https://github.com/wix/react-native-navigation/pull/5784) is included in the patch.

**Comment by N3TC4T** [comment]
> Let's make this feature happen!
> 
> #### Spec
> We'll introduce `bottomTab.selectTabOnPress` options which is true by default. If it's set to false, pressing a tab won't select the tab, instead it will emit a `bottomTabPressedEvent` (`BottomTabSelectedEvent` won't be emitted).
> 
> #### Options
> ```js
> bottomTab: {
>   selectTabOnPress?: boolean
> }
> ```
> 
> #### Implementation
> Listen to the press event globally
> 
> ```js
> Navigation.events().registerBottomTabPressedListener(({ tabIndex, componentId }) => {
> 
> });
> ```

@guyca 

I'm implemented this while ago, here is the patch file , works both in IOS and Android

https://gist.github.com/N3TC4T/9c06bc789529731bd54be689f210f20a

this patch is for v4.0.6 and this [pull request](https://github.com/wix/react-native-navigation/pull/5784) is included in the patch.

**Comment by eightyfive** [comment]
@N3TC4T Nice. What's the thinking behind not submitting a PR for this patch? Thanks!

**Comment by pontusab** [comment]
I made a PR from your code @N3TC4T https://github.com/wix/react-native-navigation/pull/5880
