### ISSUE TITLE
[V3] Bug: Splash screen shown when pushing on top of a modal with specific statusbar settings

### ISSUE THREAD

**Issue by LouiseBC** [wix/react-native-navigation#5548]
### Issue Description

Given a screen with a light statusBar, if a modal with a non-visible topbar and dark StatusBar is pushed on top, the app's splash screen is shown instead of the screen that was supposed to be pushed.

### Steps to Reproduce / Code Snippets / Screenshots
I reproduced the issue in the playground app, the changes can be found [here](https://gist.github.com/LouiseBC/e5bbf0acfc3742a3bec62c7f3538b247)
When running the app, tap on the navigation tab > modal > push. You should see the splash screen (grey screen). Now if you go back to the navigation tab, if you tap on modal again it should also show the splash screen.

---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.60.4
* Platform(s) (iOS, Android, or both?): Android only
* Device info (Simulator/Device? OS version? Debug/Release?): Occurs on simulator and physical device. So far seen on android 6 and 7

**Comment by nbolender** [comment]
Thank you for writing this up. I thought I was losing my mind.

**Comment by JB-CHAUVIN** [comment]
Same issue goes for me...

**Comment by LouiseBC** [comment]
Still relevant

**Comment by JB-CHAUVIN** [comment]
Yes, still relevant...

**Comment by nbolender** [comment]
@LouiseBC I just tried this using your test case and it seems to be fixed. Can you confirm?

I haven't tried on my own app yet.

**Comment by LouiseBC** [comment]
Same here! Seems fixed in version 4.0.5
