### ISSUE TITLE
[v2] bottomTabs - iOS dark mode 

### ISSUE THREAD

**Issue by hemith** [wix/react-native-navigation#5549]
### Issue Description

bottomTabs Appearance have changed when I turned on "Dark Mode" 

How to manage these Colors (bg, icon, text)?

How to disable this appearance change?

### Steps to Reproduce / Code Snippets / Screenshots

https://wix.github.io/react-native-navigation/#/docs/layout-types?id=bottomtabs

<img width="439" alt="settings_appearance" src="https://user-images.githubusercontent.com/10476866/66254527-5fdc9f80-e7b2-11e9-8e17-0cb3412d14b8.png">

- Device: Settings > Display & Brightness > Dark
- simulator: Settings > Developer > Appearance > Dark Appearance

![light_dark2](https://user-images.githubusercontent.com/10476866/66254529-63702680-e7b2-11e9-92e5-f86126d46ae4.png)

---
### Environment
* React Native Navigation version: 2.27.9
* React Native version: 0.61.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device. iOS 13. Debug

**Comment by markhomoki** [comment]
You can disable Dark Mode for your app if you add `User Interface Style`: `Light` to your plist.info. However, I'm not sure how you can check whether the device has dark mode enabled or not.

**Comment by hemith** [comment]
It works! Thank you very much!

**Comment by sallar** [comment]
@markhomoki I'm trying to migrate from `react-navigation` to this library because I like things to be native, but is fixing the dark mode support on your roadmap? I want my app to support dark mode. 
About the tab icons, does setting tint color help with this?
