### ISSUE TITLE
[V2][Android] waitForRender doesn't work for setStackRoot

### ISSUE THREAD

**Issue by sintylapse** [wix/react-native-navigation#5553]
### Issue Description
When I try to setStackRoot white screen will blink for a moment, because the screen has background image. So waitForRender doesn't work for setStackRoot for Android in V2. It seems it was fixed in V3 for Android here https://github.com/wix/react-native-navigation/pull/5357 and in V2 for IOS here https://github.com/wix/react-native-navigation/pull/5141 . But we still don't have this fixed in V2 for Android

---
### Environment
* React Native Navigation version: 2.26.4
* React Native version: 0.59.10
* Platform: both

**Comment by AlphaJuliettOmega** [comment]
@sintylapse can you verify whether this is still an issue?

I had all white screens fixed in our app and now I have a white screen flash on Android with a .setStackRoot() call, while the iOs version of the exact same happening, has no white screen flash.
