### ISSUE TITLE
react native project issue

### ISSUE THREAD

**Issue by afgfsdag** [wix/react-native-navigation#5556]
### Issue Description
![](https://i.stack.imgur.com/48OmF.png)

### Steps to Reproduce / Code Snippets / Screenshots]
// index.js
import {Navigation} from 'react-native-navigation';
import {registerScreens} from './screens';
import {AppRegistry} from 'react-native';

registerScreens();
AppRegistry.registerComponent('Initializing', ()  => registerScreens);
Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      component: {
        name: 'Initializing'
      }
    },
  });
});

### Environment
* React Native Navigation version: ^2.27.9
* React Native version: 0.61.2
* Platform(s) (Android): 3.4
* Device info (android emulator and debug): Nexus_5x_API29_x86:5554

**Comment by jinshin1013** [comment]
> AppRegistry.registerComponent('Initializing', () => registerScreens);

You don't have to do this.

The RNN playground has a working example of how to register screens with RNN. You can follow that.
