### ISSUE TITLE
Can not set up react native navigation for React Native 0.61 android.

### ISSUE THREAD

**Issue by suupham2506** [wix/react-native-navigation#5557]
### Issue Description

[ENTER DESCRIPTION HERE]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by jinshin1013** [comment]
Would you care to share a little more detail regarding the problem?

**Comment by valery-kuzmenko** [comment]
@jinshin1013 I am having the same issue for RNN V2 and RN 0.61.1 
Error on android: **The module 'react-native-navigation' is an Android project without build variants, and cannot be built.**

`buildscript {
...
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.2.0'
    }
...
}`

distributionUrl=https\://services.gradle.org/distributions/gradle-5.5-all.zip

Could you please recommend a way to make it work for gradle 5 and RNN v2 (without upgrading to alpha V3 version) ?

**Comment by jinshin1013** [comment]
Is there a reason not to upgrade to the latest RNN@v3.2.0? It is no longer an alpha version.

**Comment by ItsNoHax** [comment]
Please use RNN V3+ for RN 0.60.0 and higher.

**Comment by Sbarcenas** [comment]
Please can you post RRN3+ Docs Link

**Comment by jinshin1013** [comment]
It's literally in the first page of the Github repo. [Doc link](https://wix.github.io/react-native-navigation/#/)
