### ISSUE TITLE
Does this work with the new react native or not?

### ISSUE THREAD

**Issue by christianlippa** [wix/react-native-navigation#5558]
### Issue Description

Is there a definitive solution for upgrading to 0.60/0.61? 

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 3.0
* React Native version: 0.61
* Platform(s) (iOS, Android, or both?): ANDROID
* Device info (Simulator/Device? OS version? Debug/Release?): cant get that far chief

**Comment by namihiepth** [comment]
It works.

**Comment by ItsNoHax** [comment]
Yes it sure does, RNN V3 was specifically made for the breaking changes that came with RN 0.60 regarding the Android support library.
