### ISSUE TITLE
Is it possible to provide an URL for bottomTab icon?

### ISSUE THREAD

**Issue by xapai** [wix/react-native-navigation#5559]
### Issue Description

I would like to provide a URL for an icon (e.g. user avatar after successful login), but only left with unchangeable icon option.

Is there any workarounds or tricks to place a dynamic image into this?

### Steps to Reproduce / Code Snippets / Screenshots

```js
bottomTab: {
                disableIconTint: true,
                icon: {
                    uri: 'https://pixel.nymag.com/imgs/daily/vulture/2019/10/02/02-matt-damon.w330.h330.jpg'
                }
            },
```

![image](https://user-images.githubusercontent.com/5209820/66463264-70786880-ea85-11e9-9e64-0137ba188bf8.png)

---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by ItsNoHax** [comment]
Right now this is not supported, I would suggest downloading the user's picture locally and then displaying the bottomTabs
