### ISSUE TITLE
Popup Menu on toolbar right side

### ISSUE THREAD

**Issue by ccir105** [wix/react-native-navigation#556]
### Issue Description

How can I use popup menu and searching in appbar ( Top Bar )  ? I didn't find any resources for this. 
If it is possible using this navigation, please help. 

(https://github.com/wix/react-native-navigation/issues/197)

---
### Environment
Android
I just cloned the latest version of react native and this awesome react-native-navigation

**Comment by guyca** [comment]
To add a popup menu to the TopBar, Add `showAsAction: never` to each button you'd like to add to the menu. See the docs for an [example](https://github.com/wix/react-native-navigation/wiki/Adding-buttons-to-the-navigator).
Someone already mentioned the name is a bit misleading, we'll probably rename the property in a future release to make the api more clear and understandable.

Regarding custom components in TopBar, right now there's no easy and straight forward way to do this. You could add your own ToolBar component and use it in the screens you require more advance functionality. We're planing on supporting this feature in the near future.

**Comment by flyskywhy** [comment]
https://github.com/sohobloo/react-native-modal-dropdown
