### ISSUE TITLE
[V3] Not working on Android 8

### ISSUE THREAD

**Issue by ShaneMatthias** [wix/react-native-navigation#5561]
### Issue Description
On any Android 8 device, app gets stuck on a white screen when trying to navigate **AFTER** a screen gets pushed onto the stack. If I don't push onto the stack, calling `setStackRoot` works fine. I have tested this on Android 9 and 10 and it works fine. I have down graded to v2.27.9 and it worked fine.

---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Android 8

**Comment by cinder92** [comment]
this issue is also happening to me, on devices under 8

**Comment by xuananpham93** [comment]
Any solutions?

**Comment by ShaneMatthias** [comment]
@xuananpham93 I downgraded to v2.27.9
 and it worked
