### ISSUE TITLE
[v3] Topbar large Title scrolled bug

### ISSUE THREAD

**Issue by djschilling** [wix/react-native-navigation#5565]
### Issue Description

When using the `largeTitle` Option and a `ScrollView` as the root element the large title is scrolled away.

### Steps to Reproduce / Code Snippets / Screenshots

```
class Profile extends Component {
    static options() {
        return {
            topBar: {
                largeTitle: {
                    visible: true
                }
            }
        };
    }
    render() {
        return (
            <ScrollView>
                <View>
                    <Text>huhu</Text>
                </View>
            </ScrollView>
        );
    }
}
```

This is how it renders when i click the first time on the navbar item which belongs to this component:
![Bildschirmfoto 2019-10-10 um 16 54 36](https://user-images.githubusercontent.com/3503166/66580533-d7c61380-eb7e-11e9-8fd0-5f11532a781e.png)

When i scroll the view from top to bottom the largeTitle appears.

It should be visible when navigating to the component.
---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.61.2
* Platform(s) (iOS, Android, or both?): iOS

**Comment by nbolender** [comment]
+1

**Comment by ivan3177** [comment]
+1

**Comment by djschilling** [comment]
The issue still exists

**Comment by ayouidaniel** [comment]
+1

**Comment by alexxgent** [comment]
I am still seeing this issue even after upgrading to v4.0.4+ (which includes #5715). I will report back with a workaround if I find one.

**Comment by djschilling** [comment]
The issue is still there.

**Comment by djschilling** [comment]
still there

**Comment by artursvonda** [comment]
Not stale

**Comment by djschilling** [comment]
The issue is still there.

**Comment by kanzitelli** [comment]
If anyone is still facing this issue, try out [these workarounds](https://gist.github.com/kanzitelli/76609c98dd39bea75f5451f286c412f2).

**Comment by remstos** [comment]
For what it's worth. This issue disappeared by removing waitForRender: true that was in my default options

```
Navigation.setDefaultOptions({
    ...,
    animations: {
        push: {
            // waitForRender: true, remove this line
        },
    },
});
```
