### ISSUE TITLE
[V3 or V2] iOS stuck on black screen on launch

### ISSUE THREAD

**Issue by ShaneMatthias** [wix/react-native-navigation#5566]
### Issue Description
When I try to run my app on an iOS device, it loads up but only shows a black screen. I managed to resolve this issue by modifying the code in `RNNSplashScreen.m` `line: 74`:

**From:**
```
if (viewController != nil) {
    id<UIApplicationDelegate> appDelegate = [UIApplication sharedApplication].delegate;
    appDelegate.window.rootViewController = viewController;
    [appDelegate.window makeKeyAndVisible];
}
```

**To:**
```
if (viewController != nil) {
    viewController = [[RNNSplashScreen alloc] init];
}

id<UIApplicationDelegate> appDelegate = [UIApplication sharedApplication].delegate;
appDelegate.window.rootViewController = viewController;
[appDelegate.window makeKeyAndVisible];
```

I was wondering if anyone has encountered this issue? Or is it a problem on my end? If not, I can submit a PR for this.

---
### Environment
* React Native Navigation version: any v2 or v3
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device

**Comment by acollazomayer** [comment]
I encounter the same probelm

**Comment by RyanCommits** [comment]
Getting this error when using your fix:
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'`

**Comment by ShaneMatthias** [comment]
@RyanCommits Try:

```
        viewController = [[RNNSplashScreen alloc] init];
        viewController.view = [[UIImageView alloc] initWithImage:image];
    }

    id<UIApplicationDelegate> appDelegate = [UIApplication sharedApplication].delegate;
    appDelegate.window.rootViewController = viewController;
    [appDelegate.window makeKeyAndVisible];
}
```
Where the `viewController` initialization is in the `else` statement above.

**Comment by rhayart** [comment]
> @RyanCommits Try:
> 
> ```
>         viewController = [[RNNSplashScreen alloc] init];
>         viewController.view = [[UIImageView alloc] initWithImage:image];
>     }
> 
>     id<UIApplicationDelegate> appDelegate = [UIApplication sharedApplication].delegate;
>     appDelegate.window.rootViewController = viewController;
>     [appDelegate.window makeKeyAndVisible];
> }
> ```
> 
> Where the `viewController` initialization is in the `else` statement above.

Same issue here, and this fix it. @ShaneMatthias, could you submit a PR for this ?
It's seem we are not as much having this issue, it's weird.

**Comment by RyanCommits** [comment]
> @RyanCommits Try:
> 
> ```
>         viewController = [[RNNSplashScreen alloc] init];
>         viewController.view = [[UIImageView alloc] initWithImage:image];
>     }
> 
>     id<UIApplicationDelegate> appDelegate = [UIApplication sharedApplication].delegate;
>     appDelegate.window.rootViewController = viewController;
>     [appDelegate.window makeKeyAndVisible];
> }
> ```
> 
> Where the `viewController` initialization is in the `else` statement above.

I resolved my issue. The problem was that the **Launch Screen File** property, under General > App Icons and Launch Images, was empty. Apparently this causes RNN to not have a "Root View" on app launch and caused a black screen for me.

**Comment by rhayart** [comment]
> > @RyanCommits Try:
> > ```
> >         viewController = [[RNNSplashScreen alloc] init];
> >         viewController.view = [[UIImageView alloc] initWithImage:image];
> >     }
> > 
> >     id<UIApplicationDelegate> appDelegate = [UIApplication sharedApplication].delegate;
> >     appDelegate.window.rootViewController = viewController;
> >     [appDelegate.window makeKeyAndVisible];
> > }
> > ```
> > 
> > 
> > Where the `viewController` initialization is in the `else` statement above.
> 
> I resolved my issue. The problem was that the **Launch Screen File** property, under General > App Icons and Launch Images, was empty. Apparently this causes RNN to not have a "Root View" on app launch and caused a black screen for me.

I just tried it and it does the trick thank you.

**Comment by ShaneMatthias** [comment]
For some reason, I stopped receiving notifications for this issue. @RyanCommits I can't seem to find where to locate this path and how to fix it. Could you explain? Thanks

**Comment by tyson90** [comment]
I had same issue. And I solved it by killing the LLDB process and run app again (even without rebuilding).
