### ISSUE TITLE
[V3] [Android] change statusBar style will make Navigation cannot push

### ISSUE THREAD

**Issue by tientruongvan1995** [wix/react-native-navigation#5567]
### Issue Description

[V3] [Android] change statusBar style will make Navigation cannot push

### Steps to Reproduce / Code Snippets / Screenshots
As title, I setDefaultOption statusBar style to 'light' and when I push to new screen by below code, it navigates to new screen once and also change statusBar style, but then I try to push new screen again but nothing changes
```js
Navigation.setDefaultOptions({
    animations: Platform.select({ ios: {}, android: animations }),
    popGesture: false,
    statusBar: {
      backgroundColor: 'transparent',
      drawBehind: true,
      visible: true,
      style: 'light'
    },
// ...
}
```
statusBar style is `'light'`
then `push()`
```js
Navigation.push(componentId, {
  component: {
    name,
    passProps,
    options: {
      statusBar: {
        drawBehind: true,
        visible: true,
        style: 'dark'
      },
    },
  },
});
```
statusBar style is `'dark'`, then `pop()`, statusBar style turn to `'light'` again
and `push()` one more time and nothing changed, I cannot use `push()` function anymore

---
### Environment
* React Native Navigation version: 3.2.0-snapshot.524
* React Native version: 0.65.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): LG V10/Debug

**Comment by LiuPierr** [comment]
I also reproduce this issue when I switch between a style 'light' and 'dark' only on Android.

**Comment by cspicuzza** [comment]
I've encountered this issue with RNN 4.8.4.

Changing the the statusBar style property stops RNN from pushing more views.   I'm able to replicate in the sim using the following Android Studio VM config:

- Nexus 5
- Oreo, Api Level 27, Target Android 8.1 (google play)

**Comment by cspicuzza** [comment]
@LiuPierr I managed to fix this by setting the statusBar style with `Navigation.setDefaultOptions`.  After that I was able to change status bar styles without RNN breaking.
