### ISSUE TITLE
[V3] Invariant Violation: "AppName" has not been registered

### ISSUE THREAD

**Issue by oviedo97fer** [wix/react-native-navigation#5568]
### Issue Description

That issue's like #5520, the problem? That issue just resolving problem with [V3]RNN install in iOS. 
My problem is with Android 9 

App.js look great:
```
import {Navigation} from 'react-native-navigation';
import App from './App';

Navigation.registerComponent('main.AppScreen', () => App);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      component: {
        name: 'main.AppScreen',
      },
    },
  });
});
```
---
### Environment
* React Native Navigation version: 3.2.0
* React Native version:0.61.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Pixel 3a API 28 
 Android 9

**Comment by iscosta** [comment]
I had the same problem and it worked only when I installed version "react-native-navigation": "3.0.0-alpha.11"

**Comment by autm-syl** [comment]
look at the file app.json and package.json and check same name field both files, maybe them difference.

**Comment by t3hfx** [comment]
You've missed the installation parts with AppDelegate.m file

**Comment by zabojad** [comment]
@oviedo97fer I have the same issue on Android and RNN 3.3.0 (and all v3 versions apparently). I'm running with RN 0.61.3.

Did you find a solution?

**Comment by oviedo97fer** [comment]
> @oviedo97fer I have the same issue on Android and RNN 3.3.0 (and all v3 versions apparently). I'm running with RN 0.61.3.
> 
> Did you find a solution?

yes
but my error was that the documentation did not clarify that all of the following should be copied:
![image](https://user-images.githubusercontent.com/37948156/67898194-9e117880-fb3e-11e9-8150-909fa9ce5192.png)
Not only:
![image](https://user-images.githubusercontent.com/37948156/67898228-ae295800-fb3e-11e9-8f31-ec79ef1ba77e.png)

**Comment by oviedo97fer** [comment]
> You've missed the installation parts with AppDelegate.m file

**Comment by traxx10** [comment]
I had this issue, in my own case i was doing everything in AppDelegate.m file but there was a bridging code so i had to remove it.

Comment out this line of code 

`//  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
//  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
//                                                   moduleName:@"raajneti"
//                                            initialProperties:nil];

//  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
//
//  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
//  UIViewController *rootViewController = [UIViewController new];
//  rootViewController.view = rootView;
//  self.window.rootViewController = rootViewController;
//  [self.window makeKeyAndVisible];`

**Comment by haabnaseem** [comment]
For ios it works fine, i also face the same issue in android.
