### ISSUE TITLE
[v3] installation guide 0.60

### ISSUE THREAD

**Issue by rendomnet** [wix/react-native-navigation#5572]
### Issue Description

Can we have installation guide for RNN v3+ and RN 0.60.
Is RNN support autolinking if so then why in this doc we linking it manualy https://wix.github.io/react-native-navigation/#/docs/Installing?

**Comment by syedabuthahirm** [comment]
@rendomnet I think by default linking doesn't change `MyActivity.java` and `MainActivity.java`. In order to use React Native Navigation We have to modified those files.

**Comment by syedabuthahirm** [comment]
Check this repo [repo](https://github.com/syedabuthahirm/react-native-navigation-install-guide) for fresh installation.

**Comment by AndreiCalazans** [comment]
The way we are setting up android breaks auto-linking. 

Specially the logic around the getPackages. 

https://github.com/syedabuthahirm/react-native-navigation-install-guide/blob/master/android/app/src/main/java/com/rnninstallguide/MainApplication.java

https://github.com/facebook/react-native/blob/master/template/android/app/src/main/java/com/helloworld/MainApplication.java#L24

**Comment by syedabuthahirm** [comment]
@AndreiCalazans Do you have any other native modules in your project?

**Comment by AndreiCalazans** [comment]
I have a few like react-native-maps, react-native-reanimated, react-native-firebase. 

[error.txt](https://github.com/wix/react-native-navigation/files/3721704/error.txt)
<img width="341" alt="Screen Shot 2019-10-13 at 09 02 42" src="https://user-images.githubusercontent.com/20777666/66715310-5a75eb00-ed98-11e9-8f97-5e1222a69621.png">


To fix this error I have to manually link my native modules inside the MainApplication file.

**Comment by AndreiCalazans** [comment]
Note, it looks like automatic linking works half way since I don't need to add the dependencies inside build.gradle

**Comment by rendomnet** [comment]
what version of RNN should we use now? 3.2.0?

**Comment by syedabuthahirm** [comment]
If you like to use RN 0.60 and higher versions use V3. i will try to update that repo as soon as possible when RNN & RN release new updates.

**Comment by Gerlison** [comment]
> I have a few like react-native-maps, react-native-reanimated, react-native-firebase.
> 
> [error.txt](https://github.com/wix/react-native-navigation/files/3721704/error.txt)
> <img alt="Screen Shot 2019-10-13 at 09 02 42" width="341" src="https://user-images.githubusercontent.com/20777666/66715310-5a75eb00-ed98-11e9-8f97-5e1222a69621.png">
> 
> To fix this error I have to manually link my native modules inside the MainApplication file.
> 
> ```
> 
> return Arrays.<ReactPackage>asList(
>     // eg. new VectorIconsPackage()
>       new ReactNativeFirebaseAppPackage(),
>       new ReactNativeFirebaseFirestorePackage(),
>       new MapsPackage()
> 
>     );
> ```

I have the same problem, noticed that when was trying to install firebase crashlytics, solved just linking manually too. RNN should fix the autolinking problem as soon as possible.

**Comment by syedabuthahirm** [comment]
@Gerlison @AndreiCalazans It's normal thing when you use react native navigation. you have to normally link every native module.

**Comment by rendomnet** [comment]
@syedabuthahirm RNN v3 breaks RN0.60+ autolinking? Its breaks main feature of RN0.60+?

**Comment by syedabuthahirm** [comment]
In old versions of react-native we have `react-native link` command. but that one is also sometimes break the application. whenever i tried to link with the above command i got issues with them after run that command.

**Comment by jinshin1013** [comment]
Add this in your `MainApplication.java to enable React Native's autolinking feature

```java
import com.facebook.react.PackageList;

@Nullable
@Override
public List<ReactPackage> createAdditionalReactPackages() {
  @SuppressWarnings("UnnecessaryLocalVariable")
  List<ReactPackage> packages = new PackageList(this).getPackages();
  return packages;
}
```

**Comment by SparkleFaerieCoder** [comment]
As @jinshin1013 points out, autolinking stores packages within PackageList class, which you must import if you're upgrading to 0.60. Current RNN documentation does not mention this. Took me days to figure out this was the root of many of my problems. 

Before 0.60:
```java
protected List<ReactPackage> getPackages() {
   // No need to add RnnPackage and MainReactPackage
   return Arrays.<ReactPackage>asList(
     // eg. new RNPackage()
   );
 }

@Override
public List<ReactPackage> createAdditionalReactPackages() {
        return getPackages();
}
```
After 0.60:
```java    
@Nullable
@Override
public List<ReactPackage> createAdditionalReactPackages() {
   List<ReactPackage> packages = new PackageList(this).getPackages();
    // Packages that might not support autolinking can still go here
    // packages.add(new RNPackage());
    return packages;
 }
```

**Comment by ivan3177** [comment]
Couldn't set up RNN with auto-linking(RN 0.61, RNN 3.0.0). However could make it work with manual linking for RNN. 

However there are so many bugs in 3.x.x so updating to RN 0.60+ is blocked by them

**Comment by Gerlison** [comment]
> Couldn't set up RNN with auto-linking(RN 0.61, RNN 3.0.0). However could make it work with manual linking for RNN.
> 
> However there are so many bugs in 3.x.x so updating to RN 0.60+ is blocked by them

What bugs you're refering to?
I have a inital setup on RN 0.61.2 that works fine for while. But I would like to know the issues that can jump to my face
