### ISSUE TITLE
[V3][Android] There is a problem when i use setStackRoot command on Android with multiple stack

### ISSUE THREAD

**Issue by dmitryusikriseapps** [wix/react-native-navigation#5576]
### Issue Description

Hi Guys, i've implemented your library for the project with 100+ screens and the performance has become better, but there are a few issues.
When i  use setStackRoot command on Android with an array of layouts as the second argument how it works: the first screen is in the stack and the second one is opened correct. But when i use the pop command, the first screen renders from scratch. It doesn't happen on iOS, the first screen from the stack is already rendered.

### Steps to Reproduce / Code Snippets / Screenshots

Here is the code:
https://pastebin.com/KGqLh5xq
https://pastebin.com/2rcHfZvh
https://pastebin.com/TGEVycS8
https://pastebin.com/a55w90Ev
https://pastebin.com/T4Fcj3ZU
https://pastebin.com/gsyMhvfB

### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.61.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone XS Max, iPhone 7+ (12-13 OS version), Release and Debug builds

**Comment by dmitryusikriseapps** [comment]
@labria @benhiller @kelyar @grin Guys do you have any updates?

**Comment by labria** [comment]
@dmitryusikriseapps can you elaborate why you mentioned me here?
