### ISSUE TITLE
[V3][iOS] Screens created with SafeAreaView sometimes jump

### ISSUE THREAD

**Issue by dmitryusikriseapps** [wix/react-native-navigation#5577]
### Issue Description

Hi Guys, i've implemented your library for the project with 100+ screens and the performance has become better, but there are a few issues.
The screens created with the SafeAreaView on iOS sometimes jump at the beginning of the opening animation.

### Steps to Reproduce / Code Snippets / Screenshots

Here is the code:
https://pastebin.com/KGqLh5xq
https://pastebin.com/2rcHfZvh
https://pastebin.com/TGEVycS8
https://pastebin.com/a55w90Ev
https://pastebin.com/iSUzmJUx
https://pastebin.com/gsyMhvfB

### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.61.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone XS Max, iPhone 7+ (12-13 OS version), Release and Debug builds

**Comment by drewhamlett** [comment]
Have you tried `forceInset` on SafeAreaView?

**Comment by EJohnF** [comment]
`forceInset` is for react-navigation SafeAreaView implementation, not the one from react-native

@dmitryusikriseapps you open it quite some time ago, did you find a solution? 

I also experience the same issue :(

**Comment by Frekansapp** [comment]
I also have same issue

**Comment by kabus202** [comment]
maby its related to this one https://github.com/wix/react-native-navigation/issues/3418

**Comment by maciejBudzinskiNG** [comment]
I'm facing the same issue. I tried to use `waitForRender: true` while pushing the screen but it didn't help at all. 
@kabus202 I belive that linked issue may be something different.

react-native-navigation@3.4.0
react-native@0.61.4

**Comment by anurbecirovic** [comment]
I have the same problem.. Not sure why it's happening. Only on iOS :/
