### ISSUE TITLE
[V3][Android] If the hardware back button is pressed immediately after the push command is used there will be an empty screen without any UI

### ISSUE THREAD

**Issue by dmitryusikriseapps** [wix/react-native-navigation#5578]
### Issue Description

If the hardware back button is pressed on Android immediately after the push command is used there will be an empty screen without any UI.

### Steps to Reproduce / Code Snippets / Screenshots

Here is the code:
https://pastebin.com/KGqLh5xq
https://pastebin.com/2rcHfZvh
https://pastebin.com/TGEVycS8
https://pastebin.com/a55w90Ev
https://pastebin.com/iSUzmJUx
https://pastebin.com/gsyMhvfB

### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.61.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone XS Max, iPhone 7+ (12-* 13 OS version), Release and Debug builds

**Comment by ivan3177** [comment]
+1
Same here

**Comment by dopey2** [comment]
Same issue

**Comment by sintylapse** [comment]
The same bug happens in V2
