### ISSUE TITLE
Touches do not pass through overlay on iOS

### ISSUE THREAD

**Issue by tomhicks** [wix/react-native-navigation#5579]
### Issue Description

I have a notification component that drops down from the top, rather like the native iOS notifications. Whilst they are rendered (i.e. until dismissOverlay is called) the entire rest of the screen cannot be interacted with.

### Steps to Reproduce / Code Snippets / Screenshots

  Navigation.showOverlay({
    component: {
      name: "notification",
      passProps: props,
      options: {
        overlay: {
          interceptTouchOutside: false,
        },
      },
    },
  })

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: 0.61.2
* React Native version: 3.2.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All devices

**Comment by tomhicks** [comment]
I've managed to track down the issue here. It's actually not to do with RNN, so apologies for creating the issue. Other people might come across this though, so it's worth noting the problem.

It's actually caused by using `react-native-safe-area-context` along with RNN, when wrapping registered components with the `SafeAreaContext`.

Essentially, this causes it to break:
```
Navigation.registerComponent(
  name,
  () => (props: any) => (
    <ApolloProvider client={apolloClient}>
      <SafeAreaProvider>
        <ReduxProvider store={store}>
          <Screen {...props} />
        </ReduxProvider>
      </SafeAreaProvider>
    </ApolloProvider>
  ),
  () => Screen,
)
```

Whereas this works (you just can't use `SafeAreaContext`:
```
Navigation.registerComponent(
  name,
  () => (props: any) => (
    <ApolloProvider client={apolloClient}>
      <ReduxProvider store={store}>
        <Screen {...props} />
      </ReduxProvider>
    </ApolloProvider>
  ),
  () => Screen,
)
```

The issue is that the hit testing that happens in React Native never reaches the root view, so the passthrough never happens.

**Comment by Pczek** [comment]
How did you debug this. I have the same issue but I'm just wrapping my views with the Provider from redux so it should work, if it works for you. 🤔

**Comment by tomhicks** [comment]
I set breakpoints in the hit test code in RN. If I recall correctly I was looking at things that checked the view being hit against self.rootView or something like that.

I’m away from keyboard at the moment hence the sketchy reply

**Comment by Pczek** [comment]
This still drives me nuts.
I wasn't able to figure out what causes this in my app. I stripped everything down to the bare react-native bones, still doesn't work as expected. 

As of now I ended up removing all logic from the overlay handlers. For anyone interested:

`RNNOverlayWindow.m`
```swift
- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
	return nil;
}
```

`OverlayTouchDelegate.java`
```java
public boolean onInterceptTouchEvent(MotionEvent event) {
    return handleDown(event);
}
```

**Comment by Pczek** [comment]
Been there done that. Even the most minimal working example with the code of mine did not work. I've added the prop everywhere. I settled with the react-native alert API for now.
Has anyone used the react-native `Modal` API with RNN?
https://facebook.github.io/react-native/docs/0.60/modal
