### ISSUE TITLE
iOS - Wrong view size when topBar is hidden

### ISSUE THREAD

**Issue by rhydiant** [wix/react-native-navigation#5582]
### Issue Description

On iOS, when hiding the `topBar` the view size doesn't account for this and renders the screen with white space at the bottom.

### Steps to Reproduce

**Step 1** - create a stack navigation inside `Navigation.events().registerAppLaunchedListener(()` as per the docs. Add config to hide the top navigation bar, e.g.

```
Navigation.setRoot({
    root: {
      stack: {
        options: {
          topBar: {
            visible: false,
            height: 0
          }
        },
        children: [
          {
            component: {
              name: 'myComponent',
              options: {
                backgroundImage
              }
            }
          }
        ]
      }
    }
  });
```

**Step 2** - run the app and observe the background image you use does not fill the screen. There is white space at the bottom.

![Screen Shot 2019-10-15 at 9 31 57 am](https://user-images.githubusercontent.com/90287/66787519-bde65100-ef2f-11e9-98f2-974713caf6b5.png)

The above screenshot is taken from XCode's UI debugger. Note the child `UIImageView` of `RNNRootViewController` height is `64` points too short (the same height as the hidden navigation bar).

---
### Environment
* React Native Navigation version: `2.27.9`
* React Native version: `0.59.9`
* Platform(s): iOS only
* Device info: Device and Simulator, iOS 13.0 (and others)

**Comment by ashokkumar88** [comment]
@rhydiant did you find any solution? I'm facing same issue
