### ISSUE TITLE
iOS 13 critical issues

### ISSUE THREAD

**Issue by exentrich** [wix/react-native-navigation#5585]
### Issue Description
Apps build with Xcode 11 now forces new behavior introduced in iOS 13:
- Swipe down to dismiss for modals
- Increased height of topBar for modals
- Dark mode

Unfortunately RNN do not support any of this changes properly. And it's deal-breaker for all developers. Now we can't deploy latest update for our apps, due to several issues (sorted by severity):
1. When modal is dismissed with swipe, screen is not unmounted properly and memory not released. This makes memory leaks. `componentDidUnmount` not works https://github.com/wix/react-native-navigation/issues/5370
2. Swipe back doesn't work
3. TopBar Title misaligned in modals https://github.com/wix/react-native-navigation/issues/5564 https://github.com/wix/react-native-navigation/issues/5431
4. When dark mode is on, status bar become transparent (nothing is visible, white text on white background)

This issues easily reproducible in Playground app.

I made this ticket to gather all problems we have in iOS 13, because the main reason for all of the problems is latest iOS update. So I think we could close all other separate tickets and keep discussion here.

Here pull-requests that possibly fix part of the problems:
https://github.com/wix/react-native-navigation/pull/5512 https://github.com/wix/react-native-navigation/pull/5534

### Environment
* React Native Navigation version: 2.27.9, 3.2.0
* React Native version: 0.61.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Any

**Comment by santiripper** [comment]
Regarding the dark mode, you can disable it by adding this into the app info plist

```xml
<key>UIUserInterfaceStyle</key>
<string>Light</string>
```

**Comment by JB-CHAUVIN** [comment]
When will you fix this ?

**Comment by guyca** [comment]
Hey guys, this will be addressed very soon. Hopefully in the next two weeks.

**Comment by JB-CHAUVIN** [comment]
In our apps, the header doesn't have any titles and the back button doesn't appear... Is this related to this issue ? (on iOS 13 only)

**Comment by blueberry6401** [comment]
> In our apps, the header doesn't have any titles and the back button doesn't appear... Is this related to this issue ? (on iOS 13 only)

No, I have back and the title showing, iOS 13, xcode 11.

**Comment by OmgDef** [comment]
For me, swipe back works fine on a real device, but not an emulator. But enabling device bezels solves an issue.

**Comment by guyca** [comment]
Closing as all issues brought up here have been addressed. If there are more issues, please open a separate issue and we'll address them. Thanks all 👍
