### ISSUE TITLE
v3 react-native auto linking broken only on Android

### ISSUE THREAD

**Issue by safaiyeh** [wix/react-native-navigation#5588]
### Issue Description

Hello! I am using react-native-navigation v3. Android auto-linked Native modules no longer work.

### Steps to Reproduce / Code Snippets / Screenshots
1. Set up v3 react-native-navigation
2. Add a native module like Async Storage
3. Android application throws errors about the native module.

This is true for react-native-async-storage, react-native-cookies, react-native-device-info

---
### Environment
* React Native Navigation version: ^3.2.0
* React Native version: 0.61.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator, Pixel XL API 29

**Comment by JongtaekChoi** [comment]
Does your Application.java file include following line?
```
new PackageList(this).getPackages() 
```

**Comment by heroic** [comment]
Yeah. I was having the same error. Recheck your MainApplication.java. @JongtaekChoi 's changes will help.

**Comment by safaiyeh** [comment]
Awesome thank you @JongtaekChoi  and @heroic.

For future reference:
```java
@Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return new PackageList(this).getPackages() ;
    }
```

Fixes auto linking in v3.
