### ISSUE TITLE
Sidemenu in showmodal

### ISSUE THREAD

**Issue by Floavinci** [wix/react-native-navigation#5592]
### Issue Description

Is it possible to open a fullscreen sidemenu in a modal ?
its possible to open a sidemenu in a modal, but overFullscreen options is not working.

This is a problem since iOS13.
"react-native-navigation": "^2.26.0"

![Screenshot 2019-10-17 at 10 34 15](https://user-images.githubusercontent.com/4542567/66992301-de4a1300-f0c9-11e9-9904-6311e689e5dd.png)

### Steps to Reproduce / Code Snippets / Screenshots
`export async function pushTicket(sideMenuProps, componentProps) {
  await Navigation.showModal({
    sideMenu: {
      id: SCREENS.TICKET,
      right: {
        component: {
          name: SCREENS.DRAWERS.CHAT_DRAWER,
          passProps: sideMenuProps,
          options: {
            animations: {
              showModal: {
                waitForRender: true,
              },
            },
          },
        },
      },
      center: {
        stack: {
          children: [
            {
              component: {
                name: SCREENS.TICKET,
                passProps: componentProps,
              },
            },
          ],
          options: {
            animations: {
              showModal: {
                waitForRender: true,
              },
            },
          },
        },
      },
    },
  });
}  
`

**Comment by Yhspehy** [comment]
Can u help me how to dismissModal of sideMenu ? When i use dismissModal in sideMenu, the current screen get black. But it's ok if i use dismissAllModals.
