### ISSUE TITLE
[v3] Custom right button added using mergeOptions crashes in iOS

### ISSUE THREAD

**Issue by peresbri** [wix/react-native-navigation#5595]
### Issue Description

I want to dynamically add a custom right icon to the top bar. As per the documentation, I used `mergeOptions`. Android works well. But the app crashes on iOS.

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.mergeOptions(componentId, {
          topBar: {
            rightButtons: [
              {
                component: {
                  name: "TopBarButton",
                  passProps: {
                    label: "test",
                    iconImage: iconUrl(TEST_URL),
                    onPress: () => {
                      console.log("Custom tap button clicked");
                    }
                  }
                },
                id: "CustomTopBarButton",
                enabled: true,
              }
            ]
          }
        });
```

---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 11, iPhone X, (12 - 13)

**Comment by NISUSIN** [comment]
Same here, even without custom component, it crash
