### ISSUE TITLE
How can push back to parent screen and passprops?

### ISSUE THREAD

**Issue by peterlau0010** [wix/react-native-navigation#5597]
How can I push back to parent screen with parameters?

`Navigation.pop(this.props.componentId) `
can only close the current screen, but not passing values.

```
    Navigation.push(this.props.componentId, {
      component: {
        name: 'ParentView',
        passProps: {
          data: 'values',
        }
      },
    });
```
can pass values, but create a new ParentView...

Is that any way I can pass back value to parentView, and close current view? Thanks.

### Environment
* React Native Navigation version: 2.27.9
* React Native version: 0.61.2
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 11 pro, 13.1

**Comment by peresbri** [comment]
Props should be immutable. 
That said, in instances where you need to pass some data to previous screens, a ui store which act a bit as a controller is usually a good way to go. Where you use redux or MobX or ..., having a UI store should apply changes instantly to your mounted screen.

**Comment by peterlau0010** [comment]
Thanks @peresbri and @NISUSIN , it work for me!!!
