### ISSUE TITLE
Android run error

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#56]
Please help me :(

How add RnnPackage

![screen shot 2016-06-06 at 9 08 36 pm](https://cloud.githubusercontent.com/assets/19372005/15824841/5cfde184-2c2b-11e6-9b7f-6136c41af642.png)
![screen shot 2016-06-06 at 9 11 05 pm](https://cloud.githubusercontent.com/assets/19372005/15824842/5d0351f0-2c2b-11e6-861a-5661e4a4a462.png)
![screen shot 2016-06-06 at 9 11 28 pm](https://cloud.githubusercontent.com/assets/19372005/15824843/5dfa9f28-2c2b-11e6-91f3-cde737e619c0.png)
![screen shot 2016-06-06 at 9 11 38 pm](https://cloud.githubusercontent.com/assets/19372005/15824844/5e0025c4-2c2b-11e6-88c2-8198d0511334.png)

**Comment by SimchaShats** [comment]
You need to add import: 
import com.reactnativenavigation.packages.RnnPackage;

**Comment by agumack** [comment]
thanks @SimchaShats 
I have add import com.reactnativenavigation.packages.RnnPackage;

run no bug but not start app,

message when run on android: 

`Application has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent....`

**Comment by explorigin** [comment]
Read this comment and the following: https://github.com/wix/react-native-navigation/issues/5#issuecomment-217704276

**Comment by agumack** [comment]
I tried #5 but not working. 
:(
`Application has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent....`

**Comment by guyca** [comment]
@agumack Have you managed to get it working?

**Comment by agumack** [comment]
Hi @guyca,

my apps setup ok for ios, android not working. i don't know why

**Comment by guyca** [comment]
Can you please copy paste here you `MainActivity.java` file?

**Comment by agumack** [comment]
@guyca this is my MainActivity.java file

```
package com.appplus;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.microsoft.codepush.react.CodePush;
import com.oblador.vectoricons.VectorIconsPackage;
import com.reactnativenavigation.packages.RnnPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {
    @Override
    protected String getJSBundleFile() {
        return CodePush.getBundleUrl();
    }

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "appPlus";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new RnnPackage(),
            new VectorIconsPackage(),
            new CodePush("bS8uy-nM1-Dfg8CGYAstKU65an2UV1BFJqUNW", this, BuildConfig.DEBUG)
        );
    }
}
```

**Comment by guyca** [comment]
Please change it to the following 

```java
import com.reactnativenavigation.activities.RootActivity;

public class MainActivity extends RootActivity {
    
    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new RnnPackage(),
            new VectorIconsPackage(),
            new CodePush(TOKEN, this, BuildConfig.DEBUG)
        );
    }
}
```

**Comment by agumack** [comment]
@guyca thanks for support.
I changed it and now this error:

![screen shot 2016-06-16 at 1 26 51 pm](https://cloud.githubusercontent.com/assets/19372005/16107380/39b8a608-33c6-11e6-8ab0-d1c23cd32500.png)

**Comment by guyca** [comment]
Edited code snippet. `getPackages` should be `public` instead of `protected`.

**Comment by agumack** [comment]
Thanks @guyca 
It BUILD SUCCESSFUL now, but not launch on Genymotion, error _**"Unfortunately, app has stopped**_" 

Am I missing a something?

Thanks.

**Comment by guyca** [comment]
With out stack trace I can't really help. Can you please send me crash log from adb? Exceptions + Warnings
Thanks

**Comment by agumack** [comment]
@guyca my apps run on android succeed! thank you so much for help.

I have a new question: navigatorStyle not apply.
Ex:  navigationBarColor,.. 
'Search' title not show, it showing is my app name
```
Navigation.startSingleScreenApp({
  screen: {
    screen: 'app.SearchScreen', // unique ID registered with Navigation.registerScreen
    title: 'Search', // title of the screen as appears in the nav bar (optional)
    navigatorStyle: {
      navigationBarColor: '#000000',
      toolBarColor: '#000000',
      navBarTextColor: '#ffffff',
      navBarButtonColor: '#ffffff',
      statusBarTextColorScheme: 'light',
      navBarHideOnScroll: false,
      navBarHidden: true
    }, // override the navigator style for the screen, see "Styling the navigator" below (optional)
    navigatorButtons: {} // override the nav buttons for the screen, see "Adding buttons to the navigator" below (optional)
  }
});

```

**Comment by guyca** [comment]
@agumack Glad to hear it's working. Can you please open a separate issue for the navigatorStyle issues? Thanks.
