### ISSUE TITLE
V3: BottomTab's visibility doesn't work

### ISSUE THREAD

**Issue by opiruyan** [wix/react-native-navigation#5605]
### Issue Description

hiding bottom tab doesn't work.
on **iOS** it just remains on the bottom on the screen.
on Android results in a black space on the bottom of the screen

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.setDefaultOptions({
            bottomTabs: {
                visible: false,
            }
        });
```

---
### Environment
* React Native Navigation version: 3.2.0, 3.1.1, 3.1.2
* React Native version: 0.61.2
* Platform(s) (iOS, Android, or both?): iOS and Android
* Device info (Simulator/Device? OS version? Debug/Release?): simulator and device. iOS 12.4.2. Android 9

**Comment by khorark** [comment]
> ### Issue Description
> hiding bottom tab doesn't work.
> on **iOS** it just remains on the bottom on the screen.
> on Android results in a black space on the bottom of the screen
> 
> ### Steps to Reproduce / Code Snippets / Screenshots
> ```js
> Navigation.setDefaultOptions({
>             bottomTabs: {
>                 visible: false,
>             }
>         });
> ```
> 
> ### Environment
> * React Native Navigation version: 3.2.0, 3.1.1, 3.1.2
> * React Native version: 0.61.2
> * Platform(s) (iOS, Android, or both?): iOS and Android
> * Device info (Simulator/Device? OS version? Debug/Release?): simulator and device. iOS 12.4.2. Android 9

` bottomTabs: {
                        visible: false,
                        animate: false,
                        drawBehind: true,
                    },`

You used this options?

**Comment by opiruyan** [comment]
@khorark 
Of course.

Apparently, on iOS part
```
- (void)rnn_setTabBarVisible:(BOOL)visible animated:(BOOL)animated
```
is called with
```
visible = YES
```
though it is **false** on a js-side.

So setting
```
visible = NO
```
inside ite method hides tabs, but leaves the space, which is somewhat similar to Android.

**Comment by khorark** [comment]
@opiruyan I'm also hidden bottom tabs and this work for android and ios. Version RNN 3.2.0

**Comment by opiruyan** [comment]
@khorark well, the story that It used to work on v2.
And the issue appeared just after upgrading RN version to and RNN. No changes to the code were made whatsoever.

**Comment by edferreira** [comment]
Same is happening here. It worked fine on V2

**Comment by edferreira** [comment]
When I set `bottomTabs: { visible: false, animate: false, drawBehind: true, }` at defaultOptions it's not working, but doing with the Navigation.push works as expected.
Thanks @khorark

**Comment by davidmarinangeli** [comment]
> When I set `bottomTabs: { visible: false, animate: false, drawBehind: true, }` at defaultOptions it's not working, but doing with the Navigation.push works as expected.
> Thanks @khorark

I can confirm that using `push` gives me the correct behavior. Unfortunately, I need `defaultOptions` to work too.

**Comment by ArjunRajesh** [comment]
For customizing android bottom bar, as i have curved borders in the design, I am trying to hide bottomTabs and create a custom one.
But as i am making visible:false,drawBehind:true; finding a white space in android, is there any hack for removing white space or alternatives on how i can customize bottom Tabs.

**Comment by diegoprates** [comment]
@ArjunRajesh I had the same problem, solved it by creating a custom one with `Navigation.showOverlay`  and then you can set the height based on `const { bottomTabsHeight } = await Navigation.constants()`

**Comment by davidmarinangeli** [comment]
Any update on this? @diegoprates your workaround does not work on my app, unfortunately

**Comment by samparmenter** [comment]
This is still an issue!

**Comment by guyca** [comment]
Hey guys, this is fixed in [v5](https://github.com/wix/react-native-navigation/issues/5904). Sorry for the inconvenience.

**Comment by 92sajid110** [comment]
> Hey guys, this is fixed in [v5](https://github.com/wix/react-native-navigation/issues/5904). Sorry for the inconvenience.

hello this is not working on version 7.15.0
