### ISSUE TITLE
Cannot convert value of type 'Swift.Bool' to specified type 'ReactNativeNavigation.Bool'

### ISSUE THREAD

**Issue by szalaybalazs** [wix/react-native-navigation#5608]
### Issue Description
We just wanted to update our react-native version to 60+, but xcode gives the above error when building.

### Steps to Reproduce / Code Snippets / Screenshots
Create a new RN project, follow the install steps.

---
### Environment
* React Native Navigation version: 2.27.9
* React Native version: 0.61.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by ksiwei** [comment]
RNN redefines 'Bool' and 'Dictionary' in obj-c. I managed to get around the error by adding this to my AppDelegate:
```
typealias Bool = Swift.Bool 
typealias Dictionary = Swift.Dictionary
```

**Comment by szalaybalazs** [comment]
@ksiwei worked like a charm, thanks a lot!

It would be nice though not to have to use these kind of brute-force fixes... 😕
