### ISSUE TITLE
Top bar left button is too big

### ISSUE THREAD

**Issue by meraklis56** [wix/react-native-navigation#5616]
### Issue Description

In the release apk of the application, the top bar left icon is always bigger that it should whereas the right icon as in the correct size. This bug is **only** on release.apk, not in debug.apk

![Screenshot_20191030-105944_Meme Studio Pro](https://user-images.githubusercontent.com/10517197/67849398-d1381580-fb06-11e9-9a6e-617f3234907d.jpg)

Both buttons have the exact same icon as source.

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
Navigation.push(this.props.componentId, {
            component: {
                name: constants.CANVAS_SIZE_SCREEN.id,
                passProps: {
                },
                options: {
                    topBar: {
                        height: Dimensions.get('window').height * palette.MAIN_TOP_BAR_HEIGHT,
                        visible: true,
                        title: {
                            text: constants.CANVAS_SIZE_SCREEN.name,
                            alignment: 'center',
                            color: 'white',
                            waitForRender: true,
                        },
                        borderHeight: 1.3,
                        elevation: 1.5, // TopBar elevation in dp,
                        background: {
                            color: palette.SECONDARY_DARK
                        },
                        leftButtons: [
                            {
                                id: 'BackButton',
                                icon: require('../assets/btn_succeed.png')
                            }
                        ],
                        rightButtons: [
                            {
                                id: 'ProceedButton',
                                icon: require('../assets/btn_succeed.png')
                            }
                        ]
                    },
                    sideMenu: {
                        left: {
                            visible: false,
                            enabled: false
                        }
                    }
                }
            }
        });
``` 
---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): Android (haven't tested iOS)
* Device info (Simulator/Device? OS version? Debug/Release?):S7 Edge, Android 8, Release only

**Comment by vietnt-uet** [comment]
I do have the same issue like @meraklis56. Icon is good when debug but get too big on release build.

**Comment by mucha-git** [comment]
I have a similar issue but with right button. In my case the height is good but width is stretched almost double. In RNN v2 it works good but in v3 and v4 not. I've tested it on ios 13 on simulator and on real iPhone Xs. React-native 0.61.5.

**Comment by kurnal** [comment]
@stalebot this is still an issue

**Comment by koiralakiran1** [comment]
I'm facing this issue as well, for release build.

React native version: 0.63.2
RNN version: 7.0.0

![image](https://user-images.githubusercontent.com/11130898/94645533-c8018b00-030b-11eb-9d7c-98f7337dd8c1.png)

**Comment by guyca** [comment]
@koiralakiran1 Make sure you icon contains all [required resolutions ](https://reactnative.dev/docs/images#static-image-resources) (@2, @3 etc)

**Comment by koiralakiran1** [comment]
Just saw seconds ago that this works fine on the release build of playgroud app.

> @koiralakiran1 Make sure you icon contains all [required resolutions ](https://reactnative.dev/docs/images#static-image-resources) (@2, @3 etc)

This fixed the issue for me. Thanks @guyca
