### ISSUE TITLE
[V3][Android] FATAL EXCEPTION: create_react_context

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#5617]
### Issue Description

I'm migrating an existing application from RN 0.59.9 and RNN 2.26.5 to RN 0.61.3 and RNN 3.3.0. I'm doing it from a fresh `npx react-native init` project.

For now, I'm only working with Android.

When launching the app with `npx react-native run-android`, the app installs correctly on the device but it instantly crashes with:

```
2019-10-30 21:35:21.135 17097-17143/? E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: my.app, PID: 17097
    java.lang.RuntimeException: Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:227)
        at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:28)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:261)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1175)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)```
```

So... what is the problem?

### Steps to Reproduce / Code Snippets / Screenshots

You should be able to reproduce the same issue with setting up a new RNN project with RN 0.61.3 and RNN 3.3.0.

You can use the basic app from the documentation.

```js
import { Navigation } from "react-native-navigation";
import App from "./App";

Navigation.registerComponent(`navigation.playground.WelcomeScreen`, () => App);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      component: {
        name: "navigation.playground.WelcomeScreen"
      }
    }
  });
});
```

Run `npx react-native run-android` and you should get the crash when the app starts///

---
### Environment
* React Native Navigation version: 3.3.0
* React Native version: 0.61.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): device, debug mode, Android 9

**Comment by zabojad** [comment]
OK, I've tried each RNN version down to 3.0.0 and the bug is still happening. So... I might have missed some RNN v3 setup step or... It's not working with latest RN 0.61.3 ?

Anybody help me?

**Comment by zabojad** [comment]
and... it seems that downgrading to RNN 2.27.10 is not helping much:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-navigation.
     Required by:
         project :app
      > Unable to find a matching variant of project :react-native-navigation:
          - Variant 'reactNative57_5DebugApiElements' capability MyApp:react-native-navigation:unspecified:
              - Incompatible attributes:
                  - Required RNN.reactNativeVersion 'reactNative60' and found incompatible value 'reactNative57_5'.
```

**Comment by zabojad** [comment]
Did anyone succeeded in running RNN with RN 0.61.3?

**Comment by zabojad** [comment]
I do not understand this issue. I'm having it on a fresh and empty project. Anyone help?

**Comment by zabojad** [comment]
OK, after a good night of sleep, I've found why I was having this issue.

In the `MainApplication.java`, I had this:

```java
import com.facebook.react.BuildConfig;
```

For a reason I don't yet understand, this was compiling correctly but was also provoking this issue.

Gosh! It was painful. If anyone could explain to me the error I was having, I would be very glad.

**Comment by danielwinkler** [comment]
@zabojad How did you find out that this was causing the problem?

**Comment by zabojad** [comment]
@danielwinkler I did setup my entire project from scratch several times and finally ended up comparing my RNN setup with the one from some example like this [one](https://github.com/alexn29/react-native-navigation-v3).

And eventually found ou that the only difference was this... Quite a painful debug...

**Comment by danielwinkler** [comment]
Thanks for letting me know.

I guess you saved me some precious hours going through the same troubles on
this stupid bug!

Thanks!

Thomas Fétiveau <notifications@github.com> schrieb am Di., 3. Dez. 2019,
13:41:

**Comment by dphaener** [comment]
@zabojad Thank you so much for this. I am eternally grateful.

**Comment by muganwas** [comment]
> OK, after a good night of sleep, I've found why I was having this issue.
> 
> In the `MainApplication.java`, I had this:
> 
> ```java
> import com.facebook.react.BuildConfig;
> ```
> 
> For a reason I don't yet understand, this was compiling correctly but was also provoking this issue.
> 
> Gosh! It was painful. If anyone could explain to me the error I was having, I would be very glad.

OMG you saved me!! can't thank you enough

**Comment by TakaKeiji** [comment]
> OK, after a good night of sleep, I've found why I was having this issue.
> 
> In the `MainApplication.java`, I had this:
> 
> ```java
> import com.facebook.react.BuildConfig;
> ```
> 
> For a reason I don't yet understand, this was compiling correctly but was also provoking this issue.
> 
> Gosh! It was painful. If anyone could explain to me the error I was having, I would be very glad.

You saved my ass thanks a lot... but i'm wondering by removing this import... do you know possible consequences?

**Comment by zabojad** [comment]
> but i'm wondering by removing this import... do you know possible consequences?

@TakaKeiji After months running without that import, I can safely say that I have not observed any bad consequence from it...

**Comment by RatFou** [comment]
@zabojad: many thanks!

**Comment by esynaps** [comment]
@zabojad: Thanks!

**Comment by edward-s** [comment]
OMG!! I spent 4 hours debugging this issue
@zabojad  THANK YOU!!!

**Comment by ngochai117** [comment]
> OK, after a good night of sleep, I've found why I was having this issue.
> 
> In the `MainApplication.java`, I had this:
> 
> ```java
> import com.facebook.react.BuildConfig;
> ```
> 
> For a reason I don't yet understand, this was compiling correctly but was also provoking this issue.
> 
> Gosh! It was painful. If anyone could explain to me the error I was having, I would be very glad.

OMG!! WORK PERFECT! I tried all way and spent 4h for this issue

**Comment by Zhennan-Xu** [comment]
Thanks for solving this bug. You are the real hero.

**Comment by knivesq** [comment]
> > but i'm wondering by removing this import... do you know possible consequences?
> 
> @TakaKeiji After months running without that import, I can safely say that I have not observed any bad consequence from it...

I was led to put it when I got some error with android studio regarding debug build, it was because I was trying to clone an existing app of my company with the same things but different names.

Thank you very much.

**Comment by 1Ajay** [comment]
[
![Screenshot from 2020-08-27 23-32-06](https://user-images.githubusercontent.com/29257275/91478492-98e79c00-e8bd-11ea-97d7-9ce0c5426c84.png)
](url)

in MainApplication.java added import com.facebook.react.BuildConfig; then also I am facing same issue :(

> OK, after a good night of sleep, I've found why I was having this issue.
> 
> In the `MainApplication.java`, I had this:
> 
> ```java
> import com.facebook.react.BuildConfig;
> ```
> 
> For a reason I don't yet understand, this was compiling correctly but was also provoking this issue.
> 
> Gosh! It was painful. If anyone could explain to me the error I was having, I would be very glad.

**Comment by zmfang** [comment]
> > OK, after a good night of sleep, I've found why I was having this issue.
> > In the `MainApplication.java`, I had this:
> > ```java
> > import com.facebook.react.BuildConfig;
> > ```
> > 
> > 
> > For a reason I don't yet understand, this was compiling correctly but was also provoking this issue.
> > Gosh! It was painful. If anyone could explain to me the error I was having, I would be very glad.
> 
> OMG!! WORK PERFECT! I tried all way and spent 4h for this issue

it saved me too

**Comment by uzaircs** [comment]
> OK, after a good night of sleep, I've found why I was having this issue.
> 
> In the `MainApplication.java`, I had this:
> 
> ```java
> import com.facebook.react.BuildConfig;
> ```
> 
> For a reason I don't yet understand, this was compiling correctly but was also provoking this issue.
> 
> Gosh! It was painful. If anyone could explain to me the error I was having, I would be very glad.

Saved me hours. Thanks.

Turns out I imported the wrong BuildConfig from Import Suggestions while adding a library

![image](https://user-images.githubusercontent.com/17011138/93355574-a9a18700-f857-11ea-8be8-843f73bcbd4e.png)

**Comment by arun0715** [comment]
> > OK, after a good night of sleep, I've found why I was having this issue.
> > In the `MainApplication.java`, I had this:
> > ```java
> > import com.facebook.react.BuildConfig;
> > ```
> > 
> > 
> > For a reason I don't yet understand, this was compiling correctly but was also provoking this issue.
> > Gosh! It was painful. If anyone could explain to me the error I was having, I would be very glad.
> 
> You saved my ass thanks a lot... but i'm wondering by removing this import... do you know possible consequences?

Yes , I had same problem and i removed  
**import com.facebook.react.BuildConfig;**  
and it worked for me

**Comment by LucasHimelfarb** [comment]
If that solution doesn't work, try this in /awesomeProject/android:   ./gradlew clean

**Comment by Rishijay** [comment]
Thankss alottt..!! Removing the same worked for me t0o... Genious.!! 💯

**Comment by iska9der** [comment]
> OK, after a good night of sleep, I've found why I was having this issue.
> 
> In the `MainApplication.java`, I had this:
> 
> ```java
> import com.facebook.react.BuildConfig;
> ```

Thaaanks, brudda. 3 FKNHOURS.

**Comment by nhatminh1601** [comment]
> OK, after a good night of sleep, I've found why I was having this issue.
> 
> In the `MainApplication.java`, I had this:
> 
> ```java
> import com.facebook.react.BuildConfig;
> ```
> 
> For a reason I don't yet understand, this was compiling correctly but was also provoking this issue.
> 
> Gosh! It was painful. If anyone could explain to me the error I was having, I would be very glad.

thanks guy.

**Comment by surajsahijwani** [comment]
This is a simple cache issue. Invalidate caches from android studio and rebuild project properly. This worked for me everytime I faced this issue

**Comment by RazaShehryar** [comment]
> OK, after a good night of sleep, I've found why I was having this issue.
> 
> In the `MainApplication.java`, I had this:
> 
> ```java
> import com.facebook.react.BuildConfig;
> ```
> 
> For a reason I don't yet understand, this was compiling correctly but was also provoking this issue.
> 
> Gosh! It was painful. If anyone could explain to me the error I was having, I would be very glad.

you are literally a life saver!

**Comment by a-koka** [comment]
The solution is the same for those of us using multidex. Just remove the following line:

```
import androidx.multidex.BuildConfig;
```

**Comment by kg-currenxie** [comment]
> Yes , I had same problem and i removed **import com.facebook.react.BuildConfig;** and it worked for me

somehow, _removing_ it worked for me :D
