### ISSUE TITLE
[v3] iOS 13 wrong keyWindow.backgroundColor

### ISSUE THREAD

**Issue by blueberry6401** [wix/react-native-navigation#5618]
### Issue Description
When open modal with modalPresentationStyle is pageSheet or formSheet, the background should be black instead of white.

### Steps to Reproduce / Code Snippets / Screenshots

Navigation.showModal(Screens.Modal, { modalPresentationStyle: 'formSheet' });

| What should be | RNN v3 |
| ------------- | ------------- |
| ![Screen Shot 2019-10-31 at 15 42 12](https://user-images.githubusercontent.com/7337535/67931719-0cb10d80-fbf5-11e9-9904-129583e89467.png) | ![ezgif-1-5fbf0bcbb04c](https://user-images.githubusercontent.com/7337535/67931358-39185a00-fbf4-11e9-9864-a3207f30c555.gif) |

---
### Environment
* React Native Navigation version: 3.3.0
* React Native version: 0.61.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone

**Comment by edvinasbartkus** [comment]
It would work well if we would remove `keyWindow.backgroundColor = white`. But there is also an issue that we need to change the status bar color to white when the modal is shown? Should this be managed by the app or this can be automated?

**Comment by pie6k** [comment]
in iOS, automatic changing of status bar color when opening modal is handled when setting `View controller-based status bar appearance` in `Info.plist` to `YES`.

This, however, disables the manual setting of StatusBar anywhere in the JS world and the only option is to manage it with `Options` of the screens.

I'm fine with that and I did it.

Which was

1. In my `AppDelegate.m` I've added

```obj-c
self.window.backgroundColor = [UIColor blackColor];

// it's just before return YES; of didFinishLaunchingWithOptions
```

and also
```xml
<key>UIViewControllerBasedStatusBarAppearance</key>
	<true/>
```

It resulted in a beautiful status bar color animation when opening modals.

**Comment by wbw20** [comment]
@pie6k Your approach works well, but I think there is another drawback.  If you are animating your bottom tabs to be visible/invisible then as they are disappearing in a transition the black background will be visible for a moment.

Your approach is great for people who don't need to do that, though.

**Comment by pie6k** [comment]
It's not resolved, and it's still important in my opinion

**Comment by guyca** [comment]
@yogevbd Isn't this resolved in 4.x.x?

**Comment by pie6k** [comment]
not stale

**Comment by guyca** [comment]
@pie6k Are you sure this isn't fixed? Have you checked latest version (6.1.0) ?

**Comment by Infigoforza** [comment]
Currently using the latest version (7.0.0) and experiencing this issue (white background instead of black). Worked on the previous version we used (6.9.1).

**Comment by simonarcher** [comment]
Also have this issue and I have no idea how to change the background colour behind the modal.
Right now its white and I can't get it to support 'dark mode'.

Is this ability to change the background possible, or not possible? 
If possible, does anyone know specifically know how to set it?

```
"@react-navigation/bottom-tabs": "^5.8.0"
"@react-navigation/compat": "^5.2.5"
"@react-navigation/native": "^5.7.3"
"@react-navigation/stack": "^5.9.0"```

**Comment by todorone** [comment]
@guyca We are trying to migrate from 6.x to the latest 7.x and it's the blocker for us.

On 6.x we have a black background, while on 7.x it's white.

**Comment by el-banna** [comment]
I am facing the same issue with version `7.26.0`. @pie6k workaround worked fine for the time being.
I would suggest to add the ability to change root's background color `window.backgroundColor` from JS.
