### ISSUE TITLE
StatusBar translucent support for Android?

### ISSUE THREAD

**Issue by messense** [wix/react-native-navigation#562]
Currently seems no `statusBarTranslucent` style could be set? Has to use `StatusBar` component to do that.

Would be great to be able to define it in `navigatorStyle` and/or `appStyle`.

---
### Environment
* React Native Navigation version: 2.0
* React Native version: 0.39
* Platform(s) (iOS, Android, or both?): Android

**Comment by guyca** [comment]
@messense Yes we definitely need to add native support for that so you wouldn't need to use the `StatusBar` component.

**Comment by kenma9123** [comment]
is there any news to this?

**Comment by jurajkrivda** [comment]
@kenma9123 Hi, you can use <StatusBar barStyle="light-content" backgroundColor="rgba(0, 0, 0, 0.60)" translucent />

**Comment by kenma9123** [comment]
@jurajkrivda that was actually the problem. `StatusBar` should not be use in order for it to work lol. But thanks for the suggestion :)

**Comment by guyca** [comment]
To achieve this in v2, use the following options

```js
statusBar: {
  backgroundColor: '#00000039',
  drawBehind: true
}
```
