### ISSUE TITLE
[V3] [Android] Top bar title is not centering, parent view now overlaps right buttons

### ISSUE THREAD

**Issue by kyledmellander** [wix/react-native-navigation#5626]
### Issue Description

We use a custom top bar title component. After updating to V3, passing 'center' in the styling no longer works, and the text aligns to the left. Additionally, the right buttons seem to be getting overlapped with a transparent view, which makes them unable to be tapped. 

### Steps to Reproduce / Code Snippets / Screenshots

```
  topBar: {
    elevation: 0,
    buttonColor: 'black',
    backButton: {
      ...{ icon: Platform.OS === 'ios' ? undefined : Icons.backArrow },
      color: 'black',
    },
    title: {
      component: {
        name: types.navBarTitle,
        passProps: {
          title,
        },
        alignment: 'center',
      },
    },
  },
```

Title Component
```
  render() {
    const { title } = this.props;
    return (
      <Text allowFontScaling={false}>
        {title ? title.toUpperCase() : ''}
      </Text>
    );
```
<img width="299" alt="Screen Shot 2019-11-04 at 12 54 03 AM" src="https://user-images.githubusercontent.com/6511976/68109028-6be57b00-fe9e-11e9-9ec0-44ab417aa170.png">

### Environment
* React Native Navigation version: 3.2.0
* React Native version: 6.1.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator. Debug.

**Comment by bdrobinson** [comment]
This is still an issue for me on RNN 6.7.3.
