### ISSUE TITLE
How to disable tabs bar button animation on Android

### ISSUE THREAD

**Issue by linwenjun** [wix/react-native-navigation#563]
### Issue Description

Is there a way to disable tabs bar button animation on Android
### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 2.0.0
* React Native version: 0.37
* Platform : Android 5.0 
* Device info: Device

**Comment by mordaha** [comment]
Not sure if it helps...

You cat set forceTitlesDisplay

```javascript
 Navigation.startTabBasedApp({
      // ....
      appStyle: {
        forceTitlesDisplay: true,
      },
      // ....
```

So text labels on the android tabbar will be always shown (and the animation will be only a little resize of the selected tab)

See `/android/app/src/main/java/com/reactnativenavigation/params/parsers/StyleParamsParser.java` for reference.

**Comment by lappalj4** [comment]
Could we get a proper reference of the available styles for both platforms? As it is, it is quite troublesome to play around with the styles...

**Comment by guyca** [comment]
@lappalj4 Sorry about the confusion. The docs were neglected for while and we're now slowly adding the missing pieces. Added `forceTitlesDisplay` to the [docs](https://wix.github.io/react-native-navigation/#/styling-the-tab-bar?id=style-object-format)

**Comment by lappalj4** [comment]
@guyca, good to hear - thanks!

**Comment by Naoto-Ida** [comment]
Is there a way to completely do away with the slight animation that happens when you select tabs, even with `forceTitlesDisplay`?

**Comment by luoyushouchai** [comment]
@guyca Where to set forceTitlesDisplay true in v2?

**Comment by pie6k** [comment]
I'm not able to set it in v2 too

**Comment by adeteejay** [comment]
@pie6k @luoyushouchai if you havent found it, you can titleDisplayMode: 'alwaysShow' | 'showWhenActive' | 'alwaysHide';  in options under setroot like so: 
```

Navigation.setRoot({
	root: {
		bottomTabs: {
			options: {
				bottomTabs: {titleDisplayMode: 'alwaysShow'}
			},
			children:[]
		}
	}
})
```
