### ISSUE TITLE
No known class method for selector 'systemBackgroundColor'

### ISSUE THREAD

**Issue by cybercoder** [wix/react-native-navigation#5630]
### Issue Description

I don't know about xcode programming, but after installation using documentation on a clean react-native this error appeared in build to simulator time.
 

### Steps to Reproduce / Code Snippets / Screenshots
![Screen Shot 2019-11-05 at 15 02 20](https://user-images.githubusercontent.com/437872/68205007-760e9300-ffde-11e9-9df8-9e60fac4ea74.png)

### Environment
* React Native Navigation version: 3.4.0
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Sim/iPhone X/Debug

**Comment by blueberry6401** [comment]
Looks like this commit fixes this https://github.com/wix/react-native-navigation/commit/99ddcd864005ce768ca7c0b34d2ecfa8246dc568
