### ISSUE TITLE
(IOS) Intermediate unknown screen between splash screen and landing screen

### ISSUE THREAD

**Issue by vrautgit** [wix/react-native-navigation#5631]
### Screenshot
<img width="830" alt="Screenshot 2019-11-06 at 12 51 45 PM" src="https://user-images.githubusercontent.com/22424365/68277277-d9f39300-0094-11ea-8352-00c99b94d00e.png">

### Steps to Reproduce
1. First splash screen is shown
2. Immediately after splash-screen above screen shows up for few seconds

### Issues
1. Half white and half black screen
2. App is opened in landscape and only **this particular** screen is shown in **portrait**

### Device and Platform tested
1. IOS - iPad (On release build as well)

### Dependancies
1. react-native-navigation: 3.2.0
2. react-native: 0.60.5
3. react-native-cli: 2.0.1

**Comment by MakhouT** [comment]
I am also having this issue. I think it's related to React-native and not RNN?
When you have an error (trigger it with console.error('error') ) I think you should also have the red error screen on it's side. Can you confirm this?

**Comment by vrautgit** [comment]
Thank @MakhouT

I fixed the issue using following workaround:
1. Installed react-native-splash-screen.
2. On the first component render added this snippet
   `SplashScreen.hide();` 

Above screen is present but it's in the background so not shown to the user
