### ISSUE TITLE
Require working example of react-native-navigation

### ISSUE THREAD

**Issue by shobhitnpm** [wix/react-native-navigation#5637]
### Issue Description

Hi there is no working example given in docs.
We require working example of react-native-navigation with latest version with react-native version 0.61
### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: 3.5.1
* React Native version: 0.61.3
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by syedabuthahirm** [comment]
[This repo](https://github.com/syedabuthahirm/react-native-navigation-install-guide) will guide you for android

**Comment by guyca** [comment]
https://github.com/wix/react-native-navigation/tree/master/playground
