### ISSUE TITLE
[Android] react-native-slider doesn’t work on overlay 

### ISSUE THREAD

**Issue by marf** [wix/react-native-navigation#5638]
### Issue Description

Hello, I am using the [react-native-slider](https://github.com/react-native-community/react-native-slider) package from react native community, it is a native slider.

I display the slider inside an overlay of RNN v3, the problem is that on iOS the slider can be controller by the touch, while on Android I cannot drag on top of it to change its value.

I have tried to put the slider outside the overlay and it works fine.

I guess there are some problems with the OverlayTouchDelegate, but I am not sure.

Any solutions?

### Environment
* React Native Navigation version: 3.5.0
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and physical device, both Debug and Release

**Comment by geroale** [comment]
Same problem.

A sample of the code I'm using:

Root.js
`
Navigation.registerComponentWithRedux('MyApp.OverlayScreen', () => OverlayScreen, Provider, store);
. . . .
Navigation.setRoot(. . . .);
Navigation.showOverlay({
  component: {
    name: 'MyApp.OverlayScreen',
    options: {
      overlay: {
        interceptTouchOutside: false,
        handleKeyboardEvents: true
      }
    }
  });
`

OverlayScreen.js
`
class OverlayScreen extends Component {

  constructor(props) {
    super(props);
    GlobalComponents.setOverlayComponentId(this.props.componentId);
  }

  render() {
    return (
      <Slider
      style={styles.progressbar}
      value={props.currentTime}
      minimumValue={0}
      maximumValue={props.duration}
      onSlidingComplete={(value) => props.onSeekSliderMoved(value, false)}
      onSlidingStart={props.onSeekSliderMoving}
      minimumTrackTintColor={props.volumeSliderEnabled ? props.colorText : props.colorPrimary}
      maximumTrackTintColor={props.colorSecondaryTextLight}
      disabled={props.disableSlider}
     />
    )
  }
}

export default connect(. . . .)(withTheme(CodePush(AppHover)));
`
