### ISSUE TITLE
[V3] Passprops not passing... props...

### ISSUE THREAD

**Issue by siperjff** [wix/react-native-navigation#5639]
### Issue Description
When using passProps in (at least) these scenarios: root, push, modal, stack,  the props that are called in **this.props** are **undefined**

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.push('resultsScreen', {
        component: {
          name: 'resultPage',
          passProps: {
            currentPosition: accessedItemPosition,
            positionsList: positionsList,
          },
          options: {
            topBar: {
              title: {
                text: contextList[accessedItemPosition].name,
              },
            },
          },
        },
});
```

![Simulator Screen Shot - iPhone 11 - 2019-11-08 at 12 18 42](https://user-images.githubusercontent.com/17105333/68501621-8c119300-022c-11ea-98aa-bb5c7e690be1.png)

Also, when printing the values of ``` this.props``` , there is no mention of either  "currentPosition" or "positionsList" further confirming the "undefined" description mentioned above.
---
### Environment
* React Native Navigation version: ^3.5.1
* React Native version: 0.61.3
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): OS 13.2
* Extra: Also using redux and redux-persists

**Comment by DaniShalash** [comment]
Can we see the code?
Maybe "this" is not defined, which is the case if you try to access it in an unbound method

**Comment by siperjff** [comment]
Hi, thank you for responding.

I am not sure which code you are referring to, but one thing I can confirm is that, like said in my previous post, printing `JSON.stringify(this.props)` does print. But it only prints the value of the redux props (redux's root). That said it does not print  "currentPosition" or "positionsList".

Furthermore, I would also like to say that I am using the same code (minus the necessary changes to make react-native-navigation v3.5.1 work) as I did when using react-native-navigation v1.

I will still share the code of where the error message ( shown in the image ) is pointing to (3rd line under render):

```
render() {
    console.log('Update of ResultPage');
    let currentResult = this.state.list[
      this.props.positionsList[this.props.currentPosition]
    ];
    return (
      <View style={{backgroundColor: '#FFF', flex: 1}}>
        <IndicatorViewPager
          style={{height: '90%', width: '100%'}}
          indicator={this.renderTabIndicator()}
          indicatorOnTop={true}>
          <View>
            <ScrollView
              contentContainerStyle={{
                flexGrow: 1,
                justifyContent: 'space-between',
              }}>
              <View
                style={{alignItems: 'center', justifyContent: 'center'}}
                pointerEvents="none">
                <TitleComponent text={'PK Profile'} />
                <ViewShot ref={ref => (this.pkProfileRef = ref)}>
                  <GraphComponent
                    data={currentResult.data}
                    formData={currentResult.formData}
                    style={{backgroundColor: 'white'}}
                    animate={this.state.animationFlag}
                  />
                </ViewShot>
              </View>
            </ScrollView>
          </View>
        </IndicatorViewPager>
      </View>
    );
  }
}
```

**Comment by jinshin1013** [comment]
It's most likely you are registering your components correctly. Here is a similar issue which was resolved: https://github.com/wix/react-native-navigation/issues/4406.

If it still doesn't help, creating a minimal reproduction for me to have a look would be greatly appreciated.

**Comment by siperjff** [comment]
@jinshin1013 You are correct, it appears that I was not registering my components properly.

I am sorry for reading the docs wrongly and for anyone that has the same issue please see either the docs here: https://wix.github.io/react-native-navigation/#/docs/third-party or  this post: 

> > Please try this code in app.js Navigation.registerComponent('route-builder.PlaceDetailScreen', () => (props) => ( <Provider store={store}> <PlaceDetailScreen {...props} /> </Provider> ), () => PlaceDetailScreen);
