### ISSUE TITLE
Missing field in CommandCompletedEvent interface

### ISSUE THREAD

**Issue by jpgarcia** [wix/react-native-navigation#5641]
### Issue Description

I'm updating the [react-native-navigation-hooks](https://github.com/underscopeio/react-native-navigation-hooks) library to use **Typescript** and while doing it I noticed that the `CommandCompletedEvent` inside [Events.ts](https://github.com/wix/react-native-navigation/blob/master/lib/src/interfaces/Events.ts) does not include `commandName` parameter. 

Apparently this value is only set on **IOS** but on **Android**. Also on android the `params` field doesn't seem to be passed

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.events().registerCommandCompletedListener(event => {
  console.log(event)
})
```
#### IOS output 
```bash
{
 "commandId": "push5",
 "completionTime": 1573340365021,
 "params": {
  "componentId": "Component2"
 },
 "commandName": "push"
}
```

#### Android output 
```bash
{
 "completionTime": 1573340393522,
 "commandId": "push5"
}
```

@guyca does it make sense? If so I can create a PR to include the `commandName` as part of the `CommandCompletedEvent` interface and try to return it from **Android** if possible

---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.61.0-rc.3
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): N/A

**Comment by guyca** [comment]
Thanks @jpgarcia 
This field wasn't actually missing, it's redundant on iOS. The command name can be deduced by the commandId. But I agree sending it makes using the listener simpler 👍
