### ISSUE TITLE
imageWithTintColor

### ISSUE THREAD

**Issue by eladgel** [wix/react-native-navigation#5647]
### Issue Description

When running app on ios 13 devices the buttons color is **blue** until **mergeOptions** is called

### Steps to Reproduce / Code Snippets / Screenshots

Open every screen with a left/right button with custom color 
---
### Environment
* React Native Navigation version: 3.2.0-snapshot.504+
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, IOS 13, Debug

This [commit](https://github.com/wix/react-native-navigation/commit/5d751f643ad80a67abccc51d75f1127e2b65824a) is causing the issue

**Comment by guyca** [comment]
duplicate, lets track progress on #5651
