### ISSUE TITLE
V3 Roadmap?

### ISSUE THREAD

**Issue by pie6k** [wix/react-native-navigation#5650]
Hi Folks!

First of all, thank you so much for maintaining this amazing lib!

Recently, when working with a new project, I've noticed V3 tags everywhere in issues and pull requests.

However, I was not able to find any official announcement or roadmap that would include the main goals and some progress indication.

I'd love to play with new features, but I don't really know what they are and how risky it is to start using them now.

**Comment by guyca** [comment]
Hey @pie6k 👋 
Changes are detailed in the [changelog](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#300). V3 mostly contained a big refactor on Android needed to support drawing behind StatusBar properly (and soon behind the NavigationBar). There were no changes on iOS.
