### ISSUE TITLE
Get screen position of bottom tap

### ISSUE THREAD

**Issue by hnsa** [wix/react-native-navigation#5652]
Is it possible to get the "coordinates" of a bottom tab? We're building a guide that should point at a specific bottom tab (a bit like the gif below).

I have tried to build it by computing the x, y coordinated based on [`Navigation.constants()`](https://wix.github.io/react-native-navigation/#/docs/constants) and [Dimensions](https://facebook.github.io/react-native/docs/0.59/dimensions#docsNav). But have realised that there is too much difference between platforms and devices. There seems to be some positioning logic going on in either RNN or AHBottomNavigation that I can't find.

![suggest_tooltip_by_volorf](https://user-images.githubusercontent.com/47025640/68769068-0030aa00-0624-11ea-90d2-1355bec7b88a.gif)

**Comment by ItsNoHax** [comment]
That's a interesting one. Gonna tag @guyca for this. Maybe you have an idea?

**Comment by ys-sherzad** [comment]
@ItsNoHax Hi there, I'm wondering if this now possible? to locate the bottom tab somehow?
