### ISSUE TITLE
White space / gap in overlay

### ISSUE THREAD

**Issue by BeauCarrel** [wix/react-native-navigation#5653]
### Issue Description

In Android and Android only I have a strange white gap at the top of the screen.

Not only is this gap ugly and takes up space, but it seems to "shift" all touches, for example, if I want to select a button on the overlay screen, I have to tap about the size of this whit space above the button for it to be registered.

### Steps to Reproduce / Code Snippets / Screenshots

![Screenshot_2019-11-13-14-48-43-722_com mmtsurvey mmt](https://user-images.githubusercontent.com/32204131/68769579-d88e1180-0624-11ea-86e0-f88d8f813ebd.png)

```
Navigation.showOverlay({
        component: {
            name: launcherId,
            options: {
                ...
            }
        }
}
```

I've tried every layout config imaginable, (all modalPresentationStyles, topBar visible / not visible, drawBehind on/off, statusBar etc.) and I can't seem to get rid of this In my application.

I'm not sure which other files to show, I've followed the installation instructions, obviously if you want to see any other file just ask :)

---
### Environment
* React Native Navigation version: 3.5.1
* React Native version: 0.61.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device, Debug and release, Simulator running Android 6.0, device is a Mi 8 running Android 8.1.0

---
Thanks in advance for the help, and thanks for the great package, I've been using it for over a year in all my RN projects and I appreciate the great work! 😀

**Comment by DanDance** [comment]
Hey! Can you try to render topBar? Will it go or stay?

**Comment by BeauCarrel** [comment]
Hi ! Changing the topBar options doesn't do anything for me, whether visible or not, draw behind etc, I see no topBar at all, just this white space. I'm not even sure you can have headers on overlays, so this might be normal.

**Comment by edferreira** [comment]
You shouldn't need to pass any Topbar config to an Overlay.
Could you provide how your root view is being called and your Overlay component?

**Comment by BeauCarrel** [comment]
I just experimented with the topBar config to see if it got rid of this bar. 

But good news, I have an update on the problem thanks to your question, I've found where the problem is coming from, I didn't think to mention that the overlay was being shown before any root was being shown. 

My app starts and shows a"launcher" overlay and a Eula "I accept" overlay and a location permission overlay, if necessary. While showing these overlays, in the background it tries to connect to our API to check if the user is connected or not which then decides which root to open (Connection or the main app)

I noticed that if I open a root first, then show these overlays I don't have this problem. I didn't realise that I needed a root, I don't know if that's a bug or not, It wasn't a problem before updating RN and RNN.

I'll close this issue. Feel free to reopen if it is a bug and needs sorting.

Thanks for your help, your question made me realise the cause!
