### ISSUE TITLE
[v3][Andorid 4.4.2] Can't hide topBar

### ISSUE THREAD

**Issue by DanDance** [wix/react-native-navigation#5655]
### Issue Description

Android 4.4.2 not hiding topBar. Tested on 8.0.0, everything seems to be ok.

### Steps to Reproduce / Code Snippets / Screenshots
Still have about 20px blank bar on top of the screen. Tried to set topBar options on stackNavigator but had no effect.
Configuration:
```
const startLayout = {
  root: {
    component: {
      name: navKeys.loadingScreen,
    },
  },
};
Navigation.setDefaultOptions({
    topBar: {
      visible: false,
      drawBehind: true,
      animate: false,
      height: 0,
    },
    bottomTabs: {
      visible: false,
      height: 0,
    },
    statusBar: {
      style: 'light',
    },
  });
  Navigation.setRoot(startLayout);
```
---
### Environment
* React Native Navigation version: 3.5.1
* React Native version: 0.61.2
* Platform(s) (iOS, Android, or both?): Android 4.4.2. Don't ask me why that old version.
* Device info (Simulator/Device? OS version? Debug/Release?): Alcatel Onetouch, debug

**Comment by guyca** [comment]
Android 4.x isn't supported.

**Comment by DanDance** [comment]
https://github.com/wix/react-native-navigation/blob/master/lib/android/app/build.gradle#L8
@guyca but `DEFAULT_MIN_SDK_VERSION = 19`, is it mistake?
