### ISSUE TITLE
[v3] Option to change the top border/shadow color of the bottom tabs

### ISSUE THREAD

**Issue by svenlombaert** [wix/react-native-navigation#5656]
### Issue Description

Option to style the top border of the bottom tabs. I think it uses shadow now, but when I change the background color of the bottom tabs to black, there's no border/divider anymore.

### Steps to Reproduce / Code Snippets / Screenshots

![](https://d2u34f81dd2wkc.cloudfront.net/w68i%2Fpreview%2F29403896%2Fmain_full.png?response-content-disposition=inline%3Bfilename%3D%22main_full.png%22%3B&Expires=1573816542&Signature=fXNl1WnzTyQeJGk-86vYntCaVETCzONjNVhXkhyZz5nVQlZyV7fD1BMAjahtYaRibKRHeUfMn6R81Fe5BevHMtgNbd-YF61muLmO609igP2v4vMfZuCFH90E8axsIL5mL1TMIAESqraTJWOYPjFSZ~wHzLF6cPSE3zTCCEBdcp1~6c8nEIOXZfvn6VWs1XFgBtS5pDS~jeyxzSFg67PgXanYPSkl4oEhmcXRXalZ31i23pBBvmfySnF05tlW1-T~sV0pBAIKzU31fGUhNpL1qbDbzJ1akpmyClsNB8lb6UTrrfm7OFHfJYzZdy2MLe6~4-xDUYJo28gAzcxthla2yQ__&Key-Pair-Id=APKAJT5WQLLEOADKLHBQ) ![](https://d1lkrksv5kyiko.cloudfront.net/178i%2Fpreview%2F29403901%2Fmain_full.png?response-content-disposition=inline%3Bfilename%3D%22main_full.png%22%3B&Expires=1573816570&Signature=fLLVFuhs5MPP1tCS4ZWCdUh6U0VLdLxM1RXAOzazcU8i6wjJ5c-WiWEMF7-ht5rUTCvJO3774YJ-67tyfpAr27cEkojYWGyMvis-JAEQbBhntELQbV6aUKGOtFnYfx~iRu~~hCKc-8km~2IXr7ej70SzSit~uI9NWL~ov7jB-FNP1osi1wnVcoBP0gQ3CNOhAs2aITlQ1kq4NpJJ68OBHStjdDr3NYR6IHkFisD0xw3h-R~f8v2jQmsjMzLEfZey5EL5G1wARaNG59~M3WV-ozAXOaGjUGf1EvjaovAazMfKAzdivv995jSLAN6buBZ3PhHQn0eIhfwmr3Yc50H-XA__&Key-Pair-Id=APKAJT5WQLLEOADKLHBQ)

---
### Environment
* React Native Navigation version: 3.1.1
* React Native version: 0.60
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iPhone X, One Plus 7 Pro

**Comment by vovka-s** [comment]
Not stale!
I need this option too. Please add an attribute to bottomTabs like a `borderColor` for tobBar

**Comment by vovka-s** [comment]
Not stale!

**Comment by svenlombaert** [comment]
Not stale

**Comment by vinnyA3** [comment]
Bot! you have no chill 😒

**Comment by vinnyA3** [comment]
can we re-open this?

**Comment by Findiglay** [comment]
Not stale!

**Comment by ifier** [comment]
We have light UI for the dark mode as well and I need to set color of border/shadow for bottomTabs to a dark color as well :(
Not stale

**Comment by stereodenis** [comment]
not stale

**Comment by zazagag** [comment]
not stale
