### ISSUE TITLE
Push Notifications forcing the app to launch

### ISSUE THREAD

**Issue by kristikristo** [wix/react-native-navigation#566]
### Issue Description

I'm using react-native-navigation with react-native-push-notifications and having a strange issue. 
When the app is closed (not in foreground) and a push notification is received, it automatically launches the application. Somehow, it forces the app to go in foreground.

I tested it by removing react-native-navigation from the project (updated MainApplication, MainActivity and index.android.js) and it worked fine. Push notifications were received without forcing the app to launch.

---
### Environment
* React Native Navigation version: 2.0.0-experimental.154
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device. Debug & Release.

**Comment by Crash--** [comment]
I got the same behavior with RN 0.39.2 :/

@varungupta85 Is it something you've experimented?

**Comment by varungupta85** [comment]
@Crash-- I will check this behavior and report back.

**Comment by varungupta85** [comment]
@Crash-- @kristikristo I am not observing the behavior reported in this issue but I am using my own fork of RNPN which leads me to believe that it may be a regression in the RNPN package. I don't have the changes checked in by mikelambert which has changed the way the remote notifications are handled by the package. Some of those changes were reverted. So, if you are not using the latest package, please upgrade to the latest and try again.

For me, if the app is not running, the remote notification is shown but the app is not started until I click on the notification.

**Comment by varungupta85** [comment]
@kristikristo Could you share the notification handler for the Android app? That is the only code that would be run when a notification is received and I can check if something stands out there.

**Comment by kristikristo** [comment]
@varungupta85 I have react-native-navigation@2.0.0-experimental.154 and react-native-push-notification@2.2.1 on my project.

Sure, code is below, but I do not handle the content of push:

`
PushNotification.configure({
      onRegister: (token) => {
        this.onPushRegistered(token.token);
      },
      senderID: '',
      popInitialNotification: true,
      requestPermissions: true,
    });
`

**Comment by varungupta85** [comment]
@kristikristo This looks alright. I am not sure why would the app come into foreground when a notification is received. I was thinking maybe you have the `startApplication` method of RNN in the notification handler which may cause the app to come into foreground (not sure if it would but just a guess).

**Comment by kristikristo** [comment]
@varungupta85 You are using the same versions as well?

**Comment by explorigin** [comment]
I'm experiencing this too (only on Android). I'm currently using my own branch but last I rebased was on .150

**Comment by Crash--** [comment]
I just made a simple project to reproduce the bug. https://github.com/Crash--/RNN-RNPN-BUG

**Comment by guyca** [comment]
This is caused by RNPN calling `createReactContextInBackground()` which results in a call to `start*App()`. Will be fixed hopefully on Sunday

**Comment by kristikristo** [comment]
@guyca With the committed fix, the app is not being launched when the push notification arrives, but however, the app cannot be opened anymore

**Comment by guyca** [comment]
@kristikristo Yes, me and @Crash-- debugged the issue more today and figured out why that's happening, will do my best to push a fix tomorrow.

RNN doesn't play nice with other components that start react context in background - we must address this asap and it will solve the issue. But this issue would have not surfaced if RNPN bothered to cleanup after its self by calling `reactInstanceManager.destroy()` after it finished handling incoming notifications in Js.

**Comment by kristikristo** [comment]
@guyca @Crash-- Any news regarding the fix for this bug?

**Comment by guyca** [comment]
Hey guys

Daniel and I discussed this issue at length and came to conclusion that fixing it will break all apps using RNN. The fix is also very high risk since it changes the entire mechanism used to start the app.

The issue is that RNPN creates react context in background in order to run it’s logic in Js, even if the app is killed and after it finishes, it doesn’t destroy react context. Meaning, each time a push notification is received, your entire bundle is parsed and all your static Js code is run. We didn’t think the bundle would be parsed by some other action like push notifications, so we tied the call to startApp to static code execution.
This means that when the app is launched, either by opening a notification or clicking the app icon, if react context is already created or being created, we bail out and don’t show the app (NavigationActivity).

We’ll do our best to address this issue, but we can’t commit on a time frame since any solution will have unknowns and will require action from all our internal teams using RNN.

Since this issue might be an ongoing effort, it might be worth to consider migrating to https://github.com/wix/react-native-notifications which relys on events and promises to query notifications and makes no assumptions and the Applications state.

```js
import {NotificationsAndroid, PendingNotifications} from 'react-native-notifications';

PendingNotifications.getInitialNotification()
  .then((notification) => {
        console.log("Initial notification was:", (notification ? notification.getData() : 'N/A');
    })      
  .catch((err) => console.error("getInitialNotifiation() failed", err));
```

**Comment by elliotstokes** [comment]
Hey. I've just hit this issue. Is there any kind of work around for this?

**Comment by explorigin** [comment]
@elliotstokes The fix is to switch to https://github.com/wix/react-native-notifications to handle your push notifications.

**Comment by enahum** [comment]
So I've moved our app to use https://github.com/wix/react-native-notifications but I'm wondering if there is an issue cause when calling `consumeBackgroundQueue` on RNNotification on IOS it does not do anything, and If I use PushNotificationIOS from react-native directly `getInitialNotification` it also returns null, same happened with `react-native-push-notifications` library, so im thinking there is an issue with the way the app bootstraps to use RNNavigation.

Note: If the app is in the foreground or already opened but in the background then everything works fine no matter the library im using

**Comment by guyca** [comment]
@enahum Perhaps it will be better to open an issue in `react-native-notifications` and not piggyback on this one.

**Comment by enahum** [comment]
Already did, but the thing is that the issue happens no matter what lib I use when the app is in cold state and the push notification is tapped the initial notification is not present and if I use any other navigation lib like navigationExperimental it works just fine, so im guessing is something about the way the app bootstraps when using RNNavigation, don't you agree?

**Comment by varungupta85** [comment]
@guyca @enahum Not sure if this is the right thread, but I also ran into a similar issue with using `getInitialNotification` API in `PushNotificationIOS` module of React Native. @d4vidi has confirmed that they have also identified a similar issue and that they would work on a fix for it. I don't think it has been worked on yet. I think `getInitialNotification` is an important part of the overall UX of the app and it should either work out of the box or there should be some suggested workaround that users can employ till a fix is available.

**Comment by jbolter** [comment]
@enahum Does this solve your issue with the initial push on iOS? https://github.com/wix/react-native-notifications/issues/35  I made a small tweak to the AppDelegate to make sure launchOptions were being passed in and then I was able to then consume the background push that opened the app.

**Comment by enahum** [comment]
@jbolter I ended up making the same modification to pass **launchOptions** and it works great

**Comment by hungdev** [comment]
@enahum please could you tell me how to open app when receiving notification?

**Comment by kholiavko-roman** [comment]
I have the same issue.
If I kill app from process, and recive push notification - app is opened ! How to fix this ? I tested on android.

**Comment by guyca** [comment]
@kholiavko-roman 
You change the way your app is launched according to what's shown [here](https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=compatibility-with-headlessjs), it should solve the issue.

**Comment by kholiavko-roman** [comment]
@guyca, thanks for replay! 
I trying change the way of starting my app, as you say, but it comes to foreground anyway. 
I enabled debug mode, kill app from process, then send push, and variable appLaunched - shows false.

Here is my code:
`Promise.resolve(Navigation.isAppLaunched()).then(appLaunched => {
  console.log('appLaunched');
  console.log(appLaunched);

  if (appLaunched) {
    startApp(); // App is launched -> show UI
  } else {
    new NativeEventsReceiver().appLaunched(startApp()); // App hasn't been launched yet -> show the UI only when needed.
  }
});

function startApp() {
  Navigation.startSingleScreenApp({
    screen: {
      screen: 'splash'
    },
    drawer: {
      left: {
        screen: 'drawer'
      },
      animationType: 'door'
      //optional, iOS only, for MMDrawer: 'door', 'parallax', 'slide', 'slide-and-scale'
      // for TheSideBar: 'airbnb', 'facebook', 'luvocracy','wunder-list'
    },
    animationType: 'fade'
  });
} //end of startApp`

**Comment by kholiavko-roman** [comment]
@guyca 
If I call `Navigation.isAppLaunched()` form child pages - it return right result - true, but if I call it from my root file, index.android - it does not return true.

**Comment by guyca** [comment]
Right, because the app is not launched. `appLaunched` is true when app was opened specifically by the user (app icon was clicked)

1. You killed the app (it's not launched)
2. Pressed a push notification
3. The bundle is parsed (app is still not launched)
You'll probably need to change the conditional somehow

```js
if (appLaunched || appOpenedFromPushNotification()) {
    startApp();
  } else {
    new NativeEventsReceiver().appLaunched(startApp());
  }
```

**Comment by kholiavko-roman** [comment]
@guyca, thank you for helping!

My problem is, when I killed app frop process, and I resive push, app started and becomes to foreground.
1. You killed the app (it's not launched)
2. Recive push notification (I am not clicked on it)
3. App launched and becomes to foreground.

How to avoid this ?

In case if app is launched in background and I received push, all works fine.

**Comment by kholiavko-roman** [comment]
I tried to switch on `wix/react-native-notifications` plugin, but it has a problem - it app dropped from process, it can`t fire callback.

**Comment by kholiavko-roman** [comment]
@guyca 
Does [bransh v2](https://github.com/wix/react-native-navigation/tree/v2) still has this problem ?

**Comment by fokoz** [comment]
@guyca 
The solution is almost working for me, but after receiving push notification and user taps the app icon (not tapping notification), sometimes app cannot be opened(40%) or sometimes it has some weird windows(like it stucks) before opening the app(60%).

**Comment by tmaly1980** [comment]
@guyca  What exactly is `appOpenedFromPushNotification()` ? Could you give an example with the react-native-push-notification ?
