### ISSUE TITLE
Deep linking with optional arguments

### ISSUE THREAD

**Issue by mbrucher** [wix/react-native-navigation#5660]
### Issue Description

`path` doesn't seem to accept optional arguments.

### Steps to Reproduce / Code Snippets / Screenshots

```
  ex: {
        screen: UpdateEvent,
        navigationOptions: ({ screenProps }) => ({
          title: screenProps.intl.formatMessage({ id: "UpdateEvent.title"}),
        }),
      },
    path: "ex/:param1(/:param2)",
  },
````

I thought `param2` was optional when looking on some tutorials, but it doesn't work. Would be great to have some documentation on this.

---
### Environment
* React Native Navigation version: 4.0.10
* React Native version: 0.61.3
* Platform(s) (iOS, Android, or both?): iOS and Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug, Release...

**Comment by makirby** [comment]
Hey, I think you’ve posted in the wrong library, I believe that is the api for https://github.com/react-navigation
