### ISSUE TITLE
[Android 9, 3.6.0]After hiding StatusBar container does not get resized

### ISSUE THREAD

**Issue by bvic23** [wix/react-native-navigation#5662]
### Issue Description

When I hide the `StatusBar` on Android 9.0 container does not get resized and a (white) stripe remains at the top of the screen. Without `react-native-navigation` it works fine!

### Steps to Reproduce / Code Snippets / Screenshots

| With react-native-navigation               | Without react-native-navigation               |
| -------------------- | ------------------- |
|![statusbar_bug_with_react-native-navigation](https://user-images.githubusercontent.com/2664424/69136801-c9dbaa80-0abb-11ea-882d-08042a77c848.gif)|![statusbar_bug_without_react-native-navigation](https://user-images.githubusercontent.com/2664424/69136813-d4963f80-0abb-11ea-9f8f-b15f46eca346.gif)|

Let me attach a sample projects of the videos above:

[StatusBarBug_Without_react-native-navigation.zip](https://github.com/wix/react-native-navigation/files/3863190/StatusBarBug_Without_react-native-navigation.zip)

[StatusBarBug_With_react-native-navigation.zip](https://github.com/wix/react-native-navigation/files/3863192/StatusBarBug_With_react-native-navigation.zip)

---
### Environment
* React Native Navigation version: 3.6.0
* React Native version: 0.61.4
* Platform: Android
* Device info: Reproducible both in Emulator/Device, Debug/Release

**Comment by DaniShalash** [comment]
Same issue here

**Comment by JunoVW** [comment]
Any idea on a solution? Having the same problem with both the status and navigation bar on Android.

**Comment by guyca** [comment]
Should be fixed by now
