### ISSUE TITLE
[v3] Setting layout backgroundColor via mergeOptions doesn't change the color behind the bottomTabs

### ISSUE THREAD

**Issue by svenlombaert** [wix/react-native-navigation#5668]
### Issue Description

Related to this https://github.com/wix/react-native-navigation/issues/5533 I'm also experiencing a different issue with mergeOptions and changing colors. This issue can also be seen as follow-up of https://github.com/wix/react-native-navigation/issues/5192

Calling mergeOptions with the current componentId, and changing the backgroundColor of layout, correctly changes the color on iOS (This color can be seen when hiding the bottomTabs). On Android, this color does not change, only after I switched tabs.

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
Navigation.mergeOptions(this.props.componentId, 
  {
     layout: {
        backgroundColor: 'white',
     }
  }
);
```

After this, when pushing a new screen and hiding the bottomTabs, the color behind the bottomTabs is still the previous one (black in our case). This color can be briefly seen when the bottomTabs disappear.

---
### Environment
* React Native Navigation version: 3.7.0
* React Native version: 0.60
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Galaxy S7

**Comment by guyca** [comment]
When BottomTabs are not visible, you're actually seeing the color of the native view's background.
You can change that color by specifying
```js
options: {
  layout: {
    backgroundColor: 'red'
  }
}
```

**Comment by svenlombaert** [comment]
I know that, and that's not the bug. When the color is set, and I use mergeOptions, the change doesn't take place.

**Comment by freudibili** [comment]
Hello @svenlombaert did you manage to solve it somehow? I'm getting the same behavior:

 ```
const { themeColors, isDark } = useTheme()

    const updatedTheme = (): void => {
        Navigation.mergeOptions(componentId, {
            layout: {
                backgroundColor: themeColors.BACKGROUND,
                componentBackgroundColor: themeColors.BACKGROUND,
            },
            statusBar: {
                backgroundColor: themeColors.BACKGROUND,
            },
            topBar: {
                background: {
                    color: themeColors.BACKGROUND,
                },
                title: {
                    color: themeColors.LABEL,
                },
                backButton: {
                    color: themeColors.TERTIARY,
                },
            },
            bottomTabs: {
                backgroundColor: themeColors.BACKGROUND_SECONDARY,
            },
            bottomTab: {
                selectedTextColor: themeColors.PRIMARY,
                textColor: themeColors.SECONDARY,
            },
        })
    }
```
The layout background color, doesn't update.
