### ISSUE TITLE
Any way to prevent re-mounting?

### ISSUE THREAD

**Issue by singhsoldier13** [wix/react-native-navigation#5670]
### Issue Description

I am opening a Webview inside react-native-navigation's modal. When I call dismissModal, it unmounts the WebView component. Is there any way to prevent this re-mounting behaviour? If not possible in modal, can we do it in stack navigation somehow?
We don't want to reload webpage everytime we show a modal. Any indication would be helpful.

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
You'll need to create a ViewManager for that which creates and manages the WebView. It will keep a ref to it even when the screen is unmounted.
