### ISSUE TITLE
[V3] support onPress event for bottom tab

### ISSUE THREAD

**Issue by idanlo** [wix/react-native-navigation#5676]
### Issue Description
Support tab press event so that you can open a modal instead of a screen.
these issues were closed because they were stale but they are still relevant: #5545 #5193

### Environment
* React Native Navigation version: 3.7.0
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): Both

**Comment by guyca** [comment]
Reopened one of the issues you've linked, I'll try to prioritise it internally.
