### ISSUE TITLE
Can`t open leftSideMenu by swipe, but can close by swipe on iOS. Android works fine

### ISSUE THREAD

**Issue by trantus** [wix/react-native-navigation#5680]
### Issue Description

I can`t open sidebar by swipe from left side, but can close, when it was open by button.
Even more, if i just add absolutely the same sidebar to right side, it works to right swipes!
I tried install and link **react-native-gesture-handler** but nothing changed

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.setRoot({
      root: {
        sideMenu: {
          left: {
            component: {
              name: 'Sidebar',
              id: 'leftSideDrawer',
            },
          },
          center: {
            stack: {
              id: 'mainStack',
              children: [
                {
                  component: {
                    name: screen,
                    passProps: { particularKekId: KekId, notification, type: 'menu' },
                    options: {
                      statusBar: {
                        backgroundColor: darkTheme.alpha,
                      },
                    },
                  },
                },
              ],
            },
          },
        },
      },
    })
  })
}
```

---
### Environment
* React Native Navigation version: 3.7.0
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator & Real Devices

**Comment by itsam** [comment]
Have a look at this https://github.com/wix/react-native-navigation/issues/4918
(I have added a gist for V3 as well). For V2 search the comments...

**Comment by trantus** [comment]
> Have a look at this #4918
> (I have added a gist for V3 as well). For V2 search the comments...

thanks to you i found a solution for V2
here is gist to my /node-modules/react-native-navigation/lib/ios/RNNSideMenuPresenter.m
https://gist.github.com/trantus/04b05afd8b79ff6cd11664d2c9afbc1a
