### ISSUE TITLE
How showOverlay works ...

### ISSUE THREAD

**Issue by djha-effendi** [wix/react-native-navigation#5684]
### Issue Description

I try to show an overlay but the screen is not draw above the called screen but in a new screen ...
I expect to display the overlay screen above the current screen displayed ...

### Steps to Reproduce / Code Snippets / Screenshots

  // Register screens ...
  ` Navigation.registerComponent('app.home', () => AppHome); ` 
  `  Navigation.registerComponent('app.overlay', () => TestOverlay); ` 

  // Set stack root
   ` Navigation.setRoot({ ` 
 `      root: { stack: { children: [{ component: { name: 'app.home' } }] } }, ` 
 `   }); ` 

  // AppHome component
 ` <SafeAreaView style={styles.container}> ` 
 `     <Button onPress={() => Navigation.showOverlay({ component: { name : 'app.overlay' } }) label="Press me" /> ` 
  `</SafeAreaView> ` 

  // Overlay
  `  <View style={{ ...StyleSheet.absoluteFill, opacity: 0.5, backgroundColor: 'red' }}> ` 
 `     <Text>Test overlay</Text> ` 
 `   </View>`

---
### Environment
* React Native Navigation version: 3.7.0
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): Android

**Comment by guyca** [comment]
You can find an example for showOverlay in the playground app https://github.com/wix/react-native-navigation/blob/master/playground/src/screens/NavigationScreen.js#L52

**Comment by djha-effendi** [comment]
Ok, interesting answer.
My code is based on this example ...
I will more investigate and maybe ask on stackoverflow.

If anyone else see my mistake ...

**Comment by GioLogist** [comment]
> You can find an example for showOverlay in the playground app https://github.com/wix/react-native-navigation/blob/master/playground/src/screens/NavigationScreen.js#L52

Well, actually this is interesting, because that code doesn't even use `showOverlay`, it uses `showModal`. 

When I use `showOverlay` directly, I get the same issue as mentioned above. Might be worth reopening this and diving in deeper.

**Comment by itsam** [comment]
Same here...

**Comment by kuzzmi** [comment]
I get the same problem. Using `showOverlay` displays a new screen with an overlay component.
