### ISSUE TITLE
[v3] Unresponsive Touch when animations are passed to modal 

### ISSUE THREAD

**Issue by GioLogist** [wix/react-native-navigation#5692]
### Issue Description

Touchables become unresponsive when animations are passed to `showModal`.

---
### Environment
* React Native Navigation version: 3.7.0
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug

---

### Example

```js
// App.js
Navigation.showModal({
  component: {
    name: 'Notification',
    options: {
      animations: {
        showModal: {
          content: {
            y: {
              from: -100,
              to: 0,
              duration: 100,
              interpolation: 'accelerate',
            },
          },
        },
      },
    }
  }
})
```

```js
// Notification.js

import React from 'react'
import { Text, TouchableOpacity } from 'react-native'

export const Notification = () => (
  <TouchableOpacity  onPress={() => console.log('hi')} activeOpacity={.5} style={{ alignItems: 'center', justifyContent: 'center', height: 400, width: 400}}>
    <Text>Hello World</Text>
  </TouchableOpacity>
)

export default Notification

```

### Expected behavior

`onPress` event logs to console

### Actual behavior

`onPress` never fires

### Workaround

Remove animation from `showModal` options

**Comment by GioLogist** [comment]
This is not stale, please re-open

**Comment by GioLogist** [comment]
@guyca can this be marked as not stale?

**Comment by elingersin** [comment]
not stale at all
