### ISSUE TITLE
[v3] dismissModal disabling animation does not work 

### ISSUE THREAD

**Issue by GioLogist** [wix/react-native-navigation#5693]
### Issue Description

Disable animations for `dismissModal` via the `mergeOptions` param doesn't work

### Steps to Reproduce / Code Snippets / Screenshots

```js
// Dismissing the modal like this does not work as expected. Dismiss is still animated
  Navigation.dismissModal(id,  { 
    animations: {
      dismissModal: {
        enabled: false
      }
    }
  })
```
---
### Environment
React Native Navigation version: 3.7.0
React Native version: 0.61.4
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug

**Comment by wincjh** [comment]
+1

**Comment by GioLogist** [comment]
This is not stale, please re-open

**Comment by pk1m** [comment]
dismissModal only takes one argument.  I disabled it by disabling it on my showModal call.

ie
``` 
Navigation.showModal({ ....., options: { animations: { dismissModal: { enabled: false } } } })
````
