### ISSUE TITLE
Huge right buttons on android

### ISSUE THREAD

**Issue by jfrolich** [wix/react-native-navigation#5694]
This bug is still not resolved. No way to do proper left buttons on android. (Pretty important because that's where the modal close button should be).

https://github.com/wix/react-native-navigation/issues/4819

**Comment by jfrolich** [comment]
My bad, the icon should be 24x24.

**Comment by crushy26** [comment]
hi @jfrolich, 24x24 creates a blurry icon in the release. Did you face the same issue?

**Comment by jfrolich** [comment]
You need to add @2x and @3x versions
