### ISSUE TITLE
3.2+ Invalid UIFontWeight '500'

### ISSUE THREAD

**Issue by MakhouT** [wix/react-native-navigation#5695]
### Issue Description

A screenshot says more than a thousand words.
<img width="723" alt="Screenshot 2019-11-28 at 11 04 30" src="https://user-images.githubusercontent.com/3041165/69810528-69034f00-11ec-11ea-97e7-d5103642b048.png">

Note: I am not setting any fontWeight: '500' though.

The last working version for me was 3.2. Then I did an upgrade to 3.6 then I got this bug, then I upgraded to 4.0 and the bug still existed. I am only developing on iPad, not on a phone.
When downgrading back to 3.2 it works again. But my red error screen is being rotated to portrait mode while I am doing development in landscape mode strictly on 3.2. When I upgraded to 3.6 and 4.0 landscape was being respected. 

---
### Environment
* React Native Navigation version: Issue is happening on 3.6 and on 4.0, last working version for me was 3.2
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): Currently only doing development on iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and device, iOS,

**Comment by MakhouT** [comment]
The problems was between the screen and the chair

**Comment by samcampisi** [comment]
@MakhouT what happened though? I'm having the same issue after upgrading to 4.0.4

**Comment by MakhouT** [comment]
@samcampisi Yes indeed that was the issue. Tip use typescript fixes it.

Sorry for the late response though!
