### ISSUE TITLE
[V4] iOS TopBar noBorder and largeTitle color issue

### ISSUE THREAD

**Issue by jinshin1013** [wix/react-native-navigation#5696]
### Issue Description
iOS TopBar `noBorder: true` and `largeTItle.color` options are no longer applied.

### Steps to Reproduce / Code Snippets / Screenshots
I've created a reproduction [here](https://github.com/jinshin1013/rnn-boilerplate), checkout `repro/ios-topbar-border` branch.

---
### Environment
* React Native Navigation version: 4.0.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by jinshin1013** [comment]
**Update**
Just a quick update that v4.0.2 fixed the `noBorder` issue, however the `topBar.largeTitle` issue is still present. I feel like I haven't specified the detailed issue with `largeTitle`:

* Setting `topBar.largeTitle.color` does not take in an effect
* `topBar.title` does not disappear when `largeTitle` is visible.

Hope this helps debug the problem little bit more.

**Comment by akahnn** [comment]
I'm on RNN `4.0.4` and can still reproduce this issue

**Comment by jinshin1013** [comment]
I can confirm that with `RNN@4.0.4` these issues were resolved.
