### ISSUE TITLE
[V4] Setting backButton icon wont hide the native back arrow 

### ISSUE THREAD

**Issue by ptfly** [wix/react-native-navigation#5697]
### Issue Description

Setting an `icon` to `backButton` doesn't hide the native back arrow

### Steps to Reproduce / Code Snippets / Screenshots

```js 
backButton: {
     color:'#758698',
     icon:require('./src/assets/icons/back.png')
},
```
<img width="363" alt="Screenshot 2019-11-29 at 10 06 38" src="https://user-images.githubusercontent.com/1925966/69853610-019edb00-1290-11ea-8de8-fcf6c7d722fa.png">

As you can see, it adds the image but does not hide the native one.

### Environment
* React Native Navigation version: 4.0.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device

**Comment by akahnn** [comment]
I'm on RNN `4.0.4` and can still reproduce this issue
