### ISSUE TITLE
Bottom tabs badge only showing after clicking on the tab

### ISSUE THREAD

**Issue by idanlo** [wix/react-native-navigation#5698]
### Issue Description
The badge icon for a tab in a bottomTabs layout only appears on the tab after the tab is clicked and the screen for that tab shows up.

### Steps to Reproduce / Code Snippets / Screenshots
1. Create a bottomTabs layout as your root.
2 Create more than 1 tab.
3. Put a badge on a tab (not the first as the first will work, because the tab is selected).
4. See that the badge does not appear, but will appear after you click the tab

---
### Environment
* React Native Navigation version: 4.0.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by robertgresogitl** [comment]
@idanlo have you somehow made it work? I am facing the same issue.. Thank you!

**Comment by aqweider** [comment]
@idanlo 

assign an id to the component
`{
      component: {
          id: 'componentId',
          name: 'componentName'
      }
 }`

then use mergeOptions
`     Navigation.mergeOptions('componentId', {
          bottomTab: {
            badgeColor: 'red',
            badge: '2'
          }
        });
      }`
