### ISSUE TITLE
How style rightButtons leftButtons

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#57]
How i can custom left, right button style? ex: margin

Thank you!

**Comment by InYourDreamz** [comment]
I'd like to know as well. The margins are always off when we're using custom icons.

**Comment by guyca** [comment]
@InYourDreamz Can you please add a screen shot? Are they misaligned on both platform?

**Comment by InYourDreamz** [comment]
Hi @guyca 

Here's how it looks like.

![custom_icon_margin](https://cloud.githubusercontent.com/assets/11990210/16104755/a28d6890-33b6-11e6-98cb-8ada69cb834a.png)

I'm not sure if @agumack is having this same issue?

**Comment by agumack** [comment]
yep @InYourDreamz 
large margin too bween 2 icons button. How I cant seting a custom style for icon?
Header title i want font-weight: nomar, too

**Comment by guyca** [comment]
@gran33 Can you please look into it? Thanks.

**Comment by InYourDreamz** [comment]
If it helps, the screenshots are taken on iPhone 5 simulator.

**Comment by rowellx68** [comment]
This appears to be the default behaviour of the NavBar.

![image](https://cloud.githubusercontent.com/assets/10155704/16197732/1d1a6710-36fb-11e6-80a5-8b457dee92a2.jpeg)

The app above is written n Objective-C, as you can see the custom icon on the right has a bit of an offset.

**Comment by InYourDreamz** [comment]
Ok, what about when there is two icon side by side? I'm assuming your screenshot was taken on a larger screen device.

**Comment by rowellx68** [comment]
Below is what a native navbar with two right icons look like. Used the iPhone 5S simulator.

![simulator](https://cloud.githubusercontent.com/assets/10155704/16362186/59b8afe4-3b9f-11e6-9e5a-82236d709759.png)

**Comment by janroures** [comment]
Hi @InYourDreamz , can you please tell me how did you remove the "Back" text from the button? Thank you very much.

**Comment by indivisable** [comment]
@janroures You can do this by setting backTitle='';

**Comment by SudoPlz** [comment]
Any news on that? Can we at least somehow change the fontFamily of the button? If so we could perhaps even use `react-native-vector-icons` for an icon, instead of an image.

**Comment by jolones** [comment]
I have a similar problem where using a company logo as the left button pins it to the left border. Was there any ever movement on the margin styling OP mentioned?

**Comment by miriyas** [comment]
Still no news ..

**Comment by SudoPlz** [comment]
You can't style it, but you can always use a Custom nav bar component with the `navBarCustomView`. That property was not a thing back when the issue first started.

**Comment by 6axter82** [comment]
Any news on this issue?

**Comment by keremcubuk** [comment]
I have same problem. I tried lots of things but I could not find a solution. Any news?

**Comment by SalviShahzad** [comment]
Hey, @stale, we are facing this issue in the latest version
