### ISSUE TITLE
How do I define the size of the icon in rightButtons?

### ISSUE THREAD

**Issue by luojinghui** [wix/react-native-navigation#570]
### Issue Description

I defined a share in the rightButtons png icon, but in android, the sharing of the icon is too small, how can I change his size, help, thank you

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version:  2.0.0
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android 6.0.1
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by guyca** [comment]
@luojinghui I think this is relevant https://github.com/wix/react-native-navigation/issues/43#issuecomment-267370982

**Comment by luojinghui** [comment]
@guyca 
Yes, I found the law, and then I tried a few sizes to adjust the size of btn, very grateful. I have a suggestion, because the document does not specify how to control the size of the icon, which makes a lot of beginners very confused, so you can add a note in the document. This is a very practical tip.
