### ISSUE TITLE
[v3] iOS Dark/Light Mode - Bottom Tabs w/Background Color

### ISSUE THREAD

**Issue by GioLogist** [wix/react-native-navigation#5701]
### Issue Description

iOS's Dark/Light mode effects styling in unpredictable ways.

### Steps to Reproduce / Code Snippets / Screenshots

Start a tab app, with the following style options.

```js
{
    bottomTab: {
      backgroundColor: '#fff',
      textColor: '#222',
      iconColor: '#222',
      selectedTextColor: '#251a7c',
      selectedIconColor: '#251a7c',
      fontFamily: 'Roboto',
    }
}
```

Dark mode enabled:

![image](https://user-images.githubusercontent.com/4120754/69907514-3479c980-138b-11ea-8f57-0948b681624a.png)

Dark mode disabled:

![image](https://user-images.githubusercontent.com/4120754/69907515-3d6a9b00-138b-11ea-8e0d-7802f2756c0d.png)

A couple of unexpected things happening here. First off, it seems to attempt to invert the background color, without doing so to the icon and text color. Which is inconsistent and makes for a rather unreadable UI. 

Also, imo, it would make more sense if we were able to explicitly define secondary colors for dark/light mode, as oppose to everything being arbitrarily inverted. Is this possible?

All around, I do think that the dark/light mode can be documented a bit better. Glad to help and make a PR, once i can get a better understanding myself.

---
### Environment
React Native Navigation version: 3.7.0
React Native version: 0.61.4
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug

**Comment by manuhook** [comment]
With RNN the bottom tab is automatically adapting to dark/light mode (on iOS and Android)
You can use
https://github.com/codemotionapps/react-native-dark-mode
or
https://github.com/expo/react-native-appearance
or wait for RN v6.2
to change colors accordingly to the color mode used on your phone (for bottom tab icons and other parts of your application)

**Comment by GioLogist** [comment]
> With RNN the bottom tab is automatically adapting to dark/light mode (on iOS and Android)

Yep, the issue is not that it's adapting the setting. The issue is that its doing so unpredictably and without a way to override. Even with your recommended packages, I'd have no way to implement the logic they provide with RNN.

**Comment by manuhook** [comment]
If you don't want the BottomTabs to adapt to the system dark/light setting, the only thing you can do for the moment with iOS is to add `User Interface Style: Light` to your Info.plist to disable it.

**Comment by GioLogist** [comment]
> If you don't want the BottomTabs to adapt to the system dark/light setting, the only thing you can do for the moment with iOS is to add User Interface Style: Light to your Info.plist to disable it.

Yea, trying to find alternatives here (even if for the future). For example, being able to configure styling for dark & light mode separately. So that we can properly utilize it.

**Comment by GioLogist** [comment]
@guyca sorry to keep tagging you. not sure who else is best to tag, to mark not stale.
