### ISSUE TITLE
StatusBar translucent causing TopBar cut off on Android

### ISSUE THREAD

**Issue by messense** [wix/react-native-navigation#571]
### Issue Description

Using `StatusBar` component to set `translucent` causing TopBar(I don't know if it is called `TopBar`) cut off on Android

### Steps to Reproduce / Code Snippets / Screenshots

![image](https://cloud.githubusercontent.com/assets/1556054/21211525/3e7ba2b6-c2bf-11e6-83bd-4168ea05f7b0.png)

---
### Environment
* React Native Navigation version: 2.0
* React Native version: 0.39
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Android 7.0 Debug

**Comment by guyca** [comment]
Thanks for reporting. If you only want to control the color of the status bar - you can set `statusBarColor: 'red'` in `navigatorStyle or `AppStyle`

**Comment by bluetec** [comment]
I have same issue with Experimental-300.
```navBarBackgroundColor: '#00A387',
        navBarTextColor: '#FFFFFF',
        navBarButtonColor: '#FFFFFF',
        navBarTranslucent: false,
        topBarElevationShadowEnabled: false,
        navBarTextFontFamily: 'IRANYekan',
        navBarTitleTextCentered: true,
        statusBarColor: '#00997d',```

navBarTranslucent is disabled, but TopBar is same as @messense screenshot.
How to fix this?

**Comment by guyca** [comment]
@bluetec Are you using [immersive mode](https://developer.android.com/training/system-ui/immersive.html)? rnn renders only below the status bar, please check if you have one of the immersive mode flags defined.

**Comment by bluetec** [comment]
@guyca thanks, a @Shoutem/Ui StatusBar component cause the issue, That's my fault. 👍

**Comment by guyca** [comment]
RNN is compatible with the status bar component, You can use `statusBarColor` instead. Hope that help.

**Comment by dev-two** [comment]
Actually, it would be great if you add support for translucent statusbar. It's actually very important part of material design, for example. Most of apps are using translucent status bar.

**Comment by jurajkrivda** [comment]
@dev-two you can use StatusBar from RN, `<StatusBar barStyle="light-content" backgroundColor="rgba(0, 0, 0, 0.60)" translucent />`

**Comment by xvonabur** [comment]
@jurajkrivda can you give an example? As far, as I understand, I need to disable built-in status bar with `statusBarHidden: true` and put `<StatusBar barStyle="light-content" backgroundColor="rgba(0, 0, 0, 0.60)" translucent />` on every screen, right?

Unfortunately, it doesn't work for me. The first screen is fine, but the second looses translucent status.

Here are the first screen:

<img width="81" alt="screen shot 2017-11-12 at 23 32 01" src="https://user-images.githubusercontent.com/616857/32703073-bb6c42c4-c801-11e7-8e6f-fe2fd530e748.png">

And here is the second:

<img width="89" alt="screen shot 2017-11-12 at 23 31 42" src="https://user-images.githubusercontent.com/616857/32703074-c5424a3c-c801-11e7-8270-bf35b98a99db.png">

Of course, I also need to add padding to the TopBar content...

**Comment by jurajkrivda** [comment]
My component wrapper

```
export default Component =>
  class extends React.Component {
    static navigatorStyle = {
      navBarTextColor: 'black',
      navBarTransparent: true,
      topBarElevationShadowEnabled: false,
    };


    render() {
      return (
        <View style={{flex:1}}>
          <StatusBar barStyle="dark-content" backgroundColor="transparent" />
          <Component { ...this.props } />
        </View>
      );
    }
  };
```

**Comment by xvonabur** [comment]
@jurajkrivda I have the similar code and it doesn't work for me (see screenshots above).

I have a HOC for all my screens:

```js
const navStyles = {
  navBarTextFontFamily: 'Roboto',
  navBarTextFontSize: 20,
  navBarBackgroundColor: Colors.teal600,
  navBarTextColor: '#fff',
  navBarButtonColor: 'white',
  topBarColor: Colors.teal600,
  backgroundColor: Colors.background,
  screenBackgroundColor: Colors.background,
  statusBarHidden: true
}

function applyTheme (WrappedComponent, customStyles = {}) {
  class ThemeHOC extends Component {
    static navigatorStyle = {
      ...navStyles,
      ...customStyles
    }

    render () {
      return (
        <ThemeProvider uiTheme={uiTheme}>
          <View style={{ flex: 1 }}>
            <CustomStatusBar />
            <WrappedComponent {...this.props} />
          </View>
        </ThemeProvider>
      )
    }
  }

  return hoistStatics(ThemeHOC, WrappedComponent)
}

export function registerScreens (store, Provider) {
  Navigation.registerComponent('myapp.About', () => applyTheme(AboutScreen), store, Provider),
  ...
}
```

In the App.js I called it like this:

```js
import { Provider } from 'react-redux'
import createStore from '../Redux'

const store = createStore()
registerScreens(store, Provider)
```

And my CustomStatusBar is:

```js
import React from 'react'
import { StatusBar, StyleSheet } from 'react-native'
import styles from './Styles/CustomStatusBarStyle'

export default class CustomStatusBar extends React.Component {
  render () {
    return (
      <StatusBar backgroundColor={StyleSheet.flatten(styles.container).backgroundColor}
        translucent
        animated />
    )
  }
}

```

I've tried removing `statusBarHidden: true`, but it doesn't help.

**Comment by dev-two** [comment]
@jurajkrivda it not works the way most of the users need. This should add padding on top, not overlay the header.

And actually, this problem could be solved in a terrible way by editing source code of the plugin.
