### ISSUE TITLE
iOS bottom tab issue

### ISSUE THREAD

**Issue by sm2017** [wix/react-native-navigation#5711]
### Issue Description

I have a bottom tabs , with different colors based on tab index (once first tab is active whole  bottom tabs is red , once first tab is active whole  bottom tabs is green) , in android everything is ok , but in iOS when I change tabs multiple times is loose right color , sometimes first/second tab is green/red wrongly

I have no `mergeOptions` in my codes , Just I have a single `Navigation.setRoot` and never change/merge it

### Steps to Reproduce / Code Snippets / Screenshots

```js
  Navigation.setRoot({
    root: {
      bottomTabs: {
        id: 'BOTTOM_TABS',
        children: [
          {
            stack: {
              children: [
                {
                  component: {
                    id: 'TAB_ONE',
                  },
                },
              ],
              options: {
                bottomTabs: {
                  backgroundColor: '#FF0000',
                },
                bottomTab: {
                  text: 'Tab 1',
                  icon: require('tab1.png'),
                },
              },
            },
          },
          {
            stack: {
              children: [
                {
                  component: {
                    id: 'TAB_TWO',
                  },
                },
              ],
              options: {
                bottomTabs: {
                  backgroundColor: '#00FF00',
                },
                bottomTab: {
                  text: 'Tab 2',
                  icon: require('tab2.png'),
                },
              },
            },
          },
        ],
        options: {
          bottomTabs: {
            titleDisplayMode: 'showWhenActive',
          },
        },
      },
    },
  });
```
---
### Environment
* React Native Navigation version: 4.0.2
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): both Simulator and Device , OS :10.15 , both  Debug and Release , XCODE 11.1

**Comment by sm2017** [comment]
Any idea?

**Comment by sm2017** [comment]
??????????????????????????

**Comment by vikaskhandekar001** [comment]
same issue here going to react navigation library
