### ISSUE TITLE
How to dynamically change all colors

### ISSUE THREAD

**Issue by sallar** [wix/react-native-navigation#5713]
### Issue Description

I want to react to system theme changes (on iOS 13) dynamically without making the user quit and reopen the app. Currently the tab bar and navbar background colors change automatically, but none of the text colors change. Is there a way to change all colors that were set using `Navigation.setDefaultOptions` on runtime?

I'm using RNN v4

**Comment by manuhook** [comment]
You can use RN hooks and mergeOptions

**Comment by sallar** [comment]
@manuhook I tried that. But using mergeOptions I can only change the “current” tab’s colors and not all tabs. Also I tried setting topBar.rightButtonColor using mergeOptions and that didn’t do anything as well.

**Comment by manuhook** [comment]
Yes you will not be able to update all your screens at once with mergeOptions but you can call it each time you are going to display one.
if your plan is to use dark mode you can use react-native-dark-mode, with hooks it's working great.
If your are not using hooks and don't want to go through mergeOptions, you can reload your app with react-native-restart and the color scheme you want.

**Comment by sallar** [comment]
I’m actually using hooks. But anyway I tried that and the button colors in the navBar don’t get updated. I can successfully change the tab color and background color of the layout, but not the button colors in navBar.

**Comment by a-eid** [comment]
it looks like you need to change the colors & then call `setRoot` again, however this seems to restart the app to the first screen on that root.

**Comment by MSchmidt** [comment]
Yes, setRoot is not a good solution. I'm also wondering what the recommended approach would be. Nothing in the docs about dark mode unfortunately.

**Comment by prateekpareekvyas** [comment]
+

**Comment by prateekpareekvyas** [comment]
+1
