### ISSUE TITLE
[V2][iOS] - Custom topBar component is not displayed in iOS devices / simulators.

### ISSUE THREAD

**Issue by emilioheinz** [wix/react-native-navigation#5716]
### Issue Description

I have a custom header in my app with the logo of my brand and I want to display it as the title, in Android by passing a custom component to the topBar title works but in iOS not.

### Steps to Reproduce / Code Snippets / Screenshots

When the app starts I'm setting as a default option the custom header:
```js
Navigation.setDefaultOptions({
      bottomTab: {
        iconColor: UNACTIVE_BOOTOM_TAB_COLOR,
        textColor: UNACTIVE_BOOTOM_TAB_COLOR,
        selectedIconColor: ACTIVE_BOTTOM_TAB_COLOR,
        selectedTextColor: ACTIVE_BOTTOM_TAB_COLOR,
      },
      bottomTabs: {
        titleDisplayMode: 'alwaysShow',
      },
      topBar: {
        title: {
          component: {
            name: 'customHeader',
            alignment: 'center',
          }
        }
      }
    });
```

Custom header component:
```js
import React from 'react'
import { View, Text  } from 'react-native'

import styles from './styles'

export function CustomHeader() {
  return (
    <View style={styles.container}>
      <Text>
        TITLE
      </Text>
    </View>
  )
}
```
The result in both devices:
![image](https://user-images.githubusercontent.com/47385105/69989060-9835fb00-1521-11ea-8949-ff81ca5d3f54.png)

---
### Environment
* React Native Navigation version: 2.27.5
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Happens in all iOS devices and simulators.

**Comment by emilioheinz** [comment]
That is not stale, still relevant.

**Comment by jinshin1013** [comment]
Would you be able to provide a reproduction? I'm able to use custom component for both iOS and Android. Although give this a quick try for your custom title component `container style`:

```tsx
container: {
  flex: 1,
  width: '100%'
}
```
