### ISSUE TITLE
[v3][v4] "Gesture Area" for pop is much less accessible than menus

### ISSUE THREAD

**Issue by GioLogist** [wix/react-native-navigation#5718]
### Issue Description

With side menus, I can begin swiping left to right from anywhere in the screen, which is what's expected and works perfect. With pop gesture, this isn't the case.

### Steps to Reproduce / Code Snippets / Screenshots

This can be reproduced in the playground. Visit "SideMenu". Notice how the gesture to open the menus can be started from any position (as is expected).

![output](https://user-images.githubusercontent.com/4120754/70025149-06de7d00-1551-11ea-9565-c5a744482b94.gif)

Now, visit Stack -> Push. Notice how the gesture only works if its started from the very edge of the screen (not as expected)

![output](https://user-images.githubusercontent.com/4120754/70025277-6b014100-1551-11ea-80ff-4ac59418941c.gif)

---
### Environment
* React Native Navigation version: 4.0.0
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Debug & Release

**Comment by GioLogist** [comment]
Not stale

**Comment by itsam** [comment]
I second that

**Comment by itsam** [comment]
This is a workaround https://gist.github.com/itsam/f33a063bf5f07ef7b4112e691f7edddc

**Comment by jhondavila** [comment]
hay alguna forma de indicar el area desde donde inicia el gesto para retroceder de pantalla...

**Comment by itsam** [comment]
you can replace MMOpenDrawerGestureModeAll with MMOpenDrawerGestureModeBezelPanningCenterView on the above gist

**Comment by GioLogist** [comment]
> This is a workaround https://gist.github.com/itsam/f33a063bf5f07ef7b4112e691f7edddc

Nice, good to know!

In the meantime, I still think this should be marked as not stale. cc @guyca
