### ISSUE TITLE
No known class method for selector 'systemBackgroundColor'

### ISSUE THREAD

**Issue by ravik2015** [wix/react-native-navigation#5719]
### Issue Description

No known class method for selector 'systemBackgroundColor'

### Steps to Reproduce / Code Snippets / Screenshots

 "react-native-navigation": "^4.0.3" is not working with  "react-native": "0.61.5" we are getting the following error while working with IOS
![Screen Shot 2019-12-03 at 3 22 11 PM](https://user-images.githubusercontent.com/26789619/70039951-b3b40b00-15e0-11ea-987f-5abcbf8323c7.png)

No known class method for selector 'systemBackgroundColor'

---
### Environment
* React Native Navigation version: "^4.0.3"
* React Native version: "0.61.5"
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device

**Comment by guyca** [comment]
Hey @ravik2015 
v4 requires Xcode 11 and does not support Xcode 10. This is the only breaking change in v4 and it's listed in the [changelog](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#ios) as well.
