### ISSUE TITLE
Android build failed due to react-native-navigation

### ISSUE THREAD

**Issue by vyky** [wix/react-native-navigation#572]
### Issue Description

Android build failed with following information:

```
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-navigation'.
   > failed to find target with hash string 'android-25' in: /Users/username/Library/Android/sdk
```

### Steps to Reproduce / Code Snippets / Screenshots

```
react-native run-android
```

---
### Environment
* React Native Navigation version: 2.0.0-experimental.155
* React Native version: 0.39.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Debug

**Comment by varungupta85** [comment]
You don't have the android support appcompat library v25. The easiest way to fix it would be to open the project in Android Studio which would point out that the library is missing and would give you a link to download and install it.
