### ISSUE TITLE
Small button area in navbar on ios

### ISSUE THREAD

**Issue by sorokin0andrey** [wix/react-native-navigation#5723]
### Issue Description

Small button area in navbar on ios. With real use cases, it’s very difficult to hit the button.

### Steps to Reproduce / Code Snippets / Screenshots

<img width="361" alt="Снимок экрана 2019-12-03 в 16 44 15" src="https://user-images.githubusercontent.com/3092044/70056538-af8dea80-15ec-11ea-9e24-137b9f8ca14f.png">

---
### Environment
* React Native Navigation version: 4.0.3
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All ios devices Debug, Release

**Comment by sorokin0andrey** [comment]
not stale

**Comment by sorokin0andrey** [comment]
Not stale

**Comment by bneigher** [comment]
not stale

**Comment by sorokin0andrey** [comment]
not stale

**Comment by sorokin0andrey** [comment]
not stale lol

**Comment by bneigher** [comment]
not stale.

FWIW - I have a post install patch that fixes the issue for me, its just annoying to have to make my own edits to this:  ./node_modules/react-native-navigation/lib/ios/RNNUIBarButtonItem.m

```objective-c
-(instancetype)init:(NSString*)buttonId withIcon:(UIImage*)iconImage {
  // UIButton* button = [[UIButton alloc] init];
  // [button addTarget:self action:@selector(onButtonPressed) forControlEvents:UIControlEventTouchUpInside];
  // [button setImage:iconImage forState:UIControlStateNormal];
  // [button setFrame:CGRectMake(0, 0, iconImage.size.width + 40, iconImage.size.height + 20)];
  // self = [super initWithCustomView:button];
  // self.buttonId = buttonId;
  // button.contentHorizontalAlignment = UIControlContentHorizontalAlignmentLeft;
  self = [super initWithImage:iconImage style:UIBarButtonItemStylePlain target:self action:@selector(onButtonPressed)];
  self.buttonId = buttonId;
  return self;
}
```

@sorokin0andrey lmk if this works for you and hopefully if its legit the wix team can get this changed in the source

**Comment by sorokin0andrey** [comment]
Not stale

**Comment by sorokin0andrey** [comment]
Not stale

**Comment by danilobuerger** [comment]
Duplicate of #5000 , PR at #6482
