### ISSUE TITLE
[v4] [v3] [android] currentTabIndex doesn't allow switching tabs

### ISSUE THREAD

**Issue by GioLogist** [wix/react-native-navigation#5724]
### Issue Description

With `currentTabIndex` set, Android does not allow changing tabs

### Steps to Reproduce / Code Snippets / Screenshots

```js
    // NOTE: Needs to be set via setDefaultOptions method, due to this issue:
    // https://github.com/wix/react-native-navigation/issues/5679
    Navigation.setDefaultOptions({
      bottomTabs: {
        currentTabIndex: 2,
      }
    })
```

For an example of the issue in playground:
https://github.com/GioLogist/react-native-navigation/tree/android-switching-currentTabIndex-enabled

---
### Environment
* React Native Navigation version: 4.0.3
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All of the above

**Comment by kabus202** [comment]
repeating issues to sad :(

**Comment by GioLogist** [comment]
This issue is not stale. @guyca had marked it as in progress.
