### ISSUE TITLE
Issue with iOS TouchID

### ISSUE THREAD

**Issue by sm2017** [wix/react-native-navigation#5727]
### Issue Description

react-native-navigation has an issue with iOS TouchID , I am using https://www.npmjs.com/package/expo-local-authentication package

When I trigger face id in `componentDidMount` , it opens but react-native-navigation unmount screen and mount new instance of current screen so  `componentDidMount` called again , and we have a infinite loop , it happens only on iOS , android is ok 

### Steps to Reproduce / Code Snippets / Screenshots

```js
class WelcomeScreen extends React.Component {
  async componentDidMount(){
    const results = await LocalAuthentication.authenticateAsync();
    console.log('results.success',results.success);
  }
  render() {
    return <h1>Hello</h1>;
  }
}
```

[FILL THIS OUT]

---
### Environment
React Native Navigation version: 4.0.2
React Native version: 0.61.4
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): both Simulator and Device , OS :10.15 , both Debug and Release , XCODE 11.1

**Comment by ItsNoHax** [comment]
Hi @sm2017 
I think this is most likely a problem in their package. I use a different library myself (https://github.com/hieuvp/react-native-fingerprint-scanner) and it works no problem.
