### ISSUE TITLE
Change UpperCase text on Top Navbar button

### ISSUE THREAD

**Issue by juddey** [wix/react-native-navigation#5729]
### Issue Description

Can Text in default Navigation TopBar be set to Sentence Case?

### Steps to Reproduce / Code Snippets / Screenshots
Heres my ShowModal Command: 
```js
    Navigation.showModal({
      stack: {
        children: [
          {
            component: {
              name: 'anapp.group_selection',
              options: {
                topBar: {
                  visible: true,
                  title: { text: 'Group Selection' },
                  rightButtons: [
                    {
                      id: 'done',
                      text: 'done',
                      color: Colors.blue,
                      fontFamily: 'Roboto',
                      fontWeight: 'regular'
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    })
```
I get this result:
![image](https://user-images.githubusercontent.com/7445602/70183059-f0e7dc80-1749-11ea-9269-2026e607e576.png)

Can the text of the "DONE" Button be set to "Done" (ie sentence case) _without_ using a custom component?

### Environment
* React Native Navigation version: 3.7
* React Native version: 0.61
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by juddey** [comment]
Not stale, Mr Bot.

**Comment by remstos** [comment]
This is still the case, not the only issue I've seen about this.
It seems impossible to not have an `uppercased` text topbar button without using a custom component.
Mr bot, can we reopen ?
