### ISSUE TITLE
SectionList not rendering correctly with drawBehind

### ISSUE THREAD

**Issue by jfrolich** [wix/react-native-navigation#5732]
### Issue Description

When a sectionList is part of a view with a `topBar` that has `drawBehind` set to true, the sections are rendered on the top of the screen behind the `topBar`. This might also be a bug in SectionList. It's not possible to manually offset because the `topBar` has a dynamic height.

![sectionListScroll](https://user-images.githubusercontent.com/579279/70217726-afbcf000-177c-11ea-9774-ba65c7c2d194.gif)

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 4.0.3-snapshot.618
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): 13.2.2

**Comment by jfrolich** [comment]
Still a bug

**Comment by jfrolich** [comment]
Not stale

**Comment by guyca** [comment]
@jfrolich Can you please reproduce this in the playground app? Thanks.

**Comment by jfrolich** [comment]
ok will try!
