### ISSUE TITLE
showModal Modal by default not fullscreen anymore on Tablets?

### ISSUE THREAD

**Issue by Pczek** [wix/react-native-navigation#5735]
### Issue Description

I've just updated from 3.7 to 4.0.3 and now my modals on iOS Tablets at least are not fullscreen anymore. It looks cool but not what I wanted. Not mentioned in the changelogs about this. Can I somehow force it to be fullscreen again or do I need to downgrade in order to fix it?

###  Screenshots

<img width="1139" alt="Screenshot 2019-12-05 at 15 12 58" src="https://user-images.githubusercontent.com/839848/70242909-f6f1b380-1771-11ea-892b-cf7ef5261a19.png">

### Environment
* React Native Navigation version: 4.0.3
* React Native version: 0.60
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPad 7th Gen

**Comment by jinshin1013** [comment]
You can add this option:

```tsx
modalPresentationStyle: 'fullscreen', // or OptionsModalPresentationStyle.fullScreen if TS
```

More info in the [doc](http://wix.github.io/react-native-navigation/#/docs/styling?id=common-options)

**Comment by guyca** [comment]
default modal presentation style has changed on iOS 13 👍
