### ISSUE TITLE
Android bottomTabs rendering blank on Android API 18/19

### ISSUE THREAD

**Issue by zzorba** [wix/react-native-navigation#5736]
### Issue Description

I did some recent upgrades of dependencies and have noticed that old versions of Android are getting blank bottom tabs. The tabs are still functional (i.e. I can tap the blank space where a button should be, and it transitions to the tab), but there's just no visuals rendered.

![image](https://user-images.githubusercontent.com/1091291/70263386-33b6ae00-1764-11ea-826a-bf602cf1c233.png)

Trying different simulators, this seems to only be happening on API versions < 21.  I've confirmed the behavior on both Jellybean (18) and KitKat(19).  JellyBean is basically dead, but KitKat still has 7% market share so would prefer not to lose these users.

### Steps to Reproduce / Code Snippets / Screenshots
Here's sample code, the icons are coming from 'react-native-svg-icons' (but converted to bitmaps before running this code and stored, as per the guide).  I'm seeing icons from the same font rendering elsewhere in the app, so I hope that is working.

```
const tabs = [{
      stack: {
        children: [browseCards],
        options: {
          bottomTab: {
            text: t`Cards`,
            icon: iconsMap.cards,
          },
        },
      },
    }, {
...
}];
Navigation.setDefaultOptions({
      topBar: {
        buttonColor: COLORS.lightBlue,
        background: {
          color: 'white',
        },
      },
      layout: {
        backgroundColor: 'white',
      },
      bottomsTabs: {
        elevation: 8,
      },
      bottomTab: {
        textColor: COLORS.darkGray,
        iconColor: COLORS.darkGray,
        selectedIconColor: COLORS.lightBlue,
        selectedTextColor: COLORS.lightBlue,
      },
    });
    Navigation.setRoot({
      root: {
        bottomTabs: {
          children: tabs,
        },
      },
    });
```

---
### Environment
* React Native Navigation version: 4.0.3
* React Native version: 0.61.5
* Platform(s)): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, confirmed to be broken on Android API 18/19 but working on API 21.

**Comment by guyca** [comment]
Hey there, API 18 and 19 are not supported.

**Comment by zzorba** [comment]
Thanks for the update, totally understand. 

I thought 19 might be supported based on the getting started docs, but maybe its' just out of date: https://wix.github.io/react-native-navigation/#/docs/Installing?id=_2-make-sure-you39re-using-the-new-gradle-plugin-edit-androidgradlewrappergradle-wrapperproperties
