### ISSUE TITLE
Title becomes very small if I specify 'fontWeight'

### ISSUE THREAD

**Issue by StasD** [wix/react-native-navigation#5739]
### Issue Description

Hi, After some recent updates, the title on iOS becomes very small if fontWeight is specified. (I have it set to 'bold', but the title gets small for any value of fontWeight, even 'Regular'.) Without fontWeight, size is OK.

### Steps to Reproduce / Code Snippets / Screenshots

```
    topBar: {
      visible: true,
      title: {
        color: '#ffffff',
        fontWeight: 'bold',
      },
     ...
     }
```

---
### Environment
* React Native Navigation version: 4.0.4
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, for now

**Comment by jinshin1013** [comment]
I can also reproduce the problem.

**Comment by StasD** [comment]
Fixed in https://github.com/wix/react-native-navigation/pull/5772
