### ISSUE TITLE
android navigator bug

### ISSUE THREAD

**Issue by charlesluo2014** [wix/react-native-navigation#574]
### Issue Description

1. add a button to the navbar right ，attach event to the button
2. click the button and push to a new screen。（tabbar hidden）
3. click the back button
4. click the other tabbar and come back to the page
5. click the button again but the push can not take effect。

### Steps to Reproduce / Code Snippets / Screenshots
 
---
### Environment
* React Native Navigation version:latest
* React Native version: 0.39.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):all

**Comment by guyca** [comment]
Hey @charlesluo2014 
`latest` (1.0.30) version isn't supported anymore. Read [here](https://github.com/wix/react-native-navigation#important) for more info.

I'm closing since we're not supported `latest`, you're welcome to upgrade to `next` version, we use it in production and it's stable.
