### ISSUE TITLE
[v3/v4] Cannot push to any screen after pop

### ISSUE THREAD

**Issue by alipiry** [wix/react-native-navigation#5740]
### Issue Description
I have a screen that includes some form stuff, so after form submission I do pop current screen and then push to another screen which causes an error.

Is there any solution for this issue?

### Steps to Reproduce / Code Snippets / Screenshots
```js
Error: Failed to execute stack command. Stack Component71 not found.
```
---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.61.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by kyle-ssg** [comment]
I've found this on Android when using an old API.

**Comment by alipiry** [comment]
> I've found this on Android when using an old API.

Actually, my project was using RNN v1, I'm facing this issue after migrating it to v3!

**Comment by alipiry** [comment]
### Issue Description
So to reproduce this issue, I've created a new RN project which uses RNN v4.
You can find out the issue yourself by running project below:

### Steps to Reproduce / Code Snippets / Screenshots
```js
> git clone git@github.com:alipiry/react-native-navigation-example.git
> cd react-native-navigation-example/
> yarn start
> yarn ios or yarn android 
```
In this example, we can push to a screen called `Other Screen`, then in the `Other Screen`, if you press `Go Back` button, first of all the Navigation should pop the current screen then push to `Other Screen` again but as you see it won't do such thing!
Related Code:
```js
const handlePopScreen = useCallback(() => {
    Navigation.pop(componentId);
    Navigation.push(componentId, {
      component: {
        name: 'Other',
      },
    });
  }, [componentId]);
```

in `iOS` platform, it doesn't do anything but in `Android` it causes an error which is: 
```js
Error: Failed to execute stack command. Stack Component3 not found.
```
---
### Environment
* React Native Navigation version: 4.0.4
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by alipiry** [comment]
@guyca please check this issue, tnx

**Comment by guyca** [comment]
Hey @alipiry 
You're trying to push a screen by passing the `componentId` of a component which has already been popped from the stack. This isn't possible as that component is detached and has no parent.

Give you stack an `id` and push using that id instead of using `componentId`.

```js
stack: {
  id: 'MyStack`,
  children: [
  ]
}

...
const handlePopScreen = useCallback(() => {
    Navigation.pop(componentId);
    Navigation.push('MyStack', {
      component: {
        name: 'Other',
      },
    });
  }, [componentId]);

```

**Comment by alipiry** [comment]
> Hey @alipiry
> You're trying to push a screen by passing the `componentId` of a component which has already been popped from the stack. This isn't possible as that component is detached and has no parent.
> 
> Give you stack an `id` and push using that id instead of using `componentId`.
> 
> ```js
> stack: {
>   id: 'MyStack`,
>   children: [
>   ]
> }
> 
> ...
> 
> const handlePopScreen = useCallback(() => {
>     Navigation.pop(componentId);
>     Navigation.push('MyStack', {
>       component: {
>         name: 'Other',
>       },
>     });
>   }, [componentId]);
> ```

Thnks a lot, but my app has 5 tabs which means it has 5 stacks!
How should I handle multiple stacks with your solution?

**Comment by guyca** [comment]
@alipiry Assign each stack a unique id; `homeStack`, 'profileStack`, `chatStack` etc
