### ISSUE TITLE
[V3/V4] Android <= 8.X show/hide overlay causes abnormal screen behavior

### ISSUE THREAD

**Issue by kyledmellander** [wix/react-native-navigation#5742]
### Issue Description

This issue only is occurring on Android <= version 8.x both in the simulator and on an app both in debug and release.

After showing/hiding an overlay, pushed screens no longer render correctly. The component exists and fetches it's data, but it doesn't get pushed visually over the correct tab. The screens reappear after pushing the app to the background, then reopening from the background. The code works on future versions of Android, and on IOS. 

Still working on making a smaller repro. We are using tab based navigation. 

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.showOverlay({ component: { name: 'example_overlay' } });
... later from the overlay
Navigation.dismissOverlay(componentId);
Navigation.push('STACK_ID', { component: { name: 'component_name' } });
``` 

---
### Environment
* React Native Navigation version: "^3.2.0",
* React Native version: "0.61.3"
* Platform(s) (iOS, Android, or both?): Android <= 8.x
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device. Release & Debug. Android <= 8.x.

**Comment by griarman** [comment]
same here

**Comment by guyca** [comment]
@kyledmellander Have you managed to make a reproduction? I'm investigating a similar issue and I think `statusBar.translucent: true` is causing issues on Android API <= 28

**Comment by tavour-frank** [comment]
@guyca Not sure that this is related to the `statusBar.translucent: true` bug you fixed
More specifically, the issue we run into is when we have a combination of bottom tabs and a side menu. If we open the side menu, pushing screens from the side menu results in a no-op.

[FWIW the playground currently has this scenario also broken](
https://imgur.com/jlBRT9V) - you can see in the webm the side menu push screens successfully when going SideMenu -> Open Left -> Push, but fail to push screens when going BottomTabs -> Tab 2 -> SideMenu inside BottomTabs -> Open Left -> Push, which matches the behavior we see in our app on android API <= 28

I had hoped to leverage the playground to put together a simple repro, but the SideMenu inside BottomTabs has the same behavior for both android api 28 and 29, so it's unclear that the specific issue is currently captured by the playground app. Going to dig in a bit more and try to come up with an example that repros on API 28 and not 29
