### ISSUE TITLE
Build failed on IOS for UIImage

### ISSUE THREAD

**Issue by aditya21** [wix/react-native-navigation#5746]
I have installed the library and completed all native linking process through CocoaPods. Now, I am getting error if try to build the on Xcode. 

node_modules/react-native-navigation/lib/ios/UIImage+tint.m:7:16 No visible @interface for 'UIImage' declares the selector 'imageWithTintColor:renderingMode:'

react-native-cli: 2.0.1
react-native: 0.61.5
Xcode Version 10.1 (10B61)

**Comment by ItsNoHax** [comment]
react-native-navigation V4 requires you to have XCode 11. If you NEED to use Xcode 10, please use V3 of the library.

**Comment by ZeeshanAhmadKhalil** [comment]
What Xcode version is required if I am using rn 5?
