### ISSUE TITLE
While trying to initialize the app i get this error

### ISSUE THREAD

**Issue by prince4moha** [wix/react-native-navigation#575]
![untitled](https://cloud.githubusercontent.com/assets/9276573/21297492/285a3326-c58a-11e6-9870-ec537e0fd9f6.png)

**Comment by guyca** [comment]
What RNN version are you using?

**Comment by prince4moha** [comment]
Version 0.39

**Comment by guyca** [comment]
RNN not RN

**Comment by prince4moha** [comment]
^1.0.30

**Comment by guyca** [comment]
1.0.30 is not supported. Please upgrade to `next` as stated in the [readme](https://github.com/wix/react-native-navigation#important)
