### ISSUE TITLE
global componentDidAppear listener cancels listener for a specific screen

### ISSUE THREAD

**Issue by idanlo** [wix/react-native-navigation#5750]
### Issue Description
In our app we have a global `componentDidAppear` listener on our redux store to have an updated `componentId` globally. We also created a `useComponentDidAppear` hook that creates a `componentDidAppear` event listener and calls a function (in order to focus inputs etc).
The global listener works but then the listener for that screen doesn't work, and when I delete the global listener then the listener for that screen does work.

Since there is no `componentDidAppear` for a specific screen (they are both global but one of them only takes action on a certain `componentId`), the issue may be that there can't be more than 1 `componentDidAppear` listener at the same time

### Steps to Reproduce / Code Snippets / Screenshots
1. create `componentDidAppear` listener on your App.js file
2. create `componentDidAppear` listener on a specific screen
3. the listener for the screen will not work but the global listener will work

### Environment
* React Native Navigation version: 4.0.4
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all devices

**Comment by smn-snkl** [comment]
@idanlo did you solve the issue? Having the same problem ...
