### ISSUE TITLE
Random white screen on launch iOS

### ISSUE THREAD

**Issue by damandeepsingh93** [wix/react-native-navigation#5753]
### Issue Description

We are getting the random white screen issue on app launch. It tries to start the "Splash" component but gets stuck on white screen. Its very random. Happens only on iOS.

### Steps to Reproduce / Code Snippets / Screenshots
I am attaching the video and logs along with it
[ios_white_screen_issue.log](https://github.com/wix/react-native-navigation/files/3944265/ios_white_screen_issue.log)
Video - https://we.tl/t-z1U6zL3ACj

---
### Environment
* React Native Navigation version: 4.0.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6s 13.2 Release

**Comment by beingArkReal** [comment]
I'm also facing the same issue on both ios and android.

**Comment by ItsNoHax** [comment]
@damandeepsingh93 Can you please provide the video in a .gif format?

**Comment by damandeepsingh93** [comment]
> @damandeepsingh93 Can you please provide the video in a .gif format?

![Uploading ezgif.com-video-to-gif.gif…]()

**Comment by avichopra1989** [comment]
I am facing the same issue on iOS. Can you please get the resolution for this?

**Comment by Neeraj-111** [comment]
I'm also facing the same issue on iOS devices. I thought I was going mad, glad it's not just me.
I can confirm that it's still in 0.61.5

**Comment by damandeepsingh93** [comment]
Any update, Can somebody please look into this.
Even tried using RAM bundles.

**Comment by beingArkReal** [comment]
I'm currently on 4.8 and this issue still persists.

**Comment by dooleyb1** [comment]
Similar issue here on `"react-native-navigation": "4.3.0"` and `"react-native": "^0.59.10"`. Attempting to run app on iPhone 7 with Debug configuration. Works fine if ran through XCode but when ran via command line screen hangs on white before splash screen and then crashes.

**Comment by kirantripathi** [comment]
still facing the same issue randomly, did anyone find the solution for this?
