### ISSUE TITLE
[V4] iOS crash when reload if you have overlays

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#5761]
If your app have overlay, after reload, app will be crashed
The problem is in RNNOverlayManager.m
`- (void)dismissAllOverlays {
    for (RNNOverlayWindow* overlayWindow  in _overlayWindows) {
        [self detachOverlayWindow:overlayWindow];
    }
}`
When app receive notify reload, it will dismiss all overlay, but, the code is running loop in "enumerate" the "mutable array"
We should fix to this
`- (void)dismissAllOverlays {
    NSArray *_immutableArray=[NSArray arrayWithArray:_overlayWindows];
    for (RNNOverlayWindow* overlayWindow  in _immutableArray) {
        [self detachOverlayWindow:overlayWindow];
    }
}`

* React Native Navigation version: 4.0.4
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): iOS

**Comment by bneigher** [comment]
Damn I was wondering why this started happening (just updated from an older 3.x.x to most recent)
