### ISSUE TITLE
In version `4.0.5`, the rendering of the title component in TopBar gets delayed.

### ISSUE THREAD

**Issue by StasD** [wix/react-native-navigation#5762]
### Issue Description

TopBar gets buggier with each new version...
I started using a component with `alignment: 'fill'` to display a title, because of various issues with simple text title. (e.g. https://github.com/wix/react-native-navigation/issues/5739)
But now, in version `4.0.5`, the rendering of the title component in TopBar gets delayed significantly (probably until `componentDidMount` of the screen component finishes).
It is OK in version 4.0.4 to which I reverted.

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: 4.0.5 (OK in 4.0.4)
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both, iOS 13.3, Both

**Comment by ItsNoHax** [comment]
Hi @StasD , we are currently trying to track down all the iOS regressions from the latest updates. Could you please provide some reproduction code or screenshots/gifs that display your issue.

**Comment by StasD** [comment]
Here are the urls of screen recordings:
[4.0.4 (OK)](https://stas-ie.s3-eu-west-1.amazonaws.com/public/Screen_Recording_2019-12-13_at_22.02.14.mov)
[4.0.5 (Bad)](https://stas-ie.s3-eu-west-1.amazonaws.com/public/Screen_Recording_2019-12-13_at_22.07.34.mov)

Title is the component with this code:
```javascript
function TopBarTitle() {
  return props => (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text style={styles.topbartitletext} numberOfLines={1}>
        {props.title}
      </Text>
    </View>
  );
}

Navigation.registerComponent('TopBarTitle', TopBarTitle);
```

Used with `alignment: 'fill'`, as mentined before. Also, I had to use 'dummy' left or right buttons when they were not needed in order to center it on screen... As if I use `alignment: 'center'`, then long title goes behind other buttons...

**Comment by ItsNoHax** [comment]
@StasD Great thank you! This will help a lot to further investigate the issue.

**Comment by guisuzuki-ene** [comment]
Any clue? In Android i have the same issue, the title component is the last to render and this create a bad UX.
