### ISSUE TITLE
[v4.0.5] Topbar not showing if set custom fontFamily

### ISSUE THREAD

**Issue by blueberry6401** [wix/react-native-navigation#5765]
### Issue Description

In v4.0.5, if topBar title is set with fontFamily, it will be disappear on iOS.
Workaround fix: specify fontSize to title.
v4.0.3 working fine.

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by ItsNoHax** [comment]
Hi @blueberry6401 , we are aware of the iOS bugs in the latest release and are busy trying to track them all down. Could you please provide some reproduction code/screenshots so the dev can pick this up faster?

**Comment by blueberry6401** [comment]
This is reproduction code,  just set custom fontFamily on any topBar title

```
static options() {
    return {
      topBar: {
        testID: WELCOME_SCREEN_HEADER,
        title: {
          text: 'React Native Navigation',
          fontFamily: 'Copperplate',
          // fontSize: 18, // Uncomment this line to bring title back
        }
      }
    };
  }
```
| Without fontSize  | With fontSize |
| ------------- | ------------- |
| ![Screen Shot 2019-12-13 at 18 03 39](https://user-images.githubusercontent.com/7337535/70795717-0e184d00-1dd3-11ea-822a-af5fd28c1000.png)  | ![Screen Shot 2019-12-13 at 18 04 27](https://user-images.githubusercontent.com/7337535/70795722-12dd0100-1dd3-11ea-9804-d416875d6a43.png) |
