### ISSUE TITLE
[iOS] Stacked modals get dismissed automatically

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#5767]
### Issue Description

When updating from 4.0.3 to 4.0.5 we have ran into some regression when using several modals over each other.

### Steps to Reproduce / Code Snippets / Screenshots

Open 3 modals on top of each other and the last one opened will automatically close.
Most our modals used modalPresentationStyle: overFullScreen but even when removing the modalPresentationStyle it still happens.

![2019-12-13 11 16 13](https://user-images.githubusercontent.com/4223434/70793997-ec9c6e80-1d9c-11ea-9e22-c11263a468eb.gif)

---
### Environment
* React Native Navigation version: 4.0.5
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by yogevbd** [comment]
@ItsNoHax Can you please reproduce it in the playground app? I didn't manage to reproduce it there

**Comment by ItsNoHax** [comment]
Can't seem to reproduce anymore with the latest version of RNN so going to close this.
