### ISSUE TITLE
Question: Is it possible to dynamically change navigator buttons

### ISSUE THREAD

**Issue by Kdoherty11** [wix/react-native-navigation#577]
I have a screen with a `ListView` and a "Edit" nav button. When I press the Edit button, I want the button's text to change from "Edit" to "Done". 

I have only read how to set the nav buttons using a static variable or by overriding them when pushing a screen. Is this possible?

**Comment by brianjd** [comment]
```
this.props.navigator.setButtons({
  leftButtons: [], // see "Adding buttons to the navigator" below for format (optional)
  rightButtons: [], // see "Adding buttons to the navigator" below for format (optional)
  animated: true // does the change have transition animation or does it happen immediately (optional)
});
```

Read more here, [Screen API](https://github.com/wix/react-native-navigation/wiki/Screen-API#setbuttonsparams--).

**Comment by Kdoherty11** [comment]
Thanks! Sorry I wasn't looking in the right place in the docs.
