### ISSUE TITLE
Android  Navigation.setRoot bug

### ISSUE THREAD

**Issue by sm2017** [wix/react-native-navigation#5770]
### Issue Description

When app is in foreground and  I press power button , app state will changes to background
Sometimes `Navigation.setRoot` has bug in this situation

We I call `Navigation.setRoot` , in 10% of cases , It set two root (I think), that means I have two instance of `My_COMPONENT` , because I have a `componentDidAppear` listener in `My_COMPONENT` after  `Navigation.setRoot` it calls twice 

### Steps to Reproduce / Code Snippets / Screenshots

```js

AppState.addEventListener('change', handleAppStateChange);

handleAppStateChange = (nextAppState )=>{
if (nextAppState === 'background') {
 Navigation.setRoot({
    root: {
      stack: {
        children: [
          {
            component: {
              name:'My_COMPONENT'
            },
          },
        ],
      },
    },
  });
}
}
```

---
### Environment
React Native Navigation version: 4.0.2
React Native version: 0.61.4
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): both Simulator and Device , OS :10.15 , both Debug and Release , XCODE 11.1

**Comment by ItsNoHax** [comment]
I don't think it's a safe assumption to set root off a change listener. This seems like it will be riddled with bugs.

Either ways I'm going to close this issue as it seems that you are not running into a RNN issue. It sounds like your code is the problem here.

**Comment by sm2017** [comment]
@ItsNoHax I have to change root , let me explain
I have a passcode lock screen, once apps goes to background I must reset stack to passcode lock, and force user to enter password at foreground
I donr reset in forground because it has a small delay
