### ISSUE TITLE
Problem with react-native-reanimated

### ISSUE THREAD

**Issue by LahmerIlyas** [wix/react-native-navigation#5771]
### Issue Description

Hi, I'm porting my code from react-navigation to react-native-navigation, but I'm facing a problem when trying to import react-native-reanimated.

### Steps to Reproduce / Code Snippets / Screenshots
# HomeScreen.ts
```js                                                         
import Animated from 'react-native-reanimated';
class HomeScreen extends Component {
    render() {
        return (
            <View><Text>Home Screen</Text></View>
        );
    }
}
 ```                    
                                      
# package.json
```js                                                         
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.3",
    "lodash": "^4.17.15",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-navigation": "^4.0.3",
    "react-native-navigation-hooks": "^3.3.1",
    "react-native-reanimated": "^1.4.0",
    "react-native-vector-icons": "^6.6.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3"
  },

}
 ```                                                          

 The error is 
 * TypeError: null is not an object(evaluating ' ReanimatedModule.default.configureProps')
---
### Environment
* React Native Navigation version: ^4.0.3
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both Simulator and Samsung device OS version OREO Debug Mode

**Comment by ismailharmanda** [comment]
> ### Issue Description
> Hi, I'm porting my code from react-navigation to react-native-navigation, but I'm facing a problem when trying to import react-native-reanimated.
> 
> ### Steps to Reproduce / Code Snippets / Screenshots
> # HomeScreen.ts
> ```js
> import Animated from 'react-native-reanimated';
> class HomeScreen extends Component {
>     render() {
>         return (
>             <View><Text>Home Screen</Text></View>
>         );
>     }
> }
> ```
> 
> # package.json
> ```js
>   "dependencies": {
>     "@react-native-community/async-storage": "^1.6.3",
>     "lodash": "^4.17.15",
>     "react": "16.9.0",
>     "react-native": "0.61.5",
>     "react-native-gesture-handler": "^1.5.2",
>     "react-native-navigation": "^4.0.3",
>     "react-native-navigation-hooks": "^3.3.1",
>     "react-native-reanimated": "^1.4.0",
>     "react-native-vector-icons": "^6.6.0",
>     "react-redux": "^7.1.3",
>     "redux": "^4.0.4",
>     "redux-persist": "^6.0.0",
>     "redux-saga": "^1.1.3"
>   },
> 
> }
> ```
> 
> The error is
> 
> * TypeError: null is not an object(evaluating ' ReanimatedModule.default.configureProps')
> 
> ### Environment
> * React Native Navigation version: ^4.0.3
> * React Native version: 0.61.5
> * Platform(s) (iOS, Android, or both?): Android
> * Device info (Simulator/Device? OS version? Debug/Release?): Both Simulator and Samsung device OS version OREO Debug Mode

Hi, did u solve this problem?:)
