### ISSUE TITLE
Larget Title Background Color [V4][iOS]

### ISSUE THREAD

**Issue by captaincole** [wix/react-native-navigation#5779]
### Issue Description

Large Title ignores color attribute, and it also takes the background of whatever layout.backgroundColor attribute is set. 

The most recent update allowed me to set the fontWeight of the largeTitle, and I have not seen an issue with a small title and large title showing up after upgrading to 4.0.6. 

I found a much older similar issue to this by @mohammadalijf 

### Expected Behaviour

I expected the largeTitle background color to follow the background color I specified in the topBar attributes (rgba(60,60,60,70))

### Steps to Reproduce / Code Snippets / Screenshots

```js    
const defaultOptions = {
  layout: {
    backgroundColor: 'rgba(60,60,60,70)', // This will now be the color of the largeTitle...
  },
  statusBar: {
    style: 'light',
  },
  topBar: {
    visible: true,
    color: 'white',
    background: {
      color: 'rgba(60,60,60,70)',
    },
    noBorder: false,
    title: {
      color: 'white',
      fontFamily: 'Avenir Next',
      fontWeight: 'bold',
      fontSize: 18,
    },
    largeTitle: {
      color: 'white',
      fontSize: 30,
      fontFamily: 'Avenir Next',
      fontWeight: 'bold',
    },
  },
};
```

<img width="423" alt="Screen Shot 2019-12-15 at 9 33 06 PM" src="https://user-images.githubusercontent.com/7246257/70881958-17e0b280-1f83-11ea-9203-1b871e066f32.png">
                                                                                                  
### Environment
* React Native Navigation version: 4.0.6
* React Native version: 0.61.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iOS 13, iPhone 11 Pro

**Comment by Fawxy** [comment]
I've also just run into this issue - can't seem to change the background colour from black when largeTitle is visible.

**Comment by Fawxy** [comment]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/9826062/70957708-d7487c80-20db-11ea-8cd1-4ce1914b8611.png">
<img width="255" alt="image" src="https://user-images.githubusercontent.com/9826062/70957720-e0d1e480-20db-11ea-8c80-c5aa0668b240.png">

As you can see the UIBarBackground color is nil

**Comment by ChristianKuhn** [comment]
Having the same problem.

**Comment by haneul512** [comment]
having the same issue as well

**Comment by captaincole** [comment]
@Fawxy Thanks, I might use that to take a stab at fixing this myself. But don't hold me to it, I haven't written a ton of react-native-navigation PRs.

**Comment by jayrylan** [comment]
@stale this issue is still relevant.

**Comment by wfilleman** [comment]
Same here. We can't upgrade past 4.0.4. Using LargeTitles on iOS results in a black header on all versions past 4.0.4.

**Comment by jarne** [comment]
Might this issue be related to this commit https://github.com/wix/react-native-navigation/commit/60f836e8a875534e1f40b02807f1902bdc2c6887 (@yogevbd @guyca)? As this commit was shortly after version 4.0.4, "Remove main window backgroundColor" is mentioned there and some TopBar background color functions are removed in this commit. Just a guess, wasn't able to investigate deeper 😉

**Comment by blueberry6401** [comment]
So is there any solution?

**Comment by yogevbd** [comment]
I found that `topBar.drawBehind: true` solves this.
```js
topBar: {
  largeTitle: {
    visible: true
  },
  drawBehind: true
}
```

**Comment by korre** [comment]
> I found that `topBar.drawBehind: true` solves this.
> 
> ```js
> topBar: {
>   largeTitle: {
>     visible: true
>   },
>   drawBehind: true
> }
> ```

Does it really? What happens when adding this property is that the large title background color is not drawn at all? It gets transparent.

`topBar: {
            background: {
                color: '#00ff00'
              },
              largeTitle: {
                visible: true,
                
              },
              drawBehind: true
          }`

When having this setup I expect the top bar to have the background color: #00ff00 in large and small title mode and on android as well. Now it's transparent in large title mode and gets the correct color on small title mode and on android. Is that a correct behaviour?

**Comment by yogevbd** [comment]
@korre This is not the correct behaviour. I'm currently working on adding largeTitle background color support.
