### ISSUE TITLE
Background color of topBar is dark grey, even though it's set to 'transparent' (iOS 12)

### ISSUE THREAD

**Issue by timjuenemann** [wix/react-native-navigation#5785]
### Issue Description

Background color of topBar is dark grey, even though it's set to 'transparent' (iOS 12)

### Steps to Reproduce / Code Snippets / Screenshots

```
options: {
    ...
    topBar: {
      drawBehind: true,
      noBorder: true,
      borderHeight: 0,
      elevation: 0,
      background: {
        color: 'transparent',
      },
      leftButtonColor: '#000',
      rightButtonColor: '#000',
      backButton: {
        color: '#000',
      },
    },
    ...
  },
```

![Simulator Screen Shot - iPhone 5s - 2019-12-17 at 16 58 41](https://user-images.githubusercontent.com/14848797/71011898-82623180-20ee-11ea-941f-ae00a2690724.png)

---
### Environment
* React Native Navigation version: 4.0.6
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS 12.4
* Device info (Simulator/Device? OS version? Debug/Release?): On iPhone 5S with iOS 12.4

**Comment by manuhook** [comment]
Fixed on 4.0.7 =)

**Comment by manuhook** [comment]
Hmm in fact it's not completly fixed,
on iOS 12 with 4.0.8 when you push a screen with a topbar transparent it's fine
but if you pop on a screen with a topbar transparent, the topbar is becoming black

**Comment by yogevbd** [comment]
Fixed in https://github.com/wix/react-native-navigation/commit/2ad41f3adb9883fa20f1d52fcbbc6fd0750976f9
