### ISSUE TITLE
ipad does not respect layout orientation setting

### ISSUE THREAD

**Issue by peterh32** [wix/react-native-navigation#5786]
Most of the screens in my app are portrait-only. However I have an image viewer screen that I want to be able to flip orientation. 

So in `Info.plist` I allow switching:
```
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
```

...but then restrict it on individual screens using layout:
```
	layout: {
		orientation: ['portrait'],
	},
```

This works on iphone but on ipad, the layout spec is ignored and all pages in the app flip portrait/landscape.

### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

### Workaround
Thanks to https://stackoverflow.com/questions/29664441/different-device-orientation-according-to-device-iphone-or-ipad/29686990#29686990 -- add an ipad-only key to Info.plist:

```
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>

```

**Comment by chrise86** [comment]
@peterh32 did you manage to resolve this? Still seems like an issue to me.
