### ISSUE TITLE
[Question] Present a bottom-sheet on top of the app tab bar

### ISSUE THREAD

**Issue by oferRounds** [wix/react-native-navigation#5789]
### Issue Description

Trying to to use [`react-native-reanimated-bottom-sheet`](https://github.com/osdnk/react-native-reanimated-bottom-sheet) to present a bottom-sheet. Our app is a tab-based, and using V1. Our problem is that the bottom-sheet is presented beneath the tab-bar, and we’d like to present it on top of it (when it opens)

I apoplogize for asking a V1 related question - wondering if there is an option to place a component in general outside the tab screen context (our "app.js" class, which initiates our tabs. is not a component)

We can upgrade to v3, but the question is if this possible in general, and specifically in V1?

Thank you very much for this great library, we really enjoy it!

### Steps to Reproduce / Code Snippets / Screenshots
Use the [bottom-sheet](https://github.com/osdnk/react-native-reanimated-bottom-sheet) inside tab-component

---
### Environment
* React Native Navigation version: v1
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): iOS (perhaps also Android, haven’t check yet)
* Device info (Simulator/Device? OS version? Debug/Release?): All iOS devices, all envs

**Comment by guyca** [comment]
Hey @oferRounds 
You might be able to hack the `LightBox` component for that - but I really can't guarantee any results.
In v2 we've introduced an `Overlay` component, suitable for these needs. It allows you to place a component on top of all other screens.

I'm closing since there's really not much we can assist here.

**Comment by oferRounds** [comment]
@guyca makes sense, got you! thank you for the answer!

**Comment by oferRounds** [comment]
@guyca do you think it could be possible to achieve a bottom sheet behaviour  using the `Overlay` API? Alternatively, how would you approach it?

**Comment by guyca** [comment]
Sure - just show your component in an Overlay and that's it. An Overlay can either block touch events outside of the view or let touch events pass through.

**Comment by oferRounds** [comment]
Got you, thank you very much once again!
