### ISSUE TITLE
ANDROID: White screen after launch app from push notification (app in background)

### ISSUE THREAD

**Issue by MatthewPattell** [wix/react-native-navigation#5792]
### Issue Description

1. Run app on android and go to background mode.
2. Send push notification with key "notification" (e.g. firebase console)
3. Click on notification in status bar.
4. App open with white (clear) screen.

If app is killed or foreground, running from notification working correctly.

P.S.: If remove key "notification" from fcm message, all works correctly.

[GIF Example](https://s5.gifyu.com/images/untitled303137edf65b1500.gif)

Before:
![image](https://user-images.githubusercontent.com/10459911/71154028-ad15cc80-224b-11ea-8f51-c72e4f53733f.png)
After (app open via push notification):
![image](https://user-images.githubusercontent.com/10459911/71154110-d9314d80-224b-11ea-9417-9f26280056dd.png)

---
### Environment
* React Native Navigation version:  4.0.6
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Emulator - Pixel 2 API 28

**Comment by RobertPaul01** [comment]
Are you registering app launched with `Navigation.events().registerAppLaunchedListener(..)`?

**Comment by MatthewPattell** [comment]
@MatthewPattell yes. App work correctly in other cases.

**Comment by RobertPaul01** [comment]
@MatthewPattell I see. I ran into this issue with universal links when not having `Navigation.events().registerAppLaunchedListener(..)` the first thing called during app startup.

Also, I had to add `Linking.getInitialURL().then(handleUniversalLink);` to the `Navigation.events().registerAppLaunchedListener(..)` callback

**Comment by MatthewPattell** [comment]
> @MatthewPattell I see. I ran into this issue with universal links when not having `Navigation.events().registerAppLaunchedListener(..)` the first thing called during app startup.
> 
> Also, I had to add `Linking.getInitialURL().then(handleUniversalLink);` to the `Navigation.events().registerAppLaunchedListener(..)` callback

I have ```Navigation.events().registerAppLaunchedListener(..)``` and it [called first](https://wix.github.io/react-native-navigation/#/docs/Installing?id=you-can-use-react-native-navigation-o).

**Comment by Kezmo** [comment]
Does anybody have an update on this? Currently on v7.2.0 and this is happening to me when opening a push notification from a closed app.

**Comment by AlphaJuliettOmega** [comment]
@Kezmo same here.

```
// Register AppLaunched Listener as early as possible.
Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot(x);
});

// Bootstrap navigation.
Navigation.setDefaultOptions(y);
```

In my case it seems that the `setDefaultOptions` does not apply if the app is launched from a Push Notification :(

Not sure how to debug yet

**Comment by mahmood** [comment]
call Navigation.setDefaultOptions(y); inside Navigation.events().registerAppLaunchedListener that fixes issue for me.
