### ISSUE TITLE
[v4] React Native 0.62.0-rc.0

### ISSUE THREAD

**Issue by safaiyeh** [wix/react-native-navigation#5794]
### Issue Description

Upgraded to 0.62.0-rc.0. `react-native-navigation` does not compile on Android.

```
error: cannot find symbol class NativeDeltaClient 
```
is thrown with reactNative60

62 rc discussion: https://github.com/react-native-community/releases/issues/145
### Steps to Reproduce / Code Snippets / Screenshots

1. Upgrade to 0.62.0-rc.0
2. Build android project
3. errors thrown
---
### Environment
* React Native Navigation version: ^4.0.4
* React Native version: 0.62.0-rc.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator. Debug

**Comment by safaiyeh** [comment]
A quick check looks like `com.facebook.react.bridge.NativeDeltaClient` was removed.

https://github.com/facebook/react-native/tree/master/ReactAndroid/src/main/java/com/facebook/react/bridge

**Comment by ItsNoHax** [comment]
Hi @safaiyeh ,

RN 0.62 support has already been planned and will be worked on further on in this year.
Going to leave this issue open for people who are looking to update their own app to RN 0.62.

**Comment by ItsNoHax** [comment]
Closing since 0.62 support has recently been merged! :+1:

**Comment by ideerge** [comment]
what? what's the conclusion?

**Comment by guyca** [comment]
@ideerge RNN supports 0.62

**Comment by harshitsmt** [comment]
Hi ! Does RNN supports 0.63?

**Comment by jinshin1013** [comment]
Hi @harshitsmt it sure does! Check out our Playground app 😃
