### ISSUE TITLE
[V4] Right buttons of top bar aren't touchable occasionally

### ISSUE THREAD

**Issue by Tradex1234** [wix/react-native-navigation#5796]
### Issue Description

Sometimes, the right buttons on the top bar aren't touchable when I open the app. Even I switch to another screen by navigation, and display another right buttons, but the right button cannot come back to work again. 

If I turn off the application and turn on again, it will be back to normal. It happens very rarely, just few times over hundred of tests

---
### Environment
* React Native Navigation version: 4.0.5
* React Native version: 0.61.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Release mode

**Comment by ItsNoHax** [comment]
Hi @Tradex1234 , which Android OS version are you seeing this on?

**Comment by Tradex1234** [comment]
@ItsNoHax Android OS is Android 9
