### ISSUE TITLE
Top Tabs

### ISSUE THREAD

**Issue by kevinkhagan** [wix/react-native-navigation#5798]
### Issue Description

Hi, please how do I setup TopTabs in React Native Navigation.

---
### Environment
* React Native Navigation version:  "4.0.4"
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by jinshin1013** [comment]
Are you in the right place? This repo is `react-native-navigation`

**Comment by vtuppala** [comment]
does this library support top tabs?
