### ISSUE TITLE
navigation buttons tint color

### ISSUE THREAD

**Issue by ethanshar** [wix/react-native-navigation#58]
allow controlling icons and text buttons tint color, and allow to remove tint (for icons buttons).

**Comment by willks** [comment]
@ethanshar Does this also include colours for buttons with "disabled" state? Mine default to "gray" when in disabled state, and I need to have them in a shade lighter. I can do a pull request to address the disabled state buttons, after I clean up the ObjC (I'm not an ObjC nor Swift Dev so code will look green)

**Comment by Andreyco** [comment]
I did this by setting tint color app wide in AppDelegate.m

**Comment by guyca** [comment]
@gran33 This is supported on Android by setting these in `navigatorStyle`
```
buttonsTint: '#FFFFFF',
titleColor: '#FFFFFF'
```

**Comment by gran33** [comment]
@ethanshar, I added this property (iOS only), u can use it like this:
```
rightButtons: [
            {
              icon: require('./img/star.png'),
              disableIconTint: true,
              onPress: function() {
              AlertIOS.alert('Button', 'Edit pressed');
              }
            }
          ]
```
