### ISSUE TITLE
Topbar animation not working

### ISSUE THREAD

**Issue by AnilNewari** [wix/react-native-navigation#5804]
I just added react native navigation default options but Topbar animation is not working with remaining screen content. 

Navigation.setDefaultOptions({
  topBar: {
    animate: true <--- this is not working
  },
  animations: {
    push: {
      waitForRender: true,
      enabled: true,
      content: {
        x: {
          from: 400, //500
          to: 0,
          duration: 200,
          interpolation: "accelerate" //decelerate
        }
      }
    },
    pop: {
      waitForRender: true,
      enabled: true,
      content: {
        x: {
          from: 0,
          to: 400, //500
          duration: 200
        }
      }
    }
  }
});

 Environment
* React Native Navigation version: 4.0.9
* React Native version: 0.61.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android device

**Comment by vovka-s** [comment]
Faced with same issue. Any decisions?

**Comment by manuhook** [comment]
For some reason you have to always explicitly set topbar enabled:true for it to animate, content you don't.

`    animations: {
      push: {
        waitForRender: Platform.select({ios: false, android: true}),
        enabled: true,
        topBar: {
          enabled: true,
          alpha: {
            from: 0,
            to: 1,
            duration: 200,
            interpolation: 'decelerate',
          },
        },
      },
    },`

**Comment by vovka-s** [comment]
This is my code.
Attribute `enabled` is set to `true` for all parts of screen.
Nonetheless content animated perfectly, but topBar isn't animated at all
```
const ANIMATIONS = {
    APPEARING: {
        RIGHT_TO_LEFT: {
            enabled: true,
            x: {
                from: 1000,
                to: 0,
                duration: 300,
                startDelay: 300,
                interpolation: 'decelerate'
            },
        },
    },
    DISMISSING: {
        LEFT_TO_RIGHT: {
            enabled: true,
            x: {
                from: 0,
                to: 1000,
                duration: 300,
                startDelay: 300,
                interpolation: 'decelerate'
            },
        },
    },
};
            Navigation.setDefaultOptions({
                topBar: {
                    animate: true,
                    background: {
                        color: '#f7f7f7'
                    },
                },
                bottomTabs: {
                    animate: false,
                    backgroundColor: '#f7f7f7',
                    titleDisplayMode: 'alwaysHide',
                },
                bottomTab: {
                    iconColor: '#a7a7a7',
                    selectedIconColor: '#00b7f0',
                },
                animations: {
                    push: {
                        enabled: true,
                        topBar: ANIMATIONS.APPEARING.RIGHT_TO_LEFT,
                        content: ANIMATIONS.APPEARING.RIGHT_TO_LEFT,
                    },
                    pop: {
                        enabled: true,
                        topBar: ANIMATIONS.DISMISSING.LEFT_TO_RIGHT,
                        content: ANIMATIONS.DISMISSING.LEFT_TO_RIGHT,
                    },
                },
            });
```

**Comment by manuhook** [comment]
Today topbar is animated "only" when topbar visibility is changing from false to true.
Once toolbar is visible you don't have animations between push

**Comment by vovka-s** [comment]
Wow! It is interesting. Thank you!
