### ISSUE TITLE
Unable to build release on Windows 10 due to  MD5 hash for file content

### ISSUE THREAD

**Issue by kelvin-dev** [wix/react-native-navigation#5806]
We're interested in your latest release, we just cloned the source and evaluate the performance but it doesnt work. Please help investigate our system info and build logs:
Tons of thanks,

D:\Demos\react-native-navigation\playground\android>react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 3.68 GB / 15.83 GB
  Binaries:
    Node: 8.14.0 - D:\Program Files\nodejs8\node.EXE
    npm: 6.4.1 - D:\Roaming\npm\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.2, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1
      System Images: android-22 | Google APIs ARM EABI v7a, android-23 | Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-25 | Google APIs ARM 64 v8a
      Android NDK: 18.1.5063045
...
Build logs * after run "> npm install install-android"
> Configure project :react-native-view-overflow
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.2.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Failed to create MD5 hash for file content.

**Comment by ItsNoHax** [comment]
Hi @kelvin-dev,

I'm afraid this issue is not clear at all. There is very little information for us to even start helping you. 
I'm going to go ahead and close this issue for now to avoid clutter. Feel free to update or create a new issue when you have more descriptive information.
