### ISSUE TITLE
[v4] iOS 13 - componentDidAppear event no longer fired after modal close

### ISSUE THREAD

**Issue by Collin3** [wix/react-native-navigation#5808]
### Issue Description

If you use the new form sheet iOS 13 modals, the `componentDidAppear` event does not get fired on modal close for the underlying screen. If you switch the modal to be a full screen modal, then the `componentDidAppear` event will work as expected for the underlying screen.

### Steps to Reproduce / Code Snippets / Screenshots

1. Run an app on an iOS 13 simulator
1. Add a `componentDidAppear` event to your root screen and put a log statement in there.
1. Open a modal from your root screen (use the default iOS 13 modal that is NOT a full screen modal)
1. Close the modal (by swiping or tapping the close button) and see that your log statement never got logged because the `componentDidAppear` event never got triggered.

If you repeat steps 1-4 using a full screen modal instead of the default sheet modal you WILL get a the log statement to log out.

---
### Environment
* React Native Navigation version: 4.0.6
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Any iOS 13 simulator or device on both Debug and Release

**Comment by ItsNoHax** [comment]
@yogevbd Is this expected behavior with the new type of modals? If not we can mark it as a bug.

**Comment by yogevbd** [comment]
This is how lifecycle works in the new iOS 13 pageSheet modals. The underlying component never actually disappear. You can listen to modal dismissed event instead.
