### ISSUE TITLE
RNN.ScreenPopped is no supported event type for RNNEventEmitter.

### ISSUE THREAD

**Issue by Sbarcenas** [wix/react-native-navigation#5809]
### RNN.ScreenPopped is no supported event type for RNNEventEmitter.

I Just update RNN to last versión
![Captura de Pantalla 2019-12-27 a la(s) 12 04 43 p  m](https://user-images.githubusercontent.com/23620536/71525725-15465d00-28a1-11ea-8f2d-db0ea2c8824d.png)

**Comment by jinshin1013** [comment]
Have you ran `pod install` or `yarn ios` again? It seems like npm package is updated but haven't updated the native version.

**Comment by cspicuzza** [comment]
`pod install` didn't fix this error for me

**Comment by odesey** [comment]
Same issue as @jinshin1013 

Tried the following:

` rm -rf node_modules`
`yarn`
`cd ios && pod install && cd ..`
`yarn ios`

Had to downgrade to version `~3` in order to get rid of the error message

React-Native Version: **`0.61.2`**
React Version: **`16.9.0`**
React Native Navigation Version (causes error):  **`4.1.0`**, this version works:  **`3.2.0-snapshot.537`**

**Comment by jinshin1013** [comment]
I can confirm that the latest react-native-navigation version does not cause this error. Try the following:

```bash
# 1. Stop all processes of metro

# 2. Delete node_modules
rm -rf node_modules

# 3. Install node_modules
yarn

# 4. Install Pod
cd ios && pod install && cd ..

# 5. Start metro
yarn start # most likely have forgotten to stop and re-run the metro again.

# 6. Run ios and android
yarn ios 
yarn android
```

**Comment by guyca** [comment]
Thanks @jinshin1013 👍 
this error indicates there's a mismatch between native and js versions - npm install, pod install and recompile and it should work.

**Comment by cspicuzza** [comment]
I'm running:
RN 0.6.5
RNN 4.2.0

Removing node modules, `yarn install`, `pod install`, is not fixing the error for me.   Anyone else still having this error come up?

**Comment by odesey** [comment]
Finally got it to work, here is what I had to do:
`stop bundler ... CTRL + C`
`rm -rf node_modules`
`rm -rf ios/build`
**`** Update RNN to version 4.x now in your package.json file **`**
`yarn`
`cd ios && pod update ReactNativeNavigation --no-repo-update`
` pod install && cd ..`
**`** start bundler again **`**,  `yarn start`
`yarn ios`

Hopefully this helps anyone who was having this issue.

**Comment by ptfly** [comment]
A simple `pod update && pod install` should do the trick.

**Comment by guibas741** [comment]
I am facing the same problem, but only when I run `react-native run-ios` on the command line, if I run the project at Xcode it works fine.

**Comment by cspicuzza** [comment]
@ptfly that resolved my issue, thanks!

**Comment by mamoru0217** [comment]
I solve this problem by deleting files in `~/Library/Developer/Xcode/DerivedData`.
Maybe remaining module cache causes a problem.

```
renact-native-navigation 6.3.1
react-native 0.61.5
```

**Comment by lkwjohn** [comment]
Facing the same issue from react-native run-ios but is fine from Xcode. The above solutions didn't work for me.

renact-native-navigation 6.9.0
react-native 0.60.6
