### ISSUE TITLE
startTabBasedApp in use process, TAB can only load the first

### ISSUE THREAD

**Issue by usergyt** [wix/react-native-navigation#581]
### Issue Description

 startTabBasedApp in use process, TAB I can only load the first, because the second page is called camera,Special slow operation. what's the solution?

### Steps to Reproduce / Code Snippets / Screenshots

  Navigation.startTabBasedApp({
    tabs: [
      {
        label: 'home',
        screen: 'shop.Home',
        icon: require('Almond/res/images/btn_home.png'),
        selectedIcon: require('Almond/res/images/btn_home_hover.png'),
        title: 'home',
      },
      {
        label: 'scan',  //Here to open the camera
        screen: 'shop.Barcode',
        icon: require('Almond/res/images/btn_scan.png'),
        title: 'scan',
       }
      ...
---

**Comment by guyca** [comment]
We will add screen lifecycle callbacks soon, you'd be able to use those to determine when a screen is visible or not. Then you could show to camera only when the screen/bottom tab is actually displayed.

**Comment by usergyt** [comment]
thanks

**Comment by godlevel** [comment]
@guyca how long before the lifecycle callbacks will be available, is there a workaround available now?
