### ISSUE TITLE
Fab position under the bottomtab when change tab.

### ISSUE THREAD

**Issue by suupham2506** [wix/react-native-navigation#5816]
### Issue Description

[ENTER DESCRIPTION HERE]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: ^4.0.9
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): not show on IOS and incorrect position on android when change tab.
* Device info (Simulator/Device? OS version? Debug/Release?): 
![Screenshot_1577723152](https://user-images.githubusercontent.com/28852565/71590748-43a39100-2b5c-11ea-8ff8-656858ade215.png)
![Screenshot_1577723147](https://user-images.githubusercontent.com/28852565/71590749-43a39100-2b5c-11ea-8d6b-04018c05c32e.png)

FILL THIS OUT

**Comment by charpeni** [comment]
We're experiencing the same bug with react-native-navigation@4.0.6.

To add more details to the issue, while using a FAB with BottomTabs, on tab changed, the FAB will move back to the bottom of the screen for a fraction of a second, the move back to its expected location.

Introduced in https://github.com/wix/react-native-navigation/commit/47149835dcf707806bb211230e63a61d8cf9a1d5 (cc @guyca), I'm not sure what would be the best way to fix this yet.

**Comment by charpeni** [comment]
@guyca @yogevbd We're still experiencing this within the latest release, can we reopen this?

I have no clues about what's going on, do you?

<img height="600" src="https://user-images.githubusercontent.com/7189823/82225375-1ed56d80-98f3-11ea-97f9-f76e091f3115.gif" />
