### ISSUE TITLE
Way to remove the ugly effect on bottomTabs in Android?

### ISSUE THREAD

**Issue by msqar** [wix/react-native-navigation#5818]
### Issue Description
Is there a way to remove the ugly icon mini-zoom and bubble effect it does when any bottomTabs button is pressed? This only happens on Android, iOS doesn't do that. I'm guessing is the normal default Android behaviour, but is there a way to remove it completely?

Thanks. 

### Environment
* React Native Navigation version: 3.7.0
* React Native version: 0.60.6
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Debug & Release

**Comment by MakhouT** [comment]
You are looking for this
https://wix.github.io/react-native-navigation/#/docs/styling?id=android-specific-options

```
  bottomTabs: {
    elevation: 8, // BottomTabs elevation in dp
    titleDisplayMode: 'alwaysShow' | 'showWhenActive' | 'alwaysHide' // Sets the title state for each tab.
  },```

**Comment by msqar** [comment]
I will check @MakhouT whenever i get home and close the ticket if solved. Thanks. I hope we are talking about the same thing (effect). I hate that effect so bad haha.

**Comment by msqar** [comment]
@MakhouT I tested what you suggested but still, doing the same visual effects when pressed. This is how that part looks like atm:

```
const startTabs = () => {
    Navigation.setRoot({
        root: {
            bottomTabs: {
                animate: true,
                visible: false,
                drawBehind: true,
                waitForRender: true,
                options: {
                    bottomTabs: {
                        animate: false,  // <- i even added this one just in case, but not doing anything
                        elevation: 8,
                        titleDisplayMode: 'alwaysShow',
                        backgroundColor: commonStyles.WHITE
                    }
                },
                children: [
                    {
                        stack: {
                            children: [
```

Am i doing it right? Thanks in advance.

**Comment by msqar** [comment]
Still waiting on a way to handle this.

**Comment by drewhamlett** [comment]
```js
  Navigation.setDefaultOptions({
    layout: {
      backgroundColor: getColor('grays.1'),
    },

    bottomTabs: {
      // backgroundColor: getColor('white'),
      tabsAttachMode: 'onSwitchToTab',
      ...Platform.select({
        android: {
          titleDisplayMode: 'alwaysShow',
          // elevation: 60,
        },
      }),
    }

```

**Comment by msqar** [comment]
@drewhamlett thanks, i will test it out in a few hours. But i'm already using the alwaysShow title, it only keeps the title visible, but the fontSize keeps increasing in size, pushing the icon up. That was the effect I wanted to remove. But I guess is not possible yet.

**Comment by remstos** [comment]
@msqar Have you found any way to remove this effect?

**Comment by guyca** [comment]
@msqar @remstos You can set the `fontSize` and `selectedFontSize` to be the same value. This will effectively prevent the font size animation.

```js
options: {
  bottomTabs: {
    titleDisplayMode: 'alwaysShow'
  },
  bottomTab: {
    fontSize: 14,
    selectedFontSize: 14
  }
}
 ```

**Comment by remstos** [comment]
Thanks for this @guyca , unfortunately the icon still moves up a little bit on selection

**Comment by msqar** [comment]
@remstos exactly, and there's a bubble animation when you tap on the icons, that grows and changes opacity

**Comment by saad277** [comment]
thanks @hyunminyoo worked great

**Comment by boxxyapp** [comment]
> @msqar @remstos You can set the `fontSize` and `selectedFontSize` to be the same value. This will effectively prevent the font size animation.
> 
> ```js
> options: {
>   bottomTabs: {
>     titleDisplayMode: 'alwaysShow'
>   },
>   bottomTab: {
>     fontSize: 14,
>     selectedFontSize: 14
>   }
> }
> ```

this worked well, didnt get rid if the animation but lowered the effect a lot, i think the best way is to move from wix to react native navigation.
