### ISSUE TITLE
onPress event of element in non-active bottom tab getting called on Android

### ISSUE THREAD

**Issue by asaharan** [wix/react-native-navigation#5828]
### Issue Description
When I click on chip on the top of Tests section, onPress event is called for items in Analysis tab and Practice, sometimes on elements of Practice tab and sometimes on elements of Analysis tab.

Complete view of Tests tab is rendered by one "Native UI Component" which I have created.

### Steps to Reproduce / Code Snippets / Screenshots
<img width="311" alt="Screenshot 2020-01-06 at 11 17 32 AM" src="https://user-images.githubusercontent.com/11248242/71797945-30ba2080-3076-11ea-96d0-ed520041a8ae.png">
<img width="316" alt="Screenshot 2020-01-06 at 11 23 19 AM" src="https://user-images.githubusercontent.com/11248242/71798133-f8ffa880-3076-11ea-8abe-9fa4cb0a34c4.png">

This is how I have rendered my Native UI Component.

components/TestList.js
```js
import React from 'react';
import {requireNativeComponent, View} from 'react-native';

const TestList = requireNativeComponent('TestList');

const TestListWrapper = props => {
	const {tabs} = props;
	return <TestList tabs={tabs} style={{height: '100%'}} />;
};

export default TestListWrapper;
```

screens/Tests.js
```js
import React, {useEffect} from 'react';
import {SafeAreaView, Text} from 'react-native';
import {useDispatch, useSelector} from 'react-redux';
import {getSelectedSubscription} from '../utils/user';
import {getList} from '../redux/actions/assessmentList';
import TestList from '../components/TestList';
import {getTabs} from '../utils/assessmentList';

const Tests = () => {
	const tabs = useSelector(getTabs);
	return (
		<SafeAreaView>
			{Array.isArray(tabs) && tabs.length ? (
				<TestList tabs={tabs} />
			) : (
				<Text>Loading data</Text>
			)}
		</SafeAreaView>
	);
};

export default Tests;
```

---
### Environment
* React Native Navigation version: 4.1.0
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Pixel 3, Android 10, Debug Mode

**Comment by ItsNoHax** [comment]
Hi @asaharan ,

For us to help you further with this issue we need you to provide a reproducible example using the playground app. Please fork this project, create a branch with a clear reproducible example and link it here.

**Comment by asaharan** [comment]
Hi @ItsNoHax ,

I have created the example here: https://github.com/asaharan/react-native-navigation-bug-report.

Here is the video showing this bug in the example app.
