### ISSUE TITLE
CodePush installation for iOS

### ISSUE THREAD

**Issue by benjaminb10** [wix/react-native-navigation#584]
Hi,
To install CodePush http://codepush.tools we need to have a Root component to call sync() at initialisation of the index.ios.js.

With react-native-navigation, I don't have a root component. How can I modify my code to have a root component, then using react-native-navigation ?

**Comment by sogko** [comment]
Hi @benjaminb10 

We're using CodePush with `react-native-navigation` as well. 

Actually you don't need the Root component to set up CodePush. You can call `CodePush.sync()` manually in `componentDidMount()` or `onPress()` button event for example.

See: https://github.com/Microsoft/react-native-code-push#plugin-usage
> Alternatively, if you want fine-grained control over when the check happens (e.g. a button press or timer interval), you can call CodePush.sync() at any time with your desired SyncOptions, and optionally turn off CodePush's automatic checking by specifying a manual checkFrequency:

We can share how we got it working currently, hopefully it starts a discussion for a better way to integrate CodePush + react-native-navigation.

```javascript
...
class HomeScreen extends Component {
  componentDidMount() {
    // setup CodePush
    CodePush.sync({
     ...,
     installMode: CodePush.InstallMode.ON_NEXT_RESUME // CodePush iOS only seems to work with this mode, ON_NEXT_RESUME. Will look for original issue later for reference.
    }, ...);
  }
  ...
}

// Register screen
Navigation.registerComponent("HomeScreen", () => HomeScreen);

// Start screen
Navigation.startSingleScreenApp({
  screen: {
    screen: "HomeScreen"
  }
});

```

Hope this helps!

**Comment by benjaminb10** [comment]
The problem is that I want to use others modes than ON_NEXT_RESUME...

**Comment by vedovato** [comment]
This method you mentioned works fine in Android, @sogko but it doesn't in iOS. What happens is that iOS get the previous app version when you close and open the app again. Did you get this too?

**Comment by grigored** [comment]
Here's my fix for rnn and codepush: https://github.com/Microsoft/react-native-code-push/issues/875 works with any install method
