### ISSUE TITLE
[v4][IOS] waitForRender doesn't work

### ISSUE THREAD

**Issue by sintylapse** [wix/react-native-navigation#5845]
### Issue Description
Starting from version 3.1.0 waitForRender stopped working on IOS. Just add backgroundColor to all screens in playground app and you will notice white flickering on the right side of a screen for a few millisecond inside new incoming screen

![Screen-Recording-2020-01-12-at-2](https://user-images.githubusercontent.com/12295016/72225367-d5b48c00-3595-11ea-862b-cac7447fb731.gif)

### Steps to Reproduce / Code Snippets / Screenshots
Add waitForRender
```
Navigation.setDefaultOptions({
    animations: {
        push: {
            waitForRender: true,
        },
        setStackRoot: {
            waitForRender: true,
        },
    },
})
```
And push a new screen. Reproducible in playground app https://github.com/sintylapse/react-native-navigation/tree/wait-for-render-is-broken-ios the only change is - added green backgroundColor to `playground/src/components/Root.js` component

---
### Environment
* React Native Navigation version: 4.4.0
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device, Debug/Release

**Comment by sintylapse** [comment]
https://github.com/wix/react-native-navigation/issues/5871

**Comment by sintylapse** [comment]
Seems that issue is gone in [V5](https://github.com/wix/react-native-navigation/issues/5904) @guyca

**Comment by guyca** [comment]
@sintylapse Thank for reporting! 🙇
