### ISSUE TITLE
[V4] the color of bottom tabs becomes black when pushing and popping screen

### ISSUE THREAD

**Issue by giftset** [wix/react-native-navigation#5848]
### Issue Description

[ENTER DESCRIPTION HERE]
the color of bottom tabs becomes black when pushing and popping screen under the option of toggling visibility of bottom tabs.

It didn't happen when i was using V3.

Is there anyone who has this issue?

### Steps to Reproduce / Code Snippets / Screenshots

bottomTabs: {
            titleDisplayMode: "alwaysShow", // android,
            backgroundColor: "white",
            translucent: true,
            barStyle: "default",
            animate: false,
            drawBehind: true}
this is my option of setRoot Fn

[]

---
### Environment
* React Native Navigation version: 4.5.0
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Real devices

**Comment by jonyuen** [comment]
We are experiencing this as well... one "fix" is to change the background color of the window in your AppDelegate.m.

We have it set as black because it matches our view when the app initially loads up, but since the rest of the app has a white background it becomes jarring when a user pushes a screen.

Is it possibly to programmatically change the window background color after your app is loaded?

**Comment by vjtc0n** [comment]
@jonyuen I think the issue is drawBehind: true is not working if the tab is not the initial tab.
It causes "Black" because the bottomTabs dissapears too soon.
I set the window UI background white but it's still black...

**Comment by guyca** [comment]
@vjtc0n This is resolved in 6.0.0

You have two options to resolve this issue.
1. Add a background color to the BottomTabs layout. This way, when the bottomTabs are toggled you won't see a black flickering (you're actually seeing the window behind the layout who's color is black)
2. Draw the root child (the child that's displayed with bottomTabs.visible) behind the bottomTabs. It should also have a SafeAreaView or a ScrollView as it's root View as both of these views inset content so its not hidden behind the BottomTabs.

The first option is the easiest and you'll affectively have the same behavior as before iOS 13. The second option will look much better and is the correct approach.
