### ISSUE TITLE
0.61.5 React Native Navigation

### ISSUE THREAD

**Issue by pm02446** [wix/react-native-navigation#5852]
### Issue Description

I can not get the navigation feature to work, keeps telling me 
it is no longer supported

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: 4.0.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by sintylapse** [comment]
Work fine for me with RN 0.61.5 and RNN ^4.4.0, both platforms

**Comment by pm02446** [comment]
problem was solved, I need to down load something and it works prefect now. Thanks for all the help.

**Comment by ItsNoHax** [comment]
Closing this as it seems the issue has been solved. I can also confirm RNN works fine with RN 0.61.5

**Comment by CrisangerA** [comment]
## How to resolve this?
you could leave a link or at least an idea of how you solved it?
Thanks
