### ISSUE TITLE
[V4][Android] White screen on pop after setStackRoot

### ISSUE THREAD

**Issue by sintylapse** [wix/react-native-navigation#5854]
### Issue Description

White screen appears for a moment on pop after setStackRoot, even with waitForRender

![Screen Recording 2020-01-18 at 14 48 32](https://user-images.githubusercontent.com/12295016/72663846-197d1a80-3a08-11ea-8939-2f9ca0bbe82b.gif)

### Steps to Reproduce / Code Snippets / Screenshots

Add waitForRender then use setStackRoot with two screens then pop to first screen and you will see white screen for a moment. Reproducible in playground app - https://github.com/sintylapse/react-native-navigation/tree/white-screen-on-pop-after-setstackroot . The only changes are: added green background to root component, added waitForRender for setStackRoot

---
### Environment
* React Native Navigation version: 4.4.0
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device, Debug/Release

**Comment by fbaralle** [comment]
Hi, im facing the same issue when navigating between tabs, and using the side drawer. Did anyone could solve this? It's really annoying and my apps uses a dark theme, so the effect is even worse

**Comment by fbaralle** [comment]
I have a similar issue, can anyone help? I publish the details in this thread.
@guyca any idea of what is happening?
[https://github.com/react-navigation/react-navigation/issues/7084#issuecomment-634130909](url)

**Comment by trantus** [comment]
any solutions?

**Comment by fbaralle** [comment]
@trantus Not yet. I stopped working on that app beacuse of my current job, but I think I'll finish it in the next few months even if this issue is not fixed.

**Comment by guyca** [comment]
FIxed in [6.7.0](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#android-4) in a1beebe74beb265ed196e9e322a85aa40b84aa98
