### ISSUE TITLE
Use an image as background / custom nav bar ?

### ISSUE THREAD

**Issue by ajonno** [wix/react-native-navigation#586]
### Issue Description
Is it possible to use an image as background on the nav bar (ios and droid) ? Also use custom image Here's a couple examples of what we need (ios / droid):

![image](https://cloud.githubusercontent.com/assets/3005269/21386660/fb51b42c-c7c7-11e6-896b-32fb1883a7b4.png)

![image](https://cloud.githubusercontent.com/assets/3005269/21386758/7abf9166-c7c8-11e6-91da-b907d9ec95c1.png)

---
### Environment
* React Native Navigation version: v2
* React Native version: 0.39.0
* Platform(s) (iOS, Android, or both?): both

**Comment by guyca** [comment]
Sure.
You can add the following properties to your `navigatorStyle`
```js
static const navigatorStyle = {
  drawUnderNavBar: true,
navBarTransparent: true
};
```

and draw your `TopBar` background as part of your screen

**Comment by ajonno** [comment]
Many thanks! Sorry but we're new to your api - when you say "..and draw your TopBar background as part of your screen " what do you mean? Is TopBar a component we should use and then within that component place background image etc? If you had an example that would be great but regardless if you could clarify would be much appreciated.

**Comment by guyca** [comment]
@ajonno I guess I wasn't clear enough.
This behavior isn't really supported. But as a quick workaround, what you can do is set two parameters that will render your components (screens) behind the `TopBar` (aka Toolbar, navBar), then just draw a `<View />` with that nice image as a background color behind the `TopBar`.

That being said, this doesn't really feel like a native app. On Android, material guidelines strongly advise against this. Maybe ask your designers to rethink this design?

https://material.io/guidelines/layout/structure.html#structure-app-bar
