### ISSUE TITLE
[v4] Invalid UIModalPresentationStyle

### ISSUE THREAD

**Issue by amorino** [wix/react-native-navigation#5866]
### Issue Description
At creating a Root with Bottom Tabs, I got the following error: 
```
Invalid UIModalPresentationStyle 'default'
should be one of: (
formSheet,
fullScreen,
overFullScreen,
pageSheet
)
``` 

### Steps to Reproduce / Code Snippets / Screenshots

```js
 Navigation.setRoot({
        root: {
          bottomTabs: {
            children: [
              {
                stack: {
                  children: [
                    {
                      component: {
                        name: 'Page 1',
                      },
                    },
                  ],
                  options: {
                    bottomTab: {
                      fontSize: 12,
                      text: 'Home',
                      icon: require('../static/image/tabbar/home_icon.png'),
                    },
                  },
                },
              },
              {
                component: {
                  name: 'Page 2',
                  options: {
                    bottomTab: {
                      fontSize: 12,
                      text: 'Trips',
                      icon: require('../static/image/tabbar/my_trips_icon.png'),
                    },
                  },
                },
              },
            ],
          },
        },
      });
``` 
![Simulator Screen Shot - iPhone X - 2020-01-21 at 18 28 20](https://user-images.githubusercontent.com/1342805/72855043-d3c88800-3c7b-11ea-966c-e74cc99f053e.png)

---
### Environment
* React Native Navigation version:  4.4.0
* React Native version:  0.59.10
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X 12.4, Debug

**Comment by jinshin1013** [comment]
It looks like your local version of `react-native-navigation` does not match the native version. You have most likely forgotten to run `pod install`.

**Comment by amorino** [comment]
I'm using manual linking

**Comment by ItsNoHax** [comment]
I believe this is a problem in RN, instead of RNN, I can use all types of modalPresentationStyles using RN 0.61.5

**Comment by jgtorrejon** [comment]
Same here, made an upgrade to RN@0.60.0, RNN@4.5.3 and keep the manual link.

**Comment by jgtorrejon** [comment]
Solved by added the next line on defaults:

`modalPresentationStyle: 'fullScreen'`

@jinshin1013 probably should mark this as required on docs, because the last version don't recognize the 'default' option as valid.

**Comment by ItsNoHax** [comment]
@jgtorrejon Have you tried using RN 0.61.5? I'm pretty sure this is not a RNN problem but a RN problem.

**Comment by Yassir4** [comment]
Solved with this [quick fix](https://github.com/wix/react-native-navigation/issues/4603#issuecomment-471528960)

**Comment by jinshin1013** [comment]
If you are using Cocoapods to link packages, you can remove the manual linking.
