### ISSUE TITLE
[V4] Regression "Flash" on launch after Splash screen.

### ISSUE THREAD

**Issue by jfrolich** [wix/react-native-navigation#5871]
### Issue Description

In 4.0.5 a regression is introduced that causes a noticeable flash of the background before showing the component (right after the splash screen disappears). I tried many different versions and it was introduced in 4.0.5 while still working in 4.0.4.

### Steps to Reproduce / Code Snippets / Screenshots

See  above

---
### Environment
* React Native Navigation version: between 4.0.5
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Any

**Comment by guyca** [comment]
@jfrolich Are you using `waitForRender` when calling `setRoot` ? I assume the background image is an `<Image>` component set in JSX, right?

**Comment by jfrolich** [comment]
Yes I'm using `waitForRender`. There is indeed an image in the background (from the native asset catalog).

**Comment by guyca** [comment]
@yogevbd `waitForRender` seems to have broke in recent versions, any chance it's already fixed in v5?

**Comment by yogevbd** [comment]
Not sure, will check.

**Comment by guyca** [comment]
@jfrolich This should be fixed in v5, could you please update and let us know if the issue persists? Thanks.

**Comment by jfrolich** [comment]
Confirmed that 5.0 works.

**Comment by jfrolich** [comment]
BTW I had some issues making 5.0 work with Android. Would be good to put some documentation out when it is released.

**Comment by cspicuzza** [comment]
Is 5.0 stable enough for production?

**Comment by jfrolich** [comment]
Not sure, we shipped it though 🤫

**Comment by guyca** [comment]
@cspicuzza We're upgrading the Wix app to v5 next week. I'm not aware of any more issues.

@jfrolich Thanks for the feedback, We'll update the docs before release 👍

**Comment by jfrolich** [comment]
@guyca I didn't know about the docs in the issue related to the beta (I kind of had to debug my way into that solution), with that info it would have been smooth sailing.
