### ISSUE TITLE
White space between Status bar and Topbar on iOS

### ISSUE THREAD

**Issue by theromie** [wix/react-native-navigation#5872]
How can i remove white space between Status bar and Topbar in iOS?[https://media.discordapp.net/attachments/339371162855276544/669912102093324298/Screenshot_2020-01-23_at_7.56.54_PM.png](Image)

**Comment by guyca** [comment]
How does your root look like?
Any chance you have a bottomTabs layout inside a stack?

**Comment by theromie** [comment]
I fixed by removing stackroot to toot
