### ISSUE TITLE
Can't use navigation options within functional/stateless components

### ISSUE THREAD

**Issue by geroale** [wix/react-native-navigation#5874]
### Issue Description

It is not possible to use the navigation options in a functional/stateless component, but the same options are working with the static options in the class component.

### Steps to Reproduce / Code Snippets / Screenshots

This is working
```
class ExploreScreen extends React.Component<Props, State> {

  static options (passProps: Props): Options {
    return getNavigationOptions({
      topBar: {
        title: {
          text: "Explore"
        },
      },
    });
  }

  ...

}
```

This is not working
```
const ExploreScreen: FunctionComponent<Props> = (props) => {
   ...
}

ExploreScreen.options = (passProps: Props): Options => getNavigationOptions({
  topBar: {
    title: {
      text: "Explore"
    },
  }
})
```

How can I use this options "inside" the stateless component? I would prefer not to use them when pushing the screen or in other places, but I am open to new ideas.

### Environment

* React Native Navigation version: 4.0.5
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS, but probably both
* Device info (Simulator/Device? OS version? Debug/Release?): iOS Simulator

**Comment by vrgimael** [comment]
Just use merge options and set the options dynamically when mounting

**Comment by geroale** [comment]
@vrgimael This is a good solution except that for some properties (as in my case, the color of the bottom tabs), applying the options when the component mounts is slightly late and a quick graphical flick may occur, seeing the default options for a moment.

If others were to have my problem, the solution I adopted was to move the tab options out of the screen mount, leaving them only the properties strictly related to the component and it worked.

**Comment by guyca** [comment]
Declaring static options with functional components is documented [here](https://wix.github.io/react-native-navigation/docs/functionalComponents#declaring-static-options)

**Comment by code-by** [comment]
@guyca 
I got `TypeError: Screen.options is not a function. (In 'Screen.options()', 'Screen.options' is undefined)`

**Comment by code-by** [comment]
> Just use merge options and set the options dynamically when mounting

how to do this?
