### ISSUE TITLE
how to make bottomTabs appears on top of overlay

### ISSUE THREAD

**Issue by bougarfaoui** [wix/react-native-navigation#5878]
### Issue Description
Hi guys, I couldn't find a way to show overlay under bottomTabs
### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 4.5.3
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?):Simulator

**Comment by bougarfaoui** [comment]
this image illustrates that https://imgur.com/f3njZb5

**Comment by guyca** [comment]
@bougarfaoui That's not supported. Overlay appears on top of the root ViewController.
