### ISSUE TITLE
[IOS] Modal view can not transparent?

### ISSUE THREAD

**Issue by charlesluo2014** [wix/react-native-navigation#588]
### Issue Description

hi,I use showModal,and set the navigatorStyle={
screenBackgroundColor:'rgba(0,0,0,0.2)',
}
but the view can not transparent

### Steps to Reproduce / Code Snippets / Screenshots

just like above ,android is ok

---
### Environment
* React Native Navigation version: 2.0.0-experimental.157
* React Native version: 0.39.2
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): IOS 10

**Comment by Crash--** [comment]
In my use case, I use showModal() with transparent background on Android, and I use showLightBox() on iOS 
```
showLightBox({
          screen: "InTeach.HowToSwipe",
          title: "My Modal",
          style: {
            backgroundBlur: "none",
            backgroundColor: "#FFFFFFDD",
            flex: 1,
            marginLeft: sizes.cardMargin,
            marginRight: sizes.cardMargin,
            marginBottom: sizes.cardMargin,
            //backgroundColor: colors.white,
            padding: sizes.cardMargin,
            overflow: 'hidden',
            alignItems: 'stretch',
            justifyContent: 'center',
            borderRadius: 8,
            zIndex: 0
          },
```

**Comment by charlesluo2014** [comment]
Thanks @Crash,I think make RNN of the two platform as same as possible would be much better，I step in to the code implement，there is a RCTView Block the transparent

**Comment by guyca** [comment]
cc @DanielZlotin

**Comment by norman-kapschefsky** [comment]
With experimental version 2.x it is possible but not documented. Found a way by setting the `navigatorStyle` like mentioned above for your modal screen:

    static navigatorStyle = {
        screenBackgroundColor: 'transparent',
        modalPresentationStyle: 'overCurrentContext',
    };

**Comment by gran33** [comment]
@norman-kapschefsky Classic!
Thanks for the sharing.

**Comment by robbie-mcfarlane** [comment]
```javascript
static navigatorStyle = {
    screenBackgroundColor: 'transparent',
    modalPresentationStyle: 'overFullScreen'
}
```

**Comment by sapjax** [comment]
If set `modalPresentationStyle`, when `dismissModal`, it will not trigger  `willAppear` and `didAppear` event for the under screen.

**Comment by HighSoftWare96** [comment]
Excuse me folks but where do I have to put 
```
static navigatorStyle = {
    screenBackgroundColor: 'transparent',
    modalPresentationStyle: 'overFullScreen'
}
```? Inside the screen component? It does not work with me... Do I have to set also a flex:1 view with a backgroundcolor with opacity?

**Comment by ramonrovirosa** [comment]
The only way I was able to get a transparent background for a modal or overlay as of react-native-navigation version `2.1.3` was to set the style of my modal view to have a background color of null e.g.

```
<View style={{
    backgroundColor: null,
  }}>
    <ActivityIndicator  />
  </View>
```

**Comment by kevinvangelder** [comment]
@ramonrovirosa @HighSoftWare96 I was also still having this issue, but then I found this comment and it worked for me. https://github.com/wix/react-native-navigation/issues/4134#issuecomment-430277278

It seems that screenBackgroundColor is ignored and instead we should be using layout: { backgroundColor: 'transparent' }

**Comment by sturmenta** [comment]
```
export const showModal = async props => {
  await Navigation.showModal({
    component: {
      name: 'modal', // screen name - previous registered
      passProps: props,
      options: {
        layout: { backgroundColor: 'transparent' },
        screenBackgroundColor: 'transparent',
        modalPresentationStyle: 'overCurrentContext',
        topBar: {
          visible: false,
          drawBehind: true,
        },
      },
    },
  });
};
```

**Comment by adybuciuman** [comment]
on `"react-native-navigation": "^2.22.3"` is not working the following code
` Navigation.showModal({
    component: {
      name: ScreenName,
      passProps: { isModalScreen: true },
      options: {
        layout: { backgroundColor: 'transparent' },
        screenBackgroundColor: 'transparent',
        modalPresentationStyle: 'fullScreen',
      }
    }
  });`  
and `overCurrentContext ` is out of question because it crash
