### ISSUE TITLE
Changing the navigation root crashes on Android.

### ISSUE THREAD

**Issue by alejo-lapix** [wix/react-native-navigation#5881]
### Issue Description

Changing the navigation root crashes on Android.

In the application root I'm using a **side bar** and **bottom tabs**, this will lead to the following error.

`java.lang.NullPointerException: Attempt to invoke virtual method 'void com.reactnativenavigation.viewcontrollers.bottomtabs.AttachMode.destroy()' on a null object reference`

Don't know if this is not the way that the library should be used. Is there any other way to handle things like deeplinks that keep navigation stack in the correct order?

### Steps to Reproduce / Code Snippets / Screenshots
[This is a fork](https://github.com/alejo-lapix/react-native-navigation/commit/449291dc2e749b46615884bcf1de83f9d687665b) of the react-native-navigation library. To reproduce the error you just need to run the application in an Android device and that's it.

Also those are the steps which I follow to replicate the error my project.

1. In the application entry point this is how we set the navigation root.

```js
Navigation.setRoot({
  root: {
    sideMenu: {
      center: {
        stack: {
          children: [
            // The first child will have bottom tabs.
            {
              bottomTabs: {
                children: [
                  {
                    component: {
                      name: GUEST_HOME,
                      options: {
                        bottomTab: {
                          icon: 'menu',
                        },
                      },
                    },
                  },
                ],
              },
            },
            // The second child can come from a deeplink 
            // or something like that. This component will change the 
            // application root.
            {
              component: {
                name: TERMS,
              },
            },
          ],
        },
      },
    },
  },
});
```
2. This component will change the application root.
```jsx
import React, {useEffect} from 'react';
import AppContent from './AppContent';

const TermsScreen = () => {
  useEffect(() => {
    setTimeout(() => pushOtherStack(), 5000);
  });
  return <AppContent render={'terms'} />;
};

export default TermsScreen;
```
3. **BOOM**!

---
### Environment
* React Native Navigation version: 4.5.3
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): 
Simulator CPU/ABI: x86 Pixel 2 API level 24
OS version: Android 7.0
Debug

**Comment by ItsNoHax** [comment]
Hi @alejo-lapix,

Please use the provided template when creating issues.
There is a lot of information missing such as RN version, RNN version etc.

Also please provide a reproducible example in the Playground project by creating a fork.

**Comment by alejo-lapix** [comment]
Ok @ItsNoHax , sorry for the initial poor description of the error. I've updated the issue description. Also [this is a fork](https://github.com/alejo-lapix/react-native-navigation/commit/449291dc2e749b46615884bcf1de83f9d687665b) of the react-native-navigation library there you can find a commit where reproduce the crash.

**Comment by flexsurfer** [comment]
we also sometimes see a crash when changing root
![image](https://user-images.githubusercontent.com/11790366/122522613-73777a80-d016-11eb-87f6-83f0a6e01460.png)
