### ISSUE TITLE
[v4] setDefaultOptions statusBar drawBehind not respected

### ISSUE THREAD

**Issue by manuhook** [wix/react-native-navigation#5886]
### Issue Description

When setting `statusBar: { drawBehind: true }` as default option, it is not respected on Android. Only when setting it via `static options () `or `mergeOptions()` it is being applied.

### Steps to Reproduce / Code Snippets / Screenshots

On Playground App
```
diff --git a/playground/src/commons/Options.js b/playground/src/commons/Options.js
index 5a7c2ebe..01b8a26a 100644
--- a/playground/src/commons/Options.js
+++ b/playground/src/commons/Options.js
@@ -7,6 +7,9 @@ const { useSlowOpenScreenAnimations } = require('../flags');
 const SHOW_DURATION = 230 * 8;
 
 const setDefaultOptions = () => Navigation.setDefaultOptions({
+  statusBar: {
+    drawBehind: true,
+  },
   layout: {
     backgroundColor: Colors.background,
     orientation: ['portrait']
```

---
### Environment
* React Native Navigation version: 4.6.0
* React Native version: 0.61
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulato & Device / any Android version

Thanks @guyca 🙏

**Comment by vuongductuanktmt** [comment]
I am also getting this error, hope to fix it soon!

**Comment by guyca** [comment]
@vuongductuanktmt It's fixed in [v5](https://github.com/wix/react-native-navigation/issues/5904)

**Comment by vuongductuanktmt** [comment]
> @vuongductuanktmt It's fixed in [v5](https://github.com/wix/react-native-navigation/issues/5904)
i use `"react-native-navigation": "5.0.0-alpha.12",`

` Navigation.setDefaultOptions({
      topBar: {
        visible: false,
      },
      bottomTabs: {
        backgroundColor: Colors.shadow,
      },
      statusBar: {
        drawBehind: true
      },
      layout: {
        backgroundColor: Colors.light,
        orientation: ['portrait']
      }
})`

`
<View style={{backgroundColor: "blue", flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <Text style={{color: "#fff", fontWeight: "bold", fontSize: 20}}>hello</Text>
</View>
`
but StatusBar not drawBehind
![image](https://user-images.githubusercontent.com/25997663/74211590-21587380-4cc3-11ea-84a5-a37bad615188.png)
please help me!

**Comment by guyca** [comment]
@vuongductuanktmt Can you please try to reproduce in the playground app? If you're using `<StatusBar>` component, then make sure to remove any usages of it.

**Comment by vuongductuanktmt** [comment]
> @vuongductuanktmt Can you please try to reproduce in the playground app? If you're using `<StatusBar>` component, then make sure to remove any usages of it.
I tried use <StatusBar> or remove <StatusBar> but error as above! 
version RNN 2.26.5 then working!

**Comment by guyca** [comment]
@vuongductuanktmt I'm unable to reproduce this in the playground app running v5. If you believe this is still an issue, please fork the library and submit a reproduction with v5 branch, Thanks.

**Comment by vuongductuanktmt** [comment]
> @vuongductuanktmt I'm unable to reproduce this in the playground app running v5. If you believe this is still an issue, please fork the library and submit a reproduction with v5 branch, Thanks.

I have replaced the whole configuration
showModal and delete the configuration in setDefaultOptions are now working!
but cannot use the configuration in setDefaultOptions!

`Navigation.showModal({
    stack: {
      children: [
        {
          component: {
            name: MEETING_ROOM_SCREEN,
            options: {
              statusBar: {
                drawBehind: true,
                backgroundColor: Colors.transparent,
              }
            }
          }
        }
      ]
    }
  })`

![image](https://user-images.githubusercontent.com/25997663/74285551-ae99d780-4d58-11ea-8ee4-5859bbe1cc5f.png)
