### ISSUE TITLE
Cannot change swipeToDismiss through mergeOptions

### ISSUE THREAD

**Issue by nielsmadan** [wix/react-native-navigation#5888]
### Issue Description

It does not seem to be possible to change the value of `swipeToDismiss` through `mergeOptions`. Looking at the Code of `RNNBasePresenter.m`, it looks like the option is only used in `applyOptionsOnInit`.

Not sure if iOS allows you to change it after the view is created, but if it doesn't, it should at least be documented.

### Steps to Reproduce / Code Snippets / Screenshots

```js
componentDidMount() {
  Navigation.mergeOptions(this.props.componentId, {
    modal: {
      swipeToDismiss: false,
    }
  });
}
```

---
### Environment
* React Native Navigation version: 4.2.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by dominicstop** [comment]
Hello! For anyone looking for a temp. fix, I just added this snippet to `RNNBasePresenter.m` in the `mergeOptions` function (which i just copied from the `applyOptionsOnInit` function). And it seemed to have worked just fine? 😂✨ 
```objective-c
  if (@available(iOS 13.0, *)) {
    UIViewController* viewController = self.boundViewController;
    viewController.modalInPresentation = !withDefault.modal.swipeToDismiss.get;
  }
```

(for the meantime, i'm just manually pasting it in the Pods > Developer Pods > ReactNativeNavigation > RNNBasePresenter.m file haha 😃)
