### ISSUE TITLE
[iOS 13] Overlays intercept touch on iPad Pro + iPad Air

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#5889]
### Issue Description

On iPad Pro and iPad Air models, overlays with ``` interceptTouchOutside: false ``` do not work as expected as they actually absorb all the touch events. This is strange because it does not happen on normal iPhones or even the standard iPad's (6th generation).

Similar closed issues:
- https://github.com/wix/react-native-navigation/issues/5661
- https://github.com/wix/react-native-navigation/issues/5579

### Steps to Reproduce / Code Snippets / Screenshots

Fork with reproducible example: https://github.com/ItsNoHax/react-native-navigation/tree/reproduce-invisible-overlay

Steps:
- Open a simulator of type: iPad Pro 3rd generation 12 inch.
- Open the playground project and navigate to the 3rd tab: Navigation
- Click on the Overlay button to open OverlayScreen
- Click on Show invisible overlay
- Try to click any buttons and notice how it's not possible
- Re-do the steps above with a simulator of type: iPhone 11 and note how it does work

---
### Environment
* React Native Navigation version: 4.6.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS 13
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by fjmorant** [comment]
Same for me

**Comment by fjmorant** [comment]
@guyca any updates on this issue? 

Thanks

**Comment by fjmorant** [comment]
Hi,

A possible hint for solving this issue, if you go to file RNNOverlayWindow.m and take a look at this method:

```
- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
	UIView *hitTestResult = [super hitTest:point withEvent:event];
	
	if ([hitTestResult isKindOfClass:[UIWindow class]]) {
		return nil;
	}
	
	return hitTestResult;
}
```

 - On iPhone when you touch outside of your overlay view **hitTestResult** is a **RNNOverlayWindow**
 - On iPad touch outside of you overlay view **hitTestResult** is a **UIView**

There is some view added in the middle for iPad, I have checked all the code and doesn't seem to be anything conditional for iPad, a workaround for solving this issue temporarily is this:

```
 @implementation RNNOverlayWindow

- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
	UIView *hitTestResult = [super hitTest:point withEvent:event];
	
	if ([hitTestResult isKindOfClass:[UIWindow class]]) {
		return nil;
	}
    
        if ([[hitTestResult class] isEqual:[UIView class]]) {  <===== Added this
                return nil;
        }
	
	return hitTestResult;
}

@end
```

And it works on iOS 13 because what we really want to intercept is RCTViews not pure UIViews in my opinion

**Comment by ItsNoHax** [comment]
Nice find @fjmorant , hopefully @yogevbd can use this to propose a fix.

**Comment by yogevbd** [comment]
Great finds guys.. 👏

**Comment by ItsNoHax** [comment]
@yogevbd Seems like this has been lost in V5 version. Going to re-open the issue.

**Comment by flikQ** [comment]
This also appears to be an issue on all iOS devices, not just on iPads. V6.3.1

**Comment by flikQ** [comment]
You can see a video of the replication here: https://d.pr/v/My6YCg

**Comment by flikQ** [comment]
@yogevbd as no-one seems to be seeing this issue. The iPad fix issued doesn't resolve.

**Comment by guyca** [comment]
Hey @flikQ ! 👋 If you could fork the library and push a reproduction to the issue to your clone, that would help us a lot debug this issue.
