### ISSUE TITLE
Podfile is not updating correctly with upgrades

### ISSUE THREAD

**Issue by MakhouT** [wix/react-native-navigation#5897]
**### Issue Description**

Currently, when updating RNN, the Podfile is not being updated correctly. 

I will include a few screenshots of the upgrading process with RNN and `react-native-device-info` then you can see the process/expected behavior/issue.

**### Steps to Reproduce / Code Snippets / Screenshots**
1. Increase the version number of RNN in `package.json`
![image](https://user-images.githubusercontent.com/3041165/73589760-058ee980-44db-11ea-9ddb-f128b54a8970.png)

2. Run `yarn install` to bring in the new package
3.  `cd ios`
4. `pod install`

![image](https://user-images.githubusercontent.com/3041165/73589820-9d8cd300-44db-11ea-9d4e-44c25f55c84e.png)

**Current behavior:** 
RNN is not being updated, while other packages are being updated

**Expected behavior:**
RNN also gets updated without deleting the Podfile.lock

**Comment by jinshin1013** [comment]
This is very interesting. I never saw this happening when I do my upgrades. Could it be some local environment setup issue? Also I'm not entirely sure if this would be the RNN issue since it does seem to be upgrading after deleting the `Podfile.lock` file.

**Comment by MakhouT** [comment]
Hmm strange, I'm only having this issue with RNN and my teammates have the same issue.

**Comment by jinshin1013** [comment]
I'm not sure how to combat this man to be honest. This is the screenshot of me updating RNN and it worked fine. You could try on fresh setup if that fixes it then slowly add your setup and identify the root cause. But yeah I don't know what to tell you 😓

![Screen Shot 2020-02-04 at 9 02 59 am](https://user-images.githubusercontent.com/17612922/73698556-349c9980-472d-11ea-8071-9cf683d0f23a.png)

**Comment by MakhouT** [comment]
Hmm interesting!
Do you have this line in your Podfile
```  pod 'ReactNativeNavigation', :podspec => '../node_modules/react-native-navigation/ReactNativeNavigation.podspec'
```

**Comment by jinshin1013** [comment]
Oh, you will need to delete that line. It should work without that line!

**Comment by MakhouT** [comment]
That indeed fixes the issue and then it's working as it should!

I just verified in the docs, the install guide is telling to add that line. Maybe we should remove it.

https://wix.github.io/react-native-navigation/#/docs/Installing?id=installation-with-cocoapods

**Comment by jinshin1013** [comment]
Yeah it seems like the doc isn't reflecting the react-native autolink. I believe the team is working on the new doc at the moment so let's give it few days 🤗

**Comment by guyca** [comment]
Updated the docs in v5 branch. Thanks guys 👍
