### ISSUE TITLE
content remains underneath topbar (android)

### ISSUE THREAD

**Issue by gunduzcihat** [wix/react-native-navigation#5905]
### Issue Description

I don't know whether it is a bug.

### Steps to Reproduce / Code Snippets / Screenshots

**My default layout option code is:**

    export const setDefaultOptions = () => Navigation.setDefaultOptions({
    layout: {
        orientation: ['portrait'],
        direction: 'ltr',
    },
    topBar: {
        visible: true,
        drawBehind: true,
        animate: false,
        hideOnScroll: false,
        backButton: {
            visible: true,
            icon: TopbarBackButtonIcon,
            color: '#ccc',
        },
        title: {
            component: { name: TopBarLogoNav, alignment: 'center', passProps: {} },
            alignment: 'center'
        }
    },
    sideMenu: {
        left: {
            enabled: true,
            shouldStretchDrawer: false,
            width: 270,
        },
        openGestureMode: 'entireScreen'
    }
    });

---
### Environment
* React Native Navigation version: 4.6.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Debug mode

**Problem:**
![img1](https://user-images.githubusercontent.com/24367679/73845404-9d6e3980-4833-11ea-9f07-40cb5c8f526f.jpg)

**Expected:**
![img2](https://user-images.githubusercontent.com/24367679/73845398-9ba47600-4833-11ea-8355-762c0805186a.jpg)

**Comment by ItsNoHax** [comment]
drawBehind: true, <--- should be false no?

**Comment by gunduzcihat** [comment]
Thank you so much!!!
