### ISSUE TITLE
[Android] Stack pops the screen without a pop being called

### ISSUE THREAD

**Issue by srossi3** [wix/react-native-navigation#5907]
### Issue Description

Hi everyone.
I am using this library to handle navigation between screens in a react native application. Everything works fine when navigating between the screens with the onPress call of buttons. The issue emerged when I connected an external ble device which is supposed to control the navigation and, in certain screens, act as a keyboard. I have been handling the switch between keyboard and navigation-control through cases of a global reducer. 
If it doesn't switch to the keyboard mode, everything works as expected, after it does though, the stack appears to automatically pop the screen (though in no point of the code is there a call to a function which pops the stack) which enables the keyboard function, returning to the screen before without navigation beeing called. 
Is there any known conflict between ble, redux and navigation that I am not aware of?
Has anyone experienced similar issues?
Thank you, 
Silvia 

--
### Environment
* React Native Navigation version: 3.6.2
* React Native version: 1.2.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):Xiaomi mi mix 2 Android 9.0.1

**Comment by guyca** [comment]
hmmm
You can set a breakpoint in [StackController.pop()](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java#L254) and see why pop is invoked.
