### ISSUE TITLE
[Android] How to set actionOverflowButton Icon/Color

### ISSUE THREAD

**Issue by tolu360** [wix/react-native-navigation#591]
### Issue Description

There's currently no way to set or change the color of the `actionOverflowButtonIcon` in javascript for the NavBar on Android or perhaps I don't know where to look in the docs. I had to resort to setting this up in native using the drawable resources.

### Steps to Reproduce / Code Snippets / Screenshots

Create `rightButtons` on the navigator with at least an item that has its `showAsAction` property set to `never` e.g:

```js
{
	title: 'New group',
	id: 'new_group',
	showAsAction: 'never'
}
```

The default overflow icon is black which won't work well with dark any `navBarBackgroundColor` 

---
### Environment
* React Native Navigation version: 2.0.0-experimental.157
* React Native version: 0.39
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator

**Comment by guyca** [comment]
Hey @tolu360 Defining `navBarButtonColor` will set the icon color for all buttons in the TopBar, including the overflow icon.

```js
static navigatorStyle = {
    navBarButtonColor: 'red'
  };
```

**Comment by tolu360** [comment]
Thanks @guyca, somehow I was trying `titleBarButtonColor` the whole time with no success.

**Comment by guyca** [comment]
I understand your confusion. We're going to change the naming scheme real soon (already done in v2 branch)

**Comment by sijad** [comment]
is there a way to change actionOverflowButton icon?

**Comment by windydang26** [comment]
Hi! @guyca , How i can set special color for only some button ?
