### ISSUE TITLE
Is there a way to prevent from leaving a screen?

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#5911]
### Issue Description

I do not see any easy way to prevent from leaving a screen, either by using a rnn command or using a gesture or native back button (android).

Is there something that would allow to do that?

My use case is to display a modal before leaving a page with a form if the user did not save its changes.

### Steps to Reproduce / Code Snippets / Screenshots

n/a

---
### Environment
* React Native Navigation version: All
* React Native version: All
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by zabojad** [comment]
We could for example have something like the current [command observers](https://wix.github.io/react-native-navigation/#/api/CommandsObserver) that would additionally allow us to cancel a command.

**Comment by sintylapse** [comment]
For screens that should not be dismissed the only way I see is ti use modal instead of screen, at least for IOS, modal will not have swipe back gesture. But for Android it doesn't matter what are you using, you can always do
```
BackHandler.addEventListener(
    'hardwareBackPress',
    () => true,
)
```
to prevent back press

**Comment by guyca** [comment]
@zabojad What type of screen do you want to prevent the user from leaving? It's different for pushed screens and modals.

# Modal
## Disable page sheet modal dismiss
```
modal: {
  swipeToDismiss: false
}
```
## Disable hardware back button
```js
BackHandler.addEventListener(
    'hardwareBackPress',
    () => true,
)
```

# Pushed screen
## Remove software back button
```js
topBar: {
  backButton: {
    visible: false
  }
}
```
## Disable swipe gesture
```js
{
  popGesture: false
}
```
