### ISSUE TITLE
The term 'pod' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by aaliz2000** [wix/react-native-navigation#5912]
My operating system(OS) is windows 10. I have created a React-Native project with the following code :

`react-native init AwesomeProject`

I want to install React-navigation then do the following steps :(based on the React-Navigation documentation)

1-
`npm install @react-navigation/native`

2-
```
npm install 
react-native-reanimated 
react-native-gesture-handler 
react-native-screens 
react-native-safe-area-context 
@react-native-community/masked-view
```

3- When I run the following step I get an error :

```
cd ios
pod install
cd ..

```

>     pod : The term 'pod' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I do not know how to run the command above in windows.

my package.json
```
{
  "name": "testproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.6",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.2",
    "react-native-screens": "^2.0.0-beta.2"
  },
  "devDependencies": {
    "@babel/core": "7.8.4",
    "@babel/runtime": "7.8.4",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.4",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by jinshin1013** [comment]
This isn't `react-navigation` repo.

**Comment by mayconmesquita** [comment]
@aaliz2000 you need to open the issue here: https://github.com/react-navigation/react-navigation/issues

**Comment by safafmohammed** [comment]
type 'npx pod install'

**Comment by muhammadfaizkhan** [comment]
> type 'npx pod install'

Thanks man ! It **works** for me now.

**Comment by OmkarIsHere** [comment]
> type 'npx pod install'

Do you have any solution for a flutter?
