### ISSUE TITLE
Deprecate drawBehind on iOS

### ISSUE THREAD

**Issue by yogevbd** [wix/react-native-navigation#5913]
The drawBehind option has been an anti pattern on iOS from the start and was introduced only for parity with Android api.
On iOS, when a ScrollView or a SafeAreaView are used as screen root; the system handles insets automatically.
As adoption of notch devices increases, developers use these views regularly, rendering the drawBehind option useless.

In v6 `drawBehind` will always be true on iOS, and the `drawBehind` option will be disregarded. 

**During the migration phase, you should set `drawBehind: true` to both TopBar and BottomTabs in default options.**

**Comment by troozksa07** [comment]
> The drawBehind option has been an anti pattern on iOS from the start and was introduced only for parity with Android api.
> On iOS, when a ScrollView or a SafeAreaView are used as screen root; the system handles insets automatically.
> As adoption of notch devices increases, developers use these views regularly, rendering the drawBehind option useless.
> 
> In v6 `drawBehind` will always be true on iOS, and the `drawBehind` option will be disregarded.
> 
> **During the migration phase, you should set `drawBehind: true` to both TopBar and BottomTabs in default options.**
