### ISSUE TITLE
animationType

### ISSUE THREAD

**Issue by AtixD** [wix/react-native-navigation#592]
animationType : 'fade' not working with Navigation.startSingleScreenApp

---
### Environment
* React Native Navigation version:  "react-native-navigation": "^2.0.0-experimental.157"
* React Native version: 0.39.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Genymotion 6.0 Debug

**Comment by brunolemos** [comment]
This can be closed, it's working fine on current version.
