### ISSUE TITLE
Full Screen OpenGestureMode Option Should Be Set to bezel By Default

### ISSUE THREAD

**Issue by adilanchian** [wix/react-native-navigation#5925]
### Issue Description
SideMenu option `openGestureMode` having a default of `entireScreen` makes it very painful to debug issues with swipe gestures on other components. This should either be set very visibly in the docs or all together the default should be `bezel` <--- Preferred in my opinion.

### Steps to Reproduce / Code Snippets / Screenshots
1. Create a stack with `sideMenu`
2. Set `sideMenu` option to right
3. I was using `react-native-swipe-list-view v2.0.1` to try to setup swipe actions as my center content
4. Try to swipe a cell

### Actual Results 
The `entireScreen` default option would not allow the event to propagate down

### Environment
* React Native Navigation version: 3.1.2
* React Native version: 0.60.4
* Platform(s) (iOS, Android, or both?): iOS (Probs Android as well)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
@yogevbd WDYT?

**Comment by adilanchian** [comment]
@guyca  - More than happy to implement this as well. Just let me know! I spent too long debugging this to find out that it was this one flag haha. Lemme know!

**Comment by guyca** [comment]
Default`openGestureMode` was changed to `bezel` in v7. Thanks for reporting @adilanchian
