### ISSUE TITLE
[v2] componentDidAppear not called for topBarButton (iOS)

### ISSUE THREAD

**Issue by FinnGu** [wix/react-native-navigation#5927]
### Issue Description

I have a topBar Button which I register as a redux component and would like to fetch data as soon as it is rendered. Therefore, I implemented the listener for `componentDidAppear` and everything works fine on Android. Only on iOS the event does not get triggered. I added a global listener to log ALL `componentDidAppear` events and it seems to me that none of my multiple topBar Buttons trigger this event.

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.setRoot({
    root: {
        stack: {
            children: [
                {
                    component: {
                        name: 'AnyComponent',
                        options: {
                            topBar: {
                                rightButtons: [
                                    {
                                        id: 'anyId',
                                        component: {
                                            name: 'AnyOtherComponent',
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            ]
        }
    }
});

// Will output "AnyComponent did appear", but not "AnyOtherComponent did appear" :(
const screenEventListener = Navigation.events().registerComponentDidAppearListener(({ _componentId, componentName, _passProps }) => {
      console.log(componentName + " did appear");
});
```

---
### Environment
* React Native Navigation version: 2.21.0
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): real device, iOS 13, both Debug and Release

**Comment by guyca** [comment]
@FinnGu I think this issue is resolved in v5. Can you try to reproduce it in the playground app?

**Comment by FinnGu** [comment]
> @FinnGu I think this issue is resolved in v5. Can you try to reproduce it in the playground app?

Will try. Probably only have time during the weekend though.

Haha, I really should upgrade this awesome library soon. Just saw all the new and improved features.
