### ISSUE TITLE
Empty screen after showing/hiding modal and then pushing screen on Android version 8 and below

### ISSUE THREAD

**Issue by jaapmengers** [wix/react-native-navigation#5941]
### Issue Description

This is quite a specific case, but we do run into it in our production app. On Android versions 8 and below the following scenario will lead to an empty screen being shown:

Given three screen definitions:

1. A screen (let's call it NavigationScreen) that has a light statusbar style and that has a button to present a modal, and a button to push a new screen.
1. A screen that contains the modal content (let's call it ModalScreen) that has a dark statusbar style and a button to dismiss itself. 
1. A screen without with arbitrary content (let's call it PushedScreen) that will get shown after the push button is used on the NavigationScreen.

The following scenario will lead to an empty screen being shown:

1. From the NavigationScreen, tap the modal button and use `showModal` with modal presentation style `overCurrentContext` to show the ModalScreen.
1. From the ModalScreen, tap the button to dismiss the modal.
1. From NavigationScreen, tap the push button to push the PushedScreen to the navigation stack.
1. A new screen will not be pushed, and instead an empty screen is shown.

This scenario happens only when:
1. The statusbar style on the Navigation- and ModalScreen are different. Eg. NavigationScreen is light and ModalScreen is dark or vice versa.
1. ModalPresentationStyle `overCurrentContext` is used.

### Steps to Reproduce / Code Snippets / Screenshots

I created a reproduction scenario based on the playground app. See this gist for the diff that can be applied to the playground app to reproduce: https://gist.github.com/jaapmengers/13202dedab12da3712bef13bcf5abffd 

 Screenshots of the reproduction steps:

1. NavigationScreen before tapping the Modal button.
![screen](https://user-images.githubusercontent.com/4312892/74815227-c2ad7e00-52f0-11ea-93aa-14bd22a0088b.png)
1. ModalScreen before tapping the Dismiss Modal button.
![screen2](https://user-images.githubusercontent.com/4312892/74815256-d22cc700-52f0-11ea-83bc-964e578600ea.png)
1. NavigationScreen after the ModalScreen is dismissed.
![screen3](https://user-images.githubusercontent.com/4312892/74815316-ecff3b80-52f0-11ea-927b-f2db7028c0e4.png)
1. Empty screen being shown after Push button is tapped from NavigationScreen.
![screen4](https://user-images.githubusercontent.com/4312892/74815379-07d1b000-52f1-11ea-9316-92a6b59e066e.png)

---
### Environment
* React Native Navigation version:  4.8.4
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): Reproduced on Android versions 7 and 8
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung Galaxy A3 with Android 7.0, Samsung S7 with Android 8.0, Huawei P20 Lite with Android 8.0

**Comment by talyuk** [comment]
Have the same issue

**Comment by redwind** [comment]
have the same issue
