### ISSUE TITLE
Third Party Libraries Support : react-native-gesture-handler & react-native-reanimated

### ISSUE THREAD

**Issue by subhadipsjsc** [wix/react-native-navigation#5948]
some extra 3rd party Library support will be helpful

Support for native animation : react-native-gesture-handler & react-native-reanimated

React-native-navigation is the native implementation of the navigation system in the react-native ecosystem. Its main focus is performance  (shifting weight of navigation from Js thread to native one).
currently, it supports Third-Party Libraries: Redux, react-native-vector-icons

react-native-gesture-handler & react-native-reanimated are Animation libraries, also doing kinda same like React-native-navigation in the animation domain. (shifting weight of Animation from Js thread to native one).
support for these native implementations ( react-native-gesture-handler & react-native-reanimated ) will be very helpful.

its purely a request, not a bug or issue. Entirely depends on contributors 

---
### Environment
* React Native Navigation version: 5.0.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by jinshin1013** [comment]
You can use those libraries with react-native-navigation.

**Comment by subhadipsjsc** [comment]
I did not get any info how to add those , do you know any boiler plate got link or any docs which I can follow. Searched for 3 days , no solution till.

By the way thanks for replying.

**Comment by jinshin1013** [comment]
react-native-gesture-handler will need to be installed differently as their [doc](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#with-wix-react-native-navigation-https-githubcom-wix-react-native-navigation) points out. But react-native-reanimated can just be installed through auto-link so you won't have to do anything really.

**Comment by muhammadwafa** [comment]
As I heard that auto linking works in v5, but now v6 and still does not works

**Comment by jinshin1013** [comment]
@muhammadwafa What is not working for you? Could you provide more specifics? From a fresh react-native project, running `react-native link react-native-navigation` will make the required native changes for you.

**Comment by muhammadwafa** [comment]
For me auto linking does not work

**Comment by jinshin1013** [comment]
I've created a PR that fixes the autolink script https://github.com/wix/react-native-navigation/pull/5989. It will still complain that RNN is linked manually but you can ignore that  error.

**Comment by muhammadwafa** [comment]
Thank you, and also please update the installation instructions as I am seeing it is not updated. both for IOS and Android

**Comment by jinshin1013** [comment]
New documentation is on the way I believe. You can keep your eye on https://github.com/wix/react-native-navigation/issues/5959.
