### ISSUE TITLE
[V6] Show Overlay with transparent backgroundColor

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#5953]
`Navigation.showOverlay({
                    component: {
                        name: TOP_NOTIFICATION,
                        id: TOP_NOTIFICATION,
                        options: {
                            layout: {
                                backgroundColor: 'transparent',
                                orientation: ['portrait'],
                            },
                            overlay: {
                                interceptTouchOutside: false,
                                handleKeyboardEvents: true,
                            }
                        }
                    }
                });`
But the overlay fill out full screen with white color
---
### Environment
* React Native Navigation version: 6.0.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
Hey @moonjava2005 There's a breaking change in v6 regarding layout.componentBackgroundColor - see the changelog for [details](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#600)

**Comment by skychx** [comment]
> Hey @moonjava2005 There's a breaking change in v6 regarding layout.componentBackgroundColor - see the changelog for [details](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#600)

Very helpful! I think RNN should update its documentation.
