### ISSUE TITLE
White Background for Overlay with Version 6.0.0

### ISSUE THREAD

**Issue by sebastianpopp** [wix/react-native-navigation#5955]
### Issue Description

Hi @yogevbd,
I was looking at your changes in the latest version and was wondering what [these lines](https://github.com/wix/react-native-navigation/commit/950642d48b2ec67f510ae6b3eefaaeb1ebfcf43d#diff-cd71f333780078ef719899945b7b3261R62) were for. I'm using an overlay to display an AdMob banner in my app, but with that change, the background of the overlay can no longer be set transparent for iOS >= 13.0 but is instead white. I'm not quite sure what these changes were intended to do, so I didn't want to mess with it. 5.1.1 was working fine, 6.0.0 is not and if I revert the lines linked above, it's working again. Maybe we can find a solution so the overlay keeps working as well? Thank you for your help!

### Steps to Reproduce / Code Snippets / Screenshots

```js
export default class Banner extends Component {
  render() {
    return (
      <View
        style={{
          position: 'absolute',
          left: 0,
          bottom: 20,
          width: '100%',
          height: 60,
          justifyContent: 'center',
          alignItems: 'center',
        }}>
        <AdMobBanner
          adSize="banner"
          adUnitID="ca-app-pub-xxxxxxxxxxxxxxx"
          testDevices={[AdMobBanner.simulatorId]}
          onAdFailedToLoad={error => console.info(error)}
        />
      </View>
    );
  }
}
```

```js
Navigation.registerComponent('overlay.banner', () => Banner);
```

```js
    Navigation.showOverlay({
      component: {
        name: 'overlay.banner',
        options: {
          overlay: {
            interceptTouchOutside: false,
          },
        },
      },
    });
```
<img width="200" alt="Bildschirmfoto 2020-02-23 um 15 01 28" src="https://user-images.githubusercontent.com/2521500/75113338-69757f80-564d-11ea-8be6-757af8781967.png">

---

### Environment
* React Native Navigation version: 6.0.0 and 6.0.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 11 13.3

**Comment by sebastianpopp** [comment]
Sorry, I missed #5953, but I think this is still relevant. What is the advantage of not being able to configure the background color for iOS >= 13.0?

**Comment by alexandrepalagem** [comment]
Use `layout.componentBackgroundColor` to change background color of individual overlay

```Javascript
Navigation.showOverlay({
  component: {
    name: "overlay.banner",
    options: {
      layout: {
        componentBackgroundColor: "transparent" // <-- Add this line
      },
      overlay: {
        interceptTouchOutside: false
      }
    }
  }
});

```

**Comment by sebastianpopp** [comment]
Should have kept on reading the changes :/
Thank you for your help! That worked
