### ISSUE TITLE
this.nativeEventsReceiver.registerModalAttemptedToDismissListener is not a function on Android 10

### ISSUE THREAD

**Issue by joaom182** [wix/react-native-navigation#5956]
### Issue Description

I'm using react-native-navigation version 4.8.1 with react-native 0.59.9 and when i call `Navigation.events().registerAppLaunchedListener()` throws this exception:

```
this.nativeEventsReceiver.registerModalAttemptedToDismissListener is not a function.
```

![WhatsApp Image 2020-02-23 at 23 35 32](https://user-images.githubusercontent.com/3612098/75125736-51c1e980-5695-11ea-9d70-9d94325a85c7.jpeg)

### Steps to Reproduce / Code Snippets / Screenshots
- Install react-native-navigation version 4.8.1 on react-native 0.59.9
- Call `Navigation.events().registerAppLaunchedListener()`

### Environment
* React Native Navigation version: 4.8.1
* React Native version: 0.59.9
* Platform: Android
* Device info: Motorola One Vision Real Device.

**Comment by guyca** [comment]
Hey there, Seems like you've updated RNN and did not recompile your app.

**Comment by joaom182** [comment]
@guyca I've cleaned build folder, sync Graddle in Android studio, deleted app on my device and recompile.
