### ISSUE TITLE
Docs on Docasaurus

### ISSUE THREAD

**Issue by kgshv** [wix/react-native-navigation#5959]
N.B. This issue is a WIP and related to https://github.com/wix/react-native-navigation/issues/5399.

Using this to track work on the new and improved documentation. Originally started [here](https://github.com/wix/react-native-navigation/issues/5399), but there is currently a need for a somewhat fresh start.

The new documentation website is powered by [Docusaurus.io](https://docusaurus.io/) instead of Docsify, and has a new structure. Work is done in the `docusaurus` branch.

### New documentation structure

**N.B.**
- [X] 1-st level items are in the left-side navigation
  - [X] so are the 2-nd level items
    - [X] 3-rd level items are in the right sidebar.

_________

- [ ] Home page - clicking on "React Native Navigation" at the top should lead to /before-you/start
- [x] **Getting started**
  - [x] Before you start
  - [x] Installation
  - [x] Playground app
  - [x] Showcases
- [x] **Using the app**
  - [x] Launching the app
  - [x] Basic navigation
  - [x] Advanced navigation
  - [x] Screen lifecycle
  - [x] Passing data to components
- [x] **Layouts**
  - [x] Stack
  - [x] BottomTabs
  - [x] SideMenu
  - [x] ExternalComponent
- [ ] **Hierarchy**
  - [x] Root
  - [x] Modal
  - [x] Overlay
- [ ] **Styling**
  - [x] Themes
  - [x] StatusBar
  - [x] Orientation
  - [ ] Screen Animations - `has uncompleted TODO`
  - [x] Changing fonts
  - [x] Constants
- [x] **Meta**
  - [x] **Contributing**

___

### Various TO-DO:

- [ ] Make sure all info in [docusaurus.config.js](https://github.com/wix/react-native-navigation/blob/docusaurus/website/docusaurus.config.js) is correct and not the default one. Same goes for [index.js](https://github.com/wix/react-native-navigation/blob/docusaurus/website/src/pages/index.js).
- [x] Make sure syntax highlighting works for every language (I'm concerned about the `diff` mostly) - this is low priority and not a blocker.
- [ ] more items might be added or subtracted in this list...

**Comment by kgshv** [comment]
@guyca the syntax highlighter isn't making the embedded `diff` pretty for me, so just a suggestion to check if we include the `diff` syntax highlighting module - https://v2.docusaurus.io/docs/markdown-features/#syntax-highlighting

**Comment by guyca** [comment]
Right, I looked into this yesterday and it should work. [diff](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js) is included in docusaurus... we'll look into it later. not a blocker.

**Comment by jinshin1013** [comment]
Is there a way for us to contribute to this as well? I'd like to help documenting the installation and minimal setup part if I could

**Comment by guyca** [comment]
Hey @jinshin1013 Of course you can contribute. We're working on [docusaurus](https://github.com/wix/react-native-navigation/tree/docusaurus) branch and are coordinating work in [discord](https://discord.gg/DhkZjq2). Once you join discord, send us a message in the docs channel 👍

**Comment by kgshv** [comment]
"External" anchor links don't seem to work for me for some reason. Not sure why. Steps to reproduce:
- run the docs website and navigate to Playground (.../docs/playground-app)
- try clicking on the "available here" link in "You can run tests if / when you need to (list of scripts available here)"
- lands on /docs/meta-contributing#scripts but does not scroll down to the page anchor. Loading this URL directly in browser does nothing either.
Note that the right-sidebar navigation works just fine.

I feel like I'm missing something really basic here...

**Comment by kgshv** [comment]
@guyca FYI - just updated the issue to reflect current state of the docs structure

**Comment by guyca** [comment]
[New docs are up](http://wix.github.io/react-native-navigation/) - amazing work everyone 😻
