### ISSUE TITLE
iOS 13 Modal - Any way to disable swipe down to dismiss?

### ISSUE THREAD

**Issue by dmathewwws** [wix/react-native-navigation#5967]
### Issue Description
For the new iOS 13 modal. I would love the option to disable swipe down to dismiss (or have the option to go full screen like pre iOS 13 and Android).

I am using the modal for a multi screen signup flow and don't want the user to dismiss by mistake / want to give the user my own option to dismiss the modal.

---
### Environment
* React Native Navigation version: 4.8.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS 13

**Comment by jinshin1013** [comment]
You can find the options in the [doc](http://wix.github.io/react-native-navigation/#/docs/styling). You can change `modalPresentationStyle` option for modal appearance (full modal) or `modal.swipeToDismiss` option to disable that behaviour.
