### ISSUE TITLE
[v6 Android] setDefaultOptions statusBar drawBehind not working

### ISSUE THREAD

**Issue by mayconmesquita** [wix/react-native-navigation#5971]
### Issue Description

When setting **statusBar**: { **drawBehind**: true } as default option, it is not respected on Android. Only when setting it via static options () it is being applied.

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.setDefaultOptions({
    statusBar: {
      style: 'light',
      backgroundColor: '#ff6600',
      drawBehind: true,
    },
})
```

---
### Environment
* React Native Navigation version: v6.0.1
* React Native version: v0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator API 28

**Comment by jayshah123** [comment]
Issue also present when used with mergeOptions i.e. drawBehind is not respected. no relayout happens when drawBehind is set again to false.
My use case is a video player where I use mergeOptions to change statusBar config on fullscreen and vice versa.

**Comment by jayshah123** [comment]
SYSTEM_UI_FLAG_LAYOUT_STABLE seems to be already set, when I checked Presenter.java -> mergeStatusBarVisible method.
I would like my content to re-layout when statusbar is visible again. 

Multiple guides are here with android doc:
https://developer.android.com/training/system-ui/navigation
https://developer.android.com/training/system-ui/status#behind

**Comment by srfaytkn** [comment]
+1

**Comment by srfaytkn** [comment]
same issue

**Comment by mayconmesquita** [comment]
@guyca is this hard to solve? I'm trying to solve this issue, but after change the code i have to wait 30s of build time.

**Comment by farad4y** [comment]
+1

**Comment by guyca** [comment]
@mayconmesquita This should be a fairly easy fix.
The `ComponentViewController` should request the [topInsets](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/ComponentViewController.java#L110) from the presenter, where we need to merge the resolved options with the default options.

Similar to how bottom insets are applied for bottom tabs [here](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java#L186)

**Comment by ahk093** [comment]
I have the same issue.

**Comment by mayconmesquita** [comment]
@guyca Thank you! I'll investigate.

**Comment by serjek** [comment]
Hey guys any ETA on this one? Unfortunately I can not use `static options()` as I'm on ES5 (hints how to get it working on ES5 are appreciated).

**Comment by mayconmesquita** [comment]
@serjek unfortunately i don't know a ETA. I tried to fix this, but i didn't.
