### ISSUE TITLE
[v6 Android] Elevation shadow over StatusBar

### ISSUE THREAD

**Issue by mayconmesquita** [wix/react-native-navigation#5975]
### Issue Description

When setting **topBar: { elevation: 5 }** the shadow is appearing over statusbar.

### Steps to Reproduce / Code Snippets / Screenshots

![elevetation-statusbar](https://user-images.githubusercontent.com/46308804/75578125-12531e80-5a42-11ea-9720-4dc253362c39.png)

```js
Navigation.setDefaultOptions({
    topBar: {
      elevation: 5
    }
})
```                     

---
### Environment
* React Native Navigation version: v6.0.1
* React Native version: v0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator API 28

**Comment by guyca** [comment]
@mayconmesquita I'm unable to reproduce this in the playground app. Which StatusBar options did you declare when you've reproduced in your project?
