### ISSUE TITLE
[V4] When The Pagesheet, a kind of modal is open, 'Debug JS Remotely' is not working

### ISSUE THREAD

**Issue by devsoonote** [wix/react-native-navigation#5977]
### Issue Description

When The pagesheet is open, If I click 'Debug JS Remotely', App is not working

### Steps to Reproduce / Code Snippets / Screenshots

![image](https://user-images.githubusercontent.com/45555359/75537056-a977a080-5a59-11ea-921d-d026981b2501.png)
![image](https://user-images.githubusercontent.com/45555359/75537105-c2805180-5a59-11ea-89e9-003778343e3d.png)

---
### Environment
* React Native Navigation version: v4.0.6
* React Native version: v0.60.0
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): IOS All, Debug

**Comment by ItsNoHax** [comment]
Hi @devsoonote,

Thanks for reporting this issue. For us to help you further we will require a branch that reproduces this problem. Please fork the playground project and let us know how to reproduce it.
