### ISSUE TITLE
iOS10 - topBar height is not working

### ISSUE THREAD

**Issue by AlkanV** [wix/react-native-navigation#5979]
### Issue Description

Hello,

We are using 4.8.1 version of RNN and we have following issue only occur in iOS 10 devices. 

### Steps to Reproduce / Code Snippets / Screenshots

https://share.getcloudapp.com/Qwu7l75Y

---
### Environment
* React Native Navigation version: 4.8.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS 10
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 10 - all possibilities

**Comment by artashsanoyan** [comment]
Seems like you'r trying to use android specific options for iOS. As you can see the height property on topBar is a android specific option,

https://github.com/wix/react-native-navigation/blob/b4e4eff6fd3ff4fe196dc8b0ad9748ee291127e7/lib/src/interfaces/Options.ts#L476-L496

**Comment by AlkanV** [comment]
@artashsanoyan actually no, if you look at the screenshot i post it, it is happening only in ios10 not 11 or 13.
