### ISSUE TITLE
iOS app stuck at splash screen

### ISSUE THREAD

**Issue by ajonno** [wix/react-native-navigation#598]
### Issue Description
When running iOS (test) app it runs but just sits on the splash screen. The XCode log shows:
```
__nw_connection_get_connected_socket_block_invoke 4 Connection has no connected handler
[warn][tid:main][RCTEventEmitter.m:54] Sending `websocketFailed` with no listeners registered.
[]__nw_connection_get_connected_socket_block_invoke 4 Connection has no connected handler
```

### iOS Environment
XCode 8.2 (8C38)
deployment target: 8.0
simulator running iOS 10.2

### Steps to Reproduce / Code Snippets / Screenshots
For testing this library I did the following: 

- react-native init wixtest
- opened package.json and changed (to) the following
```
    "react": "15.3.1",
    "react-native": "0.37.0",
```
- deleted node_modules folder
- ```npm install```    (to get the project on 0.37)
- i then ran this updated project to ensure it built and ran. it was fine and simulator displayed the default ios view for a new react native app.

- i then closed the react packager console instance

- then: ```npm install react-native-navigation@next --save```

- followed instructions for required changes in XCode. Project then built ok in XCode.

- ran the project again. this time, it hung at the splash screen. tried closing the react packager, cleaning in Xcode, re-running. no change.

i then tried backing out the changes that i had made for react-native-navigation to see if it was the cause of the issue. for this - i removed all XCode settings (only) that are listed in the setup instructions. I didnt remove the react-native-navigation node package.

the app then ran fine, displayed the home screen view.

---
### Environment
* React Native Navigation version: ^2.0.0-experimental.157
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): simulator

**Comment by amanthegreatone** [comment]
It might be an issue with how app component is loaded from index.ios.js. I was also getting this error but then i checked the examples and figured out the problem.

index.ios.js
```

import App from './App/App'

const app = new App();
```

App.js

```
export default class App extends Component {

  constructor(props){
    super(props)

    //load some data
    this.startApp();
  }

  startApp(){
    Navigation.startSingleScreenApp({
      screen: {
        screen: 'app.Home',
        title: 'Home',
        navigatorStyle
      },
      drawer: {
        left: {
          screen: 'app.Drawer'
        }
      }
    });

  }//end of startApp

}//end of App
```

**Comment by ajonno** [comment]
thanks for this. im fairly sure i just missed a step in the setup. just started from scratch and all seems ok on ios and droid.
