### ISSUE TITLE
Disable unittest messages

### ISSUE THREAD

**Issue by lucasrodes** [wix/react-native-navigation#5980]
### Issue Description

When building my project for android (i.e. `npx react-native run-android`), all unit tests are sometimes excuted for React Native Navigation.

Is it possible to disable this?
 
### Steps to Reproduce / Code Snippets / Screenshots

It runs like ~500 tests for :react-native-navigation:testReactNative60DebugUnitTest and ~500 more for :react-native-navigation:testReactNative60ReleaseUnitTest. A frament of those is shown below.

```
com.reactnativenavigation.viewcontrollers.stack.StackControllerTest > handleBack_PopsUnlessSingleChild PASSED

com.reactnativenavigation.viewcontrollers.stack.StackControllerTest > isAViewController STANDARD_OUT
    [Robolectric] com.reactnativenavigation.viewcontrollers.stack.StackControllerTest.isAViewController: sdk=28; resources=BINARY

com.reactnativenavigation.viewcontrollers.stack.StackControllerTest > isAViewController PASSED

com.reactnativenavigation.viewcontrollers.stack.StackControllerTest > setRoot_multipleChildren STANDARD_OUT
    [Robolectric] com.reactnativenavigation.viewcontrollers.stack.StackControllerTest.setRoot_multipleChildren: sdk=28; resources=BINARY

com.reactnativenavigation.viewcontrollers.stack.StackControllerTest > setRoot_multipleChildren PASSED
```

---
### Environment
* React Native Navigation version: 4.8.1
React Native version: 0.61.5
Platform(s) (iOS, Android, or both?): Android
Device info (Simulator/Device? OS version? Debug/Release?): Device, Android 9

**Comment by jinshin1013** [comment]
This seems like odd, could you create a minimal reproduction?

**Comment by MrOggy85** [comment]
I managed to disabled them by adding this to `settings.gradle`
```
startParameter.excludedTaskNames += ':react-native-navigation:testReactNative63DebugUnitTest'
startParameter.excludedTaskNames += ':react-native-navigation:testReactNative63ReleaseUnitTest'
```
