### ISSUE TITLE
Inconsistency Android gradle plugin version

### ISSUE THREAD

**Issue by lqrz** [wix/react-native-navigation#5981]
### Issue Description
I believe there is an inconsistency between the documented Android manual installation steps & the link command. Which one of these should apply?

In the documentation, inside the Android manual installation, it is specified that we should add the following dependency in the `android/build.gradle`:
```
buildscript {
    ...
    dependencies {
        ...
        classpath 'com.android.tools.build:gradle:3.5.3' // Or higher
    }
}
```

But, if I compare it with the outcome of running `react-native link react-native-navigation`, I see that the gradle plugin version in the latter `android/build.gradle` file differs:
```
buildscript {
    ...
    dependencies {
        ...
        classpath("com.android.tools.build:gradle:3.4.2")
    }
}
```

### Steps to Reproduce / Code Snippets / Screenshots
N/A

### Environment
* React Native Navigation version: 6.0.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): N/A

**Comment by guyca** [comment]
It probably doesn't matter in your case, you can go with whichever version. I'll update the docs. Thanks for reporting 👍
