### ISSUE TITLE
RN CLI Autolinking error

### ISSUE THREAD

**Issue by lqrz** [wix/react-native-navigation#5983]
### Issue Description

I installed the library via `npx react-native link react-native-navigation` (and modifying the `minSdkVersion` in `andoid/build.gradle`).

When I run `npx react-native run-android`, the app is built and works fine, though I get the following error in the terminal:
```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-navigation (to unlink run: "react-native unlink react-native-navigation")
```

Since the lib has been linked manually,  I add an entry in the `react-native.config.js` file to prevent react native to try to autolink the lib, as in:
```
module.exports = {
    dependencies: {
        'react-native-navigation': {
            platforms: {
                android: null, // disable Android platform, other platforms will still autolink if provided
            },
        }
    }
  };
```

Now, the CLI error is not longer shown and the app is successfully built, but I get an error in the emulator:
```
TypeError: null is not an object (evaluating "this.nativeCommandsModule.setRoot()").
```

Which comes about at my first `Navigation.setRoot(...);` call:
```
[index.js]

const start = () => {
    Navigation.events().registerAppLaunchedListener(() => {
        registerScreens();
        gotoInitialising();
        // gotoLogin();
    });
};

start();
```
My question is, what extra step should I take to get the lib to work and to not have a React Native CLI error, at the same time.

### Environment
* React Native Navigation version: 6.0.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android emulator API 28 - (emulator version 29.2.1-5889189) - Debug build

**Comment by jinshin1013** [comment]
So if the project is a fresh project, after installing the package:
```bash
yarn add react-native-navigation
``` 
All you have to run is `react-native link react-native-navigation` as from `V5` the team added the linking script which will modify all the necessary native changes required. 

That should set you up with the working project. However if you, for some reason, required to do this manually, you can reference my [boilerplate project](https://github.com/jinshin1013/rnn-boilerplate) and look at the `./android` files line by line. You will need to look at these files:

- `./android/settings.gradle`
- `./android/build.gradle`
- `./android/app/build.gradle`
- `./android/src/.../java/your/namespace/MainActivity|MainApplication.java`

Also no need to add `react-native-navigation` in your `react-native.config.js` file.

**Comment by ida-n** [comment]
Hi Jin,

I followed the steps bellow on a fresh project:
```
yarn add react-native-navigation
yarn react-native link react-native-navigation
```
and I also get:
```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-navigation (to unlink run: "react-native unlink react-native-navigation")
```
as well as:
```
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 18 declared in library 
```
when I run `yarn react-native run-android`.

**Comment by jinshin1013** [comment]
@ida-n  Ooof, the autolink script does not modify the `minSdkVersion` in `android/build.gradle` file. If you change that to anything over 19, it should work fine. I could probably create a PR that fixes this.

Also you can probably don't worry about the first error regarding it's manually linked or something.

**Comment by ida-n** [comment]
With `minSdkVersion = 19` the app builds. I am ignoring the unlink error for now since it is not stopping the build. Thank you :)

**Comment by lqrz** [comment]
Hi @jinshin1013 Thanks for your answer, I understand the changes the "link script" does. I was originally wondering if there was a scenario where we link the lib and we get rid of the react-native-cli error (it is still unclear to me why we need to manually link the lib and also let react-native autolink it afterwards as well, do you have any pointers on that / or places I should look at to figure it out?) Thanks again!

**Comment by guyca** [comment]
@lqrz Autolink only makes your project "be aware" of the native dependency. It only adds RNN as a dependency to your project. If a dependency requires changes to your project, you are requires to either do them manually or, like in our case, run a "link script" which attempts to do all manual changes for you.
