### ISSUE TITLE
[V6] Can't use modalPresentationStyle popOver

### ISSUE THREAD

**Issue by AlexDM0** [wix/react-native-navigation#6004]
### Issue Description

If you use the option 
```
modalPresentationStyle: OptionsModalPresentationStyle.popOver
```

You get the error:
![2020-03-05 17 44 59](https://user-images.githubusercontent.com/5363277/76003992-1cc15c80-5f09-11ea-8335-560dc98bb99b.png)

So then you do not use the provided enum:
```js
export enum OptionsModalPresentationStyle {
  formSheet = 'formSheet',
  pageSheet = 'pageSheet',
  overFullScreen = 'overFullScreen',
  overCurrentContext = 'overCurrentContext',
  currentContext = 'currentContext',
  popOver = 'popOver',
  fullScreen = 'fullScreen',
  none = 'none'
}
```

but just type "popover".

The problem at that point is, typescript keeps reporting an error.

---
### Environment
* React Native Navigation version: 6.0.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): iphone x

**Comment by harveyconnor** [comment]
I made a pull for this.
https://github.com/wix/react-native-navigation/pull/5963

**Comment by guyca** [comment]
Seems to be fixed now.
