### ISSUE TITLE
Bottom tab text cut off/truncated after changing fontWeight to semibold or bold.

### ISSUE THREAD

**Issue by drewhamlett** [wix/react-native-navigation#6005]
### Issue Description

After upgrading to 6.1.0 , bottom text is cut off after changing the fontWeight to 'semibold' or 'bold' on the bottomTab property.  'light' or 'regular' doesn't affect the truncation.

### Steps to Reproduce / Code Snippets / Screenshots

![Screen Shot 2020-03-05 at 3 33 49 PM](https://user-images.githubusercontent.com/1056587/76023645-86d10600-5ef7-11ea-9f70-a381b25843be.png)

```js
 bottomTab: {
      fontWeight: 'semibold',
}
```
---
### Environment
* React Native Navigation version: 6.1.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by guyca** [comment]
Hey @drewhamlett Can you please check if this happens on iOS 12 as well?

**Comment by drewhamlett** [comment]
@guyca This is not happening on iOS 12.4

**Comment by shanereid** [comment]
Same issue. Happens with regular fonts for me too. (ApercuPro I'm using)

RN 0.61.2 + RNN 6.1.0
