### ISSUE TITLE
translucent bottomTab does not work after upgrading to 6.1.0

### ISSUE THREAD

**Issue by drewhamlett** [wix/react-native-navigation#6006]
After upgrading to 6.1.0 the translucent bottomTab does not work.

### Steps to Reproduce / Code Snippets / Screenshots

```js
  bottomTabs: {
      tabsAttachMode: 'onSwitchToTab',
      hideShadow: false,
      translucent: true,
      drawBehind: false,
    }

```
---
### Environment
* React Native Navigation version: 6.1.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by hadnet** [comment]
I'm using v6.5 and translucent doesn't work either.

**Comment by hadnet** [comment]
Trying with v6.9.1 and still translucent tabbar doesnt work!

**Comment by hadnet** [comment]
Trying with v6.9.1 and still bottomTabs.translucent option doesnt work! The tabbar background gets white and not translucent. Jesus..

**Comment by yogevbd** [comment]
Do you use `SafeAreaView`? It will cause your layout to render above the `bottomTabs` and the `translucent` option will have no effect.
When you use `ScrollView`, `SafeAreaView` is not needed.

**Comment by drewhamlett** [comment]
This works in latest for me! Version `6.11.0`
