### ISSUE TITLE
react-native-navigation v1 still can use in React-native 0.61.5 ? 

### ISSUE THREAD

**Issue by lyicelee** [wix/react-native-navigation#6007]
### Issue Description

React-native-navigation v1 can still use in React-native 0.61.5 ? 

If it can. Please teach how to install it in to React-native 0.61.5 Project.

thank you.

---
### Environment
* React Native Navigation version: 1.1.458
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by guyca** [comment]
Hey @lyicelee I recommend you upgrade to latest RNN. This [section](https://wix.github.io/react-native-navigation/#/docs/top-level-api-migration) should help you get started on migrating your project

**Comment by witalobenicio** [comment]
@guyca For some projects would take a lot of effort due to size of application or architecture problems...It's possible to use v1 with RN 0.62?
