### ISSUE TITLE
[V6] TypeError: null is not an object (evaluating 'this.nativeCommandsModule.setDefaultOptons')

### ISSUE THREAD

**Issue by ridik1803** [wix/react-native-navigation#6009]
### Issue Description

`TypeError: null is not an object (evaluating 'this.nativeCommandsModule.setDefaultOptons')`

![Screenshot_2020-03-06-13-08-37-881_com taxi135 driver](https://user-images.githubusercontent.com/3540152/76074078-d244ec00-5fab-11ea-8fda-34c69b9de47c.png)

### Steps to Reproduce / Code Snippets / Screenshots

Update from 4.8.4 to 6.1.0

---
### Environment
* React Native Navigation version: 6.1.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All devices

**Comment by guyca** [comment]
Hey @ridik1803 
Could you please post a reproduction of this issue?

**Comment by ridik1803** [comment]
@guyca I have an [error](https://github.com/wix/react-native-navigation/issues/5996) and to fix it i try to upgrade library version (using this [manual](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#upgrading-from-v4)). After upgrading I have this error

**Comment by ridik1803** [comment]
@guyca In my App.js I have this code and here the error occurs
`Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setDefaultOptions({
        animations: {
            push: {
                waitForRender: true
            }
        },
        layout: {
            backgroundColor: Theme.authorization.backgroundColor
        }
    });

    Navigation.setRoot({
        root: {
            component: {
                name: SPLASH_SCREEN
            }
        }
    });
});`

**Comment by ridik1803** [comment]
Re-read the instructions and realized that I had not completed all the points. That helped

**Comment by jaimeagudo** [comment]
Excuse me @ridik1803 , would you please share what was the origin of the above bug ^? Thanks in advance
