### ISSUE TITLE
Providing fontWeight and fontFamily breaks custom font family in titles (And possibly other places)

### ISSUE THREAD

**Issue by simonmitchell** [wix/react-native-navigation#6010]
### Issue Description

If you provide both a `fontWeight` and `fontFamily` in styling objects for `topBar.title` and `topBar.largeTitle` then on iOS the system font is used.

### Steps to Reproduce / Code Snippets / Screenshots

- Add a custom font into your application
- Add `fontWeight` and `fontFamily` values to your RNN styling
- Observe custom font face is ignored

The issue lies with this `if` statement in `RNNFontAttributesCreator`

```objc
CGFloat resolvedFontSize = [self resolveFontSize:currentFont fontSize:fontSize];
    
    titleTextAttributes[NSForegroundColorAttributeName] = color;
    
   // If font weight is provided, all other attributes are ignored!
    if (fontWeight) {
        titleTextAttributes[NSFontAttributeName] = [UIFont systemFontOfSize:resolvedFontSize weight:[RCTConvert UIFontWeight:fontWeight]];
    } else if (fontFamily){
        titleTextAttributes[NSFontAttributeName] = [UIFont fontWithName:fontFamily size:resolvedFontSize];
    } else if (fontSize && currentFont) {
        titleTextAttributes[NSFontAttributeName] = [UIFont fontWithDescriptor:currentFont.fontDescriptor size:resolvedFontSize];
    } else if (fontSize) {
        titleTextAttributes[NSFontAttributeName] = [UIFont systemFontOfSize:resolvedFontSize];
    }
```

---
### Environment
* React Native Navigation version: 6.0.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS (Unsure about Android)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iOS 13.0, Debug

**Comment by simonmitchell** [comment]
@guyca @yogevbd I have the beginnings of a PR that I thought would resolve this, however after testing with the custom font we're using it seems like you may need to go a step further and find the closest matching font like in RCCFont like so:
```
// Get the closest font that matches the given weight for the fontFamily
  CGFloat closestWeight = INFINITY;
  for (NSString *name in [UIFont fontNamesForFamilyName:familyName]) {
    UIFont *match = [UIFont fontWithName:name size:fontSize];
    if (isItalic == isItalicFont(match) &&
        isCondensed == isCondensedFont(match)) {
      CGFloat testWeight = weightOfFont(match);
      if (ABS(testWeight - fontWeight) < ABS(closestWeight - fontWeight)) {
        font = match;
        closestWeight = testWeight;
      }
    }
  }
```

**Comment by simonmitchell** [comment]
This has been accepted and assigned to someone, is it not a bit premature for the bot to be closing it for inactivity @yogevbd? ☺️

**Comment by guyca** [comment]
@simonmitchell Can you please verify this bug still happens on 6.4.0?

**Comment by yogevbd** [comment]
@simonmitchell In case you want to use custom fonts you don't need the fontWeight.. You can provide the full font name through `fontFamily`.
It was added in order to support system font weight.. we should clear that out in the docs.

**Comment by simonmitchell** [comment]
Ahhh that's interesting thanks @yogevbd!  @guyca sorry I didn't get time to test, been incredibly busy the past few weeks as we have a lot of clients who are needing to get updates out left-right-and centre with Covid-19 info!

If we could just update the docs to make it clear, I'm happy for this to be closed ☺️

Thanks both!

**Comment by simonmitchell** [comment]
Oops, didn't realise that would auto-close it sorry!

**Comment by guyca** [comment]
No worries @simonmitchell , we'll clearify the docs 👍
