### ISSUE TITLE
[V6] Unable to resolve module './adapters/SharedElement'

### ISSUE THREAD

**Issue by TylerNRobertson** [wix/react-native-navigation#6011]
### Issue Description

Install version 6.0.0+ of RNN. Run on IOS and the error should appear.

### Steps to Reproduce / Code Snippets / Screenshots
1. Install RNN
2. Run IOS App

Error:
<img width="1321" alt="Screen Shot 2020-03-06 at 11 08 16 AM" src="https://user-images.githubusercontent.com/23481122/76095625-fc41e280-5f9a-11ea-98fb-2753a63e5b80.png">

---
### Environment
* React Native Navigation version: 6.1.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator IOS 13.3

**Comment by guyca** [comment]
hmm this file was indeed deleted in v6. Are you using the old shared element api? if not, try resetting cache when running the packager: `npm run start -- --reset-cache`

**Comment by bang88** [comment]
@guyca I have another issue when I click the `SharedElement` demo it crashes.

- clone the repo
- install deps
- yarn start
- open xcode run in ios emulator
- click Options -> click Shared Element

![image](https://user-images.githubusercontent.com/433259/76139376-11496f00-608a-11ea-9f42-544849e1dba3.png)

**Comment by guyca** [comment]
@bang88 @TylerNRobertson I wasn't able to reproduce this on a fresh clone. This leads me to think it's a caching issue. Please try starting the packager with  `watchman watch-del-all && npm run start -- --reset-cache`.

**Comment by TylerNRobertson** [comment]
@guyca you were right caching issue. Thanks!

**Comment by chuttam** [comment]
Came here after hitting the same issue on an RNN upgrade effort to v6. Can confirm that these steps to restart and clear package manager resolved the issue:

> Please try starting the packager with watchman watch-del-all && npm run start -- --reset-cache
