### ISSUE TITLE
[v6] ReactNativeNavigation/ReactNativeNavigation.h file not found

### ISSUE THREAD

**Issue by chrise86** [wix/react-native-navigation#6012]
On a brand new app, after installing and linking with `react-native link react-native-navigation`, running via `react-native run-ios` produces the following error:

Versions:
```
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-navigation": "^6.1.0",
```

Manually adding:
```
 $(SRCROOT)/../node_modules/react-native-navigation/lib/ios
```
to the header search paths doesn't help either.

Adding the cocoapod to the Podfile fixes, but results in:
```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-navigation (to unlink run: "react-native unlink react-native-navigation")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
```

**Comment by EnricoGallus** [comment]
I had exactly the same problem. 
I was able to fix it by updating the podfile.
`cd ios`
`pod install`

I got some other problems with react-native-vector-icons due to the `pod install`, but looks like you don't use this package, so you should be fine.

Hope this helps you too! Happy coding

**Comment by kuzzmi** [comment]
Surprised that no updates here.

I have exact same issue after fresh `pod install`. Adding manually headers didn't work for me either.

By the way, I had a similar issue with `react-native-maps`, but there adding a path manually did work.

**Comment by zabojad** [comment]
@kuzzmi How did you solve it? I'm having the same problem on aa freshly setup project and after running `pod install`.

**Comment by kuzzmi** [comment]
@zabojad I probably had some interference with some other solutions. I don't remember 100%, but I remember purging all workarounds and **just** defining paths manually as well as use the most up-to-date `pod` version.

**Comment by zabojad** [comment]
I've just updated from Cocoapods 1.8.x to 1.9.x and it now works fine... Thanks @kuzzmi !
