### ISSUE TITLE
[v6] Shared element transition crashes on iOS

### ISSUE THREAD

**Issue by chrise86** [wix/react-native-navigation#6013]
When using the following transition:
```tsx
const MULTIPLIER = 1.15
const LONG_DURATION = 350 * MULTIPLIER
const SHORT_DURATION = 190 * MULTIPLIER

Navigation.push(this.props.componentId, {
  component: {
    name: 'Marina',
    passProps: {
      marina,
    },
    options: {
      animations: {
        push: {
          sharedElementTransitions: [
            {
              fromId: `image${marina.id}`,
              toId: 'image',
              duration: LONG_DURATION,
            },
          ],
          elementTransitions: [
            {
              id: 'description',
              alpha: {
                from: 0,
                duration: SHORT_DURATION,
              },
              translationY: {
                from: 16,
                duration: SHORT_DURATION,
              },
            },
          ],
        },
      },
    },
  },
})
```

I get a crash that, when run via Xcode points to the following:

```obj-c
- (UIView *)topMostView:(UIView *)view { // Thread 1: EXC_BAD_ACCESS (code=2, address=0x7ffeeb36ffd8)
    if ([view isKindOfClass:[RNNReactView class]]) {
        return view;
    } else {
        return [self topMostView:view.superview];
    }
}
```

I've tried with and without the `elementTransitions` option, but what I have above is a replica of the example. I've also tried adding an `interpolation` option to the transition.

Versions:
```
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-navigation": "^6.1.0",
```

**Comment by chrise86** [comment]
Doh... turns out it was a typo: `nativeId` instead of `nativeID`. Closing, leaving it here incase anyone else makes the same mistake. TypeScript is not liking either property, so wasn't getting autocompletion or reliable TS errors.

**Comment by SudoPlz** [comment]
I get the same error but I'm definitely not mis-spelling the `nativeID` prop. I wonder what the underlying reason for that is.

I'm using nativeID inside a component that's in a flat list, I wonder if it's related..

**Comment by SudoPlz** [comment]
Ok similar issue here https://github.com/wix/react-native-navigation/issues/6609
