### ISSUE TITLE
How to trigger when i onPress TabBar in Navigation.startTabBasedApp({tabs})

### ISSUE THREAD

**Issue by trung1008** [wix/react-native-navigation#602]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by quoctuams** [comment]
I am also interested in this. How to call a function whenever user click on a tab, such as notification, so that the badge displayed can be reset to zero :)

**Comment by Asleepace** [comment]
I am also very curios if this is possible? I think a sort of "hack" to achieve this might be to actually open up a new screen, which redirects back instantly and also calls a function. But is there a better way to accomplish this behavior?

**Comment by guyca** [comment]
[Listening to tab selected events](https://wix.github.io/react-native-navigation/#/screen-api?id=listening-to-tab-selected-events)
