### ISSUE TITLE
[V6] Customizing screen animations not working 

### ISSUE THREAD

**Issue by tiennv-0883** [wix/react-native-navigation#6020]
### Issue Description

I upgraded from React-Native-Navigation 4. to 6.
I use the setting:

```
Navigation.push(props.componentId, {
      component: {
        name: 'AddTheme',
        options: {
          popGesture: true,
          backgroundImage: url,
          animations: {
            push: {
              waitForRender: false,
              content: {
                alpha: {
                  from: 0,
                  to: 1,
                  duration: 300,
                  interpolation: 'accelerate',
                },
              },
            },
            pop: {
              content: {
                alpha: {
                  from: 1,
                  to: 0,
                  duration: 300,
                  interpolation: 'decelerate',
                },
              },
            },
          },
        },
      },
    });
```

And Customizing screen animations not working .
Please help me 
---
### Environment
* React Native Navigation version: 6.1.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): IOS and Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 11 iOS 13.3 Debug

**Comment by guyca** [comment]
Hey @tiennv-0883 
I'm unable to reproduce this in the playground app. Please push a reproduction in the playground app

**Comment by ovcovc** [comment]
I can confirm this does not work on iOS.

```
animations: {
          push: {
            enabled: true,
            content: {
              alpha: {
                from: 0,
                to: 1,
                duration: 300,
                interpolation: 'accelerate',
              },
            },
          },
          pop: {
            enabled: true,
            waitForRender: true,
            content: {
                alpha: {
                    from: 1,
                    to: 0,
                    duration: 300,
                    interpolation: 'accelerate',
                },
            },
          },
```
The code I posted above does not seem to work - the default push segue animation is triggered. If I set enabled to false, no animation is played at all (it kinda makes sense).

**Comment by guyca** [comment]
@ovcovc I'm unable to reproduce the issue. Please clone the library and push a branch with a reproduction to the playground app.

**Comment by witalobenicio** [comment]
@guyca The problem for me is that the popMethod makes the previous screen all black.
