### ISSUE TITLE
RNCSafeAreaView was not found in the UIManager

### ISSUE THREAD

**Issue by ASchwad** [wix/react-native-navigation#6021]
### Issue Description

I am trying out Version 5 of this library and encountered the following error when going through the stack navigator example from the documentation. 

Invariant Violation: requireNativeComponent: "RNCSafeAreaView" was not found in the UIManager.

This error is located at:
    in RNCSafeAreaView (at src/index.tsx:28)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:379)
    in RCTView (at View.js:35)
    in View (at StackView.tsx:378)
    in StackView (at createStackNavigator.tsx:67)
    in StackNavigator (at App.js:103)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:267)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:39)
    in ThemeProvider (at NavigationContainer.tsx:38)
    in ForwardRef(NavigationContainer) (at App.js:102)
    in Dashboard (at cmNativeApp/index.js:15)
    in LocalizeProvider (at cmNativeApp/index.js:14)
    in Provider (at cmNativeApp/index.js:13)
    in RNRedux (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)

### Steps to Reproduce / Code Snippets / Screenshots
```
import React, {Component} from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

const Stack = createStackNavigator();

function Dashboard() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Dashboard" component={LoginScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default Dashboard;
```

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: 5.0.9
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by ASchwad** [comment]
Questionable closing of the issue.

Nevertheless, I upgraded my react-native version and fixed the bug with it - still, i would have like to know how to fix it without changing the react-native version.

**Comment by dicka88** [comment]
same errro :"

    "dependencies": {
        "@react-native-community/masked-view": "^0.1.7",
        "@react-navigation/native": "^5.0.9",
        "@react-navigation/stack": "^5.1.1",
        "expo-constants": "^8.0.0",
        "install": "^0.13.0",
        "native-base": "^2.13.12",
        "react": "16.9.0",
        "react-native": "0.61.5",
        "react-native-gesture-handler": "^1.6.0",
        "react-native-reanimated": "^1.7.0",
        "react-native-safe-area-context": "^0.7.3",
        "react-native-screens": "^2.3.0",
        "react-navigation": "^4.2.2"
    },

Android -> redmi note 8, android 10, cusrom PE

**Comment by cursivedgreat** [comment]
same error

**Comment by aphougat** [comment]
its very simple. Please go into the iOS folder of your react-native project and fire the the command  "pod install"

**Comment by RUANDUARTE03** [comment]
I have the same problem, I have the same dependencies

**Comment by felo89** [comment]
> its very simple. Please go into the iOS folder of your react-native project and fire the the command "pod install"

it works for me! thank you!

**Comment by AdiYElisha** [comment]
I don't have an ios folder. what should I do?

**Comment by jcan1995** [comment]
@AdiYElisha You would need to run `expo eject` to get the ios and android folders.
@aphougat That didn't work for me unfortunately. Still getting the same error
`"@react-native-community/masked-view": "^0.1.10",
    "@react-native-firebase/app": "^7.1.0",
    "@react-native-firebase/auth": "^7.1.0",
    "@react-navigation/native": "^5.4.3",
    "@react-navigation/stack": "^5.4.0",
    "expo": "~37.0.3",
    "expo-splash-screen": "^0.2.3",
    "expo-updates": "~0.2.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.5",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^2.0.0",
    "react-native-screens": "^2.8.0",
    "react-native-unimodules": "~0.9.0",
    "react-native-web": "~0.11.7"`

**Comment by ProdeveloperR** [comment]
> I don't have an ios folder, I use expo and running on android emulator.

@AdiYElisha You need to run "expo eject" to get seperate ios and android folders.

**Comment by sohantandle1997** [comment]
I am working on expo-cli project and im facing the same issue. Please help me!

**Comment by premnathkulal1** [comment]
If you using Expo than use expo command to install the packages.
`expo install <package name>`

**Comment by daniellupascu** [comment]
I am having the same issue here, and it is super frustrating! Running on an Android Emulator! @guyca, has this been a know issue?

**Comment by AdriiMesa** [comment]
I have solved it installing react-native-safe-area-view dependencies and then doing 'expo update'
That works for me!

**Comment by tyrone2kx** [comment]
I had this issue right now. Solved it by downgrading react-native-safe-area-context to version 0.6.0.

**Comment by zholmes1** [comment]
If you're using Expo, make sure you are installing `react-native-safe-area-context` with `expo install`, not `yarn install`

**Comment by RohanKhedekar21** [comment]
> its very simple. Please go into the iOS folder of your react-native project and fire the the command "pod install"

what should i do for android without expo

**Comment by phattanle2009** [comment]
> its very simple. Please go into the iOS folder of your react-native project and fire the the command "pod install"
You have saved my day! This comment is very helpful. Big thanks.

**Comment by Maxeeezy** [comment]
I had problems with my android and this did the trick for me:

```
npm install react-native-safe-area-context
react-native link react-native-safe-area-context
```
I simply forgot to link the package. :/

**Comment by Benetzz** [comment]
`pod install` did not work for me. 

Follow the guide to react-navigation for bare app here: https://reactnavigation.org/docs/getting-started/#installing-dependencies-into-a-bare-react-native-project

- first add all needed deps: `yarn add react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view`
- run `npx pod-install ios`
- add this to the top of the entry file: `import 'react-native-gesture-handler';`

This is what worked for me.

**Comment by hoangdoanfinx** [comment]
pork pork

**Comment by RustyRishii** [comment]
I had this same error, If you are using Expo, Just use the command. 
`npx expo install expo-updates`

It started working again
