### ISSUE TITLE
 Issues 2 duplicate symbols for architecture x86_64 Incompatibility with React-Native-Keyboard-Input

### ISSUE THREAD

**Issue by AugustoAleGon** [wix/react-native-navigation#6022]
### Incompatibility with React-Native-Keyboard-Input

I am upgrading to the latest version of `react-native-navigation` [6.1.1] with the latest version of `react-native-keyboard-input` [6.0.0], the problem happens on iOS when I am trying to build.

### Steps to Reproduce / Code Snippets / Screenshots

Install the latest version of `react-native-navigation` with `react-native-keyboard-input` and then just run with `react-native run-ios`

---
### Environment
* React Native Navigation version: 6.1.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

This is the trace in XCode:

```
duplicate symbol '_LNInterpolationBehaviorUseRGBColorSpace' in:
    /Users/myuser/Library/Developer/Xcode/DerivedData/RocketChatRN-eherffeomkuvbtbrkwpnkcongycw/Build/Products/Debug-iphonesimulator/ReactNativeKeyboardInput/libReactNativeKeyboardInput.a(Color+Interpolation.o)
    /Users/myuser/Library/Developer/Xcode/DerivedData/RocketChatRN-eherffeomkuvbtbrkwpnkcongycw/Build/Products/Debug-iphonesimulator/ReactNativeNavigation/libReactNativeNavigation.a(Color+Interpolation.o)
duplicate symbol '_LNInterpolationBehaviorUseLABColorSpace' in:
    /Users/myuser/Library/Developer/Xcode/DerivedData/RocketChatRN-eherffeomkuvbtbrkwpnkcongycw/Build/Products/Debug-iphonesimulator/ReactNativeKeyboardInput/libReactNativeKeyboardInput.a(Color+Interpolation.o)
    /Users/myuser/Library/Developer/Xcode/DerivedData/RocketChatRN-eherffeomkuvbtbrkwpnkcongycw/Build/Products/Debug-iphonesimulator/ReactNativeNavigation/libReactNativeNavigation.a(Color+Interpolation.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by AugustoAleGon** [comment]
@guyca @yogevbd any news?

**Comment by joewired** [comment]
Similar issue:

"react-native": "0.62.0-rc.5"
"react-native-ui-lib": "5.4.1"
"react-native-navigation": "^6.2.0"

duplicate symbol '_LNInterpolationBehaviorUseRGBColorSpace' in:
    /Library/Developer/Xcode/DerivedData/rwtl-hkykvjdnvqjjsneswnddljhuhfht/Build/Products/Debug-iphonesimulator/ReactNativeNavigation/libReactNativeNavigation.a(Color+Interpolation.o)
    /Users/joegarcia/Library/Developer/Xcode/DerivedData/rwtl-hkykvjdnvqjjsneswnddljhuhfht/Build/Products/Debug-iphonesimulator/ReactNativeUiLib/libReactNativeUiLib.a(Color+Interpolation.o)
duplicate symbol '_LNInterpolationBehaviorUseLABColorSpace' in:
    /Library/Developer/Xcode/DerivedData/rwtl-hkykvjdnvqjjsneswnddljhuhfht/Build/Products/Debug-iphonesimulator/ReactNativeNavigation/libReactNativeNavigation.a(Color+Interpolation.o)
    /Library/Developer/Xcode/DerivedData/rwtl-hkykvjdnvqjjsneswnddljhuhfht/Build/Products/Debug-iphonesimulator/ReactNativeUiLib/libReactNativeUiLib.a(Color+Interpolation.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AugustoAleGon** [comment]
@yogevbd Thanks Appreciate it.

**Comment by AugustoAleGon** [comment]
@yogevbd Today I got the same error after upgrade to the latest version of `react-native-navigation`. Even in a new app.
