### ISSUE TITLE
[v6] Issues with Dark-Mode

### ISSUE THREAD

**Issue by djschilling** [wix/react-native-navigation#6028]
### Issue Description

I have the property `UIUserInterfaceStyle` set to `Light`. If now dark mode is enabled on ios the status bar is only barely visible:

![Simulator Screen Shot - iPhone 11 - 2020-03-11 at 10 38 09](https://user-images.githubusercontent.com/3503166/76402944-6df7a300-6384-11ea-8a42-731f2e981b7e.png)

Then i tried to remove the property `UIUserInterfaceStyle` to see if this helps. Then it looks like this:
![Simulator Screen Shot - iPhone 11 - 2020-03-11 at 10 39 33](https://user-images.githubusercontent.com/3503166/76403092-b0b97b00-6384-11ea-9b75-d3bfe853488c.png)

When i do not use the `largeTitle` it looks better, but still not good:

![Simulator Screen Shot - iPhone 11 - 2020-03-11 at 10 40 05](https://user-images.githubusercontent.com/3503166/76403129-be6f0080-6384-11ea-882d-152c140117fd.png)

I tried out different options to style the background but it seams nothing has an effect: https://wix.github.io/react-native-navigation/#/docs/styling

What i want is to be able to use the `largeTitle` and that it is functioning on dark mode.

How should i handle this?

---
### Environment
* React Native Navigation version: 6.1.2
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 11 Simulator iOS 13.3

**Comment by djschilling** [comment]
o guess nothing changed here?

**Comment by djschilling** [comment]
😢

**Comment by djschilling** [comment]
not fixed

**Comment by witalobenicio** [comment]
Not fixed

**Comment by navasiloy** [comment]
not fixed

**Comment by jehee-choi** [comment]
seems still not fixed

**Comment by sallar** [comment]
@djschilling unrelated question, are you using a UI library for those list styles or is it custom?

**Comment by djschilling** [comment]
@sallar they are custom

**Comment by sallar** [comment]
@djschilling have you tried setting `statusBar.style` to `dark` when setting `defaultOptions`?

**Comment by djschilling** [comment]
@sallar Thanks this is working for us.
