### ISSUE TITLE
Duplicated symbols when using  react-native-ui-lib

### ISSUE THREAD

**Issue by eladgel** [wix/react-native-navigation#6034]
### Issue Description

Duplicated symbols when using  react-native-ui-lib: 5.4.1
Yarn installed both libraries on a fresh project, I get these
### Steps to Reproduce / Code Snippets / Screenshots

![image](https://user-images.githubusercontent.com/412137/76603067-f3aa5880-6514-11ea-9157-5a331f877fc2.png)

---
### Environment
* React Native Navigation version: 6.2.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
This will be fixed in the next version, for now you can use `6.2.0-snapshot.875` which contains the fix.
