### ISSUE TITLE
[v6] not work option: layout

### ISSUE THREAD

**Issue by aspidvip** [wix/react-native-navigation#6035]
### Issue Description

not work option -> layout -> backgroundColor

```
stack: {
                              children: [
                                {
                                  component: {
                                    name: MY_USER,
                                    options: {
                                      layout: {
                                        backgroundColor: '#EFEFF4',
                                      },
```

everything used to work

---
### Environment
* React Native Navigation version:  "^6.2.0-snapshot.875",
* React Native version: "0.61.5",
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device 13.3

**Comment by guyca** [comment]
@aspidvip If you want to set a background color to a component, then you probably want to use the `componentBackgroundColor` option.

**Comment by ArnasJack** [comment]
I have the same issue. Also, the default background color is now black, whenever you navigate to a new screen you can see a flash of black color before it changes color based on your screen.

**Comment by olegdev** [comment]
Hm..  from docs i see that `componentBackgroundColor ` is for android only.
Am i wrong?

And why `backgroundColor ` not work?

**Comment by vedovato** [comment]
@olegdev in V6 i can confirm `componentBackgroundColor` works for both while `backgroundColor` is Android only 💁‍♂️

**Comment by devattendant** [comment]
@olegdev True, though it was different before v6 (but I used v2 before, so hard to compare). Either the docs are misleading here or I am misunderstanding something.
