### ISSUE TITLE
v6 in use react-native-community/viewpager conflict bottomTabs disappear 

### ISSUE THREAD

**Issue by skyliwq** [wix/react-native-navigation#6037]
react-native-navigation Version v6 in use react-native-community/viewpager conflict bottomTabs disappear

**Comment by guyca** [comment]
Hey @skyliwq Please fork the project and push a branch with a reproduction so we can debug this issue.

**Comment by mrquanghuy** [comment]
I using v6.3 have same here :( how to fix it

**Comment by mamoru0217** [comment]
This problem starts from [6.1.0](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#610), so it seems that one or some of changes in 6.1.0 causes this. (I can't make time to investigate more now 😂)

**Comment by skyliwq** [comment]
+1

**Comment by guyca** [comment]
Hey @skyliwq @mamoru0217 @mrquanghuy  Please fork the project and push a branch with a reproduction so we can debug this issue.

**Comment by mrquanghuy** [comment]
seems like this problem was gone when I updated RNN 6.4.0 and viewpager 3.3.0

**Comment by mamoru0217** [comment]
> seems like this problem was gone when I updated RNN 6.4.0 and viewpager 3.3.0

same as @mrquanghuy 👍

**Comment by guyca** [comment]
Glad to hear it's resolved! 👍
