### ISSUE TITLE
How to style bottomTabs ?

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#6046]
### Issue Description

Sorry for asking a question that might be a bit simple but I have to use `bottomTabs` for the first time and I do not see How I can style them (the tabs).

How can I style bottom tabs? (colors, text font and size, keep texts displayed even if not active, different icon if active, etc...)

---
### Environment
* React Native Navigation version: 6.2.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by didrikkvanvik** [comment]
There are multiple ways you can style your bottom tabs. For example to set a default _text color_, _selected tect color_, _font size_, and _font family_ you can do the following:

```
 Navigation.setDefaultOptions({
        bottomTab: {
            textColor: colors.greys.grey,
            selectedTextColor: colors.brand.blue,
            fontSize: 12,
            fontFamily: '...',
        },
    })
```

[Link](https://github.com/wix/react-native-navigation/blob/master/lib/src/interfaces/Options.ts ) to the `Options.d.tx` documentation. Really easy to read!

I specify the various icons and texts for each bottom tab when i use `Navigation.setRoot` when the app starts by:

```
Navigation.setRoot({
        root: {
            bottomTabs: getBottomTabs(),
            stack: {
                id: 'Stack',
                children: [{ component: { name: 'Home' } }],
            },
        },
    })
```

A stack of bottom tabs can look like this (`getBottomTabs`):
```
{
    children: [
        {
            id: 'bottomTabId',
            stack: {
                children: [
                    {
                        component: {
                            name: 'componentId',
                            options: {
                                bottomTab: {
                                    text: 'name',
                                    selectedIcon: SelectedIcon,
                                    icon: Icon,
                                },
                            },
                        },
                    },
                ],
            },
        },
    ],
    options: {
        bottomTabs: {
            animate: false,
            backgroundColor: colors.brand.white,
            titleDisplayMode: 'alwaysShow',
        },
    },
}
```
Hope this clears up some of the confusion :)

**Comment by zabojad** [comment]
Thanks a lot @didrikkvanvik!
I should indeed stop searching into the project documentation and instead check out the ts files directly...

**Comment by zabojad** [comment]
It's pretty good. The only thing I miss is a `selectedFontFamily` option in the `OptionsBottomTab` object. @guyca do you think we could add that?

**Comment by Manikanta-GEP** [comment]
hi all, i am also looking for selectedFontFamily option for bottom tab
