### ISSUE TITLE
Pushing a screen with animated change of bottomTab visibility leads to wrong layout on iOS

### ISSUE THREAD

**Issue by hubermat** [wix/react-native-navigation#6049]
### Issue Description

From a view with bottomTabs, when I push a new screen that hides the bottomTabs animated (with animate=true in the bottomTabs options), in the pushed screen, views within a SafeAreaView do not layout correctly, i.e. Layout is not triggered during/after the hide animation.

### Steps to Reproduce / Code Snippets / Screenshots

From a view with bottomTabs, when I push a new screen like this:

```js
Navigation.push(componentId, {
    component: {
        name: name,
        passProps: props,
        options: { 
            bottomTabs: {
                visible: false,
                drawBehind: true,
                animate: true 
            }
        }
    }
});
```
the pushed screen does not layout correct:

Parent screen:
![Bildschirmfoto 2020-03-16 um 15 06 18](https://user-images.githubusercontent.com/1336497/76766574-7f7fe700-6798-11ea-8016-3dadb0723c42.png)

iPhone 11, with animate: true
![Bildschirmfoto 2020-03-16 um 15 06 25](https://user-images.githubusercontent.com/1336497/76766577-8149aa80-6798-11ea-9977-379f044197c1.png)

iPhone 11, with animate: false
![Bildschirmfoto 2020-03-16 um 15 06 34](https://user-images.githubusercontent.com/1336497/76766580-81e24100-6798-11ea-9a5f-31deff1d4186.png)

iPhone 8, with animate: true
![Bildschirmfoto 2020-03-16 um 15 13 25](https://user-images.githubusercontent.com/1336497/76766725-b950ed80-6798-11ea-980b-95894fccdbc6.png)

iPhone 8, with animate: false
![Bildschirmfoto 2020-03-16 um 15 13 33](https://user-images.githubusercontent.com/1336497/76766729-b9e98400-6798-11ea-8755-e4cde96252c8.png)

This is how the pushed screen renders:
```js
return (
            <SafeAreaView style={{ flex: 1, backgroundColor: '#00f'}}>
                <View style={{ flex: 1, backgroundColor: '#f00'}} />
            </SafeAreaView>
        );
```

---
### Environment
* React Native Navigation version: 6.2.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iPhone 11, iPhone 8

**Comment by rezasazesh** [comment]
This was working well for me up until yesterday, I did a mode module remove and npm install and must have been a minor update of RNN that caused this

I currently have `"react-native-navigation": "^4.8.3"` in my `package.json`

**Comment by alpamys-qanybet** [comment]
@rezasazesh, now it works, thanks to @yogevbd.
