### ISSUE TITLE
Playground app won't install

### ISSUE THREAD

**Issue by harveyconnor** [wix/react-native-navigation#6052]
### Issue Description

Could not install at this time.
Failed to load Info.plist from bundle at path /Users/harveyconnor/Library/Developer/CoreSimulator/Devices/7B8E2EE9-43A6-41AD-8E53-D8A80A623A62/data/Library/Caches/com.apple.mobile.installd.staging/temp.ZT76kD/extracted/playground.app/Frameworks/RCTVibration.framework; Extra info about plist: ACL=<not found> 

### Steps to Reproduce / Code Snippets / Screenshots

I've run npm install, pod install etc. but still won't install.

---
### Environment
* React Native Navigation version: master
* React Native version: master
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 8 simulator / iPhone 6 Device

**Comment by harveyconnor** [comment]
Details

This app could not be installed at this time.
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Could not install at this time.
Recovery Suggestion: Failed to load Info.plist from bundle at path /Users/harveyconnor/Library/Developer/CoreSimulator/Devices/7B8E2EE9-43A6-41AD-8E53-D8A80A623A62/data/Library/Caches/com.apple.mobile.installd.staging/temp.fyENVU/extracted/playground.app/Frameworks/RCTVibration.framework; Extra info about plist: ACL=<not found> 
--
Failed to load Info.plist from bundle at path /Users/harveyconnor/Library/Developer/CoreSimulator/Devices/7B8E2EE9-43A6-41AD-8E53-D8A80A623A62/data/Library/Caches/com.apple.mobile.installd.staging/temp.fyENVU/extracted/playground.app/Frameworks/RCTVibration.framework; Extra info about plist: ACL=<not found> 
Domain: MIInstallerErrorDomain
Code: 35
User Info: {
    FunctionName = "-[MIBundle _validateWithError:]";
    LegacyErrorString = PackageInspectionFailed;
    SourceFileLine = 128;
}
--

**Comment by harveyconnor** [comment]
I get this on the physical iPhone 6
```
Details

Unable to install "playground"
Domain: com.apple.dtdevicekit
Code: -402653103
--
App installation failed
Domain: com.apple.dtdevicekit
Code: -402653103
Failure Reason: Could not inspect the application package.
User Info: {
    DVTRadarComponentKey = 487927;
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000011f3b86e7 DTDKCreateNSError + 109
	1   DTDeviceKitBase                     0x000000011f3b8de9 DTDK_AMDErrorToNSError + 792
	2   DTDeviceKitBase                     0x000000011f3f856a __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 164
	3   DVTFoundation                       0x00000001072abc12 DVTInvokeWithStrongOwnership + 73
	4   DTDeviceKitBase                     0x000000011f3f8301 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1589
	5   IDEiOSSupportCore                   0x000000011f280a25 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.352 + 4523
	6   DVTFoundation                       0x00000001073dce7a __DVT_CALLING_CLIENT_BLOCK__ + 7
	7   DVTFoundation                       0x00000001073de552 __DVTDispatchAsync_block_invoke + 809
	8   libdispatch.dylib                   0x00007fff6f203583 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x00007fff6f20450e _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x00007fff6f209ace _dispatch_lane_serial_drain + 597
	11  libdispatch.dylib                   0x00007fff6f20a452 _dispatch_lane_invoke + 363
	12  libdispatch.dylib                   0x00007fff6f213a9e _dispatch_workloop_worker_thread + 598
	13  libsystem_pthread.dylib             0x00007fff6f45e6fc _pthread_wqthread + 290
	14  libsystem_pthread.dylib             0x00007fff6f45d827 start_wqthread + 15
);
}
--
```

**Comment by jinshin1013** [comment]
From a quick Google search, this might be related to your local setup. Try [this solution](https://stackoverflow.com/a/42067502).

**Comment by harveyconnor** [comment]
@jinshin1013 Already tried that with no success.

**Comment by ethanyuwang** [comment]
have you solved this issue?

**Comment by harveyconnor** [comment]
nope, it appeared to be something with my development environment as it worked just fine on another pc

**Comment by 0x7fs** [comment]
I'm experiencing this too and can't figure out what's causing it. It happened to both my computers a few weeks ago and I got to the point where I had to reinstall macOS before they finally worked again (obviously tried derived data/reinstall xcode, reboot, etc first).

It just started happening again today out of the blue. No configuration changes were made in the meantime. It wasn't happening all day, and then on one rebuild it just started.

**Comment by NSShentu** [comment]
same problem too, and no idea now.
try many times to clear env and rebuild, but not worked

**Comment by NSShentu** [comment]
Try remove **use_frameworks!** in podFile, it seems works for me

**Comment by mtkuyucu** [comment]
> Try remove **use_frameworks!** in podFile, it seems works for me

thanks it worked
