### ISSUE TITLE
[v6] iOS Changing bottomTabs visibility does not affect safeArea

### ISSUE THREAD

**Issue by rverbytskyi** [wix/react-native-navigation#6059]
### Issue Description

After hiding bottom tabs an empty space is left since the safe area of the view does not change.

### Steps to Reproduce / Code Snippets / Screenshots

```js
someFunction() {
  Navigation.mergeProps(
    componentId,
    {
      bottomTabs: {
          visible: false,
          animate: true,
        },
    },
  )
}

render() {
  return (
    <SafeAreaView>
      // Screen layout
    </SafeAreaView>
  )
}
```

With drawBehind false
![Screen-Recording-2020-03-19-at-16 37 31](https://user-images.githubusercontent.com/33003758/77079804-38e0f580-6a01-11ea-9f3d-014275dce5ef.gif)

With drawBehind true
![Screen-Recording-2020-03-19-at-16 40 20](https://user-images.githubusercontent.com/33003758/77079851-48f8d500-6a01-11ea-8c66-64e98bd9162b.gif)

---
### Environment
* React Native Navigation version: 6.3.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 11 - 13.3

**Comment by Blackfaded** [comment]
Having the same issue.

**Comment by stachu2k** [comment]
Same issue. Is there any way to remove safearea inset at the bottom while having bottom tas hidden?
