### ISSUE TITLE
| ERROR | popToRoot: Nothing to pop

### ISSUE THREAD

**Issue by nikolajordanovski** [wix/react-native-navigation#6062]
### Issue Description

Trying to check if pop screen can be called and I am getting my App crash, need to be able to track if I can pop a scree or not so to know it should pop() then push() or just push() but am getting an error witch results into App Crash -> Nothing to pop

export const goBackTo = async (componentId: string, mergeOptions?: any) => {
  await Navigation.popToRoot(componentId, mergeOptions);
  await Navigation.dismissAllModals();
};

---
### Environment
* React Native Navigation version: 3.1.0
* React Native version: 0.60.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Samsung

**Comment by jinshin1013** [comment]
I'm not sure if I understood your problem correctly but you can just add `.catch` to `pop` method to silent the error which will prevent the crash.

**Comment by jayshah123** [comment]
This can probably be avoided if there was a way to query navigation state. Is there a way to query current navigation state?
things like currently shown screen/component-id?
APIs like currently shown modals etc?
