### ISSUE TITLE
Custom style for BottomTab items like width

### ISSUE THREAD

**Issue by MortezaAghili** [wix/react-native-navigation#6072]
### Issue Description

I built a custom bottom navigation tab with this awesome **Wix react-native-navigation**  library like the screenshots. But there is something I looking for, customize or adding custom styles for these items or disable the selected items' styles.

all I want is to make these items equal in width. When we have 5 items, the selected item receives a more horizontal width and this is the issue in my case.

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      bottomTabs: {
        id: 'bottomTabsMain',
        children: [
          {
            component: {
              name: routes[0].name,
              options: {
                bottomTab: {
                  icon: routes[0].icon,
                },
              },
            },
          },
          {
            component: {
              name: routes[1].name,
              options: {
                bottomTab: {
                  icon: routes[1].icon,
                },
              },
            },
          },
          {
            component: {
              name: routes[2].name,
              options: {
                bottomTab: {
                  icon: routes[2].icon,
                },
              },
            },
          },
          {
            component: {
              name: routes[3].name,
              options: {
                bottomTab: {
                  icon: routes[3].icon,
                },
              },
            },
          },
          {
            component: {
              name: routes[4].name,
              options: {
                bottomTab: {
                  icon: routes[4].icon,
                },
              },
            },
          },
        ],
      },
    },
  });
  Navigation.showOverlay({
    component: {
      name: 'navigation.Overlay',
      options: {
        overlay: {
          interceptTouchOutside: false,
        },
      },
    },
  });
});
```
The problematic selected Item:
![2](https://user-images.githubusercontent.com/6826680/77434744-f2273d00-6dfe-11ea-9235-a1f75bd5d2ad.jpeg)

Wanted one:
![1](https://user-images.githubusercontent.com/6826680/77434736-ef2c4c80-6dfe-11ea-9d14-f6624faf1d74.jpeg)

---
### Environment
* React Native Navigation version: "^6.3.1"
* React Native version: "0.61.5"
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by bneigher** [comment]
I've this issue too.  For me the fix was:
```
Navigation.setDefaultOptions({
    bottomTabs: {
        ...
        titleDisplayMode: 'alwaysHide'
    }
})
```

**Comment by bneigher** [comment]
Curious how your centered FAB works for you.  I did something very similar but have this issue:
https://github.com/wix/react-native-navigation/issues/5976

![image](https://user-images.githubusercontent.com/4627728/77462965-157fc700-6dc2-11ea-8257-e4624a1e7fe4.png)
