### ISSUE TITLE
Bottom tab bar icons having issue while swithing tabs.

### ISSUE THREAD

**Issue by swapanil** [wix/react-native-navigation#6073]
### Issue Description

Bottom tab bar icons having issue while swithing tabs.

### Steps to Reproduce / Code Snippets / Screenshots

The screen recording will show you the animation [icons taking padding](https://drive.google.com/open?id=17KPcdq0b1Z_4LK9xLWhHGOqPkwwJEa7H).

#### here is my code:
``` 
 Navigation.setRoot({
    root: {
      bottomTabs: {
        children: [
          {
            stack: {
              children: [{
                component: {
                  id: 'tabOne',
                  name: 'Home'
                }
              }],
              options: {
                bottomTab: {
                  fontSize: 11,
                  text: 'Home',
                  icon: require('../assets/images/homeactive.png'),
                  selectedTextColor: '#e04f5f'
                }
              }
            }
          },
          {
            stack: {
              children: [{
                component: {
                  id: 'tabTwo',
                  name: 'Explore'
                }
              }],
              options: {
                bottomTab: {
                  fontSize: 11,
                  text: 'Explore',
                  icon: require('../assets/images/search.png'),
                  selectedTextColor: '#e04f5f'
                }
              }
            }
          },
          {
            stack: {
              children: [{
                component: {
                  id: 'Favourites',
                  name: 'SignIn'
                }
              }],
              options: {
                bottomTab: {
                  fontSize: 11,
                  text: 'Favourites',
                  icon: require('../assets/images/heart.png'),
                  selectedTextColor: '#e04f5f'
                }
              }
            }
          },
          {
            stack: {
              children: [{
                component: {
                  id: 'tabFour',
                  name: 'Menu'
                }
              }],
              options: {
                bottomTab: {
                  fontSize: 11,
                  text: 'Menu',
                  icon: require('../assets/images/menu.png'),
                  selectedTextColor: '#e04f5f',
                }
              }
            }
          },
        ],
        options: {
          bottomTabs: {
            titleDisplayMode: 'alwaysShow',
            animate: false,
          },
          bottomTab: {
            titleDisplayMode: 'alwaysShow',
            animate: false,
          },
        }
      },
    }
  });
```
---
### Environment
* React Native Navigation version: 0.61.5
* React Native version: ^6.3.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and device,Debug and Release,Android version 8,9

**Comment by ItsNoHax** [comment]
Hi @swapanil ,

This is the default behavior of Android bottomtabs!
If you create a normal Android project with bottomtabs it will be the same!

![android-native](https://user-images.githubusercontent.com/4223434/77542124-fce8dd00-6ea5-11ea-8633-1499d84e9bbc.gif)

**Comment by swapanil** [comment]
> Hi @swapanil ,
> 
> This is the default behavior of Android bottomtabs!
> If you create a normal Android project with bottomtabs it will be the same!
> 
> ![android-native](https://user-images.githubusercontent.com/4223434/77542124-fce8dd00-6ea5-11ea-8633-1499d84e9bbc.gif)

But YouTube App don't have this effect. How they achieve this?

**Comment by swapanil** [comment]
YouTube, Swiggy, Skype and many apps don't have this effect. There is something we are missing.

**Comment by ItsNoHax** [comment]
@swapanil This is the Android bottom tab library used by react-native-navigation.
https://github.com/wix-playground/ahbottomnavigation

It's very possible that the behavior can be toggled on/off.

**Comment by swapanil** [comment]
So can you please tell me how to turn this off.
