### ISSUE TITLE
[v6][iOS13.4][debug] Bottom Tab Icons are not visible

### ISSUE THREAD

**Issue by StasDoskalenkoHover** [wix/react-native-navigation#6075]
### Issue Description

After XCode and iOS version update In debug mode both bottom tab icons and text are not visible.

![image](https://user-images.githubusercontent.com/60673142/77598435-0763a080-6ebf-11ea-8892-de77c76d2f4c.png)

![image](https://user-images.githubusercontent.com/60673142/77598633-97094f00-6ebf-11ea-827f-145f6579a1f1.png)

### Steps to Reproduce / Code Snippets / Screenshots

Reproduced on the Playground app as well.

---
### Environment
* React Native Navigation version: 6.3.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS 13.4
* Device info (Simulator/Device? OS version? Debug/Release?): debug, device and simulator

**Comment by Magnai1030** [comment]
Same

**Comment by exentrich** [comment]
Same

**Comment by AidenMontgomery** [comment]
We were still on RNN 3.3.0 and saw this issue today on iPhone Simulator 13.4.
Upgraded to 6.3.1 and still saw the issue. If I run an iOS 12.4 simulator the icons and text appear OK.

- React Native Navigation version: 3.3.0
- React Native version: 0.61.5
- Platform(s) (iOS, Android, or both?): iOS 13.4

**Comment by narodejesus** [comment]
there is no issues if you build it using xcode v11.3.1 but yeah you might not able to test it in your iOS 13.4 device in debug mode. so I guess for now that will be our option.

**Comment by leolusoli** [comment]
+1

**Comment by dozoisch** [comment]
Got the same issue on XCode 11.4

- Building from 11.4 if I use a iOS13.4 simulator buttons are not there, iOS12.2 simulator no issues. So it's really new Xcode + new simulator version.

**Comment by artehg** [comment]
+1

**Comment by dmitryusikriseapps** [comment]
+1

**Comment by rf1804** [comment]
Got the same issue on XCode 11.4

Building from 11.4 if I use a iOS13.4 simulator buttons are not there, iOS12.2 simulator works well. So it's something with new xCode version or ios 13.4

- RN 0.61.5
 
- RNN ^4.6.0

**Comment by eladgel** [comment]
RN 0.59.9

RNN 6.4.0 still missing

**Comment by eladgel** [comment]
@yogevbd Any suggestion how to get the latest version of the playground that worked with RN <0.60

**Comment by eladgel** [comment]
https://github.com/wix/react-native-navigation/pull/6093
Create a pr to show that rn 59.9 does not work well

**Comment by yogevbd** [comment]
@eladgel It sounds like your Podfile.lock prevents the library upgrade. Try to `rm -rfv Podfile.lock` and then `pod install`.

**Comment by eladgel** [comment]
@yogevbd 
changed podfile to this:
pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'
When trying to pod install I get this

[!] Unable to find a specification for `React-RCTImage` depended upon by `ReactNativeNavigation`

**Comment by devbabs** [comment]
If you're using react native >= 0.61,

### Option 1
Upgrade react-native-navigation to 6.5.0

or

### Option 2
follow the following steps

1. Delete your **node_modules** folder
2. Run **npm install**
3. Run **cd ios && pod install && cd ../**
