### ISSUE TITLE
Side menu animation - Clarification

### ISSUE THREAD

**Issue by MaliahRajan** [wix/react-native-navigation#6083]
Have some ever tried out this kind of side menu animation. Is this possible over react native navigation
![animated_sidemenu](https://user-images.githubusercontent.com/16203679/77843979-cd94e180-71bf-11ea-9994-4fbceb7f272a.gif)
 ??

**Comment by kyle-ssg** [comment]
@MaliahRajan try https://www.npmjs.com/package/react-native-navigation-drawer-extension. It allows exactly this :)
