### ISSUE TITLE
Jitsi-meet library conflicts i think

### ISSUE THREAD

**Issue by batuhansahan** [wix/react-native-navigation#6086]
### Issue Description

I am using [Jitsi-meet](https://github.com/jitsi/jitsi-meet/) it is video conference library
with **no navigation** working correctly
with **react-navigation** working correctly
with **react-native-navigation** there is a problem

**The problem**:

1. I kill the app from background
2. Click app, click button to join conference
3. Apps shows blank black screen but console shows joined the conference and i also confirm phone user joined the conference i can see the phone camera from my chrome tab in the same conference room.

4. i go back(didn't kill app from background) and click button to join conference again and it is showing the conference screen properly.

but again when i kill the app and then fresh start its showing first black screen then 2nd 3rd clicks responding correctly

### Steps to Reproduce / Code Snippets / Screenshots

I tried on 0.60.x 0.61.x 0.62.0 react native version with react-native-navigation v6.x and v2 too 

And the Jitsi-meet component registered screen on my app not, also it is now modal screen, i tried every way i even set the screen as a root screen, it is same.

I even created new project tried on it, not working in any way. same response.

### Jitsi meet installation

I also wanted to mention [how jitsi added](https://github.com/skrafft/react-native-jitsi-meet#install) my project because if there is anything block rnn code or jitsi code that i would know.

In android/app/build.gradle, add/replace the following lines:
```
project.ext.react = [
    entryFile: "index.js",
    bundleAssetName: "app.bundle",
    ...
]
```

**MainApplication.java**
```jsx
package com.XXX;


 // ###### HERE ADDED FOR JITSI-MEET ###### //
import androidx.annotation.Nullable;


import com.facebook.react.PackageList;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.reactnativenavigation.NavigationApplication;
import com.reactnativenavigation.react.NavigationReactNativeHost;

import java.util.List;

public class MainApplication extends NavigationApplication {
    private final ReactNativeHost host = new NavigationReactNativeHost(this) {
      ...
       // ###### HERE ADDED FOR JITSI-MEET ###### //
        @Override
        protected @Nullable String getBundleAssetName() {
          return "app.bundle";
        }
    };

    ...
}
```

and i add **AndroidManifest.xml** <application section
``` 
android:allowBackup="true"
```

Added metro.config.js
```jsx
const blacklist = require('metro-config/src/defaults/blacklist');

module.exports = {
  resolver: {
    blacklistRE: blacklist([
      /ios\/Pods\/JitsiMeetSDK\/Frameworks\/JitsiMeet.framework\/assets\/node_modules\/react-native\/.*/,
    ]),
  },
};
```

---
### Environment
* React Native Navigation version: 6.3.1
* React Native version: 0.61.5 with HERMES ENGINE:ENABLE
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Device / Release

**Comment by damionsteen** [comment]
I'm running into a similar issue also
