### ISSUE TITLE
Is necessary install RN Gesture Handler to use RN Navigation?

### ISSUE THREAD

**Issue by glauberfc** [wix/react-native-navigation#6088]
### Issue Description
I was reading the documentation of RN Gesture Handler in this [link](https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#with-wix-react-native-navigation-https-githubcom-wix-react-native-navigation). Is necessary install RN Gesture Handler to use RN Navigation yet? If not, since for what RN Navigation version is not more necessary?

**Comment by jinshin1013** [comment]
RN Gesture handler was never the dependency required for react-native-navigation. Their documentation just lays out what you need to do if you wanted to integrate RN gesture handler with react-native-navigation.

**Comment by glauberfc** [comment]
Thanks for helping!
