### ISSUE TITLE
Trying to pop the screen, library is using iOS's default animation of sliding from left to right

### ISSUE THREAD

**Issue by KiranAtQuicken** [wix/react-native-navigation#6089]
### Issue Description

I am trying to add custom animations to the Navigation. Here is what I did.

So I have these different animations defined as:

`
    
    const ANIMATIONS = {
      [ANIMATION_TYPE.NONE]: ANIMATION_NONE,
      [ANIMATION_TYPE.SLIDE_HORIZONTAL]: ANIMATION_SLIDE_HORIZONTAL,
      [ANIMATION_TYPE.SLIDE_DOWN]: ANIMATION_SLIDE_DOWN,
      [ANIMATION_TYPE.SLIDE_UP]: ANIMATION_SLIDE_UP
    }

`

each of these is defined with a value. Example:
`
    
    const ANIMATION_SLIDE_UP = {
        push: {
            content: {
                y: {
                    from: 2000,
                    to: 0,
                    duration: 500,
                }
            }
        },
        pop: {
            content: {
                y: {
                    from: 0,
                    to: 2000,
                    duration: 500,
                }
            }
        }
    }`

pushScreen function:
`

    export const pushScreen = (componentId, screen: string, navigatorStyle: ?{} = 
        QKNAVIGATIONSTYLE.light, title: ?string = '', animated: ?boolean = true, passProps: ?{} = {}, bottomToTopAnimation: ?boolean = false, screenId) => {

        let animationType
        if(Platform.OS !== 'ios') { // this is currently needed as there is no proper override for the Navigation animation on iOS that can simulate the bottom to top on push, and top to bottom on pop
            animationType = animated ? (bottomToTopAnimation ? ANIMATION_TYPE.SLIDE_UP : ANIMATION_TYPE.SLIDE_HORIZONTAL) : ANIMATION_TYPE.NONE
        }
        push(componentId, screen, NAVIGATION_STYLE(navigatorStyle, animationType, title), passProps, screenId)

    }`

The push function above is defined as:
`

    export const push = (componentId, screenName, options, passProps, screenId) => {
    previousScreenIds.push(componentId)
    Navigation.push(componentId, {
        component: {
        ...(screenId ? {id: screenId} : {}),
        name: screenName,
        passProps,
        options
        }
    })
    }
`

---
### Environment
* React Native Navigation version: 4.8.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device both, iOS, Debug

Here I want to use the bottom to top (on push, and top to bottom on pop) animation instead of default slide from right to left (on push, and left to right on pop).

What I have seen: push works fine (bottom to top), but pop (top to bottom doesn't happen) doesn't work. While popping we have the same right to left slide animation (iOS default pop behaviour).

**Comment by nicoburns** [comment]
React Native Navigation: 6.1.0
React Native version: 0.61.5
Platform: iOS
Device: Simulator

I have also had this problem. When using a stack view on iOS: configuring the push animation works fine, but the pop animation does a left-to-right slide regardless of what you set the configuration to (unless you set it to none, which does work).

**Comment by KiranAtQuicken** [comment]
@nicoburns you said **unless you set it to none, which does work** what do you mean? Please elaborate.

**Comment by nicoburns** [comment]
> @nicoburns you said **unless you set it to none, which does work** what do you mean? Please elaborate.

It's is possible to disable the pop animation entirely. But it is not possible to change it to something else.

Specifically:
```
animations: {
    pop: {
        enabled: 'false',
    },
},
```
will successfully disable the animation. However:
```javascript
animations: {
      pop: {
        enabled: 'true',
        content: {
          y: { from: 0, to: windowHeight, duration: 100 },
        },
        topBar: {
          y: { from: 0, to: windowHeight, duration: 100 },
        },
        bottomTabs: {
          y: { from: 0, to: windowHeight, duration: 100 },
        },
      },
    },
```
will do the default left-to-right slide. Even though the configuration ought to represent a top-to-bottom slide. I have also tried setting the opacity, and this has no effect.

**Comment by KiranAtQuicken** [comment]
Oh, so on iOS it is not possible to add custom animations for pop, right? Ok got it, thanks for the replies.

**Comment by nicoburns** [comment]
@KiranAtQuicken I believe it's possible. I think it's just a bug in this library which is causing it to not work (although I'm not sure about that). To be clear: I'm not involved in the development of React Native Navigation, I'm just a user who experienced the same issue as you.

**Comment by sanghavan** [comment]
@nicoburns Which version you got pop animation off.
```
animations: {
    pop: {
        enabled: 'false',
    },
}
```
I tried on latest version 7.6.0, Can't disable pop animation.
