### ISSUE TITLE
Blank top bar on ios when using react-native-safe-area-context

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#6092]
### Issue Description

I'm using [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context) to manage ios devices safe areas.

It requires to wrap each page component with `<SafeAreaProvider></SafeAreaProvider>`.

When doing so, all my stack top bar are blank (on iOS only).

Is there anyone using `react-native-safe-area-context` successfully with `react-native-navigation`?

---
### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Debug both device and simulator

**Comment by zabojad** [comment]
Not sure if needed but my top bar is a custom component :

    const defaultTopBarOptions = 
        {
            drawBehind: false,
            backButton: {
                visible: false,
                showTitle: false,
            },
            buttonColor: "black",
            hideOnScroll: false,
            title: {
                component: {
                    name: MyHeaderToolbar,
                    alignment: Center,
                }
            },
        }

    Navigation.setRoot({
        root: {
            sideMenu: {
                left: {
                    component: {
                        id: IDs.DRAWER,
                        name: MySideMenu,
                    }
                },
                center: {
                    stack: {
                        id: IDs.My_STACK,
                        children: [{
                            component: {
                                name: MyHome,
    // temp hotfix for https://github.com/wix/react-native-navigation/issues/5622
                                options: {
                                    topBar: defaultTopBarOptions
                                }
                            },  
                        }],
                    }
                },
            },
        }
    })

**Comment by zabojad** [comment]
@guyca @yogevbd hi guys ! Any idea on this one? It's a bit of a problem as react-native-safe-area-context is a dependency of [react-native-safe-area-view](https://github.com/react-native-community/react-native-safe-area-view) and is thus largely used by the community...

Please tell me what can be done to help you find a fix for that.

**Comment by guyca** [comment]
Hey @zabojad 👋 
How are you wrapping your screens?

**Comment by zabojad** [comment]
Hey @guyca !

There are wrapped with Redux provider, Redux persister, Intl provider and finally this `SafeAreaProvider` (that I've removed).

Here is my wrapping code:

    function register(name) {
        Navigation.registerComponentWithRedux(
            name, 
            () => cmpsMap.get(name),
            AppProviders,
            {store:store, persistor:persistor}
        );
    }

    const FORMATS = { number: { twodigits: { minimumIntegerDigits: 2 } } };

    class AppProviders extends React.Component {
    
        // FIXME wait for a fix for https://github.com/wix/react-native-navigation/issues/6092 
        renderSafeView() {
            let { children } = this.props;
            return children;
            // return (
            // <SafeAreaProvider>
            // 	{ children }
            // </SafeAreaProvider>
            // );
        }
    
        renderIntl() {
            return (
                <ConnectedIntlProvider.Reduxed
                    formats={FORMATS}
                >
                    { this.renderSafeView() }
                </ConnectedIntlProvider.Reduxed>
            );
        }
    
        renderPersist() {
            let { store } = this.props;
            return (
                <PersistGate persistor={store.persistor} loading={null}>
                    {this.renderIntl()}
                </PersistGate>
            );
        }
    
        render() {
            let { store } = this.props;
            return (
                <Provider store={store.store}>
                    {this.renderPersist()}
                </Provider>
            );
        }
    }

Note that all is working nicely until I wrap my comps in this `SafeAreaProvider`.

Also note that I've tried to put this `SafeAreaProvider` deeper in the components tree (even right above its consumer) and the problem is the same. There is something maybe on the native part that leads to this problem...

**Comment by guyca** [comment]
Hmmm it seems like you're using a deprecated api to register your screens. Please try registering your screens with providers as explained in the [docs](https://wix.github.io/react-native-navigation/api/component#registering-a-component-wrapped-with-providers) and let us know if it helps.

**Comment by nenjamin2405** [comment]
Hi @guyca I'm facing another problem using `SafeAreaProvider` from `react-native-safe-area-context`. If I have the SafeAreaProvider outside of the registered screen so the code snippet below will not work and have the white flash flickering.
```js
 Navigation.push(SCREEN.testScreen, {
      component: {
        name: SCREEN.testScreen2,
        options: {
          animations: {
            push: {
              waitForRender: true,
            },
          },
        },
      },
    });
  };
```

My code to register screen:
```js
  Navigation.registerComponent(
    SCREEN.testScreen2,
    () => ProviderWrapper(TestScreen2),
    () => TestScreen2,
  );
```

My ProvderWrapper
```js
import React from 'react';
import {gestureHandlerRootHOC} from 'react-native-gesture-handler';
import {SafeAreaProvider} from 'react-native-safe-area-context';

const ProviderWrapper = (Component: any) => {
  return (props: any) => (
    <SafeAreaProvider>
      <Component {...props} />
    </SafeAreaProvider>
  );
};

export default gestureHandlerRootHOC(ProviderWrapper);

```

If I remove the SafeAreaProvider, then the waitForRender works fine
