### ISSUE TITLE
[v6] [iOS] Stack layout get wrong screens order 

### ISSUE THREAD

**Issue by dzuncoi** [wix/react-native-navigation#6101]
### Issue Description

Stack layout get wrong screens order

### Steps to Reproduce / Code Snippets / Screenshots
Setup screens in `index.js`
```js
import App from './src/App'
import App2 from './src/App2'

const register = (name, Comp) =>
  Navigation.registerComponent(
    name,
    () => (props) => (
      <Provider store={store}>
        <Comp {...props} />
      </Provider>
    ),
    () => Comp
  )

register('Home', App)
register('Profile', App2)

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      stack: {
        children: [
          {
            component: {
              id: 'home',
              name: 'Home',
            },
          },
          {
            component: {
              id: 'profile',
              name: 'Profile',
            },
          },
        ],
      },
    },
  })
})
```

### Expected result
Display `Home` screen at initial, then able to navigate to `Profile` screen

### Actual behavior
Display `Profile` screen first (with back button on top bar), clicking on back button will navigate back to `Home` screen

![Simulator Screen Shot - iPhone 11 - 2020-04-04 at 10 38 59](https://user-images.githubusercontent.com/7270403/78422583-952e5100-7660-11ea-9798-ffe9610d900b.png)
(initial screen)

---
### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.62.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 11 simulator

**Comment by batuhansahan** [comment]
put the initial screen you want at end of the array.

**Comment by dzuncoi** [comment]
@batuhansahan Then again, it will display the `Profile` page first, but with back arrow, which navigate back to `Home` page when clicked. It's still wrong behavior. I wonder if I missed anything from the docs but how can a basic setup like this failed?

**Comment by guyca** [comment]
@dzuncoi This is the correct order. The screen at index 0 will be displayed at the bottom of the stack.
