### ISSUE TITLE
Black screen on IOS when application restarts

### ISSUE THREAD

**Issue by Doaa-Ismael** [wix/react-native-navigation#6106]
when application restarts (for changing language for example) black screen appear for seconds then my screens show up.
V3 was showing white screen not black screen I thought it was white screen because it is the background color in my rootView in IOS AppDelegate.m 

```
self.window.backgroundColor = [UIColor whiteColor];
```
but after I changed it to red it still white (in version 3) , so where can I change it this background color ? 

![Simulator Screen Shot - iPhone 6s - 2020-04-07 at 11 41 47](https://user-images.githubusercontent.com/24235866/78655878-df187080-78c6-11ea-8c5b-eba6984b8356.png)

System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 93.01 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.18.1 - ~/.nvm/versions/node/v10.18.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-25 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
    react-native-navigation:  ^6.4.0
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

**Comment by oxyii** [comment]
Very unusable with code-push (((
@guyca may be `[RNNSplashScreen showOnWindow:UIApplication.sharedApplication.delegate.window];` will be better here?
https://github.com/wix/react-native-navigation/blob/22444b1fc27f0dcf1a59885ec5f5656b241790c6/lib/ios/RNNBridgeManager.m#L118
