### ISSUE TITLE
Options don't change bottomTabs style

### ISSUE THREAD

**Issue by garydevenay** [wix/react-native-navigation#6109]
### Issue Description
Setting options for bottomTabs don't affect tab styling.

### Steps to Reproduce / Code Snippets / Screenshots
![image](https://user-images.githubusercontent.com/722306/78704058-31778280-7903-11ea-9608-fbdbaf4c036f.png)

```js
Navigation.setDefaultOptions({
    bottomTabs: {
        backgroundColor: 'white',
        barStyle: 'black'
    },
    bottomTab: {
        backgroundColor: 'red',
        textColor: 'black',
    },
    topBar: {
        visible: false
    }
});

const root = {
    root: {
        bottomTabs: {
            children: [
                {
                    stack: {
                        children: [],
                        options: {
                            bottomTab: {
                                text: 'Tab 1',
                            }
                        }
                    }
                },
                {
                    component: {
                        name: 'navigation.Navigation',
                        options: {
                            bottomTab: {
                                text: 'Tab 2',
                            }
                        }
                    }
                }
            ],
            options: {
                bottomTabs: {
                    backgroundColor: 'white'
                }
            }
        },
    },
}

Navigation.events().registerAppLaunchedListener(() => {
    Navigation.setRoot(root);
});
```

---
### Environment
* React Native Navigation version: 6.3.1
* React Native version: 0.60.5
* Platform(s) (iOS, Android, or both?):iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator - iOS 13.4

**Comment by garydevenay** [comment]
I upgraded this to v6.4.0 which resolved this issue.

**Comment by flikQ** [comment]
I am on 6.4.0 and doesn't seem to be fixed.

**Comment by garydevenay** [comment]
@flikQ I can try help you out if you post your code. I feel like most of the issues with this library are in the documentation.

**Comment by flikQ** [comment]
`bottomTabs: {
        //backgroundColor: colors.darkerPurple,
        drawBehind: true,
        animate: true,
        hideShadow: true,
        titleDisplayMode: 'alwaysHide',
        translucent: true,
        barStyle: 'black',
      },`

**Comment by flikQ** [comment]
Sorry @garydevenay forgot to mention you - and thanks for any help!

**Comment by garydevenay** [comment]
@flikQ Could you show me the full root that has bottom tabs in it?

**Comment by flikQ** [comment]
@garydevenay you can see it here: https://pastebin.com/2J7FndWB

**Comment by flikQ** [comment]
Obviously I've commented out the offending 2 lines in that paste - so that isn't the reason :)

**Comment by bmwertman** [comment]
I'm also having issues getting `setDefaultOptions` to change the styling of `bottomTabs`. Anything new on this?

**Comment by flikQ** [comment]
No luck, have abandoned setting the bottom tabs as translucent and gone back to solid color

**Comment by bmwertman** [comment]
I can't get anything besides the default styling to apply.

**Comment by chrise86** [comment]
This is still an issue on `7.16.0`, at least for `topBar` when using:
```jsx
Navigation.setDefaultOptions({
  topBar: {
    barStyle: 'black',
    background: {
      translucent: true,
    },
  },
})
```
