### ISSUE TITLE
[v6] Bottom Tab Color reverts to blue when rotating to landscape mode.

### ISSUE THREAD

**Issue by dorthwein** [wix/react-native-navigation#6111]
### Issue Description

When changing orientation, selected tab text color reverts to default blue color.

### Steps to Reproduce / Code Snippets / Screenshots
Reproduce: Set tabs correctly -> rotate to landscape mode -> selected tab color will be blue.

```
  Navigation.setDefaultOptions({
    bottomTabs: {
        titleDisplayMode: "alwaysShow",
        backgroundColor: theme.PRIMARY_COLOR,
        hideShadow: false,
        drawBehind: false
    },
    bottomTab: {
        textColor: defaultColor,
        iconColor: defaultColor,
        selectedTextColor: defaultSelectedColor,
        selectedIconColor: defaultSelectedColor
    }
})
```
---
### Environment
* React Native Navigation version: 6.4.0-snapshot.924
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS (Haven't checked android)
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 8, iOS 13.4 (Debug)

**Comment by dorthwein** [comment]
As an update - I can confirm that text colors do not get set at all on land scape mode - it is not just when rotating.

**Comment by arjndr** [comment]
Any workaround for this yet?

**Comment by IonoclastBrigham** [comment]
I am seeing this manifest differently across platforms:
* iPad (13.3.1) - universally doesn't work; text is always default blue in any orientation 💀
  * Text also seems to change size slightly in circumstances I haven't' figured out yet, which causes the tab labels to ellipsize sometimes 💀
* iPhone 11 sim (13.2.2) - selected text switches to blue in landscape, as originally reported 🙃
* Pixel 3 (10.0) - always works 👍
