### ISSUE TITLE
[v6] Jumping Splash Screen image on Android

### ISSUE THREAD

**Issue by xvonabur** [wix/react-native-navigation#6117]
### Issue Description

Using `setRoot` animation results in moving up splash screen image just before rendering first screen. It happens in 6.4.0 release AND current master.

### Steps to Reproduce / Code Snippets / Screenshots

Add `setRoot` alpha animation:

```js                                                        
const setDefaultOptions = () => Navigation.setDefaultOptions({
  layout: {
    componentBackgroundColor: Colors.background,
    orientation: ['portrait'],
    direction: 'locale'
  },
  bottomTabs: {
    titleDisplayMode: 'alwaysShow'
  },
  bottomTab: {
    selectedIconColor: Colors.primary,
    selectedTextColor: Colors.primary
  },
  animations: {
    setRoot: {
      waitForRender: true,
      alpha: {
        from: 0,
        to: 1,
        duration: 300
      }
    }
  },
  modalPresentationStyle: 'fullScreen'
});

```                                                          
Demo:

![jump](https://user-images.githubusercontent.com/616857/78892746-98677980-7a72-11ea-8199-5261de17da51.gif)

Reproduced in playground app in my fork: https://github.com/xvonabur/react-native-navigation/commit/05b97b0e38cb14e25bf61897c400c25323b4df7d

---
### Environment
* React Native Navigation version: 6.4.0-snapshot.928 and master
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, tested on Android 7-10, in debug and release mode

**Comment by xvonabur** [comment]
Issue is still persist.

**Comment by xvonabur** [comment]
Still an issue.

**Comment by xvonabur** [comment]
Not stale

**Comment by RomualdPercereau** [comment]
This issue is still relevant on **6.10.1** on Android with the example on the documentation. Tested on debug & release build. Look a lot at that issue on iOS with a Side Menu : https://github.com/wix/react-native-navigation/issues/6000 
By the way, the default behaviour shouldn't be waitForRender ?

- React Native Navigation version: 6.10.1
- React Native version: 0.63.2
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Debug and release mode

![demo react-native splash](https://user-images.githubusercontent.com/4194506/88773033-e61f0380-d181-11ea-81a0-9e40bee4f354.gif)


```
const HomeScreen = (props) => {
  return (
    <View style={styles.root}>
      <Text>Home Screen</Text>
    </View>
  )
}
Navigation.registerComponent("HomeView", () => HomeScreen)

Navigation.setDefaultOptions({
  animations: {
    setStackRoot: {
      waitForRender: true,
    },
    setRoot: {
      waitForRender: true,
    },
  },
})

Navigation.events().registerAppLaunchedListener(async () => {
  Navigation.setRoot({
    root: {
      stack: {
        children: [
          {
            component: {
              name: "HomeView",
            },
          },
        ],
      },
    },
  })
})

const styles = StyleSheet.create({
  root: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "pink",
  },
})

```

**Comment by RomualdPercereau** [comment]
This is NOT a fix, but you can replace the white screen by a view with something like : 

**MainActivity.java**
```
    @Override
    protected void addDefaultSplashLayout() {
        LinearLayout view = new LinearLayout(this);
        view.setBackgroundColor(Color.parseColor("#AABBCC"));
        setContentView(view);
    }

```

**Comment by xvonabur** [comment]
@RomualdPercereau I've done that in my production app, but it doesn't fix jumping logo, like you said.

**Comment by RomualdPercereau** [comment]
It doesn't fix the jumping logo, but it replace the white screen with a custom view. Up to you, to add a logo on it to have a view like the startup screen.

**Comment by guyca** [comment]
@RomualdPercereau Have you tried using a "materialish" layout and specifying `android:fitsSystemWindows="true"` ? Something like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:orientation="vertical">

    <ImageView
        android:id="@+id/rnnLogo"
        android:layout_width="wrap_content"
        android:layout_height="200dp"
        android:contentDescription="@string/app_name"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:srcCompat="@drawable/navigator" />
</androidx.constraintlayout.widget.ConstraintLayout>
```

Here I'm using `ConstraintsLayout` as the root layout of the splash screen. When `fitSystemWindows` is set to true, the splash layout will be drawn under the StatusBar and not behind it.

Make sure you have a dependency on `ConstraintsLayout` in your app:
```gradle
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "androidx.constraintlayout:constraintlayout:2.0.1" // <- add this
    ...
}
```

**Comment by t3hfx** [comment]
Still an issue, splash screen jumps a bit up or scales, but @guyca's method worked. But I needed to do some adjustments to the xml file, because I've had a full screen size splash screen. So, if you have this issue and you need to place full screen splash try this:
1. Add ConstraintsLayout to your dependencies as @guyca mentioned in android/app/build.gradle
`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "androidx.constraintlayout:constraintlayout:2.0.1" // <- add this
    ...
}`
Add a folder layouts in the folder res, so you have this path: 
`android/app/src/res/layouts `
Modify your MainActivity.java to: 
```
package your_package_name;

import android.os.Bundle;

import com.reactnativenavigation.NavigationActivity;

import androidx.annotation.Nullable;

public class MainActivity extends NavigationActivity {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setSplashLayout();
    }

    private void setSplashLayout() {
        setContentView(R.layouts.launch_screen); //launch_screen is the name of the xml file that we are going to create in layouts folder
    }
}
```
Create an xml file in layouts folder, in my case launch_screen.xml
`<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:id="@+id/rnnSplashScreen"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:orientation="vertical">
    <ImageView
        android:id="@+id/rnnSplashImage"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:scaleType="centerCrop"
        android:contentDescription="@string/app_name"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:srcCompat="@drawable/splash_screen" />
</androidx.constraintlayout.widget.ConstraintLayout>`

        android:layout_width="wrap_content" stands for wrapping image width to parent view
        android:layout_height="wrap_content" stands for wrapping image height to parent view
        android:scaleType="centerCrop" is like 'cover' for react-native image resizeMode (Scale the image uniformly (maintain the image's aspect ratio) so that both dimensions (width and height) of the image will be equal to or larger than the corresponding dimension of the view)
        
        After that you need to add your image named splash_screen to the folder android/app/src/res/drawable 
        
        Now build and you don't have jumping splash screen anymore

**Comment by guyca** [comment]
Thanks for the detailed solution @t3hfx 🙇

**Comment by devattendant** [comment]
@t3hfx Thanks for the documentation, that has really improved my splashscreen and fixed any issues with it. However I noticed, that the folder had to be named "_layout_" for me (not "_layouts_"), otherwise in launch_screen.xml I got the message `Element androidx.constraintlayout.widget.ConstraintLayout must be declared`
