### ISSUE TITLE
noBorder does not get applied when largeTitle is visible

### ISSUE THREAD

**Issue by haneul512** [wix/react-native-navigation#6118]
### Issue Description

noBorder: true does not get applied when largeTitle is visible

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.mergeOptions(this.props.componentId, {
      topBar: {
        title: {
          color: 'black',
          text: "Settings",
        },
        largeTitle: {
          visible: true,
        }
      }
    });
```
---
### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device

**Comment by cesarm16** [comment]
Same here
