### ISSUE TITLE
[v4] -> [v6] [Android] Still getting UNAUTHORIZED_OVERLAY error while we use react-native-youtube.

### ISSUE THREAD

**Issue by vanthang91** [wix/react-native-navigation#6121]
### Issue Description
Hi, this issue is probably duplicated but my app is totally dependant on your lib, please help me.
I always get UNAUTHORIZED_OVERLAY error when playing the video inline. 
I tried all versions from v4 to v6 but no luck. I also see all changes of commits and PRs below.
Please take a look. Thank you so much!!

Related issues #4256, PR #5999, PR #5903 

---
### Environment
* React Native Navigation version: Have tried 4.0.4, 4.8.0, 6.1.0, 6.4.0
* React Native version: 0.61.5 (Sorry I cant downgrade to 0.59)
* React Native Youtube version: 2.0.0
* Platform(s) (iOS, Android, or both?): Just Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both of simulator and device

**Comment by guyca** [comment]
Hey @vanthang91 , I'm sorry to hear you're still experiencing issues integrating `react-native-youtube`.
In what kind of layout are you showing the native YouTube video player? Please provide as much details about the layout structure as possible. Thanks.

**Comment by vanthang91** [comment]
Hi @guyca, thanks for replying me quickly.
Here is more details about the layout structure:
- Tabbar app
```
export function startTabbarApp() {
   Navigation.setRoot({
        root: {
            bottomTabs: {
                children: [
                    {
                        stack: {
                            children: [{
                                component: {
                                    name: SCREEN.FIRST_TABBAR,
                                    options: {
                                        topBar: {
                                            title: {
                                                text: 'First Tabbar',
                                            },
                                        }
                                    }
                                }
                            }],
                            options: {
                                bottomTab: {
                                    text: 'First Tabbar',
                                    icon: require('../../asset/img/tabbar_1.png'),
                                }
                            }
                        }
                    },  
                    {
                        stack: {
                            children: [{
                                component: {
                                    name: SCREEN.SECOND_TABBAR,
                                    options: {
                                        topBar: {
                                            title: {
                                                text: 'Second Tabbar',
                                            },
                                        }
                                    }
                                },
                            }],
                            options: {
                                topBar: {
                                    backButton: {
                                        title: '',
                                        icon: require('../../asset/img/ic_back_black.png'),
                                        color: 'red',
                                    }
                                },
                                bottomTab: {
                                    text: 'Second Tabbar',
                                    icon: require('../../asset/img/tabbar_2.png'),
                                }
                            }
                        }
                    }
                ]
            }
        }
    })
}
```

- And the component of first tab just render
```
render() {
        return (
            <View style={styles.container}>     // with style flex: 1
                <YouTube
                    ref={(player) => this.player = player}
                    apiKey={getYouTubeAPIKey()}
                    videoId={'ArexdEMWRlA'}
                    play={true}
                    loop={true}
                    showFullscreenButton={false}
                    rel={false}
                    // onReady={e => ()}
                    onChangeState={e => this.setState({ playerState: e.state})}
                    onError={e => this.setState({ error: e.error })}
                    style={{ alignSelf: 'stretch', backgroundColor: 'black', height: YOUTUBE_PLAYER_VIEW_HEIGHT }}
                />
            </View>
        )
    }
}
```

I also test pushing or showing modally another component (crashed when dismiss modal) but 
the video is getting paused immediately after starting. Please see attached video gif file below.

Simulator test device: Nexus 5X API 24 (Android 7.0)


![screencast_200413_gif](https://user-images.githubusercontent.com/2484896/79113591-6d02c880-7dab-11ea-9f0c-010f8c6495a1.gif)

**Comment by guyca** [comment]
Have you tried setting padding to `styles.container`? What's the full error message? It details which view exactly is conflicting.
Try disabling yellow boxes with `console.disableYellowBox = true` just to rule that out.

**Comment by vanthang91** [comment]
I already set ```console.disableYellowBox =  true``` and tried setting ```padding: 10``` to ```styles.container``` too.

Here is detailed error message:
YouTube video playback stopped due to unauthorized overlay on top of player. The YouTubePlayerView is not contained inside its ancestor com.google.android.youtube.player.YouTubePlayerView{4139589 V.E...... ......ID 0,0-0,0}. The distances between the ancestor's edges and that of the YouTubePlayerView is: left: 0, top: 0, right: 0, bottom: 0 (these should all be positive).
2020-04-13 21:29:59.409 9266-9266/****bundleName**** W/unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTEventEmitter.receiveEvent([65,"error",{"target":65,"error":"UNAUTHORIZED_OVERLAY"}])

I pushed demo app on here, you can check out and run on Android.
https://github.com/vanthang91/RN_Youtube_Demo

Note: Please update local.properties file on root/android to help IDE can find Android SDK and run ```npm install``` first.
Thank you!!!

**Comment by vanthang91** [comment]
@guyca If you have any updates, pls tell me. Thanks

**Comment by crushy26** [comment]
+1 same issue. On latest RNN and youtube.

**Comment by guyca** [comment]
Hey guys, I'm closing the issue as it should be resolved by 6.7.5

**Comment by vanthang91** [comment]
Thanks for your support!!

**Comment by hapo-hoangbp** [comment]
@vanthang91 e cũng bị vấn đề như trên mà ko biết cái 6.7.5 giải quyết là cái gì. a có thể giup e đc ko? cảm ơn a :)

**Comment by vanthang91** [comment]
@hapo-hoangbp Hi e, a đã thử từ v4 đến v6 của react-native-navigation thì react-native-youtube đều bị dính trường hợp chạy dc 1s rồi lại dừng. Em có thể vào issue #161 bên react-native-youtube để tham khảo thêm. Nguyên nhân là do có view đè lên <YouTube /> nên youtube nó ko play đc, còn cụ thể view gì thì do project của e setting phần hiển thị thế nào, hoặc có đang dùng 1 loại navigation nào ko. Hiện bản 6.7.5 trở lên a dùng thằng wix/navi này thì ko thấy bị nữa. Tốt nhất là e nên để cái Youtube view của e ở 1 cái single view thôi, còn trường hợp e vẫn bị thì có thể cân nhắc dùng kết hợp với thằng này react-native-youtube-iframe.
Cần thêm trợ giúp thì liên hệ với a qua mail vthang91@gmail.com nhé

**Comment by hapo-hoangbp** [comment]
Hi a. E cảm ơn a đã chia sẻ cách của a cho e. Vấn đề của e gặp phải e đã
tìm được nguyên nhân và giải quyết nó rồi ạ. Dù sao vẫn cảm ơn a nhiều hiii


Vào Th 5, 8 thg 7, 2021 lúc 21:10 Thang Nguyen ***@***.***>
đã viết:
