### ISSUE TITLE
[v6] Support for transparent Modal w/ PageSheet modalPresentationStyle

### ISSUE THREAD

**Issue by dominicstop** [wix/react-native-navigation#6123]
### Issue Description

Hello!! 😊 I have a pageSheet modal w/ a transparent bg (I use it to render a BlurView behind the modal ✨):
```js
options: {
  modalPresentationStyle: 'pageSheet',
  layout: {
    backgroundColor: 'transparent'
  },
}
```

It used to worked on 5.1.1 and previous versions. But on 6.0.0 and newer (i've tried it on 6.4.0), the modal is not transparent anymore. Checking the docs, it says that the new way of showing a transparent modal 👏:
```js
modalPresentationStyle: 'overCurrentContext',
layout: {
  backgroundColor: 'transparent'
}
```

Which is great!! ✨ But is there a way to use the pageSheet style and a transparent bg? I read the changelog for 6.0.0:
>This release changes how layout.backgroundColor work on iOS to add parity with Android.

So i guess, it's somehow related to that? Is there a way to have a transparent bg w/ pageSheet again? Maybe i missed something in the docs (sorry 😭).

Thank you for the help!

### Steps to Reproduce / Code Snippets / Screenshots

Version 5.1.1 / 6.0.0 and later:
![BeFunky-collage-2](https://user-images.githubusercontent.com/18517029/79091667-bb4ea200-7d80-11ea-9b1b-94a52908aecf.png)

---
### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Debug

**Comment by jinshin1013** [comment]
Hey there try:

```tsx
layout: {
    backgroundColor: 'transparent',
    componentBackgroundColor: 'transparent',
 }
```

Since v6, the behaviour slightly changed: [reference](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#600)

**Comment by dominicstop** [comment]
@jinshin1013 Hello!! Sorry for the late reply, thank you so much for the help 🥰✨

(i will try it and close the issue later, thanks again haha)

**Comment by FinnGu** [comment]
> Hey there try:
> 
> ```tsx
> layout: {
>     backgroundColor: 'transparent',
>     componentBackgroundColor: 'transparent',
>  }
> ```
> 
> Since v6, the behaviour slightly changed: [reference](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#600)

Thank you @jinshin1013! Can you explain to me why you would need `backgroundColor` at all? In my application everything worked fine as soon as I replaced `backgroundColor` with `componentBackgroundColor`.

**Comment by ninjz** [comment]
I can confirm, just need to change `backgroundColor` to `componentBackgroundColor`. Would be good to change this in the docs

**Comment by kubilaytural** [comment]
> Hey there try:
> 
> ```tsx
> layout: {
>     backgroundColor: 'transparent',
>     componentBackgroundColor: 'transparent',
>  }
> ```
> 
> Since v6, the behaviour slightly changed: [reference](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#600)

Thx
