### ISSUE TITLE
[Android] Dismiss All Modals on Stack Modals not triggering modalDismissed event.

### ISSUE THREAD

**Issue by jinshin1013** [wix/react-native-navigation#6124]
### Issue Description
When dismissing Stack layout modals using `Navigation.dismissAllModals`, `modalDismissed` event is not being triggered.
However dismissing Single layout modals do trigger the event fine. 

The same behaviour can be observed when using hardware back button on Android. Dismissing stack layout modal does not trigger `modalDismissed` event whereas dismissing single layout modal do.

tl;dr
- `Navigation.dismissAllModals` on Stack Layout Modal does not trigger `modalDismissed` event.
- Android hardware back button to dismiss Stack Layout Modal does not trigger `modalDismissed` event.

### Steps to Reproduce / Code Snippets / Screenshots
1. In the Playground app, add:

```js
// ModalScreen.js
constructor(props) {
  super(props)
  Navigation.events().bindComponent(this)
}

modalDismissed(event) {
  console.log('Event: ', event)
}
```

2. Click `Modal` button in `Navigation tab`.
3. Click `Dismiss All Modals` or `Dismiss modal` button in `Modal` screen.

You will find the event not being triggered. However if you open up a single layout modal from the `Navigation tab` and click `Dismiss All Modals` button, the event will be triggered.

---
### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by jinshin1013** [comment]
The problem seems to be occurring due to the wrong the type of `componentId` emitted when dismissing `Stack Modal` is `stack ID` rather than the `component ID`.

**Comment by jinshin1013** [comment]
Not stale. @guyca Would you be able to have a look at this whenever you can 🙏

**Comment by guyca** [comment]
Hey @jinshin1013 , sorry for the delay. I'll try to get to this asap.

**Comment by guyca** [comment]
@jinshin1013 the `modalDismissed` event isn't meant to be used this way.

This event is emitted once, and it should be emitted with the id of the root component being dismissed - which in your case is the stack.
Unfortunately, on both platforms it's emitted with the id of the visible child in the modal, in your case the top child in the stack.

While fixing this can be considered a breaking change, the current implementation has no practical use case and I think it's safe to fix it.

@yogevbd Think you could get to this for the next release?

**Comment by guyca** [comment]
Oh jeez, Just read your comment https://github.com/wix/react-native-navigation/issues/6124#issuecomment-615837867 . We'll align the implementation asap - the id emitted by `dismissAllModals` is actually the correct id, the id of the root layout (stack).

**Comment by jinshin1013** [comment]
@guyca Thanks for clarifying it further :)

**Comment by guyca** [comment]
Of course, but keep in mind that after we fix this issue, stack children won't recieve the event.
