### ISSUE TITLE
Can you swipeToDismiss fullScreen modal?

### ISSUE THREAD

**Issue by ArnasJack** [wix/react-native-navigation#6125]
I've tested all options with `modalPresentationStyle` and `modalTransitionStyle` to get swipeToDismiss to work, but It only works with `formSheet` and `pageSheet`  `modalPresentationStyle`. 

Was anyone able to achieve this?

**Comment by jinshin1013** [comment]
Hi there, `swipeToDismiss` feature is only available for `sheet` style modals. This is a native constraint. You could create your own component to achieve the desired behaviour. 

For example, you could show an overlay screen and add a gesture event to the overlay screen to handle "swiping down" animation and when it reaches the bottom, dismiss the overlay. Hope this helps :)
