### ISSUE TITLE
[v6] can't set stack of components in setRoot with bottomtabs 

### ISSUE THREAD

**Issue by didrikkvanvik** [wix/react-native-navigation#6130]
### Issue Description

Users in my app can change their preferred language in a settings screen (in `MyProfile` tab).  When the language changes, both the `bottomTabs` and every `topBar` in each tab has to update new titles with the newly selected language. This will, of course, not happen by itself. I therefore attempted to reset the root with a new stack when users change the preferred language, seen as I can't see any other way of being able to update the `bottomTabs` labels and every `topBar` title.

The problem is occurs when setting a new stack layout using `setRoot` with `bottomTabs` present. It works fine when removing `bottomTabs`. Want I want to achieve is to reset the root with a new stack layout.

### Steps to Reproduce / Code Snippets / Screenshots

When changing the language in the app, I run the following code:

```js
Navigation.setRoot({
    root: {
        bottomTabs: getBottomTabs(),
        stack: {
            id: 'Stack',
            children: [
                {
                    component: {
                        id: 'MyProfile',
                        name: 'MyProfile',
                    },
                },
                {
                    component: {
                        id: 'Settings',
                        name: 'Settings',
                    },
                },
            ],
        },
    },
})
```

No matter which component `name` I declare in the stack, every single one is ignored and always resets to `'MyProfile'`. Any tips as for why this is happening?  :) 

BottomTabs has the following options (if it helps):
```js
options: {
    bottomTabs: {
        animate: false,
        backgroundColor: '#fff',
        titleDisplayMode: 'alwaysShow',
        drawBehind: false,
        tabsAttachMode: 'onSwitchToTab',
        currentTabIndex: 4,
    },
}
```

---

### Environment
* React Native Navigation version: v6.0.1
* React Native version: v0.61.4
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator (Debug)

**Comment by guyca** [comment]
@didrikkvanvik You should upgrade to latest version - I have a feeling some of the bugs you're experiencing have already been fixed.

**Comment by didrikkvanvik** [comment]
I'm still experiencing this issue with the latest version. It works if I remove `bottomTabs` from `setRoot`, so I assume the issue has to do using `bottomtabs` while setting a the root.

**Comment by guyca** [comment]
@didrikkvanvik Can you please submit a reproduction?

**Comment by didrikkvanvik** [comment]
I'm using precisely the same structure as specified in the docs. The `stack` has the same structure as `LayoutStack`.
The `getBottomTabs()` function returns the following:
```
children: [{
    id: 'profile',
    stack: {
        children: [
            {
                component: {
                    name: ProfileComponent,
                    options: {
                        bottomTab: {
                            text: 'Profile',
                            selectedIcon: ProfileIconSelected,
                            icon: ProfileIconUnselected,
                        },
                    },
                },
            },
        ],
    },
    ...,
]
```
I can't see a difference between this code and the docs. Bottomtabs works great within the app and we're experiencing no other issues with it, except when trying to reset the root with a stack of multiple components. If I remove `bottomTabs` from `root` it works fine, but then again the `bottomTabs` of course disappears.

**Comment by guyca** [comment]
@didrikkvanvik I just want to make sure I understand what you're trying to do. Are you trying to set the root of the [entire app](https://wix.github.io/react-native-navigation/api/root#setroot)? or reset a [specific stack](https://wix.github.io/react-native-navigation/api/stack#setstackroot)?

**Comment by didrikkvanvik** [comment]
Set the root of the entire app. 

This is related to another issue I'm having. We support multiple languages in our app. When changing a language, the bottomtabs texts does not change. As a result, we have to reset the app root in order to update the bottomtabs text to the correct language. I tried using the `setStackRoot` as well, but then we end up with the push navigation animation when pushing a second component over the first component (seen as we are trying to reset with a stack of 2 components).

**Comment by guyca** [comment]
@didrikkvanvik The root layout you're using seems wrong. you're using both stack and bottom tabs!

```ts
Navigation.setRoot({
    root: {
        bottomTabs: getBottomTabs(),
        stack: { // This is probably a mistake! This stack should be the last child of the bottomTabs layout
            id: 'Stack',
            children: [
                {
                    component: {
                        id: 'MyProfile',
                        name: 'MyProfile',
                    },
                },
                {
                    component: {
                        id: 'Settings',
                        name: 'Settings',
                    },
                },
            ],
        },
    },
})
```

**Comment by didrikkvanvik** [comment]
@guyca Ah that explains it. It works fine resetting with a stack now. Thanks!
