### ISSUE TITLE
Question: Need some more info about the global events and local component events.

### ISSUE THREAD

**Issue by MakhouT** [wix/react-native-navigation#6131]
### Issue Description
Currently, we are having issues with our app. We are only using functional components and are not using any class-based components. I think the issue we are having is because we are not really understanding the global events versus local component events. Are they interchangeable? 

Like explained in the docs:

```js
class MyComponent extends Component {
  componentDidMount() {
    this.navigationEventListener = Navigation.events().bindComponent(this);
  }

  componentWillUnmount() {
    // Not mandatory
    if (this.navigationEventListener) {
      this.navigationEventListener.remove();
    }
  }
}
```

Does this mean this can only be used in the component and not globally? If so how can I get this working in a functional component?

And what will the behavior be when combining it with the global listener
```js
// Subscribe
const screenEventListener = Navigation.events().registerComponentDidAppearListener(({ componentId, componentName, passProps }) => {

});
...
// Unsubscribe
screenEventListener.remove();
```

The issue we are having currently in our app is that after open/closing a few times we then get a warning that more listeners are being removed than having added. And after a while, it just crashes. 

The docs are not giving a lot of information on this, we also had a look in the typing of the events to try to figure out what we are doing wrong. But I think we are just not understanding how it should work and behave.

Can someone elaborate on this, please.
Thanks!

### Environment
* React Native Navigation version: **4.6.0**
* React Native version: **0.61.4**
* Platform(s) (iOS, Android, or both?): **Both**
* Device info (Simulator/Device? OS version? Debug/Release?): **Both**

**Comment by jinshin1013** [comment]
Hi there, I am sure if I fully understand what you mean by global event listeners. Would you be able to create a minimal reproduction for me to have a look?

**Comment by MakhouT** [comment]
Hi @jinshin1013 

Well that's how it stated in the docs of RNN, 
https://wix.github.io/react-native-navigation/api/events#componentdidappear

As I read it there, there are global and local listeners?

**Comment by guyca** [comment]
@MakhouT Try registering component listeners [instead](https://wix.github.io/react-native-navigation/docs/functionalComponents#listening-to-navigation-events), perhaps it will help.

**Comment by MakhouT** [comment]
@guyca Link is not working, also can't find 'functional components' in the docs

**Comment by guyca** [comment]
@MakhouT clear browser cache `cmd+shift+r`
