### ISSUE TITLE
Question:  [iOS] react-native-bootsplash integration and [android] debug button bindings

### ISSUE THREAD

**Issue by FrederickEngelhardt** [wix/react-native-navigation#6134]
### Question: [iOS] How would I go about adding bootsplash support

On the [bootsplash](https://github.com/zoontek/react-native-bootsplash) side of things they do not support react-native-navigation. I thought I'd ask how it could be integrated in the AppDelegate.m file.

Code example
```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import "RNBootSplash.h" // <- add the header import

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // …
  rootViewController.view = rootView;
  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // <- initialization using the storyboard file name

  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  return YES;
}
```

### Question 2: How would I go about adding a onKeyUp listener that accesses getReactInstanceManager()?

This would normally be added in the MainActivity.java and it's nice to have to avoid shaking my phone to death.
```java
    // Custom Debug Script
    @Override
    public boolean onKeyUp(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_VOLUME_DOWN && this.getReactInstanceManager() != null) {
            this.getReactInstanceManager().showDevOptionsDialog();
            return true;
        }
        return super.onKeyUp(keyCode, event);
    }
```

**Comment by jinshin1013** [comment]
Hi 🙌
I think these questions are more of a general StackOverflow question than a bug report. 

I'm not familiar with BootSplash to answer the first question.

For the second question, not an android developer but I think you should be able to use `MainActivity` as you would for normal Java project so I'm sure you could just add those in. Also with the newer React Native now the Metro bundler supports pressing `r` for reloading and `d` for opening up developer menu.
