### ISSUE TITLE
[V6] [Android] bottomTabs drawn under Android virtual buttons

### ISSUE THREAD

**Issue by vovka-s** [wix/react-native-navigation#6135]
After migration from 4.5.1 to 6.4.0 I got a bug:
- bottom tabs are located under Android virtual buttons
- they are touchable
- in the correct place for tabs I see white rectangle
- the correct upper board of tabs shown by a green line
- the actual upper board of tabs shown by a blue line
- the actual position of first tab shown in orange circle

![IMG_20200417_132524](https://user-images.githubusercontent.com/9987233/79561900-c96b2e00-80b2-11ea-9a1e-ed3fe1d4a1f6.jpg)

defaultOptions
```
Navigation.setDefaultOptions({
    topBar: {
        elevation: 0,
        animate: true,
        hideShadow: true,
        borderColor: '#bbb',
        borderHeight: 0.5,
        background: {
            color: '#f7f7f7',
        },
    },
    bottomTabs: {
        animate: false,
        hideShadow: true,
        backgroundColor: '#f7f7f7',
        titleDisplayMode: 'alwaysHide',
    },
    bottomTab: {
        iconColor: '#a7a7a7',
        selectedIconColor: '#00b7f0',
    },
});
```
screenOptions
```
static options() {
    return {
        topBar: {
            title: {
                component: {
                    id: COMPONENTS.NavBarImageTitle.getNextId(),
                    name: COMPONENTS.NavBarImageTitle.componentName,
                    alignment: 'center',
                    passProps: {
                        image: assets.images.logo,
                    },
                },
            },
            leftButtons: [
                {
                    id: NAVIGATION_ACTION_NAMES._FILTERS_SCREEN,
                    icon: assets.navIcons.filter,
                    disableIconTint: true,
                },
            ],
            rightButtons: [],
        },
        bottomTab: {
            disableIconTint: true,
            icon: assets.navIcons.lenta,
        },
    };
}
```
On 4.5.1 it worked fine. I missed anytyhing?

### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.61.2 and 0.62.2
* Platform(s) (iOS, Android, or both?): Android (iOS not tested)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator - Google Pixel 3, Device - Mi9 SE, android - 9,10, Debug and release builds

**Comment by guyca** [comment]
Hey @vovka-s 
This is very strange. Does this bug reproduce on all devices? Or only Mi9 SE?

**Comment by vovka-s** [comment]
> Hey @vovka-s
> This is very strange. Does this bug reproduce on all devices? Or only Mi9 SE?

I tried on Mi9 SE, Samsung Galaxy S10, Huawei P8 Lite. It reproduced.
On emulator too...

**Comment by valnermedeiros** [comment]
@vovka-s i am having the same problem in my app

**Comment by MarkusAbtion** [comment]
I'm seeing this as well on Samsung S23
