### ISSUE TITLE
Persistent Component not belonging to Stack

### ISSUE THREAD

**Issue by TylerZubke** [wix/react-native-navigation#6157]
### Issue Description

This is just a general question. Let's say I have a basic structure like this:
```
Navigation.setRoot({
  root: {
    bottomTabs: {
      children: [
        {
          stack: {
            children: [
              {
                component: {
                  name: 'FEED_SCREEN'
                }
              }
            ]
          }
        },
        {
          stack: {
            children: [
              {
                component: {
                  name: 'CHAT_LIST'
                }
              }
            ]
          }
        },
        {
          stack: {
            children: [
              {
                component: {
                  name: 'PROFILE_SCREEN'
                }
              }
            ]
          }
        }
      ]
    }
  }
});
```
Is there a way to have a persistent component that sits outside of these stacks and is unaffected by the user switching tabs? For instance, a toolbar that sits below the navigation bar, but above the actual components in the stack. I know I could make the toolbar part of the stack and store it's state and then rebuild it when moving to a new stack, but I was hoping there was a way to move it outside the scope of RNN.

### Steps to Reproduce / Code Snippets / Screenshots

N/A

---
### Environment
N/A

**Comment by guyca** [comment]
You can achieve this using an [Overlay](https://wix.github.io/react-native-navigation/docs/overlay).
