### ISSUE TITLE
How to get a left button event in Android?

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#616]
Hey there @guyca,

I've been manually keeping track of wether the side menu is open or not in iOS by adding a custom left button as an object in my `leftButtons`, toggling the drawer and keeping a `boolean` in my redux state to know if it's open or not. 

But when I tried to make the same thing in Android, I found that I **cannot overwrite** the `leftButton` with a custom one, and thus I don't know when it's clicked, and thus I'm not able to tell if the side menu is open or not..

How come don't you dispatch an event when a button is clicked?

Any ideas about this?

Thank you..!

**Comment by guyca** [comment]
Thanks for the PR, I wrote one comment, think there's one small mistake but other then that looks good 👍

**Comment by SudoPlz** [comment]
Hmm, can't really find that comment, any idea where it is?

**Comment by guyca** [comment]
merged. Thanks @SudoPlz

**Comment by SudoPlz** [comment]
Thank you!!
