### ISSUE TITLE
Header from previous screen is rendering after navigate()

### ISSUE THREAD

**Issue by yazmnh87** [wix/react-native-navigation#6160]
### Issue Description

On my landing screen I have several components which when clicked on navigate to different stacks.  Unfortunately after navigating from my "root" stack to another stack, the Header from the Landing screen in still rendering on the screen that Im navigating to.  

### Steps to Reproduce / Code Snippets / Screenshots

<img width="385" alt="herbapp_home_screen_issue" src="https://user-images.githubusercontent.com/25097299/80270096-842a9b80-8672-11ea-8920-55d2d1a07ce0.png">
<img width="382" alt="herbapp_herb_screen" src="https://user-images.githubusercontent.com/25097299/80270097-87258c00-8672-11ea-9e7e-7f3c16d975a1.png">

---
### Environment
* React Native Navigation version: "@react-navigation/native": "^5.0.9"
* React Native version: expo - "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz"
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): simulator iPhone 11  ios 13.2.2

**Comment by yazmnh87** [comment]
thanks for the help guyca

**Comment by landonwjohnson** [comment]
I am having the same problem. You would think that the people that made react navigation would know what they are doing. Apparently not. @guyca

**Comment by jinshin1013** [comment]
Hey guys, please try not to add any offensive comments. You are reporting a react-navigation issue in the react-native-navigation.

**Comment by yazmnh87** [comment]
> Hi @yazmnh87 and @landonwjohnson, please try not to add any offensive or sarcastic comments. You are reporting a [react-navigation](https://github.com/react-navigation/react-navigation) issue in the react-native-navigation.
@jinshin1013 
firstly I dont know why you tagged me, secondly its offensive when you auto close legitimate issues without any response.

**Comment by jinshin1013** [comment]
I know the names might have caused a confusion but react-navigation and react-native-navigation are different projects. You are posting react-navigation issue (suggested by your environment description) in react-native-navigation repo hence closed the issue.

**Comment by yazmnh87** [comment]
@jinshin1013 ^interesting, I didnt see that difference between the repos, thanks.
