### ISSUE TITLE
Question: react-native 0.66 + react-native-navigation v1 compatability?

### ISSUE THREAD

**Issue by oferRounds** [wix/react-native-navigation#6161]
### Issue Description

Should there a problem with the the combination above? I know it’s strange, but so far RNN v1 worked perfect for us, and currently, if it’s not a must, we would like to keep RNN v1

The problem we see is that FlatList won’t scroll to the bottom of the list, in all screens. We also see the scroll-indicator flickers while scrolling.

Could this problems be related somehow to RNN?

### Steps to Reproduce / Code Snippets / Screenshots
Not sure, happens on our project consistently

---
### Environment
* React Native Navigation version: v1
* React Native version: 0.60.6
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device

**Comment by guyca** [comment]
Good question! Since I'm the last team member who has worked on v1, and I haven't compiled v1 in the last 3 years, I don't think you'll find an answer here 😅 

@oferRounds why don't you migrate to v6? Once this Corona mess is over you're welcome to our office and we'll migrate together 😁

**Comment by oferRounds** [comment]
@guyca funny! sounds good! We have a date then!
Thank you 🤗🤗
