### ISSUE TITLE
RNN1 is not work on release mode with iOS SDK 13

### ISSUE THREAD

**Issue by zhaiduo** [wix/react-native-navigation#6162]
### Issue Description

RNN1 is not work on release mode with iOS SDK 13, when I use 12 SDK, APP has no problem.
This APP developed two years ago, I hesitate to update to version 2. 

Is there another way to resolve this problem? Apple has told us iOS 12 SDK will not work after June 30, 2020.
It seems I have to make a big upgrade.

### Steps to Reproduce / Code Snippets / Screenshots

Null || None

---
### Environment
* React Native Navigation version: 1.1.469
* React Native version: 0.53.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device both Release mode MacOS Mojave 10.14.6

**Comment by guyca** [comment]
Hey there, v1 isn't supported anymore. I suggest you update to v6 👍
