### ISSUE TITLE
No option to add animations to showing/hiding overlays

### ISSUE THREAD

**Issue by Puupuls** [wix/react-native-navigation#6165]
### Issue Description

There is no option to add animations to showing/hiding overlays
![image](https://user-images.githubusercontent.com/22271605/80309881-53687480-87e0-11ea-82d5-b73c70d48cb9.png)

---
### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): any

**Comment by guyca** [comment]
@Puupuls Since Overlays are typically displayed with transparent backgrounds and only a specific view needs to be animated, we're leaving it to the user to animate the Overlay.
