### ISSUE TITLE
[V6] fullscreen Modal Presentation style isn't working anymore 

### ISSUE THREAD

**Issue by MakhouT** [wix/react-native-navigation#6172]
### Issue Description
I can't get my modal back to be fullScreen after upgrading from `4.6` to `6.4`
in the `defaultOptions` I tried all the options on the `modalPresentationStyle` mentioned in the docs like 

```js
enum('formSheet', 'pageSheet', 'fullScreen', 
'overFullScreen', 'overCurrentContext', 'popOver', 'none')
```
But it always stays the default one
Is this regression?

---
### Environment
* React Native Navigation version: 0.62
* React Native version: 6.4
* Platform(s) (iOS, Android, or both?): Only tested on iOS (13.x) - testing on an iPad

**Comment by sm2017** [comment]
I have same issue , Any solution?

**Comment by sm2017** [comment]
@guyca @yogevbd Please take a look

**Comment by guyca** [comment]
Hey @sm2017 @MakhouT `modalPresentationStyle: 'fullScreen'` seems to work as expected in the playground app. Can you please reproduce any use case which doesn't work properly?

**Comment by MakhouT** [comment]
It is not working when setting it on the defaultOptions. When passing the `modalPresentationStyle` through the options of the `modal` itself it is working.

**Comment by MakhouT** [comment]
Can't seem to reproduce it in the playground app... However it is fixed by having it set on the modal instead of defaultOptions. Can be closed for me.
