### ISSUE TITLE
[v6] Nesting Stack -> BottomTabs -> Stack creates empty space above topBar

### ISSUE THREAD

**Issue by NBoychev** [wix/react-native-navigation#6174]
### Issue Description

Nesting Stack -> BottomTabs -> Stack creates empty space above topBar on **iOS**

### Steps to Reproduce / Code Snippets / Screenshots

Reproduced in the playground app:
https://github.com/NBoychev/react-native-navigation/blob/master/playground/src/app.js

Screenshot:
![Simulator Screen Shot - iPhone 11 Pro - 2020-04-28 at 15 23 15](https://user-images.githubusercontent.com/1816446/80486928-9bb09f80-8964-11ea-8e01-f3c1e1ba3369.png)

---
### Environment
* React Native Navigation version: **6.5.0**
* React Native version: **0.62.2**
* Platform(s): **iOS**
* Device info: Simulator iPhone 11 Pro and real device iPhone X 13.3.1

**Comment by ShabanovPavel** [comment]
Same. Only on ios. The problem in my opinion in SafeArea is two stacks. Checked for android everything is fine 

[#6132 ](https://github.com/wix/react-native-navigation/issues/6132)

**Comment by NBoychev** [comment]
I've just checked and can confirm that there's no issue on Android. What I've found is that on iPhone 8, where we don't have a notch, so SafeArea shouldn't apply, the issue is still presented.
![Screenshot 2020-04-29 at 13 37 17](https://user-images.githubusercontent.com/1816446/80587227-d70fa480-8a1e-11ea-808b-644628e4280f.png)

**Comment by lkwjohn** [comment]
I have similar issue but it's on Android and the issue is bottom having too much empty space.

Page Navigation to reach this page: Main Screen  =>  Open new Screen 
![2020-07-15 10 32 50](https://user-images.githubusercontent.com/273127/87496638-9707a780-c686-11ea-8df0-8e9319beeccb.jpg)

**Comment by ashokkumar88** [comment]
@lkwjohn did you find any workaround? I am facing the same issue.

**Comment by lkwjohn** [comment]
@ashokkumar88 sadly no, seems to me it's a bug introduced after 2.62.1. This only happen on Android.

**Comment by jinshin1013** [comment]
@NBoychev If you refer to the [playground app](https://github.com/wix/react-native-navigation/blob/master/playground/src/app.ts), you can see that `bottomTabs.children` does not contain any `stack` layout. If you remove `stack` under `bottomTabs.children`, it will fix the issue for you 👍

**Comment by NBoychev** [comment]
@jinshin1013 , unfortunately, this doesn't resolve the issue. In my case, I want a structure of stack -> bottom tabs -> stack. It's a specific case, but I'm sure that others will also bump in the same. In the example, a stack is actually nested in the bottomTabs: https://github.com/wix/react-native-navigation/blob/master/playground/src/app.ts#L39

@guyca helped me to resolve the issue with the idea to use custom tabs, but I hope that I'll see this one fixed at some point, so I can transition to the native solution.

**Comment by jinshin1013** [comment]
@NBoychev My bad I said the wrong thing 😅  Meant to say, do not wrap `BottomTabs` with a `Stack` hahaha. 
If you don't mind me asking, what's your use case of going `Stack -> BottomTabs` ??

**Comment by NBoychev** [comment]
@jinshin1013 , it's actually more complicated -> SideMenu -> Stack (like a home screen with items) -> Bottom tabs (each item has modules) -> Stack (each module has lists and list item detailed screens).

**Comment by nextriot** [comment]
Has anyone ever found a way to make this work? I'm attempting the same layout (with sidemenu and center nested inside a stack navigator) - my use case is simply that I want the whole view including the tabs to be pushed off the screen when I navigate to another view.

I've asked the question on SO (https://stackoverflow.com/questions/74188621/wix-rnn-anybody-know-how-to-nest-bottomtabs-inside-of-a-stack-navigator-withou)

If anybody knows the answer please let me know 🙏
