### ISSUE TITLE
[V6] navigationBar visible option not working on Android

### ISSUE THREAD

**Issue by arjndr** [wix/react-native-navigation#6175]
### Issue Description

navigationBar is not being hidden with the visible property, backgroundColor is working tho

### Steps to Reproduce / Code Snippets / Screenshots

```js
HomeScreen.options = {
  navigationBar: {
    visible: false
  }
}
```

---
### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.62.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Android 9, Debug

**Comment by guyca** [comment]
It was added in 6.5.0

**Comment by arjndr** [comment]
Oh okay, my bad. Thanks a lot!
