### ISSUE TITLE
I want Header to be overlayed while any modal is open...

### ISSUE THREAD

**Issue by hari3110** [wix/react-native-navigation#6177]
![Simulator Screen Shot - iPhone 8 - 2020-04-29 at 19 21 17](https://user-images.githubusercontent.com/58428834/80604138-f7575780-8a4e-11ea-92b3-035883cccca0.png)

As you can see that transparent background it must be over header as well.
Any help would be appreciated.

**Comment by phuongwd** [comment]
It seems the “modal” is component inside “Abdul...” screen. You did not use api `showModal`, right?

**Comment by hari3110** [comment]
Yes exactly @phuongwd

**Comment by phuongwd** [comment]
I have solutions below, you can try 👻
1. Use api `showModal`
- disable animation when show/hide
- search “modal background transparent” on this issues tab to find solutions. It has issued when rotation - I assume you are using RNN v3
- listen component life cycle events to handle show/hide custom “modal”
2. Use api `showOverlay`
- listen component life cycle events to handle show/hide custom “modal”

**Comment by hari3110** [comment]
Ohh I'll give it a try for sure 😉
