### ISSUE TITLE
[docs] Links to API Pages from Docs Pages Broken

### ISSUE THREAD

**Issue by 0xcaff** [wix/react-native-navigation#6179]
### Issue Description

Links from /docs pages to /api pages are broken. Here's an example.

https://github.com/wix/react-native-navigation/blob/fe675b3ea1498e5a9be349e79f7ca7703ca97113/website/docs/docs-screen-lifecycle.mdx#L33

This link goes to:
https://wix.github.io/react-native-navigation/docs/screen-lifecycle/options-root.mdx#modalpresentationstyle

It should go to:
https://wix.github.io/react-native-navigation/api/options-root/#modalpresentationstyle

Not sure how docusaurus's link resolution works exactly otherwise I'd fix it myself. Awesome library! ❤️

**Comment by guyca** [comment]
Thanks for reporting @0xcaff ! 🙇 
Yeah it wasn't that straight forward for us as well, took a while to figure out 😅 Fixed now, probably have a few more places to fix.
