### ISSUE TITLE
How to disable the title for a screen?

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#618]
I tried passing an empty string like so:
`title: '',`
but sometimes it works, other times it doesn't...

I wan't to make SURE there's no title to my screen when it opens..

Thank you!!

**Comment by guyca** [comment]
@SudoPlz IIRC The title property is optional. Don't pass it when you push or show modal.

**Comment by SudoPlz** [comment]
Well if I don't pass it at all I get a title that is the id of the screen in camel case (I think).

**Comment by guyca** [comment]
@SudoPlz On which platform?

On Android, this code pushes a screen with out a title:
```js
  onPushPress() {
    this.props.navigator.push({
      screen: "example.PushedScreen"
    });
  }
```

**Comment by SudoPlz** [comment]
Well the app is built for both iOS and Android. I know right now I see this issue on Android, but I remember occasionally seeing a title on iOS as well, when I shouldn't. I wonder if that is connected to https://github.com/wix/react-native-navigation/issues/614
