### ISSUE TITLE
Feature request , Support Android API 19

### ISSUE THREAD

**Issue by sm2017** [wix/react-native-navigation#6183]
Android bottomTabs rendering blank on Android API 19

We have some duplicate issue , I know 
https://github.com/wix/react-native-navigation/issues/5736

**Comment by guyca** [comment]
Hey @sm2017, we don't plan on supporting API 19 but we'll accept a PR to fix this.

**Comment by danilobuerger** [comment]
Lets close this as API 19 is not supported and it doesn't look like anybody is going to tackle it.
