### ISSUE TITLE
Can't change badgeColor for bottomTab on iOS (v6.5.0)

### ISSUE THREAD

**Issue by Tatsiana0607** [wix/react-native-navigation#6191]
### Issue Description

In RNN 6.5.0 badge color is not changing on iOS. Works fine on Android.

I've tried different ways to set badge color:
1) with `mergeOptions`:
```
Navigation.mergeOptions('Tab.Inbox', {
    bottomTab: {
        badge: newMessagesCount ? String(newMessagesCount) : '',
        badgeColor: colors.pink
    }
});
```
2) with `setDefaultOptions`:
```
Navigation.setDefaultOptions({
    bottomTab: {
	 badgeColor: colors.pink,
    }
});
```
3) setting color directly in the `bottomTabs` children:
```
{
    stack: {
	id: 'Tab.Inbox',
	children: [{
	    component: {
		id: 'Inbox.Main',
		name: Screens.Inbox,
	    }
	}],
	options: {
	    bottomTab: {
		icon: IMG_INBOX,
		text: 'Inbox',
		iconColor: colors.grayBlue,
		textColor: colors.grayBlue,
		selectedIconColor: colors.orange,
		selectedTextColor: colors.orange,
		fontFamily: FONT_OPENSANS_BOLD,
		badgeColor: colors.pink,
	    }
	}
    }
},
```

But none of these ways worked and badge is always displayed with default orange color:
![iPhone 11 — 13 2 2 2020-05-04 18-34-50](https://user-images.githubusercontent.com/32789351/80984090-1599ca80-8e36-11ea-9303-c7bbd92ed03f.png)
Compare to Android:
![httpsmonosnap comdirectfbAfLRdFgalk5B5njoqdmdOLa9WIFg 2020-05-04 18-58-15](https://user-images.githubusercontent.com/32789351/80986486-4b8c7e00-8e39-11ea-8587-376b12c07e7c.png)

Note: If RNN is downgraded to `6.0.0` everything works fine on both platforms.

---
### Environment
* React Native Navigation version: 6.5.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS Simulator 13.2.2 Debug and Release

**Comment by keenubee** [comment]
We have the same issue (
Can somebody take a look on this please?
@guyca

**Comment by keenubee** [comment]
@yogevbd Do you have any ETA for this issue?

**Comment by yogevbd** [comment]
Fixed in #6246

**Comment by yond** [comment]
Please reopen this issue. After upgrading to latest (6.7.5), badgeColor cannot be changed. Prior to upgrade it worked fine. Please help.

**Comment by Tatsiana0607** [comment]
@yond The fix in #6246 is working fine, but as I see it wasn't yet released for some reason.
It was mentioned in bug fixes list for v6.7.5 (https://github.com/wix/react-native-navigation/releases/tag/6.7.5) but I can't see these changes in the latest version (https://github.com/wix/react-native-navigation/compare/6.5.0...6.7.5)

@yogevbd @guyca Could somebody please take a look at this?

**Comment by rodribech20** [comment]
Hello, Im checking on latest version and Im not able to change the badgeColor. 
Im using:
RN 0.64.2
Xcode 12.5 - iOS 14.5
Thanks

**Comment by mattmcdonald-uk** [comment]
Setting `badgeColor` through `setDefaultOptions` worked for me.

```
Navigation.setDefaultOptions({
    bottomTab: {
        badgeColor: 'blue',
    },
})
```
