### ISSUE TITLE
Issue when navigating screens back and forth

### ISSUE THREAD

**Issue by atrofimenko** [wix/react-native-navigation#6198]
### Issue Description

Navigating back and forth to every page causes the app to hang and just show empty screen without having an error. I tried to figure out the problem and understand that onLayout of any view in component not called after first push of component(previous umount was called for it), logs on android did not give clarifications.

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.62.1
* Platform(s) (iOS, Android, or both?): Android(only on versions < 9)
* Device info (Simulator/Device? OS version? Debug/Release?): simulator, sdk version 26

**Comment by guyca** [comment]
@atrofimenko Any chance you're changing StatusBar options when pushing/popping the screens?

**Comment by atrofimenko** [comment]
@guyca On these steps i'm only using push and popTo without any additional options

**Comment by guyca** [comment]
Please fork the library, reproduce in the playground app and post a link with your reproduction so we can take a look. Thanks 👍
