### ISSUE TITLE
push screen right after Navigation.startSingleScreenApp

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#62]
I'd like to restore my app's state from persisted redux store. My current approach would be to do it right after Navigation.startSingleScreenApp e.g.:
```js
        Navigation.startSingleScreenApp({
          screen: {
            screen: 'myApp.IndexScreen', 
            title: 'Items',
            navigatorStyle: {} 
          }

        // Load app state 
        const { app } = store.getState()
        store.dispatch(fetchItem(app.currentItem))
        Navigation.push('myApp.'+app.currentScreen)
````
But of course that doesn't work... is there a way to do this, am I on the right track, or is it not possible this way?

I have two motivations for this:

1. For testing - so I land on the right screen each time I restart the app, e.g. for incremental design tweaks (when hot reloading is not available)
2. To save user state so they land at the same place after closing the app

**Comment by guyca** [comment]
The way I would do it, is load the app regularly. and dispatch an action before you main screen mounted:
```
componentWillMount() {
  this.props.dispatch(feedActions.IndexScreenMounted());
}
```
in `IndexScreenMounted` you can fetch your stored data (We're using `redux-thunk` to run async actions) then post a secondary action to update the state with the data you've loaded.


Does this answer your question?

**Comment by adamski** [comment]
Thanks I'll give that a go. I'm also using `redux-thunk`.
