### ISSUE TITLE
[Feature] Push stack as replace

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#6208]
Dear all,
Could we have the feature with push as replace like this:
A -> B ->C. When we at C, we want to push "D" but not stack on C, just replace C, then the result is A -> B -> D, then, at top stack here (D), we push as replace again "E" to become A -> B -> E, and so on
It means, when we call 'push', we have slide transition like "push" action but only replace the current top.
From "E" when we call "pop" or slide back, it will return to "B" and we have stack A -> B
This is useful when we make the chat application, at conversation A, when top notification have new messages from conversation B, we can touch and push to conversation B, transition and replace conversation A. Then, just back or slide back, it will bring us to Conversation List again. No need to back alot

**Comment by guyca** [comment]
Hey @moonjava2005 
This has been discussed several times in the past, we've agreed not to include such feature for two reasons:
1. iOS's NavigationController does not support it
2. The Stack data structure does not support it

When ever this feature seems to be needed, the actual solution should probably using a modal.
```
A -> push B
            showModal C -> setStackRoot D
```

Now, your layout looks like this:
```
A -> push B
            showModal C
```

Calling `dismissModal C` will result in:
`A -> push B`

**Comment by UtillYou** [comment]
@guyca In some cases, modal is not the good choice. I'm building a shop APP. I have a product detail page A, a confirm order page  B, a success page C, an address page D. I can't put B into A as a modal, because user may go to D from B, and do some operation on D, then back to B. So, what I can do in this situation?
Can I customize the back action on C? So when user click back button, I can directly pop to A.
Or something like replace the B with C?

**Comment by angelos3lex** [comment]
@guyca I was trying this enhancement locally, on android ftm as i am more familiar with. I understand that the stack doesn't support replace but we can 'simulate' it using a little bit different pop than the current one, and an immediate push on the native side.

Imagine we have a view A, then go to View B and then replace B with C.
For the pop implementation, some differences i made were: the appearing view before the push (A) to not become visible on the screen and removed the 'didAppear' events emissions. For the push i left the same implementation. Its working really nice and there is nothing i noticed weird or something. 

I will play on ios side as well to try a similar solution, but what do you think? I would like to hear the drawbacks, as i'm sure you have already thought a similar solution

**Comment by RichardLindhout** [comment]
@guyca is it possible to get the current children e.g. a getRoot() function? Then I could remove the last item and replace it with another screen.

**Comment by guyca** [comment]
@RichardLindhout I'm not sure I understand what you mean by `getRoot()`
