### ISSUE TITLE
Links to the stack layout docs are not working

### ISSUE THREAD

**Issue by nedjulius** [wix/react-native-navigation#6209]
### Issue Description

Links in the ['Basic Navigation' documentation](https://wix.github.io/react-native-navigation/docs/basic-navigation/) section that lead to further readings about the stack layout and API are not working (specifically, [this link](https://wix.github.io/react-native-navigation/docs/basic-navigation/stack.mdx) and [this link](https://wix.github.io/react-native-navigation/docs/api/layout-stack)).

### Steps to Reproduce / Code Snippets / Screenshots

Just navigate to https://wix.github.io/react-native-navigation/docs/basic-navigation/ and try clicking on the following links:

![Screenshot 2020-05-12 at 14 25 44](https://user-images.githubusercontent.com/45975811/81680949-9ec78780-945c-11ea-8edc-6ea6f3fc6e74.png)

**Comment by guyca** [comment]
Hey @nedjulius Thanks for reporting. This was recently fixed and now published as well 🙇
