### ISSUE TITLE
How to hide the hamburger icon from the nav bar?

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#621]
Hey there,

I've enabled a side menu (drawer) by the following code:

```javascript
Navigation.startSingleScreenApp({
    screen: {
      screen: ScheneKeys.WELCOME,
      title: 'Welcome',
      navigatorStyle: FixedStyles.NavBarStyleDark,
      navigatorButtons: {
        leftButtons: [],
        rightButtons: [],
      },
    },
    drawer: {
      left: {
        screen: ScheneKeys.SIDE_MENU,
      },
      disableOpenGesture: true, // on false can the drawer be opened with a swipe instead of button
    },
    animationType: 'slide-down',  // optional, add transition animation to root change: 'none', 'slide-down', 'fade'
  });
```
All works well, but there are cases on which I don't want a hamburger icon in the nav bar. (Because I don't need the drawer at all for those screens).

 For instance I don't want it on the welcome screen, but I do want it on later screens. (I use `resetTo` and replace the root screen with something else).

I only have a problem with the icon showing without me having any control over it on Android. On iOS I have to create an icon myself, and I really prefer it that way.

So how do I hide the hamburger icon?
Thanks!

**Comment by SudoPlz** [comment]
Update: I found a boolean called `backButtonHidden` that seems to be doing exactly what I want but I'm not sure were I have to add that to make it work.

**Comment by SudoPlz** [comment]
Created a pull request to resolve this. Do you mind taking a look @guyca it's just 1 line of code.

**Comment by guyca** [comment]
Generally, We'd like to avoid passing booleans in the navigation commands. Maybe we should change `setButtons` logic to remove buttons when an empty buttons array is passed. I'll bring this up on Sunday in our meeting.

**Comment by SudoPlz** [comment]
That would also work..! Right now we have absolutely no control over that button.

**Comment by SudoPlz** [comment]
Ok @guyca, I confirm that this is fixed with v2.0.0-experimental.180.
Closing.

**Comment by SudoPlz** [comment]
@guyca , I think I've lost my nav bar icons on the right side of the screen in Android when I show a new modal window.

Also the left button is always the back button, even when it's a modal screen. Is that normal behaviour?

**Comment by SudoPlz** [comment]
Not sure if the problem is the changes you made, but I've just made a pull request that fixes this:

https://github.com/wix/react-native-navigation/pull/675

**Comment by SudoPlz** [comment]
Also the padding for the right button is a bit off with this new commit, I did do anything for that on my pull request.

**Comment by guyca** [comment]
Since Modal is not an Android concept, we kind if thought of it as an Activity on Android  - which has a back button.

**Comment by SudoPlz** [comment]
Aaah gotcha..

Any idea how I can give a bit rightPadding to the right button?
Right now it's almost stuck to the right side of the screen.
