### ISSUE TITLE
[v6] showOverlay is ignoring backgroundColor/componentBackgroundColor on iOS

### ISSUE THREAD

**Issue by Bendetta** [wix/react-native-navigation#6213]
### Issue Description

I have a loading indicator I display using `showOverlay()`. I was upgrading from 3.2 to the latest and now on iOS my loading indicator has a white background that covers all content on the screen. When using 3.2, I didn't have anything specified in options and it worked as I expected. After upgrading, when I saw the white background and tried specifying the background color as transparent but it doesn't seem to have any effect. Everything continues to work as expected on android however, even without the layout options set. If I set the colors to something other than transparent, android also respects those but iOS still is entirely white.

Edit: When I downgrade to 5.1.1 and the code works as expected.

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.showOverlay({
    component: {
      name: 'LoadingIndicator',
      id: loadingIndicatorComponentId,
      options: {
        layout: {
          backgroundColor: 'transparent',
          componentBackgroundColor: 'transparent'
        }
    }
}
```
![Simulator Screen Shot - iPhone 11 - 2020-05-13 at 07 59 04](https://user-images.githubusercontent.com/1703759/81815673-e3e8c980-94ef-11ea-835b-7771a73d44be.png)
---
### Environment
* React Native Navigation version: 6.6.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, 13.4, Debug

**Comment by jinshin1013** [comment]
Hmm I couldn't reproduce the issue. Would you be able to provide a minimal reproduction on Github?

**Comment by knifedge** [comment]
Issue still persists. I think, this shouldn't be closed.

**Comment by yogevbd** [comment]
@knifedge What are you trying to achieve? keep in mind that your react component background color will always be on top, it should be transparent if you want to use `componentBackgroundColor`.
