### ISSUE TITLE
[v6] Overlay interceptTouchOutside not working

### ISSUE THREAD

**Issue by yadigarbz** [wix/react-native-navigation#6215]
### Issue Description

Hi everybody,

I realize, if your main component(which below overlay) somehow there is any other wrapper component had(In this condition almost, because safe-area-context is always in use in new versions of RN **RNVrs > 0.61) RNNOverlayWindow is not passes touch below component.

### Steps to Reproduce / Code Snippets / Screenshots

**Defining and showing the overlay**
`Navigation.showOverlay({`
      component: {
        name: ROUTES.OVERLAY.IN_APP_NOTIFICATION,
        options: {
          layout: {
            componentBackgroundColor: 'transparent',
          },
          overlay: {
            interceptTouchOutside: false,
            orientation: 'portrait',
          },
        },
      },
    }); `

---

I fixed basically with adding an import and class check into RNNOverlayWindow hitTest invoking. So there is how it looks my RNNOverlayWindow.m file

`
...other imports
#import <react-native-safe-area-context/RNCSafeAreaView.h>

... code here
if (
[hitTestResult isKindOfClass:[UIWindow class]] 
|| [hitTestResult isMemberOfClass:UIView.class] 
+ || [hitTestResult isKindOfClass:[RNCSafeAreaView class]] // Added this check to did i press on RNCSafeAreaView because even I use SafeAreaView no need to use full width SafeAreView isn't causing another conclusion.
) {
        return nil;
    }

.. code here
`

Hope helps.

### Environment
* React Native Navigation version: 6.6.0
* React Native version: 0.61
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device -Tested on iOS 13 - Debug/Release

**Comment by baotoan1905** [comment]
Same issue with react-native 0.62.2 and react-native-navigation 6.6.2. Platform IOS. Even though I don't use any wrapper at all
Here is how I set root 
![image](https://user-images.githubusercontent.com/7258479/82400451-89b4af00-9a81-11ea-82fe-ad39899d9199.png)
And register screen with no wrapper at all 
![image](https://user-images.githubusercontent.com/7258479/82400482-9c2ee880-9a81-11ea-9374-87582ed37a6e.png)
Also pass Navigation.showOverlay({
            component: {
              name: 'appNotification',
              options: {
                layout: {
                  backgroundColor: 'transparent',
                  componentBackgroundColor: 'transparent',
                },
                overlay: {
                  interceptTouchOutside: false,
                },
              },
            },
          })

**Comment by guyca** [comment]
Hey @yadigarbz 
Could you please push a project with a reproduction to GitHub? That would help us better understand the issue. Thank you! 👍

**Comment by oferRounds** [comment]
Seeing this bug also on Android,  although `interceptTouchOutside` is set to `false`, the touches does not pass
@guyca any idea of something else I can check?

**Comment by Pietro-Putelli** [comment]
Hey, someone find a solution about this problem?
Thank you

**Comment by Abramovick** [comment]
Also facing the same issue `interceptTouchOutside : false` still does not pass touch

**Comment by arnekolja** [comment]
Same here.

**Comment by Y-k-Y** [comment]
Any process? I'm facing same issue
