### ISSUE TITLE
How to disable auto RTL?

### ISSUE THREAD

**Issue by Rezania815** [wix/react-native-navigation#622]
layout changes to RTL when a RTL language is set. I want to stop this behavior.
I also tried android:supportsRtl="false" in AndroidManifest but no luck

there is not such a thing when rnn is not used

### Environment
* React Native Navigation version: latest next
* React Native version: 0.39.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device/7.1/Debug

**Comment by nidongara** [comment]
Any update on this?

**Comment by Rezania815** [comment]
I fixed this by using I18nManager.allowRTL(false).

**Comment by Niryo** [comment]
Just to add to the above comment, this code worked for me on android:
```
import {I18nManager} from 'react-native';
I18nManager.allowRTL(false)
```

(From the answer above it wasn't clear for me that I18nManager comes with react-native itself)

**Comment by obaiomari** [comment]
@Niryo where exactly we should add those two lines, i mean so it efects the whole app

**Comment by Niryo** [comment]
@obaiomari you can put it in your index.js for example...

**Comment by obaiomari** [comment]
@Niryo Thank you it worked for me, the problem now is, it will work only when reload the app after i run from terminal, i mean when i first run the app Rtl will be working  unless i reload.
this is my index code, it tried to put it before importing the app but it made no difference 
```
import { AppRegistry } from 'react-native';
import {I18nManager} from 'react-native';
I18nManager.allowRTL(false)
import App from './src/index';
AppRegistry.registerComponent('Alhdara', () => App);
```

**Comment by peymanifar** [comment]
i like this kind of problem and one or two line solution.

**Comment by mohammed2782** [comment]
@Niryo  you saved my day, thank you so much

**Comment by IsraaMoqbel** [comment]
> @Niryo Thank you it worked for me, the problem now is, it will work only when reload the app after i run from terminal, i mean when i first run the app Rtl will be working unless i reload.
> this is my index code, it tried to put it before importing the app but it made no difference
> 
> ```
> import { AppRegistry } from 'react-native';
> import {I18nManager} from 'react-native';
> I18nManager.allowRTL(false)
> import App from './src/index';
> AppRegistry.registerComponent('Alhdara', () => App);
> ```

same problem with me, first time I launch the app it's RTL!
