### ISSUE TITLE
[V6] Shared element transition breaks with different resizeModes

### ISSUE THREAD

**Issue by tastyqbit** [wix/react-native-navigation#6228]
When fromId image has resizeMode cover and toId has resizeMode contain, the image does not change shape in the transition animation like it did in previous versions.

**Comment by guyca** [comment]
Thanks for reporting @tastyqbit .
On which platform does this happen? Can you please push a reproduction?

**Comment by tastyqbit** [comment]
It happens on IOS. I found the bug while trying to upgrade my production app which I can't share the code. I went back to v2 until this is fixed. One fromId image had resizeMode="cover" and toId image had resizeMode="contain"

**Comment by guyca** [comment]
Thanks @tastyqbit 👍

**Comment by guyca** [comment]
@tastyqbit Can you please check if this happens on Android as well?

**Comment by mrousavy** [comment]
Can confirm that on the current master branch this does not appear to be a problem anymore. However if you were to set resizeMode to `'repeat'` then the app hard-crashes. That doesn't seem to be a valid use case though.

**Comment by guyca** [comment]
Thanks for looking into this @mrousavy ! 🙇
