### ISSUE TITLE
showModal background alpha animation

### ISSUE THREAD

**Issue by cspicuzza** [wix/react-native-navigation#6231]
I'm trying to recreate [this background effect](https://github.com/osdnk/react-native-reanimated-bottom-sheet/blob/master/gifs/2.gif) using showModal.   By default backgroundColors translate vertically.   I'd like the content to slide up using the native animation but the background color fade in/out.

Is there anyway to achieve that with RNN?

**Comment by jinshin1013** [comment]
Hi there, I wouldn't recommend using the `showModal` from RNN to achieve this. Rather I would suggest to:

1. Implement the gesture handler for the Swipe Card and background.
2. Show the screen with above as an overlay.
3. Use gesture handler to detect `bottom reached` and dismiss the overlay.
