### ISSUE TITLE
handling backhandler

### ISSUE THREAD

**Issue by otikindriyana** [wix/react-native-navigation#6233]
### Issue Description

[handling backhandler]

backhandler.exitApp() is not working? 
and how to backhandler in curren screen? 
i try that code in another screen still call it,
 **expected just on login screen call backhandler**

### Steps to Reproduce / Code Snippets / Screenshots

 ```
componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
  }
 
  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
  }
 
  onBackPress = () => {
    if (this.props.componentId === 'LOGINSREEN') {
       Alert.alert(
         'Confirm exit',
         'Do you want to exit App prett?',
         [
           {text: 'CANCEL', style: 'cancel'},
           {text: 'OK', onPress: () => {
             BackHandler.exitApp()
            }
          }
         ]
      );
    } else {
      Navigation.pop(this.props.componentId);
    }
 
    return true;
  }
 ```                                                         

---
### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): device

**Comment by jinshin1013** [comment]
Would you be able to provide a reproduction, preferably on Github so I can pull and play around.

**Comment by jinshin1013** [comment]
Hey @otikindriyana, I couldn't reproduce this problem unfortunately. So as you can see in the gif and code below, when user clicks `Exit` in the alert, the app is successfully exited. It'd be best if you could provide a minimal reproduction on Github so I could have a look. 

```tsx
const onBackPress = useCallback(() => {
  Alert.alert('Exit the app', 'Do you want to exit the app?', [
    {
      text: 'Cancel',
      style: 'cancel',
    },
    {
      text: 'Exit',
      onPress: () => BackHandler.exitApp(),
    },
  ])
  return true
}, [])

useEffect(() => {
  BackHandler.addEventListener('hardwareBackPress', onBackPress)

  return () => {
    BackHandler.removeEventListener('hardwareBackPress', onBackPress)
  }
}, [onBackPress])
```

![backhandler](https://user-images.githubusercontent.com/17612922/83119087-9df84c00-a112-11ea-92f0-6d3a06e44dc9.gif)

**Comment by jinshin1013** [comment]
So I did some research and it seems like `BackHandler.exitApp` does not actually terminate the app process (evident by AppState change to `background`) and the function actually invokes the default back press event, [see the code here](https://github.com/facebook/react-native/blob/master/Libraries/Utilities/BackHandler.android.js#L79).

So if you call `BackHandler.exitApp` on a pushed screen, it will not `exit` the app but will do its default behaviour which is `popping` the current screen. If you need to properly kill the app process, you will need to use https://github.com/wumke/react-native-exit-app instead.
