### ISSUE TITLE
Stuck on splash screen.

### ISSUE THREAD

**Issue by dev7050** [wix/react-native-navigation#6235]
Stuck on splash screen on first launch but if we don't kill app and launch app again the app works fine.

I have upgraded code to react-native 0.59.9 from 0.53.3. I think I may have missed some essential steps and getting launch issues. Please check and help me to make app work fine.

------------------
MainActivity.java
------------------
```java
public class MainActivity extends NavigationActivity {
  static Backbonebits b;
   public void addDefaultSplashLayout() {
        LinearLayout splash = new LinearLayout(this);
        Drawable splash_screen_bitmap = ContextCompat.getDrawable(getApplicationContext(),R.drawable.splashscreen);
        splash.setBackground(splash_screen_bitmap);

        setContentView(splash);
    }
   @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MobileAds.initialize(this, new OnInitializationCompleteListener() {
            @Override
            public void onInitializationComplete(InitializationStatus initializationStatus) {
            }
        });
           b = new Backbonebits(this);
    }
}
```
*******
------------------
MainApplication.java
------------------
```java
 public class MainApplication extends NavigationApplication {
 

 private static CallbackManager mCallbackManager = CallbackManager.Factory.create();

    protected static CallbackManager getCallbackManager() {
        return mCallbackManager;
    }

     @Override
     protected ReactGateway createReactGateway() {
         ReactNativeHost host = new NavigationReactNativeHost(this, isDebug(), createAdditionalReactPackages()) {
             @Override
             protected String getJSMainModuleName() {
                 return "index";
             }
         };
         return new ReactGateway(this, isDebug(), host);
     }
 
     @Override
     public boolean isDebug() {
         return BuildConfig.DEBUG;
     }
 
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new FBSDKPackage(mCallbackManager),
      );
    }
 
     @Override
     public List<ReactPackage> createAdditionalReactPackages() {
         return getPackages();
     }
 }
```
*******
------------------
App.js
------------------
```js
import React, { Component } from 'react';
import {
  Platform
} from 'react-native';
import { Navigation } from 'react-native-navigation'
import TermsOfUseController from "./app/routes/TermsOfUseController"
import Utility from './app/config/Utility';


const registerScreen = (name, component, styles) => {
  component.navigatorStyle = {
    ...defaultNavigatorStyles,
    ...styles
  };
  Navigation.registerComponent(name, () => component)
}

function registerAllScreens() {
  registerScreen('MyApp.LoginController', LoginController, {})
}


registerAllScreens();

User.loggedInUser((user) => {
  User.addSignOutListner()
  var screenName = 'MyApp.LoginController';
  if (user) {
    if (user.id != 0 && user.id != undefined) {
      Utility.isFirstTimeLaunch = true
      screenName = 'MyApp.HomeScreenController'; // User Already logged in 
    }
    else {
      Utility.isFirstTimeLaunch = true
      screenName = 'MyApp.LoginController'; // Not Logged in
    }
  }
  });

  Navigation.events().registerAppLaunchedListener(() => {

    Navigation.setRoot({
      root: {
        stack: {
          children: [{
            component: {
              name: screenName,
              passProps: { ...Navigation }
            }
          }],
          options: {
            topBar: {
              visible: false
            },
          }
        }
      }
    });
  });
});

```
---

* React Native Navigation version:  4.0.6
* React Native version: 0.59.9
* Platform(s) (iOS, Android, or both?): Android.
* Device info: Device and Simulator Both (All Android versions).

**Comment by guyca** [comment]
Hey @dev7050 
Try executing `Navigation.events().registerAppLaunchedListener(() => {` as soon as possible. Perhaps the native emits the event before your listener is registered.

Other this this I don't see anything suspicious.

**Comment by dev7050** [comment]
> Hey @dev7050
> Try executing `Navigation.events().registerAppLaunchedListener(() => {` as soon as possible. Perhaps the native emits the event before your listener is registered.
> 
> Other this this I don't see anything suspicious. Closing since this isn't a bug report or a feature request.

Hello @guyca, Thanks for sharing your reply. Actually the app works flawless in iOS and the issue is in android. So, could you please help me more on this because I think it may be some native issue and not js. if js, could you please help me out with js code as I have shared the app.js code and suggest me some steps how could I call launch listener as soon as possible ?

**Comment by dev7050** [comment]
Hello @guyca, One more thing the code " Navigation.events().registerAppLaunchedListener" is not triggering for the first time. If we don't kill the application and launch app again then it's triggered. I think you can help me for this.

**Comment by dev7050** [comment]
> Hey @dev7050
> Try executing `Navigation.events().registerAppLaunchedListener(() => {` as soon as possible. Perhaps the native emits the event before your listener is registered.
> 
> Other this this I don't see anything suspicious. Closing since this isn't a bug report or a feature request.

Hello @guyca , Sorry! My bad I had launch listeners inside user check condition. I resolved it by keeping launch listeners outside the condition. BTW Thanks.

**Comment by dev7050** [comment]
> Hey @dev7050
> Try executing `Navigation.events().registerAppLaunchedListener(() => {` as soon as possible. Perhaps the native emits the event before your listener is registered.
> 
> Other this this I don't see anything suspicious. Closing since this isn't a bug report or a feature request.

Hello @guyca , Sorry! My bad I had launch listeners inside user check condition. I resolved it by keeping it outside. It created problem in android, It works on iOS though.

**Comment by mblenton** [comment]
My fix was:

Navigation.events().registerAppLaunchedListener(() => {
  if (Platform.OS === 'android') {
    SplashScreen.hide();
  }
  Navigation.setRoot(myRoot);
}
