### ISSUE TITLE
Drawer item not navigating to required screen

### ISSUE THREAD

**Issue by amanthegreatone** [wix/react-native-navigation#624]
### Unable to navigate when clicking on drawer item

I am trying to build a small test app and am unable to get the drawer item to navigate correctly. Instead of going to the required screen it always goes back to home screen. I am noob to react-native and any help will be appreciated.

All code:

index.ios.js

```
import App from './App/App'
const app = new App();
```

App.js
```

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Platform
} from 'react-native';

import { Navigation } from 'react-native-navigation';

// screen related book keeping
import { registerScreens } from './Screens/screens';
registerScreens();

const navigatorStyle= {
  navBarBackgroundColor: '#4dbce9',
  navBarTextColor: '#ffff00',
  navBarSubtitleTextColor: '#ff0000',
  navBarButtonColor: '#ffffff',
  statusBarTextColorScheme: 'light',
  statusBarTextColorScheme: 'light',
  tabBarBackgroundColor: '#4dbce9',
  tabBarButtonColor: '#ffffff',
  tabBarSelectedButtonColor: '#ffff00'
};

export default class App extends Component {

  constructor(props){
    super(props)

    //load some data
    this.startApp();
  }

  startApp(){
    Navigation.startSingleScreenApp({
      screen: {
        screen: 'app.Home',
        title: 'Home',
        navigatorStyle
      },
      drawer: {
        left: {
          screen: 'app.Drawer'
        }
      }
    });

  }//end of startApp

}//end of App

```

screens.js

```
import { Navigation } from 'react-native-navigation';

import Drawer from './Drawer';
import Screen1 from './Screen1';
import Home from './Home'


export function registerScreens() {
	Navigation.registerComponent('app.Drawer', () => Drawer);
  Navigation.registerComponent('app.Home', () => Home);
  Navigation.registerComponent('app.Screen1', () => Screen1);
}
```

Drawer.js

```
import React, { Component, PropTypes } from 'react';
 import {
 	Text,
 	View,
 	TouchableOpacity,
 	ToastAndroid,
  StyleSheet
 } from 'react-native';

import Icon from 'react-native-vector-icons/Ionicons';


class Drawer extends Component {


  //navigate to Screen1 from Drawer
  _goToScreen1() {
		this._toggleDrawer();
		this.props.navigator.popToRoot({
      title: "Screen 1",
      screen: "app.Screen1"
		});
	}//end _goToScreen1

  _toggleDrawer() {
		this.props.navigator.toggleDrawer({
			to: 'closed',
			side: 'left',
			animated: true
		});
	}//end _toggleDrawer


  render(){
    const iconSearch = (<Icon name="md-search" size={26} color="#000000" style={[styles.drawerListIcon, { paddingLeft: 2 }]} />);
		const iconMovies = (<Icon name="md-film" size={26} color="#000000" style={[styles.drawerListIcon, { paddingLeft: 3 }]} />);
		const iconTV = (<Icon name="ios-desktop" size={26} color="#000000" style={styles.drawerListIcon} />);

    return(
				<View style={styles.container}>
					<View style={styles.drawerList}>

						<TouchableOpacity onPress={this._goToScreen1.bind(this)}>
							<View style={styles.drawerListItem}>
								{iconMovies}
								<Text style={styles.drawerListItemText}>
									Screen1
								</Text>
							</View>
						</TouchableOpacity>
						<View style={styles.drawerListItem}>
							{iconTV}
							<Text style={styles.drawerListItemText} onPress={() => ToastAndroid.show('Coming Soon!', ToastAndroid.SHORT)}>
								Coming Soon
							</Text>
						</View>
					</View>
				</View>

    );//end of return
  }//end of render


}//end of Drawer


Drawer.propTypes = {
  navigator: PropTypes.object
};


const styles = StyleSheet.create({
	container: {
		flex: 1,
		paddingLeft: 25,
		justifyContent: 'center'
	},
	drawerList: {

	},
	drawerListIcon: {
		width: 27
	},
	drawerListItem: {
		flexDirection: 'row',
		alignItems: 'center',
		marginBottom: 23
	},
	drawerListItemText: {
		color: 'red',
		fontWeight: 'bold',
		fontSize: 23,
		paddingLeft: 15,
		flex: 1
	},
	linearGradient: {
		// top: 0,
		// left: 0,
		// right: 0,
		// height: 248,
		// position: 'absolute'
		flex: 1
	},
});

export default Drawer
```

Home.js

```
 import React, { Component } from 'react';
 import {
 	Text,
 	View,
  TouchableOpacity,
  StyleSheet,
  Alert
 } from 'react-native';

class Home extends Component {

  static navigatorButtons = {
    leftButtons: [
      {
        //icon: require('../../img/navicon_menu.png'),
        title: 'Menu',
        id: 'menu'
      }
    ],
    rightButtons: [
      {
        title: 'Edit',
        id: 'edit'
      },
      {
        //icon: require('../../img/navicon_add.png'),
        title: 'add',
        id: 'add'
      }
    ]
  };

  constructor(props){
    super(props);
    // if you want to listen on navigator events, set this up
   this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
  }

  onNavigatorEvent(event) {
    if (event.id === 'menu') {
      this.props.navigator.toggleDrawer({
        side: 'left',
        animated: true
      });
    }
    if (event.id === 'edit') {
      Alert.alert('NavBar', 'Edit button pressed');
    }
    if (event.id === 'add') {
      Alert.alert('NavBar', 'Add button pressed');
    }
  }


  onPressScreen1() {
    this.props.navigator.push({
      title: "Screen 1",
      screen: "app.Screen1"
    });
  }

  render(){
    return(
      <View style={{flex: 1, padding: 20}}>
        <Text>Home</Text>
        <TouchableOpacity onPress={this.onPressScreen1.bind(this)}>
          <Text style={styles.button}>Screen 1</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  button: {
    textAlign: 'center',
    fontSize: 18,
    marginBottom: 10,
    marginTop: 10,
    color: 'blue'
  }
});

export default Home
```

Screen1.js

```
 import React, { Component } from 'react';
 import {
 	Text,
 	View,
 } from 'react-native';

class Screen1 extends Component {
  render(){
    return(
      <View>
        <Text>Screen 1 :)</Text>
      </View>
    );
  }
}

export default Screen1
```
---
### Environment
* React Native Navigation version: 2.0.0-experimental.164
* React Native version: 0.39.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iphone6 Debug

**Comment by amanthegreatone** [comment]
I'm assuming there is an issue with this.props.navigator.popToRoot({screen: "app.Screen1"}) function in the drawer's _goToScreen1 () function.

**Comment by amanthegreatone** [comment]
Ok so i managed to resolve the issue. popToRoot doesn't do what some of the examples show it is supposed to. Read the docs and the DeepLinks worked.

changed 

`this.props.navigator.popToRoot({screen: "app.Screen1"}) `

to 

`this.props.navigator.handleDeepLink({
      link: "Screen1"
		});`

and added the following to Home.js 

```
onNavigationEvent(event) {
// handle a deep link
    if (event.type == 'DeepLink') {
      const parts = event.link;
      if (parts == 'Screen1') {
        this.onPressScreen1();
      }
    }
}
```

**Comment by kis25791** [comment]
hi @amanthegreatone ,
I also got confused with this feature. 
This should be an issue that need to support

**Comment by guyca** [comment]
@kis25791 In order to navigate in your app from the side menu, you need to use [deep links](https://github.com/wix/react-native-navigation/wiki/Deep-links). Is this what you're using?

**Comment by kis25791** [comment]
Nope I did not you use deep links. But why "popToRoot" did not work, even your example was implemented that way? @guyca

**Comment by guyca** [comment]
Each screen has a unique navigator instance. Actions you perform on a navigator relate to the screen it's attached to.
The side menu isn't exactly a screen, It's registered as one but not perceived as such, that's why you need to use deep links and handle the deep link in the appropriate screen. Home it's clearer now 👍

**Comment by kis25791** [comment]
Thanks for your answer, then you should update your example code too. It took me hours to find this issue LOL

**Comment by guyca** [comment]
apologies

**Comment by kis25791** [comment]
@guyca Can I ask another question? Can I change navigator button (remove and add new) at run time?

**Comment by guyca** [comment]
You can call [setButtons](https://github.com/wix/react-native-navigation/wiki/Screen-API#setbuttonsparams--) from the relevant screen.
Note that on iOS, if you call set buttons from a none-visible screen, it will change the buttons on the current visible screen. That's will be fixed in the upcoming version.
To workaround this limitation, you can use change the buttons only when you screen is [visible](https://github.com/wix/react-native-navigation/wiki/Screen-API#screen-visibility)

**Comment by kis25791** [comment]
@guyca  That's awesome, thanks

**Comment by hashans** [comment]
@guyca So in other words with redux popToRoot works?

**Comment by gauravr-dev** [comment]
@guyca 
@kis25791 In order to navigate in your app from the side menu, you need to use deep links. Is this what you're using?

I am using deeplinks to navigate from drawer menu. But only `this.navigator.reestTo` and `this.navigator.showMadol` are working. `this.navigator.push()` gives the error


> **Exception '-[NSNull boolValue]: unrecognized selector sent to instance 0x10e6a1ef0' was thrown while invoking NavigationControllerIOS on target RCCManager with params**

**Comment by CusProjects** [comment]
You can use a static ref of the Navigator for another page to make the push. I did it myself and it worked

**Comment by mdelclaro** [comment]
I'm using handleDeepLink and inside the event handler, I'm using startSingleScreenApp. It does what it has to do, but it then throws me this error:

```
Invariant Violation: eventType argument is required

     This error is located at:
            in SharePlaceScreen (created by Connect(SharePlaceScreen))
            in Connect(SharePlaceScreen) (at Navigation.js:83)
            in Provider (at Navigation.js:82)
            in _class2 (at renderApplication.js:33)
            in RCTView (at View.js:60)
            in View (at AppContainer.js:102)
            in RCTView (at View.js:60)
            in View (at AppContainer.js:122)
            in AppContainer (at renderApplication.js:32) 
```
Does anyone know what could it be? I can't find anything related to this error.

**Comment by Dgs-asohail4** [comment]
Guys can you help me with this, i want a drawer behavior like one can have in native android development the drawer icon and drawer stays as it is and the fragment (component/screen) changes.. current this.props.navigator.popToRoot({screen: "app.Screen1"}) remove the drawer icon and this.props.navigator.push({screen: "app.Screen1"}) add screen to the current stack with back icon in navbar.
