### ISSUE TITLE
layout background color is not respected ..

### ISSUE THREAD

**Issue by creative-ae** [wix/react-native-navigation#6244]
No matter whereever i try to set the layout background color, it is just not respected and has no effect.. i tried to add it in default options, in the stack declaration, in static options ... it always white 

```
class LayoutsScreen extends React.Component {
  static options() {
    return {
      topBar: {
        testID: WELCOME_SCREEN_HEADER,
        title: {
          text: 'React Native Navigation'
        },
        drawBehind: true,
        background: {
            color: 'transparent',
        },
      },
      layout: {
        backgroundColor: "green",
      },
    };
  }

```
### Steps to Reproduce / Code Snippets / Screenshots

layout background color is not respected ..

---
### Environment
* React Native Navigation version: 6.6.0
* React Native version: 0.62
* Platform(s) (iOS, Android, or both?): both
 Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by jinshin1013** [comment]
Hi there, try using :`layout. componentBackgroundColor` instead of `backgroundColor`.

**Comment by vrgimael** [comment]
Is this documented anywhere? I just spent a really long time trying to figure this out too..

Thanks for answering though

**Comment by jinshin1013** [comment]
@vrgimael Although the documentation mention both options, it doesn't clearly suggest the specific use case 🙈 Will look into clarifying these further in the doc. Thanks for the suggestion!
