### ISSUE TITLE
undefined is not an object (evaluating '_native.NavigationHelpersContext.Provider')

### ISSUE THREAD

**Issue by keshav100** [wix/react-native-navigation#6247]
### I got error for header button then i just did update for all packages. then i stuck on this error 

[ENTER DESCRIPTION HERE]

### Steps to Reproduce / Code Snippets / Screenshots
![image](https://user-images.githubusercontent.com/11971739/83030881-86a55a00-a051-11ea-9f06-ebdbf4d3bbe6.png)

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/react-native-action-sheet": "^3.8.0",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/datetimepicker": "^2.4.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.5.0",
    "@react-navigation/drawer": "^5.8.0",
    "@react-navigation/material-bottom-tabs": "^5.2.8",
    "@react-navigation/native": "^5.1.7",
    "@react-navigation/native-stack": "^5.0.4",
    "@react-navigation/stack": "^5.3.7",
    "axios": "^0.19.2",
    "base-64": "^0.1.0",
    "expo": "~36.0.0",
    "expo-camera": "^8.2.0",
    "expo-image-picker": "^8.1.0",
    "expo-linear-gradient": "~8.0.0",
    "expo-location": "^8.1.0",
    "expo-media-library": "^8.1.0",
    "expo-permissions": "~8.0.0",
    "expo-sqlite": "^8.1.0",
    "firebase": "^7.14.5",
    "galio-framework": "^0.6.3",
    "moment": "^2.26.0",
    "native-base": "2.13.8",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-circular-progress": "^1.3.6",
    "react-native-elements": "^1.2.7",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-paper": "^3.9.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.8.0",
    "react-native-simple-toast": "^1.1.2",
    "react-native-storage": "^1.0.1",
    "react-native-svg": "^12.1.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.3.9",
    "react-navigation-stack": "^2.5.1",
    "react-navigation-tabs": "^2.8.13",
    "shortid": "^2.2.15",
    "sqlite3": "^4.2.0",
    "styled-components": "^5.1.1"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.1.0",
    "@babel/core": "^7.8.6"
  },
  "private": true
}

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by jinshin1013** [comment]
Hi there, you have posted `react-navigation` related issue here, this repo is `react-native-navigation`.
