### ISSUE TITLE
adding tabs to screens

### ISSUE THREAD

**Issue by amanthegreatone** [wix/react-native-navigation#625]
Just wondering how to add tabs to screens. My first screen is a dashboard that gives the user a summary of all his data (listview) so I startSingleScreenApp. On clicking an item I want to display a tabbed screen. How can I do this?

**Comment by guyca** [comment]
This is currently possible only on Android using `TopTabs`. See the deprecated, yet still relevant, example-redux project. Will be fully supported real soon 👍

**Comment by amanthegreatone** [comment]
thanks!
was checking out other navigation options and came across ex-navigation from the exponent team and I've gotta say it is pretty slick!
