### ISSUE TITLE
Handling  notch screens?

### ISSUE THREAD

**Issue by JogiPrasadPakki** [wix/react-native-navigation#6252]
How to handle notch cutout screens with  this library is it automatically handle it or not how to use react-native-safe-area-context with it

**Comment by jinshin1013** [comment]
You could use `react-native-safe-area-context` as usual or you could utilise `SafeAreaView` or `ScrollView` as well. The RNN exposes constants for heights of the topbar, statusbar and etc, more [info here](https://wix.github.io/react-native-navigation/docs/style-constants).
