### ISSUE TITLE
How To Implement Slide In From Right Animation In Android ?

### ISSUE THREAD

**Issue by jack-coder-25** [wix/react-native-navigation#6259]
### Issue Description

![android-left-right-activity-animation-1](https://user-images.githubusercontent.com/63912668/83404013-6f86b380-a427-11ea-8fd5-417a759814c3.gif)

In this above example (Not mine) when moving from one screen both of them slide to the next screen.

How can i do this in react-native-navigation so that both screen transition to produce the same result as the above one did ?

### Steps to Reproduce / Code Snippets / Screenshots

The below code is from docs which does not actually slide like the above example only one screen slides which looks ugly...

```js                                                         
{
    animations: {
      push: {
        content: {
          translationX: {
            from: require('react-native').Dimensions.get('window').width,
            to: 0,
            duration: 300
          }
        }
      },
      pop: {
        content: {
          translationX: {
            from: 0,
            to: -require('react-native').Dimensions.get('window').width,
            duration: 300
          }
        }
      }
    }
  }
```                                                    

---
### Environment
* React Native Navigation version: 6.7.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device Android O / Both Debug And Release

**Comment by pribeh** [comment]
I'm experiencing the same. The above documented code doesn't produce the correct animation on Android.

**Comment by skyliwq** [comment]
+1
