### ISSUE TITLE
[v6][Android] componentDidAppear is invoked before the animation completes on Android

### ISSUE THREAD

**Issue by arosca** [wix/react-native-navigation#6261]
### Issue Description

Sorry if this is the intended behaviour but I just noticed `componentDidAppear` is invoked before the animation completes. This is only happening on Android, works as expected on iOS. If it doesn't wait for the animation, how is it different from `componentDidMount`?

### Steps to Reproduce / Code Snippets / Screenshots

Could reproduce this in the playground app:

```js
componentDidAppear() {
  console.log('appear'); // this is shown immediately, instead of waiting for the 3500 animation delay 
}

push = () => Navigation.push(this, {
  component: {
    name: Screens.Pushed,
    passProps: this.createPassProps(),
    options: {
      topBar: {
        title: {
          text: `Pushed ${this.getStackPosition() + 1}`
        }
      },
      animations: {
        push: {
          content: {
            translationY: {
                from: getDimensions('screen').height,
                to: 0,
                duration: 3500,
            },
          },
        },
      },
    },
  },
});
```

---
### Environment
* React Native Navigation version: 6.7.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Pixel_2_API_28

**Comment by guyca** [comment]
This change is available in `6.8.0-snapshot.1071` in case anyone wants to try it out before we release a version with it.
