### ISSUE TITLE
Proper way to initialize RNN on iOS

### ISSUE THREAD

**Issue by mralj** [wix/react-native-navigation#6270]
### Issue Description

Hello everyone, I was wondering which is better/proper way to initialize RNN on iOS. Because there is difference in official docs vs Playground app.

#### Docs
According to the [docs](https://wix.github.io/react-native-navigation/docs/installing#ios)

`AppDelegate.h` should have `@interface AppDelegate : UIResponder <UIApplicationDelegate>`

And in `AppDelegate.m` we should have:

```
NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
[ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];
```

### Playground app

`AppDelegate.h` looks like `@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate>
`

And in  `[AppDelegate.m](url)` ([link](https://github.com/wix/react-native-navigation/blob/master/playground/ios/playground/AppDelegate.m))  we have:

```
[ReactNativeNavigation bootstrapWithDelegate:self launchOptions:launchOptions];

// more code here

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

```

Please, can some one explain which way is "better" and what are differences ? 

### Environment
* React Native Navigation version:  6.4.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?):  N/A

**Comment by jinshin1013** [comment]
Hi @mralj ✋ nicely spotted! The one used in the Playground app is what react-native team has officially put in the template so I'd say to follow the Playground app style.

I'll update the documentation to reflect the correct code. Thanks for the report!

**Comment by mralj** [comment]
Thank you very much for your feedback 😁
