### ISSUE TITLE
[QUESTION] How to register event listener for the native Android back button?

### ISSUE THREAD

**Issue by Jarzka** [wix/react-native-navigation#6274]
I'm upgrading React Native Navigation from version 1.1.370 to 6.5.0 (yes, this project has been unmaintained for a while).

Previously, there was a way to listen React Native Navigation events with code like this:
```
onNavigatorEvent(event) {
  if (event.type === 'NavBarButtonPress') {
    if (event.id === 'cancel' || event.id === 'backPress') {
      ...
  }
}
```

However, now in version 6.5.0, it seems that the native back button press does not fire any events and there is no example of this in the doc files AFAIK.

**Comment by jinshin1013** [comment]
@Jarzka Hi there, you can use the react-native's own solution to handle `BackHandler` event: https://reactnative.dev/docs/backhandler

**Comment by Jarzka** [comment]
Thanks!

**Comment by Lady-Gao** [comment]
请问怎么监听？
