### ISSUE TITLE
How to set the height of the bottom tab？

### ISSUE THREAD

**Issue by AKaiYi** [wix/react-native-navigation#6277]
How to set the height of the bottom tab？

**Comment by AKaiYi** [comment]
> 如何设置选项卡底部的高度吗?

**Comment by jinshin1013** [comment]
@AKaiYi Hi there, currently the library does not provide an ability to customise the height of the bottom tabs.

**Comment by AKaiYi** [comment]
> @AKaiYi大家好,目前图书馆不提供定制的能力标签底部的高度。

How to set the icon size of the bottom tabs in the bottom tabs

**Comment by govindaBump** [comment]
I am facing the same problem, if the icon is small it looks blurred and if we use a bigger image there is no way to give height/width
