### ISSUE TITLE
TitleBarButton Icon doesn't render when color defined

### ISSUE THREAD

**Issue by brianjd** [wix/react-native-navigation#628]
### Issue Description
Was creating an icon toggle, found that icon wasn't rendering when color provided.

### Environment
* React Native Navigation version: 2.0.0-experimental.162
* React Native version: 0.39.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / 6.0.0  API 23 / Debug

**Comment by guyca** [comment]
Hey Brian, Can you please provide more information? Not sure I understand the issue

**Comment by brianjd** [comment]
Trying to tint an icon via params is a no go. 

This displays an icon:
```
{
        title: 'Save',
        id: 'save',
        showAsAction: 'always',
        icon: iconsMap['FontelloIcon-heart'],
}
```

this does not:

```
{
        title: 'Save',
        id: 'save',
        showAsAction: 'always',
        icon: iconsMap['FontelloIcon-heart'],
        color: 'red' // (or a hex value)
}
```

I took a quick glance at the params parser, everything looked proper.  Have to do some more digging.

**Comment by brianjd** [comment]
As per Google, this is an anti-pattern.  Can revisit if someone really needs this feature.
