### ISSUE TITLE
Calling finish() on MainActivity onCreate breaks componentDidAppearListeners

### ISSUE THREAD

**Issue by JK0N** [wix/react-native-navigation#6281]
### Issue Description

We had to change from using launchMode "singleTask" to "singleTop" because of issues with 3rd party component (active screen with it's own Activity) being automatically cancelled when the user launches our app again from Android Home screen Icon. With the singleTop mode we have to make sure we only have one instance running by having this code in our MainActivity:

```    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (!isTaskRoot()) {
            finish();
            return;
        }
    }
```

That mandatory super.onCreate call will however cause issues as it will create new Navigator instance that gets then immediately destroyed when we call finish(). The fix for this is to have the NavigationActivity onCreate also have the "isTaskRoot()" check in place to make sure only task root will create new navigator. Not sure if there are some side effects of this in different launchModes but in this specific use case it solves the problem.

Is it even a valid case to have RNN create multiple NavigationActivities and Navigators?

### Steps to Reproduce / Code Snippets / Screenshots

Modify your AndroidManifest.xml to have MainActivity android:launchMode="singleTop".

Run the app on android and launch it with different intents using adb:

```
adb shell am start -f 0x10000000 -n YOUR.PACKAGE.NAME/.MainActivity

adb shell am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -f 0x10600000 -n YOUR.PACKAGE.NAME/.MainActivity
```

This should cause multiple instances of the app to open and with the fix in MainActivity onCreate (see on top), that won't happen as it automatically closes all non-root activities. However when we call finish() and the newly created Navigator gets destroyed, something breaks in RNN and at least componentDidAppearListeners break on current active screen.

---
### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel 3a, Android emulator, ...

**Comment by guyca** [comment]
@JK0N you can modify `NavigationActivity` to the following:

```java
public class NavigationActivity extends AppCompatActivity implements DefaultHardwareBackBtnHandler, PermissionAwareActivity, JsDevReloadHandler.ReloadListener {
    protected Navigator navigator;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (isFinishing()) return; // <- add this
        ....
    }
}
```

You can check if it resolved your use case. If it does then feel free to create a PR.

**Comment by JK0N** [comment]
Thanks @guyca, it seems to be working! 

https://github.com/wix/react-native-navigation/pull/6292

**Comment by thuongtv-vn** [comment]
What if your main activity is not at top of the stack? In the theory of singleTop, a new instance should be created? If we prevent this, it does not make sense.

**Comment by thuongtv-vn** [comment]
> @JK0N you can modify `NavigationActivity` to the following:
> 
> ```java
> public class NavigationActivity extends AppCompatActivity implements DefaultHardwareBackBtnHandler, PermissionAwareActivity, JsDevReloadHandler.ReloadListener {
>     protected Navigator navigator;
> 
>     @Override
>     protected void onCreate(@Nullable Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>         if (isFinishing()) return; // <- add this
>         ....
>     }
> }
> ```
> 
> You can check if it resolved your use case. If it does then feel free to create a PR.


What if your main activity is not at top of the stack? In the theory of singleTop, a new instance should be created? If we prevent this, it does not make sense. Actually, as I can see, the current main activity is refreshed in this case, even though a new instance will be not created.
