### ISSUE TITLE
[v6]backButton showTitle is not working in setDefaultOptions

### ISSUE THREAD

**Issue by witalobenicio** [wix/react-native-navigation#6284]
### Issue Description

If I set default options to:

```javascript
Navigation.setDefaultOptions({
    topBar: {
        hideBackButtonTitle: true,
        backButton: {
            showTitle: false,
        }
    },
});
```

This is not kept across screens. It always show the title.

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
Navigation.setDefaultOptions({
    topBar: {
        hideBackButtonTitle: true,
        backButton: {
            showTitle: false,
        }
    },
});
```

---
### Environment
* React Native Navigation version: 6.7.1
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 11 Simulator - iOS 13.4

**Comment by jinshin1013** [comment]
@witalobenicio Hi there ✋, I was not able to reproduce this on the Playground app. Would you be able to provide a minimal reproduction on Github for me to have a look please?

![backbutton](https://user-images.githubusercontent.com/17612922/84208185-7d5ac980-aaf6-11ea-8b88-bd22a363fd34.gif)

**Comment by witalobenicio** [comment]
@jinshin1013 Sorry, it was a problem with the adapter that I'm using to migrate from v1 to v6.
I fixed it and it's working. Thanks!
