### ISSUE TITLE
Changes omitted from 6.7.2 release

### ISSUE THREAD

**Issue by mathieumg** [wix/react-native-navigation#6285]
### Issue Description

When looking at the 6.7.2 release in https://github.com/wix/react-native-navigation/releases/tag/6.7.2 it seems most of the changes listed are not actually included in the release itself (see https://github.com/wix/react-native-navigation/compare/6.7.2...master) Is that by design or an oversight? I'm looking forward to one of those bugfixes and that misled me, so I just wanted to bring up in case it's a mistake.

Thank you! 😄

**Comment by guyca** [comment]
Hey @mathieumg 
6.7.2 includes a single changes - it patches a regression intoduced in 6.7.0.

The rest of the commits in master still haven't been published, but you can checkout the latest snapshot which includes them: `6.7.2-snapshot.1024` for example.

**Comment by mathieumg** [comment]
Thanks for the quick reply @guyca ! It's what I figured, but https://github.com/wix/react-native-navigation/releases/tag/6.7.2 really gave a different impression with its changelog. I imagine I'll wait for 6.8 as we prefer to use those "stable" versions in our codebase. I did check out `6.7.2-snapshot.1024` and validated that it fixes my issue, however! Thank you.

**Comment by guyca** [comment]
@mathieumg Oh you're absolutely right! Sorry about that. We're implementing auto-changelog script, it kicked in but grouped all commits in 6.7.x into 6.7.2. We're on it :)
For the mean time, you can find the correct changelog [here](https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md).
