### ISSUE TITLE
[v6]backButton color is not working in setDefaultOptions on Android

### ISSUE THREAD

**Issue by witalobenicio** [wix/react-native-navigation#6286]
### Issue Description

Setting defaultOptions like this doesn't make the button white in screen after a push:

```javascript
Navigation.setDefaultOptions({
    topBar: {
        backButton: {
            color: '#FFFFFF',
        }
    },
});
```

This happens only with push. If I push two screens and pop once, backButton color is white.

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
Navigation.setDefaultOptions({
    topBar: {
        backButton: {
            color: '#FFFFFF',
        }
    },
});
```

---
### Environment
* React Native Navigation version: 6.7.1
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Pixel 2 - Genymotion

**Comment by witalobenicio** [comment]
I think the problem is actually with `mergeOptions`. 
I have a HOC that sometimes do a style update. I was testing some things and put a code to always do a `mergeOptions`. This way, all my screens were calling mergeOptions, and then, the backButton color wasn't properly working.

**Comment by jinshin1013** [comment]
@witalobenicio Hmm, I couldn't reproduce this problem on the Playground app. Would you be able to provide a minimal reproduction on Github for me to have a look?

![android-backbutton](https://user-images.githubusercontent.com/17612922/84208409-040fa680-aaf7-11ea-90b8-bde9f393fc93.gif)

**Comment by witalobenicio** [comment]
In fact, it's working too. Thanks
