### ISSUE TITLE
dismissModal alpha animation on iOS

### ISSUE THREAD

**Issue by karimb1** [wix/react-native-navigation#6289]
### Issue Description

This is a follow up to an original issue that was reported here: https://github.com/wix/react-native-navigation/issues/6195

Which was subsequently fixed, however there seems to be a regression in the form of a flicker before the alpha animation starts.

### Steps to Reproduce / Code Snippets / Screenshots

```typescript
const component = {
    name: "example.modal",

    options: {
        layout: {
            backgroundColor: "transparent",
            componentBackgroundColor: "transparent"
        },

        modalPresentationStyle: OptionsModalPresentationStyle.overCurrentContext,

        topBar: {
            visible: false
        },

        animations: {
            showModal: {
                waitForRender: true,
                alpha: {
                    duration: 200,
                    from: 0,
                    to: 1
                }
            },

            dismissModal: {
                alpha: {
                    duration: 2000,
                    from: 1,
                    to: 0
                }
            }
        }
    }
};

Navigation.showModal({
    stack: {
        children: [ { component } ]
    }
});
```
A long animation duration was set on purpose so that you can clearly see the flicker before the animation starts.

By flicker I mean the modal disappears and shows up again in the span of less than a second.

---
### Environment
* React Native Navigation version: 6.7.2-snapshot.1024
* React Native version: 0.63.0-rc.1
* Platform(s) iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6s, running 13.5.1

Thanks

**Comment by karimb1** [comment]
Hello @jinshin1013, are you able to reproduce this issue 🙏 , if you need more details plz let me know.

**Comment by jinshin1013** [comment]
@karimb1 I'm so sorry about the delay 😓 Haven't had a chance to look into this more. Will get to the issue as soon as I get some time. Thanks for your patience.

**Comment by karimb1** [comment]
@jinshin1013 Thank you very much, take your time 🙏

**Comment by jinshin1013** [comment]
Hi @karimb1 ✋ I finally got around to this issue. However, I was not able to reproduce the problem in the Playground app. I've used the same config as what you have provided in the issue, but couldn't see the flicker :(

Would you be able to provide the minimal reproduction on the Github so I can have a look?

![modal-reproduction](https://user-images.githubusercontent.com/17612922/84719867-d677a100-afbf-11ea-890d-e36d3dd203b4.gif)
