### ISSUE TITLE
conflict with react-native-fbsdk - need to override onActivityResult

### ISSUE THREAD

**Issue by dgobaud** [wix/react-native-navigation#629]
### Issue Description

Trying to integrate https://github.com/facebook/react-native-fbsdk which requires that onActivityResult in MainActivity be overridden. The problem is com.reactnativenavigation.controllers.SplashActivity does not seem to implement onActivityResult so I can't override it. I can implement it but don't think it'll be called.

```
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
    }
```

### Steps to Reproduce / Code Snippets / Screenshots

Try to setup https://github.com/facebook/react-native-fbsdk

---
### Environment
* React Native Navigation version: next
* React Native version: 0.39
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): n/a

**Comment by dgobaud** [comment]
I actually think it might work - only change needed is to comment out @Override.

com.reactnativenavigation.controllers.SplashActivity extends AppCompatActivity which indirectly extends Activity https://developer.android.com/reference/android/support/v7/app/AppCompatActivity.html and onActivityResult is a method on Activity so if it is simply implemented as

```
public void onActivityResult(int requestCode, int resultCode, Intent data) {
  super.onActivityResult(requestCode, resultCode, data);
  MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
}
```

I think it'll work?

**Comment by perrosnk** [comment]
@dgobaud can you please help me with this issue #520 ? Could you please share your AppDelegate.m file to check if I have set mine correctly?
Thank you!

**Comment by dgobaud** [comment]
I got the android app to build and run - Facebook button shows up, clicking it opens login but when cancelling it the callback doesnt go back to the app - I'm betting this is related to onActivityResult not working correctly

**Comment by guyca** [comment]
@dgobaud You need to setup the activity result listener as described in the docs. https://github.com/wix/react-native-navigation/wiki/Android#activity-lifecycle-and-onactivityresult

**Comment by dgobaud** [comment]
@guyca thanks I'm getting a compile error though trying to implement that

```
MainApplication.java:38: error: cannot find symbol
    setActivityCallbacks(new ActivityCallbacks() {
                             ^
  symbol:   class ActivityCallbacks
  location: class MainApplication
```

**Comment by dgobaud** [comment]
fixed it with below - would be good to add to wiki page

```
import com.reactnativenavigation.controllers.ActivityCallbacks;
import android.content.Intent;
```

**Comment by perrosnk** [comment]
Could someone please publish his MainApplication.java and MainActivity.java files? That would help me a lot

**Comment by lglomer** [comment]
Mind sharing your code? 
I've implemented the suggestions but onActivityResult still doesn't seem to get called. Whenever I log in with facebook nothing happens afterwards.

**Comment by rafi** [comment]
@lglomer see https://github.com/wix/react-native-navigation/issues/373#issuecomment-270015677 for an example

**Comment by githubabbacus** [comment]
> fixed it with below - would be good to add to wiki page
> 
> ```
> import com.reactnativenavigation.controllers.ActivityCallbacks;
> import android.content.Intent;
> ```

it solved my issue thanks
