### ISSUE TITLE
Any plans to support iOS home indicator?

### ISSUE THREAD

**Issue by jaybowong** [wix/react-native-navigation#6290]
### Issue Description

It would be really nice to control the home indicator visibility by setting the options. Simple and intuitive to use.
#5581 by @lukaszfran looks cool but got ignored. #4668 by @StasDoskalenko was closed for an unknown reason. 

I believe developers need this feature for cases like watching a video in a full screen, video chat and etc..
Do you have any plans for this feature?

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by jinshin1013** [comment]
I think we could revive #5581 unless there was a reason not to support this feature.

**Comment by markhomoki** [comment]
https://github.com/wix/react-native-navigation/pull/5581 is coming from us. Would be nice to include as I think it would benefit others too. Once decided to include, let me know if need any help revisiting/updating that PR.
