### ISSUE TITLE
react-native-print hidden NavBar on iOS

### ISSUE THREAD

**Issue by hamoudaarfaoui** [wix/react-native-navigation#6296]
### Issue Description

i recently moved from v1 to v6 but have screen that pops a modal than this modal pushScreen that has button to call for `react-native-print` print modal shows on full screen and with no NavBar attached to it, this doesn't happend and work fine if there is no modal somewhere on current Navigation Stack

### Environment
```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 225.40 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7
```

**Comment by jinshin1013** [comment]
Hi @hamoudaarfaoui ✋ Could you provide a minimal reproduction on Github for us to have look please?

**Comment by hamoudaarfaoui** [comment]
Solution : don't hide React Native Navigation `TopBar` on any of previous screens .
