### ISSUE TITLE
Documantion links: some are broken

### ISSUE THREAD

**Issue by oferRounds** [wix/react-native-navigation#6299]
Hi,

Some of the docs links are broken, such as:
[Installing](https://wix.github.io/react-native-navigation/docs/before-you-start/installing
) and [Basic navigation]( https://wix.github.io/react-native-navigation/docs/before-you-start/basic-navigation)

Can you please check?
Thank you!

**Comment by jinshin1013** [comment]
Where did you get these links? All the links in the `readme.md` is directing to the correct url.

**Comment by oferRounds** [comment]
See here: https://wix.github.io/react-native-navigation/docs/before-you-start/

**Comment by jinshin1013** [comment]
My bad, you are absolutely right 🙈. Will have this fixed soon 🙏

**Comment by oferRounds** [comment]
No problem - all good! and thank you!

**Comment by guyca** [comment]
@oferRounds You're migrating??

**Comment by oferRounds** [comment]
Yes! 😃
