### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by 1appstudio** [wix/react-native-navigation#6301]
'ReactNativeNavigation/ReactNativeNavigation.h' file not found

1. Updated pod file.
2. Added react in edit scheme

Changed

#import <UIKit/UIKit.h>
@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow *window;

@end

But still build failed to run

**Comment by 1appstudio** [comment]
I can run it in android but not worked in IOS. Please help us to implement, Still working on it for 2 days.

**Comment by jinshin1013** [comment]
It seems like you have incorrectly set up the project on iOS. Could you carefully follow [the instruction](https://wix.github.io/react-native-navigation/docs/installing) when setting up your project? 

If the issue persists, let me know and provide me with a minimal reproduction on Github to have a look.
