### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by FvApp** [wix/react-native-navigation#6302]
'ReactNativeNavigation.h' file not found

Xcode 11.4.1

I am using following libraries.

"react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-navigation": "^6.7.1",
    "react-native-paper": "^3.10.1",
    "react-native-vector-icons": "^6.6.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"

How can I fix this

**Comment by jinshin1013** [comment]
Please follow [the instruction](https://wix.github.io/react-native-navigation/docs/installing) carefully when setting up your project.
