### ISSUE TITLE
Drawer Navigator

### ISSUE THREAD

**Issue by FvApp** [wix/react-native-navigation#6303]
Successfully added into my project and ran it. Now I have to add drawerNavigator in to my app.

Is there any example available to add Sidemenu. If available, please let us know. I am using     "react-native-navigation": "^6.7.1",

**Comment by jinshin1013** [comment]
You can find an example in [the documentation](https://wix.github.io/react-native-navigation/docs/sideMenu).

**Comment by delciopolanco** [comment]
The documentation you provide doesn't reflect a real example of a drawer navigation feature. :(
