### ISSUE TITLE
changing bottomTab badge with mergeOptions causes a change of the index assigned to that tab

### ISSUE THREAD

**Issue by moverholt** [wix/react-native-navigation#6305]
### Issue Description

I am listening for long press events for a specific tab w/ index 2. Anytime I call mergeOptions to update the 2nd tab's badge then the event callback starts returning index 5 instead of 2 for `selectedTabIndex`. 

### Steps to Reproduce / Code Snippets / Screenshots

Event listener:
```
    const listener = Navigation.events().registerBottomTabLongPressedListener(
      async ({selectedTabIndex}) => {
        // selectedTabIndex is 2 until I update badge then it starts returning 5 for same tab.
      },
    );
```
Updating badge count like:
```
      Navigation.mergeOptions('ALERTS_TAB', {
        bottomTab: {
          badge: newBadgeCount,
        },
      });
```
---
### Environment
* React Native Navigation version: 6.7.2
* React Native version: 6.7.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 11 simulator / 13.3 / Debug

Thank you!

**Comment by ItsNoHax** [comment]
Hi @moverholt , could you please try version 6.7.5 and see if that fixes your problem?

**Comment by moverholt** [comment]
@ItsNoHax I upgraded to 6.7.5 and still experience the issue. Thank you.

**Comment by guyca** [comment]
@moverholt Sorry if asking an obvious question - did you `pod install` after npm installing 6.7.5?

**Comment by moverholt** [comment]
@guyca no worries. After installing 6.7.5 I did run pod install, I also reset the simulator, cleared derived data, and rm'd node_modules.

Are you thinking that the reported issue should be fixed? (I can try again)

Also, I am also using react-native-navigation-hooks version 6.0.2.

Thank you for helping me.

**Comment by moverholt** [comment]
I verified 7.8.0 fixes my issue. Thank you!
