### ISSUE TITLE
How to disable pan gesture to open drawer menu?

### ISSUE THREAD

**Issue by hossamghareeb** [wix/react-native-navigation#631]
### Issue Description

I have integrated drawer menu successfully but I want to disable the pan gesture to open it. How can I do that?

### Steps to Reproduce / Code Snippets / Screenshots
---

Navigation.startSingleScreenApp({
 screen: {
   screen: 'screen.Splash',
   title: 'First Screen',
   navigatorStyle: {
     navBarBackgroundColor: '#3C274D',
     navBarTextColor: '#ffffff',
     navBarNoBorder: true,
     navBarSubtitleTextColor: '#ff0000',
     navBarButtonColor: '#ffffff',
     statusBarTextColorScheme: 'light'
   }
 }
 ,
 drawer: {
   left: {
     screen: 'screen.SideMenu'
   }
 }
});

### Environment
* React Native Navigation version: 0.37.0
* React Native version: 2.0.0
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 7 Simulator

**Comment by guyca** [comment]
set `disableOpenGesture: 'false'` in your drawer declaration. See the docs for me info 👍

**Comment by hossamghareeb** [comment]
Thanks, but is it possible to disable it only for specific screens? Do you have a link for library docs which has the whole APIs

**Comment by kyle-ssg** [comment]
+1

**Comment by terrysahaidak** [comment]
Hey @guyca, @hossamghareeb and @kyle-ssg, any solution for disabling drawer open gesture on specific screens?

**Comment by thiennhank9** [comment]
I have a same question of @terrysahaidak . How can I disable drawer open gesture on specific screens.
I find to use Drawer under Stack like this

```
export const draw = DrawerNavigator(
    {
        ChatView: { screen: ChatView },
        ListViewDone: { screen: ListViewDone },
    },
    {
        headerMode: 'screen',
        drawerPosition: 'right',
        contentComponent: Side
    }
)

export const stack = StackNavigator(
    {
        Login: { screen: Login },
        draw: { screen: draw }, //Insert drawer navigation under stack here
    },
    {
        headerMode: 'screen',
    }
)
```

But when I open drawer on ChatView scene, it now show header on top, although I set header be null  in all components, even component I use to be rendered in Drawer like this
```

static navigationOptions = {
        header: null
    };

```
Hope any ideas! Tks u in advance guys!

**Comment by thiennhank9** [comment]
/home/nhan/Pictures/header_drawer.png

**Comment by thiennhank9** [comment]
this is how it looks like
[https://ibb.co/hCwG6k](url)

**Comment by kyle-ssg** [comment]
Dynamically you can disable the drawer by doing:
```this.props.navigator.setDrawerEnabled({ side: 'right', enabled: true });```

If you want to disable this globally you can do so by doing:

```
 drawer: { // optional, add this if you want a side menu drawer in your app
    ...
    disableOpenGesture: true // optional, can the drawer be opened with a swipe instead of button
  },
```

**Comment by rgoldiez** [comment]
@kyle-ssg - disabling the drawer programmatically does indeed work, but it seems that the underlying drawer is still listening for / capturing gestures.  

More specifically, I am using a left drawer with `disableOpenGesture: false` set globally (also the default setting from the RNN).  I have a lightbox component that *should* accept and respond to touch/pan gestures to zoom and resize an image.  But it does not work even when the drawer is disabled for that lightbox screen with `this.props.navigator.setDrawerEnabled({ side: 'right', enabled: false });`.

I noticed this morning that if I set `disableOpenGestures: true` globally, the lightbox pan responders work as expected and move/resize the image with gestures.

Any idea what's going on?

**Comment by isaachinman** [comment]
Related to #2352.

**Comment by hardy-android** [comment]
` drawer: {
      left: { 
        screen: 'screenname',
        passProps: {}, 
        disableOpenGesture: true
      },
      style: { // ( iOS only )
        drawerShadow: false, // optional, add this if you want a side menu drawer shadow
        contentOverlayColor: 'rgba(0,0,0,0)', // optional, add this if you want a overlay color when drawer is open
        leftDrawerWidth: '100', // optional, add this if you want a define left drawer width (50=percent)
        //rightDrawerWidth: 10 // optional, add this if you want a define right drawer width (50=percent)
      },
      type: 'MMDrawer', // optional, iOS only, types: 'TheSideBar', 'MMDrawer' default: 'MMDrawer'
      animationType: 'slide', //optional, iOS only, for MMDrawer: 'door', 'parallax', 'slide', 'slide-and-scale'
          disableOpenGesture: true, // optional, can the drawer be opened with a swipe instead of button            
    },
`
here is disableOpenGesture: true, it's only working on iOS but not working on ANDROID

**Comment by gupta-ji6** [comment]
Try this: 

```
const AppNavigator = StackNavigator(
  {
    // Drawer: { screen: Drawer },
    Register: {
      screen: Register,
      navigationOptions: ({ navigation }) => ({
        drawerLockMode: "locked-closed",
      })
    },
    TabHome: { screen: TabHome },
    Album: { screen: Album },
    offlineContent: { screen: offlineContent },
    changePassword: { screen: changePassword },
    Player: {screen: Player},
  },
  {
    initialRouteName: "TabHome",
    // header: null
  }
);
```
