### ISSUE TITLE
bottomTabs visibility change only working from mergeOptions on iOS

### ISSUE THREAD

**Issue by ahwatts** [wix/react-native-navigation#6310]
### Issue Description

I have a `bottomTabs` layout with a `stack` component on one of the tabs. When I push something on to that stack, I want to hide the bottom tabs. Doing so only appears to work if the visibility is changed from a `Navigation.mergeOptions` call. If I do so from the component's `static options`, or as part of the `Navigation.push` command, the bottom tabs are still present.

### Steps to Reproduce / Code Snippets / Screenshots

I have a minimal example reproducing this issue here: https://github.com/ahwatts/NavTest

The `OptionDetailScreen` which is linked to from the `OptionsScreen` hides the bottom tabs via `Navigation.mergeOptions`. The other ways to do so are commented out, either in the `static options` method, or in the `Navigation.push` call on the `OptionsScreen`.

---
### Environment
* React Native Navigation version: 6.7.3
* React Native version: 0.62.2
* Platform(s): iOS
* Device info: iOS 13.5 Simulator / iPhone X with iOS 13.5, debug mode

**Comment by sorokin0andrey** [comment]
+1
Have the same problem :(

**Comment by jinshin1013** [comment]
Can reproduce the problem in `6.7.3-snapshot.1042`.
