### ISSUE TITLE
Backbutton color is not working on iOS 10

### ISSUE THREAD

**Issue by johuder33** [wix/react-native-navigation#6312]
### Issue Description

I am working on a project, and I using RNN, a great lib, so trying to change the `backButton` color I realize that is not working on iOS 10, please can you help me how to work around this ?

### Steps to Reproduce / Code Snippets / Screenshots

Just set the code below for any pushed route, and you will see that backButton color is not taking into account for iOS 10.

```js
// this is my code for change the backButton color, is not working on iOS 10
backButton: {
    color: 'white',
    showTitle: false,
},
```

---
### Environment
* React Native Navigation version: ^6.7.1
* React Native version: 0.61.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): 10.3.1

## Screenshots

| iPhone 5s  | iPhone 7  | iPhone 11  |
|---|---|---|
| <img width="370" alt="Captura de Pantalla 2020-06-15 a la(s) 21 25 21" src="https://user-images.githubusercontent.com/12078950/84722261-afce5180-af50-11ea-9143-e0457a451475.png"> | <img width="404" alt="Captura de Pantalla 2020-06-15 a la(s) 21 25 37" src="https://user-images.githubusercontent.com/12078950/84722245-a5ac5300-af50-11ea-9a66-e83bfdf04a64.png">  | <img width="353" alt="Captura de Pantalla 2020-06-15 a la(s) 21 25 29" src="https://user-images.githubusercontent.com/12078950/84722279-ba88e680-af50-11ea-9acd-377dfd069101.png"> |

**Comment by johuder33** [comment]
Do you need some additional info ? Thank u in advanced

**Comment by danilobuerger** [comment]
@johuder33 RNN v7 dropped support for iOS 10, so it is very unlikely that this will get fixed going forward.
