### ISSUE TITLE
`rnn-link` does not appear to exist as npm package

### ISSUE THREAD

**Issue by michael-caktus** [wix/react-native-navigation#6319]
### npx rnn-link fails to find existing npm package

Attempts to access `rnn-link` package [described in documentation](https://wix.github.io/react-native-navigation/docs/installing#installing-with-npx-rnn-link) result in 404s.

### Steps to Reproduce / Code Snippets / Screenshots

```bash
$ npx rnn-link

#  -- or --

$ npm i rnn-link

# -- or --

$ curl https://registry.npmjs.org/rnn-link

```

result in:

```bash
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/rnn-link - Not found
npm ERR! 404
npm ERR! 404  'rnn-link@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

# -- or if curl ---
{"error":"Not found"}

```

---
### Environment
* React Native Navigation version: 6.7.5
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): n/a

**Comment by ItsNoHax** [comment]
@eduardopelitti @guyca The rnn-link package needs to be published on npm

**Comment by eduardopelitti** [comment]
Hi @ItsNoHax @michael-caktus! 

I just started a new project and ran `npm install` with the latest version and I don't see the `bin` script in the package.json file.

I think the docs were published prior to publishing the actual changes.

Is it possible that this is the case?

The `rnn-link` command is a local reference to the bin script, not a published npm package.

**Comment by guyca** [comment]
Hey guys,
Indeed the issue is what @eduardopelitti described, sorry about that. I've reverted that change until we publish a new version.

**Comment by Mangor1no** [comment]
This problem happened again today on React Native version 0.63

**Comment by guyca** [comment]
`rnn-link` isn't a package - it's a script located in `node_modules/.bin/rnn-link`. Meaning you first need to run `npm install` before it can be executed.

**Comment by Mangor1no** [comment]
I'm using yarn for my project. I have already remove node_modules folder and reinstall packages, but nothing changes

**Comment by guyca** [comment]
hmm can you trying using `npm install` and check the `.bin` folder if it contains the `rnn-link` script?

**Comment by eduardopelitti** [comment]
> This problem happened again today on React Native version 0.63

Hi! Could you provide the React Native Navigation version you are using as well?

Using yarn, the installation steps from zero would be:

```
$ yarn add react-native-navigation
$ npx rnn-link
```

The script only exists inside the React Native Navigation package, so `rnn-link` is just a shortcut to execute that file with a fancier syntax. This reference can be found in the module's `package.json`:

```
"bin": {
    "rnn-link": "./autolink/postlink/run.js"
  },
```

(If you can't find this in RNN `package.json` then it's definitely a version issue, see below)

I see this working properly on the latest stable version, 6.11.0 which installs with `yarn add react-native-navigation`.

If you are trying to run it from a version prior to **v6.7.5**, the script will not exist and you will need to link using `react-native link react-native-navigation` or follow the steps manually from the docs (the steps labeled as hardcore are not necessary).
