### ISSUE TITLE
[Solved for iOS, still need help for Android] Start tab based app with 2nd/3rd/... tab 🤔

### ISSUE THREAD

**Issue by kanzitelli** [wix/react-native-navigation#632]
### Issue Description

Hello, 
I have kind of silly question but anyways, how can start tab based app with second tab active from the beginning? I can do ```this.props.navigator.switchToTab({ tabIndex: 1 })``` in ```componentWillMount()``` but there is a small delay.

Thank you :)

**Comment by kanzitelli** [comment]
I'm not sure if my solution is best for iOS, but it works. I've done next steps:
- Changed file ```app.js``` where I start tab based app:
```
Navigation.startTabBasedApp({
  tabs: [...],
  startIndex: 1, // added prop
  ...
});
```
- Added some code to ```renderBody``` function in ```startTabBasedApp(params)``` that is located in ```platformSpecificDeprecated.ios.js```:
```
renderBody: function() {
      return (
        <TabBarControllerIOS
          id={controllerID + '_tabs'}
          style={params.tabsStyle}
          startIndex={params.startIndex}>
...
```
- Also added code to ```initWithProps``` method  in ```RCCTabBarController.m``` file:
```
...
  // Set start index
  NSNumber *startIndex = props[@"startIndex"];
  if (startIndex)
  {
    int i = (int)[startIndex integerValue];

    if ([self.viewControllers count] > i)
    {
      self.selectedIndex = i;
    }
  }

  return self;
}
```
So this code works for iOS. 

It would be great if someone could help to do the same for Android 👍

**Comment by perrosnk** [comment]
This is related to #273

**Comment by braco** [comment]
@guyca: would a PR for this be accepted for the 1.x branch?
