### ISSUE TITLE
Shared Element Transition with popToRoot crash

### ISSUE THREAD

**Issue by alan-nakagiri** [wix/react-native-navigation#6320]
### Issue Description

Calling `popToRoot` on a screen that has a shared element transition on `pop` the app crashes. When I remove the shared element transition, `popToRoot` works. 

### Steps to Reproduce / Code Snippets / Screenshots
- push screen on without shared element transition
- push screen on with shared element transition
- call popToRoot

**with shared element transition on pop**
![with pop](https://user-images.githubusercontent.com/11300359/85047996-7e6ba680-b147-11ea-9cac-a717fff1d51d.gif)

**without shared element transition on pop**
![no pop animations](https://user-images.githubusercontent.com/11300359/85047987-77449880-b147-11ea-9ff3-13e4dc46c8c1.gif)

          animations: {
            push: {
              sharedElementTransitions: [{
                fromId,
                toId,
                duration: 250,
              }],
            },
            pop: {
              sharedElementTransitions: [{
                fromId: toId,
                toId: fromId,
                duration: 250,
              }],
            },

---
### Environment
* React Native Navigation version: 6.7.3
* React Native version: 61
* Platform(s) (iOS, Android, or both?): iOS (have not checked Android)
* Device info (Simulator/Device? OS version? Debug/Release?): simulator, debug, ios 13.3

**Comment by alan-nakagiri** [comment]
@guyca I decided not to use shared element transition for the time being. So I'll have to try again using a recent release. Will get back to you once I have time to check. Thanks!

**Comment by guyca** [comment]
gotcha. Thanks @alan-nakagiri 🙇

**Comment by yogevbd** [comment]
Fixed in latest version.
