### ISSUE TITLE
iOS: swipe back gesture hard to trigger

### ISSUE THREAD

**Issue by sebastianistoblame** [wix/react-native-navigation#6322]
### Issue Description

The iOS back gesture (swiping from the left side of the screen), which is used to dismiss a screen is hard to trigger. I remember, that I could trigger the gesture easier in RNN v1.

### Steps to Reproduce

Try swiping from the left to dismiss a screen you previously pushed a few times.
Then, go to a iOS system application (Settings, Safari, ...) and try the same.
You will notice, that in a significant amount of times it does not work reliably on your RNN app.

---
### Environment
* React Native Navigation version: 6.4.0
* React Native version: 0.61.5
* Platform: iOS
* Device info: iOS 13.5, Simulator and real device, debug and release

**Comment by vrgimael** [comment]
Hey, did you have any luck with this? I was also wondering whether I could increase the box detection size or something like that - having the swipe to go back function working only _sometimes_ is pretty annoying

Thanks!

**Comment by chris-chao** [comment]
Seconded - is there any update with this?

**Comment by Wolfenberg** [comment]
Still there
