### ISSUE TITLE
many UI bugs

### ISSUE THREAD

**Issue by webforuse** [wix/react-native-navigation#6329]
### Issue Description

1. StatusBar settings are not applied (Status bar. = visible, style)
2. apply settings to TopBar = ui bugs

see video and source code
https://github.com/webforuse/sandbox.git

---
### Environment
* React Native Navigation version: 6.7.5
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Release/Debug
![Запись экрана 2020-06-22 в 16 42 27](https://user-images.githubusercontent.com/37406224/85295063-13540400-b4a8-11ea-8ecc-6a9d7fd0b56e.gif)

**Comment by jinshin1013** [comment]
@webforuse Thanks for reporting the issue. Could you please be more specific on the actual bugs you are seeing so that we could better focus on fixing the bugs.

**Comment by webforuse** [comment]
my cases
case A:
root (bottom tab visible ,  tab#1 - topBar-visible: false)
detailScreen topBar-visible: true

tab#1 -> navigate to DetailScreen 

result: UI bug - top bar is huge

case B:
root (bottom tab visible ,  tab#1 - topBar-visible: false)

ScreenA topBar-visible: false
ScreenB topBar-visible: true

set new root ScreenA
navigate to ScreenB
on ScreenB topBar not working (back button not pressed)

if you remove the bottomBar (just navigate the screens) , result NO UI bugs

**Comment by jinshin1013** [comment]
Hi @webforuse the problem you are seeing is due to pushing to `BottomTabs` screen with `setStackRoot`. Could you try the following to see if the problem is fixed?

```diff
// splashScreen.js

// moveNext function
-Navigation.setStackRoot(componentId, getNavigationComponentBottomBar());
+Navigation.setRoot({
+  root: getNavigationComponentBottomBar()
+});
```

**Comment by webforuse** [comment]
> Hi @webforuse the problem you are seeing is due to pushing to `BottomTabs` screen with `setStackRoot`. Could you try the following to see if the problem is fixed?
> 
> ```diff
> // splashScreen.js
> 
> // moveNext function
> -Navigation.setStackRoot(componentId, getNavigationComponentBottomBar());
> +Navigation.setRoot({
> +  root: getNavigationComponentBottomBar()
> +});
> ```
Hi, @jinshin1013 
Not working. 
I have app crash

![Simulator Screen Shot - iPhone SE 13 - 2020-07-10 at 10 04 16](https://user-images.githubusercontent.com/37406224/87126380-c1c3bb80-c294-11ea-87d7-dbf1c1840f65.png)
