### ISSUE TITLE
Static backButtonHidden / title on scene?

### ISSUE THREAD

**Issue by kyle-ssg** [wix/react-native-navigation#633]
More of a question rather than an issue, I can see you are able to set a number of static properties on a scene component e.g. ```static navigatorStyle = {};``` - is it possible to do the same with title and backbutton enabled ? A lot of my routes have multiple entry points and would like to reuse as much config as possible.

**Comment by Kureev** [comment]
Hey guys,

What's the status of this issue? Do you have any ideas in mind of what needs to be done here?

I also see you removed `2.0` label from this issue, does it mean that it should be removed from the milestone as well?

**Comment by DanielZlotin** [comment]
The labels were too messy so I removed them but this feature is correctly assigned to 2.x.x milestone

**Comment by DanielZlotin** [comment]
The idea is to basically support 2 different set of options in 2 different ways. styles and buttons, dynamic and static.
Meaning:
All screen specific styles will be configurable by setting `static navigationStyle = {...}` in the screen components,
Likewise, all button stuff will be configurable by setting `static navigationButtons = {...}`, including `enabled: false`.

The same configuration object (with a future feature to override only certain values) will be settable dynamically by calling `setStyle / setButtons` with a screen Id.
