### ISSUE TITLE
[V6][Android] Topbar props are reset on dismiss

### ISSUE THREAD

**Issue by Andarius** [wix/react-native-navigation#6330]
### Issue Description

When passing from a page with a component with a topbar to another component where topbar is set to `visible = false`, the topbar appears white when animating the disappear movement.

![out](https://user-images.githubusercontent.com/5070712/85295880-d5071680-b4a0-11ea-95f2-5c17de8a3f1f.gif)

### Steps to Reproduce / Code Snippets / Screenshots

Going from a page with 
```js
topBar: {
    drawBehind: true,
    elevation: 0,
    visible: true,
    height: 55,
    background: {
        color: 'transparent'
    }
}
```

to 
```js
topBar: {
    visible: false,
}
```

One workaround is to specify here

```js
topBar: {
    visible: false,
    // Hack so it does not flicker white
    elevation: 0,
    background: {
        color: 'transparent'
    }
  //
}
```

---
### Environment
* React Native Navigation version: 6.7.5
* React Native version: 0.62.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Debug

**Comment by guyca** [comment]
Hey @Andarius 👋 
I'm not sure I understand the issue. Could you please fork the library and reproduce in the playground app?

**Comment by Andarius** [comment]
Hey @guyca , here you go: https://github.com/Andarius/react-native-navigation
Press the `Go to page` button, it will go to the search screen which I updated so the topbar is not visible anymore.
