### ISSUE TITLE
[iOS] LargeTitle is broken 

### ISSUE THREAD

**Issue by cesarm16** [wix/react-native-navigation#6337]
### Issue Description

It's not possible to apply styles to largeTitle

### Steps to Reproduce / Code Snippets / Screenshots

You can reproduce it in the playground app, try to apply tobBar styles in to SearchScreen largeTitle.

![out](https://user-images.githubusercontent.com/7118451/85776087-fc9af080-b6e5-11ea-86f3-190f8a834ac0.gif)

styles applied: 
```js
static options() {
    return {
      topBar: {
        noBorder: true, // it doesn't work 
        title: {
          text: "Search2",
          color: "green",  // it doesn't work 
        },
        largeTitle: {
          visible: true,
          color: "red",  // it doesn't work 
        },
        searchBar: true,
        background: {
          translucent: true,
        },
        searchBarPlaceholder: "Start Typing",
        hideNavBarOnFocusSearchBar: false,
      },
    };
}
```

you can see noBorder works only when largeTitle is not visible
fontFamily  it doesn't work either
---
### Environment
* React Native Navigation version: 6.8.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Iphone 11 Pro (13.5) Simulator

**Comment by bennettk** [comment]
ha, I came here to report exactly this. looks like it's iOS 13+ as it's working fine for me on iOS 12.

here's the same screen on iOS 13.5 vs 12.2, with the following options:
```
MoreView.options = {
  topBar: {
    title: {
      text: 'More',
    },
    largeTitle: {
      visible: true,
      fontSize: 36,
      fontFamily: 'Futura PT Heavy',
    }
  }
}
```


![more](https://user-images.githubusercontent.com/26149/85779044-0cabd380-b6d8-11ea-8f19-d638fd08c3b3.jpg)

**Comment by axxag** [comment]
I was able to track this down to the following PR:

https://github.com/wix/react-native-navigation/pull/6027

If I revert to RNN v6.1.2 (before the PR was merged), or manually revert the PR, the issue disappears.

**Comment by cesarm16** [comment]
Thanks for solving many of the bugs in 6.12.1, really really appreciated, but noborder is still faulty.

**Comment by guyca** [comment]
Hey @cesarm16 
We'd love to look into that - can you please open another issue with the description? Please provide as much information as you can provide, gifs and code snippets would be greatly appreciated.
