### ISSUE TITLE
dynamically change the navigation bar buttons

### ISSUE THREAD

**Issue by hossamghareeb** [wix/react-native-navigation#634]
### Issue Description

I have a screen with right bar button. This bar button will have a text with number and this number is dynamically changes in the app. I want to know how can I update the bar button title text whenever the screen is opened (Initially or when user pop back to the screen). 

### Steps to Reproduce / Code Snippets / Screenshots

static navigatorButtons = {
    rightButtons: [
      {
        title: 'Cart (0)', // for a textual button, provide the button title (label)
        id: 'cart', // id for this button, given in onNavigatorEvent(event) to help understand which button was clicked
        color:'#BF876C',
        // icon:require('./img/cart.png')
      }
    ],
    leftButtons:[
      {
        title: 'Settings',
        id: 'profile',
        color: '#BF876C'
      }
    ]
  };

The text "Cart (0)" will be dynamically changes based on number of items in the shopping cart. 
I need to know two things:

1. How can we dynamically update the navigation buttons?
2. How can we detect that the screen is appeared (something like viewWillAppear in iOS ) ?
---
### Environment

* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by kyle-ssg** [comment]
I can answer number 1 as I'm coming across a similar usecase:

```
 this.props.navigator.setButtons({leftButtons:[],rightButtons:[]})
```

As for getting the current route, I'm trying to also find out myself as this is crucial to setting dynamic titles, I was getting a case where it would update the title for the wrong view. Digging into the code I couldn't find anything: https://github.com/wix/react-native-navigation/issues/643

**Comment by longdw** [comment]
I also face the same problem.

**Comment by jeroenbourgois** [comment]
This has been requested on several occasions and up till now a workaround is required. Most solutions approach the problem with a 'man in the middle' class, we use this to for now. We created a 'Navigator' class that has a reference to the navigator prop. In our base screen class (in our case a HOC) in the constructor we pass the passed navigator to the Navigator, and from all other places we can call the Navigator to access the navigator methods.

Sounds more complex than it is :)

```
class Navigator {
  setNavigator(navigator) {
    this.navigator = navigator
  }

  push(params) {
    this.navigator && this.navigator.push(params)
  }

  setButtons(params) {
    this.navigator && this.navigator.setButtons(params)
  }
  // and so on
}
```

Than in your base Screen
```
constructor(props) {
  super(props) // if needed
  Navigator.setNavigator(props.navigator)
}
```

Hope this can help you. Maybe not the best approach, but we have seen it around the project here and it works for us.
