### ISSUE TITLE
[Feature Request] Enable LogBox React Native in RNN

### ISSUE THREAD

**Issue by zxccvvv** [wix/react-native-navigation#6348]
### Issue Description

React Native has a new feature called `LogBox` to replace `yellowScreen` and `redScreen` into better good-looking error screen since RN v0.62.0 , and i have used it in my other project,
does RNN can bring this feature too?
since the `LogBox` need react native `AppRegistry` and RNN use it own AppRegistry

`Red Screen`:

![image](https://user-images.githubusercontent.com/19633881/86130577-8b58a480-bb0e-11ea-8e69-f714ad7ebaee.png)

`LogBox Error` screen:

![image](https://user-images.githubusercontent.com/19633881/86130509-73812080-bb0e-11ea-8a77-8466b3c540e7.png)

[Source](https://levelup.gitconnected.com/goodbye-to-the-red-screen-error-in-react-native-baf59daaed0c)

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: 6.8.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): none

**Comment by jinshin1013** [comment]
Hi @zxccvvv 🙌  you can enable `LogBox` with RNN project:

```tsx
// index.js
import { unstable_enableLogBox } from 'react-native'
unstable_enableLogBox()
```

Or are you facing an error when you turn this feature on?

**Comment by guyca** [comment]
Seems to be working like @jinshin1013 mentioned. Closing 👍
