### ISSUE TITLE
Unable to pass props as function on showInAppNotification

### ISSUE THREAD

**Issue by vyky** [wix/react-native-navigation#635]
### Issue Description

Passing props as function on showInAppNotification return `this.props.text is not function. this.props.text is an instance of Object`

Is this because passing function props on showInAppNotification is not supported yet? I can do this with other apis like `push`

### Steps to Reproduce / Code Snippets / Screenshots

```js
this.props.navigator.showInAppNotification({
	screen: "Notification",
	passProps: {
		text: (text)=> this.setState({text:text})
	}
})
```

---
### Environment
* React Native Navigation version: 2.0.0-experimental.165
* React Native version: 0.39
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by varungupta85** [comment]
I am facing the same problem. Passing a function in the `passProps` in `showInAppNotification` API doesn't pass it across as a function but as an object which doesn't work when used in any `onPress` handlers. Works fine in the `push` screen API.

**Comment by MeKarina** [comment]
@vyky @varungupta85 
i experience similar problem,,, can u try https://github.com/wix/react-native-navigation/pull/644 ...

**Comment by vyky** [comment]
Thanks @MeKarina 

Confirmed it fixes this issue.
