### ISSUE TITLE
page not rendered when changing statusBar.style option in push()

### ISSUE THREAD

**Issue by Synaric** [wix/react-native-navigation#6358]
### Issue Description
screen A:
```
static options() {
    return {
      statusBar: {
        style: 'light',
        backgroundColor: '#d8201e'
      }
    }
  }
```

try to change the style of the  status bar
screen A:
```
Navigation.push(this.props.componentId, {
          component: {
            name: 'B',
            options: {
              statusBar: {
                style: 'dark',
                backgroundColor: 'white'
              }
            }
          }
        })
```

### Steps to Reproduce
A --push-->B       It's okey.
back to A
A --push-->B       B is not rendered！

**Comment by Synaric** [comment]
there is my demo
[https://github.com/Synaric/RnNavigationTest](url)

**Comment by jinshin1013** [comment]
Hi @Synaric, your demo isn't linked to your actual demo 😅
I've tried to reproduce the issue on the latest Playground app however I could not. It'd be super helpful if you could provide the reproduction.

**Comment by Synaric** [comment]
Hi @jinshin1013 , I've fixed the link. Sorry for my mistake. Looking forward for your reply!

**Comment by guyca** [comment]
This is a known Android bug on Android 8 and below - changing status bar text style freezes the entire app 🤷‍♂️
