### ISSUE TITLE
Unable to pop screen using custom stackId [ios]

### ISSUE THREAD

**Issue by yasir2hats** [wix/react-native-navigation#6359]
### Issue Description

Unable to pop screen from stack using custom stackId in ios

##### My root structure is:
```js
  Navigation.setRoot({
    root: {
      stack: {
        id: 'LoginStack',
        children: [
          {
            component: {
              name: 'com.Login',
            },
          },
        ],
      },
    },
  });
```
=> push to stack works
=> Navigation.pop('LoginStack'); doesn't pop the screen 

---
### Environment
* React Native Navigation version: 6.8.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by jinshin1013** [comment]
Hi @yasir2hats 🙌 , `Navigation.pop` expects the `componentId` so you will want to do something like:

```ts
// If you have not specified the id.
const App = ({ componentId } => {
  function pop() {
    Navigation.pop(componentId)
  }
}

// If you have provided the id.
Navigation.setRoot({
  root: {
    stack: {
      children: [
        {
          component: {
            id: 'CUSTOM_ID',
            name: 'com.Login',
          },
        },
      ],
    },
  },
});

const App = ({ componentId } => {
  function pop() {
    Navigation.pop('CUSTOM_ID')
  }
}
```

**Comment by yasir2hats** [comment]
According to the doc pop api takes 'The componentId of a screen pushed into the stack, or the stack id.'.

https://wix.github.io/react-native-navigation/api/stack#pop

So it should work with both componentId and stackId . 
It was working till RNN version:3.x.x.

It is working fine in android issue is on ios

**Comment by daveyjones** [comment]
@yasir2hats I'm seeing the same behavior. Should we re-open this ticket or start a new one?

If the documentation is wrong, then it should be removed. If the documentation is correct, then there's a bug.

**Comment by ghitier** [comment]
Hello, I encounter the same issue. We would certainly expect iOS to have the same behaviour as Android here. This ticket should be reopened imo (as an iOS bug).
