### ISSUE TITLE
Execution failed for task ':react-native-navigation:compileReactNative62DebugJavaWithJavac'.

### ISSUE THREAD

**Issue by lisichka999** [wix/react-native-navigation#6366]
### Issue Description

After upgrading to 6.8 getting the following error when run react-native run-android: 
Execution failed for task ':react-native-navigation:compileReactNative62DebugJavaWithJavac'.
Why it compile 62 form this package? I have RN 61
### Environment
* React Native Navigation version: 6.8
* React Native version: 61
* Platform : Android
* Device info: only compilation, before installation

**Comment by guyca** [comment]
Hey @lisichka999 I wasn't able to reproduce. Can you please push a project where this issue reproduces? Thanks.

**Comment by mmilvydas112** [comment]
I had similar issue with :react-native-navigation:compileReactNative60DebugJavaWithJavac

yarn remove react-native-navigation
yarn add react-native-navigation

was a fix for me. Hope it helps!

**Comment by lisichka999** [comment]
@mmilvydas112 Thanks!
I get over it by adding names.contains("reactNative62") to ignore list.
@guyca Do you think this solution is ok? Still don't understand why this package compile 62 as well.
Thanks

**Comment by priyak-sdei** [comment]
Any update. Still Facing this issue
