### ISSUE TITLE
mergeoption missing properties inherit from superclass

### ISSUE THREAD

**Issue by jebai0521** [wix/react-native-navigation#6373]
### Issue Description

while merge options

properties of class ElementTransitionOptions inherit from TransitionOptions cannot merge

just the `elementId` can be merged, other properties cannot list by objectProperties

because the class_copyPropertyList cannot get the properties of supper class

### Steps to Reproduce / Code Snippets / Screenshots

```objective-c
- (NSArray *)objectProperties:(NSObject *)object {
	NSMutableArray* properties = [NSMutableArray new];
	unsigned int count;
	objc_property_t* props = class_copyPropertyList([object class], &count);
	for (int i = 0; i < count; i++) {
		objc_property_t property = props[i];
		NSString *propertyName = [NSString stringWithCString:property_getName(property) encoding:NSUTF8StringEncoding];
		[properties addObject:propertyName];
	}

	free(props);
	return properties;
}
```

change to below code will resolve the problem

```objective-c
- (NSArray *)objectProperties2:(NSObject *)object {
  NSMutableArray* properties = [NSMutableArray new];
  unsigned int count;
  Class cls = [object class];
  do {
    objc_property_t* props = class_copyPropertyList(cls, &count);
    for (int i = 0; i < count; i++) {
      objc_property_t property = props[i];
      NSString *propertyName = [NSString stringWithCString:property_getName(property) encoding:NSUTF8StringEncoding];
      [properties addObject:propertyName];
    }
    free(props);
    cls = [cls superclass];
  } while ([cls isSubclassOfClass:[RNNOptions class]] && cls != nil);
  return properties;
}
```

---
### Environment
* React Native Navigation version: 6.8.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by guyca** [comment]
Hey @jebai0521 
Can you please explain what you're doing in JavaScript that leads to the issue you're describing? Also, is this (whatever it is you're doing) something that works on Android?

**Comment by jebai0521** [comment]
> Hey @jebai0521
> Can you please explain what you're doing in JavaScript that leads to the issue you're describing? Also, is this (whatever it is you're doing) something that works on Android?

pop with content animations, but the animation not work

**Comment by guyca** [comment]
@jebai0521 Gotcha. We have an issue opened for this internally and it has been prioritised, we should get to this soon.
