### ISSUE TITLE
SharedElementTransition stretching image

### ISSUE THREAD

**Issue by remoblaser** [wix/react-native-navigation#6379]
### Issue Description

Using the SharedElementTransition on a image that's initially a card to a destination where it acts as a background image, the image gets stretched in height instead of being correctly transitioned with a cover resize method.

### Steps to Reproduce / Code Snippets / Screenshots

*detailStack.ts*
```ts                                                         
export const detailStack = (props: DetailScreenProps): Layout => ({
  component: {
    id: 'DetailScreen',
    name: 'DetailScreen',
    passProps: props,
    options: {
      topBar: {
        visible: false,
      },
      popGesture: true,
      animations: {
        push: {
          sharedElementTransitions: [
            {
              fromId: `image${props.recipeId}`,
              toId: `image${props.recipeId}Dest`,
            },
          ],
        },
      },
    },
  },
});
```

*Card.ts* (This is rendered within a FlatList)
```ts                                                         
<Image
  style={{
    width: '100%',
    height: 300,
  }}
  source={{
    uri: item.imageUrl,
  }}
  resizeMode={'cover'}
  nativeID={`image${recipe.id}`}
/>
```

*Detail.ts*
```ts                                                         
<Image
  nativeID={`image${recipeId}Dest`}
  style={{
    height: '100%',
    width: '100%',
  }}
  source={{
    uri: imageUrl,
  }}
/>
```

Animation state just before the view is changed: [Image](https://i.imgur.com/TmvOTGG.png) 
Expected result / rendered detail screen: [Image](https://i.imgur.com/kNhvB1z.png) 

---
### Environment
* React Native Navigation version: 6.9.0
* React Native version: 16.11.0
* Platform(s): iOS
* Device info: Simulator

**Comment by jinshin1013** [comment]
Hi @remoblaser, would you be able to confirm if this is occurring on Android as well?

**Comment by yogevbd** [comment]
Fixed in latest version.
