### ISSUE TITLE
Problem when running `npx rnn-link`

### ISSUE THREAD

**Issue by byw** [wix/react-native-navigation#6382]
### Issue Description

When running `npx rnn-link`, I get `Cannot read property 'replace' of undefined`.

### Steps to Reproduce / Code Snippets / Screenshots

* `cd` into project root
* run `yarn add react-native-navigation`
* run `npx rnn-link`

---
### Environment
* React Native Navigation version: 6.9.0
* React Native version: https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz
* Platform(s) (iOS, Android, or both?): Expo starter defaults (iOS, Android, and web)
* Device info (Simulator/Device? OS version? Debug/Release?): MacOS 10.15.5

**Comment by jinshin1013** [comment]
Hi @byw, it seems like you are running an expo project. Expo is not supported with react-native-navigation.
