### ISSUE TITLE
[QUESTION] Is the SharedElement transition native?

### ISSUE THREAD

**Issue by mrousavy** [wix/react-native-navigation#6386]
### Issue Description

I'm currently using the [react-navigation-shared-element](https://github.com/IjzerenHein/react-navigation-shared-element) library, and while it is a great library it suffers from performance because it is not native. That's why I'm considering migrating my existing project to use wix navigation instead, and the biggest concern about this is the Shared Element transition. Is the SharedElement transition a native, non-JS, animation, and therefore "fast"?

Thanks!

**Comment by guyca** [comment]
Hey @mrousavy 
The transition is native. If you clone the project, you can run the playground app where there's an example for shared element transition.
Keep in mind it's till under development, we're especially focusing on it this quarter.
