### ISSUE TITLE
Allow drawer or view to overlay content and navbar

### ISSUE THREAD

**Issue by kyle-ssg** [wix/react-native-navigation#639]
I'm migrating a project over to use this however I can't seem to find a way to implement the side menu I have which overlays the content. 

Ideally this is something that could be accomplished with the drawer, If not is it possible to have a view appear over the navbar?

**Comment by guyca** [comment]
First of all - welcome to RNN 😄 
Which version of RNN are you migrating to? `latest` or `next`? In the experimental version the side menu is displayed over the content.

**Comment by kyle-ssg** [comment]
Hey @guyca thank you 😄 

Apologies for all the issues, very much keen to get one of my projects using this. This project is an amazing effort, very pleased to have come accross it!

I'm using 2.0.0-experimental.165, the drawer in this version seems to push the content alongside it rather than overlaying the content.

**Comment by guyca** [comment]
I understand you're referring to iOS. @gran33 might have some insights, he has far more ux experience on iOS then I do.

**Comment by Royce** [comment]
@kyle-ssg I was kind-of curious about what SideMenu options were available in RNN _on iOS_ too. Short answer, none of them obscure/overlay the TopBar or any of the Screen.

I had a look in src/depreciated/Controllers/Constants.js to get a list.

```
  drawer: {
    type: "MMDrawer",
    animationType: 'door',
    animationType: 'parallax',  // I like this one
    animationType: 'slide',  // Default
    animationType: 'slide-and-scale',
    type: "TheSideBar",
    animationType: 'airbnb',
    animationType: 'facebook',
    animationType: 'luvocracy',
    animationType: 'wunder-list',  // A more subtle parallax
    left: {
      screen: 'example.SideMenu',
    }
  }
```

All the sidemenu's come in from the left or right and the exist Screen remains visible on the opposite edge.

The only RNN functionality I know that overlays (but isn't full screen like modals/lightboxes) is .showInAppNotification() which slides a ContentView from the top (default) or bottom.

Perhaps a picture of what you are trying to achieve/replicate would be helpful...
Is there a particular reason you need the menu to overlay the content?

**Comment by kyle-ssg** [comment]
Hey @Royce, thanks for the reply - yeah I spotted that, I like the parallax animation :). I came to a similar conclusion that it isn't currently possible, and in fact probably won't be as MMDrawer don't intend to support this kind of effect (https://github.com/mutualmobile/MMDrawerController#what-this-library-doesnt-do). 

I'm trying to replicate my original sidemenu (see below)
http://g.recordit.co/Hmik6iA4dp.gif 

At the moment this isn't a huge priority as I compromised by hiding the navbar when adjusting the sidemenu as so:
http://g.recordit.co/3ZcIIaDAjC.gif

**Comment by kyle-ssg** [comment]
Can close this for now as it is no longer needed

**Comment by indivisable** [comment]
@kyle-ssg How did you tell the navigation bar to show after you closed the sidebar? Is there a event that gets dispatched for "sidebarclosed"?

**Comment by guyca** [comment]
@indivisable You can dispatch an action when the side menu screen is unmounted

**Comment by kyle-ssg** [comment]
@indivisable Well in that gif I'm using my own drawer component (I think you've cloned it actually 😄) with that I'm using ```onChange={(isOpen)=>{}}```

**Comment by adeb6600** [comment]
@guyca  react-native-navigation does not support feedly type of sidebar which is an overlay implementation of the sidebar. do you have an idea why it is commented out.?

**Comment by ducpt2** [comment]
+1 this style is needed. Thanks.

**Comment by guyca** [comment]
This is supported in v2

**Comment by yomybaby** [comment]
@guyca Great news! How can I make it in v2? I couldn't find a v2 documentation about it.

**Comment by isaachinman** [comment]
@guyca Is there no way to achieve this in v1? If v2 is still alpha, it's going to cause a lot of users (myself included) to think twice about upgrading.
