### ISSUE TITLE
Could not create task ':downloadRobolectricDependencies'.

### ISSUE THREAD

**Issue by josedelgado9** [wix/react-native-navigation#6390]
### Issue Description

My application built successfully a couple weeks ago, however, that i snot the case anymore. When I tried to build it today some of the gradle files were deprecated so I opened the project  with android studio and updated gradle files which was recommended by android studio. After updating, the project continues to fail building, but due to  the following errors:

FAILURE: Build failed with an exception.

#### - Where:
 .......\node_modules\react-native-navigation\lib\android\prepare-robolectric.gradle' line: 18
#### - What went wrong:
A problem occurred evaluating script.
Could not create task ':downloadRobolectricDependencies'.
Unnecessarily replacing a task that does not exist is not supported.  Use create() or register() directly instead.  You attempted to replace a task named 'downloadRobolectricDependencies', but there is no existing task with that name.

### Steps to Reproduce / Code Snippets / Screenshots

Updates recommended by android studio:
#### File: android/build.gradle
```
 dependencies {
        classpath('com.android.tools.build:gradle:4.0.0')
    }
}
```
#### File: android/gradle/wrapper/gradle-wrapper.properties
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```
---
### Environment
* React Native Navigation version: 2.29
* React Native version: 0.59.10
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus_5X_API_28_x86   Android 9.0

**Comment by guyca** [comment]
Hey @josedelgado9 
You're using a very old version, I suggest you upgrade. If you can't upgrade, you can delete the contents of this file in a post install script which should work around the issue.

**Comment by josedelgado9** [comment]
Hi @guyca, thank you for the response. What version do you suggest to update to ?

**Comment by guyca** [comment]
6.9.1 👍
