### ISSUE TITLE
Shared Element Transition for Overlays and Modals, similar to Apple's app of the day

### ISSUE THREAD

**Issue by mrousavy** [wix/react-native-navigation#6391]
### Issue Description

I think it would be great to have "overlay"-like views (Overlays and Modals) also be able to run shared element transitions in order to achieve some cool UI/UX. 

For example, looking at the App Store's app of the day animation, we have a Shared Element with a bounce/spring effect (which would also be cool as an `interpolation` option btw! 😉) which transitions into a subview over the parent's view where the parent is blurred out. The user can easily drag this view down which reveals the background view:

<img src="https://user-images.githubusercontent.com/15199031/87281540-9e4a7c00-c4f3-11ea-9268-a64b48eaaf8d.gif" alt="App store demo gif" height=600 />

I was able to achieve roughly the same (no "springy" effect unfortunately) in `react-navigation` using the `react-navigation-shared-element` library by defining a `StackCardStyleInterpolator`: 

<img src="https://user-images.githubusercontent.com/15199031/87282060-27fa4980-c4f4-11ea-9bf7-38de97a64cb1.gif" alt="react-navigation demo gif" height=600 />

Unfortunately with `wix/react-native-navigation` I can't set the details view as an overlay to the parent view and add a blur over it (which I can fade out on transition progress), it's always the white background:

<img src="https://user-images.githubusercontent.com/15199031/87282185-4f511680-c4f4-11ea-9e59-7f4ffb66dfe2.gif" alt="wix/react-native-navigation demo gif" height=600 />

> Also the scroll view behaves weirdly when I use my pan gesture handler to `transform: { scale }` the view down.. is this a separate issue?

So unless I'm missing something, that's currently not possible in wix navigation, that's why I'm opening this enhancement issue.

### Steps to Reproduce / Code Snippets / Screenshots

<table>
<tr>
  <th>App Store</th>
  <th>react-navigation</th>
  <th>wix/react-native-navigation</th>
</tr>
<tr>
  <td><img src="https://user-images.githubusercontent.com/15199031/87281540-9e4a7c00-c4f3-11ea-9268-a64b48eaaf8d.gif" alt="App store demo gif" height=400 /></td>
  <td><img src="https://user-images.githubusercontent.com/15199031/87282060-27fa4980-c4f4-11ea-9bf7-38de97a64cb1.gif" alt="react-navigation demo gif" height=400 /></td>
  <td><img src="https://user-images.githubusercontent.com/15199031/87282185-4f511680-c4f4-11ea-9e59-7f4ffb66dfe2.gif" alt="wix/react-native-navigation demo gif" height=400 /></td>
</tr>
</table>

---
### Environment
* React Native Navigation version: 6.9.0
* React Native version: 0.63.0
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): not relevant

**Comment by jinshin1013** [comment]
Hi @mrousavy, some slick animations you have here! You can definitely set overlay background colour as `transparent`.
Try setting:

```ts
layout: {
  componentBackgroundColor: 'transparent',
  backgroundColor: 'transparent',
}
```

This should set the Overlay's background colour as `transparent` and show the screen underneath the Overlay.

**Comment by guyca** [comment]
@mrousavy I'm prioritising this internally. We're a bit preoccupied with other issues but Shared Element Transition is still high in our priorities.

**Comment by mrousavy** [comment]
@jinshin1013 awesome. How would you implement the underlying blur view though? In `react-navigation` I had a separate layer which was above the first screen once the second screen was shown, meaning it also overlays the bottom tab bar.

If I wanted to implement this in react-native-navigation I'm thinking about two approaches:
1. render the blurview below my second screen. but then I can't animate the screen properly, as the blur view has to be faded out and the screen might have some Y translations added.
2. create an extra screen between those two screens, which I navigate to from first screen, and it immediately navigates to the second screen. This would act as a separate layer, but I don't think the shared element transitions will work.

**Comment by guyca** [comment]
@mrousavy I think you can place the blur view in the pushed screen and it will be faded out during the shared element transition.

**Comment by mrousavy** [comment]
closed with https://github.com/wix/react-native-navigation/pull/6716

**Comment by wal3d122** [comment]
hey! 
I've been trying to replicate this animation all day long but with no luck, 
any chance you could share how you did it please? 
Thanks
