### ISSUE TITLE
Plugin with id 'kotlin-android' not found. compileSdkVersion is not specified.

### ISSUE THREAD

**Issue by FatemeMirzaeii** [wix/react-native-navigation#6395]
### Issue Description
Hi!
I'm trying to run 'react-native-calendars' on my simulator. after cloning the repository and installing dependencies, I will get these errors on 'react-native-navigation' package to run the project. what should I do?

1. I have tried latest version of package and the problem still exists.
2. './gradlew clean' didn't work.
3. I have changed my simulator and again nothing changed.

WARNING: The following project options are deprecated and have been removed:
android.useDeprecatedNdk
NdkCompile is no longer supported

* What went wrong:
A problem occurred evaluating project ':react-native-navigation'.
> Plugin with id 'kotlin-android' not found.
> compileSdkVersion is not specified.

### Steps to Reproduce / Code Snippets / Screenshots

git clone https://github.com/wix/react-native-calendars.git
npm i
react-native run-android

![Screenshot (70)](https://user-images.githubusercontent.com/33895649/87323443-01fc9580-c544-11ea-9c19-5830f1743113.png)

---
### Environment
* React Native Navigation version: 6.7.1 - 6.9.0 - 6.9.1
* React Native version: 0.62.2
* Platform: android
* Device info (Simulator/Device? OS version? Debug/Release?): simulator android 9.0, API 28, build version 28.0.3

**Comment by zabojad** [comment]
I'm having the exact same issue. @FatemeMirzaeii have you solved it?

**Comment by FatemeMirzaeii** [comment]
> I'm having the exact same issue. @FatemeMirzaeii have you solved it?

Yes, native settings wasn't applied correctly and I've done all native installation steps from scratch.
If you are trying to run react-native-calendars too, you can see changes in this commit.


https://github.com/FatemeMirzaeii/react-native-jalali-calendars/commit/6860ec237332fde86f0ac2ac202aebe1b3ed0fb4
