### ISSUE TITLE
[Docs] Borken link

### ISSUE THREAD

**Issue by oferRounds** [wix/react-native-navigation#6403]
This link is broken: https://wix.github.io/react-native-navigation/api/events

Reached from this page: https://wix.github.io/react-native-navigation/docs/functionalComponents

**Comment by guyca** [comment]
Works for me. Have you tried `cmd+shift+r`?

**Comment by oferRounds** [comment]
Ahmm you’re right, with `cmd+shift+r` it does work. Ok cool, thank you :)
