### ISSUE TITLE
Support 'fontSize' on OptionsTopBarButton

### ISSUE THREAD

**Issue by oferRounds** [wix/react-native-navigation#6405]
font family and font weight are supported, is there a reason why font size is not?

Thank you!

**Comment by guyca** [comment]
Hey @oferRounds 👋 
This probably get left out by mistake - go ahead and PR this

**Comment by oferRounds** [comment]
Got you, will do

**Comment by stachu2k** [comment]
Yup. I can confirm, but it was working on version 6.0.0. After upgrading to 6.10.1 `fontSize` property in `rightButtons` stopped working.

**Comment by guyca** [comment]
@stachu2k On which platform?

**Comment by stachu2k** [comment]
@guyca On Android, I have Xiaomi Redmi Note 5 with Android 9. Setting `fontSize` property makes the text on right button incredibly small.

![picture](https://user-images.githubusercontent.com/6988196/88635534-0aaea900-d0b8-11ea-87f6-b76afe348ca4.jpg)
