### ISSUE TITLE
alert overlay

### ISSUE THREAD

**Issue by vijay-mca** [wix/react-native-navigation#6408]
![Screenshot from 2020-07-20 19-30-49](https://user-images.githubusercontent.com/45515876/87946547-c885d600-cabf-11ea-83a0-2a3951a0c515.png)
### Issue Description

[ENTER DESCRIPTION HERE]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: 5.6.1
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): simulator

**Comment by vijay-mca** [comment]
please help me sir

**Comment by flikQ** [comment]
@vijay-mca You didn't fill out the post correctly so we don't know what the actual issue is.

**Comment by jinshin1013** [comment]
The issue doesn't seem like it's reporting a bug.
