### ISSUE TITLE
How to use pushViewController in RCT_EXPORT_METHOD

### ISSUE THREAD

**Issue by mmok1234** [wix/react-native-navigation#641]
### Issue Description

I used a Chat UI Kit SDK on Native Module, it will help me create a RCConversationViewController for Chat UI.

> How can I get the current rootview and push the  RCConversationViewController?

My Code:
```
RCT_EXPORT_METHOD(chat)
  {
    RCConversationViewController *chat = [[RCConversationViewController alloc]init];
    chat.conversationType = ConversationType_PRIVATE;
    chat.targetId = @"74837293";
    chat.title = @"Dick lau";

    dispatch_async(dispatch_get_main_queue(), ^{
      [self pushViewController:chat animated:YES completion:nil]; <-- Error
    });
  }
```
Error msg:  No visible @interface for 'MyDigitsClass' declares the selector 'pushViewController:animated:completion:'

---
### Environment
* React Native Navigation version: 2.0.0-experimental.170
* React Native version: 0.39.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by mmok1234** [comment]
I can use get the rootViewController and **presentViewController**. But I must use **pushViewController**. 

> How can I created a navigation controller and put in the RCConversationViewController?

```
RCT_EXPORT_METHOD(chat) {
    RCConversationViewController *chat = [[RCConversationViewController alloc]init];
    chat.conversationType = ConversationType_PRIVATE;
    chat.targetId = @"74837293";
    chat.title = @"Dick lau";
    
    UIViewController *rootViewController = [UIApplication sharedApplication].delegate.window.rootViewController;

    dispatch_async(dispatch_get_main_queue(), ^{
      [rootViewController presentViewController:chat animated:YES completion:nil];
    });
  }
```

**Comment by mmok1234** [comment]
**I found a solution. Upload later**

**Comment by mmok1234** [comment]
I have an idea.

How can I use **rootViewController.presentedViewController** to the **navigationController**?

> [UIApplication sharedApplication].delegate.window.rootViewController. presentedViewController. presentedViewController.navigationController;

![xcode](http://i.imgur.com/TwqVHYD.png)

**Comment by chrise86** [comment]
Did you ever find a solution @mmok1234? I'm facing the same situation :(
