### ISSUE TITLE
DotPicker under the icon on iOS

### ISSUE THREAD

**Issue by kshport** [wix/react-native-navigation#6411]
### Issue Description

![image](https://user-images.githubusercontent.com/23387073/88019490-99f51300-cb32-11ea-9ceb-b529e0d6ca71.png)

### Steps to Reproduce / Code Snippets / Screenshots

```js                                                         
Navigation.mergeOptions('EventsTab', {
      bottomTab: {
        dotIndicator: {
          color: '#ec004a',
          size: 12,
          visible: count > 0,
          animate: true,
        },
      },
    });
```

---
### Environment
* React Native Navigation version: 6.9.1
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device, iOS 13.5, Debug and Release

**Comment by aliraza-noon** [comment]
also the size does not work cross platform on ios dot indicator is huge

**Comment by hieunguyendut** [comment]
It seem that the indicator show wrong place. I will move to tab that activated
