### ISSUE TITLE
Badge color sets only on active icon

### ISSUE THREAD

**Issue by kshport** [wix/react-native-navigation#6412]
### Issue Description

![image](https://user-images.githubusercontent.com/23387073/88019801-3c14fb00-cb33-11ea-9895-a009391f3b95.png)
![image](https://user-images.githubusercontent.com/23387073/88019841-4b944400-cb33-11ea-93d1-dc8345ad6cf6.png)

### Steps to Reproduce / Code Snippets / Screenshots

```js
static updateMessagesBadge(count) {
    Navigation.mergeOptions('ContactsTab', {
      bottomTab: {
        text: 'Messages',
        fontSize: 11,
        fontFamily: 'SFProText-Medium',
        textColor: '#6e7478',
        selectedTextColor: '#234c7d',
        iconColor: '#6e7478',
        selectedIconColor: '#234c7d',
        badge: count ? count.toString() : null,
        badgeColor: '#ec004a',
        selectedIcon: iconsMap.message,
        icon: iconsMap['message-outline'],
      },
    });
  }
```

---
### Environment
* React Native Navigation version: 6.9.1
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device, iOS 13.5, Debug and Release

**Comment by jinshin1013** [comment]
HI @kshport, thanks for reporting the issue! I've tried to reproduce the issue however was not successful 😓 . It'd be much appreciated if you could provide a minimal reproduction on Github or fork the library and reproduce the issue on the Playground app.

![Screen Shot 2020-07-23 at 6 45 20 pm](https://user-images.githubusercontent.com/17612922/88267781-ab961080-cd14-11ea-80e4-e63b2d1fa0e0.png)

**Comment by mrtry** [comment]
I have the same issue.
- React Native Navigation: 6.10.1
- iOS: 13.6

**Comment by radjivF** [comment]
i have the same issue also

**Comment by taehuA** [comment]
i had same issue

**Comment by manuel-grondona** [comment]
Having the same issue:
- RNN: 6.12.2
- iOS: 14.5

**Comment by vlatri** [comment]
Setting the badge color via `Navigation.setDefaultOptions({ bottomTab: { badgeColor: 'green' } })` appears to do the job for both active and inactive icons.

**Comment by eightyfive** [comment]
I have the same issue, `badgeColor` green is only set to green when the tab is active.

It goes back to red (default RNN color ?) as soon as the tab changes.

`Navigation.mergeOptions` has no effect if the tab is not active.
