### ISSUE TITLE
Custom component for topBar background doesn't show

### ISSUE THREAD

**Issue by quintenbox** [wix/react-native-navigation#6413]
### Issue Description

When I want to show a custom component as background for the topBar it doesn't show. In my case I want to have a gradient background as topBar background. I can change the color but he doesn't accept the `component` property. 

### Steps to Reproduce / Code Snippets / Screenshots

![image](https://user-images.githubusercontent.com/24385345/88079740-6dff7f00-cb7e-11ea-9739-4781d73d05e3.png)

I've created a `RootLayout` with the following structure: 
```js
root: {
    bottomTabs: {
      id: 'bottomTabsId',
      children: [
        {
          stack: {
            id: 'stackId',
            children: [
              {
                component: { id: 'screen1Id', name: 'screen1Id' }
              }
            ],
            options: {
              statusBar: { style: 'light' },
              topBar: {
                background: {
                  component: { name: 'MyTopBarBackgroundComponentName' } // This is the id of the component to show, which I registered with 'registerComponent'.
                }
              }
            }
          }
        }
      ]
    }
  }
```
This is the code where I register the background component: 

```js
Navigation.registerComponent( 'MyTopBarBackgroundComponentName',() => MyTopBarBackgroundComponent)
```

This is MyTopBarBackgroundComponent: 

```js
export default class MyTopBarBackgroundComponent extends Component<Props, State> {
  render() {
    return (
      <View style={[styles.container, { backgroundColor: Colors.RED }]}>
        <LinearGradient
          start={{ x: 0, y: 1 }}
          end={{ x: 1, y: 1 }}
          colors={['#4FAAFE', '#04FAFB']}
          style={styles.navbar}>
          <View />
        </LinearGradient>
      </View>
    );
  }
}
``` 
---
### Environment
* React Native Navigation version: 6.8.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, 13.6, Debug, iPhone 11

**Comment by UtillYou** [comment]
In your `MyTopBarBackgroundComponent `, try setting `styles.container` equal `flex:1` .

**Comment by jinshin1013** [comment]
Hi @quintenbox, thanks for reporting the issue! As @UtillYou it's most likely due to not setting `flex: 1` in your root container of `MyTopBarBackgroundComponent`. However if the issue persists, it'd be greatly appreciated if you could provide a minimal reproduction on Github for us to have a look. Cheers!

**Comment by quintenbox** [comment]
@jinshin1013 & @UtillYou Thanks for your answers. I've tried the `flex:1` but with no success. It should be noted that it does work when I push another screen on the stack. 

**For example:** 
I've a login screen, when I login I go to my 'main' screen, this is done by setting the root `Navigation.setRoot(...)`, this root defines the `topBar: { background: { component: { name: 'MyTopBarBackgroundComponentName' } } }` . But this does not show any background, like the image within my issue description. However, when I push another screen on top of this stack, I get my gradient.  

I will work on a reproduction project soon.

**Comment by UtillYou** [comment]
Maybe you should use `setDefaultOptions` in the entrance(usually index.js) of your app.

**Comment by UtillYou** [comment]
I have the same problem. 

React Native Version:0.63.2
react-native-navigation Version:6.9.1

My codes are:

```javascript
// In index.js of a new project
const {Navigation} = require('react-native-navigation');
const React = require('react');
const {View, Text, Button, StyleSheet} = require('react-native');

// const TopbarBg = () => {
//     return <LinearGradient style={{flex: 1}} colors={['#FF0000', '#00FF00']} />;
//   };
const TopbarBg = () => {
  return <View style={{flex: 1, backgroundColor: 'blue'}} />;
};
// Home screen declaration
const HomeScreen = (props) => {
  return (
    <View style={styles.root}>
      <Text>Hello React Native Navigation 👋</Text>
      <Button
        title="Push Settings Screen"
        color="#710ce3"
        onPress={() =>
          Navigation.push(props.componentId, {
            component: {
              name: 'Settings',
              options: {
                topBar: {
                  title: {
                    text: 'Settings',
                  },
                },
              },
            },
          })
        }
      />
    </View>
  );
};
HomeScreen.options = {
  topBar: {
    title: {
      text: 'Home',
      color: 'white',
    },
  },
};

// Settings screen declaration - this is the screen we'll be pushing into the stack
const SettingsScreen = () => {
  return (
    <View style={styles.root}>
      <Text>Settings Screen</Text>
    </View>
  );
};

Navigation.registerComponent('Home', () => HomeScreen);
Navigation.registerComponent('Settings', () => SettingsScreen);
Navigation.registerComponent('Bg', () => TopbarBg);

Navigation.events().registerAppLaunchedListener(async () => {
  Navigation.setDefaultOptions({
    topBar: {
      background: {
        component: {
          name: 'Bg',
        },
      },
    },
  });
  Navigation.setRoot({
    root: {
      stack: {
        children: [
          {
            component: {
              name: 'Home',
            },
          },
        ],
      },
    },
  });
});

const styles = StyleSheet.create({
  root: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'whitesmoke',
  },
});

```
