### ISSUE TITLE
React-Native Android is empty 

### ISSUE THREAD

**Issue by fadinasr** [wix/react-native-navigation#6417]
### Android App shows empty screen

React-Native Android app runs well with no issues but shows an empty activity (screen) and the log shows no errors or issues.

#### Registering App Lauch Event Listener
```js
Navigation.events().registerAppLaunchedListener(async () => {
  if (Platform.Version > 25) {
    await Navigation.setDefaultOptions({
      bottomTab: {
        fontSize: 12,
        selectedFontSize: 12,
      },
      topBar: {
        // hideOnScroll: true,
        drawBehind: true,
        backButton: {
          color: 'red',
        },
      },
    });
  }
  await Navigation.dismissAllModals();
  await Navigation.setRoot({
    root: {
      component: {
        name: 'App',
      },
    },
  });
});

registerComponents();
registerScreens();

```

#### Registering Screens
```js
export function registerScreens() {
  Navigation.registerComponent('Home', () => Screens.Home);
}
```

#### Login Root
```js
const LoginRoot = {
  root: {
    stack: {
      id: 'Login',
      children: [
        {
          component: {
            name: 'SignIn',
            options: {
              topBar: {
                visible: false,
              },
            },
          },
        },
      ],
    },
  },
};
```
    
<img width="256" alt="Screen Shot 2020-07-22 at 5 27 02 PM" src="https://user-images.githubusercontent.com/26388160/88188472-9354c180-cc40-11ea-8ab5-5355e25199b3.png">

---
### Environment
* React Native Navigation version: 6.8.0
* React Native version:  0.62.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All Android Devices

**Comment by fadinasr** [comment]
Tried to upgrade react-native-navigation to version 6.9.1 and the following happened:

1. IOS is working well
2. Android is showing the below error:
`
TypeError: null is not an object (evaluating 'this.nativeCommandsModule.setDefaultOptons')
`

**Comment by jinshin1013** [comment]
Hi @fadinasr the error seems to suggest that the react-native-navigation has not been linked correctly in your project. Could you please follow the [installation guide](https://wix.github.io/react-native-navigation/docs/installing) to see if your project is set up correctly? If the issue persists, feel free to comment with the minimal reproduction on Github for us to have a more detailed look 🙂  . Cheers!

**Comment by fadinasr** [comment]
Thank you @jinshin1013. Uninstalled the library and linked it manually (without auto-linking) and then update maven repository.
