### ISSUE TITLE
Change the DeviceStatusBar color in iOS

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#642]
### Issue Description
DeviceStatusBar is always colored black at the moment on iOS. If I use a colored navigation bar, with darker colors, the black status bar doesn't look good and sometimes also not very visible if the navigation bar color is too dark. I tried the `statusBarTextColorScheme` property in the navigator style and set it to `light` and `dark` but I don't see any difference. This is how the DeviceStatusBar appears currently in my app. I want to make it white.

![screen shot 2017-01-06 at 2 11 23 pm](https://cloud.githubusercontent.com/assets/7475133/21718398/2c55a1ec-d43d-11e6-8932-53c816f52d0d.png)

### Steps to Reproduce / Code Snippets / Screenshots

Reproducible using the example project on the simulator

### Environment
* React Native Navigation version: .163
* React Native version: .37
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by Crash--** [comment]
add  `View controller-based status bar appearance` `yes` to your plist. And you should be able to use `statusBarTextColorScheme` ;)

**Comment by varungupta85** [comment]
Great! Thanks for the actual fix and the workaround on Discord :)

**Comment by yungobiwan** [comment]
@Crash-- @varungupta85 Hey guys, I'm getting 

RCTStatusBarManager manager module requires that the UIViewControllerBarStatusAppeareance key in the info.plist is set to NO

Do you know why i'm getting this error?

**Comment by SudoPlz** [comment]
@yungobiwan The reason you get that error is because you're still using the `StatusBar` component from react-native.
In order to use `statusBarTextColorScheme` or `statusBarTextColorSchemeSingleScreen` in your app you have to totally remove any `<StatusBar>` components from your code.
