### ISSUE TITLE
[v6][iOS] Crash when using back button after calling setStackRoot with multiple screens

### ISSUE THREAD

**Issue by mattmcdonald-uk** [wix/react-native-navigation#6421]
### Issue Description

After using `setStackRoot` with multiple screens and using the back button the app will crash with the following exception:
`Exception NSException * "-[_UIBackButtonContainerView titleLabel]: unrecognized selector sent to instance`

I have tested this on iOS 10-13 and it occurs on iOS 11 and 12 only. iOS 10 and 13 were both fine.

### Steps to Reproduce / Code Snippets / Screenshots

Call `setStackRoot` with multiple screens, then use the back button on the screen at the top of the stack.

I have created a simple reproducible example here: https://github.com/mattmcdonald-uk/RNNDebug

---
### Environment
* React Native Navigation version: 6.9.1
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): iOS 11; iOS 12
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and physical, debug and release

**Comment by mattmcdonald-uk** [comment]
Still present in 6.10.1

**Comment by guyca** [comment]
Hey @mattmcdonald-uk We'll investigate asap.

**Comment by mattmcdonald-uk** [comment]
As a workaround, setting `showTitle: false` in your `backButton` options will avoid this crash.
