### ISSUE TITLE
Component doesn't unmount on pop /  can't detect current screen

### ISSUE THREAD

**Issue by kyle-ssg** [wix/react-native-navigation#643]
I have a usecase where I have to set the title dynamically, to do so i listen for a store changing in my screen. The issue that this is being called regardless of if it is the active screen.
```
    chatChanged = () => {
           this.props.navigator.setTitle({
                title: 'Luke',
                setTitle: this.props.roomId,
                subtitle: roomCount + ' ' + 'members'
            })
}
```

Correct me if I'm wrong but the following 2 cases apply :

- Screens aren't unmounted when navigation changes
- Each screen has it's own navigator object, meaning that we can't get the current active screen through props.

**Comment by guyca** [comment]
Hey @kyle-ssg 

That's correct, screen aren't unmounted when "temporary" navigation state changes. (Modal is displayed, active bottom tab changed, screen is pushed).
We recently added a callback to bottom tab click event, it's broadcasted only to the top most visible screen in the selected tab. Can that help you?

**Comment by kyle-ssg** [comment]
Hey @GabiGrin my app is a singleScreenApp rather than a tab based app so I'm not sure this is relevant?

**Comment by kyle-ssg** [comment]
I think the biggest problem here is that ```this.props.navigator.setTitle``` (or any screen function) from screen A should never affect screen B.

**Comment by guyca** [comment]
@kyle-ssg As you observed, seTtitle on iOS sets the title on the currently displayed screen. On Android it's bound to the navigator you used, meaning `setTitle` can be called safely from navigators which are bound to screens that are not visible.
This issue will be fixed in the v2 branch (Or maybe it's already fixed)

**Comment by kyle-ssg** [comment]
Ok thanks for letting me know, will look out for the fix - will avoid dnyamic set titles until then
