### ISSUE TITLE
[ios] showing the wrong icon in the topbar rightbutton

### ISSUE THREAD

**Issue by freightlive** [wix/react-native-navigation#6430]
After migrating to V6 i've noticed that the icons in iOS aren't correct. Am I missing something obvious here? There is a pattern; i seems that the Icon showing is always the one that should have been shown on the previous page.

iOS:

<img width="426" alt="Schermafbeelding 2020-07-23 om 23 15 15" src="https://user-images.githubusercontent.com/9133487/88340000-486ba480-cd3b-11ea-8868-7c3f10c57bc7.png">

Android (correct)

<img width="434" alt="Schermafbeelding 2020-07-23 om 23 22 22" src="https://user-images.githubusercontent.com/9133487/88340100-72bd6200-cd3b-11ea-9db2-4b381c6f6ad3.png">

The (compacted) code: 

    import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';

    let infoIcon;
    MaterialCommunityIcons.getImageSource('information-outline', 24, bbColors.textColor).then((source) => { infoIcon = source; });

    static options(passProps) {
        return {
            topBar: {
                title: {
                    text: i18next.t("activity_list.topbar")
                },
                rightButtons: [{
                    id: 'infoBtn',
                    icon: infoIcon
                }]
            }
        };
    }

---
### Environment
* React Native Navigation version: 6.9.1
* React Native version: 0.63.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by jinshin1013** [comment]
@freightlive It definitely seems weird! Could you provide a minimal reproduction on Github for us to have a better look at the issue please? Cheers!
