### ISSUE TITLE
IOS: Fixed Topbar apparence and new searchBar options

### ISSUE THREAD

**Issue by MrEkinox** [wix/react-native-navigation#6438]
Forked Repo : https://github.com/MrEkinox/react-native-navigation

- Large Title apparence fixed
- SearchBarHiddenWhenScrolling option fixed
- searchBarBackgroundColor option was added

Have Fun.

**Comment by jinshin1013** [comment]
@MrEkinox We'd really appreciate if you could put up a PR if you want these changes merged into the repo 🤗
