### ISSUE TITLE
"installing" link here is broken

### ISSUE THREAD

**Issue by artemshevch** [wix/react-native-navigation#6442]
### Issue Description

https://wix.github.io/react-native-navigation/docs/before-you-start/ - installing link here is broken

`This site can’t be reachedThe webpage at https://wix.github.io/react-native-navigation/docs/installing might be temporarily down or it may have moved permanently to a new web address.`

**Comment by jinshin1013** [comment]
Hi @artemshevch 🙌 , it is working for me currently, could you try accessing the site again? Also try clearing your cache as well. Cheers!
