### ISSUE TITLE
Keyboard.dismiss() not work on Android

### ISSUE THREAD

**Issue by Synaric** [wix/react-native-navigation#6447]
example:
```
componentWillUnmount() {
    Keyboard.dismiss()
  }
```

---
### Environment
* React Native Navigation version: 6.10.1
* React Native version: 0.62.2

**Comment by Synaric** [comment]
I know **blurOnUnmount** blurOnUnmount, but sometimes I want to dismiss the keyboard in a onPress callback, Keyboard.dismiss()  is still not working.

**Comment by karolissaint** [comment]
Any progress?

**Comment by jinshin1013** [comment]
Hi @Synaric @karolissaint, I cannot reproduce this issue on the playground app. Could you provide a minimal reproduction for us to have a look please? 

Closing this for now.
