### ISSUE TITLE
Swiping / pop gesture on root Screen breaks navigation push / touches.

### ISSUE THREAD

**Issue by Royce** [wix/react-native-navigation#645]
### Issue Description

In the example app, swiping (a pop gesture) at the edge of the root Screen causes touches to the ContentView etc. have no effect. Eg. tapping the “Push Plain Screen” link engages the TouchableHighlight animation but does not cause the navigation to push.

After further swiping the screen, eventually, the ignored touches/navigation start having an effect. When this happens the phone behaves as if mid-way through a pan gesture / pushing a Screen

Note: If the app has a SideMenu, The ContentView inside the SideMenu does not stop responding to touches.

### Steps to Reproduce / Code Snippets / Screenshots

Build and run the example app (preferably disable the drawer/SideMenu) as it makes the issue clearer.

To replicate, whilst on the root Screen, swipe from the edge of the physical screen. Now tap on a link to push a Screen. Nothing happens. :(

After this point the Screen stops responding to all touches.

Swiping at the left of the screen again makes the problem go away…

See this video: https://drive.google.com/file/d/0B6eyHwHL_Zq2OFZEdkt4anF1dzg/view?usp=sharing

---
### Environment
* React Native Navigation version: 2.0.0-experimental.165 (also .141)
* React Native version: 0.38.0
* Platform(s): iOS
* Device info: 4S; 5S; 6 Plus; 6S

**Comment by Royce** [comment]
Can someone explain what this code does in RCCViewController.m as commenting it out will make the problem disappear, yet I can still use a swipe gesturing to pop the second Screen...

```objective-c
//Bug fix: in case there is a interactivePopGestureRecognizer, it prevents react-native from getting touch events on the left screen area that the gesture handles
//overriding the delegate of the gesture prevents this from happening while keeping the gesture intact (another option was to disable it completely by demand)
self.originalInteractivePopGestureDelegate = nil;
if (self.navigationController != nil && self.navigationController.interactivePopGestureRecognizer != nil)
{
  id <UIGestureRecognizerDelegate> interactivePopGestureRecognizer = self.navigationController.interactivePopGestureRecognizer.delegate;
  if (interactivePopGestureRecognizer != nil)
  {
    self.originalInteractivePopGestureDelegate = interactivePopGestureRecognizer;
    self.navigationController.interactivePopGestureRecognizer.delegate = self;
  }
}
```

**Comment by guyca** [comment]
cc @artald

**Comment by gilra2000** [comment]
1+

**Comment by lakhman** [comment]
also had this issue dismissing a modal, setting the delegate to self fixed the issue.

```obj-c
//Bug fix: in case there is a interactivePopGestureRecognizer, it prevents react-native from getting touch events on the left screen area that the gesture handles
//overriding the delegate of the gesture prevents this from happening while keeping the gesture intact (another option was to disable it completely by demand)
self.originalInteractivePopGestureDelegate = nil;

// Add this
self.navigationController.interactivePopGestureRecognizer.delegate = self;

if (self.navigationController != nil && self.navigationController.interactivePopGestureRecognizer != nil)
// ...
```

**Comment by gilra2000** [comment]
Swiping Bug...ㅠㅠ

**Comment by grundmanise** [comment]
#428

**Comment by RobertBiehl** [comment]
@Royce I don't even know what that bug should have been which it solves. If a native view receives a gesture it is not the interactivePopGestureRecognizers problem. It seems like there was an unexpected behaviour which has been "solved" in the totally wrong location.
I'm all for removing this piece of code completely.

**Comment by jnbt** [comment]
I'm also experiencing the same issue and removing this block of code seems to solve "all" issues.

**Comment by gran33** [comment]
Seems that the issue is solved.

Plz, feel free to report if we r good or still need to handle it.

Thanks u all for the report and the solutions proposals.
