### ISSUE TITLE
setDefaultOptions not honoured (at least orientation and backgroundColor) on Android

### ISSUE THREAD

**Issue by jdegger** [wix/react-native-navigation#6451]
### Issue Description
We have the following code. With this code we can not set the orientation locked and the backgroundColor. This has worked before but I'm not sure at what version it broke.

We know for sure that the orientation is broken because when I edit `lib/android/app/src/main/java/com/reactnativenavigation/options/Orientation.java` to change the default to Portrait, it suddenly starts working. We can conclude from this that the defaultOptions are not in effect as it's still looking at the supplied default.

### Steps to Reproduce / Code Snippets / Screenshots

```js
Navigation.events().registerAppLaunchedListener(() => {

  Logger.info('App Context Started');

  // defaults for wix
  Navigation.setDefaultOptions({
    topBar: {
      visible: false,
    },
    sideMenu: {
      [Platform.OS === 'android' ? 'right' : 'left']: {
        enabled: false,
      },
    },
    layout: {
      backgroundColor: 'white',
      orientation: ['portrait'],
    },
    animations: {
      setRoot: {
        waitForRender: true,
      },
      pop: {
        waitForRender: true,
        content: {
          alpha: {
            from: 1,
            to: 0,
            duration: 300,
            startDelay: 0,
            interpolation: 'decelerate',
          },
        },
      },
      push: {
        waitForRender: true,
        content: {
          alpha: {
            from: 0,
            to: 1,
            duration: 300,
            startDelay: 0,
            interpolation: 'accelerate',
          },
        },
      },
    },
  });

  // start
  //  ...setRoot etc
  
});
```

---
### Environment
* React Native Navigation version: 6.10.1
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both release and debug builds. Mostly noticed on Android 10. Some devices do not have this problem. Mainly tested on Samsung A51.

**Comment by guyca** [comment]
Hey @jdegger I wasn't able to reproduce the issue in the Playground app. Can you please try to reproduce it in the playground app? Thanks.
