### ISSUE TITLE
type seems worng use CompositeNavigationProp

### ISSUE THREAD

**Issue by idhowardgj94** [wix/react-native-navigation#6455]
### Issue Description

I've using react-native-navigation with typescript.

everything go perfectly, expect when I use nested navigation with type hint CompositeNavigationProp.

let say, I have a nest navigation, which is a stack navigation, contain Login screen and Home screen, which is a bottom tab navigation.

so when user click logout, I can navigate back to login screen.

### Steps to Reproduce / Code Snippets / Screenshots

it's my RootStackParam and HomeBottomTabParam type: 

```ts
export type RootStackParamList = {
  Loading: undefined
  Login: undefined
  Signup: undefined
  // Home is nesting navigation
  Home: undefined
}

export type HomeBottomTabParamList = {
  Courses: undefined,
  Lectures: undefined,
  MyLearning: undefined,
  Setting: undefined
}
```

and create navigation:

```ts

const RootStack = createStackNavigator<RootStackParamList>()
export const RootStackNavigation = () => {
  return (
    <RootStack.Navigator initialRouteName={'Loading'} screenOptions={{ cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS }}>
     {/* ...... other stack screen */}
      <RootStack.Screen name="Home" component={HomeBottomTabNavigation} options={{ headerShown: false }} />
    </RootStack.Navigator>
  )
}
`HomeBottomTabNavigation` is a valid function component. and home bottom tab created by `createBottomTabNavigator()` as usual.

then, when I set a  prop type inside screen in `Home` bottom tab navigator, i use  type bellow:

```ts
type Props = CompositeNavigationProp<
  BottomTabNavigationProp<HomeBottomTabParamList, 'Setting'>,
  StackNavigationProp<RootStackParamList, 'Home'>
>;
export class Setting extends Component<any>  {
    // implement setting screen
}
```
but when i need to use `this.props.navigation.navigate('Login')`, type will go wrong.

it seems that `CompositeNavigationProp` type will contain `this.props.navigate(<arugement>)`, which is wrong.

did I use type wrong, or forget to set anything ?

---
### Environment
* React Native Navigation version: ^5.7.2
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): macbook, debug mode

**Comment by idhowardgj94** [comment]
for now, i setup components props by my own to solve this problem.

```ts
type NavigationProp = CompositeNavigationProp<
  BottomTabNavigationProp<HomeBottomTabParamList, 'Setting'>,
  StackNavigationProp<RootStackParamList>
>;

type Props = {
  route: RouteProp<HomeBottomTabParamList, 'Setting'>
  navigation: NavigationProp;
}
export class Setting extends Component<Props> {
    // implement component
}
```

but I wonder to know  is there  other solution?

**Comment by ksielyov** [comment]
import { CompositeNavigationProp } from '@react-navigation/native';

It was deleted; No method exist there
