### ISSUE TITLE
[Android] Difference in right/left topbar button size using the same image.

### ISSUE THREAD

**Issue by ItsNoHax** [wix/react-native-navigation#6458]
### Issue Description

It seems there is a difference in how the left and right topbar buttons calculate the size of the button.

![topbar](https://user-images.githubusercontent.com/4223434/89545531-c469f000-d803-11ea-93c4-21e215e1d8f7.png)

### Steps to Reproduce / Code Snippets / Screenshots

PNG is 512 x 512

```js
  static options(): Options {
    return {
      topBar: {
        leftButtons: [
          {
            id: 'user-cog-left',
            color: 'white',
            icon: require('images/user_cog.png'),
          },
        ],
        rightButtons: [
          {
            id: 'user-cog-right',
            color: 'white',
            icon: require('images/user_cog.png'),
          },
        ],
      },
    };
  }
```

---
### Environment
* React Native Navigation version: 6.9.0
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator + Device, Android 10, Debug

**Comment by guyca** [comment]
This happens when the icon is bundled in a single resolution. To fix this icons need to be generated for multiple [densities](OptionsTopBarButton)

**Comment by hannojg** [comment]
Hey, the link is broken and I face the same issue. Could you please update the link?
Thanks in advance!
