### ISSUE TITLE
support navigating between RN ViewController and native viewcontroller?

### ISSUE THREAD

**Issue by sdutlyb** [wix/react-native-navigation#6464]
Dose it support navigating between RN ViewController (RNNComponentViewController) and native viewcontroller and pass params, to be used in RN&native hybrid apps?

just like one of the libs:  https://github.com/listenzz/react-native-navigation-hybrid

**Comment by jinshin1013** [comment]
@sdutlyb You can utilise [External Component](https://wix.github.io/react-native-navigation/docs/externalComponent/#fragment) which allows registering native views with RNN. I'm not familiar with native code so let us know if you meant something else 👍
