### ISSUE TITLE
Bottom tab not working correctly when keyboard shown.

### ISSUE THREAD

**Issue by suupham2506** [wix/react-native-navigation#6467]
### Issue Description

Bottom tab is hidden when keyboard is shown. It makes my text input hidden also. But it works fine on single stack.

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]
This is screen when I push to.
![Simulator Screen Shot - iPhone 11 - 2020-08-12 at 20 41 31](https://user-images.githubusercontent.com/28852565/90022346-9d685e00-dcdc-11ea-9be1-1f59ee8fc068.png)

And this is screen when I touched on text input. My text input is hidden somehow. (on bottomtabs stack)
![Simulator Screen Shot - iPhone 11 - 2020-08-12 at 20 36 01](https://user-images.githubusercontent.com/28852565/90022485-cb4da280-dcdc-11ea-9164-1710d5dd6d49.png)
But when I displayed this screen on single stack. My text input worked fine. (single stack)
![Simulator Screen Shot - iPhone 11 - 2020-08-12 at 20 48 18](https://user-images.githubusercontent.com/28852565/90022826-31d2c080-dcdd-11ea-8f94-6675005b1b6d.png)

---
### Environment
* React Native Navigation version: ^6.11.0
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): All devices.

**Comment by jinshin1013** [comment]
@suupham2506 Could you please provide a minimal reproduction on Github? It'd be helpful for us to see what is going on the screen with the reproduction 🤓

**Comment by jinshin1013** [comment]
Closing this for now. Feel free to comment here any time :)
