### ISSUE TITLE
IOS titleImage sizing 

### ISSUE THREAD

**Issue by kyle-ssg** [wix/react-native-navigation#647]
Forgive my lack of knowledge in objc however there doesn't seem to be an effort to fit the title image within the navigation bar. I find that the image is bigger than the navigation bar

After researching a bit I have found that adjusting  ```setupTitleImage``` does the trick, it seems that a combination of this and a titleImageSize prop would be a good idea
```
-(void)setupTitleImage
{
   //UIImageView *imageView = [[UIImageView alloc] initWithImage:titleImage];
    UIImageView *imageView=[[UIImageView alloc]initWithFrame:CGRectMake(0, 0, 85, 34)];
    imageView.image= titleImage;
```

**Comment by IgorVanian** [comment]
Awesome. This should be merged ASAP because right now titleImage is useless :/

**Comment by kyle-ssg** [comment]
I kind of have to agree here, I know there are more elegant solutions but it's better than what we currently have.
