### ISSUE TITLE
Question about missing icon

### ISSUE THREAD

**Issue by Jarzka** [wix/react-native-navigation#6479]
Hi

I have the following top bar which contains a left button:

```
topBar: {
  title: {
    text: 'Hello',
  },
  leftButtons: [
    {
      id: 'Menu',
      icon: require('./img/menu-white.png'),
    },
  ],
},
```

The icon I'm using is not shown on a physical device in release build, even if it works on emulator and on physical device when developing the app locally. Any idea what might cause this?

**Comment by jinshin1013** [comment]
@Jarzka Hi there, it'd be great if you could provide us with a minimal reproduction on Github so that we could have a better look at the issue. Cheers!

**Comment by Jarzka** [comment]
Unfortunately I'm unable to create a minimal working reproduction of this bug, especially since it happens only when running release build from app store (I tried running release build locally too, but it was just stuck on the splash screen). However, I do understand that if this is not a known issue, it's pretty hard to debug it without a broken example project. I'm not even sure if this is related to React Native Navigation or React Native itself.

I'll come back to this if I find a solution.

**Comment by jinshin1013** [comment]
@Jarzka Thanks! Feel free to comment back here and we will reopen the issue! Cheers :)

**Comment by Jarzka** [comment]
I'll tried using the menu icon in an `Image` tag. The icon is drawn incorrectly as a black rectangle. So, it seems that there is some problem with my icons in release build, and this issue is probably not related to React Native Navigation.

**Comment by Jarzka** [comment]
I was able to solve the issue by settings:

```shrinkResources false```

as adviced here: https://github.com/facebook/react-native/issues/21790
