### ISSUE TITLE
Tab Navigation Changed Event

### ISSUE THREAD

**Issue by ziftinpeki** [wix/react-native-navigation#648]
Hi,

I'm using Navigation.startTabBasedApp method in my app and i need information about active tab or change event info. How can i get tab changed event or active tab information? 

Thanks,
m.

**Comment by ziftinpeki** [comment]
Hi,

New version trigerred bottom tab change event. 

Thanks.

`// add this line to constructor method
this.props.navigator.setOnNavigatorEvent(this._onNavigatorEvent.bind(this));

// add this function after construtor method
_onNavigatorEvent(event) {
        if (event.id == 'bottomTabSelected') { // handle change }
}`

**Comment by Jaafar-abusair** [comment]
The event didn't get trigger when switch tab !

**Comment by Jaafar-abusair** [comment]
It worked after I upgraded to version Exp.219
