### ISSUE TITLE
it is cause some issue when i push native UIControllerView in 4.0

### ISSUE THREAD

**Issue by princeSmall** [wix/react-native-navigation#6487]
### Issue Description

headerHeight will heigth more when i pop from native or jswebView

### Steps to Reproduce / Code Snippets / Screenshots

[creatStackNavigation headerHeight will heigth more when i pop from native]

---
### Environment
* React Native Navigation version: 4.4
* React Native version:0.6.6
* Platform(s) (iOS, Android, or both?): only iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device

**Comment by jinshin1013** [comment]
@princeSmall Your code snippet suggests that you are referring to `react-navigation` 😅. Let me know if you are using `react-native-navigation` and some more detailed information could be appreciated, cheers!
