### ISSUE TITLE
Calling setRoot while having bottom tabs - iOS

### ISSUE THREAD

**Issue by vdino96** [wix/react-native-navigation#6491]
Issue Description
Hello,

This is a copy of an already closed issue that was about android platform. The issue is the same, the difference is only the platform. As I've seen that the Android version is fixed, maybe somebody can take a look at the iOS bug too.

PS: Thank you for fixing the android bug.

Original issue: #5890 

Environment
React Native Navigation version: ^6.12
React Native version: 0.62.2
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): Device - any iOS device

**Comment by vajid-khan** [comment]
Hi @vdino96 any update on this. I am facing same issue on ios with version 6.11

**Comment by vdino96** [comment]
Hello @vajid-khan, the only fix to this that I have found, is downgrading RNN to 6.5. On that (and maybe prior versions), the bug is not present.

This is not a solution tho, as newer versions have some other bug fixes that are great, but this one is a higher priority for me.

**Comment by vajid-khan** [comment]
@vdino96 the issue is resolved, try to clear store after the setRoot promise is resolved
```
//Changing navigation root
Navigation.setRoot({
....
})
.then(()=>{
//Clearing old stack store
});
```

**Comment by vdino96** [comment]
Hello @vajid-khan, can you please elaborate how to clear the store. I have tried clearing my Store which is my local container that stores variables in the application. Other than that, I haven't found any Navigation store that I can clear.

**Comment by vajid-khan** [comment]
My screen re render was due to redux store. Earlier after logout I was calling setRoot to set authStack navigation as root but before setRoot promise was resolved I was also clearing redux store. This made my all current stack screens to re render as were still in memory and redux state updated

**Comment by vdino96** [comment]
@vajid-khan Thank you for the answer, but my issue is not solved by clearing the store. I should note that I am using lazy loading of bottom tabs and the issue comes only if the tab was never rendered. For instance, if I pre-load all 4 tabs that I have, then the issue is not present. If the tab was never rendered, when I call setRoot again, the tab gets called as if the user physically clicked the tab (this is done for all the tabs that were never opened).

**Comment by danilobuerger** [comment]
I just tried this with rnn v7 and the current playground and could not reproduce it, the not-opened tab never gets its render method called when calling setRoot again. Please check with rnn v7. If you are still seeing the issue, please provide a minimal reproducible iOS example.

**Comment by vdino96** [comment]
@danilobuerger  thank you, the issue has been resolved in v7. With that said, this issue can be close.
