### ISSUE TITLE
Navigation.mergeOptions is not updating topBar rightButtons on iOS

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#6493]
### Issue Description

In some screen, I update the right buttons based on some props read from the redux store. For such screens, since I can't set the top bar right buttons statically, I update them during render using `Navigation.mergeOptions`. After updating from `6.8.0` to `6.12.0`, the top bar right buttons are not set after the call to `Navigation.mergeOptions`.

I see a few commits w.r.t. `mergeOptions` API recently. Probably one of them is causing the issue.

**The issue is only occurring on iOS**. On Android, the right buttons are updated okay.

### Steps to Reproduce / Code Snippets / Screenshots

1. Clone repo https://github.com/varungupta85/RNNIssues
2. Install the app on iOS
3. Tap on "Merge Options Screen"
4. Observe that there are no right buttons
5. Replace the contents of MergeOptionsScreen.js with below:

```js
import React, { Component } from 'react'
import { View, Text } from 'react-native'
import { Navigation } from 'react-native-navigation'

class MergeOptionsScreen extends Component {
  constructor(props) {
    super(props)
    Navigation.events().bindComponent(this)
  }

  navigationButtonPressed = ({ buttonId }) => {
    if (buttonId === 'saveMembers') {
      alert('saveMembers')
    }
    if (buttonId === 'cancel') {
      Navigation.pop(this.props.componentId)
    }
    if (buttonId === 'search') {
      alert('search')
    }
  }

  render() {
    setTimeout(
      () =>
        Navigation.mergeOptions(this.props.componentId, {
          topBar: {
            rightButtons: [
              {
                text: 'Save',
                id: 'saveMembers'
              },
              {
                icon: require('./img/ic_find.png'),
                id: 'search'
              }
            ],
            leftButtons: [
              {
                id: 'cancel',
                icon: require('./img/ic_close.png')
              }
            ]
          }
        }),
      100
    )

    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>{'Merge Options Screen'}</Text>
      </View>
    )
  }
}

export default MergeOptionsScreen
```

6. Tap on Merge Options Screen and observe that both the buttons are seen.

---
### Environment
* React Native Navigation version: 6.12.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by jmhuret** [comment]
I believe you would want to use `componentDidAppear` as opposed to `componentDidMount` if you are going to call merge options. You can find info on that [here](https://wix.github.io/react-native-navigation/api/events/#registercommandcompletedlistener)

You may also want to consider setting the static options instead of calling mergeOptions shown [here](https://wix.github.io/react-native-navigation/docs/functionalComponents/#declaring-static-options)

**Comment by jinshin1013** [comment]
@varungupta85 It is a general rule of thumb not to do anything with side-effects (state mutation, in this case `Navigation.mergeOptions`) in `render` function. It is strange that the `mergeOptions` didn't get called in `componentDidMount` as I was able to set the right button in all lifecycle methods https://github.com/wix/react-native-navigation/issues/6493#issuecomment-678234935.

As @jmhuret suggested, try calling `Navigation.mergeOptions` in `componentDidAppear` to see if it works there. Cheers!

**Comment by varungupta85** [comment]
@jmhuret Thanks for the pointer. Shifting `mergeOptions` to `componentDidAppear` helped.

@jinshin1013 I guess I was just being lazy. I understand that I shouldn't do any state mutation in the render but I guess we should avoid any side-effects in render as you mentioned. Thanks.
