### ISSUE TITLE
Opening drawer over TouchableOpacity unexpectdly triggers onPress

### ISSUE THREAD

**Issue by headlessme** [wix/react-native-navigation#65]
I have a ListView that contains lots of TouchableOpacity views in an app started with `startSingleScreenApp`. I have a drawer set up on the left hand side that can be opened with the standard swipe gesture. However when I start and end the swipe-to-open gesture on a TouchableOpacity item in the main view, the `onPress` action of the TouchableOpacity is triggered (and the drawer is opened).

It seems like the gesture to open the drawer isn't correctly stealing the responder from the TouchableOpacity. Any suggestions how to fix this?

**Comment by headlessme** [comment]
As a workaround, adding the following PanResponder to my main view prevents the TouchableOpacity remaining the responder:

```
this._panResponder = PanResponder.create({
  onStartShouldSetPanResponder: (evt, gestureState) => false,
  onStartShouldSetPanResponderCapture: (evt, gestureState) => false,
  onMoveShouldSetPanResponder: (evt, gestureState) => false,
  onMoveShouldSetPanResponderCapture: function(evt, gestureState) {
    if (gestureState.dx > 10) return true;
    return false;
  }
});
```
with
```
<View  {...this._panResponder.panHandlers}>
...
```
It's a bit hacky and simplistic as it breaks diagonal scrolling motions and probably a bunch of other stuff, so a lower level fix would be better!

**Comment by guyca** [comment]
@headlessme It's a known issue. Unfortunately I don't think anyone from the team here at Wix will have time to look into it any time soon.
