### ISSUE TITLE
Use RNN APIs within External Component

### ISSUE THREAD

**Issue by hunterclarke** [wix/react-native-navigation#6502]
### Issue Description

Let's say I've navigated to an external component via RNN. Is there a way I can call the navigation APIs to push another RNN managed component onto the stack while in the external component? The external component callback is only provided the bridge, which doesn't seem to be enough to call `push` via native code. Does anyone have an idea of how to do this?

TL;DR how do I allow this navigation:
```
React Native Component -> External Component -> React Native Component
```

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: 6.9.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 11 Pro Max Simulator

**Comment by danilobuerger** [comment]
Emit an event from your external component, subscribe to it on the JS side, push a rnn component.
