### ISSUE TITLE
Small Empty Space at bottom after hiding BottomTabs

### ISSUE THREAD

**Issue by ashokkumar88** [wix/react-native-navigation#6503]
### Issue Description

After calling `Navigation.mergetOptions()` to hide `bottomTabs` there is small empty space showing at the bottom of the screen.

### Steps to Reproduce / Code Snippets / Screenshots
1. Start App with `Navigation.setRoot()` with `bottomTabs` in center.
2. In Home screen it is looking fine with `bottomTabs`. When navigating to another screen by hiding the `bottomTabs` it leaves a small empty space at bottom. (image attached)

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: 6.12.0
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): Android. (IOS not tested)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device / Android 10 / Both
![Screenshot_1598249228](https://user-images.githubusercontent.com/11060139/91009906-277ac580-e5ff-11ea-95ef-429fbbd03a13.png)

**Comment by lkwjohn** [comment]
+1 facing the same issue as well, seems like 6.1.0 also have this bug

**Comment by jinshin1013** [comment]
@ashokkumar88 It'd be awesome if you could provide a minimal reproduction on Github for us to have a look. Cheers!

**Comment by lkwjohn** [comment]
@jinshin1013 

React-Native: 0.60.6
RN-navigation:6.1.0 tot 6:12.1 (tested a few versions in V6 series)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/273127/91407240-1d61fc80-e875-11ea-80a4-2384b1a77e5a.gif)

**Comment by ashokkumar88** [comment]
Finally I got the issue. In my case I had a set a default settings for push animation in `Navigation.setDefaultOptions()` which was causing issue. The set was like below:
```
Navigation.setDefaultOptions({
animations:{
push: {    
        content: {
          y:     {
                  from: 1000,
		 to: 0,
		duration:      300,
		interpolation: 'linear',
					},
          alpha: {
              from: 0,
              to: 1,
              duration: 300,             
              interpolation: 'accelerate'
          }
      }
      
        }
}
})
```

I removed the animation settings and it is working fine now.

**Comment by lkwjohn** [comment]
@ashokkumar88 I don't think you should close this, this animation I have it with RN-navigation 2.62 version, and it's working. We should let the team investigate instead

**Comment by ashokkumar88** [comment]
@lkwjohn  have u used a custom animation for Push screen?

**Comment by lkwjohn** [comment]
@ashokkumar88 I think if the "content: {  **y**:     {" is changed to "content: {  **transitionY**:     {" it will resolve the issue.

**Comment by guyca** [comment]
Hey guys, animating the `y` property is wrong in this case as the screen's actual `y` value at the time of animation isn't 0. You'r e basically animating the screen and setting the wrong y value.

As mentioned by @lkwjohn - use `translationY` instead. You can refer to the Playground app for an [example](https://github.com/wix/react-native-navigation/blob/master/playground/src/commons/Options.ts#L69). You probably will want the animation value to be dependent on device screen height as well.
