### ISSUE TITLE
Shared Element Transition does not transform Image correctly

### ISSUE THREAD

**Issue by mrousavy** [wix/react-native-navigation#6505]
### Progress

- [x] iOS (thanks @yogevbd)
- [ ] Android (WIP)

### Issue Description

When using Shared Element Transitions to animate Images between Screens, the animation does not work in the following scenarios:

1. The source image and destination image have different **layout sizes** (aspect ratios), e.g.: source image layout is `400 x 300`, destination image is `440 x 300`.
2. The source image and destination image have different `resizeMode`s.

I've created a repro for this bug in a [branch on my fork](https://github.com/mrousavy/react-native-navigation/commit/c902ea6b01e542328d2ca01e1898f2b7bfd0ec65). This shows the first scenarios, change the resizeMode to `'contain'` to reproduce the second scenario.

### Steps to Reproduce / Code Snippets / Screenshots

1. Create Shared Element Transitions as explained [in the docs](https://wix.github.io/react-native-navigation/docs/style-animations#shared-element-transitions)
2. Give source image a different aspect ratios than the destination image, e.g.:
    ```js
    sourceImage: { 
      width: 400,
      height: 300
    }
    ```
    and destination:
    ```js
    destImage: {
      width: 440,
      height: 300
    }
    ```
3. Animate between them.

#### Demo GIF

<table>
<tr>
<th width="33%"></th>
<th width="33%">iOS</th>
<th width="33%">Android</th>
</tr>
<tr>
<td>Animating between Images with different Aspect Ratios</td>
<td><img alt="aspect ratio bug iOS demo" src="https://user-images.githubusercontent.com/15199031/91046902-85b4a200-e619-11ea-875a-bbcb34d0effd.gif"></td>
<td><img alt="aspect ratio bug android demo" src="https://user-images.githubusercontent.com/12352397/91084923-5cb20280-e655-11ea-97c5-572db0ec9d36.gif"></td>
</tr>
<tr>
<td> Animating between Images with different resizeModes</td>
<td><img alt="resizeMode bug iOS demo" src="https://user-images.githubusercontent.com/15199031/91046986-a8df5180-e619-11ea-93d5-920e0410f26b.gif"></td>
<td><img alt="resizeMode bug android demo" src="https://user-images.githubusercontent.com/15199031/91047457-61a59080-e61a-11ea-9814-b0f68ff442e4.gif"></td>
</tr>
</table>

---
### Environment
* React Native Navigation version: 6.12.0
* React Native version: 0.63.2
* Platform: iOS only
* Device info: Simulator & Device, Debug & Release

**Comment by mrousavy** [comment]
Can confirm that the issue also occurs with `<TextInput>` components of different dimensions and/or font sizes. SETs are becoming more and more brainf*ck...

**Comment by tastyqbit** [comment]
This is still not working properly. Any updates?

**Comment by yogevbd** [comment]
@tastyqbit Are you talking about an image transition with different `resizeMode`? it's still not supported on iOS but we will add it soon.

**Comment by tastyqbit** [comment]
@yogevbd Yes that is what I was asking about, thanks for the update :) Do you have any idea on the timeline? I am just in the process of upgrading a lot of libraries including react-native from 0.59 to 0.63 and RNN from v2 to v7 and maybe I wait instead of redo my workaround I made for v2 if its not too long

**Comment by FawadMahmood** [comment]
In my case shared element only working for IOS, android element just disappear.

**Comment by guyca** [comment]
Closing this issue as the last messages don't provide substantial info to work with. If there are any more issues related to image transformations, we would greatly appreciate if you could open new issues with reproductions and we will look into them ASAP.

**Comment by tastyqbit** [comment]
@guyca Does that mean the "Animating between Images with different resizeModes" issue shown in the demo gifs above is solved?
