### ISSUE TITLE
ScrollViews have weird top spacing which shrinks when the view scales down

### ISSUE THREAD

**Issue by mrousavy** [wix/react-native-navigation#6510]
### Issue Description

ScrollViews have a weird top spacing (margin/padding ?) that shrinks down when the view gets downscaled (e.g. with a drag down to dismiss gesture). The top spacing is exactly off by the height of the statusBar (so `-44` for iPhones with notches), and leads to the following issues:

* Makes it difficult to write scroll animations
* Makes scroll animations behave weirdly (because the initial Y isn't `0`, but rather `-44`)
* Weirdly shrinks to `0` again when the view is being scaled down, a.k.a. being moved away from the statusBar
* Looks really off, since there is a rather big margin at the top of my content 
* Scroll Indicator doesn't start at the top

Here's a screenshot showing that the ScrollView's scroll indicator doesn't begin at the top:

<img src="https://user-images.githubusercontent.com/15199031/91181415-2de56c00-e6e9-11ea-9df0-a72224fcce55.png" width=400>

And here's a GIF demonstrating the shrinking effect of the ScrollView:

![ezgif com-optimize](https://user-images.githubusercontent.com/15199031/91181764-9f251f00-e6e9-11ea-85ad-638078b8b2a4.gif)

> When dragged down completely, the ScrollView's content and it's Scroll Indicator move towards their intended position where they should be.

After a bit of playing around, I noticed that this top spacing exactly represents the height of the status bar. This means, that there must be some wrong calculation going on with the status bar height.

### Steps to Reproduce / Code Snippets / Screenshots

1. Create Navigation Screen/Component
2. Create ScrollView, possibly with content insets (margin or padding in the `contentContainerStyle`) (not sure if that's required, but all my scrollviews are styled like this)
3. (Optional) Add animations that interpolate on scrollY, e.g. absolute positioned header that doesn't move when scrollY < 0
4. Observe weird top spacing (if you added the absolute header animation you can notice that in the scroll Y range of `-44` to `0` the header doesn't move, which, again, is weird behaviour)

---
### Environment
* React Native Navigation version: 7.0.0
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): iOS, haven't tested on Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device, Debug & Release

**Comment by mrousavy** [comment]
After a bit more playing around, I noticed that my HomeScreen's ScrollView starts at a partially scrolled state, so it's already scrolled down by the status bar height (offsetY === 44 on iPhone X), and the user can then scroll up more which adds more spacing to the ScrollView's contentContainer than intended (which I don't want)

I also set my `topBar` and `bottomTabs` to `visible: false` in the PostDetailsScreen (see demo above), but I don't think that has anything to do with that since it's exactly off by the StatusBar's height.

**Comment by yogevbd** [comment]
Passing `contentInsetAdjustmentBehavior="never"` to `ScrollView` solves this.

**Comment by mrousavy** [comment]
To anyone else experiencing this:

1. Set [`contentInsetAdjustmentBehavior`](https://reactnative.dev/docs/scrollview#contentinsetadjustmentbehavior) to `'never'` just like @yogevbd pointed out
2. If your indicator is still a bit off and you have a custom content inset (e.g. to manually render custom header), set it to the content inset's height (in my case that's exactly the absolute positioned header's height) and remove the top safe area inset height (status bar height), because that's being added to the ScrollView by iOS.

Thanks!
