### ISSUE TITLE
Bug in translationY/translationX animations

### ISSUE THREAD

**Issue by gsrendev** [wix/react-native-navigation#6514]
### Issue Description

When using translationY/translationX to pop a screen out the animation does not work properly, especially if you slide down or right. The problem is in VerticalTranslationTransition.m and HorizontalTranslationTransition.m in the ObjectiveC code. The animateWithProgress function should simply be (for horizontal and then similar for vertical):

```objective-c
- (CATransform3D)animateWithProgress:(CGFloat)p {
    CGFloat x = [RNNInterpolator fromFloat:self.from toFloat:self.to precent:p interpolation:self.interpolation];
    return CATransform3DMakeTranslation(x, 0, 0);
}
```

---
### Environment
* React Native Navigation version: 6.12.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): simulator and iPhone 11

**Comment by jinshin1013** [comment]
@gsrendev Thanks for digging into the problem! Would you be able to provide a minimal reproduction on Github for developers to be able to more easily debug the issue? Cheers!

**Comment by mrousavy** [comment]
@gsrendev What do you mean with "does not work properly"? I've noticed that sometimes there is a small spacing at the top of the screen when sliding it up on push, so it doesn't fully go to 0 but stops somewhere before that which then adds an ugly white spacing at the top. (obviously not desireable)
Does that have anything to do with this issue?

**Comment by gsrendev** [comment]
Hi Marc,
I had to reverse the animation for a page - slide in from left to right on push and slide out from right to left on pop.

Here is the push call with the customized animation:

Navigation.push('App', {
  component: {
    name: 'AccountIndex',
    passProps: response.data,
    options: {
      animations: {
        push: {
          content: {
            x: {
              from: 0,
              to: width
            }
          }
        },
        pop: {
          content: {
            alpha: {
              from: 1,
              to: 1
            },
            translationX: {
              from: 0,
              to: -width
            }

          }
        }
      }
    }
  }

Here the width is: 

let {width, height} = Dimensions.get('window');


What doesn’t work is the pop animation, because of the interpolation calculations being off. 
The slide out translation does not visualize, the page just disappears after the animation duration expires.

The pop call is very simple, in another page, tied to a custom back button: 

Navigation.pop(this.props.pageId);

Both, translationX and translationY have the same problem.

In HorizontalTranslationTransition.m the original code is:

- (CATransform3D)animateWithProgress:(CGFloat)p {
    CGFloat x = [RNNInterpolator fromFloat:self.from + self.to toFloat:self.to precent:p interpolation:self.interpolation];
    return CATransform3DMakeTranslation(x - self.to, 0, 0);
} 
 
I had to clean it up as follows to get it to work:

- (CATransform3D)animateWithProgress:(CGFloat)p {
    CGFloat x = [RNNInterpolator fromFloat:self.from toFloat:self.to precent:p interpolation:self.interpolation];
    return CATransform3DMakeTranslation(x, 0, 0);
}

The same thing for the vertical translation.

Hope this helps.

Best Regards,
Georgi

**Comment by mrousavy** [comment]
@gsrendev please format your code using backticks (`)

**Comment by mrousavy** [comment]
Can confirm that this bug only occurs on iOS.

<table>
<tr>
<th>iOS</th>
<th>Android</th>
</tr>
<tr>
<td width="50%"><img src="https://user-images.githubusercontent.com/15199031/91895077-edf92880-ec96-11ea-8b86-84cee99f0fe8.gif"></td>
<td width="50%"><img src="https://user-images.githubusercontent.com/15199031/91895031-db7eef00-ec96-11ea-95b1-1f94dc194d28.gif"></td>
</tr>
</table>


On iOS, only the opacity animation works. On Android, both translateY and opacity animations work.
