### ISSUE TITLE
No able to push screen from overlay screen

### ISSUE THREAD

**Issue by rahutwr33** [wix/react-native-navigation#6515]
Not able to push screen from overlay.i am using overlay screen for a search.not able to push screen when click on search result

### Environment
* React Native Navigation version: ^6.7.5
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?):  MAC OS CATLINA

**Comment by jinshin1013** [comment]
Hi @rahutwr33, it seems like you may have not initiated the Overlay screen with a [stack layout](https://wix.github.io/react-native-navigation/docs/stack#layout-examples). Let us know if the problem persists, if you could also provide a minimal reproduction, that'd be awesome as well 👍

**Comment by rahutwr33** [comment]
@jinshin1013  yes it is solved now.Thanks for help.
