### ISSUE TITLE
Automatic content insets for ScrollViews

### ISSUE THREAD

**Issue by JosephDuffy** [wix/react-native-navigation#653]
### Issue Description

When using the default project setup (as described in this repo) and using React Native's `ScrollView` with the `automaticallyAdjustContentInsets` property set to `true` (the default) and the following styles on the navigator:

```
{
  navBarTranslucent: true,
  drawUnderNavBar: true,
}
```

The scroll view's content is rendered behind the navigation, rather than below it. This might be a problem with `ScrollView`, but I'm still new to React Native some I'm not 100% sure!

### Steps to Reproduce / Code Snippets / Screenshots

Code:

`index.io.js`

```
import { Navigation } from 'react-native-navigation';
import { registerScreens } from './app/config/screens';

registerScreens();

const navigatorStyle = {
  navBarTranslucent: true,
  drawUnderNavBar: true,
};

Navigation.startTabBasedApp({
  tabs: [
    {
      title: 'Add',
      screen: 'namespace.Add',
      label: 'Add',
      navigatorStyle: navigatorStyle
    },
    {
      title: 'History',
      screen: 'namespace.History',
      label: 'History',
      navigatorStyle: navigatorStyle
    },
  ]
});
```

`Add/index.js`

```
render() {
    return (
      <ScrollView
        keyboardShouldPersistTaps={true}
        keyboardDismissMode="interactive"
        automaticallyAdjustContentInsets={true}
      >
        <...>
      </ScrollView>
    )
}
```

**How it should look**

![simulator screen shot 9 jan 2017 09 56 50](https://cloud.githubusercontent.com/assets/1325813/21762733/4c63006c-d652-11e6-858a-58a257386192.png)

**How it looks**

![simulator screen shot 9 jan 2017 09 56 42](https://cloud.githubusercontent.com/assets/1325813/21762744/5742533e-d652-11e6-99fc-26ae322c300f.png)

---
### Environment
* React Native Navigation version: 2.0.0-experimental.160
* React Native version: 0.39.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iOS 10, Debug

**Comment by jodm** [comment]
+1

**Comment by MiyoAlpizar** [comment]
Have anyone found a solution for this? =(

**Comment by toadums** [comment]
I found this same issue, and even setting `contentInset={{ top: 64 }}` renders like in your example initially, but once you drag the scrollview it fixes itself.

**Comment by samosaboy** [comment]
Any update on this? I'm experiencing this as well.

**Comment by Kosai106** [comment]
Guys, just take an extra look at the navigatorStyle and *really* look at the name of those values.

``js
{
  navBarTranslucent: true,
  drawUnderNavBar: true,
}
``

These styles indicate that you actually want stuff under the NavBar, but in this case you don't, so flip those booleans to false.

**Comment by samosaboy** [comment]
You should _really_ read the original post and see what native iOS > 7 apps have. There is a way to offset the content under the navbar while maintaining translucency. The effect exists in all native Apple apps and some native iOS apps, which is what we are trying to achieve here.

I think the problem stems from the content offset area is going to the edge of the view controller, so we need to offset it from the navigation controller's height. I managed to offset the view controller in `RCCViewController` but it resorts back to default after you switch tabs or navigate away.

**Comment by LeoNatan** [comment]
This will be fixed in v2.

**Comment by yogevbd** [comment]
Fixed in https://github.com/wix/react-native-navigation/commit/485623074f3bc77bc1cb47c403d9463f4ba3ea4f

In order to enable contentInsetAdjustmentBehavior for iOS 11 you will need to set `autoAdjustScrollViewInsets` in your appStyle:

```
Navigation.startTabBasedApp({
  tabs,
  appStyle: {
    autoAdjustScrollViewInsets: true
  }
});
```
For some reason React native disables this feature by default.
