### ISSUE TITLE
when i update bottom tab badge in  ios the app is freez 

### ISSUE THREAD

**Issue by mohamedanwer123** [wix/react-native-navigation#6531]
Navigation.mergeOptions("NotificationsStack", {
                bottomTab:{
                badge: this.props.unreadNotificationsCount,
                badgeColor:colors.gold,
                text:allStrings.notifications,
                fontFamily:this.props.isRTL?arabicFont:englishFont
                }
});

RN v 0:63
RNN v 6.8.0

**Comment by jinshin1013** [comment]
Hi @mohamedanwer123 I could not reproduce this issue on the Playground app. Would you be able to create a minimal reproduction on Github for us to have a look?

**Comment by jinshin1013** [comment]
Closing for now. Feel free to comment back any time :)

**Comment by RichardLindhout** [comment]
I do have the same problem right now

**Comment by RichardLindhout** [comment]
It's because you can't send a number you have to send in a string on iOS!

**Comment by RichardLindhout** [comment]
``` 

mergeOptions({
      bottomTab: {
        badge: cartAmount === 0 ? '' : `${cartAmount}`,
      },
    })

```
