### ISSUE TITLE
topBar/bottomTabs/statusBar abruptly unmounting when using custom push animations, causing background flickering

### ISSUE THREAD

**Issue by mrousavy** [wix/react-native-navigation#6543]
### Issue Description

When pushing a screen which doesn't have TopBar, BottomTabs or StatusBar visible to a screen that does, there are short whitescreen/blackscreen flickers visible. This can be seen especially when the push animation is not the default slide, but rather an opacity animation which looks like the screen is going to get overlayed ontop of the parent screen.

Here's a demo:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15199031/92452024-d00f5480-f1bd-11ea-8ea6-061cf7128d7b.gif)

Take a look at the top bar, which goes black as soon as the animation starts. If I change the `layout: { componentBackgroundColor }`, this color changes.

Maybe it would be great so somehow allow screens (and it's special components such as BottomTabs, TopBar and it's Overlays) to stay mounted when a screen pushes. This would probably be a nice step towards https://github.com/wix/react-native-navigation/issues/6391, in case we want to support **screens** which are see-through.

### Steps to Reproduce / Code Snippets / Screenshots

1. Create Screen A which has TopBar `visible: true`
2. Create Screen B which has TopBar `visible: false`
3. Navigate to Screen A
4. Push Screen B with custom animation: `content: { alpha }`

---
### Environment
* React Native Navigation version: 6.12.2
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): iOS, Not yet tested on Android
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by mrousavy** [comment]
Here's another demo, a bit zoomed in to see the `topBar` being unmounted, shortly but abruptly flashing the white app/component background:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15199031/92737383-5fae3200-f37b-11ea-8f39-3890fd3c190d.gif)

**Comment by zabojad** [comment]
Can we reopen this issue? The topbar animations are messy and needs to be fixed. Disabling them does not work on iOS...
