### ISSUE TITLE
setting waitForRender: true causes Navigator.mergeOptions of topBar leftButtons in the constructor/componentDidMount to not work

### ISSUE THREAD

**Issue by ijasm** [wix/react-native-navigation#6550]
### Issue Description

After setting waitForRender: true in Navigation.setDefaultOptions, setting of topBar leftButtons in Navigator.mergeOptions no longer works when called within constructor or componentDidMount.

### Steps to Reproduce / Code Snippets / Screenshots

1. Set waitForRender: true in Navigation.setDefaultOptions
```js
Navigation.setDefaultOptions({
	layout: {
		orientation: ["portrait"],
		backgroundColor: NavBarStyle.screenBackgroundColor,
	},
	...options,
	sideMenu: {
		openGestureMode: "bezel",
	},
	statusBar: {
		// android 8 and below default style is light and it does not work well with changing thestyle
		style: DeviceInfoUtil.isAndroid8Below ? "light" : "dark",
		backgroundColor: DeviceInfoUtil.isAndroid8Below ? "black" : NavBarStyle.statusBarColor,
		// style: DeviceInfoUtil.isAndroid10 ? NavBarStyle.statusBarTextColorScheme : null,
	},
	animations: {
		setRoot: {
			waitForRender: true,
		},
		showModal: {
			waitForRender: true,
		},
		push: {
			waitForRender: true,
		},
	},
});
```

2. Set topBar leftButtons in Navigator.mergeOptions within componentDidMount or constructor
```js
public componentDidMount() {
	Navigation.mergeOptions(this.props.componentId, {
		topBar: {
			leftButtons: [
				{
					id: "done_btn",
					text: "Done",
				}
			],
		},
	});
}
```
---
### Environment
* React Native Navigation version: 6.11.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 11 Simulator OS 13.7 Debug

**Comment by jinshin1013** [comment]
Hi @ijasm 🙌, thanks for reporting the issue! You are indeed right about `mergeOptions` not being applied when it gets called in `componentDidMount` on a pushed screen when `push.waitForRender: true` is set.

There are two solutions to work around the issue:

### Use options()
You can define your `leftButtons` in the `static options()`. This approach will look the smoothest as it will transition nicely.

```tsx
// Component.tsx
import React from 'react'
import { NavigationComponent } from 'react-native-navigation'

class Component extends ReactNavigationComponent {
  static options() {
    return {
      topBar: { leftButtons: [{ ...defineLeftButtonHere }] }
    }
  }
  
  // If you need to access props.
  static options(props) {
    return {
      topBar: { 
        leftButtons: [
          { text: props.showApple ? "🍎" : "🍐" }
        ] 
      }
    }
  }
}
```

### Use componentDidAppear
You can also use `componentDidAppear` to call `mergeOptions`. All you need to do is simply replace `componentDidMount` with `componentDidAppear` however keep in mind that the appearance of the left button will slightly be delayed the `componentDidAppear` event will get emitted once the screen is "shown" to the user.
