### ISSUE TITLE
Compatibility with React Native 0.40?

### ISSUE THREAD

**Issue by pjb3** [wix/react-native-navigation#656]
When I tried to upgrade to React Native 0.40, I get a lot of compilation errors, I assume due to the iOS native headers being moved as described here: https://github.com/facebook/react-native/releases/tag/v0.40.0

Are there plans to make a release that addresses this problem?

**Comment by MichielDeMey** [comment]
I too tried to use this project yesterday (2.0.0-experimental) in my 0.40 app and it failed compilation.

**Comment by christiangenco** [comment]
Should be a simple find and replace:

> Native code on iOS must refer to headers out of the react namespace. Previously the following would work:
> 
>      #import "RCTUtils.h"
> 
> But now all headers have been moved:
> 
>      #import <React/RCTUtils.h>

**Comment by MichielDeMey** [comment]
I believe a PR is already partly up for this: https://github.com/wix/react-native-navigation/pull/652.

**Comment by chrissm79** [comment]
Stumbled across [this post](https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c#.yfajsgaeg) which explains how to incorporate backwards compatibility
