### ISSUE TITLE
[V7] App is stuck on the Splashscreen when using RCTBridgeDelegate in Swift

### ISSUE THREAD

**Issue by charpeni** [wix/react-native-navigation#6561]
Hello there! 👋 

First of all, congrats on the v7 release! 🎉 👏 

### Issue Description

⚠️ Related to Swift.

The upgrade from `6.12.0` to `7.0.0` isn't working well for us, the app is getting stuck on the Splashscreen.

It seems like the bridge isn't correctly initialized. I can see JavaScript console logs happening in Xcode and the packager, but I can't see those screens in the app.

I created a repro case in the Playground app for an easier debugging session: https://github.com/charpeni/react-native-navigation/tree/swift-v7.0.0.

### Steps to Reproduce / Code Snippets / Screenshots

```diff
import UIKit

@UIApplicationMain
-class AppDelegate: UIResponder, UIApplicationDelegate {
+class AppDelegate: UIResponder, UIApplicationDelegate, RCTBridgeDelegate {
  var window: UIWindow?

  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
-     ReactNativeNavigation.bootstrap(jsCodeLocation, launchOptions: launchOptions)
+     ReactNativeNavigation.bootstrap(with: self, launchOptions: launchOptions)

      return true
    }

+  func sourceURL(for bridge: RCTBridge?) -> URL? {
+    #if DEBUG
+    return RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index", fallbackResource: nil)
+    #else
+    return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
+    #endif
+  }

+  private func extraModules(for bridge: RCTBridge?) -> [RCTBridgeModule?]? {
+    return ReactNativeNavigation.extraModules(for: bridge)
+  }
}
```
<img height="600" src="https://user-images.githubusercontent.com/7189823/92662783-8f9efc00-f2cd-11ea-96e6-34bbbde371ec.png" />

I went back to `6.12.0`, and I tried with `ReactNativeNavigation.bootstrap(jsCodeLocation!, launchOptions: nil, bridgeManagerDelegate: self)` and it's working fine.

Not sure what's wrong with this actual setup? 🤔 It could be something stupid that I'm not aware of in Swift.

@yogevbd @danilobuerger Any thoughts?

---
### Environment
* React Native Navigation version: 7.0.0
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 11 Pro, 13.7, Debug

**Comment by danilobuerger** [comment]
Put a breakpoint inside `extraModules`. Is it getting called?

**Comment by yogevbd** [comment]
The problem is that the bridge delegate isn't exposed to objective-c in this case. Try this:
```objectivec
import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        ReactNativeNavigation.bootstrap(with: RNModuleInitialiser.init(), launchOptions: launchOptions)
        
        return true
    }
}

@objc(RNModuleInitialiser)
final class RNModuleInitialiser: NSObject {}
extension RNModuleInitialiser: RCTBridgeDelegate {
    
    func sourceURL(for bridge: RCTBridge!) -> URL! {
        #if DEBUG
        return RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index", fallbackResource: nil)
        #else
        return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
        #endif
    }
    
    func extraModules(for bridge: RCTBridge!) -> [RCTBridgeModule]! {
        return ReactNativeNavigation.extraModules(for: bridge);
    }
    
}
```

Also, you might need to add `-D DEBUG` flag to your Project Settings > Build Settings > Other Swift flags > Debug configuration

**Comment by charpeni** [comment]
Thanks for sending this @yogevbd, it worked as expected! 🙇‍♂️ 

Do you mind explaining why the bridge delegate isn't exposed to Objective-C and how to know that?

Could we do something within RNN to expose it? Or is this a common Swift thing?
