### ISSUE TITLE
Support different topBar appearances on iOS

### ISSUE THREAD

**Issue by sallar** [wix/react-native-navigation#6565]
### Issue Description

Currently `topBar` configuration on iOS only supports `largeTitle`, but not different appearances. For example, I want to have a large title and a blurred background, but the background should be hidden when large title is visible.

### Steps to Reproduce / Code Snippets / Screenshots

For example:

```js
topBar: {
	largeTitle: {
		visible: true
	},
	drawBehind: true,
	background: {
		translucent: true
	}
}
```

This works, but the large title also has a blurred background when not scrolled down yet. But in many apps and native views on iOS, the behavior is like this:

- When large title is visible, the top bar does not have a background
- As soon as the view is scrolled and large title is converted to a normal title, the blurred background appears.

You can see this behavior in WhatsApp and Settings on iOS. Or for example GitHub app which looks like this:

![IMG_7769](https://user-images.githubusercontent.com/768052/92708965-35e71200-f35f-11ea-9efd-971fbfa31ee0.PNG)

And when scrolled:
![IMG_7770](https://user-images.githubusercontent.com/768052/92708976-38e20280-f35f-11ea-90ec-2019db3487b4.PNG)

Currently, RNN does this:

![image](https://user-images.githubusercontent.com/768052/92710199-4055db80-f360-11ea-8483-edc0211286c9.png)

As you can see, background is visible even when not scrolled.

---
### Environment
* React Native Navigation version: 6.12.2
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by sallar** [comment]
@yogevbd it seems like this is possible with this:

```
navigationBar.standardAppearance = navBarAppearance
navigationBar.scrollEdgeAppearance = navBarAppearance
```

**Comment by yogevbd** [comment]
@sallar that's true. We need to think of the API.. do you have a suggestion?

**Comment by sallar** [comment]
@yogevbd maybe we can use the existing `background` property in the options? Something like `background.appearance.standard` and `background.appearance.scrollEdge` and the values could be enums like `IOSNavbarAperance.Something`. But that's just my idea.. to make it clear what it does.

**Comment by yogevbd** [comment]
I think we can support it without breaking the current API.
```js
topBar: {
  background: {
    color: 'blue',
  },
  scrollEdgeAppearance: {
    background: {
      color: 'red',
    },
  },
}
```

wdyt?

**Comment by sallar** [comment]
That looks good to me. What would it look like with a blurred background? Something similar to iOS settings app

**Comment by yogevbd** [comment]
It would look like that:
```js
topBar: {
  background: {
    color: 'transparent',
  },
  scrollEdgeAppearance: {
    background: {
      translucent: true,
    },
  },
}
```

**Comment by sallar** [comment]
This is exactly what was on my mind! Wish I knew objective-c enough to make it work haha.

**Comment by ArekChr** [comment]
How to reproduce this for react-native-navigation 7.1.0?

**Comment by sallar** [comment]
@ArekChr what do you mean?

**Comment by ArekChr** [comment]
It doesn't work on version 7

**Comment by danilobuerger** [comment]
@ArekChr it doesn't work because this is a feature request. Somebody will have to implement it first.

**Comment by julian-baumann** [comment]
I think this could be related: https://sarunw.com/posts/uinavigationbar-changes-in-ios13/

**Comment by mateioprea** [comment]
I can take this if you want @yogevbd

**Comment by sallar** [comment]
Thanks for implementing this! I will give it a try ASAP
