### ISSUE TITLE
Shared Element Transition crashes when navigating from <Text> to <TextInput>

### ISSUE THREAD

**Issue by mrousavy** [wix/react-native-navigation#6568]
### Issue Description

The Shared Element Transition hard-crashes when trying to transition from a `<Text>` view to a `<TextInput>`.

Xcode error:

```diff
- Thread 1: Exception: "[<RCTMultilineTextInputView 0x7fa12353ccd0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key textStorage."
```

### Steps to Reproduce / Code Snippets / Screenshots

1. Create Screen A with `<Text>` component and set `nativeID`
2. Create Screen B with `<TextInput>` component and set `nativeID`
3. Create Shared Element Transition between those two Screens (and Views)
4. See crash

---
### Environment
* React Native Navigation version: 7.0.0
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): iOS

**Comment by guyca** [comment]
Transitioning from Text to TextInput isn't a valid transition as the two elements are not the same type (while similar in appearance).

Have you tried changing the `<Text>` element to `<TextInput>` and disabling edits so it looks like a `<Text>` element?

**Comment by mrousavy** [comment]
I see, yeah I've tried that but then the transition transforms incorrectly (see that SET image issue) and stretches it to full height. I think there's a lot of edge cases to consider, including borderRadius, backgroundColors, different fontSizes, different numberOfLines, different aspect ratios, etc. which is going to make this a difficult task to do this all natively. But we'll get there.

I'm closing this issue since it's not intended behavior
