### ISSUE TITLE
Android splash screen hangs / gets stuck

### ISSUE THREAD

**Issue by linnett** [wix/react-native-navigation#6569]
### Issue Description

Pretty much exactly the same as this issue here: https://github.com/wix/react-native-navigation/issues/4255
The only difference is I am using ~v3.2.0~ v7.0.0. And apparently this issue was fixed in v2. 
The user gets stuck at the splash screen on Android when using the back button.

### Steps to Reproduce / Code Snippets / Screenshots

* Tap on the app icon to open app
* Without navigating in the app at all, press the Back button
* Tap on the app icon again to boot app. 
* Gets stuck at splash

Note: The user gets stuck on the splash screen sometimes when coming back into the app but 100% consistently when they go into the app after pressing the back button which prompts an exit.

---
### Environment
* React Native Navigation version: 7.0.0
* React Native version: 0.61.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Any Android release/debug

**Comment by danilobuerger** [comment]
RNN is already on Version 7, maybe you should try that first and see if it fixes your problem.

**Comment by danilobuerger** [comment]
Please feel free to reopen the issue if it persists with the current version of RNN.

**Comment by linnett** [comment]
@danilobuerger Upgraded to 7.0.0. Still breaks. Please reopen

**Comment by danilobuerger** [comment]
I just tried this with the playground app on an android device and couldn't reproduce it. Please provide a minimal reproducible example (preferably based on the playground app).
