### ISSUE TITLE
[V7] Custom bundle root

### ISSUE THREAD

**Issue by pontusab** [wix/react-native-navigation#6572]
With the change in V7 to this:
`[ReactNativeNavigation bootstrapWithDelegate:self launchOptions:launchOptions];`'

from this there is no way to support a custom bundle path like this:
```
    NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"packages/mobile/index" fallbackResource:nil];
    [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions bridgeManagerDelegate:self];
  ```

**Comment by snechiporenko** [comment]
Add:
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}
In:
https://github.com/wix/react-native-navigation/blob/master/playground/ios/playground/AppDelegate.m

**Comment by danilobuerger** [comment]
@pontusab as @snechiporenko pointed out, implement the `RCTBridgeDelegate`.
