### ISSUE TITLE
How to integrate with the newest Microsoft Code Push?

### ISSUE THREAD

**Issue by UtillYou** [wix/react-native-navigation#6574]
### Issue Description

The code push documents only recorded the version 2 of RNN. So how to integrate with the newest version 7?

---
### Environment
* React Native Navigation version: 7
* React Native version: 0.63.0
* Platform(s) (iOS, Android, or both?): Both

**Comment by iuliuvisovan** [comment]
Did you manage to integrate it? For me it works fine on iOS without special setup, but Android doesnt.
