### ISSUE TITLE
Bottomtabs warning visible deprecation

### ISSUE THREAD

**Issue by MakhouT** [wix/react-native-navigation#6584]
### Issue Description
Regarding this [issue](https://github.com/wix/react-native-navigation/issues/6416) 
After upgrading to RNN 7.0 I am getting a warning (as expected) because I still had the `visible` key in my options like this
```js
Navigation.mergeOptions(tabComponentId, {
      bottomTabs: {
        currentTabIndex: 2,
        visible: true,
      },
    });
```

But I am still getting this warning message after removing the `visible` key in my options, my snippet now looks like this:
```js
Navigation.mergeOptions(tabComponentId, {
      bottomTabs: {
        currentTabIndex: 2,
      },
    });
```

### Environment
* React Native Navigation version: 0.63.2
* React Native version: 7.0
* Platform(s) (iOS, Android, or both?): only tried ios
* Device info (Simulator/Device? OS version? Debug/Release?): simulator, debug ios

**Comment by jinshin1013** [comment]
Hi @MakhouT, sorry for the delay in responding 🙏  I have tried to replicate the issue on the Playground app, however no luck. Would you be able to try out the Playground app see if you can reproduce the issue?

Closing this for now, but feel free to comment at any time if the issue persists. Cheers!

```ts
// playground/src/screens/FirstBottomTabScreen.tsx
switchTabByIndex = () => 
    Navigation.mergeOptions(this, {
      bottomTabs: {
        currentTabIndex: 1,
      },
    });
```

![bottom-tabs](https://user-images.githubusercontent.com/17612922/94220558-2ef5fd00-ff24-11ea-814b-138e5365d436.gif)
