### ISSUE TITLE
[iOS] Deprecate searchBar params in favour of a new standalone searchBar option

### ISSUE THREAD

**Issue by mateioprea** [wix/react-native-navigation#6585]
### Issue Description

We were discussing about moving the search bar params on iOS into a new options object. This will replace the old configuration in favour of the following: 

```javascript
options: {
  topBar: {
    searchBar: {
      visible: boolean,
      hideOnScroll: boolean,
      hideTopBarOnFocus: boolean,
      obscuresBackgroundDuringPresentation: boolean,
      backgroundColor: color,
      tintColor: color,
      placeholder: string
    }
  }
}
```

The old config will still work until Wix team considers that they will deprecate it, but a deprecation message will be shown pointing to this issue. 

Collaborators: @danilobuerger / @mrousavy 

More details to follow in the comments after I finish the implementation.

**Comment by mrousavy** [comment]
Have we considered supporting the search bar on Android as well? See: https://developer.android.com/guide/topics/search/search-dialog
