### ISSUE TITLE
mergeOptions topBar title not applying defaultOptions fontFamily on android

### ISSUE THREAD

**Issue by danilobuerger** [wix/react-native-navigation#6588]
### Issue Description

When using `Navigation.mergeOptions` to set a `title` on a screen that previously had no title, the `fontFamily` in `defaultOptions` is not applied.

The cause is most likely in `TitleBar.java`. When no `title` is set, the corresponding `TextView` is not created. Therefor
```java
    public void setTitleTypeface(Typeface typeface) {
        TextView titleTextView = findTitleTextView();
        if (titleTextView != null) titleTextView.setTypeface(typeface);
    }
```
will not set the type face as `titleTextView == null`.

The current workaround is using Options Processor to apply the font family there. 

### Steps to Reproduce / Code Snippets / Screenshots

```ts
Navigation.setDefaultOptions({
  topBar: {
    title: {
      fontFamily: "CustomFont",
    },
  },
});

class SomeScreen extends React.Component {
  public componentDidMount(): void {
      Navigation.mergeOptions(this.props.componentId, {
        topBar: {
          title: {
            text: "Title",
          },
        },
      });
  }
}
```

---
### Environment
* React Native Navigation version: 7.0.0
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by guyca** [comment]
Fixed in 7.1.0 👍
