### ISSUE TITLE
No option to hide the navigation menu button in  android. 

### ISSUE THREAD

**Issue by chirag93** [wix/react-native-navigation#659]
### Issue Description

When I add the navigation by default it gives a menu button on the top left corner but there is no way to hide those button. 

Currently was trying to hide as below even this doesn't work. 
`static navigatorButtons = {
    //This is a dummy button to hide the back navigation
     leftButtons: [{
      title: '', 
        id: 'dummy', 
      disabled:true,
      disableIconTint:true
     }] 
  };`

---
using version  : ^2.0.0-experimental.154

**Comment by SudoPlz** [comment]
I think that's the same as https://github.com/wix/react-native-navigation/issues/621
