### ISSUE TITLE
Document sf symbols usage

### ISSUE THREAD

**Issue by danilobuerger** [wix/react-native-navigation#6594]
### Issue Description

Recently we introduced usage of sf symbols for all `icon` props for ios. This needs to be documented. See https://github.com/wix/react-native-navigation/pull/6576

**Comment by mateioprea** [comment]
@danilobuerger maybe we can close this. if we want the docs maybe cherry pick from #6611 ?

**Comment by danilobuerger** [comment]
@mateioprea Yeah, we should still update the docs. Can you create a new pr with the cherry pick?

**Comment by mateioprea** [comment]
yup

**Comment by mateioprea** [comment]
Done https://github.com/wix/react-native-navigation/pull/6680

**Comment by guyca** [comment]
Yes!! So happy this didn't get left behind 🔥
