### ISSUE TITLE
\node_modules\react-native-navigation\lib\android\app\src\main\java\com\reactnativenavigation\options\ValueAnimationOptions.kt: (20, 36): Unresolved reference: NullFloatParam

### ISSUE THREAD

**Issue by lhb11** [wix/react-native-navigation#6595]
### 
安装之后android运行报错，app\src\main\java\com\reactnativenavigation\options\ValueAnimationOptions.kt: (20, 36): Unresolved reference: NullFloatParam
我已经检查kotlin版本，不知如何处理

### Steps to Reproduce / Code Snippets / Screenshots

---
### Environment
* React Native Navigation version: ^7.0.0
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): Device  Debug

**Comment by jinshin1013** [comment]
HI @lhb11 I can't reproduce this problem. Could you ensure you have followed the installation guide (comparing the Playground app can be helpful 🙂). Going to close the issue for now. Let me know if the issue persists.
