### ISSUE TITLE
fontWeight / fontStyle default options are not applied

### ISSUE THREAD

**Issue by danilobuerger** [wix/react-native-navigation#6597]
### Issue Description

With the recent addition of fontWeight / fontStyle to android (https://github.com/wix/react-native-navigation/pull/6590), I missed to include those in the default options. So they are not being merged in.

### Steps to Reproduce / Code Snippets / Screenshots

```ts
Navigation.setDefaultOptions({
  topBar: {
    title: {
      fontFamily: "Cool Font",
      fontStyle: "italic",
      fontWeight: "bold",
    },
  },
});
```
---
### Environment
* React Native Navigation version: 7.0.0-snapshot.1216
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by guyca** [comment]
Fixed in 7.1.0
