### ISSUE TITLE
Check if Screen is Registered

### ISSUE THREAD

**Issue by indivisable** [wix/react-native-navigation#660]
What is the best way to check if a screen (string) is registered with the navigator?

Is there something like:

```
if(Navigation.isRegistered("app.TestView")){
  ... Push View
}else{
  ... Register View
}

```

Alternatively is their an array that I can check?

**Comment by kyle-ssg** [comment]
Why not register all routes up front ?

**Comment by indivisable** [comment]
We'll typically I do register screens before hand, but still to be able to check the registry would be good to make sure the app does'nt crash when trying to load a view. Also sometimes it may be good to load a view "on demand" to make the system more dynamic.

**Comment by DanielZlotin** [comment]
That's a cool feature suggestion for v2, thanks
