### ISSUE TITLE
BottomTab Style

### ISSUE THREAD

**Issue by KhubaibQaiser** [wix/react-native-navigation#6601]
### Issue Description

How can we style the bottom tabs container? For example if we want to increase the vertical padding and change the top border color?

### Environment
* React Native Navigation version: 6.12.2
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Any

**Comment by Anahita-Fakhravar** [comment]
I have the same problem. How we can give border Radius to bottom tab container?

**Comment by jinshin1013** [comment]
Hi @KhubaibQaiser @Anahita-Fakhravar  🙌  Unfortunately the library does not yet support customising the appearance of the Bottom Tabs. However it'd be super awesome if you could contribute to the project! 

Closing the issue for now. Let us know on Discord if you would like to further discuss about contributing!

**Comment by kabus202** [comment]
@KhubaibQaiser @Anahita-Fakhravar it's supported now...  just use borderColor: '#000'  in options bottomTabs

**Comment by TheHeumanModean** [comment]
2 years late here, but you can add custom amounts of padding around the icons on android by overwriting dimensions defined by the bottom navigation package this library wraps. Simply add a resource file like `dimens.xml` and then you can overwrite all the properties in the following file

https://github.com/aurelhubert/ahbottomnavigation/blob/master/ahbottomnavigation/src/main/res/values/dimens.xml.

There isn't great documentation of what each property does but you can try and figure it out yourself from this file 

https://github.com/aurelhubert/ahbottomnavigation/blob/master/ahbottomnavigation/src/main/java/com/aurelhubert/ahbottomnavigation/AHBottomNavigation.java

For example I wanted more padding to both the top and bottom of my bottom nav bar on android (iOS looked fine) and also remove the animation moving the icon up on select, so I have the following content in the dimens file.

```
<?xml version="1.0" encoding="utf-8"?>
<resources
    xmlns:tools="http://schemas.android.com/tools"
    tools:ignore="MissingDefaultResource"
>
    <dimen name="bottom_navigation_margin_top_active">18dp</dimen>
    <dimen name="bottom_navigation_margin_top_inactive">18dp</dimen>
    <dimen name="bottom_navigation_margin_bottom">18dp</dimen>
    <dimen name="bottom_navigation_height">80dp</dimen>
</resources>
```
