### ISSUE TITLE
Dev menu causing navigation bar to stay on Android

### ISSUE THREAD

**Issue by DavidShefcik** [wix/react-native-navigation#6602]
### Issue Description

When opening the React Native dev menu on Android, if I have the NavigationBar hidden it'll show and then stick without going away.

### Steps to Reproduce / Code Snippets / Screenshots

```
Navigation.setDefaultOptions({
  navigationBar: {
    visible: false,
  },
});
```

### Here is a gif of the behavior. As you can see, the navigation bar stays and becomes the non transparent version indicating it is not going to go back down.
[https://imgur.com/o7n3VPR](https://imgur.com/o7n3VPR)

---
### Environment
* React Native Navigation version: 7.0.0
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android 9 Kernel version 4.4.147

**Comment by jinshin1013** [comment]
Hi @DavidShefcik I cannot reproduce this on the Playground app where there is no custom items in the Dev Menu. Could this be related to the packages you use to add the custom items (if any used)? Could you see if pressing `Toggle Inspector` or other non-custom dev menu still causes the issue?

![android-dev-menu](https://user-images.githubusercontent.com/17612922/94219062-dbce7b00-ff20-11ea-82cc-ab69cd4e65f0.gif)

**Comment by danilobuerger** [comment]
stale
