### ISSUE TITLE
event.componentName no longer provided from registerModalDismissedListener

### ISSUE THREAD

**Issue by hugo-chq** [wix/react-native-navigation#6605]
### Issue Description

Previously registerModalDismissedListener would provide the componentName , but it's now unavailable / undefined.  

registerModalDismissedListener was being used to recognise when returning to the previous screen underneath.  

Is this change intentional? And if so is there a recommended way to get the componentName from the componentId?  
 Thanks

### Steps to Reproduce / Code Snippets / Screenshots

```
// logs 'undefined'
Navigation.events().registerModalDismissedListener((event) => {
  console.log(event.componentName);
})
```

---
### Environment
* React Native Navigation version: 7.0.0
* React Native version: 0.63.2
* Platform: tested on iOS
* Device info: iOS Simulator iPhone 11 iOS 13.7 Debug

**Comment by danilobuerger** [comment]
Whats the content of `event` for you? (`console.log(event)`)

**Comment by jinshin1013** [comment]
It seems like `V7` removed the emitting `componentName` on `ModalDismissed` event [PR here](https://github.com/wix/react-native-navigation/pull/6422/files#diff-e42324e91a1b48834d165e91fc3c9a25R126).

@yogevbd Was this an intentional change? Android is still emitting `componentName`.

**Comment by hugo-chq** [comment]
Hi @danilobuerger sorry for the delay, the event logs `{"componentId": "Stack10", "modalsDismissed": 1}`

**Comment by guyca** [comment]
Hey guys, indeed we've removed `componentName` from the `modalDismissed` event. It should have been removed from Android as well, this is my mistake.

The reason for removing the parameter from the event is because it's not reliable. Modals can contain any type of layout, including a `SideMenu` or a `SplitView`. What's the current component of a SideMenu? Is the the center layout? or the currently opened drawer?

@hugo-chq Can you please describe the use case for which you need the current component?

**Comment by hugo-chq** [comment]
@guyca Hi , yes the current use case is keeping track of the latest active / visible screen.
we use `registerComponentDidAppearListener` to detect the current visible screen, and then 
 'registerModalDismissedListener' to detect returning to a previous screen, as `registerComponentDidAppearListener` doesn't fire when dismissing a modal.

For example in an app with a settings modal.

1. tap `Home Screen` , 
registerComponentDidAppearListener fires, 
state.visibleScreen = componentName ("Home")

2. tap `Settings Modal` icon, 
registerComponentDidAppearListener fires, 
state.previousScreen = state.visibleScreen ("Home" )
state.visibleScreen = componentName ("Settings")

3. tap `Close Settings Modal` icon, revealing the Home screen underneath
registerModalDismissedListener fires, 
state.visibleScreen = state.previousScreen ("Home")


Keeping track of the screen can be used for:  
- blocking screen reader accessibility for non active screens
- analytics for screen opened
- playing animation on screen change
- (side effect) reacting to a screen transition ending

The state is being stored in [zustand](https://github.com/pmndrs/zustand) (redux style state library) so it can subscribed to

**Comment by N3TC4T** [comment]
I don't use any `SplitView` or `SideMenu`, end up with a patch for it

```
diff --git a/node_modules/react-native-navigation/lib/ios/RNNModalManagerEventHandler.m b/node_modules/react-native-navigation/lib/ios/RNNModalManagerEventHandler.m
index 0905cb9..1c4c2f2 100644
--- a/node_modules/react-native-navigation/lib/ios/RNNModalManagerEventHandler.m
+++ b/node_modules/react-native-navigation/lib/ios/RNNModalManagerEventHandler.m
@@ -12,17 +12,17 @@ - (instancetype)initWithEventEmitter:(RNNEventEmitter *)eventEmitter {
 }
 
 - (void)dismissedModal:(UIViewController *)viewController {
-    [_eventEmitter sendModalsDismissedEvent:viewController.topMostViewController.layoutInfo.componentId numberOfModalsDismissed:@(1)];
+    [_eventEmitter sendModalsDismissedEvent:viewController.layoutInfo.componentId numberOfModalsDismissed:@(1)];
 }
 
 - (void)attemptedToDismissModal:(UIViewController *)viewController {
-    [_eventEmitter sendModalAttemptedToDismissEvent:viewController.topMostViewController.layoutInfo.componentId];
+    [_eventEmitter sendModalAttemptedToDismissEvent:viewController.layoutInfo.componentId];
 }
 
 - (void)dismissedMultipleModals:(NSArray *)viewControllers {
     if (viewControllers && viewControllers.count) {
         UIViewController* lastViewController = [viewControllers.lastObject presentedComponentViewController];
-        [_eventEmitter sendModalsDismissedEvent:lastViewController.topMostViewController.layoutInfo.componentId numberOfModalsDismissed:@(viewControllers.count)];
+        [_eventEmitter sendModalsDismissedEvent:lastViewController.layoutInfo.componentId numberOfModalsDismissed:@(viewControllers.count)];
     }
 }
```
