### ISSUE TITLE
on below version android 10.0 showing blank screen after two screens pushed ? in 10.0 working perfect.

### ISSUE THREAD

**Issue by ahmedawais93** [wix/react-native-navigation#6606]
### Issue Description

[ENTER DESCRIPTION HERE]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by jinshin1013** [comment]
HI @ahmedawais93, it'd be awesome if you could add more information regarding the issue and a reproduction. This will help devs to debug and resolve the issue much more easily. Cheers!
