### ISSUE TITLE
topBar flickers when popping screens on IOS12

### ISSUE THREAD

**Issue by zzorba** [wix/react-native-navigation#6608]
### Issue Description

This does not reproduce on IOS13/14, but on IOS12 if the topBar has a non-default background color when using bottom tabs, popping screens causes the topBar to flash in the default color.

### Steps to Reproduce / Code Snippets / Screenshots

Repository with a repro is here: https://github.com/zzorba/RnnHeaderFlicker/tree/master

The steps seem to be

1) Use BottomTabs
2) Use `Navigation.setDefaultOptions` to change `topBar: { background: { color: 'red' } }`
3) Push a screen in one of the tabs, and then pop it.

---
### Environment
* React Native Navigation version: 7.0.0
* React Native version: 0.63.2
* Platform(s): iOS
* Device info: Reproduces on both device and simulator, but seems to only happen on IOS12. I have not tested lower versions of iOS as the simulator is no longer available.

**Comment by reime005** [comment]
@zzorba could you please confirm that this fixed? just use `"react-native-navigation": "https://github.com/reime005/react-native-navigation#86cfd57"`

**Comment by zzorba** [comment]
@reime005, I can confirm this is fixed with the 7.1.0 release (which it looks like has your change merged into it?). 

 I tried to test the commit you linked directly, but received a message along the lines of `However, this package itself specifies a `main` module field that could not be resolved`.

Thank you for the fix, I really appreciate it!

**Comment by reime005** [comment]
@zzorba it is not yet merged. I've tested it with 7.1.0 and for me it is still there

**Comment by zzorba** [comment]
Yeah, not sure why it appeared to have gone away, but you're absolutely correct.  Trying to test the branch again.

**Comment by zzorba** [comment]
Applying your diff manually I can confirm that the fix works as expected, the flicker is gone.

**Comment by zzorba** [comment]
Not stale, this bug still exists on the latest version as far as I can tell.

**Comment by marcshilling** [comment]
Just confirming that this is still an issue on iOS 12 with version 7.5.0 of react-native-navigation

**Comment by marcshilling** [comment]
Not stale - I confirmed this issue is still present on iOS 12 in v7.8.3

**Comment by aliraza-noon** [comment]
this is not stale

**Comment by aliraza-noon** [comment]
this is not stale

**Comment by aliraza-noon** [comment]
this is not stale
