### ISSUE TITLE
When rotate the screen of Android phone, it makes my app to restart, and sometimes throw exception.

### ISSUE THREAD

**Issue by jaggerwang** [wix/react-native-navigation#661]
### Issue Description

My app has a video player page, the restarting is not acceptable. Is there anyway to avoid this?

### Steps to Reproduce / Code Snippets / Screenshots

Simply switch screen from portrait to landscape, or reverse.

### Environment
react-native-navigation: next newest
react-native: 0.39.2 
platform: Android on device, iOS has no problem.

### Screenshot

Sometimes throw the following exception, and make app crash.

![image](https://cloud.githubusercontent.com/assets/1255011/21954267/f054ce02-da86-11e6-9388-bd1aed644685.png)

**Comment by jaggerwang** [comment]
Is there any plan to solve this problem?

**Comment by guyca** [comment]
@jaggerwang Yes. In the mean time, you might want to consider locking your app to portrait only https://github.com/wix/react-native-navigation/issues/349#issuecomment-250973612

**Comment by jaggerwang** [comment]
@guyca , OK. Thanks for your suggestion.

**Comment by shafy** [comment]
+1
