### ISSUE TITLE
Semantic Issue on build with xcode

### ISSUE THREAD

**Issue by outaTiME** [wix/react-native-navigation#662]
### Issue Description

Im getting the following build error, i follow installation steps from:
https://github.com/wix/react-native-navigation/wiki/Installation---iOS#installation---ios

<img width="460" alt="screen shot 2017-01-13 at 7 55 11 pm" src="https://cloud.githubusercontent.com/assets/140472/21948568/d9fc0f60-d9ca-11e6-9dab-b072da4ff1bd.png">

I dont know what it means, thanks !!

---
### Environment
* React Native Navigation version: @next
* React Native version: 0.40.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator with debug

**Comment by outaTiME** [comment]
Same here with stable release of native navigation:

<img width="463" alt="screen shot 2017-01-13 at 10 52 51 pm" src="https://cloud.githubusercontent.com/assets/140472/21951309/5c778ea2-d9e3-11e6-9578-bdbb603fd17d.png">

im doing something wrong? thanks !!!

---
### Environment
* React Native Navigation version: 1.0.30
* React Native version: 0.40.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator with debug

**Comment by outaTiME** [comment]
React-native 0.40 issue related:

https://github.com/facebook/react-native/issues/11725

**Comment by bawn** [comment]
+1

**Comment by csubbum** [comment]
+1
