### ISSUE TITLE
Drawer passProps not passing through. 

### ISSUE THREAD

**Issue by CapitanRedBeard** [wix/react-native-navigation#663]
### Issue Description
According to this [line in the platformSpecificDeprecated.ios.js](https://github.com/wix/react-native-navigation/blob/7540fa7c13f2ba40d3c29f57fca962f698313912/src/deprecated/platformSpecificDeprecated.ios.js#L139) we decide to pass the `navigatorID` to the screen through passProps instead of the passProps property. This results in code like: 
```
     "right": {
         "screen": "drawer",
         "passProps": {...}
     }
```
to not pass down props to my screen `drawer`. What is the proper way to get additional properties into a drawer screen?

### Environment
React Native Navigation version: `^2.0.0-experimental.175`
React Native version: `0.36.0`
Platform(s) (iOS, Android, or both?): `iOS`
Device info (Simulator/Device? OS version? Debug/Release?): `Simulator with debug`

**Comment by peteroid** [comment]
Got the same issue. I found that setting the `passProps` in the params of startSingleScreenApp could pass through to the drawer. My code is like below,

```javascript
Navigation.startSingleScreenApp({
  screen: {
    screen: 'app.main'
  },
  passProps: {
    // could be passed to the drawer
    drawerRight: {
      deviceWidthRatio: 0.85
    }
  },
  drawer: {
    right: {
      screen: 'app.drawer.right'
      // bug: props not passing to the drawer
      // passProps: {
      //   deviceWidthRatio: 0.85
      // }
    }
  }
})
```

### Environment

React Native Navigation version: react-native-navigation@^1.1.193
React Native version: 0.45.0
Platform(s) (iOS, Android, or both?): iOS
Device info (Simulator/Device? OS version? Debug/Release?): Simulator iPhone 6 / iOS 10.0.3 / Debug

**Comment by raunaqss** [comment]
@peteroid absolutely!

I just tried passing the props through the startSingleScreenApp's param like your code shows, and it worked.

**Comment by ogelacinyc** [comment]
same issue here.
Anything I can try to pass the props through only drawer?

**Environment**
react-native: 0.49.3
"react-native-elements": "^0.17.0"

**Comment by 6axter82** [comment]
I am getting the same issue only on iOS. Cannot pass in startTabBasedApp the drawer passProps. everything I pass is undefined. Any suggestions on it?

**Environment**
"react": "16.2.0",
"react-native": "0.53.0",

**Comment by philvasseur** [comment]
Any follow up on this? I can't seem get it to work no matter where I put it. Always get the prop doesn't exist.

**Comment by 6axter82** [comment]
@philvasseur you could try something similar to (the filename is NavigationHelper.js):
```
       static getTabConfig() {
		const tabs = [
			{
				screen: Screens1.name,
				icon: IMAGES.1,
				title: 'blah,
			},
			{
				screen: Screens2.name,
				icon: IMAGES.2,
				title: 'blah2',
			},
                        {
				screen: Screens3.name,
				icon: IMAGES.3,
				title: 'blah3,
			},
			{
				screen: Screens4.name,
				icon: IMAGES.4,
				title: 'blah4',
			}

		];
		return tabs;
	}
	
	static showMainTabView() {
		const tabs = NavigationHelper.getTabConfig();
		const initialTabIndex = 0;

		const config = {
			tabs: tabs,
			tabsStyle: {
				tabBarHidden: true,
				tabBarButtonColor: 'transparent',
				tabBarSelectedButtonColor: 'transparent',
				tabBarBackgroundColor: 'transparent',
				initialTabIndex: initialTabIndex, // start from view iOS !!!
			},
			appStyle: {
				navBarBackgroundColor: 'white',
				navBarTextFontFamily: fonts.navbar.fontFamily,
				navBarTextFontSize: fonts.navbar.fontSize,
				navBarTextColor: fonts.navbar.color,
				orientation: NavigationHelper.orientation,
				tabBarHidden: true,
				initialTabIndex: initialTabIndex, // start from view Android !!!
			},
			drawer: {
				left: {
					screen: Screens.DrawerMenu.name,
					passProps: {
						items: tabs,
					},
					fixedWidth: fixedWidth,
				},
				style: { // ( iOS only )
					drawerShadow: true,
					contentOverlayColor: 'rgba(0,0,0,0.25)',
					shouldStretchDrawer: true,
				},
				type: 'MMDrawer',
				animationType: 'parallax',
				disableOpenGesture: true  // this props  works only on ios
			},
			animationType: 'none',
			passProps: {
				items: NavigationHelper.getTabConfig(), <-------- IMPORTANT!!!
			},
		};
		Navigation.startTabBasedApp(config);
	}
```
