### ISSUE TITLE
Customize bottomTabs

### ISSUE THREAD

**Issue by caiphaav** [wix/react-native-navigation#6642]
@guyca  Please, add possibilities to fully customize bottomTabs component like it realized in react-navigation:

![image](https://user-images.githubusercontent.com/53155258/94989044-62ff9c80-057a-11eb-8723-a3362d66d0f9.png)

**Comment by jinshin1013** [comment]
Hi @caiphaav, appreciate for the suggestion but seems like your request is much similar to https://github.com/wix/react-native-navigation/issues/6384. 

I'm going to close the issue for now as there is no development plan to allow a custom component for the bottom tabs AFAIK (I might be wrong though 😅). Also keep in mind that we always welcome new contributors who could help out improving the project! Cheers!
