### ISSUE TITLE
Planning to move to this project over react-native-router-flux

### ISSUE THREAD

**Issue by robcalcroft** [wix/react-native-navigation#665]
I'm currently using https://github.com/aksonov/react-native-router-flux/ but it feels unstable and the support is dwindling. Also I want something more simple that doesn't use NavigatorExperimental. This project looks like it fits this and the API looks just as extensive as https://github.com/aksonov/react-native-router-flux/. If I migrate should I look to move to 1.x.x or 2.0? Thanks 😄

**Comment by explorigin** [comment]
This project is very much a work in progress. While Wix is awesome to offer this up as open-source, it is incomplete and the Wix guys work on what they need to deliver their product.  Whether it is production-ready depends on your product.

Also consider that if you use React-Native-Push-Notifications, you may need to migrate to [wix/react-native-notifications](https://github.com/wix/react-native-notifications) for some types of notifications to work on Android.

Go with version 2. Version 1 is really out-dated at this point.

**Comment by robcalcroft** [comment]
Cool thanks for the heads up. Struggling to get the example app working so not sure.

**Comment by robcalcroft** [comment]
@guyca thanks for the response 😄  will give it another go and let you know if I need a hand thanks
