### ISSUE TITLE
resetTo -> StartTabBasedApp with navigation

### ISSUE THREAD

**Issue by dillonykyang** [wix/react-native-navigation#666]
### Issue Description

I want the navigation stack to reset to a tab based wrapper (aka, from a splash to tab with animations).
Currently I can only call startTabBasedApp with a sudden screen transition, and resetTo only take a single screen has param.

Any ways I can achieve that?

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.40
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guyca** [comment]
On Android, The call to `startTabBasedApp` is equivalent to  starting a new [Activity](https://developer.android.com/reference/android/app/Activity.html) - which comes with a transition. You can try calling `startTabBasedApp` with `animationType: 'none'` as described in the [doc](https://github.com/wix/react-native-navigation/wiki/Top-Level-API#starttabbasedappparams)
