### ISSUE TITLE
[v7] [iOS] statusBar is disappearing on calling dismissOverlay

### ISSUE THREAD

**Issue by JOHN1202** [wix/react-native-navigation#6661]
### Issue Description

I have bottom tabs with screens and modals, and also with an overlay (as a FAB). when I click to open a modal using showModal, there's a registerComponentDidAppearListener that's controlling when to show / hide the overlay, and when dismissOverlay is called (after the modal is shown with showModal) the modal opens and the overlay is dismissed, but the status bar disappears.

At some point in a handled way, I show the overlay and it's working properly, and on some click event, I show the Modal and it's also working properly. then when the modal is opened the overlay is dismissed. Previously and specifically before V6.12.2 the overlay was dismissing as it should and the status bar is kept visible without any weird behaviors. Now it just disappears on overlay dismissal.

### Steps to Reproduce / Code Snippets / Screenshots

<!-- ```
Navigation.showModal({
  stack: {
    children: [{
      component: {
        name: 'someModal',
        passProps: { text: 'modal to show' },
        options: { topBar: { title: { text: 'someModal' } } }
      }
    }]
  }
})

Navigation.showOverlay({
  component: {
    name: 'someOverlay',
    options: {
      layout: { componentBackgroundColor: 'transparent' },
      overlay: { interceptTouchOutside: false }
    }
  }
});

Navigation.events().registerComponentDidAppearListener(({ componentName }) => {
       if (componentName === 'someModal') {
              Navigation.dismissOverlay('someOverlay')
       }
})
```                                                           -->

---
### Environment
* React Native Navigation version: 7.1.0
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device - iOS 13.6 - Debug & Release

**Comment by jinshin1013** [comment]
@JOHN1202 Could you provide a minimal reproduction on Github please? It'd be extremely helpful for us to debug the issue better.
