### ISSUE TITLE
how to translucent statusbar in Android?

### ISSUE THREAD

**Issue by jehee-choi** [wix/react-native-navigation#6673]
### Issue Description

I want to set StatusBar translucent.
IOS is fine. 
when modal is open(called showModal), 
It only shows grey color status bar when I set statusBar translucent in Android.

### Steps to Reproduce / Code Snippets / Screenshots

 Navigation.mergeOptions(this.props.componentId, {
            statusBar: {
                backgroundColor: "transparent",
                style: "dark",
                translucent: true,
            },
        });

![image](https://user-images.githubusercontent.com/69952081/95931957-783fbb00-0e05-11eb-8cf6-845c4130124e.png)

---
### Environment
* React Native Navigation version: 6.9.1
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device/ Both

**Comment by guyca** [comment]
https://wix.github.io/react-native-navigation/api/options-statusBar#translucent

**Comment by LiangYizhi1024** [comment]
`statusBar: {
      drawBehind:true,
      style:'light',
      backgroundColor:'rgba(0,0,0,0)'
}`

**Comment by mohshbool** [comment]
> `statusBar: { drawBehind:true, style:'light', backgroundColor:'rgba(0,0,0,0)' }`

Where do i add this? Here's my current `App.tsx` code:
```
        <SafeAreaProvider>
          <NavigationContainer>
            <Stack.Navigator
              initialRouteName="Splash"
              screenOptions={{
                headerShown: false,
              }}>
              <Stack.Screen
                name="Splash"
                component={Splash}
                options={{headerShown: false}}
              />
              <Stack.Screen
                name="Home"
                component={Home}
                options={{headerShown: false}}
              />
            </Stack.Navigator>
          </NavigationContainer>
        </SafeAreaProvider>
```
