### ISSUE TITLE
Impossible to install v2 (Pod)

### ISSUE THREAD

**Issue by eightyfive** [wix/react-native-navigation#6682]
## 🐛 Bug Report

I cannot install ReactNativeNavigation Pod using version `^2`. I get the following error message when running `pod update`:
```bash
Installing ReactNativeNavigation 2.29.0 (was 4.8.4)

[!] Error installing ReactNativeNavigation
[!] /usr/bin/git clone https://github.com/wix/react-native-navigation.git /var/folders/k2/8lx78gtj4b33y68kjrr5j01w0000gn/T/d20201018-9599-1ec57vb --template= --single-branch --depth 1 --branch 2.29.0

Cloning into '/var/folders/k2/8lx78gtj4b33y68kjrr5j01w0000gn/T/d20201018-9599-1ec57vb'...
warning: Could not find remote branch 2.29.0 to clone.
fatal: Remote branch 2.29.0 not found in upstream origin
```

Basically:
```bash
fatal: Remote branch 2.29.0 not found in upstream origin
```

## Your Environment

* React Native Navigation version: `2.29.0`
* React Native version: `0.59.9`
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS debug build

**Comment by guyca** [comment]
Hey @eightyfive 👋 
I'm sorry but previous versions are not supported, you're welcome to upgrade to the latest version.

**Comment by eightyfive** [comment]
As I suspected, fair enough, I'm running an oooold version.

My problem is v3 requires AndroidX afaik, but am running RN < 0.60 which does not support AndroidX as far as I know...

Anyway, I will try to upgrade.
