### ISSUE TITLE
Transition animation is transparent on iOS 12

### ISSUE THREAD

**Issue by Rybachello** [wix/react-native-navigation#6687]
## 🐛 Bug Report

Transition animation is transparent on iOS 12.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## To Reproduce

Run app on iOS 12.4 and latest RNN.

## Expected behavior

Background color shouldn't be transparent.

## Actual Behavior

<img width="348" alt="Screen Shot 2020-10-19 at 12 29 21" src="https://user-images.githubusercontent.com/7879621/96431935-e4a72980-120c-11eb-854c-68962d71ac95.png">

## Your Environment

* React Native Navigation version: 7.1.0,
* React Native version: 0.63.3,
* Platform(s) (iOS, Android, or both?): iOS 12.4
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator

**Comment by danilobuerger** [comment]
@Rybachello Please provide a reproducible demo as mentioned in the issue template. Skipping this means that this issue has a very low priority and is likely to get closed in the future.

**Comment by Rybachello** [comment]
Hi, @danilobuerger,
I made a simple demo [here](https://github.com/Rybachello/transitionExample). But it is only on iOS 12. ( I reproduced it on iPhone 8, 12.4 iOS)

**Comment by kanzitelli** [comment]
@Rybachello @danilobuerger hey guys! I have faced the same problem while testing the [app](https://github.com/kanzitelli/rabbit-app) with RNN 7.+ and iOS 12 (iPhone 6 Plus). And I think it's related to [#6721](https://github.com/wix/react-native-navigation/issues/6721). The only thing I could have found is to set `layout.componentBackgroundColor` and `layout.backgroundColor` to your desired color.

**Comment by Rybachello** [comment]
Hi, @kanzitelli 
Yes, I also fixed this by adding `layout.componentBackgroundColor`.
