### ISSUE TITLE
Build issue with example but not example-redux

### ISSUE THREAD

**Issue by jpokrzyk** [wix/react-native-navigation#67]
Thanks for sharing this project! The IOS stuff I've been able to play with is awesome.

If I clone the project and do a npm install and react-native run-android in the example folder I get the following error. The example-redux folder works fine though. Is anyone able to run the example on android from the master branch? 

The build.gradle files are a little different between the two examples. And it looks like the missing pieces would be related to my error below. But even when I even them up it's still not pulling in the lib.

This doesn't seem super complicated to track down. But before I start ripping apart the build stuff I wanted to ask to make sure I wasn't missing something obvious. Thanks. 

```
/Users/jon/github/rn-examples/react-native-navigation/example/android/app/src/main/java/com/example/MainActivity.java:4: error: cannot find symbol
import com.reactnativenavigation.activities.RctActivity;
                                           ^
  symbol:   class RctActivity
  location: package com.reactnativenavigation.activities
/Users/jon/github/rn-examples/react-native-navigation/example/android/app/src/main/java/com/example/MainActivity.java:6: error: cannot find symbol
public class MainActivity extends RctActivity {
                                  ^
  symbol: class RctActivity
/Users/jon/github/rn-examples/react-native-navigation/example/android/app/src/main/java/com/example/MainActivity.java:8: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/jon/github/rn-examples/react-native-navigation/example/android/app/src/main/java/com/example/MainActivity.java:13: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/jon/github/rn-examples/react-native-navigation/example/android/app/src/main/java/com/example/MainActivity.java:15: error: cannot find symbol
        super.onPause();
        ^
  symbol:   variable super
  location: class MainActivity
/Users/jon/github/rn-examples/react-native-navigation/example/android/app/src/main/java/com/example/MainActivity.java:16: error: cannot find symbol
        finish();
        ^
  symbol:   method finish()
  location: class MainActivity
6 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

**Comment by guyca** [comment]
@jpokrzyk example project is broken on Android. This project started out as an iOS project and Android adaptation came later. The Android adaptation is under active develop and we don't have the resources to support both example and example-redux atm.
pull request #61 fixes example project, I hope to merge it soon.

**Comment by jpokrzyk** [comment]
@guyca  Ah thanks for the response! Yea I couldn't tell if it was the build process or the code or what. Just knowing that it isn't working for everyone is very helpful. I'll take a look at the PR.
