### ISSUE TITLE
The demo app in the gif in README - is the source code available?

### ISSUE THREAD

**Issue by longsangstan** [wix/react-native-navigation#670]
Hi,

In the demo app gif I see some very nice features such as image upload, chat, search in navbar...
Just wonder is the source code of that available? Can't find it in example folder.

Thanks.

**Comment by guyca** [comment]
That gif is of the Wix app - source code not available. But we will have a much more complex example/playground project available soon.

**Comment by dongodngtang** [comment]
look forward to

**Comment by guyca** [comment]
@dongodngtang New example app was merged yesterday
