### ISSUE TITLE
 Question: missing field 'params' in CommandCompletedEvent interface (iOS - v7.0.0)

### ISSUE THREAD

**Issue by DonovanDeSmedt** [wix/react-native-navigation#6701]
### Issue description
Since the migration to RNN 7.0 the `CommandCompletedEvent` interface is missing the field `params` on platform **iOS**.
This is not described in the change logs and caused some issues in our projects.

Is this a breaking change and something you guys forgot to mention in the change logs or is this a bug that will be fixed?

## Your Environment

* React Native Navigation version: 7.0.0
* React Native version: 0.63.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by danilobuerger** [comment]
@guyca / @yogevbd do you know the reason why this was removed in v7?

**Comment by guyca** [comment]
Hey @DonovanDeSmedt 👋 
This is indeed a breaking change in 7.0.0 which got left out of the release notes. Sorry about that.

If you could tell us a bit about your use case and what you used the `params` object for, perhaps we could assist you in finding a different solution to your requirement.

**Comment by DonovanDeSmedt** [comment]
Hey @guyca 

No problem, it's just something minor! I'll update it in a PR.

In some scenarios we had an issue in our iOS app where a screen could be pushed multiple times to the stack (especially when a user rapidly clicked multiple times on the button that triggers the push screen). 

To prevent this from happening, I had implemented a simple check that attaches the screenId that is being pushed to a variable. If this variable contains the same screenId as the screen that wants to be pushed (read: same screen will be pushed multiple times when clicking rapidly on the button), the push screen will be prevented. When the push screen event completes, I reset this variable. This is done by using the `registerCommandCompletedListener`, where I check if the current value of that variable equals the `componentId` that is passed in the `params` property of the `CommandCompletedEvent`.

Any idea how this might be prevented by another solution?

Here I perform the check whether or not I need to push the screen (only required on iOS)
```javascript
if (Platform.OS === 'android' || !mountingScreen) {
    mountingScreen = componentId;
    Navigation.push(componentId, {
      component: {
        id: pushTo,
        name: pushTo,
        passProps: {
          ...props,
        },
        options: componentOptions,
      },
    });
  }
```

Here I reset the variable when the push screen event is completed
```javascript
let mountingScreen = '';
Navigation.events().registerCommandCompletedListener((commandCompletedEvent) => {    
    const { commandName, params = {}} = commandCompletedEvent as any;
    const { componentId } = params;
    if (commandName === 'push' && mountingScreen === componentId) {
      mountingScreen = '';
    }
  },
);
```

**Comment by danilobuerger** [comment]
This relates to #3110. It would really be nice to have a general way to handle this.

**Comment by guyca** [comment]
@DonovanDeSmedt Interesting approach! You can set a `commandListener` (in addition to the `commandCompleted` listener) and track `commandId` to `componentId`. Then when a command completes you could correlate the commandId to the componentId.

**Comment by guyca** [comment]
Closing this one for now as I believe we addressed the issue in the discussion above. If there's a use case when can't be solved with the existing API's in an easy enough manner please describe it here or in a new issue.

**Comment by DonovanDeSmedt** [comment]
@guyca Thanks for the suggestion! Haven’t found time to test it out yet but it sure looks promising!
