### ISSUE TITLE
showSlidingOverlay does not display a message.

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#672]
Hey there,

I'm using 

```
this.props.navigator.showInAppNotification({
   screen: 'NOTIFICATION',
   passProps: { 
             message: 'My Message',
             btnTextColor: 'red',
             textColor: 'white',
             bgColor: 'blue',
             heightPercentage: 0.25,
             highlightBgColor: 'green',
   },
   animation: Animation.NOTIFICATION_SWING,
   position: 'top',  // or bottom
   autoDismissTimerSec: 10,
   dismissWithSwipe: true,
});
```

and it works fine on iOS. I can see a swinging notification and the text on it.

On Android though, I don't get any property coming from `passProps`.

Any ideas why?

[Here's my Notification component](https://gist.github.com/SudoPlz/0f3cac0d46d9c370c55d53f319c85ea0).

Thank you!

**Comment by d4vidi** [comment]
Hi @SudoPlz, very sorry but on Android this feature is a WIP... none of those things are currently supported.

**Comment by SudoPlz** [comment]
Ah, I see.. Let me know when it's shipped, I really like this!
:)

Thank you

**Comment by SudoPlz** [comment]
Closing because that's the same as https://github.com/wix/react-native-navigation/issues/672

**Comment by grundmanise** [comment]
@SudoPlz It is not the same.. #635 is for the issue on the iOS :)

**Comment by SudoPlz** [comment]
Cool cool. Re-opened..!

**Comment by lfabreges** [comment]
I don't know if it is related or not, but on Android, when using showInAppNotification in a modal, the notification is actually hidden by the modal. If I immediately dismiss the modal, then I can see the notification on the main screen.

**Comment by guyca** [comment]
@lfabreges should be fixed in .247

**Comment by alexsmartens** [comment]
I have similar problem as @lfabreges does. My showInAppNotification is displayed under showLightBox  Can anyone help?
(react-native-navigation: 1.1.376, tested on Android)
