### ISSUE TITLE
Black Screen rendering on IOS 12 with RNN 7.x

### ISSUE THREAD

**Issue by juddey** [wix/react-native-navigation#6721]
## To Reproduce
1. RNN installed at 6.12.2
1. Upgrade to 7.1.0
1. Run on IOS 6 device using ios 12 in either debug or release mode 

## Expected behavior
I'd keep the white background saw prior to the upgrade

## Actual Behavior
A dark black background presents in multiple screens Example screen:

![AB80D77E-7225-4C65-9757-F3543038DBBD](https://user-images.githubusercontent.com/7445602/97376118-6e4bab00-1921-11eb-82b8-5f39486d629b.png)

If I rollback to 6.12.2 the black screen reverts to white background (which is as expected)

* React Native Navigation version: 7.1, 7.2
* React Native version: 63.2
* Platform(s) (iOS, Android, or both?): IOS
* Device info: Device, Debug and Release, IOS 12
## Reproducible Demo

Happy to provide a repro if you think that this is not just a configuration issue, or just something strange with old hardware.

**Comment by jinshin1013** [comment]
Could you try setting [layout.componentBackgroundColor](https://wix.github.io/react-native-navigation/api/options-layout#componentbackgroundcolor) to white in your default options or screens?

**Comment by juddey** [comment]
Thanks, I shall try this and report back findings.

**Comment by juddey** [comment]
No luck with either of those settings. Pasted code below in case I have not understood where in the options hash I should put the layout key.

```
const warmer = {
  root: {
    stack: {
      children: [
        {
          component: {
            name: 'chapel.startup',
            options: {
              topBar: { visible: false }
            }
          }
        }
      ]
    },
    options: {
      layout: {
        backgroundColor: Colors.white,
        componentBackgroundColor: Colors.white
      }
    }
  }
}
```

**Comment by guyca** [comment]
Hey @juddey 👋 
That should have worked, have you tried specifying these in default options? Also, I would try only specifying `componentBackgroundColor`.

**Comment by juddey** [comment]
hey thanks @guyca, that fixed the issue. I'll close this out now.

**Comment by guyca** [comment]
@juddey Alternatively you can set background color directly on the components in JSX.
