### ISSUE TITLE
ModalDismissedListener got wrong componentId value

### ISSUE THREAD

**Issue by vovka-s** [wix/react-native-navigation#6722]
## 🐛 Bug Report

ModalDismissedListener got wrong componentId

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

yes

## To Reproduce

1. Create any modal screen with the custom id, ex. `SetingsWindow_8`
2. Create the modal dismissed listener via `registerModalDismissedListener`
3. Close the modal screen via `dismissModal`
4. Set breakpoints to modal dissmissed listener and dismissModal.then functions
5. See that `componentId !== 'SetingsWindow_9'`. Actual value is `StackXX`, ex. `Stack17`

![Screenshot from 2020-10-28 15-57-45](https://user-images.githubusercontent.com/9987233/97440901-25075580-1939-11eb-980f-48dcad6ecad7.png)
![Screenshot from 2020-10-28 15-58-14](https://user-images.githubusercontent.com/9987233/97440906-26d11900-1939-11eb-97db-1f6d350a06ca.png)
![Screenshot from 2020-10-28 15-58-32](https://user-images.githubusercontent.com/9987233/97440915-28024600-1939-11eb-8801-55367d657aed.png)

## Expected behavior

`componentId === 'SetingsWindow_9'` both in listener and then function

## Actual Behavior

`componentId === 'StackXX'` both in listener and then function

## Your Environment

* React Native Navigation version: 7.2.0
* React Native version: 0.63.2
* Platform(s): Android (iOS not tested)
* Device info: All available devices and simulators, debug and release (Mi 9 SE, Mi max 2, Galaxy S7, S20)

**Comment by danilobuerger** [comment]
Thats not a bug. If your component is in a stack, the id of the stack will be returned.

**Comment by vovka-s** [comment]
> Thats not a bug. If your component is in a stack, the id of the stack will be returned.

Exactly? If so you need to correct docs for `registermodaldismissedlistener`:
https://wix.github.io/react-native-navigation/api/events#registermodaldismissedlistener
ComponentId should be returned by it
Moreover, I am pretty sure it returned on 6.6.0 and before

**Comment by danilobuerger** [comment]
If the most outer component of your modal is a stack, then the component id of the stack is returned. There is nothing wrong with the docs.

**Comment by vovka-s** [comment]
I think I got it. Thanks!
