### ISSUE TITLE
How to set initialProperties in RCTRootView?

### ISSUE THREAD

**Issue by ryzhak** [wix/react-native-navigation#6727]
Hi!

I want to pass properties from native ios code to react native.

Here is the guide https://reactnative.dev/docs/communication-ios#passing-properties-from-native-to-react-native which states that you should use `initialProperties` in `RCTRootView`

Here is how I start the ios app with react native navigation (7.1):
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    self.launchOptions = launchOptions;
    [ReactNativeNavigation bootstrapWithDelegate:self launchOptions:launchOptions];  
    return YES;
}
```

So how can I set `initialProperties` of the `RCTRootView` with `ReactNativeNavigation` ?

Thanks in advance

**Comment by danilobuerger** [comment]
@ryzhak This is currently not supported by rnn as rnn uses one `RCTRootView` per screen (compared to one per app). If you think this would be a good enhancement, please open a feature request with the filled out issue templated (pitch, motivation, etc).

**Comment by guyca** [comment]
@ryzhak In this case you can implement a simple mechanism that sets props from JS.

This involves:
1. Pass the props from native to JS with a simple event
2. Handle the event in JS and either call `Navigation.updateProps` on a specific component, or on all mounted components. This will trigger `shouldComponentUpdate` on every component.
3. Save the props and inject them into each component via an `OptionsProcessor`

Eventually, we do see RNN supporting brownfield apps. When that day finally arrives, users would be able to update props from native without needing to implement JS wrappers.
