### ISSUE TITLE
Shared Element Transitions: Animating from scaled down state looks jumpy

### ISSUE THREAD

**Issue by mrousavy** [wix/react-native-navigation#6728]
## 🐛 Bug Report

I have a view which the user can drag down to dismiss. When dragging down, the view also gets scaled down to indicate that it is being dismissed. Once it reaches a certain threshold, I dismiss the screen (`dismissModal` atm) which causes the Shared Element Transition to run.

Something similar to my use-case can be found in the playground repo.

Unfortunately, _sometimes_ the Shared Element (animating view, in my case a `<FastImage>`) does not start at it's transformed state (scaled down), but rather shortly goes to original position and only then start animating. When running at normal speed, this looks like a very weird flickering, and is definitely noticeable by users.

> I emphasized _sometimes_, because the bug is not reproducable 100% of the time, but rather happens randomly, I'd say about 1 out of 4 times.

Here is a video demo: https://i.imgur.com/4Fp0GAA.mp4

> If you didn't notice it, try playing it frame by frame (e.g. download & play in QuickTime)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## To Reproduce

I've tried reproducing it in the playground, but couldn't get it to work. Maybe it's because my views are way more complex and therefore it leads to the animation start being delayed by a frame? I've tried debugging this to find out where the initial values are being set incorrectly, but I couldn't understand the whole codeflow, maybe @yogevbd could help here?

## Expected behavior

Shared Element Animation should transition smoothly starting from scaled down state (all transforms applied)

## Actual Behavior

Shared Element Animation _sometimes_ flickers back to original state then starts from scaled down state

## Your Environment

- React Native Navigation version: master (snapshot)
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): iOS

## Reproducible Demo

^ above

## Related Issues

* SET for Modals: #6647
* #6729

**Comment by mrousavy** [comment]
also I'm using SET in Modals, not sure if that has anything to do with the issue.

**Comment by ArekChr** [comment]
+1

**Comment by guyca** [comment]
@mrousavy Does this reproduce in the cars example in the playground app?

**Comment by mrousavy** [comment]
@guyca unfortunately not. I am not sure what exactly is causing it, I can only assume that it is because I have more content in my app, which makes the performance a bit worse than in the simple cars dealer playground and therefore skipping a frame making the first initial frame, where it is not scaled down, visible. 

The car dealer is already code copied 1:1 from my app, so I'm not doing anything else. Hmu on discord if you want access to part of my codebase, that way we'll have a repro

**Comment by ArekChr** [comment]
Same here, my transition is based on car dealer code. One thing I noticed, the problem occurs maybe once in 10 times in the simulator but 9 out of 10 times on a real device.

**Comment by mrousavy** [comment]
Maybe interesting:

<table>
<tr>
<th>Last frame before I call `pop`/`dismissModal`</th>
<th>First frame of Shared Element Transition</th>
<th>Second frame of Shared Element Transition</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/15199031/98529756-4ee84280-227e-11eb-8c47-2bdbe844b849.png"></td>
<td><img src="https://user-images.githubusercontent.com/15199031/98529746-4bed5200-227e-11eb-8110-24abec3c2426.png"></td>
<td><img src="https://user-images.githubusercontent.com/15199031/98529759-50196f80-227e-11eb-9960-0a174e4a1b32.png"></td>
</tr>
</table>

1. My HomeScreen has red background, my PostDetailsScreen has blue background
2. Maybe the `"First frame of Shared Element Transition"` isn't really the first frame, but rather only an initialized state, and the first frame of the actual animation has been skipped? Then that means that somewhere the initial values are initialized without the parent transforms applied. They are only then applied when the actual animation begins
3. In the first frame you can see the image is also visible on the HomeScreen
4. I've sent @yogevbd a repro on discord, but I had to try like 10 times until I got it to reproduce again, on my phone it happens more often. Maybe it's really because of performance/frame skipping?
5. It has nothing to do with interpolation, as this happens with spring as well as linear.

I've stepped through the whole navigation animation logic but unfortunately I couldn't pinpoint where exactly it goes wrong.

**Comment by ArekChr** [comment]
someone working on fixing that?

**Comment by yogevbd** [comment]
@mrousavy I think that when we hijack that view, we reset the view transformation and we shouldn't, can you try to remove [this line](https://github.com/wix/react-native-navigation/blob/e58be648e33c68c4046ddf1a74cfff2c3674c9ee/lib/ios/AnimatedReactView.m#L56) and test again?

@ArekChr I'm currently full time working on the shared element feature.

**Comment by mrousavy** [comment]
You're our hero @yogevbd 🙏 

About the transform reset; I initially also thought this was the problem, tried to remove that line but that didn't change anything :(
