### ISSUE TITLE
Navigation Drawer button not displayed

### ISSUE THREAD

**Issue by palmsnipe** [wix/react-native-navigation#673]
### Issue Description

Since the update #671, I'm not able to show the home button (I have the issue only on Android).

I've tried to comment/uncomment `icon`, but without success.

### Steps to Reproduce

The app is running with `Navigation.startSingleScreenApp()`

```js
navigatorButtons = {
	leftButtons: [
		{
			icon: iconsMap['ios-menu'],
			// icon: Platform.OS === 'ios' ? iconsMap['ios-menu'] : null,
			title: 'Menu',
			id: 'menu'
		}
	]
}
```

---
### Environment
* React Native Navigation version: `2.0.0-experimental.180`
* React Native version: `0.39.2`
* Platform(s) (iOS, Android, or both?): `Android`
* Device info (Simulator/Device? OS version? Debug/Release?): `Simulator API25 Debug`

**Comment by guyca** [comment]
use `id: 'sideMenu'`
