### ISSUE TITLE
IOS 14.0+ Back Button Menu Issues

### ISSUE THREAD

**Issue by TylerNRobertson** [wix/react-native-navigation#6733]
## 🐛 Bug Report

IOS 14+ introduces a menu popup on IOS over topBar back button when you long press the built in back button in topBar.
Currently there seems to be no way to disable or customize this popup so its just a blank rectangle that covers the button. It can be pressed and still navigates back but it's weird for users to see this empty box just appear if they happen to do this.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes I have

## To Reproduce

1. Install RNN to your RN App.
2. Run on IOS 14+ Simulator
3. Enable topBar & backButton, long press the back button & the popup will appear.

## Expected behavior

Expected to be able to disable or modify this feature.

## Actual Behavior

Currently no way to disable or modify it causing a blank popup to appear.

## Your Environment

- React Native Navigation version: 7.2.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): IOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator or Real Device. Any Environment.

**Comment by mrousavy** [comment]
do you mean this menu?
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15199031/98098874-31d2fe80-1e8f-11eb-982e-ecdb01d369ff.gif)

you can "customize" it by setting the `title` prop on your screens

**Comment by TylerNRobertson** [comment]
@mrousavy yeah actually, this helps a lot, I wasn't using the title option since my back buttons had no text but I'll make use of this.

Still would be great to be able to disable this entirely though

**Comment by guyca** [comment]
@TylerNRobertson Can you please add a screenshot of how the menu looks when there's no title?
