### ISSUE TITLE
[v6 -> v7] library not found for -lReactNativeNavigation

### ISSUE THREAD

**Issue by bneigher** [wix/react-native-navigation#6734]
## ❓ Questions and Help
I just updated today from v6 to v7 and I can't build an Archive of my app anymore.  Works fine when running the simulator tho.

I followed the required upgrade steps:

1. package.json
```javascript
- "react-native-navigation": "^6.12.2",
+ "react-native-navigation": "^7.2.0",
```

2. Podfile
```
- platform :ios, '10.0'
+ platform :ios, '11.0'
```

3. AppDelegate.m
```swift
+ - (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge {
+  return [ReactNativeNavigation extraModulesForBridge:bridge];
+ }

- [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];
+ [ReactNativeNavigation bootstrapWithDelegate:self launchOptions:launchOptions];
```

When archiving, here is what I get:

```
ld: warning: directory not found for option '-L/Users/bneigher/Library/Developer/Xcode/DerivedData/Dieta-dpawevnwpycqmeaqmceawnuenbty/Build/Intermediates.noindex/ArchiveIntermediates/Dieta/BuildProductsPath/Release-iphoneos/ReactNativeNavigation'
ld: library not found for -lReactNativeNavigation
```

What I've tried:
pod deintegrate, delete podfile.lock, pod install
rm -rf /Users/bneigher/Library/Developer/Xcode/DerivedData/
XCode: Clean Builds
Manually linking libReactNAtiveNavigation.a in build phases

Any ideas?

**Comment by uragecz** [comment]
I have same problem... when building release version, i get - 
```
can't locate file for: -lReactNativeNavigation
file: -lReactNativeNavigation is not an object file (not allowed in a library)
```

**Comment by bneigher** [comment]
@uragecz I believe for me I managed to get it working.  In addition to setting the Podfile platform minimum sdk version - make sure to set the:
Deployment > iOS Target Deployment to version 11 in Xcode Build Settings:
<img width="659" alt="Screen Shot 2020-11-02 at 3 28 17 PM" src="https://user-images.githubusercontent.com/4627728/97921169-2e6d3500-1d20-11eb-8d33-968b121b32fe.png">

**Comment by firdausious** [comment]
> @uragecz I believe for me I managed to get it working. In addition to setting the Podfile platform minimum sdk version - make sure to set the:
> Deployment > iOS Target Deployment to version 11 in Xcode Build Settings
> <img alt="Screen Shot 2020-11-02 at 3 28 17 PM" width="659" src="https://user-images.githubusercontent.com/4627728/97921542-b4897b80-1d20-11eb-85b9-dab86ef4066d.png">

Wow thanks @bneigher, confirmed and also works with 

```javascript
{
    "react": "17.0.1",
    "react-native": "0.64.0-rc.3",
    "react-native-navigation": "^7.10.0"
}
```

I think this is should be documented on ios manual installation or automated during `npx rnn-link`

**Comment by spiandorelo** [comment]
THANKS!!!! 3 hours trying to archive here.... hahaha
Changing iOS version in Deployment target worked for me, already had changed in podfile but needed to change here too
