### ISSUE TITLE
Mobx : can not update store by use mobx-react-lite from the document

### ISSUE THREAD

**Issue by smiletomyself** [wix/react-native-navigation#6736]
## 📚 Documentation

when I want to use the latest version of react-native-navagation , and I read the document by https://wix.github.io/react-native-navigation/docs/third-party-mobx , but I can not update my "count" by the document , check many times , I still find the reason why the "count" do not update , the details is below:

dependencies:
 "react": "16.13.1",
 "react-native": "0.63.3",
 "mobx": "^6.0.2",
  "mobx-react": "^7.0.0",
  "mobx-react-lite": "^3.0.1",
  "react-native-navigation": "^7.2.0",

ande the code:

``` js
// counter.store.js
import React from 'react';
import { observable, action } from 'mobx';

class CounterStore {
  @observable count = 0;

  @action.bound
  increment() {
    this.count += 1;
  }

  @action.bound
  decrement() {
    this.count -= 1;
  }
}

// Instantiate the counter store.
const counterStore = new CounterStore();
// Create a React Context with the counter store instance.
export const CounterStoreContext = React.createContext(counterStore);
```

```js
// CounterScreen.js
import React from 'react';
import { Button, Text, View } from 'react-native';
import { observer } from 'mobx-react-lite';
import { CounterStoreContext } from './counter.store';

const CounterScreen = observer((props) => {
  const { count, increment, decrement } = React.useContext(CounterStoreContext);

  return (
    <Root>
      <Text>{`Clicked ${count} times!`}</Text>
      <Button title="Increment" onPress={increment} />
      <Button title="Decrement" onPress={decrement} />
      <Button title="Push" onPress={() => Navigation.push(props.componentId, 'CounterScreen')} />
    </Root>
  );
});
module.exports = CounterScreen;
```

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

(Write your answer here.)

**Comment by guyca** [comment]
@jinshin1013 I believe you have the most experience with this 🙏

**Comment by jinshin1013** [comment]
Hi @smiletomyself, yes you are definitely right that those code will not work with the latest `mobx@^6.0.0` as they recently upgraded to v6 which had some breaking changes on how to define stores. Could you try updating the Counter store file to below? This `should` work, if not please 🙏 pardon me, I've typed this up from my phone.

```tsx
// counter.store.js
import React from 'react';
import { makeAutoObservable } from 'mobx';

class CounterStore {
  count = 0;

  constructor() {
    makeAutoObservable(this)
  }

  increment = () => {
    this.count += 1;
  }

  decrement = () => {
    this.count -= 1;
  }
}

// Instantiate the counter store.
const counterStore = new CounterStore();
// Create a React Context with the counter store instance.
export const CounterStoreContext = React.createContext(counterStore);
```

I should've updated the documentation to reflect the latest mobx integration. In the meantime, please refer to mobx's official documentation regarding how to create observable states.

**Comment by jinshin1013** [comment]
Closing the issue now in favour of #6739. @smiletomyself Really appreciate the report and will fix the documentation as soon as possible!

**Comment by smiletomyself** [comment]
> Hi @smiletomyself, yes you are definitely right that those code will not work with the latest `mobx@^6.0.0` as they recently upgraded to v6 which had some breaking changes on how to define stores. Could you try updating the Counter store file to below? This `should` work, if not please 🙏 pardon me, I've typed this up from my phone.
> 
> ```tsx
> // counter.store.js
> import React from 'react';
> import { makeAutoObservable } from 'mobx';
> 
> class CounterStore {
>   count = 0;
> 
>   constructor() {
>     makeAutoObservable(this)
>   }
> 
>   increment = () => {
>     this.count += 1;
>   }
> 
>   decrement = () => {
>     this.count -= 1;
>   }
> }
> 
> // Instantiate the counter store.
> const counterStore = new CounterStore();
> // Create a React Context with the counter store instance.
> export const CounterStoreContext = React.createContext(counterStore);
> ```
> 
> I should've updated the documentation to reflect the latest mobx integration. In the meantime, please refer to mobx's official documentation regarding how to create observable states.


Hi, @jinshin1013 ,  thanks your reply, first of all, I have update my code in store.js by use below:
```js
import { makeAutoObservable, observable, action } from 'mobx';
... ... 
     constructor() {
       makeAutoObservable(this)
     }
... ...
```
but is still can not update the "count" store by use observer from "mobx-react" or "mobx-react-lite" .

 finally, I have pass the issue by the latest resource code, the relative reference path is "react-native-navigation/website/docs/docs/third-party-mobx/counter-store.tsx",  the difference is below:

```js
import { makeObservable, action, observable } from 'mobx';
... ... 
  constructor() {
    makeObservable(this, {
      count: observable,
      increment: action.bound,
      decrement: action.bound
    })
  }
... ...
```

as we know, mobx@6+ have stopped using decorators by default, actually the two way in the constructor function are all correct in mobx@6+'s document, but I don't know why the function of  makeAutoObservable is still useless for update the store, looking forward your more support, 🙏 

Besides, hopping update the document link of https://wix.github.io/react-native-navigation/docs/third-party-mobx .
