### ISSUE TITLE
Ability to change text of cancel button on the iOS search-bar

### ISSUE THREAD

**Issue by julian-baumann** [wix/react-native-navigation#6742]
## 🚀 Feature

I couldn't find any documented way of changing the text of the "Cancel" button that appears when you focus the search-bar on iOS.

![Searchbar](https://user-images.githubusercontent.com/39265507/98133278-acb30e00-1ebd-11eb-951d-7278f46a6653.jpg)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

It is important, because we need the ability to localize it to different languages.

**Comment by mateioprea** [comment]
it's on 

```javascript
topBar: {
	searchBar: {
		tintColor: '#FCD'
	}
}
```

**Comment by julian-baumann** [comment]
But I don't want to change the tintColor. I want to change the text.

**Comment by mateioprea** [comment]
@julian-baumann yeah, sorry. my bad. I've reopened the issue.
