### ISSUE TITLE
Mobx of document

### ISSUE THREAD

**Issue by smiletomyself** [wix/react-native-navigation#6744]
Hi, @jinshin1013 ,  thanks your reply, first of all, I have update my code in store.js by use below:
```js
import { makeAutoObservable, observable, action } from 'mobx';
... ... 
     constructor() {
       makeAutoObservable(this)
     }
... ...
```
but is still can not update the "count" store by use observer from "mobx-react" or "mobx-react-lite" .

 finally, I have pass the issue by the latest resource code, the relative reference path is "react-native-navigation/website/docs/docs/third-party-mobx/counter-store.tsx",  the difference is below:

```js
import { makeObservable, action, observable } from 'mobx';
... ... 
  constructor() {
    makeObservable(this, {
      count: observable,
      increment: action.bound,
      decrement: action.bound
    })
  }
... ...
```

as we know, mobx@6+ have stopped using decorators by default, actually the two way in the constructor function are all correct in mobx@6+'s document, but I don't know why the function of  makeAutoObservable is still useless for update the store, looking forward your more support, 🙏 

Besides, hopping update the document link of https://wix.github.io/react-native-navigation/docs/third-party-mobx .

_Originally posted by @smiletomyself in https://github.com/wix/react-native-navigation/issues/6736#issuecomment-721498347_

**Comment by jinshin1013** [comment]
Hi @smiletomyself, I've updated the documentation https://github.com/wix/react-native-navigation/pull/6740. You can [check it out here](https://wix.github.io/react-native-navigation/next/docs/third-party-mobx). Cheers!
