### ISSUE TITLE
Command event callback not being invoked on popping

### ISSUE THREAD

**Issue by mrousavy** [wix/react-native-navigation#6748]
## 🐛 Bug Report

```ts
  useNavigationCommand(
    useCallback(() => {
      console.debug(`${componentId} on navigation command!`);
      canNavigate.current = false;
    }, [componentId])
  );
  useNavigationCommandComplete(
    useCallback(() => {
      console.debug(`${componentId} on navigation command complete!`);
      canNavigate.current = true;
    }, [componentId])
  );
```

> this uses the react-native-navigation-hooks package

Per [docs](https://wix.github.io/react-native-navigation/api/events/#registercommandcompletedlistener), this command should be called on every command:

> The `commandListener` is called whenever a _Navigation command_ (i.e push, pop, showModal etc) is invoked.

In my case, when pushing from Screen A to Screen B, the order of execution is the following:

1. ✅ First callback is invoked
2. ✅ Navigation animation happens
3. ✅ Second callback is invoked

When popping from Screen B to Screen A though;

1. ✅ First callback is invoked
2. ✅ Navigation animation happens
3. ❌ nothing

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes.

### Platform

* [x] iOS
* [ ] Android (not yet tested!)

**Comment by guyca** [comment]
@mrousavy Are you listening to these commands in screen B?

**Comment by mrousavy** [comment]
@guyca I have listeners on both screens, none of them trigger on pop. 😟

**Comment by guyca** [comment]
@mrousavy I'm unable to reproduce in the Playground app. Please repro as this could be an issue with the hooks library or a timing issue related to component unmount.

**Comment by mrousavy** [comment]
did you try it on iOS? I'll try creating a quick repro later

**Comment by guyca** [comment]
Yup, tried on iOS and a global command listener.
