### ISSUE TITLE
Custom header each screen

### ISSUE THREAD

**Issue by linhtv97** [wix/react-native-navigation#6751]
I want to use each type of header for different screens but it seems when I customize the header in the props option by the screen but it only accepts the header of the first one. Please tell me what to do

![image](https://user-images.githubusercontent.com/48935244/98518430-f7f46480-22a1-11eb-9d8f-a34d5bb87bf5.png)

**Comment by jinshin1013** [comment]
Hi @linhtv97 🙌. Unfortunately you are on a wrong repo haha. This is `react-native-navigation` not `react-navigation` 😎
