### ISSUE TITLE
mergeOptions inside a bottomTabs layout does not work

### ISSUE THREAD

**Issue by Andarius** [wix/react-native-navigation#6756]
## 🐛 Bug Report

Calling `mergeOptions` from a screen inside a bottomTabs layout does not work as expected

## To Reproduce

https://github.com/Andarius/react-native-navigation/tree/mergeIssue

Press "BottomTabs" button on the main page, then "Change right button"

## Expected behavior

A right button should appear when clicking on "Change right button"

## Actual Behavior

No right button is visible when clicking on "Change right button". It appears if: 
1. we click on "Change right button" 
2. we go to to "Tab 2" 
3. we go back to "Tab 1"

## Your Environment

- React Native Navigation version: 7.2
- React Native version: 0.63
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Debug

## Reproducible Demo

https://github.com/Andarius/react-native-navigation/tree/mergeIssue

![video](https://user-images.githubusercontent.com/5070712/98606549-b8e90200-22e7-11eb-8ab6-d43dc29b2e90.gif)

**Comment by guyca** [comment]
@Andarius 
I checked out the `mergeIssue` branch but it seems like the layout screen is different then what's seen in the screen shots you've posted.

![Screenshot_1605106743](https://user-images.githubusercontent.com/12352397/98829478-ea75e080-2441-11eb-9377-f0511e1180ea.png)

**Comment by Andarius** [comment]
@guyca It did not push because of the eslint error. Should be ok now (I added --no-verify)

**Comment by Andarius** [comment]
Hey @guyca , were you able to reproduce with the updated repo ?

**Comment by guyca** [comment]
Hey @Andarius, I haven't gotten back to it yet 😕

**Comment by Andarius** [comment]
@guyca I noticed that in the current latest version of master (7.5.0) the same occurs if on the 1rst page, you click bottom tabs.
The star won't appear, but if you change tab then back it will.



![video](https://user-images.githubusercontent.com/5070712/101063984-c1a1c080-3593-11eb-8c20-bff45281a03c.gif)

**Comment by swabbass** [comment]
@Andarius I tried to reproduce your issue in the current master and it did not reproduce, at least this flow, here is a [branch](https://github.com/wix/react-native-navigation/tree/merge_options_change_topbar) that does the same thing as in your fork.

> I noticed that in the current latest version of master (7.5.0) the same occurs if on the 1rst page, you click bottom tabs.
> The star won't appear, but if you change tab then back it will.
> 
> ![video](https://user-images.githubusercontent.com/5070712/101063984-c1a1c080-3593-11eb-8c20-bff45281a03c.gif)


maybe it's fixed as a side effect of other issues, can you kindly try current master out and approve if it occurs again? does my branch cover all changes done in your fork above as a test?

**Comment by Andarius** [comment]
Hey @swabbass, I'll check that ASAP and let you know !

**Comment by Andarius** [comment]
The issue still exists, the star should appear immediatly
Here is a new repro: https://github.com/Andarius/react-native-navigation/tree/issue/mergeOptionsTopbar

https://user-images.githubusercontent.com/5070712/104207507-a21e7300-5430-11eb-8465-18160a52ba43.mp4

**Comment by swabbass** [comment]
> https://github.com/Andarius/react-native-navigation/tree/issue/mergeOptionsTopbar

I tried your changes on navigation master (not the fork) and I could not reproduce

https://user-images.githubusercontent.com/7227793/104214131-c0d83600-543f-11eb-9dc5-4a86550b2f96.mp4

**Comment by Andarius** [comment]
Interesting you are also experiencing another issue that I have: you have both the left button and the back button visible but you specified `backButton : { visible: false }`.

Are you sure you are on master? I pulled and forked `d1355780b`

**Comment by swabbass** [comment]
thx, i noticed the back button thing, debugging it in the meantime.

I'm up-to-date with master actually I provided a branch from the master above, you can check it out here https://github.com/wix/react-native-navigation/tree/merge_options_change_topbar

**Comment by Andarius** [comment]
Oh my bad, I was not running the emulator on the right branch. Thank you and sorry for making you lose your time.

It also explains why I could not reproduce the back button issue in the playground. Do you want me to open another issue for it ?

**Comment by swabbass** [comment]
It's ok :], yeah I'll be glad to have a new issue about that back button
