### ISSUE TITLE
[v7] [iOS] setRoot error `TypeError: undefined is not an object (evaluating 'componentName.toString')`

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#6760]
## 🐛 Bug Report

I'm having an error at `Navigation.setRoot()` and I do not get  why.

The error: `TypeError: undefined is not an object (evaluating 'componentName.toString')`

It happens only on iOS. Everything is fine on Android.

I don't know what change caused this issue to happen. I was not having this issue until today. I tried and it happens in v6.10.1, v7.2.0 and v7.3.0.

I believe it is surely caused by my code but why only on iOS? If anyone could please give me some hint here...

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## To Reproduce

I do not  know yet how to reproduce it...

I'm having  it  in my project, I'm currently trying to remove everything non essential to isolate what causes the issue.

## Your Environment

- React Native Navigation version: 0.63.3
- React Native version: 7.3.0 (but was happening in 7.2.0 too)
- Platform(s) (iOS, Android, or both?): iOS only, does not happen on Android
- Device info (Simulator/Device? OS version? Debug/Release?): device and simulator

## Reproducible Demo

(Paste the link to an example repo and exact instructions to reproduce the issue.)

**Comment by zabojad** [comment]
Apparently, it happens here:

```js
    processComponent(key, value, options) {
        if (isEqual_1.default(key, 'component')) {
            value.componentId = value.id ? value.id : this.uniqueIdProvider.generate('CustomComponent');
            this.store.ensureClassForName(value.name);
            if (value.passProps) {
                this.store.updateProps(value.componentId, value.passProps);
            }
            options[key].passProps = undefined;
        }
    }
```

in `commands/OptionsProcessor.js`

**Comment by zabojad** [comment]
Found out why this error was happening.

**Comment by simonmitchell** [comment]
@zabojad could you provide any info on what was causing this? Seeing the same issue in my project!

**Comment by zabojad** [comment]
@simonmitchell yes, it usually happens because of navigation options setting. In my case, I was passing options with both a `static options` field in the screen class, and by passing nav options to the nav command. I do not remember the exact details but the merging of those options did not work well and I sorted it out by managing the options merging myself with [`deepmerge`](https://github.com/TehShrike/deepmerge).

Hope it will help you...

**Comment by simonmitchell** [comment]
Thanks for the reply @zabojad, got to the bottom of it in the end! Caused by a rogue `component` key within our custom title component. `component` keys are treated as if they are objects in `processComponent` so just cleared that up and now it's working! Thanks :D
