### ISSUE TITLE
[V7] setRoot never returning (.then not called)

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#6761]
## 🐛 Bug Report

Since today and without knowing the cause of that change, `Navigation.setRoot` is not resolving. I have absolutely no error neither in the XCode logs nor in the js logs.

It does not happen in Android.

I've tried to limit the setRoot content to a single screen without anything: no stack, no side menu but I still have the issue.

I do not know what to do next to debug this. Please give me some hint.

## Your Environment

- React Native Navigation version: 7.3.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): iOS only
- Device info (Simulator/Device? OS version? Debug/Release?): device and simulator, debug and release

## Reproducible Demo

not yet

**Comment by zabojad** [comment]
Debugging the native calls reveals that `RNNBridgeModule.setRoot` is called but `RNNCommandsHandler.setRoot` is never called...

**Comment by danilobuerger** [comment]
Works in the playground app. Please provide a reproducible demo and follow the issue template.

**Comment by zabojad** [comment]
@danilobuerger I'm trying to reproduce it on another project but fails to do so so far...

I have the same project running on RNN V6 which has not this issue. I'm following that track.

Please keep it open a couple of days until I find some more info and hopefully provide a reproducer.

**Comment by zabojad** [comment]
OK I rolled back my project to v6.12.2 + ios 10 as min SDK version and I do not have this issue anymore.

I'll try to reproduce it on the playground app tonight.

**Comment by jinshin1013** [comment]
Minimum iOS required from RNN v7 is 11. Could you see if updating the iOS target to 11 fixes the problem?

**Comment by zabojad** [comment]
I already had min iOS version set at 11 when using the v7.

**Comment by jinshin1013** [comment]
@zabojad Have you resolved the issue? I had a similar experience the other day while upgrading RNN and it turned out I've missed adding this to `AppDelegate.m` file:

```obj-c
- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge {
  return [ReactNativeNavigation extraModulesForBridge:bridge];
}
```

Your problem may be something totally different but just thought to double check.

**Comment by zabojad** [comment]
Hey @jinshin1013! No I did not come back to this issue since 11 days ago. I will try your fix and keep you updated in this ticket about the results.

**Comment by jinshin1013** [comment]
@zabojad I'm going to close this as it has been stale for quite some time. Let's reopen this once we have more info 👋

**Comment by zabojad** [comment]
@jinshin1013 a bit late but better now than never, your suggestion solved my issue. Now I have other problems like pushing a page to a stack id that is broken... I'm investigating. Thanks again for your help!
