### ISSUE TITLE
initialNotification fired again on calling Navigation.setRoot

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#6764]
## 🐛 Bug Report

I support light and dark themes for my app. I call `Navigation.setRoot` when user changes the app theme to start using the new theme colors. If the app was previously started using a notification (this fires `initialNotification` event), then the `initialNotification` event is fired again after calling `Navigation.setRoot`.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## To Reproduce

1. Schedule a local notification for the app
2. Stop the app from the Recent Apps
3. Tap on the notification to start the app
4. Handle the `initialNotification` event to display an alert
4. Call `Navigation.setRoot`and observe that the alert is displayed again

## Expected behavior

The `initialNotification` shouldn't be fired again.

## Actual Behavior

The `initialNotification` event is fired again causing the app to run the initial notification event handler.

## Your Environment

- React Native Navigation version: 6.12.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): iOS and Android
- Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by jinshin1013** [comment]
@varungupta85 Could you please more information on the issue you are experiencing? What is `initialNotification`? Where are you putting this event handler that is firing again? Can you provide a minimal reproduction of this, preferably without introducing any 3rd party dependencies (you could just use `console.log` for example to mimic the event handler running again)?

**Comment by jinshin1013** [comment]
Stale issue.
