### ISSUE TITLE
initialNotification fired again when app is stopped using the back button on Android

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#6765]
## 🐛 Bug Report

If the app was previously started using a notification (this fires `initialNotification` event), then if the user taps on the back button to put the app in the background which technically also stops the app and start the app again at a later time from the "Recent Apps", the `initialNotification` event is fired again

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## To Reproduce

1. Schedule a local notification for the app
2. Stop the app from the Recent Apps
3. Tap on the notification to start the app
4. Handle the `initialNotification` event to display an alert
5. Tap on the hardware back button to stop the app
6. Tap on the "Recent Apps" button
7. Start the app again

## Expected behavior

The `initialNotification` shouldn't be fired again.

## Actual Behavior

The `initialNotification` event is fired again causing the app to run the initial notification event handler.

## Your Environment

- React Native Navigation version: 6.12.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): iOS and Android
- Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by jinshin1013** [comment]
I'm assuming this is similar to your previous issue #6764. Let's keep it the discussion in one place. Closing this now.
