### ISSUE TITLE
Bottom tabs "currentTabId" option is ignored

### ISSUE THREAD

**Issue by HectorRicardo** [wix/react-native-navigation#6766]
## 🐛 Bug Report

Trying to select a default tab by currentTabId doesn't work. In contrast, trying to select 

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## To Reproduce

1. Install RNN according to the documentation: `npm i react-native-navigation` and then run `npx rnn-link`.
2. Create two simple screen components, like this:

src/screens/Screen1.js
```js
import React from 'react';
import {SafeAreaView, Text} from 'react-native';

const Screen1 = () => (
  <SafeAreaView>
    <Text>Screen 1</Text> // Screen2.js will be exactly the same as this file, but here it would say "Screen 2"
  </SafeAreaView>
);

export default Screen1;
```

3. Setup bottom tabs in `index.js`, using the screens that you created in the previous steps. Observe the line with the comment in the snippet below.
```js
import React from 'react';
import {Navigation} from 'react-native-navigation';

import Screen1 from './src/screens/Screen1';
import Screen2 from './src/screens/Screen2';

Navigation.registerComponent('Screen1', () => Screen1);
Navigation.registerComponent('Screen2', () => Screen2);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      bottomTabs: {
        id: 'BottomTabs',
        options: {
          bottomTabs: {
            currentTabId: 'Screen2', // This line doesn't work. If you change it to currentTabIndex: 1  , then it will work
          },
        },
        children: [
          {
            component: {
              id: 'Screen1',
              name: 'Screen1',
              options: {
                bottomTab: {
                  text: 'Screen1',
                },
              },
            },
          },
          {
            component: {
              id: 'Screen2',
              name: 'Screen2',
              options: {
                bottomTab: {
                  text: 'Screen2',
                },
              },
            },
          },
        ],
      },
    },
  });
});
```

4. Run the app with `npx react-native run-ios` or `npx react-native run-android`

## Expected behavior

When running the app, the screen that should appear by default is Screen2.

## Actual Behavior

The screen that appears by default is Screen1.

![image](https://user-images.githubusercontent.com/16261233/99106580-1318ea00-25aa-11eb-8b4e-ad7265174e67.png)

## Your Environment

- React Native Navigation version: 7.3.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): Both. Tested with a Huawei p30 Lite and with an iOS simulator.

## Reproducible Demo

Link to Minimum Reproducible Example: [https://github.com/HectorRicardo/bug-rnn-currentTabId](https://github.com/HectorRicardo/bug-rnn-currentTabId)

**Comment by danilobuerger** [comment]
@HectorRicardo please try the current master and see if the expected behavior is restored.
