### ISSUE TITLE
Deep cloning of props contradicts documentation.

### ISSUE THREAD

**Issue by vovkasm** [wix/react-native-navigation#6768]
## 🐛 Bug Report

Current behavior is to deep clone `passProps`. As a result we can't pass mobx observables to components, also no objects can be passed "by reference". But documentation clearly states, that **any** objects can be passed through `passProps`.

![Docs](http://vovkasm.skitch.vovkasm.org/passProps_25612ECC.png)

Issue #4798 describe this behavior, but it was closed without full information. I propose to remove `deepClone` from passProps, because:
1. Documentation clearly states that any object can be passed through
2. This props do not passed through native, they whole time in js, in the store (https://github.com/wix/react-native-navigation/blob/master/lib/src/components/Store.ts#L7). Because of this it is totally safe to pass any values through
3. `deepClone` - is overhead, its slow, and definitely should be optional and not default behavior. If one want additional safety he can add it very easy by cloning passProps itself. But currently if one don't need this behavior, he could not disable it.
4. Current workaround from #4798, is to pass closure which will return objects that broken by `deepClone`, but this workaround will stop to work soon (https://github.com/lodash/lodash/issues/4781)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes. But this link is broken :-)

## To Reproduce

```typescript
// Form model
class LoginForm {
  login: string = '';
  password: string = '';

  constructor() {
    makeAutoObservable(this);
  }

  setLogin(val: string) { this.login = val; }

  get isLoginValid() { return Boolean(this.login) }
  get isValid() { return this.isLoginValid && Boolean(this.password); }
}


// In some place, called from another screen
  pushLoginScreen(componentId: string) {
    const loginForm = new LoginForm();
    Navigation.push(componentId, {component: {name: screens.Login, passProps: {loginForm}}});
  }


const Login: NavigationFunctionComponent<{loginForm: LoginForm}> = observer((props) => {
  const form = props.loginForm;
  const onChange = useCallback((text) => form.setLogin(text), [form]);
  return (
    <ScreenContent>
      <LoginInput inputTitleText="Login" value={form.login} onChange={onChange} />
      {form.isLoginValid ? <Button title={'Next'} /> : null}
    </ScreenContent>
  );
}
```

## Expected behavior

TextInput can be filled with value. `onChange` sets observable prop login in the LoginForm which followed by component rerender because Login wrapped in observer.

## Actual Behavior

TextInput can't be filled. I place any symbol and it momentary resets to empty string. Because loginForm after deepClone is't observable anymore.

## Your Environment

- React Native Navigation version: 7.0.3
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): both
- Device info (Simulator/Device? OS version? Debug/Release?): not relevant, its all in js

## Reproducible Demo

Can create on request.

**Comment by vovkasm** [comment]
I can prepare PR, after discussion to be sure that we agree on design.

**Comment by guyca** [comment]
Hey @vovkasm 👋 
Thanks for reporting the issue and proposing to submit a PR! Let's continue the discussion on [Discord](https://discord.gg/DhkZjq2)? It's easier to have a conversation there compared to the issue tracker.
