### ISSUE TITLE
Props are deep cloned the first time Navigation.updateProps is called

### ISSUE THREAD

**Issue by HectorRicardo** [wix/react-native-navigation#6769]
## 🐛 Bug Report

For some reason, the first time `Navigation.updateProps` is called, properties of type object are deep cloned. For this reason, comparison with `===` fails.
However, from the second time on, this doesn't happen. I will show below a simple demostration in how to reproduce the bug in a practical example. 

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## To Reproduce

1. Create a new React-Native Project. `npx react-native init deepclonepropfirsttime`
2. Install RNN according to the documentation: `npm i react-native-navigation`, then run `npx rnn-link` and for ios, run `cd ios && pod update && cd ..`.
4. Enable MultiDex on Android. On `app/build.gradle`, add this line to the `defaultConfig` section:
```
defaultConfig {
        applicationId "com.deepclonepropfirsttime"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        multiDexEnabled true // <----------- Add this line
    }
```
5. Here comes the actual code for the bug: Use the following code in `index.js` and on `App.js`

index.js
```javascript
import {Navigation} from 'react-native-navigation';
import App from './App';

const items = [{name: 'item1'}, {name: 'item2'}];

Navigation.registerComponent('com.myApp.WelcomeScreen', () => App);

Navigation.events().registerAppLaunchedListener(() => {
  Navigation.setRoot({
    root: {
      component: {
        id: 'com.myApp.WelcomeScreen',
        name: 'com.myApp.WelcomeScreen',
        passProps: {
          items,
          onSelectItem: function onSelectItem(selectedItem) {
            Navigation.updateProps('com.myApp.WelcomeScreen', {
              items,
              selectedItem,
              onSelectItem,
            });
          },
        },
      },
    },
  });
});
```

App.js
```javascript
import React from 'react';
import {Button, Text, View, StyleSheet} from 'react-native';

const App = ({items, selectedItem, onSelectItem}) => (
  <View style={styles.root}>
    <Text>Selected item's name: {selectedItem?.name}</Text>
    {items.map((item) => (
      <View
        key={item.name}
        style={[
          styles.itemContainer,
          selectedItem === item && styles.selectedItem, // <------ comparison with === fails
        ]}>
        <Text>{item.name}</Text>
        <Button title="Select me" onPress={() => onSelectItem(item)} />
      </View>
    ))}
  </View>
);

export default App;

const styles = StyleSheet.create({
  root: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemContainer: {
    width: 300,
    flexDirection: 'row',
    marginTop: 10,
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  selectedItem: {backgroundColor: 'yellow'},
});
```

Quick explanation of the demo: Basically I have a list of two items, and I am displaying them in the screen. Each has a "Select me" button associated to it. When you click the button, the item in question gets highlighted. Also, the name of the item you clicked is shown as text at the top.

So the initial screen is:

![image](https://user-images.githubusercontent.com/16261233/99214156-0efcf000-2795-11eb-83a2-8011a8698219.png)

And when you press an item, it should be like this:

![image](https://user-images.githubusercontent.com/16261233/99214290-600ce400-2795-11eb-98d0-9de95651d9a0.png)

## Expected behavior

The first time I click on the "Select me" button of whichever item, that item should get highlighted. (See screenshots above)

## Actual Behavior

The first time you click on "Select me", the item's name appears as text on the top, however it doesn't get highlighted:

![image](https://user-images.githubusercontent.com/16261233/99214246-466b9c80-2795-11eb-91ca-446ff790a7a7.png)

## Your Environment

- React Native Navigation version: 7.3.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): BOTH
- Device info (Simulator/Device? OS version? Debug/Release?): I tested with both: Huawei p30 Lite in Android (Android 10) and an ios simulator Iphone 11 - 14.2

## Reproducible Demo

[https://github.com/HectorRicardo/bug-rnn-clonedPropFirstTime](https://github.com/HectorRicardo/bug-rnn-clonedPropFirstTime)

**Comment by guyca** [comment]
duplicates #6768
