### ISSUE TITLE
Change the navbar style depending on scroll position

### ISSUE THREAD

**Issue by hamidhadi** [wix/react-native-navigation#677]
Can I change the Navbar style when scroll position is changed?

**Comment by guyca** [comment]
No. You can try setting the NavBar color to transparent and draw your screen under it using:
```js
static navigatorStyle = {
  navBarTransparent: 'true',
  drawUnderNavBar: 'true'
}
```

Then show  fake navBar (`View`) and change it's color.
Or just use a react nav bar component in that specific screen
