### ISSUE TITLE
Use icons instead of title strings in TopTabs

### ISSUE THREAD

**Issue by desmondhume** [wix/react-native-navigation#678]
Is there any way I can display icons in TopTabs, instead of text strings?

Example:

```
Navigation.startSingleScreenApp({
  screen: {
    screen: 'example.TopTabsScreen',
    topTabs: [
      {
        screenId: 'example.HomeScreen',
        title: 'Home', // Use an icon here
      },
      {
        screenId: 'example.ProfileScreen',
        title: 'Profile', // Use an icon here
      },
    ]
  }
})
```

---
### Environment
* React Native Navigation version: 2.0.0-experimental.180
* React Native version: 0.38.0
* Platform: Android

**Comment by guyca** [comment]
I actually wanted to work on this issue this morning - but I woke up late 😄 Will do my best to have this by the end of the week

**Comment by guyca** [comment]
#680 adds support for icons in `TopTabs`
