### ISSUE TITLE
All screens load and render on app start

### ISSUE THREAD

**Issue by fadinasr** [wix/react-native-navigation#6786]
## 🐛 Bug Report

I'm using bottom tabs in my Main root after the user logs in. All pages are rendering after the app starts. I tried using `tabsAttachMode: 'onSwitchToTab'` but nothing is changed.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## To Reproduce

1. Add tabs attached mode to qual to `onSwitchToTab` inside the `bottomTabs` of the main root.
2. Rebuild the application
3. Check the log to see which screens loads on startup

## Expected behavior

Each stack should render after pressing on its' icon. Would be perfect if each child can render after jumping into it.

## Actual Behavior

All the screens are being rendered on app load.

## Your Environment

- React Native Navigation version: 7.4.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): both
- Device info (Simulator/Device? OS version? Debug/Release?): debug version on both simulator and device

## Reproducible Demo

https://gist.github.com/fadinasr/f582af0b82504d0929e41deea4fb2290

**Comment by fadinasr** [comment]
Tried to add `tabsAttachMode: 'onSwitchToTab'` inside `Navigation.setDefaultOptions` and also didn't work.

**Comment by danilobuerger** [comment]
There is no `root.bottomTabs.tabsAttachMode` option.

**Comment by zainspresso** [comment]
Anyone got this working?
