### ISSUE TITLE
passProps are unavailable in commandListener

### ISSUE THREAD

**Issue by Frenchford** [wix/react-native-navigation#6790]
## 🐛 Bug Report

passProps passed into component on showModal are unavailable in commandListener

## To Reproduce

1. Register component
```
Navigation.registerComponent(
   'SomeName',
   () => (props) => <Component {...props} />),
);
```
2. call showModal
```
Navigation.showModal({
        stack: {
            children: [{
                name: 'SomeName',
                passProps: {
                  someProp: 'someValue'
                },
            }],
        },
    });
```
3. Navigation.events().registerCommandListener fires with 
```
{
  data: {
    ...
    layout: {
      ...
      children: [
        0: {
          ...
          data: {
            name: "SomeName"
            passProps: undefined
          }
        }
      ]
    }
  }
}
```

## Expected behavior

passProps of components are available and same as it was called in showModal

## Actual Behavior

passProps are undefined

## Your Environment

- React Native Navigation version: 7.1.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): Android, iOS not tested
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator (Pixel 3a XL, api r:5554)

**Comment by Frenchford** [comment]
#4716 https://github.com/wix/react-native-navigation/issues/4716

**Comment by pribeh** [comment]
Bummer

**Comment by danilobuerger** [comment]
In the playground app you can go to Navigation -> Modal -> Show Modal. On both platforms I got something similar to:
```
{
    "commandId": "showModal15",
    "layout": {
        "id": "Component14",
        "type": "Component",
        "data": {
            "name": "Modal",
            "passProps": {
                "modalPosition": 2,
                "previousModalIds": [
                    "Component12"
                ]
            }
        },
        "children": []
    }
}
```
On both platforms the `passProps` was present and filled. Please provide a reproducible demo (as asked in the issue template!) with the newest version of rnn for us to investigate this further.

**Comment by Frenchford** [comment]
Untouched playground with registerCommandListener in start function of the playground app.
Navigation -> Modal -> ShowModal.
CommandListener fires with next params
```
{
  "commandId": "showModal17",
  "layout": {
    "id": "Component16",
    "type": "Component",
    "data": {
      "name": "Modal",
      "options": {
        ...
      },
      "passProps": undefined,
    },
    "children": []
  }
}
```

passProps are undefined despite showModal:
```
showModal = () => {
    Navigation.showModal({
      component: {
        name: Screens.Modal,
        passProps: {
          modalPosition: this.getModalPosition() + 1,
          previousModalIds: concat([], this.props.previousModalIds || [], this.props.componentId),
        },
      },
    });
  };
```

**Comment by danilobuerger** [comment]
@Frenchford that is not sufficient as a reproduction. As I mentioned above, I tried the playground app on android and received the filled `passProps` (see above).

**Comment by Frenchford** [comment]
@danilobuerger any suggestions? How to prove that I'm not a camel?

**Comment by danilobuerger** [comment]
Don't know, but we can't fix a problem that we are not experiencing.

**Comment by Frenchford** [comment]
Maybe I use it wrong? Is that correct?
```
  Navigation.events().registerCommandListener((name, params) => {
    console.log('registerCommandListener', { name, layout: params.layout });
  });
```

**Comment by Frenchford** [comment]
As I understand layoutTreeCrawler mutates the layout that passed to showModal command. So crawl removes passProps from layoutNode.  And even notify calls before crawl, both of them use the same object which is already mutated in commandListener.

**Comment by guyca** [comment]
@Frenchford It would be best if you could submit a falling Detox e2e test which reproduces the bug.

**Comment by Frenchford** [comment]
@guyca, Got it! My case is I want to keep props I got in the commandListener for a while. The only thing I have is to deep copy props in the commandListener because it will be mutated right after notify ends. Right?

**Comment by guyca** [comment]
> I'm not realy familiar with detox e2e testing, sorry

It's very easy I assure you. Just clone the repo and run the tests - it should just work.
