### ISSUE TITLE
Let define the title in the screen itself

### ISSUE THREAD

**Issue by dropfen** [wix/react-native-navigation#68]
I was wondering, that it is not possible to define a `static title` in the screen itself, but have to define it in the `action`. like 

```
navigator.push({
 screen: "foo.bar",
 title: "FooBar"
})
```

I would prefer to define it in the class itself, because I think it belongs there

```
class FooBar extends Component {
  static title = "FooBar";
  static navigatorStyle = {
    screenBackgroundColor: '#222'
  }
  ...
}
```

Please correct me, if I am doing something wrong.

Otherwise, this is a feature request ;)

**Comment by dropfen** [comment]
I am using a forked version of the react-native-controller, and I've put the title into the `navigatorStyle`.
I just used it, because it was the simplest way of passing this option to the native code, without a lot of modifications. I would make a PR, but I think navigator**Style** is not the right place for it.. 
But what are styles? This are just options for style customizations.. right? I would suggest to rename the dictionary to **navigatorOptions** and put there everything we need.. Styles options, behavior, title.. its just a simple object and it is straightforward to reuse and update for the next addition, further PR request, etc.

**Comment by guyca** [comment]
@dropfen Your suggestion is very interesting. Defining a title when pushing a screen by _id_ does seem wrong.
We're actually going to have a meeting this Thursday (June 23'RD) regarding the current state of the API. once the Android version becomes more stable, our next goal is to reexamine the API. If there are more cases like this one you think should be addressed, please let me know and I'll bring it up in our meeting.

**Comment by dropfen** [comment]
Hmm, well its not a lot time to dive deep into it, but this is what I would suggest.

**Let the screen itself decide, how it should behave by default.**

lets say the screen is representing a modal, And I want, that this modal always slides up. I can override this by passing the value through the action, but defaults should be in one place.

To have the title option in the action makes also sense, because, I can set it programmatically, when I am moving from a list to item view and so on. In my code the title in the action overrides the default title from the screen.

To give more space for customizations, I would also suggest to rename
**navigatorStyle** => **navOpts** 

There are already a couple of properties, which are more options, than styles..

```
{
  navBarTextColor: '#000000', 
  navBarBackgroundColor: '#f7f7f7', 
  navBarButtonColor: '#007aff', 
  navBarHidden: false,
  navBarHideOnScroll: false,
  navBarTranslucent: false,
  drawUnderNavBar:true,
  navBarTransparent: false,
  navBarNoBorder: false,
  navBarTranslucent:true
  drawUnderTabBar: false,
  statusBarBlur: false,
  navBarBlur: false, 
  tabBarHidden: false, 
  statusBarHideWithNavBar: false,
  statusBarHidden: false,
  statusBarTextColorScheme: 'dark' 
}
```

**Comment by dabit1** [comment]
Hi! What's the state of this? Defining title for each push call seems wrong. Thanks!

**Comment by blairvanderhoof** [comment]
Agreed, why do we need to define the title in push when we already define it in registerComponent?

**Comment by peterlau** [comment]
This sounds like a great feature request for V2.. but in the meanwhile this, perhaps lacking in 'elegance', works just fine:

```
  constructor(props){
    super();
    ...
    props.navigator.setTitle({title: "JLine"})
  }
```

**Comment by isaachinman** [comment]
For those using a Redux/MobX provider HOC who want their actual screen components to be nice and clean, and don't mind some dirtiness elsewhere, you can implement something like this:

    componentWillMount = () => {
      const { children } = this.props
      // Set titles from class properties
      React.Children.map(children, (child) => {
        if (child && child.type && child.type && child.type.screenTitle && typeof child.type.screenTitle === 'string' &&
          child.props && child.props.navigator && child.props.navigator.setTitle) {
          child.props.navigator.setTitle({ title: child.type.screenTitle })
        }
      })
    }

This allows you to use `static screenTitle = 'My title'` without having to fork anything.

**Comment by guyca** [comment]
Closing as this is implemented in v2

```js
class WelcomeScreen extends Component {
  static get options() {
    return {
      topBar: {
        title: {
          title: 'My Screen'
        }
      }
    };
  }
  ...
}
```

**Comment by sapjax** [comment]
I use @Decorator implement this feature：
```typescript
@screenDecorator
class Screen1 extends React.Component {
static navigatorTitle = (props) => 'xxxx'
...
}
```

and in @screenDecorator:

```typescript
function screenDecorator<T extends Props>(Component: T) {

  class ScreenComponent extends Component {
    constructor(props) {
      super(props)
      props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this))

      // set Title
      if (ScreenComponent.navigatorTitle) {
        props.navigator.setTitle({
          title: ScreenComponent.navigatorTitle(props),
        })
      }
   }
}
```

The benefit is we can pass props to the function return a title,  so we also can handle i18n situation.

**Comment by webdeb** [comment]
@guyca please, can you give an estimate for v2, when is it actually stable enough to be used in production?

**Comment by isaachinman** [comment]
@sapjax How are you passing other statics through your decorator?

**Comment by sapjax** [comment]
@isaachinman other statics no need to pass through,  the screen component processed by typescript @Decorator is like a new class extend the old class,  statics is used as the same.

**Comment by guyca** [comment]
@webdeb The api in v2 is already stable and, as you've seen in the road map, we're almost in parity with v1. I've updated the roadmap a bit, it still doesn't fully reflect the current state as we've stopped updating it a while ago since we're managing tasks [here](https://github.com/wix/react-native-navigation/projects/3?fullscreen=true).

**Comment by GitHubGreg** [comment]
@guyca I am using v2 but your code doesn't work to rename the component title. Any ideas why not?
