### ISSUE TITLE
Status bar always black when setRoot is delayed

### ISSUE THREAD

**Issue by marcshilling** [wix/react-native-navigation#6800]
## 🐛 Bug Report

When your `Navigation.setRoot` call is delayed, the status bar text color changes to black during launch, even when you set Status Bar Style to "Light Content" in Xcode.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## To Reproduce

1. Set `UIStatusBarStyle` to `UIStatusBarStyleLightContent` in the Xcode project (Info.plist)
2. Delay your app's call to `Navigation.setRoot` in some way (loading data, logging in, etc)
3. Set your app's initial screen to have a light status bar. In your `Navigation.setDefaultOptions`, set `statusBar: { style: 'light' },

## Expected behavior

The status bar text color should remain white throughout the app's launch.

## Actual Behavior

The status bar text color turns black between the splash screen and the app calling `setRoot`.

## Reproducible Demo

https://github.com/marcshilling/react-native-navigation-status-bar-launch-issue

In my 1 commit on that repo, I did the following to the playground:
- Set `UIStatusBarStyle` to `UIStatusBarStyleLightContent` in the Xcode project (Info.plist). This specifies to use a light status bar on launch.
- Set the splash screen to have a red background (so you see the white status bar)
- In `Navigation.setDefaultOptions`, specify light status bar style (so initial screen is white status bar) and red top bar background (for visibility)
- Delay the Navigation.setRoot` call 5 seconds with a setTimeout

Run a playground release build. You will see the status bar initially white on launch, then turn black for 5 seconds (during the delay), then back to white for the initial screen. We should either pull the `UIStatusBarStyle` from iOS for that period, or use Navigation's default options...but seems neither is happening.

**Comment by danilobuerger** [comment]
@marcshilling Could you please try the fix in #6803 and report back?

**Comment by marcshilling** [comment]
@danilobuerger yep, that fixes it! Sorry, don't know how I didn't find that first. Will patch for now until this gets merged, thanks.
