### ISSUE TITLE
Cannot build release Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by djschilling** [wix/react-native-navigation#6808]
## 🐛 Bug Report

After upgrading to version `7.5.0` from version `6` i get the following compiler error when trying to release a new version on ios:

```
ld: warning: ignoring file /Users/david/Library/Developer/Xcode/DerivedData/ChurchTools-czjzvuuedsriwgcrishcnnblzofc/Build/Intermediates.noindex/ArchiveIntermediates/ChurchTools/BuildProductsPath/Release-iphoneos/ReactNativeNavigation/libReactNativeNavigation.a, building for iOS-armv7 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_ReactNativeNavigation", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried the steps descriped here but they didn't help: https://github.com/facebook/react-native/issues/29984#issuecomment-696328815

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## Your Environment

- React Native Navigation version: 7.5.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Release

**Comment by djschilling** [comment]
Why did this issue get closed?

**Comment by danilobuerger** [comment]
@djschilling because its not a bug with rnn. Most likely it has to do with your specific setup. You are more than welcome to join us on Discord and ask for help there. But this issue tracker (as explained above) is for bugs and feature requests.

**Comment by mahadazad** [comment]
> ## 🐛 Bug Report
> After upgrading to version `7.5.0` from version `6` i get the following compiler error when trying to release a new version on ios:
> 
> ```
> ld: warning: ignoring file /Users/david/Library/Developer/Xcode/DerivedData/ChurchTools-czjzvuuedsriwgcrishcnnblzofc/Build/Intermediates.noindex/ArchiveIntermediates/ChurchTools/BuildProductsPath/Release-iphoneos/ReactNativeNavigation/libReactNativeNavigation.a, building for iOS-armv7 but attempting to link with file built for iOS-arm64
> Undefined symbols for architecture armv7:
>   "_OBJC_CLASS_$_ReactNativeNavigation", referenced from:
>       objc-class-ref in AppDelegate.o
> ld: symbol(s) not found for architecture armv7
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> I tried the steps descriped here but they didn't help: [facebook/react-native#29984 (comment)](https://github.com/facebook/react-native/issues/29984#issuecomment-696328815)
> 
> ### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?
> Yes
> 
> ## Your Environment
> * React Native Navigation version: 7.5.0
> * React Native version: 0.63.3
> * Platform(s) (iOS, Android, or both?): iOS
> * Device info (Simulator/Device? OS version? Debug/Release?): Release

I have the same issue. Did you manage to fix it?

**Comment by nericode** [comment]
I have the same issue.

**Comment by elsurudo** [comment]
I'm also having the same issue. Did anyone have any luck resolving it?

**Comment by alan-nakagiri** [comment]
I have the same issue as well... @djschilling Did you ever find a fix?
