### ISSUE TITLE
Feature needed: enable single screen supporting orientation.

### ISSUE THREAD

**Issue by jaggerwang** [wix/react-native-navigation#681]
### Issue Description

Right now, Android can turn on portraitOnlyMode to make the whole app not supporting orientation, iOS not implemented yet. Both are not supporting turn on or off orientation for single screen. This feature is useful for apps that has a video player screen, which only need the player screen can be rotated.

**Comment by Crash--** [comment]
I've a workaround for iOS. You need to check in XCode portrait and landscape mode for you app.

And add in you AppDelegate something like this: it will lock the orientation change onto Portrait except for `AVFullScreenViewController` view (native video player on iOS)
```obj-c
- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window{
  UIViewController *presentedViewController = window.rootViewController.presentedViewController;
  if (!presentedViewController) {
    return UIInterfaceOrientationMaskPortrait;
  }
//AVFullScreenViewController is the class for the native iOS VideoPlayer
  Class videoControllerClass = NSClassFromString(@"AVFullScreenViewController");
  if (!videoControllerClass) {
    return UIInterfaceOrientationMaskPortrait;
  }
  if ([presentedViewController isKindOfClass:videoControllerClass] || [presentedViewController.presentedViewController isKindOfClass:videoControllerClass]) {
    return UIInterfaceOrientationMaskAll;
  }
  [[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationNone];
  return UIInterfaceOrientationMaskPortrait;
}
```

But I've a bit more problems to achieve the same thing on Android. I have added `android:configChanges="keyboard|keyboardHidden|orientation|screenSize"` but everytime I rotate the screen or ask for a setRequestOrientation, the activity is refreshed :(

**Comment by guyca** [comment]
@Crash-- #783 prevents the activity from getting destroyed.

**Comment by Crash--** [comment]
@guyca Thanks. It works as expected now :)

**Comment by gran33** [comment]
https://github.com/wix/react-native-navigation/pull/820
