### ISSUE TITLE
[iOS] mergeOptions is slow

### ISSUE THREAD

**Issue by manuhook** [wix/react-native-navigation#6815]
## 🐛 Issue Report

Hi !

mergeOptions on iOS is slower since version 6.10.1 
I use it on a scroll to change the color of the status bar and the tabbor at a given scroll point, and the scrolling is jumpy on iOS. 

Note that it's not the options that consume resource. If I do a simple Navigation.mergeOptions(componentId); the scrolling become also jumpy.

No problem on Android, it’s butter smooth, but on iOS the frame drop in the ui thread is even visible on an iphone 12 pro.

The change that seems to me to be the most resource-intensive is this one :

6.10.1 > 6.11
mergeOptions became slower because of this commit
https://github.com/wix/react-native-navigation/commit/c9e5309f87bdae31cd2d90a51ead201b297bbf94
Renaming `objectProperties` to `classProperties` 
Reverting this commit greatly improves fluidity.

Demo on iPhone X (Release)

With this commit :
https://imgur.com/a/8DyQyjE

Without this commit :
https://imgur.com/a/hC3TqBk

Do think there is a way to improve that ?

Thank you  ! 🙏

## Your Environment

- React Native Navigation version: 7.5.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device, Debug @ Release

**Comment by mrousavy** [comment]
I can't wait for the bridge to disappear. With a sync invocation (TurboModules) this would be much smoother.

Either way, that's a regression. I believe @yogevbd is pretty busy right now, I've assigned him but I'll take a look at this tomorrow and see if I can fix it.

**Comment by danilobuerger** [comment]
@guyca I wonder why we are resorting to runtime introspection for mergeOptions anyway? Why not do it like on android and be explicit about what we are merging?

**Comment by yogevbd** [comment]
@danilobuerger we should be explicit here.. working on it asap
