### ISSUE TITLE
Change Font of the navigation bar

### ISSUE THREAD

**Issue by hamidhadi** [wix/react-native-navigation#682]
I could change the font of the tabbar by adding this line of code in `AppDelegate.m` file: 
```objective-c
  [[UITabBarItem appearance] setTitleTextAttributes:@{NSFontAttributeName:[UIFont fontWithName:@"fontName" size:11]} forState:UIControlStateNormal];
```

I also want to change the font of the navigation bar so I write this code: 
```objective-c
  [[UINavigationBar appearance] setTitleTextAttributes:@{
      NSFontAttributeName: [UIFont fontWithName:@"fontName" size:20]
  }];
```
But It doesn't change the font of the navigation bar. How can I fix it?

**Comment by jbolter** [comment]
Same question. How do we set the fontFamily for the navigation bar title?  This seems like it should be obvious but I can't seem to find it in the docs anywhere.

**Comment by hamidhadi** [comment]
@jbolter I couldn't change it. My solution is hiding the navigation bar and create a fake navigation title. 
I hope this problem will fix in the future :\

**Comment by jbolter** [comment]
@hamidhadi I dug through the iOS code and found that there are some apparently undocumented settings that affect the navigation bar title...

navBarTextFontFamily: "TiemposHeadline-Regular",
navBarTextFontSize: 20,

With these two additions I am able to change the fontFamily and fontSize. However this only seems to work for iOS.  I come from an iOS background so I'm more familiar digging through that code.  If anyone has any ideas for Android I would love to hear them!  I will update here if I figure it out.

Thanks!

**Comment by hamidhadi** [comment]
@jbolter Hmmm 🤔 
How and where can we use these settings?
I'm using [react-navigation](https://reactnavigation.org) for android. It's more customizable than `react-native-navigation`. Also, I will switch my iOS app navigation module to that in the future.

**Comment by jbolter** [comment]
@hamidhadi These are keys into the navigatorStyle object that is set in each Screen or is passed into the Navigation.startSingleApp or Navigation.push functions.

```
const navigatorStyle = {
    	statusBarColor: (Platform.OS === 'ios') ? 'white' : 'black',
    	statusBarTextColorScheme: 'light',
    	navigationBarColor: 'black',
    	navBarBackgroundColor: colors.primary,
    	navBarTextColor: 'white',
    	navBarButtonColor: 'white',
    	tabBarButtonColor: 'red',
    	tabBarSelectedButtonColor: 'red',
    	tabBarBackgroundColor: 'white',
      navBarTextFontFamily: "Tiempos Headline", // Replace with your fontFamily
      navBarTextFontSize: 20, // Replace with your fontSize
    };

navigator.push({
      screen: 'msbuddy.SignIn',
      title: 'Sign In',
      navigatorStyle
    });
```js

**Comment by jbolter** [comment]
@hamidhadi  I really wasn't very happy with the [react-navigation] (https://reactnavigation.org/) library on iOS.  The JavaScript implementations just don't quite "feel" native to me.  I didn't play with it much on Android before switching to the wix native navigation.

**Comment by guyca** [comment]
Hey guys, `navBarTextFontFamily` was added to Android as well. `tabBarTextFontFamily` was also added.
