### ISSUE TITLE
White Space at bottom of Tabs

### ISSUE THREAD

**Issue by priyak-sdei** [wix/react-native-navigation#6827]
## 🐛 Bug Report

Bottom tabs are showing  whitespace from bottom. See screenshot attached.
![Simulator Screen Shot - iPhone XR - 2020-12-09 at 19 45 56](https://user-images.githubusercontent.com/70944781/101641194-7ab24000-3a57-11eb-939d-ec9d0454c8f1.png)

## Your Environment
- React Native Navigation version: 3.2.0
- React Native version: 0.61.1
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): iPhone 11, iPhone Xr. Simulator (iOS 14.2)

**Comment by jinshin1013** [comment]
@priyak-sdei I couldn't reproduce the problem on the Playground app. I can see you are using quite old version of `react-native-navigation`, could you update to the latest version and compare you code with the Playground app?
