### ISSUE TITLE
Content view is hidden by the bottom tabs

### ISSUE THREAD

**Issue by nitzanbener** [wix/react-native-navigation#6828]
## 🐛 Bug Report

I have a clean screen with only <View style={{ height: '100%', justifyContent: 'flex-end' }}><Text>Hey!</Text></View> and bottomTabs are set with 4 items.

The issue is that the bottom tabs are places on top of the view, making the text invisible.

## To Reproduce

1. Create a new application with 4 screens and bottom tabs included.
2. Set the first screen to have a View just like the example above.
3. Note that the text is hidden behind the bottom tabs.

## Expected behavior

I'd expect the bottom tabs to reduce view size just like a Footer.

## Your Environment

- React Native Navigation version: 7.5.0
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): iOS 14.2

## Reproducible Demo
<img width="584" alt="Screen Shot 2020-12-09 at 17 15 58" src="https://user-images.githubusercontent.com/44496859/101648675-bbec2500-3a42-11eb-9a59-abc5ec541def.png">

**Comment by jinshin1013** [comment]
Hi @nitzanbener thanks for reporting the issue! This is intended and try using `SafeAreaView` to wrap your screen. Cheers 🙏
