### ISSUE TITLE
[IOS] `bottomTabSelected` event not dispatched on `switchToTab`

### ISSUE THREAD

**Issue by desmondhume** [wix/react-native-navigation#684]
The `bottomTabSelected` event is dispatched only when the user presses a button in the Tab Bar. 

I'm using a custom TabBar (which is just a View with some icons calling `switchToTab` method when the user presses on each of them), but it seems like the `switchToTab` method alone is not triggering any event. 

---
### Environment
* React Native Navigation version: 2.0.0-experimental.184
* React Native version: 0.38
* Platform(s) (iOS, Android, or both?): iOS

**Comment by ankitgroovy** [comment]
hi,
@desmondhume 

you can modify the code of RCCTabBarController.m

replace this code

if (tabIndex)
    {
      int i = (int)[tabIndex integerValue];
      
      if ([self.viewControllers count] > i)
      {
        viewController = [self.viewControllers objectAtIndex:i];
      }
    }


by this code


if (tabIndex)
    {
      int i = (int)[tabIndex integerValue];
      
      if ([self.viewControllers count] > i)
      {
        viewController = [self.viewControllers objectAtIndex:i];
        NSDictionary *body = @{
                               @"selectedTabIndex": @([self.viewControllers indexOfObject:viewController]),
                               @"unselectedTabIndex": @(self.selectedIndex)
                               };
        [RCCTabBarController sendScreenTabChangedEvent:viewController body:body];
        
        [[[RCCManager sharedInstance] getBridge].eventDispatcher sendAppEventWithName:@"bottomTabSelected" body:body];
        
      }
    }
and you done it :)
