### ISSUE TITLE
componentWillAppear events not dispatching for ExternalComponents on iOS

### ISSUE THREAD

**Issue by cayleyh** [wix/react-native-navigation#6844]
## 🐛 Bug Report

Our app uses a mix of ExternalComponents and standard React components. The primary navigation is via Bottom Tab bar. We also open other screens as modals.

I am not seeing the global `componentDidAppear` listener get called for any of the screens that are using ExternalComponents. I do see the `command` events for these navigation actions, and I do see the `componentDidAppear` events for all non-ExternalComponent screens.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yup.

## To Reproduce

I created a simple reproduction with the Playground by:

- Replace the middle tab component with the existing ExternalComponent screen (I just copy & pasted from `ExternalComponentScreen.tsx`)
- Attach an `Navigation.events().registerComponentDidAppearListener()` listener in the main `start()` method that logs out all interactions.

## Expected behavior

I expect to have the `componentDidAppear` listeners called consistently for both regular and external components, and called consistently across platforms.

## Actual Behavior

`componentDidAppear` listener is only triggered for the regular component screens.

Here's a video showing the issue: https://www.loom.com/share/87029631be95473884813084ba31374c.

Appears to be iOS only. Testing our Android app, and it does not have this problem with latest 7.4.0.

## Your Environment

- React Native Navigation version: Latest Playground version
- React Native version: Latest playground version
- Platform(s) (iOS, Android, or both?): iOS. Android appears to work correctly.
- Device info (Simulator/Device? OS version? Debug/Release?): Xcode 12.3, iOS simulator, tested both 12.1 & 14.3

## Reproducible Demo

I'll link to a PR with the reproduction in playground as soon as I get can push it.

**Comment by yogevbd** [comment]
Is it possible that you override `- (void)viewDidAppear:(BOOL)animated` and forgot to call `[super viewDidAppear:animated];`?

**Comment by cayleyh** [comment]
No, I've double checked and we're calling all that correctly. In the video showing the issue I attached, I've reproduced this bug in the Playground app. I'm just committing that reproduction and will have it pushed to a fork'd branch shortly so you can see if you can reproduce what I'm seeing in that recording.
