### ISSUE TITLE
pop: { enabled: false } not working, can't disable pop animation

### ISSUE THREAD

**Issue by sanghavan** [wix/react-native-navigation#6854]
## 🐛 Bug Report

pop: { enabled: false } not working, can't disable pop animation.

## To Reproduce

The issue able to reproduce from main playground app.
I tried on tap button `Push Without Animation` in **Pushed Screen** component `PushedScreen.tsx`, then tapping back from navigation.

## Expected behavior

Pop animation should be disabled by setting pop: { enabled: false }

## Actual Behavior

Pop animation is still there when setting pop: { enabled: false }

## Your Environment

- The playground app downloaded from release tag `7.6.0`
- React Native Navigation version: `7.6.0`
- React Native version: `0.63.2`
- Platform(s) (iOS, Android, or both?): `iOS`
- Device info (Simulator/Device? OS version? Debug/Release?): Real device iPhone X, Simulator iPhone 8 Plus. OS: iOS 14.3, The both Debug & Release mode

**Comment by danilobuerger** [comment]
I think you are confusing the back button with pop. Those are different. In the playground if you click the "Pop" button after "Push without Animation" it pops without an animation. If you want the same behaviour with the back button, you will need to override it.

**Comment by sanghavan** [comment]
> I think you are confusing the back button with pop. Those are different. In the playground if you click the "Pop" button after "Push without Animation" it pops without an animation. If you want the same behaviour with the back button, you will need to override it.

Thanks for your clarifying. Is there the ways to override default back button action for all components? I mean it allows to override in `Navgiation.setDefaultOptions()`

**Comment by sanghavan** [comment]
@danilobuerger I think the default back button action is used Navigation.pop() as its internal implementation, because when I custom translation/alpha as below, the default back button behaviour is changed. Just can't disable it.
```
pop: {
        content: {
            alpha: {
                from: 1,
                to: 0,
                duration: SHOW_DURATION
            },
            translationY: {
                from: 0,
                to: _screenHeight * 0.7,
                duration: SHOW_DURATION * 0.9
            }
        }
    }
```

**Comment by sanghavan** [comment]
Hi! any updates on this?
