### ISSUE TITLE
bottomTab selectedTextColor does not work properly on android.

### ISSUE THREAD

**Issue by a-eid** [wix/react-native-navigation#6859]
## 🐛 Bug Report

I'm trying to use `selectedTextColor` with my tabs, however it seems that it does not work on android for some reason.

## To Reproduce

- make a simple `BottomTabs` navigator with `selectedTextColor`. 
- works on IOS great, & does not work on android.

## Expected behavior

it should work on both platforms

## Actual Behavior

only works on ios.

![Dec-26-2020 07-14-56](https://user-images.githubusercontent.com/19273413/103145916-19be8380-474a-11eb-8f64-ddd0b48a1c0b.gif)

## Your Environment

- React Native Navigation version: ^7.6.0
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): Android 9
- Device info (Simulator/Device? OS version? Debug/Release?): Debug

please let me know if a repro is necessary here, I can provide on if needed.

**Comment by a-eid** [comment]
after some investigation, it does work with `Navigation.setDefaultOptions`, so I guess that's probably enough.

**Comment by danilobuerger** [comment]
@a-eid But does it work via static options or mergeOptions?

**Comment by a-eid** [comment]
@danilobuerger hey, it does work with `Navigation.setDefaultOptions`, it didn't work when defining the colors on the individual `bottomTab` when defining the stack. 

but it seem to be working now for some reason, I was in the testing phase sorry ( usually I include all the details needed .), I'll reopen if I face this again.

**Comment by d-baranowski** [comment]
I'm seeing the exact same issue. The text is initially the color specified but then changes to gray. 

```
Navigation.setDefaultOptions({
  bottomTabs: {
    backgroundColor: '#212121',
    animate: true,
    animateTabSelection: true,
  },
  bottomTab: {
    selectedTextColor: 'white',
  },
  topBar: {
    title: {
      text: '96Yoga',
      fontSize: 25,
      color: 'white',
      alignment: 'center',
      fontWeight: 'bold',
    },
    rightButtons: [
      {
        id: 'notifications-bell',
        icon: require('./static/icons/bell-white.png'),
      },
    ],
    background: {
      color: '#212121',
    },
  },
});
```
