### ISSUE TITLE
[v7.2+][iOS] dismissAllModals now does not resolve at all if there is no modal

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#6875]
## 🐛 Bug Report

If no modal is currently displayed, `dismissAllModals` does not resolve at all (neither in `then` nor in `catch`). This is due  to [this change](https://github.com/wix/react-native-navigation/pull/6671). 

It happens only on some versions  of iOS. So far, I've checked two versions :
- iOS 12.2 => broken
- iOS  14.3 => it works as expected...
I'm currently downloading other iOS simulator versions to check against them.

IMO, it should at least resolve or throw an error...

## To Reproduce

Call `dismissAllModals` when no modal is currently open. Check if it resolves of throw an error => none of those cases happen, nothing happen at all...

## Expected behavior

`dismissAllModals` should resolve if no modal is currently open.

## Actual Behavior

`dismissAllModals` does not resolve if no modal is currently open.

## Your Environment
- React Native Navigation version: Any version >= 7.2.0
- React Native version: Any
- Platform(s) (iOS, Android, or both?): at least iOS 12.2 and **not** iOS 14.3, 
- Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by danilobuerger** [comment]
I just tried this with the current master playground and `dismissAllModals` resolves just fine. Please provide a reproducible demo.

**Comment by zabojad** [comment]
@danilobuerger I'm trying  to produce that but on  master's playground, each time I'm trying to compile the project in XCode, I'm getting errors in RNNNavigationButtons.m: `No visible @interface for 'Color' declares the selector 'getWithDefaultValue:'`

<img width="1144" alt="Screenshot 2021-01-01 at 11 59 00" src="https://user-images.githubusercontent.com/1238030/103437516-d0c66d80-4c28-11eb-9452-df04360b2cc0.png">

Do you know why am I getting that?

**Comment by danilobuerger** [comment]
Try `yarn run pod-install`

**Comment by zabojad** [comment]
I just tried :

```
$ rm -rf node_modules/
$ rm -rf playground/ios/Pods/
$ yarn 
$ yarn run pod-install
```

And still have the same problem...

I'm gonna try a clean git clone, maybe something is corrumpted somewhere...

**Comment by zabojad** [comment]
OK, it works on a clean clone...

**Comment by zabojad** [comment]
@danilobuerger here you are: https://github.com/zabojad/react-native-navigation/tree/issue_6875

Notes about the  reproducer:
1. the first screen shows two buttons: one to dismissAllModals and one for showing a modal. 
2. dismissAllModals resolution callback shows an Alert to confirm it resolved.
3. the modal that opens also presents a dismissAllModals button that also has a resolution callback that shows an Alert to confirm it resolved.

Now what  we observe: 
1. dismissAllModals will not resolve when no modal is shown (only on RNN iOS >= 7.2). 
2. dismissAllModals will resolve when at least  a modal is shown.

=> It is not consistent with Android behavior or with RNN iOS versions prior to 7.2 where dismissAllModals resolves also if no modal is shown.

**Comment by danilobuerger** [comment]
Why so complicated? Wouldn't a simple reproduction just be:
```diff
diff --git a/playground/src/screens/LayoutsScreen.tsx b/playground/src/screens/LayoutsScreen.tsx
index 8da85df08..903ce39ff 100644
--- a/playground/src/screens/LayoutsScreen.tsx
+++ b/playground/src/screens/LayoutsScreen.tsx
@@ -52,7 +52,7 @@ export default class LayoutsScreen extends NavigationComponent {
     );
   }
 
-  stack = () => Navigation.showModal(stack(Screens.Stack, 'StackId'));
+  stack = () => Navigation.dismissAllModals().then(() => console.log('test'));
 
   bottomTabs = () =>
     Navigation.showModal({

```
?

If so, clicking on the Stack button should **not** print "test" on the console per your bug report... but it does.

<img width="896" alt="Screenshot 2021-01-01 at 13 38 42" src="https://user-images.githubusercontent.com/996231/103438745-b2676e80-4c36-11eb-89f3-d718213b7f24.png">

**Comment by zabojad** [comment]
@danilobuerger I wanted it to be as visual as possible (I would  not call it complicated though) but yes, you are right, a simple console.log would make it too...

Now it doesn't change anything at my end, it does not work on iOS at my end. On what target have you tested it?

**Comment by danilobuerger** [comment]
The current iOS 14.3 Simulator.

**Comment by zabojad** [comment]
Here is our delta... It does work on iOS 14.3 and it does not work on iOS 12.2 (at least).

**Comment by danilobuerger** [comment]
Then you should have mentioned that in your issue description. You wrote all versions.

**Comment by zabojad** [comment]
@danilobuerger I did not try all versions and really thought it would be broken everywhere...  I'm downloading the simulator 13.3 to check it and will edit the original post afterwards...
