### ISSUE TITLE
7.7.0 regression with TopBar button color on IOS 12

### ISSUE THREAD

**Issue by zzorba** [wix/react-native-navigation#6877]
## 🐛 Bug Report

When upgrading from version 7.6.0 to 7.7.0, it appears that setting colors for left/right buttons in the TopBar no longer works. I have tried setting them with both the topBar.leftButtonColor/rightButtonColor options as well as the individual color option on each button with the same effect. This doesn't appear to happen on IOS13.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. Load a nav button icon to use (from react-native-svg or similar)
2. Construct a component in the following manner with a custom button color:
```  component: {
        name: 'My.Screen',
        options: {
          topBar: {
            title: {
              text: `Campaigns`,
            },
            rightButtonColor: '#888888',
            rightButtons: [{
              icon: iconsMap.add,
              id: 'add',
              color: '#888888',
              accessibilityLabel: 'New Campaign',
            }],
          },
        },
      },
    }; 
 ```
3. Observe that the buttons remain 'navigation' blue on iOS 12 simulator/real devices.

## Expected behavior

Expected the buttons change to the specified color.

## Actual Behavior

Buttons remain navigation blue (default)

## Your Environment

- React Native Navigation version: 7.7.0
- React Native version: 0.63.4
- Platform: iOS
- Device info: Simulator/Real device running IOS 12

## Reproducible Demo

Can create one if necessary, but seems fairly easy to reproduce with any existing project.

**Comment by yogevbd** [comment]
Couldn't reproduce in the playground app. Could you please provide a reproduction?

**Comment by zzorba** [comment]
I’ll see what I can do.

**Comment by yogevbd** [comment]
@zzorba How does your `defaultOptions` look like? It might be related to that

**Comment by zzorba** [comment]
Test repro that demonstrates the problem, for posterity https://github.com/zzorba/RnnTopBarButtons
Left is IOS 12, right is IOS 13 (which shows correct behavior).
![image](https://user-images.githubusercontent.com/1091291/103542940-b9c38d80-4e6b-11eb-93d5-46c16e0825e3.png)
