### ISSUE TITLE
topBar title component alignment instability [regression]

### ISSUE THREAD

**Issue by alpha0010** [wix/react-native-navigation#6883]
## 🐛 Bug Report

When using a custom component as a screen title on Android, the horizontal position changes after navigation.  Potentially related to #6456.

This issue does not occur on RNN 7.5.0.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes.

## To Reproduce

1. With stack navigation, use a component title (not a string title)
2. Push a screen
3. Pop the screen
4. Look at the title position

## Expected behavior

The title position remains stable.

## Actual Behavior

Before push (Android - iOS)
<img width="646" alt="Screen Shot 2021-01-04 at 1 33 00 PM" src="https://user-images.githubusercontent.com/4990928/103568531-b0e6b200-4e93-11eb-89cb-9e71dce11d51.png">

After pop (Android - iOS)
<img width="641" alt="Screen Shot 2021-01-04 at 1 33 24 PM" src="https://user-images.githubusercontent.com/4990928/103568585-cd82ea00-4e93-11eb-8b98-d47098f6617e.png">

Android, RNN 7.5.0
<img width="298" alt="Screen Shot 2021-01-04 at 1 56 14 PM" src="https://user-images.githubusercontent.com/4990928/103569306-12f3e700-4e95-11eb-9020-f1a67dd0a7bb.png">

Android, RNN 7.8.0
<img width="294" alt="Screen Shot 2021-01-04 at 1 58 57 PM" src="https://user-images.githubusercontent.com/4990928/103569346-1dae7c00-4e95-11eb-8688-9add95ebb269.png">

## Your Environment

- React Native Navigation version: 7.8.0
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator, API 26, Debug

**Comment by ernestasgobionis** [comment]
In my case it happens with RNN 7.7.0 as well, even without navigating, the title component on Android is centered in the topBar.

**Comment by bkalmuk** [comment]
I have the same issue. I think it's because of backButton space size is not stable when screens changes with push etc.

**Comment by alpha0010** [comment]
Perhaps introduced by #6841?

**Comment by vaibhavhrt** [comment]
For me the custom component moves left a bit once I come back to the screen by popping a different screen.
using latest version: 7.8.1
