### ISSUE TITLE
sideMenu & bottomTabs does not work together on IOS9 & IOS10

### ISSUE THREAD

**Issue by damii** [wix/react-native-navigation#6884]
## 🐛 Bug Report

i have issue, it depends sideMenu & bottomTabs use together RNN 6.12.2 on iOS10. It render following screen

React Native version: 0.61.3

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

yes

## Expected behavior

          root: {
            topBar: {
              visible: true,
              background: {
                color: COLORS.BACKGROUND,
              },
            },
            statusBar: {
              visible: true,
            },
            layout: {
              backgroundColor: COLORS.BACKGROUND,
              orientation: ['portrait'],
            },
            sideMenu: {
              visible: false,
              enabled: false,
              openGestureMode: 'bezel',
              options: {
                sideMenu: {
                  left: {
                    width: 350,
                  },
                },
              },
              left: {
                component: {
                  id: FILTER_SCREEN.id,
                  name: FILTER_SCREEN.name,
                },
              },
              center: {
                bottomTabs: {
                  currentTabIndex: 0,
                  backgroundColor: COLORS.BACKGROUND,
                  translucent: true,
                  id: 'App',
                  children: [ ... ],
                },
              },
            },
          },

## Actual Behavior

<img width="363" alt="Screen Shot 2021-01-06 at 16 24 54" src="https://user-images.githubusercontent.com/8553768/103746281-d0b8da00-503b-11eb-829b-dbb4189ab894.png">

## Your Environment

- React Native Navigation version: 6.12.2
- React Native version: 0.61.3
- Platform(s) (iOS, Android, or both?): IOS10 only
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by danilobuerger** [comment]
RNN does not support iOS 9 & 10 any more.
