### ISSUE TITLE
Add option to change badgeTextColor for bottomTab

### ISSUE THREAD

**Issue by lindesvard** [wix/react-native-navigation#6889]
## 🚀 Feature

I don't think this option exists (but can't find it in the documentation). Would be nice to be able to change the text color for the bottom tab badge. Seems like we only can change the background color?

So basically add a option like `badgeTextColor` to `bottomTab`-options.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## Motivation/Pitch

We have a fairly light badge color and together with the white text color causing poor a11y compliance. We could off course increase the background color but I think this option would be appreciated by others as well.

**Comment by danilobuerger** [comment]
This should preferably be implemented inside a `badge` object option, for example:
```
badge: {
  value: "...", // old badge option
  color: "...", // new proposed option
  backgroundColor: "...", // old badgeColor option
}
```
