### ISSUE TITLE
Detect tab change

### ISSUE THREAD

**Issue by Sehur** [wix/react-native-navigation#689]
### Issue Description

The performance of my app decreases a lot because one of the tabs has a firebase call that updates data every second, making the other tabs work really slow. 
Is there a way to stop a call or unmount the tab when another tab is selected?

* React Native Navigation version: 2.0.0-experimental
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android device 4.4.4

**Comment by guyca** [comment]
For now, you can listen to bottom tab selected events. https://github.com/wix/react-native-navigation/issues/594#issuecomment-269594664
