### ISSUE TITLE
Bottom Tabs event listener on double tap 

### ISSUE THREAD

**Issue by shankarGdev** [wix/react-native-navigation#6896]
## 🚀 Feature
Right now we have bottom tab event listener API for `registerBottomTabSelectedListener` and `registerBottomTabLongPressedListener`, the feature I'm expecting is a event listener when a user double tap a bottom tab.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## Motivation
When a user double tap on bottom tab, I can pop to root component or scroll to top functionality to my application.

## Pitch

Expose new event lister like `registerBottomTabDoubleTapListener`

**Comment by mrousavy** [comment]
What would be the reason for a double tap? It is a _very_ uncommon gesture to double tap on a tab bar item. Actually I'm not even sure if it's supported out of the box natively (iOS/Android)

**Comment by remigijusbalc** [comment]
Hey! That's pretty easy to implement with existing listener. This listener returns these properties: 
*   selectedTabIndex: number;
*  unselectedTabIndex: number;
So, if unselected tab is same as selected and they match for example Tab A - you can scroll or do whatever you need to

**Comment by error-try-again** [comment]
> What would be the reason for a double tap? It is a _very_ uncommon gesture to double tap on a tab bar item. Actually I'm not even sure if it's supported out of the box natively (iOS/Android)

Perhaps I can comment on two potential use cases. I discovered this post as I was looking to implement a method that focuses on my searchbar when the user double taps, making my app more accessible. The other use case was for nested non-search screens to go directly up to the top of the stack rather than pressing the back button in the top left.

**Comment by timothyerwin** [comment]
> Hey! That's pretty easy to implement with existing listener. This listener returns these properties:
> 
> * selectedTabIndex: number;
> * unselectedTabIndex: number;
>   So, if unselected tab is same as selected and they match for example Tab A - you can scroll or do whatever you need to

I'm not sure that's really a double tap...sure it would handle the case, but correct me if I am wrong, but if you tapped on the same tab 30 seconds later it would count as a double tap?

**Comment by timothyerwin** [comment]
> What would be the reason for a double tap? It is a _very_ uncommon gesture to double tap on a tab bar item. Actually I'm not even sure if it's supported out of the box natively (iOS/Android)

well everything is uncommon until someone does it :) I'm looking for this behavior now
