### ISSUE TITLE
ResetTo breaks push functionality, issue happening on react-native-gifted-chat

### ISSUE THREAD

**Issue by razvanpaul** [wix/react-native-navigation#691]
I use this amazing library in coalition with react-native-gifted-chat. It seems to work fine in some cases, even if I had to implement some handlers.

I have the following: Homepage, Drawer, Match and finally the Chat. At the initial moment of the app, I present the homepage with the drawer in the left side, where I choose the Match page. The Match is instantiated using deep links, onNavigatorEvent and this.props.navigator.resetTo.

Finally, when an item is tapped in the Match page, I want the app to go to the Chat page, but all I get is this:
![simulator screen shot 27 jan 2017 15 01 27](https://cloud.githubusercontent.com/assets/8782666/22381186/4df78d64-e4c9-11e6-8ddf-c2137eccb691.png)

I use this.props.navigator.push to do it, but I've also tried this.props.navigator.showModal, nothing worked.
Observation: Everything is good when I firstly instantiate the Match page, instead of the Homepage. Apparently something is not ok with react-native-navigation and deep linking here.

Can you tell me any solution please?

* React Native Navigation version: 2.0.0-experimental.188
* React Native version: 0.39
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6

**Comment by razvanpaul** [comment]
Update

Apparently, this is the difference when the Match page is firstly instantiated and when it is not:

Instantiated:
![simulator screen shot 27 jan 2017 18 58 52](https://cloud.githubusercontent.com/assets/8782666/22381210/611a04b2-e4c9-11e6-8ac3-9eebfd0c51a9.png)

Not Instantiated:
![simulator screen shot 27 jan 2017 19 02 49](https://cloud.githubusercontent.com/assets/8782666/22381220/68cac58e-e4c9-11e6-8496-f40b7064044f.png)

**Comment by indivisable** [comment]
This may help: 
https://github.com/wix/react-native-navigation/issues/399

**Comment by razvanpaul** [comment]
@indivisable Thanks for the tip, but I've already tried that. Didn't work.

**Comment by indivisable** [comment]
I am using gifted-chat with no issues, however not deep linking... I simple have a tabbed application and use showModal to show the chat screen. Are you using singlePageApp?

**Comment by guyca** [comment]
@razvanpaul I don't have any experience with gifted-chat but it seems that it is part of the hierarchy. fwiw, We also use this component and didn't have any issues with it.

**Comment by razvanpaul** [comment]
@indivisable Yes, this is how I instantiate the app:

```
  Navigation.startSingleScreenApp({
    screen: {
      screen: constants.kSMPlaygroundScreen,
      title: undefined,
      navigatorStyle: navigationBarStyle
    },
    drawer: {
      left: {
        screen: constants.kSMDrawerScreen
      },
      disableOpenGesture: true
    }
  });
```

@guyca I know, it works in most of the circumstances, but apparently here we have a problem.

**Comment by guyca** [comment]
Can you try to debug the [native code](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java#L156) and see where/why it breaks?

From what you've described nothing stands out to me, everything seems right.

**Comment by razvanpaul** [comment]
The bug occurred on iOS, but I am trying to configure Android right now to check if it happens there too. If not, how could I debug the [native code](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/layouts/SingleScreenLayout.java#L156) for iOS?

**Comment by razvanpaul** [comment]
@guyca I'm trying for 3 hours already to run on Android, but I get exactly the #334 behaviour. No logs, nothing, just updated to 0.40, it's a plain, blank white page!

**Comment by razvanpaul** [comment]
Here it is a video with the issue:
https://www.dropbox.com/s/nmzzyi6d34dxyn6/recording.mov?dl=0

**Comment by guyca** [comment]
Hey
We're using RN 0.39.2 - might be good to use it as well in your app (at least for now) just to eliminate a big unknown.
If you're getting a white screen on Android - usually it's a simple issue in `index.android.js`. It happened to be a few days ago in a personal project, I'm now it's frustrating. if your not getting any logs - that means `startSingleScreenApp` wasn't called. I suggest you add a static log at the top of the file - just to make sure it's parsed, then progress from there.

Can you tell me where you're calling `resetTo` from? Is it possible you're calling `resetTo` from the sideMenu or using the sideMenu's navigator?

**Comment by razvanpaul** [comment]
I called `resetTo` from the PlaygroundComponent, so the navigator is definitely not the sidemenu's one, but maybe I don't do something well. This is the code which is executed when I tap the "Match" row (the second one) from the video above.

```
  onNavigatorEvent(event) {
    console.log(event);
    if (event.type == 'NavBarButtonPress') {
      if (event.id == 'closeButton') {
        this.didTapDrawerButton();
      }

      if (event.id == 'filterButton') {
        this.didTapFilterButton();
      }
    }
    if (event.type == 'DeepLink') {
      this.props.navigator.resetTo({
        screen: event.link,
        title: undefined,
        animated: false,
        navigatorStyle: navigationBarStyle
      });
    }
  }
```

**Comment by guyca** [comment]
Ping me on [discord](https://discord.gg/DhkZjq2)

**Comment by razvanpaul** [comment]
Apparently, all this mess was just an ugly bug caused by some mock data. More specifically, the following function of the react-native-gifted-chat example:

```
  componentWillMount() {
    this._isMounted = true;
    this.setState(() => {
      return {
        messages: require('./data/messages.js'),
      };
    });
  }
```

I simply removed the './data/messages.js' import and added data from the server. Then, it simply worked. This is very strange and I don't really know yet the reason for this, but currently the solution seems to transition to "production" environment when using react-native-navigation in coalition with react-native-gifted-chat. Thank you @guyca one more time!

**Comment by razvanpaul** [comment]
This was actually an issue caused by a react-native bug, triggered by react-native-navigation and implemented in react-native-gifted-chat.

To be honest with you, I still don't believe I sorted it out. Please, take a look [here](https://github.com/FaridSafi/react-native-gifted-chat/pull/355) for the solution.

Hope it helps.
