### ISSUE TITLE
System Item Icons not appearing in Top Bar

### ISSUE THREAD

**Issue by twelvearrays** [wix/react-native-navigation#6911]
## 🐛 Bug Report

Upgrading from 7.6.0 to 7.7.0 or above, top bar buttons that use the system item option for their icons on iOS are not appearing in Top Bar.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

Buttons visible in 7.6.0 upgrading to 7.84 causes system item icons not to appear.  Using the icon option still shows the custom icons.  Only system items are not working.

```
                          rightButtons: [
                            {
                              id: 'compose',
                              systemItem: 'compose',
                              color: theme.main,
                            },
                            {
                              id: 'bookmarks',
                              component: {
                                id: 'bookmarkButton',
                                name: 'Bookmark',
                              },
                              color: theme.main,
                            },
                          ],
```
### 7.6.0
![image](https://user-images.githubusercontent.com/11466453/104947577-94617400-5981-11eb-9914-b0a4736e27e3.png)

### 7.8.4
![image](https://user-images.githubusercontent.com/11466453/104947033-ac84c380-5980-11eb-80f0-e2bcf907812d.png)

**Comment by jinshin1013** [comment]
I haven't tried to reproduce it on the Playground app but encountered the same problem in the app I am working on. Can confirm as @twelvearrays said, system icon appears on `7.6.0` but do not from `7.7.0` and up.

**Comment by danilobuerger** [comment]
There was some large button work in https://github.com/wix/react-native-navigation/pull/6851 by @yogevbd. Maybe a regression there?
