### ISSUE TITLE
EXC_BAD_ACCESS (RNNComponentViewController)

### ISSUE THREAD

**Issue by bneigher** [wix/react-native-navigation#6922]
## 🐛 Bug Report

Unfortunately this bug is non-reproducable - but occurs frequently enough to have been caught in my release cycle.  All I have in my logs are:

```
EXC_BAD_ACCESS (RNNComponentViewController)
completed > XTUM > Attempted to dereference garbage pointer 0x5fce568870
```

I just noticed it happen a few seconds after popping screens.  Seems to happen when popping from a view with a lot of memory (camera view rendering several images)

This is either due to a bug introduced in a newer version of react-native or react-native-navigation as I just upgraded both to be latest stable.  I'll try downgrading RNN to see if it goes away and report my findings here.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

I'll try to figure this one out 

## Your Environment

Testflight.  On Device.

- React Native Navigation version: 7.8.4
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): iPhone XS, iPhone 6S

**Comment by danilobuerger** [comment]
Feel free to reopen once you have a reproduction. There is really nothing we can do right now.

**Comment by marcshilling** [comment]
This crash report pops up for my production app too but I'm not sure if its an actual concern. Users have not been reporting crashes, and from what I can gather the app seems to always be in a backgrounded state when it occurs, so it may not even be something users are aware of.
