### ISSUE TITLE
Setting rightButtons with mergeOptions stopped working on iOS after 7.6.0

### ISSUE THREAD

**Issue by rosskhanas** [wix/react-native-navigation#6924]
## 🐛 Bug Report

`Navigation.mergeOptions` stopped working after 7.6.0 Not sure if it is broken since 7.7.0 or 7.8.0.

```
Navigation.mergeOptions(componentId, {
      topBar: {
        rightButtons: [{"enabled": true, "id": "button_id", "systemItem": "edit"}],
        title: {
          text: "Test",
        },
      },
    });
```

Given example updates the title, but does not set the right button. On Android all work well.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. Open ant page with no right buttons.
2. Try to use `mergeOptions` in `componentDidAppear` or/and in `componentDidUpdate` to add the right button.

## Expected behavior

`Navigation.mergeOptions` should add/update/remove rightButtons depending on its value.

## Actual Behavior

It does not add the right buttons on iOS.

## Your Environment

- React Native Navigation version: 7.8.4
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Debug

**Comment by jinshin1013** [comment]
@rosskhanas Does it work if you set in `static options`?

**Comment by rosskhanas** [comment]
@jinshin1013 no, it does not. It sents `title` textx same as `mergeOptions`, but not `rightButtons`.
