### ISSUE TITLE
Original image on Bar Button Item

### ISSUE THREAD

**Issue by rodribech20** [wix/react-native-navigation#6934]
Hello, I updated RNN (I was using v2.27.9) to v7.8.4 and I noted that the barButtonItem does not have the original color, it has blue color but the v2 I could leave the icon with original color. I was checking on documentation if there was about that but I did not find nothing. 
I was reviewing the code on this file: `RNNUIBarButtonItem`
```
- (instancetype)initWithIcon:(RNNButtonOptions *)buttonOptions
                     onPress:(RNNButtonPressCallback)onPress {
    UIColor *tintColor = [buttonOptions.color withDefault:nil];
    UIImage *iconImage = buttonOptions.icon.get;
    [self applyOptions:buttonOptions];
    self = [super initWithImage:tintColor ? [iconImage withTintColor:tintColor] : iconImage
                          style:UIBarButtonItemStylePlain
                         target:self
                         action:@selector(onButtonPressed:)];
    self.onPress = onPress;
    return self;
}

```

I think iconImage should be ` [iconImage imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal]` if tintColor is nil.

I leave 2 screenshot with V2 and V7 about barButtonItem:
V2:
![Screen Shot 2021-01-27 at 09 36 25](https://user-images.githubusercontent.com/823023/105991936-2bfe4b00-6083-11eb-842b-b83b771f70d6.png)

V7:
![Screen Shot 2021-01-27 at 09 33 14](https://user-images.githubusercontent.com/823023/105991565-b4302080-6082-11eb-85b6-ae1c5e78d01f.png)

Thanks

**Comment by simonmitchell** [comment]
This is not a general usage or support question! We're having same issue :(

**Comment by yogevbd** [comment]
We need to add `disableTintColor` option for buttons that will render the image like @rodribech20 suggested. (`[iconImage imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal]`)

@simonmitchell @rodribech20 currently we don't have enough capacity and it might take a while to get to this task. it's really simple though and it would be awesome if one of you can implement it. 🙏

**Comment by guyca** [comment]
@simonmitchell You know how to reach us 😉

**Comment by simonmitchell** [comment]
@yogevbd @guyca if you can point me to the right place I shall make it happen!! Library has changed a bit since I last contributed 😝 Unfortunately the nature of my job (Agency work) means I might not be on React Native projects for months/years at a time!

**Comment by simonmitchell** [comment]
I'll try and work it out myself anyhow of course, but if you could point that would be amazing ☺️

**Comment by simonmitchell** [comment]
I'm clearly having a moment (Battling with Bitrise to get a build working again). The code area I'm guessing is where @rodribech20 found it? I'll see what I can do on my next support day or when I get some free time available outside of work hours :D
