### ISSUE TITLE
Adding an id to a backbutton makes it invisible

### ISSUE THREAD

**Issue by Andarius** [wix/react-native-navigation#6935]
## 🐛 Bug Report

Adding an id to a back button make it invisible even if `visible: true`

## To Reproduce

https://github.com/Andarius/react-native-navigation/tree/issue/topbarBackBtn

1. Press the "Options" button
2. Press the "Push" button

## Expected behavior

The back button should be visible

## Actual Behavior

The back button is not visible

## Your Environment

- React Native Navigation version: 7.8.1
- React Native version: 0.63
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Debug

## Reproducible Demo

https://user-images.githubusercontent.com/5070712/106069526-f5681500-6102-11eb-835d-072e2fa118d3.mp4

**Comment by mrousavy** [comment]
I noticed you also put a "hide back button" and "show back button" callbacks in the repro, do those do anything?

**Comment by Andarius** [comment]
Yes they are to test another issue I was initially debugging: if you hide thé backbutton then show it again, no event is dispatch when you press it.
Maybe these two issues are related

**Comment by yogevbd** [comment]
@Andarius Why are you changing the back button `id`?

**Comment by Andarius** [comment]
I set it with `Navigation.setDefaultOptions` for when I need to listen to it (eg: call `onDone` function )
