### ISSUE TITLE
Multiple Stacked Views (Lightboxes/Modals ontop of eachother)

### ISSUE THREAD

**Issue by indivisable** [wix/react-native-navigation#694]
Is it possible to show stacks of lightboxes? I am trying to achieve this effect:

![cards](https://cloud.githubusercontent.com/assets/22860891/22395220/a5193b64-e4fc-11e6-893c-8b0ab341527d.gif)

Any feedback would be helpful, also I think t**his would be great feature for the react-native-navigation**. I was going to do this by displaying lightboxes with a slight marginTop offset and possibly scale. May end up writing some Bridge code to the library shown above (https://github.com/jobandtalent/CardStackController).

Much thanks!

**Comment by guyca** [comment]
This is a great idea. I think it's possible, just keep in mind LightBox is still not implemented on Android. 😢

**Comment by RobertBiehl** [comment]
I think the Lightbox implementation needs to be changed first. Currently Modal screens and the Lightbox server similar purposes.
The Lightbox could be implemented using modal screens. (Even with the blur animation etc.) Then the wouldn't be a problem to stack them.

Moving around between stacked cards by swiping is a whole new can of worms though.

**Comment by guyca** [comment]
Will be resolved for v2 in #3057
