### ISSUE TITLE
YogaKit/YogaKit.modulemap' not found Xcode 12.4

### ISSUE THREAD

**Issue by kubilaytural** [wix/react-native-navigation#6942]
Description

I create a new app using react native. When I try to run the archive using Xcode I get the following error and the app doesn't archive.

 module map file '/Users/kubilaytural/Library/Developer/Xcode/DerivedData/passerMobileApp-fhpbfuxtqdjloddnafpzbplvrsxk/Build/Intermediates.noindex/ArchiveIntermediates/passerMobileApp/BuildProductsPath/Release-iphoneos/YogaKit/YogaKit.modulemap' not found

I have tried to google this but have been unable to find a way to fix it, is there any way this can be fixed?

**The problem goes away when removing react native navigation from the project.**
(I have this problem with all my projects. Possibly related to Xcode)

    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-navigation": "^7.8.4"

System:
macOS version: Big Sur 11.1
**Xcode version:** 12.4

<img width="867" alt="Screen Shot 2021-01-31 at 22 29 49" src="https://user-images.githubusercontent.com/23127307/106395550-db387a80-6413-11eb-89d7-15276692826f.png">

<img width="605" alt="Screen Shot 2021-01-31 at 22 30 52" src="https://user-images.githubusercontent.com/23127307/106395577-002ced80-6414-11eb-95e2-7891e91dc3ad.png">

**Comment by kubilaytural** [comment]
@yogevbd @swabbass @mrousavy @mateioprea @JasonXiang2014 @Andarius pls help?

**Comment by kubilaytural** [comment]
I was able to solve my problem by synchronizing the xcode development target and pod target version.

**Comment by hannahlf** [comment]
> I was able to solve my problem by synchronizing the xcode development target and pod target version.
@kubilaytural 
How do you synchronize those?

**Comment by BulletButcher88** [comment]
@kubilaytural I have the same question as @hannahlf.

Are you adding a pod file into the Build Phases > Link Binary with Libraries?
Please share details
