### ISSUE TITLE
doing startSingleScreenApp again after first launch crashes the app

### ISSUE THREAD

**Issue by vivekparekh8** [wix/react-native-navigation#695]
### Issue Description

WindowLeak exception from Android.

<img width="440" alt="screen shot 2017-01-28 at 1 57 03 am" src="https://cloud.githubusercontent.com/assets/9562838/22395266/06a6960a-e4fe-11e6-93d0-9ebf71bed32f.png">

### Environment
* React Native Navigation version: 127 experimental.
* React Native version: 0.34
* Platform(s) (iOS, Android, or both?): Android
* Device info Simulator/Device - Any 6.0 Debug

**Comment by guyca** [comment]
Are you able to reproduce this in the example project as well? There's a "Start singleScreenApp" button in the first tab iirc

**Comment by vivekparekh8** [comment]
@guyca thanks for the quick response.
not in the example project

**Comment by vivekparekh8** [comment]
any insight guys

**Comment by guyca** [comment]
Are you calling startApp from modal?

**Comment by vivekparekh8** [comment]
Yes. there is modal and on pressing ok we are restarting the app 'calling startApp' @guyca

**Comment by guyca** [comment]
A workaround would, probably, be dismissing the modal before calling startApp.

**Comment by vivekparekh8** [comment]
I tried calling navigator.dismissAllModals in componentWillUnmount but that also didn't help

**Comment by vivekparekh8** [comment]
actually the thing is two modals are opening instead of one as I have logic in componentDidMount()
which getting triggered twice. So what I think is the first modal is not closed (probably not having any reference as already in background)

**Comment by guyca** [comment]
I think calling `Navigation.dismissAllModals()` from your action - then `startApp` from unmount will work.

**Comment by vivekparekh8** [comment]
@guyca : still having this issue. I have tried to replace my modal component.
But that didn't help. ```Navigation.dismissAllModals()``` also didn't work

**Comment by vivekparekh8** [comment]
https://github.com/wix/react-native-navigation/issues/300

**Comment by guyca** [comment]
@vivekparekh8 Since this use case is working fine for us, we'll need more info.
Few things, you're running a pretty old version on react native, maybe consider updating?
Second, Are you using react native's [Modal](https://facebook.github.io/react-native/docs/modal.html)?

**Comment by Crash--** [comment]
I had, I think, a similar issue. Not with startApp() but with dismissAllModals() not closing my modals. In fact, the dismissAllModals() was called twice in a very short time and nothing happens. My modals were always visible. I just added a check to launch it once, and it works as expected. Modals were closed. 

Don't know if it related to your issue, but since you seems to call showModal() twice, maybe you call dismissModal twice also. hope it can help.

**Comment by vivekparekh8** [comment]
@guyca Yes, I am using react native's Modal

**Comment by guyca** [comment]
@vivekparekh8 well you should use RNN's modal. We never tested RNN with RN's modal implementation.

**Comment by die20** [comment]
I wasn't using RN's modal but I was getting the same error. My issue was resolved by removing this from the FlatList I had in the component being loaded: `onEndReachedThreshold={Platform.OS === 'ios' ? 0 : 1}`
