### ISSUE TITLE
Bottom Tab Navigator wrong behaviour

### ISSUE THREAD

**Issue by Yadro** [wix/react-native-navigation#6950]
## 🐛 Bug Report

I set Bottom Tab Navigator, and it works when I navigate on the screen, which I didn't navigate before, but when I go back, the screen doesn't change. What I did wrong?

## To Reproduce

```js
import { NavigationContainer } from '@react-navigation/native';
const Tab = createBottomTabNavigator();

export const Navigator = () => {
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Screen1">{() => <Screen text="Screen1" />}</Tab.Screen>
        <Tab.Screen name="Screen2">{() => <Screen text="Screen2" />}</Tab.Screen>
        <Tab.Screen name="Screen3">{() => <Screen text="Screen3" />}</Tab.Screen>
      </Tab.Navigator>
    </NavigationContainer>
  );
};
```
## Your Environment

- React Native Navigation version: 
  - "@react-navigation/bottom-tabs": "5.11.7",
  - "@react-navigation/native": "5.9.2",
  - "@react-navigation/stack": "5.14.2",
- React Native version: 0.63.2
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Android 11, Debug

## Reproducible Demo

![Recording 21-02-04 11-34-56](https://user-images.githubusercontent.com/3994873/106867145-4f0da800-66de-11eb-888c-da54c6386a3c.gif)

**Comment by mateioprea** [comment]
You are on the wrong repo.
