### ISSUE TITLE
Shared Element Broken in Android with latest version 7.9.0

### ISSUE THREAD

**Issue by FawadMahmood** [wix/react-native-navigation#6957]
I have tried every possible way to use it on android, it was working fine on IOS with the latest release, however when downgraded to 7.8.4 same code works well now.

 animation.animations.push = {
        ...animation.animations.push,
        sharedElementTransitions: [
          {
            fromId: key,
            toId: `${key}dest`,
            interpolation: {
              type: "spring",
              ...{ mass: 3, damping: 500, stiffness: 200 },
            },
          },
        ],
      };

      // if (Platform.OS === "ios") {
      animation.animations.pop = {
        ...animation.animations.pop,
        sharedElementTransitions: [
          {
            fromId: `${key}dest`,
            toId: key,
            interpolation: {
              type: "spring",
              ...{ mass: 3, damping: 500, stiffness: 200 },
            },
          },
        ],
      };

**Comment by swabbass** [comment]
Hey @FawadMahmood , thx for the report.

can you please share a reproducible demo of a minimal project that has the specified version of RNN you are using, including the flows?

**Comment by FawadMahmood** [comment]
Hello, Yes it’s here https://github.com/FawadMahmood/react-native-navigation-bug, there’s no need of any extra work to reproduce, it’s a very basic example with default navigation. Please have a look.
