### ISSUE TITLE
How  to add image in status bar My code Here

### ISSUE THREAD

**Issue by suzonice15** [wix/react-native-navigation#6967]
Navigation.setDefaultOptions({
  statusBar: {
    backgroundColor: 'red'
  },
  topBar: {
    title: {
      color: 'white'
    },
    backButton: {
      color: 'white'
    },
    background: {
      color: 'red'
    }
  },
  bottomTab: {
    fontSize: 14,
    selectedFontSize: 14,
	backgroundColor:'red'
  }
});

**Comment by mrousavy** [comment]
You cannot add images to the StatusBar. If you're searching for adding images to the topBar, take a look [at those docs](https://wix.github.io/react-native-navigation/7.7.0/api/options-imageResource/#imageresource)

**Comment by fawad-khalil** [comment]
@mrousavy this is a basic functionality and is required by the many apps. We also need to implement such functionality in our UI. But we don't want to switch our navigator library for such a small requirement.
