### ISSUE TITLE
Size of image used for titleImage

### ISSUE THREAD

**Issue by indivisable** [wix/react-native-navigation#698]
I am trying to figure out how to size the titleImage, does anyone know the best size for the png? It seems that the image gets scaled and pixelated, so I hope if I make to match size it will look crisp. Also how does it handle @1x/@2x for different phone resolutions.

```
tabs: [
      {
        title: "NONE",
        titleImage: require('../assets/logos/test.png') <--- What is best size?
...
```
Best way to solve seems to be setting a fixed size in Objective-C:  https://github.com/wix/react-native-navigation/issues/647. It may be nice to expose this size/option to use a fixed image size.

**Comment by gfugfu** [comment]
^ This would be nice to know. I apologize in advance if it is already in the docs.
