### ISSUE TITLE
bottom tab tap don't pop to root on android

### ISSUE THREAD

**Issue by ludwig-pro** [wix/react-native-navigation#6981]
## 🐛 Bug Report

iOS and Android don't have the same behavior when you navigate inside a stack with bottom tabs and tap the active tab.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

yep !

## To Reproduce
1. navigate inside a sub screen of a stack ( so have 2 screens inside the stack, the root and a second one)
2. tap on the current active tab

## Expected behavior

When you are inside a stack, I expect the tap on active bottom tab to popToRoot() 

## Actual Behavior

when you are inside a stack,  and tap on active bottom tab 
- ✅ on iOS it's worked,  popToRoot() 
- ❌on android... nothing append 

<br />
**ANDROID**
<br />

https://user-images.githubusercontent.com/62896243/108593337-53d78a80-7373-11eb-91a5-2ed9e7ca600f.mp4

<video width="350" controls="controls">
  <source type="video/mp4" src="https://user-images.githubusercontent.com/62896243/108593337-53d78a80-7373-11eb-91a5-2ed9e7ca600f.mp4"></source>
  <p>Your browser does not support the video element.</p>
</video>

<br />
**IOS**
<br />

https://user-images.githubusercontent.com/62896243/108594067-01e53380-7378-11eb-9779-47afe86cbb44.MP4

<video width="350" controls="controls">
  <source type="video/mp4" src="fhttps://user-images.githubusercontent.com/62896243/108594067-01e53380-7378-11eb-9779-47afe86cbb44.MP4"></source>
  <p>Your browser does not support the video element.</p>
</video>

## Your Environment

```sh
 "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-navigation": "^7.10.0"
  },

```
- Platform: Android
- Device info: tested on physical device, debug & release

## Reproducible Demo

https://github.com/ludwig-pro/react-native-navigation-debug

1. Tap on the setting tab
2. Tap on the button "push new settings screen"
3. Tap on the current tab - Settings

i have found a workaround by listening event

```js
  React.useEffect(() => {
    const listener = async (event) => {
      await Navigation.popToRoot('THE_HOME');
    };
    const unsubscribe = Navigation.events().registerBottomTabSelectedListener(
      listener,
    );
    return () => {
      unsubscribe.remove();
    };
  }, []);
  ``` 

you can test it on the home stack:

1. Tap on the Home tab
2. Tap on the button "push new screen"
3. Tap on the current tab - Home -> it's pop to root :)

**Comment by nericode** [comment]
Same issue

**Comment by SeamusY** [comment]
@swabbass 

Index.js

```
Navigation.setRoot({
  root: {
    bottomTabs: {
      id: 'BottomTabsId',
      children: [
        {
          stack: {
            children: [{
              component: {
                name: 'QrCode',
                options: {
                  bottomTab: {
                    fontSize: 12,
                    text: 'Children1',
                  }
                }
              }
            }],
          }
        },
        {
          stack: {
            children: [{
              component: {
            name: 'Doc',
            options: {
              bottomTab: {
                text: 'Children2',
                fontSize: 12,
              }
            }
          }}],
        },
      },
      {
        stack: {
          children: [{
            component: {
          name: 'Profile',
          options: {
            bottomTab: {
              text: 'Children3',
              fontSize: 12,
            }
          }
        }}],
      },
    }
      ],
    }
  }
});
```

Children3:
```
export default class Children3 extends React.Component {
  constructor(props) {
    super(props);
  }
  
  editProfile = () => {
    Navigation.push(this.props.componentId, {
    component: {
        name: 'Edit',
        options: {
          bottomTabs: { visible: false, drawBehind: true, animate: true },
            topBar: {
                title: {
                    text: 'Edit '
                }
            }
        }
    }
  })};

  changePassForm = () => {
    Navigation.push(this.props.componentId, {
    component: {
        name: 'Pass',
        options: {
          bottomTabs: { visible: false, drawBehind: true, animate: true },
            topBar: {
                title: {
                    text: 'Push Navigation 1'
                }
            }
        }
    }
  })};

  render(){
    return (
      <NativeBaseProvider>
        <Center>
          <VStack space={4} safeAreaTop={16} bg="gray.200" px="32">
            <Heading textAlign="center" mb="8">
              Profile
            </Heading>
            <Pressable onPress={this.editProfile}>
              <Box textAlign="left" bg="lightBlue.100" >
                Edit 
              </Box>
            </Pressable>
            <Pressable onPress={this.changePassForm}>
              <Box textAlign="left" bg="lightBlue.100">
                Change
              </Box>
            </Pressable>
          </VStack>
        </Center>
      </NativeBaseProvider>
    );
};
}
```

Push Navigation 1:

```
import React from "react";
import { NativeBaseProvider, Center, Stack, FormControl, Input, Button } from "native-base";
import Auth from "@aws-amplify/auth";
import { Navigation } from "react-native-navigation";

export default class Edit extends React.Component {
    constructor(props) {
        super(props);
    }

      getOut = () => {
        Navigation.popTo(this.props.componentId, {
            component: {
                name: "Profile"
            }
        })
      }

    render() {
        const { isBusinessUser } = this.state
        return (
            <NativeBaseProvider>
                <Center flex={1} px={8}>
                    <Stack space={4}>
                        <Button onPress={this.getOut}>Get out</Button>
                        <Button onPress={()=> { console.log(Navigation)}}>Print</Button>
                    </Stack>
                </Center>
            </NativeBaseProvider>
        )
    }
}
```

**Comment by svbutko** [comment]
@SeamusY the issue described here covers the functionality of bottom tab tap specifically, I'd rather create a separate issue for your problem rather than have discussion in already closed one.

**Comment by jbseppanen** [comment]
I'd like to know the status of the original issue here.  It appears to be closed but also I see evidence of it being rolled back.  I have cloned the original demo provided by @ludwig-pro and updated to the latest available version of `react-native-navigation` [here](https://github.com/jbseppanen/react-native-navigation-debug).  I am still seeing the same issue if I comment out the workaround.

**Comment by swabbass** [comment]
Hey all, sorry for the inconvenience, Android should be aligned with iOS and vice versa (whenever possible).

Just to clear things up, what you are trying to achieve is clicking on a bottom tab will clear its stack till root, am I getting it?

If that is the case, then soon (next week I think) will have a PR for it.

**Comment by jbseppanen** [comment]
That is correct.  It works as expected on ios but not on Android.

**Comment by jbseppanen** [comment]
> But first, did you try to pass popToRoot on bottomTabOptions? what is #7239 fix.

I'm not sure what you are asking here.  The workaround using `registerBottomTabSelectedListener` does work, but I'm hoping for a fix in the library if that's feasible.

**Comment by swabbass** [comment]
@jbseppanen, I'm taking about the PR #7239 that closed this issue, which added support for what you described, what is missing is to add `popToRoot: true` for each tab you want in the **bottomTabOptions**

**Comment by swabbass** [comment]
what i did is something like this:
```
  {
            stack: {
              id: 'LayoutsStack',
              children: [
                {
                  component: {
                    id: 'LayoutsTabMainComponent',
                    name: 'Layouts',
                  },
                },
              ],
              options: {
                bottomTab: {
                  popToRoot: true, <------ADD THIS
                  id: 'LayoutsBottomTab',
                  text: 'Layouts',
                  icon: require('../img/layouts.png'),
                  selectedIcon: require('../img/layouts_selected.png'),
                  testID: testIDs.LAYOUTS_TAB,
                },
              },
            },
```
https://user-images.githubusercontent.com/7227793/146261552-933b96bf-dd7d-4573-b1c4-f5dbc5d1087e.mov

**Comment by swabbass** [comment]
@jbseppanen adding popToRoot solves your issue, then we need to reclose this. can you confirm?

**Comment by jbseppanen** [comment]
OK, that makes sense now.  I tried it and it does indeed solve the problem.  Is it intentional for this to be Android only?  iOS does not seem to regard that prop at all but it does pop to root as I want.

**Comment by swabbass** [comment]
By default ios implement its native bottom tabs behaviour, I think since the opposite was on android (tap won't popToRoot) we might need to respect such option, on ios if that is needed, which is to disable popToRoot, but for now, it seems that this is a wanted behaviour, we might invert it to be true by default.

Thanks :]

**Comment by jbseppanen** [comment]
Thank you for walking me through this and so promptly.  Much appreciated.

**Comment by swabbass** [comment]
> Thank you for walking me through this and so promptly. Much appreciated.

You are welcome!!
