### ISSUE TITLE
react-native-smart-barcode setup (android)

### ISSUE THREAD

**Issue by lodev09** [wix/react-native-navigation#699]
### Issue Description

I need to setup [react-native-smart-barcode](https://github.com/react-native-component/react-native-smart-barcode) to my application for android. It's currently conflicting given that this package modifies default react native inits.

I looked at the guide [here](https://github.com/wix/react-native-navigation/wiki/Android#activity-lifecycle-and-onactivityresult) and managed to compile it but I'm getting a crash as I'm not sure if I did it correctly on setting up the "MainActivity" as instructed in the 3rd party plugin.

### Steps to Reproduce / Code Snippets / Screenshots
See android installation of `react-native-smart-barcode` (link above)

My current MainApplication.java:
```java
// https://github.com/wix/react-native-navigation/wiki/Android
// https://github.com/react-native-component/react-native-smart-barcode

package com.ezserve;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import com.reactnativecomponent.barcode.RCTCapturePackage;
// import com.reactnativenavigation.RnnPackage;
import com.RNFetchBlob.RNFetchBlobPackage;
import io.realm.react.RealmReactPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
// import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.reactnativenavigation.NavigationApplication;

// https://github.com/wix/react-native-navigation/issues/629
import com.reactnativenavigation.controllers.ActivityCallbacks;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends NavigationApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          // new MainReactPackage(),
            // new RCTCapturePackage(),
            // new RnnPackage(),
            new RNFetchBlobPackage(),
            new RealmReactPackage(),
            new VectorIconsPackage()
      );
    }
  };

  private MainActivity mainActivity; // ?????

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);

    setActivityCallbacks(new ActivityCallbacks() {
      public void onActivityCreated(MainActivity activity) {
        mainActivity = activity; // ????
      }
    });
  }

  @Override
  public boolean isDebug() {
      // Make sure you are using BuildConfig from your own application
      return BuildConfig.DEBUG;
  }

  // @NonNull
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
      // Add the packages you require here.
      // No need to add RnnPackage and MainReactPackage
      return Arrays.<ReactPackage>asList(
          new RCTCapturePackage(mainActivity), // ?????
          new RNFetchBlobPackage(),
          new RealmReactPackage(),
          new VectorIconsPackage()
      );
  }
}

```

NOTE: app will run fine (compile/no crash) if I remove the setup related to `RCTCapturePackage`

---
### Environment
* React Native Navigation version: https://github.com/dcgoss/react-native-navigation.git (fixed RN 0.40 ios headers)
* React Native version: 0.40
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Android 6 Debug

I'm just new with React native and haven't had any experience on Android native development so bare with me!
Any help would be much appreciated, thank you!

**Comment by guyca** [comment]
`onActivityCreated` is called after `createAdditionalReactPackages`, so you're essentially instantiating RCTCapturePackage with null.

The entire init phase of that library is wrong, it requires you to call `setReactNativeHost` from your activities `onCreate` and override `getPackages` from there as well. I suggest you avoid this library.

**Comment by lodev09** [comment]
Thanks. I guess I'll have to find another barcode scanner package. I see wix has the camera kit but no barcode support :(

Do you have any suggestion?

**Comment by guyca** [comment]
Unfortunately I'm not familiar with any barcode libraries (doesn't mean there aren't others), sorry.

**Comment by lodev09** [comment]
No problem @guyca . thanks for the tip :)
