### ISSUE TITLE
IOS - Black screen - Unbalanced calls to begin/end appearance transitions for RNNSplashScreen

### ISSUE THREAD

**Issue by caciobanita** [wix/react-native-navigation#6990]
## 🐛 Bug Report
Application wont run on iOS, black screen after storyboard is loaded and i get this error:

021-02-25 10:10:28.680322+0200 TestApp[679:203188] Unbalanced calls to begin/end appearance transitions for <RNNSplashScreen: 0x105310350>.

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

(Write your answer here.) YES

## To Reproduce

(Write your steps here:)

react-native run-ios

## Expected behavior
The application should register my first screen and then be visible.

(Write what you thought would happen.)

## Actual Behavior
Black screen.

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- React Native Navigation version: 7.11.0
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): IOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator 12.7 / Device - 13.4

## Reproducible Demo

(Paste the link to an example repo and exact instructions to reproduce the issue.)

**Comment by francbelak** [comment]
Hi @caciobanita, I ran into the same situation today. After some debugging I found out that I was missing

```
- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge {
  return [ReactNativeNavigation extraModulesForBridge:bridge];
}
```

after an update in the AppDelegate.m.

**Comment by pdpd123** [comment]
> Hi @caciobanita, I ran into the same situation today. After some debugging I found out that I was missing
> 
> ```
> - (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge {
>   return [ReactNativeNavigation extraModulesForBridge:bridge];
> }
> ```
> 
> after an update in the AppDelegate.m.

This helped me today. thanks a lot!
