### ISSUE TITLE
iOS - Native back button is not working on iOS 12 since RNN 7.11.0

### ISSUE THREAD

**Issue by manuhook** [wix/react-native-navigation#6993]
## 🐛 Bug Report

Hi @yogevbd  ! since version 7.11.0 the native back button doesn't work anymore on iOS 12 (tested on iPhone 5s ios.12.5.1). 
By clicking on the back button clicking on the back button, the navbar disappears but there is no pop for the current screen. 

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

Just click on the native back button from a pushed screen on iOS 12.x

**Comment by manuhook** [comment]
Thank a lot @yogevbd 
However I have still an issue with  iOS 12 on RNN 7.11.1  with the back button in this particular case : 

1 - Push 2 screen
2 - On the last screen pushed, pop the screen in JS "Navigation.pop(componentId)"
3 - On the first screen pushed, the native back button is not working (same behavior as described in this issue, the disappears but there is no pop for the current screen.

NB : its working when you push 2 screen and if you use always the native back button to go back.

Thank again !

**Comment by yogevbd** [comment]
@manuhook I couldn't reproduce it in the playground. Could you please add a reproduction? Also feel free to message me in our [discord channel](https://discord.gg/DhkZjq2)
