### ISSUE TITLE
Request - Lightbox with props

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#7]
I would like to be able to call up a Lightbox, and pass it props and/or call it like other screens, `connect`ing it to part of the redux state .

**Comment by talkol** [comment]
good point. we'll add the props. I also noticed that showLightBox isn't exposed directly in react-native-navigation at all, we'll fix this as well.

**Comment by talkol** [comment]
Added https://github.com/wix/react-native-navigation/commit/fdf215fd143a362b085d0089b025ffe68db4ad03

**Comment by adamski** [comment]
Thanks
