### ISSUE TITLE
iOS Build fails with React Native 0.27.0 

### ISSUE THREAD

**Issue by andybbtt11** [wix/react-native-navigation#70]
I have been working on a project using this lib and I am really enjoying it, however when I try to upgrade to React-Native 0.27.0, the ios build produces the following errors:

http://imgur.com/U67zHAs.

I have tried adding -lc++ to Other Linker Flags (http://stackoverflow.com/questions/37186967/undefined-symbols-for-architecture-x86-64-stdterminate-referenced-from) in the build settings which will allow it to build, but then I see these errors in ios logs:

2016-06-21 11:09:45.543 [error][tid:com.facebook.react.JavaScript] Native module cannot be null.
2016-06-21 11:09:45.558 [error][tid:com.facebook.react.JavaScript] Requiring module "144", which threw an exception.

I tried this update using a freshly cloned version of this repo. Thanks.

**Comment by artald** [comment]
New RN project indeed needs to have the `-lc++` linker flag. Make sure you add it to the traget build settings.

Regarding the logs: I have a project which uses RN-0.27.2 and I don't have similar errors. Maybe it's related to other things going on in your code? Did you see similar errors in the log before you tried to upgrade RN?

**Comment by epaga** [comment]
I did not see similar errors before I upgraded, but re-running

`pod install`

after upgrading solved the issue in my case - not sure if this might help @andybbtt11 ...
