### ISSUE TITLE
Transitioning from tabBasedApp to singleScreenApp doesn't reset the screens

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#700]
### Issue Description

In my app, when the user is logged in, he is directed to tabBasedApp. When he logs out, he is re-directed to singleScreenApp, which is basically the log in screen. I am doing so by changing the root, as described in the example project.

The problem is that after transitioning to the singleScreenApp, the previous screens/tabs probably remain on the background, because I can see some functions that belong to those screens, being called continuously (ex. setInterval).

How can I remove them from the background?

---
### Environment
* React Native Navigation version: 2.0.0-experimental.185
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): iOS, haven't tried android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/iphone 5 ? MacOS

**Comment by guyca** [comment]
Add logs to `componnentWillUnmount` - that has to be called when you switch roots. `setInterval` needs to be cancelled by you when root changes.
