### ISSUE TITLE
iOS- Custom animations on showModal not working since 7.11.0

### ISSUE THREAD

**Issue by manuhook** [wix/react-native-navigation#7005]
## 🐛 Bug Report

Since https://github.com/wix/react-native-navigation/commit/17c82b456e0d6b0ee79f3d2a1643fe14054bf069
It seems showModal animations are not working anymore

Modal Enter and Exit animation have no effect on iOS and old modal animation options for backwards compatibility is also broken.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

On playground app, set useCustomAnimations in flags.ts to true, and try to showModal with Animation (translationY, alpha etc ..)

## Expected behavior

You should see your custom animation

## Actual Behavior

No animation, only default one

## Your Environment

- React Native Navigation version: 7.11.2
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): tested on iOS
- Device info (Simulator/Device? OS version? Debug/Release?): tested on Simulator / iOS14

**Comment by svenlombaert** [comment]
Can confirm that disabling the animation isn't working anymore as well.

**Comment by guyca** [comment]
I believe this is resolved in 7.13.0-snapshot.1519
