### ISSUE TITLE
mergeOptions does not merge topBar.title deeply

### ISSUE THREAD

**Issue by robrechtme** [wix/react-native-navigation#7011]
## 🐛 Bug Report

When using `mergeOptions` on `topBar.title`, the options from `setDefaultOptions` are overridden by the RNN defaults.  

## To Reproduce

```js
Navigation.setDefaultOptions({
   topBar: {
     title: {
          alignment: 'center',
      },
    },
});

Navigation.mergeOptions(componentId, {
   topBar: {
     title: {
          text: title, // alignment is back to 'fill' on Android
      },
    },
});
```
## Expected behavior

The options from `mergeOptions` should merge deeply with the options from `setDefaultOptions`.

## Actual Behavior

Somehow, the default values are used (`alignment: 'fill'` on Android), causing the title to jump off-center when changed.

## Your Environment

- React Native Navigation version: 7.11.0
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Android 11

**Comment by danilobuerger** [comment]
Possibly fixed by #7036
