### ISSUE TITLE
BottomTab Icons disappear on android

### ISSUE THREAD

**Issue by rezasazesh** [wix/react-native-navigation#7016]
On android only randomly sometimes some of the bottom tab icons will just disappear, this image below happens randomly but I do know if you push to a screen and hide bottom tab, then from that screen once again push to a screen and show bottom tab this bug happens each time

![image](https://user-images.githubusercontent.com/45229791/110391142-2d2b8a80-80bb-11eb-996d-161c27512692.png)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

I could not find something similar reported, all other reports are about the entire bottom tab missing

## To Reproduce

One way I know for sure is:

1. Set a bottom stack navigation
2. Push to a screen with bottom tab hidden
3. From there push to a screen with bottom tab showing (having a badge on one of the icons could help to reproduce)

One more way:

1. Set a bottom stack navigation
2. Push to a screen with button to a modal
3. Open a modal with `Navigation.showModal`
4. Close modal and you will see an icon disappear

## Expected behavior

For all the icons to show all the time

(Write what you thought would happen.)

## Actual Behavior

sometime some bottom tab icons missing on android

(Write what happened. Add screenshots, if applicable.)

## Your Environment
````
 "react-native-navigation": "^7.8.4",
 "react-native": "0.63.4",
````
## Reproducible Demo

(Paste the link to an example repo and exact instructions to reproduce the issue.)

**Comment by rezasazesh** [comment]
I found out if have tabs with screen pushed and open and close a modal in another tab, those tabs with screen pushed will have their icons disappear when the modal is closed!

**Comment by rezasazesh** [comment]
Okay so turns out that iconColor and selectedIconColor properties don't work on tabs that have multiple screens after bottom tab is out of sight (either but setting it as invisible or opening a modal over them. I used to have the icons for bottom tab imported as white color then the color was over written by  bottomTab.iconColor and bottomTab.selectedIconColor, I changed the color that I was initially importing the icons as and at least the icons are now visible but when selected they don't change color because of this issue

````
 AntDesign.getImageSource('calendar', 25, '#A3A3A4'),
    Icon.getImageSource('user-o', 25, '#A3A3A4'),
    Ionicons.getImageSource('chatbubble-ellipses-outline', 25, '#A3A3A4'),
    Feather.getImageSource('edit', 25, '#A3A3A4'),
    Feather.getImageSource('menu', 25, '#A3A3A4'),

````

**Comment by solonifer** [comment]
Same issue, versions 7.12.0

**Comment by TrustDec** [comment]
Same issue, versions 7.16.0

**Comment by swabbass** [comment]
Hey @rezasazesh , Thx for reporting this issue, I'm trying to follow your steps above to reproduce the issue, meanwhile, can you kindly provide a reproducible demo (Code to run and help reproduce) as mentioned in the guideline?

**Comment by swabbass** [comment]
> I found out if have tabs with screen pushed and open and close a modal in another tab, those tabs with screen pushed will have their icons disappear when the modal is closed!

I could not reproduce that flow, see:

https://user-images.githubusercontent.com/7227793/127769937-5728d104-f5d2-4121-ac75-1c9286abcf46.mov

**Comment by ashokkumar88** [comment]
@rezasazesh How did you solve it? I am having same issue

**Comment by TrustDec** [comment]
我已经收到你的邮件啦~,表着急,待我仔细查看
