### ISSUE TITLE
Shared element transition regression on Android

### ISSUE THREAD

**Issue by nelsonprsousa** [wix/react-native-navigation#7020]
## 🐛 Bug Report

Android crashes with a native error when trying to perform the SET animation. I am confident that this was working with RNN v7.8.4.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?
Yes.

## To Reproduce

1. Clone the [project](https://github.com/nelsonprsousa/rnn-testing/tree/set-bug-example)
2. Go to `set-bug-example` branch
3. yarn android
4. Press the card to show the modal

## Expected behavior

SET should work on Android, no application crash.

## Actual Behavior

https://user-images.githubusercontent.com/8364345/110533439-e919a380-8115-11eb-96b1-e97f4b927496.mov

I was able to collect the following exception from logcat:
<img width="2179" alt="Screenshot 2021-03-09 at 20 26 27" src="https://user-images.githubusercontent.com/8364345/110533522-fb93dd00-8115-11eb-896d-df11faf406f4.png">

This is probably the source of the exception:
`type org.json.JSONArray cannot be converted to JSONObject
`
## Your Environment

- React Native Navigation version: 7.11.3
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): iPhone X / Emulator / Debug / Release

## Reproducible Demo

Clone and use this branch: https://github.com/nelsonprsousa/rnn-testing/tree/set-bug-example

**Comment by guyca** [comment]
cc @yogevbd @swabbass

**Comment by swabbass** [comment]
@nelsonprsousa thx for the report :]

before checking the demo, did you have the chance to see if what's in the demo is valid usage of the shared element, using the right options just like in the playground? you can try it before and see the examples there and see if the demo missing something or its a bug in the lib.

**Comment by nelsonprsousa** [comment]
Hi @swabbass 

I followed the example, just like in the playground. The demo I provided is pretty straightforward, it only contains 2 elements. This was working with v7.8.4, stopped working after upgrade. That's why I think it's a regression in RNN.

I believe there's a problem in some Java code regarding JSONArray vs JSONObject.

**Comment by swabbass** [comment]
@nelsonprsousa i think that PR fixed the issue :]

**Comment by nelsonprsousa** [comment]
Hi @swabbass thank you 🙏 

Any idea how can I test it? Maybe there's a way to specify a specific branch in package.json or a commit hash?

**Comment by swabbass** [comment]
> Hi @swabbass thank you 🙏
> 
> Any idea how can I test it? Maybe there's a way to specify a specific branch in package.json or a commit hash?

it was merged to master :]

**Comment by nelsonprsousa** [comment]
> > Hi @swabbass thank you 🙏
> > Any idea how can I test it? Maybe there's a way to specify a specific branch in package.json or a commit hash?
> 
> it was merged to master :]

Oh, I didn't know it was possible to target a branch in package.json 😅

Thank you, tomorrow I'll try to test it 💪

**Comment by guyca** [comment]
@nelsonprsousa You can use the `snapshot` tag or latest snapshot version `7.11.3-snapshot.1490`
