### ISSUE TITLE
Title is not displayed properly.

### ISSUE THREAD

**Issue by leralera2201** [wix/react-native-navigation#7037]
If the title is long, it covers  right buttons.
<img width="538" alt="Screenshot 2021-03-16 at 13 24 04" src="https://user-images.githubusercontent.com/58082566/111338710-cfc9a780-867f-11eb-8e90-b3b331a7ea7f.png">

**Comment by swabbass** [comment]
@leralera2201 it seems ugly, but I can explain a bit, there are apps that might want to cut it after a certain count of characters, maybe replace it with "..." or apply any other solution, so it is more like a product thing, and it could be per app, also take into consideration real use, no one would fit such long title, and if there is a case, you can change `fontSize` in the code, and have full control over each title.

**Comment by yogevbd** [comment]
@swabbass it should cut the end of the string.. look like we have a wrong calculation there.

**Comment by guyca** [comment]
@swabbass Notice that Android's behaviour is to collapse the buttons to make room for the title, and only when all buttons are collapsed into the overflow menu icon (three dots button) the title is elipsized.
