### ISSUE TITLE
iOS build fails on latest RN 0.64 and RNN 7.11.3

### ISSUE THREAD

**Issue by leoz** [wix/react-native-navigation#7038]
## 🐛 Bug Report

Build fails on latest RN 0.64 and RNN 7.11.3

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. Generate new RN app: ``npx react-native init <project name>``
2. Install RNN to it: ``yarn add react-native-navigation`` , ``npx rnn-link``, ``pod install --project-directory=ios``
3. Try to build and run the app: ``npx react-native run-ios``

## Expected behavior

App compiles and runs on the iOS simulator.

## Actual Behavior

Build fails with following error message:

``AppDelegate.m:37:7: error: use of undeclared identifier 'rootView'
      rootView.backgroundColor = [UIColor whiteColor];``

## Your Environment

- React Native Navigation version: 7.11.3
- React Native version: 0.64
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator

## Reproducible Demo

Follow the steps above to generate the demo setup

**Comment by yogevbd** [comment]
Removing this line: `rootView.backgroundColor = [UIColor...` in `AppDelegate.m` file should solve this.
