### ISSUE TITLE
StatusBar options don't work on iOS (rnn: v7.11.3)

### ISSUE THREAD

**Issue by dan-trewin** [wix/react-native-navigation#7039]
## 🐛 Bug Report

StatusBar options don't work on iOS (rnn: v7.11.3)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes.

## To Reproduce

- In your project, set rnn defaults:

1. `visible` prop doesn't do anything/work on iOS:
```js
Navigation.setDefaultOptions({
  statusBar: {
    visible: false
  }
})
```

2. `style` prop (I tried light too) doesn't do anything/work on iOS:
```js
Navigation.setDefaultOptions({
  statusBar: {
    style: 'light'
  }
})
```

I'm assuming other StatusBar props (<https://wix.github.io/react-native-navigation/api/options-statusBar>) don't work either but I've only tested these two. Both the props work as expected on android project.

## Expected behavior

1. I expected this prop to make the status bar invisible (like it does on android). 
2. I expected this prop to make the status bar text white (like it does on android). 

## Actual Behavior

1. Instead nothing changed about the status bar on my iOS project. It still lists the carrier, the time and your battery: 
<img width="388" alt="Screen Shot 2021-03-16 at 1 32 43 PM" src="https://user-images.githubusercontent.com/35882574/111362045-5a001480-865c-11eb-83c9-0be38445d0f2.png">

2. I tried `style: 'light'` and `style: 'dark'` and nothing changed:
<img width="389" alt="Screen Shot 2021-03-16 at 1 33 23 PM" src="https://user-images.githubusercontent.com/35882574/111362268-9469b180-865c-11eb-9bb3-ade61e204a26.png">

## Your Environment

- React Native Navigation version: `7.11.3`
- React Native version: `0.63.4`
- Platform: iOS
- Device info: Debug and Release, Tested on iPhone 8 Simulator (iOS 14.2) and iPhone 12 Pro Max Simulator (iOS 14.2) 

## Reproducible Demo

This should be easy to reproduce without a demo. But if one is required to fix this issue, I could make one...

Thanks!

**Comment by cspicuzza** [comment]
I'm experiencing the same behavior when declaring static options in my class component. topBar options appear to work but statusBar options are ignored.

**Comment by cspicuzza** [comment]
[This](https://github.com/wix/react-native-navigation/issues/5797#issuecomment-596025390) fixed it for me

**Comment by dan-trewin** [comment]
Thanks, setting that fixed it for me as well. They should add this requirement to the documentation at some pt. Closing the thread.
