### ISSUE TITLE
Delayed scene rendering (IOS)

### ISSUE THREAD

**Issue by kyle-ssg** [wix/react-native-navigation#704]
I say IOS as I haven't looked at the project in android (though will be very soon).

There is a noticeable delay when pushing a basic scene, this becomes especially noticeable when pushing a scene with a different background to the main app - during a push transition the screen will appear to flash briefly.

The way I've got around this generally is to have a barebones component (normally with just an element or 2, any more and I'd see a flash) and defer rendering of the real scene by a few ms. I think this issue may be unavoidable however wonder if anything can or is being looked at around performance.

Before deferring
http://g.recordit.co/IYWeaVyJnZ.gif

After deferring
http://g.recordit.co/0xFr0cn6rd.gif

**Comment by guyca** [comment]
Hey @kyle-ssg 
This issue has been discussed at length in the past. It's already addressed on Android, and will be addressed on iOS in the upcoming version. #437 can help mitigate this issue

**Comment by kyle-ssg** [comment]
Hey @guyca, thanks for the very prompt reply 😄  
Ah brilliant, I'm glad to hear this is being addressed. Setting background color / rendering faux components for initial render will probably be fine for now.

Thanks!

**Comment by RomualdPercereau** [comment]
Hey @guyca  

Do you know if there is any progress on this issue (without using the backgroundColor trick) ?
