### ISSUE TITLE
[7.12.0] waitForRender doesn't work as expected on iOS

### ISSUE THREAD

**Issue by rashidul0405** [wix/react-native-navigation#7068]
## 🐛 Bug Report

Can see a white screen before rendering the root screen, in other words, white flickering between splash screen and root screen. So `waitForRender` is not working

7.11.0 it was
```
animations: {
  setRoot: {
    waitForRender: true,
  },
},
```

in case of 7.12.0 [changed](https://github.com/wix/react-native-navigation/commit/a9559ab1ce4dfda2d318bfcccb2bda0af361c381) as below:
```
animations: {
  setRoot: {
    enter: {
      waitForRender: true,
      enabled: false,
    }
  }
}
```
### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

yes

## To Reproduce

N/A

## Expected behavior

Should transit smoothly, no white flickering.

## Actual Behavior
white flickering between splash screen and root screen.

## Your Environment

- React Native Navigation version: 7.12.0
- React Native version: 0.64.0
- Platform(s) (iOS, Android, or both?): iOS, didn't test android
- Device info (Simulator/Device? OS version? Debug/Release?): iPhone 12 (iOS 14.4) simulator

## Reproducible Demo

Can be provided if seems necessary.

**Comment by pribeh** [comment]
Experiencing the same.
