### ISSUE TITLE
Tab Bar Text Still Cuts Off

### ISSUE THREAD

**Issue by priyak-sdei** [wix/react-native-navigation#7072]
### I am using the updated library version
 "react-native-navigation": "7.11.3",
 
But still it is replicating
![Simulator Screen Shot - iPhone 11 - 2021-04-05 at 11 09 59](https://user-images.githubusercontent.com/70944781/113541686-5aa71d80-9600-11eb-954c-4129b0fd4214.png)

**Comment by sanghavan** [comment]
Same issue for me.
I guess the issue relates to `react-native` version. I upgraded `react-native` to 0.64.0 then my app got this issue.

**Comment by stachu2k** [comment]
Same issue here. I have react-native 0.64.1 and react-native-navigation: 7.13.0.

**Comment by guyca** [comment]
@stachu2k @sanghavan @priyak-sdei Can you guys please [provide a reproduction](https://wix.github.io/react-native-navigation/docs/meta-contributing/#provide-reproductions) so we can investigate?

**Comment by sanghavan** [comment]
Similar https://github.com/wix/react-native-navigation/issues/6923

**Comment by filipsuk** [comment]
I was able to locally fix this by reverting this PR https://github.com/wix/react-native-navigation/pull/6784 using patch-package

**Comment by stachu2k** [comment]
@guyca Hi. I created a minimal reproduction for you https://github.com/stachu2k/RNNavigationBug
![demo](https://user-images.githubusercontent.com/6988196/140949018-651718e2-05f2-42c1-866a-62f059208d2c.gif)
As you can see it is not always happening. Weird.

**Comment by gvillenave** [comment]
Can this issue be reopened? This reproduces fairly consistently on iOS 15.

**Comment by kabus202** [comment]
@stachu2k  Did you find a solution for this?

**Comment by stachu2k** [comment]
@kabus202 Unfortunately not. I'm stuck with version 6.0.0 which is extremely old and I don't recommend using it. I would be happy to drop this package and move to react-navigation, but my app is too big and rewrite can take months. I'm very disappointed working with react-native.

**Comment by stachu2k** [comment]
@kabus202 It looks like it is no longer occuring on iPhone if you compile project with the latest XCode 13. But sadly, the bug still exists on iPads.

**Comment by marf** [comment]
Yes, bug still happening with iPad and version of RNN 7.28.0

**Comment by olegderecha** [comment]
Ok, guys, let's solve it together here: https://github.com/wix/react-native-navigation/issues/7506#issuecomment-1160668701
