### ISSUE TITLE
playground is not working in android

### ISSUE THREAD

**Issue by Ppang0405** [wix/react-native-navigation#7073]
Totally work on ios. 
But not for android:
![Screen Shot 2021-04-06 at 21 24 05](https://user-images.githubusercontent.com/33455900/113726411-6be64c00-971e-11eb-8062-93a1a83adf80.png)
![Screen Shot 2021-04-06 at 21 24 54](https://user-images.githubusercontent.com/33455900/113726569-891b1a80-971e-11eb-913a-cc7e87010e95.png)

**Comment by guyca** [comment]
Hey, @Ppang0405 this seems like a local environment issue unrelated to RNN.
