### ISSUE TITLE
playground does not working (android)

### ISSUE THREAD

**Issue by Ppang0405** [wix/react-native-navigation#7084]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

No

## To Reproduct

1. clone project
1. run android
1. Caused by: java.lang.Exception: Couldn't determine CLI location. Please set `project.ext.react.cliPath` to the path of the react-native cli.js

## Expected behavior

Everything should work

## Actual Behavior

1. Caused by: org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener.
![Screen Shot 2021-04-12 at 19 29 18](https://user-images.githubusercontent.com/33455900/114394424-60cf6800-9bc5-11eb-96e8-a349959f7b6e.png)

2. Caused by: java.lang.Exception: Couldn't determine CLI location. Please set `project.ext.react.cliPath` to the path of the react-native cli.js
![Screen Shot 2021-04-12 at 19 29 39](https://user-images.githubusercontent.com/33455900/114394463-6dec5700-9bc5-11eb-93d2-ab5405b46bf9.png)

3. Couldn't determine CLI location. Please set `project.ext.react.cliPath` to the path of the react-native cli.js
![Screen Shot 2021-04-12 at 19 29 50](https://user-images.githubusercontent.com/33455900/114394476-747ace80-9bc5-11eb-98dd-c0184523562a.png)

## Your Environment

- React Native Navigation version: *
- React Native version: *
- Platform(s) (iOS, Android, or both?): Android (ios do not have any issues)
- Device info (Simulator/Device? OS version? Debug/Release?): Any emulators

## Reproducible Demo

The demo is the playground of this project

**Comment by guyca** [comment]
Hey there 👋 
This isn't related to RNN. The Playground app does work on Android.
