### ISSUE TITLE
[Android] - drawer, navigatorStyle, NavigatorEvent not working

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#71]
Hi, I am testing Example project on Android.

Drawer(Sidemenu): navicon_menu.png icon not show
NavigatorStyle: allway show gray background color
NavigatorEvent not working

![screen shot 2016-06-22 at 12 36 11 am](https://cloud.githubusercontent.com/assets/19372005/16239919/60e02fea-3811-11e6-8a26-504ff602ae4f.png)

**Comment by guyca** [comment]
Hey @agumack PR #61 adds drawer functionality to Android. Unfortunately the author has disappeared so I'm slowly cherry-picking some of the commits. Hope to cherry pick the drawer commit by the end of next week.
If someone is willing to submit a PR with the cherry-picked drawer commit it would speed things up for sure.
