### ISSUE TITLE
library not found for -lReactNativeNavigation on archive

### ISSUE THREAD

**Issue by alirizvibuzzinteractive** [wix/react-native-navigation#7100]
ld: warning: directory not found for option '-L/Users/goharshafique/Library/Developer/Xcode/DerivedData/demy-gzkzyxfvdowaczhjkyflttaoxdvs/Build/Intermediates.noindex/ArchiveIntermediates/demy/BuildProductsPath/Release-iphoneos/ReactNativeNavigation'
ld: warning: directory not found for option '-F/Users/goharshafique/Library/Developer/Xcode/DerivedData/demy-gzkzyxfvdowaczhjkyflttaoxdvs/Build/Intermediates.noindex/ArchiveIntermediates/demy/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/OpenSSL'
ld: library not found for -lReactNativeNavigation

its working fine on debug but an error comes when clicking on the archive

**Comment by hukpavlo** [comment]
Hi @alirizvibuzzinteractive you can change your iOS deployment target to iOS 11 and it'll work. Probably this should be changed in their install script to not confuse users.
![image](https://user-images.githubusercontent.com/40897161/115963541-6d8a7f00-a528-11eb-82cb-b76a1aece201.png)

**Comment by yogevbd** [comment]
@hukpavlo we actually have it in our [link script](https://github.com/wix/react-native-navigation/blob/e58cf1532217c210f1e25f465d44b13fd16ab8b6/autolink/postlink/podfileLinker.js#L29).

**Comment by hukpavlo** [comment]
@yogevbd in Podfile yes, but not in Xcode file
![image](https://user-images.githubusercontent.com/40897161/129945859-c7a13a29-541e-49e9-9e28-4644f1744e80.png)
