### ISSUE TITLE
iOS Large Title does not work with custom backButton

### ISSUE THREAD

**Issue by robrechtme** [wix/react-native-navigation#7101]
## 🐛 Bug Report

When using a custom `topBar.backButton` in combination with the `topBar.largeTitle`, it uses the default chevron until you scroll up.

## Expected behavior

The custom backButton (in this case the `X` icon) should be the backButton in all cases.

## Actual Behavior

The  default chevron is used until you scroll up. The custom color however is used at all times.

![ios14](https://user-images.githubusercontent.com/24371353/115884856-a4409680-a44f-11eb-87d8-aff06896fc07.gif)

## Your Environment

- React Native Navigation version: 7.13.0
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): iPhone 12 mini sim (14.4)

## Reproducible Demo

```ts
MyScreen.options = {
  topBar: {
      title: { 
        text: 'Profile' 
      },
      backButton: {
        icon: CLOSE_ICON,
        color: 'red',
      },
     largeTitle: { 
         visible: true, 
     },
  },
};
```

**Comment by robrechtme** [comment]
Still an issue.

**Comment by todorone** [comment]
Confirm, still an issue.
