### ISSUE TITLE
testID of bottomTabs is not an ancestor of testID of bottomTab

### ISSUE THREAD

**Issue by Andarius** [wix/react-native-navigation#7104]
## 🐛 Bug Report

All `bottomTab` testIDs are expected to be a descendant of `bottomTabs`testID which is not the case anymore in the latest version.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

yes

## To Reproduce

Setup an e2e test that tries to access a bottomTab testID with the following syntax: `element(by.label('Second Tab').withAncestor(by.id(TestIDs.BOTTOM_TABS)))`

## Expected behavior

e2e tests should not fail and match the testID

## Actual Behavior

The testID is not found

![image](https://user-images.githubusercontent.com/5070712/116067184-367faf00-a689-11eb-88c6-bbc4cca28280.png)

## Your Environment

- React Native Navigation version: 0.64
- React Native version: 7.13.0
- Platform(s) (iOS, Android, or both?): tested on android
- Device info (Simulator/Device? OS version? Debug/Release?): the one from the e2e tests

## Reproducible Demo

https://github.com/Andarius/react-native-navigation/tree/issue/bottomTabs

run `detox test --configuration android.emu.debug ./e2e/BottomTabs.test.js`

**Comment by guyca** [comment]
@Andarius I'm not sure I understand the issue. Can you please elaborate?

**Comment by Andarius** [comment]
@guyca if I try to access a bottom tab by it's label, but to make sure it's really the label of a button  in the bottomTab I add in the following options (like in the playground app):
```
        options: {
          bottomTabs: {
            testID: BOTTOM_TABS,
          },
        },
```
This code was working before but it's now failing.

**Comment by Andarius** [comment]
Maybe the testID of `bottomTabs` was never supposed to be an ancestor of a `bottomTab` ?

**Comment by guyca** [comment]
I'm sorry - I still don't understand what's not working. Can you please show the complete options object and the layout which now doesn't work?

**Comment by Andarius** [comment]
I'm sorry if I explain badly.

With this layout:

(https://github.com/Andarius/react-native-navigation/blob/cf2ae62b05c36d0e0d6b337db3d32f679e7cdcb1/playground/src/screens/LayoutsScreen.tsx#L57)
```
  bottomTabs = () =>
    Navigation.showModal({
      bottomTabs: {
        children: [
          stack(Screens.FirstBottomTabsScreen),
          stack(
            {
              component: {
                name: Screens.SecondBottomTabsScreen,
              },
            },
            'SecondTab'
          ),
        ],
        options: {
          bottomTabs: {
            testID: BOTTOM_TABS,
          },
        },
      },
    });
    ```
    Isn't "Tab 1" (https://github.com/Andarius/react-native-navigation/blob/cf2ae62b05c36d0e0d6b337db3d32f679e7cdcb1/playground/src/screens/FirstBottomTabScreen.tsx#L33) supposed to be a descendant of 
    ```
     bottomTabs: {
            testID: BOTTOM_TABS,
          },
  ```

**Comment by Andarius** [comment]
After some digging in my CI, it seems that `element(by.label('Second Tab').withAncestor(by.id(TestIDs.BOTTOM_TABS)))` was working in `7.9.0` but not in `7.10.0`

**Comment by Andarius** [comment]
Ok, there is something weird here. It was working before, but I cannot reproduce using the same version that it was passing in my tests...
Sorry for that, I'll close both the PR and issue.
