### ISSUE TITLE
Support for a root stack that contains bottom stacks that contains another stack

### ISSUE THREAD

**Issue by jfrolich** [wix/react-native-navigation#7107]
## 🐛 Bug Report

I would like to check first if this would be in scope for this project. For an application I am building we would like to push the bottom tabs away so we don't have the tabs taking up space where we have a text input at the bottom of the screen.

This can be achieved with a top level stack, then inside that a bottomTabs, and inside that another stack. However there are many bugs when doing that:

- Tab active color doesn't work correctly anymore
- The back button is positioned too low for the stack that is contained in the bottomTabs

Perhaps there is a way to work around these bugs (anyone tried this?). And if not, is this something that would be fixed in a future version?

PS: I know that you can hide the tab bar, but that UI is weird even though it can animate.

**Comment by guyca** [comment]
Hey @jfrolich! 👋 
I'm sorry, but I'm not entirely sure I understand the use case you've described. Any chance you can attach a screenshot or provide more clarifications?

**Comment by guyca** [comment]
FWIW, you can run the playground app with [this](https://github.com/wix/react-native-navigation/blob/master/playground/src/flags.ts#L2) flag enabled. It will show a text input at the bottom of each screen. You can use this to test problematic use cases. Hope this helps.

**Comment by jfrolich** [comment]
Yes I think it's more clear to write a proper reproduction of this. I'll follow up with a PR. Thanks!

**Comment by jfrolich** [comment]
Actually, I found that hiding the bottomTabs now works as expected! This wasn't the case in an older version of this library. This is actually much better because it keeps the hierarchy simple!
