### ISSUE TITLE
Title bar text wrapping since v7.13.0

### ISSUE THREAD

**Issue by devattendant** [wix/react-native-navigation#7108]
## 🐛 Bug Report

After I've upgraded RN to 0.63.4 and RNN to 7.13.0 (previously I used 0.62.2 and 7.8.4) I noticed that titles in the title bar being longer than the actual title bar are wrapped instead of being truncated with "..." at the end, which was the behaviour before.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes.

## To Reproduce

1. Set a longer title than the UI can take and see how it wraps.

## Expected behavior

The title is being truncated with "..." being added to the end.

## Actual Behavior

![photo_2021-05-02_12-12-09](https://user-images.githubusercontent.com/11097642/116809711-adacbb80-ab3f-11eb-9abd-04b59a4acbe0.jpg)

## Your Environment

- React Native Navigation version: 7.13.0
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): Android
- Device info: Device (Pixel 3a), Android 11, Debug & Release

## Reproducible Demo

Not available.

## Quick fix

Sadly I am not enough into Android development but I managed to fix the issue with editing `TitleSubTitleLayout.kt` as following:

`class TitleSubTitleLayout(context: Context) : LinearLayout(context) {

    private val titleTextView = TextView(context).apply { TextViewCompat.setTextAppearance(this, R.style.TitleBarTitle) }
    private val subTitleTextView = TextView(context).apply { TextViewCompat.setTextAppearance(this, R.style.TitleBarSubtitle) }

    init {
        this.orientation = VERTICAL
        this.setVerticalGravity(Gravity.CENTER_VERTICAL)
        this.addView(titleTextView, LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT).apply { gravity = Gravity.START or Gravity.CENTER_VERTICAL })
        this.addView(subTitleTextView, LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT).apply {
            gravity = Gravity.START or Gravity.CENTER_VERTICAL
            weight = 1f
        })

        titleTextView.setEllipsize(TextUtils.TruncateAt.END)
        titleTextView.setSingleLine(true)
    }`

**Comment by guyca** [comment]
I believe this will be fixed by #7096, @swabbass will probably know for certain.

**Comment by swabbass** [comment]
Closed by  #7096
