### ISSUE TITLE
Prevent pop screen swipe gesture

### ISSUE THREAD

**Issue by t2n3qqq** [wix/react-native-navigation#711]
### Issue Description

I am trying to implement gallery view for iOS application, it appears on the screen as view with absolute position and when I'm swiping images in gallery I can pop previous screen by swipe on the left edge of the screen. Is it possible to disable pop screen swipe gesture in each screen or maybe in whole application?

**Comment by indivisable** [comment]
You could comment out this code to remove it (requires objecitve-c editing)

https://github.com/wix/react-native-navigation/issues/428

**Comment by t2n3qqq** [comment]
@indivisable Yeah, I have tried it, but it disables back gestures for all screens, so I just add a method that switching back swipes state from RN navigator prop. It solve my problem, but this switcher disables and enables back swipes for all screens too and it can't solve issue with back swipe on the root screen because of we can't catch that screen is focused after pop from next screen, unfortunately.

**Comment by gran33** [comment]
@t2n3qqq,
I added this feature, plz see this PR:
https://github.com/wix/react-native-navigation/pull/872
