### ISSUE TITLE
Shared Element Transition broken with safe area

### ISSUE THREAD

**Issue by mrousavy** [wix/react-native-navigation#7111]
## 🐛 Bug Report

The Shared Element Transition seems to not animate to the correct bounds.

Here's a video of the SET breaking on a phone that has left and right "edges" 

https://user-images.githubusercontent.com/15199031/117459200-6eb9a400-af4b-11eb-83a6-1cfda49d6711.mp4

In this case I think the problem is that the screen absolute coordinates are used, which are not equal to the coordinates relative to the React Root view and they extend beyond those screen "edges":

![](https://cdn57.androidauthority.net/wp-content/uploads/2019/10/waterfall-displays-curved-edges-glass-1-1200x675.jpg)

(just assuming things here)

Here's another case of the bounds animation failing, this is a regular phone without any "safe areas", just the 24px statusbar:

https://user-images.githubusercontent.com/15199031/117459759-0a4b1480-af4c-11eb-84ae-1e5e34049c97.MP4

Here the image seems to be a bit higher up than it should be, looks to me as if it were exactly twice the statusbar moved up. Maybe there's a `- STATUS_BAR_HEIGHT` somewhere where it should be a `+ STATUS_BAR_HEIGHT` instead, just assuming things again. You can also see that after I fast-refresh the view, it goes into the correct place, so it has to be an issue with the RNN SET.

Maybe `statusBar: { drawBehind: true }` or `statusBar: { visible: false }` is not respected here?

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

yea

## To Reproduce

1. Create Shared Element Transition
1. Try it on phones with Safe Areas, or in my case just a regular Huawai P10

## Expected behavior

It should exactly animate to the bounds of the target react view

## Actual Behavior

it animates to some wrong coordinates.

## Your Environment

- React Native Navigation version: 6f7c2d9f75b5fb653452f903d822429eed429f51
- React Native version: 0.64.1
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): all

**Comment by swabbass** [comment]
@mrousavy  Thx dude for the report, and sorry for the late response :].
Actually, I have no such device (edge) to reproduce and check, but can you check this PR if it fixes your issue? at least left/right edges.

**Comment by guyca** [comment]
@mrousavy wasn't this fixed by Hano and me two weeks ago? 🤔

**Comment by mrousavy** [comment]
Yes, I believe that's the fix: https://github.com/wix/react-native-navigation/commit/642b4296ced6ad453e4db8e6e74139c3b2ba7e8e

Wonder what's happening now, I'll check

**Comment by mrousavy** [comment]
@swabbass which PR is it ? did you merge it already?

**Comment by swabbass** [comment]
> Yes, I believe that's the fix: [642b429](https://github.com/wix/react-native-navigation/commit/642b4296ced6ad453e4db8e6e74139c3b2ba7e8e)
> 
> Wonder what's happening now, I'll check

@mrousavy can we close this issue? :] (the PR I was talking about is merged to master, contains a couple of SET bug fixes )

**Comment by mrousavy** [comment]
Hey! Sorry, that app isn't alive anymore. :(
