### ISSUE TITLE
BottomTabs Text didn't show when tab is not active

### ISSUE THREAD

**Issue by chj-damon** [wix/react-native-navigation#7117]
## 🐛 Bug Report
1. I want to display both icon and text at the same time no matter the tab is active or not. But currently I see text will show if tab is active but it will hide if tab is not active.
2. I configured the `bottomTab` but it didn't work, my configuration is: 
```ts
root: {
    bottomTabs: {
      id: 'BOTTOM_TABS_LAYOUT',
      children: [
        {
          stack: {
            children: [
              {
                component: {
                  name: 'Home',
                },
              },
            ],
            options: {
              bottomTab: {
                text: 'Home',
                icon: require('./assets/home.png'),
              },
            },
          },
        },
        {
          stack: {
            children: [
              {
                component: {
                  name: 'Settings',
                },
              },
            ],
            options: {
              bottomTab: {
                text: 'Settings',
                icon: require('./assets/setting.png'),
                badge: '2',
              },
            },
          },
        },
      ],
      options: {
        bottomTabs: {
          animate: true,
          animateTabSelection: true,
          tabsAttachMode: 'onSwitchToTab',
        },
        bottomTab: {
          textColor: '#000',
          selectedTextColor: 'red',
          selectedIconColor: 'red',
        },
      },
    },
  },
```
`selectedTextColor` and `selectedIconColor` do not work in the screenshot.
3. animation is not been seen when switching the tabs.

(A clear and concise description of what the bug is)
![Screenshot_1620896715](https://user-images.githubusercontent.com/4902684/118104197-66f77500-b40d-11eb-8f09-41e26619ea4b.png)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. Step 1...
1. Step 2...
1. Step 3...

## Expected behavior
It should work as what I've configured.

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- React Native Navigation version: v7.14.0
- React Native version: 0.64.0
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug

## Reproducible Demo

(Paste the link to an example repo and exact instructions to reproduce the issue.)

**Comment by birkir** [comment]
Use `bottomTabs.titleDisplayMode = 'alwaysShow'`

defaults to `showWhenActive` if i remember correctly.

**Comment by guyca** [comment]
Thanks @birkir 👍
