### ISSUE TITLE
Animation in the playground project not working on Android devices

### ISSUE THREAD

**Issue by chj-damon** [wix/react-native-navigation#7118]
## 🐛 Bug Report

I tried the playground on my computer and it works fine on IOS. But when I run the playground on Android devices, I didn't see any animation effect. no matter showModal or Shared Elements.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

run the playground locally on Android devices.

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- React Native Navigation version: FILL THIS OUT
- React Native version: FILL THIS OUT
- Platform(s) (iOS, Android, or both?): FILL THIS OUT
- Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

## Reproducible Demo

(Paste the link to an example repo and exact instructions to reproduce the issue.)

**Comment by yogevbd** [comment]
Did you try to run it on an emulator or a real device? It might be possible that the device animations is disabled

**Comment by chj-damon** [comment]
I tried it on an emulator, maybe you're right, I should try it on real device to see what happens.

**Comment by chj-damon** [comment]
yes it works fine on real android devices.
