### ISSUE TITLE
navigator.setButtons defined on Component1, sets buttons on pushed Component2 [Possible BUG]

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#712]
### Issue Description

On a TabBasedApp, at Component-1, I am calling `navigator.setButtons` AFTER a `fetch` call and after the server has returned the results (the button name depends on server results).

If the user clicks on TouchableOpacity button to push a new screen (Component-2), and if the server hasn't returned the results yet, the `navigator.setButtons` (from Component-1) is executed on the pushed screen and instead of the left button to be '< Back' it is set depending on the results returned from the server.
This happens either if I don't define any left button when pushing the Component-2, or even if I do define it within the Component-2 with static method.

If instead of push, I use showModal, this doesn't happen. The correct button is shown.

---
### Environment
* React Native Navigation version: 0.37
* React Native version: 2.0.0-experimental.191
* Platform(s) (iOS, Android, or both?): iOS(haven't tried Android)
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iOS 10, macOS

**Comment by perrosnk** [comment]
@guyca any idea on how to solve this?

**Comment by tim-dev** [comment]
I think this is basically https://github.com/wix/react-native-navigation/issues/243
