### ISSUE TITLE
Issue when enabling waitForRender on setRoot

### ISSUE THREAD

**Issue by alradadi** [wix/react-native-navigation#7126]
## 🐛 Bug Report

Please see the below screenshot. There's a white bar at the top that cannot be removed. Even though the visibilty of `topBar` is set to false.

 
<img src="https://user-images.githubusercontent.com/16872175/118965013-d7a01380-b970-11eb-8fc1-d4f02c484ed3.png" width="250">

## To Reproduce

I was able to reproduce this in the playground app. 

```
stack = () => Navigation.setRoot({
    sideMenu: {
      center: {
        stack: {
          children: [
            {
              component: {
                name: Screens.Stack
              }
            }
          ]
        }
      },
      options: {
        topBar: {
          visible: false
        },
        animations: {
          setRoot: {
            waitForRender: true
          }
        }
      },
    }
  });
```

## Environment

This issue started happening with version 7.2.0. I was able to track this issue to this exact line

https://github.com/wix/react-native-navigation/pull/6689/files#diff-3543698422c04c8920f1582ae4cbe3a3ceb74af1dfde417ab07b6c2a7eaa0a16R257

**Comment by yogevbd** [comment]
Which rnn version are you using? It look like you are rendering a `SafeAreaView`.
