### ISSUE TITLE
How to navigate to a screen from outside a React component

### ISSUE THREAD

**Issue by mohsinulhaq** [wix/react-native-navigation#7142]
I see https://github.com/wix/react-native-navigation/issues/993 was raised a few years ago, and I wonder if any support was added for this in the latest versions of the library. Thanks.

**Comment by guyca** [comment]
@mohsinulhaq You can either pass the `componentId` to other screens, or set a predefined id to the relevant layout and use it when pushing. This is described in detail in the [docs](https://wix.github.io/react-native-navigation/docs/sideMenu#pushing-to-the-center-layout-from-a-menu)

**Comment by mohsinulhaq** [comment]
I ended up adding a command event listener and storing the current componentId.
```ts
Navigation.events().registerCommandListener((name, params) => {
  if (name === 'push') {
    currentComponentId = params.componentId;
  }
});
```
