### ISSUE TITLE
Minimum Version of Kotlin documented in Install Instructions doesn't work for React Native Navigation 7.15

### ISSUE THREAD

**Issue by orthanc** [wix/react-native-navigation#7145]
## 📚 Documentation

The [install instructions for 7.15](https://wix.github.io/react-native-navigation/docs/installing#android) indicate the minimum kotlin version is 1.3.x

```
kotlinVersion = "1.3.72" // Or any version above 1.3.x
```

Using Kotlin `1.3.61` worked fine with RNN 7.14, but on upgrading to 7.15 gradle bundling for android fails with the following errors:

```
e: <BASE_PATN>/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleAndButtonsMeasurer.kt: (28, 26): Expecting a parameter declaration
e: <BASE_PATN>/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt: (22, 43): Unresolved reference: maxByOrNull
e: <BASE_PATN>/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/views/stack/topbar/titlebar/TitleBarReactView.kt: (22, 57): Unresolved reference: it
```

When I switch to Kotlin `1.4.31` ([What would be installed by rnn-link if not already present](https://github.com/wix/react-native-navigation/blob/master/autolink/postlink/gradleLinker.js#L6) ) the build suceeds, leading me to believe the minimum Kotlin version is now 1.4.x

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

**Comment by yogevbd** [comment]
This is already fixed in master. building a new version with it.

**Comment by yogevbd** [comment]
Aligned with the documentation in 7.16.0
