### ISSUE TITLE
dotIndicator is shown on the next tab when badge in null on ios 

### ISSUE THREAD

**Issue by flexsurfer** [wix/react-native-navigation#7146]
dotIndicator is shown on the next tab when badge is null on ios 

## To Reproduce

1. Show badge 
```
Navigation.mergeOptions('componentId', {
  bottomTab: {
    badge:"1"
  },
});
```
2. Hide badge and show dotIndicator
```
Navigation.mergeOptions('componentId', {
  bottomTab: {
    badge:null,
    dotIndicator: {visible: true}
  },
});
```
## Expected behavior

dotIndicator is shown for componentId tab

## Actual Behavior

dotIndicator is shown for the next tab

## Your Environment

- React Native Navigation version: 7.13.0
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): iOS 13.5
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator and Device, Debug and Release

**Comment by anagovitsyn** [comment]
you should set this options for bottomTab, not for bottomTab**s**

**Comment by flexsurfer** [comment]
yes, mistake in the description, fixed

**Comment by eightyfive** [comment]
Ok I did run some other tests, and it does not seem to be related to `badge: null` in particular. It's a broader issue, it happens when "using multiple times `Navigation.mergeOptions`" on some/all tabs.

Hope this helps.

**Comment by MateusAndrade** [comment]
I managed to hide the `badge` indicator by adding an:  

```js
                  bottomTab: { dotIndicator: { visible: false } }, 
````

Without omitting the `badge` and `badgeColor` on the `mergeOptions` I would end with the badge being shown with a 0.
