### ISSUE TITLE
Android: setStackRoot on a non-selected tab triggers componentDidAppear

### ISSUE THREAD

**Issue by tastyqbit** [wix/react-native-navigation#7148]
## 🐛 Bug Report

When trying to setStackRoot on a tab that is not currently selected, the componentDidAppear method triggers anyway. Then the next time the unselected tab is selected, the componentDidAppear doesnt trigger

EDIT: The bug only happens when setStackRoot animations are disabled

## To Reproduce

Only on android

1. A tab based root navigation
2. setStackRoot on non selected tab screen with default setStackRoot animated disabled
3. componentDidAppear triggers on that tab
4. Clicking the unselected tab and showing it does not trigger componentDidAppear

## Expected behavior

componetnDidAppear should not trigger if the screen is not active

## Actual Behavior

componentDidAppear triggers

## Your Environment

- React Native Navigation version: 7.6.0
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): All

**Comment by swabbass** [comment]
@tastyqbit Thx for the info :] we are looking into it
