### ISSUE TITLE
Recursive call of navigationButtonPressed when popStackOnPress: false

### ISSUE THREAD

**Issue by angelos3lex** [wix/react-native-navigation#7154]
## 🐛 Bug Report

navigationButtonPressed is called after Navigation.pop, while it should only be called when there is a press on a navigation button. (happens only on iOS 11 (probably 12 too))

## To Reproduce

1. In Navigation default options, set:
```
backButton: {
       showTitle: false,
       popStackOnPress: false
},
```
2. Init a navigation root with one screenA. Push screenB to the stack. 
3. On both screens, register to events with; `Navigation.events().bindComponent(this)` and listen to navigation button press event:
```
navigationButtonPressed({ buttonId }: { buttonId: string }) {
        if (buttonId === "RNN.back") {
            Navigation.pop(this.props.componentId);
        }
    }
```
4. Press back button while on screenB.
5. This will trigger `navigationButtonPressed` of screenB. Since we manually pop there, this will trigger again the `navigationButtonPressed` on screenA. If we didn't manually pop there, there would be no recursive call. 
So somehow, the  Navigation.pop calls the `navigationButtonPressed` of previous screens in the stack. 

## Expected behavior

As happening on android and ios 14, `Navigation.pop` shouldn't recursively call the `navigationButtonPressed` of other screens

## Your Environment

- React Native Navigation version: 7.14.0
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): IOS
- Device info (Simulator/Device? OS version? Debug/Release?): Both simulator and device, debug and release versions, iOS 11 (probably 12 too)

**Comment by yogevbd** [comment]
Hi, I tried to reproduce your use case with no luck. Can you add a reproduction demo in our playground app?
Thanks!

**Comment by Nehal-Sanklecha** [comment]
@yogevbd You can reproduce this issue on iOS 12.0 I'm facing a similar problem.

**Comment by Nehal-Sanklecha** [comment]
@angelos3lex  Did you find any solution to this problem?
