### ISSUE TITLE
Issue rendering text on "More" tab page

### ISSUE THREAD

**Issue by lindesvard** [wix/react-native-navigation#7160]
## 🐛 Bug Report

When we have more than 5 tabs the `More` tab appears. When we click this the rest of the tabs appears. But they do not have any text. 

<img width="597" alt="Screenshot 2021-06-21 at 15 14 49" src="https://user-images.githubusercontent.com/1987198/122767941-6de29480-d2a3-11eb-86a7-bea43f86cc48.png">
![Screen Recording 2021-06-21 at 15 11 19](https://user-images.githubusercontent.com/1987198/122768039-80f56480-d2a3-11eb-90f3-44c3a05a3436.gif)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. Checkout: https://github.com/lindesvard/rnn-bugs/tree/more-tab
2. `yarn && yarn ios`
3. Click on the more tab

## Expected behavior

The rest of the tabs should be displayed with text

## Actual Behavior

The rest of the tabs are displayed but *without* text

## Your Environment

- React Native Navigation version: 7.16.0
- React Native version: 0.63.4
- Platform(s): iOS
- Device info: iOS Sim 14.3 Debug

## Reproducible Demo

https://github.com/lindesvard/rnn-bugs/tree/more-tab

**Comment by retyui** [comment]
> Note:  on Android App will be crashed💥 if tabs more than 5 https://github.com/wix/react-native-navigation/blob/102b7184fc0cf1a1dfd177a8766cc463a72dfeb5/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/bottomtabs/BottomTabsController.java#L193-L195

**Comment by denkeni** [comment]
Also, in previous discussion https://github.com/wix/react-native-navigation/issues/3095 they decided the design pattern to support  5 tabs at max on both platforms. I wonder that would change.
