### ISSUE TITLE
there is a problem with the code of the reference doc

### ISSUE THREAD

**Issue by lly0414** [wix/react-native-navigation#7165]
## 📚 Documentation

Is there an import error here?
I refer to the code in the doc with an undefined property "event" error
```js
import Navigation from 'react-native-navigation';
```
>[doc page](https://github.com/wix/react-native-navigation/blob/master/website/docs/docs/docs-functional-components.mdx)

Should it be modified to
```js
import {Navigation} from 'react-native-navigation';
```

**Comment by swabbass** [comment]
Thx, changed in master
