### ISSUE TITLE
[iOS] topBar button flash on mergeOptions

### ISSUE THREAD

**Issue by alpha0010** [wix/react-native-navigation#7168]
## 🐛 Bug Report

Using `Navigation.mergeOptions()` to update the `rightButtons` in `topBar` on iOS causes elements in the top bar to flash.  This includes both changed and unchanged elements.

I would guess this was introduced in https://github.com/wix/react-native-navigation/pull/7127 .

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes.

## To Reproduce

1. Have `rightButtons`
2. Specify the `rightButtons` field during a `Navigation.mergeOptions()` operation

## Expected behavior

If the specified `rightButtons` are the same, nothing changes.  If they are different, the `rightButtons` in the top bar are updated, but nothing else changes.

## Actual Behavior

The back button, right buttons, and title (if title is a component, not text) all flash white.

https://user-images.githubusercontent.com/4990928/123828961-05616c00-d8d0-11eb-90c8-f229053882a1.mp4

## Your Environment

- React Native Navigation version: 7.16.0
- React Native version: 0.64.2
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): simulator, iOS 14.5, debug

## Reproducible Demo

```diff
diff --git a/playground/src/screens/PushedScreen.tsx b/playground/src/screens/PushedScreen.tsx
index 750361dde..c037c729a 100644
--- a/playground/src/screens/PushedScreen.tsx
+++ b/playground/src/screens/PushedScreen.tsx
@@ -68,6 +68,24 @@ export default class PushedScreen extends NavigationComponent<Props> {
     if (buttonId === 'backPress') alert('back button clicked');
   }
 
+  componentDidAppear() {
+    const componentId = this.props.componentId;
+    setInterval(() => {
+      console.log('Merging!');
+      Navigation.mergeOptions(componentId, {
+        topBar: {
+          rightButtons: [
+            {
+              id: 'singleBtn',
+              text: 'single',
+              testID: TOP_BAR_BTN,
+            },
+          ],
+        },
+      });
+    }, 1000);
+  }
+
   render() {
     const stackPosition = this.getStackPosition();
     return (
```

**Comment by JuraSemenenko** [comment]
Same issue

**Comment by parkingprodennis** [comment]
Same issue for us, does anyone has a workaround?

**Comment by yogevbd** [comment]
Sorry for the inconvenience. for now you can disable it through default options with:
```js
{
  topBar: {
    animateLeftButtons: false,
    animateRightButtons: false
  }
}
```
