### ISSUE TITLE
v2 API changes

### ISSUE THREAD

**Issue by adamski** [wix/react-native-navigation#717]
I see there are some API changes, is there any documentation available yet? Best I found was the 'playground' folder which seems to be contain the most up-to-date examples.

**Comment by DanielZlotin** [comment]
We'll document everything as the project matures. Our minimum product for release is most of the features that we currently have in master so we are not quite there yet, but moving rapidly.
A migration guide will be provided as well.

**Comment by adamski** [comment]
OK I understand - sorry if that came across as impatient. I'm excited to use the new API as there are a couple of recent additions I've been waiting for. I *really* appreciated the work you guys have put into this project. Thank you!

**Comment by DanielZlotin** [comment]
No worries, all good 😀

**Comment by DanielZlotin** [comment]
No worries, we do need to communicate better our intents and milestones.. this is also under development ;)
