### ISSUE TITLE
[Android] Screen size not adjusted properly when navigationBar is hidden

### ISSUE THREAD

**Issue by larslr** [wix/react-native-navigation#7171]
## 🐛 Bug Report

Screen size remains the same size when navigationBar is hidden, leaving a background colored box where the navigationBar used to be.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes.

## To Reproduce

1. Start with playground app
2. In app.ts, edit the setRoot() call so that that the Options stack is directly below root, removing bottomTabs and the other screens
3. Start the app, click the "Toggle Navigation bar visibility" button

## Expected behavior
The usable screen should expand towards the bottom when the navigation bar disappears. This works when using the bottomBar.

## Actual Behavior
The navigation bar disappears, but the area remains unusable. Scrolling the view moves the buttons under the navigation bar area instead of letting them hit the bottom of the screen.

Attached are screenshots showing the situation.

![scrolled_down](https://user-images.githubusercontent.com/3696793/123985021-6a4abe00-d9c5-11eb-8d67-53255fef9bda.png)
![scrolled_up](https://user-images.githubusercontent.com/3696793/123985031-6b7beb00-d9c5-11eb-887c-bb64f6f82eda.png)

## Your Environment

- React Native Navigation version: 7.16.0
- React Native version: 0.63.1
- Platform: Only tested on Android
- Device info: Android 8.1 simulated and device

## Reproducible Demo

```
git clone https://github.com/hooplab/react-native-navigation.git rnn_navbar
cd rnn_navbar
git checkout navbar_bug
```

Follow [Playground instructions](https://wix.github.io/react-native-navigation/docs/playground-app) to start app

**Comment by MagnusEklof** [comment]
Any chance getting an estimate when this is going to be fixed? I can't seem to find a workaround besides creating a "fake" bottombar just to be able to remove it...

**Comment by swabbass** [comment]
Fixed in the mentioned PR:

https://user-images.githubusercontent.com/7227793/142223869-d7bddb81-546f-4c67-809e-f2f952a0c3b8.mov

**Comment by MagnusEklof** [comment]
Hmm yes, but will it work without a bottomtabs @swabbass? I mentioned in #7199 that I could not  make it work without first creating a dummy bottomtabs and then hiding both bottomtabs and navbar... but that was not a very good workaround.

**Comment by swabbass** [comment]
@MagnusEklof  yes it will work without, you can check out the PR :#7343, the one mentioned in this issue.

**Comment by Mitesh-2009** [comment]
https://github.com/wix/react-native-navigation/issues/7431

**Comment by Mitesh-2009** [comment]
While Navigation bar visible true then bottom tabs bar not display
