### ISSUE TITLE
Navigation event listeners are not working

### ISSUE THREAD

**Issue by aparnagude396** [wix/react-native-navigation#7175]
I'm calling  Navigation.events().registerComponentDidAppearListener(({ componentId }) => {} method in constructor. In previous version it's working fine but after updating react native navigation library these events are not calling. How to use these events in react native project with lastest version. can anyone pls help me

**Comment by Kabangi** [comment]
Am experiencing a similar issue.

Works well on iOS but doesn't work on android:-

Using RNN v7.18
And react native v0.64
