### ISSUE TITLE
Dropdown for docs similar to version dropdown on smaller screens

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [wix/react-native-navigation#7179]
## 📚 Documentation

In the sidebar, specifically on a smaller screen, there's no dropdown for the docs section. However, on larger screens, you can see all the subsections of the docs. Was this done intentionally? If so, just wanted to share that on smaller screens, if I'm just scrolling through the docs to see what's available, then it'd be great to see this!

- [X] Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

yes

**Comment by yogevbd** [comment]
In smaller screens, a menu button appears and allow opening the menu drawer. Is that what you were looking for? 😌


<img width="826" alt="Screen Shot 2021-07-14 at 18 36 31" src="https://user-images.githubusercontent.com/10794586/125650464-50cd1234-fa66-4814-90b7-daf5f3669906.png">

**Comment by Andrew-Chen-Wang** [comment]
ah absolutely. Thank you!
