### ISSUE TITLE
Navigation.mergeOptions was invoked on component with id: Component33 before it is mounted, this can cause UI issues and should be avoided.

### ISSUE THREAD

**Issue by MohitSkycap** [wix/react-native-navigation#7189]
Navigation.mergeOptions(componentId, {
            topBar: {
                title: {
                    alignment: 'center',
                    fontSize: 12
                    text: "hello,
                }
            }
        })
        
 When I use the above code snippet in componentDidMount gets warning **Navigation.mergeOptions was invoked on component with id: Component33 before it is mounted, this can cause UI issues and should be avoided.**
 
 "react-native": "0.63.3",
 "react-native-navigation": "^7.15.0"
       
     Thanks

**Comment by MohitSkycap** [comment]
> Navigation.mergeOptions(componentId, {
> topBar: {
> title: {
> alignment: 'center',
> fontSize: 12
> text: "hello,
> }
> }
> })
> 
> When I use the above code snippet in componentDidMount gets warning **Navigation.mergeOptions was invoked on component with id: Component33 before it is mounted, this can cause UI issues and should be avoided.**
> 
> "react-native": "0.63.3",
> "react-native-navigation": "^7.15.0"
> 
> ```
>  Thanks 
> ```

**Comment by yogevbd** [comment]
This is intended, you should move your options to be static. read more [here](https://wix.github.io/react-native-navigation/docs/style-options/#static-options).

**Comment by MohitSkycap** [comment]
Thanks @yogevbd  Its working
