### ISSUE TITLE
How to call function onclose in modal.

### ISSUE THREAD

**Issue by trung1008** [wix/react-native-navigation#719]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
Invoke it from componentWillUnmount of the screen you show in the modal

**Comment by trung1008** [comment]
@guyca all i want is close modal, and call a function in parent.

**Comment by guyca** [comment]
pass a callback in props, and call it when the modal is unmounted
```js
this.props.navigator.showModal({
  ...
  passProps: {
    onUnmount: () => console.log('Modal dismissed')
  }
});
```

**Comment by srameshr** [comment]
@guyca Adding under async await works! Awesome !!! This critical info in docs maybe?

**Comment by liviaciabati** [comment]
Is this available on v2?
