### ISSUE TITLE
Content is clipped by tab bar when it is revealed on iOS

### ISSUE THREAD

**Issue by fiznool** [wix/react-native-navigation#7191]
## 🐛 Bug Report

Enabling bottom tab bar visibility on iOS causes content to be clipped behind the tab bar until the user navigates away to a different screen or tab.

See screenshot: the red border at the bottom of the content should be visible, but it is masked by the tab bar.

<img width="328" alt="Screenshot 2021-07-16 at 17 33 59" src="https://user-images.githubusercontent.com/820863/125980189-670d1abe-0ef3-40c2-949d-332a5e11ff9e.png">

Also see screencast in linked repo below.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

(Write your steps here:)

This is a concise summary: code reproducing this is in the repo listed below.

1. Create a new RNN project with a tab bar and two tabs, each containing a stack of one screen. Ensure the bottom tabs visibility is set to `false`.
2. Set a timer in the screen with `setTimeout`. When the timer fires, use `Navigation.mergeOptions` to set the bottom tabs visibility to `true`.

## Expected behavior

The content inside the component should not be clipped by the tab bar.

## Actual Behavior

The content is clipped by the tab bar on iOS. It is not on Android.

## Your Environment

- React Native Navigation version: 7.18.0
- React Native version: 0.64.2
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): iPhone 12 simulator, iOS 14.5, Debug

## Reproducible Demo

All instructions and a screencast showing the issue can be found at the following repo:

https://github.com/studiozeffa/rnn-tab-bar-ios-issue

**Comment by yogevbd** [comment]
Hi @fiznool, controlling the tabBar programatically isn't officially supported by Apple and therefor causing a lot of issues such as yours, we actually plan on removing this feature from iOS. read more [here](https://github.com/wix/react-native-navigation/issues/6416).
