### ISSUE TITLE
Hiding the bottom navigation bar on Android creates a gap at the bottom of the view

### ISSUE THREAD

**Issue by daveyjones** [wix/react-native-navigation#7199]
## 🐛 Bug Report

When the navigation bar is set to `visible: false` (as described [here](https://wix.github.io/react-native-navigation/api/options-navigationBar#visible)), it still takes up space. Nothing is able to render in the gap.

<img width="426" alt="Screen Shot 2021-07-21 at 2 32 04 PM" src="https://user-images.githubusercontent.com/2852617/126564007-61b9e0e9-eaf7-4afc-9f20-42e8f3c56f22.png">

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes.

## To Reproduce

1. Clone the demo (link below)
2. `cd navigation-bar-demo`
3. `yarn install`
4. `react-native run-android`

If the blue background doesn't appear on the first run, you may need to run `react-native run-android` a second time.

## Expected behavior

The blue background should extend all the way to the bottom of the view.

## Actual Behavior

The blue background stops where the navigation bar would be if it were visible.

## Your Environment

- React Native Navigation version: 7.17.1
- React Native version: 0.64.2
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Android 11 on Pixel 4 Emulator

## Reproducible Demo

https://github.com/dillpixel/navigation-bar-demo

**Comment by swabbass** [comment]
Hey, thanks for the report, we are testing react-native-navigation with ReactNative 0.64, soon it will be ready, for now, can you kindly verify that this issue does not happen on ReactNative 0.63? (the version we support for now).

**Comment by phuongwd** [comment]
@swabbass just confirm, it's happening on RN@0.63.4 and RRN@7.18.1.
I have to use layout.backgroundColor for temporary fix

**Comment by swabbass** [comment]
> Just a note here, hiding the navigation bar works in the playground app because there you have bottomtabs and if you have bottomtabs visible and then do mergeOptions to set visibility to false for navigationBar then it works fine, no space is left and bar is completely gone. If you do not have any bottomtabs then you get the problem in this bug report. I have experimented with https://github.com/dillpixel/navigation-bar-demo to find a workaround and can push a branch if needed that show when it works.

This is really appreciated info, thanks for demo and thanks for the explanation which will help a lot figuring out what is happening!!

**Comment by bertrand-caron** [comment]
Hi team, first of all thanks for your hard work. Is this supposed to be fixed in 7.24.0? Just tried it this morning and I'm still seeing the white gap at the bottom of the screen.

**Comment by bertrand-caron** [comment]
> Just a note here, hiding the navigation bar works in the playground app because there you have bottomtabs and if you have bottomtabs visible and then do mergeOptions to set visibility to false for navigationBar then it works fine, no space is left and bar is completely gone. If you do not have any bottomtabs then you get the problem in this bug report. I have experimented with https://github.com/dillpixel/navigation-bar-demo to find a workaround and can push a branch if needed that show when it works.

@MagnusEklof  That would be much appreciated.

**Comment by bertrand-caron** [comment]
Not sure if this will help, but on 7.24.0, if I put the app to the background and then foreground again, the gap is gone.

**Comment by swabbass** [comment]
I'll try to debug this via @MagnusEklof own branch, sorry for the inconvenience.

**Comment by bertrand-caron** [comment]
> I'll try to debug this via @MagnusEklof own branch, sorry for the inconvenience.

Don't apologize, this is open-source, if I am not happy I can go and fix it myself :)
Really appreciate your time though.

**Comment by bertrand-caron** [comment]
I've finally found a workaround: if I instantiate all my components with `{options : {bottomTabs: {visible: false}}}`, it works!

This might also help you debug the issue.

**Comment by swabbass** [comment]
@bertrand-caron Appreciated! thx for the info, I'm working on finding a proper solution.

**Comment by swabbass** [comment]
@bertrand-caron 
I'm trying with the demo project here and it seems to be fixed, just updated the RNN version (`7.24.0` (has transparent status bar bug) or latest snapshot `7.24.0-snapshot.459` status bar bug fixed) and did a clean `npm install` and `npm run start -- --reset-cache`, it just works, am I missing something? since the project is reproducible if I'm using old versions of RNN.

What I would advise about the project, is to move `setDefaultOptions` outside of `registerAppLaunchedListener` callback, to be set just at the beginning.

https://user-images.githubusercontent.com/7227793/144992402-722fde6f-0cb4-4fbe-93dd-41507d31c8c0.mov

**Comment by bertrand-caron** [comment]
@swabbass Sorry I won't have time to a detailed answer tonight (I'm on AEST timezone), but I believe the gap only appeared when pushing a new screen on top of a stack (not when setting the stack root). Hopefully someone else on this thread can chime in to help reproduce the issue.

**Comment by MagnusEklof** [comment]
Will try this new release, not sure when I have time though but the plan is to do it this week at least.

**Comment by swabbass** [comment]
I forked the demo and updated it, and tested it with push/pop flow, feel free to use it and update it, and please make sure you have clean install and reset cache before start working after upgrading a version 
[Demo fork
](https://github.com/swabbass/navigation-bar-demo)

https://user-images.githubusercontent.com/7227793/144995576-7579a1ed-47d5-4425-8f97-bb0bb86df4c4.mov
