### ISSUE TITLE
How create navigator button with badge

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#72]
Thanks you!

**Comment by guyca** [comment]
`this.props.navigator.setTabBadge` did not work for you?

**Comment by agumack** [comment]
@guyca 
I am mean a SingleScreenApp, not Tab
I want set badge for button right(or left) 

```
this.props.navigator.setButtons({
  leftButtons: [], // see "Adding buttons to the navigator" below for format (optional)
  rightButtons: [], // see "Adding buttons to the navigator" below for format (optional)
  animated: true // does the change have transition animation or does it happen immediately (optional)
});

```

**Comment by guyca** [comment]
Hey @agumack It's not supported at the moment. As far as I'm aware, We don't have plans to add this functionality any time soon, but if there's a demand - a PR would be awesome.

**Comment by agumack** [comment]
I think it important @guyca 
I am coding app about ecommerce. Need badge for Items cart :(

**Comment by guyca** [comment]
@agumack I completely agree it's a viable use case for many apps. Would love to see this feature added, but since we don't require it for our apps here at Wix, I don't see how one of the devs here will develope it.

**Comment by agumack** [comment]
@guyca can you add this feature for v2.0? 
Thank you so much
