### ISSUE TITLE
How to call function onclose in modal. I want to modal close and call a function on navigation to a subpage. Thanks all

### ISSUE THREAD

**Issue by trung1008** [wix/react-native-navigation#720]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
duplicate
