### ISSUE TITLE
Type mismatch after upgrading to ReactNative 0.65.0-rc.3

### ISSUE THREAD

**Issue by keremoge** [wix/react-native-navigation#7204]
I upgraded react-native from 0.63.4 to **0.65.0-rc.3**

but when I build android package I get this error ;

**> Task :react-native-navigation:compileReactNative63ReleaseKotlin FAILED**

e: /mobile-branch/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ReactImageMatrixAnimator.kt: (31, 21): Type mismatch: inferred type is ScalingUtils.ScaleType? but ScalingUtils.ScaleType was expected

e: /mobile-branch/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/views/element/animators/ReactImageMatrixAnimator.kt: (32, 21): Type mismatch: inferred type is ScalingUtils.ScaleType? but ScalingUtils.ScaleType was expected

The rows at `ReactImageMatrixAnimator.kt` :
```
           val fromBounds = calculateBounds(from, parentScaleX, parentScalyY)
            hierarchy.actualImageScaleType = InterpolatingScaleType(
                    getScaleType(from), ------> 31
                    getScaleType(to), ---------> 32
                    fromBounds,
                    calculateBounds(to),
                    PointF(from.width * parentScaleX / 2f, from.height * parentScalyY / 2f),
                    PointF(to.width / 2f, to.height / 2f)
            )
```

**Comment by swabbass** [comment]
Thx for the report, 
I saw that they changedthe policy to strict for null safety in fresco, https://github.com/facebook/fresco/commit/f5cb99281cbc74e5100b633dc3ed6c0d6499925c#diff-43e31f004f4f0ac1a1820b5fefa54217b9b4a0c9e88733ce5ac9b83c8c37d4b2L18 ,

but at the same time `actualImageScaleType` might return null: https://github.com/facebook/fresco/blob/v2.5.0/drawee/src/main/java/com/facebook/drawee/generic/GenericDraweeHierarchy.java#L407

from here we can see that there is a default value from ReactImageView:
see: https://github.com/facebook/react-native/blob/v0.65.0-rc.3/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageView.java#L225

A draft PR with type fix will help
