### ISSUE TITLE
How to call parent function from modal

### ISSUE THREAD

**Issue by trung1008** [wix/react-native-navigation#721]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by kyle-ssg** [comment]
By parent I assume you mean the screen that initiated the modal:

```
 //'Parent' View
  this.props.navigator.showModal({
            screen: "modal",
            title: 'Mr Modal',
            passProps: { myFunc:this.myFunc }
        });
```

```
//modal
this.props.myFunc()
```

**Comment by trung1008** [comment]
thanks u (y)
