### ISSUE TITLE
Overlay cannot show if it has been dismissed within 0-1000ms

### ISSUE THREAD

**Issue by jessypouliot98** [wix/react-native-navigation#7214]
## 🐛 Bug Report

In our app, we use overlay to show a full screen loading to prevent users from interacting with the app.
What happens is were are showing and dismissing an Overlay alot during initialisation

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

FYI: LoaderOverlay.show() and LoaderOverlay.dismiss() are static functions that calls RNN's functions with the componentName assigned to the class component.

LoaderOverlay has a component name of "Overlay.LoaderOverlay"

LoaderOverlay.isActive is false by default and is updated when LoaderOverlay is mounted and unmounted with the componentDidMount and componentWillUnmount lifecycle events

```javascript
        setInterval(async () => {
            let r = null;

            if (!LoaderOverlay.isActive) {
                console.log('show');
                r = await LoaderOverlay.show();
            } else {
                console.log('hide');
                r = await LoaderOverlay.dismiss();
            }
        }, 450);
```
The above code will log
show - **hide** - show - show - show - show [...]

What is seen is: Loader showing, loader dismissing, then nothing happens.
I think the delay depends on device/calls, but it this example fails at 450ms, but does actually show/hide infinetly on >=600ms

steps to reproduce:

- show overlay
- wait < 400ms
- dismiss overlay
- wait < 400ms
- show overlay
- etc.
- etc.

## Expected behavior

I expect to be able to show overlay anytime.
This has also been noticed in the past with 2 seperate overlay where I was dismissing a loader and showing another type 
 of overlay right after the dismiss.

## Actual Behavior

When trying to show an overlay too soon after dismissing an overlay, all overlays are temporarily exempt from showing until the delay between the last dismiss is long enough for it to be able to show a new overlay.

## Your Environment

- React Native Navigation version: 7.14.0
- React Native version: 0.64.2
- Platform(s) (iOS, Android, or both?): iOS, Android
- Device info (Simulator/Device? OS version? Debug/Release?): iphone 12 mini (14.?), iOS simulator (14.3), Android device (10)

## Reproducible Demo

```javascript
        setInterval(async () => {
            let r = null;

            if (!LoaderOverlay.isActive) {
                console.log('show');
                r = await LoaderOverlay.show();
            } else {
                console.log('hide');
                r = await LoaderOverlay.dismiss();
            }
        }, 450);
```

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by swabbass** [comment]
Hey @jessypouliot98 , thanks for the report and sorry for the inconvenience, I don't have access to `LoaderOverlay` can you kindly, submit a link to a minimal project that has the issue reproduced, you can fork our playground, which is highly recommended.

**Comment by jessypouliot98** [comment]
@swabbass do you mind explaining how I can use the playground ?

```
jessyp98@macbook-pro Workspace % git clone https://github.com/wix/react-native-navigation.git
Cloning into 'react-native-navigation'...
remote: Enumerating objects: 157609, done.
remote: Counting objects: 100% (21386/21386), done.
remote: Compressing objects: 100% (1577/1577), done.
remote: Total 157609 (delta 11208), reused 20842 (delta 10884), pack-reused 136223
Receiving objects: 100% (157609/157609), 99.52 MiB | 7.07 MiB/s, done.
Resolving deltas: 100% (88514/88514), done.
jessyp98@macbook-pro Workspace % cd react-native-navigation 
jessyp98@macbook-pro react-native-navigation % npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-native-navigation@7.18.0
npm ERR! Found: @react-native-community/datetimepicker@3.5.2
npm ERR! node_modules/@react-native-community/datetimepicker
npm ERR!   dev @react-native-community/datetimepicker@"^3.4.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @react-native-community/datetimepicker@"^2.1.0" from react-native-ui-lib@5.11.0
npm ERR! node_modules/react-native-ui-lib
npm ERR!   dev react-native-ui-lib@"5.11.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/jessyp98/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jessyp98/.npm/_logs/2021-08-19T19_43_42_853Z-debug.log
jessyp98@macbook-pro react-native-navigation %         
```

**Comment by swabbass** [comment]
What npm version do you use? I did a fresh npm install now and it looks ok, I'm using npm 6.14.13, also you can just remove ` "@react-native-community/datetimepicker": "^3.4.7"` from `package.json` if it still causing issues.

**Comment by jessypouliot98** [comment]
@swabbass 

jessyp98@macbook-pro activix-crm-mobile % npm -v
7.19.1
jessyp98@macbook-pro activix-crm-mobile % node -v
v14.15.4

**Comment by jessypouliot98** [comment]
Removing `@react-native-community/datetimepicker` didn't work but `npm i --force` worked

**Comment by jessypouliot98** [comment]
we had a debounce when we ment to use a throttle 😅  My bad no issues here
