### ISSUE TITLE
Android Keypad issue: Keypad in Android is pushing the contents of Modal to top and showing the background screen while dismissing the keypad

### ISSUE THREAD

**Issue by RajeshUppara** [wix/react-native-navigation#722]
Keypad in Android is pushing the contents of Modal to top and showing the background screen while dismissing the keypad and is working fine in IOS.

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 2.0.0-experimental.170
* React Native version: 0.38.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by guns2410** [comment]
Having exactly the same issue. @RajeshUppara did you manage to solve this?

**Comment by guyca** [comment]
@guns2410 
Modals have softInputMode set to adjustResize, if set your root view to be a ScrollView, it should push the view as expected so that the focused TextInput is at the bottom of the screen, right above the keyboard.
By the way, starting from RN 0.42 this will be the default behavior of all RN apps as well.

**Comment by ugiacoman** [comment]
@guyca Is there a reason Modals have `softInputMode` set to `adjustResize`? It is leading to inconsistent behavior throughout our app.

**Comment by rawrmaan** [comment]
Yeah I need to use adjustPan or adjustNothing for my modal, but I can't. The way it displays right now is pretty bad. This is frustrating.

**Comment by binbinla** [comment]
Is there any certain solution?
