### ISSUE TITLE
No clear way to go back

### ISSUE THREAD

**Issue by Lenny4** [wix/react-native-navigation#7226]
I'm looking for a way to display a custom back button to the user without using the back button in the [TopBar](https://wix.github.io/react-native-navigation/api/options-stack/).

Here what I would like to do:
```javascript
// Component1
await Navigation.push(props.componentId, {
  component: {
    name: 'Component2',
  },
});
```
```javascript
// Component2
<Button onPress={Navigation.goBack}>
    Go back
</Button>
```
But there is no `Navigation.goBack` function.

How am I able to do this ? I couldn't find it in the documentation.

Thanks.

**Comment by yogevbd** [comment]
Use [Navigation.pop](https://wix.github.io/react-native-navigation/api/stack#pop) function.
