### ISSUE TITLE
[Android] RNN 7.19.0 -  Top bar not extending behind status bar anymore on mergeOptions 

### ISSUE THREAD

**Issue by manuhook** [wix/react-native-navigation#7232]
## 🐛 Bug Report

Because of https://github.com/wix/react-native-navigation/commit/e63bfd2bb7e29d86fe89ed93a75382bc2fcc299c
When doing a mergeOptions on a screen where statusBar drawBehind is set to true in static options() or in Navigation.setDefaultOptions() the Top bar is not extending behind status bar anymore.

@MBrianLoc

The only solution now to avoid this problem is to set again in each mergeOptions statusBar> drawBehind: true, even if there is no change.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. Push a screen with statusBar> drawBehind: true
2. Do a mergeOption
3. You will see that the top bar is not extending behind status bar after the mergeOption. The padding above the topbar is set to 0.

## Expected behavior

When doing a mergeOptions on a screen where statusBar drawBehind is set to true in static options() or in Navigation.setDefaultOptions() the Top bar should extend behind status bar and the padding above the topbar shouldn't be set to 0.

## Actual Behavior

When doing a mergeOptions on a screen where statusBar drawBehind is set to true in static options() or in Navigation.setDefaultOptions() the Top bar the padding above the topbar is set to 0.

## Your Environment

- React Native Navigation version: 7.19.0
- React Native version: 0.65.1
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device, Debug & Release

## Reproducible Demo

(Paste the link to an example repo and exact instructions to reproduce the issue.)

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  &nbsp; No, I don’t have the knowledge and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by yogevbd** [comment]
We should consider revert that [commit](https://github.com/wix/react-native-navigation/pull/6991). @swabbass what do you think?

**Comment by swabbass** [comment]
> We should consider revert that [commit](https://github.com/wix/react-native-navigation/pull/6991). @swabbass what do you think?

It needs to be fixed, rather than revert, by tmw we will have a fix :]

**Comment by manuhook** [comment]
Thanks @swabbass for the fix, however I'm still having the issue with 7.19.1, I'm going to check if I can reproduce it on the playground
