### ISSUE TITLE
[iOS] componentDidDisappear not fired when showing modal over modal

### ISSUE THREAD

**Issue by robrechtme** [wix/react-native-navigation#7233]
## 🐛 Bug Report

On iOS with the `pageSheet` modals, the `componentDidDisappear` is not fired when showing a modal over another modal.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

(Write your steps here:)

1. On iOS 13 and above
1. Show a modal A (`Navigation.showModal`) with default `modalPresentationStyle: 'pageSheet'` .
1. Register a `componentDidDisappear` listener on modal A.
1. Push a modal B over modal A (`Navigation.showModal`).
1. `componentDidDisappear` is not triggered.

## Expected behavior

The `componentDidDisappear` event should be fired.
This is the case on Android and when setting `modalPresentationStyle: 'fullScreen'` .

## Actual Behavior

The `componentDidDisappear` event is not fired.

## Your Environment

- React Native Navigation version: 7.19.0
- React Native version: 0.64.2
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): iPhone 12 mini (iOS 14.5) Simulator

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✅   &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by yogevbd** [comment]
The second modal (B) is also a `pageSheet`? If so, this is not a bug as when presenting a `pageSheet` modal, the underneath screen is still partially visible

**Comment by robrechtme** [comment]
The second modal is indeed a `pageSheet`. I did not expect this to be normal behaviour, but I understand the reasoning behind it. 

Thanks for your response.
