### ISSUE TITLE
Cannot find symbol @NonNull - Android won't build

### ISSUE THREAD

**Issue by danieljvdm** [wix/react-native-navigation#724]
I'm trying to build the Android version of my app (iOS runs fine) and after following the setup steps for Android. However, I get this error:

    /Users/daniel/dev/myapp/android/app/src/main/java/com/prayerrequest/MainApplication.java:27: error: cannot find symbol
       @NonNull
        ^
      symbol:   class NonNull
      location: class MainApplication
    /Users/daniel/dev/myapp/android/app/src/main/java/com/myapp/MainActivity.java:17: error: method does not override or implement a method from a supertype
        @Override
        ^
    2 errors
    :app:compileDebugJavaWithJavac FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':app:compileDebugJavaWithJavac'.

My `MainApplication.java` looks like this:

    package com.myapp;

    import android.app.Application;
    import android.util.Log;

    import android.support.annotation.Nullable;

    import com.facebook.react.ReactApplication;
    import com.oblador.vectoricons.VectorIconsPackage;
    import com.facebook.react.ReactInstanceManager;
    import com.facebook.react.ReactNativeHost;
    import com.facebook.react.ReactPackage;
    import com.facebook.react.shell.MainReactPackage;

    import com.reactnativenavigation.NavigationApplication;

    import java.util.Arrays;
    import java.util.List;

      public class MainApplication extends NavigationApplication {
        @Override
         public boolean isDebug() {
             // Make sure you are using BuildConfig from your own application
             return BuildConfig.DEBUG;
         }

         @NonNull
         @Override
         public List<ReactPackage> createAdditionalReactPackages() {
             // Add the packages you require here.
             // No need to add RnnPackage and MainReactPackage
             return null;
         }
      }

---
### Environment
* React Native Navigation version: 2.0.0-experimental.199
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by Lichwa** [comment]
@danieljvdm How did you solve this? I'm having exact same problem right now.

**Comment by danieljvdm** [comment]
I actually just removed the @NonNull annotation

**Comment by kyle-ssg** [comment]
import android.support.annotation.Nullable;

**Comment by jbolter** [comment]
@Lichwa Thanks for the fix!  The Android install documentation is a little sparse.

**Comment by Guangxingtianxia** [comment]
> I actually just removed the @nonnull annotation
Good job !
