### ISSUE TITLE
DynamicColorIOS not working anymore with react-native 0.65.1

### ISSUE THREAD

**Issue by magrinj** [wix/react-native-navigation#7247]
## 🐛 Bug Report

Using `DynamicColorIOS` inside `Navigation.setDefaultOptions` break after upgrading to react-native `0.65.1`.

It seams fo happen since `0.65.0` as some changes has been made on `DynamicColorIOS` to add `highContrast` feature.

https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#ios-specific-1
https://github.com/facebook/react-native/commit/4b9d9dda270acd4e0314f40490c699ffd0f6e30e

Everything was working properly on react-native `0.64`.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. Put some `DynamicColorIOS` inside `Navigation.setDefaultOptions`

## Expected behavior

No error thrown working properly.

## Actual Behavior

The following error is thrown:
```
JSON value 'NoColor' of type NSString cannot be converted to a UIColor. Did you forget to call processColor() on the JS side?
JSON value '{
    dynamic =     {
        dark = NoColor;
        light = NoColor;
    };
}' of type NSMutableDictionary cannot be converted to a UIColor. Expected an iOS dynamic appearance aware color.
```

## Your Environment

- React Native Navigation version: 7.19.1
- React Native version: 0.65.1
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator - Debug

## Reproducible Demo

```javascript
Navigation.setDefaultOptions({
    layout: {
      componentBackgroundColor: DynamicColorIOS({dark: 'black', light: 'white'}),
    },
);
```

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by karlsander** [comment]
I'm pretty sure this regression was introduced by this PR https://github.com/wix/react-native-navigation/pull/7178 in 7.19.0 and not react-native 0.65.0 When I downgrade, the issue is solved.

**Comment by magrinj** [comment]
@karlsander I think you're right, I've updated both libraries at the same time but didn't point the right spot 😏

**Comment by yogevbd** [comment]
I fixed the issue but I recommend you using our own dark mode support. 
That's how you can do it for both Android and iOS:
```js
Navigation.setDefaultOptions({
    layout: {
      componentBackgroundColor: { dark: 'black', light: 'white' },
    },
);
```

**Comment by rosskhanas** [comment]
@yogevbd since 7.19.0 `PlatformColor` not working anymore as well. Is it expected?

This is what cause the error:

> largeTitle: {
>   color: PlatformColor("labelColor"),
> }

![image](https://user-images.githubusercontent.com/10609041/132241031-a8020254-7272-4ee5-b2d2-609842c51bbd.png)

**Comment by rosskhanas** [comment]
Quite interesting, this line crashes:

> `color: PlatformColor("labelColor")`

But this is ok:

> `color: { dark: PlatformColor("labelColor"), light: PlatformColor("labelColor") }`

**Comment by swabbass** [comment]
It should not crash, @yogevbd I think it was working in this [commit](https://github.com/wix/react-native-navigation/blob/df117842edbd797e2a3476da40acc863f5d311f4/playground/src/commons/Colors.ts#L10), at least for system colours, and not custom native defined colours, what we are missing here?
