### ISSUE TITLE
[iOS] useEffect not called on bottom tab screen with "together" or "afterInitialTab" configuration

### ISSUE THREAD

**Issue by dariuscosden** [wix/react-native-navigation#7267]
## 🐛 Bug Report

On iOS, when using bottom tabs with `together` or `afterInitialTab` loading configuration, the logs do show every screen being rendered as expected, however any `useEffect` in a screen that is not the currently selected tab will not fire until the user navigates to that tab.

## To Reproduce

Follow the guide [here](https://wix.github.io/react-native-navigation/docs/bottomTabs) without any extra configuration.

## Expected behavior

The screens show as being rendered in the logs and any react lifecycle hooks (`useEffect`, `componentDidMount`, etc) should fire even if the user is not currently on that tab.

## Actual Behavior

The screens are being rendered correctly according to the logs, but no react lifecycle hooks are fired. `useEffect` is not fired until user navigates to selected tab. On Android this works fine.

## Your Environment

- React Native Navigation version: 7.18.1
- React Native version: 0.64.1
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator Debug

**Comment by svbutko** [comment]
Fixed starting from version `7.22.0` with both modes
