### ISSUE TITLE
registerModalDismissedListener returns a stackId instead of a componentId

### ISSUE THREAD

**Issue by robinvandenberghe** [wix/react-native-navigation#7269]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. Copy the reproducible demo code into an existing project.
2. Log the given componentId from the listener
3. See that it is a 'Stack...' instead of a 'Component...'

## Expected behavior

It should return a componentId (e.g. 'Component...')

## Actual Behavior

It returns a stackId (e.g. 'Stack...')

## Your Environment

- React Native Navigation version: 7.20.0
- React Native version: 0.64.2
- Platform(s) (iOS, Android, or both?): both
- Device info (Simulator/Device? OS version? Debug/Release?): Produced on iPhone 12 emulator with iOS 14.8 and a Xiaomi Mi Pad 4 with Android 8.1 among others.

## Reproducible Demo

This function was written in a hook to run a handler when a certain modal is dismissed.

```
 const modalDismissedSubscription = Navigation.events().registerModalDismissedListener(
    ({ componentId }) => {
      if ( hookComponentId === componentId) {
        handler();
      }
    },
  );
```

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✅  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by mateioprea** [comment]
I think that this is expected behaviour. If you have a stack in your modal, when you're dismissing it, you're dismissing the entire stack not the component.

**Comment by bitcrumb** [comment]
@mateioprea So how would one be able to know from inside a pushed screen (x levels deep) that the modal to which it belongs is being dismissed? How would you know what stackId to expect?

**Comment by N3TC4T** [comment]
this may help for a temporary solution 

https://github.com/wix/react-native-navigation/issues/6605#issuecomment-703553016

**Comment by bitcrumb** [comment]
We worked around this by providing a fixed stack ID ourselves in the layout config & passing that ID down the component hierarchy to be able to use it in the registerModalDismissedListener method.

**Comment by swabbass** [comment]
> We worked around this by providing a fixed stack ID ourselves in the layout config & passing that ID down the component hierarchy to be able to use it in the registerModalDismissedListener method.

@bitcrumb Thx, that's how it should be done!

**Comment by yogevbd** [comment]
And this is how you show modal with a predefined id:

```js
Navigation.showModal({
  stack: {
    id: 'predefined-id', // Add your id here
    children: [
      {
        component: {
          name: Screens.OrientationDetect,
        },
      },
    ],
  },
});
```
