### ISSUE TITLE
[iOS] iOS 15 not work params to topBar -> noBorder

### ISSUE THREAD

**Issue by aspidvip** [wix/react-native-navigation#7281]
Hello!!!

"react-native": "0.63.4",
"react-native-navigation": "7.21.0",

xCode 13

`component: {
          id: SEARCH_MAIN,
          name: SEARCH_MAIN,
          options: {
            statusBar: {
              backgroundColor: colors.WHITE,
            },
            topBar: {
              noBorder: true, // is not work
              elevation: 0,
              background: {
                color: 'transparent',
              },
            },
            layout: {
              backgroundColor: colors.WHITE,
            },
          },
        },

`
<img width="308" alt="Снимок экрана 2021-10-02 в 16 26 02" src="https://user-images.githubusercontent.com/22605655/135706406-fa3fbd18-5d34-41b2-bd3b-770e7dc7d646.png">

**Comment by mateioprea** [comment]
Add scrollEdgeAppearance: {noBorder:true} and it will work

**Comment by aspidvip** [comment]
thank you
