### ISSUE TITLE
[iOS 15] not wotk bottomTabs->translucent: true

### ISSUE THREAD

**Issue by aspidvip** [wix/react-native-navigation#7283]
Hello!!!

"react-native": "0.66.0",
"react-native-navigation": "7.21.0",

xCode 13

`options: {
bottomTabs: {
              translucent: Platform.OS === 'ios',
            },
}
`

**Comment by aspidvip** [comment]
<img width="308" alt="Снимок экрана 2021-10-04 в 16 10 21" src="https://user-images.githubusercontent.com/22605655/135802138-ad3a5af8-d76c-4808-80bd-57ab987c7d76.png">

**Comment by svbutko** [comment]
@aspidvip, can you try the same behaviour with `7.22.0`?

**Comment by svbutko** [comment]
Fixed starting from `7.22.0`
<img width="502" alt="image" src="https://user-images.githubusercontent.com/14828004/135967239-f23afb5a-13da-4759-9b99-1f5e0fccf73c.png">
