### ISSUE TITLE
upgrade 7.21.0  —> 7.22.0  Error: Unable to resolve module react-native-ui-lib

### ISSUE THREAD

**Issue by MikePodgorniy** [wix/react-native-navigation#7289]
**Error after upgrade 7.21.0  —> 7.22.0**
Why add an extra dependency for a simple View?

node_modules/react-native-navigation/lib/dist/components/Modal.js
import { View } from 'react-native-ui-lib';

https://github.com/wix/react-native-navigation/commit/588e908af9a9a470a2a68fbbcb444513871e7fb5#diff-b90f2f58ce45df51df2ec086f35fbd03f7c1d90c1dfe94cfc1ed6577ddf6813d

## 🐛 Bug Report

error: Error: Unable to resolve module react-native-ui-lib from node_modules/react-native-navigation/lib/dist/components/Modal.js: react-native-ui-lib could not be found within the project or in these directories:
  node_modules/react-native-navigation/node_modules
  node_modules
  ../../node_modules

**Comment by svbutko** [comment]
https://github.com/wix/react-native-navigation/pull/7286
