### ISSUE TITLE
null cannot be cast to non-null type com.reactnativenavigation.NavigationActivity

### ISSUE THREAD

**Issue by nextriot** [wix/react-native-navigation#7290]
## 🐛 Bug Report

Upgrading from 7.21.0 -> 7.22.1 causes above error on Android only. 
No other change was made other than upgrading RNN package.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## Actual Behavior

![IMG_1018](https://user-images.githubusercontent.com/711457/136082719-db6e70bb-53f3-4d63-aaf9-e2e0aee3f52b.jpg)

## Your Environment

- React Native Navigation version: 7.22.1
- React Native version: 0.64.1
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Android Galaxy S20

**EDIT:**
Happens on launch, right after splash screen.
Doesn't seem to be related to modals.

Reproducible demo repo: https://github.com/nextriot/rnn-example-repo

**Comment by svbutko** [comment]
Can you share reproducible demo?
At what point does it happen? When switching screens, or on start?

It's hard to operate using only this screenshot

**Comment by nextriot** [comment]
Apologies for the sparse info. 
Here's a link to a reproducible demo repo: https://github.com/nextriot/rnn-example-repo

It happens on startup, right after the splash screen.
I do use showModal on the initial tab that gets shown, but it doesn't seem to be related.
