### ISSUE TITLE
custom topBar componenet is not working properly

### ISSUE THREAD

**Issue by varadig** [wix/react-native-navigation#7301]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

YES

## To Reproduce

(Write your steps here:)

1. Step 1...
If I setup the topBar custom component in the `setDefaultOptions` it's working well.
1. Step 2...
2If I set the topBar custom component somwhere else (where I want to use it), it's not visible/rendered/...etc
1. Step 3...

## Expected behavior

Setup custom topbar component per stack

## Actual Behavior

The custom topBar component is just visible if I setup in the `setDefaultOptions`

## Your Environment

- React Native Navigation version: 7.22.3
- React Native version: 0.66.0
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator , iOS 15, Debug

## Reproducible Demo

```
root: {
				sideMenu: {
					id: "MAIN",
					options: {
						topBar: {visible: true}
					},
					center: {
						bottomTabs: {
							id: 'BOTTOM_TABS_LAYOUT',
							options: {
								topBar: {
										background: {
											component: {
												name: Component.topbarBackground
											}
										}
									},
	
//.....						},
```

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

<!--
  Remember that first-time contributors are welcome! 🙌 Feel free to reach us out on https://discord.gg/DhkZjq2
  👋 Have a great day and thank you for the bug report!
--

>
<img width="1495" alt="Screenshot 2021-10-09 at 07 07 12" src="https://user-images.githubusercontent.com/6317148/136645139-3cef38a3-915c-4cb6-a7ed-64c3054b359d.png">
<img width="1250" alt="Screenshot 2021-10-09 at 07 05 34" src="https://user-images.githubusercontent.com/6317148/136645140-b0cf7dcf-d302-4533-881c-c1c7bcad1018.png">

**Comment by varadig** [comment]
<img width="1495" alt="Screenshot 2021-10-09 at 07 07 12" src="https://user-images.githubusercontent.com/6317148/136645147-1d52fd81-dea6-48c9-ab80-2ca7a8085d52.png">
<img width="1250" alt="Screenshot 2021-10-09 at 07 05 34" src="https://user-images.githubusercontent.com/6317148/136645151-d8e1d0e1-080a-4ca1-83b8-ecd8f80f03a1.png">

**Comment by svbutko** [comment]
@varadig can you try to do the same with iOS 14.x emulator to see whether this issue persists there?

**Comment by varadig** [comment]
@svbutko , thanks for the reply!
I have to download that ios simulator version, and I will come back with the results

**Comment by svbutko** [comment]
@varadig I checked it now and it looks ok on iOS 15 if setting them in component like so:

```typescript jsx
Main.options = {
  topBar: {
    background: {
      component: {
        name: Pages.topBar.name,
      },
    },
    largeTitle: {
      visible: true,
    },
    title: {
      text: localization.pages.main,
    },
  },
};
```
Or in `roots` like so:

```typescript
Navigation.setRoot({
    root: {
      bottomTabs: {
        id: Pages.tabs.id,
        children: [
          {
            stack: {
              id: Tabs.main.id,
              children: [
                {
                  component: {
                    id: Pages.main.id,
                    name: Pages.main.name,
                    options: {
                      topBar: {
                        background: {
                          component: {
                            name: Pages.topBar.name,
                          },
                        },
                      },
                    },
                  },
                },
              ],
```

**Comment by svbutko** [comment]
You have `sideMenu` in your case, right?

**Comment by svbutko** [comment]
![](https://user-images.githubusercontent.com/6317148/136645147-1d52fd81-dea6-48c9-ab80-2ca7a8085d52.png)

Based on your screenshot you're setting `topBar` option somehow in `bottomTabs`

**Comment by svbutko** [comment]
@varadig you should set this options in options where you're setting `topBar: {visible: true}` or on page or like I did in previous example

**Comment by svbutko** [comment]
@varadig found where it happens and made a PR to fix it, now need just to wait until it will be accepted and published

**Comment by varadig** [comment]
Thank you!

**Comment by varadig** [comment]
more info:
If I setup the custom topBar component, it''s not just not visible, but cover the default one.
Also I don't know, why the topbar height is double then the normal.

https://user-images.githubusercontent.com/6317148/136697668-d2d202d6-cd22-4f3a-9e16-f1f7de9bf9e2.mov
