### ISSUE TITLE
registerModalDismissedListener not working with dismissAllModals

### ISSUE THREAD

**Issue by marcshilling** [wix/react-native-navigation#7304]
## 🐛 Bug Report

Somewhere in the upgrade from 7.12.0 to 7.22.1, `Navigation.events().registerModalDismissedListener` stopped firing on iOS when `Navigation.dismissAllModals()` is used to dismiss more than 1 modal.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. Use `Navigation.events().registerModalDismissedListener()` to register a listener. Add some logging in there.
2. Present 2 modals on top of each other
3. Use `Navigation.dismissAllModals()`

## Expected behavior

The modals are dismissed and the modal dismissed listener event fires with `modalsDismissed = 2`

## Actual Behavior

The modals are dismissed but the listener event is not fired **on iOS only**. Android fires the event.

## Your Environment

- React Native Navigation version: 7.22.1
- React Native version: 0.64.2
- Platform(s) (iOS, Android, or both?): iOS, Xcode 13
- Device info (Simulator/Device? OS version? Debug/Release?): iOS 15, simulator or device, release or debug

When I roll back to RNN 7.12.0, the listener works as expected.

**Comment by svbutko** [comment]
@marcshilling I'm trying to reproduce your case and it's all working fine.

React Native Navigation version: 7.22.3
React Native version: 0.66.0
iOS 15 simulator

Can you make a reproduction demo if possible so that we can find where the issue is hidden?

**Comment by svbutko** [comment]
> I was able to dig into this more and I have a working reproduction: https://github.com/marcshilling/rnn-modal-dismiss-event-bug. I've narrowed it down to an issue with React Native's `<Modal>` component. In a current modal screen, If I present an overlay that is a `<Modal>`, and then dismiss that overlay followed by using `Navigation.dismissAllModals()`, you'll notice the modal dismiss event is not fired. If I remove the `<Modal>`, or use `Navigation.dismissModal(componentId)` instead, the event fires.
> 
> Obviously this is a weird edge case and a weird design by my app to be using `<Modal>` in conjunction with an overlay. With this new knowledge, I have a workaround (remove `<Modal>`)...so I would be fine closing this ticket, but my repo does seem to showcase a valid issue.
> 
> If I had to guess, it was probably #7156 that introduced this, since that was added after 7.12 (my last working version). There is a particular change in there that makes it only send the modal dismiss event if there is a componentId.
> 
> @svbutko

1) Personally, I'd get rid of RN's <Modal/> since it's buggy enough itself in favour of RNN's [Overlay](https://wix.github.io/react-native-navigation/docs/overlay) or [Modal](https://wix.github.io/react-native-navigation/docs/modal) (based on UI/X which you need)

2) I added PR to your repo to fix your case, take a look there
