### ISSUE TITLE
Topbar TintColor not working in iOS 15

### ISSUE THREAD

**Issue by SanthoshDhandapani** [wix/react-native-navigation#7306]
Building with Xcode 13 broken the top bar background color in ios 15. The same app works perfectly on versions prior to ios 15.
`options: {
                topBar: {
                  elevation: 0,
                  noBorder: true,
                  background: {
                    color: Colors.BLUE_PRIMARY,
                  },
                  rightButtons: [
                    {
                      id: 'HeaderMenu',
                      component: {
                        name: 'HeaderMenu',
                      },
                    },
                  ],
                },
              }`
<img width="905" alt="Screenshot 2021-10-11 at 7 41 36 PM" src="https://user-images.githubusercontent.com/10140204/136805926-d080b1ea-9920-480a-9c1c-c3653d1e15cd.png">

I made a patch for this in lib/ios/TopBarPresenter.m Line number 71
`- (void)setBackgroundColor:(UIColor *)backgroundColor {
    _backgroundColor = backgroundColor;
    [self updateBackgroundAppearance];
	if (@available(iOS 15, *)) {
		self.navigationController.view.backgroundColor = _backgroundColor;
	}
}`

After this patch, it is working as expected, kindly update a proper fix for this.

**Comment by code-by** [comment]
Hi!
I have similar issue but can't figure out how to solve using suggested change in lib due legacy v.3 still using because project only RN 0.60.5 (
could you help? thank you

**Comment by svbutko** [comment]
> Hi!
> 
> I have similar issue but can't figure out how to solve using suggested change in lib due legacy v.3 still using because project only RN 0.60.5 (
> 
> could you help? thank you

Hi, unfortunately iOS 15 specific changes are only available on the latest version of RNN, so the only way to have proper support is to update the version

**Comment by code-by** [comment]
sorry for offtopic question, will latest version of wix/RNN work with RN 0.60.5 or one should also update RN to latest version?

**Comment by swabbass** [comment]
> sorry for offtopic question, will latest version of wix/RNN work with RN 0.60.5 or one should also update RN to latest version?

We are now targeting 0.66.2, you can use >= 0.64, but it is mostly the same as 0.66.2.
