### ISSUE TITLE
[iOS] [iOS < 14] Navigation.pop(componentId) fires on multiple components

### ISSUE THREAD

**Issue by Reeywhaar** [wix/react-native-navigation#7311]
## 🐛 Bug Report

Given that application has bottom tabs layout.
Bottom tab screen (Parent) has handled back navigation (i.e has `popStackOnPress` set to `false`).
If we push on that stack another screen (Child) and call `Navigation.pop(Child.componentId)`. Two NavigationButtonPressed events will be fired:
1. first is `{buttonId: "RNN.back", componentId: Parent.componentId}`
2. second is `{buttonId: "RNN.back", componentId: Child.componentId}`

This maybe somehow related to https://github.com/wix/react-native-navigation/issues/7147

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

yes

## To Reproduce

Reproduction repo: https://github.com/Reeywhaar/rnn-double-back-event-bug

1. Install and run on iOS with iOS < 14 (in my case it is 11.4)
2. Select second tab **Example**
3. Push **Push Example screen**
4. Push back button **< Main** 
5. Watch logs, there should be two lines **BACK NAVIGATION CALLED ON COMPONENT ID %COMPONENTID%**

## Expected behavior

Only one line should be present in log

## Actual Behavior

There are two lines, one for **Parent** and one for **Child**. Thus **Parent** somehow receives **RNN.back** navigation button pressed event.

Video on ios < 14 **(BUG EXISTS)**

https://user-images.githubusercontent.com/884649/136994982-aabc587f-bd87-43ab-bd5f-11029beb660c.mov

Video on ios 14.5 **(BUG NOT PRESENT)**

https://user-images.githubusercontent.com/884649/136997391-bd7f74a5-2077-44f5-b21d-5b952f2148f5.mov

## Your Environment

- React Native Navigation version: 7.21.0, 7.22.0
- React Native version: 0.65.1
- Platform(s) (iOS, Android, or both?): IOS < 14.0
- Device info (Simulator/Device? OS version? Debug/Release?): Any Simulator with iOS < 14

## Reproducible Demo

https://github.com/Reeywhaar/rnn-double-back-event-bug

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue. (Don't think I have lot of knowledge in iOS)

**edit**: fixed misleading screen recording on ios 14.5

**Comment by Reeywhaar** [comment]
Done a little research and what I know:
Calling **Navigation.pop(id)** results in following stack:
- [RNNCommandsHandler.pop](https://github.com/wix/react-native-navigation/blob/e53c866b54be3cb86ee67c32b7f61ef489d57ada/lib/ios/RNNCommandsHandler.m#L281)
- [UIViewController.popAnimated](https://github.com/wix/react-native-navigation/blob/b53f13c60fe6498ad1690adf1dfd7509f602965c/lib/ios/UINavigationController%2BRNNCommands.m#L30)
- [RNNStackController.popViewControllerAnimated](https://github.com/wix/react-native-navigation/blob/e53c866b54be3cb86ee67c32b7f61ef489d57ada/lib/ios/RNNStackController.m#L43)
- [UIViewController.popViewControllerAnimated](https://developer.apple.com/documentation/uikit/uinavigationcontroller/1621886-popviewcontrolleranimated?language=objc)

... and after that I see another call to [RNNStackController.navigationBarShouldPopItem](https://github.com/wix/react-native-navigation/blob/e53c866b54be3cb86ee67c32b7f61ef489d57ada/lib/ios/RNNStackController.m#L48) where [self.getCurrentChild.layoutInfo.componentId](https://github.com/wix/react-native-navigation/blob/e53c866b54be3cb86ee67c32b7f61ef489d57ada/lib/ios/RNNStackController.m#L52) resolves to id of **Parent**.

Not quite understand who initiates the call to **RNNStackController.navigationBarShouldPopItem**? Last call was to iOS built in, so is there any event listener? I've tried to find but no luck.

**Comment by yogevbd** [comment]
It looks like a bug in iOS itself. on old iOS versions, `navigationBar:shouldPopItem` called when it doesn't need to get called and in the wrong timing. It first remove the child and only then ask if it should be removed which doesn't make any sense.

I'm trying to find a workaround. Will keep you updated

**Comment by Nehal-Sanklecha** [comment]
@Reeywhaar  Did you find any solution to this? I'm facing similar problem
