### ISSUE TITLE
Navigation.events().registerComponentDidAppearListener doesn't work in RN 0.66

### ISSUE THREAD

**Issue by meDev-lab** [wix/react-native-navigation#7315]
### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

yes

## To Reproduce

1. Upgrade react-native from 0.63.0 to 0.66.0 and react-native-navigation from 7.16.0  to 7.23, and run on Android emulator
1. After load app i should was alert() , but i didn't saw anything

## Expected behavior

 After load app should work ```Navigation.events().registerComponentDidAppearListener``` and we will be get alert() 

## Actual Behavior

In preview versions (RN 0.63.0) this code work fine, but after upgrade RN to 0.66 version he is broken (no error, no warning - just not work)
```
Navigation.events().registerComponentDidAppearListener(() => {
    alert(componentId);
    // getData();
  });
```
He should make alert, after we open this modal component, 

![image](https://user-images.githubusercontent.com/55193940/137203761-d2c404f4-160b-4df5-afb9-7d13e4a0b8bb.png)

Also i tried this lib [react-native-navigation-hooks](https://underscopeio.github.io/react-native-navigation-hooks/docs/before-you-start) but also to no avail (

## Your Environment

- React Native Navigation version: 7.23.1
- React Native version: 0.66.0
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Any Simulator with Android >25

**Comment by swabbass** [comment]
Hey, did you manage to check it on iOS? 

We are working on upgrading our library to support RN 0.66 we will take this into consideration, follow #7305.

**Comment by swabbass** [comment]
Thx a lot, we are going to check this issue soon as part of upgrading to React Native 0.66.0 :]

**Comment by Ryabchikus** [comment]
@N3TC4T , Thanks a lot for response.
If everything works correctly for you , then we have a problem in the configuration of the navigator(or something else).
Just now we are moving legacy project from RN@0.59&&RNN@2.27.5 to actual versions and got problem with componentDidAppear/componentDidDisappear calling
I try to create minimal reproducible project  in reasonable time

**Comment by meDev-lab** [comment]
> We found out a couple of issues with `componentDidAppear` event specifically when having animations disabled for the device or via options for `showModal` or `push`, and it is fixed in the PR mentioned in this issue.
> 
> I hope that our case was similar to the one mentioned here, soon we will introduce RNN with RN 0.66.0 and then you can try it and report here :].

Of course we used ```showModal``` 
i think it's it :)

We will try again after new release and write result here 
Thanks all :)

**Comment by tarouboy** [comment]
I have similar cases being reported. 

After upgrading to RN0.66, the functions inside componentDidAppear are not firing on a small amount of Android devices. However I cannot reproduce as well.

I guess I will move all the code to componentDidMount for now.

**Comment by swabbass** [comment]
> I have similar cases being reported.
> 
> After upgrading to RN0.66, the functions inside componentDidAppear are not firing on a small amount of Android devices. However I cannot reproduce as well.
> 
> I guess I will move all the code to componentDidMount for now.

We did not release our RNN version with RN 0.66.x support till now, but you can try master, update your package.json with react-native-navigation and navigation master and report back what do you see.

**Comment by tarouboy** [comment]
> > I have similar cases being reported.
> 
> > 
> 
> > After upgrading to RN0.66, the functions inside componentDidAppear are not firing on a small amount of Android devices. However I cannot reproduce as well.
> 
> > 
> 
> > I guess I will move all the code to componentDidMount for now.
> 
> 
> 
> We did not release our RNN version with RN 0.66.x support till now, but you can try master, update your package.json with react-native-navigation and navigation master and report back what do you see.
> 
> 
> 
> @tarouboy

The point is I cannot reproduce as well. It's hard to ask our users to test for us. 

How confident do you think the master has resolved the issue?

**Comment by swabbass** [comment]
@tarouboy Well, I managed to reproduce similar behaviour, where `componentDidAppear` did not get called when the component opened, now master confidence is ok for such issue, we are working on stabilizing the android part, so soon you will get a release that will include a fix, then you can update and monitor if such issue exists.
