### ISSUE TITLE
[ANDROID] Overriding MainApplication methods

### ISSUE THREAD

**Issue by danieljvdm** [wix/react-native-navigation#732]
The Realm library (as well as probably many others) requires an override method in the `MainApplication.java` class. It looks like so:

     @Override
     protected List getPackages() {
       return Arrays.asList(
         new RealmReactPackage(),
         new MainReactPackage()
       );
     }

The problem is, because we're subclassing `NavigationApplication`, this method doesn't override anything and thus doesn't accomplish what it's supposed to, rendering my app useless. I don't understand the Android system at all, so I can't find out how to get this to work myself. Any ideas?

**Comment by guyca** [comment]
As described in [step 5](https://github.com/wix/react-native-navigation/wiki/Installation---Android#important) in the Android installation guide - you should add all packages you require in `createAdditionalReactPackages` method.

It would look something like this:

```java
@Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return Arrays.asList(
     new RealmReactPackage()
    );
  }
```

**Comment by danieljvdm** [comment]
As a heads up, the above code won't work, you need to do this:

```List<ReactPackage> list = new ArrayList<ReactPackage>() {{
             add(new RealmReactPackage());
         }};```
