### ISSUE TITLE
Use Android 12 splashscreen API

### ISSUE THREAD

**Issue by fiznool** [wix/react-native-navigation#7337]
## 🚀 Feature

Android 12 has introduced a [new SplashScreen API](https://developer.android.com/guide/topics/ui/splash-screen), with an AndroidX compat library for older versions. In a nutshell, this allows developers to hook up an animatable splash screen, and provides an API for dismissing the splash screen when the app is ready to be used.

If this library were to use the new SplashScreen API, apps using RNN could add splash screen support quite easily.

- [x] <strong>Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?</strong>

## Motivation

From the [Android docs](https://developer.android.com/guide/topics/ui/splash-screen/migrate):

> If you do not migrate your app [to the new SplashScreen API], your app launch experience on Android 12 and higher will be either degraded or may have unintended results

## Pitch

Changes to RNN codebase (mostly as per [these Android docs](https://developer.android.com/guide/topics/ui/splash-screen/migrate)):

- `compileSdkVersion` should be set to 31.
- `'androidx.core:core-splashscreen:1.0.0-alpha01'` should be added as a dependency to `build.gradle`.
- New documentation should be added to guide developers on adding the necessary splash screen assets.
- The `onCreate` method in `NavigationActivity.java` should be updated as follows:
  - Install the splash screen: `SplashScreen.installSplashScreen(this)`.

The splash screen will be automatically dismissed when the app draws its first frame, so providing this happens when the React Native side calls `Navigation.setRoot`, the splash screen will remain until this time.

Changes to documentation:

- Section added on how to customise the Android splash screen. By default, the splash screen will consist of the launcher icon, centered in the screen, with a white background. This can be customised according to the [Android docs](https://developer.android.com/guide/topics/ui/splash-screen/migrate#migrate_your_splash_screen_implementation), briefly the following needs to be done:
  - Create a new theme in `android/app/src/main/res/values/styles.xml` which extends `Theme.SplashScreen`
  - Add the necessary details here to customise the icon, animation etc.
  - Set the `postSplashScreenTheme` value to the main `AppTheme`
  - Update `AndroidManifest.xml` so that the `MainApplication` theme is this new splash theme
- Section added on how to customise the exit animation of the splash screen, as per the [Android docs](https://developer.android.com/guide/topics/ui/splash-screen#suspend-drawing)

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by swabbass** [comment]
Looks cool, I think moving to 31 can have some breaking changes.

If we have a contributor who can add such a cool feature it would be nice, We will offer a helpful guide to make the process smoother and easier.
