### ISSUE TITLE
Android: Janky header bars on first screen render

### ISSUE THREAD

**Issue by dbi1** [wix/react-native-navigation#7338]
Hello,

I'm running the playground app on AndroidStudio's Android emulator (Pixel 5 API 29, qemu-system-x86_64).

When I click on a tab bar icon for the first time, the requested screen renders in a fairly janky way. The header seems to come in from the top in a jagged fashion, and after it appears, the main section of the screen shows up.

The odd thing is that this is only an issue the first time I click on a tab bar icon. After clicking on another tab bar icon, and then clicking the original tab bar icon again, the original screen renders perfectly without any "jankiness".

Is there a solution for this problem?

Thank you for building this library!

**Comment by swabbass** [comment]
Hey, appreciated, can you please provide a minimal project to reproduce the janky behaviour you described.
