### ISSUE TITLE
statusBar is black with translucent true option when showOverlay on some Android devices

### ISSUE THREAD

**Issue by flexsurfer** [wix/react-native-navigation#7339]
## 🐛 Bug Report

showOverlay with statusBar translucent true, makes statusBar black on some Android devices

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

yes

## Expected behavior

statusBar has correct color

![telegram-cloud-photo-size-2-5195033218670245126-y](https://user-images.githubusercontent.com/11790366/140046664-06852a7a-5b99-4eed-af5c-730810efe8f3.jpg)

## Actual Behavior

statusBar is black 

![screenshot](https://user-images.githubusercontent.com/11790366/140042381-16b30dbf-9d80-4bc4-a885-2d8178153d0e.jpg)

## Your Environment

- React Native Navigation version: 7.23.1
- React Native version: 0.63.4
- Platform(s) (iOS, Android, or both?): Android 6.0.1
- Device info (Simulator/Device? OS version? Debug/Release?): Readme Note 3

**Comment by flexsurfer** [comment]
PR - translucent true
Nightly - translucent false

- on Android 9 (Galaxy A10):
![nightly1 png 2021-11-03 12-11-05](https://user-images.githubusercontent.com/4557972/140050456-91da626e-8687-4988-94f0-0cbd1f001a06.png)

- on Android10 (Samsung Galaxy S20+):
![samsung10](https://user-images.githubusercontent.com/4557972/140050728-699ad89e-8735-4bed-a256-c0b2e7e44fe7.png)

- on Android10(Xiaomi Redmi Note9):
![chin_night_10 png 2021-11-03 12-14-57](https://user-images.githubusercontent.com/4557972/140050895-9ba85401-fa88-455a-ac1d-80e4af1d026e.png)

- on Android11 (Google Pixel 5):
![nightly_11 png 2021-11-03 12-16-48](https://user-images.githubusercontent.com/4557972/140051065-705e6632-b6b8-47ab-b635-21135006d737.png)

**Comment by ducheng0** [comment]
Can confirm the same issue exists on the Samsung A50 phone, and Galaxy Tab A shows the primary color of the app instead of white or black, in the case above, that would be blue.

**Comment by swabbass** [comment]
what SDK is your project target?

**Comment by flexsurfer** [comment]
`targetSdkVersion=30`

**Comment by swabbass** [comment]
Soon it will be fixed, in the mentioned PR.

**Comment by flexsurfer** [comment]
hey @swabbass thank you for the fixes, i just tried latest release, and it just ignores `statusBar translucent` , is that expected ? so now its not translucent for any android version

**Comment by flexsurfer** [comment]
translucent true

![image](https://user-images.githubusercontent.com/11790366/148094456-c5e3b33e-9b8b-4159-b6c6-1b7d8ed2da2a.png)

**Comment by flexsurfer** [comment]
i filed an issue https://github.com/wix/react-native-navigation/issues/7418
