### ISSUE TITLE
hardware back button support for bottoms

### ISSUE THREAD

**Issue by aliraza-noon** [wix/react-native-navigation#7348]
## 🐛 Bug Report

When switching between bottom tabs it does not go back to previously selected tab when i press hardware back button, please check popular apps like

* youtube
* facebook
* twitter

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

(Write your steps here:)

1. Setup a demo app with 2 bottoms 
2. Tap on 1st tab first and then switch to 2nd tab
4. Try pressing hardware back button

## Expected behavior

It should take you back to previously selected tab

## Actual Behavior

It closes the app when you press the hardware back button

## Your Environment

- React Native Navigation version: 7.23.1
- React Native version: 0.66.0
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Pixel2 api version 30 debug

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by phuongwd** [comment]
I have handled that on my app. Im prefer the behavior "always to the first (default) tab" when press on hardware back button.
Just checked, the Material Design no longer mentions back button behavior.

| Popular apps  | back behavior |
| ------------- | ------------- |
| Google Photos | quit app on back press on any tab  |
| Youtube, Facebook | previously selected tab |
| Airbnb, Google+, Play Books | pressing back takes you always to the first (default) tab, pressing again closes the app |

**Comment by swabbass** [comment]
This should be converted to a discussion (on the side menu "convert to discussion" as an idea, and maybe you can suggest adding a new option for hardware back like:
```javascript
const options = {
  hardwareBackButton:{
    dismissModalOnPress: true, //exists
    popStackOnPress: true, // exists
    bottomTabsBehaviour: 'exit' | 'previous' | 'first', // new
  }
}
```

**Comment by aliraza-noon** [comment]
@swabbass I don't see the "convert to discussion"
