### ISSUE TITLE
IOS 15, noBorder not working.

### ISSUE THREAD

**Issue by suupham2506** [wix/react-native-navigation#7355]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. Step 1...
1. Step 2...
1. Step 3...

## Expected behavior
When I set noBorder: true the border on ios15 should be not displayed.

## Actual Behavior
Topbar's border on ios15 is still displayed when noBorder: true. It works fine on IOS version < 15

## Your Environment

- React Native Navigation version: 7.23.0
- React Native version: 0.64.2
- Platform(s) (iOS, Android, or both?): IOS only
- Device info (Simulator/Device? OS version? Debug/Release?): Both simulator and real device.

## Reproducible Demo

(Paste the link to an example repo and exact instructions to reproduce the issue.)

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by LYevhen** [comment]
I can confirm the same on:
- React Native Navigation version: 7.13.0, updated to 7.23.1
- Platform(s) :  IOS 15.0, 15.1 only
- Device info: IOS 15 simulator, iOS 15.1 device
- React Native version: "0.63.4"
- folowed instructions in [manual](https://wix.github.io/react-native-navigation/7.11.2/api/options-migration/#navbarnoborder)
- no overlay components initialized
![image](https://user-images.githubusercontent.com/44976185/142260838-d52a7832-4460-498a-811e-c9bf44550bb2.png)

**Comment by yogevbd** [comment]
You should also add `topBar.scrollEdgeAppearance.noBorder` option. 

```js
topBar: {
  scrollEdgeAppearance: {
    noBorder: true,
  },
}
```

**Comment by yogevbd** [comment]
Will add this to our documentation as well, just saw that it's missing.
