### ISSUE TITLE
Android - cannot dismissOverlay when it contains a stack

### ISSUE THREAD

**Issue by zabojad** [wix/react-native-navigation#7358]
## 🐛 Bug Report

I'm trying to workaround the Android API 30 bugs : https://github.com/wix/react-native-navigation/issues/7225

To do so, I wrap my overlay's components in a stack. The layout issue is gone but when doing so, I cannot dismiss the overlay...

## To Reproduce

Add somewhere in your code:

    Navigation.showOverlay({ stack: { children: [ MyScreen ]  } });

Then, in MyScreen code, add:

    Navigation.dismissOverlay(props.componentId); // that will have no effect except a warning for unhandled promise...

## Expected behavior

This:

    Navigation.dismissOverlay(props.componentId);  

...  should work even when overlay contain a stack.

## Actual Behavior

This: 

    Navigation.dismissOverlay(props.componentId);  

... does not work when the overlay contains a stack.

## Your Environment

- React Native Navigation version: 7.12.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): both

**Comment by zabojad** [comment]
Note: the same code with showModal / dismissModal works. This happens only with overlays.

**Comment by swabbass** [comment]
It is fixed here #7343. soon it will be merged to master and then you can test it.
