### ISSUE TITLE
Status Bar - Overlay cut due to upgrade targetSDKversion upgate to 29 to 30

### ISSUE THREAD

**Issue by Mitesh-2009** [wix/react-native-navigation#7360]
![WhatsApp Image 2021-11-20 at 12 46 47 PM](https://user-images.githubusercontent.com/34374930/142722727-19a46a7c-ca76-4224-b4e8-25e9a4e3874d.jpeg)

Top status bar cut when overlay open see above screenshot

and make changes below
![Screenshot 2021-11-19 at 7 06 34 PM](https://user-images.githubusercontent.com/34374930/142722759-7ba749cc-c7af-4328-9fda-43de0024a349.png)

I tried to set status bar value as below but not working and also upgrade lib 7.16.0 to 7.23.1 and then try below solution but not working and I have tested this in my redmi note 8 pro mobile
statusBar: {
        visible: false,
        drawBehind: true,
        translucent: false,
      }

**Comment by swabbass** [comment]
Fixed here #7343. should be merged soon.
