### ISSUE TITLE
How do you add/remove components to the bottomTabs children without rerendering all children

### ISSUE THREAD

**Issue by FrederickEngelhardt** [wix/react-native-navigation#7374]
Is there a way to efficiently update the BottomTabs component tree without causing the other tabs to rerender? 

Example you click a button and add a new item to the tabs. So far the only way I'm seeing is to use setRoot. But that causes my previously mounted components to reset. Also the large the number of tabs the higher change the app crashes. 

This question is related to my post [here](https://stackoverflow.com/questions/70073552/react-native-navigation-how-to-add-an-item-to-drawer-navigation).

Is there a way to update the BottomTabs but not cause all tabs to rerender (ie using setRoot)?

**Comment by N3TC4T** [comment]
have you tried using `tabsAttachMode` with `onSwitchToTab` value ?

```
Controlling tab loading
By default, all tabs are mounted at the same time. This can have a negative impact on performance since screens which are not visible to the user are mounted.

The order in which tabs are mounted can be configured with the tabsAttachMode option:

together - all tabs are mounted at the same time, this is the default behavior.
afterInitialTab - after initial tab is mounted, other tabs are mounted.
onSwitchToTab - initial tab is mounted, other tabs are mounted when the user navigates to them for the first time.
```

https://wix.github.io/react-native-navigation/api/options-bottomTabs/#tabsattachmode

**Comment by FrederickEngelhardt** [comment]
I have, the issue is that whenever I add a new tab the previous tabs will all refresh. `onSwitchToTab` would solve the memory issue of having too many tabs loaded on a app refresh, but not when adding new tabs.

Example use case:
1. User clicks addTab button
2. Add tab regenerates all previously mounted bottomTabs with `Navigation.setRoot`. All components are remounted. This causes all user session progress in each tab to effectively be reset. Session progress would have to be saved across tabs.

My hope is there is a way to have a method to add,replace,remove a bottomTab without regenerating all components. Example `tabs.push(ID)` or `tabs.remove(ID)`

**Comment by swabbass** [comment]
can you, kindly, simulate your issue with a minimal project or in our playground? we would like to enhance our performance and help others achieve performant flows using navigation.
