### ISSUE TITLE
negative sizes are not supported in the flow layout

### ISSUE THREAD

**Issue by harleenarora** [wix/react-native-navigation#7377]
Carsh log::
`Fatal Exception: NSInternalInconsistencyException
negative sizes are not supported in the flow layout`

`Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x9904c __exceptionPreprocess
1  libobjc.A.dylib                0x15f54 objc_exception_throw
2  Foundation                     0x1306cc _userInfoForFileAndLine
3  UIKitCore                      0x471bb0 -[UICollectionViewFlowLayout _getSizingInfosWithExistingSizingDictionary:]
4  UIKitCore                      0x218634 -[UICollectionViewFlowLayout _fetchItemsInfoForRect:]
5  UIKitCore                      0x2100ec -[UICollectionViewFlowLayout prepareLayout]
6  UIKitCore                      0x175a3c -[UICollectionViewData _prepareToLoadData]
7  UIKitCore                      0x3ecf9c -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:collectionViewAnimator:]
8  UIKitCore                      0x372700 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:animationHandler:]
9  Test project                   0x121fe4 __48-[QBAssetsViewController photoLibraryDidChange:]_block_invoke + 410 (QBAssetsViewController.m:410)
10 libdispatch.dylib              0x2914 _dispatch_call_block_and_release
11 libdispatch.dylib              0x4660 _dispatch_client_callout
12 libdispatch.dylib              0x12b60 _dispatch_main_queue_callback_4CF
13 CoreFoundation                 0x51cd4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
14 CoreFoundation                 0xbeac __CFRunLoopRun
15 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific
16 GraphicsServices               0x138c GSEventRunModal
17 UIKitCore                      0x5196a8 -[UIApplication _run]
18 UIKitCore                      0x2987f4 UIApplicationMain
19 Test project                   0x5900 main + 7 (main.m:7)
20 ???                            0x1040b9a24 (Missing)`

**React-native Info**
System:
    OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 30.97 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.10 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**React-native-navigation::** ^7.20.0

**Device Info::** 
Device
Model:iPhone 13 Pro Max
Orientation: Face Up
RAM free: 1.56 GB
Disk free: 64.17 GB
Operating System
Version:15.1.1
Orientation: Portrait
Jailbroken:No
Crash

How to fixed crash log.

**Comment by yogevbd** [comment]
Look like this crash is coming from [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) and not from react-native-navigation itself.
