### ISSUE TITLE
Android: v7.24.0 statusBar does not respect transparency anymore

### ISSUE THREAD

**Issue by nicost71** [wix/react-native-navigation#7387]
## 🐛 Bug Report

When upgrading from 7.23.1 to 7.24.0, the StatusBar on Android does not respect "transparency/alpha value" anymore.

I have set the following statusBar Options:

    statusBar: {
      visible: true,
      style: 'light',
      backgroundColor: 'rgba(255,255,255,0)',
      drawBehind: true,
      blur: true,
    },

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

YES

## To Reproduce

Build app with statusBar settings mentioned above.

## Expected behavior

Screen with v.7.23.1:

I don't know whether this was a bug in version 7.23.1 or not, but in 7.23.1 the statusBar with this setting was transparent.

![Screenshot 2021-12-03 at 14 27 17](https://user-images.githubusercontent.com/3907474/144610160-56d085ba-30b8-4de9-a8ec-2a370b8ad177.png)

When scrolled:

![Screenshot 2021-12-03 at 14 26 00](https://user-images.githubusercontent.com/3907474/144610185-1b29b5f8-5ce4-4376-beec-a0dac7ebcb2f.png)

## Actual Behavior

With the same settings on v 7.24.0, the background color now is white (e.g. rgb(255,255,255) ).

![screen](https://user-images.githubusercontent.com/3907474/144609880-1842b3e3-bb1b-417f-b6c0-0ba0199757dd.png)

If I add translucent = true, the statusBar now is translucent but with the white color:

![Screenshot 2021-12-03 at 14 26 39](https://user-images.githubusercontent.com/3907474/144610227-52886f25-8ef5-4b43-93dd-70e9b4db21d4.png)

If I remove the backgroundColor, the statusBar becomes dark (still translucent):

![Screenshot 2021-12-03 at 14 26 24](https://user-images.githubusercontent.com/3907474/144610259-e8e142e9-4b30-4a5a-9b87-d19f4dec203b.png)

My goal is to get a completely transparent statusbar, however this does not seem possible anymore?.

## Your Environment

- React Native Navigation version: 7.24.0
- React Native version: 0.65.1
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator + Device, Debug+Release mode, tested on Huawei P20, Samsung Galaxy S9

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅   &nbsp; No, I don’t have the time/knowledge and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by swabbass** [comment]
It will be possible :] soon thx for reporting such a bug..

**Comment by swabbass** [comment]
Fixed here #7390.

**Comment by swabbass** [comment]
checkout `7.24.0-snapshot.459`, report here if it fixed, soon `7.24.1` will be released

**Comment by nicost71** [comment]
@swabbass - works like charm, thx a lot! Looking forward to `7.24.1`
