### ISSUE TITLE
[Android] Content shifting up when keyboard appear

### ISSUE THREAD

**Issue by N3TC4T** [wix/react-native-navigation#7402]
## 🐛 Bug Report

Content always shifting up when keyboard appears, even with setting `windowSoftInputMode` to `adjustNothing`.

removing `keyboardInsets` is a temporary solution but I'm not sure if it will effect other situations or not.

https://github.com/wix/react-native-navigation/blob/fb6d02897156e4dbbc4ba1e29d76bfce0f320f4b/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java#L146

## To Reproduce

(Write your steps here:)

1. Set `windowSoftInputMode` to `adjustNothing`
2. Focus on TextInput
3. Keyboard pushing content to top

## Expected behavior
Keyboard visibility should NOT effect content visibility when `windowSoftInputMode` set to `adjustNothing`.

## Your Environment

- React Native Navigation version: `7.24.1`
- React Native version: `0.66.1`
- Platform(s): `Android`
- Device info: `Android Device running SDK 30`

**Comment by swabbass** [comment]
We should take  `windowSoftInputMode` options like `adjustNothing` into consideration, you are right, soon it will be fixed.

**Comment by thuongtv-vn** [comment]
> We should take `windowSoftInputMode` options like `adjustNothing` into consideration, you are right, soon it will be fixed.

Hi @swabbass Do you know how to android consider "windowSoftInputMode" normally? You are right, we should consider this option as well.

**Comment by swabbass** [comment]
we might use `getActivity().getWindow().getAttributes().softInputMode;` and take it into consideration, soon we will have a PR for this

**Comment by alan-nakagiri** [comment]
Hello! I just wanted to share that I too have seen an issue with `softInputMode` and RNN `7.25.0`. 

Instead my app is set to `adjustPan` and it does not seem to recognize it, and it is behaving like `adjustResize` is set instead.
