### ISSUE TITLE
[Android 9][7.24.1+] Popping with open keyboard does not uses screenspace of the keyboard

### ISSUE THREAD

**Issue by Ainias** [wix/react-native-navigation#7427]
[[## 🐛 Bug Report

I don't know how to describe it very well. If your keyboard is open and you pop to a previous screen, the keyboard hides, but the space the keyboard used is not filled from the screen. View the screencasts

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)? 

yes

## To Reproduce

1. Create a screen A
2. Open a screen B from A with a text-input
3. Focus text-input such that the keyboard pops up
4. Use the back button inside the topbar to return to screen A
5. The keyboard hides, but the space the keyboard used is not used by the app again
  - If screen A has an input-component which is autofocused, the keyboard stays open and nothing is wrong

## Expected behavior

The screen which is popped to uses the full display space

## Actual Behavior

See step 5 and the screen casts. I removed the `selectable={true}` inside the profile-screen-cast (See https://github.com/wix/react-native-navigation/issues/7426 for referecne) (the person infos inside the casts are dummy data and relates to no real person)

![keyboardHalfScreenLogin](https://user-images.githubusercontent.com/17934715/150654754-2ec2302c-571f-41cf-807a-087cb856d38c.gif)
![keyboardSpaceProfile](https://user-images.githubusercontent.com/17934715/150654758-b47a1af1-de36-47f6-92df-4746cb3ada58.gif)

## Your Environment

- React Native Navigation version: 7.24.1,7.24.2, 7.24.3-hotfix.1, 7.25.1 
- React Native version: 0.66.3
- Platform(s) (iOS, Android, or both?): Android 9 
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator and real device, Android 9 (10+ in simulator was fine, I have no real device with Android 10+), Debug & Release

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by swabbass** [comment]
Hey @Ainias, I tried the described behaviour in our playground and could not reproduce it on Android 9 Emulator, can you please try to reproduce it in our playground, or maybe share a minimal reproducible demo project so we can debug the issue?

**Comment by Ainias** [comment]
@swabbass I've made a minimal reproducible demo here: https://github.com/churchtools/rnnBug
I hope this helps

**Comment by swabbass** [comment]
Thanks, @Ainias, soon it will be checked and fixed :].
