### ISSUE TITLE
Android windowSoftInputMode is ignored

### ISSUE THREAD

**Issue by kabus202** [wix/react-native-navigation#7428]
## 🐛 Bug Report

after the 7.24.0 release the windowSoftInputMode is ignored  for android. For example android:windowSoftInputMode="adjustPan" has no effect at all. 

Last working version: 7.23.1

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. In AndroidManifest.xml set android:windowSoftInputMode  to android:windowSoftInputMode="adjustPan" 
1. Add a <TextInput> component
1. run

## Expected behavior

Is that the Keyboard is not pushed up. 

## Actual Behavior

Keyboard getting pushed up

**Comment by alan-nakagiri** [comment]
@yogevbd I'd like to reopen this issue. It looks like the recent release may have reintroduced this issue for Android 30.

Below are some screenshots of what I am seeing. The same code except swapping emulators and RNN versions.

**Android 30, v7.25.4 with AdjustPan**
![adjustPan30-25-4](https://user-images.githubusercontent.com/11300359/157148221-d097e5cd-8e08-4266-95e5-735c83af8624.png)

**Android 30, v7.26.0 with AdjustPan**
![adjustPan30-26](https://user-images.githubusercontent.com/11300359/157148623-4e42f560-f4c2-4fb1-bc17-1bf5ef2ce7c9.png)

**Android 29, v7.26 and with AdjustPan**
![adjustPan29-26](https://user-images.githubusercontent.com/11300359/157148729-8a6bdfdc-685b-4728-a0c7-eea81951561c.png)

**Android 29, v7.25.4 with AdjustPan**
![adjustPan29](https://user-images.githubusercontent.com/11300359/157149879-371197bb-dc3a-4b18-abbc-846bca8386fb.png)

I double checked I had the setups right, but it looks like Android 30 w/ 7.26 does not work but Android 29 with 7.26 does, while Android 30 w/ 7.25.4 does work but Android 29 w/ 7.25.4 does not.

**Comment by stachu2k** [comment]
I have the same problem. My app has android:windowSoftInputMode="adjustPan" and it's ignored. Version 7.26.0.

**Comment by marf** [comment]
Same issue here

**Comment by lethienhung** [comment]
Same issue here

**Comment by huynqjmango360** [comment]
yeb. Android is suck!

**Comment by kabus202** [comment]
@alan-nakagiri did you manage to find a workaround?

**Comment by alan-nakagiri** [comment]
@kabus202 we ended up having to fork the repo and made an adjustment to the `ComponentViewController.java` file

**Comment by kabus202** [comment]
Thanks @alan-nakagiri for your reply. I manage to fix it within the component itself.

**Comment by MattEveritt** [comment]
Hi @kabus202 , would really appreciate it if you could share how you managed to fix this? Im experiencing the same issue.

**Comment by marcshilling** [comment]
Setting `android:windowSoftInputMode="adjustPan"` has no effect, it just behaves the same way as adjustResize. This used to work with this library. I suspect it broke when I upgraded from 7.32.1 to 7.37.2. Issue should not be closed IMO.

**Comment by shaneinlogik** [comment]
> @kabus202 we ended up having to fork the repo and made an adjustment to the `ComponentViewController.java` file

Are you able to share a link to the fork?

**Comment by marcshilling** [comment]
> @kabus202 we ended up having to fork the repo and made an adjustment to the `ComponentViewController.java` file

@alan-nakagiri can you please share you solution?

**Comment by shaneinlogik** [comment]
@alan-nakagiri I think that will help. Thanks!

**Comment by ngducviet1** [comment]
> Sorry, the company I was with when we wrote the fork is no longer around.
> 
> I was able to find this snippet that may be helpful. No idea if it's is still relevant or works anymore. Note, I have not touched this code or ran in a very long time.
> 
> <img alt="image" width="752" src="https://private-user-images.githubusercontent.com/11300359/398823502-9d9764ed-fdad-4e80-9593-ad7d98e743eb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY0NTcwNzEsIm5iZiI6MTc1NjQ1Njc3MSwicGF0aCI6Ii8xMTMwMDM1OS8zOTg4MjM1MDItOWQ5NzY0ZWQtZmRhZC00ZTgwLTk1OTMtYWQ3ZDk4ZTc0M2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODI5VDA4MzkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiM2I3MTAzNzdmMDUyNTYzM2RmNTdhN2JmNWRkZDJlM2ZjNGVhYWEyMGYyNDcyNDQwMTAxYzU5ZDNkZjhkMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TaQd-BGsezp2DMcJBz3azRS_9Vb3PlcW0u-gd1UHZu0">

thanks, it work for me. 
Navigation.setDefaultOptions({
    layout: {
      adjustResize: false, // remember add this
    },
  });

**Comment by marcshilling** [comment]
Thanks to @alan-nakagiri and @ngducviet1 I was able to get this working. I needed to make @alan-nakagiri's patch and then I am able to change the adjustResize behavior on a per-screen basis using
```
Navigation.mergeOptions(componentId, {
  layout: {
    adjustResize: true/false
  },
})
```

Here's the actual patch if anyone needs rather than translating from a screenshot 😂 :
```
diff --git a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
index b9e7d27..f83b6d1 100644
--- a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
+++ b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
@@ -180,10 +180,13 @@ public class ComponentViewController extends ChildController<ComponentLayout> im
     @Override
     protected WindowInsetsCompat onApplyWindowInsets(View view, WindowInsetsCompat insets) {
         final Insets systemBarsInsets = insets.getInsets(WindowInsetsCompat.Type.systemBars());
+        final Options currentOptions = resolveCurrentOptions(presenter.defaultOptions);
+        final int keyboardBottomInset = currentOptions.layout.adjustResize.get(true) ?
+                insets.getInsets(WindowInsetsCompat.Type.ime()).bottom : 0;
         int systemWindowInsetTop = insets.getInsets(WindowInsetsCompat.Type.statusBars()).top +
                 insets.getInsets(WindowInsetsCompat.Type.navigationBars()).top -
                 systemBarsInsets.top;
-        int systemWindowInsetBottom = insets.getInsets(WindowInsetsCompat.Type.ime()).bottom +
+        int systemWindowInsetBottom = keyboardBottomInset +
                 insets.getInsets(WindowInsetsCompat.Type.navigationBars()).bottom -
                 systemBarsInsets.bottom;
 
```

I still maintain that this issue should not be closed and this patch probably incorporated upstream.
