### ISSUE TITLE
Bottom tabs affected by layout backgroundColor

### ISSUE THREAD

**Issue by kevinwaelkens** [wix/react-native-navigation#7455]
## 🐛 Bug Report

When adding a layout backgroundColor to the navigation options, the bottom tabs are affected by it. This means that when you add a layout backgroundColor `'white'`, the bottom tabs will be completely white. For that reason I applied a semi-transparent color as backgroundColor so you can still see the bottom tabs.

## To Reproduce

1. Run the playground application
2. Notice the bottomTabs are only 50% visible because there's a 50% red color overlay.
3. Change the `backgroundColor: 'rgba(255,0,0, .5)'` to eg. backgroundColor: 'white', and notice the bar is fully white.

## Expected behavior

I expect the bottomTab buttons to be visible.

## Actual Behavior

The bottomTab buttons are affected by the backgroundColor of the layout property.

![Screenshot 2022-02-11 at 19 27 27](https://user-images.githubusercontent.com/9056632/153649698-c109c32a-60ea-44ac-a1e6-35a07a16fc4e.png)

## Your Environment

- React Native Navigation version: 7.25.3
- React Native version: 0.66.3
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Android Emulator Android 12 API 31

## Reproducible Demo

https://github.com/kevinwaelkens/react-native-navigation/tree/bug/bottom-tabs-disappearing

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✅  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by SYoder1** [comment]
After updating to  7.25.3 I am seeing the exact same issue.

**Comment by agestaun** [comment]
Same problem

**Comment by ghashi** [comment]
version [7.25.1](https://github.com/wix/react-native-navigation/releases/tag/7.25.1) is ok

**Comment by yogevbd** [comment]
@kevinwaelkens could you please test it with [7.26.0-alpha.1](https://www.npmjs.com/package/react-native-navigation/v/7.26.0-alpha.1)? it should be stable

**Comment by kevinwaelkens** [comment]
> @kevinwaelkens could you please test it with [7.26.0-alpha.1](https://www.npmjs.com/package/react-native-navigation/v/7.26.0-alpha.1)? it should be stable

Confirmed it works, thanks for this! 🙏
