### ISSUE TITLE
leftButtons can't set the color (Android)

### ISSUE THREAD

**Issue by alexsbobylev** [wix/react-native-navigation#746]
I can not set the color for the leftButtons. I install white, anyway set black. (Only for the left button, title and the rightButtons fine). The problem only occurs on Android, iOS is fine.

![screenshot_2017-02-08-13-52-07_com altocar_1486551170434](https://cloud.githubusercontent.com/assets/4498226/22734489/f06b0576-ee06-11e6-9af3-307a8eea8b08.jpg)

## code

```
  Navigation.startSingleScreenApp({
    screen: {
      screen: screen,
      title: title,
      navigatorStyle: styles.navigatorStyle,
    },
    ...drawer,
    animationType: 'fade'
  })
```

## styles.navigatorStyle:

```
navBarBackgroundColor: '#2196F3', //#1a2238 (dark)
    navBarTextColor: '#ffffff',
    navBarButtonColor: '#ffffff',
    tabBarBackgroundColor: '#ffffff',
```

## in component

```
  setMenuButton() {
    iconsLoaded.then(() => {
      this.props.navigator.setButtons({
        leftButtons: [
          {
            id: 'sideMenu',
            icon: iconsMap['menu']
          }
        ],
        rightButtons: [
          {
            id: 'info',
            icon: iconsMap['info']
          }
        ]
      })
    })
  }
```

## iconsmap

```
const icons = {
  "search": [30, "#FFF"],
  "history": [30, "#FFF"],
  "menu": [30, "#FFF"],
  "info": [30, "#FFF"],
}

let iconsMap = {};
```

Help please, how to change leftButtons color? The problem appeared after 2.0.0-experimental.155 version updates.

---
### Environment
* React Native Navigation version: 2.0.0-experimental.209
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by kristiansoren** [comment]
We have the same issue here. Has anyone solved this?

**Comment by guyca** [comment]
@kristiansoren Sorry about the delay, I'll look into it today/tomorrow

**Comment by guyca** [comment]
@kristiansoren what version of rnn are you using?

**Comment by kristiansoren** [comment]
It was on the latest, but I see you already pushed a fix! Will you release a new version?

**Comment by guyca** [comment]
https://github.com/wix/react-native-navigation/releases
.234 contains the fix

**Comment by kristiansorens** [comment]
@guyca Just updated to v1.1.115 and got the same issue again. I can see in the docs that there's a lot of added styling options, but I can't get it to work - any ideas?

**Comment by guyca** [comment]
@kristiansoren Seems to work fine in the use cases that I checked.
I defined:
```js
static navigatorStyle = {
  navBarButtonColor: 'red'
};
```
In the screen. Also tried setting `navBarButtonColor` in `appStyle`

**Comment by kristiansoren** [comment]
@guyca It works for android if I set the leftButtons in each tab when starting the app, but then it doesn't show on iOS. To get it to work on iOS I have to set it programmatically in the view.

The bug I reported is if you only set it programmatically - it will show on both platforms, but on android it will not use the specified style and defaults to black. What we ended up doing is: 

1) Set leftButtons for each tab to make it work on android with correct color .
2) Use navigator.setButtons() in the views where I want the menu icon to work on iOS.

Is this how it is supposed to work?

**Comment by guyca** [comment]
Hey @kristiansoren 
From your description, I understand this might be a relatively big issue, could you please open a new issue and include code samples that will help me debug it?

**Comment by kristiansoren** [comment]
@guyca Yes, will do :)

**Comment by andq-ibl** [comment]
When I check the leftButton object in navigatorSetButton function in platformSepecificDeprecated.android.js, it does not contain buttonColor property although I added buttonColor property for leftButtons when I  used it on a screen. This may be the cause of this issue

**Comment by andq-ibl** [comment]
Found the problem. This is your code in LeftButton.java
![12](https://user-images.githubusercontent.com/29767799/30373479-98f799bc-98ab-11e7-99aa-8a6d45a16177.jpg)
In this image, if you already have the default icon and want to use a custom Icon, this code will always  execute the setColor for your default Icon. You must also check if a custom Icon exist to change your custom Icon color. Like this:
![13](https://user-images.githubusercontent.com/29767799/30373648-399f5418-98ac-11e7-9a45-2eee653aa1f8.jpg)

And it worked :)
