### ISSUE TITLE
Bottom Tabs Clickable but not display

### ISSUE THREAD

**Issue by Mitesh-2009** [wix/react-native-navigation#7460]
https://user-images.githubusercontent.com/34374930/154234965-adb70b15-1b7c-4bfc-a020-f3ebe0d7aa54.mov

React Native Navigation Version: 7.25.4
React Native Version: 0.67.1

Check App in android device, application login page to redirect to bottom tab page at that time bottom tab items icon not display.

**Comment by SYoder1** [comment]
I think this is exactly the same as https://github.com/wix/react-native-navigation/issues/7455.

Try and remove the `backgroundColor` on the `layout` object

**Comment by Mitesh-2009** [comment]
Thanks @SYoder1 , Its working....
