### ISSUE TITLE
[v7] [iOS] Crash when largeTitle.visible = false 

### ISSUE THREAD

**Issue by zainspresso** [wix/react-native-navigation#7474]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

(Write your steps here:)

1. Set options.largeTitle.visible to false

## Expected behavior

A small title in the navigation without a crash.

(Write what you thought would happen.)

## Actual Behavior

Crash with Exception '-[NSTaggedPointerString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x82a10297712b6d29' was thrown while invoking push on target RNNBridgeModule

BTW:

This works and renders a small navigation top bar without text:
`topBar: {
          visible: true,
          largeTitle: {
            visible: false,
          },
        },`

This does **NOT** and causes a crash:
`topBar: {
          visible: true,
          title: 'test',
          largeTitle: {
            visible: false,
          },
        },`

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- React Native Navigation version: 7.25.0
- React Native version: 0.66.4
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Debug, 12 Pro Max, iOS 15

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✅  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by danilobuerger** [comment]
In my opinion the crash is caused by setting `title = "test"`. This is not allowed as `title` takes an object. See https://wix.github.io/react-native-navigation/api/options-title#text
This could be avoided by using Typescript which would have thrown an error when setting a string on `title`.

**Comment by zainspresso** [comment]
You're right.. Stupid mistake ;)
