### ISSUE TITLE
Android keyboard pushes UI up on Android 30+

### ISSUE THREAD

**Issue by tomgransden** [wix/react-native-navigation#7477]
## 🐛 Bug Report

On Android 30+, absolute positioned elements at the bottom of the screen are pushed up when the keyboard is visible. In older versions of React Native Navigation, the elements are covered by the keyboard.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

Assuming the app has a text input at the top and an absolute positioned element at the bottom of the screen:

1. Click the text input to open the Android keyboard

## Expected behavior

The absolute positioned button at the bottom would be covered by the keyboard

## Actual Behavior

The keyboard appears and absolute positioned elements get pushed up the screen

**React Native Navigation version 7.23.1**
![7-23-1-android-31](https://user-images.githubusercontent.com/42301553/157636888-343daee0-ccb9-42af-bbc7-1183f6ed1ad5.png)

**React Native Navigation version 7.26.0**
![7-26-android-31](https://user-images.githubusercontent.com/42301553/157636977-0a845318-dd75-4981-890c-f5323f168814.png)

## Your Environment

- React Native Navigation version: 7.26.0
- React Native version: 0.67.3
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Any build type, Android 30+ emulator/device

## Reproducible Demo

https://github.com/tomgransden/RNNKeyboardBug

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by alan-nakagiri** [comment]
I've seen this same issue as well. 

https://github.com/wix/react-native-navigation/issues/7428#issuecomment-1061324526

**Comment by marf** [comment]
Same issue

**Comment by alan-nakagiri** [comment]
@guyca I always appreciate the work you do to maintain this critical library for a lot of us. 

Any chance you are able to take a look into this in the near future?

**Comment by ach5910** [comment]
I am seeing the same issue, regardless of what I set my `windowSoftInputMode` to, it is treated like `adjustResize` and the keyboard moves all the content up.

**Comment by alan-nakagiri** [comment]
@guyca 
We are still seeing an issue with softWindowResizeMode with Android 30 and the latest version of RNN 7.28.1. We were getting by before by staying on version RNN 7.23.1.

However we are attempting to update RN to 68 so we are also updating to RNN. 

Is there any update on this issue being resolved?

**Comment by kabus202** [comment]
please reopen. I think those are related https://github.com/wix/react-native-navigation/issues/7428 https://github.com/wix/react-native-navigation/issues/7477 https://github.com/wix/react-native-navigation/issues/7582 https://github.com/wix/react-native-navigation/issues/7569 https://github.com/wix/react-native-navigation/issues/7436

**Comment by MyPalVikram** [comment]
Does anyone know a fix to this by chance?

**Comment by alwazqazi** [comment]
any update this still no workarounds are working. Keyboard Pushes the button upwards when coming from a previous screen which is ScrollView.

**Comment by dprajapati1179** [comment]
Still facing the issue , ANyone has solution then please share

**Comment by marcshilling** [comment]
Setting `android:windowSoftInputMode="adjustPan"` has no effect, it just behaves the same way as `adjustResize`. This used to work with this library. I suspect it broke when I upgraded from 7.32.1 to 7.37.2. Issue should not be closed IMO.

**Comment by bumjin1013** [comment]
same here on 0.73.5

**Comment by IamMax279** [comment]
so it cannot be fixed, huh?

**Comment by shaysingh** [comment]
any update on this? still facing same issue on android.
