### ISSUE TITLE
BackAndroid.addEventListener call back not work on pushed screen

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#749]
### Issue Description

When you use the BackAndroid in pushed screen (opened by this.props.navigator.push({})) the call back function not getting called, but when you return to the home screen after this.props.navigator.popToRoot() the call back get called, but no need for it in this case.

(https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

 pushed screen (opened by this.props.navigator.push({})) the call back function not getting called, but when you return to the home screen after this.props.navigator.popToRoot() the call back get called, but no need for it in this case.

---
### Environment
* React Native Navigation version: 2.0.0-experimental.151
* React Native version: 0.39.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): OS 6 emulator

**Comment by lipingruan** [comment]
+1

**Comment by guyca** [comment]
https://github.com/wix/react-native-navigation/issues/250#issuecomment-254186394 might be helpful for now

**Comment by Jaafar-abusair** [comment]
@guyca  I'm sorry but it's not, on pushed screen the event not getting invoked, only on the main screen (tabsapp), If you do navigator.push() the event will not work in the pushed screen until you do pop.

**Comment by guyca** [comment]
setting `overrideBackPress: true` when you push a screen prevents back button from popping your pushed screen or dismissing your modal. You can handle that `backPress` event in your `onNavigatorEvent` function.

**Comment by Jaafar-abusair** [comment]
how to handle it in onNavigatorEvent? there is no documentation for that, can you guide me for the correct document

**Comment by guyca** [comment]
register an onNavigatorEvent as usual, and listen for it like this:

```js
  onNavigatorEvent(event) {
    if (event.id === 'backPress' {
      // handle back button press
    }
  }
```

**Comment by Jaafar-abusair** [comment]
That great, I have another question, can we also listen to Tab select changed in onNavigatorEvent?

**Comment by guyca** [comment]
sure, this was discussed in a lot of issues

bottom tabs: https://github.com/wix/react-native-navigation/search?q=bottomTabSelected&type=Issues&utf8=%E2%9C%93

topTabs: https://github.com/wix/react-native-navigation/search?q=tabSelected&type=Issues&utf8=%E2%9C%93

**Comment by ugiacoman** [comment]
@guyca We should add `overrideBackPress` to the docs!

**Comment by Jaafar-abusair** [comment]
```
onNavigatorEvent(event) {
    if (event.id === 'backPress' {
      // handle back button press
    }
  }
```

this one not working anymore, I have no idea why

**Comment by truongthanh1303** [comment]
@guyca I wondering don't know why the onNavigatorEvent does not fire when the back button pressed.

**Comment by truongthanh1303** [comment]
Exactly,  the back event does not fire onNavigatorEvent when the app first launched.
Do you have any suggestions for me?

Regards,
