### ISSUE TITLE
RN > 0.40 Duplicate interface definition for class RCTBridge

### ISSUE THREAD

**Issue by Johan-dutoit** [wix/react-native-navigation#750]
### Issue Description

Build error when using `react-native-navigation` with `react-native >= 0.40`

- Init new app
- Follow steps to install `react-native-navigation`
- Build

Side note.  First noted when upgrading from `RN 0.37.0` to `RN 0.41.2`

---
### Environment
* React Native Navigation version: `next`
* React Native version: `0.41.2`
* Platform(s) (iOS, Android, or both?): `iOS`
* Device info (Simulator/Device? OS version? Debug/Release?): `OS 10.2`

**Follow up** There is already a pull request in place (https://github.com/wix/react-native-navigation/pull/652), but as per @DanielZlotin comment, this won't be merged in any time soon.

**Comment by anitricks** [comment]
Having same problem with RN 0.41.2 Are the docs updated to reflect the change of the iOS header in RN 0.40 and above?

**Comment by robinvw1** [comment]
Same issue here with RN 0.41.2.
<img width="259" alt="schermafbeelding 2017-02-12 om 19 34 23" src="https://cloud.githubusercontent.com/assets/793157/22864920/4abd5e88-f15a-11e6-9d6d-b7c5395b0281.png">

**Comment by outaTiME** [comment]
Same here guys, any solution? Thanks !!!

**Comment by gperdomor** [comment]
Same here

**Comment by charlesluo2014** [comment]
same here，when will upgrade to the RN 0.4x？

**Comment by jarsen** [comment]
Same.

**Comment by xiaoleiooo** [comment]
Same

**Comment by zhiyuanfirst** [comment]
Same

**Comment by ibzieg** [comment]
Until this is fixed, what is the latest version of RN we can use? 0.37.0?

**Comment by dillonykyang** [comment]
Please refer to this thread. https://github.com/wix/react-native-navigation/pull/723
