### ISSUE TITLE
Bottom tab upper line color issue

### ISSUE THREAD

**Issue by jasonKRR** [wix/react-native-navigation#7502]
I would like to change the gray line on bottom tab, Is there anyone who can let us know how i can change the color?
*Please refer to the the grey line in the red box 

Your help means a lot to Junior developer!

![image](https://user-images.githubusercontent.com/92898953/163528287-cb47c0c0-e62b-4978-a2c1-5bbfdf93bcc2.png)

**Comment by aneena-thomas** [comment]
Any help on the above issue mentioned by @jasonKRR
