### ISSUE TITLE
Back button on Android not closing the Drawer if it's open

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#751]
### Issue Description

Back button on Android not closing the Drawer if it's open

### Steps to Reproduce / Code Snippets / Screenshots

Open the drawer, clock device back button, nothing happen

---
### Environment
* React Native Navigation version: 2.0 Exp 151
* React Native version: 0.39.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): OS 7.1 emulator

**Comment by guyca** [comment]
Hey
What do you mean by "clock device back button" ? I opened the drawer, on clicked the device back button - drawer closed (tried both left and right drawers)

**Comment by Jaafar-abusair** [comment]
Typo: when click onbback button, drawer not getting closed, note that open drawer by gesture is disabled.
