### ISSUE TITLE
Get current route name in App.js (no access to navigation prop)

### ISSUE THREAD

**Issue by Gabotron-ES** [wix/react-native-navigation#7520]
Hi everybody, in my react native main file (App.js) I have a handler for firebase notifications, in the foregroundNotifications listener I want to check current route name but problem is I don't have access to navigation prop, that's why I created a ref to navigation in another file which I then import in App.js.

In my RootNavigation.js
```
import * as React from 'react';

export const isReadyRef = React.createRef();

export const navigationRef = React.createRef();

export function navigate(name, params) {
  if (isReadyRef.current && navigationRef.current) {
    // Perform navigation if the app has mounted
    navigationRef.current.navigate(name, params);
  } else {
    // You can decide what to do if the app hasn't mounted
    // You can ignore this, or add these actions to a queue you can call later
  }
}
```

This allowed me to use navigate (added the method following another stackoverflow post) , but how can I get current route name from NavigationRoot.js?

How I use it in my App.js (I added navigate, but how can I add getCurrentRoute?)
```
import { navigationRef, isReadyRef } from '@env/RootNavigation.js';

RootNavigation.navigate('NewScreen');

<NavigationContainer ref={navigationRef} onReady={ () => { isReadyRef.current = true; } }>
            <ROOTSTACK1></ROOTSTACK1>
</NavigationContainer>

```

**Comment by Andarius** [comment]
Hey @Gabotron-ES, I think you are on the wrong repo, see https://reactnavigation.org/docs/navigating-without-navigation-prop/
