### ISSUE TITLE
Possible inconsistency in header title behavior between OSes

### ISSUE THREAD

**Issue by Helicosaurus-Rex** [wix/react-native-navigation#7522]
## 🐛 Bug Report

There seems to be a different behavior on iOS and Android when setting the headerTitle property of an options prop to `() => null`. On Android, there will be nothing as expected, but on iOS, the title then defaults to the screen's name. When setting headerTitle to an empty string, both OSes work as intended.

As I've been upgrading the project in which I discovered the bug, it's likely there was a change of behavior implemented at some point in rn-navigation.

The project always set the following options properties for Screens: headerLeft, headerRight, headerTransparent, headerStyle, headerTintColor, headerTitleStyle.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. Use a Stack.Screen with the headerTitle property of the options prop set as `() => null` wherever in an app.

## Expected behavior

On both Android and iOS, there shouldn't be any title.

## Actual Behavior

On iOS, the title is set to the Screen's name.

## Your Environment

- React Native Navigation version: 6.0.10
- React Native version: 0.68.1
- Platform(s): Both
- Device info: Physical devices (Android 5.0, 12.0, and iOS 15)

## Reproducible Demo

/

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by phuongwd** [comment]
@Helicosaurus-Rex  I think you are on the wrong repo, https://reactnavigation.org/docs/headers/#setting-the-header-title

**Comment by Helicosaurus-Rex** [comment]
Indeed! My apologies, I'll move the issue, you can close this one.
