### ISSUE TITLE
Tab label not showing on Android if tab count > 3

### ISSUE THREAD

**Issue by dhammikab** [wix/react-native-navigation#753]
### Issue Description

On Android, if there are more than 3 tabs, the labels under each icon do not show. Only the selected item is shown (i.e.  One label at a time) - See attached screen shot. I do see the labels if I have 3 tabs instead of 4. 

### Steps to Reproduce / Code Snippets / Screenshots

Here is a snippet of the code I use:

```js
		Navigation.startTabBasedApp({
			tabs: [
				{
					label: 'Explorer',
					screen: 'enw.Explorer',
					icon: require('./img/coupon.png'),
					title: 'Explore',
					navigatorStyle
				},

				{
					label: 'Collect',
					screen: 'enw.Collect',
					icon: require('./img/collect.png'),
					title: 'Collect',
					navigatorStyle
				},
				{
					label: 'Redeem',
					screen: 'enw.Redeem',
					icon: require('./img/redeem.png'),
					title: 'Redeem',
					navigatorStyle
				}	,
				{
					label: 'Settings',
					screen: 'enw.Settings',
					icon: require('./img/settings.png'),
					title: 'Settings',
					navigatorStyle
				}
			]
		});
```
I have attached a screen shot of the resulting tab rendered on a simulator.
![starttabbasedapp-label-not-showing](https://cloud.githubusercontent.com/assets/1028364/22824078/69d7e840-ef54-11e6-89e9-0c6d1ac1372f.jpg)

---
### Environment
* React Native Navigation version: "next"
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Genymotion

**Comment by guyca** [comment]
Pass an `appStyle` node when calling startTabBased app with `forceTitlesDisplay: true`.

```js
Navigation.startTabBasedApp({
  ...
  appStyle: {
    forceTitlesDisplay: true
  }
});
```

**Comment by dhammikab** [comment]
After updating my code to what @guyca said above it worked like a charm! - Thanks @guyca!!!!

Here is what the updated code looks like:


Navigation.startTabBasedApp({
			tabs: [
				{
					label: 'Explorer',
					screen: 'enw.Explorer',
					icon: require('./img/coupon.png'),
					title: 'Explore',
					navigatorStyle
				},

				{
					label: 'Collect',
					screen: 'enw.Collect',
					icon: require('./img/collect.png'),
					title: 'Collect',
					navigatorStyle
				},
				{
					label: 'Redeem',
					screen: 'enw.Redeem',
					icon: require('./img/redeem.png'),
					title: 'Redeem',
					navigatorStyle
				}	,
				{
					label: 'Settings',
					screen: 'enw.Settings',
					icon: require('./img/settings.png'),
					title: 'Settings',
					navigatorStyle
				}
			],
			appStyle: {
					forceTitlesDisplay: true
			}
		});
