### ISSUE TITLE
Styling StatusBar with MMDrawer

### ISSUE THREAD

**Issue by indivisable** [wix/react-native-navigation#754]
### Issue Description

![feb-11-2017 01-59-27](https://cloud.githubusercontent.com/assets/22860891/22852258/c6c37f16-effd-11e6-9e52-4e9c327564d2.gif)

You cannot apply styles to StatusBar when opening left or right drawers. I tried to apply it using static navigationStyle object, but when I opened it would change my StatusBar text from white to black. I also tried to pass it props to the view.

In my main App.js (Where I initialize the TabApplication)

```
drawer: {
                type: 'MMDrawer',
                animationType: 'parallax',
                disableOpenGesture: true,
                left: {
                    screen: 'view.menu.LeftSideMenu',
                },
                right: {
                  screen: 'view.menu.RightSideMenu'
                },
            },

```

And in my Side Menu View Controller (LeftSideMenu.js)

```
export default class LeftSideMenu extends Component {
  static navigatorStyle = {
    statusBarHideWithNavBar: true,
    statusBarHidden: true,
    statusBarTextColorScheme: 'dark'
  };
...
```

Related Issues: 
https://github.com/wix/react-native-navigation/issues/189
https://github.com/wix/react-native-navigation/issues/639

### Temporary Workaround

In MMDrawerController.m Line 1178 instead of returning the statusbar preferences from sidemenu we get from the center view controller. This delivers a more consistent results as it matches whatever is set in the main view. See: https://github.com/indivisable/react-native-navigation/commit/514ecf55d1bad0b56eace02e6dfea9242ada9b68

```
#pragma mark - iOS 7 Status Bar Helpers
-(UIViewController*)childViewControllerForStatusBarStyle{
    //return [self childViewControllerForSide:self.openSide];
    return [self childViewControllerForSide:MMDrawerSideNone];
}

-(UIViewController*)childViewControllerForStatusBarHidden{
    //return [self childViewControllerForSide:self.openSide];
    return [self childViewControllerForSide:MMDrawerSideNone];
}

```

### Steps to Reproduce / Code Snippets / Screenshots

Simply try to apply a style to the StatusBar when opening a left or right Drawer, you can test with example provided with project.

---
### Environment
* React Native Navigation version: 2.0.0 @196
* React Native version: 0.38.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator and iPhone 6S

**Comment by guyca** [comment]
cc @gran33

**Comment by jordanbrown** [comment]
Is this still the best way to hide the status bar when the drawer is open/closed?

**Comment by camdagr8** [comment]
This seems to be an issue in version `1.1.409` on `iOS 11.2.6`
