### ISSUE TITLE
How to add navigator on header have badge like this

### ISSUE THREAD

**Issue by trung1008** [wix/react-native-navigation#755]
![screen shot 2017-02-10 at 15 05 29](https://cloud.githubusercontent.com/assets/14955532/22860114/3d66eeea-f126-11e6-994b-e671d8786832.png)

**Comment by jkomyno** [comment]
+1

**Comment by indivisable** [comment]
You can try to experiment with this PR: https://github.com/wix/react-native-navigation/pull/619

**Comment by trung1008** [comment]
@indivisable  thanks u, but i no have idea to resolve problem. those repository seem to don't merge to master :(

**Comment by indivisable** [comment]
you can view their changes on the PR and integrate yourself with a comparison tool:

https://github.com/wix/react-native-navigation/pull/619/files

**Comment by trung1008** [comment]
@indivisable nice, thanks u
