### ISSUE TITLE
Android HardwareBackButtonOptions not working

### ISSUE THREAD

**Issue by huynqjmango360** [wix/react-native-navigation#7555]
I try to use HardwareBackButtonOptions config but instead of pop stack, android back hardware minimize app to back ground.

`Navigation.push<ProductDetailProps>(
      componentId,
      {
        component: {
          name: Screens.ProductDetail,
          passProps: {
            product,
          },
          options: {
            statusBar: {
              style: 'dark',
              animated: true,
            },
            topBar: {
              visible: false,
              height: 0,
            },
            layout: {
              componentBackgroundColor: 'transparent',
            },
            hardwareBackButton: {
              popStackOnPress: true,
              dismissModalOnPress: true,
            },
            animations: buildSharedElementAnimations(product.id),
          },
        },
      }
    );`

Did i missing something here?

Im using RNN 7.28.0, RN 0.68.1, google pixel 5, android 13

**Comment by sashansk3** [comment]
Hey, @huynqjmango360 are you using the hardware back button inside the bottom tab?

**Comment by huynqjmango360** [comment]
@sashansk3 my ProductDetail screen is push from ProductList, it's child of bottom tab stack.

`
bottomTabs: {
      id: BottomTabs,
      options: {
        bottomTabs: {
          testID: 'Button-Tabs',
        },
      },
      children: [
        {
          stack: {
            id: Screens.HomeStack,
            children: [
              {
                component: {
                  name: Screens.HomeScreen,
                  options: {
                    topBar: {
                      visible: false,
                    },
                  },
                },
              },
`

**Comment by sashansk3** [comment]
I have the same problem, after a few days of research I found a problem in the [StackController.java](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java) on line [407](https://github.com/wix/react-native-navigation/blob/cbb1bb20a9771e72cd2c1bcc9c73f5e624153c31/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackController.java#L407).

Try to replace `return stack.size() > 1;` with `return stack.size() >= 1;`. This change fixed the hardware back button issue in my case.
