### ISSUE TITLE
Nav bar buttons and their event handlers are lost with each push

### ISSUE THREAD

**Issue by elimydlarz** [wix/react-native-navigation#756]
We wanted to add a logout button to our nav bar, so we added the navigatorButtons key to our initial startSingleScreenApp call to define the button. However, this then disappears on every navigator push or resetTo call - this sort of makes sense, as the button is defined only for the initial screen. We worked around this by defining the buttons again on each of these calls.

Unfortunately, the button event handler we register upon loading our initial route with setOnNavigatorEvent also seems to disappear with each navigator push or resetTo call.

Having to redefine buttons and their handlers on every push or resetTo seems a bit odd. Is this behaviour intentional?

---
### Environment
* React Native Navigation version: pulling from Github
* React Native version: 0.40 with Redux
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPad 2 (Simulator)

**Comment by guyca** [comment]
Hey @elimydlarz 
You can define buttons once for each screen using a static `navigatorButtons` block like [this](https://github.com/wix/react-native-navigation/wiki/Adding-buttons-to-the-navigator)
