### ISSUE TITLE
Update to react-native 0.69 

### ISSUE THREAD

**Issue by hellforever** [wix/react-native-navigation#7563]
I can not build my react native app after updating react native version to 0.69.1.

In Android, the react native update helper says I need to extend ReactActivity and use MainActivityDelegate in MainActivity but react-native-navigation doc says I need to extend NavigationActivity, which is a conflict.

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/5683380/178864488-d099f7cd-a14e-4e83-aed9-443214f2ab7b.png">

**Comment by mattmcdonald-uk** [comment]
Issues with 0.69 are being discussed here: https://github.com/wix/react-native-navigation/issues/7547
