### ISSUE TITLE
White flash after splash and before app render

### ISSUE THREAD

**Issue by tvansteelandt** [wix/react-native-navigation#757]
### Issue Description

I have a white flash when booting the app, after the splash screen hides and the RNN single screen app shows.
I've read a lot on the RN repo, and here on the RNN repo, but I'm not sure what's causing this.
Is it react native itself, or is it a problem with react native navigation?

I've stumbled upon this:
https://peterminarik.tumblr.com/post/153039209421/how-to-fix-the-initial-white-flash-in-your-react
But I don't see a way to implement this using the bootstrap from RNN?

### Steps to Reproduce / Code Snippets / Screenshots

Use standard splash screen image and boot singleApp or tabBasedApp.

---
### Environment
* React Native Navigation version: 2.0.0-experimental.187
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone5S device

**Comment by JuneDomingo** [comment]
Hi @tvansteelandt, when using actual device, try to change `jsCodeLocation` value from ios/AppDelegate.m to
`jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];`

**Comment by guyca** [comment]
@tvansteelandt https://github.com/wix/react-native-navigation/pull/437 might help
