### ISSUE TITLE
navigationButtonPressed trigger multiple times when push screen????

### ISSUE THREAD

**Issue by suupham2506** [wix/react-native-navigation#7579]
## 🐛 Bug Report

I push to a screen multiple times name "Profile" with rightButtons id more, when press more button, I trigger to show an ovelay.

Expected: trigger 1 time only, but currently it triggers multiple times.
For example: I push to Profile screen 3 times, it will show overlay 3 times when press on more button.

## Your Environment

- React Native Navigation version: 7.28.0
- React Native version: 0.68
- Platform(s) (iOS, Android, or both?): both platform
- Device info (Simulator/Device? OS version? Debug/Release?): both simulator and real device

## Reproducible Demo

![Simulator Screen Shot - iPhone 12 mini - 2022-08-08 at 18 38 43](https://user-images.githubusercontent.com/28852565/183409766-1efb95de-f2cd-4e5a-af17-249de25535ac.png)

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by suupham2506** [comment]
@wixmobile Can you help me on this?

**Comment by suupham2506** [comment]
Is there any maintainer for this module?

**Comment by varungupta85** [comment]
@suupham2506 you are probably calling the `bindComponent` method in `componentDidMount` or something due to which it is called multiple times and hence added multiple event listeners. Without looking at the code, it is hard to tell what exactly is wrong.
