### ISSUE TITLE
Navigation Buttons out of bounds

### ISSUE THREAD

**Issue by lodev09** [wix/react-native-navigation#758]
### Issue Description

When pushing a screen with a `TextInput` layout at the top, it doesn't get the touch because the navigator button bounds are just to huge. In short, you can't really put a textinput to the top of the screen :(

### Steps to Reproduce / Code Snippets / Screenshots

![navbutton_issue](https://cloud.githubusercontent.com/assets/6686328/22898638/f80e645c-f262-11e6-89c7-f8699c997948.gif)

I highlighted the `TextInput` with style:
```js
textInput: {
	fontSize: 15,
	height: 22,
	backgroundColor: colors.danger
},
```

Also if you notice, there's an issue with `autofocus` related to the push animation. I'll create a separate issue about that later.

---
### Environment
* React Native Navigation version: latest (from forked git)
* React Native version: 0.41
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6 simulator

**Comment by lodev09** [comment]
Hmmm, it seems like this is only happening in the simulator, just tested with a real device and it seems be focusing right when tapped.

I'll close this for now. Thanks for the great package!

**Comment by guyca** [comment]
Thanks for reporting @lodev09 
A few users reported a similar issues in the past, If you have anymore insights please let us know. Thanks 👍
