### ISSUE TITLE
bottomTabs+topBar with drawBehind/visible=true not working when pushing a screen with animation options

### ISSUE THREAD

**Issue by thanksyouall** [wix/react-native-navigation#7583]
## 🐛 Bug Report
If I use the option for animations and also set `drawBehind=true` (or `visible=false`) for `bottomTabs` and `topBar`, the application does not respond.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?
Yes

## To Reproduce
1. Clone my repo – https://github.com/thanksyouall/wix-nav-bug
2. Run: `yarn`;
3. Run: `yarn start`;
4. Run: run from Xcode or `yarn ios`;
6. Click on "Push Settings Screen".

## Expected behavior
I expect to move to the next screen with this options: https://github.com/thanksyouall/wix-nav-bug/blob/main/index.js#L77-L87

## Actual Behavior
The app stops responding, push to the next screen does not work.

## Your Environment
- React Native Navigation version: ^7.30.0-alpha (it doesn't work on previous versions either)
- React Native version: 0.69.4
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Ipad Prop 11-inch, debug.

## Reproducible Demo
https://github.com/thanksyouall/wix-nav-bug

**Comment by thanksyouall** [comment]
And I found similar issue https://github.com/wix/react-native-navigation/issues/5090

**Comment by thanksyouall** [comment]
Up

**Comment by thanksyouall** [comment]
UP UP UPr

**Comment by goldfish15** [comment]
Hey there,
I've never replied on github before but maybe this will help you. Here's an example of my navigation push code.
I push my options inside of the push itself, hope it helps!
```
Navigation.push(this.props.componentId, {
      component: {
        name: 'account',
        passProps: {
        },
        options: {
          topBar: {
            title: {
              text: "Account",
            },
          },
          bottomTabs: {
            visible: false,
            drawBehind: true
          }
        }
      }
    });
```
