### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'h.g.k.g.f h.g.b.d()' on a null object reference

### ISSUE THREAD

**Issue by DenisPostnikov** [wix/react-native-navigation#7593]
Hey there,

here's the stacktrace of the issue:

## StackTrace

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'h.g.k.g.f h.g.b.d()' on a null object reference
       at com.reactnativenavigation.react.NavigationModule.navigator(NavigationModule.java:4)
       at com.reactnativenavigation.react.NavigationModule.access$100(NavigationModule.java)
       at com.reactnativenavigation.react.NavigationModule$1.lambda$onHostPause$0(NavigationModule.java:2)
       at com.reactnativenavigation.react.-$$Lambda$NavigationModule$1$YAogg-YWvGlqmTQTIc1m0ewJv3s.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

## Environment

- React Native Navigation version: "^7.29.0"
- React Native version:"0.66.3"
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): samsung Galaxy S9, Release

**Comment by mcapocaccia** [comment]
Many crashes here too, same RNN and RN versions.

Crash is in NavigationModule.java:213

    private Navigator navigator() {
        return activity().getNavigator();
    }

This is the context:
- app goes to background
- activity gets destroyed
- getCurrentActivity returns null, so "activity()" above is null
- crash

**Comment by marf** [comment]
Same problem here.

**Comment by mcapocaccia** [comment]
We patched with the diff below in postinstall and the crash disappeared completely.
@guyca @yogevbd you could consider patching 7.30.x

[react-native-navigation+7.29.0.patch.zip](https://github.com/wix/react-native-navigation/files/9557913/react-native-navigation%2B7.29.0.patch.zip)

**Comment by yogevbd** [comment]
Will add this fix in the next release, thanks!

**Comment by SYoder1** [comment]
> Will add this fix in the next release, thanks!

@yogevbd Is there any ETA on when the next version is going to be release?

**Comment by Spencer-Yoder** [comment]
Bump

**Comment by androideveloper** [comment]
@yogevbd any updates on the new release? 🙏

**Comment by tarouboy** [comment]
> We patched with the diff below in postinstall and the crash disappeared completely. @guyca @yogevbd it is a quite safe modification, you could consider patching 7.30.x
> 
> [react-native-navigation+7.29.0.patch.zip](https://github.com/wix/react-native-navigation/files/9557913/react-native-navigation%2B7.29.0.patch.zip)

Do you still receive crash reports after applying this patch?

**Comment by mcapocaccia** [comment]
@tarouboy No more crashes since we added the patch in our postinstall process

**Comment by tarouboy** [comment]
> @tarouboy No more crashes since we added the patch in our postinstall process

Lovely. I will apply that patch too. Thanks man.

**Comment by thuongtv-vn** [comment]
Hi All,

I am facing the same issue. But could not reproduce it even i pushed app to background. However, i have been received some mentioned error message. 

Do you guys know exactly the case?
