### ISSUE TITLE
How to change the navigation style such as topbar, bottomtab... style to all component

### ISSUE THREAD

**Issue by thuongtv-vn** [wix/react-native-navigation#7597]
Hi all,

I am using `mergeOptions` to change the app theme (light/dark). The problem is the `mergeOptions` api required only a 'componentId' that why we have to track and lookup all the existing component to make the `mergeOptions`.

The question is how to change the navigation style to all components at the same time? other words by 1 command?
For example:
`mergeOptions('bottom_tab_layout_id', {....})` then all child component will be updated?

Thank for any advice!

**Comment by b8ne** [comment]
The [docs](https://wix.github.io/react-native-navigation/docs/style-theme#changing-theme-dynamically) do cover this by mentioning the need to use `setDefaultOptions` and then `setRoot` again. 
I found an issue here, not so much a bug, but a use case that I think is fairly common.  My default `setRoot` command loads the app to the main dashboard, however when changing theme, the user is on a More > Settings screen, and would expect to remain there when toggling the theme.
So I had to do this:


    // store my theme state internally
    setThemeMode({darkMode});

    // calculate the new navigation styles for the theme mode
    const navStyles = makeNavigationStyles(darkMode);

    // apply the styles but also merge in the currentTabIndex of my More tab
    Navigation.setDefaultOptions({
      ...navStyles,
      bottomTabs: {
        ...navStyles.bottomTabs,
        currentTabIndex: 4,
      },
    });

    // set root based on initial screens, but also conditionally push in my Settings screen if it doesn't exist
    let screens = mainScreens.map(screen => {
    if (
      screen.stack &&
      screen.stack.id === 'MORE_TAB' &&
      screen.stack.children.length === 1
    ) {
      screen.stack.children.push({
        component: {
          id: 'App.More.Settings',
          name: 'App.More.Settings',
        },
      });
    }
    return screen;
    });

    setRoot('bottomTabs', 'App', screens);

This appears to be working pretty well, not sure if there is a more elegant solution though.
