### ISSUE TITLE
Custom ViewController presentation animation?

### ISSUE THREAD

**Issue by epaga** [wix/react-native-navigation#76]
In my original app that I am trying to port to use react-native-navigation, I had a separate ViewController which I presented with my own `UIPresentationController`, `UIViewControllerAnimatedTransitioning`, and `UIViewControllerTransitioningDelegate`. It is similar to a lightbox-presentation, but it slides up from the bottom half-way and causes the background view controller to scale down about 10%.

What would be the best way to go about using this code with react-native-navigation? I'm assuming I'd need to modify `RCCManagerModule` for using this other ViewController - perhaps adding a method with a key which then uses a presentation controller previously registered from within my own code?

**Comment by epaga** [comment]
OK so I did it and it seems to work for me. Here is the pull request / changeset in case anyone is interested:

https://github.com/wix/react-native-controllers/pull/68

**Comment by guyca** [comment]
Thanks @epaga
