### ISSUE TITLE
Pop callback?

### ISSUE THREAD

**Issue by leonciocaminha** [wix/react-native-navigation#760]
when i pop some navigation, the previous page callback exists? like componentDidMount or something like this? how i do that into previous page? or pass data into it?

**Comment by guyca** [comment]
When you pop a screen, that screen gets unmounted. You can dispatch action, or do any other logic, in `componentWillUnmount`.

In v2, you'll be able to `await` navigation commands to easily queue actions after pop or other actions.

**Comment by jslz** [comment]
anecdotally, running in debug mode attached to chrome debugger, i think i often do not see the componentWillMount / componentWillDismount methods called, according to console.logs() i put in there. it seems pretty arbitrary. these are not tabs that live forever, these are pushed/popped screens that i assumed would be dynamic on/off the stack. RNN ^1.1.205, react-native-cli 2.0.1, react-native 0.46.4.

**Comment by VicFrolov** [comment]
@guyca Hey is there an example of using an await for a pop action?
