### ISSUE TITLE
Class 'ModalContentLayout' is not abstract and does not implement abstract member public abstract fun onChildStartedNativeGesture(p0: View!, p1: MotionEvent!):

### ISSUE THREAD

**Issue by ChurikiTenna** [wix/react-native-navigation#7612]
## 🐛 Bug Report

% react-native run-android

Class 'ModalContentLayout' is not abstract and does not implement abstract member public abstract fun onChildStartedNativeGesture(p0: View!, p1: MotionEvent!):

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

(Write your steps here:)

run react-native run-android

## Expected behavior

app start running

## Actual Behavior

warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
(node:43242) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
info JS server already running.
info Installing the app...

> Configure project :react-native-reanimated
Native libs debug enabled: false
Android gradle plugin: 7.0.4
Gradle: 7.5.1
building Reanimated2
WARNING:The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 7.0.4.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
WARNING:The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 7.0.4.
Android SDK Build Tools 30.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:processDebugMainManifest
/Users/tenna/Desktop/aitem/android/app/src/main/AndroidManifest.xml:10:5-95 Warning:
        uses-permission#android.permission.READ_PHONE_STATE was tagged at AndroidManifest.xml:10 to remove other declarations but no other declaration present

> Task :react-native-navigation:compileReactNative57_5DebugKotlin FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
170 actionable tasks: 30 executed, 140 up-to-date
e: /Users/tenna/Desktop/aitem/node_modules/react-native-navigation/lib/android/app/src/reactNative57_5/java/com/reactnativenavigation/react/modal/ModalContentLayout.kt: (12, 1): Class 'ModalContentLayout' is not abstract and does not implement abstract member public abstract fun onChildStartedNativeGesture(p0: View!, p1: MotionEvent!): Unit defined in com.facebook.react.uimanager.RootView

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative57_5DebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
e: /Users/tenna/Desktop/aitem/node_modules/react-native-navigation/lib/android/app/src/reactNative57_5/java/com/reactnativenavigation/react/modal/ModalContentLayout.kt: (12, 1): Class 'ModalContentLayout' is not abstract and does not implement abstract member public abstract fun onChildStartedNativeGesture(p0: View!, p1: MotionEvent!): Unit defined in com.facebook.react.uimanager.RootView

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative57_5DebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

    at makeError (/Users/tenna/Desktop/aitem/node_modules/execa/index.js:174:9)
    at /Users/tenna/Desktop/aitem/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/tenna/Desktop/aitem/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/tenna/Desktop/aitem/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.

## Your Environment

- React Native Navigation version: ^2.29.0
- React Native version: 0.7
- Platform(s) (iOS, Android, or both?): android
- Device info (Simulator/Device? OS version? Debug/Release?): not relevant 

## Reproducible Demo

Not sure how to reproduce...
I can give the repository access if that'll help.

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✅  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by trantansang** [comment]
My project has the same issue

**Comment by oferRounds** [comment]
Has anyone find a solution? getting it also

**Comment by laoduan395** [comment]
My project has the same issue + 1

**Comment by erkutr-prog** [comment]
same issue here..

**Comment by adenrashid** [comment]
same here

**Comment by chandan-edureka** [comment]
same here

**Comment by yunusemreayar** [comment]
same issue here..

**Comment by manohar-octifi** [comment]
No point in saying "same here" does anyone of you know Kotlin or know who does?

**Comment by manohar-octifi** [comment]
Method 1 worked for me
https://stackoverflow.com/a/74334163/9254635

**Comment by laoduan395** [comment]
> Method 1 worked for me https://stackoverflow.com/a/74334163/9254635

really useful (Method 1)  thx

**Comment by MikePodgorniy** [comment]
[READ ME] [FIX INSIDE] Android build failures happening since Nov 4th 2022
https://github.com/facebook/react-native/issues/35210

**Comment by chandan-edureka** [comment]
https://stackoverflow.com/questions/74334162/android-build-failure-common-issue-failed-to-install-the-app-error-command-f/74334163#74334163
Method 1 worked for me

**Comment by yogevbd** [comment]
As said, the solution is to bump react-native to the latest patch version. See more [here](https://github.com/facebook/react-native/issues/35210#issuecomment-1304536693)

**Comment by Jojocaster** [comment]
hey guys, sorry to reopen this .. but I've also come across this issue, and none of the solutions worked for me. 
Both solutions were already part of my `build.gradle`, so I'm not sure what else to try. 

I'm running RN v0.69.11, `react-native-navigation` v7.29.0, and kotlin v1.6.0. 

Let me know if there's anything else that I can try. 

Works perfectly fine on iOS btw.

**Comment by FinnGu** [comment]
> hey guys, sorry to reopen this .. but I've also come across this issue, and none of the solutions worked for me. Both solutions were already part of my `build.gradle`, so I'm not sure what else to try.
> 
> I'm running RN v0.69.11, `react-native-navigation` v7.29.0, and kotlin v1.6.0.
> 
> Let me know if there's anything else that I can try.
> 
> Works perfectly fine on iOS btw.
> 
> EDIT: alright, found the issue. To anyone who finds this in the future, I had to add (well, edit) this line in `app/build.gradle`:
> 
> ```
> android {
>   packagingOptions {
>     missingDimensionStrategy "RNN.reactNativeVersion", "reactNative71"
>  ....
> ```
> 
> This was previously set to `reactNative63`

Can you explain why it had to be `reactNative71`? That version is higher than your actual version of `react-native` which confuses me a bit. I am currently using `react-native` version `0.68.7` and am wondering which fallback I should use.
