### ISSUE TITLE
SDK 30 hardware back behaviour not working

### ISSUE THREAD

**Issue by magneutron** [wix/react-native-navigation#7614]
## 🐛 Bug Report

Hardware BackButton cannot pop to previous screen
hardwareBackPress listener also cannot listen anything in some devcie/android version

## To Reproduce

Call Navigation.push or Navigation.showOverlay
Press hardware back button, or back gesture 

## Expected behavior

Back to previous screen, like calling Navigation.pop(this.props.componentId) or Navigation.dismissOverlay(this.props.componentId)

## Actual Behavior

Some device can pop correctly after pressing hardware back button ( Galaxy A22, Android version 11) hardwareBackPress listener triggered
Some device go to background, not pop to previous screen after pressing hardware back button (Pixel 5a, Android version 13)
hardwareBackPress listener not triggered

## Your Environment

- React Native Navigation version: ^7.30.0-alpha.1
- React Native version: ^0.70.2
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by berehovyi** [comment]
Got same issue.
Solution - use newer androidx libraries.
```
implementation 'androidx.appcompat:appcompat:1.6.0-rc01'
implementation 'androidx.appcompat:appcompat-resources:1.6.0-rc01'
```

Discussion why - [here](https://issuetracker.google.com/issues/247982487?pli=1) .

**Comment by jjv360** [comment]
I had a very similar issue in my app (using v7.29.1) on my Samsung tablet (Android 12)... It seemed like the back button wasn't closing the app even though it was popping to previous screens, but it was actually calling `invokeDefaultOnBackPressed()` in NavigationActivity over and over in a loop...

What fixed it for me was replacing `super.onBackPressed()` with `finish()` in [NavigationActivity here](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java#L98)...

I also tried changing `android:enableOnBackInvokedCallback` to false in the manifest, and using the newer androidx libraries, but it made no difference...

**Comment by magneutron** [comment]
> 

Thanks you, problem resolved

**Comment by magneutron** [comment]
> I had a very similar issue in my app (using v7.29.1) on my Samsung tablet (Android 12)... It seemed like the back button wasn't closing the app even though it was popping to previous screens, but it was actually calling `invokeDefaultOnBackPressed()` in NavigationActivity over and over in a loop...
> 
> What fixed it for me was replacing `super.onBackPressed()` with `finish()` in [NavigationActivity here](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java#L98)...
> 
> I also tried changing `android:enableOnBackInvokedCallback` to false in the manifest, and using the newer androidx libraries, but it made no difference...

I also facing that probolem...
Waiting for new version to fix it

**Comment by magneutron** [comment]
> > I had a very similar issue in my app (using v7.29.1) on my Samsung tablet (Android 12)... It seemed like the back button wasn't closing the app even though it was popping to previous screens, but it was actually calling `invokeDefaultOnBackPressed()` in NavigationActivity over and over in a loop...
> > What fixed it for me was replacing `super.onBackPressed()` with `finish()` in [NavigationActivity here](https://github.com/wix/react-native-navigation/blob/master/lib/android/app/src/main/java/com/reactnativenavigation/NavigationActivity.java#L98)...
> > I also tried changing `android:enableOnBackInvokedCallback` to false in the manifest, and using the newer androidx libraries, but it made no difference...
> 
> I also facing that probolem... Waiting for new version to fix it

I am usinig androidx.appcompat:appcompat:1.7.0-alpha01
and     "react-native-navigation": "^7.30.2",

All problem we mentioned have been resolved
