### ISSUE TITLE
 Cannot run program "Android/sdk/cmdline-tools/latest/bin/sdkmanager": error=2, No such file or directory

### ISSUE THREAD

**Issue by retyui** [wix/react-native-navigation#7619]
## 🐛 Bug Report

```java
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/i/all_work/thera/mobile/node_modules/react-native-navigation/lib/android/app/build.gradle' line: 177

* What went wrong:
A problem occurred evaluating project ':react-native-navigation'.
> Cannot run program "/Users/i/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager": error=2, No such file or directory

```

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. Step 1...
1. Step 2...
1. Step 3...

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- React Native Navigation version: 7.29.1
- React Native version: 0.70.1
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Debug

## Reproducible Demo

(Paste the link to an example repo and exact instructions to reproduce the issue.)

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅  &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by retyui** [comment]
To fix the issue you need to install cmd line tolls:

<img width="980" alt="Screenshot 2022-10-19 at 23 30 00" src="https://user-images.githubusercontent.com/4661784/196808457-297e3c8b-e586-4362-8a59-1b5b8c6d263e.png">

**Comment by onaggar** [comment]
I have done this and still receive the same error. I also added the path to environment variables. Is there anything else that should be done?

**Comment by retyui** [comment]
@onaggar  you should see the next error

```java
> Cannot run program "<...>/sdk/cmdline-tools/latest/bin/sdkmanager": error=2, No such file or directory
```

please verify that `<...>/sdk/cmdline-tools/latest/bin/sdkmanager` path exist

**Comment by onaggar** [comment]
![SDK Tools](https://user-images.githubusercontent.com/26486541/196955817-f4f99f6d-78e8-496c-8a1a-a2819692f562.jpg)
It exists and when I try to run the command from the terminal, it runs

**Comment by RaviMopo** [comment]
Same Error any help on this. 
If I downgraded 7.30.1 to 7.27.1 compiled without issues. 

`FAILURE: Build failed with an exception.

* Where:
Build file '/home/circleci/mopo-mobile-app2/node_modules/react-native-navigation/lib/android/app/build.gradle' line: 177

* What went wrong:
A problem occurred evaluating project ':react-native-navigation'.
> Cannot run program "/opt/android/sdk/cmdline-tools/latest/bin/sdkmanager": error=2, No such file or directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 40s`

**Comment by lyswhut** [comment]
This problem still exists, it should not be turned off, on windows platform, `sdkmanager` needs `.bat` extension to run, so here should check the platform
