### ISSUE TITLE
params.screen.navigationParams.screenInstanceID: Undefined is not an object

### ISSUE THREAD

**Issue by jkomyno** [wix/react-native-navigation#762]
### Issue Description
Currently, my react-native project compiled for Android works well, without warning or crashes, but if I try to run it on the iOS 10.2 iPhone7 emulator it only shows me the default splash screen, without allowing me to proceed any further.

### Error
Here's part of the logs I have copied from xCode
[tid:com.facebook.react.JavaScript] Possible Unhandled Promise Rejection (id: 0):
undefined is not an object (evaluating 'params.screen.navigationParams.screenInstanceID')
savePassProps@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:75498:59
startSingleScreenApp@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:75123:14
startSingleScreenApp@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:74936:65
startApp@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:1604:55

I have some passProps that work well for android, could it be that I have passed an undefined value that is not warned in Android but is blocking in iOS?
---
### Environment
* React Native Navigation version: 2.0.0-experimental.0
* React Native version: 0.38.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iOS 10.2, Debug

**Comment by guyca** [comment]
This is just a hunch but maybe you forgot to register that screen on iOS?

**Comment by jkomyno** [comment]
Nope, I have the same screen registered on both iOS and Android, but thanks for the hint anyway

**Comment by jkomyno** [comment]
It seems like it calls [platformSpecific.android.js](https://github.com/wix/react-native-navigation/blob/master/src/platformSpecific.android.js) instead of platformSpecific.ios.js.
I really can't understand how come XCode is fetching from *.android.js. Any suggestion please?
