### ISSUE TITLE
Broken android with new(7.30.0) version of RNN

### ISSUE THREAD

**Issue by ApargMobile2** [wix/react-native-navigation#7633]
with new update of package 7.30.0 is broken android build
I'm getting error compileReactNative68DebugKotlin 
also I've tried to set kotlin version to 1.6.0 but it's not worked, what can I do without downgrade to 7.29.0 because in 7.29.0 is broken ios, so I need something to fix in both platforms

**Comment by tukaAlalami** [comment]
@ApargMobile2 do you find any solution ?
