### ISSUE TITLE
Getting warning all the time about dependency.assets and dependency.hooks

### ISSUE THREAD

**Issue by noomorph** [wix/react-native-navigation#7647]
## 🐛 Bug Report

After installing React Native Navigation and auto-linking it (`npx rnnlink`), I see this warning on every attempt to run React Native CLI scripts:

```
warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
```

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

No.

## To Reproduce

1. `npx react-native init DemoProject`
2. Go inside the project.
3. `npm install`
4. `npm install --save react-native-navigation`
5. `npx rnn-link`
6. `pod install --project-directory=ios`
7. `npm start`

## Expected behavior

I guess we should not see this warning. Something's not correct.

## Actual Behavior

Any `npx react-native ...` command warns me about this:

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/1962469/204826008-9d6d23a5-b52f-4c2f-ac1f-996acb26611d.png">

## Your Environment

```
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 34.81 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - ~/.nvm/versions/node/v19.2.0/bin/node
    Yarn: Not Found
    npm: 9.1.2 - ~/.nvm/versions/node/v19.2.0/bin/npm
    Watchman: 2022.10.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/yaroslavs/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Reproducible Demo

<https://github.com/noomorph/rnn-7647>

### Are you willing to resolve this issue by submitting a Pull Request?

✖️ No, I don’t have the time, and I’m okay to wait for the community/maintainers to resolve this issue.

**Comment by xgenem** [comment]
Experiencing this now. Tsk no one replied.

**Comment by Garamani** [comment]
The problem was related to **AppDelegate.mm** settings. I changed the AppDelegate.mm based on [this comment](https://github.com/wix/react-native-navigation/issues/7676#issuecomment-1408435169) and the warning disappeared.

**Comment by jeremybarbet** [comment]
I'm using this patch 

```patch
diff --git a/node_modules/react-native-navigation/react-native.config.js b/node_modules/react-native-navigation/react-native.config.js
index 17feda2..de80338 100644
--- a/node_modules/react-native-navigation/react-native.config.js
+++ b/node_modules/react-native-navigation/react-native.config.js
@@ -8,10 +8,6 @@ module.exports = {
         packageInstance: 'new NavigationPackage(reactNativeHost)',
       },
     },
-    assets: [],
-    hooks: {
-      postlink: 'node node_modules/react-native-navigation/autolink/postlink/run',
-    },
   },
   project: {
     android: {

```

**Comment by abhishekjmd** [comment]
Getting this warning did anyone found the solution

**Comment by MateusAndrade** [comment]
> 

The patch fixed the warning, let's see if there will be any build errors. 😅
