### ISSUE TITLE
LightBox animation speed option

### ISSUE THREAD

**Issue by lodev09** [wix/react-native-navigation#765]
### Issue Description

Is there any chance that an option for "Animation Speed" for lightbox be implemented? Currently, I'm using LightBox API to create my custom ActionSheet but the animation seems rather slow.

I'm just new with react-native and haven't had a chance to re-learn ios so I can't submit PR as of the moment -- I'd love to in the future.

### Steps to Reproduce / Code Snippets / Screenshots

![lightbox_animation](https://cloud.githubusercontent.com/assets/6686328/22967967/99c99c76-f3a3-11e6-95ad-ca1305b4b64b.gif)

---
### Environment
* React Native Navigation version: latest
* React Native version: 0.41
* Platform(s) (iOS, Android, or both?): ios
* Device info (Simulator/Device? OS version? Debug/Release?): debug simulator

**Comment by guyca** [comment]
Hey @lodev09 
Don't see a reason for it not to be supported. We're a bit busy with 2.0 major version, after its release we will put an emphasis on customization and styling.

**Comment by lodev09** [comment]
I see. Thanks for the quick response @guyca . I'll look forward to it :)

**Comment by bduyng** [comment]
@guyca do we have a time when v2 will be released? I need open and close LightBox without any animations. can you show me how to test the functions when we update the native code on the current version? Thanks!

**Comment by nbomberger** [comment]
@guyca Take a look at [this](https://github.com/najabu/react-native-navigation/pull/1) PR.  I forked it and implemented this in ios (i only needed it for a prototype).  It should give you some idea of how to move forward.  I can probably do a PR for Android when I get time.
