### ISSUE TITLE
Alternative Distribution Methods

### ISSUE THREAD

**Issue by wSedlacek** [wix/react-native-navigation#7659]
## 🚀 Feature

Currently `ahbottomnavigation` comes from `jitpack` which downloads from GitHub.
It would be nice to be able to have places to download this dependency from that are not direct from GitHub

## Motivation

When running in a shared GitHub Action I get this error from time to time.

```
Execution failed for task ':app:checkDebugAarMetadata'.
See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
19 actionable tasks: 19 executed
   > Failed to transform ahbottomnavigation-3.3.0.aar (com.github.wix-playground:ahbottomnavigation:3.3.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not download ahbottomnavigation-3.3.0.aar (com.github.wix-playground:ahbottomnavigation:3.3.0)
         > Could not get resource 'https://www.jitpack.io/com/github/wix-playground/ahbottomnavigation/3.3.0/ahbottomnavigation-3.3.0.aar'.
            > Could not HEAD 'https://www.jitpack.io/com/github/wix-playground/ahbottomnavigation/3.3.0/ahbottomnavigation-3.3.0.aar'. Received status code 521 from server: 
```

It appears that this error comes from the shared IP address of the GitHub runner getting rate limited due to not just request I have made but by request anyone using the public GitHub Actions runners have made to GitHub.

I have encountered a similar issue with other actions too
https://github.com/autero1/action-terragrunt/issues/68

## Pitch

Upload to Maven Central or another repository so that request are less likely to get rate limited

### Are you willing to resolve this issue by submitting a Pull Request?

I don't know what the upload process looks like, if it is done manually or if CI controls it so I don't have enough information to make a PR to fix this issue. I can update docs on how to use a new repository once it has been uploaded.

**Comment by emrahyurttutan** [comment]
There seems to be a general problem with jitpack. Or is this place completely closed?

**Comment by yogevbd** [comment]
Look like the problem was in jitpack servers. closing
