### ISSUE TITLE
React Native 0.71.0 react-native-navigation:compileReactNative68DebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by ertugruldogan** [wix/react-native-navigation#7668]
## ❓ [Questions and Help](react-native-navigation:compileReactNative68DebugJavaWithJavac FAILED)

React Native 0.71.0 react-native-navigation - not working.
https://wix.github.io/react-native-navigation/docs/installing/
"react-native-navigation": "7.30.6",
> Task :react-native-navigation:compileReactNative68DebugJavaWithJavac FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative68DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by yogevbd** [comment]
Should be resolve in 7.31.0
