### ISSUE TITLE
Are navigatorButtons' leftButtons disabled on Android?

### ISSUE THREAD

**Issue by jkomyno** [wix/react-native-navigation#767]
I don't know if this actually is an issue or if it's just a question, but:
how come that ```leftButtons``` are disabled on Android? Take [FirstTabScreen.js](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/FirstTabScreen.js) for example. The ```leftButtons``` are displayed on iOS but not on Android. So, ```event.id === "menu"``` in [onNavigatorEvent(event)](https://github.com/wix/react-native-navigation/blob/master/example/src/screens/FirstTabScreen.js#L46) never gets fired on Android.

**Comment by guyca** [comment]
Hey @jkomyno 
On Android, the `id` property of LeftButton is an enum which accepts four properties:
* back
* cancel
* accept
* sideMenu

This might change soon but I'll add this to the docs to prevent confusion.

**Comment by jkomyno** [comment]
Thank you very much. That's exactly what I needed.

**Comment by guyca** [comment]
No problem. Also update the [docs](https://github.com/wix/react-native-navigation/wiki/Adding-buttons-to-the-navigator#android-left-button)

**Comment by Fenwil** [comment]
Hi @guyca using your official example `leftButtons` seems to be working but doing a project from scratch for myself isn't working (using the lastest version`v2.0.0-experimental.275` ).

So investigating a little bit theres a `TitleBarLeftButtonParamsParser.java` that I don't have on my react-native-navigation.

I'm forgetting about something or this is not available yet ?

**Comment by Fenwil** [comment]
@guyca I already fix it. It was my fault:

```
Navigation.startSingleScreenApp({
  screen: {
    screen: 'Home',
    navigatorStyle: {},
    navigatorButtons: {},
  },
  drawer: {
    left: {
      screen: 'DrawerMenu',
    },
  },
  animationType: 'slide-down',
});
```

When I remove navigatorStyle and navigatorButtons started working everything!

**Comment by jslz** [comment]
Hmm, even after reading this issue and the docs, I am confused about how to get this working on Android. :-) The code here below is working for me on iOS but not on Android. I only see the right button. What should / can I do to get the 'Done' appearing as a left text button on Android? Thanks!

```
const DONE_ID = 'done';
const CANCEL_ID = 'cancel';
  static navigatorButtons = {
    leftButtons: [{
      title: '   Done',
      id: DONE_ID,
      buttonColor: 'white',
    }],
    rightButtons: [{
      title: 'Cancel   ',
      id: CANCEL_ID,
      buttonColor: 'white',
    }],
  };
```

**Comment by fcochim** [comment]
How to enable /Disable  a Nav Bar  Right Button on iOS?
