### ISSUE TITLE
Overlay Screen with `interceptTouchOutside` doesn't work correctly on Android

### ISSUE THREAD

**Issue by joetannenbaum** [wix/react-native-navigation#7674]
### What happened?

On a fresh React Native installation (0.71 and 0.71.1 thus far), an overlay screen on Android with `interceptTouchOutside: false` isn't behaving correctly, you can't interact with the screen underneath it. It still works correctly on iOS.

### What was the expected behaviour?

With `interceptTouchOutside: false` specified, you should be able to interact with the content beneath the overlay.

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### Help us reproduce this issue!

1. Clone https://github.com/joetannenbaum/sample-react-native-navigation-overlay-bug
2. Yarn
3. npx react-native run-android

This screen is where the `interceptTouchOutside` option is specified:

https://github.com/joetannenbaum/sample-react-native-navigation-overlay-bug/blob/main/OverlayScreen.tsx

### In what environment did this happen?

React Native Navigation version: 7.31.1
React Native version: 0.71.1
Has Fabric (React Native's new rendering system) enabled: (yes/no) no
Node version: 19.4.0
Device model: Pixel 3XL and Pixel 6 Pro
Android version: 12 and 13

**Comment by Omelyan** [comment]
Any updates on this..?

**Comment by Omelyan** [comment]
ok, I'm not familiar with Kotlin and Java at all, but here's how I solved it:

/lib/android/app/src/main/java/com/reactnativenavigation/utils/MotionEvent.kt

```javascript
+import android.view.ViewGroup

fun MotionEvent.coordinatesInsideView(view: View?): Boolean {
     view ?: return false
-    view.getHitRect(hitRect)
+    val content = ((view as ViewGroup).getChildAt(0) as ViewGroup).getChildAt(0) as ViewGroup // it looks like sht but I don't know Kotling at all
+    content.getHitRect(hitRect)
     return hitRect.contains(x.toInt(), y.toInt())
}

```
so without even knowing RN in nitty gritty details, it seems that the latest version somehow wraps the root view in containers and we should get overflow's child dimensions instead of the parent's one.

**Comment by anglingiq** [comment]
Having the same issue. @Omelyan solution worked for me!

**Comment by LYevhen** [comment]
Having same issue, for some reason after patch apply created by @likesebiii or direct module modification with @Omelyan proposal did not fix an issue, instead of click was not intercepted, now app just crash.

**Comment by aschmitz-wbd** [comment]
> can confirm the above patch [#7674 (comment)](https://github.com/wix/react-native-navigation/issues/7674#issuecomment-1436954602) fixes it for me as well.

Same thing here. Solved our problem, too.

**Comment by leandro-faria** [comment]
Is there any PR for this issue?

**Comment by clytras** [comment]
@likesebiii maybe you should consider opening a PR with this patch code, it fixes the issue.

**Comment by fiznool** [comment]
Sadly this hasn't fixed the issue for me. I'm running RN 0.67 with RNN 7.32.1, on Android 12.

**Comment by MatthewPattell** [comment]
@yogevbd Could you tell me please, why do not merge the PR that fixes this?

**Comment by yogevbd** [comment]
@MatthewPattell Fixed tests and now merging 💯

**Comment by tiempham** [comment]
I'm using react-native 0.71.6 apply batch above not working for me.

**Comment by thuongtv-vn** [comment]
It is not working for me too.

**Comment by animatereactnative** [comment]
Still doesn't work 
"react-native": "0.72.5",
 "react-native-navigation": "7.37.0",

**Comment by stoutatnerdery** [comment]
This issue is still there in 7.37.1, using RN 0.71.11... Using patch-package and the examples above I was able to fix the issue.

**Comment by aschmitz-wbd** [comment]
We are facing the same problem @thuongtv-vn mentioned.

"react-native": "0.72.7",
"react-native-navigation": "7.37.2"

**Comment by birkir** [comment]
I had to just do a different implementation for Debug, no way around it in Release using viewgroup scanning.

```kotlin
fun MotionEvent.coordinatesInsideView(view: View?): Boolean {
    if (BuildConfig.DEBUG) {
        val viewGroup = (view as ViewGroup).getChildAt(0) as ViewGroup
        return if (viewGroup.childCount > 0) {
            val content = viewGroup.getChildAt(0)
            content.getHitRect(hitRect)
            hitRect.contains(x.toInt(), y.toInt())
        } else {
            false
        }
        return true
    }

    view ?: return false
    view.getHitRect(hitRect)
    return hitRect.contains(x.toInt(), y.toInt())
}
```
