### ISSUE TITLE
dismissModal shows the root nav icons, instead of the right ones.

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#768]
Ok, so if I **push to a new screen**, and from that screen I **showModal**, and then I **dismissModal** the nav bar shows the icons and titles from the **root screen** instead of the **pushed screen** as it should.

Ever seen or heard of that before?
Thanks

react-native 0.39.2

**Comment by guyca** [comment]
Hey, I'm assuming this happens only on Android. You probably have margin around the root container instead of padding.

**Comment by SudoPlz** [comment]
@guyca No idea if it happens on Android. I experienced this on iOS and no I don't have a margin around the root container.

**Comment by guyca** [comment]
How are the root screens buttons and title defined? statically in navigatorButtons and startApp or dynamically via setButtons and setTitle?

**Comment by SudoPlz** [comment]
@guyca They are both statically defined on init and later on dynamically set via setButtons.

**Comment by SudoPlz** [comment]
Note that what happens is this:

**I get an error this way:**
`Parent screen --> (Push to screen 1) --> (show modal screen 2) --> (hide modal screen 2) --> We now see the nav items for the Parent screen instead of screen 1.`


If instead of pushing screen 1 I show it as a modal this does **not** happen.

**I DON'T get an error this way:**
`Parent screen --> (show modal screen 1) --> (show modal screen 2) --> (hide modal screen 2) --> We now see the nav items for the screen 1 as it should be.`

Does this help?

**Comment by SudoPlz** [comment]
Ok I found out what causes this.
I'm setting the navBarButtons on `componentWillReceiveProps` of the parent.

1) Is `componentWillReceiveProps` supposed to be running on the Parent screen when we're in screen 1 or 2?

2) How can I receive the current screen from `navigator` in order to add something like the following if clause:

```javascript
if ( navigator === "Parent" ) {
    // set the nav buttons etc
}
```

Thanks.

**Comment by guyca** [comment]
`componentWillReceiveProps` is called regardless of the screen being visible or not. If it's connected, and store changes - it's called.

I think relying on `componentWillReceiveProps` is bad since it causes unpredictability. I prefer the explicitness of calling navigator commands form the constructor or `componentWillMount`

**Comment by SudoPlz** [comment]
I'd do that, but I need to update the nav bar when certain changes take place..
So is there no way for me to know the screen I'm currently on?
