### ISSUE TITLE
[Android] app:compileDebugJavaWithJavac react-native 0.72.2

### ISSUE THREAD

**Issue by 4mm4r7** [wix/react-native-navigation#7680]
### What happened?

Note: Recompile with -Xlint:unchecked for details.
/Users/dlx-21/Documents/Ammar/Company/The_Source/source_app/android/app/src/main/java/com/source_app/MainActivity.java:17: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/dlx-21/Documents/Ammar/Company/The_Source/source_app/android/app/src/main/java/com/source_app/MainActivity.java:21: error: cannot find symbol
        getMainComponentName(),
        ^
  symbol:   method getMainComponentName()
  location: class MainActivity

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### In what environment did this happen?

React Native Navigation version:  7.31.1
React Native version:  0.71.2
Has Fabric (React Native's new rendering system) enabled: yes
Node version: v18.7.0

**Comment by markmadlangbayan** [comment]
Is there a solution for this?

**Comment by Omelyan** [comment]
yeap, MainActivity (for initial project) should look like this:
`javascript
public class MainActivity extends NavigationActivity {}
`
so just delete the override of getMainComponentName

**Comment by xgenem** [comment]
Will there be a new  version?
