### ISSUE TITLE
Custom fontSize in bottomTab is not working for first item on Android

### ISSUE THREAD

**Issue by pufinek** [wix/react-native-navigation#7694]
### What happened?

For first item in bottomTab is fontSize ( only on Android) different then for the exactly same item on different place. It is not possible to change fontSize for this item.

Tested on Android 12.0 - Xiaomi Redmi Note 9 Pro
react-native-navigation: 7.30.2, 7.32.1

Image for fontSize: 12 and fontSize:20
First and second item (Home) on images are completely same. 

<img width="623" alt="image" src="https://user-images.githubusercontent.com/16817572/225587811-99e9a860-8c72-4c60-ad84-d85ad7edff4e.png">

### What was the expected behaviour?

Custom fonSize is applied on all tabs

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### In what environment did this happen?

React Native Navigation version: 7.30.2, 7.32.1
React Native version: 0.70.6
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 19.6.0
Device model: Xiaomi Redmi Note 9 Pro
Android version: 12.0

**Comment by sashansk3** [comment]
Hello, @pufinek
Looks like you need to use [selectedFontSize](https://wix.github.io/react-native-navigation/api/options-bottomTab#selectedfontsize) prop.

**Comment by pufinek** [comment]
@sashansk3  Yes, it is working, thx
