### ISSUE TITLE
Topbar custom background overlay the title

### ISSUE THREAD

**Issue by nhatth219** [wix/react-native-navigation#7697]
### What happened?

Im using the custom background for tabbar background.
Root configuration:
```
  Navigation.setDefaultOptions({
    sideMenu: {
      left: {
        visible: false,
      },
    },
    topBar: {
      background: {
        component: { name: RouterComponentNames.TOP_BAR_BACKGROUND },
      },
})
```
Background Component: 
```
const TopBarBackgroundView: FC<TTopBarBackgroundProps> = () => {
  return (
    <LinearGradient
      colors={['#99A1D5', '#11CBCA', '#E554AE']}
      style={{ flex: 1 }}
      start={{ x: 0, y: 0 }}
      end={{ x: 1, y: 0 }}
    ></LinearGradient>
  )
}
TopBarBackground.name = RouterComponentNames.TOP_BAR_BACKGROUND
```
Issue:
<img width="870" alt="Screen Shot 2023-04-07 at 16 22 06" src="https://user-images.githubusercontent.com/114040146/230583801-e9d0989b-6ec2-4458-8b13-09e7e9b39b3c.png">

### What was the expected behaviour?

Title show in both android and ios

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### In what environment did this happen?

React Native Navigation version: 7.32.1
React Native version: 0.71.6
Has Fabric (React Native's new rendering system) enabled: (yes/no) yes
Node version: v16.14.0
Device model: Iphone 11 
iOS version: Ios 15.5

**Comment by thaycacac** [comment]
I got the same problem :'(

**Comment by tyson90** [comment]
+1

**Comment by mykyta-rusyn** [comment]
The same for me. RNN - 7.38.3, RN - 0.72.12
