### ISSUE TITLE
EventListener registerBottomTabLongPressedListener doesn't work on Android

### ISSUE THREAD

**Issue by niklasarnitz** [wix/react-native-navigation#7698]
### What happened?

I implemented the `registerBottomTabLongPressedListener` as follows:

```typescript
Navigation.events().registerBottomTabLongPressedListener(({ selectedTabIndex }) => {
    console.log('BottomTabLongPressedListener::', selectedTabIndex);
});
```

On iOS it outputs the selected tab index. On Android it doesn't. (It just switches to the long pressed tab)

### What was the expected behaviour?

It should correctly trigger the event.

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### In what environment did this happen?

React Native Navigation version: 7.32.1
React Native version: 0.71.3
Has Fabric (React Native's new rendering system) enabled: no
Node version: v16.17.0
Device model: Xiaomi Redmi Note 10 Pro and Samsung Galaxy S23
Android version: 12, 11

**Comment by hoorsa** [comment]
hi,
Did you find any solution?
