### ISSUE TITLE
Inconsistent Navigation Animations when using Navigation.push inside a showModal

### ISSUE THREAD

**Issue by GhayoorUlHaq** [wix/react-native-navigation#7711]
### What happened?

When using the Wix React Native Navigation library, I've encountered an issue with inconsistent animations between the top bar and content when navigating from a modal. Specifically, the issue occurs when using **Navigation.push** within a component displayed using **Navigation.showModal**. When navigating within the modal, the top bar and content animations appear to be out of sync. However, when using **Navigation.push** outside of the modal, the top bar and content animations are in sync as expected.

### What was the expected behaviour?

The top bar and content animations should be in sync when navigating from a modal, similar to when using **Navigation.push** outside the modal context.

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### Help us reproduce this issue!

- Create a screen with a button that opens a modal using Navigation.showModal.
- In the modal component, add a button that navigates to another screen using Navigation.push.
- Observe the animations between the top bar and content when navigating inside the modal.

### In what environment did this happen?

React Native Navigation version: 7.33.0-alpha.7
React Native version: 0.70.1
Has Fabric (React Native's new rendering system) enabled: no
Node version: 18

**Comment by nicolaosm** [comment]
Experiencing same Issue!
