### ISSUE TITLE
View not rendered on iOS - RNN 7.32.1 + RN 0.71.3

### ISSUE THREAD

**Issue by jobinabraham** [wix/react-native-navigation#7715]
### What happened?

Yeah ..so we have upgraded the react native app to 71.3 and React-native-navigation to 7.32.0. The Android part is working fine...but in iOS for some reason the view doesn't get rendered even though desired components are getting loaded..tried following the docs as mentioned and also tried their issues section ..no solution seems to be working for me..You can see it is reaching the login alert via setroot ....that I have added in login/index.tsx....There are no errors in the console. I can the the component is mounted. 

### What was the expected behaviour?

View should have rendered properly

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### Help us reproduce this issue!

![ios-issue](https://github.com/wix/react-native-navigation/assets/9764162/4be90e14-242c-4a7a-8e98-c4196ae4c1d7)

### In what environment did this happen?

React Native Navigation version: 7.32.1
React Native version: 0.71.3
Has Fabric (React Native's new rendering system) enabled: (yes/no)  no
Node version: 18.14.0
Device model: iPhone 13
iOS version: 16.3.1

**Comment by yogevbd** [comment]
Fixed in latest version, 7.36.0
