### ISSUE TITLE
Android 14 compatibility

### ISSUE THREAD

**Issue by androideveloper** [wix/react-native-navigation#7751]
### What happened?

We are exploring Android 14 and possibility to target it as soon as possible. In Android 14, Runtime-registered broadcasts receivers must specify export behavior. 

There's one place in rn-navigation library, where a broadcast is registered without specifying the export behaviour. You can find it [here](https://github.com/wix/react-native-navigation/blob/357397f3c96ab2d4d06170a3b44ea3a485c7d46a/lib/android/app/src/main/java/com/reactnativenavigation/react/JsDevReloadHandler.java#L52). The way to fix this is bumping androidx.core dependency to be able to use the latest APIs for `ContextCompat` class.

On the other hand, we've noticed, that this class `JsDevReloadHandler ` is initialized on app start, even for release builds. I've not found any checks for debug/release in the code. Isn't this supposed to run only on debug version of the app?

### What was the expected behaviour?

- `JsDevReloadHandler ` shouldn't be initialized on release builds.
- registering broadcast receiver should be compatible with android 14

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### In what environment did this happen?

React Native Navigation version: 7.32.1
React Native version: 0.71.7
Has Fabric (React Native's new rendering system) enabled: no
Node version: 16.14.2
Device model: Pixel 6 Pro, android 14 beta
Android version: 14

**Comment by androideveloper** [comment]
It's still relevant

**Comment by danialseikh34** [comment]
I am facing same issue how I can fix this ?
