### ISSUE TITLE
change #7156 modals no longer work on iOS

### ISSUE THREAD

**Issue by RobertGary1** [wix/react-native-navigation#7752]
### What happened?

Updated from 7.17.0 to 7.17.1 modal dialogs stop working on iOS

import {
 , Modal,
  Text,,
  View
} from 'react-native';

      <Modal
          presentationStyle={'pageSheet'}
          animationType="slide"
            visible={true}
          <View style={{backgroundColor: 'white'}}>
<Text>hello</Text>
</View
</Modal>

### What was the expected behaviour?

Modal should appear as they do in 7.17.0

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### Help us reproduce this issue!

import {
 , Modal,
  Text,,
  View
} from 'react-native';

      <Modal
          presentationStyle={'pageSheet'}
          animationType="slide"
            visible={true}
          <View style={{backgroundColor: 'white'}}>
<Text>hello</Text>
</View
</Modal>

### In what environment did this happen?

React Native Navigation version:    react-native-navigation": "7.17.1",

React Native version:     "react-native": "0.66.1",

Has Fabric (React Native's new rendering system) enabled:no
Node version: 16.13.2
Device model: iphone 14
iOS version: 16.2

**Comment by RobertGary1** [comment]
Looks like this chnage is when it stopped working
https://github.com/wix/react-native-navigation/pull/7156

**Comment by scottgrunerud** [comment]
I am also having this issue

**Comment by yogevbd** [comment]
hey, did you test it on the latest RNN version?
