### ISSUE TITLE
iOS build failed with new architecture of React Native

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#7753]
### What happened?

I got this error message when making build with new architecture of react native
`react-native-navigation/lib/ios/RNNReactView.h:2:9: 'React/RCTFabricSurfaceHostingProxyRootView.h' file not found`

### What was the expected behaviour?

Build OK

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### In what environment did this happen?

React Native Navigation version: 7.33.3
React Native version: 0.72.3
Has Fabric (React Native's new rendering system) enabled: yes
Node version: v18.14.2
Device model: Simulator iPhone 14 Pro
iOS version: 16.4

**Comment by abhayagrawal-fareye** [comment]
not using [react-native-navigation](https://github.com/wix/react-native-navigation) but still getting this error
