### ISSUE TITLE
Lack of documentation with Redux

### ISSUE THREAD

**Issue by anonrig** [wix/react-native-navigation#776]
Hello,

Even though I really want to use react-native-navigation with my current projects, because of the lack of documentation on using react-native-navigation with redux, I can't, and I'm stuck with react-native-router-flux. Is there a proper example that is up to date with React 0.4x?

**Comment by JuneDomingo** [comment]
Hi @anonrig , checkout this [repo](https://github.com/JuneDomingo/movieapp).

**Comment by anonrig** [comment]
Thanks man @JuneDomingo

**Comment by SeanDunford** [comment]
@junedomingo can you add that example to the README.MD.

**Comment by junedomingo** [comment]
Hi @SeanDunford , they already added that in [Usage](https://github.com/wix/react-native-navigation/wiki/Usage) .

**Comment by henrikra** [comment]
@junedomingo How exactly this repo is done with react-native-navigation + redux? Since if you look at https://github.com/junedomingo/movieapp/blob/master/src/modules/movies/MoviesList.js#L85 you will see that the modal state is not going to the redux store? Or am I missing something? If so can @junedomingo provide tutorial or at least README to his repo :D

**Comment by anonrig** [comment]
Instead of requiring the component itself in the screens.js (registering screen component), you can require the component by requiring the redux container. Therefore, you can easily access the redux state. @henrikra

**Comment by henrikra** [comment]
So how for example I can push new screen with redux-saga?

**Comment by ysfzrn** [comment]
@henrikra +1 
Is there any example with redux-saga ?

**Comment by ysfzrn** [comment]
I did implementation like old-redux-example. It works well. 

**Action**
```js
export const ToPush =(root)=>({
    type:'CHANGE_ROUTE',
    root
})
```

**reducer**
```js
const initialState = {
  root: 'intro' 
};

export default function navigation(state = initialState, action = {}) {
  switch (action.type) {
    case 'CHANGE_ROUTE':
      return {
        root: action.root
      };
    default:
      return state;
  }
}
```

**Saga**
```js
...
export function* getUserSaga(feathersApp) {
  yield takeEvery("LOGIN_SUCCEEDED", tryGetUser, feathersApp);
}
function* tryGetUser(feathersApp, action) {
  const user = yield call(getuser, feathersApp);
  yield put({ type: "GET_USER", user });
  yield put(ToPush("main"));
}
...
```

**App**
```js
...
export default class App {
  constructor() {
    store.subscribe(this.onStoreUpdate.bind(this));
  }

  onStoreUpdate() {
    const { root } = store.getState().navigation;

    if (this.currentRoot != root ) { //!Important
      this.currentRoot = root;
      iconsLoaded.then(() => {
        this.startApp(root);
      }); 
      
    }
  }

  startApp(root) {
    switch (root) {
      case "intro":
        Navigation.startSingleScreenApp({
          screen: {
            screen: "mychatapp.IntroScreen", // unique ID registered with Navigation.registerScreen
            navigatorStyle: {
              navBarHidden: true
            }
          },
          animationType: "fade",
          appStyle: {
            orientation: "portrait"
          }
        });
        return;
      case "login":
        Navigation.startSingleScreenApp({
          screen: {
            screen: "mychatapp.LoginScreen",
            navigatorStyle: {
              navBarHidden: true
            }
          },
          animationType: "fade",
          appStyle: {
            orientation: "portrait"
          }
        });
        return;
      case "signup":
        Navigation.startSingleScreenApp({
          screen: {
            screen: "mychatapp.SignUpScreen",
            navigatorStyle: {
              navBarHidden: true
            }
          },
          animationType: "slide-down",
          appStyle: {
            orientation: "portrait"
          }
        });
        return;
      case "main":
...
```

**Comment by tmaly1980** [comment]
OK I think that example makes sense, but are you sure that calling startSingleScreenApp for every single redux/saga navigator push is the most efficient approach? It might be needed any time a saga depends upon an external API and needs to redirect to a different screen depending on the result (or only navigate/redirect on success).

Also, hard coding the root like this in startApp() limits pushing from redux/saga to a few use cases, why not have startApp() accept the screen name itself instead?

**Comment by maitham1** [comment]
Can you not just pass the navigator object through to the saga?
