### ISSUE TITLE
Navigator (v2) crashed on Android API16/API25

### ISSUE THREAD

**Issue by valeriik** [wix/react-native-navigation#777]
I'm trying to launch it on Android API16 and API25 but fail.
With iOS looks like everything ok.

### Steps to Reproduce / Code Snippets / Screenshots
1. Deployed all changes from here
https://github.com/wix/react-native-navigation/wiki/Installation---Android#important
2. Run "react-native run-android" on Terminal

Android 4.1 / API16:
BUILD SUCCESSFUL, but App crashed in virtual device with error - "Unfortunately, [app name] has stopped."

Android 7.1.1 / API25:
BUILD SUCCESSFUL, but I see only white screen without any errors.
![2017-02-18 13 43 38](https://cloud.githubusercontent.com/assets/24571089/23093009/547cd4c8-f5e0-11e6-8758-2b185c81a374.png)
In Chrome Developer Tools there are not any errors as well.

### Environment
* React Native Navigation version: 2.0.0-experimental.219
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): Android
* Device info 
Simulator/Device? - Simulator Android 4.1 (API16), Simulator Android 7.1.1 (API25)
OS version? - MacOS 10.12.3
Debug/Release? - Debug

P/S
In the above-mentioned wiki instruction in point "5. Implement isDebug and createAdditionalReactPackages methods" I think missed 1 import:
"import android.support.annotation.NonNull;"
Without it I received build error:
"...error: cannot find symbol @NonNull"

**Comment by JuneDomingo** [comment]
Hey @valeriik, on your 'android/build.gradle', try to update the dependency 
 to
 -        classpath 'com.android.tools.build:gradle:1.3.1'	

and 'android/gradle/wrapper/gradle-wrapper.properties'

-          distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip

**Comment by valeriik** [comment]
with yours proposition:

"BUILD FAILED
...
FAILURE: Build failed with an exception.
Failed to apply plugin [id 'com.android.application']
> Gradle version 2.2 is required. Current version is 2.14.1."

After I have changed

distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
to
distributionUrl=https\://services.gradle.org/distributions/gradle-2.2-all.zip

BUILD SUCCESSFUL, but on my Android 5.1.1 I see the same white screen
