### ISSUE TITLE
react-native undefined is not an object (evaluating RCCManager.setRootController)

### ISSUE THREAD

**Issue by jainh** [wix/react-native-navigation#779]
### Issue Description

[not able to run navigation tab on ios - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[react-native-navigation, react-native-controllers but issue still exist - It will be extremely helpful]

---
### Environment
* React Native Navigation version: 1.0.30
* React Native version: 0.40.0
* Platform(s) (iOS, Android, or both?): 8.0
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6s

**Comment by guyca** [comment]
Hey @jainh
1.030 isn't supported - please switch to the [experimental version](https://github.com/wix/react-native-navigation/wiki/Installation---iOS#installation---ios)

**Comment by bilalma** [comment]
I'm currently facing this issue on simulator kindly someOne share the solution
