### ISSUE TITLE
 No matching variant of project :react-native-navigation was found. The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:RNN.reactNativeVersion' with value 'reactNative57_5', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.1'

### ISSUE THREAD

**Issue by MasterAlex7** [wix/react-native-navigation#7796]
* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :react-native-navigation.
     Required by:
         project :app
      > No matching variant of project :react-native-navigation was found. The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:RNN.reactNativeVersion' with value 'reactNative57_5', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.1' but:
          - Variant 'reactNative68DebugApiElements' capability ARKManagement:react-native-navigation:unspecified declares a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.1', attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug':
              - Incompatible because this component declares an API of a component, as well as attribute 'com.android.build.api.attributes.ProductFlavor:RNN.reactNativeVersion' with value 'reactNative68' and the consumer needed a runtime of a component, as well as attribute 'com.android.build.api.attributes.ProductFlavor:RNN.reactNativeVersion' with value 'reactNative57_5'
          - Variant 'reactNative68DebugRuntimeElements' capability ARKManagement:react-native-navigation:unspecified declares a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.1', attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.ProductFlavor:RNN.reactNativeVersion' with value 'reactNative68' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.ProductFlavor:RNN.reactNativeVersion' with value 'reactNative57_5'
          - Variant 'reactNative68ReleaseApiElements' capability ARKManagement:react-native-navigation:unspecified declares a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.1':
              - Incompatible because this component declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'com.android.build.api.attributes.ProductFlavor:RNN.reactNativeVersion' with value 'reactNative68' and the consumer needed a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:RNN.reactNativeVersion' with value 'reactNative57_5'
          - Variant 'reactNative68ReleaseRuntimeElements' capability ARKManagement:react-native-navigation:unspecified declares a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.1.1':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'com.android.build.api.attributes.ProductFlavor:RNN.reactNativeVersion' with value 'reactNative68' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:RNN.reactNativeVersion' with value 'reactNative57_5'

**Comment by bhagatpratik07** [comment]
were you able to solve this?

**Comment by bhagatpratik07** [comment]
so I found a fix for anyone wondering 

In the file `app/build.gradle` 

Change this -
 `missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57_5"`
 
 to 
 
 `missingDimensionStrategy "RNN.reactNativeVersion", "reactNative71"`
