### ISSUE TITLE
Options.overlay.interceptTouchOutside disfunctional

### ISSUE THREAD

**Issue by aight8** [wix/react-native-navigation#7797]
### What happened?

When I display an overlay screen, and set the interceptTouchOutside option to false, it is not possible to interact with UI elements on the screen behind it.

### What was the expected behaviour?

If I display an overlay screen (component layout), and set the interceptTouchOutside option to false (no matter if in the defaults, in showOverlay or on the screen component options), it should be possible to interact with elements on the screen behind (behind the overlay screen).

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### Help us reproduce this issue!

```
Navigation.showOverlay({
	component: {
		name: 'OverlayComponent',
		options: {
			layout: {
				componentBackgroundColor: 'transparent',
			},
			overlay: {
				interceptTouchOutside: false,
			}
		},
	},
})
```

### In what environment did this happen?

React Native Navigation version: 7.37.1
React Native version: 0.72.6
Has Fabric (React Native's new rendering system) enabled: no
Node version: 20.8.0
Device model: iPhone 13 Pro (device)
iOS version: 17.1

**Comment by aight8** [comment]
It's an issue with react-native-gesture-handler
https://github.com/software-mansion/react-native-gesture-handler/issues/514

**Comment by james-ovens-eurostar** [comment]
This is still a problem, I don't think this issue should be closed just because the problem originates in another library being used

**Comment by donatoaguirre24** [comment]
@james-ovens-eurostar in case it helps, we were able to workaround the issue by setting `pointerEvents="box-none"` in the root view (so only the overlay content respond to touch events)
