### ISSUE TITLE
[Android] Could not find method compile() for arguments [directory 'libs']

### ISSUE THREAD

**Issue by zocario** [wix/react-native-navigation#78]
Hello, I am starting to use your wonderful library and I am really happy with it on iOS !
..but I have issues to run it on Android. I just followed the instruction on your readme page, and I got the following error:

<img width="844" alt="capture d ecran 2016-06-23 a 15 43 42" src="https://cloud.githubusercontent.com/assets/800617/16305311/8b4473ce-3959-11e6-8f72-c288e5711cd4.png">

Here is my build.gradle file:

      buildscript {
          repositories {
              jcenter()
          }
          dependencies {
              classpath 'com.android.tools.build:gradle:1.3.1'

              // NOTE: Do not place your application dependencies here; they belong
              // in the individual module build.gradle files
          }
      }

      allprojects {
          repositories {
              mavenLocal()
              jcenter()
              maven {
                  // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                  url "$rootDir/../node_modules/react-native/android"
              }
          }
      }

      dependencies {
          compile fileTree(dir: "libs", include: ["*.jar"])
          compile "com.android.support:appcompat-v7:23.0.1"
          compile "com.facebook.react:react-native:+"
          debugCompile project(path: ':react-native-navigation', configuration: 'libraryDebug')
          releaseCompile project(path: ':react-native-navigation', configuration: 'libraryRelease')
      }

Any ideas? Thanks!

**Comment by guyca** [comment]
Seems like you've edited the wrong gradle file. You should edit the `build.gradle` filed that's under the `app` folder.

**Comment by zocario** [comment]
Oh my god, sorry about that it was really a rookie mistake.. thanks for your quick answer!

**Comment by Bhumi07** [comment]
For Facebook Analytics I am getting this.Please tell me fast how to solve this?
Error:(12, 0) Could not find method implementation() for arguments [com.facebook.android:facebook-android-sdk:[4,5)] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler. <a href="openFile:G:\AndroidStudio\PhotoCrop-master\FbTesting\build.gradle">Open File</a>

**Comment by lordkiz** [comment]
@Bhumi07 compile has been deprecated and replaced with implementation. If you are using older versions of android studio you might encounter this problem. U can manually change '`implementation`' to '`compile`' in your `/android/build.gradle`
