### ISSUE TITLE
Text in bottom bar is cut off in ipad

### ISSUE THREAD

**Issue by uma-uc** [wix/react-native-navigation#7827]
### What happened?

I had posted this on 
https://github.com/wix/react-native-navigation/issues/7506#issuecomment-1877620924. But this issue is closed. Not sure why.
This is a show-stopper.
Also, h
<img width="506" alt="Screenshot 2024-01-04 at 11 06 15 AM" src="https://github.com/wix/react-native-navigation/assets/94931629/6edd811a-8d30-41d6-bf57-8e63374b3302">
ow do I increase the padding?

### What was the expected behaviour?

I would expect that 

1. that the text does not get cutoff
2. Ideally that I am able to control the look and feel by having the text below the icon

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### In what environment did this happen?

React Native Navigation version: 
React Native version: 
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 
Device model: 
iOS version:

**Comment by aschmitz-wbd** [comment]
I am facing the same problem.
