### ISSUE TITLE
AppComponent.componentWillUnmount alternative for RNN

### ISSUE THREAD

**Issue by megahertz** [wix/react-native-navigation#785]
In a typical RN project it's easy to write code which is executed on app exit using componentWillUnmount of the root component. But with RNN the root component is changed each time you call startSingleScreenApp/startTabBasedApp. So how can I attach a handler on app exit with RNN?

**Comment by guyca** [comment]
Hey,
you can have these screens extend a base class and have that logic in the base class, or pass a callback in props to each root screen and invoke it from `componentWillUnmount`.
These methods don't work for you?

**Comment by megahertz** [comment]
Thank you for response. But how can I determine if componentWillUnmount was called on app exit or on another startSingleScreenApp call?

**Comment by guyca** [comment]
For now, you'll need to differentiate between these two use cases by yourself. Save in store or in a global variable a boolean indicating you called `startSingleScreenApp`.

Perhaps we can add an easy way to tackle this issue, like `Navigation.isStartingApp()`.

**Comment by megahertz** [comment]
Thank you @guyca , I asked just to be sure that there is no another way (something like listen to an event emitted inside native code)
