### ISSUE TITLE
Fabric is not working on IOS. 

### ISSUE THREAD

**Issue by gosha212** [wix/react-native-navigation#7865]
### What happened?

When fabric is enabled on iOS we are getting a white screen.
Looks like it never used to work.
Demo repo: https://github.com/asafkorem/react-native-navigation-demo

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### In what environment did this happen?

React Native Navigation version:  0.73.2
React Native version: 
Has Fabric (React Native's new rendering system) enabled: (yes/no) yes
Node version: 
Device model: 
iOS version:

**Comment by TheLonelyAstronaut** [comment]
Hey, I spent some time and investigated an issue: 

After migration to RN73 (Thanks, @gosha212),`RNNReactView` now extends from `RCTSurfaceHostingProxyRootView` and uses new `initWithBridge:` implementation (with Fabric) with `RCTFabricSurface` instance. In `initWithBridge:` method, we call `[super initWithSurface:surface sizeMeasureMode:sizeMeasureMode]`, but this method located in `RCTSurfaceHostingView` (parent for `RCTSurfaceHostingProxyRootView`)  and does not call `[surface start]` (unlike `RCTSurfaceHostingProxyRootView` `[super initWithSurface:surface]` that calls it, but it does not allow us to specify `RCTSurfaceSizeMeasureMode`), so all we need to do is to call `[surface start]` after `RNNReactView` init:

<details>
<summary>New Expo app</summary>

![image](https://github.com/wix/react-native-navigation/assets/50376577/addc8554-7d37-468d-bc9f-c312b5d09a19)

</details>

<details>
<summary>RNN Playground</summary>

![image](https://github.com/wix/react-native-navigation/assets/50376577/3e4d9826-2783-4261-8328-f014cdfdf673)

</details>

 Created a very small PR to fix this issue: [Fix](https://github.com/wix/react-native-navigation/pull/7867)
 
Also few days ago I created Expo plugin for this wonderful library, it supports SDK 49 and SDK 50 (RN 72 & 73): [RNN Expo Plugin](https://github.com/TheLonelyAstronaut/rnn-expo-plugin)
