### ISSUE TITLE
About IOS folder ReactNativeNavigation xcodeproj

### ISSUE THREAD

**Issue by wq13718048209** [wix/react-native-navigation#787]
Hello author, I'm very like your this project, because it in the android and apple phones is running very smoothly, so I also want to using it on their own projects, but I have a problem, the first is the introduction of [NPM install - sava react - native - navigation], I can't find in the Xcode (ReactNativeNavigation xcodeproj) this file, because I found that your case is some, there is an error under the android, I simply check and found that after introduction, in the android project directory and the contents inside And you are not the same as in the example, it makes me very upset, don't know what to do, because I think the library is really great!Than the official process a lot!I hope you can help me to solve!Thank you very much

**Comment by guyca** [comment]
Hey @wq13718048209 
Sorry for the late reply. I'm not sure I understood entirely the issue you've described, but you can `npm install` in the example app and use it as a bootstrap.
