### ISSUE TITLE
ReactNative 0.42.1 ?

### ISSUE THREAD

**Issue by rborn** [wix/react-native-navigation#789]
Any chance to update to use the latest RN ? Thank you 😸

**Comment by benkraus** [comment]
This is the pull request that should help things along: https://github.com/wix/react-native-navigation/pull/723

**Comment by rborn** [comment]
@benkraus Thank you 👍

**Comment by benkraus** [comment]
Support for 0.41.2 was just added, in case you were curious.

**Comment by guyca** [comment]
Thanks @benkraus

**Comment by rborn** [comment]
@benkraus Thank you sir!
