### ISSUE TITLE
[Android] Configuration with name 'libraryDebug' not found.

### ISSUE THREAD

**Issue by brah** [wix/react-native-navigation#79]
getting this error when trying to run `react-native run-android`:

>`* What went wrong:
>A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-navigation : Configuration with name 'libraryDebug' not found.`

any idea what i'm doing wrong?

**Comment by guyca** [comment]
Where are you running the command? In one of our example projects? Your own project?
Did you update `settings.gradle`?

**Comment by brah** [comment]
Hi @guyca,

running this command in my own project. i've updated both my settings and build.grade

**Comment by guyca** [comment]
Just to rule this out, can you please try to invalidate your gradle cache and restart android studio?

**Comment by brah** [comment]
Just did so and got the same error

**Comment by guyca** [comment]
I'm not sure what wrong with your setup, This is the first time someone reports this issue. 
```groovy
include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(
            rootProject.projectDir, '../node_modules/react-native-navigation/android/app/')
```

maybe your directory structure is different then the expected path?

In the project structure panel and build variants - Do you see `react-native-navigation`?
<img width="233" alt="screen shot 2016-06-24 at 8 35 13 am" src="https://cloud.githubusercontent.com/assets/12352397/16328834/b00bd638-39e6-11e6-82dd-e40ac0e55fa9.png">

**Comment by chrisdukey** [comment]
I just got this error on a project, turns out I'd forgotten to run `npm install react-native-navigation --save` in my project folder. Doh!

**Comment by dg92** [comment]
@brah did you get it resolved ?

**Comment by guyca** [comment]
@dg92 What version of RNN are you using? `latest` or `next` tag?

**Comment by dg92** [comment]
@guyca 
"react-native": "^0.32.0",
 "react-native-navigation": "^2.0.0-experimental.105",

**Comment by guyca** [comment]
@dg92 A few weeks ago the [Android configuration](https://github.com/wix/react-native-navigation/wiki/Installation---Android) changed. There are minor changes you need to make to your gradle files.

**Comment by dg92** [comment]
@guyca  urgently need this package for android and RN 0.34
