### ISSUE TITLE
topBarElevationShadowEnabled not working

### ISSUE THREAD

**Issue by zhong6739168** [wix/react-native-navigation#791]
hi, I have a problem.I want to get rid of the shadow below the title bar,I set topBarElevationShadowEnabled is false, but not working.

`static navigatorStyle = {
        topBarElevationShadowEnabled: false
    };`
![image](https://cloud.githubusercontent.com/assets/9208390/23248111/ad12051c-f9d8-11e6-85c7-ce7db2706555.png)

**Comment by guyca** [comment]
Hey @zhong6739168 
Works for me on Android 6 simulator, It also works for us in production. You need to have this property defined in each screen you want to remove the shadow from.

**Comment by zhong6739168** [comment]
sorry,I found the reason, I use the old version
