### ISSUE TITLE
Drawer Button disappear

### ISSUE THREAD

**Issue by sourabhkheterpal** [wix/react-native-navigation#796]
### Drawer Button disappear when upgrade to newer version
 I have upgrade from 2.0.0-experimental.155 to 2.0.0-experimental.228 and button disappear.
### Code for drawer.
  ```
Navigation.startSingleScreenApp({
    screen: {
      screen: 'canny.dashboard',
      title: 'ABC',
      topTabs: [
        {
          screenId: 'canny.dashboard.now',
          title: 'Now'
        },
        {
          screenId: 'canny.dashboard.doc',
          title: 'My Doc'
        }
      ],
      navigatorStyle: {
        navBarBackgroundColor: '#284283',
        navBarTextColor: '#FAFAFA',
        navBarSubtitleTextColor: '#FAFAFA',
        navBarButtonColor: '#FAFAFA',
        statusBarTextColorSchemeSingleScreen: 'dark',
        topTabTextColor: '#FAFAFA',
        selectedTopTabTextColor: '#FAFAFA'
      }
    },
    drawer: {
      left: {
        screen: 'canny.side.menu'
      },
      disableOpenGesture: false
    }
  });
```

Please let me know how to fix. Thanks.
---
### Environment
* React Native Navigation version: 2.0.0-experimental.228
* React Native version: 0.39.2
* Platform(s) (iOS, Android, or both?): checked on android
* Device info (Simulator/Device? OS version? Debug/Release?): checked on Simulator/Device

**Comment by guyca** [comment]
The hamburger button is no longer added by default since a lot of users asked to control when it's displayed and when not.
In every screen you'd like to have the hamburger button, add it explicitly:

```js
static navigatorButtons = {
  leftButtons: [
    {
       id: 'sideMenu'
    }
  ]
};
```

**Comment by sourabhkheterpal** [comment]
Thanks. fixed.

**Comment by mahdi-gh1373** [comment]
hi @guyca where should I use your code to show hamburger menu in my app ? when I write it in my screen it doesn't work. I should use it as a option ?

**Comment by naftis** [comment]
@mahdi-gh1373, I found a way to do add the menu manually.

1) Assign `id`  to your drawer like this:
```js
Navigation.setRoot({
  root: {
    sideMenu: {
      left: {
        component: {
          name: 'Settings',
          id: 'settingsDrawer' // <--
        }
      },
      center: {
        bottomTabs: {
          ...
        }
      },
    },
  },
});
```
2) Control the button clicks like this:
```js
/* This is not the same id that your drawer has,
 * it's only there to distinguish different button clicks
 */
const SIDEMENU_ID = 'sideMenu';

class Profile extends React.Component {
  static get options() {
    return {
      topBar: {
        // Configure your button style here
        rightButtons: [
          {
            id: SIDEMENU_ID,
            text: 'x',
            fontSize: 28,
            color: 'red'
          }
        ]
      }
    };
  }

  constructor(props) {
    super(props);

    // Bind the current component to get its' events
    Navigation.events().bindComponent(this);
  }

  navigationButtonPressed({ buttonId }) {
    if (buttonId !== SIDEMENU_ID) {
      return;
    }

    // Use the assigned id here
    Navigation.mergeOptions('settingsDrawer', {
      sideMenu: {
        right: {
          visible: true
        }
      }
    });
  }

  render() {
    return <View />;
  }
}
```

While this is a very customisable way, it is a bit painful for only adding a simple burger menu.

**Comment by fadilnatakusumah** [comment]
> 
> 
> The hamburger button is no longer added by default since a lot of users asked to control when it's displayed and when not.
> In every screen you'd like to have the hamburger button, add it explicitly:
> 
> ```js
> static navigatorButtons = {
>   leftButtons: [
>     {
>        id: 'sideMenu'
>     }
>   ]
> };
> ```

please can you explain how to do it. or atleast update the docs about the usage of sideMenu. I don't know how to do this "sideMenu"

**Comment by fadilnatakusumah** [comment]
> 
> 
> > The hamburger button is no longer added by default since a lot of users asked to control when it's displayed and when not.
> > In every screen you'd like to have the hamburger button, add it explicitly:
> > ```js
> > static navigatorButtons = {
> >   leftButtons: [
> >     {
> >        id: 'sideMenu'
> >     }
> >   ]
> > };
> > ```
> 
> please can you explain how to do it. or atleast update the docs about the usage of sideMenu. I don't know how to do this "sideMenu"

nevermind. I got it now

**Comment by naftis** [comment]
@fadilnatakusumah care to share how you did it?

**Comment by jannunen** [comment]
For some reason I did not get this working (I'm using version 2.14.0). I managed, however, to make it work with the good old `navigationButtonPressed`

`
static navigatorButtons = {
  leftButtons: [
    {
       id: 'sideMenu'
    }
  ]
}
`

I set also the icon property. And I also tried to both refer to sideMenu and Drawer:

` 
sideMenu: {
          id: 'sideMenu', 
          left: {
           component: {
              id : 'Drawer',
             name: 'app.LeftSideMenu',
      }
}
}
`

Any help would be appreciated.

**Comment by fadilnatakusumah** [comment]
@jannunen have you added `Navigation.events().bindComponent(this);` to your constructor?

**Comment by jannunen** [comment]
@fadilnatakusumah Yeah. That's why the navigationButtonPressed -method works.

But there's now something I don't grasp with the other method:

`static navigatorButtons = { leftButtons: [ { id: 'sideMenu' } ] }`

Would there be a sample code somewhere so I could figure out what I'm doing wrong...

**Comment by dhyeysejpal** [comment]
I am also not able to get this to work. @fadilnatakusumah , can you share a snippet showing how to utilize ```static navigatorButtons = { leftButtons: [ { id: 'sideMenu' } ] }; ``` in our component? Any help is appreciated.
