### ISSUE TITLE
Deep Link doesn't work

### ISSUE THREAD

**Issue by keith527** [wix/react-native-navigation#797]
### Issue Description

I write a simple demo to use deep link. I have two tabs(`home.js` and `notes.js`), There is a Button on `home.js`, when click, I want to go `note_detail.js`, and when I back from `note_detail.js`, I hope that I can back to `notes.js` not` home.js`.
now ,The question is in notes.js, the listener doesn't work when I click in the `home.js`
Thanks for help ~
### Steps to Reproduce / Code Snippets / Screenshots
- `home.js`
```javascript
//call this method when click the button in home.js
 goNoteDetail(){
            
             this.props.navigator.handleDeepLink({
                link: 'note/note_1'
            });
    }
```
- ` notes.js`
```javascript
constructor(props){
        super(props);

        this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));

    }

    onNavigatorEvent(event) {
      // doesn't in here when click the button in `home.js`
        alert(event);

        // handle a deep link
        if (event.type == 'DeepLink') {
             const parts = event.link.split('/');
            if (parts[0] == 'note') {
                // handle the link somehow, usually run a this.props.navigator command
                    this.props.navigator.push({
                    screen: 'seven.note.detail', 
                    title: 'Note Detail', 
                    passProps: {}, 
                    animated: true, 
                });
            }
        }
    }
```

---
### Environment
* React Native Navigation version:2.0.0-experimental.226
* React Native version: 0.41.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator iphone 7 plus

**Comment by vyky** [comment]
Confirmed I encounter the same issue.

This happen after I migrated to commit "migration to RN41.2" 

Isolated issue:
JS file change > live reload > Deeplink not working

Deeplink works only when build from the start (react-native run-ios)

**Comment by guyca** [comment]
Thanks a lot @vyky

**Comment by keith527** [comment]
@vyky Thanks a lot~ but you mean it can work when build by `react-native run-ios`?
I use this way ,but it still doesn't work~

**Comment by vyky** [comment]
@guyca Confirmed https://github.com/wix/react-native-navigation/pull/803 fixed my issue

@keith527 Hmm. I don't see any problem with your code above. Can you provide more detail?

**Comment by guyca** [comment]
@keith527 I'm closing the issue, if it's still not resolved please reopen.

**Comment by kyle-ssg** [comment]
Was getting this too, latest version seems all good to me 👍

**Comment by keith527** [comment]
@guyca Thank you ,I updated  and now it works well~

**Comment by srameshr** [comment]
@keith527 @guyca  I have the exact same code as yours and it does not work. I never see the onNavigatorEvent being invoked when I call handleDeepLink from different screen.

Im running on iOS simulator: 10.3, React native: 0.48.4 and navigation: 1.1.231

**Comment by kakakalot** [comment]
I met this issue same as @srameshr . My app is running on android, react-native 0.50

**Comment by leolusoli** [comment]
same problem. Please, fix it.
