### ISSUE TITLE
Screen mounts twice after live reload

### ISSUE THREAD

**Issue by codeandgraphics** [wix/react-native-navigation#800]
### Issue Description

Hello! 

My app uses redux, and I have a problem with startSingleScreenApp. When app runs, it waits for icon loader promise, then calls startSingleScreenApp with MainScreen. When I reload app with Cmd+R, MainScreen mounts twice. I'm pretty sure that startSingleScreenApp calls only once. Maybe RNN saves state when reloading? Where can I turn this feature off?)

---
### Environment
* React Native Navigation version: 2.0.0-experimental.0
* React Native version: 0.41.2
* Platform(s) (iOS, Android, or both?): both
* Device info (Simulator/Device? OS version? Debug/Release?): Any

**Comment by ryancoughlin** [comment]
I was about to post the same issue. I have noticed this the past few days and have been trying to drill into the problem and not sure what is happening. 

I am on the same environment as @codeandgraphics.

I can't think of anything else that I am doing to cause this to mount twice. Below is my app start:

```
import { Navigation } from 'react-native-navigation'

import Map from './app/components/map'
import StationDetail from './app/components/station-detail'
import TideList from './app/components/tide-list'
import BaseStyle from './app/base-styles'

Navigation.registerComponent('Salty.StationDetail', () => StationDetail)
Navigation.registerComponent('Salty.Map', () => Map)
Navigation.registerComponent('Salty.TideList', () => TideList)

Navigation.startSingleScreenApp({
  screen: {
    screen: 'Salty.StationDetail',
    navigatorStyle: BaseStyle.navigationBarStyles,
  },
})
```

![screen shot 2017-02-25 at 6 20 03 pm](https://cloud.githubusercontent.com/assets/1182341/23335626/0a185ff4-fb87-11e6-8d9c-b01810072c0e.png)

**Comment by kyle-ssg** [comment]
Had a similar issue to this in which previous screens get launched on simulator refresh, I found running on a simulator on ios 11 solved this for me.

**Comment by manjeetwadi** [comment]
is this resolved?
