### ISSUE TITLE
React/RCTBridge.h file not found Error when run on actual Device

### ISSUE THREAD

**Issue by nickrobinson352** [wix/react-native-navigation#801]
### Issue Description
I am getting an "React/RCTBridge.h file not found in RCCNavigationalController.h" when running on a device. I get no errors and the code runs perfectly, when I run this on an IOS Simulator. 

I also get the same error when I try to build the ReactNativeNavigation Project by itself from the node_modules folder using the xcode project. I also did a fresh `npm install` and still have the same issue

### Steps to Reproduce / Code Snippets / Screenshots
Screenshot : http://imgur.com/a/RCH8v
                      http://imgur.com/a/Sr3q1

---
### Environment
* React Native Navigation version: ^2.0.0-experimental.229
* React Native version: 0.39.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): **Works in Simulator but not in Actual Device (DEBUG)**

**Comment by guyca** [comment]
version .225 and above support minimum RN version of 0.40

**Comment by nickrobinson352** [comment]
I was actually on .157 when I had this issue and then upgraded. I just went back to .157 and the issue seems to have disappeared. Thanks for your help

**Comment by resure** [comment]
Same problem here, was on the "next" branch, downgrade to `.157` helped.
