### ISSUE TITLE
Custom transitions for showModal and push

### ISSUE THREAD

**Issue by jimvanzummeren** [wix/react-native-navigation#809]
Is it in any way possible to change the way views are animated when being pushed or when being presented as modal view?

Thanks!

Jim

**Comment by guyca** [comment]
Currently no, but it's planned

**Comment by dsvgit** [comment]
@guyca Hello, when will you want to implement it? we need it now. mb we can contribute it and add some pull request. Can you give some recomendations how do you see implementation?

**Comment by dsvgit** [comment]
@guyca what do you think about this implementation https://github.com/dsvgit/react-native-navigation/commit/b38b160b6d8602067fc8532441428f26f0b3f555 ?
js settings example
```javascript
nextShow: [
  {
    type: 'TRANSLATION_X',
    from: '1',
    to: '0',
    duration: 300,
    easing: 'accelerate'
  }
]
```

**Comment by Findiglay** [comment]
Is this still currently planned?
