### ISSUE TITLE
How to reset navbar buttons for screen

### ISSUE THREAD

**Issue by musicode** [wix/react-native-navigation#81]
By default, navbar has a back button and title.

if i switch to a editable form, i set the right buttons(Edit).

if the form submit success or i press back button, app will back to the prev screen，i want to know how to keep the prev screen navbar buttons.

**Comment by guyca** [comment]
You can define them in your screen and when ever it's displayed, these buttons will be set in the toolbar
```js
class FirstTabScreen extends Component {

  static navigatorButtons = {
    rightButtons: [
      {
        title: 'Edit',
        id: 'edit'
      },
      {
        icon: require('../../img/navicon_add.png'),
        title: 'Add',
        id: 'add'
      }
    ]
  };
}
```

**Comment by musicode** [comment]
i found there are many issues like it, because i don't know the current screen, i can't hide the navbar and tabbar, i can't reset the nav buttons.

for this  issue, i think the default back button(left arrow) is nice, i want to use it, but how ?

**Comment by musicode** [comment]
if trigger some events when press the default back button, all the issues will be fixed, because i can keep a screen stack in business logic.

**Comment by musicode** [comment]
```javascript
this.props.navigator.setOnNavigatorEvent(event => {
    if (event.type === 'NavBarButtonPress') {
        // default and custom back button use the id 'back' 
        if (event.id === 'back') {
            store.dispatch(...)
        }
  }
})
```
just for

**Comment by guyca** [comment]
We plan to release a new version soon with improved API to support such use cases. For now, You can try to use `shouldComponentUpdate` and `componentWillUpdate`.

**Comment by musicode** [comment]
how long to wait for the new version?

**Comment by guyca** [comment]
I'm afraid I can't really give an estimate ATM.

**Comment by musicode** [comment]
thank you, i like this project, it solved my app's performance issue, i will waiting for new the features!

**Comment by guyca** [comment]
@musicode 
We've added option to handle back button in JS.

* Set `overrideBackPress` when you [push](https://github.com/wix/react-native-navigation/blob/master/example-redux/src/screens/FirstTabScreen.js#L166) a screen.
* [Handle](https://github.com/wix/react-native-navigation/blob/master/example-redux/src/screens/PushedScreen.js#L66) back press in your screen

Hope this helps you

**Comment by musicode** [comment]
unfortunately, the default back button has no event.

**Comment by guyca** [comment]
@musicode You need to set [overrideBackPress](https://github.com/wix/react-native-navigation/blob/master/example-redux/src/screens/FirstTabScreen.js#L170) when pushing the screen. Then you can [handle back press event](https://github.com/wix/react-native-navigation/blob/master/example-redux/src/screens/PushedScreen.js#L66)

**Comment by musicode** [comment]
@guyca I implement the same feature in v1.x like below:

```javascript
this.props.navigator.setButtons({
    leftButtons: [
       {
           id: 'back',
           icon: xx
       }
    ]
})
this.props.navigator.setOnNavigatorEvent(event => {
  if (event.type === 'NavBarButtonPress') {
    if (event.id === 'back') {
      this.props.navigator.pop()
    }
  }
})
```

I feel it is the same as your suggestion.

I hope I can get the default back button(maybe native button) press event, because it is more fast than overrided js button.

another question, how to get the current screen? push or pop by gesture, I don't know what happened.

**Comment by guyca** [comment]
@musicode Currently we don't support custom left buttons on Android. When you push a screen, it automatically gets a back button, so no need to specify one yourself.
You can still explicitly set left button, if you want to change its color. To do that, use:

```js
this.props.navigator.setButtons({
    leftButton: {
      id: 'back',
      color: '#ffffff'
    }
})
```

The api is a bit different between iOS and Android. on Android you need to set `leftButton` object instead of `leftButtons` which is an array of objects. That's temporary and we'll adapt the api to the iOS version.

Once you defined you leftButton, you can handle button press events like [this](https://github.com/wix/react-native-navigation/blob/master/example-redux/src/screens/PushedScreen.js#L57)

Currently we support only 4 left buttons:
* hamburger
* back
* accept
* cancel

You can run `example-redux` project, it's implemented there.

**Comment by musicode** [comment]
what is the different between this two:

```
this.props.navigator.setButtons({
  leftButton: {
    id: 'back',
    color: '#ffffff'
  }
})
```

```javascript
this.props.navigator.setButtons({
  leftButtons: [
    {
      id: 'back',
      color: '#ffffff'
    }
  ]
})
```

**Comment by guyca** [comment]
leftButton !== leftButton**_s_**
__________________________^

`leftButtons` accepts and array of buttons while `leftButton` is a single object.

_BUT_ eb8579c should consolidate the apis, try it and let me know.

**Comment by musicode** [comment]
the api is a little confused. I don't know when to use leftButton and when to use leftButtons.

I guess author think left of navbar has one button in most cases, so provide a [Object] config.

the standard way is use an Array config.

**Comment by guyca** [comment]
@musicode You're absolutely. We realised it was a poor decision on our side and consolidated the apis. Now `leftButtons` work on both iOS and Android.

**Comment by musicode** [comment]
I have try leftButton like this:

```javascript
static navigatorButtons = {
    leftButtons: [
      {
        id: BUTTON_BACK_ID,
        color: '#FFFFFF',
      }
    ],
    rightButtons: []
  }

this.props.navigator.setOnNavigatorEvent(event => {
        console.log(event)
        if (event.type === 'NavBarButtonPress') {
          let { id } = event
          if (typeof this[id] === 'function') {
            this[id]()
          }
        }
      })
```

the back button is become white, but has no log, so I have to use custom back button, right?
