### ISSUE TITLE
Action sheets displayed behind lightbox

### ISSUE THREAD

**Issue by hammadj** [wix/react-native-navigation#812]
### Issue Description
Action sheet (or any other presented view) is displayed behind LightBox when a lightbox is open. Presenting it again then correctly shows it above the screen.

### Steps to Reproduce / Code Snippets / Screenshots

![](https://media.giphy.com/media/xUPGchUOkAdzydvsju/giphy.gif)

---
### Environment
* React Native Navigation version: 2.0.0-experimental.166
* React Native version: 0.37.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6S Simulator, iOS 10.2, Debug

**Comment by eard7** [comment]
I faced a similar issue, i was trying to open a lightbox before launch the facebook login window, but the lightbox remained in the front. To solve that, i changed from lightbox to a modal.

**Comment by ittikorns** [comment]
+1, I'm experiencing this same problem with AlertIOS as well.

**Comment by guyca** [comment]
fixed in 1.1.128

**Comment by ouabing** [comment]
Just found the same problem when using v2 overlay

**Comment by geroale** [comment]
Same here
