### ISSUE TITLE
Remote image as button in navbar?

### ISSUE THREAD

**Issue by peteclark3** [wix/react-native-navigation#815]
I'm not having an issue per se, just am having trouble trying to figure out how to use a remote image as a button in the nav bar (since in my case it will be a user avatar image).  I've tried resolveAssetSource (in which case I get an error as though resolveAssetSource wasn't called).. as well as prefetching the image with Image.prefetch, but even then I can't figure out the right syntax to pass it as a rightButton icon.. 

My current try is: 
```
Image.prefetch(store.getState().user.loggedInUser.user_avatar).then( () => {
      Navigation.startSingleScreenApp({
        screen: {
          screen: 'my.MyApp',
... 
navigatorButtons: {
          ...
            rightButtons: [
              {
                icon: this.searchIcon,
                disableIconTint: true
              },
              {
                icon: this.props.prefetchedSource, // have also tried other props, and just this
                disableIconTint: true
              }
            ]
...
```

Is anyone willing to help?

**Comment by tvansteelandt** [comment]
Anyone found a solution to this?

**Comment by goncalo-msrt** [comment]
You can create a new component for that, and then pass it in the rightButtons {component: 'RegisteredComponent'}

you can even attach it to redux and get the image itself

**Comment by pqkluan** [comment]
You could either use the custom component for navbar button or fetch the image first then [set the buttons](http://wix.github.io/react-native-navigation/#/screen-api?id=setbuttonsparams-) at the screen.
