### ISSUE TITLE
How use tabs/tab icon with backgroundImage/image or backgroundColor transparent

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#816]
Hi Guy,

I want style tabs/tab icon with backgroundImage/image or backgroundColor transparent.

How i can do? Thanks so much!

**Comment by guyca** [comment]
Hey @agumack 
https://github.com/wix/react-native-navigation/wiki/Styling-the-tab-bar
Did you try using `tabBarBackgroundColor: 'transparent'` ?

**Comment by barghi** [comment]
@agumack any solution ?
