### ISSUE TITLE
SideMenu not showing up

### ISSUE THREAD

**Issue by ericacooksey** [wix/react-native-navigation#818]
### Issue Description

When I set `drawer` in Navigation.startSingleScreenApp, it does not show up. I can neither open in by dragging nor by clicking the `sideMenu` left button.

### Steps to Reproduce / Code Snippets / Screenshots

Here is a gist with my relevant code: https://gist.github.com/ericacooksey/7314b004d6eba0050e17a9a8aeb18435 . The second file is the SideMenu.

---
### Environment
* React Native Navigation version: 2.0.0-experimental.236
* React Native version: 0.38.0
* Platform(s) (iOS, Android, or both?): Only tested on Android
* Device info (Simulator/Device? OS version? Debug/Release?): Marshmallow emulator in debug

**Comment by vivekparekh8** [comment]
@ericacooksey : how did you resolve this ?

**Comment by BigPun86** [comment]
+1

**Comment by guyca** [comment]
If you're on Android, you need to use `sideMenu` id on the `LeftButton` https://github.com/wix/react-native-navigation/wiki/Adding-buttons-to-the-navigator#android-left-button

**Comment by BigPun86** [comment]
I am running into same issue on ios with following environment:

React Native Navigation version: 2.0.0-experimental.238
React Native version: 0.42.0
Platform(s): Android and iOS
Device info (iOS Simulator): Marshmallow emulator in debug

```
Navigation.startSingleScreenApp({
  screen: {
    screen: 'screen.Splash',
    title: 'Navigation',
    navigatorStyle: {
      navBarHidden: true
    }
  },
  drawer: {
    left: {
      screen: 'drawer.SideMenu',
    },
    disableOpenGesture: false, // on false can the drawer be opened with a swipe instead of button
  },
  animationType: 'slide-down',  // optional, add transition animation to root change: 'none', 'slide-down', 'fade'
});
```

**Comment by guyca** [comment]
@vivekparekh8 @BigPun86 the example app has a [SideMenu](https://github.com/wix/react-native-navigation/blob/master/example/src/app.js#L48) and afaik everything works fine. If something doesn't work - please be more specific and explain exactly what doesn't work for you.

**Comment by vivekparekh8** [comment]
@guyca Apologies. Thank you for the response. I got it. (I upgraded RNN to experiental 200 that's why I faced this.)
