### ISSUE TITLE
Login Redux example

### ISSUE THREAD

**Issue by PoloGarcia** [wix/react-native-navigation#826]
### Login Redux example

Hi have been looking around for a Redux example using this library, I see that you recommend checking out the movie app example. But so far I can help to find it useful for my case where I have two single screen apps (one is login and the other is the actual app) 

How do I transition from one to another using redux? 

Here is what I have been doing so far:

```
startApp() {
    if (store.getState().login.token) {
      Navigation.startSingleScreenApp({
          screen: {
            screen: 'globalTill.MainScreen',
            title: 'Product List',
            navigatorStyle: {},
          },
        });
    } else {
      Navigation.startSingleScreenApp({
          screen: {
            screen: 'globalTill.Login',
            navigatorStyle: {
              navBarHidden: true,
            },
          },
        });
    }

  }
```

Thanks in advance for any help 👍 
---
### Environment
* React Native Navigation version: @next
* React Native version: 0.41.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by guyca** [comment]
What's wrong with your current approach? Seems good 👍

**Comment by PoloGarcia** [comment]
@guyca Hi :) I'm fairly new to redux, so I was wondering what should I do when the store gets updated how do I transition from the login to my actual app. 

Thanks

**Comment by guyca** [comment]
When your store updates after a user logged in, you can dispatch an action that will start the actual app.

**Comment by mattharrison** [comment]
Is there an example of this somewhere? I need to transition to another page after a REST call. In https://github.com/react-community/react-navigation when using redux, the navigator is shimmed into the reducers so you can just do a dispatch to change the page.

My logic to perform the REST request is not in my page, so it doesn't have access to the navigator. Would love an example, as the movieapp doesn't appear to have one.

**Comment by mattharrison** [comment]
I ended up passing in a callback to my asynchronous action. My action called the callback after it had fetched the data. The callback called ``this.props.navigator.resetTo...``

**Comment by PoloGarcia** [comment]
@mattharrison we ended up inspiring ourselves from the deprecated example of redux they have here.

**Comment by jaspal747** [comment]
@PoloGarcia thanks for pointing to the old redux example. It helped me with the same issue.

Just in case someone needs it, 
https://github.com/wix/react-native-navigation/blob/master/old-example-redux/src/app.js

To update the app on login/logout etc. use the **store.subscribe()** method and then dispatch your login success action and update the app accordingly.

Cheers

**Comment by ODelibalta** [comment]
I would love to see an example for this. I am currently using what is in the first post which looks okay to me to be honest. I am still looking for a good redux example though. I have created an app state reducer that I want to use for things such as showing a lightbox when appState.isloading is true. I have everything working except I do not know where to put the show lightbox command. I rather have it just at one place if possible instead of having the same code across my screens. I've [posted on SO about this](https://stackoverflow.com/questions/45654051/should-i-handle-navigation-in-my-reducer-react-native-wix-navigation?noredirect=1#comment78267259_45654051) as well

**Comment by hmenzagh** [comment]
@mattharrison Did you have any luck in finding a way to call dispatch from redux itself ?
