### ISSUE TITLE
Navbar white flash when pushing

### ISSUE THREAD

**Issue by danieljvdm** [wix/react-native-navigation#828]
I'm trying to push a view with the following navbar style:
```
  static navigatorStyle = {
    navBarBackgroundColor: '#05668D',
    navBarButtonColor: 'white',
    navBarTransparent: true,
    drawUnderNavBar: true,
    navBarNoBorder: true,
    statusBarHidden: true,
    screenBackgroundColor: '#05668D'
  }
```

The result is the following. The primary view has a `navBarHidden: true` setting, and if I don't hide it the entire navbar flashes white during the push. Bare in mind this only shows for about 1s then comes right.

![white-navbar](https://cloud.githubusercontent.com/assets/3450486/23649319/5d892cc4-031e-11e7-9196-d2416b944bf0.png)

---
### Environment
* React Native Navigation version: next (236)
* React Native version: 0.42
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator 10.2

**Comment by pqkluan** [comment]
Hi ,

```
