### ISSUE TITLE
Drawer uses over 130% CPU

### ISSUE THREAD

**Issue by siwymilek** [wix/react-native-navigation#835]
I noticed that if I put drawer into my app, CPU usage increases to over 130%. In other cases (if drawer isn't initialized) CPU usage isn't greather than 5%.
My drawer is just simple View without any child DOM nodes, without any unnecessary imports.

The problem occurs probably only on iOS. I tested it on release configuration.

---
### Environment
* React Native Navigation version: next 236
* React Native version: 0.41.1
* Platform: iOS
* Device info: Device iOS 10.2.1 / Release

**Comment by Lichwa** [comment]
Is there any update on this?

**Comment by simonmitchell** [comment]
Any news on what's going on here? This is causing real issues for our app 😕

**Comment by simonmitchell** [comment]
Seems like `layoutSubviews` of the side panel's `RCTRootView` is getting called recursively for some reason. Will continue to investigate when I next get a chance

**Comment by guyca** [comment]
@simonmitchell No news. We don't use a side menu in our app - so I don't think someone will look into it 😢
