### ISSUE TITLE
[iOS] peculiar bug

### ISSUE THREAD

**Issue by lipingruan** [wix/react-native-navigation#836]
### Issue Description

I open new window by press button, but no display window and **can't do anything in screen**.

an transparent view cover over my views and buttons.

then i swipe from left to right, new window show the right, finger more to right, window show more.

when i loosen finger, window be close.

### Steps to Reproduce / Code Snippets / Screenshots

finger swipe from left to right on button [ gently and quickly onPress triggered ]

---
### Environment
* React Native Navigation version: all
* React Native version: >=0.25.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): any iOS version

**Comment by grundmanise** [comment]
https://github.com/wix/react-native-navigation/issues/428
