### ISSUE TITLE
Show a loading screen while app is transitioning from a singleScreenApp to a tabBasedApp

### ISSUE THREAD

**Issue by grundmanise** [wix/react-native-navigation#837]
Is it possible to show a loading screen (native) while the app is transitioning from a `singleScreenApp` to a `tabBasedApp`. I need to show a loading screen because the UI flickers while switching to the `tabBasedApp`. Only native screen can handle this..

**Comment by grundmanise** [comment]
So, I managed to _almost_ completely hide UI flicker using `animationType: fade`

**Comment by yungobiwan** [comment]
Hey @grundmanise  how are you doing this. I have a similar situation where i'm calling Navigation.startSingleScreenApp() for an onboarding screen and Navigation.startSingleScreenApp()
to launch main app after onboarding. I will like to fade the transition between onboarding  and the main app.

How are you hiding UI flicker using animationType:fade

**Comment by grundmanise** [comment]
@yungobiwan I've just added `animationType: 'fade'` to the Navigation.startTabBasedApp({})  and Navigation.startSingleScreenApp({}). Take a look here, there is an example: https://github.com/wix/react-native-navigation/wiki/Top-Level-API
