### ISSUE TITLE
tabBasedApp prerender all tabs

### ISSUE THREAD

**Issue by grundmanise** [wix/react-native-navigation#838]
### Issue Description

When using `tabBasedApp` and when switching tabs for the first time UI flickers (while components are not rendered). I use `screenBackgroundColor` so I don't have that white flicker, only flicker while components are not rendered.

My question is: 
**Is it possible to prerender all tabs?**

**Comment by guyca** [comment]
Hey
We've never encountered this issue in our apps. All bottom tabs are mounted and rendered on creation time. Can you create a project where this issue is reproducible?

**Comment by grundmanise** [comment]
I'll try to create a project on the next week.
When launching a `tabBasedApp` I can see that all tab screens are rendered - screen component's `componentDidMount` is called 5 times (I have 5 tabs). I have a custom tabbar (`View` with buttons) and the default iOS tabbar is hidden. Each button in my tabbar calls the `swtichToTab` method with the  appropriate tab. But when switching to each tab for the first time I can see the UI flickers while `RN` renders my components. On the second and further `switchToTab` everything is fine.

**Comment by guyca** [comment]
It's possible `swtichToTab` causes the views to rerender

**Comment by grundmanise** [comment]
UI flicker is very noticeable because I've got a contrast button in the custom tabbar which jumps for a few `ms` to the top left corner of the screen and after to the actual location. This button is styled with a plain `style` prop. I don't have any conditional/onLayour styling

**Comment by newappco** [comment]
same issue, on the first time of switching tab the UI is white flicking a while.

**Comment by grundmanise** [comment]
@newappco check `navigatorStyle` `screenBackgroundColor` prop. Should fix white flicking.

**Comment by newappco** [comment]
@grundmanise 
here is my style
const navigatorStyle = {
	statusBarColor: Colors.searchBar,
	navigationBarColor: Colors.main,
	navBarBackgroundColor: Colors.main,	
	screenBackgroundColor: '#fff',
	navBarTextColor: '#ffffff',
	navBarButtonColor: '#ffffff',
	statusBarTextColorScheme: 'light',
	navBarHidden: true,
	tabBarButtonColor: '#aaa',
	tabBarSelectedButtonColor: Colors.main,
	tabBarBackgroundColor: '#fff'
};
what is your suggestion?

**Comment by grundmanise** [comment]
set `screenBackgroundColor` to the bg color of your screen component

**Comment by Crash--** [comment]
I've the same issue with TabBased App without using switchToTab. First click on a tab it flickers, second one everything is fine. (iOS)

**Comment by newappco** [comment]
@grundmanise set screenBackgroundColor, it's still showing flickering screen (with backgroundColor) before tabscreen is loaded

**Comment by grundmanise** [comment]
@newappco I also have flickering while components aren't loaded... `screenBackgroundColor` hides 'white' flickering

**Comment by newappco** [comment]
@grundmanise yes, set screenBackgroundColor just fix white flickering, the tab screen is still showing background color for a while before component is loaded. It should show the loading screen (inside the component - loading screen before data is get from api) instead

**Comment by hose314** [comment]
Encountered the same issue worth to mention that screen has hidden nav bar so the flickering more notable.
It's happened only once at first time when you push on tab button.

**Comment by blairvanderhoof** [comment]
Same issue, when the user clicks the second tab, it renders the screen way off the top left of the screen (somewhere -1000px x -1000px y).

**Comment by rauliyohmc** [comment]
Happening to me as well...and this is super annoying. As @blairvanderhoof mentioned, first time we click on a tab it renders the content on the top left corner for few ms, then the content gets placed correctly. On 2nd iterations over visited tabs, the issue does not occur. Did somebody manage to find a workaround or put together an example repo?

**Comment by blairvanderhoof** [comment]
Also I'm testing a version of my app where I put all of the fetch calls into component did mount with a set time out of 300 ms. My theory is that the fetch calls and also calls to things like code push and sentry are causing it to interrupt the render flow.Steven Liu also has this theory.

**Comment by rauliyohmc** [comment]
I managed to put into place a workaround for the issue. You can check out this [gist](https://gist.github.com/rauliyohmc/b89ab1bcd96c7cf095e1afbc0bb5fd25).

It basically holds off rendering the content of the tab, the first time we switch to a new one. That prevents the top left garbled render from happening.

If your screens use a different background color than white, you'd also need to set the `screenBackgroundColor` property in your `navigatorStyle`, such as:

```js
tabs: [
      {
        label: Foo,
        screen: 'Screens.Foo',
        icon: require('../foo.png'),
        title: Foo,
        navigatorStyle: {
          screenBackgroundColor: $YourBGColor, // <-- Match your background color here
        },
      },
      ...
];
```

**Comment by blairvanderhoof** [comment]
@rauliyohmc nice work! Have you ever encountered an issue where the content is completely blank or stuck? Or do you just have the flicker issue?  I wonder if the wix team can investigate why the content appears messed up briefly. Seems the tabs aren't sized appropriately to begin with then later recover?

**Comment by rauliyohmc** [comment]
@blairvanderhoof my app uses a darked background so I had a combination of flickering issue + content off its expected position for some ms. 

I never experienced the content being stuck though.

**Comment by grundmanise** [comment]
Hey guys,

I think that _"content off its expected position for some ms"_ is due to element's styles.
Some styles are faster to calculate (e.g. width: 100 is faster to calculate than width: "30%"), thus some elements are rendered faster than those with "slower" styles, and because of this they are aligned incorrectly in relation to "still calculating styles" elements.
For me switching to "slower" styles (i.e left: 200 -> left: "xx%", width: 50 -> "width: xx%") on the elements that appeared off for some ms solved the issue.

**Comment by rauliyohmc** [comment]
@grundmanise suggestion worked for me. I used `Dimensions` from React Native instead of `flex: 1`. Those are my styles for the top most container views, for each tab:
```js
const styles = StyleSheet.create({
  container: {
    flex: Platform.OS === 'android' ? 1 : undefined,
    width: Platform.OS === 'ios' ? Dimensions.get('screen').width : undefined,
    // 20 (status bar) + 44 (navigation bar) + 49 (tab bar)
    height:
      Platform.OS === 'ios' ? Dimensions.get('screen').height - 113 : undefined,
  },
});
```

**Comment by linasmnew** [comment]
Fixed it: Add `overflow: 'hidden'` to parent `<View>` ‘s of all tab components which have this issue, and also add it to their child components which contain the particular UI that is jumping up.

**Comment by sfratini** [comment]
@grundmanise @guyca Guys, tabs being pre rendered at creation time is awful from a performance point of view. Is there a way to disable this? The app works fast, but the servers are being overloaded for no reason. I would like the tabs/topTabs to mount when the user clicks on them.

**Comment by chrise86** [comment]
@sfratini I think that's generally how tab navigation works, at least on iOS.

**Comment by sfratini** [comment]
@chrise86 Well, this is happening in Android too. I understand the benefit, however I have multiple clients that will say this is a bad practice because you are making requests to the server when there is no need to, so other requests suffer from it. Specially in long and demanding queries. I think I found a way around it listening to tab selected events however I need to test it. It would be great to be able to disable this globally.

**Comment by Crash--** [comment]
@sfratini You can workaround this by simply storing the current displayed screen and by rendering null for others. See https://github.com/wix/react-native-navigation/issues/1118#issuecomment-296578643

**Comment by sfratini** [comment]
@Crash-- Great! Actually, I was thinking about listening to tabSelected events however that would mean more logic. I was ignoring the willAppear event on the screen itself, which makes the logic more simple so thanks!

**Comment by jasperkuperus** [comment]
Ok, so @linasmnew's trick using `overflow: hidden` fixes the bug of content being rendered on the wrong position. Although having the elements in the right position, there is still a small flicker. I've made a new project to isolate and reproduce the problem. You can find the gist here: https://gist.github.com/jasperkuperus/9f4c2677c7505fc3ea0d92c30b5f84b5

In this example the flicker happens when switching tabs after one in ~7 refreshes. I've got a bigger app in which the flicker occurs at a higher frequency. I'm using RN `0.54.3` and RNN `1.1.428`. Is there a way to get rid of the flicker?

**Comment by gupta-ji6** [comment]
Try switching `lazy` to `false` in TabNavigatorConfig. See below for example. It rerenders all the tabs at once even if they are active or not.
```
swipeEnabled: true,
    lazy: false,
    navigationOptions: ({navigation}) => ({
    }),
    tabBarOptions: {
      style: {
        backgroundColor: "#222325"
      },
      activeTintColor: "white",
      indicatorStyle: {
        backgroundColor: "white"
      }
    },
    tabBarPosition: "top",
```
[Refer this link](https://v1.reactnavigation.org/docs/tab-navigator.html#tabnavigatorconfig)

**Comment by jonathanRinciari** [comment]
Another option would be to change your screen to be a PureComponent so if state/props are the same there will not be a rerender

**Comment by jneuendorf** [comment]
@rgommezz The link to your gist (in [this comment](https://github.com/wix/react-native-navigation/issues/838#issuecomment-320508603)) is not working anymore. Could you please update it?
