### ISSUE TITLE
Detect app resume / sleep

### ISSUE THREAD

**Issue by tvansteelandt** [wix/react-native-navigation#839]
### Issue Description

Screen component 'componentWillMount' function doesn't get called when app gets resumed from background.
As stated in the RN docs, it should.
And then you can detect state changes with AppState.
Is this a bug?

### Steps to Reproduce / Code Snippets / Screenshots

Resume the app, log smth in componentWillMount inside a screen

---
### Environment
* React Native Navigation version: 2.0.0
* React Native version: 0.37
* Platform(s) (iOS, Android, or both?): iOS, android not tested
* Device info (Simulator/Device? OS version? Debug/Release?): simulator iPhone 6, iOS 10

**Comment by Crash--** [comment]
if the app goes to background, componentWillUnMount() will not be called, so you don't have to worry about that. If you set an AppState listener in your componentWillMount(), this listener will remains even if the app goes to background and foreground. 

So in your componentWillMount() or componentDidMount() you can write something like : 
```jsx
componentDidMount(){
 AppState.addEventListener('change', (state) => {
    if (state === 'active') {
     console.log('state active');
    } 
   if(state === 'background'){
    console.log('background');
   }
 }
}
```

**Comment by DanielZlotin** [comment]
@tvansteelandt if it's written in the docs, then it is a bug we can fix (please share a link to this). In any case, we added screen lifecycle in the next version

**Comment by DanielZlotin** [comment]
Correction, it already exists in current version

**Comment by tvansteelandt** [comment]
Nvm, it works now. I wasn't using the event listener.
I thought componentDidMount had to fire after background resume.
This isn't the case.
My bad.

**Comment by voidstarfire** [comment]
Do we need to remove this listener on componentWillUnmount (Potencial memory leaks?)

**Comment by sujay-bidchat** [comment]
Does react native have a listener for onResume/onPause of a component, i.e
onPause - When component A goes in background and a new component B comes on top of component A.
onResume - When component B is popped and component A comes in foreground from background.

**Comment by nkov** [comment]
@sujay-bidchat within the confines of react-navigation there are [these events](https://reactnavigation.org/docs/en/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle) you can subscribe to on the `navigation` object: `didFocus`, `didBlur` to achieve this.
