### ISSUE TITLE
replaceTo without replacing root screen

### ISSUE THREAD

**Issue by perrosnk** [wix/react-native-navigation#841]
### Issue Description

During the sign up process, I am pushing some screens. At a certain point I want to give the user the ability to sign in instead, and thus want to show the log in screen, but I don't want to push it or replace all screens, because when I show the log in screen, I want to enable the user to 'go back' to the initial screen.

As far as I understand if I use `replaceTo` I will replace ALL screens, including the initial app's screen, so the user won't be able to go 'Back'. Is there a way to achieve this?

**Comment by guyca** [comment]
Show the login screen in a modal.

Modals should be used whenever you need to branch out from your current navigational stack. Once in a modal, you can push into it and reset its stack with out effecting the stack you branched out of. After the flow is complete, the modal is dismissed and you'r back in the screen you branched out of.

**Comment by Prozhxxx** [comment]
@guyca I want to change the previous route，but react-native-navigation can not do this....

**Comment by aminosman** [comment]
I have the same issue with a messaging app. If the user is in a conversation and they tap a notification from a different conversation I need to replace the current conversation screen with the one they tapped to open. Right now the navigation stack is appended to resulting in going back taking the user though all their chats until they hit the chat list screen. I do not think modal is the solution here.
