### ISSUE TITLE
switchToTab with topTabs on Android

### ISSUE THREAD

**Issue by lfabreges** [wix/react-native-navigation#842]
I'd like to use switchToTab with topTabs but it's not working, is there a way to programmatically switch to topTab ?

---
### Environment
* React Native Navigation version: 2.0.0-experimental.239
* React Native version: 0.42
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator

**Comment by guyca** [comment]
This is currently not implemented, but will be supported in the upcoming v2 version. I'll try to implement it asap for the current version.

**Comment by lfabreges** [comment]
Great! Thank you.

**Comment by elliotstokes** [comment]
This is something were quite interested in getting access to also. If you want/need any help/assistance with this then let me know.

**Comment by guyca** [comment]
@elliotstokes I'll try to get to this by the end of the week.

**Comment by guyca** [comment]
@lfabreges @elliotstokes I added `switchToTopTab`, let me know if you find any issues 👍
