### ISSUE TITLE
Push a screen from a ListView's item clicked

### ISSUE THREAD

**Issue by bdebout** [wix/react-native-navigation#843]
Hi !

Is it possible to push a screen with a click on a ListView's row ?

**Comment by bogobogo** [comment]
Hey bdebout, 

The answer is yes.
Just make sure your row is touchable and that it has access to the navigator object.
Here is an example:

`<TouchableOpacity onPress={() => this.props.navigator.push({screen: 'screenName',            title:'screenTitle')}>
               <Text> Row Content</Text>/>
  </TouchableOpacity>`

**Comment by bdebout** [comment]
Hi bogobogo !

Thanks for the answer but I still have trouble with this. I tried and I get this error:

undefined is not an object (evaluating '_this2.props.navigator.push')

I do not understand why navigator or this is undefined.
I also tried to make a touchable Text under my Listview and push the screen I want to push from my row and it works perfectly.

I linked my imports and the code I used below: (got same error with showModal or push)

![listview row](https://cloud.githubusercontent.com/assets/25125506/23847939/113dec9a-07d5-11e7-9938-4565862a8c24.png)
![imports](https://cloud.githubusercontent.com/assets/25125506/23847942/15766fe4-07d5-11e7-9d2e-ae4499de6e85.png)

**Comment by guyca** [comment]
@bdebout 
Is that list defined in a screen pushed with navigation? Seems like you don't have a navigator instance in your props.
Also, make sure you call `super(props)` in your constructor

```js
constructor(props) {
    super(props);
}
```

**Comment by bogobogo** [comment]
Hey @bdebout,

Be aware that Navigation and navigator are not the same thing. **Navigation** is used to register your screens and to launch your app ([see Wiki](https://github.com/wix/react-native-navigation/wiki/Top-Level-API)) After you launch your app the **navigator object** should be available as props and can be used to navigate between screens ([see Wiki](https://github.com/wix/react-native-navigation/wiki/Screen-API))

**Comment by bdebout** [comment]
I have a TabBaseApp (I made 4 tabs). I made another .js file where I code my ListView and I imported it in my first tab (I want to be able to reuse this ListView in other tabs too).

I declared it within index.android.js file and I call super(props) for the ListView like guyca mentioned it.

So, how to set/define my navigator object ?

Hope this helps...

**Comment by guyca** [comment]
Pass the navigator from the screen you show in the tab, to the list view via props

```js
<MyListView
  ...
  navigator={this.props.navigator}
/>
```

**Comment by bdebout** [comment]
Thanks a lot ! It's working like a charm now :)

Thanks @guyca and @bogobogo !
