### ISSUE TITLE
Screen visibility events on Android

### ISSUE THREAD

**Issue by lfabreges** [wix/react-native-navigation#844]
Below issues I ran into on Android:

- Visibility events aren't triggered when switching top tabs.
- When showing a modal, "willAppear" and "didAppear" events are triggered but with a "NavBarButtonPress" type.
- "willDisappear" and "didDisappear" aren't triggered when dismissing the modal.

---
### Environment
* React Native Navigation version: 2.0.0-experimental.239
* React Native version: 0.42
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator

**Comment by ilyaivjev** [comment]
same problem IOS 
React Native Navigation version: 2.0.0-experimental.239
React Native version: 0.42.1
Emulator

**Comment by Binsabbar** [comment]
Anyone is having the same issue? I am not entirely sure if this is an emulator issue only or not. I will confirm tomorrow if I can get hold of an android device.

I am having the exact issue in Android Emulator I have tried both React Native version: latest and experimental.

However, it is working without any issues in the iOS both simulator and physical device.

**Comment by FilipIlievski** [comment]
Any news on this issue?
