### ISSUE TITLE
Screen orientation on IOS inherits the previous style

### ISSUE THREAD

**Issue by bogobogo** [wix/react-native-navigation#846]
### Screen orientation on IOS is broken

Defining orientation in IOS works on the initial screen, but if I push to a screen with a different orientation style, the new style is ignored and the previous one remains.

### Steps to Reproduce / Code Snippets / Screenshots

1) Create a screen with orientation 'portrait'
2) Push to screen with orientation 'auto'
3) Try to change to landscape mode

---
### Environment
* React Native Navigation version: 2.0.0-experimental.240
* React Native version: 0.40.0
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): IPHONE 6S simulator

**Comment by guyca** [comment]
Orientation can be applied to the [entire app](https://github.com/wix/react-native-navigation/wiki/Top-Level-API#starttabbasedappparams) in `appStyle` or to [Modals](https://github.com/wix/react-native-navigation/wiki/Styling-the-navigator#style-object-format) in their `navigatorStyle`.

If your app is locked to portrait and you want to show a single screen in landscape orientation, show it modally and it'll work 👍

**Comment by drpiou** [comment]
I agree with @guyca but this doesn't work if I want an orientation to `auto`. So this issue is still opened for me.
