### ISSUE TITLE
collapsingToolbar without image + custom component 

### ISSUE THREAD

**Issue by steve228uk** [wix/react-native-navigation#851]
### Issue Description

It seems that the current version doesn't support a collapsing toolbar in Android without an image. This is a pretty standard pattern on Android and actually seems to be something that was implemented at one point.

https://github.com/wix/react-native-navigation/blob/3f7f42367d4c740d6e079a7098ff3fce9d76d580/src/deprecated/platformSpecificDeprecated.android.js#L144-L145

### Steps to Reproduce / Code Snippets / Screenshots

I've added the following to my `navigatorStyle`:

```js
static navigatorStyle = {
    collapsingToolBarComponent: 'twfl.OnboardingHeader',
    collapsingToolBarComponentHeight: 300
};
```

However, this returns the following:

![screenshot_1489400974](https://cloud.githubusercontent.com/assets/1169297/23850584/f99e4bc2-07d7-11e7-8b0f-83380efa26fa.png)

#### Expected pattern
![collapsing_header_animated](https://cloud.githubusercontent.com/assets/1169297/23850516/c0238772-07d7-11e7-87ba-9e37ffc303af.gif)

---
### Environment
* React Native Navigation version: next
* React Native version: 0.41.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device. Lollipop. Debug.

**Comment by guyca** [comment]
Hey @steve228uk 
I added a few missing properties to the [docs](https://github.com/wix/react-native-navigation/wiki/Android#collapsing-react-view) regarding the collapsing toolbar with react view.

Note that `collapsingToolBarComponentHeight` property is deprecated. We measure the collapsing toolbar according to the root component you have in your header screen. So your header should either have a set height or **not** have `flex: 1` in combination with `flexDirection: 'column'`

Also, your screen must have either a `ScrollView` or a `ListView` as it's root component

**Comment by steve228uk** [comment]
@guyca This is amazing, thanks so much! Feel free to close this if everything is sorted on your end.

**Comment by steve228uk** [comment]
Using a ListView with this does seem to get some strange results on first load when the data is still being loaded from the server. On debug reload it works.

![screenshot_1489417153](https://cloud.githubusercontent.com/assets/1169297/23860104/dad597ce-07fd-11e7-8848-64f87798ac59.png)
![screenshot_1489417157](https://cloud.githubusercontent.com/assets/1169297/23860106/daf77498-07fd-11e7-8d47-91e185a4091e.png)

**Comment by guyca** [comment]
What react-native-navigation version are you using?

**Comment by steve228uk** [comment]
@guyca Yep, with cached data it works. If the screen loads and then loads data from the server the height calculation seems to mess up.

**Comment by guyca** [comment]
What do you render when you open the screen with out data?

**Comment by steve228uk** [comment]
@guyca An `ActivityIndicator` so I guess that's where the problem lies…

**Comment by guyca** [comment]
Can you please try wrapping the `ActivityIndicator` with a `ScrollView`?

**Comment by guyca** [comment]
@steve228uk The current implementation assumes that if the collapsing screen's root component is either a `ListView` or a `ScrollView` - it remain as such. And if the root component is any other view, it doesn't detect the new component correctly.
I'm not sure this will be fixed in the current version, but will definitely be address in v2.

I'm closing the issue for now, please reopen if you have more questions.

**Comment by steve228uk** [comment]
@guyca Thanks, sorry I didn't get back to you, I haven't had chance to get back onto this project yet but I'll let you know if I have any further issues.

**Comment by guyca** [comment]
No worries. We also faced this issue in our app here at Wix, for now we wrapped the "problematic" view in a `ScrollView`, but as I said - will be address soon.

**Comment by steve228uk** [comment]
@guyca Curiously I get the same issue on first load when I do wrap the view or even if I display the empty `ListView`.

Here's the render method of my screen component:

```js
render() {
    if(!this.state.loaded) {
        return (
            <ScrollView contentContainerStyle={styles.scrollView}>
                <ActivityIndicator
                    animating={true}
                    style={{height: 80}}
                    size="large"
                    color="#406C97"
                />
            </ScrollView>
        );
    }

    return (
        <ListView
            style={{backgroundColor: '#fff'}}
            dataSource={this.state.dataSource}
            renderRow={this.renderRow}
            renderSeparator={this.renderSeparator}
            enableEmptySections={true}
            prerenderingSiblingsNumber={1}
        />
    );
}
```

And the stylesheet for these items is:

```js
const styles = StyleSheet.create({
    scrollView: {
        backgroundColor: '#eee',
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    }
});
```

This is the **first** screen that is displayed when the app launches if that has any effect here.

### Screenshots

![screenshot_1489602567](https://cloud.githubusercontent.com/assets/1169297/23964782/8e5ae988-09ad-11e7-9e8b-961567f14bf0.png)
![screenshot_1489602569](https://cloud.githubusercontent.com/assets/1169297/23964783/8e854ebc-09ad-11e7-8eb4-fca0c7deee62.png)

**Comment by guyca** [comment]
@steve228uk I've pushed a test screen to this [branch](https://github.com/guyca/react-native-navigation/tree/CollapseSteve228uk).
Basically the screen contains an ActivityIndicator and loads data after a short delay - seems to work.

Feel free to contact me at [discord](https://discord.gg/DhkZjq2), I'm more available there. 👍

**Comment by steve228uk** [comment]
Thanks @guyca! I'll check this out 😊

**Comment by steve228uk** [comment]
@guyca I actually get the exact same issue in the simulator with your branch. 

It could perhaps be something to do with the simulator as reloading the screen with R,R fixes the issue. Are you using the Android Studio emulator or something else?

![screenshot_1489747170](https://cloud.githubusercontent.com/assets/1169297/24039732/261d6a38-0afe-11e7-9ac5-b13641666a91.png)
![screenshot_1489747173](https://cloud.githubusercontent.com/assets/1169297/24039731/2619a04c-0afe-11e7-959b-2410bd5b91ee.png)

**Comment by guyca** [comment]
Oh this is very interesting, I managed to repro the issue. I think it happens only if the collapsing screen is the first screen displayed in a "Single screen" app, If the screen is pushed the behavior is as expected.
I'll look into it.
