### ISSUE TITLE
Feature | Support windowSoftInputMode: adjustResize

### ISSUE THREAD

**Issue by Jc160** [wix/react-native-navigation#857]
Please help support windowSoftInputMode: adjustResize in android.

Tons of thanks

**Comment by guyca** [comment]
adjust resize will be the default mode in the upcoming major version:

For now, see the docs for [instructions](https://github.com/wix/react-native-navigation/wiki/Android#adjusting-soft-input-mode).

**Comment by guyca** [comment]
@DanielZlotin `adjustResize` should be the default value in v2, wdyt?

**Comment by DanielZlotin** [comment]
Yup. 99% of the cases that's the best option
