### ISSUE TITLE
How to clean the cache for a specific tab?

### ISSUE THREAD

**Issue by agumack** [wix/react-native-navigation#86]
Hi everybody. 
The caching feature is great, but I'm facing an issue. The problem is:  I have a tab called 'Shoping Cart', It display a list products form AsyncStorage. Beause tab cached so a new item added will not display when i switch tabs :(

How clean the cache or tell react-native a screen tab data changed.

Thanks you so much!!!

**Comment by guyca** [comment]
When your app starts, do you load items from `AsyncStorage` and save them in your state? If you do, once the user adds an item to the shopping cart - reflect change in your state and the screen is supposed to render.

**Comment by agumack** [comment]
@guyca User add item to the shopping cart from tab other.

Here i have CategoriesTab and CartTab. How state on CartTab change when user add form categoriesTab?
