### ISSUE TITLE
Shared Element Transitions?

### ISSUE THREAD

**Issue by braco** [wix/react-native-navigation#860]
Any plans for this feature?

http://airbnb.io/native-navigation/docs/guides/shared-element-transitions.html

https://github.com/exponent/ex-navigation/tree/master/example-shared-element-transitions

**Comment by guyca** [comment]
Hey @braco 
This feature has been in the works for sometime, hope to merge it in on earlier next week

**Comment by Kureev** [comment]
Hi @guyca, do you have any updates on this? Maybe you need any assistance with the release or smth?

**Comment by guyca** [comment]
Hey @Kureev 
The story of Shared Element Transition (SET) on Android is pretty interesting. SET is supported natively on Android in Activities and Fragments (ick). RN forces single activity architecture, which is great, so can't use SET with Activity transitions, that leaves us with Fragments.

Since we really [detest fragment](https://medium.com/square-corner-blog/advocating-against-android-fragments-81fd0b462c97) and wanted to avoid them if we could, I [implemented SET](https://github.com/guyca/react-native-navigation/tree/sharedElementTransition) my self. The example app in this branch has two screens which demonstrate the api.

I'll try to merge the branch in it's current experimental state tonight. If it won't be good enough as the native implementation, we'll switch to Fragments 😢

**Comment by guyca** [comment]
Hey guys,
I merged the code a few days ago, you can check it out in the example app. Just make sure to [switch this field to true](https://github.com/wix/react-native-navigation/blob/master/example/src/app.js#L10). I'll also update the docs this week.

Keep in mind this is still an incubating feature, Any feedback you have would be most welcome. Regarding the api. It's pretty simple right now - if there's anything missing let me know (callbacks?)

anyways, I'm closing this for now. If any issues arise lets discuss them in different issues.

**Comment by Kureev** [comment]
Thanks for you hard work, @guyca!

Should I use any specific attributes to mark which elements should be re-used?

**Comment by guyca** [comment]
Thanks @Kureev 👍 
So I started working on the first shared element view in the Wix app, as you can see [here](http://gph.is/2nR3gOf).

Implementation is pretty simple:

From view:
```jsx
<SharedElementTransition
  sharedElementId={`SET${this.props.data.id}`}>
  <View style={{backgroundColor: 'transparent'}}>
    <Avatar initials={utils.getNameInitials(this.props.clientName)} url={this.props.avatar} size={50}/>
  </View>
</SharedElementTransition>
```

To view:
```jsx
<SharedElementTransition
    sharedElementId={`SET${this.props.data.id}`}
    showDuration={SHOW_DURATION}
    hideDuration={HIDE_DURATION}
    showInterpolation={
      {
        type: 'linear',
        easing: 'FastOutSlowIn'
      }
    }
    hideInterpolation={
      {
        type: 'linear',
        easing:'FastOutSlowIn'
      }
    }
  >
    <View style={{backgroundColor: 'transparent'}}>
      <Avatar
        initials={utils.getNameInitials(this.props.data.participants[0].name)}
        url={this.props.avatar}
        size={70}
      />
    </View>
  </SharedElementTransition>
```
> Both `SharedElementTransition` need to have the same `sharedElementId`.

These two screens were already defined when I started adding the SET to them. In this example out shared element in the `Avatar`, just has to wrap it in the `SharedElementTransition` and thats it.
Also I noticed a bug when transitioning views with rounded corners, so I wrapped the `Avatar` with a transparent `View` as a workaround  for now 😝 

The example app also has a screen where shared elements animate with curved motion (Similar to app icons in the google play app)

**Comment by Kureev** [comment]
Thanks for such an exhaustive documentation of the feature! ❤️ 

I'll give it a try in the nearest future! Once again, great feature! Looking forward for the 2.0 release. Let me know if I can do something to make it happen faster 😉

**Comment by guyca** [comment]
Hey guys
I added basic documentation of the Shared Element feature to the [docs](https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=shared-element-transition).

Still need to document the available interpolation and easing values. There are two example screens in the example app which can be found [here](https://github.com/wix/react-native-navigation/tree/master/example/src/screens/set).

@Ehesp is working on adding another very nice screen to the example app. @gran33 has started iOS implementation.

cc @Kureev @brianjd @henrikra

**Comment by varungupta85** [comment]
@guyca I have been itching to make use of this feature in the app, just as soon as I find the time. I always use to wonder how do apps such as whatsapp have such cool animations when I move from one screen to another with avatars animating into full screen images. Just realized that that was the magic of shared element transitions. Thanks for adding this awesome feature.

**Comment by kuma-guy** [comment]
@guyca  Can I use Shared Element Transitions on iOS?

**Comment by Kureev** [comment]
@kuma-guy yes, you can

**Comment by matpaul** [comment]
@guyca @gran33 Hello, any updates about this implementation in IOS ? 
Thank!

**Comment by matpaul** [comment]
@Kureev, how? - I can't find implementation in iOS side

**Comment by sagark1510** [comment]
@guyca @Kureev How to make it work on iOS?

**Comment by williambout** [comment]
Implementation is not ready yet on iOS, it'll do a simple push animation for now.

**Comment by sagark1510** [comment]
How can I achieve it on iOS in some other ways?

**Comment by guyca** [comment]
@sagark1510 You'll probably need to research how this is implemented in native iOS since each screen is a different react root view displayed in a different ViewController, then implement the js api which interacts with the native framework. I also suggest taking a look at how AirBnb implemented this feature in native-navigation - they did a very impressive job and the apis are pretty similar.

**Comment by kuma-guy** [comment]
@guyca Do you guys have a plan to implement this feature any time soon?  It seems that native-navigation by Airbnb is not ready for production yet, so  I am happy to help it if this feature is going to be implemented in this project (I am not a Swift/Obj-C expert though)

**Comment by luispuig** [comment]
I'm playing with this feature and its incredible great!!! And It will be great to get it on iOS too. The app seems awesome on Android and very Poor on iPhone.

Is there a plan to port it?

**Comment by Ehesp** [comment]
There are plans yes, however v2 is currently the priority as it'll make such features as this much easier to implement.

**Comment by luispuig** [comment]
@Ehesp Great to know.

**Comment by williambout** [comment]
@Ehesp @guyca Any ETA for the iOS implementation?

**Comment by guyca** [comment]
@williambout No ETA 😢 We had to prioritize other issues over this. If someone from the community wants to implement it, please ping me on discord 👍

**Comment by omarchacinortega13** [comment]
Any plans of releasing this feature for iOS soon?

**Comment by gran33** [comment]
@bogobogo believe he can do it by the end of the month 🙏 .
Anyway, it will on `v2` and NOT on `v1`.

**Comment by zsajjad** [comment]
We need it in iOS as well, are there any plans in near future? Also if anyone can confirm [this](https://github.com/wix/react-native-navigation/issues/2798) happening with them as wee

**Comment by alejoasotelo** [comment]
Any news for iOS?

**Comment by pie6k** [comment]
https://wix.github.io/react-native-navigation/#/docs/animations?id=shared-element is this working on iOS?
