### ISSUE TITLE
JS Debugging Bug

### ISSUE THREAD

**Issue by tolu360** [wix/react-native-navigation#862]
### Issue Description

Pushing new screens to the navigation stack results in blank screens when the push happens with Js debugging enabled, only the first screen displays normally. Things work properly when JS debugging is not enabled.

### Steps to Reproduce / Code Snippets / Screenshots

Enable JS debugging. Push a new screen to the navigation stack as usual:

```javascript
        this.props.navigator.push({
    		screen: 'myapp.Login'
    	})
```

---
### Environment
* React Native Navigation version: 2.0.0-experimental.240
* React Native version: 0.42.0
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator 10.2/ Emulator API 25/ Debug

**Comment by natdm** [comment]
Same. It is only on iOS, and both on the emulator and device, and only while debugging.
