### ISSUE TITLE
does the tabbar support swipe in iOS & Android? (question)

### ISSUE THREAD

**Issue by jasan-s** [wix/react-native-navigation#863]

**Comment by jasan-s** [comment]
yes.

**Comment by guyca** [comment]
It's not supported. It's against the material design guidelines since it's problematic when you have a tab that has `TopTabs` (TabLayout in ToolBar with a ViewPager) as well.
On iOS I understand it's also considered a bad ux pattern.

**Comment by jasan-s** [comment]
@guyca , thanks for the reply. I wanted to have a Instagram style navigation. Where swiping between top tabs and each tab has bottom tabs with out swipe capable.

**Comment by guyca** [comment]
Then that's definitely possible.
BottomTabs - don't respond to swipe.
TopTabs - respond to swipe.

You can easily add `TopTabs` in rnn (even though it's currently undocumented). You can look at the [deprecated](https://github.com/wix/react-native-navigation/issues/672#issuecomment-287020822) example project where this functionality was show cased. Will try to update the docs asap.

**Comment by jasan-s** [comment]
The deprecated example link is to another issue.

**Comment by guyca** [comment]
Sorry about that, fixed.

**Comment by Ehesp** [comment]
@jasan-s @guyca is it possible to have `topTabs` within a tab based navigator?

```
Navigation.startTabBasedApp({
  tabs: [
    {
      label: 'One',
      screen: 'example.FirstTabScreen', // this is a registered name for a screen
      title: 'Screen One',
      icon: require('./src/images/icon.png'),
      topTabs: [
        {
          screenId: 'example.FirstTabScreen.One',
          title: 'Tab1',
          passProps: {
            str: 'This is a prop passed to Tab1',
            fn: () => 'Hello from a function passed as passProps!'
          }
        },
```

it says FirstTabScreen.One used but not yet registered. Looking into it...

**Comment by guyca** [comment]
@Ehesp Sure. I think you forgot to register `example.FirstTabScreen.One`

**Comment by brycepavey** [comment]
@Ehesp did you resolve this?

**Comment by Ehesp** [comment]
Yep, check out the example on this repo.

**Comment by brycepavey** [comment]
Ah, I was testing on iOS and not Android. The context of the discussion was for cross-platform so I didn't realise this was an Android only solution. 
@jasan-s did you find a solution to the Instagram style navigation for both platforms?

**Comment by Ehesp** [comment]
You could use react-native-navigation for ios, works well just not native.

**Comment by brycepavey** [comment]
What do you mean? The example only supports tabtabs on Android

**Comment by jasan-s** [comment]
@brycepavey  I actually ended up using [react-navigation](https://github.com/react-community/react-navigation) as the primary router which uses[ react-native-tab-view](https://github.com/react-native-community/react-native-tab-view). JS approach although not ideal in terms of performance is sufficient for my use case.

**Comment by brycepavey** [comment]
Thanks @jasan-s, I'm starting a new project and have been weighing up between react-navigation and this library. 
I knew from the start that I'd be able to do everything I needed with react-navigation but would much prefer to go native. Unfortunately this type of navigation support is my last hurdle to going ahead with react-native-navigation and it might force me to go the js route 😞

**Comment by Ehesp** [comment]
You can mix and match them. https://github.com/react-community/react-navigation works as a drop in on any screen, and is simple to setup. My app uses this lib + the react-navigation :)

**Comment by jasan-s** [comment]
@Ehesp that's interesting. Curious of your motivation to use both.

**Comment by Ehesp** [comment]
Well this library provides a great performance whilst navigating between screens, and provides native functionality out of the box (snackbars etc). It's current downside is that it does lock you in to design patterns. For example on Android the bottom tabs are from a native module, and there's no real way to make it super custom using JS.

The top tabs follow the Material Design guidelines, but sometimes you need it more customisable than this, which is what react-navigation provides. In general, stick with this lib for the heavy duty actual navigation, and use react-navigation for the modular bits on a screen if you need it.

Hopefully v2 will help address these issues though :)

**Comment by arryanggaputra** [comment]
@jasan-s  Instagram have ability to hide navigation bar on scrolling, how you do that on `react-navigation` ?
