### ISSUE TITLE
showInAppNotification error when reloading JS on iOS

### ISSUE THREAD

**Issue by lfabreges** [wix/react-native-navigation#864]
### Issue Description

When I show a notification on the screen and reload JS before the notification being dismissed, the following error is raised on reload:
```
Module AppRegistry is not a registered callable module (calling runApplication)
```

It appears in the log that `Running application <Screen Name>` is ran before actually starting my application.

### Steps to Reproduce / Code Snippets / Screenshots

1. Show a notification.
2. Reload JS immediately.

---
### Environment
* React Native Navigation version: 2.0.0.experimental.246
* React Native version: 0.42
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / Debug

**Comment by guyca** [comment]
@lfabreges Thanks for reporting. It appears the root view isn't dismissed before the app is reloaded.

**Comment by gran33** [comment]
@lfabreges I can't reproduce the issue, can u plz provide some more details/steps/short video?

**Comment by lfabreges** [comment]
I didn't manage to reproduce the issue using the example app. I switched to a custom notification component in my app to have more control over it, so I'll just close this issue. Thank you.

**Comment by ujwal-setlur** [comment]
Actually, I have this issue as well, not with a notification per se, but when I push a new screen and reload from there. I think this needs to be reopened.
