### ISSUE TITLE
toggleTabs to hidden, place button in that original area can not trigger onPress event

### ISSUE THREAD

**Issue by davidmhh** [wix/react-native-navigation#868]
### Issue Description
I place button behind the tabbar, and then toggleTabs to hidden. The button located in the original tabbar area can not trigger onPress event. 

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots
`this.props.navigator.toggleTabs({
				to: 'hidden', 
				animated: true 
			})`

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: "^2.0.0-experimental.240"
* React Native version: "^0.42.0"
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by cocoalasca** [comment]
+1

**Comment by tayfunyugruk** [comment]
+1
