### ISSUE TITLE
animationType fade ignored on startSingleScreenApp and startTabbedBasedApp

### ISSUE THREAD

**Issue by steve228uk** [wix/react-native-navigation#870]
### Issue Description

When launching the app a blank screen is displayed as expected with most Android apps. However when the `startSingleScreenApp` and `startTabbedBasedApp` is called the slide up animation is played and not the fade as expected.

### Steps to Reproduce / Code Snippets / Screenshots

Here's what's being called to launch the single screen app. When launching the Gmail app this animation is not shown. It either fades or no transition is made. I have tried `animationType` of `fade` and `none` here.

```js
Navigation.startSingleScreenApp({
    appStyle: {
        tabBarBackgroundColor: '#406C97',
        tabBarButtonColor: '#0F2A49',
        tabBarSelectedButtonColor: '#ffffff',
        statusBarColor: '#365B7F',
        statusBarTextColorScheme: 'light'
    },
    screen: {
        screen: 'twfl.Onboarding',
        title: 'Follow your club'
    },
    animationType: 'none'
});
````

---
### Environment
* React Native Navigation version: next
* React Native version: 0.41.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator/Device. Lollipop. Debug.

**Comment by felipemartim** [comment]
It is also not working for me on Android.

**Comment by Ulydev** [comment]
Not working either.

**Comment by dabit1** [comment]
Not working either. The first animation that is from front to back is an expected behavior ?

**Comment by guyca** [comment]
#1197 should address this
