### ISSUE TITLE
Feature: option to pass a custom View for the tabbar.

### ISSUE THREAD

**Issue by grundmanise** [wix/react-native-navigation#873]
It would be super cool & useful if we could pass a custom `View` for the `tabbar` that replaces default `tabbar`. Nowadays a lot of apps tend to have non default tabbars with all sorts of animations. I am not that good in native dev, but I think we can use `layoutSubviews `, `insertReactSubview` and a custom `UIView` that serves as a `tabbar`. Would be glad to contribute on this as far as my knowledge allows..

**Comment by guyca** [comment]
@grundmanise This is a great suggestion and we have thought of ways to easily allow users to pass their own implementations.
Our goal is to make RNN easy to extend and create your own "plugins" to various native views. That being said, it's not in the current scope for the long awaited v2.0 release.
