### ISSUE TITLE
react-native undefined is not an object (evaluating RCCManager.setRootController)

### ISSUE THREAD

**Issue by hsukfry88** [wix/react-native-navigation#874]
### Issue Description

[ENTER DESCRIPTION HERE - Please make sure to use the current [naming conventions](https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version:0.41.2 and 42
* React Native version:15.4.2
* Platform(s) (iOS, Android, or both?):IOS

**Comment by laynemoseley** [comment]
Did you follow the installation steps completely? This happened to me when I skipped a step. 😄
