### ISSUE TITLE
Can you pass props that were not declared up front?

### ISSUE THREAD

**Issue by colin-riddell** [wix/react-native-navigation#875]
This is really a general question about react-native-navigation... sorry.

With the default Navigator, I find it really hard to pass props through the navigator that I didn't declare when creating the navigator. Is it possible to do that with this solution?

eg
in your example..
   ```
 {
      label: 'One',
      screen: 'example.FirstTabScreen', // this is a registered name for a screen
      icon: require('../img/one.png'),
      selectedIcon: require('../img/one_selected.png'), // iOS only
      title: 'Screen One'
    }
```

which means I can do
``` this.props.navigator.push(title: 'Some Screen');```
but is it also possible for me to do something like:
``` this.props.navigator.push(title: 'Some Screen', myAwesomeObject: myAwesomeObject); ```

Hope it makes sense?

**Comment by guyca** [comment]
Hey @colin-riddell 
You can [push a screen](myAwesomeObject) with a `passProps` object to pass `myAwesomeObject` which will be accessible through props.
