### ISSUE TITLE
RCCManager.h file not found.  

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#876]
Fresh install of react-native-navigation@next

After following the direction, 

Xcode8 and below, generates a build failed error,

Lexical or Preprocessor issue
RCCManager.h file not found.

### Steps to Reproduce / Code Snippets / Screenshots

yarn add react-native-navigation@next

---
### Environment
* React Native Navigation version: next
* React Native version: .42.3
* Platform(s) (iOS, Android, or both?):  iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator (XCode8 and XCode7)

**Comment by gran33** [comment]
R u try to run the example project?

**Comment by smooJitter** [comment]
The example project works. But if I start a fresh react-native init app, it falls apart as soon as I add react-native-navigation. I'm using the lastest npm.  There are a bunch (8 or more) warnings but the problem highlighted above crashes the build. Odd

**Comment by victorious85** [comment]
@gran33 I have the same issue on fresh project

**Comment by gran33** [comment]
Do u use yarn?

**Comment by victorious85** [comment]
@gran33 no just npm install

**Comment by smooJitter** [comment]
I tried it with both yarn and npm.  @gran33 it might be worth it to assume most people are at least using npm3.  The notes suggest using npm3+.  I using npm 4.1.2.  I recall reading a post suggesting this may have something to do with using npm2.  In any case.  It seems like there should be a quick work around for it.  RCCManager.h does appear in the library.  Aside from RCCManager, Xcode throws several build  warnings.  

Note, run npm install on the example project throws an error with detox during the post-installation process.

**Comment by smooJitter** [comment]
I'm not sure if this helps.  After running into problems I decided to uninstall and re-install.  An interesting thing happen, for some reason react-redux found it's way into my node_models.  In any case I reinstalled again and it worked.  Puzzling.

```
Dwaynes-iMac:RNApp smoojitter$ npm3 install react-native-navigation@next
-bash: npm3: command not found
Dwaynes-iMac:RNApp smoojitter$ npm install react-native-navigation --save
RNApp@0.0.1 /Users/smoojitter/Downloads/react-native-meteor-boilerplate-master/RNApp
└─┬ react-native-navigation@1.0.30 
  ├── react-native-controllers@2.1.4 
  ├─┬ react-redux@5.0.3 
  │ └── lodash-es@4.17.4 
  └── UNMET PEER DEPENDENCY redux@^2.0.0 || ^3.0.0

npm WARN react-redux@5.0.3 requires a peer of redux@^2.0.0 || ^3.0.0 but none was installed.
Dwaynes-iMac:RNApp smoojitter$ npm uninstall react-native-navigation
- lodash-es@4.17.4 node_modules/lodash-es
- react-native-controllers@2.1.4 node_modules/react-native-controllers
- react-redux@5.0.3 node_modules/react-redux
- react-native-navigation@1.0.30 node_modules/react-native-navigation
Dwaynes-iMac:RNApp smoojitter$ npm install --save react-native-navigation@next
RNApp@0.0.1 /Users/smoojitter/Downloads/react-native-meteor-boilerplate-master/RNApp
└── react-native-navigation@2.0.0-experimental.254 

Dwaynes-iMac:RNApp smoojitter$ react-native link react-native-navigation
rnpm-install info Android module react-native-navigation is already linked 
rnpm-install info iOS module react-native-navigation is already linked 
Dwaynes-iMac:RNApp smoojitter$ 
```

**Comment by smooJitter** [comment]
UPDATE: 
I continued to run into problems with this.  I think there may be an issue with "react-native link"

**Comment by guyca** [comment]
@smooJitter We don't support `react-native link` yet.

**Comment by asessa** [comment]
I have the same problem but only when I try to build on Release, no errors on Debug.
My search paths are both configured for debug and release.

**Comment by yifan** [comment]
@guyca can you elaborate on that? I have seen `react-native link` does the setting the same way as described in installation README.

**Comment by asessa** [comment]
In my case it solved... automagically....

**Comment by smooJitter** [comment]
This is a simple annoyance.  Sometimes i have to run "react-native link"  to setup other packages.  Unless I specify the name of the said package, link seems to pick up react-native-navigation

**Comment by smooJitter** [comment]
@guyca could you please add a bit mor information to the installation documents about this problem.  Particularly why does it happen and how to resolve it.  I always struggle starting g up a new project.  I've tried npm install v4.2 and with yarn and in both case I'm getting a RCCManager.h is not found. The documentation warns about this issue but limits the root cause to using npm 2 during install. I'm not using npm 2 and I'm still running into this problem.  I really appreciate the work you all are doing.  Each time I start a new project it takes me at least 5 hours trying to figure out how to solve this.   I usually settle wth downloading the example project and using it as my boilerplate.  Please advise.

**Comment by lin-hun** [comment]
The error makes by react-native link.
I tried to unlink,then link. It make success
Maybe can help u @smooJitter

**Comment by chrise86** [comment]
Any development on this? Hitting this issue again after trying a project with v2.0.1920

**Comment by filipcarlen** [comment]
@smooJitter @lin-hun or anyone else who might have solved this problem - can you please tell how? I have struggled with this issue for several hours and not managed to solve it. I have used yarn and done the installation process 3-4 times, without success. Nothing seems to fix this issue.

**Comment by brunolemos** [comment]
I solved this issue by following the updated v2 documentation: https://wix.github.io/react-native-navigation/v2/#/docs/installation-ios

There is no `RCCManager.h` anymore. Check full `AppDelegate.m` below:

```objc
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <ReactNativeNavigation/ReactNativeNavigation.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];

  return YES;
}

@end

```

**Comment by lefoy** [comment]
I solved this issue by using `#import "../../node_modules/react-native-navigation/ios/RCCManager.h"` instead of `#import "RCCManager.h"` in `AppDelegate.m`
