### ISSUE TITLE
reload while modal is showing, modal leaks

### ISSUE THREAD

**Issue by DanielZlotin** [wix/react-native-navigation#877]
see #878 
Maybe wix/detox#23 will help.

Currently fixed by manually unsubscribing from NotificationCenter events on JSReload and nullifying the view.

**Comment by guyca** [comment]
@trleithoff 
This issue is relates to v2 and has been fixed in the last week. What version are you using?

**Comment by trleithoff** [comment]
Here are our versions:

    "react": "16.3.0-alpha.1",
    "react-native": "0.54.2",
