### ISSUE TITLE
Pan responders not blocking SideMenu gestures 

### ISSUE THREAD

**Issue by kyle-ssg** [wix/react-native-navigation#883]
### Issue Description

I'm using https://github.com/SolidStateGroup/react-native-swipeout for a swipeable listview item, ideally I'd expect to be able to swipe one of these items without it opening the sidemenu.

IOS
<img src="http://g.recordit.co/QxqnAfMelR.gif"/>

Android
This is somewhat an issue on android too however it is less noticeable as the hit area for the SideMenu is much smaller.
<img src="http://g.recordit.co/xa1kKx7P4T.gif"/>

Is there a way to prevent bubbling or perhaps reduce the hit area for the SideMenu on iOS?

---
### Environment
* React Native Navigation version: 2.0.0-experimental.252
* React Native version: 0.40.0
* Platform(s) (iOS, Android, or both?): Both but mainly IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Debug ios 10

**Comment by rgoldiez** [comment]
@kyle-ssg did you find a work around for this?

**Comment by kyle-ssg** [comment]
I’m afraid not

**Comment by AE0011** [comment]
I have a same problem with react-native-swiper
any solution?
