### ISSUE TITLE
rightButtons click event not happening on android

### ISSUE THREAD

**Issue by Temereru** [wix/react-native-navigation#886]
### Issue Description

For my app I use a singlePage app with TopTabs.
I've set the leftButton to the side-menu, and I created a rightButton with an ID and an image.
the buttons are displayed as expected, and the side-menu button works as expected (the drawer is being opened).

The problem is, my rightButton isn't firing any event, while my leftButton does.

### Steps to Reproduce / Code Snippets / Screenshots

navigator buttons definition:

```
navigatorButtons: {
            leftButtons: [
                {
                    id: 'sideMenu'
                }
            ],
            rightButtons: [
                {
                    id: 'search',
                    icon: require('../../images/Nav/search.png')
                }
            ]
        }
```

listener code, lives in the component of my first Tab, called in the componentDidMount:

```
this.props.navigator.setOnNavigatorEvent((event) => {
            Log('ActionsPage onNavigatorEvent', event);
            if (event.type === 'NavBarButtonPress') {
                if (event.id === 'search') {
                    this.props.navigator.showModal({
                        screen: 'modals.search'
                    })
                }
            }
        })
```

log from when the side-menu button is pressed:

```
03-20 16:47:49.289  1893 21187 I ReactNativeJS: 'ActionsPage onNavigatorEvent', { navigatorEventID: 'screenInstanceID6_events',
03-20 16:47:49.289  1893 21187 I ReactNativeJS:   id: 'sideMenu',
03-20 16:47:49.289  1893 21187 I ReactNativeJS:   type: 'NavBarButtonPress' }

```

---
### Environment
* React Native Navigation version: 2.0.0-experimental.241
* React Native version: 0.42
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): OnePlus 2, android 6, debug app

**Comment by guyca** [comment]
Hey @Temereru I'm not able to reproduce. Still happening?
