### ISSUE TITLE
Use react-native-navigation in an existing iOS project

### ISSUE THREAD

**Issue by shuiboshi** [wix/react-native-navigation#887]
I Use react-native-navigation in an existing project, like the following code.
```
 NSURL *jsCodeLocation;
    jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
    
    RCCNavigationController *navi = [[RCCNavigationController alloc]initWithProps:@{
                                                                                    @"component":@"Default",
                                                                                    }
                                                                         children:nil
                                                                      globalProps:nil
                                                                           bridge:
                                     [[RCTBridge alloc] initWithBundleURL:jsCodeLocation moduleProvider:nil launchOptions:nil]];
    [self presentViewController:navi animated:YES completion:^{
        
    }];
```

 But the Component in JavaScript can not use props, shown as undefine。so ,the props.navigator can't use,too.

**Comment by DanielZlotin** [comment]
This doesn't look right.. what version are you using?

**Comment by DanielZlotin** [comment]
Current implementation changes window.rootViewController so it will be a pain to add it to an existing native app. Maybe it's better to return a viewcontroller that you can just add to your exsiting app using a modal, like in your example. I'll try to squeeze it into the next major release

**Comment by shuiboshi** [comment]
thanks.it's mean that we can't use RCCNavigationController directly,now? @DanielZlotin

**Comment by DanielZlotin** [comment]
You can try..But we don't support it officially

**Comment by shuiboshi** [comment]
ok。maybe i don't use it correctly 。
