### ISSUE TITLE
PushNotification eventListener not working with react-native-navigation

### ISSUE THREAD

**Issue by CarbonC** [wix/react-native-navigation#89]
I tried to place my listener on route or on a tab (tabview) and the result is the same: no event is launched while I'm sure the listener is "on" (it starts on ComponentWillMount and is removed on ComponentWillUnmount)...

**Comment by guyca** [comment]
Can you lease provide more information? code snippets would be helpful. I assume you've encountered this issue on iOS, yes?

**Comment by CarbonC** [comment]
Yes it was on IOS... My code just do something like:
componentWillMount() {
    PushNotificationIOS.addEventListener('localNotification', this._onLocalNotification);
  }

  componentWillUnmount() {
    PushNotificationIOS.removeEventListener('localNotification', this._onLocalNotification);
  }

_onLocalNotification(){
      console.log("Hey!");
    );

And I don't receive the console.log(). I have no error message, nothing :/

**Comment by CarbonC** [comment]
This issue is very problematic since you can't work with pushnotification on a project using react-native-navigation. Do you know how difficult it is to fix, and when will it be good?
