### ISSUE TITLE
Run in iPhone is very slow, but smooth in emulator of osx

### ISSUE THREAD

**Issue by musicode** [wix/react-native-navigation#90]
very very slow, i has no idea, help please....

**Comment by CarbonC** [comment]
More information please? Did you disabled debug, on which IPhone version and os are you running?
Are you sure it's navigation fault?

**Comment by musicode** [comment]
not matter dev is true or false, the result is the same.

```
http://myip:8081/index.ios.bundle?platform=ios&dev=false
```

my iPhone is 5s, ios version is 9.3.2

i use react-native-router-flux before, but i think it's slowly a little, so i found this project, i spend two days to change the code, today, when i run it in iPhone, i can't believe it......

sorry for my english, i wish you know what i said....

**Comment by musicode** [comment]
my react-native version is 0.28.0

**Comment by CarbonC** [comment]
I don't have a real iphone here to test, but can you try with the example (or example-redux) on your iphone to see if the problem is really the navigation?

**Comment by musicode** [comment]
![image](https://cloud.githubusercontent.com/assets/2732303/16341418/71836cd6-3a5f-11e6-9050-d58ea4174f9a.png)
i found this, i dont't know why

**Comment by musicode** [comment]
i found the reason, because i want to reset navbar button, so i add the code:

```javascript
// componentDidUpdate() {
  //   this.updateNavBarButton()
  //   if (this.componentDidUpdateExtend) {
  //     this.componentDidUpdateExtend()
  //   }
  // }
```

i comment it, app become quickly.
