### ISSUE TITLE
Can RNPM be used?

### ISSUE THREAD

**Issue by calvinmikael** [wix/react-native-navigation#91]
Can RNPM or its replacement, react native link, be used safely instead of manually linking the project?

**Comment by roysG** [comment]
Why the question is closed?
Can we use it?

**Comment by guyca** [comment]
Currently we don't support RNPM, simply because we don't use it, I don't think there's someone here at the team who's familiar with RNPM. Once v2.0 is released, we'll be more open to PR's in this matter.

**Comment by roysG** [comment]
Ok.
Second thing,
You wrote on your wiki page that facebook is not maintain their navigation plugin any more and you attach link.

But i clicked on the link and the link is not active any more.
Maybe facebook start maintain their navigation plugin?

**Comment by guyca** [comment]
From what I know, the guys at Facebook are not satisfied with the current Navigation api and are experimenting in ways to improve upon it, [NavigationExperimental](https://github.com/facebook/react-native/issues/6184) for example which you're probably familiar with. 
When we first got into react native here at Wix, We quickly noticed the sub par performance of `Navigator` and knew it was a deal breaker. We First wanted to submit PR's to improve `Navigator`. One of the guys here that started work on it and contacted the guys at Facebook. He got the impression from them that their current navigation solution will be deprecated in the future. Maybe it's still maintained, we didn't bother checking.

That was a short history lesson on how RNN was born, hope I answered your question.

**Comment by guyca** [comment]
Here's an example for Navigator's problematic performance: [Memory is not released after scene popped in Navigator #4740](https://github.com/facebook/react-native/issues/4740)
You can try it your self, create a screen with an image (each screen displays a different image), and just keep pushing screens/scenes. After about 10 screens your app will run out of memory and crash. 👍

**Comment by ex3ndr** [comment]
RNPM is a very simple and useful thing to support and dramatically simplifies integration. I hope you will support.

**Comment by Kureev** [comment]
Hi there! RNPM (now `react-native link`) can do most of the work for you, but [these changes](https://github.com/wix/react-native-navigation/blob/master/example/ios/example/AppDelegate.m) should be applied by hand.

Theoretically, it's possible to parse AppDelegate.m code and apply an AST transform to perform required changes automatically, but not sure if someone will invest time in this.

**Comment by guyca** [comment]
Guys if someone has experience with rnpm and can kickstart this effort, please feel free to do so. We'll gladly accept any help with this matter 👍

**Comment by Kureev** [comment]
I'm one of the co-authors of RNPM 😺 . If someone write a script to patch AppDelegate.m, I can hook it up and add appropriate documentation for it.
