### ISSUE TITLE
Deep Link event with extra data

### ISSUE THREAD

**Issue by Jpoliachik** [wix/react-native-navigation#915]
My use case: 
I have a generic picker dialog I display with `showModal`. I populate the picker list with `passProps` and on user completion I need to dismiss the modal and return the selected value to the controller underneath. 

With the current event system, deep linking _almost_ works, except it doesn't allow data in the event object other than `type` and `link`.

Would a different event type be the best solution here? Maybe call it an `Intent`?
Alternatively, I could add a "data" property onto the existing deepLink event, but that slightly distorts the intended `deepLink` function. 

Any other ideas?

**Comment by agumack** [comment]
@Jpoliachik you can using  passProps callback function. it supported now.

**Comment by Jpoliachik** [comment]
@agumack oh sweet, didn't know that was supported now. Thanks!
