### ISSUE TITLE
Custom splash screen.

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#916]
Hello,

I'm trying to create a simple splash screen that pretends to be my first react component.

This is what I want my splash screen to look like:
<img src="https://cloud.githubusercontent.com/assets/3070948/24228232/a535b9de-0f7b-11e7-81f7-f59da00a9eec.jpg"  width="200">

and this is what my first react component looks like:
<img src="https://cloud.githubusercontent.com/assets/3070948/24228242/b4da2640-0f7b-11e7-9ff9-2d2d1fcd94d6.png"  width="200">

So far so good, I added this code to my `AppDelegate.m`:

```Objective-C
-(void)showSplashScreen
{
  // CGRect screenBounds = [UIScreen mainScreen].bounds;
  UINavigationController *splashView = nil;
  
  NSString* launchStoryBoard = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"UILaunchStoryboardName"];
  if (launchStoryBoard != nil)
  {//load the splash from the storyboard that's defined in the info.plist as the LaunchScreen
    splashView = [[NSBundle mainBundle] loadNibNamed:launchStoryBoard owner:self options:nil][0];
    
    id<UIApplicationDelegate> appDelegate = [UIApplication sharedApplication].delegate;
    appDelegate.window.rootViewController = splashView;
    [appDelegate.window makeKeyAndVisible];
  }
  
}
```

it works because my `SplashScreen.xib` looks like this:

![screen shot 2017-03-23 at 03 52 33](https://cloud.githubusercontent.com/assets/3070948/24228340/2f3e2e90-0f7c-11e7-823f-7d7ea769595d.png)

The only problem I have is a flickering right between the splash screen fading away and the first react component being mounted.

It happens when this [line runs](https://github.com/wix/react-native-navigation/blob/cc94e023a1b501084d9f2adf08fd7c9e50f18b2d/ios/RCCManagerModule.m#L209).

Here's a gif demonstrating the problem (you can see the problem right AFTER the green debugging line that says `Loading from localhost` on the top of the screen goes away):
<img src="http://g.recordit.co/gbKQkPcbfE.gif" />

Please advise!

Thanks!

**Comment by tomauty** [comment]
You can give `rootViewController` a `loadingView`. See below

```objective-c
  UIViewController *rootViewController = [UIViewController new];
  
  // Add loading view
  UIImageView* loadingView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"Splash"]];
  loadingView.contentMode = UIViewContentModeScaleAspectFill;
  loadingView.frame = self.window.frame;
  
  rootView.loadingViewFadeDelay = 0.5;
  rootView.loadingViewFadeDuration = 0.5;
  rootView.loadingView = loadingView;
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
```

**Comment by SudoPlz** [comment]
@tomauty how do I get access to the rootView?

**Comment by SudoPlz** [comment]
Anyone? I don't think react-native-navigation gives us access to `rootView` does it?

**Comment by jbolter** [comment]
Why was this closed?  Is there an iOS solution?  We're trying to solve the same issue with various splash screen plugins and/or rolling out own solution but this flash is hard to resolve with react-native-navigation.

**Comment by jbolter** [comment]
@SudoPlz I think I solved my white flash.  If you set the ```screenBackgroundColor``` property on the navigation style you can get rid of the white flash.  There are also some other iOS only options that I'm going to play with such as the ```screenBackgroundImageName ``` and ```rootBackgroundImageName```

https://wix.github.io/react-native-navigation/#/styling-the-navigator

**Comment by SudoPlz** [comment]
I'm going to take a look at this tomorrow, thanks @jbolter !
