### ISSUE TITLE
[Question] use disableOpenGesture selectively

### ISSUE THREAD

**Issue by tolu360** [wix/react-native-navigation#922]
### Issue Description

This is more of a question than an issue. Please, is it possible to disable open gesture for the `drawer` on selected screens and not app-wide using the `disableOpenGesture` flag? If possible, can I get a quick guide on how? Thanks

---
### Environment
* React Native Navigation version: 2.0.0-experimental.240
* React Native version: 0.42.0
* Platform(s) (iOS, Android, or both?): Both
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by enterline** [comment]
+1 on this. I would definitely like to know if this is possible.

**Comment by kis25791** [comment]
@tolu360 @enterline  Currently I think we have to do some workaround. In my side, I have a workflow like SplashScreen => Login => Main App. If I registered sidemenu at beginning then in my splash screen and Login screen, I was able to open SideMenu by gesture. So I decided to **startSingleScreenApp** without **Sidemenu** at first and after done with Login, I **startSingleScreenApp** again and add **Sidemenu** as drawer.
This workaround will prevent Open Gesture in Splash screen and Login Screen, but you will lost page animation transition from Login => Main app. But I think it was acceptable till now.

**Comment by tolu360** [comment]
Thanks @kis25791, I am doing the exact flow you described but I have a slightly different issue here - it seems to be peculiar to IOS, for my main app, I **startTabBasedApp** with a **Drawer** and all is fine. My issue is just the views in my app which have **Swipeable ListViews**, the drawer seem to interfere with those lists and they are un-swipeable unless I **disableOpenGesture** altogether, after which I can now swipe open my **Swipeable ListViews**.

**Comment by kis25791** [comment]
@tolu360 I think if you enable Swipeable ListView and Drawer, it will cause a conflict gestures in app. Did you try with different directions for both? Such as Drawer will move from left to right and your Swipeable List View will move from right to left, etc.

**Comment by tolu360** [comment]
@kis25791 yes, I did. I have the drawer on the left (swiping right to open) and the listview swipes to the left to open, yet I cannot get the swipeable listview to work properly with the drawer on IOS.

**Comment by Fenwil** [comment]
@guyca do you have any thoughts on this? thanks!

**Comment by dabit1** [comment]
Hi! Any news about it? In most cases, the app has login system and we need to disable drawer depends on the screen. Also there are cases where some screens should not open the drawer.

Thanks!

**Comment by kristikristo** [comment]
+1 for this

**Comment by Fenwil** [comment]
Guys we've found a hacky solution with @jpgarcia and I made this repo to show it.
It will work until a real solution for the issue arrives:
[https://github.com/Fenwil/rnn-disable-drawer](https://github.com/Fenwil/rnn-disable-drawer)

Imagine you have a Login screen and you don't want the drawer on that particular Screen

1. This is my main entry pointing to a `Splash` screen
```javascript
import { Navigation } from 'react-native-navigation'

import { registerScreens } from './screens'
registerScreens()

Navigation.startSingleScreenApp({
  screen: { screen: 'Splash' },
  drawer: {
    left: { screen: 'Drawer' },
  },
})
```

2. The `Splash` screen will not render anything it will be used to call `navigator.showModal` to render our `Login` screen as a modal. Why? Because modals are on top of everything and my guess is that the event for the drawer is below. And also will pass through `props`  a `logIn` method because from the `Login` screen itself we cannot use `resetTo` or any other method because will not work correctly.
```javascript
import { Component } from 'react'
import PropTypes from 'prop-types'

class Splash extends Component {
  static navigatorStyle = {
    navBarHidden: true,
    screenBackgroundColor: '#FFFFFF',
  }

  componentDidMount() {
    const { navigator } = this.props
    navigator.showModal({ screen: 'Login', animationType: 'none', passProps: { logIn: this.logIn } })
  }

  logIn = () => {
    const { navigator } = this.props
    navigator.resetTo({ screen: 'Home', animated: true })
    navigator.dismissModal({ animationType: 'slide-down' })
  }

  render() {
    return null
  }
}

Splash.propTypes = {
  navigator: PropTypes.shape({
    resetTo: PropTypes.func,
    showModal: PropTypes.func,
    dismissModal: PropTypes.func,
  }),
}

export default Splash
```
3. This is the code for the `Login` screen and if you try it by yourself you will see that the Drawer cannot be used
```javascript
import React, { Component } from 'react'
import { StyleSheet, View, Text, Button } from 'react-native'
import PropTypes from 'prop-types'

class Login extends Component {
  static navigatorStyle = {
    navBarHidden: true,
    screenBackgroundColor: '#FFFFFF',
  }

  render() {
    const { logIn } = this.props
    return (
      <View style={styles.container}>
        <View style={styles.texts}>
          <Text>This is a modal screen</Text>
          <Text>Here there's no drawer!</Text>
        </View>
        <Button onPress={logIn} title="Go to Home screen" />
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },

  texts: {
    marginBottom: 20,
  },
})

Login.propTypes = {
  navigator: PropTypes.shape({
    resetTo: PropTypes.func,
    showModal: PropTypes.func,
    dismissModal: PropTypes.func,
  }),
}

export default Login
```
4. If we click on the button `"Go to Home screen"` we will use the `logIn` method sent from the `Splash` screen and will send us to our `Home` screen that now we have a Drawer to use.
```javascript
import React, { Component } from 'react'
import { StyleSheet, View, Text, Button } from 'react-native'

class Home extends Component {
  static navigatorStyle = {
    navBarHidden: true,
    screenBackgroundColor: '#FFFFFF',
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.texts}>
          <Text>This is a normal screen</Text>
          <Text>Here you have a drawer!</Text>
        </View>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },

  texts: {
    marginBottom: 20,
  },
})

export default Home
```

**Comment by raunaqss** [comment]
@Fenwil thanks so much for your solution—really helped me with my productivity today.

**Comment by kyle-ssg** [comment]
Well, using a modal to prevent drawer gestures is obviously a hack. I guess the main difference is that by using navigator.setDrawerEnabled you can use standard screens.

Saying that, I suppose it depends on your app. If you wanted the drawer to be persistent across your entire app excluding one or two screens then perhaps using modals in those cases is correct.

**Comment by Fenwil** [comment]
You're welcom @raunaqss. Yes for the time I wrote that there was no `setDrawerEnabled` yet.
