### ISSUE TITLE
How can I cover the tabbar by a new push view?

### ISSUE THREAD

**Issue by wangwailok** [wix/react-native-navigation#923]
Is there anyway to make a new push view cover the tabbar?
I can't see any API or even the official example have a way to achieve that.

---
### Environment
* React Native Navigation version: 2.0.0
* React Native version: 4.2.0
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 6 / Both

**Comment by Crash--** [comment]
you can use `showModal()`

**Comment by CodeXtinction** [comment]
on the pushed screen

static navigatorStyle = {
        tabBarHidden: true,
  };

**Comment by wangwailok** [comment]
thank you guys!
