### ISSUE TITLE
Compatibility with RN 0.43

### ISSUE THREAD

**Issue by sexykodo** [wix/react-native-navigation#924]
Hi, I'm facing a compatibility problem with RN 0.43-rc.x

In this RN version com.facebook.react.devsupport.DevSupportManager is no longer available,
wich breaks
```
private void replaceInDevSupportManager(DevCommandsHandlerProxy proxy) {
        DevSupportManager devSupportManager = (DevSupportManager)
        ReflectionUtils.getDeclaredField(reactInstanceManager, "mDevSupportManager");
        ReflectionUtils.setField(devSupportManager, "mReactInstanceCommandsHandler", proxy);
    }
```
 method in JsDevReloadListenerReplacer.java

I tried to switch DevSupportManager with DevSupportManagerImpl, it builds, but
I get a "Unable to connect with remote debugger" when i try to debug.

React Native Navigation version: 2.0.0-experimental.256
React Native version: 0.43-rc.3 
ANDROID DEBUG

**Comment by Crash--** [comment]
see  #903

**Comment by sexykodo** [comment]
Yep, with that change the solution builds, but I still get "Unable to connect with remote debugger".
It could be something else though..

**Comment by pqkluan** [comment]
+1

**Comment by mdjnewman** [comment]
As the CI build failed in #903 and it hasn't been updated in 15 days I've opened #990.

**Comment by guyca** [comment]
Hey guys, .300 should be compatible with RN 0.43
