### ISSUE TITLE
Is there any way to set the tab label dynamically after release-v.256?

### ISSUE THREAD

**Issue by gameboyVito** [wix/react-native-navigation#925]
Before the `@2.0.0-experimental.256`, I can use `setTitle` to set both of title of navbar and label of tabbar at the same time. However, I found that in the 256 release, the `setTitle` method now can only change the title of navbar. Could you please add a new method like `setLabel` so that I can only set the label dynamically?

**Comment by gameboyVito** [comment]
I know it's the change of #897, can you provide a new method like `setLabel`? For example, I use the I18n to change the language dynamically, as far as I know, the only way to rerender the tab is to set the label by using `setTitle`. So, it would be great to have this method if someone wants to change the label of tab in the runtime.

**Comment by aaafly** [comment]
Same issue here, I want to dynamically translate my labels.

**Comment by baijunjie** [comment]
Same issue here, I want to dynamically translate my labels.

**Comment by Frexuz** [comment]
+1

**Comment by alburdette619** [comment]
+1

**Comment by danielang** [comment]
+1

**Comment by FlyOceanFish** [comment]
+1 i want to change the text color at any time whether it is or not selected

**Comment by danielang** [comment]
@FlyOceanFish with this already merged PR #2215 you should be able to change the tabbutton label
I've also made a PR for dynamic tabbar styles but it was causing some issues, which are now fixed on android. But my mac is broken since last week, so I cant fix the issues on iOS.

**Comment by vuadenthuj1** [comment]
+ 1

**Comment by brainbrain34** [comment]
+1

**Comment by mralj** [comment]
+1

**Comment by dammy95** [comment]
+1

**Comment by danielang** [comment]
This issue was an issue of the v1 version of rnn and was resolved by #2215.  
Documentation can be found here: [Screen API > setTabButton(params = {})](https://wix.github.io/react-native-navigation/#/screen-api?id=settabbuttonparams-)  

@guyca: I think we should close this issue and open a new one for v2.
