### ISSUE TITLE
Preserve navigation bar height after hiding status bar

### ISSUE THREAD

**Issue by kolking** [wix/react-native-navigation#931]
### Issue Description

It's a quite common case to show a modal or a lightbox with status bar hidden. When you show a modal using "slide" animation (or show semi-transparent lightbox), you can see the navigation bar in the parent view jumps up once the status bar collapsed. It would be really great to have an option to hide status bar while keeping the navigation bar's height - preserve the space taken by status bar.

![example](https://cloud.githubusercontent.com/assets/4656448/24316191/8cf006aa-1105-11e7-9c04-687760b37074.gif)

**Desired behavior after hiding status bar:**

![image](https://cloud.githubusercontent.com/assets/4656448/24322090/57468ed6-1176-11e7-9b55-3d0492e80aa4.png)

Another minor issue is that the status bar animates from black to white after it becomes visible.

### Steps to Reproduce / Code Snippets / Screenshots

Hide status bar when navigation bar stays visible.

---
### Environment
* React Native Navigation version: 2.0.0-experimental.233
* React Native version: 0.41.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone, iOS8+, Both

**Comment by AlimovSV** [comment]
+1

**Comment by kolking** [comment]
Tested on the latest v2.0.2314, the issues are not resolved.

**Comment by fivenp** [comment]
Is there any chance we could re-open this issue and maybe "fix" the behaviour? (even by maybe just passing a prop?)

**Comment by sajsanghvi** [comment]
dang I really need a solution for this
