### ISSUE TITLE
Navigation Events not firing on Android, iOS is fine.

### ISSUE THREAD

**Issue by timoschlueter** [wix/react-native-navigation#940]
### Issue Description

I have an issue with the navigation events on my app running on Android. I am working on an app thats supposed to run on both Android and iOS. I started developing the App on iOS and had no issues with navigation at all.

I use navigation events, which i hook up in the constructors of my screens to track the screen the user is currently looking at. 

On iOS, the following code works well and logs "Screen appeared" onto the console. On Android however, the event does not seem to be triggered.

### Steps to Reproduce / Code Snippets / Screenshots

On the screen, hook up the event listener in the constructor as [described here](https://github.com/wix/react-native-navigation/wiki/Screen-API#setonnavigatoreventcallback).

```
constructor(props) {
        super(props);
        this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
}

onNavigatorEvent(event) {
        switch(event.id) {
        case 'willAppear':
            break;
        case 'didAppear':
            console.log("Screen appeared");
            break;
        case 'willDisappear':
            break;
        case 'didDisappear':
            break;
        }   
    }
```
---
### Environment
* React Native Navigation version: 2.0.0-experimental.256
* React Native version: 0.42.3
* Platform(s): Android
* Device info: Device (Moto G4, Android 7.0) / Simulator (Android 6.0)

**Comment by Kraignos** [comment]
Same issue here with:
* Navigation version: 2.0.0-experimental.260
* RN: 0.41.0

**Comment by odemolliens** [comment]
+1

**Comment by knapeto** [comment]
Any solution?

**Comment by shafy** [comment]
Same here

**Comment by guyca** [comment]
Hey guys
I've never encountered such an issue, could someone upload an example project where this bug reproduces?

**Comment by shafy** [comment]
Hi @guyca no, I am not. And also it's weird that it only exists on Android. So when I first show the screen the event is fired, but it's not fired when I open a modal on top of it (it should fire 'willDisappear' etc. and then when I dismiss the modal it should again fire 'willAppear' etc. - it least that's what it does on iOS).

My code:
1) I start a single screen app:
```
Navigation.startSingleScreenApp({
  screen: {
    screen: 'humbot.BootScreen',
    title: 'Welcome',
    navigatorStyle: {
      navBarHidden: true
    },
    portraitOnlyMode: true,
  }
});
```

In BootScreen, I check if user is logged in and start a new single screen app with the ArticleFeed:
```
componentDidMount() {
    getLoginState().then( (startRoot) => {
      switch(startRoot) {
      case 'welcome':
        Navigation.startSingleScreenApp({
          screen: {
            screen: 'humbot.Welcome',
            title: 'Introduction',
            navigatorStyle: {
              navBarHidden: true,
            },
            portraitOnlyMode: true,
          }
        });
        break;
      case 'feed':
        Navigation.startSingleScreenApp({
          screen: {
            screen: 'humbot.ArticleFeed',
            title: 'Feed',
            navigatorStyle: {
              navBarHidden: true,
            },
            portraitOnlyMode: true,
          }
        });
        break;
      }
    })
  }
```

And now in the ArticleFeed, the correct event fires. However, if I open a modal from ArticleFeed it doesn't fire on Android (works well on iOS).
The method that opens the modal is defined in ArticleFeed, but passed down to a child component and fired from there. Could that be a problem? If yes, why does it work on iOS?

**Comment by guyca** [comment]
@shafy Can you please upgrade rnn and check again? I believe this issue was fixed in 1.1.5x

**Comment by shafy** [comment]
@guyca yess - it works now. Thanks!

**Comment by xinlangzi** [comment]
@guyca 

I did not see the version 1.1.5x. Can you tell me how to ? The latest version "react-native-navigation": "^1.1.365";

**Comment by alandmonte** [comment]
I'm facing the same issue with "react-native-navigation" "^1.1.457"

**Comment by guyca** [comment]
Hey guys, I'm closing the issue as v1 is not supported anymore.
