### ISSUE TITLE
How to style status bar to transparent

### ISSUE THREAD

**Issue by pronevich** [wix/react-native-navigation#941]
This code doesn't work. Mabe we need to add something like  `statusBarTranslucent`  to API

```javascript
static navigatorStyle = {
    navBarHidden: true,
    statusBarColor: 'transparent',
    statusBarTextColorScheme: 'light',
  }
```
---
### Environment
* React Native Navigation version: v2.0.0-experimental.261
* React Native version: 0.43.0-rc.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android 6.0

**Comment by laiyifeng77** [comment]
looking forward to it
