### ISSUE TITLE
ListView issue with topTabs + navBarHideOnScroll

### ISSUE THREAD

**Issue by davendesai** [wix/react-native-navigation#942]
### Issue Description

When combining the `navBarHideOnScroll: true`, `topTabs` on Android, and a ListView, the expected behavior would be similar to the Youtube app where the titleBar is collapsed on scroll but the tabs remain. While this does indeed occur, the bottom of the ListView is also raised (by what looks to be the same height as the titleBar) leaving a gap at the bottom of the view.

This may be a result of ScollView(s) requiring a bounded height in order to work (via the Facebook docs) but I'm not familiar enough with the underpinnings to be sure (or to know a workaround).

If someone can point me in the correct direction that would be greatly appreciated! 😃 

#### App Entrypoint
```
Navigation.startSingleScreenApp({
    screen: {
	screen: 'example.AndroidWrapper',
	topTabs: [
	    {
		screenId: 'example.MainScreen',
		title: 'Main'
	    },
	    {
		screenId: 'example.OtherScreen',
		title: 'Other'
	    }
	]
    }
});
```

#### AndroidWrapper screen navigationStyle
```
static navigatorStyle = {
    navBarHideOnScroll: true,
}
```

#### MainScreen render method
```
render() {
    <ListView
        dataSource={this.state.dataSource}
        renderRow={this._renderRow} />
}
```

##### Collapsed titleBar as expected
![screen shot 2017-03-27 at 5 18 42 pm](https://cloud.githubusercontent.com/assets/4980883/24383400/8a46f072-1311-11e7-9fa2-d3d672cfe69a.png)

##### Unfortunately whitespace left on bottom of ListView when collapsed
![screen shot 2017-03-27 at 5 18 51 pm](https://cloud.githubusercontent.com/assets/4980883/24383438/afb6efa6-1311-11e7-861b-15b12246065c.png)

---
### Environment
* React Native Navigation version: 2.0.0-experimental.261
* React Native version: 0.42.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Genymotion Emulator Android 7.0

**Comment by jnsone11** [comment]
I'm able to reproduce the problem. Help is appreciated.

**Comment by guyca** [comment]
hmm, setting `drawUnderTabBar: true` will prevent this, until this is fixed.

**Comment by davendesai** [comment]
Maybe it's an emulator issue, but unfortunately setting `drawUnderTabBar: true` isn't resolving the issue for me. Still see a white bar when scrolling the content upwards AKA a simple ScrollView with `backgroundColor: 'red'` as below:

![screen shot 2017-04-17 at 5 03 36 pm](https://cloud.githubusercontent.com/assets/4980883/25109235/256a4fa2-2390-11e7-84b9-2f86c4839b21.png)

**Comment by guyca** [comment]
@davendesai If you can upload an example project where this issue is reproducible, it would help me debug it since I couldn't reproduce it locally.

**Comment by davendesai** [comment]
@guyca [Here](https://github.com/davendesai/react-native-navigation-example) you go! Let me know if you need any more info as well 👍

**Comment by guyca** [comment]
Thanks @davendesai, will get back to you today/tomorrow

**Comment by davendesai** [comment]
Thanks for taking the time to look into it! 😄

**Comment by juancaacuna** [comment]
Hey @davendesai , were you able to get this "white" box gone?
I added the `drawUnderTabBar: true` but still the box is showing and hiding for a second, under the TabBar.

**Comment by davendesai** [comment]
@juancaacuna Yup, managed to test it again today and can confirm the problem is resolved. My 'dummy android wrapper screen' has the following `navigationStyle`:

```
static navigatorStyle = {
    // Collapse the nav (title) bar when scrolling
    navBarHideOnScroll: true,

    // Avoid re-expanding the nav (title) bar when switching tabs
    expendCollapsingToolBarOnTopTabChange: false,

    // wix/react-native-navigation issue #942
    drawUnderTabBar: true
  }
```

This is with the latest release of [wix/react-native-navigation](https://github.com/wix/react-native-navigation) from the v1 branch. I believe it was 1.1.76. Hope that helps.

**Comment by JohnProg** [comment]
Good afternoon, I'm getting the same error with react-native-navigation 1.1.407. There is a white view on the bottom of the screen, even I set the following:
```
 // Collapse the nav (title) bar when scrolling
    navBarHideOnScroll: true,

    // Avoid re-expanding the nav (title) bar when switching tabs
    expendCollapsingToolBarOnTopTabChange: false,

    // wix/react-native-navigation issue #942
    drawUnderTabBar: true
```

 Please help.
