### ISSUE TITLE
Align text in navigatorStyle

### ISSUE THREAD

**Issue by DanielGM** [wix/react-native-navigation#944]
### Issue Description

Hi, im having issues trying to align in the center my text in static navigatorStyle, i read (https://github.com/wix/react-native-navigation/wiki/Styling-the-navigator) and couldn't find a property for it.

### Environment
* React Native Navigation version: 2.0.0-experimental.256
* React Native version: 0.42.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, 4.2.2

**Comment by guyca** [comment]
Hey there
If you update to latest version, you can specify `navBarTitleTextCentered: true` 👍

**Comment by Coolerfall** [comment]
I use `setScreenTitleBarTitle: true` in navigatorStyle and it dose center the title, but when I use `navigator.setTitle()`, the text is not aligined center anymore, I have to invoke `navigator.setStyle({ navBarTitleTextCentered: true })` again to center title.
