### ISSUE TITLE
iOS Status Bar

### ISSUE THREAD

**Issue by shonnamartell** [wix/react-native-navigation#95]
I can't seem to show the status bar no matter what. What option shows the status bar on top, I don't want it hidden.

**Comment by guyca** [comment]
All of the available styling options are mentioned in the docs.
I think this is the one you need:
```js
  navBarHidden: false, // make the nav bar hidden
```
https://github.com/wix/react-native-navigation#styling-the-navigator

**Comment by shonnamartell** [comment]
I read the docs and already knew about this option, I have tried setting it to true and false, with no different result. I still do not see my status bar that, this is why I posted here to see if anyone had come across the issue before.
