### ISSUE TITLE
Pop gesture and left navigation item(pop back) in a custom-define way.

### ISSUE THREAD

**Issue by toureek** [wix/react-native-navigation#951]
### Issue Description
It is an awesome repo for navigation in react-native. Thanks for the open-source world.

I have a question which contains popGesture and NavigationItem(PopBack).
There're two pages in App. One is MainPage, the other one is InfoPage.
In the condition I push to lnfoPage from MainPage and typing typing typing the content in InfoPage, when I click the LeftNaviItem(Back) in InfoPage, I want to Alert user something and Do Not Leave InfoPage before Click SubmitButton.
But the result is that Alert shows up and the page pop back to MainPage automatically.

Actually, I also need to forbid popGesture in iOS in the react-native way just like the objective-c native code in this special page:
self.navigationController.interactivePopGestureRecognizer.enabled = NO;

Can any one can give me some help for this?
Here's the part of my source codes. Many Thanks.

In InfoPage.js

static navigatorButtons = {
    leftButtons: [{
      // icon: require('../../img/navicon_back.png'),
      id: 'popBack'
    }]
  };

  constructor(props) {
    super(props);
    this.props.navigator.setOnNavigatorEvent(this.onNavigatorEvent.bind(this));
  }

  onNavigatorEvent(event) {
    if (event.id === 'willDisappear' && event.type === 'ScreenChangedEvent') {
       console.log('do sth. right here when current page will pop back');
       Alert.alert('Attentions', 'You have sth. must be saved before leave');
       return;
    }
  }

---
### Environment
* React Native Navigation version: @latest
* React Native version: @latest
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?):  Simulator, iOS 10

**Comment by yungobiwan** [comment]
How did you solve this problem?
