### ISSUE TITLE
Blank screen on Android

### ISSUE THREAD

**Issue by jp928** [wix/react-native-navigation#953]
###Blank screen on Android

[Get blank screen on Android (https://github.com/wix/react-native-navigation/issues/197)]

### Compile without any error message, javascript file load fine. javascript Console.log information can be seen from logcat.
Just get blank screen.
![screenshot_1490873521](https://cloud.githubusercontent.com/assets/659612/24502265/c079e6d4-1598-11e7-8e4b-46697979a3f2.png)

```adb shell input keyevent 82``` no response as well

---
### Environment
* React Native Navigation version:  2.0.0-experimental.262
* React Native version: 0.42.3
* Platform: Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator api 23, Android 6.0

**Comment by guyca** [comment]
I think you either missed an installation step in Android or in Js.

**Comment by jp928** [comment]
@guyca You are absolutely right !
After comparing with the example code, I found the android start the app in a different manner as ios:

in ios, we do 

```javascript
class App extends Component {
  startApp() {
    Navigation.startTabBasedApp({...tabs})
  }
}
```
whereas in android, we directly do

```
 Navigation.startTabBasedApp({...tabs})
```

**Comment by guyca** [comment]
App doesn't need to extend `Component` since it's not related to react. Maybe you forgot to call `new App().startApp()` in `index.android.js` ?

**Comment by andfs** [comment]
I`m facing this problem in android too, if I start with a startSingleScreenApp everything works fine

/```
* eslint-disable no-unused-vars */
import React, { Component } from 'react';
import { View, Platform } from 'react-native';
import { Navigation } from 'react-native-navigation';
import { registerScreens } from './screens';
import { Provider } from 'react-redux';
import store from './store';
import Icon from 'react-native-vector-icons/Ionicons';

registerScreens(store, Provider);

var agoraIcon = null;
var agendaIcon = null;
var estabelecimentosIcon = null;
var promocoesIcon = null;

Icon.getImageSource('ios-alarm-outline', 30).then((agora) => { 
	Icon.getImageSource('ios-calendar-outline', 30).then((agenda) => { 
		Icon.getImageSource('ios-home-outline', 30).then((estabelecimentos) => { 
			Icon.getImageSource('ios-pricetag-outline', 30).then((promocoes) => { 
				promocoesIcon = promocoes;
				estabelecimentosIcon = estabelecimentos;
				agendaIcon = agenda;
				agoraIcon = agora;

				const 

				Navigation.startTabBasedApp({
					tabs: [{
							label: 'Agora',
							screen: 'agora',
							title: 'Agora',
							icon: agoraIcon
						},
						{
							label: 'Agenda',
							screen: 'agenda',
							title: 'Agenda',
							icon: agendaIcon
						},
						{
							label: 'Estabelecimentos',
							screen: 'estabelecimentos',
							title: 'Estabelecimentos',
							icon: estabelecimentosIcon
						},
						{
							label: 'Promocoes',
							screen: 'promocoes',
							title: 'Promocoes',
							icon: promocoesIcon
						}
					],
					animationType: Platform.OS === 'ios' ? 'slide-down' : 'fade',
					tabsStyle: {
						tabBarBackgroundColor: '#003a66',
						tabBarButtonColor: '#ffffff',
						tabBarSelectedButtonColor: '#ff505c',
						tabFontFamily: 'BioRhyme-Bold',
					},
					appStyle: {
						tabBarBackgroundColor: '#003a66',
						navBarButtonColor: '#ffffff',
						tabBarButtonColor: '#ffffff',
						navBarTextColor: '#ffffff',
						tabBarSelectedButtonColor: '#ff505c',
						navigationBarColor: '#003a66',
						navBarBackgroundColor: '#003a66',
						statusBarColor: '#002b4c',
						tabFontFamily: 'BioRhyme-Bold',
					},
					drawer: {
						left: { 
							screen: 'drawer'
						}
					}
				});
			});
		});
	});
});
```
