### ISSUE TITLE
showLightBox not working on Android

### ISSUE THREAD

**Issue by jp928** [wix/react-native-navigation#959]
### this.props.showLightBox({...params}) shows exception on Andorid

![screenshot_1490997684](https://cloud.githubusercontent.com/assets/659612/24571008/5a773a58-16ba-11e7-8556-4312c214e950.png)

---
### Environment
* React Native Navigation version: 2.0.0-experimental.262
* React Native version: 0.42.3
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?):Simulator/Android 6.0

**Comment by guyca** [comment]
Starting work on this today

**Comment by guyca** [comment]
Added LightBox support in experimental-273

**Comment by Ehesp** [comment]
Hey @guyca I'm on 277 and it's crashing my app. Log trace is as follows:

![image](https://cloud.githubusercontent.com/assets/842078/24803818/531e7e62-1ba4-11e7-990f-ffb343acb99e.png)
