### ISSUE TITLE
Blank when debug mode is on

### ISSUE THREAD

**Issue by vzhen** [wix/react-native-navigation#963]
### Issue Description
When react native `debug JS remotely` is on. App is blank and no react native menu at all.
Tested on official example, have the same issue
---
### Environment
* React Native Navigation version: 2.0.0-experimental.265
* React Native version: "0.42.3"
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Android Emulator

**Comment by guyca** [comment]
Hey @vzhen 
I think this is regression was introduced in 42.3. Maybe go back to previous RN version until this we will address this.

**Comment by vzhen** [comment]
Which version should be fine?
0.42?

**Comment by Liroo** [comment]
0.42 is fine with me

**Comment by vzhen** [comment]
Same issue on 0.42

**Comment by jp928** [comment]
I encounter this issue because of javascript issue.
In the example code, the Navigator is initialised in a function startApp() and this function must be called from constructor. Please make sure you have called the function explicitly somewhere.

**Comment by vzhen** [comment]
@jp928  I didn't see `startApp()` in the example. Could you show me your code?

**Comment by jp928** [comment]
@vzhen
just follow what they did from here

https://github.com/junedomingo/movieapp?files=1

**Comment by vzhen** [comment]
@jp928 Not working, I'm on Android. 
Seems like they have different way to initial navigation in android and ios.

**Comment by jp928** [comment]
what they did for ios working in android as well. please notice the syntax in index.ios.js as well.

**Comment by jp928** [comment]
After you have startApp() in the constructor, you need create a instance from index.android.js by
``` JavaScript
New App()
```

**Comment by vzhen** [comment]
Ok,  it suddenly works. i didn't change anything.
It very unstable.

**Comment by vzhen** [comment]
I enable hot reloading. Now it working.

**Comment by GlisboaDev** [comment]
I have the same problem here, and my constructor call `startApp()` right away.
```
constructor(props) {
    super(props);
    this.startApp();
}
```
Everything works normally if I'm not on debug mode, but as soon as I enable it I get blank screens on navigating. 
Am I missing anything?

**Comment by vzhen** [comment]
@GlisboaDev  Try enable both debug js and hot reloading then RR and react-native run-OS. It works for me.

**Comment by GlisboaDev** [comment]
@vzhen I tried it already, not working same way. Have been changing some configs to see if I get the cause, but nothing so far. I'll post an update if I figure something out

**Comment by Ehesp** [comment]
Also happening here. Problem is once it's opened the dev menu doesn't appear again meaning the only way to get out of debug mode is to clear the app data.

Using Redux too if that matters...

**Comment by vzhen** [comment]
@Ehesp Yes, u r right. Using with redux causes app keep crashing.

**Comment by ywongweb** [comment]
Same problem here, hope this gets fix soon. Was really impressed by the examples and looking to migrate a project to this router, but can't because of no debugging.

**Comment by guyca** [comment]
@vzhen Can't reproduce on RN 0.43 and RNN .300

**Comment by Crash--** [comment]
Are you developing on Linux? Since on my Mac everything works as expected both on iOS & Android. But as soon as one of my colleague try to debug on Linux, we have the blank screen :(

**Comment by Ehesp** [comment]
I'm on mac. I'll setup a new RN project later with Android.

**Comment by vzhen** [comment]
@Crash--  On Windows, android emulator here.

**Comment by Ehesp** [comment]
Okay so for me it's working out of the box, with Redux too. However when the app unexpectedly crashes it's not able to reconnect to the debugger. I have another package installed which causes the app to crash when attempting to opening debugger, so I see this issue every time.

The logs from logcat are:

![image](https://cloud.githubusercontent.com/assets/842078/25073469/810827dc-22df-11e7-9670-0fbe4ba1487d.png)

**Comment by Ehesp** [comment]
Hi Guys,

I made a repo to reproduce this: https://github.com/Ehesp/wix-react-navigation-debugger-issue

I've found the following results. In general it seems that when debugger is active promises don't seem to be resolving as we'd expect. This may also fall into the event emitters too.

The following code doesn't work (condensed for clarity):

## A) getImageSource not resolving

```javascript
const iconsLoaded = () => {
    const promises = [];

    Object.keys(icons).forEach((iconName) => {
        promises.push(FontAwesome.getImageSource(iconName, 24);
    });
    
    return Promise.all(promises).then((sources) => {
        Object.keys(icons).forEach((iconName, idx) => iconsMap[iconName] = sources[idx]);
        console.log('Promise All Resolved');
        return Promise.resolve();
    });
};
```
The log `Promise All Resolved` is never shown.

B) `Promise.all` doesn't seem to resolve

```
const promise = () => {
    return new Promise((resolve) => {
      return resolve();
    });
};

const promises = [promise, promise];

console.log('Attempting to resolve all...')

return Promise.all(promises).then(() => {
  console.log('All promises resolved');
  return Promise.resolve();
});
```
The log `Promise All Resolved` is never shown.

C) Returning a promise directly works, but doesn't chain

```
runPromise = () => {
  console.log('Resolving promise...');
  return new Promise((resolve) => {
    console.log('Promises resolved');
    return resolve();
  });
}

export default class App {
  constructor() {
    return runPromise()
      .then(() => {
          console.log('Start App');
          this.startApp();
      });
  }

  startApp() {
    ...
  }
}
```

These work fine when debugger is disabled.

**Comment by Ehesp** [comment]
cc @DanielZlotin 

After speaking with @guyca some more, combined with the fact this only happens on Android, I think the general thought line was that the current implementation of the debugger isn't detaching properly, which is causing the events (promises etc) to get resolved into a black hole.

**Comment by anhtuank7c** [comment]
@Ehesp do you have any alternate solution?

**Comment by dabit1** [comment]
I have the same issue. I use Linux & Android & RN 0.43.3. When I enable remote debugger then my app crashes and does not work (blank screen) until I uninstall it and re-install it.

**Comment by Liroo** [comment]
If you didn't notice, the debugger is in active mode when app is blank (while debugger is on and hot reloading off). The only problem seems to be how the app is launching.

Actually, the only way to debug an app (android) is when the hot reload is active...

**Comment by Amurmurmur** [comment]
Same issue here :/
How can I disable the debugger before the app starts?
Is there a PR for that?

**Comment by Liroo** [comment]
@Amurmurmur  re - install app ;)

**Comment by Amurmurmur** [comment]
@Liroo 
I've tried multiple times :/
Whats more I've switched to react-navigation :/

**Comment by gaguirre** [comment]
Any update on this? @DanielZlotin

**Comment by joonhocho** [comment]
Related https://github.com/wix/react-native-navigation/issues/1397 ? I created fix for #1397, but it's for v2. Maybe it can fix v1 as well.

**Comment by Liroo** [comment]
This only solution I've found actually is to press the home button and return to the app. It works well and is the fastest way :)

**Comment by diruuu** [comment]
Any update on this?

**Comment by anhtuank7c** [comment]
My solution is write my own navigation =))

**Comment by alejoasotelo** [comment]
any news? 
RN: 0.47.0
Windows 10 with Android Emulator.

**Comment by jay1337** [comment]
any news ?

I have the same issue when my app start while remote debugging has been turned on.
If my app crash while using remote debugger, I need to reinstall the app or clear its data, load the app, login (since all data has been cleared) and then turn on the debugger.

**Comment by escaton** [comment]
@DanielZlotin have you had a chance to take a look at this issue?

**Comment by DanielZlotin** [comment]
v1 is not prioritized for bugs which not directly impact production. all dev effort goes into v2. there is not reason to keep asking `any news?`. we will update as soon as we can

**Comment by perrosnk** [comment]
I am experiencing the same issue

**Comment by tmaly1980** [comment]
@DanielZlotin I fail to understand what the sense is in not prioritizing development mode. How exactly will apps ever get into production if the developer runs into issues in the development process? This 'low priority' cost me half of my day. I can understand not prioritizing a version when the next version is already in production and the old one is being deprecated, but I suspect we're not quite there.

**Comment by herarya** [comment]
+1

**Comment by aMarCruz** [comment]
For me, too many lost days, returning to react-navigation :(

**Comment by havinhthai** [comment]
+1

**Comment by tmaly1980** [comment]
If you press the home button, then go back to the app, it fixes the issue. Or, you can return 'hot loading' on and that'll work too.

**Comment by jay1337** [comment]
hey !

**Comment by Amurmurmur** [comment]
It is a trend now, everyone has included that stale bot into their repos, and issues get left unresolved. 👎

**Comment by Manish3323** [comment]
I have lost my weekend on this. i do not want my Dream Fifa app go in vain .. only 6 days are left for fifa world cup ..please look into it.
Here are the logs : 
`06-10 22:25:02.709 1621-1621/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.bet18, PID: 1621
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bet18/com.reactnativenavigation.controllers.NavigationActivity}: java.lang.NullPointerException: uriString
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6938)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
                                                  Caused by: java.lang.NullPointerException: uriString
                                                     at android.net.Uri$StringUri.<init>(Uri.java:476)
                                                     at android.net.Uri$StringUri.<init>(Unknown Source:0)
                                                     at android.net.Uri.parse(Uri.java:438)
                                                     at com.reactnativenavigation.react.ImageLoader.loadImage(ImageLoader.java:18)
                                                     at com.reactnativenavigation.params.parsers.TabIconParser.parse(TabIconParser.java:19)
                                                     at com.reactnativenavigation.params.parsers.ScreenParamsParser.parse(ScreenParamsParser.java:57)
                                                     at com.reactnativenavigation.params.parsers.ActivityParamsParser.parse(ActivityParamsParser.java:18)
                                                     at com.reactnativenavigation.controllers.NavigationCommandsHandler.parseActivityParams(NavigationCommandsHandler.java:21)
                                                     at com.reactnativenavigation.controllers.NavigationActivity.onCreate(NavigationActivity.java:77)
                                                     at android.app.Activity.performCreate(Activity.java:7174)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030) 
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6938) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) `

**Comment by DanielZlotin** [comment]
1. Is this issue still relevant for v2?
2. Support for remote debugging (not debug mode. These are separate things), in my eyes at least, is a nice-to-have feature at best in it's current form. Remote debugging in react-native works by loading the js bundle remotely from chrome instead of using the bundled native library (JavaScriptCore) from the apk itself. Therefore anything that happens in debug mode can be drastically different than what happens in production. You can (and should) still test your javascript code with jest/mocha separately from the native app, and you should be able to play with the app with *debug mode* (not remote debugging) easily. If not, open a separate issue.
3. @Manish3323 I sympathise with your urgency but this issue must not really be a blocker for you, is it? More importantly there is little to be gained from such a description you copy pasted here. It's useful to no one. If you want to provide a reproducible example you should open a new public repo and paste the *link*. This repo should be as minimal as possible and be compilable and reproduce the problem. Descriptions of this sort will be removed and closed in the future.
4. To the point, if this can be reproduced with the playground app, no more examples (or +1s or "me too"s) needed. PRs are welcome, otherwise, we will fix this as soon as we can. Thank you.

**Comment by DanielZlotin** [comment]
@Manish3323 I know realise your issue is not even related THIS issue. Open a relevant issue with good description please.

**Comment by Manish3323** [comment]
@DanielZlotin there was a thing that i missed while configuring splashActivity on android side. 
The solution given in this  link here worked for me.
https://googleweblight.com/i?u=https://stackoverflow.com/questions/20546703/how-to-fix-white-screen-on-app-start-up/33123963&hl=en-IN#

I think readme  file must be updated.

**Comment by Dgs-asohail4** [comment]
OCTOBER 1 2018.. still same issue

**Comment by zcmgyu** [comment]
On Sat Feb 9 2019 still stuck at debug mode on
