### ISSUE TITLE
Documentation of navigation event types. 

### ISSUE THREAD

**Issue by smooJitter** [wix/react-native-navigation#969]
### Issue Description
Where can I find documentation of the various navigation event types e.g.,

```
event.type == 'DeepLink'
event.type == 'NavBarButtunPress'

```

**Comment by guyca** [comment]
deeplinks: https://wix.github.io/react-native-navigation/#/deep-links?id=deep-links

Regarding the buttonPress events, they only field of value they contain is `id` which is the if you set on the button.
