### ISSUE TITLE
support testId on navigation elements

### ISSUE THREAD

**Issue by DanielZlotin** [wix/react-native-navigation#979]
see https://github.com/wix/detox/issues/12#issuecomment-291499294

**Comment by yogevbd** [comment]
Done for iOS - #2334

**Comment by gundlev** [comment]
Any progress on this in regards to android?

**Comment by guyca** [comment]
@gundlev Can you be more specific? Most elements already in v2 already handle `testId`

At any case, I'm closing this as both platforms are already covered afaik. If an element doesn't support test id lets open issues regarding each element 👍
