### ISSUE TITLE
toggleTabs() can't hide tabbar

### ISSUE THREAD

**Issue by musicode** [wix/react-native-navigation#98]
when keyboard is shown, i want to hide the tabbar

```
this.props.navigator.toggleTabs({
  to: 'hidden',
  animated: true,
})
```

the result is:

![image](https://cloud.githubusercontent.com/assets/2732303/16367015/c3da466e-3c51-11e6-8ded-fb3f24fedc5e.png)

the tabbar is transparent, not hidden.

**Comment by dg92** [comment]
@musicode any success ?

**Comment by guyca** [comment]
@dg92 @musicode You have to set `drawUnderTabBar: true` in that screen's `navigatorStyle`.
This way, when you hide the `BottomTabs` there won't be any margin since the screen is aligned to the bottom of the screen

**Comment by messense** [comment]
@guyca Could you please kindly add this to `toggleTabs` API documentation?

**Comment by alexcoady** [comment]
When I set `drawUnderTabBar: true` I get a white space the size of the hidden tab bar.

![screen shot 2017-04-11 at 20 36 59](https://cloud.githubusercontent.com/assets/1643182/24927363/a92cfd1a-1ef6-11e7-9616-7b9b6773eb96.png)

**Comment by guyca** [comment]
What version are you using?

**Comment by skyworld** [comment]
` 	static navigatorStyle = {
        tabBarHidden: true,
        //navBarHidden:true
    };`

**Comment by liushigit** [comment]
`this
      .props
      .navigator
      .push({screen: 'my.ItemDetail', navigatorStyle: {tabBarHidden: true}})
`

**Comment by MarishkaKravchenko** [comment]
drawUnderTabBar: true,
    navBarHideOnScroll: false,

**Comment by jeevankumarkanuganti** [comment]
i want to hide the tabbar 
this.props.navigator.toggleTabs({
  to: 'hidden',
  animated: true,
})

but still getting blank space
