### ISSUE TITLE
How to animate navigator text?

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#986]
How is it possible to animate navigator text. Sorry if I am spamming questions here! I am migrating from Navigation Experimental at the moment and I make notes when I notice that I can't do something with this library :)

**Comment by guyca** [comment]
Hey @henrikra 
Right now, the title can't be animated. I suggest that if you have a screen with a simple `navBar` with only a title or a few buttons - you use some RN component which gives you more control over the title.
Whenever you want to use a custom navBar component, set `navBarHidden: 'true'` in the `navigatorStyle` of the relevant screens. This will hide our `navBar`.

We're adding support for custom react views in the `navBar`. There's already a pending PR for iOS, hope Android will follow soon.
