### ISSUE TITLE
Possible to add navigator buttons dynamically?

### ISSUE THREAD

**Issue by henrikra** [wix/react-native-navigation#987]
Is it possible to add navigator buttons dynamically?

**Comment by guyca** [comment]
https://wix.github.io/react-native-navigation/#/screen-api?id=setbuttonsparams-

**Comment by henrikra** [comment]
@guyca Looks like adding button dynamically works only on Android with that function. Not on iOS according to my testing

**Comment by guyca** [comment]
@henrikra As far as I know it work on iOS as well (we use it a lot in our apps)
