### ISSUE TITLE
RN 0.43 and fbsdk crash on android

### ISSUE THREAD

**Issue by tiempham** [wix/react-native-navigation#988]
Hi all
I build Rn app in android. Link app to wix react navigation and fbsdk was fine but app crash when run with no error. Any idea? (https://github.com/wix/react-native-navigation/issues/197)]

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT - It will be extremely helpful]

---
### Environment
* React Native Navigation version: Last version
* React Native version: Rn0.43
* Platform(s) (iOS, Android, or both?): android
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by guyca** [comment]
Hey there
RN 0.43 is not supported yet, though #990 should address that
